### ISSUE TITLE
Add more packages to monorepo

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#10]
- [ ] - trezor-link
- [ ] - hd-wallet
- [x] - trezor-blockchain-link
- [ ] - trezor-utxo-lib
- [ ] - trezor-connect
- [x] - trezor-ui-components
- [x] - trezor-flags
- [x] - rollout
- [x] - connect-explorer

**Comment by ZdenekSL** [comment]
Related to #314
