### ISSUE TITLE
Subtitle in item should have different font size / colour

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10000]
![Screenshot 2023-11-17 at 11 22 22](https://github.com/trezor/trezor-suite/assets/84183817/a9b0dbcc-f72f-4b59-989d-28cdd77232d1)

**Comment by bosomt** [comment]
**QA OK**

tested on Android 13 - Nothing phone 1
 23.11.1 (591)
f3c6929 - [develop] - Fix\/discovery fixes (#10061)
