### ISSUE TITLE
Arrows in switcher should disappear when the switcher is opened

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10010]
![Image](https://github.com/trezor/trezor-suite/assets/84183817/e2e78826-3167-4b1b-9a7d-ba256bbdaca5)

**Comment by bosomt** [comment]
**QA OK**

tested on Android 13 - Nothing phone 1
 23.11.1 (591)
f3c6929 - [develop] - Fix\/discovery fixes (#10061)
