### ISSUE TITLE
Delete device accounts on disconnect

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10015]
In the first milestone we don't have support for remember mode. So after disconnecting a device, all it's accounts should be wiped from the persisted memory.

## Acceptance criteria
- If the user disconnects device all it's accounts are removed.
- If user starts the app with some persisted accounts in memory and the specific device is not connected, the accounts are removed during the app init.

**Comment by bosomt** [comment]
**QA OK**

Nothing phone 1 - Android 13
23.11.1 (601) 
9e363ff - [develop] - feat(suite-native): bootloader error alert (#10127)
