### ISSUE TITLE
Multiple background update processes

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#10027]
**Describe the bug**
It's possible to start several update processes.

**Info:**

    "environment": "desktop",
    "suiteVersion": "23.10.1",
    "commitHash": "6c8d061f7305947b0270a2560e4cc65d1f7ded27",

**How to reproduce**

1. Open outdate Suite
2. Agree to update
3. Reload the app with **⌘R**
4. Agree to update
5. Repeat

**Expected behavior**
Previous background update is stopped.

**Screenshots**

https://github.com/trezor/trezor-suite/assets/45338719/56412cd3-0073-478d-8679-9b74c39e2085

**Comment by matejkriz** [comment]
closing as duplicate https://github.com/trezor/trezor-suite/issues/7740
