### ISSUE TITLE
Missing links in the buttons

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10023]
Please adjust the content of the switcher menu items (see Figma: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=3987%3A21458&mode=design&t=mNQxJzRbSkapkjDD-1) 
1. Learn the basics - there is icon missing and the link should be: https://trezor.io/learn
2. Read the docs > It should be "Explore Trezor shop" and there is icon missing. The link: https://trezor.io/

**Comment by bosomt** [comment]
**QA OK**

develop-TrezorSuite 23.12.2 (425)
