### ISSUE TITLE
Discovery assets issues

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10038]
- [x] When we start the discovery, the loader of the assets stop showing the loader after 4 coin, then it seems that the discovery has ended but the assets are still loading
- [x] When user has some assets in portfolio tracker and connects the Trezor, the portfolio balance merge the assets for some time and displays portfolio balance for both - look at the video (00:01:25): https://drive.google.com/file/d/1vp6mVwqom17pVrX8WyLsZNdHtPt_L87B/view?usp=drive_link

**Comment by PeKne** [comment]
Fixed by #9992 and #10061
