### ISSUE TITLE
Trezor Suite crashes when you navigate to `Settings/Coins` section with uninitialized device 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10035]
**Describe the bug**
Trezor Suite crashes when you navigate to `Settings/Coins` section with uninitialized device 
Same results with Trezor model T

**Steps to reproduce:**
1. Connect new or empty device
2. Skip onboarding
3. navigate to Settings/Coins

**Info:**
 - Suite version: desktop 23.11.5 (4566edae060459a5645f0ddabde574b998d53c53)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.11.5 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1  undefined (revision null)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/8ee0bd52-2f14-449c-adbc-d912ac218157

**Comment by STew790** [comment]
Just to add, this is not new, it is happening since 23.9.3. (23.8.1. was OK)

**Comment by komret** [comment]
Looks like this is the bug we saw in Sentry: https://github.com/trezor/trezor-suite/pull/9968 cc @mroz22

**Comment by matejkriz** [comment]
yes, and this is an attempt to get better log https://github.com/trezor/trezor-suite/pull/9968

**Comment by matejkriz** [comment]
But in Sentry I see reports from `/switch-device#/true`, `/web/firmware`...
https://satoshilabs.sentry.io/issues/?groupStatsPeriod=auto&project=5193825&query=is%3Aunresolved+%22version+string+is+in+wrong+format%22+version%3A23.11.5&referrer=issue-list&statsPeriod=90d

**Comment by matejkriz** [comment]
ok, I see `/settings/coins` too https://satoshilabs.sentry.io/issues/4661693032/?project=5193825&query=is%3Aunresolved+%22version+string+is+in+wrong+format%22+version%3A23.11.5&referrer=issue-stream&statsPeriod=90d&stream_index=4

**Comment by STew790** [comment]
**QA OK**
Going to `settings/coins` with uninitialized device works just fine, no crash present. (Desktop and web)

**Info:**
 - Suite version: web 23.12.1 (9c59daf2803153743eb1c2036c14f3cd25e0769d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2B1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33
