### ISSUE TITLE
New MetadataLabeling design 

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#10055]
After a discussion with Ondra, we still agree that for now we keep the look of the labelling component.

The `Badge` component does not have a loading state, so perhaps we can keep using `Button`, just gotta make is smaller and use badge's dimentsion. Let's not create a new `Button` size yet because this might be the only use case. 

<img width="640" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/936ddabf-967b-462b-b41b-529ae909c36e">

_Originally posted by @dahaca in https://github.com/trezor/trezor-suite/pull/9942#pullrequestreview-1747789382_

**Comment by peter-sanderson** [comment]
It was already implemented here https://github.com/trezor/trezor-suite/commit/f04450b6b702a3e3731d570cba3ea6ae21e83833
