### ISSUE TITLE
Inform user that device is in Bootloader mode

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10069]
If user connects the device in bootloader, we show him message that in order to continue in bootloader, he must connect to Trezor Suite
User can't continue using the app

Figma: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=5022%3A17612&mode=design&t=KKa4u3i8BGcFgXDw-1

**Comment by bosomt** [comment]
**QA OK**

Nothing phone 1 - Android 13
23.11.1 (601) 
9e363ff - [develop] - feat(suite-native): bootloader error alert (#10127)
