### ISSUE TITLE
Device info + Unsupported device connected

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10060]
**Device info page:**
Current:: Get accessories @ Trezor Shop
New: Get swag for your device @ Trezor Shop

**Unsupported Trezor connected**
Error message - unsupported FW: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=4064%3A24657&mode=design&t=vhogq6wFQ1Gcu0jX-1 
Error message - no FW installed: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=4068%3A24715&mode=design&t=vhogq6wFQ1Gcu0jX-1

**Comment by mnuky** [comment]
@PeKne there is one copy wrong:
Instead of: How to update firmware
Should be: Follow these steps

**Comment by PeKne** [comment]
I will prepare fixup.

**Comment by PeKne** [comment]
Fixed by #10127
