### ISSUE TITLE
Add input field to transaction import

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#10066]
**Design:** Let's discuss feasibility with @Hermez-cz please, we'll keep it simple together.

**Spec:**
When Sending a transaction, it can be imported from a CSV file which can be dropped into the modal window or selected from files.
Sometimes, users have the transaction copied in their paste bin, please add an input field for them to be able to paste the copied transaction in without having to create a file first.

Current implementation:
![image](https://github.com/trezor/trezor-suite/assets/88533514/92fb77ca-331d-43af-95f3-db06c4de86e6)

Deprecated Trezor Wallet solution for more context:
![image](https://github.com/trezor/trezor-suite/assets/88533514/3ec698e0-7253-448b-aa2d-c2d3149051d6)

**Comment by szymonlesisz** [comment]
related issue https://github.com/trezor/trezor-suite/issues/5739

**Comment by szymonlesisz** [comment]
pls check [this pull request](https://github.com/trezor/trezor-suite/pull/10331)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.1.1 (c4cf80383d5f554ff118ba507b743074e73216d4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.5 regular (revision f4d3a7456afaa850f9651d31ddc9d7e4b68ab7b8)
 - Transport: BridgeTransport 2.0.33
