### ISSUE TITLE
Support interaction-less update

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#10067]
Please simplify the Device FW update/reinstallation flow according to the diagram and especially the tech specification from @matejcik  below.

![Image](https://github.com/trezor/trezor-suite/assets/88533514/a2f95352-add5-473a-8367-0d497ca4a284)

From [here](https://github.com/trezor/trezor-firmware/issues/2919#issuecomment-1723398691). Please discuss details with @matejcik.

> interaction-less update RFC:
> 
> 1. Firmware stage
> 
> host sends FirmwareUpdate that contains exactly the header, i.e., concatenated vendor header + firmware header
> 
> firmware verifies that:
> 
> the headers are valid (signatures match etc)
> vendor matches the currently installed one
> version is strictly higher than the current one
> if this fails, Failure is returned. (if the operation is actually what the user wants, they will need to go to bootloader to do it)
> 
> if it is OK, Trezor displays a prompt:
> "Upgrade firmware to version 2.7.9?"
> (I don't think we need to mention the vendor here, given that it is forced to be the same as current -- but we can)
> 
> when the user confirms, firmware sends Success and jumps to bootloader
> 
> host must wait until the device disappears from the bus and a bootloader reappears
> 
> 2. Bootloader stage
> 
> bootloader detects that a header was sent from firmware
> 
> bootloader verifies that:
> 
> the headers are valid
> vendor matches the currently installed one
> vendor is strictly higher than the current one
> if this fails, an error screen is displayed, asking the user to replug device (?)
> (alternately, we could either (a) continue booting as if nothing happened, or (b) jump to bootloader menu as if normal jump-to-bootloader)
> 
> if header is OK, bootloader goes to "waiting for host" screen. this should be rendered in black instead of bootloader blue
> 
> host sends FirmwareErase message indicating that it is ready to update firmware
> 
> if the host sends something else here, like UnlockBootloader or WipeDevice, we can probably go to that flow? it seems to make the impl simpler, and I can't see any problem in allowing that.
> bootloader acts as if it already received the header and jumps to verification. we need to inject an automatic response into this step -- this is already done when is_new comes out as sectrue, so that should not be a problem
> 
> firmware upgrade process continues as normal (with black progress bar)
> 
> For bonus points:
> 
> Make the interval between erasing firmware and writing first sector shorter.
> The ideal would be:
> 
> receive & validate header
> erase first sector
> write header at start of first sector
> erase rest of sectors
> proceed to ask for first chunk, then write chunk into rest of sector
> this shortens the interval when no valid header is present in flash to minimum (i.e., if we allow recovery from corrupted firmware, the only way to lose the header is if the power goes out at exactly the right moment)
> 
> unfortunately I believe it further complicates the logic of chunk handling. but maybe we could untangle and refactor the current code so that this is achievable?
> 
> cc @mroz22 for Connect-side review

**Comment by STew790** [comment]
**QA OK**
All findings are here https://www.notion.so/satoshilabs/Interactionless-fw-update-d2c4c0f5382f479a8b0ba81932f423e8.

**Info:**
 - Suite version: desktop 24.5.2 (1ca8b8063fd7028d1fe242db41caa31c0a1f7d5a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
