### ISSUE TITLE
Transaction fee rates does not match desktop and blockbook fee rates

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10070]
**Describe the bug**
Transaction fee rates does not match desktop and blockbook fee rates.
I was able to reproduce it on production 23.11.2 and develop 23.11.1 versions.

**Info:**

-   Mobile Suite Version: 23.11.2 production and 23.11.1 develop 
-   OS: iOS and Android 

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/31506317/1fba39fc-ef7a-44f7-b917-0136cd3fa432)
![telegram-cloud-photo-size-4-5992421466567720734-y](https://github.com/trezor/trezor-suite/assets/31506317/a360f737-9431-4e94-ac16-1a303dc68afd)
![image](https://github.com/trezor/trezor-suite/assets/31506317/f2332505-855b-43f4-9785-c8aeb86d57f2)
![image](https://github.com/trezor/trezor-suite/assets/31506317/518f6f68-c5f9-44c0-8f91-e55f423bf686)

**Comment by bosomt** [comment]
**QA NOK**

tested on this account `zpub6rszzdAK6RuafeRwyN8z1cgWcXCuKbLmjjfnrW4fWKtcoXQ8787214pNJjnBG5UATyghuNzjn6Lfp5k5xymrLFJnCy46bMYJPyZsbpFGagT`

34 vs 57.5

<img width="623" alt="Screenshot 2024-01-22 at 10 25 07" src="https://github.com/trezor/trezor-suite/assets/31506317/b60115c0-e3f6-4c0f-a62a-6bf57b3c43fa">

![telegram-cloud-photo-size-4-5870500075317346090-y](https://github.com/trezor/trezor-suite/assets/31506317/499a3cc5-320a-49b9-9e97-ad48febac013)


https://btc2.trezor.io/tx/1977ac5fee52828772ce9b4a79176988f09db3e458a3fcdfd21c8a4c233ad5a1

**Comment by Hannsek** [comment]
Maybe the mistake is on the desktop side?

**Comment by bosomt** [comment]
@Hannsek mistake on Firebase side :)
downloaded latest version but it downloaded version from friday :)

**Comment by bosomt** [comment]
**QA OK**

tested on multiple BTC transactions 

24.2.0 (698)
374f4c0 - [develop] - feat(suite-native): android face recognition (#10733)
