### ISSUE TITLE
Message with informing about uninitialised Trezor wrong appearance

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10076]
Steps to reproduce:
First bug: 
1. Connect the Trezor device which is not set up
2. Message with informs that this device has not been set up appears
3. Click Eject
4. Then Disconnect the device
5. Message appears again

Second bug:
1. Connect the Trezor device which is not set up
2. Message with informs that this device has not been set up appears
3. Disconnect the device
4. Message is still there but - it should disappear when device disappears

Check the video: https://drive.google.com/file/d/1NHYaaB03gajA4uE9T1YcLZ_LVCDwX1VN/view?usp=drive_link

**Comment by juriczech** [comment]
Relates to https://github.com/trezor/trezor-suite/issues/10084

**Comment by mnuky** [comment]
can it be related to this issue, too? https://github.com/trezor/trezor-suite/issues/10107

**Comment by PeKne** [comment]
Yes, I think that PR #10109 should fix this as well. But it is not merged yet.

**Comment by bosomt** [comment]
**QA OK**

Nothing phone 1 - Android 13
23.11.1 (601) 
9e363ff - [develop] - feat(suite-native): bootloader error alert (#10127)
