### ISSUE TITLE
Portfolio tracker in Android - missing Sync button on dashboard

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10073]
There should be "button" to Sync my coins on dashboard of portfolio tracker in Android. It is missing, see the printscreen:

![Image](https://github.com/trezor/trezor-suite/assets/84183817/0233c429-27cc-4921-a401-e3879afa671d)

**Comment by juriczech** [comment]
@mnuky According to design, this is correct. The button was there and when discovery was implemented, it was removed to be according to design

@juriczech then there is bug in design :) Please add it there

**Comment by juriczech** [comment]
@mnuky Can you please provide some info about how the button should look like? I will add the same button that's present in the empty state, if that is correct
![image](https://github.com/trezor/trezor-suite/assets/36101761/f6a10649-ff6e-47bb-b5ab-0ee14d751d61)

Same as we have for iOS:
![Image](https://github.com/trezor/trezor-suite/assets/84183817/9a08ff3b-cd2d-4c29-a3d1-1212b45d22f6)
