### ISSUE TITLE
Log screen change to Sentry

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#10087]
We should log screen change to Sentry (with omitted screen params because of privacy). This should help us track random crashes if they are specific to some screen(s) or something.

We can use some Sentry context or log or maybe [Sentry Tracing feature](https://docs.sentry.io/product/sentry-basics/concepts/tracing/) will be best.

**Comment by vytick** [comment]
Check parameters for screen tracking? We dont want to track any ids.
