### ISSUE TITLE
Sentry JS source maps in mobile app

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#10080]
It seems that sourcemaps for JS doesn't work both on Android and iOS. This is really unfortunate for debugging.

**Comment by Nodonisko** [comment]
They seems to work now for iOS but not Android.

**Comment by juriczech** [comment]
Reverted (https://github.com/trezor/trezor-suite/pull/10665) due to failing CI. Still needs to be implemented, let's just do this after release to avoid blocking pipelines cc @vytick

**Comment by vytick** [comment]
pausing until expo build exploration is done. This might change the way we do that or even render this issue irrelevant.

**Comment by matejkriz** [comment]
hopefully will be fixed by moving to Expo https://github.com/trezor/trezor-suite/issues/10597
