### ISSUE TITLE
Frozen app: Connect Trezor One without app being opened - app opens automatically but it gets frozen on Splash screen

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#10085]

**Comment by juriczech** [comment]
@Nodonisko This seems like a problem on native layer, is that correct?

**Comment by Nodonisko** [comment]
@juriczech I will take a look but I tested this specific case many times and it worked before.

**Comment by PeKne** [comment]
@mnuky Could you please test this again? I'm unable to reproduce it.

**Comment by mnuky** [comment]
I can't reproduce it anymore, so please close

**Comment by bosomt** [comment]
**QA OK**

- version 23.12.2 (656) 19c6638 - [develop] - Chore\/receive image btc cash (#10414)
- Android 13 - Nothing phone 1
