### ISSUE TITLE
Device connecting screen redirects

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10084]
The connecting device screen should be visible right away, after the device is connected even though that the connection might be unsuccessful.

## Acceptance criteria
- when user connects device, the connecting screen is displayed right away
- when is the device locekd by PIN, redirects to the PIN screen
- if there is error while connecting (unsuported firmware, seedles device, etc.) the error alert is displayed over the connecting screen
- When user disconnects anytime, redirects to the portfolio dashboard (if there are any coins synced) or to the fresh start screen (crossroads)
- After device connects, redirect to dashboard is done and discovery loading is displayed immediately, without empty state being shown before the loader

**Comment by STew790** [comment]
**QA NOK**
- when I disconnect the device while I'm in the settings and "About Suite Lite" , the Suite doesn't recognize this and shows it as connected https://github.com/trezor/trezor-suite/issues/10159
-  ̶w̶h̶e̶n̶ ̶I̶ ̶c̶o̶n̶n̶e̶c̶t̶ ̶T̶S̶3̶ ̶t̶h̶e̶ ̶S̶u̶i̶t̶e̶ ̶L̶i̶t̶e̶ ̶r̶e̶c̶o̶g̶n̶i̶z̶e̶s̶ ̶i̶t̶ ̶b̶u̶t̶ ̶d̶i̶s̶c̶o̶v̶e̶r̶y̶ ̶n̶e̶v̶e̶r̶ ̶f̶i̶n̶i̶s̶h̶e̶s̶ ̶h̶t̶t̶p̶s̶:̶/̶/̶g̶i̶t̶h̶u̶b̶.̶c̶o̶m̶/̶t̶r̶e̶z̶o̶r̶/̶t̶r̶e̶z̶o̶r̶-̶s̶u̶i̶t̶e̶/̶i̶s̶s̶u̶e̶s̶/̶1̶0̶1̶4̶4̶ not really an issue, my bad.

**QA OK**
- when user connects device, the Suite Lite starts right away
- After device connects, redirect to dashboard is done and discovery loading is displayed immediately, without empty state being shown before the loader
- when is the device locekd by PIN, redirects to the PIN screen
- if there is error while connecting (unsuported firmware, seedles device, etc.) the error alert is displayed over the connecting screen
![Screenshot_2023-12-01-08-35-53-029_io trezor suite develop](https://github.com/trezor/trezor-suite/assets/48477147/7103ccb2-3028-40d8-b8d4-fbbfdea0f7c8)
![Screenshot_2023-12-01-08-33-18-351_io trezor suite develop](https://github.com/trezor/trezor-suite/assets/48477147/8c9a2036-5203-4dd2-a29c-37a0186ebd01)

**Comment by STew790** [comment]
The [issue](https://github.com/trezor/trezor-suite/issues/10159) mentioned above was resolved, approving.
