### ISSUE TITLE
Translations blob handling with firmware

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-suite#10099]
Some `Suite`-related information about upcoming firmware translations:
- the handling will be similar to `ETH definitions` - `Suite` will not have to create any data, the whole signed binary/blob will be hosted on `trezor.io` --- with variables being the `language` (`cs`/`fr`), `version` (`2.6.3`) and `model` (`TT`/`TR`)
- creation, signing and uploading of the blob will happen outside of `Suite` - via `trezorlib` and other tools --- so `Suite` could just stream the blob into the device without having to know much about it

Supported models:
- currently, `T1` translations are not supported, and probably will not be, at least right now

Content of translations blob:
- it contains all the translations strings, but also font data --- therefore each model (`TT` vs `TR`) has different fonts, therefore different blobs

Data integrity:
- translations data are signed, and device will reject them when signature validation fails

Versioning:
- translations will be versioned according to the firmware version they belong to - e.g. firmware `2.6.4` will only accept translations of version `2.6.4` --- and reject all others when tried to load

New protobuf messages:
- one to start the process - `ChangeLanguage` - and then two exchanged in messaging driven by device - `TranslationDataRequest` and `TranslationDataAck`

https://github.com/trezor/trezor-firmware/blob/grdddj/fw_translations/common/protob/messages-management.proto#L182-L211

Trezorlib handling:
- initiating the language change by sending `data_length` - when 0, that will reset language to `english`, when positive, device will start requesting data in chunks (max 1024 bytes)

https://github.com/trezor/trezor-firmware/blob/grdddj/fw_translations/python/src/trezorlib/device.py#L66-L84

Getting the language from the device:
- what was already possible before - reading `language` string from `Features` --- `en-US` when English, otherwise the abbreviation like `cs` or `fr`

Firmware updating process:
- when the user with loaded translations updates firmware, it would be nice to offer him an update of the translations blob as well (there is a chance that the translations got changed, or new strings were added)
- device may show something like `Translations update needed` on the device homescreen, but it may be done automatically after firmware update in `Suite`

**Comment by Hannsek** [comment]
> when the user with loaded translations updates firmware, it would be nice to offer him an update of the translations blob as well (there is a chance that the translations got changed, or new strings were added)

This should be ideally done automatically together with fw update. So that user won't even know that the translation blob was updated. The issue regarding this is that user would have to confirm "installing" the translation blob. We can, however, do it so that by approving fw update, user also approves update of translation blob.

**Comment by mroz22** [comment]
Maybe consider renaming fields according to the same convention as with firwmare update? 
consider differences `data_offset` vs `offset`. `data_length` vs `length`. Also `FirmwareUpload` vs `TranslationDataAck`
these 2 are basically the same thing and we could possibly write it with less code 🤔 

```
"ChangeLanguage": {
            "fields": {
                "data_length": {
                    "rule": "required",
                    "type": "uint32",
                    "id": 1
                },
                "show_display": {
                    "type": "bool",
                    "id": 2
                }
            }
        },
        "TranslationDataRequest": {
            "fields": {
                "data_length": {
                    "rule": "required",
                    "type": "uint32",
                    "id": 1
                },
                "data_offset": {
                    "rule": "required",
                    "type": "uint32",
                    "id": 2
                }
            }
        },
        "TranslationDataAck": {
            "fields": {
                "data_chunk": {
                    "rule": "required",
                    "type": "bytes",
                    "id": 1
                }
            }
        },
```

firemware update
```
"FirmwareErase": {
            "fields": {
                "length": {
                    "type": "uint32",
                    "id": 1
                }
            }
        },
        "FirmwareRequest": {
            "fields": {
                "offset": {
                    "rule": "required",
                    "type": "uint32",
                    "id": 1
                },
                "length": {
                    "rule": "required",
                    "type": "uint32",
                    "id": 2
                }
            }
        },
        "FirmwareUpload": {
            "fields": {
                "payload": {
                    "rule": "required",
                    "type": "bytes",
                    "id": 1
                },
                "hash": {
                    "type": "bytes",
                    "id": 2
                }
            }
        },
```
