### ISSUE TITLE
Hide Exchange for bitcoin-only firmware

### ISSUE THREAD

**Issue by FreeWall** [trezor/trezor-suite#10092]
**Describe the bug**
Users with Bitcoin-only firmware in their devices still see all trade options, including alt-coins in Exchange, which has no use for them.

**Expected behavior**
Hide Exchange tab in Trade section and Trade box for all bitcoin-only firmware devices.

![image](https://github.com/trezor/trezor-suite/assets/12121074/91f23c33-f9f2-4445-889b-88e056cdf7e9)
![image](https://github.com/trezor/trezor-suite/assets/12121074/af528f99-233e-412b-aa91-835af68ba4b6)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.12.1 (9ec6ac5438d7a952abcbbdc049bf729a47d4e039)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.12.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 bitcoin-only (revision 1f693d3561c375661563970e066f678590abc19c)
 - Transport: BridgeTransport 2.0.33
