### ISSUE TITLE
Device manager animations

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10091]
At the current state, if the user opens the switcher, it just appears on the screen without any animation. Same for closing it.

## acceptance criteria
- when is the device manager opened/closed there is a similar animation as we have implemented for the `BottomSheet`

## Implementation proposal
- [How to Make a Bottom Sheet with React Native Reanimated](https://www.youtube.com/watch?v=lYYiuXcTnnE&pp=ygUicmVhY3QgbmF0aXZlIGJvdHRvbXNoZWV0IGFuaWFtdGlvbg%3D%3D) this new reanimated API could be easy to use

**Comment by bosomt** [comment]
**QA OK**

- version 23.12.2 (656) 19c6638 - [develop] - Chore\/receive image btc cash (#10414)
- Android 13 - Nothing phone 1
