### ISSUE TITLE
Incorrect info about device in Lite app when device is used in mobile web Suite

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10104]
**Describe the bug**
Incorrect info about device in Lite app when device is used in mobile web Suite.
 - See video https://www.youtube.com/shorts/pggU_IL-tgU
- when device is in passphrase dialogue Lite app reports device as not set up and app icons disappears

**Info:**

- Android 13 and Nothing phone 1 - 23.11.1 (597) develop version

**Screenshots**
![telegram-cloud-photo-size-4-5996903767452270005-y](https://github.com/trezor/trezor-suite/assets/31506317/8bec9448-278d-4517-8870-2f95101ef1bb)
![telegram-cloud-photo-size-4-5996903767452270006-y](https://github.com/trezor/trezor-suite/assets/31506317/aaa46234-42ef-4339-a439-89c47b02b6d1)

**Comment by STew790** [comment]
**QA OK**
Device is shown as connected and setup.
23.11.1(602)
