### ISSUE TITLE
Missing device name in Device info section

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10103]
**Describe the bug**
Missing device name in `Device info` section as mentioned here https://github.com/trezor/trezor-suite/issues/9184

> Device info:
When user access Device info page, he can see:
    Type of the device
    Name of the device

*Screenshots**
<img width="387" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/d40ecc7a-9798-405c-85a3-fef6d4d76693">
![telegram-cloud-photo-size-4-5996903767452270015-y](https://github.com/trezor/trezor-suite/assets/31506317/f94c35df-0f4a-4397-aa2a-94ebe73e0835)

**Comment by mnuky** [comment]
QA NOK - now there is label of the Trezor device but the type of the device is missing.
It should be:
[Label of the device]
[Type of the Device]
[FW Version]

**Comment by bosomt** [comment]
**QA NOK**

same here :)
350a52f - [develop] - fix(suite-native): device label instead device name (#10111)

**Comment by bosomt** [comment]
**QA OK**

23.11.1 (601) 
9e363ff - [develop] - feat(suite-native): bootloader error alert (#10127)
