### ISSUE TITLE
Update WelcomeLayout

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#10108]
* Update WelcomeLayout colors
* fix content overflowing 
<img width="600" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/0a3401bd-a5f9-4722-ab4e-788d4a65692f"> 

* make the support button `small`
<img width="600" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/27b801be-8df7-4632-b30e-7e9dd58bd9c7">

* ~~move collapsible heading to the left~~ the WebUSB button is there and those changes are out of scope.
<img width="600" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/4078a175-298b-4011-9aad-272354965f2a">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
