### ISSUE TITLE
Check receive address ignores cancellation on device. 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10105]
**Describe the bug**
Check receive address ignores cancellation on device. 

**Info:**

- Android 13 and Nothing phone 1 - 23.11.1 (597) develop version

**How to reproduce**

1. Check address on connected device
2. Press `x` and cancel verification of address device
3. Device closes address dialogue but app still waits

## Acceptance criteria
- if the user cancels the verification address via the device UI, the account receive flow is exited

**Comment by PeKne** [comment]
Will be improved later by implementing #10125
