### ISSUE TITLE
Sanity retest of the message system before prod release

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#10110]
QA didn't test the message system kill switch as they don't have a way to test it. Since this will be a critical bug if user is not able to dismiss feature message, we should retest this on dev just to be sure we won't release unusable app in case there is feature message coming to the mobile app - this would make the app completely unusable.

https://www.notion.so/satoshilabs/Message-system-production-release-c0ac4275461f4755bc9050ff2de57425?pvs=4

**Comment by PeKne** [comment]
Note: please test the implementation of the banner messages as well. It was never production tested as well and since the banners might be non-dismissable, it might also cause a major UI issue.

**Comment by juriczech** [comment]
@PeKne This won't be a production test either though. I just want to make sure the dismiss functionality doesn't create a scenario where the user won't have the app unusable. 

I wonder if we can test it on staging though. That could work I guess.

**Comment by PeKne** [comment]
Yes, just wanted to mention that banners should be tested as well  👍.

I think that you can create push a testing message-system config to develop and then test it with that on the `dev` and `staging` builds.

**Comment by vytick** [comment]
This has been tested on develop and is considered working correctly
