### ISSUE TITLE
Missing function info in Connect 9.1.6 popup

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10122]
**Describe the bug**
Missing function info in new Connect 9.1.6 popup.
Compare screenshots from production and staging.

**Info:**

https://staging-connect.trezor.io/

**How to reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/31506317/4011c05b-5a0d-4fae-8313-e512a2aa08de)
![image](https://github.com/trezor/trezor-suite/assets/31506317/e112cff6-4aa9-4970-941f-ec981916f146)

**Comment by mroz22** [comment]
@karliatto plese check on it.
the info that is supposed to be shown in the left col is loaded defined in `method.info`, which is affected by `method.initAsync`. 

During execution of connect method, we at some point of time wait for result of initAsync, and only after that send info to popup https://github.com/trezor/trezor-suite/blob/develop/packages/connect-iframe/src/index.ts#L113

also what could be affecting this is that we are now loading method itself asynchronously https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/core/index.ts#L306

and last change related to this is that previously, methdo.info was part of popup.handshake, but now it has its own message `POPUP.METHOD_INFO` so popup and iframe can handshake without waiting for some ethereum definitions (for example) to load.

**Comment by bosomt** [comment]
**QA OK**
