### ISSUE TITLE
Debug message in new connect release candidate

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10121]
**Describe the bug**
Every request or response generates `Unknown message` message in browser console.

**Info:**

https://staging-connect.trezor.io/9/

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/31506317/762002b8-5129-4f0a-943e-3a44bfbf76b7)

**Comment by mroz22** [comment]
@karliatto if you could please check on it. its just some leftover we left there. But little investigation would be nice, I would like to know if we are sending some message we don't expect, or it is some message from a 3rd party application/extension that we don't filter out properly.

**Comment by karliatto** [comment]
@bosomt can you reproduce it using the link below:
* https://staging-connect.trezor.io/9.1.6/?trezor-connect-src=https://staging-connect.trezor.io/9.1.6/#/method/getAddress
?

**Comment by bosomt** [comment]
@karliatto yes i can

<img width="1210" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/fff35830-3f7a-47e8-b8bf-f8537b053513">

**Comment by bosomt** [comment]
**QA OK**
