### ISSUE TITLE
Receive verification - show error on cancel

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10125]
At the moment when the user cancels the address verification on the device, the receive flow is exited and user is redirected to the previous screen (bug fix of #10105).

In the future it would be nice to show some understandable UI message informing user what happened.

**Comment by juriczech** [comment]
@PeKne @mnuky Out of scope for this sprint, right? I moved it to january

**Comment by PeKne** [comment]
Yes, out of scope 👍

**Comment by shenkys** [comment]
[Design ready here](https://www.figma.com/file/SzqPKc7fA253syVTeohsoe/Receive?type=design&node-id=215-1637&mode=design&t=fo8Bp7q2JhRKTt1L-11)

**Comment by bosomt** [comment]
**QA OK**

`Address verification cancelled` notification

Android 14 Nothing phone 1 
24.4.0 cd82750
