### ISSUE TITLE
App stucks on the `Connecting` screen

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10142]
After merging of #10109, the app sometimes freezes on the connecting screen on device connection.

**Comment by PeKne** [comment]
The problem occured usually when you connected device, started discovery, but not finished and disconnected again. Then while connecting the device again, it got stuck.

**Comment by bosomt** [comment]
**QA OK**

i was not able to reproduce this issue for some time /it happened to me multiple times with older versions/

- version 23.12.2 (656) 19c6638 - [develop] - Chore\/receive image btc cash (#10414)
- Android 13 - Nothing phone 1
