### ISSUE TITLE
Add Elevation Context

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#10140]
### Issue

Some color tokens have different _elevation variants_. What does that mean? It means that a certain color token has different values when it's displayed on different elevations, aka elevation values of color tokens of a background. Those exist to make sure that the contrast ratio is the best across different surfaces.

Currently we have hardcoded elevation values, e.g. `Button` backgrounds always have elevation 0. It leads to buttons being incorrectly displayed on surfaces with elevation 1 – white surfaces, e.g. `Card` and `Modal`. There is no background visible on the screenshot:

<img width="300" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/77019338-12d4-4e1a-a472-04dc6f214383">

With the correct elevation value it looks like this:

<img width="300" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/ff1c5d77-8f7a-427f-84c7-7a7f51010e07">

### Proposal

Creat `ElevationContext` and a `useElevation` hook to read that context. The hook will be aware of the elevation value of a closest parent and interpolate it into the color token or use a default one — `0`. 

Container components should define their elevation context, like `Modal` and `Card`, and components which are displayed and using an elevatoin variant should use the `useElevation` hook, like `Button` or `Input`.

### temporary solution

Use `onElevation1` as the default, since it does not lead to components beling the same color as containers with `elevation1` as shown on the first screenshot.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
