### ISSUE TITLE
Transactions [EPIC]

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#1014]
#1031 [Wallet] Transactions tab - Empty state
Design: https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6efa120829110bc496f4

#1034 [Wallet] Transactions tab - Bitcoin (like) 
Design: https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6eec1b06a0202b351f1f

#1035 [Wallet] Transactions tab - Ethereum with tokens
Design: https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6ef2883d131f631afcf0

#1036 [Wallet] Transactions tab - Transaction detail modal 
Design: https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa1bdd08fcb816e78ff460

**Comment by ZdenekSL** [comment]
@matejzak Why do we have tokens in transactions if you already have them on the dashboard?

**Comment by sorooris** [comment]
@matejzak answer the question by @ZdenekSL pls, we all need to know :smile_cat:
