### ISSUE TITLE
Inform user when discovery takes too long

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10151]
As a user I would like to be informed that the discovery takes more time than usual in order to know what is happening and won't be confused. 

Acceptance criteria:
1. When it takes ore than 45s to finish discovery of all assets, we display in Graph loading this message: "It takes longer than usual to retrieve balances. This may be caused by an unstable Internet connection."

**Comment by juriczech** [comment]
QA NOK
First step not implemented, second step needs bump from 20s to 45s

**Comment by STew790** [comment]
**QA OK**

Message is shown after more then 45s of discovery time.

Develop 23.12.2 (656) https://github.com/trezor/trezor-suite/commit/19c6638a3225f0c321d88fc6b36b8da18a0bc079
