### ISSUE TITLE
Unknown url reported on Connect staging

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10156]
**Describe the bug**

Unknown url reported on Connect staging when trezor-connect-src not specified.

NOT OK https://staging-connect.trezor.io/9/#/method/getPublicKey
OK         https://staging-connect.trezor.io/9/?trezor-connect-src=https://staging-connect.trezor.io/9/#/method/getPublicKey

**Screenshots**

https://github.com/trezor/trezor-suite/assets/31506317/52c4a0cb-aa67-47a3-b058-5f9c14fa5fe9

**Comment by mroz22** [comment]
it should take validated origin sent from iframe (mapped to config, if possible), imho in handshake message. sorry for that I probably broke it.

**Comment by bosomt** [comment]
**QA OK**
