### ISSUE TITLE
Animated transitions in the app - Connect flow

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10152]
1. Connecting screen - when user clicks on Connect device on empty dashboard, the screens slides from the left. When user clicks on cross, the screen slides to the left. Can we make it slide from the bottom up and when user clicks on cross, slide from the top to bottom?

**Comment by vytick** [comment]
While exploring this, there is also an unwanted possibility to go back via swipe or back button on sync flow:

https://github.com/trezor/trezor-suite/assets/2011829/f26177cf-d896-427d-95a6-d84de098bfdb

**Comment by mnuky** [comment]
@vytick is it Android, right? Because on iOS it's working. It should kill the flow not go back

**Comment by vytick** [comment]
@mnuky Both. On android it is back button (not the cross). On ios it is swipe back

**Comment by mnuky** [comment]
I think it is already broken on Prod so not related to this issue. Can you please create new issue @vytick? Let's fix it separately

**Comment by juriczech** [comment]
@mnuky This is based on mutual discussion with @vytick as I am working with these transitions and we were discussing it today, I offered I will try to make this improvement into this PR as well. If it's more effort than 20 minutes, I won't bother with it but I suspect I know where the issue is and should be fairly easy fix

**Comment by mnuky** [comment]
@juriczech @vytick - aah, ok, let's do it :)

**Comment by juriczech** [comment]
@mnuky Wasn't as easy as I thought, so I skipped it

**Comment by STew790** [comment]
**QA OK**

https://github.com/trezor/trezor-suite/assets/48477147/51c7133f-34bc-48eb-a819-2b1956dba85e

Develop 23.12.2 (656) https://github.com/trezor/trezor-suite/commit/19c6638a3225f0c321d88fc6b36b8da18a0bc079
