### ISSUE TITLE
Device looks connected when I disconnect it while in "About Suite Lite" settings

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#10159]
**Describe the bug**
When I connect my device, wait for the discovery to finish and go to settings and disconnect it there, the app still thinks that the device is connected.

**Info:**

-   Mobile Suite Version: 23.11.1(602)
-   OS: Android 12

**How to reproduce**

1. Connect device
2. Wait for discovery to finish
3. Go to "Settings" and "About Suite Lite"
4. Disconnect your device
5. The Suite doesn't take you back to "Connect my Trezor" screen
6. When you go back to "Dashboard" it shows the device as connected

**Expected behavior**
Suite takes me to "Connect my Trezor" screen when I disconnect my device and doesn't show any device connected.

**Comment by juriczech** [comment]
After retest from @STew790 , closing as it seems issue is resolved
