### ISSUE TITLE
When receiving ERC20 token the icon is token but label is Ethereum

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10166]
Please put there:
First Line: ETH Receive address
Second line: ETH icon [Ethereum account name] - [Token name]

Example Figma: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=5391%3A4448&mode=design&t=LS1uGmUj9VxVGC6E-1

**Comment by PeKne** [comment]
We are showing the name of the Ethereum account there (e.g. `Ethereum #1`). Whould would you like to see there? If receiveing Shiba Inu, should there be `Ethereum #1 - Shiba Inu`? 

The desing shows this: 

![Image](https://github.com/trezor/trezor-suite/assets/26143964/31965ff7-9a5b-4992-9feb-b0a1db0c4eaa)

 but IMO it does not make sense. What is `Shiba Inu #1`?

**Comment by mnuky** [comment]
Good point, let's put there your proposal - `Ethereum #1 - Shiba Inu`

**Comment by Hannsek** [comment]
I'd drop `SHIB` in front of Receive address.

**Comment by Hannsek** [comment]
Also `Ethereum #1 - Shiba Inu` still seems like there is some special address for Shiba Inu…

**Comment by mnuky** [comment]
Yes, Hans is right. What about?
Fist line: `ETH Receive address`
Second line: `SHIB - Ethereum #1`

**Comment by Hannsek** [comment]
Can you please post here the whole screenshot where is this situated?

**Comment by Hannsek** [comment]
What about this:
Fist line:  `Receiving SHIB`
Second line: `Ethereum #1 address`

@Hannsek we use the first line as identificator of Coin + Receive address and the second line as an account name, like a breadcrumb navigation. 
So I would suggest:
First line: `ETH Receive address for SHIB`
Second line: `Shiba Inu - Ethereum #1`
Figma: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=3804%3A14128&mode=design&t=VpCUSIIgyr1duGbL-1

**Comment by juriczech** [comment]
@mnuky I would be careful with these long strings like `ETH Receive address for SHIB` - might be problem on smaller screens. But let's discuss tomorrow on standup, once it's decided, the actual change is simple. 

Also, please reply with normal comments, don't edit messages as it's really confusing please 🙏🤣

**Comment by juriczech** [comment]
I like this one (https://github.com/trezor/trezor-suite/issues/10166#issuecomment-1840502601) the best.

**Comment by Hannsek** [comment]
> @Hannsek we use the first line as identificator of Coin + Receive address and the second line as an account name, like a breadcrumb navigation.

I think that my suggestion comply with that:
`Receiving SHIB` - receiving + coin
`Ethereum #1 address` - information about account

**Comment by Hannsek** [comment]
> Fist line: ETH Receive address
> Second line: SHIB - Ethereum #1

This is IMO confusing as there is _ETH_ and _Ethereum_ on one place.

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/b8d6acf9-1589-457d-a4a4-b6d0eac5ddd5)

Develop 23.12.2 (656) https://github.com/trezor/trezor-suite/commit/19c6638a3225f0c321d88fc6b36b8da18a0bc079
