### ISSUE TITLE
Enable sync XRP in portfolio tracker iOS&Android

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10165]
Acceptance criteria:
- User can sync XRP coin addresses in iOS and Android
- Helpguide to navigate users is the same as ETH

**Comment by mnuky** [comment]
QA NOK, there is error in Transaction detail

![Image](https://github.com/trezor/trezor-suite/assets/84183817/5cdfbced-2917-4171-b1d9-aaecce66464e)

**Comment by mnuky** [comment]
QA NOK, TX detail is fine but when you open Compare values tab, it does not show anything:
![Image](https://github.com/trezor/trezor-suite/assets/84183817/c0baadfb-7bf8-43c5-8ded-3a665a87eadf)

**Comment by Nodonisko** [comment]
Should be fixed, please retest also other coins I did some refactors here.

**Comment by bosomt** [comment]
**QA OK**

**QA OK**

Android 13 - Nothing Phone 1
 23.12.1 (639)
33aa5ef - [develop] - feat(suite-native): device module slide vertically (#10301)
