### ISSUE TITLE
requesting passphrase on device connection

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10167]
If is device with enabled passphase connected, it shows `Please enter your passphrase` message on the screen for a fraction of a second. It also brings some performance problems, because such device takes much longer authorize than a device with passphase disbaled `device.useEmptyPasshrase === false`. 

### possible fix
There is probably still some `TrezorConnect` method call in the `suite-common` thunks that access device without explicitly passing `useEmptyPassphase: true`. Try to find this call and hopefully it will fix the problem.

### Screenshot 
![IMG_1497](https://github.com/trezor/trezor-suite/assets/26143964/23152d73-7d11-4f5d-89ab-bc2a05159e4c)

**Comment by bosomt** [comment]
Not sure if 100% fixed.

Using/testing version 30d12fc - [develop] - chore(mobile): fix receive animation (#10412)
And i have seen passphrase dialogue on device when there was discovery running in app :(

**Comment by STew790** [comment]
Same here, I can still see passphrase prompt on device when connecting to my mobile phone.
Tested on develop version 23.12.2 (656) 19c6638

**Comment by bosomt** [comment]
**QA NOK**

it just happened to me during Cardano show address



![Image](https://github.com/trezor/trezor-suite/assets/31506317/c9c738ee-7c34-4d15-ade2-a1f118b021ae)



- version 23.12.2 (656) 19c6638 - [develop] - Chore\/receive image btc cash (#10414)
- Android 13 - Nothing phone 1
- S3 2.6.4 FW

**Comment by juriczech** [comment]
@bosomt I will check the receive address flow and fix that. Can you please confirm that during discovery this passphrase dialog is not visible on the trezor device?

**Comment by mnuky** [comment]
@juriczech QA NOK - Passphrase is still flashing during discovery - check the video: https://drive.google.com/file/d/1h6RjLT-4QoxvGyOCn3YtWMk8dj8kKN9S/view?usp=sharing

**Comment by bosomt** [comment]
**QA OK**

- havent see in for some time
- passphrase dialogue still flashes at beginning but this is happening in desktop app

24.2.0 (692)
abae3b8 - [develop] - chore(suite-native): track breadcrumbs for sentry on screen change (#10680)
