### ISSUE TITLE
Data Analytics: Trade button

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#10173]
We would like to track clicks on the Trade button in the header of the account. There should be new event `accounts/actions` with specific parameter `symbol` for coin (currency) differentiation.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.1.0 (e24c80afa0c49184f185c16112b545aab9bf0271)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
