### ISSUE TITLE
Cache fonts and icons in lite app

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10190]
**Describe the bug**
Loading of receive address page looks strange because fonts and icons are loaded after page is rendered.

**Info:**

-   Mobile Suite Version: ecb2d06 - [develop] - fix(suite-native): chunkify for ada (#10185)
-   OS: Android 13

**Screenshots**

https://github.com/trezor/trezor-suite/assets/31506317/f975b71c-3717-4371-aaa5-6dd8c7eeaeaa

**Comment by Nodonisko** [comment]
@bosomt Can you please retest this? I am not able to reproduce it and it may be solved by #10046

**Comment by bosomt** [comment]
**QA OK**

50fe764 - [develop] - chore(suite-native): update skia + reanimated (#10202)
