### ISSUE TITLE
Solana - graph and history are slow for a lot of txns

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#10236]
- It takes a lot of time to fetch all txns for the graph and txn history.

**Comment by shenkys** [comment]
Resolved in another [issue](https://github.com/orgs/trezor/projects/61/views/27?filterQuery=week%3A%3C%3D%40current+-release%3A%3C%40previous+-week%3Aprehistory++solana&pane=issue&itemId=86079018&issue=trezor%7Ctrezor-suite%7C15247)
