### ISSUE TITLE
Receive flow - cancel the receive does not work

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10239]
**No1: Cancel Receive address from Trezor device**
Steps to reproduce:
1. Connect Trezor
2. Choose some coin to Receive and click Show address
3. Show address screen appears
4. Click on Cancel button on Trezor device and cancel the Address confirming
5. Mobile app shows confirmation screen
Right behaviour: Mobile app should cancel the Receive and user should be redirected back to previous screen

**No2:Cancel Receive in mobile app:**
Steps to reproduce:
1. Connect Trezor
2. Choose some coin to Receive and click Show address
3. Show address screen appears
4. Click on back in mobile app
5. Trezor Device keep showing address to confirm
Right behaviour: When user cancel the Receive in the app, Trezor device should cancel it too

**Comment by STew790** [comment]
**QA OK**
Both cases now work correctly.

Develop 23.12.2 (656) https://github.com/trezor/trezor-suite/commit/19c6638a3225f0c321d88fc6b36b8da18a0bc079
