### ISSUE TITLE
When retrieving balances for connected trezor is in progress, portfolio balance from portfolio tracker appears

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10242]
Steps to reproduce:
Have some coins synced in Portfolio tracker
Open the app and connect the Trezor
When the asset balances are loading, you can see that until the final balances of connected trezor are loaded, the balance of portfolio tracker appears

**Comment by juriczech** [comment]
Cannot replicate. Could you elaborate, or better post a video?

**Comment by STew790** [comment]
**QA OK**
I wasn't able to reproduce this. I had some coins synced with tracker but I saw 0 balance when connecting my device (which was correct)

Develop 23.12.2 (656) https://github.com/trezor/trezor-suite/commit/19c6638a3225f0c321d88fc6b36b8da18a0bc079
