### ISSUE TITLE
Dry run for both devices

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1024]
T1 needs (probably) modal with word input dialog for dry_run recovery.

[**Zeplin**](https://zpl.io/2veYg6n) for Model One

**[Zeplin](https://zpl.io/aweYQP7)** for Model T

**Comment by mroz22** [comment]
no design linked, no work

**Comment by petrsulc** [comment]
Design:
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/dashboard?seid=5e4be083489d0bac13dccf4f

**Comment by mroz22** [comment]
done, more or less

**Comment by bosomt** [comment]
**You either have a seed containing 12, 18, 24, 33 words.**

Can you please add 20 words option to start of TT dry run ?
@mroz22

**Comment by wendys-cats** [comment]
Issue: Suite asks Advanced / Basic recovery choice for TT in Dry Run

Expected:
There is no Advanced recovery / Basice recovery option for TT, this applies to T1 model. 

Actual:
Suite asks Advanced recovery / Basice recovery option for TT.

Please fix, thank you!

**Comment by wendys-cats** [comment]
Issue: Number of words in seed has to be selected both in Suite and on device on TT model

Expected:
User will select the number of seed words only once, just like on T1 model. 

Actual:
User has to select number of seed words first in Suite, then the device is prompted to ask about dry run initiation. After that, user has to select the number of seed words on device again. Selecting number of seed words in Suite is redundant. 

Please get rid of seed word number selection in dry run for TT device, thank you!

**Comment by wendys-cats** [comment]
**Issue: Cannot close the "Your device is in recovery mode" modal window**

**Steps tor eproduce:**
1. Plug in device 
2. Start dry run, get as far as the actual control of seed words
3. Disconnect the device
4. Connect it again and abort the dry run on device

**Expected:**
The modal window will either disappear after aborting the recovery mode on device itself, or it can be closed by user.

**Actual:**
The modal window with notification will stay active even after aborting dry run, disabling any intercation with Suite. 
![your device is in recovery mode](https://user-images.githubusercontent.com/58593111/77072269-b8fd6000-69ed-11ea-8d12-1be5acfb635d.png)

**Comment by bosomt** [comment]
@szymonlesisz ready to test ?

**Comment by bosomt** [comment]
X button doesn't do anything

![image](https://user-images.githubusercontent.com/31506317/79104114-3195d900-7d6e-11ea-801a-27fe273722e0.png)
