### ISSUE TITLE
It is not possible to sync coin from connected Trezor

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10255]
Steps to reproduce:
1. Open App
2. Portfolio tracker is empty (no coins are synced)
3. Connect Trezor
4. Wait for discovery to finish
5. Pick some coin and copy the public address
6. Open the portfolio tracker and insert the address in syncing flow
7. App says that the coin is already synced

Expected behaviour: Coin from connected Trezor can be add to Portfolio tracker while the Trezor is connected

**Comment by bosomt** [comment]
**QA OK**

imported Eth account from discovered device without any kind of error or warning

- version 23.12.2 (656) 19c6638 - [develop] - Chore\/receive image btc cash (#10414)
- Android 13 - Nothing phone 1
