### ISSUE TITLE
App does not show account types labels

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10256]
Steps to reproduce:
1. Connect Trezor
2. Let the discovery finish
3. Go to My assets
4. Bitcoin assets don't have account type labels

Expected behaviour: Bitcoin like coins have account type label

**Comment by bosomt** [comment]
**QA OK**

- version 23.12.2 (656) 19c6638 - [develop] - Chore\/receive image btc cash (#10414)
- Android 13 - Nothing phone 1
