### ISSUE TITLE
[ Dashboard ] design bug - text overflows button

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1026]
![image](https://user-images.githubusercontent.com/30367552/71974270-66dfd780-3211-11ea-9b0a-27880ebbbbd8.png)

**Comment by slowbackspace** [comment]
I discussed it with @vladimirvolek and we came to conclusion that we should prevent word wrap in the `Button` component inside trezor components. Sounds good to you?

**Comment by slowbackspace** [comment]
> I discussed it with @vladimirvolek and we came to conclusion that we should prevent word wrap in the `Button` component inside trezor components. Sounds good to you?

eh this could a problem if we want to show very long amount in Send button
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f315be7b5114d3968db
