### ISSUE TITLE
ETH send

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#1030]
**[Zeplin](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f2db698581b5e108526)**

- [x] Address
- [x] Scan address QR code
- [x] Amount (without ERC 20)
- [x] Set Max (without ERC 20)
- [x] Converter to fiat (USD, EUR  etc.)
- [x] Fee (Normal, Economy, High....)
- [x] Clear
- [x] Send
- [x] Gas limit
- [x] Gas price
- [x] Data
- [x] Connect composing transactions from Connect
- [x] Tooltips 
- [x] Wizard 
- [x] Refresh fee button 
- [x] Review and send

**Comment by bosomt** [comment]
+ missing tool tips 
+ data field makes send protocol go wild ;)

please see video 

https://www.youtube.com/watch?v=wWSzPHf6BBY&feature=youtu.be

**Comment by glacierbits** [comment]
Both issues fixed.

**Comment by bosomt** [comment]
> * []  Address
> * []  Scan address QR code
> * []  Amount (without ERC 20)
> * []  Set Max (without ERC 20)
> * []  Converter to fiat (USD, EUR  etc.)
> * []  Fee (Normal, Economy, High....)
> * []  Clear
> * []  Send
> * []  Gas limit
> * []  Gas price
> * []  Data
> * []  Connect composing transactions from Connect
> * []  Tooltips
> * []  Wizard
> * []  Refresh fee button
> * []  Review and send

**Comment by bosomt** [comment]
see amount field, when window is not in full screen on full hd monitor
i think that we need to resize that button or chop some decimals
you need at 1600 pixels resolution to fit in
 
most user resolutions are bellow this / 1920x1080 has less than 10% market share/

![image](https://user-images.githubusercontent.com/31506317/82729023-7eb58500-9cf4-11ea-8da5-67e37fe20252.png)

**Comment by bosomt** [comment]
and there is no fee types, just normal, not even custom fee / Fee (Normal, Economy, High....)/
