### ISSUE TITLE
App got frozen for some seconds between tracking consent and empty dashboard

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10307]
Steps to reproduce:
1. Open the app (with cleared data storage)
2. Go through the welcome flow screen
3. On Consent tracking screen click on Confirm
4. The button got frozen for 3-5s
5. Then the app redirects to next screen but very weirdly

Look at the video:
https://github.com/trezor/trezor-suite/assets/84183817/c9d8f245-7222-4bbc-bf62-a2b494b42ef0

**Comment by bosomt** [comment]
**QA OK**

Android 13 - Nothing Phone 1
 23.12.1 (639)
33aa5ef - [develop] - feat(suite-native): device module slide vertically (#10301)
