### ISSUE TITLE
2023 Popup window disappears 

### ISSUE THREAD

**Issue by nopty** [trezor/trezor-suite#10314]
Hello, can you point link to fix for the popup disappearing issue? Thanks

**Comment by Hannsek** [comment]
Please either comment on already created issue or create a new one with all necessary info.

**Comment by nopty** [comment]
I use:
metamask (Version: 1 1 . 4 . 1)
firefox (115.5.0esr (64-bit))
chrome (Version 109.0.5414.120 (Official Build) (64-bit))
MS edge (Version 109.0.1518.140 (Official build) (64-bit))
