### ISSUE TITLE
QR code with long text not fitting into container

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#10313]
Show receive address or XPUB with language set to Spanish:
![Screenshot 2023-12-12 at 21 08 12](https://github.com/trezor/trezor-suite/assets/42465546/ba7a230d-135f-48f0-a9ea-303467593414)

My suggestion is to remove absolute positioning and make the container scale with the text.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.2.0 (a30bef7c9b4c2a3baa8b4c467038663d9af1b1d1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2T1 2.6.4 bitcoin-only (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
