### ISSUE TITLE
Empty state

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#1031]
Child of #1014  Design: https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6efa120829110bc496f4

**Comment by glacierbits** [comment]
@slowbackspace Ticket reopened: The design proposal in Zeplin has an image now. Please update.

**Comment by bosomt** [comment]
please see 

![image](https://user-images.githubusercontent.com/31506317/74628510-28193780-5156-11ea-81e0-ba8a6dc68630.png)

404 error when i disable all coins

**Comment by glacierbits** [comment]
@bosomt FYI this issue has label "Transactions", the "Empty state" here refers to Transactions tab with no outgoing or incoming txs (i.e. new account added, no txs yet). Empty state with all coins disabled has a separate issue. 

<img width="1405" alt="Screen Shot 2020-03-03 at 14 10 44" src="https://user-images.githubusercontent.com/29627086/75779430-e1ccf680-5d59-11ea-9f72-c74d44fc0704.png">
