### ISSUE TITLE
Not able to onboard device when used in second app or tab

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10333]
**Describe the bug**
Web version of Trezor Suite does not recognize device correctly when there is enter passphrase dialogue open.
I was able to reproduce it with two tabs of same browser open.

**Steps to reproduce:**
1. Start Trezor Suite app or open in browser and open add passphrase dialogue
2. Device reports `please enter your passphrase`
3. Try to onboard device in web version of Trezor Suite

**Info:**
 - Suite version: web 23.12.1 (6de97f02214677afe4d5117ee16b92e631bf1e12)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0
 - OS: MacIntel
 - Screen: 2268x1473
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/2edbc1bf-8e24-4dd5-a19e-7aa857861111

**Comment by komret** [comment]
Hopefully resolved by https://github.com/trezor/trezor-suite/pull/10386

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.12.3 (8fd6a446f2f03d4c8407e1f5f97a804f315a0253)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.12.3 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 bitcoin-only (revision 1f693d3561c375661563970e066f678590abc19c)
 - Transport: BridgeTransport 2.0.33
