### ISSUE TITLE
Cardano with connected device freezes the app

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10339]
Steps to reproduce:
1. Connect Trezor device with Cardano assets
2. Click receive
3. Click Show full address
4. Click on Device in order to scroll the address - up and down
5. Do the same on Mobile Screen
6. App starts lagging and not responding

**Comment by vytick** [comment]
I was not able to simulate this in emulator. Passing to @juriczech

**Comment by Nodonisko** [comment]
done

**Comment by bosomt** [comment]
**QA OK**

- version 23.12.2 (656) 19c6638 - [develop] - Chore\/receive image btc cash (#10414)
- Android 13 - Nothing phone 1
