### ISSUE TITLE
BTC Cash Receive address displays prefix on mobile

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10348]
Steps to reproduce:
- Connect the Trezor to app with BTC Cash
- Click Show full address
- Trezor Screen displays Receive address
- Mobile screen displays address with prefix: `bitc oinc ash: `

Expected behaviour: the prefix should not be part of the address displayed on mobile screen

**Comment by bosomt** [comment]
**QA NOK**

30d12fc - [develop] - chore(mobile): fix receive animation (#10412)

checking latest today build and i still see prefix
UPDATE: prefix is only displayed in accounts imported via QR code not imported from device 

<img width="382" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/d4a85b5e-327e-4b4a-b559-37a39c05d44b">

**Comment by bosomt** [comment]
**QA OK**

prefix is only hidden during confirming of address, any other display includes `bitc oinc ash:` prefix

- version 23.12.2 (656) 19c6638 - [develop] - Chore\/receive image btc cash (#10414)
- Android 13 - Nothing phone 1
