### ISSUE TITLE
Bitcoin (like)

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#1034]
Child of #1014 
Design: https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6eec1b06a0202b351f1f

**Comment by sorooris** [comment]
Will be approved by QA after #1074 is done.

**Comment by bosomt** [comment]
https://github.com/trezor/trezor-suite/issues/1074 is still open, waiting

**Comment by bosomt** [comment]
approving , but creating https://github.com/trezor/trezor-suite/issues/1464
