### ISSUE TITLE
Graph breaks sometimes

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#10344]
This account cause graph to fall to zero at last point.

It seems that `blockchainGetAccountBalanceHistory` is shomehow in conflict with `getAccountInfo`. Probably bug in `addBalanceForAccountMovementHistory` ?

BTC xpub: xpub6BiVtCpG9fQQ77Qr7WArXSG3yWYm2bkRYpoSYtRkVEAk5nrcULBG8AeRYMMKVUXAsNeXdR7TGuL6SkUc4RF2YC7X4afLyZrT9NrrUFyotkH

**Comment by matejkriz** [comment]
Notes for @trezor/qa: Please test also ETH accounts if you don't see negative balances somewhere.

**Comment by bosomt** [comment]
**QA OK**

tested on multiple coins including Eth accounts

24.01.1 (673)
96d12a4 - [develop] - fix(suite): fix label drop for RBG transactions
Android 13 - Nothing phone 1
