### ISSUE TITLE
PIN 3 - Loader when user inserts the PIN for T1

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10359]
As a user I would like to get response once I insert PIN on mobile screen for T1 and click on Enter because it increases my understanding what is happening. Current state is static and it may make impression that nothing has happened. 

Design: https://www.figma.com/file/KvbZGG16li6BA90Xtpf0BP/Device-interaction?type=design&node-id=365-6013&mode=design&t=goKq8hyrLBXvx9eR-0

**Comment by juriczech** [comment]
Loader means the loading screen with `Hodl on tight` or different design?

**Comment by mnuky** [comment]
Nope, it is this screen when user inserts the PIN and click on Enter PIN, it takes time before the PIN is validated on device. It would be great to put some loader before the PIN is validated in the Button.

![Image](https://github.com/trezor/trezor-suite/assets/84183817/6970008b-6425-4f7b-9524-d7e3b82b049f)

**Comment by juriczech** [comment]
I'm asking because of the loader design. What should it look like? I thought by loader you mean the loading screen. This is not ready for development yet I guess?

**Comment by matejkriz** [comment]
TODO: animation for expansion of PIN form for Enter Pin button

**Comment by STew790** [comment]
**QA OK**
Verifying PIN loader OK

24.3.1 (cc7d18e)
