### ISSUE TITLE
Account type Legacy Segwit tagged as Segwit

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10354]
BTC account types Legacy Segwit are marked as Segwit in mobile app. 

Please label accounts:
XPUB: zpub6rszzdAK6RuafeRwyN8z1cgWcXCuKbLmjjfnrW4fWKtcoXQ8787214pNJjnBG5UATyghuNzjn6Lfp5k5xymrLFJnCy46bMYJPyZsbpFGagT
=> Mark as Segwit

XPUB:
tr([5c9e228d/86'/0'/0']xpub6Bw885JisRbcKmowfBvMmCxaFHodKn1VpmRmctmJJoM8D4DzyP4qJv8ZdD9V9r3SSGjmK2KJEDnvLH6f1Q4HrobEvnCeKydNvf1eir3RHZk/<0;1>/*)
=> Mark as Taproot

XPUB:
ypub6XKbB5DSkq8Royg8isNtGktj6bmEfGJXDs83Ad5CZ5tpDV8QofwSWQFTWP2Pv24vNdrPhquehL7vRMvSTj2GpKv6UaTQCBKZALm6RJAmxG6
=> Mark as Legacy SegWit

XPUB:
xpub6BiVtCpG9fQPxnPmHXG8PhtzQdWC2Su4qWu6XW9tpWFYhxydCLJGrWBJZ5H6qTAHdPQ7pQhtpjiYZVZARo14qHiay2fvrX996oEP42u8wZy
=> Mark as Legacy

**Comment by STew790** [comment]
**QA OK**
Accounts marked correctly.

**Info:**
Version 24.01.1 (680)  commit 7a1500b
