### ISSUE TITLE
Suite showing overlapping info on hover over the CJ start/stop button

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#10357]
**Describe the bug**
When CoinJoin is running and the account gets out of sync somehow, the info on hover over the start/stop Coinjoin button is overlapping.

**Steps to reproduce:**
Not really sure because you need to have the account out of sync to get this.

**Info:**
 - Suite version: desktop 23.12.1 (6de97f02214677afe4d5117ee16b92e631bf1e12)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.12.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
Only one info is shown.

**Actual result:**
Overlapping information is shown on hover.

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/48477147/f42db73c-ef55-4681-a700-6ceae9be2493)

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
