### ISSUE TITLE
Optimalize discovery

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#10350]
Current discovery is doing lot of unnecessary things:
1. getFeatures request on device after every account address request
2. fetching also transactions for accounts in discovery but we don't need them and throw them away anyway
3. logging middleware is loggin like crazy during discovery which is adding lot of overhead

Solution:
1. don't do that
2. don't do that
3. remove logging middleware because it's useless anyway

QA:
1. Test discovery
2. Test discovery for BTC only firmware
3. Test if ERC20 tokens are discovered (visible on My Assets page)
4. Test if correct address is generated (not receive address) - ADA won't work probably because of #10343 but you may try

**Comment by bosomt** [comment]
**QA OK**

- discovery works with all models
- TT BTC only works as expected
- ETH + ERC20 works as expected
- Cardano + device currently shows passphrase dialogue and not address :) /tested on S3 with 2.6.4 FW/

**info**
- version 23.12.2 (656) 19c6638 - [develop] - Chore\/receive image btc cash (#10414)
- Android 13 - Nothing phone 1
- model T with BTC only 2.6.4 fw
- model S3 with 2.6.4 fw

**Comment by STew790** [comment]
**QA OK**
- test with BTC only fw and device discovery works as expected

**Info:**
version 23.12.2 (656) https://github.com/trezor/trezor-suite/commit/19c6638a3225f0c321d88fc6b36b8da18a0bc079
Android 12 Xiaomi Redmi Note 9 Pro
