### ISSUE TITLE
T1: Receive address on device has different break point than on mobile screen

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10351]
Steps to reproduce:
- Connect Trezor One to mobile app
- Receive BTC Segwit
- Show full address
- Compare the addresses on device and mobile screen - the line breaking is different

Expected behaviour: line breaking should be same on both screens

![Image](https://github.com/trezor/trezor-suite/assets/84183817/9f70041e-429c-455a-af7f-66e180632e76)
![Image](https://github.com/trezor/trezor-suite/assets/84183817/3e792fe1-c06c-48fe-9e1b-27d4c001b687)

**Comment by bosomt** [comment]
**QA OK**

24.01.1 (681)
e089477 - [develop] - feat(suite-native): empty states copy (#10630)

* feat(suite-native): empty states copy

* feat(suite-native): search again

* feat(suite-native): different icons

* fix(suite-native): receive copy
