### ISSUE TITLE
Ethereum with tokens

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#1035]
Child of #1014 
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6ef2883d131f631afcf0

**Comment by bosomt** [comment]
i can see tokens in transactions 
i can see tokens summary
it looks amazing,

but in transaction details i don't see them:

![image](https://user-images.githubusercontent.com/31506317/78651110-2d764100-78c0-11ea-830d-5c5fbcb850a5.png)



![image](https://user-images.githubusercontent.com/31506317/78651172-41ba3e00-78c0-11ea-8c16-874f94215091.png)

https://eth1.trezor.io/tx/0xc18c3d66a3d3e0491c037002d99e66e8a24310a05569eee84dd5455581925434

@szymonlesisz @matejzak is this separate issue or you can fix it in this issue ?

**Comment by glacierbits** [comment]
Will be fixed by #2549
