### ISSUE TITLE
Transaction detail modal 

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#1036]
Child of #1014 
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa1bdd08fcb816e78ff460

**Comment by bosomt** [comment]
please check historical value, it always says price of whole coin, for any coin

![image](https://user-images.githubusercontent.com/31506317/74422305-b20f8a80-4e4e-11ea-97ef-9931e8d8b6dd.png)

**Comment by glacierbits** [comment]
@slowbackspace Correct me if I am wrong, but I see the historic / current values work just fine now. Moving this to "Approved". (cc @bosomt) Thanks!
