### ISSUE TITLE
XRP send

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#1037]
**[Zeplin](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa1c07eb55711ae3e9afea)**

- [x] Address
- [x] Scan adress QR code
- [x] Amount 
- [x] Set Max
- [x] Converter to fiat (USD, EUR  etc.)
- [x] Fee
- [x] Clear
- [x] Send
- [x] Fee
- [x] Destination tag
- [x] Check destination address for balance (20 XRP warning limit)
- [x] Review & Send
- [x] Tooltips

**Comment by vladimirvolek** [comment]
Missing new design

**Comment by bosomt** [comment]
no 20 XRP limit, allows you to send all of them + then account summary is broken. 
Maximum is 604 but alowed me to send 624 and then it says 0 XPR with price 3$ :)

![image](https://user-images.githubusercontent.com/31506317/76755147-a253d080-6783-11ea-8706-edec9c56dcea.png)

![image](https://user-images.githubusercontent.com/31506317/76757301-a550c000-6787-11ea-9bfc-3fc4f1d48530.png)

**Comment by bosomt** [comment]
when you click on transaction:

![image](https://user-images.githubusercontent.com/31506317/76758227-9539e000-6789-11ea-8e04-532c2d8914c1.png)

**Comment by bosomt** [comment]
works fine !

https://xrpscan.com/account/rJa92XEEzK8jTzL3UCQ6TeyHCqeUA6G6Li
https://xrpscan.com/tx/9B80840AB99071E86C9FDDCF8438D01FC3865BE2FA0729270898E3CE6582B211
