### ISSUE TITLE
Workaround for lack of json-rpc batching support in Electrum Personal Server

### ISSUE THREAD

**Issue by mcjoojar** [trezor/trezor-suite#10387]
**Describe the bug**
Trezor Suite gets stuck indefinitely on checking balances when using Electrum Personal Server ("EPS") backend. Looking over the EPS logs, this appears to be because Trezor Suite is using json-rpc batching, which is not supported by EPS

**Info:**

-   Remembered Wallet: no
-   Suite Version: app v23.11.5
-   Browser: n/a
-   OS: Windows 11

**How to reproduce**

1. Setup EPS
2. Configure Trezor Suite to use the EPS that was set up in 1
3. Connect Trezor Model T

**Expected behavior**
Balances are checked successfully and show in the Trezor Suite UI in the usual way

**Screenshots**
n/a

**Additional context**
EPS has an open issue for lack of support for json-rpc batching: https://github.com/chris-belcher/electrum-personal-server/issues/186

However, it doesn't seem like it will be fixed any time soon, so how about a workaround along similar lines to the one described in the thread for Blue wallet? Blue wallet works well with my EPS server, presumably thanks to this workaround.

**Comment by mroz22** [comment]
Is it some specific setup of electrum backend? 

Maybe @marekrjpolak can comment on this.

**Comment by mcjoojar** [comment]
> Is it some specific setup of electrum backend?

Yes, it is a canonical install of Electrum Personal Server (EPS) on Ubuntu. Here is EPS: https://github.com/chris-belcher/electrum-personal-server

The root cause is that EPS does not support json-rpc batching, and is not likely to any time soon - full details here: https://github.com/chris-belcher/electrum-personal-server/issues/186

**Comment by marekrjpolak** [comment]
Yeah, I've implemented json-rpc batching as a default. Currently it cannot be turned off with a param, but it should be relatively simple to add it. The question is whether this BlueWallet's heuristics is sufficient (electrs currently supports batching):
https://github.com/BlueWallet/BlueWallet/pull/940/files#diff-40c0cccbe75c88e8db6d83e684deb07c172cd6702e9e2ab6392014fed76015c3R64-R67

**Comment by mcjoojar** [comment]
> Yeah, I've implemented json-rpc batching as a default. Currently it cannot be turned off with a param, but it should be relatively simple to add it. The question is whether this BlueWallet's heuristics is sufficient (electrs currently supports batching): https://github.com/BlueWallet/BlueWallet/pull/940/files#diff-40c0cccbe75c88e8db6d83e684deb07c172cd6702e9e2ab6392014fed76015c3R64-R67

If not, what about exposing EPS as its own backend type, so the user explicitly chooses EPS (which turns off batching)?

**Comment by bosomt** [comment]
**QA OK**

sent,bumped, finalized via electrum.corp.sldev.cz:50001:t

**Info:**
 - Suite version: desktop 24.1.0 (e06b9375a3b7fd9066c847178791ffcb8e2e9436)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.1.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.5 regular (revision f4d3a7456afaa850f9651d31ddc9d7e4b68ab7b8)
 - Transport: BridgeTransport 2.0.33
