### ISSUE TITLE
Send form fee frame empty state

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#10395]
For coins with no fee setup options, like Solana, there is nothing to show in the Fee frame of the Send form until users enter some value to be sent for some fee to be calculated based on that.

Size of the frame as it is now doesn't count with this empty state to happen and therefore leaves an unnecessarily tall blank space in the frame (for the non-present fee controls).

Please make the frame vertically responsive, so the size will be only as tall as the empty Total frame one's and that it will accommodate any content well once present (that means the same size as Total also when populated with just a value (like for Solana) and tall enough for coins with controls.

![Image](https://github.com/trezor/trezor-suite/assets/88533514/8f2f3472-e560-45d6-a47b-d075985c66c7)

![Image](https://github.com/trezor/trezor-suite/assets/88533514/46f41fad-1c32-407e-b642-aa3833d3d0b5)

![Image](https://github.com/trezor/trezor-suite/assets/88533514/b1b19214-632b-4a43-bbd1-cdf68b435318)

**Comment by komret** [comment]
There is some extra space needed for when the for is filled, the fee is on two lines (SOL and fiat) and we want to avoid changing the card's dimensions. The Total card is not below it in the Empower design so these two won't be compared. So I think this is resolved by https://github.com/trezor/trezor-suite/pull/10517.

**Comment by MiroslavProchazka** [comment]
Should be fixed by https://github.com/trezor/trezor-suite/pull/10517.

**Comment by STew790** [comment]
**QA OK**
Looks way better now
![image](https://github.com/trezor/trezor-suite/assets/48477147/cc70d9e2-b797-4e24-ab2c-2cc262fb8dea)
![image](https://github.com/trezor/trezor-suite/assets/48477147/c3f2cc06-d0ee-4ad6-8b30-59e0e0a3987e)
![image](https://github.com/trezor/trezor-suite/assets/48477147/de52ab56-2aea-4174-93b2-6c395b0addb4)

**Info:**
 - Suite version: desktop 24.3.0 (094fbb029397557a6f4bcbb2390fcdc8de54f3d3)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
