### ISSUE TITLE
Menu Shamir Backup Not Found in Trezor Suite Linux Mint 12.2

### ISSUE THREAD

**Issue by ZeroTierCloud** [trezor/trezor-suite#10397]
**Describe the bug**

**Info:**

-   Remembered Wallet: yes
-   Suite Version: app v23.11.5
-   OS: LINUX MINT 12.2
-   Bridge: version
-   Firmware Version: model, version/commit

I have Shamir backup, but when I want to restore in Trezor Safe 3, the backup menu option using Shamir Backup in Trezor Suite is not there!
Is this a trezor suite application bug?

**Screenshots**
![Screenshot from 2023-12-20 19-19-22](https://github.com/trezor/trezor-suite/assets/154435070/3e754af7-8c5b-4fa6-be31-2b2ce1476c12)

**Comment by Hannsek** [comment]
It is not. You press the _Start recovery_ flow in Suite. Device will ask you to select how many words are in your backup. For shamir, you select either 20 or 33. After this you follow instruction in the device.

**Comment by ZeroTierCloud** [comment]
thanks you, solved
