### ISSUE TITLE
Character "l" looks different on Trezor device and on mobile screen

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10394]
Steps to reproduce:
Connect Trezor  T1 or TS3 to mobile app
Pick asset and show full address which contains character "l"
Compare the addresses on both screens - character "l" looks different on trezor device and on mobile screen - check the printscreens

![Image](https://github.com/trezor/trezor-suite/assets/84183817/240f2cfc-8103-4e46-8438-d5b3ff55eacc)
![Image](https://github.com/trezor/trezor-suite/assets/84183817/7cfcc819-d25e-4cd1-9a4a-36027c79d2f0)

**Comment by bosomt** [comment]
**QA OK**

24.01.1 (673)
96d12a4 - [develop] - fix(suite): fix label drop for RBG transactions
Android 13 - Nothing phone 1
Trezor model Safe 3
