### ISSUE TITLE
Enable copy the address via long hold on the address

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10406]
Enable copying the address by double clicking on it.

Acceptance criteria:
When user long presses on Receive address, it is copied
Message "Address copied" appears
It applies also to Receive address before it is confirmed (for users who want to copy the address and put it into sender's form and verify it there)

**Comment by shenkys** [comment]
Design done
[Figma here](https://www.figma.com/file/SzqPKc7fA253syVTeohsoe/Receive?type=design&node-id=314-1913&mode=design&t=lovyoNJsNmJjoBcd-11)

**Comment by Hannsek** [comment]
Is double click the best UX pattern? What about a long hold?

**Comment by shenkys** [comment]
Long hold is in place, check the design.

**Comment by matejkriz** [comment]
related internal discussion https://satoshilabs.slack.com/archives/C04JZAYEV41/p1709303628147489

**Comment by bosomt** [comment]
**QA OK**

Android 14 Nothing phone 1
24.5.0 aedc1f7
