### ISSUE TITLE
Button for disabling WebUSB is too wide

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#10415]
**Describe the bug**
The button for disabling WebUSB and use Bridge looks weird and it lacks some spacing.

**How to reproduce**

1. Go to the dropdown under "Still don't see your Trezor?"
1. See the button

**Expected behavior**
Button should have some spacing (horizontal and on the bottom).

**Screenshots**
![17448AF2-911C-476D-A230-BDFD94DF3CD7](https://github.com/trezor/trezor-suite/assets/66002635/54e008ef-f299-4bc6-bbbb-0e777e96fb43)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.1.0 (e24c80afa0c49184f185c16112b545aab9bf0271)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
 - OS: MacIntel
 - Transport: WebUsbTransport
