### ISSUE TITLE
Device & Suite comparison screens improvements

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#10425]
### Specification
We have introduced the address chunking and changed the way of comparing the on device shown data with the ones to compare in Suite. Now the things look much more alike for easier comparison. However as we had to focus on the top priorities in the first iteration, there's an opportunity to improve some more cases described below.

- [x] Addresses on Trezor Model One: Please improve the breakpoints of all addresses to match the breakpoints on device
- [x] XPUBs on all devices: Please improve the breakpoints of all xpubs to match the breakpoints on device
   - [x] Unchinkified for now, we will have to add chunking once it will be ready on FW
- [x] Cardano on all compatible devices: Please improve the breakpoints of Cardano addresses to match the breakpoints on device
  - [x] Unchinkified for now, we will have to add chunking once it will be ready on FW

### Screenshots of the current state
**Trezor Model One**
![Image](https://github.com/trezor/trezor-suite/assets/88533514/9d9d2718-a64d-4277-babb-60e5a54c8aeb)
![Image](https://github.com/trezor/trezor-suite/assets/88533514/d8e481bf-23ec-45b2-96d4-f50af31fed24)

______________________________________________
**XPUBs**
![Image](https://github.com/trezor/trezor-suite/assets/88533514/720c9080-44c5-4c18-a399-8a379be8d674)
![Image](https://github.com/trezor/trezor-suite/assets/88533514/8a1b5cbb-b002-4a16-8c13-bfef0195ca52)

![Image](https://github.com/trezor/trezor-suite/assets/88533514/66f7ec88-c222-4aca-a590-28e8de34ad7f)
![Image](https://github.com/trezor/trezor-suite/assets/88533514/c303faad-ceba-4b4c-872c-278d0ba18a5a)

![Image](https://github.com/trezor/trezor-suite/assets/88533514/58e429e3-457b-4d6f-a1f1-87c50dc725eb)
![Image](https://github.com/trezor/trezor-suite/assets/88533514/845bf1d7-01e2-46d1-8a7d-3812ab83adc5)

______________________________________________
**Cardano**
![Image](https://github.com/trezor/trezor-suite/assets/88533514/1e4452d9-b424-4251-8591-2ec4ed76bb3d)
![Image](https://github.com/trezor/trezor-suite/assets/88533514/8ecbb455-2ac4-463e-9f65-2ab70846d678)
![Image](https://github.com/trezor/trezor-suite/assets/88533514/983834b7-f00c-4ff9-969c-06947c9089e3)
![Image](https://github.com/trezor/trezor-suite/assets/88533514/75c27bb4-b443-4e4e-af5b-ba9c77166492)
![Image](https://github.com/trezor/trezor-suite/assets/88533514/cfdc42fc-1aeb-479c-a955-d8cc6b6edfb0)
![Image](https://github.com/trezor/trezor-suite/assets/88533514/ced666cc-44aa-4397-a541-f22e1292a14b)
![Image](https://github.com/trezor/trezor-suite/assets/88533514/86a95e45-7cfa-4c4a-8f9b-75c0f6d2ff08)

**Comment by komret** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/11251

**Comment by bosomt** [comment]
**QA OK**

checked multiple coins receive address and xpubs, all matches device /even when its 3 page size/
tested on Trezor T2B1

**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
