### ISSUE TITLE
Differentiate the Coinjoin Account 

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#10420]
In the current version of suite-e there is no more `Default Accounts` header, which is slightly confusing when a Coinjoin account is present.

Render `Default Accounts` when there is one or more CJ account.

![image](https://github.com/trezor/trezor-suite/assets/45338719/217c0e30-9aec-46c9-8e0b-c7a018564d21)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
