### ISSUE TITLE
SOL derivation path difference between Trezor and Ledger

### ISSUE THREAD

**Issue by biscogit** [trezor/trezor-suite#10428]
**Describe the bug**
Simulating a user migrating from Ledger or recovering onto a Trezor (Safe 3, in this case), and an existing SOL balance is not found

**Info:**

-   Remembered Wallet: yes/no (either)
-   Suite Version: app/web, PC Suite 23.12.3, web 23.12.3
-   Browser: Brave 1.61.104
-   OS: Windows 11 64-bit
-   Bridge: version 2.0.33 (bundled)
-   Firmware Version: Safe 3, Universal 2.6.4

**How to reproduce**

1. Have Ledger with SOL balance
2. Restore seed phrase from Ledger on Trezor
3. Add SOL as an asset
4. Note there is no balance
5. Note generated public addresses do not match
6. Check Ledger derivation path: 44'/501'/0'
7. Check Trezor derivation path: 44'/501'/0'/0'

**Expected behavior**
Expected derivation paths to match, or at least balances to be discovered

**Screenshots**

**Additional context**
Not sure if there are other complicating factors preventing use of same deriv path -- wondering if a possible solution would be similar to how ADA is handled:  balances detected in a Ledger path for Cardano are listed as "Ledger Accounts" in Suite along with the "Default Accounts" using Trezor methodology.

**Comment by biscogit** [comment]
Cloned the repo and tested by modifying trezor-suite/suite-common/wallet-config/src/networksConfig.ts from 
```
        name: 'Solana',
        networkType: 'solana',
        bip43Path: "m/44'/501'/i'/0'",
```

to (line 464, bip43Path definition)
```
        name: 'Solana',
        networkType: 'solana',
        bip43Path: "m/44'/501'/i'",
```

and compiling through to suite:dev:desktop -- confirmed Suite will then show the (non-delegated) available SOL balance as expected.  (Being able to manage delegation/see the combined available+delegated balances would also be fantastic, but are beyond the scope of this specific issue).

Did not test further to confirm any transaction operations, but the public address displayed properly and transaction history populated.

**Comment by Hannsek** [comment]
This is currently expected as Ledger's non-standard derivation path is not supported right now.

We advise all user to migrate their funds to standard derivation path (Solana account created in Suite).

**Comment by biscogit** [comment]
Fair enough -- thanks for the review and response!

**Comment by tomasklim** [comment]
@Hannsek it can be easily added to Trezor Suite

~~@trezor/qa when checking this, I discovered, that based on our network config, we should support 3 derivation paths for Cardano (icarus, icarus-trezor, ledger) . However, based on this condition, we do not allow to add the account https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx#L149 is it feature or bug?~~

**Comment by Hannsek** [comment]
It is a feature. 
We don't want our users to add all 3 Cardano derivation path accounts. We support these 3 paths when someone has a seed from other wallet and want to discover their accounts.

**Comment by tomasklim** [comment]
So the same can be done for Solana easily

**Comment by Hannsek** [comment]
Yes, however, we have decided we don’t won’t to support all 3 derivation paths on Solana. We can reevaluate it later.
