### ISSUE TITLE
Default device naming improvement

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#10424]
Replace “My Trezor” with device name (Trezor Model T etc.) to be the default name assigned to any device during the onboarding.

Let Suite pass the default name as a parameter to resetDevice. This way, we won’t have the default value (“My Trezor”) set in two places (Connect and Suite).

**Comment by MiroslavProchazka** [comment]
@Hermez-cz Please add Slack thread mentioning this issue.

**Comment by Hermez-cz** [comment]
Related Slack discussion incl. further context: https://satoshilabs.slack.com/archives/CKN5C51CJ/p1699624093877649

Related issue: #10443 (Trigger reset flow during recovery)

**Comment by komret** [comment]
Closing in favour of https://github.com/trezor/trezor-suite/issues/12881. Suite will not set the device label automatically, only the user can do that. If it is not set, Suite will display device name (Trezor Model T etc.).
