### ISSUE TITLE
SOL Account discovery error: We were unable to discover your accounts.

### ISSUE THREAD

**Issue by LTD-Dev** [trezor/trezor-suite#10427]
Describe the bug
After using a custom passphrase and adding SOL (Default SOL wallet works just fine)

Important Fact: this only happened after sending funds to the generated address

Errors:
 1. Asset not loaded correctly
 2. Accounts were not loaded properly
Solana: Cannot read properties of undefined (reading 'slice')
 3. Account discovery error
We were unable to discover your accounts.

Suite Version: appImage x64 23.12.3
OS: Mac
Bridge: version
Firmware Version: 2.6.4

**Comment by LTD-Dev** [comment]
Same issue as this other user: https://forum.trezor.io/t/solana-token-msol/14676/2
![issue](https://github.com/trezor/trezor-suite/assets/38134746/45880f13-03e9-4d3b-9e7c-ed21b4c96cbe)

**Comment by MiroslavProchazka** [comment]
This issue will be fixed in the upcoming version of Trezor Suite to be released on January 17. If the problem continues to occur, please let us know. Thanks
