### ISSUE TITLE
Trezor Suite prompts to install older Trezor bridge version

### ISSUE THREAD

**Issue by CodeShakingSheep** [trezor/trezor-suite#10433]
**Describe the bug**
When using Trezor Suite Web to install Trezor bridge, it prompts to install Trezor bridge 2.0.27 although newer versions of the bridge have been released and although Trezor bridge 2.0.33 (included in Trezor Desktop Suite) is already installed on my system.

**Info:**

-   Remembered Wallet: no
-   Suite Version: web v23.12.3
-   Browser: Brave, Version 1.61.109 Chromium: 120.0.6099.144 (Official Build) unknown (64-bit)
-   Bridge: 2.0.33 (installed)
-   Firmware Version: T, 2.3.4

**How to reproduce**

1. Have latest Trezor bridge v 2.0.33 (included in Trezor Desktop Suite) installed.
2. Go to https://suite.trezor.io/web/bridge/
3. See that it prompts you to install Trezor bridge 2.0.27.

**Expected behavior**
If Trezor bridge is already installed I would expect a notice that it is already installed. If it is not installed I would expect a prompt to install the latest bridge version (currently 2.0.33 according to https://github.com/trezor/trezord-go/blob/master/CHANGELOG.md) instead of 2.0.27.

**Screenshots**
![Screenshot from 2023-12-26 23-04-35](https://github.com/trezor/trezor-suite/assets/19874562/7dd69ec0-d109-4d0f-b886-afa0bb5d583d)

**Additional context**
Additionally, I don't see latest bridge versions

- 2.0.31
- 2.0.32
- 2.0.33

here https://github.com/trezor/data/tree/master/bridge . Not sure if that might be intended as these versions are included in Trezor Desktop Suite.

**Comment by MiroslavProchazka** [comment]
Hey, thanks for reaching out to us. This is currently a intentional behavior, but we are already working on a structural change that will address and fix this issue.
