### ISSUE TITLE
Unable to manually validate firmware 2.6.4

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10436]
**Describe the bug**
`Error: Unable to validate firmware: httpRequest error: https://data.trezor.io/firmware/t2t1/trezor-t2t1-2.6.4.bin Not Found`

im getting this error when trying to check authenticity of firmware, 2.6.3 FW is present there but we forgot to deply new version of fw to t.io  
2.6.3 firmware is present 

**Steps to reproduce:**
1. Enable debug section in settings
2. Check authenticity of 2.6.4 fw device
3. Observe error

**Info:**
 - Suite version: desktop 23.12.3 (8fd6a446f2f03d4c8407e1f5f97a804f315a0253)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.12.3 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="318" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/97d48043-dd8f-48da-afcf-0dbab6b78ef8">

**Comment by CodeShakingSheep** [comment]
There is a PR for FW 2.6.4 which needs to be approved and merged https://github.com/trezor/data/pull/66

**Comment by MiroslavProchazka** [comment]
Resolved by https://github.com/trezor/data/pull/66

**Comment by bosomt** [comment]
**QA OK**

`Firmware authentic`


**Info:**
 - Suite version: desktop 24.1.1 (c4cf80383d5f554ff118ba507b743074e73216d4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
