### ISSUE TITLE
Portfolio tooltip probably does not take Cardano and Solana into account

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#10432]
**Describe the bug**
I guess we do not calculate with Cardano and Solana tokens

**Screenshots**
![Screenshot 2023-12-26 at 21 11 00](https://github.com/trezor/trezor-suite/assets/33235762/998de030-b5b8-4d65-ba5c-db888e3f5ff1)

**Comment by MiroslavProchazka** [comment]
Could you please check if the suite does not show the tokens in the graph? Could you please fix the copy?

**Comment by bosomt** [comment]
**QA OK**

`XRP, SOL and any token transactions are included in the balance, but not currently supported in the graph view.`

**Info:**
 - Suite version: desktop 24.2.0 (81d011d6dc01c0135cb38b989270cec8b9f74a57)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
