### ISSUE TITLE
Historical fiat rates for ERC20 are missing

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#10431]
**Describe the bug**
Historical fiat rates are missing for ERC20.

**Expected behavior**
Fiat rate is there as it is possible to fetch it from blockbook

**Screenshots**
![Screenshot 2023-12-26 at 20 02 43](https://github.com/trezor/trezor-suite/assets/33235762/cc099407-0b47-4224-9dff-328bf82e0a3a)

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/5fe78d76-f022-4b92-ada7-78568fc505d0)

**Info:**
 - Suite version: web 24.6.0 (d5b518f0f76f227a66ea0b0b7a4c7763c8bee2bf)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 3.0.0
