### ISSUE TITLE
Components v2 bugs

### ISSUE THREAD

**Issue by keip** [trezor/trezor-suite#1043]
- [x] Button: add alignIcon prop
- [x]  Button isDisabled property does not have disabling effect (works only visually)
- [x] Missing icons https://app.zeplin.io/project/5dad9fc62145a0128b1105f0/styleguide/components?coid=5e173f16e0203f7b394d37bd
- [x] Missing component's props exports (eg. ButtonProps, IconProps,...)
- [x] #1013
- [x] #1010 
- [x] #1007 
- [x] #957 
- [x] #1011 
- [x] #1017 
- [x] #1026 
- [x]  fix Tooltip snapshots

**Comment by vladimirvolek** [comment]
Select label color 
![image](https://user-images.githubusercontent.com/3112191/72158962-b19d5300-33bb-11ea-9f1b-49ae23045705.png)
