### ISSUE TITLE
UI of fiat rates in Suite (last updated, loading,...)

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#10435]
**Describe the bug**

------------------

**Logic:**
- ~`Price updated` is when price was fetched, it can be older. Use `timestamp` which we get from `Blockbook` / `Coingecko`~
-  ~In case 🔝 , we need to modify wording a little bit I guess~
<img width="278" alt="Screenshot 2024-02-08 at 12 19 12" src="https://github.com/trezor/trezor-suite/assets/33235762/f6151bce-8ff2-4e24-80ba-62247a394af8">

Blockbook

![Screenshot 2024-02-08 at 12 21 58](https://github.com/trezor/trezor-suite/assets/33235762/4bbbae58-b063-4c99-b118-acc23e5cf634)

Coingecko

<img width="561" alt="Screenshot 2024-02-08 at 12 25 38" src="https://github.com/trezor/trezor-suite/assets/33235762/544f7194-c0f1-4b75-bfba-eec41ab7b290">

+ ~Try to reduce amount of data fetched from coingecko, we fetch description, whitepaper url,..~
---------------------

**Dashboard**
- ~`No data available` is there for `~1sec`~
- ~Show loading or nothing there~
- ~Fix/improve UI of `No data available`~

<img width="930" alt="Screenshot 2024-04-16 at 9 14 16 AM" src="https://github.com/trezor/trezor-suite/assets/66002635/6dfb4130-8d82-41a1-85ab-b12507e139cd">
----------------------

**Account nav:**
- ~What does the triangle show, with what price is it compared? yesterday? 1 week? Why do we show triangle here and in trade box arrow?~
- ~`No data available` is there for `~1sec`, show loading or nothing there~
- ~fiat rate of whole balance is invisible when loading~
![Screenshot 2024-04-29 at 11 35 09 AM](https://github.com/trezor/trezor-suite/assets/66002635/134769e3-0175-4769-b64a-15259434ae61)
---------------------

**Trade box**
- ~Updated time under crypto name, not in a tooltip as everywhere else~
- ~Trend is explained but triangle vs arrow inconsistency~
- ~When no data available, it says updated 19762 days ago~
<img width="918" alt="Screenshot 2024-04-16 at 9 13 22 AM" src="https://github.com/trezor/trezor-suite/assets/66002635/2fa31579-4b1e-4930-8673-a0ee3e054d5b">

![Screenshot 2024-04-29 at 11 34 55 AM](https://github.com/trezor/trezor-suite/assets/66002635/9ea1ca2a-7a34-4c7a-91d7-8f8832978c81)
--------------------

**Tokens**
- ~No updated info~
- ~Looks like price is missing in the loading state~
- ~No data available info is missing~
<img width="929" alt="Screenshot 2024-04-16 at 9 14 45 AM" src="https://github.com/trezor/trezor-suite/assets/66002635/08704821-e59a-4657-9f6a-6582e2401909">
<img width="925" alt="Screenshot 2024-04-16 at 9 13 40 AM" src="https://github.com/trezor/trezor-suite/assets/66002635/48eb7b60-c5b9-4afe-8803-b662f8066c10">

**Comment by tomasklim** [comment]
@Hermez-cz + no token values in graphs, dashboard accounts, ~~sidebar accounts~~

**Comment by AdamSchinzel** [comment]
cc @Hermez-cz Basically all that remains to be specified is:
- Improve No data available (copy or UI)
- Think about other places where we show fiat rates like left sidebar and transactions, graphs etc.

**Comment by Hermez-cz** [comment]
- Improve No data available (copy or UI)

Let's please update it:

- Recognized tokens: `Rate unavailable`
   - + tool tip on hover at (?): `Exchange rate is currently not available.`
- Unrecognized tokens: _item not shown at all_

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.5.0 (689d17eca3f6ca0ab3810aba732390abecfed841)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
