### ISSUE TITLE
Trigger reset flow during recovery

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#10443]
Discussion [here](https://satoshilabs.slack.com/archives/CKN5C51CJ/p1703161937364569?thread_ts=1699624093.877649&cid=CKN5C51CJ).

Should be done together with https://github.com/trezor/trezor-suite/issues/10424.

**Comment by komret** [comment]
Closing in favour of https://github.com/trezor/trezor-suite/issues/12881. Suite will not set the device label automatically, only the user can do that. If it is not set, Suite will display device name (Trezor Model T etc.). Setting the device label was the original reason to open this issue, so I believe it can be closed now.
