### ISSUE TITLE
Ethereum discovery not working on particular passphrase

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10444]
**Describe the bug**
See video, its happening only on this passphrase. 
Other passphrases i already tested worked fine.
Replicated on multiple computers and devices /web and app/

```
{
  "id": 10,
  "success": true,
  "payload": {
    "path": [
      2147483692,
      2147483708,
      2147483648,
      0
    ],
    "serializedPath": "m/44'/60'/0'/0",
    "childNum": 0,
    "xpub": "xpub6DwvgyytvWLrKvWKivZKCeqhi7UKBLwd6NUFRJw3PkUCvFD8JPVhWKc18Mng4qV4xguKY7UK3D8mDAJDWcFEKK5vYmHik35LY5Yap5bGZ5e",
    "chainCode": "aea115b9cb795e34b283932bc551db94cfbda6d28a6ab97c4fd60a7d660077ab",
    "publicKey": "0204af221846e3e7e5239d8744cae655bfdf80673455f28a0ec8e75fe6db19619b",
    "fingerprint": 945378181,
    "depth": 4
  }
}
```

**Steps to reproduce:**
1. Add passphrase wallet
2. Perform discovery
3. Observe

**Info:**
 - Suite version: desktop 23.12.3 (8fd6a446f2f03d4c8407e1f5f97a804f315a0253)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.12.3 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33

**Expected result:**

**Screenshots:**
https://youtu.be/wzNcmQanxkI

**Comment by bosomt** [comment]
**QA NOK** https://eth1.trezor.io/
**QA OK**  https://eth2.trezor.io/

**Comment by marekrjpolak** [comment]
The error is caused by `null` value of `gasPrice` in a pending tx, received from backend. It's pretty easy to fix in Suite, but that could hide the real cause somewhere else.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (e3e4c163e7af37542ce0a550285fc0a792e6a161)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2T1 2.6.4 regular (revision 1f693d3561c375661563970e066f678590abc19c)
 - Transport: BridgeTransport 2.0.33
