### ISSUE TITLE
Show address as one string

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10440]
Change the appearance of the Receive address on final screen with QR code to be in one string
a. because of Bitcoin cash - the chunked address looks really weird
b. to stay consistent with Trezor Suite

Apply on Connected Trezor Confirmed address and on Portfolio tracker Receive address. 

**Acceptance criteria:**
Confirmed receive address is displayed as one string
Receive address in portfolio tracker is displayed as one string

**Comment by Nodonisko** [comment]
I personally don't like this, because it basically cause change address before my eyes but whatever :D

**Comment by mnuky** [comment]
we will solve the transition in different issue, this is temporary solution, we have to find more scalable solution.

**Comment by bosomt** [comment]
**QA OK**

24.01.1 (673)
96d12a4 - [develop] - fix(suite): fix label drop for RBG transactions
Android 13 - Nothing phone 1
