### ISSUE TITLE
Cardano address mismatch

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#10449]
Address mismatch on cardano. 

**Steps to reproduce:**

1. Connect device with all-seed and wait for discovery to finish (or load all cardano accounts)
2. Generate receive address on `Cardano #3` account
3. Confirm and go back
4. Generate new address on the same account and you will get address mismatch

**Comment by matejkriz** [comment]
related? https://github.com/orgs/trezor/projects/58/views/6?pane=issue&itemId=48767630

**Comment by matejkriz** [comment]
> related? https://github.com/orgs/trezor/projects/58/views/6?pane=issue&itemId=48767630

It wasn't related...

**Comment by bosomt** [comment]
**QA OK**

24.01.1 (673)
96d12a4 - [develop] - fix(suite): fix label drop for RBG transactions
Android 13 - Nothing phone 1
