### ISSUE TITLE
Suite doesn't switch backends when one is not available

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#10463]
**Describe the bug**
Suite doesn't switch backends when I have 2 set up and one is available and the other one is not.
More info here: https://www.notion.so/satoshilabs/Suite-backend-fallback-test-63eb68c6f15a41ca99e4177e74e365a8

**Info:**
 - Suite version: desktop 24.1.0 (ed53f9f5caf12b7fce24bc17b74043e4c1e6d448)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.1.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
Suite correctly switches to the backend that is working (not timed out)

**Actual result:**
Suite doesn't switch to available backend.

**Note(s):**
More info here: https://www.notion.so/satoshilabs/Suite-backend-fallback-test-63eb68c6f15a41ca99e4177e74e365a8
and probably related to https://github.com/trezor/trezor-suite/issues/10460

**Comment by marekrjpolak** [comment]
It's a feature. Namely, _sticky backend_ feature - once you've successfully connected and the connection got lost, you always try to reconnect to the same backend, as there could be specific pending txs, fiat rates etc...

We've discussed to relax this feature - after some time and/or retries, sticky backend could be abandoned.

**Comment by Hannsek** [comment]
@marekrjpolak Can we close it then?

**Comment by Dehumanizer77** [comment]
no, we want to change it, it doesn't make sense to keep connecting to the same backend if it's down...

**Comment by bosomt** [comment]
Can we consider to fixing this issue ?
We need to raise priority due to multiple issues due to Ethereum back-ends DDOS attacks

**Comment by marekrjpolak** [comment]
I'm working on a prerequisites (moving backend reconnecting from Suite to Connect) and thinking/waiting for proposals when to abandon the sticky backend.

**Comment by STew790** [comment]
**QA OK**
Tested together with @Dehumanizer77 . The backends switches correctly.

**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
