### ISSUE TITLE
Android app freezes for few seconds during welcome flow - after consent screen

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10487]
When you go through the Welcome flow and click on Confirm button on Analytics tracking screen, app freezes for few seconds. See the video:
https://drive.google.com/file/d/1kM-VCsaIRtD-OyxgeQfpAHW5JgwU05Ew/view?usp=drive_link

**Comment by bosomt** [comment]
**QA OK**

 24.01.1 (682)
be06d91 - [develop] - fix(suite-native): correct error for firmwareless device (#10635)
