### ISSUE TITLE
Trezor suite does not correctly display the details of an XRP transaction when it comes from a disabled address

### ISSUE THREAD

**Issue by stefanostatuti** [trezor/trezor-suite#10496]
**Describe the bug**
Trezor suite does not correctly display the details of an XRP transaction when it comes from a disabled address but shows a generic "Unknown transaction"
For example it doesn't show who sent transaction, the amount received and the relative value in fiat currency. These informations are also missing in transaction's detail popup.

**Info:**

-   Remembered Wallet: NO
-   Suite Version: app/web
-   Browser: Firefox, version 121.X
-   OS: Windows, version 11
-   Bridge: version latest
-   Firmware Version: model 'Universal'

**How to reproduce**

1. Go to an received XRP transaction from a deactived account
2. See missing transaction infos

**Expected behavior**
Transaction informations should be shown (maybe labeling the sending address as deactivated)

**Screenshots**
![img1](https://github.com/trezor/trezor-suite/assets/4499372/1458143e-40c0-4100-853b-76a8abea7446)
![img2](https://github.com/trezor/trezor-suite/assets/4499372/18d6c1df-330d-408d-a19e-9d0d349b86ab)

**Additional context**

**Comment by Hannsek** [comment]
@marekrjpolak can this be connected to your edits?

**Comment by marekrjpolak** [comment]
No.

**Comment by marekrjpolak** [comment]
In Trezor Suite, we currently support and properly display only basic XRP transactions of type `Payment`, while, [according to documentation](https://xrpl.org/accountdelete.html), this is type `AccountDelete`.

**Comment by stefanostatuti** [comment]
hi, thanks for reply. Checking in another XRP explorer i can see the full history of this address:
- the most recent received transaction is made with TransactionType: "AccountDelete"
- the "middle transaction" is the flare redeem movement/sending with "TransactionType": "AccountSet" and too in this case nothing is shown
- the older transaction has TransactionType: "Payment"
![XRPL Explorer rHhPauSFqwfg](https://github.com/trezor/trezor-suite/assets/4499372/6f09926d-a519-43cd-b207-d960d404ae8c)

**Comment by MiroslavProchazka** [comment]
Hi, thank you for reaching out. Currently, we have no plans to add those transaction types in Trezor Suite.
