### ISSUE TITLE
Device security check neg. result screen is overflowing in some languages

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#10492]
**Describe the bug**
In some languages, the contents of the device security check's negative result screen overflow the frame. Please see the screenshots.

**Info:**

-   Suite Version: app 23.12.3
-   OS: MacOS 14.2.1 (23C71)
-   Firmware Version: T2B1 2.6.4

**How to reproduce**

1. Wipe your Suite app data
2. Resolve the analytics screen
3. Switch app to Spanish in Settings, exit settings
4. Connect a T2B1 (enter PIN if needed)
5. One the "¿Has utilizado este Trezor antes?" ("Have you used this Trezor before?") screen choose the "No, no tengo dudas." ("No I haven't") option.
6. Observe the text and button overflowing the frame (shring the window to smaller if needed, but it's visible already at 1800 px)

**Expected behavior**
All the contents should stay in the given frame including proper paddings. See English variant for correct view if needed.

**Screenshots**
![Snímek obrazovky 2024-01-04 v 15 48 36](https://github.com/trezor/trezor-suite/assets/88533514/161e35e2-792b-4136-97c4-3fa31148a956)

![Snímek obrazovky 2024-01-04 v 16 02 03](https://github.com/trezor/trezor-suite/assets/88533514/9272e37c-d964-4edd-b4f2-6ba7c2115ceb)

![Snímek obrazovky 2024-01-04 v 15 48 51](https://github.com/trezor/trezor-suite/assets/88533514/62b32bb9-60ff-4f67-95eb-3ad4d5c641b1)

**Additional context**
It seems that long copy in the primary CTA button breaks the layout.

**Comment by Hermez-cz** [comment]
Related Slack discussion: https://satoshilabs.slack.com/archives/CKN5C51CJ/p1703860418027819

**Comment by MiroslavProchazka** [comment]
I will check possibilities of letters limit for translations and follow up on that.

**Comment by MiroslavProchazka** [comment]
Let's wait until the Suite redesign and then re-check whole app for similar issues.
