### ISSUE TITLE
App accesibility

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#10502]
Accessibility report from google play warns about couple of buttons. 
<img width="1083" alt="image" src="https://github.com/trezor/trezor-suite/assets/36101761/cfdc6f7c-5a62-455c-bb4a-4feb97420e86">

**Comment by bosomt** [comment]
**QA OK**

24.01.1 (673)
96d12a4 - [develop] - fix(suite): fix label drop for RBG transactions
Android 13 - Nothing phone 1
