### ISSUE TITLE
cardano cleanup backwards compatibility branches

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#10504]
we are bumping min fw version in connect to 2.4.3 for cardano methods in #10493

there are numerous backwards compatibilty code branches that can now be removed.

**Comment by bosomt** [comment]
**QA OK**

cardano and tests cardano claiming/staking/sending/receiving
works as expected with current 2.7.3 FW

2.4.0 fw reports `Firmware update required`

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.4.0 regular (revision ea3596ad8)
 - Transport: BridgeTransport 2.0.33
