### ISSUE TITLE
Review: Trezor Modal abort button is not well aligned

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#10518]
<img width="468" alt="Screenshot 2024-01-05 at 12 34 09" src="https://github.com/trezor/trezor-suite/assets/858321/2b564e72-8113-4b18-93e2-d336585c63c0">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (a09bff7b9a570ce41acce14bf96627d44dbf8e77)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
