### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1051]
Style 404 page. Now user appearing here accidentally has no choice but adjust url manually. We should add menu at least.

**Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5e3052eef2b7959777be5d1d)

**Comment by glacierbits** [comment]
broken layout


<img width="1013" alt="Screen Shot 2020-04-13 at 18 01 20" src="https://user-images.githubusercontent.com/29627086/79136184-e05b0900-7db0-11ea-9c89-4ebc180f47df.png">
