### ISSUE TITLE
Review: Replace some secondary buttons with tertiary ones

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#10529]
We added tertiary style for buttons and in previous design. Right now some of the designs, especially in modals with two buttons looks very weird:

<img width="870" alt="Screenshot 2024-01-05 at 14 19 06" src="https://github.com/trezor/trezor-suite/assets/858321/6fcba8a4-e58f-45b6-853d-d9fda32a4c9b">

<img width="837" alt="Screenshot 2024-01-05 at 14 22 26" src="https://github.com/trezor/trezor-suite/assets/858321/90c79939-cdbf-42bb-a3a0-079c67149d08">

<img width="1211" alt="Screenshot 2024-01-05 at 17 20 23" src="https://github.com/trezor/trezor-suite/assets/858321/23a0bddf-7225-4d44-a139-a2f5b8ddb0bf">

<img width="1217" alt="Screenshot 2024-01-05 at 17 22 35" src="https://github.com/trezor/trezor-suite/assets/858321/893e17b7-08a6-49bf-8183-7ece95dd20f0">

<img width="793" alt="Screenshot 2024-01-05 at 14 25 13" src="https://github.com/trezor/trezor-suite/assets/858321/3e3f9353-9d0c-4d79-8e06-56bb0719dc69">

<img width="1009" alt="Screenshot 2024-01-08 at 14 37 51" src="https://github.com/trezor/trezor-suite/assets/858321/02a70e4d-3e42-4096-b81e-85a47c90729c">

These whole modal should be polished a bit.

We should keep primary button and other one should be tertiary.

Vscode regexp for check:

`<Button(.(?!>)|\n|\t)*variant="tertiary"`

**Comment by AdamSchinzel** [comment]
1. What are you suggesting to polish on the last screenshot apart from the buttons? I think it looks okey
2. Imho would keep the receive and buy buttons that are visible on dashboard page when tx history is empty as they are
3. You draw some lines on the first image, you wanted to show by that what please?

**Comment by jvaclavik** [comment]
> 1. What are you suggesting to polish on the last screenshot apart from the buttons? I think it looks okey

Back should be `tertiary` variant
Contact support should be `primary`

Also alignment is a bit weird. My proposal is to set Contact support as the first button with full width and back as a second one aligned in the center. But I'm just guessing here.

> 2. Imho would keep the receive and buy buttons that are visible on dashboard page when tx history is empty as they are

I agree, it looks different now

> 3. You draw some lines on the first image, you wanted to show by that what please?

It should follow our new modal designs. More info here: 
https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A31645&mode=design&t=fKRmGnO7Zlekcjiy-1
