### ISSUE TITLE
Discovery of tokens does not work properly

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10525]
Steps to reproduce:
1. Connect Trezor which has some ERC20 tokens
2. Let the discovery finish
3. Go to My assets
4. You see only ETH account
5. Click on ETH account and go back to My Assets
6. ERC20 token appear

See the video:
https://drive.google.com/file/d/1uKZBK_WzUSnfV_RK1ClwXI9RodQFwbM8/view?usp=sharing

**Comment by bosomt** [comment]
**QA OK**

 24.01.1 (682)
be06d91 - [develop] - fix(suite-native): correct error for firmwareless device (#10635)
