### ISSUE TITLE
Review: Polish Recovery check modal

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#10522]
<img width="867" alt="Screenshot 2024-01-05 at 14 31 49" src="https://github.com/trezor/trezor-suite/assets/858321/7d2d7ddf-8e10-4ab8-8931-8456bc8e79b0">

design
<img width="501" alt="Screenshot 2024-01-09 at 15 09 04" src="https://github.com/trezor/trezor-suite/assets/858321/dd97424e-c512-4e81-842e-2b25578d16fa">

**Comment by AdamSchinzel** [comment]
I think that it just lacks button for closing. Wdyt?

![CC7115FD-D473-4357-9338-CCCB26F91DB9](https://github.com/trezor/trezor-suite/assets/66002635/69020665-dd12-460d-b2d7-d3b02d465ec4)

**Comment by jvaclavik** [comment]
Yes, and I think Close button should be primary button here and aligned to the left. These 3 lines should be on the right like in design above

**Comment by AdamSchinzel** [comment]
The alignment is not according to the design at all so I guess maybe this could be intentional @dahaca

**Comment by dahaca** [comment]
> The alignment is not according to the design at all so I guess maybe this could be intentional

if you mean the alignment of the steps, I am confused myself, since there are 2 variants in Figma, already dropped a comment.

![image](https://github.com/trezor/trezor-suite/assets/45338719/9e12b08a-fad4-408f-b740-0dc135a13567)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
