### ISSUE TITLE
PIN 4 - Do not show the PIN matrix on Trezor One until the app is opened and unlocked

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10538]
Current behaviour:
When user connects Trezor One to mobile, right away the PIN matrix is initialized. 
But the app shows the "biometric" unlock first. It may be confusing, that app shows unlock by Biometric and Trezor displays PIN matrix. 

Acceptance criteria:
When user connects the Trezor One, the PIN matrix is displayed after app is opened and unlocked

**Comment by STew790** [comment]
**QA OK**
PIN matrix on device and on host are shown basically at the same time.

**Info:**
App version 24.4.0 https://github.com/trezor/trezor-suite/commit/d39f66ef539bc1a8944cb3c88f6ac0610649350e
Android
