### ISSUE TITLE
Review: ButtonGroup for orientation

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#10533]
<img width="972" alt="Screenshot 2024-01-05 at 17 16 47" src="https://github.com/trezor/trezor-suite/assets/858321/119984fe-e6ae-4407-980c-9aa731819552">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
