### ISSUE TITLE
PIN 2 - wrong entry of PIN does not work after 3rd attempt

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10536]
Steps to reproduce:
1. Connect Trezor One to App
2. Insert wrong PIN for first time - app shows error message
3. Insert wrong PIN for second time - app shows error message
4. Insert wrong PIN for third time - app does not tell you anything and the PIN matrix disappear from trezor device

**Comment by STew790** [comment]
**QA OK**
Failed the PIN 6 times with no issue.

**Info:**
App version 24.4.0   https://github.com/trezor/trezor-suite/commit/d39f66ef539bc1a8944cb3c88f6ac0610649350e
Android
