### ISSUE TITLE
Review: blur amounts better

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#10534]
- Big values are too visible while they are blurred. Increase the `intensity` of `HiddenPlaceholder` where needed.

<img width="700" alt="Screenshot 2024-01-05 at 17 19 36" src="https://github.com/trezor/trezor-suite/assets/858321/a36a8502-da82-4fe6-b042-be27f22c5a4a">

**Comment by dahaca** [comment]
Added a [follow-up issue](https://github.com/trezor/trezor-suite/issues/10567) with out-of-the-scope further improvement.
