### ISSUE TITLE
Review: Fix content overflowing on Welcome screen

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#10540]
<img width="1010" alt="Screenshot 2024-01-08 at 14 35 24" src="https://github.com/trezor/trezor-suite/assets/858321/ae5b5dd9-7c75-4d23-bd79-35169dddd92b">

**Comment by dahaca** [comment]
Closing and moving to and already opened https://github.com/trezor/trezor-suite/issues/10108 so all welcome page bugs are in one place.
