### ISSUE TITLE
Empty portfolio tracker settings tab bar

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#10546]
Missing tab bar or back button in settings in portfolio tracker with no accounts imported

Steps to reproduce:
1. On iOS, open portfolio tracker which is empty with no coins imported
2. Go to settings
3. You cannot go back to homescreen

There should be a go back button or tab bar for user to navigate back.

**Comment by bosomt** [comment]
**QA OK**

tested on latest iOS dev build 24.1.1
