### ISSUE TITLE
Update the Trade page

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#10557]
I have left a bunch of comment in Figma with directions, hopefully that would provide more clarity! The designs might be updated soon if Ondra has time for it, let me know if any info is missing.

- [x] [Core section](https://www.figma.com/file/pewjlOfequOKYVC6h3v0YL/%5BEmpower-%231%5D-UI-Library-%26-Global-Navigation?type=design&node-id=8423-16902&mode=design&t=kjolSWNKovWkleuP-4)
- [x] [Offers section](https://www.figma.com/file/pewjlOfequOKYVC6h3v0YL/%5BEmpower-%231%5D-UI-Library-%26-Global-Navigation?type=design&node-id=3276-177456&mode=design&t=kjolSWNKovWkleuP-4)
- [x] [Checkout section](https://www.figma.com/file/pewjlOfequOKYVC6h3v0YL/%5BEmpower-%231%5D-UI-Library-%26-Global-Navigation?type=design&node-id=8424-16995&mode=design&t=kjolSWNKovWkleuP-4)
- [x] Move [this](https://github.com/trezor/trezor-suite/blob/334fcb95f64d748d1028861e45744335a68e1f87/packages/suite/src/views/wallet/coinmarket/savings/setup/index.tsx#L131) to `onClick` as it's not broken

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (3ba71cbdf7a956185ce627ecd7aa0364ad35fc0b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
