### ISSUE TITLE
Accounts Page polish

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#10556]
* use `Card` for the trade section
* adjust the trade section. Do not use the ButtonGroup though. On mobile keep the current layout 
![image](https://github.com/trezor/trezor-suite/assets/45338719/e646ba2a-b7b0-4b72-ae41-06ea134b38a6)

* remove background from the transaction date header + do not make months ALL CALS
<img width="240" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/9b372755-ab36-433c-a835-cb428cc647f4">

* bring the transaction actions closer
<img width="166" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/3751ae84-69bf-4d41-8be2-22dbd8d2207f">

* remove custom card paddings from transactions, the graph and the account stat cards
* add `min-width: 170px` to the "Show public key" button to align better 
* make the loader for the wallet holdings larger 
![image](https://github.com/trezor/trezor-suite/assets/45338719/17caeeb6-0e62-4e68-8975-c7faef3f0166)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
