### ISSUE TITLE
enlarged fonts check

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10562]
Adjust the newly implemented UI (connect trezor and receive features) so it works with font enlarging accessibility settings builtin both Android and iOS.

**Comment by bosomt** [comment]
**QA OK**

high contrast + biggest font in accessibility settings 

24.01.1 (673)
96d12a4 - [develop] - fix(suite): fix label drop for RBG transactions
Android 13 - Nothing phone 1
