### ISSUE TITLE
Review: Redesign exchange/send/receive buttons

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#10570]
<img width="434" alt="Screenshot 2024-01-09 at 14 21 42" src="https://github.com/trezor/trezor-suite/assets/858321/c16264e3-a0c4-4f03-b982-8fa640dbd2df">

**Comment by dahaca** [comment]
Already done as a part of the [Send Page redesign](https://github.com/trezor/trezor-suite/pull/10517) + should be re-written properly and become global as a part of the [last batch of changes](https://github.com/trezor/trezor-suite/issues/9881) to the layout.
