### ISSUE TITLE
Review: Showing address issues

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#10576]
- icon alignment
- monospace font (the proper one like in `develop` branch) 🙏 

<img width="761" alt="Screenshot 2024-01-09 at 14 54 40" src="https://github.com/trezor/trezor-suite/assets/858321/e996acf2-5277-4ac8-9e16-55e385bc6b6c">

<img width="774" alt="Screenshot 2024-01-09 at 14 56 11" src="https://github.com/trezor/trezor-suite/assets/858321/70bcf57c-b35c-4e5e-854b-5a71e362bd4a">

<img width="761" alt="Screenshot 2024-01-10 at 16 02 29" src="https://github.com/trezor/trezor-suite/assets/858321/71a2ae9b-51ea-4ca6-aa2b-404e5c85d9d3">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
