### ISSUE TITLE
Review: Fix alignemnent in Wallet switching

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#10572]
<img width="833" alt="Screenshot 2024-01-09 at 14 39 00" src="https://github.com/trezor/trezor-suite/assets/858321/58b93913-59e9-4f5a-bdaf-d191ca7952a3">

**Comment by peter-sanderson** [comment]
Seems that it is already fixed 
![image](https://github.com/trezor/trezor-suite/assets/152899911/81be5e52-61f6-4d43-862c-43bf6d722a21)
