### ISSUE TITLE
Provide APK downloads of Trezor Suite Lite mobile app

### ISSUE THREAD

**Issue by CodeShakingSheep** [trezor/trezor-suite#10586]
While expectedly many individuals will download Trezor Suite Lite from Google Play Store / Apple Store, it is crucial to ensure the availability of the app beyond the confines of these platforms. Therefore, provide PGP-signed APK releases on GitHub.

**Comment by matejkriz** [comment]
Yes, we're definitely planning on it, it's just not a top priority right now. Closing as duplicate of https://github.com/trezor/trezor-suite/issues/5728 and https://github.com/trezor/trezor-suite/issues/9475
