### ISSUE TITLE
Disallow cancel on connecting screen

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#10598]
**Steps to reproduce:**

1. Connect device
2. Loading screen pops up indicating connect flow was initialized
3. Click on close
4. UI indicates flow was cancelled, but device hangs as unacquired device

**Acceptance criteria:**
Remove close button

**Comment by bosomt** [comment]
**QA OK**

24.01.1 (681)
e089477 - [develop] - feat(suite-native): empty states copy (#10630)

* feat(suite-native): empty states copy

* feat(suite-native): search again

* feat(suite-native): different icons

* fix(suite-native): receive copy
