### ISSUE TITLE
Discrepancy between modal and device display when sending  transaction with additional data

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10593]
**Describe the bug**

Some coins allow to attach additional data when sending transaction. 
During transaction confirmation modal asks you to confirm recipient and data but device asks you to confirm data first and receive address as second.

**Steps to reproduce:**
1. Send ETC transaction that include data
2. Observe device and modal behavior

**Info:**
 - Suite version: desktop 24.1.1 (cd3946024cb2233e2e80788ea25784b83daa0a06)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="620" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/34812ed4-5b0d-47dd-949d-2f878790b016">

<img width="548" alt="Screenshot 2024-01-10 at 14 41 34" src="https://github.com/trezor/trezor-suite/assets/31506317/dca732ce-5a12-42cd-b16c-448154e83fd3">

<img width="528" alt="Screenshot 2024-01-10 at 14 41 42" src="https://github.com/trezor/trezor-suite/assets/31506317/d1474343-3f34-4fd3-ab8c-a8da5dc49827">

**Comment by MiroslavProchazka** [comment]
@tomasklim Can you please investigate a little bit where might be the problem? We will decide about the solution after that.

**Comment by bosomt** [comment]
Retested with model T with same results

![telegram-cloud-photo-size-4-5855074060323635142-y](https://github.com/trezor/trezor-suite/assets/31506317/9173514c-64b5-4b55-89f6-358d55043ae4)

**Comment by bosomt** [comment]
same problem when unstaking Eth
device says data but modal says recipient address

<img width="638" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/e190c5cd-ef11-496d-ad7e-3fd32fedc6e9">


@sime

**Comment by sime** [comment]
@bosomt the upcoming FW release has custom screens for staking. When you have time, please use them.

**Comment by sime** [comment]
@bosomt the upcoming FW release has custom screens for staking. When you have time, please use them.

**Comment by bosomt** [comment]
@sime i will retest later with new firmware, so far i get `Transaction signing error: Definition is outdated` with new version.

**Info:**
 - Suite version: web 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.6.5 regular (revision a784c4046e79ae138f9a7a9c5e97d2f6771140eb)
 - Transport: BridgeTransport 2.0.33

**Comment by tomasklim** [comment]
@bosomt is staking ok now?

**Comment by bosomt** [comment]
- staking **QA OK**
- sending data **QA NOK**
@tomasklim Staking modal vs display was already fixed 🎉 

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.5.0 (5b29898216a6008533a9b540cf3b00891598c9a6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
