### ISSUE TITLE
PIN 1 - Handle locked device

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#10596]
1. Connect device
2. Enter PIN
3. Wait till Trezor get locked (10 min by default, can be shorten to 1 min)
4. Try to interact with the Trezor

For TT and TS3 it somehow works, user can enter the PIN on the device and then interaction continues, it's just not optimal UI - no indication in app, that you have to enter PIN. But for T1 it's not working at all, user have to reconnect the device.

Design: https://www.figma.com/file/KvbZGG16li6BA90Xtpf0BP/Device-interaction?type=design&node-id=265-19536&mode=design&t=bvxgE0PCvWE8fjXH-0

**Comment by STew790** [comment]
**QA NOK**
When I lock the device and click on receive address and show receive address, T1 shows me the PIN matrix but the app just doesn't react at all.

**Info:**
App version 24.3.1 cc7d18e
Android

**Comment by matejkriz** [comment]
> **Info:** App version 24.3.1 [cc7d18e](https://github.com/trezor/trezor-suite/commit/cc7d18ed3f02caf46636bf68ebefd6ac48cac287) Android

@STew790 You are testing on (or referencing) wrong version, it should be 24.3.2 23371adc93aff4949506959b478ebf47647eb5e2

**Comment by STew790** [comment]
**QA OK**
It is ok on develop

**Info:**
App version 24.4.0 d39f66e
Android
