### ISSUE TITLE
Enable Biometric for Android when there are both options

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10608]
Some Android phones have Biometric options via Finger print or Face recognition. 
Current version of the app offers user to enable FaceID which is wrong because FaceID is name for iOS biometric.
Also when user clicks on Enable - native Android system gives user a choice which option he would like to use

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=21883%3A118651&mode=design&t=QkyqMXkr8OImc9kj-1 

**Acceptance criteria:**
When user with android phone which offers both biometric options to unlock the app goes through the welcome flow, we display adequate prompt.

**Comment by bosomt** [comment]
**QA OK**

24.2.0 (709)
c12a2a8 - [develop] - wip commit to get the develop build
