### ISSUE TITLE
Review: receive modal warning no backup

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#10615]
This is a step before address reveal if wallet is not backed up, Imo it is really empty...
![1ACDA46A-1253-49C0-87C1-DB028A5E880F](https://github.com/trezor/trezor-suite/assets/66002635/68aee554-0372-47ad-80fe-7e298656baf6)

**Comment by dahaca** [comment]
a use case for the `DialogModal`
