### ISSUE TITLE
App promo in dark mode

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#10613]
Cleared up the issue because a lot of dark-mode things have been solved by #10140 

I think I would be better to do some lighter dark color.

![1DB61EBC-2108-4ED1-98C9-FF2E7B3DCA2E](https://github.com/trezor/trezor-suite/assets/66002635/d2872e06-3cc4-419c-b25d-da9da6ecc334)

**Comment by dahaca** [comment]
> Bit weird...

This component is already being fixed by @jvaclavik as a part of the Review page update :) Crossing it out.
