### ISSUE TITLE
App shows wrong message with unitialized Trezor device

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10611]
When user connects Trezor device which is not initialized, it shows this message: 
![Image](https://github.com/trezor/trezor-suite/assets/84183817/f34e5cf3-53ba-4141-8dd0-0062a271e982)

Please replicate if it's really happening

Right behaviour - app should show this message:
https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=4068%3A24715&mode=design&t=ZuRUCmI0UfkzRx3u-1

**Comment by STew790** [comment]
Unfortunately, the message is indeed incorrect. It shows the same for me too.
Just connect uninitialized device and you will see this message.

24.01.1 (677) develop version

**Comment by bosomt** [comment]
**QA OK**

4.01.1 (682)
be06d91 - [develop] - fix(suite-native): correct error for firmwareless device (#10635)
