### ISSUE TITLE
XPub displayed in receive flow

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10619]
**Describe the bug**
During the receive flow with connected device, there is sometimes account xpub displayed instead of the receive address.

**Screenshots**

https://github.com/trezor/trezor-suite/assets/26143964/bd6b40ea-7fde-4a65-a8bb-917ac42f2e69

**Comment by bosomt** [comment]
**QA OK**

24.01.1 (681)
e089477 - [develop] - feat(suite-native): empty states copy (#10630)

* feat(suite-native): empty states copy

* feat(suite-native): search again

* feat(suite-native): different icons

* fix(suite-native): receive copy
