### ISSUE TITLE
 Solana enabled when using older bitcoin only firmware

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10612]
**Describe the bug**
Solana enabled when using older bitcoin only firmware.
As soon you install new one Solana is not displayed anymore

**Steps to reproduce:**
1. Connect device with 2.6.3 bitcoin only firmware
2. observe settings/coins section

**Info:**
 - Suite version: desktop 24.1.1 (66325e1a9834a4e8f59eea9bb893bda13ca4470d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 bitcoin-only (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

_2.6.4_
<img width="707" alt="Screenshot 2024-01-11 at 11 27 35" src="https://github.com/trezor/trezor-suite/assets/31506317/a6884482-7b2f-4449-a9d7-bf9509f944c6">
<img width="683" alt="Screenshot 2024-01-11 at 11 27 32" src="https://github.com/trezor/trezor-suite/assets/31506317/8889da8f-ee76-484d-8e43-6141706a2d1b">

_2.6.3_
<img width="646" alt="Screenshot 2024-01-11 at 11 25 47" src="https://github.com/trezor/trezor-suite/assets/31506317/185fc89d-9ef6-4acd-b73c-98a4d14303eb">
<img width="1080" alt="Screenshot 2024-01-11 at 11 25 42" src="https://github.com/trezor/trezor-suite/assets/31506317/4ce21849-d15c-4bec-9e9a-c41622002f80">

**Comment by MiroslavProchazka** [comment]
Might be caution during future adding of new coins -  we need to adjust the logic.

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/f4437eb4-d71a-42a6-a789-267b0e8ace1c)

**Info:**
 - Suite version: desktop 24.11.0 (e65d214d92f513962e8322d8cabd9bf63e320b79)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Device: Trezor T1B1 1.12.1 bitcoin-only (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 3.0.0-bundled.24.11.0
