### ISSUE TITLE
Copy iOS welcome flow - step Generate receive address contains Verification which is not true

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10628]
Steps to reproduce:
1. Open the iOS app with the welcome flow
2. Go to step Receive
3. There is text saying Generate and verify addresses directly on your Trezor to get paid and receive crypto on the go
4. Correct copy: Generate addresses and QR codes to receive crypto on the go.

Note: make sure that this copy stays on Android where user can actually verify the address on Trezor

![Image](https://github.com/trezor/trezor-suite/assets/84183817/9496ba47-7406-4cf0-9b63-43d406d45f78)

**Comment by bosomt** [comment]
**QA OK**

24.01.1 (442)
