### ISSUE TITLE
Discovery skeletons overflow

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10620]
**Describe the bug**
While discovery, the loading skeletons are overflowing their parent component. See the video attached. 

**Screenshots**

https://github.com/trezor/trezor-suite/assets/26143964/97727038-6dab-4e91-a949-db3b5dd360d7

**Comment by bosomt** [comment]
**QA OK**

Android 13 - Nothing phone 1 
24.01.1 (685)
6793f0f - [develop] - chore(suite): move usePasswords hook to hooks folder
