### ISSUE TITLE
Change copy in empty states

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#10627]
https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=21849-149340&mode=design&t=Kxa1igP9zVBcjqYs-11

**Comment by bosomt** [comment]
**QA OK**

24.01.1 (681)
e089477 - [develop] - feat(suite-native): empty states copy (#10630)

* feat(suite-native): empty states copy

* feat(suite-native): search again

* feat(suite-native): different icons

* fix(suite-native): receive copy
