### ISSUE TITLE
Closing and opening the app causes icons in accounts modal to disappear

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#10634]
**Describe the bug**
When I go to, for example, my BTC accounts modal and close the app and then open it again, the icons in the modal disappear.

**Info:**

Version 24.01.1 (680) commit https://github.com/trezor/trezor-suite/commit/7a1500b6984908655e5d492c5ce8b0d7e3648290
Android 12

**How to reproduce**

1. Connect device
2. Wait for the discovery to finish
3. Open bitcoin accounts modal
4. Close the app
5. Open it again and there are no icons in the modal

**Expected behavior**
Icons are still showing after closing and opening the app.

**Screenshots**
![Screenshot_2024-01-12-13-07-27-473_io trezor suite develop](https://github.com/trezor/trezor-suite/assets/48477147/0f29fcb0-5f4f-425c-b4ef-308c15ebb69b)

**Comment by bosomt** [comment]
**QA OK**

Android 13 - Nothing phone 1 
24.01.1 (685)
6793f0f - [develop] - chore(suite): move usePasswords hook to hooks folder
