### ISSUE TITLE
Graph value is cropped when user goes from Home to My Assets and back

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10639]
The graph at Home screen does not show the balance correctly after tapping “My assets” and then “Home”.

![Image](https://github.com/trezor/trezor-suite/assets/84183817/dff7c307-2c94-40ae-9c12-cdce5ee68430)

**Comment by bosomt** [comment]
**QA OK**

24.2.0 (709)
c12a2a8 - [develop] - wip commit to get the develop build
