### ISSUE TITLE
Graph shows balances when the total balance is "0"

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10632]
Steps to reproduce:
Connect All seed device to mobile app
1. Wait for discovery to finish
2. Total balance shows 0
3. Graph shows balances
4. Tap on the graph move on it
5. Total balance still displayes 0

App version: 24.01.1

See the video: 

https://github.com/trezor/trezor-suite/assets/84183817/042ec9b7-b69a-46d3-9809-8c21956b3ad6

**Comment by bosomt** [comment]
**QA OK**

 24.2.0 (692)
abae3b8 - [develop] - chore(suite-native): track breadcrumbs for sentry on screen change (#10680)
