### ISSUE TITLE
Wipe device with webusb transport

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1064]
Steps to reproduce

- transport webusb 
- model t1 
- onboarding -> create new wallet
- settings -> wipe device
- no we see fallback screen for uninitialized device, which leads to onboarding again -> go to onboarding
- try to create new wallet
- now get error "device disconnected"

Probably needs fix in trezor-link. Webusb transport uses device_id as path, which changes after device wipe internally but is not propagated to more high level layers (connect, suite).

**Comment by bosomt** [comment]
@mroz22 + there is not button to connect webusb device, so even when you reconnect your device then you are not able to continue ;(
