### ISSUE TITLE
Canceling FaceID to unlock the app "glitches" the FaceID and makes it unusable for the whole iPhone

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#10647]
**Describe the bug**
When you fail the FaceID scan and then cancel the "retry" of it, it somehow "glitches" the FaceID but not only for the app but for my whole phone. I was unable to use the FaceID to unlock my iPhones (15 for a couple of minutes, then it was OK but 11 just wouldn't work and I had to actually restart it to make it work again).

**Info:**

-   Mobile Suite Version: version/commit
-   OS: name, version

**How to reproduce**

1. Fail FaceID to unlock your app
2. Cancel the retry of the FaceID
3. FaceID in app starts "glitching"

**Expected behavior**
I think the cancelling of the FaceID should maybe close the app? 

**Screenshots**

https://github.com/trezor/trezor-suite/assets/48477147/8bab4688-63e9-4f24-bf57-d3d4ba865da1

**Comment by mnuky** [comment]
@STew790 does it also happen on current Production version of the app?

**Comment by PeKne** [comment]
I am afraid it does...

**Comment by STew790** [comment]
@mnuky Yes, it does, unfortunately.

**Comment by vytick** [comment]
we'll use https://www.figma.com/file/RlWH784CRUIvooy8aq6XoR/Main-Flow?type=design&node-id=628-20028&mode=design

**Comment by STew790** [comment]
**QA OK**
I just tried it and the "flow" is a little different and I can click on the "Use FaceID" button that is new.

iOS 24.3.1 (cc7d18e)
