### ISSUE TITLE
Update FAQ content

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10641]
**Android:**
Question: My Trezor device can't connect
1. Reconnect your Trezor
2. Use a different USB data cable
3. Use a different mobile device
4. Enable connection for Trezor Suite Lite via phone system message

Question: What version of Trezor device Firmware Trezor Suite Lite supports?
- Trezor One: from version 1.12.1
- Trezor T: from version 2.6.3
- Trezor Safe 3: from version 2.6.3

Question: Are my data safe?
- Delete the question

New question: What is View-only?
Even when your Trezor device is disconnected, you can still keep track of your balances with the View-Only. This feature provides peace of mind by allowing you to monitor your funds without compromising security. Plus no more waiting for retrieving all the assets and balances while connecting your Trezor device.

**iOS**
Question: Are my data safe?
- Delete the question

**Comment by mnuky** [comment]
@juriczech  QA NOK, answers are not complete - check the printscreen. Question "My Trezor device can't connect" - the answer is cropped. Question "What version of Trezor device Firmware Trezor Suite Lite supports?" - The answer is not complete

![Image](https://github.com/trezor/trezor-suite/assets/84183817/069fa624-9c78-4acc-85ac-250c7a988495)

**Comment by STew790** [comment]
**QA NOK**
This is still the same in version 24.5.1 https://github.com/trezor/trezor-suite/commit/319a98a62131c0d0ddd2eb238cb8530a540764a3

**Comment by juriczech** [comment]
@STew790 So far, the fix is only in develop. Could you please test there?

**Comment by STew790** [comment]
Tested in develop and it's better but I can't click on the arrows even though they will highlight and the info is still cropped:
![image](https://github.com/trezor/trezor-suite/assets/48477147/10f8b7bd-5bb5-4c0e-9f97-523fb33ce7fe)

Redmi Note 9 Pro 
Android 12

**Comment by matejkriz** [comment]
> Tested in develop and it's better but I can't click on the arrows even though they will highlight and the info is still cropped: ![image]

It should be fixed, right, @juriczech? https://github.com/trezor/trezor-suite/pull/12548

**Comment by juriczech** [comment]
@trezor/qa @matejkriz Yes, fixed.

**Comment by STew790** [comment]
**QA OK**
LGTM now 
![image](https://github.com/trezor/trezor-suite/assets/48477147/6c3b9178-9df5-4145-a58b-319b8f501e4a)

24.5.0 73206d2
