### ISSUE TITLE
Add Brazilian Portuguese as a community language

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#10649]
Brazilian Portuguese has been translated in Crowdin, please add it to suite as a community language.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.0 (81d011d6dc01c0135cb38b989270cec8b9f74a57)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: BridgeTransport 2.0.33
