### ISSUE TITLE
Re-aquire device functionality is missing

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#10645]
Noticed that a test is failing because of:

`AssertionError: Timed out retrying after 20000ms: Expected to find element: "[data-test="@menu/switch-device/refresh-button"]", but never found it.`

Turns out the ability to [re-acquire a device](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/components/suite/Preloader/SuiteLayout/NavigationBar/DeviceSelector/DeviceSelector.tsx#L177) had been lost when `DeviceSelector` was re-written. 

[Figma](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=125-22036&mode=dev)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.2.0 (2acb84bb22f134bdaef4e2706a6e1041fe277ab1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
