### ISSUE TITLE
Add new coin 2 - add account with type selection

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#10676]
Add new account:

When user wants to add new coin to be in the app, he can create it via "+" button on My asset page
User can choose from available coins for the connected device
BTC like coins - user must choose account type
ETH like coins - user does not need to choose the account type
User can’t create new account if the previous one has no transactions
Maximum number of accounts under one coin is 10

Polish UI for adding new account based on updated design 👇 

https://www.figma.com/file/BVA3IAmqDjz36sBGVtEFbz/Add-new-coin-%2F-Account?type=design&node-id=280-19249&mode=design&t=bZP0odolbHL26WAW-0

**Comment by bosomt** [comment]
**QA NOK**

account type is ignored, even i chosen legacy for LTC and taproot for BTC i see that default account was added /not by account label by address prefix/



![Image](https://github.com/trezor/trezor-suite/assets/31506317/325d2657-9018-4770-b090-19ba82f97b12)



![Image](https://github.com/trezor/trezor-suite/assets/31506317/0ad39fa0-8b96-4e2c-89cd-37e87658aec7)



Android 14 Nothing phone 1 
24.4.0 cd82750

**Comment by vytick** [comment]
Fixed via:
https://github.com/trezor/trezor-suite/pull/11661

**Comment by bosomt** [comment]
**QA OK**

checked on BTC and LTC accounts

Release notes for 24.4.0 (72)
Last commit hash: 7296f1a74998c3ae5648eb066e43f87e0259a13c
