### ISSUE TITLE
Add new coin 3 - via receive

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#10677]
Via Receive

When user clicks on Receive, he sees available coins with active accounts
User can click on (+)  and sees all available coins
If user chooses coin and type we activate the coin (add coin) on his behalf
User continues to receive address verification
When user leaves the Receive address flow and comes back to My assets, he sees new account activated

https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=5751-26317&mode=design&t=LZOvpJ69q35KpYKk-0

**Comment by bosomt** [comment]
**QA OK**

+ is present and active in `Receive` tab

Android 14 Nothing phone 1 
24.4.0 cd82750
