### ISSUE TITLE
QR Code with dark mode

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10674]
### **Describe the bug**
The border of the QR code on the receive screen is too narrow. Sometimes if you try to scan a QR code with dark mode enabled, the reader can not recognize the code.

### **How to reproduce**

1. Enabled dark theme
1. Open the receive screen with the address QR code
1. Try to scan the QR code with a low quality camera code reader

### **Expected behavior**
- The QR code is always recognized even when is the dark mode on.

**Comment by shenkys** [comment]
Solution: Add 12px border in dark mode to the QR code and see whether it helps. Hard to test. My awful motorola reads it just fine

**Comment by bosomt** [comment]
**QA OK**

Android 14 - Nothing Phone 1
24.3.1 (24) dev version 6e9d8d6
