### ISSUE TITLE
Add new coin 1 - Add coin with default account type

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#10675]
Add new coin:

When user wants to add new coin to be in the app, he can create it via "+" button on My asset page
When user clicks on the "+" he can choose from available coins for the connected device
When user chooses coin, new coin with default account type is added

https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=5601-17951&mode=design&t=LZOvpJ69q35KpYKk-0

**Comment by bosomt** [comment]
**QA OK**

Release notes for 24.4.0 (72)
Last commit hash: 7296f1a74998c3ae5648eb066e43f87e0259a13c
