### ISSUE TITLE
Better format of date headers in Transaction list

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10683]
Current date format in Transaction list displays only Month which is confusing for users if they don't have that many transactions and they see e.g. February, March, February, March

[Design here](https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?node-id=1317-10005&node-type=frame&t=Hypij8sd56oCxzkc-11)

**Comment by shenkys** [comment]
Design done [here](https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?node-id=1317-10005&node-type=frame&t=Hypij8sd56oCxzkc-11)

**Comment by STew790** [comment]
**QA OK**
LGTM
![Image](https://github.com/user-attachments/assets/4f4b9185-ab29-44b3-b6d1-74ae2c2bebae)
![Image](https://github.com/user-attachments/assets/cb4ceab3-0e8e-4088-b024-de7651838503)

**Info:**
Android 25.1.1 132e7c6
