### ISSUE TITLE
Tertiarry Button is not working well on the different elevations

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#10689]
This is hovered button (it disappears).

![image](https://github.com/trezor/trezor-suite/assets/152899911/8321c20e-fe2b-43f6-a0d5-a5db64b3ea73)

Problem is that we are missing color-tokens for different buttons

see: 
- `packages/components/src/components/buttons/buttonStyleUtils.ts`
- and `packages/theme/src/colors.ts`

![image](https://github.com/trezor/trezor-suite/assets/152899911/1a66b35f-83b8-47ba-9200-e76a1ff44fec)

**Comment by MiroslavProchazka** [comment]
cc @peter-sanderson we have the dedicated color codes for this, so it might be a quick fix. Anyway I put it to Phase 2, so let's skip it for now
