### ISSUE TITLE
Enabling Send Max on desktop does not re-render the label properly

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#10681]
The input label does not react to the `send max` toggle populating the input with a value on the desktop

![image](https://github.com/trezor/trezor-suite/assets/45338719/c79da68b-2480-4943-b648-c94f71e28a6a)

_Originally posted by @dahaca in https://github.com/trezor/trezor-suite/issues/10517#issuecomment-1887540840_

**Comment by peter-sanderson** [comment]
Here it is doing weird flicker when on the Web. (When you turn it ON-> OFF and then ON again. On video you can see as it fully hides value and shows the Placeholder and then sets value again.

This maybe causes some re-rending and glitches the CSS placeholder or something.

[Screencast from 2024-01-25 16-40-17.webm](https://github.com/trezor/trezor-suite/assets/152899911/795b3682-e544-480a-afd2-6ec86c072e0e)

**Comment by MiroslavProchazka** [comment]
Text "Částka" should be placeholder, not a label.

**Comment by peter-sanderson** [comment]
@jvaclavik @MiroslavProchazka 

Removing the duplicate "Amount" placeholder is just "half-solution". The same place is used for this. 

![image](https://github.com/trezor/trezor-suite/assets/152899911/dddecd37-9cb0-4642-a436-febb1fb0517b)
