### ISSUE TITLE
Define colors for Skeleton animation for different elevations

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#10697]
[Figma](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=3811-20716&mode=design&t=uxIM5mikL8NBhxXP-4) for the skeletons

See: `packages/components/src/components/skeletons/utils.ts`

this code:

```ts
export const shimmerEffect = css`
    animation: ${SHINE} 1.5s ease infinite;
    background: linear-gradient(
        90deg,
        ${({ theme }) =>
            `${theme.gradientNeutralBottomFadeSurfaceElevation1Start}, ${theme.gradientNeutralBottomFadeSurfaceElevation1End}, ${theme.gradientNeutralBottomFadeSurfaceElevation1Start}`}
    );
    background-size: 200%;
`;
```

Needs to take Elevation into account and animate it with different colors.

**Comment by peter-sanderson** [comment]
What about just doing it on elevation+1?

**Comment by dahaca** [comment]
Update 1

* skeletons should definitely have updated sizes and border radii
* David shared [this](https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=13592-82679&mode=design&t=C1ZySV9ogk9CiV1Y-4) Figma for mobile, with an example [prototype](https://www.figma.com/proto/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?page-id=5212%3A30121&type=design&node-id=14455-107614&viewport=-3996%2C336%2C0.35&t=zR5lYN1fYYzuSUUQ-1&scaling=scale-down&starting-point-node-id=14455%3A107614&show-proto-sidebar=1&mode=design). What's missing is that the color shades are not added to the list of semantic tokens. As soon as this is done, this issue will get updated!
