### ISSUE TITLE
Connect: blockchain-methods: add "identities"

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#10696]
add param to create a new websocket connection for blockchain methods in connect.

**Comment by bosomt** [comment]
**QA OK**

https://www.notion.so/satoshilabs/Separate-Blockchain-link-identities-for-ETH-9ad42f1fb75240b4a75c11b5198f5b91?pvs=4

**Info:**
 - Suite version: desktop 24.5.0 (babb748ecaefda0dddfac8b1257feaf7ff57500b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.5.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
