### ISSUE TITLE
Save Bitcoin - invalid calculation

### ISSUE THREAD

**Issue by martykan** [trezor/trezor-suite#10695]
**Describe the bug**
The "Save Bitcoin" feature has a summary that shows how much you'll save up in a year, however the calculation does not work. 

**Info:**

 - Suite version: desktop 24.1.2 (b529bd13d2d6d77c065a09828ef0bbfa206ef7d8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.2 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
-   Remembered Wallet: yes

**How to reproduce**

1. Go to BTC -> Trade -> Save Bitcoin
1. Select any frequency/amount
1. See the incorrect sum of 0.00 BTC / 0.00€

**Expected behavior**
See the correct calculation in BTC and fiat

**Screenshots**
<img width="742" alt="Screenshot 2024-01-17 at 13 28 58" src="https://github.com/trezor/trezor-suite/assets/8833813/b3fd4b64-5bae-4a67-9844-54b110e3d63b">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.6.5 regular (revision a784c4046e79ae138f9a7a9c5e97d2f6771140eb)
 - Transport: BridgeTransport 2.0.33
