### ISSUE TITLE
Transaction history: Unknown transaction is blank

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1072]
xrp testnet account on all* seed, `tx.type === 'unknown'`
https://test.bithomp.com/explorer/F9D288367754A9E89990D1664E701B030B024E8C2054F1DA2A7924B1261AA883
<img width="563" alt="Screenshot 2020-01-21 at 15 54 23" src="https://user-images.githubusercontent.com/6961901/72815131-76760c00-3c66-11ea-8047-e752170058ef.png">

**Comment by slowbackspace** [comment]
huh, can't find it now. probably fixed.

**Comment by bosomt** [comment]
@slowbackspace i will send you passphrase, please check it with all seed

![image](https://user-images.githubusercontent.com/31506317/78782349-2cb5db80-79a2-11ea-989e-129a55e09adf.png)

and

![image](https://user-images.githubusercontent.com/31506317/78782377-38090700-79a2-11ea-9e8e-cc8fbed5d5f3.png)

**Comment by bosomt** [comment]
but i dont see any unknown transaction :)

**Comment by bosomt** [comment]
moved to rejected till cards are fixed by @slowbackspace

**Comment by slowbackspace** [comment]
> moved to rejected till cards are fixed by @slowbackspace

it is not related to this issue :)
I created a new issue with the problem you mentioned
https://github.com/trezor/trezor-suite/issues/1495

**Comment by bosomt** [comment]
moving to approved ;)
