### ISSUE TITLE
Select's Menu component is not rendered properly at times

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#10720]
_note:
likely it is related to Portals_  

Hint: If drop-down menu is opened during discovery, after discovery finishes -> the menu jumps to the corner 

![image](https://github.com/trezor/trezor-suite/assets/152899911/ffb592ce-a0a6-42dd-9bd7-8c6fc5bd4865)

**Comment by peter-sanderson** [comment]
@jvaclavik you reported this as well, so just FYI

**Comment by dahaca** [comment]
Also reported in other places ⬆️ ⬆️ ⬆️

**Comment by jvaclavik** [comment]
According to my testing, it could also relate to using Select inside of Modal – or maybe in general with components that are using also portal.
It Custom backends this bug happens when it's in the modal, but when I delete it it's not happening.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.1 (d1eda6c68c4619a7060f1fcc8033ee44c4a94a03)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.2.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by MiroslavProchazka** [comment]
I'm reopening this issue due to a similar bug that can be found during a dry run of recovery seed on T1. 
Attaching video of the problem: 



https://github.com/trezor/trezor-suite/assets/152851523/64ac5b64-714c-436a-97ea-9c905da1bbc1

**Comment by MiroslavProchazka** [comment]
Another place where it is happening - 

![Image](https://github.com/trezor/trezor-suite/assets/152851523/5945ce3e-1679-4564-81c6-fce05cf22674)

**Comment by peter-sanderson** [comment]
- This is the [last commit before Empower was merged](https://github.com/trezor/trezor-suite/tree/fb80938756e8e1bc74e130e5353c443926ca2718)
- It works on this commit

**Comment by STew790** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.4.0 (a0556d2e0c123ad3080ce3df4accaa47e9d39021)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.32
