### ISSUE TITLE
Discovery error on Ethereum

### ISSUE THREAD

**Issue by quickplaymobile** [trezor/trezor-suite#10730]
**Describe the bug**
Trezor Suite fails to load Ethereum wallets.

**Info:**

-   Remembered Wallet: yes
-   Suite Version: Both app/web, commit [24.1.2]
-   Browser: Chrome, Latest
-   OS: Windows 11, Latest
-   Bridge: Latest
-   Firmware Version: model:one, latest version

**How to reproduce**

1. Go to Trezor Suite.
1. Insert Pin
1. Bitcoin loads while Ethereum Throws error.
1. Can't access or interact with my Ethereum wallets on trezor suite.

**Expected behavior**
Show both wallets Bitcoin And Ethereum.

**Screenshots**
![ss](https://github.com/trezor/trezor-suite/assets/11901639/caadea78-ddb1-4f63-a408-1d10cf4d2d6f)

**Additional context**
Is Ethereum getting removed from Trezor? I love Ethereum more than I like Bitcoin and removing Ethereum from Trezor Suite would be just bad. I mainly purchased it to hold my Ethereum Coins.

**Comment by mroz22** [comment]
champs down in the basement managed to roll out some update to mitigate this ongoing ddos attack. did it help?

**Comment by bosomt** [comment]
**QA OK**

fixed and released and tested at Friday

**Comment by quickplaymobile** [comment]
Confirm Solved
