### ISSUE TITLE
Wallet graph (v.1)

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1074]
- [ ] Graph [shown](https://sketch.cloud/s/AK1WY/a/WOMWGg) / [hidden](https://sketch.cloud/s/AK1WY/a/3gKdwD)
- [ ] Tooltip on hover: _Rate updated (time) ago_
- [ ] Styling 

Zeplin **[here](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5e79c9bc8b52437106eac048)**

**Comment by glacierbits** [comment]
Added _Styling_ as todo in the issue description. To be the same visual style as graph on Dashboard.

**Comment by bosomt** [comment]
@slowbackspace 

was it merged ? i see graph and and transaction when i hover over graph, except it's different type compared to zepelin

can you please notify us when you close it ?

**Comment by slowbackspace** [comment]
> @slowbackspace
> 
> was it merged ? i see graph and and transaction when i hover over graph, except it's different type compared to zepelin
> 
> can you please notify us when you close it ?

Just so there is no confusion. If this is an issue for graph on Dashboard page (zeplin linked in the description). It is not merged yet. 
edit: oh this IS the issue for transactions graph, nevermind.

Regarding the graph in transactions tab, there is no design for it. Behaviour is mostly like graph in mytrezor (merged) with a bit of styling shared with dashboard graph (not merged).

So I'll ping you when both lands in develop branch.

**Comment by glacierbits** [comment]
<img width="746" alt="Screen Shot 2020-04-14 at 12 42 36" src="https://user-images.githubusercontent.com/29627086/79216444-72b0ea80-7e4d-11ea-8760-df2726530183.png">

**Comment by slowbackspace** [comment]
edit: nevermind

**Comment by sorooris** [comment]
QA NOK
Chromium 80, Firefox 74
version: internal alpha release, [web](https://suite.corp.sldev.cz/suite-web/develop/settings/)

**Show/hide graph**: OK.

**Tooltip on hover**: NOK.
Couldn't find anywhere on page, hovering on the graph displays the following:
![image](https://user-images.githubusercontent.com/10185314/79481218-78eec480-800f-11ea-8bdf-6cd57722340b.png)

**Styling**: NOK.
I'm really missing some designs, for example on how the dates in the "month" option should be displayed (the dates are displayed really close to each other when the browser window size is near the breakpoint)...
QA could greatly benefit with a note saying how these cases that aren't present in the design were solved.
![image](https://user-images.githubusercontent.com/10185314/79480168-0cbf9100-800e-11ea-965c-4b28a1063b54.png)

**Also** the same minor visual bug that appears in the dashboard graph is present.
![image](https://user-images.githubusercontent.com/10185314/79480419-53ad8680-800e-11ea-9018-fb487557b69c.png)

**Comment by glacierbits** [comment]
QA FYI work continues in #1613 hence moving to Approved.

**Comment by sorooris** [comment]
ok, ack
