### ISSUE TITLE
Application startup modal

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1075]
The step between _Welcome screen_ and _Onboarding_ with analytics opt-in.

**Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa1af7734c3d9725eb2300)

**Comment by glacierbits** [comment]
Broken layout. 
<img width="1440" alt="Screen Shot 2020-02-06 at 19 12 44" src="https://user-images.githubusercontent.com/29627086/73965822-201af580-4915-11ea-82e1-dfab777a1347.png">

**Comment by mroz22** [comment]
fixed

**Comment by bosomt** [comment]
works fine for me,
no idea how to test if it works or not ;)

**Comment by sorooris** [comment]
[develop](https://suite.corp.sldev.cz/suite-web/develop/)
QA NOK:
1) Learn more link redirects to a [404](https://suite.corp.sldev.cz/suite-web/develop/todo%20some%20link).
2) Switching on the Data collection switch does not store any (anonymous) data.

**Comment by glacierbits** [comment]
FYI seperate issues #1441 and #1443 have been created to fix this. Moving to Approved. Thanks!

**Comment by glacierbits** [comment]
Naughty text is getting handsy with the toggle. 

<img width="555" alt="Screen Shot 2020-04-10 at 11 30 04" src="https://user-images.githubusercontent.com/29627086/78980772-e20d9e00-7b1e-11ea-95c3-04633b4f949d.png">

**Comment by bosomt** [comment]
in linux app we are missing test of data collecting purpose  in startup modal
probably related to size of window during app start


![image](https://user-images.githubusercontent.com/31506317/79463718-7ed9ab00-7ff9-11ea-800f-39bfcdf1543d.png)

browser OK

![image](https://user-images.githubusercontent.com/31506317/79463783-91ec7b00-7ff9-11ea-9593-08c0af6861b0.png)

**Comment by slowbackspace** [comment]
@bosomt  try to redownload the app. binary is synced from develop branch and it might be the case that copy was not synced yet

**Comment by bosomt** [comment]
@slowbackspace looks ok now
