### ISSUE TITLE
Missing default wallet label 

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#10768]
The default wallet name is now missing from the wallet switcher. MIght be cause by [this commit](https://github.com/trezor/trezor-suite/commit/2d9dc8f872f4f731857809bc8ad18a2addfc139c) but not guaranteed 🙏 

<img width="300" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/81599f31-39e9-4919-ad38-241c2ce987d1">

<img width="300" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/e21510cd-0126-4454-94f1-4bca33ea1099">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
