### ISSUE TITLE
Abandon the use of BIP-69

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-suite#10765]
**Introduction**
At the R&D meeting on 23rd January 2024 with @prusnak, @hynek-jina and @Hannsek we decided to abandon the use of BIP-69 in Suite. The reasons for this decision are that:
- Sorting outputs according to BIP-69 means that users may have to confirm them on Trezor in a different order than how they entered them.
- According to [1] Electrum and Trezor Suite are the only wallets that use BIP-69. We implemented BIP-69 when it seemed that everyone will be using it, but now almost no one uses it, so it's actually making Trezor more easy to fingerprint instead of making it harder. There is also a pretty convincing discussion about this topic in the Bitcoin core repository, see [2].

For a full discussion on Slack see [3].

**Specification**
When creating a transaction Suite will:
- select the UTXOs for transaction inputs as it does now, but instead of sorting them, it will randomly shuffle them,
- maintain the order of the transaction outputs as the user entered them, and
- insert the change-output at a random position among the outputs, e.g. if there are 2 user-entered outputs, then pick a random number from the range [1, 2, 3] to decide whether the change-output should be the first output, go in between the two user-entered outputs, or be the last output.

[1] https://ishaana.com/blog/wallet_fingerprinting/
[2] https://github.com/bitcoin/bitcoin/issues/12457
[3] https://satoshilabs.slack.com/archives/CKZHV2G13/p1704713827631289

**Comment by bosomt** [comment]
@peter-sanderson @andrewkozlik is there way to test this issue in Suite ?

**Comment by andrewkozlik** [comment]
QA:
- Check that if a transaction has multiple outputs, then they are shown on Trezor in the same order as they were entered in Suite.
- Check that fee bumping works correctly. Both bumping a small transaction and a "Send max" transaction.

**Comment by bosomt** [comment]
**QA OK**

1.
- 4 outputs , 4 match device vs Suite ✅ 
- and bump ✅ [transaction](https://tbtc1.trezor.io/tx/abc99809526976de470398ed6e50b5e68bf0bd9359e2cc6bc57438e5e9c09285)

2.
- send all ✅  
- and bump [transaction](https://tbtc1.trezor.io/tx/6fad639033963a5c0e704a796225f1ef5b5d80b5a4a697b6de7a9cfcb55f858f) /No funds left for fee. Final amount needs to be reduced to bump fee/

**Info:**
 - Suite version: desktop 24.11.0 (661633dc3f8f690c3338fe5f47da748a1c374525)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Transport: BridgeTransport 3.0.0-bundled.24.11.0
