### ISSUE TITLE
Error when rebooting to bootloader device with outdated firmware

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10776]
**Describe the bug**

`Error: ui-device_firmware_old` error when rebooting to bootloader device with outdated firmware

**Steps to reproduce:**
1. Connect device with firmware/bootloader that does not support reboot to bootloader
2. Start firmware update
3. Observe error

**Info:**
 - Suite version: desktop 24.1.2 (b529bd13d2d6d77c065a09828ef0bbfa206ef7d8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.2 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.10.0 regular (revision f4424ece1ccb7fc0d6cad00ff840fac287a34f07)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/83e05bd1-3a06-4685-bf85-027706082ae9

**Comment by MiroslavProchazka** [comment]
@komret Will you take a look at this please?

**Comment by bosomt** [comment]
Maybe it got broken when fixing this issue ?
https://github.com/trezor/trezor-suite/issues/9577

**Comment by komret** [comment]
Do I get this right that the update works and the issue is about the tooltip that shouldn't be there?

**Comment by STew790** [comment]
**QA OK**
Error not present when updating 2.5.3>2.6.4

**Info:**
 - Suite version: desktop 24.3.0 (0aa33ed34c5ded3b67310af8e3931501e91ce1f5)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
