### ISSUE TITLE
Closing bottom sheets on tap outside

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10775]
At the moment only way how to close bottom sheet or device navigator is by clicking on the close button. It should close also if you click outside of the sheet.

## Current behaviour
https://github.com/trezor/trezor-suite/assets/26143964/1bae98f7-1afb-4e43-a142-7d34571014a7

## Acceptance criteria
When user click outside of the bottom sheet or top device menu, it is closed.

**Comment by bosomt** [comment]
**QA OK**

 24.2.0 (710)
ef9d565 - [develop] - feat(suite-native): close sheets by click outside (#10778)
