### ISSUE TITLE
Bottom sheet does not stick to bottom edge

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10777]
**Describe the bug**
- If you drag the bottom sheet down and then up without releasing the finger press, you can drag it higher than the default position.

**How to reproduce**

1. open any bottom sheet
2. drag it a little bit down
3. drag it up
4. the bottom sheet does not stick to the bottom edge anymore

**Expected behavior**
There is never space between the bottom sheet and the bottom edge of the screen.

**Screenshots**

https://github.com/trezor/trezor-suite/assets/26143964/628ac149-cfd9-447b-98c5-9075adb0b7c6

**Comment by juriczech** [comment]
Before implementing, let's discuss within team whether it could be useful to outsource bottom sheets through using a library for that.

**Comment by PeKne** [comment]
Ok, will you open the discussion?

**Comment by juriczech** [comment]
I'd just leave that on the person who takes this issue for implementation. If it's me, yes, but no need to discuss it in advance IMO. Let's discuss later when it's relevant.

**Comment by bosomt** [comment]
**QA OK**

24.2.0 (709)
c12a2a8 - [develop] - wip commit to get the develop build

**Comment by bosomt** [comment]
**QA OK**

24.2.0 (709)
c12a2a8 - [develop] - wip commit to get the develop build
