### ISSUE TITLE
Adding token does not trigger fiat rate fetch

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#10771]
**Describe the bug**
When I add ERC-20 token in ETH account, it does not trigger fiat rate fetch automatically. However, in max 1 minute it is fetched correctly if available

**Info:**

-   Remembered Wallet: yes/no
-   Suite Version: 2024.1.2

<img width="587" alt="Screenshot 2024-01-24 at 9 59 40" src="https://github.com/trezor/trezor-suite/assets/33235762/4d448ebb-6787-4bbb-909f-3186115355b5">
After max 1 minute
<img width="572" alt="Screenshot 2024-01-24 at 9 57 44" src="https://github.com/trezor/trezor-suite/assets/33235762/9f0b1745-57d5-497b-989c-d79b49aa7cb6">

**Comment by tomasklim** [comment]
@AdamSchinzel 
Please also change wording in the `Add token` modal. I would get rid of `ERC-20`.
I guess it will also work for NFTs in the future. If we do not get rid of it now, we have to fix Polygon to have `MRC-20` there.
Try to ask @Hermez-cz and maybe add there some desc to the modal, it is kinda empty 😀
<img width="763" alt="Screenshot 2024-02-08 at 11 58 45" src="https://github.com/trezor/trezor-suite/assets/33235762/bc9682da-f02e-4f47-ba31-71a75663b317">

**Comment by bosomt** [comment]
**QA OK**

fiat rates are fetched as expected

Checked 24.2.3 and 24.3.0 and ERC20 is present in both version, probably needs to be released via crowdin translation tool ?
@tomasklim @AdamSchinzel please confirm

**Info:**
 - Suite version: web 24.3.0 (e43684addeef71a85cb3bfd945d2a701619363e6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Info:**
 - Suite version: desktop 24.2.3 (c7dd0f7b0d64ce2d06bbece30f746799bdc914c4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.2.3 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by AdamSchinzel** [comment]
> **QA OK**
> 
> fiat rates are fetched as expected
> 
> Checked 24.2.3 and 24.3.0 and ERC20 is present in both version, probably needs to be released via crowdin translation tool ?
> @tomasklim @AdamSchinzel please confirm
> 
> **Info:**
>  - Suite version: web 24.3.0 (e43684addeef71a85cb3bfd945d2a701619363e6)
>  - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
>  - OS: MacIntel
>  - Screen: 1663x1080
>  - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
>  - Transport: BridgeTransport 2.0.33
> 
> **Info:**
>  - Suite version: desktop 24.2.3 (c7dd0f7b0d64ce2d06bbece30f746799bdc914c4)
>  - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.2.3 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
>  - OS: MacIntel
>  - Screen: 1512x982
>  - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
>  - Transport: BridgeTransport 2.0.33

Translation strings were already updated, they are not just synced yet.
