### ISSUE TITLE
Onboarding flow

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1078]
**Zeplin** [here](https://zpl.io/VYo1Jxe)

**Comment by mroz22** [comment]
what should happen if:
- create new wallet call to device fails
- backup device call to device fails
- set pin call to device fails
- recover device call to device
- firmware update call to device fails
- user disconnects device on any step (probably different steps should have different behaviour)
- user connects different device than device previously connected on any step (probably different steps should have different behaviour)

**Comment by glacierbits** [comment]
@mroz22 I think we should have a back button here (if feasible).

<img width="841" alt="Screen Shot 2020-04-16 at 00 46 20" src="https://user-images.githubusercontent.com/29627086/79396331-f7018b80-7f7b-11ea-8c2a-cacd8e4465cc.png">
