### ISSUE TITLE
Do not fetch fiat rates for tokens without definitions

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#10783]
**Describe the bug**
Do not fetch fiat rates for tokens without definitions <img width="673" alt="Screenshot 2024-01-02 at 5 02 55" src="https://github.com/trezor/trezor-suite/assets/33235762/3c83b87d-f780-4c00-8e82-cbc7e7bc628c">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.3.0 (b05fc18e49fdf062f2c8db4e7f34dbd81dcd91e2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
Maybe we can consider not fetching tokens that are not available on Coingecko over and over again ?
We have one token thats not available and Suite tries to fetch it over and over again

https://etherscan.io/address/0xa74476443119A942dE498590Fe1f2454d7D4aC0d


<img width="854" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/e58a40e8-2f1e-4ac5-8a3c-66092f786555">


<img width="1102" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/1456cddb-7a5a-4841-828e-50a7ffe1bb7a">

**Comment by Hannsek** [comment]
Strange, if it is not in the definitions it should be in the `Unrecognized tokens` tab.

**Comment by sime** [comment]
It looks like a lovely edge case. [GNT](https://etherscan.io/address/0xa74476443119a942de498590fe1f2454d7d4ac0d) token has been replaced by [GLM](https://etherscan.io/address/0x7DD9c5Cba05E151C895FDe1CF355C9A1D5DA6429). From [CoinGecko](https://www.coingecko.com/en/coins/golem/usd): 

> GNT is migrating to GLM. Refer to https://blog.golemproject.net/gnt-to-glm-migration/. Contract address has changed from 0xa74476443119a942de498590fe1f2454d7d4ac0d to 0x7DD9c5Cba05E151C895FDe1CF355C9A1D5DA6429.

Both contracts are in our definitions. I guess CoinGecko knows it's no longer a valid token.

**Comment by Hannsek** [comment]
Ok, it will likely be solved in March when we release updated definitions.

**Comment by sime** [comment]
GNT>GLM migration was in 2020. I believe the contract will exist in our definitions for a while.

We may need some custom handling for deprecated but once valid coins.

There is a chance to optimise this handling, as @bosomt mentioned.
* When token fiat rates returns 40x, don't refetch
* Can we skip fiat rates for token balances of zero?

**Comment by Hannsek** [comment]
So far coingecko was doing ok job by removing the deprecated coins.

> When token fiat rates returns 40x, don't refetch
> Can we skip fiat rates for token balances of zero?

@tomasklim does it seem ok? do you have any other ideas which logic we can implement?
