### ISSUE TITLE
Error on signing signTypedData V4

### ISSUE THREAD

**Issue by vvvvvv1vvvvvv** [trezor/trezor-suite#10793]
**Describe the bug**
Error on signing signTypedData

**Info:**

-   Remembered Wallet: no
-   Suite Version: @trezor/connect-web
-   Browser: Chrome 120.0.6099.234
-   OS: MacOS 13.4
-   Bridge: how to check?
-   Firmware Version: Trezor T, 2.6.0

**How to reproduce**
1. set up a signTypedData V4 and send to device via connect-web, message as below

```json
{"types":{"EIP712Domain":[{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}],"SafeTx":[{"type":"address","name":"to"},{"type":"uint256","name":"value"},{"type":"bytes","name":"data"},{"type":"uint8","name":"operation"},{"type":"uint256","name":"safeTxGas"},{"type":"uint256","name":"baseGas"},{"type":"uint256","name":"gasPrice"},{"type":"address","name":"gasToken"},{"type":"address","name":"refundReceiver"},{"type":"uint256","name":"nonce"}]},"message":{"to":"0xa2036f0538221a77a3937f1379699f44945018d0","value":"0","data":"0xa9059cbb0000000000000000000000006b8a1e78ac707f9b0b5eb4f34b02d9af84d2b689000000000000000000000000000000000000000000000070292499f7db340000","operation":"0","safeTxGas":"0","baseGas":"0","gasPrice":"0","gasToken":"0x0000000000000000000000000000000000000000","refundReceiver":"0x0000000000000000000000000000000000000000","nonce":"35"},"domain":{"chainId":"1101","verifyingContract":"0x13854835c508fc79c3e5c5abf7afa54b4ccc1fdf"},"primaryType":"SafeTx"}
```

3. will get the error message as below

```
Invalid parameter "" (= {"path":"m/44'/60'/0'/0/0","data":{"types":{"EIP712Domain":[{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}],"SafeTx":[{"type":"address","name":"to"},{"type":"uint256","name":"value"},{"type":"bytes","name":"data"},{"type":"uint8","name":"operation"},{"type":"uint256","name":"safeTxGas"},{"type":"uint256","name":"baseGas"},{"type":"uint256","name":"gasPrice"},{"type":"address","name":"gasToken"},{"type":"address","name":"refundReceiver"},{"type":"uint256","name":"nonce"}]},"message":{"to":"0xa2036f0538221a77a3937f1379699f44945018d0","value":"0","data":"0xa9059cbb0000000000000000000000006b8a1e78ac707f9b0b5eb4f34b02d9af84d2b689000000000000000000000000000000000000000000000070292499f7db340000","operation":"0","safeTxGas":"0","baseGas":"0","gasPrice":"0","gasToken":"0x0000000000000000000000000000000000000000","refundReceiver":"0x0000000000000000000000000000000000000000","nonce":"35"},"domain":{"chainId":"1101","verifyingContract":"0x13854835c508fc79c3e5c5abf7afa54b4ccc1fdf"},"primaryType":"SafeTx"},"metamask_v4_compat":true,"domain_separator_hash":"00b399243bbd97a5429fcd244167b7ea04695d4b2a4e6f99517323a02f720dfa","message_hash":"0b9db5a9e7d087a85c66de3976a19d62e1d5de7ad7640e3bbb1438bfd23ef94e","method":"ethereumSignTypedData"}): Expected union value
```

**Expected behavior**
Can sign the typed message

**Screenshots**

**Additional context**
https://github.com/RabbyHub/eth-trezor-keyring/blob/main/index.ts#L517 here is the code how we call connect-web

**Comment by EV6999** [comment]
Got the same error.

**Comment by puruoni** [comment]
Same.
No longer able to sign in XEM, LTC, BCH, MONA, DOGE.
Response is "Expected union value".
<img width="1178" alt="nem sign" src="https://github.com/trezor/trezor-suite/assets/54670037/bd10b2f8-5f38-446a-a50c-d9ee7494e22f">

**Comment by mroz22** [comment]
thanks for report, this has now highest priority. looking into it. you can expect hotfix to be delivered today.

If you could please post any payloads which are expected to pass, it would be helpful. We tightenend validations so that they match types definitions but could be that your code relied on passing some non-conforming data. or it could be event something else.

**Comment by mroz22** [comment]
@puruoni your tx paylaod doesn't seem to match one of expected payloads here https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/types/api/nem/index.ts#L142. we can certainly loosen this validation if needed.

**Comment by mroz22** [comment]
as a temporary workaround, you can do 
```
TrezorConnect.init({
...
connectSrc: 'https://connect.trezor.io/9.1.9/'
});
```
to force legacy behavior

**Comment by mroz22** [comment]
We expect fix to be released in about 1 hour

**Comment by mroz22** [comment]
update is now online. please let us know if your problems persist.
also if you could please check whether your code complies with TrezorConnect typescript definitions. If yes, this kind of problems shuoldn't be hitting you.

**Comment by biafffff** [comment]
Tried to open a new Tx from my Safe, but still the same error:
* Open the Tx on Safe and click on _Sign_
* Rabby signing window pops out. Click on _Begin signing process_
* Trezor window (1) pops out. Enter PIN
* Trezor window (2) pops out empty. Infinite loading.
* Error message on Rabby "Transaction rejected"
```
Invalid parameter "" (= {"path":"m/44'/60'/0'/0/0","data":{"types":{"EIP712Domain":[{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}],"SafeTx":[{"type":"address","name":"to"},{"type":"uint256","name":"value"},{"type":"bytes","name":"data"},{"type":"uint8","name":"operation"},{"type":"uint256","name":"safeTxGas"},{"type":"uint256","name":"baseGas"},{"type":"uint256","name":"gasPrice"},{"type":"address","name":"gasToken"},{"type":"address","name":"refundReceiver"},{"type":"uint256","name":"nonce"}]},"message":{"to":"0xa2036f0538221a77a3937f1379699f44945018d0","value":"0","data":"0xa9059cbb0000000000000000000000006b8a1e78ac707f9b0b5eb4f34b02d9af84d2b689000000000000000000000000000000000000000000000070292499f7db340000","operation":"0","safeTxGas":"0","baseGas":"0","gasPrice":"0","gasToken":"0x0000000000000000000000000000000000000000","refundReceiver":"0x0000000000000000000000000000000000000000","nonce":"35"},"domain":{"chainId":"1101","verifyingContract":"0x13854835c508fc79c3e5c5abf7afa54b4ccc1fdf"},"primaryType":"SafeTx"},"metamask_v4_compat":true,"domain_separator_hash":"00b399243bbd97a5429fcd244167b7ea04695d4b2a4e6f99517323a02f720dfa","message_hash":"0b9db5a9e7d087a85c66de3976a19d62e1d5de7ad7640e3bbb1438bfd23ef94e","method":"ethereumSignTypedData"}): Expected union value
```

Should Rabby, Safe or I do something to get the update?

**Comment by mroz22** [comment]
hey @biafffff it should be enough to wait. it could be either some cache on your side, or possibly again our validation tightening which we will revert if this is really the case. @martykan is working on that.

**Comment by martykan** [comment]
@biafffff 
Can you try it now please? Maybe try closing/opening the browser as well first.  
I was testing it on my side on Safe+Rabby and signing worked.

**Comment by biafffff** [comment]
Agree @martykan! Was able to open and sign as usual. Thanks for the prompt fix.

**Comment by martykan** [comment]
Great, closing the issue. If anyone encounters this elsewhere feel free to reopen
