### ISSUE TITLE
Broken layering in the SectionItem component

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#10792]
After i've added a zIndex to the `SectionItem` in order to improve the setting anchor UI _(the yellow outline)_, it broke the Selects

<img width="272" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/4cd157fa-02c3-450b-93ea-e2536ec62487">

**Comment by peter-sanderson** [comment]
https://github.com/trezor/trezor-suite/pull/10604#discussion_r1465628882

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
