### ISSUE TITLE
When click on add hidden wallet, we need a modal that says "Follow instructions on device" where you turn on passphrase

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#10798]

**Comment by matejkriz** [comment]
@juriczech @shenkys do we have design for this? It should be universal for more cases, right?

**Comment by juriczech** [comment]
We don't. This is just placeholder issue so far. We will need a way for the mobile app to redirect the users attention to Trezor screen, however there is no such occurence in the app so far. What I mean by that is that both PIN form and receive flow (only 2 places redirecting users eyes to Trezor screen so far) are not using any universal component, so I'm just leaving this here and would be great to discuss before implementing design with @shenkys
