### ISSUE TITLE
Add a Tooltip for disabled Buttons during discovery 

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#10791]
**Description**
* there already exists a tooltip notifying that an element is disabled dues to a device being disconnected
* we need to add a new one for when a device is connected but a discovery is in process
* there's also an opportunity to create a shared component for the buttons in Settings which would be handling both the tooltip and `isDisabled` state.
* additionally there is an opportunity to create one more abstraction for a button which is disabled due to a device bein disconnected. I believe we have a bunch of those and they are not anyhow connected.

**Additional context**
More info here: https://github.com/trezor/trezor-suite/pull/10524#discussion_r1465201709

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.6.5 regular (revision a784c4046e79ae138f9a7a9c5e97d2f6771140eb)
 - Transport: BridgeTransport 2.0.33
