### ISSUE TITLE
Show / export log

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1079]
First version (Q1 Milestone) of this feature will only have 2 buttons (copy to clipboard + export log) and a toggle to include/exclude xPUBs. 

Next version (Q2 Milestone) is #239 

**Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f7ca6b4581f75605531)

**Comment by slowbackspace** [comment]
Related, discussion on what should be included in the log happened here: https://github.com/trezor/trezor-suite/issues/239

**Comment by mroz22** [comment]
duplicate with #239
