### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by shenkys** [trezor/trezor-suite#10804]
Let's discuss how might we approach different error communication in Mobile Suite. 

As of right now, we have no strict & solid structure for error recovery & communication. 

We've discovered that these cases would be worth thinking about: 
- Some coin's backend is down (all backends down now)
- You're not connected to the internet (all backends down now)
- You refuse to re-enter pin when device locks during discovery (infinite loading now)
- Add new coin / account with locked device
- Use current error communications as baseline. We should not only fix new issues, but also refactor the existing one. 
- Unable to fetch fiat rates for define timestamps (if there is a rate limit error on ANY coin)

Please, if you come accross this and have anything to add, feel free to add it to the list.  

Some [figma explorations](https://www.figma.com/file/KvbZGG16li6BA90Xtpf0BP/Device-interaction?type=design&node-id=470-6373&mode=design&t=VidCOK8Goq423l2S-11)

**Comment by matejkriz** [comment]
added "Unable to fetch fiat rates for define timestamps" 
![IMG_E31ECA5EA82A-1](https://github.com/trezor/trezor-suite/assets/3729633/5807883b-00df-417e-a2e7-7d2476c1a59f)

**Comment by matejkriz** [comment]
closing in favour of https://github.com/trezor/trezor-suite/issues/11562
