### ISSUE TITLE
Empower/Wrong font files

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10809]
The ones in prod. are moved a bit up, let’s use these please:[
 - Satoshi font

<img width="1000" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/841b8bba-c115-41ea-a512-c0b4aaab9a55">

**Comment by peter-sanderson** [comment]
@dahaca / @MiroslavProchazka I am not sure what to do, can you explain more?

Both address and `Received BTC` has this font:
![image](https://github.com/trezor/trezor-suite/assets/152899911/97811753-1d6e-4b26-9eed-4f279fd92d40)
