### ISSUE TITLE
Empower/Placeholder copy in Add account modal

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10810]
![Uploading 24-January-13-26@2x.png…]()

![image](https://github.com/trezor/trezor-suite/assets/152851523/4874514f-6c70-4ab2-a153-d91c42942987)

**Comment by dahaca** [comment]
Let's remove the placeholders to solve the issue and if needed the Copy team will update the copy. 

_cc: @b-irving_

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
