### ISSUE TITLE
Empower/Can’t enable labeling + no names for wallets in wallet switch

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10813]
# Can’t enable labeling + no names for wallets in wallet switch

Could be because of testing env.?

![image](https://github.com/trezor/trezor-suite/assets/152851523/8c8d2ca8-131f-4832-82a5-05700eddd8ee)
![image](https://github.com/trezor/trezor-suite/assets/152851523/ca58f241-1b0e-487b-9d2a-7496dd942e5f)

**Comment by peter-sanderson** [comment]
I believe this was fixed here https://github.com/trezor/trezor-suite/issues/10768
