### ISSUE TITLE
Empower/No wallet name in navbar when in passphrase wallet

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10814]
No wallet name in navbar when in passphrase wallet

In passphrase wallet instead of “🔗 Connected”, let’s show “🔗 [wallet name]”.
[Components in Figma](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A31386&mode=design&t=dDDckCeQTSS0DgJh-1)

![image](https://github.com/trezor/trezor-suite/assets/152851523/da010fed-dccf-401d-a67a-cb12bd3740a9)

**Comment by peter-sanderson** [comment]
@MiroslavProchazka it seems to me that its working.

![image](https://github.com/trezor/trezor-suite/assets/152899911/ef89a6e6-a013-4e21-860a-1d32d1428a24)
![image](https://github.com/trezor/trezor-suite/assets/152899911/19967ee2-6003-4bb7-bbab-74beb17a9d59)

**Comment by peter-sanderson** [comment]
Got it, when labeling is off: the default name of the passphrase wallet is not shown

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
