### ISSUE TITLE
Empower/Dashboard > Assets Card view wrong currency shown

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10811]
Shows both values in e.g. BTC. Top one should be fiat, bottom should be current asset’s currency.

![image](https://github.com/trezor/trezor-suite/assets/152851523/2bdf931f-9de6-4bb8-95f3-010b39cc4c1d)

**Comment by peter-sanderson** [comment]
This was fixed already in https://github.com/trezor/trezor-suite/pull/10788
