### ISSUE TITLE
Empower/Send form 

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10816]
Amount isn’t responsive:
![image](https://github.com/trezor/trezor-suite/assets/152851523/943e2d9a-725c-492c-b3bf-509663d43977)

lower prio:
Error happens too early:

- Either let’s wait some time, or do it on focus leave (+ amount too big)
- We can wait with this for future tho
![image](https://github.com/trezor/trezor-suite/assets/152851523/5aaec28d-6e7c-4e00-915f-fc936e904895)

Let’s flex advanced settings + add recipients to top instead of middle:
![image](https://github.com/trezor/trezor-suite/assets/152851523/a9f2fe71-c386-4427-a9ee-354e836346d9)

**Comment by Hannsek** [comment]
> We can wait with this for future tho

I don't think so, as not many people would send `>0. …` bitcoins.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
