### ISSUE TITLE
Empower/Settings promo banner isn’t responsive

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10812]
![image](https://github.com/trezor/trezor-suite/assets/152851523/299ceb9b-d326-4c46-8e95-713dcfe1f880)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.2.0 (d7f9480e15d050caeaffb33c2e8e09586d6b5ef3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
