### ISSUE TITLE
Add new coin 5 - edge cases

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#10827]
Handle edge cases:

- [ ] app is not connected to the internet when clicked add account
- [x] finding networks fails
- [x] error handling in general

**Comment by vytick** [comment]
Connection handling will be done later when we start introducing connection checks into the app.

After discussion with @sime I am closing this task and there will be a new one once we get there.

**Comment by bosomt** [comment]
**QA OK**

Release notes for 24.4.0 (72)
Last commit hash: 7296f1a74998c3ae5648eb066e43f87e0259a13c
