### ISSUE TITLE
Send coins - address and crypto amount form

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10823]
## Description
The goal of this issue is to develop a simple send form. So far the form has only two inputs: address and crypto amount. The other inputs have been ignored so far. There is not even the fee rate input, the fee is hardcoded to the `5 sats/byte`. Since the send form works only for BTC testnets, there should be no problem. But the form should be designed with the fact that there will be more input fields of different data types in the future (RBF, fiat value, fee, etc.)

> ℹ️ Since no design files are ready yet, this issue does not concern UI appearance. Any working form is enough.

## Acceptance criteria

- [ ] There are two inputs in the form:
  - address string input
  - amount number input
- [ ] both fields are on change validated
  - The address field shows an error if the input string is not a valid address
  - amount field shows an error if the input is not a valid number or if the amount exceeded the account balance

**Comment by PeKne** [comment]
Note for QA: After navigating to send screen via homescreen button "Send coins", it should be possible to select an account for sending an fill in "amount" and "address" form inputs. These two imputs should be correctly validated and inform the user if he filled in correct values.

**Comment by STew790** [comment]
**QA OK**
It correctly states if I have not enough funds or if I want to send something below the dust limit.
![image](https://github.com/user-attachments/assets/a524e153-fa59-48f3-beae-5e9dfd3f1d3e)

**Info:**

24.8.0 https://github.com/trezor/trezor-suite/commit/aceb3c7d3e1213eb9aa9fee3a62eca2c224862fd
