### ISSUE TITLE
Send coins - `module-send` package

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10822]
## Description
This issue prepares the ground for the send flow in mobile app. Not detailed implementation should be done yet in this stage.

> ⚠️ IMPORTANT! The send flow should work only with BTC TESTNET accounts. Mainnets and other coins will be revisited in a followup issues.

## Acceptance criteria

- [ ] new feature flag `isSendEnabled` added
  -  this flag is set to `true` only in `debug` and `develop` enviroments
- [ ] package `suite-native/send-module` is initialized
- [ ] SendStackNavigator created with following two screens:
  - [ ] `SendAccountsScreen` 
    - lists all the BTC testnet accounts of current device
    - on selecting account it redirects to the form screen with the selected account key inside of `route.params` object
  - [ ] `SendFormScreen` 
    - So far empty screen, will be revisited in the followup issue

**Comment by PeKne** [comment]
Notes for QA: After merging this. There should be a new Feature flag in the settings "Send". After enabling it, connect a device that contains Testnet account. After finishing the discovery and discovering TEST account a "Send coin" button should appear on the homescreen.

**Comment by STew790** [comment]
**QA OK**
- featuer flag is present and set up
- send button is visible 
- it is visible even before discovery is finished
- I am able to select from TEST accounts when I click on "Send"
**Info:**
24.8.0 aceb3c7
