### ISSUE TITLE
Empower/Wrong top+bot in some modal content paddings

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10849]
Viz. [[components in figma](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A31645&mode=design&t=dDDckCeQTSS0DgJh-1)](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A31645&mode=design&t=dDDckCeQTSS0DgJh-1)

Found in:

- Satety checks
- Add token
- Select labeling source
![image](https://github.com/trezor/trezor-suite/assets/152851523/d5be16a0-8cb7-49ee-b438-6602b0e623ee)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (d2613d7feb8922adaa8dabf60a2d393147a1e8ec)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
