### ISSUE TITLE
Empower/Dashboard > Assets List view

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10847]
Reference design: https://www.figma.com/file/mQhdQPKzdi93Swb8FNX9wL/branch/pewjlOfequOKYVC6h3v0YL/%5Bs2.0%5D-Desktop?type=design&node-id=6076%3A13023&mode=design&t=LpdUfFZ6Diaodpzd-1

1. **Clicking change to sat also redirects to account. Should only change to sats.**
2. Wrong header alignment
3. Wrong font colors (amount in fiat vs. amount in crypto)
4. Radial graph inconsistent rounding 
    - In the case above, BTC is fully filled and ETH also has a part of the graph filled
![image](https://github.com/trezor/trezor-suite/assets/152851523/c01b32fc-e113-40da-ab81-3f334ceedb21)

**Comment by AdamSchinzel** [comment]
5. No empty state
![9611427E-F9AD-4C00-9F64-8BC713765BB9_4_5005_c](https://github.com/trezor/trezor-suite/assets/66002635/e2bbf7ff-5373-47ca-9da0-d35829a2dec3)
6. Assets were not loaded properly not displayed in card section

**Comment by peter-sanderson** [comment]
@AdamSchinzel how can I reproduce empty state for Asset Row? I am able to get only error state when no joins are selected

**Comment by AdamSchinzel** [comment]
Try to create a wallet under some new passphrase, this should get you there

**Comment by peter-sanderson** [comment]
@AdamSchinzel   shows always something  (zero balances) -> 

![image](https://github.com/trezor/trezor-suite/assets/152899911/2080af1f-ac50-4a7d-a4f9-5bf042b58bb6)

**Comment by AdamSchinzel** [comment]
I probably was in some weird state that I can't reproduce now, never mind...
