### ISSUE TITLE
Empower/Left nav styling

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10851]
[[Figma component](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A31386&mode=design&t=dDDckCeQTSS0DgJh-1)](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A31386&mode=design&t=dDDckCeQTSS0DgJh-1)

Missaligned:

- Trezor photo with the container (horizontally & vertically)
- BTC icon
- Active coin logo within the green circle

Wrong fonts:

- Navigation rail item ([[Figma](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A31386&mode=design&t=dDDckCeQTSS0DgJh-1)](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A31386&mode=design&t=dDDckCeQTSS0DgJh-1)) + wrong inactive state

Wrong spacings:

- Trezor + connected
- Between search : coin logos : account list

![image](https://github.com/trezor/trezor-suite/assets/152851523/3c05cfa9-ea2a-455f-abe2-26a1f2ebfcae)

**Comment by peter-sanderson** [comment]
> Wrong fonts:

We agreed with Leo that smaller fonts are not looking that good as they are in Figma. Also we dont have proper typography (its not callout nor hint)

So I am leaving it as it is for now.
