### ISSUE TITLE
Empower/Device & Coins tabs disable active state on Settings (in left nav)

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10852]
Application tab keeps the left nav item active as expected.

![image](https://github.com/trezor/trezor-suite/assets/152851523/166c3b7f-ba5c-4864-9a3b-3a9366e0f093)
![image](https://github.com/trezor/trezor-suite/assets/152851523/c7c233d0-d370-49e0-bdb1-c85c14cd96fb)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (2acb84bb22f134bdaef4e2706a6e1041fe277ab1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
