### ISSUE TITLE
connect analytics modal - wrong default value

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#10854]
although analytics is turned off, and no event is reported indeed, analytics modal in popup shows "on"

<img width="886" alt="image" src="https://github.com/trezor/trezor-suite/assets/30367552/ac2eccaf-3a10-4b24-a816-715e9047d6b5">

found while working on #10770

**Comment by mroz22** [comment]
wasn't this already fixed by @karliatto ?

**Comment by karliatto** [comment]
> wasn't this already fixed by @karliatto ?

Yes, I think this was closed by https://github.com/trezor/trezor-suite/pull/11299

**Comment by bosomt** [comment]
**QA OK**

connect popup remembers `Allow anonymous data collection` settings in popup
