### ISSUE TITLE
refactor http-receiver 

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#10859]
suite-desktop-core - refactor http-receiver module to be more versatile.

**Comment by bosomt** [comment]
**QA OK** invity buy
**QA OK** invity spend
**QA OK** buy p2p

**Info:**
 - Suite version: desktop 24.2.0 (459374dc7a4603aa35844f9ee7ddce9316a3a79f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
