### ISSUE TITLE
Context

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1086]
Context: **Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5e284ca49d2d35550199a36b)

Stacking with App banner: **Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5e2fe9747eecc454cf972268)

**Comment by glacierbits** [comment]
Merged in #1142

**Comment by sorooris** [comment]
Test of the blockbook warning blocked by #913.
