### ISSUE TITLE
Send coins - send transaction

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10868]
## Description
After validating the send values by device, user should be able to create transaction and send it.

## Acceptance criteria
- [ ] after the device values verification, user is able to click `Send` button
- [ ] button click triggers on device send flow
- [ ] after successful device send flow, the user is in app notified that send was successful and redirected back to the account screen

**Comment by PeKne** [comment]
blocked by #12378

**Comment by PeKne** [comment]
Notes for QA:
described here: https://github.com/trezor/trezor-suite/issues/10867#issuecomment-2222148507

**Comment by STew790** [comment]
**QA OK**
I was able to send testnet coins from one account to another. More can be found here https://www.notion.so/satoshilabs/Send-function-in-Suite-Lite-c70512ea96e54e18b222c0fed4e0472d

**Info**
24.8.0  aceb3c7
