### ISSUE TITLE
 Send coins - address QR scanner

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10866]
## Description
It should be possible to fill in the address value by scanning a QR code by phone camera or by importing a photo from the gallery.  The functionality of XPUB scan screen will be enhanced and this same component will be reused for the send flow.

## Acceptance criteria
- [ ] No new component is created, the existing XPUB scanning component is reused and improved
- User can insert the recipient address
    - [ ] Via scanning the QR code
    - [ ] from photo library
    
## Resources
- Link to [DESIGN 1](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=2135-10290&t=KTigu9fek47mphXN-4)
- Link to [DESIGN 2](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=2135-11081&t=KTigu9fek47mphXN-4)

**Comment by STew790** [comment]
**QA OK**
- scanning via camera works same as before
- uploading tested both on Android and iOS
- on Android also tested with send form (both camera and upload)

**Info**

24.9.1 306d448
