### ISSUE TITLE
Send coins - inputs review screen

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10867]
## Description
After filling an input form, user should be able to validate these values on the device screen.

## Acceptance criteria
- [x] After submiting a valid send form user is redirected to another screen where he can review filled inputs
- [x] After user goes through the device process, the screen renders simple message saying that verification was successful

**Comment by PeKne** [comment]
blocked by #12378

**Comment by PeKne** [comment]
### notes for @trezor/qa : 
This PR was merged with https://github.com/trezor/trezor-suite/issues/10868 (send transaction).

Please test that you can review the `amount` and `address` input, confirm it on the device, and send the transaction. To do it you will need to enable the `send` feature flag using the `testnet` or `regtest` account.  Other networks are still disabled. Then you should see a `Send coins` button in the home screen as an entry point to the send flow.

**Comment by STew790** [comment]
**QA OK**
More can be found here https://www.notion.so/satoshilabs/Send-function-in-Suite-Lite-c70512ea96e54e18b222c0fed4e0472d

**Info:**

24.8.0  aceb3c7
