### ISSUE TITLE
Send coins - fiat amount input

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10872]
## Acceptance criteria
- [ ] User can insert amount in FIAT or BTC
- [ ] When user inserts amount in FIAT, it is reflected in BTC and vice versa
- [ ] When user inserts amount above his balance, he is informed
- [ ] When user inserts amount below dust, he is informed
- [ ] FIAT input respects the user settings, if user has default currency USD, he inserts amount in USD
- [ ] there is an transition animation for going between crypto and fiat input

## Resources
- Link to [DESIGN](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=1816-25102&t=KTigu9fek47mphXN-4).

**Comment by STew790** [comment]
**QA NOK**
I can select amount below dust limit and above my balance and I don't see any warning
**QA OK**
- i can input either BTC or FIAT
- fiat and BTC are both changing whenever I change the other one
- fiat input respects users fiat settings
- animation looks smooth and good (feelsgoodman.jpg)

**Info:**
24.8.2   e722418

**Comment by PeKne** [comment]
The discovered bug from QA NOK section will be revisited in the separate issue: https://github.com/trezor/trezor-suite/issues/14071.

Moving this issue to Approved ✅ status.
