### ISSUE TITLE
Empower/TX list item wrong padding

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10879]
# TX list item wrong padding

Too big of a padding on the bottom

![image](https://github.com/trezor/trezor-suite/assets/152851523/6f2adb5f-1a98-4583-ab73-7fd77337b8cb)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.6.5 regular (revision a784c4046e79ae138f9a7a9c5e97d2f6771140eb)
 - Transport: BridgeTransport 2.0.33
