### ISSUE TITLE
Add new coin 4 - polish empty account state

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#10870]
Polishing how the account detail looks for no transaction:
- [x] send to account detail before it is added - use skeleton for loading state
- [x] pop back and show error if adding account fails
- [x] use skeleton for loading of coin price
- [x] visual tweaks according to design
- [x] go directly to address verification when adding account via receive flow

https://www.figma.com/file/BVA3IAmqDjz36sBGVtEFbz/Add-new-coin-%2F-Account?type=design&node-id=280-18926&mode=design&t=bZP0odolbHL26WAW-0

**Comment by bosomt** [comment]
**QA OK**

Android 14 Nothing phone 1 
24.4.0 cd82750
