### ISSUE TITLE
Empower/Range input has extra gray container + old style of inputs

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10877]
![image](https://github.com/trezor/trezor-suite/assets/152851523/93cbe909-46d9-4614-bf53-27002c46ad88)

**Comment by STew790** [comment]
**QA OK**

![image](https://github.com/trezor/trezor-suite/assets/48477147/cca05e01-a834-4b90-bd62-6cfc348f9c8f)

**Info:**
 - Suite version: desktop 24.3.0 (094fbb029397557a6f4bcbb2390fcdc8de54f3d3)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
