### ISSUE TITLE
Send coins - fee rate input

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10871]
## Description
User should be able to specify the fee rate of the transaction. Under the amount input there will be rendered fee level options (low,normal,high).

For testnets there is always only normal level.

**Comment by STew790** [comment]
**QA OK**
Testnet have only one fee rate. Normal BTC you can choose from `low`, `medium` and `high`.
![image](https://github.com/user-attachments/assets/e8ef09c0-3d29-4b7a-88a5-595168a3f6b0)
![image](https://github.com/user-attachments/assets/346ffcc8-34e9-493b-984f-31476def7291)
(The fees were correct at the time of making the screenshot)

**Info**

24.8.1 https://github.com/trezor/trezor-suite/commit/f2f56aa44a2843d9cae13ff77d8439882f1e9875

**Comment by PeKne** [comment]
@STew790 Are you in Bangladesh right now? :D

**Comment by STew790** [comment]
I wish :joy:  but it's just a random different fiat that I usually select when doing tests (because I don't have to swipe and it's like a third or fourth fiat from the selection iirc :sweat_smile: )
