### ISSUE TITLE
Empower/Some texts are inbalanced

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10878]
Let’s add text-wrap: balance; ? (idk if it won’t fuck something up, e.g. addresses)

**Comment by MiroslavProchazka** [comment]
![image](https://github.com/trezor/trezor-suite/assets/152851523/23d8fc37-9e89-4a70-bcdf-a6133dc5fa7d)

**Comment by jvaclavik** [comment]
Let's wait with this issue after merge PR with header: https://github.com/trezor/trezor-suite/pull/11232

It can looks better there

**Comment by MiroslavProchazka** [comment]
@trezor/qa can you check this please?

**Comment by STew790** [comment]
The whole Staking page changed a bit so this is not really relevant. Closing.
![image](https://github.com/trezor/trezor-suite/assets/48477147/fc2c15f7-f62a-48e6-a668-7b43ca0f1fc0)
