### ISSUE TITLE
Empower/Padding between Portfolio value + TS3 promo

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10876]
Kinda just floats there, should be either:

- 16px between the graph (so it fits with the container paddings)
- or same as between sections (Portfolio : Assets : Security)
- 
![image](https://github.com/trezor/trezor-suite/assets/152851523/68a1beb6-5c22-4222-9da1-c496f03a3773)

**Comment by AdamSchinzel** [comment]
Already done - https://github.com/trezor/trezor-suite/issues/10895
