### ISSUE TITLE
Make cards the default portfolio display option

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#10882]
![image](https://github.com/trezor/trezor-suite/assets/45338719/37731df3-e2fa-455f-9b60-b6fab8846d3a)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (2acb84bb22f134bdaef4e2706a6e1041fe277ab1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
