### ISSUE TITLE
Margin in the Select Wallet modal is too large

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#10883]
![image](https://github.com/trezor/trezor-suite/assets/45338719/d38a2c32-2e98-4b0f-9eae-79099543d654)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (2acb84bb22f134bdaef4e2706a6e1041fe277ab1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
