### ISSUE TITLE
Padding between Portfolio value + TS3 promo

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#10895]
Kinda just floats there, should be either:

- 16px between the graph (so it fits with the container paddings)
- or same as between sections (Portfolio : Assets : Security)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (d2613d7feb8922adaa8dabf60a2d393147a1e8ec)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
