### ISSUE TITLE
Settings - disconnected trezor banner is missing some space around

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#10897]
At least one wallet needs to be remembered to achieve this state
![Jan 29 Screenshot from Notion](https://github.com/trezor/trezor-suite/assets/66002635/eebd6526-6009-4e4d-ae2c-04de9ed71bdf)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (2acb84bb22f134bdaef4e2706a6e1041fe277ab1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
