### ISSUE TITLE
Empower minor issues p 2

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10905]
**Describe the bug**
6.`Close` button not properly aligned in `Update firmware complete` modal
7. Send and receive buttons are active even account not properly loaded, buttons disappear after you click them 
8. Account name is rendered as context help sometimes /probably due that it didnt fit to left panel before when ARS fiat value enabled/

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
6.
![image](https://github.com/trezor/trezor-suite/assets/31506317/7f9da84b-de70-4b8e-a6b1-8b91c7d3d116)

7.
<img width="959" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/6747618c-6a38-4c2a-a180-6a85e142b89b">

8.

https://github.com/trezor/trezor-suite/assets/31506317/2e73b3aa-a64a-4f13-87a3-94ff7884b0a8

https://github.com/trezor/trezor-suite/assets/31506317/0327cf57-0717-4784-aa01-7eec5c737e0c

**Comment by peter-sanderson** [comment]
+ `6. & 7.` done in https://github.com/trezor/trezor-suite/pull/11112
+ `8.` will be done by @jvaclavik in separate pr

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.1 (d1eda6c68c4619a7060f1fcc8033ee44c4a94a03)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.2.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
