### ISSUE TITLE
Add Solana total tx box to account

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#10911]
We do not show graph as we do not have data but we can show at least total number of transactions

![Screenshot 2024-01-30 at 13 53 50](https://github.com/trezor/trezor-suite/assets/33235762/89cc37af-590e-41f1-b9ac-d91591abdef3)

![Screenshot 2024-01-30 at 13 48 46](https://github.com/trezor/trezor-suite/assets/33235762/ac2cf30d-85ad-46dc-8b56-b8f11f21a3b3)
![Screenshot 2024-01-30 at 13 52 13](https://github.com/trezor/trezor-suite/assets/33235762/e0e8571c-6f3a-403c-a72f-2bd3779f72e0)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 25.1.0 (20a35a51ea92edb7ffa42c696f6da297c66d2971)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
