### ISSUE TITLE
Update github actions to use Node 20

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#10919]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

see the warning: https://github.com/trezor/trezor-suite/actions/runs/7709977798

**Comment by hrudolf** [comment]
This commit 2 weeks ago addressed the issue:
https://github.com/trezor/trezor-suite/commit/1abb8302897ddb3d2c295870153b3623abe288eb

**Comment by matejkriz** [comment]
@hrudolf Thank you for noticing! 👍

**Comment by matejkriz** [comment]
Resolved in https://github.com/trezor/trezor-suite/pull/11237
