### ISSUE TITLE
"Receiving" SOL when receiving token

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#10915]
**Describe the bug**
It looks like that I got some Solana together with a token but it is not true

**Info:**

-   Suite Version: 24.2.0

**How to reproduce**

1. Send solana tokens

**Expected behavior**
It should not be visible

**Screenshots**

![Screenshot 2024-01-30 at 14 32 16](https://github.com/trezor/trezor-suite/assets/33235762/49a6e5f3-f0f6-4471-8174-10f8a4de849b)
![Screenshot 2024-01-30 at 14 32 30](https://github.com/trezor/trezor-suite/assets/33235762/ef071301-b54f-4e02-b6e4-30401f079037)
![Screenshot 2024-01-30 at 14 32 44](https://github.com/trezor/trezor-suite/assets/33235762/3dbdea51-5136-4ba3-bd17-55eef655e974)

**Comment by martykan** [comment]
Technically there is a small amount of SOL in the associated token account which is used to pay for the onchain storage
It's possible to burn the token and retrieve it, there are tools like https://sol-incinerator.com/

**Comment by STew790** [comment]
This issue will be fixed by https://github.com/trezor/trezor-suite/pull/12996

**Comment by bosomt** [comment]
What about sent ?
Isn't this similar issue ?
It always looks like i sent some SOL but i did nat

<img width="747" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/ac8121b8-9d03-4239-bb60-b135352cc22c">
<img width="742" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/3710c22c-4944-4e0b-9d1e-64a356044a17">

**Info:**
 - Suite version: web 24.7.0 (d1aa1b9444db33de097ac4bd1fb19ae3f4f61a43)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
**QA OK**

already deployed on production

**Info:**
 - Suite version: desktop 24.6.2 (b319fb1a1e4e2fb85e398589dec064c26450bab0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
