### ISSUE TITLE
Long time to see Solana tx so that the button in notification is useless

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#10916]
**Describe the bug**
Sent tx notification has button which does not take me to specific tx

**Info:**

-   Suite Version: 24.2.0
- 
**How to reproduce**

1. Sent tx

**Expected behavior**
See pending transaction to which `View details` takes me

**Screenshots**
![Screenshot 2024-01-30 at 14 41 17](https://github.com/trezor/trezor-suite/assets/33235762/1f10c173-fd81-4edd-9f37-6e1b1a343108)

**Comment by sime** [comment]
Related or fixed via https://github.com/trezor/trezor-suite/pull/11033 ?

**Comment by vytick** [comment]
Was this resolved or is still relevant @tomasklim ?

**Comment by tomasklim** [comment]
@bosomt please test

**Comment by bosomt** [comment]
**QA OK**

- i was not able to replicate it, guess scammy transactions are not active now so you can navigate your transaction as it stays on 1 page of transaction history

<img width="899" alt="Screenshot 2024-10-22 at 10 19 10" src="https://github.com/user-attachments/assets/6da86116-60ea-4d9c-a129-63926f1d6545">
<img width="894" alt="Screenshot 2024-10-22 at 10 18 58" src="https://github.com/user-attachments/assets/a4805745-2e56-40cc-8819-2d3a5cf15115">



**Info:**
 - Suite version: desktop 24.11.0 (17bac171ecd870c4d76bb64c6ec5f8d69b333d4c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Transport: BridgeTransport 3.0.0-bundled.24.11.0
