### ISSUE TITLE
Tx sent to myself shows that I got fee back in tx modal detail

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#10920]
**Describe the bug**
Tx sent to myself shows that I got fee back in tx modal detail

**Info:**

-   Suite Version: 24.2.0

**How to reproduce**

1. Sent token tx to yourself

**Expected behavior**
I says the truth!

**Screenshots**
![Screenshot 2024-01-30 at 14 54 20](https://github.com/trezor/trezor-suite/assets/33235762/55c0f5f4-d9c0-4c1d-b22d-f389a65cd70a)
![Screenshot 2024-01-30 at 14 54 26](https://github.com/trezor/trezor-suite/assets/33235762/b5fc184c-98cc-4f00-bbad-b9b6d7915e34)
![Screenshot 2024-01-30 at 14 54 49](https://github.com/trezor/trezor-suite/assets/33235762/061f0324-8c11-42c7-872c-525b7d6012ae)

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/17568337-66d5-46c2-afeb-deaf6d454b07)
![Image](https://github.com/user-attachments/assets/b2250685-fce4-45cb-b290-daf262510611)

**Info:**
 - Suite version: desktop 24.11.0 (17bac171ecd870c4d76bb64c6ec5f8d69b333d4c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
