### ISSUE TITLE
Empower/Options of dropdown element position glitch when parent(s) component/or something change

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10929]
in this view it happens after `@common/wallet-core/blockchain/updateFee` action

![image](https://github.com/trezor/trezor-suite/assets/152851523/c8202ef2-32ab-4b72-a5f5-0b554d6e4021)

![image](https://github.com/trezor/trezor-suite/assets/152851523/c7eea291-e742-4423-a67c-5f6e2e35b6f4)

**Comment by FreeWall** [comment]
relates / duplicates #10942

**Comment by dahaca** [comment]
duplicate of https://github.com/trezor/trezor-suite/issues/10720
