### ISSUE TITLE
Empower/Invity/Trade section 

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10924]
Trade section Typography hierarchy seems off (account name vs. amount vs. Trade heading) + on second 👁️ Buy in active state has almost invisible buttonish shadow

![image](https://github.com/trezor/trezor-suite/assets/152851523/284c3f18-d8f1-44ed-bd46-9976d7c26802)

**Comment by peter-sanderson** [comment]
I have fixed the isActive background color here https://github.com/trezor/trezor-suite/pull/10939

I don't know what this is about

> Trade section Typography hierarchy seems off (account name vs. amount vs. Trade heading) 

I assume it is about headers? Those are still not implemented yet right @dahaca ?

**Comment by dahaca** [comment]
> I assume it is about headers? Those are still not implemented yet right @dahaca ?

Correct! 🙏
