### ISSUE TITLE
Empower/Outer circle of coins in filter is misaligned

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10927]
Specifically on Linux the circles around coins are misaligned. 

![image](https://github.com/trezor/trezor-suite/assets/152851523/15f55a1e-54fe-4435-a0d4-b2ff841f1817)
![image](https://github.com/trezor/trezor-suite/assets/152851523/b940ff73-3249-4fdd-bd20-06dd8d527036)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (2acb84bb22f134bdaef4e2706a6e1041fe277ab1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by jvaclavik** [comment]
IMHO it's not fixed yet. It has different border width on bottom right side. WDYT @peter-sanderson ?

<img width="223" alt="image" src="https://github.com/trezor/trezor-suite/assets/858321/9eda28b1-6fc7-47ea-b332-d9ef58426953">
