### ISSUE TITLE
Empower/Invity/Comparator - info-notes are off

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10925]
![image](https://github.com/trezor/trezor-suite/assets/152851523/3c6a6d42-59e9-46de-91e0-3db37211d64d)

**Comment by peter-sanderson** [comment]
What are info notes? It would be really good to have some drawings in the picture so its clear.

**Comment by MiroslavProchazka** [comment]
Hey @peter-sanderson , I'm trying to gather more info. For now please delete this text as it seems it should be not part of the production version. Thanks!
![image](https://github.com/trezor/trezor-suite/assets/152851523/6e5956aa-1fab-4307-affb-3b605d724d6c)

**Comment by MiroslavProchazka** [comment]
The wrong text "Long message used to test the feature" is not fetching from a codebase, but from somewhere in Invity source. Can you please investigate? 

cc @IvaFingerova @FreeWall

**Comment by MiroslavProchazka** [comment]
Info notes are the yellow Tags "Test tag" - we need to adjust the padding around and center them to proper position. The text to which the arrow is directing is correct,  no need to fix it.

**Comment by LukasRada** [comment]
@MiroslavProchazka Should we check and eventually use Badge component from Storybook?

**Comment by MiroslavProchazka** [comment]
cc @jvaclavik , can you help Luky please? :)

**Comment by zuzjes** [comment]
@jvaclavik I am working on this task, would you alight the badge to center, or remove the padding from left ?

**Comment by zuzjes** [comment]
@MiroslavProchazka please some advice, help?

**Comment by MiroslavProchazka** [comment]
Sorry, I missed this one. I would rather ask @marek-andrsk what should be the desired outcome as this issue was originally created by @IvaFingerova. So I would leave this completely in your hands :)

**Comment by marek-andrsk** [comment]
@zuzjes align to the left please, i.e. remove the padding as you suggest :)

**Comment by MiroslavProchazka** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/11357

**Comment by STew790** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
