### ISSUE TITLE
Empower/Bad gradient color for overlayed receive address in dark theme

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10928]
![image](https://github.com/trezor/trezor-suite/assets/152851523/6af3fa9b-8abd-4e0a-bb38-dc99c38da6c4)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.2.0 (02d6217963c3f8d49694fe1b6d90610aca848a55)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
