### ISSUE TITLE
Fix gradient overlay glitches

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#10922]
<img width="1004" alt="Screenshot 2024-01-30 at 15 15 41" src="https://github.com/trezor/trezor-suite/assets/858321/e07f637f-d8bd-4e31-8ff9-3e5c9ab8a863">

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.2.0 (02d6217963c3f8d49694fe1b6d90610aca848a55)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
