### ISSUE TITLE
Empower/Coinjoin loading account toggle missaligned

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10937]
Plese align it to the right side of the screen
![image](https://github.com/trezor/trezor-suite/assets/152851523/c05cb0db-26b1-47ae-993b-cd154b235c95)

Like this 
![image](https://github.com/trezor/trezor-suite/assets/152851523/35d19166-536d-4e31-a72b-5973abfd9b60)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.3.0 (b05fc18e49fdf062f2c8db4e7f34dbd81dcd91e2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
