### ISSUE TITLE
Empower/Invity/ Trade - buy - pending TX - CTA Zobrazit podrobnosti doesn’t fit

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10934]
![image](https://github.com/trezor/trezor-suite/assets/152851523/a9f95bc9-e994-4f1f-bd70-a56163fcb7ef)

**Comment by dahaca** [comment]
I also believe the vertical separator should be simply removed

**Comment by zuzjes** [comment]
What should be the solution to this bug? Make wider column for the button or what any other suggestion?

**Comment by MiroslavProchazka** [comment]
cc @jvaclavik , can you advise please? :)

**Comment by jvaclavik** [comment]
@zuzjes Important part is to make container with "Zobrazit více" wider (ideally dynamic, not just static width).

Also I suggest to use `Button` component (from `@trezor/components`) with `variant="tertiary"` for "Zobrazit více". It will be more evident that it's clickable element.

**Comment by zuzjes** [comment]
@jvaclavik the button already has `variant="tertiary"` prop

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.3.0 (b05fc18e49fdf062f2c8db4e7f34dbd81dcd91e2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
