### ISSUE TITLE
Empower/Spacing of coinjoin state and time seems a bit off

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10938]
![image](https://github.com/trezor/trezor-suite/assets/152851523/b6f80760-2b44-4f49-b827-c58b7d6277bf)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.0 (42c94a1fda8c6fde6cdadc8696de4f83f8ae9f37)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
