### ISSUE TITLE
Empower/Add new account has weirdly aligned text

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10932]
![image](https://github.com/trezor/trezor-suite/assets/152851523/db0aa354-d2f7-47dd-8ea9-c9df3d001d48)

**Comment by jvaclavik** [comment]
@MiroslavProchazka Let's move this issue to another milestone. It's very minor.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.3.0 (2221ceddf6b6281ce753b4f226945fc121ebbaee)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
