### ISSUE TITLE
Empower/Settings - disconnected trezor banner is missing some space around

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10931]
![image](https://github.com/trezor/trezor-suite/assets/152851523/965d403d-b23e-4d15-822c-ccdfd18f2057)

**Comment by AdamSchinzel** [comment]
Already fixed - https://github.com/trezor/trezor-suite/issues/10897

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (2acb84bb22f134bdaef4e2706a6e1041fe277ab1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
