### ISSUE TITLE
Empower/Invity/ Trade - buy - pending TX 

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10935]
Trade - buy - pending TX - clicked CTA Zobrazit…Paragraph “pro dokončení” is too narrow, Trans ID bellow the right summary block is misaligned 

![image](https://github.com/trezor/trezor-suite/assets/152851523/6bd57b02-ae0d-49b8-b8b2-125c0f6a7a8f)

**Comment by MiroslavProchazka** [comment]
<img width="1415" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/1f9ed555-c87e-4d96-9061-60c1cd9b0a98">

**Comment by zuzjes** [comment]
![Screenshot 2024-02-27 at 11 46 23](https://github.com/trezor/trezor-suite/assets/41970479/8cdb4193-7a89-4442-adc5-97d172a9a612)
Solved this way.

**Comment by MiroslavProchazka** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/11357

**Comment by STew790** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
