### ISSUE TITLE
Empower/Coinjoin modal not aligned

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10933]
![image](https://github.com/trezor/trezor-suite/assets/152851523/9347a9ed-d11b-40fd-ad7d-46f83c758be0)

**Comment by jvaclavik** [comment]
@MiroslavProchazka Could you be more specific what's the issue here?

**Comment by MiroslavProchazka** [comment]
Sure! The status copy and time info should be centered 
![image](https://github.com/trezor/trezor-suite/assets/152851523/537333c8-5946-42bf-980e-8ec4b3d67842)
cc @jvaclavik

**Comment by bosomt** [comment]
**QA OK**

<img width="405" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/0cbddff0-e88a-4595-ba92-bfdba678df20">

**Info:**
 - Suite version: desktop 24.2.0 (42c94a1fda8c6fde6cdadc8696de4f83f8ae9f37)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
