### ISSUE TITLE
Empower/Invity/ Payment method 

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10948]
Comparator - sell - payment method label in CZ lang is in azbuka 😀

<img width="1190" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/3b11d8f5-aa47-44f2-8ebc-6e8d59d0cc36">

**Comment by dahaca** [comment]
It's a crowdin issue @b-irving 

<img width="473" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/e269acb1-ee94-4037-b12b-0dc6af4ed445">

**Comment by b-irving** [comment]
Following up with Chris and Kuba.

**Comment by Hermez-cz** [comment]
Fixed in Crowdin, will be visible after translation files deploy.
