### ISSUE TITLE
Empower/Invity/ DEX flow

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10942]
DEX flow (ETH→SOL exchange) - choose Decentralised exchange offer step 1 - Přijímací account dropdown makes swaps with some other account select (see recording)

![image](https://github.com/trezor/trezor-suite/assets/152851523/6d1882fe-ff5e-4a26-92d4-46e07726686c)
![image](https://github.com/trezor/trezor-suite/assets/152851523/873958d5-974a-42f9-a223-e9fd74b74b70)

https://github.com/trezor/trezor-suite/assets/152851523/20fca59e-1f21-4d06-a996-81297d590a22

**Comment by dahaca** [comment]
duplicate of https://github.com/trezor/trezor-suite/issues/10720
