### ISSUE TITLE
Empower/Invity/ BTC DCA Tooltip

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10949]
Tooltip with link to Suite guide - link has smaller font size

<img width="1195" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/0bf7cd7f-73a9-4f93-aead-97c34fe49798">

**Comment by zuzjes** [comment]
![Screenshot 2024-02-26 at 18 46 42](https://github.com/trezor/trezor-suite/assets/41970479/43aaf0b3-33e6-487b-8e80-b4cb6bebb211)
This looks already resolved? @LukasRada

**Comment by LukasRada** [comment]
Perfect. Please then feel free to close this issue if you confirm @MiroslavProchazka

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.6.5 regular (revision a784c4046e79ae138f9a7a9c5e97d2f6771140eb)
 - Transport: BridgeTransport 2.0.33
