### ISSUE TITLE
Empower/Invity/ BTC DCA - USA location

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10947]
BTC DCA - 1st step - location dropdown breaks for the USA

![image](https://github.com/trezor/trezor-suite/assets/152851523/edae0048-09ff-4d24-a199-fdf5c3c02bb0)

**Comment by zuzjes** [comment]
![Screenshot 2024-02-26 at 19 15 34](https://github.com/trezor/trezor-suite/assets/41970479/292c91fe-c781-4926-b2ee-b4c8ca8d2a22)
Fixed by adding minimum right padding of 20px to the LabelText. @LukasRada

**Comment by MiroslavProchazka** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/11357

**Comment by STew790** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
