### ISSUE TITLE
Empower/Invity/ 1inch label

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10944]
DEX Flow (ETH-USDC ERC20) - step 2 P3 label “smlouva 1inch” should start with UpperCase

<img width="1300" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/28c09310-b79f-46e8-9f00-4f8ad0b9d901">

**Comment by dahaca** [comment]
@b-irving letting you know 🙌

**Comment by b-irving** [comment]
On it

**Comment by b-irving** [comment]
@dahaca string has been updated via CrowdIn

**Comment by martinboehm** [comment]
Is it in Czech translated as "smlouva"?? The meaning of this field is "1inch contract address".

**Comment by b-irving** [comment]
@martinboehm OK, following this up

**Comment by b-irving** [comment]
@martinboehm @dahaca we have updated both English and Czech strings to: `{provider} contract address` and `Adresa kontraktu {provider}` respectively.

**Comment by MiroslavProchazka** [comment]
Should be solved with next crowdin sync
