### ISSUE TITLE
Empower/Invity/ Comparator buttons alignment

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10943]
Comparator - exchange - P1 ETH logo ind ETH amount no padding, P1 Cta is misaligned, P2 KYC messages donnt fit in, P3 validation of min-max amount “x” sign is misaligned

![image](https://github.com/trezor/trezor-suite/assets/152851523/234bc448-a4b7-4e4b-a228-44c7bbe62f8d)

**Comment by MiroslavProchazka** [comment]
We will fix just the button for now

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (f2463690bb56fb775fd9df588572f3c40ac7c00c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
