### ISSUE TITLE
Empower/Invity/ Location selectbox

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10946]
Trade - buy - location selectbox - after click it gets weird border + might have better padding

![image](https://github.com/trezor/trezor-suite/assets/152851523/a71be209-4f2a-4531-aefb-6a54dc6338d0)

**Comment by dahaca** [comment]
The border should be there but the padding should be fixed. These `Selects` are currently not a part of the design system btw, so they might have to be changed in the future.

**Comment by komret** [comment]
See the arrow overlapping the text:
![Screenshot 2024-02-09 at 17 29 36](https://github.com/trezor/trezor-suite/assets/42465546/00adf67a-4f7e-45f5-8cb9-36a1f9e17e9e)

**Comment by MiroslavProchazka** [comment]
It would make sense to create a separate component for this scenario. fyi @jvaclavik

**Comment by MiroslavProchazka** [comment]
Fixed in 24.8.1
<img width="1236" alt="image" src="https://github.com/user-attachments/assets/e1a66035-39d5-4691-acf9-6d642819c56f">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.8.2 (96e583538c6a30e010a81346d1251f3246cb1def)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.32
