### ISSUE TITLE
Empower/Invity/ input form misaligned

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10945]
DEX Flow (ETH-USDC ERC20) - step3 - Vlastní odchylka input is misaligned

<img width="659" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/659aba5c-798e-4722-b930-c76270d541fb">

**Comment by zuzjes** [comment]
![Screenshot 2024-03-07 at 18 31 52](https://github.com/trezor/trezor-suite/assets/41970479/4ad36865-4291-4999-93e8-e8a5a3c482fe)
Any advice with how this should behave? I got rid of the bottom padding - the padding is there for making space for the validation message. @MiroslavProchazka

**Comment by zuzjes** [comment]
![Screenshot 2024-03-07 at 18 33 14](https://github.com/trezor/trezor-suite/assets/41970479/5eaed4f4-3099-46e1-984e-88568e1e662a)
This is how it look without the validation error message..

**Comment by MiroslavProchazka** [comment]
Hmm, this one is tricky. @marek-andrsk do you have some thoughts on this? Personally I would just place the error message directly below the cell (with custom number) and center it, but as in the previous issue, I would rather leave this design decision up to you (and Marek).

**Comment by zuzjes** [comment]
Or the input could show under the select of values, so it don't size down when I click on custom, it's a bit weird as well. So we would not have to think about what to do with the validation. @MiroslavProchazka

**Comment by MiroslavProchazka** [comment]
Yep, could be as well. Still I would rather wait for confirmation from @marek-andrsk.

**Comment by marek-andrsk** [comment]
@zuzjes can you please move the error message directly bellow the fee picker element and align to the left so that there's enough space for longer text

**Comment by zuzjes** [comment]
So input for custom fee will stay where it is and somehow move just the error message bellow the whole element, will try my best @marek-andrsk

**Comment by zuzjes** [comment]
@marek-andrsk is this OK by you?

![Screenshot 2024-03-19 at 11 38 57](https://github.com/trezor/trezor-suite/assets/41970479/92cad6cc-b216-4f03-a893-65be515d4dbe)

**Comment by marek-andrsk** [comment]
@zuzjes that's great, thank you

**Comment by MiroslavProchazka** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/11357

**Comment by bosomt** [comment]
**QA OK**

please consider follow up issue for entering hex number ;)  @zuzjes 


**QA NOK**


![Image](https://github.com/trezor/trezor-suite/assets/31506317/56b309d9-ced2-498d-9d73-47bda4109008)


**QA OK**

![Image](https://github.com/trezor/trezor-suite/assets/31506317/c6863b8e-c0ff-4b6a-81d3-d9013303ba1a)
![Image](https://github.com/trezor/trezor-suite/assets/31506317/a3bc77d9-2c7c-4693-b557-4d79a1bcfc8c)


**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by MiroslavProchazka** [comment]
cc @FreeWall & @marek-andrsk.
<img width="887" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/0ec077c3-f7b5-40fc-967e-853e608ac1ce">
