### ISSUE TITLE
Different color of buttons when signing not broadcasted transaction.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10959]
**Describe the bug**
Different color of buttons when signing not broadcasted transaction.

**Steps to reproduce:**
1. Navigate to Send dialogue
2. Turn broadcast off and sign transaction
3. Observe two available buttons

**Info:**
 - Suite version: web 24.2.0 (2acb84bb22f134bdaef4e2706a6e1041fe277ab1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="535" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/328eff5e-ba62-46db-9ce5-f6e248954a45">

**Comment by MiroslavProchazka** [comment]
cc @jvaclavik please check this

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (f2463690bb56fb775fd9df588572f3c40ac7c00c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
