### ISSUE TITLE
Empower/Invity/ Trade section alignment

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10951]
Trade section - Invity footer - Zjisti Více on click a popup appers - Invity logo is misaligned. Link to [invity.io](http://invity.io/) is a button - might be just a hyperlink - it looks weird right next to the “x” closing the popup. Right margin is too small
![image](https://github.com/trezor/trezor-suite/assets/152851523/06dd0d65-8325-418e-b312-27caaf3e8e84)

**Comment by MiroslavProchazka** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/11357

**Comment by STew790** [comment]
**QA OK**
LGTM
![image](https://github.com/trezor/trezor-suite/assets/48477147/82b656f9-a129-481d-bbd5-9136ce6f1d1e)

**Info:**
 - Suite version: desktop 24.5.0 (a54e74f6dc7655fd94fc10203562226e0dc5527d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.5.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
