### ISSUE TITLE
Empower/Fake tx warning - text spacing

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10956]
<img width="777" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/86a247ec-3897-40d9-9950-795b2c6fc7c3">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.3.0 (b05fc18e49fdf062f2c8db4e7f34dbd81dcd91e2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
