### ISSUE TITLE
Empower/Invity/ Trade-exchange coin amount input 

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10957]
Trade-exchange coin amount input - amount doesn’t fit
![image](https://github.com/trezor/trezor-suite/assets/152851523/790c9d25-eca1-40d1-8244-745a1711da22)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.3.0 (0498c2ef4c0a61ff56fc60cff0f545636592814d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
