### ISSUE TITLE
Empower/ Visibility of trade button

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10955]
Hardly visible Trade button atop account + Buy-sell-exchange in trade box (normal+dark mode) - they don’t even look on the same level (secondary button)

![image](https://github.com/trezor/trezor-suite/assets/152851523/5f16eef4-b1eb-4cf6-ad56-78216515263e)
![image](https://github.com/trezor/trezor-suite/assets/152851523/95242f12-a7d3-47d6-a95e-504105851d3b)

**Comment by MiroslavProchazka** [comment]
@dahaca will you take this please?

**Comment by marekrjpolak** [comment]
> they don’t even look on the same level

As God intended.

**Comment by dahaca** [comment]
Duplicate of https://github.com/trezor/trezor-suite/issues/10689 and is related to https://github.com/trezor/trezor-suite/issues/9881

@Hermez-cz leaving it for product to make color-related decisions.

**Comment by MiroslavProchazka** [comment]
Closing for now, this needs to be discussed internally at first.
