### ISSUE TITLE
Empower/ Buy button is not visible

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10960]
Assets - grid view - buy button invisible

![image](https://github.com/trezor/trezor-suite/assets/152851523/12756d6e-b5b7-41ab-ba1d-215d41b117b9)

**Comment by IvaFingerova** [comment]
I'm afraid, we'll need designer's touch on this @Hermez-cz what do you reckon?

**Comment by dahaca** [comment]
@IvaFingerova @Hermez-cz  it's a known issue, Petr and Honza had another sync with David regarding elevation colors today, all good :)
