### ISSUE TITLE
Polygon: Empty account explanation banner should use the "Taproot" component

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#10964]
On a fresh new (empty) Polygon account, we are showing an informational banner telling:

> Polygon is its own blockchain
> It shares the same address style as Ethereum but has its own unique coins and tokens that can't be used on other networks.

![Image](https://github.com/trezor/trezor-suite/assets/88533514/a12763ae-3d66-497f-acfb-0ecbf948011c)

Such banner should use a component we have ready for this situation. It can be seen on any Taproot account. Please use that component, only adapt it to the given content mentioned above.
Also please, for Polygon, change the color from green to violet and the checkmarks to "i" icon.
We will also have to reduce the header font size, that thing is huge.

![Image](https://github.com/trezor/trezor-suite/assets/88533514/8b8ade16-d2c5-443a-bb41-f27df1ecd00b)

Together with this, please update also the banner's behavior. It shouldn't be shown on an empty account only as there might be already some spam/scam transactions waiting for the users to open the respective accounts. It should instead appear on all newly added Polygon accounts and it should disappear once the user clicks the [Got it!] button and never come back again.

**Comment by bosomt** [comment]
**QA OK**

created follow up issue /not sure if it was broken by this change or not https://github.com/trezor/trezor-suite/issues/11478

**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33
