### ISSUE TITLE
Polygon: The Send/Receive info modals should appear only on an empty Ethereum account

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#10967]
Together with Polygon, we will introduce the network explanation modals also to Ethereum. They will show up first time the user will try to Send/Receive on an Ethereum account after the Suite installation/update in the respective version. That will be valuable for fresh users*, but it might annoy experienced Ethereum users and prolong their essential user journeys.

We should only show that on fresh new empty Ethereum accounts with no Tx history. If this condition won't be feasible in time for the release, we have to remove these modals from Ethereum completely!

<img src="https://github.com/trezor/trezor-suite/assets/88533514/f93a4382-21a7-43d5-8b15-ae368797a344" width="264" height="264">
<img src="https://github.com/trezor/trezor-suite/assets/88533514/8d09c4e1-4f8b-4db3-949a-51d86f3fee63" width="264" height="264">

*(to avoid cross-sending between networks which happens as we know from Support)

**Comment by FreeWall** [comment]
fixed in https://github.com/trezor/trezor-suite/pull/10506/commits/50b023645b197b1f383c449069b77899a69c0a32

**Comment by tomasklim** [comment]
@FreeWall next time add `Resolves #10967` to your PR, not here

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (f2463690bb56fb775fd9df588572f3c40ac7c00c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
