### ISSUE TITLE
Problem with visibility labels with coin control

### ISSUE THREAD

**Issue by PeterHortvat1986** [trezor/trezor-suite#10968]
**Describe the bug**
I have got added labels on bitcoin addresses in the past, which source is dropbox. But in accounts i can see 2 types of labels. One is with small icon and another without this small icon. When i want send transaction and choose coincontrol, there are visible only labels with that small icons and another are missing. On that address which is not vissible (is missing) label i can add "add label" (with that small icon) again. But why are there 2 types of labels and arent visible in coin control?

**Info:**

-   Remembered Wallet: yes
-   Suite Version: app 24.1.2
-   Browser: -
-   OS: Windows 10 PRO 22H2
-   Bridge: -
-   Firmware Version: Model T, firmware 2.6.4, bootloader 2.1.4

**How to reproduce**

1. Go to 'Dashboard'
2. Click on 'Bitcoin'
3. Click on 'Send'
4. Click on 'Coin control'
5. See error

**Expected behavior**
I can see all labels in coin control mod.

**Screenshots**
How it is vissible in accounts:
https://ibb.co/CQbrLGZ

How it is vissible after click on send button and choose coin control:
https://ibb.co/fHMk9LK

**Comment by MiroslavProchazka** [comment]
Hello @PeterHortvat1986, thank you for reaching out to us. The entire labeling system is currently undergoing reconstruction. We are planning structured changes in the upcoming months that will address this issue as well. I'm closing this issue as "not planned" since similar goals are currently on our roadmap.
