### ISSUE TITLE
Add checksum to taproot descriptor

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#10963]
https://github.com/trezor/trezor-firmware/pull/3505#issuecomment-1918256659

We should add it to both, Suite and Suite mobile. @Hermez-cz @sime

**Comment by Hannsek** [comment]
Please mind that for TS3 the number of screens changes to 3 (from 2). https://github.com/trezor/trezor-firmware/pull/3505#issuecomment-1929120642
So the design/logic has to be tweaked for TS3.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by STew790** [comment]
**QA NOK**
Same issue as here https://github.com/trezor/trezor-suite/pull/11314#pullrequestreview-1911221821 with T2T1

T2B1 is QA OK.

**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
