### ISSUE TITLE
Buttons with different colors in Coinmarket p2p section

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10978]
**Describe the bug**
Buttons with different colors in Coinmarket p2p section

**Steps to reproduce:**
1. Navigate to `web/accounts/coinmarket/p2p#/` via buy options
2. Select `Go to Hod Hodl`
3. Return to Trezor Suite
4. Observe two buttons 

**Info:**
 - Suite version: web 24.2.0 (3ba71cbdf7a956185ce627ecd7aa0364ad35fc0b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="1032" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/d27df0ab-0863-4cbd-8317-4dda1edb0d0e">

**Comment by dahaca** [comment]
We do not know that priorities should be here. I believe Invity should assign appropriate button varians themselves :) @IvaFingerova

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (f2463690bb56fb775fd9df588572f3c40ac7c00c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
