### ISSUE TITLE
Message system state is not presistent

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#10979]
**Describe the bug**
If is a closable message banner closed, it should never appear again.
**How to reproduce**

1. Close a banner message
1. Kill the app
1. Open the app again
1. See the banner message again

**Expected behavior**
Whole message system redux state is persisted.
**Screenshots**

https://github.com/trezor/trezor-suite/assets/26143964/cdd19612-e2de-4a2c-918b-55115a29ec12

**Comment by matejkriz** [comment]
@PeKne Not only hidden messages should be persistent, but the entire downloaded config should be preserved.

**Comment by bosomt** [comment]
**QA OK**

will be tested with next system message and it there will be any problem we will create issue
