### ISSUE TITLE
Empower/Blockbook icon is not aligned

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10981]
Please align the icon towards the button/text - should be centered. 

<img width="1242" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/147bb1c3-1853-41bf-b7f3-43d78081041f">

**Comment by peter-sanderson** [comment]
It seems to me, that this was already fixed

![image](https://github.com/trezor/trezor-suite/assets/152899911/7312d408-ac66-4b7c-b123-86de9ef6f033)
