### ISSUE TITLE
Empower/Invity/ long token names brake component

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10983]
Trade-exchange coin to dropdown long names brake and might have smaller line height

![image](https://github.com/trezor/trezor-suite/assets/152851523/023730dd-bba0-48fc-8416-a890b8790aa2)

**Comment by MiroslavProchazka** [comment]
@dahaca  or @jvaclavik , can you please propose solution for this?

**Comment by dahaca** [comment]
Not an issue, closing. Looks even clearer with ERC20 on the next line.
