### ISSUE TITLE
Empower/Trade-exchange coin/Fiat input validation

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10985]
@Hermez-cz we need InputGroup component for these purposes. 

![image](https://github.com/trezor/trezor-suite/assets/152851523/a40759b7-1083-4998-b77a-4f24a66680fc)

**Comment by MiroslavProchazka** [comment]
@peter-sanderson  Can you please take this one? 

1. Add padding bottom to error text "Not enough funds"
2. Add  red right border to the input form

![image](https://github.com/trezor/trezor-suite/assets/152851523/b6d41b4d-cabd-4eeb-90c4-1242ed6e7cc1)

**Comment by MiroslavProchazka** [comment]
cc @peter-sanderson please just adjust the padding of "Not enough funds", the rest we will tackle in the future.

**Comment by dahaca** [comment]
@MiroslavProchazka @peter-sanderson spacing already solved in https://github.com/trezor/trezor-suite/pull/11031 🙏
