### ISSUE TITLE
Empower/Invity/ Trade - TXs on account 

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10980]
Trade - TXs on account - counts of types of TXs / filter is barely readable - kerning

<img width="865" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/ea23d6eb-3def-4fc9-ab08-9dd1a600be43">

**Comment by dahaca** [comment]
@IvaFingerova this has been here for 3 years 😓 Moving it to the other milestone

**Comment by zuzjes** [comment]
I am not sure how to solve this issue as there are gaps between the number and tx type. @LukasRada

**Comment by FreeWall** [comment]
@zuzjes \<h> elements has negative letter-spacing (it works for title elements because the font is large). These count types are part of the \<h> element, I think taking them out of \<h> element should fix this.

**Comment by zuzjes** [comment]
@FreeWall thank you!

**Comment by zuzjes** [comment]
![Screenshot 2024-02-27 at 10 58 00](https://github.com/trezor/trezor-suite/assets/41970479/2bdc7b54-a9ca-4a21-a2d1-23b17c44071f)
Removing the H tag helped a lot, thank you.

**Comment by MiroslavProchazka** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/11357

**Comment by STew790** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
