### ISSUE TITLE
Check address

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1099]
**Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa1be4d78bad98ee94396b)

**Comment by glacierbits** [comment]
Merged via #1154

**Comment by bosomt** [comment]
I'm still missing X button to close dialogue :(

![image](https://user-images.githubusercontent.com/31506317/74415523-d31eae00-4e43-11ea-9fe9-15dcec4f508d.png)

**Comment by sorooris** [comment]
@matejzak please let us know if an X button for exiting the modal is desirable.

**Comment by bosomt** [comment]
please decide and then move to Approved or to Test! @matejzak

**Comment by glacierbits** [comment]
We reviewed all scenarios and decided to go for the "no X button" option.
