### ISSUE TITLE
Previous addresses opened

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1100]
**Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f03cbe83f201c1f2af0)

**Comment by szymonlesisz** [comment]
already merged

**Comment by bosomt** [comment]
i prefer this version :)

**Comment by sorooris** [comment]
QA NOK, Hide previous address button is missing.
![image](https://user-images.githubusercontent.com/10185314/74652034-73970a00-5185-11ea-84fa-35d50ae5e7dc.png)
