### ISSUE TITLE
Previous addresses closed

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1101]
**Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f054d29031fdce43ae9)

**Comment by szymonlesisz** [comment]
already merged

**Comment by bosomt** [comment]
it looks like this currently
there is nothing much to test for us,
it looks good for me and we can move it to approved
how about you @sorooris 

![image](https://user-images.githubusercontent.com/31506317/74419461-3b708e00-4e4a-11ea-8830-b8797d9896d3.png)

**Comment by sorooris** [comment]
QA NOK, Show previous addresses button is missing.
![image](https://user-images.githubusercontent.com/10185314/74652098-94f7f600-5185-11ea-8819-6df7c9d241e2.png)

**Comment by glacierbits** [comment]
@sorooris Thanks for the catch. We decided to remove it at the end. Design updated, moving issue to Approved. FYI other Receive details (errors etc.) being handled in separate issue (In Progress).
