### ISSUE TITLE
Install custom firmware feature not working - not detecting image type

### ISSUE THREAD

**Issue by bslabiak** [trezor/trezor-suite#11013]
**Describe the bug**
Install custom firmware feature Firmware not detecting image type
**Info:**

-   Remembered Wallet: yes/no
-   Suite Version: web
-   Browser: chrome 120
-   OS: Mac
-   Firmware Version: 2.6.4

**How to reproduce**

1. Go to Trezor wallet settings
2. Click on Install firmware button
3. Select firmware from official releases  ( eg. [trezor-2.6.4.bin](https://github.com/trezor/data/blob/master/firmware/2/trezor-2.6.4.bin)
4. Error "Unrecognized firmware image type" is disaplyed 

**Expected behavior**
Instal Firmware button should be enabled and user should be able to proceed

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/112852128/880effc9-5c2c-495e-8a62-a160c26944a0)

**Comment by MiroslavProchazka** [comment]
@trezor/qa Can you please check this issue and reproduce it? Thanks!

**Comment by STew790** [comment]
Works fine for me, I was able to reinstall 2.6.4 FW.
![image](https://github.com/trezor/trezor-suite/assets/48477147/4f1c4121-f341-4f0d-b43b-3931d2f0eda4)
![image](https://github.com/trezor/trezor-suite/assets/48477147/389766ad-3720-4061-befd-29a2e5ab76e1)


**Info:**
 - Suite version: web 24.1.3 (240373658ecb4b9ea1e6b09e06e657722ae6c2f1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: BridgeTransport 2.0.32

**Comment by bosomt** [comment]
**QA OK**


managed to install `trezor-t2b1-2.6.4.bin` and `trezor-t2t1-2.6.4` without any problem multiple times, downloaded from github or extracted from app binary

https://github.com/trezor/data/tree/master/firmware/t2b1
https://github.com/trezor/data/tree/master/firmware/t2t1

![Image](https://github.com/trezor/trezor-suite/assets/31506317/c1f5a8ae-0a0a-4f55-a0c6-98c2b155a166)



**Info:**
 - Suite version: web 24.1.3 (240373658ecb4b9ea1e6b09e06e657722ae6c2f1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by bslabiak** [comment]
I managed to downgrade the firmware. I have noticed odd thing.

Issue only exists when I downloaded whole repository and select one of the firmware from data/firmware location. 

If I download single firmware .bin file the issue is not there and I can proceed with changing firmware. Seems like cloning somehow altering bin files.
