### ISSUE TITLE
Empower/ text is not rendered as bold

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11027]
text is not rendered as bold, but shows <string> tag while searching txns in account detail

![image](https://github.com/trezor/trezor-suite/assets/152851523/afb5034c-ff11-45b3-b25e-3ea40bd3660d)

**Comment by peter-sanderson** [comment]
:thinking: this works for me, weird...

![image](https://github.com/trezor/trezor-suite/assets/152899911/1cacbef7-f088-4869-8b1c-c590785d0d34)

**Comment by peter-sanderson** [comment]
This is a translation issue I believe. Token `TR_TRANSACTIONS_SEARCH_TIP_9` is invalid 
 
It contains extra `>` after `<strong>`

=> `<strong>> 2020-12-01 & < 2020-12-31 & > 0</strong>`

**Comment by b-irving** [comment]
Updated in CrowdIn

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (407f7ffdc4e3a3801dd3cc69e48ba9d42e8b7646)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
