### ISSUE TITLE
Do not have the option to switch to Universal Firmware

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#11024]
Following these instructions

https://trezor.io/learn/a/bitcoin-only-firmware-on-trezor
![image](https://github.com/trezor/trezor-suite/assets/48504624/8a48451b-f5d6-4472-bf7b-ca9e6defc50f)

This is what I have

![image](https://github.com/trezor/trezor-suite/assets/48504624/d8413bf0-27ae-4f3e-accc-e473827a153d)

**Comment by nostitos** [comment]
https://forum.trezor.io/t/initial-selection-of-firmware/9652/2

**Comment by MiroslavProchazka** [comment]
Hey @nostitos , thanks for reaching out to us. Which device do you use, please? In some cases, the device can only be used with Bitcoin only FW, such as the Bitcoin-only Trezor Safe 3.

**Comment by nostitos** [comment]
Yes it's a bitcoin only device. Would make sense if there wasn't like 50
places on the internet saying it can be turned into a universal.

Can the universal firmware be manually flashed?

If so where are the files located?

**Comment by Hannsek** [comment]
Switching to Universal fw on BTC only device is not supported in Suite by design. You can however install Universal fw on BTC only device via `trezorctl`.

**Comment by nostitos** [comment]
I hope you get to change your documentation. Everything I read about this was contrary to what you just said.

Also spent way to much time trying to find the firmware's binaries. 

https://trezor.io/learn/a/firmware-changelog

Do we need to build from source?

**Comment by Hannsek** [comment]
Please point us to the documentation when it is said that installing Universal fw on Btc only device is supported in Suite.

**Comment by Hannsek** [comment]
You can find the binaries here: https://github.com/trezor/data/tree/master/firmware/t2b1
