### ISSUE TITLE
Prevent importing incompatible XPUB

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#11029]
- Prevent importing testnet XPUB as Bitcoin mainnet account.
- Prevent importing XPUB for a wrong coin when possible (dodge vs btc).

- keep it simple

Check https://github.com/satoshilabs/slips/blob/master/slip-0132.md
![Screenshot 2024-02-05 at 07 08 56](https://github.com/trezor/trezor-suite/assets/3729633/7d3a7b3f-7dc6-41f9-929a-f83a1901cd4c)

Design: use what we have for other cases - error message on submit.
![Image](https://github.com/trezor/trezor-suite/assets/216917/0a1627a2-9152-4618-9b18-c5e9a53c99f0)

**Comment by juriczech** [comment]
For @trezor/qa - Only available for bitcoin. When testing, test that bitcoin testnet xpub cannot be imported as BTC, all other coins should work same as previously.

**Comment by bosomt** [comment]
Tested TEST > BTC **QA OK**
Tested BTC > TEST and it was imported

This ZPUB 
https://btc1.trezor.io/xpub/zpub6rc2MkTC2EPUy8kHDGpk6NKpTmpdyVo43kiJi4aK2A1ePZpHpVKdYeyuUUUNKvjnBdc488mRPFGeoJTxepcW5kxxHwBhDAhTkZojr9WudhY?secondary=USD&use_secondary=true


Tested on 23.3.1 and 23.4.0
If its ok please approve @juriczech
