### ISSUE TITLE
Do not show zero balance tokens in Send form select

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11037]
**Describe the bug**

Pre-issue of https://github.com/trezor/trezor-suite/issues/6595 to distinguish potential scams

Do not show zero balance tokens in Send form select

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (f2463690bb56fb775fd9df588572f3c40ac7c00c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
