### ISSUE TITLE
Send dialogue minor issues

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11032]
**Describe the bug**
See screenshot
- [x] amount is not properly rendered when you enter fiat value first **(edit: fix by fixed by #11061)**
- [x] when using coin control and there is input with long label its not rendered/shortened properly  **(edit fix here: https://github.com/trezor/trezor-suite/pull/11063)

**Info:**
 - Suite version: desktop 24.2.0 (d3a7b23a070f251e1ef5cfd9064a2b1d3d779026)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="1150" alt="Screenshot 2024-02-05 at 12 43 02" src="https://github.com/trezor/trezor-suite/assets/31506317/779c01c4-8bda-4308-baf8-4e64adcfaa5e">

**Comment by peter-sanderson** [comment]
> amount is not properly rendered when you enter fiat value first

Fixed by: https://github.com/trezor/trezor-suite/pull/11061

**Comment by bosomt** [comment]
**QA OK**

2x OK

**Info:**
 - Suite version: desktop 24.3.0 (b05fc18e49fdf062f2c8db4e7f34dbd81dcd91e2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
