### ISSUE TITLE
Fallback screens

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1103]
**Possible scenarios:**

- [x] Coin is not supported on the particular FW (e.g. T1 > XRP): We need to inform the user in Coin Settings. [**Zeplin**](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f891898121f8d1c8126)

- [ ] Soft coin switch-off: Coin needs to be switched off remotely (via config). Becomes a watch only account, actions on account disabled. Goes together with persistent context notification (and CTA to retry in case of failed Discovery). [**Zeplin**](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5e2fec0f3a028394bdfdfa5d)

- [ ] Hard coin switch-off: BE is broken. We can't allow the user to access the account. Fallback screen on the account view. [**Zeplin**](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5e2fec0f3a028394bdfdfa5d)

- [x] All coins switched off. "Success" empty state screen with CTA to add account. [**Zeplin**](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6efa120829110bc496f4)

**Comment by szymonlesisz** [comment]
missing layouts:

- [x] add account menu when coin is unavailable (eg: T1 + XRP)
- [ ] account fallback view (eg: account was loaded in past but coin was disabled from `future updates`)

layouts above are from `wallet` but those cases should be displayed in `dashboard` as well:

- [ ] Auth error
- [ ] Discovery error (hard, no account loaded)
- [ ] Discovery error (partial, some coins loaded, some not, eg: BTC, LTC loaded, ETH failed)
- [ ] Discovery empty (no coin selected OR available, eg: T1 with ONLY XRP enabled)
- [ ] Passphrase confirmation error

**Comment by glacierbits** [comment]
- [ ] Auth error: **[Zeplin](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5e956e8271e80752c2c071a4)**

- [ ] Discovery error (partial): **[Zeplin](https://zpl.io/VYEWAQd)**

- [ ] Discovery error (hard): **[Zeplin](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5e95916ee0a8467b4acf514e/)**

- [ ] Discovery empty: **[Zeplin](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5e95afe90757177ccd45ce90)**

- [ ] Passphrase confirmation error: Zeplin is coming
