### ISSUE TITLE
Categorise tokens into verified/unverified in send form and tokens section

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11040]
**Describe the bug**

Pre-issue of https://github.com/trezor/trezor-suite/issues/6595 to distinguish potential scams

By introducing token definitions, we can categorise tokens into two sections. Normal (has token definition) and unverified (does not have token definition)

**Send select:**
ETH + verified tokens in one section and `Unverified Tokens` the others 

**Tokens section:**
Verified tokens (no heading) and `Unverified Tokens` the other section with some tooltip explaining it `Unverified Tokens pose potential risks. Use caution.`

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.2.0 (f2463690bb56fb775fd9df588572f3c40ac7c00c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
