### ISSUE TITLE
Suite issues by testing crew 🐕

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-suite#1104]
This is a place for posting issues found by QA team.

**Comment by pankrats** [comment]
**1. Device Settings seem to be accessible when Seed check is run on the device.** 
Device model: TT, fw 2.2.0
 Steps to reproduce:
1) Go to Device Settings -> Check Recovery Seed, press Seed Check.

Expected behavior: Seed check is run on the device and Device Settings menu is disabled in Suite. 

Actual behavior: Device settings menu is still accessible in Suite, so it seems like user can set up PIN protection, passphrase, Device label etc. 

![photo_2020-01-24_14-36-22](https://user-images.githubusercontent.com/31442634/73073539-dadbda00-3eb7-11ea-8275-6cb44fea483d.jpg)
![photo_2020-01-24_14-43-01](https://user-images.githubusercontent.com/31442634/73073540-db747080-3eb7-11ea-8e19-c7f5ba5bdbc5.jpg)

**Comment by bosomt** [comment]
what i found 
- [x]  not able to set **PIN** code with **T1** 1.8.3 FW
- [x]  not able to set **PIN** code with **T1** 1.9.0 FW
- [x] portfolio says 0 value even i see my funds in accounts
- [ ] **tips** section ends in 404 error
- [ ] connect _dropbox_ button is not working
- [x] **support** button is not working
- [x] **show log** button is not working
- [ ] normal fee is 1 sat, but custom **fee** says: Allowed fee is between 100 and 40000
- [ ] Scan QR code - upload image button is not working
- [ ] Don't have a Trezor? Get one sends you to trezor.io and not to shop.trezor.io
- [ ]  Discreet /i don't like this name at all/ doesnt do anything
- [ ] Onboarding says Connect Trezor to continue when you connect onboarded device via onboarding
- [ ] upload image to change wallpaper is not working
- [ ] create backup button doesn't work with 1.9.0
- [ ]  backup failed link What to do now sends you to foooo url
- [ ]  you can hit enter in PIN dialogue without entering any digit
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by pankrats** [comment]
Settings -> General: 

- [ ]  changing Language does not do anyhting

- [ ]  connect Dropbox does not work

- [ ]  Check for updates in Suite version does not do anything

**Comment by mroz22** [comment]
> - [ ]  not able to set **PIN** code with **T1** 1.8.3 FW
> - [ ]  not able to set **PIN** code with **T1** 1.9.0 FW

should be fixed now

**Comment by bosomt** [comment]
there is no close button to leave onboarding dialogue when you connect onboarded device 

![image](https://user-images.githubusercontent.com/31506317/73726246-6282dd80-472f-11ea-981d-ae8f9b424ab7.png)

**Comment by bosomt** [comment]
during onboarding backup button is not working

![image](https://user-images.githubusercontent.com/31506317/73735980-5e12f080-4740-11ea-8ee3-bf25c5749f3a.png)

**Comment by mroz22** [comment]
> during onboarding backup button is not working

transport? I guess it is webusb

**Comment by bosomt** [comment]
> > during onboarding backup button is not working
> 
> transport? I guess it is webusb

nah, bridge, at least i think
no info in log ;) or in wallet

**Comment by bosomt** [comment]
closing due to amount of solved issues/features in suite
