### ISSUE TITLE
Incorrect account label in send dialogue

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11054]
**Describe the bug**
Incorrect account label in send dialogue
I was able to reproduce it on develop and on production version.
When you activate testnet account first and then mainnet account of coin that uses same address you will see incorrect label in send dialogue when sending to address that belong to account that is already discovered. 

**Steps to reproduce:**
1. Activate testnet accounts
2. Activate mainnet accounts 
3. Send TX from mainnet
4. Observe account label

**Info:**
 - Suite version: web 24.1.3 (240373658ecb4b9ea1e6b09e06e657722ae6c2f1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="417" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/a34795f8-c209-4d35-afa6-81ca3488c635">
<img width="651" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/7b9d5c39-f8a1-4214-8e2d-b1ce5cca2950">

**Comment by tomasklim** [comment]
@bosomt @MiroslavProchazka could you please retest? I think I fixed that already

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
