### ISSUE TITLE
connect-popup empower bug

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#11052]
after empower 

<img width="642" alt="image" src="https://github.com/trezor/trezor-suite/assets/30367552/b5f373f8-8441-4d8f-9e4a-9a3ff70dff6e">

@karliatto  please if you could post a fix 🙏

**Comment by karliatto** [comment]
I assume the issue is the separation between the error messages box and the button. Sure I can add a fix for that.

**Comment by mroz22** [comment]
yes, something visually more appealing :D

**Comment by Hannsek** [comment]
just put there a space for now, we'll redesign it soon anyway.
