### ISSUE TITLE
Incorrect copy on Wipe-code modal for T1

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#11069]
**Describe the bug**
Wipe-code modal is using copy from PIN setup.
This is probably not only about copy in Crowdin. I've reused the PIN modal. So there probably needs to be added another one for wipe-code flow. 

![image-1](https://github.com/trezor/trezor-suite/assets/26002916/f7fa2b00-b150-44a7-a937-1aa5f5b790c4)

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/47613707-bb6a-42bd-9474-1915abfa0230)

**Info:**
 - Suite version: web 24.4.0 (366aa93b6dd6ad808d4904e49fc345b14f86394c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33
