### ISSUE TITLE
Invity / coinmarket section never loads in develop version

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11079]
**Describe the bug**
Invity / coinmarket section never loads in develop version

**Info:**
 - Suite version: web 24.2.0 (f2463690bb56fb775fd9df588572f3c40ac7c00c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="791" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/fa3cfb81-ae53-4956-81f6-1837f6e85a5e">

<img width="1035" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/233d3dfb-4e2d-4f51-a1c0-c739e8ac2af4">
<img width="986" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/d3aee8d1-c51f-4cbc-883c-084574d7bcc4">

**Comment by LukasRada** [comment]
That is because we did not released Invity API v2 yet. We will release it ASAP.

**Comment by MiroslavProchazka** [comment]
@LukasRada do you have ETA for it please?

**Comment by LukasRada** [comment]
We have released Invity API v2 on production. Feel free to close this issue.

**Comment by bosomt** [comment]
**QA OK**
