### ISSUE TITLE
Missing fiat value of ERC20 tokens

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11086]
**Describe the bug**
Missing fiat value of ERC20 tokens.
See comparison with production version.

**Info:**
 - Suite version: desktop 24.2.0 (42c94a1fda8c6fde6cdadc8696de4f83f8ae9f37)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="931" alt="Screenshot 2024-02-07 at 14 25 14" src="https://github.com/trezor/trezor-suite/assets/31506317/6afd66ca-6351-46eb-83ee-78da06305c5d">
<img width="624" alt="Screenshot 2024-02-07 at 14 24 56" src="https://github.com/trezor/trezor-suite/assets/31506317/c4bc50bf-c6cc-4790-b598-55d46306a562">

**Comment by tomasklim** [comment]
Fiat rates are missing in case that they are fetched before token definitions are fetched which are fetched on selecting account. I will fix it, if you open app on accounts page, everything should work.

I have to fetch token definitions when account discovery is done, not when account is selected

Problem is in `updateFiatRatesThunk`

**Comment by Hannsek** [comment]
Maybe it is already solved but some tokens do and some don't have the fiat rates. 
<img width="1072" alt="image" src="https://github.com/trezor/trezor-suite/assets/57008159/4d7af2da-b049-4149-afad-5c2bee26ad55">

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/723f6b67-cd09-468e-b6a3-ad6f23a5e458)
![image](https://github.com/trezor/trezor-suite/assets/48477147/b7b09756-dd51-4dc6-a20b-e5dcf0542166)
**Info:**
 - Suite version: desktop 24.2.2 (6544eb4cdb6f8982f3f391307e2bff5784db2bcf)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.2.2 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
