### ISSUE TITLE
Mark all Polygon Mint transaction as potentialy scammy

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11083]
**Describe the bug**
Follow up of https://github.com/trezor/trezor-suite/issues/11071
Consider mark as scammy mint transactions too, our fresh accounts are already full of them

https://matic2.trezor.io/tx/0x3675d633bae4b03667c730a80332f9697717f281e360a258a402302adbdbf88b
https://matic2.trezor.io/nft/0x9fB8b156D1c0a6b81531cbc6ad742BbA295b12E3/1

https://matic2.trezor.io/tx/0x5e71d49f5b3fbd73ce6b17adc89b8f81a78107a08374f5543b301d3e3a71782e
https://matic2.trezor.io/nft/0x3Ba100120a9d1B63502956AbDA2C1e7A5E19E250/1

**Info:**
 - Suite version: desktop 24.2.0 (42c94a1fda8c6fde6cdadc8696de4f83f8ae9f37)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="936" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/34648222-d0ba-4360-86d1-b3e9b5d7eddf">

**Comment by sime** [comment]
@tomasklim Shouldn't this be covered by all NFTs blocking.

**Comment by tomasklim** [comment]
@sime i guess boso is testing on old develop.

**Comment by bosomt** [comment]
**QA OK**

yeah already fixed today /my dev version app was already 2 hours old :) /

maybe we can consider adding switch for hiding this transactions, we never used polygon and we already have almost 200 scammy mints/drops 😡 in tx history

<img width="422" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/e8210f0d-cc11-456c-85f9-46e344561f21">



**Info:**
 - Suite version: web 24.2.0 (3babb0a4b7925b530e3da2b985f6a486f60e0a6f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
