### ISSUE TITLE
Switch devices: Logic

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1108]
**Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6fd8cbe83f201c1f35ba)

Modal (accessible from the primary menu) for switching between wallets and devices. 

When accessed from context of Settings, wallets listed under each Device are to be disabled.

**Comment by petrsulc** [comment]
@matejzak Need to discuss the new logic according to testing results (users confused with different versions of switch device modal).
