### ISSUE TITLE
Empower/ Suite settings color change

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11106]
Settings: Suite version shouldn’t be red, but [grey](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A30256&mode=design&t=HXh74r5A6uJdiKgp-1)

![image](https://github.com/trezor/trezor-suite/assets/152851523/b812d471-7938-413b-aaae-0713052431a4)

https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57-30256&mode=design

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/f51e19b9-7d74-4ffe-ac62-1b11fdd47871)

**Info:**
 - Suite version: desktop 24.3.0 (094fbb029397557a6f4bcbb2390fcdc8de54f3d3)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
