### ISSUE TITLE
Empower/ text not aligned very well

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11109]
Dashboard, Assets list: “No data available” text not aligned very well

![image](https://github.com/trezor/trezor-suite/assets/152851523/10e4cbd3-f74a-4a42-af89-fad979201c4f)

**Comment by bosomt** [comment]
**QA OK**

new way to display error:


![Image](https://github.com/trezor/trezor-suite/assets/31506317/3d93dde4-7c6a-4350-84a8-8f26666b2d33)

**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
