### ISSUE TITLE
Empower/ Change button color in Onboarding

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11108]
Onboarding: [Skip backup] button should be tertiary (grey), not red

![image](https://github.com/trezor/trezor-suite/assets/152851523/3efd808d-5544-45bd-b526-548c5842e68a)

**Comment by martykan** [comment]
This doesn't look the best, but we might want to use red to highlight it's a dangerous action?

**Comment by Hannsek** [comment]
I think you have another confirmation after this screen no?

**Comment by MiroslavProchazka** [comment]
cc @jvaclavik - prober s Ondrou prosím

**Comment by MiroslavProchazka** [comment]
This button should be gray (tertiary)

**Comment by peter-sanderson** [comment]
@MiroslavProchazka Shall this be for the Skip PIN as well?

**Comment by peter-sanderson** [comment]
This is how it looks like: 
![image](https://github.com/trezor/trezor-suite/assets/152899911/ff4e0e85-98b0-42f3-a0da-b16e3f047517)

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/trezor/trezor-suite/assets/31506317/4183ffcd-c3b9-43ff-bc9a-bc2c9cd36c33)
![Image](https://github.com/trezor/trezor-suite/assets/31506317/6283b6af-f5c9-4218-9d3a-786d39308b56)


**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.5 regular (revision 561a697481656a4933e40f200455b07b28b051fc)
 - Transport: BridgeTransport 2.0.33
