### ISSUE TITLE
Analytics for Add new coin

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#11104]
We would like to track Add new account action similar to [Suite event](https://www.notion.so/satoshilabs/accounts-new-account-65a2055499c54a338b9988283482287b?pvs=4).

**Comment by vytick** [comment]
we'll send:

```_c_type: 'coin_discovery/new_account'
  type: 'normal',
  path: "m/84'/0'/1",
  symbol: 'btc'```
