### ISSUE TITLE
Empower/ Obnovit button has wrong padding

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11101]
<img width="283" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/7fc31f5a-9600-49b7-8046-27d75aa050e1">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.3.0 (b05fc18e49fdf062f2c8db4e7f34dbd81dcd91e2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
