### ISSUE TITLE
make connect-explorer webextension build webstore compliant

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#11113]
Make sure that projects using @trezor/connect-webextension package will face no challenges when publishing their webextensions.

- Lets make sure that connect-explorer webextension build is compliant with chrome store requirements https://developer.chrome.com/docs/webstore/publish
- Prepare it to state where it would be publishable if we decided we want to do it. if possible to make it pass google verification process and keep it as a draft without publishing it, lets do it. 
- Should it need some images / icons, just put there some placeholder images. 

Discussion for possible next steps:
- we could release connect-explorer in webextension similarly to how we release the same app to connect.trezor.io/9/
- imho it would be very useful for testing and further development. doing something without referential implemenation isn't easy.

cc @Hannsek

**Comment by karliatto** [comment]
@mroz22 do we still want to do this? I think the webextension is ready, the last thing that would remain to be done would be to really publish it. But we already have some 3rd party integrations that do that, so I am not sure if this is required anymore.

**Comment by mroz22** [comment]
not required anymore
