### ISSUE TITLE
Misalligned/Ugly checkboxes on security cards in Onboarding + different color

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#11111]
![image](https://github.com/trezor/trezor-suite/assets/152899911/58da92ac-9cba-4570-85ca-f5dd65df82a5)
![image](https://github.com/trezor/trezor-suite/assets/152899911/47f97f20-ddf2-4076-9dda-3aabec6cfeef)

**Comment by MiroslavProchazka** [comment]
This happens only when you change width of the screen. Moreover the checkboxes are not visible at all. So I suggest: 


```[tasklist]
### Tasks
- [ ] Adjust the color of the checkboxes or make them more visible via other way - please check with our designer. 
- [ ] Adjust the position of the checkboxes when the screen size of the app is decreasing 
```

**Comment by STew790** [comment]
**QAOK**

![image](https://github.com/trezor/trezor-suite/assets/48477147/bb486c33-ce33-4692-afc2-ca07f5bf16e6)

**Info:**
 - Suite version: desktop 24.2.2 (6544eb4cdb6f8982f3f391307e2bff5784db2bcf)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.2.2 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Win32
 - Screen: 2560x1440
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.31
