### ISSUE TITLE
Switch firmware type modal changelog hint in dark mode even in light mode

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11110]
**Describe the bug**
Switch firmware type modal changelog hint in dark mode even in light mode

**Info:**
 - Suite version: desktop 24.2.1 (fd5d1fa8475b78659e80f19bada6933ca804fab3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.2.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/31506317/f15655f9-4d75-41f3-9996-78907ec0bf0b)

**Comment by bosomt** [comment]
Same result during onboarding

<img width="1185" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/14ec1d56-91aa-431f-a32a-4e441523b887">

**Comment by martykan** [comment]
This uses the tooltip component which is designed to use the opposite of background color. 
So might be working as intended
