### ISSUE TITLE
Notifications panel

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1111]
**Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5e284ca4d043509717d90013)

**Comment by szymonlesisz** [comment]
already in develop,

Actions logged:
- Device connected (one time for new not remembered physical device)
- Wallet created
- Tx sent
- Tx received
- Tx confirmed
- every other notification displayed in Toast
