### ISSUE TITLE
Switch wallets: Logic

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1112]
**Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5e2eb789b530e498136335cd)

Related to _Switch device: Logic_ #1108

**Comment by slowbackspace** [comment]
@matejzak I think we can close this. It is already merged into the develop

**Comment by glacierbits** [comment]
Right you are @slowbackspace
Thanks for the heads-up!
