### ISSUE TITLE
Cardano token definitions

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11126]
**Spec:**

https://www.coingecko.com/en/chains/cardano

TODO

**Comment by bosomt** [comment]
Not sure if its ok or not OK
Suite tries to fetch fiat rates but fails with 404 on response from cdn

 

On test Cardano account we have on SNEK token 
https://explorer.blockfrost.dev/token/279c909f348e533da5808898f87f9a14bb2c3dfbbacccd631d927a3f534e454b

This is what i see in console
<img width="897" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/43a5f140-2755-49b0-918d-1cb358113e42">

And in Suite
<img width="1095" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/5f86c1d4-fa1a-446a-889e-061e04471efd">

SNEK is in top 10 on this list https://www.coingecko.com/en/chains/cardano

**Info:**
 - Suite version: web 24.3.0 (444b665147ebbdfa1237c09dd875052e37d2375a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
