### ISSUE TITLE
UI bug in coinmarket/exchange section

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11133]
**Describe the bug**
Minor UI bug in `coinmarket/exchange` section

1. When adding/discovering account via exchange dialogue there is modal in left up corner of Suite
2. receive address field text overflows from frame

Managed to reproduce it on web dev version and in release candidate app

**Steps to reproduce:**
1. Navigate to coinmarket exchange section
2. Try to exchange coins to coin that's not already discovered

**Info:**
 - Suite version: web 24.3.0 (b05fc18e49fdf062f2c8db4e7f34dbd81dcd91e2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="982" alt="Screenshot 2024-02-09 at 13 43 44" src="https://github.com/trezor/trezor-suite/assets/31506317/8b80ca53-d30c-43aa-bb28-7a7937174d05">
<img width="602" alt="Screenshot 2024-02-09 at 13 42 00" src="https://github.com/trezor/trezor-suite/assets/31506317/446db6da-4822-4a9c-8139-50092ec42b86">

**Comment by jvaclavik** [comment]
Maybe it could be related to this one: https://github.com/trezor/trezor-suite/issues/10720

**Comment by bosomt** [comment]
Sure, i will retest later during weekend as soon it get deployed

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.2.1 (d1eda6c68c4619a7060f1fcc8033ee44c4a94a03)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.2.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
