### ISSUE TITLE
Add token option should also be available for Solana and Cardano accounts

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#11141]
**Describe the bug**
Currently we provide users with option to add token just for Ethereum type accounts. It is missing on Solana and Cardano but they have tokens too.

**Info:**
-   Suite Version: app/web, commit

**Expected behavior**
Option for adding token is also present on Cardano and Solana type account.

**Additional context**
In `packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddTokenModal.tsx` we need to find out why is this code not working out of the box and what we need to change
```jsx
const response = await TrezorConnect.getAccountInfo({
   coin: acc.symbol,
   descriptor: acc.descriptor,
   details: 'tokenBalances',
   contractFilter: contractAddress,
   suppressBackupWarning: true,
});
```

**Comment by tomasklim** [comment]
We removed the feature
