### ISSUE TITLE
Trezor Suite - Low limits in provider's comparator

### ISSUE THREAD

**Issue by misartomas** [trezor/trezor-suite#11147]
**Bug description:**
There is a bug on Trezor Suite (web v24.1.3) - accepted maximum amount for particular provider is set too low (check Devtools - server response) for more information for each provider.

**Info:**
-   Secured wallet + all environments
-   Suite Version: v24.1.3 - desktop + web
-   Browser: Google Chrome v121.0.6167.139
-   OS: MacOs

**Replication steps:**
1. Go directly to https://suite.trezor.io/web/accounts in web browser
2. Click on Trade button => then click on Buy button
3. In fiat input field choose AUD currency and amount 25000 AUD.
4. Then click on Compare offers button
5. Now in comparator check error messages for providers => the maximum accepted amount is way too low (there is a fiat amount that is aminimum amount)
6. As a control - when the user fill out lower amount in input field, there is no problem at all

**Current behavior**
In error message the user can see that the maximum amount is way too low in case the input amount is way too high. The reason is that we take provider’s minimum amount and promote it as maximum amount.

**Expected behavior**
Minimum and maximum amounts should match with provider’s limits.

**Screenshots**
![1a_accepted maximum](https://github.com/trezor/trezor-suite/assets/159724889/eb36d6ee-9963-4cac-b66d-f5eebab7c0eb)

**Comment by bosomt** [comment]
**QA OK**

tested buy section but i was not able to reproduce issue anymore

**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33
