### ISSUE TITLE
Empower/ ADA confirmation small bugs

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11151]
1. The icon next to the broadcast should be aligned
2. Check with Figma if the filed around the check mark should be there
![image](https://github.com/trezor/trezor-suite/assets/152851523/da78b57c-417f-4e9c-8d87-ffaf986876ec)

**Comment by martykan** [comment]
Looks fine to me currently on develop
<img width="781" alt="Screenshot 2024-02-14 at 15 06 17" src="https://github.com/trezor/trezor-suite/assets/8833813/a66a323d-2904-488c-992e-0aded5c41044">

**Comment by MiroslavProchazka** [comment]
Fix should be already on develop branch

**Comment by STew790** [comment]
**QA OK**
The icon next to broadcast is aligned now.
![image](https://github.com/trezor/trezor-suite/assets/48477147/be2c20f7-8e47-4f60-a96d-52c6d4dbfb52)
![image](https://github.com/trezor/trezor-suite/assets/48477147/e28505a4-bbc3-461a-b76d-b4a4f466fd4b)

**Info:**
 - Suite version: desktop 24.3.0 (094fbb029397557a6f4bcbb2390fcdc8de54f3d3)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
