### ISSUE TITLE
Investigate "All backends are down" error

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#11153]
Network issue, hard to reproduce. Try to investigate what are the most common reasons and how to optimize it.

Check some details on internal slack https://satoshilabs.slack.com/archives/C03FL9TCURZ/p1706529781266019

We used to filter this error in Sentry, but the filter is temporarily disabled: https://satoshilabs.sentry.io/issues/?query=%22backends+are+down%22&statsPeriod=90d&utc=true

**Screenshots**
<img width="215" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/7d2f1974-f9f7-4be9-a41f-da6af9842ac0">

**Comment by matejkriz** [comment]
This can be one potential issue, but probably not the only one: https://github.com/trezor/trezor-suite/issues/10726

**Comment by matejkriz** [comment]
related but probably different root cause? https://github.com/trezor/trezor-suite/issues/11148

**Comment by matejkriz** [comment]
general sentry issue https://github.com/trezor/trezor-suite/issues/5071

**Comment by vytick** [comment]
For @trezor/qa:

This change might have broken any blockchain connection in both desktop and mobile apps. More precisely it touches disconnecting and reconnecting blockchain backends after the network disconnect happened. 

What might be worth to test in bigger detail: 

Apps should recover blockchain if they go offline and online again. 

In mobile this should be working and if it fails, it is a bug:
- sync account or connect device with accounts
- wait for account balances and details fetch
- go offline or enable airplane mode -> goes offline
- on home pull for refresh
- app shows All backends are down
- enable connection again
- pull for refresh again
- All backends are down error should go away and graph should load

**Comment by bosomt** [comment]
**QA NOK**

iphone:

![image](https://github.com/trezor/trezor-suite/assets/31506317/7fa7ea8a-59ce-4fcd-b0b3-ce1682fa4e69)

Android: 

forever `retrieving data` message

**Comment by vytick** [comment]
@bosomt In flight mode there will always be the error since you are offline. Does it recover after you go back online?

**Comment by matejkriz** [comment]
btw, here is the sentry report of `ETH: Get account balance movement error: All backends are down` https://satoshilabs.sentry.io/issues/5241887464/events/93dde4291e3e4c1080f377d7b2a3627e/

**Comment by STew790** [comment]
Also, in desktop Suite, there is only `Backend disconnected` and Suite is trying to reconnect all the time and nothing else. I remember there was a red banner warning at the top that you are disconnected, no? (maybe @matejkriz knows) It isn't in production as well, so that might be a different issue and possibly Suite desktop only thing but I just wanted to mention it because I remember the banner was definitely there before.
![image](https://github.com/trezor/trezor-suite/assets/48477147/9dd87c65-2758-49c1-935e-a8828fdcb6ce)

**Comment by vytick** [comment]
I created a new issue for this #12109

**Comment by matejkriz** [comment]
Moved back to Approved in 24.04 as this solved the issue of user get forever stucked on All backends are down even after going back online.
