### ISSUE TITLE
Missing frame of name and homescreen buttons in Setup complete modal

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11150]
**Describe the bug**
Missing frame of name and homescreen buttons in Setup complete modal.
Same result in develop version of Suite.
Same results in browser and desktop app.

**Steps to reproduce:**
1. Proceed with device onboarding
2. Check `Setup complete!` modal

**Info:**
 - Suite version: desktop 24.2.1 (d1eda6c68c4619a7060f1fcc8033ee44c4a94a03)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.2.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.12.1 bitcoin-only (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="817" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/494d4c89-83bc-4a6b-bfb2-6a12fafd5f37">

**Comment by STew790** [comment]
**QA NOK**
Unfortunately, i still barely see the frames of the buttons. And not only here:
![image](https://github.com/trezor/trezor-suite/assets/48477147/7a38dcf5-4fe3-4571-8c78-8b512d797899)

but also here:
![image](https://github.com/trezor/trezor-suite/assets/48477147/dd1a87a7-7b9a-410e-baa8-3e977553e624)

Should I create a separate issue for it? 

**Info:**
 - Suite version: desktop 24.3.0 (0aa33ed34c5ded3b67310af8e3931501e91ce1f5)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: BridgeTransport 2.0.33

**Comment by MiroslavProchazka** [comment]
@stew

**Comment by MiroslavProchazka** [comment]
Looks good on my TS3. @trezor/qa please check also on T1 and TT. Thanks!
<img width="1062" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/030987f7-81e9-460f-9edc-47b38299fe1b">
<img width="799" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/2a3d037c-e52a-4162-b4d7-b6d35653094f">

**Comment by STew790** [comment]
**QA OK**
Buttons are visible for TT and T1 as well.

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
