### ISSUE TITLE
Investigate fetching fiat rates

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#11174]
- Are we overfetching? 
- ~Can we start using the logic shared with desktop?~ DONE
- What about fallback to coingecko directly in case of rate limit on CDN?
- We are facing "Unable to fetch fiat rates for defined timestamps" which is blocking the dashboard graph. The issue is mostly (only?) with cardano.

related [internal slack thread]( https://satoshilabs.slack.com/archives/CKZHV2G13/p1706195249563519)
[notion page](https://www.notion.so/satoshilabs/Hitting-rate-limit-on-CoinGecko-4d4e69e2d81a49fd85b1e51dfd50639a?pvs=4)

**Screenshots**
<img width="600" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/0ef0965d-66c2-4eef-8151-8f6b5ee6c885">

**Comment by davehorner** [comment]
crashes the app most times, sometimes it works.  troublesome problem.

**Comment by mnuky** [comment]
closing in favour of https://github.com/trezor/trezor-suite/pull/11592

**Comment by mnuky** [comment]
closing in favour of https://github.com/trezor/trezor-suite/pull/11592

**Comment by mnuky** [comment]
closing in favour of https://github.com/trezor/trezor-suite/pull/11592
