### ISSUE TITLE
Passphrase: Styling

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1118]
**Zeplin** [here ](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/dashboard?seid=5e315abc3c48197f8d2cc4b7)

**InVision flow** [here](https://projects.invisionapp.com/share/Y8VQJ28PUZ7#/screens/402575375_7-5-0-Pass_Source_Select_-_Home_-)

**Comment by slowbackspace** [comment]
merged, closing the issue. feel free to reopen if there is something horribly wrong :)

**Comment by sorooris** [comment]
@matejzak @petrsulc Is the InVision flow link still relevant?

**Comment by petrsulc** [comment]
> @matejzak @petrsulc Is the InVision flow link still relevant?

Yep, apart from the missing "try again" flow.

**Comment by bosomt** [comment]
looks and works as expected,
if we find any kind of issue we will create separate issue
