### ISSUE TITLE
Dashboard shows different balance then account

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#11215]
**Describe the bug**
When I import in my Portfolio an ETH account and I sent my funds from that account to another, the dashboard shows incorrectly still the same balance and it differs from the balance of the Account and Account details. (screenshots attached)

**Info:**

-   Mobile Suite Version: 24.1.1 (28) 3c4a0da
-   OS: both

**How to reproduce**

1. Import account with some balance 
2. Send the whole balance to a different account
3. See that the balance still shows on dashboard
4. The balance is 0 in the account section and in the Account details

**Expected behavior**
Balance in dashboard is the same as in account/account details

**Screenshots**
Dashboard
![image](https://github.com/trezor/trezor-suite/assets/48477147/8aa33832-bcd0-466f-9ffd-271c7059f9ac)

vs Account details
![image](https://github.com/trezor/trezor-suite/assets/48477147/6abbd3a2-118a-4a26-8d91-2d17b9e2529c)

**Comment by matejkriz** [comment]
related internal slack thread: https://satoshilabs.slack.com/archives/C03FL9TCURZ/p1707811206594579

**Comment by matejkriz** [comment]
Could it be somehow connected to this? https://github.com/trezor/trezor-suite/issues/11231

**Comment by STew790** [comment]
Unforunately, it seem that I might not have been just patient enough. After a while the transaction was still seen as "pending" but the dashboard graph and price update so I saw 0 there. I will try to investigate this further. (might be connected to the issue @matejkriz posted because it happened to me a lot of times when I was trying this one)

**Comment by sime** [comment]
Dropping priority due to the lack of reproducibility.

**Comment by STew790** [comment]
Hopefully fixed by this :pray: 
https://github.com/trezor/trezor-suite/pull/15815
