### ISSUE TITLE
Export as .csv or .pdf

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1121]
**Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6eec1b06a0202b351f1f)

**Comment by slowbackspace** [comment]
Instructions not clear. Moved to Q2.

**Comment by glacierbits** [comment]
@slowbackspace How cheeky.

**Comment by mroz22** [comment]
note:  dont forget to use workers for building files for export. large seeds tend to freeze pc using main thread. inspiration to be found in mytrezor repo

**Comment by mroz22** [comment]
Actually this feature is quite easy to implement, once we have designs.

**Comment by glacierbits** [comment]
Duplicity #2085
