### ISSUE TITLE
Calendar icon cut off on TX detail screen

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#11217]
**Describe the bug**
Calendar icon cut off on TX detail screen

**Info:**

-  Mobile Suite Version: 23.3.1/2434be24
-   OS: Android 13

**How to reproduce**
Open TX detail

**Expected behavior**
<details><summary>Production shows the icon correclty</summary>

![Screenshot_20240216-140430921](https://github.com/trezor/trezor-suite/assets/216917/f54262bb-05cc-4e27-91e9-972a69253ecd)

</details> 

**Screenshots**

![Screenshot_20240215-163252636 (1)](https://github.com/trezor/trezor-suite/assets/216917/57a0dd81-8aab-4315-8e84-68de1f7297d1)

**Comment by bosomt** [comment]
**QA OK**

Android 14 - Nothing Phone 1
24.3.1 (24) dev version 6e9d8d6
