### ISSUE TITLE
Chain icon in DeviceStatus is visible before showing the device name

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#11229]
https://github.com/trezor/trezor-suite/assets/858321/52e6267f-ffe1-4fc1-b9e6-cb1982064b5a

**Comment by MiroslavProchazka** [comment]
Please take a look also on the "Activate coins" button - that should not be visible during discovery because it breaks the padding between coin filter.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.3.0 (b8e43cdb821472b7d6db8d60936947cec0b0b6da)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.6.5 regular (revision e1f696b4dd8c024a9ceca276d7336b4d93ae7ff2)
 - Transport: BridgeTransport 2.0.33
