### ISSUE TITLE
connect e2e testing strategy

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#11228]
There are many tests across the monorepo related to connect. Lets wrap it up.
  
| package  | purpose  | testing focus  | testing matrix | legacy  |  canary  |
|---|---|---|---|---|---|
| connect  | core logic, api definition  | test api, all possible params and results   | `node/web`, `blockchain:mocked/unmocked`   | old firmwares  | future firmwares| 
|connect-popup  | UI,  partially communication logic between `api definition layer` and `core`  |  UI part ([methods](https://github.com/trezor/trezor-suite/blob/develop/packages/connect-popup/e2e/tests/methods.test.ts#L4-L5), [passphprase](https://github.com/trezor/trezor-suite/blob/develop/packages/connect-popup/e2e/tests/passphrase.test.ts#L4-L5)..?) | x  | old browser  | future browser (chrome canary channel)
|  connect-web  | this is the `api definition layer`. it talks to `core` which can live either inside iframe or popup  |  communication between popup, core, and api layer works. UI is properly opened and closed | core-in-iframe, core-in-popup  | old npm package with new trezor.io (popup, iframe)  | x
|  connect-webextension | similar to connect-web  |  similar to connet-web | x  | old npm package with new trezor.io (popup)  | x

The table above displays basic categorization of tests and their focus. Now it is time to set which tests should be run when

| when  |  on PR push | on develop merge   |  nightly  |  note |
|---|---|---|---|---|
| connect - node  |   |   |   |   |
| connect - node - legacy |   |   |   |   |
| connect - node - canary |   |   |   |   |
| connect - web - legacy |   |   |   |   |
| connect - web - canary |   |   |   |   |
| connect-popup - web  |   |   |   |   |
| connect-popup - web - legacy |   |   |   |   |
| connect-popup - web - canary |   |   |   |   |
| connect-web  |   |   |   |   |
| connect-web - legacy |   |   |   |   |
| connect-webextension  |   |   |   |   |
| connect-web - legacy |   |   |   |   |

notes to think about:
- blockchain-link mocked / unmocked?

<img width="1044" alt="image" src="https://github.com/trezor/trezor-suite/assets/30367552/ed08feee-db53-4818-8a72-1775a19c227a">

**Comment by karliatto** [comment]
I think `nightly` we should run all the test and probably if we run it on PR push and it works properly meaning it runs when it has to run, then there is no added value in running any of those test on develop.
