### ISSUE TITLE
Button is overflowing 'Passphrase dupliated' dialogue window  

### ISSUE THREAD

**Issue by zaplmi** [trezor/trezor-suite#11226]
**Describe the bug**
When entering the same hidden wallet repeatedly in Suite version 24.2.1 the _Passphrase duplicated_ has one button 'try different passphrase' that is overflowing the dialog window.

**Info:**

-   Remembered Wallet: no
-   Suite Version: 24.2.1 desktop (current EAP)
-   OS: macOS
-   Firmware Version: Universal 2.6.4

**How to reproduce**

1. Access any hidden wallet 
2. Click on +Add hidden wallet in wallets overview
3. Enter the same passphrase 
4. See the error in the _Passphrase duplicated_ dialog window 

**Screenshots**

![image](https://github.com/trezor/trezor-suite/assets/91535734/9f6b3739-76fb-4d54-907b-e5440de02d78)

**Comment by mroz22** [comment]
this could have been caught by visual regression tests if we had the active

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/9dc6974d-8c93-4f3a-a596-29cad755e16c)

**Info:**
 - Suite version: desktop 24.3.0 (0aa33ed34c5ded3b67310af8e3931501e91ce1f5)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by zaplmi** [comment]
the issue still persists on the 24.2.1 **web version**
