### ISSUE TITLE
Align Suite with device screens when displaying taproot XPUB

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#11239]
Next FW (2.6.5) will display the whole descriptor instead of just XPUB for taproot (and coinjoin) accounts - just as Suite does currently. However, TS3 requires a space of 3 screens while Suite only shows two. See https://github.com/trezor/trezor-firmware/pull/3505#issuecomment-1929120642

Check TT as well, T1 is unaffected.

Related: https://github.com/trezor/trezor-suite/issues/11238

**Comment by bosomt** [comment]
Not sure if this is expected outcome




![Image](https://github.com/trezor/trezor-suite/assets/31506317/41a3121b-71c7-4be4-977e-51f93afd6b60)



![Image](https://github.com/trezor/trezor-suite/assets/31506317/01b98f3d-4b7a-4b7b-8f9d-faef3ac5f5ce)





**Info:**
 - Suite version: web 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.6.5 regular (revision a784c4046e79ae138f9a7a9c5e97d2f6771140eb)
 - Transport: BridgeTransport 2.0.33

**Comment by komret** [comment]
@bosomt Do you mean the extra characters at the end of the string displayed on Trezor? Will be added in https://github.com/trezor/trezor-suite/pull/11314.

**Comment by bosomt** [comment]
@komret yes and derivation path , device shows `h` and Suite `'`

or not derivation path of course, maybe account type descriptor ?

**Comment by komret** [comment]
Should also be tackled there.

**Comment by komret** [comment]
**QA:**

Resolved by https://github.com/trezor/trezor-suite/pull/11251
The third screen will only be visible when https://github.com/trezor/trezor-suite/pull/11314 is merged

**Comment by bosomt** [comment]
**QA OK**

S3 - 3 screens and device matches app
T - 2 screens and device matches app

**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 -  - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
