### ISSUE TITLE
Graph: Last touched point on graph is persisted through refresh + balance is taken from different device when view-only enabled

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#11231]
**Describe the bug**
Last touched point on graph is persisted through refresh
When user has two devices in view-only and refreshes the dashboard, the balance is refreshed from the different device - see the video. 

**Info:**

-   Mobile Suite Version: 24.3.1
-   OS: Android, 13

**How to reproduce**
Balance persisted on graph:
1. Choose a point on the graph that is different from the portfolio balance
2. Pull down to refresh
3. Note the old selection price represented as the portfolio balance

Balance persisted from second device
1. Have two devices in view-only
2. refresh graph on dashboard on one
3. The balance from the other one appears

**Expected behaviour**
Current portfolio balance to be visible

**Screenshots**
https://github.com/trezor/trezor-suite/assets/216917/20dd4053-e130-4738-8291-5533bfc27715
[

https://github.com/trezor/trezor-suite/assets/84183817/2a07fcf5-6405-4e9b-8867-f94b5b3992cf

](url)

**Additional context**

**Comment by sime** [comment]
Time selector shows the wrong portfolio balance after long pressing on the graph and changing the dates.



https://github.com/trezor/trezor-suite/assets/216917/21bebef8-bf78-4755-998a-8124b45edb3c

**Comment by tsusanka** [comment]
Gotta say that this one is really annoying. I don't even think you need to refresh, it just happens after you switch to another view.

**Comment by matejkriz** [comment]
With view-only, it happens also cross wallets 😞

**Comment by STew790** [comment]
I am not really sure if this is OK or not but I can see just for a split second still the persisted point on graph. Video below:

Uploading 1000011988.mp4…

**Comment by STew790** [comment]
I don't know why the video didn't upload, lets hope this works:

https://github.com/trezor/trezor-suite/assets/48477147/90894de1-8348-4c2b-b698-563c5ce2a188

**Comment by matejkriz** [comment]
@STew790 It's not a new bug, it is on current production. Could you please create a new bug issue for it to not block this one?

**Comment by STew790** [comment]
Done.

**QA OK**

24.5.1 https://github.com/trezor/trezor-suite/commit/319a98a62131c0d0ddd2eb238cb8530a540764a3
