### ISSUE TITLE
Add checksum behind taproot descriptor

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#11238]
Next FW (2.6.5) will append a checksum to a taproot descriptor. Suite should display it as well. See https://github.com/trezor/trezor-firmware/pull/3505#issuecomment-1929120642.

Relevant for bitcoin taproot and coinjoin accounts on TT and TS.

Related: https://github.com/trezor/trezor-suite/issues/11239

**Comment by Hannsek** [comment]
Duplicate https://github.com/trezor/trezor-suite/issues/10963
