### ISSUE TITLE
Trezor Suite reports last day of fiat rates updates as 1.1.1970 before it gets date from servers

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11230]
**Describe the bug**
Trezor Suite reports last day of fiat rates updates as 1.1.1970 before it gets date from servers.
Same results in EAP and in dev version of app

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: web 24.3.0 (d1c8f966e1f74f6c1d916eff24201ad6021ea58d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="738" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/eb5ac6c8-b7fa-4781-8791-ea056fb1d4fd">
<img width="596" alt="Screenshot 2024-02-19 at 9 48 49" src="https://github.com/trezor/trezor-suite/assets/31506317/c0f756b7-1bd8-4f57-b984-47723cee902c">
<img width="590" alt="Screenshot 2024-02-19 at 9 47 36" src="https://github.com/trezor/trezor-suite/assets/31506317/5f6f8361-4594-4afb-89f8-231f6c7b25ae">

**Comment by tomasklim** [comment]
Will be fixed in https://github.com/trezor/trezor-suite/issues/10435
