### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1123]
First version: Search transactions and addresses.

Modal: **[Zeplin](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5e79c9b29ad455629e3ea563)**

Results scroll: [**Zeplin**](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5e79c9b18b52437106eabf61)

**Comment by slowbackspace** [comment]
wow, this design needs an update! 😬

**Comment by glacierbits** [comment]
Let's close it and pretend it didn't happen. Just kidding, new design #2085
