### ISSUE TITLE
Allow trading of tokens on Solana in trade section

### ISSUE THREAD

**Issue by LukasRada** [trezor/trezor-suite#11253]
Because we have newly add Solana into Trezor Suite, we can allow trading of Solana tokens.

For example show Select component in buy/exchange/sell in Solana account with options of trading tokens like we see it in Ethereum account trading.
![image](https://github.com/trezor/trezor-suite/assets/7394177/a0358336-45d3-4b2a-ab65-4a4dbfae0060)

Goal is to see Select like this but with values like SOL, USDT, USDC, etc...
![image](https://github.com/trezor/trezor-suite/assets/7394177/59c859a8-0cab-4b14-9b04-cbf239b94618)

For buy we offer only those tokens provided by our partners.
For exchange we offer only those tokens held by a user and offered by our partners.
For sell it is the same as for exchange.

And also being able to fully trade such tokens with our partners (buy/exchange/sell) where partners support.

**Comment by bosomt** [comment]
I dont see any tokens in sell or exchange section, even i have 7 tokens.
Are they filtered ?



![Image](https://github.com/trezor/trezor-suite/assets/31506317/918b48ba-b34a-4dfb-b047-0c60877a8758)



![Image](https://github.com/trezor/trezor-suite/assets/31506317/331df176-96fa-42b8-a8b4-af21f96db6cb)



**Info:**
 - Suite version: web 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.6.5 regular (revision a784c4046e79ae138f9a7a9c5e97d2f6771140eb)
 - Transport: BridgeTransport 2.0.33

**Comment by FreeWall** [comment]
They are hidden probably because invity comparator doesn't support them for trading yet, they should be enabled by Wednesday hopefully.

**Comment by bosomt** [comment]
**QA OK**

tested on staging invity backend
i can see tokens in selection


![Image](https://github.com/trezor/trezor-suite/assets/31506317/ac31d0b8-2e9d-441d-876c-7536b6593613)



**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
