### ISSUE TITLE
`Activate coins` is redundant in case of Bitcoin-only FW

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#11257]
**Describe the bug**
There is no need to try searching of other coins when I'm using bitcoin-only firmware:
![Screenshot 2024-02-21 at 08 31 03](https://github.com/trezor/trezor-suite/assets/26002916/403fbbe9-6af8-4193-a4e1-5e8a7bb8e491)

**How to reproduce**

1. Use bitcoin-only firmaware
1. Go to Coins settings
1. See redundant `Active coins` button

**Comment by hynek-jina** [comment]
If it's meant to run the discovery that it should be triggered automatically by activating coin (bitcoin or bitcoin testnet)

**Comment by komret** [comment]
It is meant to run discovery. If we want to trigger discovery automatically, it should be done for both types of firmware for consistency IMO. Closing.
