### ISSUE TITLE
Staking set dressing: Fund leaving Trezor

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#11256]
# User Story
As an Ethereum User
I want to know the risks of staking on Trezor
So that I can evaluate any security concerns

# Acceptance Criteria
Given I am on the Staking in a nutshell modal
When I click continue
Then I should see 'Your staked funds are managed by...'

# Design
https://www.figma.com/file/0Kz3w6WDlvQm62RjOm87na/Staking?type=design&node-id=4285-21022&mode=design&t=52EcRrIDbhO337OD-4

**Comment by bosomt** [comment]
**QA OK**


![Image](https://github.com/trezor/trezor-suite/assets/31506317/aa7b5abf-f10e-48dc-a147-aec5d0987b7e)



**Info:**
 - Suite version: web 24.4.0 (3a5dee13187d9decb0592c009a9c9e1d5704a7bc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
