### ISSUE TITLE
Guide icon overlays PromoBanner

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#11270]
<img width="1342" alt="Screenshot 2024-02-21 at 14 56 47" src="https://github.com/trezor/trezor-suite/assets/858321/59e6fc06-7fe5-415d-8fe5-27039bd0d172">

**Comment by MiroslavProchazka** [comment]
@trezor/qa Can you please verify if is this still valid?

**Comment by bosomt** [comment]
**QA NOK**

yes it does

<img width="143" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/18f37521-2e76-47b5-a232-60b16668baad">

**Info:**
 - Suite version: desktop 24.4.3 (41c16dcd8caf5cc9501a038608d3e4d2cd50baf7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by hstastna** [comment]
@bosomt @jvaclavik Is this ever a bug? I can see the Guide icon is simply always at the same place, simply being over any content under it. It seems to me this is intentional behavior for keeping this icon always accessible, visible, so the user won't need to scroll or anything else to see it. And if it overlays some banner or anything else - it depends on the size of the window and/or zoom level. Thanks.

**Comment by jvaclavik** [comment]
> @bosomt @jvaclavik Is this ever a bug? I can see the Guide icon is simply always at the same place, simply being over any content under it. It seems to me this is intentional behavior for keeping this icon always accessible, visible, so the user won't need to scroll or anything else to see it. And if it overlays some banner or anything else - it depends on the size of the window and/or zoom level. Thanks.

@hstastna: Yes, Guide icon has fixed position and we should keep it that way.
But no matter what, it overlays google play button. We shouldn't touch guide button, but we should add right margin to google play banner.

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/trezor/trezor-suite/assets/31506317/e63bf9d1-1b30-4e1f-a432-aedb1728d742)



**Info:**
 - Suite version: web 24.8.0 (77f85770245bade10fdaa9da7404cb385bd4c272)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
