### ISSUE TITLE
Accounts Refresh button always visible with Cardano

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#11285]
**Describe the bug**
When Cardano is enabled, the `Don't see an account after activating a coin? [Refresh]` element and the `Activate coins` button are visible all the time, although it should disappear after 1st refresh after any Coins Settings change. 

**Info:**

-   Suite Version: app, 24.2.1
-   OS: MacOS, 14.1.2 (23B92)
-   Bridge: 2.0.33
-   Firmware Version: TT, 2.6.4

**How to reproduce**

1. Go to 'Settings > Coins'
2. Enable Cardano
3. Click [Activate coins] or [Refresh]
4. Observe the `Don't see an account after activating a coin? [Refresh]` element and the `Activate coins` button still visible below your accounts nad in the Coin setting
5. Try deactivating Cardano (just for comparison)
6. Observe the controls disappear correctly

**Expected behavior**
The `Don't see an account after activating a coin? [Refresh]` element and the `Activate coins` button should disappear after 1st refresh after any Coins Settings change. 

**Screenshots**
![Feb-21-2024 17-32-17](https://github.com/trezor/trezor-suite/assets/88533514/c81d9167-0271-42fc-b418-0cb8b63263d9)

**Additional context**
It seems to be caused by a Cardano implementation bug.

**Comment by marekrjpolak** [comment]
Partially working fix here, completion needed: https://github.com/trezor/trezor-suite/commit/9df5accb07f25c9c4637ee12b0938e3f7365f1fb

Explanation: initial `total` is calculated from all the possible Cardano account types (`normal`/`legacy`/`ledger`) but some of them are later omitted from discovery based on (asynchronously obtained) `availableCardanoDerivation`, so `total` is never met. Therefore, `total` must be correctly recalculated whenever ADA is turned on/off or `availableCardanoDerivation` changed.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.4.0 (0072d9131891ee8335fa16d285e534e3f7767625)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
