### ISSUE TITLE
Main menu "?" cursor on account titles

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#11286]
**Describe the bug**
When hovering over an account title (and fiat valua) in the main menu, the cursor changes to a "?"

**Info:**

-   Suite Version: app, 24.2.1
-   OS: MacOS Sonoma

**How to reproduce**

1. Go to main menu
2. Hover on some account title or its fiat value
3. Observe cursor change to "?"

**Expected behavior**
The cursor should remain being a pointer

**Screenshots**
![Feb-21-2024 17-38-44](https://github.com/trezor/trezor-suite/assets/88533514/eb28d006-0708-45c5-ad32-0c7694d93e0f)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.6.5 regular (revision a784c4046e79ae138f9a7a9c5e97d2f6771140eb)
 - Transport: BridgeTransport 2.0.33
