### ISSUE TITLE
Data Analytics: Device Update Firmware fix

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#11302]
We would like to add parameter `Model` with device name to event [device-update-firmware](https://www.notion.so/satoshilabs/device-update-firmware-862ec5e97f0c41c98dc035412be83721?pvs=4) so we can distinguish TS3 from TT or any future Trezor models sharing the same firmware.

**Comment by bosomt** [comment]
**QA OK**

analytics: `model=T2T1&fromFwVersion=2.7.2&fromBlVersion=&error=&toFwVersion=2.7.2&toBtcOnly=true`

**Info:**
 - Suite version: web 24.7.0 (0959ca14fb3b440d4f849e9c8bf7d3688afd6b94)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 bitcoin-only (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
