### ISSUE TITLE
Remembered wallet: all ERC-20 tokens unrecognised and scammy txs not labeled

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11307]
**Describe the bug**
When Suite is launched with remembered wallet, token-definitions are not fetched. All tokens are marked as unrecognised and no txs are labeled as scammy.
Create/update redux action has to be called to fetch token definitions. e.g. new tx or disabling and enabling coin does that.

https://www.reddit.com/r/TREZOR/comments/1ax5q80/trezor_suite_update_2422_token_as_uncategorized/

**Info:**

-   Remembered Wallet: yes
-   Suite Version: 2024.2.1

**How to reproduce**

1. Remember wallet
2. Restart Suite

**Screenshots**
Remembered wallet:
<img width="1191" alt="Screenshot 2024-02-22 at 16 39 27" src="https://github.com/trezor/trezor-suite/assets/33235762/0efd0727-6db8-4b27-b5cf-c6b5dd0b3264">
<img width="751" alt="Screenshot 2024-02-22 at 16 44 24" src="https://github.com/trezor/trezor-suite/assets/33235762/ac43db46-e233-4c73-9dbb-4062f6d62b31">

Non-remembered wallet:
<img width="1182" alt="Screenshot 2024-02-22 at 16 40 32" src="https://github.com/trezor/trezor-suite/assets/33235762/d3f0c76c-cdae-43b6-bef6-827eea6b9f0e">
<img width="760" alt="Screenshot 2024-02-22 at 16 47 25" src="https://github.com/trezor/trezor-suite/assets/33235762/e289f9b3-f7de-4877-b271-39e5c3cf21e2">

**Comment by STew790** [comment]
**QA OK**
After remembering and restarting wallet, ETH token definitions are OK.

![image](https://github.com/trezor/trezor-suite/assets/48477147/53f35f13-a5a5-4f34-adad-1167dada3e64)

**Info:**
 - Suite version: desktop 24.2.3 (c7dd0f7b0d64ce2d06bbece30f746799bdc914c4)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.2.3 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
