### ISSUE TITLE
Search button/field doesn't work properly

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#11312]
**Describe the bug**
Search button/field doesn't work properly.
<img width="116" alt="image" src="https://github.com/trezor/trezor-suite/assets/57008159/a5424b46-4e14-4a84-be15-dd1b7d1f1aea">

1. when mouse over the button, there should be the "hand" and not cursor.
![image](https://github.com/trezor/trezor-suite/assets/57008159/1a186c59-75de-47c3-a747-556c19364f8a)

2. when you type something into the field, the "x" button doesn't work 
<img width="23" alt="image" src="https://github.com/trezor/trezor-suite/assets/57008159/4a9f39b8-d205-4fb9-b76a-949e5e31fd8c">

**Info:**

-   Remembered Wallet: yes
-   Suite Version: 24.2.2

**How to reproduce**

1. hover over the button
2. type some text into the text field and try to delete with the "x" button

**Expected behavior**
1. See a hand on hover
2. be able to delete the whole text with the "x" button

**Comment by bosomt** [comment]
X button works as expected and hover changes cursor. Bot attached some nitpicks. @MiroslavProchazka follow up ? reopen ?

Cursor changes as you move pointer above looking glass icon. see video

https://github.com/trezor/trezor-suite/assets/31506317/714b916e-643f-44b1-bc7c-375ee03e2508



when you click on search field cursor is not active and you have to click again to enter search text

https://github.com/trezor/trezor-suite/assets/31506317/2c1761d8-ef64-4657-9be5-0c17e1442a1b

**Info:**
 - Suite version: desktop 24.6.0 (e9a042518338e1b23fbf1542d4f08ea64dd930cd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by peter-sanderson** [comment]
Fixed the cursor issue, however the "you have to click again to enter search text" is not happening to me.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.0 (a72b06ae4b20a7a1f4992769371e1dea18996639)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 3.0.0-bundled.24.11.0
