### ISSUE TITLE
Add new coin 6 - locked device

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#11317]
After the discussion with @matejkriz: 

Blocked by [#10596](https://github.com/trezor/trezor-suite/issues/10596) 

Once the blocking task is merged to develop, check, whether there is any action to take or handling of this task is already solved by mentioned PR.

Acceptance criteria:
- [x] When adding account to locked device, flow should be canceled until device is unlocked
- [x] Flow must cancel if device is locked anytime during the flow

**Comment by bosomt** [comment]
**QA OK**

Noticed that when you try to add new account and you cancel PIN dialogue on TT you will get `unknown technical issue` in Lite app.
Not sure if its not covered by mistake or it will be implemented later

24.4.0 (74)
Last commit hash: 2882f42525f5173c6673e0b4c41c9644c2ccb92e
