### ISSUE TITLE
Coinjoin loading funds not working

### ISSUE THREAD

**Issue by JakubSlovak** [trezor/trezor-suite#11313]
2 days back I was using coinjoin normally. . The device was then disconnected. Subsequently, since yesterday I have been trying to scan my wallet and find funds. Unsuccessfully.
A complete reinstallation of the application was performed. Then also tried different hardware. Unsuccessfully.
 Could this be an error on your end?
 
 
![image](https://github.com/trezor/trezor-suite/assets/84938209/6f05f02b-eaa5-438e-be56-4afd4e7e21ed)

![image](https://github.com/trezor/trezor-suite/assets/84938209/fadd62a6-b5d9-4544-a656-ca59f8067a51)

**Comment by sime** [comment]
Hi @JakubSlovak 

Thanks for reaching out. We are seeing the same thing, still investigating.

**Comment by sime** [comment]
@JakubSlovak Could you try and again. Looks like Tor proxy might have being fussy.

**Comment by JakubSlovak** [comment]
Currently it seems to be resolved.
Accout was find. 
Thank you for your help.
