### ISSUE TITLE
Coinjoin status inconsistent and not easy to understand.

### ISSUE THREAD

**Issue by Transisto** [trezor/trezor-suite#11327]
Top message constantly say "Signing start in ... "  While the main part say something different, That don't mean much either. "Registering coins"

![image](https://github.com/trezor/trezor-suite/assets/388716/5dd92205-2e11-439a-9fa0-4ef41581c926)

![image](https://github.com/trezor/trezor-suite/assets/388716/c9a6a572-6879-47e2-9b37-c8242e605c16)

...

![image](https://github.com/trezor/trezor-suite/assets/388716/b37adb04-7500-4453-84c6-9c931a89943d)

![image](https://github.com/trezor/trezor-suite/assets/388716/4aa14ad1-7ce9-4d84-b2d7-bf3b326af2df)

No idea what to expect to happen after this delay, it's been about two hours and every few minutes it feels like something's about to happen, but nothing does.

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
