### ISSUE TITLE
Allow to dismiss firmware update notifications.

### ISSUE THREAD

**Issue by Transisto** [trezor/trezor-suite#11326]
![image](https://github.com/trezor/trezor-suite/assets/388716/e17f3145-c089-4dd1-8e10-8bb81c1869a1)

Couldn't care less about these "features" and I feel forced to change my firmware just to get rid of this top popup.

**Comment by Hannsek** [comment]
That is a good thing. You should always have you firmware updated.

**Comment by Transisto** [comment]
I disagree, it turn your dev keys into an even bigger target to get your
users to update over every mundane altcoin UI update. If your keys get
compromised you don't want a high % of users to pawned themselves
semi-automatically in the first 8h.

**Comment by Hannsek** [comment]
If you don't want to be bothered by altcoin updates you can use btc-only firmware.
