### ISSUE TITLE
UI: Device language settings BETA

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#11336]
- Related Issue (Connect): [#10099](https://github.com/trezor/trezor-suite/issues/10099)
- Successor full scale issue: https://github.com/trezor/trezor-suite/issues/11234

- Logic specification
    - FW translations will be shipped in BETA version together with Suite 24.2 release. In that case there will be no logic yet, we will only allow users to set their FW language manually in Device settings and it will be marked as beta. When user will change the language in these settings, device will prompt them to confirm the change.
    - FW language in Settings:
        - Please add a `Device language` select menu into `Settings > Device > Firmware`  as third option
        - It should act the same way as the Language setting in `Settings > Application > Localization`.
            - There will be no language categories for now, as FW will only be localized into official languages.
            - There will be no `System` option.
            - All other languages than English will be marked as (beta), e.g. Deutsch (beta)

"*"
![Image](https://github.com/trezor/trezor-suite/assets/88533514/7f9f7ae1-c247-4a19-bd6e-443a3f5cb3a6)

- Design in Settings
    
 

![Image](https://github.com/trezor/trezor-suite/assets/88533514/04a09b32-3e12-4524-97d8-c3deb174b0dc)

**Comment by bosomt** [comment]
**QA OK**


![Image](https://github.com/trezor/trezor-suite/assets/31506317/d098c53a-7dc6-4da5-af85-a2990d7b9604)



**Info:**
 - Suite version: desktop 24.3.1 (d03de8bf472a7b59b644083604d011af3b70f413)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
