### ISSUE TITLE
Sweep / Redeem private key

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#1133]
Do we even want this?

**Comment by HeroHann** [comment]
Why not? Wouldn't this bring more people to Trezor / it would be easier to switch.

Best case: All Coins would be sweept. So even multi coin wallets should be transferrable to the Trezor.

**Comment by hynek-jina** [comment]
I’m closing this issue for now until the product is specified.
[Current private specification](https://www.notion.so/satoshilabs/Sweep-Redeem-private-key-c827d8b85ced43018aa34fb07d0ffdbe)
