### ISSUE TITLE
Hide unrecognized tokens in sell and exchange

### ISSUE THREAD

**Issue by FreeWall** [trezor/trezor-suite#11341]
In Trade section we still show tokens are unrecognized by coingecko.
Users might have several scamy tokens with same name on the account and no way to know which are scamy ones.

Example contracts:
```
0x32819d807Af179EB93f510191607Dba58d27152f
0x6d995217db76437ea053770dDaB27aA90a298bCa
0xC377cF8Ea22eBc196D9C376B1cc952B633bfBC81
0xB9b207eF957fB679CaAE55C0E3ae9cB404503cd9
0x2B90d84FE76c33f3Dc1ADAf645D6f6202B4b853A
```

![image](https://github.com/trezor/trezor-suite/assets/12121074/fbac5087-cd03-4a43-b2dc-5d912a838a36)

**Expected behavior**
Since we’re unable to trade those tokens anyway, we need to hide them from exchange and sell forms.

**Comment by bosomt** [comment]
Not sure if this is expected result

recognized tokens in account 



![Image](https://github.com/trezor/trezor-suite/assets/31506317/39eaabce-6d86-43e0-b6d8-167f441224d0)

but im allowed to sell only one



![Image](https://github.com/trezor/trezor-suite/assets/31506317/93d5beb3-e601-42e7-827a-0f837ee48346)


**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by FreeWall** [comment]
I checked and I think it is expected result.

- USDC -  :heavy_check_mark: 
- TUSD - from invity api, no provider is currently supporting TUSD for sell (some of them support TUSD for exchange though)
- USDP - invity api does not support this coin at all
- USDT - you have 0 balance so it won't show
