### ISSUE TITLE
Two or more outputs in the same received transaction

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#1134]
Should we show them as two/more separate values, should we show them as aggregated amount?

Ideally, both where user could expand/collapse the amount.

**Comment by szymonlesisz** [comment]
already solved
![Screenshot 2020-05-19 at 11 45 39](https://user-images.githubusercontent.com/3435913/82311664-4fd2a280-99c6-11ea-9093-499afae0642e.png)
