### ISSUE TITLE
ETH - Gas price is reported as 0 when exchange tab custom fee

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11359]
**Describe the bug**
Info under maximum fee is not updated when changing values in custom fee form. Both Gas limit and Gas price

**Info:**

-   Suite Version: 24.2.4

**Screenshots**

https://github.com/trezor/trezor-suite/assets/33235762/407751e9-5c4e-46a7-939a-83c315776aa0

**Comment by STew790** [comment]
**QA OK**

The layout changed a bit so the Gas Limit and Price are only shown in the "Custom" fields. It also calculates the whole price correctly when I change it.

![image](https://github.com/trezor/trezor-suite/assets/48477147/ea39fa42-9215-4684-826f-0ea7b4aaa719)

**Info:**
 - Suite version: desktop 24.4.0 (a0556d2e0c123ad3080ce3df4accaa47e9d39021)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.32
