### ISSUE TITLE
Invity sell form missing token balance

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11358]
**Describe the bug**
Would be nice to see token balance in Sell form

**Screenshots**
Missing token balance in sell form
![Screenshot 2024-02-27 at 18 12 24](https://github.com/trezor/trezor-suite/assets/33235762/907e1eaf-e1e1-46fe-93a3-b36e91a70e8b)
Available in exchange form
![Screenshot 2024-02-27 at 18 12 17](https://github.com/trezor/trezor-suite/assets/33235762/4d37f72d-c3e0-4232-8fea-e388f33aeb85)

**Comment by tomasklim** [comment]
Looks resolved

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
