### ISSUE TITLE
Empower/Invity/Exchange does not display eth balance correctly

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11353]
https://github.com/trezor/trezor-suite/assets/152851523/392c4fbc-9e10-46d1-b7dc-06d851c97cd8

**Comment by MiroslavProchazka** [comment]
Fixed in 24.9.1
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/b3bf116b-a304-4401-8156-897d285ad105">

**Comment by bosomt** [comment]
**QA OK**

Sell and Exchange fractions and amounts works as expected


**Info:**
 - Suite version: web 24.9.0 (b2ea3830e71db4f0e32a202fcaff2959b952a02a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32
