### ISSUE TITLE
Empower/Invity/Trade section - portion selectors does not work

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11352]
https://github.com/trezor/trezor-suite/assets/152851523/69423231-69cc-4e2b-b04a-200959a65c5d

**Comment by MiroslavProchazka** [comment]
Fixed in 24.8.1

**Comment by bosomt** [comment]
**QA OK**

tested on ETH to BTC exchange portion buttons

**Info:**
 - Suite version: desktop 24.8.2 (96e583538c6a30e010a81346d1251f3246cb1def)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.32
