### ISSUE TITLE
Empower/Invity/Exchange - currency USDT is not supported

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11354]
https://github.com/trezor/trezor-suite/assets/152851523/e52c4737-45d5-4d04-af8b-73bc55bbc0bf

**Comment by MiroslavProchazka** [comment]
I do not  have USDT, so I tested it on USDC and it is working on 24.8.1. 
Please try also with USDT

**Comment by bosomt** [comment]
**QA Ok**

- i dont have enough usdt to sell it
- but i can enter any amount and proceed with sellin
- overall no not supported info :)


![Image](https://github.com/user-attachments/assets/74e444ef-1c39-4160-931c-6143fd7ada26)




![Image](https://github.com/user-attachments/assets/fa16647a-ca15-46c3-978d-a8fd19769e91)



**Info:**
 - Suite version: web 24.9.0 (b2ea3830e71db4f0e32a202fcaff2959b952a02a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32
