### ISSUE TITLE
Atom components refactor to accept <Translation />

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#11369]
Some widely used components (e.g. Button or Alert), that were created before we adopted translations are accepting only `string` as a parameter. Changing this to ReactNode would allow us to use `Translation`, also styled text or even `DiscreetText`. 

Do: 
- [x] identify atom components that should be refactored and confirm the scope
- [x] make ReactNode work there
- [x] check all usages and change usage of `useTranslate` to `Translation`

**Comment by vytick** [comment]
For @trezor/qa:

This PR might have technically broken any text containing component, but should not change any functionality. I have tested it myself, hopefully I have not missed anything 🤞. Testing this issue is mostly sanity check of the whole app.

**Comment by bosomt** [comment]
**QA OK**

- haven't found any broken text in app

- 24.4.0 103 0072d913
- Android 14
