### ISSUE TITLE
Recent Firmware Upgrade Shows $0 Amount beside Ethereum Account

### ISSUE THREAD

**Issue by Satoshi-Nakamoto888** [trezor/trezor-suite#11363]
Recent Firmware Upgrade Shows $0 Amount beside Ethereum Account in Trezor Suite

I had an X amount beside Ethereum prior to the upgrade. After the upgrade it shows $0. Please FIX ASAP

**Comment by sime** [comment]
Thanks for the report, a fix is in progress.

If you can't wait for the fix, you can install the previous version of Trezor Suite. https://github.com/trezor/trezor-suite/releases/tag/v24.1.2

**Comment by Satoshi-Nakamoto888** [comment]
how much more longer for the fix?

and how to revert back to the old firmware?

**Comment by Hannsek** [comment]
This is not about firmware but about Trezor Suite, the desktop app.
