### ISSUE TITLE
Strange artifact during app start

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11377]
**Describe the bug**
Strange artifact during app start.
Does not happen on Android / only splashsceen logo blinks/

**Info:**

-   Mobile Suite Version: 24.3.1 (15) a20b6c3
-   OS: latest iOS, iPhone 11

**How to reproduce**
Start app

**Screenshots**
<img width="430" alt="Screenshot 2024-02-28 at 20 56 36" src="https://github.com/trezor/trezor-suite/assets/31506317/2f09ba35-9012-46d3-8882-392188e8bd95">

https://github.com/trezor/trezor-suite/assets/31506317/4d003732-2f81-4a01-adfe-9bb9ce97ca7c

**Comment by juriczech** [comment]
Might be also related to this google report. 

![image](https://github.com/trezor/trezor-suite/assets/36101761/af07a997-3d8d-4acb-854f-e5d03039666d)

**Comment by bosomt** [comment]
**QA OK**

with current build cc7d18e i done see any artifacts :)

**Comment by evgenysl** [comment]
Artifact appears in iOS app.

24.3.1. Last commit hash: cc7d18e
iOS: 17.0

https://github.com/trezor/trezor-suite/assets/63164324/a6fa87f8-e8ff-4959-aea8-0536eec8c60d

**Comment by mnuky** [comment]
@vytick - the issue is assigned to you and marked as in Progress - are you working on it?

**Comment by bosomt** [comment]
afaik its already fixed for some time :)
