### ISSUE TITLE
Trezor monitoring your activity?

### ISSUE THREAD

**Issue by GREG377** [trezor/trezor-suite#11379]
Hi 
Around month ago I install Trezor Suite.
Few days after installing Trezor Suite on my MacBook pro I notice an icon from Trezor asking me to click on "yes" icon, there was no option for "no", saying so Tresor could monitor my Trezor activities for future updates.
Was this a scam or legit from Trezor?
Thank you for your time
Greg

 **Describe the bug**

**Info:**

-   Remembered Wallet: yes/no
-   Suite Version: app/web, commit
-   Browser: name, version
-   Browser Installation Method: snap, flatpak, app store, windows store, downloaded installer, etc.
-   OS: name, version
-   Bridge: version
-   Firmware Version: model, version/commit

**How to reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Hannsek** [comment]
Can you provide us with screenshots of the dialog?

**Comment by GREG377** [comment]
Unfortunately I do not have it.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by sime** [comment]
Hi @GREG377 what you describe doesn't sound like a Trezor Suite prompt. In future, it's best to reach our support team: https://trezor.io/support

GitHub is a developer portal, not a support channel.

**Comment by GREG377** [comment]
Hi
Thanks for your time.
The link you give me to trezor do not have the option to contact any body (human) from trezor, unless Im missing something.
Please let me know.
Thx
Greg

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by sime** [comment]
@GREG377 Follow the prompts in the chat window. Support will get back to you when they are available (via E-Mail).
