### ISSUE TITLE
Accounts tab - search does not work correctly with special chars

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#11383]
**Describe the bug:**
Search in accounts tab does not correctly filter accounts with special chars `#`

**Info:**

- Suite Version: 24.8.1

**How to reproduce**

- try to filter accounts using `#` or other special characters (you have to enable labeling to be able to add other chars)

**Expected behavior**
It would find my account whatever name it has

**Screenshots**
<img width="273" alt="Screenshot 2024-09-08 at 9 57 14" src="https://github.com/user-attachments/assets/e8a556ad-cd5f-480f-9ffe-6ac544b39e34">
<img width="286" alt="Screenshot 2024-09-08 at 9 57 04" src="https://github.com/user-attachments/assets/a00802e9-f663-41c5-a9b5-b83e46c62a14">
<img width="293" alt="Screenshot 2024-09-08 at 9 56 48" src="https://github.com/user-attachments/assets/1d2696ba-aad6-4c42-97de-77342dddbc1d">
<img width="286" alt="Screenshot 2024-09-08 at 9 56 42" src="https://github.com/user-attachments/assets/6618fc46-95c2-4076-bae1-f1b6ffeb1697">

https://github.com/trezor/trezor-suite/assets/858321/ecb6c2fc-6cfb-49bf-b773-d65834826477

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.0 (96159d214b65b6c0c5315f09f571e52fbab8a1be)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Transport: BridgeTransport 2.0.33
