### ISSUE TITLE
Empower/Add scroll bar to a replace btc transaction modal

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11385]
With the new design, it is hard to find out that there is a second part of the btc tx detail modal, since there is no scrollbar. 
Please adjust the design or add a scrollbar there so it is more user-friendly. 

[Screencast from 2024-02-28 21-01-22.webm](https://github.com/trezor/trezor-suite/assets/152851523/87694f2a-ae7f-4ec7-b0d9-34b4e3762b16)

![image (7)](https://github.com/trezor/trezor-suite/assets/152851523/a259849e-ead1-45e4-b3db-920b5751f471)

**Comment by bosomt** [comment]
@MiroslavProchazka please confirm that this is expected look 🙏 

https://github.com/trezor/trezor-suite/assets/31506317/a3bdda04-fee7-4973-8482-b3d7599f01f1





**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by Hermez-cz** [comment]
@bosomt it's ok as a quick fix. We'll propose better design soon-ish, where we'll avoid unneccesary scrolling.
