### ISSUE TITLE
Biometrics not working

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#11380]
Biometrics seems to be broken on latest build. 

https://github.com/trezor/trezor-suite/assets/36101761/6de80cd8-fd6d-47f7-bd62-933f7a4c27cb

**Comment by STew790** [comment]
**QA OK**
Same as here https://github.com/trezor/trezor-suite/issues/10647#issuecomment-1976659625 biometrics working fine.

iOS 24.3.1 (https://github.com/trezor/trezor-suite/commit/cc7d18ed3f02caf46636bf68ebefd6ac48cac287)
