### ISSUE TITLE
Passphrase recognized on Web but results in 'Empty Wallet' on AppImage App

### ISSUE THREAD

**Issue by pluja** [trezor/trezor-suite#11389]
**Describe the bug**

When I attempt to open my Trezor T wallet using the latest desktop application, it prompts me for the passphrase (hidden wallet). I enter the passphrase directly from my Trezor device, only to be met with an "Empty Wallet" message. I re-enter the passphrase (confirm empty wallet prompt), but all the addresses still appear empty. Despite multiple attempts and ensuring the passphrase is correct, the outcome remains the same each time.

However, when I switch to using the Trezor Suite web application and follow the same steps, my wallet displays correctly without any issues.

This leads me to believe there might be an issue with how the desktop AppImage application is handling the passphrase, though I'm not entirely certain what the problem is. If any debug information is required, I'm willing to assist in resolving this issue!

**Info:**

-   Remembered Wallet: yes
-   Suite Version: app/web
-   Browser: Firefox, latest
-   Browser Installation Method: AppImage.
-   OS: Fedora Linux 39
-   Bridge: trezord version 2.0.27
-   Firmware Version: T, [version/commit](https://github.com/trezor/trezor-firmware/blob/42e9ed0e09033d474dee1a560fe5870646fa440e/core/CHANGELOG.T2T1.md)

**How to reproduce**

Steps to replicate the issue:

1. Connect the Trezor T device.
2. Launch the Trezor Suite AppImage.
3. Input the passphrase on the Trezor to access the hidden wallet.
4. Receive a warning indicating the wallet is empty.
5. Confirm the passphrase once more.
6. Notice the wallet remains empty despite the confirmation.

Following the same steps (1 to 3) on the Trezor web interface leads to:

4. The wallet displays correctly without any issues.

**Expected behavior**
Show my hidden wallet with my coins, discovering addresses correctly.

**Additional context**
Was working fine on previous version, I updated, and now it can't find it anymore (on desktop).

**Comment by MiroslavProchazka** [comment]
@trezor/qa Can you please test this? Thx

**Comment by MiroslavProchazka** [comment]
I just tested and it works for me - Suite 24.2.4

**Comment by STew790** [comment]
Same here, I just tried a couple of passphrases and they all work for me. Either in app or on Web. Let us know if this persists, please. 

**Info:**
 - Suite version: desktop 24.2.4 (748176286ae231aae44c83981a62b174b7605e1a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.2.4 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by pluja** [comment]
I cleaned up everything from the app in my machine, and it worked, nothing changed other than removing cache and config folders. So I guess it was a weird bug. 

I can also note that I had updated the app from the older version with an "Update" pop-up it showed. I also verified the checksum, it was correct. 

Can't replicate again now after cleaning.
