### ISSUE TITLE
Mac app top bar improvement

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#11399]
We have a fixed top bar on Mac now, which is sub-optimal.

Please incorporate the top bar into the app for a seamless design experience.
Mind resizing of the menu from #11400 

Screenshots:
Mac:
<img width="1443" alt="Screenshot 2024-05-28 at 07 52 49" src="https://github.com/trezor/trezor-suite/assets/858321/9c8ca4e0-1b26-4100-92a5-a10f077f8785">

Windows:
<img width="936" alt="Screenshot 2024-05-28 at 07 53 31" src="https://github.com/trezor/trezor-suite/assets/858321/bd6a41b3-3dc9-4e9b-b54f-56f4cc31e33c">

Design: [Figma link](https://www.figma.com/file/KOTm1scRKiHBRTvMgEFhe6/OS-Specifics?type=design&node-id=4002%3A7181&mode=dev&t=NKffSnRun7Y4dhh8-1)

_In the design, there are also the browser and Windows options shown (Linux should keep its current top bad similarly as Windows). Those should basically stay as they are._

**Comment by bosomt** [comment]
**QA OK**

https://www.notion.so/satoshilabs/Update-bar-traffic-lights-on-mac-d0f7e47e0a964469b745ebb9e526ed53

**Info:**
 - Suite version: desktop 24.8.0 (0ecb6c9312d413c455a98de8906f258d73d8153a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.8.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: BridgeTransport 2.0.33
