### ISSUE TITLE
Tokens balance in the left nav accounts menu

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#11398]
Currently, we're not showing tokens balance in the left nav menu account items (only main net balance is shown on every network).

Please update the menu items of networks having tokens according to the new design to include token balance and staked balance.

Together with that please improve the visual of tabs in every account detail to be consistent with the new menu item designs (pill buttons instead of tabs). _Note: we will further reorder the header items together with graph updates. For now, keep the order as is, it is also shown like that in the Pills design linked below._

Design:

- Pills + left nav preview: [Figma link](https://www.figma.com/file/DByE5e8nkNAa46J8bc2QTt/Main-flow?type=design&node-id=30%3A23221&mode=design&t=BrLHCbRo6MaSftAR-1)
- Components: [Figma link](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A31385&mode=design&t=Q3oUNw5KDo2cnSUG-1)

Details:

- Accounts list in the main nav menu
  - At every account, only show the items that are really present
    - BTC? Show just account, like up until now (no tokens or staking exist)
    - ETH/EVM/...?
      - Mainnet: Show always, even if 0 value
      - Staking: Show only on accounts where something is or has been staked
      - Tokens: Show only on accounts where there's >0 recognized tokens (show only count and value of recognized tokens, disregard unrecognized)
  - Hovering over an account with only mainnet remains unchanged, clicking on it as well (hover = grey background; click = white highlight with a shadow + opens Overview of the account (light mode)) -> see Components design for details in both light and dark mode
  - When hovering anywhere over the whole account frame having 2 or 3 items shown, show an outline around it as per design
    - Inside it, highlight the singular items on hover by the grey background (the whole group remains outlined)
    - On click on the singular item within, highlight it by white background with shadow and open the appropriate tab (the group remains outlined); when switching tabs, switch the highlighted items accordingly. When the Details tab is selected, highlight the mainnet coin, as those are it's details (we'll get rid of this once Details will become something smaller than a tab, but for now, hold on)
- Tabs on the account detail page
  - Leave the tabs basically where they are, just change their looks into pill buttons, where the selected one remains highlighted, align them according to their size
  - Switch tabs together with switching the main menu items within the whole account menu item

**Comment by MiroslavProchazka** [comment]
We will display sum of for Ethereum coins, tokens and staking in Portfolio balance on Dashboard.

**Comment by MiroslavProchazka** [comment]
Please get rid of the Staking value and fiat rate on the Overview tab in Eth account.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.4.0 (5231fe0e7dd0272a8218d1ebf04e44710d663859)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
