### ISSUE TITLE
Unstaking: Instant unstake forecasting

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#11402]
## User Story
As a staker
I want to unstake my Ethereum
So that I can buy NTFs

## Acceptance Criteria
Given I see the 'Unstake' modal
When I click on 'Other amount'
Then I should see 'Approximate ETH available instantly: 1.75 ETH' 

Given I see 'Approximate ETH available instantly: 1.75 ETH'
When I hover on the (i) icon
Then I should see 'Liquidity of the staking pool can allow for instant unstake of some funds. Remaining funds will follow the unstaking period'

## [Screens](https://www.figma.com/file/0Kz3w6WDlvQm62RjOm87na/Staking?type=design&node-id=4304-21002&mode=design&t=52EcRrIDbhO337OD-4)

![image](https://github.com/trezor/trezor-suite/assets/216917/7526e6ac-db64-457d-af7c-125ca38c3131)

**Comment by tomasklim** [comment]
Waiting for https://github.com/trezor/blockbook/issues/1084

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.11.0 (3e2480c61fd43545db72544d59b7154b01abb5d7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Transport: WebUsbTransport
