### ISSUE TITLE
Staking: Dynamic APY

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#11407]
## User story
As a user
I want to know the APY of staking
So that I can gauge the return of my investment

## Acceptance criteria
Given I am on the staking tab
When I have no ETH staked
Then I should see the current APY

Given I am on the staking tab
When I have ETH staked
Then I should see 'Annual Percentage Yield' 
And I should see the current APY

## Screens

![apy-welcome-screen](https://github.com/trezor/trezor-suite/assets/216917/e51b7338-0b23-4161-b3b1-e06be69a319b)
<img width="1149" alt="Screenshot 2024-03-01 at 17 20 13" src="https://github.com/trezor/trezor-suite/assets/216917/60303ae7-3fb2-4af0-944d-0181dea74e30">

**Comment by sime** [comment]
Outstanding issues:
* Staging [/stats](https://eth-api-b2c-stage.everstake.one/api/v1/stats) endpoint used in production
* Whitelisting of trezor subdomains: suite.corp.sldev.cz, suite.trezor.io and staging-suite.trezor.io

**Comment by bosomt** [comment]
**QA OK**

`Earn 1.81% APY* by staking your Ethereum with Trezor.`

**Info:**
 - Suite version: web 24.4.0 (3a5dee13187d9decb0592c009a9c9e1d5704a7bc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
