### ISSUE TITLE
Everstake server error even ETH or ETH testnet not enabled

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11413]
**Describe the bug**

When i enable non ETH coin testnet account i get this error
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://eth-api-b2c-stage.everstake.one/api/v1/stats. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘’).
```

**Steps to reproduce:**
1. Enable any testnet coin
2. Observe browser console error
3. c

**Info:**
 - Suite version: web 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.6.5 regular (revision a784c4046e79ae138f9a7a9c5e97d2f6771140eb)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="1438" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/36d4c744-4956-43ff-becd-6506edd4c946">

**Comment by sime** [comment]
Should be resolved via https://github.com/trezor/trezor-suite/pull/11422

**Comment by sime** [comment]
@bosomt Can you re-test.

**Comment by bosomt** [comment]
retested:

dev version: 
- does not happen when ethereum is disabled
- as soon i enable ethereum i see this error
<img width="597" alt="Screenshot 2024-03-08 at 9 19 36" src="https://github.com/trezor/trezor-suite/assets/31506317/a309d082-3b31-48f5-98d3-351fe7a16fab">

release candidate:
 - i see same results
 - does not happen when ethereum is disabled
 - as soon i enable ethereum i see this error

**Info:**
 - Suite version: web 24.4.0 (f141bd42ae7b3ad84598fe240429238dbc74ff57)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Info:**
 - Suite version: web 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.4.0 (3a5dee13187d9decb0592c009a9c9e1d5704a7bc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
