### ISSUE TITLE
Staking on testnets show really fiat value sometimes

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#11416]
**Describe the bug**
We treat e. g. THOL with real ETH value

1. Start staking
1. See total stake pending

**Expected behavior**
Should be zero value

**Screenshots**
![Screenshot 2024-02-29 at 12 50 40 PM](https://github.com/trezor/trezor-suite/assets/66002635/4e69f16a-bedb-4ee1-953e-199a1f78e19e)

**Comment by tomasklim** [comment]
It is intended for testing
