### ISSUE TITLE
Suite reports 1.1.1970 as last day of update before it fetches new fiat data from servers

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11415]
**Describe the bug**
Suite reports 1.1.1970 as last day of update before it fetches new data from servers

**Steps to reproduce:**
1. Enable Solana
2. observe `Trade` `Price updated` in `Overview` before discovery finish

**Info:**
 - Suite version: web 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.6.5 regular (revision a784c4046e79ae138f9a7a9c5e97d2f6771140eb)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="506" alt="Screenshot 2024-03-03 at 21 19 52" src="https://github.com/trezor/trezor-suite/assets/31506317/a95dbd78-bd42-4e3f-988c-20213a16e929">

**Comment by tomasklim** [comment]
Already reported https://github.com/trezor/trezor-suite/issues/10435
