### ISSUE TITLE
Hide staking stats if the account isn't staking

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#11417]
**Describe the bug**
We show staking stats next to balance even if I'm not staking at the moment.

**How to reproduce**

1. Go to any ETH account that you don't stake with
1. See staking stats (staked amount)

**Expected behavior**
Should be hidden, not zero.

**Screenshots**
![Screenshot 2024-02-29 at 12 38 25 PM](https://github.com/trezor/trezor-suite/assets/66002635/917feeee-ac46-4803-b79d-184000525487)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.4.0 (fdd09c1115e32052c305e4f58624ab99c43d0149)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
