### ISSUE TITLE
It is not possible to do exchange from USDT@MATIC to USDT@ETH

### ISSUE THREAD

**Issue by FreeWall** [trezor/trezor-suite#11418]
**Describe the bug**
It seems that the detection of the same symbol in the from and to does not respect different platforms.

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/12121074/27776f57-12e6-40b1-9797-3a277404f86b)

**Comment by bosomt** [comment]
**QA OK**

Minor graphic issues reported here:
https://satoshilabs.slack.com/archives/C04DD84P4A1/p1709745854675249
https://satoshilabs.slack.com/archives/C04DD84P4A1/p1709746645795089

![Image](https://github.com/trezor/trezor-suite/assets/31506317/c3e4fc7b-783c-4c99-9f04-4331423b4e19)

**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
