### ISSUE TITLE
Accounts tab - network filter should not reset on wallet change

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#11410]
**Description:**
Currently, Suite resets the networks accounts filter on every Wallet switch (even when "switching" back to the aready selected wallet).

Please change the behavior, so the filtered networks stays selected even if the user switches wallets until the instance of the app is running (or ofc until the user deselects it or selects another instead).

You should save it into redux but not into index db

**Info:**

Suite Version: 24.8.1

**How to reproduce**

Check video or ⬇️ 

- remember two different wallets (e.g. standard and 1 hidden passphrase wallet)
- be on standard wallet and select 1 network in filter
- switch to second wallet
- filter resets

**Screenshots**
<img width="292" alt="Screenshot 2024-09-08 at 9 55 33" src="https://github.com/user-attachments/assets/e7ad3016-54d8-42c2-91f7-dc851f75267b">

https://github.com/user-attachments/assets/3a9ff38c-fb83-4b5f-823e-199c22f587c3

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.12.0 (63ca256b226cc9d6a9e411424f380c7317810943)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport
