### ISSUE TITLE
Unable to sign transactions with trezor connect via trezor/connect-web

### ISSUE THREAD

**Issue by logansease** [trezor/trezor-suite#11437]
As of the trezor-web 9.2.0 release yesterday our integration with trezor to sign bitcoin multisig transaction is broken. During signing we get an 'unknown error' back from the Trezor.signTransaction() method. 

**Info:**

-   Remembered Wallet: no
-   Suite Version: web 9.2.0 -> 9.0.4
-   Browser: chrome 122.0.6261.94
-   Browser Installation Method: download
-   OS: Mac OSX 13.5.2
-   Bridge: version 2.0.27
-   Firmware Version: Trezor Model One, most recent

**How to reproduce**

Reproducible in connect explorer

1. Go to "https://trezor.github.io/trezor-suite/connect-explorer/#/method/signTransaction-p2sh"
2. Click on Bitcoin -> Sign Transaction
3. Add inputs:
```
[{"address_n":[49,1,1,0,0],"prev_index":0,"prev_hash":"1b3626080ed19736a9c41dfe6375ee3b6f54128463995aa3390e80ac5af50245","amount":"1920761","script_type":"SPENDP2SHWITNESS","multisig":{"pubkeys":[{"address_n":[0,0],"node":{"version":76067358,"depth":3,"child_num":1,"fingerprint":31537651,"chain_code":"b6901d997f8149b3ab32ef83632c7aac73de63757175b02836163f3e1f901724","public_key":"0211f3c30d80d95ddf622c902af6bbe372cedd8350406ee0b68b2e6e2b4ac97f08"}},{"address_n":[0,0],"node":{"version":76067358,"depth":3,"child_num":5565,"fingerprint":2845417111,"chain_code":"dc3f5d4a9c02dbb1d0571dc5e16abad088a75d36b1c6dd100bffe93ebd9dcb90","public_key":"02a006b1ede51fd09943e9ac09d9c07667796f9fb6f64ec3c53e437de1d36ac981"}},{"address_n":[0,0],"node":{"version":76067358,"depth":3,"child_num":1,"fingerprint":837819873,"chain_code":"b40b92d9a3dc41245adbb34b55881f2eb1cb15b0b7a2c0424c498bd1dae79dcb","public_key":"0291abb363b0feaf232065856891614892d62d1c67027c62c082286d4e234b0087"}}],"signatures":[],"m":2}}]
```

Outputs:
```
[{"address":"2N3t5S1BJMJJJHqX73zguHt5uL78oHMEp2H","amount":1920399,"script_type":"PAYTOADDRESS"}]
```
Action Not completed, "unexpected error"
Trezor screen stuck at "Loading Transaction"

**Expected behavior**
The method should return a signature

**Screenshots**
<img width="1479" alt="Screenshot 2024-03-04 at 3 30 12 PM" src="https://github.com/trezor/trezor-suite/assets/1085547/cfd88248-598f-4bfa-8008-ecba5bf5fdbd">
<img width="1507" alt="Screenshot 2024-03-04 at 3 21 37 PM" src="https://github.com/trezor/trezor-suite/assets/1085547/b1daad22-1646-4c8e-8c1c-adb720f5a175">

**Comment by logansease** [comment]
I have a more basic example taken from the example in the connect-explorer dashboard, which produces the same unexpected error results described above.

inputs:
```
[
    {
      "address_n": [
        2147483692,
        2147483649,
        2147483648,
        1,
        0
      ],
      "amount": "1234567",
      "prev_index": 0,
      "prev_hash": "20912f98ea3ed849042efed0fdac8cb4fc301961c5988cba56902d8ffb61c337"
    }
  ]
  ```
  
  outs:
  ```
  [
    {
      "address": "2Mwb91LuJPiJEHDxRemFpDbVFHPFpiPiUhM",
      "amount": "12300000",
      "script_type": "PAYTOADDRESS"
    }
  ]
  ```

**Comment by jlopp** [comment]
Just wanted to note that this is a critical issue for Casa because it means all of our clients are currently unable to sign transactions with Trezor One devices.

**Comment by beckySchmitty** [comment]
these failed tests from the recent 9.2.0 release may point towards the source of the issue?
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/6283489380
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/6283489419
<img width="1312" alt="Screenshot 2024-03-04 at 9 32 05 PM" src="https://github.com/trezor/trezor-suite/assets/69874992/7eb35825-10d5-4672-91aa-17f6780e8eda">
<img width="1300" alt="Screenshot 2024-03-04 at 9 37 58 PM" src="https://github.com/trezor/trezor-suite/assets/69874992/034c0ac2-4a6f-4211-a13e-7c972c33adf7">

**Comment by mroz22** [comment]
fix should be online within an hour.

**Comment by Hannsek** [comment]
Hi, thanks for reporting, we are working on fixing this. Sorry for inconvenience.

I am wondering if we have your email addresses from Connect code so we can contact you with upcoming releases before putting them into production. Feel free to send me the email addresses to jan.setina@satoshilabs.com.

**Comment by logansease** [comment]
Thank you for addressing this quickly!

**Comment by logansease** [comment]
Quick question / thought. Our web package is locked to a specific version of connect-web in its package file and we didn’t update it, yet this new code was pulled in and “hotloaded”. This is a bit of a security vulnerability. 
I believe this is because code within the package loads from the url ‘https://connect.trezor.io/9/…’ instead of ‘https://connect.trezor.io/9.xx/…’?

is it possible in the future, the connect web package could respect the version supplied? Should I create a ticket for this?

**Comment by mroz22** [comment]
yes, this does the trick

```
 TrezorConnect.init({ connectSrc: 'https://connect.trezor.io/9.x.y/' }) 
```

for a conservative app this is probably better way to go. "hot load" mode is useful mostly for crazy shitcoins with constant additions

**Comment by bosomt** [comment]
@logansease deployed to production, please confirm that it works as expected now 🙏

**Comment by logansease** [comment]
yes. thank you!
