### ISSUE TITLE
Coinmarket: Use partner's brandName for non-legal purposes and partner's companyName for the legal ones

### ISSUE THREAD

**Issue by LukasRada** [trezor/trezor-suite#11433]
Current state: We use company name for legal and non-legal purposes in Trezor Suite.

New State: We need to distinguish between brand and company name. Brand name will be used for non-legal purposes, whereas company name will be used for the legal ones.

![image](https://github.com/trezor/trezor-suite/assets/7394177/0b7554e7-5364-46dc-bd52-c4046d603f22)
![image](https://github.com/trezor/trezor-suite/assets/7394177/49fdf8ac-ef8e-431a-a6c8-3d00b075ba4a)

**Comment by peter-sanderson** [comment]
Resolves: https://github.com/trezor/trezor-suite/issues/11433 ?

**Comment by bosomt** [comment]
**QA OK**

looks like expected



![Image](https://github.com/trezor/trezor-suite/assets/31506317/c9401bd9-473c-4dcd-9b28-41a8df7dbaec)




**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33
