### ISSUE TITLE
Staking: Stake buttons active when device is disconnected

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11438]
**Describe the bug**

stake/unstake is available even device is disconnected
you can choose how much you want to stake/unstake
till you get to this dialogue, maybe we can consider disabling button when wallet is remembered but device is not connected :pray

**Steps to reproduce:**
1. Stake funds
2. Remember wallet
3. Disconnect device
4. Try to unstake funds or stake more funds

**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

<img width="833" alt="Screenshot 2024-03-05 at 10 04 20" src="https://github.com/trezor/trezor-suite/assets/31506317/72aaa72e-0b24-4ef2-9d41-704549afbc43">

**Comment by bosomt** [comment]
Not sure


`Stake more` and `Unstake` buttons are still active even device is disconnected
But `Continue` and `Unstake` buttons are not active.
@sime  please confirm that its expected bahavior. 

![Image](https://github.com/trezor/trezor-suite/assets/31506317/36e1e9fe-8365-48db-9b13-cb6d89a63ca3)

![Image](https://github.com/trezor/trezor-suite/assets/31506317/74380b94-b6d5-4442-a500-7bb58dc7f5c6)



![Image](https://github.com/trezor/trezor-suite/assets/31506317/a869bd45-1e78-468e-a4dc-95e61a870950)


**Info:**
 - Suite version: web 24.4.0 (fdd09c1115e32052c305e4f58624ab99c43d0149)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by sime** [comment]
@bosomt Behaviour works for me.

Staking modal plan is to have return on [investment calculator](https://github.com/trezor/trezor-suite/issues/9258), making that available for non-plugged into Trezor's is handy.

Unstake can project what can be unstaked.
