### ISSUE TITLE
Review and send transaction

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1143]
**[Zeplin](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa1bf26b256c1a29031104)**

**Comment by wendys-cats** [comment]
@vladimirvolek @matejzak quick question - there seems to be a functionality in Confirm transaction modal (according to Zeplin) for multiple transactions that is not in Suite, a check of some sorts and an option to highlight one of the transactions. Had this feature been scratched from Suite?

**Comment by bosomt** [comment]
im missing FIAT value in confirm transaction.
is correct behavior ? i see it in zepelin

![image](https://user-images.githubusercontent.com/31506317/78893034-cd6fce00-7a6a-11ea-8b2e-a931bed1f139.png)
