### ISSUE TITLE
Do not fallback on CDN if fiat rate for token is not on Blockbook

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#11447]
Blockbook has all token rates that are in Coingecko (and updates the list once a day). If they are not in Blockbook, they are not in Coingecko

**Comment by AdamSchinzel** [comment]
I think we can apply this approach for any call for fiat rates where the backend is Blockbook based. So for everything except Solana, Cardana and Ripple right? Plus Bitcoin but only if platform is desktop because you can have there custom electrum backend where `blockbookService` comes in place.

**Comment by matejkriz** [comment]
Yes, this applies only for networks that have blockbook. So everything except SOL, ADA, XRP.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 24.3.3 (1b6b0c29ca5982930ac65e23be9014d76d6b8478)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.3 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
