### ISSUE TITLE
App crashes on graph

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#11448]
Steps to reproduce:
- Load wallet with Cardano and get fiat rates error (try different time scopes if it doesn't fail)
- Click somewhere in graph area
- See app crash

Suite Lite 24.1.1 Android

**Expected behavior:**
- App does not crash 
- Try again button do try again
(fixing fetching fiat rates is not part of scope of this issue)

<img width="572" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/f26fde14-b910-4851-8251-f1131b3de657">

https://satoshilabs.sentry.io/issues/5037970051/?project=4504214699245568&query=release:io.trezor.suite@24.3.1+45

**Comment by bosomt** [comment]
**QA OK**

2 cardano account, different time scopes, no crash, graph visible

Android 14 Nothing phone 1 
24.4.0 cd82750
