### ISSUE TITLE
Connect PIN enable process to Backup process

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1145]

**Comment by bosomt** [comment]
@mroz22 i see TT logo during PIN setup during backup when using T1

![image](https://user-images.githubusercontent.com/31506317/79111270-7e80ac00-7d7c-11ea-8b28-436cf3ce9f2c.png)

next screen looks OK 

![image](https://user-images.githubusercontent.com/31506317/79111317-95bf9980-7d7c-11ea-9319-a363185ae27f.png)

3. screen TT again :) 

![image](https://user-images.githubusercontent.com/31506317/79111365-acfe8700-7d7c-11ea-8661-5e610b32e904.png)

**Comment by slowbackspace** [comment]
> @mroz22 i see TT logo during PIN setup during backup when using T1
> 
> ![image](https://user-images.githubusercontent.com/31506317/79111270-7e80ac00-7d7c-11ea-8b28-436cf3ce9f2c.png)
> 
> next screen looks OK
> 
> ![image](https://user-images.githubusercontent.com/31506317/79111317-95bf9980-7d7c-11ea-9319-a363185ae27f.png)
> 
> 1. screen TT again :)
> 
> ![image](https://user-images.githubusercontent.com/31506317/79111365-acfe8700-7d7c-11ea-8661-5e610b32e904.png)

cc @mroz22

**Comment by mroz22** [comment]
Ok, If this was only about TT/T1 images, I have just fixed this recently.
