### ISSUE TITLE
Passphrase: Enable passphrase on device

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#11468]
When user wants to access hidden wallet, but this feature is not available on device, we need to turn this feature on within the device. 

Result of this task is that we're able to switch device feature `passphrase_protection` to `true`.

This will then break the current behaviour of the app, because the authorization of device will not run as expected, so https://github.com/trezor/trezor-suite/issues/11469 will have to be implemented first.

**Comment by STew790** [comment]
**QA OK**
Tested together with https://github.com/trezor/trezor-suite/issues/12354

24.6.0 https://github.com/trezor/trezor-suite/commit/c747f2a42759f6804364b7bfbe32010124172b76
