### ISSUE TITLE
Passphrase: Go to default wallet when passphrase is on device

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#11469]
If device has passphrase protection turned on (via `device.features.passphrase_protection`), on device connect, we'll under the hood give the device empty passphrase so we can access the base wallet of the device. 

No changes in the UI should happen, but this will prepare the dashboard for passphrased wallet to be accessed later.

Injecting `useEmptyPassphrase: true` in `App.tsx` should be removed as part of this issue.

**Comment by STew790** [comment]
**QA OK**

24.5.0 0ff1770
