### ISSUE TITLE
Empower/ Suite Guide Search bar floating over the screen

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11461]
In Suite Guide Search appears to float over the header when scrolling.

https://github.com/trezor/trezor-suite/assets/152851523/e479394e-33b2-4723-808d-be555f2589da

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.4.0 (fdd09c1115e32052c305e4f58624ab99c43d0149)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
