### ISSUE TITLE
Empower/Trade - unable to type country in the dropdown menu

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11462]
In the Suite Trade section, users can select the country to display offers from. However, currently, users can only scroll down to choose the country, which is a time-consuming process. Therefore, it would be helpful to add a functionality that allows users to simply type the name of the country they want to search for, which will make the search much faster and more efficient.

![image](https://github.com/trezor/trezor-suite/assets/152851523/c0e49020-3b96-4a54-b9d5-53e93462e4f7)

**Comment by STew790** [comment]
**QA NOK**
More info here https://satoshilabs.slack.com/archives/C031LD98L9K/p1709839755010899

**Comment by jvaclavik** [comment]
@adamhavel could you take a look on this? If it needs some harder refactoring jusk skip it, but if it's easy, please try to fix it 🙏

**Comment by bosomt** [comment]
**QA OK**

please consider limit character count that can be entered to search field 



![Image](https://github.com/user-attachments/assets/9f072370-8932-47b5-9bdd-023b383e1fa1)



**Info:**
 - Suite version: web 24.8.0 (9a1a5a697e9b34f44a1951e6c32d71074b243d50)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
