### ISSUE TITLE
Spike: Enable Polygon

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#11473]
Identify and describe what needs to be done to add a Polygon

Make it testable by reverting https://github.com/trezor/trezor-suite/issues/11262 at least temporarily or in branch.

- check places where `network.symbol === eth` condition is used
- check token definitions handling
- make use of `ethereumTokensSelectors` work with matic
- make `AccountDetailTokenHeader` work for with matic
- make `EthereumTokenToFiatAmountFormatter` work for with matic
- in general make sure stuff in `@suite-native/ethereum-tokens` to works for with matic
- make `TransactionDetailListItem` to work for with matic
- make sure everything in `@suite-native/transactions` works with matic
- make sure assets UI works correctly with matic
- make sure receive UI works correctly with matic

**Comment by vytick** [comment]
I see are two paths we can take here:

1. just do matic and a lot of stuff can remain the same
2. make some parts more generic (e.g. ethereum-tokens) to also work with cardano and sol tokens, while keeping the current UI for tokens

**Comment by matejkriz** [comment]
Let's close this one as done, thanks @vytick 👏  We should create a new issue for the actual implementation and link to this.
