### ISSUE TITLE
Passphrase: Handle passphrased wallet through form

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#11470]
If user wants to add hidden wallet, he'll be redirected to the form, submit passphrase, confirm on device and redirected to dashboard. 

Typing passphrase on device is not part of this issue. 

**Note:** For simplicity, use just very simple loader and don't implement the `Wallet is empty` right now.

![image](https://github.com/trezor/trezor-suite/assets/36101761/60485dd5-4aa3-4d4b-8b54-8bbeaf6cc754)

[Figma](https://www.figma.com/file/mmDnYtctfjnreWhTjLfeQH/Passphrase?type=design&node-id=911-48773&mode=design&t=TLzwBFP7RNxuSMHY-4)

**Comment by STew790** [comment]
**QA OK**
When I click on "Open passphrase", I am shown a form where I can enter the passphrase either on mobile or on device.
After that I am redirected to a loading screen that tells me that my passphrased wallet is being loaded and after that to a standard dashboard where discovery starts.

**Info**

24.6.0 https://github.com/trezor/trezor-suite/commit/c747f2a42759f6804364b7bfbe32010124172b76
