### ISSUE TITLE
No data available text alignment in Eth/Token section

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11483]
**Describe the bug**
Follow up of https://github.com/trezor/trezor-suite/issues/11109
See `No data available` text, rendered twice but aligned differently
Consider removing text completely 
 

**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="1155" alt="Screenshot 2024-03-06 at 21 53 21" src="https://github.com/trezor/trezor-suite/assets/31506317/b05e18cc-ec8d-429e-a203-0bcf1cbae733">

**Comment by MiroslavProchazka** [comment]
cc @peter-sanderson "Didn't we already eliminate this completely in a different issue?"

**Comment by tomasklim** [comment]
https://github.com/trezor/trezor-suite/issues/10435

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.4.0 (fdd09c1115e32052c305e4f58624ab99c43d0149)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
