### ISSUE TITLE
Standalone Trezor Suite app never starts without internet connection even with remembered wallet

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11482]
**Describe the bug**
Standalone Trezor Suite app never starts without internet connection even with remembered wallet.

**Steps to reproduce:**
1. Start app , connect device, discover and remember wallet
2. Stop app
3. Disconnect from internet
4. Start app and observe its behavior

**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
App loads thanks to remembered wallet

**Actual result:**
App never loads

**Screenshots:**
<img width="1435" alt="Screenshot 2024-03-06 at 19 24 54" src="https://github.com/trezor/trezor-suite/assets/31506317/d3d0192e-71da-4fcf-a83d-00b99ae20b5a">

**Comment by MiroslavProchazka** [comment]
It took like 2 minutes to start but eventually Suite loaded for me.
