### ISSUE TITLE
Dropwdown arrow orientation in Wallet switcher is reversed

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11505]
The dropdown beak orientation in Wallet switcher should be pointing down in case you wants to expand the modal and pointing upwards if you want to  collaps it. Currently it is reversed.

https://github.com/trezor/trezor-suite/assets/152851523/49c391e9-4eb4-4098-b0c5-0a48472e8ad3

**Comment by bosomt** [comment]
**QA OK**

https://github.com/trezor/trezor-suite/assets/31506317/598c7b86-5c3f-4985-96d5-dcfa2632a781

**Info:**
 - Suite version: desktop 24.3.1 (3b51be8c3246100235e4f1f204e2d1981df15318)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.4.0 (fdd09c1115e32052c305e4f58624ab99c43d0149)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
