### ISSUE TITLE
Move tokenDefinitions to root redux store from wallet

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11506]
https://github.com/trezor/trezor-suite/pull/11484#discussion_r1516533115

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.6.0 (e9a042518338e1b23fbf1542d4f08ea64dd930cd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
