### ISSUE TITLE
Change Biometric icons and texts

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#11511]
Change the UI according to [🆕 design](https://www.figma.com/file/RlWH784CRUIvooy8aq6XoR/Main-Flow?type=design&node-id=628-20420&mode=design&t=fJMnB8RW5tcKvkiP-11)  and [this](https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=22244-2009&mode=design&t=lWEUl9U3b8Jmig3I-0)

- [x] Use the same icon/text for all possible options. 
- [x] Differentiate ios and android according to design.
- [x] Change the order of primary/secondary button so the primary is on top
- [x] Change icon in settings to follow other changes

**Comment by shenkys** [comment]
[Design here](https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=22244-2009&mode=design&t=WbTpXqHo14jeqleP-11)

Please also change the order of primary/secondary button so the primary is on top. THX

**Comment by shenkys** [comment]
Locked screen [design here](https://www.figma.com/file/RlWH784CRUIvooy8aq6XoR/Main-Flow?type=design&node-id=628-20420&mode=design&t=fJMnB8RW5tcKvkiP-11)

Only difference between AN & iOS is the icon (for AN we use AN fingerprint icon, for iOS it's an iOS icon - you can see it in the board)

**Comment by bosomt** [comment]
**QA OK**

- version 24.4.0 c8e7d2e
- Android 14 , Nothing phone 1
