### ISSUE TITLE
Passphrase duplicated modal misaligned 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11528]
**Describe the bug**
Passphrase duplicated modal misaligned 

**Steps to reproduce:**
1. Add same passphrase or standard wallet twice
2. Observe warning modal

**Info:**
 - Suite version: desktop 24.3.1 (d03de8bf472a7b59b644083604d011af3b70f413)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/31506317/d0592697-0338-44ef-808e-6cedf155b747)

**Comment by jvaclavik** [comment]
This modal will be completely redesigned in view-only.
