### ISSUE TITLE
Transaction detail compare values - input is too high

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#11531]
**Describe the bug**mo
- In the `Transaction detail > Compare values bottom sheet` are the input values enormously high. 

**How to reproduce**

1. Go to Transaction detail > Compare values bottom sheet
1. See the error

**Expected behavior**
The `total` value is equal to sum of `input` and `fee` values.
**Screenshots**
![9093EF74-3A25-4430-AC7A-5F1E32F9B966_4_5005_c](https://github.com/trezor/trezor-suite/assets/26143964/dab7f0d8-4b39-45c1-90fd-f2156059cfd3)
![6B11E03C-AFFE-42FE-84DE-08B4ECC87E7D_4_5005_c](https://github.com/trezor/trezor-suite/assets/26143964/1eb3cbe1-bba2-40e5-a49b-4c708189e487)

**Comment by sime** [comment]
Transaction in question. Inputs are accurate. b4ea8e26f717cd2108ad512974b70070752d596aeb7c5c642a6c4111a98c4230
