### ISSUE TITLE
Short symbol name unrecognised tokens include '...' in its name in send form

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11539]
**Describe the bug**
![Screenshot 2024-03-11 at 13 01 12](https://github.com/trezor/trezor-suite/assets/33235762/b47b40f3-abea-42e7-a4ae-492ca0e561a8)

**Comment by Hannsek** [comment]
Is this regression? I believe so.

**Comment by bosomt** [comment]
@tomasklim is it possible that this change introduced blinking cursor to token/coin selector ?



https://github.com/trezor/trezor-suite/assets/31506317/a0b41b1a-9c97-42b3-aa9b-1e509da815dd



**Info:**
 - Suite version: web 24.5.0 (996e96de144e225b32baae3fb209371532e8ba95)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.5.3 regular (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
@tomasklim was this change merget into 24.5.1 version ?
and found Cardano token that has ... in middle of name, see screenshot.


![Image](https://github.com/trezor/trezor-suite/assets/31506317/ba73c94a-7025-4562-ad62-c57c2b36d1f5)



![Image](https://github.com/trezor/trezor-suite/assets/31506317/a29a6ca9-4e5a-44a5-8983-6de64be1143b)
![Image](https://github.com/trezor/trezor-suite/assets/31506317/e0acff21-4371-49b6-815c-1695fbc928fe)



**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by tomasklim** [comment]
Cardano is its own story. Please check other chains and ignore Ada 😀 there is some different component used

But it is weird, i will check cardano component and i will try to remove it

**Comment by bosomt** [comment]
ERC20 token looks like this on 24.5.1 in Send dialogue

<img width="146" alt="Screenshot 2024-05-05 at 15 48 43" src="https://github.com/trezor/trezor-suite/assets/31506317/b202408a-5009-4d01-b51e-90763ad41c85">
<img width="507" alt="Screenshot 2024-05-05 at 15 48 32" src="https://github.com/trezor/trezor-suite/assets/31506317/f2e2fb87-e7fd-4544-9067-c5f11287e52a">
<img width="468" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/d99cc251-4acf-4878-b802-b899310c4086">

**Comment by bosomt** [comment]
**QA OK**

- long names are shortened with ...
- short names no ... is present 🙏 


**Info:**
 - Suite version: desktop 24.5.2 (1ca8b8063fd7028d1fe242db41caa31c0a1f7d5a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
