### ISSUE TITLE
Account name labling ignores acc type

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11536]
Am I sending to Legacy, taproot or segwit account? I don't know
![Screenshot 2024-03-11 at 12 37 37](https://github.com/trezor/trezor-suite/assets/33235762/02dbdeb2-6978-401f-b652-6fedb9ba7826)

**Comment by MiroslavProchazka** [comment]
cc @Hermez-cz this one should be tackled by design.

**Comment by tomasklim** [comment]
Resolved by @enjojoy

**Comment by STew790** [comment]
**QA OK**
I tried BTC (Taproot, Legacy Segwit, Legacy), ETH (Legacy, Ledger), BNB (Ledger) and SOL (Ledger) and all have correct "tags" next to the number of account.

**Info:**
 - Suite version: web 24.12.0 (8869ea943a7f8770a85980dfc752f99ce33f7d70)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.5 regular (revision a61e783448043760a7c925e017bd08a4673a61c8)
 - Transport: BridgeTransport 2.0.33
