### ISSUE TITLE
Add new coin 7 - UI finetunning

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#11533]
Visual fixes according to UI feedback:

- [x] Account type selector screen on android seems broken
- [x] on press state is odd
- [x] after adding account, detail or receive screen should have  [ x ] close button instead of [ < ]back
- [x] update empty dashboard to https://www.figma.com/file/RlWH784CRUIvooy8aq6XoR/Main-Flow?type=design&node-id=601-66119&mode=design&t=oSgfDxIZoR35yGMM-0

**Comment by bosomt** [comment]
**QA OK**

Release notes for 24.4.0 (72)
Last commit hash: 7296f1a74998c3ae5648eb066e43f87e0259a13c
