### ISSUE TITLE
Empower/Invity/ Copy button and TX text alignment

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11541]
![image](https://github.com/trezor/trezor-suite/assets/152851523/566a91ea-8556-4367-8b4e-3f4667c1c0e7)

**Comment by MiroslavProchazka** [comment]
![image](https://github.com/trezor/trezor-suite/assets/152851523/2e4269a9-792b-4606-acb4-6dbb0085ac32)

**Comment by MiroslavProchazka** [comment]
Solved in 24.8.1
<img width="926" alt="image" src="https://github.com/user-attachments/assets/d39f0c81-ce41-4f91-9adc-ed79d9e542b3">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.8.2 (2a555706122c837a581ed139cf65114ad85fe7cf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.32
