### ISSUE TITLE
Standard wallet added as hidden after passphrase disabled

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11547]
**Describe the bug**
See videos. Its possible to 
1. add standard wallet by disabling passphrase and not reconnecting device as hidden wallet
2. adding standard wallet one more time and this crashes app

Happened to me multiple times that app crashed and not just on purpose by reproducing this issue.
Sometimes its not possible to reproduce. 
 
**Steps to reproduce:**
1. Start discovery of standard wallet
4. Disable passphrase
5. Add standard wallet 

**Info:**
 - Suite version: desktop 24.3.1 (3b51be8c3246100235e4f1f204e2d1981df15318)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/9c34354c-5215-41e7-b825-cd0cb691ff27

**Comment by MiroslavProchazka** [comment]
@komret I believe that this one is already fixed by https://github.com/trezor/trezor-suite/pull/11557, right?

**Comment by komret** [comment]
No, it is unrelated, I'll remove the second video from the original post.

**Comment by bosomt** [comment]
See https://satoshilabs.slack.com/archives/CKYFBT2C9/p1714717436762489

- you can see that Suite asks you to enable passphrase even you disabled passphrase and 
- you are not able to check receive address before you reconnect device after disabling pass

https://youtu.be/27J9R3K6MLw?si=58Kel3O7YLX4N2yT

**Comment by bosomt** [comment]
**QA OK**

its not possible to disable passphrase anymore in Suite

**Info:**
 - Suite version: desktop 24.12.0 (19aeb1a0f7d306fcbe7cc61ed330a2481a3d0e4e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 3.0.0-bundled.24.12.0
