### ISSUE TITLE
Discovery improvements

### ISSUE THREAD

**Issue by shenkys** [trezor/trezor-suite#11562]
Enable to restart/continue discovery if it was not finished

**Comment by shenkys** [comment]
Design done [here](https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?node-id=259-2068&t=gZI3UoFGeSkVq5WN-11)

**Comment by STew790** [comment]
**QA NOK**
Waiting for this fix https://github.com/trezor/trezor-suite/pull/13855

**Comment by vytick** [comment]
#13855 merged

**Comment by STew790** [comment]
**QA OK**
Issue was fixed, otherwise ok.

**Info:**
 24.8.1 f2f56aa
