### ISSUE TITLE
Custom gas price for Ethereum Staking, Unstaking and Claming

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11564]
**Design:**
![Screenshot 2024-03-13 at 14 13 36](https://github.com/trezor/trezor-suite/assets/33235762/42137137-3377-40ac-9458-88e0486ce895)
![Screenshot 2024-03-13 at 14 18 13](https://github.com/trezor/trezor-suite/assets/33235762/dbef5cda-6365-40e8-b68c-568469f4eea2)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.4.0 (0072d9131891ee8335fa16d285e534e3f7767625)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
