### ISSUE TITLE
Change font color on address poisoning alert 

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11561]
Please change font color to "white" in alert that the transaction might be fradulent. 
![image](https://github.com/trezor/trezor-suite/assets/152851523/f10bc644-5fc8-416a-ad17-a405fe99b60a)

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/0de5f6d6-cec5-47c1-9135-440aea656381)

**Info:**
 - Suite version: desktop 24.3.2 (5178a3047e9e34328f2ba7892e6b222ee32c1f58)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.2 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
