### ISSUE TITLE
Amount slider component

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11566]
**Description**
We need to create `slider` component so that user can choose how much he wants to unstake without typing the number.

- labels should be clickable and should fill the corresponding part
- just the slider is part of this issue, no inputs (probably the input is needed in storybook to demonstrate how it works)

Inspiration:
- something like this [codepen.io/thebabydino/pen/dybajpx](https://codepen.io/thebabydino/pen/dybajpx) just instead of blue dot separator, there is the empty space separator
- another example [codesandbox.io/embed/hrm4cd?module=/src/Demo.tsx&fontsize=12](https://codesandbox.io/embed/hrm4cd?module=/src/Demo.tsx&fontsize=12)
this is probably what we need just we do not want the library solution but custom

**Design:**
![Screenshot 2024-10-21 at 12 34 37](https://github.com/user-attachments/assets/ad4eef3d-69e7-4924-bf9b-86c752289fca)

We are going to use it in Unstake modal

![312560746-779b1257-ff00-488f-96d8-70c6d041218a](https://github.com/user-attachments/assets/903c3225-daca-49ab-a073-41503a1b452c)

**Comment by tomasklim** [comment]
@jvaclavik do we have slider component similar to this one?

**Comment by omykhailovskyi** [comment]
@tomasklim , @sime 
Do we need slider only for Staked Amount, right?
Or we need 2 Sliders, 1 for Reward and 1 for Staked amount? If Yes - then it's impossible to create a slider with separation
What should be the step within the slider? Percentage ratio in relation to the total amount?

**Comment by tomasklim** [comment]
@omykhailovskyi It should be just 1 slider, something like this https://codepen.io/thebabydino/pen/dybajpx just instead of blue dot separator, there is the empty space separator

**Comment by hynek-jina** [comment]
Btw. similar component is already used in coinjoin account details.. 
![Screenshot 2024-11-05 at 15 12 35](https://github.com/user-attachments/assets/be70885d-56e3-4ef8-b86f-eb4fb2ea0bd7)

**Comment by omykhailovskyi** [comment]
Hey, @hynek-jina 
Yes, it's similar.
But as you can see according to the design, there should be a divider, and in that case it should somehow understand the rewards amount, which would be much less in comparison with what is represented on the picture (~4% from the origin staked amount).
As well we need to understand the step that should be set there (users could stake thousands of Ethereum or just 0.1 ETH, what should be the step in that case?)

**Comment by hynek-jina** [comment]
hi @omykhailovskyi,
steps can be dynamic, and non-linear just like in mentioned case.
Sure it's not same.. but there is some common ground.
