### ISSUE TITLE
Cannot start Trezor Suite Error: http-receiver: Start error code: EACCES

### ISSUE THREAD

**Issue by hajekt2** [trezor/trezor-suite#11565]
Running first time Trezor Suite on new PC with Windows 11.
Installed latest version Trezor-Suite-24.2.4-win-x64.exe for my user only.
When Trezor suite starts it just immediately shows:
Error occurred
It appears something is broken.
Check if there is another instance of the Suite app running. Error: http-receiver: Start error code: EACCES

I tried to uninstall and install again. Tried to restart Windows several times. Task manager does not show any other instances of Trezor Suite running.

**Info:**
-   Remembered Wallet: -
-   Suite Version: app 24.2.4
-   Browser: -
-   Browser Installation Method: -
-   OS: Windows 11 Business 23H2 build 22631.3155
-   Bridge: -
-   Firmware Version: -

**How to reproduce**
1. Install Trezor Suite for my user only (no admin)
2. Run Trezor Suite
3. The first screen that comes up is the error screen attached as screenshot. No significant delay starting the app.

**Expected behavior**
It is expected Trezor Suite starts without any errors.

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/7295116/d1c2aab4-fa2f-4f2b-a7e7-0a69c76b83cc)

**Comment by MiroslavProchazka** [comment]
@trezor/qa  Can you try to reproduce it please?

**Comment by STew790** [comment]
Unfortunately, can't replicate this. I would suggest just restarting PC or maybe reinstall of Suite. 
Closing.

**Comment by hajekt2** [comment]
@STew790 That is what I have done already without any success.
I have a suspicion this is something in my environment, maybe caused by the fact I do not have admin access.
Any way to get some logging or debugging info to you?

**Comment by MiroslavProchazka** [comment]
Can you use the web version of Suite? (https://trezor.io/trezor-suite) 
You don't have admin access, does that mean that the machine is under the settings and rules of some company? Sometimes companies block IP addresses and sites, dunno if that could be your cause as well.

**Comment by hajekt2** [comment]
Web version is working OK. If web has the same functionality as the app then I am OK with web version.
I have tried to install the app as admin for all users, but it ended up with the same result.
Yes, the machine has some company rules, but not behind  firewall/vpn. Another machine on the same network works OK.

This is content of C:\Users\TomasHajek\AppData\Local\Programs\Trezor Suite\debug.log
`[0313/125356.246:ERROR:registration_protocol_win.cc(107)] CreateFile: The system cannot find the file specified. (0x2)`

**Comment by MiroslavProchazka** [comment]
Can you please check whether your port 21335 is not used with another service? It seems that Suite is trying connect to this port and fails in case it is not available.

**Comment by hajekt2** [comment]
Yees, I have Printix Service by Kofax running on that port. When that app was stopped Trezor Suite starts OK.
Suggest you improve error reporting.
Thank you for help.
