### ISSUE TITLE
Hide Low Fee option from Sell and Spend

### ISSUE THREAD

**Issue by marek-andrsk** [trezor/trezor-suite#11577]
**Issue**
Users contact Support due to stuck transactions sent with Low/Economy fees. RBF is not supported by exchange partners at the moment so we need a quick/easy solution to prevent this.

**Solution**
Hide Low fee option from Fee component in Sell and Spend. In other places (Exchange or Send) the Low option will remain.
<img width="757" alt="Snímek obrazovky 2024-03-14 v 14 59 54" src="https://github.com/trezor/trezor-suite/assets/6542812/eeacb823-8916-4618-88ba-61cd5cf91bf1">

**Comment by MiroslavProchazka** [comment]
Maybe it is also worth thinking about remapping the fees we are getting from mempool.space to Suite fee priorities - as it is discussed [here](https://satoshilabs.slack.com/archives/CKZHV2G13/p1710324037584349?thread_ts=1710323205.445049&cid=CKZHV2G13). I totally agree with deleting the LOW fees, but we can also think of adjustments of fee levels for the rest of buttons - economy and normal. cc @marek-andrsk

**Comment by marek-andrsk** [comment]
@MiroslavProchazka that's why we're hiding only Low option instead of Low+Economy as we originally wanted :) the remapping is being handled separately

**Comment by MiroslavProchazka** [comment]
Great, thanks!

**Comment by bosomt** [comment]
I still see `Low` fee in `Trade/Sell` section


![Image](https://github.com/trezor/trezor-suite/assets/31506317/4513aadf-db21-4c47-a6d8-8564497cc5c2)

**Info:**
 - Suite version: desktop 24.4.0 (0072d9131891ee8335fa16d285e534e3f7767625)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by FreeWall** [comment]
@bosomt its probably because of this, its filters low, but economy is translated as low now
https://github.com/trezor/trezor-suite/pull/11733
