### ISSUE TITLE
Custom homescreen upload

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1157]
- [ ] Validation (?)
- [ ] Cropping (?)

Include Model One in the process.

**Comment by prusnak** [comment]
Duplicate of https://github.com/trezor/trezor-suite/issues/945

**Comment by jimbojw** [comment]
Is this still on the roadmap?

**Comment by tsusanka** [comment]
I think this has been done by https://github.com/trezor/trezor-suite/pull/4725?
