### ISSUE TITLE
Unstaking: Align FW and Suite when signing

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#11586]
# Acceptance Criteria 

Given I am staking in Trezor Suite
Then I should see 'Unstake'
And I should see 'Unstake ETH from Everstake'

# Screenshots
![image](https://github.com/trezor/trezor-suite/assets/216917/77efc6f0-85ac-428f-9f2e-c7cc5aecf69e)
![image](https://github.com/trezor/trezor-suite/assets/216917/9e6215e4-ac87-4b1e-bcf8-00825b853b5b)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.4.0 (5c0062348b4f812f50604dd13814d2b07d61b534)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
