### ISSUE TITLE
Staking: Aligning FW and Suite when signing

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#11583]
# Acceptance Criteria 
Given I am staking in Trezor Suite
Then I should see 'Stake'
And I should see 'Stake ETH on Everstake'

# Screenshots
![image](https://github.com/trezor/trezor-suite/assets/216917/25f4d070-26c5-435c-9da1-cf0af2be5fff)
![image](https://github.com/trezor/trezor-suite/assets/216917/223b0b0b-7272-444c-ab10-6691a71b7da4)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.4.0 (5c0062348b4f812f50604dd13814d2b07d61b534)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
