### ISSUE TITLE
Claiming: Align FW and Suite when signing

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#11587]
# Acceptance Criteria 

Given I am staking in Trezor Suite
Then I should see 'Claim'
And I should see 'Claim ETH from Everstake'

# Screenshots
![image](https://github.com/trezor/trezor-suite/assets/216917/a303db57-c25e-42da-988e-c30519aebef6)
![image](https://github.com/trezor/trezor-suite/assets/216917/f383eed9-baf9-4901-8464-feeebbe9347b)

**Comment by bosomt** [comment]
**QA OK**




![Image](https://github.com/trezor/trezor-suite/assets/31506317/8e26aae5-845c-41dd-8e20-3bc14e2d978d)

**Info:**
 - Suite version: web 24.4.0 (7296f1a74998c3ae5648eb066e43f87e0259a13c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
