### ISSUE TITLE
Gaps are quite small between accounts on the same network

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#11597]
**Describe the bug**
Gaps between accounts on the same network have in my opinion quite small gap so I can't really see difference between a tokens link to one account and two different accounts.

**Info:**
-   Mobile Suite Version: 24.3.1
-   OS: iOS

**How to reproduce**

1. Import at least 2 accounts on the same network (ideally with tokens so ethereum)
1. See assets or receive lists

**Expected behavior**
It will be better to have bigger gaps between them.

**Screenshots**
![IMG_2691](https://github.com/trezor/trezor-suite/assets/66002635/67669eca-f54f-41db-b4a9-8016cda45527)

**Comment by matejkriz** [comment]
@shenkys what do you think? Please assign priority or close it.

**Comment by mnuky** [comment]
will be resolved as part of issue: https://github.com/trezor/trezor-suite/issues/7646
