### ISSUE TITLE
Don't show the "Portfolio" tooltip on Dashboard for BTC only wallets.

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#11615]
On the Dashboard, the Portfolio title above the graph has an explanative tooltip.
Remove it please together with the title underscore if the wallet is BTC only (BTC only FW or device). It makes no sense showing it for BTC only use cases.

![Image](https://github.com/trezor/trezor-suite/assets/88533514/39564507-d7b2-4591-87d8-e25b3e13dc60)

**Comment by bosomt** [comment]
**QA OK**

no tooltip is present when btconly device connected

**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
