### ISSUE TITLE
Move the notifications popup slightly lower

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#11610]
**Describe the bug**
The notification popup is now covering the "Send/Receive" buttons when visible. Just a quick fix might be to just show it a little lower.

**Steps to reproduce:**
1. Go to account
2. Reveal an address
3. Copy address via button, notification appears

**Info:**
 - Suite version: web 24.2.4 (748176286ae231aae44c83981a62b174b7605e1a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: WebUsbTransport

**Expected result:**
Notification popup shouldn't hide the buttons

**Actual result:**
The notification popup is now covering the "Send/Receive" buttons

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/48477147/96f86a04-1309-4537-8230-f40e3424653e)

**Comment by Hermez-cz** [comment]
Please make sure the notifications aren't blocking the buttons even if some messaging system banner or warning is present (or multiple).

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.5.0 (d599391ce8467166f0ffd6f3f1fb0abd35c6bb91)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
