### ISSUE TITLE
Wallet discovery is not looking thoroughly enough.

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#11614]
I just had two very related experience in the same day.

Receive ETH to last account to then realize there was an account with a balance right after.
Suite only look for a single ETH account before deciding that there is nothing else. It should look way further like 10.
This is like having a gap limit of 1 for fetching a BTC balance.

Then a bit later I restored a Trezor device on another machine, I was surprised not to be able to see Coinjoin account and having to figure how it manually.

You should look into how electrum AND sparrow are doing account discovery.

https://github.com/spesmilo/electrum/issues/6155
Great thread.

I understand that you don't want people to use any gap in accounts but since other wallet allows it (Metamask) there's a risk that people will lose funds because they assume all account with balance would show up using the native device wallet.

**Comment by MiroslavProchazka** [comment]
cc @Hannsek @Hermez-cz @sime - will you share your thoughts on that please? I think the current state in Suite is a mix of product decisions and market consensus. There is also part of users that have their own Electrum server and use Tor, which would wait quite a long term in case of a bigger gap limit.

**Comment by prusnak** [comment]
If an account is empty then the search stops. The BIP-44 is very specific about that.

Fix: Send coins to the empty account.

**Comment by nostitos** [comment]
BIP44 is for bitcoin with infinite amount of address per account. 

It should be way more prevalent for ETH to have some gaps in addresses since it's one per account.

My issue also had a CJ account component, 
In the same way that I assume Suite checks all script types for balances it should check it's CJ account.

**Comment by nostitos** [comment]
BTW last I checked, MEW shows the first 6 ETH accounts with a balance or not.

**Comment by Hannsek** [comment]
CJ is not discovered automatically right now by design.
