### ISSUE TITLE
Add CZ language as official language in Suite

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11622]
Please move CZ language from community to official.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.4.0 (fdd09c1115e32052c305e4f58624ab99c43d0149)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by STew790** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.5.0 (a54e74f6dc7655fd94fc10203562226e0dc5527d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.5.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
