### ISSUE TITLE
Fix app name in app config

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#11644]
When we migrated to expo, app name changed from `Trezor Suite Lite` to `Trezor Suite`. Change this in `suite-native/app.config.ts`.

**IMPORTANT**: This might break expo eas and we might need to move certificates for production project in expo.

**Comment by matejkriz** [comment]
@juriczech I guess we can fix the name but keep the slug as it is. Then it should not break anything on EAS, I hope.

**Comment by juriczech** [comment]
@matejkriz Yes, I hope that's the case. Just wanted to add it as a reminder that it should be tested at least not to surprise us before release.

**Comment by juriczech** [comment]
This will have to be tested on production build

**Comment by bosomt** [comment]
**QA OK**

both platforms apps are identified as Trezor Suite Lite
