### ISSUE TITLE
Cancelling wipe code setup shows "pin-cancelled" notification

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#11655]
**Describe the bug**
If I cancel the wipe code setup it shows a notification "pin-cancelled".

**Steps to reproduce:**
1. Go to settings
2. Device settings
3. Click on set up wipe code
4. Cancel the setup
5. Observe wrong notification "pin-cancelled"

**Info:**
 - Suite version: desktop 24.3.2 (f67de55c38fb87853e66fafc2143fe3b17ac6e54)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.2 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
Wipe code cancelled should be shown in notification.

**Actual result:**
"Pin cancelled" is shown in notification when cancelling wipe code.

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/48477147/2fa86441-2018-4c83-b70a-b81ee4266f88)

**Comment by bosomt** [comment]
**QA OK**

i got `Error: Cancelled`

**Info:**
 - Suite version: desktop 24.3.3 (1b6b0c29ca5982930ac65e23be9014d76d6b8478)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.3 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
