### ISSUE TITLE
App starts slow as soon you have Solana token account present

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11659]
**Describe the bug**
See video.
As soon you reload app that contains Solana tokens it takes really long to start

**Steps to reproduce:**
1. Enable Solana account that contains tokens
2. Load and remember wallet
3. Reload or restart Suite app

**Info:**
 - Suite version: desktop 24.3.2 (f67de55c38fb87853e66fafc2143fe3b17ac6e54)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.2 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
https://youtu.be/gDCZZOTGbzo

**Comment by MiroslavProchazka** [comment]
Can we call all the fiat rates requests at once?

**Comment by AdamSchinzel** [comment]
Related: There is already comment in code to refactor `fiatRatesThunk.ts` to batch requests as much as possible

**Comment by MiroslavProchazka** [comment]
@AdamSchinzel Have you touched this during the Fiat rates PR? :)

**Comment by AdamSchinzel** [comment]
I think it should be resolved by #12445, can you check @bosomt

**Comment by bosomt** [comment]
**QA OK**

24.5.2 - still slow
24.6.0 - 7 seconds for remembered wallet with solana and bitcoin accounts

**Info:**
 - Suite version: desktop 24.6.0 (65cacb6ca27ad3c1792212e3ce945f98c692cb22)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 3.0.0
