### ISSUE TITLE
Add an option to change language to CZ on device 

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11654]
Please add an option to change the device language to CZ in the Suite dropdown menu. 

![image](https://github.com/trezor/trezor-suite/assets/152851523/f1efe500-b514-4915-8039-d50c6711ece5)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.4.1 (979558244707a3d9d577cf9afff6a860c48b137d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
