### ISSUE TITLE
Create new account type duplicates existing account type Segwit

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#11653]
Steps to reproduce:

1. Connect Trezor with some existing accounts
2. Click on My Asset
3. Click on "+" and create new account - type Segwit - account is added and marked correctly
4. Go back to My Assets
5. Click on "+" and create new account - type Taproot, go back to My Assets, you see new Bitcoin item but it is marked as Segwit and inherits the balances from BTC#1 account - watch the attached video.

https://github.com/trezor/trezor-suite/assets/84183817/094539d9-f247-4a0c-9319-243f4d24c6c3

**Comment by bosomt** [comment]
**QA OK**

24.4.0 (74)
Last commit hash: 2882f42525f5173c6673e0b4c41c9644c2ccb92e
