### ISSUE TITLE
Coin balance font is too tiny

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#11668]
Steps to reproduce:
1. Open the app (it appears on both platforms)
2. Look at the My Asset page
3. Look at the coin detail page
4. Coin balance text is super small - non readable

See the printscreens:
![Image](https://github.com/trezor/trezor-suite/assets/84183817/e7f26640-c09b-4176-8951-e0be322a6f7f)
![Image](https://github.com/trezor/trezor-suite/assets/84183817/30e35db9-e71c-44c2-a16e-02b941e08dc3)

**Comment by bosomt** [comment]
I was not able to reproduce it on my iPhone 11 or Nothing phone 1 with Android 14

**Comment by bosomt** [comment]
I was able to reproduce it now on my Android 14 phone

![telegram-cloud-photo-size-4-6048485190805864149-y](https://github.com/trezor/trezor-suite/assets/31506317/2f0d0eec-e3aa-426e-bda8-454fe9d38dea)

24.4.0 (74)
Last commit hash: 2882f42525f5173c6673e0b4c41c9644c2ccb92e

**Comment by bosomt** [comment]
**QA OK**

@mnuky  please confirm on latest dev version, it works fine on my Android phone and on iPhone 11

Release notes for 24.4.0 (79)
Last commit hash: d31fb00d71aec67cc98757b6ade92e4b2b051082
