### ISSUE TITLE
Create ResizableBox component

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#11681]
## Description

Create a generic component `ResizableBox` into the [Trezor design system](https://github.com/trezor/trezor-suite/tree/develop/packages/components/src/components) for drag & drop resizing elements.

- It should follow basic UI patterns used for this type of component. 
- whole side should be draggable, it should be highlighted on hover and should use appropriate cursor and highlighting (check screenshot below).
- It should be implemented with Javascript (ideally without external dependencies)
- create storybook with example

## Screenshots

<img width="176" alt="Screenshot 2024-03-21 at 16 03 57" src="https://github.com/trezor/trezor-suite/assets/858321/c275131c-3a62-42da-8e73-6736b6512bc4">

<img width="75" alt="image" src="https://github.com/trezor/trezor-suite/assets/858321/c93c5479-5ef7-476f-b44d-0097c634d415">

https://github.com/trezor/trezor-suite/assets/858321/06d9bae7-8380-4204-8f14-aa08ccae1b88

## Interface

Props:
```typescript
type ResizableBoxProps = {
  children: React.ReactNode;
  directions: Array<"top" | "left" | "right" | "bottom">; 
  isLocked?: boolean; // if true, it's not possible to resize the component (default = false)
  width?: number;
  minWidth?: number;
  maxWidth?: number;
  height?: number;
  minHeight?: number;
  maxHeight?: number;
}
```

Usage:
```tsx
<ResizableBox width={250} minHeight={60} maxHeight={400} directions=["right"]>
  <Sidebar 
    ...
  />  
</ResizableBox>
```

**Comment by hstastna** [comment]
Hi @jvaclavik, thanks for this issue, let's see what I can do, starting working on it..

**Comment by bosomt** [comment]
**QA OK**



https://github.com/trezor/trezor-suite/assets/31506317/90720654-4670-4658-ae94-12e2647d12cd



**Info:**
 - Suite version: web 24.7.0 (85680dd78db3284862c2a4d263cc532cfa7d6b0a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
