### ISSUE TITLE
Connect device animation overflow

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#11694]
**Describe the bug**
Trezor device animation overflows on smaller screen devices during the onboarding.

**How to reproduce**

1. Go to `Connect Trezor` screen in onboarding flow
2. See the overflowing animation

**Screenshots**
![Screenshot 2024-03-21 at 9 52 16](https://github.com/trezor/trezor-suite/assets/26143964/fc53bd05-91ee-41cd-99af-a1fc49fb78b8)

**Comment by bosomt** [comment]
**QA OK**

- version 24.4.0 3550932
- Android 14 , Nothing phone 1
