### ISSUE TITLE
connect-popup tests - more logs

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#11698]
We already have @trezor/connect-webextension package tests running in github. This is good. But some of them are pretty flaky. 

Check develop runs: https://github.com/trezor/trezor-suite/actions/workflows/connect-dev-release-test.yml?query=branch%3Adevelop

Lets please figure out how to add downloading logs from logs page [similary to this test ](https://github.com/trezor/trezor-suite/blob/develop/packages/connect-popup/e2e/tests/popup-close.test.ts#L154-L168) also to other test files

**Comment by karliatto** [comment]
It does not look like we need this anymore, do we? Popup tests have become way more reliable than they were 2 years ago. And we can use playwright to get a lot of information. Right?
