### ISSUE TITLE
Remove popperjs from `connect-explorer-theme`, replace with floating-ui

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#11695]
See: https://github.com/trezor/trezor-suite/pull/11667#discussion_r1532202740

The relevant file: `packages/connect-explorer-theme/src/utils/use-popper.ts`

**Comment by MiroslavProchazka** [comment]
cc @martykan

**Comment by martykan** [comment]
The hook is only used in one place - their Select component, so probably it would be better and easier to get rid of that altogether and use the Select from our components.
The Select component itself is used for the theme switcher and locale switcher (which we don't use)
