### ISSUE TITLE
Failing ETH tokens fiat rates - `Rendered more hooks than during the previous render`

### ISSUE THREAD

**Issue by marekrjpolak** [trezor/trezor-suite#11701]
## How to reproduce
- go into ETH tokens tab
- add a new token
- observe the error

**Comment by STew790** [comment]
**QA OK**
Works fine both web and app.

**Info:**
 - Suite version: desktop 24.3.3 (1b6b0c29ca5982930ac65e23be9014d76d6b8478)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.3 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
