### ISSUE TITLE
Hide only rewards in ETH staking when below 0.1

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11716]
Hide `Only rewards` part if unstaking minimum is not met
![Screenshot 2024-03-25 at 9 34 54](https://github.com/trezor/trezor-suite/assets/33235762/fe7e27e5-ec92-44b7-bab5-6f4622125bfe)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.4.1 (f4684c1893fe8b0f45c217837e2cbedaa6928d25)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
