### ISSUE TITLE
Hide Finalize transaction button

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11710]
Please hide the button **Finalize transaction** in the send flow as we will come up with fullrbf later this year as a replacement for this relict. 
It would be wise to also align the **Bump fee** button to the right 
![image](https://github.com/trezor/trezor-suite/assets/152851523/4bcc3317-d76e-44ec-8f02-fa0727801cee)

**Comment by sime** [comment]
Related https://github.com/trezor/trezor-suite/issues/6810

**Comment by STew790** [comment]
**QA OK**
Finalize transaction not present.

![image](https://github.com/trezor/trezor-suite/assets/48477147/040a63c6-149c-42b9-94a1-73b1e0c43434)

**Info:**
 - Suite version: desktop 24.4.0 (a0556d2e0c123ad3080ce3df4accaa47e9d39021)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.32
