### ISSUE TITLE
Show Ethereum staking banners when user has ETH enabled

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11717]
Now we show it only in case user has more than `0.1` ETH. Let's show it when `Ethereum` is enabled because user can have funds on CEX, in `WETH`, he can stake somewhere else or he just want to buy new eth to stake.

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/trezor/trezor-suite/assets/31506317/54ea49d8-adf6-4b76-b9f1-55874e70f8c0)



**Info:**
 - Suite version: desktop 24.4.0 (0072d9131891ee8335fa16d285e534e3f7767625)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
