### ISSUE TITLE
Trezor suite upgrade code is terrible, the worst ever!

### ISSUE THREAD

**Issue by akissz** [trezor/trezor-suite#11712]
The Trezor Suite upgrade downloader code is the worst because the recovery during either slow or bad internet makes the download crash every time and not complete the download. I have had it happen 50 or 100 times in the past few years. It has been this way for many years. It is the worst upgrade software I have used in 20 years. Please try to improve the code to improve recoveries during slow or bad internet so upgrades function more smoothly recover and you do not need to restart the download every single time the download fails, is incomplete or anything else. I would think a crypto community with decentralized mindset would understand the meaning of good torrent-like downloading for upgrading software.

**Comment by sime** [comment]
@akissz Sorry you're having trouble with Trezor Suite auto-updating. Trezor Suite also supports updating over Tor and that can be slow and unresponsive too.

Could you share the details of your internet connection? 

If you are _really_ struggling, I suggest the following strategies:
* The web version of Trezor Suite is always up to date: https://suite.trezor.io/web
* Manually download Trezor Suite using your browser/favourite download manager on https://trezor.io/trezor-suite (which links directly the file hosted GitHub).

**Comment by akissz** [comment]
@sime My internet connections is good. Not the best but good. I am a web developer and constantly using the Internet all day long without issue. I am also a server admin using servers all around the world without issue for decades. When I start the Trezor Suite and it tries to update, and 95 percent of the time the download always fails to start or fails to complete. Today I tried multiple times. Once it got to 25 percent and the next time only about 3 percent. Now that I think about this more I remember also every time I try to download Trezor Suite via a web browser, Firefox and Chrome, the download also dies part way though. I guarantee something is wrong with your servers or something needs to be changed on your end or somewhere in the middle!

**Comment by sime** [comment]
@akissz Which operating system? If Windows, do you have the same experience with a live booted Linux distribution?

> Now that I think about this more I remember also every time I try to download Trezor Suite via a web browser, Firefox and Chrome, the download also dies part way though. 

Eeek, this is a tough one, if your browsers struggle to download from [GitHub](https://github.com/trezor/trezor-suite/releases), I don't know what remedies we could offer.

Many moons ago, I was trying to leech from a terribly performing server, default browser-based downloaders would continually fail. 

Until I tried [wget](https://www.gnu.org/software/wget/), that little program constantly retried until I got what I wanted.

I wonder if your IP is not favoured by GitHub, I suggest you try auto-updating with Tor enabled. GitHub won't know your IP that way.
