### ISSUE TITLE
Staking in a nutshell days improvement

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11718]
Use `Unstaking currently takes {x} days. Once completed, you can trade or send it.`
![Screenshot 2024-03-25 at 9 38 49](https://github.com/trezor/trezor-suite/assets/33235762/98b2177d-63f7-464e-86ce-afd1346c8a5b)

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/trezor/trezor-suite/assets/31506317/bdccf89e-76d5-4133-b17f-7500cc879be9)

**Info:**
 - Suite version: desktop 24.4.1 (f4684c1893fe8b0f45c217837e2cbedaa6928d25)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
