### ISSUE TITLE
Disable low fee option

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#11732]
- disable low fee
- instead of economy show translation for low fee

current state:

![image](https://github.com/trezor/trezor-suite/assets/858321/35f58a03-6b9d-4185-a95b-06d9daddd168)

desired state:

![image](https://github.com/trezor/trezor-suite/assets/858321/a770e909-0314-4829-8278-9da726678223)

**Comment by STew790** [comment]
**QA OK**

Low fee option is not present in both languages.

![image](https://github.com/trezor/trezor-suite/assets/48477147/32d84774-656a-4b3a-8aab-0e347265031e)
![image](https://github.com/trezor/trezor-suite/assets/48477147/ed0f5f79-c382-404c-9dfa-9100edfe3e6e)

**Info:**
 - Suite version: desktop 24.4.0 (a0556d2e0c123ad3080ce3df4accaa47e9d39021)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.32
