### ISSUE TITLE
Can't add ERC20 token 

### ISSUE THREAD

**Issue by 0x143** [trezor/trezor-suite#11748]
**Describe the bug**
When trying to add a new ERC20 token I get:

> Error occurred
> It appears something is broken. 
>
> Minified React error `#310`; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Info:**

-   Remembered Wallet: no
-   Suite Version: app and (24.3.2) web
-   Browser: FF 115
-   Bridge: 2.0.30
-   Firmware Version: T, 2.70

**How to reproduce**

1. Start new session (either web or app) with clean env,
2.  Enable Ethereum in coin list
3. Open ethereum walled
4. Click on tokens
5. Click on add token
6.  Paste contract (i.e. 0xdac17f958d2ee523a2206206994597c13d831ec7 - USDt copied from coinmarketcap).
7.  Click on add token

**Expected behavior**
Action succeeds

**Comment by sime** [comment]
Thanks, we are already tracking it. https://github.com/trezor/trezor-suite/issues/11701
