### ISSUE TITLE
"No accounts" when wallet is not yet discovered

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#11747]
**Describe the bug**
Avoid showing `No accounts` before I choose what wallet I want

**Info:**

-   Suite Version: 24.3.2

**How to reproduce**

1. Open app
2. Check left bar before you choose standard/hidden wallet

**Screenshots**
![Screenshot 2024-03-26 at 6 50 53](https://github.com/trezor/trezor-suite/assets/33235762/6ad6d743-b8a3-4fb6-85d3-816a4bfa0df0)

**Expected behavior**
![Screenshot 2024-03-26 at 6 50 57](https://github.com/trezor/trezor-suite/assets/33235762/55edcda0-9e7e-4cda-98fe-acf921d76458)

Maybe better just do not show `No accounts`

**Comment by MiroslavProchazka** [comment]
Will be fixed once View-only wallet will be implemented (ETA 24.7 release)
