### ISSUE TITLE
Content: Learn more about staking link to KB

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#11757]
URL: https://trezor.io/learn/a/stake-ethereum-eth-in-trezor-suite

**Comment by bosomt** [comment]
**QA OK**

linked but article not yet published 
@sime expected right ?

**Info:**
 - Suite version: desktop 24.4.0 (0072d9131891ee8335fa16d285e534e3f7767625)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
