### ISSUE TITLE
Add option to bump fee even for transactions without RBF flag

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#11750]
Ignore RBF flag for bumping transaction option.

All pending transactions should be possible to bump (speed up)
![Screenshot 2024-03-26 at 09 56 14](https://github.com/trezor/trezor-suite/assets/26002916/76adaf3f-c506-4f80-ad37-0200fded9eab)

Same option should be visible in transaction detail.

Related to: https://github.com/trezor/trezor-suite/issues/11710

**Comment by bosomt** [comment]
**QA OK**

checked multiple txs with RBF off but bump button was always available
bump worked
new tx has RBF on

**Info:**
 - Suite version: web 24.8.0 (d9959adfccff250c111f6e2b9bfb91305834cb3c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
