### ISSUE TITLE
Adjust Add token button

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11762]
Please adjust the Add token button according to the following spec: 

If Debug mode is ON - keep the button as it is right now 
If Debug mode is OFF - delete the insert field and keep just adjusted text there -> 
![image](https://github.com/trezor/trezor-suite/assets/152851523/4f343908-2b20-4d67-8cd2-cc03e50805ab)

The final copy will be finalized, I will post it in the comment once it is reviewed

**Comment by tomasklim** [comment]
Empty token page has to be changed @MiroslavProchazka 
![Screenshot 2024-03-27 at 15 19 19](https://github.com/trezor/trezor-suite/assets/216917/5845b3da-f118-4e5e-bd61-196327185f32)

**Comment by MiroslavProchazka** [comment]
Final copy 

"Add tokens with receive" - header after you click the button

"No need to activate tokens first. Simply click the receive button to create a receive address and send your tokens straight to your Trezor. Just make sure to match the network to access your tokens correctly." - text in the modal

**Comment by STew790** [comment]
**QA OK**
The button is correct and the copy as well.
![image](https://github.com/trezor/trezor-suite/assets/48477147/70f6057c-4bf7-4e68-9e6d-659915fa0925)
![image](https://github.com/trezor/trezor-suite/assets/48477147/4124555f-ebd5-4186-9246-8676f0f1dc2c)

**Info:**
 - Suite version: desktop 24.4.0 (a0556d2e0c123ad3080ce3df4accaa47e9d39021)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.32
