### ISSUE TITLE
New Trezor initialization,  Suite doesn't seems to be loading anything, No progess,

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#11774]
![image](https://github.com/trezor/trezor-suite/assets/48504624/2cf39d86-d399-449b-9c79-1cc0f01e674e)

It's been a good 5min.

Update: I had to click dashboard and select "standard - no passphrase"

No users should end up on that page.

**Comment by MiroslavProchazka** [comment]
Will be fixed with new wallet switcher and default wallet in View only mode adjustment - ETA 24.7
