### ISSUE TITLE
Add text to SOL tx modal

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11771]
As a follow-up to https://github.com/trezor/trezor-suite/pull/11515, please add text to the modal indicating that confirming transaction might take up to 1 minute. 

Final text to insert into the modal - "Please wait, confirmation of the transaction may take up to 1 minute"
<img width="704" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/6702bbee-67a9-46c0-b983-120af188cb8a">

**Comment by MiroslavProchazka** [comment]
@peter-sanderson Please put the text bellow the button "Confirming transaction"

**Comment by bosomt** [comment]
**QA OK**

<img width="396" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/c607e3be-1ae7-433f-a474-fc805d239f17">

**Info:**
 - Suite version: desktop 24.4.0 (0072d9131891ee8335fa16d285e534e3f7767625)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
