### ISSUE TITLE
Staking: Double click on confirm+stake attempts double signing

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#11772]
Signing window opens twice when double-clicking confirm+stake.

https://github.com/trezor/trezor-suite/assets/216917/26cc1b80-3e35-46d4-952f-319f7daaa6cf

**Comment by bosomt** [comment]
**QA OK**

Fixed but im not sure if  `Stake Ethereum` modal should be reopen or not, probably yes,



https://github.com/trezor/trezor-suite/assets/31506317/257c40b7-674a-4139-aa6f-d629be37e98b

**Info:**
 - Suite version: desktop 24.4.0 (0072d9131891ee8335fa16d285e534e3f7767625)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
