### ISSUE TITLE
Polygon PoS addtoken error

### ISSUE THREAD

**Issue by Drennann** [trezor/trezor-suite#11775]
I try to add the WETH token to the Polygon PoS network and I get an error related to reactJs

-   Remembered Wallet: yes
-   Suite Version: app, 24.3.2
-   OS: Windows 10 Pro, 22H2
-   Firmware Version: 1.21.1, 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f

1. Settings
2. Coins
3. PolygonPoS
4. tokens
5. add token
6. paste WETH (0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619)

![Captura de pantalla 2024-03-27 021029](https://github.com/trezor/trezor-suite/assets/53791578/3f27c410-9493-46d2-b46b-aad69cc453ab)

**Comment by MiroslavProchazka** [comment]
Please update to Suite 24.3.4 where it is already fixed.
