### ISSUE TITLE
Backup failed during device onboarding

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11789]
**Describe the bug**
Multiple users are reporting Backup failed during device onboarding.
So far it does not look like problem with latest firmware.
See whole thread here https://satoshilabs.slack.com/archives/CL1D61PQF/p1711530306816269
I will update issue if needed after we found culprit of this issue

**Steps to reproduce:**
not sure if its same problem but i can replicate it this way
1. Start device onboarding
2. During seed backup wait till computer is locked.
3. Unlock computer and check state of app and device

**Info:**
 - Suite version: desktop 24.3.2 (f67de55c38fb87853e66fafc2143fe3b17ac6e54)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.2 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/31506317/911fd12b-8697-45aa-9966-49ac8a3d869a)
![image](https://github.com/trezor/trezor-suite/assets/31506317/2bd4c82c-918a-4357-94f2-56508b9b6b3e)

**Comment by MiroslavProchazka** [comment]
Is fixed in Suite 24.3.4

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.3.4 (8aa83165e83ecb6d9456d44727f64f76793327b2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.4 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: BridgeTransport 2.0.33
