### ISSUE TITLE
Hide "All fees included" info in Trezor Suite - Buy

### ISSUE THREAD

**Issue by marek-andrsk** [trezor/trezor-suite#11783]
### Issue
In buy we’re showing to user information “Fees Included all fees” for all partners. This is not true anymore as some partners now include for example blockchain fee and some don’t.

### Solution
Before we design better solution and communicate with all partners to ideally provide separately offer and fees, we want to remove this information. Specific fees are still communicated in partner’s checkout.

![Snímek obrazovky 2024-03-27 v 17 41 34](https://github.com/trezor/trezor-suite/assets/6542812/62be79e6-7347-4a3d-a8e0-b0015241c0b6)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.4.0 (0072d9131891ee8335fa16d285e534e3f7767625)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
