### ISSUE TITLE
TS5 in mobile app

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#11788]
What needs to be done to make TS5 working with TSL.

Make necessary changes in the code to make TS5 working.

Product&Design
- [x] Replace images with TT to TS5
- [x] Collect places where we display device
- [x] adjust the FAQ question: (What version of Trezor device Firmware Trezor Suite Lite supports?):
add Trezor Safe 5: from version 2.7.2

Tracked in Notion task: https://www.notion.so/satoshilabs/Trezor-graphic-redesign-tasks-ac5ac14135c3430b9c3520371e463025

**Comment by tomasklim** [comment]
Please use device internal name for naming files.
![Screenshot 2024-05-08 at 13 07 06](https://github.com/trezor/trezor-suite/assets/33235762/e2d7b56c-047f-4eb4-a479-7173378e31dd)
