### ISSUE TITLE
Coming out of airplane mode: all backends are down

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#11786]
**Describe the bug**

**Info:**

-   Mobile Suite Version: 24.4.0 d5077fc
-   OS: Android, 13

**How to reproduce**

1. Run app w/ graph
2. Go to airplane mode
3. Refresh graph
4. Leave airplane mode
5. Refresh graph

**Expected behavior**
No error

**Screenshots**

https://github.com/trezor/trezor-suite/assets/216917/9e665ff9-33d0-4384-bff3-d7819310795b

**Related**
https://github.com/trezor/trezor-suite/pull/11642

**Comment by mnuky** [comment]
duplicate of https://github.com/trezor/trezor-suite/issues/11153
