### ISSUE TITLE
Invity Trade values are also hidden with "Hide balance" button

### ISSUE THREAD

**Issue by evgenysl** [trezor/trezor-suite#11798]
**Describe the bug**
When using **Hide balance** button, Invity's **Trade** section gets affected also.

**Steps to reproduce:**
1. Click **Hide balance** button
2. Go to **Trade** menu -> Buy -> select amount -> Compare offers
3. Observe **Invity** providers offers BTC value is also hidden

**Info:**
 - Same on production Suite
 - Suite version: desktop 24.3.3 (48fda1977950f0fa25b14a739f2289af6cbe87d3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.3 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36

**Expected result:**
Trezor Suite wallet BTC balance is hidden, but Invity's trade values are show to the user.

**Screenshots:**
<img width="1494" alt="Screenshot 2024-03-27 at 12 35 07" src="https://github.com/trezor/trezor-suite/assets/63164324/9f70800d-c59a-45b7-b612-6c0120560b1f">

**Comment by MiroslavProchazka** [comment]
Fixed in 24.8.1 
<img width="1078" alt="image" src="https://github.com/user-attachments/assets/aa1d4b66-08cb-4513-89f7-156787f8e7a3">

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/user-attachments/assets/ada66707-e053-40da-b671-6abbb07bdaf2)



**Info:**
 - Suite version: desktop 24.8.2 (96e583538c6a30e010a81346d1251f3246cb1def)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.32
