### ISSUE TITLE
Settings > Coins: Remove [Activate coins] button

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#11836]
Please remove the button, it damages the layout between Coins and Test Coins and it is not needed, as there's another button with the same function in the Accounts menu, where i§s the only place where the button has any value.

![Image](https://github.com/trezor/trezor-suite/assets/88533514/e9df1905-743a-4cba-95f4-b3a0ceac5680)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.4.0 (0072d9131891ee8335fa16d285e534e3f7767625)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
