### ISSUE TITLE
Suite no longer shows if address is correct in send form

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#11834]
**Describe the bug**
Suite no longer shows if input address is correct, only shows if it is not correct. Green tick is present in 24.1.x version but not after the "empower".

**Steps to reproduce:**
1. Input correct address into send form
2. No green tick is present if the address is correct

**Info:**
 - Suite version: desktop 24.4.0 (467aad84e0c1d1282a0afea997837adb6c489a41)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.4.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32

**Expected result:**
A green tick should be shown when correct address is pasted into the send form.

**Actual result:**
No green tick is shown when correct address is pasted, only red text is shown when address is incorrect.

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/48477147/e0facb5e-7935-4789-81d6-5e19ca4651ae)
![image](https://github.com/trezor/trezor-suite/assets/48477147/9d6f4a32-79e3-45b9-96dd-b7d268960d1d)
Version 24.1.2
![image](https://github.com/trezor/trezor-suite/assets/48477147/d1b5742f-1de9-4588-93b0-f4891fb76a3e)

**Comment by Hermez-cz** [comment]
The tick should never been shown, it mioght imply something like you're sending it to a "correct" address while you could have some other address in mind or so (beyond address format).
