### ISSUE TITLE
Fix no spacing in graph balance

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#11844]
No space between fiat value and time of graph point selected. 

**Expected behavior:** There should be space between and fiat value should be aligned properly.

![image](https://github.com/trezor/trezor-suite/assets/36101761/3046da4c-2b8d-4dcf-9c56-cd7bffdc44dc)

**Comment by bosomt** [comment]
**QA OK**

Android and iPhone 
24.4.1 / https://github.com/trezor/trezor-suite/commit/9e244b52146bfac1b93764d2021024f1e180ead4
