### ISSUE TITLE
Adding BTC Taproot account shows an error

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#11857]
**Describe the bug**
Syncing BTC taproot account shows an error in Suite Lite.

**Info:**

-   Mobile Suite Version: 24.3.1 and 24.4.1 
-   OS: iOS and Android

**How to reproduce**

1. Go to Portfolio tracker
2. Sync coin and select BTC
3. Scan taproot XPUB
4. Continue to add coin and Suite Lite shows an error

**Expected behavior**
Taproot account can be added in Portfolio tracker

**Video**

https://github.com/trezor/trezor-suite/assets/48477147/4db42a2f-937d-4a89-939f-7b66fad2b386

**Comment by matejkriz** [comment]
The error is `Descriptor cannot be parsed: tr([5c9e228d/86'/0'/0']xpub6Bw885JisRbcKmowfBvMmCxaFHodKn1VpmRmctmJJoM8D4DzyP4qJv8ZdD9V9r3SSGjmK2KJEDnvLH6f1Q4HrobEvnCeKydNvf1eir3RHZk/<0;1>/*)#9thz2a5h` and come from https://github.com/trezor/trezor-suite/blob/develop/packages/utxo-lib/src/derivation.ts/#L101 cc @marekrjpolak

**Comment by bosomt** [comment]
**QA OK**

- iPhone 11
- version 24.4.0 commit 26df2f2

**Comment by cerebrux** [comment]
Today I tried to add a taproot and got an error "Invalid Public address" (XPUB)

- iPhone X
- version 25.1.2 commit: 06c04e9
