### ISSUE TITLE
View only - store the data

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#11852]
The actual implementation of storing wallet's data.

- [x] design the shape of data, take into account current&future desktop implementation
- [x] implement remembering the wallet
- [x] implement wallet forgetting

> ⚠️ Graph time ranges are not migrated, so with update to 24.5.1 users will lost selected time ranges, but from then on, they'll be persistent again.

**Notes for QA**
- It would be great to test migration from previous app versions - user should not loose his portfolio tracker accounts.
- Not sure if it makes sense to test this separately – I guess it makes sense to test view-only as a whole feature at once?

**Comment by bosomt** [comment]
**QA OK**

- there was one stored device from previous version, imported one more device, updated, both present
- it will be retested on production wallet during upgrade
- needs to be added to release sanity tests 

**info**
- tested on nothing phone 1  android 14
- version  24.5.0 (246) Last commit hash: dd16bcf5a9df09c85af270cc7dbe5d10f92414fa

**Comment by STew790** [comment]
**QA OK**

Tested on production as well 24.4.2 > 24.5.1 

Redmi Note 9 Pro Android 12
