### ISSUE TITLE
View only - Settings: full UI

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#11853]
- [x] Devices overview
  -  [x] Not Set yet 
  -  [x] Other set
  -  [x] Empty state
  -  [x] Nothing connected, view only only
- [x] Removal
- [x] How it works explanation

<img width="250" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/14128e96-2e4f-434b-8bfe-2e66ba7a73a2">
<img width="250" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/5dc72650-7d50-4718-ba60-c3e981070a9c">
<img width="250" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/349f5924-8cb8-45b8-8fab-76955bbe0408">
<img width="250" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/d7d65461-c965-4983-87e5-bd1890af37e7">

**Comment by vytick** [comment]
wip design with passphrase from @shenkys 

![Image](https://github.com/trezor/trezor-suite/assets/2011829/6a5e4cd3-1467-4cab-9c36-b7034fb83ee6)

**Comment by vytick** [comment]
Updated visual including passphrased wallets:
<img width="250" src="https://github.com/trezor/trezor-suite/assets/2011829/792e71c6-e9b4-4ecc-b60b-17418352e59b">


[figma](https://www.figma.com/file/mmDnYtctfjnreWhTjLfeQH/Passphrase?type=design&node-id=0-1&mode=design&t=LCdcedqw68hAtS6v-0)

**Comment by STew790** [comment]
I just want to be completely sure that this is OK, I can still see the last pointed dot on the graph for a split second before I point in a different place on the graph and its persistent through wallets. See video:

https://github.com/trezor/trezor-suite/assets/48477147/a8065bb0-854c-483c-a828-26e70159605d

**Comment by STew790** [comment]
**QA OK**

24.5.1 https://github.com/trezor/trezor-suite/commit/319a98a62131c0d0ddd2eb238cb8530a540764a3
