### ISSUE TITLE
Been installing the same POLYGON update about 3-4 times per PC

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#11866]
`"The Polygon (PoS) network, along with its native currency MATIC, has joined the EVM compatible networks in Trezor Suite. This integration expands the ecosystem, offering more options for our users."`

Disgusting altcoin promotion.

Doesn't seem like you know how to write changelogs. 

How are we supposed to know we're not installing the same updates many many time if the update is about the same Polygon shilling?

**Comment by MiroslavProchazka** [comment]
Hey, thanks for the feedback. I know that it might be frustrating to see the same changelog several times. We were fixing a lot of bug fixes lately, namely:

- Fixed payload error while hovering over the Portfolio graph
- Fixed an error on discovering some Taproot addresses
- Fixed an error while adding ETH token
- Fixed an timeout error while doing wallet backup

Unfortunately, the Bug fixes section is at the end of the changelog, so it is not visible for first sight that there is some change.
