### ISSUE TITLE
Device renders refresh - custom for each device type

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11880]
**Do not disconnec**t - dont-disconnect-trezor-t3t1.png / dont-disconnect-trezor-t3t1@2x.png
**Device confirm** - device-confirm-trezor-t3t1.svg
**Device icon** - ts5.svg
**Device render** - ts5.png
**Trezor unknown** - trezor-unknown.png / trezor-unknown@2x.png
**Bridge check** - bridge-check-trezor-t3t1.svg

**Comment by STew790** [comment]
**QA OK**
Done as part of https://github.com/trezor/trezor-suite/issues/11841
