### ISSUE TITLE
View only - popup on device connect

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#11886]
When a user connects a Trezor and has never clicked "Skip", show modal that allows to turn on view-only mode right away.

It should be shown after "biometrics enable" modal (after onboarding) or after Connecting screen on subsequent runs of the app.

If user taps enable - we offer it again with new devices and passphrase wallets. 

If user taps skip  - we globally stop offering this feature. Save this in form of timestamp for possible timeout of this decision

<img width="325" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/b65d94ec-3747-48a8-b392-425f40770df2">

[Figma](https://www.figma.com/file/KvbZGG16li6BA90Xtpf0BP/Device-interaction?type=design&node-id=970-17549&mode=design&t=KKhTAXTh0Wmu2KU9-4)

**Comment by bosomt** [comment]
**QA OK**


- 24.4.0 3550932
- Android 14

**Comment by matejkriz** [comment]
@shenkys mentioned that he saw the popup over connecting screen. I'll double check that.

**Comment by matejkriz** [comment]
fixed in https://github.com/trezor/trezor-suite/pull/12364, it is no more appearing over connecting screen

**Comment by matejkriz** [comment]
Popup is now shown only after discovery finishes, see https://github.com/trezor/trezor-suite/issues/12454

**Comment by STew790** [comment]
**QA OK**

24.5.1 https://github.com/trezor/trezor-suite/commit/319a98a62131c0d0ddd2eb238cb8530a540764a3

**Comment by STew790** [comment]
**QA NOK**

I am sorry I have no idea how I missed it but clicking OUTSIDE of the modal actually freezes the app until you either disconnect your device or you kill the app.

24.5.1 https://github.com/trezor/trezor-suite/commit/319a98a62131c0d0ddd2eb238cb8530a540764a3

**Comment by matejkriz** [comment]
@STew790 fixed by https://github.com/trezor/trezor-suite/pull/12545 (in develop so far)

**Comment by STew790** [comment]
**QA OK**

Indeed fixed in develop.

24.5.0   45e4505
