### ISSUE TITLE
Update AlertBox visual and layout in Card component

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#11889]
[Figma](https://www.figma.com/file/KvbZGG16li6BA90Xtpf0BP/Device-interaction?type=design&node-id=1514-12455&mode=design&t=JziGq5qwGwNjTE9B-0)

Update AlertBox UI

- change text color, bg color, border and radius

- layout differently in Card component according to new design (4 px padding from top and sides)

new design:
<img width="308" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/92bcbafe-206f-4a60-a1c1-313bee04ebe3">

current state:
<img width="308" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/eea7a021-9a5e-4e46-93e6-a5d55fda8c2d">

**Comment by bosomt** [comment]
**QA OK**

- 24.4.0 commit 3550932
- android 14 nothing phone 1
