### ISSUE TITLE
View only - receive disconnected

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#11887]
[Figma](https://www.figma.com/file/KvbZGG16li6BA90Xtpf0BP/Device-interaction?type=design&node-id=970-17554&mode=design&t=KKhTAXTh0Wmu2KU9-4)

Warn user that receive address can't be verified without connected Trezor.

<img width="305" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/20cdfb8e-875f-4132-bf26-799a7acf46ed">
<img width="302" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/41afc5be-71dc-4f24-a926-2a7ad4eaf3ca">

**Comment by bosomt** [comment]
**QA NOK**

missing continue without device modal



https://github.com/trezor/trezor-suite/assets/31506317/57d66481-0063-487b-bdc8-230cb31c9724


- 24.4.0 dev version 3550932
- Android 14

**Comment by juriczech** [comment]
I didn't realize that you couldn't get into the state where this issue would be testable. Testing is blocked by https://github.com/trezor/trezor-suite/issues/11852, retest when closed please.

To test: 
- device should be remembered and disconnected
- then it will be possible to test the flow visible in issue description
