### ISSUE TITLE
Handle connection to Trezor Suite web and connected Trezor

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#11896]
We want to achieve that when user connects unitialised Trezor and we linked him to Trezor Suite web on the mobile device, mobile app does not steal the session. User can do the whole onboarding on web with Trezor Suite Lite installed. And that user can use the Trezor Suite web without App stealing the session.

_1. System message to open app when Trezor is connected remains as it is._

_2. If Suite Lite missing USB persmission for the connected Trezor, new system message will appear right after user opens the app_
- If the user grants permissions (opens) another application (3rd party, web) or none from the original system message to open app, a new system window for granting USB permissions pops up right after user opens the Suite Lite. 

_3. User connects the uninitialized device_
- when user connects unitialized device, we display him message
- Uses is informed he can proceed to Trezor Suite Web 
- If user clicks on the link, he is redirected to Trezor Suite Web and the device is "released" from the app

_4. **New requirement**: After FW installation via Web Suite_
- user is possibly navigated back to Suite Lite app by system message
- We have a new alert for that case with better explanation where to continue
[FIGMA](https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?node-id=687-8798&t=UKVccuAiW7tl0r0H-11)

___

[Figma here](https://www.figma.com/file/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?type=design&node-id=223-7882&mode=design&t=lWTn9tT6dPpKQhGI-11)

___

- New uninitialized device screen: 

**Current approved implementation**
<img width="230" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/fc0bddc7-0821-4cdf-bca1-70822e77329a">

**Original design**
<img width="230" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/e975391d-88ba-4cea-85d5-357a85dc4597">

**After FW installation, still without seed** NEW
<img width="230" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/433f7831-462a-46ea-b793-9bbeb9a69b34">
___

**Comment by matejkriz** [comment]
Internal discussion - report of the issue https://satoshilabs.slack.com/archives/C04RE4DL7PD/p1712833931062419

**Comment by matejkriz** [comment]
This issue affects initialized devices too, but major issue is the onboarding.

**Comment by shenkys** [comment]
Design done. [Linked here](https://www.figma.com/file/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?type=design&node-id=223-7882&mode=design&t=lWTn9tT6dPpKQhGI-11).

**Comment by matejkriz** [comment]
Handling declined USB permissions extracted in new issue https://github.com/trezor/trezor-suite/issues/13156

**Comment by STew790** [comment]
**QA OK**

I tried this with all the devices and I was able to get from Suite lite to web version and install firmware and do onboarding.  

24.6.0 https://github.com/trezor/trezor-suite/commit/814ab5d0df52939057bfa7643e7c0a83012e86f7

**Comment by STew790** [comment]
~~QA OK~~

~~I tried this with all the devices and I was able to get from Suite lite to web version and install firmware and do onboarding.~~

~~24.6.0 https://github.com/trezor/trezor-suite/commit/814ab5d0df52939057bfa7643e7c0a83012e86f7~~

Sorry, I accidentally wrote this to a wrong issue...

**Comment by matejkriz** [comment]
New requirement: After FW installation via Web Suite, user is possibly navigated back to Suite Lite app by system message. We have a new alert for that case with better explanation where to continue:

<img width="300" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/433f7831-462a-46ea-b793-9bbeb9a69b34">

[FIGMA](https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?node-id=687-8798&t=UKVccuAiW7tl0r0H-11)

**Comment by evgenysl** [comment]
**QA OK** on 24.7.1  (61) 

![Screenshot_20240711_171739_Trezor Suite Lite](https://github.com/trezor/trezor-suite/assets/63164324/0a967bf9-8624-4c56-860a-a226f25f6903)
