### ISSUE TITLE
View only - wallet switcher

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#11892]
[Figma](https://www.figma.com/file/mmDnYtctfjnreWhTjLfeQH/Passphrase?type=design&node-id=2146-52545&mode=design&t=byABEIZniotrg0l6-0)

Update wallet switcher visual to show view only devices correctly

- [x] Generic device icon changed to model-specific
- [x] Show current device connection state
- [x] Show/hide device selector on button tap
- [x] Show all devices including connection state (view only) 
- [x] Make device selector slide out/in animated
- [x] Show all wallets for current device
- [x] Hide` Open passphrase` button behind feature flag and make it disabled during discovery
- [x] New connected state for View only settings harmonised with new design
- [x] New visual for current device/wallet when closed manager
 
<img width="805" alt="image" src="https://github.com/trezor/trezor-suite/assets/2011829/42bb7c04-e9e4-4042-ac6d-1ac553659fe0">

These enhancements will be done in followup issue #12421
- Show wallet fiat amount
- Scrolling wallets to fit size

**Comment by matejkriz** [comment]
DEV QA NOK, there is a weird animation glitch when opening the wallet switcher while the Portfolio tracker is active.


https://github.com/trezor/trezor-suite/assets/3729633/0b82c3f5-7d61-4d61-b1ae-7d63f6475787

**Comment by STew790** [comment]
**QA NOK**
- https://github.com/trezor/trezor-suite/issues/11892#issuecomment-2127425888

**QA OK**
- icons according to device
- connection state shown correctly
- all devices shown on drop down
- device selector drop-down
- `Open passphrase` feature is behind feature flag

24.5.1 https://github.com/trezor/trezor-suite/commit/319a98a62131c0d0ddd2eb238cb8530a540764a3

**Comment by matejkriz** [comment]
The animation glitch is fixed on develop now by https://github.com/trezor/trezor-suite/pull/12544

**Comment by STew790** [comment]
The animation is indeed fixed in develop.

**QA OK**
