### ISSUE TITLE
Fiat rates are not calculated properly on CSV import

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11908]
1. Launch Suite 24.3.4
2. Connect your trezor
3. Set Application currency to USD 
4. Go to BTC account 
5. Open send dialog
6. Hit Import addresses form CSV
7. Import CSV file with different currencies 
8. Observe that the re-calculation to btc is correct on strings that contain same currency as the application default (in this case USD), and is not correct on any different currencies (for example CZK)

![image](https://github.com/trezor/trezor-suite/assets/152851523/a625647b-18d0-45f1-a7d8-1408e1b73bf2)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.5.0 (a33ad459d3d919d5b6ac4210c9d876298ee8947a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 2144x1206
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
