### ISSUE TITLE
Send dialogue of TEST coins design broken

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11915]
**Describe the bug**
Send dialogue of TEST coins design broken.
Same web and app version.

**Info:**
 - Suite version: desktop 24.4.1 (f4684c1893fe8b0f45c217837e2cbedaa6928d25)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="1406" alt="Screenshot 2024-04-08 at 8 45 37" src="https://github.com/trezor/trezor-suite/assets/31506317/e9fe8ebb-01cf-45af-a754-7b05a7d0ff99">

**Comment by MiroslavProchazka** [comment]
Should be fixed on develop by https://github.com/trezor/trezor-suite/pull/11899

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.4.0 (a880750a9e5878032860abf6ba70aeb0a8718094)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T1B1 1.12.1 bitcoin-only (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33
