### ISSUE TITLE
Token fiat value not hidden in Discreet mode 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11912]
**Describe the bug**
Token fiat value not hidden in Discreet mode 

**Info:**
 - Suite version: desktop 24.4.1 (f4684c1893fe8b0f45c217837e2cbedaa6928d25)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="272" alt="Screenshot 2024-04-06 at 8 11 03" src="https://github.com/trezor/trezor-suite/assets/31506317/76258b88-c15f-44d9-9c52-b80374f816dd">

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/3e8cef9d-7591-4485-b948-5f418df78038)

**Info:**
 - Suite version: desktop 24.4.2 (22d7c411755389aef139a5c705da2dda7f3e4af1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
