### ISSUE TITLE
Trezor suite - exchange currency bug

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#11927]
#  Wrong cryptocurrency symbol

## Behaviour
**Current result**: in modal window there is `BTC receive address`
**Expected result**: in modal window there should be `LTC receive address`
![image-20231208-124244](https://github.com/trezor/trezor-suite/assets/15160619/3a622e2f-2026-4c3d-8d8e-8cbf2f437819)
![image-20231208-113942](https://github.com/trezor/trezor-suite/assets/15160619/d3373c29-c893-4718-8635-00df48ccf901)

## Info:
Steps to reproduce (macOS, Trezor Suite - desktop version 23.12.1):

## Steps to reproduce the behavior:
1. Open trade section in Trezor suite 
2. Go to exchange section
3. Choose BTC x LTC pair and fill out desired BTC amount to exchange and choose offer
4. Here after clicking on “Confirm on Trezor” button in modal window there is mentioned, that its BTC, not LTC address
**Expected behavior**

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.5.0 (1a7ff332d4b1d3c128487964794663604502e1d7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
