### ISSUE TITLE
Address drop-down selector misplaced when opened during discovery

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11922]
**Describe the bug**
Address drop-down selector misplaced when opened during discovery

**Steps to reproduce:**
1. Start discovery of wallet
2. Navigate to `Sign and verify`
3. Open selector multiple times during discovery and wait till it finishes

**Info:**
 - Suite version: desktop 24.4.1 (f4684c1893fe8b0f45c217837e2cbedaa6928d25)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/9e95b7c6-d64d-41ad-b9f7-aba000166b48

**Comment by MiroslavProchazka** [comment]
So this only occurs when you open sign and verify addresses during discovery? Is it happening also after you finish the discovery?

**Comment by bosomt** [comment]
Only during discovery, so its edge case, but its still happening on develop / i just checked/

**Comment by peter-sanderson** [comment]
I think this was already fixed by https://github.com/trezor/trezor-suite/pull/11825

**Comment by bosomt** [comment]
**QA OK**

I'm not able to reproduce this issue anymore

**Info:**
 - Suite version: web 24.5.0 (245ca14279a6edd46d5737dcef86f73a700e1d2a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
