### ISSUE TITLE
Passphrase: Confirm on Trezor popup

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#11938]
UI only task. Create a popup for informing user he needs to confirm passphrase on device. No functionality required here.

[Figma](https://www.figma.com/file/mmDnYtctfjnreWhTjLfeQH/Passphrase?type=design&node-id=911-48465&mode=design&t=Rcy0avN3Fq6VVaIk-0)

![image](https://github.com/trezor/trezor-suite/assets/36101761/d4c6e575-ec8c-478a-a1fd-98febf4796fb)

**Comment by STew790** [comment]
**QA OK**

![image](https://github.com/trezor/trezor-suite/assets/48477147/cc47b34a-fbbe-4674-be93-abe671042124)

24.5.0 0ff1770
