### ISSUE TITLE
Add colors for yellow and red button

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#11931]
We're extending button variants with following colors: 
- red bold
- yellow bold
- yellow elevation 1
- yellow elevation 0

For these colors, we'll need following button colors:
- backgroundColor: background color of button
- onPressColor: background color of button when pressed
- textColor
- disabledTextColor

**Comment by shenkys** [comment]
Bold Yellow button: 
- Default = background/alert/yellow/bold
- Pressed = background/alert/yellow/bold-alt

Subtle Yellow button:
- Default = background/alert/yellow/subtle/on-elevation-1
- Pressed = background/alert/yellow/subtle/on-elevation-0

Bold Red button: 
- Default = background/alert/red/bold
- Pressed = background/alert/red/bold-alt
 
Bold Blue button
- Default = background/alert/blue/bold
- Pressed = background/alert/bold/bold-alt

Subtle Blue Button
- Default = background/alert/blue/subtle/on-elevation-1
- Pressed = background/alert/blue/subtle/on-elevation-0

**Comment by juriczech** [comment]
As discussed, colors might change again

**Comment by vytick** [comment]
Colors according to:
https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5BSuite%5D-Components?type=design&node-id=1-1238&mode=design&t=n2c49jnQ9yszwneH-0
