### ISSUE TITLE
Warning in coinjoin receive tab has unexpected design

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11948]
**Describe the bug**
Warning in coinjoin receive tab has unexpected design, yellow color is probably not used anywhere else

**Steps to reproduce:**
1. Add fresh coinjoin account
2. navigate to receive section

**Info:**
 - Suite version: desktop 24.4.1 (979558244707a3d9d577cf9afff6a860c48b137d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/31506317/2eaf089e-89b6-4701-b6ef-4ace92551296)

**Comment by bosomt** [comment]
ok it is used in different notification 

<img width="1164" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/d252327f-5f3f-47a9-ba1e-8cb36f834651">

**Comment by MiroslavProchazka** [comment]
@jvaclavik fyi, priority is to fix the button position and padding
