### ISSUE TITLE
Canceling/stopping Coinjoin freezes Suite

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#11950]
**Describe the bug**
When I start Coinjoin and then I stop it and try to go to "Send" of the same Coinjoin account for example, the Suite freezes completely. In the console I can see:
`2024-04-10T08:56:48.310Z - WARN(content): Unresponsive`
And I have to force quit the app.
My console was also flooded with this after quitting the app:
![image](https://github.com/trezor/trezor-suite/assets/48477147/954a2071-97d9-4ffd-be63-908e5be1956d)

It is not present in the production app.

**Steps to reproduce:**
1. Start Suite
2. Add Coinjoin account
3. Start Coinjoin
4. Go to "Send" form of the Coinjoin account for example
5. Suite freezes

**Info:**
 - Suite version: desktop 24.4.1 (979558244707a3d9d577cf9afff6a860c48b137d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32

**Expected result:**
I can stop the Coinjoin process.

**Actual result:**
Suite freezes after stopping the Coinjoin process.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.4.1 (1c10bfbdbea0d07f80d9398b3935b8345079c295)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
