### ISSUE TITLE
Allow passphrase to be inserted from device

### ISSUE THREAD

**Issue by stevexyz** [trezor/trezor-suite#11959]
**Design:** Allow input of passhrase for hidden wallet directly into the device (e.g. Trezor One) will allow the passphrase not to be exposed on the PC/phone that might have been compromized (e.g. with a keylogger)

**Spec:** An example of input for devices with two buttons can be: scroll thru all letters/numbers/symbols thru left and right buttons, and select one long pressing right button, and delete one long pressing left button

**Note:** This can be made optional from Trezor Suite interface to have an additional layer of security even if less user friendly

**Comment by Hannsek** [comment]
Passphrase input on device is possible on TT and TS3. We won't implement it for T1.
