### ISSUE TITLE
Passphrase: Form UI

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#11979]
Base form UI so we can start working on accessing hidden wallets using this form.

![image](https://github.com/trezor/trezor-suite/assets/36101761/3d94ee9a-ea1a-4053-b72c-b0ffdd5f79e9)

**Comment by STew790** [comment]
**QA OK**

![image](https://github.com/trezor/trezor-suite/assets/48477147/d46cd687-a847-4482-a85e-bb97ecf06c27)

24.5.0  0ff1770
