### ISSUE TITLE
View only - handle impossible Add account without device

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#11977]
If device is remembered and disconnected, it's not possible to add new coin/account. In that case, `+` buttons remains there (on both My assets and Receive tabs) but instead of adding new coin/account it shows this explanation "alert".

- We can use Alert component for it but make icon optional.

<img width="337" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/85b77a88-a27b-47d7-a947-3e26b6fd55e1">

**Comment by bosomt** [comment]
**QA OK**

- 24.4.0 commit 3550932
- Android 14 , Nothing phone 1
