### ISSUE TITLE
Passphrase: Handle empty passphrased wallet

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#11973]
When accessing passphrased wallet which is empty, we want to make sure user knows what he's doing and double-check.

![image](https://github.com/trezor/trezor-suite/assets/36101761/d4f2e989-94dd-4a1d-a5d9-4b16c0bde017)

[Figma](https://www.figma.com/file/mmDnYtctfjnreWhTjLfeQH/Passphrase?type=design&node-id=911-48576&mode=design&t=TLzwBFP7RNxuSMHY-4)

**Comment by STew790** [comment]
**QA OK**

Tested together with https://github.com/trezor/trezor-suite/issues/12207
