### ISSUE TITLE
Update hologram picture for TS3

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#11985]
We are updating TS3 holograms. Please update the hologram picture in tooltip in the pre-onboarding security check. 

![Screenshot 2024-04-11 at 17 13 15@2x](https://github.com/trezor/trezor-suite/assets/75733878/e2d1a4ec-ad9d-45aa-929f-d1d7f822f39f)

Use this picture please. I made it in the same style as the current one. https://drive.google.com/file/d/1pZoJkJY748zHyOclE7O15-PzR-jidY1b/view?usp=sharing

For the next couple of months users will be receiving devices with both old and new holograms. For that reason I think it would be ideal to display both old and new - one above the other. If you are going to display only one, please make it the new one.

**Comment by MiroslavProchazka** [comment]
@tomasklim please implement this together with new placeholders for t3t1.

**Comment by MiroslavProchazka** [comment]
My recommendation: 

put the original / new seal next to each other in one pic, similar to this. Please put the text above the picture in the code, so it can be translated. 
<img width="336" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/8eb003e5-9da1-4ad7-a6c6-9c722d382fc4">

Thanks!

**Comment by MiroslavProchazka** [comment]
Original pic of the seal here - https://trezor.io/support/a/is-my-device-safe-to-use 
New pic of the seal here - https://drive.google.com/file/d/1pZoJkJY748zHyOclE7O15-PzR-jidY1b/view?usp=sharing

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/08be21a1-ca47-42d9-9c94-02dba97dade4)

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
