### ISSUE TITLE
Cardano wallet not visible between Suite and AdaLite/Yoroi

### ISSUE THREAD

**Issue by mkoura** [trezor/trezor-suite#11981]
**Describe the bug**
I have Trezor Safe 3. My Cardano wallet that I created in Trezor Suite is different from the one created in Yoroi/AdaLite.

Both hidden wallets have the same passhprase. I can reliably access both wallets. I tested it on two different computers several times, and the behavior is consistent. I can see the same wallet in AdaLite and Yoroi, but the wallet in Suite is different. I can verify address correctness on Trezor in both Suite and AdaLite/Yoroi. The derivation paths reported by all three tools are the same: `m/1852'/1815'/0'`
My mnemonic has 24 words.

**Info:**

-   Remembered Wallet: yes
-   Suite Version: v24.3.4
-   OS: Linux, Fedora 38
-   Bridge: 2.0.27-1
-   Firmware Version: Safe 3, 2.7.0

**How to reproduce**

1. Go to Trezor Suite
1. Access hidden Cardano wallet, confirm passphrase on Trezor
1. Check wallet address, derivation path, balance, etc.
1. Disconnect Trezor, close Suite
1. Open AdaLite
1. Connect Trezor
1. Export public key, enter passphrase for hidden wallet, confirm passphrase on Trezor
1. Check wallet address, derivation path, balance, etc.

**Expected behavior**
The same Cardano wallet can be accessed with Suite and AdaLite/Yoroi

**Comment by mkoura** [comment]
Update: I can now see my AdaLite wallet under "Legacy accounts". So I guess there is some difference in the derivation paths between AdaLite and Suite.

**Comment by MiroslavProchazka** [comment]
@marekrjpolak can you confirm which derivation path Suite uses please?

**Comment by Hannsek** [comment]
Trezor Suite currently supports 3 derivation paths for cardano. The one from Adalite is supported.

**Comment by Hannsek** [comment]
But 2 of them are supported only for recovery.
