### ISSUE TITLE
Security cards not properly aligned

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12007]
<img width="1123" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/6c3df596-0149-4339-8e73-602c15b01c66">

**Comment by evgenysl** [comment]
Bug is present only when some security check mark is not done.
When it's completed, alignment is correct:
![Screenshot 2024-04-16 at 10 29 26](https://github.com/trezor/trezor-suite/assets/63164324/3dbdf57e-3b3b-48fe-a61b-c28aa045b3bd)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.5.0 (d599391ce8467166f0ffd6f3f1fb0abd35c6bb91)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: 
 - Transport: BridgeTransport 2.0.33
