### ISSUE TITLE
View only [last] - delete feature flag or add migration

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#12013]
when we publish it, we need to either delete the feature flag completely or add a migration to make it appear to existing users

**Notes for QA**
View only feature is now turned on for everyone, even for those updating from 24.4 version.

**Comment by STew790** [comment]
**QA OK**
Updated the app and I got the "View only" modal.

24.5.1 https://github.com/trezor/trezor-suite/commit/319a98a62131c0d0ddd2eb238cb8530a540764a3
