### ISSUE TITLE
Alert sheet layout glitch

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#12035]
**Describe the bug**
Alert sheet layout is broken. The pictogram is not centered.

**How to reproduce**
Open any alert sheet.
**Expected behavior**

**Screenshots**

![Screenshot 2024-04-16 at 15 04 53](https://github.com/trezor/trezor-suite/assets/26143964/c952c93d-c27f-42bb-a2ac-ee6d567ddb8c)

**Comment by bosomt** [comment]
**QA OK**

- version 24.4.0 c8e7d2e
- Android 14 , Nothing phone 1
