### ISSUE TITLE
Staking: Clarify of the role of Everstake

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#12042]
### Problem
Users are learning about Everstake for the first time as they attempt to stake in Trezor Suite

It provides a point of friction as a new and unknown entity is introduced during the happy path

[Captured feedback](https://miro.com/app/board/uXjVMx7x5CQ=/?moveToWidget=3458764584076718837&cot=14)

![Image](https://github.com/trezor/trezor-suite/assets/216917/f5396e4d-1b49-4470-b5e5-6f48b9108ab3)

### Trezor & Everstake
Introduce Everstake as the [third column](https://www.figma.com/file/0Kz3w6WDlvQm62RjOm87na/Staking?type=design&node-id=4826-55546&mode=design&t=vLhSUH42EdyibprV-4) on the staking landing screen.

![Image](https://github.com/trezor/trezor-suite/assets/216917/7d41d47a-1a8b-4ace-98d3-b305a19d9eff)

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/392c534c-0f08-41c4-98d5-69461561c713)
![image](https://github.com/trezor/trezor-suite/assets/48477147/a4a7aa71-4a2d-4630-99e3-be7bfae06625)

**Info:**
 - Suite version: desktop 24.5.0 (a54e74f6dc7655fd94fc10203562226e0dc5527d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.5.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
