### ISSUE TITLE
Staking: Instant staking success

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#12047]
## User story
As a staker
I want to stake Ethereum
So that I can earn a return on my ETH

## Acceptance Criteria

Background: Only visible whilst Trezor Suite is open during transaction switches from pending to confirmed.

Given I have staked ETH
When the transaction confirms
Then I should see 'You've instantly staked x ETH. The remaining ETH is staked with x days'

## [Screens](https://www.figma.com/file/0Kz3w6WDlvQm62RjOm87na/Staking?type=design&node-id=4870-10560&mode=design&t=vLhSUH42EdyibprV-4)

![Image](https://github.com/trezor/trezor-suite/assets/216917/ec90abe5-c9bb-433a-bfc8-6fe0246ae37e)

**Comment by tomasklim** [comment]
https://satoshilabs.slack.com/archives/C0543DJBK0C/p1715258808315629?thread_ts=1714472038.012399&cid=C0543DJBK0C

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/user-attachments/assets/8079afd5-9135-443f-8b82-90afd1def440)

**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
