### ISSUE TITLE
Staking: Align 'total stake pending' with staked/rewards/unstaking totals

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#12045]
## Problem

Users miss the pending total stake tally.

![Image](https://github.com/trezor/trezor-suite/assets/216917/b473a2bd-46f3-4663-a813-c9d3f9c37e7a)

## Alignment
Align pending total stake tally with other tallies. **All tallies to be trimmed to 5 decimal places.**

![Image](https://github.com/trezor/trezor-suite/assets/216917/5d081768-06f7-4263-87b6-2e53dff8ca5b)

**Comment by tomasklim** [comment]
@sime trimmed with `...`?

`1.1234567` -> `1.12345` or `1.12345...`?

How about tooltip with whole amount on hover

**Comment by tomasklim** [comment]
![Screenshot 2024-04-25 at 17 17 22](https://github.com/trezor/trezor-suite/assets/33235762/aa12e2fa-a6e9-4506-b116-bc91d40e942e)

**Comment by sime** [comment]
> @sime trimmed with `...`?
> 
> `1.1234567` -> `1.12345` or `1.12345...`?
> 
> How about tooltip with whole amount on hover

Trimmed with no ellipsis. Tooltip is nice if possible!

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/b4e3abea-6624-4747-b90c-f4a5c335b0eb)

**Info:**
 - Suite version: desktop 24.5.0 (a54e74f6dc7655fd94fc10203562226e0dc5527d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.5.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
