### ISSUE TITLE
Coinmarket - payment method filter

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#12048]
# Info
Add payment method filter above list of offers in Buy flow in Trezor Suite.
- Default payment method will be “All payment methods”
- Filter will show payment methods available for current list of offers (only offers without error)
- Persist selected payment method - if there is no offer, fallback to default

# Design
![image](https://github.com/trezor/trezor-suite/assets/15160619/81bb497f-e5db-4767-ad62-15bb6fcd98ec)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.5.0 (1a7ff332d4b1d3c128487964794663604502e1d7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
