### ISSUE TITLE
Coin control closes itself when opened for the first time

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#12057]
**Describe the bug**
When you open the coin control tab in send form for the first time, it closes itself after like 1-2s. When I open it again, it stays opened correctly.

**Steps to reproduce:**
1. Go to any BTC account
2. Go to send form
3. Click on Coin control tab
4. The tab closes itself

**Info:**
 - Suite version: desktop 24.4.2 (22d7c411755389aef139a5c705da2dda7f3e4af1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32

**Expected result:**
Coin control tab stays opened when I click on it.

**Actual result:**
Coin control closes itself when opened for the first time

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/48477147/726e7995-38a2-4308-8dc0-9a553ad95229

**Comment by MiroslavProchazka** [comment]
Is this happening just on the CJ account, or does it show similar behavior on other account types as well?"

**Comment by hynek-jina** [comment]
It happens on other accounts as well

**Comment by peter-sanderson** [comment]
I was able to reproduce it when discovery was still running. When discovery finished, the dialog closes.

Was it this case? (Its not clear from the video)

**Comment by peter-sanderson** [comment]
It seems that problem was caused by this change. https://github.com/trezor/trezor-suite/pull/11281/files#diff-7eb64e3e1e5dbeb9de99bc8ce9b17f39a6f145145a03c63aae4d83057dd0ea93R336

It will trigger the effect by change in `composeDraft` that is caused by change in `account` in `useSendFormCompose`

**Comment by STew790** [comment]
> I was able to reproduce it when discovery was still running. When discovery finished, the dialog closes.

> Was it this case? (Its not clear from the video)

No, the discovery was already finished when it happened. At least for me on the CJ account.

**Comment by MiroslavProchazka** [comment]
@STew790 can you please try to replicate it in production? I can't trigger the bug behavior.

**Comment by STew790** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
