### ISSUE TITLE
Deploy Storybook

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#12051]
Deploy Storybook nightly to sldev. This makes the components available to devs, designers and product managers without having to run Suite locally.

Before the URL migration, it could be found at https://suite.corp.sldev.cz/components/develop/, deployed by [this job](https://github.com/trezor/trezor-suite/blob/89c1cd5d8c2afe0bdac9d73cdf100ccaaa0b42f9/ci/deploy.yml#L144).

To start Storybook locally, run `yarn workspace @trezor/components storybook`.

**Comment by vdovhanych** [comment]
This is done right?
