### ISSUE TITLE
Suite prompts you for a passphrase when sending SOL tx

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12052]
- Go to the Suite 24.2.4 
- Remember standard wallet with enabled SOL account
- Refresh Suite (or turn of/on) 
- Proceed to send SOL Tx
- Observe modal asking you about Passphrase 

https://github.com/trezor/trezor-suite/assets/152851523/051b0515-6ec6-47c6-a640-857f032f434b

**Comment by AdamSchinzel** [comment]
Hmm I'm not able to reproduce this behavior

**Comment by STew790** [comment]
**QA OK**
No passphrase prompt shown.

**Info:**
 - Suite version: web 24.6.0 (d5b518f0f76f227a66ea0b0b7a4c7763c8bee2bf)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 3.0.0
