### ISSUE TITLE
Device should report that it has security chip

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12078]
Would be nice to be able to do decisions in the app based on device properties.

It would be future proof for new devices

https://github.com/trezor/trezor-suite/blob/6371d1044399e4106d99ff39b7e6073c5f43c761/packages/suite/src/config/onboarding/steps.ts#L36-L41

**Comment by Hannsek** [comment]
Shouldn't this be in fw repo?

**Comment by komret** [comment]
Requested in https://github.com/trezor/trezor-firmware/issues/3966, but looks like not planned :/
