### ISSUE TITLE
Device should report that it offers tutorial

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12079]
Would be nice to be able to do decisions in the app based on device properties.

It would be future proof for new devices

https://github.com/trezor/trezor-suite/blob/6371d1044399e4106d99ff39b7e6073c5f43c761/packages/suite/src/config/onboarding/steps.ts#L42-L47

**Comment by komret** [comment]
Requested in https://github.com/trezor/trezor-firmware/issues/3966.
