### ISSUE TITLE
Bug: Infinite graph loading after flight mode

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#12109]
Never ending loading on dashboard while in flight mode or offline

**Info:**

-   Mobile Suite Version: version/commit
-   OS: android, 24.4.1 and later

**How to reproduce**

1. Add account to watch in portfolio tracker mode or connect device
2. Put phone to flight mode
3. Refresh graph on home
4. Infinite loading with text **Retrieving data...** appears and never goes away

**Expected behavior**
Connection should fail with error and after going back online and refresh it should recover and fetch data

**Screenshots**
<img src="https://github.com/trezor/trezor-suite/assets/2011829/04e18629-7b2c-4d78-9a8c-153cfacba72a" width=250 />

context in slack: https://satoshilabs.slack.com/archives/C04RE4DL7PD/p1713199343097829

**Comment by matejkriz** [comment]
fixed by https://github.com/trezor/trezor-suite/issues/12490
