### ISSUE TITLE
Disappearing zero while adding small amounts in send form

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12106]
https://github.com/trezor/trezor-suite/assets/152851523/20b64d81-83d2-45a0-a605-0d8cadc50bc9

While you will be at it, please also fix this thingy 

https://github.com/trezor/trezor-suite/assets/152851523/ecdcf266-bfc5-494a-bd1c-2bc592f17fdd

**Comment by peter-sanderson** [comment]
This is problem (only?) for Czech language. If you use English with `.` (dot) it works.

**Comment by STew790** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.5.0 (a54e74f6dc7655fd94fc10203562226e0dc5527d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.5.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
