### ISSUE TITLE
Change stellar-sdk dependency to @stellar/stellar-sdk

### ISSUE THREAD

**Issue by acharb** [trezor/trezor-suite#12100]
Hey Trezor team - we changed the stellar-sdk dependency to be under the @stellar scope, can you change the dependency here

https://github.com/trezor/trezor-suite/blob/62c48b2cf019528d31903dffe31fb8edf4f1a081/packages/connect-plugin-stellar/package.json#L27

it should be `@stellar/stellar-sdk` instead 
(see the deprecated package alert at the top of the [stellar-sdk npm page](https://www.npmjs.com/package/stellar-sdk?source=post_page---------------------------))

Otherwise projects using the old dependency will get an error

Thanks

**Comment by mroz22** [comment]
as long as @overcat approves, we can do I t :D

**Comment by overcat** [comment]
Hi @acharb, I agree with this point, should I create a PR or will you create one?

**Comment by acharb** [comment]
feel free! I'm not too familiar with the project. Thanks!

**Comment by overcat** [comment]
Hi @mroz22, I remember that we have already [completed](https://github.com/trezor/trezor-suite/commit/213043748ae35e2aacc0416d35c908c0b29509c2) the migration, now we just need to wait for the new connect-plugin-stellar to be released. May I ask when will the next release be?

**Comment by mroz22** [comment]
ah, true, I will do it soon

**Comment by MiroslavProchazka** [comment]
Hi @overcat , can you please check whether [this](https://www.npmjs.com/package/@trezor/connect-plugin-stellar?activeTab=dependencies) already contains the change? Thx

**Comment by overcat** [comment]
> contains the change

@MiroslavProchazka, yes, it contains the changes. Thanks!

Hi @acharb, can you try using @trezor/connect-plugin-stellar 9.0.3?

**Comment by acharb** [comment]
yup, that works

Thanks!

I'll close this ticket as resolved
