### ISSUE TITLE
Passphrase on receive

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#12132]
On remembered passphrase device, when reconnected, device won't ask for passphrase until receive address is requested. Handle passphrase request in that flow.

![Image](https://github.com/trezor/trezor-suite/assets/36101761/0e3d5386-f97a-4244-9c79-3415d57e808e)

https://www.figma.com/design/mmDnYtctfjnreWhTjLfeQH/Passphrase?node-id=2895-5652&t=WScMaNsEhAqbs34a-0

**Comment by shenkys** [comment]
Design note: 
- this will be done in the week of 29.4-3.5
- we need to cover how this flow will be entered when device is remembered and receive or some other, confirmation from device demanding action will be initialized
