### ISSUE TITLE
Solana backends CORS doesn't allow Connect

### ISSUE THREAD

**Issue by martykan** [trezor/trezor-suite#12149]
Connect fails to communicate with Solana backends due to CORS settings, meaning any blockchain methods with Solana won't work. 

<img width="922" alt="Screenshot 2024-04-25 at 13 28 46" src="https://github.com/trezor/trezor-suite/assets/8833813/00df47f0-7be3-4cae-9653-f19a5261c68e">

**Comment by mroz22** [comment]
please @vdovhanych or maybe @Dehumanizer77  🙏

**Comment by vdovhanych** [comment]
I will update it.

**Comment by Dehumanizer77** [comment]
I've just done it. Please try it now.

**Comment by martykan** [comment]
It works, except for `solana-dev`

**Comment by Dehumanizer77** [comment]
should be working there now as well

**Comment by martykan** [comment]
Works, thank you
