### ISSUE TITLE
Flaky test - Connect popup passphrase in webextension

### ISSUE THREAD

**Issue by martykan** [trezor/trezor-suite#12156]
This is currently one of the most flaky tests, it does pass but often requires several attempts. 
Until we track down the issue let's skip it (#12155)

**Comment by mroz22** [comment]
one of the sources of flakiness in the connect-popup tests is too big core.js (3.1 MB). taking too long to load thus timeouting the test.

![image](https://github.com/trezor/trezor-suite/assets/30367552/4cb2376f-8ff1-463e-8abe-0103f5b67eff)

**Comment by martykan** [comment]
Interesting, it's much bigger when built with `NODE_ENV=development`, it's an output format optimized for debugging with devtools
<img width="1148" alt="Screenshot 2024-04-29 at 19 31 03" src="https://github.com/trezor/trezor-suite/assets/8833813/efa6c903-2dba-4917-9766-66f161cb67a1">
Should we just use production Webpack for these builds?

**Comment by martykan** [comment]
<img width="1035" alt="Screenshot 2024-04-29 at 20 15 50" src="https://github.com/trezor/trezor-suite/assets/8833813/826d2f99-a320-4116-b17a-b9a2bd7ff8a4">
I think there must be something going wrong that's preventing it from loading, not that it's taking too long.
