### ISSUE TITLE
Set PIN video tutorial

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1215]
currently, tutorial displaying old wallet (even older than mytrezor) is shown in pin mismatch modal. implemented in #1209

todo: 
- [ ] new video with current design
- [ ] provide it in (WebM or Ogg) and mp4 format

**Comment by glacierbits** [comment]
As commented in #1230, video creation in progress. ETA second release. Moving this to Q2 milestone.

**Comment by slowbackspace** [comment]
@matejzak any update on this? 😁

**Comment by glacierbits** [comment]
Ah, thanks for reminding me! We will create the 3D animations for this as well.

**Comment by bosomt** [comment]
Video tutorials are already gone from settings and onboarding.
Just simple text instructions. 
Is this final version and we can close this issue or there is different issue in progress for new videos that will be added later ?

![image](https://user-images.githubusercontent.com/31506317/126615709-1bb22a07-7c29-4bc1-aeb7-beac74025783.png)


**Info:**
 - Suite version: web 21.7.1 (24cc565a3badd85ab48b30348022471dfd85f90e)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model 1 1.10.2 regular
