### ISSUE TITLE
(Draft) New Connect release procedure

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12157]
### Background
To improve the stability of our releases and address any potential bugs that may impact our users, we have transitioned from continuous releases to date-anchored releases. These releases experience thorough testing by our QA team and are made available in early access to 3rd party developers well ahead of their stable release, this will help us discover and eliminate possible bugs way ahead of Stable release, thus contributing to safer and more reliable environment. 

### Stable vs Beta releases

We do 2 types of release builds - `Stable` and `Beta`

`Stable release` once in two months (last week of the month)

`Canary release` are being released continuously (when we decide)

### Versioning System

`Canary release` - 9.1.x-canary (9.1.12-canary)
Bumping just the _patch_ version with "canary" tag at the end

`Stable release` - 9.x.0 (e.g., 9.2.0)
Bumping _minor_ version

New _major_ version is released when there are breaking changes on API level. Previous major version will be maintained for 12 months and after this period it can be taken down without notice.

Current major version 9 is being developed on top of develop branch. When there is a new major version a new branch should be created (v-<major-version>) and mantained separately.

Furthermore we will do split versioning for specific parts of connect
npm package web
npm package node
npm package webextension
content of trezor.io (popup + iframe + core).

### Release process
Each Canary version will be deployed to https://connect.trezor.io/canary/9/trezor-connect.js.
Each Stable version will be deployed to https://connect.trezor.io/9/trezor-connect.js.

We will be using Canary releases as well for any hot-fixes, if such situation occurs. In that case any developer or third party will be able to use this hot-fix version instead of the Stable stream until the hot-fix become Stable release, or he simply switch back to the main release stream.
We would also welcome any developer or third party to try our Canary releases and give us feedback on new features and latest changes.

### Release flow
`Canary`
**Continuous development** - *Day x-y*
**Freeze** - *Day 1*
**Build preparation** - *Day 1*
**QA testing** - *Day 1-2
**Canary release preparation + deployment** -  *Day 3*
**Post release testing** - *Day 3
**Connect explorer update*** - *Day 3*

`Stable`
**Freeze** - *Day 1
**NPM package check** - Day 1*
**Build preparation and deploy to staging** - *Day 2* 
***Communication to partners and connect explorer update** - Day 2*
**QA testing** - *Day 3-7* 
**Beta release preparation + deployment** -  *Day 7*
**Post release testing** - *Day 7*

### External communication
We will be informing all developers and third parties listed in our newsletter in following situations:
- In case of any breaking change in the upcoming Stable/Canary release
- Pre-release Notification: Sent two weeks before each major release, detailing upcoming features and how to prepare.
- Post-release Summary: Distributed within 24 hours of a release, summarizing the changes, known issues, and where to report bugs.

**Channels of Communication:**
Slack channel: Joint space for release communication and feedback 
Email: Official method for sending out notifications and summaries.
Developer Portal: Release notes and documentation updates will be posted here. (Connect Explorer)

**Comment by mroz22** [comment]
### note 1 

> Canary release are being released continuously

What is continuously? Every day, every week, every commit? Also If canary release requires npm releases of connect packages and all its dependencies (transport, blockchain-link), it can't be too often.

### note 2 - versioning

there are already some versioning rules. https://github.com/trezor/trezor-suite/blob/develop/packages/connect/README.md#L37

how does the current proposal play with them together? are we going to keep minor/patch version distinction based on changes to npm packages?

### note 3 
maybe we want to do split versioning for specific parts of connect

- npm package web
- npm package node
- npm package webextension
- content of trezor.io (popup + iframe + core).

All these  could be versioned separately If deemed useful. In the future we might want to split our packages even more into:

- connect-api-ethereum
- connect-api-cardano
- etc.. 

### note 4

> We will be using Canary releases as well for any hot-fixs, if such situation occurs.

So this means no hotfixes of stable versions?

**Comment by Hannsek** [comment]
> What is continuously?

When needed.

> maybe we want to do split versioning for specific parts of connect

That'd be great if feasible. 

> So this means no hotfixes of stable versions?

Stable should be stable for majority of 3rd party apps. All hotfixes would go into Canary releases and individual 3rd party apps can use it if something is off with the Stable version for the particular app.

**Comment by karliatto** [comment]
I think we need to change the order of things. 
I am not sure if there is nay benefit on separating release of connect and connect dependencies.
Maybe there is still the point that if any of the dependencies of connect fails to be deployed then we do not want to deploy connect. :thinking:
## The way we were doing things until now:
1. Release connect NPM dependencies
1. Release staging
1. Ask QA to test staging
1. If QA OK -> release [connect.trezor.io/9](http://connect.trezor.io/9)
1. Ask QA to test [connect.trezor.io/9](http://connect.trezor.io/9)
1. If QA OK -> Release @trezor/connect , @trezor/connect-web  and @trezor/connect-webextension
1. Release is completed.
## I think we should do:
1. Release staging (or whatever we name it now)
1. Ask QA to test staging
1. If QA OK -> release [connect.trezor.io/9](http://connect.trezor.io/9)
1. Ask QA to test [connect.trezor.io/9](http://connect.trezor.io/9) including webextension builds and sanity tests with 3rd party wallets
1. If QA OK release all the NPM dependencies
1. If all the NPM dependencies were properly deployed then release @trezor/connect , @trezor/connect-web  and @trezor/connect-webextension
1. Release completed.

**Comment by karliatto** [comment]
## Connect versioning

We have to decide which version strategy we should follow. Each of them has some advantages and disadvantages.

## Without metadata in semantic version number
* 9.2.3 beta tag
* 9.2.4 beta tag
* 9.2.5 beta tag
* Change 9.2.5 to latest so it is an stable release
The problem with that is that we will have stable versions non consecutive. I have not seen yet anywhere were it says that this is consider a bad practice.

## With metadata in semantic version number
* 9.2.4-beta.1 beta
* 9.2.4-beta.2 beta
* 9.2.4-beta.3 beta
* 9.2.4 latest

This approach adds more clarity to the version number of what type of version it is. On the other side it has disadvantage that it is a bit more complex in our side for changelogs.
