### ISSUE TITLE
Remove from debug mode

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12167]

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.5.0 (a33ad459d3d919d5b6ac4210c9d876298ee8947a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 2144x1206
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
