### ISSUE TITLE
Reflect balances & staking in the app

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#12187]
Since the ETH staking has been introduced in Trezor Suite, we need to reflect it in TSL, in order not to scare users that they've lost their ETH but indicate that it's been staked.
We should indicated that:
- ETH funds are staked
- Amount of staked ETH
- Rewards

Total balance:
- Staked ETH is still reflected in total amount (= ETH + staked ETH + rewards)

Inform user that in case they want to Unstake they have to do it Trezor Suite web or desktop

[Figma design](https://www.figma.com/design/ylfHUP23P94yZPcVTiPTZ6/ETH-Staking?node-id=255-25893&t=puFlKGLmJswhbHwv-11)

**Comment by shenkys** [comment]
View-only: 
- Staking process timeline
- Staked
- Rewards
- APY
- Period

**Comment by shenkys** [comment]
Design done [here](https://www.figma.com/design/ylfHUP23P94yZPcVTiPTZ6/ETH-Staking?node-id=255-25893&t=puFlKGLmJswhbHwv-11)

**Comment by STew790** [comment]
**QA OK**
Staking is correctly reflected in the account
- dashboard
![image](https://github.com/user-attachments/assets/11a5d61a-2e01-43c7-9b5b-72767d2f1547)
- assets
![image](https://github.com/user-attachments/assets/8d4c44d9-2fb2-47da-a060-c9a0a4cda641)
- account
![image](https://github.com/user-attachments/assets/62018d95-0cab-4879-8a79-a3f0b240e7e8)
- staking 
![image](https://github.com/user-attachments/assets/4801f088-dc70-4c19-a861-1c7179931c10)
- info about managing in Suite
![image](https://github.com/user-attachments/assets/5b317879-79e9-4957-8146-b1c8e39e2a4a)
- link to desktop is correct
**Info**
24.10.1 https://github.com/trezor/trezor-suite/commit/6f4c0b1102e3df30853adce30c53a0de8453a48a
