### ISSUE TITLE
Use reserve for bumping fee of un/staking, claiming tx

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12183]
**Describe the bug**
Fee reserve is not applied for bumping staking, unstaking and claiming tx

**How to reproduce**
1. Stake with low gas price
1. Bump fee and observe

**Screenshots**

![Screenshot 2024-04-29 at 10 31 43](https://github.com/trezor/trezor-suite/assets/33235762/c57c0ebe-6b19-4694-a116-768f30013761)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.7.2 (3282fe8f6f491e024c0cc9cae99f3085c229c96c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
