### ISSUE TITLE
Staking: Everstake modal friendliness

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#12186]
# Problem
Messaging about the relationship between Trezor and Everstake is too harsh

# Screenshots
Resolve by [changing the colour](https://www.figma.com/file/0Kz3w6WDlvQm62RjOm87na/Staking?type=design&node-id=4826-65997&mode=design&t=tOV9dDvPKsUuw6IJ-4) of Everstake with an adjusted copy

![Image](https://github.com/trezor/trezor-suite/assets/216917/1cd2b8f1-0440-4c2d-837a-ff5dcc922fe0)

# User Feedback
>  I feel it is all about trust and I trust Trezor. So whoever they partner with, it is ok.

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/trezor/trezor-suite/assets/31506317/9e92f4cf-2f0e-4120-a1bd-57358d8d1128)


**Info:**
 - Suite version: web 24.5.0 (fd4f1f4fd94335f752ec551b5a4654c2168390f1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
