### ISSUE TITLE
Passphrase: Handle "Start over" and "retry

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#12207]
Implement start over and retry functionality

<img width="406" alt="image" src="https://github.com/trezor/trezor-suite/assets/36101761/b005c2e4-12a7-4b0b-9044-b3916f32e58c">
<img width="462" alt="image" src="https://github.com/trezor/trezor-suite/assets/36101761/11924d11-e73a-4c36-b83a-fd6a1edcaded">

**Comment by STew790** [comment]
**QA OK**
- open unused wallet warns me about empty wallet and lets me input passphrase again
- try again lets me try my passphrase again
- mismatch shown when I enter different passphrase each time and sets me back to start

24.6.0 29914f2
