### ISSUE TITLE
Start discovering Ledger derivation path for SOL

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#12234]
With great sadness, I have to ask for implementation of Ledger Solana derivation path (`"m/44'/501'/i'`) during discovery phase.

**Comment by evgenysl** [comment]
**QA OK**
Funded Ledger account is discoverable. 

![Screenshot 2024-08-08 at 12 23 22](https://github.com/user-attachments/assets/1c0c63e7-1bd0-4a33-8f16-c4684f9cfd17)
