### ISSUE TITLE
Autoupdate not working in EAP when a newer tag exists

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#12236]
Mobile release tags break Suite autoupdate for users in Early Access Program while the tag for mobile app is newer than for desktop, even if it is not marked as `Latest` or `Pre-release`. This is because Suite accesses https://github.com/trezor/trezor-suite/releases.atom, not https://github.com/trezor/trezor-suite/releases/latest when EAP is on. This is possibly an Electron bug. Needs to be investigated.

![image](https://github.com/trezor/trezor-suite/assets/42465546/511b678a-8dbe-44e8-8df4-dccf58647a3c)

**Comment by MiroslavProchazka** [comment]
Is kinda solved for now by deleting the Suite Lite release tag and whole release from GH.

**Comment by matejkriz** [comment]
But we still want to find a way how to publish other things than Suite Desktop without interfering with the auto-update.

**Comment by matejkriz** [comment]
This is no longer an issue with new auto-update provider https://github.com/trezor/trezor-suite/pull/12788
