### ISSUE TITLE
Optional common parameters link in connect explorer does not work

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#12246]
![image](https://github.com/trezor/trezor-suite/assets/57008159/50f84abd-d2ea-4770-bcf9-06ef91f02160)

`Optional common parameters` link leads to https://github.com/trezor/trezor-suite/blob/develop/docs/packages/connectcommonParams.md and throws `404 - page not found`

**Comment by Hannsek** [comment]
the same thing applies for [this](https://github.com/trezor/trezor-suite/blob/develop/docs/packages/connecthttps://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/types/api/getPublicKey.ts) and [this](https://github.com/trezor/trezor-suite/blob/develop/docs/packages/connecthttps://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#Serialization_format)

**Comment by martykan** [comment]
This is the old Explorer right?
