### ISSUE TITLE
Update banner not visible with remembered different wallet/device

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#12247]
**Describe the bug**
If I have a remembered wallet from a different device and I plug in another device with outdated FW, I don't see the blue banner with "Update firmware" prompt, but when I go to "Device" settings and click on "Install custom firmware" I can see the banner appear there. Screenshots attached.

**Steps to reproduce:**
1. Have a remembered wallet
2. Plug in a different device with an outdated fw
3. Go to Device settings
4. Click on "Install custom firmware"
5. The modal appears and you can see the blue banner with "update fw" prompt in the background

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
The blue banner with update fw prompt should be seen.

**Actual result:**
The blue banner with update fw prompt can be seen only when you click on "Install custom firmware".

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/48477147/e857d7fa-ee1b-4a11-9541-86853141e4ce)
![image](https://github.com/trezor/trezor-suite/assets/48477147/98bc9cda-a1f0-4958-8fee-ef17ea08e20f)

**Comment by MiroslavProchazka** [comment]
@jvaclavik Please use this https://github.com/trezor/trezor-suite/pull/12260 and finish it up. Thx :)

**Comment by MiroslavProchazka** [comment]
Solved by [reverting the initial commit](https://github.com/trezor/trezor-suite/pull/12278)

**Comment by STew790** [comment]
**QA OK**
Reverted to the initial commit.

**Info:**
 - Suite version: desktop 24.5.1 (a94f65e0a34ae30fc78759aabec64c0f99055a1c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.32
