### ISSUE TITLE
Staking promo banner visible on BTC-only FW device

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12253]
The Staking promo banner is visible even on Device with BTC-only FW with 0 ETH balance. We need to get rid of it. 

<img width="1379" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/87655282-afe0-46c9-b904-293fd5fdf81d">
<img width="1416" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/eca9b7ae-766a-4b77-88e7-67ba384ce795">

**Comment by bosomt** [comment]
**QA OK**

no staking banner available when BTC only device

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.12.1 bitcoin-only (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33
