### ISSUE TITLE
missing favicon in connect.trezor.io/9/log.html

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#12257]
missing favicon in connect.trezor.io/9/log.html

![image](https://github.com/trezor/trezor-suite/assets/30367552/fd81c0b3-c0a5-401f-a4f0-404c7dc2d40d)

**Comment by bosomt** [comment]
**QA OK**

fixed at 
https://dev.suite.sldev.cz/connect-nextra/develop/log.html
