### ISSUE TITLE
Incorrect anchor behaviour when navigating

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12265]
**Describe the bug**
Incorrect anchor behaviour when navigating

**Steps to reproduce:**
1. See video

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/686e1e76-9774-4766-8022-b6d02f325907

https://github.com/trezor/trezor-suite/assets/31506317/86598442-3a4f-418d-bab0-cfcecd8352d8

**Comment by peter-sanderson** [comment]
It was broken by https://github.com/trezor/trezor-suite/pull/11930

Not sure what exactly yet, but commit before this works.

**Comment by bosomt** [comment]
**QA OK**

anchor behavior was fixed

but im not sure if it behaves as expected see video @peter-sanderson 
https://youtu.be/weY1FJH9qIs

**Info:**
 - Suite version: web 24.5.0 (5b29898216a6008533a9b540cf3b00891598c9a6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
