### ISSUE TITLE
New view-only wallet design appearing in the production release without Debug mode on

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12269]
When you open the freshly installed Suite 24.5.1, this notification pops up. I was not able to replicate it after closing or resetting the Suite, but this issue has occurred for 3+ users (internally) already, so it must be hidden somewhere.

![image](https://github.com/trezor/trezor-suite/assets/152851523/95361041-1bbc-4e45-90cf-af64459f06cf)

**Comment by MiroslavProchazka** [comment]
Solved by https://github.com/trezor/trezor-suite/pull/12285

**Comment by STew790** [comment]
**QA OK**
No longer appearing for me.

**Info:**
 - Suite version: desktop 24.5.1 (a94f65e0a34ae30fc78759aabec64c0f99055a1c)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Win32
 - Screen: 2560x1440
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.31
