### ISSUE TITLE
Message system massage overlapping modals

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12268]
**Describe the bug**
Message system massage overlapping modals

**Steps to reproduce:**
1. Start new version of Suite with number lower than production /using 0.24.5 on staging/
2. Observe modals

**Info:**
 - Suite version: web 0.24.5 (b4c0d6e5e3993576a2a1b94a13f3e624ec283002)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1455x868
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="1420" alt="Screenshot 2024-05-05 at 8 17 28" src="https://github.com/trezor/trezor-suite/assets/31506317/31071015-98f0-4896-bdf4-aeeb6b4a5c2f">
<img width="1365" alt="Screenshot 2024-05-05 at 8 15 12" src="https://github.com/trezor/trezor-suite/assets/31506317/a46cc7bc-e7c2-4105-8c36-9e1ae5a13ae6">

**Comment by MiroslavProchazka** [comment]
@jvaclavik Please use this [draft](https://github.com/trezor/trezor-suite/pull/12260) and finish it up. Thx :)

**Comment by MiroslavProchazka** [comment]
Solved by [reverting the initial commit](https://github.com/trezor/trezor-suite/pull/12278)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.5.1 (a94f65e0a34ae30fc78759aabec64c0f99055a1c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
