### ISSUE TITLE
Difference address on Trezor One and Suite with Legacy account.

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12272]
There is a difference between displayed address on Trezor One and Suite with Legacy account.

Last letter of the first line on Suite  (j) should be on the second line just like on the Trezor.

![image](https://github.com/trezor/trezor-suite/assets/152851523/aa6f4916-5b60-4a42-8cd2-cd899197e820)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.7.0 (0959ca14fb3b440d4f849e9c8bf7d3688afd6b94)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33
