### ISSUE TITLE
Put bridge switcher into the debug menu

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#12288]

**Comment by bosomt** [comment]
**QA OK**

 - Suite version: web 24.5.0 (11037d7495bca59794d9331a2c21898810291f6a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
