### ISSUE TITLE
Passphrase analytics

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#12281]
Passphrase metrics:
- [x] Users with Standard wallet only (already implemented)
- [x]  Users with opened Passphrase wallet (send event when passphrase is opened and either user access passphrase with transactions or empty passphrase
- [x] Clicks on How a passphrase works
- [x]  number of opened Passphrase per user (check with BI)
- [x]  Users choose passphrase on mobile screen
- [x]  Users choose passphrase on device
- [x]  Opening existing wallet
- [x]  User made typo - clicked Try again
- [x]  Passphrase mismatch
- [x]  Passphrase not enabled on Trezor
- [x]  Finish rate - users successfully entered the flow and finished it - either by accessing existing passphrase or empty one. 
- [x]  Edit: Finish rate will be succesfull submits (already part of another checklist item) + `add passphrase wallet` will have another analytics event
- [x]  Drop off - send event when user leaves the passphrase flow (click on cancel, cross)

**Comment by juriczech** [comment]
Blocked by code review on https://github.com/trezor/trezor-suite/pull/13121
Moving packages so there would be too many conflicts.
