### ISSUE TITLE
Remove +/- from 0 values

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#12289]
**Describe the bug**
Please remove + and/or - signs from zero values.

![Image](https://github.com/trezor/trezor-suite/assets/88533514/f71525c7-9a62-4f67-9fc2-140bc13f1605)

**Info:**

-   Suite Version: 24.4

**How to reproduce**

1. Observe any 0 value in the transaction history.

**Expected behavior**
0 should be 0, no + or -.

**Comment by AdamSchinzel** [comment]
Actually here the -0 ETH is another bug so will just adjust it for the fiat sum of the day

**Comment by bosomt** [comment]
**QA OK**

i was still able to find - in 0 ETH fees on all seed standard wallet but other coins and values are ok



![Image](https://github.com/trezor/trezor-suite/assets/31506317/6a147fa3-a139-4a75-ac2a-2edeeece7055)



![Image](https://github.com/trezor/trezor-suite/assets/31506317/2287c367-3c9b-4b02-bb58-efc853d110c6)



![Image](https://github.com/trezor/trezor-suite/assets/31506317/dcb0856d-73d2-4aa6-9899-43868620f6e0)



**Info:**
 - Suite version: web 24.6.0 (d24790f5abfa61029c017ed655351da3862ad40f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 3.0.0
