### ISSUE TITLE
Use black-box to show data and OP_RETURN so it is shown the same way as it is on the device

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#12280]
1. make OP_RETURN in black box

![image](https://github.com/trezor/trezor-suite/assets/152899911/7e8440e5-ffeb-4348-97d6-1c120cdf17b4)

2. swap data and address 
3. data into black bubble

This also should fix: https://github.com/trezor/trezor-suite/issues/10593#issuecomment-2092826673

![image](https://github.com/trezor/trezor-suite/assets/152899911/e9829b42-0f9e-422b-8308-18d9c28057ce)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.5.0 (5b29898216a6008533a9b540cf3b00891598c9a6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
