### ISSUE TITLE
Change PIN

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1230]
If PIN protection enabled, option to change PIN is to appear. 

**[Zeplin](https://zpl.io/VOnyj71)**

**Comment by mroz22** [comment]
done

**Comment by bosomt** [comment]
pin mismatch starts video that you can't mute or stop. 

![image](https://user-images.githubusercontent.com/31506317/76853503-b19f5080-684d-11ea-9076-6c2c5d569b4c.png)

**Comment by bosomt** [comment]
PIN change accepts keyboard characters  !@#$%^&*() /shift + number/

**Comment by glacierbits** [comment]
@mroz22 Let's remove the video please for now and use the error illustration instead: **[Zeplin](https://zpl.io/2j96DE6)** with the _Try again_ button. 

Rationale: 

(1) First release will be rolled out among experienced users only.
(2) If the user is really confused about the PIN input they still have the option to _Learn more_
(3) We are working on new set of explainer videos. Can't guarantee they will be ready for the release though.

**Comment by bosomt** [comment]
looks fine now, 
can you please remove that second copy of pin mismatch or change it to something else ?
looks strange.
@mroz22 @slowbackspace 

![image](https://user-images.githubusercontent.com/31506317/78752697-d54d4680-7974-11ea-9319-11bbe1b48254.png)

**Comment by glacierbits** [comment]
I will fix the copy, thanks. 

@slowbackspace can you please fix the button? Related to #1328

**Comment by bosomt** [comment]
edit: my VPN was down ;)

**Comment by bosomt** [comment]
i see only one back button

but text is still there

![image](https://user-images.githubusercontent.com/31506317/78983984-95799100-7b25-11ea-9615-f50c597ab16c.png)

**Comment by glacierbits** [comment]
Text fixed. 

FYI @bosomt the change will propagate upon @slowbackspace 's sync magic.

**Comment by bosomt** [comment]
@slowbackspace when ? :)

current status: 

![image](https://user-images.githubusercontent.com/31506317/81065749-6106b400-8edc-11ea-8153-4b0c6b9143bd.png)

**Comment by slowbackspace** [comment]
> @slowbackspace when ? :)
> 
> current status:
> 
> ![image](https://user-images.githubusercontent.com/31506317/81065749-6106b400-8edc-11ea-8153-4b0c6b9143bd.png)

in 30 mins
