### ISSUE TITLE
Discovery error - Litecoin, Ethereum Classic

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#1231]
suite.corp.sldev.cz/suite-web/develop/

**Steps to reproduce:** 
Activate Litecoin or Ethereum Classic account in Settings/through + Accounts button in wallet

**Expected behaviour**
Coin discovery after activating selected coin accounts will be succesful

**Actual behaviour**
Coin discovery for Litecoin and Ethereum Classic results in Discovery error.

**Comment by wendys-cats** [comment]
@bosomt will you add the bit about deactivate>activate, please?

**Comment by bosomt** [comment]
it works fine now :( sorry ....

**Comment by bosomt** [comment]
but, sometimes it happens. sometimes not, 
i don't know what triggers it ;(
fw 2.2.0

![image](https://user-images.githubusercontent.com/31506317/74934090-b22aff80-53e5-11ea-960e-a4bf0a0a1e2f.png)
![image](https://user-images.githubusercontent.com/31506317/74934100-b9eaa400-53e5-11ea-82f2-8f7064b00f90.png)

**Comment by glacierbits** [comment]
Easter egg for the QA. Solved.
