### ISSUE TITLE
Add option to enable/disable haptic feedback on T3T1 (Connect)

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12315]
With the arrival of T3T1, haptic feedback will be introduced as a device feature. Please implement the logic for calling requests to turn that on or off in Connect and hand it over to @peter-sanderson, who will be implementing it in the UI.
UI-wise issue as follow up to this one is [here](https://github.com/trezor/trezor-suite/issues/12314).

**Comment by mroz22** [comment]
waiting for https://github.com/trezor/trezor-firmware/pull/3802

**Comment by MiroslavProchazka** [comment]
https://github.com/trezor/trezor-firmware/pull/3802 already merged, can you take a look at it please?

**Comment by mroz22** [comment]
connect should be ready in this PR https://github.com/trezor/trezor-suite/pull/12733

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/7a72e1d0-3a01-48bc-8194-6c5eba2ac2d9)

**Info:**
 - Suite version: desktop 24.6.1 (686e06027e8698cc8f17f928a6ae947d76280489)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
