### ISSUE TITLE
Add option to enable/disable haptic feedback on T3T1 (UI)

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12314]
With the arrival of T3T1, haptic feedback will be introduced as a device feature. Please implement an option to turn this feature on or off in Suite settings - Device - Customization section. Graphically, please use similar logic as with the PIN/Passphrase options.

Related to [this](https://github.com/trezor/trezor-suite/pull/12313) Connect PR

![image](https://github.com/trezor/trezor-suite/assets/152851523/ee05532c-1428-470e-9ffa-8cddf98deb58)

<img width="773" alt="image" src="https://github.com/trezor/trezor-suite/assets/152851523/f17100b8-3918-4183-9b8e-119076f948fb">

**Comment by MiroslavProchazka** [comment]
@Hermez-cz please draft copy for this feature

**Comment by STew790** [comment]
**QA OK**

Same as here https://github.com/trezor/trezor-suite/issues/12315
