### ISSUE TITLE
Ugly Backup failed modal

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12317]
**Describe the bug**
Ugly `Backup failed` modal

**Steps to reproduce:**
1. Connect device that needs backup
2. Navigate to `Settings/Device`
3. Start backup
4. Disconnect device

**Info:**
 - Suite version: desktop 24.5.1 (a94f65e0a34ae30fc78759aabec64c0f99055a1c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision null)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="690" alt="Screenshot 2024-05-08 at 15 50 52" src="https://github.com/trezor/trezor-suite/assets/31506317/384772c8-a52a-4510-8d27-e63dae06a181">

**Comment by MiroslavProchazka** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/12325

**Comment by STew790** [comment]
**QA OK**
As per https://github.com/trezor/trezor-suite/pull/12325#issuecomment-2102926320

**Info:**
 - Suite version: desktop 24.5.2 (1ca8b8063fd7028d1fe242db41caa31c0a1f7d5a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
