### ISSUE TITLE
Transaction anchor behaviour

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12330]
**Describe the bug**
Transaction anchor behaviour
Follow up of https://github.com/trezor/trezor-suite/issues/12265

**Steps to reproduce:**
1. Send transaction 
2. Try to click on anchor from notification multiple times

**Info:**
 - Suite version: web 24.5.0 (7f11664fece9598bf7d43bc46ad48d857845ca4c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
https://youtu.be/gyzouff20fI

**Comment by MiroslavProchazka** [comment]
Please re-test this against current 24.5.2 RC, it should be fixed there.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.6.0 (b6167266c98396f27a6f118acbc9fda04928ebe4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 3.0.0
