### ISSUE TITLE
Incorrect fee when trying to claim staked funds

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12332]
**Describe the bug**
Incorrect fee when trying to claim staked funds.
See screenshots, i was able to reproduce it on dv version and current EAP version.
Account address 0x11E3a88727f94b6c8230881B1d56230964c05dA7

**Info:**
 - Suite version: desktop 24.5.0 (7f11664fece9598bf7d43bc46ad48d857845ca4c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.5.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: NodeUsbTransport

**Screenshots:**
<img width="442" alt="Screenshot 2024-05-10 at 9 40 12" src="https://github.com/trezor/trezor-suite/assets/31506317/30ef573d-bf48-4e71-8a43-524d17e8cc4b">
<img width="683" alt="Screenshot 2024-05-10 at 9 40 01" src="https://github.com/trezor/trezor-suite/assets/31506317/7f45ce32-997f-4f50-95f0-e7f44f8d5dcf">
<img width="524" alt="Screenshot 2024-05-10 at 9 39 48" src="https://github.com/trezor/trezor-suite/assets/31506317/fc7ad5ab-2a15-413a-bd1f-96037e340e47">
![image](https://github.com/trezor/trezor-suite/assets/31506317/b2b16469-7984-4d96-9082-77d3fb31b4f8)
![image](https://github.com/trezor/trezor-suite/assets/31506317/0ecdb051-e1ae-4c04-9986-3e9ea0565cc8)

**Comment by tomasklim** [comment]
It is also on mainnet

**Comment by bosomt** [comment]
**QA OK**

ETH unstake ok
ETH stake OK

HOLESKY stake [ok](https://holesky1.trezor.io/tx/0x13d3a0d33fbb2f90660c6f8743936f7b0e51705ef47fd1cc99b17f7fa4adeda2) 
HOLESKY unstahe [ok](https://holesky1.trezor.io/tx/0x679ee0b87f4f611ca560804bbe9b177a2d5296700f60b9ac9f930e6a388ec259)
HOLESHKY claim [ok](https://holesky1.trezor.io/tx/0x01975bda35757260d582f5f180fbb46b3f102dde978447d4851a08ebeba21c13)

**Info:**
 - Suite version: web 24.5.0 (a7d7b97c87cd8679ce0d33fb070e2e05514f0d29)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 3.0.0
