### ISSUE TITLE
Enable passphrase on add hidden wallet

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#12354]
When passphrase is disabled and `Add passphrase` is clicked, user should be redirected to screen that handles this case and takes users attention to the device screen. Then the flow should continue to the passphrase flow.

https://www.figma.com/file/mmDnYtctfjnreWhTjLfeQH/Passphrase?type=design&node-id=2567-11934&mode=design&t=R7jx578b96an5B2v-11

**Comment by STew790** [comment]
**QA OK**
When I disable passphrase and click on "Open passphrase" it takes me to a screen where I can enable it again and after that a screen where I can enter it. (don't know why it's upside down, sorry :sweat: )
![image](https://github.com/trezor/trezor-suite/assets/48477147/4fcf7659-6118-4ec4-89b9-c4ef047424f2)

**Info:**

24.6.0 c747f2a
