### ISSUE TITLE
Cannot scroll down on backup type dropdown menu

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12377]
https://github.com/trezor/trezor-suite/assets/152851523/208f544a-4620-4c16-90ad-e3f3ab5fe99c

**Comment by bosomt** [comment]
**QA OK**

scrolling is ok, 

**Info:**
 - Suite version: web 24.6.0 (f4408ff224e991759720931f540a569d4cd0b398)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 bitcoin-only (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 3.0.0
