### ISSUE TITLE
Inconsistent time to stake estimation

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#12374]
# Description
Staking in a nutshell, confirm entry period and adding to staking pool do not have consistent estimations

# Screenshots
(from mainnet)

![Image](https://github.com/trezor/trezor-suite/assets/216917/5a910428-bd1d-447d-8ffb-dbdcf5e65eb4)

![Image](https://github.com/trezor/trezor-suite/assets/216917/15a92aaa-6fe3-4f87-a307-7eb08bd35b55)

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/trezor/trezor-suite/assets/31506317/6ac13d1d-54f2-478b-a246-3bf457a2eb4b)

**Info:**
 - Suite version: desktop 24.7.1 (3856b5e5f845e68f754487dee863c6ea0c347070)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
