### ISSUE TITLE
Distinguish between standard and passphrase wallet (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12387]
Functionality for these actions should be implemented:
<img width="395" alt="Screenshot 2024-05-15 at 10 10 58" src="https://github.com/trezor/trezor-suite/assets/858321/6f8e8d4d-5f88-4855-88c2-3e97027d42ff">

<img width="1341" alt="image" src="https://github.com/trezor/trezor-suite/assets/858321/40cd1dab-7c0a-4cd5-a64c-a5cb5c286d68">

<img width="1380" alt="image" src="https://github.com/trezor/trezor-suite/assets/858321/6ed87682-bc86-4c68-b282-6b0e045f8a6a">

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.7.0 (87a1ef738cd9557e8d447be74b6eb438d1691c8d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
