### ISSUE TITLE
Analytics for Multi-share backup

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12381]
To monitor user interactions with the feature, please add an analytics event that captures:

### Onboarding (Wallet creation and backup step)
<aside>

- [x] Menu Interaction Rate: Track how many users open the select menu versus those who proceed with the default option directly.

- [x] Option Selection Breakdown: Record which options are selected by users who open the menu, including returns to the default setting.

- [x] User Context Data: Capture the type of device and seed card (12/20w) each user is using.

</aside>

### Wallet successfully created screen
![image](https://github.com/trezor/trezor-suite/assets/152851523/6dd1151c-20ee-48c1-befb-72fec6d4d865)

- [ ] We are already monitoring skipped backups statistically in analytics. Please make sure to keep it functional.

### Settings Multi-share backup creation (”Shamirization”)
![Untitled](https://github.com/trezor/trezor-suite/assets/152851523/08a27db9-a458-47d5-a3b5-5dcc365cce1c)

- [x] To statistically monitor the usage of this feature, please implement an analytics event that captures relevant data. We should be able to check how many of the eligible instances (with compatible devices & backups) will go for this option.

### Create multi-share backup explanative modal window (Nice to have)
<aside>
**Nice to have**

- [x] Modal Closure: Record how many users close the modal, indicating disinterest.

- [x] Learn More Clicks: Track how many users click on the [Learn more] button, which can indicate the need for further information or clarity.

- [x] Create Multi-share Backup Clicks: Monitor how many users click on the [Create multi-share backup] button, which will help assess the effectiveness of the content and its ability to engage users.

</aside>

### Multi-share backup created (success) screen
![Untitled (3)](https://github.com/trezor/trezor-suite/assets/152851523/58df4bd4-056b-4587-be62-b9784d414146)

- [x] To statistically monitor the usage of this feature, please implement an analytics event that captures relevant data, such as how many [instances that initiated this flow (Create multi-share backup explanative modal window) ended up successfully completing it.

**Comment by peter-sanderson** [comment]
> We are already monitoring skipped backups statistically in analytics. 
 
 I haven't found it. What is the supposed EventType? It not in the code and I also did not found any in notion (https://www.notion.so/satoshilabs/c63bdab01b704b099cab3bbb3227e1b1?v=406d107d6d584577a47d7580e8b2df89)

**Comment by STew790** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.6.1 (f640a29f7ac7cc7bdac9259531267689d66e64e9)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
