### ISSUE TITLE
Redesign passphrase mismatch (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12389]
<img width="553" alt="image" src="https://github.com/trezor/trezor-suite/assets/858321/eb4b1246-64ef-4e3b-9a6f-8628d27868cc">

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2360-57995&t=03r75bJYrFjp9AqS-0

**Comment by jvaclavik** [comment]
Kamino cloned this issue to [trezor/trezor-suite](https://github.com/trezor/trezor-suite/issues/12390)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.7.0 (3185c54bc8a4499ef5cfd5825b01df02833cab80)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision 2e10618876be8a09a9d985098429f3016baf348e)
 - Transport: BridgeTransport 2.0.33
