### ISSUE TITLE
Passphrase secure input

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#12383]
Current input is using `secureEntry` prop from react native's input and that gets caught by password managers so we'll need to implement some kind of `SecureInput` component, that will reuse lots of stuff from our custom Input implementation from atoms, but the value and onChange logic will have to be changed so that value gets changed for `*` after user types something. But the stored value should actually be normal string. 

**Acceptance criteria**
- same styles as our current input, ideally as much reused code between these components as possible
- reusable component in `suite-native/atoms`
- no use of `secureEntry` and test that it doesn't get picked up by password managers
- works with react-hook-form

**Comment by PeKne** [comment]
note for QA: After merging https://github.com/trezor/trezor-suite/pull/12508 we just need to test if the passphrase input doesn't offer an autofill nor interact with a password manager. The passphrase should be never read or saved to password manager.

**Comment by STew790** [comment]
Just to be sure, is it OK to copy+paste there something? Also, you can ping us via @trezor/qa for next time :).

**Comment by juriczech** [comment]
cc @mnuky @shenkys How is it with copy+pasting into the input on passphrase form please?

**Comment by juriczech** [comment]
@STew790 Copy + pasting is intended, apparently it's available also on desktop

**Comment by STew790** [comment]
**QA OK**
I was not able to use any pass manager for passphrase and copy+pasting works just fine.

24.6.0 c747f2a
