### ISSUE TITLE
Redesign wallet already opened (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12390]
old:
<img width="698" alt="image" src="https://github.com/trezor/trezor-suite/assets/858321/68714801-38d6-4e90-bcea-03d4aa8472a8">

new (there are bugs in copy):
<img width="559" alt="image" src="https://github.com/trezor/trezor-suite/assets/858321/a6b044c2-a74c-410d-b6d6-6747bcf5d40e">

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2360-57995&t=03r75bJYrFjp9AqS-0

**Comment by jvaclavik** [comment]
Kamino cloned this issue to [trezor/trezor-suite](https://github.com/trezor/trezor-suite/issues/12391)

**Comment by bosomt** [comment]
@jvaclavik @MiroslavProchazka 

- not sure if modal is aligned as expected, see screenshot
- not sure why there is 🔽 button present when you have to choose one option anyway to return to app, see video

![Image](https://github.com/trezor/trezor-suite/assets/31506317/971419a9-c3a7-48a4-9a3f-815475ecf291)



https://github.com/trezor/trezor-suite/assets/31506317/95802593-9faf-4b65-a96d-ed71ec0b5ff4

**Info:**
 - Suite version: web 24.6.0 (05304daec4881bbeb3fbc8c975b68b7d9a321013)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
