### ISSUE TITLE
Tertiary buttons when trezor is disconnected (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12398]
<img width="719" alt="Screenshot 2024-05-15 at 10 33 11" src="https://github.com/trezor/trezor-suite/assets/858321/6877a93a-74ed-48f7-bc9f-e6f01a8f21fa">

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2354-40396&t=03r75bJYrFjp9AqS-0

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/c72029dc-6caf-402c-87bd-b48bb82a862a)
![image](https://github.com/trezor/trezor-suite/assets/48477147/9d2670ac-2c6c-4f81-a3a4-b3f94375c360)
![image](https://github.com/trezor/trezor-suite/assets/48477147/fd299afa-8424-47ff-8566-9bba70e4717a)

**Info:**
 - Suite version: desktop 24.7.1 (6477c7424ba244d53200f37ad9698e54fed8d169)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32
