### ISSUE TITLE
Fix tooltip when switch device is opened (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12393]
This is fine:
<img width="923" alt="image" src="https://github.com/trezor/trezor-suite/assets/858321/5647dcfc-b881-4bb5-9993-d75f3761e82b">

This is not fine:
<img width="953" alt="image" src="https://github.com/trezor/trezor-suite/assets/858321/0f79bdcc-7b6a-42d3-ab5d-c3aeee651c7c">

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2360-57995&t=03r75bJYrFjp9AqS-0

**Comment by STew790** [comment]
**QA OK**
The tooltip hides when I open the switch device menu.

**Info:**
 - Suite version: desktop 24.7.1 (6477c7424ba244d53200f37ad9698e54fed8d169)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32
