### ISSUE TITLE
Add promo banner to dashboard (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12396]
**Ondra will design all banners first so we can unify it to common component.**

<img width="1111" alt="Screenshot 2024-05-15 at 10 30 25" src="https://github.com/trezor/trezor-suite/assets/858321/232f9b26-fa7f-4824-b044-b4414af52a63">

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2354-40396&t=03r75bJYrFjp9AqS-0

**Comment by MiroslavProchazka** [comment]
We need to define logic on when this modal will display to users 
cc @Hermez-cz

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.7.0 (87a1ef738cd9557e8d447be74b6eb438d1691c8d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
