### ISSUE TITLE
Add default wallet loading to Settings (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12394]
<img width="1026" alt="Screenshot 2024-05-15 at 10 14 01" src="https://github.com/trezor/trezor-suite/assets/858321/a15f4a93-e941-4ffa-abe4-3a98b6dab4c1">

<img width="1180" alt="Screenshot 2024-05-17 at 15 39 58" src="https://github.com/trezor/trezor-suite/assets/858321/e0bf2f02-2e86-435b-81ef-44a59ebefb37">

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2354-40396&t=03r75bJYrFjp9AqS-0

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.7.0 (87a1ef738cd9557e8d447be74b6eb438d1691c8d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
