### ISSUE TITLE
"Try again" should go back (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12391]
<img width="357" alt="Screenshot 2024-05-15 at 09 58 46" src="https://github.com/trezor/trezor-suite/assets/858321/c9137508-4cbf-4ae8-a191-6175eba353aa">

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2360-57995&t=03r75bJYrFjp9AqS-0

**Comment by bosomt** [comment]
**QA OK**

after you press try again you are navigated to 



![Image](https://github.com/trezor/trezor-suite/assets/31506317/c8fa9d3e-760e-4c1d-82e3-bb4f6d11eb76)



**Info:**
 - Suite version: web 24.7.0 (3185c54bc8a4499ef5cfd5825b01df02833cab80)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision 2e10618876be8a09a9d985098429f3016baf348e)
 - Transport: BridgeTransport 2.0.33
