### ISSUE TITLE
Receive page with disconnected trezor (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12403]
- banner
- show button for unverified address

<img width="690" alt="Screenshot 2024-05-15 at 12 11 10" src="https://github.com/trezor/trezor-suite/assets/858321/b199b425-a081-403c-8a38-9f868f57d255">

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2354-40396&t=03r75bJYrFjp9AqS-0

**Comment by bosomt** [comment]
**QA OK**

both banners and warning modal is present

**Info:**
 - Suite version: web 24.7.0 (3185c54bc8a4499ef5cfd5825b01df02833cab80)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision 2e10618876be8a09a9d985098429f3016baf348e)
 - Transport: BridgeTransport 2.0.33
