### ISSUE TITLE
Send page with disconnected trezor (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12402]
- show banner
- disable send button
 
<img width="690" alt="Screenshot 2024-05-15 at 12 08 57" src="https://github.com/trezor/trezor-suite/assets/858321/3cc629fa-092f-40af-b13b-c23d43f70579">

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2354-40396&t=03r75bJYrFjp9AqS-0

**Comment by bosomt** [comment]
**QA NOK**

Tested multiple accounts but `Connect Trezor to Send` button is never rendered.

![Image](https://github.com/trezor/trezor-suite/assets/31506317/62634fd6-0531-4c2d-bf33-aa4f518aa687)


**Info:**
 - Suite version: web 24.6.0 (05304daec4881bbeb3fbc8c975b68b7d9a321013)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by jvaclavik** [comment]
@bosomt Are you sure? I just test it and it looks like it's working 🤷‍♂️

https://github.com/trezor/trezor-suite/assets/858321/2f3d3eb9-621b-42ce-a71e-ed880ba5d7cc

it check if device is not connected or it's not available

**Comment by bosomt** [comment]
@jvaclavik i mean this :)
<img width="281" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/25b23a80-8e58-4e2a-ab1b-e78844c99e8d">

**Comment by jvaclavik** [comment]
I see!

Should be fixed here: https://github.com/trezor/trezor-suite/pull/12559
