### ISSUE TITLE
Revise renaming wallets (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12408]
I'm not sure if it's working or it's broken. 

Desired state:
<img width="357" alt="image" src="https://github.com/trezor/trezor-suite/assets/858321/156e584d-bfa8-48ae-9446-0364cf8d3d49">

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2360-57995&t=03r75bJYrFjp9AqS-0

**Comment by jvaclavik** [comment]
It's working now

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.7.0 (3185c54bc8a4499ef5cfd5825b01df02833cab80)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision 2e10618876be8a09a9d985098429f3016baf348e)
 - Transport: BridgeTransport 2.0.33
