### ISSUE TITLE
Delete legacy components (view-only) - last issue!

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12406]
```
packages/suite/src/views/suite/SwitchDevice/SwitchDeviceLegacy.tsx
packages/suite/src/views/suite/SwitchDevice/DeviceItemLegacy/
packages/suite/src/components/suite/modals/ModalSwitcher/DiscoveryLoaderLegacy.tsx
packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/PassphraseModalLegacy.tsx
packages/components/src/components/Passphrase/PassphraseTypeCardLegacy.tsx
```

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2354-40396&t=03r75bJYrFjp9AqS-0

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.8.0 (e3effd817c278b7877a1f1f8e24d74f78a56d374)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.8.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
