### ISSUE TITLE
Add HotkeyBadge to Switch device modal (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12404]
<img width="254" alt="Screenshot 2024-05-15 at 12 13 20" src="https://github.com/trezor/trezor-suite/assets/858321/8c76c5b5-9e54-4e0c-8b2d-3ea358a5b9cd">

<img width="1069" alt="Screenshot 2024-05-14 at 17 19 37" src="https://github.com/trezor/trezor-suite/assets/858321/c5719f5a-7dd6-4f4d-88c5-ed42a80b06f2">

Test shortcut properly!

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2354-40396&t=03r75bJYrFjp9AqS-0

**Comment by STew790** [comment]
**QA OK**
OK on Linux (PopOS!), shortcut works properly, both in app and on web.

**Info:**
 - Suite version: desktop 24.7.1 (6477c7424ba244d53200f37ad9698e54fed8d169)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.7.1 (88dbe0410ac5b6245f392ce13e8c30f0f8f549f2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 3.0.0
