### ISSUE TITLE
Stake Ethereum modal Max button broken

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12417]
**Describe the bug**
Stake Ethereum modal Max button broken

**Steps to reproduce:**
1. Navigate to Staking section
2. Press `Stake'
3. Press `Max`
4. Observe error

**Info:**
 - Suite version: desktop 24.5.2 (1ca8b8063fd7028d1fe242db41caa31c0a1f7d5a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 1f67c1e55ca2fcf47ce6b28aff75303a8dc19187)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="1147" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/a1379333-f237-4c6d-8d47-d69dd1b5e9a9">

**Comment by MiroslavProchazka** [comment]
Fixed by switching BE to Erigon 2.59.1.

**Comment by bosomt** [comment]
**QA OK**

tested on holesky erigon/2.59.3/linux-amd64/go1.21.6

**Info:**
 - Suite version: desktop 24.6.0 (b6167266c98396f27a6f118acbc9fda04928ebe4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 3.0.0
