### ISSUE TITLE
Passphrase: Wallet switcher enhancements

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#12421]
Better prepare Wallet switcher for passphrase by showing fiat amount for each wallet, make content scrollable in case of many wallets and update visual in case of single wallet per device

[Figma here](https://www.figma.com/design/mmDnYtctfjnreWhTjLfeQH/Passphrase?node-id=2146-54343&t=IUU4Nb1aSTFhpLPl-0)

- [x] make device switcher content scrollable when there are more wallets
- [x] `Change` button animation between `⌄` and `^` icon state
<img src="https://github.com/trezor/trezor-suite/assets/2011829/6234c3aa-24a2-4f9e-9118-6c6624780dc3" width=300 />

**Comment by matejkriz** [comment]
waiting for transaction cache and scrolling design

**Comment by vytick** [comment]
mindnote: my discussion about this with Sheny:
https://satoshilabs.slack.com/archives/D06CTSHJ34Y/p1717008785611149

**Comment by STew790** [comment]
**QA NOK**
I can scroll through the menu but I don't see the fiat. Is there any flag for this or should it just be there by default?

![image](https://github.com/trezor/trezor-suite/assets/48477147/cd28c47d-45ff-466a-b386-38939536685d)

24.6.0 814ab5d

**Comment by vytick** [comment]
@STew790 I have split this issue last week to make PR smaller and fiat balance is being added in the next task: #13099

**Comment by STew790** [comment]
**QA OK**
I see, otherwise it is OK then, approving.
