### ISSUE TITLE
Iconset replacement

### ISSUE THREAD

**Issue by shenkys** [trezor/trezor-suite#12433]
We've finally received the unified iconset where we're no longer using strokes which caused that we had to keep 5 different variants of each icon. Now we're using scalable stroke so no matter at what size you export it, it'll look consistently throughout. 

What we’ll need to do (likely) is to replace all the icons in the repo with new ones. I’d just need someone to check: 
- If the naming convention is the same 
- If we’re missing any icons
- If some icons aren’t matching
- Replace it in repo

[Outline.zip](https://github.com/user-attachments/files/16837224/Outline.zip)
source: https://www.figma.com/design/BdbvEYgjDdntL3haFcXRgV/%5BAssets%5D-Icons?node-id=1746-54&node-type=SECTION&t=u59DUGSGadXCIoTQ-11

**Comment by matejkriz** [comment]
It is a small and "easy" task, but not low hanging - testing can be time consuming (not days, but more than 2 hours...)

**Comment by matejkriz** [comment]
tech notes:
- current icons package will be renamed to `@suite-common/icons-deprecated` and the new iconset will go to new package with current name.
- There will be two variants for every icon - outlined and filled (marked in name of icon by the suffix)
- Both platform can shift to the new iconset independently
- We need to find a way how to ideally not include all the icons in the bundle but only those used. But that tooling should not be part of the shared package.
- Components like CryptoIcon, FlagIcon, Icon, should not be part of the new shared iconset anymore - the shared package should not depend on react-native at all.

**Comment by STew790** [comment]
**QA OK**
I haven't found any missing/broken icons throughout testing but will definitely monitor this.

**Info**
24.11.1 35433e7d5213f924061bc36bb74edf017bd39db0
