### ISSUE TITLE
Add feature flag to ETH staking

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12437]
Please add a feature flag to the Ethereum staking section, enabling it to be potentially turned off if necessary (e.g., if a third party goes offline). 
Additionally, implement a similar logic to that used in the CJ account, allowing us to display a context banner through the messaging system.

**Comment by tomasklim** [comment]
Should it have different parameters for disabling `staking`, `unstaking`, `claiming`? Because probably the "most" used case will be to disable just `staking`, but if we find out that `unstaking` method is somehow broken` maybe we will want to disable just it?

**Comment by MiroslavProchazka** [comment]
Yeah, that would be good! Good idea.
