### ISSUE TITLE
Change copy in the Update firmware modal for TS3

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12435]
Please change the current copy in the modal (Restart cour trezor...) to "Update Trezor firmware" 
![Untitled](https://github.com/trezor/trezor-suite/assets/152851523/a9eab790-f88e-484a-8e92-adb55970edb7)

**Comment by MiroslavProchazka** [comment]
Will be solved in Crowdin

**Comment by MiroslavProchazka** [comment]
DONE

**Comment by bosomt** [comment]
**QA OK**

but maybe we can consider follow up issue to align text properly /if left alligment is not expected, then disregard/

![Image](https://github.com/trezor/trezor-suite/assets/31506317/652ae903-0266-41d9-9bbd-e7cfd036841c)



![Image](https://github.com/trezor/trezor-suite/assets/31506317/e41054a6-5ab7-468e-85e7-f4936b2169e5)



**Info:**
 - Suite version: web 24.6.0 (f4408ff224e991759720931f540a569d4cd0b398)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 bitcoin-only (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 3.0.0
