### ISSUE TITLE
Wipe device dialog

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1243]
**[Zeplin](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5e4fcf5f79f38961aebe0e8f)**

Add confirmation & detail explanation of the action before the actual wipe.

**Comment by bosomt** [comment]
after device is wiped and you want to access your second device you need to disconnect first device or onboard it again, you can switch to different device

![image](https://user-images.githubusercontent.com/31506317/76771313-721a2b00-679f-11ea-8279-8e4bec5d6694.png)

**Comment by glacierbits** [comment]
Also check boxes should be aligned with the bold text (see Zeplin).
<img width="616" alt="Screen Shot 2020-04-08 at 18 12 16" src="https://user-images.githubusercontent.com/29627086/78808031-284eea00-79c5-11ea-8b74-207e7e2ac303.png">

**Comment by bosomt** [comment]
aligned and working fine ;)
