### ISSUE TITLE
Disable passphrase input suggestion

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1244]
Do not allow input suggestion (on Chrome).

<img width="1021" alt="Screen Shot 2020-02-25 at 10 01 56" src="https://user-images.githubusercontent.com/29627086/75231912-972a0800-57b6-11ea-9419-efd7ed8b07cd.png">

**Comment by slowbackspace** [comment]
AFAIK there is not an easy way to do it and we have talked about it forever (win wink https://github.com/trezor/trezor-suite/pull/779). Everything I tried failed (fake hidden inputs, magic values in autoComplete prop,...), maybe the situation will change, but right now Chrome reaaaally wants to autofill your passwords. I rather would not waste my time on this one. If anyone is willing and able to get it done, feel free to do so.

**Comment by glacierbits** [comment]
Thanks for the try @slowbackspace, I appreciate it! 

@szymonlesisz could you please have a look at this? I remember you sounded like you might know a solution to this. Thanks!

**Comment by szymonlesisz** [comment]
Those are possible known and already used solutions to this issue:

1. Use custom font where every char is a *
- Example: http://jsbin.com/juwuy/2/edit?html,css,output
- missing chars others than latin (chinese, russian, arab...), this font will be huge if we add support for all chars

2. Replacing chars with *
- possible unknown caret position (move caret position using arrows, start typing or worse, start deleting from the middle)
- keyboard shortcuts (ctrl + A > ctrl + V)

3. Overlay (one input above other)
- invisible caret position (blinking cursor) 

4. Runtime replace input elements (switch input element on "focusin"/"focusout")
- Example: https://jsfiddle.net/dcardoso/AeQJp/
- doesn't work anymore

5. Runtime replace input "type" attribute ("text" becomes "password" on "focusin" and get back to "text" after "focusout")
- doesn't work anymore

6. Set input id="new_password" attribute
- doesn't work anymore

7. -webkit-text-security: disc;
- webkit only :)

tag: @slush0  :)

**Comment by bosomt** [comment]
works fine now :)
