### ISSUE TITLE
Add option to enable/disable display brightness on T3T1 (UI)

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12442]
With the arrival of T3T1, device brightness will be introduced as a device feature. 
Please implement an option to turn this feature on or off in Suite settings - Device - Customization section - IF Debug mode is ON. Graphically, please use similar logic as with the PIN/Passphrase options. 

Please generate new protobuf message for this feature from this [PR](https://github.com/trezor/trezor-firmware/pull/3791)

Design wise it will be just turn ON / OFF, no slider etc. for now. 

Copy: 
"Enable brightness customization for the display on the device"

![image](https://github.com/trezor/trezor-suite/assets/152851523/861ee294-fc9f-4d97-8aa2-1c856c5772bf)
![image](https://github.com/trezor/trezor-suite/assets/152851523/7a5b7dbf-b8b4-484b-a6a1-76cef7c78b94)

**Comment by Hannsek** [comment]
> "Enable brightness customization for the display on the device"

More like _Trigger_ instead of _Enable_

**Comment by bosomt** [comment]
**QA OK**

i see options with TS5, no options with TS3



![Image](https://github.com/trezor/trezor-suite/assets/31506317/f07965e0-76aa-4288-ae52-b30c2aa57414)



**Info:**
 - Suite version: web 24.8.0 (510ba018179d967303bf00ac071e5ce0825e0b06)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 3.0.0
