### ISSUE TITLE
Can't select wabisabi coordinator?

### ISSUE THREAD

**Issue by GeetaCX** [trezor/trezor-suite#12447]
I run my own coordinator and can't find how to change to it in Trezor suite.

I understand you might want to ear coordinator affiliate fees but I think that's going away anyway at end of May.

**Comment by Hannsek** [comment]
Please take a look at our [blog post](https://blog.trezor.io/important-update-transitioning-from-coinjoin-in-trezor-suite-9dfc63d2662f).

**Comment by GeetaCX** [comment]
"This coordination is essential for the feature’s operation, and without it, we cannot sustain coinjoin in Trezor suite."

This is false, there are plenty of alternative coordinators.

You should not have hardcoded a single coordinator run by a corporation in the first place.
