### ISSUE TITLE
View-only: Warning about inability to verify the receiving address appears in portfolio tracker

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#12457]
Warning about not verified address is in portfolio tracker
Platform: Android

Steps to reproduce:
1. Sync asset in portfolio tracker 
2. Go to Receive
3. Click Show address
4. Warning about connecting the Trezor appears

**Expected behaviour**
Warning is not presented in portfolio tracker

<img width="350" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/e5ddf9f7-7eb4-4c05-830f-588659211cda">

**Comment by STew790** [comment]
**QA OK**
Not present in Portfolio tracker now.

24.5.1 https://github.com/trezor/trezor-suite/commit/319a98a62131c0d0ddd2eb238cb8530a540764a3
