### ISSUE TITLE
View-only promotion bottom sheet appears after View-only is disabled

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#12456]
View-only promotion bottom sheet appears after View-only is disabled

Steps to reproduce:
1. Enable view-only
2. Keep the device connected
3. Go to settings and disable View-only
4. Go back to dashboard - banner with promoting view only appears

Expected behaviour: Banner is not presented

Video: https://github.com/trezor/trezor-suite/assets/84183817/a55bbd20-46e9-4aaf-a43a-1b6a11b2384b

**Comment by vytick** [comment]
Solution agreed on with @mnuky and @matejkriz :

When user disables View only for any device/wallet in settings, we stop showing the banner for any device since then.

**Comment by STew790** [comment]
**QA OK**

View only banner is shown only for the first connected device. It is not shown when I disable view-only.

24.5.1 https://github.com/trezor/trezor-suite/commit/319a98a62131c0d0ddd2eb238cb8530a540764a3
