### ISSUE TITLE
View only: discovery interruption

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#12454]
**Describe the bug**
Interrupted discovery never continues.

**Info:**

-   Mobile Suite Version: 24.5.0 6516c718b79596480fd136a80440748af31247d8
-   OS: android

**How to reproduce**
- Disconnect device during discovery, discovery looks like still loading, but get stucked.
- When the device is plugged in again, it somewhat continues (discover more BTC accounts) but not properly (no more coins discovered)
- restart the app, discovery never runs again for the view-only device, no more coins discovered.

**Expected behavior**
~~Discovery should continue if device is connected. App has to indicate somehow incomplete discovery.~~
current mitiagion/workaround:
View only is not offered until discovery is completed. It is also not possible to enable it in settings while discovery is running. See the PR https://github.com/trezor/trezor-suite/pull/12516

**Comment by STew790** [comment]
**QA OK**
Discovery is interrupted and doesn't continue. View-only is enabled only after discovery finishes.

24.5.1 319a98a
