### ISSUE TITLE
Fix eject icon background on dark mode (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12467]
<img width="516" alt="Screenshot 2024-05-17 at 15 41 35" src="https://github.com/trezor/trezor-suite/assets/858321/a9c823f4-8a1f-4fa2-9fb0-09e4a15f0b26">

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2354-40396&t=03r75bJYrFjp9AqS-0

**Comment by bosomt** [comment]
**QA OK**

eject button match color mode

**Info:**
 - Suite version: web 24.7.0 (3185c54bc8a4499ef5cfd5825b01df02833cab80)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision 2e10618876be8a09a9d985098429f3016baf348e)
 - Transport: BridgeTransport 2.0.33
