### ISSUE TITLE
Passphrase: passphrase entry screen after PIN entry with feature flag disabled

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#12471]
**Describe the bug**
Passhprase screen is presented even with passphrase feature flag disabled after PIN entry.

**Info:**

-   Mobile Suite Version: develop-24.5.0/3e14473a21e65de47dcc6d1c1b3432e5ae5962b0
-   OS: android
- TT

**How to reproduce**
(see the video, trezor locked after finished discovery)

1. Wait for finished discovery
1. Do not enable view only
1. Do not enable passhprase feature flag
1. Lock the device (long press on screen for TT)
1. Exit Suite Lite
1. Open Suite Lite again
1. App ask for PIN entry on device
1. Enter the PIN on device
1. Passhprase screen is opened

**Expected behavior**
Discovery of standard wallet should start, no request for passhprase

**Screenshots**
https://github.com/trezor/trezor-suite/assets/3729633/782c7860-1799-490e-944d-5fd32a5726c2

**Comment by STew790** [comment]
**QA OK**
Can't reproduce.

24.6.0 https://github.com/trezor/trezor-suite/commit/29914f27123785daa59f0b4a89ffc25a2ff67e30
