### ISSUE TITLE
New account can't be added, it is not loaded

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#12478]
It is not possible to add new account with connected Trezor, there is loading screen forever. 

Platform: Android
Last commit hash: 3e14473

Video enclosed:
https://github.com/trezor/trezor-suite/assets/84183817/3ddfbdbe-03e2-4a0c-aa15-1048a20bc7d9

**Comment by STew790** [comment]
**QA OK**
Show address is showing address correctly.

24.5.1 https://github.com/trezor/trezor-suite/commit/319a98a62131c0d0ddd2eb238cb8530a540764a3
