### ISSUE TITLE
Trezor Model One - unsupported coins

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#12483]
Create a new category of coins in coin settings for Trezor Model One, similarly as there already are Coins and Testnet coins.

The coins buttons should be inactive.

There should be a question mark icon (same as at Testnet coins). On hover it will say "These coins are supported on Trezor Safe family devices and the Trezor Model T."

Design mockups:
- [Settings](https://www.figma.com/design/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?node-id=882-1086&t=ZbtInoruEiDYe2b9-1)
- [Onboarding](https://www.figma.com/design/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?node-id=882-1117&t=ZbtInoruEiDYe2b9-1)
    - Opened dropdown menu will be a clone of the Testnet dropdown menu (just with appropriate inactive unsupported coins inside)
- [Add account menu](https://www.figma.com/design/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?node-id=882-1092&t=ZbtInoruEiDYe2b9-1)
    - Opened dropdown menu will be a clone of the Testnet dropdown menu (just with appropriate inactive unsupported coins inside)
    - While at it, please add a question mark icon and tooltip also for Testnet coins, it's missing here although it's present in both Settings and Onboarding

**Comment by bosomt** [comment]
**QA NOK**

this is what you see when you connect device with BTC only FW
is that expected or reopen ? @adamhavel @Hermez-cz @MiroslavProchazka 



![Image](https://github.com/user-attachments/assets/28f1600f-3273-417f-b8fc-e21ca269762f)


**Info:**
 - Suite version: web 24.8.0 (b8a30db81eb48ee909e78d15c1b958f669c71df6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.12.1 bitcoin-only (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.32

**Comment by MiroslavProchazka** [comment]
@adamhavel Please remove it for BTC only FW, it should appear only on Universal FW. Thanks!
