### ISSUE TITLE
"Your browser is not supported" modal/page improvements - Suite web

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#12486]
Currently "Your browser is not supported" modal/page is displayed before accessing Suite web or Connect popup on any browser except Chrome and Firefox.
However, all features should work as expected on almost all Chromium-based browsers. 

- [ ] Create a better conditions for supported (Chromium-based) browsers so the modal doesn't has to be displayed for all non-Chrome/Firefox browsers

With the deprecation of support of Firefox browsers due to the deprecation of Trezor Bridge, 
- [x] remove Firefox from the list of supported browsers

![image](https://github.com/trezor/trezor-suite/assets/57008159/e255aaa8-60fc-4d4b-9f8a-cbf2a47ab16a)

**Comment by STew790** [comment]
**QA NOK**
I can still see on Brave, Edge and Opera the unsupported browser modal

**QA OK**
FF is no longer amongst the supported browsers

**Info:**
 - Suite version: web 24.8.0 (70de4d61928122fa2b43fde47f0e2248a1df364f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: BridgeTransport 2.0.33

**Comment by martykan** [comment]
Sorry, the browser support was updated only in Connect but not in Suite. Making a PR now.

**Comment by STew790** [comment]
**QA OK**
Works on Arc and Brave and Edge.

**Info:**
 - Suite version: web 24.7.3 (19fd64f5b2ab1bc265821e34d4c4b9c910864d0e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T3T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
