### ISSUE TITLE
Receive address is not displayed on Trezor device

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#12480]
**Steps to reproduce:**
Connect the Trezor and set the View on on Enabled
Disconnect the Trezor
Connect the Trezor again
Click on Receive and Show full address
Address is displayed on mobile screen but not on the Trezor device
Note: I have multiple device in View-only

Video:
https://github.com/trezor/trezor-suite/assets/84183817/eb5eb0e7-88ac-4a3e-beeb-772a26db41ca

**Comment by STew790** [comment]
Receive address displayed on device correctly, although for some reason when it is the first time after a connection of the device, I can see 3 times loading on the device, then slight delay and after that the address is shown. Every subsequent address showing is normal after that.

cc @mnuky let me know if this is OK or not

24.5.1 https://github.com/trezor/trezor-suite/commit/319a98a62131c0d0ddd2eb238cb8530a540764a3

**Comment by matejkriz** [comment]
> Receive address displayed on device correctly, although for some reason when it is the first time after a connection of the device, I can see 3 times loading on the device, then slight delay and after that the address is shown. Every subsequent address showing is normal after that.
> 
> cc @mnuky let me know if this is OK or not
> 
> 24.5.1 [319a98a](https://github.com/trezor/trezor-suite/commit/319a98a62131c0d0ddd2eb238cb8530a540764a3)

Issue created: https://github.com/trezor/trezor-suite/issues/12563
