### ISSUE TITLE
Browser extensions popup showing 404 page

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#12499]
**Describe the bug**
I was testing the new 9.2.4-beta.1 connect and the browser extensions and both mv2 and mv3 are showing 404 status page when trying to open the popup. (screenshots from mv2)

**Screenshots**

![image](https://github.com/trezor/trezor-suite/assets/48477147/aa57e654-7c08-425b-9190-c5f2aae14408)
![image](https://github.com/trezor/trezor-suite/assets/48477147/bab5a021-dc9d-43e4-9d6f-6e7f641b5522)

**Comment by karliatto** [comment]
At least part of it should be possible to test it in the artifacts in this workflow https://github.com/trezor/trezor-suite/actions/runs/9173559613?pr=12504

The part of supporting of staging will have to wait for next canary release to be tested.
