### ISSUE TITLE
Connect another device button in device switcher during discovery puts app into bad state temporarily

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#12512]
**Describe the bug**
You might get locked in connect device screen while other discovery is running.

1. When the discovery is running, click button in device switcher -> you get to connect device screen. 
2. If you then click close, you are prompted to insert pin on device even in case you dont have it set. 
3. Also you are unable to leave the screen until the discovery ends.`

https://github.com/trezor/trezor-suite/assets/2011829/8658a840-0ed6-4896-9aee-681841394576

Correct behaviour:
Until discovery ends, we dont show Connect another device button in device switcher

**Comment by STew790** [comment]
**QA OK**
There is no "Connect another device" during discovery.

24.5.1 https://github.com/trezor/trezor-suite/commit/319a98a62131c0d0ddd2eb238cb8530a540764a3
