### ISSUE TITLE
Switch to portfolio tracker sent user to empty dashboard instead of sync coin

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#12524]
1. Open the app
3. Connect device
4. Enable view-only
5. Disconnect device
6. Try to switch from disconnected device to portfolio tracker
7. You are redirected to "empty dashboard"

Video: 
https://github.com/trezor/trezor-suite/assets/84183817/5f081569-4731-4b4f-a45e-316a7fca7cc1

Version: 24.5.0, Last commit hash: 5e5d8a3

**Comment by STew790** [comment]
**QA OK**

24.5.1 https://github.com/trezor/trezor-suite/commit/319a98a62131c0d0ddd2eb238cb8530a540764a3
