### ISSUE TITLE
Firmware upgrade from 2.1.1 never starts

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12528]
**Describe the bug**
- im not able to onboard old device with 2.0.5 firmware /before storage upgrade/
- upgrade **2.0.5 > 2.1.1** works as expected  ✅ 
- but **2.1.1 > 2.7.0** never starts even after i try to reconnect device in BL mode even im not asked. ❌ 
- f you start with device in bootloader mode you can upgrade to 2.7.0 see screenshot

**Steps to reproduce:**
1. Connect device with 2.1.1 firmware and no seed
2. Try to upgrade to current 2.7.0
3. Observe that installation never starts

**Info:**
 - Suite version: desktop 24.6.0 (f48ce5b81db91a7a2ce25e23554292b5eaee44cd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.1.1 undefined (revision null)
 - Transport: BridgeTransport 3.0.0

**Screenshots:**
https://youtu.be/3rupJrS0pIQ

<img width="609" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/7f5889c5-4a52-4410-b762-ad4ee2c50e6d">

**Comment by bosomt** [comment]
Managed to reproduce it it on production version with old bridge.
Upgrade as seen on screenshot never starts

<img width="1053" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/73204f15-5046-45a1-809b-95b7fd373f58">

**Info:**
 - Suite version: desktop 24.5.2 (1ca8b8063fd7028d1fe242db41caa31c0a1f7d5a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.0.5 regular (revision 8852fb54)
 - Transport: BridgeTransport 2.0.33

**Comment by Hannsek** [comment]
cc @komret @mroz22

**Comment by bosomt** [comment]
Works as expected in 24.4.3 version, 
Looks like problem during on-boarding that  we dont expect that we need upgrade from old model T storage via 2.1.1 firmware 


**Info:**
 - Suite version: desktop 24.4.3 (41c16dcd8caf5cc9501a038608d3e4d2cd50baf7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: BridgeTransport 2.0.33

**Comment by mroz22** [comment]
it looks like suite isn't correctly reacting to events from connect

![image](https://github.com/trezor/trezor-suite/assets/30367552/21f073a4-5a83-4d92-a51a-4667b0e4397f)

suite should render a screen telling you to reconnect your device manually in  bootloader mode. 

when I reconnect manually in bootloader mode at this moment, it works as expected

**Comment by komret** [comment]
@bosomt This is broken for all firmwares requiring manual reconnection while being upgraded in onboarding, i.e. < 1.10.0 or < 2.6.0.

**Comment by bosomt** [comment]
**QA OK**

tested by onboarding empty Model T device with 2.1.1 FW 

**Info:**
 - Suite version: web 24.7.0 (2805d01872de7b7dfc542aa70e1d2f31cb704d36)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: BridgeTransport 2.0.33
