### ISSUE TITLE
MetaMask opens second Trezor Connect popup after transaction is confirmed on Trezor 

### ISSUE THREAD

**Issue by evgenysl** [trezor/trezor-suite#12547]
**Describe the bug**

Not sure if it's MetaMask or Trezor Connect bug.

1. I send a transaction in MetaMask
2. I enter passphrase and confirm transaction on Trezor
3. After a short time, second Trezor Connect popup opens in a new tab where I need to confirm transaction again (without entering the passphrase for the second time)
4. Meanwhile, transaction is getting confirmed on blockchain (see video).
5. If I proceed with second Trezor Connect popup, I need to confirm transaction (address, fee) again 
7. "Second" transaction is showing as failed in MetaMask
8. Actual first transaction is confirmed on the blockchain (see Trezor Suite on video)

Attaching videos:

https://github.com/trezor/trezor-suite/assets/63164324/a9298ba3-659f-4a14-a00c-7031401ffee5

https://github.com/trezor/trezor-suite/assets/63164324/2f611f88-a94f-4841-b1f3-8a2408561469

Reported at https://www.reddit.com/r/TREZOR/comments/1cuaih5/trezor_problems_in_metamask_and_rabby/

**Comment by martykan** [comment]
Has this popped up recently? If I remember we weren't able to replicate this last time

**Comment by martykan** [comment]
Closing this since we don't have reports of this happening recently
