### ISSUE TITLE
App does not warn you about wipe when switching firmware type

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12558]
**Describe the bug**

- App does not warn you about wipe when switching firmware type
- wrongly used "recovery seed" instead of "wallet backup" 

Discussion here https://satoshilabs.slack.com/archives/G019WLX2P7B/p1716553429915749

**Steps to reproduce:**
1. Connect model T with backup failed
2. Navigate to settings
3. Try to change firmware type

**Info:**
 - Suite version: desktop 24.6.0 (6c0926389c44dc418d086fa992e04fcf9be727a7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 3.0.0

**Screenshots:**
<img width="629" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/863af3e3-9fd4-46a6-85a6-37d3997e40d9">

**Comment by komret** [comment]
> **Steps to reproduce:**
> 
> 1. Connect model T with backup failed

The warning should never be shown on TT or T1 because it only wipes TS3 or later models. It was broken for all cases, not just failed backup - the warning was never displayed. Should be fixed by the PR.

**Comment by bosomt** [comment]
**QA OK**

@komret yes i know :) but i totally forgot about it when i was creating issue :) 
Tested on TT and T3 by updating it and it worked as expected

**Info:**
 - Suite version: web 24.6.0 (e9a042518338e1b23fbf1542d4f08ea64dd930cd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.7.0 bitcoin-only (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
