### ISSUE TITLE
connect explorer - negative address_n values 

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#12568]
![image](https://github.com/trezor/trezor-suite/assets/30367552/037228b7-3663-4dde-b396-c1ea7c7c7358)

also please make Bitcoin the default, not Bitcoin cash 🙏 

![image](https://github.com/trezor/trezor-suite/assets/30367552/dd26c9b1-3326-49d2-b983-a4a41535ec97)

**Comment by bosomt** [comment]
**QA OK**

success: true at https://connect.trezor.io/9/methods/bitcoin/signTransaction/
