### ISSUE TITLE
Device not detected after reboot to bootloader

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12560]
**Describe the bug**

Device not detected after reboot to bootloader, im not happen to reproduce it with 100% rate.
It happens before install of firmware, after reboot /after firmware installation/
Reconnect of device or reload or restart of app does not help /i will create follow up issue/

I was only able to reproduce it on Windows computer and not on macARM computer.
Same behavior when connected directly or via hub.
Same behavior when connected external mouse and keyboard.

Info:
 - Suite version: desktop 24.6.0 (b6ccc949b30d2c22cfc9a3e59bfe0459a32dc693)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.7.0 regular (revision null)
 - Transport: BridgeTransport 3.0.0

**Screenshots:**
![telegram-cloud-photo-size-4-5947173913089916918-y](https://github.com/trezor/trezor-suite/assets/31506317/fe38a396-db14-4d7c-8e97-f57caf0e5294)

**Comment by bosomt** [comment]
**QA OK**

tested node bridge for multiple devices and updates, 100% success 🎉 

# TT
- Universal 2.7.2 Bitcoin-only 2.7.2 fw type switch
- Bitcoin-only 2.7.2 Bitcoin-only 2.7.2 fw reinstall **2x**

# TS3
- Universal 2.8.0 Universal 2.8.0 **3x**

# TS5
- Universal 2.8.0 Universal 2.8.0 **3x**

**Comment by MiroslavProchazka** [comment]
cc @mroz22 is it worth fixing and cherry-picking into 24.7 or we will leave it to 24.8?

**Comment by mroz22** [comment]
and isn't it already part of the latest release?

**Comment by MiroslavProchazka** [comment]
Ah, you are right. It's already in the 24/7 branch, thanks! :)
