### ISSUE TITLE
Trezor safe 3: same pin input method as for Trezor one

### ISSUE THREAD

**Issue by dr-ni** [trezor/trezor-suite#12572]
Is it also for Trezor safe 3 possible to enable optional the pin input from the device directly (no button input)?
I' m disabled and cannot input pin with the buttons - but the method as used for Trezor one is easily possible.
This would be a very helpful improvement.

**Comment by Hannsek** [comment]
Hi, thanks for the report. We are not currently planning to do so, however we are thinking about implementing some accessibility measures, unfortunately not in the near future.

Btw, would one button entry help?

I close this issue, but feel free to continue in the discussion.

**Comment by dr-ni** [comment]
> Hi, thanks for the report. We are not currently planning to do so, however we are thinking about implementing some accessibility measures, unfortunately not in the near future.
> 
> Btw, would one button entry help?

no, it doesn't help
