### ISSUE TITLE
feat(coinmarket): complete redesign & refactoring

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#12585]
## Information
The changes are in the associated pull requests.
## List of PRs:
- https://github.com/trezor/trezor-suite/pull/12582
- https://github.com/trezor/trezor-suite/pull/12584
- https://github.com/trezor/trezor-suite/pull/12604
- https://github.com/trezor/trezor-suite/pull/12708
- https://github.com/trezor/trezor-suite/pull/12735
- https://github.com/trezor/trezor-suite/pull/12745
- https://github.com/trezor/trezor-suite/pull/12891
- https://github.com/trezor/trezor-suite/pull/13116
- https://github.com/trezor/trezor-suite/pull/13012
- https://github.com/trezor/trezor-suite/pull/13080
- https://github.com/trezor/trezor-suite/pull/13387
- https://github.com/trezor/trezor-suite/pull/13540

### Figma - Trade section
https://www.figma.com/design/xSW1knAjH25SfOmqSdNioY/Trade?node-id=1-104&t=0nEmCm0ceufJAI1k-1

**Comment by bosomt** [comment]
**QA OK**

deployed to 24.8.1
found issues have separate issues
 - Suite version: desktop 24.8.1 (738a69170a50b3c76ead3dac6b6e200e564b2e50)
