### ISSUE TITLE
 feat(coinmarket): redesign buy offers

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#12587]
## Information
Visual redesign of current comparison screen for buy.
Without additional filters.
Offer will be shared component for other screens - exchange and sell

## Design
**Design note**: There is a slight difference between the currently developed design and the design below. The filter will be developed later, so the amount of crypto is temporarily placed next to the filter.
![Version_1_buy](https://github.com/trezor/trezor-suite/assets/15160619/17cade52-6e7a-4596-8869-b522f30967d6)

**Comment by STew790** [comment]
@adderpositive Can we test this in develop already? I can still see the old page of offers
![image](https://github.com/trezor/trezor-suite/assets/48477147/90430ba1-aae0-4de9-91f8-36d5d75a5fb1)

**Comment by adderpositive** [comment]
@STew790 No, it is only in the `feat/coinmarket-redesign`. I have created small branches, like this one, and pushed them to `feat/coinmarket-redesign` (https://github.com/trezor/trezor-suite/pull/12586).
