### ISSUE TITLE
Duplicite passphrase error (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12590]
It's happening that it shows modal with passphrase duplicate when you create standard wallet

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2354-40396&t=03r75bJYrFjp9AqS-0

**Comment by bosomt** [comment]
**QA OK**


![Image](https://github.com/trezor/trezor-suite/assets/31506317/4f67327c-395c-49cd-aea5-aeaaae46fab5)



**Info:**
 - Suite version: web 24.7.0 (87a1ef738cd9557e8d447be74b6eb438d1691c8d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
