### ISSUE TITLE
Skipping seed backup and backing up seed in settings defaults to multiseed Shamir

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#12596]
**Describe the bug**
When I select the single shamir backup in the onboarding but I skip the backup part and back up my seed in the settings after finishing the onboarding, the backup only shows me the "full" Shamir and not the single 20 word seed Shamir that I selected in the onboarding.

**Steps to reproduce:**
1. Start onboarding with wiped device with new 2.7.1 FW.
2. Continue the onboarding until seed selection
3. Select single Shamir (for TS3 will be default)
4. Skip the backup part
5. Continue until discovery
6. Click on the red banner showing you need to backup your seed
7. The backup on your device shows you full Shamir instead of the single Shamir

**Info:**
 - Suite version: desktop 24.6.0 (8d8029424601f267f8c8e231ba25da18dec49e68)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: BridgeTransport 2.0.32

```[tasklist]
### Tasks
```

**Comment by STew790** [comment]
**QA OK**
Skipping the backup and doing it in the settings for 20 word seed shamir now correctly shows again 20 word seed shamir for 2.7.1 FWs.

**Info:**
 - Suite version: web 24.6.0 (d5b518f0f76f227a66ea0b0b7a4c7763c8bee2bf)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: BridgeTransport 3.0.0

**Comment by MiroslavProchazka** [comment]
After skiping backup Suite allows you to do the Additional Multi-shares

**Comment by Hannsek** [comment]
It is a different issue.
