### ISSUE TITLE
Error while connecting Trezor appears as an uninitialized device

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#12603]
# Bug

From time to time there is some error while connecting Trezor (we can't reproduce it consistently) but app present that error as uninitialized device:
<img width="200" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/d6ff9254-ee22-44ae-a5b7-ec7e8b328e54">

<details>
  <summary>Example of device state in that case</summary>

  ```js
{
selectedDevice: {
  available: false,
  buttonRequests: [],
  connected: true,
  error: "Initialize failed: unexpected error ",
  label: "Unreadable device",
  metadata: {},
  name: "Trezor",
  path: "21095CA051AA872F01416C1C",
  ts: 1716801174952,
  type: "unreadable",
  useEmptyPassphrase: true,
}
}
  ```
</details>

# Solution
We need to show general error instead and navigate user to reconnect the device. See screenshots below and follow [figma link](https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?node-id=482-4228&t=IYUGy4yCtouxmmha-4).

- Underlying error should be reported to Sentry if analytics are allowed.
- `Reconect device` button should disconnect the unreadable device and navigate to `ConnectAndUnlockDevice` screen.
- `Contact support` button should lead to https://trezor.io/learn/c/trezor-suite-lite#open-chat

<img width="260" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/ee6d64e7-04eb-4904-b8b8-cf076865bc45">
<img width="260" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/ca2423c1-cfb9-47bf-bd6b-6841f700c5a7">

[Figma](https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?node-id=482-4228&t=IYUGy4yCtouxmmha-4)

**Comment by STew790** [comment]
**QA OK**
I haven't encountered this error while testing. (Before it was definitely happening from time to time)

**Info:**

24.6.0 https://github.com/trezor/trezor-suite/commit/814ab5d0df52939057bfa7643e7c0a83012e86f7
