### ISSUE TITLE
Push a message via banner to users with fw version <1.7.0 about updating their fw

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#12624]
Banner copy: `Please update device firmware now: Your Trezor will not be recognized or usable in new versions of Trezor Suite.`

**Comment by MiroslavProchazka** [comment]
Do we want to put there some CTA button?

**Comment by Hannsek** [comment]
yes, that would be nice, didn't know we can tho. Let's put there a button with deeplink to settings. Simmilar to what we have in _backup failed_ banner.

**Comment by MiroslavProchazka** [comment]
Resolved by https://github.com/trezor/trezor-suite/actions/runs/9287745344


https://github.com/trezor/trezor-suite/assets/152851523/043608dd-c489-4ae6-87a0-fbbcd0c1fc20

**Comment by STew790** [comment]
**QA OK**
Tested with FW 1.5.0.

![image](https://github.com/trezor/trezor-suite/assets/48477147/fe2aab60-9530-4563-9eaf-c23a4235cca2)

**Info:**
 - Suite version: web 24.8.0 (f65530492c89854af6495e39b50e3780d9950565)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T1B1 1.5.0 regular (revision 6b74139b4530a4687b4a317b8b08f4329704efc4)
 - Transport: BridgeTransport 2.0.33
