### ISSUE TITLE
Receive address identified as BTC receive address even its Solana or Ethereum

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12631]
**Describe the bug**
Receive address identified as `BTC receive address` even its Solana or Ethereum.
Not sure when it happens, im not able to reproduce it after i tried older version.
But i had BTC,ETH and SOL enabled and all of them were identified as BTC at one time /see screenshots/

**Info:**
 - Suite version: desktop 24.5.3 (0ff3e0bd75d90719b7b36a60b3eab1c2bd3d3491)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
Solana:

![image](https://github.com/trezor/trezor-suite/assets/31506317/6d83f378-a038-4c39-89ac-c27c2b719b85)

Eth:

![image](https://github.com/trezor/trezor-suite/assets/31506317/5f245eaa-cafb-4dd5-b2ed-4dc5000a68d8)

**Comment by bosomt** [comment]
How to reproduce https://youtu.be/PAHchoJL2JA

Looks like its related to Invity/Trade section.
Its happening again after i created exchange offer 

<img width="579" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/9fb24d99-0f59-4fdf-a46a-35e35e4918db">

**Comment by tomasklim** [comment]
https://github.com/trezor/trezor-suite/pull/11937 @adderpositive 

```
const receiveSymbol = useSelector(
        state => state.wallet.coinmarket.exchange.quotesRequest?.receive,
    );
```

**Comment by bosomt** [comment]
**QA OK**

tested receive, exchange, receive, exchange, receive and all modals had expected coin name

**Info:**
 - Suite version: desktop 24.6.0 (e9a042518338e1b23fbf1542d4f08ea64dd930cd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
