### ISSUE TITLE
backup type selection with older firmwares

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#12645]
backup type selection is displayed even for firmware that do not support offered backup types. 

With firmware 2.1.1 

<img width="1086" alt="image" src="https://github.com/trezor/trezor-suite/assets/30367552/b803b641-e500-4d2d-90ad-b471258ed724">

**Comment by MiroslavProchazka** [comment]
cc @peter-sanderson Shamir was introduced to TT as of 2.1.13 https://github.com/trezor/trezor-firmware/blob/main/core/CHANGELOG.md#added-24

**Comment by MiroslavProchazka** [comment]
Resolved by this https://github.com/trezor/trezor-suite/pull/12739

**Comment by STew790** [comment]
**QA OK**

Can't access multishare on TT with FW lower then 2.1.3.

**Info:**
 - Suite version: desktop 24.6.1 (f640a29f7ac7cc7bdac9259531267689d66e64e9)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
