### ISSUE TITLE
Single-share wallet backup prompts device to generate Multi-share on TT

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12658]
While doing wallet backup on TT, when user selects Single-share backup, device shows wallet backup for Multi-share. 

Please find more info [here](https://www.notion.so/satoshilabs/Multishares-backup-in-Suite-b57187a0481646e5aca4d5245371f50d?pvs=4)

**Comment by STew790** [comment]
The same is for T3T1 

**Info:**
 - Suite version: desktop 24.6.0 (6d165800ee73c0f6c6286c3257af8fd14bcc0ae4)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.7.1 bitcoin-only (revision 003461419b93fa765ab45e66f295de9c9ab82b36)
 - Transport: BridgeTransport 2.0.32

**Comment by STew790** [comment]
**QA OK**
Both TT and TS3 correctly showing 20 word multi-share.

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
