### ISSUE TITLE
Strange Problem with passphrase protected wallets on different maschines. Derivation Problem?

### ISSUE THREAD

**Issue by fschell** [trezor/trezor-suite#12653]
I have problems with my Trezor T and Safe3 on a specific Windows system and under Ubuntu. In both cases, I connect the Trezor and enter the correct passphrase, which is correctly displayed and confirmed on the device. This works perfectly on my notebook with updated Windows 10 and my MAC with Sonoma 14.5 and I can see the funds. BUT under Ubuntu and my workstation (also updated Windows 10) both reported an empty wallet. How can that be?
I use Trezor Suite 24.4.3 in all cases. On the workstation (Windows 10 Pro 22H2 19045.4412) I updated to version 24.5.2, which unfortunately does not change the result. The Safe3 has firmware 2.7.0.
On my notebook (i.e. Windows 10 Pro 22H2 19045.4412) with 24.4.3 everything works as expected and the assets are displayed.

How can it be that the addresses are derived differently? Or could there be other reasons? The passphrase was entered correctly every time, this was always checked very carefully, both in the suite and on the device.

**Comment by fschell** [comment]
The Trezor T runs now also with firmware 2.7.0 but the failure remains on workstation (ubuntu not testet).

**Comment by Hannsek** [comment]
Do you see different addresses in the same account? E.g. `Bitcoin #1`?

**Comment by fschell** [comment]
Yes, Ethereum #1 and Cardano #1, if you mean this

Von: Jan Šetina ***@***.***>
Gesendet: Donnerstag, 30. Mai 2024 14:46
An: trezor/trezor-suite ***@***.***>
Cc: Folker Schellenberg ***@***.***>; Author ***@***.***>
Betreff: Re: [trezor/trezor-suite] Strange Problem with passphrase protected wallets on different maschines. Derivation Problem? (Issue #12653)


Do you see different addresses in the same account? E.g. Bitcoin #1?

-

**Comment by Hannsek** [comment]
No, I mean if you see the different addresses under the "same" passphrase in the same account on different computers.

**Comment by fschell** [comment]
Oh dear, I shot myself in the foot there. During the test I found that Ethereum was not set up on the affected Trezor installations and therefore the default Bitcoin wallet naturally appeared to have never been used.

Sorry, my mistake. I'm closing the issue. Thanks for the right questions.

**Comment by fschell** [comment]
Oh dear, I shot myself in the foot there. During the test I found that Ethereum was not set up on the affected Trezor installations and therefore the default Bitcoin wallet naturally appeared to have never been used.

Sorry, my mistake. I'm closing the issue. Thanks for the right questions.
