### ISSUE TITLE
Replace Staking TX showing raw contract address instead of "Stake ETH with Everstake"

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#12662]
* Bumping shows the contract address, and not the message visible on Trezor.
* Duplicate TX in transaction list when replacing

![Image](https://github.com/trezor/trezor-suite/assets/216917/20f0d878-8050-458f-922f-2c15fdefeda2)

![Image](https://github.com/trezor/trezor-suite/assets/216917/0679eecc-9699-4f75-b5b2-6cb0483cac25)

![Image](https://github.com/trezor/trezor-suite/assets/216917/e94fee75-e189-4188-aaa0-3a052b42ceb0)

**Comment by Hannsek** [comment]
![image](https://github.com/trezor/trezor-suite/assets/57008159/54bef6fa-19be-4f78-ba68-f7aa54f95a32)
so this is a contract address?

which message would you expect to see?

**Comment by sime** [comment]
Stake with ETH with Everstake. (FW already shows it)

**Comment by Hannsek** [comment]
It was not clear that you meant bumping _staking_ transaction.

**Comment by tomasklim** [comment]
fixed in #13076

**Comment by bosomt** [comment]
not sure if it was fixed properly as 
 - unstaking bump shows 0 /first screenshot/
 - unstaking bump detail Missing fee info /second screenshot/
 - unstaking bump detail Account info actually shows fee info /see third screenshot/

_1_
![telegram-cloud-photo-size-4-5769289398620374453-y](https://github.com/trezor/trezor-suite/assets/31506317/36a825a3-12a4-41b1-8d48-e352a3c36c4b)

_2_
<img width="312" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/bbdd2744-07b6-4ca4-9455-b4be889334fc">

_3_
<img width="342" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/8cb64361-3836-4968-99a8-c1917ddec6da">

**Comment by MiroslavProchazka** [comment]
cc @tomasklim is it worth fixing and cherry-picking into 24.7 or we will leave it to 24.8?
