### ISSUE TITLE
Rabby Wallet Requests Bitcoin Instead of Ethereum Addresses

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12664]
While connecting  Rabby Wallet with Trezor,  Trezor connect is claiming that Rabby Wallet is requesting Bitcoin addresses instead of Ethereum one.

https://github.com/trezor/trezor-suite/assets/152851523/15b76ab9-dbcc-4043-9316-3cf5169a738d

**Comment by Hannsek** [comment]
Probably not a connect issue. Closing it for now.

**Comment by bosomt** [comment]
already released and tested
