### ISSUE TITLE
Input field refactor

### ISSUE THREAD

**Issue by shenkys** [trezor/trezor-suite#12672]
As a part of the passphrase project, we've encountered a mismatch in the design of inputfields. 

Design: 
the height of the "input" element is 56 px

Prod: 
the height of the "input" element is 64 px

when discussed with @juriczech, it shouldn't bee too much of work on dev and no work on design. 

As the component is global, the change should then easily propagate all around. What we should check prior to releasing it, is if it changes/breaks the layout structure anywhere in the app. 

As a part of this, let's also add border for both default & focus states of the inputfield. This requires adding 2 design tokens.

**Comment by STew790** [comment]
**QA OK**
Portfolio tracker with XPUBs and Send form checked

**Info:**
24.8.2  dev e722418 both Android and iOS
