### ISSUE TITLE
connect-popup - install bridge page broken UI (misaligned header)

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#12673]
![image](https://github.com/trezor/trezor-suite/assets/30367552/f585f102-bd5d-47fe-90d1-63501c5f2597)

**Comment by mroz22** [comment]
and maybe if suite is running display a button with a deeplink to it?

**Comment by Hannsek** [comment]
If it is running? Then you won't need to do anything.

It would be nice to have that deeplink if Suite is not running.

**Comment by bosomt** [comment]
**QA OK**

https://connect.trezor.io/9/popup.html

`Install Bridge` message aligned
