### ISSUE TITLE
Remove canary version when new stable version is released

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#12683]
https://satoshilabs.slack.com/archives/C02V2PSDNA2/p1717309082222399

**Comment by bosomt** [comment]
**QA OK**

checked at 
https://github.com/trezor/trezor-suite/blob/develop/packages/connect/CHANGELOG.md



![Image](https://github.com/trezor/trezor-suite/assets/31506317/67beac66-3120-41d7-b642-f3a47fc63ac0)

**Comment by Hannsek** [comment]
@karliatto can we center the "-"?

**Comment by karliatto** [comment]
> @karliatto can we center the "-"?

@Hannsek something like this?

https://github.com/trezor/trezor-suite/pull/12751
