### ISSUE TITLE
Onboarding - restrict using of SLIP 39 extendable seed only for devices with newer FW

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12701]
Please add a condition that only devices with firmware version 2.7.1 (TT/TS3) or later can use the new Slip 39 extendable seed wallet backup.

All devices with firmware version 2.7.0 and older will not be able to do this (fields will be deactivated).  Please add a tooltip on hover with the following copy:

“Please update your device firmware to enable the new Single-share / Multi-share Backup feature.”

**Comment by STew790** [comment]
**QA OK**
TT 2.7.0 FW and TS3 2.7.0 FW
![image](https://github.com/trezor/trezor-suite/assets/48477147/6387f4c5-c374-4032-836b-1afbdc5a7c10)

**Info:**
 - Suite version: desktop 24.6.0 (30824d1961aa4a95879be2a4e23196c152f54ef8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
