### ISSUE TITLE
feat(coinmarket): redesign sell offers

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#12707]
## Information
- Visual redesign of current comparison screen for sell.
- Without additional filters.

## Design
- Same design as it is presented here: https://github.com/trezor/trezor-suite/issues/12587

**Comment by STew790** [comment]
@adderpositive same as https://github.com/trezor/trezor-suite/issues/12587

**Comment by adderpositive** [comment]
@STew790 sorry for making a mess. I'm not going to continue to create these issues, just PRs.
