### ISSUE TITLE
Enter passphrase on Trezor not offered on T1

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#12703]
On passphrase form, `Enter on Trezor` should only be available for devices that enable this functionality and T1 is not one of them. So we should remove it for that device.

**Comment by STew790** [comment]
**QA OK**
Passphrase on device option is not available for T1.

**Info:**

24.6.0 https://github.com/trezor/trezor-suite/commit/c747f2a42759f6804364b7bfbe32010124172b76
