### ISSUE TITLE
Skip TS5 tutorial during onboarding

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12700]
Please skip tutorial in Suite for TS5 since it will not be supported from the beginning.

**Comment by MiroslavProchazka** [comment]
On connect side it's this [string](https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/data/config.ts#L240)

**Comment by komret** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/12740

**Comment by STew790** [comment]
**QA OK**
Tutorial is not present for T3T1

**Info:**
 - Suite version: web 24.6.0 (3a3ddc11049e181d849a7cee2ff0bc7268b243b7)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.7.1 regular (revision 510121bad342d1f900ca123e131448d577a25e39)
 - Transport: BridgeTransport 2.0.33
