### ISSUE TITLE
Remove "my portfolio balance headline"

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#12709]
Remove the headline "My portfolio balance" from connected trezor area. 

With introducing passphrase and view-only where user can have more devices in view-only and passphrase it is confusing for users, what does it mean as it can make impression that it is a total of everything they have on all wallets / devices

**Comment by STew790** [comment]
**QA OK**
Now it only shows "Porfolio tracker" in the connected trezor area.

**Info:**

24.6.0 https://github.com/trezor/trezor-suite/commit/c747f2a42759f6804364b7bfbe32010124172b76
