### ISSUE TITLE
Longer indication label for passphrase discovery

### ISSUE THREAD

**Issue by shenkys** [trezor/trezor-suite#12719]
We need to indicate that the passphrase discovery might take a while. 

For this purpose, we'll add a smaler text below the label when loading. 

Link to figma [here](https://www.figma.com/design/mmDnYtctfjnreWhTjLfeQH/Passphrase?node-id=2350-73720&t=zSlSsyD2w6IXuXa3-11)

**Comment by STew790** [comment]
**QA OK**
The screen shows when connecting a passphrase wallet.

**Info:**

24.6.0 https://github.com/trezor/trezor-suite/commit/c747f2a42759f6804364b7bfbe32010124172b76
