### ISSUE TITLE
Bold text during onbording on Dev

### ISSUE THREAD

**Issue by evgenysl** [trezor/trezor-suite#12711]
**Describe the bug**
Bold text during onbording on Dev

**Info:**
 - Suite version: web 24.6.0 (011dedde8b9ac74ca49379580db03b9d52fd4c73)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.7.1 regular (revision 510121bad342d1f900ca123e131448d577a25e39)
 - Transport: WebUsbTransport

**Screenshots:**
![Screenshot 2024-06-03 at 17 05 09](https://github.com/trezor/trezor-suite/assets/63164324/2b6b0970-59f8-4731-a935-c6f95960f116)

![Screenshot 2024-06-03 at 17 05 48](https://github.com/trezor/trezor-suite/assets/63164324/2bd79e6c-0731-40d7-b614-c75208126f22)

![Screenshot 2024-06-03 at 17 05 58](https://github.com/trezor/trezor-suite/assets/63164324/957a9d4b-fac3-4751-a954-982356f5938e)

![Screenshot 2024-06-03 at 17 13 55](https://github.com/trezor/trezor-suite/assets/63164324/dae0ff62-d099-4875-ac36-a64147feaa36)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.6.0 (e9a042518338e1b23fbf1542d4f08ea64dd930cd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.1 bitcoin-only (revision 9baa9e03a12bbf363af3439a46694083cd077937)
 - Transport: BridgeTransport 2.0.33
