### ISSUE TITLE
documentation: connect-webextension: proxy

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#12717]
document proxy in connect-webextension package 

https://www.npmjs.com/package/@trezor/connect-webextension

based on discussion with ppl implementing connect into a 3rd party we realized that proxy feature in connect-webextension is not very well documented.

**Comment by martykan** [comment]
Since we decided proxy won't be officially supported or even published, I guess we can close this?

**Comment by Hannsek** [comment]
No, we've decided that we would document it, at least somehow, and have it somewhere, but we won't promote it.

**Comment by Hannsek** [comment]
I mean, if it is a thing for a couple of minutes then let's do it. If not let's skip it.

**Comment by martykan** [comment]
Well with #12785 it won't even be available anymore

**Comment by Hannsek** [comment]
Aha, ok, thanks.
