### ISSUE TITLE
Add new and remove old images to Suite for T3T1

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#12725]
[16kb.zip](https://github.com/user-attachments/files/15552176/16kb.zip)
 
![Screenshot 2024-06-04 at 15 33 03](https://github.com/trezor/trezor-suite/assets/57008159/1374f567-ed7e-47e5-a3e9-6cd762cd32db)

**Comment by Hannsek** [comment]
tracked in different repo…

**Comment by MiroslavProchazka** [comment]
Tracked in [here](https://github.com/trezor/trezor-suite-private/issues/93)
