### ISSUE TITLE
Passphrase: When Standard wallet not remembered

### ISSUE THREAD

**Issue by shenkys** [trezor/trezor-suite#12722]
When only passphrase wallet is remembered and device is connected, we keep the user in the initially visible passphrase wallet, instead of switching him to standard (which might be empty). 

As a workaround to allow users to  actually open it, we will display the "Standard wallet" when connected. It would show no balance in the switcher at first and discovery would happen only after the user would open it with it. 

After that, it'd be normally loaded, balance would appear in wallet switcher and user could effortlessly switch back & forth. 

[Design here](https://www.figma.com/design/mmDnYtctfjnreWhTjLfeQH/Passphrase?node-id=2978-47942&t=zSlSsyD2w6IXuXa3-11)

**Comment by STew790** [comment]
**QA OK**
Works as expected
**Info**
24.10.2     e436527

**Comment by vytick** [comment]
Reverting. 

Add placeholder for standard wallet to wallet switcher and create+discover accounts after user clicks it.

**Comment by vytick** [comment]
@STew790 This was redone after revert. Please, test it once more 🙏

**Comment by STew790** [comment]
**QA OK**
Works as expected, button is present, upon opening a discovery for standard wallet starts :tada: 

**Info**
24.11.1 https://github.com/trezor/trezor-suite/commit/c214aa306ebf33a0255973753fb55b487dcdc6db
