### ISSUE TITLE
Legacy account number confusing

### ISSUE THREAD

**Issue by martinboehm** [trezor/trezor-suite#1275]
When I have two legacy accounts, one P2SH and one P2PKH, both get assigned as account number 1, see the screenshot.
![image](https://user-images.githubusercontent.com/11609674/75781832-35414380-5d5e-11ea-8ba1-6772fb9880da.png)
Maybe it would help to show that they are both of different type (a tiny P2SH/P2PKH or Segwit/Legacy (like in the transaction list) next to the coin name?). Or assign them as number 1 and 2.

**Comment by glacierbits** [comment]
@szymonlesisz Design for Legacy, Segwit legacy, and Imported accounts: **[Zeplin](https://zpl.io/aB8Aqgk)**

**Comment by szymonlesisz** [comment]
implemented https://github.com/trezor/trezor-suite/pull/1467
