### ISSUE TITLE
Fiat rates not showing for transactions on remembered wallet

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#12762]
**Describe the bug**
FIAT rate is not showing for past transactions on the "Overview" tab of the accounts for remembered wallet after Suite update.

**Steps to reproduce:**
1. Install older version then 24.6.1
2. Connect Trezor
3. Wait for discovery and click on remember wallet
4. Close Suite
5. Install version 24.6.1
6. Click on any account
7. Scroll to transaction history

**Info:**
 - Suite version: desktop 24.6.1 (ee1bf19e747daba31bec272b64d09bfa8c6a807e)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.7.1 regular (revision 8c63c1ce7be90a6ff33b79ec7afa742e04f6e7b8)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
Fiat rate is shown for transactions

**Actual result:**
Fiat rate is not shown for transactions

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/48477147/c64a2588-65fc-461c-97e6-86e84022f0c1)
![image](https://github.com/trezor/trezor-suite/assets/48477147/e25a236f-ce55-418b-9ad8-099707de266b)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.6.1 (686e06027e8698cc8f17f928a6ae947d76280489)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
