### ISSUE TITLE
Disable unsupported coins

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12777]
**Describe the bug**
Disable unsupported coins

**Steps to reproduce:**
1. Enable all coins
2. Start discovery
3. Observe errors

**Info:**
 - Suite version: desktop 24.6.1 (ee1bf19e747daba31bec272b64d09bfa8c6a807e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.1 regular (revision 83d1ce2b8e6e4eefe09539f06b28709c8a7a89dc)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/31506317/91d6c7c5-bb99-43b5-8767-82bbe027f10f)

**Comment by STew790** [comment]
**QA OK**
Only supported coins are shown in settings and after enabling all, the discovery finishes correctly.

![image](https://github.com/trezor/trezor-suite/assets/48477147/623abb27-a6d2-4d1e-978f-9bc17557b076)

**Info:**
 - Suite version: desktop 24.6.1 (686e06027e8698cc8f17f928a6ae947d76280489)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
