### ISSUE TITLE
Change copy in onboarding 

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12779]
TR_ONBOARDING_COINS_STEP_DESCRIPTION

Select which coins to show in Trezor Suite. You can change this setting anytime. Some coins are ERC20 tokens and can be used by enabling Ethereum below.
- we need to address ADA/SOL and other tokens as well 

![image](https://github.com/trezor/trezor-suite/assets/152851523/f3436b44-3466-49e7-8cbe-7cce8eb85870)

**Comment by MiroslavProchazka** [comment]
Resolved in crowdin, final copy is "Select which coins to show in Trezor Suite. You can change this setting anytime."

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/96232537-4a53-4f2c-96f6-b3d61b99abf0)

**Info:**
 - Suite version: desktop 24.7.1 (6477c7424ba244d53200f37ad9698e54fed8d169)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32
