### ISSUE TITLE
XPUB match check does not match device and modal and its identified as receive address in modal

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12775]
**Describe the bug**
XPUB match check does not match device and modal and its identified as receive address in modal

**Steps to reproduce:**
1. Navigate to Account/Detail/Public key (XPUB)
2. Display xpub
3. Compare modal and device

**Info:**
 - Suite version: desktop 24.6.1 (ee1bf19e747daba31bec272b64d09bfa8c6a807e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.1 bitcoin-only (revision 83d1ce2b8e6e4eefe09539f06b28709c8a7a89dc)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

**Comment by bosomt** [comment]
works as expcted with TS3
 - Device: Trezor T2B1 2.7.1 bitcoin-only (revision 83d1ce2b8e6e4eefe09539f06b28709c8a7a89dc)

**Comment by komret** [comment]
@bosomt The layout mismatch must be resolved in Suite, can you move the issue there please?

**Comment by bosomt** [comment]
**QA NOK**

current state, you confirm xpub on device and in suite but last "success" screen says `Receive address`
not sure if this is issue in Suite or in fw @komret 

<img width="494" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/e18ea71e-e729-4726-ab3c-57a43aab5352">


**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Comment by Hannsek** [comment]
This is on FW. Please create a new issue in FW repo. 🙏🏻

**Comment by bosomt** [comment]
**QA OK**

follow up issue for fw created

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: BridgeTransport 2.0.33
