### ISSUE TITLE
Manage device #1 design delivery 

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#12789]
- User can enable / disable PIN
- User can change the PIN
- User can update FW
- user can check the device authenticity

[Figma here](https://www.figma.com/design/yY9Zl2jXLKXVV3CwuBmaMU/Manage-device?node-id=0-1&t=LqWgtZcsihX33s9Z-11)

**Comment by shenkys** [comment]
[Figma here](https://www.figma.com/design/yY9Zl2jXLKXVV3CwuBmaMU/Manage-device?node-id=0-1&t=LqWgtZcsihX33s9Z-11)
