### ISSUE TITLE
Improve FW changelog in Suite

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12783]
Please adjust Suite parser so that the format of FW in Suite is  simplified and btc-only and universal changelog is separated. 

We'd also want to have a possibility of formatting the changelog. Headers, body, bold font, ...

**Comment by MiroslavProchazka** [comment]
I can imagine formatting similar to this - 
header, emoji, bold, italic etc. 



![Image](https://github.com/user-attachments/assets/e055278a-9142-4ef1-82d1-39e46a6325e2)

**Comment by Hannsek** [comment]
yeah, that would be it, just classic formatting.

@MiroslavProchazka @Hermez-cz It would be great if you can think about how to distinguish between universal and bitcoin-only fw changelog. 🙏🏻

**Comment by bosomt** [comment]
**QA OK**


formatting updated to match expected style

**Info:**
 - Suite version: web 24.8.0 (a707883081ddf9f3b75ececcb0e8a38732136988)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
