### ISSUE TITLE
Suite allows you to start multishare backup conversion before you received single share backup

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12794]
**Describe the bug**
Suite allows you to start multishare backup conversion even its not possible because you never created backup that you need to enter during conversion.

**Steps to reproduce:**
1. Onboard device with 20w seed
2. Skip backup
3. Start multi share backup

**Info:**
 - Suite version: desktop 24.6.1 (ee1bf19e747daba31bec272b64d09bfa8c6a807e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision e90cf366243f5686c1452c926dceb8ebfc2279fc)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/31506317/9f42e32e-9d97-461e-a757-1c2cbdced383)

![image](https://github.com/trezor/trezor-suite/assets/31506317/26b0ddee-facd-4fe3-a357-e833b3719bb0)

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/2313b2e0-b722-4a66-b056-3bd6ff585557)

**Info:**
 - Suite version: desktop 24.6.1 (686e06027e8698cc8f17f928a6ae947d76280489)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
