### ISSUE TITLE
Tap to enlarge the diagrams in Connect explorer + filters

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#12791]
![image](https://github.com/trezor/trezor-suite/assets/57008159/26493453-373a-4871-8aba-72a9a03bc57f)

Also, apply filters so the diagrams are ok when in darkmode.

**Comment by martykan** [comment]
Something like this library? 
https://rpearce.github.io/react-medium-image-zoom/?path=/story/img--regular

**Comment by Hannsek** [comment]
yes, might be.

**Comment by bosomt** [comment]
**QA OK**

checked at https://connect.trezor.io/9/ docs
