### ISSUE TITLE
Device asks for number of words after you cancel dry run in Suite

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12797]
**Describe the bug**

After you cancel dry run in Suite you need to reconnect device or restart app
Device: asks for number of words after you cancel dry run in Suite.
Suite: Device detected in incorrect state

**Steps to reproduce:**
1. Start dry run
2. Cancel dry run in Suite
3. Observe Suite and device state

**Info:**
 - Suite version: desktop 24.6.1 (ee1bf19e747daba31bec272b64d09bfa8c6a807e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision e90cf366243f5686c1452c926dceb8ebfc2279fc)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="750" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/e869c5b0-9319-4f7b-b631-15f08f61389d">
<img width="289" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/3db53d8a-ccb8-4f71-8ebe-3f5b5eb0585f">
<img width="521" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/64772a0d-72f8-4e2f-bedb-729845f1f6fd">
<img width="400" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/733de289-33b6-4440-ac16-d3e107b1698e">

**EDIT**
after reload of suite i see `Unexpected state: Initialize failed: Cancelled , code: Failure_ActionCancelled`

<img width="577" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/98ad9872-18a3-4c3e-bf48-0c5b2f104d4f">

**Comment by peter-sanderson** [comment]
This is FW bug. 

See: https://satoshilabs.slack.com/archives/CL1D61PQF/p1718029051129309

**Comment by komret** [comment]
Needs to be fixed on the firmware side, closing.

**Comment by bosomt** [comment]
https://github.com/trezor/trezor-firmware/issues/4022
