### ISSUE TITLE
Connect Explorer signTransaction window is not scaling properly in browser 

### ISSUE THREAD

**Issue by evgenysl** [trezor/trezor-suite#12801]
For _signTransaction_ method, I need to use 80% browser scaling, otherwise _Method testing tool_ doesn't fit the screen (on separate display also). It's not scrollable also.

Applicable for all coins except Ethereum, Ripple, Tezos.

![Screenshot 2024-06-07 at 16 47 21 (1)](https://github.com/trezor/trezor-suite/assets/63164324/1f2e0e16-9ec3-4bac-8c44-9f478066c1d5)
![Screenshot 2024-06-07 at 16 52 15 (1)](https://github.com/trezor/trezor-suite/assets/63164324/bf12cce2-30a1-420f-ad52-24bec2c1fcda)

@martykan

**Comment by bosomt** [comment]
**QA OK**

https://connect.trezor.io/9/methods/bitcoin/signTransaction/ looks good after recent release
