### ISSUE TITLE
EVM tokens/ Remove add tokens modal and button

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12812]
Please remove add tokens modal and button, leave it active just in the debug mode (for testing purposes)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.7.0 (ab4c670d962b5cba6ee77a7ae7f25c9ebf4f9949)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
