### ISSUE TITLE
Tokens tab redesign #1

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12810]
Implement Tokens

![Screenshot 2024-06-11 at 17 07 28](https://github.com/trezor/trezor-suite/assets/33235762/4458ee69-94ce-426c-9962-52379bdfbcf2)
![Screenshot 2024-06-11 at 17 08 28](https://github.com/trezor/trezor-suite/assets/33235762/630ee390-d839-4519-bea8-2404e8294f28)
![Screenshot 2024-06-11 at 17 11 25](https://github.com/trezor/trezor-suite/assets/33235762/b4405cea-d997-4764-a650-a936f637ad42)

**Comment by tomasklim** [comment]
TODO make first and second part

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.7.0 (fc7a45b19d84332855dfccf7dd353991786680fc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
