### ISSUE TITLE
EVM tokens/ Blur url in a token name

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12811]
Please blur url in a token name so we mitigate another attack field for possible scams

![Screenshot 2024-06-11 at 16 57 15](https://github.com/trezor/trezor-suite/assets/33235762/15bef785-0c13-484a-a8d6-b8b67cac54fd)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.7.0 (fc7a45b19d84332855dfccf7dd353991786680fc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
