### ISSUE TITLE
EVM tokens/ Enhanced searching

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12826]
search according to token *name*, *symbol* and *token (contract) address* should be possible in chosen category (hidden, collectibles, coins)

![Screenshot 2024-06-11 at 17 02 55](https://github.com/trezor/trezor-suite/assets/33235762/bfdfb1e6-7cc0-4c5d-a90f-8e69320ccb19)

**Comment by tomasklim** [comment]
TODO: is it search in tokens tab or in transaction history?

**Comment by tomasklim** [comment]
@Hannsek Should it search accross all categories or just within the current one?

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.7.0 (5c77ed494ad14df538af06ba46c5ef86b269f7f3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
