### ISSUE TITLE
EVM tokens/ Zero balance tokens

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12823]
do not show tokens with 0 balance, but still show its transaction history

**Comment by tomasklim** [comment]
Show it only under debug mode to make add token work

**Comment by bosomt** [comment]
**QA OK**

switching between debug mode on/off shows/hides 0 tokens as expected

**Info:**
 - Suite version: web 24.7.0 (fc7a45b19d84332855dfccf7dd353991786680fc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
