### ISSUE TITLE
EVM tokens/ Send form adjustment for tokens

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12820]
after clicking the 'Send' button next to the token, the user should be taken to the send form, where the token would be prefilled

![Screenshot 2024-06-11 at 16 59 52](https://github.com/trezor/trezor-suite/assets/33235762/c68fcf94-9683-4070-a51e-6ec2a2347983)

![Screenshot 2024-06-11 at 17 00 06](https://github.com/trezor/trezor-suite/assets/33235762/477e8c8f-01f1-46b6-a2d9-62e29056e6fb)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.7.0 (87a1ef738cd9557e8d447be74b6eb438d1691c8d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
