### ISSUE TITLE
Confirm on Trezor hidden behind backdrop in onboarding

### ISSUE THREAD

**Issue by martykan** [trezor/trezor-suite#12829]
The "Confirm on Trezor" box seems to be hidden behind the backdrop during onboarding

<img width="1069" alt="Screenshot 2024-06-11 at 11 46 18" src="https://github.com/trezor/trezor-suite/assets/8833813/f0c9cc84-f573-4c71-ab86-62bb3434e903">

**Comment by MiroslavProchazka** [comment]
Should be fixed in 24.6.1

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/trezor/trezor-suite/assets/31506317/75284113-4cd0-4b6c-9e6d-d3aab437fdd3)

**Info:**
 - Suite version: web 24.7.0 (ab4c670d962b5cba6ee77a7ae7f25c9ebf4f9949)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
