### ISSUE TITLE
Staking in dashboard portfolio balance

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#12828]
Include the Ethereum staking balance in the portfolio summary.

![Image](https://github.com/trezor/trezor-suite/assets/216917/ca8171d2-5bd3-4d99-9504-a001a5228542)

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/trezor/trezor-suite/assets/31506317/7ae906dc-904f-40a5-a837-aaa68c09e4c4)

**Info:**
 - Suite version: web 24.7.0 (5c77ed494ad14df538af06ba46c5ef86b269f7f3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
