### ISSUE TITLE
EVM tokens/ Icons

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12822]
**Description:**

Add token icon to tokens list to the left of token name. Including all EVMs, Solana and Cardano
- do not show ring, just icon of token
- 3 letters are better than 1 in case of tokens without icon
<img width="465" alt="Screenshot 2024-08-02 at 21 06 07" src="https://github.com/user-attachments/assets/f7c9acbe-da6e-443c-b8e7-35af38ec9964">

Tokens available in token definitions should have an icon, no need to fetch icons for the ones without token definitions. They are not going to be available.

**Prerequisite issue:**

#13630

**Comment by ffrediani** [comment]
+1 to this feature. Having icons next to well known EVM tokens is very useful thing to illustrate better when dealing with them on each chain.

Not only to EVM tokens but also to Solana or Cardano tokens as well if possible.

**Comment by MiroslavProchazka** [comment]
Sizes: 24px, 48px (2x)
URL [https://data.trezor.io/cryptoIcons/{coin}.webp](https://data.trezor.io/cryptoIcons/%7Bcoin%7D.webp)
file name: [coinId].webp or [network]_[contract].webp
bitcoin.webp, bitcoin@2x.webp
ethereum.webp, ethereum@2x.webp
ethereum_0xdAC17F958D2ee523a2206206994597C13D831ec7.webp, ethereum_0xdAC17F958D2ee523a2206206994597C13D831ec7@2x.webp

**Comment by jvaclavik** [comment]
This component should be probably very similar to `packages/suite/src/views/dashboard/components/AssetsView/components/AssetCoinLogo.tsx`

**Comment by hstastna** [comment]
@MiroslavProchazka @Hermez-cz @FreeWall @jvaclavik @yanascz there was a lot of discussion about this task. Could I kindly ask you for providing the update of this issue here with the clear expected result, expected properties, sizes of the icons etc, so we make sure the result fits all of our needs? Thank you very much in advance! 🙏🏽

**Comment by ffrediani** [comment]
Yeah, would be nice to know when this will be ready for stable version and we can the icons in the Trezor Suite.

**Comment by tomasklim** [comment]
This issue is related to icons in token list. Please use https://github.com/trezor/trezor-suite/issues/13630 for icon itself. Not relevant comments were removed

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.10.0 (265028df5e34d075abd34f2ee338e6392d3613c1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
