### ISSUE TITLE
EVM tokens/ Token transaction history 

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12825]
after clicking on transaction button, user should be taken on the transaction history screen, where transaction related only to that token would be filtered

**Comment by tomasklim** [comment]
Probably add button here 
![Screenshot 2024-06-11 at 17 01 48](https://github.com/trezor/trezor-suite/assets/33235762/364ff98d-ff5b-4c9a-96dd-0191f61b2cb1)

**Comment by tomasklim** [comment]
Related to this #3544

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.9.0 (59c92533990756c8ab1d4f54537f94b9148c7b25)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.2 regular (revision null)
 - Transport: BridgeTransport 2.0.32
