### ISSUE TITLE
Resolve Cardano token definitions

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12840]
- [x] Unify token definitions to include only fingerprint or policy id
- [x] Enable `token-definitions` for cardano
- [x] Fix name and symbol
- [x] Add policy id, finger print to dropdown
- [x] Do migration

**Comment by tomasklim** [comment]
@trezor/qa 
What to test? 
- migration - remember cardano wallet with tokens on old suite 
  - check tokens, try to send tokens (this is really important!), try to send cardano, check old and new txs with older version of suite
  - tokens will have different name and can have different symbol after migration in comparison with clean Suite!
- non remember wallet
  - check tokens, try to send tokens, try to send cardano, check old and new txs with older version of suite
- try explorer links (account, tx, token)
- compare fingerprint, policy id with token data on explorer

**Comment by bosomt** [comment]
**Work in progress**

# fresh

- `Token section` token/contract link to explorer OK
- `Token section` send button OK
- `Token section` receive button OK
- `Token section` hide button ok
- `Token section` unhide button ok
- `Send section` dropdown in amount section divided by hidden section
- `Send section` send max token OK
- ADA transaction link explorer OK
- Staking transaction link explorer OK
- Token transaction link explorer OK
- Policy matches explorer
- Fingerprint matches explorer

# remembered/migration

- Saved wallet in 24.6.2 
- Tokens present in 24.7.1
- i was able to send tokens [link](https://cexplorer.io/tx/282dbe4186f63136f2a5ee083443d05fb2b756a9dd2dc4b20e199a9c0253198d)
- device screen does not match suite modal, i will send issue
-

**Comment by bosomt** [comment]
**QA OK**

overall very good, sent some minor issues

**Info:**
 - Suite version: desktop 24.7.1 (d97e8c2769f8b2751a8db3c4109c10619cf8b926)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 bitcoin-only (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
 -
