### ISSUE TITLE
Onboarding copy tweak 1 / TS5 (20w default) ✅ 

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12848]
![image](https://github.com/trezor/trezor-suite/assets/152851523/c2838b64-385c-414e-8a39-6de59348ec91)

Heading: OK
Sub-heading: OK
Kategorie 1 (20-word backup types)
Můžeme smazat, bude uvedeno v popisu obou variant, že mají 20w
Ale low prio, teď nechme

**Varianta 1 (Single)**
Title: OK
Tag: OK
Popis: `Generates a single share of 20 words that recovers your wallet. This backup type is upgradable to Multi-share Backup whenever you're ready.`
_Hodně úprav_

**Varianta 2 (Multi)**
Title: OK
Tag: OK
Popis: `Generates multiple 20-word lists (shares) to recover your wallet. A minimum number of shares, set by you, are needed to regain access to your wallet.`
_(zkráceno, drobné úpravy)_

Kategorie 2: OK
Modrý box
Heading: OK
Sub-heading: `Generates a single set of 12 or 24 words that can be used to recover your wallet. Legacy backups can't be easily upgraded to a Multi-share Backup. Read more`
_Přidán člen a před Multi-share_
Kategorie 3: OK
Kategorie 4: OK

**Comment by MiroslavProchazka** [comment]
Done

**Comment by STew790** [comment]
**QA OK**

![image](https://github.com/trezor/trezor-suite/assets/48477147/a787137b-a553-4f21-a86b-ec9147ebc359)

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
