### ISSUE TITLE
EVM Tokens / Rename amount to balance

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12841]
Rename amount to balance so that it is unified with dashboard (use same translation strings)
<img width="503" alt="Screenshot 2024-06-11 at 18 39 24" src="https://github.com/trezor/trezor-suite/assets/33235762/a59f5169-e624-490b-8a1d-bbde7fde703d">

**Comment by bosomt** [comment]
**QA OK**

header says Balance 

**Info:**
 - Suite version: web 24.7.0 (fc7a45b19d84332855dfccf7dd353991786680fc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
