### ISSUE TITLE
EVM Tokens / Hidden two categories

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12846]
<img width="1197" alt="Screenshot 2024-06-11 at 18 44 17" src="https://github.com/trezor/trezor-suite/assets/33235762/3e96e201-a7bc-4918-b78d-f6dd1adaf7e9">

**Comment by Hannsek** [comment]
As discussed, leave it like this for now. We can change it later if needed.

**Comment by bosomt** [comment]
**QA OK**

i see two categories after i hide random token manually

**Info:**
 - Suite version: web 24.7.0 (87a1ef738cd9557e8d447be74b6eb438d1691c8d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
