### ISSUE TITLE
Onboarding copy tweak 2 / TS5 (20w default) tooltip (IP)

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12849]
![image](https://github.com/trezor/trezor-suite/assets/152851523/8e04ebcc-c61b-4b4c-ac92-4345bf9f43ec)

Tooltip: `Recommended option for a simple, flexible setup.`
Oproti ostatnímu low prio (ač ten “unsure” text je divný)

**Comment by MiroslavProchazka** [comment]
In progress

**Comment by STew790** [comment]
**QA OK**

![image](https://github.com/trezor/trezor-suite/assets/48477147/c6f1c2fa-038a-41c5-94fc-734d11c495b8)

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
