### ISSUE TITLE
EVM Tokens / Fix copy icon alignment + copy warning

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12842]
![Screenshot 2024-06-11 at 17 48 59](https://github.com/trezor/trezor-suite/assets/33235762/2c00fb54-0782-4d98-aafe-d1c2c2cecb0e)
<img width="342" alt="Screenshot 2024-06-11 at 18 40 03" src="https://github.com/trezor/trezor-suite/assets/33235762/1a418f2c-06b1-4885-bbad-7276b0ddfb40">

On click do not copy directly but show warning with `This is not receive address` `Copy` red button and close button

**Comment by AdamSchinzel** [comment]
Copy icon alignment should be fixed in https://github.com/trezor/trezor-suite/pull/12501

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.7.0 (87a1ef738cd9557e8d447be74b6eb438d1691c8d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
