### ISSUE TITLE
Onboarding - Device security check - Smaller device image

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#12856]
Please change the design of the Onboarding Device security check so the device image is smaller. It is too large, causes unnecessary scrolling and the device is off, so it's just a large black shape.

Design: https://www.figma.com/design/BUMem1C7j4roQDyJf9yxQT/Exploring-Onboarding?node-id=2902-2029&t=iQX5I5fCpR6fYepe-1

Comparison:
![Image](https://github.com/trezor/trezor-suite/assets/88533514/8a2e9939-4c8d-47a0-bdfb-2cf06d1eb2f2)

**Comment by komret** [comment]
I don't have access to the Figma file. However, the original requirement was for this image to be large so that the model is clearly recognizable. Otherwise, scammers could make a fake TT looking as TS5, skipping the authenticity check.

**Comment by hstastna** [comment]
> I don't have access to the Figma file. However, the original requirement was for this image to be large so that the model is clearly recognizable. Otherwise, scammers could make a fake TT looking as TS5, skipping the authenticity check.

@Hermez-cz WDYT? Thanks! :)

**Comment by Hannsek** [comment]
I agree it should be bigger. But also the scrolling is not nice.

Time for the new welcome screen? Wink wink 😅

**Comment by Hermez-cz** [comment]
Hi, thank you for the healthy discussion. The image isn't small beyond recognition in the smaller design (@komret access to Figma granted) and there's still the name of the device you just bought and connected that should help as well. Plus we didn't encounter any devices mimicking other models yet.

So my suggestion is:

1. Getting rid of the scroll barrier hiding the CTAs by implementing the smaller design as Ondra did design it.
2. Prioritizing a welcome screen redesign that will utilize the plain left hand part of it (won't make it for this release though, it will have dependencies)

**Comment by Hermez-cz** [comment]
Will be solved by #13521
