### ISSUE TITLE
Change logic for T3T1 homescreens

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#12852]
We have different default homescreens for different fws:

For T3T1 universal - green circles
For T3T1 btc-only - orange circles

Adjust the logic in Suite accordingly.

**Comment by STew790** [comment]
**QA OK**
T3T1 universal 2.8.0 fw green circles, BTC only orange circles.

**Info:**
 - Suite version: desktop 24.7.1 (6477c7424ba244d53200f37ad9698e54fed8d169)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32
