### ISSUE TITLE
Onboarding copy tweak 4/ TS3 (12w default)

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12851]
![image](https://github.com/trezor/trezor-suite/assets/152851523/56e50bbd-276e-4479-a555-2e0d1fbdc95a)

Heading: OK
Sub-heading: `We've selected the default backup type for your wallet based on your device.`
_Mikro-úprava (set/selected), low prio_

Kategorie 1 (`20-word`…)
_Odstranit, ale nemusí být teď hned_

**Varianta 1 (Single)**
Title: OK
Tag: OK
Popis: `Generates a single share of 20 words that recovers your wallet. This backup type is upgradable to Multi-share Backup whenever you're ready.`
_(stejný jako v případě TS5)_

**Vatianta 2 (Multi)**
Title: OK
Tag: OK
Popis: `Generates multiple 20-word lists (shares) to recover your wallet. A minimum number of shares, set by you, are needed to regain access to your wallet.`
_(stejný jako v případě TS5)_

**Kategorie 2: OK**
Modrý box
Title: OK
Body: `Generates a single set of 12 or 24 words that can be used to recover your wallet. Legacy backups can't be easily upgraded to a Multi-share Backup. Read more`
_(stejný jako v případě TS5)_

**Varianta 3 (12w)**
Title: OK
Tag: OK
Popis: `Generates a single set of 12 words that fits on your device's wallet backup card (recovery seed card), making it easy to write down accurately.`
_(odebráno “or”)_

Varianta 4 (24w): OK

**Comment by STew790** [comment]
**QA OK**

![image](https://github.com/trezor/trezor-suite/assets/48477147/849ec175-a796-4dca-82d3-8c787a7ff964)

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.7.2 bitcoin-only (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
