### ISSUE TITLE
The Linux version of Trezor Suite is offering up a less recent version of firmware than the web version

### ISSUE THREAD

**Issue by Engelberg** [trezor/trezor-suite#12859]
Updated Linux version of Trezor Suite, but it still wouldn't offer to install the latest firmware.

**Comment by matejcik** [comment]
@Hannsek can you move to trezor-suite repo?
(also this might not be the case anymore)

**Comment by MiroslavProchazka** [comment]
@Engelberg Can you please try on Suite 24.6.1 (latest), it should offer you FW 2.7.2. (for TT, TS3, TS5)

**Comment by STew790** [comment]
**QA OK**
Version 24.6.1 is offering me latest update for all 3 devices.

Please, try the update on this version.

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: BridgeTransport 2.0.33
