### ISSUE TITLE
 Onboarding copy tweak 3 /  ✅ 

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12850]
![image](https://github.com/trezor/trezor-suite/assets/152851523/e8e0dd42-ec7b-44b4-9494-0dcd8ed32fc0)

Zvolená varianta: OK
Modrý box: `This cannot be directly upgraded to Multi-share Backup. To allow for seamless upgrades, use the default Single-share Backup.`

**Comment by MiroslavProchazka** [comment]
Done

**Comment by STew790** [comment]
**QA OK**

![image](https://github.com/trezor/trezor-suite/assets/48477147/695dda12-2eaa-45f4-bc7e-0908e4e2e450)

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
