### ISSUE TITLE
EVM Tokens / Blur tooltip and Drowndown misaligned

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12860]
![Screenshot 2024-06-12 at 12 40 14](https://github.com/trezor/trezor-suite/assets/33235762/e90dc069-ebc7-4233-a58f-6b04490a3586)
Tooltip "arrow" is not above my cursor.
Dropdown is outside of screen, I cannot scroll to the bottom

**Comment by AdamSchinzel** [comment]
Tooltip arrow was broken even before my first token PR cc @jvaclavik

**Comment by AdamSchinzel** [comment]
After discussion after @jvaclavik I will close this one and create separate issues for both bugs since it's everywhere.
