### ISSUE TITLE
EVM Tokens / Fix coins without token definitions (ETC, TADA, tSOL,...)

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12862]
I am unable to hide tokens for coins without token definitions. You can test it on all seed for cardano testnets. But we need to fix it because of ETC. Maybe you can also test it by adding tokens (check that it works for ETC but it should so you can enable it #12864)

https://github.com/trezor/trezor-suite/assets/33235762/aae39fc8-f673-4a27-a54c-da5284c05249

**Comment by bosomt** [comment]
No tokens are present in Cardano testnet accounts, probably unrelated issue 
Tokens are present in transactions history


![Image](https://github.com/trezor/trezor-suite/assets/31506317/22708593-9311-4a40-b9da-dbc593612c3c)


**Info:**
 - Suite version: web 24.7.0 (87a1ef738cd9557e8d447be74b6eb438d1691c8d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by AdamSchinzel** [comment]
Yes this is because they have 0 balance probably.

**Comment by bosomt** [comment]
Only zero fiat value, this is what i see on production

<img width="1400" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/779b2c7a-2741-41aa-850d-47f4a4aefa3c">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.7.1 (88dbe0410ac5b6245f392ce13e8c30f0f8f549f2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 3.0.0
