### ISSUE TITLE
App sometimes crashes during coinjoin discovery

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12886]
**Describe the bug**
App sometimes crashes during coinjoin discovery when you open transaction detail.
Managed to reproduce it on 24.6.1 and 24.5.4 version

**Steps to reproduce:**
1. Add BTC coinjoin account
2. During discovery navigate to TEST account with tx history and open tx detial
3. Repeat till app crashes, looks like when you hit at bad time app crashes

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/31506317/0fff7bfc-f73c-4ebc-afa7-6807f0990f63)
https://youtu.be/Ez5l_qUDrLw

**Comment by MiroslavProchazka** [comment]
https://satoshilabs.sentry.io/issues/5485460105/?project=5193825&query=is:unresolved+version:24.6.1&referrer=issue-stream&sort=freq&statsPeriod=7d&stream_index=14

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 24.7.0 (17f727ae2eb1e934aff84f8d8e5d1859f8c50efd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.7.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
