### ISSUE TITLE
Do not rename device default name to "My Trezor"

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#12881]
Firmware currently names devices by their model name as default, like "Trezor Safe 3". Please do not rename it to "My Trezor" during initialization.

![Image](https://github.com/trezor/trezor-suite/assets/88533514/36b000af-3de9-4301-9efa-f0426bfaa720)

**Comment by MiroslavProchazka** [comment]
What should be the default name then?

**Comment by Hannsek** [comment]
The default name is set in the device already. So nothing from Suite side.

**Comment by MiroslavProchazka** [comment]
@Hannsek So I should close this one?

**Comment by Hannsek** [comment]
No, Suite is renaming the device during the onboarding to `My Trezor`. It should not do that.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 24.10.0 (7a4ddc9a8137951fe69c7693d4ac9e70511a39b4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
