### ISSUE TITLE
Add tokens with receive - please get back to the previous solution

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12890]
Please return the previous solution for button "Add token with receive" - do not show the moda lfor adding token manually!

https://github.com/trezor/trezor-suite/assets/152851523/496955f5-8ffc-47f0-badc-aaae565b91fd

**Comment by MiroslavProchazka** [comment]
Viz - https://github.com/trezor/trezor-suite/pull/11797

**Comment by STew790** [comment]
**QA OK**
(Without debug mode)
![image](https://github.com/trezor/trezor-suite/assets/48477147/b811a19f-578c-4f5f-a11d-18c006624291)

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
