### ISSUE TITLE
Staking modal says 1 days and not one day in Confirm entry period modal 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12893]
**Describe the bug**
Staking modal says 1 days and not one day in Confirm entry period modal 

**Steps to reproduce:**
1. Start staking and observe modals

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![Image](https://github.com/trezor/trezor-suite/assets/31506317/cdc241f6-88d1-4b23-bbaa-06a9d4d76899)

**Comment by MiroslavProchazka** [comment]
https://crowdin.com/editor/trezor-suite/103/en-en?view=comfortable#35338

**Comment by bosomt** [comment]
**QA OK**

we didnt manage to see 1 day even we checked it every working day in last month
if i see `1 days` i will reopen if needed

**Info:**
 - Suite version: desktop 24.7.2 (3282fe8f6f491e024c0cc9cae99f3085c229c96c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
