### ISSUE TITLE
Onboarding Backup type visual fixes

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#12895]
**Describe the bug**
Please improve visual details in the Onboarding Backup Type select menu:

- Body (small) text in the selected option should be subdued
- Titles should be in black color also in the unselected options
- Blue box and the first option under it are missing padding between them

Design:

![Image](https://github.com/trezor/trezor-suite/assets/88533514/88807144-c4ec-4abe-802d-94d6f34a971c)

**Info:**

-   Suite Version: app 24.6.1

**How to reproduce**

1. Connect a wiped device (not Trezor Model One)
2. Start onboarding
3. Reach the Create new wallet step
4. Open the Backup type select menu
5. Observe designs

**Screenshots**
Implementation:

![Image](https://github.com/trezor/trezor-suite/assets/88533514/f134c57b-eef6-44e1-ac74-b702214a931b)

**Comment by komret** [comment]
> * Blue box and the first option under it are missing padding between them

What do you mean, @Hermez-cz? It looks identical to me in the two images.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.7.0 (0959ca14fb3b440d4f849e9c8bf7d3688afd6b94)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33
