### ISSUE TITLE
EVM Tokens / Hidden tokens by user are missing fiat

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12909]
![Screenshot 2024-06-16 at 19 32 40](https://github.com/trezor/trezor-suite/assets/33235762/17475d23-51d1-4936-98c3-75a56d03e725)
![Screenshot 2024-06-16 at 19 33 25](https://github.com/trezor/trezor-suite/assets/33235762/b0d49473-d579-468c-8a20-1f6af0178f71)

**Comment by AdamSchinzel** [comment]
This is on purpose (I already asked @Hermez-cz

**Comment by bosomt** [comment]
**QA OK**


hidden tokens with fiat value are not missing value in hidden section

**Info:**
 - Suite version: web 24.7.0 (fc7a45b19d84332855dfccf7dd353991786680fc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
