### ISSUE TITLE
EVM Tokens / Dropdown - open in explorer hover not work

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12908]
https://github.com/trezor/trezor-suite/assets/33235762/8b3ebca3-f59b-4896-bd40-ad4a60209246

**Comment by bosomt** [comment]
**QA OK**

hover works as expected now

**Info:**
 - Suite version: web 24.7.0 (fc7a45b19d84332855dfccf7dd353991786680fc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
