### ISSUE TITLE
When coin is disabled, app is still subscribed to new blocks

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12904]
**Describe the bug**
When I disable coin after start, I am still getting new block info

**How to reproduce**
1. Activate whatever coin (best is polygon (fast blocks))
1. Restart Suite
1. Load accounts
2. Disable coin
3. Check console that `blockchain-block` for disabled coin is still getting updated

**Screenshots**
![Screenshot 2024-06-16 at 18 52 07](https://github.com/trezor/trezor-suite/assets/33235762/e9496faa-0970-4a9b-bb68-a26d72bcb6ac)

**Comment by bosomt** [comment]
**QA OK**

same behavior on remembered and connected wallet
disabled all coins, no blocks/coins updates , only expected messages 

<img width="407" alt="Image" src="https://github.com/user-attachments/assets/6bf4e282-f011-4277-a264-1213285f2a54" />


**Info:**
 - Suite version: desktop 25.1.0 (7daeb57b631e7e306bc3282476941420944bfeda)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3B1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
