### ISSUE TITLE
EVM gas price 9 decimal places

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12903]
**Describe the bug**
Gas price unit is `gwei` and `gwei` has 9 decimal places 
![Screenshot 2024-06-16 at 18 44 57](https://github.com/trezor/trezor-suite/assets/33235762/6587ec72-49c0-4669-b492-15476a42870a)
![Screenshot 2024-06-16 at 18 46 23](https://github.com/trezor/trezor-suite/assets/33235762/73d1b7d6-fb3e-4ffe-ab7f-213fc07f24be)

We are getting 9 decimals from Blockbook but we round it somewhere. Let's use correct gas price. By this, tx can be easier identified that comes from Trezor Suite.
![Screenshot 2024-06-16 at 19 06 06](https://github.com/trezor/trezor-suite/assets/33235762/d376e846-77ab-4cdd-852c-e1c3fac1c5d4)

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/user-attachments/assets/aa79e93b-a43c-4cec-bb34-dd34687239c8)



![Image](https://github.com/user-attachments/assets/db6451b9-c8c0-46b2-a760-0eccc44ca1f2)




**Info:**
 - Suite version: desktop 24.7.2 (3282fe8f6f491e024c0cc9cae99f3085c229c96c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
