### ISSUE TITLE
EVM Tokens / Send form select

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12905]
Send form does not respect Tokens / Hidden / Unregosnised

![Screenshot 2024-06-16 at 19 24 30](https://github.com/trezor/trezor-suite/assets/33235762/27783bfb-c681-4253-ab5c-6fc911e19346)

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/trezor/trezor-suite/assets/31506317/4a1c3560-2008-4079-8e12-eb28e68cd027)

**Info:**
 - Suite version: web 24.7.0 (c468135ca482e43174ccc81da0f71379a820d289)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision 2e10618876be8a09a9d985098429f3016baf348e)
 - Transport: BridgeTransport 2.0.33
