### ISSUE TITLE
EVM Tokens / Big last token line

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12906]
Last line should not have padding bottom 
![Screenshot 2024-06-16 at 19 26 47](https://github.com/trezor/trezor-suite/assets/33235762/95e88666-f625-4441-b797-fee97550894a)
![Screenshot 2024-06-16 at 19 28 25](https://github.com/trezor/trezor-suite/assets/33235762/28f4b9bf-bd5c-4285-b053-6ba2e595b07d)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.7.0 (fc7a45b19d84332855dfccf7dd353991786680fc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
