### ISSUE TITLE
Polygon update time is slow

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12901]
**Describe the bug**
When I send tx in Polygon, it is usually confirmed in ~2 seconds. However, it is pending or missing in Suite for ~1 minute.

I think there is something wrong with fetch limiter for "fast" blockchains.

![Screenshot 2024-06-16 at 18 25 07](https://github.com/trezor/trezor-suite/assets/33235762/86c24d01-5316-49f3-9dbb-bb9ed020d1e0)
![Screenshot 2024-06-16 at 18 24 53](https://github.com/trezor/trezor-suite/assets/33235762/7b298778-6013-4585-8484-6df3d6bf3069)

Idea: It would be at least nice to speed up "slowed" accounts when user is inside an account

**Comment by bosomt** [comment]
**QA OK**

sent Poly tx, changed to confirmed almost immediately 

**Info:**
 - Suite version: web 24.8.0 (8b84b7ecb82ad6d641dc8d3b9bf7fa50cb016fed)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: WebUsbTransport
