### ISSUE TITLE
EVM Tokens / Weird line in button group

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12907]
When disabled, there is some separator line
![Screenshot 2024-06-16 at 19 28 53](https://github.com/trezor/trezor-suite/assets/33235762/fb39a30b-feea-492c-9a6a-2655ede8158d)

**Comment by AdamSchinzel** [comment]
@jvaclavik probably should be removed if at least one item is disabled wdyt?

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/trezor/trezor-suite/assets/31506317/51030ce6-e7e7-419e-86db-9cb8a051543d)

**Info:**
 - Suite version: web 24.7.0 (c468135ca482e43174ccc81da0f71379a820d289)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision 2e10618876be8a09a9d985098429f3016baf348e)
 - Transport: BridgeTransport 2.0.33
