### ISSUE TITLE
Display rotation for device that does not support it.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12915]
**Describe the bug**
Display rotation for device that does not support it.
See screenshot with TS3 connected.
It allows you to change it and it has success notification `Settings changed successfully`

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="862" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/e1563265-3383-4ce0-ac98-7f4c90c6cd59">

<img width="286" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/90a505d2-089d-4399-b3ad-f3b2db527d43">

**Comment by bosomt** [comment]
**QA OK**

TT - rotate available and functional
T1 - rotate unavailable 


**Info:**
 - Suite version: web 24.7.0 (ae11f5fd0914d1980aac8ba181432377306a70f1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by MiroslavProchazka** [comment]
@bosomt what about ts3 and ts5 please?

**Comment by bosomt** [comment]
**QA OK**

retest for TS3 and TS5 OK

**Info:**
 - Suite version: web 24.7.0 (d8da75e7aa4fa4fb3e7d9b10a1ed6b4b668a93df)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 **- Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)**
 **- Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)**
 - Transport: BridgeTransport 2.0.33
