### ISSUE TITLE
EVM Tokens / Show more decimal places of price when price is small

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12910]
The price is obviously not zero
![Screenshot 2024-06-16 at 19 36 21](https://github.com/trezor/trezor-suite/assets/33235762/8fbf5fd1-a58a-4f72-8cfc-e341f03c799f)
![Screenshot 2024-06-16 at 19 36 43](https://github.com/trezor/trezor-suite/assets/33235762/28f918b4-f6b7-4840-a70d-1041ee559c16)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.7.0 (87a1ef738cd9557e8d447be74b6eb438d1691c8d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
