### ISSUE TITLE
Suite shows you incorrect info during wallet recovery on T1

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#12924]
https://github.com/trezor/trezor-suite/assets/152851523/faa9a96f-355d-4404-893a-603120a54067

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/88fa90c9-472a-41de-9051-b13d50d80cf9)

**Info:**
 - Suite version: desktop 24.7.1 (88dbe0410ac5b6245f392ce13e8c30f0f8f549f2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.32
