### ISSUE TITLE
Anchor highlight has thinner top border

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#12936]
**Describe the bug**
Anchor highlight has slightly thinner border on the top.

**How to reproduce**

1. Go to dashboard
1. Click on "Check backup in settings" in security section
1. See highlight

**Expected behavior**
Highlight should have border top.

**Screenshots**
<img width="1029" alt="Screenshot 2024-06-18 at 10 09 59 AM" src="https://github.com/trezor/trezor-suite/assets/66002635/cd148412-71ad-4542-ad88-338e0c263036">

**Comment by komret** [comment]
Closing as duplicate of https://github.com/trezor/trezor-suite/issues/10824.
