### ISSUE TITLE
Add cursor:not-allowed to disable components

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12945]
To all interactive/input components in our design system, we want to add `cursor: not-allowed` when they are disabled.

Components:
```
Input
Button
ButttonGroup (maybe it will work when you change it in Button)
Radio
Checkbox
AutoscalingInput
Range
Select
SelectBar (?)
Switch
Textarea

ButtonGroup
IconButton
PinButton
TextButton
TooltipButton
```

**Comment by hstastna** [comment]
Note:
Solving this issue will include also adding args in storybook for components that are missing them so one could easily change the values of selected component and to see how the component behaves/changes.

**Comment by hstastna** [comment]
The following components are done:
- Input
- Button, ButttonGroup
- Radio
- Checkbox

The rest in followup PRs.

**Comment by hstastna** [comment]
Update: The following components are done:
- Input
- Button, ButttonGroup
- Radio
- Checkbox
- AutoscalingInput
- Range
- Select
- SelectBar
- Switch

The rest in followup PR (hopefully the last one).

**Comment by hstastna** [comment]
_Note:_
`PinButton` component cannot be disabled, hence `cursor:not-allowed` won't be added to it as it does not make sense (probably only its storybook will be updated).

**Comment by bosomt** [comment]
**QA OK**


https://github.com/user-attachments/assets/d4f1fccd-8afb-4022-8634-424655e505e3



**Info:**
 - Suite version: web 24.9.0 (6d647cf2c218b432a970a7ca830f3fa2e8673b60)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.32
