### ISSUE TITLE
Apply ResizableBox to Sidebar

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#12955]
Replace `resize: horizontal` in `packages/suite/src/components/suite/layouts/SuiteLayout/Sidebar/Sidebar.tsx` with `ResizableBox` component.

**Designs:**
- https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A31385&mode=design&t=Q3oUNw5KDo2cnSUG-1
- https://www.figma.com/file/r9wXzA4BLJLw8KJoAioLqO/Playground?type=design&node-id=2005%3A12357&mode=design&t=xr33j5igi5zNBPZa-1

**Nice to have:**
Responsive items in sidebar

<img width="529" alt="image" src="https://github.com/trezor/trezor-suite/assets/858321/1900b1b4-b2c7-47b9-9844-46786227ed2c">

**Comment by hstastna** [comment]
Note:
Responsive items in sidebar not implemented yet. Coming soon..
