### ISSUE TITLE
Misplaced hint in Tokens/Hidden section

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12957]
**Describe the bug**
Misplaced hint in `Tokens/Hidden` section

**Steps to reproduce:**
1. Connect wallet with unrecognized tokens
2. Navigate to `tokens/hidden` section
3. Hover over `Unrecognized tokens`

**Info:**
 - Suite version: web 24.7.0 (fc7a45b19d84332855dfccf7dd353991786680fc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="445" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/d388bd5f-900a-4e3a-8a90-d8f1daf54456">

<img width="545" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/869eb4c0-b505-4884-9322-7fbaede058a3">

**Comment by tomasklim** [comment]
Closing, already reported https://github.com/trezor/trezor-suite/issues/12937
