### ISSUE TITLE
Dashboard cards - paddings + widths

### ISSUE THREAD

**Issue by shenkys** [trezor/trezor-suite#12952]
I'd like us to fix the paddings & widths in dashboard cards before device is connected. 

It goes for all states of all cards when device has not been loaded yet. Namely: 
- Connect & unlock 
- Track my coins
- Unlock my Trezor (acquired state)

Sides + bottom = 24px
Top = 32px 

Stretch the button to full width - all cases as well. 

Initial state: 
![Image](https://github.com/trezor/trezor-suite/assets/156302069/a9ab7821-7bd8-446b-8d7f-a1b1866f88ad)
![Image](https://github.com/trezor/trezor-suite/assets/156302069/194e995d-8e41-4b04-acae-fa2a2ae17a2c)

Updated:
![Image](https://github.com/trezor/trezor-suite/assets/156302069/26300fb7-9e27-48bb-84f3-f1db89aa0e5f)
![Image](https://github.com/trezor/trezor-suite/assets/156302069/7b0f3e44-bda8-46d3-b401-b23a3908b446)

[Figma](https://www.figma.com/design/mmDnYtctfjnreWhTjLfeQH/Passphrase?node-id=3100-8856&t=yroUG4UucwLTO6m7-11)

**Comment by STew790** [comment]
**QA NOK**
I just don't see the "Unlock Trezor" screen anywhere when I connect my T1 and lock it.

**Info**

24.6.0 https://github.com/trezor/trezor-suite/commit/ff75009f1076edbd6476b90c97fa899ca7807b48

**Comment by STew790** [comment]
**QA OK**
My bad, the paddings LGTM and the buttons are stretched.

24.7.2 6975009
