### ISSUE TITLE
Connecting screen not displayed 

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#12976]
Connect screen is not being present when device that has enabled passphrase is connected

Video recording can be seen at this PR
https://github.com/trezor/trezor-suite/pull/12889#pullrequestreview-2128190853

**Comment by STew790** [comment]
**QA OK**
Connecting screen shows correctly.

**Info:**

24.6.0 https://github.com/trezor/trezor-suite/commit/c747f2a42759f6804364b7bfbe32010124172b76
