### ISSUE TITLE
any operation with device responds PIN changed

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1297]
Same results for 2.3.0 and 2.3.0 

Latest version in incognito window
https://suite.corp.sldev.cz/suite-web/develop/

See video.

Wipe - PIN changed
PIN changed - PIN changed
Recovery  - PIN changed

![suit](https://user-images.githubusercontent.com/31506317/76317329-52d15880-62dc-11ea-823b-bf89d6a5dc13.gif)

**Comment by bosomt** [comment]
after onboarding of 1.9.0 it says PIN changed 

![image](https://user-images.githubusercontent.com/31506317/77316695-2b31b580-6d0a-11ea-96cd-dcd047213fbc.png)

**Comment by bosomt** [comment]
same result when you wipe device with 2.3.0 FW

**Comment by mroz22** [comment]
Its just matter of copy I believe. We just need to build new messages.

**Comment by bosomt** [comment]
it's not happening any more
if it happens i will reopen it or contact you @slowbackspace with exact operation to reproduce/fix it
