### ISSUE TITLE
Extra space on devices without address chunkification 

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12988]
**Describe the bug**
On old FWs chunkification is not supported, so we show address without it. 

I am not so smart user so I do not check address with device and I copy it right away from receive address modal. However, there are whitespaces :( that does not happen in case of chunkified address 

![Screenshot 2024-06-19 at 17 14 09](https://github.com/trezor/trezor-suite/assets/33235762/dd4f0220-889d-48ac-a78c-411b14a61038)

**Comment by bosomt** [comment]
**QA OK**

<img width="319" alt="image" src="https://github.com/user-attachments/assets/c180783e-855d-403f-ba28-21ff7a23a785">

**Info:**
 - Suite version: web 24.8.0 (90b029d7f70e030bc2a7cfd2b178df9b45fbd5d1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.4.0 regular (revision ea3596ad8)
 - Transport: BridgeTransport 2.0.32
