### ISSUE TITLE
Fiat in tx history in day header is incorrect

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12992]
**Describe the bug**
I've sent solana so it should be negative, not positive
<img width="1205" alt="Screenshot 2024-06-20 at 17 06 31" src="https://github.com/trezor/trezor-suite/assets/33235762/f7c2ea9e-a339-4edf-b21e-68bced383f81">

**Comment by tomasklim** [comment]
there is just 5 solana txs per page, please check other chains if the days header is calculated across pages or not

- decide if you fix it or if you remove it for solana

**Comment by enjojoy** [comment]
> there is just 5 solana txs per page, please check other chains if the days header is calculated across pages or not
> 
> * decide if you fix it or if you remove it for solana

On other chains it is not calculated across pages, only what is displayed on the page

**Comment by bosomt** [comment]
**QA OK**

<img width="1137" alt="Screenshot 2024-11-21 at 12 56 36" src="https://github.com/user-attachments/assets/255a262b-e1d2-4f8e-998f-fadee933461f">
<img width="1139" alt="Screenshot 2024-11-21 at 12 55 45" src="https://github.com/user-attachments/assets/f7aca33a-6649-4bc5-8313-024ac71cade4">
<img width="1151" alt="Screenshot 2024-11-21 at 12 55 40" src="https://github.com/user-attachments/assets/642493c1-1075-4847-b5e3-d9c028e94852">


**Info:**
 - Suite version: web 24.12.0 (0c7477e1102acb3fd29cd80579fdba7763f736d0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport
