### ISSUE TITLE
Webusb +check for devices button missing in "switch device" modal

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1299]
**[Zeplin](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5e2eb789b530e498136335cd)**

<img width="155" alt="Screen Shot 2020-03-19 at 15 40 13" src="https://user-images.githubusercontent.com/29627086/77079214-f23acd80-69f7-11ea-9344-375c5d64cfd8.png">

**Comment by bosomt** [comment]
button is present and it's working
