### ISSUE TITLE
Message - Do you want the app to accept incoming connections?

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#13]
I see this message from dev server, is it ok?

![image](https://user-images.githubusercontent.com/3112191/57623205-94478900-758f-11e9-8df8-617adcc2da4c.png)

![image](https://user-images.githubusercontent.com/3112191/57623295-c527be00-758f-11e9-927f-e68c9c3dcc24.png)

**Comment by szymonlesisz** [comment]
yarn issue: 
https://github.com/yarnpkg/yarn/issues/4983
https://github.com/yarnpkg/yarn/commit/b827eae221220ea84ab31a010f2f4301a644e6e6

do you have firewall enabled?
