### ISSUE TITLE
Missing Unstake info in Suite modal during bumping transaction 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13004]
**Describe the bug**
- Missing Unstake info in Suite modal during bumping transaction /see first screenshot/
- Missing fee info /second screenshot/
- Account info actually shows fee info /see third screenshot/
- Modal and device not aligned / see fourth screenshot/

**Steps to reproduce:**
1. Unstake your funds
2. Bump unstake transaction
3. Check info in /// section
4. Compare info on device with modal

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
_1_
![telegram-cloud-photo-size-4-6028144144087629956-y](https://github.com/trezor/trezor-suite/assets/31506317/9182df6a-c6fa-4f16-9e92-21f7396c58da)
_2_
<img width="312" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/bbdd2744-07b6-4ca4-9455-b4be889334fc">
_3_
<img width="342" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/8cb64361-3836-4968-99a8-c1917ddec6da">
_4_
![telegram-cloud-photo-size-4-6028144144087629954-y](https://github.com/trezor/trezor-suite/assets/31506317/f4f80acf-07c8-446c-b9cb-d7949e1c8674)

**Comment by tomasklim** [comment]
duplicate https://github.com/trezor/trezor-suite/issues/12662
