### ISSUE TITLE
Coin Enabling - create feature flag  and make enabled whitelist

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13005]
- [x] create feature flag IsCoinEnablingActive and set it default to false
- [x] rework disabledDiscoveryNetworkSymbolsForDevelopment into whitelist
- [x] make it work the same for users without ff enabled
- [x] If the flag is disabled, discovery should run as before for all supported networks (e.g. no polygon and solana).

**Comment by STew790** [comment]
Feature flag shows the enabling of coins at the bottom of the dev menu.
- enabling each coin shows the coin for newly discovered wallets
- already discovered wallets have the same coins as before 

Is this correct behaviour or this is only about the feature flag? @vytick

**Comment by vytick** [comment]
@STew790 It seems so. 

Currently the most important part is, that without enabling this featureflag, discovery should happen exactly the same way for the user, as in previous versions of the app.

**Comment by STew790** [comment]
**QA OK**
Thanks for clarifying! It works OK then.

24.6.0 https://github.com/trezor/trezor-suite/commit/814ab5d0df52939057bfa7643e7c0a83012e86f7
