### ISSUE TITLE
App is unusuable(or very slow) with ETH account with large number of tokens

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#13019]
**Describe the bug**
Import this account into app: `0xdac17f958d2ee523a2206206994597c13d831ec7` and app will be freezing all the time.

**Info:**

-   Mobile Suite Version: version/commit
-   OS: name, version

**How to reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Nodonisko** [comment]
There are still two major issues left:

1. When ETH asset or account is clicked and modal is opened, if there is more than few tokens it will freeze app for few seconds. It's because everything is rendered at once. This component should use FlashList to show tokens so only visible will be rendered. It will require some structural changes to components so it could be used in FlashList.
2. Homescreen Assets component is rerendered very often during discovery/app start. That's probably because loading of fiat rates for tokens and every updated fiat rate will trigger rerender. Solution here is to separate fiat values from main assets selector a create atomic component just for fiat rate that will be use direct selector for example something like `selectAssetFiatValue(state, 'eth')` so it will update minimal amount of components (other solutions possible but this seems easier to me).

Both of these issue should be relative quick to do.

**Comment by STew790** [comment]
**QA OK**
App is usable even with large amount of tokens and values.

**Info**
24.10.1 d87ce74

**Additional notes**
Just additional notes for @Nodonisko 
When there is only the account you shared with me (and no device connected) the app is a little faster then with the device connected.
With the device connected it is like this:
https://github.com/user-attachments/assets/d4804c81-9016-4e23-971e-ae79044e2d3d

And this is with the really big account shared above:

https://github.com/user-attachments/assets/2fdc1139-be05-48fc-adcb-6c6421506c90
