### ISSUE TITLE
Backends sometimes does not reconnect after Tor is disabled 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13014]
**Describe the bug**
Back-ends sometimes does not reconnect after Tor is disabled.
Connect button does work.
Suite does not try to connect automatically, but im not able to reproduce it all the time.

**Steps to reproduce:**
1. Enable Tor
2. Disable Tor
3. Observe servers reconnect
4. Repeat till reproduced

**Info:**
 - Suite version: desktop 24.6.2 (319c5b3ede6f1579b0c4f777b755da5286dd1632)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/31506317/b28d1f86-c471-4de9-b963-0fe248e5bdcd)
![image](https://github.com/trezor/trezor-suite/assets/31506317/81d32c3d-8b60-4194-b495-9b27d1a159cf)
![image](https://github.com/trezor/trezor-suite/assets/31506317/6d15f87e-3e86-44b1-8985-3fa8210b0c1b)

**Comment by marekrjpolak** [comment]
It can be reproduced if Tor is turned on and then off before the backends connect.

The reason is that on proxy change, all the _currently opened_ backends are reconnected, and at that exact time no backend is in fact opened. I'm not sure how and whether to resolve this, but I'm still thinking about that.
