### ISSUE TITLE
Transaction detail: layout for ETH, ERC20 and XRP

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1301]
Those transactions shouldnt have fields like historical value or current value, total input/output.
Design needed

cc @matejzak

**Comment by tomasklim** [comment]
Redesigned as a part of this https://github.com/trezor/trezor-suite/issues/7368

**Comment by STew790** [comment]
Solved in https://github.com/trezor/trezor-suite/issues/7368
