### ISSUE TITLE
Coin Enabling - move enabling settings one level up

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13024]
This task is only functional not Visual

- [x] Move enabling settings into the setting to separate screen
- [x] use wip design same as is in the dev utils
- [x] only show testnets when enabled in DEV utils

**Comment by STew790** [comment]
**QA OK**
- coins enabling in separate settings
- testnet coins only there if enabled in dev tools

**Info:**

24.8.0 https://github.com/trezor/trezor-suite/commit/aceb3c7d3e1213eb9aa9fee3a62eca2c224862fd
