### ISSUE TITLE
EVM Tokens/ (un)hidden tokens are not reflected in transaction history

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13039]
**Describe the bug**
When I unhide scam token, it is still marked as scam in tx history

**Info:**

-   Suite Version: develop

**Expected behavior**

- I would expect that unhidden tokens are not marked anymore
- I am not sure if I would expect that hidden tokens are now marked as "scam". Probably not
- I am not able to mark/unmark tokens with balance 0 because they are hidden, I would probably like to be able to hide/unhide tokens with balance 0 so there should probably be option to show 0 balance tokens using some filter

**Comment by tomasklim** [comment]
@Hannsek

**Comment by Hannsek** [comment]
> I am not able to mark/unmark tokens with balance 0 because they are hidden, I would probably like to be able to hide/unhide tokens with balance 0 so there should probably be option to show 0 balance tokens using some filter

Why would you like to do that?

> I would expect that unhidden tokens are not marked anymore

Most probably yes, I am thinking about putting some warning after unhiding scammy tokens. But maybe not needed.

Seems like low prio.

**Comment by tomasklim** [comment]
if we not do it 100% now, we will never do it 😀

**Comment by AdamSchinzel** [comment]
I think this is quite important. I agree with not marking transactions with tokens that are unhidden as scammy but when I hide some token I would probably mark the transaction with this token as a scammy one. You hid it for some reason and you don't want to see it anymore.

> I am not able to mark/unmark tokens with balance 0 because they are hidden, I would probably like to be able to hide/unhide tokens with balance 0 so there should probably be option to show 0 balance tokens using some filter

True but I think it's not a big problem.

**Comment by bosomt** [comment]
**QA NOK**

https://github.com/trezor/trezor-suite/pull/13380#issuecomment-2238752033

**Comment by bosomt** [comment]
**QA NOK**

now all tokens say `unhide` even they are recognized and not hidden :)

<img width="1126" alt="image" src="https://github.com/user-attachments/assets/c3e2edb3-476b-4dd5-9186-cc418a220f8b">

**Info:**
 - Suite version: web 24.8.0 (4a126f2ac2dcd21f29662c208be402a449e9d672)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
