### ISSUE TITLE
Coin Enabling - enable via Settings final UI

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13034]
Final UI for enabling coin via Settings

- [x] Only show options for selected device (e.g. do not show unsupported accounts)
- [x] If last coin is unselected show alert and enable it again
- [x] raise toast about coin being discovered when connected trezor device
- [x] special UI for BTC only firmware
- [x] ensure everything from #13547 is working

[Figma](https://www.figma.com/design/oQtgXoPIgGSlh01TLHnmeE/Coin-enabling?node-id=377-21063&t=bZoil3v12NSuv9No-0)

<img width="273" alt="Screenshot 2024-07-09 at 22 24 34" src="https://github.com/trezor/trezor-suite/assets/2011829/ee577f96-7ddd-4e57-a20d-564b76da1e52">
<img width="273" alt="Screenshot 2024-07-09 at 22 22 39" src="https://github.com/trezor/trezor-suite/assets/2011829/47fabf60-b9bd-4a11-916d-cb64191a45ec">
<img width="273" alt="Screenshot 2024-07-09 at 22 22 55" src="https://github.com/trezor/trezor-suite/assets/2011829/53ec3379-d01a-405c-8041-cf012f07c8c2">
<img width="273" alt="Screenshot 2024-07-09 at 22 22 49" src="https://github.com/trezor/trezor-suite/assets/2011829/475a8ac3-8737-4059-a653-51b9ec4523f0">

**Comment by vytick** [comment]
blocked by #13547

**Comment by STew790** [comment]
**QA OK**
- Only show options for selected device (e.g. do not show unsupported accounts) - OK
- If last coin is unselected show alert and enable it again - OK
- raise toast about coin being discovered when connected trezor device - OK
- special UI for BTC only firmware - tested here https://github.com/trezor/trezor-suite/issues/13547

**Info:**

24.8.1  f2f56aa
