### ISSUE TITLE
Coin Enabling - analytics

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13035]
1. Coins Active on Startup: Total Number of Coins - Overall
- Which coins are enabled by user when the selection is displayed to them
- Which coins are initially active on Start up (after user did the selection previously)
2. Coins Active on Startup - Overall
3. Average of active coins
4. Median of active coins
5. Change Enabled coins in settings
- When user change the enabled coins in settings

**Comment by sime** [comment]
@vytick Could you dig into what desktop has here? @tomasklim should be able to help.

**Comment by STew790** [comment]
Discussed on slack that no QA needed.
