### ISSUE TITLE
Staking - setting amount close to max adjust gas price

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13040]
**Describe the bug**

- lets say I have 0.102ETH, I want to stake 0.101ETH, it auto adjust custom gas price to an amount I am able to stake
- this leads to a lot of pending staking txs with small gas price
- it should not do this

**Screenshots**

https://github.com/trezor/trezor-suite/assets/33235762/c5e9becd-492a-4fcc-a3c9-1945fb755363

**Comment by bosomt** [comment]
**QA OK**

by trying to stake 0.1xxx ETH and changing amount i was not able to reproduce small gas fee

**Info:**
 - Suite version: web 24.8.0 (3af4c9492403e09ed5ccf1fa57bbf362a80e942e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.32
