### ISSUE TITLE
Persisted sidebar width

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#13055]
It should be saved in `SuiteSettings` (`packages/suite/src/reducers/suite/suiteReducer.ts`) - it's synced with IndexDB

save it on mouse up, not every mouse move event

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.8.0 (fe65e0963b951f8b8bf820916ca877d953964058)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
