### ISSUE TITLE
Analytics for `optiga_sec`

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-suite#13065]
Starting with the next firmware release v2.8.0 Trezor will include a new field `optiga_sec` in `Features`, which contains the value of Optiga's security event counter. This field appears in devices that have the Optiga secure element, i.e. TS3 and TS5. The possible values are integers from 0 to 255 or empty. Let's collect the value of this field from users who have opted in to providing analytics data. The value may change in time. So I propose that we collect the value from the first `Features` message that Suite receives from the device after it's connected.

Related to https://github.com/trezor/trezor-firmware/pull/3977.

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/trezor/trezor-suite/assets/31506317/b3edc7db-890a-4283-9351-14878248216b)

**Info:**
 - Suite version: web 24.8.0 (61c84716ead502aad955db39b0326ff2eb29a294)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
