### ISSUE TITLE
QR code is inverted in dark mode

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-suite#13083]
**Describe the bug**
When the app is in dark mode, the QR code is shown with inverted colors.
This is non-standard and while _some_ QR scanners can deal, not all of them, because they expect dark-on-light scheme.

**Info:**

-   Suite Version: web 24.6.2

**How to reproduce**

1. enable dark mode
2. go to a Receive tab
3. show an address + QR code

**Expected behavior**
Dark-mode QR code should not be inverted. It should be the same as light-mode QR code, surrounded by at least one cell wide white border.

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/596073/a212ab61-1490-42c1-b8e2-6cb868c987d3) ![image](https://github.com/trezor/trezor-suite/assets/596073/351fd818-fc2e-4702-ac70-dbff572e3183)

**Additional context**
reported on the forum: https://forum.trezor.io/t/qr-code-cannot-be-scanned-in-dark-mode-both-trezor-suite-desktop-and-web-based-are-affected/18111/2

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/user-attachments/assets/16f0a666-4b50-46f9-ae08-8da4d6694950)
![Image](https://github.com/user-attachments/assets/358c199c-dc3e-4d14-b331-796b7e9882f6)

**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
