### ISSUE TITLE
reimplement simple trezor password manager 

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#13085]
just basic functionality, it should reuse labeling logic as much as possible (and not break anything!) put it somewhere into debug so that we can play with it.

**Comment by Hannsek** [comment]
I don't think this is a prio now. Why did you come up with this now? 😄

**Comment by STew790** [comment]
**QA OK**
Nice, it's there and the basic functionality works. I can add, edit, decrypt entries. We will monitor labeling more closely throughout our testing phase just so we know it doesn't break anything.

![image](https://github.com/trezor/trezor-suite/assets/48477147/958fd7dd-692f-478b-8ad6-98141ce46be9)

**Info:**
 - Suite version: desktop 24.7.1 (6477c7424ba244d53200f37ad9698e54fed8d169)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32
