### ISSUE TITLE
connect.corp.sldev.cz does not resolve

### ISSUE THREAD

**Issue by peterzen** [trezor/trezor-suite#1308]
trezor-suite fails when trying to load the iframe.  According to the network console, the below request cannot be completed:

https://connect.corp.sldev.cz/develop/iframe.html?1584221761566&version=8.1.0&manifest=IntcImVtYWlsXCI6XCJpbmZvQHRyZXpvci5pb1wiLFwiYXBwVXJsXCI6XCJAdHJlem9yL3N1aXRlXCJ9Ig%3D%3D

Please see below the `dig` output.

Is there a workaround for this problem, or an ETA for when the domain will be accessible?
```
dig connect.corp.sldev.cz @1.1.1.1

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> connect.corp.sldev.cz @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 19637
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;connect.corp.sldev.cz.		IN	A

;; AUTHORITY SECTION:
sldev.cz.		3561	IN	SOA	jeff.ns.cloudflare.com. dns.cloudflare.com. 2033518984 10000 2400 604800 3600

;; Query time: 20 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Sat Mar 14 22:36:40 CET 2020
;; MSG SIZE  rcvd: 112

```

**Comment by mroz22** [comment]
Hi, which version of https://github.com/trezor/trezord-go do you use? Currently released version does not support sldev.cz domain. You should either compile trezord from master branch or disable trezord process on your system and continue with webusb transport (in chrome browser)

**Comment by peterzen** [comment]
Thank you for your reply @mroz22 .

I was running trezord 2.0.27.  I've now compiled 2.0.29 (from latest master), am getting the same problem (iframe not being able to connect to the same hostname).

I've also tried stopping trezord and re-starting `trezor-suite` (I'm running it with `yarn suite:dev` - is this correct?), the iframe problem still persists.  Is there anything I need to run differently in order to enable the Webusb support?

I'm running Chrome Version 80.0.3987.132 (Official Build) (64-bit), restarted the browser after having stopped `trezord`.

Many thanks!

**Comment by mroz22** [comment]
Argh. sorry. My bad. Actually sldev.cz is not publicaly accessible. 

in path  
trezor-suite/packages/suite/src/actions/suite/trezorConnectActions.ts
you should change trezor-connect url to https://connect.trezor.io/8/ (it is commented out), then it should work. sorry for that, we will try to keep in generaly working state for everyone for develop branch in future.

**Comment by mroz22** [comment]
> I've also tried stopping trezord and re-starting trezor-suite (I'm running it with yarn suite:dev - is this correct?), the iframe problem still persists. Is there anything I need to run differently in order to enable the Webusb support?

webusb transport should init automatically in case you:
- run chrome
- trezord is not running 

so what you say you are trying should be enough to make it work. are you sure trezord is not running? you can check it here `http://127.0.0.1:21325/status/`

**Comment by peterzen** [comment]
It did start up correctly with your suggested `trezorConnectActions.ts` change, thank you.

Just one more question - what daemon needs to be running on `localhost` in order for trezor-suite to be able to run without dialing out to `connect.trezor.io`?  (The `https://localhost:8088/` line.)

Thanks again!

**Comment by mroz22** [comment]
You would need trezor-connect instance to be available on localhost. Repo here:  https://github.com/trezor/connect It has `yarn dev` command as well which opens devserver on port 8088 (I think). 

Another option is to run desktop version `yarn workspace @trezor/suite-desktop dev`. It has everything you need bundled inside and should work out of the box.

**Comment by mroz22** [comment]
Seems to be resolved to me, so closing it now. Feel free to reopen.

**Comment by prusnak** [comment]
The Suite is not meant to be used right now. Please wait until the official release.
