### ISSUE TITLE
This passphrase wallet is empty warning when adding cardano account on testing passphrase

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13095]
**Describe the bug**
This passphrase wallet is empty warning when adding cardano account on testing passphrase.
There should be passphrase dialogue and not warning as in previous design before view-only

**Steps to reproduce:**
1. Discover wallet without Cardano enabled
2. Add cardano coin
3. Observe warning

**Info:**
 - Suite version: web 24.7.0 (87a1ef738cd9557e8d447be74b6eb438d1691c8d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="400" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/26c621fe-9d7c-4158-b79e-5e8274833a77">

**Comment by MiroslavProchazka** [comment]
Can you try again on develop? I Wasnt able to reproduce it

**Comment by bosomt** [comment]
Videos how to reproduce.
Show xpub or add cardano after discovery of other coins


https://github.com/trezor/trezor-suite/assets/31506317/8e03fc96-24d7-41a2-a366-e464d2d74966


https://github.com/trezor/trezor-suite/assets/31506317/6967ef77-fcab-40bc-8861-c35ad4b47f52

**Comment by STew790** [comment]
**QA NOK**
This is still happening, unfortunately.
![image](https://github.com/trezor/trezor-suite/assets/48477147/cff3ae5f-e82c-41a8-a8c1-109cdf451f13)

**Info:**
 - Suite version: desktop 24.7.1 (88dbe0410ac5b6245f392ce13e8c30f0f8f549f2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32

**Comment by STew790** [comment]
**QA OK**
Sorry, I just realised I checked it on the RC where it can't be fixed yet, my bad. It is OK on develop :pray: .
![image](https://github.com/trezor/trezor-suite/assets/48477147/0d3f3d6d-8cda-43f2-9750-2ca0d235ecfb)

**Info:**
 - Suite version: desktop 24.7.1 (88dbe0410ac5b6245f392ce13e8c30f0f8f549f2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32
