### ISSUE TITLE
Passphrase: Add fiat balances to wallet swichter

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13099]
- [x] add fiat rates for each wallet
- [x] different visual for single wallet per device

[Figma](https://www.figma.com/design/mmDnYtctfjnreWhTjLfeQH/Passphrase?node-id=2146-52545&t=vhP0Zy4NrG8fYeOU-0)

<img src="https://github.com/trezor/trezor-suite/assets/2011829/394cdd31-e8c4-40e3-be30-b73e22385e38" width=300 />
<img src="https://github.com/trezor/trezor-suite/assets/2011829/d515d353-9f28-47ea-8338-28ecd9953e72" width=300 />

**Comment by STew790** [comment]
**QA OK**
Tested as part of the sanity tests.
