### ISSUE TITLE
Drop-down selector size changes after opening.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13098]
**Describe the bug**
Drop-down selector size changes after opening.
See videos from transaction detail and onboarding 

https://satoshilabs.slack.com/archives/G019WLX2P7B/p1719738173339079

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: web 24.7.0 (c00e0472d7b36073dc95265d90b83900c4f5d299)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision 2e10618876be8a09a9d985098429f3016baf348e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/216f4e40-e08a-4463-984b-cbfe7473c31b

https://github.com/trezor/trezor-suite/assets/31506317/68350718-10ef-4b28-a0b6-ae76d564bed6

**Comment by hstastna** [comment]
This issue is still in progress, fixed only the first of the buggy scenarios (in https://github.com/trezor/trezor-suite/pull/13105).

**Comment by bosomt** [comment]
**QA OK**

checked coinjoin transaction with multiple inputs/outputs and coin selection during onboarding 

**Info:**
 - Suite version: web 24.8.0 (d9959adfccff250c111f6e2b9bfb91305834cb3c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 bitcoin-only (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
