### ISSUE TITLE
connect-explorer - background.scripts

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#13117]
chrome doesn't like this field (although it seems to be a warning only).

<img width="683" alt="image" src="https://github.com/trezor/trezor-suite/assets/30367552/6491773f-63bd-41c4-be09-0075a5592b40">

projects typically maintain 2 manifest.json, one for firefox and one for chrome to be able to deal with their specifiecities.

so far it feels like a low prio to me. cc @martykan

**Comment by martykan** [comment]
Yeah, I'm aware of it, it's exactly because Chrome and Firefox do things differently, but it doesn't seem to affect anything. 
2 manifests also means 2 separate builds...

**Comment by mroz22** [comment]
ok, I am closing it now.
