### ISSUE TITLE
connect - update required for firmwares <1.9.0 and < 2.3.0

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#13113]
as discussed here https://github.com/trezor/trezor-suite/pull/12887#discussion_r1642738757

the time has come to deprecate firmwares implementing 'legacy passphrase flow'. Devices below this version should be presented as `firmware: required` (https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/types/device.ts#L16)

All the code related to handling of legacy passprhase should be removed. 

Related sources:
- https://github.com/trezor/trezor-suite/blob/develop/packages/suite-web/e2e/tests/suite/passphrase-legacy.test.ts#L7
- https://docs.trezor.io/trezor-firmware/common/communication/passphrase-redesign-migration.html
- https://github.com/trezor/trezor-suite/blob/develop/packages/protobuf/src/messages-schema.ts#L1396

**Comment by bosomt** [comment]
**QA OK**

Trezor Suite wont let you in and it starts FW update almost immediately  

https://github.com/user-attachments/assets/142bcf20-b044-4888-84b3-3ad08bb525c0


**Info:**
 - Suite version: web 24.8.0 (290edab512aa23179b76b518f7ef3e5b28cd82a7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
