### ISSUE TITLE
Coin enabling - Design

### ISSUE THREAD

**Issue by shenkys** [trezor/trezor-suite#13123]
As a prerequisite to Solana & Polygon, we need to change up how we handle coin discovery in the mobile app. 

We're shifting from autodiscovery (running it through all coins) to manual enabling. 

This functionality should be available both when device is connected and when it is not. In case user changes it when device is connected, we inform them that it'll be discovered only when they connect their device.

**Touchpoints / JTBD:**

**New users:**
- Post-onboarding

**Users that didn't have view-only.**
- Prompt upon opening the app

**Users that have had view-only.**
- Autoenable what's on their view-only wallets

**All**
- Settings
- My assets 
- Receive

**Edge-cases:**
- When BTC only device is connected, discover only btc
- When BTC only is connected and BTC is not enabled, enable it globally

[Design here](https://www.figma.com/design/oQtgXoPIgGSlh01TLHnmeE/Coin-enabling?node-id=377-21062&t=MTRyDq1ARu28kimA-11)

**Comment by shenkys** [comment]
[Design done here](https://www.figma.com/design/oQtgXoPIgGSlh01TLHnmeE/Coin-enabling?node-id=377-21062&t=MTRyDq1ARu28kimA-11)

**Comment by vytick** [comment]
Closing as done. Made into issues in https://github.com/trezor/trezor-suite/milestone/65
