### ISSUE TITLE
Send coins - error handling

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#13125]
The `suite-native/module-send` should be prepared for comprehensive error handling. The idea is to save an error object to the send form redux state whenever an error occurs in the send form related thunks. Inspiration can be found in recently created passphraseSlice.

## Acceptance criteria
- On fail of any common thunk, an object describing error is returned
- Send form native reducer is able to catch these errors, so the UI can work with them later (UI effects are not part of this issue)

**Comment by PeKne** [comment]
Notes for @trezor/qa: 
This PR does not add any new functionality, it is just a refactor. But also code used in desktop was refactored. Please test that the send form work as expected on the desktop and nothing is broken there.

**Comment by STew790** [comment]
**QA OK**
Tested as part of sanity and standard testing of new RC for desktop.
