### ISSUE TITLE
connect - sldev domain alias for cross origin testing

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#13132]
could I haz it?

**Comment by martykan** [comment]
We can probably skip this, I found a way to do this in Playwright by proxying requests

https://github.com/trezor/trezor-suite/pull/13031/files#diff-5b46eb0967298a9da65edf50f48035404d32ffec1dcb49dfece3565799117ae7R10

**Comment by mroz22** [comment]
yes, thanks! solved
