### ISSUE TITLE
EVM Tokens / Change route logic to avoid closing search and loading

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13142]
Try to use https://v5.reactrouter.com/web/api/Switch

Instead of having token routes defined in the main routes file, add also smaller router to main token component.

This will fix 
- loading between Coins / Collectibles / Hidden 
- closing search
- resetting filter

```
const TokenComponent = () => (

<div>
  <TokensSelectorAndSearch />
  <Switch>
     <Route id="coins" component={Coins} />
     <Route id="nfts"...
     <Route id="hidden"...
)
```

https://github.com/trezor/trezor-suite/assets/33235762/0c008f7d-cb44-438a-bd73-8d025d13659f

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.11.0 (3e2480c61fd43545db72544d59b7154b01abb5d7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Transport: WebUsbTransport
