### ISSUE TITLE
EVM Tokens / Generic table structure

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13152]
Create generic asset table which should be reusable on `Dashboard` and in `Tokens` tab in `Account`.
Please use css `grid`. The table should look the same as before, it should use newly created component `Table`

- [x] Create table https://github.com/trezor/trezor-suite/pull/13961
- [x] Use it in `Tokens` tab https://github.com/trezor/trezor-suite/pull/14013
- [x] Use it on `Dashboard`

Issue created based on feedback in [notion](https://www.notion.so/satoshilabs/Tokens-tab-improvements-b1a0a31ef3dd43fcb1079401c84c0bc6?pvs=4#9f54463c0a3c4a64b6f379195155ff97)

Tokens ✅ :
![Screenshot 2024-09-30 at 9 19 54](https://github.com/user-attachments/assets/475c14bf-9ca9-409d-8cbb-54988f2a5a31)

Dashboard 🟡 :
![Screenshot 2024-09-30 at 9 20 07](https://github.com/user-attachments/assets/6a4a1009-ff52-4224-96ac-8bcce38cfe79)

**Comment by enjojoy** [comment]
The table should be there instead of Cards on the mobile view as well?

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.11.0 (a682ea653d7d39851dc7129991b6a11eae493bdc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
