### ISSUE TITLE
Let me adjust the sats per byte value

### ISSUE THREAD

**Issue by jingxi285** [trezor/trezor-suite#13153]
Using latest Trezor suite I found I can't adjust the sats per byte value.
Seems sensible to have the current buttons to set Normal, or High, but why not let users edit as well?
High I recall is more than double the Normal amount.

**Comment by MiroslavProchazka** [comment]
Hi @jingxi285, for which coin you mean this? 
In BTC you can choose between low, normal, high and custom 
![image](https://github.com/trezor/trezor-suite/assets/152851523/0d8a8e74-29ef-49ba-92e5-f4481d4cd755)

**Comment by MiroslavProchazka** [comment]
@trezor/qa Can you verify please whether this applies even for LTC, Bitcoin cash and like network with sats unit?

**Comment by bosomt** [comment]
- checked 10+ coins
- found no discrepancy in fees settings
- all checked coins that are BTC like have custom fees in sats per B `sat/B`
- some coins dont have custom fees , thats expected

@jingxi285 please let us know more information about your issue

**Comment by komret** [comment]
Closing until reproduction steps are provided.
