### ISSUE TITLE
EVM Tokens/ Receive address modal tweaks

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#13155]
- Copy shouldn’t be desctructive.
- Cancel shouldn’t be primary
- Icon BG shouldn’t be green

![image](https://github.com/trezor/trezor-suite/assets/152851523/bccc065b-4573-4ad7-91e2-9c0d8ef31276)

approx like this pls
![image](https://github.com/trezor/trezor-suite/assets/152851523/52240d7e-031d-4510-bf72-e802441507be)

**Comment by bosomt** [comment]
**QA OK**

https://github.com/trezor/trezor-suite/assets/31506317/a5acbda3-e800-4629-a562-d4f46f5aa988


**Info:**
 - Suite version: desktop 24.7.1 (88dbe0410ac5b6245f392ce13e8c30f0f8f549f2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 3.0.0
