### ISSUE TITLE
Full RBF (step 2/2)

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#13159]
- ~Remove `[Finalize Transaction]`~ Its already gone: https://github.com/trezor/trezor-suite/pull/11730/files
- Allow replace all transaction despite RBF flag.

**Comment by komret** [comment]
Is there still something to do now that https://github.com/trezor/trezor-suite/pull/13226 is done?

**Comment by peter-sanderson** [comment]
> Allow replace all transaction despite RBF flag.

This is not possible. It will result in `-26: txn-mempool-conflict`. This makes sense as the original TX does not signal for RBF.

**Comment by peter-sanderson** [comment]
Turns out that `-mempoolfullrbf=1` enables such transactions.

**Comment by hynek-jina** [comment]
> It will result in -26: txn-mempool-conflict

This might be the case when custom backend is used. So we could improve the error to something like: "Your backend doesn't support replacement of finalized transactions"

**Comment by peter-sanderson** [comment]
@hynek-jina https://github.com/trezor/trezor-suite/issues/13285

**Comment by bosomt** [comment]
**QA OK**

1. ### sent tx from suite
 - RBF on/off switch not available
 - tx json "sequence": 4294967293 - RBF ON & Locktime ON
 - bump worked as expected
 - tx json "sequence": 4294967293 in new tx
 - https://btc3.trezor.io/tx/8aca86e7161fefc61971fbafc5bfda7b292f82fc53b4ee646ee34177a1e0efd3

2. ### send tx with locktime from suite
 - "sequence": 4294967293
 - bump ok
 -   "locktime": 854900, present after bump
 
3. ### send tx with RBF off and bump it in Suite
 - sent tx from old suite with RBF off
 -  "sequence": 4294967295
 -  RBF	OFF️ in blockbook
 - bump in new suite
 - "sequence": 4294967293
 - RBF	ON in blockbook
 - https://btc2.trezor.io/tx/7e097d8b690ff919a5fc6eecb3f5c606fc3bf7a057a7a842f02bd8f954e9da5a

**Info:**
 - Suite version: web 24.8.0 (a4a196fac842336986acdb51fc48c072a9217888)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
