### ISSUE TITLE
Full RBF (step 1/2)

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#13160]
- [x] All new transactions has RBF `ON` (remove UI to enable/disable it)
- ~[ ] Leave `[Finalize Transaction]`~ Its already gone: https://github.com/trezor/trezor-suite/pull/11730/files

Followup https://github.com/trezor/trezor-suite/issues/13159

**Comment by bosomt** [comment]
**QA OK**

- rbf switch or bump not available for other BTC like coins /checked LTC/
- rbf switch not available in send section
- rbf info not available in send/sign modal
- rbf info not available in transaction detail
- rbf ON reported in blockbook explorer
- finalize button not available
- bump button available
- rbv On reported in blockbook explorer after bump

**Info:**
 - Suite version: web 24.8.0 (d9959adfccff250c111f6e2b9bfb91305834cb3c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
