### ISSUE TITLE
Small FIAT id in Send dialogue in amount section

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13172]
**Describe the bug**
Small FIAT id in Send dialogue in amount section

**Steps to reproduce:**
1. see video

**Info:**
 - Suite version: desktop 24.7.1 (3856b5e5f845e68f754487dee863c6ea0c347070)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/6ebd0dc2-9d22-41f9-87d5-e7ea227b0bd8

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/4af3af97-c40b-4b71-90ab-4af7e022eb19)


**Info:**

Suite version: web 24.7.3 (https://github.com/trezor/trezor-suite/commit/19fd64f5b2ab1bc265821e34d4c4b9c910864d0e)
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
OS: Linux x86_64
Screen: 1920x1080
Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
Transport: BridgeTransport 2.0.32

**Comment by STew790** [comment]
closing

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.7.3 (19fd64f5b2ab1bc265821e34d4c4b9c910864d0e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
