### ISSUE TITLE
Modal instructions does not match device when bumping Stake Claim transaction.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13181]
**Describe the bug**
Modal instructions does not match device when bumping Stake Claim transaction.
See video, you are confirming Claim text twice but never fee.

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: desktop 24.7.1 (88dbe0410ac5b6245f392ce13e8c30f0f8f549f2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 3.0.0

**Screenshots:**

<img width="320" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/811c41f7-26d0-492c-bd6d-d4230b318045">

https://github.com/trezor/trezor-suite/assets/31506317/19caec2f-91e6-4be0-a6a1-b58611371172

**Comment by tomasklim** [comment]
Duplicate [#13397](https://github.com/trezor/trezor-suite/issues/13397)
