### ISSUE TITLE
T1 Pin mismatch video design

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1318]
See screenshot.
When there is Pin mismatch modal with video will open that's not muted and you can pause/stop it in this modal. 

![image](https://user-images.githubusercontent.com/31506317/76865559-2fba2200-6863-11ea-91f7-57d5d856aa33.png)

**Comment by bosomt** [comment]
+ that video plays over and over again :(

**Comment by glacierbits** [comment]
Duplicity: Being handled by #1230
