### ISSUE TITLE
Close after locked device in passphrase leads to wrong selected device

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#13192]
If device is locked and user goes to passphrase flow and cancels during pin screen - it gets closed but acquired (newly created instance) is still selected. It should forget this instance and select different device.
https://github.com/trezor/trezor-suite/assets/36101761/acb59d8b-dafe-4f1e-8155-974bc13135bb

**Comment by PeKne** [comment]
Notes for QA:
1. try to open passphrase device that is PIN-locked 
2. cancel the PIN screen 
3. you should be returned to the dashboard screen of previously opened device (If not, something is not working as it should.)

(demo attached in: https://github.com/trezor/trezor-suite/pull/13343)

**Comment by STew790** [comment]
**QA OK**
I am returned to the standard wallet correctly.

24.6.0 https://github.com/trezor/trezor-suite/commit/ff75009f1076edbd6476b90c97fa899ca7807b48
