### ISSUE TITLE
Connect device stuck when physical device that's also view-only is connected & unlocked 

### ISSUE THREAD

**Issue by shenkys** [trezor/trezor-suite#13198]
Connect device stuck when physical device that's also view-only is connected & unlocked 

**Info:**

-   Mobile Suite Version: 24.6.0., commit: 0af43838cf5d13a9566619b2dea......
-   OS: ios 17.5

**How to reproduce**

When I go to app -> wallet switcher -> change -> connect another device and connect the device that's also view-only, the connect screen does nothing and stays there. When X clicked

**Expected behavior**
No matter if the device is view-only or not, when in connect screen & unlocking device successfully, I should be moved to dashboard with correct device open

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/156302069/10757e3c-87be-471e-9686-3393d305ce13)

**Additional context**
None

**Comment by matejkriz** [comment]
@shenkys Is it OK to hide "Connect another device" button from the Device switcher IF you have selected connected device? So you have to unplug the device first and then you can search for connecting another device. 

I have to hide it in that case because I use connected state of selected wallet as condition to navigate out of this screen...

You can check the screen recording in the PR https://github.com/trezor/trezor-suite/pull/13566

**Comment by matejkriz** [comment]
@shenkys One more question - is it OK to navigate BACK? So if you trigger the Connect & Unlock screen from device switcher from Settings page, you end up back on Settings page (and you can see newly selected device in the Device Switcher on that page). Or should I change it to always redirect you to the Dashboard screen?

**Comment by shenkys** [comment]
> [@shenkys](https://github.com/shenkys) Is it OK to hide "Connect another device" button from the Device switcher IF you have selected connected device? So you have to unplug the device first and then you can search for connecting another device.
> 
> I have to hide it in that case because I use connected state of selected wallet as condition to navigate out of this screen...
> 
> You can check the screen recording in the PR [#13566](https://github.com/trezor/trezor-suite/pull/13566)

Agreed, let's do it.


> [@shenkys](https://github.com/shenkys) One more question - is it OK to navigate BACK? So if you trigger the Connect & Unlock screen from device switcher from Settings page, you end up back on Settings page (and you can see newly selected device in the Device Switcher on that page). Or should I change it to always redirect you to the Dashboard screen?

Agreed, let's do it.

**Comment by STew790** [comment]
**QA OK**
It takes a few seconds but app asks me correctly for passphrase of the device and shows it connected.

**Info:**
24.8.1 https://github.com/trezor/trezor-suite/commit/f2f56aa44a2843d9cae13ff77d8439882f1e9875
