### ISSUE TITLE
Added account is not visible in My Assets.

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13196]
**Describe the bug**
Added account is not visible in My Assets.

**Info:**

-   Mobile Suite Version: develop

**How to reproduce**

1. Go to My assets
2. Click on + (top right corner) with connected device after finished discovery
3. Chose bitcoin
4. Tap Continue with SegWit
5. New Bitcoin account detail appears (remember the #number)
6. tap X (top left) and app goes to My assets
7.  BTC account it #number is not present in the list

**Expected behavior**
in step 7. BTC account should be present

**Screenshots**

https://github.com/trezor/trezor-suite/assets/2011829/e8731c52-bf6e-4528-a53b-99f6640b058c

**Additional context**
- If user taps Change account type in step 4. and in next screen selects the same SegWit, it works correctly.
- For Coins that do not go through any kind of account type selection (ETH, ETC, DOGE) it works correctly

**Comment by STew790** [comment]
**QA OK**
Adding account works correctly.

24.6.0 https://github.com/trezor/trezor-suite/commit/814ab5d0df52939057bfa7643e7c0a83012e86f7
