### ISSUE TITLE
Labelling issues when using multiple Trezors

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#13204]
## Steps to reproduce

1. Add first Trezor
2. Rename wallet (allow labelling on device)
3. Add second Trezor
4. Rename wallet (allow labelling on device) 
5. Disable labelling in settings
6. Can't rename any labels 

## Expected behaviour
- disabling device should disable renaming only for specific device, not for all of them
- enable labelling should be in device settings, not in application

**Comment by Hannsek** [comment]
I disagree, labelling is an application feature. So if you disable labelling in Suite settings, it shouldn't be possible to do anything with the labels.

**Comment by Hannsek** [comment]
We can totally come up with some sophisticated setting, like disabling setting for the device when you have 2 or more connected at once. That does make sense.

**Comment by komret** [comment]
Closing as not planned.
