### ISSUE TITLE
Long addresses / symbol names in tx history break UI

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13210]
**Describe the bug**

In case of long addresses or symbol names in tx history when screen is bigger than 991px, sidebar width jumps and app gets out of window. See Video

**How to reproduce**

1. All seed cardano testnet and you should be able to see it
2. 1000px window

**Expected behavior**

https://github.com/trezor/trezor-suite/assets/33235762/19700c4e-48f7-4178-ae77-97362389bba4

**Comment by tomasklim** [comment]
Maybe the sidebar will be fixed by #13171

**Comment by hstastna** [comment]
> Maybe the sidebar will be fixed by #13171

Yes, exactly this is the fix. Thank you for opening this bug! :) I'll add it to the PR.

**Comment by hstastna** [comment]
Maybe we will also need https://github.com/trezor/trezor-suite/pull/13200 to let the sidebar work perfectly...

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.8.0 (61c84716ead502aad955db39b0326ff2eb29a294)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
