### ISSUE TITLE
Code signing of macos electron build

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1323]
Before we can distribute the app to the public we are gonna need some code signing magic.
https://www.electronjs.org/docs/tutorial/code-signing

<img width="423" alt="Screenshot 2020-03-18 at 12 02 09" src="https://user-images.githubusercontent.com/6961901/76954225-4c606380-6910-11ea-8244-50b9e4887464.png">

workaround for launching the app without all this:
1. right click on the app to show context menu => click "open"
2. you ll see this modal window
<img width="465" alt="Screenshot 2020-03-18 at 12 04 24" src="https://user-images.githubusercontent.com/6961901/76954488-b5e07200-6910-11ea-95af-48dc28342862.png">
3. click "open" again

**Comment by keraf** [comment]
MacOS builds are now signed (thanks @1000101 !)
