### ISSUE TITLE
Polygon - blur suspicious transactions

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13241]
Blur phishing txns

**Comment by STew790** [comment]
**QA OK**
It's not blurred. The same first transaction is blurred on desktop but not on mobile.
![image](https://github.com/user-attachments/assets/074f996f-f4e3-40c0-b087-4c3124c1cab3)

**Info**
24.9.2 https://github.com/trezor/trezor-suite/commit/b718af4a2b5d9fde28e1832276405f36a1c2399b

**Comment by vytick** [comment]
As we just discovered with @STew790 the discrepancy is in shown txns. Desktop shows some, that mobile does not show and one was blurred on desktop and hidden on mobile. 

So unless we want to change mobile logic and show all txns, this is not a bug, but feature.

cc @sime

**Comment by STew790** [comment]
**QA OK**
Finally found some :pray: 
![image](https://github.com/user-attachments/assets/30c1075f-19b6-4d01-9bac-ffd9122eeec3)
