### ISSUE TITLE
Please add Icelandic Króna to the Fiat currency list

### ISSUE THREAD

**Issue by mummi-digital** [trezor/trezor-suite#13249]
Please add Icelandic Króna to the Fiat currency list

 diff fiat.ts org-fiat.ts         
23d22
<     isk: { label: 'isk', value: 'Icelandic Króna' },

I am not a developer but would be happy to test, if needed.

thank you

**Comment by MiroslavProchazka** [comment]
Hi @mummi-digital , we are using Coingecko as a provider of fiat rates. Unfortunately 'Icelandic Króna' is not there. Can you approach them first please?

**Comment by MiroslavProchazka** [comment]
As we currently cannot implement this, I'm closing the issue for now. Please re-open once you will hear from Coingecko. Thanks!
