### ISSUE TITLE
Fix UI of Welcome Screen for dark mode

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#13257]
Borders and backgrounds in onboarding are broken (and it is first screen every new user see), fix it by [FIGMA](https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?node-id=689-9271&t=UKVccuAiW7tl0r0H-11)
<img width="1662" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/5fa976c2-4214-4292-980c-1dc896ec134b">

**Comment by STew790** [comment]
**QA OK**
Dark mode
![image](https://github.com/user-attachments/assets/6c2799dd-e72f-4bcb-89e9-d0a5c2b2c5bc)
![image](https://github.com/user-attachments/assets/9b8a3036-1a63-4fcf-bd46-5c6a5bc50ea3)
![image](https://github.com/user-attachments/assets/7b94117d-56dc-4002-bb9c-f0f4a9ac38d1)
![image](https://github.com/user-attachments/assets/f16841e5-885f-4b90-8a6f-a0ee2f36f328)
Light mode
![image](https://github.com/user-attachments/assets/84ee6824-20b5-47af-a4d2-1a9b9eaa036c)
![image](https://github.com/user-attachments/assets/ec3e7dc9-15dd-475d-896e-aa9d2fec19f3)
![image](https://github.com/user-attachments/assets/06dac675-e481-459d-b04f-b4793d545b44)
![image](https://github.com/user-attachments/assets/c2fb6cef-dd45-4cc1-b2ae-53a793b6ac80)

**Info:**
24.9.1 https://github.com/trezor/trezor-suite/commit/9ff8920814b8616034ab7375d1b6dbf9b5ec65ab
