### ISSUE TITLE
Coin Enabling - settings reorganisation

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13259]
Split Application group in settings into two:

<img width="367" alt="Screenshot 2024-07-09 at 22 36 31" src="https://github.com/trezor/trezor-suite/assets/2011829/0789a2e8-0f3e-4b1e-8d23-7c08216c30d7">

[Figma](https://www.figma.com/design/oQtgXoPIgGSlh01TLHnmeE/Coin-enabling?node-id=377-21746&t=bZoil3v12NSuv9No-0)

**Comment by vytick** [comment]
blocked by #13024

**Comment by STew790** [comment]
**QA OK**
"Enabled coins" correctly in "Features" settings.

**Info:**

24.8.0  5cd19fd
