### ISSUE TITLE
Polish Welcome screen

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#13261]
1. Check main button color - should be `variant="primary"`

2. There are multiple responsive issues:

![image](https://github.com/trezor/trezor-suite/assets/858321/bafbe3b4-1a54-489a-ab5b-796b4feb534b)

![image](https://github.com/trezor/trezor-suite/assets/858321/b99c4d9e-6ea8-430a-a5c2-9519791fdf6f)

3. Verify design with Ondra

**Comment by hstastna** [comment]
I think there are more places in Suite with the same overflow problem (especially with big zoom and small window size):
![wdyt](https://github.com/trezor/trezor-suite/assets/13417815/6e5a5810-39cc-41e0-9777-c9ab8b5b72fc)

**Comment by matejkriz** [comment]
One more important for us now (as we will navigate users from Suite Lite to mobile Suite Web for onboarding) 🙏 :
<img width="342" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/dc4199d0-cf40-4990-8331-376a35994d0b">

**Comment by hstastna** [comment]
![image](https://github.com/user-attachments/assets/82af61f8-54b3-4545-bdcd-f1cfbebfe033)

**Comment by jvaclavik** [comment]
One more screen. Can you please take a look @hstastna? 🙏 

![image](https://github.com/user-attachments/assets/9c94be04-ad70-4a6e-a596-52a4a5b3b740)

**Comment by hstastna** [comment]
Need to adjust view only promo content related screen, hence reopening the issue.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.8.0 (96da7b911c634b1506220e297f1e755ccd42394a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 bitcoin-only (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
