### ISSUE TITLE
Coin Enabling - enable via Add Coin

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13260]
- [x] Show all supported networks
- [x] If selected network is not enabled, enable it, run discovery for the coin
- [x] if discovery finds some account, show them 
- [x] user can go back while discovery is running and this closes Add coin flow
- [x] allow to add new coin even if discovery has found account(s)
- [x] if no account is found in discovery, add new (normal) account and go into its detail like in current version

<img width="250" alt="Screenshot 2024-07-09 at 22 40 14" src="https://github.com/trezor/trezor-suite/assets/2011829/15185415-9a8a-49fc-8c41-ae14b4fadf1d">
<img width="250" alt="Screenshot 2024-07-09 at 22 40 18" src="https://github.com/trezor/trezor-suite/assets/2011829/2c21a7f3-5232-4de0-ab3b-bab1595f7e53">
<img width="250" alt="Screenshot 2024-07-09 at 22 40 24" src="https://github.com/trezor/trezor-suite/assets/2011829/d68f73fc-fe94-49d7-98f9-a47e7a032219">

[Figma](https://www.figma.com/design/oQtgXoPIgGSlh01TLHnmeE/Coin-enabling?node-id=391-27727&t=bZoil3v12NSuv9No-0)

**Comment by STew790** [comment]
**QA OK**
- all supported networks are shown
- if selected network for wanted account is not enabled, it is enabled and there is a discovery for that coin
- if discovery finds any accounts, they are shown
- I can go back while the discovery is running
- I can add coin even if this coin was already discovered/enabled
- if no account is found, then the standard account is discovered and shown

**Info:**
24.9.1 https://github.com/trezor/trezor-suite/commit/bf893a5e0f152087cb4e47a4921a64c3c4c1624f
