### ISSUE TITLE
Replacing Final transaction with custom backend with fullrbf OFF leads to not-nice message

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#13285]
![image](https://github.com/trezor/trezor-suite/assets/152899911/715c3c14-fb60-4e85-bc4c-56e2dac58187)

https://github.com/trezor/trezor-suite/issues/13159#issuecomment-2220582463

**Comment by MiroslavProchazka** [comment]
As it is an edge case, I’m closing it until its priority increases.
