### ISSUE TITLE
Suite silent update

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#13281]
- [x] Add an option to Experimental Features to enable silent app updates. This should work the same as enabling Password manager.
- [x] When the experimental feature is enabled, show a `SectionItem` to the Application section in `SettingsGeneral` called "Automatic Trezor Suite updates" with `description` "Trezor Suite automatically downloads the latest version in the background and installs it when restarting the app. This ensures you're always up-to-date with the latest features and security patches. Updates occur without requiring your permission." and a `Switch` which is on be default.
- [x] When the setting is on, users don't see the update modal when there is a new version available. Instead, the new version is automatically downloaded in the background. This should work the same as downloading in the background in the current setup.
- [ ] When the new version is downloaded, a notification similar to the one you see when sending a transaction is shown. it says "A new version of Trezor Suite was downloaded. Restart to install." It includes a button saying "Restart". That should work the same as restarting after a new version is downloaded in the current setup.
- [x] Next time Suite is launched, it is the new version.

To investigate: Once the new version is downloaded, is it possible to prevent its installation by toggling the switch in Application settings?

Note: experimental features don't have final copy and don't use translations.

[Notion spec](https://www.notion.so/satoshilabs/Silent-Automatic-Update-ba941c59eb1b4597aa89d248c81b9de2?d=caf0bf86ae6949a5bbc6e0037598184f#791cbcad38944acbb06e95211a8b5144) (may be outdated)

**Comment by Hannsek** [comment]
A changelog should be accesible somewhere. I'd like to see a button in the notification with something like "what's new" and if you click on that you'd see a modal with the changelog… or something like that…

**Comment by hynek-jina** [comment]
@Hannsek 
Changelog is accessible from Settings → Application.
User just needs to click on the version number
<img width="906" alt="Screenshot 2024-07-31 at 19 33 02" src="https://github.com/user-attachments/assets/3e61faef-dd64-4fdd-b7c9-ca683b0d76f9">

**Comment by Hannsek** [comment]
I mean it should be accessible and _after_ the update (before it is in the settings and that is somewhat ok). Something like Brave or Signal update.

**Comment by bosomt** [comment]
- `Automatic Trezor Suite updates` switch is available in Experimental section
- `Automatic Trezor Suite updates` switch is available after enabled via experimental section
- `Automatic Trezor Suite updates` switch disappears when you disable `Experimental features` section
- actual update will be tested with with 24.9.1 release candidate

**Comment by bosomt** [comment]
**QA OK**

tested on 24.9.1 > 24.9.2 upgrade on macARM
we havent found any issue
