### ISSUE TITLE
Labeling is enabled without a complete user action and view-only settings is not kept when device prompt times out

### ISSUE THREAD

**Issue by ondracja** [trezor/trezor-suite#13294]
**Describe the bug**
When the user triggers a device action (like enable labeling prompt) and lets it time out, prompt disappears on its own. When suite is reloaded, view-only settings are switched to `disabled`

**Steps to reproduce:**
1. go through initial Suite run, `enable` view-only
2. go to settings and verify that labeling is turned off
3. go to a btc account and trigger label change by clicking on `Rename` next to the btc account name
4. a `Enable labeling` prompt should appear on the device
5. wait a couple of seconds, prompt should disappear on its own
6. go back to settings and observe that labeling is now `enabled`
7. reload the page
8. observe that `view only` is now disabled
9. go to settings and observe that labeling is still set to active

**Info:**
 - Suite version: web 24.8.0 (3808da45bc3bda5b173a97f30d25cae631f1f127)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: WebUsbTransport

**Expected result:**
- View-only state is persistent.
- labeling is not activated without user agreeing to it on the device

**Actual result:**
- view-only changes to `disabled`
- labeling is active without my consent

**Comment by STew790** [comment]
**QA OK**
View only stays enabled.

**Info:**
 - Suite version: desktop 24.7.2 (3282fe8f6f491e024c0cc9cae99f3085c229c96c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.32
