### ISSUE TITLE
Recovery mode

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1329]
Needs design: How should suite behave when user connects / selects device in recovery mode.

**Comment by glacierbits** [comment]
Product approves. Proceed as discussed @mroz22 . Thanks!

**Comment by glacierbits** [comment]
### 1st task 
- [ ] Illustration on first screen: **[Zeplin](https://app.zeplin.io/project/5d401d280d23b8354bdbf964/screen/5e26e70ac41f158086a15170)**




![Screen Shot 2020-04-01 at 09 26 25](https://user-images.githubusercontent.com/29627086/78110420-3916c300-73fb-11ea-9d82-e958eed9ee3c.png)



### 2nd task
- [ ] Fix padding around illustration (fixed button position)


![Screen Shot 2020-04-01 at 09 21 49](https://user-images.githubusercontent.com/29627086/78110644-a165a480-73fb-11ea-81ce-4f7be2b63891.png)

### 3rd task
- [ ] Fix progress bar to track progress accurately


![Screen Shot 2020-04-01 at 09 26 45](https://user-images.githubusercontent.com/29627086/78110745-d114ac80-73fb-11ea-85fd-2915240a9299.png)
