### ISSUE TITLE
Loading fiat value should show skeleton instead of 0 value

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13299]
**Describe the bug**
- fiat values of portfolio are not cached
- when you start app when offline you see all fiat values with zero value
- before fiat values are fetched from servers after you see start app all values are zero too for quite a long time
- same results for latest dev version, 24.7.1 version and two weeks old dev version

**Steps to reproduce:**
1. Import multiple accounts
2. Kill app
3. Start app with phone in flight mode or observe app before values are fetched from servers

**Info:**
 - Suite version: Release notes for 24.6.0 (350)
Last commit hash: 8a20d9cf4567a8077dd95d88212f9bd2eb66f89e

**Screenshots:**

![telegram-cloud-photo-size-4-5801191960428528094-y](https://github.com/trezor/trezor-suite/assets/31506317/7ba281b1-536b-4c37-bcfb-5fd4c265f6bb)

https://github.com/trezor/trezor-suite/assets/31506317/f965e330-d720-4c4c-add4-57c88a00244a

**Comment by matejkriz** [comment]
This is not a bug, it was always like that, so it's a feature request. I totally agree that we should not show 0 if we don't know the correct value, there should be nothing or skeleton or another loading indicator. 

Another possible improvement is storing historical fiat rates persistently, but there is a question if we can persist fiat rates for not remembered devices. As a key, we use timestamps rounded to hours. It is possible to persist only those used for some view-only wallet, but kinda hard to check all the transactions. Other possibility (compromise) is to make it persistent only if there is some view only wallet (including portfolio tracker) but do not check if the timestamped fiat rate is used for that wallet or for another that was not remembered...

**Comment by shenkys** [comment]
Solution: Add skeleton loader to the fiat value.

**Comment by yanascz** [comment]
Need to revisit, the layout shift got worse after last change on real device.

**Comment by STew790** [comment]
**QA OK**
Skeletons lgtm :skull: 
![image](https://github.com/user-attachments/assets/f60a49a6-76c3-49a8-902d-e6b5f928f2f5)

**Info:**

24.9.1 https://github.com/trezor/trezor-suite/commit/9ff8920814b8616034ab7375d1b6dbf9b5ec65ab
