### ISSUE TITLE
Analytics: View only & passphrase

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#13300]
Please add analytics events to track:

- View only
    - Promotional frame shown
        - [Yes / Not) now selected
    - View only enabled in wallet switcher settings
    - View only disabled in wallet switcher settings
- Passphrase
    - Settings: Passphrase selected as primary wallet to load

Please add all new events to data team's [Overview](https://www.notion.so/satoshilabs/device-setup-completed-d565806f8de24d8ca8b5db8150721d0c?pvs=4) and [Changelog](https://www.notion.so/satoshilabs/Changelog-Suite-1551ab666b1943f080ff56ffc6896d12?pvs=4).

**Comment by bosomt** [comment]
**QA OK**

<img width="822" alt="image" src="https://github.com/user-attachments/assets/8735d82e-06be-4060-ae38-29f75e47f250">

**Info:**
 - Suite version: web 24.8.0 (01a00268f81a8b0ac72d0dcf357d7bbcf8b79cce)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
