### ISSUE TITLE
Empty account fiat value quick fix

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#13309]
more info here: https://www.notion.so/satoshilabs/Empty-account-fiat-value-quick-fix-72eec25e9f6b4ff8964f3d009b9bdf38

**Comment by bosomt** [comment]
**QA OK**

trade box is present 

<img width="1072" alt="Screenshot 2024-07-23 at 12 23 30" src="https://github.com/user-attachments/assets/7e3b5c8d-92eb-4249-ae81-fdd91319cd6f">


**Info:**
 - Suite version: web 24.8.0 (76ee7c62a1b17ef35ed680a384b2b989aaeb00aa)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
