### ISSUE TITLE
Staking "Max" when amount is lower than 0.13 ETH + current fee

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13316]
**Description**
Right now `10%`, `20%`, `50%` and `Max` buttons are disabled when balance is from `0.1 ETH` to `0.1299999 ETH`. 
Max becomes enabled from `0.13 ETH` (included)

**Current solution**
- Unable to use `Max` when `<0.13 ETH`
![Image](https://github.com/trezor/trezor-suite/assets/216917/1c52fb66-06b1-46f2-86eb-ef88b2ad767c)

- `Max` button sets less than `0.1 ETH` when balance is `0.13 ETH` (because of fees)
![Image](https://github.com/user-attachments/assets/c122fa6b-63f2-468f-a956-2768f90450f1)

 
**Changes:**
Please enable max button when user has `>=0.1 ETH` (minimum amount)
- in case balance is less than `0.13 ETH + current fee to stake`, set `0.1 ETH` (minimum amount) into input.
- warning `It's recommended to leave 0.03 THOL so you can pay for withdrawal fees.` should explain the rest
![Image](https://github.com/user-attachments/assets/e7c148b2-62f9-4532-bb6b-e60d1f82cce3)

**Comment by MiroslavProchazka** [comment]
@tomasklim Should I change the copy in Crowdin then?

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.0 (17bac171ecd870c4d76bb64c6ec5f8d69b333d4c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
