### ISSUE TITLE
connect-explorer - defaults

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#13310]
<img width="690" alt="image" src="https://github.com/user-attachments/assets/6e598ddd-3a8e-4113-a680-8cd0c708fc10">

it looks like certain fields (bools, numbers) get prefilled with default nullable values? This is probably not what we want, or at least with applySettings definitely no. I typically want to change only one of the settings

Also autoLock=0 doesn't seem to be allowed.

<img width="735" alt="image" src="https://github.com/user-attachments/assets/29178d14-fbce-4dca-a3ab-307979bd8cd1">

**Comment by mroz22** [comment]
assigned to @martykan not a high prio though

**Comment by evgenysl** [comment]
@martykan 
I'm still getting this on 9.3.1-beta.3
![Screenshot](https://github.com/user-attachments/assets/72985de6-a87b-4439-9dd0-db40f191ec33)

**Comment by martykan** [comment]
@evgenysl I'm not seeing it, can you please describe the reproduction steps in more detail? 

<img width="1106" alt="Screenshot 2024-08-28 at 20 25 36" src="https://github.com/user-attachments/assets/8a8b1417-a03e-44cd-83f7-e013fd6fdb28">
