### ISSUE TITLE
Coins settings coin features quick fix

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#13319]
Although we inform in coins settings about coins having tokens, we don't inform about staking. Let's please start informing about staking and improve how we do it in following two steps:

1. As an addition to the translation key `TR_INCLUDING_TOKENS` that says `Including tokens`, create a new one that will say `Incl. tokens & staking`, so we can distinguish between coins that only have tokens and coins that have both tokens and staking.
2. Improve this feature by removing the label from `networksConfig` and manage it by content of `features`
    a. [More details here](https://satoshilabs.slack.com/archives/C05R69DBKSN/p1720781428917929?thread_ts=1720777491.587909&cid=C05R69DBKSN)

**Comment by bosomt** [comment]
**QA OK**

only thing im missing is testnet /cardano and holesky/ staking label :)



![Image](https://github.com/user-attachments/assets/3c1a0606-507f-45bd-af87-beaee880ead3)



**Info:**
 - Suite version: web 24.8.0 (986443265e98fc01bb2824dc8ea43dead2bd0113)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: WebUsbTransport
