### ISSUE TITLE
Replace Spinner with slower one

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#13311]
Our spinner spins like crazy so we need to replace it with slower one.

Lottie file for spinner animation: [Refreshing Spinner (MIDDLE).json](https://github.com/user-attachments/files/16190052/Refreshing.Spinner.MIDDLE.json)
More info in notion: https://www.notion.so/satoshilabs/Check-loaders-24bbda03e90a4027bb2fe6d2d3d6bfe3

## Storybook 

You can test `Spinner` component in the design system storybook:

```bash
yarn workspace @trezor/components storybook
```

<img width="579" alt="image" src="https://github.com/user-attachments/assets/57a1000d-eaa9-441d-9776-2842557569e5">

Optional task: Add all Spinner props to controls in stories (`packages/components/src/components/loaders/Spinner/Spinner.stories.tsx`)

## New animation

https://github.com/user-attachments/assets/6a0040e2-d38d-428a-82fe-8a8028e0499b

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.8.0 (fe65e0963b951f8b8bf820916ca877d953964058)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
