### ISSUE TITLE
Warning messages displayed for all devices

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13315]
**Describe the bug**
Warning messages displayed for all devices in new view-only design.
Current production version only shows messages related to active device.
This breaks anchors navigation.

**Steps to reproduce:**
1. Connect and remember device
3. Connect device with warning /backup failed or similar/
4. Navigate to remembered device observe and click on message warning.

**Info:**
 - Suite version: desktop 24.7.1 (bb6f170ca3198acfb906696c234ed5aa660ccf09)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 bitcoin-only (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/user-attachments/assets/1c0e3c8c-e46b-4625-ae44-549d68c0d326

https://github.com/user-attachments/assets/fed57959-43ec-4bed-b33e-b6f97b0f64dc

**Comment by peter-sanderson** [comment]
@bosomt We did not managed to replicate it. Please :pray: can you replicate it once again.

**Comment by STew790** [comment]
We couldn't replicate it. Closing.
