### ISSUE TITLE
Suite does not display tokens without symbol

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#13322]
From [slack conversation](https://satoshilabs.slack.com/archives/C03SRP8PSS2/p1720429988564829)

![image](https://github.com/user-attachments/assets/9a2510f0-4d3a-4001-b7cd-44428e3e41b5)

Test token:
`0xa1Ac2d8a57b70ff9637521F76D5733260c6F0f5a`

**Comment by bosomt** [comment]
**QA OK**

i was able to add manually mentioned token and i can see it in token list

![Image](https://github.com/user-attachments/assets/9af55a17-debe-4883-996d-becf2ddec70b)


**Info:**
 - Suite version: web 24.8.0 (fe65e0963b951f8b8bf820916ca877d953964058)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
