### ISSUE TITLE
Txs on ETH network are getting stuck forever

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13329]
Because of gas price close to 1, transactions are getting stuck because we floor down gas price. E.g. Blockbook return `1.932323` and we just sent tx with gas price `1`.

See gas price of this week
![Screenshot 2024-07-14 at 23 19 47](https://github.com/user-attachments/assets/237cb072-e151-44be-b970-ce742e595512)

https://milkroad.com/ethereum/gas/

The gas price was lowered than 2 for at least 30% time

After sending tx, users have to bump fee immediately. However, sometimes this also does not work because of wrong pending tx data from blockbook

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.7.2 (3282fe8f6f491e024c0cc9cae99f3085c229c96c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
