### ISSUE TITLE
Account does not exist in send dialogue

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1333]
1 passphrase - OK
2 passphrases - not OK

please show only accounts from currently active wallet.

![image](https://user-images.githubusercontent.com/31506317/77057308-0bca1e00-69d4-11ea-9648-ddd400d3e14d.png)
![account](https://user-images.githubusercontent.com/31506317/77057316-0e2c7800-69d4-11ea-8362-a6ab94d6c3e1.gif)

**Comment by szymonlesisz** [comment]
related to https://github.com/trezor/trezor-suite/issues/1294

**Comment by bosomt** [comment]
@szymonlesisz nice ! 
as soon it's fixed I will close it
