### ISSUE TITLE
Fix switch device icon in sidebar 

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#13332]
![image](https://github.com/user-attachments/assets/92a0db5e-d1f9-4ee2-915c-1f3dfc235321)

(it definitely happened in Firefox)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.8.0 (cfe5d486a85f9ab85f4447101456d9ac4f56d5a8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
