### ISSUE TITLE
EVM Tokens/ Add unhide token modal warning

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13336]
Please warn user when he unhides token

**Comment by bosomt** [comment]
**QA OK**

i see

```
Unhide this token?
This token appears to be suspicious and may be a scam.
```

modal

**Info:**
 - Suite version: desktop 24.8.0 (68068a49c689e6441ffbf3d164ea26b7c9ef3886)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.8.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 3.0.0
