### ISSUE TITLE
EVM Tokens/ Allow user to show 0 balance tokens

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13338]
Prerequisite for #13039

Allow user to show 0 balance tokens to be able to operate with all tokens he has in tx history and if he want to trade it

Rabby also shows it under this button
![Screenshot 2024-07-15 at 12 38 55](https://github.com/user-attachments/assets/b0bb9aeb-39be-4f29-acbd-7b09e132cf63)

Design:
![image](https://github.com/user-attachments/assets/cd0f5850-f55f-493e-a338-ac2def1479c1)

**Comment by tomasklim** [comment]
![Screenshot 2024-07-16 at 13 01 24](https://github.com/user-attachments/assets/29c419b6-a02a-4c89-b20a-33c462935f5d)

**Comment by Hannsek** [comment]
Do we know how to do it? Or we need any design/UX work?

**Comment by bosomt** [comment]
Is it expected that section is available even when there are no 0 tokens ?


https://github.com/user-attachments/assets/62285310-ea7c-485e-8f71-17069db0c7f5

**Info:**
 - Suite version: web 24.8.0 (90b029d7f70e030bc2a7cfd2b178df9b45fbd5d1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.32

**Comment by Hannsek** [comment]
I'd remove it if no token is present.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.9.0 (808c28ba480a9614eba7f28ee2a37aa5dc147fa8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
