### ISSUE TITLE
Staking dashboard - amounts in wide wrapper

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13344]
Tooltip is visible on whole container, should be available just on amount. Applies for all values available on dashboard

![Image](https://github.com/user-attachments/assets/5767a9ac-5566-4f93-8307-5b2533e8edf1)
![Image](https://github.com/user-attachments/assets/7e09f9b8-2acd-447e-8582-e91bb270c43c)

**Comment by tomasklim** [comment]
https://github.com/user-attachments/assets/413ad6d2-77fd-4af9-b094-92a82a8e0c6d

**Comment by bosomt** [comment]
**QA OK**

tooltip is only rendered when hoverin over amount number

**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
