### ISSUE TITLE
Delete isViewOnlyModeVisible flag (view-only)

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#13359]

**Comment by bosomt** [comment]
**QA OK**

flag is already gone from `Settings/Debug/View only` section

**Info:**
 - Suite version: desktop 24.8.0 (e3effd817c278b7877a1f1f8e24d74f78a56d374)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.8.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
