### ISSUE TITLE
Coin amount cropped when sending token with long name shortcut

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13365]
**Describe the bug**
Coin amount cropped when sending token with long name shortcut

**Steps to reproduce:**
1. Send [Staked Frax Ether (sfrxETH)](https://eth1.trezor.io/address/0xac3E018457B222d93114458476f3E3416Abbe38F)
2. Observe amount field

**Info:**
 - Suite version: web 24.8.0 (7e8611e4742617894b6c40feaa64314abc6dd183)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 3.0.0

**Screenshots:**
<img width="713" alt="Screenshot 2024-07-16 at 14 57 33" src="https://github.com/user-attachments/assets/019a0f7f-8b9a-400e-baa1-efbb5c5c7e6b">

**Comment by tomasklim** [comment]
@bosomt does is still happen on develop?

**Comment by bosomt** [comment]
**QA OK**

new send form looks 🆒 

<img width="728" alt="image" src="https://github.com/user-attachments/assets/35cc1772-c5be-4915-a166-5789b1906bf7">

**Info:**
 - Suite version: web 24.12.0 (c6241643be36851ab6ce21b6b663d20c9c5c5983)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport
