### ISSUE TITLE
Portfolio graph value not updated after change of fiat currency 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13374]
**Describe the bug**

Portfolio graph value not updated after change of fiat currency .
See screenshots, amount/value number is still same even after you change ti from USD to ARS
https://satoshilabs.slack.com/archives/G019WLX2P7B/p1721137707181419

**Steps to reproduce:**
1. Load portfolio a check value in graph
2. Change fiat currency to something totally different 
3. Check axis values

**Info:**
 - Suite version: web 24.8.0 (7e8611e4742617894b6c40feaa64314abc6dd183)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="860" alt="Screenshot 2024-07-16 at 17 36 06" src="https://github.com/user-attachments/assets/783438d6-c71d-4acb-aea0-a202dc2b0094">
<img width="862" alt="Screenshot 2024-07-16 at 17 35 55" src="https://github.com/user-attachments/assets/b706b78a-316b-4fef-9d15-58f9513b9176">

**Comment by hynek-jina** [comment]
I didn't even had to change the fiat currency to get the bad result...

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.7.3 (19fd64f5b2ab1bc265821e34d4c4b9c910864d0e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

<img width="867" alt="Screenshot 2024-07-26 at 11 28 24" src="https://github.com/user-attachments/assets/0e136874-a4d2-491c-95dd-2249fee78776">
<img width="752" alt="Screenshot 2024-07-26 at 11 28 13" src="https://github.com/user-attachments/assets/6378bacf-cfca-4d78-a75d-38c963f6b753">
