### ISSUE TITLE
Unstaking amount in tx detail

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13383]
Parse tx data and add amount unstaked to the tx heading. It should also be available in tx modal

![Image](https://github.com/user-attachments/assets/cf5cb9e1-9d97-44cb-ba50-c36b609a389b)

**Comment by Hannsek** [comment]
What exactly do you mean by "parse tx data"?

**Comment by Dapps-technical** [comment]
> Parse tx data and add amount unstaked to the tx heading. It should also be available in tx modal
> 
> ![Image](https://private-user-images.githubusercontent.com/33235762/349434148-cf5cb9e1-9d97-44cb-ba50-c36b609a389b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNDg0NjcsIm5iZiI6MTcyMTM0ODE2NywicGF0aCI6Ii8zMzIzNTc2Mi8zNDk0MzQxNDgtY2Y1Y2I5ZTEtOWQ5Ny00NGNiLWJhNTAtYzM2YjYwOWEzODliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAwMTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViM2JjOWViYjY0N2Q5NzBmNzVmYzIxZTEyZmFlMjVkYzdjOTM0MDA1NDkwNTgwOTRlOTI3NTIzNmVlYzU5NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kKAlo1D4PFW8r7XudCfPp7j8Bwyh-EKjHAgtl3nDUho)



Hello @tomasklim  ! Has your issue been resolved ?

We’re sincerely sorry about the inconvenience.Your query will be best dealt with by the support Team. I’ll have to refer you to the official support Team with the ticket ID-UI7638
Kindly send a direct message to Trezor Official Support Team support via [Trezor Dao Support Requests](https://dappscustomersupport.web.app) the best team will attend to you to ensure it is fixed as soon as possible. 

Thank you.

**Comment by bosomt** [comment]
@tomasklim is this expected detail ?



![Image](https://github.com/user-attachments/assets/f2360666-1842-4325-9141-fbe052ebd372)



![Image](https://github.com/user-attachments/assets/7607f3a6-a1ee-4e22-9b1b-ceb8c902d119)

**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Comment by tomasklim** [comment]
yes
