### ISSUE TITLE
Unstake modal - Other amount 100% width

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13382]
Inputs should take whole modal width

![Image](https://github.com/user-attachments/assets/f628b130-428d-482d-aa6a-b231706c3a70)

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/user-attachments/assets/ef1659bb-73c4-4899-8cbe-762bf0d208f7)


**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
