### ISSUE TITLE
Ethereum staking low gas warning

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13381]
As of writing, [there are 70 staking transactions](https://etherscan.io/txsPending?a=0xD523794C879D9eC028960a231F866758e405bE34&ps=50&sort=gasprice&order=desc&m=hf) (~242 ETH) pending in the mempool with really low gas price. i.e 1-5 Gwei.

Users should be advised that low gas prices transactions will not be confirmed in the predictable future.

![Image](https://github.com/trezor/trezor-suite/assets/216917/99da6ab3-652d-4d82-a15b-36dd5448b2b7)

**Comment by MiroslavProchazka** [comment]
Should be resolved by https://github.com/trezor/trezor-suite/pull/13388, no?

**Comment by tomasklim** [comment]
It looks like there are no more issues after releasing new version. People are not stuck anymore with 24.7.2+ version

@MiroslavProchazka please remove banner for 24.7.2+

![Image](https://github.com/user-attachments/assets/2358fce2-875b-44c6-98c5-e681b1d7abec)

Would be nice to improve texting for 24.7.1- to also target people who want to stake without upgrading to new version. All the people stuck have gas price `1`. It is right now 442 ETH stuck in 117 txs

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.7.1 (d97e8c2769f8b2751a8db3c4109c10619cf8b926)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
