### ISSUE TITLE
Line above other amount when no rewards to unstake

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13392]
![Image](https://github.com/user-attachments/assets/20bafd6f-466a-443f-9a7e-a084351f99c3)

**Comment by tomasklim** [comment]
solved in [#13469](https://github.com/trezor/trezor-suite/pull/13469)

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/user-attachments/assets/0d723b96-7aa5-4734-ae30-c94c90d59a5b)


**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
