### ISSUE TITLE
Remove ConnectDevicePromptManager

### ISSUE THREAD

**Issue by martykan** [trezor/trezor-suite#13399]
Remove last remaining uses of `ConnectDevicePromptManager` and replace them with `PrerequisitesGuide`, to avoid unnecessary code duplication
This affects `FirmwareModal`, `FirmwareStep`, `FirmwareInitial`

**Comment by bosomt** [comment]
**QA OK**

tested with multiple devices and firmwares before and after merge to develop, it will be futher tested during release cycle sanity tests
https://www.notion.so/satoshilabs/remove-ConnectDevicePromptManager-6e57f261390b4b1d9c8f93b2239e9882

**Info:**
 - Suite version: web 24.8.0 (a707883081ddf9f3b75ececcb0e8a38732136988)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
