### ISSUE TITLE
design bug - coinmarket exchange 

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#13391]
## Describe the bug
There is no space between the crypto amount input and the fiat amount input in the _Exchange_ section. The _Buy_ and _Sell_ sections are correct.

## Info

-   Suite Version: 24.8.0 web 
-   Browser: Firefox 128.0
-   OS: macOS Sonoma 14.5
-   Bridge: 2.0.27
-   Firmware Version: 1.12.1

## How to reproduce

1. Go to Trade/Exchange

## Expected behavior
Space between the crypto amount input and the fiat amount input.

### Bad design
![obrazek](https://github.com/user-attachments/assets/d952c705-c2d0-4dd4-9af0-bf760d2a9e11)![](https://files.slack.com/files-pri/T0J8V2YBY-F07DFKD85B2/screenshot_2024-07-15_at_14.45.47.png)

### Correct design
![obrazek](https://github.com/user-attachments/assets/d86aeee5-d3a0-48be-9d4e-c3de2a89018e)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.9.0 (983e42f2cc2f6fb51463a26c7f6206c4f56a3d14)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
