### ISSUE TITLE
Deduplicate data info during bumping fee in review tx modal

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13397]
When bumping fee on staking/unstaking/claiming, the info about action is shown twice and it should not

Something should probably be modified in `TransactionReviewOutput.tsx`

![Image](https://github.com/user-attachments/assets/30cfcf65-6aeb-4672-98dd-4500c49cc32e)

![Image](https://github.com/user-attachments/assets/10758e4b-e3d4-425a-b599-d84ed315da16)

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/26492007-780c-4583-9136-64111f5a6a87)

**Info:**
 - Suite version: web 24.11.0 (258ab9664fb9cddbc0bd28638f00b56583b15e1d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Transport: WebUsbTransport
