### ISSUE TITLE
Send dialogue prefilled after bumping transaction 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13404]
**Describe the bug**
Send dialogue prefilled after bumping transaction.
Managed to replicate it 3 times in row.

**Steps to reproduce:**
1. Navigate to Send dialogue and clear it
2. Find pending transaction and bump it
3. Navigate to Send dialogue and check if its pre filled 

**Info:**
 - Suite version: web 24.8.0 (fe65e0963b951f8b8bf820916ca877d953964058)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/user-attachments/assets/f2d74de0-2714-4d4b-9528-32f9871daed5

**Comment by tomasklim** [comment]
Duplicate https://github.com/trezor/trezor-suite/issues/13325
