### ISSUE TITLE
Suite incorrectly calculates transactions using different fiat rates.

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#13408]
If I send the first transaction in a fiat currency, for example, CZK, the next transaction uses the same fiat currency as the first transaction. As you can see in the screenshot, 10,000 CZK is correctly converted to BTC, but 10,000 EUR gives the same BTC amount as the CZK transaction. I entered the transactions manually. 
![image](https://github.com/user-attachments/assets/67c0c385-94ad-430a-ab84-e0ecbbba81c2)

https://github.com/user-attachments/assets/45a01274-6294-48ba-b8b2-e934650168ec

**Comment by bosomt** [comment]
**QA OK**

https://www.notion.so/satoshilabs/multiple-recipients-fiat-calculation-send-form-4756846d284d46d895733924f0ed45c9

**Info:**
 - Suite version: web 24.8.0 (15dcfb4ed241fe8261cf9060eefc7bd4e25aa68d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Comment by tomasklim** [comment]
@AdamSchinzel @bosomt 
Does not work for cardano
![Screenshot 2024-07-23 at 14 32 27](https://github.com/user-attachments/assets/21f12e02-38b7-4878-87b8-a96746a2a998)

**Comment by bosomt** [comment]
**QA NOK**

i can confirm that it does not work for Cardano tokens.
Reopen or followup ? @MiroslavProchazka @AdamSchinzel 


https://github.com/user-attachments/assets/c5ae245b-b9ac-4323-a648-b4fb1fe5018c

**Info:**
 - Suite version: desktop 24.7.3 (19fd64f5b2ab1bc265821e34d4c4b9c910864d0e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**Comment by MiroslavProchazka** [comment]
Please create separate issue just for ADA tokens and mention it to this issue. Thx!

**Comment by tomasklim** [comment]
**TK OK**

just tested, works ok, for some specific tokens it is slow because of coingecko contract addresses issue

@bosomt I think it is just slow network. In case of some cardano tokens, it has to do 2 fiat rates fetches. The first one has to fail. I think if you wait 1-5 seconds, the fiat correctly updates.

<img width="743" alt="Screenshot 2024-07-29 at 14 00 42" src="https://github.com/user-attachments/assets/9c05a818-a98e-48b7-b9fd-71de0df56377">

**Comment by bosomt** [comment]
**QA OK**

it works fine now with ADA tokens, guess it was really slow network

**Info:**
 - Suite version: desktop 24.7.3 (19fd64f5b2ab1bc265821e34d4c4b9c910864d0e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
