### ISSUE TITLE
DOGECOIN transaction error : Sign transaction error: Invalid parameters: Parameter "amount" has invalid type. "string" expected.

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#1341]
Expected:
Transaction will go through.

Actual:
Cannot send transactions in current web suite. Exact issue as #1336 ,  #1339 and #1340  . Transaction will notify you with this error:
Sign transaction error: Invalid parameters: Parameter "amount" has invalid type. "string" expected.
![DOGE transaction error](https://user-images.githubusercontent.com/58593111/77088602-fc16fd80-6a04-11ea-9f91-ab2916bf0125.png)

@vladimirvolek check it out, please.

**Comment by bosomt** [comment]
still broken in web suite

**Comment by vladimirvolek** [comment]
fixed in develop
