### ISSUE TITLE
Send coins - analytics

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#13414]
Some metrics based on doc from desktop: https://www.notion.so/satoshilabs/transaction-created-16a7363c8ab14dce95d506d26ff2adcf?pvs=4 

Sent actions
1. Coin&token (symbol) - Which coin(+token) was sent
2. Send parameters
- selected fee
- number of recipients
- inserting recipient address via inserting text / scanning the QR code
- click on FIAT switcher
3. Send form churn 
- (funnel - Address&Amount, Fee settings, review&Sign, Successful send) - from which step user dropped
- Users who left the app on the screen Review&Sign

**Comment by STew790** [comment]
Will be checked after release with analytics dept.
