### ISSUE TITLE
DGB BCH VTC bad address validation

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#1342]
Expected:
Send address validation will work correctly for all coins.

Actual:
**Cannot send transactions to valid addresses on these coins: DigiByte DGB, Vertcoin VTC, Bitcoin Cash BCH.** Suite will flag the addresses as incorrect, but they are not (wallet.io flags them as valid and sent coins do end up on the receiving accounts successfully). 

@vladimirvolek please look into this, thank you!

**Comment by vladimirvolek** [comment]
Can you please provide some examples? I don't see any problem.

DigiByte (https://chainz.cryptoid.info/dgb/address.dws?1443818.htm)

![image](https://user-images.githubusercontent.com/3112191/77688338-36057800-6fa0-11ea-9a5c-527485b318b7.png)

Vertcoin (https://chainz.cryptoid.info/vtc/address.dws?VyJ9NKD8W8WcLZgLorg37L7hKBxia7pz3x.htm)

![image](https://user-images.githubusercontent.com/3112191/77688438-5fbe9f00-6fa0-11ea-820c-ad773b1b72b1.png)

**Comment by wendys-cats** [comment]
@vladimirvolek the problem is still there. You can see in this screenshot very clearly - Suite will mark the address (that suite gave as a receiving adress for the second DGB account, btw) as invalid, while trezor wallet marks it as a valid address. 
![DGB](https://user-images.githubusercontent.com/58593111/78032298-1508a280-7365-11ea-9ecb-713ac6a07dd9.png)

**Comment by sorooris** [comment]
The issue persists with DGB:
An address generated in Suite's second account's receive form and pasted in the first account's send form validates it as a invalid address. The same address then validates as valid in the latest stage wallet.
Suite:
![image](https://user-images.githubusercontent.com/10185314/78035208-120fb100-7369-11ea-97f9-97096a26d110.png)

Stage Wallet
![image](https://user-images.githubusercontent.com/10185314/78034717-623a4380-7368-11ea-962e-71809243b6f2.png)

**Comment by vladimirvolek** [comment]
related to https://github.com/christsim/multicoin-address-validator/issues/9

**Comment by bosomt** [comment]
@vladimirvolek that issue is open for one year and no reply yet.
we need to solve it somehow. It's impossible to send DGB transactions

**Comment by bosomt** [comment]
wroks fine with DGB VTC and BCH /normal and legacy accounts tested/
