### ISSUE TITLE
Account #5 appears after adding account #3 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13435]
See video.
Account #5 appears after adding account #3 
I was not able to reproduce it on 24.7.1
@STew790 managed to replicate this issue on BTC account with different seed

- Android 14
- Nothing phone 1
- version 24.7.2 7dd5a5f

<img width="290" alt="image" src="https://github.com/user-attachments/assets/3ffcdd5e-366e-48f7-bda1-863eb9959f53">

https://github.com/user-attachments/assets/c61e91b1-c528-49cf-84f3-b253e191b2e6

**Comment by STew790** [comment]
**QA OK**
I no longer see additional accounts.

24.7.2 6975009

**Comment by bosomt** [comment]
**QA OK**

im not able to reproduce the issue anymore

24.8.0 8cfac13
