### ISSUE TITLE
Cannot find the add token button in my ethereum account

### ISSUE THREAD

**Issue by ckc1984** [trezor/trezor-suite#13441]
Hi guys,

I upgraded my trezor suite app to version 24.7.2. I cannot find the "add token" button in my ethereum account. Do you have the same issue?

**Comment by Hannsek** [comment]
There is no Need to have one. All tokens are automatically shown in the "tokens" tab.

And if you just want to receive any toke use the eth (if we are talking about eth tokens) address.
