### ISSUE TITLE
Issue with Ping proto definition in Trezor common repo

### ISSUE THREAD

**Issue by shrimalmadhur** [trezor/trezor-suite#13440]
Hello, 

I am checking trezor cli and the [Ping](https://trezor.io/learn/a/using-trezorctl-commands) command in that has 3 fields 
```
-b or --button-protection
-p or --pin-protection
-r or --passphrase-protection
```

But the proto definitions in the [trezor-common](https://github.com/trezor/trezor-common/blob/68502be56e9fa2d600b0ff5fdc808a747b7371a6/protob/messages-management.proto#L305-L308) repo doesn't have the same interface. Why is there a discrepancy. As far as I can recall, there used to be fields in `Ping` command before which had pin protection and passphrase-protection

Is there a reason? Did it move somewhere? How can I achieve the same programmatically ?

**Comment by MiroslavProchazka** [comment]
Hi, @shrimalmadhur.

Can you please open issue in the FW repository? Suite does not have anything in common with trezor ctl. 

Thank you,
