### ISSUE TITLE
"Your browser is not supported" modal/page improvements - Popup (3rd party app)

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#13447]
Based on https://github.com/trezor/trezor-suite/issues/12486.

If it is popup when using 3rd party app, please change the copy to:

"Device Not Detected

Your browser is not supported. For the best experience, please download and run the Trezor Suite desktop app in the background or use a supported Chromium-based browser that is compatible with WebUSB."

**Comment by martykan** [comment]
I would use a more precise title rather than "Device Not Detected", to really clarify that it's not an issue with the device or connection. Right now the title is "Browser can't communicate with device"

**Comment by Hannsek** [comment]
yeah, can be, even though it is right under: "your browser is not supported".

But let's put there "Browser can't communicate with device"

**Comment by martykan** [comment]
Yeah, but you know how it is, most people don't actually read things properly 😄

**Comment by martykan** [comment]
![Screenshot 2024-07-30 at 09 44 36](https://github.com/user-attachments/assets/cf38ce54-d50a-4937-96db-af2e7567c571)

This is the current state, we can close this right? @Hannsek

**Comment by Hannsek** [comment]
I'd like to see there in the body "Your browser is not supported. For the best… "

**Comment by martykan** [comment]
Message updated as part of #13651

**Comment by evgenysl** [comment]
**QA OK**

<img width="1078" alt="Screenshot 2024-08-26 at 08 32 55" src="https://github.com/user-attachments/assets/df280b94-15ec-47d1-8b8b-7c0dcfb024c2">
