### ISSUE TITLE
Connecting device first and starting app second throws an error

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#13456]
**Describe the bug**
If I connect my device first and start the app via the prompt on Android, the app then shows a connection error and prompts me to "Reconnect device". I have to have already one view-only wallet in the app first. I also can't get out of this state unless I reconnect the device which the app don't exactly say I should do, unfortunately.

**Info:**

-   Mobile Suite Version: 24.6.0 https://github.com/trezor/trezor-suite/commit/ff75009f1076edbd6476b90c97fa899ca7807b48
-   OS: Android 12

**How to reproduce**

1. Connect your device
2. Wait for the discovery of the standard wallet and enable view only
3. Disconnect the device and kill the app
4. Connect the device and select to start the app when the Android prompt shows
5. A connection error is shown in the app

**Expected behavior**
My device correctly connects and discovery happens

**Screenshots**
![image](https://github.com/user-attachments/assets/9bab050b-d176-4ca7-b392-05950638426a)

**Comment by matejkriz** [comment]
It might be connected to https://github.com/trezor/trezor-suite/issues/13198

EDIT: No, it's not at all.

**Comment by STew790** [comment]
**QA OK**
After wiping data of app it worked fine but before I wiped it I got the error again, sadly. I couldnt really reproduce it but I will definitely monitor it in the stable/production app testing.

**Info**

24.8.0   5cd19fd
