### ISSUE TITLE
Tx history is jumping

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13471]
**Describe the bug**
Tx history is jumping because of `Add label` button

**Info:**

-   Suite Version: 24.8.0

**How to reproduce**

1. Go to tx history and hover address

**Screenshots**

https://github.com/user-attachments/assets/9bb2ba06-9809-42ab-b21a-2e64c6b3622b

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
