### ISSUE TITLE
Coin Enabling - message system compliance

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13470]
Make sure that message system can correctly detect which coins are enabled to correctly show banner based on this.

**Comment by STew790** [comment]
**QA NOK**
https://github.com/trezor/trezor-suite/pull/14233 this is still not merged :thinking:

**Comment by matejkriz** [comment]
> **QA NOK** #14233 this is still not merged 🤔

Now it's released on develop, you can test it.

**Comment by vytick** [comment]
@STew790 can be tested now with a bit different testsing message (for nmc, dash, btg, vtc)

**Comment by STew790** [comment]
**QA OK**
Yes, this is now working correctly for me :tada:
