### ISSUE TITLE
Make desktop build usable on 1366x768

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1348]
thanks @bosomt for the heads-up! 
<img width="829" alt="Screenshot 2020-03-20 at 11 14 07" src="https://user-images.githubusercontent.com/6961901/77154412-ec96c380-6a9b-11ea-90c8-ffd682ea111e.png">

**Comment by glacierbits** [comment]
I am kindly closing this issue and putting the screenshot into the _Reponsivity_ issue #1359 as to keep things organized. Thanks!
