### ISSUE TITLE
View only wallet showing "Your wallet is empty" even though it isn't

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#13485]
**Describe the bug**
When you connect a device and enable a view only feature for it and for the wallet and kill the app and start it again, it shows as if the device is empty, even though it had some accounts.

**Info:**

-   Mobile Suite Version: version/commit
-   OS: Android

**How to reproduce**
It is not really 100% reproducible but it is tied with timing and more easy to reproduce on BTC only FW 
(according to @matejkriz )

1. Connect your device
1. Wait for the discovery and enable view only wallet
1. Kill the app 
1. disconnect trezor
1. start the app again
1. App is showing device connected but says "Your wallet is empty"

**Expected behavior**
Your wallet with your accounts is shown/loaded

**Screenshots**

https://github.com/user-attachments/assets/0d9116fa-3a2b-41b3-ac14-0bdcd8601774

**Comment by matejkriz** [comment]
Notes for QA @STew790 : 
Please test multiple times and try killing the app as soon after turning on view-only as possible...

**Comment by matejkriz** [comment]
will be released in 24.7.3

**Comment by STew790** [comment]
**QA OK**
I couldn't replicate this on 24.7.3

**Info:**
24.7.3  1aefc81
