### ISSUE TITLE
Exchange rates possibly unavailable when using a vpn and/or builtin tor service

### ISSUE THREAD

**Issue by BartAgterbosch** [trezor/trezor-suite#13497]
As the title says essentially, from what I can tell trezor suite pulls the fiat exchange rates from coingecko, however lately it has becoming more and more common that exchange rates cannot be retrieved in the trezor suite.

I tend to always have a vpn on at all times, and have the builtin tor service turned off, now I noticed that whenever it says it cannot retrieve the exchange rates (which isn't always but these days most of the time) I also happen to be thrown a captcha when going to coingecko.com.
So I decided to enable builtin tor service to see if it would make a difference if I had my vpn turned off, and lo and behold, again exchange rates cannot be retrieved, so I disabled the builtin tor service AND vpn service, and voila, exchange rates appear.

I have a suspicion that it's coingecko that is blocking the requests, which makes me feel like there should be a fallback for exchange rates if there isn't one already (coinmarketcap maybe?).

For me personally an easy solution would be to just turn everything off, vpn and tor service, but for some people that live in places in the world where they are forced to hide the fact they even own a trezor, this would not be an option, not that they couldn't just check the value outside of the trezor suite, but still..

I am on the latest version of the trezor suite for desktop, using Windows 10 22h2

**Comment by MiroslavProchazka** [comment]
Hello, 

thank you for reporting. We've tried several times on latest release, without any luck to replicate this issue. For most of networks we use our own blockbook servers for fetching rates, additionally coingecko as a fallback. As of now we do not plan to add additional exchanges/sources of fiat rates. 
Thank you.

**Comment by BartAgterbosch** [comment]
![Schermopname (330)](https://github.com/user-attachments/assets/d191f8ba-a015-4636-a35e-df170e780af4)
![Schermopname (331)](https://github.com/user-attachments/assets/dff76da0-3254-47ea-a69a-0215685825fc)
![Schermopname (332)](https://github.com/user-attachments/assets/0f8cca37-3b5e-43ce-869c-6604d3635c7b)
It doesn't always happen, but for example it is happening right now with nordvpn turned on, whereas with coinmarketcap right now it does not.
Coingecko doesn't seem to blanketban vpn's so you can switch servers if this happens (or just complete the recaptcha in a browser first), but when it does this with inbuilt tor it is a lot more of a hassle
I didn't know coingecko was just the fallback, but this always seems to coincide, could it be then that whenever this happens your own blockbook servers are unreachable?
