### ISSUE TITLE
Change window title in electron

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1349]
<img width="373" alt="Screenshot 2020-03-20 at 11 15 55" src="https://user-images.githubusercontent.com/6961901/77154547-341d4f80-6a9c-11ea-9e78-dc96b1b05b0b.png">

For the web version we are changing the tab title based on the suite app user is in.
IMO in the desktop app it is weird and the title should stay static (just show "Trezor Suite"). What do you think?

@matejzak @petrsulc

**Comment by glacierbits** [comment]
@slowbackspace Agree, pls proceed.
