### ISSUE TITLE
Amount in Send form not reseted after you change token or from/to Eth

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13494]
**Describe the bug**
Amount in send form not reseted after you change token or from/to Eth

**Steps to reproduce:**
1. Navigate  to send form of account that contain Eth and some Erc20 tokens
2. Click on send max after selecting token or enter amount higher than Eth amount in account
3. Change to different token with lower amount or to Eth or to token with different decimals
4. Observe error

**Info:**
 - Suite version: web 24.8.0 (6cffcc1b53fcb83d0b8b6a89c62788d248199e56)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/user-attachments/assets/d1969995-0ca5-4412-8347-dce5aef74f38)
![image](https://github.com/user-attachments/assets/f7e55495-9502-465c-a0e4-d0981cdb14cc)

https://github.com/user-attachments/assets/66948242-8f63-42eb-8fb0-dd79869290fb

**Comment by tomasklim** [comment]
Should also reset `Send max` button

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 25.1.0 (7daeb57b631e7e306bc3282476941420944bfeda)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3B1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
