### ISSUE TITLE
Signing windows build

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1350]
related task: https://github.com/trezor/trezor-suite/issues/1323 (not sure if it is the same process)
![image](https://user-images.githubusercontent.com/6961901/77154752-98401380-6a9c-11ea-96d5-b262f9ed0080.png)
![image](https://user-images.githubusercontent.com/6961901/77449635-77582500-6df2-11ea-87a7-2ee352fa7e69.png)

**Comment by keraf** [comment]
~~Windows builds are also now signed!~~

Edit: I thought they were but apparently not. Sorry for the confusion.

**Comment by tsusanka** [comment]
This should be done but we need to test it. @prusnak will push into `codesign` branch when we create the `release/2020-10` branch. QA will test it then. I think we close this issue unless @keraf thinks otherwise.

**Comment by sorooris** [comment]
**QA OK**

Installation wasn't blocked on my machine, I've instructed @wendys-cats and @bosomt to verify this issue as well - I'll move it to Approved after they confirm QA OK.

> Suite: app 20.10.1 a263552
> OS: Windows 10
> Device: model T 2.3.4 50854b921

**Comment by tsusanka** [comment]
Wait that is weird because the builds were not signed yet (due to the mac runner also for windows :( ). So your system probably got some exception?

**Comment by bosomt** [comment]
**QA OK**

Windows 10
Suite commit a26355244abe0850d23e6c353b5e157f44f12694

**Comment by zmluvny-jednorozec** [comment]
**QA OK**

Windows 10 Home 19041.508
Suite Type: app 20.10.1 a26355244abe0850d23e6c353b5e157f44f12694
Device TT 2.3.4 50854b921

Windows Defender flagged it in my system and asked if I want to run it (BUT my settings are to ask about any change before).

**Comment by sorooris** [comment]
@tsusanka what do we do?

what about this? https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by tsusanka** [comment]
> Windows Defender flagged it in my system

I think this should not happen in case the app is signed. Let's discuss this after it is signed.

**Comment by prusnak** [comment]
I tested the non-signed binary yesterday on my Windows 10 machine and oddly enough, there were no extra dialog screens. It started right away without any questions. :shrug:

**Comment by wendys-cats** [comment]
> > Windows Defender flagged it in my system
> 
> I think this should not happen in case the app is signed. Let's discuss this after it is signed.

Actually, I think it should happen in my particular case even if the app is signed, my settings are specifically set to ask about any potential system change and/or permissions. But we can when the app is signed with and without these settings and find out.

**Comment by tsusanka** [comment]
Please test again with latest signed binaries sent via Slack.

**Comment by bosomt** [comment]
@tsusanka no threats found /binary and installer were tested/

**Comment by sorooris** [comment]
**QA OK**

Neither threats detected nor any prompts displayed on my system during app installation and running the app.

Suite Version: app, commit e6ba320
OS: Windows 10, 19041.508
Firmware Version: N/A

**Comment by wendys-cats** [comment]
**QA OK**

**OS** Windows 10 Home 19041.1508
**Suite** Type APP Commit e6ba320
**Device** TT 2.3.4. 50854b921

Tested with my paranoid settings - system asked if I really want to make the change (expected) and installed the app without problems. 
Changed the system settings to standard and no prompts nor threats appeared during app installation.
