### ISSUE TITLE
Icons for hide/unhide token don't look great

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#13503]
**Describe the bug**

There are currently two icons when working with tokens visibility.

First one is in the dropdown and looks the same for hide and unhide action.

Second one is in the button for unhide inside hidden tokens section.

**How to reproduce**

1. Go to account with some tokens
1. Click on tokens tab
1. Click on three dots button or go to hidden section
1. See icons

**Expected behavior**
One icon for hide and one icon for unhide that matches the action type.

**Screenshots**
![Screenshot 2024-07-25 at 11 27 54 AM](https://github.com/user-attachments/assets/5d01301c-d664-4f25-892d-043e4832283f)
![Screenshot 2024-07-25 at 11 27 45 AM](https://github.com/user-attachments/assets/d6b02317-9352-46c4-8d1c-720f90d9eafc)

**Comment by MiroslavProchazka** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/13827
