### ISSUE TITLE
Loading content visuals are not consistent

### ISSUE THREAD

**Issue by seibei-iguchi** [trezor/trezor-suite#13508]
The spinner component has an end animation for both success and error states which is not used in various context where a different solution is implemented instead. It should look and work the same everywhere.

**Comment by bosomt** [comment]
**QA OK**


very nice !

**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
