### ISSUE TITLE
Invalid URL gets detected as a link and is blurred in token name

### ISSUE THREAD

**Issue by domve** [trezor/trezor-suite#13528]
**Describe the bug**
If a user receives an Ethereum token where the token's name includes a string such as `2.0`, Trezor Suite mistakenly detects it as a valid link and incorrectly blurs it for phishing protection.

**Info:**
- Suite Version: desktop 24.7.2 (3282fe8)
- OS: Linux x86_64 

**How to reproduce**

1. Create an Ethereum account
2. Receive Lido Staked Ether (stETH) tokens
3. Navigate to tokens page
4. Observe token name being partially blurred

**Expected behavior**
`2.0` and other invalid URLs should not be detected as links, and should not be blurred in the tokens page.

**Screenshots**
![Screenshot from 2024-07-28 15-21-54](https://github.com/user-attachments/assets/17c78c18-e090-4577-900c-da479b916f9a)
![Screenshot from 2024-07-28 15-21-44](https://github.com/user-attachments/assets/61071dc1-c386-42ee-a079-ebfa0b07bd3f)

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/user-attachments/assets/cd4b0437-aefb-4c61-bed7-a64d6ea2cf2e)

**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
