### ISSUE TITLE
Disable “Bump Fee” for txs with higher nonce than the lowest pending

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13529]
Users are currently experiencing difficulty determining which transaction to bump to ensure it gets confirmed. The current system can lead to confusion, as bumping the oldest transaction with a small fee may still not result in confirmation due the a fact that oldest tx (time) may not have lowest nonce (was already bumped once)

Solution to address this issue:

1.	Disable “Bump Fee” for txs with higher nonce: Only the bump button for the transaction with the lowest nonce should remain enabled. This will guide users to prioritize the oldest transaction first.
2.	Add Tooltips to Disabled Buttons: Implement tooltips on disabled buttons indicating that the user must first bump the fee for the transaction with the lowest nonce. This tooltip will provide clarity on the required action.

Possible downsides:
1. In case user has all txs underprices, he has to wait for the oldest one to get confirmed to bump the rest. If that is problematic, we can introduce modal or add nonce to pending tx 

![Screenshot 2024-07-28 at 20 53 13](https://github.com/user-attachments/assets/a04b3345-c638-44e2-898b-77f2ecb3a749)

Please take in mind also this change which can make it even more confusing https://github.com/trezor/trezor-suite/pull/12975

**Comment by Lemonexe** [comment]
If I understand correctly, this is only for ethereum-type networks, right?

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/6d5bb9b2-56ee-4adc-ba15-decb0f19acb7)

**Info:**
 - Suite version: desktop 24.10.0 (0c147a1d37dc615e286a114d90bc8b637bbb929f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
