### ISSUE TITLE
Hide default wallet loading setting if passphrase is off

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#13522]
**Describe the bug**
The Default wallet loading option should not be shown in Settings > Device if Passphrase is off, as it doesn't make sense offering default loading for something that is disabled. Please remove the Default wallet loading setting if Passphrase is off.

**Info:**

-   Suite Version: 24.7

**How to reproduce**

1. Launch Suite 24.6 or older
2. Connect Trezor
3. Go to Settings > Device > Passphrase and turn it off
4. Close Suite 24.6 or older
5. Launch Suite 24.7
6. Connect the same Trezor
7. Go to Settings > Device > observe the combination of Passphrase off and Default wallet loading present

**Expected behavior**
- If passphrase is off, DON'T show Default wallet loading setting.
- If passphrase is on, DO show Default wallet loading setting. (that is ok now)

**Screenshots**

![Image](https://github.com/user-attachments/assets/4e7b8ae2-acf6-4485-a74d-09149cd9aafb)

**Comment by bosomt** [comment]
**QA OK**

default wallet loading switcher not available when passphrase is disabled /via `trezorctl set passphrase off`

**Info:**
 - Suite version: web 24.8.0 (305ddea867653c5c8808d14860159a3132e8de03)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.32
