### ISSUE TITLE
Display Settings on mobile without necessity of scrolling

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#13536]
**initial scroll:**
![image](https://github.com/user-attachments/assets/953d248a-9831-4042-b3d6-4c99d24fb9d4)

**after scroll down:**
![image](https://github.com/user-attachments/assets/623021b0-ec59-4eb0-91a6-d385fce25da1)

<img width="719" alt="image" src="https://github.com/user-attachments/assets/0edb1c92-b5fc-4aa6-a2e9-393b808e4ec6">

Slack thread: https://satoshilabs.slack.com/archives/C03FL9TCURZ/p1722172647278229

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/user-attachments/assets/f08460a0-57b8-4884-8048-aea688d126f2)

**Info:**
 - Suite version: web 24.9.0 (0fef2eaa780dec66ae8fda74b1111cc8741e550e)
 - Browser: Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36
 - OS: MacIntel
 - Screen: 360x800
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.32
