### ISSUE TITLE
Bump gas price at least by 1 gwei

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13531]
Before the implementation of #13328, the gas price was always increased by at least one gwei compared to the previous transaction. However, after the fix, the bump fee can propose an increase of just 1 wei. To maintain a more consistent fee bump logic, we should ensure that the new gas price is not only adjusted to the current network gas price but also is at least 1 gwei higher than the previous gas price.

<img width="803" alt="Screenshot 2024-07-28 at 20 56 15" src="https://github.com/user-attachments/assets/43e4632c-ca8f-49e1-965d-00a41bfad77f">

It should also fix this warning error (at least 2 gas price)

https://github.com/user-attachments/assets/8ffeeb8b-01f4-4dbd-961b-7f012a14140b

**Comment by enjojoy** [comment]
It already increases the gas by at least 1 gwei. I've also tested it with gas price higher than the proposed network gas and it's increased it by at least 1 gwei. 

The current logic suggests that if the network gas is lower than the previous gas, the new gas will be increased by 1. Since it was already in gwei, it will be increased by 1 gwei.  

```
const getEthereumFeeInfo = (info: FeeInfo, gasPrice: string) => {
    const current = new BigNumber(gasPrice);
    const minFeeFromNetwork = new BigNumber(fromWei(info.levels[0].feePerUnit, 'gwei'));

    const getFee = () => {
        if (minFeeFromNetwork.lte(current)) {
            return current.plus(1);
        }

        return minFeeFromNetwork;
    };

    const fee = getFee();

    // increase FeeLevel only if it's lower than predefined
    const levels = getFeeLevels('ethereum', info).map(l => ({
        ...l,
        feePerUnit: fee.toString(),
    }));

    return {
        ...info,
        levels,
        minFee: current.plus(1).toNumber(), // increase required minFee rate
    };
};

```

@tomasklim Please let me know if there is any other case in which the gas price can be increased by less than 1 gwei.  Otherwise I would close the issue.

**Comment by tomasklim** [comment]
Note: The minimum should be configurable because of new L2 chains https://github.com/trezor/trezor-suite/issues/15478

**Comment by tomasklim** [comment]
Then I do not understand this situation. Current develop

![Screenshot 2024-12-07 at 14 33 41](https://github.com/user-attachments/assets/512a13b5-ee1b-4ddc-9416-69f103273339)

**Comment by tomasklim** [comment]
@enjojoy Nobody touched the code from the time this issue was created.

Current develop (I see difference only `0.1`)
![Screenshot 2024-12-07 at 14 33 41](https://github.com/user-attachments/assets/512a13b5-ee1b-4ddc-9416-69f103273339)

it is clear from the code you shared, that it can happen
```
    const getFee = () => {
        if (minFeeFromNetwork.lte(current)) {
            return current.plus(1);
        }

        return minFeeFromNetwork;
    };
```

Situation:
You send tx with gas price 10 `current`
Current network gas price is 10.5 `minFeeFromNetwork`

`minFeeFromNetwork` is `gte` than `current` 

The gas price is set to `10.5`, not to `11` (and as we update fees once per 10 block, it is better to have there a buffer)

It is incremented by `1` only in case the tx fee is higher than current gas price in the network (it can happen as we use legacy fees and also fees in suite can be old)

The inconsistency visible in the video is also still there.
![Screenshot 2024-12-07 at 14 48 17](https://github.com/user-attachments/assets/d9213b82-0d6d-4b34-a037-34e8f8112501)
![Screenshot 2024-12-07 at 14 48 12](https://github.com/user-attachments/assets/a2cd7071-6fca-4af8-a5e2-4604139831ae)

**Comment by enjojoy** [comment]
> @enjojoy Nobody touched the code from the time this issue was created.
> 
> Current develop (I see difference only `0.1`) ![Screenshot 2024-12-07 at 14 33 41](https://private-user-images.githubusercontent.com/33235762/393520225-512a13b5-ee1b-4ddc-9416-69f103273339.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTIyOTksIm5iZiI6MTczMzc1MTk5OSwicGF0aCI6Ii8zMzIzNTc2Mi8zOTM1MjAyMjUtNTEyYTEzYjUtZWUxYi00ZGRjLTk0MTYtNjlmMTAzMjczMzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDEzNDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYjIxYTRkOTIxZGIxN2JiNWU2YmNmZjdhYTU2MzNkYzc3NjIzYTg3ZDNkMDk3Y2Y3YjZiZTk5MmE3MGM3MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mdbb_9Ova88685mp5JrlJPGi6WgIek266YBu2EnX3Eo)
> 
> it is clear from the code you shared, that it can happen
> 
> ```
>     const getFee = () => {
>         if (minFeeFromNetwork.lte(current)) {
>             return current.plus(1);
>         }
> 
>         return minFeeFromNetwork;
>     };
> ```
> 
> Situation: You send tx with gas price 10 `current` Current network gas price is 10.5 `minFeeFromNetwork`
> 
> `minFeeFromNetwork` is `gte` than `current`
> 
> The gas price is set to `10.5`, not to `11` (and as we update fees once per 10 block, it is better to have there a buffer)
> 
> It is incremented by `1` only in case the tx fee is higher than current gas price in the network (it can happen as we use legacy fees and also fees in suite can be old)
> 
> The inconsistency visible in the video is also still there. ![Screenshot 2024-12-07 at 14 48 17](https://private-user-images.githubusercontent.com/33235762/393521002-d9213b82-0d6d-4b34-a037-34e8f8112501.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTIyOTksIm5iZiI6MTczMzc1MTk5OSwicGF0aCI6Ii8zMzIzNTc2Mi8zOTM1MjEwMDItZDkyMTNiODItMGQ2ZC00YjM0LWEwMzctMzRlOGY4MTEyNTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDEzNDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYTIxZWRmZWJmYTUxMzc2MjRmNTE4NmE2MjA4MDdjM2MxYTgwZDFlM2E3Yjg2M2E4ZmVkMTAxZTY0NzZkNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IaTJXWXGYcaxrmxT01bmZtih25AE15zDnuJMg4RiF-Q) ![Screenshot 2024-12-07 at 14 48 12](https://private-user-images.githubusercontent.com/33235762/393521010-a2cd7071-6fca-4af8-a5e2-4604139831ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTIyOTksIm5iZiI6MTczMzc1MTk5OSwicGF0aCI6Ii8zMzIzNTc2Mi8zOTM1MjEwMTAtYTJjZDcwNzEtNmZjYS00YWY4LWE1ZTItNDYwNDEzOTgzMWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDEzNDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYWIyNDZhYjhlMDg1MTliMzE5MzNiZGFhZTk1Y2YyYmI0ODI3YmY0ZjRiNzkzY2NkZTg3MmU1ZmQxZmI4NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jWBu7_kFEqCgw4n7SrGth_Ma4P_iPnvxMPld6fDKVDw)

Got it 🙏🏻 Thank you. Didn't realize that the difference with the network proposed fee can be less that 1 gwei and then it's problematic. Usually the fees are pretty high.

**Comment by bosomt** [comment]
**QA OK**



**Info:**
 - Suite version: desktop 25.1.0 (0b116799334cb4a05fcb59cc480deb7c4b9a63e9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e196413bb745443610211c325623ba7cee7309e9)
 - Transport: BridgeTransport 2.0.33
