### ISSUE TITLE
Solana Token2022

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13538]
**Token2022 overview**

**Suite:**

- tokens are not visible (e.g. `$CWIF`)
- transactions including Token2022 are `Unknown transaction`

**Third-party wallet:**
- Nufi and Backpack ok
- tokens are visible
- device is able to sign transactions with Token2022. It just says `Transaction contains unknown instructions`

**Device:**
- resolve `Transaction contains unknown instructions`

**Comment by bosomt** [comment]
**QA OK**

https://www.notion.so/satoshilabs/Solana-Token2022-15adc5260606800aaa2ef036aebd9a3f?pvs=4

**Info:**
 - Suite version: web 25.1.0 (0056b217a594e1ce57edbee60a493326503e5788)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e196413bb745443610211c325623ba7cee7309e9)
 - Transport: BridgeTransport 2.0.33
