### ISSUE TITLE
Warn users when using custom fee

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13530]
Users modify custom fee to save money and then their tx is stuck.

<img width="767" alt="Screenshot 2024-07-29 at 21 26 05" src="https://github.com/user-attachments/assets/673790bf-9fd6-49c1-b8a9-b3f04b8f6e5e">

Let's introduce warning above inputs for all coins similar to the one in Safety checks modal

![Screenshot 2024-07-28 at 21 12 55](https://github.com/user-attachments/assets/860f6207-8743-4a04-813a-f8843c18f5f9)

**Comment by Hannsek** [comment]
Is this really needed?

If yes, we should have it for every coin.

**Comment by tomasklim** [comment]
According to support, people are changing fee to the lowest possible and their tx becomes stuck

It can be bumped of course but 🤷‍♂️  this is easy task

**Comment by Hannsek** [comment]
Ahh, yeah, forgot about this perspective. Then let's do it. But again, as I said, for every coin.

**Comment by enjojoy** [comment]
Do we want the warning to be displayed there constantly, or only if the user tries to change the gas fee/type something in the field? @tomasklim 

UPD: constantly

**Comment by bosomt** [comment]
**QA OK**

when selecting custom fee you see this banner/warning
`Setting a low fee may result in transaction failure or significant delays. Learn more`


**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
