### ISSUE TITLE
Coin Enabling - implement settings screen update logic

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13547]
- [x] When leaving screen (back press or swipe) run discovery for enabled networks
- [x] disabled coin accounts are removed from current and view only devices

**Comment by vytick** [comment]
blocked by #13486

**Comment by STew790** [comment]
**QA OK**
- disabled coins are removed (even from portfolio)
- after enabling a coin and going back to home/assets a discovery starts for enabled coins

**Info**
24.8.1  f2f56aa
