### ISSUE TITLE
Include bridge switcher in troubleshooting steps when T1 HID device is connected

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#13567]
https://github.com/trezor/trezor-suite/pull/13561#issuecomment-2258603925

**Comment by mroz22** [comment]
should be there already

**Comment by bosomt** [comment]
**QA OK**

link to KB and bridge switch works as expected

<img width="618" alt="Image" src="https://github.com/user-attachments/assets/7413811a-bf3f-4875-a517-93d7737f3e03" />

**Info:**
 - Suite version: desktop 25.1.0 (0f8a86379bcb00bce86b888c3f43458e01da19f3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.2.0 regular (revision df524b9f35fd5cdba14eaa2bf2d948e3dc75254a)
 - Transport: BridgeTransport 2.0.33
