### ISSUE TITLE
Modal refactor/redesign

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1357]
ala discord.
3 parts
- header (title, close button) (fixed at the top)
- scrollable content
- action buttons (fixed at the bottom)

**Comment by glacierbits** [comment]
Examples [Search](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5e79c9b18b52437106eabf61) and [Tx Details](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5e81ab421cdef0701767390c)
