### ISSUE TITLE
suite-desktop debug: bridge running switch

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#13587]
1. start suite-desktop with bundled bridge
1. turn off bundled bridge in debug settings
1. try to turn on bundled bridge in debug settings - checkbox does not react
2. transport is however started and TRANSPORT_START event emitted 

<img width="1173" alt="image" src="https://github.com/user-attachments/assets/d50ba0a4-fbbd-4999-a982-1134dd5e2882">
<img width="753" alt="image" src="https://github.com/user-attachments/assets/69256810-0b89-401a-813b-1c4e940caaff">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.10.0 (3e1d4dff6ceb7a96cff59c4d15d223b0802366ca)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.0
