### ISSUE TITLE
Homescreen button in settings responsive design

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13583]
**Describe the bug**
Homescreen button responsive design

**Steps to reproduce:**
1. Navigate to `settings/device/Customization/Homescreen`
2. Reduce responsive screen size
3. Observe button

**Info:**
 - Suite version: web 24.8.0 (a4a196fac842336986acdb51fc48c072a9217888)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.1 regular (revision 55473a0b4be7b22317cd0c401c938d430d86f29f)
 - Transport: BridgeTransport 2.0.33
A clear and concise description of what actually happens.

**Screenshots:**
![image](https://github.com/user-attachments/assets/adb57682-1847-437c-9b4e-b1adbe54d235)

https://github.com/user-attachments/assets/9e669656-588e-4ea9-9061-93e7b2959557

**Comment by bosomt** [comment]
same for `Show full address` button

 
![image](https://github.com/user-attachments/assets/296deb8e-1654-4fb9-a954-59d3aabb4854)

**Comment by Lemonexe** [comment]
`Show full address` Button was confirmed to be working correctly; probably someone fixed it in the meantime.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.9.0 (6d647cf2c218b432a970a7ca830f3fa2e8673b60)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.32
