### ISSUE TITLE
Device switcher visual glitch

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13599]
Top offset of opened device switcher is too big. Easy to spot on iOS devices.

The issue probably is extra top padding added to mitigate ` statusBarTranslucent={true}` on android devices here:
https://github.com/trezor/trezor-suite/blob/bbcb365ee8778364a435c5f7a5f35411cb175640/suite-native/device-manager/src/components/DeviceManagerModal.tsx#L36

Resolve this issue so it works nicer on both platforms.

<img src="https://github.com/user-attachments/assets/707d4879-ab3b-4c3d-a6b0-c8118076a026" width=350 />

**Comment by STew790** [comment]
**QA OK**
The padding is correct.
**Info:**

24.8.0 e86c3fe
