### ISSUE TITLE
Mobile offline state

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13597]
Show banner, that the app is offline

___
### [Design here](https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?node-id=259-2068&t=gZI3UoFGeSkVq5WN-11)

**Comment by STew790** [comment]
**QA OK**
A yellow banner showing user that they are offline is shown

**Info:**

24.8.0.  5cd19fd

**Comment by vytick** [comment]
@STew790 Please retest after latest update

**Comment by vytick** [comment]
actually wait a bit. I'll do one more check

**Comment by vytick** [comment]
No need to test now. I'll have to make a change. Sorry for ping

**Comment by vytick** [comment]
@STew790 please check now
