### ISSUE TITLE
Duplicated minimum amount to stake ETH in codebase

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13594]
We are using two variables for minimum staking amount `0.1`: `MIN_ETH_AMOUNT_FOR_STAKING` and `MIN_AMOUNT` in `stake` method in `stake.ts` file.

Let's unify it to use just one `MIN_ETH_AMOUNT_FOR_STAKING`.

Also modify error 
```
throw new Error(`Min Amount ${MIN_AMOUNT} wei`); 
``` 
to throw it in `ETH` not in `wei`

**Comment by bosomt** [comment]
**QA OK**

stake minimum 0.1 works as expected on ETH and THOL


**Info:**
 - Suite version: web 24.9.0 (244b9d62f86d9de0a6ccfd7affb4039c1a0ad16f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.2 regular (revision null)
 - Transport: BridgeTransport 2.0.32
