### ISSUE TITLE
Remove network send warning when staking/unstaking/claiming

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13600]
Please do not show this warning in transaction review modal when staking/unstaking/claiming

![Image](https://github.com/user-attachments/assets/6d4afdb1-0e06-4f25-bbfc-34a3fe575ed5)

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/user-attachments/assets/fb5a189c-b239-41a1-bfe2-d751e682ee1f)

**Info:**
 - Suite version: web 24.9.0 (244b9d62f86d9de0a6ccfd7affb4039c1a0ad16f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.2 regular (revision null)
 - Transport: BridgeTransport 2.0.32
