### ISSUE TITLE
Add tokens rates for tokens added on ACCOUNT.UPDATE

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1360]
leftover from https://github.com/trezor/trezor-suite/pull/1055
just leaving some work for future generations
(inside fiatRatesMiddleware, figure out how to find out IF new tokens were added and only THEN fetch rates)

**Comment by bosomt** [comment]
before and after transaction to suite

![image](https://user-images.githubusercontent.com/31506317/81704074-b52a0f00-946d-11ea-8a46-bedbecf1777b.png)

![image](https://user-images.githubusercontent.com/31506317/81704571-426d6380-946e-11ea-8af7-9040bfc8606e.png)

**Comment by sorooris** [comment]
@slowbackspace 
is the red-marked area the rates that are supposed to be displayed?
![image](https://user-images.githubusercontent.com/10185314/81706061-1226c480-9470-11ea-8d94-2346f323c173.png)

**Comment by slowbackspace** [comment]
@sorooris yup!
I already told @bosomt  how to test it, but I'll write it again.
1. you need to make sure that the token is not already somewhere in suite (different wallet/account) otherwise rates are already downloaded and will be reused.
2. open suite and keep it open
2. after the discovery process send a token to the suite account and wait for tx confirmation
3. token should appear in token list along with its fiat rate.

**Comment by bosomt** [comment]
![image](https://user-images.githubusercontent.com/31506317/81818366-3c3ebc00-952e-11ea-984d-3d15e424656c.png)

![image](https://user-images.githubusercontent.com/31506317/81818407-4a8cd800-952e-11ea-8b97-35c1a136bd36.png)
