### ISSUE TITLE
Symbol wrapping

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13603]
**Describe the bug**
Coin/Token symbol should not be wrapped in the middle of word

**Expected behavior**

<img width="242" alt="Screenshot 2024-08-02 at 11 00 40" src="https://github.com/user-attachments/assets/75d8cc23-5d31-42ed-9e6f-19e901091895">

**Screenshots now**
This is an example from tx review modal but I think that it can occur everywhere, so it would be fine to fix it in some global component

<img width="248" alt="Screenshot 2024-08-02 at 10 19 09" src="https://github.com/user-attachments/assets/fb1f9875-74e4-4fe3-87ac-d7192aa69548">
<img width="256" alt="Screenshot 2024-08-02 at 10 18 26" src="https://github.com/user-attachments/assets/95ac9f88-aa05-44b3-96e2-b50097ac133c">
<img width="238" alt="Screenshot 2024-08-02 at 10 16 17" src="https://github.com/user-attachments/assets/b0fa2bf6-28f1-434f-b9f5-cc7e2bed3dfe">
<img width="306" alt="Screenshot 2024-08-02 at 9 55 06" src="https://github.com/user-attachments/assets/342adc93-f709-461c-a5b8-3bd1e89804c6">

**Comment by bosomt** [comment]
There is some strange `.` artefact after coin name when signing tx.
Can this be related ? Coin/token name is not wrapped anymore 

**Info:**
 - Suite version: desktop 24.10.0 (03347b5e28587e194525d937b7943bc9836db435)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33

![Image](https://github.com/user-attachments/assets/c420b4db-1254-4d1f-9a47-75f4cf9b5eea)
![Image](https://github.com/user-attachments/assets/78af30aa-65c4-4f8f-9b5e-62e0520f4c20)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.10.0 (53303523db1a941907766902bcf79b3f320b4dd2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
