### ISSUE TITLE
Stake any amount promotion in ETH account

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13611]
Fix `any amount` in ETH promotion banner on eth dashboard acc

**Comment by bosomt** [comment]
**QA NOK**

`Stake any amount and watch that sweet ETH roll in. With our current APY rate of 3.79%, your rewards earn too`

same in dev version

<img width="645" alt="image" src="https://github.com/user-attachments/assets/7a8e2022-db74-455c-990f-2fff2998f65e">


**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Comment by MiroslavProchazka** [comment]
Should be solved after merge of https://github.com/trezor/trezor-suite/pull/13707

**Comment by bosomt** [comment]
**QA OK**

checked at develop
`Stake a minimum amount of 0.1 ETH and start earning rewards. With our current APY rate of 3.78%, your rewards earn too`

**Info:**
 - Suite version: web 24.9.0 (808c28ba480a9614eba7f28ee2a37aa5dc147fa8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
