### ISSUE TITLE
Settings overflows on small screens

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13628]
**Describe the bug**
In case of small screen and big sidebar, Settings General and Device does not fit the screen

**Info:**

-   Suite Version: 24.8.0

**How to reproduce**

1. Be big sidebarphile or smallscreenphile

**Expected behavior**
App does not overflow

**Screenshots**

https://github.com/user-attachments/assets/70a1ad84-bc9e-452d-b44a-f0bcfcf8a74b

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.12.0 (4258d1c3c5bfcc405e73e48ea633f0bdf62f4d80)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport
