### ISSUE TITLE
@component ButtonGroup should have same height for all buttons

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13629]
**Describe the bug**
I would expect that each button have height based on the "biggest" button

**Screenshots**
<img width="578" alt="Screenshot 2024-08-02 at 20 41 31" src="https://github.com/user-attachments/assets/89979074-c557-4447-8377-e37bd27e9950">

**Comment by MiroslavProchazka** [comment]
@jvaclavik can we fix this until the EAP 24.8 release, please?

**Comment by MiroslavProchazka** [comment]
Should be fixed already in develop
