### ISSUE TITLE
Network/Token icon

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13630]
Prerequisite https://github.com/trezor/trezor-suite/pull/12694

**Description:**
Create component to show icon/logo of an asset.
Create another component which will add ring around the asset. This ring should have part filled using dominant color of the icon.

<img width="69" alt="Screenshot 2024-08-02 at 22 25 38" src="https://github.com/user-attachments/assets/2f645b21-6ab4-4379-a64d-7fe02fa93e31">

In case file is not available, show first letter

<img width="66" alt="Screenshot 2024-08-02 at 22 26 58" src="https://github.com/user-attachments/assets/36e0fde5-cc2e-43e2-9c10-a5509c4d1ff4">

In case file nor text are available, show `?` instead of the letters.

_____ 
**Files:**

Assets which we have as a network are available offline in `packages/components/src/images/coins`
- naming: 
  - `[network].svg`
  - as it is svg, it can be scaled to whatever sizes

Assets available on `data.trezor.io`
- naming: 
  - in case of network `[coingecko_id].webp`
  - in case of token `[coingecko_id]--[contract_address].webp`
- icon display size: `24x24` 
- available sizes: 
  - `24x24` 
    - https://data.trezor.io/suite/icons/coins/bitcoin.webp
  - `48x48` 
    - `@2x` add to the name of file: `[platform]--[contract_address]@2x.webp`
    - https://data.trezor.io/suite/icons/coins/bitcoin@2x.webp

> https://github.com/trezor/trezor-suite/pull/13768 there is change from `_` separator to `--`

<img width="465" alt="354698861-f7c9acbe-da6e-443c-b8e7-35af38ec9964" src="https://github.com/user-attachments/assets/931734e4-8b44-4af4-9bbb-f66a4e2ab973">

_____
**Beware of:**
- `networkSymbol` !== `coingecko_id`
  - `coingecko_id` is available in `networksConfig.ts` for each network except testnets
- to find out how `@2x` should be used, visit `Image.tsx`
- offline icon is preferred (just for networks) (those can have bigger size if we need it, please decide)
- in case network is `ada` please try fetch 2 urls, see `buildCoinUrls` in `coingecko.ts`
```
    if (ticker.symbol === 'ada') {
        const { policyId } = parseAsset(contract_address);

        return [`cardano_{policyId}`, `cardano_{contract_address}`];
    }
```

______
**Api:**
```tsx
// CoinLogo (can be deprecated in the future because we will have AssetLogo)
// ------------------------------------------
// we already use this component

type CoinLogoProps = {
  size: number; // can be any, we have it as SVG
  symbol: NetworkSymbol;
}

<CoinLogo symbol="btc" size={30} />

// AssetLogo 
// ------------------------------------------
// new component for rendering token logo
// icon is fetched from API 

type AssetLogoProps = {
  size: 20 | 24; // + inner implementation for @2x (srcSet on img)
  coingeckoId: string; // this is coingecko id, we can maybe also provide symbol and do translation inside?
  contractAddress?: string; 
  shouldTryToFetch?: boolean; // (by default true) we know that some images are not available
  placeholder: string; // letters when unavailable
}

<AssetLogo 
  coingeckoId="binance-smart-chain" 
  contractAddress="0x0203d275d2a65030889af45ed91d472be3948b92"
  size={24} 
  shouldTryToFetch={true} 
  placeholder="CATWIFHAT"
/>


// ShareIndicator
// ------------------------------------------
// - uses coin/token logos icons independently

type ShareIndicatorProps = {
  percentageShare: number; // 0-100
  image: ReactNode;
}

// ShareIndicator using coin logo
<ShareIndicator 
  percentageShare={90}
  image={<CoinLogo 
    symbol="btc" 
    size={30}
  />}
/>

// ShareIndicator using asset logo
<ShareIndicator 
  percentageShare={90}
  image={<AssetLogo 
      coingeckoId="binance-smart-chain" 
      symbol //
      contractAddress="0x0203d275d2a65030889af45ed91d472be3948b92"
      size={24} 
      shouldTryToFetch={true} 
      placeholder="CATWIFHAT"
  />}
/>
```

**Comment by ffrediani** [comment]
Is the download of the main token images still a prerequisite to be done ?
I see there is a pending pull request, but it seems there are issues within it ? Does that make it is still a work in progress and may not come up in the next versions to come soon ?

**Comment by tomasklim** [comment]
```
type AssetLogoSize = 20 | 24

// CoinLogo (can be deprecated in the future because we will have AssetLogo)
// ------------------------------------------
// we already use this component

type CoinLogoProps = {
  size: number; // can we any, we have it as SVG
  symbol: NetworkSymbol;
}

<CoinLogo symbol="btc" size={30} />

// TokenLogo 
// ------------------------------------------
// new component for rendering token logo
// icon is fetched from API 

type AssetLogoProps = {
  size: AssetLogoSize; // + inner implementation for @2x (srcSet on img)
  assetId: string; // not 100% sure about this format
}

<AssetLogo 
  assetId="binance-smart-chain--0x0203d275d2a65030889af45ed91d472be3948b92" 
  size={24} 
/>


// ShareIndicator
// ------------------------------------------
// - uses coin/token logos icons independently

type ShareIndicatorProps = {
  percentageShare: number; // 0-100
  image: ReactNode;
}

// ShareIndicator using coin logo
<ShareIndicator 
  percentageShare={90}
  image={<CoinLogo 
    symbol="btc" 
    size={30}
  />}
/>

// ShareIndicator using asset logo
<ShareIndicator 
  percentageShare={90}
  image={<AssetLogo 
    assetId="binance-smart-chain--0x0203d275d2a65030889af45ed91d472be3948b92" 
    size={24} 
  />}
/>
```

**Comment by ffrediani** [comment]
I can't see any token icons (ex: WBTC) inside Ethereum Coins tab in Trezor Suite. What happened ?

**Comment by Hannsek** [comment]
It is not released yet.

**Comment by ffrediani** [comment]
@Hannsek would share when will that become visible on Trezor Suite ?

**Comment by Hannsek** [comment]
It should be out next release - in 2 weeks. cc @MiroslavProchazka
