### ISSUE TITLE
connect-explorer - getAccountInfo - dead chains 

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#13638]
capricoin, komodo, I would simply remove it

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/ff62bd82-e69c-46fb-8ca5-f772f111c81b">

**Comment by evgenysl** [comment]
**QA OK**
Namecoin, Vertcoin, Komodo, Capriporn removed

![Screenshot 2024-08-23 at 20 29 18](https://github.com/user-attachments/assets/05cfcd6d-30fb-4067-b87f-2ccccdc3c300)
