### ISSUE TITLE
Exception page design/copy

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1363]
![IMAGE 2020-03-24 11:36:40](https://user-images.githubusercontent.com/6961901/77416082-bae76a80-6dc3-11ea-9613-1adae4d2cc9f.jpg)

**Comment by szymonlesisz** [comment]
related to https://github.com/trezor/trezor-suite/issues/1103#issuecomment-596399006

**Comment by glacierbits** [comment]
Duplicity. Being handled by #1103 
Currently in the design process.
