### ISSUE TITLE
Redesign modals

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#13650]
https://www.notion.so/satoshilabs/Dropdown-Modal-f41806296601449195ee5e6e267238d7?pvs=4

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.9.0 (59c92533990756c8ab1d4f54537f94b9148c7b25)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.2 regular (revision null)
 - Transport: BridgeTransport 2.0.32
