### ISSUE TITLE
Send form: send max + Not enough funds error

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1365]
coin: Testnet
1. set "send max"
2. open advanced, set custom fee, make it higher
3. got "Not enough funds" error but i would expect that "max" will be recalculated with given fee

update:
generally after this operation "fee form" is broken, custom fee field is gone, fee select doesnt react properly

**Comment by martinboehm** [comment]
This might be related: ETH account, I used "send max", sent the suggested value but some dust remained on the account.

**Comment by bosomt** [comment]
im not sure, is this proper behavior ? 
https://www.youtube.com/watch?v=WHSQ6haFHj8&feature=youtu.be

**Comment by vladimirvolek** [comment]
This is the correct issue https://github.com/trezor/trezor-suite/issues/1795
