### ISSUE TITLE
Send form: Review tx modal,

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1366]
disable possibility to quickly click into "Confirm transaction" button which will throw error "device call in progress" to toast notification

**Comment by wendys-cats** [comment]
Issue: Device call in progress

Steps to reproduce:
1. set the connection to Slow 3G in browser 
2. fill the Send form
3. Click on Review transaction
4. Click on Confirm transaction button

Expected:
Clicking on Confirm transaction button is not possible while device is not ready to do it.

Actual:
You can click on Confirm transaction button. The action will result in "Sign transaction error: Device call in progress" notification. 

Video: https://drive.google.com/file/d/1qFNojfi0ZcQ4ojtnhaOK5V2zS-oJt6xw/view

![device call in progress 1366](https://user-images.githubusercontent.com/58593111/78566453-85a93680-781f-11ea-9078-2ff7ec4f0cff.png)

**Comment by bosomt** [comment]
same behavior in verify address dialogue.
i don't know if this is a issue or not ;) 

![image](https://user-images.githubusercontent.com/31506317/80489380-07dcd480-8960-11ea-9e43-0fae254940ee.png)

**Comment by bosomt** [comment]
but i think it's same problem, you can press address in suite many time when you have slow internet,
is there way to lock this requests ? or at lease add some 2sec timeout ?

**Comment by bosomt** [comment]
looks like this https://www.youtube.com/watch?v=dwZdKpzJDWw&feature=youtu.be

**Comment by wendys-cats** [comment]
**Issue: Edit available after confirm** 

**Steps to reproduce:**
**1.** set the connection to Slow 3G in browser
**2.** fill the Send form
**3.** Click on Review transaction
**4.** Click on Confirm transaction button
**5.** Click on Edit (exit the review modal)

**Expected:**
Clicking on Confirm transaction will disable Edit.

**Actual:**
You can click on Edit and exit the Review transaction modal, editing the transaction (the device is signing at the same moment) and so on. While not a critical bug, some users might get the impression that exiting the Review transaction modal cancels the whole action, and might be surprised when device finishes signing the transaction. @matejzak please comment on whether this should be addressed or not.

**Video:** https://drive.google.com/file/d/1qFNojfi0ZcQ4ojtnhaOK5V2zS-oJt6xw/view
https://drive.google.com/file/d/1xKjkNHoKxd_VRiQ8B6lPNwlHCQ_bTGPr/view

**Comment by wendys-cats** [comment]
**Issue: Edit available after confirm (with Cancel button)** 

**Steps to reproduce:**
**1.** set the connection to Slow 3G in browser
**2.** fill the Send form
**3.** Click on Review transaction
**4.** Click on Confirm transaction button
**5.** Click on Close, 

**Expected:**
Clicking on Confirm transaction will disable exiting from the modal.

**Actual:**
You can click on Close (X) and exit the Review transaction modal, seemingly editing the transaction (the device is signing at the same moment). While not a critical bug, some users might get the impression that exiting the Review transaction modal cancels the whole action, and might be surprised when device finishes signing.
