### ISSUE TITLE
Coinmarket - redesign 1

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#13679]
<img width="1201" alt="image" src="https://github.com/user-attachments/assets/b776f7fd-eabe-4a99-9c2b-cef987beee47">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.8.1 (ff36df61a0f4df46dfc9fbff1ac26f00429a00dc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: BridgeTransport 2.0.32
