### ISSUE TITLE
Coinmarket - redesign - console errors

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13682]
**Describe the bug**
Console errors and slow loading when composing transaction

Navigating thru Sell and exchange generates lots of unexpected errors in app console.

**Info:**
 - Suite version: desktop 24.8.0 (1c6c918e36e7413de1753b4658b80c81306203b8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.8.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="1166" alt="image" src="https://github.com/user-attachments/assets/19ecce42-8e42-4035-aa38-3bf019875d55">

**Comment by adderpositive** [comment]
Fixed by this commit https://github.com/trezor/trezor-suite/commit/01610f0a9080dcb0c2d5d310596a2891bb0bf798

**Comment by bosomt** [comment]
**QA OK**
