### ISSUE TITLE
Coinmarket - redesign - sell section crash 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13683]
**Describe the bug**

Managed to replicate it on yesterday dev build and on todays build.
Had to reset app storage via looking for /Users/bosomt/Library/Application Support/@trezor/suite-desktop-dev folder yesterday. 
Video is from today, screenshot is from yesterday.
Happened to me every time i tried to sell my Bitcoins

**Steps to reproduce:**
1. Load account with funds
2. Try to sell it via coinmarket section

**Info:**
 - Suite version: desktop 24.8.0 (1c6c918e36e7413de1753b4658b80c81306203b8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.8.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

<img width="1434" alt="Screenshot 2024-08-06 at 19 56 59" src="https://github.com/user-attachments/assets/11e61f6e-6d59-44b9-91cb-32a3fad023b9">

<img width="539" alt="image" src="https://github.com/user-attachments/assets/54dfca58-4e70-410d-bd83-7d518a9b9ed2">

https://github.com/user-attachments/assets/41372ca1-9fa7-497a-a11a-2e07716da095

**Comment by adderpositive** [comment]
Looks like old version of the Sell sectiont - should be fixed by this PR https://github.com/trezor/trezor-suite/pull/13685

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.8.0 (ad4737e3b34efe19f535c288130b3af528007031)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
