### ISSUE TITLE
Fiat rates missing in blockbook return -1

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13689]
**Describe the bug**
In case Blockbook does not have fiat rate, it returns `-1`. It means error

It never happened in production but it would be nice to check it. So that we do not show it in suite UI.

![Screenshot 2024-08-07 at 11 29 35](https://github.com/user-attachments/assets/aa926ab0-a5b9-4250-b834-d9107a622332)
![Screenshot 2024-08-07 at 11 29 22](https://github.com/user-attachments/assets/59514c9c-cc2c-4422-8337-24542949c2bc)

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/98f2a81d-735c-4ab5-9efb-1f8086aa7efe)
![Image](https://github.com/user-attachments/assets/77b0786f-fe83-44e4-b281-a35cbb733b9e)


**Info:**
 - Suite version: desktop 24.12.0 (f43af85636fa7911c692fe274cd0726a74138726)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: BridgeTransport 2.0.33
