### ISSUE TITLE
Passphrase - missing event

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#13691]
Add event to Passphrase flow. 
When user inserts passphrase and it is identified as empty, add event when user clicks on "Yes,open" empty passphrase.

**Comment by matejkriz** [comment]
What events are reported from the screen with "Yes, open" button:
- If user click X to close the passhprase flow 
 ```
LOG  Analytics report 'screen_change': {"payload": {"currentScreen": "Home", "previousScreen": "PassphraseEmptyWallet"}, "type": "screen_change"}
 LOG  Analytics report 'passphrase/exit': {"payload": {"screen": "PassphraseEmptyWallet"}, "type": "passphrase/exit"}
```

- If user click Try again
```
LOG  Analytics report 'passphrase/try_again': {"type": "passphrase/try_again"}
 LOG  Analytics report 'screen_change': {"payload": {"currentScreen": "PassphraseForm", "previousScreen": "PassphraseEmptyWallet"}, "type": "screen_change"}
```

- If user click "Yes, open", nothing is reported right away, but it just opens the bottom sheet with only option to click on "Got it"
```
 LOG  Analytics report 'screen_change': {"payload": {"currentScreen": "PassphraseVerifyEmptyWallet", "previousScreen": "PassphraseEmptyWallet"}, "type": "screen_change"}
```

@mnuky please check if it is sufficient, or we really miss something

**Comment by matejkriz** [comment]
Closing this now, I believe we should have the relevant data already.
