### ISSUE TITLE
Preloader component

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#137]
What is  the purpose for implementing Preloader component here:

https://github.com/trezor/trezor-suite/blob/44c6be7eadb9fb90de3d9f11bd301f2e89a6f7c5/packages/suite-web/pages/_app.tsx#L29-L31

and here 

https://github.com/trezor/trezor-suite/blob/44c6be7eadb9fb90de3d9f11bd301f2e89a6f7c5/packages/suite-desktop/pages/_app.tsx#L29-L31

and probably in other build targets.

Wouldnt it be better to implement it only in suite-core index.tsx?

**Comment by ZdenekSL** [comment]
Closed after discussion
