### ISSUE TITLE
Crash when checking remembered 2.8.1 device after upgrade to 24.8.1 version

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13704]
**Describe the bug**
Crash when checking remembered 2.8.1 device after upgrade to 24.8.1 version.
Its kinda edge case as 2.8.1 was not yet released in Suite as i was not able to reproduce issue with 2.7.2 device

**Steps to reproduce:**
1. Start 24.7.3
2. Remember device with 2.8.1 FW
3. Start Suite with remembered and disconnected device

**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="894" alt="Screenshot 2024-08-07 at 20 51 06" src="https://github.com/user-attachments/assets/92c298a9-a8f7-4e54-9e2b-205a208bb3ff">
<img width="545" alt="Screenshot 2024-08-07 at 20 52 58" src="https://github.com/user-attachments/assets/2e31d6d4-35e6-4bc7-bc04-77f950f4dbf2">

**Comment by STew790** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.8.1 (b4f8ad7e864cf72f3965f41e541e280bfa906a7d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
