### ISSUE TITLE
Broken buttons in Settings on lower width

### ISSUE THREAD

**Issue by evgenysl** [trezor/trezor-suite#13709]
**Describe the bug:**

When I resize the window, buttons in Settings break, see screenshot.
Not happening on 24.7.3

**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![Screenshot 2024-08-08 at 11 58 42](https://github.com/user-attachments/assets/f2ecab47-7e48-456b-95eb-aca2bf1a2971)

**Comment by tomasklim** [comment]
duplicate https://github.com/trezor/trezor-suite/issues/13629
