### ISSUE TITLE
Switch Wallets modal: Visual update

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1371]
Including: 

+ Hover 
+ Outline border (selected Wallet)
+ Add wallet centered 

**[Zeplin](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5e7a482bf60fd483cbea8219)**

**Comment by slowbackspace** [comment]
New design is missing the case "Device needs attention" with "Solve issue" button. The position where it should be placed is blocked by "Device Settings" button. For now I am not gonna implement this button, keeping the position available for "Device needs attention".

**Comment by glacierbits** [comment]
Discussed & solved on Slack. Removing the Product label.

**Comment by bosomt** [comment]
@matejzak 

Zepelin:
You’re not invited to this project
Please contact project members.
