### ISSUE TITLE
Coinmarket - redesign design issues

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#13719]
## Design bugs
1. Overlap select and modal
![image](https://github.com/user-attachments/assets/7ffd2005-d7d9-4933-b338-5902626f0abf)
2. Not displaying the received amount in the Buy detail transaction and partner logo with the name
![image](https://github.com/user-attachments/assets/16f22458-6f60-4586-b260-f3a5dbcfb498)
3. The Receive method in error state is just blank, let’s add ‘No methods available'. [Figma link](https://www.figma.com/design/xSW1knAjH25SfOmqSdNioY/Trade?node-id=7651-16248&t=dxYKbMUF8mkxOiU3-1)
![image](https://github.com/user-attachments/assets/cc6d403b-d9bd-4902-91a4-78e7c5b6ca87)
4.  The space between the chips and the input is not correct, it should be 8px.
![image](https://github.com/user-attachments/assets/1ee527da-36b9-46f1-bde5-0dec13921745)
5. Remove button title (https://github.com/trezor/trezor-suite/issues/13741)
![image](https://github.com/user-attachments/assets/2301d9f1-61ed-4531-8eef-78140bb2fc14)
6. Sell `All` works only on double-click
7. Fiat change in the Exchange section doesn't update fee levels and `Compare offers` is stuck.
8. Receive address design bug (https://github.com/trezor/trezor-suite/issues/13679)
9. Exchange badly selected cryptocurrency (BE problem)
10. https://github.com/trezor/trezor-suite/issues/13740
11. https://github.com/trezor/trezor-suite/issues/13739

**Comment by tomasklim** [comment]
1. Does it make sense to offer account which is not in Suite for coins we support? It can lead to errors

**Comment by bosomt** [comment]
**QA OK**

follow up here https://github.com/trezor/trezor-suite/pull/13720

**Info:**
 - Suite version: desktop 24.8.1 (738a69170a50b3c76ead3dac6b6e200e564b2e50)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.2 regular (revision null)
 - Transport: BridgeTransport 2.0.32
