### ISSUE TITLE
Cardano missing discovery button on add

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13711]
**Describe the bug**
- It does not offer discovery when Cardano is added

https://github.com/user-attachments/assets/e15f1fb3-506d-4002-b342-f05f3a26b5f3

I preparated this bug from #13324

**Comment by bosomt** [comment]
**QA OK**

button is back


**Info:**
 - Suite version: web 24.9.0 (244b9d62f86d9de0a6ccfd7affb4039c1a0ad16f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.2 regular (revision null)
 - Transport: BridgeTransport 2.0.32
