### ISSUE TITLE
Can't initialize new device with remembered wallets

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#13721]
**Describe the bug**
If I have some remembered wallet, I can't initialize a new device and do an onboarding. The "refresh" button in the device switcher is inactive and I can't click on it for some reason.

**Steps to reproduce:**
1. Start Suite 24.8.1 and remember some wallet
2. Disconnect the device
3. Connect an uninitialized device
4. The device shows up in the device switcher and there's a "Refresh" button but I can't click on it

**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
I can initialize a new device with remembered wallet.

**Screenshots:**
In version 24.7.3 (BEFORE)
![image](https://github.com/user-attachments/assets/0f850d1f-2615-436c-ae87-c5cddabdc134)

In version 24.8.1
![image](https://github.com/user-attachments/assets/708357ee-2a07-4a07-983f-b3dc8ebd0b21)

**Comment by bosomt** [comment]
**QA OK**

- remembered TT
- connected "fresh" T1 with old BL
- i was able to acquire it without any problem


https://github.com/user-attachments/assets/2117aae7-6304-42d2-8b3e-39a1abc9ae28



**Info:**
 - Suite version: desktop 24.9.0 (0a0f1e7d6a3c89e7134929dab5e5032702a4abcd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.9.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
