### ISSUE TITLE
Coinmarket - redesign exchange

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#13722]
## Intro
- [Figma link](https://www.figma.com/design/xSW1knAjH25SfOmqSdNioY/Trade?node-id=6032-33921&m=dev)

## Design before
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/796f1f37-dc23-4363-afc0-58845b7feb84">

## Design after
<img width="744" alt="image" src="https://github.com/user-attachments/assets/e206a167-c3c6-493d-966e-60261b516cc6">

##  Other information
Resolve https://github.com/trezor/trezor-suite/issues/13391 (deprecated)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.9.0 (983e42f2cc2f6fb51463a26c7f6206c4f56a3d14)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
