### ISSUE TITLE
DCA landing page in Trezor Suite

### ISSUE THREAD

**Issue by marek-andrsk** [trezor/trezor-suite#13724]
DCA has been removed from Suite recently and we'd like to offer users alternative in our Invity App which is more focused on this feature.

**Design**
https://www.figma.com/design/xSW1knAjH25SfOmqSdNioY/Trade?node-id=7987-27851&t=HV5JHw0xq1DT11aG-4

- DCA tab and this page will be only displayed to users in European Economic Area where is Invity App available

**Comment by bosomt** [comment]
I see DCA button.
But its separated by | is that expected ?
It looks sepaarted from other 3 buttons
@salax @jvaclavik 



![Image](https://github.com/user-attachments/assets/d279c358-9d6c-48fe-b207-aa27c4c2685e)



![Image](https://github.com/user-attachments/assets/8763602c-14f2-430a-894e-d6242937c0da)

**Info:**
 - Suite version: web 24.10.0 (ad118a04f39d2b359e76282c18b8ef92c011d7e5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision d7e1f0faf3ab8753dfd9dc292b503dff39fd81db)
 - Transport: BridgeTransport 2.0.33

**Comment by salax** [comment]
@bosomt yeah, separator is in the design
