### ISSUE TITLE
Fix add account of eth, sol, ada in debug mode

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13736]
You should probably reuse info from #13735, maybe you would have to do those two issues together

- Fix account type and account desc in add account modal for solana, evm, cardano
- maybe start to show derivation path for solana/eth in the selector

Screenshots:
We do not have text strings logic ready for unknown account types, so that's why it is all `Legacy`
![Screenshot 2024-08-09 at 15 43 21](https://github.com/user-attachments/assets/98cbe798-5044-4b09-88e9-cb7091a79eeb)
<img width="510" alt="Screenshot 2024-08-09 at 15 49 08" src="https://github.com/user-attachments/assets/857d5bb9-9f26-4918-97f3-22c09b3a2ccb">

**Comment by enjojoy** [comment]
Resolved here https://github.com/trezor/trezor-suite/pull/13995

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (ea069c398862907b1ae3fc12fb0c9a2d6d5a3e6e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport
