### ISSUE TITLE
Add account details page to all networks

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13735]
Introduce this page for each coin
- you can use badge in account type so that people connect it visually

![Screenshot 2024-08-09 at 16 45 41](https://github.com/user-attachments/assets/9a5dd638-8be3-43e8-85d3-e1f29123f174)

- Public key should be hidden for non-XPUB coins, we can show descriptor (receive address)
- You need to find info of account types of coins which did not have details page before

You can inspire by rabby EVM info. BIP44 is the one we support by default
<img width="758" alt="Screenshot 2024-08-10 at 15 52 32" src="https://github.com/user-attachments/assets/46bba6f9-b972-492d-90a1-93a3a52acd7b">
<img width="782" alt="Screenshot 2024-08-10 at 15 52 27" src="https://github.com/user-attachments/assets/585468e6-d16c-4fcb-a6ad-981f409f34a2">
<img width="789" alt="Screenshot 2024-08-10 at 15 52 24" src="https://github.com/user-attachments/assets/bbf2c012-58a4-49da-ba21-57ace95e1de5">

Some solana info here https://help.phantom.app/hc/en-us/articles/12988493966227-What-derivation-paths-does-Phantom-wallet-support

Cardano you need to find. Regarding trezor-icarus, it is there because we had some bug in firmware for 24words seed.

**Comment by tomasklim** [comment]
Related #13767

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (ea069c398862907b1ae3fc12fb0c9a2d6d5a3e6e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport
