### ISSUE TITLE
Unable to acquire Device

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1373]
**Steps to reproduce:** 

Two Chrome Suite windows opened. 
Unable to acquire Device from another window.

<img width="1440" alt="Screen Shot 2020-03-24 at 21 38 35" src="https://user-images.githubusercontent.com/29627086/77475199-b8633000-6e18-11ea-80e4-baed65518d97.png">

**Comment by szymonlesisz** [comment]
i'm afraid there is nothing we can do about it.
Looks like webusb error, "enable to claim interface" (cannot open device to read mode), only reload will help at this point

**Comment by szymonlesisz** [comment]
why are you using webusb btw? :)
