### ISSUE TITLE
Coinmarket - redesign Switching to fiat input in Sell doesn't switch it for the first time

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#13739]
**Describe the bug**
When I try to switch to fiat for the first time, it doesn't really happen and there is a forever loading in the "Receive method" part.

**Steps to reproduce:**
1. Go to your BTC account
2. Go to "Trade" section
3. Select "Sell" feature
4. Switch to EUR from BTC input
5. Observe that it doesn't switch and there's forever loading in the "Receive method" part below

**Info:**
 - Suite version: desktop 24.8.1 (b4f8ad7e864cf72f3965f41e541e280bfa906a7d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
Input from BTC to fiat switches correctly

**Video:**
https://youtu.be/vF8R6ucRgzE

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.8.1 (ff36df61a0f4df46dfc9fbff1ac26f00429a00dc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.1 regular (revision 55473a0b4be7b22317cd0c401c938d430d86f29f)
 - Transport: BridgeTransport 2.0.32
