### ISSUE TITLE
Add account type badges to non-default accounts

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13737]
Description:
- [x]  Add account type badge to non-default accounts
- [x]  Add account type badge to Header of account, also to the smaller when it it scrolled down
- [x] Add account type badge to send form when sending to self
- [x] Add account type badge to Exchange part

Design:
[Figma](https://www.figma.com/design/o6eb4wUMjSu5xMb34423vh/Tokens?node-id=4341-13003&t=ymVL5AzFo1ExeyGM-1)

![Screenshot 2024-08-05 at 9 49 28](https://github.com/user-attachments/assets/d51e8f44-2dc6-4e1c-a740-bd4e1b20a9f6)
![Screenshot 2024-08-05 at 9 50 02](https://github.com/user-attachments/assets/143ebb9c-955e-403b-a7ab-54f935bfb8d1)
![Screenshot 2024-08-05 at 9 50 30](https://github.com/user-attachments/assets/6f295968-26ec-4b0a-864e-4c3b541b34ab)

**Comment by bosomt** [comment]
**QA OK**

- account badges visible in transaction history
- account label is present in account header
- account label is present in account header when scrolling
- account label matches left account selection section /checked ETH and BTC/
- account label is present in `Send` dialogue when sending funds between accounts
- account label is present when sending between two devices
![Screenshot 2024-08-28 at 13 38 25](https://github.com/user-attachments/assets/dec4e416-0948-44d0-9e89-8841dab0215b)
- account label is present in trade section
![Screenshot 2024-08-28 at 13 39 58](https://github.com/user-attachments/assets/b941468e-c809-4a9f-a8b2-e1fb65452dd4)

**Info:**
 - Suite version: web 24.9.0 (dea394b61290428b18d191b05391a5b365b6fa8b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: Trezor T3T1 2.8.2 regular (revision c7eabe30886bad47dd1a36e101fb77e8cffc2dfc)
 - Transport: BridgeTransport 2.0.33

**Comment by enjojoy** [comment]
Ohh this badges look very weird on your Trade section screenshot. I didn't experience it myslef yet. @jvaclavik 
Could it be because of elevation level color collision?

**Comment by enjojoy** [comment]
Okay, for me it looks normal on Chrome. Will test on Mozilla 
![image](https://github.com/user-attachments/assets/80e7808c-806a-4eff-b3c9-228b90f42d74)

**Comment by bosomt** [comment]
Retested in Chromium app

- missing badges in `Sell section`
- Same badges like in Firefox browser

<img width="683" alt="image" src="https://github.com/user-attachments/assets/81d0d37d-a32c-4470-a4d5-ddec3fb78bd2">

<img width="256" alt="image" src="https://github.com/user-attachments/assets/d4ce33c8-2b4c-4e9f-8c66-73bb6087152c">

**Comment by bosomt** [comment]
3x **QA OK**

- retested on send to multiple recipients with multiple account types

![Image](https://github.com/user-attachments/assets/277926e6-50f8-4344-befb-ab9d053ec1cc)

- accounts/coinmarket/sell#/btc/0/normal OK as well

![Image](https://github.com/user-attachments/assets/c31388c1-ff8b-4aa6-91a4-fdc4b545a5af)

- badges look as expected



![Image](https://github.com/user-attachments/assets/b9cfa485-b416-45d1-aa59-e435b38ff72c)



**Info:**
 - Suite version: web 24.9.0 (415a8355f01f3decc99e16194bfb75b3fb549aba)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
