### ISSUE TITLE
EVM Tokens / Contract address in send form

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13749]
## Description
Improve token select feature in send form. It should replace the currency (token) mini select menu in the send form.

![Image](https://github.com/user-attachments/assets/6e4ddf0f-005b-4a7a-887e-1844ee5a45f7)

[Figma design](https://www.figma.com/design/o6eb4wUMjSu5xMb34423vh/Tokens?node-id=4518-22627&t=wM3XYIq1PipOxf5S-1)

### Token select element
- a new element which enable users to choose a token in send form
- the element is placed at the top to highlight and clarify what is being sent. The user can change it at any time; it includes the mainnet coin and tokens available on the selected account
- an 'i' icon will appear next to it, and hovering over the icon will show the full contract address in a tooltip.

![Screenshot 2024-09-30 at 10 52 52](https://github.com/user-attachments/assets/1276e0fd-2a00-451f-b7ca-8630e4a49720)
- in case of Cardano, please show both `assetId` and `fingerprint`

### Token select modal _TBD_
- Reuse choose token modal #14551 
- _Design TBD_ (it should not be dropdown but modal from 🔝 
- Searchable by `name`, `symbol`, `contract address`
- Choose `Shown` / `Hidden`
- Display contract address

![Screenshot 2024-09-30 at 11 13 23](https://github.com/user-attachments/assets/f3f3998c-4632-45de-8a70-4d329221a0b3)
![Screenshot 2024-09-30 at 11 12 49](https://github.com/user-attachments/assets/1e1dd0b9-b821-428b-9d89-80934b461c3b)
 ![Image](https://github.com/user-attachments/assets/b31fcc6f-12c1-4d03-ad0a-7009bb78b1fc)

**Comment by Hermez-cz** [comment]
### Design & spec:

Design: [Figma](https://www.figma.com/design/o6eb4wUMjSu5xMb34423vh/Tokens?node-id=4518-22627&t=wM3XYIq1PipOxf5S-1)

Specification: Please add a dropdown element for sending tokens on the specific network associated with the currently open account.
![Image](https://github.com/user-attachments/assets/b8591be2-0f1f-4513-8f1e-6628d93e8af0)

It is intended to replace the currency (token) mini select menu in the send form.
![Image](https://github.com/user-attachments/assets/6e4ddf0f-005b-4a7a-887e-1844ee5a45f7)

The entire send form for networks / coins with tokens should look like this:
![Image](https://github.com/user-attachments/assets/a0183541-f45c-4032-89c4-d4be61528c3a)
- A new dropdown element is placed at the top to highlight and clarify what is being sent. The user can change it at any time; it includes the mainnet coin and tokens available on the selected account.
- This is how the element [appears when opened](https://www.figma.com/design/o6eb4wUMjSu5xMb34423vh/Tokens?node-id=4344-25715&t=wM3XYIq1PipOxf5S-1):
- ![Image](https://github.com/user-attachments/assets/b31fcc6f-12c1-4d03-ad0a-7009bb78b1fc)
- When collapsed, it will display the token's contract address in a condensed format if a token is selected. An 'i' icon will appear next to it, and hovering over the icon will show the full contract address in a tooltip.
- ![Image](https://github.com/user-attachments/assets/25d0f822-45d9-420a-b955-cfd252ac4ba6)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.12.0 (4258d1c3c5bfcc405e73e48ea633f0bdf62f4d80)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport
