### ISSUE TITLE
Coinmarket - redesign When switching to fiat input in Sell I get an error

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#13740]
**Describe the bug**
When I switch to fiat input in the Sell section, I get almost infinite loading and a error that shouldn't be there since I didn't even input anything in the field.

**Steps to reproduce:**
1. Start Suite
2. Go to the "Trade" section and select the "Sell" feature
3. Try to switch from BTC to fiat input

**Info:**
 - Suite version: desktop 24.8.1 (b4f8ad7e864cf72f3965f41e541e280bfa906a7d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
There is no error with decimals since I didn't input anything.

**Screenshot:**
![image](https://github.com/user-attachments/assets/fae6011c-aa8d-4899-bf54-12e4655529af)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.8.1 (ff36df61a0f4df46dfc9fbff1ac26f00429a00dc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
