### ISSUE TITLE
Coinamarket - redesign Remove Trade button and price info for testnets

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13746]
**Describe the bug**
Remove Trade button and price info for testnets

**Steps to reproduce:**
1. Enable TEST
2. Observe Trade section in Account info

**Info:**
 - Suite version: desktop 24.8.1 (b4f8ad7e864cf72f3965f41e541e280bfa906a7d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/user-attachments/assets/993e8fde-7f5c-4a49-9e62-a52e7eed87c3)

**Comment by tomasklim** [comment]
I enabled it for testnets to have it 1:1 with mainnets. I don't see single problem having it there. 

https://github.com/trezor/trezor-suite/pull/13634/commits/cbcf6562fadc075e8b50674807ccbc6ee657556c
