### ISSUE TITLE
Coinmarket - redesign Missing tooltip translation

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#13741]
**Describe the bug**
There's a missing translation for tooltip in the Trade section of Suite on the "Last transactions" button (on hover).

**Steps to reproduce:**
1. Go to "Trade" section
2. Hover over the "Last transactions" button
3. Observe the missing translation on the tooltip

**Info:**
 - Suite version: desktop 24.8.1 (b4f8ad7e864cf72f3965f41e541e280bfa906a7d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/user-attachments/assets/7fb4d2ad-0a2c-4223-b825-869b46afe7ae)

**Comment by adderpositive** [comment]
This specific case is resolved in https://github.com/trezor/trezor-suite/pull/13720, but other translations are missing.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 24.8.1 (738a69170a50b3c76ead3dac6b6e200e564b2e50)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.2 regular (revision null)
 - Transport: BridgeTransport 2.0.32
