### ISSUE TITLE
Staking fee reserve advice is not shown when minimum amount is typed

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13750]
Should be display also when staking amount === minimum
![Image](https://github.com/user-attachments/assets/9f9d9740-ba71-4952-b339-0b3d6e947939)
![Image](https://github.com/user-attachments/assets/c4c27255-5a96-41eb-8c76-245d4d77a48b)

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/user-attachments/assets/b10eb522-b194-4ea6-8103-631053cd341e)


**Info:**
 - Suite version: web 24.9.0 (b2ea3830e71db4f0e32a202fcaff2959b952a02a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32
