### ISSUE TITLE
Unify staking files

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13754]
Right now utils and types are all over suite in many files.

Please unify as much as possible.

There is `stake.ts` utils file in `packages/suite`
There is `stake.ts` utils file in `@suite-common/suite-utils`
Then there is `stakingUtils.ts` in `@suite-common/wallet-utils`

There is `stake.ts` utils file in `@suite-common/wallet-types`
There is `stakeTypes.ts` utils file in `@suite-common/wallet-core`
- there are also values which are definitely not types in this file. Maybe should be in file `ethStaking.ts`

The file with constants `ethStaking.ts` is also hard to find, please come up with better naming

Please do some kind of cleaning and organising so that it is easy to find what we are looking for.

**Comment by omykhailovskyi** [comment]
Please add acceptance criteria, as discussed

**Comment by sime** [comment]
> Please add acceptance criteria, as discussed

@tomasklim

**Comment by tomasklim** [comment]
@dev-pvl @omykhailovskyi 

as discussed, create files for eth staking utils and generic staking utils. Same for types.

**Comment by bosomt** [comment]
**QA OK**

Stake and unstake THOL OK

**Info:**
 - Suite version: web 24.11.0 (c58454703ba01107ffa6e7938e1608354342b26a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: WebUsbTransport
