### ISSUE TITLE
Deduplicate errors in unstake modal when using other amount

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13753]
**Description**
- error is duplicated right under input and then in warning. Please show it just once. Under input in case it is related to it. In warning otherwise.

![Image](https://github.com/user-attachments/assets/ff7f2008-9e64-4715-98d3-0dbca552dff6)

![Image](https://github.com/user-attachments/assets/7319a045-0bc4-4e2f-b67a-bed2bc9c2833)

![Image](https://github.com/user-attachments/assets/7a766cc1-869f-4143-a894-050672249cc9)

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/user-attachments/assets/b409c267-6520-4874-9aea-37c7ba9082d8)



**Info:**
 - Suite version: web 24.9.0 (b2ea3830e71db4f0e32a202fcaff2959b952a02a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32
