### ISSUE TITLE
Custom fee warning is ugly in staking modals

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13751]
**Describe the bug**
![Screenshot 2024-08-10 at 20 47 11](https://github.com/user-attachments/assets/8b4d6945-a5bf-4ab6-a67f-1fc65758d014)
![Screenshot 2024-08-10 at 20 48 04](https://github.com/user-attachments/assets/27fc2ccb-fb7d-4fdb-997a-8f48a89ece89)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.9.1 (d8848035b1badf8ef15fb0cecb6113bfc87326a9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: BridgeTransport 3.0.0
