### ISSUE TITLE
Zero amounts when bumping fee of unstaking and claiming txs

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13752]
**Description**
- the amount of unstaking and claiming is indeed zero but let's fix it

**Current**
![Image](https://github.com/user-attachments/assets/bee5248c-14ca-489e-8d22-40638d33186c)

**Desired state**
- please check how it is done for regular unstaking/claiming tx that the amount is there. Maybe it is somehow hacked.
- I am thinking about parsing it from data in tx review modal in case it is staking type tx
- If you introduce this parsing from data. It would be nice to do it also for regular unstaking/claiming and remove hacky current solution.

Unstake:
![Image](https://github.com/user-attachments/assets/69ac1a57-61d5-4d25-b267-c1abd95b996a)

Bump unstake:
![Image](https://github.com/user-attachments/assets/dd3b3ec4-2d7d-4004-9f36-20c68c8fc46b)

**Comment by bosomt** [comment]
**QA OK**

- THOL - skare and unstake
- ETH - claim

**Info:**
 - Suite version: web 24.11.0 (258ab9664fb9cddbc0bd28638f00b56583b15e1d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Transport: WebUsbTransport
