### ISSUE TITLE
Send coins - review transaction

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#13763]
## Acceptance criteria
- [ ] User is prompted to compare the recipient address displayed on Trezor Device against the original source
- [ ] When user confirms the recipient address on Trezor, he continues to Confirming amount
- [ ] When user confirms amount, he continues to Confirm total including fee
- [ ] When user Sign the transaction on Trezor device, he can Send (finalise) the transaction in the app

## Resources
- link to DESIGN: 
   - [Address confirmation](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=1695-31209&t=KTigu9fek47mphXN-4)
   - [Confirm Amounts](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=1695-31433&t=KTigu9fek47mphXN-4)

**Comment by STew790** [comment]
**QA NOK**
- if I confirm the address and go to the amount and wanna check the address again on the device (which I can), the flow in the app continues forwards with a green dot
- 
**QA OK**
- i am prompted to check the original source of address (tooltip works as well)
- then i am prompted to confirm the address on device
- then the amount
- then the total and fee
- then I can proceed with sending the transaction

**Info:**
24.9.1 https://github.com/trezor/trezor-suite/commit/9ff8920814b8616034ab7375d1b6dbf9b5ec65ab

**Comment by PeKne** [comment]
@STew790 Do you mean that you check the address, go to the amount, and then click on the `go back` button in the firmware UI? You are saying that in that case, you would expect also the ui of the Trezor Suite Lite app to go back? I would love to see this behavior as well. Unfortunately, this is something that would have to be changed on the side of firmware and connect. This is an old known issue that is happening also on desktop without an easy fix. Good catch anyway.

If this is what you meant, I believe that the issue is QA OK.

**Comment by STew790** [comment]
Oh right, you are correct. I completely forgot about it :man_facepalming: . Approving this!
**QA OK**
