### ISSUE TITLE
Mac - small toolbar area to move app window

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13760]
**Describe the bug**
It is really hard to move window after latest changes on mac

**Info:**

-   Suite Version: 24.8.0

**Expected behavior**
Manipulating area to be bigger

**Screenshots**

https://github.com/user-attachments/assets/19c1390c-c400-495f-bb7c-ab60fe2ba369

**Comment by evgenysl** [comment]
tested in PR
QA OK

**Comment by evgenysl** [comment]
Also good on Intel Mac.
Can move app by holding above green line (except account name and buttons)

![Image 26 11 2024 at 15 39](https://github.com/user-attachments/assets/9cf1cf3d-7acc-42df-a924-0585f0e31a69)

QA OK
