### ISSUE TITLE
Allow to add ledger account types in Add coin flow

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13767]
We want to enable users to add ledge account types.

- [ ] make this work code wise
- [ ] adapt flow when nonBTC network has more account types. - account types description etc.

**Comment by vytick** [comment]
@mnuky What texts do we use with new accounts? Mainly everywhere where we have `ledger` account type?

For btc like networks we have:

<img width="406" alt="Screenshot 2024-08-12 at 11 18 25" src="https://github.com/user-attachments/assets/57482908-ba01-4507-9b45-dccb114b4ce2">

**Comment by tomasklim** [comment]
@vytick @enjojoy will deal with the texts soon

**Comment by Hannsek** [comment]
TBH We do not want to enable adding ledger account. At least we should discuss why. 
We decided to start the discovery of ledger accounts, but we didn't discuss adding them.

**Comment by Hannsek** [comment]
So let's please keep this under the debug mode for now until we discuss it.

**Comment by vytick** [comment]
Thanks for this intel 🙏 

cc @mnuky

**Comment by vytick** [comment]
we are not planning to do this
