### ISSUE TITLE
Coin Enabling - ensure networks are in the same order all the time

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13766]
No matter when you enabled the new network, still keep the same order of networks all the time.

**Comment by tomasklim** [comment]
We need this for desktop too 🙏

**Comment by vytick** [comment]
will be resolved by https://github.com/trezor/trezor-suite/pull/13876

**Comment by STew790** [comment]
**QA OK**
After enabling coins and finishing the discovery of them, they are ordered as in the coin enabling settings.

**Info:**

24.9.1 https://github.com/trezor/trezor-suite/commit/bf893a5e0f152087cb4e47a4921a64c3c4c1624f
