### ISSUE TITLE
Send coins - sign transaction improvements

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#13764]
The transaction detail page has to be redesigned according to the attached Figma link. After are these changes take place, the successfull send flow redirects to the transaction detail page, where user can see all the transaction data and metadata.

## Acceptance criteria 
- [ ] When user sends the transaction, transaction is proceeded to mempool to be mined
- [ ] User is redirected to detail of the transaction
- [ ] When transaction is sent in the mobile app, user sees the status of the transaction Pending
- [ ] When transaction is confirmed, it is marked as Confirmed

## Resources
- link to [DESIGN](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=1724-35592&t=KTigu9fek47mphXN-4)

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/5ae54cd7-24e8-43f7-9a54-ff084e482a6c)
![image](https://github.com/user-attachments/assets/77c3693b-cefd-4d8d-aa0e-8e3ee3a96b1c)

**Info:**
24.9.1  b415aa2
