### ISSUE TITLE
Send coins - navigation improvements

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#13765]
## Acceptance criteria
- [x] the send button is removed from dashboard (It will stay this way until we do not support send for all the networks)
- [x] user is able to enter the send flow from the account detail --> redirect directly to the send form (with particular account selected)
- [ ] user is not allowed to entry the send flow from portfolio tracker accounts 
- [ ] If user clicks on a close screen header button while is on device review in progress, he is redirected to the place from where he entered the send flow (dashboard or account detail)

**Comment by matejkriz** [comment]
> user is allowed to entry the send flow only with connected devices (not view-only or portfolio tracker)

@shenkys Do we have a design for it? I would expect some bottom sheet with message to connect the device to continue...

**Comment by STew790** [comment]
**QA OK**
- send button no longer on dashboard
- send button moved to assets

**Info**
24.9.2 https://github.com/trezor/trezor-suite/commit/7a4ddc9a8137951fe69c7693d4ac9e70511a39b4v
