### ISSUE TITLE
When aborting Create Multi-share Backup process Multi-share Backup creation disappears from settings

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13777]
**Describe the bug**
see https://satoshilabs.slack.com/archives/CKYFBT2C9/p1723475118504789
When aborting Create Multi-share Backup process Multi-share Backup creation disappears from settings

**Steps to reproduce:**
```
Have a Multi-share compatible device connected
Go to Settings > Device > Multi-share Backup; click [Create Multi-share Backup]
Check boxes, click [Create Multi-share Backup] primary CTA
Click [Enter current backup…] primary CTA
Approve on device, enter your current backup
After that you’re in Step 2 in Suite (screenshot)
On device set Shares count and Threshold (perhaps not necessary, I just did, so noting exactly how I got here)
Swipe up (confirm) on device until you’ll get to the 1st word of the 1st share
Cancel in Suite (close the modal)
Create Multi-share backup part disappeared from Settings (it was actually missing even below the blurry modal backdrop)
Refresh (CMD+R), go to Settings > Device; the Create Multi-share backup should be back
```

**Info:**
 - Suite version: desktop 24.8.1 (b4f8ad7e864cf72f3965f41e541e280bfa906a7d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
https://youtu.be/OLB3I8WOS2I

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/179e3912-43cd-4e2b-8301-3ec9bc7c01a2">

**Comment by mroz22** [comment]
would you please @bosomt retest it using this branch?  :pray: https://dev.suite.sldev.cz/suite-web/fix/connect-cancel-prompt/web/

I haven't checked very closely but changes in #13925 are related

**Comment by bosomt** [comment]
I was not able to replicate it anymore in this web branch

**Info:**
 - Suite version: web 24.10.0 (d56a818c8c8f7fb07618d41daa645e66f0aa06a1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: WebUsbTransport

**Comment by mroz22** [comment]
isn't it fixed maybe?

**Comment by bosomt** [comment]
**QA OK**

i was not able to replicate it anymore



**Info:**
 - Suite version: desktop 24.11.0 (99bc1a55596bd6c262159c160320ef3e1862e385)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
