### ISSUE TITLE
Clear form to appear after input

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1378]
The option "X clear" to remove any inputs should appear after there is an actual input (as opposed to be there by default). 

<img width="165" alt="Screen Shot 2020-03-25 at 10 34 30" src="https://user-images.githubusercontent.com/29627086/77523874-b637ba80-6e86-11ea-9b72-2f3957f061eb.png">

**Comment by bosomt** [comment]
works fine!
