### ISSUE TITLE
Coinmarket - redesign bugs

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#13786]
# Description

1. I am buying on Acc `#2`, why receive acc is by default ETH `#1`?
![Screenshot 2024-08-12 at 22 51 10](https://github.com/user-attachments/assets/b14a84f4-8b35-4003-b025-cf250196ab0d)

2. You are showing hidden tokens 
![Screenshot 2024-08-12 at 22 58 30](https://github.com/user-attachments/assets/9fc4a4c9-15fa-4661-8879-cdafe3f6cb52)

3. Balances are not blurred 
![Screenshot 2024-08-12 at 23 05 06](https://github.com/user-attachments/assets/d24a8876-ef4d-4846-8aac-c891247ab447)

4. Sell form does not respect that I am on polygon network
https://github.com/user-attachments/assets/91b9a5b5-4025-4480-8161-2b00b7ee72b7

5. Last transactions are not powered by Invity footer
![Screenshot 2024-08-12 at 23 08 27](https://github.com/user-attachments/assets/7ca60bdd-f934-45a9-ac6f-fcce9b6d3ef7)

6. Maybe there could be a search filter working not just with abbreviation "BTC", but also with whole word like "Bitcoin":
![image](https://github.com/user-attachments/assets/15b48c66-2cf2-4ec3-84bb-33f3ece52288)

7. https://github.com/trezor/trezor-suite/issues/13792

cc @tomasklim @MiroslavProchazka

**Comment by misartomas** [comment]
Maybe there could be a search filter working not just with abbreviation "BTC", but also with whole word like "Bitcoin":
![image (2)](https://github.com/user-attachments/assets/d2914948-f518-40dc-84c3-636c57a71c71)

**Comment by bosomt** [comment]
**QA OK**

1. ✅ 
2. ✅
3. ✅
4. ✅
5. ✅
6. ✅
7. ✅

**Info:**
 - Suite version: desktop 24.8.2 (96e583538c6a30e010a81346d1251f3246cb1def)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.32
