### ISSUE TITLE
Send coins - fee level unsuficient balance

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#13782]
WIP 🚧: If the user fills out the send form and then selects a fee level that he does not have enough funds for, we should inform him about it and prevent him from continuing to the on-device review step.

**Comment by PeKne** [comment]
info for QA: It should be impossible to submit the address + amount form in case that the amount is too high for composing a transaction with at least normal fee.

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/4521d1b0-edef-4644-a57c-613ab3f430cf)
![image](https://github.com/user-attachments/assets/ee5c2931-98b2-4996-8eab-fa05374594e6)
![image](https://github.com/user-attachments/assets/3ce38ed6-004f-47b1-96ad-17a3d8dabd6d)

**Info**
24.9.2 https://github.com/trezor/trezor-suite/commit/7a4ddc9a8137951fe69c7693d4ac9e70511a39b4
