### ISSUE TITLE
Send coins - send max

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#13791]
## Acceptance criteria
- [ ] there is a Send max button next to the `amount to be sent` input
- [ ] When user selects send max, balance is calculated as `balance - normal_fee`
- [ ] When user changes fee level on the next screen, the totalAmount stays unchanged and the outputs are adjusted so it is always possible to send the transaction with any fee level

**Comment by tomasklim** [comment]
When I click on `max` in rabby, This fee chooser is auto opened. I kinda like this approach 
![Screenshot 2024-08-14 at 9 43 12](https://github.com/user-attachments/assets/85b648da-4fd0-4963-9663-b4ab0599fb1c)

**Comment by PeKne** [comment]
> When I click on `max` in rabby, This fee chooser is auto opened. I kinda like this approach ![Screenshot 2024-08-14 at 9 43 12](https://private-user-images.githubusercontent.com/33235762/357721036-85b648da-4fd0-4963-9663-b4ab0599fb1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDE4MDgsIm5iZiI6MTcyMzY0MTUwOCwicGF0aCI6Ii8zMzIzNTc2Mi8zNTc3MjEwMzYtODViNjQ4ZGEtNGZkMC00OTYzLTk2NjMtYjRhYjA1OTlmYjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDEzMTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NDdiZmEyYzFiOWYwZjBjZGFlNzM1MjQzOTI2MDYxMTU4ODhhYzExYTk4NWQwNTRiZDA3MTg5Mjg3MDg0NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fajU2-H9OWctZehrIXXf9hv9H-AlYO9USkVbdm3auMs)

cc @shenkys

**Comment by matejkriz** [comment]
@mnuky /@sime is this must have for first release or can be delivered one release later?

**Comment by STew790** [comment]
**QA OK**
Send max button works as expected.
- send max button is present for coins with "Send" feature
- it is correctly calculated
- changing the fee changes the send max amount

https://github.com/user-attachments/assets/82956a91-64ff-4262-89cb-9a10045d8ef1

**Info**
24.11.1 https://github.com/trezor/trezor-suite/commit/c214aa306ebf33a0255973753fb55b487dcdc6db
