### ISSUE TITLE
Style Add hidden Wallet button as disabled

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1380]
Terciary button **_+ Add hidden Wallet_** needs to be disabled when Device disconnected.

In such case, please add tooltip on hover saying "Connect your Trezor to add hidden wallet"

<img width="801" alt="Screen Shot 2020-03-25 at 12 33 35" src="https://user-images.githubusercontent.com/29627086/77532321-f3a34480-6e94-11ea-9089-49d97d0c9f95.png">

**Comment by slowbackspace** [comment]
hehe, it already is disabled, just the styles seem to be broken :] I'll fix it and add the tooltip

**Comment by glacierbits** [comment]
My bad, sorry! Title fixed. I wished the generally excepted 3rd hard thing in CS was calling things the right name, but it's probably just me.

**Comment by bosomt** [comment]
maybe you can consider to add possibility to add wallet when you dont want to add no passphrase wallet and device IS connected ?

![image](https://user-images.githubusercontent.com/31506317/78645099-39113a00-78b7-11ea-85e3-92e4c7490171.png)

**Comment by bosomt** [comment]
works fine but...
it doesn't work when connected device doesnt have no passphrase wallet loaded,
see screenshot.

please decide /fix or approve/ in your team
