### ISSUE TITLE
Staking: Restaked badge

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#13804]
# Problem
Users are unclear if rewards earn yield.
The text `(i) Your THOL rewards also earn the APY rate.` is not discovered   

# Task
## Drop (i) text
> Your THOL rewards also earn the APY rate. Keep your funds staked or add more to increase your rewards.
## Badge w/ tooltip
![rewards-restaked](https://github.com/user-attachments/assets/c6493815-123e-4225-91ce-d4b496d915c5)

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/user-attachments/assets/82cb3467-0132-45eb-9410-504d443ec9a0)

🤑 

**Info:**
 - Suite version: web 24.9.0 (b2ea3830e71db4f0e32a202fcaff2959b952a02a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32
