### ISSUE TITLE
Coin Enabling - Flow polishing

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13819]
- [x] Trigger init screen from any location
- [x] prevent dismissing init screen by hw back while no network is selected
- [x] enable coin enabling for develop and debug
- [x] Make sure showing the UI works correctly with biometric, pin, connecting screen, etc. 
- [x] preselect view only networks when user enters settings Coin enabling before initial setup takes place

**Comment by STew790** [comment]
**QA OK**
All mentioned points are OK.

**Info**
24.9.2 7a4ddc9
