### ISSUE TITLE
Send coins - satoshi unit for BTC

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#13823]
## Acceptance criteria
- [ ] If user selected satoshi unit in settings, he also sees amount in satoshi in send form

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/4409c58e-9adc-4d2b-86b8-4c00175c21eb)

**Info**
24.9.2 https://github.com/trezor/trezor-suite/commit/7a4ddc9a8137951fe69c7693d4ac9e70511a39b4
