### ISSUE TITLE
Refactor and type network config

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13839]
There is file `networksConfig.ts`

In this file, there is `networks` variable declaring all networks available in Suite and there is also `networksCompatibility` which is a transformation of `networks` to format used in the past.

**Issues:**
- `networks` variable is not typed, the type is generated from the structure of file
  - it would be best to type it so that it is easier to work with it
- `networksCompatibility ` is dynamic and it is almost a blackbox how to work with it. It would be great to finally get rid of it in behalf of `networks`

- together with those changes we can maybe change (as a bonus, not really needed but would be nice)
  - `explorer` can have `base` url and then just `path` for `tx, account, address`,...
  - `default` account type which is now on root of each network could be moved to `accountTypes` under `default` type
  - `customBackends` can be called just `backendTypes` or `backends`
  - I am not sure if we really need `support`, it is also defined in `coins.json`
    - cardano: old fw version of T is deprecated anyway so we can just bump supported version in there maybe
    - solana is 1:1
    - probably we need it but extended for seed type, see Optimisation #13738

**Why:**
- cleaner codebase
- easier work
- easier to implement - different `networkSymbol` from `networkCurrency` required for L2
  - `ln`: `BTC`
  - `op`: `ETH`
  - `base`: `ETH`
  - ...

**Comment by Lemonexe** [comment]
All of the PRs above :arrow_up: solve only the first two bullet points, not the 3rd (_together with those changes we can..._)

The bonus work is **not done** yet. I'd suggest moving it to another issue, because wow, this was already much more work than I anticipated at first :open_mouth:

Also, there are no unit tests for [wallet-config utils](https://github.com/trezor/trezor-suite/blob/develop/suite-common/wallet-config/src/utils.ts) :see_no_evil:

**Comment by Lemonexe** [comment]
Created
- #14444 unit tests
- #14445 moved the bonus bullet points except the 2nd one - I don't think it's necessary, there is a helper for this purpose introduced in [this commit of #14281](https://github.com/trezor/trezor-suite/pull/14281/commits/8f0270267d714f747542facdee446861ef20ed69)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.10.0 (53303523db1a941907766902bcf79b3f320b4dd2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
