### ISSUE TITLE
Coin Enabling - show at least one account for each enabled coin

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13844]
When coin (and coin enabling in general) is enabled, and no account with txns exist, show at least one default account (empty). 

If coin enabling is disabled only discover non empty accounts

**Comment by STew790** [comment]
**QA OK**
Enabled coins shows first empty accounts if there are no values for enabled coins.
When Coin enabling is turned off, only coins and accounts with some value are discovered.
When there are no coins with values and Coin enabling is turned off, "Empty wallet" message is shown.

**Info:**
- Mobile Suite Version: 24.9.1 https://github.com/trezor/trezor-suite/commit/b415aa2c5f4d8c5c767055211d4e22c85865c05c
- OS: Android
