### ISSUE TITLE
Unnecessary scrolling in Unstake modal  

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13848]
**Describe the bug**
Unnecessary scrolling in `Unstake` modal  probably thanks to  warning banner

**Steps to reproduce:**
1. Discover account with staked Eth funds
2. Change fee to custom
3. Observe modal design

**Info:**
 - Suite version: web 24.9.0 (e86c3fea59d9d0d9acfeaccd0ab4c65f700fff59)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.32

**Screenshots:**

https://github.com/user-attachments/assets/b99c0e47-2fd5-4978-b181-894119a50219

**Comment by omykhailovskyi** [comment]
Currently there is a default height set for all modals, should we make an exception for Unstake Modal?
@sime , @tomasklim

**Comment by bosomt** [comment]
**QA OK**

already fixed by `Learn more` button fix

<img width="529" alt="image" src="https://github.com/user-attachments/assets/004bf229-d6c2-4581-a674-2fa184b9a24c">

**Info:**
 - Suite version: desktop 24.10.1 (6fbf039c99a65832b8acf0c0852f7df74ffea128)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.10.1 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.1
