### ISSUE TITLE
Delayed error response when closing trezor popup quickly (@trezor/connect-webextension)

### ISSUE THREAD

**Issue by superKalo** [trezor/trezor-suite#13856]
When initiating an action in the @trezor/connect-webextension package that triggers the Trezor popup (e.g., `ethereumSignTransaction`, but all other methods too), if the popup is closed immediately, there is a ~10-second delay before receiving an error response from TrezorConnect. **That wasn't the case with the `@trezor/connect-web` package.**

Steps to Reproduce:

- Trigger an action that requires the Trezor popup (e.g., `ethereumSignTransaction`).
- Close the popup **quickly**, before any interaction.
- Observe the delay in receiving the error response.

Here's a video:

https://github.com/user-attachments/assets/ca6586ae-aa53-41a4-9cc6-3e738d07cc32

Expected Behavior: The error response should be received immediately after closing the popup. Like it does if I don't close the Trezor popup immediately (wait a bit). Here's me again, **waiting a bit**:

https://github.com/user-attachments/assets/9fff8278-b31e-42b4-948f-ce3543ca4122

The videos are with the Ambire Wallet, but the same is reproducible with Rabby Wallet.

**Comment by MiroslavProchazka** [comment]
cc @karliatto
