### ISSUE TITLE
QR scan for outgoing address is not working

### ISSUE THREAD

**Issue by worras2019** [trezor/trezor-suite#13861]
I am using Trezor Suite on MacOS sonoma 14.6.1. When I used the QR scan to scan the QR code of outgoing address via Mac's camera or iPhone connected to it, nothing happened. The Trezor Suite version is 24.7.3. Please check the bug.

**Describe the bug**

**Info:**

-   Remembered Wallet: yes/no
-   Suite Version: app/web, commit
-   Browser: name, version
-   Browser Installation Method: snap, flatpak, app store, windows store, downloaded installer, etc.
-   OS: name, version
-   Bridge: version
-   Firmware Version: model, version/commit

**How to reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by MiroslavProchazka** [comment]
@trezor/qa can you try to replicate please? 
@evgenysl

**Comment by bosomt** [comment]
**QA OK**


tested on 24.7.3 and 24.8.1 app
imported in Bitcoin Send dialogue random address from blockbook via macbook camera
both times success

**Info:**
 - Suite version: desktop 24.7.3 (19fd64f5b2ab1bc265821e34d4c4b9c910864d0e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982

**Comment by evgenysl** [comment]
Tested also on ARM Mac Sonoma 14.6.1

Camera opened on iPhone by default and bitcoin address was populated from QR code without any issues.

Make sure Trezor Suite is allowed to access camera in Settings:

<img width="715" alt="Screenshot 2024-08-19 at 18 24 57" src="https://github.com/user-attachments/assets/416b0d6d-5482-4f45-887f-fae576b8b901">
