### ISSUE TITLE
Select & Modal overlap

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#13867]
## Describe the bug
When the Select and Modal components are active simultaneously, the Select menu overlaps the Modal.

## Info
The CSS property `z-index` is the same for both components. 

## How to reproduce
1. Create a Select component using `menuIsOpen` property.
2. Open a Modal when the Select options are opened. 

## Expected behavior
The Modal should appear in front of the Select option menu.

## Screenshots
![obrazek](https://github.com/user-attachments/assets/ca554542-a59f-4d71-8b9b-ca5fef7505d3)

**Comment by MiroslavProchazka** [comment]
cc @adamhavel as you are implementing the new modals, just sth to keep in mind. Thx

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.9.0 (b2ea3830e71db4f0e32a202fcaff2959b952a02a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32
