### ISSUE TITLE
XRP balance mismatch

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#13900]
Amount on Dashboard and Account detail shown including 10 XRP reserve, My assets, Receive and Select account shown without.

It has to be unified - the amount should always include those locked 10 XRP.

**Comment by STew790** [comment]
**Info**
XRP amount is unified across the app.

**Info**
24.11.3 https://github.com/trezor/trezor-suite/commit/6715904f662cf02dc22969ac659849b3a1b1a11b
