### ISSUE TITLE
Staking: In a nutshell expandable process copy

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#13912]
# Problem
Users are interested in staking Ethereum w/ Trezor but are unclear of the steps and the eventual where they stand in the process.

# Solution
Include staking and unstaking steps in the 'staking in a nutshell' modal

![Image](https://github.com/user-attachments/assets/72f38636-bd11-4713-87fe-20515b39a067)

![Image](https://github.com/user-attachments/assets/6e46aa65-2965-4f79-84e6-df6dba478389)

![Image](https://github.com/user-attachments/assets/551b87c9-be55-4577-ab43-f6aaf715f935)

**Comment by omykhailovskyi** [comment]
https://www.figma.com/design/0Kz3w6WDlvQm62RjOm87na/Staking?node-id=5274-26491&node-type=frame&t=58bYzpLYIFG3YAm3-0

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 24.10.0 (7a4ddc9a8137951fe69c7693d4ac9e70511a39b4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
