### ISSUE TITLE
Change the "All backends are down" error message to "Connection lost"

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#13913]
Please replace the "All backends are down" error message by "Connection lost". (instead of "Bitcoin: All backends are down" it should read "Bitcoin: Connection lost" etc. Please make sure it's translated to all Suite languages (it's not in Crowdin).

In most cases there are other reasons for not being able to reach backends than that they would be "down". User internet connection issues, rate limits etc.

Also please, if possible, hit automatically [Retry] once the connection has been re-established. As seen below, we can detect it, we remove the red banner when reconnected. Together with that, we should ideally Retry discovery instead of waiting for the user to do it manually.
![Image](https://github.com/user-attachments/assets/8d78b51e-d2f6-4dc2-a492-b386423e169c)
![Image](https://github.com/user-attachments/assets/656466fb-f517-489d-ae9a-d664df94fc1f)

**Comment by bosomt** [comment]
**QA OK**

`Connection lost` observed at dashboard


**Info:**
 - Suite version: web 24.9.0 (6cd1fdc8aff63b4c810d2b7e270dc298e392e775)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 3.0.0
