### ISSUE TITLE
Typo in TR_DEVICE_FIRMWARE_REVISION_CHECK_UNABLE_TO_PERFORM string

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13924]
**Describe the bug**

Please change vision to version.

  "TR_DEVICE_FIRMWARE_REVISION_CHECK_UNABLE_TO_PERFORM": "Firmware revision check couldn't be performed. Go online to verify your firmware vision.",

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: desktop 24.9.0 (d29b0f30de7cffd9f5a3ec5d937b5d7a1ce7aa23)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.9.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.2 regular (revision null)
 - Transport: BridgeTransport 2.0.32

**Comment by MiroslavProchazka** [comment]
Will be fixed by https://github.com/trezor/trezor-suite/pull/13952

**Comment by bosomt** [comment]
**QA OK**

`Firmware revision check couldn't be performed. Go online to verify your firmware version.`

**Info:**
 - Suite version: desktop 24.9.0 (6ba2bd1d277d1d354677f46e17bd3a5a2a03937e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.9.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.13.0 regular (revision null)
 - Transport: BridgeTransport 2.0.32
