### ISSUE TITLE
Staking: Earnings projections + steps

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#13939]
# Problem
1. Users are unaware of what can be expected as an earning projection with their staked Ethereum
2. Users are unclear where they stand in the staking process and how long it takes

# Solution

Compound interest tooltip: Your rewards are automatically restaked.

![Image](https://github.com/user-attachments/assets/96fe6079-154c-4682-b712-4e5d335ea264)

![Image](https://github.com/user-attachments/assets/687da019-6e50-457e-8aa5-c3c9a7b64ccb)

**Comment by omykhailovskyi** [comment]
https://www.figma.com/design/0Kz3w6WDlvQm62RjOm87na/Staking?node-id=5274-27824&node-type=frame&t=58bYzpLYIFG3YAm3-0

**Comment by omykhailovskyi** [comment]
Hey, @sime 
Seems we need also to add Expanded Once you confirm, right?
![Image](https://github.com/user-attachments/assets/53509918-0118-4c31-bfe5-06879ac410ca)
https://www.figma.com/design/0Kz3w6WDlvQm62RjOm87na/Staking?node-id=5366-27696&node-type=frame&t=H1BY5jovpJBAcwSS-0

**Comment by dev-pvl** [comment]
Hey, @sime 

Please clarify the default values for the gains section if the user doesn't input the amount yet. 

![Image](https://github.com/user-attachments/assets/46ec65fc-e67d-4909-9d4a-99b8261ea62f)

**Comment by dev-pvl** [comment]
Also, it's unclear where the compound interest link should lead. 

![Image](https://github.com/user-attachments/assets/f5069e6b-204f-4d4c-9a6a-6ab463b9a843)

**Comment by sime** [comment]
@dev-pvl Link. https://trezor.io/learn/a/stake-ethereum-eth-in-trezor-suite

**Comment by sime** [comment]
@dev-pvl Please blank the values when the input is zero. i.e. not to show 0.00 ETH, just an empty space.

**Comment by omykhailovskyi** [comment]
Hey, @sime 
Please confirm which option we choose
Option 1 (0 value)
![Image](https://github.com/user-attachments/assets/9f745452-df0e-4e29-958c-5e98b51b29cb)

Option 2 (remove values at all)
![Image](https://github.com/user-attachments/assets/7a47a310-e85c-4407-9035-95ca07553a39)

Option 3 (remove including lables)
![Image](https://github.com/user-attachments/assets/93e9c229-175e-4c88-bab0-d2043276fac0)

Option 4 (remove including values and space) - don't recommend, as it will blink after user entered values
![Image](https://github.com/user-attachments/assets/36134a00-113a-40b3-9d56-7e7aa39c9c67)

**Comment by sime** [comment]
@omykhailovskyi option 1. 0 value, because of no layout shift and the placeholder of 0 help with visual continuity.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
