### ISSUE TITLE
Staking: Unstaking steps in modal

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#13940]
# Problem
Users miss that unstaking has multiple steps (i.e. pay multiple network fees)

# Solution

![Image](https://github.com/user-attachments/assets/adf63c8f-3d05-42a0-8d49-6a9d438e6711)

**Comment by omykhailovskyi** [comment]
Hey, @sime 
Please check, seems wrong picture in the task
![Image](https://github.com/user-attachments/assets/65702b0a-0cf6-4512-ac42-a69101bb94d5)

https://www.figma.com/design/0Kz3w6WDlvQm62RjOm87na/Staking?node-id=5937-28223&node-type=frame&t=H1BY5jovpJBAcwSS-0

**Comment by omykhailovskyi** [comment]
Drop "You’ll pay another network fee when claiming. Why?"

**Comment by sime** [comment]
Blocked by #13939

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/7129c6e0-f291-4ab4-b1f9-3160758238d5)

![Image](https://github.com/user-attachments/assets/b8706b0a-b18c-4d72-ad1c-820905d8a391)

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
