### ISSUE TITLE
Staking: Instant stake notification eye grabbing visual update

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#13941]
# Problem
User miss/glance over that their investment (or partial investment) was stake immediately. 

# Solution
![Image](https://github.com/user-attachments/assets/ceb891bc-eead-4489-b51a-03c18a86d65f)

**Comment by omykhailovskyi** [comment]
@dev-pvl 
Task only for visual representation of notification to the end user
Related to [issue](https://github.com/trezor/trezor-suite/issues/12047) which already consist of the logic and already live

FYI @sime , @tomasklim

**Comment by omykhailovskyi** [comment]
Hey, @sime 
Should we also change the representation for instant unstake success?
Reference to the [issue](https://github.com/trezor/trezor-suite/issues/11406)

**Comment by omykhailovskyi** [comment]
@tomasklim CC

**Comment by omykhailovskyi** [comment]
@dev-pvl 
Need to cover both Instant stake success and Instant unstake success as part of the implementation
https://www.figma.com/design/ylfHUP23P94yZPcVTiPTZ6/ETH-Staking?node-id=207-2843&node-type=frame&t=EpSl2d9TqzKTCxgE-0

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 24.10.0 (3e1d4dff6ceb7a96cff59c4d15d223b0802366ca)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.0
