### ISSUE TITLE
Mobile - bug in discovery

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13954]
**Describe the bug**

If Cardano is enabled (default state for everyone) for device with unsupported derivation, this one is not included into the count for started discovery, but `createDescriptorPreloadedDiscoveryThunk` is being run for it. This can cause count being off by 1 in `finishNetworkTypeDiscoveryThunk`, meaning that the discovery will end before the last network is being discovered.

**How to reproduce**

1. enable Coin Enabling in dev settings and connect model T
2. enable Cardano
3. go to dashboard and wait for the discovery to finish
4. go to settings and enable Dash 
5. Dash is never discovered

https://github.com/user-attachments/assets/0d55c810-e6e3-4885-938e-cf22f9cca92e

**Expected behavior**

All networks are discovered

**Comment by STew790** [comment]
**QA OK**
Discovery gets finished correctly after enabling another coin after Cardano.

**Info**
24.8.2 d19acd1
