### ISSUE TITLE
Write the library for address validation

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#1396]

**Comment by prusnak** [comment]
We already have this:

* https://github.com/trezor/trezor-address-validator
* https://www.npmjs.com/package/trezor-address-validator

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.7.1 (24cc565a3badd85ab48b30348022471dfd85f90e)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.2 regular
