### ISSUE TITLE
Coin Enabling - when network is not enabled, it deletes portfolio tracker accounts

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#13986]
**Describe the bug**
When network is disabled, it wrongly removes accounts of that network also for portfolio tracker. Those accounts should not be touched by Coin enabling setup.

**How to reproduce**

1. Go to portfolio tracker, add ethereum
2. Enable coin enabling
3. go to settings - coin enablling
4. have disabled ethereum
5. go back to dashboard and eth accounts are gone (actually accounts for all not enabled networks)

**Expected behavior**
Portfolio tracker should not be influenced at all by coin enabling

**Comment by STew790** [comment]
**QA OK**
If I remove a coin that I have in portfolio, it correctly stays in portfolio.

**Info:**
24.9.1 https://github.com/trezor/trezor-suite/commit/bf893a5e0f152087cb4e47a4921a64c3c4c1624f
