### ISSUE TITLE
ETH show negative balance

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#13988]
**Describe the bug**
ETH can't have negative balance, but Suite Lite show negative value on allall seed.

It is not affecting all accounts, just some.

Both portfolio tracker and connected device.

This PR might be relevant https://github.com/trezor/trezor-suite/pull/10481

**Info:**

-   Mobile Suite Version: 24.8.2 - DEVELOP so far - we don't have it reported from production version
-   OS: both

**How to reproduce**

1. Discover ETH on allall seed
1. Check the balance

**Expected behavior**
We should always see the accurate balance value.

**Screenshots**
<img width="375" alt="image" src="https://github.com/user-attachments/assets/d6fb50d0-556a-45f4-9ef6-12e933db08b9">

**Comment by matejkriz** [comment]
I believe it has been fixed by recent changes from @Nodonisko, please check it @STew790

**Comment by STew790** [comment]
**QA OK**
Ok on address `0x73d0385F4d8E00C5e6504C6030F47BF6212736A8`
![image](https://github.com/user-attachments/assets/8ffec110-5ce1-4d7f-a1d6-38c9fbafff5d)

**Info:**

24.9.1 9ff8920
