### ISSUE TITLE
Silent Update - UI

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#13990]
Figma: https://www.figma.com/design/d8Ekwm865R3YR6PtH4gdyc/Auto-update?node-id=4083-20734&t=D2t4VMq29llhHKn3-1

- [x] Legacy Icons refactoring
- [x] Icons (QuickActions)
- [x] Icon with corner Icon component
- [x] Update Icons (to display FW and Suite update state)
- [x] Tooltip Update Only
- [x] Update Tooltip on WEB (what to do on Web? hide the Suite part?)
- [x] Update Icon is clickable 
- [x] Tooltips
- [x] Implement update mini-popup-banner (there are many states see figma)
![image](https://github.com/user-attachments/assets/e76daec7-bb43-4d67-ae0d-199ddb62e49d)
![image](https://github.com/user-attachments/assets/af557c76-a1af-4429-8b76-a4e69a7b97eb)
- [x] Click on mini-popup-banner "Just updated" will lead to changelog
- [x] Implement new Update Modals (should be probably new Issue, its a big stuff)
- [x] App (Suite) "Whats new"  click works to show changelog
- [x] remove it from experimental features

**Comment by bosomt** [comment]
QA task here https://www.notion.so/satoshilabs/Silent-update-11fdc526060680a0b7c2f11c5d999c98#11fdc526060681bb9a60d1fc55b6bcec

**Comment by bosomt** [comment]
**QA OK**

sanity tests for multiple platforms ok, if anything raises we will create separate issue
 - Suite version: desktop 24.11.1 (9e9dadff47c5243bf4a10f539a898fe48da46506)
