### ISSUE TITLE
Trezor Model One bricked after firmware update from 1.11.1 to 1.11.2

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#13999]
Trezor Model One seems to be bricked after update.

Setup

After a long time downloaded latest version of Trezor Suite: Version 24.7.3 (24.7.3)
Connect Trezor Model One and check the ballance
Notice that update is available
Perform update following instructions
Update performed
Trezor suite ask to unplug and plug the Trezor without holding any button. While the picture next to clearly shows hand pressing a button while plugging a Trezor device. Very strange.
Plugging and unplugging device
Trezor suite continues to show the same message to plug and plug device
Trezor Model One device does not show anything on the screen nor is recognized by macos
System

macos
Trezor Suite: Version 24.7.3 (24.7.3)
connected with original USB cable
Issue

Trezor Model One does not connect in Trezor Suite.
Trezor is not recognized by macos
Observation

Changing USB cables does not help
Trying on different computer does not help
Linux command lsusb does not show any output when connecting
Trezor is drawing some current when connecting to powerbanks. I am not able to measure it as now.
Not able to reset Trezor without first successfully connecting in Trezor Suite.
1.11.2 is a patch update. Nothing significant.
Info

Old firmware: Go to github org trezor and trezor-firmware repo. There go to directory legacy and firmware. Here you find a CHANGELOG.md#1111-18th-may-2022 (no links allowed in this post)
New firmware CHANGELOG.md#1112-17th-august-2022
With this post I wonder is there anything else I can try to awake Trezor Model One. Also I wonder if anybody else has similar issue.

**Comment by MiroslavProchazka** [comment]
@trezor/qa please test the update flow and observe if this is true 

> "Trezor suite ask to unplug and plug the Trezor without holding any button. While the picture next to clearly shows hand pressing a button while plugging a Trezor device. Very strange."

**Comment by bosomt** [comment]
@MiroslavProchazka 
- see video https://youtu.be/8sUmt-IVmPY
- device was not bricked
- probably during installation there was intermediary firmware installed as i see install progress bar running twice

**Info:**
 - Suite version: desktop 24.8.3 (054258687669f8ac2d1bcbd002e96bf5cba9a403)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.32
