### ISSUE TITLE
Cannot run android app

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#14]
Looks like I don't have correct SDK path?

![image](https://user-images.githubusercontent.com/3112191/57623655-7fb7c080-7590-11e9-99f0-0a4c62877e19.png)

**Comment by slowbackspace** [comment]
have you followed installation instructions for the android sdk? 
```
Add the following lines to your $HOME/.bash_profile config file:

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
```
https://facebook.github.io/react-native/docs/getting-started#2-install-the-android-sdk
