### ISSUE TITLE
Create notification button

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#1400]
We use the tertiary button for notifications. 
![image](https://user-images.githubusercontent.com/3112191/77765930-3e60c000-703f-11ea-8baa-0b5b374d1167.png)

**Comment by vladimirvolek** [comment]
![image](https://user-images.githubusercontent.com/3112191/78572776-2d2a6700-7828-11ea-8254-7bc7963cdab4.png)

**Comment by glacierbits** [comment]
Solved by #1632
