### ISSUE TITLE
After removing colors from buttons its immediately not clear if its active or not

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14029]
**Describe the bug**
After removing colors from buttons its immediately not clear if its active or not.
See screenshots before and current version.

See third screenshot. Some buttons are still not monochrome so its inconsistency.

**Info:**
 - Suite version: web 24.9.0 (c63f73cc9cb1c714b31ed58c29500b0500c87725)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.2 regular (revision 9e18e72a2c7896cbcce1df4c2d908eab0f01564f)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

**NOW**
<img width="858" alt="image" src="https://github.com/user-attachments/assets/cf6b9daa-b57e-4fe5-a360-c2bca185be3a">

**YESTERDAY**
<img width="813" alt="image" src="https://github.com/user-attachments/assets/92f828dd-4244-408a-958a-45a8c9175aa4">

**NOW**
<img width="815" alt="image" src="https://github.com/user-attachments/assets/c8a0b9ef-71e5-4097-be09-3cfe0b8d9bbd">

**Comment by MiroslavProchazka** [comment]
Should be fixed in develop

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (49b5ea90d92e6650f8a1cbdadc7b3e3371df4eae)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: WebUsbTransport
