### ISSUE TITLE
Fiat label - indicate values less than zero

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#1402]
This is not true.
![image](https://user-images.githubusercontent.com/3112191/77783073-85a77a80-7058-11ea-83e3-e7a0f0cf665a.png)

**Comment by slowbackspace** [comment]
maybe "~" character before could be enough? or something like tooltip on hover with the exact amount?

**Comment by tsusanka** [comment]
I think we can live with this as it is very edge-casy.
