### ISSUE TITLE
Import sorting

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#14031]
I really like when imports are sorted since you know what are you importing from libraries, files etc. This makes even more sense to our repo because we would be able to differentiate imports from external libraries, `@trezor` packages, `@suite-common` packages, `@suite-native` packages and files. To what and how many groups we will divide imports is for sure open for a discussion.

There are multiple tools for import sorting that work nicely out of the box (for example [this one](https://github.com/lydell/eslint-plugin-simple-import-sort)).

```js
// 🔴 not that clean
import { decode, verify } from 'jws';
import { jws as configJwsLocal } from '../files/config.v1';
import { ACTION_PREFIX, messageSystemActions } from './messageSystemActions';
import { getJWSPublicKey, isCodesignBuild, isNative } from '@trezor/env-utils';
import { memoize, memoizeWithArgs } from 'proxy-memoize';

// 🟢 nice and clean
import { decode, verify } from 'jws';
import { memoize, memoizeWithArgs } from 'proxy-memoize';

import { getJWSPublicKey, isCodesignBuild, isNative } from '@trezor/env-utils';

import { jws as configJwsLocal } from '../files/config.v1';
import { ACTION_PREFIX, messageSystemActions } from './messageSystemActions';
```

**Comment by Nodonisko** [comment]
This is already enabled in most of repo, it's only disabled for `package/suite` here https://vscode.dev/github/trezor/trezor-suite/blob/feat/flashlist-bottom-sheet/.eslintrc.js#L346

Feel free to enable it for everything.
