### ISSUE TITLE
connect-explorer - icons - console.error

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#14052]
caught by CI https://github.com/trezor/trezor-suite/actions/runs/10658520617

likely introduced by the recent changes in icons by @jvaclavik? 

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/70ca606c-3439-4fbf-8e10-a3d71f7ae246">

**Comment by evgenysl** [comment]
I don't see this error on production now
![Screenshot 2024-09-05 at 14 11 45](https://github.com/user-attachments/assets/9ee3689a-c29e-425f-9da7-1ec1c10c5854)
