### ISSUE TITLE
Trezor Suite fails to start on Ubuntu 24.04.1 LTS -  The SUID sandbox helper binary was found, but is not configured correctly. Rather than...

### ISSUE THREAD

**Issue by filipponeri** [trezor/trezor-suite#14051]
Dear Developers,

Trezor Suite fails to start when launched from the command line on Ubuntu 24.04.1 LTS producing the following error:

>   ./Trezor-Suite-24.6.2-linux-x86_64.AppImage 
[260139:0901/210644.259196:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_TrezorA5Ct6S/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)

**Partially Solved**

launching Trezor Suite from the graphical interface (Files app in the Dash bar )  works without errors

Thank you for you attention. Kind regards

**Comment by MiroslavProchazka** [comment]
Hello, 
have you tried to open the app with the "`--no-sandbox`" flag?

**Comment by MiroslavProchazka** [comment]
Closing due to the inactivity.

**Comment by PavelNiedoba** [comment]
having same problem, tried to create folder  chrome sandbox owned by root, but next run it wants folder with different suffix, it's on 
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble

Trezor-Suite-24.9.2-linux-x86_64.AppImage

**Comment by PavelNiedoba** [comment]
I fixed it by following https://github.com/electron/electron/issues/42510

one liner: 

`sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0`

**Comment by filipponeri** [comment]
thank you! @PavelNiedoba

**Comment by PavelNiedoba** [comment]
the problem is coming back with every update @MiroslavProchazka , consider reopening
