### ISSUE TITLE
Make the button "Confirm" in syncing coins sticky to the bottom of the screen

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#14065]
When user wants to sync coin with tokens, button with Confirming it is hidden at the bottom and user must scroll. 
Please change the behaviour so that it is more accessible for users. 

Acceptance criteria:
When user syncs the coin with and is on the page where the coin must be confirmed. Button "Confirm" is sticked to the bottom of the screen so that it's always accessible for the user.

**Comment by STew790** [comment]
**QA OK**
Button is sticky

**Info**
24.10.2 https://github.com/trezor/trezor-suite/commit/e4365278aa8be68324c41f57fa796f9b4ee631f9
