### ISSUE TITLE
Send coins - validation of fiat input

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#14071]
###  Current behaviour
- if user starts filling fiat input without touching the crypto input before, the value is not validated.

### Steps to reproduce
1. enter empty send form
2. change value input to fiat
3. start filling the value
4. see that there is no warning about value below the dust limit or higher the balance warning

https://github.com/user-attachments/assets/7a30365b-18e6-4b05-a0ae-459252787204

### Expected behaviour
When user changes the fiat value, the input is always validated

**Comment by STew790** [comment]
**QA OK**
Validation is OK now for fiat as well.

**Info:**
24.9.1 bf893a5
