### ISSUE TITLE
Incorrect hint in receive section

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14084]
**Describe the bug**
`Your device may have been compromised. Do not send funds to it.` message as hint when revealing receive address with legit device

**Steps to reproduce:**
1. Navigate to receive section
2. Reveal address
3. Observe hint

**Info:**
 - Suite version: web 24.9.0 (983e42f2cc2f6fb51463a26c7f6206c4f56a3d14)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/user-attachments/assets/60c65325-98a7-4fa2-86a3-1c5caa08f566

**Comment by bosomt** [comment]
Did the fix made it to 24.9.1 release candidate ?
I just added fresh account and im not able to generate receive address ;(
I have new firmware that is not known to Suite but i disabled both device checks



![Image](https://github.com/user-attachments/assets/20b840e1-a39e-4ab1-a125-b93c4799431b)



![Image](https://github.com/user-attachments/assets/506ddeed-72e3-43c1-96b1-bd46ca78e2a7)



**Info:**
 - Suite version: desktop 24.9.1 (ce0f589a4863ec711ca3f0e5677accb2d0c06cd2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision d7e1f0faf3ab8753dfd9dc292b503dff39fd81db)
 - Transport: BridgeTransport 3.0.0

**Comment by MiroslavProchazka** [comment]
Does it work on develop?

**Comment by bosomt** [comment]
**QA NOK**

no its not yet fixed on develop

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/0cbccc0b-9a53-465f-9ec3-c40442edff94">

**Info:**
 - Suite version: web 24.10.0 (09e8213d0c5e7ab2c88931ea7fe196082840f716)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision d7e1f0faf3ab8753dfd9dc292b503dff39fd81db)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (daaa8fbf65858a99b6a43ff77238b3749de98eb6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
