### ISSUE TITLE
Wrong position of Retrieving balances title when loading

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#14090]
Reported by @shenkys:
 
~~- [ ] Last network has wrong balance on dashboard (zero)~~ moved to separate issue https://github.com/trezor/trezor-suite/issues/14177
- [ ] While discovery is running, text Retrieving balances is too close to bottom edge (was not previously)

**Screenshots**
<img width=280 src="https://github.com/user-attachments/assets/ba0385ac-3614-4b01-8fc7-4c581711902b" /><img width=280 src="https://github.com/user-attachments/assets/2450b1e2-b378-4ea0-9c31-771b88eadb7b" />

**Comment by matejkriz** [comment]
I don't think the line break issue is always only on the last network, I think it can be for any network with 0.00 balance no matter the position.

**Comment by matejkriz** [comment]
note for Dev - think about potential conflicts with https://github.com/trezor/trezor-suite/pull/14072 and communicate if there are any

**Comment by STew790** [comment]
**QA OK**
Looks good now.

**Info:**

24.9.1  https://github.com/trezor/trezor-suite/commit/9ff8920814b8616034ab7375d1b6dbf9b5ec65ab
