### ISSUE TITLE
Split Trade button and rename Exchange to Swap

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14103]
## Description
To follow industry standards where most self-custody wallets call coin-to-coin exchange a “swap”. Additionally, in testing, we saw a significant uplift in confidence and easier-to-find trade features when the navigation buttons were separate for fiat-crypto and coin-to-coin operations.
Add also an analytics event on Swap - `wallet-coinmarket-exchange` (`accounts/actions`)

## Solution
- Account detail - header: Split Trade button into “Buy & Sell” (it will lead to the Buy tab) and “Swap” (it will lead to the former Exchange tab)
- Account detail - trade box: Rename Exchange for Swap
- Trade screen tabs: Rename Exchange for Swap
- Rename input and transaction labels
- Update modal content for CEX and DEX

### Split buttons
![image](https://github.com/user-attachments/assets/96a1b3bf-2d7e-4722-934a-89428f957e0d)
### Replaced button title from `Exchange` to `Swap`
![image](https://github.com/user-attachments/assets/6e2ebe3e-1a1b-4089-948a-dac049e39254)
### Replaced label from `Exchange amount` to `Swap amount`
![image](https://github.com/user-attachments/assets/48f473b6-7392-4c92-9dc8-7c9cd43de756)
### Replaced tab title from `Exchange` to `Swap` and updated icon
![image](https://github.com/user-attachments/assets/a11e67c4-1cf3-472b-8925-25489e7d9f21)
### Replaced `Exchange` button title with `Swap`
![image](https://github.com/user-attachments/assets/12e6058f-a9a5-4adb-816d-225d4708b8fa)
### Replaced `exchange` strings with `swap` (CEX)
![image](https://github.com/user-attachments/assets/6d0cedf9-b3aa-4ffb-9cde-2952caba118e)
### Replaced `exchange` strings with `swap` (DEX)
![image](https://github.com/user-attachments/assets/5b57e5be-56d3-4a82-8583-21fef1534f77)
### Replaced `Exchange` label with `Swap` (DEX)
![image](https://github.com/user-attachments/assets/c0d54206-35cc-411d-8368-0a45374fced8)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.10.0 (d48f1d337c96e29fad684a19fbb55bd842b9df74)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.0
