### ISSUE TITLE
Coinmarket - Rate related issues

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14111]
## Description
1. _Tokens_ - an issue with validating the maximum balance on the account (Enter amount in USD)

2. _Tokens_ - wrong calculation of fiat amount (Enter amount in USDT)
Screen for 1st and 2nd issues
![image](https://github.com/user-attachments/assets/d6b5c352-0248-4f0f-bcbc-beb5ea16c3e4)

3. Visible balances in the "Hide balances" mode - should be hidden
![image](https://github.com/user-attachments/assets/d6a56d88-ca37-450b-ba44-bdedcd499c25)

4. Calculation btc to fiat in sat mode
![image](https://github.com/user-attachments/assets/2fe695ba-170d-4433-9d80-b69170d00e49)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.10.0 (e7305b93f2e0c62c2c2d9f7b7a34db05ad903824)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport
