### ISSUE TITLE
Polygon - add BNB Feature Flag to better test EVM related changes

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#14116]
- [x] Add feature flag
- [x] Allow discovery on enabled BNB
- [x] Notify QA, to put sanity checks for not visible BNB while not enabled

**Comment by STew790** [comment]
**QA OK**
BNB is behind a feature flag. After enabling it, I am able to do a discovery on BNB.

**Info**
24.9.2 https://github.com/trezor/trezor-suite/commit/b718af4a2b5d9fde28e1832276405f36a1c2399b
