### ISSUE TITLE
Highlight of account drop-down button is too big

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#14118]
**Describe the bug**
Highlight of the drop-down button for accounts is a little too big and almost overlaps the account type name.

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: desktop 24.9.1 (ce0f589a4863ec711ca3f0e5677accb2d0c06cd2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.2 regular (revision d7e1f0faf3ab8753dfd9dc292b503dff39fd81db)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/user-attachments/assets/f602dcb8-f2e3-4322-93d1-bc43347a31ab)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (daaa8fbf65858a99b6a43ff77238b3749de98eb6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
