### ISSUE TITLE
Spike: Check the flakiness of our E2E tests

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#14117]
Android E2E tests are not stable, failing from time to time for no obvious reason. 

Nightly: https://github.com/trezor/trezor-suite/pull/12630

**Comment by komret** [comment]
Some of my recent fails:

https://github.com/trezor/trezor-suite/actions/runs/10665429295/attempts/1
https://github.com/trezor/trezor-suite/actions/runs/10632558852
https://github.com/trezor/trezor-suite/actions/runs/10616016089
https://github.com/trezor/trezor-suite/actions/runs/10594575772/attempts/1
https://github.com/trezor/trezor-suite/actions/runs/10525596559

**Comment by jvaclavik** [comment]
maybe this one https://github.com/trezor/trezor-suite/actions/runs/10698542969/job/29659273802?pr=14089

**Comment by Lemonexe** [comment]
Two times I've got the same as @jvaclavik, on third rerun I've got a different one
https://github.com/trezor/trezor-suite/actions/runs/10697608810/job/29663701700

**Comment by matejkriz** [comment]
Let's close this one now, it's more stable. We can create another spike once we get to it.
