### ISSUE TITLE
Coinmarket - bad crypto ticker in limits message

### ISSUE THREAD

**Issue by FreeWall** [trezor/trezor-suite#14114]
## Description
There should be symbol (USDT) instead of crypto id

![image](https://github.com/user-attachments/assets/c625c2e9-ab6f-4088-a558-4a8563002de1)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (5f021c81121297dd3c008afecc4c1818db06575a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
