### ISSUE TITLE
Coinmarket - Network tags are not showing for all the networks, only Ethereum

### ISSUE THREAD

**Issue by FreeWall** [trezor/trezor-suite#14129]
## Description
Network tags are not showing for all the networks in dropdown in trade section, only Ethereum

![image](https://github.com/user-attachments/assets/78e55888-3665-42ee-b633-ffae3e2dfbc0)
![image](https://github.com/user-attachments/assets/2d935753-5039-4ffa-9d84-bba76205888d)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (0703febd9141b491eb914ca8c486fecd781aceab)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
