### ISSUE TITLE
Coinmarket - update receive select

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14133]
## Issue
1. Select the default cryptocurrency in `To` input
the default is BTC if you select ETH account - BTC will select

2. Update `To` input on `From` change
If you select the same value in the 'From' dropdown as in the 'To' dropdown, the 'To' dropdown will be updated according to the condition above.

3. Select options re-render fix

### Before
![image](https://github.com/user-attachments/assets/de068b0c-2dce-46d8-b246-a258a6844ce2)

### After
![image](https://github.com/user-attachments/assets/829ca2a7-2083-42e2-8070-7c4a44e4aeae)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (f27b837e5934625c5aae63c08d39ed4b1b2ea9fa)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport
