### ISSUE TITLE
Coinmarket - Fix DCA icons thickness

### ISSUE THREAD

**Issue by salax** [trezor/trezor-suite#14135]
## Issue

Before merging of https://github.com/trezor/trezor-suite/pull/13772 there were changes in other icons thickness so now they are of different weight.

## Now

<img width="60" alt="Screenshot 2024-09-04 at 18 05 23" src="https://github.com/user-attachments/assets/25de8e3a-6ec9-43f3-a006-f6e644ad89ba">

## Desired after

<img width="60" alt="Screenshot 2024-09-04 at 18 05 59" src="https://github.com/user-attachments/assets/fdf04041-7306-4423-84d6-c0568ee346f0">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (5f021c81121297dd3c008afecc4c1818db06575a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
