### ISSUE TITLE
Coinmarket - Featured offers wrong receive amount

### ISSUE THREAD

**Issue by LukasRada** [trezor/trezor-suite#14132]
**Describe the bug**
Featured offers show wrong receive amount

**How to reproduce**

1. Go to Bitcoin trade section
1. Fill out 100 EUR to buy
1. Wait till featured offers load
1. See wrong amount in featured offers

**Expected behavior**
Featured offers show wrong receive amount

**Screenshots**
![image](https://github.com/user-attachments/assets/0c43d994-94af-433e-8f2f-a37dcf33ab03)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (0703febd9141b491eb914ca8c486fecd781aceab)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
