### ISSUE TITLE
Coinmarket - sllipage tolerance not changable

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14142]
## Issue
It is not possible to change _Slippage tolerance_ and errors are in the console

## Expected behavior
To change _Slippage tolerance_ without console errors

## How to reproduce
1. Go to Trade - Exchange
2. Choose `From` ETH and `To` some `ETH` token to get DEX offers
3. Select DEX on the right side
4. Click on Exchange
![image](https://github.com/user-attachments/assets/f8ba4511-c68a-4002-bcba-e9810168a104)

##  Screenshots 
![image](https://github.com/user-attachments/assets/31da4efd-e304-4665-94c5-09c274083db5)
![image](https://github.com/user-attachments/assets/704f2da4-a75a-43e0-a851-1764e460a93c)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (f27b837e5934625c5aae63c08d39ed4b1b2ea9fa)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: WebUsbTransport
