### ISSUE TITLE
Coinmarket - design for no offers available

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14146]
## Describe the bug
Small font size and separate text on two lines

## Design before
![image](https://github.com/user-attachments/assets/54369f4f-debe-4749-9ae4-7c64b5f44fa0)

## Design after
![image](https://github.com/user-attachments/assets/ce498882-d77e-4c89-b41d-b939cc932461)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.9.1 (921f579006bed33b0c5fbb10a70874035bb89fa9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
