### ISSUE TITLE
Coinmarket - incomplete list in the exchange comparator 

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14144]
## Describe the bug
Floating quotes and DEX are separated.

## Expected behavior
There should be only two lists of quotes at all - **fixed** and **floating** list of quotes. Fixed quotes will remain unchanged, while floating quotes will be unified with the DEX.

## How to reproduce
1. Go to Trade - Exchange
2. Choose `From` ETH and `To` some `ETH` token to get DEX offers
3. Select __Compare all offers__
![image](https://github.com/user-attachments/assets/f8ba4511-c68a-4002-bcba-e9810168a104)

## Design after (quotes after - first quote DEX and then other floating quotes)
![image](https://github.com/user-attachments/assets/63cd8fa2-13ca-43b4-a8b0-3bafd317a845)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.10.0 (92bc40e2b5ae19333075af50099a0f56b48bc8b1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
