### ISSUE TITLE
Token missing from Solana wallet

### ISSUE THREAD

**Issue by jakejackyll** [trezor/trezor-suite#14140]
**Describe the bug**
Token missing from Solana wallet (can see it on solscan).

**Info:**

-   Remembered Wallet: yes
-   Suite Version: app v24.8.3 on linux
-   Browser: app, no browser
-   OS: Fedora 40
-   Bridge: bridge is fine
-   Firmware Version: up to date

**How to reproduce**

Have a token of this type in your wallet, for example:
https://solscan.io/token/7atgF8KQo4wJrD5ATGX7t1V2zVvykPJbFfNeVf1icFv1
Can't be seen in suite, can be seen on solscan.
Maybe something about "Token Program" vs. "Token 2022 Program".

**Expected behavior**
Also see "Token 2022 Program" tokens in suite.

**Comment by Hannsek** [comment]
We currently do not display Token 2022 in Suite. We have it planned.
