### ISSUE TITLE
Coinmarket - missing cryptocurrency

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14147]
## Design before
![image](https://github.com/user-attachments/assets/4b2cc332-db2a-43fa-8a09-126f86f07aa8)

## Design after
![image](https://github.com/user-attachments/assets/f471278f-b244-4cac-8881-aa044aefb6e9)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (f27b837e5934625c5aae63c08d39ed4b1b2ea9fa)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport
