### ISSUE TITLE
Coinmarket - Slippage summary shows network and contract

### ISSUE THREAD

**Issue by LukasRada** [trezor/trezor-suite#14156]
**Describe the bug**
Slippage summary shows network and contract. We should see the correct name of receiving token.

**How to reproduce**

1. Go to Exchange/Swap
1. Select Ethereum account as from and ENA as to
1. Choose DEX with 1inch
1. Confirm receiving address
2. Create approval
3. See `Slippage summary`

**Expected behavior**
We should see the correct name of receiving token.

**Screenshots**
![image](https://github.com/user-attachments/assets/f32e04cc-2c1b-48f4-9144-fb6fd10b4d6d)

**Comment by bosomt** [comment]
**QA OK**

<img width="670" alt="image" src="https://github.com/user-attachments/assets/a9f4065f-12bf-4afa-a30f-bdc790d43035">

**Info:**
 - Suite version: web 24.10.0 (f27b837e5934625c5aae63c08d39ed4b1b2ea9fa)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: WebUsbTransport
