### ISSUE TITLE
Transaction details: Update

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1415]
**[Zeplin](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5e66552a25009b15b79e9aaf)**

**Comment by bosomt** [comment]
I think that historic values are broken 

![image](https://user-images.githubusercontent.com/31506317/78751753-1b090f80-7973-11ea-9915-cddd973ad55a.png)

**Comment by bosomt** [comment]
solved
