### ISSUE TITLE
Coinmarket - Add transaction event when user confirms trade

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14157]
## Description
```
{
  c_v=23.11.0&
  c_type=trade/confirm-trade&
  c_commit=9745dbb7a78674007258f39cfa144dfdcd8aeb59&
  c_instance_id=Z04wNMyHlf&
  c_session_id=Z7qeBw8mBM&
  c_timestamp=1698763630371&
  c_message_id=kXxNerHCt2&
  type=sell
}
```
- `c_type` - `trade/confirm-trade`
- `type` - `buy|sell|exchange` - depending on which flow (exchange remains as an exchange for swap flow, to be consistent with other events)
- should be only triggered when user-approved analytics consent

### Trigger
- When a user clicks on “Finish transaction” button in Buy, Sell or Swap flow regardless of API response.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (a9eaedc0a7d3470b05d4299ca4bc661d3732c7db)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: WebUsbTransport
