### ISSUE TITLE
Coinmarket - timer is below 0s in Exchange

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14151]
## Describe the bug
[Screencast from 2024-09-05 12-59-31.webm](https://github.com/user-attachments/assets/adb1f670-fbe2-4b84-8a10-5d7dc683af93)

## How to reproduce
1. Go to Trade - Exchange
2. Choose `From` ETH and `To` some ETH token to get DEX offers
3. Select Compare all offers

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.9.1 (921f579006bed33b0c5fbb10a70874035bb89fa9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
