### ISSUE TITLE
`Button` ignores `frameProps`

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#14159]
`Button` accepts `minHeight` etc. but doesn't use it and propagates it to the DOM.

![Screenshot 2024-09-05 at 16 16 56](https://github.com/user-attachments/assets/6fbaf718-754f-4aeb-b1ee-c20b76deaec3)

**Comment by marekrjpolak** [comment]
Related to #14148?

**Comment by MiroslavProchazka** [comment]
Should be fixed in develop
