### ISSUE TITLE
Wrong line break of fiat values on dashboard

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#14177]
- Spotted so far only on Android
- Already in production
- With smallest system font scale it's "fixed"
- Only some values are broken, 0.00, but also for example $5.35

<img width="400" alt="image" src="https://github.com/user-attachments/assets/df25fea2-a7f6-42dc-9127-66a480b005a1">
<img width="400" alt="image" src="https://github.com/user-attachments/assets/f04fadb0-e25d-4da6-b2b0-32b0f964164d">
<img width="400" alt="image" src="https://github.com/user-attachments/assets/563f0238-ffca-4ba6-bf1c-effd25256ef5">

**Comment by matejkriz** [comment]
Probably related to https://github.com/facebook/react-native/issues/35039

If I remove either `maxFontSizeMultiplier` or `letterSpacing`, the issue is resolved.

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/44bf4894-c2e6-4199-8077-efa0424f9327)

**Info**

24.9.1 306d448
