### ISSUE TITLE
Coinmarket - app crashing

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14172]
## Description
https://github.com/user-attachments/assets/c04737f5-77f6-455c-b791-99d2b7a0c748

### 1. Prerequisite
1. Reset the app for clean storage
2. Discovery at least two different accounts (BTC, ETH for DEX)
### 2. Select BTC account
1. Select **BTC** account
2. Go to **Trade** section
3. Go to **Exchange**
4. Select `From` some ETH token
5. Select `To` ETH
6. Click on **Exchange**
7. Click on **Confirm on Trezor**
8. Click on **Finish transaction** -> will work

### 3. Select ETH account
1. Select **ETH** account
2. Go to **Trade** section
3. Go to **Exchange**
4. Select `From` some ETH token
5. Select `To` ETH
6. Click on **Exchange**
7. Click on **Confirm on Trezor**
8. Click on **Finish transaction**  -> `app will crash`

## Additional related issues
- also issue with double request after **Finish transaction**
![image](https://github.com/user-attachments/assets/da8fa81e-b8c4-4577-8051-cc0825c70c25)

- overriding the redux object will trigger errors in the console
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/55363699-9554-458f-921b-c7f1a4ef416b">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (ea069c398862907b1ae3fc12fb0c9a2d6d5a3e6e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport
