### ISSUE TITLE
Coinmarket - Unexpected text when exchanging to coin that is not currently enabled 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14182]
**Describe the bug**
Unexpected text when exchanging to coin that is not currently enabled 

**Steps to reproduce:**
1. Navigate to exchange section 
2. Select funded account as input
3. Select disabled coin as output
4. Observe text

**Info:**
 - Suite version: web 24.10.0 (a85f6b6ce96920a8e4cb66ccffb36dba6e25a606)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="713" alt="image" src="https://github.com/user-attachments/assets/bfd3c9bc-665e-4a3d-a7c8-90667b528837">

**Comment by tomasklim** [comment]
I think it is related also to this https://satoshilabs.slack.com/archives/C04DD84P4A1/p1725546798097659?thread_ts=1725545584.820709&cid=C04DD84P4A1

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.10.0 (acd58e6c26394eb09907791dd4006d03c130fe65)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
