### ISSUE TITLE
Polygon - Make account detail work with all evms not only ethereum

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#14191]
- [x] textual warning mentioning directly ethereum while included tokens, should mention actual network

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/b175aabb-9320-4bf6-aaef-f6f121eca836)
![image](https://github.com/user-attachments/assets/af62264d-9eac-418c-8dff-f0463a63f5e1)


**Info**
24.11.1 https://github.com/trezor/trezor-suite/commit/ff16b788c576e89bbbfc17cbe783154223440336
