### ISSUE TITLE
Polygon - base logic

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#14196]
- [x] change `isCoinWithTokens` to work with more token enabled networks
- [x] make txns work with token enabled networks
- [x] change ethereum token selectors to token selectors and make it network agnostic

**Comment by MiroslavProchazka** [comment]
We will be doing the migration from MATIC to Polygon in the upcoming weeks, so please be aware. of it. @tomasklim is preparing all needed in [here](https://github.com/trezor/trezor-suite/pull/14093)

**Comment by vytick** [comment]
@MiroslavProchazka Thanks! I
am aware and waiting for this to be merged. but mostly this is can be done even before.

**Comment by vytick** [comment]
I have split this issue to multiple ones and this one was resolved by #14633 and already tested there
