### ISSUE TITLE
Design inconsistency between Send and Receive (maybe others too)

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1419]
below screenshots of Send, Receive, Transactions tab for the same coin, same account!
### send:
<img width="805" alt="Screenshot 2020-04-02 at 09 11 55" src="https://user-images.githubusercontent.com/6961901/78220831-8c077d80-74c2-11ea-83fd-e5fbc18e44cd.png">

### receive:
<img width="752" alt="Screenshot 2020-04-02 at 09 12 29" src="https://user-images.githubusercontent.com/6961901/78220833-8dd14100-74c2-11ea-80ea-7a0c7e077b02.png">

### transactions:
<img width="816" alt="Screenshot 2020-04-02 at 09 20 53" src="https://user-images.githubusercontent.com/6961901/78221282-6169f480-74c3-11ea-8c74-bf5c9be43073.png">

**Comment by slowbackspace** [comment]
also my personal opinion is that this huge font sizes are weird. there is no semantical meaning to them now (jeez just copy what github uses)
<img width="1026" alt="Screenshot 2020-04-02 at 09 18 02" src="https://user-images.githubusercontent.com/6961901/78221009-dbe64480-74c2-11ea-8c70-340cd032464e.png">

**Comment by glacierbits** [comment]
As discussed, some of these issues will fixed by the new layout (#1326).

**Comment by slowbackspace** [comment]
sooooo I guess we should close this issue only after these designs are implemented and hence the issue resolved 😬
