### ISSUE TITLE
Coins with tokens label change

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#14209]
Whenever we mention coin which includes tokens we support and present in the app we should be consistent in their appearance within the app.
Acceptance criteria:
1. When user is prompted to select coins he would like to use with the app (coin enabling) and there are coins including tokens, the label say [coin] +tokens
2. When user goes to Enabled coins settings and there are coins including tokens, the label say [coin] +tokens
3. When user wants to sync coin in portfolio tracker and he selects the coin and there are coins including tokens, the label say [coin] +tokens

Figma: https://www.figma.com/design/oQtgXoPIgGSlh01TLHnmeE/Coin-enabling?node-id=381-25514&node-type=FRAME&t=qIbNfHggugBL7yx9-0

**Comment by STew790** [comment]
**QA OK**
Tokens are shown in all 3 cases.

**Info:**
24.9.1 https://github.com/trezor/trezor-suite/commit/bf893a5e0f152087cb4e47a4921a64c3c4c1624f
