### ISSUE TITLE
The alignment of the firmware installation modal text is wrong

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#14205]
**Describe the bug**
The alignment of the firmware installation modal text is wrong. It is to the left but it should be centered.

**Steps to reproduce:**
1. Connect device to Suite
2. Go to Device settings
3. Click on Install firmware/Update available
4. The text in bold in the modal is not centered

**Info:**
 - Suite version: web 24.10.0 (f27b837e5934625c5aae63c08d39ed4b1b2ea9fa)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: WebUsbTransport

**Expected result:**
The bold text in the install firmware modal is aligned to the left but it should be centered.

**Actual result:**
The bold text in the install firmware modal is aligned to the left

**Screenshots:**
![image](https://github.com/user-attachments/assets/681fa3c2-0143-4725-ab99-cc5f9ddf7aca)
![image](https://github.com/user-attachments/assets/cf4b9bbd-8186-402a-9777-8000594fd486)

**Comment by bosomt** [comment]
**QA NOK**

found one modal with wrong alignment 

![Image](https://github.com/user-attachments/assets/fcaca48e-408d-49db-af3e-ab07e064b195)

**Info:**
 - Suite version: web 24.10.0 (3ba8a9226c8db83f7f2a058a3fbfec2516ea27b5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.9.1 (d8848035b1badf8ef15fb0cecb6113bfc87326a9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: BridgeTransport 3.0.0
