### ISSUE TITLE
@suite-desktop > browser communication

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1420]
- [ ] Handle requests from browser and open electron app
- [ ] Create webextension?
- [ ] trezor-connect (3rd party apps) requests handled in electron

**Comment by slowbackspace** [comment]
related https://github.com/trezor/trezor-suite/issues/991 (I guess the old issue may be closed in favour of this one?)

**Comment by tsusanka** [comment]
I think this is a duplicate of https://github.com/trezor/trezor-suite/issues/3294. Please reopen if I am mistaken.
