### ISSUE TITLE
Analytics: Use primary and secondary button (YES/No) instead of checkbox

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1421]
I think no one will check this checkbox
![Screenshot 2020-04-02 at 11 05 12](https://user-images.githubusercontent.com/3435913/78230636-e4924700-74d1-11ea-8989-0664c6cdc57d.png)

**Comment by szymonlesisz** [comment]
another thing, that it needs to be implemented

**Comment by glacierbits** [comment]
As discussed with our legal department, this will be ON by default.
