### ISSUE TITLE
Passphrase empty: maybe enable some coins?

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#14229]
**Problem**

User enters passphrase expecting money
Discovery doesn’t find anything
They perhaps have something, but the coin is not enabled

**Opportunity**

Explain user to perhaps enable the coin manually

**Design and spec**
When the user enters a passphrase and confirms it on device (or enters it on it right away), we'll check if there's any balance or transaction history on all currently enabled coins.
If nothing is found, we will show a "This passphrase is empty" state of the wallet switcher.

Please add a new small element to the "Expecting passphrase wallet with funds?" part of it as per [design](https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/View-only?m=auto&node-id=3614-43910&t=C7CKBVPhnQcDIlyX-1).

![Image](https://github.com/user-attachments/assets/978f04a4-0dfb-4576-9115-a302c4948873)

It shows all currently enabled coins and an [+ Add] button
(button not show if all coins are enabled; in case of Bitcoin only FW, don't show this new element at all as nothing else can be checked)

At this MVP solution, the [+Add] button will simply lead the user to Settings > Coins to set up the coins, they will have to manually get back to the Passphrase entry afterwards.
_______________________________________________________________________________
In case the user will continue to open an empty Passphrase wallet instead, we'll show them a new Passphrase wallet empty state including a similar new small element showing coins checked as per [design](https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/View-only?m=auto&node-id=3614-43717&t=C7CKBVPhnQcDIlyX-1).
Similarly as in the above described wallet switcher, it should not be shown for the Bitcoin only FW.
Also here, the [+Add] button will simply lead the user to Settings > Coins to set up the coins.

![Image](https://github.com/user-attachments/assets/bdaf546e-693e-4cc5-8cb1-61971a6f355e)

**Comment by Hannsek** [comment]
Have we drifted from the idea of having silent recovery of all, even non activated, coins?

**Comment by Hermez-cz** [comment]
> Have we drifted from the idea of having silent recovery of all, even non activated, coins?

Hi @Hannsek, it might cause an inefficient overload of resources at this stage, as we don’t know the user’s intention from the start (whether money is expected or not). We plan to introduce this in the upcoming improved Passphrase entry UX, where we’ll work with the user’s mental model of opening a passphrase with funds expected. In that scenario, we can efficiently silently discover all coins to check the expectation. Until that point, we’d be slowing down every user who is intentionally opening an empty passphrase wallet.

**Comment by bosomt** [comment]
**QA OK**

button is present and active, you are navigated into settings/coins section where you can enable more coins
but you have to go to add passphrase wallet again and enter passphrase again

**Info:**
 - Suite version: desktop 24.11.0 (17bac171ecd870c4d76bb64c6ec5f8d69b333d4c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
