### ISSUE TITLE
Onbarding: inavlid left margin

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1422]
![Screenshot 2020-04-02 at 11 09 11](https://user-images.githubusercontent.com/3435913/78231061-86b22f00-74d2-11ea-876d-c4e4e73f63d7.png)

**Comment by szymonlesisz** [comment]
![Screenshot 2020-04-02 at 11 11 08](https://user-images.githubusercontent.com/3435913/78231163-aea19280-74d2-11ea-904f-71c889234132.png)

**Comment by bosomt** [comment]
looks fine !
