### ISSUE TITLE
Missing target="_blank" in  Learn more button

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14237]
**Describe the bug**
See video web version of Trezor Suite does not open links in new window but it closes web wallet 

**Info:**
 - Suite version: web 24.10.0 (0294a9c113f2efc84188e26bd2c3ffdd04eefb13)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: WebUsbTransport

**Screenshots:**

https://github.com/user-attachments/assets/bb31694c-3328-4776-881d-a7f28fc6e5ca

**Comment by MiroslavProchazka** [comment]
@bosomt it is working for me on develop, can you re-check?

https://github.com/user-attachments/assets/ecb368d7-f2ea-49de-9825-ddfd09eb1ddb

**Comment by bosomt** [comment]
**QA OK**

already fixed

**Info:**
 - Suite version: web 24.10.0 (1ffb476cb588fec3e1449d803fd2914ad79bf3cd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.0
