### ISSUE TITLE
Token undefined error when opening ... section in Pol/Tokens/Coins

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14247]
**Describe the bug**
Token undefined error when opening ... section in Pol/Tokens/Coins.

Loaded tokens
- https://matic2.trezor.io/address/0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6
- https://matic2.trezor.io/address/0x4e78011Ce80ee02d2c3e649Fb657E45898257815
- same behavior in `Unrecognized tokens` section

**Steps to reproduce:**
1. Load wallet with Pol token history
2. Open known tokens 
3. Open token detail and observe console errors

**Info:**
 - Suite version: web 24.10.0 (88a6e3e5f7e8daced04c545b7eb9d30bf76286b1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: WebUsbTransport

**Screenshots:**

https://github.com/user-attachments/assets/b372561c-1029-4d5e-9c6d-1d1f3df03f29

**Comment by tomasklim** [comment]
@bosomt cannot replicate, could you please check?

**Comment by bosomt** [comment]
i will check it as soon polygon discovery start working on my computer 😡 

<img width="1196" alt="image" src="https://github.com/user-attachments/assets/3b2aded0-b07e-4713-97f4-579c5b2106eb">

**Comment by bosomt** [comment]
**QA OK**

fixed /probably with fix of missing send receive buttons ;) /

**Info:**
 - Suite version: desktop 24.10.0 (55ac8cb8a4edc1ac546c163acb3482cf53c4e4f8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
