### ISSUE TITLE
Send coins - fee levels improvements

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#14240]
- [ ] Fee-level cards display time estimation when the transaction should be approximately mined. ATM, the estimates are static strings. Replace it with some heuristic calculation.  (Implementation should be reused from the desktop Suite)
- [ ] the fee levels reflect the updated design (every fee level is a separate card) [FIGMA LINK](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=2807-11437&t=VyETZijz1mTRqVWR-4)
- [ ] sat/vByte unit is displayed for Bitcoin-like coins
- [ ] In case that is selected a fee that is too high to be sent, show UI response according to [this design](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=2807-14735&t=VPzuMJ81cT2t7tyJ-4)
   - [ ] [this animation](https://www.figma.com/proto/sqKFZAIvk3zERxiWgthK8K/Send?page-id=0%3A1&node-id=2807-14663&node-type=frame&viewport=-12257%2C-481%2C0.71&t=qGIuVxLOcOml3SEh-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2225%3A19415) is included

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/1a8ab3e8-d99e-4efb-9370-109f84e28fb6)
![image](https://github.com/user-attachments/assets/1ca0f453-66b2-494a-86f4-a3f1d0760ffa)

**Info**
24.9.2 https://github.com/trezor/trezor-suite/commit/49d390a153095aa0110b7ab654c05de5da362e0c
