### ISSUE TITLE
Coinmarket - DCA wrong colors for store icons for Light color scheme 

### ISSUE THREAD

**Issue by salax** [trezor/trezor-suite#14257]
**Describe the bug**
Wrong store icons color when "Light" color scheme is active.

https://github.com/user-attachments/assets/6a1c10b6-23e0-4357-bc76-6e26f0f2a8f9

Cause: Color scheme "Light" and "System" (even when it is light) have different state values (`standard` vs `light`).

Fix: improve light scheme detection logic

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/user-attachments/assets/64fca525-1891-4bbd-995e-3eea1e2951fc)

**Info:**
 - Suite version: web 24.10.0 (46fe7abf9737bbd439901882dceb29aad98a2b26)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3B1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: WebUsbTransport
