### ISSUE TITLE
Coin Enabling works wrong for BTC only device

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#14255]
**Describe the bug**
For BTC only device without testnets allowed it shows initial coin enabling settings and in settings it shows networks to use with only BTC. 

**How to reproduce**
Have BTC only device, connect to not set app with fresh app with coin enabling on. It shows initial dialog and in settings there is BTC instead of BTC only UI.

**Expected behavior**
Dont show initial dialog for BTC only firmware.
In settings show BTC only graphic

**Screenshots**
This should not be seen
<img width=280 src="https://github.com/user-attachments/assets/4aac0898-ea64-4e0c-a7db-2ab47da1f369" />

**Additional context**
This should be in settings instead
<img width=280 src="https://github.com/user-attachments/assets/10c0eae0-90f2-4679-bf8b-30d513f718a4" />

**Comment by STew790** [comment]
**QA OK**
Initial dialog for coin enabling is not shown for BTC only.
Coin enabling settings looks like this:
![image](https://github.com/user-attachments/assets/58daf7a1-bfe4-47b0-9fb5-b7a432c651d3)

**Info**
24.9.1 306d448
