### ISSUE TITLE
`AbortButton` broken layout

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#14260]
This is the only remaining place `AbortButton` is used, maybe it can be replaced with a simpler icon?

**How to reproduce**

- Go to update firmware on TT with FW version < 2.6.0 (or T1 < 1.10.0).
- Observe broken button

**Screenshots**
![Screenshot 2024-09-10 at 16 43 40](https://github.com/user-attachments/assets/6216be71-83de-49de-a344-ce371491209a)

**Comment by bosomt** [comment]
**QA NOK**


https://github.com/user-attachments/assets/87f0206f-233d-47a7-902b-08605b0867fe

**Info:**
 - Suite version: web 24.10.0 (0cb09ab127e1213a55f4fce24243c674884c436a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.4.0 regular (revision ea3596ad8)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.0

**Comment by bosomt** [comment]
**QA NOK**

<img width="629" alt="Screenshot 2024-09-19 at 15 16 26" src="https://github.com/user-attachments/assets/bd1d5f60-5464-4806-b243-a16eb8cdcaa1">


**Info:**
 - Suite version: desktop 24.10.0 (265028df5e34d075abd34f2ee338e6392d3613c1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.4.0 regular (revision ea3596ad8)
 - Transport: BridgeTransport 2.0.33

**Comment by komret** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/14643.
However, there is another problem: https://github.com/trezor/trezor-suite/issues/15157

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/429bec45-1a1a-4557-8fec-ecdbea955ba9)

**Info:**
 - Suite version: web 24.11.0 (ccc4abd7435e4efabeac8fa846d6e4f7a4e23432)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 5120x1440
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport
