### ISSUE TITLE
Components ignoring className

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#14261]
While it is discouraged to overload `@trezor/components` with styles, there is still some code that does this. However, `className` prop is ignored by some components (e.g. `H2`), which leads to broken layouts.

Add `className` prop to all components where it once was, unless you are sure no code relies on it.

For example, all this code is ignored:
![Screenshot 2024-09-10 at 16 49 52](https://github.com/user-attachments/assets/621d04fa-d435-49f2-9f5b-044159c3f6e0)

**Comment by MiroslavProchazka** [comment]
cc @jvaclavik @adamhavel , might be related to broken layout in several places right now in develop
