### ISSUE TITLE
Mined UTXOs not included in default Coin Control

### ISSUE THREAD

**Issue by Lemonexe** [trezor/trezor-suite#14270]
**Describe the bug**
When creating a Send transaction with default Coin Control settings, I cannot send all my funds - mined UTXOs are not included. I have to open manual Coin Control and check the mined UTXOs in order to send them.

Tested **only** on regtest.

**Info:**

-   Remembered Wallet: no
-   Suite Version: web on production, desktop on develop
-   OS: Ubuntu 24.04
-   Bridge: 2.0.33
-   Firmware Version: T2T1, 2.8.1

**How to reproduce**

1. Use `trezor-user-env` regtest
1. In Suite, create regtest account no. 1
1. Send some amount to the regtest address
2. Mine some blocks at the regtest address
3. Create another regtest account no. 2
4. Open Send from regtest account no. 1
5. Send max
6. See that it is not the full amount! :bug:  
open Coin Control and see that mined UTXOs are not included by default, only received UTXOs are included

**Expected behavior**
When I don't interact with Coin Control settings, send max should include all UTXOs, including the mined.

**Screenshots**
In the video I have some regtest UTXOs that were recieved, and some that were mined (those are always 25).
[mined_regtest.webm](https://github.com/user-attachments/assets/e3d632bb-e37f-4725-ba9b-975ebff031d4)

**Comment by MiroslavProchazka** [comment]
Check whether you need 100 confirmation of mined UTXO to be able to spend them. If yes, let's close it

**Comment by peter-sanderson** [comment]
Even if you compose transaction with coin-controll and you try to spend it, you will get 
![image](https://github.com/user-attachments/assets/5a8702fa-841c-4650-882a-db79ef41dc36)

**Comment by peter-sanderson** [comment]
The root issue is here: `packages/utxo-lib/src/coinselect/coinselectUtils.ts:323` (usage of the `filterCoinbase` function)

**Comment by bosomt** [comment]
**QA OK**

created regtest tx 
send all added fresh mined input automatically

https://github.com/user-attachments/assets/220d6e01-8215-44fd-a86e-b67be33a4d68


**Info:**
 - Suite version: web 25.1.0 (98b2554adacdfeef932c69e5442db4e00def44f9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.7 regular (revision 8a254aa8eae82f99630df63f40e4d290066a3efc)
 - Transport: WebUsbTransport
