### ISSUE TITLE
Coin enabling - handle coin enabling during discovery

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#14275]
Do not allow to change coin settings during discovery. Block opening settings and show spinner/loader when discovery is running

[figma](https://www.figma.com/design/oQtgXoPIgGSlh01TLHnmeE/Coin-enabling?node-id=0-1&node-type=canvas&t=QZfImcKwcqfIj4Yw-0)

<img width="439" alt="Screenshot 2024-09-12 at 15 48 55" src="https://github.com/user-attachments/assets/f205efd4-8729-45db-857c-dc8f3cdf0db5">

**Comment by STew790** [comment]
**QA OK**
Can't enter `Enabled coins` settings while discovery is being done.

**Info**

24.9.1 e716494
