### ISSUE TITLE
Label ETH ledger accounts

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#14278]
Based on: https://github.com/trezor/trezor-suite/issues/13737

Acceptance criteria:
- Default ETH accounts have no tag
- Ledger accounts are marked Ledger or Legacy

Tags are assigned based on derivation path:
Default = m/44'/60'/0'/0/address_index
Ledger = m/44'/60'/address_index'/0/0
Legacy = m/44'/60'/0'/address_index

**Comment by STew790** [comment]
**QA OK**
I can see both accounts labeled correctly.

**Info**
24.10.2 17d794f
