### ISSUE TITLE
Confusing instructions on landing page for old devices

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#14284]
When you connect an old device not supported by WebUsb while using web Suite, you get the following instructions, which are confusing and not helpful. I tried this with bootloader 1.3.3 on devkit.

Web:
![Screenshot 2024-09-11 at 13 52 06](https://github.com/user-attachments/assets/a8c54f2d-fb47-400c-9795-45bf72bb2daa)
1. The top message "Device detected in incorrect state" is inaccurate. There is a problem with the app, not the device.
1. It then tells you to download Bridge, but does not tell you how to get it.
1. It leads you to Bridge status page, but you probably don't have Bridge at all. (Copy could be better.)
1. It tells you to use desktop app, which won't work either because it doesn't use Bridge anymore.
1. The button to disable WebUSB and use Bridge instead won't help you because you probably don't have Bridge.

**Comment by mroz22** [comment]
> The top message "Device detected in incorrect state" is inaccurate. 

Thats right and I have been asking product to change this for ages. Maybe we should take an action ourselves. What do you suggest? "There is an issue to solve"?
