### ISSUE TITLE
Coinmarket - show DCA page only for Bitcoin accounts

### ISSUE THREAD

**Issue by salax** [trezor/trezor-suite#14290]
Right now DCA page is shown for all accounts, but we will show it only for Bitcoin accounts.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.10.0 (ce5e5732348fa083a1687a0b23bf2ee987a7c95a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 3.0.0
