### ISSUE TITLE
Data collection

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1429]
_Note: More items will be added as we move along._

**Onboarding**

- [x] Decision on Startup screen (Yes / No) #1421 🔥

**Menu**

- [x] Switch Wallet 🔥
- [x] Settings 🔥
- [?] Activity 
- [x] Discreet toggle

**Switch Wallet modal**

- [x] Add Wallet 🔥
- [x] Remember 🔥
- [x] Eject 🔥

**Dashboard**

Primary CTAs on tiles:
- [x] Create backup
- [x] Enable PIN
- [x] Try discreet mode

Secondary CTAs on tiles:
- [x] Check seed in Settings
- [x] Change PIN in Settings
- [x] Create hidden Wallet 🔥
- [x] Enable discreet mode 

**Wallet**

- [x] Add account 🔥
- [?] Number of Accounts (?) 🔥

**Settings**

General
- [x] Language
- [x] Primary fiat

Device
- [x] PIN protection 🔥
- [x] Check seed
- [x] Passphrase
- [x] Device label
- [x] Wipe device

Coins
- [x] Coins enabled 🔥

**Comment by mroz22** [comment]
more or less done
