### ISSUE TITLE
Always show only 1 extra skeleton during discovery

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#14305]
as discussed here internally https://satoshilabs.slack.com/archives/C04JZAYEV41/p1725951870182429

**Comment by STew790** [comment]
**QA OK**
Only one skeleton is showed :skull: 

**Info**
24.9.2 https://github.com/trezor/trezor-suite/commit/7a4ddc9a8137951fe69c7693d4ac9e70511a39b4
