### ISSUE TITLE
Not able to update firmware of device using translation

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14300]
**Describe the bug**
I'm not able to update firmware of device when using translation.
I was able to replicate it in web and app version of suite
I was able to reproduce issue on production and release candidate

**Steps to reproduce:**
1. Install 2.7.2 firmware to device
2. Change language to Czech
3. Try to update device

**Info:**
 - Suite version: web 24.9.1 (d8848035b1badf8ef15fb0cecb6113bfc87326a9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 751x870
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: WebUsbTransport

**Screenshots:**

https://github.com/user-attachments/assets/6f0efa5a-0abc-42d4-a059-d3df9573fbc8

**Comment by Hannsek** [comment]
@matejcik should it be even possible to update? 🤔

**Comment by matejcik** [comment]
FirmwareError indicates firmware-side problem
updating with translations should generally work so i think this is a real issue

**Comment by MiroslavProchazka** [comment]
Fixed in latest 24.9.1

**Comment by bosomt** [comment]
**QA OK**

24.9.1 and 24.10.0  tested for all translations
https://www.notion.so/satoshilabs/Firmware-update-with-different-language-2880584429bc4d6497c95f7808ec3d7f?pvs=4
