### ISSUE TITLE
Coinmarket - Incorrect amount when buying BTC in Argentinian pesos

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14309]
**Describe the bug**
Incorrect amount when buying BTC in Argentinian pesos

**Steps to reproduce:**
1. Navigate to BTC/Trade/Buy
2. Select 0.1 BTC and select you want to pay in ARS
3. No offers
4. Navigate to Eth holesky
5. Offer available
6. In next step there is only 0.001 BTC in amount but fiat value does not change

**Info:**
 - Suite version: desktop 24.9.1 (d8848035b1badf8ef15fb0cecb6113bfc87326a9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: BridgeTransport 3.0.0

**Screenshots:**

https://github.com/user-attachments/assets/fa74b4ee-fb47-4e76-9e97-3305ef6c3834

**Comment by tomasklim** [comment]
@bosomt please check develop if still available

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
