### ISSUE TITLE
Sporadic missing icons in dark mode

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#14311]
Missing icons appear sporadically, so far, only noticed in dark mode. Artifact is resolved when navigating to another screen and navigating back.

![image](https://github.com/user-attachments/assets/2878ac9a-e554-4982-a02b-b91476c92580)
![image](https://github.com/user-attachments/assets/9ec6a1df-c826-4699-8ea2-682cda94c75a)

**Comment by matejkriz** [comment]
Let's fix this together with https://github.com/trezor/trezor-suite/issues/12433, we will probably switch from Skia to react-native-svg or icon font.

**Comment by STew790** [comment]
**QA OK**
I haven't seen any missing icons in dark mode for weeks now.
**Info**
24.11.1 https://github.com/trezor/trezor-suite/commit/ff16b788c576e89bbbfc17cbe783154223440336
