### ISSUE TITLE
Trading - pair_is_inactive error when exchanging BTC to Stellar token

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14314]
**Describe the bug**
When testing https://github.com/trezor/trezor-suite/issues/14249 i stumbled on this error.

`Error: pair_is_inactive`

**Screenshots:**
Insert here.

<img width="610" alt="Screenshot 2024-09-12 at 9 55 40" src="https://github.com/user-attachments/assets/446e8eee-af1a-4615-a6e4-a40f65edfedd">

https://github.com/user-attachments/assets/9a2c421f-0eba-456d-8c7a-f0bbbffac87e

**Info:**
 - Suite version: desktop 24.9.1 (d8848035b1badf8ef15fb0cecb6113bfc87326a9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: BridgeTransport 3.0.0

**Comment by tomasklim** [comment]
@bosomt please check if still available

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
