### ISSUE TITLE
Coinmarket - Allow buy without connected Trezor device

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14310]
## Issue

When a user gets to the second step in the Buy flow where they select a specific address to receive crypto and the Trezor is disconnected, Suite only allows to Show an unverified address and copy it so the user is stuck.
![obrazek](https://github.com/user-attachments/assets/f794728e-f44f-42ee-bc97-fc52909227c1)

## Solution
Instead of “Show unverified address” in this dialog show “Proceed with unverified address” button, close the dialog, and allow a user to proceed to the partner’s checkout.

![obrazek](https://github.com/user-attachments/assets/390085a7-a415-4793-b55d-0ed22a83860f)

**Comment by Hermez-cz** [comment]
Please update the modal component to this warning one: https://www.figma.com/design/dYIRTk1qVcKsrJDqOzZ7SG/Modals?node-id=4037-2006&t=61v4fJb4LWtWq6cX-1

<img width="880" alt="image" src="https://github.com/user-attachments/assets/6646aee3-cb30-4ff7-aafd-e18ccae2c113">

**Comment by adderpositive** [comment]
@Hermez-cz  It should be fine (used a new design for the modal), only without an Icon.

![obrazek](https://github.com/user-attachments/assets/5d3ee112-ad08-4e18-a308-18e00d917a02)

**Comment by Hermez-cz** [comment]
@adderpositive If it's a warning modal (yellow), it should have the icon and the layout as linked above.

The used layout is intended just to plain informative purposes.

**Comment by STew790** [comment]
**QA OK**
There is "Continue..." instead of "Proceed.." but I assume that is ok.
![image](https://github.com/user-attachments/assets/8a6c1956-514f-43f4-98ed-3e82f85e43e6)


**Info:**
 - Suite version: desktop 24.10.0 (ac53d354cc8538700fb9e93de2dc7f6b6c6a37f4)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Comment by adderpositive** [comment]
No, it's not correct. There should be `Proceed`

**Comment by STew790** [comment]
**QA NOK**
Ok, I stand corrected, sorry. Then it is not OK.

**Comment by adderpositive** [comment]
Should be resolved here https://github.com/trezor/trezor-suite/pull/14644

**Comment by bosomt** [comment]
**QA OK**

`Proceed with unverified address` needs to be translated.

![Image](https://github.com/user-attachments/assets/e00b9bd5-0973-4cc4-ac01-dfc44532d237)


**Info:**
 - Suite version: desktop 24.10.0 (2187dc0a75fc5ffb03e51b661ff61952c5159ebf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.0
