### ISSUE TITLE
Grey label provider icons

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#14325]
**Describe the bug**
The icons for providers for labels are grey.

**Steps to reproduce:**
1. Connect a device
2. Go to settings
3. Click on "Labeling"
4. When choosing provider see grey icons of the providers

**Info:**
 - Suite version: desktop 24.9.1 (e2177b22af8251cd1e81e2fec0a0019e664e053a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 3.0.0

**Expected result:**
Icons are colored

**Actual result:**
Icons are grey

**Screenshots:**
![image](https://github.com/user-attachments/assets/9d3f28a2-3242-4ba8-abc9-cc02c878a951)

**Comment by MiroslavProchazka** [comment]
Is this also on develop?

**Comment by STew790** [comment]
Yes it is

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/73cb22ff-0ef2-495b-b6bd-b1c90916642e)
![Image](https://github.com/user-attachments/assets/8c57dc19-7d96-4424-85e9-5ec3225d8fa8)

**Info:**
 - Suite version: web 24.10.0 (0c147a1d37dc615e286a114d90bc8b637bbb929f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: WebUsbTransport
