### ISSUE TITLE
Send coins - confirm on trezor cancelation dialog

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#14330]
In case that user wants to cancel on device review from mobile app UI,[ this cancelation dialog](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=2913-8772&t=AYq1qouAwONMiMdP-4) is displayed.

**Comment by STew790** [comment]
**QA NOK**
I am returned to the first point of the "review" of the transaction but I don't see no modal when I cancel on device.
**Info**
24.9.2 https://github.com/trezor/trezor-suite/commit/49d390a153095aa0110b7ab654c05de5da362e0c

**Comment by PeKne** [comment]
@STew790 I double-checked, and the behavior that you describe is correct. The modal dialog should not be displayed if you cancel on the Trezor device. The confirmation dialog is already displayed in the firmware UI, and when the user performs the cancel, there is no way back in the Suite UI. So, showing the alert in this case does not make sense.

But good point: Maybe there should be some alert with different content informing the user what happened. I will discuss it with product and design. But no action needed regarding this issue.

**Comment by STew790** [comment]
**QA OK**
Approving, since this is intended.
