### ISSUE TITLE
Send coins - bitcoin-like networks fee settings

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#14333]
# Acceptance criteria:

For other Bitcoin like coins (LTC,  BTC, BTH etc.)  where is only one fee option, change fee selection screen copy according to [this design](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=2163-18557&t=eU86aJbMDI54zSmX-4).

**Comment by STew790** [comment]
**QA OK**
Fee is correct according to design.

**Info**
24.11.1 https://github.com/trezor/trezor-suite/commit/36fdc66a6a60ec39ec68134ae6f1aba13979f1f3
