### ISSUE TITLE
Coinmarket - incorrect menu/tab icons & responsive behavior

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14331]
## Responsiveness
- When decreasing the screen width, the Send + Receive buttons should always remain visible. The Buy, Sell, and Swap buttons should disappear first into a dots. The Send + Receive buttons must be the last to wrap.
- Buttons should not wrap vertically like this.
![image](https://github.com/user-attachments/assets/8a404f40-c438-4a7a-a37e-105f7bc8d68f)
<img width="808" alt="image" src="https://github.com/user-attachments/assets/47b8afc2-1f51-4bd8-b649-39dc823861b6">

## Icons
- Icons need to be different (the coin icon is used elsewhere, and the refresh icon should not be used for Swap).”

	
<img width="547" alt="image" src="https://github.com/user-attachments/assets/ef1ceead-b047-4671-b6e5-740ae7fb0ff0">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.10.0 (acd58e6c26394eb09907791dd4006d03c130fe65)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
