### ISSUE TITLE
Deprecation of getSignatureStatus

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#14343]
According to [Agave 2.0 transition](https://www.helius.dev/blog/agave-2-0-transition), getSignatureStatus is deprecated.

https://github.com/trezor/trezor-suite/blame/develop/packages/blockchain-link/src/workers/solana/transactionConfirmation.ts#L22

**Comment by mroz22** [comment]
is it time-sensitive? do we need to sync with our releases?

**Comment by bosomt** [comment]
**QA OK**

[sent sol tx ](https://explorer.solana.com/tx/VfjXXxK58DQMyasosXGUefts8ohuGqMhRmwWxGvGcAHzUNRxKAM6Lmbs7knWfrAyp9Gi2LJb8wgvLBYn9dUixYm)
[and sent token tx](https://explorer.solana.com/tx/32yT1kCEj49J1ZDK7cJBNVURqp7wfm4WTQR5zGcgMn2uaXX9aJHAz24d8zLJ5Y5aZ2bDMcgKhocRjU8MPJ22ZBCp)

**Info:**
 - Suite version: desktop 24.9.2 (1b0a1195c54a9c8bc91fff19ee4248a84a599106)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.2 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
