### ISSUE TITLE
Display TS5 along T and TS3 on Bridge Status Page

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#14346]
Now, only model T / R is displayed on bridge status page.

- [ ] Rename "R" to "TS3"
- [ ] Add "TS5"

Because we cannot currently distinguish between core devices we have to list all core devices there. It should look like 

`Model: Trezor Model T / Trezor Safe 3 / Trezor Safe 5
`

![image](https://github.com/user-attachments/assets/46d9314c-e5a4-46a3-b34e-9fcc9cee71b0)

**Comment by bosomt** [comment]
**QA OK**


```
Devices
Connected devices: 1
model: Trezor Model T / Trezor Safe 3 / Trezor Safe 5
path: 1
session: none
```

**Info:**
 - Suite version: desktop 24.10.0 (265028df5e34d075abd34f2ee338e6392d3613c1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.0
