### ISSUE TITLE
Increase trezor rememberedDevice validity beyond 15mins with Rabby

### ISSUE THREAD

**Issue by 0xGitGuy** [trezor/trezor-suite#14344]
With the new rabby webextension implementation, the rememberedDevice validity is set to 15mins. Is there a way to increase this period to forever or weekly? It's rather annoying every now and then you need to enter a pin and passphrase. 

https://github.com/trezor/trezor-suite/pull/11796

#11796

**Comment by Hannsek** [comment]
Hello, thanks for the issue. 

We'll change the behaviour in the way that the _session timeout_ will be set based on the greater among 
1. 15 minutes
2. auto-lock of the device


So, if you set auto-lock to e.g. 30 minutes. The session timeout will be 30 minutes. If you set it to 5 minutes, the autolock will be 15 minutes.

In the next version of Connect (10) we would like to make it configurable by the user.

**Comment by 0xGitGuy** [comment]
I assume if the  auto lock is set to never, the session timeout will be forever?

**Comment by martykan** [comment]
The maximum supported auto lock time is 6 days (144 hours). However keep in mind the device has to be powered on the entire time. We don't save passphrases persistently.

**Comment by Hannsek** [comment]
Most probably. But there can also be some restrictions from the side of the browser. cc @martykan 

I just want to point out that not having auto-lock time set up is dangerous and may potentially lead to lost of funds.

**Comment by 0xGitGuy** [comment]
Thanks for the reminder of the security trade off. Does the wallet extension need to implement any changes on their end for this pull request to be effective on the wallet UI so that I can ping them?

**Comment by martykan** [comment]
Changes on the extensions side shouldn't be necessary right now, it should be effective with the next release of Trezor Connect

**Comment by Hannsek** [comment]
You can expect it to be out in couple of weeks.
