### ISSUE TITLE
Coinmarket - no offers state has bad translation

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14351]
## Issue
Bad translation of state, when no offers found.

### Before
![obrazek](https://github.com/user-attachments/assets/4f14e2db-55d4-4224-9b18-572475770269)

### After
![obrazek](https://github.com/user-attachments/assets/9732a378-d13d-4d8d-811a-1ba1a1249547)

**Comment by bosomt** [comment]
Will be tested as soon there will be next crowdin release

**Comment by MiroslavProchazka** [comment]
Crowdin bot run - https://github.com/trezor/trezor-suite/actions/runs/10988570673
Watch this PR, once it will be merged, you can re-test this issue

**Comment by adderpositive** [comment]
Looks good.

**Comment by bosomt** [comment]
**QA OK**

```
No offers available for your request.
Change amount or currency.
```

**Info:**
 - Suite version: desktop 24.10.0 (55ac8cb8a4edc1ac546c163acb3482cf53c4e4f8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
