### ISSUE TITLE
Send coins - fixes of UI/UX review

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#14356]
Fix all the problems discovered during the [UI/UX review](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=3241-9623&t=rZPWs70FeVAIyzjH-4) that are marked as critical for the first send release.

**Comment by PeKne** [comment]
info for QA: Probably not much to test. Mainly UI and layout improvements. Please just test that you are able to go through the whole flow and everything looks good.

**Comment by STew790** [comment]
**QA OK**
LGTM

**Info**
24.9.2 https://github.com/trezor/trezor-suite/commit/49d390a153095aa0110b7ab654c05de5da362e0c
