### ISSUE TITLE
Cardano related TrezorConnect calls might fail even with useCardanoDerivation: true 

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#14369]
It seems, that if `TrezorConnect` call had `keepSession: true` followed by enabling Cardano and asking for cardano derivations, it fails. 

According to our discussion with @mroz22 this might probably happen, because the Device has connect already initialized and not disposed (`this.commands?.disposed === false`), meaning, that [this condition](https://github.com/trezor/trezor-suite/blob/b1c111c8f21bda5221367cbbf3a204663b3804b2/packages/connect/src/device/Device.ts#L333) does not pass and the call is run without change in `useCardanoDerivation` even if it was passed in the call options. It probably also works the same the other way around, when cardano is disabled. Even patching in `connectInitThunk` with `cardanoConnectPatch` does not fix it in this case.

It seems that, workaround to this is to send another trezor connect request with `keepSession: false` which probably sets `this.commands?.disposed` to `true` and correctly applies `useCardanoDerivation`. 

We are using this workaround in #14345

**Comment by evgenysl** [comment]
Checked Cardano on develop, everything looks OK
