### ISSUE TITLE
Display error when more than max allowed decimal digits are used

### ISSUE THREAD

**Issue by yanascz** [trezor/trezor-suite#14370]
**How to reproduce**
Go to the send form screen and type an amount with more than 8 decimal digits.
<img width="352" alt="image" src="https://github.com/user-attachments/assets/8ddaf3f1-5018-43fa-b91f-5186093d05a7">

**Expected behavior**
The same error message as in the desktop Suite shall be displayed.
![image](https://github.com/user-attachments/assets/cde03b32-32b4-4bf6-9ebd-a16454ad94dd)

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/6168f2d8-a753-4fbd-86bf-e2071cba1145)


**Info**
24.9.2 https://github.com/trezor/trezor-suite/commit/7a4ddc9a8137951fe69c7693d4ac9e70511a39b4
