### ISSUE TITLE
Changing tokens in Solana send form triggering passphrase modal

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#14392]
**Describe the bug**
Changing tokens in Solana send form is triggering a passphrase modal

**Steps to reproduce:**
1. Connect a wallet with a passphrase
2. Navigate to Solana send form
3. Change the tokens
4. Observe the passphrase menu triggering

**Info:**
 - Suite version: web 24.10.0 (d34ecbd7f29f72f9765deeeeba21a08713624d46)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport

**Comment by tomasklim** [comment]
@STew790 cannot replicate :(

**Comment by STew790** [comment]
**QA OK**
I wasn't able to replicate it on latest develop. Closing.

**Info:**
 - Suite version: web 24.11.0 (9394468337699af878c582b976cc80ed601721e4)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.32
