### ISSUE TITLE
Collapsible component update

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#14397]
**Problem statement**
The refactoring of the collapsing component caused issues due to the lack of a standardized version, leading to suboptimal fixes. For instance, the test coins box is too noticeable with the gray background, and the no-fill variant lacks borders, making it appear to float (see below).

![Image](https://github.com/user-attachments/assets/dcf94859-5b76-48ee-bbd9-b14a7e140730)
![Image](https://github.com/user-attachments/assets/cc7a65cd-17f5-4a36-a44a-fe76b2878824)

**New design**
[Figma](https://www.figma.com/design/Y2E8dcdNYrSMGIVRjYFXKp/%5BSuite%5D-Components?m=auto&node-id=1735-55384&t=Xjf21U6Q0SdypkMt-1)

**Comment by MiroslavProchazka** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/14532
