### ISSUE TITLE
Token definitions fetching improvements

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#14399]
We should come up with better solution for fetching token definitions. We now have hardcoded `eth`, `pol`, `bnb` & `sol` which is suboptimal. ~Also it will fetch that definitions during startup which is also not good because parsing it is kind of slow.~

- [x] Only definitions for enabled networks and networks of imported accounts should be fetched. (DONE in #15263)
- ~[ ] Don't fetch token definitions right on app start, not to make it slow.~

possible followups:
#15252 #15253

**Comment by matejkriz** [comment]
Notes for QA: check that token definitions are not missing when needed (tokens have fiat rates, are visible in transaction list)

**Comment by STew790** [comment]
**QA OK**
Since this https://github.com/trezor/trezor-suite/issues/15332 was fixed, I haven't found any other issue with tokens :tada: 

**Info**
24.11.1    35433e7d5213f924061bc36bb74edf017bd39db0
