### ISSUE TITLE
Different decimals for different tokens allowed

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#14391]
**Describe the bug**
There is a difference for allowed decimals for tokens on Solana.

**Info:**
 - Suite version: web 24.10.0 (d34ecbd7f29f72f9765deeeeba21a08713624d46)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport

**Screenshots:**
![image](https://github.com/user-attachments/assets/1bb7a212-6266-4ba1-b76f-036a22083a5f)
![image](https://github.com/user-attachments/assets/71452d1c-a99d-46a4-9db5-2624e9a93b29)

**Comment by tomasklim** [comment]
That’s ok, depends on the token itself
