### ISSUE TITLE
Mobile send - Trezor device connection states

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#14405]
Handle  these connection events in context of the send flow:
- connection/disconnection of Trezor device during the send flow
- pin locking

[DESIGN](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=3202-15202&t=rZPWs70FeVAIyzjH-4).

**Comment by STew790** [comment]
**QA OK**
- disconnection of device:
![image](https://github.com/user-attachments/assets/fd1a24e7-cf38-4874-a863-7cb7b21a32dc)
- when device is pin locked, I am asked to unlock it
**Info**
24.10.1 https://github.com/trezor/trezor-suite/commit/d87ce7455c97466e91037508e50516aa2ae8ba4b
