### ISSUE TITLE
Dropdown component fix

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#14428]
Dropdown BG is always …/Surface/Elevation 1, regardless on which surface it is. 

![Image](https://github.com/user-attachments/assets/e2bd9aed-a1e8-4024-838e-2464a9712a9e)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.12.0 (fd5fbfb39a942f7cad024fd1f0a979e4ee8ec783)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: BridgeTransport 2.0.33
