### ISSUE TITLE
Analytics toggle by default ON

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1443]
- [ ] Analytics screen toggle ON

- [ ] Reflect the preference in General Settings 

![78230636-e4924700-74d1-11ea-8989-0664c6cdc57d](https://user-images.githubusercontent.com/29627086/78386552-0b3da400-75de-11ea-8221-4214ae2764eb.png)

**Comment by bosomt** [comment]
works fine in Chromium and Firefox
