### ISSUE TITLE
Send coins - form submit button scroll position

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#14431]
- [ ] When the user fills in the amount to send in the send form and the submit button appears, the content of the screen should scroll so that both crypto and fiat inputs are visible above the button. [More here](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=3256-9757&node-type=instance&t=vOcgCS1B9dwftZr4-0)
- [ ] If a user has opened the software keyboard, he  should be able to click fiat <==> crypto input without the need for an extra tap to hide the keyboard

**Comment by STew790** [comment]
**QA OK**
Both points are working correctly.
**Info**
24.9.2 49d390a
