### ISSUE TITLE
Missing historical fiat prices in transaction detail

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14458]
**Describe the bug**
Missing historical fiat prices in transaction detail.
I was able to reproduce issue on 24.9.x and 24.10.0 versions of Suite.

**Steps to reproduce:**
1. Load wallet with transaction history
2. Open transaction detail
3. Check transaction value at time of confirmation of transaction.

**Info:**
 - Suite version: web 24.10.0 (1a4daf5fbdceb450535815b46f2a31e2114d07a5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: WebUsbTransport

**Screenshots:**
<img width="679" alt="image" src="https://github.com/user-attachments/assets/58296e2e-2ac7-42b2-b89f-ee76f010cf35">

![image](https://github.com/user-attachments/assets/6a30df77-ff36-44e8-9206-f6461ae50d80)

**Comment by tomasklim** [comment]
@bosomt cannot replicate, could you please check?

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.10.0 (2187dc0a75fc5ffb03e51b661ff61952c5159ebf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.0
