### ISSUE TITLE
connect docs - web - core in popup

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#14452]
core in popup mode is not documented. maybe this diagram should be extended to describe full lifecycle (if bridge -> iframe, if not core in popup and webusb)

<img width="810" alt="image" src="https://github.com/user-attachments/assets/7d141501-7479-40b3-a9af-cf55218d7be7">

**Comment by Hannsek** [comment]
The  diagram is already ready.
![image](https://github.com/user-attachments/assets/4f619c80-2586-43b0-aeeb-4e37b62f67f7)
cc @martykan

**Comment by martykan** [comment]
Maybe also a flowchart like this to explain the auto mode?
<img width="904" alt="Screenshot 2024-09-23 at 10 25 21" src="https://github.com/user-attachments/assets/4735fd04-b7f4-42bb-b4a0-01eb3a522a79">
