### ISSUE TITLE
EVM Tokens / Add tokens and staking info to dashboard assets overview

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#14456]
**Description:**
Please add `Tokens` and `Staking` info to the dashboard "My Assets" section as per design below and as is already available in sidebar

[Design Figma](https://www.figma.com/design/0Kz3w6WDlvQm62RjOm87na/Staking?node-id=6130-28049&t=bVgXOf4lz3Nz6qDE-1)

**Current state:**
![Screenshot 2024-09-30 at 9 54 52](https://github.com/user-attachments/assets/af235023-86ad-46a6-b742-fe7e1057b7e0)
![Screenshot 2024-09-30 at 10 14 34](https://github.com/user-attachments/assets/302bcf8b-d43c-435a-aacc-b01558815160)

________
**Future state:**

- prerequisite [EVM Tokens / Token icons bundle #14611](https://github.com/trezor/trezor-suite/issues/14611)

**Table view:**
- prerequisite [EVM Tokens / Generic table structure #13152](https://github.com/trezor/trezor-suite/issues/13152)

![image](https://github.com/user-attachments/assets/bfa3465f-7eff-4bd8-bbed-6b7bb86cb7b4)

**Card view:**
![image](https://github.com/user-attachments/assets/3965120f-4fd2-4e9b-b8a3-b37e8a38cc7f)

**Comment by tomasklim** [comment]
Prerequisite [EVM Tokens / Generic table structure #13152](https://github.com/trezor/trezor-suite/issues/13152)

**Comment by tomasklim** [comment]
@Hermez-cz 
1. I think staking with just $ value does not make much sense. The $ amount is changing every second. I would like to see also ETH amount there.
2. I find this confusing. Price and Last 24h is too far from amount itself.
<img width="540" alt="Screenshot 2024-09-21 at 6 53 14" src="https://github.com/user-attachments/assets/0670867f-d6b2-49bd-9afb-b2c49acbb436">

There is too many numbers $ numbers, I am lost as a user

**Comment by Hermez-cz** [comment]
> @Hermez-cz
> 
> 1. I think staking with just $ value does not make much sense. The $ amount is changing every second. I would like to see also ETH amount there.
> 2. I find this confusing. Price and Last 24h is too far from amount itself.
> 
> <img alt="Screenshot 2024-09-21 at 6 53 14" width="540" src="https://private-user-images.githubusercontent.com/33235762/369596065-0670867f-d6b2-49bd-9afb-b2c49acbb436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODEwNzgsIm5iZiI6MTcyNzA4MDc3OCwicGF0aCI6Ii8zMzIzNTc2Mi8zNjk1OTYwNjUtMDY3MDg2N2YtZDZiMi00OWJkLTlhZmItYjJjNDlhY2JiNDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA4MzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMmQ4MWEzOTYzNTY5MWNkZjBiZDNhNDY1ZWNiODhiZWU2ZWRiY2ZkYzI4OGEyY2JjZTkxZTFiMDhlYWExZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VgLAgYchPBG6AjXe1oZNpokQ5g0NAef0hL8vYRk75iM">
> There is too many numbers $ numbers, I am lost as a user

Apologies, I have linked an older design iteration. Fixed now.

**Comment by bosomt** [comment]
**QA OK**

nice!

![Image](https://github.com/user-attachments/assets/91e43a31-e493-450c-8221-658b33df5527)

**Info:**
 - Suite version: desktop 24.11.1 (9e9dadff47c5243bf4a10f539a898fe48da46506)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.5 regular (revision d72aab0bf75a9cfe6679da87efc4ac33382468dc)
 - Transport: BridgeTransport 2.0.33
