### ISSUE TITLE
Add filters for Exchange comparator

### ISSUE THREAD

**Issue by marek-andrsk** [trezor/trezor-suite#14462]
**Change of logic**
- In (Exchange) Comparator screen display all offers, including DEX, Floating CEX and Fixed CEX
- In Exchange form screen, always display Floating/Fixed rate switch (now it’s hiding when DEX is selected)

**Add filters for Exchange Comparator**

CEX/DEX filter:
- Default: All CEX and DEX offers
- Fixed-rate CEX
- Floating-rate CEX
- DEX

KYC filter:
- Default: All KYC options
- KYC never required

**Add section headlines for DEX / Floating-rate CEX / Fixed-rate CEX **

Copy for sections (on hover):
- Fixed-rate CEX: Lock in your rate for 15 minutes by paying a higher fee.
- Floating-rate CEX: Get an estimated rate that may adjust with real-time market changes.
- DEX: Decentralized exchange - trade crypto through blockchain transactions without a centralized intermediary.

**Design:**
https://www.figma.com/design/xSW1knAjH25SfOmqSdNioY/Trade?node-id=8953-49344&t=jIElVnYVBf01GcBU-4 

![image](https://github.com/user-attachments/assets/e09944bd-57ff-4a55-bcf4-7f6519fac28e)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.10.0 (acd58e6c26394eb09907791dd4006d03c130fe65)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
