### ISSUE TITLE
Build app from PR

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#14467]
- Add possibility to run the mobile app from PR easily for quick review and testing
- Rebuild native part only if necessary to optimize EAS costs

**Comment by matejkriz** [comment]
Note for QA: Please make sure you are able to use it and check this doc: https://www.notion.so/satoshilabs/Trezor-Suite-Lite-Preview-12adc526060680628b84d92dc8bf411a?pvs=4

**Comment by STew790** [comment]
**QA OK**
Works like a charm :tada: I was able to check the branch via the QR code.
