### ISSUE TITLE
Onboarding modals too wide

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14474]
**Describe the bug**
Onboarding modals too wide

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: web 24.10.0 (0c147a1d37dc615e286a114d90bc8b637bbb929f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: WebUsbTransport

**Screenshots:**

<img width="1441" alt="Screenshot 2024-09-23 at 12 47 20" src="https://github.com/user-attachments/assets/0a8c030d-73a8-4e30-9e04-dc444637a4d3">
<img width="1445" alt="Screenshot 2024-09-23 at 12 33 20" src="https://github.com/user-attachments/assets/7ad3b8a4-a6c3-4852-813d-2ac7eb3ded72">

**Comment by martykan** [comment]
@jvaclavik 
I think it's related to https://github.com/trezor/trezor-suite/pull/14441

**Comment by MiroslavProchazka** [comment]
@trezor/qa should be fixed in develop, please re-test

**Comment by jvaclavik** [comment]
Just tried develop and looks like it's fixed 

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/a31dfb1b-bd39-4a09-a092-c114ea38b84b">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.10.0 (03347b5e28587e194525d937b7943bc9836db435)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
