### ISSUE TITLE
Reset storage button in Settings/Application does not do anything

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14480]
**Describe the bug**
Reset storage button in Settings/Application does not do anything.
You only get `Storage cleared` notification but nothing is actually reset.

**Steps to reproduce:**
1. Navigate to `Settings/Application`
2. Press `Reset app`
3. Observe that nothing is reset

**Info:**
 - Suite version: desktop 24.10.0 (0c147a1d37dc615e286a114d90bc8b637bbb929f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="1421" alt="Screenshot 2024-09-23 at 14 32 13" src="https://github.com/user-attachments/assets/66cdd167-25dc-404a-b4f9-c1f774edf4b3">

https://github.com/user-attachments/assets/51aa2f03-ed01-4a0f-b93f-47f87fce29be

**Comment by evgenysl** [comment]
**Arm Mac** I have the same issue:
1. Reset app button
2. Trezor Suite minimizes into Dock
3. Wallets are not removed

On **Windows** Reset app works as expected. 
Trezor Suite fully restarts and wallets are removed.

**Comment by bosomt** [comment]
same results for `Settings/Debug/Wipe data` 
im not able to quit app after i try to reset/wipe it 

looks like every reset spawns one more binary in memory

<img width="825" alt="image" src="https://github.com/user-attachments/assets/50e6f986-539e-4a8c-8ccc-676ea19dfc29">

**Comment by komret** [comment]
Broken by https://github.com/trezor/trezor-suite/commit/f3a11183d459a1d8974d11d0d891aec1fb6a1c76 👀 @martykan

**Comment by mroz22** [comment]
On my machine, it works nicely provided I don't have the autostart feature enabled. To find out whether you have it enabled or not, please consult this issue too #14721

If what I am saying is correct, I suggest not cherry-picking fix for this into current release since A] I am afraid I could break something else, B] autostart is still in debug so it shouldn't affect typically users

**Comment by bosomt** [comment]
**QA OK**

https://www.notion.so/satoshilabs/fix-suite-desktop-app-reset-on-mac-14727-118dc5260606807eb564f97189559500?pvs=4

tested on `fix-mac-restart` branch

**Comment by bosomt** [comment]
**QA OK**

- retested on RC
- quit, reset app, wipe storage works as expected

**Info:**
 - Suite version: desktop 24.10.1 (3cbe786b5c8effd03b331faec20a41ef01d6671b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.10.1 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
