### ISSUE TITLE
The margin of the Card component isn't working

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14493]
## Describe the bug
The margin of the Card component isn't working.
![obrazek](https://github.com/user-attachments/assets/8877a9af-3dff-4347-b151-ed66098726a2)

## Expected behavior 
![obrazek](https://github.com/user-attachments/assets/a25cc00b-3e60-4fc2-9a10-5b49227326db)

**Comment by MiroslavProchazka** [comment]
@adderpositive  @trezor/qa should be fixed in develop, please re-test

**Comment by adderpositive** [comment]
it is perfect!  @MiroslavProchazka

**Comment by MiroslavProchazka** [comment]
Can I close it then?

**Comment by adderpositive** [comment]
Yes

**Comment by evgenysl** [comment]
**QA OK**
![Screenshot 2024-09-30 at 13 42 48](https://github.com/user-attachments/assets/7cf4673d-9533-4394-9f99-de06ae114a0a)
