### ISSUE TITLE
cancel from host - meta issue

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#14507]
## Cancel from host
_lets finally fix it everywhere_

There are a couple of button requests that may be cancelled from the host: 
- common button request (eg get address), basically whatever "confirm on device"
- passphrase
- pin (t1)

<img width="752" alt="image" src="https://github.com/user-attachments/assets/3245f828-e7b4-4f0d-9be5-414dea015e51">

All of these should have a cancel button available somewhere in UI.

As @szymonlesisz found, it didn't always work correctly and prepared a fix in #13925

please let's test the following matrix: 

|   	| Webusb  	| bridge 2.0.27 * 	| bridge 2.0.33  	|  bridge 3+  	|
|---	|---	|---	|---	|---	|
| get address  	|   	|   	|   	|   	|
| pin  T1	|   	|   	|   	|   	|
| passphrase  	|   	|   	|   	|   	|

* here you will likely not see cancel buttons in Suite.

Also please check these issues - they may be affected by the fix as well: 
- #14214
- #13777
- #12210

**Comment by bosomt** [comment]
**QA OK**

probably OK but when you cancel T1 pin dialogue with 2.0.27 bridge device freezes and does not respond to get address or add wallet command and needs to be reconnected @szymonlesisz @mroz22 
EDIT: follow up issue created

|   	| Webusb  	| bridge 2.0.27 * 	| bridge 2.0.33  	|  bridge 3+  	|
|---	|---	|---	|---	|---	|
| get address  	|   ✅ 	|   ✅ x button not available in app	|   ✅ |   ✅	|
| pin  T1.   	|   ✅ 	|  ❌   `Error: device disconnected during action` reported 	|   ✅ |  ✅	|
| passphrase  	|   ✅ 	|  ✅ 	|   ✅ |  ✅ 	|

**Info:**
 - Suite version: desktop 24.11.0 (17bac171ecd870c4d76bb64c6ec5f8d69b333d4c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.12.1 bitcoin-only (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33
