### ISSUE TITLE
BottomSheet refactor to better support other ScrollViews

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#14503]
1. From @matejkriz 

> I just faced the problem of scrolling up. It's possible, but the scrollview has to be moving, so you have to start scrolling down a bit and then scroll up, otherwise bottomsheet is closed instead 🙈 But I guess it's separate issue and minor.
[user-attachments/assets/b07c41da-856d-48d0-ae09-411d97769458](https://github.com/user-attachments/assets/b07c41da-856d-48d0-ae09-411d97769458)

2. Another issue is that when used with `isScrollable=false` it will fill nearly entire screen even if there is only few items - bottom sheet height is adapting to number of items in sheet, for example if there are only two items it will fill about 30% of screen.
3. Toast messages are hidden under BottomSheet - for example when you click Staking in Receive flow

We can either refactor BottomSheet or create some special bottom sheet for FlashList or maybe both with some shared primitives.

**Comment by Nodonisko** [comment]
This is follow up for #14487

**Comment by STew790** [comment]
**QA OK**
LGTM
**Info**
24.10.1   6f4c0b1
