### ISSUE TITLE
Restart of onboarding not working after backup is failed

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1451]
Restart of onboarding not working after backup is failed.
Please see video.
Onboarding offers and wipes your video but after that it's not working

https://drive.google.com/file/d/1-WXGJkcX-nErCA06BV_h9CQNcMuPJY5k/view?usp=sharing

**Comment by mroz22** [comment]
possible. but we also need @matejzak to answer the question - what shall happen if reset device, recovery device, backup device fails in onboarding. https://github.com/trezor/trezor-suite/issues/1078

**Comment by bosomt** [comment]
EDIT: it only happens when you: 
1) disconnect device during creatin of wallet
2) wipe device
3) create new wallet without reconnecting device

there is no restart of backup any more, but i think it got even worse ;(
see video please ;(
im not even able to backup device that was wiped

https://www.youtube.com/watch?v=vRPa86KeLl4&feature=youtu.be

**Comment by bosomt** [comment]
works fine now
