### ISSUE TITLE
Some legacy styles ignored due to nesting

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#14510]
Nesting `Text` in `Paragraph` and other components breaks some old styles because they are applied to the wrapper and overridden by defaults on the child. For example, the line starting with “Oops” in the screenshot should be red.

<img width="1293" alt="Screenshot 2024-09-24 at 13 39 26" src="https://github.com/user-attachments/assets/7bfe4ab1-0cd0-4512-b88c-29c5f47f0586">

**Comment by jvaclavik** [comment]
Should be solved here

https://github.com/trezor/trezor-suite/pull/14516

**Comment by bosomt** [comment]
**QA OK**


![Image](https://github.com/user-attachments/assets/f698de36-e125-4f6c-9723-4097587295e1)

**Info:**
 - Suite version: desktop 24.10.0 (03347b5e28587e194525d937b7943bc9836db435)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
