### ISSUE TITLE
URL icon update

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#14520]
The current URL icon doesn't look very good after we've unified all icons.
![Image](https://github.com/user-attachments/assets/16df5860-98a2-4b2c-9eab-b496ada51192)

Please replace it by the simpler [ArrowUpRight](https://www.figma.com/design/BdbvEYgjDdntL3haFcXRgV/%5BAssets%5D-Icons?node-id=1723-1867&t=RAYPigO6WlgyRfuJ-1) icon everywhere.
`ArrowUpRight` (in the outline version)

![Image](https://github.com/user-attachments/assets/5a52bb17-57bb-4290-9bdb-a3e96d95736b)

![Image](https://github.com/user-attachments/assets/0bbbe495-e565-4d5d-bf0b-45a2e96fe8fb)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.10.0 (3e1d4dff6ceb7a96cff59c4d15d223b0802366ca)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.0
