### ISSUE TITLE
Enabling coins on disconnected device should not be allowed

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1453]

**Comment by bosomt** [comment]
works fine
even when one is connected and one disconnected
then coins are only address to connected device
and new coins are loaded only after device is connected

**Comment by bosomt** [comment]
eject help says: Explanation what the 'eject wallet' button does
everything else works for me and approving
@mroz22 can you please change text of eject help button ? :)

**Comment by slowbackspace** [comment]
> eject help says: Explanation what the 'eject wallet' button does
> everything else works for me and approving
> @mroz22 can you please change text of eject help button ? :)

cc @matejzak copy needed
