### ISSUE TITLE
Trading - coin name all caps in list of available addresses

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14538]
**Describe the bug**
When buying coins coin name is all uppercase in list of addresses, see screenshots

**Steps to reproduce:**
1. Navigate to coinmarket buy section
2. Open list of available addresses when buying 
3. Observe coinname text

**Info:**
 - Suite version: desktop 24.10.0 (acd58e6c26394eb09907791dd4006d03c130fe65)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/user-attachments/assets/5ae4de52-adbc-47b7-b42b-ba60bba05081)
![image](https://github.com/user-attachments/assets/48095915-0067-4f0c-83fe-6f22a5b65253)

**Comment by bosomt** [comment]
Same in `Last transactions` section

<img width="1016" alt="image" src="https://github.com/user-attachments/assets/db85f68e-2270-4032-bda0-ade3404f43a6">

**Comment by tomasklim** [comment]
@bosomt please check develop if still available

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
