### ISSUE TITLE
Misaligned signs in tx detail and tx history

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#14548]
**Describe the bug**
Sometimes there are misaligned `+-` signs in tx history and tx detail page. Usually with larger numbers.

**Info:**

-   Mobile Suite Version: 24.9.2 https://github.com/trezor/trezor-suite/commit/7a4ddc9a8137951fe69c7693d4ac9e70511a39b4
-   OS: 
- 
**How to reproduce**

1. Open Suite lite
2. connect a device
3. Go to account details on `all` seed for example

**Screenshots**
![image](https://github.com/user-attachments/assets/b079549e-94bc-4c79-8bed-46f6f0bb72b2)
![image](https://github.com/user-attachments/assets/c252af33-9a4d-4e1b-a103-7d48896463ff)

**Comment by STew790** [comment]
**QA NOK**
The signs in the transaction detail still seems misaligned to me.
![image](https://github.com/user-attachments/assets/fb35e7ba-8eac-4b85-b9b3-4238894a0b17)

**QA OK**
The transaction history LGTM.

**Info**
24.9.2 https://github.com/trezor/trezor-suite/commit/b718af4a2b5d9fde28e1832276405f36a1c2399b

**Comment by vytick** [comment]
This is not  easily fixable in reasonable time and imo not worth the time. It happens only for very long amount of decimals (eth) and is only slightly off due to automatic downscaling of amount label due to too long string.

**Comment by STew790** [comment]
Ok, I will create a separate issue for this and approve this one. Thanks!
