### ISSUE TITLE
Small Connect Explorer improvements

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#14547]
- [ ] Align the headers so they are inline: 

<img width="814" alt="image" src="https://github.com/user-attachments/assets/9cb811eb-a85a-4ebb-be3d-9e2c9534535b"> 

- [ ] Make the header smaller. Maybe use the same font as "What is Canary release?"

<img width="354" alt="image" src="https://github.com/user-attachments/assets/55f05f06-5ee1-489a-a4e4-62610e632d88">

- [ ] Use **bold** instead of _italic_ .

<img width="251" alt="image" src="https://github.com/user-attachments/assets/2bc2bbca-a2c5-4e1f-8c7e-110501766efb">

- [ ] Fix the overflowing dot at the end of the paragraph.

<img width="832" alt="image" src="https://github.com/user-attachments/assets/26fd3178-0fc0-4c2c-a0b2-e0dcf7516ae2">

- [ ] Increase the vertical space above "Why use Canary release?" header.
<img width="899" alt="image" src="https://github.com/user-attachments/assets/44cf71be-7083-4d81-8cbb-6f48a44016eb">

**Comment by evgenysl** [comment]
**QA OK**
