### ISSUE TITLE
Coin Control: UTXO sorting

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#14545]
To improve UTXO management and simplify handling potential dust UTXOs, please add UTXO sorting to the Coin Control feature alongside the existing search field.

[Figma Design](https://www.figma.com/design/jsdvZlsY36rCc1E6PoItcz/Global-actions?node-id=4102-4590&t=OP9kyNRVbQpztKsT-1)

MVP: Add a select menu to the right of the Search input and allow sorting accordingly.

2nd stage: Coin Control sidebar

**Comment by bosomt** [comment]
**QA OK**

very nice implemented
but search works odd, trying to search via address that i see in CC list
not sure why and how it behaves, trying to find `3M` or `NH` 
search by inputs and outputs address does not work :(

search by label or txid works as expected

@Hermez-cz @komret follow up issue ?

https://github.com/user-attachments/assets/7070f68d-2ef6-4dc2-a6d4-e532339d4e17

**Info:**
 - Suite version: desktop 25.1.0 (7daeb57b631e7e306bc3282476941420944bfeda)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
