### ISSUE TITLE
Coinmarket - Implement New crypto-picker modal

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14550]
## Description
- Replace Select with Select modal of assets in Swap & Buy
- Search should allow to input crypto name, symbol, contract address or network name
  - Placeholder copy: Search by name or paste address
- Networks filter: this works as radio button, only one can be selected and it’s static list, not all available networks will be listed
  - Ethereum
  - Polygon
  - Solana
  - BNB Smart Chain

## Design
- design in [Figma](https://www.figma.com/design/xSW1knAjH25SfOmqSdNioY/Trade?node-id=8971-55712&t=QpRBy6vtRcqZtP81-1)
### Before
**In Buy section**
![image](https://github.com/user-attachments/assets/67b34d64-3aa9-44a3-8301-b8b2d708dcc9)
**In Exchange section**
![image](https://github.com/user-attachments/assets/09335ec0-38d6-40ce-8827-43f4e0099964)
###  After
![Screenshot 2024-10-01 at 12-57-59 Trade](https://github.com/user-attachments/assets/6d207b2a-b4a3-4212-985e-e2d87d4bb087)
![image](https://github.com/user-attachments/assets/2a36ecc7-7e96-4f72-a508-81e4ee6ce041)
![image](https://github.com/user-attachments/assets/ca626275-ae46-4139-bac7-0606e5d285db)
![Screenshot 2024-10-01 at 12 59 19 PM](https://github.com/user-attachments/assets/99fcfffb-971a-4341-81da-56774ccf9455)
![image](https://github.com/user-attachments/assets/a0704e9d-171b-43a5-b861-e9c45a0f4caa)
![Screenshot 2024-10-01 at 12 59 05 PM](https://github.com/user-attachments/assets/4eb5d360-c59f-4faa-b4a6-2184e3acf649)

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/dbcd9b8e-6dac-45a4-8c37-b895feb91de5)

**Info:**
 - Suite version: desktop 24.10.1 (3017e5864a176715b1023945397ef49e8aa24d5e)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.10.1 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
