### ISSUE TITLE
Turn off firmware revision check KB URL

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#14557]
Please add a Learn more button in Settings > Device > Danger area > Turn off firmware revision check

Link it to: https://trezor.io/learn/a/trezor-firmware-revision-check

![Image](https://github.com/user-attachments/assets/db7cd75c-ae35-451c-baff-3c10fd299f06)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.10.0 (03347b5e28587e194525d937b7943bc9836db435)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
