### ISSUE TITLE
You can load custom homescreen that doesn't fit resolution of device

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1455]
See photo, you can load T1 background to TT homepage

![photo_2020-04-07_09-14-15](https://user-images.githubusercontent.com/31506317/78640566-4545c900-78b0-11ea-96e2-8e758a73689e.jpg)

**Comment by bosomt** [comment]
problem is that you can load any picture, smaller or bigger and suite will load it do TT :)

**Comment by bosomt** [comment]
Still same

**Info:**
 - Suite version: web 21.7.1 (24cc565a3badd85ab48b30348022471dfd85f90e)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.2 regular

**Comment by glacierbits** [comment]
Closing in favor of #1157
