### ISSUE TITLE
Third-party cookies handling

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#14556]
Third-party cookies will be blocked in a future Chrome version. This might affect the desktop app and sldev.cz domain. See the warnings in console when you open the Trade section. More info [here](https://developers.google.com/privacy-sandbox/cookies/prepare/overview).
![Screenshot 2024-09-26 at 15 32 41](https://github.com/user-attachments/assets/6a9cfe70-c4a6-4ff9-8968-93b862f54587)

**Comment by LukasRada** [comment]
We have disabled the third-party cookie. Feel free to test it and close it. I did not see the warning anymore.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.10.0 (2187dc0a75fc5ffb03e51b661ff61952c5159ebf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.0
