### ISSUE TITLE
Coinmarket - sell process stucked

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14569]
## Bug description:
There is a bug on the Trezor Suite sell feature - when choosing a MoonPay provider, there is a “Waiting for MoonPay address” infinite loading.

## Replication steps
https://github.com/user-attachments/assets/183386a8-6bca-4c3d-88e1-05f1b7901118

**Comment by misartomas** [comment]
Fix checked - now the Moonpay address is generated correctly:
https://github.com/user-attachments/assets/1f7b0fc5-d588-4af2-963d-e28b146730b0
