### ISSUE TITLE
BTC only Send max button is not working when address is not valid

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1457]
Send max button is not working in send dialogue when address is not valid.

See video. Very low priority.

https://youtu.be/kWlhMWL4yTQ

**Comment by bosomt** [comment]
still broken

**Comment by wendys-cats** [comment]
**Issue still persists**

**Info**
**OS:** nixos
**Browser:** Chromium Version 83.0.4103.61 (Developer Build) (64-bit)
**Wallet Version:** branch suite-web/send-new-version/ #1966
**COMMIT HASH** 16ed6dd
**Firmware Version:** model TT 2.3.1 and T1 1.9.1

**Comment by sorooris** [comment]
**QA NOK**
Issue still persists.

> Wallet Version: web, 20.9.1 cf1f180
OS: NixOS
Browser: any supported (tested Firefox 79.0)
Device: Model 1 1.9.3 0d5f00668

![Peek 2020-09-08 20-47](https://user-images.githubusercontent.com/10185314/92515934-b0efe180-f214-11ea-9a6a-8082fd8b6e60.gif)

**Comment by bosomt** [comment]
**QA OK**

works fine now

Nixos + CHromium 85
Suite web dev master commit a64816b985a74b1493eac2f76311722ceabbdb8f
FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,

**Comment by sorooris** [comment]
**QA OK**

Suite Version: web, f24640d
OS: NixOS
Browser: Chromium 85.0.4183.102
Device 2.3.3 0d5f00668

Confirming correct behavior of the setMax/Send max. button.
