### ISSUE TITLE
MATIC to POL

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14589]
Change app to use `POL` for Polygon. Do proper migration

**Comment by bosomt** [comment]
Notion task to test this migration properly
https://www.notion.so/satoshilabs/MATIC-to-POL-symbol-renaming-110dc526060680508141e2e88e5c83cf

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.10.0 (03347b5e28587e194525d937b7943bc9836db435)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33
