### ISSUE TITLE
BIP322 Message signing

### ISSUE THREAD

**Issue by kvhnuke** [trezor/trezor-suite#14596]
Hi
I was wondering whether you have any plans to support bip322 message signing.
I see some work has been done on trezor-firmware side, is there any plans to add the feature to trezor-connect?

Thank you

**Comment by Hannsek** [comment]
Hi, we are looking into the possibility of adding it. But nothing is yet planned for the near future in both Connect and Firmware.

**Comment by kvhnuke** [comment]
> Hi, we are looking into the possibility of adding it. But nothing is yet planned for the near future in both Connect and Firmware.

Ah got it! Thank you!
I saw this line https://github.com/trezor/trezor-firmware/blob/a1d9975507bf5bc272946855219fbac40221e10f/core/src/apps/bitcoin/scripts.py#L639
and thought it was already in the firmware, now I realize it is for something else
