### ISSUE TITLE
Learn more button elevation in Staking dashboard

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#14598]
<img width="1328" alt="image" src="https://github.com/user-attachments/assets/db2f95b5-fdd1-4057-9177-ccf7bd63c749">

**Comment by bosomt** [comment]
**QA OK**

<img width="126" alt="image" src="https://github.com/user-attachments/assets/1d7f91a2-cb54-4c27-b15e-575edcc5daac">

**Info:**
 - Suite version: desktop 24.10.0 (47e5dcd72e9b988793f51cd6a576714de69c8260)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.0
