### ISSUE TITLE
Add Chinese simplified as a community language

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#14604]
As we have 100% of strings in Chinese simplified translated, it is time to promote this language to a "community" language. 
Slack discussion about this topic [here](https://satoshilabs.slack.com/archives/C04FLM3PZAB/p1727513564114809)

**Comment by STew790** [comment]
**QA OK**
LGTM

**Info:**
 - Suite version: web 24.10.0 (96edcf3fe43646e971c58e66ef45cdfcf5aa1032)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T1B1 1.9.0 regular (revision 0b7a8449f8dd003fc415262b05102d113247d3de)
 - Transport: BridgeTransport 2.0.33
