### ISSUE TITLE
Unexpected text in `Copy contract address` modal

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14606]
**Describe the bug**
Unexpected text in `Copy contract address` modal.
To copy contract address you have to press `Unhide` button. /That renders `Copied to clipboard` notification/
I would expect copy or confirm button and not `Unhide` button

**Steps to reproduce:**
1. Load account with tokens
2. Navigate to token section
3. Press ... and select Contract address section

**Info:**
 - Suite version: desktop 24.10.0 (03347b5e28587e194525d937b7943bc9836db435)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="682" alt="Screenshot 2024-09-29 at 8 43 18" src="https://github.com/user-attachments/assets/78d4be62-448b-432a-87e4-8717c2589ec0">

**Comment by STew790** [comment]
Fixed here https://github.com/trezor/trezor-suite/issues/15242
