### ISSUE TITLE
EVM Tokens / Token icons bundle

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14611]
**Description:** 
Create a component displaying bundle of most valuable tokens (biggest $ sum) on user's account in sidebar and dashboard asset table.

- [x] Create token bundle component
- [x] Use it in sidebar

[Figma](https://www.figma.com/design/o6eb4wUMjSu5xMb34423vh/Tokens?node-id=4637-5677&t=hkw49OUQAXdX1OUH-1)

**Current state:**
![Screenshot 2024-09-30 at 10 01 28](https://github.com/user-attachments/assets/27a7d168-fe88-4b84-8fc6-515b23ae773e)

**Future state:**
**1 icon**
Icon 24x24
<img width="333" alt="Screenshot 2024-10-02 at 14 22 08" src="https://github.com/user-attachments/assets/913b47ba-1bff-49dd-b22a-d7640b5b22eb">

**2 icons**
Icons size 16x16 but try to use 24x24 image
<img width="331" alt="Screenshot 2024-10-02 at 14 22 20" src="https://github.com/user-attachments/assets/f87ebc83-83c4-49ff-90e4-8568e1787e33">

**3 icons**
<img width="333" alt="Screenshot 2024-10-02 at 14 22 28" src="https://github.com/user-attachments/assets/cca9bb13-9d1c-446c-a60f-dd7034e261e5">

**4+ icons**
The last one is just grey coin
<img width="316" alt="Screenshot 2024-10-02 at 14 22 40" src="https://github.com/user-attachments/assets/5c86875e-aa51-4a52-9d28-4e5335a37ddb">

**Error/Loading state**
Error - there is first char in the coin (that's already implemented)
Loading state - Maybe it should be grey and then with transition it should change to the image? Let's investigate when you implement it

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.11.0 (0f49b0fadd15e07a61d4fb88d47a4f7e2d5158db)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: WebUsbTransport
