### ISSUE TITLE
Change Validation Trigger for First Name and Last Name Fields to On-Typing

### ISSUE THREAD

**Issue by osikovsky** [trezor/trezor-suite#14612]
Currently, the validation for the First Name and Last Name fields appears when the user clicks outside of the input fields. We need to modify the behavior so that the validation message appears while the user is typing.

**Comment by tomasklim** [comment]
Should this be in Trezor Suite repo? @osikovsky

**Comment by MiroslavProchazka** [comment]
Please post this to trezor.io repository, closing for now
