### ISSUE TITLE
Mobile device management - change PIN

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#14616]
[Figma](https://www.figma.com/design/yY9Zl2jXLKXVV3CwuBmaMU/Manage-device?node-id=367-2922&t=um4cRUycAW4gJnBL-1)

**User can change PIN of the device in Device settings**

- If user has PIN disabled (not set) he can only Enable
- When user clicks on Enable he is prompted to continue on Trezor and confirm it there
- T1
- if user has PIN protection enabled and wants to change on T1, he clicks on Change and is prompted to confirm on Trezor. Then he is prompted to enter current PIN on mobile screen, then enters the new PIN on mobile screen.
- If user wants to disable PIN protection on T1, he clicks on Disable and is prompted to confirm it on Trezor device, then enters current PIN on mobile screen.

**Other models**

- If user has PIN protection enabled and wants to change, he clicks on Change and is prompted to confirm on Trezor. Then he is prompted to enter current PIN on Trezor device, then enters new PIN on Trezor Device
- If user wants to disable PIN protection, he clicks on Disable and is prompted to confirm it on Trezor device, then enters current PIN on Trezor device

**Comment by STew790** [comment]
**QA OK**
- tried the PIN on T1 and TS5
- I was able to enable/disable/change the PIN
- cancel at any point (either on device or on host) worked just fine and I always returned to the settings page

**Info**
24.10.2 https://github.com/trezor/trezor-suite/commit/17d794f5dee37026247df980bdccae1f7e489cae
