### ISSUE TITLE
Mobile device settings - device settings screen

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#14618]
[Figma](https://www.figma.com/design/yY9Zl2jXLKXVV3CwuBmaMU/Manage-device?node-id=367-3045&t=um4cRUycAW4gJnBL-1)

- User is able to see the image and name of his model in device settings
- User can see and interact with all 3 new sections of device settings (PIN protection, Device authenticity check, Firmware)

**Comment by STew790** [comment]
**QA NOK**
Device auth check is not yet done.

**Comment by STew790** [comment]
**QA OK**
Screen LGTM.

**Info**
24.10.2 https://github.com/trezor/trezor-suite/commit/e4365278aa8be68324c41f57fa796f9b4ee631f9
