### ISSUE TITLE
Mobile device management - enable/disable PIN

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#14615]
[Figma](https://www.figma.com/design/yY9Zl2jXLKXVV3CwuBmaMU/Manage-device?node-id=367-2923&t=um4cRUycAW4gJnBL-1)

- Use can enable or disable PIN for device

**Comment by STew790** [comment]
**QA OK**
Already approved here https://github.com/trezor/trezor-suite/issues/14616
