### ISSUE TITLE
Suite reloads when you try to wipe locked T1 device

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1462]
See video.
Suite reloads when you try to wipe PIN locked T1 device.
So if you forget PIN you can't wipe it in suite

Fw 1.9.0

https://www.youtube.com/watch?v=GWZtvVf6QmM&feature=youtu.be

**Comment by mroz22** [comment]
Video show clearing storage, not wiping device. It actually did not enter device settings at all

**Comment by bosomt** [comment]
LOL sorry, i thought clear storage wipes storage ;)
