### ISSUE TITLE
Not able to communicate via WebUSB on Arc browser

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#14634]
Arc Version 1.61.2 (54148)
Chromium Engine Version 129.0.6668.71

I tried it on 1inch and Adalite.

![image](https://github.com/user-attachments/assets/913df271-6a65-4676-ad55-436b41877746)

**Comment by martykan** [comment]
Not a problem on our side and not a problem of Arc either, they are simply on old versions:

1inch - v9.1.4
Adalite - v9.3.0

Minimum v9.4.0 is needed for WebUSB to work on 3rd party sites

**Comment by Hannsek** [comment]
Ah, ok, didn't check their version…
