### ISSUE TITLE
Polygon - receive adjustments for tokens

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#14631]
- [x] adjust copy for receiving token on all token enabled networks
- [x] show correct network

<img width=300 src="https://github.com/user-attachments/assets/f819679c-fc57-4c9b-8fc9-ae12c42df017" />

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/b2c3a372-49d0-4121-bda0-d7a255e8c7ab)
![image](https://github.com/user-attachments/assets/69cdbac1-f5f5-4d8d-956f-be10ee1b8e54)
![image](https://github.com/user-attachments/assets/f9071aea-29f3-441f-b6f4-2ee4ba521dfd)
![image](https://github.com/user-attachments/assets/666e984c-12fb-4549-b18e-acf776d7498e)


**Info**
24.11.1 c214aa3
