### ISSUE TITLE
webusb/bridge detection

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#14639]
bridge detection might still be in trouble. see:

<img width="1461" alt="image" src="https://github.com/user-attachments/assets/26cd6d1c-6266-4f20-af3a-a98c1f9fdb76">

also exodus suggests installing bridge even though it is already running 

![image](https://github.com/user-attachments/assets/9ffbca2f-50c9-41bc-803a-3e3eb789a53e)

could it be connected with the new bride format version we are now serving from the `/` endpoint?

**Comment by mroz22** [comment]
also this:
we say there is 2.0.27 version running. this is a bug.

<img width="1183" alt="image" src="https://github.com/user-attachments/assets/dae62aff-2530-46b9-8050-012ca7aab6d7">

**Comment by bosomt** [comment]
**QA OK**

- download link works as expected
- Open the Trezor Suite desktop app anchor link works as expected
- both versionbs of bridge are correctly detected

![Image](https://github.com/user-attachments/assets/d3e9e184-00c7-477c-a9b5-232d3e0e84a1)


![Image](https://github.com/user-attachments/assets/261e15fa-2616-48e4-8661-35ddce4f22d5)


**Info:**
 - Suite version: web 24.11.0 (21955fdc4a6d847a4838beada0e4abfd539749d8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.1
