### ISSUE TITLE
ERC20 tokens missing in Dashboard

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1463]
We are missing ERC20 tokens  in Dashboard
At least those that have any fiat value

Very low priority. Maybe just list them as one coin named ERC20 tokens  taht will show sum of all of them ?

![image](https://user-images.githubusercontent.com/31506317/78667884-04fb4080-78da-11ea-9762-01cbce657bc8.png)

![image](https://user-images.githubusercontent.com/31506317/78667917-13495c80-78da-11ea-9b5b-4b1432ebdfb5.png)

**Comment by Oliv95** [comment]
Any idea when this might be added?

**Comment by glacierbits** [comment]
Will be solved by new dashboard (~ Q4 21')
