### ISSUE TITLE
Change "Forbidden key path" for EVM legacy accounts

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14638]
EVM legacy paths are not available on old fw versions (e.g. 2.5.3TT). Instead of skipping it for old fw, let's change the text to something like:

`Ethereum Legacy: Update firmware to discover this account`

![Screenshot 2024-09-30 at 14 24 17](https://github.com/user-attachments/assets/8b8b2c92-1374-4dd9-80ca-58c9da2f433e)

**Comment by evgenysl** [comment]
**QA OK**

https://github.com/trezor/trezor-suite/pull/14648#issuecomment-2386058009
