### ISSUE TITLE
Transactions older than year are missing in graph and transaction count

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1464]
See screen, I see transactions but from 2018 or less.
At least please add transactions counter, it looks really strange to see 
**NUMBER OF TRANSACTIONS
0 transactions**
and then transactions underneath it 

![image](https://user-images.githubusercontent.com/31506317/78673953-2ad91300-78e3-11ea-9754-c9996d358fc4.png)

**Comment by slowbackspace** [comment]
ok, let's try to do "all" button into to graph (and making it as default view) with some client-side caching and hope we won't kill blockbook.

**Comment by bosomt** [comment]
BTC accounts are OK
but when I add different coins graph and transaction counts are not loaded and i have to hit reload button next to graph. 

is this proper behavior ?

![image](https://user-images.githubusercontent.com/31506317/79886636-91892100-83f9-11ea-96df-396e1c75b312.png)

![image](https://user-images.githubusercontent.com/31506317/79886664-a2d22d80-83f9-11ea-9245-5bc3ad55c84a.png)

**Comment by bosomt** [comment]
BTC accounts are OK
but when I add different coins graph and transaction counts are not loaded and i have to hit reload button next to graph. 

is this proper behavior ?

![image](https://user-images.githubusercontent.com/31506317/79886636-91892100-83f9-11ea-96df-396e1c75b312.png)

![image](https://user-images.githubusercontent.com/31506317/79886664-a2d22d80-83f9-11ea-9245-5bc3ad55c84a.png)

**Comment by slowbackspace** [comment]
@bosomt certainly not proper, just not implemented 😬
