### ISSUE TITLE
Can't paste number with whitespace to number input

### ISSUE THREAD

**Issue by Lemonexe** [trezor/trezor-suite#14654]
**Describe the bug**

When pasting a number into number field with whitespace at the end, for example `0.1 ` to `Amount` field in send form. It  errors out the textfield

**How to reproduce**

1. Go to any coin
1. Click on Send
1. Paste a number, even a very short one, with whitespace at the end 
1. It errors out :x:
2. Press backspace and type a number, only now it will be correct :heavy_check_mark: 

**Expected behavior**
It should correctly parse the string.

**Screenshots**
![image](https://github.com/user-attachments/assets/02569be3-f210-4b5c-9bcd-aa37ad2ffd31)
![Screenshot 2024-10-21 at 13 01 03](https://github.com/user-attachments/assets/30f9f27e-6255-4f46-9cb6-160eb3232082)
![Screenshot 2024-10-21 at 13 00 38](https://github.com/user-attachments/assets/758c8b6f-330c-4519-8a2d-b325f6b8087a)

**Comment by Harshit-0020** [comment]
Hi @Lemonexe 👋, I’m a newcomer to the project. I wanted to ask if it would be alright for me to work on this issue.
If yes, then should I follow the steps in [Developement](https://github.com/trezor/trezor-suite?tab=readme-ov-file#development) section of readme to setup the environment.
Also if you could provide any hint/guide as to where the bug might be occurring ?

_EDIT:_ 
Shoot! I think @tomasklim assigned it to himself just now 😅. I'll look for some other open bug. Apologies for the inconvenience.

**Comment by komret** [comment]
Hey @Harshit-0020, any help is much appreciated! Once you get the project up and running, check out the list of [good first issues](https://github.com/trezor/trezor-suite/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+) to start!

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.12.0 (4258d1c3c5bfcc405e73e48ea633f0bdf62f4d80)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport
