### ISSUE TITLE
Transactions: Various types

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1465]
Reported by @slush0 

Docs: [**How to**](https://docs.google.com/document/d/1G3Vm5vC-CTDUyWP8vaIZBxNfYeYCbJC5ymAlLPSqGNk/edit#heading=h.cwhrqs43phw5) 

Design: **[Zeplin](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5eaac8c28b7dc7272d31a615)**

**Comment by slowbackspace** [comment]
need more info 😬

**Comment by slush0** [comment]
That's why it is assigned to Matej and not devs :).

**Comment by sorooris** [comment]
@matejzak @slush0 Cooperation with the Coinbase transaction is needed.
Until then the issue won't be considered fully tested.

**Comment by sorooris** [comment]
bump

**Comment by sorooris** [comment]
Bump McBumperson.

**Comment by sorooris** [comment]
Again, we need some help with the Coinbase transaction since we in QA cannot make one ourselves.
cc @matejzak please assist
bumpity bump
![image](https://user-images.githubusercontent.com/10185314/84261308-d7ba5100-ab1b-11ea-97f1-a9c66e2876fd.png)

**Comment by glacierbits** [comment]
Talked to Slush, we are unable to provide the coinbase tx type for testing at the moment. However, good news is, this will be handled by automated testing (ongoing project by @mroz22 and @tsusanka).
