### ISSUE TITLE
Missing icons in TokenRow

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#14666]
<img width="1162" alt="image" src="https://github.com/user-attachments/assets/0df2aa4b-b1b5-4bb0-a68a-90b84ff39ef4">

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/32f613fa-ea54-454a-8532-beb30c43a04a)

**Info:**
 - Suite version: web 24.10.0 (bfe42f2d115a933baeb1c44901ebcae176e1e1e8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
