### ISSUE TITLE
Take BNB out of experimental features

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14672]

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.11.0 (f98f57023fd18f78a805443001e5a08ada0fef80)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
