### ISSUE TITLE
Send coins - old flow outputs (Trezor M1)

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#14678]
The Trezor M1 supports only FW of version <= 1.x.x. That means that the set of on-device send review outputs is constructed according to the old send flow ([see this](https://github.com/trezor/trezor-suite/blob/18eb018eba350e02573f531f5ae51b3c3b952f3f/suite-common/wallet-utils/src/reviewTransactionUtils.ts#L337)). As a result, there might be `regular_legacy` and `fee` outputs present in the review.

## Acceptance criteria
Are outputs of old flow correctly handled, and the user can do a device review using Trezor model 1.

**Comment by STew790** [comment]
**QA OK**
I was able to send coins with T1 with a correct review.
**Info**
24.9.2 b718af4
