### ISSUE TITLE
Coinmarket - BTC-only firmware should display only BTC in Buy

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14693]
## Description 
- Bitcoin-only hardware is limited so that Swaps are not showing, we should also limit Buy to Bitcoin only.
- `You buy` dropdown should be displayed to indicate BTC, but disabled.
![image](https://github.com/user-attachments/assets/4169eb96-f776-4f33-a5c2-bdb13d062b9d)

**Comment by bosomt** [comment]
**QA OK**

only BTC is available to buy when device has BTC only firmware
as Trezor Suite allows to buy to accounts that are not linked to your device users with BTC only firmware are not allowed to buy any other coins or tokens that are supported or not supported by Suite

**Info:**
 - Suite version: web 24.11.0 (03d398390665c7c1d3a044d5d93ea0d6adde5dac)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 bitcoin-only (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
