### ISSUE TITLE
Skip PIN & Backup copy improvements

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#14712]
Please improve the body text copy for the Skip Backup and Skip PIN modals. It can't be done in Crowdin, as there it's just one translation key `TR_DO_YOU_REALLY_WANT_TO_SKIP` 

We need to create two new keys, separate ones for skipping Backup and skipping PIN. Let's not recycle the original one to avoid mistakes in translations or similar.

New copy for skip Backup:
`A wallet backup lets you recover your funds if your Trezor is lost, stolen, or damaged. Without a backup, you could lose access to your crypto permanently.`

New copy for skip PIN: 
`A device PIN prevents unauthorized access to your Trezor. Without it, anyone with your device can access your funds.`

![Image](https://github.com/user-attachments/assets/e8a3adf8-1cd3-48c5-83c9-3f8068f9399c)
![Image](https://github.com/user-attachments/assets/5242c666-336c-424d-b769-4c7126e100fe)

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/ed52691e-62b1-4666-83df-69bb376d96f3)

**Info:**
 - Suite version: desktop 24.11.0 (e1fe4b85d4885e52a080798539b215c6366afeaa)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.12.1 bitcoin-only (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33
