### ISSUE TITLE
Missing info in Explorer about discovery options based on addresses

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#14719]
Connect Explorer doesn't inform about option to use specific address in getAccountInfo() to discover transactions related to address instead of xpub.

Probably it might be better to have specific method for it? 
For example like https://mempool.space/docs/api/rest#get-address-transactions
Which btw allows you to enter multiple addresses at once.

**Comment by evgenysl** [comment]
**QA OK**
![Screenshot 2024-10-22 at 07 07 08](https://github.com/user-attachments/assets/e95b0a60-1f05-4274-976e-b8eb7f40512f)
