### ISSUE TITLE
Confirming recipient address outside Trezor app freezes Trezor

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#14716]
When sending BTC, switching to another application to review the presented recipient address and pressing confirm whilst outside of Trezor Suite freezes the Trezor

1. Send BTC
2. See recipient address
3. Switch to another application
4. Press confirm

https://github.com/user-attachments/assets/89669e83-6415-49a3-b5a4-1c85a58cbd33

**Comment by STew790** [comment]
**QA OK**
I was able to confirm the address outside of app and get back to app to sign the transaction and send it.

**Info**
24.10.1 cb2d5d1
