### ISSUE TITLE
Use Blockbook network param

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14724]
Use `network` instead of `shortcut` for identification that Blockbook backend is correct for specific network.

Right now it is allowed, to set Arbitrum, Base and Optimism BlockBooks as custom backend of Ethereum.

https://github.com/trezor/blockbook/commit/a0960c8e1760497d9c04a0cd8507243cb208b181

When solving this issue, please contact @martinboehm to fix wrong `network` param (would be good to check all blockbooks we use that it is correct, for everything except BNB Smart Chain, Base, Arbitrum, Optimism, the network param should equal to shortcut param)

## Example

You can test it on Blockbook https://op1.trezor.io/test-websocket.html -> `Login` -> `getInfo`

**POL**
- ok, both same
```
{"name":"Polygon Archive", "shortcut":"POL", "network":"POL", "decimals":18, "version":"0.4.0", "bestHeight":65190373, "bestHash":"0x8fa5a81c314eb554e2a6da2a5fc4c675832cd1252e6835057d838ceda3a9e612", "block0Hash":"0xa9c28ce2141b56c474f1dc504bee9b01eb1bd7d1a507580d5519d4437a97de1b", "testnet":false, "backend":{"version":"bor/v1.4.1/linux-amd64/go1.22.2"}}
```

**OP**
- ok
```
{"name":"Optimism Archive", "shortcut":"ETH", "network":"OP", "decimals":18, "version":"0.4.0", "bestHeight":128985334, "bestHash":"0x057205997c41658b85297c10040954795454b64f0a93acf95165785330c1595a", "block0Hash":"0x7ca38a1916c42007829c55e69d3e9a73265554b586a499015373241b8a3fa48b", "testnet":false, "backend":{"version":"Geth/v1.101411.2-stable-3dd9b027/linux-amd64/go1.23.3"}}
```

**BSC**
- wrong, shortcut should be `BNB`, but network should be `BSC`
```
{"name":"BNB Smart Chain Archive", "shortcut":"BNB", "network":"BNB", "decimals":18, "version":"0.4.0", "bestHeight":44662844, "bestHash":"0xec24a8a43eec0df465faf2d20f22bd99c50a5df258ace1c6a16b899cad88d3aa", "block0Hash":"0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b", "testnet":false, "backend":{"version":"Geth/v1.4.15-ec318b9c/linux-amd64/go1.21.13"}}
```

**BASE**
- wrong, shortcut should be `ETH`, network should be `BASE`
- https://github.com/trezor/trezor-suite/issues/15817 (dev mode)
```
{"name":"Base Archive", "shortcut":"ETH", "network":"ETH", "decimals":18, "version":"0.4.0", "bestHeight":23390061, "bestHash":"0xb950a8180fbeb1d266fbf67032c0d8bf1c71fc0355d524c9985b248430ef476b", "block0Hash":"0xf712aa9241cc24369b143cf6dce85f0902a9731e70d66818a3a5845b296c73dd", "testnet":false, "backend":{"version":"Geth/v1.101411.0-stable-d5a96613/linux-amd64/go1.22.6"}}
```

**ARB**
- wrong, shortcut should be `ETH`, network should be `ARB`
```
{"name":"Arbitrum Archive", "shortcut":"ETH", "network":"ETH", "decimals":18, "version":"0.4.0", "bestHeight":282264405, "bestHash":"0xecea30ff921ef03f8ce7f11f32330ae70847acacd045bb4ff31602c03b77fd16", "block0Hash":"0x7ee576b35482195fc49205cec9af72ce14f003b9ae69f6ba0faef4514be8b442", "testnet":false, "backend":{"version":"nitro/v3.2.0-f847be0/linux-amd64/go1.21.10"}}
```

**BTC**
- ok 
```
{"name":"Bitcoin", "shortcut":"BTC", "network":"BTC", "decimals":8, "version":"0.4.0", "bestHeight":873644, "bestHash":"000000000000000000010ecb9c4056788261accae9e641e9574c60659b4b5a62", "block0Hash":"000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f", "testnet":false, "backend":{"version":"280000", "subversion":"/Satoshi:28.0.0/"}}
```

**Comment by martinboehm** [comment]
@tomasklim @adderpositive it is fixed in Blockbook and currently being deployed to production. Also, Arbitrum is finally synced and will be put to production.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 25.1.0 (56ad6e595587664274434bcf78b5fdc5b24326ea)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e3183e58f35f6bd6b98fc9262434abb773f6ae9a)
 - Transport: WebUsbTransport
