### ISSUE TITLE
autostart changed in OS setting not reflected

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#14721]
1. go to debug 
2. turn on autostart
3. go somewhere else
4. turn off autostart in system settings 
5. go back to debug menu - autostart still appears to be on, should be off

<img width="758" alt="image" src="https://github.com/user-attachments/assets/fb9124c5-61eb-49cb-aa85-a167131674c4">

![image](https://github.com/user-attachments/assets/19bf6088-5dda-456a-bc07-36d559f91382)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.0 (a741e65bfdb64ec9ec7a37f7d4288c7d5ac57a86)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
