### ISSUE TITLE
Introduce network symbol display name

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14725]
Some networks have different native coin shortcut than is the shortcut of network itself

Suite is not ready for:
`BNB` to `BSC`
`OP` to `ETH`
`BASE` to `ETH`
`ARB` to `ETH`

- [ ] Unify occurrences of `NetworkSymbol`. Use naming `symbol` as is used by Blockbook. 
  - symbol in the codebase is called by `asset`, `coin`, `logo`,... we should unify so that it is easier to do ⬇️ 
  - sometimes the symbol is not typed as `NetworkSymbol` but by `string`, fix that
- [ ] Introduce `displaySymbol` (or better naming) and replace `symbol` on places where it is presented to a user

NetworkSymbol can be btc, eth, sol,...

Some networks (Optimism, BNB Smart Chain, Base,...) have different identificator of the network (op, bsc, base) than native coin (eth, bnb, eth). We need to introduce also something like DisplaySymbol, NativeSymbol, NativeCoin,... name TBD

Unfortunately Connect uses coin, Blockbook uses symbol, so we should stick to using symbol as we do not want to transform data.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 25.1.0 (102be08a4eddf031a463e2907f96a9d45d9d748f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.7 regular (revision 8a254aa8eae82f99630df63f40e4d290066a3efc)
 - Transport: WebUsbTransport
