### ISSUE TITLE
Tor cannot be connected

### ISSUE THREAD

**Issue by btclinux** [trezor/trezor-suite#14731]
Trying with Snowflake and pure. How to view Tor debug logs?

**Comment by karliatto** [comment]
@btclinux what is the operating system that you are using?

If you want to see the logs of Trezor Suite you can run it from the terminal it like 
```bash
./Trezor-Suite-24.9.2-linux-x86_64.AppImage --log-level=debug
```

If you are using Tails OS we have an open issue for that https://github.com/trezor/trezor-suite/issues/5819 and the fix is coming soon.

**Comment by btclinux** [comment]
OS: Ubuntu 22.04

So it stuck on

```
INFO(tor): Bootstrap - 10% - Connected to a relay
```
with and without snowflake and then killed by timeout in ~3 minutes.

```
ERROR(tor): Failed to start: Timeout waiting for TOR control port: 
connect ECONNREFUSED 127.0.0.1:40223
```

Is it possible to use alternative bridge parameters as explained here https://forum.torproject.org/t/fix-problems-with-snowflake-since-2024-03-01-broker-failure-unexpected-error-no-answer? Or maybe increase the timeout. Or allow to use obfs4 bridges using transport executable as in snowflake case

**Comment by karliatto** [comment]
@btclinux have you tried using a VPN and then try to enable Tor?

>  Or maybe increase the timeout.

I don't think increasing the  timeout will help here. 3 minutes should be enough. Does Tor browser work for you?

>  Or allow to use obfs4 bridges using transport executable as in snowflake case

That is not possible right now.

**Comment by btclinux** [comment]
I successfully connected to tor via tor daemon with snowflake or VPN & pure tor

**Comment by karliatto** [comment]
> I successfully connected to tor via tor daemon with snowflake or VPN & pure tor

Great! So I guess we can close this issue.

**Comment by btclinux** [comment]
> > I successfully connected to tor via tor daemon with snowflake or VPN & pure tor
> 
> Great! So I guess we can close this issue.

I connected on OS side but not in Trezor Suite

**Comment by karliatto** [comment]
> I connected on OS side but not in Trezor Suite

Did it take so long to connect using VPN and pure Tor?

Trezor Suite is using the same so if it works, Tor bundled in Trezor Suite should work as well.

**Comment by btclinux** [comment]
> > I connected on OS side but not in Trezor Suite
> 
> Did it take so long to connect using VPN and pure Tor?
> 
> Trezor Suite is using the same so if it works, Tor bundled in Trezor Suite should work as well.

No, connection takes no more than 30 seconds

**Comment by btclinux** [comment]
Where to find Tor temp files created by Suite?

**Comment by btclinux** [comment]
Maybe just add the option to use system proxy, so user can just route Suite to 9050/9150 port

**Comment by karliatto** [comment]
> Where to find Tor temp files created by Suite?

In Ubuntu you should be able to find it at `/home/<user>/.config/@trezor/suite-desktop/tor`.

> Maybe just add the option to use system proxy, so user can just route Suite to 9050/9150 port

This option is work in progress right now. Soon it will be possible to use external Tor with Trezor Suite.

**Comment by btclinux** [comment]
> In Ubuntu you should be able to find it at `/home/<user>/.config/@trezor/suite-desktop/tor`.

I deleted the whole `@trezor` directory, still no luck

**Comment by karliatto** [comment]
Could you share with us some more logs? I am interested in the section from `INFO(process-tor): Starting process:`

Specially the log:

```bash
 INFO(process-tor): - Params: --AvoidDiskWrites,1,Log,notice stdout,--DormantCanceledByStartup,1,--SocksPort,39215 ExtendedErrors KeepAliveIsolateSOCKSAuth,--SocksTimeout,30,--MaxCircuitDirtiness,1800,--ControlPort,43153,--CookieAuthentication,1,--CookieAuthFile,/home/<user>/.config/@trezor/suite-desktop/tor/control_auth_cookie,__OwningControllerProcess,264924,--DataDirectory,/home/<user>/.config/@trezor/suite-desktop/tor
```

**Comment by btclinux** [comment]
```
2024-10-14T15:08:47.633Z - INFO(tor): Toggling ON
2024-10-14T15:08:47.633Z - INFO(tor): Setting proxy rules to "socks5://127.0.0.1:42245"
2024-10-14T15:08:47.634Z - INFO(process-tor): Starting process:
2024-10-14T15:08:47.634Z - INFO(process-tor): - Path: /tmp/.mount_TrezorbB58It/resources/bin/tor/tor
2024-10-14T15:08:47.634Z - INFO(process-tor): - Params: --AvoidDiskWrites,1,Log,notice stdout,--DormantCanceledByStartup,1,--SocksPort,42245 ExtendedErrors KeepAliveIsolateSOCKSAuth,--SocksTimeout,30,--MaxCircuitDirtiness,1800,--ControlPort,36065,--CookieAuthentication,1,--CookieAuthFile,/home/user/.config/@trezor/suite-desktop/tor/control_auth_cookie,__OwningControllerProcess,2182847,--DataDirectory,/home/user/.config/@trezor/suite-desktop/tor,--UseBridges,1,--ClientTransportPlugin,snowflake exec /usr/bin/snowflake-client -log /home/user/.config/@trezor/suite-desktop/tor/snowflake.log,--Bridge,snowflake 192.0.2.3:80 2B280B23E1107BB62ABFC40DDCC8824814F80A72 fingerprint=2B280B23E1107BB62ABFC40DDCC8824814F80A72 url=https://snowflake-broker.torproject.net.global.prod.fastly.net/ fronts=foursquare.com,github.githubassets.com ice=stun:stun.l.google.com:19302,stun:stun.antisip.com:3478,stun:stun.bluesip.net:3478,stun:stun.dus.net:3478,stun:stun.epygi.com:3478,stun:stun.sonetel.com:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.voys.nl:3478 utls-imitate=hellorandomizedalpn
request-manager: connect ECONNREFUSED 127.0.0.1:36065
2024-10-14T15:08:47.634Z - INFO(process-tor): - CWD: /tmp/.mount_TrezorbB58It/resources/bin/tor
2024-10-14T15:08:48.754Z - INFO(tor): Bootstrap - 1% - Connecting to pluggable transport
2024-10-14T15:08:48.755Z - INFO(tor): Bootstrap - 2% - Connected to pluggable transport
2024-10-14T15:08:48.795Z - INFO(tor): Bootstrap - 10% - Connected to a relay

...

2024-10-14T15:12:06.868Z - INFO(tor): Setting proxy rules to ""
2024-10-14T15:12:06.869Z - INFO(process-tor): Stopping process
2024-10-14T15:12:06.870Z - INFO(process-tor): Exited, code: N/A (Stopped: Yes)
2024-10-14T15:12:07.870Z - INFO(process-tor): (2x) Killed successfully
```

Btw, snowflake not used in options but in log it exist
`--UseBridges,1,--ClientTransportPlugin,snowflake exec /usr/bin/snowflake-client` etc.

**Comment by btclinux** [comment]
Snowflake cannot be turned off

**Comment by btclinux** [comment]
So, I deleted /home/user/.config/@trezor/ and pure Tor successfully started

**Comment by btclinux** [comment]
I get the problem. You cannot turn off Snowflake if you used it once, the only way is to remove /home/user/.config/@trezor/, The second issue is in Snowflake bridge itself. Look here for alternative servers https://forum.torproject.org/t/fix-problems-with-snowflake-since-2024-03-01-broker-failure-unexpected-error-no-answer. Unfortunately, default bridge
`Bridge snowflake 192.0.2.3:80 2B280B23E1107BB62ABFC40DDCC8824814F80A72 fingerprint=2B280B23E1107BB62ABFC40DDCC8824814F80A72 url=https://snowflake-broker.torproject.net.global.prod.fastly.net/ fronts=foursquare.com,github.githubassets.com ice=stun:stun.l.google.com:19302,stun:stun.antisip.com:3478,stun:stun.bluesip.net:3478,stun:stun.dus.net:3478,stun:stun.epygi.com:3478,stun:stun.sonetel.com:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.voys.nl:3478 utls-imitate=hellorandomizedalpn`
useful not for everyone.
Is there any option to use another bridge?

**Comment by karliatto** [comment]
Ok, I see, that was my guess, somehow snowflake config not clearing up properly. I will fix that issue.

Regarding the snowflake bridge server we are using the one recommended from https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/tree/main/client  we currently do not have a way to customize it.

But probably with the new feature that will allow users to use external Tor that can be customized as you want will be enough.

**Comment by bosomt** [comment]
**QA OK**

path to snowflake binary is cleared when disabled and enabled again

**Info:**
 - Suite version: desktop 24.11.0 (96159d214b65b6c0c5315f09f571e52fbab8a1be)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Transport: BridgeTransport 2.0.33
