### ISSUE TITLE
discreet mode placeholder cutout 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14736]
**Describe the bug**
discreet mode placeholder cutout 
Compare first nice fadeout from portfolio and second and third screenshot from account detail that has no fadeout of HiddenPlaceholder

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: desktop 24.10.1 (6fbf039c99a65832b8acf0c0852f7df74ffea128)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.10.1 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.1

**Screenshots:**

_**OK**_
<img width="520" alt="Screenshot 2024-10-05 at 9 46 41" src="https://github.com/user-attachments/assets/af25c103-251d-421d-a4cf-1504cb8a73ba">

_**QA NOK**_
<img width="175" alt="Screenshot 2024-10-05 at 9 45 36" src="https://github.com/user-attachments/assets/7440d268-1d17-47e8-a3f4-5ea21dca57c9">
<img width="176" alt="Screenshot 2024-10-05 at 9 45 31" src="https://github.com/user-attachments/assets/d26a2784-216d-48ec-9452-8ba6e76dbc1a">

**Comment by tomasklim** [comment]
Not exactly a bug, it was like that before. 
@Lemonexe would be better to create an overview issue with issues of this component. You can take inspiration from this https://github.com/trezor/trezor-suite/issues/14698

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 25.1.0 (0b116799334cb4a05fcb59cc480deb7c4b9a63e9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e196413bb745443610211c325623ba7cee7309e9)
 - Transport: BridgeTransport 2.0.33
