### ISSUE TITLE
Labeling - label blurred when entering with privacy mode enabled

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14737]
**Describe the bug**
Labeling - label blurred when entering with privacy mode enabled

**Steps to reproduce:**
1. Enable discreet mode
2. Enable labeling
3. Add label
4. Label is blurred during inputing label

**Info:**
 - Suite version: desktop 24.10.1 (6fbf039c99a65832b8acf0c0852f7df74ffea128)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.10.1 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.1

**Screenshots:**
![image](https://github.com/user-attachments/assets/315f1225-e05f-4caa-b3d6-029ddd3ecea0)

**Comment by MiroslavProchazka** [comment]
So the labels should not be blurred while editing the labels. Otherwise let it be blurred

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 25.1.0 (0b116799334cb4a05fcb59cc480deb7c4b9a63e9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e196413bb745443610211c325623ba7cee7309e9)
 - Transport: BridgeTransport 2.0.33
