### ISSUE TITLE
Coinmarket - delete swap in BTC only firmware

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14746]
## Info
Displaying the _Swap_ button in the header for BTC-only firmware.

## Screenshot
![obrazek](https://github.com/user-attachments/assets/0be3474e-c1ff-4d96-a6bd-bb67646d9a5a)

## Related
https://github.com/trezor/trezor-suite/issues/14693

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.11.0 (decfe32132516cbbd8ac78fc0c7ec235a5e1cf66)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.0 bitcoin-only (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: WebUsbTransport
