### ISSUE TITLE
Missing "all coins deactivated" states

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#1475]
Dashboard

![image](https://user-images.githubusercontent.com/3112191/78711951-1ebb7880-7918-11ea-98fb-2330a8d24fb5.png)

The menu should not be visible I guess?

![image](https://user-images.githubusercontent.com/3112191/78712036-41e62800-7918-11ea-871e-8935f739b112.png)

**Comment by glacierbits** [comment]
Duplicity (#1103 and #1488 ). Working on it.
