### ISSUE TITLE
Send coins - adjust feature flag

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#14759]
- [ ] adjust feature flag so the send flow is always available in production build for ordinary users.
- [ ] Bitcoin based coins are possible to send after enabling feature flag
- [ ] It is still impossible to send any other coins.
- [ ] make sure that iOS user can not enter send flow

**Comment by STew790** [comment]
**QA OK**
- "Send" is visible even without feature flag on production
- cant send any other coins
- iOS doesn't have "Send" feature

**Info**
24.10.1 https://github.com/trezor/trezor-suite/commit/d87ce7455c97466e91037508e50516aa2ae8ba4b
