### ISSUE TITLE
Spending right after the bump of RBF results in "Transaction signing error"

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#14753]
Steps:

1. Create transaction with 1sat/byte (to never be confirmed)
2. Bump it to 2sats/byte
3. Try to spend the UTXO of the 2. tx (use coin control
4. -> error
```
Transaction signing error: Transaction 'd06dfa184166eed133240ed4f712f43db13f500fc19b7d1597e10e09dd849f1b' not found
```

![image](https://github.com/user-attachments/assets/c89e75d6-4707-406f-879f-6d0604f1e9cb)

The clearing of the send-form solves the issue. 
![image](https://github.com/user-attachments/assets/4183b225-f0fd-46ee-af78-43ef74e121e4)

**Comment by peter-sanderson** [comment]
The  `d06dfa184166eed133240ed4f712f43db13f500fc19b7d1597e10e09dd849f1b` tx id from the error is the original transaction (1sat/byte)

**Comment by gorrdy** [comment]
I have the same experience and can confirm this happens on 24.10.1
https://github.com/trezor/trezor-suite/releases/tag/v24.10.1

**Comment by gorrdy** [comment]
Actually even after 1 confirmation it's not possible to send the transaction from the same account.

**Comment by komret** [comment]
Related to https://github.com/trezor/trezor-suite/issues/13325. Not related to transaction confirmations but flawed form drafts. Temporary solution: use "Clear all" button in send form. I am working on a fix.
![Screenshot 2024-11-12 at 16 19 50](https://github.com/user-attachments/assets/ee5035c6-a673-4ef8-8588-46b543aa66b5)

**Comment by bosomt** [comment]
**QA OK**

https://github.com/trezor/trezor-suite/pull/15402#issuecomment-2483078219
