### ISSUE TITLE
Coinmarket - minor bugs

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14767]
## Description
- missing Invity Footer in confirm pages(1)
- in the Last transaction pages
  - replace `exchanges` → `swaps` (2)
  - send in swaps transactions using contract address instead of symbol (3)
- infinity loading when the response contains empty quotes (edge case - do not know how to replicate without localhost API)
- bad `watchTrade` account - change account to selectedAccount (some trades were saved in bad account) (4)

## Screenshots
**Missing footer (1)**
![obrazek](https://github.com/user-attachments/assets/d1141926-03e4-45db-8b9b-4151d8a7693f)
**Rename `exchanges` (2)** 
![obrazek](https://github.com/user-attachments/assets/8f26e342-c2af-43ff-b143-8b5ac1575634)
**Bad symbol (3)**
![obrazek](https://github.com/user-attachments/assets/5c319867-5589-4e9c-ae7d-1a19074408b3)

## Other
**Steps to reproduce (4)**
1. Select ETH account 
2. Go to Swap
3. Choose `From` SOL and `To` USDT
4. Make the trade
5. After transaction confirmation you will be on SOL account instead of ETH account

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.11.0 (9e739c0dd91402b9b2311ff86de4ec03c0d215bb)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: WebUsbTransport
