### ISSUE TITLE
nodebridge - enumerate while other call waiting for button request

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#14771]
client 1:

1. get address
2. show on device, do not confirm and wait

client 2:
1. open app 
2. enumerate does not respond - gets aborted, transport-error is emitted resulting in some troubleshooting screen

**Comment by evgenysl** [comment]
@mroz22 results for both Bridge 2.0.33 and NodeBridge 3.0.0

![fix branch](https://github.com/user-attachments/assets/be5ed22e-93b8-4cd0-8faf-818d24798a8c)

When I click "Use Trezor here", I'm correctly switched to web Suite:

![fix branch 2](https://github.com/user-attachments/assets/b9c911df-bd9e-4ef6-8f46-bc93c68a5c95)

**Comment by evgenysl** [comment]
Results:

Two apps are open.

Client 1:

1. get address
2. show on device, do not confirm and wait

Client 2:

1. Close app

Client 1:
1. Address verification error
2. Trezor is disconnected

**Comment by evgenysl** [comment]
T1 and TS5 are connected.

client 1:

1. get address
2. show on TS5, do not confirm and wait

client 2:

1. open app
2. Only T1 is visible, TS5 is not discovered

![m2](https://github.com/user-attachments/assets/3f4059e6-dc51-4a4a-a034-c94c41a49cf5)

**Comment by evgenysl** [comment]
NodeBridge
Desktop client 1:

1. get address
2. show on device, do not confirm and wait

Web client 2:

1. open app
2. click Use Trezor here
3. Wallet is correctly switched
4. Bitcoin -> Receive -> Show full address :white_check_mark:

![m4](https://github.com/user-attachments/assets/0e2aca03-c0b8-439f-a212-c2f6fbbd8b2e)

![m5](https://github.com/user-attachments/assets/9ffc59cf-2509-4f14-bb7b-b1613eb32ca3)

**Comment by evgenysl** [comment]
T1 and TT are connected.

![m20](https://github.com/user-attachments/assets/023d2ea4-5b1f-480c-95cb-2d3a046dd920)

1. Disconnect TT cable
2. Correct TT disappeared from wallet switcher ✅
3. Connected TT back without closing wallet switcher
4. TT appeared in wallet switcher  

Tried this many times, disconnecting different wallets (active and inactive in wallet switcher).

**Comment by evgenysl** [comment]
T1 and TT are connected.

1. T1 wallet is active
2. Go to bitcoin account
3. Disconnect T1 cable
4. Suite switches to TT correctly
