### ISSUE TITLE
Text missing in transaction detail help

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1477]
Please add correct text.

![image](https://user-images.githubusercontent.com/31506317/78751068-d16bf500-7971-11ea-9113-695edaee4dc9.png)

**Comment by bosomt** [comment]
@matejzak it still says **TODO TODO TODO ExPlAnAtIoN** in /suite-web/

**Comment by sorooris** [comment]
@bosomt :) @matejzak 
![image](https://user-images.githubusercontent.com/10185314/80467006-912edf80-893d-11ea-9445-75a8e5d73557.png)

**Comment by glacierbits** [comment]
@bosomt It's just waiting to be synced: That's why it's not in the [Test] column.

**Comment by bosomt** [comment]
@matejzak i saw you to move it to Approved so i got concerned :)

**Comment by sorooris** [comment]
**QA OK**
Suite: staging 8c4905608587809ea355b1befffe3cf45095ae38
![image](https://user-images.githubusercontent.com/10185314/85399131-9a5fb580-b556-11ea-8871-12beccfd4ba5.png)
