### ISSUE TITLE
Remove ability to type passphrase into keyboard

### ISSUE THREAD

**Issue by HalFinneyIsMyHomeBoy** [trezor/trezor-suite#14789]
The ability to enter passphrase into keyboard really should be removed. 
Or at least display a big red warning why it's not recommended to use anything other than the device.

I know too many people who use it and don't understand the risks.

**Comment by Hannsek** [comment]
Hello, Thanks for the issue. We won't remove the option to enter the passphrase on the connected host. 
The passphrase is now more hidden then before plus we are currently improving the experience around passphrase even more.

Hello, Thanks for the issue.

We don’t plan to remove the option to enter the passphrase on the connected host. However, we have made the passphrase  more hidden, and we’re actively working on further improvements to enhance the overall passphrase experience together with better explaining what it is and what are the risks about that.

I am closing this issue now, but feel free to put down additional thoughts or concerns.
