### ISSUE TITLE
Connect: expose info about methods

### ISSUE THREAD

**Issue by martykan** [trezor/trezor-suite#14782]
Add a function that returns an array with details about each method, for example something like `TrezorConnect.allMethods()`.

This could include the name, permissions, useDevice, useUi, FW range, TypeBox schemas

**Comment by Hannsek** [comment]
Why is this needed? What is the expected usage of this?

**Comment by martykan** [comment]
To replace hardcoded lists of methods, like this: https://github.com/trezor/trezor-suite/blob/722a2b2b7f1f73143d089593df66548a1a9ab910/suite-common/connect-init/src/connectInitThunks.ts#L64-L96

**Comment by martykan** [comment]
Resolved by #14910
