### ISSUE TITLE
Move staking logic to @trezor/connect

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14786]

**Comment by bosomt** [comment]
**QA OK**

- claim, stake, unstake tested

**Info:**
 - Suite version: web 24.11.0 (f53d31e47fc68e1ce17248b6591d865088781ed1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: WebUsbTransport
