### ISSUE TITLE
Skeleton remains in the last coins fiat value on the dashboard after discovery

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#14785]
**Describe the bug**
When a discovery is finished (being finished) there's a chance that there is a skeleton that remains in the fiat value and it's always with the last coin (enabled) on the dashboard. This can be "fixed" by going into, for example, settings and back, the value suddenly appears.

**Info:**

-   Mobile Suite Version: [version/commit](https://github.com/trezor/trezor-suite/pull/14281)
-   OS: Android

**How to reproduce**

1. Connect a device with some enabled coins
2. Wait for the discovery of the coins and specifically for the last enabled one
3. There remains a skeleton where the fiat value should be even after quite some time
4. This can be "fixed" by going for example into the settings and back

**Screenshots**
<img width=300 src="https://github.com/user-attachments/assets/a7b7ddbd-0596-4a28-8a60-eb896608df60" /><img width=240 src="https://github.com/user-attachments/assets/2e70b993-2ae4-4f8d-a3ff-1edd2c12279f" />

**Comment by evgenysl** [comment]
**QA OK**
Tested with T1 and TS5 on multiple funded wallets.

**Version**
24.11.1 https://github.com/trezor/trezor-suite/commit/35433e7d5213f924061bc36bb74edf017bd39db0
