### ISSUE TITLE
Send form "Total" value overflows to second row moving the "Incl. fee" row for fiat

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#14798]
**Describe the bug**
In Send form, the "Total" that is showing value in crypto can overflow to the second row which is for "Incl. fee" for fiat and that also moves the "Review & Send" button.

**Steps to reproduce:**
1. Go to Ethereum send form
2. Enter for example 1$ as an amount
3. See the result on the right with "Review & Send" button

**Info:**
 - Suite version: desktop 24.10.1 (3cbe786b5c8effd03b331faec20a41ef01d6671b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.10.1 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.1

**Expected result:**
Total for crypto and fiat stays on one line.

**Actual result:**
Total value for crypto overflows to second row for "Incl. fee" value

**Screenshots:**
[2024-10-10 13-16-16.webm](https://github.com/user-attachments/assets/605bd8a4-b462-432f-aba0-9f35fe91c104)

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/aa62a50f-1418-4b9b-974e-dd647b9d564c)
![Image](https://github.com/user-attachments/assets/28166fff-2ed2-433a-ace3-707cbb7d2713)


**Info:**
 - Suite version: desktop 24.11.0 (a337b23e886188d52160cc2c00dfa4a8000801d0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Transport: BridgeTransport 3.0.0-bundled.24.11.0
