### ISSUE TITLE
Token name wraping in trade section

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#14795]
![image](https://github.com/user-attachments/assets/27130c4e-a24d-4f51-8016-af499544e912)

**Comment by bosomt** [comment]
**QA OK**


![Image](https://github.com/user-attachments/assets/4c404222-c257-4397-adf8-72d1862b4af3)

![Image](https://github.com/user-attachments/assets/f6827233-3205-47ca-861c-aa91e36f83b0)

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
