### ISSUE TITLE
Missing prefixes of new coins in protocol.ts

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14813]
**Describe the bug**
Missing prefixes of new coins in `protocol.ts`
If you try to scan QR code that include coin name in receive prefix it will fail.
`QR code contains invalid address for this account`

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: desktop 24.10.1 (3cbe786b5c8effd03b331faec20a41ef01d6671b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.10.1 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.1

**Screenshots:**
![image](https://github.com/user-attachments/assets/86284c87-0695-40de-9c79-a3b818ee3851)

**Comment by tomasklim** [comment]
Please change the logic so that type-check yells when new network is added and it is not added here. We are missing Solana, Polygon, BNB, Optimism,... and it does not warn us.

I think the logic has to be changed completely. And btw sometimes there can be two different protocols for 1 coin. 
e.g. (maybe, validate)
- Polygon: 'matic' or 'polygon'
- BNB: 'bnb' or 'binance' or 'bsc'

**Comment by bosomt** [comment]
**QA OK**

1. 
- import of QR code `binance:0x607ce71Ae895D7759141c6ae2695a2eb64e92Bb7` worked as expected in BNB send section
-  `QR code is defined for Binance account` error when tried to scan it in ETH send section
- `Unknown protocol scheme: "koko". Please try again or enter the address manually.` when not valid protocol :)
2. uri link `bitcoin:bc1qf8cedqguh2ucc3fgsphmgt789q9szh35vtl38m` worked as expected

**Info:**
 - Suite version: desktop 24.11.0 (17bac171ecd870c4d76bb64c6ec5f8d69b333d4c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
