### ISSUE TITLE
Trading - UI fee number is little bit cut

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14821]
**Describe the bug**

Suite version: 24.10.1

See the `$0.00`
![Screenshot 2024-10-11 at 10 37 45](https://github.com/user-attachments/assets/45dd3580-f6a8-4180-86c3-34711a7c12b7)

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/80ff3ec9-8e01-4cec-b977-4c6c63b675fb)

**Info:**
 - Suite version: desktop 24.12.0 (19aeb1a0f7d306fcbe7cc61ed330a2481a3d0e4e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 3.0.0-bundled.24.12.0
