### ISSUE TITLE
Polygon - make POL and BSC available for portfolio when enabled

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#14826]
When POL or BSC are enabled, make them available for portfolio tracker as well to import

**Comment by STew790** [comment]
**QA OK**
I was able to add POL and BSC to my porftolio both on Android and on iOS.

**Info**

24.11.1 https://github.com/trezor/trezor-suite/commit/ff16b788c576e89bbbfc17cbe783154223440336
