### ISSUE TITLE
Trading - button All sometimes fill more than available balance

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14823]
**Describe the bug**

Suite version: 24.10.1

For some reason sometimes when I click `All` it fills more than available balance

https://github.com/user-attachments/assets/290a84d4-fc70-4aba-85ed-f0c758f88e19

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.1 (9e9dadff47c5243bf4a10f539a898fe48da46506)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.5 regular (revision d72aab0bf75a9cfe6679da87efc4ac33382468dc)
 - Transport: BridgeTransport 2.0.33
