### ISSUE TITLE
Trading - swap ALL - not enough funds for fee

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14837]
**Describe the bug**

Suite Version: 24.10.1

We lie about DEX fees so it fails before I make the trade :( Related to #14838

https://github.com/user-attachments/assets/ba7f1568-983c-46ca-9205-503af59d3a5e

**Comment by bosomt** [comment]
**QA OK**

ETH > Tether erc20 🆗 

<img width="686" alt="image" src="https://github.com/user-attachments/assets/5324d8ee-5079-4eb8-9d7f-f1660a078a11">

**Info:**
 - Suite version: desktop 24.11.1 (9e9dadff47c5243bf4a10f539a898fe48da46506)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.5 regular (revision d72aab0bf75a9cfe6679da87efc4ac33382468dc)
 - Transport: BridgeTransport 2.0.33
