### ISSUE TITLE
Trading - all button sometimes does not fill amount at all

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14835]
**Describe the bug**

Suite version: 24.10.1

Sometimes the `All` button does not fill anything

https://github.com/user-attachments/assets/d30aa515-233d-493c-ab35-a4e813c1f77f

**Comment by bosomt** [comment]
I was not able to replicate issue in dev build app with ETH and BTC
Maybe slow ETH network caused it ?


**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33

**Comment by tomasklim** [comment]
It sometimes works, sometimes not. No idea why. There were also some pending txs on the account

**Comment by evgenysl** [comment]
Can reproduce:

https://github.com/user-attachments/assets/d37c4774-37ee-4c06-b3c2-b35eefdcf427

**Comment by bosomt** [comment]
**QA OK**

- sell all BTC ✅ 
- sell all ETH ✅ 
- swap all ERC20 ✅ 

**Info:**
 - Suite version: desktop 24.11.1 (9e9dadff47c5243bf4a10f539a898fe48da46506)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.5 regular (revision d72aab0bf75a9cfe6679da87efc4ac33382468dc)
 - Transport: BridgeTransport 2.0.33
