### ISSUE TITLE
Trading - receive account select cannot be closed once open

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14845]
**Describe the bug**

Version: 24.10.1

Once I open receive account select I cannot close it by clicking outside

https://github.com/user-attachments/assets/3b50a1f7-1305-46e4-b27e-106622fcb9d0

**Comment by bosomt** [comment]
**QA OK**

https://github.com/user-attachments/assets/569fdf4f-7596-4014-8485-4455aa7c354b


**Info:**
 - Suite version: desktop 25.1.0 (20a35a51ea92edb7ffa42c696f6da297c66d2971)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision a8e5d471fe35164cbf2529a2c0042ca465f6f159)
 - Transport: BridgeTransport 2.0.33
