### ISSUE TITLE
Trading - trading fee is sometimes in billions of $$$

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14844]
**Describe the bug**

Suite Version: 24.10.1

![Screenshot 2024-10-14 at 19 18 47](https://github.com/user-attachments/assets/265f8e35-515b-4b29-a31b-a33c8eaa02a8)
![Screenshot 2024-10-11 at 10 19 26](https://github.com/user-attachments/assets/cf6146a3-ba11-4626-a585-850226e34bb2)

**Comment by bosomt** [comment]
I was  not able to replicate it on 24.10.1 app, but i will watch for this error on 24.11.0 builds

<img width="1104" alt="image" src="https://github.com/user-attachments/assets/810a7113-9e31-4eed-8974-59ebbdba35d9">

**Comment by tomasklim** [comment]
It happens just sometimes, no idea why. It never happens in send form, so there is some wrong calculation or default state

**Comment by LukasRada** [comment]
Repro steps here...

https://github.com/user-attachments/assets/11e154c3-a481-4f0a-829d-64cd80ee941e

Thank you for the report.

**Comment by bosomt** [comment]
**QA OK**

im not able to replicate it /used @LukasRada video as reference to replicate it/

**Info:**
 - Suite version: desktop 24.11.0 (17bac171ecd870c4d76bb64c6ec5f8d69b333d4c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
