### ISSUE TITLE
Trading - time elapsing slower on the offers page

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14843]
**Describe the bug**

Suite Version: 24.10.1

Time is more than twice slower on the offers page

https://github.com/user-attachments/assets/72bee907-64db-41ad-a7e6-771cd34aeb30

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.11.0 (c9e9759e2e6285c103717796c32cd910b838716c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Transport: BridgeTransport 2.0.33
