### ISSUE TITLE
Trading - long amount or symbols does not fit to UI nicely

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14852]
**Describe the bug**

Version: 24.10.1

![Screenshot 2024-10-14 at 19 46 16](https://github.com/user-attachments/assets/b8732246-cca4-4b70-9afa-25997b24e51d)
![Screenshot 2024-10-14 at 19 46 43](https://github.com/user-attachments/assets/f5d9756d-cf0f-435c-98eb-961d697367d3)
![Screenshot 2024-10-14 at 19 44 10](https://github.com/user-attachments/assets/3c555ffc-1b78-4076-91d5-1ec48d78e65d)
![Screenshot 2024-10-14 at 19 44 59](https://github.com/user-attachments/assets/937c1475-79c5-4207-b7e1-f854718f6568)

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/3f9856df-f357-4dc8-a4de-a647c30aca16)
![Image](https://github.com/user-attachments/assets/b94788d8-c017-46c4-98d3-4cd810871b6f)

**Info:**
 - Suite version: web 24.11.0 (ccc4abd7435e4efabeac8fa846d6e4f7a4e23432)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 5120x1440
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport
