### ISSUE TITLE
Polygon - make sure POL and BNB works with graph

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#14851]
POL and BNB networks should be counted in portfolio graph (same rules as eth)

**Comment by STew790** [comment]
**QA OK**
POL and BNB are correctly shown in graph (both alone and together with other coins).
**Info**
24.10.2 https://github.com/trezor/trezor-suite/commit/e4365278aa8be68324c41f57fa796f9b4ee631f9
