### ISSUE TITLE
Trading - Consider removing `on the right` text in hint.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14859]
**Describe the bug**
Consider removing `on the right` text in hint.
As there are more and more ETH like networks added they are listed below `All networks` button too

**Steps to reproduce:**
1. Navigate to swap
2. Open destination section
3. Check all networks button hint

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="690" alt="Screenshot 2024-10-15 at 10 54 46" src="https://github.com/user-attachments/assets/65b8ebca-ef35-4493-96a3-90f107e40e03">
<img width="731" alt="Screenshot 2024-10-15 at 10 53 43" src="https://github.com/user-attachments/assets/c428cefa-0a09-483b-b3ee-3d3273af2ef8">

**Comment by cavigneron** [comment]
Updated in CrowdIn to "View tokens from all {networkCount} networks. Filter by the most popular networks."

**Comment by bosomt** [comment]
**QA OK**

`View tokens from all 47 networks. Filter by the most popular networks.`

**Info:**
 - Suite version: desktop 24.11.1 (9e9dadff47c5243bf4a10f539a898fe48da46506)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.5 regular (revision d72aab0bf75a9cfe6679da87efc4ac33382468dc)
 - Transport: BridgeTransport 2.0.33
