### ISSUE TITLE
Trading - Add Buy&Sell button and Swap button to Dashboard header  

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14863]
## Description 
- Add **Buy&Sell** button and **Swap** button to Dashboard header + add click event.
  - Analytics event c_type=dashboard/actions after Buy&Sell or Swap button is clicked ([mandatory attributes doc](https://www.notion.so/satoshilabs/c63bdab01b704b099cab3bbb3227e1b1?v=406d107d6d584577a47d7580e8b2df89)).
  - Type attribute 
     - Buy&sell: `type=wallet-coinmarket-buy`
     - Swap: `type=wallet-coinmarket-exchange`
- Both sections will not require account context
- Always show the DCA tab in the Buy&Sell screen

## Screenshots
![image](https://github.com/user-attachments/assets/0aee7738-8d1c-49f4-b286-11126aceaadc)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.11.0 (17bac171ecd870c4d76bb64c6ec5f8d69b333d4c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport
