### ISSUE TITLE
Remove FW upgrade banner - it is duplicate

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#14869]
![image](https://github.com/user-attachments/assets/b624e8b6-09f5-44fe-8cee-89c351183959)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.0 (e1fe4b85d4885e52a080798539b215c6366afeaa)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.10.3 regular (revision 9276b1702361f70e094286e2f89e919d8a230d5c)
 - Transport: BridgeTransport 2.0.33
