### ISSUE TITLE
Trading - accounts are not organised by account type when swapping

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14881]
**Describe the bug**
Accounts are not organised by account type when swapping.
See screenshot, they should by sorted into categories.

**Steps to reproduce:**
1. Swap into coin that used multiple account types in wallet
2. Observe account types in account list when swapping

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="420" alt="image" src="https://github.com/user-attachments/assets/1656c22b-3a18-457e-945b-c88748a4e4db">

**Comment by tomasklim** [comment]
Duplicate https://github.com/trezor/trezor-suite/issues/14879
