### ISSUE TITLE
Trade - update trade section structure

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#14889]
## Description
- Split Buy&Sell section and Swap section
- Header will not show account (instead there is a go back button)

### Before
![image](https://github.com/user-attachments/assets/f408894a-fe29-45b6-84b3-3efe41d3cef9)
![image](https://github.com/user-attachments/assets/c45de900-40bf-4c67-a53f-7752cb324d11)

### After
![image](https://github.com/user-attachments/assets/bc7a6b20-3fe5-4120-80cf-d35d38f55d7e)
![image](https://github.com/user-attachments/assets/248ae3da-416a-4f6d-887a-03f612f84ee6)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 24.11.0 (504e7b0c757d7aa98434c2b6b9b27ed0e2fad8f9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Transport: BridgeTransport 3.0.0-bundled.24.11.0
