### ISSUE TITLE
Polygon - feature flag cleanup

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#14887]
Clean feature flags for POL and BNB when not needed.

**Comment by matejkriz** [comment]
Waiting just for product decision that we can go out with what we have.

**Comment by matejkriz** [comment]
@sime We need to decide if we want to release only POL in November or BNB too.

**Comment by vytick** [comment]
As we discussed today, we will release in next version.

**Comment by STew790** [comment]
**QA OK**
POL and BNB present without feature flags.

**Info**
24.11.1 ff16b78
