### ISSUE TITLE
Solana - create feature flag

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#14895]
BY enabling feature flag, user should be able to:

- enable Solana and discover accounts
- import Solana to Portfolio Tracker
- See SPL tokens and txns for the account

**Comment by STew790** [comment]
**QA OK**
Solana is correctly hidden behind feature flag.

**Info**
24.10.2 https://github.com/trezor/trezor-suite/commit/17d794f5dee37026247df980bdccae1f7e489cae
