### ISSUE TITLE
Terms and conditions

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1490]
- [x] Update content of Terms and Conditions 

- [x] Upload to wallet.trezor.io/tos.pdf (not really there, this link still contains old /tos. I don't have access there. But quick search over satoshilabs and trezor organization suggests that it is not used anywhere anymore. New link is https://data.trezor.io/legal/wallet-terms.pdf

- [x] Update content of T&Cs for Suite (todo @matejzak)

- [ ] ~~Upload (find place) to Suite stage~~ (invalid - we have single place^^)

[02_Wallet Terms and Conditions_revision(2) (1).pdf](https://github.com/trezor/trezor-suite/files/4509126/02_Wallet.Terms.and.Conditions_revision.2.1.pdf)

**Comment by matejzak** [comment]
[02_Wallet Terms and Conditions_revision(2) (1).pdf](https://github.com/trezor/trezor-suite/files/4509045/02_Wallet.Terms.and.Conditions_revision.2.1.pdf)

**Comment by mroz22** [comment]
pretty much all I could do is done now
- https://github.com/trezor/trezor-suite/pull/1691
- https://github.com/satoshilabs/mytrezor/pull/926
- https://github.com/trezor/webwallet-data/pull/14

so moving this back on matej

**Comment by glacierbits** [comment]
Perfect, we are all set for Suite launch then. 

As for wallet.trezor.io, @mroz22 please update the link _Terms_ at the footer with the new link.

**Comment by mroz22** [comment]
> As for wallet.trezor.io, @mroz22 please update the link Terms at the footer with the new link.

only sick or slush may do it. Pull request is already merged into mytrezor. That's why I say I cannot do anything else regarding this issue
