### ISSUE TITLE
Trading - Apple Pay logo in Dark mode

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#14924]
![image](https://github.com/user-attachments/assets/c286b10d-061a-49a3-bbcb-c96bdec9a8a8)

**Comment by tomasklim** [comment]
It looks better now. Closing 
<img width="456" alt="Image" src="https://github.com/user-attachments/assets/db9e0214-fcc0-402c-a666-81bb8f6b0336" />

**Comment by bosomt** [comment]
**QA OK**

<img width="385" alt="Image" src="https://github.com/user-attachments/assets/4f412b91-6211-46b4-a375-93807f3e6148" />

**Info:**
 - Suite version: web 25.1.0 (adb2ff4bb90b9221a26ce7cc8c4f9e6317e675db)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e196413bb745443610211c325623ba7cee7309e9)
 - Transport: BridgeTransport 3.0.0-bundled.24.12.3
