### ISSUE TITLE
Trading - successful swap is never resolved in the UI

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14939]
**Describe the bug**
- I've done 1inch swap. Because I know my address I was able to check it on polygon scan and it is confirmed.
![Screenshot 2024-10-18 at 11 02 46](https://github.com/user-attachments/assets/b57d9c2e-559b-429c-b21f-72ba481f9510)

- Suite is still Loading
<img width="1378" alt="Screenshot 2024-10-18 at 11 03 03" src="https://github.com/user-attachments/assets/89745ce7-303b-486d-8848-d0d48956e302">

- I dont know tx id and the `Go to provider support` goes to 1inch
- when I go to all transactions. I see that my tx was confirmed 
<img width="1241" alt="Screenshot 2024-10-18 at 11 10 32" src="https://github.com/user-attachments/assets/560b30ab-a5a7-43b4-9bbc-4a76f5e7ea77">

- Last transactions still shows pending 

<img width="1331" alt="Screenshot 2024-10-18 at 11 10 41" src="https://github.com/user-attachments/assets/a81914bd-9cce-4f25-9758-d722e9052c4b">
<img width="1269" alt="Screenshot 2024-10-18 at 11 10 37" src="https://github.com/user-attachments/assets/58b1a83f-c9d0-4925-b8f7-38f46944e42f">

**Comment by tomasklim** [comment]
it is not only about 1inch, also other chains and exchanges do that

**Comment by bosomt** [comment]
**QA NOK**

see https://github.com/trezor/trezor-suite/issues/15705

**Comment by bosomt** [comment]
**QA NOK**

swapped but even transactions are confirmed Suite says its converting

![Image](https://github.com/user-attachments/assets/3846c448-aa3e-46a8-869e-e60e53d92962)


![Image](https://github.com/user-attachments/assets/0899b809-d3ea-4e60-bdbc-c99df21a169d)

![Image](https://github.com/user-attachments/assets/015ea577-c0d7-4763-a323-880b5f072fe0)

**Comment by bosomt** [comment]
**QA OK**

guess it takes some time 

<img width="1164" alt="image" src="https://github.com/user-attachments/assets/140b62c9-97de-4161-9f9c-0ea75f02f9e9">

**Comment by adderpositive** [comment]
> **QA OK**
> 
> guess it takes some time
> <img alt="image" width="1164" src="https://private-user-images.githubusercontent.com/31506317/392294630-140b62c9-97de-4161-9f9c-0ea75f02f9e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDIyMDgsIm5iZiI6MTczMzMwMTkwOCwicGF0aCI6Ii8zMTUwNjMxNy8zOTIyOTQ2MzAtMTQwYjYyYzktOTdkZS00MTYxLTlmOWMtMGVhNzVmMDJmOWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA4NDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YWM4ZWUwOWM3YzQ5NGE0OGE2NGQ3MTU4MWJjNmZmMTk0NGJjNDM1ZTE4ZTY3NjgwNjQ4MGM5MTU1ZWM0MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fwSLKD1aX1-d5cRabeIeUHZhi_Hy1ylmmVadi_UnEKc">

The completion of the transaction is faster than the provider's response.
