### ISSUE TITLE
 Send Ethereum - address checksum

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#14933]
## Acceptance criteria 
- When the user inserts the address in the non-checksum format:
    1. When a user inserts an already used address that is not checksummed at all, conversion to checksum is done automatically, and the user is informed about that action.
    2. When the user inserts an address that has not been used yet and is not checksummed, he is informed that the address is not in valid format (is not checksummed) and that he should convert it to checksum. The user can’t send the transaction without a checksummed address.
    3. When the user inserts an invalid address where the checksum is not possible (no matter whether it is used or not). The user is informed that the address is invalid

### Design
- [Figma](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=2208-7212&t=4jNMD8UvChwkIvDF-4)

### Dev note
You can get inspired by the [desktop implementation](https://github.com/trezor/trezor-suite/blob/07fff7930b73d02eb3e0bf68cda3439973e468c6/packages/suite/src/views/wallet/send/Outputs/Address.tsx).

**Comment by evgenysl** [comment]
Sending to used address with all lower case letters:

![Screenshot_20241112_092224_Trezor Suite Lite Develop](https://github.com/user-attachments/assets/5f5cbf89-e2cc-4547-9609-aa010c6ebca8)

It's not automatically converted to checksum.
I tried with addresses used in the past both for sending and receiving ETH.

**Comment by evgenysl** [comment]
When pasting used address with some lower and upper case letters, address is marked as incorrect.
Same behaviour as in Trezor Suite desktop.

![Screenshot_20241112_091407_Trezor Suite Lite Develop (1)](https://github.com/user-attachments/assets/10ccf932-f667-44d9-ada4-16bd8edbc125)

**Comment by PeKne** [comment]
@evgenysl could you please test it again on the latest build? Should be fixed by: https://github.com/trezor/trezor-suite/pull/15349

**Comment by STew790** [comment]
**QA OK**
LGTM now, the checksum seems to be working for lower case.

**Info**
24.11.1 a33bf1d
