### ISSUE TITLE
Trading - token approval confirmation is never loaded so I am unable to go to the next step

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#14938]
**Describe the bug**
3 minutes ago done
![Screenshot 2024-10-18 at 10 51 29](https://github.com/user-attachments/assets/f604f9f3-7241-44e7-a516-8fb4694b5259)

suite is still waiting 
<img width="793" alt="Screenshot 2024-10-18 at 10 51 45" src="https://github.com/user-attachments/assets/ac53c905-71c3-4d0c-a1a6-90d30af7705e">

I have to now exit the trading and try it again with same amount

**Comment by bosomt** [comment]
**QA OK**

swapped tokens and it went fine
![Image](https://github.com/user-attachments/assets/9b11a3ff-bf6c-44d3-98d7-418450386562)


**Info:**
 - Suite version: web 25.1.0 (d92f6c4120253f1dd7c9880611f4c4442481d825)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 2625facf1fe9b71db120439853ceca0a61bb8396)
 - Transport: WebUsbTransport

**Comment by bosomt** [comment]
40 minutes has passed, funds were swapped long time ago
trade is still pending :(

<img width="1195" alt="Screenshot 2024-12-06 at 12 42 44" src="https://github.com/user-attachments/assets/29bd5d09-d783-4041-9383-e6736b883df8">
<img width="1169" alt="Screenshot 2024-12-06 at 12 42 33" src="https://github.com/user-attachments/assets/479a7efa-7eee-4874-b6ec-38b2f8709f70">

**Comment by helpBot-cmyk** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Trezor Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by FreeWall** [comment]
fixed on invity backend ([quoteId](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts#L376) was not returned by the trade endpoint) (fix is already deployed on production)

![image](https://github.com/user-attachments/assets/98f4e274-15ec-446c-8259-3a5ce9839307)

**Comment by tomasklim** [comment]
@bosomt please test

**Comment by MiroslavProchazka** [comment]
Can we close this one? Has it been already resolved?

**Comment by bosomt** [comment]
**QA OK**

i managed to get it swapped and approved 
so i think we can close the issue 


BUT it looks like there is another issues
both times i tried to swap POS to POS tokens i was aked to sing transaction TWICE 
see third screenshot, one i cancelled it so i got two notifications /send and cancelled/ or i signed it twice / i got `Transaction signing error: nonce too low: next nonce 47, tx nonce 46` /
if i manage to replicate it again today i will send another issue

**Info:**
 - Suite version: web 25.1.0 (221fe9e7fcd29fc2ef5fa51ca2c22ba6a9369ef6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.6 regular (revision a0a0c93d0dbd62f799a58f0f75f6f4adbf270ef8)
 - Transport: WebUsbTransport


<img width="1174" alt="Screenshot 2024-12-16 at 10 19 45" src="https://github.com/user-attachments/assets/891c016b-812f-4aa2-a5ac-6092444a9495" />
<img width="1159" alt="Screenshot 2024-12-16 at 10 19 50" src="https://github.com/user-attachments/assets/b347ccc8-2b12-48d4-9d19-bfff595603a3" />

<img width="437" alt="image" src="https://github.com/user-attachments/assets/ca833afe-c56c-4f70-8e9f-316ad7c2a3ac" />
