### ISSUE TITLE
Send Ethereum - specific network message

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#14930]
### Acceptance criteria
The user is informed that they should only send the funds to the respective network. Otherwise, the funds might be lost.

If a user opens the send form of an Ethereum-based coin,[ a message](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=2274-444&t=YV27MbkHrf0vbyhs-4) recommending that he check if he is using the intended networks is displayed. 
- If the user fills in the token address in the send form [an alert message is displayed
](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=2285-9716&t=YV27MbkHrf0vbyhs-4)
These messages should appear for all the Ethereum-based networks (ETH, POL, BNB...).

**Comment by STew790** [comment]
**QA OK**
Works for all networks correctly

![image](https://github.com/user-attachments/assets/b473c141-108d-4268-a8c8-309f34d171ec)


**Info**
24.11.1 https://github.com/trezor/trezor-suite/commit/ff16b788c576e89bbbfc17cbe783154223440336
