### ISSUE TITLE
Timestamp shall be human redable nice date

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#14948]
![image](https://github.com/user-attachments/assets/9016ed2d-ca86-4168-9528-8a014e9f1e44)

**Comment by bosomt** [comment]
**QA OK**

testing `AUTOUPDATE-TEST-suite-desktop-0.24.11-win` and date is gone

**Comment by bosomt** [comment]
![Image](https://github.com/user-attachments/assets/c05f11ad-a7b9-4163-87ec-8d6b63476667)
