### ISSUE TITLE
"Latest" version (24.5.4)

### ISSUE THREAD

**Issue by 2011** [trezor/trezor-suite#14962]
I went to the main repository page:

https://github.com/trezor/trezor-suite

And downloaded the version marked "Latest" (24.5.4).

Running the app produced an immediate suggestion to upgrade.

It remains unclear to me why version 24.5.4 continues to carry the "Latest" designation when subsequent releases lack a "beta" or "release candidate" (or equivalent) label.

**Comment by Hannsek** [comment]
This may be connected to app certificates. @komret can you take a look / elaborate? 🙏🏻

**Comment by komret** [comment]
We changed the source URL for new versions in 24.5.4 when we switched to a new Windows certificate. Older versions of Suite must upgrade to 24.5.4 which acts as intermediary before upgrading to latest. It must be marked as "Latest" here for the older versions to upgrade to it. We will drop the "Latest" tag when most users upgrade from versions below 24.5.4.
