### ISSUE TITLE
Solana - decode txn to get event history

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#14969]
To add Solana to Graph we need to decode all wallet transactions to get amount changes. It is already done for EVMs, but not for Solana.

- Count history movements and show graph with events for Solana, similar to EVMs

**Comment by STew790** [comment]
**QA OK**
I can see SOL in graph :tada: 
![image](https://github.com/user-attachments/assets/4043b05c-7a45-494f-a642-1096eeff9bdd)
![image](https://github.com/user-attachments/assets/dd37742f-3314-4f6a-8eb5-a1d237e636c2)


**Info**
24.11.1 https://github.com/trezor/trezor-suite/commit/a33bf1d19feacec314c3debbbbfbf52f8426e674
