### ISSUE TITLE
connect: implement LoadDevice method

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#14970]
there is `LoadDevice` message which has not been implemented to connect yet. It might be useful for testing. lets implement it 

```
"LoadDevice": {
            "fields": {
                "mnemonics": {
                    "rule": "repeated",
                    "type": "string",
                    "id": 1
                },
                "pin": {
                    "type": "string",
                    "id": 3
                },
                "passphrase_protection": {
                    "type": "bool",
                    "id": 4
                },
                "language": {
                    "type": "string",
                    "id": 5
                },
                "label": {
                    "type": "string",
                    "id": 6
                },
                "skip_checksum": {
                    "type": "bool",
                    "id": 7
                },
                "u2f_counter": {
                    "type": "uint32",
                    "id": 8
                },
                "needs_backup": {
                    "type": "bool",
                    "id": 9
                },
                "no_backup": {
                    "type": "bool",
                    "id": 10
                }
            }
        },
```

**Comment by evgenysl** [comment]
~I was not able to load seed on TT with 2.8.3~
Was using normal Trezor and not debug build.

![Screenshot 2024-10-31 at 13 33 57](https://github.com/user-attachments/assets/34c3254e-c192-4ebd-ad95-6e30fc216af3)

![Screenshot 2024-10-31 at 13 34 47](https://github.com/user-attachments/assets/d325de1d-88e8-499a-906c-f4b55f64315b)

1. Path with **not wiped Trezor** 
Error is expected, but it would be an improvement to change "Unexpected message" to something like "Please wipe your Trezor first before proceeding"
cc. @karliatto 


![Screenshot 2024-10-31 at 13 34 56](https://github.com/user-attachments/assets/ba878808-63f6-4ddb-b605-7c14f5470422)

2. When using with Wiped Trezor without firmware: :white_check_mark:

![Screenshot 2024-10-31 at 13 36 09](https://github.com/user-attachments/assets/437cd8e7-a8bc-443f-9d57-d1ffc68f14dc)

~3. When using with Wiped Trezor with firmware: :x:~

![Screenshot 2024-10-31 at 13 50 23](https://github.com/user-attachments/assets/aba6c0ce-4d1a-4be9-a87f-e506bf0faed8)

**Comment by mroz22** [comment]
> Error is expected, but it would be an improvement to change "Unexpected message" to something like "Please wipe your Trezor first before proceeding"
cc. @karliatto

this should be achievable via "method.allowDeviceMode" that should be set t correct values.

**Comment by evgenysl** [comment]
When tested with emulator, everything is good.

![Screenshot 2024-10-31 at 15 16 06](https://github.com/user-attachments/assets/999228d4-f73c-46c1-b10a-edba41126e9f)

![Screenshot 2024-10-31 at 15 16 16](https://github.com/user-attachments/assets/ccd2c1cf-eee4-4f5d-ae74-56ec11cbaa82)


QA OK

**Comment by evgenysl** [comment]
I suggest adding here more clarity:

![Screenshot 2024-10-31 at 15 22 07](https://github.com/user-attachments/assets/a972417a-1a8f-428b-be1a-733e32017694)

1. Link to firmware documentation as suggested by @mroz22 
this one? 
https://docs.trezor.io/trezor-firmware/tests/device-tests.html#extended-testing-and-debugging

2. Add **(not going to work on Trezor with production firmware)**

**Comment by evgenysl** [comment]
**QA OK**

![Screenshot 2024-11-05 at 10 17 38](https://github.com/user-attachments/assets/49d2f5d2-8e62-4c1a-a86e-a61a1ad5e288)

![Screenshot 2024-11-05 at 10 41 05](https://github.com/user-attachments/assets/4f4561a1-b69b-494c-b0e2-70f374beada4)

"Already initialized" when loading Trezor with seed.
