### ISSUE TITLE
suite: start using device._state for connect calls

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#14972]
now `device.state` is used to identify specific device on TrezorConnect level. 

`device.state` is deprecated and will be replaced with `device._state` which we should start using now. 

![image](https://github.com/user-attachments/assets/8787e705-bd4c-49af-992e-d6a1d3015d2e)

this should also cause passphrase to persist suite reloads if implemented correctly

now: 
1. entre passphrase
2. remember device 
3. reload app
4. get address -> get prompted 
![image](https://github.com/user-attachments/assets/d8cf867a-843a-4c94-9d95-ffee9010ebb0)

later: 
number 4 shouldn't happen

## QA notes
- everything with saved devices can break
- everything that is using device state as a reference to something can break (saved transactions, labels)
- needs migration

**Comment by bosomt** [comment]
**QA OK**

- remembered multiple wallets and reload
- remembered multiple wallets including labeling and reload
- added account
- added more coins
- sent tx of new added coin 2x

- tested in app and in web version of devel builds

**Comment by mroz22** [comment]
ok ok, please don't forget testing migration when releasing next suite version
