### ISSUE TITLE
Rename Coins/Hidden

### ISSUE THREAD

**Issue by enjojoy** [trezor/trezor-suite#14985]
We need to rename Coins/Hidden to something like Visible/Hidden or Legit/Hidden is the tokens section. Soon NFT section will be added so it should be consistent. 

<img width="1048" alt="image" src="https://github.com/user-attachments/assets/eb9e141d-59f9-497a-abc4-5f99e3e2f085">

**Comment by jirih-stsh** [comment]
As discussed, lets please change the button text from "Coins" to "My tokens". 
The "Hidden" button should stay as-is.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.11.0 (c9e9759e2e6285c103717796c32cd910b838716c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Transport: WebUsbTransport
