### ISSUE TITLE
Asked for PIN twice during firmware update when trying to cancel FW update during PIN dialogue /no cancel button on host/

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#15005]
**Describe the bug**
Asked for PIN twice during firmware update when trying to cancel FW update during PIN dialogue /no cancel button on host/

**Steps to reproduce:**
1. Start firmware update with device with PIN enabled
2. Try to cancel it
3. There is no way to cancel in app
4. When you cancel PIN dialogue you are asked for PIN once again 
5. After you cancel PIN dialogue for second time you will get Installation failed: Error: PIN entry cancelled error

**Info:**
 - Suite version: desktop 24.11.0 (a337b23e886188d52160cc2c00dfa4a8000801d0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 3.0.0-bundled.24.11.0

**Screenshots:**
<img width="629" alt="image" src="https://github.com/user-attachments/assets/96e931ef-588c-4838-9c9a-ffc97b70751c">

**Comment by komret** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/15009

**Comment by bosomt** [comment]
**QA OK**

- X is present now
- when you cancel PIN dialogue on device it wont open again

**Info:**
 - Suite version: desktop 24.12.0 (19aeb1a0f7d306fcbe7cc61ed330a2481a3d0e4e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 3.0.0-bundled.24.12.0
