### ISSUE TITLE
Trezor + Rabby:  Invalid parameter "path" (= undefined): Expected required property - = p

### ISSUE THREAD

**Issue by alvatar** [trezor/trezor-suite#15015]
**Describe the bug**
Rabby initiates the Trezor popup and then shows ´ Invalid parameter "path" (= undefined): Expected required property - = p ´ 

**Info:**

-   Remembered Wallet: yes/no I dont know what this means
-   Suite Version: web, v24.10.1
-   Browser: chrome  129.0.6668.103 (Official Build) Mac
-   Browser Installation Method: downloaded installer.
-   OS: OSX 15.0.1 (24A348)
-   Bridge: version
-   Firmware Version: it's triggered with or without the device connected

**How to reproduce**

1. Go to any operation with Rabby wallet
1. Initiate transaction
1. Click sign

**Expected behavior**
Usually now you would see the popup with the 9 digits to click

**Screenshots**
<img width="590" alt="image" src="https://github.com/user-attachments/assets/9c70628f-2837-4956-8f3f-aced8e2f0c63">

**Additional context**
It was working well until very recently

**Comment by Hannsek** [comment]
Do you have the latest version of Rabby?

**Comment by mroz22** [comment]
It sounds like it coudl be related to rabby update. TrezorConnect call from rabby did not pass validation.

**Comment by Hannsek** [comment]
Yes, It happened to me too, but it should work after update.

**Comment by alvatar** [comment]
Yes, I have the latest. I've restarted it, the browser. It keeps happening.
I have the latest: 0.92.94

**Comment by Hannsek** [comment]
ok, thank you. Try re-connecting the trezor to rabby (forget the address and add it again).

**Comment by alvatar** [comment]
Now I can't even add it...

<img width="479" alt="image" src="https://github.com/user-attachments/assets/00279350-3cfd-44b7-978a-99b80fa448ad">

**Comment by Hannsek** [comment]
I've tried it and I successfully added an address from Trezor. Can you please share more info about the browser, extension, firmware - versions, systems, …

**Comment by alvatar** [comment]
Not sure what else do you need? The browser, extension, is all in the issue post.

The firmware is 1.12.1. However this happens without the device connected as well.

**Comment by alvatar** [comment]
Actually the browser updated today:  130.0.6723.59

**Comment by Hannsek** [comment]
> Not sure what else do you need? The browser, extension, is all in the issue post.

Sorry, didn't notice. What is the version of Rabby extension

**Comment by evgenysl** [comment]
Can't reproduce with TS5 and TT

Rabby: v0.92.94
Chrome: 130.0.6723.70

**Comment by alvatar** [comment]
Rabby version: 0.92.94

BTW it's happening only in Chrome. I got it working on Brave now.

**Comment by alvatar** [comment]
I disabled all other extensions btw, no effect

**Comment by Hannsek** [comment]
It appears there is a problem with Chrome as I reproduced it there. Investigating…

**Comment by Hannsek** [comment]
It looks like a Chrome bug when Trezor is not detected if the Trezor was plugged in before opening Chrome. If you open Chrome first and then connect Trezor, it should work. Let us please know if the issue is solved on your side.

**Comment by alvatar** [comment]
I'm afraid this doesn't solve it, no. Also, I tried connecting it after the trezor pop up shows, but same thing.

**Comment by Hannsek** [comment]
Can you pair Trezor with Chrom via webUSB? Or are you using Trezor Bridge (`trezord` process running in the background, you can check it in Activity monitor app)

**Comment by alvatar** [comment]
`trezord` is running indeed. I don't know what you mean / how to do the pairing via webUSB

**Comment by Hannsek** [comment]
That is even stranger. May you please try killing the `trezord` process, restart chrome and try to do it one more time?

you can use our method testing tool on https://connect.trezor.io/9/methods/bitcoin/getAddress/. It is easier to start connect popup from here.

![image](https://github.com/user-attachments/assets/949759c3-d507-4d3d-8bd3-f7581bacf3e3)

**Comment by alvatar** [comment]
> That is even stranger. May you please try killing the trezord process, restart chrome and try to do it one more time?

I've done this and still get the same issue

> you can use our method testing tool on https://connect.trezor.io/9/methods/bitcoin/getAddress/. It is easier to start connect popup from here.

This thing seems to work, verify the Bitcoin address. But not the above.

So I can't re-add the address that I removed earlier.

**Comment by Hannsek** [comment]
Can you please tell us exact steps you do and what is happening so we can replicate? Possibly with screenshots.

**Comment by alvatar** [comment]
I go to add the hardware wallet in this menu

<img width="417" alt="image" src="https://github.com/user-attachments/assets/81573054-5905-4d60-b2d3-6e206f4059b1">

Click on Trezor and go through these steps

<img width="1232" alt="image" src="https://github.com/user-attachments/assets/f3823384-54cd-45c9-9792-77ef6bcdad0c">

(there I select the wallet and enter the pin)

and then this shows up

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/4b73bca8-0c99-47d8-b704-37c082913496">

**Comment by Hannsek** [comment]
So the last image is shown right after clicking on `export` button?

**Comment by alvatar** [comment]
after selecting the wallet and inserting the pin in that popup

**Comment by Ondra-Zik** [comment]
@alvatar Please try to open this page before you pair the Rabby wallet to start logging your session: https://connect.trezor.io/9/log.html

After you go through all the steps leading to the error, could you please download the log and send it to us at support@trezor.io so it is not shared publicly on GitHub? Please share only the ticket ID here.

**Comment by alvatar** [comment]
I really appreciate your support. But I prefer to just use the other browser even though it's inconvenient, than to send logs of my personal accounts.

**Comment by MiroslavProchazka** [comment]
Hello @alvatar , has this been resolved?

**Comment by martykan** [comment]
Closing as stale, we haven't had recent reports of this issue
