### ISSUE TITLE
Trading - sort out transaction history

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#15024]
## Description 
- split for Buy & Sell and Swap
  - the account does not matter (e.g. in Swaps last transactions will be listed all swaps)
- refactor Transaction Items
- minor design improvements (heading structure, singular/plural counter, swap item design fix) 
- delete `Buy again` from the success Buy Quotes

### Before
![obrazek](https://github.com/user-attachments/assets/849720c3-385c-46d9-b273-41f9c4758b85)

### After 
![obrazek](https://github.com/user-attachments/assets/66c0cece-e451-459b-b2fe-5fc29c028385)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.11.0 (ccc4abd7435e4efabeac8fa846d6e4f7a4e23432)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 5120x1440
 - Device: Trezor T3T1 2.8.4 regular (revision 31d228a325b5968a2f3565b803818aaf7fa29bbb)
 - Transport: WebUsbTransport
