### ISSUE TITLE
Solana - update visual of failed txn

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#15029]
Failed transactions are currently shown almost the same way as successful ones and it looks confusing. Update how failed txn look in:
- [x] Transaction list
- [x] Transaction detail

[Figma](https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?node-id=1583-9572&node-type=section&t=wvLYlKwmzrb0rxSH-0)

<img width="270" alt="Screenshot 2024-10-23 at 14 59 23" src="https://github.com/user-attachments/assets/3272adde-cd29-45c6-8516-3c0446f4be56">
<img width="270" alt="Screenshot 2024-10-23 at 15 00 17" src="https://github.com/user-attachments/assets/a3b438ea-4248-46a6-824e-99e8c64cbd1d">

**Comment by STew790** [comment]
**QA OK**
LGTM
![image](https://github.com/user-attachments/assets/a26c4800-3f32-4627-ba76-9898be0af4ae)
![image](https://github.com/user-attachments/assets/6345b674-e22a-47f7-ae9e-db781e0c257f)

**Info**
24.10.2 https://github.com/trezor/trezor-suite/commit/e4365278aa8be68324c41f57fa796f9b4ee631f9
