### ISSUE TITLE
Send - Remember the transaction fee selected by the user 

### ISSUE THREAD

**Issue by fang314** [trezor/trezor-suite#15046]
As a user during the "send flow, If I go back and forth in the flow without changing anything, I would like that my transaction speed that I have selected is remembered

<img width="393" alt="Screenshot 2024-10-24 at 9 34 54 AM" src="https://github.com/user-attachments/assets/365e0eb1-47fa-4010-a6f4-d2dac25ebc15">

**Comment by STew790** [comment]
**QA OK**
Fee is correctly remembered when I go back a step.

**Info**
24.11.3  6715904
