### ISSUE TITLE
Connect: some coins icons are missing in dropdown menu

### ISSUE THREAD

**Issue by evgenysl** [trezor/trezor-suite#15050]
**Describe the bug**
Since v.9.4.2, some crypto coins icons are missing in Connect Explorer:

![Screenshot 2024-10-24 at 10 43 58](https://github.com/user-attachments/assets/6c3b9a33-036b-4d50-af19-f7d9c3b766f2)

to follow up: 
https://satoshilabs.slack.com/archives/C068FRUFBE2/p1727692748246999?thread_ts=1727686423.770189&cid=C068FRUFBE2

**Comment by mroz22** [comment]
Please retest, is it ok already in develop? https://dev.suite.sldev.cz/connect/develop/

**Comment by evgenysl** [comment]
@mroz22 yes, all looks good on develop and the latest beta
