### ISSUE TITLE
Balance digits consistency

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1506]
Transactions balance should have 8 digits ( and comply with the same rules ) as Account balance.

![Screen Shot 2020-04-10 at 00 03 36](https://user-images.githubusercontent.com/29627086/78944843-29fcd880-7abf-11ea-9cb5-f135c6fcc992.png)

**Comment by slowbackspace** [comment]
I thought we want to display the exact amount at least in ONE PLACE (there should even be enough space). It seems really weird that in wallet-like software I won't see my full balance.
