### ISSUE TITLE
Send Ethereum - mainnet and tokens MVP

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#15060]
We already have send form working for BTC. Make the Bitcoin version of the send form work for ETH and its tokens as well.

## Acceptance criteria
- It is possible to dispatch an ETH or ERC20 transaction from Trezor Suite Lite
- the UI and UX are not adjusted to ETH it still looks the same as BTC flow at this stage

**Comment by STew790** [comment]
**QA OK**
I was able to send ETH and ERC20 tokens.

**Info**
24.11.1  36fdc66
