### ISSUE TITLE
Trading - Add relevant swap/buy/sell buttons to Tokens list

### ISSUE THREAD

**Issue by marek-andrsk** [trezor/trezor-suite#15069]
### Tokens List

- add swap button (icon only), separate from send and receive 
<img width="34" alt="Screenshot 2024-10-22 at 15 27 17" src="https://github.com/user-attachments/assets/683d6907-44c1-4354-b58a-01161f93a997">

- add buy and sell button (icon+label) into the context menu before first item

- buttons will be enabled only for the relevant assets, otherwise disabled

<img width="1629" alt="Screenshot 2024-10-14 at 20 21 37 (1)" src="https://github.com/user-attachments/assets/88c39795-bd66-4f48-9bc3-0b38b9632d24">

**Comment by STew790** [comment]
**QA NOK**
I can buy JUPITER token on SOL but I can't click on the button in tokens list.
![image](https://github.com/user-attachments/assets/68a6c57f-f249-4ca8-8f98-5e40b82acff6)
![image](https://github.com/user-attachments/assets/e8dc5615-d540-4539-b3af-376be0346fc7)

**Info:**
 - Suite version: web 24.12.0 (8869ea943a7f8770a85980dfc752f99ce33f7d70)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.5 regular (revision a61e783448043760a7c925e017bd08a4673a61c8)
 - Transport: BridgeTransport 2.0.33

**Comment by STew790** [comment]
One more thing, should the buttons for sell/buy/swap be actually there when you can't do it for said token? I don't mind it I just wanna know if it is intended because of this:

> buttons will be showing only for the relevant assets - e.g. if a token can be swapped and not bought/sold, only swap is displayed

cc @LukasRada @marek-andrsk

**Comment by tomasklim** [comment]
It is ok

**Comment by STew790** [comment]
**QA OK**
Ok then, :ship: :it: .
