### ISSUE TITLE
multitransport part 1

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#15062]
implement multitransport prerequisites 

## QA 🙏 

this is touching, again, everything related to all transports
- multi devices
- session stealing
- multi tabs/apps
- bridge/node-bride/webusb

**Comment by bosomt** [comment]
Created Notion task to track testing https://www.notion.so/satoshilabs/Multitransport-12adc526060680f1aba7f5fa93acff2a?pvs=4

**Comment by bosomt** [comment]
**QA OK**
