### ISSUE TITLE
Trading - too many requests per time unit while Suite is watching for DEX trade approval

### ISSUE THREAD

**Issue by LukasRada** [trezor/trezor-suite#15063]
**Describe the bug**
Something triggers too many requests to exchange server while watching for DEX trade approval.

**Expected behavior**
The Trezor Suite should make HTTP request only per defined interval (~~currently 30s~~ for trade approval it is 15s).

Reprosteps:
Can be reproduced by swaping any asset which needs approval first. I tried USDT on ETH -> TUSD on ETH with 1inch.

https://github.com/user-attachments/assets/12f769a6-3112-4024-acdc-ae943f403de7

**Comment by bosomt** [comment]
**QA OK**


swapped some POL and nothing suspicious is happening in network section

**Info:**
 - Suite version: desktop 24.12.0 (f7dd25b803538b443f07f880f4fdceaa4faadd1a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: BridgeTransport 2.0.33
