### ISSUE TITLE
Send Ethereum - token send form drafts

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#15078]
The current implementation can store only one send form draft per account. Since we have a separate flow for sending mainnet and token, we need to change the implementation so that a token draft and mainnet draft can be stored without overriding each other.

## Acceptance criteria
- If the user fills the Ethereum mainnet send form, leaves it, and goes to a token send form, the values filled in the mainnet flow are not visible in the token form. 
- User can have a draft of multiple tokens without erasing each other.

**Comment by matejkriz** [comment]
Do we really need this? How many users will have multiple relevant drafts? I would say it's nice to have with very low priority for now. What do you think?

**Comment by matejkriz** [comment]
I didn't realize that the values from draft on token are used to prefill the form for main account or other tokens now. And the solution should be relatively easy. So I agree with the priority now, it would be better to fix it 👌

**Comment by PeKne** [comment]
Note for QA: Try to fill in the send form for multiple tokens, go to the fees screen, and then go to another token. The values should be saved for each token and main net separately and should not override each other.

**Comment by STew790** [comment]
**QA OK**
Since [this](https://github.com/trezor/trezor-suite/issues/15341) was fixed, it is ok now. Send form correctly remembers each token.

**Info**
24.11.1 https://github.com/trezor/trezor-suite/commit/36fdc66a6a60ec39ec68134ae6f1aba13979f1f3
