### ISSUE TITLE
It's impossible to force FW update when memory fault

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1507]
It's impossible to force FW update.
When you need to force update FW because you have memory fault and you can only start device in bootloader mode

Like this:

![image](https://user-images.githubusercontent.com/31506317/78969615-a2878780-7b07-11ea-9117-3149566f1c60.png)

but suite says: 

![image](https://user-images.githubusercontent.com/31506317/78969628-af0be000-7b07-11ea-92aa-16f99902fd38.png)

and of course when you leave bootloader mode you can't install same FW or it says no device

**Comment by mroz22** [comment]
hm I forgot about such cases. Good point!

**Comment by bosomt** [comment]
good job!
im able to instal FW when in BL mode
