### ISSUE TITLE
Absolutely positioned borders

### ISSUE THREAD

**Issue by shenkys** [trezor/trezor-suite#15075]
As talked with David Kotik & @PeKne, let's explore the possibilities of having 1px alpha border in default state and 2px solid border in selected state for selectable component (e.g. fee selection card in send).

As this is a little tricky both in code and figma, let's focus on: 
- when the 2px border appears, the inner content doesn't jump by 1 pixel 
- the 1px alpha border takes the transparency from the page background, not the card itself 

Figma example [here](https://www.figma.com/design/QbqBXe7mu5A6bL0A80EsUQ/%5B%E2%9A%A0%EF%B8%8F-Exploration%5D-Foundation-2.0?node-id=7799-45804&node-type=frame&t=C5kapF4HSF6X8bD5-11).

**Comment by PeKne** [comment]
https://github.com/user-attachments/assets/78b4ee96-e45e-4813-b02e-a6834271e988


The desired behaviour of outside border without a layout shift is achievable in React Native. Demo code can be found here: https://gist.github.com/PeKne/1e807664d3a1945b523fff5be810f39d
