### ISSUE TITLE
Wallet switcher showing the picture of the first connected device

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#15082]
**Describe the bug**
When I have 2 devices connected to the PC, the wallet switcher is showing the animation/picture of only the first one connected when I select either of the two devices. For example when I connect TS3 and TS5 and I connect the TS3 first, it will show the animation and picture of TS3 even though I have selected to show me the wallet of the TS5.

**Steps to reproduce:**
1. Connect TS3 and TS5 to your pc
2. Whichever you connected first will be the one you first see the dashboard of
3. Go to the wallet switcher
4. Select the other device
5. After selecting you can see that the picture is showing the wrong device 

**Info:**
 - Suite version: web 24.11.0 (96159d214b65b6c0c5315f09f571e52fbab8a1be)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/user-attachments/assets/4556b7f9-622f-4e34-aac1-7d4db3cecfb6

**Comment by bosomt** [comment]
**QA OK**

TS5 + TT

**Info:**
 - Suite version: desktop 24.12.1 (ec8321d0d17529ca77d8916e70158cecc469f863)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.12.1 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
