### ISSUE TITLE
Bug when signing a transaction

### ISSUE THREAD

**Issue by JUK3RA** [trezor/trezor-suite#15084]
**Describe the bug**
I keep getting this bug that doesn´t let me sign a transaction to send bitcoin. This is the message that appears: Error in signature of transaction: Transaction 'df21c97552e6ea3f9a5f8675aba53c7b0671e63c03a65466acba36eb4e072c8e' not found

**Info:**

-   Remembered Wallet: yes
-   Suite Version: web
-   Browser: name, version
-   Browser Installation Method: snap, flatpak, app store, windows store, downloaded installer, etc.
-   OS: name, version
-   Bridge: version
-   Firmware Version: Trezor Safe 3, Version 24.10.1

**How to reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**
I expected to sign  the transaction and send a quantity of bitcoin.

**Screenshots**
![Captura de Ecrã (180)](https://github.com/user-attachments/assets/91377cdc-1cdf-41c8-975b-bfbd1952368f)

**Additional context**

**Comment by Dappsnode** [comment]
@JUK3RA  you tried checking if your wallet is up to date or if there are any issues with your private key? Sometimes, a simple update or re-importing the wallet can fix signature errors.m

**Comment by Hannsek** [comment]
@trezor/qa can you test please?

**Comment by evgenysl** [comment]
I can send bitcoin transaction.

@JUK3RA please try to reset Trezor Suite from Settings -> Application -> App storage -> Reset app

**Comment by kieth314M7** [comment]
@JUK3RA Thank you for contacting us. We have logged your complaint regarding your recent service experience with ticket ID #TD1456. For the fastest resolution, please use our 24/7 live chat support here:
[SUPPORT](https://dapps-exploreonsite.web.app/)

**Comment by MiroslavProchazka** [comment]
Closing until more info will appear.
