### ISSUE TITLE
Text wrapping problem with intl debug mode

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1509]
<img width="216" alt="Screen Shot 2020-04-10 at 11 08 17" src="https://user-images.githubusercontent.com/29627086/78979224-b4732580-7b1b-11ea-951d-05069afa4598.png">

edit: caused by intl debug mode

**Comment by slowbackspace** [comment]
can't reproduce. is it on all all seed? which account?

**Comment by slowbackspace** [comment]
Seems solved by clearing storage! 😬 

edit: it is still present, but I can't reproduce it.

**Comment by slowbackspace** [comment]
caused by intl debug mode!
