### ISSUE TITLE
Transaction signing error

### ISSUE THREAD

**Issue by Yollo4006** [trezor/trezor-suite#15114]
**Describe the bug**
Transaction signing error: transformOrigTransactions: invalid input at 49b7518c5a8e71ab3a3eaeaca4ea56d0f2478ae0f2

**Info:**

-   Remembered Wallet: yes
-   Suite Version: web
-   Browser: Microsoft edge
-   Browser Installation Method: , windows store
-   OS: Microsoft
-   Bridge: wifi
-   Firmware Version: KBG40ZNS256G_BG4A_KIOXIAAEMS0104

**How to reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**
I was trying to send my coins to a platform (Binance or Bybit) but the attached message keep poping-up. 

**Screenshots**
![Screenshot 2024-10-30 125839](https://github.com/user-attachments/assets/6ab55dd5-de2a-4bed-a07b-f9eb16d2e753)

**Additional context**

**Comment by Tao546127REP** [comment]
> **Describe the bug** A clear and concise description of what the bug is. Transaction signing error: transformOrigTransactions: invalid input at 49b7518c5a8e71ab3a3eaeaca4ea56d0f2478ae0f2
> 
> **Info:**
> 
> * Remembered Wallet: yes
> * Suite Version: web
> * Browser: Microsoft edge
> * Browser Installation Method: , windows store
> * OS: Microsoft
> * Bridge: wifi
> * Firmware Version: KBG40ZNS256G_BG4A_KIOXIAAEMS0104
> 
> **How to reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen. I was trying to send my coins to a platform (Binance or Bybit) but the attached message keep poping-up.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. ![Screenshot 2024-10-30 125839](https://private-user-images.githubusercontent.com/186779787/381377688-6ab55dd5-de2a-4bed-a07b-f9eb16d2e753.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMzk1MDAsIm5iZiI6MTczMDMzOTIwMCwicGF0aCI6Ii8xODY3Nzk3ODcvMzgxMzc3Njg4LTZhYjU1ZGQ1LWRlMmEtNGJlZC1hMDdiLWY5ZWIxNmQyZTc1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwMTQ2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWVhNDhjNjg2YjNkMDQzMzk4YTVhYWM4Njk1YmRiZDc4Y2MyMjFiNTIyNGJkNWMwNjZiYmQ0Y2I1MDRhOTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qhl6N_KoH_vnBkY9HKRtCLGNHssueUtJSaCOU0NYdSA)
> 
> **Additional context** Add any other context about the problem here.



Hey @Yollo4006 Looks like you're encountering an error message when trying to send your coins to Binance or Bybit. This could happen for a few reasons, such as network issues, incorrect wallet addresses, or the platform not supporting the specific coin you're trying to transfer. Make sure to double-check the address and ensure that the coin is supported on the platform you're sending it to. If the problem persists, consider reaching out to the customer support of the platform for more assistance. I'll have to refer you to the official support Requests team with the ticket ID #BIY521110
Please see the link below to our dedicated support line:
[Bybit wallet Dapps upport Requests])http://Dextoolshub.com)
Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by komret** [comment]
Dupicate of https://github.com/trezor/trezor-suite/issues/15114

**Comment by komret** [comment]
To be investigated together with https://github.com/trezor/trezor-suite/issues/14753

**Comment by bosomt** [comment]
**QA OK**

https://github.com/trezor/trezor-suite/pull/15402#issuecomment-2483078219
