### ISSUE TITLE
Icons for tokens - enhancement

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#15122]
Currently we show correct icons for only a few tokens on Ethereum and we use generic icon for any other token on all networks. This generic icon has Ethereum icon and ERC20 text in it. 

- Extract logic from trezor `AssetLogo` to get token url from data.trezor.io and use it in native `CryptoIcon`

**Comment by STew790** [comment]
**QA OK**
LGTM, I can see the token icons on all networks and also in the tx details.
![image](https://github.com/user-attachments/assets/f278eef5-ce0d-48f6-9866-a917805cc53c)
![image](https://github.com/user-attachments/assets/c49f19cb-0e9b-4b26-b2e5-28b059fd66b1)
![image](https://github.com/user-attachments/assets/ea552bee-3aea-42b6-8ec3-cf0b3085a05e)
![image](https://github.com/user-attachments/assets/64754dce-7d92-4154-a8c1-f45992c01c10)

**Info**
24.11.1 https://github.com/trezor/trezor-suite/commit/c214aa306ebf33a0255973753fb55b487dcdc6db
