### ISSUE TITLE
App crashes when installing custom firmware via trezorctl or web Suite

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#15133]
**Describe the bug**

When installing custom firmware via `trezorctl firmware update -f file` or via web suite Suite crashes and its not able to load even after reload. 
Probably clash of multiple transports?
After install reload button works as expected.

```
Objects are not valid as a React child (found: Error: Unable to open device). 
If you meant to render a collection of children, use an array instead.
```
**Steps to reproduce:**
1. Open Suite app
2. Update device via trezrctl
3. Observe App behavior

**Info:**
 - Suite version: desktop 24.11.0 (661633dc3f8f690c3338fe5f47da748a1c374525)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision 3c468fa4ddb0dc28ff7476c6312721babbf71410)
 - Transport: BridgeTransport 3.0.0-bundled.24.11.0

**Screenshots:**
![image](https://github.com/user-attachments/assets/5a7c1620-3918-4a85-a387-2c1ee71a20b0)

https://github.com/user-attachments/assets/dfe8dfd0-dba2-4da7-b2de-8a52294a2617

https://github.com/user-attachments/assets/bfa15cd2-a73b-4895-a479-44350be43aeb

**Comment by mroz22** [comment]
@bosomt can you please retest? 

at least the crash stating "Objects are not valid...." should be go now. 

It could be that you will see "unable to open device" or similar error. But I was unable to reproduce myself on my machine right now

**Comment by bosomt** [comment]
**QA OK**

4x QA OK
tested with trezorctl and web suite vs latest dev app
retested with 3.0 bridge version 

**Info:**
 - Suite version: desktop 24.12.0 (19aeb1a0f7d306fcbe7cc61ed330a2481a3d0e4e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: BridgeTransport 2.0.33
 - Transport: BridgeTransport 3.0.0-bundled.24.12.0
