### ISSUE TITLE
Adding an account to portfolio doesn't show it in portfolio

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#15131]
**Describe the bug**
When I scan a QR code of an account to sync it to my Portfolio, it doesn't actually show it in the portfolio after adding it.

**Info:**

-   Mobile Suite Version: 24.10.2   41e1bb2
-   OS: Android

**How to reproduce**

1. Go to Portfolio tracker
2. Select "Sync & Track" to sync any account
3. Scan any account to add it
4. It shows the balance
5. Confirm it
6. Nothing shows on the dashboard

**Comment by matejkriz** [comment]
fixed by https://github.com/trezor/trezor-suite/pull/15153

**Comment by STew790** [comment]
**QA OK**
Adding accounts to portfolio correctly shows them (and even accounts added when this issue was present are correctly shown)
**Info**
24.10.2 e436527
