### ISSUE TITLE
`ReconnectDevicePrompt` not visible

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#15157]
When you click "Install firmware" in the FW update flow, `ReconnectDevicePropt` is not visible, which may lead to confusion, mainly in the manual flow.

Current state:
![Screenshot 2024-10-31 at 18 59 06](https://github.com/user-attachments/assets/1e9a8f0a-a519-4682-b2c2-0888658434ee)

How it should look:
![Screenshot 2024-10-31 at 19 01 15](https://github.com/user-attachments/assets/86b0cb70-55f5-4edc-bd1f-d1d4c64be8e4)

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/cfc90d6b-0543-4702-8f8c-5b8f2f012e8e)

**Info:**
 - Suite version: web 24.11.0 (ccc4abd7435e4efabeac8fa846d6e4f7a4e23432)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 5120x1440
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport
