### ISSUE TITLE
`ReconnectModal|Prompt` visual bugs

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#15169]
`ReconnectDevicePrompt` was refactored and redesigned in https://github.com/trezor/trezor-suite/pull/14643, which left the manual flow broken:

Before:
![Screenshot 2024-11-01 at 11 33 08](https://github.com/user-attachments/assets/677f022e-555b-4429-81a4-423fcd0617de)
After:
![Screenshot 2024-11-01 at 11 25 26](https://github.com/user-attachments/assets/312fb288-7015-4b9b-a455-d3762db61b70)

- [ ] low vertical margins
- [ ] no border radius on animation
- [ ] active step not highlighted
- [ ] button misaligned

How to access manual flow:
- install old firmware not supporting `rebootToBootloader` (I used 2.1.4 on TT)
- update firmware

**Comment by bosomt** [comment]
Do we plan to align find button , if its expected design feel free to approve issue.
Tested on outdated TT with fw 2.4.2 with no reboot to bl feature.

![Image](https://github.com/user-attachments/assets/627656e6-6f12-4946-b291-f19a13282b6f)


**Info:**
 - Suite version: web 24.11.0 (258ab9664fb9cddbc0bd28638f00b56583b15e1d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: WebUsbTransport

**Comment by bosomt** [comment]
**QA NOK**

find button misaligned 

<img width="368" alt="Screenshot 2024-11-05 at 9 17 29" src="https://github.com/user-attachments/assets/568dcb7e-afcd-480f-adb8-b4e1f28497a5">

**Info:**
 - Suite version: web 24.11.0 (c58454703ba01107ffa6e7938e1608354342b26a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.12.1 bitcoin-only (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: WebUsbTransport

**Comment by komret** [comment]
@bosomt, I also find it a bit weird, but I think it is expected based on the screenshot in the [PR](https://github.com/trezor/trezor-suite/pull/15182). Is that right, @adamhavel?

**Comment by seibei-iguchi** [comment]
> @bosomt, I also find it a bit weird, but I think it is expected based on the screenshot in the [PR](https://github.com/trezor/trezor-suite/pull/15182). Is that right, @adamhavel?

I'll make it aligned to the middle though
