### ISSUE TITLE
Update @everstake/wallet-sdk because of security warnings

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#15176]

**Comment by bosomt** [comment]
**QA OK**

- THOL - stake, unstake, claim OK
- ETH claim OK

**Info:**
 - Suite version: desktop 24.11.0 (e65d214d92f513962e8322d8cabd9bf63e320b79)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Transport: BridgeTransport 3.0.0-bundled.24.11.0
