### ISSUE TITLE
Usd istead of dollar sign 

### ISSUE THREAD

**Issue by enjojoy** [trezor/trezor-suite#15178]
**Describe the bug**
![image](https://github.com/user-attachments/assets/0459798a-d464-45f3-8cd3-082cd865c7f1)

**Expected behavior**
Dollar sign instead of the currency shortcut

**Comment by evgenysl** [comment]
QA OK

![Screenshot 2024-11-05 at 13 35 17](https://github.com/user-attachments/assets/05b84183-e54c-46b3-b754-be8aae531737)
![Screenshot 2024-11-05 at 13 36 16](https://github.com/user-attachments/assets/56bfd739-b331-42fd-99b1-2dda1504aa94)
