### ISSUE TITLE
Send Coins - Custom fee

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#15180]
## Acceptance criteria
User is allowed to specify custom fee rate if he does not like any of the predefined fee levels provided.

**Comment by PeKne** [comment]
Notes for the QA: the custom fee now works for all the send-enabled networks. Please try each of the networks at least once. Also, test setting a custom fee while sending the `max` amount. The total transaction amount should always stay the same, but the outputs should adjust according to the custom fee.

**Comment by STew790** [comment]
**QA OK**
- I was able to set custom fee for all coins with "Send"
- when I set "Send max" the fee got always deducted correctly and the "max" value adjusted accordingly
- the custom fee is correctly remembered as well

**Info**
24.11.3 https://github.com/trezor/trezor-suite/commit/6715904f662cf02dc22969ac659849b3a1b1a11b
