### ISSUE TITLE
Tokens drop-down menu is hidden outside of view/window

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#15198]
**Describe the bug**
When I click on the `...` menu in tokens section (doesn't matter the coin) it can be shown outside of view/window. See screenshot.

**Steps to reproduce:**
1. Navigate to tokens section of either coin that has tokens
2. Click on the token menu of the last token in the list
3. It can be shown outside of view

**Info:**
 - Suite version: web 24.11.0 (1d93e3c26b2b23c0d8f983919618d9fdcaa93533)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
The drop-down menu should be fully shown.

**Screenshots:**
![image](https://github.com/user-attachments/assets/4af79a6a-994e-4052-a82c-9c393efa066d)

**Comment by adderpositive** [comment]
Same here: https://github.com/trezor/trezor-suite/issues/15135

**Comment by STew790** [comment]
Ah, sorry, didn't see this issue, will close it as a duplicate then.
