### ISSUE TITLE
Coinmarket - cannot continue with sell - infinite button loading

### ISSUE THREAD

**Issue by LukasRada** [trezor/trezor-suite#15190]
**Describe the bug**
"Confirm on Trezor & Send" is disabled and in loading state while advancing through sell. The sell trade is in valid (non-blocked or non-loading) state.

**How to reproduce**

1. Go directly to https://suite.trezor.io/web/  in web browser (or desktop version)
2. Choose an account, e.g. Bitcoin account
3. Click on “Buy & Sell” button
4. Go to “Sell” section
5. Fill out amount to sell and click on “Compare all offers” button
6. Choose BTC Direct offerby clicking on “Select” button => click “I’m ready to sell”
7. Click on “Proceed” button => Infinite loading “Confirm on Trezor & Send” button appears

**Expected behavior**
The button has to be available when a user can continue with valid sell trade.

**Screenshots**
## Current version
![image](https://github.com/user-attachments/assets/1d0a15ce-d2da-4c18-b17b-428bc910a975)

## Fixed version
![image](https://github.com/user-attachments/assets/5a6a835f-28c4-4cee-816a-f151dd4d85c3)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.11.0 (c58454703ba01107ffa6e7938e1608354342b26a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision 31d228a325b5968a2f3565b803818aaf7fa29bbb)
 - Transport: WebUsbTransport
