### ISSUE TITLE
Double scroll bar on Windows

### ISSUE THREAD

**Issue by evgenysl** [trezor/trezor-suite#15195]
**Steps to reproduce:**
1. Appears on startup
2. Snap window to right (Win+>) or full size (Win + arrow up)
3. Observe double scroll bar

**Info:**
 - Suite version: desktop **24.11.0 (fff042a80d260c7e7ff7fefe705478585e87853a)**
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: Windows 10
 - Screen: 1536x864
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![scroll1](https://github.com/user-attachments/assets/3b2dd2aa-29bf-4df5-8c7d-145c841b7da2)
![scroll2](https://github.com/user-attachments/assets/8df16ff1-0462-434d-a2ec-c02373ba0ebc)

**Comment by Lemonexe** [comment]
Couldn't reproduce at windows 10.
@evgenysl can you try again with [24.11.1 draft](https://github.com/trezor/trezor-suite/releases/tag/untagged-03e762416f7d0501ffc1)?
I've tried win→, win↑, minimize, fullscreen, manually resizing, and the same with display resolution lowered to 1152x864.
Nothing, just single scrollbar :/

**Comment by evgenysl** [comment]
Confirm same bug on 24.11.1 RC

Screen resolution is 1920x1080

**Comment by evgenysl** [comment]
![scaling](https://github.com/user-attachments/assets/7f5bcd73-3351-45ba-8937-7f11e509567e)

This bug is happening on 125% scaling
Not reproducible on 100% scaling

**Comment by Lemonexe** [comment]
📝 WIP notes:
- It's some off-by-1-pixel kind of error.
- Indeed, it's only on 125% scaling, but regardless of resolution (I reproduced at 2560x1440 + 125% scaling),
- And it's not limited to just win← or win→
- I can grab the window, slowly resize its height and it does this _every 6th pixel_ for some reason 🙈

**Comment by evgenysl** [comment]
Fixed on Windows 1920 x 1080

Tried 125, 100 and 150% scaling.

QA OK
