### ISSUE TITLE
Use immerjs for reducers

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#152]

**Comment by mroz22** [comment]
Missing reducers 

Onboarding
- [x] connectReducer (needs broader refactoring though, I ll do) (in 
b08bdc6)

Suite
- [ ] modalReducer
- [x] ~~routerReducer~~ (intentional)

Wallet
- [x] selectedAccountReducer

**Comment by slowbackspace** [comment]
I think we are good for now, all (almost) existing reducers are rewritten. I am closing the issue.
