### ISSUE TITLE
Portofolie - delete buy button

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#15218]
## Description
Delete the buy button from a portfolio if the wallet is empty.

### Before

![image](https://github.com/user-attachments/assets/a76db244-e000-4d35-a248-a022a4287e28)

### After

![image](https://github.com/user-attachments/assets/4b945576-5a57-4425-888c-33e73f808ea6)

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/c01357ed-93f0-499d-9aff-7ee6762c334d)

**Info:**
 - Suite version: desktop 24.11.1 (9e9dadff47c5243bf4a10f539a898fe48da46506)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.5 regular (revision d72aab0bf75a9cfe6679da87efc4ac33382468dc)
 - Transport: BridgeTransport 2.0.33
