### ISSUE TITLE
Show how much fee is needed to send token tx

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#15219]
**Describe the bug**
Based on [Slack](https://satoshilabs.slack.com/archives/C016ACNF1BN/p1730561896489939)
Related to https://github.com/trezor/trezor-suite/issues/13756

User is missing info what is enough ETH to cover token tx fee 
<img width="684" alt="Screenshot 2024-11-05 at 10 59 28" src="https://github.com/user-attachments/assets/e07feb5d-6412-41ff-b838-b9b890d04558">

**Info:**

-   Suite Version: 24.11.0

**Expected behavior**
We can also add it into error message `With current network fees (5 gas price), enough amount of ETH is 0.001`
<img width="682" alt="Screenshot 2024-11-05 at 10 58 22" src="https://github.com/user-attachments/assets/0ee0da2d-7ce6-428c-b389-e8dfde60e24f">

**Comment by bosomt** [comment]
**QA OK**

<img width="766" alt="Image" src="https://github.com/user-attachments/assets/44795704-6ab1-4254-b4a8-2390c12a7ea3" />

**Info:**
 - Suite version: desktop 25.1.0 (20a35a51ea92edb7ffa42c696f6da297c66d2971)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
