### ISSUE TITLE
Suite doesn't calculate crypto value correctly in send form after deleting and writing again the fiat input

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#15227]
**Describe the bug**
Suite doesn't calculate crypto value correctly in send form after deleting and writing again the fiat input. It works best with only single digit number but I managed to replicate it sometimes with even 2 digits.

**Steps to reproduce:**
1. Navigate to send form of any coin
2. Write any fiat value and delete it
3. Write a single digit fiat value again
4. The crypto value isn't calculated at all or incorrectly

**Info:**
 - Suite version: web 24.11.0 (b7afbd05152736013d619dfd9dc9f10143fbd216)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/user-attachments/assets/9c454141-f11f-4a27-ad6e-f4c62ce9bc71

**Comment by bosomt** [comment]
**QA OK**

tested on ETH and SOL
works as expected 🎉 

**Info:**
 - Suite version: web 24.12.0 (0c7477e1102acb3fd29cd80579fdba7763f736d0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport
