### ISSUE TITLE
Order networks by networkConfig

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#15222]
Currently mobile app uses custom ordering of networks in coin enabling, dashboard and portfolio tracker . Remove this and use ordering based on how networks are ordered in the [networksConfig](https://github.com/trezor/trezor-suite/blob/develop/suite-common/wallet-config/src/networksConfig.ts).

**Comment by STew790** [comment]
**QA OK**
Networks are ordered correctly according to https://github.com/trezor/trezor-suite/blob/develop/suite-common/wallet-config/src/networksConfig.ts 

**Info**
24.11.1 https://github.com/trezor/trezor-suite/commit/ff16b788c576e89bbbfc17cbe783154223440336
