### ISSUE TITLE
Suite needs passphrase input for every action after reconnecting to view only wallet

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#15226]
**Describe the bug**
When I reconnect my device to Suite and I have my wallet in view-only mode, Suite wants passphrase input for "every" action there is and not only once per session.

**Steps to reproduce:**
1. Connect device with passphrase
2. Enable view only for the wallet
3. Disconnect device
4. Reconnect device
5. Go to any account and select receive address
6. Suite asks for passphrase
7. Now go to any other receive address to show it
8. Suite asks for passphrase again

**Info:**
 - Suite version: web 24.11.0 (b7afbd05152736013d619dfd9dc9f10143fbd216)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
Suite wants passphrase input only once per session.

**Actual result:**
Suite wants passphrase input for "every" action there is and not only once per session.

**Comment by evgenysl** [comment]
1. Connect device with passphrase
2. Enable view only for the wallet
3. Disconnect device
4. Reconnect device
5. Go to Bitcoin 1 account and select receive address
6. Suite asks for passphrase
7. Now go to Bitcoin 2 account select receive address
8. Suite **do not ask** for passphrase second time

**QA OK**



**Info:**
 - Suite version: desktop 24.12.0 (ec680379be0dba0729ca169420c7379492a7cc46)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
