### ISSUE TITLE
Unhide button in tokens should be "Copy" contract address button

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#15242]
**Describe the bug**
When you want to copy contract address of a token, in the modal the button for the copy says "Unhide" .

**Steps to reproduce:**
1. Go to tokens section of any network
2. Click on the copy contract address button of one of the tokens
3. A contract address warning modal appears
4. In this modal the "Unhide" button actually copies the contract address

**Info:**
 - Suite version: web 24.11.0 (3ccb452ad86f2ab00b456018a6cb6223320ba71c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/user-attachments/assets/b592b329-d0a4-47f0-8fbf-5fc9c7562a2c)

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/1bddc4aa-0ab9-4844-8d21-3651691b73d1)

**Info:**
 - Suite version: desktop 24.11.1 (9e9dadff47c5243bf4a10f539a898fe48da46506)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.5 regular (revision d72aab0bf75a9cfe6679da87efc4ac33382468dc)
 - Transport: BridgeTransport 2.0.33
