### ISSUE TITLE
Exclude some networks from graph and adjust UI

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#15247]
For various reasons we want to exclude some networks from graph and not show the graph in the account detail as well. The main example is Solana (desktop also does not show Ripple), where fetching txns takes a long time and costs a lot of resources.

We need to adjust UI for this:

- [x] Hide graph on dashboard if user has only graph-disabled networks
- [x] Hide graph in disabled networks account details
- [x] Tell user that some networks (SOL) are not part of the graph
- [x] remove infinite scrolling and introduce button to load more txns

**[FIGMA](https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?node-id=0-1&node-type=canvas&t=SxZFvZrePzBclO0J-0)**

<img width=280 src="https://github.com/user-attachments/assets/03d949cc-aa54-4920-b447-604ba1e056d6" />
<img width=280 src="https://github.com/user-attachments/assets/88fb0ff0-0d78-4a00-a365-e157c3332372" />

**Comment by shenkys** [comment]
https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?node-id=1725-10116&node-type=section&t=tTXg03Wsfb93PWLK-11

**Comment by STew790** [comment]
**QA OK**
- graph on dashboard hidden when only SOL enabled
![image](https://github.com/user-attachments/assets/ae096899-d7d8-4d39-a88c-199fd73645d0)
- graph hidden in SOL accounts details
![image](https://github.com/user-attachments/assets/35269509-aece-4ca5-874d-e0d6c077e2eb)
- user informed that SOL is not included in the graph
![image](https://github.com/user-attachments/assets/78fca53e-354a-4d38-8f51-8f5afd16514c)
- infinite scrolling removed, load button present and working (first only 16 accounts loaded, load more button shows 21 txns)
![image](https://github.com/user-attachments/assets/7b7b65f9-034e-4042-ad58-9c69af98cf78)
- portfolio is the same

**Info**
24.11.3 https://github.com/trezor/trezor-suite/commit/712c824923c35d82c634b3995cc14b8257f89770
