### ISSUE TITLE
Extend message system to include AB testing variant

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#15279]
## Description 
- Experiments would use Message System to configure Feature Flags (i.e. there will be no UI to config experiments, deploy of the messaging system will be required - independent from Suite release though).
- Experiment ID (e.g. rename-trade-section) 
   - Multiple Variation IDs (e.g. control, buy-swap) - this may be unlimited, but in reality, we won’t use more than 4 for one experiment
   - Each would have a distribution percentage set between 0 - 100%

**Comment by tomasklim** [comment]
Closing in favor of [#15067](https://github.com/trezor/trezor-suite/issues/15067)
