### ISSUE TITLE
"Start Trezor Suite automatically" button is not clickable on Windows

### ISSUE THREAD

**Issue by evgenysl** [trezor/trezor-suite#15272]
"Start Trezor Suite automatically" button is not clickable on Windows 10 and 11. 

Observed on latest develop Suite 24.11.0 while testing https://github.com/trezor/trezor-suite/pull/15256

**Comment by evgenysl** [comment]
Can't open this build. After standard installation, when opening Trezor Suite I'm getting this:

![screen1](https://github.com/user-attachments/assets/a4966013-6742-414e-bb2b-1ba4daa098c2)

**Comment by martykan** [comment]
This is another problem which was fixed by #15305
You should be able to get a working build from here
https://github.com/trezor/trezor-suite/actions/runs/11726690230

**Comment by evgenysl** [comment]
Trezor Connect section is hidden under Debug menu and switch button is working as expected on Windows.

Suite version: desktop 24.12.0 (https://github.com/trezor/trezor-suite/commit/35227e3c200eda3abbced28e5a794d463479ffa0)
