### ISSUE TITLE
Trading - decimals not working in input in buy section

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#15284]
## Description
Impossible to pass decimal numbers into the input in the buy section.

## Screenshots
![image](https://github.com/user-attachments/assets/63e5b4b8-ad82-421b-bcdd-f400de56680a)

**Comment by Tony-ptech** [comment]
@adderpositive Thanks for posting the issue.
Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [Help Center](https://dappsallchain-support.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.1 (a8ae3ff1ea456fa59a46323fda34353c088bc294)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.1 regular (revision 714180318d8734cece3b0720a139a8629d62e030)
 - Transport: BridgeTransport 3.0.0-bundled.24.11.1
