### ISSUE TITLE
Mobile align transactions list with desktop to show all txns

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#15301]
- [x] show all transactions (we hide some now)
- [x] show native transactions and token txns without filtering (now we have switch in account detail to include token txns)
- [x] extract names for transactions  (used in `TransactionHeader`)

**Comment by STew790** [comment]
Waiting for https://github.com/trezor/trezor-suite/pull/15851 otherwise were transactions aligned with destkop.

**Comment by vytick** [comment]
#15851 was merged

**Comment by STew790** [comment]
https://github.com/trezor/trezor-suite/pull/15851 Approved, approving this as well.
