### ISSUE TITLE
Passphrase not requested on host after reconnecting remembered device

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#15306]
**Describe the bug**
When I enable view only for my passphrase wallet and reconnect my device and I want to either check my receive address or send a tx or enable a new coin, I get a request for passphrase on my device but not on my phone.

**Info:**

-   Mobile Suite Version: 24.10.2 https://github.com/trezor/trezor-suite/commit/e4365278aa8be68324c41f57fa796f9b4ee631f9
-   OS: Android

**How to reproduce**

1. Connect a device
2. Open a passphrase wallet
3. Enable view only for that wallet
4. Reconnect the device
5. Go to "Show receive address" or "Send" or "coin enabling" (and enable any coin)
6. You are prompted to enter passphrase on device but not on host so you can't enter it

**Screenshots**

https://github.com/user-attachments/assets/44d26cba-5aac-4571-a828-b6961957c4f4

**Comment by vytick** [comment]
should be resolved by [#15327](https://github.com/trezor/trezor-suite/pull/15327)

**Comment by STew790** [comment]
**QA OK**
Works as expected. I can enter my passphrase.

**Info**
24.11.1 https://github.com/trezor/trezor-suite/commit/ff16b788c576e89bbbfc17cbe783154223440336
