### ISSUE TITLE
(Do not) Reintroduce `@typescript-eslint/no-shadow` 

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#15311]
I think it brings more hard then benefit. It supper annoying and I am not sure if it really can help with something.

With Typescript, its very hard to introduce an error by shadowing anyway,

Even with most lenient configuration
```
'@typescript-eslint/no-shadow': [
    'error',
    {
        builtinGlobals: false,
        hoist: 'never', // most lenient variant
        allow: ['_', 'error', 'resolve', 'reject', 'fetch'],
    },
],
```

It is 192 errors

**Comment by Nodonisko** [comment]
We agreed to turn this on not that long ago and I prefer to have this enabled. 

You may disable this for this desktop if you want but please leave this on for mobile.
