### ISSUE TITLE
When importing first ETH accounts, tokens are not displayed on summary screen

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#15332]
In portfolio tracker when importing first token for coin that supports tokens, tokens are not displayed on import summary because token definitions are not fetched. It will work for second account because it will fetch token definitions for first account.

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/4b7f5045-c82f-41e4-af24-7bbc3b0bcd8c)

**Info**
24.11.1 35433e7
