### ISSUE TITLE
node bridge - another case of segfault 11

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#15336]
1. get address 
2. show address on device active
3. disconnect device 
4. node-bridge dies 

```
@trezor/transport-bridge Handling request for POST /release/3
@trezor/transport-bridge usb: closeDevice. device.opened: true
@trezor/transport-bridge usb: device.releaseInterface: 0
@trezor/transport-bridge Request POST /release/3 aborted
@trezor/transport-bridge usb: releaseInterface error Error: reset error: Error: LIBUSB_ERROR_TIMEOUT. device: {"productName":"TREZOR","manufacturerName":"SatoshiLabs","serialNumber":"C320C738E14062788C37A51E","vendorId":4617,"productId":21441,"deviceVersionMajor":1,"deviceVersionMinor":0,"opened":true}
@trezor/transport-bridge usb: device.close
Segmentation fault: 11
```

it looks like that we are trying to releaseInterface for a device that is no longer there but we don't know about it because disconnect event is not fired in this case.

the culprit causing it is this https://github.com/trezor/trezor-suite/pull/14092/files#diff-c3affa910cc3a7ed65bcf910b11dc07b7407c5ba91394f76b80f14677a3c14faR369-R372

**Comment by evgenysl** [comment]
Testing on **Windows**:

with Suite running
version: desktop 24.11.1 (a8ae3ff1ea456fa59a46323fda34353c088bc294)

   1. Go to Bitcoin account -> Receive address
   2. Show address on Trezor
   3. Disconnect Trezor
   4. Node-Bridge is still running on http://127.0.0.1:21325/status/
   5. Reconnect Trezor
   6. Trezor is discovered in node-bridge Devices and Suite


https://connect.trezor.io/9/methods/bitcoin/getAddress/

1. getAddress
2. Show address on Trezor
3. Disconnect device before clicking Confirm
4. Node-Bridge is still running
5. Reconnect Trezor
6. Trezor is discovered in Node Bridge
7. getAddress successful


Same results on Mac Arm with Suite running.
Node-Bridge is not crushing when disconnecting Trezor during getAddress.

**Comment by evgenysl** [comment]
Both on **Windows** and **MacOS**:

with Trezor Suite closed, but node-bridge process running

https://connect.trezor.io/9/methods/bitcoin/getAddress/

1. getAddress
2. Show address on Trezor
3. Disconnect device before clicking Confirm
4. Node-Bridge is still running
5. Reconnect Trezor
6. Trezor is discovered in Node Bridge
7. getAddress successful

**Comment by evgenysl** [comment]
Re-tested on 24.11.2 b44a924ad9e7cb96c8eaadfdca45e4183314bd66 with T1.
Not reproducible on Arm Mac yet.


https://github.com/user-attachments/assets/366ee388-36a4-4464-82b3-bfdacf60e066



After reconnecting T1, session changed from 10 to 14 which is correct.

**Comment by mroz22** [comment]
![image](https://github.com/user-attachments/assets/6fd7512a-2c95-49b8-89a0-47b47c688f50)

what is your version @evgenysl ?

**Comment by evgenysl** [comment]
15.1.1 (24B91) and same results at Boso's Mac

**Comment by evgenysl** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.12.1 (7571aef50689644cd309c06c809e2ceea025e021)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.12.1 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.27
