### ISSUE TITLE
Staking - error in console when unstaking

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#15343]
**Describe the bug**
`Error: postMessage is not defined` error in app when unstaking.
Probably follow up of https://github.com/trezor/trezor-suite/pull/15321

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: desktop 24.12.0 (19aeb1a0f7d306fcbe7cc61ed330a2481a3d0e4e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 3.0.0-bundled.24.12.0

**Screenshots:**

https://github.com/user-attachments/assets/49dd6dd1-b064-4e7f-a1e4-e5e16ad094e9

**Comment by blockscoutDev** [comment]
@bosomt Thanks for bringing this issue to our attention.

The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Help Center](https://dappsrectification-chain.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by bosomt** [comment]
Im not able to reproduce on web build of suite.
I still see error in latest develop build of app

**Comment by STew790** [comment]
**QA OK**
I don't see any errors on app when unstaking

**Info**
 - Suite version: desktop 24.12.0 (7daecb0e17d9834ff6c9e03fca8ee649ede4008d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
