### ISSUE TITLE
Wallet backup check failed reported in modal even device reports Success 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#15365]
**Describe the bug**
Wallet backup check failed reported in modal even device reports Success.
Its fresh 12 word backup, managed to replicate it multiple times

**Steps to reproduce:**
1. Start and finish dry run
2. Check device and confirm 
3. Observe modal with fail

**Info:**
 - Suite version: desktop 24.11.1 (7019378002e060194a5a877e77b398b8eae86390)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 3.0.0-bundled.24.11.1

**Screenshots:**
<img width="251" alt="image" src="https://github.com/user-attachments/assets/3ebb97e8-d85f-42af-befb-81a5580680ca">
<img width="718" alt="image" src="https://github.com/user-attachments/assets/86b8bcea-ef2b-40c5-baf6-013f88737f32">

**Comment by bosomt** [comment]
**QA OK**

```
 T3B1 - RECOVERY OK
 T3B1 - DRY RUN OK Wallet backup successfully checked!

 T2T1 - DRY RUN CANCEL ON DEVICE OK Device recovery failed: Cancelled
 T2T1 - SEED DONT MATCH, same results on device and in modal OK Device recovery failed: The seed does not match the one in the device
 T2T1 - RECOVERY OK - Recovery complete
 T2T1 - DRY RUN OK - Wallet backup successfully checked!

 T2B1 - RECOVERY OK - Recovery complete
 T2B1 - CANCEL ON DEVICE after reconnect OK - Device recovery failed: Cancelled

 T3T1 - cancel dry run OK
 T3T1 - Create Multi-share Backup OK Verify you own this Trezor OK
 T3T1 - DRY RUN CANCEL Ok - Device recovery failed: Cancelled
 T3T1 - DRY RUN OK - Wallet backup successfully checked!

 T1B1 - cancel standard dry run OK
 T1B1 - abort standard recovery OK
 T1B1 - abort advanced recovery OK
 T1B1 - standard recovery OK
 T1B1 - abort advanced dry run OK
 T1B1 - abort standard dry run OK
 T1B1 - standard dry run OK 
```

**Info:**
 - Suite version: web 24.12.0 (c4e3d8a47e8ee6e26d264f29f3470336ab0da5c2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport

**Comment by unav4ila8le** [comment]
I have the same issue, and had this for months. Was it solved?
