### ISSUE TITLE
Send XRP

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#15369]
Enable XRP send in Trezor Suite Lite app.

[Design](https://www.figma.com/design/sqKFZAIvk3zERxiWgthK8K/Send?node-id=2830-19660&node-type=canvas&t=vxkb3Ps0F8C1Ft2h-0)

### Acceptance criteria
- send flow works for XRP in the same was as for any other coin
- user is can input destination tag
- if the destination tag was submitted. there is an extra screen for reviewing the tag before the address review

**Comment by PeKne** [comment]
Notes for QA: Try to send some XRP. Send one transaction without specifying the destination tag and the second one where you include it.

Also, try to break the app by exiting the flow from any step (address review, outputs review, cancelation from HW device, etc.).

Thanks 🙏

**Comment by STew790** [comment]
**QA OK**
- happy path works OK
- with tag as well
- extra screen with confirming the tag is present
- I wasn't able to break this, cancelling/going back from anywhere works as expected
- unable to send to myself
- locked or passphrase protected device works correctly as well

**Info**
24.11.3 034c264
