### ISSUE TITLE
Staking APY doesn't reflect reality

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#15362]
**Describe the bug**
The presented APY doesn't reflect what is offered by [Everstake](https://eth-api-b2c-stage.everstake.one/api/v1/stats)

**Info:**

-   Mobile Suite Version: 24.11.1 (746) 35433e7
-   OS: Android

**How to reproduce**
1. Add staking
2. Check APY
3. See 4.13%

**Expected behavior**
See value from [Everstake](https://eth-api-b2c-stage.everstake.one/api/v1/stats)

**Screenshots**
![image](https://github.com/user-attachments/assets/d7086ac8-2ac7-4baa-819a-cfce88cd01b2)

**Comment by sime** [comment]
Issue is on 24.10 production too.

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/52c5cfe4-3b26-4dec-aeaa-a953820caec1)
Same as on desktop.
**Info**
24.11.1 4cc822b
