### ISSUE TITLE
Unused input props drilled to DOM

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#15398]
1. Open console
2. Go to send form

Caused by https://github.com/trezor/trezor-suite/commit/f7cb5caeff7a028655ac58f52a46012fc4a23008

![Screenshot 2024-11-14 at 16 40 31](https://github.com/user-attachments/assets/0a102e38-59c3-406b-a8ff-2ced3a9b89ef)
![Screenshot 2024-11-14 at 16 30 51](https://github.com/user-attachments/assets/da55bbdf-85af-4a6d-9371-df3028b28b9a)
![Screenshot 2024-11-14 at 16 30 59](https://github.com/user-attachments/assets/a3e1e129-685e-4609-a769-21e9f187a72c)
![Screenshot 2024-11-14 at 16 31 10](https://github.com/user-attachments/assets/d36e14a1-7d60-4e0e-92f9-c0d22ff66136)
![Screenshot 2024-11-14 at 16 31 24](https://github.com/user-attachments/assets/e25512e6-a005-4b03-91f5-19d91e3d77b4)
![Screenshot 2024-11-14 at 16 31 31](https://github.com/user-attachments/assets/74a81314-f012-42f5-9676-d4f86dbdd37b)
![Screenshot 2024-11-14 at 16 31 38](https://github.com/user-attachments/assets/6ae6312a-4f44-46e3-84c5-328ad55a8cc5)

**Comment by mroz22** [comment]
also unit tests are full of this.. https://github.com/trezor/trezor-suite/actions/runs/11855306674/job/33039425918?pr=15338#step:5:1116
