### ISSUE TITLE
Send coins - Advanced address validation

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#15403]
The desktop has some more advance send address input validation checks that haven't bee implemented in the mobile yet. See these: [deprecated, firmware and uppercase](https://github.com/trezor/trezor-suite/blob/98eb80e33960a8838f89802a703d3fe97ef5a0a5/packages/suite/src/views/wallet/send/Outputs/Address.tsx#L213-L241) checks.

Also go through [this list](https://github.com/trezor/trezor-suite/blob/9f1f76b994dc1fbc486adbcb46f61c106bc0c394/docs/packages/suite/send.md) and check if there  is no other validation missing.

## Acceptance criteria
All the validation used in desktop apply also for mobile.

**Comment by STew790** [comment]
**QA OK**
Validations for address are same as on desktop.

**Info**
24.11.3 https://github.com/trezor/trezor-suite/commit/f6fa667886f5abd1d4e68d8f38121bd934fec405
