### ISSUE TITLE
Suite shows "Changelog could not be loaded" error after installing update

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#15408]
![image](https://github.com/user-attachments/assets/591d0050-40a1-44fe-af0a-f4ffe59ba6e3)

How to replicate: 

https://github.com/user-attachments/assets/c333c979-4000-49a7-98df-0a771a5586e7

**Comment by bosomt** [comment]
**QA OK**

clicked on `just been updated and seen this`

![Image](https://github.com/user-attachments/assets/4abd6760-4dba-4d43-bcc2-fb25bde91e11)

**Info:**
 - Suite version: desktop 24.11.2 (80088650b0a123e29b0e38f340bda504bb9c4334)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.2 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
