### ISSUE TITLE
There is no character limit in label field "Device Label"

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1541]
Issue for **T1**

You can enter any kind of device name to field "Device Label" and
it ends with **Error: string overflow**

see https://www.youtube.com/watch?v=nWse87VVfTg&feature=youtu.be

Issue for **TT**

You can enter and change device name to really long name

![image](https://user-images.githubusercontent.com/31506317/79251691-c852ba80-7e80-11ea-861f-0519254c2977.png)

**Comment by mroz22** [comment]
Mytrezor has 16 I believe

**Comment by bosomt** [comment]
works fine, 
maybe add some info about character limit but I think it's obvious anyway
