### ISSUE TITLE
Static notification inconsistencies

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1542]
![image](https://user-images.githubusercontent.com/30367552/79269013-0a3d2a00-7e9c-11ea-89a7-b6d89608f5e1.png)

- different cta
- shouldnt there be only one at time?

**Comment by vladimirvolek** [comment]
related https://github.com/trezor/trezor-suite/issues/1488 and https://github.com/trezor/trezor-suite/issues/1400

**Comment by glacierbits** [comment]
To be solved by #1632 and #1636
