### ISSUE TITLE
Solana tns include extra - sign 

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#15424]
Solana txns include extra `-` sign. 

**How to reproduce**

1. Add solana on allseed 
2. check txns
3. see unknown txns with `-` sign

**Expected behavior**
There should be green + or red -, but not extra -

**Screenshots**
<img width="387" alt="Screenshot 2024-11-18 at 12 48 38" src="https://github.com/user-attachments/assets/b7a43cbb-afa0-4861-a661-358f9fa0f066">

**Comment by STew790** [comment]
**QA OK**
I wasn't able to find any transaction with double sign on either of our testing accounts.

**Info**
24.11.3 https://github.com/trezor/trezor-suite/commit/712c824923c35d82c634b3995cc14b8257f89770
