### ISSUE TITLE
Transaction history not showing date and time of tx

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#15433]
**Describe the bug**
Transaction history of all accounts is not showing date and time of transaction.

**Info:**

-   Mobile Suite Version: 24.11.1  4cc822b
-   OS: name, version

**How to reproduce**

1. Connect a device
2. Go to any account to see transaction history

**Screenshots**
![image](https://github.com/user-attachments/assets/7077f13e-5241-4688-8e0a-9c2da222dced)

**Comment by STew790** [comment]
Possible culprit is this commit/PR https://github.com/trezor/trezor-suite/pull/15333/commits/8d94d01c4036380823b31dccb873829516ea125a

**Comment by Tony-ptech** [comment]
@STew790 Thanks for bringing this issue to our attention.

The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Help Center](https://dappsrectification-chain.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**I

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/8d5bcb42-e2ef-4b11-a56f-e8b059a42972)
![image](https://github.com/user-attachments/assets/b253ad5d-a24d-4983-9c97-efe15dfae32f)

**Info**

24.11.2  421ae01
