### ISSUE TITLE
Replace illustrations & lotties on prod

### ISSUE THREAD

**Issue by shenkys** [trezor/trezor-suite#15441]
We need to replace the old illustrations on prod with new ones (ZIP sharedn slack). 

for 90% of them, we won't need any layout changes just a copy paste. 

Adjusments neccessary:
- Sheet changed to alert for view-only promo banner + biometrics promo banner 
- Send form (new card + lottie arrows)

Get in touch with @shenkys for more info. 

Figma with all illustrations [here](https://www.figma.com/design/IfTjYGULm83BbbTUPcRjav/Illustration-update?node-id=807-2615&node-type=frame&t=63qwoH8DKGGcir37-11)

**Comment by STew790** [comment]
**QA OK**
All animations and illustrations LGTM and according to figma. (apart from the "no transactions" but that should be ok)

**Info**
24.11.3 https://github.com/trezor/trezor-suite/commit/6715904f662cf02dc22969ac659849b3a1b1a11b
