### ISSUE TITLE
Disabled Choose Device/Wallet Modal

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#1546]
**Issue: Clicking on Settings disables wallet options.** 

**Steps to reproduce**
**1.** Cet into Settings 
**2.** Open the uppermost icon on the left, the Choose Device/Wallet Modal.

**Actual**
Getting into Settings and then opening the Choose Device/Wallet Modal will result in disabled Choose Wallet options. The only available option is to Choose Device, if there are more than one connected. 
See video: https://drive.google.com/file/d/1ATxeGLMllkTSpz2ukOaKBGqTSLdhlSmJ/view

**Expected**
To be able as a user to change wallet, even when in Settings.

**Comment by glacierbits** [comment]
Related to #1108. Product decision & design needed.

**Comment by glacierbits** [comment]
As discussed with @szymonlesisz, the content of the "Switch Wallets" modal will remain to be the same (i.e. actions enabled as opposed to disabled in the current version) even when access from the Settings. Click to discover or add wallet will send the user to Dashboard.
