### ISSUE TITLE
Passphrase flow is missing URL to the Knowledge Base

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#15466]
**Describe the bug**
Passphrase entry flow is missing URL to the Knowledge Base

**Info:**

-   Suite Version: 24.10

**How to reproduce**

1. Have a Trezor connected and unlocked, initialized device, so you can se the dashboard or some account.
2. Open wallet switcher in the upper left corner
3. Click the [+ passphrase wallet] button
4. Observe the first "It's important to first learn how a passphrase works" bullet point, it's missing a URL to the Knowledge Base

**Expected behavior**
The "It's important to first learn how a passphrase works" text should have a URL on the "learn how a passphrase works" part of the text (it should be underscored and have a hover effect like any other text URL)

It should link to: https://trezor.io/learn/a/passphrases-and-hidden-wallets

**Screenshots**
![Image](https://github.com/user-attachments/assets/c7aead22-2035-4995-85dc-02de601741bc)

**Additional context**

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.12.0 (4258d1c3c5bfcc405e73e48ea633f0bdf62f4d80)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport
