### ISSUE TITLE
Account details boxes

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1547]
2 overlapping boxes

<img width="1006" alt="Screen Shot 2020-04-15 at 10 54 10" src="https://user-images.githubusercontent.com/29627086/79318615-80c34180-7f07-11ea-8c0d-a8d5521461e6.png">

**Comment by vladimirvolek** [comment]
Use the latest develop please :p 

![image](https://user-images.githubusercontent.com/3112191/79319881-3642c480-7f09-11ea-81ef-6cef0e4a67a3.png)
