### ISSUE TITLE
Replace alert icons on prod

### ISSUE THREAD

**Issue by shenkys** [trezor/trezor-suite#15487]
We need to replace the old status icons in the app. 

Let's create a component with 4 states: 
- success
- info
- warning
- critical

Once we have that, let's replace all the status icons in screens, alert, sheets, etc. for respective new icons.

We're keeping the background shape + inner asset separated and the inner asset is interchangeable for any icon in our library.

Use standardized size for all, specced in figma.

112x112px parent shape
40px inner shape (only exception is the "success" symbol that's been custom handdrawn and can't be fitted in such small shape

Figma with all illustrations [here](https://www.figma.com/design/IfTjYGULm83BbbTUPcRjav/Illustration-update?node-id=807-2615&node-type=frame&t=63qwoH8DKGGcir37-11)

**Comment by STew790** [comment]
**QA OK**
Alert icons replaced correctly.

**Info**
24.12.1 https://github.com/trezor/trezor-suite/commit/4e6ac6aa71591d2e354fd6851e4e5761564a5b79
