### ISSUE TITLE
Send Solana + Tokens

### ISSUE THREAD

**Issue by vytick** [trezor/trezor-suite#15497]
- [x] Validate recipient address
- [x] fetch fee
- [x] send Solana
- [x] send Tokens
- [x] error state when txn times out or is marked as failed
- [x] send max

**Comment by STew790** [comment]
**QA OK**
- validation address OK
- fee fetched correctly
- SOL sent multiple times with confirmed txs
- tokens on SOL sent as well
- error state ok (ish, will follow up with an issue)
![image](https://github.com/user-attachments/assets/c7fa1c19-8bb0-4941-9290-8762bd6f7317)
- send max also ok

**Info**
24.12.1 4e6ac6a
