### ISSUE TITLE
Discard barrel index files inside of packages

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#15494]
I see index files as API of the package. However we are using them inside packages as well. Good example of this is the `packages/suite/src/components/suite/index.tsx`. 

Main problem here is, that it can create circular dependency and then the import need to be direct anyway. As an example, it happened [here in this PR](https://github.com/trezor/trezor-suite/pull/15465/files#diff-fdb0dab76967e4865b07a44267b2d23fec0c414396f506b3ef685d3ec784ff9eR8).

**Comment by Nodonisko** [comment]
This was already decided many years ago that we want to get rid of it, but no one did the necessary work since then :D

https://www.notion.so/satoshilabs/Code-Improvements-1-Code-style-changes-0f1bb44d86764715b8f5962c7f23466e
