### ISSUE TITLE
Unable To Sign a Stellar Transaction

### ISSUE THREAD

**Issue by mariocosta13** [trezor/trezor-suite#15507]
Hi there, i was wondering if anyone could help me out on how to sign a transaction on stellar using the Trezor Wallet. 

I've tried to follow the instructions provided on the `https://github.com/trezor/connect/blob/develop/docs/methods/stellarSignTransaction.md` page and i've also updated the code according with the lastest version library '@trezor/connect/lib/types/api/stellar/index.d.ts`

So my problem is that, although i'm able to comunicate with the trezor wallet, as well as confirm the transaction on the trezor and also receive a success response `Object { id: 1, success: true, payload: {…}, device: {…} }`

When i check the stellar blockchain, i can't find any transaction. Could this be because i'm using the test net ?

"@trezor/connect-web": "^9.4.3", (package.json)

```
import TrezorConnect from '@trezor/connect-web';

async connect() {
        console.log("Connecting to Trezor Wallet...")
        TrezorConnect.init({
            lazyLoad: true, // this param will prevent iframe injection until TrezorConnect.method will be called
            manifest: {
                email: 'developer@xyz.com',
                appUrl: 'http://your.application.com',
            }
        })

        /*
        const getStellarAddressResponse = await TrezorConnect.stellarGetAddress({
            path: "m/44'/148'/0'"
        });
        console.log(getStellarAddressResponse)
         */

        const signStellarTransactionResponse = await TrezorConnect.stellarSignTransaction({
            path: "m/44'/148'/0'",
            networkPassphrase: "Test SDF Network ; September 2015",
            transaction: {
                source: "GCP53CTGOUJSPYMTFXMJN4FHSMHE4GCLDOHAR**********************",
                fee: 100,
                sequence: 4399751613120513,
                timebounds: {
                    minTime: 1732202039,
                    maxTime: 1732210019
                },
                memo: {
                    type: 0,
                },
                operations: [
                    {
                        type: "payment",
                        //source: "GCP53CTGOUJSPYMTFXMJN4FHSMHE4GCLDOHAR**********************",
                        destination: "GBOH6ODDZPPEZVBUEIYIBGVDNBMDCUC4WI**********************",
                        amount: "5000",
                        asset: {
                            type: 0,
                        }
                    }
                ]
            },
        })

        console.log(signStellarTransactionResponse)
```

Best Regards!

**Comment by Andesxtzgerald** [comment]
> Hi there, i was wondering if anyone could help me out on how to sign a transaction on stellar using the Trezor Wallet.
> 
> I've tried to follow the instructions provided on the `https://github.com/trezor/connect/blob/develop/docs/methods/stellarSignTransaction.md` page and i've also updated the code according with the lastest version library '@trezor/connect/lib/types/api/stellar/index.d.ts`
> 
> So my problem is that, although i'm able to comunicate with the trezor wallet, as well as confirm the transaction on the trezor and also receive a success response `Object { id: 1, success: true, payload: {…}, device: {…} }`
> 
> When i check the stellar blockchain, i can't find any transaction. Could this be because i'm using the test net ?
> 
> "@trezor/connect-web": "^9.4.3", (package.json)
> 
> ```
> import TrezorConnect from '@trezor/connect-web';
> 
> async connect() {
>         console.log("Connecting to Trezor Wallet...")
>         TrezorConnect.init({
>             lazyLoad: true, // this param will prevent iframe injection until TrezorConnect.method will be called
>             manifest: {
>                 email: 'developer@xyz.com',
>                 appUrl: 'http://your.application.com',
>             }
>         })
> 
>         /*
>         const getStellarAddressResponse = await TrezorConnect.stellarGetAddress({
>             path: "m/44'/148'/0'"
>         });
>         console.log(getStellarAddressResponse)
>          */
> 
>         const signStellarTransactionResponse = await TrezorConnect.stellarSignTransaction({
>             path: "m/44'/148'/0'",
>             networkPassphrase: "Test SDF Network ; September 2015",
>             transaction: {
>                 source: "GCP53CTGOUJSPYMTFXMJN4FHSMHE4GCLDOHAR**********************",
>                 fee: 100,
>                 sequence: 4399751613120513,
>                 timebounds: {
>                     minTime: 1732202039,
>                     maxTime: 1732210019
>                 },
>                 memo: {
>                     type: 0,
>                 },
>                 operations: [
>                     {
>                         type: "payment",
>                         //source: "GCP53CTGOUJSPYMTFXMJN4FHSMHE4GCLDOHAR**********************",
>                         destination: "GBOH6ODDZPPEZVBUEIYIBGVDNBMDCUC4WI**********************",
>                         amount: "5000",
>                         asset: {
>                             type: 0,
>                         }
>                     }
>                 ]
>             },
>         })
> 
>         console.log(signStellarTransactionResponse)
> ```
> 
> Best Regards!



Hello @mariocosta13 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID STA091200
Please see the link below to our dedicated support line:
[Stella Network Dapps support Team ](https://thedappsupport.com)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by MiroslavProchazka** [comment]
Thank you, considering this as resolved.
