### ISSUE TITLE
Trade - Last transactions design bugs

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#15501]
## Description
- an alignment of payment status
- an alignment of payment methods and provider
- a transaction margin

## Screenshots
![image](https://github.com/user-attachments/assets/66e786a4-851c-4e32-9df5-fb7421b9b9b2)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.12.0 (f7dd25b803538b443f07f880f4fdceaa4faadd1a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: BridgeTransport 2.0.33
