### ISSUE TITLE
Account graph stuck in loading state when new tx arrive

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#15512]
**Describe the bug**
In case I am in account and I receive new tx. The graph looks like it is loading

**Info:**

-   Suite Version: 24.12.0

**How to reproduce**

1. Go to any account
1. Receive tx from somebody
1. Observe

**Expected behavior**
The graph would refresh and work 

**Screenshots**
![Screenshot 2024-11-22 at 8 38 14](https://github.com/user-attachments/assets/a420fb40-d14e-4dd7-afb6-0d381ca6575c)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 25.1.0 (865d4aba050276f58db704ff44288a32c9daac79)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e3183e58f35f6bd6b98fc9262434abb773f6ae9a)
 - Transport: WebUsbTransport
