### ISSUE TITLE
Fix app icon and splashscreen after Expo update

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#15523]
Followup for https://github.com/trezor/trezor-suite/pull/15383, not in production.

App icon and splash screen is supposed to stay the same as it is on production, but the logo is somewhat smaller in app icon and splash screen is missing.

ICON
<img src="https://github.com/user-attachments/assets/c5bfe6da-6b7a-448a-9cab-f7bcebc1d606" width="300" >

splashscreen ORIGINAL
<img src="https://github.com/user-attachments/assets/6d78e0de-7f7b-4753-8f47-e375d2fa41b6" width="300" >

splashscreen AFTER UPDATE
<img src="https://github.com/user-attachments/assets/9f7064df-9ec3-4438-ac68-4d4e48a5329e" width="300" >

**Comment by Nodonisko** [comment]
We need to use new expo-splash plugin

**Comment by matejkriz** [comment]
> We need to use new expo-splash plugin

Yeah, it looks like this issue https://github.com/expo/expo/issues/32515 fixed here https://github.com/expo/expo/issues/33138, but testing `expo-splash-screen@0.29.13` and it still looks the same 🤔

**Comment by matejkriz** [comment]
The doc is not very clear for the new config of splash screen via plugin https://github.com/expo/expo/issues/32878

**Comment by STew790** [comment]
**QA NOK**
I feel like this was ok a few versions ago but on latest develop its broken again :cry: 
![image](https://github.com/user-attachments/assets/adb9bebd-6114-48fa-8fe5-b8ae7549c343)


**QA OK**
The app icon lgtm
![image](https://github.com/user-attachments/assets/dadb2a0e-dcb7-43b0-990c-95c37e13e349)

**Info**
24.11.3 https://github.com/trezor/trezor-suite/commit/f6fa667886f5abd1d4e68d8f38121bd934fec405 (838)
