### ISSUE TITLE
Broken animation of device switcher

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#15527]
**Describe the bug**
Opening the device switcher is somewhat slower and the animation is not smooth anymore.

**Info:**

-   Mobile Suite Version: develop, not released on production
-   OS: probably both

**How to reproduce**

1. Go to dashboard
1. Click on Device Switcher

**Expected behavior**
The animation should looks the same as on production

**Screenshots**

https://github.com/user-attachments/assets/25875999-2ee1-413e-983d-bccf5cd7db8d

**Comment by vytick** [comment]
It seems to be something with modals appearing on android 🤔. When appearing they stretch to full screen

<img width=300 src="https://github.com/user-attachments/assets/f1dd4153-e080-4e68-a869-ac6d9f0ad627" />

**Comment by STew790** [comment]
**QA OK**
Animations of device switcher and other modals looks good :+1: 

**Info**
24.11.3  f6fa667

**Comment by STew790** [comment]
**QA NOK**
I was a little "hasty" with this one it seems. The modals in txn detail are a little "jumpy":

https://github.com/user-attachments/assets/bc8a2b9d-4018-4697-a576-cc957132638c
