### ISSUE TITLE
Add new account header

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1553]
<img width="618" alt="Screen Shot 2020-04-15 at 13 13 24" src="https://user-images.githubusercontent.com/29627086/79331100-f08ef780-7f1a-11ea-96f3-41fdaf3f1b4f.png">

**Comment by slowbackspace** [comment]
<img width="995" alt="Screenshot 2020-04-15 at 13 15 26" src="https://user-images.githubusercontent.com/6961901/79331264-2df38500-7f1b-11ea-862f-1d8b8538b315.png">

probably caused by the intl debug mode itself
