### ISSUE TITLE
`device.features` don't update after unsuccessful backup

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#15549]
1. Create a new wallet, skip backup in onboarding.
2. Go to create backup in settings.
3. Cancel the flow.
4. Now you can attempt to create backup again (it will fail), but you shouldn't be offered this option. `device.features.unfinished_backup` should be set to `true` after the action fails, but it only updates after I refresh Suite.

**Comment by bosomt** [comment]
**QA OK**


<img width="1442" alt="Image" src="https://github.com/user-attachments/assets/c940b069-3503-4c55-8400-fccc9efa78fa" />

**Info:**
 - Suite version: web 25.1.0 (f81e70edde076bf7a7890b12a303859e6e2ecc06)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 bitcoin-only (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport
