### ISSUE TITLE
Trading - passphrase modal when trying to swap Bonk to USDC

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#15543]
**Describe the bug**

Passphrase modal when trying to swap Bonk to USDC, im not able to replicate it 💯 but it happened to me once.
Reported here https://www.reddit.com/r/TREZOR/comments/1gz53i2/really_strange/

**Steps to reproduce:**
1. Load wallet with Bonk
2. Try to swap it to USDC
3. Observe passphrase modal

**Info:**
 - Suite version: desktop 24.11.3 (71f9b21d21c9b033e34fc8c6d33ffd8223ffda73)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.3 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/user-attachments/assets/16fd9477-60bf-4b83-bd55-913db46c27b3)
![image](https://github.com/user-attachments/assets/b1dfe8d9-1afd-451d-870c-081d50e40000)

**Comment by STew790** [comment]
**QA OK**
Fixed by PR here https://github.com/trezor/trezor-suite/pull/15545
