### ISSUE TITLE
Trading - Support for full KYC swaps

### ISSUE THREAD

**Issue by marek-andrsk** [trezor/trezor-suite#15556]
Due to regulations (especially in UK) we need to be ready for Full KYC Swap flow.

Full KYC Flow for Swaps:
- when full-KYC offer is selected, user proceeds to first step of swap as normally (i.e. select and verify receive address)
- after the receive address is verified, user is redirected to Invity or partner's web to log in/provide KYC info
- when successful a token is securely stored on Invity or partner's backend
- user is redirected back to Suite to finish transaction (i.e. send crypto for swap)
- for any subsequent swaps we no longer need to redirect user to KYC widget, token will be used to execute trade on behalf of user

Screens TBA

**Comment by bosomt** [comment]
**QA OK**

swap tested on dev version on MoonPay sandbox with KYC
