### ISSUE TITLE
Set 16px padding as default for Screen components

### ISSUE THREAD

**Issue by yanascz** [trezor/trezor-suite#15553]
Currently, 8px are used as default but it is overridden on many screens already.

All `Screen*` components shall be revised and updated accordingly.

**Comment by STew790** [comment]
**QA OK**
LGTM 

![Image](https://github.com/user-attachments/assets/ab4815c3-bae2-475d-b047-b6898892cd6c)

![Image](https://github.com/user-attachments/assets/79096997-9eac-436d-8d1e-0547f5237926)

![Image](https://github.com/user-attachments/assets/5a05b158-b00a-4d0a-a5dd-908b91dfe950)

**Info**
25.1.2 https://github.com/trezor/trezor-suite/commit/995410aa85fd67087647a56ac29d5f0d34b6097e
