### ISSUE TITLE
Onboarding - Inconsistent progress bar

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#1555]
![image](https://user-images.githubusercontent.com/3112191/79336020-4b2c5180-7f23-11ea-8889-4ee21c749868.png)
![image](https://user-images.githubusercontent.com/3112191/79336033-4ebfd880-7f23-11ea-8e03-353397edf966.png)

**Comment by mroz22** [comment]
If I get it right, the inconsistency was different paddings from left and right? If yes, this appears to be already fixed as a side effect of another PR, probably slowbackspace update of modals, so closing it now. Feel free to reopen if I get it wrong.

**Comment by wendys-cats** [comment]
**Issue:** Inconsistency with progress bar persists

**Expected**
Loading of the progress bar will be consistent (same length) with each step.

**Actual**
Incosistency persists - as seen on video
video: https://drive.google.com/file/d/1jtu8J1uH4XUGY2N61P_UIpAbnjEPhMsp/view

**Comment by mroz22** [comment]
well, this is hard to achieve. total number of steps is changing under the hood - depending on users choices. maybe we could do some finetuning, but unless product decides this is really important, I would leave it as it is.

at the very begginig of the video: you chose used device, which means you skip hologram step. again, I could rearange it to make hologram a "substep" of new/used devicce selection or something like this.. but doing this in Q2 is fine I belive
