### ISSUE TITLE
Align app download banners to the right

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#15575]
<img width="1458" alt="Screenshot 2024-11-26 at 10 44 59" src="https://github.com/user-attachments/assets/6c77abca-7b09-4e81-84a3-29f7656ecdb6">

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/7abeaaee-ef1d-4425-84de-8b451edb54d1)

Links work correctly as well. (love the hover with QR code on those)

**Info:**
 - Suite version: web 24.12.0 (8869ea943a7f8770a85980dfc752f99ce33f7d70)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.5 regular (revision a61e783448043760a7c925e017bd08a4673a61c8)
 - Transport: BridgeTransport 2.0.33
