### ISSUE TITLE
Sidebar - Add token search

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#15585]
**Describe the bug**
Add search among  tokens.
I often need/want to send some token and i dont know account where its stored.
Especially when its hidden/0 fiat vaule/ token i have to go thru account/token till i find it

**Steps to reproduce:**
1. Load accounts with token
2. Try to localise token via search

**Info:**
 - Suite version: web 24.12.0 (fb0a013bd89e71f3cb30ab7c1f395996c345aa91)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport

**Screenshots:**
<img width="412" alt="Screenshot 2024-11-26 at 16 29 09" src="https://github.com/user-attachments/assets/8fbb7e7d-c2c7-410e-befd-61df3f0e671a">
<img width="408" alt="Screenshot 2024-11-26 at 16 28 33" src="https://github.com/user-attachments/assets/ef4d6831-cc7c-4b4e-82cd-b8a16c0b2795">

**Comment by tomasklim** [comment]
token name, token symbol, token contract address

**Comment by bosomt** [comment]
**QA OK**

all 3 token ids found via search /tested on 3 ETH and POL tokens/
```
LPT
Livepeer
0x58b6A8A3302369DAEc383334672404Ee733aB239
```

**Info:**
 - Suite version: web 25.1.0 (280c7d1328e2a9cd02ca9d5adbaef4ab5064c25f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 3.0.0-bundled.24.12.2
