### ISSUE TITLE
Custom fee is ignored when bumping transaction

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#15598]
**Describe the bug**
Custom fee is ignored when bumping TX
See screenshots, even i set custom fee its ignored and normal fee is used.
Tested on BTC and TEST
See 5. screenshot there is `Reduce from` present but when you select it it fails

**Steps to reproduce:**
1. Send tx
2. Bump tx with custom fee
3. 

**Info:**
 - Suite version: web 24.12.0 (5dca0c378d98ae387d53dda29d782a671b67182f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: WebUsbTransport

**Screenshots:**
<img width="781" alt="Screenshot 2024-11-27 at 11 38 28" src="https://github.com/user-attachments/assets/1edac3f6-c429-4566-8b98-faabc65ff5d4">
<img width="719" alt="Screenshot 2024-11-27 at 11 38 46" src="https://github.com/user-attachments/assets/b93a1b99-e1a0-4209-9ea5-776213173bff">
<img width="772" alt="Screenshot 2024-11-27 at 11 39 18" src="https://github.com/user-attachments/assets/05954030-6459-4b5a-b53f-cf122a0d5299">
<img width="700" alt="Screenshot 2024-11-27 at 11 39 26" src="https://github.com/user-attachments/assets/b1383c3b-8805-452c-8faa-c789635e12b3">

<img width="789" alt="image" src="https://github.com/user-attachments/assets/27d382ed-432a-4e2f-a266-081230dcca95">

**Comment by SmithDEVV** [comment]
@bosomt Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a 💬.

**Comment by bosomt** [comment]
**QA NOK**

- bump button is never active 🚫 
- bump is available for every transaction, even confirmed or received

<img width="761" alt="Image" src="https://github.com/user-attachments/assets/07e05d6b-a1e8-4afb-bc0f-b88ff4e0a49a" />
<img width="774" alt="Image" src="https://github.com/user-attachments/assets/c786de06-18e2-4bf5-812d-b450c8201014" />

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 25.1.0 (adb2ff4bb90b9221a26ce7cc8c4f9e6317e675db)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e196413bb745443610211c325623ba7cee7309e9)
 - Transport: BridgeTransport 3.0.0-bundled.24.12.3
