### ISSUE TITLE
Fresh address is still hidden after it's confirmed in one address account type.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1559]
Fresh address is still hidden after it's confirmed in one address account type
See screenshot. In multi address account you can see that address.
But in XRP,ETH,ETC you have to repeat confirm process if you haven't copied it.

![image](https://user-images.githubusercontent.com/31506317/79340769-1d4b0b00-7f2b-11ea-9b27-57be0634b623.png)

**Comment by slowbackspace** [comment]
should be fixed by https://github.com/trezor/trezor-suite/pull/1551

**Comment by bosomt** [comment]
@slowbackspace any idea why there is STOP sign when you move cursor over address ?
it's been there for long time

![image](https://user-images.githubusercontent.com/31506317/80457781-27f49f80-8930-11ea-9104-d2bf65551722.png)
