### ISSUE TITLE
Primary Menu: Notifications + Settings 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1560]
- [ ] They are slightly more white than the ground grey layer.

<img width="471" alt="Screen Shot 2020-04-15 at 16 27 37" src="https://user-images.githubusercontent.com/29627086/79349087-242b4b00-7f36-11ea-9d20-74f94e195afe.png">

- [ ] Notifications header

<img width="216" alt="Screen Shot 2020-04-15 at 16 29 58" src="https://user-images.githubusercontent.com/29627086/79349294-5b99f780-7f36-11ea-9770-43669707c9bf.png">

- [ ] Notifications box padding seems too small compare to the rest of the app

<img width="184" alt="Screen Shot 2020-04-15 at 16 30 30" src="https://user-images.githubusercontent.com/29627086/79349388-6eacc780-7f36-11ea-9e77-65a0490dd69f.png">

**Comment by slowbackspace** [comment]
ad 1) as designed
