### ISSUE TITLE
Prepare feature flag for Solana in message-system

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#15613]
Add possibility to unhide/hide SOL in app via message-system same as we already have via feature flag in Dev menu. 

For that, we have to fix our global handling of feature flags from message system so that only killswitch open full screen blocking modal.

**Comment by matejkriz** [comment]
Notes for QA (@STew790 ): please make sure that Send is available for all available coins except Cardano in release candidate 🙏

**Comment by STew790** [comment]
**QA OK**
Tested and reported here https://github.com/trezor/trezor-suite/pull/15700
