### ISSUE TITLE
Block Model One 1.6.1 upgrade with wipe seed requirement

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#15630]
Users one FW 1.6.1 on Model One will have storage [wiped](https://satoshilabs.slack.com/archives/CL1D61PQF/p1731572548668689?thread_ts=1731572475.561249&cid=CL1D61PQF) and will require a full recovery.

Inspired by Safe series devices, migrating between vendors informs of a necessary wipe.

### Screen 1/2
![Image](https://github.com/user-attachments/assets/0d192edc-0d51-45ae-b60a-a717c9f4db97)

### Screen 2/2
1:1 copy of the safe 3/5 vendor type change
![Image](https://github.com/user-attachments/assets/7141919e-2bd5-4dd8-8d6a-6978b591f6d1)

**Comment by evgenysl** [comment]
Tested on branch at https://github.com/trezor/trezor-suite/pull/15698#issuecomment-2514186327

**Comment by evgenysl** [comment]
**QA OK**
<img width="1292" alt="Screenshot 2024-12-03 at 15 12 56" src="https://github.com/user-attachments/assets/46d30639-d781-4ca1-9c5c-8e6e542384f9">
<img width="1402" alt="Screenshot 2024-12-03 at 15 13 17" src="https://github.com/user-attachments/assets/43c3f7f4-d8bc-42a2-bc13-7903c03d9807">
<img width="1402" alt="Screenshot 2024-12-03 at 15 13 42" src="https://github.com/user-attachments/assets/b15a9f3b-af6b-4c15-ad90-214ee3a9b1f2">
<img width="1358" alt="Screenshot 2024-12-03 at 15 17 25" src="https://github.com/user-attachments/assets/04af13c8-47de-49f2-b092-0bd512661441">
