### ISSUE TITLE
Tokens tab re-renders on each click

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#15637]
https://github.com/user-attachments/assets/6b7b56cb-ee7e-4cc2-a005-5b2b4e8cf402

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.12.0 (f43af85636fa7911c692fe274cd0726a74138726)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: BridgeTransport 2.0.33
