### ISSUE TITLE
User cannot send Solana because we set low fees

### ISSUE THREAD

**Issue by jirih-stsh** [trezor/trezor-suite#15641]
**Describe the bug**
Users are sometimes not able to send Solana transactions and have to try repeatedly. 
This is most most likely happens when fees on the network are high, because we are setting a very low hardcoded minimum fee

User report: https://www.reddit.com/r/TREZOR/comments/1h138m4/comment/lzazrln/

> Sometimes when i try to send my USDC to another wallet i encounter this
> error:
> TransactionExpiredBlockheightExceededError: Signature
> sometimes I have to wait like 20 minutes and try to send again later in hopes it will work or spam it a lot until it goes through. I also read it could be because of network congestion and trezor putting the lowest fees possible
> 

**How to reproduce**

1. Go to Solana account, when the average network fees are high
2. Try to send some tokens
3. The transaction might fail because of fees and you get: `TransactionExpiredBlockheightExceededError: Signature`

**Expected behavior**
The transaction does not fail, is approved, and user is able to send tokens on first try

**Comment by bosomt** [comment]
**QA OK**

sent txs, i noticed higher fee /0.000005162 SOL and 0.002055085 SOL/

https://solscan.io/tx/4FuGrfiZc5CgAxAsL65CMckKAy8LRqaN2NM9ph4shvFHbWh5EHw3EcYP6JdHak7EyM34cdmoWCde8pPGkdd5y29S

https://solscan.io/tx/5msJHbaV6UB8aujCGyByDjGoF1yaUcdNsthsBz6FuZEnUq8crAe3Gk7RmykqPgbttppt7CKzAratdqW9CynZvGvA

**Info:**
 - Suite version: desktop 24.12.0 (ba5174eb1c7fc19b376c089ec56e843bbbf8d437)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: BridgeTransport 2.0.33
