### ISSUE TITLE
Custom backend modal "Add new" button is touching the text field above it

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#15658]
**Describe the bug**
In the backend modal of coins, in the "Custom blockbook server" the "Add new" button is touching the text field above it.

**Steps to reproduce:**
1. Navigate to backend of any coin
2. Switch to "Custom blockbook server"
3. Observe

**Info:**
 - Suite version: web 24.12.0 (8869ea943a7f8770a85980dfc752f99ce33f7d70)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/user-attachments/assets/4536f7f2-1c2b-4861-8732-b7c213419528)

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/0f3abb5a-0664-4c6c-8145-72dfa410d36e)

**Info:**
 - Suite version: desktop 24.12.0 (f7dd25b803538b443f07f880f4fdceaa4faadd1a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: BridgeTransport 2.0.33
