### ISSUE TITLE
Suite reports needs backup even backup already failed after cancelled in app

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#15662]
**Describe the bug**
Suite reports needs backup even backup already failed after cancelled in app

**Steps to reproduce:**
1. Device is in needs backup state
2. Start backup and cancel it 
3. Suite still reports needs backup but device already reports backup failed
4. After you start backup again it correctly reports that backup is already done and failed

**Info:**
 - Suite version: desktop 24.12.0 (16cbfef4d484a16875027b80e99d07577eb09626)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/user-attachments/assets/3bcf749e-84f0-4fd6-a1fc-2ee7fc42ce63

**Comment by mroz22** [comment]
related? #15549

**Comment by komret** [comment]
Yes, this is duplicate, closing.
