### ISSUE TITLE
Don't show text helper text in collapsed sidebar

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#15685]
<img width="293" alt="Screenshot 2024-12-02 at 15 07 17" src="https://github.com/user-attachments/assets/0ef4a6f3-cd47-42c4-aea9-101b19f2961b">

**Comment by bosomt** [comment]
**QA OK**

After collapsing sidebar i dont see text that is present after and before showing full sidebar

**Info:**
 - Suite version: desktop 24.12.0 (f7dd25b803538b443f07f880f4fdceaa4faadd1a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: BridgeTransport 2.0.33
