### ISSUE TITLE
Show expanded device section when switch modal is open

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#15682]
**Screenshots**

**collapsed sidebar**

<img width="311" alt="image" src="https://github.com/user-attachments/assets/3bbfd104-28d8-428e-8781-364bcb7b46b9">

<img width="1800" alt="Screenshot 2024-12-02 at 15 00 04" src="https://github.com/user-attachments/assets/0d4b6e42-9a84-4a4d-acd8-3c2b81fc88a0">

expanded sidebar:

<img width="311" alt="image" src="https://github.com/user-attachments/assets/b01c6f3d-6885-46f7-92cf-0eeacf5cceb0">

<img width="458" alt="image" src="https://github.com/user-attachments/assets/571d6b87-2e93-4721-8b0c-f57546adec72">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.12.0 (f7dd25b803538b443f07f880f4fdceaa4faadd1a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: BridgeTransport 2.0.33
