### ISSUE TITLE
Misaligned Activity in collapsed menu

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#15732]
<img width="613" alt="image" src="https://github.com/user-attachments/assets/75b43021-059e-465d-84fa-675b06eb23d5">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 25.1.0 (cda066acdbd850067d18325297e1db7aee4ed735)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: WebUsbTransport
