### ISSUE TITLE
Hide `what's new` in collapsed sidebar

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#15755]
<img width="168" alt="image" src="https://github.com/user-attachments/assets/4cfd895a-f4b4-4908-a05a-9de096b3d5bb">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 25.1.0 (b6003e816a7807a9edaf29955cbdab370cec3632)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.5 regular (revision a61e783448043760a7c925e017bd08a4673a61c8)
 - Transport: BridgeTransport 2.0.33
