### ISSUE TITLE
Implement "cancel" action in modals

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1576]
new trezord (2.0.29?) will allow us to "cancel" actions on display (like address validation, confirmation, etc..)
- [ ] Implement cancel action in modals (trezor-connect)
- [ ] Add new bridge to desktop build

Product:
Decide how to deal with older bridge (it will not work)

**Comment by glacierbits** [comment]
@szymonlesisz is this still relevant?

**Comment by szymonlesisz** [comment]
yes it should be possible now, like in "send" modal

**Comment by dahaca** [comment]
Design of the abort button from Ondra:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/45338719/162212215-94bb4dc0-979f-465a-a786-65f9115d15f5.png">
