### ISSUE TITLE
Fiat rates for coins not loading in some cases, leaving only skeletons

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#15768]
**Describe the bug**
For me this is happening basically all the time now but for someone this just doesn't happen, so I can't really have any repro steps but for some reason, fiat rates are just not loading for me on accounts. I can see fiat on the dashboard but not in the accounts part. I can see only skeletons there

**Info:**

-   Mobile Suite Version: develop only (production is OK for me)
-   OS: Android

**Screenshots**
![image](https://github.com/user-attachments/assets/543a1e8b-f569-4e59-98b4-122305c1232e)

**Comment by Nodonisko** [comment]
fixed in #15815

**Comment by STew790** [comment]
**QA OK**
Fiat rates are loading normally for me :muscle: 

**Info**
24.11.3 f6fa667
