### ISSUE TITLE
Use format markings for text in Stake ETH modal

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#15763]
<img width="587" alt="Screenshot 2024-12-04 at 12 38 57" src="https://github.com/user-attachments/assets/094cac2b-c58b-41e4-960f-11cc34035623">

**Comment by jvaclavik** [comment]
Fixed already

**Comment by bosomt** [comment]
**QA OK**

<img width="607" alt="image" src="https://github.com/user-attachments/assets/3350a320-a73a-4468-a8b1-441790f58d64">

**Info:**
 - Suite version: web 25.1.0 (a552ac45e894db3cf8ab9dab49a040b3c98f7132)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: BridgeTransport 2.0.33
