### ISSUE TITLE
Data Analytics: New desktop OS tracking

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#15770]
We would like to add new parameters to event [suite-ready](https://www.notion.so/satoshilabs/suite-ready-1e5cbba0a1a545edb437185c37ddafdc?pvs=4) to correctly track OS name and version for desktop, especially for mac. The new method is described [here](https://www.notion.so/satoshilabs/New-operating-system-tracking-for-desktop-152dc526060680eaaeb3d89162d69a4e)  in Notion. There should be 3 new parameters:

- `desktopOsVersion` (from release)
- `desktopOsName` (from platform)
- `desktopOsArchitecture` (from architecture)

**Comment by bosomt** [comment]
**QA OK**

```
desktopOsVersion=24.1.0&desktopOsName=darwin&desktopOsArchitecture=arm64
```

in sent https://data.trezor.io/suite/log/desktop/


**Info:**
 - Suite version: desktop 25.1.0 (0b116799334cb4a05fcb59cc480deb7c4b9a63e9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e196413bb745443610211c325623ba7cee7309e9)
 - Transport: BridgeTransport 2.0.33
