### ISSUE TITLE
Bump priority of FW upgrades on seedless Trezor onboardings

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#15779]
Seedless Trezor w/ old firmware has little reason to maintain old FW. Exceptions:
* Custom FW
* Users holding on to FW to support deprecated coins

### Solution
Introduce modal deflecting the skip update interaction. Emulating the 'Skip PIN' and 'Skip Backup' interactions.

### Copy+Design

![Image](https://github.com/user-attachments/assets/72cda38e-657d-49ff-b668-5ebe1d42c2ea)

### Concept
Skip backup interaction informs user that it best practise to get the latest security features. 

![Image](https://github.com/user-attachments/assets/0b113786-1035-47aa-bd93-d05ecee10d23)

**Comment by bosomt** [comment]
**QA OK**

https://github.com/trezor/trezor-suite/pull/15805#issuecomment-2531270503
