### ISSUE TITLE
Upload homescreen background kills the app (in NixOS KDE)

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#1578]
**WHERE:** Desktop application Suite, nixos version 1.0.0

**Expected:**
User can upload custom homescreen background for both devices. 

**Actual:**
For T1 device - this option is disabled (both for desktop app and for browser version). @matejzak is this intentional? 
For T2 - trying to upload custom homescreen will kill the desktop application. (works fine in browser version).

**Comment by bosomt** [comment]
Works fine with latest app /released yesterday at 13:30/

Nixos, app, TT 2.3.0

**Comment by bosomt** [comment]
broken in KDE
works OK in GNOME

_GLib-GIO-ERROR **: 11:01:08.818: No GSettings schemas are installed on the system_

**Comment by bosomt** [comment]
Installed latest **KUBUNTU** with **KDE** interface
and it works fine, no error in cli interface, background is loaded properly

**Comment by tsusanka** [comment]
As per https://github.com/trezor/trezor-suite/issues/1578#issuecomment-615123172 and https://github.com/trezor/trezor-suite/issues/1578#issuecomment-626633946, this seems fixed. Please reopen if I am mistaken!
