### ISSUE TITLE
unable to update Suite 24.11.3

### ISSUE THREAD

**Issue by JonnyGnosis** [trezor/trezor-suite#15809]
when going to update suite on my laptop I click > get the latest version > Download > Update and restart but it just logs in and says "update available" (Trezor safe 5 connected to laptop) 
```[tasklist]
### Tasks
```

**Comment by JonnyGnosis** [comment]
my back end is disconnected as well and I am unable to connect it and send crypto

**Comment by MiroslavProchazka** [comment]
Hello, 

which version are you currently on? 

Thx

**Comment by JonnyGnosis** [comment]
24.10.1 as of now. does my VPN need to be disconnected?

**Comment by MiroslavProchazka** [comment]
Hey, 

I would advise you to: 
- turn off VPN 
- leave Early Access program (if applicable)
- turn off Tor

Let me know if that helps, 
Thank you

**Comment by JonnyGnosis** [comment]
I will try that thank you - Jonathan RobbinsOn Dec 10, 2024, at 04:01, Prochmi99 ***@***.***> wrote:﻿
Hey,
I would advise you to:

turn off VPN
leave Early Access program (if applicable)
turn off Tor

Let me know if that helps,
Thank you

**Comment by JonnyGnosis** [comment]
it still did not work, what does "leave Early Access program (if applicable)" mean

**Comment by MiroslavProchazka** [comment]
In settings - Application there is a section Experimental -> Early Access Program
<img width="1399" alt="image" src="https://github.com/user-attachments/assets/2f10e8e5-4b3b-4c4e-9cfa-7f52c1207783" />

**Comment by JonnyGnosis** [comment]
is it ok to not update? I tried no vpn, no tor, and I was not even in the group. I joined then left and it still does not work

**Comment by MiroslavProchazka** [comment]
Hey, sure! Please try it in a month or two, it is always better to use up to date product. 
In case you will run into similar issue next time, you can always download latest version on our official website - https://trezor.io/trezor-suite. 

Please do not google the link as there are lot scams pretending to be the official versions.
