### ISSUE TITLE
Do migration of BNB Smart Chain from `BNB` to `BSC` network symbol

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#15818]
Inspiration https://github.com/trezor/trezor-suite/pull/14093
but `BNB` display symbol, `BSC` symbol

**Comment by vytick** [comment]
@STew790 
Please on mobile, test mainly, that accounts of remembered devices and Portfolio tracker undergo correctly migration and app works as before. All BNB accounts with transaction should remain there. 

test: 
1. get app version before this was merged
2. discover BNB and set wallet to view only (or use portfolio tracker for this)
3. upgrade to version after this was merged
4. app should work as before with all BNB accounts still present

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 25.1.0 (102be08a4eddf031a463e2907f96a9d45d9d748f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.7 regular (revision 8a254aa8eae82f99630df63f40e4d290066a3efc)
 - Transport: WebUsbTransport

**Comment by STew790** [comment]
**QA OK**
BNB working same as before.
- receive address
- send transaction
- assets

**Info**
25.1.2 30b62f5
