### ISSUE TITLE
Add Arbitrum under debug mode

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#15817]
https://blockbook-dev.corp.sldev.cz:9306/

Inspiration 

https://github.com/trezor/trezor-suite/pull/15513
https://github.com/trezor/trezor-suite/pull/15510

**Comment by bosomt** [comment]
**QA OK**

- discovery
- receive
- send ARB
- send TOKEN
- tx detail
- explorer link

**Info:**
 - Suite version: desktop 25.1.0 (20a35a51ea92edb7ffa42c696f6da297c66d2971)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
