### ISSUE TITLE
Incosistent margin/padding in main menu

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1581]
Clicking between settings > dashboard makes main menu jumpy

**Comment by glacierbits** [comment]
When selected, Dashboard moves down, Wallet moves up.  

![Screen-Recording-2020-04-18-at-00 34 52](https://user-images.githubusercontent.com/29627086/79619225-9b1a3c80-810c-11ea-8064-9951887ee859.gif)
