### ISSUE TITLE
Make trading work with L2s

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#15821]
![Screenshot 2024-12-07 at 14 12 48](https://github.com/user-attachments/assets/307a14e0-d935-46c6-8e2d-0c8719738649)
![Screenshot 2024-12-07 at 14 13 54](https://github.com/user-attachments/assets/cf0b9421-b562-4f05-a20e-5e37eebfc5ee)

Check that it works, add `Base` to the modal as quick filter

**Comment by bosomt** [comment]
**QA OK**

<img width="401" alt="Image" src="https://github.com/user-attachments/assets/34f369e9-49f9-4c76-b5a1-5541717367f4" />

**Info:**
 - Suite version: web 25.1.0 (98b2554adacdfeef932c69e5442db4e00def44f9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.7 regular (revision 8a254aa8eae82f99630df63f40e4d290066a3efc)
 - Transport: WebUsbTransport
