### ISSUE TITLE
Primary menu width should be the same on mobile and desktop.

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#1586]
Reduce the width of this menu.

![image](https://user-images.githubusercontent.com/3112191/79471704-3921e000-8003-11ea-8046-8c4a5d01cf10.png)

**Comment by szymonlesisz** [comment]
width is ok, but buttons should be aligned differently, there where a design for that but it's gone from zeplin @matejzak

**Comment by glacierbits** [comment]
Menu(s) to be found here: **[Zeplin](https://app.zeplin.io/project/5e844ed9a790d06f246726c1/styleguide/components?seid=5e845005948fea6d454b768b)**
