### ISSUE TITLE
Discreet mode does not hide some sensitive stuff

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#1587]
The discreet mode does not hide (blur) the following:

- [x] coin balances in the account menu
- [x] addresses in the transaction history
- [x] history chart in the dashboard
- [x] history chart in the transaction history
- [x] the number of transactions in the transaction history (maybe this one is not so sensitive, IDK)

**Comment by prusnak** [comment]
4 out of 5 points are not fixed, reopening

**Comment by prusnak** [comment]
adding two more:

- [x] addresses in Transaction details dialog
- [x] transaction ID in the Transaction details dialog

**Comment by vladimirvolek** [comment]
Current develop looks good to me - https://suite.corp.sldev.cz/suite-web/develop/

dashboard chart

![image](https://user-images.githubusercontent.com/3112191/81003644-78499100-8e4b-11ea-9ec8-a909ee67e23c.png)

Transactions

![image](https://user-images.githubusercontent.com/3112191/81004020-07ef3f80-8e4c-11ea-995c-1759481d0593.png)

![image](https://user-images.githubusercontent.com/3112191/81004013-058ce580-8e4c-11ea-985e-6a96a57adab1.png)


![image](https://user-images.githubusercontent.com/3112191/81003704-8f887e80-8e4b-11ea-84c1-07cc49a5cc68.png)

transaction detail

![image](https://user-images.githubusercontent.com/3112191/81003740-a333e500-8e4b-11ea-9d79-0fc9651b8954.png)

![image](https://user-images.githubusercontent.com/3112191/81003765-aa5af300-8e4b-11ea-96d0-4c0da0553249.png)

**Comment by prusnak** [comment]
I was testing that with Desktop Suite from 03-May.

I confirm this works with the latest develop (04-May-2020 16:00)

Thanks!

**Comment by bosomt** [comment]
testing 

- [x] coin balances in the account menu
- [x] addresses in the transaction history
- [x] history chart in the dashboard
- [x] history chart in the transaction history
- [x] the number of transactions in the transaction history (maybe this one is not so sensitive, IDK)
- [x]  addresses in Transaction details dialog
- [x]  transaction ID in the Transaction details dialog
