### ISSUE TITLE
Use basescan, optimisticscan, arbiscan for L2s

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#15896]

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 25.1.0 (7a58c5c948d4b964ba1120b7deb871b608d46411)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e3183e58f35f6bd6b98fc9262434abb773f6ae9a)
 - Transport: WebUsbTransport
