### ISSUE TITLE
Device settings not showing after clicking on it

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#1590]
Issue: When you are in Wallet and you have selected anything else than Bitcoin and you want to go to Device>Device settings it will just show you the BTC balance in Wallet.

Expected: Clicking on Device>Device settings should take you to Device settings

Nixos Gnome, Suite desktop and web, TT

![settings](https://user-images.githubusercontent.com/48477147/79554915-10e7bf00-809f-11ea-986c-52026f070fc5.gif)

**Comment by bosomt** [comment]
same here /nixos app + web suite at sldev/

**Comment by bosomt** [comment]
works fine in latest app and web suite
@STew790 please confirm if possible
