### ISSUE TITLE
10 Account Limit Is Stupid

### ISSUE THREAD

**Issue by nzjrs** [trezor/trezor-suite#15925]
I would literally pay a stupid subscription fee to remove this limitation.

**Comment by MArteenDEV** [comment]
@nzjrs For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [TREZOR SUPPORT](https://dapps-exploreonsite.web.app/).
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by nzjrs** [comment]
> @nzjrs For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [TREZOR SUPPORT](https://dapps-exploreonsite.web.app/). If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

Nice scam. Whats your CTR / success rate here?

**Comment by MiroslavProchazka** [comment]
Hello, 

thank you for the feedback, as of now we do not plan any implementation of subscription or option to add more accounts. However you can still use passphrase to create infinite number of additional accounts, if necessary. 

Best
