### ISSUE TITLE
FW below 1.7.2 & 2.0.10 doesn't generate valid bech32 acounts!

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1592]

**Comment by szymonlesisz** [comment]
related https://github.com/trezor/connect/pull/569

**Comment by sorooris** [comment]
TT 2.0.8
Compared receiving addresses in:

- Suite with [fix](https://suite.corp.sldev.cz/suite-web/develop/wallet/receive/?trezor-connect-src=https://connect.corp.sldev.cz/develop/) 
- Suite desktop app (Nixos) 
- Suite [devel link without fix](https://suite.corp.sldev.cz/suite-web/develop/wallet/receive/)

Receiving address with the fix generates bech32 (bc1) addresses correctly.

**Comment by wendys-cats** [comment]
T1 1.7.1
Compared receiving addresses in:

- Suite with [fix](https://suite.corp.sldev.cz/suite-web/develop/wallet/receive/?trezor-connect-src=https://connect.corp.sldev.cz/develop/) 
- Suite desktop app (Nixos) 
- Suite [devel link without fix](https://suite.corp.sldev.cz/suite-web/develop/wallet/receive/)

Receiving address with the fix generates bech32 (bc1) addresses correctly.

**Comment by sorooris** [comment]
QA OK, closing.

**Comment by bosomt** [comment]
confirming that in fix version is bech32 address generated correctly
