### ISSUE TITLE
Balance out of balance

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1593]
Spotted on 1440 x 900 

<img width="1265" alt="Screen Shot 2020-04-18 at 00 39 38" src="https://user-images.githubusercontent.com/29627086/79619439-272c6400-810d-11ea-932d-7230fcdf4d47.png">

**Comment by vladimirvolek** [comment]
Cannot reproduce in the develop branch.

**Comment by glacierbits** [comment]
I still see the "Balance" is way too on the left on various resolutions.

![Screen Shot 2020-05-07 at 13 46 16](https://user-images.githubusercontent.com/29627086/81291080-74935580-9069-11ea-91d6-eec9168b3047.png)
![Screen Shot 2020-05-07 at 13 46 03](https://user-images.githubusercontent.com/29627086/81291084-75c48280-9069-11ea-8001-8965761237d8.png)

**Comment by slowbackspace** [comment]
@matejzak it's just that your balance is too small, buy more bitcoin and it will get fixed! 😁 

edit: nope, that's still is not enough. you have to spent more to be rewarded with proper alignment!

**Comment by glacierbits** [comment]
..this one ain't happy either to be fair. 😬  @slowbackspace 

![Screen Shot 2020-05-07 at 14 08 57](https://user-images.githubusercontent.com/29627086/81292664-4bc08f80-906c-11ea-9c65-73afa121e742.png)
