### ISSUE TITLE
Trading - endless pending state of trade for specific swap flow

### ISSUE THREAD

**Issue by FreeWall** [trezor/trezor-suite#15941]
### Describe the bug
For swap providers with KYC step required that don't generate a send address immediately and require some time for address to be generated, the user may end up stuck on endless pending state page after transaction is sent.
This happens only for newly added provider (Moonpay) for users already completed KYC step before (swap flow 2 described below).
Temporarly, we can fix this by adjusting configuration on invity backend to skip **swap flow 2** and force user to always be redirected to KYC gateway, from where he is immediately redirected back to suite in case he has already completed the KYC step before.

**Swap flow 1:** (working fine)
(required KYC step **not** done before)
1. Select offer in trade section KYC step required
2. Confirm receive transaction
3. Redirected to provider's KYC gateway (& complete KYC process if not done)
4. Redirected back to suite, wait for send address to be generated
5. Send transaction
6. Transaction done after a while

**Swap flow 2:** (endless pending state)
(required KYC step already done)
1. Select offer in trade section KYC step required
2. Confirm receive transaction
3. Wait for send address to be generated
4. Send transaction
6. Transaction done after a while (but UI is stuck in pending state)

### Info
-   Suite Version: v24.12.1

**Screenshots**

![image](https://github.com/user-attachments/assets/73ffa8eb-ac35-46c3-bfbf-ce76e07d5212)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 25.1.0 (9055e1ea2bdc3ec8fb3e97eaee863a3286635418)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e196413bb745443610211c325623ba7cee7309e9)
 - Transport: BridgeTransport 2.0.33
