### ISSUE TITLE
Sidebar re-renders very often

### ISSUE THREAD

**Issue by enjojoy** [trezor/trezor-suite#15943]
**Describe the bug**
Sidebar rerenders suspiciously often

**How to reproduce**

To see the rerenders:
- Inspect
- Command + Shift + P, look for Rendering
- Check the "Paint flashing" option

**Expected behavior**
Sidebar doesn't rerender unless the content changes

**Screenshots**

https://github.com/user-attachments/assets/39ace1b9-d3a1-4330-87bd-42f8e52fa0df

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 25.1.0 (560819f1efea315160cb274f07134910ddbb1560)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
