### ISSUE TITLE
Lables added to addresses in Send form are not added to the transaction history after sending

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#15953]
**Describe the bug**
When I add a label to a transaction, it is not shown in the tx history:
What I entered:
![image](https://github.com/user-attachments/assets/9cc0ce85-4014-43f1-8061-c4c2c1921666)
vs what is in tx history (don't mind the nonsense, its the name of the labeled account):
![image](https://github.com/user-attachments/assets/308dda62-45dc-4462-884d-43073c371174)

This all also applies for importing transactions with labels from CSV.

**Info:**
 - Suite version: desktop 24.12.1 (37b23d87f1678af93935deb93c9251a232bb2763)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.12.1 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
When I add label to transaction that I wanna broadcast, it also appears in the transaction history.

**Comment by komret** [comment]
Potentially related: https://github.com/trezor/trezor-suite/issues/13862

**Comment by bosomt** [comment]
**QA OK**

<img width="745" alt="Image" src="https://github.com/user-attachments/assets/e525c4fb-3828-4a2a-aa34-f7ed329387eb" />
<img width="1178" alt="Image" src="https://github.com/user-attachments/assets/83260597-744e-4a95-9426-587f26558a88" />

**Info:**
 - Suite version: web 25.1.0 (f81e70edde076bf7a7890b12a303859e6e2ecc06)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport
