### ISSUE TITLE
MetaMask - RPC Error: Error: Loading chunk 191 failed.

### ISSUE THREAD

**Issue by psimoesbits** [trezor/trezor-suite#15954]
### Bug Report

**Describe the bug**  
When using Trezor Connect in combination with MetaMask, the following error occurs: 

```
MetaMask - RPC Error: Error: Loading chunk 191 failed. 
(error: https://connect.trezor.io/9/js/ethereum-api.6f7e1f0b5b6c1c0663b8.js) 
```

The issue appears to be related to a failed loading of a JavaScript chunk (`chunk 191`) from the Trezor Connect URL. This prevents successful interaction between MetaMask and the Trezor hardware wallet, causing transaction processing and approvals to fail.  

**To Reproduce**  
1. Open MetaMask and set up a Trezor hardware wallet connection.
2. Attempt to sign a transaction or interact with a dApp using the wallet.
3. Observe the error in the MetaMask extension or browser console.

**Expected behavior**  
The Trezor Connect integration should load all necessary resources and allow the user to sign transactions without errors.

**Error Details**  
- **Error Code**: -32603  
- **Error Message**:  
  ```
  Error: Loading chunk 191 failed.
  (error: https://connect.trezor.io/9/js/ethereum-api.6f7e1f0b5b6c1c0663b8.js)
  ```  
- **Stack Trace**:  
  ```
  Error: Error: Loading chunk 191 failed.
  (error: https://connect.trezor.io/9/js/ethereum-api.6f7e1f0b5b6c1c0663b8.js)
      at new o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:162455)
      ...
  ```

**Environment**  
- **MetaMask Version**: MetaMask Version12.9.1 (latest) 
- **Trezor Suite**: `24.11.3`  
- **Browser**: Google Chrome
- **Operating System**: Windows 10 22H2

**Workarounds Tried**  
- Clearing browser cache and reloading MetaMask and Trezor. 

Please investigate the loading of `chunk 191` from Trezor Connect's resources and ensure compatibility with MetaMask.

**Comment by MartinSeeler** [comment]
+1

**Comment by mroz22** [comment]
Hi guys, I just tested and it works for me (some basic interaction with MM and Trezor). Are you still experiencing it? There was a release roughly at the time of you report so it might be related to that. Not all resources updated at the same time or maybe insufficient cache invalidation..

**Comment by MartinSeeler** [comment]
Just tested it again and indeed, the error is gone for me.

**Comment by psimoesbits** [comment]
I don't have any transactions to make at this moment in Metamask and with Trezor, but if you say that it tested and is fine, then we can consider it solved.

That chunk issue really seems to be just a deployment-related issue.

**Comment by mroz22** [comment]
@Hannsek we should fine-tune the deployment process a bit. At the moment we do to much copying instead of simply solving it somewhere on the Cloudflare layer.

**Comment by psimoesbits** [comment]
Precisely: the more automated, the better.
