### ISSUE TITLE
Replace checkAddressCheckSum from web3-utils to web3-validator

### ISSUE THREAD

**Issue by enjojoy** [trezor/trezor-suite#15989]
![Screenshot 2024-12-16 at 16 56 48](https://github.com/user-attachments/assets/b240539a-6ab6-4a27-bad1-8edae7800623)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 25.1.0 (adb2ff4bb90b9221a26ce7cc8c4f9e6317e675db)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport
