### ISSUE TITLE
Add wallet in Choose Wallet/Device Modal is not working

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#1600]
**Where:** Suite app nixos version 20-Apr-2020 11:26 
**Steps to reproduce:**
**1.** Open suite, plug in initialized device with disabled passphrase (only standard wallet)
**2.** Open Choose Device/Wallet modal
**3.** Click on the Add wallet button

**Expected:**
Add wallet button will prompt the device to enable passphrase encryption.
**Actual:**
Nothing happens.

**Note:** Feature works fine in browser version, this is app ONLY bug.

**Video:** https://drive.google.com/file/d/1J7vM456QTL8XdcG0CvrgyKrOTD__tVgc/view

**Comment by szymonlesisz** [comment]
is it still an issue?

**Comment by wendys-cats** [comment]
Checked app and web version, the issue has been solved.
