### ISSUE TITLE
Passphrase encryption enabling/disabling broken after wipe

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#1601]
**Where:** browser version, nixos app version (20-Apr-2020 11:26)

**Steps to reproduce:**
**1.** Connect trezor device with suite and wipe it (tested with 2.1.0, 2.3.0 and 1.9.0, with both passphrase enabled and disabled)
**2.** Restore a wallet or create new wallet
**3.** go into Device Settings and turn passphrase encryption on.

**Expected:**
To be able to change passphrase encryption settings

**Actual:**
Suite will respond with "Error: Passphrase is incorrect". Most likely related to device id changing after wipe. 

**videos:**
1 https://drive.google.com/file/d/1VM_6E1Gp1FfoDukOmsl7meWdkpUyF20c/view (0:34-1:28 is wallet recovery, can skip)
2. https://drive.google.com/file/d/1wvLiP6OFUcD8iU56cAN1iIRpr3oVswpl/view (0:26-1:15 is wallet recovery, can skip)

**Comment by mroz22** [comment]
transport please, is it webusb or bridge?

**Comment by wendys-cats** [comment]
@mroz22 bridge.

**Comment by tsusanka** [comment]
@wendys-cats could you retest this one please? It's quite old but sounds dubious

**Comment by wendys-cats** [comment]
@tsusanka bug is no longer present in current release (tried on 21.1.0 9ae82af375cea195a84fec664b387c461b2df1ae version). 
Also tried on internal alfa release cca9bfe8173e0912715ac6599799ebbd2cc9f5fb with 1.9.0. (could replicate it) and with 1.9.3 (could not replicate).

**Comment by tsusanka** [comment]
Thanks, closing then.
