### ISSUE TITLE
`customBackends` can be called just `backendTypes` or `backends`

### ISSUE THREAD

**Issue by enjojoy** [trezor/trezor-suite#16034]

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 25.1.0 (7daeb57b631e7e306bc3282476941420944bfeda)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.1.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3B1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
