### ISSUE TITLE
Trading - sell amount doesn't match

### ISSUE THREAD

**Issue by FreeWall** [trezor/trezor-suite#16046]
**Describe the bug**
There is a bug on Trezor suite - coinmarket section. When the user wants to sell all amount of crypto with Banxa, the amount sent to sell is a little bit different than the amount from the order. Therefore Banxa requests to pay the difference.
In the real example from our investigation there was a difference between 0.00128288 BTC amount sent and 0.00128273 BTC order amount - therefore the transaction is declined for amounts dismatch.

**Info:**
Suite version: web 24.11.3

![image](https://github.com/user-attachments/assets/7525b9f8-0b12-4123-a34e-61c207eff920)
![image](https://github.com/user-attachments/assets/ea97ac01-f766-4836-9cee-a562d54569d3)

**Comment by Hushg2** [comment]
Hello @FreeWall  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by bosomt** [comment]
**QA OK**

im not able to replicate on Banxa or other providers

**Info:**
 - Suite version: web 25.1.0 (9ac3a89b70218adffb67915a1276c28b80490fb8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision a8e5d471fe35164cbf2529a2c0042ca465f6f159)
 - Transport: WebUsbTransport
