### ISSUE TITLE
Move L2s to experimental features

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#16084]
Base, Arbitrum One, Optimism under 1 experimental feature toggle

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 25.1.0 (adb2ff4bb90b9221a26ce7cc8c4f9e6317e675db)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e196413bb745443610211c325623ba7cee7309e9)
 - Transport: BridgeTransport 3.0.0-bundled.24.12.3
