### ISSUE TITLE
Connect Explorer minor issues

### ISSUE THREAD

**Issue by martykan** [trezor/trezor-suite#16097]
1. BNB icon missing

<img width="302" alt="Screenshot 2024-12-23 at 09 56 05" src="https://github.com/user-attachments/assets/9b1e3a2d-48c6-4534-944e-b8d1cc5cebfb" />

2. Negative margin in method tester cropping out content

<img width="300" alt="Screenshot 2024-12-23 at 09 57 32" src="https://github.com/user-attachments/assets/708c7645-d5b7-4b4d-a3f5-8562037ea06c" />

3. Re-render when manually editing select value in JSON (for example in getCoinInfo)

**Comment by evgenysl** [comment]
See icon, method testing tool looks good.
QA OK
