### ISSUE TITLE
Trading - allowed to add account not available in Suite

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#16115]
**Describe the bug**

- Suite allows to add accounts which does not exist in Suite app

**Info:**

-   Suite Version: 24.10.1

**How to reproduce**

1. Buy XLM

**Screenshots**
![Screenshot 2024-12-29 at 12 39 31](https://github.com/user-attachments/assets/33afc7d5-7783-49d3-b871-e0c0e5273c89)

**Comment by bosomt** [comment]
**QA OK**

checked on MONERO,XLM and VeChain

<img width="726" alt="Image" src="https://github.com/user-attachments/assets/6b9db479-bc0a-4f18-b176-a512a7de7bfe" />


**Info:**
 - Suite version: web 25.1.0 (7a58c5c948d4b964ba1120b7deb871b608d46411)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision e3183e58f35f6bd6b98fc9262434abb773f6ae9a)
 - Transport: WebUsbTransport
