### ISSUE TITLE
firmware update bugs

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1611]
firmware update happy paths are generally implemented, just check if any of these are solved:

- [ ] https://github.com/trezor/trezor-suite/issues/1110#issuecomment-610890299
- [ ] https://github.com/trezor/trezor-suite/issues/1110#issuecomment-610888206
- [ ] https://github.com/trezor/trezor-suite/issues/1110#issuecomment-610839211
- [ ] https://github.com/trezor/trezor-suite/issues/392#issuecomment-597585631 probably webusb related
- [ ] #1628 fingerprint

**Comment by wendys-cats** [comment]
#1110 tested OK
 #392 probably webusb related, tested OK
 #1628 to be tested separately

**Comment by wendys-cats** [comment]
**Issue:** Missing picture when updating FW for T1

**Steps to reproduce:**
**1.** Connect empty T1 with outdated FW
**2.** Start Onboarding and choose firmware update

**Expected**
FW update for T1 will be the same from Onboarding as from Device Settings.

**Actual**
After reconnecting the device in bootloader mode, the picture for FW update will disappear when updating T1 as a part of Onboarding process. This does not happen when updating from Device Settings.

**video T1 Onboarding:** https://drive.google.com/file/d/1FBYFTc3DXz11Tshco7AM_EMzbLiuG9qo/view
**video TT Onboarding:** https://drive.google.com/file/d/1K47_dJLnobJZPXW6sSWjej0N4mesh-_8/view
**video T1 Device Settings:** https://drive.google.com/file/d/1gNvN0Mo79x3C895jWCTb9ji2bRo9X5Tb/view
