### ISSUE TITLE
add possibility to use "new line" in Translations

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1620]

**Comment by slowbackspace** [comment]
I looked into it and according to this https://github.com/formatjs/react-intl/issues/401#issuecomment-482269459 it should work out of the box

**Comment by szymonlesisz** [comment]
not working :/
![Screenshot 2020-04-28 at 17 04 52](https://user-images.githubusercontent.com/3435913/80503623-6d39c100-8972-11ea-967a-c1b1f79838aa.png)

**Comment by slowbackspace** [comment]
I don't get it. It works just fine for me.
<img width="461" alt="Screenshot 2020-05-15 at 08 35 12" src="https://user-images.githubusercontent.com/6961901/82019164-07924800-9687-11ea-8fd8-ddf6217bc9cf.png">
<img width="864" alt="Screenshot 2020-05-15 at 08 34 59" src="https://user-images.githubusercontent.com/6961901/82019168-0a8d3880-9687-11ea-9fec-7ad1cf239abb.png">
<img width="1450" alt="Screenshot 2020-05-15 at 08 34 05" src="https://user-images.githubusercontent.com/6961901/82019180-0eb95600-9687-11ea-89fb-5eb489c1df2e.png">

**Comment by tsusanka** [comment]
I believe this works. Reopen if needed.
