### ISSUE TITLE
Device settings: weird what to do button after failed backup

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1629]
<img width="826" alt="Screenshot 2020-04-24 at 20 00 29" src="https://user-images.githubusercontent.com/6961901/80242821-49bb0180-8666-11ea-9d55-8f766062c4bd.png">

**Comment by mroz22** [comment]
please link current desing for that @matejzak

**Comment by wendys-cats** [comment]
@matejzak @slowbackspace  should there be the external link icon in the button? (there is none in the red alert message about backup fail)
![external link icon in button](https://user-images.githubusercontent.com/58593111/81667245-52238280-9443-11ea-8a65-8f6f218ba406.png)

**Comment by sorooris** [comment]
@matejzak @slowbackspace bump

**Comment by slowbackspace** [comment]
@sorooris I don't think there is a design for these... I gave the button in settings an icon because it leads to external site (wiki). Notification's buttons needs a complete overhaul so I didn't feel like putting an icon there.

**Comment by sorooris** [comment]
@matejzak wat do?
shall we wait for teh design or make a separate issue?

**Comment by glacierbits** [comment]
Note to myself, current version: 

<img width="1313" alt="Screen Shot 2020-05-25 at 10 04 14" src="https://user-images.githubusercontent.com/29627086/82792139-35d60b80-9e6f-11ea-9478-bb81a3afb5eb.png">

To be designed in the next sprint.

**Comment by glacierbits** [comment]
Fixed in #2439
