### ISSUE TITLE
refactor: bridge in onboarding

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1634]
Bridge in onboarding has few problems. In general - in onboarding, there is Pair step where user should establish communication with device. There are multiple possible states:

- no transport
- webusb transport
- bridge transport

our priorities go like this: if there is no transport, use webusb transport if possible, otherwise offer bridge download. In suite, there are 2 places where you may be offered bridge download:
- in onboarding
- standalone, button in connect-device modal

Tasks here:
- [ ] evaulate if we still need `suite/src/views/onboarding/steps/Pair/components/Bridge/index.tsx` can't we use some common bridge component (possibly refactored to become more abstract?) to make it possible to use it on both places (Pair step and standalone bridge view?)
still using class component, 
- [ ] if the aformentioned file is to remain, rewrite it not to use class component but function component instead
- [ ] also check if there is any code that might be shared with standalone bridge view (possibly through common components, utils or hooks)

**Comment by bosomt** [comment]
**QA OK**

both places are offering Bridge download.

<img width="607" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/123438092-a7334100-d5d0-11eb-9e0b-23b901579735.png">

<img width="603" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/123438127-ae5a4f00-d5d0-11eb-9b5b-ea15e3f25e1c.png">


**Info:**
 - Suite version: web 21.7.0 (89aee5512ea0059de309935684b5be5fb3b1843b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model One 1.10.1 regular

**Comment by STew790** [comment]
**QA OK**

Info:
 - Suite version: desktop 21.7.0 (550942dcbdb7b2ffc17519f8307a47f2d8d060f1)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model 1 1.10.1 regular
