### ISSUE TITLE
Web Suite refuses to work in Mint Chromium

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-suite#1643]
user agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/80.0.3987.163 Chrome/80.0.3987.163 Safari/537.36

IIRC this gets misdetected as some other browser, but it should be considered the same as Chrome.

**Comment by bosomt** [comment]
we never experienced this during months of testing Suite in Chromium in Nixos.

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36

Chromium
Version 81.0.4044.113 (Developer Build) (64-bit)

@sorooris can you please confirm ?

**Comment by bosomt** [comment]
@matejcik can you please confirm that it was fixed in latest release of web suite ?

**Comment by matejcik** [comment]
> we never experienced this during months of testing Suite in Chromium in Nixos.

i know! in some discussion we found out that Mint Chromium and Nixos Chromium are detected differently.

> @matejcik can you please confirm that it was fixed in latest release of web suite ?

this currently loads fine for me: https://suite.corp.sldev.cz/suite-web/develop/

**Comment by bosomt** [comment]
tested today on latest Mint and Chromium and it works fine
