### ISSUE TITLE
initialRun in combination with 404

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1645]
![image](https://user-images.githubusercontent.com/30367552/80493489-c4856480-8965-11ea-9722-34818ea8ea98.png)

**Comment by bosomt** [comment]
@mroz22 

is there way to test it ?
i never seen 404 error in suite

**Comment by vladimirvolek** [comment]
@bosomt https://suite.corp.sldev.cz/suite-web/develop/boso123

**Comment by bosomt** [comment]
works fine :)
thanks @vladimirvolek !
