### ISSUE TITLE
Not able to add wallet when entering wallet selector from devise settings page

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1653]
Please see video: https://youtu.be/nyCEIWdtVg4

Same behavior in Chrome and firefox.
You can't load/add wallet when you go to wallet selector from any settings page.

**Comment by glacierbits** [comment]
Duplicity of #1546

**Comment by bosomt** [comment]
@matejzak thank you@ i tied so hard, but i wasn't able to find it ;)
