### ISSUE TITLE
Check seed card - scroll position in settings

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#1658]
Clicking on the link "Check seed from settings" takes you to the bottom of settings.

![image](https://user-images.githubusercontent.com/3112191/80609528-78efbb00-8a38-11ea-8cbc-1734597c9966.png)

![image](https://user-images.githubusercontent.com/3112191/80610058-2b278280-8a39-11ea-843f-2ac54d835966.png)

**Comment by szymonlesisz** [comment]
all pages are affected, looks like nextjs maintain scroll position
https://nextjs.org/docs/api-reference/next/link#disable-scrolling-to-the-top-of-the-page
