### ISSUE TITLE
Add possibility to enable coin from dashboard

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1663]
Currently to add new coin i need to got thru wallet or settings.
It will be nice to enable them straight from dashboard (AddAccount)

**Comment by glacierbits** [comment]
We actually have this option in Design already. I just didn't want to add "new features" to the release. Feel free to add it based on the relative effort (your consideration) @szymonlesisz 

**[Zeplin](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5e79c9bc8b52437106eac048)**

**Comment by szymonlesisz** [comment]
it's already implemented
