### ISSUE TITLE
Send max does not fill the amount in Sending

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#1672]
Clicking on `Send max` in sending dialog says "Amount is empty" even though there is a low amount of coins. My guess is it is below the fee threshold?

Maybe it is a copy thing?

-------

DM me for a mnemonic where this error occurs so you can reproduce it easily.

------

Occurs on current https://suite.corp.sldev.cz/suite-web/develop/wallet/. If it is automatically deployed then 1f12862, but I am not sure how to find the exact revision directly in Suite. In settings there is only "internal alfa release".

Firefox 74.0

**Comment by tsusanka** [comment]
- When selecting lower fee in advanced settings, this indeed works fine.
- Old wallet seems to behave the same way so this is probably just a text thing. Old wallet says "Not enough funds" which seems more accurate. A subtle difference is that in the old wallet the fee is not hidden in the advanced options so it may be less confusing. But I leave that up to you to decide.

**Comment by glacierbits** [comment]
Fixed in Crowdin (copy issue). Thanks @tsusanka !
