### ISSUE TITLE
12 words recovery selectbox is not visible

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#1673]
During the 12-words standard recovery I can choose from a list of words. However, the list is invisible (hidden in scroll bars to be precise) and you can't see what you are typing.

![Peek 2020-04-30 10-02](https://user-images.githubusercontent.com/1835345/80687913-4fcc3a80-8acb-11ea-99c6-bab6381d2c8e.gif)

Also it is not the only place where there are redundant scroll bars:

![Screenshot from 2020-04-30 10-11-02](https://user-images.githubusercontent.com/1835345/80687877-40e58800-8acb-11ea-9cce-94b3c1c76510.png)

------

Occurs on current https://suite.corp.sldev.cz/suite-web/develop/wallet/. If it is automatically deployed then 1f12862.

Firefox 74.0

**Comment by slowbackspace** [comment]
thanks for letting us know! What is size of your viewport and your screen resolution? https://whatismyviewport.com/

**Comment by tsusanka** [comment]
1920 × 954 or at least I hope so that it was _that_ monitor :).

**Comment by bosomt** [comment]
fixed

**Comment by tsusanka** [comment]
Indeed better, but I still see not-so-nice scrollbar on the right:

![Screenshot from 2020-05-05 10-28-44](https://user-images.githubusercontent.com/1835345/81047868-951dad00-8ebb-11ea-835b-b78d1be8d8bc.png)

On current develop, sorry if it is fixed somewhere else or whatnot. cc @slowbackspace

**Comment by slowbackspace** [comment]
> Indeed better, but I still see not-so-nice scrollbar on the right:
> 
> ![Screenshot from 2020-05-05 10-28-44](https://user-images.githubusercontent.com/1835345/81047868-951dad00-8ebb-11ea-835b-b78d1be8d8bc.png)
> 
> On current develop, sorry if it is fixed somewhere else or whatnot. cc @slowbackspace

Thanks for reporting!
Modal component has been completely rewritten, so there might be few places that got forgotten. It is a bit tricky to get right every modal-in-modal (yeaaah, these are really 2 nested modals) combination.

The goal is hiding as many scrollbars as possible, so you really shouldn't see this one. I adjusted the height of the dropdown menu. Should be fine now.  If you see something weird looking again let me know :)

Regarding the ugly scrollbars, what browser do you use? They should look pretty in webkit-like browsers (sorry firefox users, we will get to you later).
edit: Oh, I just figured why you see those, nevermind. I'll fix it :)

**Comment by bosomt** [comment]
testing here https://suite.corp.sldev.cz/suite-web/develop/settings/device/

and it looks OK now, no scrollbar , and im not even in maximized window

![image](https://user-images.githubusercontent.com/31506317/81070610-c3af7e00-8ee3-11ea-8cf6-274c5d26fc99.png)
