### ISSUE TITLE
Not enough space in Download Udev rules dialog

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#1684]
See the screenshot:

![Screenshot from 2020-05-03 13-06-15](https://user-images.githubusercontent.com/42201/80912765-93c77580-8d3f-11ea-8fcb-cd941d75cd46.png)

version: `TrezorSuite-1.0.0.AppImage` generated on `03-May-2020 01:24`

**Comment by bosomt** [comment]
i can confirm that udev modal is too small,
but of course you can scroll down

![image](https://user-images.githubusercontent.com/31506317/80950510-4bb75a00-8df6-11ea-9b55-babb2ae3c550.png)

**Comment by bosomt** [comment]
looks like that's not only one broken modal :)
+ same for loading wallet modal that will disappear after loading of wallet

![image](https://user-images.githubusercontent.com/31506317/80954225-43aee880-8dfd-11ea-97b9-b5dc9e34df22.png)

**Comment by bosomt** [comment]
Full HD full screen

![image](https://user-images.githubusercontent.com/31506317/80954339-7ce75880-8dfd-11ea-816e-bcaace9330e9.png)

**Comment by slowbackspace** [comment]
yup, thanks! for some WEIRD reason it is broken in all modals, but only in electron builds. I am working on the solution. stay tuned! :)

**Comment by bosomt** [comment]
+ im not able open any linked content from suite  that's on web /news, passphrase.../

**Comment by slowbackspace** [comment]
@bosomt could you confirm that the issue is fixed (udev rules and most of other modals should be displayed without scrollbars on decent size screens)?

> * im not able open any linked content from suite  that's on web /news, passphrase.../

I hope it is fixed as side effect  🙏t. iI your are still experiencing this then please open separate issue.

**Comment by bosomt** [comment]
download, enter passphrase and so on modals ok

still broken: 

web links, 
i'm not able to access device/coin settings
passphrase entry makes suite "dark"

**Comment by bosomt** [comment]
fixed , it all works fine
