### ISSUE TITLE
Cannot enter passphrase

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#1685]
The whole screen is dimmed down and the passphrase dialog is inactive:

![Screenshot from 2020-05-03 13-12-07](https://user-images.githubusercontent.com/42201/80912809-020c3800-8d40-11ea-8ae8-80e6a8420523.png)

version: `TrezorSuite-1.0.0.AppImage` generated on `03-May-2020 01:24`

This does not happen with suite-web, most probably because it was pushed to staging before `03 May`.

**Comment by bosomt** [comment]
yes it's broken in latest app build :(

![image](https://user-images.githubusercontent.com/31506317/80951550-68ed2800-8df8-11ea-8c2c-215e0739f34f.png)

**Comment by bosomt** [comment]
works fine in app build from yesterday
