### ISSUE TITLE
Dry run T1 PIN unlock modal broken

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1695]
tested on yesterday linux app
see screenshot

![image](https://user-images.githubusercontent.com/31506317/81044510-c3e45500-8eb4-11ea-96c8-2003e0d029e4.png)

**Comment by mroz22** [comment]
fw 1.9.0 started to report `features.pin_cached: true` even for device that had not pin entered at all.

**Comment by bosomt** [comment]
same behavior with 1.8.3 firmware
