### ISSUE TITLE
Suite doesn't remember fee settings

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1716]
Go to transaction.
Set transaction fee to **low**.
Send transaction.

Try to send another transaction.
You don't even need to leave send dialogue.
Fee is back to **Normal**

In current fees it means that if you want send 2$ in BTC you will pay 5$ fee.

**Comment by glacierbits** [comment]
Related to #1771

**Comment by bosomt** [comment]
**QA OK**

works fine now in a8438ada39fd127f5487bb5cff7c9911748a9562

OS Nixos 
BR Chromium 84.0.4147.135
FW  2.3.3 0d5f00668

**Comment by sorooris** [comment]
**QA OK**
> Wallet Version: web, 20.9.1 cf1f180
OS: NixOS
Browser: any supported (tested Firefox 79.0.1)
Device 1.9.3 0d5f00668
