### ISSUE TITLE
Beta: Landing page

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1721]
Landing page for apps download / web access.

**_URL: beta-wallet.trezor.io/wallet/start.html_**

[**Flow**](https://miro.com/app/board/o9J_kwng2E0=/?moveToWidget=3074457347844932199&cot=6) 

**[Zeplin](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5eb3bf4a5f5cec74855d6168)** 

**[Responsive](https://zpl.io/aB0gJJp)**

Copy to be improved (placeholders for now)

**Comment by bosomt** [comment]
@matejzak can you please send us L/P so we can test it properly ?

**Comment by bosomt** [comment]
![image](https://user-images.githubusercontent.com/31506317/81700779-7003de00-9469-11ea-8c75-fcebf786b2aa.png)

**Comment by glacierbits** [comment]
Text updated.
