### ISSUE TITLE
Consider behavior of Show details button in Sent popup 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1725]
Please consider behavior of Show details button in Sent popup.

When you click on show details it won't show you transaction detail 
but only account transactions and info.
Maybe you can change it to show detail of that transaction ?
See video.

5https://www.youtube.com/watch?v=3g047oOKB0o&feature=youtu.be

**Comment by glacierbits** [comment]
Good point @bosomt! I will add it to the next release.

**Comment by glacierbits** [comment]
FYI will be improved by #2208
