### ISSUE TITLE
Transaction is not showing properly

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1726]
I just sent BCH transaction from account 4 to account 1.
See screenshots
No info in account 4

![image](https://user-images.githubusercontent.com/31506317/81297103-18cdca00-9073-11ea-994a-fcc3e452fb79.png)

![image](https://user-images.githubusercontent.com/31506317/81297052-0d7a9e80-9073-11ea-9b8b-9786b1947395.png)

![image](https://user-images.githubusercontent.com/31506317/81297159-284d1300-9073-11ea-991a-d16233a1b00f.png)

**Comment by bosomt** [comment]
tried ETH transaction and it works fine :)

**Comment by slowbackspace** [comment]
> tried ETH transaction and it works fine :)

what about ripple? could you also try it once again with btc-like coin? (testnet should be enough)

**Comment by bosomt** [comment]
testnet Ripple transactions OK
testnet BTC transactions OK

edit: ZCASH is not working at all, known bug

**Comment by bosomt** [comment]
LTC transaction OK too
