### ISSUE TITLE
tests: debug tests

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1749]
issue to track most common cases of failing tests

most common issue is `Timed out waiting for udp device.` but emulator starts, last logs we have is 
```
trezor.loop DEBUG finish: <generator object 'bootscreen' at 7fd1f1da9100>
trezor.workflow DEBUG start default: <generator object 'homescreen' at 7fd1f1dc4e20>
```

Timeout happens in our utility code working with python trezor

```
def get_udp_device():
    devices = UdpTransport.enumerate()
    for d in devices:
        d.find_debug()
        return d
    raise RuntimeError("No debuggable udp device found")

def wait_for_udp_device():
    start = time.monotonic()
    timeout = 8
    while True:
        try:
            device = get_udp_device()
            return device
        except:
            elapsed = time.monotonic() - start
            if elapsed >= timeout:
                raise RuntimeError("Timed out waiting for udp device.")
            time.sleep(0.05)

```

full code is here: https://github.com/trezor/trezor-suite/blob/develop/docker/trezor-user-env/controller/emulator.py

- Emulator is apparently running, but enumaration fails.
- Bridge is NOT running
- It even sometimes happens on my local machine when I mad-rerun tests (1 in 100 cases maybe)

**Comment by tsusanka** [comment]
@matejcik could you check the code from the trezorlib point of view? I don't see anything that would cause the tests to fail. I see only off-topic stuff like catching a generic exception :).

**Comment by matejcik** [comment]
you could replace the code with:
```python
def wait_for_udp_device():
	d = UdpTransport()
	d.wait_until_ready(timeout=8)
	return d
```
but apart from that I don't see anything wrong with the code either.

The only idea comes to me is that for some reason (local firewall? networking specifics?) the `self.socket.recv(8)` call in `UdpTransport._ping` does not die immediately and instead waits for specified `trezorlib.transport.udp.SOCKET_TIMEOUT` which is `10` by default.

Try one of two things:
(a) stick a `print("PINGING......")` in the while-loop, see how often it spins. With a running emulator, it should only spin once and return.
With an emulator turned off, it should spin frequently.
Perhaps in your problematic case it only spins once and waits futilely.

(b) lower `trezorlib.transport.udp.SOCKET_TIMEOUT` to something like `0.05`, see if it helps with (a) and consequently with the issue

**Comment by tsusanka** [comment]
@mroz22 did this get solved by the new trezor-user-env?

**Comment by mroz22** [comment]
this is imho resolved.
