### ISSUE TITLE
tests: graphic output from docker on mac

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1756]
GUI from docker currently does not work on mac. This means mac people can't debug tests now.

**Comment by tsusanka** [comment]
@slowbackspace I think this could work with the revamp of trezor-user-env, could you try it out now?

**Comment by slowbackspace** [comment]
@tsusanka ohh, I tried few weeks back. I needed to manually set DISPLAY env var (to my mac's local ip) to get it working. But after trying few tests the container started crashing. Then I got distracted and moved to something else. 

I will give it another shot and report back!
