### ISSUE TITLE
Add tooltip to "labeled" addresses

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1757]
In tx history addresses displayed as `sent to myself`, `Account #N` etc.  should have a tooltip with real address inside

**Comment by hynek-jina** [comment]
![Snímek obrazovky 2022-03-08 v 9 33 17](https://user-images.githubusercontent.com/26002916/157198356-08f99def-fdd0-4d71-b45f-3154f26ba333.png)

Address is visible on hover. Send to myself is additional info to same output address.
