### ISSUE TITLE
tests: trezor-user-env in gitlab CI

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1758]
trezor-user-env image is NOT used in trezor-suite gitlab CI now. Instead, python scripts are used directly, but this brings number of issues:
- trezor-user-env image and suite-base image have different chrome version, this makes snapshoting hard
- ...

docker nor docker-compose seem to be available: 
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/598919397

adminkos could enable us use docker in docker like described here: 
https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/#the-solution

**Comment by tsusanka** [comment]
I believe this is solved :).
