### ISSUE TITLE
tests: e2e next level

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1759]
### Improve e2e tests 

- [x] [statistics of tests stability](https://track-suite.herokuapp.com/)
- [ ] documentation of tests and testing strategy
- [ ] marking tests with metadata such as `@headless @electron @firefox @prod` which are used to organize which tests should be ran
- [x] fix occasional crashes https://github.com/trezor/trezor-suite/issues/1749
- [x] gui on mac https://github.com/trezor/trezor-suite/issues/1756
- [x] proper e2e testing with trezor-firmware repozitory in CI
- [ ] mock discovery in tests not testing discovery. this shall speed tests up a lot

**Comment by tsusanka** [comment]
Most of this is done and I believe most of these things should be tackled by the new QA.
