### ISSUE TITLE
Discovery endless loop with invalid passphrase

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1763]
1. create wallet with passphrase
2. remember dvice
3. reconnect device || refresh page
4. add new coin
5. enter invalid passphrase

**Comment by bosomt** [comment]
now it says: **Account discovery error Passphrase is incorrect**

**Comment by bosomt** [comment]
tested in  /suite-web/fix/discovery-loops/notifications/
commit e7ddd48fcd98b69e7ea839359e77cd0ee2c57ba9
with 1.9.1 production version

**Account discovery error Passphrase is incorrect**

**Comment by bosomt** [comment]
same behavior with 1.8.3
i consider it fixed
