### ISSUE TITLE
SendForm: changing device state (disconnected > connected) resets draft tx

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1771]
1. discover account
2. remember wallet
3. disconnect device
4. prepare transaction (address, amount)
5. connect device (whole tx is gone)

**Comment by glacierbits** [comment]
Related to #1716

**Comment by sorooris** [comment]
**QA OK**
> Wallet Version: web, 20.9.1 cf1f180
OS: NixOS
Browser: any supported (tested Firefox 79.0.1)
Device 1.9.3 0d5f00668
