### ISSUE TITLE
Fetch missing txs rates when loading txs from storage

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1772]
It may happen that transaction will be stored without a fiat rate for the transaction's timestamp (fetching could fail for various reasons).
Some logic to refetch missing rates would be nice.

**Comment by slowbackspace** [comment]
IT IS TIME https://github.com/trezor/trezor-suite/issues/3365
this would also mitigate https://github.com/trezor/trezor-suite/issues/3459
this two are probably same issues

**Comment by bosomt** [comment]
@slowbackspace is it possible to replicate this issue to test it between 21.5.1 and 21.6.0 versions or we have to wait and see ? :)

**Comment by sorooris** [comment]
**QA OK**

Transaction rates are fetched correctly.

 web 21.5.1 4d09d884 | app 21.6.1 4f358fd1
 -|-
![image](https://user-images.githubusercontent.com/10185314/121320856-d3329f00-c90d-11eb-8ab4-797e7575c5bd.png) | ![image](https://user-images.githubusercontent.com/10185314/121320805-c7df7380-c90d-11eb-9ff7-7d31fd42edd2.png)

Suite: app 21.6.1 4f358fd1 (compared to web 21.5.1 4d09d884)
Browser: N/A, Chromium 91.0.4472.77 
OS: Win10, NixOS 21.05
Device: model 1 1.10.1
