### ISSUE TITLE
Active app icon jumps to the right

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1780]
![Screen Shot 2020-05-12 at 00 22 13](https://user-images.githubusercontent.com/29627086/81618001-c5e37200-93e6-11ea-9352-445de8048af9.png)

**Comment by vladimirvolek** [comment]
Just fixed in https://github.com/trezor/trezor-suite/commit/5e276b688f34843b2f833e9be95b88827bd423cb.
