### ISSUE TITLE
Not possible to close FW update modal

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1785]
it's not possible to leave firmware update modal when you disconnect empty device.
Even when you have more than one device connected. 

All you can do is to reload suite.
Even reconnect device without firmware won't help you

![image](https://user-images.githubusercontent.com/31506317/81662484-f0ace500-943d-11ea-9e89-45284398a3ca.png)

**Comment by mroz22** [comment]
yes, this a bug. 
firmware upadate modal should switch from cancellable to non-cancellable depending current state of progress.
- If update is not running, it should be cancellable
- If update is running it shoud not be cancellable

**Comment by mroz22** [comment]
Aha, but this is firmware update in onboarding. Not the standalone firmare update. In this case, I am leaving this for product to decide how it should be solved. @matejzak

**Comment by glacierbits** [comment]
I agree the FW update should not be cancellable in the context of Onboarding.
