### ISSUE TITLE
Security steps in Dashboard do not reflect failed backup

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#1787]
**Issue:** Security steps (first one for Device backup) do not reflect failed backup. 

**Expected**
This security step will no longer offer Device backup after the backup has already failed (just like the button in Device Settings does not, for consistency). 

**Actual**
After failed backup, this step does not change, giving the user impression that backup is still possible through Dashboard.

![backup wallet in security](https://user-images.githubusercontent.com/58593111/81668164-88153680-9444-11ea-93b5-586ddb693a0b.png)

**Comment by glacierbits** [comment]
Please add placeholder (to be enhanced via Crowdin):

- header

- description text 

- learn more link

<img width="667" alt="Screen Shot 2020-05-26 at 14 21 38" src="https://user-images.githubusercontent.com/29627086/82900582-11f0f380-9f5d-11ea-8bc6-6e21b71c292c.png">

**Comment by wendys-cats** [comment]
**QA NOK**
**Issue persists** 
Suite: suite.corp.sldev.cz/suite-web/develop/
device: TT 2.3.1 revision: c6b2580cd

**Actual** 
Security steps still offer seed backup after backup has failed. 

**Expected**
This security step will no longer offer Device backup after the backup has already failed (just like the button in Device Settings does not, for consistency).

![image](https://user-images.githubusercontent.com/58593111/84128912-86d62a00-aa41-11ea-9420-dc9917189893.png)

**Comment by mroz22** [comment]
Fix done according to https://github.com/trezor/trezor-suite/issues/1787#issuecomment-633993366 no other design provided. Reassigning this to product

**Comment by wendys-cats** [comment]
@mroz22 adminkos just confirmed that no issues merged on GH since yesterday (16ish) have made it to gitlab, that's why there is no change in develop branch.

**Comment by wendys-cats** [comment]
**QA NOK**
Issue persists
https://staging-wallet.trezor.io/wallet/
device: TT 2.3.1 revision: c6b2580cd

**Actual**
Security steps still offer seed backup after backup has failed.

**Expected**
This security step will no longer offer Device backup after the backup has already failed (just like the button in Device Settings does not, for consistency).

![image](https://user-images.githubusercontent.com/58593111/84266641-1c96b580-ab25-11ea-980b-91ad7da4152a.png)

**Comment by glacierbits** [comment]
Please change the primary "Close" button to "Settings" with link to the Settings > Device. That way it will be consistent with CTA on the failed backup notification (#2240). @mroz22 feel free to pass down this issue to our new colleague Robert (he is to join the team the week after the next). I believe this will be a good first issue.

**Comment by sorooris** [comment]
The issue still persists.

**Comment by glacierbits** [comment]
To be fixed by #3725
