### ISSUE TITLE
XRP transactions are missing in transaction list

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1793]
Please add information that XRP transaction is missing or it dates from some time.
it's really confusing that amount doesn't match  transactions

![image](https://user-images.githubusercontent.com/31506317/81693606-72ae0580-9460-11ea-9b66-eb8e23e54171.png)

**Comment by slowbackspace** [comment]
related to https://github.com/trezor/trezor-suite/issues/1498
I guess we need notification or something to tell users that we don't support xrp backends with full txs history?
@matejzak
