### ISSUE TITLE
Discovery error when you connect BTC only device

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1796]
You can see discovery error when you connect BTC only device.
Proper behavior is probably to disable all coins than BTC

![image](https://user-images.githubusercontent.com/31506317/81781488-7a20ed80-94f8-11ea-8381-bfb004fa248f.png)

![image](https://user-images.githubusercontent.com/31506317/81781517-8311bf00-94f8-11ea-8bd9-ff1e0e81c612.png)

+ video https://www.youtube.com/watch?v=e2ZrBmoVyLA&feature=youtu.be

**Comment by szymonlesisz** [comment]
fixed by https://github.com/trezor/connect/pull/589/commits/d8433eddaf290c8e58cb48090664b7b7dbc3b605 (not released yet)
