### ISSUE TITLE
Enable/disable coin in settings creates multiple instances of backend connection

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1798]
race condition similar to "backend disconnected" issue from the past
tbh. graph actions should not be called from settings
![Screenshot 2020-05-13 at 10 14 28](https://user-images.githubusercontent.com/3435913/81788427-cbce7580-9502-11ea-85ca-f537466c7514.png)

**Comment by slowbackspace** [comment]
afaik graph actions are not triggers on `change-networks` anymore. is this with latest develop? I will try to reproduce it.
