### ISSUE TITLE
FW update: Bootloader illustrations

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1805]
Explanation of how to access the bootloader mode: 

[**Trezor One**](https://zpl.io/aNJPP89 
)

[**Trezor T**](https://zpl.io/25DOOvn)

**Comment by bosomt** [comment]
You’re not invited to this project
:)
both of them

but i will check it ;)

**Comment by bosomt** [comment]
works fine for both models

but:
**Hold left or both buttons while connecting device**
can be confusing for users with older FW than 1.8.0 /one button only works since 1.8.0 or older FW, not sure/
