### ISSUE TITLE
Accessing Suite with google translate mode in Chrome results in crash

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1806]
https://sentry.io/organizations/satoshilabs/issues/1665786919/events/0741ede7c0384c68a64bd76ab181032b/?project=5193825

https://github.com/facebook/react/issues/11538

to reproduce: 
1. set Chrome lang to something else than english
2. allow offer to translate pages that aren't in selected lang (in lang settings)
3. do some clicking around suite while translate mode is activated (completing one of the security card features will do)
4. crash incoming

<img width="413" alt="Screenshot 2020-05-25 at 10 32 04" src="https://user-images.githubusercontent.com/6961901/82794737-42f4f980-9e73-11ea-84d3-76e7669b75fb.png">

**Comment by wendys-cats** [comment]
**Got the error after 2 minutes. Issue still persists.**

**Steps to reproduce:**
**1.** Use chrome auto translate feature
**2.** Connect a device
**3.** Connect a second device and enter the passphrase
**4.** Crash TR

**Video:** https://drive.google.com/file/d/1zjtR-FGi7QzYHW51RLsUzZEs16fwMXEw/view

**Comment by slowbackspace** [comment]
looks like it still happens on /notifications

update: Although I can't reproduce I'll leave the issue open for now.

**Comment by slowbackspace** [comment]
closing this, either it is fine or no one cares enough to report it :)
