### ISSUE TITLE
Receive: clicking on used addrerss during discovery results in error - call in progress

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1807]

**Comment by szymonlesisz** [comment]
dont forget about quick double-click

**Comment by slowbackspace** [comment]
@matejzak it would be nice to have some indication for the user telling him that he can't click on the addres and even nicer let him know the reason why (device is busy), but I guess that is just a small task in bigger UX overhaul.
<img width="656" alt="Screenshot 2020-05-19 at 22 20 33" src="https://user-images.githubusercontent.com/6961901/82374174-f6e32880-9a1e-11ea-882b-9f5d981915ff.png">
