### ISSUE TITLE
Add possibility to clear storage from splash creen

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1813]
It often happens that suite ends in this status: 

![image](https://user-images.githubusercontent.com/31506317/82209747-176f8d80-990e-11ea-8697-70524770c8df.png)

Even after reload/new suite.
Please consider adding clear storage button or something similar to allow access Suite when something goes wrong during loading of device or passphrase.

Right before this I had two devices without possibility of loading or adding wallets.

**Comment by mroz22** [comment]
Maybe add timeout, that unless resolved, will throw an error resulting in ErrorBoundary

**Comment by slowbackspace** [comment]
@bosomt can you reproduce it? It would be nice to know what is causing the issue (besides jumping between various branches with different storage version).

> Maybe add timeout, that unless resolved, will throw an error resulting in ErrorBoundary

that's pretty rough, what about my slow laptop? 😁 I like the idea though. After a timeout we could show some message with btn to report the issue (technically, it could throw a custom error that will be catched in error boundary)
