### ISSUE TITLE
Runtime error in TR_YOUR_CURRENT_VERSION

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1818]
in /settings:
![Screenshot 2020-05-18 at 17 10 59](https://user-images.githubusercontent.com/3435913/82229417-b1ddca00-992a-11ea-8f32-3124dc7ff00d.png)

**Comment by vladimirvolek** [comment]
The `version` variable was removed a week ago.

**Comment by szymonlesisz** [comment]
yet i'm still seeing this error on current develop

**Comment by vladimirvolek** [comment]
> yet i'm still seeing this error on current develop

ok, I will check :)
