### ISSUE TITLE
Passphrase confirmation modal size

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1819]
Steps to reproduce:
1. discover accounts and remember device
2. reconnect device (disconnect/connect)
3. show address or add acccount (any operation which uses device)
4. passphrase on host looks different than other (previous) passphrase modals (very small) and has strange text "Unlock"

![Screenshot 2020-05-19 at 09 46 51](https://user-images.githubusercontent.com/3435913/82299671-18f49080-99b6-11ea-999d-dd893ea0601b.png)

**Comment by slowbackspace** [comment]
@matejzak I am not sure what to do with this. I didn't put the strange text in there and I don't know what should be there instead. you can fix copy by editing `TR_UNLOCK` msg. 
I believe that the styling of the modal is the same as for confirming empty passphrase (afaik as it was designed ). 

For now I adjusted the width so it is not so narrow.


<img width="428" alt="Screenshot 2020-05-19 at 21 53 30" src="https://user-images.githubusercontent.com/6961901/82371858-30199980-9a1b-11ea-8f09-0b79c559a0fe.png">

**Comment by glacierbits** [comment]
Text updated.
