### ISSUE TITLE
Device needs attention / Solve issue notification always on after passphrase is disabled

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1827]
tested on latest suite with 2.3.0 FW but i think it's general problem.

When you load wallets and passphrase wallet and then **disable** passphrase protection.
Then Wallet selector says Device needs attention. Solve issue button only takes you to your accounts.
even when you remove Passphrase wallet and you have just Standard wallet nothing changes.

**Comment by sorooris** [comment]
2020.05.13-beta c076cefd191ae0b6ba17750a88965bfe3808e12c
Trezor T fw 2.3.0

1. add hidden wallets with a passphrase enabled device 
2. remember hidden wallets, disable passphrase in Suite settings
3. navigate to the wallet management modal

"Solve issue" button is displayed with a "Device needs attention" message. Selecting the button redirects to the main menu's Wallet screen. Navigating back to the wallet management the message and button in the modal are still displayed. 

![image](https://user-images.githubusercontent.com/10185314/82309054-e8672380-99c2-11ea-9ce2-636fb5cb51fc.png)

**Comment by wendys-cats** [comment]
tested on web suite, TT FW 2.3.0

Had the same bug - after disabling passphrase on a device with hidden wallet, the "Device needs attention" appears with "Solve issue" button that does nothing.

**Adding to the issue** - The faulty "Device needs attention" message disappears after going into settings. 

video: https://drive.google.com/file/d/18YkpP9IGKqp22tVgpr7AlMfRzDBPNUtC/view

**Comment by szymonlesisz** [comment]
This case (unavailability) is relevant to Account only and can be solved in Account view
There is no point to solve this from SwitchDevice modal


![Screenshot 2020-05-21 at 18 46 14](https://user-images.githubusercontent.com/3435913/82583686-a80acf80-9b93-11ea-99cb-8301c5f25f08.png)

**Comment by bosomt** [comment]
now it looks like this when you disable passphrase protection when you have passphrase wallets loaded.
Maybe we should force storage wipe or better forget all hidden wallet when you disable passphrase ?

![image](https://user-images.githubusercontent.com/31506317/82730528-c510e100-9d00-11ea-8092-6f25b4dc6ff6.png)

**Comment by bosomt** [comment]
now it always asks you to enter passphrase, and if you say no it will close modal,
i think this is correct behavior /but it asks you to enable it when you want to add standard passphrase/
