### ISSUE TITLE
Send: estimated time missing

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1831]
in BTC-like coins we are able to tell estimated time when tx will probably be mined
we don't have it implemented (time = feeLevel.blocktime * feeLevel.blocks)
![Screenshot 2020-05-19 at 12 00 32](https://user-images.githubusercontent.com/3435913/82313577-d5efe880-99c8-11ea-9e84-b2904ef65590.png)

**Comment by vladimirvolek** [comment]
It is implemented.

![image](https://user-images.githubusercontent.com/3112191/82314042-7f36de80-99c9-11ea-8295-e6e8be2a48fa.png)

**Comment by szymonlesisz** [comment]
current develop:
![Screenshot 2020-05-19 at 12 17 36](https://user-images.githubusercontent.com/3435913/82314886-c1145480-99ca-11ea-8543-e49b15ae5e4d.png)
![Screenshot 2020-05-19 at 12 15 47](https://user-images.githubusercontent.com/3435913/82314904-c8d3f900-99ca-11ea-9df3-d79ddc66d4f4.png)

**Comment by vladimirvolek** [comment]
aaah I see! Adjusted in https://github.com/trezor/trezor-suite/pull/1832
