### ISSUE TITLE
Send: ERC20 Fiat input and calculation

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1847]
Allow calculation `ERC20 > Fiat` and `Fiat < ERC20` in send form like Ethereum or any other coin.

NOTE: not all ERC20 have fiat value (could be unknown, could be below 1 cent)

![Screenshot from 2021-09-06 10-24-14](https://user-images.githubusercontent.com/3435913/132185193-9d34323a-a5cf-4bfa-9d62-88ded482cee8.png)
![Screenshot from 2021-09-06 10-24-28](https://user-images.githubusercontent.com/3435913/132185203-f620e0f1-752d-4b12-8e4a-f15e920635d9.png)

**Comment by glacierbits** [comment]
@szymonlesisz Can you please provide description for the issue? Thanks!

**Comment by hynek-jina** [comment]
It's about missing fiat value expression of some ERC20 tokens

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.3.0 (a936fd6a30ccb545dd2d3fcdf5115d042e12818a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
