### ISSUE TITLE
[Suite] Add optin switch for sentry logging

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#185]

**Comment by mroz22** [comment]
This is probably blocked by something like "suite settings page". I dont think we have one.

**Comment by vladimirvolek** [comment]
Design: https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6fd97e2e1d1baead3e8d

**Comment by mroz22** [comment]
Screen not available anymore.

**Comment by vladimirvolek** [comment]
It's already in the onboarding.
