### ISSUE TITLE
ETH-like transaction with data doesn't show data anywhere

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1854]
Maybe it should be in transaction detail?
all-trop account1
https://ropsten1.trezor.io/tx/0x0ec1f4eb8479bfb345f4b05406deb5c9a77691627b99af488498156678eddf6f

`"input": "0xdead",` field in detail (except for token transfers where input is a smart contract script)

[Design](https://www.figma.com/design/pIibgxmxD0jrAa9UGJd9da/Neue-Desktop-1.5?t=i6xNamdoKAz2amna-0)

**Comment by tomasklim** [comment]
`input` is located in `Input data` section
https://etherscan.io/tx/0x9adc3c645faa05b2d0e0e03be3b2201902cd3ccbb7ab3ff19bfd9015a3eb8a94
![Screenshot 2024-01-23 at 15 21 19](https://github.com/trezor/trezor-suite/assets/33235762/764fe669-b6cf-4185-9ef7-922dadc620bd)

Does it make sense to show raw data or would you like to add decoding feature there?

**Comment by MiroslavProchazka** [comment]
cc @szymonlesisz - can we close this one, or what do you think about @tomasklim proposal? :) 
Thx

**Comment by tomasklim** [comment]
![Screenshot 2024-06-06 at 18 09 50](https://github.com/trezor/trezor-suite/assets/33235762/dbed1be1-15d8-4601-ae50-70526b46ff56)

**Comment by Hannsek** [comment]
We should show there decoding. 

We plan to do so for fw so we can do it together. There is the new standard by ledger, so we should use that.

**Comment by bosomt** [comment]
**QA OK**

- All transfers have 0x data

![Image](https://github.com/user-attachments/assets/9d6b1308-bac8-4f2b-b3ce-c055d995a314)

- smart contracts/staking and so on displays data

![Image](https://github.com/user-attachments/assets/d20d09de-871c-4ac3-a584-9e6afbae1fed)

**Info:**
 - Suite version: web 24.11.0 (f53d31e47fc68e1ce17248b6591d865088781ed1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: WebUsbTransport
