### ISSUE TITLE
Change wording when sending ERC20 tokens

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1857]
Please change wording when sending ERC20 tokens.
Something more explanatory.
Like Maximum decimals allowed for this token is ..
I have no idea why I can't send 1.1 of this token.

![image (1)](https://user-images.githubusercontent.com/31506317/82543087-55a9be80-9b53-11ea-930d-e5790f30e6dd.png)

**Comment by glacierbits** [comment]
@vladimirvolek Please change the copy (and validation rule for tokens that only take integers) to: "Only whole numbers (integers) are allowed". 

I can't change this from Crowdin. Thanks!

**Comment by bosomt** [comment]
**QA OK**

now it says `Amount is not a integer`

Nixos + Chromium 85
Suite dev master commit 01ba0d600a401ef00bf09448b8ad388ad806af88
FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
