### ISSUE TITLE
Tx history: ETH-like & XRP received transactions

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1863]
Unlike BTC those accounts have only 1 receive address and my tx history looks kinda "boring"

![Screenshot 2020-05-21 at 14 01 14](https://user-images.githubusercontent.com/3435913/82557199-94e40980-9b6b-11ea-911d-7e7dcb4fe9ca.png)

**Comment by glacierbits** [comment]
Fixed by the new design.
