### ISSUE TITLE
Error pin cancelled

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1865]
steps to reproduce: Click change pin, then close the modal.
Is it really an error? do we want to show it? if so copy needed :)

<img width="940" alt="Screenshot 2020-05-21 at 15 05 05" src="https://user-images.githubusercontent.com/6961901/82561896-7f271200-9b74-11ea-8b15-9c74f3db8829.png">

**Comment by glacierbits** [comment]
**Problem:** 

(1) Crowding ID not visible on hover in toast notification(s). 
(2) Error string is generic, possibly included in other messages.

**Comment by glacierbits** [comment]
**Fixed.**

Note to myself: For notification translations search "TOAST_" in Crowdin. 

For Connect messages see [errors.js](https://github.com/trezor/connect/blob/2b7f43cf4a9ea64de64be0a68ed5a9def582c3da/src/js/constants/errors.js )
