### ISSUE TITLE
Debug output when accessing settings page?

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1866]
<img width="913" alt="Screenshot 2020-05-21 at 15 19 43" src="https://user-images.githubusercontent.com/6961901/82562969-83ecc580-9b76-11ea-910a-2acb2facda57.png">

steps to reproduce: disconnect all devices, go to /settings/device (device is disconnecte msg in the background) and then connect device, if you are lucky and trezor is blocked by another session (do some stuff in old wallet) you get what's on the screenshot.

edit: Oh now I get it, The name of the device is set to "Unacquired device". It is so weird. I think we don't need to show any text in the background for this case. There is already connect-trezor/blocked-by-another-window modal in front.

**Comment by mroz22** [comment]
> I think we don't need to show any text in the background for this case

yeah, we may just hide it.

**Comment by mroz22** [comment]
It is not a bug! It is actually expected :D

**Comment by glacierbits** [comment]
@mroz22 as discussed, please remove the text. Thanks!
