### ISSUE TITLE
Add option to upload custom firmware

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#1871]
In current Wallet we have a "hidden feature" to upload custom firmware. See our [wiki for tutorial](https://wiki.trezor.io/Firmware_downgrade).

This is used rarely and most often for firmware downgrades which are rare, however they do happen time to time unfortunately either because of firmware bugs, incompatibilities or other issues.

I propose to add an option to upload custom firmware in Suite. I believe this should be somewhere in Advanced Settings or similar since it is not a mainstream feature. 

Design: [**Zeplin**](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/6048a92a43e97c071f75ade9)  
Settings component: [**Zeplin**](https://zpl.io/297wlmz)

**Comment by glacierbits** [comment]
Design proposal added to the issue description. To be implemented in May release sprint.

**Comment by tsusanka** [comment]
If you downgrade a major version your device will get wiped. That means if you have e.g. 2.3.0 and you "custom install" 2.2.3 your device will be wiped. Bootloader warns you about this action but if it is easy we could warn in Suite as well.

**Comment by sorooris** [comment]
T1 downgrade to firmware with lower bootloader required (1.10.0 -> 1.8.0) is allowed, which results in a "Unknown bootloader detected" error and info to contact support (which is unneccessary).

**Expected:**
Downgrade to firmware mentioned above is not allowed, the same way downgrade to 1.7.3 is not (Firmware is too old for your device. Aborting.) 
**Actual:**
"Unknown bootloader detected. Unplug your TREZOR contact our support" is displayed.

![image](https://user-images.githubusercontent.com/10185314/116230789-5c27b980-a758-11eb-9568-4c14e289569f.png)


Note:
attempt to downgrade to 1.7.3 from 1.10.0 in trezoctl
```
$ trezorctl firmware-update -v 1.7.3
Downloading from https://wallet.trezor.io/data/firmware/1/trezor-1.7.3.bin
Trezor One firmware image.
Signatures are valid.
Firmware fingerprint: 10acc6aa4f24aff36627473b98c23dc4f6d0220d33bc1e09cb572f02410ffdaf
Firmware is too old for your device. Aborting.
```

**Comment by tsusanka** [comment]
@alex-jerechinsky I agree with @sorooris this would be nice but I would separate it into another issue so we do not complicate this one. First I would do a simple custom firmware upload and then improve. @alex-jerechinsky could you separate it into another issue pls?

**Comment by tomasklim** [comment]
@tsusanka by advanced settings, you mean the debug settings? (https://suite.trezor.io/web/settings/debug/)

**Comment by tsusanka** [comment]
No, it should be "publicly available" (no hidden debug stuff), I just meant it should be a bit hidden in some advanced place. I would put it into Device > Danger area for now and then when we have more "advanced" features we could make a separate tab. What do you think @matejzak?

**Comment by glacierbits** [comment]
We are working on and advance fold/group option within each tab. The design proposal will be available for then next (July) sprint, but is not necessarily a prerequisite for this feature. FYI I have added the "general" Settings component to the issue description.

**Comment by bosomt** [comment]
**QA OK**

works as expected, separate issues for minor logic/design issues sent 
https://github.com/trezor/trezor-suite/issues/3706
https://github.com/trezor/trezor-suite/issues/4085

**Info:**
 - Suite version: desktop 21.8.1 (8dfc3fbf9faa870f6c7e6017a63ffeb311cf5b16)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.2 Bitcoin only
