### ISSUE TITLE
Data collection: More 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1874]
- [x] Screen resolution for each session

- [x] Add account
 
- [x] Primary Fiat 

- [x] Eject Wallet

- [x] Activity

- [x] Discreet toggle

..for more see [sheet](https://docs.google.com/spreadsheets/d/1NDZT4tqgewpXTmJfdwaorGg-HFfmoQ9-uI7O6fIoG8Q/edit?ts=5ed8c016#gid=0)

**Comment by mroz22** [comment]
branch https://github.com/trezor/trezor-suite/pull/1879 resolves this issue partially.
