### ISSUE TITLE
Amount shown on account is invalid

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#1876]
Issue: Amount shown on account (both BTC and FIAT) is either outdated or invalid

WHERE: sub menu for accounts in Suite (wallet page)

Video shows sending more BTC than should be on the account (according to Suite). 
Blockchain confirms the amount of sent and received BTC is actually valid. 
The amount that suite shows on sccount submenu is most likely outdated, or maybe downright wrong.

https://drive.google.com/file/d/1zOVOJin5QDOXYJVTz-J3HP_jzQWiSiNP/view

**Comment by glacierbits** [comment]
We decided to show "available balance" (incl. unconfirmed tx) in the account balance to fix this inconsistency. XRP is to remain the same, i.e. "available balance - reserve".
