### ISSUE TITLE
Suite uses (internal) dev testnet blockbook servers

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#1893]
Suite: any build/branch (tested on 13bbfff665ff99cb7940538a3b0ca68c1d5beccd)
Browser: any (tested in Chromium)
Coins: tbtc, trop

Actual:
testnet blockbook-dev* servers are used.
Expected:
production testnet servers are used.

**Comment by szymonlesisz** [comment]
only in certain branch, for QA testing purpose (fixed blockbooks are not in production yet)
