### ISSUE TITLE
Distinguish ETH failed & BTC rbf transactions

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1904]
- in tx list
- in tx detail

Failed:
https://ropsten1.trezor.io/tx/0x13d41fecf93eca0ecdf454b35f94564f0817da626b8f27d9c71fc485fceb1add

**Comment by bosomt** [comment]
I think it was already solved. @szymonlesisz close ?

ETH: see screenshot
BTC: you can see bump button when RBF tx before it's confirmed

![image](https://user-images.githubusercontent.com/31506317/126288164-000a3718-05b8-4ec0-b075-c94aef84389e.png)

**Comment by szymonlesisz** [comment]
yes, we can close this
