### ISSUE TITLE
Windows binary is blocked by Windows 10

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1909]
I downloaded and tried to launch 
Trezor Beta Wallet-2020.5.27-beta.exe              26-May-2020 18:28            77493242
from suite-desktop/develop/

![photo_2020-05-26_21-33-14](https://user-images.githubusercontent.com/31506317/82942652-94e36f80-9f98-11ea-8c24-b6e7cb92c303.jpg)
![photo_2020-05-26_21-32-47](https://user-images.githubusercontent.com/31506317/82942656-957c0600-9f98-11ea-8bea-0de0944094b9.jpg)

**Comment by bosomt** [comment]
looks like false alarm

see https://www.virustotal.com/gui/file/b5885b9f8d3cdf81df7c285945323ce0a9ca2f1c4389ef89c23b9dd91ced24cb/detection

lets keep it open till other people confirm that there was no W10 trojan alarm

**Comment by LukasRada** [comment]
I can confirm alarm (updated W10):
![image](https://user-images.githubusercontent.com/7394177/83027298-41246500-a030-11ea-9f42-414e1647cd3c.png)

**Comment by bosomt** [comment]
The file submitted for malware analysis has been added to the queue. Depending on the prevalence of the file and its potential impact, we will prioritize its analysis appropriately.

Keep this email for future reference. Visit the Microsoft Security Intelligence portal to check the status of your submission.

Thank you,

Microsoft Defender ATP team

**Comment by bosomt** [comment]
since today update there is no virus detected via M$ Windows Defender

![image](https://user-images.githubusercontent.com/31506317/83111541-0c162200-a0c5-11ea-8661-7852951369f5.png)
