### ISSUE TITLE
Add new account - unable to search NetworkSelect by coin abbreviation

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#1913]
**Suite version** 664a977aefa1a379090d7fed64c2b7f1c3890d32

Add new account modal's NetworkSelect does not filter by coin abbreviation.

**Steps to reproduce**:
1. select Add account in the left menu
2.  enter for example "LTC" for Litecoin

**Expected**:
Litecoin is found and can be selected.

**Actual**:
No coin is found when searched for "LTC".

![image](https://user-images.githubusercontent.com/10185314/82950457-9ff0cc80-9fa5-11ea-87ab-4b4f7e599fdb.png)

**Comment by mcudev** [comment]
@sorooris Is this issue closable? It was opened almost a year ago and the mentioned select in the current version no longer allows user entered text. The select doesn't seem to respond to keyboard input either. I think maybe the design has moved on past this bug. Thanks!

**Comment by sorooris** [comment]
@mcudev correct, thank you for the heads up! Closing issue.

**QA OK**
Coin Search function in Add account modal disabled.
![image](https://user-images.githubusercontent.com/10185314/112808901-c413b300-9079-11eb-91d7-7eef3155bfd4.png)

Suite: web 21.3.2 6dbeaf3
Browser: Chromium 89.0.4389.82
OS: NixOS 20.09
Device: model 1 1.9.4 ffa9620
