### ISSUE TITLE
Device/Suite PIN/Passphrase communication

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1929]
- detect "Pin/Passphrase" failure in Connectu (regardless of the reason)
- remember device ID – set a delay before new Suite/Device communication after reconnect
- handle all other communication (U2F) during that delay

**Comment by szymonlesisz** [comment]
solved in trezor-connect https://github.com/trezor/connect/commit/36decfdde04655c6e7ff1bb1e70e29dc44cc6620 a while ago

**Comment by sorooris** [comment]
Is there a way for me to replicate the Connect failure? Or is it just a cancel action on device?

**Comment by bosomt** [comment]
any scenarios that we can test ?
suite works fine, fix was probably already merged and released to beta

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev master commit 539ad60eba674bc842260752b1d7017ef35dd86a
FW 2.3.3 commit 0d5f00668
