### ISSUE TITLE
missing FIAT values of some coins in Send transaction dialogue

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1934]
I'm missing FIAT values of some coins in Send transactions dialogue.

ETH,ETC ...

![image](https://user-images.githubusercontent.com/31506317/83120651-995f7380-a0d1-11ea-91e2-56b8e1a5bbd5.png)

**Comment by wendys-cats** [comment]
Missing FIAT values in ETC in Send transactions dialogue
![ETC chybajuci FIAT](https://user-images.githubusercontent.com/58593111/83124475-8dc27b80-a0d6-11ea-8446-52d68b03460b.png)
