### ISSUE TITLE
Passphrase length limit exceeds 50 bytes

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1944]
Paste long text.
You will get warning and button is not green but grey,
But you will hit enter and you will get error.
You can see this error in all branches, including latest develop hash 8e8f45d2783004fa78c5acbf4bb659b2c74a0e90

![image](https://user-images.githubusercontent.com/31506317/83260188-a192de00-a1b9-11ea-88a5-8b698ee8fbe5.png)

x
x
x

![image](https://user-images.githubusercontent.com/31506317/83260271-c4bd8d80-a1b9-11ea-96e1-c47171c4976c.png)

x
x
x

![image](https://user-images.githubusercontent.com/31506317/83260286-cd15c880-a1b9-11ea-9715-1ac915e2b374.png)

**Comment by sorooris** [comment]
Unless there was a change, then in [our wiki](https://wiki.trezor.io/Passphrase) there's mentioned the following:
"A passphrase, as implemented in Trezor devices, can be any character or set of characters, a word, or a sentence up to 50 bytes long (~50 ASCII characters)." in the Important characteristics section.
