### ISSUE TITLE
Provide an option in settings to modify Trezor's auto-lock timeout

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#1946]
Autolock is enabled after 10 minutes by default, however firmware supports changing this to user's value. Minimum <s>is 10 seconds</s> will be 1 minute, <s>no maximum as far as I know</s> maximum is 6 days.

All that is needed is to send the timeout in the ApplySettings message. 

**Design:**
Item in Settings: https://zpl.io/a7AG74j 
Dropdown: https://zpl.io/awzv3eD

**Comment by mroz22** [comment]
Is auto-lock feature present in capabilities? As I do not expect this to work for older firmwares, correct?

**Comment by tsusanka** [comment]
The setting is in T for a long time already, it just did not do anything. So the call will succeed also on older firmwares but will not do anything. So we might simply add this setting for all firmwares.

Nevertheless, adding autolock as capabitility sounds as a good idea anyway. @matejcik what do you think?

**Comment by matejcik** [comment]
Two points against:
1. Autolock exists on T1 since forever, but isn't in capabilities there. You'd have to check "if T1 or TT+capability". So the capability doesn't tell you the truth anyway.
2. I'd say missing autolock is something like dis-capability, and the default expectation should be that it is there.

For the record: if you send settings with (only) autolock to an older FW, you will get "No setting provided" error. ISTM that saying "failed to set auto-lock delay" on older FWs is a correct result?

**Comment by tsusanka** [comment]
> For the record: if you send settings with (only) autolock to an older FW, you will get "No setting provided" error. ISTM that saying "failed to set auto-lock delay" on older FWs is a correct result?

Really? I thought we had `auto_lock_delay_ms` since a long time ago.

**Comment by matejcik** [comment]
> > For the record: if you send settings with (only) autolock to an older FW, you will get "No setting provided" error. ISTM that saying "failed to set auto-lock delay" on older FWs is a correct result?
> 
> Really? I thought we had `auto_lock_delay_ms` since a long time ago.

we do and TT understands it, but doesn't consider it a "setting" :) the code is not great, it has a hard-coded list of fields to look for.

**Comment by tsusanka** [comment]
Let's allow this settings to be set: min to 10s, max to 6 days and disallow values out of this range. Although the max is larger at the moment for T1 the difference will vanish with the _Port_ so let's simplify this and limit to 6 days for both.

**Comment by tsusanka** [comment]
Also note we need to do https://github.com/trezor/trezor-firmware/issues/1088 first.

**Comment by tsusanka** [comment]
In https://github.com/trezor/trezor-firmware/issues/1351 we are changing the minimum value from 10 seconds to 1 minute.

**Comment by keraf** [comment]
I started some work on this to learn my way around Suite and experiment with the communication between the app and device. But it never got finished because I didn't have the design read. Functionality is there though! cc'ing @matejzak for the design.

Here's the branch for reference (needs to be rebased): https://github.com/trezor/trezor-suite/tree/feat/auto-lock-setting

**Comment by glacierbits** [comment]
FYI design proposal added to the issue description ☝🏽

**Comment by tomasklim** [comment]
Notes:
- T1
-- auto-lock works on all fw versions
-- T1 auto_lock_delay_ms is retrieved from the device from version 1.9.4

- T2
-- T2 auto-lock works from version 2.3.2
-- T2 auto_lock_delay_ms is retrieved from the device from version 2.3.5

**Comment by tsusanka** [comment]
@tomasklim btw if it would simplify code dramatically I can imagine supporting auto-locks only from versions 1.9.4 and 2.3.5 for simplicity. Of course with the blessing of @matejzak's. But only if it is really a "big saving"..

**Comment by szymonlesisz** [comment]
it's not only about big saving. it's also about precision.
read my review comment here:
https://github.com/trezor/trezor-suite/pull/3582#discussion_r604045753

**Comment by tsusanka** [comment]
@szymonlesisz got it.

> i think we should not provide this setting for all devices relying on FW version but rather only for those who have exposed `auto_lock_delay_ms` in features.

is a synonymous to mine "only from versions 1.9.4 and 2.3.5". Correct?

**Comment by szymonlesisz** [comment]
right

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.4.1 (3ed454e4e81b72482a9ad780c5cce9846cb29fb1)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model One 1.9.4 regular + model T 2.3.5

**Comment by sorooris** [comment]
**QA OK**

Suite Version: web, app 21.4.1
Browser: Chromium 89.0.4389.82, N/A
OS: Nixos 20.09, macOS 11.2.3
Bridge: 2.0.31 (rev 5f53132)
Firmware Version: model One 1.9.4 ffa96205, model T 2.3.5
