### ISSUE TITLE
trezor-connect: Errors with codes

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1953]

**Comment by szymonlesisz** [comment]
solved by https://github.com/trezor/connect/commit/0661a940afb45f0a8270c83af5fa61023a20a7e5

**Comment by bosomt** [comment]
@szymonlesisz is there some environment where we can test responses to error codes or there is no need to test it on our side ?

**Comment by sorooris** [comment]
@bosomt testing responses is possible through connect explorer
@szymonlesisz could you please confirm that a full test of all responses is not possible at the moment?
