### ISSUE TITLE
Install bridge: hide back button conditionally

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1957]
**Info:**
any setup
 
**Describe the bug**
Install bridge app-modal renders button "Take me back to the wallet" when its not `cancelable`

**Steps to reproduce:**
Enter the wallet without `trezord`

**Expected result:**
This button should be rendred only when accessing `/bridge` route (props.cancelable = true)

**Comment by bosomt** [comment]
**QA OK**

Suite: current web develop , commit bdec55b63a6484b75a4746e74930f573aef8d8ad
Browser: FIrefox, current version 76.0.1 (64-bit)
Device: 1.9.1 production version

Note: when there is no transport, download/install bridge modal is not cancel-able 

![image](https://user-images.githubusercontent.com/31506317/84369737-95eee080-abd7-11ea-8f63-f38e0995d6f5.png)
