### ISSUE TITLE
Ethereum price doesn't fit to window frame

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1959]
**Info:**
 - OS: nixos
 - Browser: Chromium 83
 - Wallet Version: web develop suite de6f63fef7a6d97d4b23812dc3be12aafedda068
 - Firmware Version:  2.3.0

**Describe the bug**
Ethereum has too many decimals and when it include price in Czech crowns it doesn't fit to frame

**Steps to reproduce:**
1. go to web develop suite
2. load Ethereum account
3. change currency to CZK

**Expected result:**
Digits does fit to frame

**Actual result:**
Digits are overflowing

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/83497465-d0130080-a4ba-11ea-9558-4e8dd63a3ce6.png)

**Comment by bosomt** [comment]
**QA NOK**

_Suite_: current web dev version acd9be52f1a2524b601aa0b750c1e3b2984fddb2
_Device_: with production 2.3.1

not yet deployed to suite-web/develop /currently running 19 hours old version/

![image](https://user-images.githubusercontent.com/31506317/84133075-f8fd3d80-aa46-11ea-9daa-b71d410ff759.png)

**Comment by slowbackspace** [comment]
@bosomt CI is broken a merged PR are not deployed right now. You can check if it is fixed here https://suite.corp.sldev.cz/suite-web/update/graph-y-domain/ (and sometimes later when CI gets fixed it will also land in develop)

**Comment by bosomt** [comment]
@slowbackspace it's fixed in this branch, i see that CI is still broken for second day ;)
