### ISSUE TITLE
Firmware updates wiping seed

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1965]
There are firmware updates, that wipe seed and we know it. This should probably be communicated in UI (if we want feature parity)

**Comment by glacierbits** [comment]
@tsusanka Can you please provide more info about this? 😇 I am guessing you will know more..

**Comment by tsusanka** [comment]
I think there was only one case of accidentally releasing a firmware that was wiping your device. However, this FW should never be offered to our users now.

What wipes seed is when you **downgrade** a major version. That means e.g. 2.**3**.0 to 2.**2**.3. But again, that relates solely to downgrading which may happen only via the custom firmware (#1871). I'll add a note there and close here.
