### ISSUE TITLE
Inconsistent settings url /wallet in coins

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#1970]
Probably should be /coins?

![image](https://user-images.githubusercontent.com/3112191/83761846-2167ef00-a677-11ea-9a89-5f0db5903e69.png)

**Comment by slowbackspace** [comment]
same goes for /notifications which are now called activities

**Comment by mroz22** [comment]
changing this would affect data collection as well.

**Comment by glacierbits** [comment]
Yup, let's do it @mroz22

**Comment by bosomt** [comment]
> same goes for /notifications which are now called activities


but url says wallet/notifications/
but page says Activity. dev master f9d6827f67e9877bbd903a05da4469578617dd74

@matejzak change or not to change ?

![image](https://user-images.githubusercontent.com/31506317/94453012-7b556d00-01b0-11eb-9c2c-7e8dec9bd758.png)

**Comment by glacierbits** [comment]
..,that is the question. :) 

Let's leave the "notifications" for now. I will amend the copy. We are preparing new side panel for notifications – calling it that way will be more appropriate anyway.
