### ISSUE TITLE
Auto-lock support on Trezor T

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-suite#1971]
trezor-core master has landed https://github.com/trezor/trezor-firmware/issues/949

this includes a new ButtonRequest type `PinEntry`, which probably needs support via #1642 

in addition, Suite thinks the device is not initialized (presumably because the `initialized` field in `Features` is not sent). We _can_ probably assume that the device is initialized because it has `pin_protection=true` - but as far as the FW is concerned, it does not actually know.
I'm not sure if this should be fixed on the Suite side or on the device side.

**Comment by tsusanka** [comment]
Just to clarify:
> (presumably because the initialized field in Features is not sent).

This is a new thing and is a result of some modifications we had to made because of the auto-lock.

----

@matejzak this is now merged into our master, which means it is scheduled for the July release (July 1st). At this point I am not saying we _must_ release in July but we already know that we would like to. Could you prioritize this issue into your planning?

**Comment by tsusanka** [comment]
After https://github.com/trezor/trezor-firmware/issues/1065 is completed this should boil down to introducing a new button request and a screen "please unlock your device". Let me ping you back after this is done.

**Comment by tsusanka** [comment]
#1065 si done. 

---

> in addition, Suite thinks the device is not initialized (presumably because the initialized field in Features is not sent). We can probably assume that the device is initialized because it has pin_protection=true - but as far as the FW is concerned, it does not actually know.
I'm not sure if this should be fixed on the Suite side or on the device side.

We have fixed this in FW. `Features.initialized` is now reliable and send even if auto-locked.

---

@szymonlesisz could you please try this out?

When trying auto-locked device in suite and I ask for an address I receive `Verify address error: Initialize failed: Cancelled, code: Failure_ActionCancelled`.

Our assumption is that you do not react to the new ButtonRequest type `PinEntry` but based on the message it does not seem that way. Could you please try this out so we are sure there is no other problem? If that's it we will mostly fix the other button request types (Others) as well as discussed but I would like to know if there is another blocker.

**Comment by tsusanka** [comment]
Is this still up to date? I think auto lock works with Suite. @sorooris could you please confirm auto-lock works with Suite?

**Comment by sorooris** [comment]
**QA NOK**

Device locks during both transaction signing and receive address verification.
Auto-lock set to 15 seconds, after that the screen locks and corresponding modal closes and displays a toast notification with a _Sign transaction error: Cancelled_ error message.

> Suite version: develop b010f7a, beta e243afdb
> Device: model T 2.3.4 feb24e42
> Browser: Chromium 85.0.4183.102
> OS: NixOS

**Comment by tsusanka** [comment]
Sorry to mislead, my question was whether it works with autolock in general. That means if set to 10 min. What you are describing will have to be solved with https://github.com/trezor/trezor-firmware/issues/1154. So if you set auto lock to 10 min it's all good?

**Comment by sorooris** [comment]
@tsusanka 
Oh, right, if set to ~10 minutes then it behaves correctly - neither I nor anyone from QA have experienced any issues with auto-lock specifically.

**Comment by glacierbits** [comment]
My two cents (I experienced a problem with passphrase): #2452

**Comment by szymonlesisz** [comment]
last reported issue should be fixed by https://github.com/trezor/connect/commit/bcfc6e1033968dd314378d306fcd3c2766e0565e
