### ISSUE TITLE
Login wall: Update

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1984]
[**Zeplin**](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5eddef22c385f8b930cb949b)

**Comment by bosomt** [comment]
QA OK
Browser: Chromium Version 83.0.4103.61 (Developer Build) (64-bit)
url: https://staging-wallet.trezor.io/
no commit, no suite, no firmware, no revision
Note: landing wall looks ok in latest stagin wallet from yesterday
