### ISSUE TITLE
Recovery mode after reload

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1987]
1. go to onboarding
1. start recovery
1. roload suite
1. go to onboarding again (depends on wheter inital run is finished or not)

now two modals on each other appear. UI appears broken.
![image](https://user-images.githubusercontent.com/30367552/84124833-07922780-aa3c-11ea-9f77-6c2d446b99a2.png)

**Comment by bosomt** [comment]
QA OK

FW: 1.8.3 stable
Browser: Version 83.0.4103.61 (Developer Build) (64-bit)
Branch : https://suite.corp.sldev.cz/suite-web/recovery-fix-continue-in-recovery-mode/ from 09-Jun-2020 09:16

Notes: looks ok after restart of recovery after suite was reloaded in browser

![image](https://user-images.githubusercontent.com/31506317/84262400-d5f18d00-ab1d-11ea-8403-2bda597cb0eb.png)


![image](https://user-images.githubusercontent.com/31506317/84261799-b7d75d00-ab1c-11ea-976d-47ba95230f8e.png)
