### ISSUE TITLE
Conventional commit and changelog

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#1993]
**Is your feature request related to a problem? Please describe.**
Commit messages are mess and changelog is "hand-generated"

**Describe the solution you'd like**
- create standard for commit messages
- add scripts enforcing this standard. Probably .git hooks and maybe some CI magic that would block merging into develop branch unless the commit message may serve as changelog record directly

**Comment by slowbackspace** [comment]
Hehe, just ran into this old issue. We are currently in the process of figuring out what will work best regarding the changelog "generation" so I'll close this.
