### ISSUE TITLE
Inappropriate Terms & Conditions copy text

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2002]
**Info:**
 - OS: any
 - Browser: any
 - Wallet Version: beta, staging
 - Firmware Version: any
 
**Describe the bug**
The `sc-fzoXWK ebEkmM analytics__BottomP-sc-1by5sm3-3 bmiWVe` element copy reads "Oh, by the way, we had to pay a hell lot of money to our lawyers to create some Terms & Conditions." 

**Steps to reproduce:**
1. Navigate to the analytics modal

**Expected result:**
Different copy text.

**Actual result:**
"Oh, by the way, we had to pay a hell lot of money to our lawyers to create some 
Terms & Conditions."

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/84240216-f578bd80-aafd-11ea-9815-4797ab3732e5.png)

![image](https://user-images.githubusercontent.com/10185314/84240700-b26b1a00-aafe-11ea-85b0-5366e3a84b78.png)

**Comment by tsusanka** [comment]
The latest version (20.12) already says "By clicking Continue you agree to our Terms & Conditions.". Closing.
