### ISSUE TITLE
Data collection: FW updates

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#2004]
- [ ] Log FW upgrade from FW A to FW B
      From where (A)  >  to where (B)  >  Success / Fail.
      Also: Log incremental update.

**Comment by bosomt** [comment]
is there anything that we can test ?
Should I check **Application log** for fw update info ?

**Comment by sorooris** [comment]
@bosomt see https://github.com/trezor/trezor-suite/issues/2161#issuecomment-707157840
