### ISSUE TITLE
skip_backup

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#2008]
reset_device call - T2

Mytrezor
shamir: skip_backup: false
basic: skip_backup: true

Suite
shamir: skip_backup: true
basic: skip_backup: true

Problems:
- copy for shamir is not correct, actually case of shamir in copy is not covered at all
- maybe we want to force user to do backup immediately?

**Comment by glacierbits** [comment]
I believe this to be fixed by the new onboarding.
