### ISSUE TITLE
Incorrect FIAT value in Confirm transaction modal + GAS price in tokens and not in coin value

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2022]
**Info:**
 - OS: nixos
 - Browser: , Firefox 76.0.1 (64-bit)
 - Wallet Version: web staging , commit 33caf3bc8934385835ad554571380d0c30278775
 - Firmware Version: 1.9.1 0xc6b2580cd245ee924507f45e9675f857a3d78768,
 
**Describe the bug**
There is something incorrect in dialogue logic.
In other places price is correct

**Steps to reproduce:**
Go to suite
Try to send ERC20 token
Check Send transaction modal

**Expected result:**
You will see real Etoken wallue and GAS price  will be in coin value

**Actual result:**
Crazy high price in modal 
GAS price is in token too

**Screenshots:**
insert here
![image](https://user-images.githubusercontent.com/31506317/84507731-92378880-acc1-11ea-9538-c09cfe724cd5.png)
![image](https://user-images.githubusercontent.com/31506317/84507827-b4c9a180-acc1-11ea-8fae-6e91d1e0724c.png)

![image](https://user-images.githubusercontent.com/31506317/84507974-f0fd0200-acc1-11ea-8160-3af46f573e48.png)

**Comment by bosomt** [comment]
still broken in suite-web/send-new-version 16ed6dd4bc8abd05dfa9ddbf51669e534d51432b

**Comment by bosomt** [comment]
still broken in Wallet Version: web, commit 17ab12b + freeze app 44254ee

![image](https://user-images.githubusercontent.com/31506317/89535125-40f5d200-d7f6-11ea-8c54-62ac28b02f33.png)

**Comment by bosomt** [comment]
same problem in Account transaction list 

![image](https://user-images.githubusercontent.com/31506317/89866956-b4aa2d00-dbb0-11ea-8bed-a7b584518488.png)

**Comment by bosomt** [comment]
**QA OK**

fixed in current master
2.3.2 63ebb8ccb
current dev master 74b74b0c70658ff4cad66541441aa7274f949308

![image](https://user-images.githubusercontent.com/31506317/90043363-48bce700-dccc-11ea-9210-ca12111189b2.png)

staging OK too

staging commit 74b74b0c70658ff4cad66541441aa7274f949308

![image](https://user-images.githubusercontent.com/31506317/90043646-ab15e780-dccc-11ea-80d4-807e6d8b4aa9.png)

**Comment by bosomt** [comment]
sorry, forgot about send dialogue ;)

still incorrect units

![image](https://user-images.githubusercontent.com/31506317/90044651-3774da00-dcce-11ea-9e02-2efcb7027e38.png)

**Comment by bosomt** [comment]
I just noticed, it says Received/Sent ETH
it should say Received/Sent ERC20

![image](https://user-images.githubusercontent.com/31506317/90125966-317d0880-dd63-11ea-866b-397950d98938.png)

**Comment by wendys-cats** [comment]
Issue with no FIAT ammount for gas price/gwei persists not only when sending tokens, but when sending ETH as well.

![ETH gweis fiat price](https://user-images.githubusercontent.com/58593111/90147049-0ce45900-dd82-11ea-81c7-86ba9181a189.gif)

**Comment by bosomt** [comment]
**QA NOK**

suite  a8438ada39fd127f5487bb5cff7c9911748a9562
OS Nixos 
BR Chromium 84.0.4147.135
FW 2.3.3 0d5f00668

looks ok now BUT
price of token is not 400$ , it's price of ETH not token price @szymonlesisz 

![image](https://user-images.githubusercontent.com/31506317/92149371-368f1e00-ee1e-11ea-90f3-5693e049d38d.png)

**Comment by bosomt** [comment]
**QA NOK**

sending 0.5 VIU , it says 0.0000000000000000005 VIU

 commit 118b1cb4d9f9c8aed2634010fe64a02f66385539
OS Nixos
BR Chromium 84.0.4147.135
FW 1.9.3 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8


![image](https://user-images.githubusercontent.com/31506317/92227965-65050b80-eea7-11ea-9ab8-d8753be577bd.png)

**Comment by bosomt** [comment]
still broken, tested few times, once it displayed correct 0.5 value, no idea why


staging and master:  cf1f18089c5ed75a68f2e720a5e08b6e3df79130
both same last commit

![image](https://user-images.githubusercontent.com/31506317/92360610-6162c600-f0ed-11ea-91a3-1f683e78729c.png)

**Comment by slowbackspace** [comment]
@bosomt this one is weird. could you try to reproduce it one more time? It seems to work for me (on current develop)

edit: to avoid any confusion. we don't have fiat rates for VIU (coingecko for some reason doesn't support VIU in its API we are using), previously there was mistakenly showed ETH rates, that was fixed.

screenshot from sending 0.2 VIU
<img width="839" alt="Screenshot 2020-10-06 at 17 58 56" src="https://user-images.githubusercontent.com/6961901/95226764-9e5dcd80-07fd-11eb-8fe0-e1554b6c2b8c.png">

**Comment by bosomt** [comment]
it looks OK now, looks like it was fixed already
tired all tokens we and it all looks good

**QA OK**

Nixos + Chromium 85
Suite staging  commit a96a6885eabbb51d757925059fcbed5347b7c2b4
Device TT fw 2.3.4 commit 55baf3a

**Comment by bosomt** [comment]
@slowbackspace @szymonlesisz 

that total ETH valuse is not correct
it says value of ETH and not token value.
It looks like you are sending 0.25eth /85$

![image](https://user-images.githubusercontent.com/31506317/95300999-42885880-0880-11eb-9e21-81c43fbfce78.png)

Nixos + Chromium 85
Suite staging commit a96a688
Device TT fw 2.3.4 commit 55baf3a

**Comment by bosomt** [comment]
same on web dev master 

Nixos + Chromium 85
Suite staging commit a735c49a28ba97569e9dab9d40794a381480690f
Device TT fw 2.3.4 commit 55baf3a

![image](https://user-images.githubusercontent.com/31506317/95323400-635fa680-089e-11eb-8185-6ded37ad6334.png)

**Comment by bosomt** [comment]
**QA NOK**

Microsoft Windows [Version 10.0.18363.1082]
Suite win app commit a26355244abe0850d23e6c353b5e157f44f12694
Device Trezor model T 2.3.4

by removing total ETH value or maybe not you made possible to send 0 of ERC20 tokens :)
You can even sign it. When you send it it says `Sign transaction error: replacement transaction underpriced`
Can you please check it ? @keraf @szymonlesisz , ro do you want me to send separate issue ?

![image](https://user-images.githubusercontent.com/31506317/95745690-d352a000-0c95-11eb-8414-25068a0555b1.png)
![image](https://user-images.githubusercontent.com/31506317/95745707-d8175400-0c95-11eb-96d6-6cdc92846015.png)
![image](https://user-images.githubusercontent.com/31506317/95745791-fbda9a00-0c95-11eb-8aaa-7778a2c79c48.png)

**Comment by szymonlesisz** [comment]
this has nothing to do with ReviewTransaction modal or removing "total eth" from it.
Those elements ale only visual parts of the sign transaction process.
"replacement transaction underpriced" means that you are trying to send using the same "nonce" as in previous pending tx (nonce = sequence number similar to RBF in bitcoin) 

Pls open separate issue for that with detailed description how to simulate this @bosomt

**Comment by bosomt** [comment]
https://github.com/trezor/trezor-suite/issues/2593 created

**Comment by bosomt** [comment]
QA OK

Microsoft Windows [Version 10.0.18363.1082]
Suite win app commit a263552
Device Trezor model T 2.3.4
