### ISSUE TITLE
Custom fees are ignored in send dialogue

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2023]
**Info:**
 - OS: nixos
 - Browser: , FireFox  76.0.1 (64-bit)
 - Wallet Version: staging web, commit 33caf3bc8934385835ad554571380d0c30278775
 - Firmware Version: 1.9.1 , revision 0xc6b2580cd245ee924507f45e9675f857a3d78768
 
**Describe the bug**

Custom fee is ignored and transaction is sent with last selected fee /normal, high, low.../
See screenshots, even when you set fee to 1 it will be sent with much higher fee compared to wallet.

0.00000229 DOGE vs 3 DOGE
0.00000x vs 0.0000x BTC

https://doge1.trezor.io/tx/78f75c802f17ad3871534df30819d9d77c1c9e4f9dfa23434be96ce166030c99

same for BTC and probably all coins.

**Steps to reproduce:**
1. prepare transaction in send dialogue
2. try to send it with high fee check fee
3. try to send it with custom fee check fee

**Expected result:**
Send dialogue will use custom fee from custom fee field

**Actual result:**
Send dialogue will use last selected fee from fee selector

**Screenshots:**

![doge](https://user-images.githubusercontent.com/31506317/84529915-92944b80-ace2-11ea-96cb-3df5aca4d9cd.png)
![doge4](https://user-images.githubusercontent.com/31506317/84529932-97f19600-ace2-11ea-88cb-788b80ba3a28.png)

![doge2](https://user-images.githubusercontent.com/31506317/84529920-945e0f00-ace2-11ea-8348-c7b3d3d715ba.png)
![doge3](https://user-images.githubusercontent.com/31506317/84529928-9627d280-ace2-11ea-9d7b-a510dda0ef5a.png)

**Comment by wendys-cats** [comment]
**Issue: Change of fee is ignored until Amount is updated**

**Info:**
**OS:** nixos
**Browser:** Chromium Version 83.0.4103.61 (Developer Build) (64-bit)
**Wallet Version:** branch suite-web/send-new-version/ #1966
**COMMIT HASH** 16ed6dd
**Firmware Version:** model TT 2.3.1 and T1 1.9.1

**Bug** 
Suite ignores fee change, will not update information after user changes fee - only after user changes Amount.

**Steps to reproduce:**
**1.** Connect device and load accounts
**2.** Open Send form, fill it correctly
**3.** Check with Review transaction
**4.** Go back, change fee and Review transaction again

**Expected result:**
Suite will react to change of fee by user.

**Actual result:**
Suite ignores fee change, will only update information after user changes Amount.
This ONLY happens on send-new-version branch @vladimirvolek @szymonlesisz.

**video:** https://drive.google.com/file/d/1z9vtoXIACtBeMuYQtnBSX7cKJ0ObYNvh/view

**Comment by bosomt** [comment]
still broken in Wallet Version: web, commit 17ab12b + freeze app 44254ee

![image](https://user-images.githubusercontent.com/31506317/89545594-da77b080-d803-11ea-9c58-fffa442fb234.png)

![image](https://user-images.githubusercontent.com/31506317/89545568-d055b200-d803-11ea-8342-75ee4ec7abc5.png)

**Comment by bosomt** [comment]
**QA OK**

works fine now in a8438ada39fd127f5487bb5cff7c9911748a9562

OS Nixos 
BR Chromium 84.0.4147.135
FW 1.9.3 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8
