### ISSUE TITLE
Suite is missing validaton for file type when uploading homescreen

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2027]
**Issue: Suite lets you choose any file for Custom homescreen upload**

**OS** nixos
**Browser** Chromium Version 83.0.4103.61 (Developer Build) (64-bit)
**Suite URL** suite-web/develop version 20.6.1-beta
**Device** TT 2.3.1 FW
 
Suite does not have any form of validation for file upload when choosing a custom homescreen image, user can choose a text, zip, pdf.... 
Important: Suite will NOT let user load the file on device. 

**Steps to reproduce:**
**1.** Connect TT device, load Device Settings 
**2.** Click on Upload image 
**3.** Change filter to all files and choose something unsupported

**Expected result:**
Suite will not allow the user to choose unsupported file types.

**Actual result:**
Suite does allow the user to choose unsupported file types. 

**video** https://drive.google.com/file/d/1C78eS2FC4Obc5SwokrQdt_tIJ5yKQF5b/view

**Comment by wendys-cats** [comment]
**Issue: Homescreen upload error message needs to be highlighted**

**OS** nixos
**Browser** Chromium Version 83.0.4103.61 (Developer Build) (64-bit)
**Suite URL** suite-web/develop version 20.6.1-beta
**Device** TT 2.3.1 FW

**Steps to reproduce:**
**1.** Connect TT device, load Device Settings
**2.** Click on Upload image
**3.** Change filter to all files and choose something unsupported

**Expected**
Error message/warning "Invalid file selected. Must be .jpg or .png" will be highlighted so that user can immediately notice it.

**Actual**
Warning/error message "Invalid file selected. Must be .jpg or .png" is barely noticeable.

![homescreen issue](https://user-images.githubusercontent.com/58593111/85996668-d38d9f00-ba08-11ea-9021-d197d252dd2c.jpg)

**Comment by sorooris** [comment]
Suite version: suite-web/develop version 20.6.1-beta 9d2fa6fef4e4dbb5f54d9eefa5c84388f11ed5cb

**Comment by mroz22** [comment]
Maybe it would be better to create new issues in such cases. It somewhat extends the original scope of this issue. I actually don't have any design for that so I can only guess what would satisfy the merciless QA department :]

**Comment by jerechinsky** [comment]
@wendys-cats could you please try to reproduce once again? I tried myself, but the file picker wouldn't let me pick anything but images.

**Comment by wendys-cats** [comment]
QA OK

Allows to load only images.

Tested on
NixOS 21.3
Browser 82 82.0.2 (64-bit)
Suite version 21.4.1 1baa8ced16f2f6a5d60e9f4d7911669f856123d8
Device TT 2.3.1 FW

Windows 10 Version 10.0.19042.867
Suite APP 21.4.1 95311f198fba5d2c452cd5d9ce3ede0a50a06a2d
Device T1 1.9.4

**Comment by jerechinsky** [comment]
thanks!
