### ISSUE TITLE
Add ability to copy notification's message

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2032]
I find it extremely annoying that I can not copy the text message in the notification. I believe it will be a common use case - for example to seek support you usually need the message.

![x](https://user-images.githubusercontent.com/1835345/84748598-269f3500-afb9-11ea-8e17-1c4169bcb49f.gif)

**Comment by glacierbits** [comment]
New design of these notifications is under construction. Let's fix this issue with the advent of the new design (in the upcoming days / week).

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev web master commit bc892c2
Device TT 2.3.3 commit 0d5f00668
