### ISSUE TITLE
Modal with info that Trezor is not initialized overlaps screen

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2036]
**Info:**
 - OS: windows 10 
 - Browser: Chromium 83
 - Wallet Version: web wallet at beta url 201b6e4264d020db7de704670c010d5b9663e7ac
 - Firmware Version:  2.3.1 c6b2580cd

**Describe the bug**

During onboarding/updating device and seed is/was wiped you will see this moddal that overlaps screen even when using full HD resolution.

**Steps to reproduce:**
1. connect device with unsigned firmware
2. perform update 
3. you will see this modal

**Expected result:**
Modal will fit screen

**Actual result:**
modal doesn't fit to screen

**Screenshots:**
![IMG_20200617_083700](https://user-images.githubusercontent.com/31506317/84875505-55cfa800-b086-11ea-8beb-b56ab08d15af.jpg)

**Comment by slowbackspace** [comment]
what a ancient issue! I assume it has been fixed already, if not then please reopen the issue 🙇

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82.0 (64-bit)
Suite commit 99959260d5639480dfb11e53a4f2ab1d789b0e7b
Device model One unsigned 1.9.0 + signed latest 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
