### ISSUE TITLE
Restore previous instanceId used in analytics and error reporting after clearing storage

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2037]
otherwise we get multiple error reports from the same user clearing storage that looks like coming from multiple user

**Comment by mroz22** [comment]
Maybe simple hash of useragent would be better. Question is whether it would be specific enough or we are likely to get numerous same hashes for actually different users

**Comment by slowbackspace** [comment]
I'll close this for now. It doesn't look like it is affecting error reporting that much. It may skew reports with less frequent errors (and still it doesn't matter that much if the issue is affecting 3 users or 6 users), but with 100s and sometimes 1000s of reports it doesn't matter if few users are counted in twice.
