### ISSUE TITLE
Unapparent "Select device" button on "Device XY Connected" notification function

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2040]
**Issue: Unapparent "Select device" button (on "Device XY Connected" notification) function**

**Info:**
 - OS: nixOS 
 - Browser: Version 83.0.4103.61 (Developer Build) (64-bit)
 - Wallet Version: web, suite develop 
 - Firmware Version: TT FW 2.3.1 revision c6b2580cd, T1 FW 1.9.1 revision 0xc6b2580cd245ee924507f45e9675f857a3d78768 

**Describe the bug**

**1.** The whole notification does not show up on screen (like other notifications). This might present a missed opportunity to make things for user easier.

**Conclusion 1:** Hiding a notification that has a button defeats the purpose of making shortcuts (button) and of the notification itself. 

**2.** The button itself (coupled with the fact that user has to go to Notifications page to find it) does very little, especially visually. While it does technically select the new device, it is very subtle and there is almost zero change on screen, most users might miss it.

**Conclusion 2:** The button functionality has not been shared, please clarify. Also, its usage can be misleading for the user, as it looks like it does nothing. 

**Steps to reproduce:**
1. Connect first device, discover wallet
2. Connect second device
3. Go to Notifications and click "Select device" button

**Expected result:**

**1.** Notification will appear on screen like others do. 
**2.** "Select device" button will also redirect user either to Dashboard page (so accounts can be loaded), or will open Choose device / Choose wallet modal (so the user will load the accounts by clicking on the wallet). 

We can safely conclude that by clicking on "Select device" button user wants to interacts with the device. This will not only make the process more noticeable for the user, it will also make it easier for the user to immediately start using their accounts.

**Actual result:**

**1.** Notification does not show.
**2.** "Select device" button does not redirect the user.

**video:** https://drive.google.com/file/d/1pj01nZ3VYBmxoNNCjUztOWZRXEfK2YdP/view

**Note:**

Not having the Choose wallet / Choose device modal open upon connecting another device is greatly appreciated.

**Comment by glacierbits** [comment]
Old design, closing issue.
