### ISSUE TITLE
 Support Zcash Heartwood hardfork

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2045]
To support Zcash Heartwood upgrade we need to start sending a new `branch_id` equal to `0xF5B9230B`. The upgrade should happen around July 16, see https://z.cash/upgrade/heartwood/.

The right solution to fix this is to prepare this now, test against testnet and publish later. However way easier solution is to fix it on July 16 directly and hope that it works..

This needs to be done in an older wallet as well :(!

**Comment by tsusanka** [comment]
We have a testnet blockbook, so we might test it I guess. https://blockbook-dev.corp.sldev.cz:19132/

**Comment by sorooris** [comment]
**QA OK**
tested successfully on [Beta](beta-wallet.trezor.io) 582ebd2f9c1b733058df3e6adf70f842c7ef394d, and branches 3e0d6372647d96b5dfb9219a01df156b739ef3cd and 8069423f3fede3dc9e73a0baff02d7099deffbce
