### ISSUE TITLE
Tabular figures: FW update

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2048]
Tabular figures on all "numbers" across the app.

**Comment by glacierbits** [comment]
Mostly handled by #2043

Still missing tabular figures in: 

- Dashboard (Portfolio value)
- Price (both Dashboard, and Account)

**Comment by glacierbits** [comment]
Oh and 3 more: 

- Dates (TX history) 
- Graph numbers
- Addresses 

.. and perhaps Account numbers (Account #1) to keep it clean?

**Comment by bosomt** [comment]
Is there way to to test it or if we see numbers in suite without any kind of errors or glitches we can consider it tested ?

**Comment by glacierbits** [comment]
Please check the aforementioned categories (in bullet points). If the figures are [tabular](https://www.fonts.com/content/learning/fontology/level-3/numbers/proportional-vs-tabular-figures#:~:text=Proportional%20vs.-,Tabular%20Figures,will%20be%20read%20in%20columns.), all is good. 

The most obvious difference in the font we are using is number 1: Proportinal figure (sans-serif), tabular figure (serif). 

<img width="550" alt="Screen Shot 2020-07-12 at 09 58 05" src="https://user-images.githubusercontent.com/29627086/87241759-7fca7f00-c426-11ea-96a2-8748b3880738.png">

**Comment by bosomt** [comment]
**QA OK**

suite master dev web version commit b739c8cb5eb507423f3a3dbb684e520a0bface72
FW 1.8.3 0xdf0963ec48f01f3d07ffca556e21ff0070cab099,
Chromium 83.0.4103.116
latest nixos

@matejzak thank you for your reply, now I see difference ;) looks good

**Comment by bosomt** [comment]
I see that new font is not used in graph hover detail 
is that proper behavior or not ?

![Screenshot from 2020-07-12 11-43-46](https://user-images.githubusercontent.com/31506317/87243349-acd25e00-c435-11ea-82e1-5148c7c35c67.png)

**Comment by bosomt** [comment]
and  Account #1 uses both fonts :)

see 

![image](https://user-images.githubusercontent.com/31506317/87243486-9547a500-c436-11ea-8175-7619cf3dba9b.png)

**Comment by bosomt** [comment]
and  Account #1 uses both fonts :)

see 

![image](https://user-images.githubusercontent.com/31506317/87243486-9547a500-c436-11ea-8175-7619cf3dba9b.png)

**Comment by bosomt** [comment]
and receive address :)

![image](https://user-images.githubusercontent.com/31506317/87243526-f5d6e200-c436-11ea-9d1f-e55b6b3ddc4d.png)

![image](https://user-images.githubusercontent.com/31506317/87243577-67af2b80-c437-11ea-847b-302b177715c7.png)

![image](https://user-images.githubusercontent.com/31506317/87243595-86adbd80-c437-11ea-8bc2-61198c1fb3cd.png)

![image](https://user-images.githubusercontent.com/31506317/87243627-c5dc0e80-c437-11ea-8c1b-616e9baee10e.png)

![image](https://user-images.githubusercontent.com/31506317/87243647-ea37eb00-c437-11ea-85a2-00dbbad788c6.png)

![image](https://user-images.githubusercontent.com/31506317/87243948-9d094880-c43a-11ea-96bb-1875b8645e5b.png)

and popup notification

**Comment by glacierbits** [comment]
Checked this with Ondra: Let's please **use tabular figures at all places** where there are number for consistency sake. @slowbackspace  Thanks! 

From what I see, we are missing: 

- Addresses
- Switch wallet 
- Activity 
- Review Tx modal 
- Inputs in Send

**Comment by slowbackspace** [comment]
> Checked this with Ondra: Let's please **use tabular figures at all places** where there are number for consistency sake. @slowbackspace Thanks!
> 
> From what I see, we are missing:
> 
> * Addresses
> * Switch wallet
> * Activity
> * Review Tx modal
> * Inputs in Send

I am leaving the send form unchanged for now since it is being heavily refactored (along with the new design). @vladimirvolek  please use tabular nums (and slashed-zero) where they are needed!

Regarding addresses I thought I already put tabular nums in use, but now I see I missed few cases (certainly some in tx details modal). We probably also want to use slashed in this case. I'll update it along with activity screen.

**Comment by bosomt** [comment]
looks better now.

found one at today's release here

![image](https://user-images.githubusercontent.com/31506317/87684362-76247c80-c782-11ea-8e39-c0493d8355c0.png)
![image](https://user-images.githubusercontent.com/31506317/87684433-89cfe300-c782-11ea-9e17-967eb12c3acf.png)

commit https://github.com/trezor/trezor-suite/commit/582ebd2f9c1b733058df3e6adf70f842c7ef394d

**Comment by bosomt** [comment]
I still see old font in FW update dialogue.

 - Wallet Version: web, commit 17ab12b7275eb83ded72c590328d371e6132ec69 + freeze app 44254ee8780ea1550b017621c154b2990b1fe3f0


![image](https://user-images.githubusercontent.com/31506317/89519663-059ad980-d7dd-11ea-8aff-68728a79e7c9.png)

**Comment by glacierbits** [comment]
I believe we can close this issue since the changelog looks different now altogether.
