### ISSUE TITLE
Shamir recovery not handled properly when device is reconnected 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2049]
**Info:**
 - OS: Nixos
 - Browser:Chromium | 83.0.4103.97 (Developer Build) (64-bit)
 - Wallet Version: web suite, dev master 50e2356caeb0cd2b16f05a58c9ae846c354553dc
 - Firmware Version: model T, 2.3.2  6ebb388
 
**Describe the bug**
Shamir recovery not handled properly when device is reconnected.
See screenshots . Suite doesn't handle possibility that you can continue with recovery after device was reconnected

**Steps to reproduce:**
1. start recovery
2. enter first shamir seed
3. reconnect device
4. continue with recovery and observe suite

**Expected result:**
Suite should say that you can continue with recovery and not that it failed.
**Actual result:**
Suite says recovery failed even you can continue and finish recovery of shamir seeds

**Screenshots:**
insert here

**Note(s):**

![image](https://user-images.githubusercontent.com/31506317/85270150-2ac7c880-b479-11ea-90c7-863d65e55358.png)

![image](https://user-images.githubusercontent.com/31506317/85269856-c99ff500-b478-11ea-9818-60c9d63b739f.png)

![image](https://user-images.githubusercontent.com/31506317/85270205-416e1f80-b479-11ea-8685-13ca483e9a4e.png)

**Comment by mroz22** [comment]
@bosomt  Could you please retest whether it is fixed on `recovery-persistence` branch?

**Comment by bosomt** [comment]
@mroz22 on it !

**Comment by bosomt** [comment]
Tested with **TT 2.3.1** commit c6b2580cd
and Chromium | 83.0.4103.106

and it was fixed and looks fine. 


But I noticed that you sometimes you have to select number of words **twice** when you continue recovery and you still have to enter first share.

I will try to record it and attach it. Strange that it only happens sometimes.

**Comment by bosomt** [comment]
@mroz22 

ok, i found reason why you see select number of words **twice**

1) first you see this:

![image](https://user-images.githubusercontent.com/31506317/86250886-741ec300-bbb1-11ea-8918-9a12fc6f2139.png)


2) you will connect device, it will ask you to select how many word seed you want to recover
3) you will select how many words dialogue **before** you will see second screen /you have only few seconds or you need wifi on train :)/:

![image](https://user-images.githubusercontent.com/31506317/86251089-b6480480-bbb1-11ea-951e-b06c92aabd85.png)

4) this second modal will reset recovery dialogue and you will be asked to _Select number of words_ again

**Comment by bosomt** [comment]
+
when you cancel recovery it will say **Recovery seed check failed**
even that it was recovery and not dry run

![image](https://user-images.githubusercontent.com/31506317/86351972-5f9c0280-bc65-11ea-8d74-a477d2c29c41.png)

**Comment by bosomt** [comment]
**QA OK**

**suite** dev master commit 96a98981993e44d470614f17cd33cb2f8a3f56ec
**FW** 2.3.1 c6b2580cd

works fine in recovery and in dry run too


how about that double dialogue ? do you want me to create separate issue ? or we just ignore it ?
@mroz22 @vladimirvolek 
https://github.com/trezor/trezor-suite/issues/2049#issuecomment-652286285
