### ISSUE TITLE
Custom fee price too high in new send dialogue branch

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2054]
**Info:**
 - OS: latest nixOS
 - Browser: Chromium | 83.0.4103.106 (Developer Build) (64-bit)
 - Wallet Version: web, commit 968c83ecfa5bbecfc202ab9ac13fdbce0e515754
 - Firmware Version: TT  , revision 0xc6b2580cd245ee924507f45e9675f857a3d78768,
 
**Describe the bug**
Price of fee is too high in FIAT and it doesn't match real FIAT price

**Steps to reproduce:**
1. go to send-new-version branch
2. choose BTC/send dialogue
3. change fee selector to custom
4. observe

**Expected result:**
fee in FIAT will match develop branch

**Actual result:**
new send branch shows crazy high price in FIAT

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/85848113-e4d87080-b7a8-11ea-8558-d66d84d34071.png)

![image](https://user-images.githubusercontent.com/31506317/85848133-f0c43280-b7a8-11ea-9512-04185b366e39.png)

**Comment by vladimirvolek** [comment]
Fixed in 3f52efb8b4c2c0109937d6e3932742459f998dbf

**Comment by bosomt** [comment]
**QA OK**

works fine in 16ed6dd4bc8abd05dfa9ddbf51669e534d51432b
