### ISSUE TITLE
Discreet mode: Transactions' blur cut off from left

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2056]
Nitpick: 

<img width="160" alt="Screen Shot 2020-06-26 at 18 22 54" src="https://user-images.githubusercontent.com/29627086/85879500-c8552c00-b7da-11ea-9122-bd89100dd6fb.png">

**Comment by bosomt** [comment]
**QA OK**

suite commit https://github.com/trezor/trezor-suite/commit/582ebd2f9c1b733058df3e6adf70f842c7ef394d
FW 1.9.1 0xc6b2580cd245ee924507f45e9675f857a3d78768,
latest nixos and chromium
