### ISSUE TITLE
Label "soon" kind of messy

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2057]
- Text is not vertically alligned in the label 
- Move it higher and to the right on the "Exchange" tab

<img width="202" alt="Screen Shot 2020-06-26 at 18 36 00" src="https://user-images.githubusercontent.com/29627086/85880335-20406280-b7dc-11ea-91ea-e12c30b7eb31.png">

**Comment by bosomt** [comment]
**QA OK**
looks better in suite-web/develop 892f87ce71cd5f943d98b1bf8eebbec353d6514a
