### ISSUE TITLE
Send form - testnet coins: Unable to delete the last digit

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#2060]
When making correction of the intended transaction amount, it's impossible to delete the last digit of the input. The only workaround is refreshing the page. Beta desktop & browser version, staging wallet. Testnet coins only. 
![Screenshot (28)](https://user-images.githubusercontent.com/54173889/86002741-0d62a380-ba11-11ea-88ff-443689684a3d.png)

**Comment by vladimirvolek** [comment]
duplicated https://github.com/trezor/trezor-suite/issues/1889

**Comment by wendys-cats** [comment]
Issue fix is implemented here on branch send-new-version, not on develop.

**Comment by bosomt** [comment]
tested in b739c8cb5eb507423f3a3dbb684e520a0bface72
still **QA NOK** in master 
/in master BTC coin has same behavior/

**Comment by vladimirvolek** [comment]
duplicated of #1889. Please DO NOT open again.
