### ISSUE TITLE
Total sum is incorrect

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2063]
**Info:**
**OS:** nixos
**Browser:** Chromium Version 83.0.4103.61 (Developer Build) (64-bit)
**Wallet Version:** branch suite-web/send-new-version/ #1966
**COMMIT HASH** 16ed6dd4bc8abd05dfa9ddbf51669e534d51432b
**Firmware Version:** model TT 2.3.1 and T1 1.9.1
 
**Bug**
Total sum is incorrect. It displays only the transaction fee sum, it is missing the actual Amount the user is transferring.
This ONLY happens on send-new-version branch @vladimirvolek @szymonlesisz. 

**Steps to reproduce:**
1. Connect device and load accounts
2. Open Send form, fill it correctly
3. Check the total sum

**Expected result:**
Total sum will show Amount + transaction fee.

**Actual result:**
Total sum does not include Amount.

**Screenshots:**
![image](https://user-images.githubusercontent.com/58593111/86006869-e9a25c00-ba16-11ea-866a-fdb1b9ba0b53.png)

**Comment by sorooris** [comment]
**QA OK**
> Wallet Version: web, 20.9.1 cf1f180
OS: NixOS
Browser: any supported (tested Firefox 79.0.1)
Device 1.9.3 0d5f00668

Tested already in #2204, retested again:
![image](https://user-images.githubusercontent.com/10185314/92500594-a6761d80-f1fd-11ea-9070-193d58201a26.png)
