### ISSUE TITLE
Add blur behind all modals

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2066]
Allows user to better focus on the content of the modal itself. Not to mention it looks legit. 

**Example**

![Screen Shot 2020-06-30 at 09 27 41](https://user-images.githubusercontent.com/29627086/86097759-6edc4e00-bab5-11ea-89b0-f49b797caf05.png)

**Comment by bosomt** [comment]
**QA OK**

looks great
web suite staging https://github.com/trezor/trezor-suite/commit/e0f48dc8e83feabbeafecac4f25b57cd750c8807
FW 1.9.1 0xc6b2580cd245ee924507f45e9675f857a3d78768,
latest Chromium and Nixos
