### ISSUE TITLE
Remove "Become a tester" from Landing page

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2068]
**This:**

<img width="342" alt="Screen Shot 2020-06-30 at 10 20 38" src="https://user-images.githubusercontent.com/29627086/86102167-769ef100-babb-11ea-9ccf-b639d1d7dae6.png">

**Comment by bosomt** [comment]
**QA OK**

its' gone from web suite master

FW 1.9.2 0x14a8da9c2830802df1474f463377669513da64fd,
Suite f8bb8f86da74e6e297831a892a8218c9400096c2
