### ISSUE TITLE
Annoying Basic recovery T1 in new Design (field missing focus)

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2074]
**Issue: New Design has an annoying basic recovery bug for T1**

**OS** nixos
**Browser** Chromium Version 83.0.4103.61 (Developer Build) (64-bit)
**Suite URL** feat/design-final-final-v2/wallet/settings/device e3b8d2591110d85a5928c796e9a51ec94557ae7b
**Device** T1 1.9.2 and 1.9.1

**Bug**
When typing in the seed, user has to click on the field to be able to enter anything in it after every seed word, focus is missing. 

**Steps to reproduce:**
**1.** Connect T1 device, load Device Settings
**2.** Run Basic recovery / Wipe and Recover wallet

**Expected result:**
Focus on the field after each seed word. 

**Actual result:**
Need to click on the field after each seed word. 

**video**  https://drive.google.com/file/d/1MClj5rhpWH7zxl0qK5n_y0Fq_S_5H0y1/view

**Comment by bosomt** [comment]
Yes.

You have to use mouse or press TAB key twice 
between every word that you enter during T1 dry run/recovery

**Comment by bosomt** [comment]
**QA OK**

works fine in web dev master branch df4e92782485d4524784eba895ef0a0d74213c63
FW 1.9.2 0x14a8da9c2830802df1474f463377669513da64fd,
Chromium 83.0.4103.116
