### ISSUE TITLE
Navigation spacing

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2076]
A few pixels more apart, please. Talked to Ondra, he approves.

<img width="385" alt="Screen Shot 2020-07-02 at 11 25 52" src="https://user-images.githubusercontent.com/29627086/86341987-4a1fdc00-bc57-11ea-9e51-a8820de3ff79.png">

**Comment by slowbackspace** [comment]
Originally the spacing between items was 24px, I'll change it to 36px.

screenshot:
<img width="1625" alt="Screenshot 2020-07-07 at 11 18 25" src="https://user-images.githubusercontent.com/6961901/86757819-b463c280-c043-11ea-8b2a-e2a3c2b764ff.png">
