### ISSUE TITLE
Disable RBF and Locktime

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2078]
Disable both toggles and input for the feature until they are implemented.

Input doesn't take any characters but still looks enabled.

<img width="466" alt="Screen Shot 2020-07-02 at 13 46 08" src="https://user-images.githubusercontent.com/29627086/86355067-64af8080-bc6a-11ea-8096-8a174fe1b8ed.png">

**Comment by vladimirvolek** [comment]
Will be enabled in a new design.
