### ISSUE TITLE
Export transactions as csv / pdf

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2080]
**[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5efc87a5cb1263131d55bd0d)**

**Comment by slowbackspace** [comment]
probably duplicate of https://github.com/trezor/trezor-suite/issues/1121

**Comment by glacierbits** [comment]
@slowbackspace right you are. Thanks
