### ISSUE TITLE
Graph: New design

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2081]
**[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5efc87a5cb1263131d55bd0d)** 

- [x] Balance line 
- [x] Bars 
- [x] Linear vs logarithmic

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite  dev web maser commit fc5e15abd6b1abfba14a82f4bf4798e9e6de1cad
Device TT fw 2.3.3 commit 0d5f00668
