### ISSUE TITLE
Dashboard: New design

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2082]
**[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/styleguide/components?seid=5ee87ee70d418aba36701f2c)** and **[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5ee8c6352150d5b8fd0344c5)**

- [x]  Table
- [x]  Headers
- [x]  Security tiles
- [x]  News

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 65
Suite dev web master commit 25d54af8358a2df77f6889a47a85f5ad83641a81
Device FW TT 2.3.3  commit 0d5f00668
