### ISSUE TITLE
Dashboard: Asset to Accounts

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2084]
Click on specific coin in the Asset table (anywhere in the full row) opens Accounts > Account filter enabled for the Coin. Related to #2083

**Comment by sorooris** [comment]
please see https://github.com/trezor/trezor-suite/issues/2083#issuecomment-688718587

**Comment by sorooris** [comment]
**QA OK**

> Wallet Version: web, 20.9.1 cf1f180
OS: NixOS
Browser: any supported (tested Firefox 79.0.1)
Device 1.9.3 0d5f00668
