### ISSUE TITLE
Export transactions

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2085]
Option to export (.csv / .pdf) transaction from the transaction history.

**[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5efc87a5cb1263131d55bd0d)**

**Comment by wendys-cats** [comment]
**QA NOK**

**Suite** web develop ac55c97
**Browser** Chromium Version 86.0.4240.111 (Official Build) (64-bit)
**System** NixOS 21.03
**Device** T1 1.9.3 public

**Expected:**
Search bar as shown in Zeplin. 

**Actual:**
There is no search transaction search bar.

**Note:**
PDF and CSV export OK.

![image](https://user-images.githubusercontent.com/58593111/100371645-65c1bf80-3008-11eb-81a3-bc5da5df9a65.png)

**Comment by glacierbits** [comment]
Title has been changed to "Export" only. Our apologies for the confusion.

**Comment by bosomt** [comment]
@matejzak is this part of design or bug ? I'm missing header of PDF file compared to mytrezor wallet

![image](https://user-images.githubusercontent.com/31506317/100609540-7460ed00-330e-11eb-8851-96600743b8ae.png)

**Comment by bosomt** [comment]
**QA OK**

i will create separate issue for pdf file header

Nixos + Firefox 82.0.3 (64-bit)
Suite web dev master commit 3cfa1ae
Device 2.3.5 model T

**Comment by rulbricht** [comment]
There seems to be some regression of this feature. When exporting ETH transactions, all ERC20 transactions are now filtered out. There does not seem to be an alternative way to export ERC20 transactions
