### ISSUE TITLE
Account details (three dots) non clickable for Ethereum account 

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#2088]
(sldev)

**Comment by slowbackspace** [comment]
@matejzak Currently we don't have any menu items (under three dots) for ethereum/ripple so I'll hide the dropdown.

<img width="999" alt="Screenshot 2020-07-07 at 10 39 48" src="https://user-images.githubusercontent.com/6961901/86750367-305b0c00-c03e-11ea-8f47-2ab7f184a179.png">

**Comment by glacierbits** [comment]
@slowbackspace ack
