### ISSUE TITLE
Sticky account cut out when scrolling

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2092]
<img width="334" alt="Screenshot 2020-07-07 at 11 29 47" src="https://user-images.githubusercontent.com/6961901/86760115-461fff80-c045-11ea-89bf-3b33e43505ea.png">

**Comment by bosomt** [comment]
**QA OK**

web suite master b739c8cb5eb507423f3a3dbb684e520a0bface72
FW 2.3.2 revison: 14a8da9
nixos
Chromium 83.0.4103.116
