### ISSUE TITLE
Arm x64 build

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2095]
As per @slush0 request.

**Comment by bosomt** [comment]
@vladimirvolek is there way to test it on our side ?

**Comment by vladimirvolek** [comment]
@bosomt Here is the build: https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/627223803/artifacts/file/Trezor%20Beta%20Wallet-20.6.1-beta.AppImage

**Comment by bosomt** [comment]
yes i know, but i thought that it's for ARM platform not for Intel :)

i tried to start it /and yes i deleted config dir/

it always crashes

nix/store/dics4rq6g5ja70pbiph4qpj52pkffhwr-appimage-exec: line 35: cd: /home/tbosansk//.cache/appimage-run/aa3b20468509c3781f3e92b2805c85e73170120caaef3c664151e20f15bee7c4//squashfs-root: No such file or directory
/nix/store/dics4rq6g5ja70pbiph4qpj52pkffhwr-appimage-exec: line 43: /home/tbosansk/.cache/appimage-run/aa3b20468509c3781f3e92b2805c85e73170120caaef3c664151e20f15bee7c4/AppRun: No such file or directory

**Comment by bosomt** [comment]
**QA NOK**

- build was already deleted
- there was some problem with app builds that was fixed already today / @mroz22 please confirm or comment please ;) /

please send new version if possible

**Comment by vladimirvolek** [comment]
@bosomt https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/641691070/artifacts/browse

**Comment by bosomt** [comment]
still same error :( on my Intel laptop running Nixos

bash-4.4$ appimage-run beta-armv7l.AppImage 
/nix/store/dics4rq6g5ja70pbiph4qpj52pkffhwr-appimage-exec: line 35: cd: /home/tbosansk//.cache/appimage-run/0dc45b0ed33990337cc51eb7209a02813facfac72773feeb65745e22842a909a//squashfs-root: No such file or directory
/nix/store/dics4rq6g5ja70pbiph4qpj52pkffhwr-appimage-exec: line 43: /home/tbosansk/.cache/appimage-run/0dc45b0ed33990337cc51eb7209a02813facfac72773feeb65745e22842a909a/AppRun: No such file or directory
