### ISSUE TITLE
Icon for not initialized device is huge

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2098]
**Info:**
 - OS:  Nix OS
 - Browser:  Firefox 77.0.1 (64-bit).
 - Wallet Version: Sutie develop, current develop (cc3829d)
 - Firmware Version: firmware master (676ac15)

**Screenshots:**

![Screenshot from 2020-07-07 10-32-00](https://user-images.githubusercontent.com/1835345/86748947-25ec4280-c03d-11ea-8f8b-45575880f015.png)

**Comment by bosomt** [comment]
**QA OK**

suite dev master commit b739c8cb5eb507423f3a3dbb684e520a0bface72
fw 1.8.3 0xdf0963ec48f01f3d07ffca556e21ff0070cab099,
nixos last update today
Chrome 0xdf0963ec48f01f3d07ffca556e21ff0070cab099,

![image](https://user-images.githubusercontent.com/31506317/87158604-4d9f0d00-c2c0-11ea-855d-18fb08573e70.png)
![image](https://user-images.githubusercontent.com/31506317/87160898-0286f900-c2c4-11ea-8f2f-d2401d3943c8.png)
