### ISSUE TITLE
Onboarding step is not centered

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#2112]
![image](https://user-images.githubusercontent.com/3112191/87023261-c24a4c80-c1d7-11ea-835b-9e6b03f48713.png)

**Comment by slowbackspace** [comment]
something something `margin: auto` was removed from modal component? :D

**Comment by mroz22** [comment]
Implementing screenshots in tests is becoming even more relevant :D

**Comment by bosomt** [comment]
**QA NOK**

Nixos + Chromium 85
Suite web dev master commit f9d6827f67e9877bbd903a05da4469578617dd74
Device 2.3.3 commit 0d5f00668

device backup dialogue

![image](https://user-images.githubusercontent.com/31506317/94564103-da29ed80-0267-11eb-948d-4a618c37996d.png)

**Comment by slowbackspace** [comment]
@bosomt closing the issue as it was for onboarding only 😝

**Comment by slowbackspace** [comment]
ohoohoh, looks like it is also fixed already!
