### ISSUE TITLE
Misaligned modal during model One onboarding

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2116]
**Info:**
 
suite dev master commit b739c8cb5eb507423f3a3dbb684e520a0bface72
fw 1.8.3 0xdf0963ec48f01f3d07ffca556e21ff0070cab099,
nixos last update today
Chrome 83.0.4103.116,
 
**Describe the bug**
Modal  that says _Follow instructions on "My Trezor" device_
Is misaligned. See video and screenshot

**Steps to reproduce:**
1. wipe device
2. start onboarding
3. create new wallet

**Expected result:**
inside of modal is aligned
**Actual result:**
inside of modal is misaligned

**Screenshots:**
video: https://www.youtube.com/watch?v=qrb5QpjGaIw&feature=youtu.be

![image](https://user-images.githubusercontent.com/31506317/87159017-ed5c9b00-c2c0-11ea-8768-1eced33d826d.png)

**Comment by vladimirvolek** [comment]
duplicated https://github.com/trezor/trezor-suite/issues/2112
