### ISSUE TITLE
Option to update a firmware during onboarding process feels like it's mandatory

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2119]
dislaimer: ...yup, I didn't actually read the gray wall of text just the heading and green button label.

I thought that by clicking "Continue" it would start the update process (it won't but I was too afraid to click on it! 😅 )
Maybe it is just me, but small copy improvement would help a lot! Eg. "Skip installing the update" or "Continue without the update" or "I pinky promise I'll install the update later" or something like that 😁 

<img width="834" alt="Screenshot 2020-07-13 at 13 30 57" src="https://user-images.githubusercontent.com/6961901/87299885-25581e00-c50d-11ea-9895-3d0ed69a3dd6.png">

**Comment by tsusanka** [comment]
I do not think this is relevant with the new onboarding anymore.
