### ISSUE TITLE
Missing redirect on page Create / Recover wallet

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2124]
**Info:**
 - **OS:** nixOS
 - **Browser:** Chromium Version 83.0.4103.61 (Developer Build) (64-bit)
 - **Wallet Version:** Wallet  branch /autolock/development (branch compatible with auto-lock feature)
 - **Firmware Version:** model 2.3.2 , revision b8127c5 
 
**Loop on Create / Recover wallet page**
When creating a new wallet, user will experience a loopy loop. Instead of being redirected into the initialized device's wallet, user is stuck on the Create / Recover wallet page. Clicking Create again will only reload this page (and console shows _{code: "Failure_UnexpectedMessage", message: "Already initialized"}_ ). Clicking Recover wallet option will warn the user that the device is already initialized. All shown on video. 

When creating a new wallet, console dosplays following error: _{code: "Failure_FirmwareError", message: "Firmware error"}_

**Steps to reproduce:**
1. Connect uninitialized device to Wallet
2. Click on Create Wallet
3. Get stuck

**Expected result:**
After creating a new wallet, user will be redirected inside their new wallet to access the accounts.

**Actual result:**
User is not redirected into initialized wallet, instead is stuck on Create / Recover wallet page.

**video:** https://drive.google.com/file/d/1Hu9ENilJ8WdHpY5kN_LGDV_39QJwU128/view

**Comment by tsusanka** [comment]
Confirming on firmware master (33d2bf4). I couldn't find bb8127c5 as @wendys-cats mentioned, but it probably does not matter.

**Comment by wendys-cats** [comment]
> Confirming on firmware master (33d2bf4). I couldn't find bb8127c5 as @wendys-cats mentioned, but it probably does not matter.

Sorry, was a misspell, it's b8127c5 and the branch is here: b8127c598388dc1249f832dc55e4074112f6e5b1, I was testing his fix for dry run with auto-lock-delay issue https://github.com/trezor/trezor-firmware/issues/1099.

**Comment by tsusanka** [comment]
@matejcik if you have a spare second could you look at this? I think it is on our side. For some reason the firmware cache raises an exception in this case.

**Comment by matejcik** [comment]
so this is a fun one: as of https://github.com/trezor/trezor-firmware/commit/a6acefbdf53ee44d973f6a92527cd1cb9cf99157, initialization includes a wipe
and wipe destroys sessions

I'm not sure what's "technically correct" behavior here.

We definitely do need to wipe caches. We technically don't need to destroy the session id; clearing the cache but keeping the id alive seems like the most simple solution, and might even be reasonable in the future with encrypted USB sessions

OTOH the simplest fix of the current problem is for the wallet to call `Initialize` instead of `GetFeatures` after a `ResetDevice` and `RecoveryDevice`. That also seems like a more correct host-side behavior.

**Comment by tsusanka** [comment]
Since changes in Wallet are somewhat troublesome I am voting for the first option: maintaining session_id over these wipes. Since we are maintaining device id I think it is reasonable to do the same with session id. If you agree, I will move this to our repo.

**Comment by tsusanka** [comment]
Thinking more about this I am not sure. Wiping the cache and leaving the session id seems somewhat against the rules we have set out ourselves. Let's discuss this on tomorrow's standup?

**Comment by tsusanka** [comment]
Just to document my findings: in Suite this does not happen, because although `GetFeatures` is also sent after `ResetDevice`, `Initialize` is being sent just after that before any `GetAddress` (or similar) is being sent.

**Comment by tsusanka** [comment]
Discussed with @mroz22 he will look at it and try to send `Initialize` after `ResetDevice` or `RecoveryDevice` is resolved.

**Comment by tsusanka** [comment]
Note: this concerns Wallet only and not Suite. I would move it to mytrezor repo but Github does not allow that (different "owner"). So let's keep it here until we fix it there.

**Comment by wendys-cats** [comment]
This issue has been tested via Asana [request](https://app.asana.com/0/1165739595414025/1185444839675255) from @tsusanka. It has been solved on 2.3.2, 1.9.x has not been affected with the bug. Full run [here](https://satoshilabs.ontestpad.com/script/134#/4/).
Tested on 2.3.1 (c6b2580cd), 2.3.2 (33d2bf4), 1.9.1 (c6b2580cd), 1.9.2 (33d2bf41) [here](https://mytrezor.corp.sldev.cz/trezor.js@9.2.1/development/) and [here](wallet.trezor.io).
