### ISSUE TITLE
Disable T1 code modal too small

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2126]
**Info:**
 - OS: nixos
 - Browser: , Chromium 83.0.4103.116
 - Wallet Version: web, commit aa77f1a1066a245a7a1fcd7d3888fc687832bb67
 - Firmware Version: 1.9.2 0xca3dd2bfb9b02cfad8077f77e680740e6de3d9e0,

**Describe the bug**
When you try to disable PIN protection and when you enter incorrect PIN code you will see modals that are too small and look strange.

**Steps to reproduce:**
1. go to Device settings
2. try disable PIN protection /screenshot 1/
3. enter invalid PIN code /screenshot 2/

**Expected result:**
Modal is not missing margins.

**Actual result:**
Modal is missing margins.

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/87318023-10d54f00-c528-11ea-886e-f78b9c91c9f9.png)
![image](https://user-images.githubusercontent.com/31506317/87318170-45e1a180-c528-11ea-9ba4-321bea8e268b.png)

**Comment by slowbackspace** [comment]
should be fixed in develop, feel free to reopen this issue if the problem persist!

**Comment by bosomt** [comment]
**QA OK**

web dev master commit https://github.com/trezor/trezor-suite/commit/c2f9617f7ea979ccf4d0a1148d2c948214f7b1cc
fw 1.9.1 0xc6b2580cd245ee924507f45e9675f857a3d78768,
latest Chrome
and latest nixos
