### ISSUE TITLE
Some links in suite are broken

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2127]
**Info:**

OS: nixos
Browser: , Chromium 83.0.4103.116
Wallet Version: web, commit aa77f1a1066a245a7a1fcd7d3888fc687832bb67
Firmware Version: 1.9.2 0xca3dd2bfb9b02cfad8077f77e680740e6de3d9e0,
 
**Describe the bug**

Some links in suite are not behaving properly, 
They look like link.
I see that they are pointing to right URL.
But they are not responding to click.

**Steps to reproduce:**
1. Go to suite
2. Click on some links that are mentioned in screenshot section
3. Observe

**Expected result:**

Links behave as links 

**Actual result:**
Nothing happens when you click on active link.

**Screenshots:**
 
**Terms & Conditions.**

![image](https://user-images.githubusercontent.com/31506317/87326875-9b6f7b80-c533-11ea-8436-e89a9569a93c.png)

**Change PIN modal**
_Learn more_

![image](https://user-images.githubusercontent.com/31506317/87327151-ff923f80-c533-11ea-9b20-59dcfcfbdd86.png)

**Dry run**
In this modal link changes checkbox _I understand this is simulated check and it won’t affect my seed_

![image](https://user-images.githubusercontent.com/31506317/87327383-4bdd7f80-c534-11ea-9a50-4c0e8adfdfdf.png)

**Comment by bosomt** [comment]
one more thing :)
see dry run link video :)
https://www.youtube.com/watch?v=AMSxtXaijzA&feature=youtu.be

suite web dev master: https://github.com/trezor/trezor-suite/commit/c2f9617f7ea979ccf4d0a1148d2c948214f7b1cc

**Comment by slowbackspace** [comment]
@bosomt could you try again? It works fine on my machine ™️
edit: Oh the issue is that clicking on the link triggers checking/unchecking checkbox. I'll create a separate issue.
