### ISSUE TITLE
Opening link in a checkbox's label triggers checking/unchecking the checkbox.

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2130]
https://www.youtube.com/watch?v=AMSxtXaijzA&feature=youtu.be

moved from https://github.com/trezor/trezor-suite/issues/2127

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite web dev master commit 4d4a9f3f493613c0a86f905414dd8071c55ac69e
Device Model T 2.3.4 commit 50854b921
