### ISSUE TITLE
Layout max width and paddings

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2139]
To match the designs we should implement different max-widths for content in dashboard and wallet/accounts.

**Comment by slowbackspace** [comment]
moved to https://github.com/trezor/trezor-suite/issues/2328

**Comment by bosomt** [comment]
**QA OK**

suite dev master, web commit fb5994a71e797046bfdf18048a763d98ba8653ff
device TT 2.3.3 commit 0d5f00668
NIXOS + Chromium 85.0.4183.83
