### ISSUE TITLE
PIN protection and passphrase says enabled even when you cancel enable dialogue

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2149]
**Info:**
 - OS: nixos
 - Browser: , Chromium 83.0.4103.116
 - Wallet Version: app/web, commit 582ebd2f9c1b733058df3e6adf70f842c7ef394d
 - Firmware Version: 1.9.1 , revision 0xc6b2580cd245ee924507f45e9675f857a3d78768,
 
**Describe the bug**

When you enable PIN protection via suite but you cancel it in device dialogue, suite says enabled.
Same behavior in web and app suite
EDIT: same behavior with passphrase enable/disable switch

**Steps to reproduce:**
1. enable PIN protection
2. press cancel on device
3. see that suite says PIN protection is enabled

**Expected result:**
PIN protection is still grey
**Actual result:**
PIN protection switch is green

**Screenshots:**
https://www.youtube.com/watch?v=INrG8T1ktKY&feature=youtu.be

**Comment by bosomt** [comment]
please consider rising priority for this issue / @mroz22 @slowbackspace @matejzak 
this issue affects auto-lock feature in recent firmware

when you try to disable or enable passphrase
you are asked to enter PIN 
when you just hit LOCK button on device  you will see error
but switch in suite changes ON/OFF or OFF/ON without changing settings of device

EDIT: checked in current staging version 44254ee8780ea1550b017621c154b2990b1fe3f0

![image](https://user-images.githubusercontent.com/31506317/89783060-9b54a280-db16-11ea-8923-47761dc0c6b3.png)

**Comment by tsusanka** [comment]
@bosomt could you please retest if this is still a thing?

**Comment by bosomt** [comment]
@tsusanka yes it is, i was able to reproduce it


**Info:**
 - Suite version: web 21.5.0 (c9d3680eb6b575f588265f541b07dd82bbd6a6ad)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.6 regular

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.7.0 (89aee5512ea0059de309935684b5be5fb3b1843b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model One 1.10.1 regular

+ 

**Info:**
 - Suite version: desktop 21.7.0 (b0ea8be015a610b83246d99a57761105259ea84f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model One 1.10.1 regular

**Comment by wendys-cats** [comment]
**QA OK**
- canceling the action results in correct behaviour (toggle no longer switches after canceling)

**Info:**
**Suite** app version 21.7.0 c6316619a13802197a5a58c0fc1f39aae18db1a7
**OS** Windows 10 Version 10.0.19042.1052
**Device** TT 2.4.0 regular
