### ISSUE TITLE
NEM wallet link outdated in suite

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2150]
**Info:**
 - OS: nixos
 - Browser: , Chromium 83.0.4103.116
 - Wallet Version: app/web, commit 582ebd2f9c1b733058df3e6adf70f842c7ef394d
 - Firmware Version: 1.9.1 , revision 0xc6b2580cd245ee924507f45e9675f857a3d78768,
 
**Describe the bug**
NEM coin wallet is linked to outdated server.
They changed it in last days. It works in web suite but it fails in app

**Steps to reproduce:**
1. add account
2. select NEM
3. click Go to external wallet

**Expected result:**
you will be forwarded to https://nemplatform.com/wallets

**Actual result:**
you are forwarded to https://nem.io/downloads/

**Comment by prusnak** [comment]
Fix in https://github.com/trezor/trezor-suite/pull/2166
