### ISSUE TITLE
Enable Suite with emulator

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2153]
Currently if someone (typically someone internal from the company) wants to run Suite with an emulator they need to run `trezord -e 21324` beforehand. That works just fine but if there is an easy way to make this even more user-friendly that would be great - we would enable this for people not so familiar with CLI (designers, management, support..).

The general idea is to add to this screen:

![Screenshot from 2020-07-21 09-06-08](https://user-images.githubusercontent.com/1835345/88023780-f0ae1d00-cb31-11ea-9491-684801c59fc3.png)

A small toggle/button that would stop the bridge and start it again with `-e 21324`. We should have this button only for BETA builds if that's easy to achieve. Another idea to achieve this is to have the button hidden - something like if you click right top corner 5x times a debug panel opens.

It seems (as @mroz22 pointed out) we could add the bridge parameters [here](https://github.com/trezor/trezor-suite/blob/8cc3650adbb123a224def6e0a024f25a8b7f5cc8/packages/suite-desktop/src-electron/bridge.ts#L74).

**Comment by matejzak** [comment]
Add Account tooltip fixed. The change is to propagate upon @slowbackspace's translation sync magic.

**Comment by slowbackspace** [comment]
> Add Account tooltip fixed. The change is to propagate upon @slowbackspace's translation sync magic.

done, will be live in ~40mins

**Comment by tsusanka** [comment]
Great job works like a charm :tada: :tada:. I have two notes:
- It seems to me it does not work on the dialog during on-boarding. Would it be too complicated to add support there as well? Not a deal breaker though.
- Could we add some notification or any other information that the five clicks were registered and the Bridge will restart? Really anything, it will help debugging imho.
