### ISSUE TITLE
Data collection: More items

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2161]
**Additional data points:** 

- [x] Operating system (easy) - in #2524
- [x] Browser language (easy) - in #2524
- [x] ~~Number of connected devices at one time~~ (easy) (yes, but..., moving to another issue) 
- [x] Run time (session length?) - For now based on Session ID – Next release
- [x] Maximazed / minimazed app (session length for each?) – Next release
- [x] Number of users (daily, weekly etc.) - Already implemented
- [x] Passphrase enabled (#, %) - Already implemented
- [x] Pin enabled (#, %) - Already implemented

**Comment by bosomt** [comment]
@matejzak 
is there anything that can be tested on our side ?

**Comment by sorooris** [comment]
@bosomt 
@mroz22 writes:
Analytics (low priority, leave it as the last one maybe):
I am going to validate it after the freeze as well, but we should take care that it never sends any data if it is disabled. 
That it works on all platforms and sends data to correct endpoints. You will probably need some tool to intercept network communication (https://www.telerik.com/fiddler) But maybe it will be easier to validate that data comes with the receiving end?
