### ISSUE TITLE
Full ERC-20 compatibility

### ISSUE THREAD

**Issue by HeroHann** [trezor/trezor-suite#2163]
**Is your feature request related to a problem? Please describe.**
I have tested the Trezor Beta Wallet the last few days after I got invited and it is WAY better than the online version of things. Updating my Trezor works like a charm. Still for ETH / ERC-20 Tokens it seems I have to leave this Wallet and connect to myEtherWallet or something else. Also let me please add my own tokens via token id.

**Describe the solution you'd like**
I would love to see the Trezor Wallet be capable to send ERC-20 Tokens and interact with smart contracts.

**Describe alternatives you've considered**
Alternatively there is only the bad old way...

**Comment by glacierbits** [comment]
@HeroHann Many thanks for your feedback! The full ERC20 support is partly in the design stage, and partly being implemented. You will be able to enjoy some of the features (specifically regarding "send") already in the next release scheduled for Sep 9.

**Comment by jerechinsky** [comment]
ERC20 implemented in v21.2.1
