### ISSUE TITLE
Import of 12 Word Seeds

### ISSUE THREAD

**Issue by HeroHann** [trezor/trezor-suite#2164]
**Is your feature request related to a problem? Please describe.**
I have tested the Trezor Beta Wallet the last few days after I got invited and it is WAY better than the online version of things.
Only thing is that it is so nice to be able to control all sorts of things while having a nice layout (at least better than electrum) that I want to be able to import my other Wallets per Seed.

I got a few other Wallet besides my Trezor just for mobile usage and smaller coins. Still I would like to be able to manage all of it from Trezor suite once I am at my pc. 

**Describe the solution you'd like**
Solution would be to allow me to "add wallet" not only a new Trezor but via my old seeds from external wallets. So I gain full fee control and other stuff for those wallets too.

**Describe alternatives you've considered**
Alternative is to use sleek Exodus but paying 5x the fee.

**Comment by mroz22** [comment]
You may load trezor with seed via trezorctl https://github.com/trezor/trezor-firmware/tree/master/python
Implementing hot-wallet without hardware device might be reconsidered in future but is not on the roadmap at the moment.

**Comment by stepmes** [comment]
Thanks @HeroHann for this input, we're noting it down and will consider it when working on future improvements.
