### ISSUE TITLE
Background of Suite not blurred in Firefox

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2165]
**Info:**
 - OS: Nixos
 - Browser: , Firefox 77.0.1 (64-bit) Chromium 84.0.4147.89
 - Wallet Version: web, b0d6438272255da85b680ecfa93954f3c10953cf
 - Firmware Version: regular-1.9.2-4eb5b927

**Describe the bug**
See screenshot. Suite behind modal in suite is not blurred in Firefox, OK in Chromium.

**Steps to reproduce:**
1. open suite in chrome
2. open suite in firefox
3. compare

**Expected result:**
uite behind modal in suite is blurred in Firefox
**Actual result:**
uite behind modal in suite is not blurred in Firefox
**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/88582475-0ef2ac00-d04f-11ea-8778-49fb9f1a9656.png)

**Comment by bosomt** [comment]
still broken ;)

Nixos
Firefox 81.0 (64-bit)
Suite.trezor.io commit 99959260d5639480dfb11e53a4f2ab1d789b0e7b
Device model T fw 2.3.4 commit 50854b921

**Comment by bosomt** [comment]
**QA NOK**

still no blur 

**Info:**
 - Suite version: web 21.3.1 (1dbc5b720515c39a47f1dc58391dbebf1d766394)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.4 regular

**Comment by slowbackspace** [comment]
> **QA NOK**
> 
> still no blur
> 
> **Info:**
> 
> * Suite version: web 21.3.1 ([1dbc5b7](https://github.com/trezor/trezor-suite/commit/1dbc5b720515c39a47f1dc58391dbebf1d766394))
> * Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
> * OS: Linux x86_64
> * Screen: 2560x1440
> * Device: model T 2.3.4 regular

😁 I guess we will wait till firefox implements this feature. Actually, it is already since v 70, but it is disabled by default. https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter#browser_compatibility

**Comment by bosomt** [comment]
looking forward, it looks really strange in Firefox when overlapping during dialogues

![image](https://user-images.githubusercontent.com/31506317/112052518-82ec4200-8b53-11eb-9025-3bf782f32930.png)

**Comment by prusnak** [comment]
> 😁 I guess we will wait till firefox implements this feature. Actually, it is already since v 70, but it is disabled by default. https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter#browser_compatibility

I confirm that setting `layout.css.backdrop-filter.enabled` to `true` in Firefox preferences (`about:config`) enables the blur.

(Firefox 86 on macOS 11)

**Comment by bosomt** [comment]
**QA NOK**

no blur in Firefox

<img width="276" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/158801784-ff3ab0db-581c-4fdd-ac78-72c33733f3ec.png">

**Info:**
 - Suite version: web 22.3.0 (3780d14cda5a50e1276643fa6302d23060fcec51)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Comment by hynek-jina** [comment]
Solution is way too complicated compared to benefit of solving it.
https://github.com/trezor/trezor-suite/pull/5063#discussion_r826962058
