### ISSUE TITLE
Missing ERC-20 tokens in Total portfolio value

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#2182]
![image](https://user-images.githubusercontent.com/3112191/89179023-2a9a0d00-d58f-11ea-9a30-8eb36bc5c84a.png)

**Comment by renekroka** [comment]
It's been almost over 1 year and still not implemented, should be very easy to do, when can we finally expect this feature to be added?

**Comment by glacierbits** [comment]
New Dashboard ~ Q4 21'
