### ISSUE TITLE
Passphrase entry behaves strangely

### ISSUE THREAD

**Issue by martinboehm** [trezor/trezor-suite#2184]
**Info:**
 - OS: macOS
 - Browser: Chrome, version 84.0.4147.105
 - Wallet Version: web
 
**Describe the bug**
Passphrase input field behaves strangely

**Steps to reproduce:**
1. Hidden wallet/Enter passphrase input field, disable character hiding
2. Enter abcde text in the passphrase field
3. Move cursor after "c", press backspace

**Expected result:**
Text abde in the input field, cursor before "d"
**Actual result:**
Text abee in the input field, cursor at the end

**Comment by jerechinsky** [comment]
Couldn't replicate it myself. @martinboehm please reopen if you still experience this.
