### ISSUE TITLE
Suite showed wallet details even though device was disconnected

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#2185]
**Info:**
 - OS: MacOs Mojave 10.14.4
 - Desktop app
 - Wallet Version: 20.7.1. beta
 - Firmware Version: T1 1.8.3
 
**Describe the bug**
I wasn't able to reproduce it, but when I opened my Mac after using it with my Trezor the previous day, I've noticed that the Trezor Suite app still shows all balances and details from my wallet. The remember mode wasn't activated. The green indicator was green as if the device was connected. When I tried to connect my device, nothing changed - the app hasn't reacted in any way, still showing my wallet's balance. First when I tried to perform some action (clicked the "add a new wallet" button), the app "woke up" and switched to the "Connect your Trezor" screen.

The screenshot shows the wallet without the device being connected. I was able to navigate to the device switch modal and back. 

<img width="1280" alt="Screenshot 2020-08-05 at 10 09 25" src="https://user-images.githubusercontent.com/54173889/89390178-a8ccef80-d706-11ea-9af0-03ace147edab.png">

**Comment by jerechinsky** [comment]
couldn't replicate after numerous attempts
