### ISSUE TITLE
Readability of firmware update changelog

### ISSUE THREAD

**Issue by LukasRada** [trezor/trezor-suite#2189]
**Is your feature request related to a problem? Please describe.**
I can't simply read changelog of firmware upgrade available.
![image](https://user-images.githubusercontent.com/7394177/89517262-bf904680-d7d9-11ea-8538-2fe4bc2299d9.png)

**Describe the solution you'd like**
Readability could be improved by putting the changelog in a list:
![image](https://user-images.githubusercontent.com/7394177/89517416-f49c9900-d7d9-11ea-9b7a-7f18d0926dd2.png)

**Comment by slowbackspace** [comment]
Thanks for filling a ~bug report~ ehh, feature request! This will be fixed soon (PR https://github.com/trezor/trezor-suite/pull/2187).

**Comment by bosomt** [comment]
**QA OK**

looks much better in 74b74b0c70658ff4cad66541441aa7274f949308
