### ISSUE TITLE
Add a "read more" link to firmware changelog during update

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2191]
The firmware update page where we include the changelog is missing a "read more on our blog" button which would direct the user to read more about the new firmware.

There are two ways to add the link imho:
- Add a field to [releases.json](https://github.com/trezor/webwallet-data/blob/4ce4129ad60a14b207cb5191b7dc578a34d0e5fc/firmware/2/releases.json) called "blog_url". Suite would take it from there.
- Add support for some basic formatting in the "changelog" field in releases.json. We could support Markdown and add the link directly into the Changelog. This would also solve also #2189.

cc @prusnak

**Comment by prusnak** [comment]
> Add a field to [releases.json](https://github.com/trezor/webwallet-data/blob/4ce4129ad60a14b207cb5191b7dc578a34d0e5fc/firmware/2/releases.json) called "blog_url". Suite would take it from there.

There was a `blog_url` field (or something very similar) in `releases.json` but I removed it, because at the time of the updating `releases.json` the blog URL is not yet known and it was missing in lots of entries (because no-one added them after the blog was published).

**Comment by tsusanka** [comment]
> Add support for some basic formatting in the "changelog" field in releases.json. We could support Markdown and add the link directly into the Changelog. This would also solve also #2189.

So maybe this is a good idea? What do you think @prusnak @mroz22 ?

**Comment by prusnak** [comment]
I don't mind it, but it does not solve the fundamental problem: the blog post is not ready yet when I update the `webwallet-data`. I think we should add one step into the release process and that is "add blogpost link to releases.json" and then other step "redeploy releases.json where it needs to be deployed".

In https://github.com/trezor/webwallet-data/commit/2263ded7f2543dfc01676f6d3d01c87a65a7f5ee I added missing blogpost links to recent firmware updates.

**Comment by tsusanka** [comment]
Ah of course. Added!

So @mroz22 you will find the blog post in releases.json in the "notes" section. I am leaving the decision about Markdown up to the Suite team then.

**Comment by mroz22** [comment]
At the moment, it looks like this: 
![image](https://user-images.githubusercontent.com/30367552/94071770-c0665180-fdf4-11ea-89c1-138cb1ed8065.png)

Current state of design looks like this: 
![image](https://user-images.githubusercontent.com/30367552/94071928-01f6fc80-fdf5-11ea-97c6-9ce650287755.png)
But I detect few issues with that: 
- Separation into fixes/features/etc is nice but how would we display changelog for other versions? At the moment we display changelog for every version that is newer. Do we really want to display only the last one? I doubt it. 
- Information about category (fix/feature) cant be deduced from releases.json at the moment. Could be done easily without breaking anything though. 
- If link to blog should become part of a record in changelog (see undrelined "interesting" in the picture), we would need to convert releases json into markdown which is breaking change.

**Comment by mroz22** [comment]
reassigning this to @matejzak 
my part is done at the moment. further work involves some coordination tasks.

**Comment by tsusanka** [comment]
Closing in favor of https://github.com/trezor/trezor-suite/issues/4161.
