### ISSUE TITLE
Firmware update workflow misses changelog when device is already in bootloader

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2192]
The update workflow works great but we did not take into account one possible course of action: the user enters the bootloader on their own (because they are experienced users already). Well that's inaccurate we have taken it into account, the workflow works just fine, but we did not consider the changelog - in this case Suite offers you a firmware update but does not include a page with the changelog. The user is then upgrading device without seeing the changelog which is unfortunate.

**Comment by mroz22** [comment]
Hm. We discussed this with @matejzak and our latest outcome was that we will force user to have device connected in normal mode at the starting screen of fw update: 

pros:
- user will see correct changelog (not possible to do this for T1 in bootloader)
- without knowing firmware version and only bootloader we don't even know whether the version we are going to install is newer than currently installed one.
- we can show warning about missing backup (and maybe forbid update in such case?)

cons:
- experienced users pissed off

**Comment by tsusanka** [comment]
Seems reasonable. I think it is an edge-case people entering Suite in bootloader.

**Comment by sorooris** [comment]
Came across a related issue today when testing the #2408 PR 

**Bug: Missing option to reinstall current firmware or install a BTC-only version (and vice-versa).**
Description: There is no option to initiate firmware install without **wiping the device** first.
Proposed solution: **display the modal with the changelog information regardless of the currently installed version when in bootloader mode**. Two redundant screens could be skipped.

Flow described below:

When connected with the device in bootloader mode the modal with information about firmware update being possible is displayed.

![image](https://user-images.githubusercontent.com/10185314/94478455-94bbe080-01d3-11eb-963e-5a326ad3b22c.png)

Selecting the _Check firmware_ button then displays a modal prompting the user to disconnect the device and connect it again in normal, non-btl mode.
![image](https://user-images.githubusercontent.com/10185314/94478756-fe3bef00-01d3-11eb-8eba-64a18f27104b.png)

After disconnecting:
![image](https://user-images.githubusercontent.com/10185314/94480074-0a28b080-01d6-11eb-862c-811eaf59d7a8.png)

Followed by the modal with changelog:
![image](https://user-images.githubusercontent.com/10185314/94480384-88855280-01d6-11eb-8e34-2063c20cae77.png)

And the seed "warning":
![image](https://user-images.githubusercontent.com/10185314/94480429-96d36e80-01d6-11eb-861e-6992c0536301.png)

To be then prompted to reconnect the device in bootloader mode.

![image](https://user-images.githubusercontent.com/10185314/94481774-8f14c980-01d8-11eb-983b-4177b140aef1.png)


Selecting the _Up-to-date_ button then displays
![image](https://user-images.githubusercontent.com/10185314/94481196-a7d0af80-01d7-11eb-895c-64a2469dea58.png)


Wallet Version: web 4ddd59a2
OS: NixOs
Browser: Chromium 85.0.4183.102
Device: model 1 1.9.2 cde8f31

**Comment by tsusanka** [comment]
Leaving this up to @matejzak but I am not sure we need to support reinstall (without wipe).

**Comment by mroz22** [comment]
This is not a bug.

**Comment by sorooris** [comment]
@mroz22 what about switching to BTC-only? Only after device wipe?
