### ISSUE TITLE
Send dialogue to bech32 uppercase address ends with error

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2193]
**Info:**
 - OS: Mint Linux and Nixos
 - Browser: , Chrome and Linux app
 - Wallet Version: web, commit 17ab12b7275eb83ded72c590328d371e6132ec69 + freeze app 44254ee8780ea1550b017621c154b2990b1fe3f0
 - Firmware Version: 2.3.2 63ebb8ccb
 
**Describe the bug**
Suite accepts uppercase BTC bech32 address /example: BC1Q60SYZAPRX43TYH6FHP4WXTA4N78SCZDRXD26NJ /
But it ends with error and device soft freezes during Sign transaction dialogue.
MyTrezor wallet solves this by auto converting it to lowercase. But suite accepts it and fails after you hit send button 

**Steps to reproduce:**
1. load BTC accounts
2. use uppercase address for example BC1Q60SYZAPRX43TYH6FHP4WXTA4N78SCZDRXD26NJ in send dialogue
3. suite accepts it but fails at the end during Signing via device

**Expected result:**
Address is refused or converted

**Actual result:**
Sign transaction error: Invalid address

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/89527821-48af7980-d7ea-11ea-8aca-6f9e4692c62a.png)

**Comment by prusnak** [comment]
The device expects lowercase letters of bech32 addresses. 

There are several options how to deal with this:
a) refuse the address - not ideal UX
b) convert the address automatically - also not very ideal and might be confusing
c) convert the address to lowercase and show the information (over or under the address) that the address has been converted to lowercase
d) show the dialog informing that the address needs to be converted and convert after users confirms the operation

I think C is the best of the options, but D might be also OK

**Comment by szymonlesisz** [comment]
i did variant "d"

![Screenshot 2020-10-28 at 17 14 03](https://user-images.githubusercontent.com/3435913/97468243-584fe180-1945-11eb-9ff6-f05411c39225.png)
![Screenshot 2020-10-28 at 17 42 53](https://user-images.githubusercontent.com/3435913/97468262-5dad2c00-1945-11eb-823a-2c8254654589.png)

**Comment by bosomt** [comment]
**QA OK**

very nice solution, tested with standard,segwit and legacy accounts

Nixos + Chromium 86.0.4240.111
suite dev web master commit fd905e582511d130cc5611bc32729ad2d3b9db18
Device model T firmware 2.3.3 commit 0d5f00668
