### ISSUE TITLE
Storybook for react-native

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#22]
https://storybook.js.org/docs/guides/guide-react-native/

**Comment by slowbackspace** [comment]
I tried integrating native storybook to an app created by `react-native init` (with nohoist setting for whole package). Thanks to yarn workspaces the storybook's node_modules contained symlink to @trezor/components and of course metro bundler can't work with symlinks ([workaround]( https://medium.com/@slavik_210/symlinks-on-react-native-ae73ed63e4a7)). But still there are some weird issues. (eg. with `core-js` lib https://github.com/storybookjs/storybook/issues/6984). We should just wait few weeks until everything's fixed.

**Comment by vladimirvolek** [comment]
We don't need this now.
