### ISSUE TITLE
Receive dialogue identifies device as disconnected when you press lock button when auto-locked 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2200]
**Info:**
 - OS: Nixos
 - Browser: , version
 - Wallet Version: web, commit 44254ee8780ea1550b017621c154b2990b1fe3f0
 - Firmware Version: 2.3.2 , revision  63ebb8ccb
 
**Describe the bug**
Receive dialogue identifies device as disconnected and passphrase disabled
when you press lock button when auto-locked and asked to unlock it to see/confirm receive address

**Steps to reproduce:**
1. load suite accounts with TT and autolock feature enabled
2. wait till it's autlocked and press Show full address
3. You are asked to unlock it and you press LOCK button
4. Observe suite status

**Expected result:**
You are asked to unlock device one more time or to close Address modal

**Actual result:**
Suite acts like deice is disconnected

**Screenshots:**
Modal after you press show for second time
![image](https://user-images.githubusercontent.com/31506317/89809414-cef5f380-db3b-11ea-9561-f48e4b76e389.png)

Status of device in Receive tab
![image](https://user-images.githubusercontent.com/31506317/89809440-d87f5b80-db3b-11ea-9291-301214828f13.png)

Wallet selector, you can see that device is still connected 
![image](https://user-images.githubusercontent.com/31506317/89809470-e1702d00-db3b-11ea-9338-81be53535836.png)

**Comment by szymonlesisz** [comment]
this should be fixed together with:
https://github.com/trezor/trezor-suite/issues/2231

**Comment by bosomt** [comment]
**QA OK**

OS Nixos
Browser Chromium 85.0.4183.83
Commit web + app 7fd6a0ebf428e995e28b98e792d1b429151fb6a2
FW 2.3.3 0d5f00668

Locked device is correctly detected and I don't see any **unavailable** or **Enable passphrase** info
