### ISSUE TITLE
The new design of Confirm address Modal

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#2201]
The old one.

![image](https://user-images.githubusercontent.com/3112191/89876564-1e313800-dbbf-11ea-9edf-2f15ade912fb.png)

The new design is missing QR code, path, and crypto symbol.

![image](https://user-images.githubusercontent.com/3112191/89876673-428d1480-dbbf-11ea-95c0-bdc5078d2b01.png)

**Comment by glacierbits** [comment]
Duplicate #2214
