### ISSUE TITLE
Inconsistent amounts in Send form 

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2204]
**Info:**
 - OS: nixos
 - Browser: Chromium Version 83.0.4103.61 (Developer Build) (64-bit)
 - Suite Version: web, commit 44254ee8780ea1550b017621c154b2990b1fe3f0
 - Firmware Version: 2.3.2 model , revision 63ebb8ccb
 
**Describe the bug**
Probably inconsistent rounding off in Send form and Confirm transaction form due to "Send max" option. The FIAT send amount was different in these two forms (see GIF links below). 

**Steps to reproduce:**
1. Open Send form
2. Chose Send max

**Expected result:**
The Send amount should always stay the same.

**Actual result:**
Send amount (in FIAT) can differ in Send form and Confirm transaction form

**Screenshots:**
[here](https://drive.google.com/file/d/1QqJrStxrxqv8lu9DYinsZs_UzKCoAvAB/view?usp=sharing) and [here](https://drive.google.com/file/d/1hKPKixuRBE4HtU1-QhXhRVGPKAhxsAcm/view?usp=sharing) (both gifs are over 10MB)

**Comment by szymonlesisz** [comment]
this is probably fixed by a new send-form

**Comment by sorooris** [comment]
**QA OK**
> Wallet Version: web, 20.9.1 cf1f180
OS: NixOS
Browser: any supported (tested Firefox 79.0.1)
Device 1.9.3 0d5f00668

Suite amounts (in the foreground and background) | Device
--- | ---
![image](https://user-images.githubusercontent.com/10185314/92499544-4cc12380-f1fc-11ea-812f-e2d69a4d40be.png) | ![image](https://user-images.githubusercontent.com/10185314/92499659-6bbfb580-f1fc-11ea-8ce6-a0ecc673a6a5.png)
