### ISSUE TITLE
Landing Page - old screenshot

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#2206]
![image](https://user-images.githubusercontent.com/3112191/89991606-5d758c80-dc84-11ea-902b-ff1e47456c9a.png)

**Comment by bosomt** [comment]
was it merged already ?

current **commit**: e243afdb73e35fa08f39a7fc08a28b84baa3ac58

current status:

![image](https://user-images.githubusercontent.com/31506317/92732959-6a66c800-f377-11ea-90a7-96591fe3abff.png)

**Comment by keraf** [comment]
@bosomt CI was fudged (because of me), should be deployed now. Clear your cache if it still shows the old screenshot.

**Comment by bosomt** [comment]
**QA OK**

suite dev master, web commit fb5994a71e797046bfdf18048a763d98ba8653ff
device TT 2.3.3 commit 0d5f00668
NIXOS + Chromium 85.0.4183.83
