### ISSUE TITLE
Cannot read data from Graph tooltip in Discreet mode

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2207]
**Info:**
 - OS: nixos
 - Browser: Chromium Version 83.0.4103.61 (Developer Build) (64-bit)
 - Wallet Suite web commit dd8d24fc3a542e23c13bb0321f45696abbf05839
 - Firmware Version: 2.3.2 63ebb8ccb
 
**Describe the bug**
Happens BOTH in Accounts and Dashboard pages. 
When Discreet mode is applied, user cannot read data from graph. Upon mouse hover on a Graph section, a small tooltip with appear, holding info about Sent and Received amounts of sectioned date. This information is blurred out. User cannot hover over tooltip, and has to disable dicreet mode to read info from the graph.

**Steps to reproduce:**
1. Open account with TX history
2. Apply discreet mode
3. Hover over a specific date/column in Graph (either in Accounts, or Dashboard)

**Expected result:**
Graph will be readable (does happen) and the appeared tooltip with data will also be readable.

**Actual result:**
Tooltip with additional info about the specific date is blurred out.

                                          Screenshots

![image](https://user-images.githubusercontent.com/58593111/90000007-e3e39b80-dc8f-11ea-910c-c0f7b5002322.png)

**Comment by slowbackspace** [comment]
@matejzak I would let this pass and fix it in the next release. Is that ok with you?

**Comment by prusnak** [comment]
Is this really a bug? From my perspective, the Discreet mode is behaving exactly as it should.

**Comment by wendys-cats** [comment]
@prusnak the thing is, Discreet mode should reveal information when you hover over said data. And you cannot hover over a tooltip, so you are not able to reveal its data - as it is right now, this tooltip for Graph data is obsolete in Discreet mode.

**Comment by glacierbits** [comment]
> @matejzak I would let this pass and fix it in the next release. Is that ok with you?

@slowbackspace we are at "the next release" now. Please have a look at it. Thanks!

**Comment by glacierbits** [comment]
Is there any easy solution to this @slowbackspace ?

**Comment by bosomt** [comment]
**QA OK**

OS: Nixos + Chromium 65
Suite: dev web master commit f9d6827f67e9877bbd903a05da4469578617dd74
FW: 1.9.2 commit 0xcde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea,
