### ISSUE TITLE
Anchor link to pending TX

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2208]
Send TX > Snack bar notif  / Activity panel > View details > Anchor link to pending TX 

..if supported by electron apps. 🤷

**Comment by jerechinsky** [comment]
Seb also summarized the issue from his point of view in #3613

**Comment by goodhoko** [comment]
For future reference when we'll get to this: this feature (link that can focus on a particular part of a page) [could be also used](https://github.com/trezor/trezor-suite/issues/2282#issuecomment-827741661) in the safety checks warning banner.

**Comment by glacierbits** [comment]
Closing in favor of #3889
