### ISSUE TITLE
Amount tip still contains temporal placeholder

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2210]
**Info:**
 - OS: Nixos
 - Browser: , xxx
 - Wallet Version: app, commit 74b74b0c70658ff4cad66541441aa7274f949308
 - Firmware Version: model 1.9.2  , revision 0xcde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea
 
**Describe the bug**
Amount tool-tip says:

TR_SEND_AMOUNT_TOOLTIP

**Steps to reproduce:**
1. load wallet
2. go to send dialogoue
3. hover over ? next to Amount field

**Expected result:**
Text that says that this is field in coins value
**Actual result:**
Contains placeholder

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/90098302-37112900-dd38-11ea-8046-bdadbfb6fdda.png)

**Comment by bosomt** [comment]
and when on it can you pelase change this to something more user friendly ?

![image](https://user-images.githubusercontent.com/31506317/90108334-6e88d100-dd4a-11ea-97cc-388c632e7c8f.png)

**Comment by slowbackspace** [comment]
@matejzak the ID for the message is `MODAL_ADD_ACCOUNT_LIMIT_EXCEEDED` pls update the copy. I'll delete the tooltip for amount field.

**Comment by bosomt** [comment]
same result in current dev master that's 5 hours old
commit 5e63937356f4dc5c806560e74f6c926ec156f840

![image](https://user-images.githubusercontent.com/31506317/90287978-39c76780-de79-11ea-9861-448166eb235c.png)

**Comment by glacierbits** [comment]
Add Account tooltip fixed. The change is going to propagate upon @slowbackspace's translation sync magic.

**Comment by slowbackspace** [comment]
> Add Account tooltip fixed. The change is going to propagate upon @slowbackspace's translation sync magic.

done, will be live in ~30 mins

**Comment by bosomt** [comment]
**QA OK**

commit ef26a1e262d97c3c30694a8ce6aff89481756dcd
current dev master
