### ISSUE TITLE
Custom coin back-end

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2212]
Design: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f32b54058d6451e30bd74da)

**Comment by bosomt** [comment]
**QA OK**
/looks and works great guys !/

suite dev master, web commit fb5994a71e797046bfdf18048a763d98ba8653ff
device TT 2.3.3 commit 0d5f00668
NIXOS + Chromium 85.0.4183.83

**Comment by w7xx** [comment]
> Design: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f32b54058d6451e30bd74da)
Zeplin is invite-only.. may I request one ?
