### ISSUE TITLE
Labeling: Overflow

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2213]

**Comment by sorooris** [comment]
**QA NOK**

Wallet: Suite develop d54381f280e3219a9383dbd4543fb1d89763d7a5
Device: model T

@mroz22 A long character string overflows over to the right and displays a horizontal scrollbar in browser:

> ![image](https://user-images.githubusercontent.com/10185314/91460644-55266f80-e888-11ea-8c0d-d32b4eb87b9c.png)

Compared to the old Wallet where instead of displaying the string an ellipsis is displayed:

> ![image](https://user-images.githubusercontent.com/10185314/91461354-2bba1380-e889-11ea-992b-630a2c1c51d8.png)

**Comment by sorooris** [comment]
@mroz22 improvement proposal - let users edit account names in the sidebar and not only in the AppNavigationPanel
![image](https://user-images.githubusercontent.com/10185314/91468473-5bb9e480-e892-11ea-96c0-1eb60d14833d.png)

**Comment by mroz22** [comment]
> @mroz22 improvement proposa 

discussed with ondra (desing) and he suggested to do it as it is.

**Comment by sorooris** [comment]
@mroz22 even with the text overflow?

> **QA NOK**
> 
> Wallet: Suite develop [d54381f](https://github.com/trezor/trezor-suite/commit/d54381f280e3219a9383dbd4543fb1d89763d7a5)
> Device: model T
> 
> @mroz22 A long character string overflows over to the right and displays a horizontal scrollbar in browser:
> 
> > ![image](https://user-images.githubusercontent.com/10185314/91460644-55266f80-e888-11ea-8c0d-d32b4eb87b9c.png)
> 
> Compared to the old Wallet where instead of displaying the string an ellipsis is displayed:
> 
> > ![image](https://user-images.githubusercontent.com/10185314/91461354-2bba1380-e889-11ea-992b-630a2c1c51d8.png)

**Comment by glacierbits** [comment]
Text overflow to be fixed by #2283
