### ISSUE TITLE
Components: Update dropdown

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2216]
<img width="151" alt="Screen Shot 2020-08-13 at 14 22 09" src="https://user-images.githubusercontent.com/29627086/90133796-60e64200-dd70-11ea-9e0f-ac3b0dbf3bfd.png">

**Comment by bosomt** [comment]
**QA OK**

works fine now in a8438ad

OS Nixos
BR Chromium 84.0.4147.135
FW 1.9.3 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8
