### ISSUE TITLE
Graph: Enhancements

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2217]
- [x] Both Dashboard and Account: Padding on the segmented control (Graph view: Linear / Logarithmic) [as designed](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5efc87a5cb1263131d55bd0d) + Remove the refresh button in Account graph
 

<img width="249" alt="Screen Shot 2020-09-02 at 17 59 13" src="https://user-images.githubusercontent.com/29627086/92007279-05431f00-ed46-11ea-8f8f-016a02ce09c8.png">

- [x] Graph ALL view: For consistency sake, let's use label format (e.g.) _Feb 2020_ instead of 02/2020 

<img width="1009" alt="Screen Shot 2020-09-02 at 18 03 31" src="https://user-images.githubusercontent.com/29627086/92007759-9f0acc00-ed46-11ea-9fb8-819c9b18eaec.png">

- [x] Similarly, use the same format (e.g.) _Feb 9, 2020_ in the summary box below the graph

<img width="341" alt="Screen Shot 2020-09-02 at 18 06 38" src="https://user-images.githubusercontent.com/29627086/92008149-0fb1e880-ed47-11ea-88c0-aff4c6f887cc.png">

- [x] Set the border radius to 0 at the bottom of the bar ([as designed](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/styleguide/components?seid=5ee87f2e6c4f4fb8451b768c)) 

- [x] Labels refactor: Do not rotate the labels to 90° ([as designed](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/styleguide/components?seid=5ee87f2e6c4f4fb8451b768c)) 

- [x] Populate only spread-enough granularity of the dates for the given resolution (e.g. max 7 per the given range and suitable resolution) so that the labels can reside in the not-rotated position. Rationale: (1) Example 1M: Labels are too crowded and cause confusion (2) Tooltip shows the exact date anyway (3) The rotated position doesn't help with readability

 

- [x] Remove the orange dot on the balance line (it will collide with bars once they are put together)

- [x] Let the tooltip "picker" move on all the data points within the selected range regardless of whether there are txs or not 

- [x] Do not populate a fall back "No tx to show" when there are no tx within the selected range (see point above)

- [x] Add non-numeral (_Jan, Feb etc._) labels for 1Y range

- [x] Remove gap between bars _(I added it for ya)_

**Comment by slowbackspace** [comment]
> * [ ]  Do not populate a fall back "No tx to show" when there are no tx within the selected range (see point above)
 
~I don't see the relation to the point above, but what do you expect to see on Y axis (what the amount range should be) in this case? Also what date range do you expect on X axis in "all" view when there are no txs?~

RESOLVED

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite  dev web master commit 3a9fd795a1b8da8223faa29aaac2aa842a22d262
Device T1 fw 1.9.2 commit 0xcde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea,
