### ISSUE TITLE
Responsive account menu stays opened after "add new account" action

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#2220]
**Expected result:**
should be closed

**Comment by sorooris** [comment]
**QA OK**
> Wallet Version: web, 20.9.1 cf1f180
OS: NixOS
Browser: any supported (tested Firefox 79.0.1)
Device 1.9.3 0d5f00668

Selecting the Add account button closes correctly and opens the newly created account's tx screen.
