### ISSUE TITLE
Incorrect line height: My portfolio on Dashboard

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2222]
Should be 1px (to match the asset table).

<img width="218" alt="Screen Shot 2020-08-14 at 16 39 24" src="https://user-images.githubusercontent.com/29627086/90261145-daebf900-de4c-11ea-8354-6a6764b8010b.png">

**Comment by sorooris** [comment]
**QA OK**

> Wallet Version: web, 20.9.1 cf1f180
OS: NixOS
Browser: any supported (tested Firefox 79.0.1)
Device 1.9.3 0d5f00668
