### ISSUE TITLE
components/Dropdown item "isHidden" doesnt work

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#2224]
items.options = [ { ..., isHidden: true} ]

+ there is no knob for that in storybook

**Comment by szymonlesisz** [comment]
https://github.com/trezor/trezor-suite/blob/develop/packages/components/src/components/Dropdown/index.tsx#L194

~~should be `visibleItems. options`, no?~~

EDIT: no it's something different

**Comment by szymonlesisz** [comment]
i've found solution in send-form branch, @slowbackspace pls update your branch witch the change from https://github.com/trezor/trezor-suite/commit/5b962362babbc91fa79e837c88d5adb788f1d499

**Comment by slowbackspace** [comment]
oh, it is already fixed in https://github.com/trezor/trezor-suite/pull/2229, just not merged yet.
