### ISSUE TITLE
Incorrect illustration

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2227]
There is nothing to confirm on device in this case.

I suggest using this illustration instead: **[Zeplin](https://zpl.io/VQ7jkeR)**

<img width="507" alt="Screen Shot 2020-08-11 at 09 50 15" src="https://user-images.githubusercontent.com/29627086/90505285-a335c780-e152-11ea-899b-4bba850ca909.png">

**Comment by bosomt** [comment]
**QA OK**

looks OK

![image](https://user-images.githubusercontent.com/31506317/93786015-14bfd480-fc2f-11ea-94ee-b9846dca8d5b.png)


Nixos + Chromium 85
FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
Suite web dev master c67a173aabdb7e5b4ea7a2de478707e96a27ced4
