### ISSUE TITLE
updateRequired in Browser detection is broken

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#2230]
This code does not behave correctly on Firefox 68 - it is identified as a browser that needs update. Because the version is picked wrongly from the Chrome version defined in the `supportedBrowsers`.

https://github.com/trezor/trezor-suite/blob/ef26a1e262d97c3c30694a8ce6aff89481756dcd/packages/suite-data/files/browser-detection/index.js#L56-L61

**Comment by sorooris** [comment]
@prusnak @slowbackspace what is the minimum required browser version for both Chrome and Firefox? I could test this with browserstack if the older browser versions are available.

**Comment by prusnak** [comment]
Checked OK.

@sorooris current check is like this:

desktop: Firefox `>= 62` ; Chrome/Chromium `>= 69`
mobile: Firefox :no_entry: ; Chrome/Chromium `>= 69`
