### ISSUE TITLE
Enable passphrase with autolock

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2231]
### **Steps to reproduce:**

Device autolocks: Device display "Locked" > 

Context notification in Account: "Change passphrase Settings to use this device" > 

CTA from context notification "Enable passphrase" > 

Device display: "Enter your PIN" >

Device display: "Do you really want to enable passphrase encryption? 
..even though passphrase has already been globally enabled to begin with.

Yes / No on Device results in the same passphrase state: It's still enabled. 

<img width="1104" alt="Screen Shot 2020-08-19 at 16 04 39" src="https://user-images.githubusercontent.com/29627086/90645084-d1400800-e235-11ea-9c63-2f0445dab634.png">

**Comment by bosomt** [comment]
**QA OK**

OS Nixos
Browser Chromium 85.0.4183.83
Commit web + app 7fd6a0ebf428e995e28b98e792d1b429151fb6a2
FW 2.3.3 0d5f00668

Locked device is correctly detected and I don't see any **unavailable** or **Enable passphrase** info

**Comment by sorooris** [comment]
**QA OK**

> Wallet Version: web, 20.9.1 e243afdb73e35fa08f39a7fc08a28b84baa3ac58
OS: NixOS
Browser: any supported (tested Firefox 79.0)
Device: Model T 2.3.3 0d5f00668

No irrelevant error message toasts are displayed.
