### ISSUE TITLE
Remove "could not retrieve data" (XRP in Dashboard graph)

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2233]
Portfolio balance includes XRP (graphs bars don't - not much we can do here because XRP). 

Please remove the "scary" sentence. In case of BE disconnected, user will be informed in the respective Asset row.

<img width="252" alt="Screen Shot 2020-08-20 at 15 38 50" src="https://user-images.githubusercontent.com/29627086/90777231-68bb5e80-e2fb-11ea-8708-704b435cc3c9.png">

**Comment by sorooris** [comment]
The "scary sentence" is not displayed, but there's no info for the user about data not being present in the graph, is it correct?

> Wallet Version: web, 20.9.1 cf1f180
OS: NixOS
Browser: any supported (tested Firefox 79.0)
Device: Model 1 1.9.3 0d5f00668

**Comment by glacierbits** [comment]
#2346 will fix this. Also we are designing better "tooltips" (all kind of previews of topics for better user onboarding to certain features). ETA Q4.
