### ISSUE TITLE
Remove "Cancel" button from Add account modal

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2237]
Rationale: It is not consistent with other "cancelable" modals 

User has 2 other options: To click outside of the modal or on the top right cross. 
Note: Add Account design will likely going to improve, so this is just an intermediate fix.

- [ ] Remove the secondary cancel button 

- [ ] Center the primary button

**Comment by bosomt** [comment]
**QA OK**

Suite dev master commit 0157226
Nixos + Chromium
Devicve fw 2.3.4 commit 55baf3a
