### ISSUE TITLE
FW update bootloader mode: Update illustration and copy

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2238]
_(#2323 is a prerequisite)_

The illustration (nor text) do say how to enter the bootloader mode. While the second step (when user disconnects the device) is sufficiently informative, the first is not (see screenshots). Please fix it.

Model T: [Zeplin](https://zpl.io/25DOOvn) 
Model One: [Zeplin](https://zpl.io/aNJPP89) 

<img width="500" alt="Screen Shot 2020-08-21 at 15 18 15" src="https://user-images.githubusercontent.com/29627086/90895236-214bd580-e3c2-11ea-95b9-78dc4a517976.png">

<img width="500" alt="Screen Shot 2020-08-21 at 15 24 36" src="https://user-images.githubusercontent.com/29627086/90895439-738cf680-e3c2-11ea-8d01-340f04ac8e1b.png">

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev web master commit 3a9fd795a1b8da8223faa29aaac2aa842a22d262
Device T1 FW 1.9.2 commit 0xcde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea,
