### ISSUE TITLE
Remove "BTC only FW" from FW update wizard

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2239]
Rationale: 

- We believe this relates to only a relatively small number of our users.
- Checked with FW team: It was always suppose to be trezorctl feature 

Note: Option to install custom_firmware is on the roadmap.

![89519663-059ad980-d7dd-11ea-8aff-68728a79e7c9](https://user-images.githubusercontent.com/29627086/90907406-3846f380-e3d3-11ea-9b13-9415fc04065f.png)

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev web master a6bf817b6111a0b31bf947ecca01522dac06441a
Device T1 FW 1.9.2 commit 0xcde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea,
