### ISSUE TITLE
CTA on backup failed notification

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2240]
Change the CTA on backup failed notification to "Continue" as a terciary button with link to Settings > Device.

<img width="1440" alt="Screen Shot 2020-08-21 at 17 41 19" src="https://user-images.githubusercontent.com/29627086/90909314-ddfb6200-e3d5-11ea-86fc-8cc7b87e5a30.png">

**Comment by sorooris** [comment]
**QA OK**

CTA includes a terciary _Continue_ button that redirects _Settings_ -> _Device_ correctly.

> Suite: app 20.10.1 a263552
> OS: Windows 10
> Device: model T 2.3.3 0d5f00668
