### ISSUE TITLE
Backup failed: Settings

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2241]
Remove the whole 2nd section (text + secondary button + divider line). 

Instead, create custom translation for the case of failed backup with the small "Learn more" button (as is). 

<img width="1009" alt="Screen Shot 2020-08-21 at 17 44 22" src="https://user-images.githubusercontent.com/29627086/90909404-fcf9f400-e3d5-11ea-9c04-385884d1b233.png">

**Comment by mroz22** [comment]
@robertbrada I have just assigned you. I am not trying to slip away from this, just in case you were looking for something quick to do :]

**Comment by mroz22** [comment]
backup not created yet

![image](https://user-images.githubusercontent.com/30367552/94336309-82c71b80-ffe2-11ea-85ce-733fee7da755.png)

success state 
![image](https://user-images.githubusercontent.com/30367552/94336547-5ca27b00-ffe4-11ea-83f5-043239527412.png)

failed 
![image](https://user-images.githubusercontent.com/30367552/94336636-e9e5cf80-ffe4-11ea-9c95-56cda5fe39dd.png)

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite web dev master commit f9d6827f67e9877bbd903a05da4469578617dd74
Device 2.3.3 commit 0d5f00668
