### ISSUE TITLE
Add option to settings to allow safety checks

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2242]
This setting introduced in https://github.com/trezor/trezor-firmware/pull/1126 enables Trezor to perform some actions that are unusual and might be dangerous in some circumstances. There are still some legitimate use-cases for this though such as when you send BTC coins to LTC address etc.

<s>We also should solve the naming and description for this setting first, see https://github.com/trezor/trezor-firmware/issues/1133.</s>

Blocks https://github.com/trezor/trezor-firmware/pull/1197. 

**Design:** [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/6048a92abfb8c20510f22b74)

**Comment by tsusanka** [comment]
Safety check levels are:

- "strict" to get the full Trezor security (default)
- "prompt" if you want to be able to allow potentially unsafe actions, such as mismatching coin keys or extreme fees. The user is prompted about the operation before it happens. This setting is removed after Trezor reboot.

There is also "prompt_always" but that's a very advanced and we do not want that in Suite yet.

**Comment by tsusanka** [comment]
Makes sense to do along with https://github.com/trezor/trezor-suite/issues/2282.

**Comment by tsusanka** [comment]
Some work in `tsusanka/safety-checks` but I need some help with that.

**Comment by glacierbits** [comment]
FYI I have added the design to the issues descrition. 👆🏽 

Let's please add the Safety checks modal (via secondary button) in the Security section (below passphrase).

<img width="1106" alt="Screen Shot 2021-03-12 at 11 04 04" src="https://user-images.githubusercontent.com/29627086/110924720-abd63100-8322-11eb-8a64-a3a05c0cd887.png">

**Comment by glacierbits** [comment]
FYI 2: Settings "item" is designed & [in Zeplin here.](https://zpl.io/297wlmz)

**Comment by goodhoko** [comment]
For me, TODO:
- [x] e2e tests
- [x] UI polish
- [x] translations
- [x] release connect (https://github.com/trezor/connect/pull/785)
- [x] changelog

**Comment by goodhoko** [comment]
Done.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.6 regular

**Comment by wendys-cats** [comment]
**QA OK**
- Safety checks is available in Settings
- can be changed from Settings
- shows notification when safety checks are disabled

**Info:**

- Suite version: web 21.5.1 (4d09d88)
- Browser: Chromium Version 88.0.4324.182 (Official Build) (64-bit)
- OS: nixOS 21.03
- Device: model T 2.3.6 public

**Comment by STew790** [comment]
QA OK

Info:

Suite version: web 21.5.1 (4d09d88)
Browser:  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
OS: NixOS
Device: model T 2.3.5 regular
