### ISSUE TITLE
Metadata #3 (anytime later)

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#2243]
- [ ] logic: ERC20 transfer labeling (missing outputIndex)
- [ ] logic: DropboxProvider differentiate exception states (errors/full ...) 
- [x] logic: UserDataProvider - saving data localy on desktop
- [ ] test/e2e: mock discovery for test not testing it. It is significant slowdown. https://github.com/trezor/trezor-suite/issues/1759
- [ ] UI: modal for provider (two steps, depends on UserDataProvider)
- [ ] UI: extra long labels, they should wrap,be hidden or what?
- [ ] logic: better oauth implementation, started here https://github.com/trezor/trezor-suite/commit/39164e1f68f1b48970b0e2bc9e17ee8c39646640

**Comment by hynek-jina** [comment]
Feel free to reopen if needed, but this issue didn't move anyhow for a long time..
