### ISSUE TITLE
Metadata #2 (before freeze)

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#2244]
- [x] oauth file for desktop. PR in mytrezor is here: https://github.com/satoshilabs/mytrezor/pull/948/files 
- [x] remove all herokuapp remnants and use https://wallet.trezor.io/oauth_receiver.html instead 
- [x] Dropbox clientId
- [x] Google clientId 

### Dropbox and Google provider setup
- For dropbox we use clientId: `wg0yz2pbgjyhoda` (from mytrezor)
- For google we probably need to setup a new one? 

redirect urls to be added:
- `http://localhost:3000/static/oauth/oauth_receiver.html`
- `https://suite.corp.sldev.cz/suite-web/develop/wallet/static/oauth/oauth_receiver.html`
- `https://staging-wallet.trezor.io/wallet/static/oauth/oauth_receiver.html`
- `https://beta-wallet.trezor.io/wallet/static/oauth/oauth_receiver.html`
- `https://wallet.trezor.io/wallet/static/oauth/oauth_receiver.html`

also don't forget please to domains to authorized javascript origins:
- `http://localhost:3000`
- `https://wallet.trezor.io` 
- `https://beta-wallet.trezor.io` 
- `https://staging-wallet.trezor.io`
- `https://suite.corp.sldev.cz`

**Comment by bosomt** [comment]
**QA NOK**

when i try to connect Google error it fails, url suite.corp.sldev.cz

Nixos + Chromium 85
FW TT 2.3.3 0d5f00668
suite dev master commit 02b68e9900858ce723fccb62d8810c3bb425effc

![image](https://user-images.githubusercontent.com/31506317/93499805-bc799180-f913-11ea-9f5e-af3b9766cd9a.png)

**Comment by prusnak** [comment]
> when i try to connect Google error it fails, url suite.corp.sldev.cz

I added `suite.corp.sldev.cz` to the allowlist. If there are any issues with that, please test also https://staging-wallet.trezor.io where the Google Drive integration is also enabled.

**Comment by bosomt** [comment]
it says google and not Google

![image](https://user-images.githubusercontent.com/31506317/93661159-e935c200-fa55-11ea-9380-5cea95daceae.png)

**Comment by bosomt** [comment]
**QA OK**

https://suite.corp.sldev.cz/ and https://staging-wallet.trezor.io/ are working fine

OS and browser: Nixos + Chromium 85.0.4183.83
FW 1.9.3 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
Suite web 4cd30a71080c193d88cb69db4776dbec17027ae1 + 02b68e9900858ce723fccb62d8810c3bb425effc
