### ISSUE TITLE
remove duplicated AccountUtils

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#2245]
- formatAmount & amountToSatoshi
- formatNetworkAmount & networkAmountToSatoshi
https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/utils/wallet/accountUtils.ts#L135-L176

**Comment by dahaca** [comment]
@szymonlesisz Could you specify why they are duplicated?  `formatAmount` essentially formats from satoshis, `amountToSatoshi` – to satoshis, same with `networkAmountToSatoshi` and `formatNetworkAmount`. As far as I understood they have different use cases.

**Comment by szymonlesisz** [comment]
i believe this is solved already
