### ISSUE TITLE
Input/Select/button size and styles

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2248]
- Currently we have implement 2 input/select sizes: default (48px height), small (32px height). 
According to our designs we should have 42px button and 48px for input/select 🤷 

- it appears we still haven't update the colors (text color, bg, borders, etc...) for input (presumably Textarea, Select too)

todo:
- check with the designer and decide on common height for all these elements
- implement the changes and check what got broken

**Comment by AlexARNcode** [comment]
Hi, do you need somebody to do it for you, once you have the necessary info to implement it ? I'm looking to contribute for a project :).

**Comment by ravinalamada** [comment]
@matejzak, Could you tell me where I can find the designs for this issue?
