### ISSUE TITLE
3 dots menu in Account won't open

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2258]
Click on the 3 dots menu in Account won't do anything.

**Comment by slowbackspace** [comment]
It was already fixed, waiting for sluggish CI to deploy it. You are just too eager to find broken things! 😀

**Comment by bosomt** [comment]
QA OK

works fine now in a8438ad

OS Nixos
BR Chromium 84.0.4147.135
FW 1.9.3 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8
