### ISSUE TITLE
Confirm empty hidden wallet : Try again button fails

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2259]
**Info:**
 - OS: NIXOS
 - Browser: Chromium 84.0.4147.135
 - Wallet Version: web, commit 96cf8b81b7f24de45feab9644c4d16162b3e5863
 - Firmware Version: 1.9.3 , revision 0xdf5421e7d6c4c03e2d3d395a2cf39d10bdef8089
 - Bridge Version: 2.0.28
 
**Describe the bug**

in Confirm empty hidden wallet dialogue,  Try again button always fails when you try to enter new passphrase after you entered incorrect/empty passphrase. Attached screenshot + downloaded log file

**Steps to reproduce:**
1. load suite and enter passphrase without transactions
2. new dialogue emerge and you are asked to confirm or to try again
3. press try again

**Expected result:**
new passphrase dialogue is displayed

**Actual result:**
You will see error

**Screenshots:**

https://www.youtube.com/watch?v=xqRI7rNNPaA&feature=youtu.be

![image](https://user-images.githubusercontent.com/31506317/91423625-1200d800-e859-11ea-80af-d51f364a35e1.png)

![image](https://user-images.githubusercontent.com/31506317/91423838-5b512780-e859-11ea-9adf-5bf14c6138bc.png)
[trezor-suite-log.txt](https://github.com/trezor/trezor-suite/files/5135526/trezor-suite-log.txt)

**Comment by szymonlesisz** [comment]
whats your bridge version? looks like a message from trezord without "cancel" fix

**Comment by bosomt** [comment]
Bridge Version: 2.0.28
that's latest Nixos version

it's still happening in Nixos
I can check it with latest bridge version in Windows10

**Comment by bosomt** [comment]
tested with bridge 2.0.30

try again button always for for first time
but when i enter some empty passphrase again and then i press try again button for second time it fails
tested twice in latest public beta 

![image](https://user-images.githubusercontent.com/31506317/92211064-20ba4100-ee90-11ea-8d70-dccfb31109f3.png)

**Comment by jerechinsky** [comment]
@bosomt can you please retest?

**Comment by bosomt** [comment]
I was not able to reproduce issue in Chrome and in Linux application


**Info:**
 - Suite version: desktop 21.4.1 (95311f198fba5d2c452cd5d9ce3ede0a50a06a2d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.3.5 regular
