### ISSUE TITLE
Disable eslint rule that forces to use default case in switch inside reducers

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#227]
With immer there is no need to explicitly define default case in switch statements inside reducers, we just need to disable eslint rule that is forcing us to do so.

> Notice that it is not needed to handle the default case, a producer that doesn't do anything will simply return the original state.

https://github.com/immerjs/immer#reducer-example

**Comment by mroz22** [comment]
The rule seems to be disabled (or at least I dont see eslint complain). So can we close this?

**Comment by slowbackspace** [comment]
yup, I already replaced default case with `//no default` comment (in merged PR linked above) that bypass eslint rule. It is good enough for me.
