### ISSUE TITLE
Please consider disabling My Portfolio graph when only XRP is enabled

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2271]
**Is your feature request related to a problem? Please describe.**

Suite dev master a867164dbc8299b2807ecfe8d1b33d479e4fdd71

Please consider disabling My Portfolio graph when only XRP is enabled
It looks really strange and XRP tokens are often not loaded due to external backends.
In some wallets you can see Date text on left, see last screenshot.

**Describe the solution you'd like**
Disable Graph when only XRP enabled/loaded

**Additional context**
![image](https://user-images.githubusercontent.com/31506317/91657211-a8cece00-eabf-11ea-9d0f-9c8a17a01fe3.png)
![image](https://user-images.githubusercontent.com/31506317/91657268-f77c6800-eabf-11ea-9afd-2b97ed31cb25.png)
![image](https://user-images.githubusercontent.com/31506317/91657357-9dc86d80-eac0-11ea-81a9-c48eb40dd647.png)

**Comment by glacierbits** [comment]
Will be solved in new Dashboard.
