### ISSUE TITLE
Fee error when sending LTC

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-suite#2279]
**Info:**
 - OS: NixOS 20.03
 - Browser:Chromium Version 83.0.4103.116 (Developer Build) (64-bit)
 - Wallet Version: Suite web, commit c038aa8f9c2471ad2d72265f93ff72404af58ee0
 - Firmware Version: Trezor One, FW 1.9.2 
 
**Describe the bug**
Failed to confirm transaction when suggested fee was selected

**Steps to reproduce:**
1. Go to LTC Legacy account
2. Sending to LTC Segwti address
3. Confirming the suggested fee
4. Confirming the TX on device
5. Confirming sending the TX

**Expected result:**
The transaction should be sent

**Actual result:**
The transaction, as not sent and the following error, was displayed: Sign transaction error: -26: min relay fee not met, 135 < 189 (code 66)

**Screenshots:**
![image](https://user-images.githubusercontent.com/37402530/91827289-eb6ae480-ec3e-11ea-9a9b-7c0208bdd0a8.png)

**Comment by szymonlesisz** [comment]
is this still an issue @trezor/qa? i believe this was fixed a while ago

**Comment by bosomt** [comment]
**QA OK**

https://ltc1.trezor.io/tx/4afd50504a527f6bb79453b3df74f239d316006733a91439c119e9bdee7e160f

**Info:**
 - Suite version: desktop 21.4.0 (e9429cf6d1aa7af9466cc93d9fd842e9c219aa3f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular
