### ISSUE TITLE
Send form: Visual improvements

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2280]
- [x] **Incorrect size of the arrow between crypto <> fiat inputs**
Please check design. The icon is way too big now.

- [x] **Error / divider spacing**
Make the spacing for error between input and divider even
<img width="120" alt="Screen Shot 2020-09-04 at 10 59 03" src="https://user-images.githubusercontent.com/29627086/92221359-a7294f80-ee9d-11ea-940e-d008d21a0d4a.png">

- [x] **Remove loading from the disabled primary button**
I believe there is no reason to have a loading in a disabled button (e.g. Changing RBF, Locktime, Broadcast results in jump to the right of the disabled primary button) 

- [x] **Consider some sort of scroll animation on "Add new recipient"** 
Adding an extra recipient doesn't provide strong enough action feedback (i.e. nothing "moves" besides the number of the recipient address header – relatively small "feedback" to the naked eye)

- [x] add space after "fee" text in "Total" row when sending eth token

**Comment by glacierbits** [comment]
To be continued in #2784

**Comment by slowbackspace** [comment]
reopening as the PR is not merged yet

**Comment by wendys-cats** [comment]
**QA OK** 

**OS** NixOS + Chromium 85
**Suite** web 20.11.1 39d1b9690756482310a3970de0d1a29b0d4d2e89 (compared the change with beta to double check)
**Device** TT 2.3.4 public

**1.** Incorrect size of the arrow between crypto <> fiat inputs **OK** 

**2.** Error / divider spacing
Make the spacing for error between input and divider even **OK**

**3.** Remove loading from the disabled primary button **OK**

**4.** Consider some sort of scroll animation on "Add new recipient" **OK**

**5.** add space after "fee" text in "Total" row when sending eth token **OK**
