### ISSUE TITLE
Labelling: Visual improvements

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2283]
- [x] Increase padding between the default label and the "Add label" button 

- [x] Incorrect icon on the "Add label" button (should be inverted colors, see design)

- [x] Native buttons in modal: [Zeplin ](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f58c1ad970d6a400e747a05) (fixed in d99e7882cee4c0973d377ba1eefb5f8b2ccb960c)

- [x] Labeled wallet won't populate in the Switch wallet navigation (fixed in ca504df45fe76bc31ec81a712adb939d11a67ed3)

<img width="304" alt="Screen Shot 2020-09-02 at 14 02 21" src="https://user-images.githubusercontent.com/29627086/91978736-ed0ed800-ed24-11ea-9707-435fcbddd949.png">

- [x] Overflow in Accounts and Receive addresses https://github.com/trezor/trezor-suite/issues/2287

<img width="313" alt="Screen Shot 2020-09-02 at 14 13 59" src="https://user-images.githubusercontent.com/29627086/91979829-a3bf8800-ed26-11ea-9bd3-370cae7d641d.png">  

![91460644-55266f80-e888-11ea-8c0d-d32b4eb87b9c](https://user-images.githubusercontent.com/29627086/92657486-377bf000-f2f5-11ea-9e34-9026ce3d919a.png)

**Comment by glacierbits** [comment]
To be continued in the next release.

**Comment by sorooris** [comment]
QA NOK

Unexpected behavior and visual when editing (default/unchanged) labels.

> OS: NixOS
> Browser: Chromium 85.0.4183.102
> Suite: web staging, commit 426ce98
> Firmware Version: 2.3.4 50854b921

- The original **title** of the account **vanishes and is replaced** by a checkmark and a cross sign during label editing.
- **No cursor is displayed** even when the focus is in the input field.
- There is no way to **click back into the input field** once clicked anywhere else & the input is empty.

I would expect the title to have a fixed width with the checkmark and cross sign fixed to the right hand side of the input field (for cases when the title is longer than the input field).
Or perhaps a placeholder text should be present when editing the label.
![image](https://user-images.githubusercontent.com/10185314/95359230-35905700-08ca-11eb-8b5b-ecb1b80fc0f7.png)
![image](https://user-images.githubusercontent.com/10185314/95359947-00383900-08cb-11eb-8ff3-23a37d4b3115.png)

**Comment by tsusanka** [comment]
Should be fixed by https://github.com/trezor/trezor-suite/pull/2547.

**Comment by sorooris** [comment]
**QA NOK**

> Suite: app 20.10.1 a263552
> OS: Windows 10
> Device: model T 2.3.4 50854b921

Placeholder text is not displayed and is instead deleted compared to the [Zeplin design](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f3bf73d694a9912ac30606f) from #2534. Same behavior both when editing the default name and the custom one. @matejzak please confirm this behavior is correct - if so, then moving to Approved.

Zeplin:
![image](https://user-images.githubusercontent.com/10185314/95693362-2e4fad00-0c2c-11eb-97db-b1a86a245738.png)
before editing | after editing
 -|-
![image](https://user-images.githubusercontent.com/10185314/95693422-97372500-0c2c-11eb-8845-b57e45c2bcd5.png) | ![image](https://user-images.githubusercontent.com/10185314/95693427-9b634280-0c2c-11eb-9826-ab43a2779262.png)

**Comment by mroz22** [comment]
Discussed with @matejzak that this is good enough for this release.

**Comment by glacierbits** [comment]
Correct, aiming for the next release. Thanks for the check though.

**Comment by sorooris** [comment]
OK, thanks.
