### ISSUE TITLE
Increase the padding on page after last transaction

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2286]
Accounts > Activity > Scroll to last transaction

As designed: [**Zeplin**](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5efc87a5cb1263131d55bd0d)

**Comment by bosomt** [comment]
**QA OK**

commit 118b1cb4d9f9c8aed2634010fe64a02f66385539
OS Nixos
BR Chromium 84.0.4147.135
FW 1.9.3 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8
