### ISSUE TITLE
Switching fast between coin types and refreshing the page displays a "Device is used in other window" message 

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-suite#229]
reported by @sorooris 

Switching between coin types in quick succession and **refreshing** the page displays a "Device is used in other window" message.

![53180739-8a4c6480-35f6-11e9-9f04-9a8ba164d547](https://user-images.githubusercontent.com/31442634/59204046-1a132000-8ba0-11e9-9834-29d41b8a865e.png)

**Comment by ZdenekSL** [comment]
Closed after discussion

**Comment by ZdenekSL** [comment]
@pankrats please retest with Suiteb
