### ISSUE TITLE
LTC change address: Remove notification

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2306]
Discussed with FW and Support. The information is no longer (as) relevant. Format of the address has changed some 3 years ago and the notification is way too prominent. Tooltip will with simple _Learn more_ will do for now.

- [ ] Remove the context notification

- [ ] Create custom error message in Send upon recognition of "3" (old) address

- [ ] Add tooltip to header in Receive tab with learn more link

<img width="1055" alt="Screen Shot 2020-09-04 at 14 01 19" src="https://user-images.githubusercontent.com/29627086/92237617-f2505c00-eeb7-11ea-934e-591634a06b88.png">

**Comment by bosomt** [comment]
not yet deployed,
i see 02b68e9900858ce723fccb62d8810c3bb425effc on web dev master

**Comment by szymonlesisz** [comment]
@keraf windows desktop build is failing on develop:

`Env WIN_CSC_LINK is not correct`

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev master commit 0fa83d87da8e164370d1f77d2c0294b88b542a36
FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
