### ISSUE TITLE
Secondary button: Update color and font weight

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2307]
[**Zeplin**](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/styleguide/components?coid=5ee87de417603cb72704d86a)

**Comment by sorooris** [comment]
**QA OK**

> Wallet Version: web, 20.9.1 e243afdb73e35fa08f39a7fc08a28b84baa3ac58
OS: NixOS
Browser: any supported (tested Firefox 79.0)
Device: Model T 2.3.3 0d5f00668

Font changed.
