### ISSUE TITLE
Labeling disrupts empty passphrase flow

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2308]
The flow disrupts user's focus on Passphrase. Labeling should be asked for at the end the flow.

Passphrase input 1 > Labeling > Discovery > Empty passphrase warning.

https://staging-wallet.trezor.io/wallet/ 
20.9.1-beta
Commit: cf1f18089c5ed75a68f2e720a5e08b6e3df79130

**Comment by mroz22** [comment]
actually we discussed this with szymon and landed on that this is the best of behaviours available.

**Comment by glacierbits** [comment]
OK. I verified and trust.

**Comment by szymonlesisz** [comment]
actually i've solve it in https://github.com/trezor/trezor-suite/pull/2460
