### ISSUE TITLE
Activity: Remove retry button from Auth error 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2309]
Ideally the "Retry" button would be present only in the app's Authorization error state. 

If we are unable to detect such state ex-post (.i.e. after the device has been authorized), the button shouldn't be present in the Activity tab at all, since it doesn't do anything while it looks fairly prominent on the page. 

<img width="1009" alt="Screen Shot 2020-09-04 at 14 27 00" src="https://user-images.githubusercontent.com/29627086/92239188-e023ed00-eeba-11ea-84e5-e79166d70711.png">

**Comment by szymonlesisz** [comment]
additionally removing buttons from notifications with similar context:
- acquire-error
- auth-error
- auth-confirm-error
- discovery-error

![Screenshot from 2021-04-14 16-29-14](https://user-images.githubusercontent.com/3435913/114833441-deff5a80-9dcf-11eb-893c-c3c21048bcae.png)
