### ISSUE TITLE
Implement bech32 accounts

### ISSUE THREAD

**Issue by slush0** [trezor/trezor-suite#231]
New bitcoin wallet is a great chance to implement bech32 bitcoin accounts (=native segwit) and communicate such change to users as a part of technological upgrade between legacy and Next wallet.

Next wallet should handle bech32 accounts as "standard" and move segwit p2sh accounts into Legacy section (together with pre-segwit P2PKH accounts).

@matejzak UI of displaying standard/legacy accounts as well as creating new accounts (both standard and legacy for segwit p2sh and p2pkh) need to be discussed first. The solution in legacy wallet is far from ideal and was designed by engineers. Reimplementing it into Next wallet is an unique chance for improvement.

Implementing #232 is an obvious requirement.

**Comment by ZdenekSL** [comment]
Implemented into discovery. 
We dont have bech32 send forms.

**Comment by maltokyo** [comment]
Why did this get closed?

**Comment by ZdenekSL** [comment]
> Why did this get closed?

Because of the finished development. This feature will be in Suite, our new application. A new wallet with bech32 accounts will be part of it.

**Comment by maltokyo** [comment]
Great. Thank you. Where can I follow that on GitHub. Would you have the
link?

**Comment by ZdenekSL** [comment]
In this repository: https://github.com/trezor/trezor-suite

**Comment by maltokyo** [comment]
Thank you!!

**Comment by maltokyo** [comment]
According to this, Bech32 is coming in Q4 2019, is it still on track?

https://github.com/trezor/trezor-wallet/issues/610#issuecomment-526868878

**Comment by SimonVillage** [comment]
almost one year later still nothing :)

**Comment by glacierbits** [comment]
Already implemented.

**Comment by SimonVillage** [comment]
But receiving with trezor wallet is still not possible?

https://wiki.trezor.io/Bech32

> Trezor already implemented Bech32 addresses in its firmware, it is possible to send funds to Bech32 addresses using Trezor Wallet. Receiving is possible using Electrum with native segwit (P2WPKH) option.

Edit: Got it, trezor suite is a different product ;)

**Comment by glacierbits** [comment]
Exactly :) Since we are talking, Trezor Suite will go live (public beta) this upcoming Wednesday, and the wiki will get updated to reflect various products. 🤞
