### ISSUE TITLE
Custom fee input

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2310]
Custom fee overflows for no particular reason for the given resolution (1440): 

APPLICATION VERSION
20.9.1-beta
LAST COMMIT HASH
cf1f18089c5ed75a68f2e720a5e08b6e3df79130

<img width="1025" alt="Screen Shot 2020-09-04 at 14 32 56" src="https://user-images.githubusercontent.com/29627086/92239829-e9fa2000-eebb-11ea-8980-fd5b34983460.png">

**Comment by bosomt** [comment]
looks like this in current web master  36515c7564d2756fe34e4136246d86b97eb6e04a
when you only have 4$ in ETH, it will use as much as possible but it looks strange

62.000001347 GWEI


![image (2)](https://user-images.githubusercontent.com/31506317/94243312-8346b000-ff17-11ea-9335-801a777c442c.png)

**Comment by slowbackspace** [comment]
@matejzak I think we had a discussion where I convinced you current layout is not that bad after all (because of reserved space for crypto/fiat value next to the fee selector), togerther with @robertbrada's recent improvements I think we can close the issue!

**Comment by glacierbits** [comment]
Agreed! However, it would still be nice to optimize the box so it doesn't jump (since we already optimized spacing for the errors everywhere else in the form) when `custom` fee applied. I will try to come up with a better design solution.

Suggestions:

- Spacing beneath the input is too large 
- Error should overflow (not wrap)

**Comment by glacierbits** [comment]
Closing in favour of #2784
