### ISSUE TITLE
Labeling modal

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#2315]
1. Click on X
2. Refresh the page

The labeling modal is visible again. 

![image](https://user-images.githubusercontent.com/3112191/92394300-9852cf00-f121-11ea-89ad-905901e33639.png)

**Comment by mroz22** [comment]
Hmm... there are 2 levels of this:

1. Global metadata settings saying whether metadata is enabled or not. This is saved to local storage always.If this option is "on", it means that user might be prompted on device (more details in 2.)
1. Per device metadata status, may be "enabled" | "disabled" | "canceled". If user rejects labeling on device, metadata status for this device is set to cancelled and this dialogue is never again invoked. But! this is saved to local storage only if device is remembered. So if device is not remembered, on page reload it will have again state "disabled".
 
If I disable setting in 1. based on choice in 2. I will also remove all metadata on application level for all devices. I don't say this can't be fixed but it will take more time than I previously expected.
It would require to ALWAYS save device state as part of global metadata settings regardless of whether user decided to save device or not. And I am not sure if this is not againts some privacy rules? @matejzak

**Comment by bosomt** [comment]
**QA OK**

Nicos + Chromium 85
Suite dev web master commit 539ad60eba674bc842260752b1d7017ef35dd86a
FW 1.9.3 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
