### ISSUE TITLE
New send form - Change of FIAT is ignored in send form

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2317]
**Info:**
 - OS: Nixos 
 - Browser: Chrome + Firrefox, current versions
 - Wallet Version: web, cf1f18089c5ed75a68f2e720a5e08b6e3df79130
 - Firmware Version: model 2.3.3 , revision 0d5f00668
 
**Describe the bug**
Change of FIAT value is ignored in Send dialogue. 
Works **OK** when you change fiat via Suite **settings**.

**Steps to reproduce:**
1. open send dialogue
2. change USD to CZK
3. thry to send ammount and check if it was USD or CZK used 

**Expected result:**
Change of FIAT value is ignored in Send dialogue. 

**Actual result:**
Change of fiat is ignored in Send dialogue

**Screenshots:**
Chrome:
https://www.youtube.com/watch?v=CvpyXlAaZ1o&feature=youtu.be
![image](https://user-images.githubusercontent.com/31506317/92467329-b2e48100-f1d1-11ea-9b66-aefecf6f3eca.png)

Firefox:

![image](https://user-images.githubusercontent.com/31506317/92467272-97797600-f1d1-11ea-8f4e-eda5e964c257.png)

**Comment by sorooris** [comment]
**QA NOK**; could reproduce

> Wallet Version: web, 20.9.1 cf1f180
OS: NixOS
Browser: any supported (tested Firefox 79.0.1)
Device 1.9.3 0d5f00668

The amount in the **Total sent** field is not recalculated correctly according to the latest input but instead just takes the nominal value of the outputs[0].fiat field - after **switching between various currencies**.

**Comment by sorooris** [comment]
**QA OK**

> Wallet Version: web, 20.9.1 e243afdb73e35fa08f39a7fc08a28b84baa3ac58
OS: NixOS
Browser: any supported (tested Firefox 79.0)
Device: Model T 2.3.3 0d5f00668

Could not reproduce.
