### ISSUE TITLE
Form state cache between accounts - address is always valid and "1"

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#2318]
![image](https://user-images.githubusercontent.com/3112191/92484436-f8ad4380-f1e9-11ea-862c-91e9377f0ff0.png)

![image](https://user-images.githubusercontent.com/3112191/92484285-dd423880-f1e9-11ea-937c-67f63e06e820.png)

**Comment by szymonlesisz** [comment]
any steps to reproduce pls? invalid form (with "1") should not be stored as draft

**Comment by vladimirvolek** [comment]
Yeah, cannot reproduce now :)
