### ISSUE TITLE
Accounts, Add account/Find my accounts - No filter switch when other coin's new account is added

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2319]
**Info:**
> Wallet Version: web, 20.9.1 cf1f180
OS: NixOS
Browser: any supported (tested Firefox 79.0)
Device: Model 1, 1.9.3, 0d5f00668

**Describe the bug**
The AccountSearchBox__CoinsFilter does not switch to the coin of the newly created account when a different coin than of the currently filtered is added (or undiscovered coin via Find my accounts button); discovered when testing the #2220 issue.

**Preconditions:**
- AccountSearchBox__CoinsFilter active on an arbitrary coin,
- 10 account limit is not exceeded on the other coin.

**Steps to reproduce:**
1. **activate filter** for an arbitrary coin (LTC for example) and select Add account
2. select a coin **other than the currently filtered** (BTC legacy for example) on the displayed modal
3. select **Add account** (or Find my accounts if adding a previously disabled coin) 

**Expected result:**
The AccountSearchBox__CoinsFilter switches to the coin of the newly added (or discovered) account's coin.

**Actual result:**
Filter deactivates for any previously selected coin.

**Screenshots:**
Add account Modal open, Litecoin filter selected:
![image](https://user-images.githubusercontent.com/10185314/92512613-52743480-f20f-11ea-9aea-a037197976cf.png)
Litecoin filter active after adding the BTC legacy account above:
![image](https://user-images.githubusercontent.com/10185314/92512700-7768a780-f20f-11ea-9a30-92ef30bfb2c4.png)

**Comment by bosomt** [comment]
I think this is related to same issue.
When you witch between wallets or you go to settings and you go back then account in the right panel is always account from coin that was loaded to suit earlier and you have to click on account on left to change it.

```
Nixos + Chromium 85
Suite web dev master commit 0d33c15327d4486bab396f7a1b2c80392fa11771
Device model TT fw 2.3.4 commit 50854b921
```

https://www.youtube.com/watch?v=JdNXOqfCtUk&feature=youtu.be

![image](https://user-images.githubusercontent.com/31506317/95435350-c3178980-0952-11eb-9f3f-59508fd61797.png)

**Comment by slowbackspace** [comment]
@bosomt good catch, I guess I should probably reset coin filter on wallet change.

**Comment by wendys-cats** [comment]
**QA NOK** 

browser Chromium 85
Suite web develop branch 4d5d94c51164f229f2f2f3796bc9f2c42f12a5fb
device TT 2.3.4 public revision 50854b921

**Preconditions:**

AccountSearchBox__CoinsFilter active on an arbitrary coin,
10 account limit is not exceeded on the other coin.

**Steps to reproduce:**

**1.** activate filter for an arbitrary coin (LTC for example) and select Add account
**2.** select a coin other than the currently filtered (BTC legacy for example) on the displayed modal
**3.** select Add account (or Find my accounts if adding a previously disabled coin)

**Expected result:**

The AccountSearchBox__CoinsFilter switches to the coin of the newly added (or discovered) account's coin.

**Actual result:**

Filter deactivates for any previously selected coin.

**video:** https://drive.google.com/file/d/1bPaHtLYV4CHRI1FhDN5bq1hPev-unpYY/view

**Comment by slowbackspace** [comment]
@wendys-cats  huh, I would expect it will only deactivates the filter so I see it as a feature, not a bug 😁  Ohh, It seems I haven't read the OG bug report properly 😞 

@matejzak Just making sure, is this what we want? Should adding a new account activate the coin filter? Couldn't user get confused where are all his other accounts?

**Comment by slowbackspace** [comment]
Discussed with @matejzak, the current implementation is indeed what the product wanted, but it was noted that UX is lacking and it will be improved in the future. Thank you all! 🙇

**Comment by sorooris** [comment]
**QA OK**

Current behavior is that the coin filter is reset and the newly created account is focused.

Suite version: app 513631a9fa62c438e60397a9942b04275bcd621a
OS: macOS Catalina 10.15.7
Device: 2.3.4 50854b921
