### ISSUE TITLE
Fw changelog font

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2323]
[Zeplin](https://zpl.io/bAMzrLn)

**Comment by bosomt** [comment]
1) new wizard doesnt use correct font.See screenshot below. Is that on purpose ?

2) can you please change update text to has been or to was ? I'm not expect but ** has released!** sounds strange

![image](https://user-images.githubusercontent.com/31506317/95071735-6e81cd80-070a-11eb-9b16-61c381a27648.png)

Nixos + Chromium 85
Suite web dev master commit 3a9fd795a1b8da8223faa29aaac2aa842a22d262
Device T1 FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,

**Comment by bosomt** [comment]
QA OK

Nixos + Chromium 85
Suite web dev master commit 4d4a9f3
Device Model T 2.3.4 commit 50854b921
