### ISSUE TITLE
New landing page

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2324]
Destination: suite.trezor.io

Design: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f7589dc8b91544e3e52c98b)

**Comment by bosomt** [comment]
@matejzak is there place where we can see that landing page deployed ? 
at suite trezor io i see only that **It works!** :)

**Comment by tomexx** [comment]
Now, after merge to develop it is available at https://suite.corp.sldev.cz/suite-web-landing/develop/ however regarding deployment to other environments I'll need to reach out somebody with deeper devops know-how. :(

**Comment by tsusanka** [comment]
@bosomt Suite.trezor.io is a production environment, it will be there _after_ release (Oct 14th). As @tomexx points out, you can check out the site on the link.

**Comment by tsusanka** [comment]
@bosomt suite.trezor.io is a production environment, it will be there _after_ release (Oct 14th). As @tomexx points out, you can check out the site on the link.

**Comment by bosomt** [comment]
Give feedback leads to dead end ;( https://www.typeform.com/private-typeform

![image](https://user-images.githubusercontent.com/31506317/95302993-f12d9880-0882-11eb-92a2-344f78cd1b2e.png)

Nixos + Chromium 85
Suite staging commit a96a688
Device TT fw 2.3.4 commit 55baf3a

**Comment by glacierbits** [comment]
- Optimize pictures (larger resolution)
- Update Give feedback link

**Comment by wendys-cats** [comment]
@matejzak you cannot access Suite form [this](https://suite.corp.sldev.cz/suite-web-landing/develop/) landing page. Is that intended behavior? Also, the landing page can be seen [here](https://suite.corp.sldev.cz/suite-web/develop/) as well.

**Comment by bosomt** [comment]
**staging-suite.t.io** and **suite.corp.sldev**
works fine including linked web Suite
@wendys-cats can I move it to approved ?

**Comment by zmluvny-jednorozec** [comment]
@bosomt bmg, I was only waiting for confirmation from @matejzak.

**Comment by wendys-cats** [comment]
@bosom yes, I was only waiting for confirmation from @matejzak.

**Comment by bosomt** [comment]
**QA OK**

Microsoft Windows [Version 10.0.18363.1082]
Suite dev master eeeed810de4baf9995cb968475f7a9c4ca6c44d2
Device Trezor model T 2.3.4
