### ISSUE TITLE
Invitation to Suite from old wallet

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2325]
_(Place holder for my-trezor task, so we don't forget)._

- [ ]  Left tab + icon

- [ ] Tag (New)

- [ ]  Tooltip

- [ ]  Link to Suite 

- [ ]  Info about link (XRP, ETH, ETC) to Suite

**Comment by prusnak** [comment]
mytrezor task: https://github.com/satoshilabs/mytrezor/issues/951

**Comment by tsusanka** [comment]
PR in https://github.com/satoshilabs/mytrezor/pull/956

**Comment by prusnak** [comment]
Button deployed to https://wallet.trezor.io
