### ISSUE TITLE
Modals refactor

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2326]
- [x] Update generic Modal component (choose if to use header with border or not)

- [x] Update progress bar design as designed in [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f58c3508fc02548a5ff28ce)

- [ ] Universal modal "Follow instruction on device"  [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f58c4626cb1d145b011da53) 🔜 💯

- [x] Receive: [Zeplin](https://zpl.io/anx6Y0v)

- [x] Cloud sync (Labelling): [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f58c1ad970d6a400e747a05)

- [x] Passphrase: #2368

- [x] Blocked by another window

- [x] Transaction details: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f58c5c02d9ce80796cda6ae)

- [ ] Custom BE (cc @slowbackspace) 🔜 💯 

- [x] Add account modal #2237 

- [x] Switch to existing passphrase (Remove the illustration, since there is nothing to confirm on Device. I suggest using [this one](https://zpl.io/VQ7jkeR) instead) 

<img width="414" alt="Screen Shot 2020-09-16 at 20 28 32" src="https://user-images.githubusercontent.com/29627086/93377390-3ac62d00-f85b-11ea-9955-7b22f44064d1.png">

**Comment by glacierbits** [comment]
To be continued next sprint in #2466

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suide dev web master commit a6bf817b6111a0b31bf947ecca01522dac06441a
Device T1 1.9.2 commit 0xcde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea,
