### ISSUE TITLE
Inconsistencies in new Send form (DOGE, LTC)

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2327]
**Info:**
 - OS: nixos (for web), Windows 10 Home (APP)
 - Browser: Chromium Version 84.0.4147.135 (for web)
 - Suite Version: app, commit e243afdb73e35fa08f39a7fc08a28b84baa3ac58
 - Firmware Version: 2.3.3 model , revision 0d5f00668
 
**Describe the bug**

There are certain cases where Send form does not appear to work correctly and it might confuse the user.
Examples: 
1. When user chooses Send max in DOGE and then tries to type in a higher amount, Suite freezes (se videos). 
2. When user chooses Send max in Litecoin and then types in the same amount as generated by Send max, Suite will respond with "Not enough funds", but WILL LET user proceed with the transaction (closely look at the changing LTC amount and the total amount)

**Steps to reproduce:**

**1.** Go to Send
**2.** Click on Send max
**3.** Tweak the numbers

**Expected result:**
User should be met with consisten behaviour from Suite regarding the Send form.

**Actual result:**
Various errors or inconsistencies, and a freeze in case of DOGE coin.

**Screenshots:**
**DOGE**
WEB version https://drive.google.com/file/d/1z9C5reRjQ5nFuc9J29eSqXjm1J8GfYqN/view
APP version (commit e243afdb73e35fa08f39a7fc08a28b84baa3ac58) https://drive.google.com/file/d/1vMbsIjK5FTKWRdPmBbpWrMxclGQPGcsV/view
APP version (commit cf1f18089c5ed75a68f2e720a5e08b6e3df79130) https://drive.google.com/file/d/1SLtMNSOi5JbQALh1vhlpzYrb3ls8Bzmy/view
**LITECOIN**
https://drive.google.com/file/d/1waeOHHb5Vk11RAH3PVdKa4B5NjOXzXHx/view
the [transaction](https://ltc1.trezor.io/tx/d11d9cbd48bedf7c72300804b5edf8d51a30a74e7dec6bef859c3721cf6ec0e9) from video

**Comment by bosomt** [comment]
**DOGE**

now it loads send transaction forever after i change max 380 to 381 and send max button stops working



380 OK
381 forever loading
382 not enough funds

suite branch fix/send-btc-compose-outputs commit 416ec7a1aa411d976b506b7ad45c727f21148b3b
Nixos + Chromium 85 
FW 2.3.3  0d5f00668


[trezor-suite-log.txt](https://github.com/trezor/trezor-suite/files/5234491/trezor-suite-log.txt)

![image](https://user-images.githubusercontent.com/31506317/93382160-05710d80-f862-11ea-8b68-e4f68a7c538a.png)

**Comment by szymonlesisz** [comment]
should be fixed by https://github.com/trezor/trezor-suite/commit/a35528039d26405e19b2edc4736ef67d995deeed already in develop
