### ISSUE TITLE
Dashboard: + Enable more coins 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2329]
Change "+ Add account" to "+Enable more coins" with **link to Settings > Coins** (as apposed to opening new Account via modal).

It is a workaround for better UX (planned for Q4) regarding enabling/disabling coins and adding/removing accounts.

**Comment by bosomt** [comment]
not yet deployed , latest web commit is older than 20hours

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev web master commit dbfc010
Device TT FW 2.3.3 commit 0d5f00668
