### ISSUE TITLE
Sign & Verify - no confirmation message after signing

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#233]
beta, stage
T1, TT any fw

Steps to reproduce:
- select an arbitrary receive address and fill out the address input
- type any message
- sign with any Trezor device
Hash is generated.

Expected:
Confirmation message is displayed after signing, the same way as when verifying.

Actual:
No confirmation message is displayed.

**Comment by vladimirvolek** [comment]
It will be implemented soon with the new design.
