### ISSUE TITLE
Eject last wallet: Remove empty state

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2330]
Upon ejecting last standing wallet, please:

**Remove:** 

- Empty "Click to discover wallet" box
- Labels: 1 Wallet, Remember, Eject

**Leave as is (and move upward):** 

- `+Add wallet button`

<img width="744" alt="Screen Shot 2020-09-09 at 20 18 05" src="https://user-images.githubusercontent.com/29627086/92637748-929fe980-f2d9-11ea-826e-f2456173dab8.png">

**Comment by glacierbits** [comment]
Yet another reason, why leaving the "Click to discover wallet" in place is an unfavourable state. 

If user clicks on the the `+Add wallet` CTA instead of the wallet box that says "Click to discover wallet", they are left with this (even if you click on the click to discover wallet nothing happens, the box stays in place, the Standard wallet label won't load, and wallet gets stuck on the authentication process).

<img width="739" alt="Screen Shot 2020-09-27 at 17 45 56" src="https://user-images.githubusercontent.com/29627086/94369330-5c3fd800-00e9-11eb-8943-653b3109ae20.png"> 


<img width="1440" alt="Screen Shot 2020-09-27 at 17 58 07" src="https://user-images.githubusercontent.com/29627086/94369607-09672000-00eb-11eb-8153-4f43fde5d895.png">

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev web master commit
Device TT 2.3.3 commit 0d5f00668
