### ISSUE TITLE
Fee: Low to Custom

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2331]
Order of the fee types should be _Low – Medium – High – Custom_ ([as designed](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5efc87aefaf0aa9cd861d17f))

**Comment by bosomt** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/31506317/93996267-587f1f00-fd92-11ea-940f-70e90a25e768.png)

Nixos + Chromium 85
Suite web master commit 539ad60eba674bc842260752b1d7017ef35dd86a
FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
