### ISSUE TITLE
Incorrect spacing: Graph type

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2332]
See [designed
](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5efc87a5cb1263131d55bd0d)

Implementation: 

<img width="276" alt="Screen Shot 2020-09-09 at 23 20 03" src="https://user-images.githubusercontent.com/29627086/92656286-0ef2f680-f2f3-11ea-9e3e-dd13372fefe9.png">

**Comment by bosomt** [comment]
**QA OK**

Suite dev master commit 0157226146ba2b580460aff418d76a16912ed8c9
Nixos + Chromium
Devicve fw 2.3.4 commit 55baf3a
