### ISSUE TITLE
Incorrect position: 3 dots menu

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2333]
See [desing](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f10a83e43bc5c9e4f613e09) 

Implementation:

<img width="188" alt="Screen Shot 2020-09-09 at 23 23 53" src="https://user-images.githubusercontent.com/29627086/92656558-87f24e00-f2f3-11ea-880a-3b40b756b0d9.png">

Results in wild content jumps between Activity and Send tab.

**Comment by bosomt** [comment]
**QA OK**

suite dev master, web commit fb5994a71e797046bfdf18048a763d98ba8653ff
device TT 2.3.3 commit 0d5f00668
NIXOS + Chromium 85.0.4183.83

**Comment by glacierbits** [comment]
White box still jumps by a few pixels (Send is positioned lower then Activity). Please optimize. Not a priority though.

**Comment by glacierbits** [comment]
From what I can see in develop, the previous comment has been fixed. Thanks @slowbackspace 🥇
