### ISSUE TITLE
Error: labeling action failed with unexpected error

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#2334]
![labeling error](https://user-images.githubusercontent.com/54173889/92749847-cbe26300-f386-11ea-9351-00c3c7db0cb3.png)

**Comment by bosomt** [comment]
had same error,
looks like Dropbox was busy

![image](https://user-images.githubusercontent.com/31506317/92751535-5a0b1900-f388-11ea-92f4-96bf3925dacc.png)

**Comment by bosomt** [comment]
Looks like problem on Suite's side
Mytrezor works fine. Loads and saves labels correctly.
Suite loads but fails to save 

here's log from suite: https://pastebin.com/Kxuaxerr

Suite commit e243afdb73e35fa08f39a7fc08a28b84baa3ac58

**Comment by bosomt** [comment]
**QA OK**
works fine now

Suite commit e243afdb73e35fa08f39a7fc08a28b84baa3ac58

@stepmes please confirm and close

**Comment by slowbackspace** [comment]
@mroz22 imo we should handle cases in which provider API doesn't response and show some human friendly message.

**Comment by bosomt** [comment]
yes please 
+ add local storage fallback ?
why local storage was omitted ?

**Comment by mroz22** [comment]
labels share fate of device. If device is set to "save", then labels are saved too in localstorage, otherwise not.

and yes, error handling is not very fine-tuned at the moment, not talking about the cases when storage is full etc that are already solved in mytrezor.

**Comment by mroz22** [comment]
I hope this should not occur anymore once this is merged https://github.com/trezor/trezor-suite/pull/2438

**Comment by mroz22** [comment]
I suspect that this still may happen (just textation of error shall be different). And I suspect that this happens after longer time, when access_token is expired and app fails to renew it. I will investigate.

**Comment by glacierbits** [comment]
Expected to be fixed already.
