### ISSUE TITLE
Implement intermediary firmware for T1 with older bootloaders

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2338]
We have finally finished, reviewed and signed the intermediary firmware. This firmware's only goal is to upgrade the device's bootloader before upgrading the firmware. This simplifies the on-boarding process for every new T1 user. See https://github.com/trezor/trezor-firmware/issues/4 for more details.

Now it's time to implement it in Suite :muscle:.

**Comment by sorooris** [comment]
Tested extensively in 21.6.2 290aab68 in issues #[1597](https://github.com/trezor/trezor-firmware/issues/1597) #[1619](https://github.com/trezor/trezor-firmware/issues/1619) and #3911, can I approve?

**Comment by tsusanka** [comment]
@sorooris yes we have new issues so let's do it :+1:
