### ISSUE TITLE
Graph labels not distributed evenly

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2342]
### 1W (Account)

<img width="839" alt="Screen Shot 2020-09-14 at 10 54 17" src="https://user-images.githubusercontent.com/29627086/93065136-a4d2ac80-f678-11ea-9c02-5c38c9d02ad0.png">

### 1M (Account / Dashboard) 

<img width="1115" alt="Screen Shot 2020-09-14 at 10 53 41" src="https://user-images.githubusercontent.com/29627086/93065274-cb90e300-f678-11ea-8dc1-4cf6724c452a.png">

**Comment by slowbackspace** [comment]
Basically we have 3 options: preserve star and end labels (current behaviour), preserve end (2nd screenshot) or preserve start (3rd screenshot). I'll go with preserving end.
<img width="926" alt="Screenshot 2020-09-25 at 11 34 22" src="https://user-images.githubusercontent.com/6961901/94251875-7465fa80-ff23-11ea-91f1-452f541fd26c.png">
<img width="933" alt="Screenshot 2020-09-25 at 11 34 42" src="https://user-images.githubusercontent.com/6961901/94251879-762fbe00-ff23-11ea-90c0-78c961c69910.png">
<img width="962" alt="Screenshot 2020-09-25 at 11 35 03" src="https://user-images.githubusercontent.com/6961901/94251883-7760eb00-ff23-11ea-9252-e5ee6dd63437.png">

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev master 5ba60e0679e7d4501c7cfa1bf59dfcbd8396687a
Device 2.3.3 commit 0d5f00668
