### ISSUE TITLE
Remove "Exchange (soon)" from top navigation

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2343]
<img width="239" alt="Screen Shot 2020-09-14 at 11 18 16" src="https://user-images.githubusercontent.com/29627086/93067834-fdf00f80-f67b-11ea-8f58-8d6ca85867f4.png">

**Comment by vladimirvolek** [comment]
This is already removed in https://github.com/trezor/trezor-suite/tree/feat/invity-apps3

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite web dev master commit b291f5ef949eee6dc5cd6e3ab653eee2210f45f7
FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
