### ISSUE TITLE
Add tooltip to "Portfolio"

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2346]
If ETH and/or XRP enabled, show tooltip. 

We'll inform the users the coins are not available in the graph (and are available in the header).

**Comment by bosomt** [comment]
it says Ripple transactions , isn't suppose to say XRP transactions ?

**Comment by bosomt** [comment]
**QA OK**

Nixos, Chromium 85
Suite web master 59dd350d5397d9b77898f4c394dda4b57b13562a
FW TT 2.3.3, 0d5f00668

**Comment by slowbackspace** [comment]
@bosomt good point!

**Comment by bosomt** [comment]
and of course Ethereum and not ethereum :)

**Comment by slowbackspace** [comment]
I hope I didn't insult any ethereum user :) ofc proper copy will be done by @matejzak
