### ISSUE TITLE
Can't reveal labeled used addresses as it opens context menu for labelling

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2347]
You can't reveal labeled used address as it opens context menu for labelling
<img width="1014" alt="Screenshot 2020-09-14 at 18 20 49" src="https://user-images.githubusercontent.com/6961901/93111597-23e6d580-f6b7-11ea-8048-6f2888a90fa4.png">

not sure if new design actually solves this by revealing all used address by default or it just slipped into the design by mistake
https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f5b9a255519d3485db3d74f

**Comment by slowbackspace** [comment]
ohh I didn't even notice there is a menu item "Confirm on device" that is doing exactly that. Anyway, once new design is implemented, we will put a separate reveal button there.

**Comment by bosomt** [comment]
Context menu looks amazing, had no idea that it exist ;)

but doesn't disappear :(

Chromium 85.0.4183.83 (Developer Build) (64-bit)
Firefox 80.0 (64-bit)

https://github.com/trezor/trezor-suite/commit/0840609ffa611dc29903e7b5e53b7d73c4381966

**Chrome**
![image](https://user-images.githubusercontent.com/31506317/93247604-db025000-f78e-11ea-9bf2-1a462cf0104a.png)
**Firefox**
![image](https://user-images.githubusercontent.com/31506317/93248327-fb7eda00-f78f-11ea-9b49-f9b6bcc7f029.png)

**Comment by slowbackspace** [comment]
~wow I had no idea it also works in confirm modal! It seems to me more like a bug than a feature. I guess we dont wanna show a label when the task is to verify the address.~
Context menu really doesn't open in the confirm addr modal. I think I know what @bosomt did. Most likely clicked on the "show address" btn in receive tab and then quickly, before the modal opened, clicked on address with a label. I think it is too crazy scenario to be bothered by it. You can close the context menu by clicking anywhere anyway.
cc @matejzak 

@bosomt Pls check if the steps I mentioned above matches what you did. I am closing this issue as it was created for a different problem anyway. You should be able to close the context menu by clicking outside of it.

**Comment by bosomt** [comment]
no i didn't checked it one more time

1) click label
2) click confirm on device
3) see context menu and address

when you click outside context menu it will disappear

i will create new issue ;)

**Comment by bosomt** [comment]
sent https://github.com/trezor/trezor-suite/issues/2358
