### ISSUE TITLE
Responsive account menu width

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#2349]
on current develop:

![Screenshot 2020-09-14 at 19 57 51](https://user-images.githubusercontent.com/3435913/93182332-df504e00-f739-11ea-9f05-602544169577.png)

**Comment by bosomt** [comment]
**QA OK**

looks good now

Nixos + Chromium 85
Suite dev web master a64816b985a74b1493eac2f76311722ceabbdb8f
FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
