### ISSUE TITLE
Remove cursor from input

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2351]
Dropdown should populate list of words starting with the particular letter upon user input.

<img width="156" alt="Screen Shot 2020-09-15 at 12 38 44" src="https://user-images.githubusercontent.com/29627086/93201022-e171d700-f750-11ea-81d2-f31406747291.png">

**Comment by slowbackspace** [comment]
I am not sure what do you mean by this. You want to start showing the cursor only after user types in first letter or just have it completely removed? imo it's good that there is a cursor. It is the only visual clue that you can filter the list instead of just scrolling through it.

**Comment by glacierbits** [comment]
Discussed with Ondra in the past: User shouldn't be able to actually type in a letter, but just filter the options. Therefore cursor shouldn't be present. It's not a search box, but a dropdown.

**Comment by bosomt** [comment]
@slowbackspace was it merged already ? i see that web dev version has commit a6bf817b6111a0b31bf947ecca01522dac06441a and it's only one hour old but i still have cursor in ETH/ERC20 send selector

**Comment by glacierbits** [comment]
Will be fixed by #2480. This issue is a duplicate.

**Comment by bosomt** [comment]
if it's duplicate I will move it to approved 
and we will wait for that second issue to get merged
