### ISSUE TITLE
New context notification

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2352]
- [x] Switch wallet modal: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f58c69ccfdcd6057a0cedde)
- [x] Account body: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/dashboard?seid=5f608bd877653d6aef26f923)

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suide dev web master commit 3a9fd795a1b8da8223faa29aaac2aa842a22d262
Device 1.9.2 commit 0xcde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea,
