### ISSUE TITLE
Layout: Bottom spacing

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2355]
Increase the spacing between the bottom of the page nad the last white box in all the Settings pages.

<img width="1266" alt="Screen Shot 2020-09-15 at 16 19 22" src="https://user-images.githubusercontent.com/29627086/93222432-3de3ef00-f76f-11ea-813e-d9f1bca140ec.png">

**Comment by slowbackspace** [comment]
I think we should consider adding some padding/margin globally somewhere in [SuiteLayout](https://github.com/trezor/trezor-suite/blob/eecc2a1d05c16e2e9d4eb59e75366a11223856d4/packages/suite/src/components/suite/SuiteLayout/index.tsx).
Maybe `DefaultPaddings` component is a good candidate, might introduce some design issue though so watch out for these.
(After implementing this we could remove custom spacing in transactions list we added recently)

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev web master commit dbfc010
Device TT FW 2.3.3 commit 0d5f00668
