### ISSUE TITLE
Wallet label edit

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2357]
Switch wallet modal > Edit label > Empty label > Close label 

.. resolves in opening the wallet

Expected result: Close the edit labeling process, leave the deterministic label at place.

**Comment by bosomt** [comment]
**QA OK**

Nicos + Chromium 85
Suite dev web master commit 539ad60eba674bc842260752b1d7017ef35dd86a
FW 1.9.3 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
