### ISSUE TITLE
Labeling - Context menu doesnt disappear in receive tab 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2358]
**Info:**
 - OS: Nixos
 - Browser: Chromium 85.0.4183.83 (Developer Build) (64-bit), Firefox 80.0 (64-bit)
 - Wallet Version: web, commit https://github.com/trezor/trezor-suite/commit/0840609ffa611dc29903e7b5e53b7d73c4381966
 - Firmware Version: model T 2.3.3 , revision 0d5f00668 
 
**Describe the bug**

Labeling context menu doesn't disappear in Receive tab when address has label attached.

**Steps to reproduce:**
1. load wallet and enable labeling
2. go to Receive tab and click on address with label
3. select Confirm on device and observe

**Expected result:**
context menu will disappear after option is selected 
**Actual result:**
context menu will be visible till you click outside that menu

**Screenshots:**
**Chrome**
![image](https://user-images.githubusercontent.com/31506317/93247604-db025000-f78e-11ea-9bf2-1a462cf0104a.png)

![image](https://user-images.githubusercontent.com/31506317/93253618-6d0e5680-f797-11ea-83f6-fb71564596aa.png)

**Firefox**
![image](https://user-images.githubusercontent.com/31506317/93248327-fb7eda00-f78f-11ea-9b49-f9b6bcc7f029.png)

**Comment by sorooris** [comment]
**QA OK**

Suite: web staging, commit 426ce98
Browser: Chromium 85.0.4183.102
OS: NixOS
Firmware Version: 2.3.4 50854b921
