### ISSUE TITLE
MonetaryUnit trezor custom backend using blockbook

### ISSUE THREAD

**Issue by sotblad** [trezor/trezor-suite#236]
Hey! 
I'm trying to get MonetaryUnit (MUE is a PIVX fork) into trezor. I've integrated it into blockbook successfully, it seems to be running as it's supposed to.
But the thing is that when I submit https://blockbook.monetaryunit.org on wallet.trezor.io/#/settings "Bitcore Server URL", it returns an error message on that page "`The bitcore server doesn't seem to reply. Please select another server.`" and I'm getting these errors on chrome's console:
<img width="641" alt="57971555-520bb680-7998-11e9-899d-6640f6907c0a" src="https://user-images.githubusercontent.com/26393434/58027717-eead9000-7b21-11e9-9a58-4792db5b9d2b.png">

There are no errors in the blockbook logs.
I'm getting something like this this on blockbook.INFO:
`I0512 23:04:21.316745 905 socketio.go:45] Client connected -QvDGo-kAam8AmdLci1R`
`I0512 23:04:29.391556 905 socketio.go:50] Client disconnected -QvDGo-kAam8AmdLci1R`

Any idea on why it doesn't get recognised? MonetaryUnit is already added on `trezor/trezor-firmware`.
Thanks.

**Comment by prusnak** [comment]
MUE was not enabled for use in the web wallet.

I added the entry here: https://github.com/trezor/trezor-firmware/commit/9b7a2095b3c4ae3455c53a7b4578c7f8e18c916a#diff-9ab1665396f435df91ac1b65d7fdc16fR2834

It should become in production in the following 2-4 weeks.
