### ISSUE TITLE
Fee box layout distorted

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2360]
Broken layout 

<img width="784" alt="Screen Shot 2020-09-16 at 15 26 40" src="https://user-images.githubusercontent.com/29627086/93343654-076ea880-f831-11ea-8407-d834b0606802.png">

**Comment by bosomt** [comment]
probably not yet deployed,
looks like this
![image](https://user-images.githubusercontent.com/31506317/94817881-cadca880-03fd-11eb-869e-2f2d0ba53ea3.png)

Suite dev master commit 0157226146ba2b580460aff418d76a16912ed8c9
Nixos + Chromium 
Devicve fw  2.3.4 commit 55baf3a

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev web master commit dbfc010
Device TT FW 2.3.3 commit 0d5f00668

**Comment by szymonlesisz** [comment]
reopening "sat/B" is floating out of the input box when error is present

![Screenshot 2020-11-19 at 20 11 35](https://user-images.githubusercontent.com/3435913/99712932-07468f80-2aa4-11eb-916f-89127f461bc4.png)

**Comment by tomexx** [comment]
Will be addressed with merge of RBF feature `feature/rbf`

**Comment by slowbackspace** [comment]
@szymonlesisz @tomexx Are you sure it is not fixed already? I can't reproduce it in current develop.

**Comment by bosomt** [comment]
@szymonlesisz i was not able to reproduce it ? what witch coin are you testing ?

**Comment by tsusanka** [comment]
@bosomt please retest on f997134b as sent to QA few hours ago.

**Comment by bosomt** [comment]
QA OK

Windows 10
Suite app commit e16f9ff
Device model One FW 1.9.3

**Comment by sorooris** [comment]
**QA OK**

Suite: app e16f9ff0d8455d1b3a40f88dd878946fbe8f7115
OS: macOS Big Sur 11.0.1
Device: model T 2.3.4 public
