### ISSUE TITLE
Coin filter deactivation

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2361]
reminder: option to deactivate account filter by clicking anywhere in the filter area except coin icons.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite web dev master commit 4600f383ea31099c4177b3bcb3a492cb88be7ebb
FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
