### ISSUE TITLE
Remove white background from News button

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2363]
Dashboard > News > Show older news

Use button without the white border (to be consitent with other buttons: Add acount, Hide). 

<img width="165" alt="Screen Shot 2020-09-16 at 17 11 22" src="https://user-images.githubusercontent.com/29627086/93356665-c336d480-f83f-11ea-98fc-19d80586f9bc.png">

**Comment by bosomt** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/31506317/94820788-23617500-0401-11eb-9468-883c67161996.png)


Suite dev master commit 0157226146ba2b580460aff418d76a16912ed8c9
Nixos + Chromium 
Devicve fw  2.3.4 commit 55baf3a
