### ISSUE TITLE
Import of transaction from .csv

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2364]
**[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f52095cc6d7c47bf1a824db)**

**Comment by szymonlesisz** [comment]
already merged

**Comment by bosomt** [comment]
**QA OK**

Nixos
Suite app commit 39d1b9690756482310a3970de0d1a29b0d4d2e89
Device model One firmware 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
