### ISSUE TITLE
Left Account menu uses only 8 numerals even coins are using more than 8 digits

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2366]
**Info:**
 - OS: Nixos
 - Browser: Chromium , version 85
 - Wallet Version: web, commit e243afdb73e35fa08f39a7fc08a28b84baa3ac58
 - Firmware Version: model 2.3.3, revision 0d5f00668
 
**Describe the bug**
Left Account menu uses only 8 numerals even coins are using more than 8 digits

**Steps to reproduce:**
1. load accounts with funds
2. compare left bar and account details /see screenshots/

**Expected result:**
You will see same results in left bar and account details 

**Actual result:**
You see different results, last digits are missing.

**Screenshots:**
![image (1)](https://user-images.githubusercontent.com/31506317/93433368-ff614800-f8c6-11ea-880f-a3877747dab1.png)
![image](https://user-images.githubusercontent.com/31506317/93433373-00927500-f8c7-11ea-9ff9-09fc92a37be9.png)

**Comment by prusnak** [comment]
We should fix this before the public release

**Comment by slowbackspace** [comment]
I came to conclusion it works exactly as "designed" 😀 I will talk with @matejzak how can we fix it. 
https://satoshilabs.slack.com/archives/CPU92A6JV/p1583492657001900

**Comment by prusnak** [comment]
I don't want to reopen the old discusion, but my 2 cents are: I think that hiding insignificant digits of amounts is fine, but then it would be nice to have some kind of indication (such as replacing the least significant digits with `…`)

**Comment by glacierbits** [comment]
Agreed. Will discuss with Ondra today whether to use `...` or some other visual cue. Thanks everyone!

**Comment by glacierbits** [comment]
Decision made: 

@slowbackspace please 

- [ ] add an extra numeral to the rule (i.e. 9 in total) to take care of most of the (smaller balance BTC-like) cases

- [ ] shorten anything longer by `...` (Color: The same grey as fiat balance)

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite web dev master commit 4600f383ea31099c4177b3bcb3a492cb88be7ebb
FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
