### ISSUE TITLE
Passphrase modal brushup

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2368]
Passphrase flow beautified:

[**Zeplin**](https://zpl.io/bzmJKQ8)

**Comment by bosomt** [comment]
@matejzak 

**select passphrase source** is that correct ? 
device display says `Enter passphrase`

![image](https://user-images.githubusercontent.com/31506317/94655330-b2399900-02fe-11eb-9fc9-99e9d4360f12.png)

Nixos + Chromium 85
Suite dev web master 565ed2da61b77ed46f3215554917b96cee38efd2
Device TT 2.3.3 commit 0d5f00668

**Comment by glacierbits** [comment]
It is not. Thanks for the catch.

@slowbackspace custom translation pls and ping once done. Thanks!

**Comment by glacierbits** [comment]
I take that back @slowbackspace. I see in Crowdin we have custom translations for each of these cases: 

1. Empty passphrase, user input on host. 
2. Empty passphrase, user input on device. 

I fixed them both to make better sense. Changes will populate upon Crowdin sync. 

<img width="363" alt="Screen Shot 2020-10-02 at 23 59 00" src="https://user-images.githubusercontent.com/29627086/94973170-40826a80-050b-11eb-9a27-710b56218918.png">

**Comment by sorooris** [comment]
**QA OK**

> OS: NixOS
> Browser: Chromium 85.0.4183.102
> Suite: web staging, commit 426ce98fbcb16af057d8b2f5d636f88f4e374a23
> Firmware Version: 2.3.4 50854b921
