### ISSUE TITLE
Animations' performance optimalization

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2369]
- [x] Check svg spinners

- [x] Remove animation from connect device modal

**Comment by tomexx** [comment]
PR: https://github.com/trezor/trezor-suite/pull/2474

**Comment by sorooris** [comment]
**QA OK**

 - [x] Check svg spinners
 - [x] Remove animation from connect device modal

> Suite: app 20.10.1 a263552
> OS: Windows 10 18363.1082
> Device: model T 2.3.4 50854b921
