### ISSUE TITLE
Graph tooltip with a point

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2370]
Accounts > Activity > ALL

<img width="176" alt="Screen Shot 2020-09-17 at 15 09 22" src="https://user-images.githubusercontent.com/29627086/93474550-c7262d80-f8f7-11ea-8cb6-60b8ef132945.png">

**Comment by slowbackspace** [comment]
magically fixed! (thanks to @tomexx )

**Comment by glacierbits** [comment]
Is it? 

76976eff883ff377438aac2c2143923f7b56630b 

<img width="846" alt="Screenshot 2020-10-20 at 19 52 03" src="https://user-images.githubusercontent.com/29627086/96624992-db51b600-130d-11eb-90dd-590b232d9799.png">

**Comment by slowbackspace** [comment]
works on my machine ™️ 
Is it somewhere on "all" seed?

<img width="638" alt="Screenshot 2020-10-21 at 09 47 07" src="https://user-images.githubusercontent.com/6961901/96689238-69678400-1382-11eb-9305-6b6b845142bf.png">

**Comment by glacierbits** [comment]
It's `Matej's seed` ™️ 

I am guessing it happens in the case when there is just 1 transaction?

**Comment by glacierbits** [comment]
I am closing this until we'll be able to reproduce.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82.0.3 (64-bit)
Suite web dev master commit 43328cfdf47e74c53d385b7f453de5affbc3f8fe
Device model One FW 1.9.1
