### ISSUE TITLE
Skeleton loaders

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2373]
Let's use skeleton loaders with shimmer (e.g. https://codepen.io/JCLee/pen/dyPejGV) 

- [ ] **Dashboard**: https://zpl.io/2ELeP5g

- [ ] **Transactions**: https://zpl.io/agjNQe9

- [ ] **Send**: https://zpl.io/bzrnqeA

- [ ] **Receive**: https://zpl.io/VYeRrEp

**Comment by bosomt** [comment]
**QA OK**

Nixos
Firefox 82.0.3 (64-bit)
Suite web dev master commit f93bd32
Device 2.3.5
