### ISSUE TITLE
Remove 3rd party wallets links

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2378]
Remove the whole "Supported by 3rd party wallets" section from Suite. 

- It's a bad practice to link to external services (especially from electron app) 
- this should be communicated outside the app (blog, wiki etc.)  

<img width="1093" alt="Screen Shot 2020-09-18 at 20 30 45" src="https://user-images.githubusercontent.com/29627086/93632798-3bdb9380-f9ee-11ea-8bf7-0121e161c45a.png">

**Comment by tsusanka** [comment]
Decided on Product meeting: let's replace this with a link to www.trezor.io/coins.

**Comment by slowbackspace** [comment]
It also should be removed from add account modal, correct? I think this will be the place where user will be searching for these coins so I would expect the link to be integrated somewhere near, but I am not sure where. @matejzak 

<img width="935" alt="Screenshot 2020-09-22 at 13 23 55" src="https://user-images.githubusercontent.com/6961901/93876273-e0075800-fcd6-11ea-8cd3-0dc87e0fda2b.png">

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
suite web dev master commit 36515c7564d2756fe34e4136246d86b97eb6e04a
FW 2.3.3 commit df5421e
