### ISSUE TITLE
Increase the bottom spacing

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2379]
Increase the bottom spacing in all Settings tabs. 

<img width="955" alt="Screen Shot 2020-09-18 at 20 35 24" src="https://user-images.githubusercontent.com/29627086/93632952-7cd3a800-f9ee-11ea-94ac-44d897b3f408.png">

**Comment by slowbackspace** [comment]
duplicate of https://github.com/trezor/trezor-suite/issues/2355
