### ISSUE TITLE
Clear all should not be present

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2380]
Show "Clear all" only after there is some input from the user (as opposed to have it present by default). 

<img width="158" alt="Screen Shot 2020-09-18 at 20 37 43" src="https://user-images.githubusercontent.com/29627086/93633204-df2ca880-f9ee-11ea-9b61-55d49e284a26.png">

**Comment by sorooris** [comment]
**QA NOK**

> Suite Version: web, f24640d
> OS: NixOS
> Browser: Chromium 85.0.4183.102
> Device 2.3.3 0d5f00668

Trivial note: the clear-form (Clear all) button isn't displayed if the outputs[0].fiat value isn't a number.
@matejzak please advise if this behavior is desirable from your point of view.

outputs[0].fiat is a number | outputs[0].fiat is non-number value
------------ | -------------
![image](https://user-images.githubusercontent.com/10185314/93909568-2e7d1c80-fd00-11ea-8555-b3c039957e74.png) | ![image](https://user-images.githubusercontent.com/10185314/93909638-3c32a200-fd00-11ea-9249-6b94033be27f.png)

**Comment by szymonlesisz** [comment]
should be fixed via https://github.com/trezor/trezor-suite/commit/50fac1ab8490c26473d238d4bbe840b2cc54cb1c

**Comment by bosomt** [comment]
**QA OK**

+ https://github.com/trezor/trezor-suite/issues/2380#issuecomment-696831277 was fixed too

Nixos + Chromium 85
Suite dev master commit 36515c7564d2756fe34e4136246d86b97eb6e04a
FW TT 2.3.3 commit 0d5f00668
