### ISSUE TITLE
Google and Dropbox are lower case in General Settings 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2381]
**Is your feature request related to a problem? Please describe.**
Google and Dropbox are lower case in General Settings 

It can be changed here https://github.com/trezor/trezor-suite/blob/57609e18ed8f9fc9f5a23cdcc6a8cf2192e5625a/packages/suite/src/types/suite/metadata.ts

Suite version 02b68e9900858ce723fccb62d8810c3bb425effc

**Describe the solution you'd like**
Connected to Google or Dropbox

![image](https://user-images.githubusercontent.com/31506317/93661583-2cddfb00-fa59-11ea-8748-edebc44275b2.png)

![image](https://user-images.githubusercontent.com/31506317/93661595-3e270780-fa59-11ea-908d-1284d79b2769.png)

**Comment by prusnak** [comment]
I would not rather change the `metadata.provider.type` and just quick-fix the rendering of the value:

``` javascript
diff --git a/packages/suite/src/views/settings/index.tsx b/packages/suite/src/views/settings/index.tsx
index 1d6664c90..b6a67d0ad 100644
--- a/packages/suite/src/views/settings/index.tsx
+++ b/packages/suite/src/views/settings/index.tsx
@@ -125,7 +125,7 @@ const Settings = ({
                                 <Translation
                                     id="TR_CONNECTED_TO_PROVIDER"
                                     values={{
-                                        provider: metadata.provider.type,
+                                        provider: metadata.provider.type.charAt(0).toUpperCase() + metadata.provider.type.slice(1),
                                         user: metadata.provider.user,
                                     }}
                                 />
```

**Comment by mroz22** [comment]
It maybe should be Google Drive. But who knows.. Copy is always few steps behind :factory_worker:
