### ISSUE TITLE
Back button on "Starting up or coming back" screen in Onboarding goes elsewhere

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#2383]
**Info:**
 - OS: NixOs 20.03.2778.20904118004
 - Browser: Chromium, version 84.0.4147.105
 - Wallet Version: web 20.9.1-beta
 - Firmware Version: Model T & Trezor 1
 
**Describe the bug**

On the second screen in Onboarding (after clicking on Fresh device), the "Back" button doesn't go back, but to a different screen that is not relevant.

**Steps to reproduce:**
1. Open Suite with Onboarding
2. Click Fresh Device
3. Click Back

**Screenshots**
![back from fresh device](https://user-images.githubusercontent.com/54173889/93749672-98ab9980-fbfa-11ea-9e0e-7eb6a45278e9.png)

@matejzak

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev master commit f9d6827f67e9877bbd903a05da4469578617dd74
Device 1.9.2 commit 0xcde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea,
