### ISSUE TITLE
Back button on "My Hologram Looks different" screen in Onboarding goes two steps back

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#2384]
@matejzak 
**Info:**
OS: NixOs 20.03.2778.20904118004
Browser: Chromium, version 84.0.4147.105
Wallet Version: web 20.9.1-beta
 
**Describe the bug**
The back button on the "My Hologram Looks different" screen in Onboarding goes two steps back to the "State of your device" screen instead of just one step to the "Hologram check" screen.

**Steps to reproduce:**
1. Any device with any FW in onboarding
2. Click all screens through to hologram check, click My hologram looks different
3. Click back

**Screenshots:**
![hologram back](https://user-images.githubusercontent.com/54173889/93753691-d8757f80-fc00-11ea-906e-955e4016686c.png)

**Comment by mroz22** [comment]
And is this a bug or a feature? 

My idea was that this hologram is signle step with "substeps", show hologram again button takes you back to hologram (initial hologram screen) and back button takes you back to device selection. 

If it was like you want it, then "back" and "show hologram again" would do the same.

**Comment by glacierbits** [comment]
Closing this issue, will be fixed (handled differently) by new Onboarding design.
