### ISSUE TITLE
Unify Bitcoin #1 / Account #1 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2396]
Use: {Network} #{n}  as opposed to: Account #{index} in both the Accounts menu and Account header. 

Remove the account type from the brackets (e.g. SegWit). This is to be handled by labels customized by the users. 

<img width="646" alt="Screen Shot 2020-09-22 at 13 15 19" src="https://user-images.githubusercontent.com/29627086/93875658-abdf6780-fcd5-11ea-8834-f0cdc8260c82.png">

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
suite dev master commit 6fa440f1fd278ceb66341afc47872c2b2cf60f39
FW 2.3.4 commit f8489f1
