### ISSUE TITLE
Wrong value is fetched from Ethereum blockchain

### ISSUE THREAD

**Issue by robertbrada** [trezor/trezor-suite#2401]
There is a wrong **input value** In TX Details Modal for Ethereum blockhain. It works okay for Bitcoin-like coins. 

![eth_bug](https://user-images.githubusercontent.com/44506010/93896307-0f2ac300-fcf1-11ea-8909-db536c94db94.png)

**Comment by slowbackspace** [comment]
ohh, I didn't notice there's an issue for this! For the time being I simply removed the input amount for ethereum (in https://github.com/trezor/trezor-suite/pull/2385).
I also removed total input/total output fields from "Amount" tab. So together with his change removing input value might even be proper solution! 😁

**Comment by robertbrada** [comment]
I am closing this issue because it's not a bug, but a valid behavior according to the way how Ethereum blockchain works (see https://github.com/trezor/trezor-suite/pull/3160#issuecomment-742375964). The current way how we handle this in the UI is for now.
