### ISSUE TITLE
ERC20 tokens Total sent  

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2403]
Optimizing token send with no fiat value (for now). As discussed in the office: 

<img width="822" alt="Screen Shot 2020-09-22 at 16 48 41" src="https://user-images.githubusercontent.com/29627086/93898401-79446780-fcf3-11ea-9819-50e24a7c219d.png">

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev master commit 36515c7564d2756fe34e4136246d86b97eb6e04a
FW TT 2.3.3 commit 0d5f00668
