### ISSUE TITLE
Firmware update during onboarding - two screens interfere with each other

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#2407]
**Info:**
OS: NixOs 20.03.2778.20904118004
Browser: Chromium, version 84.0.4147.105
Wallet Version: web 20.9.1-beta
 
**Describe the bug**
The first status screens of the fw update process skip quickly one after another. It creates an impression that something happened and the user didn't catch it. The two interfering screens are "Firmware update process started" & "Follow instructions on your device"

**Steps to reproduce:**
1. Connect device with outdated firmware to Suite in incognito window
2. During onboarding, connect device in bootloader when prompted and Initiate firmware update process
3. Click "Install full featured firmware"

**Screenshots:**
I can send a screen capture for better illustration.

@matejzak

**Comment by mroz22** [comment]
Did you mean the "started" status that appeared there for like 0.5 second?

Maybe check here if it still happens https://suite.corp.sldev.cz/suite-web/firmware-update-brushup/

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev web master commit a6bf817b6111a0b31bf947ecca01522dac06441a
Device T1 FW 1.9.2 commit 0xcde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea,
