### ISSUE TITLE
Redundant button during firmware update in onboarding

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#2409]
**Info:**
OS: NixOs 20.03.2778.20904118004
Browser: Chromium, version 84.0.4147.105
Wallet Version: web 20.9.1-beta
Trezor Model T only
 
**Describe the bug**
A firmware update screen in onboarding contains a redundant "Continue" button when accessed with Trezor Model T. The button isn't clickable. When the same screen is accessed with Trezor One, the button isn't there, so it looks rather like a bug. 

**Steps to reproduce:**
1. Connect device with outdated firmware to Suite in incognito window
2. During onboarding, connect device in bootloader when prompted

![Screenshot (41)](https://user-images.githubusercontent.com/54173889/93910459-66d12a80-fd01-11ea-9947-b37b17c261d3.png)

@matejzak

**Comment by mroz22** [comment]
In https://github.com/trezor/trezor-suite/pull/2408

![image](https://user-images.githubusercontent.com/30367552/94263436-52757380-ff35-11ea-9390-81890cc43779.png)

**Comment by mroz22** [comment]
Didnt investigate, but original logic was

In bootloader -> cant click continue, can click install
Not in bootloader -> cant click install can click continue

Firmware required -> install button appears, continue not
Firmware outdated -> install button appears, continue appears
Firmware none -> install button appears, continue not.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite web dev master commit 3a9fd795a1b8da8223faa29aaac2aa842a22d262
Device T1 FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
