### ISSUE TITLE
Hide ballances: Discreet mode

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#241]
**[Zeplin](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6eeab91a321bf43bd7b5)**

- [x] Tooltip on the switch

**Comment by ZdenekSL** [comment]
The balance should be unreadable, but visible on mouseover/tooltip.

**Comment by glacierbits** [comment]
@ZdenekSL We are suggesting to replace characters with bullet points "•" for all balances and addresses(Sketch: https://sketch.cloud/s/AK1WY/a/2wZaZM) and revealed them on hover.

**Comment by glacierbits** [comment]
@vladimirvolek Pls add a tooltip to the Discreet mode switch.

**Comment by sorooris** [comment]
https://suite.corp.sldev.cz/suite-web/develop/wallet/#/btc/0/segwit
Transaction detail screen

Current Value and Historical Value are not hidden and there is no design of the transaction detail screen. Please specify if these values should or should not be hidden.

![image](https://user-images.githubusercontent.com/10185314/76862199-03e86d80-685e-11ea-9267-beb0f38191a0.png)
