### ISSUE TITLE
"Firmware update failed" error screen in onboarding contains non-clickable "Retry" button

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#2410]
**Info:**
 OS: NixOs 20.03.2778.20904118004
Browser: Chromium, version 84.0.4147.105
Wallet Version: web 20.9.1-beta

**Describe the bug**
The "Retry" button on the "fw update failed" screen is grey and non clickable.

**Steps to reproduce:**
1. Connect device with outdated firmware to Suite in incognito window
2. During onboarding, connect device in bootloader when prompted and Initiate firmware update process
3. Click "Install full featured firmware" and **abort** the action on device
4. The "Retry" button isn't clickable. 

**Expected result**
It might give the user the option to restart the process (e.g. to navigate to the fw update start screen)

**Screenshots:**
![fw failed](https://user-images.githubusercontent.com/54173889/93915395-3f319080-fd08-11ea-8208-7a132f06c31a.png)

@matejzak

**Comment by bosomt** [comment]
Tested, and yes it looks good but that Error looks bad ;(

![image](https://user-images.githubusercontent.com/31506317/95051075-ef31d100-06ec-11eb-888c-c527b8d3f1ee.png)

Nixos + Chromium 85
Suide web dev master commit d9203c75b03db72d6399744a15c06afe6cab15db
Devier T1 FW 1.9.2 0xcde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea,

**Comment by mroz22** [comment]
@bosomt how did you trigger this error?

**Comment by bosomt** [comment]
@mroz22 

**Steps to reproduce:**

1) Connect device with outdated firmware to Suite in incognito window
2) During onboarding, connect device in bootloader when prompted and Initiate firmware update process
3) Click "Install full featured firmware" and abort the action on device
4) observe error :)

**Comment by mroz22** [comment]
Weird thing is that repository does not contain "Install full featured firmware" at the commit you provided. 
It would have to be either here 
https://github.com/trezor/trezor-suite/blob/d9203c75b03db72d6399744a15c06afe6cab15db/packages/suite/src/support/messages.ts
or here 
https://github.com/trezor/trezor-suite/blob/d9203c75b03db72d6399744a15c06afe6cab15db/packages/suite-data/files/translations/en.json

But I will try it for sure

**Comment by mroz22** [comment]
should be fixed in https://github.com/trezor/trezor-suite/pull/2587
please test :pray:

**Comment by bosomt** [comment]
**QA OK**

string issue will be fixed in this issue https://github.com/trezor/trezor-suite/issues/2710

Nixos + Firefox 81
Suite web dev  4d4a9f3f493613c0a86f905414dd8071c55ac69e
Device model One fw 1.9.1 commit 0xc6b2580cd245ee924507f45e9675f857a3d78768,
