### ISSUE TITLE
"Pin setup successful" screen in onboarding contains a redundand "Skip" button

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#2411]
**Info:**
OS: NixOs 20.03.2778.20904118004
Browser: Chromium, version 84.0.4147.105
Wallet Version: web 20.9.1-beta
 
**Describe the bug**
The last screen of the PIN setup process in onboarding contains skip button, even though there is nothing more to skip. 

**Steps to reproduce:**
1. Launch Suite in incognito mode with a non-initialized device.
2. Progress to the PIN setup 
3. The "Continue" and "Skip" button has the same efect

**Screenshots:**
![Pin skip](https://user-images.githubusercontent.com/54173889/93917745-a9980000-fd0b-11ea-935c-27a81e872488.png)

@matejzak

**Comment by bosomt** [comment]
**QA OK**

Suite dev master commit 0157226146ba2b580460aff418d76a16912ed8c9
Nixos + Chromium 85
Devicve fw 1.8.3 0xdf0963ec48f01f3d07ffca556e21ff0070cab099,
