### ISSUE TITLE
Custom navbar: Desktop app

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2412]
Customize desktop app navigation bar: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f6b0073aa3cbd1a4cd1a5af)

**Comment by keraf** [comment]
Few notes on this:
- Should of course only be shown if the environment is desktop (maybe using the environment variable or by having it as a component of suite-desktop only).
- It should be platform aware and styled according to the platform. Mac has the colored buttons on the left, Windows on the right with some specific style and Linux too. Telegram's client is a good example (see screenshots on Google).
- The top bar should use the `-webkit-app-region` CSS attribute with the `drag` value to indicate it's draggable. See: https://www.electronjs.org/docs/api/frameless-window#draggable-region
- Actions should be wired to the buttons (close, minimize, maximize, reduce) by extending `desktop_api`. Calls should be made from the rendered to main using that api. A state should be kept to switch the icons when you maximize the window, the minimize button should be shown and vice-versa.
- Once implemented, we can make the window frameless. See: https://www.electronjs.org/docs/api/frameless-window

**Comment by tomexx** [comment]
I've recreated Mac style navbar controls + for Windows and Linux I created a very generic design of the controls. Please feel free to criticise.

![image](https://user-images.githubusercontent.com/2822756/95494893-e9fbad00-099e-11eb-879b-71291f51f115.png)

![image](https://user-images.githubusercontent.com/2822756/95494923-f849c900-099e-11eb-8518-6b2d6f87613d.png)

**Comment by sorooris** [comment]
- [x] MacOS app 513631a9fa62c438e60397a9942b04275bcd621a **OK**
 - [x] Win10 (see [comment](https://github.com/trezor/trezor-suite/issues/2412#issuecomment-723236148))
 - [ ] Linux

**Comment by wendys-cats** [comment]
**Windows10 Home  OK**
20.12.0 commit 491f31ee27067b57e273e79cd1a6e1cad91459bb
Device 2.3.4 public

Exit having red background on hover for Win10 is a lovely touch!

![photo_2020-11-06_19-35-13](https://user-images.githubusercontent.com/58593111/98402286-55e93800-2067-11eb-9865-ac1f5f0a2399.jpg)

**Comment by bosomt** [comment]
Just checked 3 Linux distros with KDE and Gnome and Suite ignores native environment.

Suite staging app commit 513631a9fa62c438e60397a9942b04275bcd621a

See colors and icons.

**KDE + KUbuntu** 


![image](https://user-images.githubusercontent.com/31506317/98528907-3cb9d480-227d-11eb-9ba2-fd4f9217d224.png)
![image](https://user-images.githubusercontent.com/31506317/98528928-417e8880-227d-11eb-8c4a-a146ce750153.png)

**Mint + KDE**

![image](https://user-images.githubusercontent.com/31506317/98529160-99b58a80-227d-11eb-9e07-089314b6f4f8.png)
![image](https://user-images.githubusercontent.com/31506317/98529854-6fb09800-227e-11eb-9501-acb7312e87c1.png)
![image](https://user-images.githubusercontent.com/31506317/98529762-514a9c80-227e-11eb-8ac4-f888a2d3e475.png)


**Fedora + Gnome**

![image](https://user-images.githubusercontent.com/31506317/98529622-22342b00-227e-11eb-907f-25191a89ee10.png)

**Comment by sorooris** [comment]
@matejzak @tsusanka could you please look at the Linux distros screenshots above and confirm whether the current state is intended?

**Comment by tsusanka** [comment]
I am a bit confused about the Mint + KDE pictures. On the first pic you are showing two navbars (one Suite's and one OS's) but on the second one Suite has only one, nope?

**Comment by bosomt** [comment]
@tsusanka those are two separate apps, just move them close so you can compare them ;)

sorry for confusion :)

**Comment by tomexx** [comment]
Right now we are using custom HTML/CSS title bar and we have detection for:
- Mac
- any other device

If we want to support custom designs for different linux distros (UIs) we'll need a list which ones to support and then find a detection mechanism (Electron built-in detection won't be enough I guess). The app with custom title bar can't mimic the native controls design automatically, unfortunately.

**Comment by prusnak** [comment]
It is impossible to detect all Linux distro UIs - there are two options - keep it as it is (preferred) or remove it on Linux (as being discussed here - https://github.com/trezor/trezor-suite/issues/2856)

I think this issue is done and can be closed

**Comment by sorooris** [comment]
Agreed, closing and moving to approved as there's a follow-up issue. Thank you everyone!
