### ISSUE TITLE
Add beta status to Suite UI

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2413]
Beta: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f6b05cdc37420140bc6c17b)
Menu open: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f6b05d75fb9a107674ce971) 

..as opposed to the design proposal, **do not include Wiki** in the menu since there won't be much content at the time of the launch.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev web master 54ca021215d10c94aa93bad72546b8571f66f61c
Device TT FW 2.3.4 55baf3a
