### ISSUE TITLE
Reorganize paths

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#2416]
![Screenshot from 2020-09-23 11-55-50](https://user-images.githubusercontent.com/42201/94009881-5f635d00-fda5-11ea-9ff1-3f493a1f6f83.png)

* `/wallet/start` => `/`
* `/wallet` => `/web`

Ideally let's get rid of `assetPrefix`

**Comment by keraf** [comment]
`assetPath` is still required for our dev deploys (branch name paths). We just need to update the `assetPath` value for the staging/production deployments.

**Comment by prusnak** [comment]
Fix in https://github.com/trezor/trezor-suite/pull/2459

**Comment by sorooris** [comment]
**QA OK**

- [x] staging 
- [ ] production

![image](https://user-images.githubusercontent.com/10185314/95361543-27900580-08cd-11eb-9c11-8091c19c3a27.png)

Suite: web staging, commit 426ce98
Browser: Chromium 85.0.4183.102
OS: NixOS
Firmware Version: 2.3.4 50854b921
