### ISSUE TITLE
Receive: Font color

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2431]
Addresses, Amounts (darker)
Table headers (lighter) 

[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f69b39730490b045e54dfa0)

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
suite web dev master commit f9d6827f67e9877bbd903a05da4469578617dd74
FW 1.9.2 commit 0xcde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea,
