### ISSUE TITLE
Graph: Touch-up

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2436]
- [x] Grey out out of focus area ([as designed](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/styleguide/components?seid=5ee87f2e6c4f4fb8451b768c))

- [x]  Centered and fixed height tooltip ([as designed](https://zpl.io/aNgOLvN))

- [x] Add shadows to the bars ([as designed](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/styleguide/components?seid=5ee87f2e6c4f4fb8451b768c))

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 81
Suite dev web 4d4a9f3
Device model T 2.3.4 commit 50854b921
