### ISSUE TITLE
Date picker

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2437]
- [x] Date picker: [Zeplin](https://zpl.io/bod4ZYZ) 

- [x] Layout (Range): [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5ee8c6343e7221b6cdc90705)

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox
Suite web dev master commit 5dd771fc22dc9a97fb20e820bd8d3ff373c488cd
Device 1.8.3 public version
