### ISSUE TITLE
Sign n Verify notification on success/fail is outside of user's visible area on smaller screens

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#244]
User just clicked the Verify button and said that "nothing" happened!
ohhhh, he has to scroll all the way to the top to see the result!
We need to figure out a better way to show the result of sign n verify actions.
Maybe something like toast notification?
 
<img width="564" alt="Screenshot 2019-03-29 at 10 43 51" src="https://user-images.githubusercontent.com/6961901/55223921-95a33900-520f-11e9-9193-0c4b32483823.png">

<img width="578" alt="Screenshot 2019-03-29 at 10 44 56" src="https://user-images.githubusercontent.com/6961901/55223988-bec3c980-520f-11e9-9d52-41fffbb81a9f.png">

**Comment by ZdenekSL** [comment]
Closed after discussion
