### ISSUE TITLE
Autoupdate: Design

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2440]
[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/dashboard?seid=5f6f394f93e4fe835a0723e2)

**Comment by slowbackspace** [comment]
What is this? New type of notification just for the update process? Replacement for current toast notification? How many days are there till the freeze? 🤕 

<img width="506" alt="Screenshot 2020-09-26 at 17 23 33" src="https://user-images.githubusercontent.com/6961901/94344058-03a30900-001d-11eb-8c29-1ce0bb505d98.png">

**Comment by glacierbits** [comment]
Resolved by #2478

**Comment by bosomt** [comment]
@matejzak is there anything that we can test in this issue  ?

**Comment by sorooris** [comment]
@bosomt design can be tested once [this PR](https://github.com/trezor/trezor-suite/pull/2478) is ready .
