### ISSUE TITLE
Consistent tooltips

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2441]
Dashboard > Portfolio 

We are using solid icons.

<img width="299" alt="Screen Shot 2020-09-26 at 16 01 07" src="https://user-images.githubusercontent.com/29627086/94342478-8a51e900-0011-11eb-996e-87923662cb92.png">

<img width="278" alt="Screen Shot 2020-09-26 at 16 03 15" src="https://user-images.githubusercontent.com/29627086/94342523-cb49fd80-0011-11eb-856c-40f2a31fa052.png">

**Comment by slowbackspace** [comment]
Are you sure? It's pretty clear we are using both 😛 
<img width="1243" alt="Screenshot 2020-09-26 at 17 20 07" src="https://user-images.githubusercontent.com/6961901/94344017-89728480-001c-11eb-8f33-cd508374a297.png">

**Comment by glacierbits** [comment]
Humiliating. My apologies, I meant to say I would like to see all tooltips look the same. Anyway, we are right now in the process of designing better, multifunctional tooltips. So let's fix this inconsistency then. Moving this to Q4 and renaming it. 
 
<img width="750" alt="Screen Shot 2020-09-27 at 11 53 44" src="https://user-images.githubusercontent.com/29627086/94361940-1f0f2200-00b8-11eb-8128-7abc9c695730.png"> 
😬
