### ISSUE TITLE
New snack bar notifications

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2450]
**[Zeplin](https://zpl.io/2ELeR98)**  

Example position: **[Zeplin](https://zpl.io/br4por7)**

**Comment by bosomt** [comment]
When I receive 3 transactions I see only ONE snack notification.
See video: https://www.youtube.com/watch?v=rksJ6FRt1GI&feature=youtu.be

Is that correct behavior ? @matejzak @slowbackspace 

Nixos + Chromium 85
Suite dev web master commit bc892c27b061b02c11a1f38861b2985fb5a10b7b
Device TT 2.3.3 commit 0d5f00668

**Comment by wendys-cats** [comment]
**QA NOK**
Nixos OS + Chromium 85
Suite dev web master commit a96a6885eabbb51d757925059fcbed5347b7c2b4 (from log)
Devices TT 2.3.4. 55baf3a AND TT 2.3.3 public (0d5f00668)

OK
**Successfully ested following notifications**
"Copied to clipboard"
"XXX BTC received on Bitcoin #number"
"PIN changed successfully"
"Settings changed successfully"
"Device wiped successfully"
"Backup success"

**NOK**
**Following notifications were shown on Notification page, but did not pop up**
"Device NAME connected"
"New wallet created"

**Comment by slowbackspace** [comment]
@bosomt, @wendys-cats this is the issue for design change only. there was no change in functionality or behaviour (besides added close btn). Could we create seperate issues for these pls? 🙏 

@bosomt it may be possible we are blocking notifications about received txs if they are sent to same acount (what you see is notification about sent tx). I am not completely sure so I'll let @matejzak decide if it is a feature.

**Comment by glacierbits** [comment]
@bosomt It is good enough for now, we will review the _sent to myself_  receive behaviour. The sending part is definitely correct, since it still counts as one transaction with multiple outputs. 

@wendys-cats Not a bug, we intentionally made those notifications less intrusive (= no toast). That said, the "New wallet created" log will be removed from the list altogether in the next release on the basis of not being relevant enough.

**Comment by wendys-cats** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev web commit 426ce98fbcb16af057d8b2f5d636f88f4e374a23
Device TT FW 2.3.4 revision 55baf3a
