### ISSUE TITLE
Autolock seemingly "disables" passphrase

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2452]
1. Standard wallet loaded 
2. Device auto-locks 
3. Switch wallet modal > Add hidden wallet
4. Continue on device > PIN entry 
5. Device: Do you really want to enable passphrase on device?  

(I have never disabled passphrase, hence I shouldn't be asked this to begin with).

**Comment by szymonlesisz** [comment]
should be solved by https://github.com/trezor/connect/commit/bcfc6e1033968dd314378d306fcd3c2766e0565e

**Comment by bosomt** [comment]
works OK but I think it looks ugly when you cancel unlock device when trying to add another passphrase wallet

![image](https://user-images.githubusercontent.com/31506317/94893510-a4634f80-0487-11eb-8c17-9bab4298959c.png)

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite dev web master commit dbfc010689ca20988647b57a5d9443cf815b531e
Device TT FW 2.3.3 commit 0d5f00668
