### ISSUE TITLE
Custom translation for hidden wallet

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2453]
If technically feasible, let's please create custom translation for the case, when Standard wallet has been already loaded. 

The CTA should read: `+ Add Hidden wallet`

<img width="784" alt="Screen Shot 2020-09-27 at 15 10 35" src="https://user-images.githubusercontent.com/29627086/94365791-f72db780-00d3-11eb-87de-bbbd87a1c82a.png">

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82.0 (64-bit)
Suite web dev master commit a5b13d5
Device model TT FW 2.3.3 commit 0d5f00668
