### ISSUE TITLE
Improve locktime error message

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2463]
Transactions where `lock_time` > current block height are going to be refused by the Bitcoin network. That is a correct behavior. 

However, when user tries to send such transaction in Suite they receive `Failed to send transaction",{"message":"-26: non-final"}` error which explains nothing. Let's improve the message. 

Low priority IMHO. Related: https://github.com/trezor/trezor-firmware/issues/1287, https://github.com/satoshilabs/mytrezor/issues/736

**Comment by MichielBruijn** [comment]
If I understand correctly locktime is a tool to postpone/lock the transaction for an x amount of blocks. So the expected behaviour should be locktime > current blockheight.
There is no point in creating a Tx with locktime < current blockheight IMHO.

**Comment by prusnak** [comment]
We can also disable the "broadcast" button for such transaction since the broadcasting will always end up with the error: https://github.com/trezor/trezor-suite/issues/5391

**Comment by MichielBruijn** [comment]
Seems like a good idea to me.

**Comment by tsusanka** [comment]
That is a better idea. Let me close this one.
