### ISSUE TITLE
Trezor Suite - hidden wallet - number missing

### ISSUE THREAD

**Issue by tomexx** [trezor/trezor-suite#2467]
![image](https://user-images.githubusercontent.com/2822756/94667382-0d738780-030f-11eb-9415-b7fa56dc8a1b.png)

![image](https://user-images.githubusercontent.com/2822756/94667473-24b27500-030f-11eb-84d6-0cefe22faa19.png)

**Comment by slowbackspace** [comment]
can't reproduce 😱 
<img width="667" alt="Screenshot 2020-09-30 at 16 00 48" src="https://user-images.githubusercontent.com/6961901/94695401-27749080-0336-11eb-81c1-cc1e024c7d93.png">

**Comment by mroz22** [comment]
Might be affected by labeling/metadata stuff.

**Comment by mroz22** [comment]
Related bug: 
If you enter route that does not trigger discovery and thus does not generate device state, you see "Hidden wallet #1"

**Comment by sorooris** [comment]
**QA OK**

Hidden wallet is not missing numbers anymore but found a related issue - #2578.
> Suite: app 20.10.1 a263552
> OS: Windows 10
> Device: model T 2.3.4 50854b921

**Comment by bosomt** [comment]
**QA NOK**

im not able to reproduce it **BUT** it happened to me 3 times today.
I will try to find steps to reproduce it

Labeling disabled
Autolock+PIN enabled
Suite web commit 39dd7f81f6eec3b02c834b80a8351e0965008346
OS and browser: Nixos + Chromium 85
Device model T 2.3.4

**Comment by mroz22** [comment]
Could not reproduce today. I am removing the "high priority" label until someone can repro

**Comment by glacierbits** [comment]
What you can't reproduce, @mroz22 's robot can (at 11s): 

https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/829563583/artifacts/file/packages/integration-tests/projects/suite-web/videos/metadata/wallet-metadata.test.ts.mp4

**Comment by slowbackspace** [comment]
@matejzak holy shit! how did you managed to notice it? This is GOLD

**Comment by glacierbits** [comment]
The credit goes to the Frankenstein himself who made me aware of it while selling his robots. 😬
