### ISSUE TITLE
Lock Trezor on demand from Suite

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2469]
Since the introduction of auto-lock for Trezor T we also added the ability to lock the device via the `LockDevice` message. This was added to both TT and T1. We could somehow incorporate this into Suite to allow locking the device on demand.

**Comment by hynek-jina** [comment]
I’m closing this issue for now until the product is specified.
[Current private specification](https://www.notion.so/satoshilabs/Device-auto-lock-4623e3b252374b8f8d1e78a87c41c68a)
