### ISSUE TITLE
T1 Pin modal: LastPass wants to remember my pin

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#2477]
As i remember correctly we already solved this for passphrase modal,
any particular reason for using `<input type="password"` in pin modal? @slowbackspace 

![Screenshot 2020-10-01 at 13 44 05](https://user-images.githubusercontent.com/3435913/94805190-42a1d780-03ec-11eb-8b72-25105bd4d7fb.png)

**Comment by slowbackspace** [comment]
Probably just because it has been this way since forever and no one raised an issue. As you correctly recall the "fix" was integrated only in passphrase modal.
https://github.com/trezor/trezor-ui-components/blob/master/src/components/inputs/Pin/index.tsx

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 86.0.4240.111
Suite web dev master commit f06aff6
Device model One FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
