### ISSUE TITLE
Select refactor

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2480]
- [x] Remove cursor (disable input of characters)
- [x] Jump to value on keypress
- [x] Correct input height (48px): [Zeplin](https://zpl.io/aBxArwe)

Examples: 

- Add account modal 
- Settings (fiat)
- Send (Fiat currency)
- Send (ERC20 tokens)

**Comment by robertbrada** [comment]
Visual improvements are done. Code for **Jump to value on keypress** feature is ready and working, but it was kinda hacky to make it work. So I will make a separate PR for that feature because there might be some new errors.

**Comment by glacierbits** [comment]
I assume we can close this @robertbrada?

**Comment by robertbrada** [comment]
Yes, all of the inputs and selects should be updated.

If that's not the case, it's a bug.

**Comment by bosomt** [comment]
**QA OK**

**Info:**

Suite version: web 21.1.0 (a2ce5af)
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
OS: Linux x86_64
Screen: 1920x1080
Device: model One 1.9.3 regular
