### ISSUE TITLE
Dark mode: Research

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2481]
Research dark mode "libraries". Are there any shortcuts to recreating the whole component library?

**Comment by prusnak** [comment]
Couple of relevant reading points:
* https://www.smashingmagazine.com/2020/04/dark-mode-react-apps-styled-components/
* https://dev.to/nw/adding-dark-mode-to-your-react-app-with-hooks-media-queries-and-css-variables-50h0

**Comment by glacierbits** [comment]
Update: After a discussion with @slowbackspace and @tomexx we have enough input to begin the work – Ondra has started creating the dark mode color scheme.

**Comment by keraf** [comment]
Just some extra input here about the implementation of dark mode. We should look to implement it as one of many themes. Going forward, it would be nice to offer themes that are more geared towards accessibility (larger fonts, higher contrast, color blind friendly colors/motives, ...).
