### ISSUE TITLE
Add ERC20  token

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2484]
`+ Add token` in the ETH account Token section (same component as Enable more coins on Dashboard) 

- Opens modal with input _(Design waiting for export)_ ⚠️

**Comment by bosomt** [comment]
See difference between accounts that already have tokens. It's not possible to add/load them manually.
Maybe we can move this button to different section or always show Token section in Eth account even when there are no tokens loaded/present ?

![image](https://user-images.githubusercontent.com/31506317/103753711-aa7b4600-500b-11eb-8c8a-431df7d7d926.png)


**Tokens included**

![image](https://user-images.githubusercontent.com/31506317/103753734-b2d38100-500b-11eb-8e56-5f360fea4fe4.png)

**Comment by bosomt** [comment]
**QA OK**

/add token can be found in account **...** /

**Info:**
 - Suite version: web 21.1.0 (021d3c7a1319c33ea35570b0ac6c4b6bcff36cae)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.3 regular
