### ISSUE TITLE
Show only supported coins for each model

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-suite#2487]
**Description**
When in Trezor Wallet, the currency menu shows unsupported coins as well (for example when connected with Trezor One - I can select Cardano even though it's not supported by T1 firmware)

**Proposal**
Based on the device type display only coins that are supported by the device's firmware. The device type is known when adding an account of a certain coin to the wallet as with Suite accounts and coins are being added to the given device.

**Comment by tsusanka** [comment]
Let's not worry about Wallet, we will kill it soon. In Suite I can see the coin is listed even for T1 in case it is not supported (such as XRP and T1), however a warning is then displayed:

![Screenshot from 2020-10-02 11-38-44](https://user-images.githubusercontent.com/1835345/94909853-12b60b00-04a4-11eb-9f63-3952ad495c06.png)

I belive that's just fine? Removing the coin from the select box might be confusing. Up to @matejzak to decide though.

**Comment by glacierbits** [comment]
I agree with @tsusanka the information about the particular coin not being supported is valuable. That being said, the current `Add account` modal UX is outdated and will be redesigned (incl. this particular case) in the next release. Thanks for bringing this to our attention.

**Comment by yohaaan** [comment]
Yeah, I meant suit, didn't edit the original post, sorry for the confusion. Agree on the fact that it's valuable information, it would be great if it's communicated more clearly, thanks for having look into this.
