### ISSUE TITLE
Management method in another window breaks "acquire device"

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#249]
Steps to reproduce:
1. open wallet, auth device (pin and/or passphrase)
2. open "old" wallet in another window
3. "wipe" device in "old" wallet
4. switch to this wallet - there will be an error instead of "Device not initialized" screen

**Comment by glacierbits** [comment]
@trezor/qa Can you please retest (and reopen if needed) this issue? It's rather old. 🤔

**Comment by bosomt** [comment]
@matejzak I was not able to reproduce issue anymore

**QA OK**

<img width="523" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/131961183-2692ac2b-38d5-4073-9b4e-94b65545c0da.png">

**Info:**
 - Suite version: desktop 21.9.1 (c1fd2626a782c05c014d293964e09a4613e3040e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular
