### ISSUE TITLE
Account notification - bottom padding

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#2490]
![image](https://user-images.githubusercontent.com/3112191/94920124-f0c58400-04b5-11eb-999e-2c3c5945bdbe.png)

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 85
Suite web dev master commit 3a9fd79
Device T1 FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
