### ISSUE TITLE
Misplaced BETA dropdown in the desktop app

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#2492]
In the Desktop app (Electron).
When you click on the `BETA` button in the right corner of the app. You can see only a tiny piece of the dropdown. See the screenshot.

![image](https://user-images.githubusercontent.com/3112191/94920680-08e9d300-04b7-11eb-9aa7-2d53ee3bc154.png)

**Comment by slowbackspace** [comment]
can't reproduce, if it was in dev env you probably forgot to rebuild components lib.

**Comment by sorooris** [comment]
**QA OK**

Couldn't replicate the bug.

> Suite: app 20.10.1 a263552
> OS: Windows 10
> Device: model T 2.3.4 50854b921
