### ISSUE TITLE
Factory reset button - Incorrect action executed

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2494]
>  OS: any (tested NixOS)
>  Browser: any (Chromium 85.0.4183.102)
>  Suite Version: web develop, commit 2ab75ac
>  Firmware Version: model T 2.3.4 55baf3ac

 
**Describe the bug**
Selecting the button present in _Settings -> Device_, section _DANGER AREA_, named Factory reset (formerly Wipe device) does not erase _all_ the data; it erases only the user data, firmware is kept on the device. Compare to the current state in the public Wallet where these two actions are clearly differentiated:
- Wipe device - erases user data, keep firmware
- Factory reset - erases all data, including the firmware

**Steps to reproduce:**
1. Navigate to _Settings_, select the _Device_ tab,
2. Navigate to the _DANGER AREA_ section,
3. Select the Factory reset button, select checkbox in modal and confirm on device.

**Expected result:**
1) Device is reset to the factory state - without firmare present.
2) Button name is Wipe device and does the same action as it did thusfar.

**Actual result:**
Device is wiped of the user data and the firmware is kept.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/94927554-bca49000-04c2-11eb-9f71-cb3d142e1060.png)
![image](https://user-images.githubusercontent.com/10185314/94927519-b0203780-04c2-11eb-8e74-5332c46b5d44.png)

**Note(s):**
Button's description: _Factory reset
Wiping the device removes all its information. Only wipe your device if you have your device if you have your recovery seed at hand or there are no funds stored on this device._
Modal:
_Reseting the device removes all its data. Reset your device only if you have recovery seed or there are no funds stored on the device._

**Comment by mroz22** [comment]
Yeah, that's probably copy problem. 
Factory reset is available only for model T and (I think) only in bootloader. 
But depends on terminology, if wipe is factory reset now? Who knows?

**Comment by glacierbits** [comment]
Copy improved:

<img width="1182" alt="Screenshot 2020-10-19 at 19 12 41" src="https://user-images.githubusercontent.com/29627086/96488966-12a56180-123f-11eb-9bb4-4dc52dbe50b3.png">
