### ISSUE TITLE
You were disconnected notification

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2497]
The notification is present, even though I am connected. Refresh won't help. 

Commit: 2ab75ac21dd3aac83b636c628b63e39f93570904 

<img width="1440" alt="Screen Shot 2020-10-02 at 21 09 59" src="https://user-images.githubusercontent.com/29627086/94961019-2ab57b00-04f4-11eb-9d21-ed3bc74842c8.png">

**Comment by slowbackspace** [comment]
@trezor/qa please try if you can reproduce it, if not feel free to close the issue. thank you!

@matejzak it is your browser that is telling us that you are offline, try restarting it.

**Comment by sorooris** [comment]
**QA OK**

Couldn't replicate.

**Steps:**
- loaded Suite, let the accounts get discovered
- disconnected the computer from wi-fi
- _disconnected notification_ displayed
- re-established the wi-fi connection

_Disconnected notification_ hidden afterwards.

> Suite version: web develop a6bf817
> Browser: Chromium 85.0.4183.102
> OS: Nixos
> Device: model T 2.3.3 0d5f00668
