### ISSUE TITLE
[REQ] Port some of the HWI and Electrum codebase to allow direct integration with Core and Electrum

### ISSUE THREAD

**Issue by brianddk** [trezor/trezor-suite#2506]
**Is your feature request related to a problem? Please describe.**
With the new Trezor Suite there is the opportunity for direct file system and socket access.  With this access it will be possible to directly integrate Trezor HW to Bitcoin Core and Electrum wallets.  Although these integrations exist piecemeal already in the respective products, it might be nice to offer Trezor Suite as a "control center" for these integrations.

**Describe the solution you'd like**
I'd imagine a "Pair With..." menu with the choices of "Electrum", "Bitcoin Core" and perhaps other products like "Electron Cash" or any of dozens of different wallets.

The Electrum pairing option would produce the proper JSON wallet file for Electrum (properly encrypted with Trezor).  Once paired there could be an "Electrum..." menu allowing you to operations like LN channel operations and OP_RETURN instructions, as well as dozens of other electrum commands that might be interesting.  Perhaps even an Electrum console.

The Bitcoin Core pairing would look very similar allowing for Core specific commands related to PSBT creation and finalization as well as signing operations either natively or through HWI.  A huge win would be the keypool import through `importmulti`.  HWI does this, though the operations are simple enough to add.

**Describe alternatives you've considered**
A clear alternative is simply to allow users to do this piecemeal, though I think just a minimal amount of hand-holding would make it much easier for users to use a Trezor with Bitcoin Core.  The Electrum integration may not offer much, but it may be such a simple lift that perhaps it warrants the effort.

**Additional context**
With the recent announcement of [Core integration](https://twitter.com/dldasilvarosa/status/1312144317327106051?s=21) in future Ledger Live updates, this would be nice product parity for Trezor.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
