### ISSUE TITLE
Settings - Missing version/commit in General section

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2525]
**Info:**
 - OS: Nixos
 - Browser:Chromium  , version 85
 - Wallet Version: web, commit 71e348de9e23db614e2dcc72fb4ba26ed151cf57
 - Firmware Version: model TT , 2.3.4  revision 55baf3a
 
**Describe the bug**
We are missing ling to github or commit version and we need to look it up in Suite log.

**Steps to reproduce:**
1. Load suite
2. Go to Settings/General
3. Check version

**Expected result:**
Commit or link to GitHub

**Actual result:**
Just generic info. `You are currently running version 20.10.1. Version is available.`

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/95199124-9e010a80-07dc-11eb-8bbb-20118383d63b.png)

**Comment by prusnak** [comment]
Git commit is available from `/version` page, e.g. https://suite.corp.sldev.cz/suite-web/develop/web/version/

**Comment by bosomt** [comment]
enough for me,
@keraf close ?

**Comment by mroz22** [comment]
At least copy is weird. It indeed looks like that a variable that was originaly passed into the string might be missing now.

**Comment by bosomt** [comment]
Yes it looks strange ;)

**Comment by keraf** [comment]
Yep, there's a wee bug. I'll get all that fixed :slightly_smiling_face:

**Comment by bosomt** [comment]
**QA OK**

Microsoft Windows [Version 10.0.18363.1082]
Suite win app commit a26355244abe0850d23e6c353b5e157f44f12694
Device Trezor model T 2.3.4
