### ISSUE TITLE
Google oauth fail 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2528]
Version: 67fdb77ab781ef6d283344614bc7285545e1f60d 

Both Google and Dropbox fail to get authorized.

<img width="632" alt="Screenshot 2020-10-06 at 15 01 02" src="https://user-images.githubusercontent.com/29627086/95204895-f76d3780-07e4-11eb-8d37-a18d8439e173.png">

<img width="631" alt="Screenshot 2020-10-06 at 15 04 51" src="https://user-images.githubusercontent.com/29627086/95205323-811d0500-07e5-11eb-9038-d9e16d55e94c.png">

Also closing down the window leaves the user with modal with disabled button for Dropbox as well.

<img width="1351" alt="Screenshot 2020-10-06 at 15 02 13" src="https://user-images.githubusercontent.com/29627086/95205034-208dc800-07e5-11eb-9604-fc8e2eba0758.png">

**Comment by prusnak** [comment]
@matejzak Can you please try again? We changed the paths in develop (from "wallet" to "web" in the URI) and this was not reflected in the Dropbox/Google Oauth integration. I just added the new paths to reflect the change.

**Comment by glacierbits** [comment]
Dropbox works now, unfortunately Google Drive still returns (400).

**Comment by mroz22** [comment]
The problem with google might be that I am using clientId for iOS for both versions (desktop and web) at the moment. It works for localhost but might not work elsewhere. I'll try to use both of them for respective environment.

**Comment by tsusanka** [comment]
The Google will be hidden for the release. We will fix this later.

**Comment by prusnak** [comment]
Fixed via https://github.com/trezor/trezor-suite/pull/2753

**Comment by prusnak** [comment]
I guess this should go into Approved because this was tested already via https://github.com/trezor/trezor-suite/issues/2905 ?

**Comment by bosomt** [comment]
@prusnak yes, both providers are working, tested today

**QA OK**

Nixos + Firefox Browser 82
Suite web dev master commit 374d027
Device model T fw 2.3.4 commit 50854b921
