### ISSUE TITLE
Labeling: Fixes

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2534]
- [ ] Rename Account – **Cursor is not visible** 

- [ ] **Remove the original name** on both Account and Wallet on hover – It's irrelevant, user can still see it when deleting the label. 

- [ ] Rename Wallet – Apply **the same design principle** (**[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f3bf73d694a9912ac30606f)**) as renaming the Accounts. Use the tag `Rename`, get rid of the edit menu, since clicking on the wallet name is not intuitive and may load the wallet itself as opposed to opening the menu.

**Comment by sorooris** [comment]
**QA OK**

> Suite: app 20.10.1 a263552
> OS: Windows 10
> Device: model T 2.3.4 50854b921

 - [x] Rename Account – Cursor is not visible
 - [x] Remove the original name
 - [x]  Rename Wallet
