### ISSUE TITLE
Onboarding - Device Firmware update process logic

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2541]
**Info:**
 - OS: Nixos + Windows 10
 - Wallet Version: 20.10.1 app, commit 426ce98fbcb16af057d8b2f5d636f88f4e374a23
 - Firmware Version: 2.3.1 model T, revision c6b2580cd
 
**Describe the bug**
Looks like Suite is not detecting FW version correctly during model T FW update When in bootloader mode.
Please see video. I was able to replicate it via Nixos and Windows app builds.
No idea if it shows booloader version /i have only 2.0.3 BL devices/

I tried to check same process with T1 model but it says. Error: Cannot read property 'code' of null
See screenshot, When I press retry it only shows Onboarding modal without any kind of info

**Steps to reproduce:**
1. Start Suite app and connect empty device with older FW
2. Start onboarding and FW update
3. When asked to install press X on device and continue with process

**Expected result:**
Suite should say firmware version according to installed FW

**Actual result:**
Suite says firmware version is 2.0.3 , and not 2.3.1

**Screenshots:**
Video: https://www.youtube.com/watch?v=fzOasmoNDDQ&feature=youtu.be

![image](https://user-images.githubusercontent.com/31506317/95346648-5ea9eb00-08bc-11eb-8484-174188f8ada0.png)

![image](https://user-images.githubusercontent.com/31506317/95346563-4b971b00-08bc-11eb-8162-7d99f284e2c2.png)

**T1**
![image](https://user-images.githubusercontent.com/31506317/95347757-8a79a080-08bd-11eb-99b4-306357c994e6.png)

**T1**
![image](https://user-images.githubusercontent.com/31506317/95347945-c9a7f180-08bd-11eb-95f0-db6fd323e553.png)

**Comment by tsusanka** [comment]
Firmware prints firmware version in the `major_version`, `minor_version` and `patch_version` fields when in firmware but bootloader version when in bootloader (I agree that might be confusing).

**Comment by mroz22** [comment]
Yeah, I know this oddity. Just missed it in this screen. This is easy to fix. Just need to print another variable.

**Comment by mroz22** [comment]
There are two problems here:
1. wrong action taken upon clickig on retry button. it should retry firmware update right away probably?  Well, I am not sure about that but it seems better to me than to reset to the initial firmware screen. Something is done here https://github.com/trezor/trezor-suite/pull/2587
1. "code" of null shall be separate issue. This is something in trezord / trezor-link and possibly (if can't be fixed in any of the two mention) then it should be 'hack-fixed' in trezor-connect.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 81
Suite web dev master commit 4d4a9f3f493613c0a86f905414dd8071c55ac69e
Device model T FW 2.3.3 commit 0d5f00668
