### ISSUE TITLE
Add translations for landing page manually

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2544]
<s>Please _"Crowdin-ify"_ Suite landing page: https://suite.corp.sldev.cz/suite-web-landing/develop/  </s>

Let's replace the texts manually.

**Comment by tsusanka** [comment]
As discussed let's merge #2551 after the release. For now let's replace the texts manually.

**Comment by sorooris** [comment]
@matejzak anything for QA to test?
