### ISSUE TITLE
Ethereum Transactions Details are missing ERC20 info

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2549]
**Info:**
 - OS: Nixos  + Windows
 - Browser: Chromium , version 85
 - Wallet Version: web, commit 3240a95b49269692b73fcfbdff3a26f61b13bffe + 20.10.1 version
 - Firmware Version: TT model 2.3.4 , revision 50854b921
 
**Describe the bug**
There is no information about sent ERC20 tokens. Transaction detail only shows fees.

**Steps to reproduce:**
1. Load Eth accounts in Suite
2. find ERC20 transaction
3. open transaction detail.

**Expected result:**
You will see info about sent tokens

**Actual result:**
you only see that you sent 0 ETH + ETH fees

**Screenshots:**
Transaction: https://eth1.trezor.io/tx/0xd287082022c387f538869cf80cd3b5572fd9c241a8a233da117c65d552d80840

Transaction in Transaction list:
![image](https://user-images.githubusercontent.com/31506317/95442861-2f4abb00-095c-11eb-9b45-c50c9191c2ee.png)

Transaction detail: 

![image](https://user-images.githubusercontent.com/31506317/95442818-20fc9f00-095c-11eb-9fb7-3d739f0365a1.png)

**Comment by glacierbits** [comment]
I suggest the following (to be consistent with current state of things in Send): 

- [ ] Header: Receive / Sent `ERC20 token` 

- [ ] Amount: n `ERC20 token` 

- [ ] Fee: n `ETH` 


<img width="787" alt="Screenshot 2020-10-08 at 14 57 29" src="https://user-images.githubusercontent.com/29627086/95461500-98d7c300-0976-11eb-8ab4-805f3db4afff.png">

**Comment by bosomt** [comment]
**QA OK**

Microsoft Windows [Version 10.0.18363.1082]
Suite win app commit a26355244abe0850d23e6c353b5e157f44f12694
Device Trezor model T 2.3.4
