### ISSUE TITLE
App download - MacOS zip contents, unable to install app

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2550]
**Info:**
 - OS: any
 - Browser: N/A
 - Suite Version: .zip from staging 426ce98f
 - Firmware Version: N/A
 
**Describe the bug**
Contents of the .zip file of the MacOS version does not allow installation of the app.

**Steps to reproduce:**
1. Navigate to the landing page
2. Select the MacOS version of the app and download the .zip file
3. Unpack the .zip file

**Expected result:**
A .dmg or .pkg file is inside the .zip that allows an easy installation.

**Actual result:**
A folder with a .exe file is unpack from the .zip with no .dmg or .pkg file present.

**Screenshots:**
N/A

**Comment by prusnak** [comment]
That's happening because we create ZIP both for Windows and MacOS. The CI randomly overwrites the ZIP result (depending on which job was run as the last).

We should be serving DMG or PKG as the final installer file for macOS and not ZIP (which is just an intermediate product).

**Comment by sorooris** [comment]
QA OK

.dmg file downloaded and installed correctly. :tada: 

Suite version: staging landing page, app e6ba320201b76c285b569b99f1e4b095e53f0028
OS: MacOS Catalina 10.15.6
Device: N/A (later connected model T 2.3.4 50854b921)
