### ISSUE TITLE
Add new Account tab: Trade [SOON]

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2552]
Note: The copy will likely change, add it to Crowdin please. 

- [ ]  Tab "Trade" (disabled of course)
- [ ]  Tag "SOON" as shown on the Exchange, Spend sub-tab 

[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f7eeac0813e4db7e7d0eaef)

**Comment by sorooris** [comment]
**QA OK**

Trade tab is displayed with the soon tag correctly; disabled correctly.
> Suite: app 20.10.1 a263552
> OS: Windows 10
> Device: model T 2.3.4 50854b921

![image](https://user-images.githubusercontent.com/10185314/95691666-04dd5400-0c21-11eb-9cae-ebf629f708d8.png)
