### ISSUE TITLE
ETH transaction detail: Input shortened

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2554]
The transaction input is shortened for no particular reason.

<img width="803" alt="Screenshot 2020-10-08 at 14 51 11" src="https://user-images.githubusercontent.com/29627086/95460824-b9ebe400-0975-11eb-90a4-21a2a424619c.png">

**Comment by sorooris** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/10185314/95694329-cac87e00-0c31-11eb-90c4-2869b0506518.png)
> Suite: app 20.10.1 a263552
> OS: Windows 10
> Device: model T 2.3.4 50854b921
