### ISSUE TITLE
Tokens: Unnecessary overflow

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2555]
Let's aling `Balance – USDT` in one line. 

<img width="820" alt="Screenshot 2020-10-08 at 15 06 00" src="https://user-images.githubusercontent.com/29627086/95462430-ca04c300-0977-11eb-8c07-1c0ed1814571.png">

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 81
Suite dev web 4d4a9f3
Device model T 2.3.4 commit 50854b921
