### ISSUE TITLE
Filter & Search: Empty states improvement

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2556]
- [ ] Remove the coin icon when only 1 coin enabled: **[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f7f305f0dd94258e3c916f3/)**

- [ ] Show empty state for no search results: **[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f7f3060de903040bba7b176/)**

**Comment by bosomt** [comment]
QA OK

Nixos + Firefox 81
Suite dev web 4d4a9f3
Device model T 2.3.4 commit 50854b921
