### ISSUE TITLE
Device Dis/connected: Switch Wallet Navigation

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2558]
The text should appear (please animate) for ± 1 second upon the device connection state change. 

- [ ] Connected: https://zpl.io/bAoAGOq 
- [ ] Disconnected: https://zpl.io/2vJyWGn

**Comment by slowbackspace** [comment]
@matejzak could we get some preview of how the animation should look like from a designer? Simple fade in/out effect or something more complex like the text should slide out from the icon to the left side and then slide back in?

**Comment by glacierbits** [comment]
For sure! Thanks for asking. We have this prototyped actually, just need to find the file. Not sure what the effect is called, but I remember it rolled out from side, fading in letter by letter (and back).

**Comment by robertbrada** [comment]
How do I practically achieve the "**DISCONECTED**" state to appear? When I unplug the device, _**Connect and unlock your Trezor**_ modal appears and I can't see wallet state.

**Comment by glacierbits** [comment]
You have to "remember" the device first (in wallet switch modal).

**Comment by wendys-cats** [comment]
**QA NOK**
**Suite** web develop branch commit f06aff6c9282977e76f17857073fd85704fb7118
**OS** NixOS + Chromium 85
**Device** TT 2.3.4 public **AND** T1 1.8.3 revision 0xdf0963ec48f01f3d07ffca556e21ff0070cab099

**Actual**
Images are not the same (disconnected device has the same icon as a connected). No animation, sadly.

**Expected**
Promies animation. Icons will correspond with Zeplin (difference between connected and disconnected/used elsewhere device)

![image](https://user-images.githubusercontent.com/58593111/97874898-f95de400-1d19-11eb-9939-8f133a376e65.png)
![image](https://user-images.githubusercontent.com/58593111/97875933-645bea80-1d1b-11eb-8981-9bb21e5c7a1b.png)

**Comment by robertbrada** [comment]
**According to the animation behavior:** 

For now, the animation works only on hover effect in the following component:
![wallet-anim-1](https://user-images.githubusercontent.com/44506010/97892786-5d87a480-1d28-11eb-9586-1ea4da03fa58.png)

The animation reacting on device dis/connected status change will be implemented until the next freeze in December. So this animation issue should be opened. 

**According to the same icon for dis/connected device:**
This behavior should be unrelated to the animation changes I made in [this PR](https://github.com/trezor/trezor-suite/pull/2664/files).

So maybe it's some older issue or it's related to the changes made in [f06aff6](https://github.com/trezor/trezor-suite/commit/f06aff6c9282977e76f17857073fd85704fb7118).

**Comment by glacierbits** [comment]
Correct. This issues was to deal with the "navigation" component only. I corrected (improved) the title and created a new issue for the "switch wallet modal" for upcoming sprint. My apologies for the confusion.

**Comment by wendys-cats** [comment]
@matejzak should I report [this](https://github.com/trezor/trezor-suite/issues/2558#issuecomment-720486647) in a separate issue?

**Comment by glacierbits** [comment]
Yes please. Thanks! it skipped my attention totally.

**Comment by wendys-cats** [comment]
Thank you. Issue is reported [here](https://github.com/trezor/trezor-suite/issues/2847).

**Comment by wendys-cats** [comment]
**QA OK**
**Suite** web staging 20.11.1 commit 11ef2d3
**OS** NixOS + Chromium 85
**Device** TT 2.3.4 public **AND** T1 1.9.3 public
