### ISSUE TITLE
Remembered wallet accessible without device on Suite APP

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2563]
**Info:**
 - **OS:** Windows 10 
 - **Suite Type:** APP **Commit:** bcf7ad8a43857cd90086a558a49c23a0df65216c
 - **Firmware:** 2.3.4 TT **revision** 50854b921
 
**Describe the bug**
User installs a new version of Suite APP after a longer period of not using it (a month, in this case). If user had a wallet ticked off as remembered, this new version of Suite APP will open with this wallet - with no device needed and with OLD DATA such as balance on the accounts and so on. For example, an account that has been since emptied will seem to have assets on it, and so on. 
While technically not a bug, it is important to note that such behavior will most likely be very confusing for the user  - showing OLD DATA of user´s assets should not be and intended behaviour. 

**Steps to reproduce:**
**1.** Install Suite APP
**2.** Remember a wallet with assets and transactions
**3.** Wait a month
**4.** Install the newest Suite APP
**5.** Open Suite without device 

**Expected result:**
Cleared cache and sessions upon installing new version OR after a certain, relatively short, period of time. NOT showing old data of the user´s assets.

**Actual result:**
If there is any cache stored from previous Suite APP, the newly installed version will use it even after a prolonged time (a month) and will display a view only mode of user´s OLD data.

**Comment by tsusanka** [comment]
Thanks. Let's not rush this one into the release though. I agree we might add a warning in case the device has not been connected for some period. Maybe a week? To be discussed.

**Comment by slowbackspace** [comment]
imo it is okay that suite shows remembered device as we don't really want to force users to remember a device again and again after each upgrade, but the stored data (account balances, transactions...) should get refreshed since we don't need a connected device for this. That is a bug.
