### ISSUE TITLE
Duplicate svg coinmarket-error and uni-error

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2569]
```
$ ts-node ./test/test-same-svgs.ts
checking total svgs: 58
Detected that project includes multiple same svgs, exiting with 1
[ [ 'coinmarket-error.svg', 'uni-error.svg' ] ]
```

**Comment by mroz22** [comment]
I understand that author maybe wants to have own error image in the future but does not have it yet. So copied and renamed already existing image as a temporary placeholder? @vladimirvolek

**Comment by vladimirvolek** [comment]
Yes, what should I do? Use the uni-error.svg?

**Comment by mroz22** [comment]
```
if (going to replace it in near future) {
	donothing();	
} else {
	replaceWith(uni-error.svg)
}
```
:D

**Comment by ravinalamada** [comment]
When ran the command, I got these:

$ ts-node ./test/test-same-svgs.ts
checking total svgs: 58
No multiple same svgs found, exiting with 0
Done in 2.67s.

**Comment by matejkriz** [comment]
Thanks @ravinalamada 👍
