### ISSUE TITLE
Data collection: Run time and more..

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2573]
**Log:**

- [ ] Run time (session length?) - For now based on Session ID
- [ ] Maximazed / minimazed app (session length for each?)
- [ ] Number of connected devices at one time 
- [x] Device model detection (T / One)

**Comment by glacierbits** [comment]
Closing this issue in favor of #2882

**Comment by bosomt** [comment]
**QA OK**
nothing to test here

Firefox 82.0 (64-bit) + Nixos
Suide web dev maser commit da17a85
Device mdoel T fw 2.3.4 commit 50854b921
