### ISSUE TITLE
Question: process.env.BUILD

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#2574]
It seems to me that `process.env.BUILD` is not used anywhere:

There is a reference in isDev function which itself is being used but imho works thanks to `process.env.NODE_ENV`
https://github.com/trezor/trezor-suite/blob/83d184e8876f4e6542a8614d1a93ba1a5f823578/packages/suite/src/utils/suite/build.ts#L1-L8

And in a comment here:

https://github.com/trezor/trezor-suite/blob/83d184e8876f4e6542a8614d1a93ba1a5f823578/packages/suite/src/actions/suite/analyticsActions.ts#L217-L221

___

So do I assume correctly that these are only remnants of something that got deprecated in past? At the moment only feature flags should be used and everything is "stable build"?

**Comment by keraf** [comment]
I had a look around and it doesn't seem to be used anywhere from what I can see (not in code, configs or CI). Maybe @szymonlesisz has an idea if it's still (planning to be) used?

**Comment by prusnak** [comment]
> At the moment only feature flags should be used and everything is "stable build"?

This sounds reasonable.
