### ISSUE TITLE
upgrade dropbox lib

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#2575]
- Upgrade `dropbox` lib to the latest version (7, realased 4 days ago). [Guide](https://github.com/dropbox/dropbox-sdk-js/blob/master/UPGRADING.md)
- my-trezor dependency ⚠️

**Comment by tsusanka** [comment]
@mroz22 do we know what date Dropbox will kill the v7? In another words I am trying to find out what is the deadline for this. Mainly my-trezor, in Suite we definitely want to be up-to-date but for my-trezor we could survive on the old lib unless really needed.

**Comment by mroz22** [comment]
This https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens

but it seems that there is enought time as the changes are to come into effect in **September 2021**

v7 api shall still work. suite should work as well as it does not use legacy tokens. It actually does use some legacy APIs but I am not aware of that dropbox is going to kill them. 

only problem is with mytrezor. I am pretty sure that labeling will stop working there in sep 2021, but hopefully mytrezor will be long dead by then

**Comment by tsusanka** [comment]
Thanks! I am noting this in an Asana ticket for August and let's see where we will be at :).

**Comment by tsusanka** [comment]
@alex-jerechinsky will find out if these dates of deprecation still hold

**Comment by jerechinsky** [comment]
While Dropbox already considers long-lived access tokens to be deprecated, they do not have plans to disable already existing long-lived access tokens, i.e. they will live and work past September 2021. What will happen in September 2021 is that they will disable **creation** of long-lived access tokens. 

Source: [https://www.dropboxforum.com/...](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Migrating-to-short-lived-access-tokens/td-p/472597)

@mroz22 could you please share where did you find that a particular version of dropbox lib itself will be deprecated? 

apologies if I'm missing something

**Comment by tsusanka** [comment]
@alex-jerechinsky @mroz22 so do I understand it correctly that while users with enabled labeling will be fine in wallet.trezor.io, users that will enable newly after Sep 2021 might have some troubles?

**Comment by mroz22** [comment]
From https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens

```
we prepare to retire long-lived tokens on September 30th, 2021. This means that:
- You should review your apps permission tab to transition to scopes. (This does not require code changes).
- You should ensure your app works with short-lived access tokens. (This may require code changes).
```

```
On September 30th, 2021, Dropbox will retire the creation of long-lived access tokens —
 resulting in all new tokens being short-lived. For online-only apps that already handle 
re-authentication, users may experience more prompts for re-authentication. Apps that
 require background (“offline”) access but have not yet implemented refresh tokens
 will be impacted.
```

So I think the next step now is to 
- create some testing dropbox account (I may have one)
- set it to use short-lived tokens
- use it in some testing mytrezor build and see if it works or not.

**Comment by tsusanka** [comment]
I am afraid we won't be able to completely kill the old wallet till Sep 30th. So I am afraid we'll have to test this. @mroz22 do you think you could try the steps you are mentioning? :pray: :pray: September is fine of course.

**Comment by mroz22** [comment]
Tested short lived tokens with right now.

### Mytrezor 
1. created new account in dropbox
2. replaced api key in mytrezor
3. observe some errors in http responses regarding scopes permissions in mytrezor
4. set these permissions in dropbox console
- `account_info.read`
- `files.metadata.read`
- `files.content.write`
- `files.content.read`
5. profit. everything works. 

This observation is perfectly inline with what I have cited above: `[...] resulting in all new tokens being short-lived. For online-only apps that already handle 
re-authentication, users may experience more prompts for re-authentication. Apps that
 require background (“offline”) access but have not yet implemented refresh tokens
 will be impacted.`

### Suite (desktop)
1. used the same account from mytrezor testing
2. replaced api key in trezor-suite
3. profit. everything works

Suite already implements `refresh_token` to achieve token renewal and thus "long lived token behaviour" on desktop.

## Suite (web)
1. tested and works

## TPM
1. didn't test yet but it is very likely to work. judging by code it works the same way like mytrezor

## Final thoughts
- don't forget to check permissions

**Comment by tsusanka** [comment]
We have set the short-lived tokens in Dropbox settings and released a fix for TPM. So far nothing seems to indicate that this would break Suite or old wallet. We'll keep an eye on it but let's close for now.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.10.1 (30698b091e0eff94a2adddf92b15998092d7a3c9)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model 1 1.10.3 regular
