### ISSUE TITLE
Electron app's default window size too narrow

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2582]
> OS: any (tested Win10 18363.1082 and NixOS via nix-shell)
> Suite Version: app 20.10.1 a263552
> Firmware Version: any (tested model T 2.3.4 50854b921)

 
**Describe the bug**
Suite electron app opens in a very narrow window size.

**Steps to reproduce:**
1. Start a new instance of the app,
2. Observe.

**Expected result:**
The app opens in a standard ratio (width > height).

**Actual result:**
The app opens in a ratio, where the height is greater than the width.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/95757921-0d2ca200-0ca8-11eb-992f-49f68c48b634.png)
![image](https://user-images.githubusercontent.com/10185314/95757952-19186400-0ca8-11eb-8571-04b4f0da4377.png)
![image](https://user-images.githubusercontent.com/10185314/95758454-ce4b1c00-0ca8-11eb-919e-7aa90ceb2aaa.png)

**Note(s):**
Unable to measure pixel size precisely due to inspect function being disabled in the build.

**Comment by keraf** [comment]
I think we can set the default to the current screen resolution with a 10-20% gap around and with min and max values.

**Comment by sorooris** [comment]
**QA OK**

Couldn't replicate issue, behavior is consistent and window size is remembered when closed and launched again.

Suite version: app 513631a9fa62c438e60397a9942b04275bcd621a
OS: macOS Catalina 10.15.7
Device: 2.3.4 50854b921
