### ISSUE TITLE
Create .deb and .rpm linux packages?

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2584]
Since this should cover most of Linux users let's bundle the AppImage in .deb and .rpm packages?

**Comment by prusnak** [comment]
Nah, AppImage is de-facto standard these days.

**Comment by keraf** [comment]
They are easy to generate, we could provide them (including more options like archives on all platforms). The auto-updater also only works with AppImage, so we would have to provide other ways to keep it up to date (publishing to a repo for example). I guess not a priority but it would be nice to have more options :slightly_smiling_face:

**Comment by prusnak** [comment]
My take: This adds lot of work everywhere (release management, code signing, support, web development for distro detection, etc.) for no apparent good reason. Is there a Linux distribution (which we want to support) which does not support AppImage?

**Comment by tsusanka** [comment]
I am not very keen on it myself. @slush0 asked for it, so let me figure out how strong his feelings are. I didn't know AppImage is that widely supported TBH.

**Comment by slush0** [comment]
Does AppImage provide stuff like creating desktop/startup menu shortcut, installing itself into system directory, installing system services or starting after system startup etc?

I didn't specifically asked for DEB, but for tighter integration with OS.

**Comment by keraf** [comment]
That's currently an issue with AppImage with Electron Builder. It used to offer desktop integration but now recommends to rely on AppImageLauncher which is up to the users to install ([read more](https://www.electron.build/configuration/appimage)). On the latest Ubuntu for example, you can run AppImage without problem but it doesn't install, meaning some of the features like custom protocols don't work.

I think it would be great to have more installation packages available for Linux and publish them on their repository. Sure it's more maintenance, but if we have the time and resources, we can automate this. Another downside from generating more targets, is that it will increase the build times.

**Comment by tsusanka** [comment]
We want to do this eventually but let's wait for the first data coming in regarding how many people are using Linux. We are also thinking about writing some nice tutorial.

**Comment by domve** [comment]
+1 for this, AppImages just seem like a lazy way of bundling software. I was excited when I saw there were .rpm packages for trezor-bridge and trezor-udev, if you could accomplish that I don't see why providing proper packages for the Trezor Suite would be a huge problem.

**Comment by tsusanka** [comment]
>

**Comment by domve** [comment]
If anyone is still interested, I made a COPR repo with .rpm packages for Fedora and RHEL. At the moment it's just repackaging the AppImage from the latest GitHub releases, but it seems to work fine. 
(also has proper desktop integration)

https://copr.fedorainfracloud.org/coprs/domve/pkgs/
```
dnf copr enable domve/pkgs
dnf install trezor-suite
```

**Comment by prusnak** [comment]
@domve Great! Can you get the package to the official Fedora repo, so users don't have to add your user repo?

**Comment by domve** [comment]
I'm not sure if it would be accepted into the official repo, but getting it into RPM Fusion might be a lot easier since their packaging guidelines seem a bit more relaxed and straight forward. I'm not really a package maintainer though, so I'll have to look into it a bit more

**Comment by AnglDavd** [comment]
Maybe a snap on https://snapcraft.io/

**Comment by tsusanka** [comment]
We could also pack our udev rules inside the .deb/.rpm right? That would help because downloading Suite and then fiddling around with the udev rules is a bit weird. @prusnak we can have one .deb/.rpm which install both udev and Suite right?

**Comment by prusnak** [comment]
> @prusnak we can have one .deb/.rpm which install both udev and Suite right?

Yes. That said I am not a big fan of that because using deb/rpm would nuke the autoupdate. We need to discuss what are our goals for Linux distribution.

> That would help because downloading Suite and then fiddling around with the udev rules is a bit weird.

We could try to install udev rules also via AppImage - https://github.com/trezor/trezor-suite/issues/3664

**Comment by prusnak** [comment]
I think it's up to the respective distributions maintainers to decide whether they want to maintain Trezor Suite in their repositories. We don't have resources to maintain packages in each possible distribution.

Where we should aim form are the following means of distribution:
* AppImage - already done - we just need to figure out how to add udev-rules to the package - https://github.com/trezor/trezor-suite/issues/3664
* Snap/Snapcraft - https://github.com/trezor/trezor-suite/issues/3696
* Flatpak/Flathub - https://github.com/trezor/trezor-suite/issues/3697

Closing in favor of issues linked above.
