### ISSUE TITLE
Redundant scroll bar in onboarding

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2588]
I am using desktop version in fullscreen and my viewport size is 1920 × 948 based on whatismyviewport.com.

![image](https://user-images.githubusercontent.com/1835345/95825228-d5b60800-0d30-11eb-8d6c-99a2581ebbfb.png)

Revision: b8ea32c7bce1702e0c990324921df77c5669152a
OS: NixOS
Browser: Firefox 81

**Comment by mroz22** [comment]
This is probably going to happen more often now as the copy team is doing their work. But yeah, we probably should scale the image instead of addding scrollbar? I don't know :thinking:

**Comment by tsusanka** [comment]
Could someone confirm this happens to them as well? If it affects more of us and is easy let's fix it now.

**Comment by mroz22** [comment]
From what I remember it shall affect every user at the moment. This modal window has fixed dimensions. But what is the fix? Scaling down the image if needed?

**Comment by wendys-cats** [comment]
**QA OK**
**OS** Windows 10 Home 19041.1508
**Suite** Type APP **Commit** e6ba320201b76c285b569b99f1e4b095e53f0028
**Device** TT 2.3.4. 50854b921

Tested on Windows APP, no redundant scrollbar.

**Comment by sorooris** [comment]
**QA OK**

Suite Version: app, commit e6ba320
OS: MacOS Catalina 10.15.6
Firmware Version: T1 1.9.3 0d5f006
