### ISSUE TITLE
Add latest 2.3.4 firmware

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2591]
When I have 2.3.3 on my model T Suite says it is the latest but we have released 2.3.4 already a week ago. I think just some sync is needed? We should do it before the release. cc @szymonlesisz

**Comment by szymonlesisz** [comment]
it's waiting to be merged and released in connect:
https://github.com/trezor/connect/pull/692

**Comment by sorooris** [comment]
**QA OK**

App detected older firmware on device correctly, didn't encounter any bugs during update flow, updated to 2.3.4 50854b921 successfully.

Suite Version: app, commit e6ba3202
OS: MacOS Catalina 10.15.6
Firmware Version: model T 2.3.3 0d5f006
