### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2594]
## 👋 Say hello to Trezor Suite! 
`Welcome to the first public beta version`

### 🔑  Key features

- Desktop app 
- Bech32 accounts 
- Send & Receive experience 
- Coin discovery UX and performance
- Historic rates for supported coins .. and more! 

### 🌟 Improvements  
- Rename accounts, wallets, addresses
- Filter accounts, incl. account labels 
- Snack notifications design
- Transaction detail modal
- Passphrase and other modals

**Comment by glacierbits** [comment]
@tsusanka @keraf Let me know if I should edit anything, or feel free do it by yourselves. Thanks!

**Comment by tsusanka** [comment]
LGTM. @keraf do I understand correctly we will add this to the Github release page and Suite fetches it from there, correct?

**Comment by keraf** [comment]
Yep, that's correct.

**Comment by prusnak** [comment]
Created a release here (desktop binaries will come soon) and the changelog is copy-pasted there: https://github.com/trezor/trezor-suite/releases/tag/v20.10.1

Closing the issue
