### ISSUE TITLE
Checking.. button in settings is stuck

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2595]
As reported in https://github.com/trezor/trezor-suite/issues/649#issuecomment-706794717. I am creating a new issue to make sure it does not get lost. The update probably errors out and does not reset the state of the button.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 81
Suite web commit 4d4a9f3f493613c0a86f905414dd8071c55ac69e
Device model TT 2.3.3 FW commit 0d5f00668
