### ISSUE TITLE
Onboarding steps: incosistent subheading and description styles

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2599]
![Screen Recording 2020-10-13 at 13 03 15](https://user-images.githubusercontent.com/6961901/95854673-8cc57a00-0d57-11eb-9823-6f7225e945bc.gif)

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 81
Suite dev web 4d4a9f3
Device model T 2.3.4 commit 50854b921
