### ISSUE TITLE
Add account modal - unnecessary scrollbar

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#2602]
Add account without the menu

![image](https://user-images.githubusercontent.com/3112191/95865747-4bd56180-0d67-11eb-8f67-908c3716b6eb.png)

Click into the cryptocurrency select

![image](https://user-images.githubusercontent.com/3112191/95865415-f4cf8c80-0d66-11eb-8e18-b9a331161573.png)

**Comment by wendys-cats** [comment]
QA NOK
Browser Chromium 85 OS nixOS
Suite [web](https://suite.corp.sldev.cz/suite-web/develop/) 4d5d94c51164f229f2f2f3796bc9f2c42f12a5fb
Device TT 2.3.4 public revision 50854b921

Issue still persists. 
Note - unnecessary sidebar appears when user is choosing cryptocurrency, it is not there by default.

![image](https://user-images.githubusercontent.com/58593111/97164391-55f15a00-1782-11eb-92f0-ef7652767f13.png)

**Comment by slowbackspace** [comment]
@wendys-cats  It's most likely because the fix was not deployed yet 😛 could you give it another shot in cca 30-60 mins? 🙇

**Comment by wendys-cats** [comment]
**QA OK**
Browser Chromium 85 OS nixOS
Suite web d9ca3ad66cc33ddecb9b55121891d1a456d16e4c
Device TT 2.3.4 public revision 50854b921
