### ISSUE TITLE
Wipe with remembered wallet results in incorrect behaviour

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2604]
**Info:**
 - OS: Windows 10 Home
 - Suite Type: APP Commit b8ea32c7bce1702e0c990324921df77c5669152a
 - Firmware Version: 2.3.4. 
 
**Describe the bug**
When user wipes device with remembered wallet and skips backup, suite will not navigate him to create a new standard/hidden wallet. Instead, after skipping backup, the modal will only close and user is still in Settings (where user clicked on wipe). From Settings, user can go to Accounts - which are loaded with data from previous, now wiped, seed. And while Suite recognizes that this wallet does not have a device connected, at the same time in Choose wallet/Choose device modal there is only ONE device - the one currently active.

**Steps to reproduce:**
1. Load wallet with not empty accounts
2. Remember wallet
3. Wipe device
4. Browse through remembered wallet data

**Expected result:**
Suite navigates user to new wallet, either standard or with passphrase AND will correctly distinguish between the remembered wallet (with wiped device that is technically not connected) and the "new" device and wallet.

**Actual result:**
Mixup where Suite assigns the remembered wallet (with wiped seed) to the "new" device (with a different seed).

**video:** https://drive.google.com/file/d/1To16r1hlgXLksa5aHHPzARO6f9pWjB56/view?usp=sharing

**Comment by slowbackspace** [comment]
Can't we just delete all remembered wallets that belonged to the wiped device? 🤔

**Comment by bosomt** [comment]
**QA NOK**

Still broken in latest builds.
When you wipe device and recover/create new wallet old. **NOT** remembered wallet is still loaded when you don't disconnect device, and you will get this error.

Probably best practice would be Wipe = delete loaded/saved wallet, or at least ask user.

Suite app commit 887ea0551eb987b2ac61ef5a15764da0f2da9971


![image](https://user-images.githubusercontent.com/31506317/100337907-3a26e100-2fd8-11eb-88f7-4a4479f09273.png)

**Comment by bosomt** [comment]
Can you raise priority of this issue ? 
It's really confusing to have previous shown in suite as connected after you wipe device and load it with different seed/wallet.
It doesn't even need to be remembered, all you need it to not reconnect device /you are not asked to do that/

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.1.0 (93c2576e8a22b770241222de191c1508c595821c)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.3 regular

**Comment by wendys-cats** [comment]
QA OK

Suite version: APP 21.1.0 (93c2576)
OS: NixOS 21.03
Device: TT 2.3.4 public
