### ISSUE TITLE
Wallet associated with another seed remembered after wipe and onboarding

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2606]
**Info:**
 - Suite Version: app, commit b8ea32c
 - OS: any (tested MacOS Catalina 10.15.6)
 - Firmware Version: T1 1.9.3, 0d5f006
 
**Describe the bug**
Previously accessed **wallet** and associated accounts is still **accessible after factory reset when remembered** compared to the behavior in the MyTrezor wallet where user is **forced to disconnect** and reconnect their **device** while an overlay is displayed and the wallet becomes inaccessable.

**Steps to reproduce:**
1. Launch Suite and **remember** loaded wallet,
2. Navigate to Settings -> Device and select confirm **Factory reset/Device wipe**,
3. Select Create backup and proceed with onboarding,
4. **Skip backup** and access wallet,
5. Navigate to accounts and **display** an arbitrary **receive address**.

**Expected result:**
Creating a new wallet and skipping backup displays a new wallet with new accounts regardless of whether the previous wallet was rememberd.

**Actual result:**
An error message with _Verify account error: Passphrase is incorrect_ is displayed.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/95870663-0d42a580-0d6d-11eb-94e4-d292300d50ba.png)

**Comment by sorooris** [comment]
May be related to #1601.

**Comment by jerechinsky** [comment]
@sorooris could you please retest?

**Comment by sorooris** [comment]
**QA OK**

Couldn't replicate the issue, closing; followed the steps described above which correctly result in fresh new addresses instead of the remembered ones being displayed.

![image](https://user-images.githubusercontent.com/10185314/114744309-d7976d00-9d4d-11eb-9516-244a46608141.png)

Suite: web 21.4.1 1baa8ced16f2f6a5d60e9f4d7911669f856123d8
Remembered wallet: yes
Browser: Chromium 89.0.4389.82
OS: NixOS 20.09
Device: 1.9.4 ffa9620
