### ISSUE TITLE
Send: scan qr code is not working in suite-desktop

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#2612]
Installation failed
Permission to access the camera was denied.

**Comment by slowbackspace** [comment]
@keraf could this be related to security hardening? https://github.com/trezor/trezor-suite/issues/901

In browser it asks for a permission to use webcam.
edit: oh  I see szymon is already on it 🚀 

<img width="806" alt="Screenshot 2020-10-14 at 10 02 29" src="https://user-images.githubusercontent.com/6961901/95960712-60b40280-0e04-11eb-9673-700fc9e6c116.png">

**Comment by keraf** [comment]
I think there's a permission needed on Mac (in the plist file).

Edit: I can confirm this doesn't happen on Ubuntu (both in dev and prod builds). Not sure about Windows but I think it's a Mac only issue. Hence my suspicion of a missing permission in the plist file: 
```
    <key>com.apple.security.device.camera</key>
    <true/>
```

**Comment by szymonlesisz** [comment]
@trezor/qa can you confirm that this is working on windows build (it is only macos issue)? if so, it should be fixed by https://github.com/trezor/trezor-suite/pull/2624 (works locally)

**Comment by sorooris** [comment]
Confirming MacOS-specific, verified following: 
- Windows 10 app **OK**
- Kubuntu app **OK**
- NixOS app **OK**
- MacOS app **NOK**

**Comment by prusnak** [comment]
This is supposed to be fixed by #2624 - I will provide signed binaries for macOS soon (1 hour tops). Will let you know so you can test this.

**Comment by prusnak** [comment]
Deployed signed macOS binary with camera fix to staging. Camera works for me (app asks for extra permission when using the cam for the first time), but please test as well. Thanks!

**Comment by sorooris** [comment]
**QA OK**

Suite Version: app, commit 99959260d5639480dfb11e53a4f2ab1d789b0e7b
OS: MacOS Catalina 10.15.6
Firmware Version: T1 1.9.3 0d5f006

![image](https://user-images.githubusercontent.com/10185314/95988768-ab944100-0e29-11eb-8afd-8b523179dba1.png)
