### ISSUE TITLE
Prioritize autoupdate over discovery

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2613]
Currently in case Suite finds a new version it still asks for a device and does a discovery. The user should be able to update Suite even without a device connected.

**Comment by tsusanka** [comment]
Actually I would also like to get into settings before plugging in device. That's even a prerequisite for people that want to set their own blockbook instance.

**Comment by bosomt** [comment]
QA OK

Windows 10
Suite signed test version commit 48b5674
