### ISSUE TITLE
Firmware update on T1 fails on entering bootloader on NixOS - model T instructions are displayed

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2614]
**Info:**
 - OS: NixOS
 - Browser: desktop app
 - Suite Version: https://staging-suite.trezor.io/ - release/2020-10 - https://github.com/trezor/trezor-suite/commit/e6ba320201b76c285b569b99f1e4b095e53f0028
 - Firmware Version: 1.9.0
 
**Describe the bug**
After entering T1 bootloader I receive instruction to enter bootloader again (for TT!) even though I am already in bootloader (and I use T1!).

**Steps to reproduce:**
1. Install older firmware on T1
2. Launch Suite and go through onboarding
3. Enter bootloader and observe

**Expected result:**
The bootloader is detected and the install continues.

**Actual result:**
Instructions for model T bootloader are displayed.

**Screenshots:**
First:
![image](https://user-images.githubusercontent.com/1835345/95896694-f14efc00-0d8c-11eb-8933-245e8305bd0a.png)

And then:
![image](https://user-images.githubusercontent.com/1835345/95896531-a9c87000-0d8c-11eb-9d0f-d44aa7fb6fa8.png)

**Comment by tsusanka** [comment]
@sorooris if you could do a retest tomorrow. @mroz22 if you could have a look tomorrow.

**Comment by bosomt** [comment]
@tsusanka

First picture:  this is what I see when i disconnect 1.9.2 device to enter bootloader , problem is that when you have remembered wallet from previous connected device.

Picture two: But I was **not able** to reproduce it with 1.9.2 device in Windows  10.0.18363.1082and commit e6ba320201b76c285b569b99f1e4b095e53f0028
I only saw T1 instructions

![image](https://user-images.githubusercontent.com/31506317/95952755-fd70a300-0df8-11eb-9cae-07615a8dc2da.png)

this is what I see when I cancel installation

![image](https://user-images.githubusercontent.com/31506317/95953284-ed0cf800-0df9-11eb-9a5d-fa652b71abd4.png)

**Comment by mroz22** [comment]
Just tried it on 1.9.1, using webusb. In both standalone firmware and onboarding and it did well. 

I try it with multiple devices, that may be the root of the problem.

**Comment by tsusanka** [comment]
@bosomt I have deleted Suite's storage to make sure. So no stored wallets and I am still able to reproduce this. Could you please try with 1.9.0? And once with Linux and once with Win again? Thanks.

**Comment by mroz22** [comment]
I could partially reproduce:
1. have T2 remembered
1. star fw update with 1.9.1
1. disconnect
1. screen with T2 appears
1. reconnect T1 in bootloader
1. screen with T1 appears and I can start fw update.

**Comment by tsusanka** [comment]
Hmm interesting, I was **not** able to reproduce this on the web version (https://staging-suite.trezor.io/web/) on the same revision! So this is some weird bug in the desktop app.

**Comment by tsusanka** [comment]
@mroz22 that is not my bug :). Please try to reproduce in the desktop app. Yours is a bit edge-casy but mine seems as a very common workflow (I really did not do anything else).

**Comment by mroz22** [comment]
Checked desktop app and could not reproduce. Same revision.
Running on Ubuntu

**Comment by tsusanka** [comment]
That is very interesting. Maybe it is NixOS only and related to #2615? :thinking:

**Comment by tsusanka** [comment]
Hm I was **unable** to reproduce on my personal Arch Linux..

**Comment by tsusanka** [comment]
@bosomt can you please confirm also here this does not happen on Kubuntu?

**Comment by bosomt** [comment]
@tsusanka KUbuntu **OK**

**Comment by tsusanka** [comment]
I believe this is a duplicate of #2615.
