### ISSUE TITLE
Device not recognized when desktop app is run first on NixOS

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2615]
**Info:**
- OS: NixOS
- Browser: desktop app
- Suite Version: https://staging-suite.trezor.io/ - release/2020-10 - e6ba320
- Firmware Version: 1.9.0
 
**Describe the bug**
If I do not have bridge running already and connect the device _after_ Suite is launched, Suite does not find the device. See steps to reproduce for a better idea.

**Steps to reproduce:**
1. Make sure Bridge is not running. Use: `pkill trezord`
2. Disconnect all your devices.
3. Launch Suite.
4. Connect any device.

**Expected result:**
Suite loads up.

**Actual result:**
Nothing happens :(. Suite is stucked at "Connect and unlock your Trezor" even though the device is connected.

**Note(s):**
On a next Suite's launch (when I do not kill trezord) everything seems to work.

I am really unsure if this is not just some weird setup of mine. Because I have reproduced this also with current Trezor Beta Wallet (20.9.1 -  e243afdb73e35fa08f39a7fc08a28b84baa3ac58) and I am somewhat sure it worked just fine there before.

**Comment by tsusanka** [comment]
I am also experiencing this when I forget the device and reconnect it back. I am really wondering if I am the only who experience this. cc @trezor/qa

**Comment by slowbackspace** [comment]
huh, I cannot reproduce it on macOS. Suite correctly starts its own bridge and device is recognized (both TT and T1 with 1.9.3fw). Is the bridge running on your system after you launch Suite?

**Comment by mroz22** [comment]
Just tried it on 1.9.1, using webusb. In both standalone firmware and onboarding and it did well. 
Don't you work with multiple devices or something like this?

**Comment by tsusanka** [comment]
@slowbackspace yes it is. `pgrep trezord` returns PID.

**Comment by tsusanka** [comment]
@mroz22 if you say "using webusb" that implies you are using the browser version, nope? I am experiencing this with the desktop app.

**Comment by mroz22** [comment]
sry wrong issue. delted

**Comment by bosomt** [comment]
Windows 10: I was not able to reproduce it 

1)killed trezord, 
2) checked it via http://127.0.0.1:21325/ 
3) started suite
4) device was recognized and trezord was running at http://127.0.0.1:21325/

i will check Kubuntu and Nixos too

**Comment by bosomt** [comment]
Nixos: I was able to reproduce it, I can clearly see that accounts are loaded in background but modal `Connect and unlock your Trezor` is still overlapping Suite. After restart of suite it works fine

![image](https://user-images.githubusercontent.com/31506317/95954479-aae4b600-0dfb-11eb-84c8-6fed315ee99a.png)

**Comment by tsusanka** [comment]
I was **unable** to reproduce on my personal Arch Linux. Let's see what happens on @bosomt's Kubuntu, but it indeed seems this is related only to NixOS and is related to #2614.

**Comment by tsusanka** [comment]
I think it kind of makes sense. Same as @prusnak mentioned the autoupdater does not work on NixOS, I think it is the same with Bridge. And since QA has Bridge installed they did not catch this becuase they did not turn off Bridge beforehand. Yet another need for test scenarios.

**Comment by bosomt** [comment]
Looks to me like problem with embedded Trezor Bridge.

`ps aux | grep trezord
tbosansk  8050  0.4  0.5 1303064 41120 ?       Ssl  09:02   0:05 /home/tbosansk/.cache/appimage-run/80f4223d212330eb93bcd9a9111ef5ebc6bef0e08db250f2b5bcf2039414f442/squashfs-root/resources/bridge/2.0.27/trezord-linux-x64
`

Bridge  status page and trezorctl said that there were no devices connected, I had two of them and unlocked.

After starting regular Bridge it went OK
killed it and started regular Bridge via `systemctl start trezord`

```
trezorctl list
WebUSB transport is disabled: libusb-1.0.so: cannot open shared object file: No such file or directory
bridge:1 - (unnamed) [Trezor 1, 60EA5A917970F9136A6C136B]
bridge:2 - My Trezor [Trezor T, 3FCAEE61D128123EB6946A5F]

```

**Comment by tsusanka** [comment]
@bosomt could you try on the Kubuntu? Let's see what happens there.

**Comment by bosomt** [comment]
@tsusanka Kubuntu works fine

**Comment by tsusanka** [comment]
JFYI this still happens on NixOS, also on latest 20.12.1. Since it is NixOS-only it has low priority but I am wondering does it happen to @prusnak as well?

**Comment by tsusanka** [comment]
I am still experiencing this with 21.7.1 installed via Nix (not appimage). If I plug the device in _before_ launching Suite I am all good. If I launch Suite and _then_ connect Trezor it is not found.. This concerns NixOS only.
cc @mmahut @mmilata just in case some NixOS wizards would have an idea.

**Comment by tsusanka** [comment]
I am afraid it is not in our capacities to fix this currently. The main happy path works and that's important.
