### ISSUE TITLE
Transaction summary shows NaN - NaN when there is very first pending tx on new account

### ISSUE THREAD

**Issue by LukasRada** [trezor/trezor-suite#2616]
**Info:**
 - OS: Win 10
 - Browser: Chrome 86.0.4240.75
 - Wallet Version: web (beta), e243afdb73e35fa08f39a7fc08a28b84baa3ac58
 - Firmware Version: N/A
 
**Describe the bug**
Transaction summary shows NaN - NaN when there is very first pending tx on new account.

**Steps to reproduce:**
1. Create new BTC account.
2. Send some BTC to the first address from that account.
3. As the transaction is pending, UI shows NaN - NaN instead of dates.

**Expected result:**
Probably nothing to show yet.

**Actual result:**
Shows NaN - NaN.

**Screenshots:**
![image](https://user-images.githubusercontent.com/7394177/95916657-4f89d800-0da9-11eb-9f2d-d2c4cc630380.png)

**Comment by slowbackspace** [comment]
Thanks for the report! The issue should already resolved in our development branch and it will be released soon (no eta, but SOON 😁). If you'll experience the same issue after an upgrade (to version 20.10.1) feel free to reopen the issue.
