### ISSUE TITLE
Change the copy in udev download: tell users to download first, install later

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2618]
It automatically wants it to open in “Software Install”, but then throws “not supported” error.

<img width="683" alt="Screenshot 2020-10-14 at 11 23 19" src="https://user-images.githubusercontent.com/6961901/95969990-b93ccd00-0e0f-11eb-8b9b-5c71456e1401.png">

![image](https://user-images.githubusercontent.com/6961901/95958796-f00be680-0e01-11eb-8a23-83321e774d94.png)

![image](https://user-images.githubusercontent.com/6961901/95958805-f732f480-0e01-11eb-95cd-7841e1029fe0.png)

**Comment by prusnak** [comment]
This is not our issue, but Ubuntu's - see here: https://askubuntu.com/questions/1232868/problem-installing-deb-in-software-install-ubuntu-20-04

It seems that the `.deb` file needs to be downloaded first (via "Save File" option, not "Open with ..." ) and then installed via Software Center or Gdebi. 

If you Open automatically, the file is downloaded to /tmp and for some reason Software Center doesn't like that :-(

**Comment by slowbackspace** [comment]
Oh, that's confusing. I guess we can let our support to handle it if some users will run into this problem. Thanks for looking into it, I wasn't even sure if it is supposed to work as I don't use linux on the desktop
@matejzak not sure if we can help our users somehow (idk if there is wiki page where this can be mentioned or something), just CCing you :)
closing the issue

**Comment by prusnak** [comment]
I will reopen the issue - I think we should change the copy to include this information in the udev download page.

The information could be something like: "Please download the udev file to Desktop first, don't open it directly from the browser" or something like that.

**Comment by jerechinsky** [comment]
Changed `TR_DEVICE_NOT_RECOGNIZED_TRY_UDEV` from
_Trezor not recognized? Try installing {link}._ 
**to** 
_Trezor not recognized? Try installing {link}. Make sure to first download them to desktop before opening._

**Comment by jerechinsky** [comment]
nothing to test
