### ISSUE TITLE
Send - 'Clear all' button visible in default form state

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#2622]
- click RBF on/off
- click locktime add/remove
- add and remove the recipient

![image](https://user-images.githubusercontent.com/3112191/95971999-379a6e80-0e12-11eb-8c77-659ad53e4418.png)

**Comment by szymonlesisz** [comment]
if you click on something it's not a default state anymore
interaction has been made => clear all button appears
I don't think validating `current state` === `default state` is worth the effort in this case
