### ISSUE TITLE
Insufficient space for text in buttons Onboarding

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2625]
**Info:**
1. OS Windows 10 Home 19041.1508 Suite Type APP Commit e6ba320
2. OS Nixos web Commit e6ba320201b76c285b569b99f1e4b095e53f0028
Device TT 2.3.4. 50854b921
 
**Describe the bug**
Text in green buttons in one of the Onboarding steps (Create new wallet scenario) is overspilling a little bit.

**Steps to reproduce:**
1. Connect a device without seed
2. Create new wallet

**Expected result:**
Text will stay within button borders.

**Actual result:**
Text in green buttons in one of the Onboarding steps (Create new wallet scenario) is overspilling a little bit.

**Screenshots:**
![image](https://user-images.githubusercontent.com/58593111/95984517-9b796300-0e23-11eb-8fe3-473412d144e3.png)

**Comment by slowbackspace** [comment]
@mroz22 hardcoding pixel perfect widths is not the safest way 😁 

I would fix it but looks like the Option component is super reusable and used across onboarding and recovery so it would be probably the best if you would take a look.

**Comment by mroz22** [comment]
I'll check it. It is hard to mantain unified look on limited space with unpredictable strings lengths.

Unrelated. But what is "Advanced seed" and "standard seed". I'd say it is rather unfortunate to create new terminology here.

**Comment by wendys-cats** [comment]
@mroz22 agree with unfortunate choice of creating new terminology. The advanced seed is Shamir. Standard was called Single seed before, I think. And this change of terminology is most likely why the words do not fit in anymore.

**Comment by glacierbits** [comment]
Assigning to myself. I agree the copy (written in good faith by our colleagues hired after Shamir launch) is not ideal to begin with.

**Comment by glacierbits** [comment]
Fixed in Crowind. Changes to propagate upon @slowbackspace's sync magic.

**Comment by wendys-cats** [comment]
**QA OK**

**Suite** web develop branch commit f06aff6
**OS** NixOS + Chromium 85
**Device** TT 2.3.4 public **AND** T1 1.9.3 public
