### ISSUE TITLE
Make "Yes, I do!" clickable during firmware update

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2627]
**Info:**
- OS: NixOS
- Browser: desktop app
- Suite Version: https://staging-suite.trezor.io/ - release/2020-10 - 9995926
- Firmware Version: 1.9.0
 
**Describe the bug**
I have to click the checkbox, not just the "Yes, I do!" which is a bit annoying :).

**Screenshots:**
![a](https://user-images.githubusercontent.com/1835345/95987527-daa9b300-0e27-11eb-8e24-d3784570a885.gif)

**Comment by bosomt** [comment]
QA OK

Nixos + 81.0.2 (64-bit)
Suite web dev master commit 4d4a9f3
Device Model T 2.3.4 commit 50854b921
