### ISSUE TITLE
Redundant scroll bar in dry-run

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2628]
**Info:**
Suite Version: app, commit 99959260d5639480dfb11e53a4f2ab1d789b0e7b
OS: MacOS Catalina 10.15.6
Firmware Version: T1 1.9.3 0d5f006 with PIN ON
 
**Describe the bug**
PIN entry modal in dry-run/backup-check displays a redundant scroll bar.

**Steps to reproduce:**
1. Navigate to Settings -> Device 
2. Select Backup check
3. Proceed until the PIN dialog

**Expected result:**
No scrollbar display in the PIN dialog.

**Actual result:**
A scrollbar is displayed in the PIN dialog.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/95990838-4b52ce80-0e2c-11eb-8fe7-fede4c29a152.png)

**Comment by sorooris** [comment]
https://github.com/trezor/trezor-suite/issues/2588

**Comment by szymonlesisz** [comment]
https://github.com/trezor/trezor-suite/issues/2602

**Comment by bosomt** [comment]
Nixos
app commit 25b2e6bf56951532d0ba0364b691584dbbbbcf21
device TT 2.3.4

one more step that needs to be checked when issue is fixed

![image](https://user-images.githubusercontent.com/31506317/96427184-86734a00-11fe-11eb-8ad2-d05db163caaf.png)
