### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#2629]
Neither https://suite.trezor.io/ nor https://suite.trezor.io/web/ shows favicon - let's fix that by adding one

**Comment by slowbackspace** [comment]
@matejzak what should be used as favicon? Desktop app icon or you have something different? It would be great if was recognisable even when showed as a small image in browser's tab (16x16px or something).

**Comment by slowbackspace** [comment]
https://css-tricks.com/favicon-quiz/
jesus, favicons are hard

**Comment by prusnak** [comment]
I think using the green part of the desktop icon would look nice (i.e. replace white with transparent). Let's not bother with ICO format, just use PNG with `<link rel="shortcut icon" type="image/png" href="favicon-48x48.png"/>` and be done with it.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 81
Suite dev web commit 4d4a9f3
Device 2.3.3 model T commit 0d5f00668
