### ISSUE TITLE
Desktop: Not able to quit the app on macos

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#2630]
**Info:**
 - OS: MacOs
 - Electron
 - Wallet Version: 20.10.1, 99959260d5639480dfb11e53a4f2ab1d789b0e7b
 - Firmware Version: any 
 
**Describe the bug**
sometimes (i didnt find a pattern yet) i'm not able to quit the app using "right click > quit" it ends up with an error message and it's not killing the electron window. In need to kill the app manually using Task manager.

**Screenshots:**
![Screenshot 2020-10-14 at 15 30 13](https://user-images.githubusercontent.com/3435913/95996415-ecdd1e80-0e32-11eb-9064-a504eac9bc2b.png)

**Note(s):**
it's happening randomly

**Comment by prusnak** [comment]
@keraf That's the bug I saw after the autoupdate to 20.10.1 - so I guess that's not related to autoupdate if Szymon was able to reproduce with "vanilla" 20.10.1

**Comment by szymonlesisz** [comment]
and this is the code responsible for that (transpiled from typescript):
![Screenshot 2020-10-14 at 15 47 44](https://user-images.githubusercontent.com/3435913/95997954-a38dce80-0e34-11eb-882a-c70f7a874c66.png)

**Comment by sorooris** [comment]
**QA OK**

Couldn't replicate issue.

Suite version: app 513631a9fa62c438e60397a9942b04275bcd621a
OS: macOS Catalina 10.15.7
Device: 2.3.4 50854b921

**Comment by mroz22** [comment]
I have just run into this again. Can't close app.

OS: Windows 10 pro, version 1903
commit 36c7716b 

Also maybe it's worth mention that it does not find the latest update.

**Comment by sorooris** [comment]
macOS only - opening a new issue
couldn't replicate issue in the latest 20.11.2 build (commit b0dacc34)

**Comment by mroz22** [comment]
ok thanks.
