### ISSUE TITLE
Text in labeling field will disappear if cursor crosses certain div bounds

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2632]
**Info:**
OS Windows 10 Suite Type APP Commit e6ba320 (@bosomt is this right?)
OS Nixos web Commit e6ba320 
Device TT 2.3.4. 50854b921
 
**Describe the bug**
This happens when user is creating a label for a transaction. When they move the cursor during the creation of the label through certain div bounds (in or out of the div containing said transaction), the text will automatically be erased. 

**Steps to reproduce:**
1. Enable labeling
2. Go to Accounts > Transactions > Click on Add label
3. Write something (do not hit enter or approve it) and move the mouse around

**Expected result:**
Did not expect the text to disappear.

**Actual result:**
Text disappears under certain conditions.

**video**
https://drive.google.com/file/d/1ZAIY9v2vJMFFagxv4CKqqCyEfGI8l48-/view

**Comment by wendys-cats** [comment]
@mroz22 was told to tag you:)

**Comment by bosomt** [comment]
**QA NOK**

@mroz22 text is till disappearing when i move cursor  

Nixos + Chromium 86.0.4240.75
Suite dev master 91d61f8
Device model T fw 2.3.4 commit 50854b921

**Comment by mroz22** [comment]
Hmm, I don't say this can't happen..., but cant reproduce it right now. Will investigate.

**Comment by bosomt** [comment]
@mroz22 

it's not happening in transaction tab, 
it's happening in receive address tab

**Comment by wendys-cats** [comment]
@mroz22 [here](https://drive.google.com/file/d/18-U3dSpUjwLH6I9iTiGAzl2eN0owuOvW/view) you go

**Comment by mroz22** [comment]
Thanks. Will fix.
