### ISSUE TITLE
Labels/metadata from the (old) web wallet are not present in the new Trezor Suite wallet

### ISSUE THREAD

**Issue by darwin** [trezor/trezor-suite#2636]
I'm just testing new beta 20.10.1 with model T updated to latest firmware. I was able to give the desktop app permissions to access my dropbox but I don't see existing labels.

1. I can see labels proper when visiting wallet.trezor.io with the same device
2. I don't see labels when using trezor suite wallet with connected dropbox

The suite desktop app in SETTINGS > LABELING shows:
```
Connected to Dropbox as <NAME>
Your labeling is synced with cloud storage provider. Your data are safe, only your Trezor can decrypt them.

[Disconnect]
```

I would expect the old labels to work. 
Or is there a reason to keep them separate? 
In that case I would appreciate some tool to convert labels to the new system. 
Thanks for clarification. I'm excited about this new development.

**Info:**
 - OS: macOS 10.15.7
 - Browser: N/A
 - Wallet Version: beta 20.10.1
 - Firmware Version: model T FW@2.3.4

btw. I can provide a log. I skimmed it briefly and it looks to me that the label metadata is not retrieved, only some new metadata was created related to `@account/create` events. I tried to close and open wallet app again. Same result.

**Comment by mroz22** [comment]
They definitely should be there. I will check it.

**Comment by prusnak** [comment]
We found the culprit (scoped vs unscoped Dropbox app) - possible fix in https://github.com/trezor/trezor-suite/pull/2642

Thanks for the report!

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 81
Suite dev web 4d4a9f3
Device model T 2.3.4 commit 50854b921

![suite](https://user-images.githubusercontent.com/31506317/96993928-41b41f80-152c-11eb-9fa5-12886947dfc2.png)
![old](https://user-images.githubusercontent.com/31506317/96993932-424cb600-152c-11eb-93ec-caf0ad4fd3bb.png)
