### ISSUE TITLE
[REQ] GPG signatures for the install binaries, or a public acknowledgement of the certificate hash

### ISSUE THREAD

**Issue by brianddk** [trezor/trezor-suite#2639]
**Is your feature request related to a problem? Please describe.**
One of the crucial tasks that anyone using bitcoin must perform is the validation of all software and firmware that can touch or manage bitcoin.  Since change-address and path-isolation attacks may still be possible (in theory), the protection that the firmware provides should not be 100% relied upon.  The user should still perform due diligence to ensure that the software being run is valid.

Although the install binaries (Windows) are signed with a cert, there is no public, GPG signed acknowledgement of what the valid cert hash should be.  This is solved with the bridge installers since the `exe` is signed with a cert and a GPG signature of the `exe` is provided.  This is not the case for the suite download.

It may be possible to perform validation using the blockmap files, but that is a rather novel checksum format and not well understood.  I've asked the electron-builder team to better explain the JSON schemea.  (see [#2851](https://github.com/electron-userland/electron-builder/issues/2851#issuecomment-708971669)).

**Describe the solution you'd like**
A simple GPG `.sig` file for each installer download signed with the same key as used by the bridge software referenced below:

```
bridge GPG key: 86E6792FC27BFD478860C11091F3B339B9A02A3D
```

**Describe alternatives you've considered**
A brief description of how to perform validation against the blockmap hashes.  Or sign future suite releases with the same certificate used to sign the bridge software.  Since the bridge software has an additional GPG signature a definitive chain of trust can be built from the GPG signature to the certificate hash without relying on a centralized authority.

I do acknowledge that the git commit for the TAG creation in the Releases page is in fact signed.  So that does provide some validation, though I'm not certain that TAG signatures will hash all the binaries encased within.

**Comment by prusnak** [comment]
I added my GPG signatures as `.asc` files to the release: https://github.com/trezor/trezor-suite/releases/tag/v20.10.1
