### ISSUE TITLE
Address labels metadata is not presented by TransactionItem component

### ISSUE THREAD

**Issue by darwin** [trezor/trezor-suite#2648]
While testing PR #2642 after I noticed that some labels presented in the (old) web wallet at wallet.trezor.io are not present in the trezor suite wallet.

I decided to track this down. It turned out that all relevant metadata is properly extracted from a dropbox file and stored in the app state. This is just an UI issue that the `<TransactionItem>` component is only passed `txMetadata={account.metadata.outputLabels[tx.txid]}`. I believe it should be extended and also passed address metadata, e.g. an array of `account.metadata.addressLabels[relevant-address]` for addresses relevant to the tx at hand.

I noticed that old web wallet is displaying affected (missing) labels in cursive as oposed to other labels. Currently working labels are associated with `outputLabels` and missing labels are associated with `addressLabels`.

Also note that `addressLabels` are properly displayed by the `<UsedAddresses>` component.

**Comment by mroz22** [comment]
Hi, 
first of all let me thank you for reporting bugs!

Just to make sure I understand you

1. wallet.trezor.io - first I label an address
![image](https://user-images.githubusercontent.com/30367552/96308420-a68ae980-1003-11eb-8e7c-95e07289d221.png)

2. wallet.trezor.io - then I can see the address label in transaction even though I had not labeled the transaction yet
![image](https://user-images.githubusercontent.com/30367552/96308496-cb7f5c80-1003-11eb-9d67-85f527f4c78b.png)

3. I may label the transaction later and see another label after that.
![image](https://user-images.githubusercontent.com/30367552/96307728-6119ec80-1002-11eb-94c7-468af4289cc9.png)

4. Whereas number 2 is not implemented in the new app.
![image](https://user-images.githubusercontent.com/30367552/96307927-ab9b6900-1002-11eb-9653-9a91ca114478.png)

Is that what you mean? 

This indeed is not implemented and I am not sure at the moment if on purpose or we just missed it. @matejzak

**Comment by darwin** [comment]
@mroz22 Yes, indeed that is what I mean. I reported it because viewing my wallet.trezor.io and the same account under suite wallet didn't show the same labels.
