### ISSUE TITLE
Receive address not clickable when labeling enabled

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2651]
**Info:**
 - OS: Windows
 - Wallet Version: app commit 99959260d5639480dfb11e53a4f2ab1d789b0e7b
 - Firmware Version: T1 model 1.8.3 , revision 0xdf0963ec48f01f3d07ffca556e21ff0070cab099,
 
**Describe the bug**
See video. When you add label to address in used addresses list you then you can click on it but address it not shown.
+ Reveal address button is only visible when you navigate to this address, so it can get confusing.
Please add same functionality like in transactions list / context menu that asks you to either edit label or reveal address /

**Steps to reproduce:**
1. load wallet with used addresses
2. enable labeling and add label to used address
3. click on address to reveal complete address
4. nothing happens, you need to navigate to right to reveal address button

**Expected result:**
You can click on address with enabled labeling

**Actual result:**
 you need to navigate to right to reveal address button, this button is only present when you navigate cursor to address

**Screenshots:**
https://www.youtube.com/watch?v=H8ME6OjXmnk&feature=youtu.be

![image](https://user-images.githubusercontent.com/31506317/96235280-e2d62f80-0f9a-11eb-9fed-1f86429b2436.png)

**Comment by glacierbits** [comment]
@mroz22 Fix: Reveal address should be possible only from the `Reveal address` button on the right hand side (the same way it is revealed from the primary button above, not by clicking on the revealed address), regardless of whether label is used or not.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 86.0.4240.75
Suite dev master 91d61f8
Device model T fw 2.3.4 commit 50854b921
