### ISSUE TITLE
Fresh address not updated when pending transaction on last fresh address

### ISSUE THREAD

**Issue by xbach** [trezor/trezor-suite#2652]
**Info:**
- OS: macOS 10.14.6
- Suite Version: macOS, 20.10.1
- Firmware Version: Model T, 2.3.4

 
**Describe the bug**
When receiving a transaction to a fresh address, and the transaction is pending, the Suite sees it as pending. When going to the same account to get another fresh address, Suite will show the same (used) fresh address. As discussed in Slack tech_frontend, Suite should recognize an address with a pending transaction as a used one, and should offer next unused address instead.

**Steps to reproduce:**
1. Generate a fresh address
2. Send a transaction to said fresh address
3. Wait to see Suite noticing the transaction in mempool (pending tx)
4. Go to Receive and get a fresh address. The address will be the same one as the one used.

**Expected result:**
To improve privacy, even addresses with a pending transaction should be recognized as used addresses, so that a user will not send fund to the same address twice (unless intended). 

In the list of addresses, an address with a pending transaction should show "Pending" or something similar under Total Received, instead of "Unused".

**Actual result:**
Address with a pending transaction is not considered as used.

**Comment by slowbackspace** [comment]
should be fixed in https://github.com/trezor/trezor-suite/pull/2821
@trezor/qa please test the s..t out of it

**Comment by bosomt** [comment]
**QA OK**


![image](https://user-images.githubusercontent.com/31506317/98142797-91013500-1ec8-11eb-9cbf-bf4c9ddf736a.png)

Nixos
Suite app commit 39d1b9690756482310a3970de0d1a29b0d4d2e89
Device model One firmware 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
