### ISSUE TITLE
Label truncating

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2653]
20.10.1 desktop (probably web too)

Label truncating got broken and I'm sure it was working fine before. 2 issues:
1) placeholder space for the label button that is not imo necessary (I already fixed it once, auto truncated label could (and was) be automatically shortened if the button is visible). I think this behaviour is also in txs list.
2) truncating doesn't render ellipsis character

@mroz22 do you know about any changes that would cause this issue?

<img width="508" alt="Screenshot 2020-10-16 at 12 37 59" src="https://user-images.githubusercontent.com/6961901/96248891-9dbaf900-0fac-11eb-9675-13d1fb576475.png">
<img width="510" alt="Screenshot 2020-10-16 at 12 37 56" src="https://user-images.githubusercontent.com/6961901/96248901-a27fad00-0fac-11eb-9032-abcbad452a77.png">

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82.0 (64-bit)
Suite web commit 53e0e15a3652c0ee48b4717846305be57404c6a7
Device model One fw 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,

**Comment by bosomt** [comment]
**QA OK**

Nixos
Suite app commit 11888946531d3bf641d83bdbfddae8e0143b0738
Device model one FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
