### ISSUE TITLE
Send form - ETH - Missing gas limit input

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2654]
**Info:**
 - OS: any (tested NixOS)
 - Browser: any (tested Chromium 85.0.4183.102)
 - Suite Version: web 99959260d5639480dfb11e53a4f2ab1d789b0e7b
 - Firmware Version: 2.3.4 50854b921
 
**Describe the bug**
There is no way to edit gas limit in the send form compared to the Next Wallet.

**Steps to reproduce:**
1. Navigate to ethereum send form,
2. Observe the Fee section.

**Expected result:**
Input for editing gas limit is present.

**Actual result:**
Transaction fee is seemingly set only by gas price in GWEI.

**Screenshots:**
 [Next wallet](https://beta-wallet.trezor.io/next/#/) | [Suite](https://suite.trezor.io)
 --|--
 ![image](https://user-images.githubusercontent.com/10185314/96250729-947f5b80-0faf-11eb-8573-7ebcf8135a86.png) | ![image](https://user-images.githubusercontent.com/10185314/96250844-c7c1ea80-0faf-11eb-9f6f-ebdbbddead36.png)

**Note(s):**
Came in as an issue from support.

**Comment by szymonlesisz** [comment]
reminder: gas limit was intentionally hidden because of lack of design (two "custom inputs")

**Comment by glacierbits** [comment]
Closing in favour of #2970

**Comment by bosomt** [comment]
**QA OK**

Firefox 82.0 (64-bit) + Nixos
Suide web dev maser commit da17a85
Device mdoel T fw 2.3.4 commit 50854b921
