### ISSUE TITLE
Spawning multiple websocket connections  per coin

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2660]
**Info:**
 - Wallet Version: 20.10.1 (develop and production), web and electron
 
**Describe the bug**
With all coins enabled Suite sometimes spawns multiple websocket connections per coin to a blockbook server

**Steps to reproduce:**
(doesn't work all the time)
1. Enable all coins
2. Go to Dashboard/Accounts and hit refresh to trigger discovery for all coins
3. Open network tab in devtools, see many connections

**Expected result:**
1 connection per coin
**Actual result:**
sometimes multiple connections per coin

**Screenshots:**
<img width="1356" alt="Screenshot 2020-10-16 at 18 01 43" src="https://user-images.githubusercontent.com/6961901/96286288-72ea9800-0fe0-11eb-9f62-fe2c7cb1c99f.png">

**Note(s):**

I think it is again caused by fetching fiat rates, which is weird cause we already fixed that and nothing AFAIK changed in suite regarding fetching. I'll try to verify it later, if I am correct then it should be impossible to reproduce the issue with this line commented out https://github.com/trezor/trezor-suite/blob/9741fef934bae207438ff12dbf82b075ded27926/packages/suite/src/actions/wallet/blockchainActions.ts#L223

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82.0 (64-bit)
Suite web commit 39d1b96
Device model One FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
