### ISSUE TITLE
Ugly sidebar on landing page in mobile browser

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2662]
**Info:**
 - OS: iOS 
 - Browser: Both Google Chrome 86 and Firefox 28.2
 - Wallet Version: current release suite.trezor.io
 
**Describe the bug**
Ugly sidebar on mobile page, see pictures. I know we do not optimize for mobile yet (I guess?) but in case it would be an easy fix..

**Steps to reproduce:**

**Screenshots:**
![IMG_4722](https://user-images.githubusercontent.com/1835345/96378003-7ec58e00-1189-11eb-89b6-51e8762378dc.jpg)

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 86.0.4240.75 /switched to mobile view, tested via various mobile presets/
Suite dev master 91d61f8
Device model T fw 2.3.4 commit 50854b921
