### ISSUE TITLE
Service workers still running after disabling coin

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#2667]
Each coin has its own blockbook service worker running, but when disabling that coin, the service worker is kept alive and still uses memory. 

When disabling coins, we should dispose of the related service worker. Haven't looked too much into it, not sure if that's a connect issue or how we use connect in Suite.

**Comment by bosomt** [comment]
For reference: 
/waiting for deployment/ 
 
Incorrect behavior - active connections to blockbook when coins are disabled as a reference for future testing.

Nixos + Chromium 86.0.4240.75
Suite dev master 91d61f8
Device model T fw 2.3.4 commit 50854b921

![image](https://user-images.githubusercontent.com/31506317/97162452-82f03d80-177f-11eb-9168-042cc9ab6f6c.png)

**Comment by bosomt** [comment]
**QA OK**

Suite Version: /web, commit 513631a
Browser: Chrome, version 86.0.4240.111 + Firefox 82
OS: Nixos
Firmware Version: model T 2.3.3 , revision 0d5f00668
