### ISSUE TITLE
Overview, Trade - Web page titles inconsistent with AppNavigation titles

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2670]
**Info:**
 - OS: any (tested NixOS)
 - Browser: Chromium 85.0.4183.102
 - Suite Version: web - production 99959260d5639480dfb11e53a4f2ab1d789b0e7b, /release/2020-10-beta/ 2f07979a168660553abdf27d6b55149731509e0a
 - Firmware Version: any (tested model T, 50854b921)
 
**Describe the bug**
Web page titles are inconsistent with AppNavigation titles.

**Steps to reproduce:**
1. Navigate to Accounts,
2. Select an AppNavigation item (Overview, Send, Receive, Trade),
3. Observe web page title.

**Expected result:**
Web page titles (what is written in the tab) are consistent with AppNavigation item titles (what is in the "submenu tabs" under Accounts tab).

**Actual result:**
**Overview** and newly added **Trade** AppNavigation items are inconsistent with web page titles when selected - **Transactions** and **Coinmarket** respectively.
Send and Receive AppNavigation items are consistent with names.

**Screenshots:**
 Overview | Receive | Send | Trade
 -|-|-|-
![image](https://user-images.githubusercontent.com/10185314/96466681-60fc3580-122a-11eb-82a1-433c60249c47.png) | ![image](https://user-images.githubusercontent.com/10185314/96466706-68234380-122a-11eb-9e63-a4c26a56187e.png) | ![image](https://user-images.githubusercontent.com/10185314/96466740-72454200-122a-11eb-80a4-e53d0e3f0e63.png) | ![image](https://user-images.githubusercontent.com/10185314/96466778-78d3b980-122a-11eb-814a-7d576d75d551.png)

**Comment by slowbackspace** [comment]
loool, good catch! 😁  (maybe we could finally stop renaming these things all the time)

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82.0 (64-bit)
Suite app commit 39d1b96
Device model One FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
