### ISSUE TITLE
Action @metadata/account-loaded fired too often

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2671]
It seems that every time I add a new account I see bunch of `@metadata/account-loaded` actions fired.
bug?

<img width="621" alt="Screenshot 2020-10-19 at 16 47 41" src="https://user-images.githubusercontent.com/6961901/96467326-162eed80-122b-11eb-81a5-edee9a132a6e.png">
<img width="450" alt="Screenshot 2020-10-19 at 16 50 07" src="https://user-images.githubusercontent.com/6961901/96467393-2646cd00-122b-11eb-8106-698f612a901d.png">

**Comment by mroz22** [comment]
Yes, let me address this. I already have a note somewhere on paper. There is one place in metadataActions that lacks one additional if clause

**Comment by slowbackspace** [comment]
I would swear sometimes it is fired for no reason at all. maybe blockchain-block has something to do with it? or some timer? 🤕 

<img width="458" alt="Screenshot 2020-10-19 at 17 06 51" src="https://user-images.githubusercontent.com/6961901/96469427-7cb50b00-122d-11eb-8fc7-060b8d8918f4.png">

**Comment by mroz22** [comment]
Yes, there is timer every 3 minutes.

**Comment by mroz22** [comment]
I am moving this to another release. It could be optimized but I'd rather not touch it now.
