### ISSUE TITLE
Invity - Buy - redundant scrollbar in CoinmarketBuyTerms modal

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2672]
OS: any (tested NixOS)
Browser: Chromium 85.0.4183.102
Suite Version: /release/2020-10-beta/ 2f07979
Firmware Version: any (tested model T, 50854b921)
 
**Describe the bug**
Redundant scrollbar present in viewports under 729px in height.

**Steps to reproduce:**
Prerequisite - cleared storage; CoinmarketBuyTerms modal wasn't displayed yet.
1. Navigate to Accounts -> Trade -> Buy
2. Select an arbitrary amount to buy, confirm
3. Confirm an arbitrary deal and observe.

**Expected result:**
CoinmarketBuyTerms modal is displayed with fixed height in any viewport height.

**Actual result:**
CoinmarketBuyTerms modal is displayed with a redundant scrollbar when viewport height is under 729px.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/96468762-c0f3db80-122c-11eb-842a-8dfa5328fa10.png)

**Comment by tsusanka** [comment]
Cc @matejzak. The dialog is not very nice imho.

**Comment by tsusanka** [comment]
We have agreed with @martinboehm that we will tackle this later as it is not critical.

**Comment by vladimirvolek** [comment]
This is not a bug. You can see on the screenshot the content is bigger than your window. So there is a scrollbar.
Please reopen if I am wrong @slowbackspace @robertbrada @tomexx.

![image](https://user-images.githubusercontent.com/3112191/98940848-e43c3e80-24eb-11eb-98ba-0b4890bb311f.png)
