### ISSUE TITLE
Add OG meta tags 🚀

### ISSUE THREAD

**Issue by MrMebelMan** [trezor/trezor-suite#2673]
**Is your feature request related to a problem? Please describe.**
Website looks unfinished without meta tags 😅 

**Describe the solution you'd like**
Add them!

**Describe alternatives you've considered**
Add them later!

**Additional context**
![Selection_937](https://user-images.githubusercontent.com/15896005/96470538-b20e2880-122e-11eb-9aad-a297618a88f3.png)

**Comment by slowbackspace** [comment]
@matejzak This is useful for eg. sharing a link to suite.trezor.io on facebook (or any other social net), without these cool tags it looks like this:
<img width="519" alt="Screenshot 2020-10-22 at 13 28 09" src="https://user-images.githubusercontent.com/6961901/96865593-752e7580-146a-11eb-96c6-59e45e260026.png">

Title tag is pretty obvious I guess (Trezor Suite), what should we put inside a description and also what pic should be there?

**Comment by prusnak** [comment]
Tools to test meta tags:

* universal: https://metatags.io/
* OG tags Facebook: https://developers.facebook.com/tools/debug/
* Twitter meta tags: https://cards-dev.twitter.com/validator

**Comment by glacierbits** [comment]
@tomexx Share image and metatags below 🤗 


![Frame 74](https://user-images.githubusercontent.com/29627086/97498925-4eda6f80-196d-11eb-8f54-ae8cfe76ce62.png)

```

<!-- Primary Meta Tags -->
<title>Trezor Suite</title>
<meta name="title" content="Trezor Suite">
<meta name="description" content="New desktop & browser app for Trezor hardware wallets. Trezor Suite brings big improvements across our three key pillars of usability, security and privacy.">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://metatags.io/">
<meta property="og:title" content="Trezor Suite">
<meta property="og:description" content="New desktop & browser app for Trezor hardware wallets. Trezor Suite brings big improvements across our three key pillars of usability, security and privacy.">
<meta property="og:image" content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://metatags.io/">
<meta property="twitter:title" content="Trezor Suite">
<meta property="twitter:description" content="New desktop & browser app for Trezor hardware wallets. Trezor Suite brings major improvements across our three key pillars of usability, security and privacy.">
<meta property="twitter:image" content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png">
```

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 86.0.4240.111
Suite web dev master commit f06aff6c9282977e76f17857073fd85704fb7118
