### ISSUE TITLE
LocalStorage: replace by indexedDB/WebSQL(?) sync state, control version, data prefix

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#268]
We need to decide if we still want to use localStorage or maybe indexedDB/websql to store application data.

Make sure that LocalStorage/SessionStorage are synchronized across browser tabs (two wallets opened at once) Example: creating and saving different instances (passphrases) in two tabs

We should be also prepared for scenario where LocalStorage data schema will be changed without backward compatibility. To prevent errors there should be "version" flag which will be compared with expected and in case of incompatibility clears them or translate them into new schema

**Comment by slowbackspace** [comment]
Basic integration of indexedDB for suite-web/desktop is already done (#306), progress of native implementation is tracked in https://github.com/trezor/trezor-suite/issues/8
