### ISSUE TITLE
Suggestion: WebStorm has rich code inspections, maybe take advantage of it

### ISSUE THREAD

**Issue by darwin** [trezor/trezor-suite#2685]
I'm using WebStorm and good news is that the project structure is well understood by WebStorm and works pretty well without further configuration.

The only annoyance is that it shows quite many warnings and suggestions (aka [code inspections](https://www.jetbrains.com/help/webstorm/code-inspection.html)). Many are false positives, some are just [nitpicking](https://github.com/trezor/trezor-suite/pull/2681), but some of them are quite severe and should be addressed IMO. E.g. recently I opened issue #2676.

The code inspections could be disabled globally or on per-type/per-file/per-function/per-statement basis but I don't want to do that. If I were to write some new code I'd like my code to be fully inspected, also I don't want to be baby sitting a huge configuration file and chasing churn on the project. I believe Trezor Suite nature is that it would benefit from strict code inspections, more is better.

I'm not suggesting that Trezor devs should switch to WebStorm, but I would suggest adding some script to [run code inspections from command-line](https://www.jetbrains.com/help/idea/command-line-code-inspector.html) for people who care about it and on a CI server. So people can get some feedback about the code they produced. This would also make life of WebStorm users simpler because false positives would be naturally marked as non issues or rewritten into a better form.

Attaching a motivational screenshot with currently suggested code inspections (WebStorm 2020.2.3):
<img width="859" alt="trezor-suite-code-inspections-example" src="https://user-images.githubusercontent.com/5453/96561759-44aad800-12c0-11eb-9801-cf73102848c4.png">

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
