### ISSUE TITLE
Investigate Deterministic/Reproducible desktop builds

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#2687]
For Firmware having the deterministic/reproducible builds is a must. We'd love to have the same for Suite, but Electron + the whole JavaScript/TypeScript stack might be tricky. Let's investigate if having reproducibility is even possible.

Issues breaking the determinism:

- [x] ~https://github.com/trezor/trezor-suite/pull/2727 fix(suite-desktop): use static BuildId for Next.js~
- [x] ~https://github.com/trezor/trezor-suite/issues/2725 Constant sessionId~

**Comment by Kixunil** [comment]
In case you don't know there's a tool called diffoscope (available in Debian 10 repo) that can show you the differences between two builds. Might be handy.

**Comment by prusnak** [comment]
After fixing issues from the original post I confirm the desktop builds are deterministic.

**Comment by GittyGitGitGitty** [comment]
> After fixing issues from the original post I confirm the desktop builds are deterministic.

How can I confirm this? Where in the docs or CI is there a process for provability?
