### ISSUE TITLE
Invity - Passphrase entry prompted after redirect from Buy payment gateway

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2691]
OS: any (tested NixOS)
Browser: Chromium 85.0.4183.102
Suite Version: /release/2020-10-beta/ 2f07979
Firmware Version: any (tested model T, 50854b921)
 
**Describe the bug**
The standard _Select wallet type_ modal is displayed after redirecting from Buy payment gateway which allows the user to enter other wallet's passphrase - which in case of passphrase mismatch results in the Buy transaction detail being displayed but the transaction is not displayed in the Buy transactions list.

**Steps to reproduce:**
1. Enter passphrase #1 when launching Suite,
2. Complete a Trade -> Buy flow,
3. Enter passphrase #2 when redirected back to Suite from the payment gateway.

**Expected result:**
1) Passphrase isn't prompted and user is redirected to the wallet that they've made the transaction with automatically,
2) Passphrase confirmation modal (similar to after an empty passphrase is entered), which should not allow to enter a different passphrase of another wallet, is displayed.

**Actual result:**
_Select wallet type_ modal, which allows to enter a different passphrase than what the transaction was being made with was, is displayed.

**Screenshots:**
N/A

**Comment by sorooris** [comment]
It's up for discussion if another wallet's pasphrase entry should be allowed.

**Comment by martinboehm** [comment]
Actually, I do not think this is doable. We would have to store the original passphrase somewhere and compare it when the user comes back which would be a security risk.

**Comment by tsusanka** [comment]
Firmware sends _session id_ which when returned back in Initiialize will load the passphrase without the need to be entered again. So if this session id is stored inside local storage (as it is imho) we could remember the last session id being used nad load that state. I am not sure it is a good idea though, but I agree this UX sucks.

Maybe @szymonlesisz can help, does Connect has something like "restore the latest session"? Is it a good idea?

**Comment by szymonlesisz** [comment]
yes it has, it's stored in `device.state` string.
the problem here is that device is not persistently stored anywhere (not remembered) at this point so whenever you coming back from a trading page device is not recognized by suite/connect.

Solutions:
- "remember" device before redirection and "forget" after redirection back
- do not open trading page in the same tab but rather in new tab

**Comment by tsusanka** [comment]
We have agreed with Invity they will try to do this asap. They will aim to Friday/Monday to make it into the release.

**Comment by wendys-cats** [comment]
**QA OK** 

No Select wallet modal after redirecting from Buy payment gateway is displayed (tested against beta).

**OS** NixOS
**Suite** web 20.11.1 39d1b9690756482310a3970de0d1a29b0d4d2e89
**Device** TT 2.3.4 public
