### ISSUE TITLE
Graph tooltip overflow

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2694]
tooltip is overflowing outside of visible viewport area triggering horizontal scrollbar
<img width="616" alt="Screenshot 2020-10-21 at 10 10 27" src="https://user-images.githubusercontent.com/6961901/96691869-b1d47100-1385-11eb-9a49-0f68174ce511.png">

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82.0 (64-bit)
Suite web dev master commit a5b13d5
Device model TT FW 2.3.3 commit 0d5f00668
