### ISSUE TITLE
Labeling: Yet more improvements

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2698]
- [x] Content jumps to the right when cursor appears 

- [x]  ✔️  and ✖️   buttons should stay at the same position as the `Edit` button (instead they jump to left). See [design](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f3bf73d694a9912ac30606f) 

- [x] Please treat the default label e.g. `Bitcoin 1#` or `Standard wallet` as a placeholder when first editing the label as well 

- [x] `Renamed` should have green ✔️. See [design](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f3bf73d694a9912ac30606f) 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/29627086/96700515-d33a5a80-138f-11eb-9ff2-e1b4304dc7f6.gif)

_(As seen here: 4d4a9f3f493613c0a86f905414dd8071c55ac69e)_

**Comment by wendys-cats** [comment]
**QA OK**

**Suite** web develop ac55c97
**Browser** Chromium Version 86.0.4240.111 (Official Build) (64-bit)
**System** NixOS 21.03
**Device** T1 1.9.3 public
