### ISSUE TITLE
Landing page: add PGP Signatures + link to the verifying key

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#2699]
On Github release page: https://github.com/trezor/trezor-suite/releases/tag/v20.10.1 we also present GPG signatures + link to the verifying key for our users.

We should add this to our landing page too (somewhere under the download button).

There should be two links added:

* [SatoshiLabs 2020 Signing Key](https://trezor.io/security/satoshilabs-2020-signing-key.asc)
* one of the following (if user is downloading `$INSTALLER` there should be a link to PGP Signature `$INSTALLER.asc`):
  * https://suite.trezor.io/web/static/desktop/Trezor-Suite-20.10.1-linux.AppImage.asc
  * https://suite.trezor.io/web/static/desktop/Trezor-Suite-20.10.1-mac.dmg.asc
  * https://suite.trezor.io/web/static/desktop/Trezor-Suite-20.10.1-win.exe.asc

**Comment by glacierbits** [comment]
@slowbackspace Signature link added to [Zeplin](https://zpl.io/VqNJxZJ) (below primary buttons). Thanks!

**Comment by bosomt** [comment]
**QA OK**

checked at https://suite.corp.sldev.cz/suite-web-landing/develop/
We will test it when deployed to staging  with binaries

![image](https://user-images.githubusercontent.com/31506317/100599543-7623b400-3300-11eb-9aa3-bc9048283aa8.png)
