### ISSUE TITLE
Unconfirmed transactions

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#270]
bump z satoshilabs/trezor-qa#15

zobrazovat navic info o balance nepotvrzenych txs: 0.556 BTC (including 0.01 unconfirmed)
zobrazovat to globalne, nebo pouze v send dialogu, total / confirmed / unconfirmed funds
po zadani vyssi castky, kdy se musi pouzit unconfirmed vstupy zobrazit warning: Unconfirmed funds will be used
po clicknuti na Send zobrazit dialog:
Unconfirmed funds will be used.

buttons I take the risk / Cancel
help link What does it mean?
Rizika pouziti nepotvrzenych txs

tx se nepotvrdi vcas
tx bude zahozena
tx nebude prijata obchodnikem z duvodu retezeni vice nepotvrzenych txs

Slush:
Proc se tomuhle tasku neustale snizuje priorita a posouva se? :-) Prijde mi to relevantni (spolu s bugem #1230). Uzivatel by mel byt informovany, pokud se pouiva unconfirmed transakce i z duvodu CPFP (#1234), coz mu nenapadne zvysuje fees.

Urcite bych ten proposal orezal na nutne minimum (muzem si na to sednout), ale pointa je stale vic relevantni.

**Comment by ZdenekSL** [comment]
Closed after discussion
