### ISSUE TITLE
Uncaught Exception: Error: cannot run bridge binary 

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2700]
**Info:**
 - OS: macOS
 - Wallet Version: latest build from develop (dmg and zip)
 
**Describe the bug**
Suite throws `Uncaught Exception: Error: cannot run bridge binary ` right after launch
**Steps to reproduce:**
1. download latest build from develop eg. https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/802058440
2. launch Suite

**Expected result:**
working app
**Actual result:**
App stuck at error

**Screenshots:**
<img width="1117" alt="Screenshot 2020-10-21 at 12 36 40" src="https://user-images.githubusercontent.com/6961901/96708828-14376c80-139a-11eb-80de-50db4e326c15.png">

**Note(s):**
```
Uncaught Exception:
Error: cannot run bridge binary - Error: spawn /private/var/folders/h9/v60sqtqd5mq9wpnt_g8n2sqh0000gn/T/AppTranslocation/1B1D1534-A6C0-4BBA-AF2C-BC2A1C187E59/d/Trezor Suite.app/Contents/Resources/bridge/trezord-mac-x64 ENOENT
    at error (/private/var/folders/h9/v60sqtqd5mq9wpnt_g8n2sqh0000gn/T/AppTranslocation/1B1D1534-A6C0-4BBA-AF2C-BC2A1C187E59/d/Trezor Suite.app/Contents/Resources/app.asar/dist/bridge.js:35:11)
    at ChildProcess.<anonymous> (/private/var/folders/h9/v60sqtqd5mq9wpnt_g8n2sqh0000gn/T/AppTranslocation/1B1D1534-A6C0-4BBA-AF2C-BC2A1C187E59/d/Trezor Suite.app/Contents/Resources/app.asar/dist/bridge.js:82:9)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by slowbackspace** [comment]
There is one more issue I noticed thanks to this. Suite probably sees that bridge is not running and we have somewhere piece of code that sends request to start a bridge again and again causing the system running out of free file descriptors (my chrome extensions started crashing and if I try to do something in a terminal I get bunch of `zsh: pipe failed: too many open files in system`).

imo whole embedded bridge needs a refactoring (https://github.com/trezor/trezor-suite/issues/2655). if spawning the bridge fails there is probably a reason why it did and there is really no point in trying to start it again. We should inform the user eg. by showing a modal explaining what happened and what can be done (restart pc, contact support or something)

**Comment by prusnak** [comment]
Related to https://github.com/trezor/trezor-suite/pull/2693

I renamed the mac binary to `trezord-mac-x64`, but this does not seem to be reflected in your build

**Comment by prusnak** [comment]
> imo whole embedded bridge needs a refactoring if spawning

One idea: We could spawn the embedded bridge ONLY if there is not another bridge already running on https://127.0.0.1:21325/

**Comment by tsusanka** [comment]
> One idea: We could spawn the embedded bridge ONLY if there is not another bridge already running on https://127.0.0.1:21325/

@slowbackspace @mroz22 How does it work now? We launch it every time? It works even though both bridges (internal and external) are running? :thinking:

**Comment by slowbackspace** [comment]
@prusnak yup, but It wouldn't resolve the issue I mentioned as bridge wasn't running on my system
@tsusanka If there is bridge already running it will be killed first and then suite spawn its own. I am not sure if this works on linux because afaik if bridge was downloaded/installed separately it is run through a service which will restart the process if it is killed (?). But afaik both bridges can't run at the same time as they want to listen on the same port.

If we don't want to kill already running bridge there are few things that are worrying me:
-  In case we upgrade the bundled bridge binary we need to add additional logic to kill the currently running process (otherwise suite would still use the old version, adding to the confusion).
- It could cause a confusion. If user experience some problems it is not obvious what bridge is running (bundled or not).
- There is functionality to restart bridge with `-e 21324` option to support emulators, this probably still needs to kill the old bridge process and spawn a new one. (also killing currently running bridge on suite launch has an advantage: it prevents the user getting stuck with bridge started with `-e 21324` )
-  Right now we don't know if the bridge that is running was spawned from suite or it is a custom one that should be preferred. So if someone enabled mode mentioned in 2) then custom bridge would get killed anyway and from that point only suite bridge would be running. I think this could be partially resolved by simply storing pid of the spawned bridge process. That would also allow to kill bridge on exit without worrying we are killing user's custom bridge process,  but I am not really sure what is the best practise with these things.

**Comment by prusnak** [comment]
Fix most probably in https://github.com/trezor/trezor-suite/pull/2709

**Comment by prusnak** [comment]
Created another issue for starting/killing the bridge https://github.com/trezor/trezor-suite/issues/2719

**Comment by sorooris** [comment]
**QA OK**

Haven't encountered the issue in the latest Bridge release candidate (RC5) and staging Suite.

OS: macOS Catalina 10.15.7
Suite: app 513631a9
Device: model T 2.3.4 50854b921
