### ISSUE TITLE
Update Suite app icon + MacOS install background

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2701]
Please update:  

- [ ] The app icon (it has a shadow now).  
- [ ] MacOS installation background (the place where you move the app to apps folder)

Assets: 
[Suite Icons Shadow.zip](https://github.com/trezor/trezor-suite/files/5414971/Suite.Icons.Shadow.zip)

**Comment by sorooris** [comment]
**QA OK**

Icons & colors match the icons in the zip.

Suite version: app 513631a9fa62c438e60397a9942b04275bcd621a
OS: macOS Catalina 10.15.7
Device: N/A
