### ISSUE TITLE
Custom backend form with multiple fields

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#2706]
**Describe the bug**
It's possible to add another row (input) while previous one is empty

**Steps to reproduce:**
1. goto /settings/coins, open "custom backend" modal
2. click on "+Add new"

**Expected result:**
"+Add new" should not be active

**Screenshots:**
![Screenshot 2020-10-22 at 10 24 16](https://user-images.githubusercontent.com/3435913/96845354-e4976b80-1450-11eb-8610-2260a399b3ca.png)
![Screenshot 2020-10-22 at 10 24 35](https://user-images.githubusercontent.com/3435913/96845362-e8c38900-1450-11eb-8ab2-bb693d1299b9.png)

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82.0 (64-bit)
Suite web dev master commit a5b13d5d92e15f9ee9c1af1b117804cd671c248b
Device model TT FW 2.3.3 commit 0d5f00668
