### ISSUE TITLE
Firmware update - untranslated string in modal when cancelled

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2710]
**Info:**
 - OS: Nixos
 - Browser: Firefox , version 81.0.2 (64-bit)
 - Wallet Version: web, commit 4d4a9f3f493613c0a86f905414dd8071c55ac69e
 - Device Model One 1.9.1 commit 0xc6b2580cd245ee924507f45e9675f857a3d78768,

 
**Describe the bug**
 Untranslated string is displayed when firmware update is cancelled

**Steps to reproduce:**
1. Start Suite and connect Trezor model One with outdated firmware
2. Start update and press Abort on device 
3. observe new modal with string `Error: n.payload.error is null`

**Expected result:**
Correct string with aborted installation is displayed
 
**Actual result:**
Incorrect string with aborted installation is displayed

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/96854675-0ea25b00-145c-11eb-865f-97d9479b8d5b.png)

![Screenshot from 2020-10-22 11-48-14](https://user-images.githubusercontent.com/31506317/96855050-81abd180-145c-11eb-881c-af61474df6a8.png)

**Comment by bosomt** [comment]
cancelled 2.3.3 > 2.3.4 update via device button:

![image](https://user-images.githubusercontent.com/31506317/96862746-2aaafa00-1466-11eb-82ba-68f0b2dab015.png)

**Comment by mroz22** [comment]
Shall be fixed by https://github.com/trezor/connect/pull/700

**Comment by mroz22** [comment]
Connect updated, should be fixed.
