### ISSUE TITLE
Start recovery button - incorrect name displayed during onboarding

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2712]
**Info:**
 - OS: Nixos
 - Browser: Firefox , version 81 
 - Wallet Version: app/web, commit 4d4a9f3f493613c0a86f905414dd8071c55ac69e
 - Firmware Version: 2.3.3 model T, revision 0d5f00668
 
**Describe the bug**

Start recovery button has incorrect name displayed onboarding of model T /model One onboarding is OK/
Translation id `TR_START_RECOVERY`: “Install firmware”

**Steps to reproduce:**
1. Reset suite storage to start onboarding  
2. Connect device model T with older firmware and start onboarding
3. Press skip when asked to update firmware , recovery modal is displayed with `Install firmware` button

**Expected result:**
Start recovery button is named `Start recovery`

**Actual result:**
Start recovery button is named `Install firmware`

**Screenshots:**

![Screenshot from 2020-10-22 13-40-00](https://user-images.githubusercontent.com/31506317/96867025-795b9280-146c-11eb-8d65-40087d0b7e5a.png)

![Screenshot from 2020-10-22 13-40-16](https://user-images.githubusercontent.com/31506317/96867022-78c2fc00-146c-11eb-8a26-991e3be53ac7.png)

![Screenshot from 2020-10-22 13-40-37](https://user-images.githubusercontent.com/31506317/96867019-782a6580-146c-11eb-8736-b83d781dd52f.png)

**Comment by STew790** [comment]
Due to completely new onboarding, this is irrelevant and not present.
