### ISSUE TITLE
Unaligned checkbox items in Backup modal

### ISSUE THREAD

**Issue by robertbrada** [trezor/trezor-suite#2713]
See

![unaligned](https://user-images.githubusercontent.com/44506010/96868642-a741d680-146e-11eb-883d-8801c23641b3.png)

**Comment by wendys-cats** [comment]
**QA OK**

**Suite** Web develop branch commit f06aff6c9282977e76f17857073fd85704fb7118
**OS** NixOS + Chromium 85
**Device** T1 1.9.3 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8

Create Backup checkboxes are aligned.
