### ISSUE TITLE
Onboarding - switching between 2 devices not detected

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2715]
**Info:**
 - OS: Nixos
 - Browser: Firefox, version 81
 - Wallet Version: web, commit 4d4a9f3f493613c0a86f905414dd8071c55ac69e
 - Firmware Version: 2.3.3 + 2.3.4 model T, revision 0d5f00668
 
**Describe the bug**
Suite is not detecting that device was switched during onboarding 

**Steps to reproduce:**
1. Clear Suite and connect seedless device 
2. during onboarding disconnect and connect device that has seed
3. observe behavior

**Expected result:**
Onboarding is restarted or finalized when Suite detects device was switched. 

**Actual result:**
Onboarding process doesn't reflext that device was exchanged.

**Screenshots:**
![111](https://user-images.githubusercontent.com/31506317/96873259-0276c780-1475-11eb-98a0-816c3bc246a0.png)
![222](https://user-images.githubusercontent.com/31506317/96873266-04408b00-1475-11eb-806e-b5d82831bd49.png)
![333](https://user-images.githubusercontent.com/31506317/96873270-060a4e80-1475-11eb-993e-798ff18f38e2.png)
![444](https://user-images.githubusercontent.com/31506317/96873282-086ca880-1475-11eb-884b-b36b58959b3b.png)

**Comment by bosomt** [comment]
update: 

I was able to reproduce issue by recovering seed made of 24 words,
after I entered seed i saw error that suite lost connection to device, maybe device id was changed after recovery ?



![image](https://user-images.githubusercontent.com/31506317/114567921-faede980-9c73-11eb-9f7e-46b9ef94703d.png)

![image](https://user-images.githubusercontent.com/31506317/114568260-456f6600-9c74-11eb-99b9-6cbf762c5e72.png)

[trezor-suite-log-1618321793945.txt](https://github.com/trezor/trezor-suite/files/6304402/trezor-suite-log-1618321793945.txt)

**Info:**
 - Suite version: desktop 21.4.1 (95311f198fba5d2c452cd5d9ce3ede0a50a06a2d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.3.5 regular

**Comment by jerechinsky** [comment]
@matejzak please suggest how Suite should behave upon disconnecting / switching device during onboarding

**Comment by glacierbits** [comment]
@slowbackspace A corner case which I guess we can solve by some generic error message (?) in the new Onboarding #3332?

**Comment by bosomt** [comment]
Maybe we should consider raising priority of this issue , i was asked to generate standard or shamir seed for T1 after my 1.10.1 update and auto reboot of device /of course i had one TT wallet remembered/  isn't somehow possible to ignore or temporarily remove remembered wallet or other connected device during onboarding ? 

![obrazek](https://user-images.githubusercontent.com/31506317/120343584-bf28e500-c2f0-11eb-8b95-f7c7d2fa451f.png)
