### ISSUE TITLE
Constant sessionId

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#2725]
It seems to me that `sessionId` field is constant for everyone, not generated during the app start like it's supposed to be.

Offending line: https://github.com/trezor/trezor-suite/blob/5e1c2acef5657c520bcfdaf37b11423ec953f066/packages/suite/src/reducers/suite/analyticsReducer.ts#L15

When I look into the compiled sources, I can see the hardcoded value there:

```
$ curl -s https://suite.trezor.io/web/index.html | tr ',' '\n' | grep sessionId
"analytics":{"sessionId":"CAYDXkHfIF"
```

**Comment by mroz22** [comment]
This is probably due to how next.js servers prebuilt page along with javascript bundle. It seems to work (correctly change sessionId on page reloads) but I understand the problem with reproducible builds. Will investigate.
