### ISSUE TITLE
Buy improvements

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2732]
### Public beta: 

- [ ] "Connect Trezor"  (should be Trezor Suite branding?) 
- To be fixed once wallet.trezor.io killed

- [ ] Incorrect font colors (multiple places). Please review with the design in Zeplin.

- [ ] Footer too high (should be fixed to the bottom of the page, multiple places)

- [ ] BTC direct: Transaction made > Pending: Go to payment >  404 > Redirect to _my-trezor_ (should be Suite) 
- To be fixed once wallet.trezor.io killed

- [ ] Address component: Let's have the same as "Receive" 

- [ ] Header "Trezor / XY provider" should be Trezor Suite branding  `design needed`
- To be fixed once wallet.trezor.io killed

- [ ] Waiting for the provider missing loader `design needed` 
- Page is blank, the only loader is in browser tab. Add skeleton loading.

- [ ] Amount error > Suggested correction > Another error (+another suggestion) 

<img width="379" alt="Screenshot 2020-10-26 at 11 29 42" src="https://user-images.githubusercontent.com/29627086/97162212-2ab93b80-177f-11eb-869c-a8dd0dee2ebb.png">
<img width="1066" alt="Screenshot 2020-10-26 at 11 30 19" src="https://user-images.githubusercontent.com/29627086/97162171-1d03b600-177f-11eb-93b5-270ab4421604.png">

- [ ] Validation took place after the click on CTA: 'Compare offers'

<img width="830" alt="Screenshot 2020-10-26 at 11 35 12" src="https://user-images.githubusercontent.com/29627086/97162332-5b00da00-177f-11eb-8ebd-667033c7d419.png">

**Comment by martinboehm** [comment]
Majority done in various PRs, the rest is obsolete.
