### ISSUE TITLE
Dark mode 🌃 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2738]
Design: [Zeplin](https://zpl.io/beZg7nN)

**Comment by tsusanka** [comment]
@slowbackspace we could use https://github.com/sindresorhus/electron-util#darkmode to enable dark mode by default if it is turned on in the OS (for Mac). We might extrapolate that feature not to depend on the whole electron-util thingie.

**Comment by slowbackspace** [comment]
@tsusanka I think can be done with just electron, no need for 3rd party solutions https://www.electronjs.org/docs/api/native-theme

**Comment by slowbackspace** [comment]
anyway I am not doing any additional changes til I have my PR merged since it is big enough :)
(retrieving OS theme is the easy part really, making sure we pass that to javascript and use this instead of theme stored in reducer could be a bit tricky)

**Comment by prusnak** [comment]
> @tsusanka I think can be done with just electron, no need to for 3rd party solutions https://www.electronjs.org/docs/api/native-theme

Yes, the electron-util thingie just calls `api.nativeTheme.shouldUseDarkColors` to get the value for `darkMode`.

**Comment by tsusanka** [comment]
Great :rocket:.

**Comment by slowbackspace** [comment]
Created a new issue for tracking bugs and future improvements https://github.com/trezor/trezor-suite/issues/2997

**Comment by bosomt** [comment]
I'm not able to enable Dark mode in Firefox. please see

Firefox 82.0 (64-bit) + Nixos
Suide web dev maser commit da17a85
Device mdoel T fw 2.3.4 commit 50854b921

![Peek 2020-11-18 08-48](https://user-images.githubusercontent.com/31506317/99500726-082fd200-297b-11eb-8b6c-60696e05d572.gif)

**Comment by prusnak** [comment]
> I'm not able to enable Dark mode in Firefox. please see

It works for me - I just need to wait 2-3 seconds until it appears for the first time. The second, third switch, etc. is instant.

**Comment by bosomt** [comment]
I recorded new video with fresh private window
Firefox 82.0 (64-bit) + Nixos

![Peek 2020-11-18 09-19](https://user-images.githubusercontent.com/31506317/99504042-429b6e00-297f-11eb-9716-2223275e0cb7.gif)

Commit da17a8545b7b0342cd85c68132dbe1119ef878c1

**Comment by slowbackspace** [comment]
@bosomt it could be related to the incognito mode, I'll look into it. Thanks!

**Comment by bosomt** [comment]
**QA OK**

Dark mode works fine in both browsers and app now.
Some minor color flaws were fixed in separate issue that I created.

Nixos + Firefox 82.0.3 (64-bit)
Suite web dev master commit 3cfa1ae
Device 2.3.5 model T
