### ISSUE TITLE
CoinJoin 🎛️

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2745]

**Comment by NatoshiSakamotoo** [comment]
Hello @matejzak,

I am curious as to what's planned for the implementation of this CoinJoin? Would you perhaps consider collaborating with @SamouraiWallet to integrate Whirlpool (their implementation of CoinJoin) with the Trezor as they said they'd love to get into contact with you guys, see tweet: https://twitter.com/AScrutinize/status/1388271372866965505

Of course its non custodial and privacy focused without the flaws that Wasabi's implementation of CoinJoin has.

Kind regards,

**Comment by xanoni** [comment]
Yea would love more detail on what's planned here. Sounds amazing. Show them.

**Comment by elkimek** [comment]
Hi,

what is the current state of CJ in Trezor and can you share a little bit more about future plans? Past few days revealed some concerning information about WabiSabi which IIRC Trezor is waiting for it to be finished. 

Referring to a Twitter thread from main WabiSabi dev: https://twitter.com/mHaGqnOACyFm0h5/status/1503878374615404547 more here https://twitter.com/brian_trollz/status/1504457416389267459

Thank you!

**Comment by prusnak** [comment]
> can you share a little bit more about future plans?

It's hard to share any future plans as the situation is evolving rapidly each day. We are closely following the situation and hopefully the whole thing becomes more clear in the upcoming weeks.

**Comment by xanoni** [comment]
If you can't release it, maybe Satoshi can?

**Comment by hynek-jina** [comment]
This "issue" is tracked in dedicated milestone: https://github.com/trezor/trezor-suite/milestone/23
