### ISSUE TITLE
Remote secure messaging system

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#2752]
Let's design and implement secure remote messaging system

We might need to send various messages to the desktop app, such as:
* emergencies (upcoming hard forks, splits, coin removal etc.)
* desktop app kill switch

Requirements:
* possibility to address different versions differently (version comparison)
* security - messages are signed 

**Product specification:** [Notion](https://www.notion.so/satoshilabs/Secure-messaging-system-8ca41332ce504a0f8f6d74fc4bb9c8ab) 

Modal: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/6047b1514e30a0b8c3781a88) 
Context: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/6047b15bbafdbb06f6d25f36) 
Banner: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/6047b148d44ac2bb6f429603)

**Comment by tsusanka** [comment]
As discussed on our meetings here is the draft we came up with:

```
{
    "version": 1,  # int: version of the messaging system. In case we would change the format of the config itself.
    "timestamp": "2021-03-03T03:48:16+00:00", # ISO 8601 date-time format
    "sequence": 1, # int: an increasing counter. Suite MUST decline any file with lower than latest number. This is to protect against replay attacks, where attacker could send an older version of the file and Suite would accept it.
    "actions": [
        {
            "conditions": [
                { # object: if key is not available, then it can be whatever
                    "settings": [ # object: if key is not available, then it can be either true or false
                        {
                            "tor": true,
                            "btc": true
                        },
                        {
                            "tor": false,
                            "ltc": true
                        },
                    ...
                    ],
                    "os": {
                        "macos": ["<10.14", "10.18"], # one of
                        "linux": "<=20.04", # let
                        "windows": "*", # for all versions
                        "ios": null, # not for ios
                        "android": "10" # for android v10.x
                    },
                    "environment": {
                        "desktop": "<21.01",
                        "mobile": null,
                        "web": "<21.01"
                    },
                    "browser": {
                        "firefox": ["82", "83"],
                        "chrome": "*",
                        "chromium": null
                    },
                    "transport": {
                        "bridge": ["2.0.30", "2.0.27"], # str or array
                        "webusbplugin":  "*"
                    },
                    "devices": [
                        {
                            "model": "1", # str: device model "t" or "1"
                            "firmware": "1.9.4", # str or array: firmware version
                            "vendor": "trezor.io"
                        },
                        ...
                    ]
                },
            ...
            ],
            "message": {
                "id": "0f3ec64d-c3e4-4787-8106-162f3ac14c34", # unique identifier
                "active": true,
                "priority": 10, # range 1 to 10
                "dismissible": true, # bool: user can close this notification and never see it again
                "variant": "warning", # enum: info (blue), warning (orange), critical (red)
                "category": "banner", # str or array; banner, context, modal
                "content": {
                    "en-GB": "New Trezor firmware is available!",
                    "de-DE": "Neue Trezor Firmware ist verfügbar!"
                },
                "cta": { # only for banner and context 
                    "action": "interval-link", # enum: internal-link, external-link
                    "href": "firmware-index",
                    "label": {
                        "en-GB": "Update now",
                        "de-DE": "Jetzt aktualisieren"
                    }
                },
                "modal": {
                    "title": {
                        "en-GB": "Update now",
                        "de-DE": "Jetzt aktualisieren"
                    },
                    "image": "https://example.com/example.png"
                }, # only for category "modal"
                "domain": [ 
                    "coins.*.receive",
                    "coins.btc"
                ] # str or array: allow wildcards *; only for category "context"
            }
        }
    ]
}
```

Few notes:
- This JSON will be signed. We can JOSE/JWS. See https://en.wikipedia.org/wiki/JSON_Web_Signature, https://jose.readthedocs.io/. Question: isn't TLS enough?
- The JSON will be fetched on startup and then periodically every 6 hours.
- We will serve [commit].json and [VERSION].json (can be symlink) from data.trezor.io/messages/suite. Question: don't we want it in some repo as well for better auditability?
- Suite MUST work without the file as well (e.g. remember the latest file).

**Comment by tsusanka** [comment]
@prusnak our job candidate pointed very good point in https://github.com/trezor/trezor-suite/pull/3271 whether we actually need JOSE/JWS since we will serve the JSON over HTTPS. And honestly I am not sure myself, isn't TLS enough? I guess it provides a bit more control when signing it explicitly but at the same time it will need more management. What do you think?

**Comment by goodhoko** [comment]
@tsusanka I think the question that needs to be asked is: Do we believe the host machine of the app to properly validate TLS certificates?

If an attacker installed a fake certificate on the user's machine s/he then could spoof our HTTPS request for the messages. We can indeed protect against this by explicit signing. However effectiveness of that is questionable because at that point the attacker already has admin privileges on the user's machine.

**Comment by keraf** [comment]
> @tsusanka I think the question that needs to be asked is: Do we believe the host machine of the app to properly validate TLS certificates?
> 
> If an attacker installed a fake certificate on the user's machine s/he then could spoof our HTTPS request for the messages. We can indeed protect against this by explicit signing. However effectiveness of that is questionable because at that point the attacker already has admin privileges on the user's machine.

This. But even without admin privileges (given the user has installed a bogus CA/certificate), if there is a MITM, we need to get the public key for verifying the signature of the message. And at this point, nothing can guarantee the public key can be trusted. That additional step would be redundant.

On desktop though, we could bundle the key with the application. But that security can only be guaranteed as long as the user's machine isn't compromised and the application has not been tampered with. Still, that would be a good additional check.

**Comment by szymonlesisz** [comment]
it would be nice to be able to trigger:
* update trezor-connect files (mainly releases.json)
* update binaries (trezord, tor)

**Comment by tsusanka** [comment]
Note that we could use [JSON Schema](https://json-schema.org) to have it typed. It would also be consistent with https://github.com/trezor/trezor-firmware/issues/1264#issuecomment-783339187.

**Comment by tsusanka** [comment]
@matejzak please prepare the design for the notifications/announcements.

**Comment by tsusanka** [comment]
Summary of the thoughts above:
- @matejzak will prepare the design for the notifications/annoucements. 
- The JSON will be signed. We can JOSE/JWS.
- We want to use JSON Schema to type the items.
- We will sign via the codesign workflow similarly to how we sign Suite.
- The config will live at data.trezor.io.
- The config will be stored directly in trezor-suite repository unless there is a strong argument against it.
- Suite MUST work without the file as well (e.g. remember the latest file).

**Comment by glacierbits** [comment]
FYI I have added the product spec into the task description. ☝🏽  
Final design is expected to be delivered by Monday (March 8).

**Comment by tomasklim** [comment]
### Problems to discuss on 10/3/2021:

**JSON config**

- Property for expressing "banner" / "modal" / "context" types of messages? **yes**
- Does "location" have some meaning for banner and modal type of messages? **no**
- "enabled" when a service is not specified. Does it mean that it is "false" or it's both (true/false)? How to make combinations of true/false? **2. option**

1. Now:
`"enabled": ["tor", "btc"]`

2. Better:
```
"enabled": [
    {"tor": true, "btc": true}, {"tor": false, "ltc": true"}
]
```

If a property is not available (undefined), then it can be true/false.

- Action object improvements **yes**
```
{
   "id":"cdda48e6-df6d-4780-9cf1-8c84e7f3a6f9",          # random 32 chars (does not matter)
   "active":true,
   "if":{                                        # rename to condition?
      "...":"..."
   },
   "message":{                       # "then" deleted?
      "...":"..."
   }
}
```

**Banners**

- We need to solve the priorities of message system banners with the existing ones. The messages have three types of priorities: low, medium, high. Are these priorities equal to "info", "warning" and "critical" variants of notifications? **Make priorities 1-10 or 1-100**
- Right now, these banners are only "info" (blue colour) and "warning" (red colour => is this correct naming?), which colour for critical? **info = blue, warning = orange, critical = red**
- Which CTAs? The localisation of CTAs? **navigation in app + link outside of app; yes in config**

Existing banners:
1. Online status (warning, non-dismissable, can be with 2, 3, 4, 5 at once)
2. Failed backup (warning, non-dismissable) **Priority 9**
3. No backup (warning, non-dismissable) **Priority 7**
4. Update bridge (info, non-dismissable) **Priority 5**
5. Update firmware (info, non-dismissable) **Priority 3**

If the user closes one banner and another one is displayed right away, is it okay from the UX/UI point of view? **Yes**

**Modals**

- _"Since the modal warning is dismissible, it needs to be accompanied with either banner or context notification"_ => add a property for addressing this? **yes**
- Based on [Notion](https://www.notion.so/Secure-messaging-system-8ca41332ce504a0f8f6d74fc4bb9c8ab) description: add a header property and an image property? **yes**
- Priorities of existing modals? e.g. user has a "pin change" modal open and there are new messages fetched, what should happen? **If the modal message is critical and other modal is open, then it should restart the app and show the modal. If some other modal is opened and the new message is not critical, then show the modal next time you refresh the app, because the message will be displayed in banner or context notification anyway. If no modal is opened, it will show the modal immediately. ...Opened for changes in later...**

**Context**

- Where in the app can these context notification appear? The question is if it should be implemented for all eventual cases in the future or only for these notifications? [Link](https://www.notion.so/1d622e7079c14f64a03fa17f50bce14f?v=b8649de184c3437abb983990c5513e5f) **Right now designed for coin detail**

**[Second comment](https://github.com/trezor/trezor-suite/issues/2752#issuecomment-762824532) updated**

**Comment by bosomt** [comment]
is there anything that can be tested on our side ? Or we can move this issue from Needs QA section ?

**Comment by tomasklim** [comment]
> is there anything that can be tested on our side? Or we can move this issue from Needs QA section?

@bosomt For now, you can test that top banners are working properly. (Failed backup, ...)

Messaging system should be tested. However, @tsusanka recommends doing it after you test the other features, or even after release. Because it is a big feature which users will not see for some time (hopefully) and you will probably spend some time on it.

But if you have time, you can contact me and I can explain you how to test it, how to make configs,... and I can also prepare some test configs for you to start with.

**Comment by tsusanka** [comment]
Yes I agree!

**Comment by tomasklim** [comment]
@bosomt @sbstrd Feel free to contact me for more info and better explanation

I created two configs to be tested by QA.
**1.**
```{
    "version": 1,
    "timestamp": "2021-03-03T03:48:16+00:00",
    "sequence": 14,
    "actions": [
        {
            "conditions": [
                {
                    "duration": {
                        "from": "2021-01-01T12:10:00.000Z",
                        "to": "2022-01-31T12:10:00.000Z"
                    },
                    "os": {
                        "macos": ["10.14", "10.15", "10.18", "11"],
                        "linux": "*",
                        "windows": "*",
                        "android": "*",
                        "ios": "13"
                    },
                    "environment": {
                        "desktop": "<21.10",
                        "mobile": "!",
                        "web": "<22"
                    },
                    "browser": {
                        "firefox": ["82", "88"],
                        "chrome": "*",
                        "chromium": "!"
                    },
                    "transport": {
                        "bridge": ["2.0.31", "2.0.30", "2.0.27"],
                        "webusbplugin": "*"
                    },
                    "settings": [
                        {
                            "tor": true,
                            "btc": true
                        },
                        {
                            "tor": false,
                            "ltc": true
                        }
                    ],
                    "devices": [
                        {
                            "model": "1",
                            "firmware": ["1.9.4", "1.9.3"],
                            "vendor": "trezor.io"
                        },
                        {
                            "model": "T",
                            "firmware": ">=2.3.6",
                            "vendor": "trezor.io"
                        }
                    ]
                }
            ],
            "message": {
                "id": "0f3ec64d-c3e4-4787-8106-162f3ac14c34",
                "priority": 91,
                "dismissible": true,
                "variant": "warning",
                "category": "banner",
                "content": {
                    "en-GB": "New Trezor firmware is available!",
                    "de-DE": "Neue Trezor Firmware ist verfügbar!"
                },
                "cta": {
                    "action": "internal-link",
                    "link": "firmware-index",
                    "label": {
                        "en-GB": "Update now",
                        "de-DE": "Jetzt aktualisieren"
                    }
                }
            }
        }
    ]
}
```

Web:
https://suite.corp.sldev.cz/suite-web/qa/msg-system-test-1/web/

Linux:
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/1248216869
Mac:
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/1248216868
Windows:
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/1248216870

Please test that it shows orange banner with text "New Trezor firmware is available!" and it opens update firmware modal.
Conditions (you have to satisfy all of these, to be able to see the banner)
- TT with FW 2.3.6 or T1 with FW 1.9.4 or 1.9.3
- You have tor disabled and Litecoin enabled or tor enabled and bitcoin enabled
- You use WebUsbPlugin or bridge in version 2.0.27, 2.0.30, 2.0.31
- You use any version of chrome or firefox 88
- You use any version of Linux, Windows or macos in version 11 or 10.15

The Linux and Windows is especially important as I tested it only on macOS.

The banner should be dismissible, so if you close, you should not be able to see it on refresh.
The banner has highest priority, so when e.g. no backup banner should be visible, it is replaced by this one.

**2.**
```{
    "version": 1,
    "timestamp": "2021-03-03T03:48:16+00:00",
    "sequence": 17,
    "actions": [
        {
            "conditions": [
                {
                    "duration": {
                        "from": "2021-01-01T12:10:00.000Z",
                        "to": "2022-01-31T12:10:00.000Z"
                    },
                    "os": {
                        "macos": "*",
                        "linux": "!",
                        "windows": "*",
                        "android": "*",
                        "ios": "13"
                    },
                    "environment": {
                        "desktop": "21",
                        "mobile": "!",
                        "web": "21"
                    },
                    "browser": {
                        "firefox": "*",
                        "chrome": ">30",
                        "chromium": "!"
                    },
                    "transport": {
                        "bridge": "*",
                        "webusbplugin": "!"
                    },
                    "settings": [
                        {
                            "tor": true,
                            "btc": true
                        },
                        {
                            "tor": false,
                            "ltc": true
                        }
                    ],
                    "devices": [
                        {
                            "model": "1",
                            "firmware": ["1.9.4", "1.9.3"],
                            "vendor": "trezor.io"
                        },
                        {
                            "model": "T",
                            "firmware": ">=2.3.6",
                            "vendor": "trezor.io"
                        }
                    ]
                }
            ],
            "message": {
                "id": "0f3ec64d-c3e4-4787-8106-162f3ac14c35",
                "priority": 61,
                "dismissible": false,
                "variant": "info",
                "category": "banner",
                "content": {
                    "en-GB": "New Trezor post is on Medium!",
                    "de-DE": "Neue Trezor Artikel ist auf Medium!"
                },
                "cta": {
                    "action": "external-link",
                    "link": "https://blog.trezor.io/how-taproot-will-benefit-hardware-wallets-fa43c0b6123e",
                    "label": {
                        "en-GB": "Read now",
                        "de-DE": "Lies jetzt"
                    }
                }
            }
        }
    ]
}
```

Web:
https://suite.corp.sldev.cz/suite-web/qa/msg-system-test-2/web/

Linux:
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/1248241168
Mac:
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/1248241167
Windows:
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/1248241169

Please test that it shows blue banner with text "New Trezor post is on Medium!" and it opens new tab in browser with Medium page.
Conditions (you have to satisfy all of these, to be able to see the banner)
- TT with FW 2.3.6 or T1 with FW 1.9.4 or 1.9.3
- You have tor disabled and Litecoin enabled or tor enabled and bitcoin enabled
- You use any version of bridge
- You use any version of chrome or firefox
- You use any version of windows or macos

The Linux is especially important as I tested it only on macOS.
Please also test, that it is not visible on windows, if you satisfy all other conditions.

The banner should not be dismissible, so if you close, you should not be able to see it on refresh.
The banner has priority lower than No backup banner, so you should not be able to see it, if you have this No backup banner.

Linux (invisible) and windows (visible) is especially important as I tested it only on macOS.

----------------------

When you open test case 1, you should see orange banner (if you satisfy conditions). Then when you open test case 2, you should see blue banner (if you satisfy conditions). If you open test case 1 again (in the same browser, without wiped storage), you should not be able to satisfy conditions from test case 1, as test case 2 is newer and it replaced config from test case 1. So you should still be able to see only blue banner (if you satisfy conditions from test case 1)

**Comment by STew790** [comment]
Test case 2:

Tried this on Win10 machine and works as intended, just one little thing is that the blue bar is missing an "X" to hide it.

Info:
 - Suite version: desktop 21.5.0 (4a91b40e005a1e94255aaf80e2169c195b600852)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.5.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win 10
 - Screen: 1920x1080
 - Device: model T 2.3.6 regular

![image](https://user-images.githubusercontent.com/48477147/118103905-bc665e80-b3da-11eb-8d72-5cd27b49bb23.png)

**Comment by tomasklim** [comment]
@STew790 it should not be dismissible, sorry, copy-paste error in the description. The config has `dismissible: false`, so it works as it should.

**Comment by wendys-cats** [comment]
**QA OK**

**test case1 OK**
1. Banner from RSMS has the highest priority - OK.
2. Once newer config (config from TC2) is present, config from TC1 is replaced by it.

**Windows APP**
Suite version: desktop 21.5.0 (4a91b40)
TT 2.3.6 - bridge 2.0.27 - BTC + tor  = banner shown
TT2.3.6 - bridge 2.0.27 - LCT  = banner shown
TT 2.3.6 - bridge 2.0.27 - BTC + tor + LTC OK = banner shown
TT 2.3.6 - bridge 2.0.27 - BTC + LTC OK = banner shown
T1 1.9.3 - FW with no backup - bridge 2.0.27 + LTC = banner shown

**NixOS web**
Suite version: desktop 21.5.0 (4a91b40)
TT 2.3.6 - bridge 2.0.30 - FF Version 82 - LTC = banner shown
TT 2.3.6 - bridge 2.0.30 - Chrome 88 version - LTC = banner shown
TT 2.3.6 - no bridge, webusb only - Chrome version 88 - LTC = banner shown

**test case2 OK**
1. Once newer config (config from TC2) is present, config from TC1 is replaced by it.
2. Linux does not show banner at all.

**Windows APP**
Suite version: desktop 21.5.0 (4a91b40)
TT 2.3.6 - bridge 2.0.27 - BTC + tor  = banner shown
TT2.3.6 - bridge 2.0.27 - LCT  = banner shown
TT 2.3.6 - bridge 2.0.27 - BTC + tor + LTC OK = banner shown
TT 2.3.6 - bridge 2.0.27 - BTC + LTC OK = banner shown
T1 1.9.3 - FW with no backup - bridge 2.0.27 + LTC = banner shown

**NixOS web**
Suite version: desktop 21.5.0 (4a91b40)
TT 2.3.6 - bridge 2.0.30 - FF Version 82 - LTC = NO banner shown
TT 2.3.6 - bridge 2.0.30 - Chrome 88 version - LTC = NO banner shown
TT 2.3.6 - no bridge, webusb only - Chrome version 88 - LTC = NO banner shown
