### ISSUE TITLE
App can't be closed on Linux

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2754]
**Info:**
 - OS: NixOS
 - Browser: desktop
 - Wallet Version: 34e505ec96de077e9064e76ac4e835e62d53a338
 
**Describe the bug**
You click on the "cross" icon but nothing happens.

**Steps to reproduce:**
1. Try to close the app

---

Probably introduced by the custom title bar. Most likely will be fixed by https://github.com/trezor/trezor-suite/pull/2733.

**Comment by mroz22** [comment]
I can confirm this for Ubuntu

**Comment by bosomt** [comment]
I can confirm this for Windows 10 too.

minimise maximise close buttons are not working.
Even Task manager had problems to close app /it worked on 3. try/

Windows 10  with auto update enabled
Suite: app Commit 34e505ec96de077e9064e76ac4e835e62d53a338
Device: Trezor Model T firmware 2.3.4

**Comment by sorooris** [comment]
@bosomt pls add the following info in your comment as we usually do everywhere else:

Suite: app/web, version + commit hash
OS: version + build
Device: model, version + revision

T. Hanks.
![image](https://user-images.githubusercontent.com/10185314/97178963-89d77a00-1798-11eb-964d-78bc303fc982.png)
