### ISSUE TITLE
Invity - Buy - flow blocked with any provider

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2757]
**Info:**
 - OS: macOS Catalina 10.15.7
 - Suite: app 20.11.0 staging 34e505ec96de077e9064e76ac4e835e62d53a338
 - Device: model T 2.3.4 50854b921
 - API server: staging-exchange
 
**Describe the bug**
Buy flow cannot be finished in the app version of Suite - provider's payment gateway.

**Steps to reproduce:**
1. Launch Suite and navigate to Accounts -> Trade -> Buy,
2. Enter an arbitrary amount above minimum and confirm,
3. Select any offer (tested Simplex) and confirm,
4. Confirm receiving address on device and select The Finish transaction button.

**Actual result:**
A new electron app window is opened with only the header displayed; no content on the page is displayed. Same applies to the other providers (mercuryo, BTC Direct).

**Expected result:**

# Note: None of the testing devices have VPNs installed.

**Screenshots:**
**Simplex**
![image](https://user-images.githubusercontent.com/10185314/97182505-e9378900-179c-11eb-9964-067dd5f03156.png)
**mercuryo**
![image](https://user-images.githubusercontent.com/10185314/97184416-2ac93380-179f-11eb-8c38-7ef40d1e1a8f.png)
**BTC Direct**
![image](https://user-images.githubusercontent.com/10185314/97184363-1b49ea80-179f-11eb-9c8e-12980ff35967.png)

**Comment by tsusanka** [comment]
@martinboehm please have a look. Binaries are available at https://staging-wallet.trezor.io

**Comment by sorooris** [comment]
Neither staging exchange nor production API servers are accessible.

OS: macOS Catalina 10.15.7
Suite: app 20.11.0 staging 46ab9e5b99354942d8ddec2df8ccc5db734c12be
Device: model T 2.3.4 50854b921

**Comment by martinboehm** [comment]
You will have to use new binaries when the PR #2762 is merged to develop.

**Comment by sorooris** [comment]
Flow is functionally **OK** but it's not apparent in the default desktop app window size that there is a list of transactions on the screen when returning from the provider's payment gateway -> payment detail -> the Account/Trade tab.

There are missing indications that the list of transactions is present under the CoinmarketLayout__Content element - user has to (accidentally) scroll down the screen to find out.

OS: macOS Catalina 10.15.7
Suite: app 20.11.0 staging aa1c2341473ee9285ced799ddbb23229627874bc
Device: model T 2.3.4 50854b921

Screenshot:
After returning from the completed Buy flow.
![image](https://user-images.githubusercontent.com/10185314/97454636-436c5180-1937-11eb-8c17-91554d7646ee.png)
After scrolling down.
![image](https://user-images.githubusercontent.com/10185314/97454575-351e3580-1937-11eb-98f1-6be3d4df6db7.png)

**Comment by tsusanka** [comment]
@sorooris could you open a new issue for this? So we can tackle it properly later. You're right it would be nice if it would get scrolled down so you get some visual feedback. Seems like a new issue though.

**Comment by sorooris** [comment]
Opened a new issue #2782, closing this one.
