### ISSUE TITLE
 Support Zcash Canopy hardfork

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2764]
The Zcash network will undergo its next network upgrade, named Canopy, at blockheight 1046400, which is expected to be mined on approximately November 18th.

We need to start sending `0xE9FF75A6` as the new consensus branch id. That should be all that's required.

This PR could help: https://github.com/trezor/trezor-suite/pull/2072/files.

We should include this in the upcoming release :/.

----

More info from the email:
```
This network upgrade contains changes to Zcash consensus and therefore requires all network participants
to upgrade their Zcashd nodes and accompanying software to version 4.0.0 or later. We've released the
Canopy Network Upgrade Guide with more information.

 The main changes in this upgrade include: 
    ZIP 251 defines the Consensus Branch ID, which should be updated to 0xE9FF75A6
    ZIP 207 and ZIP 214 are needed to establish a new development fund. 
    ZIP 211 disables the ability to add new value to the Sprout value pool balance. 
    ZIP 212 improves the security assumptions needed to ensure that diversified addresses are not linkable. 
    ZIP 215 improves the validity criteria of Ed25519 signatures used in Sprout transactions.
```

**Comment by tsusanka** [comment]
And I am afraid we need to do that for the old wallet as well :/. https://github.com/satoshilabs/mytrezor/issues/958

**Comment by szymonlesisz** [comment]
suite part is ready, there is no way to test it on mainnet. but i did it in exact same way as previous fork so in 99.9% it will work :)
https://github.com/trezor/trezor-suite/pull/2795/commits/33e524beac69640ebd4a3914a1b8514cfe56e8a8

additionally i've created a branch with added "Zcash Testnet" coin where this fork is already implemented (new branch id is required) and looks like it's working
https://suite.corp.sldev.cz/suite-web/test/zcash-testnet/web/accounts/send/#/taz/0

**Comment by tsusanka** [comment]
So we can close?

**Comment by szymonlesisz** [comment]
from the suite point of view yes, its ready but maybe leave it opened until implemented in old wallet

**Comment by prusnak** [comment]
Old wallet has it's own issue - https://github.com/satoshilabs/mytrezor/issues/958

Closing

**Comment by bosomt** [comment]
@tsusanka @prusnak 
it there anything that we can test on our side ?

**Comment by tsusanka** [comment]
@bosomt as Szymon says it can be tested at https://suite.corp.sldev.cz/suite-web/test/zcash-testnet/web/accounts/send/#/taz/0 . But since Szymon already tested it I am not sure it is still needed. If you have a testnet zcash easily available go for it.

**Comment by bosomt** [comment]
**QA OK**

https://blockbook-dev.corp.sldev.cz:19132/tx/7e530e41f1ed06bd220bc4d4e5506cc300e6ada8728e9bb16484531b9c154444

Nixos + Chromium 86
Suite web commit 9959d18d60612922d52550cea22f69d71ee0467f
Device model One FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
