### ISSUE TITLE
Receive icon in TX detail

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2765]
Incorrect receive icon. 

Receive and Sent icon in TX detail should be different (inboud vs. outbound arrow). 

<img width="836" alt="Screenshot 2020-10-27 at 13 22 14" src="https://user-images.githubusercontent.com/29627086/97300972-72ab9180-1857-11eb-8be5-e0ca37675d5d.png">

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82.0 (64-bit)
Suite web dev master commit a5b13d5
Device model TT FW 2.3.3 commit 0d5f00668
