### ISSUE TITLE
Firmware update modals inconsistency

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2768]
**Info:**
 - OS: Kubuntu 20.04
 - Wallet Version: app, commit 46ab9e5b99354942d8ddec2df8ccc5db734c12be
 - Firmware Version: model T firmware 2.3.3, 
 
**Describe the bug**
+ Firmware update modals look inconsistent. They use different headers and alignments.
+ Main reason why i'm sending this issue: it's not possible to close second step. 
Only thing you can do is to confirm that you have seed, First and third step can interrupt update process. 

**Steps to reproduce:**
1. Start Suite app and connect Trezor with outdated firmware
2. Try to interrupt update in `I have seed` step
3. Observe

**Expected result:**
You can interrupt update process in any step

**Actual result:**
You have to disconnect device or reload suite to interrupt update process when you don't have your seed backup

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/97303769-206c6f80-185b-11eb-81af-9f931779fc1b.png)

![image](https://user-images.githubusercontent.com/31506317/97303809-2f532200-185b-11eb-824b-3f5668e57fab.png)

![image](https://user-images.githubusercontent.com/31506317/97303789-282c1400-185b-11eb-848e-65abd0518419.png)

**Comment by bosomt** [comment]
**QA OK**

it looks like you missed two steps. that have different alignment.
If it's part of design please close and move to approved @matejzak 

Nixos + Firefox Browser 82
Suite web dev master commit 374d027
Device model T fw 2.3.4 commit 50854b921

1
![image](https://user-images.githubusercontent.com/31506317/99362304-9b053980-28b3-11eb-97dd-c2f164ba395c.png)

2
![image](https://user-images.githubusercontent.com/31506317/99362333-a5bfce80-28b3-11eb-978c-f63b6c6096cc.png)

3
![image](https://user-images.githubusercontent.com/31506317/99362394-bcfebc00-28b3-11eb-9d42-2032844d34ad.png)

4
![image](https://user-images.githubusercontent.com/31506317/99362434-c720ba80-28b3-11eb-8d9a-6f9aca6c199e.png)

5
![image](https://user-images.githubusercontent.com/31506317/99362489-da338a80-28b3-11eb-9c71-36279efad1ad.png)

6
![image](https://user-images.githubusercontent.com/31506317/99362549-ecadc400-28b3-11eb-9a9c-474a66e140b6.png)

**Comment by mroz22** [comment]
I'd say this is not related strictly to firmware modals but to components in general. What does @slowbackspace means about this?

**Comment by bosomt** [comment]
Obsolete issue.
Brand new onboarding in next release.
