### ISSUE TITLE
Coin control 🎯

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2770]
**The aim is to allow users to opt-in for manual coin selection instead of automatic coin selection when making an outgoing transaction.** 

Automatic coin selection should remain default, users have to be informed, that switching to manual will let them take control of their strategy for transaction optimisation.

<details close>
<summary>Default Send flow in Suite will remain almost untouched, except a button, which will enable Coin control.:</summary>
<br/>
<pre>

![2 2 1 — Accounts — Send Coin Control](https://user-images.githubusercontent.com/26002916/179991147-dff18996-caf2-495a-a2c0-931fe94c1542.png)

</pre></details>

<details open>
<summary>Opened Coin Control:</summary>
<br/>
<pre>

![2 2 1 — Accounts — Coin Control Opened](https://user-images.githubusercontent.com/26002916/180590597-fdfaf786-3f2b-4770-bba3-ca51df9b57c7.png)

</pre></details>

<details close>
<summary>Coin control on</summary>
<br/>
<pre>

![2 2 1 — Accounts — Custom Coin Selection](https://user-images.githubusercontent.com/26002916/180590604-c995023c-bdd8-44e7-be14-561587333874.png)

</pre></details>

Closed coin control button detail:
| Coin control OFF | Coin control ON |
|---|---|
| ![Button](https://user-images.githubusercontent.com/26002916/180590664-3a013334-23ca-4ce1-a6ad-d079e1a84c93.png) | ![coincontrol on](https://user-images.githubusercontent.com/26002916/180590668-eb218eba-2449-4fc4-b187-f32eb09e2974.png) |

Change UI element for `send max` to toggle:
| ![send max old](https://user-images.githubusercontent.com/26002916/179993595-1966312a-9337-455b-a508-39e55702bf35.jpg) | →  | ![send amx](https://user-images.githubusercontent.com/26002916/179993622-f8d9c891-56d8-4e99-adcc-9205d59e3f6d.png) |
|---|---|---|

Edge cases and other notes in [Notion](https://www.notion.so/satoshilabs/Coin-control-c942a3c338844a09aabe30ad627051e6)

**Comment by xanoni** [comment]
Woah. Trezor Suite quickly turning into "teh shit". Great priorities!

**Comment by xanoni** [comment]
Sad to see this being pushed back :( This is the main gap keeping me from using Trezor Suite for UTXO-based coins. 

When I do use it, I have to perform "manual coin control". That is, I carefully set the tx amount and tx fee such that the Trezor algorithm selects the coins that I want to use. (And then confirm that it will do what I expect by inspecting the JSON in the transaction details.

However, this obviously causes a ton of mental overhead, and often requires quite some trial and error.

PS: Which coins are you planning to implement this for? Just Bitcoin, or more (LTC, BCH, etc.)? @matejzak

**Comment by HeroHann** [comment]
Same opinion as @xanoni
There are several other needed features to provide a good experience in suite.
Me personally feel, that resources should not work on the „trading“ via Invity but on Defi Dapp and professional additions to the Trezor Suite.

Why is this pushed back since half a year?

**Comment by ste7** [comment]
Is this ever going to be released?

**Comment by trymeouteh** [comment]
Would like this feature for all UTXO coins supported in Trezor Suite (BTC, BCH, LTC, DASH, DGB, etc) and have this feature enabled by default to prevent any errors of a new installation of sending funds from two or more addresses out.

**Comment by 0xmichalis** [comment]
It's unfortunate to see this deprioritized.

**Comment by Rambreack** [comment]
Hii

**Comment by xanoni** [comment]
What's the story? I can't believe this was de-prioritized. After all, Trezor is a Bitcoin first company and this is an essential feature. Yes it's not for newbies, but it's something newbies have to learn.

**Comment by prusnak** [comment]
WIP PR in https://github.com/trezor/trezor-suite/pull/4281

**Comment by xanoni** [comment]
> WIP PR in #4281

Great, in Trezor we trust ;-)

**Comment by kn0wmad** [comment]
Really eager to see this get merged.  Serious blocker.  Thanks and keep up the great work!

**Comment by xanoni** [comment]
Ledger Suite has this, by the way

**Comment by nmullesch** [comment]
Why has it been moved to the freezer?

**Comment by bosomt** [comment]
We probably should move this issue back from `Needs QA` to `In progress` right ?

**Comment by hynek-jina** [comment]
@bosomt I've moved it back to `Needs review` where it now belongs..

**Comment by komret** [comment]
**QA:** The screens here are a little outdated, please check the main PR (#6019) for a more detailed list of changes. More QA comments are included in the PRs.

**Comment by STew790** [comment]
**QA OK**
All PRs approved by QA.
