### ISSUE TITLE
Unify the desktop app header on Mac OS

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#2771]
Screenshot of different apps and the suite.

![image](https://user-images.githubusercontent.com/3112191/97315189-be1a6b80-1868-11eb-8db2-24c59789590e.png)

**Comment by glacierbits** [comment]
@tomexx, please also consider: 

- [x] MacOS standard icons within the `close – maximaze – minimaze` buttons.  <img width="60" alt="Screenshot 2020-10-28 at 21 32 14" src="https://user-images.githubusercontent.com/29627086/97493296-0d45c680-1965-11eb-88ed-e0a1ec106c33.png"> 

- [x] Make the buttons disabled when other window is active ([Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f6b0073aa3cbd1a4cd1a5af)). Example:
<img width="372" alt="Screenshot 2020-10-28 at 16 20 11" src="https://user-images.githubusercontent.com/29627086/97494125-3024aa80-1966-11eb-9c32-951319ca7768.png">

**Comment by sorooris** [comment]
**QA OK**

App header appears consistent and behaves correctly.

Suite version: app 513631a9fa62c438e60397a9942b04275bcd621a
OS: macOS Catalina 10.15.7
Device: 2.3.4 50854b921
