### ISSUE TITLE
Invity - improve external pages opening in the desktop version

### ISSUE THREAD

**Issue by martinboehm** [trezor/trezor-suite#2774]
- move invity urls from allowedExternalUrls to invityUrls
- drop ELECTRON_RECEIVER_SERVER usage (buyUtils), always redirect to the same url regardless of the environment and handle request in electron handleExternalLink function (invityUrls validation)

**Comment by szymonlesisz** [comment]
related to https://github.com/trezor/trezor-suite/pull/2762/files

refactor buyUtils:
- getAmountLimits
- createTxLink
- submitRequestForm

and use the same requests regardless of env

catch request in electron, similar to `handleExternalLink`, filter invity urls (electron config), lookup at incoming request if it's a POST (submitRequestForm) or GET with redirection (getAmountLimits, createTxLink) and act accordingly: either open local http server and repost data or just open native browser
