### ISSUE TITLE
Trade, Buy - Missing visual indication of previous trade transactions in default app window size

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2782]
OS: macOS Catalina 10.15.7
Suite: app 20.11.0 staging aa1c2341473ee9285ced799ddbb23229627874bc
Device: model T 2.3.4 50854b921
 
**Describe the bug**
It's not apparent in the default desktop app window size that there is a list of trades on the screen when returning from the provider's payment gateway -> payment detail -> the Account/Trade tab.

**Steps to reproduce:**
Prequisite - default app window size.

1. Navigate to the Trade tab -> Buy,
2. Complete the Buy flow,
3. Navigate from the trade detail to the Trade tab.

**Expected result:**
a) Screen is automatically scrolled down and focus is put on the trades list instead of the _CoinmarketLayout__Content_ element when returning to the Trade tab.
b) User-friendly indications that the trades list is below the _CoinmarketLayout__Content_ element.

**Actual result:**
User is redirected to the Trade tab (_CoinmarketLayout__Content_ element) and the in-progress and/or completed trades are **not immediately visible in the default window size**. No indications that the trades list is located below the CoinmarketLayout__Content element are displayed - user has to (accidentally) scroll down the screen to find out.

**Screenshots:**
After returning from the completed Buy flow.
![image](https://user-images.githubusercontent.com/10185314/97454636-436c5180-1937-11eb-8c17-91554d7646ee.png)
After scrolling down.
![image](https://user-images.githubusercontent.com/10185314/97454575-351e3580-1937-11eb-98f1-6be3d4df6db7.png)

**Comment by martinboehm** [comment]
Obsolete
