### ISSUE TITLE
Send: Design improvements

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2784]
- [x] **Avoid custom fee "jumpy" white box** : [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5efc87aefaf0aa9cd861d17f)
Fee segmented control > e.g. change from Normal to Custom > Result: White box decreases in height

~~- [ ] **Fiat dropdown** (Should be fixed by #2480) 
The arrow should appear on hover on the whole input (discussed with Invity, they need for it to work this way elsewhere). Also, cursor should not appear in the dropdown. E.g. pressing key "C" should not filter the currencies but scroll alphabetically.~~

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82.0.3 (64-bit)
Suite web dev master commit 3cfa1ae
Device 2.3.5 model T
