### ISSUE TITLE
Trade - country flag icons missing in Windows

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2790]
**Info:**
 - OS: Windows 10 
 - Browser: Firefox 82 + Chrome 81
 - Wallet Version: app + web, commit aa1c2341473ee9285ced799ddbb23229627874bc
 - Firmware Version: 2.3.3 model T 
 
**Describe the bug**

There are missing country flags in `Offers for` country selector in Trade tab.
They are replaced by misaligned text. 

**Steps to reproduce:**
1. Start or load Suite in current Windows 10
2. Visit Trade tab 
3. Observe `Offers for: ` selector

**Expected result:**
Country flags are available in Windows 10 app or web version of Suite

**Actual result:**
Country flag icons in country selector are replaced by ugly misaligned text 

**Screenshots:**

`Windows 10`
![image](https://user-images.githubusercontent.com/31506317/97547019-8aa52180-19cd-11eb-8bbd-5171d2521193.png)

`Linux web`
![image](https://user-images.githubusercontent.com/31506317/97547642-54b46d00-19ce-11eb-826f-d7ec18c4cb87.png)

**Comment by martinboehm** [comment]
Fixed by #3052.

**Comment by bosomt** [comment]
**QA OK**

Windows 10
Suite dev master commit 42848e33
FW TT  2.3.5
