### ISSUE TITLE
Accounts bar in APP is missing bottom part

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2793]
**Info:**
 - OS: Windows 10 Home Edition (happens also on NixOS)
 - Suite Version: app commit 46ab9e5b99354942d8ddec2df8ccc5db734c12be
 - Firmware Version: model  TT 2.3.4 , revision public
 
**Describe the bug**
Accounts bar is missing a small part on the bottom of the app when scrolling is necessary - FIAT amount for the last account is not seen. And if legacy accounts are wrapped up and scrolling is necessary, this account section will no longer be visible (see gif, or video).

**Steps to reproduce:**
1. Open APP
2. Open coin accounts where scrolling is necessary in Accounts bar and coin has several account types
3. Wrap up Legacy accounts

**Expected result:**
Bottom of the Accounts bar will still be visible.

**Actual result:**
Bottom of the Accounts bar is missing/not visible. 

**Screenshots:**

![photo_2020-10-29_12-13-47](https://user-images.githubusercontent.com/58593111/97561550-a49c2f80-19e0-11eb-832f-7fa3bea101fd.jpg)

https://drive.google.com/file/d/1eLBvEGZlGY4XRe-2xFmjzs1wxdngZdEp/view

**Note(s):**
You can see in the video that APP is maximized, but legacy accounts section goes missing when wrapped up.

**Comment by bosomt** [comment]
**QA OK**

Nixos
Suide app dev maser commit 9a39d54d228aa9421939117d597bb5f61779a97d
Device mdoel T fw 2.3.4 commit 50854b921
