### ISSUE TITLE
remove zcash fork temporary code after 18.11

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#2796]
https://github.com/trezor/trezor-suite/pull/2795/commits/33e524beac69640ebd4a3914a1b8514cfe56e8a8

And think how to do it better in the future, ideal candidate for remote updates #2752

**Comment by szymonlesisz** [comment]
get branch id from blockbook
https://github.com/trezor/blockbook/pull/508

**Comment by goodhoko** [comment]
This was done some time ago. Forgot to close. Closing now.
