### ISSUE TITLE
Send, csv Import - empty line break imported into form as an empty entry

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2799]
Suite: web, _feat/import-tx/_ bf0b16915a034010cebf1c825e7fca47dbe9771d
Browser: Chromium 86.0.4240.111
OS: NixOS 20.09
Firmware Version: 2.3.4 50854b921
 
**Describe the bug**
A line with no characters imported as an empty entry when importing a csv file with transactions.

**Steps to reproduce:**
1. Navigate to Send tab of an arbitrary coin,
2. Select import in the Send form menu,
3. Import a csv file with an empty line break.

**Actual result:**
An empty entry is imported into the Send form.

**Expected result:**
Line with no characters is not imported into the Send form.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/97604006-4f2a4780-1a0d-11eb-9e67-dcbc4be3d63b.png)
![image](https://user-images.githubusercontent.com/10185314/97603979-43d71c00-1a0d-11eb-9657-99be9fc8ece4.png)

**Comment by szymonlesisz** [comment]
should be fixed

**Comment by sorooris** [comment]
**QA OK** 

Suite: web, _feat/import-tx/_ cfeb4eb7638bbdf50fd908c366ab13dcf924369c
Browser: Chromium 86.0.4240.111
OS: NixOS 20.09
Firmware Version: 2.3.4 50854b921
