### ISSUE TITLE
Font size inconsinsency due to root font size

### ISSUE THREAD

**Issue by adamsir** [trezor/trezor-suite#28]
REM diff
![image](https://user-images.githubusercontent.com/5871877/54156854-5c18b280-4447-11e9-91f3-89259cd8c53a.png)

PX diff (no font-size differences)
![image](https://user-images.githubusercontent.com/5871877/54156890-6f2b8280-4447-11e9-8c06-39b3aebe59fa.png)

**Comment by slowbackspace** [comment]
I have updated the readme inside `components` pkg about base font-size.
e43e7d05bc247f1d7529491c04748c6d6c502d6a
