### ISSUE TITLE
Send, csv Import - currency selector filled with coin abbreviation

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2801]
Suite: web, _feat/import-tx/_ bf0b16915a034010cebf1c825e7fca47dbe9771d
Browser: Chromium 86.0.4240.111
OS: NixOS 20.09
Firmware Version: 2.3.4 50854b921
 
**Describe the bug**
Fiat select filled with coin abbreviation.

**Steps to reproduce:**
1. Navigate to Send tab of an arbitrary coin,
2. Select import in the Send form menu,
3. Import a csv file with mixed coins (for example BTC and LTC) in the currency column.

**Actual result:**
Fiat select filled with coin abbreviation.

**Expected result:**
Fiat select detects mismatch and validates input as incorrect.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/97610203-db8c3880-1a14-11eb-993c-eaf62091c885.png)

![image](https://user-images.githubusercontent.com/10185314/97610187-d6c78480-1a14-11eb-90a0-489965979ed5.png)

**Comment by szymonlesisz** [comment]
turns out we do have rates in other cryptocurrencies, so it was false-positive rate was found it it wasn't a fiat rate :)

**Comment by szymonlesisz** [comment]
should be fixed

**Comment by sorooris** [comment]
**QA OK** 

Suite: web, _feat/import-tx/_ cfeb4eb7638bbdf50fd908c366ab13dcf924369c
Browser: Chromium 86.0.4240.111
OS: NixOS 20.09
Firmware Version: 2.3.4 50854b921
