### ISSUE TITLE
Send, csv Import - Fiat dropdown select clipped

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2802]
Suite: web, _feat/import-tx/_ bf0b16915a034010cebf1c825e7fca47dbe9771d
Browser: Chromium 86.0.4240.111
OS: NixOS 20.09
Firmware Version: 2.3.4 50854b921
 
**Describe the bug**

**Steps to reproduce:**
1. Navigate to Send tab of an arbitrary coin,
2. Select the dropdown select,
3. Observe.

**Actual result:**
Currency dropdown select is clipped when selected.

**Expected result:**
Currency dropdown select is overflows over elements below it.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/97611204-2490bc80-1a16-11eb-93b9-33617077c390.png)

**Comment by szymonlesisz** [comment]
@slowbackspace animation wrapper overflow hidden?

**Comment by szymonlesisz** [comment]
yes, thats it, tmp solution: https://github.com/trezor/trezor-suite/pull/2704/commits/cfeb4eb7638bbdf50fd908c366ab13dcf924369c

**Comment by szymonlesisz** [comment]
should be fixed (temporary solution, will be done better)

**Comment by sorooris** [comment]
**QA OK** 

Suite: web, _feat/import-tx/_ cfeb4eb7638bbdf50fd908c366ab13dcf924369c
Browser: Chromium 86.0.4240.111
OS: NixOS 20.09
Firmware Version: 2.3.4 50854b921
