### ISSUE TITLE
Send, csv Import - Suite freezes after importing 3+ address csv file

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2803]
Suite: web, _feat/import-tx/_ bf0b16915a034010cebf1c825e7fca47dbe9771d
Browser: Chromium 86.0.4240.111
OS: NixOS 20.09
Firmware Version: 2.3.4 50854b921
 
**Describe the bug**
Importing a csv file with more than 3 addresses causes the app to freeze.

**Steps to reproduce:**
1. Navigate to Send tab of an arbitrary coin,
2. Select import in the Send form menu,
3. Import a csv file with at least 4 addresses.

**Actual result:**
App freezes and needs to be restarted.

**Expected result:**
File is imported correctly without causing a freeze.

**Screenshots:**
File:
![image](https://user-images.githubusercontent.com/10185314/97621573-5b210400-1a23-11eb-8709-4628f5c29964.png)
Freezes here:
![image](https://user-images.githubusercontent.com/10185314/97621602-67a55c80-1a23-11eb-83dc-a3e5878b3ce8.png)

**Comment by szymonlesisz** [comment]
should be fixed

**Comment by sorooris** [comment]
**QA OK** 

Suite: web, _feat/import-tx/_ cfeb4eb7638bbdf50fd908c366ab13dcf924369c
Browser: Chromium 86.0.4240.111
OS: NixOS 20.09
Firmware Version: 2.3.4 50854b921
