### ISSUE TITLE
Weird behavior in the passphrase input

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#2807]
Test case:

1. write some words

![image](https://user-images.githubusercontent.com/3112191/97634068-64b36780-1a35-11eb-9f69-15fcae0fe214.png)

2. move cursor

![image](https://user-images.githubusercontent.com/3112191/97634135-7a289180-1a35-11eb-9d49-86e6b5517478.png)

3. click backspace

![image](https://user-images.githubusercontent.com/3112191/97634183-890f4400-1a35-11eb-894a-21de28014c7a.png)

**Comment by sorooris** [comment]
**QA OK**

Couldn't replicate issue.

Suite version: app 513631a9fa62c438e60397a9942b04275bcd621a
OS: macOS Catalina 10.15.7
Device: 2.3.4 50854b921
