### ISSUE TITLE
Misaligned labels

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2808]
`Sent to myself` label is positioned lower than `12:22 PM`

<img width="305" alt="Screenshot 2020-10-29 at 23 52 28" src="https://user-images.githubusercontent.com/29627086/97640810-d5f91780-1a41-11eb-8d31-39c464d3402a.png">

**Comment by mroz22** [comment]
Ah, I guess this might be due to the button which is little higher then the text

**Comment by wendys-cats** [comment]
**QA OK**

**OS** NixOS + Chromium 85
**Suite** web 20.11.1 39d1b9690756482310a3970de0d1a29b0d4d2e89
**Device** 2.3.4 public 50854b921
