### ISSUE TITLE
Multiple recipients sent misalignment 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2809]
Might be related (🤷🏽‍♀️) to #2808 

<img width="828" alt="Screenshot 2020-10-29 at 23 57 15" src="https://user-images.githubusercontent.com/29627086/97641186-954dce00-1a42-11eb-8ce0-837d738f9a3f.png">

**Comment by bosomt** [comment]
**QA OK**

looks good now, with labelling disabled or enabled


<img width="343" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/159441960-43e119a5-dbc2-4ef1-ba3f-8e006f5a5e37.png">

<img width="327" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/159442058-5d83a07f-d13c-4bef-ba22-0f81f0dd0be9.png">

**Info:**
 - Suite version: desktop 22.3.2 (563be1e28ad75ddd4e38c2002e6032b0743511d2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
