### ISSUE TITLE
Account tabs: Fixed content

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2810]
Let's fix the white boxes in all Accounts tabs in the same position, so they don't seemingly jump up and down when switching between Overview – Receive – Send – Trade. 

Thats means moving the white box in `Receive` and `Trade` down to match the exact position of the white box in `Overview` and `Send`.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82.0.3 (64-bit)
Suite web dev master commit 3cfa1ae56f61635c77e4046a76577bfd027fb05e
Device 2.3.5 model T
