### ISSUE TITLE
Add link to our roadmap to Suite landing page

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2811]
Let's add link to our roadmap to the footer of the suite.trezor.io landing page. 

Please add "Roadmap" under the **Follow** category. 

Link to the roadmap: https://github.com/orgs/trezor/projects/28?fullscreen=true

<img width="377" alt="Screenshot 2020-10-30 at 00 41 35" src="https://user-images.githubusercontent.com/29627086/97643741-d34df080-1a48-11eb-8bfb-2268eff30221.png">

**Comment by wendys-cats** [comment]
**QA OK**

NixOS + Chromium 85
Suite web 39d1b9690756482310a3970de0d1a29b0d4d2e89
