### ISSUE TITLE
Add context notification to BCH accounts

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2812]
We need to inform the users about the upcoming hard fork on November 15. 

Copy (±): "Bitcoin Cash will undergo a contentious fork on the 15th of November 2020, which could cause a split in the network. Learn more {link to our blog}

**Comment by prusnak** [comment]
I'd like to put more emphasis on reading our detailed blogpost; maybe this will do?

**Bitcoin Cash will undergo a contentious fork on the 15th of November 2020, which could cause a split in the network.**
**Read <ins>our blogpost</ins> to understand the risks!**

**Comment by wendys-cats** [comment]
@matejzak @prusnak so we tell the user to learn more in out blogPOST about it, but the link is only a general one to our BLOG? Shouldn´t there be either "read our blog" (to reflect the link) or link directly to said blogpost?

**Comment by bosomt** [comment]
**QA NOK**

When i click learn more im redirected to https://blog.trezor.io/ and not to https://blog.trezor.io/what-trezor-users-need-to-know-about-the-bitcoin-cash-fork-a21ceafdc03e

![image](https://user-images.githubusercontent.com/31506317/98207492-0a863b00-1f3c-11eb-9e82-17c6afd403b0.png)


Nixos 
Suite app commit 39d1b9690756482310a3970de0d1a29b0d4d2e89
Device mdoel One FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,

**Comment by prusnak** [comment]
This needs to be merged first to include the correct link https://github.com/trezor/trezor-suite/pull/2883

**Comment by tsusanka** [comment]
Done. Will be moved to staging after the CI passes (~30 minutes).

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefix 82
Suite web commit 513631a9fa62c438e60397a9942b04275bcd621a
Device model One FW 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
