### ISSUE TITLE
Fw update - privacy badger

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#2814]
Investigate.

**Comment by mroz22** [comment]
@robertbrada let's do this together. First good issue start with trezor-connect.

**Comment by mroz22** [comment]
@robertbrada was unable to simulate this. Original issue was that @szymonlesisz reported that privacy badger extension somehow blocked downloading of fw update binary which resulted into a silent failure of  update process without any notification. 

robert did some experiments and it either did not happen on his machine, or when he forced download in connect to fail, it was displayed correctly

![image](https://user-images.githubusercontent.com/30367552/102350591-6f09d080-3fa5-11eb-947b-a03327e5b382.png)

I am closing for now. Maybe @trezor/qa will be able to reproduce?

**Comment by bosomt** [comment]
**QA OK**

I was not able to reproduce it. Of course I can try different setup if you want to.
But I never experienced any problem with suite and privacy badger.

see video: https://www.youtube.com/watch?v=iwfV-g1fn6Q&feature=youtu.be

Nixos + Chromium 87
Privacy Badger + UBlock enabled 
Suite suite.trezor.io commit be4e3a36f7dbe15b2b203f66de11edc50a6665b8
Device public 1.9.2 > 1.9.3

**Comment by bosomt** [comment]
**QA OK**

retested in Firefox

Nixos + Firefox 82.0.3 (64-bit)
Suite web commit e771fd3c9b850f781e06f03072b3be55b881dcb9
Device public 1.9.2 > 1.9.3
