### ISSUE TITLE
Tor design

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2818]
Navigation: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f6b0073aa3cbd1a4cd1a5af)

- Let's have the Tor icon present at all times. Active state with the green check. Inactive state without. 
- Tooltip on hover. The only copy change is "inactive" or "active" base on the state.

Settings: [Zeplin ](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f9ada84ded3b42328e3152d) 

- Location: Settings › General › Privacy _(New category)_ 

<img width="1138" alt="Screenshot 2020-10-30 at 12 13 46" src="https://user-images.githubusercontent.com/29627086/97699215-0a082300-1aaa-11eb-8810-613658ea88c5.png">

**Comment by tomexx** [comment]
I tried to make it close to the design, it's pushed to Raf's Tor PR https://github.com/trezor/trezor-suite/pull/2576

@matejzak Please later specify texts for Tor settings, there are dummy texts for now. Thx

**Comment by glacierbits** [comment]
@keraf Can you please add description for Tor Settings? I think you are the best candidate to nail it..

**Comment by wendys-cats** [comment]
**QA OK**

**OS** Windows 10 home
**Suite** APP 20.11.1 11888946531d3bf641d83bdbfddae8e0143b0738
**Device** TT 2.3.4
