### ISSUE TITLE
Update BCH fork blog link when available

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2828]
Cont of https://github.com/trezor/trezor-suite/pull/2819

**Comment by tsusanka** [comment]
The blog post should go live at tomorrow at 18:00ish. I'll post it here then.

**Comment by tsusanka** [comment]
Published: https://blog.trezor.io/what-trezor-users-need-to-know-about-the-bitcoin-cash-fork-a21ceafdc03e

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82
Suite web commit 513631a9fa62c438e60397a9942b04275bcd621a
Device model One fw 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
