### ISSUE TITLE
Storybook 5 update styles

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#283]
https://github.com/trezor/trezor-ui-components/blob/3d797e16ba2cbea80539fa34096ad8416e7ca236/.storybook/config.js
probably can be copied from old PR
https://github.com/trezor/trezor-ui-components/pull/79/files

**Comment by vladimirvolek** [comment]
![image](https://user-images.githubusercontent.com/3112191/61535333-4f7a1b80-aa32-11e9-9ebf-9806f31c34fc.png)
