### ISSUE TITLE
Invity: DBObjectSore error when buying

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#2832]
**Info:**
 - OS: Ubuntu 20.04
 - Browser: Desktop (dev)
 - Wallet Version: develop / a5b13d5d92e15f9ee9c1af1b117804cd671c248b 
 - Firmware Version: 2.3.4
 
**Describe the bug**
An error is thrown when trying to buy coins via Invity.

**Steps to reproduce:**
1. Go to accounts / Bitcoin
2. Buy 10000 CZK
3. Proceed with one of the offers
4. Validate the address on the device
5. Observe

**Expected result:**
No error :slightly_smiling_face: 

**Actual result:**
Error :slightly_frowning_face: 

**Screenshots:**
![image](https://user-images.githubusercontent.com/30026749/97879349-2ca37180-1d20-11eb-93c2-5dd0bb12c9ab.png)

**Note(s):**

**Comment by vladimirvolek** [comment]
@keraf I cannot reproduce this :( Can you please try to delete your storage and try again? Thanks

**Comment by keraf** [comment]
Wasn't able to reproduce it again. Closing for now, re-opening if it happens again.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox Browser 82
Suite web dev master commit 374d027
Device model T fw 2.3.4 commit 50854b921
