### ISSUE TITLE
Suite allows TT to load 24 word seed when creating a new wallet

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2833]
**Info:**
 - OS: NixOS 
 - Browser: Chromium 85
 - Wallet Version: web develop branch, commit f06aff6
 - Device TT 2.3.3 public AND T1 1.9.3 public  
 
**Describe the bug**
When Suite has a remembered T1 device that has been wiped, it can be used to trick Suite into loading 24 word seed into a TT device. This bug relies on user reconnecting TT device during the FW update part.
Important to note: TT needs to activate the "FW update" part of Onboarding, so it cannot have the newest FW.

**Steps to reproduce:**
1. Connect T1 and remember this device
2. Wipe T1 and disconnect
3. Connect TT and wipe it
4. Create new wallet on TT
5. During "FW update" part, disconnect and reconnect TT device (NOT in BL) and continue
6. Note how Onboarding does not offer user the choice between Standard seed and Shamir seed
6. Enjoy 24 word seed

**Expected result:**
Suite will not change the course of Onboarding during a disconnet/reconnect in ANY part of Onboarding (in this instance, Onboarding willl not offer user the usual choice between Standard seed and Shamir seed that is particular to TT Onboarding).

**Actual result:**
After the reconnect (in step 5), Suite will change the Onboarding proccess from that matching a connected TT (containing Standard and Shamir seed choice) to a T1 (straight up just "Create wallet"). 

**video:**
https://drive.google.com/file/d/1C8kyOUPHAdbHEMYYCh2f_HZAyHmW4dxI/view
![photo_2020-11-02_16-37-28](https://user-images.githubusercontent.com/58593111/97887158-cf142280-1d29-11eb-8963-1736d2093dfb.jpg)

**Comment by STew790** [comment]
Could not replicate this. Suite still wants you to connect the device in BL mode and does not let you any further.

Solved probably because of new onboarding.
