### ISSUE TITLE
Device Dis/connected: Switch Wallet Modal

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2835]
Continuing from #2558 

The device connection status in the "Switch wallet modal". 

Feel free to use the **red color** for the `DISCONNECTED` status as you rightly did in the navigation component. 

It wasn't designed so, but it is consistent with the red dot in the navigation when device disconnected.

**Comment by wendys-cats** [comment]
**QA OK**

**Suite** web develop ac55c97a1e017226e61e340d93b2e7e26b00a0f3
**Browser** Chromium Version 86.0.4240.111 (Official Build) (64-bit)
**System** NixOS 21.03
**Device** TT 2.3.4 public + T1 1.9.3 public

![image](https://user-images.githubusercontent.com/58593111/100368072-699f1300-3003-11eb-9c10-d6f493ea3916.png)
