### ISSUE TITLE
Requests being blocked in the desktop version

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2836]
**Info:**
 - OS: NixOS
 - Browser: desktop
 - Wallet Version: 89fbdfc285f5d1506fa922b336349e5fe8ae3e1a
 - Firmware Version: emulator master 89fbdfc285f5d1506fa922b336349e5fe8ae3e1a
 
**Describe the bug**
On launch I get a few warnings about requests being blocked. I have tried to clear cache but it went bananas then completely.

**Screenshots:**
After launch:

![image](https://user-images.githubusercontent.com/1835345/97909452-8881f080-1d48-11eb-8ddd-9c9c0217a027.png)

Later after I have deleted cache (or at least I hope so).

![image](https://user-images.githubusercontent.com/1835345/97909545-b109ea80-1d48-11eb-94b2-b242a223bd7b.png)

**Note(s):**
Log from cmd line:
```
Trezor-Suite-20.11.0-linux.AppImage installed in /home/tsusanka//.cache/appimage-run/4ce0485c57d644ce349f49c3818b1343212e47c69599ec34cdeff1fb0415ef0b
Checking for update
Update for version 20.11.0 is not available (latest version: 20.10.1, downgrade is disallowed).
[Warning] Domain 'api.github.com' was blocked.
[Warning] Domain 'o117836.ingest.sentry.io' was blocked.
```

**Comment by prusnak** [comment]
I guess we will need to add `api.github.com` and `ingest.sentry.io` to `allowedDomains` here for the time being:

https://github.com/trezor/trezor-suite/blob/8e6ef2b6c60933fd66cb8bc327c640efd037328c/packages/suite-desktop/src-electron/config.ts#L27

**Comment by bosomt** [comment]
**QA OK**

Nixos
Suite app commit 39d1b9690756482310a3970de0d1a29b0d4d2e89
Device model One firmware 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
