### ISSUE TITLE
Multilingual interface 🌎

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2838]
Let's translate Trezor Suite to the most popular languages. Planned:

- [x] Spanish
- [ ] Portuguese 
- [ ] German
- [ ] Russian 
- [ ] Mandarin 
- [x] Czech
- [ ] Dutch

**Comment by FrankyFFV** [comment]
@matejzak How can I join to translate?

**Comment by FrankyFFV** [comment]
@matejzak How can I join to translate?

**Comment by glacierbits** [comment]
@FrankyFFV We are yet to set up to official process (review etc.) for external contribution when it comes to translations. Once done, we will announce it to the community. What language are you interested in? Thanks!

**Comment by FrankyFFV** [comment]
> @FrankyFFV We are yet to set up to official process (review etc.) for external contribution when it comes to translations. Once done, we will announce it to the community. What language are you interested in? Thanks!

Perfect! I’m translator of anothers projects such as Brave Browser & ProtonMail. I’m interested in Spanish.

**Comment by PBWrzal** [comment]
I can help with **German**, **Indonesian** and **Javanese**.

**Comment by PBWrzal** [comment]
@matejzak I can help with German, Indonesian and Javanese.

**Comment by PBWrzal** [comment]
@matejzak I can help with **German**, **Indonesian** and **Javanese**.

**Comment by LDS90** [comment]
Hi @matejzak, Perhaps I could help with adding Dutch to the list. Feel free to contact me!

**Comment by glacierbits** [comment]
@LDS90 @PBWrzal @FrankyFFV 

Many thanks guys for your proactivity in helping us to make Trezor Suite a truly global product. 🌍 

Our IT project manager @alex-jerechinsky has kicked-off the translation process, and will reach out to you with the contribution manual. 

Once again, many thanks, your help will be very much appreciated! 🙏🏽

**Comment by FrankyFFV** [comment]
> @LDS90 @PBWrzal @FrankyFFV
> 
> Many thanks guys for your proactivity in helping us to make Trezor Suite a truly global product. 🌍
> 
> Our IT project manager @alex-jerechinsky has kicked-off the translation process, and will reach out to you with the contribution manual.
> 
> Once again, many thanks, your help will be very much appreciated! 🙏🏽

Roger! 😬

**Comment by jerechinsky** [comment]
@FrankyFFV @PBWrzal @LDS90 

Could you please shoot me a quick email at alexandr.jerechinsky@satoshilabs.com so I can onboard you into our translation project? 🙂

Thank you!

**Comment by PBWrzal** [comment]
> @FrankyFFV @PBWrzal @LDS90
> 
> Could you please shoot me a quick email at [alexandr.jerechinsky@satoshilabs.com](mailto:alexandr.jerechinsky@satoshilabs.com) so I can onboard you into our translation project? 🙂
> 
> Thank you!

Just send you the E-Mail for German, New Javanese and Indonesian (Bahasa Indonesia). ;)

**Comment by danielkp1234** [comment]
If needed i would like to help translate Trezor Suite to Danish :)

**Comment by AsksTooManyQuestions** [comment]
Hey @matejzak , please let me know if a Portuguese translator is needed. I can more than certainly help with that.

**Comment by melroy89** [comment]
I also could help with Dutch lang.

**Comment by ghost** [comment]
Please translate into Russian

**Comment by Tongchen-Wang** [comment]
Please translate into Mandarin

**Comment by lightdarkcode** [comment]
pls translate into German
