### ISSUE TITLE
suite-desktop: "Clear storage and reload" button on error page does not work

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#2839]
When an error occurs, the button "Clear storage and reload" does not do anything on suite-desktop. 
![2020-11-02_21-45](https://user-images.githubusercontent.com/30026749/97917595-faf8cd80-1d54-11eb-86a9-2ba07ba37a99.png)

**Comment by wendys-cats** [comment]
**QA OK**

Encountered issues and errors today, clear cache+reload definitely works ([here](https://github.com/trezor/trezor-suite/issues/2869))

**OS** Windows 10 home
**Suite** APP 20.11.1 11888946531d3bf641d83bdbfddae8e0143b0738
**Device** 2.3.4 public 50854b921
