### ISSUE TITLE
Unwanted scrolling of Suite in background

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2841]
**Info:**
 - OS: Nixos 
 - Browser: Firefox , version 82.0 (64-bit)
 - Wallet Version: web, commit 11ef2d377f2131ca74ddc6c7979e013082b9b061
 - Firmware Version: 2.3.2 model t  , revision **63ebb8ccb**
 
**Describe the bug**
I noticed unwanted scrolling of Suite in background of modal in Firefox.
Chromium works fine / see video from chromium/

**Steps to reproduce:**
1. Load suite in Firefox
2. Open firmware update modal
3. Scroll up and down and observe

**Expected result:**
Scrolling only scrolls opened modal.

**Actual result:**
Scrolling moves Suite background when end of modal is reached.

**Screenshots:**

`Firefox`
![Peek 2020-11-03 09-04](https://user-images.githubusercontent.com/31506317/97962202-f19f4d80-1db4-11eb-9d5a-54e1786de6a8.gif)

`Chromium`

https://www.youtube.com/watch?v=E4sf-BlXhcA&feature=youtu.be

**Comment by bosomt** [comment]
is it possible that it's related to this bug ? 
https://github.com/trezor/trezor-suite/issues/2165

**Comment by slowbackspace** [comment]
@bosomt I think it's different bug (the linked "bug" is on purpose on our side since firefox doesn't support the blur effect), but I definitely check it. A lot of weird things can happen in css world 😁 

So this is only happening on firefox right?

**Comment by bosomt** [comment]
Firefox only :) :fox_face:

**Comment by bosomt** [comment]
**QA OK**

Firefox 82 + Nixos
Suite web dev master commit 9a39d54d228aa9421939117d597bb5f61779a97d
Device model TT FW 2.3.4 commit 50854b921
