### ISSUE TITLE
Tor: Toggle behaviour & presence

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2842]
Browser: Chrome
Version: 8f4d1eedd6eb7648b17853a9a780a0688c0370e6 

- Tor settings should be available only in the desktop version 
- Strange toggle behaviour

![ezgif com-gif-maker](https://user-images.githubusercontent.com/29627086/97963876-1f39c600-1db8-11eb-8b85-9fe8b162bfdc.gif)

**Comment by wendys-cats** [comment]
@matejzak what exactly is the problem here? That tor should be only for desktop versions, or that the toggle works weirdly on app version?

**Comment by tsusanka** [comment]
@wendys-cats both :).

A) Tor should be only in the desktop apps.
B) The toggl did not toggl :). Since it should not be on a web we care only about the desktop.

**Comment by wendys-cats** [comment]
@tsusanka so two separate issues, oki. Threw me off that you want to check toggl animation where it is not even supposed to be :D

**Comment by tsusanka** [comment]
@wendys-cats please test and close (and move to Approved) if it works :). Or is there any action we should take?

**Comment by wendys-cats** [comment]
**QA OK**

**OS** Windows 10 home
**Suite** APP 20.12.0 491f31e
**Device** TT 2.3.4

Chromium on Nixos does not show TOR. TOR toggl in WinAPP does toggle correctly.
