### ISSUE TITLE
Discreet mode menu

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2843]
Browser: Chrome
Version: 8f4d1eedd6eb7648b17853a9a780a0688c0370e6

- [x]  The line above the discreet mode icon should not be present.

- [x]  Icon jumps when used for the first time during the given session 

<img width="217" alt="Screenshot 2020-11-03 at 09 40 17" src="https://user-images.githubusercontent.com/29627086/97964166-996a4a80-1db8-11eb-9ee5-8f2982e7c7d5.png"> 

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/29627086/97964524-31683400-1db9-11eb-95e4-d8e282ee8c3a.gif)

**Comment by wendys-cats** [comment]
**QA OK**

OS NixOS + Chromium 85
Suite web 20.11.1 513631a9fa62c438e60397a9942b04275bcd621a
Device TT 2.3.4 public 

**note** @matejzak  WHY is TOR in the name?

**Comment by sorooris** [comment]
@matejzak pls how is the discreet mode icon in any way related to Tor?

**Comment by glacierbits** [comment]
They are both nested in the same "privacy box" navigation in the desktop app. The line above the icon here looked like a residue of that design in the browser version (bug).

**Comment by tsusanka** [comment]
Yeah I think the idea is that they are both connected to privacy. @sorooris should we close?

**Comment by sorooris** [comment]
alright, let's close.
