### ISSUE TITLE
Tor: Navbar color

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2844]
When Tor enabled, navbar should keep it's default color. 

While Ondra (the designer) considered the option to turn the navbar purple, it's been decided it's too "aggressive" approach and the colour itself could be confusing for users who are not particularly familiar with Tor Project branding.

**Comment by wendys-cats** [comment]
@matejzak does this apply to Suite APP? Or web version?

**Comment by glacierbits** [comment]
Desktop app only

**Comment by tsusanka** [comment]
@wendys-cats please test and close (and move to Approved ) if it works :). Or is there any action we should take?

**Comment by wendys-cats** [comment]
@tsusanka thanks for the reminder!

**QA OK**

**OS** Windows 10 home
**Suite** APP 20.12.0 491f31ee27067b57e273e79cd1a6e1cad91459bb 
**Device** TT 2.3.4

Did not encounter any colour changes to purple anywhere in the APP.
