### ISSUE TITLE
Unconfirmed transaction caching issue

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2848]
**Info:**
 - OS: Nixos
 - Browser: Chromium + Firefox , latest versions
 - Wallet Version: web, commit c436bacae06bb4a2dd42af37edb7861b41f66b35
 - Suite Version: web, commit 99959260d5639480dfb11e53a4f2ab1d789b0e7b
 - Firmware Version: 2.3.3 model T, revision 0d5f00668
 
**Describe the bug**
Looks like problem with unconfirmed transactions caching. When you load same wallet in wallet and in suite you sometimes see different amount of unconfirmed transactions. Sometimes you don't see transaction in transactions list till it's not confirmed, even you see it in activities/notifications. It's not just BTC transactions issue

**Steps to reproduce:**
1. Load same wallet with unconfirmed transactions in wallet and in suite
2. Compare them
3. Sometimes suite is missing unconfirmed transactions

**Expected result:**
You see all unconfirmed transactions

**Actual result:**
Sometimes you don't see transaction till it's confirmed

**Screenshots:**

![image (3)](https://user-images.githubusercontent.com/31506317/97970091-4943b600-1dc1-11eb-8aa3-7ac0542b7791.png)

![image (4)](https://user-images.githubusercontent.com/31506317/97970116-519bf100-1dc1-11eb-9a22-ea16e0ba53e1.png)

**Comment by slowbackspace** [comment]
it almost sounds like we are not getting or ignoring some of blockchain-notification events that are sent from blockbook. 🤔 
(or maybe some weird memoization side-effect)

**Comment by szymonlesisz** [comment]
nope, if you forget the device and do the discovery again this pending tx is shown properly and then it's gone again (see slack thread)
its not about notificiation bc. this tx is "old" from the BB point of view, notification is emitted 1 time only when tx appears in mempool
my guess is that this pending transaction is not properly sorted and displayed elsewhere (there was already issue with that ifaik, that pending tx was displayed somewhere in the middle)

**Comment by slowbackspace** [comment]
hopefully fixed by https://github.com/trezor/trezor-suite/pull/2870,
pls reopen if the issue persist

**Comment by bosomt** [comment]
**QA OK**

i was noe able to reproduce it anymore

Nixos + Firefox + Suite app + wallet.trezor.io
Suite commit a7554fff457b49cd4898912e74e3063f3e8244f8
Device mdoel One fw 2.3.2 commit 63ebb8ccb
