### ISSUE TITLE
Sign & verify 🔏

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2854]
**Design:** [Zeplin](https://zpl.io/aMrekQz)

Sign and verify messages and addresses.

**Comment by tsusanka** [comment]
We should also discuss what the limits should be (what is the longest data T1/TT can take in). cc @matejcik

**Comment by HeroHann** [comment]
Which Coins will be supported? I feel BTC LtC and ETH are must haves…

**Comment by matejcik** [comment]
Current T1 (legacy) code supports maximum message size of 1024 bytes.

There is no explicit limit on TT. Practically you can rely on messages of up to ~8000 bytes working fine (to be more precise, 8192 total for the whole protobuf message).
Going forward, we are considering setting a hard limit of 4096 bytes for a single protobuf message. This is not implemented yet however.

**Comment by melroy89** [comment]
Could I be invited to the Zeplin project (username: danger89)? Thanks! So I'm able to peer-review the designs.

**Comment by bosomt** [comment]
@marekrjpolak as soon i leave `Sign message` page /usually to `Verify message` page/ all fields are cleared and i'm not able to copy them to verify message. 

Of course i can copy them to text editor but it's different design compared to MyTrezor wallet and Trezor Next wallet.

Is that expected or should i send issue ?


++ edit:

any idea why `x Clear all` button is always present in `Sign` section but in `Verify` section it only appears after you enter value to any field.

**Comment by marekrjpolak** [comment]
> Is that expected or should i send issue ?

I presumed that you usually don't need to verify your own signed message. If you want, the best way is to use the Copy button which appears after the signing and copies whole signed message (hopefully in widely used format) to clipboard: 
![image](https://user-images.githubusercontent.com/26326960/135982944-11069d5b-bdcc-4f27-84c4-4d00a89ac66b.png)

> any idea why `x Clear all` button is always present in `Sign` section but in `Verify` section it only appears after you enter value to any field.

Clear button should be visible under the same conditions in both cases. But you probably tested it on Ethereum account where the signing address is always present (because it is the only one) so the clear button is always visible even if it can't actually clear the address. Probably not a big issue, but I could fix it.

**Comment by marekrjpolak** [comment]
I know it's kind of late, but I should still write a little overview of Sign&Verify functionality.

1. Sign&Verify is enabled for most Bitcoin-like and Ethereum-like coins and accessible through … button in Account menu. ![image](https://user-images.githubusercontent.com/26326960/135984614-228d0da0-67d4-4d75-9d94-a779506a399f.png)
2. Both forms:
	1. You can write any message up to 255 characters in the Message field.
	2. When you turn on the 'Hex format' switch, message is handled differently in Trezor so you can use only 0-9a-f characters, optionally prepended with 0x.
	3. Empty message is valid only as non-hex.
	4. When any value in the form is non-empty, 'Clear all' button for resetting it appears.
3. Sign form:
    1. For Bitcoin-like coins, you can choose signing address from all of your used receive addresses plus first fresh address. In addition, if you reveal more unused addresses in Receive form and immediately go to Sign&Verify, you can choose them as well.
    2. For Ethereum-like coins, the only relevant address is prefilled and you shouldn't be able to change it.
	3. Addresses in combobox are hidden in the same way as in Receive form. After selecting, you could check them with 'Reveal address (eye)' button or let them unchecked.
	4. You could find addresses in combobox also by writing them.
	5. The signature is filled in after you use the Sign button and confirm the message on Trezor.
	6. When the signature is filled in, you can export whole signed message by 'Copy' button next to 'Clear all' button.
	7. When you change any field after the signing, the signature and the 'Copy' button should disappear.
4. Verify form:
	1. Address and Signature fields are required.
	2. You can write any address, but it's validated according to selected coin.
	3. If you use Verify button
	    1. and the signature is invalid, 'Invalid signature' notification appears.
	    2. and the signature is valid, you must confirm both address and message on your device, then 'Verification successful' notification appears.

**Comment by marekrjpolak** [comment]
Small fixes:
> any idea why `x Clear all` button is always present in `Sign` section but in `Verify` section it only appears after you enter value to any field.
- `Clear all` button is now hidden on Ethereum signing page as well, until you change something.
- `Copy` button is now visible after signing even if message was empty.
- Action buttons (Clear & Copy) are now without icons as in Zeplin design.

**Comment by bosomt** [comment]
@marekrjpolak amazing, thank you looks good for me now 
/sorry i haven't noted `copy` button during my first test session ;)/

**Comment by bosomt** [comment]
@marekrjpolak 

it's common behaviour of suite that buttons are not active/green when you are not able to perform action /fields are not filled in/

otherwise overall Sign&Verify functionality is great

<img width="734" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136328258-c8e22c24-8830-4bf8-958b-a7367cffceb7.png">

<img width="731" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136328281-e0d463b7-89dc-487e-9212-955d2286b123.png">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.10.1 (30698b091e0eff94a2adddf92b15998092d7a3c9)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728

**Comment by STew790** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.10.1 (aa3adfa347d0416f970a7fae720d3350f29f8916)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.2 regular
