### ISSUE TITLE
Consider removing custom navigation bar on linux

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2856]
It just seems very un-linuxy thing to do and I personally find it a bit ugly. I don't want apps to mess with my OS (gnome) setup.

Let's see what others think @prusnak @keraf.

**Comment by prusnak** [comment]
Since Matej indicated we'd like to add more active elements in the top bar (such as search) I think this should stay.

**Comment by tsusanka** [comment]
Search bar here :scream:?

![image](https://user-images.githubusercontent.com/1835345/98109251-8da48400-1e9d-11eb-9b7f-a4a8ef4d64ac.png)

Or are we talking about smth else?

**Comment by glacierbits** [comment]
A lot of different options to consider (e.g. search, commands, privacy settings, breadcrumb etc.). The idea is make use of the space efficiently and take advantage of the desktop "nativity". 

Slack: 
<img width="1516" alt="Screenshot 2020-11-04 at 13 13 26" src="https://user-images.githubusercontent.com/29627086/98111372-c8f48200-1ea0-11eb-8059-c4ffa5f39471.png">

Notion:
<img width="1641" alt="Screenshot 2020-11-04 at 13 14 21" src="https://user-images.githubusercontent.com/29627086/98111380-cd209f80-1ea0-11eb-9490-7aee76b6e387.png">

**Comment by tsusanka** [comment]
JFYI this is what Slack looks like at Linux with Gnome3

![image](https://user-images.githubusercontent.com/1835345/98112181-09083480-1ea2-11eb-8829-b4b6117daaaa.png)

**Comment by tsusanka** [comment]
I believe there are no clear next steps in this issue. Product should decide what the nav bar looks like not me, so I am closing.
