### ISSUE TITLE
XRP history not available

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2859]
Unable to load transaction history (for the past ± 8 hours).

<img width="1206" alt="Screenshot 2020-11-03 at 15 52 05" src="https://user-images.githubusercontent.com/29627086/98000199-883b3100-1dec-11eb-8c13-f5310e43a267.png">

**Comment by slowbackspace** [comment]
try to send fresh tx, if it'll appear in txs list then it is as I said on slack and there is nothing I can do about it.
Well even if it won't appear, it is completely out of scope 😁

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox Browser 82
Suite web dev master commit 374d027cdf94370dc09fc17c448cdfd7a3543b8c
Device model T fw 2.3.4 commit 50854b921
