### ISSUE TITLE
Dropbox API is blocked

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2862]
**Describe the bug**

**Info:**
 - Suite Version: app, commit 8d81bfdd64d716bd905d599e83113aff7b4f12c4
 - OS: Windows 10 
 - Firmware Version: 2.3.4 model T

**Steps to reproduce:**
1. Start latest version of Suite
2. Try to enable labeling when asked
3. See error at end of labeling flow

**Expected result:**
Suite has access to Dropbox API

**Actual result:**
Labeling is not working

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/98012581-8e83da00-1df9-11eb-8e75-13843443db7d.png)
![image](https://user-images.githubusercontent.com/31506317/98012598-93e12480-1df9-11eb-9127-53a1a8b910fe.png)

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezor-suite/commit/8e1d1794dfac8b372e22991f65a6b182dc002f81 

and cherry-picked to `release/2020-11` in 53e0e15a3652c0ee48b4717846305be57404c6a7

**Comment by bosomt** [comment]
**QA OK**

Nixos
Suite app commit 39d1b9690756482310a3970de0d1a29b0d4d2e89
Device model One firmware 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
