### ISSUE TITLE
React-native builds

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2867]

**Comment by slowbackspace** [comment]
I think this could be closed as the builds (well at least android for now) are already working! 🙇 
(fixed by https://github.com/trezor/trezor-suite/pull/3190)

**Comment by bosomt** [comment]
**QA OK**

i was able to download, install and start app in my phone.

Huawei Andorid 9
Suite commit 9ae82af375cea195a84fec664b387c461b2df1ae
