### ISSUE TITLE
APP Windows suite app reporting an error (Loading takes too long) after launching

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2869]
**Describe the bug**
Suite app for Win10 reports an error after launching. Reloading the app results in the same error. Clearing cache and reloading the app results in part of Onboarding (the part where user does not need device to be unlocked) working and when trying to load Dashboard and accounts, suite app crashes on the same error (see screenshot below).

Message: "Error occured. It appears something is broken. You might let us know by sending report" and "Loading takes too long"

**Info:**
 - Suite Version: app commit 8d81bfdd (latest)
 - OS: Windows 10 home edition
 - Firmware Version: 2.3.4 , revision public 50854b921

**Steps to reproduce:**
1. download app and install
2. run the app

**Expected result:**
App will not crash.

**Actual result:**
App displays an error after launching.

**Screenshots:**
![photo_2020-11-04_11-54-20](https://user-images.githubusercontent.com/58593111/98102924-83ca5300-1e94-11eb-999e-d73a35546a21.jpg)

**Comment by tsusanka** [comment]
@wendys-cats will retest on 11888946

**Comment by wendys-cats** [comment]
@tsusanka still persists on build 1188894


![photo_2020-11-04_12-49-53](https://user-images.githubusercontent.com/58593111/98108479-4ec1fe80-1e9c-11eb-93c3-d10583accbde.jpg)

**Comment by tsusanka** [comment]
Ok :(. Not sure who should have a look then, maybe @keraf, @mroz22 or @szymonlesisz?

**Comment by prusnak** [comment]
This means we've exceeded our Sentry plan - can you please check this?

**Comment by slowbackspace** [comment]
@prusnak that might be true, but I don't think that's the reason app crashes in the first place. Sentry report is sent only AFTER the crash. (suite.trezor.io works just fine)

https://github.com/trezor/trezor-suite/commit/11888946531d3bf641d83bdbfddae8e0143b0738 also works fine for me on macos

**Comment by szymonlesisz** [comment]
i've successfully run it on some archaic win10 setup from the bottom of my drawer (with trezord 2.0.12!) and it works, strange.
However i have found another problem but idk if its windows related so i'm creating [separated issue](https://github.com/trezor/trezor-suite/issues/2875)

**Comment by szymonlesisz** [comment]
@wendys-cats could you try to uninstall the app and remove all content from
~`C:/Users/[your-user]/AppData/Local/Programs/Trezor Suite`~ and install again? idk what is the reason

**Comment by slowbackspace** [comment]
I checked with @bosomt, he was also able to launch the app just fine on his windows machine. So it really should be something specific to this one machine. As @szymonlesisz said, removing all caches is a good start, but please backup the folder first so we may troubleshoot this later! @wendys-cats

**Comment by wendys-cats** [comment]
@szymonlesisz it is actually C:/Users/[your-user]/AppData/Local/Programs/@trezorsuite-desktop/Trezor Suite . 

Removing all caches did not help, error still occured (tested 1188894).

**Comment by wendys-cats** [comment]
@szymonlesisz also tried older APPs from last month and everything is working as expected. 
99959260d5639480dfb11e53a4f2ab1d789b0e7b commit hash version 20.10.1
OS specification Windows 10 Home 19041.572

After removing cache from AppData/Local/Programs AND AppData/Local/Roaming, newest build (commit 11888946531d3bf641d83bdbfddae8e0143b0738) IS WORKING! (@slowbackspace and me have no idea what happened)

**Comment by szymonlesisz** [comment]
yeah, i was pointing to invalid directory :)

it might be related to recent changes (tor/sub-process management) 

i would definitely focus on that issue! it might affect users after update as well

could you try to simulate this process again?
- uninstall current app, clear cache
- install previous (20.10.1) 
- install current without clearing cache

**Comment by wendys-cats** [comment]
**1.** Installed 20.10.1 public commit hash 9995926 
**2.** cleared cache from appData/Local/Roaming 
**3.** installed build commit hash commit 1188894

eveything is working

**Comment by tsusanka** [comment]
So this seems to work? Closing?

**Comment by wendys-cats** [comment]
@tsusanka yes please, close this issue.
