### ISSUE TITLE
A dot at the beginning of "Reconnecting in..."

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#2871]
**Describe the bug**
A wild dot appears.

**Info:**
 - Suite Version: app, acde0380f64040f1567f481f92aa4f5f5aba8b2a 
 - OS: ubuntu 

**Steps to reproduce:**
1. Somehow make app fail to connect to backends
1. See result on accounts page

**Expected result:**
No dot at the beginning of the text

**Actual result:**
There is a dot. 

**Screenshots:**
insert here
![image](https://user-images.githubusercontent.com/30367552/98105491-5f707580-1e98-11eb-9ed1-ca644e30b2f5.png)

**Comment by samay-v** [comment]
Hey, I'd like to fix this 😀 
The dot seems to come from [here](https://github.com/trezor/trezor-suite/blob/f705225ba8195bc0724d719dad4227ea56769eb2/packages/suite/src/support/messages.ts#L613).
I'd also fix it in the [translations/en.json](https://github.com/trezor/trezor-suite/blob/f705225ba8195bc0724d719dad4227ea56769eb2/packages/suite-data/files/translations/en.json#L138) just in case

**Comment by prusnak** [comment]
Great @samay-v - will you send a pull request with the fix?
