### ISSUE TITLE
content.dropboxapi.com domain blocked in Suite app

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2873]
**Describe the bug**
content.dropboxapi.com is still blocked in Suite Linux App

**Info:**
 - Suite Version: app, commit  11888946531d3bf641d83bdbfddae8e0143b0738
 - OS: Nixos
 - Firmware Version: 1.9.3 model One , revision  0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,

**Steps to reproduce:**
1. Start Suite app
2. Enable Labeling
3. Select Dropbox and login via web interface

**Expected result:**
You are able to use Dropbox to save your labels

**Actual result:**
You are not able to use Dropbox to save your labels in Suite app.

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/98109659-34892000-1e9e-11eb-8acf-7ca409f873c4.png)

![image](https://user-images.githubusercontent.com/31506317/98109690-423ea580-1e9e-11eb-8d16-b7c5a102d3d7.png)

![image](https://user-images.githubusercontent.com/31506317/98109754-613d3780-1e9e-11eb-81a8-02bd18ae90cb.png)

**Comment by keraf** [comment]
Fixed in 84e3918

**Comment by prusnak** [comment]
Cherry picked to release branch in 00cc44a9c26801a86a688f5f5dbea3aee2ba4b17

**Comment by prusnak** [comment]
I added `notify.dropboxapi.com` in aac3e96d3e4b4e9c454820a404a6f6af15b47d4b (cherry-picked in 39d1b9690756482310a3970de0d1a29b0d4d2e89)

**Comment by bosomt** [comment]
**QA OK**

Nixos
Suite app commit 39d1b9690756482310a3970de0d1a29b0d4d2e89
Device model One firmware 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
