### ISSUE TITLE
Desktop app: electron window multiplication on macos

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#2874]
**Describe the bug**
desktop app creates new window on every focus change

**Info:**
 - Suite Version: desktop app, 05ab25f 
 - OS: mac
 - Firmware Version: any

**Steps to reproduce:**
1. install desktop app
2. click somewhere outside (or [tab] to different window)
3. click on Trezor suite icon in dock

**Expected result:**
electron app should have only 1 window

**Actual result:**
got multiple windows, when i close one of them i get electron runtime error (see screenshot)

**Screenshots:**
fist focus (2 windows)
![Screenshot 2020-11-04 at 14 48 55](https://user-images.githubusercontent.com/3435913/98120065-c9474a00-1ead-11eb-88d3-52929f68082c.png)

second focus (3 widows)
![Screenshot 2020-11-04 at 14 50 50](https://user-images.githubusercontent.com/3435913/98120169-eb40cc80-1ead-11eb-8c5c-fe11ed8e5f43.png)

error after closing
![Screenshot 2020-11-04 at 14 46 33](https://user-images.githubusercontent.com/3435913/98120228-fac01580-1ead-11eb-9051-185120aa2f1e.png)

**Note(s):**

**Comment by sorooris** [comment]
**QA OK**

Couldn't replicate issue.

Suite version: app 513631a9fa62c438e60397a9942b04275bcd621a
OS: macOS Catalina 10.15.7
Device: 2.3.4 50854b921
