### ISSUE TITLE
Desktop app: update bridge forever loading

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#2875]
**Describe the bug**
I've just run desktop app on some old setup which has trezor bridge v 2.0.12 installed (quite outdated) 
desktop app notifies me about outdated bridge (correctly) but when i click on "update bridge" button it ends up with "forever loading" state

**Info:**
 - Suite Version: desktop app
 - OS: windows 10
 - Installed Bridge Version: 2.0.12 (outdated)

**Expected result:**
Not sure :) should i download new bridge and install it, or remove pre-installed bridge and start using bundled one?

**Screenshots:**

![forever-loading](https://user-images.githubusercontent.com/3435913/98124274-42956b80-1eb3-11eb-98f2-ca7bb234171c.jpg)

**Comment by szymonlesisz** [comment]
similar loading is happening when i kill the `trezord.exe` process (pre-installed one)
the suite is trying to run bundled `trezord` (correctly) but for a while i see this "gathering information, please wait..." modal
Maybe desktop build should have additional modal/view with different wording, like "restarting bridge..."

**Comment by szymonlesisz** [comment]
and when i kill the `trezord` sub-process (bundled one) it end up in "forever gathering information"
so there should be definitely additional view with a button for restarting sub-process

**Comment by bosomt** [comment]
**QA OK**

Windows 10
Suite app commit b0dacc34e574235daa2427c08b8d2985baa2dc13
Device model T FW 2.3.4
