### ISSUE TITLE
Desktop app: missing app frame border on windows

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#2878]
**Describe the bug**
App border is completely missing

**Info:**
 - Suite Version: desktop app, 1188894
 - OS: Windows 10

**Expected result:**
Other applications got at least thin 1px around itself

**Screenshots:**
![missing-border](https://user-images.githubusercontent.com/3435913/98139793-e4718400-1ec4-11eb-87f8-f1187e2ced2b.jpg)

**Comment by bosomt** [comment]
**QA OK**

Suite Version: app, commit 78c9fd3
OS: Windows
Firmware Version: 1.9.3 model One commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,
