### ISSUE TITLE
Data: More items

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2882]
Overview & todos: [Notion](https://www.notion.so/satoshilabs/e19845789ccb47a0baf36d7f8463f196?v=16dd37b30ce549cc89ca41894e8dcd0b)

**Comment by bosomt** [comment]
@matejzak is there anything that can be tested on our side ?

**Comment by glacierbits** [comment]
Nothing to be tested here manually, moving to Approved.
