### ISSUE TITLE
Discreet mode: Accounts 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2886]
<img width="357" alt="Screenshot 2020-11-05 at 00 39 09" src="https://user-images.githubusercontent.com/29627086/98179568-549cfb80-1eff-11eb-9cfa-f5d899812601.png">

**Comment by tomexx** [comment]
I saw this issue in the list so I quickly fixed it in a similar manner as the previous discreet mode cut off issues.

**Comment by glacierbits** [comment]
Thanks!
