### ISSUE TITLE
New coin icons

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2888]
Please update the coin icons. The current set is a mix of styles and colors. 

Therefore we created this custom set instead: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/styleguide/components?cseid=5fa3cd3a61208235de302db6)

**Comment by bosomt** [comment]
**QA OK**

Firefox 82 + Nixos
Suite web dev master commit 9a39d54
Device model TT FW 2.3.4 commit 50854b921
