### ISSUE TITLE
Tor: Opening links

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#2892]
Currently we have a TrezorLink component that converts trezor.io links to .onion links if Tor is on. This behaviour is correct for the web as the user might want to open new links as onion links. On desktop however, the links open in the default browser that might not be configured for Tor as it is most likely that the user will have Tor configured for the app only (Tor being bundled with). We should therefore provide an option on desktop to open new links as .onion links and default to normal links.

**Comment by wendys-cats** [comment]
@keraf are the invity.io links also included in this issue, or is it out of scope?

**Comment by prusnak** [comment]
Right, only trezor.io links are available via trezorio.....onion. So invity.io is out of scope

**Comment by wendys-cats** [comment]
@prusnak tanks for aswer!

OK for Win10 app.

**Comment by bosomt** [comment]
**QA OK**

Windows 10
Suite app commit b0dacc3
Device model T FW 2.3.4
