### ISSUE TITLE
Wallet stuck on loading screen 

### ISSUE THREAD

**Issue by freakyleader** [trezor/trezor-suite#2897]
I have followed all instruction from trezor i.e. clear cache, different browsers, etc. 
Even when I click on the link trezor sent me to download newest version its also was stuck on the loading screen. Downloaded different versions from github and still stuck on loading screen. Tried app and get error message.

**Comment by prusnak** [comment]
Please post a screenshot

**Comment by freakyleader** [comment]
[
<img width="1671" alt="Screen Shot 2020-11-05 at 12 28 11 PM" src="https://user-images.githubusercontent.com/74014409/98275258-767b9a00-1f62-11eb-9dcc-4f36df3e9122.png">
](url)

**Comment by freakyleader** [comment]
<img width="1670" alt="Screen Shot 2020-11-05 at 12 29 53 PM" src="https://user-images.githubusercontent.com/74014409/98275472-a6c33880-1f62-11eb-985c-c48c24d7cd13.png">
