### ISSUE TITLE
Mistype on the firmware update screen

### ISSUE THREAD

**Issue by MatveiP** [trezor/trezor-suite#2898]
**Describe the bug**
Mistype on the firmware update screen in Suite (the one asking to reconnect the device). “It” instead of “In”.

**Info:**
 - Suite Version: app, commit (?)
 - OS: Mac OS

**Screenshots:**
![image](https://user-images.githubusercontent.com/50269230/98274347-5e2c6f00-1fa4-11eb-9164-64e835ca5bb3.png)

**Comment by bosomt** [comment]
**QA OK**

Firefox 82 + Nixos
Suite web dev master commit f6f781c4f50bc1d8f990107bcd5d8da12b8afbc4
Device model One FW 1.8.3 commit 0xdf0963ec48f01f3d07ffca556e21ff0070cab099,
