### ISSUE TITLE
Update to storybook 5

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#29]
https://medium.com/storybookjs/storybook-5-migration-guide-d804b38c739d

**Comment by slowbackspace** [comment]
PR in old repository  https://github.com/trezor/trezor-ui-components/pull/79

**Comment by mroz22** [comment]
isnt this done already? @keip

**Comment by vladimirvolek** [comment]
There is one more task https://github.com/trezor/trezor-suite/issues/283
