### ISSUE TITLE
Labeling context menu misplaced in Firefox 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2904]
**Describe the bug**
Labeling context menu are misplaced in Firefox, sometimes are not displayed at all. 
Chromium works fine. See screenshots please.

**Info:**
 - Suite Version: app/web, commit caabdcb1ab7b32edc6c47f47d49035a9b043f19f + Staging
 - Browser: Firefox , version 82
 - OS: Nixos
 - Firmware Version: FW 2.3.3 model T, revision 0d5f00668

**Steps to reproduce:**
1. Load suite in Firefox and enable Labeling when asked
2. Try to edit previously created labels
3. Observe

**Expected result:**
Context menu is displayed next to label as usual

**Actual result:**
Context menu is not displayed or it appears in different part of account transactions list.

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/98363122-c1fb7a00-202e-11eb-800a-d9aa99755fe5.png)

+ gif

![label](https://user-images.githubusercontent.com/31506317/98363141-c889f180-202e-11eb-86e9-78642b9c679e.gif)

**Comment by mroz22** [comment]
@slowbackspace assistance might be needed here :sos:

**Comment by slowbackspace** [comment]
@mroz22  😱  I'll look into it!

**Comment by bosomt** [comment]
**QA NOK**

Nixos + Firefox
Suite web dev master commit 84550f4b5e4fd96c9515ffeaa11fd6a20fdde3d6
Device model One firmware 1.9.3 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,

please see what happens when i press `copy address`. it scrolls to bottom of page.
Maybe it's related to issue https://github.com/trezor/trezor-suite/issues/2894


![Peek 2020-11-10 11-55](https://user-images.githubusercontent.com/31506317/98665912-989f5e80-234c-11eb-8d0c-bec276cf0fe6.gif)

**Comment by tsusanka** [comment]
Let's fix this in the following release properly (no rushing to tomorrow's release).

**Comment by mroz22** [comment]
isn't that a new issue? I agree that it is probably related to the initial one but "Labeling context menu misplaced in Firefox" seems somewhat misleading.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox Browser 82
Suite web dev master commit 374d027
Device model T fw 2.3.4 commit 50854b921
