### ISSUE TITLE
google provider registration (web)

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#2905]
- Register ouath client with google (web application type) ![image](https://user-images.githubusercontent.com/30367552/98368159-2a4e5980-2037-11eb-8524-d371d2804d69.png)

- Please also set "Authorized JavaScript origins" and "Authorized redirect URIs" to the same values that are registered with Dropbox

**Comment by prusnak** [comment]
client id: `705190185912-nejegm4dbdecdaiumncbaa4ulrfnpk82.apps.googleusercontent.com`

Authorised JavaScript origins
https://wallet.trezor.io
https://suite.trezor.io
https://beta-wallet.trezor.io
https://staging-wallet.trezor.io
https://suite.corp.sldev.cz

Authorised redirect URIs
https://staging-wallet.trezor.io/wallet/web/static/oauth/oauth_receiver.html
https://staging-suite.trezor.io/web/static/oauth/oauth_receiver.html
https://beta-wallet.trezor.io/wallet/web/static/oauth/oauth_receiver.html
https://suite.trezor.io/web/static/oauth/oauth_receiver.html
https://suite.corp.sldev.cz/suite-web/develop/web/static/oauth/oauth_receiver.html
https://suite.corp.sldev.cz/suite-web/develop/wallet/static/oauth/oauth_receiver.html

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox Browser 82
Suite web dev master commit 374d027
Device model T fw 2.3.4 commit 50854b921

**Comment by mroz22** [comment]
yay, just one last thing here: 

Authorised JavaScript origins

++ `http://localhost:3000`

Authorised redirect URIs

++ `http://localhost:3000/static/oauth/oauth_receiver.html`

These seem to be necessary to list as well to make it work on localhost. May I please ask you @prusnak to do so?

**Comment by prusnak** [comment]
> yay, just one last thing here:

done
