### ISSUE TITLE
Transaction history deleted when app data deleled (webapp)

### ISSUE THREAD

**Issue by IvaFingerova** [trezor/trezor-suite#2909]
**Describe the bug**
while testing exchange, I got a fail and went to the inspector and deleted app data, went back to the transaction tab in the account and couldn't see my failed transaction any more

**Info:**
 - Suite Version:web, commit ???
 - Browser: Brave, Version 1.14.84 Chromium: 85.0.4183 
 - OS: MAC OS Catalina 10.15.7 (19H2)
 - Firmware Version: model T, revision 2.3.1.

**Steps to reproduce:**
1. a make a failed transaction (possibly any transaction) and wait for the transaction to show in the list on account level
2. b go to the browser inspector and delete app data
3. c go back to the transactions overview (account level) and transaction is gone

**Expected result:**
I'd hope to see my failed transaction 👍 

**Actual result:**
A clear and concise description of what actually happens.
I don't see my failed transaction 👎 

**Screenshots:**
insert here 
![image](https://user-images.githubusercontent.com/8152411/98386438-7659c800-2050-11eb-925e-eb686a376099.png)

**Note(s):**
on the dashboard I can see my transaction OK as sent mount

**Comment by martinboehm** [comment]
Works as expected. The trade data are stored in the storage, if the storage is deleted, the data is gone.

**Comment by mroz22** [comment]
I am closing this as it appears to be resolved. If any parts to the conversation don't feel it the same, please reopen.

**Comment by bosomt** [comment]
**QA OK**

works as expected, all suite data is deleted

Nixos + Firefox Browser 82
Suite web dev master commit 374d027
Device model T fw 2.3.4 commit 50854b921
