### ISSUE TITLE
Self-hosted labeling sync using WebDAV (Nextcloud, etc.) ⛈️

### ISSUE THREAD

**Issue by michnovka** [trezor/trezor-suite#2918]
**Is your feature request related to a problem? Please describe.**
Right now only Dropxbox is supported on my Linux distro. I have a self-hosted Nextcloud solution and as the leading opensource cloud hosting I think Trezor should aim to support this.

**Describe the solution you'd like**
Add Nextcloud to the list of supported cloud storeage providers.

**Describe alternatives you've considered**
Alternatively, allow me to specify exactly folder on my system where the data is stored and loaded from and I can set up syncing of this folder on my own using some sync client of nextcloud. This would add support to virtualy ANY cloud storage as all you need to do is sync that folder.

**Comment by mroz22** [comment]
Hi @michnovka 
Thanks for your proposal. First of all, this is something that should be validated by the product department, so I am assigning @matejzak at the moment. 

As for now, my question is, would you like to contribute implementing this?

**Comment by michnovka** [comment]
@mroz22 sorry, my node.js skills are poor. I am willing to fund this should there be some bounty program tho.

**Comment by keraf** [comment]
As a NextCloud user I think that would be awesome to support, especially since the reason I moved to NextCloud was to avoid Drive, Dropbox and co :smile:  @mroz22 @matejzak I can take this task and test it against my own instance.

**Comment by mroz22** [comment]
Could you post link to the relevant next cloud API documentation? I could read through it very quickly just to give idea on how complicated this would be. Chances are that it could be implemented pretty easily.

**Comment by keraf** [comment]
Here's the client API documentation from NextCloud: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/index.html

I think maybe we can offer a wider support of platforms by implementing a WebDav client so that people can use other products such as Pydio or their own NAS.

**Comment by prusnak** [comment]
WebDAV would be great! It seems there is a maintained webdav client package here: https://www.npmjs.com/package/webdav

**Comment by glacierbits** [comment]
@mroz22 Product department approves. :) Something we have discussed quite recently as a matter of fact. Putting it on the public roadmap, due date is yet to be agreed upon based on your evaluation of the relative implementation effort. Thanks!

**Comment by prusnak** [comment]
Found this neat Go implementation of WebDAV server - https://github.com/hacdias/webdav - might be useful for testing

**Comment by MCM-Mike** [comment]
> Alternatively, allow me to specify exactly folder on my system where the data is stored
Do we know where the labels from the Trezor-Suite are stored on a Linux file system?

**Comment by ghost** [comment]
**Disclaimer**: I am not a dev of Satoshilabs, just a random dude digging in the code. No guaranties!

@MCM-Mike 

> Do we know where the labels from the Trezor-Suite are stored on a Linux file system?

I did a digging and I have found it:
`/home/<user>/.config/@trezor/suite-desktop/metadata/<some hash>.mtdt`

And according to [this](https://github.com/trezor/trezor-suite/blob/e3f87c7ad425365772dd4972d71e292bec1cf75e/packages/suite/src/actions/suite/metadataActions.ts#L450) data there are encrypted.

**Comment by My1** [comment]
can we get this for the pw manager as well?

**Comment by prusnak** [comment]
> can we get this for the pw manager as well?

Yes, password manager will become part of the Suite eventually, so it will have this feature once implemented.

**Comment by keraf** [comment]
Would be nice to see this in Suite some day soon. Happy to submit a PR if there's a bounty.

**Comment by Perlover** [comment]
Hi!

I have a slightly different problem. But also related to this. To begin with, I want to recommend an excellent program for synchronization - Syncthing. You can sync local files between your devices there in a decentralized and transparent way - your own cloud system between your devices only. It doesn't need WebDAV and it's much easier and simpler (works under Windows/Linux/Android/iPhone).

So I can just specify to sync the folder (Linux) : /home/$USER/.config/@trezor/suite-desktop/metadata

But I have another problem. I took and copied the `*.mtdt` files to this folder from the Apps/TRESOR folder from Dropbox, but when I select Localsystem in the Trezor Suite afterwards, the application swears with errors. How can I transfer existing label files from Dropbox to the local system so that they work?

**Comment by prusnak** [comment]
> I have a slightly different problem

Please open a new issue.

**Comment by sime** [comment]
Closing in favour of #8321
