### ISSUE TITLE
Incorrect error notification for FW installation fail

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2919]
**Describe the bug:**
TT and T1 update both show "Error: Firmware install failed" instead of "Error: Firmware installation failed" in Onboarding/Update FW process when FW installation is canceled.

NixOS + Chromium 85
Suite web 20.11.1 39d1b96
Device TT 2.3.3

**Steps to reproduce**
**1** Connect device with outdated FW
**2** Initiate FW update
**3** Cancel FW update

**Expected**
"Error: Firmware installation failed"

**Actual**
TT and T1 update both show "Error: Firmware install failed" instead of "Error: Firmware installation failed"

**Note** Originally reported [here](https://github.com/trezor/trezor-suite/issues/2659).

**Comment by tsusanka** [comment]
@mroz22 is this due to https://github.com/trezor/trezor-firmware/issues/1334?

**Comment by mroz22** [comment]
Firmware does not send any message, so yes. I've added custom fallback message for this case into trezor-connect, that sounds "Firmware install failed". 

But QA would be happier if it was "Firmware installation failed".

I could have added `Firmware install cancelled` just the same as trezor T sends. But I was more like let's do it more abstract and cover all possible error cases that do not send reason.
