### ISSUE TITLE
APP blockbook transaction links in nixos are broken

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2921]
**Describe the bug**
Transaction detail links in NixOS app are broken. There is an additional character in URL link that breaks it (a hyphen)

**Info:**
 - Suite Version: APP 513631a9fa62c438e60397a9942b04275bcd621a
 - OS: NixOS
 - Firmware Version: T1 1.9.3 public

**Steps to reproduce:**
1. Connect device 
2. Go to Accounts> Overview > Transaction history
3. Click on Details for any transaction

**Expected result:**
Link will be working, just like it does with other OS platforms.

**Actual result:**
Link for blockbook view of transaction is broken and clicking on "Continue" does nothing.

**Screenshots:**

![image](https://user-images.githubusercontent.com/58593111/98531851-3594c580-2281-11eb-95cc-b65e89475f73.png)

**Comment by keraf** [comment]
The hyphen is only added for displaying the text (done automatically by the alert box), it shouldn't be in the actual link. But also that made me realize that not all trezor.io links are exempt to the external link warning. In regards to the link not opening after pressing continue, I believe this is a Nix related issue as it has been working well for me on other platforms (Ubuntu, Win 10, Mac OS).

**Comment by tsusanka** [comment]
@wendys-cats if you click Continue will the link open in the browser correctly? Or it includes the hyphen as well? Maybe it's just a "display" thing.

**Comment by tsusanka** [comment]
Interesting, clicking on Continue works just fine on my NixOS. So this is most likely specific to some weird cases. Let's not worry about this one for now and we'll try later when @wendys-cats upgrades her system if the issue persists :).

**Comment by wendys-cats** [comment]
@keraf definitely Nix related, links on other platforms are working fine. It seems like my external links in Suite are not working at all (have not noticed this outside of Suite APP). @bosomt reports his external links are good and working. I will try to find out what exactly is wrong (maybe reinstall/system update will help).

@tsusanka I will close the issue now and reopen is it persists after system update.
