### ISSUE TITLE
Pay technical debt in trezor-link

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#2923]
High level issue for the [trezor-link](https://github.com/trezor/trezor-link) work we need to do:

- [ ] [Move to monorepo as `@trezor/transport`](https://github.com/trezor/trezor-suite/issues/3663)
- [x] Unit tests
- [x] TypeScript support
- [x] Bump protobuf lib
- [ ] Refactor:
  - [ ] use .proto files
  - [ ] allow multiple protobuf sets/instances
  - [ ] http requests cancelation
  - [ ] general cancel logic (currently handled by connect)
  - [ ] enumeration cycle module (currently handled by connect)
  - [ ] http requests race conditions (currently handled by connect)

**Comment by goodhoko** [comment]
I think that the set and order of tasks is generally correct. Just a few comments:

> - [ ] Unit tests

Apprat from the classic unit tests of the individual components it would be also nice and cheap on man-time to take all existing messages of all existing message sets and for each one test that `message == desrialize(serialize(message))`. 

This could give us confidence in the `Bump protobuf lib` step.

> - [ ] Move to monorepo as @trezor/transport

Link is used by Connect and Connect is used by Suite. Further Connect is expected to be moved to monorepo too. Woudn't it make more sense to merge Link into Connect first?

**Comment by goodhoko** [comment]
I changed the order of tasks so that we start with the move to monorepo. That should make all subsequent steps a bit easier.

I'll use sub-issues for the individual setps they'll be linked from the issue description. (Link to the 'move to monorepo' issue is already in place.)

**Comment by mroz22** [comment]
closing in favor of #4601
