### ISSUE TITLE
U2F counter restoration not working

### ISSUE THREAD

**Issue by jpph** [trezor/trezor-suite#2933]
When restoring trezor one (using trezor suite), the u2f counter is reset to 0. That can make authentication fail if counter is lower than one used before. Should be unix time ?

trezor used : trezor one
firmware : 1.9.3
trezor suite : 20.10.1
website used for checking counter, with chrome on windows 10 : https://mdp.github.io/u2fdemo/

I have tested with wallet.trezor.io, it is working, counter is restored with unixtime. This is an issue with trezor suite

**Comment by prusnak** [comment]
This is a regression (missing feature) when compared to Trezor Wallet. I think this should be included in the December's sprint and I think the fix is rather easy.

**Comment by mroz22** [comment]
Yes. wallet.trezor.io sets this to unix time in seconds
https://github.com/satoshilabs/mytrezor/blob/b030ebae4de01aaf2e09f320d112837b668b3379/app/scripts/trezor/TrezorDevice.js#L1207

This will be fixed in the December's release.

**Comment by bosomt** [comment]
**QA OK**

The current Unix epoch time is  1607589143

![image](https://user-images.githubusercontent.com/31506317/101741587-89860a80-3aca-11eb-8aa9-efb09257eddd.png)

Nixos
Firefox 82.0.3 (64-bit)
Suite web dev master commit f93bd32
Device 2.3.5
