### ISSUE TITLE
Recognize that the latest firmware is already installed for TT in the bootloader mode

### ISSUE THREAD

**Issue by cryptomar1o** [trezor/trezor-suite#2934]
When connecting with Trezor Model T, the application could recognize what bootloader version is used. If the latest one is already installed, the user should be informed, not necessary to do any additional checks.

Trezor Suite version 20.0.12 connected with Trezor Model T firmware version 2.3.4, still asked to check the firmware version and reconnect the device:

![01](https://user-images.githubusercontent.com/52966597/98693350-761f3c80-2370-11eb-9542-7296801612c2.png)
![02](https://user-images.githubusercontent.com/52966597/98693357-77506980-2370-11eb-8d4f-c8af43ff0a90.png)

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
