### ISSUE TITLE
Do not instruct the user to restart bridge in desktop

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2936]
**Describe the bug**
Instructing the user to restart Trezor Bridge does not make sense when the user uses the desktop app. Also instruction to restart sounds a bit.. amateurish doesn't it?

I mean we can consider some "bridge restart" button in the desktop but obviously the Bridge should work without any restarting voodoo.

**Info:**
 - Suite Version: desktop https://github.com/trezor/trezor-suite/commit/36c7716bd5c2a01de4b8981a2ac680f80c79164c
 - OS: NixOS
 - Firmware Version: 1.9.3

**Steps to reproduce:**
1. Disconnect device during onboarding

**Screenshots:**
![Screenshot from 2020-11-10 18-25-05](https://user-images.githubusercontent.com/1835345/98709481-b5ef1f80-2382-11eb-8084-9acb5f7243d8.png)

**Comment by glacierbits** [comment]
To be fixed in new Onboarding #3332
