### ISSUE TITLE
Restarting bridge using "five clicks" is not working

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2942]
**Describe the bug**
The debug feature introduced in #2153 was working and now it is not :). Might have been broken by #2693.

**Info:**
 - Suite Version: 36c7716bd5
 - OS: NixOS but tested also on Mac with the same result

**Steps to reproduce:**
1. Disconnect all devices 
2. Launch Suite
3. On the "connect your device" click 5x times on the image (see #2153 for details)
4. Launch emulator

**Expected result:**
The emulator works with Suite.

**Actual result:**
Nothing happens. The bridge is not restarted and therefore Suite stays on the "connect your device" dialog.

**Comment by tsusanka** [comment]
Not sure whom to assigned. @keraf you did the refactoring so maybe to you? Low prio though definitely.

**Comment by keraf** [comment]
If you're trying to run Suite with Bridge in dev mode, you have to use the `--bridge-dev` flag. No clicking needed :slightly_smiling_face:

**Comment by tsusanka** [comment]
Ah, just when I documented it on our internal wiki :cry: :smile:. My general idea was to allow this also for non-command-line-aware people but since one needs to launch the emulator from CLI or even from trezor-user-env it is not a very valid point. So very well then.

I will document into docs/, it's missing.

**Comment by tsusanka** [comment]
Done in 7dace409cb7866cde59490f098bd6196a6e7e21c.
