### ISSUE TITLE
Upgrade to styled-components 5.2 breaks some css styles

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2944]
most likely caused by https://github.com/trezor/trezor-suite/pull/2940 at least I can't think of anything else that could cause this.

<img width="1601" alt="Screenshot 2020-11-11 at 16 23 30" src="https://user-images.githubusercontent.com/6961901/98830084-450b3e80-243a-11eb-9358-87a7091c8f93.png">

**Comment by slowbackspace** [comment]
update: indeed caused by new version of styled-components, breaking change introduced in 5.2 I don't feel like dealing with it right now (It could be rather tedious process to find everything that got broken because of it). We've reverted to previous version for now.

https://github.com/styled-components/styled-components/issues/3273

**Comment by jerechinsky** [comment]
Irrelevant.
