### ISSUE TITLE
Download menu width

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2946]
Nitpick alert. 

The menu width should be the same as the button. 

<img width="595" alt="Screenshot 2020-11-11 at 18 54 45" src="https://user-images.githubusercontent.com/29627086/98846622-88bc7300-244f-11eb-975f-ad00bf5dc055.png">

**Comment by bosomt** [comment]
**QA OK**

https://suite.corp.sldev.cz/suite-web-landing/develop/

![image](https://user-images.githubusercontent.com/31506317/100598299-d4e82e00-32fe-11eb-8a7f-baa2c87ff77f.png)
