### ISSUE TITLE
Update Trezor Bridge modal doesn't fit to Suite window and offers Linux version of Bridge 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2950]
**Describe the bug**
+ when maximized and in full HD version of Suite modal doesn't fit to Suite window.
+ see screenshot, you have to scroll down to see that you can close this modal and drop down menu doesn't fit suite at all.
+ even i'm in Windows Suite offers me `Linux` version of Bridge.
 
**Info:**
 - Suite Version: app, commit 36c7716bd5c2a01de4b8981a2ac680f80c79164c
 - OS: Microsoft Windows [Version 10.0.19042.630]
 - Firmware Version: 2.3.4

**Steps to reproduce:**
1. install/use Trezor Bridge older than 2.0.30
2. install current public Suite version 2020.11.1
3. click on Trezor Bridge update notification

**Expected result:**
Modal is smaller to fit to suite window

**Actual result:**
Modal doesn't fit to suite window

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/98910022-e2aa5080-24c2-11eb-8f2f-4f22d21f1e94.png)

**Comment by keraf** [comment]
Separate issue created in connect for the incorrect pre-selected download: https://github.com/trezor/connect/issues/715

**Comment by bosomt** [comment]
**QA OK**

Windows 10
Suite dev app commit  c2418811
Device Model One fw 1.9.3 public
