### ISSUE TITLE
Desktop - Buy - Payment gateway redirect opens a local file

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2958]
**Describe the bug**
Payment gateway redirect to text editor and not to browse in Kubuntu.
tested in Mint Linux with KDE and it works fine.

**Info:**
 - Suite Version: app, commit 36c7716bd5c2a01de4b8981a2ac680f80c79164c
 - OS:  Kubuntu 20.04
 - Firmware Version: 2.3.4

**Steps to reproduce:**
1. Start Suite app in Kubuntu
2. Proceed with Buy feature
3. Hit Go to payment button

**Expected result:**
Payment will proceed in browser

**Actual result:**
Buy provider is open in `Kate - Advanced Text Editor`

**Screenshots:**
![Peek 2020-11-12 12-57](https://user-images.githubusercontent.com/31506317/98938408-1e0b4600-24e8-11eb-812d-22b914d4854a.gif)

![image](https://user-images.githubusercontent.com/31506317/98938004-8b6aa700-24e7-11eb-9c62-4e682316595c.png)

**Comment by martinboehm** [comment]
@bosomt  Could you please check that you have some default browser on the system? Also, is labelling working?

**Comment by bosomt** [comment]
@martinboehm after I changed it from based on content to browser it works fine.
Is there anything that we can change in app so this default behavior doesn't need to be changed ?

![image](https://user-images.githubusercontent.com/31506317/98959365-7f8cde00-2503-11eb-96f8-82723d48d4f2.png)

**Comment by martinboehm** [comment]
I am not aware of a method in Electron how to detect what default browser is selected. Maybe @keraf or @szymonlesisz would know more?

**Comment by keraf** [comment]
I don't think there's such method in Electron but the problem seems to be related with the responses (not just this one) from `packages/suite-desktop/src-electron/http-receiver.ts`. Adding a `Content-Type` header to all responses should probably do the trick. Or maybe output valid HTML (doctype and head tag are missing).

**Comment by bosomt** [comment]
**QA OK**

fixed in https://github.com/trezor/trezor-suite/pull/2963
