### ISSUE TITLE
ARM64 support (Linux and macOS)

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#2959]
It should be possible to run Trezor Suite on ARM64 systems:
* Linux - e.g. Raspberry [Pi 4](https://www.raspberrypi.org/products/raspberry-pi-4/) or [Pi 400](https://www.raspberrypi.org/products/raspberry-pi-400/)
* Windows - e.g. Microsoft Surface Pro X
* macOS - e.g. the new Macbook Air

**Progress:**

Landing pages - merged via PR https://github.com/trezor/trezor-suite/pull/2969 :tada: 
- [x] add arch to download links
- [x] add arm64 download links

Linux - merged via PR https://github.com/trezor/trezor-suite/pull/2969 :tada: 
- [x] enable build
- [x] bundle Tor binary
- [x] bundle Bridge binary
- [x] test on real hardware

macOS - PR in https://github.com/trezor/trezor-suite/pull/4082
- [x] enable build
- [x] bundle Tor binary
- [x] bundle Bridge binary
- [x] test on real hardware

We decided to not do Windows ARM64 build for now:
- BLOCKED by Golang not being able to (cross)compile bridge (Go+C) for Windows/ARM
- BLOCKED by Electron-builder not able to produce Windows/ARM packages

**Comment by prusnak** [comment]
Work is being done in https://github.com/trezor/trezor-suite/pull/2960

**Comment by prusnak** [comment]
macOS running on Apple Silicon will be able to run Suite via Rosetta after https://github.com/trezor/trezor-suite/issues/3164 is fixed (which should happen just in time for the January release). In the meantime, November's release works just fine on Apple Silicon devices, i.e. only December's release does not work on Rosetta.

**Comment by CoelWu** [comment]
It seems like Golang 1.16+ add support for darwin/arm64 already. (Compiling From My Intel MacBook Air)
```
Coels-Air:trezord-go coel$ CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build .
# github.com/trezor/trezord-go/usb/lowlevel/libusb
cgo-gcc-prolog:1186:2: warning: 'libusb_set_debug' is deprecated [-Wdeprecated-declarations]
usb/lowlevel/libusb/c/libusb.h:1351:1: note: 'libusb_set_debug' has been explicitly marked deprecated here
usb/lowlevel/libusb/c/libusb.h:70:50: note: expanded from macro 'LIBUSB_DEPRECATED_FOR'
Coels-Air:trezord-go coel$ file trezord-go 
trezord-go: Mach-O 64-bit executable arm64
```

**Comment by prusnak** [comment]
Right. We can already build Trezor Bridge for arm64-mac. We are still missing tor binary for arm64-mac, though.

**Comment by CoelWu** [comment]
I found a script that can compile tor into native arm64 format. It's from Brave Browser which also use tor as it's dependencies.

Here is the link: https://github.com/brave/tor_build_scripts

```
Coels-Air:tor_build_scripts coel$ file /Users/coel/Desktop/tor_build_scripts/arm64/tor-0.4.5.9/root/bin/tor 
/Users/coel/Desktop/tor_build_scripts/arm64/tor-0.4.5.9/root/bin/tor: Mach-O 64-bit executable arm64
```

Hope this could help :)

**Comment by prusnak** [comment]
I prepared the PR in https://github.com/trezor/trezor-suite/pull/4082 which adds native bridge and tor binaries enabled native arm64 build for the Suite

Thanks @CoelWu !

**Comment by CoelWu** [comment]
You're more than welcome! @prusnak

**Comment by osintowl** [comment]
If ya'll need some testers on real hardware let me know! So excited ya'll got this so fast!

**Comment by osintowl** [comment]
I'm on a mac mini m1
