### ISSUE TITLE
Account scroll window glitch

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-suite#2961]
**Describe the bug**
- when scrolling the account bar accounts are being covered by each other and some of them cannot be accessed properly due to being overlapped by others.

**Info:**
 - Suite Version: app, Trezor-Suite-20.11.0-mac
 - OS: macOS Mojave (version 10.14.6)

**Steps to reproduce:**
1. Go to My Accounts
2. Add enough accounts to activate the scroll bar
3. Scroll and change the size of the window

**Expected result:**
- Scroll window should be scroll-able and all accounts accessible
- UI should be coherent

**Actual result:**

- some accounts are being covered by others
- UI is not coherent

**Screenshots:**
![photo_2020-11-12_16-52-58](https://user-images.githubusercontent.com/37402530/98963097-933a4380-2507-11eb-9538-97fb511dafa2.jpg)
![photo_2020-11-12_16-52-53](https://user-images.githubusercontent.com/37402530/98963101-93d2da00-2507-11eb-9ad5-219e015ee1ed.jpg)

Screen capture GIF: https://im4.ezgif.com/tmp/ezgif-4-73ea3f0b2cd6.gif

**Comment by slowbackspace** [comment]
@yohaaan  that gif would be really helpful :D 
<img width="386" alt="Screenshot 2020-11-13 at 15 35 05" src="https://user-images.githubusercontent.com/6961901/99083402-cfcc7480-25c5-11eb-816a-6ea6f8020a87.png">

**Comment by slowbackspace** [comment]
@matejzak are we going to finally remove sticky  account feature? 🙏 I already once shared my concerns that this feature really might confuse people.

**Comment by glacierbits** [comment]
@slowbackspace Ship it!

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.5.1 (974429bab27c43502251b646a485d792a4ab4180)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1584x990
 - Device: model T 2.3.6 regular

**Comment by wendys-cats** [comment]
**QA OK**

**Info:**
- Suite version: web 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
- Chromium Version 88.0.4324.182 (Official Build) (64-bit)
- NixOS 21.03
- Device TT 2.3.6 public

**Comment by STew790** [comment]
**QA OK

Info:**

- Suite version: App 21.5.1 (974429b)
- OS: Win10
- Device Model T 2.3.6 regular
