### ISSUE TITLE
Desktop: Not able to quit the app on Win10

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2964]
I have just run into this again. Can't close app.

OS: Windows 10 pro, version 1903
commit 36c7716b 

Also maybe it's worth mention that it does not find the latest update.

_Originally posted by @mroz22 in https://github.com/trezor/trezor-suite/issues/2630#issuecomment-726196662_

**Comment by mroz22** [comment]
After that I checked task-manager. There were number of Trezor Suite process (not meaning those clustered in single record which is expected) so I killed all of them, started the app again and quit started to work. But still no update offered.

**Comment by tsusanka** [comment]
@sorooris could you retest this on current develop if the app can be closed on Windows please? The missing update is expected at the moment.

**Comment by sorooris** [comment]
@tsusanka **QA OK**

Build: app 680b541
OS: Microsoft Windows [Version 10.0.19042.630]
Device: 2.3.4 public

Tested closing the app, verified in Task Manager all nested processes are closed.
![image](https://user-images.githubusercontent.com/10185314/100371337-e9c77780-3007-11eb-9c4f-5bf3942a078f.png)
