### ISSUE TITLE
Desktop - macOS update install not initiated when prompted to update immediatelly

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2965]
**Describe the bug**
Checking for an update and prompting an app restart/installation results in minimizing the Suite window.

**Info:**
 - Suite Version: app b0dacc34
 - OS: macOS Catalina 10.15.7
 - Firmware Version: model T 2.3.4 50854b921

**Steps to reproduce:**
Prerequisite - newer build available
1. Navigate to Settings -> General - select Check fo updates button,
2. Confirm any dialog/modal, download newer build,
3. Select Restart & update button option. 

**Expected result:**
App is restarted and updated correctly.

**Actual result:**
App window is only minimzed, no action follows.

**Screenshots:**
![Screen-Recording-2020-11-12-at-1](https://user-images.githubusercontent.com/10185314/98970495-49099000-2510-11eb-9a64-337b4f2c694f.gif)

**Comment by sorooris** [comment]
Will be tested during the release testing, after freeze.

**Comment by sorooris** [comment]
Testing of this issue is blocked by #3151.

**Comment by tsusanka** [comment]
I am moving this to the next project, since we need to test 20.12.1 -> 20.1.1 as commented [here](https://github.com/trezor/trezor-suite/issues/3151#issuecomment-740828740).

**Comment by sorooris** [comment]
@tsusanka you mean 20.12.1 -> 21.1.0, right?

**Comment by tsusanka** [comment]
Yes, thanks.

**Comment by sorooris** [comment]
Unable to initiate autoupdate and verify the issue on the macOS testing device - tested when pre-release was available, canceled download.

**Comment by sorooris** [comment]
**QA OK**

Autoupdate with the `--pre-release` flag successful; immediate update relaunches and updates Suite correctly.

Suite: app 20.1.0 -> 21.1.0 48b5674
OS: macOS Big Sur 11.1
Device: 2.3.5 RC
