### ISSUE TITLE
Make errors silent when auto-update is not available

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#2968]
**Short version:**

Currently we show a red notification when it's impossible to fetch auto-update information from GitHub.

I think this has no informational value and should be silenced.

**Long version:**

While working on https://github.com/trezor/trezor-suite/pull/2969 I stumbled upon the following auto-update error:

```
Checking for update
Error: Error: Cannot find latest-linux-arm64.yml in the latest release artifacts (https://github.com/trezor/trezor-suite/releases/download/v20.10.1/latest-linux-arm64.yml): HttpError: 404 Not Found
```

That happened, because the last release did not have `latest-linux-arm64.yml` file included and the error was correctly caught in the Suite. What also happened is that the red error notification was shown, but I think these kind of errors should be silenced, because:

1) they have very little information value for the user
2) they will show every time when GitHub is unreachable

**Comment by prusnak** [comment]
Maybe this does the trick? (untested)

``` patch
diff --git a/packages/suite/src/actions/suite/desktopUpdateActions.ts b/packages/suite/src/actions/suite/desktopUpdateActions.ts
index a99168a8a..f4d4b8c8c 100644
--- a/packages/suite/src/actions/suite/desktopUpdateActions.ts
+++ b/packages/suite/src/actions/suite/desktopUpdateActions.ts
@@ -44,7 +44,9 @@ export const error = (err: Error) => (dispatch: Dispatch, getState: GetState) =>
     console.error('auto-updater', err);
 
     const { state } = getState().desktopUpdate;
-    dispatch(addToast({ type: 'auto-updater-error', state }));
+    if (state !== 'checking') {
+        dispatch(addToast({ type: 'auto-updater-error', state }));
+    }
 
     dispatch({
         type: DESKTOP_UPDATE.NOT_AVAILABLE,
```

**Comment by keraf** [comment]
@prusnak That should work, added in a PR.
