### ISSUE TITLE
ETH: Custom fee

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2970]
Design for custom fee on ETH: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f0c3209d6b0239f5ed31ef4) 

- Click on `Custom` will expand the box with the two inputs.

**Comment by bosomt** [comment]
**QA OK**

https://eth1.trezor.io/tx/0x2a9d873f90db1bafe1a412f5205cdb08159d3e420b0c3f2f505518d2a6228345

Nixos
Chromium Version 87.0.4280.66 (Developer Build) (64-bit)
Suite dev master commit c5120e5fa57e868d215ec39d4a03717e8497afe8
Device model One 1.9.4
