### ISSUE TITLE
Exchange, Offer detail - untranslated tooltips

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2982]
**Describe the bug**
Tooltips display untranslated strings, copy is missing.

**Info:**
 - Suite Version: web, commit 8209171d71df3d6f34c367274f2aca6cdded4c57
 - Browser: Chromium 86.0.4240.111
 - OS: any (tested NixOS 20.09)
 - Firmware Version: 2.3.4 50854b921

**Steps to reproduce:**
1. Navigate to the Trade tab, Exchange sub-tab,
2. Fill the form with arbitrary values, confirm,
3. Select an arbitrary offer and navigate to the offer detail.

**Expected result:**
Hover above tooltips displays a _translated_ tooltip text.

**Actual result:**
Hover above tooltips displays an _untranslated_ tooltip text.
 - TR_EXCHANGE_RECEIVE_ACCOUNT_QUESTION_TOOLTIP
 - TR_EXCHANGE_RECEIVE_ADDRESS_QUESTION_TOOLTIP
 - Float-rate offers info TODO

**Comment by vladimirvolek** [comment]
Exchange translations are currently in progress.

**Comment by vladimirvolek** [comment]
translated

**Comment by wendys-cats** [comment]
**QA OK**

Suite Version: web, commit cefce60f91b3e4af9bc5aabafa86193b988fe6ce
Browser: Chromium 85
OS: NixOS 20.09
Firmware Version: 2.3.4 public 50854b921

Result:
Tooltips in exchange, specifically part where user picks Receiving account for exchange offer, are translated.
