### ISSUE TITLE
Exchange, SendCryptoSelect - unable to filter by coin name

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2984]
**Describe the bug**
SendCryptoSelect allows only to filter by coin abbreviation - not coin full name.

**Info:**
 - Suite Version: web, commit 8209171d71df3d6f34c367274f2aca6cdded4c57
 - Browser: Chromium 86.0.4240.111
 - OS: any (tested NixOS 20.09)
 - Firmware Version: 2.3.4 50854b921

**Steps to reproduce:**
1. Navigate to the Exchange sub-tab in Trade tab of any coin (e.g. BTC),
2. Click into the SendCryptoSelect input,
3. Type in a coin name (e.g. litecoin).

**Expected result:**
Coin is found by both its name and abbreviation (the same way asi for example in AccountSearchBox).

**Actual result:**
Coin is filtered only by coin abbrevation.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/99261331-d86ab800-281c-11eb-82b4-d9e91f2bbcac.png)

**Comment by wendys-cats** [comment]
**QA OK**

Suite Version: web, commit a7554ff
Browser: Chromium 85
OS: NixOS 20.09
Firmware Version: 2.3.4 public 50854b921

Result:
Search in SendCryptoSelect works for abbreviatons and full coin names as well.
