### ISSUE TITLE
Exchange, FiatInput + receiveCryptoInput - 0 allowed in inputs and validated in Offers list

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2987]
**Describe the bug**
FiatInput and receiveCryptoInput do not validate the 0 amount and allow to continue to Offers list, where it is validated by the providers.

**Info:**
 - Suite Version: web, commit 8209171d71df3d6f34c367274f2aca6cdded4c57
 - Browser: Chromium 86.0.4240.111
 - OS: any (tested NixOS 20.09)
 - Firmware Version: 2.3.4 50854b921

**Steps to reproduce:**
1. Navigate to the Exchange sub-tab in Trade tab of any coin (e.g. BTC),
2. Enter a 0 amount in either input (FiatInput or receiveCryptoInput) and set an arbitrary fee,
3. Confirm.

**Expected result:**
Minimum amount is validated and a 0 value is not allowed, Show offer stays disabled.

**Actual result:**
Show offers is enabled and after selecting it, the Offers list is displayed where all of the providers display a "Invalid amount" error message.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/99270061-cd1c8a00-2826-11eb-9ede-e76b5afeebc9.png)
![image](https://user-images.githubusercontent.com/10185314/99271168-1b318d80-2827-11eb-8f10-e7904c021643.png)

**Note(s):**
Tested with LTC, ETH, XLM.

**Comment by wendys-cats** [comment]
**QA OK**

Suite Version: web, commit a7554ff
Browser: Chromium 85
OS: NixOS 20.09
Firmware Version: 2.3.4 public 50854b921

Result:
Zero value is not valid, Suite shows "Amount is too low". Show offers button stays disabled.
