### ISSUE TITLE
Onboarding - Recovery completed message when device disconnected before recovery

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2992]
**Describe the bug**
You will see `Recovery completed` message when you disconnected device during select recovery type modal.
Strange that it only happens on first time, you have to restart onboarding to see this message one more time.
Otherwise you will see proper `Reconnect your Trezor` message

**Info:**
 - Suite Version: web, commit 374d027cdf94370dc09fc17c448cdfd7a3543b8c
 - Browser: Firefox, version 82
 - OS: Nixos
 - Firmware Version: 1.9.3 model One , revision 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,

**Steps to reproduce:**
1. Start suite and start recovery of empty device
2. Disconnect device when asked to perform Standard or Advanced recovery
3. Observer Recovery completed message

**Expected result:**
You are always asked to `Reconnect your Trezor`
**Actual result:**
You will see `Recovery completed`message

**Screenshots:**

![Peek 2020-11-17 09-40](https://user-images.githubusercontent.com/31506317/99366551-0f8ea700-28b9-11eb-9671-1a00663d9c9c.gif)

**Comment by bosomt** [comment]
same behavior when you disconnect device and replace it with already on-boarded device

**Comment by mroz22** [comment]
Hmmm couldn't reproduce today (using later commit 3a29cd9c1e734057c48953660e3dc87db282a9f7)
Are there maybe any more steps that you didn't include in "how to reproduce"? Also you write that you disconnected device, but onboarding should react with "device disconnected screen" and I don't see that.

Isn't that related to nixOS again?

**Comment by bosomt** [comment]
maybe it's related that Nixos is still running old 2.0.28 Bridge ?
I will try to reproduce it via Windows 10 + bridge 2.0.28 + public version of suite

**Comment by bosomt** [comment]
I was not able to reproduce it with Bridge 2.0.30
in suite.trezor.io

**Comment by bosomt** [comment]
I was able to reproduce it now :)
I reconnected already onboarded device and i see 
`Select recharge methodRecovery completedmessage` message

do you want me to create separate issue or is this too much corner case ? :) 
@mroz22 

and what is recharge method ? thy not recovery method ???
