### ISSUE TITLE
Firefox - Suite not loading in private window

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2993]
**Describe the bug**
Suite is not loading in private window, checked on multiple computers, clear of cache or tracking protection didn't helped.
Chrome works fine. Firefox normal window works fine, computer already restarted.

Nothing suspicious in command line /started via firefox --private/

`JavaScript error: , line 0: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.`
`JavaScript warning: resource://devtools/client/shared/demangle.js, line 0: Successfully compiled asm.js code (total compilation time 66ms)
`

**Info:**
Suite Version: web, commit 374d027
Browser: Firefox, version 82
OS: Nixos
Firmware Version: 1.9.3 model One , revision 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,

**Steps to reproduce:**
1. load dev suite master in Firefox incognito window 
2. observe `Loading takes too long` error

**Expected result:**
You can load Suite in private window
**Actual result:**
You can't  load Suite in private window

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/99369739-14555a00-28bd-11eb-8498-c59f88548673.png)

**Comment by slowbackspace** [comment]
I will look into it. Firefox doesn't support idb in incognito mode, but whole app should work just fine without it. (Mozilla has issue open for this and last time I checked they were planning to implement it because right now this really helps websites detecting an incognito mode and preventing access to eg. news articles.)

**Comment by slowbackspace** [comment]
@mroz22 someone deleted very much needed await 🤔

**Comment by bosomt** [comment]
**QA OK**

Firefox 82.0 (64-bit) + Nixos
Suide web dev maser commit da17a8545b7b0342cd85c68132dbe1119ef878c1
Device mdoel T fw 2.3.4 commit 50854b921
