### ISSUE TITLE
🌃 Dark mode bugs and needed improvements

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2997]
Placeholder issue to track all dark mode related issues. Maybe it would be the best if each problem will get separate issue, but let's see how it goes. 

cc @matejzak so you don't miss this issue :)

- [x] analytics on dark mode usage (pretty please @mroz22)
- [ ] desktop dark mode without flash of default theme (will be refactored after suite-native dark mode)
- [x] UI improvements (dropdown menu bg color, shadows, ~secondary button color~, ~graph tooltip~) (in progress, waiting for a design decision)
- [ ] copy for dark mode toggle (title and description) as I literally copy pasted wiki definition (@matejzak)
- [x] QR codes are not recognized by scanners due to dark bg
- [x] scrollbar thumb is too dark in light mode
- [x] Improvements for images https://github.com/trezor/trezor-suite/issues/3048 (closed, we will fix this with new illustrations soon)
- [ ] refactor color definitions (derive color from its base color if possible (doable for eg. hover colors), sane naming)

**Comment by glacierbits** [comment]
Thanks! Managers will soon lose their jobs, should you continue be this meticulous. :)

**Comment by tsusanka** [comment]
- [ ] Create Backup button (I apologize if already reported)
![image](https://user-images.githubusercontent.com/1835345/99577257-6096bc00-29db-11eb-8799-d4bf398b2b65.png)

**Comment by szymonlesisz** [comment]
tracker:
- [x] QR code reader placeholder is white

**Comment by bosomt** [comment]
Show log scroll bar is leaking white color ;)

![image](https://user-images.githubusercontent.com/31506317/101338872-dd4fe400-387d-11eb-8b07-d88d87475c27.png)

Windows 10
Suite app commit e16f9ff
Device model One FW 1.9.3

**Comment by slowbackspace** [comment]
closing this, IT IS AS PERFECT AS IT GETS. Possible improvements in color definitions are really low priority nitpicks generations after us will deal with.

**Comment by bosomt** [comment]
**QA OK**

Fine with me, dark mode is as perfect as it gets for me.
I had 0 issues with dark mode except few nitpicks ;)
