### ISSUE TITLE
Add custom fonts to @trezor/suite

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3]
Example how to add custom fonts to react-native:
https://medium.com/react-native-training/react-native-custom-fonts-ccc9aacf9e5e

**Comment by slowbackspace** [comment]
Interesting reading about custom fonts in mobile apps [https://medium.com/default-to-open/custom-vs-native-fonts-in-apps-9cd7d872491c](https://medium.com/default-to-open/custom-vs-native-fonts-in-apps-9cd7d872491c). 
Based on this, I would stick to the default system font for mobile app.
