### ISSUE TITLE
Labels on SD card 🗃️

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3002]
Give user the option to save labels on SD card via the built in slot in Trezor T.

**Comment by MCM-Mike** [comment]
Update: (rephrasing) 
How are the labels stored under Linux in my case Ubuntu under `/home/$USER/.config/@trezor/suite-desktop`

**Comment by ghost** [comment]
**Disclaimer:** I am not a dev of Satoshilabs, just a random dude digging in the code. No guaranties!

@MCM-Mike `/home/<user>/.config/@trezor/suite-desktop/metadata/<some hash>.mtdt` (See: https://github.com/trezor/trezor-suite/issues/2918#issuecomment-742134477)
