### ISSUE TITLE
Exchange improvements

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3012]
## Design › Implementation irregularities
 Please review design: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f7eead93596205177b8a537) and [Zeplin](https://zpl.io/V1P0W1E) 

- [x]  Form draft should be saved when hitting back button 

<img width="401" alt="Screenshot 2020-11-18 at 21 19 24" src="https://user-images.githubusercontent.com/29627086/99583508-def75c00-29e3-11eb-96fe-7ac422131743.png">
<img width="821" alt="Screenshot 2020-11-18 at 21 19 29" src="https://user-images.githubusercontent.com/29627086/99583492-dacb3e80-29e3-11eb-8181-53bdd92e307f.png">  

- [x]  `‹ Bitcoin #1` Takes me back to erased form. "Back to offers" should be present instead

<img width="608" alt="Screenshot 2020-11-18 at 21 47 06" src="https://user-images.githubusercontent.com/29627086/99586159-9d68b000-29e7-11eb-99f2-f44865925f5b.png"> 

@matejzak discuss with UX

- [x] Transaction ID overflows

<img width="513" alt="Screenshot 2020-11-18 at 23 56 54" src="https://user-images.githubusercontent.com/29627086/99598474-de69c000-29f9-11eb-8bf2-d50d40639d57.png">

- [ ] Pending: We should provide user with more info on what's going on [as designed ](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f46e2f892e8b22d9c45ac04)There should also be a button that will take the user to the transaction detail ( button `‹ Bitcoin #1` is not doing the trick)

<img width="1135" alt="Screenshot 2020-11-18 at 23 58 28" src="https://user-images.githubusercontent.com/29627086/99598601-11ac4f00-29fa-11eb-81c0-3224a28dff59.png"> 

## Design needed: 

- [ ] `Confirmed on Trezor` Contextual notification that we don't use anywhere else. ⚠️ `design needed`
<img width="591" alt="Screenshot 2020-11-18 at 21 48 49" src="https://user-images.githubusercontent.com/29627086/99586312-da34a700-29e7-11eb-88a6-f524860ed76f.png">

- [ ] Let's remove the receive address from the input field (to be consistent with Receive tab) ⚠️ `design needed`
<img width="555" alt="Screenshot 2020-11-18 at 21 29 51" src="https://user-images.githubusercontent.com/29627086/99584408-334f0b80-29e5-11eb-81e7-27d367076294.png"> 

- [ ] Primary button: Continue transaction. No loading is present, user doesn't have feedback on what's going on. ⚠️ `design needed`

- [ ] `Select a coin` placeholder in input: Font weight we don't use anywhere afaik ⚠️ `design needed` 
<img width="256" alt="Screenshot 2020-11-18 at 21 14 25" src="https://user-images.githubusercontent.com/29627086/99582915-0b5ea880-29e3-11eb-87d8-3262f2202f37.png">

- [ ] Loading in button for action that happens in input: Let's load "contextually" instead ⚠️ `design needed`
<img width="303" alt="Screenshot 2020-11-18 at 21 16 39" src="https://user-images.githubusercontent.com/29627086/99583132-5b3d6f80-29e3-11eb-918f-f4550e46d6d7.png">

**Comment by vladimirvolek** [comment]
@matejzak 
In 
![image](https://user-images.githubusercontent.com/3112191/100102615-23f81400-2e64-11eb-8ad7-2bd0016e79d1.png)

Where is the white design, please? I only see this. The white color is on hover only.

![image](https://user-images.githubusercontent.com/3112191/100102594-1cd10600-2e64-11eb-8fa9-62a5cbbaba98.png)

**Comment by martinboehm** [comment]
Majority done in various PRs, the rest is obsolete.
