### ISSUE TITLE
Exchange - Account with 0 balance allowed for an ERC20 transaction

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#3023]
**Describe the bug**
ETH account with 0 balance is allowed for and ERC20 transaction. 

**Info:**
Suite Version: web, commit 43328cfdf47e74c53d385b7f453de5affbc3f8fe
Browser: Chromium 85
OS: NixOS 20.09
Firmware Version: 2.3.4 public 50854b921

**Steps to reproduce:**
1. Go to Accounts > Trade > Exchange
2. Set exchange for an ERC20 token 
3. Set the receiving ETH account to one with 0 balance

**Expected result:**
An acount with 0 ETH balance is not allowed for an ERC20 transaction.

**Actual result:**
Accounts with 0 ETH balance are allowed for an ERC20 transaction.

![image](https://user-images.githubusercontent.com/58593111/99709357-5fc75e00-2a9f-11eb-8a69-a8df9712b532.png)

![image](https://user-images.githubusercontent.com/58593111/99709388-67870280-2a9f-11eb-88d2-bc140075703f.png)

**Comment by martinboehm** [comment]
I do not see this as a problem. While the user will have to send some ETH to the account for manipulation of the tokens, it can be any time later.

**Comment by sorooris** [comment]
@martinboehm shouldn't we at least inform the user that _some_ ETH balance is needed for later token manipulation? 
@matejzak @tsusanka please advise

**Comment by tsusanka** [comment]
I think we do not have to worry about this. The user will find out pretty soon after that they need some ETH to manipulate the token. I don't see big advantage of informing them beforehand and we are a bit worried about "UI hell" where you confirm one dialog after another.

I am closing and let's see if @matejzak has another opinion. Thanks for bringing it up though, good catch!
