### ISSUE TITLE
Exchange - Web page title says Coinmarket and not Trade

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3031]
**Describe the bug**

Please see screenshots.
When you proceed with your coin trade 
Web page title changes from `Trade | Trezor Suite` to `Trezor Suite | Coinmarket | Trezor Suite`

**Info:**
 - Suite Version: web, commit 964237f8458a96b9b719771582521bcbc6b78cf5
 - Browser: Firefox , version 82
 - OS: Nixos
 - Firmware Version: 1.9.1 model One

**Steps to reproduce:**
1. load Suite with Exchange enabled 
2. Proceed with exchange 
3. Observer tab/page header changing from Trade to Coinmarket

**Expected result:**
Web page title of Suite location matches Suite feature /Buy,exchange.../

**Actual result:**
Suite Web page title says Coinmarket 

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/99803330-8c2fb880-2b39-11eb-9969-0e1cfafd2a8f.png)

![image](https://user-images.githubusercontent.com/31506317/99802309-c8621980-2b37-11eb-8fc8-0f028aa715e1.png)

**Comment by martinboehm** [comment]
Fix is already in progress in #3021
