### ISSUE TITLE
Fw update - fingerprint

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#3036]
It used to work but is broken now

- Modal redurer reacts to the corresponding button request 
- modal component does not havy any corresponding view for this button request
- Fingerprint component is rendered but overlayed by empty modal.

**Comment by sorooris** [comment]
**QA OK**

Verified the presence of a fingerprint comparison in firmware update modal during incremental update.

Suite | Device
------------ | -------------
![image](https://user-images.githubusercontent.com/10185314/101613957-a4924500-3a0c-11eb-9132-b23f8dfad332.png) | ![image](https://user-images.githubusercontent.com/10185314/101614245-00f56480-3a0d-11eb-99ba-4b89d376ffc7.png)





Suite: app 20.12.1 be4e3a3
OS: macOS Big Sur 11.0.1
Device: model 1 no fw
