### ISSUE TITLE
Exchange - custom fee in ETC exchange is always zero

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#3043]
**Describe the bug**

In exchange from ETC to another coin, when fee is changed to custom and the amount is altered, suite will always mark it as zero FIAT/ETC amount instead of the actual cost. These transaction then cannot be (most likely, ETC cannot be traded right now) completed, as fee is set to zero.

**Info:**

Suite Version: web staging 964237f8458a96b9b719771582521bcbc6b78cf5
Browser: Firefox 82
OS: NixOS 21.03
Firmware Version: 2.3.4 public

**Steps to reproduce:**

**1.** Go to ETC Accounts > Trade > Exchange
**2.**  Fill out Exchange form
**3.** Change fee to custom, alter amount

**Expected result:**

Custom fee amount will be properly set.

**Actual result:**

Custom fee amount is always marked as zero.

![image](https://user-images.githubusercontent.com/58593111/99911699-83d0ac80-2cf6-11eb-8c8f-0bd219f03b38.png)

**Comment by martinboehm** [comment]
I think this has been already fixed together with #3020.

**Comment by vladimirvolek** [comment]
Already fixed in develop.

**Comment by wendys-cats** [comment]
**QA OK**

**Suite** web develop ac55c97
**Browser** Chromium Version 86.0.4240.111 (Official Build) (64-bit)
**System** NixOS 21.03
**Device** T1 1.9.3 public


![image](https://user-images.githubusercontent.com/58593111/100376463-dcae8680-300f-11eb-9374-4942719c54df.png)
