### ISSUE TITLE
Exchange - Cannot trade ETC for other coins

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#3044]
**Describe the bug**
ETC cannot be exchanged for any other coin. 
After Exchange form has been filled, Suite fetches offers and redirects user to page where every single exchange offer is inactive with error notifications "_Cannot trade pair ETC-COIN"_ , _"Invalid currency: etc temporary disabled"_ and _"No response from exchange."_ 
Console shows no errors when fetching offers. 

**Info:**

Suite Version: web staging 964237f
Browser: Firefox 82
OS: NixOS 21.03
Firmware Version: 2.3.4 public

**Steps to reproduce:**

**1.** Go to ETC Accounts > Trade > Exchange
**2.** Fill out Exchange form
**3.** Continue to Compare offers

**Expected result:**

ETC can be exchanged for other coins.

**Actual result:**
ETC cannot be exchanged for any other coin. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/58593111/99913493-584ec180-2cf8-11eb-930a-d02e1bff0c79.png)

![image](https://user-images.githubusercontent.com/58593111/99913511-67ce0a80-2cf8-11eb-9d59-3897d3a8a005.png)

![image](https://user-images.githubusercontent.com/58593111/99913520-75839000-2cf8-11eb-81de-ae6413ea0247.png)

![image](https://user-images.githubusercontent.com/58593111/99913539-8b915080-2cf8-11eb-937e-1bf820cd24bf.png)

![image](https://user-images.githubusercontent.com/58593111/99913559-a4016b00-2cf8-11eb-8586-3484c82a13c9.png)

**Comment by martinboehm** [comment]
This is not a bug. Currently none of our partners is willing to do any ETC trade. I assume it is because there were deep rollback attacks on ETC.
