### ISSUE TITLE
Exchange - Custom Fee does not load correctly

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#3046]
**Describe the bug**

Custom fee in exchange is not loaded correctly. When custom fee ich changed and only ONE digit is filled in the CustomFee Input, FIAT and COIN amount of fee will stay at zero. Suite will calculate FIAT/COIN custom fee amount only after a second digit is added (can be seen on [video](https://drive.google.com/file/d/1EoP2iT6kA_akNZcUUtmVABBmg26qgoQw/view)).

Not only that, but Suite will let Compare offeres button enabled if Exchange form is filled in, regardless if fee is displayed as zero. When Suite is fetching offers, correct fee is displayed (see [video](https://drive.google.com/file/d/16QaOYIO5_PbXDAFSfZzWocfPgIVI6fBA/view)).

Tried on BTC and BTG. Seems like a universal custom fee problem. 

**Info:**
Suite Version: web [staging](https://staging-wallet.trezor.io/) 964237f
Browser: Firefox 82
OS: NixOS 21.03
Firmware Version: 1.9.3 public

**Steps to reproduce:**
**1.** Go to Accounts > Trade > Exchange
**2.** Fill in Exchange form
**3.** Choose custom fee and fill in a single digit

**Expected result:**
Suite will calculate AND display custom fee immediately and correctly. 

**Actual result:**
Custom fee in exchange is not loaded correctly.

**Screenshots:**

**Change from Low fee to Custom fee WITHOUT entering any amount into CustomFee Input**
![image](https://user-images.githubusercontent.com/58593111/99920783-150b4780-2d26-11eb-8c91-02acecc8ed0e.png)

**Single digit entered into CustomFee Input**
![image](https://user-images.githubusercontent.com/58593111/99920796-32d8ac80-2d26-11eb-9911-e35e3110063d.png)

**Compare offers enabled with (seemingly) zero fee**
![image](https://user-images.githubusercontent.com/58593111/99920859-b98d8980-2d26-11eb-96d8-ebec3fdbdeb4.png)

**Comment by vladimirvolek** [comment]
Same as https://github.com/trezor/trezor-suite/issues/3043.
Should be fixed by https://github.com/trezor/trezor-suite/pull/3028.
