### ISSUE TITLE
Exchange - Suite does not offer ETH accounts for receiving TUSD or USDT

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#3047]
**Describe the bug**
Suite does not offer ETH accounts for receiving TUSD or USDT, even though Suite shows both among other tokens. 

**Info:**
Suite Version: web staging 964237f
Browser: Firefox 82
OS: NixOS 21.03
Firmware Version: 1.9.3 public

**Steps to reproduce:**
**1.** Go to ETH Accounts > Trade > Exchange
**2.** Fill in Exchange form
**3.** Choose TUSD or USDT
**4.** Continue to Receive address part

**Expected result:**
Suite will offers ETH accounts for TUSD receiving address and USDT address.

**Actual result:**
User has to manually get ETH receive address and use it to get TUSD or USDT.

**Screenshots:**
![image](https://user-images.githubusercontent.com/58593111/99921214-29047880-2d29-11eb-8ad8-0299fb5d045b.png)

![image](https://user-images.githubusercontent.com/58593111/99921243-6537d900-2d29-11eb-8ed6-8cea4ca7bc2b.png)

**Comment by martinboehm** [comment]
1) USDT is OMNI not ERC20 token, you cannot use ETH account for it. If you want to trade ERC20 version of USDT, you have to choose USDT20. We know that it is confusing, we are preparing with product some solution how to make it clearer
2) TUSD - lives on BNB and ETH blockchains. It is fixed now by switching it from BNB blockchain to ETH.

**Comment by martinboehm** [comment]
I think there is a related issue https://github.com/trezor/trezor-suite/issues/3389. When that issue is resolved, we can close both.

**Comment by tsusanka** [comment]
#3389 seems resolved. I will close and QA will retest.

**Comment by sorooris** [comment]
**QA OK**

ETH account offered correctly when exchanging TUSD.

![image](https://user-images.githubusercontent.com/10185314/108222855-7716f580-7139-11eb-8ad4-09d0d95296d3.png)

Suite Version: app 21.2.3 9cf47b5
OS: macOS Big Sur 11.2.1
Bridge: 2.0.27
Firmware Version: model T 2.3.6 b19cbf67c
