### ISSUE TITLE
Image in fw update needs improvements in a dark mode

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3048]
![image](https://user-images.githubusercontent.com/31506317/99954507-2e8eac80-2d83-11eb-9474-764f85b37b28.png)

**Comment by bosomt** [comment]
![image](https://user-images.githubusercontent.com/31506317/99954815-a066f600-2d83-11eb-8ba2-aafa4ee7bd2a.png)

**Comment by bosomt** [comment]
![image](https://user-images.githubusercontent.com/31506317/99954866-b379c600-2d83-11eb-95a6-6622e84bd21f.png)

**Comment by slowbackspace** [comment]
I've fixed the select component. Image on first screenshot will need someone more skilful in vector graphics. I'll change the title to better describe the the leftover issue.

**Comment by bosomt** [comment]
![image](https://user-images.githubusercontent.com/31506317/100109231-eac3a200-2e6b-11eb-9de3-9994f1967c0d.png)

@slowbackspace

**Comment by bosomt** [comment]
![image](https://user-images.githubusercontent.com/31506317/100126101-d5f00a00-2e7d-11eb-86d6-01d3fa6c08d0.png)

**Comment by bosomt** [comment]
edit: already fixed in master
