### ISSUE TITLE
Cypress dependency

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#305]
Cypress dependency is listed inside components storybook package here https://github.com/trezor/trezor-suite/blob/cba48b66484f39a8f7aa9cfc60994ebbb69c616c/packages/components-storybook/package.json#L53

But it is used by more packages, eg components-storybook, suite-web, etc.

shouldnt it be listed either in global package.json or verbosely in every project using this dependency?

**Comment by slowbackspace** [comment]
I like the second option, adding cypress as a dep to every package.json that use it (imo version across packages could be easily the same with lerna). From my pov packages should still work even if they are outside of monorepo. But we already have maintenance-like deps (eslint, prettier) as global deps and I know that some articles recommend this approach 🤷‍♂️
