### ISSUE TITLE
Persistent browser storage data on desktop

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#3062]
When the app updates, browser data (IndexedDB and LocalStorage) get lost. We should save them on disk and re-apply them when the app is opened again.

**Comment by keraf** [comment]
Did some more testing, I believe this was a false positive due to testing configuration. Closing issue.

**Comment by tsusanka** [comment]
This is happened to me as well when updating from "[fake" 20.9.0](https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/221686375) to 20.10.0. So do you think this will not happen for the newer versions?
