### ISSUE TITLE
Account: Empty states

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3065]
[**Zeplin**](https://zpl.io/brDGlX7) 

- Add the empty account state to all (empty) accounts
- The notification goes to empty Bech 32 accounts only, and is close-able via `Got it!`. The empty state box is to then move up to replace the notification.

**Comment by wendys-cats** [comment]
**QA OK**

**Suite** web develop ac55c97
**Browser** Chromium Version 86.0.4240.111 (Official Build) (64-bit)
**System** NixOS 21.03
**Device** TT 2.3.4 public + T1 1.9.3 public
