### ISSUE TITLE
Add "Ripple" keyword to account selection

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-suite#3071]
**Is your feature request related to a problem? Please describe.**
In the account menu you can add XRP but the selection menu does not say "Ripple" and also if you type the coin's name in, "XRP" keyword works, but "Ripple" won't show any result -> seems that Ripple is not supported

Ripple is the name of the system and XRP is the currency so technically this seems to be correct but CX-wise I'd add "Ripple" keyword, as well as this, is simply the name that's used by many users

**Describe the solution you'd like**
When typing coin's name "Ripple" keyword would show XRP as an option. Also I'd add "Ripple" to the name of currency as well 
- Ripple (XRP) or XRP (Ripple)

Screenshot:
https://imgur.com/a/PEcqlbR

**Comment by slowbackspace** [comment]
related issue, why are we not allowing to search for coin by typing its symbol? 🤔 

<img width="783" alt="Screenshot 2020-11-27 at 14 25 54" src="https://user-images.githubusercontent.com/6961901/100454078-7cc1e980-30bc-11eb-80b1-8bb37ece64bb.png">

**Comment by yohaaan** [comment]
@slowbackspace good point +1 on that

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.1.0 (a2ce5af90175100892a5c5f2d01fec3e5adf7220)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.3 regular
