### ISSUE TITLE
Pink Mode

### ISSUE THREAD

**Issue by Chytrazenacz** [trezor/trezor-suite#3072]
Hi, as you've already implemented [Dark mode](https://github.com/trezor/trezor-suite/issues/2738) and as we (http://www.chytrazena.cz/) do have an ongoing marketing partnership with Trezor, it would be nice if you could bring a pink mode that would match our site's color (#FFD3DF). I believe that our readers would really appreciate the possibility to have Trezor Suite in their favorite CW especially those lucky ones who are going to win Pink Trezor in our giveaway.

We've also came up with some name ideas:

- Pink Mode
- Chytrý Mode (Clever Mode)

I'm attaching a design preview, I think it looks fabulous 💘

![suite_pink_mode](https://user-images.githubusercontent.com/75077898/100353000-1ec6d080-2fee-11eb-856f-f70a2c332b78.png)

**Comment by slowbackspace** [comment]
Say no more. I have a dark mode prototype ready for quite some time already.

![image](https://user-images.githubusercontent.com/6961901/100353977-ac56f000-2fef-11eb-9e85-16ea7e2dd9b0.png)

**Comment by prusnak** [comment]
Stokrat opakovany vtip prestava byt vtipom
