### ISSUE TITLE
Windows: autoupdater uses the installation wizard

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3079]
**Describe the bug**
During the autoupdate Suite shows the installation wizard which is quite confusing.

**Info:**
 - Suite Version: desktop, commit 8b5c9b45, which is ac55c97a1e017226e61e340d93b2e7e26b00a0f3 with a version downgrade
 - OS: Windows 10
 - Firmware Version: T1, 1.9.4 (to be confirmed)

**Steps to reproduce:**
1. Install "fake" 20.9. version from [Gitlab](https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/875747218).
2. Go through the autoupdate.

**Expected result:**
Installation wizard is displayed.

**Actual result:**
Installation wizard should not be displayed.

**Screenshots:**
Video: https://drive.google.com/file/d/1TXOTVDFT09NiZM0VQgjQolM7Y3snNZQG/view?usp=sharing

**Comment by prusnak** [comment]
I guess this is expected, since we publish only .exe artefact which is an installer.

Just thinking out loud: if we re-enabled ZIP artefact for Windows, would that do the trick and update like on Mac? My guess is that this does not work that easily ... Maybe @keraf knows more

**Comment by tsusanka** [comment]
As discussed with @keraf this [might](https://github.com/trezor/trezor-suite/commit/f71a2f78a6c372ae98ffbfafa154382e5dd06059) fix it. Will test.

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezor-suite/commit/b6aca16166b3cfc0dd4d89e205b39792e937819c

**Comment by tsusanka** [comment]
Tested by me, works.

**Comment by sorooris** [comment]
**QA NOK**

Restarting app after autoupdate triggers an install wizard.

Suite: app 21.6.2
OS: NixOS 21.05, Win10 19042.1052
Bridge: 2.0.31
Device: model T 2.4.0

**Comment by prusnak** [comment]
The silent behaviour was reverted in 73bf160cbfe9c869815cbe941efede72554f91d7 which was part of PR https://github.com/trezor/trezor-suite/pull/3224

Not sure what was the reason for that, because the commit message does not say anything about it. Maybe it was an attempt to fix https://github.com/trezor/trezor-suite/issues/3203 ?

**Comment by tsusanka** [comment]
Yeah I believe so but I guess we can try again. However, I would like this assessed this first from Product whether we really should deal with it, for example @STew790 mentioned it did not seem _that_ weird to him and that he saw it in other apps. @stepmes have you seen this in the user feedback by any chance?

**Comment by stepmes** [comment]
@tsusanka I haven't seen this in the user feedback so far. It might be worsening the user experience, but perhaps not as much that someone would take the time and energy to report it to us.
