### ISSUE TITLE
Not able to send DASH via 2.3.5 FW

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3083]
**Describe the bug**

When trying to send DASH transaction in Trezor suite you will see this error:
`Sign transaction error: Failed to decode message: Required field 'amount' was not received`
other coins including Bitcoin are working fine.
This error is displayed before anything is signed via device.

**Info:**
 - Suite Version: app + web, commit 20.12.0 + 716af2f4a24a32aa801027d915269f6ce59733c8
 - Browser: Firefox 
 - OS: Nixos + Windows
 - Firmware Version: 2.3.5 model T, revision 1c28a57

**Steps to reproduce:**
1. Connect device with 2.3.5 FW and load DASH accounts
2. try to send transaction between accounts
3. observer error

**Expected result:**
You are able to sign transaction.

**Actual result:**
You will get error before you are able to sign transaction.

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/100451201-4b92ea80-30b7-11eb-8984-ed190dde8057.png)

**Comment by bosomt** [comment]
same problem with DOGE and NMC/Name coin

**Comment by tsusanka** [comment]
@bosomt could you retry on old wallet please?

**Comment by bosomt** [comment]
@tsusanka same problem with same FW/device

wallet commit 98bf3eb12c1d85029310448e24ba4d88b312cb7c

![image](https://user-images.githubusercontent.com/31506317/100594426-f5fa5000-32f9-11eb-9b70-c366e6385803.png)

![image](https://user-images.githubusercontent.com/31506317/100594655-407bcc80-32fa-11eb-9f2b-1c813b597e43.png)

**Comment by tsusanka** [comment]
@bosomt could you please open an issue at mytrezor as well? Linking this issue and providing these screenshots is enough.

**Comment by bosomt** [comment]
@tsusanka :+1:

**Comment by tsusanka** [comment]
@bosomt could you please retest on 20.12.1 (current freeze, https://github.com/trezor/trezor-suite/commit/78c9fd3b1ab100fea33c1b63256deae31b64840e) with the very same FW.

**Comment by bosomt** [comment]
**QA OK**

Windows 10
Suite app commit 78c9fd3b1ab100fea33c1b63256deae31b64840e
Device FW 2.3.5 commit 1c28a57

https://doge1.trezor.io/tx/0c9cfeac97fefa4a244bc6b502a3cfc9f3ee02102772ec263e5314e23fc6efcd
https://nmc1.trezor.io/tx/8851a738a617812568d105aa46d848614ed7eccfac15d66c262a199a137e867d
https://dash1.trezor.io/tx/a0f2d1d8657144c2049e5b6090d79986c98a99fc932e88390bc5ab9442a94548

**Comment by bosomt** [comment]
**QA OK **

https://dash1.trezor.io/tx/a3fc6fb6e15b864af9f4bac7d96f00c02482aa8ef83f68a4f31e26c8dc393eb4

Nixos
Firefox 82.0.3 (64-bit)
Suite web dev master commit f93bd32
Device 2.3.5
