### ISSUE TITLE
Coin not supported

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#3085]
When a Coin is not supported on the device, this is shown:

![En1bXQKW4AEdzp-](https://user-images.githubusercontent.com/42201/100467292-80f90180-30d2-11eb-87c2-3e7e7f3ebc26.jpg)

I think we should explain why the coin is not supported ("This coin is supported only on Trezor Model T"). This has potential to up-sell Model T even.

The other option would be to hide the element if the coin is not supported, so it would not confuse.

**Comment by slowbackspace** [comment]
just few days ago @robertbrada mentioned it too! We discussed we could add a tooltip explaining what's happening and maybe a link to trezor.io/coins. @matejzak let's make it happen!

**Comment by jerechinsky** [comment]
@slowbackspace If the user has a model one, please replace the "Not supported" string with "Available on Model T".

**Comment by glacierbits** [comment]
@alex-jerechinsky Can you please update this copy via Crowdin? Thanks!

**Comment by jerechinsky** [comment]
@matejzak Sorry! I forgot to mention that this string involves logic that checks if a **particular coin** is supported by the device's **firmware** and **not the device** itself. I.e. users with model T and btc-only firmware see it next to each coin except btc. So I asked @slowbackspace to implement another conditional that would check for the device model itself, so we know for sure that the user is on model one.

**Comment by glacierbits** [comment]
No worries @alex-jerechinsky Thanks for taking care of it!  ☺️

**Comment by slowbackspace** [comment]
@alex-jerechinsky It took me so long, sorry! It looks kinda weird but meh.

<img width="1172" alt="Screenshot 2021-02-15 at 18 15 30" src="https://user-images.githubusercontent.com/6961901/107976481-ea91f900-6fb9-11eb-9994-beaf13679c43.png">

**Comment by jerechinsky** [comment]
@slowbackspace Looks good to me! Thanks. 🙂

**Comment by bosomt** [comment]
Maybe we can consider to change this modal too when on it ? 
@prusnak @slowbackspace  do you want me to create separate issue ? 

![image](https://user-images.githubusercontent.com/31506317/109161500-6b4db380-7777-11eb-8cd6-8c3de00cfd2c.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.3.0 (a5de8753d2e8a16b1217edb644c7414d176948cc)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Comment by slowbackspace** [comment]
> Maybe we can consider to change this modal too when on it ?
> @prusnak @slowbackspace do you want me to create separate issue ?
> 
> ![image](https://user-images.githubusercontent.com/31506317/109161500-6b4db380-7777-11eb-8cd6-8c3de00cfd2c.png)

ohh here it would make even more sense! pls issue, we will improve it for the april release 😓
