### ISSUE TITLE
Bitcoin Cash fork - change wording or remove notification

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3094]
**Describe the bug**
Please change wording or remove notification of BCH fork from suite.

**Info:**
 - Suite Version: web, commit 0dd2b515fba0ae875878d3e2a17ff8b89d512c42
 - Browser: Firefox , version 82.0.3 (64-bit)
 - OS: Nixos
 - Firmware Version: 1.9.3 model One , revision 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,

**Steps to reproduce:**
1. Start any version of suite
2. Load BCH accounts
3. Check notification

**Expected result:**
Notification is removed or timing is changed to past tense

**Actual result:**
Suite says: `Bitcoin Cash will undergo a contentious fork on the 15th of November 2020,`

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/100582681-e541de00-32e9-11eb-8c1c-80e6c312a593.png)

**Comment by prusnak** [comment]
I think we can just remove the notification - PR https://github.com/trezor/trezor-suite/pull/3095

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox
Suite web dev master commit 3cfa1ae56f61635c77e4046a76577bfd027fb05e
Device fw 2.3.5 model T
