### ISSUE TITLE
landing-page (for closed beta) is broken on sldev

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3096]
Looks like resources are not deployed correctly as it happens in every branch I tried.

<img width="1473" alt="Screenshot 2020-11-30 at 11 24 27" src="https://user-images.githubusercontent.com/6961901/100598214-b7b35f80-32fe-11eb-934e-45e28fac4adf.png">

**Comment by mroz22** [comment]
It happens even on deployments from October so none of the recent changes to CI configuration are to be blamed.
