### ISSUE TITLE
Export transactions - design is missing pdf file header 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3097]
**Describe the bug**
Can you please add Trezor logo account and coin name to pdf files that's generated from transaction history ?

https://github.com/trezor/trezor-suite/issues/2085

**Info:**
 - Suite Version: web, commit 3cfa1ae
 - Browser: Firefox, version 82.0.3 (64-bit)
 - OS: Nixos
 - Firmware Version: 2.3.5 model T

**Steps to reproduce:**
1. export transaction history to pdf via Suite
2. export transaction history to pdf via mywallet
3. compare pdf files

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/100609540-7460ed00-330e-11eb-8851-96600743b8ae.png)

**Comment by glacierbits** [comment]
Good point @bosomt, thanks!

@keraf Can you please also add the `labeled` account name if possible / worthwhile? To recap, please add: 

- Default label .e.g. `Account #1 ` 
- Custom label e.g. `Savings` 
- Crypto abbreviation all caps  
- Trezor Suite logo 👇🏽 

![Group 26 10@3x](https://user-images.githubusercontent.com/29627086/101204073-f2552900-366b-11eb-9fa8-4432d718d40b.png)

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox
Suite dev web master commit 60aa1920b46d9d9a75ee4254c410694d175b4157
1.9.5+2.3.5 RC2
