### ISSUE TITLE
Search transactions 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3106]
[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f5208531549bf4b24ebdb88)

**Comment by jerechinsky** [comment]
Merged #3217

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.1.0 (9ae82af375cea195a84fec664b387c461b2df1ae)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.1.0 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular

**Comment by bosomt** [comment]
is it possible to disable ctrl+f shortcut in app when modal is opened ? 
See gif file. When you try to seach in modal search dialogue in tx history is open/
If not please close issue.


![Peek 2021-01-22 16-19](https://user-images.githubusercontent.com/31506317/105509502-d9610f80-5ccd-11eb-9f81-86acc3c6dc10.gif)

**Info:**
 - Suite version: desktop 21.1.0 (e31cc2b2c0388e1b50f3f8fd529bc47d7e00fbef)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.1.0 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular

**Comment by keraf** [comment]
Nice find :slightly_smiling_face: I'll get a fix for that shortly.

**Comment by tsusanka** [comment]
@keraf this still needs some work or is not closed by accident?

**Comment by keraf** [comment]
I guess it can be closed as the main task is done. It was re-opened by @bosomt as there was a minor bug found but it's a non-blocker imo. I created a new issue from his comment: #3304

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.1.0 (93c2576e8a22b770241222de191c1508c595821c)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
