### ISSUE TITLE
Improvements on date range picker

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#3108]
Few improvement suggestions for the date range picker:
- Go to month/year by clicking on the header (where the month and year is displayed).
- Display the dates in the user's local format (or based on preferences).

**Comment by glacierbits** [comment]
A few more ideas: 

- Consider increasing the minimum touch target slightly around the chevrons `‹ Month YEAR ›` 
- Display the dates by default in the same format as below the graph and elsewhere in the app, e.g. `Dec 12, 2020`

**Comment by tomexx** [comment]
I replaced the underlying datepicker library and implemented mentioned ideas/improvements. Regarding `from/to` input fields I've kept the default lib's locale (en-US) so the date format should now match dates in other places of Suite. I could have added more locales, but every other locale would increase the bundle size so I'd keep it like this at least for now.

**Comment by bosomt** [comment]
** QA OK**

**Info:**
 - Suite version: desktop 21.4.0 (d8afa44f141e1ae678cc89d8dda758b790888c06)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular
