### ISSUE TITLE
Reset app button doesn't wipe app storage

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3116]
**Describe the bug**
When you press `Reset app` in app, app is restarted but storage is not wiped. Suite doesn't show splash screen, Doesn't change to white mode and saved and loaded wallets are remembered.

**Info:**
 - Suite Version: app, commit 78c9fd3b
 - OS:  Nixos + Windows
 - Firmware Version: 1.9.3 model One commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,

**Steps to reproduce:**
1. Download staging app
2. Start it, change settings, load wallets
3. Press `Reset app` and observe

**Expected result:**
All suite data are wiped

**Actual result:**
Probably no suite data are wiped

**Screenshots:**
![wipe](https://user-images.githubusercontent.com/31506317/101013267-512f7b00-3564-11eb-8e35-f58c06fe6d1f.gif)

**Comment by slowbackspace** [comment]
😮  macOS works again, we should give free mac with every trezor!

**Comment by slowbackspace** [comment]
@wendys-cats's windows also works fine even though it seems she doesn't want to admit it publicly! this is gonna be something weird 😁  anyone wanna help test this?
Steps:
1. load suite (electron app, staging version to keep it scientific enough) with device connected, hit remember wallet
2. disconnect device
2. click on clear storage btn in Settings
3. do you see onboarding (thus storage was cleared) or you are back to your remembered wallet?

**Comment by wendys-cats** [comment]
@tsusanka I waited to see if it will happen, but no luck. 

Looks like @bosomt is the one with weird bugs this release (I had the horrible error situations last time).

**Comment by bosomt** [comment]
**QA OK**

I was not able to reproduce this issue anymore

**Info:**
 - Suite version: desktop 21.4.0 (ab673f9777b6ddaf13234e5e6b3b3ab5be46852c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model One 1.9.3 regular
