### ISSUE TITLE
Exchange - does not work for undiscovered accounts?

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3123]
**Describe the bug**
It seems to me I can't exchange to a coin that has not been previously discovered. The address does not get pre-filled and I can't continue.

**Steps to reproduce:**
1. Go to exchanges
2. Select a coin that you have not discovered yet and has Suite support (such as an empty altcoin account)
3. Create a new account
4. Unable to continue?

**Info:**
 - Suite version: web 20.12.1 (78c9fd3b1ab100fea33c1b63256deae31b64840e)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Expected result:**
I can continue with the operation.

**Screenshots:**
![c](https://user-images.githubusercontent.com/1835345/101144345-7978b180-3618-11eb-9b01-c51403e97224.gif)

**Notes:**
I am afraid this is critical enough to cherry-pick into the release.

Cc @trezor/qa. Could you retest on Chrome?

**Comment by sorooris** [comment]
**QA OK**

Previously _NOK_ in Chromium, now _OK_.

Suite: app e16f9ff, web 78c9fd3
OS: macOS Big Sur 11.0.1, NixOS 20.09
Device: model T 2.3.4 public
