### ISSUE TITLE
Select's options background on focus

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3125]
clicking on an option makes it light blue.
clicking on a preselected option makes it darker blue.

Let's keep the same style as we use on hover to not complicated things more than necessary.

![image](https://user-images.githubusercontent.com/6961901/101149231-e98a3600-361e-11eb-8493-5a4e01387133.png)
![image](https://user-images.githubusercontent.com/6961901/101149239-ed1dbd00-361e-11eb-8160-57ade292ca5e.png)

**Comment by bosomt** [comment]
**QA OK**

Nixos
Firefox 82.0.3 (64-bit)
Suite web dev master commit f93bd32
Device 2.3.5
