### ISSUE TITLE
Transaction graph range misleading 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3127]
**Describe the bug**

Looks like new range in graph is casing issue in ALL transactions view. See screenshots.
There is 50+ transactions in this account this year and current balance is 1642.39409405 DOGE
Previous version 20.12.0 OK /without range / ok  https://github.com/trezor/trezor-suite/commit/ffa20e9fd792abc2a55fa9fec8402044e204a911

**Info:**
 - Suite Version: app, commit 78c9fd3b
 - OS: Windows 10
 - Firmware Version: 1.9.3 model One

**Steps to reproduce:**
1. load latest version of suite
2. load accounts and change graph to all
3. observe

**Screenshots:**
![Screenshot 2020-12-04 115508](https://user-images.githubusercontent.com/31506317/101155936-260e5f80-3628-11eb-89a1-e724551512b0.png)
![Screenshot 2020-12-04 115526](https://user-images.githubusercontent.com/31506317/101155940-27d82300-3628-11eb-8d72-b9cbad7d2e6f.png)
![Screenshot 2020-12-04 115552](https://user-images.githubusercontent.com/31506317/101155941-27d82300-3628-11eb-9223-ca27129204e6.png)

**Comment by bosomt** [comment]
After reinstalled and wiped app data it's not happening anymore. 
Hard to say how to trigger it again.

**Comment by bosomt** [comment]
Looks like problem with time zones

I just sent tx and changed timezone.
It looks like this now

![image](https://user-images.githubusercontent.com/31506317/102089341-5b7f2e00-3e1c-11eb-9052-a850af34da1d.png)

xpub vpub5YX1yJFY8E236pH3iNvCpThsXLxoQoC4nwraaS5h4TZwaSp1Gg9SQoxCsrumxjh7nZRQQkNfH29TEDeMvAZVmD3rpmsDnFc5Sj4JgJG6m4b


Nixos app
Suite commit be4e3a36f7dbe15b2b203f66de11edc50a6665b8
Device model T fw 2.3.5

**Comment by bosomt** [comment]
same wallet after i change timezone to CET
range is set to all but only shows 6 tx 

![image](https://user-images.githubusercontent.com/31506317/102090692-0fcd8400-3e1e-11eb-9652-1d70f83734d5.png)

**Comment by tomexx** [comment]
Is this still valid?

**Comment by bosomt** [comment]
I don't think so ;)
I was not able to reproduce any kind of graph issues for some time.
Closing

**QA OK**
