### ISSUE TITLE
Labeling Dropbox and Google Drive never connects in app

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3130]
**Describe the bug**
Labeling storage to  Dropbox and Google Drive is never established in application.
Browser connection is successful and it asks you to to close browser window
But app waits forever. When you close modal nothing changes and labeling is still disabled.

Works fine in Firefox browser

**Info:**
- Suite Version: app, commit 78c9fd3
- OS: Windows 10 + Mac OS
- Firmware Version: 1.9.3 model One

**Steps to reproduce:**
1. Start Suite and enable labeling
2. Connect to Dropbox or/and Goodle Drive
3. Observe 

**Expected result:**
Connection to external storage is established.

**Actual result:**
Connection to external storage is never established

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/101178703-9d082000-3649-11eb-9f62-d15cafa7969d.png)

**Comment by tsusanka** [comment]
Replicated :(. Same commit and on both Windows 10 and my NixOS.

**Comment by bosomt** [comment]
**QA OK**

Suite app commit be4e3a36f7dbe15b2b203f66de11edc50a6665b8
Windows 10
Device 1.9.3 public version
