### ISSUE TITLE
Sell all button fills ETH balance when trying to exchange some ERC20 tokens

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3140]
**Describe the bug**
Sell all button fills ETH balance when trying to exchange some ERC20 tokens.
Even when you fill it out manually it won't accept them. Please see video.
USDT20 works fine, TUSD a USDC not.

**Info:**
 - Suite Version: app + web, commit e16f9ff
 - Browser: Chromium + app
 - OS: Nixos + Windows
 - Device model One FW 1.9.3

**Steps to reproduce:**
1. start suite and load accounts with ERC20 tokens
2. try to exchange them for other coins, press  all or fill value manualy
3. observe

**Expected result:**
All ERC20 tokens amounts are filled corectly

**Actual result:**
Some ERC20 tokens balances ale mixed with ETH balance

**Screenshots:**
https://www.youtube.com/watch?v=1zFGNVmSxXA&feature=youtu.be

**Comment by bosomt** [comment]
two nitpicks, are they worth fixing ? @martinboehm 

1) there is too many zeros filled when i press all, it looks strange ;)
![image](https://user-images.githubusercontent.com/31506317/101456366-3bd79980-3934-11eb-9fb6-b5cbcd4bc426.png)
![image](https://user-images.githubusercontent.com/31506317/101456406-47c35b80-3934-11eb-8be4-54a57849e4ab.png)

2) when I change token it says `Not enough funds` because value from previous token is used. after i press all button value is changed to correct value
![image](https://user-images.githubusercontent.com/31506317/101456843-ecde3400-3934-11eb-9625-a1726472e236.png)

**Comment by tsusanka** [comment]
@bosomt please open a new issue, we are already signing so this will have to go to the next release.
