### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3149]
### 🚀   New features

- Dark mode 
- Exchange (crypto to crypto)
- Time range in graphs 
- Export transactions 
- Labeling: Google Drive sync

### 🎨 Improvements 

- Account empty state (3D) 
- Send form and labeling UI 
- Device dis/connected animation
 
.. and much more!

**Comment by prusnak** [comment]
Created a release here and the changelog is copy-pasted there: https://github.com/trezor/trezor-suite/releases/tag/v20.12.1

Closing the issue
