### ISSUE TITLE
Device setting overhaul

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#3150]
As discussed with @andrewkozlik, it would be great to have an easier way to maintain device settings displayed in Suite so we can match the ones available in `trezorctl`. The idea would be to have a configuration file (JSON most likely) with setting definitions that would then be rendered on that page.

Some of the missing settings in suite currently are:
- Set U2F counter
- Set wipe pass code
- Enable SD protect

The definition file should contain the following data:
- Setting name
- Setting type (boolean, string, values, ...)
- Setting values (optional)
- Validation (if string)
- Firmware requirements

In order to make this task easier, we should consider the refactor of `trezor-link` first (#2923). This is because some of the new settings require new protobuf definitions.

**Comment by andrewkozlik** [comment]
Links to wiki:
- https://wiki.trezor.io/User_manual:Wipe_code
- https://wiki.trezor.io/Using_trezorctl_commands_with_Trezor#Safety-checks
- https://wiki.trezor.io/SD_card_protection
- `trezorctl fido counter set {COUNTER}`

The definition file should also contain flags indicating whether the given setting is applicable to T1-legacy, T1-core (this doesn't exist yet) and TT-core and whether it's applicable to BTC-only firmware. For example, the U2F counter wouldn't be applicable to BTC-only.

The definition could also contain a description (e.g. tooltip) providing more information, or a hyperlink to the wiki.

See chrome://flags/ in Chrome/Chromium for UI inspiration.

**Comment by jerechinsky** [comment]
Moving this to product column to prioritize or close this issue.

**Comment by hynek-jina** [comment]
I believe that anyone who can use `trezorctl` doesn't really need that option in Suite. For the average user, we should implement individual functionalities and find the right place for them in the application...
