### ISSUE TITLE
macOS - update from older versions cannot be executed

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3151]
**Describe the bug**
Update modal was displayed and accesible only until update download was finished.

**Info:**
 - Suite Version: app 20.10.1 9995926, app 20.11.2 b0dacc3 (-> 20.12.1 be4e3a3)
 - OS: macOS Big Sur 11.0.1
 - Firmware Version: model T 2.3.4 public

**Steps to reproduce:**
1. Run Suite app with --pre-release flag,
2. Access Suite and navigate through initial setup,
3. Skip update download,
4. Run download again, cancel during download.
5. Run download again, let download finish.

**Expected result:**
Update is installed and Suite is restarted.

**Actual result:**
Neither download nor installation can't be initiated, after update is downloaded.

**Screenshots:**
N/A

**Note(s):**
I was able to initiate the update modal ~three times. May be related to the issues with update in older macOS builds.

**Comment by sorooris** [comment]
#2965

**Comment by tsusanka** [comment]
After tomorrow's release let's create a new "fake" 21.1.0 version during the course of next week and retest then. Because these might be bugs (and are hopefully) in the previous versions.

**Comment by sorooris** [comment]
Unable to initiate autoupdate and verify the issue on the macOS testing device - tested when pre-release was available, canceled download.

**Comment by sorooris** [comment]
**QA OK**

Autoupdate with the `--pre-release` flag successful.

Suite: app 20.1.0 -> 21.1.0 48b5674
OS: macOS Big Sur 11.1
Device: 2.3.5 RC
