### ISSUE TITLE
Update - No up-to-date info displayed

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3152]
**Describe the bug**
Selecting the Check for updates button (Settings -> General -> Application) does not display any information about the app being up-to-date and the button stays enabled.

**Info:**
 - Suite Version: app 20.12.1 be4e3a3
 - OS: macOS Big Sur 11.0.1
 - Firmware Version: model T 2.3.4 public

**Steps to reproduce:**
1. Run Suite,
2. Navigate to Settings -> General -> Application,
3. Select the Check for updates button.

**Expected result:**
Information about the app being up-to-date is displayed.

**Actual result:**
Button changes title to _Checking..._ for a moment and then returns to the active state with _Check for updates_ displayed. 

**Screenshots:**
![Screen-Recording-2020-12-08-at-1](https://user-images.githubusercontent.com/10185314/101495821-4b250a00-3969-11eb-874e-f2be28e5f56c.gif)

**Comment by tsusanka** [comment]
Just as a side note: it prints info into the command line but that is obviously not sufficient.

**Comment by keraf** [comment]
Fixed by #3161

**Comment by bosomt** [comment]
**QA OK**

Nixos
Suite dev master app e771fd3c9b850f781e06f03072b3be55b881dcb9
Device model T fw 2.3.4 public version
