### ISSUE TITLE
Labelling - Cursor dismissed when clicking account title during editing label

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3153]
**Describe the bug**
Clicking anywhere during label editing results in cursor dismissal and needs to be confirmed or 

**Info:**
 - Suite Version: app/web, commit 
 - Browser: , version
 - OS: 
 - Firmware Version: model , revision 

**Steps to reproduce:**
Prerequisite - labelling enabled.
1. Select an arbitrary account and select edit label
2. Click into the account name field (instead of typing),
3. Type the new label title.

**Expected result:**
Cursor is displayed and label editing stays active until it is confirmed, dismissed or navigated to another screen.

**Actual result:**
Cursor is hidden and editing can not be resumed after clicking anywhere during editing.

**Screenshots:**
![Screen-Recording-2020-12-08-at-1 (1)](https://user-images.githubusercontent.com/10185314/101498012-e15a2f80-396b-11eb-9904-d903fdafe792.gif)

**Comment by STew790** [comment]
**QA NOK**

Issue still present

**Info:**
 - Suite version: web 21.9.1 (8b28b4c5df6eebb039ee30a35fab0016dd30679a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.2 regular

**Comment by bosomt** [comment]
**QA OK**

cursor does not disappear anymore.
But I still don't get it why I can click to label when i'm not able to change and i just can create new one


https://user-images.githubusercontent.com/31506317/137689459-1f249108-86ef-4252-9517-eca8063cd7b2.mov


**Info:**
 - Suite version: web 21.11.0 (a1c3485131b680c2916b51654f26ebf4addba3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by STew790** [comment]
Also, I am not sure if this is the same issue but when I try to change the label for the wallet and click into the text of the label, the select wallet modal just closes. Video attached.

**Info:**
 - Suite version: web 21.11.0 (9b398dbee120846b7efe9522b6a66b175daaee2f)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
 - OS: Win32
 - Screen: 1440x900
 - Device: model T 2.4.2 regular
 
 

https://user-images.githubusercontent.com/48477147/137910717-ba878a44-be2c-4e96-b31a-792d4962739b.mp4

**Comment by bosomt** [comment]
I have same result in Chrome on Mac, Wallet/device selector modal just disappears.
edit: I'm not sure if https://github.com/trezor/trezor-suite/pull/4389 ended in current staging version or not.

**Info:**
 - Suite version: web 21.11.0 (9b398dbee120846b7efe9522b6a66b175daaee2f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by bosomt** [comment]
**QA NOK**

Wallet selector modal still disappears when you click outside label space during label editting.

**Info:**
 - Suite version: web 21.11.1 (80f65d680e530c601705cd52f033e424d75d2c9a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by STew790** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.12.1 (4a5547dd0d5c3608718f736e2f34638dc427e2d4)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.4 regular
