### ISSUE TITLE
Exchange - contents (decimals) of ReceiveCryptoInput and FiatInput clipped

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3155]
**Describe the bug**
Contents (decimals) of ReceiveCryptoInput and FiatInput are clipped; prominent especially when selecting the fractions buttons.

**Info:**
 - Suite Version: app 20.12.1 be4e3a3, web beta b9113e2
 - Browser: Chromium 87.0.4280.66
 - OS: macOS Big Sur 11.0.1, Nixos 20.09
 - Firmware Version: model T 2.3.4 public

**Steps to reproduce:**
1. Run Suite in the default viewport,
2. Select an ETH or ETC account (~with 18 decimals allowed) and navigate to the Exchange tab,
3. Enter an amount in FiatInput field or select an arbitrary fraction button.

**Expected result:**
Decimals are either displayed all or hidden behind an ellipsis.

**Actual result:**
Decimals are clipped.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/101503243-300ac800-3972-11eb-9b33-1d002755b450.png)
![image](https://user-images.githubusercontent.com/10185314/101504875-00f55600-3974-11eb-9a84-d9cdccc6a056.png)

**Comment by bosomt** [comment]
current dev master looks still broken

Nixos
Firefox 82.0.3 (64-bit)
Suite web dev master commit f93bd32
Device 2.3.5

![image](https://user-images.githubusercontent.com/31506317/101751997-41b6b180-3ad1-11eb-9f98-d75063ecb50b.png)
![image](https://user-images.githubusercontent.com/31506317/101752012-467b6580-3ad1-11eb-921a-dd193632d49a.png)
![image](https://user-images.githubusercontent.com/31506317/101752035-4c714680-3ad1-11eb-9635-cbc3341b7dd5.png)

**Comment by martinboehm** [comment]
I think it will need some design change.

**Comment by bosomt** [comment]
Linux app commit be4e3a36f7dbe15b2b203f66de11edc50a6665b8
Looks like maximum decimals warning disappear after less than one second when you just ad zeros ;)

![Peek 2020-12-12 21-59](https://user-images.githubusercontent.com/31506317/101994783-64112080-3cc5-11eb-8544-d9f00be7c498.gif)

**Comment by bosomt** [comment]
see https://github.com/trezor/trezor-suite/pull/3741#issuecomment-841262066

**Comment by LukasRada** [comment]
I'd say there is need of redesign? @martinboehm

**Comment by martinboehm** [comment]
Yes, the final solution will require redesign.  I think we have done the maximum within current design limits and the usability is a lot better than before.

**Comment by sorooris** [comment]
@matejzak @alex-jerechinsky Could we please arrange the redesign Martin's mentioning? The #3741 pull request ended up in Needs QA column again but the fix does not resolve the issue.

**Comment by sorooris** [comment]
@alex-jerechinsky 
No redesign was provided and no new pull requests were linked to fix the issue, not approving. Please link a pull request fixing this and then QA will test.

**Comment by dahaca** [comment]
Not relevant anymore, new design fixed it, clipping only with absurdly long numbers
