### ISSUE TITLE
Remove "Soon" from Suite landing page

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3157]
- Both features are already in Suite (Exchanges to be released tomorrow). 

<img width="451" alt="Screenshot 2020-12-08 at 19 47 10" src="https://user-images.githubusercontent.com/29627086/101527356-2d1dd080-398e-11eb-8c03-f1dda58e44b0.png">

**Comment by bosomt** [comment]
**QA OK**

Nixos
Firefox 82.0.3 (64-bit)
Suite web dev master commit f93bd329a2428deb5832953f99cced41e4169aa9
Device 2.3.5
