### ISSUE TITLE
Update Electron to latest 11.x

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#3164]
Electron 11.0.1 blocks Rosetta, because it used to crash. This has been fixed later and reverted in https://github.com/electron/electron/pull/26568 - since Electron 11.0.2 can run on Rosetta. If we want to support Apple M1 devices, we need to update Electron to 11.0.2 or later.

**Comment by prusnak** [comment]
Fix in https://github.com/trezor/trezor-suite/pull/3187

**Comment by bosomt** [comment]
@prusnak is there anything that can be tested on our side ?

**Comment by prusnak** [comment]
Not particularly. It will be tested in full round of testing.

**Comment by bosomt** [comment]
QA OK

Info:

Suite version: desktop 21.1.0 (93c2576)
OS: Linux x86_64
Screen: 1920x1080
Device: model One 1.9.3 regular
