### ISSUE TITLE
Optimize communication with the backend

### ISSUE THREAD

**Issue by martinboehm** [trezor/trezor-suite#3169]
Suite makes request `getAccountInfo` with detail level `txs` for each of the registered accounts, after a notification that a new block has been mined. As only few blocks contain transactions related to given account, it would make sense to query only `basic` info about the account and fetch full information only if the `basic` info is different from previous request.

On the image is an example of 1 minute communication in ETH network, one account registered. New block notification (id 4) comes approximately 6 times per minute. Suite requests the most detailed (`txs`) `getAccountInfo` each time, consuming about 19kB of data. In one hour it is 7MB traffic. If we have in average about 400 open websocket connections to the server (only ETH network), with similar traffic, it makes about 2TB of data/month.
The response to `basic` level of `getAccountInfo` has only about 150 bytes, making the traffic in sum at least 10 times smaller. In addition to that, the change would probably decrease overall load both in the Suite and on the server side.

![image](https://user-images.githubusercontent.com/11609674/101783102-22804a00-3afa-11eb-98fa-e030c115f9e2.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.1.0 (fa7d200c62499405ae63b6bcc873edc15f79d318)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.1.0 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular
