### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#317]
Found a great article on performance testing
https://stuartsandine.com/lighthouse-circle-ci/
maybe we could give it a try.

**Comment by slowbackspace** [comment]
once we upgrade to react 16.9 there will be programatic way to get perf measurements from react itself. It could also be useful https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#performance-measurements-with-reactprofiler

**Comment by slowbackspace** [comment]
some reading material https://medium.com/@addyosmani/the-cost-of-javascript-in-2018-7d8950fbb5d4

> metrics for perf budgets can include:
**Milestone timings** — timings based on the user-experience loading a page (e.g Time-to-Interactive). You’ll often want to pair several milestone timings to accurately represent the complete story during page load.
**Quality-based metrics** — based on raw values (e.g. weight of JavaScript). These are focused on the browser experience.
**Rule-based metrics** — scores generated by tools such as Lighthouse or WebPageTest. Often, a single number or series to grade your site.

it would awesome if, under each PR, we would see a bundle size difference, TTI and an overall lighthouse score

**Comment by slowbackspace** [comment]
thread about running lighthouse in Gitlab CI
https://gitlab.com/gitlab-org/gitlab-ce/issues/33392

**Comment by slowbackspace** [comment]
**I compiled a must read list for writing React with performance in mind (related to rendering):**
- Learn how to use React DevTools profiler https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html
  - Update on how to use new DevTools (v4) https://reactjs.org/blog/2019/08/15/new-react-devtools.html

- Learn `React.memo` (basically same as good old `PureComponent`), `useMemo` (different that React.memo!), `useCallback`
  - https://reactjs.org/docs/react-api.html#reactmemo
  - https://reactjs.org/docs/hooks-reference.html#usecallback
  - https://reactjs.org/docs/hooks-reference.html#usememo
  - https://kentcdodds.com/blog/usememo-and-usecallback/
  - https://reactjs.org/docs/hooks-faq.html#how-to-memoize-calculations

- Understand that just adding a `key` prop  to `array.map`'ed item doesn't prevent its rerendering when the array is mutated (eg pushing a new element).
  - https://codeburst.io/react-array-re-render-performance-ee23f34c5d66 
  - https://stackoverflow.com/questions/44822432/react-state-array-updates-renders-entire-array-is-there-a-work-around
  - `React.memo` to the rescue!

### Performance monitoring with Profiler API 
_(`unstable_Profiler` in React <16.9)_
Measures how much time did a component tree took to render (each render calls callback with measured values).  By default, It is enabled in dev builds only as it comes with some performance overhead, but that is all we need for relative measurements. We could tell by how much is the rendering slower inside the PR branch compared to other branch (eg. develop). We could aggregate this measurements (avg, min, max of rerenders for a given component tree) and send a comment under each PR with the data. https://reactjs.org/docs/profiler.html

**Flow**: Profiler's callback sends the data to prometheus ([Pushgateway](https://github.com/prometheus/pushgateway)) -> prometheus doing all aggregation necessary -> trigger to send a report under the PR.

**Comment by slowbackspace** [comment]
idea: currently, we often have arrays of objects stored in reducers. Searching whole arrays is not so effective and cumberstone to use. Eg. accounts array is filtered by 3 props (descriptor, network, deviceState). We could speed up accessing (finding) an item from the array by using precise stable unique indexes (eg. in case of accounts it will be hash of those 3 props).

edit: implemented in `transactions` reducer!

**Comment by slowbackspace** [comment]
new awesome reading material https://blog.discordapp.com/how-discord-achieves-native-ios-performance-with-react-native-390c84dcd502

**Comment by mroz22** [comment]
also next.js has built in performance testing support 
https://nextjs.org/docs/advanced-features/measuring-performance

**Comment by keraf** [comment]
Added the high priority tag here. As the application grows, we need to keep track of the performance. It feels like recent commits have degraded the performance but we don't have any reference point to track this. We should make sure that there's no negative impact on the user experience caused by performance on the initial release.
