### ISSUE TITLE
Scan qr btn missing when focused on address input

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3172]
first touch was directly in the input. Scan QR button didn't show up. It appears on second try when I tap on another input and then on the address input again.

<img width="367" alt="Screenshot 2020-12-11 at 13 12 11" src="https://user-images.githubusercontent.com/6961901/101902191-89613a00-3bb2-11eb-97e4-3f9bde54ef2c.png">

**Comment by tsusanka** [comment]
We will solve this in the native app.
