### ISSUE TITLE
Accounts menu: Non BTC-like categories

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3173]
ETH filter activated:

Segwit + Legacy account categories shouldn't be present with irrelevant coins (e.g. ETH).

<img width="357" alt="Screenshot 2020-12-11 at 16 28 14" src="https://user-images.githubusercontent.com/29627086/101922024-eae2d200-3bcd-11eb-9219-a9766957e31c.png">

**Comment by slowbackspace** [comment]
related, I can reproduce this state by simply enabling only eth coin in settings, but only in develop, works fine on production suite.trezor.io 🤔 

oh yesss, loading skeletons are causing this 🥇 
<img width="732" alt="Screenshot 2020-12-11 at 18 48 09" src="https://user-images.githubusercontent.com/6961901/101936884-6bf79480-3be1-11eb-9c49-c17f1a2d2419.png">

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82
Suite web dev master commit e771fd3
Device model T fw 2.3.5
