### ISSUE TITLE
Negative balance

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3174]
<img width="871" alt="Screenshot 2020-12-11 at 16 33 20" src="https://user-images.githubusercontent.com/29627086/101922609-98ee7c00-3bce-11eb-9e29-856056f5eee2.png">

**Comment by slowbackspace** [comment]
most likely related to recent implementation of time range (it is probably same issue as https://github.com/trezor/trezor-suite/issues/3127) as AFAIK nothing else changed around graphs in months.
Hmm @bosomt said clearing storage helps with this, could you also try it please?

@tomexx Did you find the problem?

**Comment by slowbackspace** [comment]
hopefully fixed in https://github.com/trezor/trezor-suite/pull/3184
I'm closing the issue.

**Comment by bosomt** [comment]
@slowbackspace I hope so, it's really hard to replicate this issue. But as soon i see any kind of problem I will create new issue ;)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.1.0 (021d3c7a1319c33ea35570b0ac6c4b6bcff36cae)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.3 regular

**Comment by hynek-jina** [comment]
Reported from support...

**Comment by hynek-jina** [comment]
Already covered by this issue: https://github.com/trezor/trezor-suite/issues/3658
