### ISSUE TITLE
Support scanning of upper case QR codes

### ISSUE THREAD

**Issue by slush0** [trezor/trezor-suite#3177]
See https://github.com/btcpayserver/btcpayserver/issues/2110 for reasoning.

**Comment by prusnak** [comment]
This is already supported (see the table).

**Comment by prusnak** [comment]
We might want to drop the warning even and do the conversion silently, but that's for the product meeting to decide.

**Comment by hynek-jina** [comment]
There is separate issue for the conversion: https://github.com/trezor/trezor-suite/issues/5158
