### ISSUE TITLE
Suite allows you to buy less than 20 XRP to fresh account

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3178]
**Describe the bug**
Suite allows you to buy less than 20 XRP to fresh account.
Minimum  is 20 XRP to create new Ripple account. This will eventually ends with error that's not handled properly and it says  `Error: Your XRP address is invalid.`
 
**Steps to reproduce:**
1. In suite go to Trade/Exchange
2. Try to buy via exchange less than 20 XRP 
3. When asked to confirm receiving address create new account and use this address
4. observe

**Info:**
 - Suite version: desktop 20.12.1 (be4e3a36f7dbe15b2b203f66de11edc50a6665b8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/20.12.1 Chrome/87.0.4280.60 Electron/11.0.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Expected result:**
You are not allowed to buy less than 20XRP when you use new account
 
**Actual result:**
Suite allows you to buy less than 20 XRP to fresh account

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/102048081-bc881100-3dde-11eb-972f-12013988e798.png)
![Peek 2020-12-14 07-32](https://user-images.githubusercontent.com/31506317/102048087-bf830180-3dde-11eb-9f87-c4dc86e30852.gif)

**Comment by bosomt** [comment]
+ in SUite you see in list Ripple and not XRP token that you are really buying

![image](https://user-images.githubusercontent.com/31506317/102079585-46e76980-3e0d-11eb-9bd4-0e9d4e2aca27.png)

**Comment by martinboehm** [comment]
The issue with 20 XRP: I think it is OK. We do not actually have to be smarter than the user. The user can choose an account which already has at least 20 XRP, making the transaction possible.

Ripple/XRP: in the list is XRP token belonging to Ripple network, which is in my opinion more clear than showing XRP/XRP. Anyway, the values are returned by our API server and if the Suite team would require to show XRP/XRP, we would have to change it there.

**Comment by szymonlesisz** [comment]
this may be fixed by recent refactor, no? @martinboehm 
using validation in [sendFormRippleActions](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/actions/wallet/send/sendFormRippleActions.ts#L108)

**Comment by bosomt** [comment]
**QA OK**

I'm not able to buy less than 20 XRP anymore

```

Minimum is 0.012057 ETH 
Minimum is 0.00038340 BTC

```

**Info:**
 - Suite version: web 21.4.0 (0353a27e328dec1e3b8745847e0e81a001afaa75)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular
