### ISSUE TITLE
Include labels in the TX export

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3185]
At the moment, labels are not included in the export. Let's include them in a separate column.

**Comment by keo** [comment]
👍

**Comment by MCM-Mike** [comment]
I really would like to see this feature implemented as well, as it helps for accounting.

**Comment by mroz22** [comment]
first good issue indeed. 
the question is how it should look like. it might get quite complex 

![image](https://user-images.githubusercontent.com/30367552/121263943-abfcb300-c8b6-11eb-83b3-32aa287a1fbe.png)

**Comment by glacierbits** [comment]
@mroz22 Do you see any issue with the current implementation on my-trezor? 

Because if not, we can simply format it in the same way and perhaps just move the label to a separate column for easier comprehension. 

<img width="1009" alt="Screen Shot 2021-06-21 at 12 48 50" src="https://user-images.githubusercontent.com/29627086/122750915-6b763f80-d28f-11eb-8c0c-09915c279921.png">

**Comment by mroz22** [comment]
questions 
- "internal labeling"? 
- one output per line (like in mytrezor)? check all seed legacy account 1

pdf
- output amount in brackets after each output (address col)? this is currently present in pdf? 


notes:
- metadata labeling containing `;` watch out so that it does not break columns in csv

**Comment by bosomt** [comment]
**QA OK** 

**Info:**
 - Suite version: web 21.8.0 (e9976a3052507d8b888370ceb11eaa61bae5d775)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.4.1 regular

**Comment by fusionpk** [comment]
How is this closed? It's not even close to fixed. It's atrocious and extremely annoying. Web wallet used to work fine.

Now labels don't show up in any export (randomly a few labels do, but 95% don't and I can't recreate why a few do).

Labels in general have very little explanation/documentation. For example in suite, why is there 2 different types of label? i.e. if you label a receiving address, and then you receive something, you can then label the transaction again and you get Label: label.

???
