### ISSUE TITLE
Double click on title bar does not maximize the window

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#3186]
When I double-click on the title bar other applications are maximized/unmaximized on MacOS.

With Suite this does not happen. I think this is the default behaviour for double-clicking on titlebar on Windows and Linux too.

PS: Maximizing and Fullscreen are different things on MacOS (the green button does fullscreen, double click on title bar does maximize). There is no fullscreen on Windows/Linux, so both the green button and and double-click on title bar should do the same thing - maximize/unmaximize.

**Comment by prusnak** [comment]
From the documentation: https://www.electronjs.org/docs/api/browser-window#winmaximize - we want probably code similar to:

``` javascript
if (win.isMaximized()) {
    win.unmaximize();
} else {
    win.maximize();
}
```

**Comment by prusnak** [comment]
Looking at the code, I noticed the fullscreen and maximize/unmaximize events are entangled together, so we'd need to entangle them first. Not sure if that's worth the effort at this time ...

**Comment by bosomt** [comment]
works for me now,
can you please confirm and close issue @prusnak ?

**Info:**
 - Suite version: desktop 21.10.0 (3b62745211045c3e0ab7472200c69c5388593052)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.0 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.9.4 regular

**Comment by prusnak** [comment]
Works for me
