### ISSUE TITLE
Installer signature expires soon

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3188]
**Describe the bug**
Installer signature expires soon, see screenshot.
Is there plan to replace installer till end of 2020 ?

**Info:**
 - Suite Version: app, commit be4e3a36f7dbe15b2b203f66de11edc50a6665b8 
 - OS: Windows

**Expected result:**
Suite installer is signed by new certificate
**Actual result:**
Suite installer is signed by certificate that expires in two weeks

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/102329660-f4cb5300-3f88-11eb-9b67-c2a38d0c10bb.png)

**Comment by prusnak** [comment]
Yes, we'll replace the key with a new 2021 signing key for the final release.

**Comment by prusnak** [comment]
Fixed today. The new desktop builds will be signed with the new key.

Please test once there are new signed builds available on staging. (Susi will let you know when)

**Comment by bosomt** [comment]
Moving to approved,
New release certificate will be checked during testing
