### ISSUE TITLE
Add a wiki page link on how to install on linux to suite landing page

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#3192]
Since Linux is the only platform where the installation process is not as self-explanatory as double-clicking the .dmg or .exe file, I have added instructions on how to run on Linux on our wiki. Signature of Linux binaries must also be verified manually, unlike on Mac or Windows so I've explained how to do that on the wiki as well. 

https://wiki.trezor.io/Apps:Trezor_Suite#How_to_run

Could we have the wiki link added to the suite landing page, please? 
Perhaps only for when the user is on Linux or has selected Linux in the drop-down menu? 

@tsusanka has provided a nice example:
![image](https://user-images.githubusercontent.com/75733878/102478093-7b516480-405d-11eb-81c9-cdae404047d3.png)

**Comment by tsusanka** [comment]
Ping @matejzak, do you actually want to worry about this? I think my design is just fine?

**Comment by glacierbits** [comment]
Fine with me, provided: 

- The info will appear only when Linux binary selected (as Alex suggests above, otherwise design needed) 
- Copy suggestion: `Linux installation how to` (it's shorter and has Linux as first word - helps to skim the text quickly)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.3.0 (a5de8753d2e8a16b1217edb644c7414d176948cc)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
