### ISSUE TITLE
Dashboard - news tiles are not clickable

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3193]
**Describe the bug**
Clicking the tiles does not redirect to the article, only the Read more link is clickable.

**Info:**
 - Suite Version: any (tested web 20.12.1 be4e3a3)
 - Browser: any (tested Chrome 87.0.4280.66)
 - OS: any (NixOS 20.09)
 - Firmware Version: any (2.3.4 public)

**Steps to reproduce:**
1. Navigate to Dashboard, Trezor news section,
2. Click anywhere on the tile/the article.

**Expected result:**
The whole tile in the section is clickable.

**Actual result:**
Only Read more link is clickable.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/102480452-940f4980-4060-11eb-977c-9301a4a96630.png)

**Comment by bosomt** [comment]
**QA OK**

tested in Firefox and Chromium

**Info:**
 - Suite version: web 21.1.0 (5199ffd3bd526f21f68090e57e8a94d0b2d2ec44)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.4 regular
