### ISSUE TITLE
Unhandled (backup) failed state in Suite

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3194]
**Describe the bug**
Even suite says `Backup failed. Please wipe your Trezor and start the setup process again.`
Dashboard / Security section ignores it and you can click on `Backup wallet button`
Of course it ends with error.

**Info:**
 - Suite Version: app, commit be4e3a36f7dbe15b2b203f66de11edc50a6665b8
 - OS: Nixos
 - Firmware Version: 1.9.3 model One, revision public

**Steps to reproduce:**
1. Connect device with failed backup
2. Navigate to Dashboard / Security
3. Press Backup wallet button

**Expected result:**
Suite dashboard reflect state of backup

**Actual result:**
Backup wallet is available even device is already in Backup failed state.

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/102488976-21589b00-406d-11eb-819b-9db3b2d1190a.png)

![image](https://user-images.githubusercontent.com/31506317/102488962-1a318d00-406d-11eb-938a-7c7a2dc61e72.png)

**Comment by robertbrada** [comment]
I can fix this one

**Comment by mroz22** [comment]
Is that a regression?

**Comment by bosomt** [comment]
No I think it was always like that

**Comment by bosomt** [comment]
**QA OK**

button is disabled now

but

1) i would expect that it will say `Backup failed` and not `Back up wallet`
2) i would expect button to say `Backup` and not `Back up` 

![image](https://user-images.githubusercontent.com/31506317/103544542-8c450700-4ea0-11eb-8bbb-5c657630676f.png)

@mroz22 @matejzak reopen ?

**Info:**
 - Suite version: web 21.1.0 (5199ffd3bd526f21f68090e57e8a94d0b2d2ec44)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Comment by robertbrada** [comment]
@bosomt @matejzak I updated the heading of the card to `Backup failed` (see the screenshot). Should I apply this change? Or should I change the button text to something different as well?

And I think that `Back up wallet` is the right form. While `backup` is used as a noun or an adjective, `back up` is used as a verb. 
So `(to) back up wallet` and `(the) backup failed` seems okay to me (but I am not a linguist :smile:).  Let me know what you think.    

![backup_failed](https://user-images.githubusercontent.com/44506010/103640885-18166c00-4f51-11eb-86c6-a1aa9531db7f.png)

**Comment by glacierbits** [comment]
You are right @robertbrada about the chosen language. :)  Let's leave it like this for now, dashboard will be improved as a whole in couple sprints anyway (incl. these tiles).
