### ISSUE TITLE
Assets display error

### ISSUE THREAD

**Issue by mavazdel** [trezor/trezor-suite#3198]
**Describe the bug**
When Trezor wallet is pluged into computer and after enter Pin if you have Tor option active, assets are not displayed, the suite send error "Assets not loaded correctly". If you uncheck Tor option, eject the Trezor wallet and plug it again without Tor option, assets shows correctly.

**Info:**
 - Suite Version: 20.11.2 
 - OS: Windows and MacOS (running on Big Sur)
 - Firmware Version: Trezor One , 1.9.3 

**Steps to reproduce:**
1. Open Trezor Suite
2. Plug Trezor Wallet
3. Enter Pin
4. If Tor Option is enable, will show error "Asset not loaded correctly". If Tor Option is disable, assets will show correctly
5. Disable Tor option
6. Unplug Trezor wallet
7. Plug Trezor Wallet
8. Enter pin
9. Assets will show correctly

**Expected result:**
Show assets with or without Tor option enable.

**Actual result:**
Only shows assets with Tor option disable.

**Screenshots:**
![Screenshot 2020-12-17 095907](https://user-images.githubusercontent.com/76173409/102511702-b6986700-404e-11eb-88d4-e163eb4f99f2.jpg)
![Screenshot 2020-12-17 095740](https://user-images.githubusercontent.com/76173409/102511704-b7c99400-404e-11eb-83ae-6e33273c4b8a.jpg)
![image](https://user-images.githubusercontent.com/76173409/102546973-135f4600-407e-11eb-9adc-be4c6b7253f7.png)

**Comment by harlessmark** [comment]
Any updates? Mine is showing this as well. Also, the web version only loads by BCH but not my BTC. On top of that, I can't connect my Trezor Model T to Exodus. I'm starting to think I have a faulty wallet.

**Comment by jerechinsky** [comment]
Hi @harlessmark and @mavazdel, could you please retest. Are you still experiencing this?

**Comment by bosomt** [comment]
closing, backends are currently working as expected when Tor enabled

**Comment by pedroslynch** [comment]
I´m passing though the same problem, I had to disable TOR so I can see my balances loaded correctly, exactly as described by @mavazdel .

So I think the bug is back, because It was working fine since a few days ago.

**Comment by pedroslynch** [comment]
Sorry about my english, I´m from Brazil and not fluently in english

**Comment by jerechinsky** [comment]
Hello @pedroslynch. I'm sorry, but the Tor network is currently having issues. Please keep Tor off for now.

**Comment by JeriChode** [comment]
In my case , the error  persist when I disabled Tor
