### ISSUE TITLE
Right click + paste not working in receive address field in Trezor Suite

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-suite#3200]
**Right click + paste option not working in send tab - receiving address field of Trezor Suite*

**Info:**
 - Suite Version: 20.12.1, app
 - OS: Windows 10

**Steps to reproduce:**

1. Copy the receiving address to the clipboard
2. Go to the send tab
3. Right-click in order to use the right-click + paste option to paste the address
4. Not possible, the address is not pasted

**Expected result:**
- Right-click + paste option would paste the string from the clipboard

**Actual result:**
- nothing happens

**Note(s):**
Ctrl + V works, the address is pasted (no issue with clipboard)

**Comment by bosomt** [comment]
Same behavior in in Linux app / Trezor-Suite-20.12.1-linux-x86_64.AppImage /
Browser version works fine

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.1.0 (7ca8df4b2eda195a196a11c7e84f274814e19326)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.3 regular
