### ISSUE TITLE
Adding Support for XinFin[XDC] Network Mainnet chain

### ISSUE THREAD

**Issue by hckhunk** [trezor/trezor-suite#3201]
**XinFin Network mainnet chain support**
How do we initiate support for XinFin[XDC] Network support? We get replies that Trezor only supports top 30 coins. But XinFin has a strong use case in Trade Finance. CMC does not have the right way to rank the projects. It would be a shame to not list XDC.

**Added to Ethereum compatible chain list**
https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-50.json

**Additional context**
The real use case of crypto would not be just speculative trading but peer to peer DeFi lenders financing payday loans and SME origination through XDC integration. This will what make crypto industry a winner. If you want to see that then please add XDC

**Comment by prusnak** [comment]
> We get replies that Trezor only supports top 30 coins.

That's still the case.

**Comment by hckhunk** [comment]
What if a dev group that work with us here create a PR with tested integration? In that case would Trezor merge the PR and add support to the firmware?

**Comment by prusnak** [comment]
No
