### ISSUE TITLE
Desktop autoupdate - Win10 - Suite fails to relaunch after update

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3203]
**Describe the bug**
Update to 21.1.0 causes the app to display an empty white screen with no error messages in terminal.

**Info:**
 - Suite Version: app 20.12.1 be4e3a3 -> 21.1.0 
 - OS: Win10 19042.630
 - Firmware Version: 2.3.4 public

**Steps to reproduce:**
1. Launch Suite from terminal with the `--pre-release` flag,
2. Confirm update download and installation,
3. Let app restart and relaunch.

**Expected result:**
App is updated and launched correctly.

**Actual result:**
Any attempt to launch Suite app results in a white screen displayed with no specific error messages in terminal.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/102814615-331ea300-43cb-11eb-8a63-391372d062b5.png)

**Note:**
#2965, #3151

**Terminal log:**
```
...
download range: bytes=91534088-91600554
download range: bytes=93922673-93946086
download range: bytes=94177519-94360887
Cannot execute Get-AuthenticodeSignature: Error: Command failed: powershell.exe -NoProfile -NonInteractive -InputFormat None -Command Get-AuthenticodeSignature 'C:\Users\Seb\AppData\Local\@trezorsuite-desktop-updater\pending\temp-Trezor-Suite-21.1.0-win.exe' | ConvertTo-Json -Compress | ForEach-Object { [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($_)) }
. Ignoring signature validation due to unknown error.
New version 21.1.0 has been downloaded to C:\Users\Seb\AppData\Local\@trezorsuite-desktop-updater\pending\Trezor-Suite-21.1.0-win.exe
Install on explicit quitAndInstall
Install: isSilent: true, isForceRunAfter: true
Update installer has already been triggered. Quitting application.


C:\Users\Seb\AppData\Local\Programs\@trezorsuite-desktop\Trezor Suite>"Trezor Suite.exe" --pre-release
```

**Comment by keraf** [comment]
Could you repro this one with the logging set to `debug` please?

**Comment by bosomt** [comment]
**QA OK**

location: Program files directory
Windows 10 latest update
Suite commit e6156ff4

**Comment by sorooris** [comment]
**QA OK**

Suite: app 20.1.0 -> 21.1.0 48b5674
OS: Win10 19042.746
Device: 2.3.5 RC

Attaching log
[Win10 - 20.1.0 -> 21.1.0 48b5674 update log.txt](https://github.com/trezor/trezor-suite/files/5905420/Win10.-.20.1.0.-.21.1.0.48b5674.update.log.txt)
