### ISSUE TITLE
Desktop autoupdate - macOS - unable to trigger autoupdate once download was cancelled

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3204]
**Describe the bug**
There is no way to initiate update once the download was cancel in the "Downloading update" modal. Reinstall (neither clean nor dirty) does not resolve the issue, new version needs to be installed "manually".

**Info:**
 - Suite Version: app 20.12.1 be4e3a3, 21.1.0 e771fd3
 - OS: macOS Big Sur 11.1
 - Firmware Version: 2.3.4 public 

**Steps to reproduce:**
Prerequisite: a newer version of the app is available.
1. Launch the older version Suite,
2. Select cancel  on the update modal,
3. Initiate the download from settings,
4. Cancel the download again.
5. Navigate back to settings and initiate download again.

**Expected result:**
Download is re-initiated and is completed successfully.

**Actual result:**
Selecting the active "Get the latest version" button in changes title to Downloading and state to disabled with no apparent actions happening. Update needs to downloaded from the Suite Welcome page and installed manually.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/102816293-133cae80-43ce-11eb-9e22-523570cb6f05.png)

![image](https://user-images.githubusercontent.com/10185314/102816250-0324cf00-43ce-11eb-9e3a-495f8f6999c6.png)

![image](https://user-images.githubusercontent.com/10185314/102816321-1cc61680-43ce-11eb-942d-30c0b4275b70.png)

**Comment by sorooris** [comment]
#2965, #3151, #3202, #3203

**Comment by keraf** [comment]
This should have fixed it: https://github.com/trezor/trezor-suite/commit/f68b6c8b6f1714c862006ef932dd6d52bde30cd7

Could you retest on a recent build please?

**Comment by sorooris** [comment]
**QA OK**

Skipping an offered update in the modal and triggering it via settings behaves correctly - update is detected, offered, downloaded and installed correctly and Suite relaunches correctly as well.

Suite: app 20.1.0 -> 21.1.0 48b5674
OS: macOS Big Sur 11.1
Device: 2.3.5 RC
