### ISSUE TITLE
Duplicated transaction history in exported file

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3206]
**Describe the bug**
See attached file, account with 100+ transactions. Export contains 700+ columns.
After some time Transactions will start repeat itself. Same problem with pdf and csv file.

**Info:**
 - Suite Version: app + web, commit  5a99ad6ab2c15748a8dbd4e1dcf1bdf031b46fcb
 - Browser:Firefox  , version 82.0.3 (64-bit)
 - OS: Nixos
 - Firmware Version: regular-2.3.5-889a3699

**Steps to reproduce:**
1. Load account with transaction history
2. Export it 
3. Check context of file for duplicity

**Expected result:**
Exported transaction history does not contains duplicity

**Actual result:**
Exported transaction history contains duplicity

**Screenshots:**

Number of transactions:

![image](https://user-images.githubusercontent.com/31506317/102931394-99c0c100-449e-11eb-95e5-c6ba7342cc8b.png)

Search for transaction id:

![image](https://user-images.githubusercontent.com/31506317/102931523-d2609a80-449e-11eb-8589-ea0d8fd74599.png)

[export-btc-1608665423060 - export-btc-1608665423060.txt](https://github.com/trezor/trezor-suite/files/5731802/export-btc-1608665423060.-.export-btc-1608665423060.txt)

xpub6BiVtCpG9fQPxnPmHXG8PhtzQdWC2Su4qWu6XW9tpWFYhxydCLJGrWBJZ5H6qTAHdPQ7pQhtpjiYZVZARo14qHiay2fvrX996oEP42u8wZy

**Comment by keraf** [comment]
Should be fixed by #3217

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.1.0 (9ae82af375cea195a84fec664b387c461b2df1ae)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.1.0 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular
