### ISSUE TITLE
2nd ETH account not picked up correctly

### ISSUE THREAD

**Issue by steflsd** [trezor/trezor-suite#3208]
**Describe the bug**
I have a ledger NanoX where I have some btc and eth assets. There are two eth accounts on the NanoX. I initiated the trezor with the same seed + passphrase where I see a) btc accounts b)the first eth account correctly.  The 2nd eth account is an empty account where as on the ledger it has eth.

**Info:**
 - Trezor Suite
 - Browser: , version
 - OS: 
 - Trezor T

**Steps to reproduce:**
1. Verify accounts on ledger
2. Import trezor same seed
3. 1st account should work, further accounts done

**Expected result:**
Expected to see the same account derivation paths, especially since it found the 1st eth account. I am unsure if Trezor or Ledger didnt get this right :)

**Actual result:**
1st eth account is correct as per ledger, 2nd eth account has a different address and is empty

**Comment by prusnak** [comment]
This is an issue with Ledger, they did a mistake in derivation paths. You need to resend your coins to new addresses generated by Trezor.
