### ISSUE TITLE
Add Trezor Suite To Linux Repositories

### ISSUE THREAD

**Issue by trymeouteh** [trezor/trezor-suite#3209]
For enhanced security it would be great to see the Trezor Suite app to be available in the Debian & Arch repositories and constantly up to date. This will allow more security since apps in the official Linux repositories are safe to install and there is a risk to download a DEB or AppImage from a website which could of been tampered with.

**Comment by prusnak** [comment]
Please contact developers of distributions you want Trezor Suite included in to do this. This is not possible unless you find someone willing to maintain the package in the distribution.

Closing as this is not related to Trezor Suite development, but we'll definitively have a look at this too.
