### ISSUE TITLE
"Account does not exist" shown for new Ethereum address used via Metamask

### ISSUE THREAD

**Issue by vjsingh-lite** [trezor/trezor-suite#3212]
**Describe the bug**
I connected my Trezor to Metamask and selected an empty Ethereum address. Transferred some tokens into the address. Connected to Suite. It shows the new address in the left accounts section (with the correct amount of ETH shown), but the main screen shows "Account does not exist". I can withdraw tokens via the Metamask interface talking to Trezor though.

**Info:**
 - Suite Version: App; 20.11.2
 - Browser: NA
 - OS: 5.9.14-arch1-1
 - Firmware Version: Model-T; 2.3.4

**Steps to reproduce:**
1. Connect Metamask to Trezor
2. Select a new empty Ethereum address
3. Transfer some tokens to this address
4. Open suite and goto Accounts
5. You will see the new address account listed in the left section.
6. Click the new Ethereum address account.

**Expected result:**
The main Account view for the address to show up

**Actual result:**
"Account does not exist" screen.

**Screenshots:**
![image](https://user-images.githubusercontent.com/4545705/103313730-fac03a00-4a46-11eb-92e3-ea525a79a40d.png)

**Notes**
- Tried adding a new account via Suite and it just adds another Ethereum address account, but the previous one is still inaccessible, although visible in the side bar.
- I can withdraw tokens via the Metamask interface talking to Trezor though.

**Comment by prusnak** [comment]
> * Suite Version: App; 20.11.2

Please install the latest suite (20.12.1) from https://suite.trezor.io and check whether the issue is still present

**Comment by vjsingh-lite** [comment]
Thank you for the quick response.

Yes, the problem still persists.

**Comment by slowbackspace** [comment]
Hello @vjsingh-lite, is your wallet remembered?  Could you try to reset app storage ("Reset app" button in the settings)? If the reset is successful you should see Onboarding process again, you can skip it and go straight to Accounts again.  ~~Maybe, for some reason, the stored data are corrupted.~~
edit: stored data are fine, it seems we forgot to change the account visibility after it received funds and we know it is no longer empty. fix incoming

**Comment by woweckin** [comment]
Hi, I have the same, but little different. When I use websuite, I have this "account does not exist" problem with one of my ethereum address (I have few ether there and USDC tokens). But when I open it in PC suit apk on my Windows, its working. 
I also tryed to send some ether from the address, but problem stil persists (in websuite version of Trezor).
Hope my tokens are safe. :)

**Comment by slowbackspace** [comment]
@woweckin could you please also try to reset the app storage ("Reset app" button in the settings)? If you are able to see the account on one platform just fine then this should really help.

**Comment by slowbackspace** [comment]
Thank you both for your reports, bug should be fixed in the next release. Clearing the app storage should work as an immediate solution.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.1.0 (9ae82af375cea195a84fec664b387c461b2df1ae)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.1.0 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular
