### ISSUE TITLE
Windows 10 app never starts

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3232]
**Describe the bug**
I'm not able to start Trezor Suite app in current version of Windows 10. Even when I wait few minutes.
Nothing appears in cli interface. Local storage config/log directory is always created. No error is displayed.

**Info:**
 - Suite Version: app, commit 021d3c7a1319c33ea35570b0ac6c4b6bcff36cae
 - OS: Windows 10 current version , tested before and after update /version after update can be seen in screenshot

**Steps to reproduce:**
1. Install current dev master build
2. Start it via icon or via cli
3. Observe

**Tested**

- downloaded same version but Linux app / works fine /
- installed 20.11.2 /works fine/
- tried to delete config dir multiple times
- reinstall
- uninstall and fresh install
- bridge uninstall
- start as administrator
- reboot computer
- update computer

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/103786028-37d68e80-503c-11eb-8743-252a32752afd.png)

**Comment by tsusanka** [comment]
@bosomt could you please test again on current develop just to make sure the problem prevails?

**Comment by bosomt** [comment]
**QA NOK**

@tsusanka tested via 4aadce8a commit, im still not able to launch it

**Comment by bosomt** [comment]
Updated W10 to current version and rebooted
installed Trezor Bridge 2.0.27 manually.

Now it works fine, same commit.
No idea what was the problem

**Comment by tsusanka** [comment]
Could @sorooris and @wendys-cats try the latest develop as well? If neither of you would replicate it I would close.

**Comment by bosomt** [comment]
**QA OK**

tested on my side one more time.
Updated and downloaded version 03c3cd03
Let's close this issue one one more person confirms that it works fine

**Comment by sorooris** [comment]
**QA OK**

Launch, discovery, receive address, app reset, re-launch OK.

Suite: app 21.1.0 e31cc2b
OS: Win10 19042.746
Device: model T 2.3.4 50854b921

**Comment by tsusanka** [comment]
@keraf I am suggesting to close this then unless you have experienced this yourself as it seems it was just some bad universe state on @bosomt's side.
