### ISSUE TITLE
Send form: currency select expandable even for non-tokens networks

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3235]
<img width="824" alt="Screenshot 2021-01-07 at 10 48 13" src="https://user-images.githubusercontent.com/6961901/103878083-39ed2b80-50d6-11eb-9d17-b8d4a035cb95.png">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.1.0 (b872854a602ae4e8502874eee5c5deba2c98d518)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.4 regular
