### ISSUE TITLE
Trezor suite issues

### ISSUE THREAD

**Issue by jingxi285** [trezor/trezor-suite#3240]
**Describe the bug**
Quite a few issues, why tell me no update is available, and again what my version is, and then downgrade is disallowed?
Just don't output anything.. if there is an update "Update to version x.y.z is available"

GtkDialog error.

This integration with sentry.io looks risky, anyway, it then says it is blocked.

**Info:**
 - Suite Version: app/web, commit 
 Trezor-Suite-20.12.1-linux-x86_64.AppImage 
 - 
 - Browser: , version
 - OS:  Latest Ubuntu LTS
 - Firmware Version: Trezor One, latest firmware

**Steps to reproduce:**
1. Just run latest version
$ ./Trezor-Suite-20.12.1-linux-x86_64.AppImage 
Checking for update
Update for version 20.12.1 is not available (latest version: 20.10.1, downgrade is disallowed).
Gtk-Message: 09:16:40.734: GtkDialog mapped without a transient parent. This is discouraged.
[Warning] Domain 'sentry.io' was blocked.

**Expected result:**
No error messages, and a simple message "Update to version x.y.z is available"

**Actual result:**
See output above.

**Screenshots:**
Easy to reproduce every time, please just run it on Ubuntu LTS.

**Note(s):**

**Comment by prusnak** [comment]
The output you see in the console is for developers. Not for users. You don't need to worry about this.

**Comment by jingxi285** [comment]
Maybe there is a miss-understanding. We're not worried, but it is an issue. You could have fixed both issues in the time taken to close this ticket.

Both are trivial patches by any software engineer.
