### ISSUE TITLE
Trezor Suite only works once need to reboot

### ISSUE THREAD

**Issue by jingxi285** [trezor/trezor-suite#3241]
**Describe the bug**
After running Trezor Suite I need to reboot before I can connect another Trezor One.

**Info:**
 - Suite Version: app/web, commit  ./Trezor-Suite-20.12.1-linux-x86_64.AppImage 
 - Browser: , version
 - OS: Latest Ubuntu LTS
 - Firmware Version: Trezor One, latest firmware

**Steps to reproduce:**
1. Run ./Trezor-Suite-20.12.1-linux-x86_64.AppImage 
2. Access Trezor One wallet
3. Unmount it, and remove it.
4. Connect another Trezor One.
5. Observe it cannot connect to it.
6. Reboot, and launch again observe it is now working.

**Expected result:**
Should be able to mount another device after first is disconnected.

**Actual result:**
See above.

**Screenshots:**

Discovery error
Accounts were not loaded properly
Bitcoin: All backends are down

Transport error
Error details: WebUSB is not available on this browser.
Trezor Bridge. Not installed

Note, Trezor bridge is installed. Appologize me, I did not keep a screenshot of these two logs.

**Note(s):**

**Comment by tsusanka** [comment]
@trezor/qa please retest

**Comment by bosomt** [comment]
@tsusanka on it /latest KUbuntu/

**Comment by bosomt** [comment]
**QA OK**

I was not able to reproduce this issue.
Tried app with Trezor Bridge installed.
Tried app with Trezor Bridge not installed.
I was able to load wallets and sent TEST transaction.
Did some shuffle with devices, connect, disconnect, reconnect, even during discovery of accounts.
No errors in app or in cli interface that i used to start app

**Info**
KUbuntu 20.04 before and after update.
Suite public version 20.12.1.
FW Trezor One regular-1.9.4-889a3699
FW Trezor One regular-1.9.3 public version

**Comment by jingxi285** [comment]
Hello, thank you for testing. I don't have this laptop switched on at present, however would ask if is there is anyway to for Trezor Suite to generate a log when it is running? Or to view logs after an error like this occurs?  Could you tell me the steps to follow, or provide screenshots. thanking you.

**Comment by keraf** [comment]
There's unfortunately not much logging in the desktop app. I created an issue (#3248) to add logging. It's pretty high up on the priority list as it will be helpful for debugging issues users encounter.

**Comment by bosomt** [comment]
**QA OK**

i was not able to reproduce issue

**Info:**
 - Suite version: desktop 21.4.0 (ab673f9777b6ddaf13234e5e6b3b3ab5be46852c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model One 1.9.3 regular

**Comment by keraf** [comment]
@jingxi285 Logging has been added to Suite desktop. Could you please try again using the latest release. If it still doesn't work, you can add the `--log-level=info` as well as the `--log-write` (to write it to disk) flags when running Suite. You can find more details for this here: https://docs.trezor.io/trezor-suite/packages/suite-desktop.html#runtime-flags

If the issue persists, I will re-open the issue.
