### ISSUE TITLE
After changing mind about passphase must disconnect trezor one

### ISSUE THREAD

**Issue by jingxi285** [trezor/trezor-suite#3243]
**Describe the bug**
If you put in passphrase, and it says empty. So then you try a different passphrase, it always gives an invalid passphrase confirmation. The only workaround is to disconnect and reconnect.

**Info:**
 - Suite Version: app/web, commit  ./Trezor-Suite-20.12.1-linux-x86_64.AppImag
 - Browser: , version
 - OS: 
 - Firmware Version: Trezor One, latest firmware

**Steps to reproduce:**
1. Open Trezor Suite
2. Connect Trezor one
3. Put in a phassphase.
4. Observe wallet is empty
5. Put in another passphrase, even put it in 5 times. It is never accessible, always fails.

**Expected result:**
Another passphase should work.

**Actual result:**

**Screenshots:**

**Note(s):**

**Comment by tsusanka** [comment]
@trezor/qa please retest

**Comment by sorooris** [comment]
Following the steps to reproduce I am unable to replicate the issue. @jingxi285 could you by any chance specify in **which modal** are you entering the passphrase and provide a **screenshot of the error**?

**Comment by jingxi285** [comment]
Hello. May I check you followed exactly the steps to reproduce exactly? You saw the warning that passphase wallet is empty? Then you put in a different passphrase?

**Comment by tsusanka** [comment]
I think this is indeed an UX confusion (cc @matejzak). The "warning that passphrase is empty" dialog is indeed only checking that you have entered the same passphrase as previously and therefore want to create a new hidden wallet (= new passphrase). You are right there should be a clearer path to "Oops, I have messed up and I would like to enter the passphrase again because it is different".

Assigning @matejzak, he will have a look.

**Comment by tsusanka** [comment]
That being said @jingxi285 I don't think you need to disconnect and connect the Trezor again. You can click on your device in the top left corner in Suite, choose "Add hidden wallet" and enter the correct passphrase.

**Comment by prusnak** [comment]
> . You can click on your device in the top left corner and enter the correct passphrase you meant.

He has Trezor One

**Comment by tsusanka** [comment]
I meant in Suite, apologies, edited.

**Comment by jingxi285** [comment]
> That being said @jingxi285 I don't think you need to disconnect and connect the Trezor again. You can click on your device in the top left corner in Suite, choose "Add hidden wallet" and enter the correct passphrase.

My recollection is that I did try that approach. It did not work.
Would you be able to test both approaches? I need to type the correct passphrase, without disconnecting and putting in PIN again!

**Comment by jingxi285** [comment]
Same issue still visible today. Can someone work on a fix?


Expected behaviour, after an error, start from scratch, let me put in a new passphase.

 ./Trezor-Suite-20.12.1-linux-x86_64.AppImage 



1. Enter: abc
2. See warning wallet empty
3. Enter: foobar
4. See it display this error:

Passphrase confirmation error: Invalid passphrase
[Retry]

5. Click [Retry]
6. See it asks for PIN again.
7. Enter passphrase: foobar
8. See same error
Passphrase confirmation error: Invalid passphrase
[Retry]

This is an infinite loop, it never works until USB disconnected or ejected etc

**Comment by tsusanka** [comment]
Thanks @jingxi285, @sorooris please retest based on the instructions

**Comment by jingxi285** [comment]
Regular wallet.trezor.io asks requires to type the passphrase twice on the dialog. Shouldn't suite do the same?
Regular wallet.trezzor.io shows the passphase on trezor one to confirm. Shouldn't suite do the same?

**Comment by prusnak** [comment]
> Regular wallet.trezor.io asks requires to type the passphrase twice on the dialog. Shouldn't suite do the same?

Not necessarily, because the passphrase is now shown on the device.

> Regular wallet.trezzor.io shows the passphase on trezor one to confirm. Shouldn't suite do the same?

This is not decided by Suite, but by the device. So if your device is not showing the passphrase, you are on the old version of the firmware.

**Comment by jingxi285** [comment]
> > Regular wallet.trezor.io asks requires to type the passphrase twice on the dialog. Shouldn't suite do the same?
> 
> Not necessarily, because the passphrase is now shown on the device.

Unfortunately that text is barely readable, it's a very small font/LCD. Worth requiring the passphrase to be entered twice.

> > Regular wallet.trezzor.io shows the passphase on trezor one to confirm. Shouldn't suite do the same?
> 
> This is not decided by Suite, but by the device. So if your device is not showing the passphrase, you are on the old version of the firmware.

Ok I see. Many thanks. Yes maybe I was testing with old firmware.

**Comment by sorooris** [comment]
@tsusanka is the test still needed? can we close?

**Comment by sorooris** [comment]
bump

**Comment by tsusanka** [comment]
We can probably close. Let's see if the feedback repeats itself.
