### ISSUE TITLE
anonymized usage data is a risk

### ISSUE THREAD

**Issue by jingxi285** [trezor/trezor-suite#3244]
**Is your feature request related to a problem? Please describe.**
Why default to share anonymized usage data? Just default to being off.. the whole idea of Bitcoin is security.
I'd even simply just remove all the code for this feature. There's no reason to upload anything about my usage of my Trezor device.

**Describe the solution you'd like**
Remove this anonymized usage data feature, or at least disable it by default

**Describe alternatives you've considered**
Remove the whole anonymized usage data upload feature?

**Additional context**

**Comment by prusnak** [comment]
We need to prioritize our development according to our users needs. The data is anonymized and can't be tied to a particular user. And of course you are asked whether you want to participate.

**Comment by jingxi285** [comment]
Unfortunately companies get hacked all the time sadly, regardless of their aspirations for security (just think of that other HW wallet manufacturer recently). The simplest is to not gather any data. Sensible to at least have it switched off by default. We don't know what is in these logs, probably IP addresses, transaction details, amounts, logon frequencies, version of the app etc etc. Do you publish what is in this "anonymized data" please?

There's also it establishing a connection to sentry.io as well.
