### ISSUE TITLE
SatoshiLabs 2020 Signing Key expired

### ISSUE THREAD

**Issue by cvandesande** [trezor/trezor-suite#3249]
**Describe the bug**
SatoshiLabs 2020 Signing Key appears to have expired

**Steps to reproduce:**
```
$ gpg --verify Trezor-Suite-20.12.1-linux-x86_64.AppImage.asc 
gpg: assuming signed data in 'Trezor-Suite-20.12.1-linux-x86_64.AppImage'
gpg: Signature made Tue 08 Dec 2020 11:11:52 GMT
gpg:                using RSA key 54067D8BBF00554181B5AB8F26A3A56662F0E7E2
gpg: Good signature from "SatoshiLabs 2020 Signing Key" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: 5406 7D8B BF00 5541 81B5  AB8F 26A3 A566 62F0 E7E2

```
**Expected result:**
A non-expired key

**Actual result:**
```
gpg: Note: This key has expired!
```

**Comment by prusnak** [comment]
That's fine. It is `2020` signing key and it should be expired in 2021.

It still verifies the signature and it should not be used to produce new signatures.

**Comment by cvandesande** [comment]
Makes sense, I should have pointed out that the 2020 key is still offered as the only key to verify the Trezor Suite download on https://suite.trezor.io/

Is this the place to alert SastoshiLabs or should I use another means?

**Comment by prusnak** [comment]
No need to alert anyone. 
The key is perfectly valid and still performs its function (verify releases published in 2020). It is just expired, which means it is not able to produce any new signatures (in 2021) - exactly like designed.

When the next release is out (in 2021), the link on suite.trezor.io will be replaced with the new key for 2021.
