### ISSUE TITLE
Not compatible (Native SegWit, Bech32) with Wallet in browser (SegWit, P2SH)

### ISSUE THREAD

**Issue by ghost** [trezor/trezor-suite#3251]
**Describe the bug**
Suite generates by default Bech32 wallet (address like `bc1....`). However, wallet in browser (https://wallet.trezor.io) uses P2SH (`3H5Y...`) and does not support Bech32.

Basically the wallet in the browser cannot access the coins deposited via Suite.

**Steps**
- Setup Trezor wallet on suite
- Send some coins
- Disconnect and connect Trezor via web wallet
- Coins not there

**Expected**
- Web wallet can access coins deposited via Trezor Suite

**Notes**
- It works the other way around as Suite supports both.
- There is some info about the issue in wiki: https://wiki.trezor.io/Bech32

**Comment by prusnak** [comment]
Old wallet does not receive any new development and will be slowly phased out (we will keep it running, though).

All users should move to Trezor Suite.
