### ISSUE TITLE
Fee: Decimal sat/B

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3252]
**Describe the feature**
Currently, we enforce integers in the transaction fee dialog but we should also support decimals.
- Set the limit on two decimal places

**How to reproduce**

1. Try to send a transaction
2. Set custom fee
3. Try to enter 1.3

**Screenshots**
![image](https://user-images.githubusercontent.com/1835345/161514754-e64b99c4-d85e-46d9-a6a1-48771d85c63e.png)

**Comment by hynek-jina** [comment]
I’m closing this issue for now until the product is specified.
[Current private specification](https://www.notion.so/satoshilabs/Displaying-decimal-places-8abeebdfa38d4205b1238b863a2fb848)

**Comment by marnova** [comment]
I've just found a bug. Fee is not changing if the fee rate is changed on decimal position. See attached screenshots.
<img width="500" alt="2" src="https://user-images.githubusercontent.com/103438830/169780381-5546af1e-2d99-47df-b53b-c350c8275399.png">
<img width="500" alt="2.1" src="https://user-images.githubusercontent.com/103438830/169780390-12597c04-b625-4b00-b2e0-741bc790e33d.png">
<img width="500" alt="2.9" src="https://user-images.githubusercontent.com/103438830/169780410-68914a4d-6d19-40b8-87ac-113f3ab21f74.png">
<img width="500" alt="3" src="https://user-images.githubusercontent.com/103438830/169780597-75b35f55-2e6a-40e5-a2ec-58d294cf5d4e.png">

**Comment by STew790** [comment]
**QA OK**

Fees can have decimals now and it changes if it has the decimal.

![image](https://user-images.githubusercontent.com/48477147/171424672-023e3256-7633-4a97-a497-1220dbf320f0.png)

![image](https://user-images.githubusercontent.com/48477147/171424785-f78fe6f1-0fb2-45fc-9ed1-6474a7c260bd.png)

**Info:**
 - Suite version: desktop 22.6.1 (8d37e21edabe10ea6b6991f5e3a338e3464925e1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
