### ISSUE TITLE
Trezor Suite does not display Invalid seed message when an incorrect seed is recovered.

### ISSUE THREAD

**Issue by NIYAK36** [trezor/trezor-suite#3262]
**Describe the bug**
When recovering a random made up seed in Trezor Wallet, "Invalid seed" message is displayed. When recovering the same seed in Trezor Suite, it accepts the seed and opens wallet. I can add accounts and display addresses.

**Firmware version and revision**
Trezor Suite 20.12.1

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Trezor Suite
 - OS: NixOS 20.03.2157.db31e48c5c8
 - Browser: Firefox
 - Version: 77.0.1

**To Reproduce**
1. Recover a random made up seed in Trezor Wallet - "Invalid seed" is displayed in the end
2. Recover the same seed in Trezor Suite - "Recovery completed" is displayed in the end

**Expected behavior**
"Invalid seed" message displayed in Trezor Suite as well if an incorrect seed is entered

**Comment by prusnak** [comment]
Moved to `trezor-suite` repo

**Comment by tsusanka** [comment]
@mroz22 do we set [enforce_wordlist](https://github.com/trezor/trezor-common/blob/beb242691ce311286bac58a77ad50342b1544a60/protob/messages-management.proto#L301) to True in Suite? Because that's the trick to check the checksum (and wordlist) isn't it @matejcik @prusnak?

**Comment by tsusanka** [comment]
@NIYAK36 what device, T1 or TT? What firmware version?

**Comment by NIYAK36** [comment]
tried with T1, fw 1.9.3.

**Comment by mroz22** [comment]
it looks like enforce_wordlist is sent as true. this was fixed in 6617f673d75613bace55f6bbdaaea1751d8711c1

suite 
https://github.com/trezor/trezor-suite/blob/4aadce8a0b40ec6b689c5449246886348c23840d/packages/suite/src/actions/recovery/recoveryActions.ts#L64
https://github.com/trezor/trezor-suite/blob/4aadce8a0b40ec6b689c5449246886348c23840d/packages/suite/src/actions/recovery/recoveryActions.ts#L93
connect 
https://github.com/trezor/connect/blob/5f40141ee67ce51501f48514a2356a6b29b22fb9/src/js/core/methods/RecoveryDevice.js#L37

**Comment by prusnak** [comment]
> it looks like enforce_wordlist is sent as true. this was fixed in [6617f67](https://github.com/trezor/trezor-suite/commit/6617f673d75613bace55f6bbdaaea1751d8711c1)

But this was committed after the December's release was frozen. So the report is valid and the bug was already fixed and will be published in the next release (in February).

**Comment by tsusanka** [comment]
@trezor/qa please test this works as expected in develop.

**Comment by sorooris** [comment]
**QA OK**

Issue is **not present** in the current 21.1.0 web develop and also verified and confirming its presence in the 20.11.1 app.

Suite: web 21.1.0 fb8f94c8, app 20.11.1 513631a
Browser: Chromium 87.0.4280.66; N/A (app)
OS: Win10 19042.685; NixOS 20.09
Device: model One 1.9.3 0d5f006

**Comment by tsusanka** [comment]
@NIYAK36 we will release a new version with this fixed on February 10th at latest.
