### ISSUE TITLE
account filter should be cleared?

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3266]
**Steps to reproduce:**
1. go to accounts with multiple coins enabled (btc, eth)
2. use account filter on eth, select eth account
3. go to dashboard 
4. go back to accounts

**Actual result:**
selected account is btc but i dont see it in accounts menu (i see only eth)

**Comment by mroz22** [comment]
just hinting @wendys-cats that she may cover this with tests

**Comment by wendys-cats** [comment]
@trezor/qa
When you go back to Accounts, there should not be a situation where you have active ETH coin filter, but your default account that will be shown is BTC (which is NOT selected in the coin filter). Filter either works, or does not, and having BTC account selected by default when user returns to Accounts, even though only ETH is filtered, is inconsistent. 
Please either remove the coin filter when leaving Accounts page, or find a way to preserve the filter without creating an inconsistency (like in Szymon´s case).

**Comment by bosomt** [comment]
yes please, it's confusing 

current master: 

![image](https://user-images.githubusercontent.com/31506317/106287921-ad063f80-6247-11eb-9b03-d970e6d5e6e9.png)

**Info:**
 - Suite version: desktop 21.1.0 (e73dfba83051f953b15baa216b0d14697680078c)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Comment by slowbackspace** [comment]
Hmm I think the main question is: do we care about coin filter state being persistent across dashboard/accounts pages? 
If not then reseting it is a simple fix (PR is open).

If we do care about that, as @wendys-cats pointed out it could be handy for some people, we should consider if coin filter should have an effect on an account that will be selected. This probably will be a bit more complicated and I am not sure if it is worth it. Imagine a scenario where search string & coin filter results in no account being found, what account should be selected then? Couldn't user get confused why he doesn't see his beloved bitcoin account? This would certainly require some thinking and decision from @trezor/product team.

cc @matejzak

**Comment by glacierbits** [comment]
Let's do it (reseting is the way to go imo) @slowbackspace
