### ISSUE TITLE
ETH: Failed smartcontract transactions without annotation

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3268]
**Describe the bug**
ETH Smart contract transactions may be failed because of insufficient gas limit or a different reason.
Suite do not show any annotation about this fact (it's visible only in blockbook explorer) and transaction history looks like everything is ok.
Use case:
sending ETH to exchanges (to exchange smart contract)

Tx example:
https://eth1.trezor.io/api/v2/tx/0xd04e1aa4af840d211f85be5c3ea505101c5284e3bcd63c87be8ed39063ceb921
see `ethereumSpecific.status`, 0 = failed, 1 = success

**Comment by szymonlesisz** [comment]
depends: https://github.com/trezor/blockbook/issues/557

**Comment by bosomt** [comment]
Checking this transaction in latest dev build, was this feature already implemented ?

https://goerli1.trezor.io/tx/0x3d2658bf976128f5144e37632a580ca148c992f19491769759cc70bac42376fd
```
FAILED Reverted. ERC1155: insufficient balance for transfer
```

but no info why it failed
<img width="579" alt="image" src="https://user-images.githubusercontent.com/31506317/235294904-746357f2-f17c-4474-b710-c4f11dbbc475.png">

<img width="598" alt="image" src="https://user-images.githubusercontent.com/31506317/235294918-52c4e3aa-e816-4ea2-9ecd-75e619ebb358.png">


**Info:**
 - Suite version: desktop 23.5.0 (0e2010aa3ca28fd407107948cb608de5c36a02b8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.5.0 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
