### ISSUE TITLE
Support log contains amounts even when the toggle is off

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3274]
**Describe the bug**
In the Application log if I toggle the `Include balance related` button to OFF the log still contains balances, for example the `availableBalance` is still filled.

**Steps to reproduce:**
1. Go to Settings
2. Show log
3. Observe

**Info:**
 - Suite version: desktop 20.12.1 (be4e3a36f7dbe15b2b203f66de11edc50a6665b8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/20.12.1 Chrome/87.0.4280.60 Electron/11.0.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.4 regular

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.1.0 (1936ea70dad4b0293856f6f43e33d507e50d7989)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.1.0 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular
