### ISSUE TITLE
Spend - transaction not shown in Trade tab history

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3276]
**Describe the bug**
Outgoing transaction is not displayed in the shared Trade tab transaction history, only as a generic send transaction in the Overview tab.

**Info:**
 - Suite Version: web 21.1.0 develop, commit fa7d200c
 - Browser: Chromium 87.0.4280.66
 - OS: Nixos 20.09
 - Firmware Version: model T 2.3.4 50854b921

**Steps to reproduce:**
1. Navigate to Accounts -> Trade -> Spend,
2. Complete the spend flow successfully,
3. Observe.

**Expected result:**
The outgoing transaction is displayed in the Trade tab transaction history.

**Actual result:**
The outgoing transaction is displayed in the Overview tab without any indication it is the one that was used in the Spend flow.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/105014984-562b8980-5a41-11eb-8ecb-fbfc1998ed3b.png)
![image](https://user-images.githubusercontent.com/10185314/105015004-5c216a80-5a41-11eb-84ae-6fd04df4dd94.png)

**Comment by martinboehm** [comment]
This is by design. While we could record the spent amount, we have no information about what kind of purchase the user has done, limiting the usefulness of the history item. We will consider adding the feature though.

**Comment by bosomt** [comment]
**QA OK**

tested via staging exchange

![image](https://user-images.githubusercontent.com/31506317/113549508-dcdc1580-95f1-11eb-9cc8-a90d7b1031ad.png)


**Info:**
 - Suite version: web 21.4.0 (f807484bde23d8dc64de78702595fcbd01d19ac0)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular
