### ISSUE TITLE
Hidden wallet number missing

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3277]
**Info:**
 - Suite version: web 21.1.0 (fa7d200c62499405ae63b6bcc873edc15f79d318)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
 - OS: MacIntel
 - Screen: 1792x1120
 - Device: model T 2.3.4 regular 

<img width="353" alt="Screen Shot 2021-01-19 at 10 29 26" src="https://user-images.githubusercontent.com/29627086/105015757-2c269700-5a42-11eb-8411-f943bbc2ec94.png">

**Comment by slowbackspace** [comment]
@bosomt here we go again! 😁  The hardest issue in the history of computer science.

**Comment by bosomt** [comment]
@slowbackspace 

how about this one ? :) 

// removed the image to not confuse anyone as it was for different issue

**Comment by slowbackspace** [comment]
reproduced, just make sure that first wallet instance is hidden wallet.

1. start with fresh suite and in modal for choosing a wallet enter a passphrase.
2. PROFIT

**Comment by slowbackspace** [comment]
just fyi, I had kinda working fix in https://github.com/trezor/trezor-suite/pull/3511, but it wasn't very clean and could complicate things in the future (more info in the PR). I've closed the PR and I'll let this tiny issue live for now.

**Comment by bosomt** [comment]
Issue present in current version 21.6.1 with passphrase on device ` trezorctl set passphrase enabled -f`

<img width="654" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120886802-b5043080-c5e7-11eb-9aec-0b80c6cd9842.png">


**Info:**
 - Suite version: desktop 21.6.1 (4f358fd151fc1962f30f84a855b82213d958aae7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular
