### ISSUE TITLE
Tooltips: Updated

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3279]
### Design: [Zeplin](https://zpl.io/aXlnZej)

To be updated:

**1. Color** as designed 

**2. Shape** (the arrow pointing towards the text / element to be removed)

**3. Dashed underscore** to indicate further info › To replace  the `i` symbol in all suitable places:  

- [x] Switch wallets modal: Remember, Eject
- [x] Send: OP_Return, Send raw transaction
- [x] ETH Send: Data, Gas limit & Gas price (once #2970 implemented) 
- [x] Dashboard graph when XRP and/or ETH enabled
- [x] XRP Send: Destination tag 
- [ ] Settings 

..and possibly other places 💡 

**3. Hover effect** with appropriate delay (let's research & test what that means - Github itself is a good inspiration imo) on text (see point above), tertiary buttons and other worth-to-be-explained elements: 

- [x] BTC Send: Locktime, RBF, Broadcast 
- [ ] Discreet mode, Wallet switch navigation

**Comment by slowbackspace** [comment]
I just noticed it I have a need to share my 2 cents. Using dashed underscore as a visual clue is not really intuitive and I would bet very few people will understand the meaning of it. in cases such as these I would prefer to stick with battle-tested solutions used by mainstream websites that everyone already knows. Let's not make suite UI/UX even more confusing than it needs to be. 🙏

**Comment by keraf** [comment]
> I just noticed it I have a need to share my 2 cents. Using dashed underscore as a visual clue is not really intuitive and I would bet very few people will understand the meaning of it. in cases such as these I would prefer to stick with battle-tested solutions used by mainstream websites that everyone already knows. Let's not make suite UI/UX even more confusing than it needs to be. pray

I'm not a UX expert but I think dashed underlining makes more sense as it hints to "more info if you hover this text". I think it makes it more obvious that there is help related to the word/sentence the user is looking at.

**Comment by slowbackspace** [comment]
@keraf Thanks for sharing your pov! Do you know about some websites or design systems that use this approach? I've never seen it before, but maybe I'm just getting old 😁

**Comment by glacierbits** [comment]
Thanks for the feedback guys. Let me give you a little more context, why we think this a worth pursuing approach. There are a few things / ideas to consider:

- We tried to find unifying visual and behavioral cue that will work across different components / contexts (the solution is underline on text + hover on buttons)
- End goal: Limit the number of external links (e.g. to our wiki). Let's explain as much as we can contextually within the app. Tooltip › Text › Link to e.g. modal /side panel product guide with more text or video (future) 
- We are going test the hypothesis with real users from develop: Unfortunately we can't prototype hovers in Figma, and yet implementing the underline doesn't seem to be that much of an effort (risk / benefit) - correct me if I am wrong
- One of the main reasons: Underline works in plain text as well as headers (unlike the `i` icon). And boy, do we have a a lot of worth-explaining blockchain terms in various places across the whole app.  Example from the new onboarding below. 
- The underline actually increases the discoverability of the tooltip (it has bigger touch target then the `i` icon). Therefore we have the hypothesis, that even if the users won't understand the visual cue, they will learn it fast (especially in context of Send form, for example, where you will see header with and without the underline.. I bet the users will be curious to hover over it.) 

<img width="919" alt="Screen Shot 2021-01-20 at 14 25 44" src="https://user-images.githubusercontent.com/29627086/105180863-6455d480-5b2b-11eb-83f8-f5bfce5b302c.png">

**Comment by keraf** [comment]
I think the implementation of this could could be pretty neat. We could have a text component that has a map certain words to helper information. It could automatically highlight these words and provide the tooltip with the relevant help. It would also be nice to have the option to disable all of these globally, and if disabled, highlight them if a key is pressed down (for example Alt).

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.5.1 (974429bab27c43502251b646a485d792a4ab4180)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1584x990
 - Device: model T 2.3.6 regular

**Comment by wendys-cats** [comment]
QA NOK 
- ETH Send is not implemented


List
- [ ] Switch wallets modal: Remember, Eject OK
- [ ]  Send: OP_Return, Send raw transaction OK
- [ ]  ETH Send: Data, Gas limit & Gas price (once #2970 implemented) **NOK**
- [ ]  XRP Send: Destination tag **NOK**
- [ ]  Dashboard graph when XRP and/or ETH enabled OK
- [ ]  Settings not omplemented yet
- [ ] ..and possibly other places bulb EH? not checked

Hover effect with appropriate delay:
- [ ] BTC Send: Locktime, RBF, Broadcast OK
- [ ] Discreet mode, Wallet switch navigation not implemented yet
 
**Info** 
Chromium Version 88.0.4324.182 (Official Build) (64-bit)
NixOS 21.03
Suite web version 21.5.1 4d09d88476dab2e6b2fbfb833b749e9ac62251c2 
 
 **Note**
 - XRP Send: Destination tag has two tooltips, one is for the button, and the other (new) for the text shown after clicking on the button. Also seems that interactable elements use the hand cursor, and non-interactable elements use the question mark cursor.

**Comment by sorooris** [comment]
hey @alex-jerechinsky it looks like the automation for this issue didn't work after reopening - where should we move this?

**Comment by jerechinsky** [comment]
Thank you @sorooris and @wendys-cats. Moving this one to next release.

**Comment by tomexx** [comment]
@matejzak Hi Matej, can we resolve the NOK items together? Thx

**Comment by glacierbits** [comment]
Sure thing @tomexx 

I see the button & the header have different copy, so I am guessing there is some issue..
