### ISSUE TITLE
Review send modal: Updated

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3289]
**Design:** [Zeplin](https://zpl.io/anjMRvr) 

This update includes: 

- Left side with TX "parameters", right side with inputs to be signed for more visual clarity
- Success screen with link to TX detail  in case `Broadcast = ON, i.e. signing + broadcast`
- Success screen with buttons to download raw TX in case `Broadcast = OFF, i.e. signing only` 
- New, less technical TX detail view 
- Progress counter in case of 10+ items (?) to be signed by the device

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.2.1 (20f555fcbfb0d833c1c12d0d20207450b2c42e47)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
