### ISSUE TITLE
Register bitcoin: URI handler

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3294]
Clicking on a `bitcoin:` URI should open Suite and prefill the inputs if the infromation is available. See https://developer.bitcoin.org/devguide/payment_processing.html#bitcoin-uri and BIP-21 for more details.

Registering our own `trezorsuite:` handler is dealt with in #991.

**Comment by tomasklim** [comment]
I created a basic flowchart that will help us to find a solution how to solve this issue.

https://miro.com/app/board/o9J_lBcHBug=/

**Comment by tomasklim** [comment]
@tsusanka 

Questions:
1) By @matejzak: What will happen if you have more apps like Exodus, Ledger Live and Trezor Suite and you want to use **bitcoin:** handler? Will you get some dialog where you can choose an app?
2) By ondra: Can we somehow find out, that user has Trezor Suite installed? Do we need something like Figma has?
<img width="1052" alt="Snímek obrazovky 2021-06-16 v 16 44 28" src="https://user-images.githubusercontent.com/33235762/122736913-cbb1b500-d280-11eb-9e92-a032c04c4e7a.png">

Answers are based on observation on MacOS:
1) 

- If the handler is registered only by 1 desktop app. Firefox and Chrome show dialogue if you want to open it in your app.
- If the same handler is registered by desktop app and browser. Firefox show dialogue. Chrome opens the web app without asking.
- If a user has more desktop apps with the same handler. The behaviour is not defined (I am not sure where I found this info). However, it looks like that the last installed application wins.

2) 

You can show this screen only if a user opens the desktop app from your web app. However, I see a risk that you can open different app than yours (another app has bitcoin: handler registered).
I investigated how Figma solves that.
When you install Figma app, you have `FigmaAgent` process running in your computer, even when Figma app is not running. Thanks to that, web app can find out that you have this app on your computer and open it using this agent.

In Figma settings, you have to check, that you want to open links in desktop app.
So the workflow is following:
You click on `figma:` handler on xxx website, it opens the web app, which checks if you have desktop app, if not you will see it in web app. If yes, it will open desktop app using the agent and in browser it shows that you have been redirected to desktop app.

**Comment by tomasklim** [comment]
Ideas, bugs,... to follow-up issue #4313

**Comment by tomasklim** [comment]
Info about current implementation can be found [here](https://github.com/trezor/trezor-suite/blob/develop/docs/features/protocols/coin_handler.md). 

**Video example**
Web
https://user-images.githubusercontent.com/33235762/134486746-85719580-ce5c-4f58-898c-1907823014eb.mov

Desktop
https://user-images.githubusercontent.com/33235762/134506192-7a533cf9-e6e8-4c63-8d13-f223f0d41ff1.mov

**Comment by wendys-cats** [comment]
**QA NOK** (WIP, results will be added to this comment)

**1. Send button is disabled when autofill is applied BUG
When info from bitcoin: URI handler is autofilled, Suite does not automatically convert the coin amount into FIAT amount and fill the FIAT field, which is needed for Send button to become enabled.
Once coin amount is changed, or FIAT type is (re-)selected, Suite converts the coin amount into FIAT and enables Send button. Also, if the URI handler is in QR form, this does not seem to be an issue, even though FIAT value is not filled** 

URI handler text form
![image](https://user-images.githubusercontent.com/58593111/135848578-a16056a2-32f4-4ecd-a1ad-8587393fb1e5.png)

URI handler QR form
![image](https://user-images.githubusercontent.com/58593111/135850158-eb28b034-78ca-4e70-9c73-d67cf0df320c.png)


**Info**
**Suite**: web 21.10.0 f14989d7ed4081ed45c65475c6aa85602ea217f5 develop
**Browser**: Chrome Version 94.0.4606.61 (Official Build) (64-bit)
**Device**: TT 2.4.2 public regular 
**OS**: Windows 10
**URI handler used:** bitcoin:bc1qdf7yc02r7gxle4kn98ds5rc5pq2nutpxw54rlw?amount=0.00010484

**video**: https://watch.screencastify.com/v/trybQcsTp87hmW3hH6IL


**2. Mozzila WEB - OK**
info: 92.0 (64 bitů) a 
Opening handler results in browser asking where to open it (yay!)

Opening web Suite results in dialog (yay!) and adding the site into opening options (yay!)
![image](https://user-images.githubusercontent.com/58593111/135867065-de9e5338-7f83-4927-ba19-aa80ce59b184.png)
![image](https://user-images.githubusercontent.com/58593111/135867266-de7ddf18-c15a-4f2c-b110-c7337b9f41a7.png)

Removing sites/settings from Firefox results in a dialogue when site is visited again with option to add the site to settings. When site is removed from handler settings, it does not appear in pop up.
![image](https://user-images.githubusercontent.com/58593111/135924659-f2372f81-a695-48ad-94d8-a7fb9ac20bb6.png)



**3. Chrome WEB** Removing sites/settings from chrome://settings/handlers results in being unable to open the handler with the site (OK). Removed site displays a special icon on the far right side of URL bar, clicking on it opens a dialogue about adding site to URI handler settings (OK).

**Comment by STew790** [comment]
**QA OK**

I tried this on Linux and it works as intended in FF (93.0) as well as in Chorme. It is the same as @wendys-cats described. When I first open Suite it correctly asks if I want to add it as a Bitcoin URI handler. If I open any BTC URI link, it opens Suite and a pop-up tells me to go to Suite send form and then it fills up the send from with the info correctly (screenshot below).

**Info:**
 - Suite version: web 21.10.1 (aa3adfa347d0416f970a7fae720d3350f29f8916)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.2 regular

**Screenshot**

1. Click on "open in wallet"
![image](https://user-images.githubusercontent.com/48477147/137106532-9ebec667-dfc6-4dd9-b113-7b6a004e9f08.png)
2. Pop-up tells me to go to my account 
![image](https://user-images.githubusercontent.com/48477147/137106695-5eaad1f3-f2e6-4055-b634-7987c215fdfd.png)
3. When I go to my account and to send form, the pop-up shows the "Auto-fill in the form" button
![image](https://user-images.githubusercontent.com/48477147/137106845-44e4ee2a-aea6-406d-812e-4a32d96c883d.png)
4. When I click it, it correctly fills in the send form and I can send the tx
![image](https://user-images.githubusercontent.com/48477147/137106999-85586d18-8990-4a06-8b0c-5e105d367d8f.png)

**Comment by wendys-cats** [comment]
**QA OK**

**Windows 10**
Protocol handler bitcoin: is defaultly set to open in Chrome.
**Chrome web** - removing/adding settings OK. Opening when site is added OK, not opening when there is no default OK. Suite/Wallet asking for permission OK.
**Chrome+app** - Chrome opens handler in web. If no default is set, handler is not opened (even if app is open). Needs to be re-set in Win system, but only through Microsoft Store (bleh).
![image](https://user-images.githubusercontent.com/58593111/137106572-e0aeedfc-1239-48d1-a982-b9b476bb07f4.png)

Opening handler without an amount set - OK

**Firefox web** - removing/adding settings OK. Opening when site is added OK, not opening when there is no default OK. Suite/Wallet asking for permission OK.
**Firefox+app** - works OK. Also, Firefox can be set to open the handler with another app (even Chrome).

![image](https://user-images.githubusercontent.com/58593111/137105447-f292d4d3-9cba-4089-bfb3-248035128d16.png)
Opening handler without an amount set - OK
 
MacOS Big Sur
Protocol handler bitcoin: is defaultly set to open in app (if available).
App - once the app is opened, it will be set as a default. Needs to be reset via terminal. 

Opening handler without an amount set - OK

Additional info:
Chrome - protocol settings  chrome://settings/handlers
Firefox - protocol settings  about:preferences#general
