### ISSUE TITLE
Add Energy Web Chain

### ISSUE THREAD

**Issue by drgorb** [trezor/trezor-suite#3295]
The owners of EWT would like to be able to manage their tokens in the Trezor Suite

Add the EWT to the list of available coins 

* The RPC node to be used is `https://rpc.energyweb.org` 
* the logo for the token is 
![image](https://user-images.githubusercontent.com/26613/105706863-6399b580-5f12-11eb-9390-e983794afc52.png)
* The Volta test net should also be added `https://volta-rpc.energyweb.org`
* Volta tokens can be gotten from the [faucet](https://voltafaucet.energyweb.org/)
* The relevant tests should be added

**Comment by prusnak** [comment]
Please send a Pull Request with your tokens to this repo (where the token list is maintained): https://github.com/ethereum-lists/tokens

**Comment by drgorb** [comment]
EWT is not an ERC20 token it is the native token of the Energy Web Chain

**Comment by drgorb** [comment]
> Please send a Pull Request with your tokens to this repo (where the token list is maintained): https://github.com/ethereum-lists/tokens

EWT is not an ERC20 token it is the native token of the Energy Web Chain
