### ISSUE TITLE
Trading - exchange is available for disconnected device

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3297]
**Steps to reproduce:**
- run first discovery (btc)
- remember device
- disconnect device
- go to exchanges
- select exchange pair to LTC

**Expected result:**
Select coin (pair) should be disabled, TrezorConnect.getAccountInfo should not be called at all, user should be requested for "connect your [device-name/label] to continue..." instead

**Actual result:**
TrezorConnect.getAccountInfo is called, and since connect doesn't see any device it's in "waiting for device" state.
Changing pair multiple times leading to queue of TrezorConnect requestes (not handled anywhere)

**Comment by sorooris** [comment]
@martinboehm Any updates on this one?

**Comment by martinboehm** [comment]
It is in the pipeline

**Comment by bosomt** [comment]
Current state:
you can get to offers but app does not asks you to connect device it just idles forever till you leave trade section


<img width="837" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/769b7ee0-a07e-450b-a74d-65f5cce8686c">

**Info:**
 - Suite version: desktop 24.5.3 (0ff3e0bd75d90719b7b36a60b3eab1c2bd3d3491)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by tomasklim** [comment]
@bosomt could you please check how it works now? I reported this #14848

**Comment by bosomt** [comment]
@tomasklim 

looks like this now when trying to swap with remembered wallet

<img width="1441" alt="image" src="https://github.com/user-attachments/assets/b03ca318-906c-4cbd-8295-3409a8c948a2">

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33

**Comment by tomasklim** [comment]
okay, let's closed it in favor of https://github.com/trezor/trezor-suite/issues/14848
