### ISSUE TITLE
Exchange should warn about insufficient ETH balance when exchanging to ERC20 tokens

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3298]
**Describe the bug**
I want to change my BTC to USTD but i dont have any ETH to cover potential fees in case i would like to exchange it back to BTC.

**Steps to reproduce:**
1. Changing BTC to USTD
2. Trying to change back USTD > BTC

**Expected result:**
I should be warned that there is not enouh ETH on this account and i'll not be able to spend my ERC20

**Actual result:**
I'm dissapointed because i dont have BTC anymore, so im not able to buy ETH, so im not able to change my USDT to BTC, the price is changing and im losing my money!!!

**Comment by martinboehm** [comment]
We discussed this problem already and decided that we should not babysit our users. However, I will leave it open in case we want to reconsider it.
