### ISSUE TITLE
Install to user directory instead of Program Files on Windows

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3300]
We are having some problems with autoupdate when Suite is installed into Program Files directory. As suggested by @keraf let's modify the installer to prefill the path not with Program Files but User directory. The user directory is always writable so we should not have any problems there.

@matejzak ACK from the product side?

@keraf what happens if the user edits the path and installs to Program Files anyway? Can we / should we forbid editing the path? Or somehow disable the autoupdater in such case? Or not support it?

**Comment by keraf** [comment]
I would suggest doing a one-click installer into the user directory. This will avoid privilege problems when updating. The one-click installer will not let the user modify the installation path which should be fine for most of our users but I can also see people wanting to have it portable. For the latter group, I would suggest providing a zipped archive of the application.

**Comment by tsusanka** [comment]
Ok, sounds good!

**Comment by tsusanka** [comment]
Prepared in 0ad2b5fed7f1f3da0953eb49b3b8cd1986df76e6, sending to QA.

**Comment by tsusanka** [comment]
Did one-click installer is way to aggressive as discussed with @matejzak. We are trying different approaches.

**Comment by prusnak** [comment]
We can still try:

```
"oneClick": false,
"allowToChangeInstallationDirectory": false
```

**Comment by tsusanka** [comment]
It seems the problem was the "silenceness" of the autoupdater, it seems we have fixed this by https://github.com/trezor/trezor-suite/pull/3224/commits/48b5674bc521ea3feb146f2a18e5a7fa163309cb. QA will confirm but I think we do not have to worry about this.
