### ISSUE TITLE
Display "update available" message for desktop applications that don't have the auto-updater enabled

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#3301]
Applications that don't have the auto-updater enabled should still display a message to the user, informing them that a new version is available.

**Comment by hynek-jina** [comment]
@matejzak Matěji, pls is this still relevant? I don't option to opt-out update.
Thx

**Comment by glacierbits** [comment]
I'd say the questions is: If user skips the update › Goes to Settings › Is the prompt to install update present? I.e. does the button read 'Update available' or something similar? If so, we can close the issue. Afaik it wasn't working like this in the past (FYI it's a long time ago last time I checked), but it would have to be replicated to make sure.

**Comment by bosomt** [comment]
**QA OK**

<img width="791" alt="image" src="https://user-images.githubusercontent.com/31506317/161900969-fc58dafb-f86e-497e-a219-1b283b07faa4.png">

**Info:**
 - Suite version: desktop 22.2.3 (4dc44f620de7f15cdd66970cf22126695435c969)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.2.3 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device:
