### ISSUE TITLE
It is possible to use ctrl+f shortcut in app when the modal is opened on transaction list

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#3304]
See gif file. When you try to seach in modal search dialogue in tx history is open/
If not please close issue.

![Peek 2021-01-22 16-19](https://user-images.githubusercontent.com/31506317/105509502-d9610f80-5ccd-11eb-9f81-86acc3c6dc10.gif)

**Info:**
 - Suite version: desktop 21.1.0 (e31cc2b2c0388e1b50f3f8fd529bc47d7e00fbef)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.1.0 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular

_Originally posted by @bosomt in https://github.com/trezor/trezor-suite/issues/3106#issuecomment-765481378_

**Comment by bosomt** [comment]
same behaviour in latest version

**Info:**
 - Suite version: desktop 21.9.0 (fc8a7ee0dc3487bc96f3b45cac07b26c2474b5b9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular

**Comment by wendys-cats** [comment]
**QA OK for Windows and mac** 

No longer possible in latest app version. Closing issue.

 - Suite version: desktop 22.3.2 (563be1e28ad75ddd4e38c2002e6032b0743511d2)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Win32 and macOS (intel)
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular
