### ISSUE TITLE
macOS: Closing Suite window on full screen leads to black screen

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#3306]
**Describe the bug**

1. Maximize window to fullscreen
2. Close window
3. Observe black screen

This is just a cosmetic issue, Suite re-opens the window when I click on the icon on the dock. The black screen is just surprising.

**Info:**
 - Suite Version: desktop app, 21.1.0 from develop, commit 8a00eb1 
 - OS: macOS
 - Firmware Version: irrelevant

**Comment by bosomt** [comment]
I was able to reproduce issue. 
Works as expected when you use ctrl+q , when you use x button it you will observe black screen that you can close via ctrl+q

**Info:**
 - Suite version: desktop 21.4.0 (ab673f9777b6ddaf13234e5e6b3b3ab5be46852c)
 - OS: MacBook Air M1 v 11.2.3
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.6.0 (9d8cea584b1f655f0964d80f863b02b1523e2cad)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.4 regular

**Comment by bosomt** [comment]
@prusnak @sorooris 
can you please confirm that issue was resolved so we can move it to approved section ?

**Comment by sorooris** [comment]
**QA OK**

Couldn't replicate issue, moving to Approved.

Suite: app 21.6.0 9d8cea5
OS: macOS Big Sur 11.3.1
Device: model One 1.10.0 public regular
