### ISSUE TITLE
Account discovery error when you enable more coins during discovery

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3307]
**Describe the bug**
You can see `Account discovery error` when you enable more coins during discovery and switch between wallets.

**Steps to reproduce:**
1. add standard wallet and passphrase wallet
2. enable coin during discovery of previous coins
3. switch between wallets

**Info:**
 - Suite version: web 21.1.0 (656577d9e3d1f490ee175ed4e397b07ef6547c6a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Expected result:**
You are not able to add more coins during discovery 

**Actual result:**
You can enable more coins during discovery or previously enabled coins.

**Screenshots:**
https://www.youtube.com/watch?v=dbXRMdTXuiA&feature=youtu.be

![image](https://user-images.githubusercontent.com/31506317/106268014-c8168680-622a-11eb-91e2-bb8f5206e579.png)

**Comment by slowbackspace** [comment]
Just so I won't forget, I think the key point is to switch to different wallet while discovery is still running. I could replicate the bug by following steps from the video boso posted.
So it is not great, but not terrible either 😁

**Comment by bosomt** [comment]
I hope this is same problem we see this a lot.
![disc](https://user-images.githubusercontent.com/31506317/106721297-c1aa5500-6604-11eb-8608-b887575bf39f.gif)

**Info:**
 - Suite version: desktop 21.1.0 (29ae0c53d4c3401f05a4d340502f3d61c7cb8556)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.4 regular

**Comment by slowbackspace** [comment]
@bosomt could you please check if the issue is still present or it was solved at the same time as https://github.com/trezor/trezor-suite/issues/3347

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 21.2.1 (20f555fcbfb0d833c1c12d0d20207450b2c42e47)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.2.1 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Comment by bosomt** [comment]
I was able to reproduce it again :)
Switched between passphrase and standard wallets 2 or 3 times during discovery

![image](https://user-images.githubusercontent.com/31506317/107995970-8a15b280-6fdf-11eb-893a-30fce5ca8d3a.png)
![invalid](https://user-images.githubusercontent.com/31506317/107996212-22ac3280-6fe0-11eb-969d-1f086739d5e4.gif)


**Info:**
 - Suite version: web 21.3.0 (7a6dec13f1481ab0cd92bb567e45359d6570ef62)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.6 regular

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.3.0 (a0f694411d85fca4a35acedbdf3b07702517c120)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
