### ISSUE TITLE
Autoupdate - missing update result on next launch (update un/succesful message, modal)

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3308]
**Describe the bug**
User is not informed about the result of an update after relaunch.

**Info:**
 - Suite Version: any, app only (tested 21.1.0, commit ?)
 - OS: any (tested macOS 11.1 Big Sur)
 - Firmware Version: any (tested model T 2.3.5)

**Steps to reproduce:**
Precondition - update is available
1. Launch Suite and confirm update,
2. Select either update on next launch or update immediately,
3. Let either Suite relaunch or relaunch manually.

**Expected result:**
Suite displays an information about the result of the update (success, error) in form of a modal similar to how update is displayed, before entering passphrase etc.; would expect ~"update to version X succesful".

**Actual result:**
No info about update result displayed, either device connection prompt or wallet select modal is displayed.

**Screenshots:**
N/A since is doesn't exist

**Comment by sorooris** [comment]
May release then? :slightly_smiling_face:

**Comment by sorooris** [comment]
**QA NOK**

The notification is now **displayed correctly** after update, however it is **displayed after every launch** of the app.

Suite: app (tested 21.7.1 -> 21.8.1)
OS: MacOS, Win10
Device: model One 1.10.1

**Comment by STew790** [comment]
QA OK

The message appeared only once after the autoupdate and the installation was done.
Auto update 21.7.1 > 21.8.0

Info:
 - Suite version: desktop 21.8.0 (2d590edbb3b5e8e2d07db3e9d83e8e9c2de75618)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.3.6 regular

**Comment by wendys-cats** [comment]
**QA OK**

Update message appeared after update. It did not appear when the (already updated) app was opened later.


**Info:**

**version** 21.7.1 > 21.8.0
**Suite**: APP 21.8.0 2d590edbb3b5e8e2d07db3e9d83e8e9c2de75618
**OS**: Windows10
**Device**: TT 2.4.0 public regular

**Comment by sorooris** [comment]
**QA OK**

Suite: app 21.7.1 3d90909a -> 21.8.0 2d590edb
OS: macOS Big Sur 11.4
Device: any (model T 2.4.0)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - from Suite version: desktop 21.7.1 (1abd1be26f5ae166ec910fe193c4a804d5949a86)
 - to Suite version: desktop 21.8.0 (2d590edbb3b5e8e2d07db3e9d83e8e9c2de75618)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular
