### ISSUE TITLE
Windows - autoupdate checking.. forever after update is skipped

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3314]
**Describe the bug**
When you press skip when asked to update then you are not able to install it anymore.
It will never ask you to install it again and you are not able to trigger it via settings page.
This happened when used --pre-release flag and when I not used this flag.
Sometimes you need to skip it two times. Only way to trigger it one more time is delete suite data directory.
This issue is occurring since we introduced auto update 

**Info:**
 - Suite Version: app, commit e6156ff4
 - OS: Windows with latest update

**Steps to reproduce:**

1. Start suite that offers update
2. Skip update
3. Restart suite or go to Suite settings
4. Update is not offered

**Expected result:**
You are able to trigger update manually or you are asked again to update it.

**Actual result:**
Suite never updates

**Screenshots:**

![photo_2021-02-01_18-51-04](https://user-images.githubusercontent.com/31506317/106497551-7be37480-64be-11eb-81f6-15862e87f2f5.jpg)
![photo_2021-02-01_18-51-02 (2)](https://user-images.githubusercontent.com/31506317/106497556-7c7c0b00-64be-11eb-8606-c1f19c369a09.jpg)

**Note(s):**
[log.txt](https://github.com/trezor/trezor-suite/files/5905685/log.txt)

**Comment by tsusanka** [comment]
@bosomt could you please retest on 21.2.1 (to 21.2.2)?

**Comment by bosomt** [comment]
@tsusanka on it !

**Comment by bosomt** [comment]
**QA OK**

public version update 21.2.1. > 21.2.3 via release flag
tested multiple situations: skip update, update when next started, restart and update, manual update triggered via settings, interupted download, download already finished and then manually triggered update


**info**
suite commit a63b29d19ff08ece94be28d2997d4265ac1c84fc
Windows 10
