### ISSUE TITLE
Add Dependabot

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3317]
It is now part of [github](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/). To update our libraries asap and periodically.

**Comment by prusnak** [comment]
Dependabot is alive and kicking - see https://github.com/trezor/trezor-suite/security

**Comment by tsusanka** [comment]
Ah, cool. How come it did not file a PR for #3315? Maybe it is set to security fixes only? Maybe some config is needed? https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-github-dependabot-version-updates

**Comment by prusnak** [comment]
Hm, it might be confused because we are not using a single `package.json` (each package has its own) but we are using a single `yarn.lock`. This needs to be investigated whether this is supported configuration.

**Comment by tsusanka** [comment]
Seems to be working now :shrug:.
