### ISSUE TITLE
Add a help button to display contextual help

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#3320]
We should provide some in-app help in Suite to let users assist themselves and reduce the strain on the support (especially useful when Suite will officially launch). 

The idea is:
- Display a button on the top right (same section as the settings button)
- Clicking the button or pressing F1 will open a help modal
- Based on the current URL, help topics will be suggested (for example, on the send form, there will be topics about how to use it, RBF, etc...)
- Topics can be searched using a text search bar
- The topics can be pulled from the Suite wiki directly (render Markdown in app)
- On Suite, the docs/wiki will be bundled with the client for offline usage

**Comment by jerechinsky** [comment]
I believe this is addressed by #3713, #4076, #3992.
