### ISSUE TITLE
crowdin links in translator mode are not clickable in notification panel

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3322]
![image](https://user-images.githubusercontent.com/6961901/106615180-76446800-656c-11eb-9155-313f67918d30.png)

**Comment by robertbrada** [comment]
What is meant by **Translator mode**?

**Comment by slowbackspace** [comment]
@robertbrada That's our internal hidden feature that allows product team more easily find hovered intl message in crowdin.
Click 5 times on "Settings" and another option will show up in three-dots menu.

Super low priority :)

https://user-images.githubusercontent.com/6961901/108343319-18568800-71dc-11eb-9922-37c9a7db6d36.mov

**Comment by tsusanka** [comment]
@marekrjpolak could you try if this issue is still relevant please?

**Comment by marekrjpolak** [comment]
I've tried it and notification panel texts are clickable and translatable with current translation mode.
