### ISSUE TITLE
Review tx modal overflow

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3323]
Screenshot of unreleased review modal showing overflow with bigger amounts (imagine doge)/larger number of decimals (ethereum).

Amount in the left panel doesn't stand a chance, even with symbol in new line it won't fit more than 100.18decimals of eth.
Not sure what's the proper fix, but I have a feeling that one most important thing is the amount being sent and it should be visible in full.

Amount on the right can handle much larger numbers, but still you don't wanna make rich people that are using suite angry (imagine jack from twitter) :) This issue is amplified by the fact that we are placing fiat amount on the same row as crypto amount. Not everyone is using USD/EUR and we should accommodate that (since we support various fiat currencies).
As a fix for this, simply wrapping fiat amount on new line would suffice. I am not sure if it is worth to do some tricks like breaking based on actual amount showed.

<img width="764" alt="Screenshot 2021-02-02 at 17 18 17" src="https://user-images.githubusercontent.com/6961901/106629203-e3f79080-657a-11eb-9b47-747866d67107.png">

**Comment by glacierbits** [comment]
On it!
