### ISSUE TITLE
[blockchain-link]: consider dropping support for transactions with multiple addresses in vin/vout

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3329]
they are not supported by Trezor (imo) and requires a lots of conditions in multiple places (searching in array)
https://btc1.trezor.io/tx/60a20bd93aa49ab4b28d514ec10b06e1829ce6818ec06cd3aabd013ebcdc4bb1

**Comment by jerechinsky** [comment]
currently irrelevant
