### ISSUE TITLE
[copy] Ethereum sign/review fee message

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3330]
Fees in Ethereum are not final, technically you can pay less for a tx to mine.
Proper message should be the same as on the device:

![Screenshot from 2021-02-02 19-10-36](https://user-images.githubusercontent.com/3435913/106643821-8a975d80-658a-11eb-8ac4-65f6c374170a.png)
![Screenshot from 2021-02-02 19-01-30](https://user-images.githubusercontent.com/3435913/106643829-8cf9b780-658a-11eb-9e03-2787672ad69e.png)

**Comment by bosomt** [comment]
**QA OK**

 - Suite version: desktop 23.9.0 (27f88acdf82fb86f4b78db9386ca48a6df26fe4b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
