### ISSUE TITLE
RBF for ETH network ♻️

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3331]
In ETH every pending transaction is not final and could be replaced with higher fee (like bitcoin RBF)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.3.0 (b6c84eb9e23f9483d25ff4cb4a96a4c357596a24)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.3.0 Chrome/87.0.4280.141 Electron/11.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
