### ISSUE TITLE
Trezor onboarding

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3332]
**Model T:** [Zeplin](https://zpl.io/V1RmeGJ) 
**Model One:** [Zeplin](https://zpl.io/VDPR7Je)
**Spec:** [Notion](https://www.notion.so/satoshilabs/Onboarding-Trezor-57311f20596e4d25a08a119bf8de8e59)

**Comment by wendys-cats** [comment]
from original comment https://github.com/trezor/trezor-suite/pull/3677#issuecomment-863248363 :

FW 1.10.1. results in reinstall OK
BL 1.8.0 no FW results in latest (1.10.1) installed OK
FW 1.9.3 results in latest (1.10.1) installed OK
FW 1.7.3 results in latest (1.10.1) installed **OK**
FW 1.9.2 results in latest (1.10.1) installed **OK**
FW 1.10.0 results in latest (1.10.1) installed **OK**

Brand new BL 1.4.0 T1 device results in correct latest (1.10.1) installed OK

**Note:** Confirming that 1.7.3, 1.9.2 and 1.9.3 all asked to reconnect twice. 


Bridge scare - New onboarding, particularly installation of intermediary FW with update to latest will be interrupted after installing intermediary FW and device will not be recognised IF the user has 2.0.20 standalone trezord installed (trezord at fault). Please keep this in mind. Killing/uninstalling/downgrading to 2.0.27 is a workaround.

**Comment by bosomt** [comment]
**QA OK**

original comment: https://github.com/trezor/trezor-suite/pull/3677#issuecomment-862987407

QA OK 2.0.3 BL empty device > 2.4.0 installed and created new wallet correctly
QA OK 1.8.0 BL, NOFW > 1.10.1 installed
QA OK 1.9.4 FW not init > 1.10.1 asked to reconnect device 2x
QA OK 1.9.4 FW initialized > 1.10.1 asked to reconnect device 2x
QA OK 1.10.1 > 1.10.1 reinstalled correctly
QA OK 1.10.0 > 1.10.1 installed correctly
QA OK 1.3.2 BL empty device, intermediary FW installed , after that upgraded from 1.10.0 to 1.10.1
QA OK 1.4.0 BL empty fresh device onboarded in macOS app
QA NOK 1.3.1 BL 1.6.0 FW > 1.10.1 + intermediary NOT offered /issue sent/

**Comment by STew790** [comment]
Info:

QA OK 1.10.1 > 1.10.1 reinstalled correctly
QA OK 2.0.3 BL empty device > 2.4.0 installed and created new wallet correctly
QA OK 1.8.3 FW 1.8.0 BL initialized > 1.10.1 FW asked to reconnect 2x
QA OK 1.4.0 BL empty fresh device onboarded in Win10 app 
QA OK 1.4.0 BL fresh device onboarded in Win10 web (tried with Webusb as well and suite forces you to install Trezor Bridge 2.0.27)
