### ISSUE TITLE
Review modal: gas price overflow

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3333]
let's round it to 3 decimals, x.xxx, if it won't look too weird let's also add the symbol we are using in accounts menu for balance in fiat currency (something like ~).
![image](https://user-images.githubusercontent.com/6961901/106730869-21a5f900-660f-11eb-8c3b-116ccdb9ac5a.png)

**Comment by tomexx** [comment]
Do we want to make the same in the Send from?
![image](https://user-images.githubusercontent.com/2822756/106873365-ac046080-66d4-11eb-9c18-c8e0bbd8040c.png)

**Comment by bosomt** [comment]
Can this be related ? 
Same behavior in Chrome or Firefox when i press send all
Works fine at 21.2.2 7e8958e206885cd7946f431b63dad3bd446ef82e

Info:

Suite version: web 21.3.0 (7a6dec1)
Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
OS: Linux x86_64
Screen: 1920x1080
Device: model T 2.3.6 regular


![image](https://user-images.githubusercontent.com/31506317/107994570-34d8a180-6fdd-11eb-8349-708c2f973612.png)

**Comment by bosomt** [comment]
**QA OK**

i will create separate issue 

Info:

Suite version: web 21.3.0 (7a6dec1)
Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
OS: Linux x86_64
Screen: 1920x1080
Device: model T 2.3.6 regular
