### ISSUE TITLE
Move Suite version to single place?

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3335]
During every release we are bumping the packge versions to format YY.MM.PATCH (see [docs](https://docs.trezor.io/trezor-suite/misc/versioning.html)). It is a bit annoying that we have to modify the version of each and every packge, see c2448b3a. Could we have just a single file where the version is stored? Or extrapolate it somehow to a single variable? I am not sure if it is possible the way yarn works.

We could also write a tool/regex for that but that seems like an overkill.

**Comment by slowbackspace** [comment]
maybe something like lerna could do the job?
https://github.com/lerna/lerna/blob/main/commands/version/README.md

**Comment by tsusanka** [comment]
Yes! :heart: We just need to figure out how to ignore some of the packges:

```
lerna version 21.3.1                                    
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Assuming all packages changed

Changes:
 - @trezor/blockchain-link: 1.0.15 => 21.3.1
 - @trezor/components: 1.0.0 => 21.3.1
 - @trezor/integration-tests: 1.0.0 => 21.3.1 (private)
 - @trezor/landing-page: 21.3.0 => 21.3.1 (private)
 - @trezor/news-api: 1.0.0 => 21.3.1 (private)
 - @trezor/rollout: 1.0.5 => 21.3.1
 - @trezor/suite-data: 21.3.0 => 21.3.1
 - @trezor/suite-desktop: 21.3.0 => 21.3.1 (private)
 - @trezor/suite-native: 21.3.0 => 21.3.1 (private)
 - @trezor/suite-storage: 21.3.0 => 21.3.1 (private)
 - @trezor/suite-web-landing: 21.3.0 => 21.3.1 (private)
 - @trezor/suite-web: 21.3.0 => 21.3.1 (private)
 - @trezor/suite: 21.3.0 => 21.3.1 (private)
 - @trezor/translations-manager: 1.0.0 => 21.3.1

? Are you sure you want to create these versions? (ynH) 
```

**Comment by slowbackspace** [comment]
I am wondering if we really need to ignore some packages, ones that currently don't follow suite versioning are:
translations-manager, integration/tests, rollout, news-api , components, blockchain-link. But maybe they could and should? The only package that could be used by some 3rd party is blockchain-link, but I am not sure if someone really uses it. And even then, lerna should bump version number only if there were really some changes in the package. So that should work for 3rd parties fine?

hmm but what we certainly need  is, after a version bum in eg. trezor/components lerna should automatically bump dep version in all packages (in package.json) that use trezor/components
...just thinking out loud

**Comment by tsusanka** [comment]
I have introduced release-it in #3470 which can be used for version bumping but I have to say I hate it. It is very aggressive and will modify releases without prompting. So I will investigate other options.

**Comment by tsusanka** [comment]
@keraf @szymonlesisz what do you think about @slowbackspace's suggestion above? That means bumping all packages:

```
 - @trezor/blockchain-link: 1.0.15 => 21.3.1
 - @trezor/components: 1.0.0 => 21.3.1
 - @trezor/integration-tests: 1.0.0 => 21.3.1 (private)
 - @trezor/landing-page: 21.3.0 => 21.3.1 (private)
 - @trezor/news-api: 1.0.0 => 21.3.1 (private)
 - @trezor/rollout: 1.0.5 => 21.3.1
 - @trezor/suite-data: 21.3.0 => 21.3.1
 - @trezor/suite-desktop: 21.3.0 => 21.3.1 (private)
 - @trezor/suite-native: 21.3.0 => 21.3.1 (private)
 - @trezor/suite-storage: 21.3.0 => 21.3.1 (private)
 - @trezor/suite-web-landing: 21.3.0 => 21.3.1 (private)
 - @trezor/suite-web: 21.3.0 => 21.3.1 (private)
 - @trezor/suite: 21.3.0 => 21.3.1 (private)
 - @trezor/translations-manager: 1.0.0 => 21.3.1
```

`lerna version` seems to do the work just fine. We can omit some packages in lerna.json but that would omit them in general for lerna which we do not want to do I guess?

I am not sure myself, on one side it seems superfluous to bump all packages, on the other hand we could use the same argument for `suite-data` for example. We bump it even if there is no change. What do you think? Anyone strongly against? It would simplify version bumping a lot.

**Comment by goodhoko** [comment]
forme: todo:
- [x] mark private packages as private
- [x] use `1.0.0` for all private packages
- [x] update `docs/releases/versioning.md`
- [x] make electron-builder use version from the root `package.json` https://github.com/electron-userland/electron-builder/issues/5946
- [x] fix CI failures
- [x] profit

**Comment by goodhoko** [comment]
As [the PR that blocks this](https://github.com/trezor/trezor-suite/pull/3446) will be most probably merged after I leave this will have to be overtaken by someone else.

I implemented this [here](https://github.com/trezor/trezor-suite/pull/3894). The diff-set is complete but one should verify the CI produces valid builds especially with regards to the auto-updater and Suite version exposed within the app.

See the [changed documentation](https://github.com/trezor/trezor-suite/pull/3894/files#diff-b26affc21dd7bde925852ddf383db8169534f2d71f37306337970846dc5655e7) to understand what that PR aims to implement.

I'll dare to assign this to @matejkriz who AFAIK works on the blocking PR. cc @alex-jerechinsky

**Comment by tsusanka** [comment]
Also wouldn't switch [from Independent to Fixed/Locked mode in Lerna](https://github.com/lerna/lerna#how-it-works) do the trick?

**Comment by goodhoko** [comment]
@tsusanka sorry for taking so long to respond. Unfortunately fixed mode won't help us here. It's (and Lerna in general) based on assumption that the versioning is used to communicate changes in public packages of the monorepo. This means, among other things, that
- `lerna publish` only bumps *public* packages. That's a complete opposite of what we need - we use the versioning to track evolution of the Suite app and we need the few public packages to be versioned independently from the app.
- Fixed mode only bumps packages that have changed since the last release. However, in current setup we need to bump the version in most packages regardless of the changes because the versions are propagated into the app. (Eg. version of `@trezor/suite-desktop` package is shown in the desktop builds to the user.) The PR I linked above alleviates us from this by tracking the suite version in a single place (the top-level package.json).

**Comment by matejkriz** [comment]
**QA - what to test?**
User should see the app version same as before (in Settings > Application > Suite version and in filename of downloaded Suite app). Please check all platforms (**win**/linux/mac).

**Comment by goodhoko** [comment]
In addition to what @matejkriz wrote above it would be good to check that the CI produces properly named artifacts - for instance, the app version is part of the name of the released executables.

**Comment by tsusanka** [comment]
cc @vdovhanych for the next release all we need to do is change `suiteVersion` in [packages/suite/package.json](https://github.com/trezor/trezor-suite/pull/3894/files#diff-cf2f50ab25c7c54b323f082bf9c7c129fbc05b5d6e7e43371817b57149847bbeR3) :tada:. Great job!

**Comment by vdovhanych** [comment]
> cc @vdovhanych for the next release all we need to do is change `suiteVersion` in [packages/suite/package.json](https://github.com/trezor/trezor-suite/pull/3894/files#diff-cf2f50ab25c7c54b323f082bf9c7c129fbc05b5d6e7e43371817b57149847bbeR3) :tada:. Great job!

@tsusanka saw the pull request today 🥳 very nice feature for us!

**Comment by bosomt** [comment]
**QA OK**

### macOS Apple version

<img width="429" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/131262352-eae5a1b0-f80a-4370-be62-92de65947f84.png">


### macOS Intel version

<img width="407" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/131262305-c4a4a0e2-8fa0-4b21-b9b2-0d62b6309d45.png">


**Info:**
 - Suite version: desktop 21.9.0 (f9ecf819ac9cc809aa78295793c065c508f74e72)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by STew790** [comment]
**QA OK**

**Windows 10**
![image](https://user-images.githubusercontent.com/48477147/131502715-c5b8cf14-21b9-4ae5-aaab-29d3d030723e.png)

**Info**:
 - Suite version: desktop 21.9.0 (1f5e833a2d214388d3b0c760aa5287e5c83dbd87)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.2 regular

**Comment by sorooris** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/10185314/131520533-bd7cfc99-be25-4bd6-b20d-ef70f3faa52c.png)
![image](https://user-images.githubusercontent.com/10185314/131520635-e5774b6d-429a-4523-a77a-caebac2d4207.png)
![image](https://user-images.githubusercontent.com/10185314/131520660-f1f09232-887e-4446-aa92-af31c443b9fb.png)

Suite: app 21.9.0 b5a686a
OS: Linux Mint 20.02 (Cinnamon 5.0.5)
Device: model T 2.4.2
