### ISSUE TITLE
Send dialogue - Inconsistent fee info

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3336]
**Describe the bug**
See screens and gif I recorded, I selected 1 sat/b in send dialogue but in confirmation dialogue it's 4 sat/b.
Both dialogues have same fee displayed 645 sat but rate is different.
This happens only when you try to send funds from B32 account, Segwit and Legacy accounts works fine.
This only happens when you set manually see to 1 sat/b

**Steps to reproduce:**
1. go to Bech32 account send dialogue
2. Change fee to 1 sat/b
3. press Review and Send button and check fee

**Info:**
 - Suite version: desktop 21.2.1 (c2448b3a66c2850c2a99acc8574edadf5771d565)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular

**Expected result:**
Send dialogue and confirm transaction display same fee rate
**Actual result:**
Some send dialogue and confirm dialogue have different fee rates

**Screenshots:**
![fee](https://user-images.githubusercontent.com/31506317/106862131-fb439480-66c6-11eb-99fc-3dde7abb5018.gif)

![image](https://user-images.githubusercontent.com/31506317/106862559-950b4180-66c7-11eb-805d-be4b54d4d220.png)

![image](https://user-images.githubusercontent.com/31506317/106862586-9ccae600-66c7-11eb-99ba-9aa8cd7aa8ec.png)

**Comment by slowbackspace** [comment]
We know! 🤭

**Comment by bosomt** [comment]
same for DOGE :)

![image](https://user-images.githubusercontent.com/31506317/106893857-77050780-66ee-11eb-9bc4-0b0bdae79c3f.png)

![image](https://user-images.githubusercontent.com/31506317/106893908-85532380-66ee-11eb-9ebd-92b437c59c83.png)

**Comment by slowbackspace** [comment]
@bosomt it is like that for every bitcoin-like coin (segwit enabled), we know about the issue (someone actually noticed it during product demo) and are working on the fix :)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.2.1 (20f555fcbfb0d833c1c12d0d20207450b2c42e47)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
