### ISSUE TITLE
Release fixes

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3340]
Temporary issue to track what needs to cherry-picked into the release branch. Please comment to request a cherry-pick.

- [x] https://github.com/trezor/trezor-suite/pull/3338
- [x] #3339 
- [x] #3343
- [x] - https://github.com/trezor/trezor-suite/commit/fa056457fde7042c06cdb75ef7772243942a5433
- [x] https://github.com/trezor/trezor-suite/commit/e850887e08e5ea3c070769cdf235c73e02b2e752
- [x] ff7cc31b5cc21be897b8d64ae03d9bef57694f7b
- [x] https://github.com/trezor/trezor-suite/commit/116dbe3c73e1a43fff6f96e8c3fbe10a0e160ff0 (depends on ff7cc31b5cc21be897b8d64ae03d9bef57694f7b)
- [x] 3359079ed22a11dcd9da4f4003647b3f82085297

**Comment by slowbackspace** [comment]
https://github.com/trezor/trezor-suite/pull/3339

**Comment by slowbackspace** [comment]
https://github.com/trezor/trezor-suite/pull/3339 (to be merged, but I don't wanna forget about it during the weekend 😬 )

**Comment by tsusanka** [comment]
All three passed on to QA.
