### ISSUE TITLE
Send - missing Finalize switch in bump transaction modal

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3341]
**Describe the bug**
Bump transaction fee modal is missing finalize transaction switch

**Steps to reproduce:**
1. send RBF transaction
2. press bump fee
3. finalize transaction switch not available in modal

**Info:**
 - Suite version: desktop 21.2.1 (c2448b3a66c2850c2a99acc8574edadf5771d565)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.2.1 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular

**Expected result:**
You can finalize transaction from bump fee modal.

**Actual result:**
Finalize transaction can only be triggered from transaction detail

**Screenshots:**
![final](https://user-images.githubusercontent.com/31506317/106898285-488a2b00-66f4-11eb-9356-aa0e23d5d889.gif)

**Comment by slowbackspace** [comment]
@alex-jerechinsky from my pov it is actually feature request as the switch is missing in design. I am expecting that @matejzak will have to figure out where and how to show it in UI to reduce the potential for misunderstanding.

**Comment by jerechinsky** [comment]
@slowbackspace Fair enough. If @matejzak agrees, we'll put it in backlog for now until Matej figures this one out.

**Comment by hynek-jina** [comment]
## Proposal:
- Remove `Finalize transaction` from transaction detail. _It's not visible in transaction history either_
![Screenshot from 2023-08-22 11-56-13](https://github.com/trezor/trezor-suite/assets/26002916/8000b3e2-bc1f-4b63-802b-666c28658dfd)
- Add option to turn `RBF=off`. _Just like in send form_
![Screenshot from 2023-08-22 11-56-21](https://github.com/trezor/trezor-suite/assets/26002916/3cb55645-0ae7-4c50-b6eb-8ee6d0af644f)
- Keep existing warning in case of bump with turning off RBF
![Screenshot from 2023-08-22 11-56-02](https://github.com/trezor/trezor-suite/assets/26002916/f95f0ae1-ec81-40ad-b508-36d9391edc22)

**Comment by Hermez-cz** [comment]
@hynek-jina Nice solution, thank you. I'd change only the copy in the last image from `(i) Finalizing transaction will turn RBF OFF`, as it's already off in that situation, to something like `After finalizing the transaction, RBF cannot be turned on.`

**Comment by komret** [comment]
Finalize functionality removed in https://github.com/trezor/trezor-suite/pull/13279, closing.
