### ISSUE TITLE
Authorization error: Device call in progress error when adding wallet

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3347]
**Describe the bug**

This issue is occurring a lot in last versions of Suite.
I see `Authorization error` even devices were just connected after Suite was started.
Sometimes im not even able to add any even standard wallet/see last screenshot/.
I see in log:
`ERROR(console-log): Uncaught (in promise) Error: session not found - file:///static/connect/js/iframe.9cd600cdb5561a35c213.js:53`

**Steps to reproduce:**
1. Start suite
2. Connect two devices
3. Try to add wallet

**Info:**
 - Suite version: desktop 21.2.1 (c2448b3a66c2850c2a99acc8574edadf5771d565)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular + 2.3.5 

**Screenshots:**

![fuck](https://user-images.githubusercontent.com/31506317/107019984-9c534d80-67a2-11eb-9130-458bf17816a8.gif)
![error](https://user-images.githubusercontent.com/31506317/107019991-9d847a80-67a2-11eb-9605-d3dfb86b93ad.gif)
![Screenshot from 2021-02-05 11-08-42](https://user-images.githubusercontent.com/31506317/107020000-9fe6d480-67a2-11eb-8751-950b259ed6d7.png)

**Comment by bosomt** [comment]
It's occurring even when you use webUSB , so it's not Bridge related

**Comment by tsusanka** [comment]
@bosomt could you please append the whole log from Suite?

**Comment by bosomt** [comment]
@tsusanka https://pastebin.com/UheCU9UB

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.2.1 (20f555fcbfb0d833c1c12d0d20207450b2c42e47)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
