### ISSUE TITLE
Account navigation

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3348]
New account navigation design improvements: 

- [x] Increase font size for the fiat value (from 20 to 24px) [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/601d23fb81d8f9849d65adb8)
- [x] Tabs for `Overview` and  `Details` (i.e. remove 3 dots account menu) 
- [x] Turn tabs into secondary buttons for `Send`, `Receive`, `Trade` 
- [x] `‹ Back` button for expanded Send, Receive, Trade views [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/601d23f300e5519f7f8c7da2) 

- [x] Sticky account header [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/601d2d464c342e10b482dc94)

Please disregard other design changes (i.e. navbar, left account menu, top navigation etc.) in the proposal for now. These are still being tested and reviewed. This issue is related to the account header only.

<img width="907" alt="Screen Shot 2021-02-05 at 12 05 40" src="https://user-images.githubusercontent.com/29627086/107026034-79c53280-67aa-11eb-8df7-43e7c054eadc.png">

**Comment by glacierbits** [comment]
Looking at the respective branch, I have a few favors to ask: 

- [x] Button font weight should be 600 (semibold). It's 500 currently. 

- [x] Button font should be 14px. It's 16px currently.

- [x] Please increase the button padding (internal spacing) on the left & right side of the button label. (Might be improved by the font size though, I guess)  

- [x] Please hide the "Add token" button on ETH underneath the 3 dot menu + dropdown: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/6050e5242af2c021da84ca93) 
FYI In the near future, this menu will be added to BTC and other networks as well for "Sign & verify" feature.

**Current implementation:**

<img width="675" alt="Screen Shot 2021-03-16 at 18 18 16" src="https://user-images.githubusercontent.com/29627086/111351964-fd185480-8683-11eb-9fb4-6197cc3d1094.png">

**Design proposal:** 

<img width="725" alt="Screen Shot 2021-03-16 at 18 18 06" src="https://user-images.githubusercontent.com/29627086/111351986-01dd0880-8684-11eb-9142-ea3223660fd2.png">

**Comment by tomexx** [comment]
@matejzak Thank you for the feedback. Regarding buttons - I used the style from current dev styleguide. Are we adding the new button style only for this case or is there a plan to change the buttons style also in different places (I could add the new style / change current style globally)? Thanks

**Comment by tomexx** [comment]
@matejzak Trade button + more icon updated (globally)

**Comment by sorooris** [comment]
**QA OK**

 - [x] Increase font size for the fiat value (from 20 to 24px) Zeplin
 - [x] Tabs for Overview and Details (i.e. remove 3 dots account menu)
 - [x] Turn tabs into secondary buttons for Send, Receive, Trade
 - [x] ‹ Back button for expanded Send, Receive, Trade views Zeplin
 - [x] Sticky account header Zeplin

However some issues have emerged in relation to these changes and they're tracked in the #3607 and #3614 issues.

Suite: 21.4.1 3ed454e
OS: macOS Big Sur 11.2.3
Device: model One 1.9.4 ffa96205f
