### ISSUE TITLE
Do not log Bridge not running as ERROR

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3350]
**Describe the bug**
This is very nit-picky but since it is expected that Bridge might not be running we should not report an error (rather an `info` or `debug`) in the log.

```
2021-02-05T16:46:46.896Z - ERROR(process-trezord): Status error: request to http://127.0.0.1:21325/ failed,
reason: connect ECONNREFUSED 127.0.0.1:21325
```

**Steps to reproduce:**
1. Turn off Bridge
2. Launch Suite

**Info:**
 - Suite version: desktop 21.2.1 (a63b29d19ff08ece94be28d2997d4265ac1c84fc)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.2.1 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.3 regular

**Comment by nappex** [comment]
I'v got same error when I want to startup TrezorSuite on my Fedora by this [tutorial](https://wiki.trezor.io/Apps:Trezor_Suite#How_to_run). GUI of trezor suite've started anyway but it does not recognize my Trezor HW wallet which has connected already. When I wanna install `dbuv` buttons as download or other link does not working at all.

Error text:
```shell
ERROR(process-trezord): Status error: request to http://127.0.0.1:21325/ failed, reason: connect ECONNREFUSED 127.0.0.1:21325
```

**Reproduce**

- [download](https://suite.trezor.io/web/static/desktop/Trezor-Suite-21.6.1-linux-x86_64.AppImage) AppImage for linux
- `$ chmod u+x Trezor-Suite-21.6.1-linux-x86_64.AppImage`
- `$ ./Trezor-Suite-21.6.1-linux-x86_64.AppImage`


**Info:**

- Suite version: Trezor-Suite-21.6.1-linux-x86_64.AppImage
- OS: Fedora 34 X86_64
