### ISSUE TITLE
Send dialogue - missing delivery time in DGB send dialogue

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3352]
**Describe the bug**
I was only able to reproduce this issue with DGB, other coin send dialogues looks OK,
Looks like TX confirmation time of transaction can't be correctly estimated.  

**Info:**
 - Suite Version: web, commit a63b29d19ff08ece94be28d2997d4265ac1c84fc 
 - Browser: Firefox , version 82.0.3 (64-bit)
 - OS: Nixos
 - Firmware Version: 1.9.4model one

**Steps to reproduce:**
1. Send DGB TX
2. Send other coin TX
3. compare send dialogues

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/107151712-3ca4a000-6964-11eb-9ae8-230be0c98d48.png)

![photo_2021-02-07_16-49-52](https://user-images.githubusercontent.com/31506317/107151752-88574980-6964-11eb-8122-49d478cca108.jpg)

**Comment by bosomt** [comment]
@slowbackspace @tomexx is this correct behavior ?

0 is not diplayed any more but here is no dlivery time info in Confirm TX modal even estimated time is displayed in send modal

DGB: NOK
DOGE: OK
DASH: OK

Nixos 
Suite app commit 20f555fcbfb0d833c1c12d0d20207450b2c42e47

![image](https://user-images.githubusercontent.com/31506317/107285241-27606c00-6a5f-11eb-960f-609398cc9b97.png)
![image](https://user-images.githubusercontent.com/31506317/107285277-31826a80-6a5f-11eb-82a9-a3f86d92b13c.png)

**Comment by sorooris** [comment]
It seems only the 0 was removed but the estimated time / delivery is still not present in the new Send dialog.

Let's move this to and resolve it in the March release pls.

**Comment by slowbackspace** [comment]
huh, I assumed the zero was some kind of brain fart on the backend. I guess @tomexx handled that case by hiding the info.
Root cause will be something deeper (blockbook/connect - I am not sure from where are we getting this info).

**Comment by tomexx** [comment]
> huh, I assumed the zero was some kind of brain fart on the backend. I guess @tomexx handled that case by hiding the info.
> Root cause will be something deeper (blockbook/connect - I am not sure from where are we getting this info).

Yes, I just made a quick fix so the frontend doesn't look ugly in such cases, but we'll need to dig deeper as you said. However not sure where to look exactly.
