### ISSUE TITLE
Difference in fee rate between transaction detail modal and send form

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3355]
**Describe the bug**
Fee rate shown in Transaction details modal is different from the cusom fee filled in send form (and shown in review modal)
**Info:**
 - Suite Version: fa056457fde7042c06cdb75ef7772243942a5433

**Problem**: fee calculation based on tx.size instead of vsize. 
Prerequisite: https://github.com/trezor/blockbook/issues/559 (We'll wait for implementation of vsize field on the backend side of things)

<img width="863" alt="Screenshot 2021-02-08 at 11 01 00" src="https://user-images.githubusercontent.com/6961901/107208504-faca3700-6a01-11eb-9408-466b277647e1.png">
<img width="1014" alt="Screenshot 2021-02-08 at 11 01 14" src="https://user-images.githubusercontent.com/6961901/107208506-fb62cd80-6a01-11eb-8a1d-4d06210abe27.png">
<img width="826" alt="Screenshot 2021-02-08 at 11 01 25" src="https://user-images.githubusercontent.com/6961901/107208508-fbfb6400-6a01-11eb-96b8-14033f53f477.png">

**Comment by jerechinsky** [comment]
@trezor/qa could you please retest?

**Comment by bosomt** [comment]
@alex-jerechinsky same behvior, see screenshots 11 vs 9 and 5 vs 4

**QA NOK**

**Info:**
 - Suite version: web 21.7.0 (b0ea8be015a610b83246d99a57761105259ea84f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.10.1 regular

_TBTC_12

![image](https://user-images.githubusercontent.com/31506317/123253482-d0c76c00-d4ed-11eb-84b7-4c1a5e1b793e.png)

![image](https://user-images.githubusercontent.com/31506317/123253532-dfae1e80-d4ed-11eb-8b18-0341694addf6.png)

![image](https://user-images.githubusercontent.com/31506317/123253586-ec327700-d4ed-11eb-84d8-198da126aaf6.png)

_BTC_

![image](https://user-images.githubusercontent.com/31506317/123253851-39164d80-d4ee-11eb-8d4f-2b93498888bd.png)

![image](https://user-images.githubusercontent.com/31506317/123253907-4d5a4a80-d4ee-11eb-97e3-90442d145e52.png)

**Comment by jerechinsky** [comment]
Blocked by https://github.com/trezor/blockbook/issues/559

**Comment by tsusanka** [comment]
Moved to product - I believe this a feature request and should be prioritized by the product team. Also note this makes sense to do along with https://github.com/trezor/trezor-firmware/issues/1294.

**Comment by bosomt** [comment]
**QA NOK**

I just sent 12sat/b tx

| Location | Value |
| --- | --- |
| Device | 12 sat/b |
| Send dialogue | 12 sat/ |
| Transaction detail | 9 sat/b |
| Blockbook: Size / vSize | 162 / 111 |

<img width="696" alt="image" src="https://user-images.githubusercontent.com/31506317/189083827-ada889a6-49ef-4d45-bcf9-6b6f29a968b7.png">


https://tbtc2.trezor.io/tx/a0142828ac2fa4586591b1b5ec257206288eee550a5ac3a6fad562cc4127aa0f


**Info:**
 - Suite version: desktop 22.9.1 (32cfc5c61076fd9b38389efb1ec2aee2cc0b94f3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.9.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA OK**

<img width="700" alt="Screenshot 2022-09-15 at 12 52 28" src="https://user-images.githubusercontent.com/31506317/190386024-fdedadf0-e30c-4962-8808-7bd22708909c.png">
<img width="660" alt="Screenshot 2022-09-15 at 12 52 11" src="https://user-images.githubusercontent.com/31506317/190386032-fb2c78fe-07e7-429b-aaac-6a1e4247cb81.png">

**Info:**
 - Suite version: web 22.10.0 (6b3a8313662341dafbff972b5c2577c8dfebc8d2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
 - OS: MacIntel
 - Screen: 1848x1155
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA NOK**

Fee rate - NaN sat/B

<img width="693" alt="Screenshot 2022-09-15 at 12 54 57" src="https://user-images.githubusercontent.com/31506317/190386487-66bdab35-5c41-49df-90d6-fa1b6df9ee26.png">
<img width="666" alt="Screenshot 2022-09-15 at 12 54 41" src="https://user-images.githubusercontent.com/31506317/190386499-d1d0189a-95b6-4b9e-8733-c66b963578f8.png">

Info:

    Suite version: web 22.10.0 (https://github.com/trezor/trezor-suite/commit/6b3a8313662341dafbff972b5c2577c8dfebc8d2)
    Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
    OS: MacIntel
    Screen: 1848x1155
    Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
    Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.0 (da1945300f7e7497d23eef27030f0c31a6efb43b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision eb182b923f39111d9307a25a86a49d395c6611b0)
 - Transport: bridge 2.0.32
