### ISSUE TITLE
24-hour clock

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3359]
We (incorrectly) use combination of 12-hour clock and 24-hour clock format in Transactions history and other places across the app. 

- [ ] Let's use the less ambiguous 24-hour clock only: https://en.wikipedia.org/wiki/24-hour_clock 

- [ ] Also please use the same date | time format across the app: `Feb 08, 2021  ·  15:35`

TX detail:
<img width="286" alt="Screen Shot 2021-02-08 at 15 29 31" src="https://user-images.githubusercontent.com/29627086/107233265-b0a57d80-6a22-11eb-9df6-e8b3c5313b04.png">

Notifications / Activity:
<img width="264" alt="Screen Shot 2021-02-08 at 15 28 54" src="https://user-images.githubusercontent.com/29627086/107233267-b13e1400-6a22-11eb-8a01-6e245df000f3.png">

FYI the 'US' 12-hour clock (AM/PM format) is to be added as an option in the Settings later, let's not worry about that in this issue. We need to add more options to Settings anyway, so let's do it then.

**Comment by keraf** [comment]
This task kind of overlaps with this https://github.com/trezor/trezor-suite/issues/2294

It would be nice to have a setting to define currency, time and date formatting independently from the chosen language.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.3.0 (7a6dec13f1481ab0cd92bb567e45359d6570ef62)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.6 regular
