### ISSUE TITLE
Suite Landing page - Invity part update

### ISSUE THREAD

**Issue by IvaFingerova** [trezor/trezor-suite#3361]
Invity section on the [Suite landing page](https://suite.trezor.io/) mentions only buy and exchange and both are tagged SOON - which is an obsolete information :)
<img width="1248" alt="Screenshot 2021-02-08 at 15 44 42" src="https://user-images.githubusercontent.com/8152411/107237813-6f639c80-6a27-11eb-8807-9452deed0501.png">

- [x] Matt will update content in Crowdin app + I'll let you know it is ready

- [x] you may release it any time after 10.2. big release (we will be mentioning Spend feature as done...)

Thanks for your cooperation in advance :)
Iva

**Comment by tsusanka** [comment]
Btw we have already removed Soon in develop, it will be released on Feb 10.

**Comment by IvaFingerova** [comment]
Cool! But we should mention also spend and sell on which we are currently working on...
I've already asked Matt to update the content in Crowdin and will try to push it so we will make it till the release

**Comment by IvaFingerova** [comment]
Crowdin is updated from our side - ready to be released anytime!

**Comment by slowbackspace** [comment]
@IvaFingerova I tried to do crowdin sync and noticed that right now all your edits are in crowdin only as suggestions (you can use filter to show all unapproved msgs). You need to hit approve on them otherwise they won't be updated in the app. 🙇 

<img width="752" alt="Screenshot 2021-02-11 at 16 02 41" src="https://user-images.githubusercontent.com/6961901/107654109-9f5aac00-6c82-11eb-9fa1-dd1351e4f2ee.png">

**Comment by tsusanka** [comment]
@IvaFingerova is this done? Freeze is coming up again (next week)

**Comment by IvaFingerova** [comment]
@tsusanka @slowbackspace thank you so much for the heads up, this could have been a sad situation - Matt is about to approve his own work and I'll let you know this is good to go.

**Comment by IvaFingerova** [comment]
@tsusanka @slowbackspace so the strings are in approved state so we are ready to rock and roll to the freeze :)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.3.0 (a5de8753d2e8a16b1217edb644c7414d176948cc)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
