### ISSUE TITLE
GWEI price in ETH incorrect

### ISSUE THREAD

**Issue by FreeGoldRush** [trezor/trezor-suite#3362]
**Describe the bug**
Suite is recommending 300.33 GWEI for transfer at a cost of 0.060066 ETH ($103.48).  That indicates 1 GWEI is 0.0002 ETH. My understanding is that a GWEI is 0.000000001 ETH.  I am trying to send an ERC-20 token.

**Info:**
 
Windows 10.  Upgraded to latest Suite, Bridge and Trezor 1 firmware today (Feb. 8, 2021).

**Steps to reproduce:**
Run Trezor Suite desktop software.  Go to your ETH wallet.  Go to "send" tab.  Select an ERC-20 token you own.  I am testing a send of 0.01 VEN. (I'm currently attempting to get this converted to VET).

**Expected result:**

A conversion rate of GWEI to ETH of 0.000000001

**Actual result:**
The cost of GWEI is being computed incorrectly as described above.

**Comment by prusnak** [comment]
> The Trezor website says 50 GWEI is the max

What do you mean by Trezor website? Which URL?

**Comment by FreeGoldRush** [comment]
"It is possible to adjust the gas price in Beta Wallet. It is capped at 50 GWEI..."
https://wiki.trezor.io/New_cryptocurrencies_in_Beta_Wallet

**Comment by prusnak** [comment]
> https://wiki.trezor.io/New_cryptocurrencies_in_Beta_Wallet

I removed the section about the fees - it's getting obsolete soon and it doesn't make sense to update the wiki everytime there is a surge increase in fees.

**Comment by prusnak** [comment]
@trezor/qa can you please test with the latest 21.2.1 RC?

**Comment by bosomt** [comment]
@prusnak these are recommended fees when i try to send ERC20 token in latest RC

![image](https://user-images.githubusercontent.com/31506317/107287707-9b504380-6a62-11eb-941f-fb0c884f51b5.png)
![image](https://user-images.githubusercontent.com/31506317/107287737-a5724200-6a62-11eb-80c8-964c4550da61.png)


**Info:**
 - Suite version: desktop 21.2.1 (20f555fcbfb0d833c1c12d0d20207450b2c42e47)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Comment by prusnak** [comment]
The screen looks good to me now - Gas price needs to be multiplied by Gas limit to get the total fee. @FreeGoldRush do you agree it's OK now?

**Comment by FreeGoldRush** [comment]
That is definitely not what I'm getting.  Not working here.  I'll install 21.2.1 RC and let you know the result.

**Comment by FreeGoldRush** [comment]
Sorry, but where can I download a Windows binary for 21.2.1 RC?  Can't find it.

**Comment by roodsoft** [comment]
I can confirm suite.trezor.io is calculating super high fees.

Example: 

156.51 GWEI
0.031302 ETH
$54.55

**Comment by prusnak** [comment]
> I can confirm suite.trezor.io is calculating super high fees.

@roodsoft Well, that's not a bug - the fees are indeed so high now. See https://etherscan.io/gastracker 

<img width="555" alt="Screenshot 2021-02-09 at 10 48 21" src="https://user-images.githubusercontent.com/42201/107345900-59f08000-6ac4-11eb-8c76-7d6ec3503d0d.png">

**Comment by prusnak** [comment]
> That is definitely not what I'm getting.

@FreeGoldRush You are not getting it, because you don't have the binary. I was asking whether the screenshot looks good to you know.

**Comment by prusnak** [comment]
> Suite is recommending 300.33 GWEI for transfer at a cost of 0.060066 ETH ($103.48). That indicates 1 GWEI is 0.0002 ETH. My understanding is that a GWEI is 0.000000001 ETH.

The computation is correct. You are forgetting you need to multiply the GWEI price by Gas limit which is ~21.000 for transfer transaction. The Ethereum fees are indeed incredibly high now - see https://etherscan.io/gastracker

**Comment by roodsoft** [comment]
Ok, thank you for your answer. I suppose I don't get ETH fees very well yet. The thing that caught my attention is that at the same time a transfer from Binance cost $14 USD (which is high but reasonable) and suite.wallet.io was recommending $118 USD. 

Oh and also I turned to ETH wallet in beta-wallet.trezor.io and the fee was similar to what Binance charged so there's that too. However, I apologize in advance if I'm just not understanding this correctly.
