### ISSUE TITLE
Cant send Dogecoins from Trezor - Failed to send transaction Error details: Requested unknown tx #3311

### ISSUE THREAD

**Issue by Gatorace** [trezor/trezor-suite#3363]
Saw a earlier post that a similar issue was fixed, but I am not able to send even after supposed fix.  Getting this error:  Sign transaction error: requestTxInfo: Requested unknown tx: 331d51ba57b0f6292690e7a286cfcb108348b0f20efbeb98fcbcc80d4b4c7ec4

Any help would be appreciated

**Comment by prusnak** [comment]
This will be fixed in Trezor Suite update on Wednesday (in 2 days).
Meantime you can use wallet.trezor.io to send Doge
