### ISSUE TITLE
Labels only work for 1 wallet at a time

### ISSUE THREAD

**Issue by njm1984** [trezor/trezor-suite#3364]
I can't seem to have both my devices (and their respective wallets) display labels all at once. When adding a wallet, I get the prompt on the device, and my labels appear fine. However, if I add another wallet, approve that prompt, the labels disappear from the _first_ wallet. Sorry if this is a bit confusing - essentially, my Dropbox labels only work for the most recently added wallet. If it matters, I have all my wallets set to "Remember" and have tried ejecting and re-adding.

**Info:**
 - Suite Version: App, Version 20.12.1 (20.12.1.9537)
 - OS: MacOS
 - Firmware Version: Trezor One (1.9.3), Trezor Model T (2.3.4)

**Comment by jerechinsky** [comment]
Thanks for submitting the issue, @njm1984. Could you please try again with the latest release? If it still doesn't work, could you please describe precisely what are you clicking on when adding the labels, so we can try and reproduce on our side ?

**Comment by njm1984** [comment]
Hi @alex-jerechinsky - thanks for your reply! I just tested this again from a fresh setup on the new version, 21.2.3 - and all labels now work simultaneously! Awesome. Thanks again!

**Comment by bitofit** [comment]
@alex-jerechinsky I'm still experiencing this issue after updating Trezor Desktop Suite to 21.2.3
Two wallets both set to remember.  A Model One and a Model T.
I've tried re-connecting Dropbox to see if that was the issue without success.

The Model T is the one which "forgets" the labels.  I'm pretty sure this is related to the Model T using a passphrase and the Model One not.

When I click my wallet on the top left, then click "Rename" next to the Model T wallet 1, a message "flashes" on my Model T screen then disappears.  Pretty sure it's the message asking me to type in my passphrase.

**Comment by njm1984** [comment]
@alex-jerechinsky Wanted to follow up here. All the labels work in Trezor Suite now - however, something changed on the web browser. My _newest_ labels don't show up on the browser, whereas they _do_ show up in Suite.

I did some testing, and I noticed that the browser wallets now use a different file in my Dropbox folder. I can see the label files that Suite used because if I edit one, Dropbox updates and says last modified "just now." If I do the same thing (same wallet, same account) on the web browser, a completely different file gets modified!

If I delete the "new" file that the web wallet is accessing, it repopulates. Everything works on Trezor Suite currently, but my labels on the web wallet are sort of half-synced.

**Comment by slowbackspace** [comment]
> @alex-jerechinsky Wanted to follow up here. All the labels work in Trezor Suite now - however, something changed on the web browser. My _newest_ labels don't show up on the browser, whereas they _do_ show up in Suite.
> 
> I did some testing, and I noticed that the browser wallets now use a different file in my Dropbox folder. I can see the label files that Suite used because if I edit one, Dropbox updates and says last modified "just now." If I do the same thing (same wallet, same account) on the web browser, a completely different file gets modified!
> 
> If I delete the "new" file that the web wallet is accessing, it repopulates. Everything works on Trezor Suite currently, but my labels on the web wallet are sort of half-synced.

By web wallet you mean wallet.trezor.io or suite.trezor.io? We've noticed some problems on wallet.trezor.io and we are currently working on a fix.

**Comment by armujahid** [comment]
I am also facing similar issue. I added labels using Trezor-Suite-21.3.1 Linux app image but they are not showing on https://suite.trezor.io/ although both are connected with my Google account.

**Comment by jerechinsky** [comment]
@trezor/qa could you please try to replicate / whether labels sync across suite web and suite desktop?

**Comment by bosomt** [comment]
I was not able to reproduce issue.

Created new label via app and it appeared in web suite, changed it via web suite and it changed in few seconds in suite app.
Used Google Drive to store labels.


**Info:**
 - Suite version: web 21.4.1 (1baa8ced16f2f6a5d60e9f4d7911669f856123d8)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.3.5 regular


![image](https://user-images.githubusercontent.com/31506317/114730281-03f8bc80-9d41-11eb-89a9-e58f26a40437.png)
![image](https://user-images.githubusercontent.com/31506317/114730403-2094f480-9d41-11eb-80c7-f9c8eed10ded.png)

**Comment by STew790** [comment]
I can confirm, couldn't reproduce the issue.

Same steps as @bosomt mentions, created label in app and it appeared in web version. Changed it in web version and appeared in app. I also used Google Drive.

Info:

- Suite version: web 21.4.1 (1baa8ced16f2f6a5d60e9f4d7911669f856123d8)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
- OS: Windows 10
- Device: model T 2.3.5 regular
- Screen 1440x900

**Comment by bitofit** [comment]
> @trezor/qa could you please try to replicate / whether labels sync across suite web and suite desktop?

This was never the issue.  The issue was that labels work for 1 trezor at a time.

**Comment by jerechinsky** [comment]
> > @trezor/qa could you please try to replicate / whether labels sync across suite web and suite desktop?
> 
> This was never the issue. The issue was that labels work for 1 trezor at a time.

Apologies. I was swayed by armujahid's comment but I will look further into this.

**Comment by bosomt** [comment]
I was able to reproduce issue.
Deleted whole Suite config dir and used only locally stored labels so there won't be any clash with previously created labels in cloud

1) loaded standard wallet, enabled labeling and created account name/label
2) loaded passphrase wallet, enabled labeling and created account name/label
3) went to standard wallet, labels were still present
4) move back and forth and Standard wallet labels were gone even labeling was still enabled

See screenshots 

![image](https://user-images.githubusercontent.com/31506317/114837925-7ebee780-9dd4-11eb-8fc8-5604dc1c6433.png)

![image](https://user-images.githubusercontent.com/31506317/114837994-8ed6c700-9dd4-11eb-9da9-41736ba98fcd.png)

![image](https://user-images.githubusercontent.com/31506317/114838074-a1e99700-9dd4-11eb-9906-b68a16f15255.png)

![image](https://user-images.githubusercontent.com/31506317/114838799-5daac680-9dd5-11eb-8648-2246a90f711c.png)


**Info:**
 - Suite version: desktop 21.4.1 (1baa8ced16f2f6a5d60e9f4d7911669f856123d8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.3.5 regular

**Comment by jerechinsky** [comment]
I just tried to replicate and couldn't. Could you please try again sometime, @bosomt ?

**Info:**
 - Suite version: desktop 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.10.3 regular

**Comment by bosomt** [comment]
**QA OK**

i was not able to replicate issue any-more. Looks like it was already fixed.

**Info:**
 - Suite version: desktop 21.9.1 (8b28b4c5df6eebb039ee30a35fab0016dd30679a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 Bitcoin only

**Comment by bosomt** [comment]
**QA NOK**

i was able to reproduce issue.
Labels for Standard wallet are gone again :)
Used local storage for labels.

<img width="808" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/132828622-148e8693-92e1-441e-b6a5-85722416045f.png">

**Comment by wendys-cats** [comment]
**QA NOK - Confirming for Win10** 
 
Clean install (cleared and deleted everything before testing)
Connected device with hidden wallet, enabled labeling and created labels. Connected second device with standard wallet (different seeds), enabled labeling and created labels. Returned to first device's wallet and labels were gone. 
 
**Suite:** APP  21.9.1 8b28b4c5df6eebb039ee30a35fab0016dd30679a
**Device:** 2.4.1 regular and 2.4.0 regular. 
**OS:** Windows 10

**Comment by mroz22** [comment]
so, this happens only when storing data locally? or does it happen for any "data provider"?

**Comment by bosomt** [comment]
@mroz22 so far it looks like problem with local storage labels. I was not able to reproduce issue with Google storage

**Comment by STew790** [comment]
**QA OK**

I tried this with Dropbox as well as Google drive.

**Info:**
 - Suite version: web 21.11.0 (9b398dbee120846b7efe9522b6a66b175daaee2f)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
 - OS: Win32
 - Screen: 1440x900
 - Device: model T 2.4.2 regular
