### ISSUE TITLE
ETH transactions sometimes don't display fiat amounts

### ISSUE THREAD

**Issue by njm1984** [trezor/trezor-suite#3365]
Some ETH transactions don't show the fiat amount (see screenshot).

**Info:**
- Suite Version: App, Version 20.12.1 (20.12.1.9537)
- OS: MacOS
- Firmware Version: Trezor One (1.9.3), Trezor Model T (2.3.4)

**Screenshots:**
![ethbug](https://user-images.githubusercontent.com/27410673/107287384-bbf2ac00-6a16-11eb-9cb3-a36cbe9a75d4.jpg)

**Comment by slowbackspace** [comment]
Hi! Thanks for the report! I'll look into it.
As a workaround, ejecting remembered wallet (if it is remembered) and running account discovery process should fix the issue for you.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.6.0 (b65e29291276cd6a03c2fa8035966139a2847f90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular

**Comment by wendys-cats** [comment]
**QA OK**

**Info:**

**Suite** version: web 21.6.0 4f358fd151fc1962f30f84a855b82213d958aae7
**Browser**: Version 88.0.4324.182 (Official Build) (64-bit)
**OS**: NixOS 21.03
**Device**:  TT 2.4.0 regular
