### ISSUE TITLE
Transaction detail - amount different compared to transaction history

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3366]
**Describe the bug**
In sending transaction detail total input is lower than sent amount. 

**Steps to reproduce:**
1. send tx
2. compare tx detail in sending and receiving account

**Info:**
 - Suite version: desktop 21.2.1 (20f555fcbfb0d833c1c12d0d20207450b2c42e47)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.2.1 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Expected result:**
Amount is same in receiving and sending account
**Actual result:**
Amount is different in transaction detail 

**Screenshots:**
![image (4)](https://user-images.githubusercontent.com/31506317/107368085-6551a480-6ae0-11eb-80b3-9d7e5bdf832e.png)
![image (3)](https://user-images.githubusercontent.com/31506317/107368089-684c9500-6ae0-11eb-9b9a-c64f98e34b93.png)
![image (2)](https://user-images.githubusercontent.com/31506317/107368094-6b478580-6ae0-11eb-9cc0-7cba7f1716c5.png)
![image (1)](https://user-images.githubusercontent.com/31506317/107368097-6be01c00-6ae0-11eb-82a2-7358b17c2b8f.png)

**Comment by szymonlesisz** [comment]
totalInput and totalOutput should availailable in `tx.details` for some time now:
https://github.com/trezor/trezor-suite/blob/develop/packages/blockchain-link/src/workers/blockbook/utils.ts#L150-L151

**Comment by slowbackspace** [comment]
this should be also fixed as side effect of https://github.com/trezor/trezor-suite/issues/3412

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.3.0 (b6c84eb9e23f9483d25ff4cb4a96a4c357596a24)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.3.0 Chrome/87.0.4280.141 Electron/11.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
