### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#3368]
### 🚀   New features

- RBF with on-device support 
- Transaction search
- Spend crypto through Bitrefill vouchers 
- Option to add custom ERC20 tokens
- Custom fee in ETH

### 🎨 Improvements 

- Redesigned review and send transaction modal
- M1 Mac compatibility 

.. and much more!

**Comment by slowbackspace** [comment]
nothing to see here

**Comment by jerechinsky** [comment]
Shush! As awesome as this feature is, it was initially meant to be an easter egg courtesy of @keraf.

**Comment by szymonlesisz** [comment]
- custom gas limit in ETH
