### ISSUE TITLE
Accounts discovery - Skeletons not removed after loading is finished

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3370]
**Describe the bug**
Non-animated placeholder graph and accounts are displayed after accounts discovery (seemingly?) finished.

**Info:**
 - Suite Version: app 21.2.1 20f555fc
 - OS: macOS Big Sur 11.2
 - Firmware Version: model T 2.3.4

**Steps to reproduce:**
N/A - couldn't replicate again, occured during #3218 retest.

**Expected result:**
Placeholders are removed after accounts discovery's finished.

**Actual result:**
Non-animated placeholder accounts were displayed after discovery had finished.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/107425010-b1bbd500-6b1e-11eb-9dc3-0a5aebb32c0f.png)
![image](https://user-images.githubusercontent.com/10185314/107425016-b4b6c580-6b1e-11eb-9c03-44d835e8bb03.png)

**Note(s):**
Occured on an hidden wallet / passphrase with a high number of accounts with tx history; tested immiedately with other hidden wallet / passphrase with just a few accounts (BTC, ~2 of each account type). Please note that the issue didn't occur again after relaunch.

**Comment by slowbackspace** [comment]
hmm that's weird, skeleton on the dashboard will show only if `discoveryStatus.status === 'loading'`, same thing in accounts menu, that would technically mean discovery hasn't stopped yet, or we failed to update its status, or it is something completely different 😁

Actually, the info that the skeletons were not animated is really helpful. Animation is disabled when there is some modal window active or when we are waiting for a device (either no device selected or device is without state - eg. waiting for passphrase). Super weird!
@szymonlesisz could it be somehow related to https://github.com/trezor/trezor-suite/pull/3354?

I'm not gonna dig into this more right now, I would keep the issue open and if it happens again, then we'll start with debugging. For now it looks super random.

**Comment by sorooris** [comment]
It's called skeletons?! Love that! :smile:

**Comment by slowbackspace** [comment]
@trezor/qa is it reproducible already? If not then I don't know if it should be a high priority 🤷‍♂️

**Comment by slowbackspace** [comment]
@sorooris are you sure that discovery process was completed? I am trying to reproduce it with TOR enabled, and it loads so slowly that I could totally tell you that discovery is completed and I still see skeletons but the truth is discovery is still running but veery slow. btw it is also weird that I don't see progress bar for the discovery at the top.

Better question, Did this happen with TOR?

**Comment by sorooris** [comment]
@slowbackspace oh god i've just noticed that Tor is enabled in my screenshots. Yeah the thing is I was retesting the #3218 issue and I kept toggling it on/off and I thought I had it off when the skeletons did not disappear.

**Comment by slowbackspace** [comment]
@sorooris 😁  no problem, I'll close this for now as I am like 99% sure discovery was still running (or in some ugly state)and this is stupid TOR related thingy. But if you notice it again with tor disabled please reopen it. Thank you! 🙇

**Comment by sorooris** [comment]
@slowbackspace thanks and sorry for the confusion/spook :sweat_smile:

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.3.0 (a0f694411d85fca4a35acedbdf3b07702517c120)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
