### ISSUE TITLE
Cardano support directly in Trezor Suite

### ISSUE THREAD

**Issue by SvenBudak** [trezor/trezor-suite#3371]
When i check: https://trezor.io/coins/ is for Cardano only AdaLite , Yoroi Listed.
There are any plans for a direct integration in Trezor Suite?

**Comment by glacierbits** [comment]
Duplicate #3550

**Comment by melroy89** [comment]
Actually daedalus should be listed as well imo

**Comment by melroy89** [comment]
Thank you Five Binaries (@fivebinaries) and Cardano Foundation (@cardano-foundation) for the cardano code and support. Good job!
