### ISSUE TITLE
Ability to dump state of the reducers to speed up troubleshooting

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3372]
Once again I came across an issue where I wanted to see content of suite reducers to better understand what could possibly trigger reported error, but I couldn't.

It would be really helpful if, at least, QA had the option to export a snapshot of the app state right when the error is present. That would make debugging problems like https://github.com/trezor/trezor-suite/issues/3370 or https://github.com/trezor/trezor-suite/issues/239#issuecomment-762968914 much faster.

To prevent some malicious misuse I would put a button in our hidden debug settings with big banner saying if you don't know what you are doing/our you've been instructed to go there then GTFO. We could go as far as to only add this to non-signed builds (for the desktop app), but I am not sure if there is a trivial way doing this without remembering to manually switch feature flag off before the final build.

In the https://github.com/trezor/trezor-suite/issues/239#issuecomment-762968914 I argued that state dump could be handy even in production builds. In my opinion it will provide much more information about an error user is experiencing.
Current system of logging certain events has 2 major problems:
- we can't store every event (there are too many of them), chances are the event you would be interested in is simply not there
- we can't log whole payload for each event (too big)
So in the end either events that would help your to debug the problem aren't stored or they are stored without payload so you still don't know what went wrong.

Of course with the state dump we would redact sensitive data (xpubs, balances,...) just like we do in event logger.

**Comment by jerechinsky** [comment]
Not relevant.
