### ISSUE TITLE
ETH transaction detail in Transaction detail shows incorrect fee amount

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#3374]
**Describe the bug**
ETH transaction detail is missing fee amount (ETH and FIAT), it is set to zero (see screens). When creating the transaction, Suite correctly displays fee amount, this only applies to Overview>Transactions>Transaction detail. Appears to happen only to unconfirmed transactions.

**Info:**
 **- Suite Version:** web 21.2.1 20f555fcbfb0d833c1c12d0d20207450b2c42e47  AND 20.12.1 be4e3a36f7dbe15b2b203f66de11edc50a6665b8 (**current release**)
 - Browser: , version: Chromium Version 86.0.4240.193 (Official Build) (64-bit)
 - OS: NixOS 21.03
 - Firmware Version: model , revision: T1 1.9.4 

**Steps to reproduce:**
1. Create ETH transaction
2. Open transaction detail

**Expected result:**
Correct fee amount (in FIAT and coin) will be displayed.

**Actual result:**
Zero fee amount is displayed.

**Screenshots:**
staging
![image (2)](https://user-images.githubusercontent.com/58593111/107506723-ccce2980-6b9e-11eb-8d6a-efe3d0afedd6.png)
![image (3)](https://user-images.githubusercontent.com/58593111/107506727-ce97ed00-6b9e-11eb-97f3-da07a95f43d0.png)

production
![image (4)](https://user-images.githubusercontent.com/58593111/107506653-ac9e6a80-6b9e-11eb-9a16-2369af87c0d2.png)
![image (5)](https://user-images.githubusercontent.com/58593111/107506938-1e76b400-6b9f-11eb-91da-2295c769f1e0.png)

**Comment by slowbackspace** [comment]
ha! this could be actually legit cause we don't know the exact fee spent till ETH transaction is mined/confirmed. So it needs to be handled in the UI, showing n/a or something more user-friendly. We could calculate max fee that could be spent (gas limit * gas price?), but be aware that the real fee, after tx gets mined, could be different.

you know whaat, for this small usecase (while eth tx is pending) I think it would be totally fine to  just hide the field

cc @matejzak

**Comment by slowbackspace** [comment]
this isfixed as an side effect of one of changes in blockchain-link https://github.com/trezor/trezor-suite/commit/4628d7cee449639c8c7d2858bb783b6cf4375864#diff-fa760cfad5081fa4c810e0a07f72e98411565fc53b1c8971a34e91a74278980e

**Comment by bosomt** [comment]
**QA NOK**

yes ETH txs FIAT information is now present. But Not in ERC20 token transactions.


**Info**

KUbuntu Linux 20.04
Suite app commit 1dbc5b720515c39a47f1dc58391dbebf1d766394

**Screenshots**
![image](https://user-images.githubusercontent.com/31506317/110320007-f3517a00-800f-11eb-8491-699f65b48dd4.png)

![image](https://user-images.githubusercontent.com/31506317/110320298-5d6a1f00-8010-11eb-82f6-133224a4d97c.png)

![image](https://user-images.githubusercontent.com/31506317/110320102-1da33780-8010-11eb-9b7d-5f5ad9466d43.png)

**Comment by bosomt** [comment]
**QA NOK**

+ still missing tx historic fiat detail info 
+ missing fiat price in tx history even I see it in tx detail

**Info:**
 - Suite version: web 21.4.0 (1da73bf5c45ed462662a4b3f12b10993625b9999)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular



![image](https://user-images.githubusercontent.com/31506317/111162074-1514a900-859c-11eb-8d5d-3ffc8ea6b854.png)


![image](https://user-images.githubusercontent.com/31506317/111162320-56a55400-859c-11eb-9243-943d0526b14d.png)

**Comment by slowbackspace** [comment]
Wrong issue to reopen! Original issue was regarding zero fees 😁 

> still missing tx historic fiat detail info
> missing fiat price in tx history even I see it in tx detail

I believe we've never supported historical rates for tokens, that's why you don't see them.

**Comment by bosomt** [comment]
OK. Closing and approving then.
