### ISSUE TITLE
Transaction history - Typing into the search input during discovery crashes render (aka White Screen of Death)

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3376]
**Describe the bug**
Typing into the Transaction history search input crashes the render process; I am unable to determine what exactly does it. Also, none of the typed characters are displayed.

**Info:**
 - Suite Version: app 21.2.1 20f555fc
 - OS: macOS Big Sur 11.2
 - Firmware Version: model T 2.3.5 ffa96205f

**Steps to reproduce:**
1. Add a hidden wallet with a long tx history,
2. Navigate to an account's transaction history aka Overview screen,
3. Start immediately typing a long string of characters into the search input **during discovery,**
4. Observe.

**Expected result:**
Terminal displayes a Render process gone (reason: crashed) error and the Suite windows goes completely white.

**Actual result:**
Search input behaves as intended.

**Logs:**
[macos_log_search-crash.txt](https://github.com/trezor/trezor-suite/files/5958085/macos_log_search-crash.txt)
[macos_log_search-crash2.txt](https://github.com/trezor/trezor-suite/files/5958086/macos_log_search-crash2.txt)

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/107509308-a7431f00-6ba2-11eb-9956-7d63841f2a3c.png)
![image](https://user-images.githubusercontent.com/10185314/107509330-b0cc8700-6ba2-11eb-89aa-fec9fc6025cb.png)

**Comment by sorooris** [comment]
Per @keraf's request, the machine's setup:

Platform: darwin x64
OS: macOS 11.2
Manufacturer: Apple Inc.
Model: MacBookAir7,2
Virtual: No
CPU: Intel® Core™ i5-5350U
Cores: 1x2(+2) @ 1.80GHz
RAM: 8.0 GB

**Comment by STew790** [comment]
Just happened to me as well on this setup:

OS: Windows 10 Version 10.0.19042.804
CPU: Intel Core i5-4460 3.2GHz
RAM: 16GB

otherwise the same setup as @sorooris 

My RAM usage went way up
![image](https://user-images.githubusercontent.com/48477147/107516452-baf38300-6bac-11eb-8a51-d3e5e28310a2.png)

**Comment by sorooris** [comment]
**QA OK**

Couldn't replicate WSoD, however as there is still no character limit in the search input. pasting loads of them results in [high CPU usage](https://github.com/trezor/trezor-suite/issues/3214). Created [separate issue](https://github.com/trezor/trezor-suite/issues/3428#issue-810216738) for the limit.
![image](https://user-images.githubusercontent.com/10185314/108213848-c0fade00-712f-11eb-8a06-83e3c9022ae8.png)

Suite Version: app 21.2.3 9cf47b5
OS: macOS Big Sur 11.2.1
Firmware Version: model T 2.3.5 ffa96205f
