### ISSUE TITLE
Stuck at loading while bridge responding with 400 (specific case with multiple instances running)

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3379]
**Info:**
 - Suite Version: desktop, just released, but probably valid for older version too
 - OS: macos

**Steps to reproduce:**

1. make sure bridge is not running
2. connect device, go to suite.trezor.io (in Chrome), click find trezor, leave it at passphrase modal
3. open desktop app

**Expected result:**
Either suite starts properly or UI informing the user what is happening

**Actual result:**
stuck at loading, clearing storage wont help ofc.

**Screenshots:**
<img width="1282" alt="Screenshot 2021-02-10 at 16 41 27" src="https://user-images.githubusercontent.com/6961901/107533188-f72fdf00-6bbe-11eb-8414-48cc92ba8d47.png">

I am not sure if this has sane case that could be reproduceed (maybe user is running web version and then downloads desktop one and tries to launch it)

**Comment by jerechinsky** [comment]
@slowbackspace You mentioned that clearing storage didn't help. Does that mean that this issue is reproducible and persisted over restarting Suite or was this a one time occurrence ?

**Comment by jerechinsky** [comment]
Sorry. Only noticed the text below the screenshot now. I couldn't reproduce it myself by running Web Suite and opening freshly installed Desktop Suite. I will leave this to rot here for now and see if it comes up again.

**Comment by slowbackspace** [comment]
I think I can reproduce it, at least on my machine
1. make sure bridge is not running
2. connect device, go to suite.trezor.io (in Chrome, for that sweet webUSB), click find trezor, leave it at passphrase modal
3. open desktop app

it will get stuck at loading, I will update original description

@trezor/qa could you confirm?

**Comment by keraf** [comment]
What's in the response of those 400s?

**Comment by wendys-cats** [comment]
**QA confirms for:**
 - Windows on 21.2.1 Suite with 2.0.30 bridge bundled 

**Bug is NOT present in latest release (7e8958e206885cd7946f431b63dad3bd446ef82e) where bridge 2.0.27 is bundled (confirmed on Win and Nix)**

@slowbackspace, were you using 21.2.1 version? commit 20f555fcbfb0d833c1c12d0d20207450b2c42e47 (version before hotfix)
 
 **BUG PRESENT** 
 OS: Win 10.0.19042.804
 Suite: APP 21.2.1 20f555fcbfb0d833c1c12d0d20207450b2c42e47
 Device: T1 1.9.4 public
  http://127.0.0.1:21325/status/ shows 2.0.30
 
 Steps:
 1.Kill trezord (uninstall on Win)
 2. Open suite.trezor.io
 3. Connect device, stop at Passphrase modal
 4. Open Suite APP
 5. See Suite crash
 Note: Clear cache button did not help. Clearing cache manually from user/appData (Local and Roaming) did not help (it will load the onboarding for Suite, but after that Suite will still crash). Only after closing web suite version did Suite APP start properly and 127.0.0.1 shows trezor bridge status 2.0.30.
 
 **BUG NOT PRESENT IN LATEST**
 OS: Win 10.0.19042.804
 Suite: APP 21.2.2 7e8958e206885cd7946f431b63dad3bd446ef82e
 Device: T1 1.9.4 public
  http://127.0.0.1:21325/status/ shows 2.0.27
 
 Steps:
 1.Kill trezord (uninstall on Win)
 2. Open suite.trezor.io
 3. Connect device, stop at Passphrase modal
 4. Open Suite APP
 5. See Suite crash
 
 **BUG NOT PRESENT**
 OS: Win 10.0.19042.804
 Suite: APP 20.12.1 e16f9ff0d8455d1b3a40f88dd878946fbe8f7115
 Device: T1 1.9.4 public
 
 Steps:
 1.Kill trezord (uninstall on Win)
 2. Open suite.trezor.io
 3. Connect device, stop at Passphrase modal
 4. Open Suite APP
 5. See Suite working
 
 **- NixOS**

**BUG NOT PRESENT in latest app release**
 OS: Nixos 21.03pre252083.2deeb58f494 (Okapi)
 Suite: APP 21.2.2 7e8958e206885cd7946f431b63dad3bd446ef82e
 Device: TT 2.3.5 public
 http://127.0.0.1:21325/status/ shows 2.0.27
 
  Steps:
 1.Kill trezord (systemctl kill trezord.service)
 2. Open suite.trezor.io
 3. Connect device, stop at Passphrase modal
 4. Open Suite APP
 5. See Suite working

**BUG NOT PRESENT in older app release**
 OS: Nixos 21.03pre252083.2deeb58f494 (Okapi)
 Suite: APP 20.10.1 99959260d5639480dfb11e53a4f2ab1d789b0e7b
 Device: TT 2.3.5 public
 http://127.0.0.1:21325/status/ shows 2.0.27
 
  Steps:
 1.Kill trezord (systemctl kill trezord.service)
 2. Open suite.trezor.io
 3. Connect device, stop at Passphrase modal
 4. Open Suite APP
 5. See Suite working

**Comment by slowbackspace** [comment]
hmm, I can still reproduce it even with hotfixed suite.
OS: MacOS 11.2.1
Suite: APP 21.2.2
Device: TT 2.3.5
http://127.0.0.1:21325/status/ shows 2.0.27

body of 400 response from the bridge
```
{error: "LIBUSB_ERROR_ACCESS"}
```

Maybe mac-only issue? @tomexx could you try to reproduce this please?

It would make sense that device is blocked by webusb connection and bridge can't access it, but why we can't reproduce it on every system 🤔

**Comment by keraf** [comment]
I had that yesterday on my fresh Linux install and I was missing the udev rules. Not sure about Mac tho. Any ideas @prusnak ?

**Comment by jerechinsky** [comment]
Couldn't reproduce on my mac even after following the updated steps by @slowbackspace. 🤔 

**Desktop suite.**
 - Suite version: desktop 21.2.2 (7e8958e206885cd7946f431b63dad3bd446ef82e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.2.2 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1080
 - Device: model T 2.3.5 regular

**Web suite.**
 - Suite version: web 21.2.2 (7e8958e206885cd7946f431b63dad3bd446ef82e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1080
 - Device: model T 2.3.5 regular

**Comment by slowbackspace** [comment]
looks like it is something stupid on my machine. sorry to bother you all. closing the issue.
