### ISSUE TITLE
FW update 2.3.4 › 2.3.5 via Suite 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3381]
Suite desktop version: 21.2.1 
MacOS, BigSur: 11.2.1

Please note the FW update itself went OK. This is a Suite issue.

FW update from 2.3.4. to 2.3.5. is stuck on this screen in Suite: 

<img width="1439" alt="Screen Shot 2021-02-10 at 17 26 15" src="https://user-images.githubusercontent.com/29627086/107539864-af608600-6bc5-11eb-88fd-c0fc37bbce54.png"> 

Refresh result: 

<img width="1438" alt="Screen Shot 2021-02-10 at 17 29 36" src="https://user-images.githubusercontent.com/29627086/107540194-12521d00-6bc6-11eb-9fd3-e66e36d548a8.png">
<img width="1441" alt="Screen Shot 2021-02-10 at 17 29 52" src="https://user-images.githubusercontent.com/29627086/107540200-141be080-6bc6-11eb-8682-f2e6e8901377.png">

@trezor/qa Can you please retest?

**Comment by sorooris** [comment]
@matejzak is this related to the[ Bridge issue](https://github.com/trezor/trezord-go/issues/210)? I couldn't replicate the issue on my setup yesterday.

Suite: app 21.2.1 77ce6b1
OS: MacOS Big Sur 11.2.1
Device: Model T 2.3.4 -> 2.3.5

**Comment by glacierbits** [comment]
@sorooris I think it was.. the correct Bridge seemed to have fixed it for me (tested yesterday again). Thanks!

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.3.0 (a0f694411d85fca4a35acedbdf3b07702517c120)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
