### ISSUE TITLE
Discovery progress bar not visible in desktop app

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3382]
Desktop app (macos) is missing a progress bar for discovery process. 
Could it be something with custom titlebar we use in electron?

Web version is ok. 
screen from web version:
<img width="1634" alt="Screenshot 2021-02-10 at 18 20 39" src="https://user-images.githubusercontent.com/6961901/107546500-b50d9a00-6bcc-11eb-9d3b-8c5b7406ce17.png">

electron while discovery is running:
<img width="1524" alt="Screenshot 2021-02-10 at 18 24 28" src="https://user-images.githubusercontent.com/6961901/107546966-39601d00-6bcd-11eb-9678-f8e43006b44a.png">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.3.0 (67cfe9730c8c3daaee58f2760695f2b82183c462)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.3.0 Chrome/87.0.4280.141 Electron/11.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.6 regular
