### ISSUE TITLE
Browser icons broken on https://suite.trezor.io/web/version/ with Unsupported Browser

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#3383]
When I visit https://suite.trezor.io/web/version/ with Unsupported browser (i.e. Safari), the browser icons (Firefox/Chrome) are broken, because they are fetched from https://suite.trezor.io/web/version/static/browser-detection/browser-chrome.png (note the `version` in the URL)

https://suite.trezor.io/web/ looks fine, because the icon is fetch from https://suite.trezor.io/web/static/browser-detection/browser-chrome.png

**Comment by tomexx** [comment]
I found the code here https://github.com/trezor/trezor-wallet/blob/8e9d704e054f857e6a7d3651717fdd443d46a509/src/views/Landing/components/BrowserNotSupported/index.js

We should probably migrate the page to the Suite right?

**Comment by tomexx** [comment]
OK, @slowbackspace found it: https://github.com/trezor/trezor-suite/blob/2866ed43b3efcb76961c548aa7b41e35892a4b1c/packages/suite-data/files/browser-detection/index.js#L58

Thanks!

**Comment by sorooris** [comment]
**QA OK**

Icons fetched correctly.

Suite: 21.3.1 1dbc5b7
Browser: Gnome Web 3.36.4
OS: NixOS 20.09
Device: 2.3.5 public

/web/
![image](https://user-images.githubusercontent.com/10185314/110443166-ebe7aa80-80bb-11eb-85da-722e1c0b6aab.png)
/web/version/
![image](https://user-images.githubusercontent.com/10185314/110443358-1e91a300-80bc-11eb-9daa-8b3a71b12c3c.png)
