### ISSUE TITLE
Update Bridge to newly released 2.0.31

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3384]
To put an end to the bloody 2.0.30.

There is no 2.0.31 yet we need to prepare and test it.

**Comment by tsusanka** [comment]
Sent to QA. But to be on a safe side let's include it **after** the freeze so we can test it whole month "passively" in `develop` and we'll include it in April.

**Comment by bosomt** [comment]
**QA OK**

embedded version ` Version: 2.0.31 (rev 5f53132)  `

**Info:**
 - Suite version: desktop 21.4.0 (ab673f9777b6ddaf13234e5e6b3b3ab5be46852c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular
