### ISSUE TITLE
Add more information to info in issue created by suite

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3393]
**Is your feature request related to a problem? Please describe.**
Add more information to info in issue created by Suite if possible.

- Transport information webusb/bridge
- Bridge version
- firmware revision if possible
- optional attachment of log if logging is enabled in application

**Describe the solution you'd like**
This would help us to replicate and troubleshoot occurred issues and occasionally it could prevent bugfix releases.

**Comment by tsusanka** [comment]
Related: https://github.com/trezor/trezor-suite/issues/3282

**Comment by tsusanka** [comment]
@keraf do you think you could this one for us :innocent:? It would help QA and Support I believe.

**Comment by keraf** [comment]
Yes, always happy to work on things that help our QA and support :slightly_smiling_face:

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.5.0 (0d7ad344555f34f3abbc4fd42116efb7129b3a73)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular (revision 595b14254c1abb2be3f69e42c7932f1eca8cf1b1)
 - Transport: bridge 2.0.31
