### ISSUE TITLE
Find exchange rate of ERC20 token by token address, not by token abbreviation

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#3394]
It seems the exchange rate is matched not by the token address, but by the token abbreviation, leading to wrong exchange rate being used.

Good example is Uniswap (UNI) vs Unicorn (UNI) token, where the Unicorn rate is being used when actually Uniswap rate should've been used.

**Comment by slowbackspace** [comment]
@trezor/qa pls test whole fiat rates functionality as it required a bit of code refactor.
Eg: 
- fiat rates are correctly loaded when launching suite, both for coins and tokens (no all tokens have fiat rates, if fiat rate is missing please compare it to old version of suite, it might be legit).
- fiat rates are periodically updated (both for coins and tokens)
- fiat rates are shown even if you disable internet connection before loading suite (they are stored in db)
And ofc all your standard scenarios that are related to fiat rates

**Comment by bosomt** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/31506317/108605697-25c76a00-73b6-11eb-8b4e-a893f31151bc.png)

**Info:**
 - Suite version: web 21.3.0 (a0f694411d85fca4a35acedbdf3b07702517c120)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
