### ISSUE TITLE
Icon for Linux App Image

### ISSUE THREAD

**Issue by shipluhoque** [trezor/trezor-suite#3395]
Please can you add Icon for the Linux App Image,

On Linux Mint, I have an Invisible Icon on the taskbar when its open or in the background.

I have seen Ledger Live recently added Icon for their Linux App Image.

**Comment by prusnak** [comment]
Maybe this was the commit in question? https://github.com/LedgerHQ/ledger-live-desktop/pull/3427/commits/77fbd12cc0b1d06dc0ded5c9e863d1736bd42f5a

**Comment by bosomt** [comment]
Icon is present in appImage

![image](https://user-images.githubusercontent.com/31506317/112120853-ebbcd400-8bbe-11eb-8da5-8c7c7288b89a.png)

**Info:**
 - Suite version: desktop 21.3.2 (6dbeaf3dd28a11c5e4bc5867686f58d2920a14bd)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.3.2 Chrome/87.0.4280.141 Electron/11.2.1 Safari/537.36
 - OS: Linux x86_64 KUbuntu
 - Screen: 2560x1440
 - Device: model T 2.3.5 regular

**Comment by shipluhoque** [comment]
On Linux Mint, its not visible

**Comment by bosomt** [comment]
Suite 21.3.2 , public version and Mint Linux 20.1  works as expected

![image](https://user-images.githubusercontent.com/31506317/112811907-d2170300-907c-11eb-9743-908ffa80f677.png)

**Comment by shipluhoque** [comment]
I upgraded to linux mint 20.1 with cinnamon theme. still no icon

![Screenshot from 2021-03-29 11-08-32](https://user-images.githubusercontent.com/78937846/112822185-8580f700-907f-11eb-9362-8f292164c483.png)

**Comment by MarMun** [comment]
No icon in Ubuntu 20.04.2 LTS. I needed to add this manually

**Comment by shipluhoque** [comment]
Ledger Live had a similar or same issue and was later fixed.

**Comment by guiand888** [comment]
Under Manjaro Linux with KDE Plasma 5.21.5 the icon is also missing.
I ran `appimagelint` on the package and it seems to be a related to the resolution of the icon.

Surely, it shouldn't be too hard to fix?

```
-> % ./appimagelint-x86_64.AppImage Trezor-Suite-21.6.2-linux-x86_64.AppImage 
appimagelint.cli[14673] [INFO] Checking AppImage Trezor-Suite-21.6.2-linux-x86_64.AppImage
appimagelint.cli[14673] [INFO] Running check "GNU libc ABI check"
appimagelint.glibc_abi_check[14673] [INFO] detected required version for runtime: 2.3.3
appimagelint.glibc_abi_check[14673] [INFO] detected required version for payload: 2.16
appimagelint.cache[14673] [INFO] Fetching glibc version data for debian
appimagelint.setup[14673] [INFO] Fetching glibc package versions from Debian sources API
appimagelint.glibc_abi_check[14673] [INFO] [✔] AppImage can run on Debian oldstable (stretch)
appimagelint.glibc_abi_check[14673] [INFO] [✔] AppImage can run on Debian stable (buster)
appimagelint.glibc_abi_check[14673] [INFO] [✔] AppImage can run on Debian testing (bullseye)
appimagelint.glibc_abi_check[14673] [INFO] [✔] AppImage can run on Debian unstable (sid)
appimagelint.cache[14673] [INFO] Fetching glibc version data for ubuntu
appimagelint.setup[14673] [INFO] Fetching glibc package versions from Ubuntu FTP mirror
appimagelint.glibc_abi_check[14673] [INFO] [✔] AppImage can run on Ubuntu hirsute
appimagelint.glibc_abi_check[14673] [INFO] [✔] AppImage can run on Ubuntu groovy
appimagelint.glibc_abi_check[14673] [INFO] [✔] AppImage can run on Ubuntu focal
appimagelint.glibc_abi_check[14673] [INFO] [✔] AppImage can run on Ubuntu bionic
appimagelint.glibc_abi_check[14673] [INFO] [✔] AppImage can run on Ubuntu xenial
appimagelint.glibc_abi_check[14673] [INFO] [✔] AppImage can run on Ubuntu trusty
appimagelint.cli[14673] [INFO] Running check "GNU libstdc++ ABI check"
appimagelint.glibcxx_abi_check[14673] [INFO] detected required version for runtime: <none>
appimagelint.glibcxx_abi_check[14673] [WARNING] could not find any dependencies, skipping check
appimagelint.cli[14673] [INFO] Running check "Icons validity and location check"
appimagelint.icons_check[14673] [INFO] Extracting icon name from desktop file: /tmp/.mount_TrezorJfTYZG/trezor-suite.desktop
appimagelint.icons_check[14673] [INFO] Checking resolution of icon: /tmp/.mount_TrezorJfTYZG/trezor-suite.png
appimagelint.icons_check[14673] [INFO] [✔] Valid icon in AppDir root
appimagelint.icons_check[14673] [INFO] Checking resolution of icon: /tmp/.mount_TrezorJfTYZG/.DirIcon
appimagelint.icons_check[14673] [INFO] [✔] Valid icon file in .DirIcon
appimagelint.icons_check[14673] [INFO] Checking resolution of icon: /tmp/.mount_TrezorJfTYZG/usr/share/icons/hicolor/0x0/apps/trezor-suite.png
appimagelint.icons_check[14673] [ERROR] Icon resolution doesn't match resolution in path: (0, 0) (file resolution is (512, 512))
appimagelint.icons_check[14673] [WARNING] no other icons found
appimagelint.icons_check[14673] [INFO] [✖] Other integration icons valid
appimagelint.cli[14673] [INFO] Running check "Desktop files existence and validity"
appimagelint.desktop_files[14673] [INFO] Checking desktop files in root directory
appimagelint.desktop_files[14673] [INFO] [✔] Exactly one desktop file in AppDir root
appimagelint.desktop_files[14673] [INFO] Checking desktop file /tmp/.mount_Trezor2uyohz/trezor-suite.desktop with desktop-file-validate
appimagelint.desktop_files[14673] [INFO] [✔] All desktop files in AppDir are valid
```

**Comment by prusnak** [comment]
```
appimagelint.icons_check[14673] [INFO] Checking resolution of icon: /tmp/.mount_TrezorJfTYZG/usr/share/icons/hicolor/0x0/apps/trezor-suite.png
appimagelint.icons_check[14673] [ERROR] Icon resolution doesn't match resolution in path: (0, 0) (file resolution is (512, 512))
```

This is casued by an unresolved issue with electron-builder - broken icon size detection - see https://github.com/electron-userland/electron-builder/issues/5294

**Comment by STew790** [comment]
**QA OK**

We tried this on KUbuntu with KDE as well as on Mint Cinnamon and the Icon is correctly displayed on both.

**Info:**
 - Suite version: app 22.3.2 (563be1e28ad75ddd4e38c2002e6032b0743511d2)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular

**Comment by moderatedan** [comment]
When using Linux Mint: 

Right click the app image download. Go to permissions, which is found in properties, and allow executing file as program.

Cheers!

https://forum.trezor.io/t/how-do-i-access-suite-once-i-downloaded-it/3505/24?u=dan_brummitt
