### ISSUE TITLE
Giant illustrations

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3396]
**Info:**
 - Suite version: web 21.2.2 (7e8958e206885cd7946f431b63dad3bd446ef82e)
 - Browser: Chrome/88.0.4324.150 Safari/537.36
 - OS: MacIntel
 - Screen: 1792x1120
 - Device: model One 1.9.3 regular

<img width="1631" alt="Screen Shot 2021-02-12 at 12 39 42" src="https://user-images.githubusercontent.com/29627086/107763761-6298be80-6d2f-11eb-8399-6738afbb99c5.png">
<img width="655" alt="Screen Shot 2021-02-12 at 12 37 29" src="https://user-images.githubusercontent.com/29627086/107763702-54e33900-6d2f-11eb-8d6f-f8f6e4d03229.png">

**Comment by mroz22** [comment]
There was also quite a big difference in these images between chrome and firefox.

**Comment by slowbackspace** [comment]
@mroz22 Heeey, we need an extra pair of hands if you are up for it!

I remember that, firefox was handling flex: 1 on parent container of an image differently. I think this one is something new. I briefly check and it looks like nobody touched these images for ages. For now I am blaming Chrome for changing its behaviour 😁 (but it is totally legit that these images are so huge, looking at code I wouldn't expect anything else)

**Comment by slowbackspace** [comment]
kaay, I spent several hours on this, mostly trying to figure out how the hell it worked before and STILL WORKS in electron app. And most images even work (meaning they have correct size) even on the web. There are just few cases where an image expands to full container width. I wasn't able to pin point the exact problem that causing it.

Few things are weird tho:
1. electron app is okay (maybe it uses older chrome, but it also doesn't work correcly in ff)
2. even if there is specified width/height directly in svg it gets ignored

Ofc quick fix is to just specify width/height for each image (which I did), but I would really love to know what has caused this.
🤔

**Comment by sorooris** [comment]
**~~QA OK~~**

Couldn't replicate issue in app, however please note that current web version of the staging environment isn't accessible on testing devices (which have no VPN) so I couldn't verify there.

Suite version: app 21.3.1 3095751
OS: macOS Big Sur 11.2.2
Device: model T 2.3.5 public

**Comment by slowbackspace** [comment]
> **QA OK**
> 
> Couldn't replicate issue in app, however please note that current web version of the staging environment isn't accessible on testing devices (which have no VPN) so I couldn't verify there.
> 
> Suite version: app 21.3.1 [3095751](https://github.com/trezor/trezor-suite/commit/30957516994fb4b2d3ed463dcb553b21455d2f43)
> OS: macOS Big Sur 11.2.2
> Device: model T 2.3.5 public

oh for some reason it is web-only issue. it always worked fine in electron 🤷

**Comment by sorooris** [comment]
Well, let's keep it in the Needs QA column until it's testable :grin:

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.3.1 (1dbc5b720515c39a47f1dc58391dbebf1d766394)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Comment by bosomt** [comment]
**QA NOK**

I was able to reproduce issue in Firefox

![image](https://user-images.githubusercontent.com/31506317/110620473-56bae380-8199-11eb-8cdb-2b5cbe1361c2.png)

**Info:**
 - Suite version: web 21.3.1 (1dbc5b720515c39a47f1dc58391dbebf1d766394)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.4.0 (1da73bf5c45ed462662a4b3f12b10993625b9999)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
