### ISSUE TITLE
Litecoin - support for Bech32 address (native segwit)

### ISSUE THREAD

**Issue by jfriesse** [trezor/trezor-suite#3399]
**Is your feature request related to a problem? Please describe.**
Bech32 (native segwit) is supported for bitcoin in trezor-suite (thanks for this) but litecoin is sadly not yet supported, so it's not possible to use accounts starting with ltc prefix without using third party software.

**Describe the solution you'd like**
Support for Bech32 for litecoin in trezor-suite

**Describe alternatives you've considered**
Third party sw (electrum-ltc), but I really like trezor suite much more

**Comment by mcudev** [comment]
I'd like to see this support added to the GUI too.
I might work on this. I'd need to get familiar with this repo first, so don't let it stop anyone else.

If you weren't aware, you can already use the command line tools to generate BIP84 P2WPKH (aka native segwit bech32 encoded) addresses, like this:
`trezorctl btc get-address -c Litecoin -n 'm/84h/2h/0h/0/0' -t wpkh -d`
equivalent syntax without using the 'h' to stand for hardened derivation is (and careful with the quotes):
`trezorctl btc get-address -c Litecoin -n "m/84'/2'/0'/0/0" -t wpkh -d`

Use caution though, if the command line stuff doesn't make sense, then don't get in over your head.

The 2h in the commands above stands for the litecoin coin type in https://github.com/satoshilabs/slips/blob/master/slip-0044.md using hardened derivation.
Also for reference: https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki

**Comment by prusnak** [comment]
> I'd like to see this support added to the GUI too.

Are there any exchanges that support sending to Litecoin Bech32 addresses?

**Comment by mcudev** [comment]
Yes, Kraken lists support here https://support.kraken.com/hc/en-us/articles/360001474826-Supported-address-formats-for-cryptocurrency-withdrawal

I believe that Gemini does as well.

**Comment by mcudev** [comment]
It would be great to eventually make p2wpkh the default for Litecoin to get away from all that address conversion stuff, and to use the cheapest option (p2wpkh). For reference, 1 sat/vbyte transactions on LTC usually get into the next block.

**Comment by jfriesse** [comment]
> > I'd like to see this support added to the GUI too.
> 
> Are there any exchanges that support sending to Litecoin Bech32 addresses?

Simplecoin supports it flawlessly
