### ISSUE TITLE
"Previous account is empty" despite non zero balance

### ISSUE THREAD

**Issue by shimunn** [trezor/trezor-suite#3402]
**Describe the bug**
Suite won't discover additional accounts even though previous accounts are non empty and have transactions.

**Info:**
 - Suite Version: Desktop 21.2.2, [21.3.0](https://github.com/trezor/trezor-suite/tree/853dd4256ec7967501b97016d3fe46693ae374b5)
 - OS: NixOS unstable
 - Firmware Version: Model T, 2.3.4

**Steps to reproduce:**
1. Have ETH sitting in an account originating from a smart contract
2. Try to add additional accounts 

**Expected result:**
Addional accounts should be allowed to be added/discovered

**Actual result:**
Suite complains that previous accounts are empty

**Screenshots:**
![Trezor_previous_empty](https://user-images.githubusercontent.com/41011289/107856556-33667800-6e29-11eb-9eca-08340f051c40.png)

**Comment by slowbackspace** [comment]
Hello @shimunn, thanks for the report! Do you see some transactions on both first and second accounts? Or one of the accounts doesn't have any transactions even if you can clearly see non-zero balance?

**Comment by shimunn** [comment]
The first account doesn't show any transactions, the second one does as shown in the screenshot.

**Comment by slowbackspace** [comment]
> The first account doesn't show any transactions, the second one does as shown in the screenshot.

If you need quick workaround, I believe sending a transaction to the first account should unlock adding another account (regular transaction just to be safe, not a smart contract which, as you can see, we have hard time to properly detect). Before doing it please be aware that there is a chance I am wrong and it will not fix your issue and the fee you spent on the transaction is lost. 

Sorry for the trouble. Proper fix will follow soon.

**Comment by bitofit** [comment]
Related to #3057

**Comment by sorooris** [comment]
Confirmed with @tsusanka that it's out-of-scope for QA, moving to Approved column.
