### ISSUE TITLE
Advance Settings

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3405]
Advance options for both Device and General (Application) Settings.  

- [x] Safety Checks #2242 
- [x] Device autolock #1946 
- [x] Custom firmware #1871  
- [ ] Wipe code #822 

**Spec:** [Notion](https://www.notion.so/satoshilabs/Advance-settings-9dd9db4c8054430cbf37e5df496e753e) 
**Design:** [Zeplin](https://zpl.io/aXOmgR8)

**Comment by tsusanka** [comment]
> Design: Due end of this week

:eyes:

**Comment by andrewkozlik** [comment]
Additional settings to consider:

- Set passphrase source (TT only). When the passphrase is enabled allow the user to toggle the passphrase-always-on-device setting on/off. See https://wiki.trezor.io/Using_trezorctl_commands_with_Trezor#Set_passphrase_source.
- Set U2F counter. Either allow the user to specify a value like in the autolock UI or just have a "Reset U2F counter" button that will set the counter to the current UNIX timestamp, which is what most people need. See `trezorctl fido counter set {COUNTER}`.
- SD protect (TT only). Add a toggle for enabled/disabled same as with the PIN setting or the passphrase setting. When enabled also show a "Refresh" button. See https://wiki.trezor.io/SD_card_protection.

Related to https://github.com/trezor/trezor-suite/issues/3150.

**Comment by andrewkozlik** [comment]
@matejzak @tsusanka @goodhoko The safety checks setting will be available on the T1 soon. Please see https://github.com/trezor/trezor-firmware/issues/1627.

**Comment by tsusanka** [comment]
@goodhoko since [the code in Suite](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/views/settings/device/index.tsx#L345-L364) depends on device's Features, this could work out of the box for T1?

**Comment by andrewkozlik** [comment]
> @goodhoko since [the code in Suite](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/views/settings/device/index.tsx#L345-L364) depends on device's Features, this could work out of the box for T1?

Awesome! Works like a charm.

**Comment by w7xx** [comment]
& Tornado.cash to add support for non bitcoin chains ?
