### ISSUE TITLE
Copy overflow on Suite landing 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3411]
Chrome, MacOS 
Suite 21.2.2.

<img width="1305" alt="Screen Shot 2021-02-16 at 11 54 59" src="https://user-images.githubusercontent.com/29627086/108053560-dac3f480-704d-11eb-892e-b1794917f821.png">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.3.0 (a0f694411d85fca4a35acedbdf3b07702517c120)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
