### ISSUE TITLE
tx.amount inconsistency between bitcoin-like and ethereum

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3412]
`tx.amount` for sent bitcoin-like transactions includes a fee, but ethereum txs don't include fee in `tx.amount` field leading to various inconsistencies for example:

Screenshot of an ethereum account, sum of txs for 5th of february should be non-zero, but because of bitcoin-like txs when computing this sum we subtract `tx.fee` from `tx.amount` for all sent transactions, which leads in incorrect result.
![image](https://user-images.githubusercontent.com/6961901/108050804-650a5980-704a-11eb-92b8-8ed1c9ae15bb.png)

similar issues that are imo caused by the same problem
https://github.com/trezor/trezor-suite/issues/3366
https://github.com/trezor/trezor-suite/issues/3459

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.3.0 (b6c84eb9e23f9483d25ff4cb4a96a4c357596a24)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.3.0 Chrome/87.0.4280.141 Electron/11.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

![image](https://user-images.githubusercontent.com/31506317/109654105-15578200-7b62-11eb-9569-81b3ccecc571.png)
