### ISSUE TITLE
Display selected Fiat currency across the whole SendForm instead of global one

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3415]
**Describe the bug**
Fiat currency is inconsistent in the SendForm in Suite compared to Wallet.

**Info:**
 - Remembered Wallet: arbitrary (tested remembered hidden wallet)
 - Suite Version: any (tested 21.2.2 7e8958e2)
 - Browser: any (tested Chromium 88.0.4324.150)
 - OS: any (tested NixOS 20.09)
 - Bridge: any (tested 2.0.28)
 - Firmware Version: any (tested model T 2.3.6 b19cbf67c) 

**Steps to reproduce:**
1. Navigate to Accounts -> arbitrary account with balance -> Send form,
2. Fill out the address and FiatValue inputs arbitrarily and select a fiat currency different to the global one from settings (e.g. EUR when global is USD),
3. Observe the rest of the SendForm and the following ReviewTransaction modal.

**Expected result:**
Fiat currency is consistent to the selected one in FiatSelect.

**Actual result:**
Global currency is displayed everywhere else with the exception of FiatSelect.

**Screenshots:**
Suite - GBP is selected and USD is still displayed below
![image](https://user-images.githubusercontent.com/10185314/108084120-212c4a00-7074-11eb-8a4e-cab33dee35eb.png)
![image](https://user-images.githubusercontent.com/10185314/108085135-4b323c00-7075-11eb-9ab0-3dcb45823fa0.png)

compared to Wallet - EUR is selected and EUR is displayed consistently
![image](https://user-images.githubusercontent.com/10185314/108085018-29d15000-7075-11eb-83f6-d847f1dabc85.png)

**Comment by jerechinsky** [comment]
Let's make the currency consistent across SendForm and the ReviewTransaction modal according to what the user selected in the SendForm. @marekrjpolak  

I don't believe this feature request is urgent, so I'll remove the High priority label. Please correct me if I'm wrong @matejzak.

**Comment by marekrjpolak** [comment]
Technically it's doable, the question is what to do when there are multiple recipients and the user selects different fiat currency for each of them. It seems that the currency in this context is rather a helper how much crypto to send to the specific recipient, and all other amounts on the page are meant to be based on the global settings. @alex-jerechinsky 
![image](https://user-images.githubusercontent.com/26326960/134535538-e4da88da-53af-4c9d-bef9-ed47fc0e6473.png)

**Comment by jerechinsky** [comment]
Thank you, @marekrjpolak. I will leave this one up to the product team.
