### ISSUE TITLE
add https://etherscan.io/tx

### ISSUE THREAD

**Issue by europound** [trezor/trezor-suite#3420]
add https://etherscan.io/tx
https://eth1.trezor.io/tx is not good enough, not much info

**Comment by prusnak** [comment]
What information are you missing on eth1.trezor.io that can be found on etherscan.io ?

Please provide concrete examples of transactions and information missing. Thank you!

**Comment by europound** [comment]
take a look and you will see
miles away

**Comment by europound** [comment]
gas fees
eth variant
dynamic update
etc
just add extra button to etherscan io please

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
