### ISSUE TITLE
Ethereum SendMax Amount is not a number error when fee is too low

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3421]
**Describe the bug**
When there is not enough Ethereum to cover normal transaction fee and suite auto switch from normal to custom fee errors in console are triggered.
I was able to reproduce this error in `21.2.2` and `eth-erc20-gaslimit` branch

**Info:**
 - Remembered Wallet: no
 - Suite version: web 21.3.0 (67cfe9730c8c3daaee58f2760695f2b82183c462)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Nixos
 - Bridge: build version Version: 2.0.28
 - Firmware Version: 2.3.5 + 2.3.6 model T, public

**Steps to reproduce:**
1. load ethereum accounts with low amounts in account
2. press send max when trying to send transaction
3. when suite auto switch from normal to custom fee error in console is triggered

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/108134351-5bb6d680-70b6-11eb-8b3d-21df1d208571.png)

![image](https://user-images.githubusercontent.com/31506317/108135155-e4824200-70b7-11eb-8a1b-896a02823920.png)

![image](https://user-images.githubusercontent.com/31506317/108134884-4e4e1c00-70b7-11eb-8e8b-301fa232317a.png)

![image](https://user-images.githubusercontent.com/31506317/108135658-c2d58a80-70b8-11eb-9207-3bf550f6f406.png)

**Comment by sorooris** [comment]
**QA OK**

No errors in console displayed; correct notification (_Sign transaction error: insufficient funds for gas * price + value_) displayed.

Suite: 21.3.1 1dbc5b720515c39a47f1dc58391dbebf1d766394
Browser: Chromium 88.0.4324.150, Firefox 85.0.2
OS: NixOS 20.09
Device: 2.3.5 public
