### ISSUE TITLE
gpg shows as bad signature when verifying trezor suite on linux

### ISSUE THREAD

**Issue by gked** [trezor/trezor-suite#3422]
Hello, I downloaded Trezor Suite from https://suite.trezor.io/ and also got the signature and a signing key from the same location.

However, when i run verify it returns bad signature. Is this known? Or perhaps I am made a mistake somewhere.

**Info:**
 - Suite Version: Trezor-Suite-21.2.2
 - Browser: , TOR and Firefox
 - OS: Linux - Pop!_OS(Debian)
 - Bridge: build version
 - Firmware Version: model , revision 

**Steps to reproduce:**
1. Navigate to https://suite.trezor.io/
2. download Trezor-Suite-21.2.2-linux-x86_64.AppImage, Trezor-Suite-21.2.2-linux-x86_64.AppImage.asc and satoshilabs-2021-signing-key.asc
3. Import satoshilabs-2021-signing-key.asc in gpg
4. run gpg --verify Trezor-Suite-21.2.2-linux-x86_64.AppImage.asc

Should get a "Good Signature" messsage

**Actual result:**
got BAD signature from "SatoshiLabs 2021 Signing Key"

**Screenshots:**
![image](https://user-images.githubusercontent.com/12704474/108157697-35823e00-7098-11eb-90b5-a12b17c2902e.png)

**Note(s):**
The public key shown in the terminal is EB483B26B078A4AA1B6F425EE21B6950A2ECB65C.

**Comment by prusnak** [comment]
Works here.

Try removing the files and downloading them again.
