### ISSUE TITLE
CI cuts out some output?

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3424]
This [job](https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/1035753865) on CI fails and on the command `docker-compose run test-run` it prints about ~30 rows.

I have replicated this error on my computer and I got significantly more out, see the details below. It is quite difficult to debug issues then if the output is not complete.

How to reproduce:
- Mess up trezor-user-env (for example do some Python error etc.)
- Build it.
- Retry some Suite job.

<details>
$ docker-compose run test-run
WARNING: The CYPRESS_SNAPSHOT variable is not set. Defaulting to a blank string.
WARNING: The CYPRESS_updateSnapshots variable is not set. Defaulting to a blank string.
WARNING: The LOCAL_USER_ID variable is not set. Defaulting to a blank string.
WARNING: The TEST_GROUP variable is not set. Defaulting to a blank string.
WARNING: The TRACK_SUITE_URL variable is not set. Defaulting to a blank string.
WARNING: The ALLOW_RETRY variable is not set. Defaulting to a blank string.
WARNING: The CI_JOB_URL variable is not set. Defaulting to a blank string.
WARNING: The CI_COMMIT_BRANCH variable is not set. Defaulting to a blank string.
WARNING: The CI_COMMIT_MESSAGE variable is not set. Defaulting to a blank string.
WARNING: The CI_COMMIT_SHA variable is not set. Defaulting to a blank string.
WARNING: The CI_RUNNER_DESCRIPTION variable is not set. Defaulting to a blank string.
WARNING: Found orphan containers (test-runner, suite-dev) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting docker_trezor-user-env-unix_1 ... done
/root/.cache/Cypress/6.4.0/Cypress/Cypress
[run_tests.js] TRACK_SUITE_URL env not specified or CYPRESS_updateSnapshots is set. No logs will be uploaded
[run_tests.js] test files after all filters: [
  './packages/integration-tests/projects/suite-web/tests/backup/t2-fail.test.ts',
  './packages/integration-tests/projects/suite-web/tests/backup/t2-misc.test.ts',
  './packages/integration-tests/projects/suite-web/tests/backup/t2-success.test.ts',
  './packages/integration-tests/projects/suite-web/tests/browser/edge.test.ts',
  './packages/integration-tests/projects/suite-web/tests/browser/iphone-chrome.test.ts',
  './packages/integration-tests/projects/suite-web/tests/browser/outdated-chrome.test.ts',
  './packages/integration-tests/projects/suite-web/tests/browser/outdated-firefox.test.ts',
  './packages/integration-tests/projects/suite-web/tests/dashboard/dashboard.test.ts',
  './packages/integration-tests/projects/suite-web/tests/firmware/firmware.test.ts',
  './packages/integration-tests/projects/suite-web/tests/metadata/account-metadata.test.ts',
  './packages/integration-tests/projects/suite-web/tests/metadata/address-metadata.test.ts',
  './packages/integration-tests/projects/suite-web/tests/metadata/dropbox-api-errors.test.ts',
  './packages/integration-tests/projects/suite-web/tests/metadata/google-api-errors.test.ts',
  './packages/integration-tests/projects/suite-web/tests/metadata/interval-fetching.test.ts',
  './packages/integration-tests/projects/suite-web/tests/metadata/output-labeling.test.ts',
  './packages/integration-tests/projects/suite-web/tests/metadata/remembered-device.test.ts',
  './packages/integration-tests/projects/suite-web/tests/metadata/switching-providers.test.ts',
  './packages/integration-tests/projects/suite-web/tests/metadata/wallet-metadata.test.ts',
  './packages/integration-tests/projects/suite-web/tests/onboarding/firmware-update.test.ts',
  './packages/integration-tests/projects/suite-web/tests/onboarding/hologram.test.ts',
  './packages/integration-tests/projects/suite-web/tests/onboarding/steps-order.test.ts',
  './packages/integration-tests/projects/suite-web/tests/onboarding/t1-create-wallet.test.ts',
  './packages/integration-tests/projects/suite-web/tests/onboarding/t1-recovery-advanced.test.ts',
  './packages/integration-tests/projects/suite-web/tests/onboarding/t1-recovery-basic.test.ts',
  './packages/integration-tests/projects/suite-web/tests/onboarding/t2-create-wallet.test.ts',
  './packages/integration-tests/projects/suite-web/tests/onboarding/t2-recovery-fail.test.ts',
  './packages/integration-tests/projects/suite-web/tests/onboarding/t2-recovery-persistence.test.ts',
  './packages/integration-tests/projects/suite-web/tests/onboarding/t2-recovery-success.test.ts',
  './packages/integration-tests/projects/suite-web/tests/onboarding/transport.test.ts',
  './packages/integration-tests/projects/suite-web/tests/onboarding/unexpected-states.test.ts',
  './packages/integration-tests/projects/suite-web/tests/recovery/t1-dry-run.test.ts',
  './packages/integration-tests/projects/suite-web/tests/recovery/t2-dry-run-persistence.test.ts',
  './packages/integration-tests/projects/suite-web/tests/settings/general.test.ts',
  './packages/integration-tests/projects/suite-web/tests/settings/log.test.ts',
  './packages/integration-tests/projects/suite-web/tests/settings/t1-device-settings.test.ts',
  './packages/integration-tests/projects/suite-web/tests/settings/t2-device-settings.test.ts',
  './packages/integration-tests/projects/suite-web/tests/suite/analytics.test.ts',
  './packages/integration-tests/projects/suite-web/tests/suite/button-requests.test.ts',
  './packages/integration-tests/projects/suite-web/tests/suite/connecting-devices.test.ts',
  './packages/integration-tests/projects/suite-web/tests/suite/initial-run.test.ts',
  './packages/integration-tests/projects/suite-web/tests/suite/passhprase-duplicate.test.ts',
  './packages/integration-tests/projects/suite-web/tests/suite/passhprase-numbering.test.ts',
  './packages/integration-tests/projects/suite-web/tests/suite/passphrase-disabled.test.ts',
  './packages/integration-tests/projects/suite-web/tests/suite/passphrase.test.ts',
  './packages/integration-tests/projects/suite-web/tests/suite/remembering-devices.test.ts',
  './packages/integration-tests/projects/suite-web/tests/suite/static-pages.test.ts',
  './packages/integration-tests/projects/suite-web/tests/wallet/discovery.test.ts'
]

[run_tests.js] testing next file ./packages/integration-tests/projects/suite-web/tests/backup/t2-fail.test.ts
[run_tests.js] allowed to run 1 times
[mockGoogleDrive]: reset

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    6.4.0                                                                              │
  │ Browser:    Chrome 87                                                                          │
  │ Specs:      1 found (backup/t2-fail.test.ts)                                                   │
  │ Searched:   packages/integration-tests/projects/suite-web/tests/backup/t2-fail.test.ts         │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  backup/t2-fail.test.ts                                                          (1 of 1)

  Backup
Error: connect ECONNREFUSED 127.0.0.1:9001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9001
}
    1) "before each" hook for "Backup failed - device disconnected during action"

  0 passing (248ms)
  1 failing

  1) Backup
       "before each" hook for "Backup failed - device disconnected during action":
     CypressError: `cy.task('stopBridge')` failed with the following error:

> websocket_runtime_error: 

Because this error occurred during a `before each` hook we are skipping all of the remaining tests.
      at https://suite.corp.sldev.cz/__cypress/runner/cypress_runner.js:160102:19
      at tryCatcher (https://suite.corp.sldev.cz/__cypress/runner/cypress_runner.js:10609:23)
      at Promise._settlePromiseFromHandler (https://suite.corp.sldev.cz/__cypress/runner/cypress_runner.js:8544:31)
      at Promise._settlePromise (https://suite.corp.sldev.cz/__cypress/runner/cypress_runner.js:8601:18)
      at Promise._settlePromise0 (https://suite.corp.sldev.cz/__cypress/runner/cypress_runner.js:8646:10)
      at Promise._settlePromises (https://suite.corp.sldev.cz/__cypress/runner/cypress_runner.js:8722:18)
      at _drainQueueStep (https://suite.corp.sldev.cz/__cypress/runner/cypress_runner.js:5316:12)
      at _drainQueue (https://suite.corp.sldev.cz/__cypress/runner/cypress_runner.js:5309:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://suite.corp.sldev.cz/__cypress/runner/cypress_runner.js:5325:5)
      at Async.drainQueues (https://suite.corp.sldev.cz/__cypress/runner/cypress_runner.js:5195:14)
  From Your Spec Code:
      at Context.eval (https://suite.corp.sldev.cz/__cypress/tests?p=packages/integration-tests/projects/suite-web/support/index.ts:15400:6)
  
  From Node.js Internals:
    Error: websocket_runtime_error: 
        at WebSocket.<anonymous> (/trezor-suite/packages/integration-tests/projects/suite-web/plugins/websocket-client.js:169:24)
        at Object.onceWrapper (events.js:422:26)
        at WebSocket.emit (events.js:315:20)
        at ClientRequest.<anonymous> (/trezor-suite/node_modules/ws/lib/websocket.js:579:15)
        at ClientRequest.emit (events.js:315:20)
        at Socket.socketErrorListener (_http_client.js:426:9)
        at Socket.emit (events.js:315:20)
        at emitErrorNT (internal/streams/destroy.js:92:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
        at processTicksAndRejections (internal/process/task_queues.js:84:21)

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     backup/t2-fail.test.ts                                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

  (Screenshots)

  -  /trezor-suite/packages/integration-tests/projects/suite-web/screenshots/backup/t     (1050x838)
     2-fail.test.ts/Backup failed - device disconnected during action -- before each                
     hook (failed) (6).png                                                                          

  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /trezor-suite/packages/integration-tests/projects/suite-web    (0 seconds)
                          /videos/backup/t2-fail.test.ts.mp4                                        

====================================================================================================

  (Run Finished)

       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  backup/t2-fail.test.ts                   243ms        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     243ms        1        -        1        -        -  

[run_tests.js] backup/t2-fail duration: 243
[run_tests.js] test backup/t2-fail finished failing after 1 run(s)

[run_tests.js] testing next file ./packages/integration-tests/projects/suite-web/tests/backup/t2-misc.test.ts
[run_tests.js] allowed to run 1 times
[mockGoogleDrive]: reset
Cypress could not verify that this server is running:

  > https://suite.corp.sldev.cz/suite-web/develop/

We are verifying this server because it has been configured as your `baseUrl`.

Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

Cypress failed to verify that your server is running.

Please start this server and then run Cypress again.
[run_tests.js] error
TypeError: Cannot read property '0' of undefined
</details>

**Comment by tsusanka** [comment]
I have checked out the "raw" output (as recommended by @mmilata) but it does not contain ECONNREFUSED either (which I had on my local machine, see details).

**Comment by vdovhanych** [comment]
The only other option then is to enable debug login as described [here](https://docs.gitlab.com/ee/ci/variables/#enable-debug-logging). This should show everything that is shown on the runner.

**Comment by vdovhanych** [comment]
Maybe this could be closed as the debug option didn't do what we wanted and we will be getting the logs from runners?

**Comment by tsusanka** [comment]
Yes I agree. And you documented it nicely on [Notion](https://www.notion.so/satoshilabs/Accessing-detailed-logs-from-CI-4027d4482e9a499f9d31922a5617e88f) so it's a solve!
