### ISSUE TITLE
Search in Ethereum transaction history error:  Cannot read property 'amount' of undefined

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3440]
**Describe the bug**
I see `Uncaught TypeError: Cannot read property 'amount' of undefined` error when i try to seach in Ethereum transactions.
Other coins are OK. Please see video and screenshots.
Same results in development master 21.3.0 2d0d60b3e27062c63812a720d365b15e109f5d33 in Firefox

**Steps to reproduce:**
1. load Ethereum wallet with transaction history
2. search in transaction hsitory
3. observe Chrome or Firefox console

**Info:**
 - Suite version: web 21.2.3 (9cf47b5b526bbb5cda585e717fbbf0f5b93b8cc0)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Screenshots:**

https://www.youtube.com/watch?v=JzWYflQ5vjU&amp%3Bfeature=youtu.be

![image](https://user-images.githubusercontent.com/31506317/108274440-32a94b00-7175-11eb-8ac3-b9256723ee37.png)

![image](https://user-images.githubusercontent.com/31506317/108275391-9122f900-7176-11eb-933d-6b97ce953836.png)

**Comment by bosomt** [comment]
@slowbackspace I'm able to reproduce issue ONLY when there are ERC20 tokens in transactions history

**Comment by bosomt** [comment]
Search in ETH tx history is not working completely 

**Info:**
 - Suite version: desktop 21.3.0 (b6c84eb9e23f9483d25ff4cb4a96a4c357596a24)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.3.0 Chrome/87.0.4280.141 Electron/11.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

![image](https://user-images.githubusercontent.com/31506317/109653444-54d19e80-7b61-11eb-947c-8cec8ca47825.png)

**Comment by sorooris** [comment]
**QA OK**

No errors in console displayed; correct notification (_Sign transaction error: insufficient funds for gas * price + value_) displayed.

Suite: 21.3.1 1dbc5b720515c39a47f1dc58391dbebf1d766394
Browser: Chromium 88.0.4324.150
OS: NixOS 20.09
Device: 2.3.5 public

**Comment by sorooris** [comment]
**QA OK**

No errors in console displayed; relevant search results displayed.

Suite: 21.3.1 1dbc5b720515c39a47f1dc58391dbebf1d766394
Browser: Chromium 88.0.4324.150, Firefox 85.0.2
OS: NixOS 20.09
Device: 2.3.5 public
