### ISSUE TITLE
Show XPUB when not connected to the internet

### ISSUE THREAD

**Issue by haarts** [trezor/trezor-suite#3441]
**Is your feature request related to a problem? Please describe.**
I was trying to setup a Trezor on an airgapped computer. Trezor Suite seemed ideally suited for this. However when pulling in the Trezor I was greeted with an 'Account discovery error'. At some level I think I understand. The Trezor cannot know the UTXO when not connected to an up to date full node (is this how it work?). But it could still display the XPUB (I think). For that only access to the private key(s) would be required.

**Describe the solution you'd like**
Instead of stone walling the user with an 'account discovery error' give the option to at least display the XPUB.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
