### ISSUE TITLE
RBF error message when whole balance is spent - copy change proposal

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-suite#3442]
**Current Situation:**

- When the user spends the whole balance and then wants to bump the transaction by using RBF (can't be done because there is no balance from which the extra fee could be deducted) error message:**"can't bump the fee on a transaction with no change outputs"**

**Describe the solution you'd like**

- the error message could say "there are not enough funds to pay the extra fee from/your balance is 0 and so you cannot pay the extra fee, deposit funds to do so" or similar instead of the output error message that does not make sense to average user

**Comment by jerechinsky** [comment]
further discussion in slack [thread](https://satoshilabs.slack.com/archives/CKN5C51CJ/p1613642960074500)
