### ISSUE TITLE
Upload source maps to Sentry during release process

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3445]
My original idea was that if source maps are publicly accessible to download (bundled alongside the code), then sentry will fetch them and use them. That might work (and it did in the past), but when there is a new release, source maps for older versions of suite are no longer accessible on suite.trezor.io (since they are replaced by new build, thus new source maps) and I am not sure if sentry is storing old source maps (hopefully it does). Another possible problem is that this approach won't work for electron app, since sentry can't really fetch source maps from your computer :)

Better and recommended approach is to upload source maps to sentry as a part of release process
`sentry-cli` has ability to upload a source maps, all you have to do is run:
`sentry-cli releases -o satoshilabs -p trezor-suite files <commit> upload-sourcemaps <path_to_source_maps>`

By default source map files are right next to the transpilled source files, so `path_to_source_maps` should lead to build folder.
We could run this as a part of deploy-to-staging job if we still do that, if not then as a part of deploy-to-production script.

For now I manually uploaded source maps from our electron builds (I unpacked app.asar from macos app), it seems to be working!

**Comment by tsusanka** [comment]
@vdovhanych I am assigning you since this a DevOps issue but there are other more important issues, let's do those first.

**Comment by keraf** [comment]
Tagging #3446 as there will be some changes required if it gets implemented before the new pipeline is merged.

**Comment by vdovhanych** [comment]
Closing the issue as this was done by @tomasklim in #4064
