### ISSUE TITLE
Hide graph view in dashboard

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3448]

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.3.0 (a5de8753d2e8a16b1217edb644c7414d176948cc)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Comment by sorooris** [comment]
Although functionally correct, let's please reconsider cc @matejzak 

1) an **accordion** vs the current solution by hiding the _hide graph button_ under the meatball menu 
     - possibility of making **Assets** also collapsible via an accordion
     - consistent with how account types can be collapsed
2) inconsistency with the graphs in each account in the Accounts section which **can't be hidden right now**

Suite: web 21.3.0 a5de875
Browser: Chromium 88.0.4324.150
OS: NixOS 20.09
Device: 2.3.5 public

**Comment by slowbackspace** [comment]
> Although functionally correct, let's please reconsider cc @matejzak
> 
> 1. an **accordion** vs the current solution by hiding the _hide graph button_ under the meatball menu
>    
>    * possibility of making **Assets** also collapsible via an accordion
>    * consistent with how account types can be collapsed
> 2. inconsistency with the graphs in each account in the Accounts section which **can't be hidden right now**
> 
> Suite: web 21.3.0 [a5de875](https://github.com/trezor/trezor-suite/commit/a5de8753d2e8a16b1217edb644c7414d176948cc)
> Browser: Chromium 88.0.4324.150
> OS: NixOS 20.09
> Device: 2.3.5 public

give them a finger and they'll take an arm!

(but yes, good point that design should be consistent)

**Comment by glacierbits** [comment]
Dashboard will get bigger redesign 2 sprints from now (design in progress). I suggest we don't worry about this now. That being said, I applaud @sorooris for thinking of our consistency. <3

**Comment by sorooris** [comment]
@matejzak ack, approving.
