### ISSUE TITLE
Confusing UI for Account XPUB

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#3454]
When the device is unplugged, the `Show public key` button looks like this:

<img src="https://user-images.githubusercontent.com/42201/108627329-4bf01700-7455-11eb-99cf-28ed39dee688.png">

This is very confusing UI not following the least surprise principle.

Reasons:

* when the device is unplugged the button shows the spinner - this makes me think I have to wait, not to plug in the device
* when the device is plugged in - the XPUB is shown without the confirmation on the device

I think this workflow should follow the Show Address UI:
* allow showing the XPUB without the device connected, but with the warning
* when the device is connected, show the XPUB, but also show it on the device to confirm it

**Comment by bosomt** [comment]
**QA NOK**
Still same behavior.

**Info:**
 - Suite version: web 21.7.1 (24cc565a3badd85ab48b30348022471dfd85f90e)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.2 regular

**Comment by bosomt** [comment]
this "forever loading" also happens when you disable all coins on disconnected device, see start of video.

https://youtu.be/rXOdAqRVPws

![image](https://user-images.githubusercontent.com/31506317/126600405-18b8ac7a-9ce5-4c17-abb8-ce372b20f1ec.png)


**Info:**
 - Suite version: web 21.7.1 (24cc565a3badd85ab48b30348022471dfd85f90e)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.2 regular

**Comment by Hannsek** [comment]
**improvement proposal**

- showing public key should follow the same behaviour as showing address

Proposed design of showing xpub tabs is in the pictures below:


<img width="469" alt="4" src="https://user-images.githubusercontent.com/57008159/184122308-0add14f2-1b0d-4ccb-b400-39d01a1ce89b.png">
<img width="480" alt="3" src="https://user-images.githubusercontent.com/57008159/184122313-0697205d-540c-4ce6-9047-92994ce50278.png">
<img width="475" alt="5" src="https://user-images.githubusercontent.com/57008159/184122317-4059bfd2-66ea-462e-8c9e-d4632d5a79d7.png">
<img width="1139" alt="1" src="https://user-images.githubusercontent.com/57008159/184122318-e39eaab0-84f4-4c64-a436-2775b2401cce.png">
<img width="862" alt="2" src="https://user-images.githubusercontent.com/57008159/184122320-86175b30-f285-4edf-a7f3-a8a08d584b5e.png">

**Comment by prusnak** [comment]
We should boost priority of this issue with the upcoming mobile app. 

I cannot scan XPUB without Trezor connected and that's not really cool.

**Comment by komret** [comment]
I made the changes as proposed by @Hannsek, but there are still some differences from the _receive_ flow due to implementations in connect and firmware:
- no warning before displaying it if the wallet is not backed up
- no way to display the QR code on device
- no "address mismatch - contact support" screen on TT

Are we OK with that?

**Comment by prusnak** [comment]
> * no way to display the QR code on device

I can live with that, but QR code should work the same way it does for addresses.

If this is a limitation of Connect, I propose we can fix that later in another PR.

**Comment by Hannsek** [comment]
> no way to display the QR code on device
> no "address mismatch - contact support" screen on TT

I believe we should address these "issues" in FW to behave as with the address. Will do an issue.

> no warning before displaying it if the wallet is not backed up

It is a corner case but we should probably handle it as well.

**Comment by komret** [comment]
Ok, I'll see what I can do about the backup warning. The other issues must be handled by firmware.

**Comment by prusnak** [comment]
> Ok, I'll see what I can do about the backup warning. The other issues must be handled by firmware.

We can display xpub qr code in the firmware. Not sure what is the issue. Can you describe in more in detail?

**Comment by komret** [comment]
> We can display xpub qr code in the firmware. Not sure what is the issue. Can you describe in more in detail?

I can't see it on Trezor screen:

![Screenshot 2023-05-31 at 15 59 40](https://github.com/trezor/trezor-suite/assets/42465546/2b3c6fc0-99f5-437e-8e0c-bcd8ff68e10a)

Nor do I see any option to display it in [getPublicKey](https://docs.trezor.io/trezor-suite/packages/connect/methods/getPublicKey.html) method.

What am I missing?

**Comment by prusnak** [comment]
> I can't see it on Trezor screen:

I guess it was dropped from the UI when it was redesigned. It used to be there.

**Comment by komret** [comment]
**QA:** Please test with multiple accounts, devices, coins. Also remembered wallets. It should work for both bitcoin-like and Cardano. See PR for details.

**Comment by komret** [comment]
We added some UX improvements:

- no-backup modal is cancelable (and appears for XPUB, too)
![Screenshot 2023-05-31 at 13 22 22](https://github.com/trezor/trezor-suite/assets/42465546/33929f9d-53b1-449a-ab9b-cb619f736ee5)
- copy button also appears when device is not connected (warning moved to the top):
![Screenshot 2023-06-05 at 19 17 48](https://github.com/trezor/trezor-suite/assets/42465546/57f569dd-2e90-4851-a231-bff7a6f0feaa)
- modal is always cancelable, even before the value is confirmed on Trezor:
![Screenshot 2023-06-06 at 14 16 50](https://github.com/trezor/trezor-suite/assets/42465546/172da9b5-c890-4cc7-9e61-9780ba8e7185)

The latter two make it somewhat easier to skip the check on device, not that I want to encourage that, but it feels much more user-friendly. Are you ok with that @prusnak @Hannsek?

**Comment by Hannsek** [comment]
I don’t want to block this pr. (It is already merged, so I cannot 😄) But I would make it more “difficult” for user to copy/scan the xpub/address when the device is connected. We can do it in similar way as it is done in mobile app. E.g. blurr the qr.
We can figure it out with new pr. 
 Cc @Hermez-cz

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.6.1 (bf8716e07436e942dd86517475e44ba5e6f4b10c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.6.1 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
