### ISSUE TITLE
Add/remove custom backend misbehaving

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3457]
**Describe the bug**
Please see video, I was able to reproduce it in Firefox and Chromium browser.
- add custom backend allows you to add same backend URL
- second backend is added with stripped number
- when you try to remove second backend actually third URL is removed

**Steps to reproduce:**
1. add custom backend with same URL as used
2. add custom backend with different url 
3. add custom backend with different url one ore time
4. observe behavior

**Info:**
 - Suite version: web 21.3.0 (a0f694411d85fca4a35acedbdf3b07702517c120)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Screenshots:**

https://www.youtube.com/watch?v=meZ-d_xmKJk&feature=youtu.be

![image](https://user-images.githubusercontent.com/31506317/108639662-056edc80-7496-11eb-9629-328f8afbfe87.png)

![image](https://user-images.githubusercontent.com/31506317/108639674-128bcb80-7496-11eb-8504-d395757d8f80.png)

**Comment by tomexx** [comment]
I came across this while working on the new Onboarding so I'd fix that for both Settings and Onboarding

**Comment by bosomt** [comment]
**QA OK**
edit **QA OK** in neu onboarding 

**Info:**
 - Suite version: web 21.5.1 (974429bab27c43502251b646a485d792a4ab4180)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1584x990
 - Device: model T 2.3.6 regular

**Comment by STew790** [comment]
QA OK

Info:
 - Suite version: web 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: NixOS
 - Device: model T 2.3.5 regular

**Comment by sorooris** [comment]
**QA OK**

Suite: app 21.5.1 4d09d884
OS: macoS Big Sur 11.3.1
Device: T1 1.9.4 public
