### ISSUE TITLE
Send form - custom fee displayed in other fee levels

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3458]
From our feedback:

> When in the "Send" tab for a crypto account, if you set a custom fee it show that custom fee in the "Fee rate" field when you select Low/Economy/Normal/High.  If you set the custom fee to 0, the "Fee rate" field behaves normally when selecting Low/Economy/Normal/High.  Thanks!

It's a bit confusing but could @trezor/qa please retest?

**Comment by bosomt** [comment]
Im not sure but I think i was able to reproduce it ;) 
@tsusanka please see gif, when i set 0 custom fee and switch to normal or economic fee it auto switch to custom fee.

**Info:**
 - Suite version: desktop 21.2.2 (7e8958e206885cd7946f431b63dad3bd446ef82e)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.2.2 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

![0fee](https://user-images.githubusercontent.com/31506317/108797650-f79b8300-758b-11eb-96f3-c4fd10a54ef3.gif)

**Comment by tsusanka** [comment]
Bug it is then!

**Comment by jerechinsky** [comment]
The bug that bosomt found seems to be unrelated to the one tsusanka reported. The original bug report said that the custom fee selected by a user is then displayed upon selecting any of the fee levels with the exception of custom fee being set to 0. In that case (when custom fee is set to 0) the predetermined custom fees behave normally. I was able to reproduce this bug. 

![gif](https://user-images.githubusercontent.com/75733878/108865210-46303800-75f3-11eb-9713-cab2bbc508ac.gif)

**Info:**
 - Suite version: desktop 21.2.2 (7e8958e206885cd7946f431b63dad3bd446ef82e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.2.2 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1080
 - Device: model T 2.3.5 regular

---

The bug that bosomt found is such that when setting custom fee to 0 and then choosing any of the other fee levels, the selected fee level switches back to _Custom_ by itself. I will create a new issue for the bug that bosomt found and let's use this issue for the original bug.

**Comment by jerechinsky** [comment]
@szymonlesisz could you please advise whether this is a frontend issue or something more convoluted?

**Comment by sorooris** [comment]
**QA OK**

Couldn't replicate the issue.

Suite: 21.3.1 30957516
OS: macOS Big Sur 11.2.2
Device: model T 2.3.5 public
