### ISSUE TITLE
Incorrect incoming fiat value

### ISSUE THREAD

**Issue by soucek87** [trezor/trezor-suite#3459]
**Describe the bug**
Incorrect incoming fiat value (+$0.00) is displayed in transaction history. 

**Info:**
 - Suite Version: 21.2.1 (21.2.1.10324)

 - OS: OS X 10.15.6

**Expected result:**
Adequate incoming fiat value should be displayed. 

**Screenshots:**
<img width="640" alt="SuiteBugBalance" src="https://user-images.githubusercontent.com/68375745/108698751-c166f080-7504-11eb-8180-26ede806cc2d.png">

**Comment by bosomt** [comment]
i was able to reproduce issue in dev master

**Info:**
 - Suite version: web 21.3.0 (42848e334da62a5c21d25f257d839a9cf81ce2b5)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.3.0 (10db684bbd2494056eca770e69e11aac0b4e465b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Comment by slowbackspace** [comment]
note to self: probably fails right after sending/receiving new tx, check if we fetch fiat rates in this case. should be ok on refresh (if wallet is not remembered, otherwise clear storage) 

related (probably the same) issue https://github.com/trezor/trezor-suite/issues/3365

**Comment by bosomt** [comment]
**QA OK**

Info:

    Suite version: web 21.6.0 (b65e292)
    Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
    OS: MacIntel
    Screen: 1440x900
    Device: model T 2.4.0 regular

**Comment by wendys-cats** [comment]
**QA OK**

Info:

Suite version: web 21.6.1 4f358fd151fc1962f30f84a855b82213d958aae7
Browser: Version 88.0.4324.182 (Official Build) (64-bit)
OS: NixOS 21.03
Device: model T 2.4.0 071c6c0
