### ISSUE TITLE
Allow decreasing the output value in RBF transactions

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3460]
After https://github.com/trezor/trezor-firmware/issues/1491 is done it will be possible to decrease ouput value during the RBF process which is very useful for sweeping accounts (sending maximum from your account).

Multiple outputs TX scenario, where user is asked to select the particular output to be decreased: [**Design**](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/600aaace68c9370c4cc52175) _(4th screen)_

**Comment by glacierbits** [comment]
Just discussed with @szymonlesisz: 

- Let's use already existing context warning message saying the amount has been decreased + the new amount. 

_(Example)_
<img width="736" alt="Screen Shot 2021-05-11 at 13 39 40" src="https://user-images.githubusercontent.com/29627086/117809327-581e9000-b25e-11eb-87b0-9d663a7a34f7.png"> 

- Let's add the confirmation items (as per FW request) to the transaction confirmation modal.

**Comment by szymonlesisz** [comment]
this is already merged by https://github.com/trezor/trezor-suite/pull/3827

**Comment by bosomt** [comment]
**QA OK**

https://github.com/trezor/trezor-suite/pull/3827#issuecomment-863163586

**Comment by STew790** [comment]
**QA OK**

Info:
 - Suite version: desktop 21.7.0 (550942dcbdb7b2ffc17519f8307a47f2d8d060f1)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.0 regular
