### ISSUE TITLE
Unable to open the classic wallet on website because only hidden wallet is available

### ISSUE THREAD

**Issue by eromartin** [trezor/trezor-suite#3464]
**Describe the bug**
I made hidden wallet in desktop app and then when i open the web wallet i cant see any other balances other than the hidden wallet wich  is empty i have my coins on regular wallet which i can only open through desktop app. Is this intended or is it bug?

**Info:**
 - Remembered Wallet: yes
 - Suite Version: both
 - Browser: , version
 - OS: system, Windows 10
 - Bridge: build version
 - Firmware Version: model , revision 

**Steps to reproduce:**
1. Make hidden wallet
2. Open web wallet
3. No acces to your normal wallet only to hidden walet

**Expected result:**
Unable to open normal wallet due to only being limited to hidden wallet in browser

**Actual result:**
I had to use desktop client do do anything

**Screenshots:**
insert here

**Note(s):**

**Comment by slowbackspace** [comment]
Hi @eromartin, every wallet you use should be available in both the web and desktop app. However, remembered wallets are not shared between these platforms. If you remembered a wallet on the desktop app it won't show up in the web app til you add it. 

If you have added only hidden wallet, then there is a button "add wallet" that will allow you to add a standard wallet.
<img width="823" alt="Screenshot 2021-02-23 at 11 55 09" src="https://user-images.githubusercontent.com/6961901/108834772-de67f600-75ce-11eb-9814-f7bb270f2330.png">

If you are not seeing this option, please send a screenshot.
Finally, check what version of the desktop app you are using. Update to latest if possible.

**Comment by eromartin** [comment]
Okay so heres some pictures the first is when i open the online wallet it automaticaly opens the hidden wallet wich is empty and i cant find a way to my normal wallet only but when i open desktop app i can choose wich one i want to view (i created the hidden wallet in desktop and its available online while the standart wallet wich was available online isnt anymore) hope i explained it good
On the first pic is online wallet after i enter the passphrase but i dont get to choose wich wallet i want to view
![Screenshot_1](https://user-images.githubusercontent.com/65623624/108835956-83cf9980-75d0-11eb-8768-f9530356075d.png)
2nd pick is the option to choose between wallets in desktop app
![Screenshot_2](https://user-images.githubusercontent.com/65623624/108835964-87fbb700-75d0-11eb-93e3-e4b3871cdaba.png)
3rd pic is my normal wallet wich im unable to find online
![Screenshot_3](https://user-images.githubusercontent.com/65623624/108836077-b37ea180-75d0-11eb-816c-71fd91e23b39.png)

**Comment by slowbackspace** [comment]
The web app you are using is our old wallet which doesn't support Bech32 bitcoin accounts. But don't worry! You can use the web version of Trezor Suite https://suite.trezor.io/web/

**Comment by slowbackspace** [comment]
I'm closing the issue as I believe it is solved. If using web version of Trezor Suite won't solve the problem for you feel free to reopen.
