### ISSUE TITLE
Show Ethereum addresses which have positive ETH/token balance

### ISSUE THREAD

**Issue by Tomm-y** [trezor/trezor-suite#3466]
If someone has ETH or its tokens on, for example, 20th address, the user can't access that address from within the Trezor Suite wallet. Now, I know that this is in a sense feature that should prevent our new users from sending ETH to multiple addresses without having the need to do so. 

At the same time, if someone with coins already located on the 20th address connects to the wallet, he/she is unable to access that address and thus use our wallet to send these coins elsewhere. - (He/she might even think that the coins are gone)

That's why I would suggest Trezor Suite automatically scans ETH derivation paths, and subsequently allows our users to interact with all of the addresses that hold any ETH or its tokens.

Alternatively, you can add an advanced feature, which would allow our users to choose from multiple different ETH addresses. - (They could choose in the same way that users of Myetherwallet can choose to access, for example, 20th address instead of just the first one)

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
