### ISSUE TITLE
Send form - fee level switches by itself

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#3468]
When setting custom fee to 0 and then choosing any of the other fee levels, the selected fee level switches back to _Custom_ by itself.

**Info:**
 - Suite version: desktop 21.2.2 (7e8958e206885cd7946f431b63dad3bd446ef82e)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.2.2 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

![0fee](https://user-images.githubusercontent.com/31506317/108797650-f79b8300-758b-11eb-96f3-c4fd10a54ef3.gif)

_Originally posted by @bosomt in https://github.com/trezor/trezor-suite/issues/3458#issuecomment-783843558_

**Comment by tomexx** [comment]
@alex-jerechinsky is this still valid for the latest develop https://suite.corp.sldev.cz/suite-web/develop/web/ ? I am not able to replicate it, does it happen only for BTC, if it is in place can you try also BTC Testnet or other coins if the problem applies for other coins as well?

**Comment by jerechinsky** [comment]
I wasn't able to replicate either. @bosomt could you please try again on latest develop?

**Comment by bosomt** [comment]
@alex-jerechinsky i was not able to reproduce the issue

**QA OK**

**Info:**
 - Suite version: desktop 21.3.2 (6dbeaf3dd28a11c5e4bc5867686f58d2920a14bd)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.3.2 Chrome/87.0.4280.141 Electron/11.2.1 Safari/537.36
 - OS: Win32
 - Screen: 1536x864
 - Device: model One 1.9.4 regular

**Comment by jerechinsky** [comment]
thank you
