### ISSUE TITLE
Dashboard, Accounts - Inconsistent graph range designs

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3471]
**Describe the bug**
Range part of the graphs is the part of graph on the Dashboard screen and is not in each account in the Accounts screen.

**Info:**
 - Remembered Wallet: any
 - Suite Version: 21.3.0 web, commit 44e1c8d8
 - Browser: Chromium 88.0.4324.150
 - OS: Nixos 20.09
 - Bridge: 2.0.27
 - Firmware Version: model T 2.3.5 public

**Steps to reproduce:**
1. Navigate to the Dashboard screen and verify Range select position,
2. Navigate to the Accounts screen, select an arbitrary account and verify Range select position,
3. Compare.

**Expected result:**
Consistent inclusion of the Range select.

**Actual result:**
Range select is part of the graph on Dashboard and is not in each account overview.

**Screenshots:**
Dashboard
![image](https://user-images.githubusercontent.com/10185314/109166660-3b091380-777d-11eb-9420-c8534746207c.png)

Accounts
![image](https://user-images.githubusercontent.com/10185314/109166006-8242d480-777c-11eb-8d38-70c657d95d7d.png)

**Note(s):**
Unsure if the total amount should also be part of the graph when the account header already displays it.

**Comment by jerechinsky** [comment]
@sorooris are you saying that range selection from the dashboard doesn't reflect upon the range selection in each of the accounts? I'm not sure I understand.

**Comment by sorooris** [comment]
Sorry for the confusion @alex-jerechinsky, it took me some time to decode as well - the issue described here is that the range selection is inside the graph's border on the Dashboard and outside the border in Accounts.
![image](https://user-images.githubusercontent.com/10185314/132741163-7f55beee-be38-44bb-8306-101acac96642.png)

**Comment by glacierbits** [comment]
This will be handled by Suite 3.0 (re)design
