### ISSUE TITLE
Trezor Model T Does Not Send Out USDC (Pending Tx)

### ISSUE THREAD

**Issue by casoCornelius** [trezor/trezor-suite#3477]
I attempted to transfer USDC from my Trezor Model T. The Tx has been pending and Etherscan cannot even find the transaction. In Trezor suite it appears as "Pending" long time after I've sent it

**Comment by bosomt** [comment]
**QA OK**

Suite ERC20 transactions are working fine now.

**Info:**
 - Suite version: web 21.7.1 (24cc565a3badd85ab48b30348022471dfd85f90e)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.2 regular
