### ISSUE TITLE
Add account modal - Coin not supported

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3478]
Please consider to update/upgrade this modal when coin is not supported by Trezor model.
See:
see issue https://github.com/trezor/trezor-suite/issues/3085

![image](https://user-images.githubusercontent.com/31506317/109161500-6b4db380-7777-11eb-8cd6-8c3de00cfd2c.png)

**Comment by jerechinsky** [comment]
If a user is on model 1 (not model T with BTC only firmware), I would suggest replacing "_Firmware does not have capability to work with XRP_" with "_XRP is supported only on model T_"
@matejzak please ack or suggest rephrasing it 🙂

**Comment by bosomt** [comment]
**QA OK**

changed as expected in new add coin and in crypto section of settings.

**Info:**
 - Suite version: desktop 21.8.0 (566ba345c50b6fd7e773a905d5d8f40c7f8056f2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model 1 1.10.1 regular
