### ISSUE TITLE
[ERROR] On project install 

### ISSUE THREAD

**Issue by emidev98** [trezor/trezor-suite#3483]
**Describe the bug**
When I run yarn install cannot apply patch.

**Info:**
 - Suite Version: app and web
 - OS: Windows 10 Pro 10.0 Build 19042
 - NPM: 6.14.8
 - NodeJS: 14.15.1

**Steps to reproduce:**
Install project in Windows 10 for first time.

**Expected result:**
To be able to install and start the project.

**Actual result:**

`
Emi@DESKTOP-5V9QTF2 MINGW64 ~/Desktop/trezor-suite (develop)
$ yarn install
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.1: The platform "win32" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.2" has unmet peer dependency "@octokit/core@>=3".
warning " > @trezor/components@1.0.0" has unmet peer dependency "react@17.0.1".
warning " > @trezor/components@1.0.0" has unmet peer dependency "styled-components@^5.1.1".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > react-datepicker@3.4.0" has incorrect peer dependency "react@^16.9.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > react-datepicker@3.4.0" has incorrect peer dependency "react-dom@^16.9.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > react-truncate@2.4.0" has unmet peer dependency "prop-types@<= 15.x.x".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > react-truncate@2.4.0" has incorrect peer dependency "react@<= 16.x.x".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > awesome-typescript-loader@5.2.1" has incorrect peer dependency "typescript@^2.7 || ^3".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/integration-tests > @cypress/webpack-preprocessor@5.5.0" has unmet peer dependency "babel-loader@^8.0.2".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/integration-tests > cypress-image-snapshot@4.0.0" has incorrect peer dependency "cypress@^4.5.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/landing-page > babel-plugin-styled-components@1.12.0" has unmet peer dependency "styled-components@>= 2".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite-desktop > @zeit/next-workers@1.0.0" has incorrect peer dependency "worker-loader@^2.0.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite-native > react-native@0.63.4" has incorrect peer dependency "react@16.13.1".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite-native > react-navigation-stack@1.10.3" has incorrect peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite > react-qr-reader@2.2.1" has incorrect peer dependency "react@~16".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite > react-qr-reader@2.2.1" has incorrect peer dependency "react-dom@~16".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite > react-text-truncate@0.16.0" has incorrect peer dependency "react@^15.4.1 || ^16.0.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite > react-text-truncate@0.16.0" has incorrect peer dependency "react-dom@^15.4.1 || ^16.0.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite > recharts@2.0.0-beta.1" has incorrect peer dependency "react@^16.0.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite > recharts@2.0.0-beta.1" has incorrect peer dependency "react-dom@^16.0.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > react-datepicker > react-onclickoutside@6.9.0" has incorrect peer dependency "react@^15.5.x || ^16.x".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > react-datepicker > react-onclickoutside@6.9.0" has incorrect peer dependency "react-dom@^15.5.x || ^16.x".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > @storybook/addon-actions > react-inspector@5.1.0" has incorrect peer dependency "react@^16.8.4".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite-desktop > @types/next-redux-wrapper > next-redux-wrapper@6.0.2" has unmet peer dependency "react-redux@*".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite > react-focus-lock > use-callback-ref@1.2.4" has incorrect peer dependency "react@^16.8.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite > react-focus-lock > use-sidecar@1.0.3" has incorrect peer dependency "react@^16.8.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite > recharts > react-resize-detector@4.2.3" has incorrect peer dependency "react@^16.0.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite > recharts > react-resize-detector@4.2.3" has incorrect peer dependency "react-dom@^16.0.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite > recharts > react-smooth@1.0.6" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite > recharts > react-smooth@1.0.6" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/suite > @formatjs/cli > @vue/compiler-sfc@3.0.5" has unmet peer dependency "vue@3.0.5".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > @storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > @storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > @storybook/core > @storybook/ui > react-helmet-async@1.0.7" has incorrect peer dependency "react@^16.6.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > @storybook/core > @storybook/ui > react-helmet-async@1.0.7" has incorrect peer dependency "react-dom@^16.6.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > @storybook/core > @storybook/ui > react-sizeme@2.6.12" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > @storybook/core > @storybook/ui > react-sizeme@2.6.12" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-0 || ^16.0.0".
warning "workspace-aggregator-4a644556-c83e-41b8-989c-e0fd48466c0e > @trezor/components > @storybook/addon-actions > @storybook/api > @reach/router > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
[5/5] Building fresh packages...
error C:\Users\Emi\Desktop\trezor-suite\node_modules\postinstall-postinstall: Command failed.
Exit code: 1
Command: node ./run.js
Arguments:
Directory: C:\Users\Emi\Desktop\trezor-suite\node_modules\postinstall-postinstall
Output:
**ERROR** Failed to apply patch for package electron-updater

  This happened because the patch file patches\electron-updater+4.3.5.patch could not be parsed.

  If you just upgraded patch-package, you can try running:

    cd patches\electron-updater+4.3.5.patc
    patch -p1 -i h
    npx patch-package electron-updater
    cd ../..

  Otherwise, try manually creating the patch file again.

  If the problem persists, please submit a bug report:

    https://github.com/ds300/patch-package/issues/new?title=Patch+file+parse+error&body=%3CPlease+attach+the+patch+file+in+question%3E

error Command failed with exit code 1.
error Command failed with exit code 1.
child_process.js:655
    throw err;
    ^

Error: Command failed: yarn run postinstall

**ERROR** Failed to apply patch for package electron-updater

  This happened because the patch file patches\electron-updater+4.3.5.patch could not be parsed.

  If you just upgraded patch-package, you can try running:

    cd patches\electron-updater+4.3.5.patc
    patch -p1 -i h
    npx patch-package electron-updater
    cd ../..

  Otherwise, try manually creating the patch file again.

  If the problem persists, please submit a bug report:

    https://github.com/ds300/patch-package/issues/new?title=Patch+file+parse+error&body=%3CPlease+attach+the+patch+file+in+question%3E

error Command failed with exit code 1.
error Command failed with exit code 1.

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (C:\Users\Emi\Desktop\trezor-suite\node_modules\postinstall-postinstall\run.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(344) [Uint8Array] [
      121,  97, 114, 110,  32, 114, 117, 110,  32, 118,  49,  46,
       50,  50,  46,  49,  48,  10,  36,  32, 121,  97, 114, 110,
       32, 112,  97, 116,  99, 104,  45, 112,  97,  99, 107,  97,
      103, 101,  10,  36,  32,  67,  58,  92,  85, 115, 101, 114,
      115,  92,  69, 109, 105,  92,  68, 101, 115, 107, 116, 111,
      112,  92, 116, 114, 101, 122, 111, 114,  45, 115, 117, 105,
      116, 101,  92, 110, 111, 100, 101,  95, 109, 111, 100, 117,
      108, 101, 115,  92,  46,  98, 105, 110,  92, 112,  97, 116,
       99, 104,  45, 112,
      ... 244 more items
    ],
    Buffer(682) [Uint8Array] [
       10,  42,  42,  69,  82,  82,  79,  82,  42,  42,  32,  70,
       97, 105, 108, 101, 100,  32, 116, 111,  32,  97, 112, 112,
      108, 121,  32, 112,  97, 116,  99, 104,  32, 102, 111, 114,
       32, 112,  97,  99, 107,  97, 103, 101,  32, 101, 108, 101,
       99, 116, 114, 111, 110,  45, 117, 112, 100,  97, 116, 101,
      114,  10,  32,  32,  32,  32,  10,  32,  32,  84, 104, 105,
      115,  32, 104,  97, 112, 112, 101, 110, 101, 100,  32,  98,
      101,  99,  97, 117, 115, 101,  32, 116, 104, 101,  32, 112,
       97, 116,  99, 104,
      ... 582 more items
    ]
  ],
  pid: 11960,
  stdout: Buffer(344) [Uint8Array] [
    121,  97, 114, 110,  32, 114, 117, 110,  32, 118,  49,  46,
     50,  50,  46,  49,  48,  10,  36,  32, 121,  97, 114, 110,
     32, 112,  97, 116,  99, 104,  45, 112,  97,  99, 107,  97,
    103, 101,  10,  36,  32,  67,  58,  92,  85, 115, 101, 114,
    115,  92,  69, 109, 105,  92,  68, 101, 115, 107, 116, 111,
    112,  92, 116, 114, 101, 122, 111, 114,  45, 115, 117, 105,
    116, 101,  92, 110, 111, 100, 101,  95, 109, 111, 100, 117,
    108, 101, 115,  92,  46,  98, 105, 110,  92, 112,  97, 116,
     99, 104,  45, 112,
    ... 244 more items
  ],
  stderr: Buffer(682) [Uint8Array] [
     10,  42,  42,  69,  82,  82,  79,  82,  42,  42,  32,  70,
     97, 105, 108, 101, 100,  32, 116, 111,  32,  97, 112, 112,
    108, 121,  32, 112,  97, 116,  99, 104,  32, 102, 111, 114,
     32, 112,  97,  99, 107,  97, 103, 101,  32, 101, 108, 101,
     99, 116, 114, 111, 110,  45, 117, 112, 100,  97, 116, 101,
    114,  10,  32,  32,  32,  32,  10,  32,  32,  84, 104, 105,
    115,  32, 104,  97, 112, 112, 101, 110, 101, 100,  32,  98,
    101,  99,  97, 117, 115, 101,  32, 116, 104, 101,  32, 112,
     97, 116,  99, 104,
    ... 582 more items
  ]
}
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`

**Comment by keraf** [comment]
Windows is currently not a supported development environment for Suite. We could eventually make it work but it's definitely not a priority as none of our developers use Windows.

If you still wish to use Windows to build Suite, I would recommend looking at [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) (no guarantees that it works, haven't tested it myself) or using a Linux VM.

**Comment by emidev98** [comment]
Thanks, I'll switch to Linux.
