### ISSUE TITLE
[ERROR] Module not found when start the project 

### ISSUE THREAD

**Issue by emidev98** [trezor/trezor-suite#3484]
**Describe the bug**
Project won't start in local when execute **npm run suite:dev** after clean install in Debian.

**Info:**
 - OS: Debian 10 
 - Node: 14.16.0
 - NPM: 6.14.11
 - YARN: 1.22.10

**Steps to reproduce:**
Clone the project, install the dependencies with **yarn install**, run **npm run postinstall** and execute the project with **npm run suide:dev**.

**Actual result:**
![image](https://user-images.githubusercontent.com/49301655/109433312-03fe6080-7a10-11eb-80dd-5ebb81ceda4c.png)

**Comment by prusnak** [comment]
Did you run `yarn build:libs` like mentioned in the readme?

Also, don't use `npm run suite:dev` but `yarn suite:dev`.

**Comment by emidev98** [comment]
Thank you very much for that fast response , seems to be working now. 
Sorry for that I am not very familiar with yarn.

**Comment by prusnak** [comment]
> Sorry for that I am not very familiar with yarn.

No worries! Glad, we worked that out!
