### ISSUE TITLE
Support for Omni network

### ISSUE THREAD

**Issue by Sascha-1** [trezor/trezor-suite#3489]
https://coinmarketcap.com/currencies/maidsafecoin/

**Comment by prusnak** [comment]
Omni is a network built on top of Bitcoin network. It utilises OP_RETURN outputs to transfer tokens.

Currently the biggest tokens built on the Omni network are OMNI, USDT (Tether) and MAID (MaidSafeCoin).

The network could be used via OMNI Trezor wallet - https://trezor.github.io/omni-trezor/ - but this is unofficial.

Omni Explorer: https://omniexplorer.info

**Comment by stepmes** [comment]
Thanks @Sascha-1 for this input, we're noting it down and will consider it when working on future improvements.
