### ISSUE TITLE
Multiple ripple/blockbook workers

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3490]
possibly related to https://github.com/trezor/trezor-suite/issues/3214

Tested on macOS app based on 21.3.0 (custom build I made for easier troubleshooting). No special steps, just btc and xrp enabled, all seed, idle app (though I have the app running for about 4 hours now, one sleep in between which looks like triggers this ripple worker behaviour).

Each Ripple worker lives for exactly 3 minutes. Nothing interesting in passed messages.
Multiple backends (s-west.ripple, s1.ripple) are used for connection, it doesn't spawn new ws connection every time, sometimes it looks like old connection is reused.

<img width="882" alt="Screenshot 2021-03-01 at 20 36 44" src="https://user-images.githubusercontent.com/6961901/109549136-d8da4680-7acd-11eb-9cb1-d2cd2288011f.png">
<img width="688" alt="Screenshot 2021-03-01 at 20 40 49" src="https://user-images.githubusercontent.com/6961901/109549563-6ae24f00-7ace-11eb-9b9a-d0db1961baae.png">

![image](https://user-images.githubusercontent.com/6961901/109550423-8c900600-7acf-11eb-9b31-da90b277c6f0.png)

**Comment by slowbackspace** [comment]
Reproduced ripple issue after putting the computer to sleep and waking it up 2 minutes later.
I also saw "backend disconnected" banner in suite. It also affects blockbook worker (btc-like, eth coins) in a way that they need to create a new connection, which is imo reasonable. Only ripple worker creates a new connection every 3 minutes.

(btc, xrp coins enabled)

<img width="464" alt="Screenshot 2021-03-02 at 10 18 30" src="https://user-images.githubusercontent.com/6961901/109626724-2ba11600-7b41-11eb-943b-791cbb2f07ea.png">
<img width="890" alt="Screenshot 2021-03-02 at 10 21 59" src="https://user-images.githubusercontent.com/6961901/109626730-2cd24300-7b41-11eb-8b5c-64c2b1be8f72.png">

**Comment by slowbackspace** [comment]
Another run, where I did sleep&wake up about 30 times with only ETH enabled.
still 1 worker = 1 connection after each wake, but there is no issue like for xrp, where each 3 mins new connection is created. Once connection is established it keeps open.
If these old workers are not garbage collected then it could be a problem since this issue will also affect users with poor internet connections which could be disconnected from backends too often.

![image](https://user-images.githubusercontent.com/6961901/109639208-34004d80-7b4f-11eb-89e2-6128c286ee21.png)
<img width="880" alt="Screenshot 2021-03-02 at 12 02 01" src="https://user-images.githubusercontent.com/6961901/109639413-6e69ea80-7b4f-11eb-82b7-75a16b83bab9.png">

**Comment by szymonlesisz** [comment]
blockchain-link should call [terminate on workers](https://github.com/trezor/trezor-suite/blob/develop/packages/blockchain-link/src/index.ts#L279) and delete references BUT! connect [is not using](https://github.com/trezor/connect/blob/develop/src/js/backend/BlockchainLink.js#L70) dispose method at all, so there is a possibility that this worker is not collected by GC

**Comment by slowbackspace** [comment]
I'm confirming that calling worker.dispose() on error indeed clears old workers. I'll let QA test this overnight to see if this is enough to resolve abnormal memory usage. (tested on custom build with only added `dispose()`)
cc @bosomt you now what to do! 😁 

<img width="764" alt="Screenshot 2021-03-02 at 18 44 52" src="https://user-images.githubusercontent.com/6961901/109691281-907f5f00-7b87-11eb-9856-9dfc9eb407dd.png">
<img width="581" alt="Screenshot 2021-03-02 at 18 45 00" src="https://user-images.githubusercontent.com/6961901/109691293-9412e600-7b87-11eb-9501-872508498627.png">

**Comment by slowbackspace** [comment]
after running custom build with the fix above for about 20 hours I don't see any significant leaks in suite, only [trezord](https://github.com/trezor/trezord-go/issues/223) 😁 
<img width="1609" alt="Screenshot 2021-03-04 at 09 22 49" src="https://user-images.githubusercontent.com/6961901/109933492-c2014300-7ccb-11eb-83d6-6d65a8078740.png">

**Comment by slowbackspace** [comment]
fixed in https://github.com/trezor/trezor-suite/commit/564b3327af5c56659a20710a761f3c8462c292b8
