### ISSUE TITLE
copy files from suite-data before suite-desktop build

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3497]
Consider auto running `copy-files` job before build:mac/lin/win. I was expecting this is already done because when you run `yarn suite:dev` it indeed copy the files.

You may be asking what it is good for, but I just spent more than an hour editing connect files in suite-data dir without realizing they are not copied to suite-desktop on `yarn workspace @trezor/suite-desktop build:mac` 😓

**Comment by prusnak** [comment]
Ideally, we should not need to require copying the files and use them from the original location during the build. Is that possible?

**Comment by jerechinsky** [comment]
Not relevant.
