### ISSUE TITLE
Support Unstoppable Domains

### ISSUE THREAD

**Issue by trymeouteh** [trezor/trezor-suite#3498]
I know some will prefer FIO or something else, but I would like to suggest adding support on integrating Unstoppable Domains

- Support .zil and .crypto addresses
- Ability to buy multiple unstoppable domains with crypto in the app 
- Ability to transfer multiple unstoppable domains to another address in the app
- Ability to add crypto addresses to multiple unstoppable domains in the app
- Ability to send crypto to an unstoppable domain address in the app

I prefer Unstoppable Domains since they are a one time purchase and you have it for life unlike FIO addresses, they are human readable and can help with adoption by being able to tell others were to send crypto to. Unstoppable domains can be used for other things like hosting IPFS stuff but I dont see a need for Trezor to support all of that, just for the ability to register, transfer domains and be able to easily accept crypto using a unstoppable domain.

Trezor will be a great wallet to store and manage your unstoppable domains securely

EDIT:
ZIL support is not really need as much since Unstoppable Domains now supports up to 9 different domain extensions that are available on the Ethereum blockchain which are

.crypto
.coin
.wallet
.bitcoin
.x
.888
.nft
.dao
.blockchain

**Comment by matejkriz** [comment]
There is an open pull request for it https://github.com/trezor/trezor-suite/pull/2359

**Comment by trymeouteh** [comment]
https://github.com/trezor/trezor-suite/issues/3260#issuecomment-1003658291

By Adding WalletConnet you can have Unstoppable Domains support?
