### ISSUE TITLE
Show Suite Dashboard without connected Trezor

### ISSUE THREAD

**Issue by HeroHann** [trezor/trezor-suite#3503]
**Is your feature request related to a problem? Please describe.**
When checking the Wallet balance we need to connect the Trezor each time. When a new incoming transaction is there, we cannot check the status without connection the Trezor.

**Describe the solution you'd like**
I would like to access the suite dashboard without the connected device. If it is some encryption problem maybe a password could decrypt the needed data.

**Describe alternatives you've considered**
At the moment we need to track our addresses from the Trezor on a Block-Explorer.

**Comment by keraf** [comment]
Hi @HeroHann,

If I understand your inquiry correctly, this is already possible by remembering your device. 

To do this, go to the device selector on the top left, switch on "Remember" under the device you wish to remember. You can then open Suite and view your balances and transactions. Of course, certain operations like generating new addresses or sending coins will require your device to be connected.

**Comment by HeroHann** [comment]
Well if thats the case I am sorry!
I will check that. Though when I reconnect all my balances are there and I think I clicked the „remember“ button.

**Comment by keraf** [comment]
That's no problem at all :slightly_smiling_face: Please check if it works and close the issue if it does. Otherwise, you can provide us more information and we will look into it.
