### ISSUE TITLE
duplicated empty passphrase redirects to incorrect wallet

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3517]
Suite version: production 21.2.3 from suite.trezor.io, model T fw 2.3.5

While fixing https://github.com/trezor/trezor-suite/issues/3277 I run into another issue.

https://user-images.githubusercontent.com/6961901/110364011-8fe13f80-8043-11eb-94bd-9a3f3598401f.mov

Steps to reproduce I followed, but I am sure this has more minimal repro case:
1. create hidden wallet (passphrase=a), entered on device
2. create hidden wallet (passphrase="") => this is really a standard wallet (despite its name "hidden wallet #x") since I entered empty passphrase, but that's not the bug I am gonna show you
3. create another hidden wallet (passphrase="c") => double confirm ok
4. create hidden wallet, passphrase="", entered in suite
5. suite correctly detects that the wallet already exists (should be same standard wallet as created in step 2)
6. click "continue to discovered wallet"
7. you will end up in incorrect wallet, not the expected standard wallet

**Comment by tsusanka** [comment]
> you will end up in incorrect wallet, not the expected standard wallet

@slowbackspace do I understand it correctly you end up at wallet #1 at the end (passphrase=a)?

Also did you check you are indeed in the wrong wallet? It could be just an UI thing. In another words I want to say we should check the addresses (for example BTC's)

**Comment by slowbackspace** [comment]
> > you will end up in incorrect wallet, not the expected standard wallet
> 
> @slowbackspace do I understand it correctly you end up at wallet #1 at the end (passphrase=a)?
> 
> Also did you check you are indeed in the wrong wallet? It could be just an UI thing. In another words I want to say we should check the addresses (for example BTC's)

I showed in the video that, in standard wallet, there are many transactions in first BTC account (it's "all" seed). While I am not completely sure if addresses were also incorrect, I don't think this is some cosmetic issue. I ended up in wrong wallet which is clearly visible at 1:20-1:32: first hidden wallet got selected and there are no transactions. But feel free to try it on your own, I tried to document steps the best I can so there is no confusion :)

**Comment by Oxidant99** [comment]
Confirm above issue Trezor Suite 21.2.3  Trezor Model T firmware 2.3.6
In Trezor Suite created standart wallet, but with switched on empty "" passpahrase (just hit enter). See this wallet in Trezor Suite  only as "Standart Wallet". Balance is correct.  
Via https://wallet.trezor.io/ can not get acess to this wallet - see only "Standart wallet" with  zero balance, no transactions. Tried to switch on/off passphrase in both Suite /  Web application - no result. Seems to be really 2 different wallets. 

How to get acess to the wallet with balance via web? Pin is correct, seed is ok, passpahrase empty.

**Comment by slowbackspace** [comment]
Hi @Oxidant99, what you are experiencing is most likely due to wallet.trezor.io not supporting bech32 bitcoin accounts, which is a default account in Trezor Suite app. You can use web version of Trezor Suite on https://suite.trezor.io/web/

**Comment by bosomt** [comment]
**QA OK**

Windows 10.0.19042.868
Suite 21.3.2 commit 6dbeaf3dd28a11c5e4bc5867686f58d2920a14bd 
Device model T 2.3.5 public version

**Comment by sorooris** [comment]
**QA OK**

Additionally tested different combinations, couldn't replicate issue.

Suite: 21.3.2 6dbeaf3d
OS: macOS Big Sur 11.2.3
Device: model T 2.3.5 public
