### ISSUE TITLE
Google-auth-lib

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#3527]
Szymon said it's "flaky". Could you please elaborate a bit further, @slowbackspace ? 🙂

**Comment by keraf** [comment]
This library is intended for NodeJS and we use it in the front-end, which requires us to import polyfills and "null-resolve" NodeJS APIs that don't exist in the browser (to mute build errors).

The library that replaces this (if we use one) should be intended for the browser.

**Comment by jerechinsky** [comment]
There's is no feasible, good alternative for this google-auth-lib.
