### ISSUE TITLE
Missing space between the device name and an account name when sending tx

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#3530]
**Describe the bug**
There is a missing space between the device name and an account name when you are sending a transaction. Screenshot attached
**Steps to reproduce:**
1. Add a standard wallet.
2. Create a hidden wallet.
3. Try to send some currency from one wallet to another.
4. There is no space between "Hidden wallet #1" and "Account name #1" (as can be seen in screenshot)

**Info:**
 - Suite version: desktop 21.3.1 (1dbc5b720515c39a47f1dc58391dbebf1d766394)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.3.1 Chrome/87.0.4280.141 Electron/11.2.1 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.3.6 regular

**Expected result:**
There should be a space between a wallet name and an account name.

**Actual result:**
There is no space between a wallet name and an account name.

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/110500608-ae097700-80f9-11eb-91a2-37a5c63a0339.png)
![image](https://user-images.githubusercontent.com/48477147/110500657-b8c40c00-80f9-11eb-8495-c981a7f238e2.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.4.1 (3ed454e4e81b72482a9ad780c5cce9846cb29fb1)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.4 regular
