### ISSUE TITLE
Overview - Incorrect time displayed in transactions near midnight

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3531]
**Describe the bug**
Transactions sent pre-midnight (23:02) - UTC time zone (on blockbook) - are displayed in Suite as over 24, i.e. 24:02, of the ex.

**Info:**
 - Remembered Wallet: does not matter (tested remembered)
 - Suite Version: app and web 21.3.1, commit 1dbc5b7
 - Browser: Chromium 88.0.4324.150
 - OS: macOS 11.2.2 Big Sur, NixOS 20.09
 - Bridge: any (tested bundled 2.0.27, standalone 2.0.28)
 - Firmware Version: model T 2.3.5 public

**Steps to reproduce:**
1. Send a tx near midnight,
2. Wait for it to be mined,
3. Observe.

**Expected result:**
Transaction's time is displayed according to the 24 hour format.

**Actual result:**
24 hour format is broken and transaction time displayed is over 24.

**Screenshots:**
Suite transaction history
![image](https://user-images.githubusercontent.com/10185314/110503654-b1523200-80fc-11eb-92a4-501afd887ed4.png)
Blockbook
![image](https://user-images.githubusercontent.com/10185314/110503857-e8c0de80-80fc-11eb-94aa-e327ff221d00.png)
![image](https://user-images.githubusercontent.com/10185314/110503880-ee1e2900-80fc-11eb-87d2-aae295a35fb7.png)
![image](https://user-images.githubusercontent.com/10185314/110503891-efe7ec80-80fc-11eb-89f4-0da6f6668827.png)

Transactions:
https://btc1.trezor.io/tx/8b2f06738c2a2f1b793791eecc4f45c83bf86cbebf8aa1bae2dc9c6a0a743b7e
https://btc1.trezor.io/tx/ead3ac3a3dbeec17153c9a50e1269b8d930ea992b9d4afa24ff622a816e23348
https://btc1.trezor.io/tx/8559ba0570fc5428f9c36e27b9cb7dea63004d2e96b455e03dfa1d8b094da84c

**Comment by slowbackspace** [comment]
@trezor/qa could you pls check this branch in chrome and firefox https://suite.corp.sldev.cz/suite-web/fix/24h-time/web/ should be fine in both.

**Comment by bosomt** [comment]
@slowbackspace looks OK in cfabc36f5ad6f0b39b10cb236393c9b4c42480b4

**Comment by bosomt** [comment]
**QA OK**

tested in Firefox and Chromium Version 89.0.4389.72 (Official Build) (64-bit)

**Info:**
 - Suite version: web 21.4.0 (1da73bf5c45ed462662a4b3f12b10993625b9999)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
