### ISSUE TITLE
Out of memory renderer crash

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3534]
**Describe the bug**
Letting the app running idle results in running out of memory and renderer crash.

**Info:**
 - Remembered Wallet: yes, all coins enabled
 - Suite Version: app 21.3.1 
 - OS: Windows 10 Pro 10.0.19042 
 - Bridge: 2.0.27 Suite-bundled
 - Firmware Version: model T 2.3.5 disconnected

**Steps to reproduce:**
1. Launch Suite app, remember Wallet with tx history, enable all coins,
2. Let run idle for over 24 hours,
3. Navigate through accounts and let them update.

**Expected result:**
Memory usage is stable after any amount of time with and without active usage.

**Actual result:**
Running idle results in a renderer crash after running out of memory.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/110605869-db056a80-8189-11eb-9b27-b24763dca0ab.png)
![image](https://user-images.githubusercontent.com/10185314/110605880-de005b00-8189-11eb-8842-7897b4214219.png)

**Note(s):**
Detailed log available [here](https://drive.google.com/file/d/1MwhzxkINK2HX-5PIIJ3JC8L1FEbjZmqN/view?usp=sharing)
Discovered during https://github.com/trezor/trezor-suite/issues/3214 retest on Win10.

**Comment by slowbackspace** [comment]
What about labelling? Was it enabled? It could be same reason as for this https://github.com/trezor/trezor-suite/issues/3214#issuecomment-794043660

**Comment by sorooris** [comment]
> What about labelling? Was it enabled? It could be same reason as for this [#3214 (comment)](https://github.com/trezor/trezor-suite/issues/3214#issuecomment-794043660)

@keraf already asked me; i couldn't verify at the time, afaik it wasn't on during the time and it wasn't on when i re-launched the app. Could be related to the issue.

**Comment by szymonlesisz** [comment]
notice the number of coingecko requests before (2021-03-09T09:03) and after (2021-03-09T20:41)

there is nothing in between, computer probably goes to sleep. but there was more than 1000 requests called at 20:41, after awaking

**Comment by szymonlesisz** [comment]
i guess the app hibernates(?)  at some point (when is not focused?) and network requests/websocket notifications (new block) are buffered/throttled somehow.
then, after awaking all those notifications are triggered at once, leading to huge amount of requests (account updates and fiat rates updates)

the solution may be to add debouncing before processing backend notifications?

OR
there is something wrong with fiat rates [auto update intervals](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/actions/wallet/fiatRatesActions.ts#L340-L345)

result of those intervals are triggered after "app on focus", i dont see any websocket request after 2021-03-09T20:41, there are coingeckos an then crash

**Comment by szymonlesisz** [comment]
im pretty sure that this is caused by `setInterval` request + app `on blur / on focus`

same thing is with auto-update requests. they goes on every hour, then between 09 and 20 there is nothing, and finally 10 request after awaking:

```
2021-03-09T20:41:29.532Z - INFO(auto-updater): Update checking request (manual: No)
2021-03-09T20:41:29.532Z - INFO(auto-updater): Update checking request (manual: No)
2021-03-09T20:41:29.532Z - INFO(auto-updater): Update checking request (manual: No)
2021-03-09T20:41:29.532Z - INFO(auto-updater): Update checking request (manual: No)
2021-03-09T20:41:29.533Z - INFO(auto-updater): Update checking request (manual: No)
2021-03-09T20:41:29.533Z - INFO(auto-updater): Update checking request (manual: No)
2021-03-09T20:41:29.533Z - INFO(auto-updater): Update checking request (manual: No)
2021-03-09T20:41:29.534Z - INFO(auto-updater): Update checking request (manual: No)
2021-03-09T20:41:29.534Z - INFO(auto-updater): Update checking request (manual: No)
2021-03-09T20:41:29.535Z - INFO(auto-updater): Update checking request (manual: No)
```

**Comment by slowbackspace** [comment]
I found out that electron/chrome applies `backgroundThrottling`.
```
Whether to throttle animations and timers when the page becomes background. This also affects the Page Visibility API. Defaults to true.
```
https://www.electronjs.org/docs/api/browser-window

imo could be worth to try disabling it and see if it prevents gobbling up the requests
