### ISSUE TITLE
A feature that allows to see gains since deposit

### ISSUE THREAD

**Issue by danielkp1234** [trezor/trezor-suite#3536]
So I think its kinda annoying that you cant see your total gains since you have deposited coins. Something like you will able to look total gains increase/decrease from when prices of a coin increase/decrease

I would like a way to be able to see how many percentages and how many dollars my wallet has increased or decreased in value with a graph.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
