### ISSUE TITLE
You are allowed to bump different coin than BTC and ETH/ETC

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3539]
**Describe the bug**

See screenshots, you can bump transaction other than Bitcoin or Ethereum.
I sent it with multiple outputs and I turned lock-time on and off before I signed transaction.
I don't know if im able to bump this transaction /i will test it further/ and I'm not able to reproduce it when i send simple transaction to one address and one output.

EDIT: im not able to reproduce every time. So it's hard to find out how to reproduce it. But I was able to reproduce it 3 times.

https://dash1.trezor.io/tx/11f63710894398107c2380f2e5db344576939a36101241567972d12af4ebe819

**Steps to reproduce:**
1. Create transaction with multiple outputs to same address
2. Turn locktime on/off 
3. observe transaction detail

**Info:**
 - Suite version: web 21.3.1 (1dbc5b720515c39a47f1dc58391dbebf1d766394)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Expected result:**
You only are allows to bump BTC ETH and ETC transaction

**Actual result:**
You are allows to bump DASH transaction

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/110662030-6a7c3f00-81c5-11eb-85ba-cab328826b4f.png)

![image](https://user-images.githubusercontent.com/31506317/110662087-75cf6a80-81c5-11eb-9582-9ff174de5e30.png)

![image](https://user-images.githubusercontent.com/31506317/110662136-8253c300-81c5-11eb-9735-01fd697f9507.png)

![image](https://user-images.githubusercontent.com/31506317/110662662-0017ce80-81c6-11eb-852f-c91cf951e64a.png)

**Comment by szymonlesisz** [comment]
wait what? it should be disabled for other coins...

**Comment by bosomt** [comment]
Guess there is something that you can trigger that allows you to send any RBF enabled coin ;) 

https://doge1.trezor.io/tx/9e8be49b0e60e9b542730b8ab76d5f7cf3838ece6dae3e36b827604543d7decf

![image](https://user-images.githubusercontent.com/31506317/110771186-82ea6900-825a-11eb-85a7-1a0f4ce96a99.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.4.0 (d8afa44f141e1ae678cc89d8dda758b790888c06)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular
