### ISSUE TITLE
Show more decimal places for fiat value

### ISSUE THREAD

**Issue by mwmoseley** [trezor/trezor-suite#3540]
When viewing Assets, fiat values are rounded to the nearest cent (for USD). Some coins (like DOGE) operate on fractions of cents, so the rounded value isn't particularly useful. I'd like to suggest either adding a setting for how many decimal places to show, either globally or per asset, or implementing something that automatically shows more places if the fiat value is less than some (configurable?) threshold.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
