### ISSUE TITLE
tor process doesn't close after closing Trezor Suite [macOS]

### ISSUE THREAD

**Issue by caglorithm** [trezor/trezor-suite#3541]
**Describe the bug**
I Trezor Suite with the built-in tor support. When I terminate Trezor Suite, I can see the tor process still running (and also staying active on the tor network). 

**Info:**
 - Suite Version: app 20.12.1 (20.12.1.9537)
 - OS: macOS 11.2.2 (20D80)

**Steps to reproduce:**
1. Start Trezor Suite 
2. Enable Tor in Trezor Suite
3. Close Trezor Suite

**Expected result:**
tor process should be terminated

**Actual result:**
tor process keeps running

**Comment by prusnak** [comment]
> Suite Version: app 20.12.1 (20.12.1.9537)

Please use the latest Suite (21.3.1) downloaded from https://suite.trezor.io

You are using a very old version.

**Comment by caglorithm** [comment]
Same with new version. I close the app using CMD+Q.
