### ISSUE TITLE
Trezor News links are not being open as .onion

### ISSUE THREAD

**Issue by mmahut** [trezor/trezor-suite#3542]
**Describe the bug**

Trezor News links are not being open as `.onion` addresses.

**Info:**
 - Suite Version: app (AppImage), 21.3.1, 1dbc5b720515c39a47f1dc58391dbebf1d766394
 - OS: NixOS 

**Steps to reproduce:**
1. Go to the tor settings, enable "_Open trezor.io links as .onion links_".
2. Go to the Dashboard.
3. Click on any link on blog.trezor.io.

**Expected result:**
Opens as `.onion` or rename the Settings option to exclude Medium.

**Actual result:**
Opens blog.trezor.io directly.

**Comment by bosomt** [comment]
**QA OK**



**Info:**
 - Suite version: desktop 21.5.0 (130b17ff0d52b67079d29b4e7250637528be1def)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.5.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular
