### ISSUE TITLE
tor process doesn't close after closing Trezor Suite [macOS]

### ISSUE THREAD

**Issue by caglorithm** [trezor/trezor-suite#3543]
**Describe the bug**
I Trezor Suite with the built-in tor support. When I terminate Trezor Suite, I can see the tor process still running (and also staying active on the tor network). 

**Info:**
 - Suite Version: app 21.3.1 (21.3.1.10647)
 - OS: macOS 11.2.2 (20D80)

**Steps to reproduce:**
1. Start Trezor Suite 
2. Enable Tor in Trezor Suite
3. Close Trezor Suite (CMD+Q)

**Expected result:**
tor process should be terminated

**Actual result:**
tor process keeps running

**Comment by bosomt** [comment]
i was able to reproduce issue with 21.3.2 and 21.4.0 version

**Info:**
 - Suite version: desktop 21.4.0 (ab673f9777b6ddaf13234e5e6b3b3ab5be46852c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular

**Comment by keraf** [comment]
@trezor/qa Could you please test #3602 if it fixes the issue on Linux and Mac?

**Comment by bosomt** [comment]
**QA OK**

tested in MacOS 11.2.3. and KUbuntu 20.10

**Info:**
 - Suite version: desktop 21.4.0 (c6ec83b7c09580fab972518ca2892b77c2e2fbf1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.5 regular

**Comment by bosomt** [comment]
**QA OK**



**Info:**
 - Suite version: desktop 21.5.0 (130b17ff0d52b67079d29b4e7250637528be1def)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.5.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular
