### ISSUE TITLE
Transaction history - ERC20 tokens not included in search 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3544]
**Describe the bug**
When you look in Ethereum transaction history ERC20 tokens are not included in search.  

**Steps to reproduce:**
1. Load account that includes ERC20 token transactions 
2. Search for those transaction via search field
3. Observe

**Info:**
 - Suite version: web 21.4.0 (1da73bf5c45ed462662a4b3f12b10993625b9999)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Expected result:**
When you look in Ethereum transaction history ERC20 tokens are included in search.  

**Actual result:**
When you look in Ethereum transaction history ERC20 tokens are not included in search.  

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/111163203-3629c980-859d-11eb-8332-308ce1f80bfa.png)

![image](https://user-images.githubusercontent.com/31506317/111164972-d3d1c880-859e-11eb-87bd-98eaf2b678dd.png)

![image](https://user-images.githubusercontent.com/31506317/111165067-eb10b600-859e-11eb-9940-a19c3a8eaf78.png)

**Comment by keraf** [comment]
Symbol names cannot be searched yet but I think it would be good to support that for tokens. I guess we can probably use a prefix to specifically return certain tokens (for example: `token:TUSD`). We could even pre-fill the search by clicking on that token. cc @matejzak @alex-jerechinsky @tsusanka

**Comment by bosomt** [comment]
Not sure if expected

see this [transaction](https://eth1.trezor.io/tx/0xa1001cd12662acdafe34e01b184cfb939c6e83d3594f94ea51f1c0051e8bdade)

when i look for `0x40ec5B33f54e0E8A33A975908C5BA1c14e5BbbDf` i dont see this transaction

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/c266a863-1e06-43e8-824f-83d2f978b9e2">

<img width="1133" alt="image" src="https://github.com/user-attachments/assets/095f4b8e-3137-40ba-b27f-0145c7e331e0">

**Info:**
 - Suite version: web 24.8.0 (986032c73693d8ce6a5c743fcbb91b662d20b8b3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
**QA OK**

- above fixed in different PR
- im able to search and find by token name
- im able to search and find by token contract
- im able to search and find by send address
- im able to search and find by receive address
- tested on ADA ETH ETC SOL

**Info:**
 - Suite version: web 24.8.0 (78027d7778919e53c1ba92adbac2adf89b8fdd55)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
