### ISSUE TITLE
Cardano (ADA) support

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3550]
Let's review:
- https://github.com/trezor/trezor-suite/pull/3627
- https://github.com/trezor/connect/pull/832
- https://github.com/trezor/trezor-suite/pull/4144

Needs trezor/trezor-firmware#1231 and trezor/trezor-firmware#1764

**Comment by jeebster** [comment]
@matejzak Can this issue be expanded to include other assets currently available in beta (`XLM`, etc.)? I'm happy to help with implementing this feature

**Comment by buzzlightyear2000** [comment]
A big YES for ADA support (and also XLM and DOT). Thanks for all your hard work on this project.

**Comment by tsusanka** [comment]
Let's review https://github.com/trezor/trezor-suite/pull/3627 in August sprint.

**Comment by Dominator1013** [comment]
Hi when can we expect full support for Cardano to be finished? Any possible date estimation? Also would it be for both trezor model 1 and model T ? Or only Model T? @matejzak 

Thanks!

**Comment by mmhorda** [comment]
> A big YES for ADA support (and also XLM and DOT). Thanks for all your hard work on this project.

I also cannot wait for ADA and XLM in Trezor Suite!

**Comment by MarekPasnikowski** [comment]
I am very happy to see Cardano being considered seriously.

**Comment by melroy89** [comment]
Native support would be awesome in Trezor Suite! Very much appreciated. 

I noticed that @matejzak removed this issue from the TODO list, which is not a good sign I think.

**Comment by melroy89** [comment]
Just curious: will Trezor Suite also allow staking cardano in cold storage?

**Comment by Foxnox** [comment]
ADA support was one of my main reasons for buying my Trezor. Even though I get by using Deadalus, I am really looking forward to this feature being implemented in Trezor Suite. Hopefully staking will be supported as well. :)

**Comment by ppriorfl** [comment]
> Native support would be awesome in Trezor Suite! Very much appreciated.
> 
> I noticed that @matejzak removed this issue from the TODO list, which is not a good sign I think.

ADA needed please - I don't understand when I buy Trezor wallet and it says ADA supported but then I can't see it in the Suite application - it's not really supported then is it - might as well just use my yoroi wallet alone.

**Comment by melroy89** [comment]
> ADA needed please - I don't understand when I buy Trezor wallet and it says ADA supported but then I can't see it in the Suite application - it's not really supported then is it - might as well just use my yoroi wallet alone.

Yeah its supported by Daedalus, adalite or yoroi in combination with the trezor device. But I agree ada isn't supported out of the box with the trezor suite.

**Comment by Hindsightgenius** [comment]
Was also the main reason I bought my Model T.  Have to say I was disappointed to see this integration.

**Comment by xanoni** [comment]
Well to defend Trezor (oops) here, just because the device supports it doesn't mean that Trezor Suite has to support it. 

Many people use Trezor without Trezor Suite.

Also, it may just not be the best use of the Trezor team's time to re-implement what someone else has already done well.

**Comment by Hindsightgenius** [comment]
I'd say at minimum and in the interest of fair marketing there should be an asterisk next to Cardano on their supported coins list saying "supported on device but not on suite".  That being said, the addition of Cardano to suite has recently been tagged "high priority" so I guess they think it's a worthwhile use of their time.

**Comment by ppriorfl** [comment]
Agree 100% - wouldn’t have spent the extra money. I want ONE wallet not to have to remember multiple different browser plugins etc

**Comment by Foxnox** [comment]
Really happy to see the status change to HIGH. Love the device and appreciate the time and dedication from the people working to realize this feature for all of us. Keep at it guys :)

**Comment by timemaster5** [comment]
+1 :)

**Comment by melroy89** [comment]
Nice, december 8 it is 🙏🎂!

**Comment by stefanobieler** [comment]
Is this the update we need to interact with smart contracts on are hardware wallets? i'm attempting to interact with a smart contract currently with NAMI and trezor. However i'm unable to set collateral with my hardware wallet.

**Comment by mark-stopka** [comment]
> Is this the update we need to interact with smart contracts on are hardware wallets? i'm attempting to interact with a smart contract currently with NAMI and trezor. However i'm unable to set collateral with my hardware wallet.

No, that is here...

https://github.com/vacuumlabs/trezor-firmware/pull/71

**Comment by Densum87** [comment]
Is this projected to release in the march firmware release (if there is one)?

**Comment by mark-stopka** [comment]
> Is this projected to release in the march firmware release (if there is one)?

See here https://github.com/vacuumlabs/trezor-firmware/pull/71#issuecomment-1026623541

As I already said, this feature has nothing to do with Alonzo support by Trezor Model T, but relates only to Trezor Suite which is a Ledger Live like wallet software.

**Comment by Densum87** [comment]
> > Is this projected to release in the march firmware release (if there is one)?
> 
> See here [vacuumlabs/trezor-firmware#71 (comment)](https://github.com/vacuumlabs/trezor-firmware/pull/71#issuecomment-1026623541)
> 
> As I already said, this feature has nothing to do with Alonzo support by Trezor Model T, but relates only to Trezor Suite which is a Ledger Live like wallet software.

Yes, I am aware. Looking for support of ADA in Trezor Suite. I am also keeping an eye on https://github.com/vacuumlabs/trezor-firmware/pull/71#issuecomment-1026623541

**Comment by osintowl** [comment]
Hey, I saw this is currently in the needs QA phase, do you need some testers? I'm happy to oblige I have a Model T and am happy to try a preview build with this on it to help with QA.

**Comment by sime** [comment]
@5A4B48 You can find it on the staging site: https://staging-suite.trezor.io/ and then click on 'Trezor suite for web'. Remember, this is still  an unreleased version of Trezor suite.

**Comment by ghost** [comment]
How far off public release are we for this version? I have ADA I am desperate to get off the exchange, but don’t want to move it to another wallet knowing Trezor is about to natively support it.

Are we talking days? Weeks? Months?

Thank you

**Comment by hynek-jina** [comment]
@RealDonaldTrump-69 
Public version is currently planned on March 16th. Turn on Early Access Program to get that access even one week earlier.

**Comment by ghost** [comment]
> @RealDonaldTrump-69
> Public version is currently planned on March 16th. Turn on Early Access Program to get that access even one week earlier.

Excellent! Thank you

**Comment by tsusanka** [comment]
Done 🎉 . To be released on March 16th publicly.

**Comment by osintowl** [comment]
Hey one quick bug I've found is duplicate tokens showing up in the token interface. Upleading a screenshot here
![Screenshot from 2022-03-14 11-09-53](https://user-images.githubusercontent.com/16806380/158213814-94fa905b-cfa6-478b-bda1-016932692ff4.png)

**Comment by osintowl** [comment]
notice the asset fingerprints are the same.

**Comment by ghost** [comment]
Just a FYI there is a spelling error here...

![Screen Shot 2022-03-21 at 8 12 11 pm](https://user-images.githubusercontent.com/101044509/159232351-ac47f58b-94bc-4082-bced-206ed6bb4a4a.png)

Should be "...you will receive _your_ reward"

**Comment by mroz22** [comment]
> Just a FYI there is a spelling error here...
> 
> ![Screen Shot 2022-03-21 at 8 12 11 pm](https://user-images.githubusercontent.com/101044509/159232351-ac47f58b-94bc-4082-bced-206ed6bb4a4a.png)
> 
> Should be "...you will receive _your_ reward"

cc @alex-jerechinsky

**Comment by jerechinsky** [comment]
Thank you. It'll be fixed in the next release.
