### ISSUE TITLE
Trezor Suite reports old firmware as up to date

### ISSUE THREAD

**Issue by mmahut** [trezor/trezor-suite#3551]
**Describe the bug**

Trezor Suite doesn't prompt for an update when a new firmware is available. Says an older firmware is up to date.

**Info:**
 - Remembered Wallet: yes and no
 - Suite Version: both app and web, commit 1dbc5b720515c39a47f1dc58391dbebf1d766394
 - Firmware Version: model T, revision 2.3.5

**Steps to reproduce:**
1. Be lazy and do not update your Trezor on firmware release day
2. Try to do it in a month
3. Suite doesn't prompt you to do so
4. Legacy wallet does, as it is outdated in [connect](https://github.com/trezor/connect/blob/develop/src/data/firmware/2/releases.json)

**Screenshots:**
![Screenshot from 2021-03-17 12-08-41](https://user-images.githubusercontent.com/104795/111458455-b9702a00-8719-11eb-8c44-5077dca734cc.png)

**Note(s):**

By the way, the link to 2.3.6 on the wiki is pointing to 2.3.5 github tag https://wiki.trezor.io/Firmware_changelog.

**Comment by prusnak** [comment]
This is a feature - firmware 2.3.6 contained only a single fix for Unchained Capital. We did not want to trigger this update for the Suite users.

**Comment by prusnak** [comment]
> By the way, the link to 2.3.6 on the wiki is pointing to 2.3.5 github tag https://wiki.trezor.io/Firmware_changelog.

Wiki fixed, will be deployed in 60 minutes tops. Thanks!
