### ISSUE TITLE
Missing progressbar for signing big transactions

### ISSUE THREAD

**Issue by laurentdebricon** [trezor/trezor-suite#3556]
**Describe the bug**

Signing a transaction hung on the Trezor T, then did it with success in trezor web
with trezor web i had a nice progress log.
with Suit, nothing about log.

i tried 3 times, with differents usb wire before doing it with the good old trezor web

**Info:**
 - Remembered Wallet: yes
 - Suite Version: Trezor-Suite-21.3.1-linux-x86_64
 - OS: ubuntu 20.04
 - Bridge: ?
 - Firmware Version: model T , 2.3.6

**Comment by prusnak** [comment]
Which coin was that? Can you post the link to the succeeded (in the old trezor web) transaction on the block explorer?

**Comment by laurentdebricon** [comment]
bitcoin, transaction sent to you privately

**Comment by prusnak** [comment]
Thanks. We've investigated the issue and we think it would work just fine with the Suite too - you just didn't let it finish it.

I am editing the issue to be about missing progressbar in the Suite.

**Comment by laurentdebricon** [comment]
ok. i waited so long the trezor locked itself, default configuration timer.

**Comment by szymonlesisz** [comment]
your trezor was freezed in this state:
![Screenshot from 2021-03-22 16-29-11](https://user-images.githubusercontent.com/3435913/112015508-2b86ab80-8b2c-11eb-8314-f800c5395441.png)

and then lockeditself?
or the freeze happened before the confirmation process? (you didn't confirm anything on device yet)

**Comment by laurentdebricon** [comment]
The freeze happened exactly as your picture, 3 times

**Comment by szymonlesisz** [comment]
i also saw that you've reported another issue about freezing device (custom image)
is it happened before or after signing transaction? it might be related

**Comment by laurentdebricon** [comment]
After. it freezes all the times I tried, for 2 differents trezor.

but don't get burned out, i really like trezor suite ! that's why i am spending time to reports the bugs i found

**Comment by laurentdebricon** [comment]
i was without trezor-bridge. just installed it now. no idea if usefull

```
Preparing to unpack trezor-bridge_2.0.27_amd64.deb ...
Unpacking trezor-bridge (2.0.27) ...
Setting up trezor-bridge (2.0.27) ...
Created symlink /etc/systemd/system/multi-user.target.wants/trezord.service → /lib/systemd/system/trezord.service.
```

**Comment by prusnak** [comment]
> i was without trezor-bridge. just installed it now. no idea if usefull

Please don't - the Suite has its own version of the bridge. Please uninstall the separate bridge and reboot your computer. Otherwise we won't be able to debug the issue.

**Comment by tsusanka** [comment]
@laurentdebricon did you experience this issue also without Bridge installed separately as suggested by @prusnak? Did you experience it also without a homescreen set on TT? Thanks for the info!

**Comment by laurentdebricon** [comment]
it was without bridge.
only this special transaction was getting blocked all the time ( i tried three times) , until i made it on trezor web.
i can't do it again, the others works

**Comment by tsusanka** [comment]
Do I understand it correctly, you can't reproduce anymore?

**Comment by laurentdebricon** [comment]
i can't reproduce it anymore.

**Comment by tsusanka** [comment]
Ok, please reopen if you manage to reproduce it. I believe it is most likely due to the [other issue you reported](https://github.com/trezor/trezor-suite/issues/3557) which we are addressing in FW as we speak. Thanks for the reports!
