### ISSUE TITLE
Set Custom Image, Trezor crash

### ISSUE THREAD

**Issue by laurentdebricon** [trezor/trezor-suite#3557]
**Describe the bug**
- Set custom Image, the hardware wallet hang and suit hang. 
- Disconnect, and reconnect, the hardware wallet still got the new image

in the zip attached i have put the jpeg, made with Gimp on Ubuntu, it's in a zip because maybe github could compress/edit/strip the pic
[trezor.zip](https://github.com/trezor/trezor-suite/files/6178366/trezor.zip)

**Info:**
 - Remembered Wallet: yes
 - Suite Version: Trezor-Suite-21.3.1-linux-x86_64.AppImage
 - OS: ubuntu 20.04
 - Firmware Version: trezor T , 2.3.6

**Comment by tsusanka** [comment]
Thanks for your report, this a long-standing firmware issue where we are running out of memory. We are addressing it now. We would like to introduce some fixes in ~Q3 but it needs a big firmware rewrite.

Related:
- https://github.com/trezor/trezor-firmware/issues/1114
- https://github.com/trezor/trezor-firmware/pull/1541
- https://github.com/trezor/trezor-firmware/pull/1540
- https://github.com/trezor/trezor-firmware/pull/1542
