### ISSUE TITLE
Update MacOS icons 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3558]
The current Suite desktop (BigSur, MacOS) icons are too large. 

Smaller icons based on [Apple Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon#:~:text=App%20Icon%20Sizes,1x%2C%201024x1024%20px%20%402x) here: [iconMensi.zip](https://github.com/trezor/trezor-suite/files/6182502/iconMensi.zip)

Currently:
<img width="165" alt="Screen Shot 2021-03-22 at 14 33 32" src="https://user-images.githubusercontent.com/29627086/111997720-9aa7d400-8b1b-11eb-8efb-1be4ed7815b1.png">

**Comment by bosomt** [comment]
** QA OK**

OS: MacOS BigSur M1 2020
Suite commit d8afa44f

**Comment by prusnak** [comment]
The icon is too small now :-/

When using the horizontal dock the difference is subtle. But when you have a vertical dock or you check the size in the Applications folder - the difference stands out.

<img width="57" alt="Screenshot 2021-04-09 at 18 14 03" src="https://user-images.githubusercontent.com/42201/114210085-a3900680-995f-11eb-8b53-3f1028e371c5.png">

**Comment by tomexx** [comment]
Hi @matejzak, I found this [free macOS 11 icon template](https://applypixels.com/resource/macos11-app-icon-lite). Can you please export the icon according to that? Thx

**Comment by glacierbits** [comment]
Second try (our apologies for the first): 

[Icon.zip](https://github.com/trezor/trezor-suite/files/6316852/Icon.zip)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.5.0 (fd3ceda56fe84a3daad5bab69c3bd07ad2fed753)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.5.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.4 regular
<img width="61" alt="Screenshot 2021-04-28 at 9 30 31" src="https://user-images.githubusercontent.com/31506317/116364664-baaa7180-a804-11eb-86d4-7852e6873f8c.png">
<img width="260" alt="Screenshot 2021-04-28 at 9 33 11" src="https://user-images.githubusercontent.com/31506317/116364707-c5650680-a804-11eb-9d00-d01d28e06d1e.png">

**Comment by prusnak** [comment]
@bosomt Can you please post a screenshot of vertical and horizontal dock with Safari and Chrome icons next to the Suite icon? (ideally, Safari - Suite - Chrome)

**Comment by bosomt** [comment]
@prusnak 

<img width="222" alt="Screenshot 2021-04-28 at 9 49 58" src="https://user-images.githubusercontent.com/31506317/116367013-2d1c5100-a807-11eb-9e0b-4bc0ce1cbb21.png">
<img width="31" alt="Screenshot 2021-04-28 at 9 50 14" src="https://user-images.githubusercontent.com/31506317/116367014-2e4d7e00-a807-11eb-9a07-06bf487ac8ca.png">
<img width="48" alt="Screenshot 2021-04-28 at 9 50 20" src="https://user-images.githubusercontent.com/31506317/116367016-2e4d7e00-a807-11eb-9b2f-74574f3393b6.png">

**Comment by prusnak** [comment]
Great, looks good!

Thank you, @bosomt
