### ISSUE TITLE
Bump TT FW to 2.3.6

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#3571]
Required commit in Connect is here: https://github.com/trezor/connect/commit/a1831647349900f96c3a87cb24b6141162daa645

**Comment by tsusanka** [comment]
@prusnak do we need to do this if we plan to release 2.4.0 in May? I understand it might be confusing to users but the whole FW in Suite release is quite manual and a bit painful at the moment. Or can we deploy Connect already?

**Comment by prusnak** [comment]
Ah, well. Let's close this and make sure we'll update the FW in May release.

**Comment by tsusanka** [comment]
Just a side note: if we do not release TT firmware in May 2.3.6 will be added by https://github.com/trezor/trezor-suite/pull/3637.
