### ISSUE TITLE
webusb firmware installation gets stuck

### ISSUE THREAD

**Issue by mcudev** [trezor/trezor-suite#3575]
**Describe the bug**

When testing the new device (or new user) workflow and with the trezord/bridge **NOT** running, firmware installation gets stuck / hangs at the "Trezor setup" "Restarting Trezor" "Do not disconnect your Trezor." modal dialog. I tested with a TT device that I had wiped the firmware off of. After the 2.3.5 firmware gets installed, the device restarts and boots fine. The OS registers it after it boots into the new firmware. Chrome see the new device in `chrome://device-log/`. I'm guessing that we need to add another "Find device" button for the WebUSB stuff to work again after the restart.

![image](https://user-images.githubusercontent.com/29890609/112735294-594f6400-8f21-11eb-9727-14bed7700be6.png)

**Info:**
 - Remembered Wallet: not applicable. starting from a "new" device state without firmware.
 - Suite Version: 21.3.2 at https://suite.trezor.io/web/
 - Browser: Google Chrome 89.0.4389.90 (Official Build) (64-bit)
 - OS: Ubuntu 20.10, windows 10, Mac OS X
 - Bridge: bridge not running
 - Firmware Version: T, 2.3.5

**Steps to reproduce:**
1. connect TT and swipe finger to get into bootloader mode
2. wipe the firmware with the following to simulate being a user of a new device: `trezorctl device wipe --bootloader`
3. ensure trezord/bridge is not running
4. unplug/replug TT
5. in chrome go to https://suite.trezor.io/web/
6. go through the steps to load the firmware
7. TT device restarts and boots through to the firmware start screen as expected
8. TT device registers with OS and chrome sees it in `chrome://device-log/`
9. nothing is logged in the chrome dev console
10. the process hangs indefinitely until the user ignores the instructions in front of him/her
11. unplugging and replugging TT device does not help. the https://suite.trezor.io/web/ page must be reloaded to continue. doing this makes the user go back through all the setup screens modulo the firmware installation portion.

**Expected result:**
The device should be recognized, or the user prompted to find the device again so that the process can continue on to the "Installation completed" screen (as happens when running the trezord bridge).

**Actual result:**
Process hangs at the screen referenced above and the user wonders what is going on.

**Note(s):**
I'm guessing it's a WebUSB problem caused by the device switching between the bootloader and regular mode and needs to be re-found by the user.

**Comment by mcudev** [comment]
I tried this with the other web wallet and it shows the button to let the user pick the device again. That's what I had guessed. So, this is a solved problem and just needs to be implemented again for suite in this part of the process.

This is what the current wallet does after installing the firmware:
![image](https://user-images.githubusercontent.com/29890609/112737094-3d05f400-8f2e-11eb-9cb7-96a2b2957f45.png)

**Comment by jerechinsky** [comment]
I'm having some trouble replicating. @trezor/qa could you please try?

**Comment by slowbackspace** [comment]
> I'm having some trouble replicating. @trezor/qa could you please try?

Just to be sure try to remove all devices listed in `chrome://settings/content/usbDevices`.

edit: I am able to reproduce this. I believe @mcudev is correct. When going through initial setup in Onboarding with a device without a firmware the device is in bootloader-like mode out of the box. Device in bootloader mode acts rather as a separate physical device. This device is paired with the browser before the fw installation process. After the installation is completed the device is restarted in "normal" mode. To the browser it now looks like completely separate device which was not paired before thus we need to give the user an option to trigger pairing process (AKA we need to show "Find device" button).

```
(device restarted, now running in normal mode)
USBUser[14:32:57] USB device added: vendor=4617 "SatoshiLabs", product=21441 "TREZOR", serial="68D7B392517C7762D01AF23B", guid=a67b3a03-9fb5-4b62-b641-51320e0ff0f5

(fw installation is restarting the device)
USBUser[14:32:50] USB device removed: guid=afccf346-61d5-4277-8ab1-ccf58efe7835

(connecting wiped device for the first time)
USBUser[14:31:10] USB device added: vendor=4617 "SatoshiLabs", product=21440 "TREZOR", serial="000000000000000000000000", guid=afccf346-61d5-4277-8ab1-ccf58efe7835
```

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.4.1 (3ed454e4e81b72482a9ad780c5cce9846cb29fb1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.5 regular
