### ISSUE TITLE
trezor-translations-manager is using now deprecated Crowdin API

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3583]
> Please consider that API 2.0 is now the preferred version to be used. The old API will remain fully functional until the end of 2021.

😢 

things to consider:
- do we still need TTM? some functionality can be replaced by formatjs cli which also has some level of integration with crowdin (probably for converting messages to correct format). 
- Crowdin now has official JS client, if v2 api requires significant overhaul maybe using it will be more effective https://github.com/crowdin/crowdin-api-client-js
- I do remember we are using CSV format for some weird reason - some feature was not available in json format, only in csv but I am not sure what it was. Investigate if we really can't switch to JSON and drop all the conversion stuff.
- dropping id field from a message object and relying on key instead

**Comment by tsusanka** [comment]
We will use the crowdin library directly.
