### ISSUE TITLE
Allow loading accounts past first unused index

### ISSUE THREAD

**Issue by MysticRyuujin** [trezor/trezor-suite#3588]
**Is your feature request related to a problem? Please describe.**
I have Ethereum accounts, that are in use, at index 0, 1, 5, 6 (BIP44 standard)

The software will not let me load or import accounts past index 1 because index 2 is unused/has no balance. Stopping at the first unused index for a scan is "fine" but not being able to manually scan more accounts is a problem.

**Describe the solution you'd like**
Either increase the scan depth for used addresses or let us force scan or force add additional indexes.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
