### ISSUE TITLE
Exchange - Receiving address tooltip wording 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3589]
**Describe the bug**
Tool-tip in Exchange  tab Says ` Verify this address on your Trezor.` even when coin is not supported in Suite or you are using account that isn't in Suite.

**Steps to reproduce:**
1. Proceed with Exchange steps 
2. Hover over ? in `Receiving address` dialogue.

**Info:**
 - Suite version: web 21.4.0 (0353a27e328dec1e3b8745847e0e81a001afaa75)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/113126261-bf850100-9217-11eb-8012-eba04a506f3f.png)

**Comment by bosomt** [comment]
same "issue" with `Receiving account` tooltip. 
It says within even when you choose custom address.


![image](https://user-images.githubusercontent.com/31506317/113132848-47bad480-921f-11eb-92ce-f0da39146061.png)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.6.0 (5cf184412289711766c25ed43c3f6f8fce448968)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.4 regular

**Comment by sorooris** [comment]
**QA OK**
 Receiving account tooltip | Receiving address tooltip
 -|-
 ![image](https://user-images.githubusercontent.com/10185314/121215979-c61b9e80-c880-11eb-9538-05482f9760d3.png) | ![image](https://user-images.githubusercontent.com/10185314/121218067-b3a26480-c882-11eb-8a61-8488b18d2da9.png)

Checked ADA, LTC and BTC.

Suite: 21.6.1 4f358fd1
Browser: Chromium 91.0.4472.77
OS: NixOS 21.05
Device: model 1 1.10.1
