### ISSUE TITLE
Onboarding - Select-wallet-type modal not displayed after completing onboarding (and turning passphrase on)

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3592]
**Describe the bug**
The _Select wallet type_ modal is not displayed after completing onboarding in which passphrase is turned  automatically on; compared to the flow when an already set up device is connected after which the modal is displayed and Standard or Hidden wallet selection is offered. I would expect that the modal is displayed every time if passphrase is ON.

**Info:**
 - Remembered Wallet: no
 - Suite Version: web 21.3.2 6dbeaf3
 - Browser: Chromium 89.0.4389.82
 - OS: NixOS 20.09
 - Bridge: standalone 2.0.28
 - Firmware Version: any (tested model One 1.9.4 [ffa96205](https://github.com/trezor/trezor-firmware/commit/ffa96205)

**Steps to reproduce:**
Prerequisite: wiped/reset device.
1. Launch Suite,
2. Complete onboarding flow,
3. Observe.

**Expected result:**
Wallet type selection is displayed before being redirected to the Dashboard.

**Actual result:**
Redirected to a Dashboard of a _Standard wallet_.

**Screenshots:**
After onboarding flow:
![Peek 2021-03-30 16-21](https://user-images.githubusercontent.com/10185314/113138301-ea765180-9225-11eb-9863-06eb1d1e3882.gif)
Device setup:
![Peek 2021-03-31 13-41](https://user-images.githubusercontent.com/10185314/113139653-b0a64a80-9227-11eb-8a6f-ad4183c65dab.gif)

**Comment by jerechinsky** [comment]
@matejzak it seems like common sense to have the _Select wallet type_ modal displayed after user finishes onboarding, but I'd appreciate your input first. Is this something that's accounted for in the new onboarding? If so, should we still implement it here?

**Comment by glacierbits** [comment]
Heads up to @slowbackspace who is working on the new #3332

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.5.1 (974429bab27c43502251b646a485d792a4ab4180)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1584x990
 - Device: model T 2.3.6 regular

**Comment by sorooris** [comment]
**QA OK**

Suite: app 21.5.1 (4d09d884)
OS: macoS Big Sur 11.3
Device: T1 1.9.4 public
