### ISSUE TITLE
New account navigation nitpicks

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3607]
**Describe the bug**

There are some problems with new Account navigation design. Please see video/screenshots

 - 1 - When leaving account navigation to Settings it takes some time to replace `< back` button to General/Device/Coins tabs
 - 2 - After you send transaction navigation won't reappear and you will only see `< back ` is it possible to change this behavior ?
 - 3 - Account Detail header is doubled / Card title + Navigation tab name/ 

**Info:**
 - Suite version: web 21.4.1 (3ed454e4e81b72482a9ad780c5cce9846cb29fb1)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.4 regular

**Screenshots:** 
 - 1

https://user-images.githubusercontent.com/31506317/113839719-39753700-9790-11eb-9e83-0ff34283eafc.mp4

 - 2

![image](https://user-images.githubusercontent.com/31506317/113839700-35e1b000-9790-11eb-8cf8-dce050865012.png)

 - 3 

![image](https://user-images.githubusercontent.com/31506317/113842389-ea7cd100-9792-11eb-806a-10c8494bbb86.png)

**Comment by slowbackspace** [comment]
> 2 - After you send transaction navigation won't reappear and you will only see < back is it possible to change this behavior ?

As a lazy programmer I would say it is valid behaviour, from user pov I am too not sure if I would expect I'll be redirected back to overview. Certainly something that should product consider tho.

I'll add one more thing. We've somehow lost active state for tabs in Settings.

And little nitpick I noticed, there should be horizontal padding around bottom border under active tab (so the border is longer), just like we have in production right now, it looks slightly better.

Nitpick 2: Panel with overview/account details slightly changes its height when there is only "back" button.

production:
<img width="410" alt="Screenshot 2021-04-07 at 12 16 42" src="https://user-images.githubusercontent.com/6961901/113850793-1f8d2180-979b-11eb-8f02-7416485fdfd3.png">

develop Settings with missing active state:
<img width="576" alt="Screenshot 2021-04-07 at 12 15 30" src="https://user-images.githubusercontent.com/6961901/113850649-fa001800-979a-11eb-8c24-9d899988b7d7.png">

short border thingy from develop
<img width="366" alt="Screenshot 2021-04-07 at 12 28 30" src="https://user-images.githubusercontent.com/6961901/113852347-c45c2e80-979c-11eb-8aa4-099f00dd4400.png">

**Comment by sorooris** [comment]
Related to #3348.

**Comment by tomexx** [comment]
Thx, I'm on it

**Comment by bosomt** [comment]
4x **QA OK**


**Info:**
 - Suite version: desktop 21.4.1 (95311f198fba5d2c452cd5d9ce3ede0a50a06a2d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular
