### ISSUE TITLE
Trezor Bridge bundled with Suite should be prioritized over standalone Trezor Bridge

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#3608]
**Describe the bug**
If you have your standalone Bridge running when you start Trezor Suite, it will not start the bundled Bridge in Suite. Then if you kill the standalone Bridge in console/task manager, Suite obviously can't connect to the device, which is as expected. But when you try to refresh the Suite (ctrl+R) it won't start the bundled Bridge and just asks you to download and install the standalone one.

**Info:**
 - Remembered Wallet: -
 - Suite Version: app, 21.4.1 3ed454e4e81b72482a9ad780c5cce9846cb29fb1
 - Browser: -
 - OS: Win10
 - Bridge: 2.0.27
 - Firmware Version: 2.3.5

**Steps to reproduce:**
1. Download and install standalone Trezor Bridge
2. Start Trezor Bridge
3. Start Trezor Suite
4. Kill Trezor Bridge (trezord.exe) in task manager
5. Try to refresh Trezor Suite (ctrl+R)

**Expected result:**
Trezor Suite should always start up with the Trezor Bridge that is bundled with the app, to avoid old/obsolete Bridge versions that could be running standalone.

**Actual result:**
Trezor Suite is using the standalone Trezor Bridge, if it's already running, and asks to download Trezor Bridge after killing Trezor Bridge in the Task Manager.

**Comment by prusnak** [comment]
Currently, the suggested solution is not possible for two reasons:
a) both bundled and external bridges start the server on port 21325 - you can't have two programs running on the same port
b) even if we used a diffent port for bundled and configured suite to use that - you would have a problem that the external bridge might capture the device and the bundled bridge will not see it - that's not something you want

> But when you try to refresh the Suite (ctrl+R) it won't start the bundled Bridge and just asks you to download and install the standalone one.

Suite should never ask you to download and install the standalone one and rather launch a bundled one - I'd focus on fixing that issue.

**Comment by tsusanka** [comment]
To summarize: if desktop app sees the Bridge is not running it should start it itself as it does normally at the beggining.

**Comment by MiroslavProchazka** [comment]
@STew790 is this still valid please? :)

**Comment by Hannsek** [comment]
Probably not, this should be handled with the new NodeBridge well. @mroz22

**Comment by STew790** [comment]
It is still valid, when I have standalone bridge running it is "prioritized" which means that some users that still had the old 2.0.27 Bridge from before installed and running might run into some unnecessary problems because the newer bridge bundled in Suite is not being used.
Nonetheless, as @Hannsek pointed out, this might be sorted out by that but I don't know.

**Comment by mroz22** [comment]
similar to #13180

**Comment by mroz22** [comment]
This can't really be solved as long as there are applications that are using the old bridge. If you don't mind, I will close this. It should be discussed at some later point as part of complete old bridge deprecation task.
