### ISSUE TITLE
Exchange crypto: switching of fees level does not update max amount value

### ISSUE THREAD

**Issue by martinboehm** [trezor/trezor-suite#3610]
**Info:**
 - Suite Version: develop 69a0e7351c5b213f028da53bc129878fd6e8ba9a

**Steps to reproduce:**
1. choose a BTC account with some balance, go to Trade/Exchange
2. select "All"
3. observe the amount of crypto in the input field (equal to account balance minus fees)
4. change the fee level (from normal to economy, for example)

**Expected result:**
As the fees are recalculated, amount changes to the new value of account balance minus fees

**Actual result:**
The amount stays the same. The amount changes only if custom level is selected and custom value is changed.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.5.0 (818d77a2c77268e2e3dac1194c374d6cd831b40d)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.5 regular

**Comment by bosomt** [comment]
**QA OK**



**Info:**
 - Suite version: desktop 21.4.1 (95311f198fba5d2c452cd5d9ce3ede0a50a06a2d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular
