### ISSUE TITLE
Account navigation - Sticky account header stops and disappears at the wrong element

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3614]
**Describe the bug**
When scrolling on the Accounts screen upwards the sticky account header disappears further up above the position of the AppNavigation element.

**Info:**
- Suite: 21.4.1 3ed454e
- OS: macOS Big Sur 11.2.3
- Device: model One 1.9.4 ffa96205f

**Steps to reproduce:**
1. Navigate to the Accounts screen of any coin,
2. Scroll down below the graph,
3. Scroll back upwards.

**Expected result:**
AccountNavigationSticky stops below the AppNavigation element.

**Actual result:**
AccountNavigationSticky stops further up below the NavigationBar element.

**Screenshots:**
Screencap:

https://user-images.githubusercontent.com/10185314/114042362-a6b6c400-9885-11eb-8c9d-9a20c4acdf4c.mov

Stops here:
![image](https://user-images.githubusercontent.com/10185314/114041701-0c568080-9885-11eb-924c-9f294bbf924d.png)
Instead of here:
![image](https://user-images.githubusercontent.com/10185314/114041730-124c6180-9885-11eb-8516-b686ea9a1b56.png)

**Comment by tomexx** [comment]
@sorooris The idea was not to have the action buttons duplicated in the view. But I can change that. What do you think @matejzak ?

**Comment by glacierbits** [comment]
I agree @tomexx, I believe the implementation is correct. ✅

**Comment by tsusanka** [comment]
So @matejzak this works as you have designed it?

**Comment by glacierbits** [comment]
Yes.

**Comment by tsusanka** [comment]
Works as expected then. Closing.
