### ISSUE TITLE
Make e2e tests work on arm

### ISSUE THREAD

**Issue by goodhoko** [trezor/trezor-suite#3616]
Currently the e2e setup doesn't work out of the box on arm machines (eg. M1 macs). Fix this to make it easy for anyone with arm machine to run e2e tests locally.

This will require several steps some of which need to be done in other repositories. (trezor-user-env, trezord-go, ...). This issue serves as a place to track all these steps leading to seamless e2e tests on M1 macs.

Assigning myself to work on this gradually over time.

**Comment by goodhoko** [comment]
The tests really heavily on the [trezor-user-env](https://github.com/trezor/trezor-user-env) docker image which must be adapted for arm in the first place. (running the x86 version fails due to https://github.com/NixOS/nix/issues/4485 or rather https://github.com/docker/for-mac/issues/5204). 

That, in turn, will require arm64 binaries of the emulator and the bridge and arm64 version of the [nix image](https://hub.docker.com/r/nixos/nix/tags). For that last there's already [an issue](https://github.com/NixOS/docker/issues/28).

A good guide on maiking multi-arch docker images seems to be [this one](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/).

**Comment by tsusanka** [comment]
That's a bummer :(. I know @prusnak is using Nix natively without Docker so trezor-user-env _might_ work natively on M1. But we would have to alter the e2e tests then not to use trezor-user-env in docker but directly. There is some work needed and since it is just a hypothesis and I am not sure it is worth it :(.

**Comment by goodhoko** [comment]
This will have to wait for someone else.

**Comment by hynek-jina** [comment]
@vdovhanych is this still valid?

**Comment by vdovhanych** [comment]
@hynek-jina This is still being worked on but should be resolved for the most part. So i would leave it until we're finished in trezor-user-env

**Comment by komret** [comment]
@ondracja Are you able to run the Cypress tests on an M1? If so, could you please update https://github.com/trezor/trezor-suite/blob/develop/docs/tests/e2e-suite-web.md or write down the difference from the current instructions in this thread? We could then close this issue.

**Comment by ondracja** [comment]
@komret Yes, I'm able to run cypress directly (I use docker only for `trezor-user-env`). I'll update the README for E2E tests in a near future and then close this issue.

**Comment by ondracja** [comment]
Since the README update is now merged, I'm closing this issue.

**Comment by bosomt** [comment]
**QA OK** :)
