### ISSUE TITLE
Trezor Suite AppImage does not work on NixOS

### ISSUE THREAD

**Issue by cryptomar1o** [trezor/trezor-suite#3619]
**Describe the bug**
AppImage version of Trezor Suite (Trezor-Suite-21.4.1-linux-x86_64.AppImage and Trezor-Suite-21.4.1-linux-arm64.AppImage) does not work on NixOS.

`[nix-shell:/home/jirka/Documents/Wallets/suite]$ appimage-run "Trezor-Suite-21.4.1-linux-x86_64.AppImage"
/home/jirka//.cache/appimage-run/13ca679e80026a2e3e8b6803976238a74178d8389264cf87d701952295ae611f//squashfs-root/trezor-suite: error while loading shared libraries: libxshmfence.so.1: cannot open shared object file: No such file or directory
`

**Info:**
 - Suite: 21.4.1 [3ed454e](https://github.com/trezor/trezor-suite/commit/3ed454e4e81b72482a9ad780c5cce9846cb29fb1)
 - OS: NixOS 20.09.3765.d6f63659a70 (Nightingale)

**Comment by 573** [comment]
See https://discourse.nixos.org/t/add-package-to-appimage-run-without-write-a-new-derivation/11888/2

**Comment by prusnak** [comment]
This should be working with NixOS 21.05, since this commit added `xorg.libxshmfence` to appimage environment: https://github.com/NixOS/nixpkgs/commit/dd9f4e8517a4993ed00178a2963b51fc7d80225a

If it is not working, please reopen the issue.
