### ISSUE TITLE
Empty passphrase not recognized when entered via device

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3620]
**Describe the bug**
Empty passphrase not recognized when entered via device, you are asked to re-enter passphrase /when empty/ + wallet is added as hidden wallet. This looks really strange when you just initialized your new device and you entered empty passphrase on your model T device. 

When you try to add `Standard wallet` again via computer you are informed that wallet is already loaded and previously added "hidden" wallet is removed and reloaded as `Standard wallet`

**Steps to reproduce:**
1. Connect device with fresh seed
2. Select enter on device in `Select wallet type` modal
3. press enter via device
4. Empty passphrase is not recognized and you are asked to `Confirm empty Hidden wallet ` 

**Info:**
 - Suite version: desktop 21.4.1 (95311f198fba5d2c452cd5d9ce3ede0a50a06a2d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.3.5 regular

**Expected result:**
Empty passphrase is recognized when entered via device.

**Actual result:**
Empty passphrase is not recognized when entered via device 

**Screenshots:**

https://user-images.githubusercontent.com/31506317/114368636-e0394900-9b7d-11eb-891a-70f12d63eb84.mp4

**Comment by szymonlesisz** [comment]
this works properly imho.
suite/host doesn't know what you put ON device (this is a security feature not a bug), could be empty, could be "a". 
from suite point of view it's a `hidden wallet` all the time UNTIL you decide to use `standard wallet` :)
