### ISSUE TITLE
Encountered Invalid prevhash

### ISSUE THREAD

**Issue by somebodyLi** [trezor/trezor-suite#3623]
**Describe the bug**
when I use trezor one to signing my BTC transaction, I got  the error message `Encountered Invalid prevhash` ? what's it means ?? 
**Firmware version and revision**
1.9.5
**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: [Trezor Suite]
 - OS: [macOS]
 
**To Reproduce**
hard to reproduce

**Comment by prusnak** [comment]
I think this is rather an issue within the Suite, not within the Firmware - that's why we are moving this issue to trezor-suite repository.

**Comment by jerechinsky** [comment]
@liyanhrxy could you please send me the public key (xPUB) of the account in question? Please do not share it here but send it to alexandr.jerechinsky@satoshilabs.com
