### ISSUE TITLE
Enable `noImplicitReturns` TypeScript option in Suite package

### ISSUE THREAD

**Issue by goodhoko** [trezor/trezor-suite#3630]
Stemmed from [this thread](https://github.com/trezor/trezor-suite/pull/3590#discussion_r612241102).

Enabling this option could help us catch some bugs and generaly make our code more deterministic.

In the Suite package `noImplicitReturns` is curently violated on some 65 places that would have to be altered.

Marking this as `Good first issue` as it shouhd be mostly mechanical code juggling.

cc @szymonlesisz @keraf

**Comment by goodhoko** [comment]
This will have to wait for someone else.

**Comment by matejkriz** [comment]
we agreed not to do it: https://github.com/trezor/trezor-suite/pull/4921#issuecomment-1036041676
