### ISSUE TITLE
Autoupdate - not able to trigger  manually after skip

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3631]
**Describe the bug**

There is no way to update to new version via Suite after you skip update when offered.
Application is checking for new version indefinitely even log says that it skipped new version. 
This status is permanent and Reset app storage won't change it. 

**Steps to reproduce:**
1. Press `Skip` when asked to update application
2. Restart application
3. Go to `Settings / General` and try to trigger update manually

**Info:**
 - Suite version: desktop 21.3.2 (6dbeaf3dd28a11c5e4bc5867686f58d2920a14bd)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.3.2 Chrome/87.0.4280.141 Electron/11.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.3.5 regular

**Expected result:**
You are able to update application manually 

**Actual result:**
Application is checking for new version indefinitely even log says that it skipped new version. 

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/114529554-5acf9a80-9c4a-11eb-9b27-2d06a5732882.png)

2021-04-13T08:43:53.077Z - INFO(auto-updater): Skip version (21.4.1) request

![image](https://user-images.githubusercontent.com/31506317/114529412-35429100-9c4a-11eb-95a0-289d9291df5c.png)

https://youtu.be/d6C5rWnPxV0

**Comment by bosomt** [comment]
Same behavior in MacOS Big Sur when testing 21.4.0 > 21.4.1 update

**Comment by tsusanka** [comment]
@bosomt as I am looking at the video: do I understand it correctly that after clicking Skip it works ok (even in Settings) _until_ you close the app and start it again? And after the restart it is fucked up.

**Comment by bosomt** [comment]
@tsusanka yes, exactly, it works till you restart application , when you start it again app will evaluate  it as skip current update

**Comment by keraf** [comment]
Looking into this issue now. I have a clue of what could cause this. Full log would be helpful to debug this issue (cc @trezor/qa)

**Comment by bosomt** [comment]
Full log delivered, sorry that I forgot to attach it, i was planning to
