### ISSUE TITLE
unify Link components 

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3633]
currently there are 4 different approaches in the code regarding usage of external links:

[@trezor/components/Link](https://github.com/trezor/trezor-suite/blob/develop/packages/components/src/components/typography/Link/index.tsx) - high level component used for external links it's covering cases like `noreferrer noopener` or `stopPropagation`

[TrezorLink](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/components/suite/TrezorLink/index.tsx) - for handling TOR links, depends on `@trezor/components/Link`

[ExternalLink](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/components/suite/ExternalLink/index.tsx) - `TrezorLink` with 2 predefined props

- [X] `styled.a` - (11 occurrences) not covering anything

- [ ] it would be nice to reduce it to 2 (?)

**Comment by waltonzt** [comment]
@szymonlesisz I can give this a go. What were you thinking about which ones to remove? I was thinking to remove the use of `styled.a` and `ExternalLink`. Replace them with `TrezorLink` with `EXTERNAL_LINK` icon when needed.

**Comment by tomasklim** [comment]
#4595 targeted `styled.a - (11 occurrences) not covering anything`

To be done:
`it would be nice to reduce it to 2 (?)`

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.1.0 (95a1a9e112a94666fe6bd787d4b8eed0f54547cf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.1.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
