### ISSUE TITLE
Receive address marked as Unsupported address format even when valid

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3635]
**Describe the bug**
One of our customers has receive address marked as Unsupported address format and convert to lowercase is offered.
Of course Segwit address is case sensitive and after conversion it will get `Address is not valid`

**Steps to reproduce:**
1. In BTC send dialogue use valid 37VJHKeBA9DHKmTwYE7TWYjwDzo5JTb1sz address
2. observe

**Info:**
 - Suite version: desktop 21.4.1 (1baa8ced16f2f6a5d60e9f4d7911669f856123d8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.3.5 regular

**Screenshots:**
https://btc1.trezor.io/address/37VJHKeBA9DHKmTwYE7TWYjwDzo5JTb1sz

![image](https://user-images.githubusercontent.com/31506317/114693882-507cd180-9d1a-11eb-94a4-cec73c4a59c5.png)

![image](https://user-images.githubusercontent.com/31506317/114693916-583c7600-9d1a-11eb-8097-f492b906d5b4.png)

**Comment by prusnak** [comment]
I just tested 21.3.2 and it has the same issue, so this is not a regression. However, this definitively needs fixing as this is a bug in address validation.

**Comment by szymonlesisz** [comment]
should be fixed here:
https://suite.corp.sldev.cz/suite-web/fix/3635/web/

**Comment by bosomt** [comment]
**QA OK**



**Info:**
 - Suite version: desktop 21.5.0 (130b17ff0d52b67079d29b4e7250637528be1def)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.5.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular
