### ISSUE TITLE
OS Windows version in download menu should be 10 not 8+

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#3636]
**Describe the bug**
When you want to download Trezor Suite and you open the drop-down menu to select your OS, the version for Windows is 8+ but the support for Windows is actually 10 (and higher). https://wiki.trezor.io/Operating_systems

**Info:**
 - Remembered Wallet: -
 - Suite Version: app/web, 21.4.1 c1daedd 
 - Browser: Chromium 87.0.4280.66
 - OS: -
 - Bridge: -
 - Firmware Version: -

**Steps to reproduce:**
1. Go to https://suite.trezor.io/
2. Click on the drop-down menu to select OS
3. You can see Windows 8+ there

**Expected result:**
Only Windows 10 and higher should be in the menu.

**Actual result:**
Windows 8 and higher is in the menu.

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/114699086-1f070480-9d20-11eb-9151-ce2059732949.png)

**Comment by jerechinsky** [comment]
I changed it to "for Windows 10" in copy
