### ISSUE TITLE
Desktop: Setup testing framework for Electron app

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#3640]
There are currently no tests covering the desktop app specifically. For example, features like bridge, tor or auto-updater are currently untested.

We should create tests covering specific features of Suite Desktop. [Spectron](https://www.electronjs.org/spectron) could be used for this.

**Comment by matejkriz** [comment]
done here https://github.com/trezor/trezor-suite/tree/develop/packages/integration-tests/projects/suite-desktop
