### ISSUE TITLE
All settings gone after upgrade from 21.3.1

### ISSUE THREAD

**Issue by Dehumanizer77** [trezor/trezor-suite#3643]
**Describe the bug**
I have upgraded from 21.3.1 through autoupgrade and all settings I have previously set are gone after I have closed the application and opened again.

**Steps to reproduce:**
1. Open Suite 21.3.1
2. Upgrade when asked for autoupgrade
3. Allow the application to restart
4. The app will retain settings until fully closed
5. Open the app again
6. It opens without any settings, i.e. initial wizzard starts as if the Suite was never run before. 

**Info:**
 - Suite version: desktop 21.4.1 (1baa8ced16f2f6a5d60e9f4d7911669f856123d8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1843x1152
 - Device: model T 2.3.2 regular

**Expected result:**
Settings retained as set in the old version.

**Actual result:**
Suite starts without any settings set, with the fresh install wizzard.

**Note(s):**
Not sure if it can be related, but I had a link on the desktop for the old version and I was using it to start it. After the upgrade the link of course didn't work because the app filename changes during the upgrade, so I have then run it directly from the folder where I have the AppImage file saved.

**Comment by Dehumanizer77** [comment]
I have a friend who didn't upgrade so far so I'll ask him to run the old suite directly to see if he'll lose settings or not. Will report here when I'll get the info from him.

**Comment by Dehumanizer77** [comment]
Ok it seems I am the only one with the problem so far, it might be some database inconsistency on my computer.

**Comment by KernelTruth** [comment]
Lucky you. I accepted an auto-update and Trezor Suite does not start at all. Need to debug it now. Not a happy bunny here.
Ubuntu 18.04 .appimage in /opt/

**Comment by prusnak** [comment]
@Photolunatic which version were you updating from?

**Comment by KernelTruth** [comment]
> @prusnak which version were you updating from?

From **21.3.1**

**Comment by KernelTruth** [comment]
I had a perfectly fine, working app. I was prompted to update and everything went downhill from there.
The update never went through. Older AppImage stopped working and has been unregistered from the system (no app in the system menu). I had to copy manually the new AppImage. Now I am trying to thinker about how to create a .desktop file to integrate this to the system menu as AppImageLauncher does not work with this file.
I have found two folders: pending (Is it safe to delete it?) and @trezor. How to clean this mess?
Thanks.
![2021-04-16_19:22:23](https://user-images.githubusercontent.com/76048167/115067651-21688a80-9ee9-11eb-8e60-79604d3bd0bd.png)


Also, I have the same issue as OP. 
**The suite starts without any settings set, with the fresh install wizard.**

**Comment by slowbackspace** [comment]
> I had a perfectly fine, working app. I was prompted to update and everything went downhill from there.
> The update never went through. Older AppImage stopped working and has been unregistered from the system (no app in the system menu). I had to copy manually the new AppImage. Now I am trying to thinker about how to create a .desktop file to integrate this to the system menu as AppImageLauncher does not work with this file.
> I have found two folders: pending (Is it safe to delete it?) and @trezor. How to clean this mess?
> Thanks.
> ![2021-04-16_19:22:23](https://user-images.githubusercontent.com/76048167/115067651-21688a80-9ee9-11eb-8e60-79604d3bd0bd.png)
> 
> Also, I have the same issue as OP.
> **The suite starts without any settings set, with the fresh install wizard.**

If you had problem with auto updater itself then losing stored settings could be just a side-effect. Could you please create a new issue? It will get more attention :)

You can delete both folders `@trezor` (storing caches, remembered wallets, settings, configs, etc) and `@trezor-suite-desktop-updater`, then proceed just like you would in case of "installing" Suite for the first time. The app should create necessary directories again.

@trezor/qa I assume such update scenario is already tested, but could you try to update from 21.3.1 few more times?

**Comment by bosomt** [comment]
gone thru update twice:

1) downloaded 21.3.1
2) saved wallet
3) updated to 21.4.1 /21.3.1 appimage was auto removed from file system as exprect/
4) settings and wallet are present

please see log and video 

https://user-images.githubusercontent.com/31506317/115549007-69502e80-a2a8-11eb-907c-fc17ec8175c6.mp4
[trezor-suite-log-1619005571634.txt](https://github.com/trezor/trezor-suite/files/6350530/trezor-suite-log-1619005571634.txt)

**Comment by bosomt** [comment]
@Dehumanizer77 maybe we can close this issue ?

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.7.1 (24cc565a3badd85ab48b30348022471dfd85f90e)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.2 regular
