### ISSUE TITLE
Unable to label one of 2 wallets when 2 devices are connected

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#3644]
**Describe the bug**
You can't label (rename) wallets on one device when 2 devices are connected. Video included.

**Info:**
 - Remembered Wallet: -
 - Suite Version: app/web 21.4.1 (1baa8ce)
 - Browser: Chrome, Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
 - OS: Windows 10
 - Bridge: 2.0.27
 - Firmware Version: TT, 2.3.5 

**Steps to reproduce:**
1. Start Trezor Suite app or web version, doesn't matter.
2. Connect 2 devices (in my case 2 Trezor Model T)
3. Enable labeling on both of those devices
4. Click on your devices
5. Try to change the name of both standard wallets
6. When you click on either of them, it will always try to rename only one

**Expected result:**
You should be able to rename both standard wallets on both of your devices.

**Actual result:**
You can't rename your wallets on one of your connected devices.

**Screenshots:**

https://user-images.githubusercontent.com/48477147/114744512-10374680-9d4e-11eb-8614-431a59beab3e.mp4

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.6.2 (97d032adf84e5b7c5dd82fb3085fdeb4434ad7f8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular
