### ISSUE TITLE
Groestlcoin - GRS support 

### ISSUE THREAD

**Issue by groestloli** [trezor/trezor-suite#3645]
I am still missing Groestlcoin in my Trezor Suite can you please include the coin as well. Trezor firmware support already exists, the developers of GRS would also do the work and submit a PR. If you say it's okay?

**Comment by tsusanka** [comment]
Unfortunately, we do not have the capacity to review such PR, apologies. Our current product goal is to add support for the most used cryptocurrenciy projects. I am sure as time progress GRS will get there but it is not the case as of this moment. Thank you for your understanding.
