### ISSUE TITLE
Bullet points are not rendered in update changelog

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3648]
**Describe the bug**
Bullet points are not rendered in the update changelog on Windows (not sure about other platforms).

**Info:**
 - Remembered Wallet: no
 - Suite Version: 21.3.2
 - Browser: -
 - OS: Windows 10
 - Bridge: -
 - Firmware Version: -

**Steps to reproduce:**
1. Launch older version

**Expected result:**
- Bullet points
- such 
- as this
- are displayed

**Actual result:**
They are not.

**Screenshots:**
![image](https://user-images.githubusercontent.com/1835345/114831936-37cdf380-9dce-11eb-8aa2-56982e2f647d.png)

**Comment by marekrjpolak** [comment]
I unfortunately cannot properly test desktop (let alone Windows) version on NixOS. But the bullet points were explicitly turned off, so it should be fixed now.

**Comment by jerechinsky** [comment]
Thank you @marekrjpolak. Let's leave this one for QA to test out on different OS's.

**Comment by STew790** [comment]
Hi, should this be tested with the --pre-release tag? I tried to update from 21.4.1 and it doesn't show me the bullet points.

**Comment by tsusanka** [comment]
@STew790 we will most likely need to test this from this version to some future one. So let's prepare this during freeze? It is a bit easier so we do not do it twice.
