### ISSUE TITLE
WebUSB not detecting Trezor in Chrome

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3651]
**Describe the bug**

WebUSB API in Chrome is not detecting Trezor.

**Steps to reproduce:**
1. Stop Trezor Bridge
2. Connect device
3. Start web version of Suite in Chrome and try to connect to device

**Info:**
 - Suite version: web 21.4.1 (1baa8ced16f2f6a5d60e9f4d7911669f856123d8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.5 regular

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/114855647-7a9bc580-9de6-11eb-9cfd-ebe7382ffeb0.png)

**Comment by prusnak** [comment]
Same for Chromium under Linux

**Comment by sorooris** [comment]
Confirming issue on Linux.

![image](https://user-images.githubusercontent.com/10185314/114857001-0d892f80-9de8-11eb-9190-a8465ccf74dd.png)

Suite: web 21.4.1 1baa8ce
Browser: Chromium 89.0.4389.82
OS: Nixos 20.09
Device: 1.9.4

**Comment by bosomt** [comment]
same results in wallet.trezor.io

**Info:**

 - Browser: Version 89.0.4389.114 (Official Build) snap (64-bit)
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.4.0 regular

![image](https://user-images.githubusercontent.com/31506317/114858757-2d215780-9dea-11eb-806d-1e8527ff4d5c.png)

**Comment by prusnak** [comment]
Fixed via https://github.com/trezor/connect/pull/796

Deployed to production

**Comment by bosomt** [comment]
**QA OK**

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.4.1 (1baa8ced16f2f6a5d60e9f4d7911669f856123d8)
 - Suite version: web 21.5.0 (130b17ff0d52b67079d29b4e7250637528be1def)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular
