### ISSUE TITLE
Trezor Suite no longer launching after in-app update

### ISSUE THREAD

**Issue by fredddd1** [trezor/trezor-suite#3652]
**Describe the bug**
Software no longer opens after updating via in-app updater.

**Info:**
 - Remembered Wallet: unable to verify
 - Suite Version: 21.4.1
 - Browser: irrelevant
 - OS: Windows x64 20H2
 - Bridge: irrelevant
 - Firmware Version: irrelevant

**Steps to reproduce:**
1. Update via in-app updater
2. Try to open Trezor Suite

**Expected result:**
For Trezor Suite to open.

**Actual result:**
It does not open.

**Comment by fredddd1** [comment]
Can this ticket please be removed after it has been resolved?

**Comment by keraf** [comment]
Hi @fredddd1,

To help investigate the issue, I would need some logs. May I ask you to run the application with the parameters `--log-level=debug --log-write`? The file should be output in your user directory. Please make sure to go over the information inside this log and redact any information you do not wish to share (name in paths, PC hardware, etc...).

![suite-log-win](https://user-images.githubusercontent.com/30026749/114866592-0ec05980-9df4-11eb-9f01-8a90eec4962f.jpg)

**Comment by fredddd1** [comment]
No issue apparently. I was trying to launch TREZOR Bridge.

No idea why TREZOR Bridge creates an icon in the start menu when it pretty much does nothing.

Would it be possible to permanently delete this ticket, not just close it?
