### ISSUE TITLE
Desktop: Clear storage should also clear desktop settings

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#3654]
Currently, clearing the storage does not clear the desktop settings. Desktop settings should be part of this clear action as it might help with issues.

**Comment by tsusanka** [comment]
@alex-jerechinsky this is a prerequisite for the public release.

**Comment by goodhoko** [comment]
Done in https://github.com/trezor/trezor-suite/pull/3699

Closing.

**Comment by bosomt** [comment]
@keraf @tsusanka 
how do we treat Local Labelling storage ? You can choose local storage as storage of labels in Suite app.

**Comment by goodhoko** [comment]
@bosomt Great point! this PR does not delete labels. It only clears something called a _desktop storage_ which currently includes:
- tor settings
- window dimensions
- skipped suite versions (to not offer them to a user multiple times)

This raises a product question: _should the `Reset App` buton also clear the labels?_

I think it should not. Two of the three label-storage providers are cloud-based hence I'd expect them not to be erased by resetting the app. Doing that for the third provider (file system) would be confusing. We definitely should *disconnect* the app from the locally storred labels and that already happens.

**Comment by bosomt** [comment]
**QA OK**

tor settings and window dimensions deleted, im not able to check skipped suite version now.
labels from local storage were not deleted
worked as expected 

**Info:**
 - Suite version: desktop 21.6.0 (9d8cea584b1f655f0964d80f863b02b1523e2cad)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.8.3 regular

**Comment by STew790** [comment]
QA OK

Works as expected, desktop settings were deleted after clearing the storage.

Info:

Suite version: desktop 21.6.0 (9d8cea5)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
OS: Windows 10
Screen: 1920x1080
Device: model T 2.3.6 regular
