### ISSUE TITLE
ETH internal transactions

### ISSUE THREAD

**Issue by IvaFingerova** [trezor/trezor-suite#3658]
**Is your feature request related to a problem? Please describe.**
A customer bought some ETH via Suite. the transaction was successful. however, it seems it's an internal tx after all. since Suite doesn't recognize these, the only option here is to use a third-party app to access these assets. anyways, seems to me, it's kinda confusing; when people buy some assets via Suite, they should be able to manage these by using Suite as well, right?
tx ID https://etherscan.io/address/0x86334f9d2ada0efb4720a87f269183e167d56c1f#internaltx 
Internal transactions, despite the name, are not actual transactions. When two smart contracts "interact,'' the product or consequence of this interaction is a transaction. However, that transaction does not exist on the ETH blockchain. They are value transfers that were initiated by executing a smart contract (smart contract Ether or token transfer). They are like a byproduct of smart contract functionality (see the source: https://support.bitpay.com/hc/en-us/articles/360050782511-What-are-Eth-Internal-Transactions-).
The reason why you cannot see this transaction in Trezor Wallet/Trezor Suite is the backend that is used. Trezor Ethereum Blockbook at https://eth1.trezor.io/ does not know internal transactions, therefore it is not possible to show them. We are considering adding it in the future, but I cannot give you any ETA when it could be. (edited) 

**Describe the solution you'd like**
Blockbook needs to be updated which means Martin B. will have to spend rather lot of time on this change

**Describe alternatives you've considered**
Probably no other way to sort it out...

**Additional context**
These buys happened through our partner BTCDirect - they have several liquidity providers and unknown/unalterable logic behind which one processes which transaction. Their argument is to keep ETH fees as low as possible but here we can see the fee is far from low
https://eth1.trezor.io/tx/0xb140bf5ee13092300278e9f32de0f46838b711ca364407f9eca63b35efdc9d44

**Comment by slowbackspace** [comment]
Community is interested in this as well, as it sometimes pops out as bug report.

Eg. https://github.com/trezor/trezor-suite/issues/3057

**Comment by armine28** [comment]
Did send ETH from Coinbase to my ETH address but Trezor Suite(Version 22.8.2 (22.8.2.20470)) does not show the internal transaction and also not the ETHs but the transaction lists as successful. I would highly appreciate if this feature could be implemented soon.

**Comment by scott-42** [comment]
Still a problem in 22.11.1 with no transactions showing. All the other sites are able to parse the Internal Transactions and this has been open for over a year. Please put this back to High priority or at least explain why it is not.

**Comment by Hannsek** [comment]
We are currently working on implementing this feature.

**Comment by tomasklim** [comment]
done by #7805

**Comment by bosomt** [comment]
**QA OK**
