### ISSUE TITLE
Ethereum bump fee discrepancy

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3659]
**Describe the bug**
See attached screenshots, bump ETH transaction and bump ETH ERC20 transaction have discrepancy /data vs fee/

**Steps to reproduce:**
1. Send ETH and ERC20 transactions
2. Try to bump ETH transaction
3. Try to bump ETH ERC20 transaction and compare

**Info:**
 - Suite version: web 21.4.1 (1baa8ced16f2f6a5d60e9f4d7911669f856123d8)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.4.0 regular

**Screenshots:**

![image (2)](https://user-images.githubusercontent.com/31506317/115215329-b0e98580-a103-11eb-8796-d15e55253ff4.png)
![image (1)](https://user-images.githubusercontent.com/31506317/115215332-b21ab280-a103-11eb-8648-07023b970d15.png)

**Comment by jerechinsky** [comment]
@matejzak please suggest how "fee", "data" and "total" should be shown

**Comment by jerechinsky** [comment]
Szymon cleared it up for me. "Data" should not be shown.

**Comment by bosomt** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/31506317/116360703-7ae18b00-a800-11eb-9311-49803a553ed0.png)

**Info:**
 - Suite version: web 21.5.0 (fd3ceda56fe84a3daad5bab69c3bd07ad2fed753)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model One 1.10.0 regular
