### ISSUE TITLE
Move link to (this) monorepo

### ISSUE THREAD

**Issue by goodhoko** [trezor/trezor-suite#3663]
The first step towards [paying technical debt in `trezor-link`](https://github.com/trezor/trezor-suite/issues/2923).

To ease development of Suite app we're moving its depenedncies that are developed in-house to this monorepo. One of them is [`trezor-link`](https://github.com/trezor/trezor-link/).

The move comprises several steps and decisions. @tsusanka @keraf please check this out and raise your foice for or against:
- The git history must be preserved. (Easily achieved with `git subtree`.)
- *Open* issues must be brought over. (There are 5 of them.) I wouldn't bother with the closed issues.
- There are 6 stale branches. I wouldn't bother with these.
- There's [one open PR](https://github.com/trezor/trezor-link/pull/27). It contains some unit tests that might be handy when *we* start writting tests. I'd probably close that PRfor  now. We can cherry pick some of its commits later when needed.
- This is a good opportunity to give `trezor-link` a new and better name. @keraf mentioned `transport` could be a good one. Personally, I wouldn't do that. AFAIK "link" doesn't cause any confusion and such a rename should have some good motivation behind it. Less (change) is more in this case, I think.
- The old repository should be [archived](https://github.blog/2017-11-08-archiving-repositories/). Also its description and readme should stress that it's no longer used and point to the new home of Link (this repo).
- The [NPM package](https://www.npmjs.com/package/trezor-link/v/0.1.0) should point to the new repository (and homepage) I believe this infromation is pulled out of `package.json` so it's just a matter of changing that in the source.

**Comment by prusnak** [comment]
> * The git history must be preserved. (Easily achieved with `git subtree`.)

Feel free to ask @matejcik in case you have any questions wrt this. He's the mastermind behind the move to monorepo for trezor-firmware and the author of this script: [create_monorepo.py](https://raw.githubusercontent.com/trezor/trezor-firmware/master/create_monorepo.py)

That said, I expect that importing a single repo should be indeed quite easy with `git subtree`.

> * _Open_ issues must be brought over. (There are 5 of them.) I wouldn't bother with the closed issues.

Just ping me once this needs to be done and I'll transfer the issues.

> * The old repository should be [archived](https://github.blog/2017-11-08-archiving-repositories/). Also its description and readme should stress that it's no longer used and point to the new home of Link (this repo).

Again, just ping me.

> * The [NPM package](https://www.npmjs.com/package/trezor-link/v/0.1.0) should point to the new repository (and homepage) I believe this infromation is pulled out of `package.json` so it's just a matter of changing that in the source.

I think we should create a new NPM package `@trezor/link` with end goal to move all packages under the `@trezor` namespace/organization on NPM.

**Comment by tsusanka** [comment]
> Open issues must be brought over. (There are 5 of them.) I wouldn't bother with the closed issues.

Definitely not closed ones. Open ones yes or we can simply do them one at a time until they are gone :). No preference from my side.

> There are 6 stale branches. I wouldn't bother with these.

Agreed. They will be pretty old anyway.

> There's one open PR. It contains some unit tests that might be handy when we start writting tests. I'd probably close that PRfor now. We can cherry pick some of its commits later when needed.

I agree.

> This is a good opportunity to give trezor-link a new and better name. @keraf mentioned transport could be a good one. Personally, I wouldn't do that. AFAIK "link" doesn't cause any confusion and such a rename should have some good motivation behind it. Less (change) is more in this case, I think.

I have a small preference to rename ti to `transport` because link seems to me as some "href" component. But leaving the decision to you and @keraf.

> The old repository should be archived. Also its description and readme should stress that it's no longer used and point to the new home of Link (this repo).

Yup.

> The NPM package should point to the new repository (and homepage) I believe this infromation is pulled out of package.json so it's just a matter of changing that in the source.

Yup.

**Comment by tsusanka** [comment]
@szymonlesisz is it okay to move trezor-link to monorepo **before** moving Connect to monorepo?

**Comment by goodhoko** [comment]
@prusnak 

> Feel free to ask @matejcik in case you have any questions wrt this. He's the mastermind behind the move to monorepo for trezor-firmware and the author of this script: create_monorepo.py

Thanks! That script was helpful - reassured me that `git subtree` is a good choice here.

> That said, I expect that importing a single repo should be indeed quite easy with git subtree.

Yup. Importantly what we're doing here is a one-time action. No further syncing of the two repos will happen. If it would, [other](https://git-scm.com/book/en/v2/Git-Tools-Submodules) [alternatives](https://github.com/ingydotnet/git-subrepo) to `subtree` could be considered.

> I think we should create a new NPM package @trezor/link with end goal to move all packages under the @trezor namespace/organization on NPM.

Allright, moving Link NPM package into `@trezor` namespace is definitely a good move. However, I think it's orthogonal to this issue which is concerned about the git repos. IE I'd like to move to monorepo first and only then start addressing everything else. Would it be ok for you if we deferred this to a separate issue? I'd add it as a step [here](https://github.com/trezor/trezor-suite/issues/2923).

---

@tsusanka 

> I have a small preference to rename ti to transport because link seems to me as some "href" component. But leaving the decision to you and @keraf.

Ok. I guess that @keraf now holds the power of the decisive vote. .)

**Comment by keraf** [comment]
I'd say transport too.

**Comment by goodhoko** [comment]
Ok, we'll rename `link` to  `transport` meaning we can also move the package under `@trezor` NPM namespace whena at it. .)

This issue is good to go. I'll post a PR soon.

**Comment by goodhoko** [comment]
As explained [here](https://github.com/trezor/trezor-suite/pull/3917#issuecomment-869552644) this gets postponed until more work is done on the refactoring of Link itself. Marking as blocked.

**Comment by goodhoko** [comment]
This will have to wait for someone else.

**Comment by STew790** [comment]
**QA OK**
We already tested and discussed this with @mroz22 extensively.

**Comment by tsusanka** [comment]
@mroz22 closing?

**Comment by mroz22** [comment]
probably yes. lets hope for the best prepare for the worst.
