### ISSUE TITLE
Install udev rules via AppImage automatically (Linux)

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#3664]
It should be possible to install udev rules by fiddling with the `AppRun` script. 

We could first check whether the udev rules are installed and offer installing them if not. Something among this lines:

``` bash
if [ \! -f /etc/udev/rules.d/51-trezor.rules ] ; then
  pkexec cp -a $SUITE_RESOURCES/51-trezor.rules /etc/udev/rules.d/51-trezor.rules
fi
```

and only run Electron after this code has run.

**Comment by goodhoko** [comment]
Will get to this this afternoon (~3pm). I hope that's ok.

**Comment by goodhoko** [comment]
I started looking into this and found out that
1. electron-builder (the tool we use to package Suite) [won't let us](https://github.com/electron-userland/electron-builder/issues/3436) tinker with the AppRun script directly. We'll need to do this from within the app itself in either the post-install script or on first run.
2. Writing to `/etc/udev/...` (or equivalent) requires root priveleges. I'm not sure (didn't try, don't have linux) but currently Suite doesn't require elevation for installation. I'd say it would be a good UX to inform the user why we need to elevate before invoking a system dialog.
3. Our udev rules are subject to [evolution](https://github.com/trezor/trezor-common/commits/master/udev/51-trezor.rules). We shouldn't only check that rules are present but also that they're up to date.

 I agreed with @keraf he'll take over this issue as he works on Linux while I'd have spend quite some time on setting it up. I'll take over some other Raf's issue to square this off. .)

**Comment by prusnak** [comment]
> 2. Writing to `/etc/udev/...` (or equivalent) requires root priveleges.

`pkexec` takes care of showing the dialog - https://www.freedesktop.org/software/polkit/docs/latest/pkexec.1.html

> 3. Our udev rules are subject to evolution.

Last time we changed them was in 2019 and we don't plan to change them any time soon :-)

We might consider adding the check, but only as an extra effort

**Comment by goodhoko** [comment]
> We might consider adding the check, but only as an extra effort

Agree. We can add this check (and updating logic) once the udev rules change. In other words when we'll release the next Trezor. .)

**Comment by sorooris** [comment]
Tested in the branch separately, will be tested during freeze again.

**Comment by sorooris** [comment]
**QA OK**

Installation went smoothly and cancellation was handled correctly. :tada: 

Cancellation toast notification copy (from #4183) was also improved. :muscle: 
![image](https://user-images.githubusercontent.com/10185314/131522403-31c3242a-4aca-4679-b36f-0923fb61ea77.png)


Suite: app 21.9.0 b5a686a
OS: Linux Mint 20.02 (Cinnamon 5.0.5)
Device: model T 2.4.2
