### ISSUE TITLE
Option to disable hw acceleration

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3666]
Sometimes users experience various visual glitches in electron apps due to some problem in hw acceleration.
It is a common practise to provide an option to disable it as a workaround for users which are affected by such a problem. 
![image](https://user-images.githubusercontent.com/6961901/115353948-66c2db80-a1b9-11eb-9d1e-ff00c8a4699d.png)

At least on macos we could provide this option in main app menu (I am not sure if there is any menu in linux env):
![image](https://user-images.githubusercontent.com/6961901/115354055-835f1380-a1b9-11eb-910b-ba6ded468845.png)

Then cmd line arg could be also handy, spotify uses `--disable-gpu`.

**Comment by tsusanka** [comment]
@stepmes have you seen this in the feedback?

**Comment by stepmes** [comment]
@tsusanka I haven't seen it yet, but I'll note it down. Thanks, @slowbackspace for pointing it out.
