### ISSUE TITLE
Labeling - Disabling of labeling also disconnects storage provider

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3669]
**Describe the bug**
Suite doesn't remember `cloud storage provider` connection/selection after you re-enable labeling.

**Steps to reproduce:**
1. Enable labeling
2. Connect to cloud storage provider
3. Disable labeling
4. Enable labeling
5. You are asked to select and connect to cloud storage provider again 

**Info:**
 - Suite version: desktop 21.4.1 (1baa8ced16f2f6a5d60e9f4d7911669f856123d8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.4.0 regular

**Expected result:**
Suite should remember `cloud storage provider` connection/selection after you re-enable labeling.

**Actual result:**
Suite doesn't remember `cloud storage provider` connection/selection after you re-enable labeling.

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/115458666-4f6e0780-a226-11eb-9c43-2f9c1a56ddba.png)

![image](https://user-images.githubusercontent.com/31506317/115459064-e3d86a00-a226-11eb-88ac-8ed5a4a92e22.png)

![image](https://user-images.githubusercontent.com/31506317/115459822-c657d000-a227-11eb-99cc-7c4980116e45.png)

**Comment by slowbackspace** [comment]
How else would you change the provider? Or Am I missing something?

**Comment by jerechinsky** [comment]
@matejzak do you agree that Suite should remember the cloud storage provider upon disabling labeling and only "forget" it once user clicks "Disconnect"?

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.7.0 (89aee5512ea0059de309935684b5be5fb3b1843b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.10.1 regular

+


**Info:**
 - Suite version: desktop 21.7.0 (b0ea8be015a610b83246d99a57761105259ea84f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular

**Comment by wendys-cats** [comment]
**QA OK**

Disabling labeling no longer disconnects storage provider.

Info:
**Suite** app version 21.7.0 c6316619a13802197a5a58c0fc1f39aae18db1a7
**OS** Windows 10 Version 10.0.19042.1052
**Device** TT 2.4.0 regular
