### ISSUE TITLE
Remove disconnect instruction for bootloader >1.10.0

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3675]
The newest bootloader 1.10.0 (included in newest FW 1.10.0 which will go out on May 12th) is capable of so-called soft-reset. That means it can reset itself from bootloader to firmware and no replug is needed. Since we instruct the user to disconnect the device manually in Suite it would be nice to remove such instruction.

The question is whether we want to wait it out for the new onboarding and do it there or fix it in the old one.

Video: https://drive.google.com/file/d/1HvPJNhG0SfiJdh9xr4ia2d6noauzhUnW/view?usp=sharing
https://app.asana.com/0/1200234324703677/1200238518144797

cc @slowbackspace

**Comment by tsusanka** [comment]
I have this screen in mind:

![image](https://user-images.githubusercontent.com/1835345/115868962-810ceb80-a43d-11eb-8e49-7632f1291841.png)

**Comment by slowbackspace** [comment]
Certainly great feature, but right now I am not even sure if we will use it in may's new onboarding, certainly not worth fiddling with old one again. I mean the old one becomes obsolete in May anyway 😁  Also as this feature uses new protobuf message I assume that first we need to implement it in connect and release it. The onboarding is built with the absence of this feature in mind, it's not really so straightforward as to remove one UI screen and we didn't even tested if the old intermediary fw, which Martin's implemented in old onboarding, works yet 💦

**Comment by glacierbits** [comment]
Yes, let's definitely not worry about the old onboarding at all. Do you need help with the Connect changes or are you going to take care of it yourself @slowbackspace?

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 21.6.1 (4f358fd151fc1962f30f84a855b82213d958aae7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.10.0 regular

**Comment by STew790** [comment]
QA OK

Info:
 - Suite version: desktop 21.6.1 (4f358fd151fc1962f30f84a855b82213d958aae7)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model One 1.10.0 regular
