### ISSUE TITLE
"Suite version" under Settings is stuck on "Checking"

### ISSUE THREAD

**Issue by LCBradley3k** [trezor/trezor-suite#3679]
I'm trying to upgrade to the latest version from the desktop application, but it is stuck on "Checking...". I had once been asked by a pop-up to update but I had clicked to postpone it. Ever since postponing the popup - I haven't received another either.

![image](https://user-images.githubusercontent.com/9059449/116345241-9adf6300-a79c-11eb-868a-b9934f757bbd.png)

**Comment by keraf** [comment]
This bug has been fixed in a newer version. You have to manually update by getting the latest version from here: https://suite.trezor.io/
