### ISSUE TITLE
Some events are not correctly tracked to analytics

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3691]
### Bugs
The current version of analytics is 1.7, but the 1.6 version is being tracked. :white_check_mark:

**suite-ready**

- missing suite version :white_check_mark:
- missing session and instance id :white_check_mark:

**device-update-firmware**

- fromFwVersion, fromBlVersion has comma separator, but toFwVersion has dot separator :white_check_mark:

**menu/goto/exchange-index**

- event not used :white_check_mark:

**transaction-created**

- event not sent

**analytics/dispose**

- event not sent :white_check_mark:

**settings/device/goto/background**

- not activated for custom image

**menu/toggle-tor**

- never sent, if tor is enabled, it tries to send info by non-tor link and vice versa

**menu/goto/settings-index**

- activated by manage tor button

**Comment by tomasklim** [comment]
### **In 1.8 version:**
**Added:** 
- settings/device/update-auto-lock
  - value: string
- suite-ready
  - browserName: string
  - browserVersion: string
  - osName: string
  - osVersion: string
  - windowWidth: number
  - windowHeight: number

**Fixed:**
- suite-ready
  - suiteVersion
  - c_instance_id
  - c_session_id
- device-update-firmware
  - fromFwVersion (changed separator to dots from commas)
  - fromBlVersion (changed separator to dots from commas)
- analytics/dispose

**Removed:**
 - menu/goto/exchange-index
 
 More information can be found in [`Notion page`](https://www.notion.so/satoshilabs/Analytics-overview-3b49d66235e044928b79954d3a4ac8ff)

**Comment by bosomt** [comment]
@tomasklim is there any kind of action needed on our side or i can move it to approved section ?

**Comment by tomasklim** [comment]
@alex-jerechinsky should this be tested by QA now? or we will prepare some testing analytics guide when 1.9 version is done?

**Comment by wendys-cats** [comment]
@alex-jerechinsky should we test it?

**Comment by jerechinsky** [comment]
@wendys-cats Sorry, no. Not during this freeze. We're currently aware of several bugs and major flaws with analytics and we're working towards fixing those. In the meantime I'm working on creating documentation and testing scenarios so you can help us later. Thank you.

**Comment by wendys-cats** [comment]
@alex-jerechinsky thank you for responding, will inform the rest.

**Comment by sorooris** [comment]
@alex-jerechinsky should we move this to the next release then?

**Comment by jerechinsky** [comment]
@sorooris No. We have #3717 for next release. :)
