### ISSUE TITLE
Implement WAITING_FOR_USER Buy status

### ISSUE THREAD

**Issue by LukasRada** [trezor/trezor-suite#3692]
**Describe the solution you'd like**
Add new buy trade state WAITING_FOR_USER.

We need to implement new status WAITING_FOR_USER, which says that a user should do an action with cooperation with  partner (SimpleCoin in this case). The action is typically KYC info, new rate confirmation. etc.

Flow:
REQUESTING->SUBMITTED->APPROVAL_PENDING->**WAITING_FOR_USER**->APPROVAL_PENDING->SUCCESS

![image](https://user-images.githubusercontent.com/7394177/116851896-99c29180-abf3-11eb-81d5-057c280cef2d.png)

**Comment by bosomt** [comment]
@LukasRada so we can skip this issue till Invity implemnt/enable it on their servers ?

**Comment by LukasRada** [comment]
@bosomt Yep.

**Comment by sorooris** [comment]
@martinboehm Hi Martin, could we please link this issue with an issue or pull request from Invity's side so we can either test it, end to end, when it's finally implemented, or close this? The reason being I'm hesitant to approve this issue without having actually tested it, there's no apparent blocker and I'd like to move it to next sprint. DIKI

**Comment by martinboehm** [comment]
@sorooris Hi. Thank you for keeping an eye on it. 
It is already enabled in our server. 
However, it will be hard to test it artificially as it is part of the flow at the partner's (SimpleCoin) side. The status is only set in very specific (yet not known to us in detail) cases when SimpleCoin needs some additional KYC information. 
I would suggest to close it. If there are some issues with the functionality, we will get to know it via the support channel.
