### ISSUE TITLE
Remote secure messaging system follow-up

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3693]
Following the initial work in [#2752](https://github.com/trezor/trezor-suite/issues/2752), some additional improvements can be done:

- [x] #4350
<img width="949" alt="Screenshot 2021-09-17 at 11 00 32" src="https://user-images.githubusercontent.com/33235762/133756054-b472febe-f140-4afa-8f31-b08fb0e67c26.png">

- [x] #4355
- [x] #4351
- [x] #4352
- [x] #4379
- [ ] <s>always on-top banner config attribute (when modal open) </s>
- [ ] <s>smooth banner animation</s>
- [x] #4354
- [ ] #4353
- [x] reduce amount of `@message-system/save-valid-messages` actions fired
- [x] when feat/tschuss-next gets merged, resolve duplicated public key in next.config.js
- [x] update forgotten storage changelog
- [x] update message-system readme
  - [x] info about production build
  - [x] priorities
  - [x] impossible combinations
- [x] unify language settings with guide
- [x] do not rely on device.features.model, use device.features.major_version

**Comment by tsusanka** [comment]
Moved to separate issues.
