### ISSUE TITLE
Remote secure messaging system CI job

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3694]
To be able to use message system in production mode, it is required to:
- [x] set public + private production keys in GitLab 🔥  (public key has to be done before final release, otherwise develop key will be bundled in this version)
- [x] install `aws` in GitLab and set its credentials
- [x] uncomment `aws` command in `ci/packages/suite-data.yml`

**Comment by prusnak** [comment]
For reference: `JWS_PRIVATE_KEY` / `JWS_PUBLIC_KEY` keys need to be generated via the following:

```
openssl ecparam -name secp256k1 -genkey -out privateKey.pem
openssl ec -in privateKey.pem -pubout -out publicKey.pem
```

I still need to figure out the AWS creds in the CI.

**Comment by prusnak** [comment]
I'd need to have this PR merged in order to set the CI correctly: https://github.com/trezor/trezor-suite/pull/3703

**Comment by firepacket** [comment]
You want to use secp256k1 for asymmetric message encryption, and signing verifying I presume?
Is there any research in regards to this curve when it comes to encrypted messages spaced over time? Has this been deployed as a solution in any other public cases? Any research pointing to possible strengths and weaknesses of this?

**Comment by prusnak** [comment]
> You want to use secp256k1 for asymmetric message encryption, and signing verifying I presume?

There is no encryption, just signing/verification.

**Comment by firepacket** [comment]
Oh I apologize. Is there something else providing confidentiality of a message? Didn't see anything about it. Maybe I am confusing this with another feature I read about regarding end to end secure messaging?

**Comment by prusnak** [comment]
> Maybe I am confusing this with another feature I read about regarding end to end secure messaging?

Yes you are. This is just for messaging settings.

**Comment by tsusanka** [comment]
We'll test ourselves, when the time to release another config comes!
