### ISSUE TITLE
Suggestion: Add 'Line Chart' option for Dashboard - Portfolio 

### ISSUE THREAD

**Issue by MarMun** [trezor/trezor-suite#3698]
**Is your feature request related to a problem? Please describe.**
'Dashboard - Portfolio' section: I like to see the development of my portfolio over time. The current bar chart does not offer this.

**Describe the solution you'd like**
My suggestion would be to have 'chart type' toggle button to toggle between 'line' and 'bar' charts

**Describe alternatives you've considered**
Also helpful: Show gain / loss percentage for each item in 'Dashboard - Assets' section. 

**Additional context**
I imagine it like this:

![LineChart](https://user-images.githubusercontent.com/5682504/116869850-c38ab100-ac11-11eb-9e47-a0768720cf2d.jpg)

**Comment by glacierbits** [comment]
Will be introduced in #3725
