### ISSUE TITLE
Can't set custom Tor address

### ISSUE THREAD

**Issue by goodhoko** [trezor/trezor-suite#3709]
**Describe the bug**
In the Suite's general settings when I set a custom tor address it doesn't get persisted (returns to the default after navigatin away and back.)

I've been hunting this bug today. Seems like it hides somewhere in ther IPC layer between the renderer and the main process which handles changing the address.

Assigning myself. Hopefully will post a fix soon.

cc @alex-jerechinsky @keraf

**Comment by goodhoko** [comment]
@trezor/qa I'd really like to link you to a specification of how this should behave but I couldn't find any existing one. The tor feature spec is partially described in these issues
- https://github.com/trezor/trezor-suite/issues/2445
- https://github.com/trezor/trezor-suite/issues/2843
- and maybe some more

However I can't say if these are on par with what was actually implemented.

---

What I did here was that I tried to read the intended behaviour between lines of the existing code. I believe the feature should work like this:

User can simply enable tor from the navigation bar or settings. This should spin-up a tor process bundled within suite and just work. The bunled tor starts on the address which is used as placeholder in the tor address input in settings. The setting should persist over app restarts.

In addition to that user can set a custom address of the tor. If they do, we don't start the bundled tor but expect the user to run the tor themselves. If they don't suite won't work - it will not be able to fetch info from blockbook or internet generally. There's not special error handling for this case informing user the tor server isn't avilable. Instead an error of type "all backends unavailable" will occur. I guess we considered this feauture too niche to bother.

The custom address should also persist over app restarts. Note that merely setting custom tor address isn't enough to enable tor. For tha the 'enable tor' toggle must be *on* too.

Lastly when user clears the tor address input in setting it should fallback to the default (the same as the placeholder).

@keraf, did I get that right?

**Comment by bosomt** [comment]
**QA OK**

- changed port of Tor server, enabled Tor, connection failed as expected
- changed port of Tor server and re-enabled Tor, suite connected to Tor server as expected


**Info:**
 - Suite version: desktop 21.6.0 (9d8cea584b1f655f0964d80f863b02b1523e2cad)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.8.3 regular

**Comment by STew790** [comment]
**QA OK**

changed port of Tor server, enabled Tor, connection failed as expected
changed port of Tor server and re-enabled Tor, suite connected to Tor server as expected

**Info:**

Suite version: desktop 21.6.0 (9d8cea5)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
OS: Windows 10
Screen: 1920x1080
Device: model T 2.3.6 regular
