### ISSUE TITLE
Navigation: Settings menu

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3712]
**Design:** [Zeplin](https://zpl.io/be3E1Mq) 

- The menu is accessible from the top navigation bar 
- Click on the particular item opens the respective Settings tab
- Hover populates `All` › link lead to General Settings 

**Other:** 

- Please add the hover to the other icons - Notification, Tor, Discreet - as well

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.6.1 (7d50da6b9fe39ddd934fdf6153b4c4afb2d7fd88)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0 + MacOS app
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.10.0 regular

**Comment by STew790** [comment]
QA OK

Info:
 - Suite version: desktop 21.6.1 (4f358fd151fc1962f30f84a855b82213d958aae7)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.0 regular
