### ISSUE TITLE
Onboarding: More todos

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3716]
- [x]  Add a background pattern: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/60340959122e10b2d3800dd8)
<img width="923" alt="Screen Shot 2021-05-07 at 17 35 18" src="https://user-images.githubusercontent.com/29627086/117473774-98c69280-af5a-11eb-98b1-ad36d60ee79d.png"> 

- [x] Remove the description strings
<img width="1163" alt="Screen Shot 2021-05-07 at 17 47 06" src="https://user-images.githubusercontent.com/29627086/117475411-49816180-af5c-11eb-9e51-91a7a06d2087.png"> 

- [x] Older-looking input with shadows
<img width="1047" alt="Screen Shot 2021-05-07 at 18 04 54" src="https://user-images.githubusercontent.com/29627086/117477887-cf9ea780-af5e-11eb-9a6e-9d6a3677a238.png">

- [x] Wipe device › Can we send the user to the Suite startup page + tell user to reconnect instead of this modal? 
<img width="1781" alt="Screen Shot 2021-05-07 at 18 34 18" src="https://user-images.githubusercontent.com/29627086/117481266-0971ad00-af63-11eb-889b-6eade4af910a.png">

**Comment by slowbackspace** [comment]
do we need another issue? https://github.com/trezor/trezor-suite/issues/3707

**Comment by tomasklim** [comment]
@hynek-jina is it still relevant?

**Comment by hynek-jina** [comment]
@tomasklim Everything seems to be implemented.. I have tested the last bullet point (so far unchecked)
