### ISSUE TITLE
Support T1's Go to bootloader feature

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3718]
Now that we have https://github.com/trezor/trezor-firmware/issues/1047 we have the ability to go to bootloader on T1 using [Protobuf message](https://github.com/trezor/trezor-firmware/blob/master/common/protob/messages-management.proto#L414). For any new firmware updates from 1.10.1 Suite should use this feature. Users won't have to enter the bootloader on their own then!

**Comment by bosomt** [comment]
I'm not sure if this is final version and expected outcome. Can you change reconnect to restart/reboot ?
This can be confusing for customers. 

Device is asking me to `Confirm that i want to reboot to bootloader`. 
But suite asks me to `Reconnect your Trezor in bootloader mode`

![image](https://user-images.githubusercontent.com/31506317/128032318-abc3c553-57f9-42b4-bee5-6f7aa6c025d5.png)

**Comment by marekrjpolak** [comment]
> I'm not sure if this is final version and expected outcome. Can you change reconnect to restart/reboot ?
> This can be confusing for customers.

You're probably right. I've implemented it without any design proposal, so I've shared most of the elements with the previous manual reboot process. If necessary, I could change the text(s).

**Comment by sorooris** [comment]
**QA NOK**

Although in the strictest sense functionally correct, could we please finalize the design first and then implement so the final product is more user friendly and to prevent reintroduction of minor errors?

1. The ReconnectDevicePrompt__Overlay on top of the firmware update modal obstructs the close button while it's still possible to exit via pressing the Esc key - user should be able to exit the update flow any time, compared to Onboarding.
![image](https://user-images.githubusercontent.com/10185314/128341918-ef1c7d00-aae0-4ef8-b579-5ab1a6eac8b5.png)
2. 
Old design of the prompt | New design, available [here, from onboarding](https://staging-suite.trezor.io/web/static/videos/onboarding/t1_bootloader_light.mp4)
------------ | -------------
![image](https://user-images.githubusercontent.com/10185314/128342301-ba0d4082-9814-416a-8404-0de4932731e7.png) | ![image](https://user-images.githubusercontent.com/10185314/128343750-1b592dd8-dbed-401c-b21f-6cfae1318acd.png)

Suite: web 21.8.1 8dfc3fbf
Browser: Chromium 92.0.4515.107
OS: NixOS 21.05
Device: model One 1.10.1

**Comment by marekrjpolak** [comment]
Ad 1) Agreed, but I've identified exactly the same problem in current web Suite when reconnecting manually, so technically it's a new issue. Nevertheless I'm gonna fix it as soon as I receive some design proposal.

Ad 2) But the new animation shows manual reconnecting of the device, while what we need now (when rebooting automatically) is just to confirm by clicking a button. I haven't found an animation for that.

**Comment by sorooris** [comment]
@marekrjpolak yeah both should've been ready way before.

**Comment by jerechinsky** [comment]
Yes, 1) isn't pretty but it isn't a terrible detriment IMO. Let's move it to a new issue and address it in the next release as it requires a design revamp. 
 
Let's fix 2) now by replacing the animation with the old illustration and changing the copy of the heading to **"Reboot your Trezor into bootloader mode"** @marekrjpolak 

cc @matejzak @tsusanka

**Comment by tsusanka** [comment]
@alex-jerechinsky I agree with your decision.

As mentioned numerous time it is unrealistic to design each and every feature in advance. It is absolutely okay they way @marekrjpolak did it. We simply fix these issue once we find them (either the engineer right away or QA or we gather it from the user feedback..). We can discuss this further IRL.

**Comment by sorooris** [comment]
Well, i disagree, but let's move on.
