### ISSUE TITLE
Window resize causes clearing form values

### ISSUE THREAD

**Issue by LukasRada** [trezor/trezor-suite#3721]
**Describe the bug**
Window resize causes clearing form values.

**Info:**
 - Remembered Wallet: yes
 - Suite Version: web, 21.5.0, c1daedd8227baaac99c1f89e91005739d6e572a4
 - Browser: Firefox 88
 - OS: Ubuntu 20.10 Groovy

**Steps to reproduce:**
1. Open browser with Suite, but not in full screen and with left side menu visible.
2. Go to Accounts -> Send.
3. Input value into any input field.
4. Resize window width so the left side menu is not visible.

**Expected result:**
Values in form should stay filled in after the resize.

**Actual result:**
Values in form disappears.

**Screenshots:**
![Peek 2021-05-06 14-09](https://user-images.githubusercontent.com/7394177/117298240-6db74280-ae77-11eb-853b-1b916c9e3f81.gif)

**Comment by szymonlesisz** [comment]
resize (mobile layout change) causes unmount of send component (and send form hook)
values are not cached since they are not valid (they have errors), try to do the same with valid data (green)

decision has to be made, if we want to cache invalid values like above (not recommended)

**Comment by LukasRada** [comment]
I can confirm the "green case" (valid form values) behaves correctly.
Yet with validation not invoked the behavior stays as described:
![Peek 2021-05-13 11-52](https://user-images.githubusercontent.com/7394177/118110350-98a71680-b3e2-11eb-859d-dce48952ba87.gif)
 
But it's really an edge case IMHO. Decision is up to you guys :)

**Comment by szymonlesisz** [comment]
afaik exchanges doesn't have "cache" logic implemented yet (or im wrong?) this is why it doesnt work there

**Comment by bosomt** [comment]
@LukasRada can you please retest it ? I was not able to reproduce it in send or in exchange tab.
Tested resize multiple times, to smallest size as possible. Changed from mobile to desktop view multiple times.

**Info:**
 - Suite version: desktop 22.8.2 (58f4c5bf0804e02c05c0b85e020b6e452b419164)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.2 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by LukasRada** [comment]
Tested and no signs of the bug. Let's close it, if you wish.
