### ISSUE TITLE
Navigation: Tor

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3723]
**Design:** [Zeplin](https://zpl.io/VDgEd6g) 

The main idea: 

- Move Settings to the right (on both web & desktop) › Notifications › Tor (desktop only) › Discreet
- Security / Privacy Settings and statuses (will include BTC Core in future) on the left side
- For the June release: It's OK if don't manage to implement the new drop down menu in Tor
- Hovers on all icons (related to #3712)

**Comment by STew790** [comment]
Why is there the little "arrow" when the Tor notification pops up?
![image](https://user-images.githubusercontent.com/48477147/120819792-34482480-c554-11eb-9233-83c21152c034.png)

**Comment by bosomt** [comment]
**QA OK**
_design and functionality in progress..._


**Info:**
 - Suite version: desktop 21.6.1 (4f358fd151fc1962f30f84a855b82213d958aae7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.10.0 regular

**Comment by wendys-cats** [comment]
**QA OK**
design in progress

**Info:**

**Suite version**: desktop 21.6.1 4f358fd151fc1962f30f84a855b82213d958aae7
**OS**: Windows 10
**Device**: TT 2.4.0 ea3596a
