### ISSUE TITLE
Add Account: New design

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3724]
Design: [Zeplin](https://zpl.io/a8Q71AK) 
Add Account modal prototype: [Figma prototype](https://www.figma.com/proto/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?page-id=2%3A26281&node-id=90%3A2&viewport=779%2C568%2C0.049047525972127914&scaling=min-zoom) (start by clicking on Plus button, reset by pressing `R` key)

**The objective:** 

- Current design is outdated
- Same visual language of coin management at all touch-points:

- [x]  Onboarding 
- [ ]  Settings 
- [x]  Add Account modal

**Important specifics:** 

- Please do add the label `inc. ERC20 Tokens` and the tooltip on ETH
- Please do add the tooltip on disabled XRP (for **Model 1**  only)
- _Rationale: Both are known sources of confusion for our beloved users_ e.g. #3478,  #3507 

**Don't worry about :** 
- Adding the labeling option now (user can do that retrospectively) › Next release (?) 
- The label `Custom BE set` for now › Touched up Custom BE design in progress

**Comment by bosomt** [comment]
**QA OK**

2of3 that are done are OK

**Info:**
 - Suite version: web 21.8.0 (7f2b12206bca4149b2c30bf3696bf337a064a60e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by hynek-jina** [comment]
@matejzak Is this still open?
If so, what is exactly missing with settings? _I assume that we don't care about labelling in this issue._

**Comment by glacierbits** [comment]
Yes, this can be closed. Coin Settings already got their new design.
