### ISSUE TITLE
Exchange tab stuck in 'loading' state if wallet not connected

### ISSUE THREAD

**Issue by MarMun** [trezor/trezor-suite#3726]
**Describe the bug**
Exchange tab stuck in 'loading' state if wallet is not connected.

**Info:**
 - Remembered Wallet: yes
 - Suite Version: app 21.4.1, https://github.com/trezor/trezor-suite/commit/1baa8ced16f2f6a5d60e9f4d7911669f856123d8
 - Browser: -
 - OS: Ubuntu 20.04.2 LTS, 64bit
 - Bridge: -
 - Firmware Version: model T 

**Steps to reproduce:**
1. disconnect remembered wallet
2. go to an asset account -> "Trade" -> "Exchange"

**Expected result:**
UI should instruct user to connect hardware wallet

**Actual result:**
Exchange tab stuck in 'loading' state.

**Screenshots:**
![TS_EX_Stuck](https://user-images.githubusercontent.com/5682504/117437854-14134e80-af31-11eb-982f-c4c382c41ab0.jpg)

**Comment by martinboehm** [comment]
Duplicity with https://github.com/trezor/trezor-suite/issues/3297, there is already PR with fix.
