### ISSUE TITLE
Access Settings: Trezor disconnected 🔌 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3729]
The option to modify Application and Coin Settings before the keys are shared (device is connected) with the application.

Design in [Figma](https://www.figma.com/file/BUMem1C7j4roQDyJf9yxQT/Exploring-Onboarding?node-id=862%3A536)

----
![image](https://user-images.githubusercontent.com/3729633/146195566-fd7d025f-b52f-404f-a43e-8d41dbedaac4.png)
- Settings icon should be available on all Welcome screen variants in the top-right corner and behave the same as usual (dropdown with links to settings and guide). Guide icon should also be on the Welcome screen at the usual position.

----
![image](https://user-images.githubusercontent.com/3729633/146196032-0dbf3eef-ebef-4b17-a0b1-3a9c0e51ebb0.png)
- The layout of settings in case device is not connected in normal mode is the same as usual but without main Navigation Bar (so there is no way to navigate to Accounts or Dashboard)

- There is a new X button in settings (top right navigation item) that leads to last route before you open the Settings. 

- [nice to have] The `...` button should be removed from settings
  - Support - removed completely (it's in guide)
  - Show log - move to General tab as regular item
  - Debug menu - move to new tab

- If the device is not connected in normal or bootloader mode:
    - Device tab has only new banner and no possible settings
    - General settings has disabled labelling
    - Coins has all coins available (so the behaviour would be equivalent to situation, that you enable XRP with model T connected and then connect model One)

----
![image](https://user-images.githubusercontent.com/3729633/146197659-4751d343-3066-4df3-b4ba-8c57908e89aa.png)
![image](https://user-images.githubusercontent.com/3729633/148249472-a826bcc5-c5b3-4e9b-84f9-77c675c738e0.png)

 - If the device is in bootloader mode:
   - Same as above except the device tab that has different banner and firmware update, wipe device and custom firmware is there
   - This is related to issue https://github.com/trezor/trezor-suite/issues/2542
   
 ----
![image](https://user-images.githubusercontent.com/3729633/146198793-0fbf50fd-a253-4da5-a1c7-0d63e690622d.png)
- On top of that state of the Device tab in settings should be enhanced for the Remembered device
  - new banner added on top
  - cursor on all the options that are disabled should be `cursor: not-allowed` (crossed out circle)
  - there should be an explanation tooltip on disabled toggles
  
  
 - If you went to Settings from Welcome screen and then connect the device, you should stay in Settings just the Navigation bar should appear and so the state of the current settings tab
 - The same if you are in Settings with device and the device is disconnected, you should stay in Settings, but the Navigation bar disappear.

**Comment by matejkriz** [comment]
- [ ] Check if it makes sense to enable Settings in some of the special states of the device too (unacquired, unreadable, unknown, seedless, recovery, bootloader...) But let's leave it on some phase 2.

**Comment by wendys-cats** [comment]
Suggestion
Making Labeling option more visibly disabled in this case (access settings when device is disconnected) might be a good idea, there might be users that will be confused with this, since labeling is unavailable without a device connected.

![image](https://user-images.githubusercontent.com/58593111/148957112-0b72d4ef-6be4-4ea9-91f4-e82111605c9e.png)

**Comment by matejkriz** [comment]
> Suggestion Making Labeling option more visibly disabled in this case (access settings when device is disconnected) might be a good idea, there might be users that will be confused with this, since labeling is unavailable without a device connected.

We already have a design proposal for it, just not implemented yet, but it will be part of the followup issue:
![image](https://user-images.githubusercontent.com/3729633/149135810-48a3ce4a-f1fa-42ef-956d-e62e9a3c098f.png)
