### ISSUE TITLE
Onboarding: Copy improvements w/ Support

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3730]
@alex-jerechinsky Can you please review with Nika this copy? 🙏🏽 

Nika brought to my attention we should emphasize CABLE troubleshooting (proper "click" connection / trying different cable altogether). Bases on the occurrence (#), I am guessing it would make send to put it as a first step. 

<img width="741" alt="Screen Shot 2021-05-07 at 18 38 34" src="https://user-images.githubusercontent.com/29627086/117481562-738a5200-af63-11eb-86a8-4991c508b016.png">

**Comment by jerechinsky** [comment]
I talked to Nika and we decided to do it like this.

![Screenshot 2021-05-31 at 12 15 03](https://user-images.githubusercontent.com/75733878/120180129-b1e5fa80-c20b-11eb-9187-1c4df17bec23.png)

I updated the copy cc @slowbackspace.

**Comment by glacierbits** [comment]
Perfecto. Thanks! 🙏

**Comment by bosomt** [comment]
**QA OK**

@alex-jerechinsky 
maybe we can consider to change link to support like in old onboarding modal ?
Current `Contact support` leads to https://trezor.io/support/
maybe you can change it to https://trezor.io/support/technical/i-cannot-access-the-wallet/ ?

See https://github.com/trezor/trezor-suite/issues/3886



**Info:**
 - Suite version: web 21.7.0 (b0ea8be015a610b83246d99a57761105259ea84f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.10.1 regular

**Comment by STew790** [comment]
**QA OK**

Info:
 - Suite version: desktop 21.7.0 (550942dcbdb7b2ffc17519f8307a47f2d8d060f1)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.0 regular
