### ISSUE TITLE
Discreet mode nitpicks

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3733]
**Describe the bug**
Please see screenshots and adjust discreet mode

1) you can see Inputs in transactions detail
2) smooth out TX ID blur “frame” in transactions detail

**Info:**
 - Suite version: web 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.10.0 regular

**Screenshots:**

<img width="934" alt="Screenshot 2021-05-09 at 9 11 57" src="https://user-images.githubusercontent.com/31506317/117580630-28a24300-b0f9-11eb-9a3d-51e2371714a4.png">

<img width="81" alt="Screen Shot 2021-05-09 at 10 03 29" src="https://user-images.githubusercontent.com/31506317/117580650-42438a80-b0f9-11eb-9f1c-03cd9b35dcbf.png">

**Comment by matejkriz** [comment]
@keraf `disableHiddenPlaceholder` param has been added to Inputs amount in this [commit](https://github.com/trezor/trezor-suite/commit/bcb903a202ef82cc03c90d5f7b92eadd6f614b7a#diff-1dacbf61f9133f49828650c085c9209b016cadef8047d3d98ffcf7d754e95c43R83), do you have any idea why? 

And the addresses should be also blurred, right? Same as on the other places...

**Comment by bosomt** [comment]
one more blurring that's not smoothed 

![image](https://user-images.githubusercontent.com/31506317/118103741-888b3900-b3da-11eb-8ec4-df17ef44c4b5.png)

**Info:**
 - Suite version: desktop 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.5.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model One 1.10.0 regular

**Comment by matejkriz** [comment]
There was one more:
![118731794-70337800-b839-11eb-83c8-c062a283ff6f](https://user-images.githubusercontent.com/3729633/118820123-453b3980-b8b6-11eb-9af9-1cf12f8b6e85.png)

**Comment by bosomt** [comment]
@alex-jerechinsky maybe we can move it to June release ? 
Is there reason why ti went to July release project ? :)

**QA OK**

**Info:**
 - Suite version: web 21.6.0 (a7b30017426099918850f5a883a501fcc78ae230)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.4 regular

**Comment by bosomt** [comment]
New  feature introduced new items that need attention 

See:

<img width="668" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120068916-03ab4b00-c07b-11eb-8156-174e9ca95c11.png">

<img width="185" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120069038-b7143f80-c07b-11eb-8bf3-280d8118e7cf.png">

<img width="941" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120069043-bf6c7a80-c07b-11eb-9183-c8c73f6209fd.png">


**Info:**
 - Suite version: desktop 21.6.0 (b65e29291276cd6a03c2fa8035966139a2847f90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular

**Comment by bosomt** [comment]
**QA OK**

token count is not blurred, im not sure if  this it par tof design or not but everything else looks good.

![image](https://user-images.githubusercontent.com/31506317/121705012-8fd65d00-cad4-11eb-8f3f-3995db02289b.png)

**Info:**
 - Suite version: web 21.7.0 (b6021aea87a5f683069efac15473e8028fd5b869)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.0 regular

**Comment by wendys-cats** [comment]
**QA OK**

Inputs in transactions detail **OK**
smooth out TX ID blur “frame” in transactions detail **OK**
smooth out FIAT in transaction detail **OK**
smooth out token value **OK**

**Info**
**Suite version:** web 21.7.0 b6021aea87a5f683069efac15473e8028fd5b869
**Browser:** Chromium Version 88.0.4324.182 (Official Build) (64-bit)
**OS:** NixOS 21.03 unstable
**Device:** model T 2.4.0 regular
