### ISSUE TITLE
Bundle (newest) firmware in Suite

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3738]
To simplify some Freeze & Release processes it would help us a lot to bundle the actual firmwares inside Suite directly instead of fetching them from data.trezor.io. Currently we need to deploy the firmwares to data.trezor.io before we can actually test Suite with the firmwares which is suboptimal because we 1. make the firmware public 2. `trezorctl` starts offering them in the first moment they are there.

**Comment by sorooris** [comment]
To be tested during September Suite testing cycle, once available.

**Comment by sorooris** [comment]
**QA OK**

Does not apply to web version (obviously); app updates both Trezor models' firmwares correctly. Tested by completing firmware update offline.

Suite: app 21.9.1 b5a686a
OS: macOS Intel 11.5.2 Big Sur (other OS tested in the merged PR #4176)
Device: model T 2.4.0, model One empty
