### ISSUE TITLE
Blinking cursor is present in Firefox

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3745]
**Describe the bug**
You can click on most menu items and you will see cursor present, see videos.
I was able to reproduce it on Fedora linux and MacOS

**Steps to reproduce:**
1. Load web version in Firefox
2. Click on item like Dashboard or Accounts
3. observe

**Info:**
 - Suite version: web 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.6 regular

**Screenshots:**

https://user-images.githubusercontent.com/31506317/117928886-75a23700-b2fc-11eb-87ee-64811ded2fc3.mov

https://user-images.githubusercontent.com/31506317/117928890-763acd80-b2fc-11eb-9bf6-4c07596f3a1b.mov

**Comment by bosomt** [comment]
looks like Firefox issue, i just noticed that it's happening on all sites /slack,clockify and so on/

**Comment by jerechinsky** [comment]
You may have enabled caret browsing - an accessibility feature in firefox. I think you can disable it by "fn + F7" on a Mac.

**Comment by bosomt** [comment]
lol, you are right and it synced to all my computers :)  thanks !
