### ISSUE TITLE
Fetch Zcash transcation enhancements from blockbook 

### ISSUE THREAD

**Issue by goodhoko** [trezor/trezor-suite#3749]
Based on [this comment](https://github.com/trezor/trezor-suite/pull/3736#issuecomment-839584963) fetch the zcash transaction enhancments from blockbook replacing hardcoded values.

>Zcash transactions requires additional data (enhancement), those constants are defined by [zcash network](https://zcash.readthedocs.io/en/latest/rtd_pages/nu_dev_guide.html)
>
>whenever zcach do some fork/upgrade those values are changing and we need to update them. it this given case, after block 1046400 new constants were required to sign valid transaction (otherwise will not be accepted by network)
>
>Those values are now (in production? idk) sent by blockbook backend in `getServerInfo` method so they could be sent via `blockchain-link/connect` and stored in blockchain reducer and used from there without need to hardcoding it.

cc @szymonlesisz @tsusanka

**Comment by szymonlesisz** [comment]
I'm not sure if this is a "first good issue"
It's quite complex change and you need to know what you are doing here.

Steps:
1. modify `getInfo` method in [blockchain-link](https://github.com/trezor/trezor-suite/blob/develop/packages/blockchain-link/src/workers/blockbook/index.ts#L84), write tests, keep in mind that those values are optional
2. publish blockchain-link to npm
3. import blockchain-link in connect
4. publish connect
5. import connect in suite
6. implement received data in suite reducer and use them in sign action

**Comment by goodhoko** [comment]
Right, sorry. That was a mistake. Removed the label. Thanks for outlining the steps though!
