### ISSUE TITLE
warning when verifying binaries

### ISSUE THREAD

**Issue by PostPollux** [trezor/trezor-suite#3751]
**Is your feature request related to a problem? Please describe.**
I'm not an expert when it comes to verifying signatures of applications. I guess that is the case with most of your userbase.
I downloaded trezor suit as appimage from https://suite.trezor.io/
I followed the instructions of https://wiki.trezor.io/Apps:Trezor_Suite#How_to_run  to verify the binaries. It worked.
BUT there are two things that make me wonder if I can trust that result:
1. GPG show the following warning:
```
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```
As I said, I'm no signing expert, so warnings like that make me feel uncomfortable running that software. Maybe this message is normal and there is nothing you can do about it. But in this case, please mention it in the wiki an explain why this message appears and that there is no reason to be concerned. Would make me feel safer.

2. Looks like I downloaded the signing key and signing certificate from the exact same homepage as the binary itself.
I'm not sure, but if someone would tamper with that homepage and would be able to modify files on it for whatever reason, wouldn't it be easy for that person to just replace those two files, too, resulting in a correctly verified signature even if it had been modified? It took me quite a while to realize that the signature files are also hosted in the github releases. This is nice, as that seems to be a separate source.

I might sound paranoid, but having decent amounts of crypto on your trezor really makes you not want to mess up and install some tampered binaries.

**Describe the solution you'd like**
1. More clarity in the wiki concerning the warning as mentioned above
2. Mention somewhere that the signature files are also available in the github releases
3. Maybe even add a whole section to the wiki about why and how to verify binaries. Just as an example, I found this site from Decred related to that topic: https://docs.decred.org/advanced/verifying-binaries/ I think it makes you just feel safer if you know what this is all about and what's the best practices when verifying.

**Comment by adam-hurwitz** [comment]
The same warning message, _This key is not certified with a trusted signature!_, is occurring with the following steps on macOS.

## Steps

1. Download the .dmg file, signature, and signing key from [https://suite.trezor.io/][1].
   - Signature: _Trezor-Suite-21.6.2-mac.dmg.asc_
   - Signing key: _satoshilabs-2021-signing-key.asc_

2. Run the verify command: `gpg --verify Trezor-Suite-21.6.2-mac.dmg.asc`

## Output

> gpg: Signature made Wed Jun 30 12:57:23 2021 CDT
gpg:                using RSA key EB483B26B078A4AA1B6F425EE21B6950A2ECB65C
gpg: Good signature from "SatoshiLabs 2021 Signing Key" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: EB48 3B26 B078 A4AA 1B6F  425E E21B 6950 A2EC B65C

## Attempted Solutions

### 1. Import the signing key before verifying

**Command**
Import the signing key: `gpg --import satoshilabs-2021-signing-key.asc`

**Output**

> gpg: key E21B6950A2ECB65C: 1 signature not checked due to a missing key
gpg: key E21B6950A2ECB65C: "SatoshiLabs 2021 Signing Key" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1


### 2. Sign the key before verifying

**Command**

`gpg --sign-key EB483B26B078A4AA1B6F425EE21B6950A2ECB65C`

**Output**

> pub  rsa4096/E21B6950A2ECB65C
     created: 2021-01-04  expires: never       usage: SC
     trust: unknown       validity: unknown
[ unknown] (1). SatoshiLabs 2021 Signing Key
>
> gpg: no default secret key: No secret key
> 
> Key not changed so no update needed.

## Configuration

- Trezor Suite: 21.6.2
- OS: macOS BigSur 11.4

[1]: https://suite.trezor.io/

**Comment by adam-hurwitz** [comment]
@PostPollux, It may help this issue to receive more attention from the Trezor team by adding the warning message in the title, i.e., **Warning Verifying Signature - This key is not certified with a trusted signature!**

Also, it seems the label **Bug** should be applied.

**Comment by adam-hurwitz** [comment]
[According to matejcik](https://forum.trezor.io/t/signature-verification-issues-in-trezor-suite/308/5?), who seems to be a part of the Trezor engineering team, this warning can be ignored.

> A better option is to ignore the warning.
>
> What the warning is saying is that the signature is OK, but we have no way of knowing where this key came from.
>
> If you are sure that you have the right key, you can silence the warning by signing the key yourself (basically saying “yes, I know this is the right key”)
gpg --sign-key EB483B26B078A4AA1B6F425EE21B6950A2ECB65C

However, the concern with downloading both the Trezor Suite application *Trezor-Suite-21.6.2-mac.dmg* and the signing key, *satoshilabs-2021-signing-key.asc*, is that both are downloaded from the same source, https://suite.trezor.io. 

It seems that the best practice would be to download the signing key from a separate official Trezor site/source. Theoretically, if the site the app download is from is not legitimate, the signing key could also be illegitimate as it comes from the same site. The signing key can be cross-referenced from the [Trezor Suite GitHub releases](https://github.com/trezor/trezor-suite/releases) page. 

**Is there a reason the *SatoshiLabs 2021 Signing Key* is only provided for some releases and not others?**

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
