### ISSUE TITLE
Headers: Send, Receive, Trade

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3752]
**Prototype:** [Figma](https://www.figma.com/proto/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?node-id=2%3A27135&scaling=min-zoom&page-id=2%3A26281) _( 👀 See the animation)_

- [x]  Send: https://zpl.io/amk0Q3K
- [x]  Receive: https://zpl.io/bLed1X7
- [x]  Trade: https://zpl.io/anxjJXQ 
- [x] Sticky headers: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/609e6b6f9b2b15183646e173)

**Comment by matejkriz** [comment]
The link on Prototype is probably wrong? It leads me to "Add account modal" prototype, but the issue could be on my site...

**Comment by bosomt** [comment]
Maybe too sticky ? :) @matejkriz @matejzak  issue ? Or it's just minor detail.

https://user-images.githubusercontent.com/31506317/126942586-0ba11f17-a907-4d94-bd29-14c2a037f499.mov

edit: + graph range has same issue

<img width="844" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/126943235-5883bea3-b89a-4644-b57e-ca321c20ec96.png">


**Info:**
 - Suite version: web 21.8.0 (7f2b12206bca4149b2c30bf3696bf337a064a60e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by dimasivan** [comment]
> Maybe too sticky ? :) @matejkriz @matejzak issue ? Or it's just minor detail.
> Screen.Recording.2021-07-26.at.8.24.37.mov
> 
> edit: + graph range has same issue
> 
> <img alt="obrazek" width="844" src="https://user-images.githubusercontent.com/31506317/126943235-5883bea3-b89a-4644-b57e-ca321c20ec96.png">
> 
> **Info:**
> 
>     * Suite version: web 21.8.0 ([7f2b122](https://github.com/trezor/trezor-suite/commit/7f2b12206bca4149b2c30bf3696bf337a064a60e))
> 
>     * Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0
> 
>     * OS: MacIntel
> 
>     * Screen: 1680x1050
> 
>     * Device: model T 2.4.2 regular

bug related to #3875

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.8.1 (8dfc3fbf9faa870f6c7e6017a63ffeb311cf5b16)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular
