### ISSUE TITLE
Ability to set different currency for prices in dashboard

### ISSUE THREAD

**Issue by vaclav-dvorak** [trezor/trezor-suite#3753]
Every time I'm inspecting my portfolio I have a need to see my balance in national currency however when I'm checking dashboard I would like to see prices in USD.

I would like to suggest new input in settings where you would be able to set secondary currency to be used on dashboard page.

Maybe a checkbox with label like "Show dashboard prices in your main currency" and when uncheck you could set "Currency to be used on dashboard"... Im no UX expert so I believe that if you deem this useful suggestion you will easily find a way.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.

**Comment by hynek-jina** [comment]
@vaclav-dvorak 
You can simply change the currency in settings with few clicks...
![Screen](https://user-images.githubusercontent.com/26002916/145778075-70f18804-b67b-4654-9214-45d0d97a5a36.png)

**Comment by vaclav-dvorak** [comment]
Hi
when this request originated i felt that being able to have two currencies would be beneficial. After more hands-on experience with suite i must say i felt less and less need for this and now consider this idea pointless. Thank you for looking into it and sorry for late reply.
