### ISSUE TITLE
Establish Git Conventions

### ISSUE THREAD

**Issue by goodhoko** [trezor/trezor-suite#3755]
As discussed on the last stand-up, propose a set of git conventions that should be held in the Suite team. Once written up review it with the rest of the team to reach a consensus. The goal is to boost developer happiness and productivity in the long term and to ease delivering big features, bug fixing and development in general. Keep in mind that this is a balancing act and neither git fascism nor complete anarchy are viable.

The set of conventions should be accompanied by tips on how to upheld them with ease in the daily life of Suite developer. Once the conventions are in place consider organising interactive workshop to get everyone on one page.

Assigning myself to kick this off as agreed on the stand-up.

cc @tsusanka @alex-jerechinsky @keraf

**Comment by goodhoko** [comment]
I'm sorry to say this but this will have to wait for someone else.

**Comment by goodhoko** [comment]
My hot tips for the conventions: (quite opinionated)
- link issue numbers in commit messages
- write commit messages as imperative in simple present tense. (https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)
- Don't mix refactoring and features, commit these separately.
- GitHub repository settings
    - protect `develop` branch to prevent accidental pushes.
    - require all threads to be resolved before merging.
    - require at least one review approval for mergning.

**Comment by tsusanka** [comment]
@matejkriz I am voting for closing this, we are using conventional commits and it works good enough. The only setting we do not have set is 

> Require conversation resolution before merging

I can set it if you want.
