### ISSUE TITLE
Link to changelog missing in firmware update modal

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3757]
**Describe the bug**
Link to changelog says TODO in firmware update modal #3757 
Present in 21.5.1 and 21.6.0 dev master

**Steps to reproduce:**
1. connect T1 device with outdated firmware
2. Click update now
3. Click on `Learn more` for 1.10.0 firmware 

**Info:**
 - Suite version: desktop 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.5.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.8.3 regular

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/118275641-fd3ba180-b4c6-11eb-80e7-c664094caabc.png)

![image](https://user-images.githubusercontent.com/31506317/118275900-4db2ff00-b4c7-11eb-8fc9-b0e02ca21703.png)

**Comment by tsusanka** [comment]
Damn :confused:. @szymonlesisz this is probably just a mistake where you have copied & paste the previous version of releases.json from webwallet-data right? In https://github.com/trezor/trezor-suite/commit/e9558d17e0a3956b5cda7758a97bfac1971637a3.

 We need to have this file just in one repo in future

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 21.6.0 (b65e29291276cd6a03c2fa8035966139a2847f90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.6.2 regular + 2.3.4 regular

**Comment by STew790** [comment]
QA OK

**Info:**
 - Suite version: web 21.6.1 (4f358fd151fc1962f30f84a855b82213d958aae7) / same version desktop
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
 - OS: Linux x86_64 / Win10
 - Screen: 1920x1080
 - Device: model One 1.6.1 regular
