### ISSUE TITLE
Trezor Bridge install / update module

### ISSUE THREAD

**Issue by ghost** [trezor/trezor-suite#3758]
**Is your feature request related to a problem? Please describe.**

When one installs Trezor Bridge to connect to third party wallets, it is up to the user to check and install for updates, as this application has no updater, or even an interface to begin with.

**Describe the solution you'd like**

Trezor Suite is an application that is pretty much going to be a standard necessity. While I do not use the application as a wallet, whenever I receive an e-mail regarding an update, I open it, to update the software and my device firmware.

It would be great for it to handle Trezor Bridge update management as well.

**Describe alternatives you've considered**

There are no alternatives to automate Trezor Bridge updating.

**Additional context**

Once the ticket has been discussed I will be requesting the removal of this ticket for safety reasons. Thank you in advance for responding to such a request.

**Comment by jerechinsky** [comment]
Trezor Bridge is bundled with the desktop version of Trezor Suite and is automatically updated. Updates of the standalone version are handled separately.
