### ISSUE TITLE
Get Trezor files to become trusted on VirusTotal

### ISSUE THREAD

**Issue by ghost** [trezor/trezor-suite#3759]
**Is your feature request related to a problem? Please describe.**

Not many people know are interested in PGP verifying a file, nor are as technically inclined. What many of us do is upload files to services such as VirusTotal. A large company can become a trusted source on there and get their files verified or white listed as explained here: https://blog.virustotal.com/2015/02/a-first-shot-at-false-positives.html

**Describe the solution you'd like**

When I upload Trezor Bridge or Trezor Suite for it to be verified as coming from the Trezor company. If you download Skype and upload it on this website, this will be the result:

![image](https://user-images.githubusercontent.com/80743272/118356496-d1c3c000-b575-11eb-8131-41585737d26d.png)

This is the result for Trezor Bridge, it is actually having a few false positives as well:

![image](https://user-images.githubusercontent.com/80743272/118356517-f324ac00-b575-11eb-8079-0dffdf8e6434.png)

**Additional context**

Once the ticket has been discussed I will be requesting the removal of this ticket for safety reasons. Thank you in advance for responding to such a request.

**Comment by bosomt** [comment]
Closing. Both Bridge and Suite are marked as:

**No security vendors flagged this URL as malicious**

https://www.virustotal.com/gui/url/9796ce4150d1e0eebb4d2e3bd6a899b2fb8b36f306d7a8195b02e6e12116163d/detection
https://www.virustotal.com/gui/url/14d9bdfb188fe26dd1e3b3b310f129689b59010bd79f18fd34a5eaca230904d7/detection
