### ISSUE TITLE
Mention SHA256 checksum for files on website

### ISSUE THREAD

**Issue by ghost** [trezor/trezor-suite#3760]
**Is your feature request related to a problem? Please describe.**

Mention SHA256 checksums of files like Trezor Bridge and Trezor Suite offered on the website for checksum verification.

**Describe the solution you'd like**

Trezor:

![image](https://user-images.githubusercontent.com/80743272/118357011-223c1d00-b578-11eb-8d82-48520cbab8ea.png)

Daedalus wallet:

![image](https://user-images.githubusercontent.com/80743272/118357007-1ea89600-b578-11eb-9d7b-427c7121e307.png)

**Additional context**

Once the ticket has been discussed I will be requesting the removal of this ticket for safety reasons. Thank you in advance for responding to such a request.

**Comment by tsusanka** [comment]
Hey @fredddd1 thank you for your issue. As the binaries are served via TLS (HTTPS) the very same way as the website, there is no added security in displaying the hash. Our binaries are however signed using our [SatoshiLabs 2021 Signing Key](https://trezor.io/security/satoshilabs-2021-signing-key.asc), exactly as the website says.

As per your request, we do not have the ability to delete issues, you will have to contact GitHub support.
