### ISSUE TITLE
Labeling - e.split is not a function

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3761]
**Describe the bug**
There is an error in console when user wants to enable labeling

**Steps to reproduce:**
1. Enable labeling
2. Confirm on device

**Info:**
 - Suite version: web 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
 - OS: MacIntel
 - Screen: 3440x1440
 - Device: model T 2.3.6 regular

**Screenshots:**
![Screenshot 2021-05-17 at 9 59 15](https://user-images.githubusercontent.com/33235762/118453135-2d698700-b6f7-11eb-8405-7b51dfc46d0c.png)
![Screenshot 2021-05-17 at 9 59 05](https://user-images.githubusercontent.com/33235762/118453132-2c385a00-b6f7-11eb-9b3a-bb4a21d32204.png)

**Comment by mroz22** [comment]
Can't reproduce but I remember seing this too some time ago. 

@matejkriz does this appear in sentry? 

we could maybe add some additional logging, something like this would do maybe: https://github.com/trezor/trezor-suite/commit/2dae099ee915249a725394a0d5d1efb3feaa282f

**Comment by matejkriz** [comment]
yes, I found this in Sentry:
https://sentry.io/organizations/satoshilabs/issues/2534227802/

**Comment by tomasklim** [comment]
How to test:
1. Install Waves Keeper extension (Metamask for Waves blockchain) (https://chrome.google.com/webstore/detail/waves-keeper/lpilbniiabackdjcionkobglmddfbcjo?hl=en) 
2. Open Suite web
3. Enable labeling
4. Choose Google Drive
5. Error was available in the console but it should not be anymore

**Comment by bosomt** [comment]
**QA OK**

Metamask for Waves blockchain instaled

**Info:**
 - Suite version: web 21.11.0 (a1c3485131b680c2916b51654f26ebf4addba3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

<img width="1488" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/137501354-55c71405-f831-4bbe-8289-ce2d2612e719.png">
