### ISSUE TITLE
fix(invity): Sell Crypto: functionality of the button "Get this Offer"

### ISSUE THREAD

**Issue by martinboehm** [trezor/trezor-suite#3765]
The button "Get this Offer" in the sell quote has in certain cases incorrect functionality, see https://github.com/trezor/trezor-suite/pull/3603#issuecomment-839594063.

In case of BTCDirect provider, there are 4 different cases of the sell quote:

1) Suite account is not linked to BTCDirect account

![image](https://user-images.githubusercontent.com/11609674/118516988-1e0a2e00-b737-11eb-997b-1f43b3e18530.png)
In this case, there is a note in the quote "This offer is only preliminary. By choosing this offer, you will be redirected to BTC Direct site. After entering your details, you will get a more specific offer."

Functionality OK, the button redirects to BTCDirect site for account registration

2) Suite account is linked to BTCDirect account but there is no SEPA account registered at BTCDirect

![image](https://user-images.githubusercontent.com/11609674/118517093-367a4880-b737-11eb-8132-b6855f9b1701.png)
In this case, there is a note in the quote "Your bank account hasn't been verified yet. Select Register to complete the verification process with our partner."

Functionality not OK. Required is to rename the button to "Register" and its functionality is to redirect to BTCDirect for SEPA account registration.

3) Suite account is linked to BTCDirect account, there is at least one SEPA account registered but not yet verified by BTCDirect

In this case, there is a note in the quote "Your bank account verification is in progress. Please allow up to 3 business days for this to finish or select Register to add another account."

Functionality not OK. Required is to rename the button to "Register" and its functionality is to redirect to BTCDirect for SEPA account registration.

4) Suite account is linked to BTCDirect with at least one verified SEPA account.

In this case, there is no note in the quote.

Functionality OK, the button leads to the sell flow in the Suite.

**Comment by bosomt** [comment]
I was able to get 1. and 2. case and that's probably all we can do on our side, other require us to register SEPA credit card that i don't have.

<img width="988" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120078651-5b13e000-c0a8-11eb-908a-720541b87747.png">


**Info:**
 - Suite version: desktop 21.6.0 (b65e29291276cd6a03c2fa8035966139a2847f90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular
