### ISSUE TITLE
Unable to update firmware

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3767]
**Describe the bug**
After merging [#3629](https://github.com/trezor/trezor-suite/pull/3629), I am unable to update firmware on my device because app crashes. The reason is that revision is not obtained in bootloader mode.

**Steps to reproduce:**
1. Update firmware in settings
2. Connect device in bootloader

**Info:**
 - Suite version: web 21.6.0 (9d8cea584b1f655f0964d80f863b02b1523e2cad)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
 - OS: MacIntel
 - Screen: 3440x1440
 - Device: model T 2.1.5 Bitcoin only

**Screenshots:**
![Screenshot 2021-05-18 at 9 01 02](https://user-images.githubusercontent.com/33235762/118628627-11381980-b7cd-11eb-8f1f-c4e371fcc118.png)

**Comment by tomasklim** [comment]
![Screenshot 2021-05-18 at 13 00 05](https://user-images.githubusercontent.com/33235762/118640502-56fadf00-b7d9-11eb-8346-147a5b8cb6fd.png)
Another issue is bad encoding of revision because it takes me to https://github.com/trezor/trezor-firmware/commit/�BN�������@��O

On TT: the revision is in hex raw bytes (This is correct)
On T1: it is in UTF-8

However, in code, the revision is always encoded into UTF-8. So UTF-8 is encoded again.

Firmware related issue: #1620

**Comment by tomasklim** [comment]
@szymonlesisz should the revision encoding fix be available in Suite or connect?

**Comment by bosomt** [comment]
**QA OK**

2.4.0 

<img width="626" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120063043-2d557980-c05d-11eb-91e7-8aeeeb1929d5.png">

1.6.2

<img width="819" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120063112-7c031380-c05d-11eb-90ff-766e13484818.png">


**Info:**
 - Suite version: desktop 21.6.0 (b65e29291276cd6a03c2fa8035966139a2847f90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.6.2 regular + 2.4.0 regular

**Comment by STew790** [comment]
QA OK

Info:

Suite version: desktop 21.6.1 (4f358fd)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
OS: Win32
Screen: 1920x1080
Device: model T 2.4.0 regular & One 1.9.4 regular
