### ISSUE TITLE
"X-Frame-Options: DENY" header

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#3775]
Suite does not like "X-Frame-Options: DENY" header. It worked fine in v21.4.1. Likely related #3722, according to @tsusanka.

**Comment by tsusanka** [comment]
@szymonlesisz do you think this is indeed due to #3722?

**Comment by tsusanka** [comment]
Discussed with @szymonlesisz. It is indeed due to #3722. We should allow SAMEORIGIN. So unless @prusnak protests I will add  "X-Frame-Options: SAMEORIGIN" to staging. And after some time and thorough test we can add this to production.

**Comment by prusnak** [comment]
ACK for SAMEORIGIN

**Comment by tsusanka** [comment]
Changed to SAMEORIGIN on staging and confirmed it is indeed sent, everything seems to work. I'll keep it on staging for a week or two and then apply to production if no problems arise.

**Comment by tsusanka** [comment]
Done in Production as well.

QA: I did a quick check so everything seems OK so nothing in particular needs to be tested. If you find anything funny going on in production let me know.

**Comment by sorooris** [comment]
**QA OK**

Nothing funny was found; only serious business. Approving.

Suite: app + web (tested 21.7.1 ca85ae5)
Browser: N/A, Chromium 91.0.4472.77
OS: macOS Big Sur 11.4, NixOS 21.05
Device: model One 1.10.1
