### ISSUE TITLE
Upper/lowercase inconsistency in Trezor/Suite ETH format address

### ISSUE THREAD

**Issue by soucek87** [trezor/trezor-suite#3776]
**Issue**
Suite and Trezor are displaying upper/lowercase letters differently in ETH addresses.

**Describe the solution you'd like**
Suite and Trezor should display addresses in exactly the same format.

**Additional context**
Related to checksum, EIP55 https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md

**Comment by jerechinsky** [comment]
@szymonlesisz this was discussed on slack [here](https://satoshilabs.slack.com/archives/C016ACNF1BN/p1621500445003900).

**Comment by STew790** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/48477147/124289878-153cb280-db53-11eb-879a-4362a06bcb2d.png)
![image](https://user-images.githubusercontent.com/48477147/124289900-1b329380-db53-11eb-944d-f380f28df08b.png)

Info:
 - Suite version: desktop 21.7.0 (550942dcbdb7b2ffc17519f8307a47f2d8d060f1)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model 1 1.10.1 regular

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.7.0 (8b018e2f06a7e36d9a650c2b7327c13da125dcdc)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model 1 1.10.2 regular
