### ISSUE TITLE
Pending buy - double transaction ID

### ISSUE THREAD

**Issue by LukasRada** [trezor/trezor-suite#3781]
**Describe the bug**
Double transaction ID, when a buying process is in progress.

**Expected result:**
To show only transaction ID on the right (see screenshot).

**Screenshots:**
![image](https://user-images.githubusercontent.com/7394177/119144397-e823bd00-ba48-11eb-828c-6a9a1591908a.png)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 21.6.0 (b65e29291276cd6a03c2fa8035966139a2847f90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.4 regular

**Comment by wendys-cats** [comment]
**QA OK**

**Info:**

**Suite version:** desktop 21.6.1 4f358fd151fc1962f30f84a855b82213d958aae7
**OS**: Windows 10
**Device**: TT 2.4.0 ea3596a
