### ISSUE TITLE
Send form improvements

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3784]
There are a few possible improvement the current look & behavior:  

1. Users enters Send form, **` Review & Send` button is disabled by default**, and actually doesn't look like a button considering the same background color.

<img width="931" alt="Screen Shot 2021-05-23 at 17 16 00" src="https://user-images.githubusercontent.com/29627086/119268568-7172f500-bbeb-11eb-8572-876a238bedb6.png">

- [ ] Do not disable Send button by default. If users click `Send` while one or more inputs are not filled in, populate the validation error(s).

2. Transaction is signed, **the total amount doesn't have a green check**, even though, the information has been confirmed on Trezor device. 

<img width="942" alt="Screen Shot 2021-05-23 at 17 07 19" src="https://user-images.githubusercontent.com/29627086/119268198-cada2480-bbe9-11eb-99b5-42ed4ee3e622.png">

- [x] Populate the green check of `total amount` upon user's confirmation on device. 

 3. If users signs the transaction, but decides to cancel it by the `X` button before broadcasting it to the network, they are left in a **filled-in form with disabled button**. 
 
 <img width="989" alt="Screen Shot 2021-05-23 at 17 12 56" src="https://user-images.githubusercontent.com/29627086/119268278-21476300-bbea-11eb-920c-21e78040502b.png">

- [x] Not sure if it's technically feasible, but ideally the primary button will stay enabled.

**Comment by szymonlesisz** [comment]
@matejzak regarding "send button", read my [comment here](https://github.com/trezor/trezor-suite/pull/3853#discussion_r647527093)

**Comment by szymonlesisz** [comment]
closing this in favour of https://github.com/trezor/trezor-suite/pull/3879

**Comment by szymonlesisz** [comment]
as discussed in person, first improvement needs to be done in the design of the button, enabling button doesn't solve anything and even brings more trouble.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.6.2 (97d032adf84e5b7c5dd82fb3085fdeb4434ad7f8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.0 regular

**Comment by goodhoko** [comment]
@szymonlesisz This was maybe already resolved in https://github.com/trezor/trezor-suite/pull/3879?

If so, can we close this?*

**Comment by szymonlesisz** [comment]
closing in favor of https://github.com/trezor/trezor-suite/issues/4100
