### ISSUE TITLE
Remove shake from the wallet navigation

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3786]
Please remove the "shake" animation from the switch wallet navigation. 

Steps to reproduce: 

1.Standard wallet loaded 
2. Click `+ Add Hidden Wallet` 
3. The wallet switch in the top navigation shakes

https://user-images.githubusercontent.com/29627086/119279183-f5e06a80-bc21-11eb-8a2b-3006e80ac98c.mov

**Comment by tsusanka** [comment]
@matejzak we will remove the shake animation for all use cases correct? It was also triggered for new device connected for example.

**Comment by glacierbits** [comment]
Thanks! Just wondering, do we have a complete list of triggers for the action?

**Comment by tsusanka** [comment]
You mean what actions cause this animation? AFAIK it happens only if the number of wallets change.

**Comment by tsusanka** [comment]
This was a bad idea, let's do it someone more knowledgeable in this area :).

**Comment by glacierbits** [comment]
Navigation UX will change with the new dashboard, let's not worry about this.
