### ISSUE TITLE
Remove bounce from snack bar notifications

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3787]
Remove the "bounce" from the notifications. 

Please try to smooth out the animation 🙏🏽 

https://user-images.githubusercontent.com/29627086/119279320-d990fd80-bc22-11eb-9801-9ddb183ffabc.mov

**Comment by szymonlesisz** [comment]
@matejzak like this?
![Peek 2021-06-16 09-58](https://user-images.githubusercontent.com/3435913/122181343-932d6800-ce89-11eb-9f71-aaf850c136f8.gif)

**Comment by glacierbits** [comment]
Looks great!

**Comment by bosomt** [comment]
**QA OK**



**Info:**
 - Suite version: web 21.7.0 (b0ea8be015a610b83246d99a57761105259ea84f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.10.1 regular

**Comment by STew790** [comment]
**QA OK**

Info:
 - Suite version: desktop 21.7.0 (550942dcbdb7b2ffc17519f8307a47f2d8d060f1)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model 1 1.10.1 regular
