### ISSUE TITLE
Update of bitcoin-only fw

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3790]
**Describe the bug**
When I update bitcoin-only firmware, I get the regular fw.

**Steps to reproduce:**
1. Have device with old bitcoin-only fw
2. Update fw
3. Check new version

**Info:**
 - Suite version: web 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
 - OS: MacIntel
 - Screen: 3440x1440
 - Device: model T 2.3.5 Bitcoin only

**Expected result:**
Bitcoin-only fw updates to bitcoin-only fw.

**Actual result:**
Bitcoin-only fw updates to regular fw.

**Comment by bosomt** [comment]
Was this change merged to June freeze release ? Maybe it belongs to July release cycle ?

1) Installed `trezorctl firmware-update -f trezor-2.3.5-bitcoinonly.bin`
2) Got offered 2.3.6 during onboarding and got regular FW installed.


**Info:**
 - Suite version: web 21.6.1 (7d50da6b9fe39ddd934fdf6153b4c4afb2d7fd88)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.6 regular
 
<img width="288" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120635056-eb18a780-c463-11eb-82a7-3480f9cafb8b.png">

**Comment by bosomt** [comment]
retested in same environment, when updated via settings/device and not via onboarding correct BTC-only FW was installed correctly.

@tomasklim @slowbackspace do you want me to create separate issue for BTConly firmware update in current/old onboarding ?

<img width="396" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120638083-9a0ab280-c467-11eb-8116-6628d49a430e.png">

**Comment by tomasklim** [comment]
@bosomt I can see the issue. I forgot about this specific case. Fix is available in https://github.com/trezor/trezor-suite/tree/fix/btc-only-fw-update-in-onboarding. I will ask @tsusanka if we want to fix it in this release.

**Comment by bosomt** [comment]
I'm currently not able to test on domain suite.corp.sldev.cz 
Firefox doesn't have access to bridge and chrome webusb is not working ;)
Is it possible to disable CORS in Firefox ?
 

<img width="1199" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120644624-75b2d400-c46f-11eb-8d8b-a5b1dfabbc30.png">

**Comment by tomasklim** [comment]
https://addons.mozilla.org/en-US/firefox/addon/access-control-allow-origin/ maybe or you can download downgrade chrome

**Comment by bosomt** [comment]
**QA OK**

My problem was fixed by starting new version of Trezor Bridge via Suite app.
And update of BTC only firmware during onboarding was fixed too :)

**Info:**
 - Suite version: web 21.7.0 (1d88a2f3e51dea35f00ab4cdcffa39d70b3169f7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.6 Bitcoin only


<img width="689" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120650174-6d5d9780-c475-11eb-8fc9-38cf9a30119f.png">

<img width="353" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120650414-ae55ac00-c475-11eb-8498-9c2cab081b8c.png">

**Comment by STew790** [comment]
QA OK

Info:

Suite version: desktop 21.7.0 (1d88a2f)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
OS: Win32
Screen: 1920x1080
Device: model T 2.3.6 Bitcoin only
