### ISSUE TITLE
App, Settings - Tor - Onion links switch does not reflect OFF state with blog posts

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3793]
**Describe the bug**
Selecting any article link from the Dashboard's News section (blog.trezor.io/*) redirects to an onion link when _Tor_ connection is **ON** and the _Open trezor.io links as .onion links_ button is **OFF** ; however all other *.trezor.io (Support link in the floating BETA badge, wiki.trezor.io links) are not affected and reflect the button's state correctly.

**Info:**
 - Remembered Wallet: any
 - Suite Version: app 21.5.1 4d09d88
 - OS: any (tested macOS Big Sur 11.3.1)
 - Bridge: any (2.0.31 rev 5f53132)
 - Firmware Version: any (tested model T 2.4.0 RC)

**Steps to reproduce:**
1. Switch Tor connection ON,
2. Switch _Open trezor.io links as .onion links_ button OFF,
3. Open an article on Dashboard, News section.

**Expected result:**
Warning dialog about redirection to **clearsite link** is displayed (and subsequently redirected to it after confirmation).

**Actual result:**
Warning dialog contains a message about onion link, even when the  _Open trezor.io links as .onion links_ button is in OFF state.

**Screenshots:**
Tor ON, onion links button OFF
![image](https://user-images.githubusercontent.com/10185314/119529745-a9f90700-bd82-11eb-9722-9e09dc591e6c.png)
Warning dialog
![image](https://user-images.githubusercontent.com/10185314/119529704-a36a8f80-bd82-11eb-8332-ed052b73e678.png)

**Note(s):**
Please note that the undesirable behavior when both Tor and the .onion links button are in the **ON** state which opened a clearsite link was already reported in https://github.com/trezor/trezor-suite/issues/3542#issue-829042032.

Also please note that there is no (at least apparent) reason to keep the onion links button enabled when Tor is in OFF state, I'd suggest it's disabled when Tor is OFF.

**Comment by bosomt** [comment]
**QA NOK**

still same behavior


**Info:**
 - Suite version: desktop 21.8.0 (566ba345c50b6fd7e773a905d5d8f40c7f8056f2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model 1 1.10.1 regular

**Comment by bosomt** [comment]
**QA OK**

 - Suite version: desktop 21.11.0 (d7c96df8f3d4d41cb4fed0aaad8a4d648ba6fa08)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.11.0 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular
