### ISSUE TITLE
MacOS: Resizing window with double-click

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3796]
The double-click on the (black) navbar on MacOS desktop should enter full screen. Another double-click will resize the window back to the original size.

**Comment by bosomt** [comment]
And I thought that it was problem on my side :)
I was able to reproduce the issue ;)


**Info:**
 - Suite version: desktop 21.6.0 (b65e29291276cd6a03c2fa8035966139a2847f90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular

**Comment by glacierbits** [comment]
I believe it's more of a feature request than a bug, but as a MacOS user I am pretty used to resizing windows in this way, so it would be great.. 🙏🏽 😊
