### ISSUE TITLE
Autoupdate: Unclear cancel/minimaze UX

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3797]
The `X` and `x Cancel` buttons are confusing, since it is not clear which one does what. 

The original [design proposal ](https://zpl.io/2vj1LQY) counted on the option to (1) minimize the autoupdate modal to a notification and (2) maximize it back to the progress modal via `view` button. The option to cancel the autoupdating process hasn't been designed yet. 

1. I assume the option to cancel the download makes sense and we want to support it? @tsusanka @keraf 
In which case "design needed"
2. I believe the minimized update should stay in the notification (or somewhere on the front-face) since the users loses the feedback whether the update is still in progress or not unless they search for in the application settings. Is it a technical challenge to put it in the notification as designed @keraf? 

https://user-images.githubusercontent.com/29627086/119903968-77e1d380-bf41-11eb-8d98-cad10a3d5899.mov

**Comment by tsusanka** [comment]
> I assume the option to cancel the download makes sense and we want to support it? @tsusanka @keraf In which case "design needed"

At first I wasn't sure we need such option if you can minimize the window and carry on. But I can image a scenario where you may end up in a situation where your resources are limited (let's say you are on a mobile hotspot) and you really do not want to update now. So I agree we should have both minimize and cancel.

**Comment by goodhoko** [comment]
We agreed on the stand-up today that we'll remove the cancel button altogether. Our general intention is to push users to do the update. Removing the option to cancel it mid-downloading will slightly help us in this manner while affecting the UX minimally.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 21.7.1 (34de15f6b0dcdbf8dc69a34fc65e6abab6a8213d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular

**Comment by STew790** [comment]
**QA OK**

Info:
 - Suite version: desktop 21.7.1 (1abd1be)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.3.6 regular

**Comment by wendys-cats** [comment]
**QA OK**

Cancel on auto update modal is no longer present when version 21.7.1 is being updated.

**Info**:

**Suite**: APP 21.7.1 1abd1be26f5ae166ec910fe193c4a804d5949a86
**OS**: Windows 10
**Device**:  TT 2.4.1 regular
