### ISSUE TITLE
Update T&Cs in Onboarding

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3799]
We have a new T&Cs. Please update them in the new Onboarding. 

[01_Suite Terms and Conditions_202105.pdf](https://github.com/trezor/trezor-suite/files/6560038/01_Suite.Terms.and.Conditions_202105.pdf)

**Comment by slowbackspace** [comment]
We are just linking the document that is uploaded to `https://data.trezor.io/legal/wallet-terms.pdf` as we want one ultimate source of T&Cs. Maybe it should be also uploaded there (either as a replacement or addition to `wallet-terms.pdf`)?

cc @tsusanka

**Comment by glacierbits** [comment]
FYI These are intended (from our legal department point of view) for both old Wallet and Suite.

**Comment by tsusanka** [comment]
Wait @slowbackspace I am confused. On one side you are saying we link to data.trezor.io on the other you have already filled a PR where you are changing the file. So we do not link to data.trezor.io?

**Comment by slowbackspace** [comment]
> Wait @slowbackspace I am confused. On one side you are saying we link to data.trezor.io on the other you have already filled a PR where you are changing the file. So we do not link to data.trezor.io?

We do link to data.trezor.io, isn't the content of webwallet-data repository, where I opened PR, published to data.trezor.io? If not then I have no idea how to update the file.

**Comment by tsusanka** [comment]
Fuck sake, I am stupid. I thought it is a PR into Trezor Suite :facepalm:. All good then. It says it is valid from June 1st so I will merge it then :).

**Comment by bosomt** [comment]
I still see 2019 T&C during onboarding on staging Suite.

<img width="484" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120627260-6590f980-c45b-11eb-8937-52f6b807e888.png">


**Info:**
 - Suite version: web 21.6.1 (7d50da6b9fe39ddd934fdf6153b4c4afb2d7fd88)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 Bitcoin only

**Comment by slowbackspace** [comment]
cc @tsusanka 
it should work right?

**Comment by tsusanka** [comment]
Apologies I haven't deployed it yet.

**Comment by tsusanka** [comment]
Done.

**Comment by bosomt** [comment]
**QA OK**

Info:

    Suite version: web 21.6.1 (7d50da6)
    Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
    OS: MacIntel
    Screen: 1440x900

**Comment by bosomt** [comment]
@tsusanka @slowbackspace 
any plans to update TOS here : https://trezor.io/static/pdf/tos.pdf
this address is displayed on TT display during onboarding

edit: actually it's trezor.io/tos but it's redirected to https://trezor.io/static/pdf/tos.pdf so maybe you can just change redirect

<img width="636" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120713419-c64f1f00-c4b9-11eb-8fd4-69d1d0d5beed.png">

**Comment by bosomt** [comment]
sent separate issue https://github.com/satoshilabs/trezor.io/issues/233

**Comment by wendys-cats** [comment]
**QA OK**

**Suite version:** web 21.6.1 4f358fd151fc1962f30f84a855b82213d958aae7
**Browser:** Chromium Version 88.0.4324.182 (Official Build) (64-bit)
**OS:** NixOS 21.03

![image](https://user-images.githubusercontent.com/58593111/121160078-12002080-c84c-11eb-9acf-3132420a3180.png)

**Comment by STew790** [comment]
QA OK

**Info:**
 - Suite version: web 21.6.1 (4f358fd151fc1962f30f84a855b82213d958aae7)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
 - OS: Linux x86_64
