### ISSUE TITLE
Update T&Cs: Invity

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3800]
Updated T&Cs from our legal department. Please update the document in old Wallet as well as in Suite. 

[02_Trezor Suite Services by Invity_Terms of Use_202105.pdf](https://github.com/trezor/trezor-suite/files/6560090/02_Trezor.Suite.Services.by.Invity_Terms.of.Use_202105.pdf)

**Comment by tsusanka** [comment]
Uploaded to https://data.trezor.io/legal/invity-terms-of-use.pdf. Should I close the issue @LukasRada?

**Comment by LukasRada** [comment]
@tsusanka Not yet. I need to update the footer in Suite coin market. And then also in the old Wallet. Thank you.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.7.0 (b6021aea87a5f683069efac15473e8028fd5b869)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.0 regular

**Comment by wendys-cats** [comment]
**QA OK**

Suite and Wallet - https://data.trezor.io/legal/invity-terms-of-use.pdf OK 

**Info**
**Wallet version:** 3a553b24e498c56a2e03897fded706dffb4a6d6b
**Suite version:** web 21.7.0 b6021aea87a5f683069efac15473e8028fd5b869 
**Browser:** Chromium Version 88.0.4324.182 (Official Build) (64-bit)
**OS:** NixOS 21.03 unstable
**Device:** model T 2.4.0 regular
