### ISSUE TITLE
Constant GPU usage arround 66% while on the initial screen asking to connect the device.

### ISSUE THREAD

**Issue by Transisto** [trezor/trezor-suite#3802]
![image](https://user-images.githubusercontent.com/388716/120021328-eca42480-bfb8-11eb-8960-637fa518ef1b.png)

"C:\Program Files\Trezor Suite\Trezor Suite.exe" --type=gpu-process --field-trial-handle=1564,530356497636322665,14114444165887088555,131072 --enable-features=WebComponentsV0Enabled --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --gpu-preferences=MAAAAAAAAADgAAAwAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAAKAAAAAQAAAAgAAAAAAAAACgAAAAAAAAAMAAAAAAAAAA4AAAAAAAAABAAAAAAAAAAAAAAAAUAAAAQAAAAAAAAAAAAAAAGAAAAEAAAAAAAAAABAAAABQAAABAAAAAAAAAAAQAAAAYAAAA= --mojo-platform-channel-handle=1588 /prefetch:2

This is the lauch command for the app, What a disgusting bloat.

**Comment by keraf** [comment]
Not sure why there are so many parameters and even what they are used for. Have you installed the application using the provided installer? Have you done any other manipulations with the application installation/launch?

**Comment by Transisto** [comment]
> Not sure why there are so many parameters and even what they are used for. Have you installed the application using the provided installer? Have you done any other manipulations with the application installation/launch?

I haven't done anything special,  I barely ever used the app because it's always been a heavy bloat.

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/120114860-1ee78a80-c14f-11eb-920b-a6e24ad089eb.png)

These are sub process launched by the main exe itself.

**Comment by Transisto** [comment]
Fixed after updating,  https://github.com/trezor/trezor-suite/issues/3808

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 21.6.1 (0ce310eb30cff6396b91939d3293b34e8e50d7c1)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1280x720
 - Device: model One 1.10.1 regular

**Comment by STew790** [comment]
**QA OK**

Info:
 - Suite version: desktop 21.7.0 (550942dcbdb7b2ffc17519f8307a47f2d8d060f1)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.0 regular
