### ISSUE TITLE
Incorrect font properties: Setting & Account details

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3803]
Please apply the weights, size, and colors exactly as designed: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5faaa48ab6e7968540370da5) 

**Incorrect in Settings:** 

- [x] Section header
- [x] Item header
- [x] Item description 

<img width="351" alt="Screen Shot 2021-05-28 at 18 36 18" src="https://user-images.githubusercontent.com/29627086/120021925-9a2c2d80-bfe3-11eb-8ce7-a65cb1c1e459.png"> 

**Improvements in Account details:** 

- [x] Learn more in as tertiary button
- [x] Max width for description text 
- [x] Center the Account type above the secondary button (if possible) 

<img width="861" alt="Screen Shot 2021-05-28 at 18 52 14" src="https://user-images.githubusercontent.com/29627086/120023528-d52f6080-bfe5-11eb-9a02-661732766a36.png">

**Comment by glacierbits** [comment]
One more thing 🙏🏽 

Can we please [add a hover](https://www.notion.so/satoshilabs/Hover-states-78c3753ed8874fdbb224cb2d9e3b6af7) (4% black / 8% white) to the tertiary buttons instead of the underline? 

<img width="116" alt="Screen Shot 2021-06-10 at 19 15 54" src="https://user-images.githubusercontent.com/29627086/121576448-4a585800-ca20-11eb-815a-a39280df2c1c.png">

**Comment by dimasivan** [comment]
@matejzak I'll add hover to tertiary button in another PR #3829

**Comment by glacierbits** [comment]
Thanks!

**Comment by bosomt** [comment]
I'm not sure if it's caused by this change or it just made to stand out but can you please center enable/disable all buttons or  align it with section headers? Looks kinda broken. Do you want me to create issue ? @matejzak 

**screen # 1**


![image](https://user-images.githubusercontent.com/31506317/124592501-d6ae3d00-de5d-11eb-80f2-b259e94c69d5.png)






**screen # 2**
![image](https://user-images.githubusercontent.com/31506317/124592534-ddd54b00-de5d-11eb-9734-e1823069864c.png)


**Info:**

```

 - Suite version: web 21.7.0 (b606e96f4fa2418e0b44d54345c334e23a6a09de)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.1 regular
```

**Comment by sorooris** [comment]
**QA OK**

Settings:
- [x] Section header
- [x]  Item header
- [x] Item description
- [x]  Hover in tertiary buttons

Account details:
- [x]  Learn more in as tertiary button
- [x]  Max width for description text
- [x]  Hover in tertiary buttons

Suite: web 21.7.1 24cc565a
Browser: Chromium 91.0.4472.77
OS: NixOS
Device: model One 1.10.2
