### ISSUE TITLE
Hover states

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3804]
**Spec:** [Notion](https://www.notion.so/satoshilabs/Hover-states-78c3753ed8874fdbb224cb2d9e3b6af7) 

- [x] Top navigation (Dashboard, Accounts) 
- [x] Account tabs (Overview, Account details, Tokens) 

FYI @tomexx has done some hover work on the navigation icons, feel free to consult him. 

Also, if we'd be able to create that cute expanding-animation-trick shown in the spec & prototype, that would be really cool..

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.8.1 (8dfc3fbf9faa870f6c7e6017a63ffeb311cf5b16)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular
