### ISSUE TITLE
Send raw: Close button inconsistency 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3805]
The _Send raw_ has has the close button outside of the white box, while the OP_Return has the closed `X` nested within the white box › That's the correct & preferred way. 

Good 👇🏽 
<img width="814" alt="Screen Shot 2021-05-28 at 22 35 15" src="https://user-images.githubusercontent.com/29627086/120044325-85609180-c005-11eb-9784-2d391b2efbd7.png">
 
Bad 👇🏽 (Should be nested within the white box)
<img width="906" alt="Screen Shot 2021-05-28 at 22 35 23" src="https://user-images.githubusercontent.com/29627086/120044347-94474400-c005-11eb-93cd-d9ea64435c1e.png">

**Comment by wendys-cats** [comment]
**QA OK** 

**Suite:** web version 21.7.0 b6021aea87a5f683069efac15473e8028fd5b869
**Browser:** Chromium Version 88.0.4324.182 (Official Build) (64-bit)
**OS:** nixOS 21.03 unstable
**Device:** TT 2.4.0 regular 


![image](https://user-images.githubusercontent.com/58593111/121865992-d0192380-ccfe-11eb-9f57-22c16d142741.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.7.0 (89aee5512ea0059de309935684b5be5fb3b1843b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.10.1 regular

**Comment by STew790** [comment]
**QA OK**
Info:
 - Suite version: desktop 21.7.0 (550942dcbdb7b2ffc17519f8307a47f2d8d060f1)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.0 regular
