### ISSUE TITLE
Authorization error: Copy improvement

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3807]
Can we please improve (and shorten) text of this authorization error? 🙏🏽 

Maybe just `Authorization error`?  

<img width="730" alt="Screen Shot 2021-05-29 at 12 49 19" src="https://user-images.githubusercontent.com/29627086/120069182-694c0700-c07c-11eb-8999-62efb6bc0d9b.png">

**Comment by szymonlesisz** [comment]
@matejzak in this given case it's long but i think this error should be present here for debugging purposes.

error message is generic, could be anything, like "device disconnected during action", "device is used in another window" or  "lib_usb_error"... etc

without this message it will be hard to find the reason what is going on

**Comment by goodhoko** [comment]
@trezor/qa @szymonlesisz desribed the desired behaviour in the [PR description](https://github.com/trezor/trezor-suite/pull/3980#issue-682104745).

**Comment by bosomt** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/31506317/128030122-d07d3a74-c5d8-4d6c-b1fb-a0e77cd267e6.png)

**Info:**
 - Suite version: web 21.8.0 (656867e3f31ba07b4c3cd3d13cb681d132f2f825)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.4.1 regular
