### ISSUE TITLE
Should be possible to do something with the app, like updating before unlocking the device.

### ISSUE THREAD

**Issue by Transisto** [trezor/trezor-suite#3808]
![image](https://user-images.githubusercontent.com/388716/120119568-71807100-c166-11eb-84d6-86b7e60ff8b5.png)

**Comment by bosomt** [comment]
**QA OK**

you now can perform update before you connect your device and of course you can perform some available actions with app when you have locked or disconnected device when you have remembered already loaded wallet

**Info:**
 - Suite version: web 21.7.1 (24cc565a3badd85ab48b30348022471dfd85f90e)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.2 regular
