### ISSUE TITLE
"Show public key" button not clickable (& transactions not showing up)

### ISSUE THREAD

**Issue by caglorithm** [trezor/trezor-suite#3810]
**Describe the bug**
The button to show the public key for any account is not clickable. The rotating indicator keeps spinning. Happens with and without Tor since I thought the connection to the backend might be broken. Even if, I don't see the reason why it wouldn't be clickable. 

**Info:**
 - Suite Version: app, Version 21.5.1 (21.5.1.11425)
 - OS: macOS Big Sur, 11.2.2 (20D80)

**Steps to reproduce:**
Unfortunately, no idea.

**Expected result:**
Should be clickable.

**Actual result:**
Not clickable, is stuck in "loading/rotating" state.

**Screenshots:**
![image](https://user-images.githubusercontent.com/7763212/120152407-bef3f100-c1ed-11eb-8d0a-8e6c1bfa6122.png)

**Note(s):**
I also see that the most recent transactions for some accounts are not visible, although I can perfectly see them in the trezor block explorer. Generally speaking, Trezor Suite is very often not in sync with what the block explorer tells me. This leads to a lot of confusion and might scare some users who're not that familiar with how transactions work. Generally speaking, Trezor Suite has very frequent problems syncing and showing transactions that are visible in the explorer, and sometimes takes a long time to update its records.

**Comment by jerechinsky** [comment]
Was this a one time occurrence or is this something that happens often for you?

**Comment by caglorithm** [comment]
Hey! It's been the first time and has been stuck in this day for some days... I don't want to delete all the app data because of the labeling of my accounts but maybe that's the only way to go?

**Comment by jerechinsky** [comment]
Has updating the app perhaps helped? Have you encountered this bug ever since?

**Comment by bosomt** [comment]
@caglorithm this happens when Suite lost connection to Trezor , device got disconnected or Trezor Bridge is not responding.

Restart of suite is recommended. I hope upgrade to latest version or clearing Suite cache helped.

@caglorithm can we close this issue ?

**Comment by caglorithm** [comment]
@bosomt you can close the issue but I think that the UI should reflect whether it is connected or not. Please see my additional note in the top comment. It could cause a very disturbing situation for a user if they are not able to check the true state of their wallet in a block explorer. Suite currently very poorly communicates whether the information shown is up to date or not.

**Comment by jerechinsky** [comment]
Thank you for the feedback @caglorithm.
This is being addressed in #3454.
