### ISSUE TITLE
Remove BETA tag

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3822]
Please: 

- [x] Remove `BETA` tag and all it's contents 
- [x] Move the floating action button with the 3D image to the bottom right corner (cca 16-24 px from the sides) 

<img width="168" alt="Screen Shot 2021-06-01 at 19 29 08" src="https://user-images.githubusercontent.com/29627086/120373865-c3fd9100-c310-11eb-9abe-5a71e7150c38.png">

**Comment by goodhoko** [comment]
@matejzak Would you like to ship this with the next release or wait for the public launch one release later? The PR is ready and approved so it's just a question of when we'll hit the button. .)

**Comment by goodhoko** [comment]
@tomasklim I guess you just answered it .D .)

**Comment by tomasklim** [comment]
> @tomasklim I guess you just answered it .D .)

https://github.com/trezor/trezor-suite/pull/3833#issuecomment-857005901 😉

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.7.0 (b6021aea87a5f683069efac15473e8028fd5b869)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.0 regular

**Comment by wendys-cats** [comment]
**QA OK** 

**Info**

**Suite version:** web 21.7.0 b6021aea87a5f683069efac15473e8028fd5b869
**Browser:** Chromium Version 88.0.4324.182 (Official Build) (64-bit)
**OS:** NixOS 21.03 unstable
**Device:** model T 2.4.0 regular
