### ISSUE TITLE
Remove . from firmware version sentence

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3830]
**Describe the bug**
Please consider removing . in `Your current firmware version is . ` sentence.
It's not present in Suite version and it's triggering my OCD.

**Info:**
 - Suite version: web 21.6.1 (7d50da6b9fe39ddd934fdf6153b4c4afb2d7fd88)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.10.0 regular

**Screenshots:**

<img width="278" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120510902-c966e400-c3c1-11eb-88e9-f8e8f87560b1.png">

<img width="283" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120510934-d08df200-c3c1-11eb-88d7-f47e061d6e9b.png">

**Comment by jerechinsky** [comment]
Removed it via copy. Thanks, @bosomt.

**Comment by bosomt** [comment]
@alex-jerechinsky  was it merged already ?

![image](https://user-images.githubusercontent.com/31506317/121703878-87315700-cad3-11eb-89d5-cd253db5eef6.png)


**Info:**
 - Suite version: web 21.7.0 (b6021aea87a5f683069efac15473e8028fd5b869)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.0 regular

**Comment by wendys-cats** [comment]
**QA NOK**

Not merged yet, bošo is upset. @alex-jerechinsky 
![image](https://user-images.githubusercontent.com/58593111/121895105-29457f00-cd20-11eb-9f25-01dced79c2a5.png)

**Info:**
**Suite** web version 21.7.0 b6021aea87a5f683069efac15473e8028fd5b869
**OS** NixOS 21.03 unstable
**Device** TT 2.4.0 regular

**Comment by bosomt** [comment]
**QA NOK**

still present in current dev master


**Info:**
 - Suite version: web 21.7.0 (b0ea8be015a610b83246d99a57761105259ea84f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular

**Comment by sorooris** [comment]
@alex-jerechinsky Let's move to the next month's project please, thanks.

**Comment by jerechinsky** [comment]
Should be removed now, I believe.

**Comment by sorooris** [comment]
QA OK

It is finally gone! :tada: 
![image](https://user-images.githubusercontent.com/10185314/128176884-85adb3fb-e2f0-4350-a486-11ec10feb6bf.png)

Suite web version 21.8.1 8dfc3fbf
Browser: Chromium 92.0.4515.107
OS NixOS 21.05
Device TT 1.10.2
