### ISSUE TITLE
Recovery/dryrun dropdown menu not aligned

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3831]
**Describe the bug** 
See screenshots.  ̶B̶u̶g̶ ̶i̶s̶ ̶o̶n̶l̶y̶ ̶p̶r̶e̶s̶e̶n̶t̶ ̶i̶n̶ ̶l̶i̶g̶h̶t̶ ̶v̶e̶r̶s̶i̶o̶n̶ ̶o̶f̶ ̶S̶u̶i̶t̶e̶.
EDIT: i can see it in dark mode too, it was impossible to see it during day.
It's present in web and app version of suite.

**Steps to reproduce:**
1.  ̶S̶w̶i̶t̶c̶h̶ ̶o̶f̶f̶ ̶D̶a̶r̶k̶ ̶m̶o̶d̶e̶ ̶o̶f̶ ̶S̶u̶i̶t̶e̶ ̶
2. Start standard recovery or dry run of T1 device
3. Observe drop down word list during recovery

**Info:**
 - Suite version: web 21.6.1 (7d50da6b9fe39ddd934fdf6153b4c4afb2d7fd88)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.10.0 regular

**Screenshots:**
<img width="423" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120512202-097a9680-c3c3-11eb-987a-f012a774ae16.png">

<img width="473" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120512506-58283080-c3c3-11eb-802b-54fc60845620.png">

**Comment by tomasklim** [comment]
This is an old onboarding, right?

I think this should be fixed in the new one right? @slowbackspace

**Comment by bosomt** [comment]
@tomasklim 

it looks like this during recovery

<img width="479" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120704160-293ab900-c4ae-11eb-8f4b-0816bb07e92f.png">


and like this during dry run

<img width="747" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120704487-8c2c5000-c4ae-11eb-9bb4-02bbaa9e733c.png">

<img width="455" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120704604-b0882c80-c4ae-11eb-98c2-333bb2bf1954.png">


**Info:**
 - Suite version: web 21.7.0 (522bfe4f55dc599ecdb28bc7857748530eb2815b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.10.1 regular

**Comment by bosomt** [comment]
Guess it's not problem with alignment, it's part of design.
It's just missing borders of drop-down menu so it looks unaligned.


<img width="674" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120900754-75ad0280-c62e-11eb-85e2-aace09c1368e.png">

**Comment by bosomt** [comment]
**QA OK**

not bug but feature :)
New account has new modal and dry run drop-down is just border-less.

**Info:**
 - Suite version: desktop 21.8.0 (566ba345c50b6fd7e773a905d5d8f40c7f8056f2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model 1 1.10.1 regular
