### ISSUE TITLE
Fix depreacated KeyboardEvent.keyCode

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3839]
we have 8 occurrences mostly in `@trezor/components` package

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

![Screenshot from 2021-06-04 15-09-52](https://user-images.githubusercontent.com/3435913/120806666-6c953600-c547-11eb-8b3a-0a3abb3a3e91.png)

**Comment by TaseerAhmad** [comment]
I am on it.

**Comment by bosomt** [comment]
is there anything than needs to be tested by QA ? /except regress testing after freeze ? /

**Comment by karliatto** [comment]
@bosomt  there was no added functionality, just code improvements so regress testing should be enough. Right @matejkriz ?

**Comment by matejkriz** [comment]
yes, exactly, just regress testing (maybe with focus on using keyboard instead of mouse whenever possible..)
