### ISSUE TITLE
Ripple -> XRP

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#384]

**Comment by slowbackspace** [comment]
probably already done by defining `TR_NETWORK_XRP` message (https://github.com/trezor/trezor-suite/pull/442/commits/d8963e37c4221bdf3f5a85c5b93bcf94cdc54bf2)

**Comment by vladimirvolek** [comment]
![image](https://user-images.githubusercontent.com/3112191/64418293-068e2d00-d09b-11e9-8f92-6365eeb4902e.png)
