### ISSUE TITLE
ERC20 tokens transaction fees too low compared to Next wallet

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3846]
**Describe the bug**

See transaction fees screenshots compared with Next wallet.
When you send ETH fees are same, but when you try to send ERC0 tokens fees are completely different in Next wallet but same in Suite. 

**Steps to reproduce:**
1. Send ERC20 in Next wallet
2. Send ERC0 in Suite
3. Compare fees

**Info:**
 - Suite version: desktop 21.6.1 (4f358fd151fc1962f30f84a855b82213d958aae7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.10.1 regular

**Screenshots:**

_ERC20_
<img width="770" alt="Screenshot 2021-06-06 at 8 43 45" src="https://user-images.githubusercontent.com/31506317/120917388-eabc1e80-c6a6-11eb-864e-f3ab958e52cd.png">

<img width="809" alt="Screenshot 2021-06-06 at 8 41 29" src="https://user-images.githubusercontent.com/31506317/120917390-ebed4b80-c6a6-11eb-831b-eefc8b0a80a3.png">

_ETH_

<img width="820" alt="Screenshot 2021-06-06 at 8 57 56" src="https://user-images.githubusercontent.com/31506317/120917475-6b7b1a80-c6a7-11eb-9693-7c9775915d8e.png">

<img width="725" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120917570-daf10a00-c6a7-11eb-96e9-3c06536b4881.png">

**Comment by tsusanka** [comment]
@bosomt will the ERC-20 transaction go through or not?

**Comment by bosomt** [comment]
still pending after 48 hours

https://eth1.trezor.io/tx/0x08c551ff4b3654a0d483e009a4ca36fa340d701789b86ec1ab83b3ca6b84a549
https://eth1.trezor.io/tx/0x9fbf01f889f34d067fefbb9e1676fddeb171a350c38b7b9c298af280da37b732

ETH tx was confirmed in few hours

**Comment by tsusanka** [comment]
@szymonlesisz mentioned on Slack the fees in Next are hard-coded so it is not something we should compare Suite to.

However, if the TX is still not mined there might be smth wrong in the estimate I guess.

**Comment by szymonlesisz** [comment]
yes, we are investigating it with @martinboehm , it's not exactly suite related.
there is something wrong with blockbook backend (geth) which occasionally returns gas price as "0" instead of correct values.

![Screenshot from 2021-06-07 13-48-04](https://user-images.githubusercontent.com/3435913/121014804-add15400-c79a-11eb-9257-8ca366ad1cb2.png)

even if we catch this 0-value in suite and we will set it to the lowest possible (1) it may not be enough because average gas price is ~5-10

**Comment by szymonlesisz** [comment]
may be related to [this issue](https://github.com/ethereum/go-ethereum/pull/22722) 
we need to upgrade our backends first and see if it helps

**Comment by szymonlesisz** [comment]
this should be fixed here:
https://suite.corp.sldev.cz/suite-web/fix/3846/web/accounts/send/#/eth/0

Amount and recipient address **have influence** on calculated "Fee limit" in send form
"Gas limit" should never be 0 (like in screenshots above)

example scenarios:

- when using ERC20 set-max "Fee Limit" should be greater than when using lower amount (0.1 or lowest possible like 0.00001 - depending on how much decimals this token have)
- when using OWN address "Fee Limit" should be lower than when using "external address" (different account, or some exchange)


Pls compare results with mycrypto.com using exact same values (amounts and addresses)

**Comment by bosomt** [comment]
fix vs mycrypto comparison, same accounts, same coins

![image](https://user-images.githubusercontent.com/31506317/121209912-8900dd80-c87b-11eb-9ae7-32b14540e58c.png)
   

![image](https://user-images.githubusercontent.com/31506317/121210076-ac2b8d00-c87b-11eb-80c9-860a6687642c.png)

**Comment by martinboehm** [comment]
You are using TUSD (OLD) in mycrypto.com, please try with TUSD

**Comment by bosomt** [comment]
ok different token an latest staging ETH backend

![image](https://user-images.githubusercontent.com/31506317/121222316-bb640800-c886-11eb-9b70-1b2cfa08f031.png)

**Comment by szymonlesisz** [comment]
gas limit looks the same

**Comment by bosomt** [comment]
**QA OK**

yes it does and when it's not same it's lower on mycrypto side
see screenshot.


![image](https://user-images.githubusercontent.com/31506317/121223671-0fbbb780-c888-11eb-8f1e-aa0a9dfa2068.png)

**Info:**
 - Suite version: web 21.7.0 (5277e17560f96d1fbb307f0c555f671f4cc5444c)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular
