### ISSUE TITLE
Toooltip ask you to connect device even when connected

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3847]
**Describe the bug**
Tooltip ask you to connect device even when connected.
Im not sure if this is correct/expected behaviour, but i rather point it out.
It's present in web version 21.5.1 too /dark mode screenshot/

**Steps to reproduce:**
1. Connect your device/devices
2. Open Wallets modal
3. hover over `+ add hidden wallet`

**Info:**
 - Suite version: desktop 21.6.1 (4f358fd151fc1962f30f84a855b82213d958aae7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.10.1 regular

**Screenshots:**

<img width="739" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120918435-548af700-c6ac-11eb-8ec5-d817de1fa8f3.png">

<img width="739" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120918452-6a002100-c6ac-11eb-8ec9-2ebc2c5696dd.png">

<img width="586" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120918524-c5321380-c6ac-11eb-9e7d-d963d1a2755b.png">

**Comment by jerechinsky** [comment]
Let's remove the tooltip. @pingpwned

**Comment by Hermez-cz** [comment]
👍 If it's possible, I'd remove it when the device is connected and keep when disconnected. But even removing it entirely is better than the current confusing tooltip.

> Let's remove the tooltip. @pingpwned

**Comment by STew790** [comment]
**QA OK**

There is no tooltip when hovering over "Add hidden wallet".

**Info:**
 - Suite version: web 21.10.0 (33dc0f16010316d293fdeb4e262ac969c723985f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.3 regular

**Comment by wendys-cats** [comment]
**QA OK**

Tooltip not present when device is connected - OK
![image](https://user-images.githubusercontent.com/58593111/135818351-f6470a46-0a8c-4605-b4ee-9356f1c4be98.png)

Tooltip present when device is disconnected - OK
![image](https://user-images.githubusercontent.com/58593111/135818471-de0cfd36-3bff-477b-bb10-089ac600129e.png)



**Info**
**Suite:** 21.10.0 f14989d7ed4081ed45c65475c6aa85602ea217f5
**Browser:** Chrome 94.0.4606.61 (Official Build) (64-bit)
**OS:** Windows 10
**Device:** TT 2.4.2 public regular
