### ISSUE TITLE
Pin modal buttons layout

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3849]
**Describe the bug**
Buttons in PIN modal looks different (kinda broken) and goes blur after entering pin.

current develop vs current production
![Screenshot from 2021-06-07 12-10-30](https://user-images.githubusercontent.com/3435913/121004839-6c877700-c78f-11eb-915e-a066b3b08e01.png)
![Screenshot from 2021-06-07 12-10-18](https://user-images.githubusercontent.com/3435913/121004853-714c2b00-c78f-11eb-95d5-22abd8bb7477.png)

**Comment by jerechinsky** [comment]
Mine looks like this. I think @matej confirmed that this is not intended, so let's fix it. 
![pin](https://user-images.githubusercontent.com/75733878/122187214-20bf8680-ce8f-11eb-833f-427fef26d184.gif)

**Comment by jerechinsky** [comment]
This design is actually intended as I just found out by digging through a 3 week old slack [thread](https://satoshilabs.slack.com/archives/C01SXSHGK44/p1623060709004000).

Even the vertical paddings are fixed judging by my screencap. 

Sorry for disturbance everyone...
