### ISSUE TITLE
Do onboarding completely offline

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3850]
Add an ability to completely onboard yourself offline. In another words download Suite, turn off your internet and do onboarding offline. https://github.com/trezor/trezor-suite/issues/3738 is a prerequisite. After that is done maybe this will work "out of box".

**Comment by sorooris** [comment]
Could be improved upon by checking the internet connection status, just after completing onboarding and before executing discovery.

Currently an error message regarding all backends being down is displayed after completing onboarding completely offline and selecting an arbitrary wallet type (standard/hidden).
![image](https://user-images.githubusercontent.com/10185314/131657871-cc676d4b-1379-4172-9f05-37a8629101e4.png)

**Comment by tsusanka** [comment]
I think this is fine for now, the main thing it works! Great :tada:.
