### ISSUE TITLE
Missing links in Suite guide

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#3851]
**Describe the bug**
In the new Suite guide, there are missing links in the "Features" section of the guide. None of the points have functional links on them.

Info:
 - Suite version: desktop 21.6.1 (4f358fd151fc1962f30f84a855b82213d958aae7)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.0 regular

**Steps to reproduce:**
1. Open Trezor suite
2. Open the Suite guide
3. Try to click on any of the points in the "Features" section

**Expected result:**
At least the "Other resources" points should be links, as there is a mention of our Wiki and our trezor.io and satoshilabs.com page

**Actual result:**
None of the points in the "Features" section are clickable links.

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/121036696-293d0080-c7af-11eb-9758-b8a35a4ed0ed.png)

**Comment by tomasklim** [comment]
This is a problem with the content.

Links have to be in this format:
```
- Other resources
    - [Supported cryptocurrencies](https://trezor.io/coins/)
    - [Trezor Wiki](https://wiki.trezor.io/)
    - [Trezor.io](https://trezor.io/)
    - [Satoshilabs.com](https://satoshilabs.com/)
```
![Screenshot 2021-06-08 at 15 14 03](https://user-images.githubusercontent.com/33235762/121191339-2ce28d00-c86c-11eb-8aa6-1af8a46e1920.png)

They are just plain text now.

I will fix it in the project for next release, but for public launch it has to be fixed in GB. @goodhoko do you have access to fix it?

**Comment by goodhoko** [comment]
@tomasklim The current content is hardocded in Suite repo - it's not fetched from GitBook.

Before we start using content from GitBook we'll have to migrate it there first. I've created an issue for that: https://github.com/trezor/trezor-suite/issues/3863

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 21.7.0 (6796f451738b4cd59ecd9efb3257743bbe8398a1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular

**Comment by STew790** [comment]
**QA OK**

**Info:**

Suite version: desktop app 21.6.2 (4e29f3d)
Browser: -
OS: Windows 10
Screen: 1440x900
Device: model One 1.10.1 regular
