### ISSUE TITLE
Button in "Suggestion" section should say "Send feedback/suggestion"

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#3852]
**Describe the bug**
The button in the new "Suggestion" section in Suite should say "Send feedback (or suggestion)." instead of  "Send report" as it says now, which is the same as in the "Report a bug" section.

Info:
 - Suite version: desktop 21.6.1 (4f358fd151fc1962f30f84a855b82213d958aae7)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.0 regular

**Steps to reproduce:**
1. Go to the "Suggestion" section of the new Feedback or Suggestion section in Suite
2. The button says "Send report"

**Expected result:**
The button in the new "Suggestion" section in Suite should say "Send feedback (or suggestion)."

**Actual result:**
The button now says "Send report"

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/121038928-f3991700-c7b0-11eb-9a28-e793c30c06a4.png)

**Comment by jerechinsky** [comment]
@matejzak do you agree that it should say "Send feedback"/"Send suggestion" ?

**Comment by jerechinsky** [comment]
@matejzak @Hermez-cz please provide input when possible

**Comment by Hermez-cz** [comment]
@alex-jerechinsky discussed with UX, we should word the CTA "Submit" - that will even work consistently for Bugs and Suggestions.
Please mind translations.

Huh, in my case it's already worded "Submit" in English (Web app and Mac app 21.10.2.13755).
<img width="339" alt="image" src="https://user-images.githubusercontent.com/88533514/138467850-a0735234-82e5-4ed2-beeb-f76d91b37466.png"><img width="339" alt="image" src="https://user-images.githubusercontent.com/88533514/138467882-8406afa7-bffc-4b2f-9180-70b295e69b38.png">
(and Enviar for both options in ES)

However, not in Czech:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/88533514/138467956-1a8304d2-f0ff-4548-a57b-751417aca112.png"><img width="342" alt="image" src="https://user-images.githubusercontent.com/88533514/138467984-8fe71e91-43ba-415e-96b5-56e00c656fae.png">

**Comment by glacierbits** [comment]
@alex-jerechinsky Can you please change the Czech copy to just `Odeslat`? 🙏🏽

**Comment by STew790** [comment]
**QA OK**
Button now says correctly just "Submit" and in Czech, it is also correct "Odeslat"

![image](https://user-images.githubusercontent.com/48477147/149783158-d2594bd7-fc4a-4943-93ff-b663f8febf8e.png)

**Info:**
 - Suite version: web 22.1.1 (7e2101c6d91c14e6a0faba8b4057f04ba2422578)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.4 regular
