### ISSUE TITLE
Extend wiki information "how to run on Linux"

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3855]
I've tried to run suite app on two totally fresh instances of Linux (debian/centos)
in both cases i've ended up with error `The SUID sandbox helper binary was found, but is not configured correctly.`

It would be nice to extend the [wiki description](https://wiki.trezor.io/Apps:Trezor_Suite#How_to_run) how to deal with it

https://authmane512.medium.com/solve-the-suid-sandbox-helper-binary-was-found-but-is-not-configured-correctly-3-solutions-4f1425a9a76c

**Comment by tsusanka** [comment]
This is really weird, I have definitely successfully run Suite on clean Linux Mint and @trezor/qa would definitely report this (but yes they do not have clean installations). @prusnak do you by any chance understand the problem? I really do not want to add instructions to wiki until we understand the reasons well.

**Comment by prusnak** [comment]
Debian has extra security feature when running an AppImage file. One needs to add `--no-sandbox` to the commandline:

```
./foobar.AppImage --no-sandbox
```

Agree on documenting this on the wiki and/or directly on the download page.

**Comment by tsusanka** [comment]
Ah ok. I'm still a bit confused this does not occur on my Linux Mint (because it is Debian-based as well right?) but maybe this feature is kind of new? Anyway, @alex-jerechinsky please add the info on Wiki and feel free to close the issue then.

**Comment by prusnak** [comment]
> Linux Mint (because it is Debian-based as well right?)

It is debian based, but has different kernel configuration. This is a setting of the kernel that breaks things. Looking at szymon's post, this can be also fixed by using `sysctl kernel.unprivileged_userns_clone=1`

**Comment by tsusanka** [comment]
Thanks! So let's just add `On Debian and similar distributions you might need to add --no-sandbox` or similar and that's it.

**Comment by szymonlesisz** [comment]
not only debian, it happens to me on `centos` as well

for example `cypress` (testing environment) is solving it by adding `--no-sandbox` param automatically to every "linux-like" app

https://github.com/cypress-io/cypress/pull/5458/files

**Comment by jerechinsky** [comment]
updated https://wiki.trezor.io/Apps:Trezor_Suite
