### ISSUE TITLE
Missing Trezor picture during onboarding

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3856]
**Describe the bug**
Tested in application and in browser, both time missing Trezor model T graphics, other steps contains it.
21.5.1 **OK**
21.6.1 **NOK**

**Steps to reproduce:**
1. Connect device without firmware
2. Install firmware during on-boarding
3. Observe `Installation completed` screen

**Info:**
 - Suite version: web 21.6.1 (4f358fd151fc1962f30f84a855b82213d958aae7)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular

**Screenshots:**

![Screenshot_20210608_092238](https://user-images.githubusercontent.com/31506317/121142743-99459800-c83c-11eb-858a-14a5bc98f8e2.png)
![Screenshot_20210608_092532](https://user-images.githubusercontent.com/31506317/121142748-99de2e80-c83c-11eb-979f-c05e23122ae3.png)

**Comment by jerechinsky** [comment]
@bosomt Can you reproduce this even in 21.6.2 ?

**Comment by bosomt** [comment]
@alex-jerechinsky  i can't

so as soon we approve andrelease new onborading we can close this issue.


**Info:**
 - Suite version: web 21.6.2 (97d032adf84e5b7c5dd82fb3085fdeb4434ad7f8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.6 regular
