### ISSUE TITLE
Button with 100% width has too much space around icon

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#386]
<img width="320" alt="Screenshot 2019-08-09 at 13 15 05" src="https://user-images.githubusercontent.com/6961901/62775391-cb064000-baa7-11e9-88d2-0e71aae72fba.png">

It should be more like this

`|__________[icon]_[label]__________|`

**Comment by keip** [comment]
Add prop `fullWidth` which will set the width to 100%;
Fix centering icon and text when `fullWidth: true`

**Comment by slowbackspace** [comment]
> Add prop `fullWidth` which will set the width to 100%;
> Fix centering icon and text when `fullWidth: true`

We don't need additional prop for this. imo it is also a bad design. There is already a way to do full width button without a new prop called `css` (badumtss, but seriosly we can't make new prop for each css prop). So when we need full-width button we can easily style generic `Button` via styled-component wrapper ```styled(Button)`width: 100%;` ```. 

This issue is all about making the icon work the same way with fixed size just as with full-width buttons. It should be doable with css flexbox only.

(you basically wrap the icon and label in one container that will be centered in its parent (probably Button's wrapper), so when the button width is set to 100%, container with icon and label stays centered.
