### ISSUE TITLE
Migrate content to GitBook

### ISSUE THREAD

**Issue by goodhoko** [trezor/trezor-suite#3863]
In the first version of Guide we had [5 articles](https://github.com/trezor/trezor-suite/tree/e34d1748b5636fb064a860cd1b3f9fc2d480c87a/packages/suite-data/files/guide/en/trezor-suite) hardcoded into the suite repo.

Before we proceed with [fetching content from GitBook](https://github.com/trezor/trezor-suite/issues/3817) we need to migrate them to the GitBook.

@alex-jerechinsky we (devs) can certainly do this ourselves. It should take few minutes at worst. But it would be nice if this was done by someone who'll work with GitBook in future so that (s)he gets familiar with the process as early as possible. .)

Blocks #3817

cc @matejzak @tomasklim

**Comment by glacierbits** [comment]
Thanks @goodhoko! 

I will take care of it asap. Just to manage the expectations, I am afraid it will take us at least a week.

`It` meaning: 

- Define what the essential articles are (upgrade of the current ones needed - in terms of volume and quality)
- Re-write the actual articles + add new ones (sync with Ray & Anthony needed - aiming for 10 essentials posts) 
- Move it to Gitbook

**Comment by goodhoko** [comment]
@matejzak FIY I just filled GitBook with the current articles so that @tomasklim have a content to work/test against in https://github.com/trezor/trezor-suite/issues/3817.
