### ISSUE TITLE
Backup failed in the new onboarding [bug or feature?]

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#3864]
**Steps to reproduce:**
1. go to onboarding with fresh device (seen with t1 but probably does not matter)
2. disconnect during backup 

![image](https://user-images.githubusercontent.com/30367552/121224484-e64f5b80-c888-11eb-829d-f3424ff43e84.png)

I am not sure if the icon above "go to settings" button is expected? Maybe this is a feature, not a bug?

**Comment by mroz22** [comment]
The only problem was visual I think. That "alert" icon appeared HUUGEE to me.

**Comment by jerechinsky** [comment]
If the problem was that the icon was huge, then I believe this might've been fixed already.
