### ISSUE TITLE
Guide lamp icon on dark mode with white background

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3869]
after this change https://github.com/trezor/trezor-suite/pull/3854

guide lamp in dark mode has white background:

![Screenshot from 2021-06-09 08-50-08](https://user-images.githubusercontent.com/3435913/121307254-184fd480-c900-11eb-99a1-0059829f02a8.png)

**Comment by goodhoko** [comment]
This still applies on `develop`. I guess we'll need this file https://github.com/trezor/trezor-suite/blob/4bc2641fa41d0b2103ad6c43b0b2a5ba7bedfc40/packages/suite-data/files/images/suite/lamp.png but with a transparent background.

**Comment by matejzak** [comment]
I hope this (png, transparent background) export fixes it. Two different sizes, if it helps. 

<img width="15" alt="Lamp (1)" src="https://user-images.githubusercontent.com/29627086/121517105-dea5c900-c9e6-11eb-9d7a-32bc63492854.png">
![Lamp (2)](https://user-images.githubusercontent.com/29627086/121517106-df3e5f80-c9e6-11eb-95fb-b8c684c60bc1.png)

**Comment by glacierbits** [comment]
My bad, previous comment included png with white background. I am reaching out to designers for help (Ondra is off today).

**Comment by glacierbits** [comment]
Fixed 🙏🏽 

[lamp_no_bg.zip](https://github.com/trezor/trezor-suite/files/6631864/lamp_no_bg.zip)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.7.0 (b6021aea87a5f683069efac15473e8028fd5b869)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.0 regular

**Comment by wendys-cats** [comment]
**QA OK**

**Info:**

**Suite** version: web 21.7.0 b6021aea87a5f683069efac15473e8028fd5b869
**Browser:** Chromium Version 88.0.4324.182 (Official Build) (64-bit)
**OS:** NixOS 21.03 unstable
**Device:** model T 2.4.0 regular
