### ISSUE TITLE
Setup a linter for suite-data

### ISSUE THREAD

**Issue by goodhoko** [trezor/trezor-suite#3870]
The suite-data package now contains some non-trivial code. Setup a linting script similarly to how its done in other packages and invoke it in CI. This should prevent the most basic styling and semantic errors.

Could make sense to do along https://github.com/trezor/trezor-suite/issues/3812

**Comment by hynek-jina** [comment]
@matejkriz is this still valid?

**Comment by tsusanka** [comment]
@Nodonisko done right?

**Comment by matejkriz** [comment]
done
