### ISSUE TITLE
Message System config: WebUSB API not working on macOS in Google Chrome 91

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3874]
**Describe the bug**
WebUSB API is not working on macOS in Google Chrome 91 so users are not able to use the application without Bridge installed.

**Steps to reproduce:**
1. Have Google Chrome 91
2. Launch the app
3. Connect the device

**Expected result:**
Device is connected.

**Actual result:**
Device cannot be connected.

**Screenshots:**
https://user-images.githubusercontent.com/33235762/121348727-fae33080-c928-11eb-8dc9-e39d2e35a560.mov

**Comment by tomasklim** [comment]
![Screenshot 2021-06-11 at 14 44 14](https://user-images.githubusercontent.com/33235762/121690552-48e16b00-cac6-11eb-880a-487d4ded7da0.png)
![Screenshot 2021-06-11 at 14 46 21](https://user-images.githubusercontent.com/33235762/121690555-4a129800-cac6-11eb-95ed-60280591913a.png)

**Comment by tsusanka** [comment]
Config deployed to develop. That means this should be working on develop branches.

QA: please verify the message is displayed on MacOS on Chrome 91 and nowhere else without Bridge being installed. This applies for versions >=21.6.2.

**Comment by tsusanka** [comment]
QA: please when you start testing this on staging, ping me I will deploy the config.

**Comment by bosomt** [comment]
@tsusanka please deploy it, I don't see it now on / MacOS + Chrome 91 - Bridge setup/ staging

**Comment by tsusanka** [comment]
@bosomt deployed. Please also make a quick check that this does not affect production in any way. The warning will be displayed from 21.6.2 so it should not be displayed on production yet (as it has 21.6.1 currently).

**Comment by bosomt** [comment]
@tsusanka i can see it in Chrome 91

21.6.2
<img width="654" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/122213449-40fc3f00-cea9-11eb-92a9-576a272c8d99.png">

21.6.1
<img width="658" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/122213641-743ece00-cea9-11eb-8752-e29566171be6.png">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.7.0 (b0ea8be015a610b83246d99a57761105259ea84f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular

**Comment by sorooris** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/10185314/124591823-0a3c9780-de5d-11eb-9eb8-eca01415edf6.png)

Suite: web 21.7.0 b606e96f
Browser: Chrome 91.0.4472.114
OS: MacOS Big Sur 11.4
Device: model One 1.10.1
