### ISSUE TITLE
Clean up of css "z-index" attributes in the project

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3875]
Right now we use a wide spectre of values of css z-index attribute. One unaware change can cause problems in the whole project. Let's make one file with those z-indexes and let's specify what z-index should be used where. 

**Is your feature request related to a problem? Please describe.**
It can cause UI bugs in the future.

**Describe the solution you'd like**
Put z-index values into variables into a separate file.

**Comment by tomasklim** [comment]
@matejkriz

**Comment by bosomt** [comment]
@dahaca anything that needs to be checked by QA
or regular regress test after Suite freeze is enough ?
