### ISSUE TITLE
Account menu disappears when guide is open

### ISSUE THREAD

**Issue by goodhoko** [trezor/trezor-suite#3881]
discussed on standup today. cc @szymonlesisz @matejzak 

stems from https://github.com/trezor/trezor-suite/issues/3713#issuecomment-857716962

**Comment by goodhoko** [comment]
For the record, just found out the original [figma prototype](https://www.figma.com/proto/PVqDKfI5VvzbCJ5kheBPfS/Learn-%26-Discover?page-id=0%3A1&node-id=1%3A30&viewport=672%2C292%2C0.12598536908626556&scaling=min-zoom) actually hides the account menu when guide is opened so that's probably why it was implemented this way.

**Comment by glacierbits** [comment]
I remember specifically talking about this use case with Tom & Maros on the feature kickoff. It's here in [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/6086f65ed4cdec143d289fd5). 

In general, the prototypes are to be used with caution, they are not the "go-to pixel perfect" proposal because of many limitations Figma has with that regard. It's just to show the general feature look and feel and some specific animation. 

That being said, it's a good point. I will make sure to share this fact with the team.

**Comment by goodhoko** [comment]
Done in https://github.com/trezor/trezor-suite/pull/3887

@trezor/qa The desired behaviour is described in [this commit message](https://github.com/trezor/trezor-suite/pull/3887/commits/7ec61832847d30d7a35e861dc0498d82b2719b2a):

> fix(guide): #3881 Fix Suite layout for various widths and guide states
>
> The first version of Guide was implemented in a way that opening caused the accounts menu to hide.
> 
> Introduce new layout option to handle all combinations of widths and guide states.
>
> When the viewport width is XLARGE (+1200px) display menu, body and guide in three columns along each other.
>
> When the viewport is smaller than XLARGE but not larger than mobile (768-1200px) display menu and body in two columns unless the guide is open. In that case display body and guide in two columns and inline the menu on top of body.
>
> If the viewport is below the mobile threshold preserve the current state. That is inline the menu on top of body and hide guide completely.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.6.2 (97d032adf84e5b7c5dd82fb3085fdeb4434ad7f8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.0 regular

**Comment by STew790** [comment]
**QA OK**
**Info**

- Suite version: desktop 21.6.2 (4e29f3d6e527618670936bf6d1d3617b217be30c)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.0 regular

**Comment by sorooris** [comment]
**QA OK**

- XLarge viewport displays My accounts menu, body and guide in three columns along each other correctly
- smaller than XLarge viewport hides the My accounts menu correctly
- resize hides and displays the menu after reaching viewport breakpoint correctly

Suite: app 21.6.2 1ff4cbc
OS: Windows 10 19042.1052
Device: T1 1.10.1 [3204fd68](https://github.com/trezor/trezor-firmware/commits/3204fd68)
