### ISSUE TITLE
Manually added ERC20 tokens not present after wallet reload/reconnect

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3883]
**Describe the bug**
There is inconstancy between remembered coins and ER20 tokens  that were added manually.
When you reload wallet enabled/disabled coins are remembered but added ER20 tokens not. 

**Steps to reproduce:**

1. Add sUSD token
2. Balance shows
3. Eject Trezor, exit Suite
4. Open Suite, connect Trezor
5. Token is missing, needs to be added again, shows correctly
6. same issue after disconnecting again

Specific for sUSD token : 0x57ab1ec28d129707052df4df418d58a2d46d5f51

**Info:**
 - Suite version: desktop 21.6.1 (0ce310eb30cff6396b91939d3293b34e8e50d7c1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular

**Comment by szymonlesisz** [comment]
it's also not present if you add it but you don't have it.
example: 

add `0x4e3a36a633f63aee0ab57b5054ec78867cb3c0b8` to empty ETH account

notification says: "token added" yet nothing happened

then you can repeat this operation endlessly :)

-----
@bosomt
as far as i remember tokens are added "per account" not globally. your account was not remembered, therefore token is gone - maybe this is the reason?

**Comment by jerechinsky** [comment]
@szymonlesisz does this require better design to explain to the user that tokens are added "per account" and therefore are not remembered if the account isn't remembered?

**Comment by szymonlesisz** [comment]
@alex-jerechinsky  firstly we need decision:
- should custom token be available in other accounts? if not then yes, it will require some explanation in UI
- should custom token be visible even if it's 0-balance (see my comment above)

**Comment by forgiSL** [comment]
hi, just a side note, this came from support tickets. User has one account, remembering wallet did not work either. Token is not 0 balance it shows correct balance, but doesn't show at all after reconnecting.

**Comment by szymonlesisz** [comment]
@forgiSL i guess it is the same case as mentioned by @bosomt ?
wallet was not remembered > custom token is gone after disconnection because it was assigned to account which was "forgotten"

**Comment by bosomt** [comment]
@szymonlesisz yes it's same case, issue was created as "feature request" or "suggestion" from customer feedback.

**Comment by IAmIntractable** [comment]
> @szymonlesisz does this require better design to explain to the user that tokens are added "per account" and therefore are not remembered if the account isn't remembered?

I reported the issue and I have one ETH account only. The ETH account clearly has transactions for SUSD so the token needs to be resolved. I dont think adding ERC 20 tokens should be by account. There should be a master list stored by the suite for all ETH accounts. That list should also be editable by the user.

**Comment by IAmIntractable** [comment]
Not sure how this issue was labeled as a feature request. It's clearly a bug. Also need others to confirm it is not happening anymore with the latest suite release. For me, SUSD is remaining in the list between disconnections.

**Comment by IAmIntractable** [comment]
My Bad. I did not open this one but I did open one just like it.

**Comment by tomasklim** [comment]
It is not possible to add ERC20 token anymore, closing
