### ISSUE TITLE
Safety checks notification button doesn't work when im in device/settings

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3884]
**Steps to reproduce:**
1. go to `device/settings`
2. disable safety checks (prompt), confirm on device
3. then click on "change" button in notification
![Screenshot from 2021-06-10 16-01-09](https://user-images.githubusercontent.com/3435913/121539979-63eca600-ca06-11eb-9009-f255a750cabe.png)

**Expected result:**
either it should enable safety checks right away instead of redirection to `device/settings` (preferred) or should not be visible while i'm on `device/settings` route

**Actual result:**
button does nothing (actually it adds react render errors in console)

**Comment by goodhoko** [comment]
Thanks for reporting @szymonlesisz.

@matejzak Originally, the button was implemented to open the device settings. Could you elaborate what is the ideal behaviour of the button when the user already is in device settings?

**Comment by glacierbits** [comment]
Before #3889 gets implemented in some way or another (out of scope for this sprint), I suggest we change the copy on the button from `Change` to `Settings` at least indicating where is the user being taken (or why nothing happens if they are there already).

**Comment by goodhoko** [comment]
@matejzak Updated the copy in Crowdin.

@szymonlesisz The error in console seems to be another instance of the `Encountered two children with the same key` problem. @matejkriz mentioned that he might have a global fix for this. I'm not sure if it's worth tackling it within this issue.

I'll opportunistically close this. We'll need to sync Crowdin translations before the next release. @matejzak I'm waiting for a signal to do that. (as we agreed some time ago)
