### ISSUE TITLE
Link to given support page section at "device not recognized" instead of the support mainpage

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-suite#3886]
**Current state**
When the device is not recognized by Suite (see screen below) the support link links to main support page

**Suggested solution**
In such case it would be more Suitable to link directly to "device not recognized by wallet" section at https://trezor.io/support/technical/i-cannot-access-the-wallet/ 

![image](https://user-images.githubusercontent.com/37402530/121541793-e32ea980-ca07-11eb-8669-4b48db200cfe.png)

**Comment by dimasivan** [comment]
@yohaaan @matejzak Wouldn't it be too confusing for users to go to this support page which is about the Wallet (wallet.trezor.io) ? 
Don't want to make it more messy adding another path in the support page, but maybe this one can be edited to mention Suite as well? :pray:

**Comment by yohaaan** [comment]
@pingpwned  IIRC the troubleshooter should be updated with Suite content as well once it's launched. The truth is that at the moment there aren't many sections reflecting Suite due to lack of documentation, but that applies to the whole support page, not just the not recognized section. On the other hand, the troubleshooting tips are still relevant. It's rather a matter of the copy and form.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.7.0 (b0ea8be015a610b83246d99a57761105259ea84f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.10.1 regular

**Comment by STew790** [comment]
**QA OK**

Info:
 - Suite version: desktop 21.7.0 (550942dcbdb7b2ffc17519f8307a47f2d8d060f1)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.0 regular
