### ISSUE TITLE
Connect device (no longer modal)

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3888]
The new "onboarding" design was suppose to bring a new _startup_ page of the Suite application even for initialized devices. It seems that even though the New onboarding has been merged, the CTA to connect device for initialized devices is still a modal. It should be a full page instead. 

## Old (modal)

<img width="1224" alt="Screen Shot 2021-06-10 at 17 12 26" src="https://user-images.githubusercontent.com/29627086/121560596-964ed100-ca0f-11eb-8063-4b3926b0ec8b.png">

## New (full page) 

<img width="1778" alt="Screen Shot 2021-06-10 at 17 14 02" src="https://user-images.githubusercontent.com/29627086/121560642-a1a1fc80-ca0f-11eb-98db-c8c780d0599a.png">

**Comment by STew790** [comment]
**QA OK**![image](https://user-images.githubusercontent.com/48477147/124288297-4f0cb980-db51-11eb-9e90-9a33a6b0155b.png)
Info:
 - Suite version: desktop 21.7.0 (550942dcbdb7b2ffc17519f8307a47f2d8d060f1)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model 1 1.10.1 regular

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.7.0 (b606e96f4fa2418e0b44d54345c334e23a6a09de)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.1 regular
