### ISSUE TITLE
Anchor links

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3889]
_A link that helps to link to the content on the same page that has an anchor attached. It is a unique id (identifier) attached to the content block or specific element._ 

**Examplary problem:** User want to switch off Tor from the top navigation. They click on the chevron in the menu. Application Settings get opened, but they have no idea which element they should focus on or why they were sent to Settings to begin with.

Concrete cases (there might be more):
- [ ] Failed backup notif › General Settings › Backup 
- [x] Safety checks notification › Device Settings › Safety checks (#3884)
- [x] Transaction notification › Account › Overview › Transaction (#2208)
- [x] Tor navigation menu › General Settings › Tor  

TK - More are:
- [x] Check seed - Security features on dashboard
- [x] Change pin - Security features on dashboard
- [x] Failed backup in onboarding
- [x] Failed backup banner
- [X] Early access 

Design proposal (to be finalized): 

1. Click on the notifications opens the respective page
2. View automatically scrolls to the element in question 
3. Component gets highlighted (highlight disappears after scroll and/or action)

<img width="944" alt="Screen Shot 2021-06-10 at 18 29 59" src="https://user-images.githubusercontent.com/29627086/121570582-dfa41e00-ca19-11eb-8188-db1197958e13.png">

**Comment by matejkriz** [comment]
@matejzak FYI, we will try a solution that will work for links inside Suite itself only at first, because we are a bit afraid of e.g. transaction id visible in URL (stored in browser history and non-hideable by discreet mode). And it could also interfere with our accounts selection (e.g. `/web/accounts#/eth/0`)

 So it will not be possible to share a link, that could scroll.

We could find a solution for it later depending on the priority.

**Comment by tomasklim** [comment]
**Design info**
```
Light:
Oranžová: #C19009
Světle oranžová: #FDFBF5

Dark:
Oranžová: #9B813B
Světle oranžová: #272714
```

**Comment by tomasklim** [comment]
Added more cases into the first post. If I find some more, I will add them.

I did not implement `Failed backup notif › General Settings › Backup`. This notification is in onboarding and also inside app. The user is well informed when a backup fails and the user is also informed by a banner.

**Comment by tomasklim** [comment]
Followup:

- [x] messaging system

**Comment by STew790** [comment]
**QA OK**
OKed via PR here https://github.com/trezor/trezor-suite/pull/4781

**Info:**
 - Suite version: web 22.1.0 (45062edb383596efc81932b8fe6b51f124933b11)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular
