### ISSUE TITLE
csv/pdf export of transaction history is missing labels

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3892]
**Describe the bug**
CSV/PDF export of transaction history is missing labels + export form Suite is using am/pm even we already changed to 24 hour time.
see screenshot.

**Steps to reproduce:**
1. load wallet and saved labels in wallet
2. load wallet and saved labels in Suite
3. export transactions and compare exported files

**Info:**
 - Suite version: web 21.6.1 (0ce310eb30cff6396b91939d3293b34e8e50d7c1)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.0 regular

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/121692135-0fa9fa80-cac8-11eb-8253-46c3fc05938e.png)

**Comment by jerechinsky** [comment]
Closing in favor of #3185

**Comment by bosomt** [comment]
moving to approved, it will be solved by different issue https://github.com/trezor/trezor-suite/issues/3185
