### ISSUE TITLE
Token List Displays the Same Ticker Multiple Times

### ISSUE THREAD

**Issue by IAmIntractable** [trezor/trezor-suite#3898]
**When I review my token list in the suite, I note that it displays the same token twice. One entry shows the correct quantity but no value. The other entry shows the correct quantity and the correct value. The suite is likely displaying 2 entries because either:**

1)	There are two SNX contract addresses being reporting by CoinGecko 

2)	The Suite is seeing SNX in my ETH transactions under two different contract addresses

Note that in this case the latter is true because SNX used to be HAV before it was renamed. So, there are likely transactions under the older HAV contract and the new SNX contract in my ETH transactions. Nevertheless, the suite should not display SNX twice as the second entry implies an additional quantity of SNX that does not exist. I also want to mention that MetaMask displays the token list correctly further supporting the notion that the Suite is doing something wrong.

As a side note, I installed the Trezor suite on a brand-new Windows workstation over the weekend and after attaching my Trezor the token list was still wrong. So, the extra entry is not a consequence of me having added an SNX token address.

After giving the issue more thought I believe I understand what is going on to the point that I was able to define a new requirement that should mitigate the problem. 

**First, this is my interpretation of what your suite is currently doing when it displays the token list:**

1) Scans ETH address for tokens
2) Loops through each token
3) Find the token’s on CoinGecko and retrieves the coin price
	a) Display the token ticker
	b) Show the total tokens for the ticker 
	c) Displays a total value for the token
4) Moves to next token on the ETH address

This approach leads to the same ticker being displayed in the exact manner as I am seeing and supported by the attached picture.

**Second, this is what the suite should be doing when it displays the token list:**

1)	Scan ETH address and create an array of unique ERC20 tickers. One row per ticker
2)	Sort the array by the ticker
3)	Now rescan the transaction list for each Ticker and count the number of unique contract addresses associated with the Ticker
4)	Place the count in the array so that it appears in the same row as the Ticker

You now should have an array of Tickers and contact address counts like this:
BTC, 1
ADA, 1
SNX,2

5)	Process the ticker list to create the token list

If a Ticker has one and only one contract address:

6)	Find the ticker on CoinGecko and retrieve the coin price EVEN IF zero

7)	Now generate the Token List:

        a) Display the ticker
        b) Show the total tokens for the ticker 
        c) Display a total value for the ticker
        d) If no coin price was found at CoinGecko display a blank total value
 
If a Ticker has more than one contract address:

8)	Loop through each of the contract addresses in the ETH transaction list that are associated with the ticker

9)	Find the contract address that actually has a coin price on CoinGecko:

10)	Now generate the rest of the Token List:

        a) Display the ticker
        b) Show the total tokens for the ticker 
        c) Displays a total value for the token based upon the coin price you found in step 9
        d) If none of the contract addresses have a coin price then display a blank total value

**Outcome:**

This approach ensures that only one ticker is displayed in the token list for all tokens on the ETH address.

Attachments:
I have attached a screenshot of my token list where you can clearly see SNX listed twice and how it implies there are more than 6149 tokens. To reiterate, if Metamask can display the token list properly then the Trezor Suite should be able to do the same.

<img width="820" alt="Screen Shot 2021-06-09 at 10 51 52 AM" src="https://user-images.githubusercontent.com/85356294/121920990-93512a80-cd06-11eb-935c-49115932be65.png">

**Comment by bosomt** [comment]
@IAmIntractable so far we were not able to reproduce your issue, does the issue still persists?

can you please give us Eth address so we can import it to Trezor Suite and debug your problem ?

**Comment by IAmIntractable** [comment]
> @IAmIntractable so far we were not able to reproduce your issue, does the issue still persists?
> 
> can you please give us Eth address so we can import it to Trezor Suite and debug your problem ?

You're looking for my public ETH address. Is there any way I can provide without it being permanently displayed here?

**Comment by IAmIntractable** [comment]
I reported June 14 and gave you a ton of information. You can clearly see from the picture that SNX is displayed twice meaning that your code is not able to determine which one should not be displayed. I responded above to your question and 17 days later you have not responded. Is the cycle here that you pay attention to this once every 5 months? I spent a considerable amount of time conversing with your support people on this and in the end they said post here. Not an earth-shattering issue, but perhaps you take some time to respond to me and make a plan to resolve this?

**Comment by bosomt** [comment]
@IAmIntractable 

can i ask you to start Trezor Suite with ` --log-level=debug --log-write`  flags and attach log if possible ?
So far we were not able  to reproduce your issue.

**Comment by MiroslavProchazka** [comment]
@IAmIntractable please try on 24.3.4 as we've introduced recognized/unrecognized tokens feature this this should be solved.

**Comment by MiroslavProchazka** [comment]
@trezor/qa can you please verify this as well?

**Comment by bosomt** [comment]
@MiroslavProchazka i consider it fixed
