### ISSUE TITLE
Early Access Program

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3900]
**Design:** [Figma](https://www.figma.com/file/stayh4edU3aeLULpcvYSMu/Exploring-Settings?node-id=601%3A2)

**Spec:** [Notion](https://www.notion.so/satoshilabs/Early-access-program-4385b04f97114b3db6e1e3e0f0d1e036#2f20b677acbb4fc2a43d65296912a11c)

In Suite we will have a new feature: "Early access toggle". If enabled Suite will behave as when started with `--pre-release` flag. That means it will offer updates from Github that are marked as pre-release. Each new version will be released first as a pre-release. This new version will be offered for those with "Early access" on. After week, if no issues have been found we will make the release official.

**Comment by glacierbits** [comment]
Design linked at the description 🙏🏽

**Comment by matejkriz** [comment]
Notes for testing:
cc @bosomt @vdovhanych 

- We must never release testing pre-release with the higher version than the first release including EAP (22.1.1)!!
- We start using 0.X.X versions for testing purposes 
- To test auto-update FROM the new version we will release 0.X.X version from the same commit and verify the auto-update from it

### Scenarios:
- Join the EAP
  - with published newer pre-release on github
  - without existing pre-release version
     - publish the pre-release after joining the EAP and check again
     
- Leave the EAP
  - on the pre-released version
  - on the stable version
  
- pre-released version is published as production
 - user in EAP should not be affected
 
### What to check in every scenario:
 - Check for updates button
 - Current version in app info and Guide > Report Bug & Feedback  panel
 - The update dialogue on app start
