### ISSUE TITLE
Remove all closed beta code

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3901]
As we are killing beta-wallet.trezor.io we should remove all beta-related code. We will replace this by the #3900.

I believe we can also completely remove the `landing-page` package as it was used for the closed beta solely.

**Comment by goodhoko** [comment]
It would be nice if someone knowledgable of the codebase could outline the scope of this. I.e. I have no idea what "all closed beta code" can include or where should I look for it. Maybe @szymonlesisz may know better? 

I'll start digging into this either way a but advice on direction would be appreciated.

**Comment by jerechinsky** [comment]
That's very fair. I'll probably reassign to @szymonlesisz for his extensive knowledge of the codebase. Thank you, Jen.

**Comment by goodhoko** [comment]
@alex-jerechinsky That's not necessary nor what I wanted. .) I'll happily do this I'd just be glad for a more detailed description of what needs to be done.

**Comment by tsusanka** [comment]
I have searched through the code and did not find any more _beta_ occurrences. So hopefully this is good to go.
