### ISSUE TITLE
Latest release 21.6.2 offers outdated firmware versions

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3902]
**Describe the bug**
See screenshot, latest public version that we started to test contains outdated firmware versions.

**Steps to reproduce:**
1. Onboard device with 2.3.6 firmware
2. No firmware is offered

1. Try to update device with 2.4.0 firmware 
2. Older than 2.4.0 firmware is offered

**Info:**
 - Suite version: desktop 21.6.2 (97d032adf84e5b7c5dd82fb3085fdeb4434ad7f8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.0 regular

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/122046494-4725e900-cddf-11eb-88f0-d9f6b878b354.png)
![image](https://user-images.githubusercontent.com/31506317/122046742-93712900-cddf-11eb-82d3-e72400adc959.png)

**Comment by tsusanka** [comment]
@szymonlesisz I guess this is because we have not published Connect right? So I will simply cherry-pick https://github.com/trezor/trezor-suite/commit/0ce310eb30cff6396b91939d3293b34e8e50d7c1 ? Is there a reason not to push it to `develop` directly btw?

**Comment by szymonlesisz** [comment]
exactly,  cherrypick should be enough

**Comment by tsusanka** [comment]
And I can do it to `develop`?

**Comment by szymonlesisz** [comment]
exactly, cherrypick **to develop** should be enough

**Comment by tsusanka** [comment]
Closed by 3fad508ccee65687b2921a5a752803ed30a6f90b.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.6.2 (4e29f3d6e527618670936bf6d1d3617b217be30c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model One 1.10.1 regular
