### ISSUE TITLE
ETH compose transaction - handle errors returned by estimateFee method

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3905]
handle [errors](https://github.com/ethereum/go-ethereum/blob/c503f98f6d5e80e079c1d8a3601d188af2a899da/core/error.go) returned by `estimateFee` [method ](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts#L123) (related https://github.com/trezor/trezor-suite/issues/3283)

**Comment by alex-jerechinsky** [comment]
Moving to product column so product team can prioritize it.

**Comment by tomasklim** [comment]
closing as duplicate of https://github.com/trezor/trezor-suite/issues/3283
