### ISSUE TITLE
Wallet cannot be renamed

### ISSUE THREAD

**Issue by goodhoko** [trezor/trezor-suite#3908]
**Describe the bug**
When I try to rename a hidden wallet, nothing happens.

**Info:**
 - Remembered Wallet: yes
 - Suite Version: web, 0ce310eb30cff6396b91939d3293b34e8e50d7c1
 - Browser: Firefox 89.0
 - OS: macOS, M1 MB air
 - Firmware Version: TT , https://github.com/trezor/trezor-firmware/commit/ea3596ad8, setup with a shamir seed

**Steps to reproduce:**
1. Open the "wallets" modal by clicking on the device button in top-left corner.
2. Click on the "rename" button that appears on hover next to a hidden wallet name.
3. Loading wheel appears, Trezor screen shows "please wait" for a brief while and then nothing happens.

**Expected result:**
It is possible to change the name.

**Actual result:**
Nothing happens.

**Screenshots:**
https://photos.app.goo.gl/GgEp5ER9NcfCArzh8

**Comment by jerechinsky** [comment]
@trezor/qa could you please try to replicate ?

**Comment by bosomt** [comment]
i think it was already fixed here, https://github.com/trezor/trezor-suite/issues/3644
but i will check it ;)

**Comment by bosomt** [comment]
**QA OK**

I was able to change name of both wallets BUT first i hat to enable labelling on both devices

<img width="361" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/125739356-67786ca2-0105-4721-b66e-9600b1cab6ed.png">


**Info:**
 - Suite version: desktop 21.7.1 (24cc565a3badd85ab48b30348022471dfd85f90e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.1 regular

**Comment by bosomt** [comment]
**QA OK**

<img width="361" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/128854757-1951dc37-871a-4565-9405-280bd5152721.png">


**Info:**
 - Suite version: desktop 21.8.1 (e25dcfce1f3b57cbf3d4bf194b3b5d58499abaf5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.2 Bitcoin only
