### ISSUE TITLE
Huge icon during onboarding

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3910]
**Describe the bug**
Huge icons are back and it appeared in newly designed onboarding.
I tested new onboarding multiple times but saw it for first time /at least in recent time/
I was able to replica it and record it. See video link.

**Steps to reproduce:**
1. Start suite that includes new onboarding
2. Disconnect device during seed backup
3. Reconnect it and observe

**Info:**
 - Suite version: desktop 21.7.0 (6796f451738b4cd59ecd9efb3257743bbe8398a1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular

**Screenshots:**

**https://youtu.be/cKRmzC0GJM0**

<img width="1303" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/122408676-da4b5400-cf82-11eb-9f3c-31864e31e31e.png">

**Comment by bosomt** [comment]
**QA OK**

<img width="489" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/123141974-41707900-d459-11eb-90a5-c68b7a73b062.png">


**Info:**
 - Suite version: web 21.7.0 (b0ea8be015a610b83246d99a57761105259ea84f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.10.1 regular

**Comment by zmluvny-jednorozec** [comment]
**QA OK**
- no more huuuge icons. 

Info:
**Suite** app version 21.7.0 c6316619a13802197a5a58c0fc1f39aae18db1a7
**OS** Windows 10 Version 10.0.19042.1052
**Device** TT 2.4.0 regular

![image](https://user-images.githubusercontent.com/59280808/123630546-f322f780-d815-11eb-9b0e-283dedfa8d61.png)

**Comment by wendys-cats** [comment]
**QA OK**
- no more huuuge icons. 

**Info:**
**Suite** app version 21.7.0 c6316619a13802197a5a58c0fc1f39aae18db1a7
**OS** Windows 10 Version 10.0.19042.1052
**Device** TT 2.4.0 regular

![image](https://user-images.githubusercontent.com/59280808/123630546-f322f780-d815-11eb-9b0e-283dedfa8d61.png)
