### ISSUE TITLE
Trezor model T hologram displayed during onboarding even when model One connected

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3913]
**Describe the bug**
Trezor  T hologram displayed during onboarding even when Trezor model One is connected.

**Steps to reproduce:**
1. Start Suite 21.6.2
2. Connect not initialized device model One 
3. Hover over hologram tooltip

**Info:**
 - Suite version: desktop 21.6.2 (c0e30df7aa3c7b37e6f0a19b5201744a5de66a90)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.0 regular

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/122533269-a5daa500-d021-11eb-975b-81777a5f00d0.png)

**Comment by tomasklim** [comment]
@bosomt could you please test it once more? I cannot replicate. Moreover, you have `Device: model T 2.4.0 regular` in the info.

**Comment by tomasklim** [comment]
![Screenshot 2021-06-22 at 9 44 02](https://user-images.githubusercontent.com/33235762/122885354-4d681800-d33f-11eb-8e76-13aa1ab89ce5.png)
![Screenshot 2021-06-22 at 9 50 14](https://user-images.githubusercontent.com/33235762/122885364-4f31db80-d33f-11eb-980d-f5f8190e2012.png)

**Comment by bosomt** [comment]
**QA OK**

sorry about confusion with firmware version, Yes I checked it multiple times with model One and it really showed model T hologram.
But I'm glad that it works with latest version that we received last night.
Is it possible that incorrect hologram was only displayed when you connected device with old firmware ? 

**Info:**
 - Suite version: desktop 21.6.2 (1ff4cbc91f640b645aa72c59047ffeff01819b1b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model One 1.10.1 regular

**Comment by bosomt** [comment]
**QA NOK**

I just unpacked fresh device that our customers are currently receiving and it shows model T hologram ;)
It's in deed problem with devices with older bootloader /older but currently shipped to cutomers/

![image](https://user-images.githubusercontent.com/31506317/122888001-b781bc80-d341-11eb-8cfd-5ca61405e891.png)


**Info:**
 - Suite version: desktop 21.6.2 (1ff4cbc91f640b645aa72c59047ffeff01819b1b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440

edit: attached Suite log 
[trezor-suite-log-1624348795463.txt](https://github.com/trezor/trezor-suite/files/6692496/trezor-suite-log-1624348795463.txt)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.7.0 (d1f46900b29015f165fcc20937538222a0c4cf6c)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model 1 1.4.0 BL

**Comment by wendys-cats** [comment]
**QA OK**

Hologram displayed for T1 is correct.

**Info:**

**Suite version:** app 21.7.0 c6316619a13802197a5a58c0fc1f39aae18db1a7
**OS**: Windows Version 10.0.19042.1052
**Device**: T1 1.4.0 BL and T1 1.10.0 BL
