### ISSUE TITLE
Firmware update says already updated to latest firmware even when device has old firmware

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3914]
**Describe the bug**

When trigger firmware update manually from Suite seeings it says already updated to latest firmware even when device has old firmware.
+ There is no message about availability of new firmware in application or during onboarding.

`Your device is already updated to latest firmware. You may reinstall the firmware if needed.`

**Steps to reproduce:**
1. Connect initialized device with 1.6.2 firmware
2. Start and finish onboarding 
3. Start firmware update manually

**Info:**
 - Suite version: desktop 21.6.2 (c0e30df7aa3c7b37e6f0a19b5201744a5de66a90)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.0 regular

**Screenshots:**

Incorrect text
![image](https://user-images.githubusercontent.com/31506317/122534645-074f4380-d023-11eb-91c9-97a1e162659c.png)

No message about firmware update 
![image](https://user-images.githubusercontent.com/31506317/122535355-c73c9080-d023-11eb-8834-4d2df360d9e3.png)

**Comment by jerechinsky** [comment]
@bosomt could you please try to find out what are the exact differences between this case and for example #3911. Here it says `Your device is already updated to latest firmware. You may reinstall the firmware if needed.` while there it says `Your device has firmware that is no longer supported. You will need to update it`. Is the firmware version the only difference? This leads me to believe that this is not a copy issue but some sort of logic issue.

**Comment by bosomt** [comment]
@alex-jerechinsky 

I tried to connect device whit 1.9.4 firmware and I have same result. So it doesn't look like problem with old device update logic.
It says `Your device is already updated to latest firmware` again before update is started.


![image](https://user-images.githubusercontent.com/31506317/122903187-742e4a80-d34f-11eb-9930-707063f6b072.png)

**Comment by jerechinsky** [comment]
Thank you @bosomt. 

For now I updated the copy to be less confusing. @matejkriz could you please try to find out why is Suite showing the `reinstall` modal and not `update`? I'm not sure what was the initial purpose of the `reinstall` modal. In crowdin, I see the `reinstall` string as `TR_FIRMWARE_REINSTALL_FW_DESCRIPTION` while I would be expecting so see `TR_FIRMWARE_NEW_FW_DESCRIPTION` as 1.9.4 to 1.10.1 is an upgrade.

**Comment by matejkriz** [comment]
> Thank you @bosomt.
> 
> For now I updated the copy to be less confusing. @matejkriz could you please try to find out why is Suite showing the `reinstall` modal and not `update`? I'm not sure what was the initial purpose of the `reinstall` modal. In crowdin, I see the `reinstall` string as `TR_FIRMWARE_REINSTALL_FW_DESCRIPTION` while I would be expecting so see `TR_FIRMWARE_NEW_FW_DESCRIPTION` as 1.9.4 to 1.10.1 is an upgrade.

It was a logic issue, wrong condition.

**Comment by matejkriz** [comment]
> No message about firmware update
> ![image](https://user-images.githubusercontent.com/31506317/122535355-c73c9080-d023-11eb-8834-4d2df360d9e3.png)


Because "No backup" banner has priority 70 but "Update available" banner has priority 10 - only one of them could be shown.

**Comment by matejkriz** [comment]
@alex-jerechinsky please get back the original copy for TR_FIRMWARE_REINSTALL_FW_DESCRIPTION

**Comment by jerechinsky** [comment]
Will do. Thank you. @matejkriz

**Comment by bosomt** [comment]
**QA OK**

<img width="468" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/125193714-2d48bc00-e24e-11eb-9180-a35e21adffbd.png">

**Info:**
 - Suite version: web 21.7.1 (ca85ae5c485fd0291952f50bc9d7a06076fddaa4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.3.4 regular

**Comment by STew790** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.7.1 (ca85ae5c485fd0291952f50bc9d7a06076fddaa4)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.6 regular

![image](https://user-images.githubusercontent.com/48477147/125303397-0f05bd80-e32d-11eb-9648-3306833e8a66.png)
