### ISSUE TITLE
Suite crashes when you connect device with 1.6.0 firmware when asked to connect device

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3915]
**Describe the bug**
Suite crashes when you connect device with 1.6.0 firmware when asked to connect device.
It's happening in Windows/Linux and macOS too.
When you connect it during onboarding of fresh Suite it asks you to install 1.6.3.
When you connect it when Suite is already started it crashes. You need to see old modal connect your device and not new modal from onboarding.
Logs from Linux attached. 

**Steps to reproduce:**
1. Start suite
2. Connect device with fw 1.6.0 when asked to connect
3. Observe.

**Info:**
 - Suite version: desktop 21.6.2 (c0e30df7aa3c7b37e6f0a19b5201744a5de66a90)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model One 1.6.0 regular BL 1.3.1

**Screenshots:**

[trezor-suite-log-1624014654740.txt](https://github.com/trezor/trezor-suite/files/6676657/trezor-suite-log-1624014654740.txt)
[trezor-suite-log-1624014775225.txt](https://github.com/trezor/trezor-suite/files/6676658/trezor-suite-log-1624014775225.txt)

Linux
![image](https://user-images.githubusercontent.com/31506317/122552774-058f7b00-d037-11eb-8cbe-b918c84d766e.png)

Windows 10

<img width="593" alt="image" src="https://user-images.githubusercontent.com/31506317/122552812-13450080-d037-11eb-8b7d-f0719f02dcd7.png">

**Comment by tsusanka** [comment]
Could you please test whether this is a regression from Suite version 21.6.1 or 21.5.1?

**Comment by bosomt** [comment]
@tsusanka 21.5.1 "works" as expected, this was common issue with unsupported firmware, now it just crashes

<img width="558" alt="image" src="https://user-images.githubusercontent.com/31506317/122566841-4e036480-d048-11eb-8c8b-4f29cc9b634c.png">

**Comment by bosomt** [comment]
@tsusanka see my old issue https://github.com/trezor/trezor-suite/issues/3181

**Comment by tsusanka** [comment]
@bosomt could you prepare the device with 1.6.0 to @matejkriz? We do not have 1.6.0 in trezor-user-env unfortunately.

**Comment by matejkriz** [comment]
It wasn't only desktop issue nor only 1.6.0 firmware issue - any firmware that requires upgrade on both platforms (native/browser) could do the crash. Fix is on the way (in the review).

**Comment by bosomt** [comment]
**QA OK**

Suite offers update to 1.6.3 /see https://github.com/trezor/trezor-suite/issues/3911 /
But it doesn't crash anymore

**Info:**
 - Suite version: desktop 21.6.2 (1ff4cbc91f640b645aa72c59047ffeff01819b1b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440

```
Features (135 bytes) {
    bootloader_hash: 32 bytes 0xafb4cf7a4a5796100ed5416b75121bc71008c2a2fd5449bd8f63cc22a6a7d680,
    device_id: 'C893A655C37A35C6CCB37B45',
    flags: 0,
    imported: False,
    initialized: True,
    label: 'My Trezor',
    major_version: 1,
    minor_version: 6,
    needs_backup: True,
    passphrase_protection: False,
    patch_version: 0,
    pin_protection: False,
    revision: 20 bytes 0x723cf295a72ce07b96047901bb8c2e461a2488f8,
    unlocked: False,

Features (30 bytes) {
    bootloader_mode: True,
    firmware_present: True,
    major_version: 1,
    minor_version: 5,
    patch_version: 0,
    vendor: 'bitcointrezor.com',

```

**Comment by bosomt** [comment]
**QA OK**

Suite offers update to 1.6.3 and updates device over and over again /see https://github.com/trezor/trezor-suite/issues/3911 /
But it doesn't crash anymore

**Info:**
 - Suite version: desktop 21.6.2 (1ff4cbc91f640b645aa72c59047ffeff01819b1b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440

```
Features (135 bytes) {
    bootloader_hash: 32 bytes 0xafb4cf7a4a5796100ed5416b75121bc71008c2a2fd5449bd8f63cc22a6a7d680,
    device_id: 'C893A655C37A35C6CCB37B45',
    flags: 0,
    imported: False,
    initialized: True,
    label: 'My Trezor',
    major_version: 1,
    minor_version: 6,
    needs_backup: True,
    passphrase_protection: False,
    patch_version: 0,
    pin_protection: False,
    revision: 20 bytes 0x723cf295a72ce07b96047901bb8c2e461a2488f8,
    unlocked: False,

Features (30 bytes) {
    bootloader_mode: True,
    firmware_present: True,
    major_version: 1,
    minor_version: 5,
    patch_version: 0,
    vendor: 'bitcointrezor.com',

```
