### ISSUE TITLE
labelling is gone when switching from hidden to standard wallet

### ISSUE THREAD

**Issue by maravac** [trezor/trezor-suite#3919]
**Describe the bug**
When I switch from hidden to standard wallet, then all labels (custom labels of my transactions) and custom account names are gone.

**Info:**
 - Remembered Wallet: yes
 - Suite Version: Windows app v. 21.5.1
 - OS: Windows 10 Pro 21H1
 - Bridge: not sure
 - Firmware Version: Trezor T fw 

**Steps to reproduce:**
1. switched from standard to hidden wallet
2. switched from hidden to standard walled
3. 

**Expected result:**
labels and custom names should not disappear

**Actual result:**
labels and custom names disappear or reset to a default ones

**Screenshots:**

**Note(s):**

**Comment by bosomt** [comment]
closing in favour of https://github.com/trezor/trezor-suite/issues/3364
