### ISSUE TITLE
Connecting to a custom btc full node (f.e. Umbrel)

### ISSUE THREAD

**Issue by maravac** [trezor/trezor-suite#3920]
Please, would it be possible to add a new features and functions to a TREZOR hw wallet or Trezor Suite so it could connect to a custom full node? I am using my own Umbrel btc full node running on Raspberry Pi4 in my local home network and it would be great to connect somehow the TREZOR to this full node.
Thank you.

**Comment by tsusanka** [comment]
Yes, this will be soon possible via Electrum Server support. Tracked in #2737.

**Comment by maravac** [comment]
Skvělé, díky za zprávu. Kdy to asi tak bude?

**Comment by tsusanka** [comment]
[Roadmap](https://github.com/orgs/trezor/projects/28)

**Comment by maravac** [comment]
SUPER!
