### ISSUE TITLE
Sentry: add source maps

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3927]
To make solving issues in Sentry easier, we should solve a problem with missing source maps in Sentry.

We can upload source maps [manually](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/) or add a plugin to webpack config and it will be solved [automatically](https://docs.sentry.io/platforms/javascript/sourcemaps/) on each release.

**Comment by matejkriz** [comment]
I just came across this https://github.com/trezor/trezor-suite/blob/develop/docs/misc/notes.md#upload-source-maps-to-sentry
