### ISSUE TITLE
T1 bootloader instruction text vs animation inconsistency

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3938]
**Describe the bug:**
The animation shows that only 1 button (on T1 >1.8.0) should be pressed to get into bootloader, but the text says to press both.

**Steps to reproduce:**
1. Update firmware
2. Read instructions

**Screenshots:**
<img width="522" alt="Screenshot 2021-06-24 at 9 36 56" src="https://user-images.githubusercontent.com/33235762/123242464-57764c00-d4e2-11eb-979a-222502d33d5f.png">

**Comment by sorooris** [comment]
**QA OK**
 1.5.2 | 1.10.0
 -|-
![image](https://user-images.githubusercontent.com/10185314/123830663-cc42ef00-d903-11eb-87e4-4bc566698a0a.png)|![image](https://user-images.githubusercontent.com/10185314/123831840-05c82a00-d905-11eb-8d0a-13bee41fa9cd.png)

Suite: web 21.7.0, develop 550942d
Browser: Chromium 91.0.4472.77
OS: Nixos 21.05
Devices: T1 1.5.2 & 1.10.0
