### ISSUE TITLE
New onboarding - install firmware - confirm on device missing

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3940]
**Describe the bug**
The user is not informed about the fact, that he has to confirm the installation of firmware on device in onboarding.

**Info:**
 - Firmware Version: Trezor T 

**Steps to reproduce:**
1. Have TT without firmware
2. Open Suite
3. Get to install firmware step

**Actual result:**
?Sometimes? It is required to confirm installation of fw on device. However, there is no prompt to confirm installation on the device. Loader is incrementing but device is waiting for user.

It is cropped but there is no Confirm on Trezor.
![IMG_3585 2](https://user-images.githubusercontent.com/33235762/123246814-7ecf1800-d4e6-11eb-8fa1-83f167803a67.jpg)

**Expected result:**
The loader is in 0% and there is a prompt to confirm installation on the device.

Firmware update modal:
<img width="645" alt="Screenshot 2021-06-24 at 10 09 59" src="https://user-images.githubusercontent.com/33235762/123246828-8393cc00-d4e6-11eb-94ee-894daee8a626.png">

**Comment by jerechinsky** [comment]
@trezor/qa have you encountered this recently?

**Comment by sorooris** [comment]
Not afaik - will retest.

**Comment by sorooris** [comment]
@tomasklim I'm struggling to replicate the confirmation screen on device with a model T without firmware - any clue how'd you achieved that? The only instance i could display a confirmation screen on device was when updating from an older firmware.

**Comment by tsusanka** [comment]
@wendys-cats please retest with TT with old firmware installed (update). We want to know if there is a confirmation in Suite along with the confirmation on the device.

**Comment by wendys-cats** [comment]
QA OK, closing this issue, it is no longer present in Suite, Progress bar will appear only after device prompt for FW installation is dealt with by user.

**Info:**
**OS:** Windows 10
**Browser:** Version 94.0.4606.81 (Official Build) (64-bit)

**21.10.2 APP (trezord 2.0.31)**
2.0.5 -> 2.1.1 OK progress bar is not visible before device prompt is dealt with
2.1.1->2.4.2 OK progress bar is not visible before device prompt is dealt with
2.1.0->2.4.2 OK progress bar is not visible before device prompt is dealt with
2.3.0->2.4.2 OK progress bar is not visible before device prompt is dealt with
1.10.1->1.10.3 OK progress bar is not visible before device prompt is dealt with

**21.10.2 WEB (trezord 2.0.27)**
20.5->2.1.1 OK progress bar is not visible before device prompt is dealt with
2.1.1->2.4.2 OK progress bar is not visible before device prompt is dealt with
2.1.0->2.4.2 OK progress bar is not visible before device prompt is dealt with
2.3.0->2.4.2 OK progress bar is not visible before device prompt is dealt with
1.10.1->1.10.3 OK progress bar is not visible before device prompt is dealt with

**21.10.2 WEB (WEBUSB)**
20.5->2.1.1 OK progress bar is not visible before device prompt is dealt with
2.1.1->2.4.2 OK progress bar is not visible before device prompt is dealt with
2.1.0->2.4.2 OK progress bar is not visible before device prompt is dealt with
2.3.0->2.4.2 OK progress bar is not visible before device prompt is dealt with
1.10.1->1.10.3 OK progress bar is not visible before device prompt is dealt with


For comparison 21.5.1 - also does not show the progress bar before prompt is dealt with, but also does not show the percentage
![image](https://user-images.githubusercontent.com/58593111/138245842-ebdc548d-4819-414a-9671-cfb6cd53bc04.png)
