### ISSUE TITLE
Transaction with bumped fees don't disappear from the list

### ISSUE THREAD

**Issue by przlada** [trezor/trezor-suite#3941]
**Describe the bug**
After bumping fees, a new transaction (with updated fees) appears on the transaction list but the previous (one present before fees bump) won't disappear. The previous (unconfirmed) transaction is still present on the send transaction list even after the new transaction is confirmed. The previous transaction disappears from the transaction list after the `trezor-suite` app restart. 
The observation was made on the ETH account.

**Info:**
 - Suite Version: desktop 21.6.1, [commit](https://github.com/trezor/trezor-suite/commit/0ce310eb30cff6396b91939d3293b34e8e50d7c1)

**Steps to reproduce:**
1. Create new ETH send transaction
2. Click `bump fees` on the transaction list
3. Update fees
4. Now two unconfirmed send transactions, with different fees, are present on the list
5. After a transaction with higher fees is confirmed, one with lover fees is still present on the list as a pending send transaction

**Comment by bosomt** [comment]
**QA OK**

i was not able to reproduce issue, previous transaction disappears and new updated tx is present.
Same for sending and receiving account.


![image](https://user-images.githubusercontent.com/31506317/126648523-dc1b4509-a5ad-403b-9b16-50fbb7574a36.png)

![image](https://user-images.githubusercontent.com/31506317/126648655-8c415568-4738-4fe4-8a0b-6322057d7e36.png)

![image](https://user-images.githubusercontent.com/31506317/126648924-07834d68-02c4-49d5-be6e-057cfd045132.png)


**Info:**
 - Suite version: desktop 21.8.0 (566ba345c50b6fd7e773a905d5d8f40c7f8056f2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model 1 1.10.1 regular
