### ISSUE TITLE
New onboarding - install firmware fails UI

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3942]
**Describe the bug**
When the installation of fw in new onboarding fails, user can retry the installation. However, when device is dead, it looks like that it is doing something, but it does not.

**Info:**
 - Firmware Version: T1

**Steps to reproduce:**
1. Device without fw
2. Install fw in onboarding
3. Fail installation of fw
4. Hit retry

**Expected result:**
I should not be able to retry installation when a device is dead.

**Actual result:**
I can retry installation and the installation progress is incrementing.

**Screenshots:**
![IMG_3584 2](https://user-images.githubusercontent.com/33235762/123248386-28fb6f80-d4e8-11eb-9e29-719cb67c37a5.jpg)

**Comment by jerechinsky** [comment]
@mroz22 is it technically possible to fix this?

**Comment by mroz22** [comment]
What does dead device mean? Red screen of death? If yes then we do not have any information about this available. We probably only got something like device disconnected error from TrezorConnect.

So the goal here is to identify why RSOD happened. Was it hardwarware malfunction (rare but possible) or did we (suite) somehow contribute to this (possibly but unlikely)

**Comment by tsusanka** [comment]
Alex will discuss with @tomasklim if this issues still persists.
