### ISSUE TITLE
New Onboarding: Copy improvements link to support

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3944]
**Describe the bug**

See https://github.com/trezor/trezor-suite/issues/3886 and https://github.com/trezor/trezor-suite/issues/3730#issuecomment-867576763

Please consider to change link to support
Current Contact support leads to https://trezor.io/support/
maybe you can change it to https://trezor.io/support/technical/i-cannot-access-the-wallet/ ?

**Info:**
 - Suite version: web 21.7.0 (89aee5512ea0059de309935684b5be5fb3b1843b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.10.1 regular

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/123259745-1b98b200-d4f5-11eb-82b6-59b9a53aabf5.png)

**Comment by hynek-jina** [comment]
Related to: https://github.com/trezor/trezor-suite/issues/3971

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.4.0 (449e0c62f08fd7482397da775f20ed1a4c8a5432)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: 
 - Transport: BridgeTransport 2.0.33
