### ISSUE TITLE
ReferenceError: Can't find variable: HTMLAnchorElement

### ISSUE THREAD

**Issue by hiteshpanwar8926** [trezor/trezor-suite#3947]
Getting following error while trying to run a dev build for ios (yarn suite:dev:ios).

ReferenceError: Can't find variable: HTMLAnchorElement
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

**Info:**
 - Remembered Wallet: yes/no
 - Suite Version: 21.7.0
 - Browser: , version
 - OS:MacOS Big Sur, build
 - Bridge: build version
 - Firmware Version: model , revision 

**Steps to reproduce:**
1. -   `git clone https://github.com/trezor/trezor-suite.git`
2.-   `yarn`
3.-   `yarn build:libs && yarn workspace @trezor/suite-data msg-system-sign-config`
4.-   `yarn suite:dev:ios`

**Screenshots:**
<img width="1440" alt="Screenshot 2021-06-27 at 11 46 27 PM" src="https://user-images.githubusercontent.com/86569906/123555214-f41a4180-d7a1-11eb-9b5c-7616993a3d2e.png">

**Comment by jerechinsky** [comment]
iOS is not supported.
