### ISSUE TITLE
Desktop app: Tor connection issues

### ISSUE THREAD

**Issue by asavis** [trezor/trezor-suite#3950]
Desktop app Version: 21.6.1
OS: Windows 10 21H1

The same symptoms as in closed #3218 and #2876

Errors seen:

Account discovery error Failed to fetch
Discovery error
Accounts were not loaded properly
Bitcoin: All backends are down
Ethereum: All backends are down

Everything works fine when Tor is disabled. I was not able to get Tor working on previous builds neither.

**Comment by asavis** [comment]
vs21.8.1 is still affected

![изображение](https://user-images.githubusercontent.com/3955000/129542690-8601444c-e499-4cb4-986a-a2261a39fc0c.png)

**Comment by jerechinsky** [comment]
@trezor/qa could you please try to replicate ?

**Comment by sorooris** [comment]
@STew790 could you please take this one?

**Comment by STew790** [comment]
I could not replicate the issue. I tried to turn Tor ON multiple times in multiple different stages of the discovery and also tried to turn it ON after the first discovery and then add a hidden wallet, still wasn't able to reproduce this.

@asavis Would you, please, let us know about the steps that lead to this issue? Did you let the first discovery of the accounts to go through and then turn ON Tor or did you turn Tor ON even before the first discovery? 

**Info**:
 - Suite version: desktop 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win10 32  21H1
 - Screen: 1920x1080
 - Device: model T 2.4.1 regular

**Comment by asavis** [comment]
@STew790 The latest version does not allow me to turn on/off TOR in the settings. Just nothing happens when I click the switch. However if I click it once and then close the app and reopen it the switch does go on/off. So if I manage to turn it on using this way I get the errors. Everything works fine if I turn Tor off.

**Comment by STew790** [comment]
@asavis Thank you for your answer.

I finally managed to get the same error as you do on a different machine. Nonetheless, I would suggest you try to reset the app in the settings and then try to wait for the initial discovery to finish and after that turning ON the Tor. This worked for me to resolve it.

**Steps to reproduce**

1. Start Trezor Suite with Trezor device connected
2. After selecting "Standard wallet", immediately click on the Tor icon at the top, before discovery is finished
3. Enable Tor in the settings
4. Go to "Account" tab
5. Before accounts load, go to "Dashboard" tab
6. Error appears after the discovery ends

I attached a screenshot of the error as well as Suite log.

**Info:**
 - Suite version: desktop 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1366x768
 - Device: model T 2.4.1 
 
 **Screenshot**

![tor_issue](https://user-images.githubusercontent.com/48477147/129722287-97c5a157-4f0a-4056-b4af-391c28994017.JPG)
[log.txt](https://github.com/trezor/trezor-suite/files/6999753/log.txt)

**Comment by asavis** [comment]
@STew790 Thank you. I will try to do that in two weeks when I am back.

**Comment by asavis** [comment]
@STew790

So today I got a chance to do the reset and try Tor after that.

First of all if I click the Tor switch once nothing changes. The switch stays at the disabled state and everything woks like Tor is disabled. 

However if I restart the app Tor is enabled and I get errors as before. If I click the Tor switch nothing happens again. And only after restart Tor is disabled and everything works fine.

**Comment by asavis** [comment]
This is resolved for me in by a new Windows 10 installation.

**Comment by jerechinsky** [comment]
I tried replicating the error myself per Stew's steps, but couldn't. I'll assume this is an edge case and close this now. Please let me know if you experience this again.

**Info:**
 - Suite version: desktop 21.9.2 (6b68428cc0e94f3c636df43f4f1add14b5f6fab3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1080
 - Device: model 1 1.10.3 regular
