### ISSUE TITLE
Analytics 1.11: add timestamp

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3952]
After discussion with our analyst, we want to add `timestamp` to every event.

**Comment by goodhoko** [comment]
A bit late, but still: What is the motivation for this? A timestamp is currently added to the submitted events *on backend*. Doing that on the client can be unreliable as the client's clock can be off. This seems like we're replacing a working solution with something less reliable. Why?

**Comment by tomasklim** [comment]
On the client it is definitely not less reliable. We do not care about user's current system time, we care about time between events. We cannot do that with backend time because it is unreliable because of delays of network.

**Comment by goodhoko** [comment]
> We do not care about user's current system time, we care about time between events.

Very good point that would be very cool to mention in the commit message/PR description/code comment. ,)

**Comment by sorooris** [comment]
**QA OK**

Timestamp attribute present in logs (as "c_timestamp=1625485437378").

Checked in our analytics tool.
Analytics version: 1.11
