### ISSUE TITLE
Display ERC20 Token Icon before its name

### ISSUE THREAD

**Issue by CoelWu** [trezor/trezor-suite#3957]
**Is your feature request related to a problem? Please describe.**
From my opinion, it's easier to distinguish between coins by using their icon instead of names.

**Describe the solution you'd like**
Adding token icon to the position labeled in the picture.
![image](https://user-images.githubusercontent.com/76829607/123767852-61d98100-d8fa-11eb-8076-ef7c5b525166.png)

**Describe alternatives you've considered**
This [repository](https://github.com/coinwink/cryptocurrency-logos) have some very nice icons
Or maybe using CoinGekco's api, I saw [ETHVM](https://www.ethvm.com/) doing this as well.

**Comment by CoelWu** [comment]
![Screen Shot 2021-07-13 at 7 32 09 PM](https://user-images.githubusercontent.com/76829607/125444794-a8759648-d5d5-420f-adb3-4bcaf1bed977.png)
Something like this

**Comment by glacierbits** [comment]
Thanks @CoelWu for the suggestion. We will consider it. 

@marekrjpolak Could you please have a look? Low prio for this sprint, so no pressure. :)

**Comment by tomasklim** [comment]
Closing, we will reconsider after implementation of https://github.com/trezor/trezor-suite/issues/6595
