### ISSUE TITLE
New onboarding - wrong 3D instruction during Trezor One firmware installation

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#3960]
**Describe the bug**
When onboarding asks the users to reconnect their Trezor One after a new firmware has been installed, the instruction text says correctly "Do not hold any buttons while connecting the cable", but there is also a 3D animation showing a hand that is holding one button on Trezor One. 

**Steps to reproduce:**
Launch new onboarding
Connect Trezor One without any firmware
Proceed with firmware installation

**Screenshots:**
<img width="973" alt="Screen Shot 2021-06-29 at 1 52 32 PM" src="https://user-images.githubusercontent.com/54173889/123793400-ef5ca700-d8e1-11eb-96ce-66f9ece7ec97.png">

**Comment by jerechinsky** [comment]
@matejzak do we have an animation where the hand is not holding any buttons?

**Comment by glacierbits** [comment]
FYI our 3D designer should deliver the solution next week.

**Comment by glacierbits** [comment]
@stepmes any objections regrading this design proposal? 👇🏽 🙏🏽 

https://www.dropbox.com/s/arnj76udq4gbubt/Dark_mode.mp4?dl=0

**Comment by glacierbits** [comment]
3D animation for implementation: https://www.dropbox.com/s/1jszt6ugshc0k9t/Dark_mode.mov?dl=0

**Comment by mroz22** [comment]
> 3D animation for implementation: [dropbox.com/s/1jszt6ugshc0k9t/Dark_mode.mov?dl=0](https://www.dropbox.com/s/1jszt6ugshc0k9t/Dark_mode.mov?dl=0)

@matej you sure about this .mov extension? Probably should be .mp4.

**Comment by glacierbits** [comment]
@mroz22 .mp4 (both light & dark) [hier](https://www.dropbox.com/sh/cbh5qdr8rnieuha/AADWOUJCf3LZoYcOtZHWU5c8a?dl=0)

**Comment by jerechinsky** [comment]
We've decided to merge and test this when there's more changes to the update process so QA wouldn't have to waste a device with old FW on an issue that affects so few users.
