### ISSUE TITLE
Settings button: Categories in the popup don't correspond with top navigation tabs in the Settings section. 

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#3964]
**Describe the bug**
The categories that appear when a user clicks on the "gear" settings icon in the top right corner of Suite are "Application" "Device" and "Coins". However the top navigation tabs in the Settings section are "General" "Device" and "Coins". 

As the "General" top navigation tab in the settings section includes an own subsection that is called "application", I believe that the popup categories should be changed from "Application" to "General". Beside the copy, also the icon should be substituted with a "gear" icon. 

**Steps to reproduce:**
1. Open Trezor Suite dev build.  
2. Click the settings "gear" icon in the top right corner of Suite
3. Click "Application"

**Info:**
 - Suite version: web 21.7.0 (550942dcbdb7b2ffc17519f8307a47f2d8d060f1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
 - OS: MacIntel
 - Screen: 1280x800
 - Device: model T 2.3.6 regular

**Screenshots:**
Insert here.
<img width="1280" alt="Screen Shot 2021-06-30 at 4 18 09 PM" src="https://user-images.githubusercontent.com/54173889/123976957-dfff5b80-d9be-11eb-9550-aeff1ea70d1c.png">

**Comment by glacierbits** [comment]
@alex-jerechinsky Can you please change the "General" to "Application" in Crowdin? Thanks!

**Comment by glacierbits** [comment]
FYI I changed it with other copy-related changes. It will populate with the next Crowdin sync.

**Comment by bosomt** [comment]
Current dev master still contain different icons and headers.

![image](https://user-images.githubusercontent.com/31506317/124589806-afa23c00-de5a-11eb-962e-b2f1633e4f61.png)

**Info:**
 - Suite version: web 21.7.0 (9d473f00215843741241e13ff3b857667fdf3e3f)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.1 regular

**Comment by sorooris** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/10185314/125274374-339e6d00-e30e-11eb-9a28-332dc86b65b5.png)


Suite version: web 21.7.1 ca85ae5
Browser: Chromium 91.0.4472.77
OS: NixOS 21.05
Device: model One 1.10.1 3204fd682
