### ISSUE TITLE
remove WebUSB banner

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#3965]
The macOS WebUSB Chromium bug that stick reported [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1216324) appears to be fixed now. It works in my Chrome 91.0.4472.114. Could we have the WebUSB banner removed?

**Info:**
 - Suite version: web 21.6.1 (0ce310eb30cff6396b91939d3293b34e8e50d7c1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1200
 - Device: model T 2.3.6 regular

**Comment by tsusanka** [comment]
Removed for `develop`. Could you confirm on `https://suite.corp.sldev.cz/suite-web/develop/`?

**Comment by vdovhanych** [comment]
@tsusanka can confirm that it is indeed gone.

**Comment by tsusanka** [comment]
Done.
- [ ] for me: remove the backup after testing

**Comment by sorooris** [comment]
**QA NOK**

Not sure what went wrong here, the banner is still displayed.

Suite: web 21.7.0 b606e96
Browser: Chrome 91.0.4472.114
OS: MacOS Big Sur 11.4
Device: N/A

https://github.com/trezor/trezor-suite/issues/3874#issuecomment-874678639

![image](https://user-images.githubusercontent.com/10185314/124592643-f6ddfc00-de5d-11eb-9a4c-d19727b7ffaa.png)

**Comment by tsusanka** [comment]
Well that is interesting because it seems correct on my side. Could you please:
1. Run Ctrl + F5 to refresh properly just in case.
2. Try on suite.trezor.io/web?

**Comment by sorooris** [comment]
**QA OK**

Confirming that a new browser session and a hard refresh resolved it in develop, suite.trezor.io/web did not have the banner displayed.

![image](https://user-images.githubusercontent.com/10185314/124593807-5dafe500-de5f-11eb-881b-c7a0efe67d5e.png)

Suite: web 21.7.0 b606e96, 21.6.2 290aab68
Browser: Chrome 91.0.4472.114
OS: MacOS Big Sur 11.4
Device: N/A

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.7.1 (34de15f6b0dcdbf8dc69a34fc65e6abab6a8213d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular
