### ISSUE TITLE
New onboarding - Analytics opt-out skipped after connecting a device in recovery mode

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3969]
**Describe the bug**
Connecting a Model T in recovery mode very briefly displays the Analytics opt-out and redirects to the second step of the onboarding process, preventing the user to opt-out of anonymous data collection.

**Info:**
 - Suite Version: app + web 21.6.2, commit 41f736b3bfb09303a2acfbae5ef2bd55ee73985c
 - Browser: Chrome 91.0.4472.77, Firefox 88.0.1
 - OS: NixOS 21.05, Win10 19042.1052
 - Bridge: 2.0.27 standalone, 2.0.31 Suite-bundled
 - Firmware Version: model T 2.4.0

**Steps to reproduce:**
1. Connect a device in recovery mode,
2. Let Suite detect the device,
3. Observe.

**Expected result:**
Welcome screen is displayed first with ConnectDevicePrompt displaying that the device is connected, with the option to continue in recovery.

**Actual result:**
Analytics opt-out very briefly displayed and redirect to the second step of the onboarding process is done.

**Screenshots:**
Actual:

https://user-images.githubusercontent.com/10185314/124112613-c1ef3500-da6a-11eb-939a-efbf646883ec.MOV

Expected:
![image](https://user-images.githubusercontent.com/10185314/124116850-bb16f100-da6f-11eb-9bb1-5071f326672f.png)

**Comment by dimasivan** [comment]
@Hermez-cz 
this is a rare case as it depends on two factors: cleared Suite storage and device in recovery mode. After connecting device to suite user can see analytics opt out screen just for a while and then it disappears  and recovery mode starts. What is an appropriate solution to this: 
1. show opt-out screen and wait for user action
2. hide opt-out screen when in recovery mode(?)

**Comment by Hermez-cz** [comment]
@pingpwned Thank you for the options outlined.

We should definitely go for option 1., any further steps might be subject to Analytics, so it's essential getting consent first.

I have 2 more improvement suggestions to this flow (and we might create separate issues for those shall they be complicated, to avoid scope growth of this one):

1. Device screen should stay inactive during the Analytics opt-out selection in Suite. Testing has shown, that different parallel instructions in Suite vs. on device are confusing users. First after Analytics opt-out choice has been done, in the next step, device should display contents shown in the video:

_Incorrect:_
<img width="570" alt="image" src="https://user-images.githubusercontent.com/88533514/128899892-40471f9f-d138-49ff-bc57-ef8d25fd8f58.png">

_Correct:_
<img width="588" alt="image" src="https://user-images.githubusercontent.com/88533514/128895406-f3bf77ce-abf0-4d00-8786-ffc2de2d6efa.png">

2. Even before the Analytics opt-out screen we might add one more to get the users in context (they might have reconnected the device after some time has passed or disconnect-reconnect by mistake, so some indication of where they are and that the recovery can continue might help them)

So the ideal complete flow could be (if technically possible):
- Step 1: Setting context - Focus in Suite. Info “Wallet recovery is in progress on this Trezor, do you wish to continue?” CTAs “Continue recovery” / “Abort recovery”. Device screen inactive.
- Step 2: Anonymous data collection - Focus still in suite. CTA “Continue recovery”. Device screen inactive.
- Step 3: Recovery - As is: “Recover wallet from seed” CTA “Confirm on Trezor”. Focus moves to the Trezor device, where users continue in the recovery process.

**Comment by dimasivan** [comment]
there's a [middleware](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/middlewares/recovery/recoveryMiddleware.ts#L38) which skipps welcome and starts onboarding if recovery mode detected.

dispatch can be moved to onboarding middleware to wait for user action and then start recovery, but I'm aware if it makes sense - in case if suite not using analytics while recovery process, then there is no point to opt out before

**Comment by Hermez-cz** [comment]
@pingpwned Thank you. Makes sense in that case. And after such recovery, can we trigger opt-out process to avoid skipping it completely?

**Comment by bosomt** [comment]
**QA OK**

tested with reconnected device and without reconnection. 
It fails when device is not reconnected and you have to press retry to continue with recovery.

https://user-images.githubusercontent.com/31506317/131452197-7743b68f-8114-4799-afdc-d5bd0cf9c0cc.mov


https://user-images.githubusercontent.com/31506317/131452220-4cb52d67-f289-4cf5-abcf-1831090e4fb7.mov


**Info:**
 - Suite version: web 21.9.0 (f427443fe8f1c2c25312785a277f2cc61dbb4d1a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by matejkriz** [comment]
but disconnecting during shamir recovery is now broken :-(

**Comment by bosomt** [comment]
@matejkriz can you please give us more information so I can try to reproduce it ? 

I tested it with shamir backup multiple times. But i reconnected device or opened suite fresh suite between shamir parts

**Comment by matejkriz** [comment]
@bosomt sorry for the lack of info, but we already have a fix for that: https://github.com/trezor/trezor-suite/pull/4203

The steps to reproduce that fixed bug are described in this test case [t2-recovery-persistence.test.ts#L89 ](https://github.com/trezor/trezor-suite/blob/develop/packages/integration-tests/projects/suite-web/tests/onboarding/t2-recovery-persistence.test.ts#L89 )because that test was failing on [#L125](https://github.com/trezor/trezor-suite/blob/develop/packages/integration-tests/projects/suite-web/tests/onboarding/t2-recovery-persistence.test.ts#L125).
