### ISSUE TITLE
New onboarding - Find Trezor button expands CollapsibleBox and opens webUSB modal at the same time

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3970]
**Describe the bug**
Selecting the _Find Trezor_ button opens the webUSB modal and expands the CollapsibleBox at the same time when connecting via webUSB in Chrome.

**Info:**
 - Suite Version: web, 21.6.2, commit 41f736b
 - Browser: Chrome 91.0.4472.77
 - OS: NixOS 21.05, Win10 19042.1052
 - Bridge: N/A, **webUSB**
 - Firmware Version: model 1 1.10.1, model T 2.4.0

**Steps to reproduce:**
1. Disable Bridge if running,
2. Launch Suite in Chrome with webUSB allowed,
3. Select the Find Trezor button.

**Expected result:**
CollapsibleBox element is expanded and browser's webUSB modal is opened at the same time.

**Actual result:**
Selecting the _Find Trezor_ button only opens the browser's webUSB modal, while **clicking outside the button** expands the CollapsibleBox element.

**Screenshots:**
Before selecting the button:
![image](https://user-images.githubusercontent.com/10185314/124118347-84da7100-da71-11eb-849e-c1493cd51cba.png)
After selecting the button:
![image](https://user-images.githubusercontent.com/10185314/124118403-94f25080-da71-11eb-8ef5-be43e312dc3b.png)

**Comment by bosomt** [comment]
Same behaviour in current dev master 21.10.0

**Comment by mroz22** [comment]
I think this had already been fixed by this https://github.com/trezor/trezor-suite/pull/4347
and this fix should be available from dev server already

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.11.0 (f9651145c08c7b5dd5ad9d658ee7bba96891fbfb)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.9.4 regular
