### ISSUE TITLE
New onboarding: Trezor One FW update contains instruction for TT instead of T1.

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#3981]
**Describe the bug**
Updating FW on Trezor One through new onboarding. Suite asks to "Reconnect your Trezor in bootloader mode"
- First screen shows two steps 1) Disconnect your Trezor 2) Hold left button while connecting the cable
- Second screen after users disconnects Trezor shows two steps 1) "Disconnect your Trezor" 2) "Swipe your finger across the screen while connecting the cable", which is an instruction for TT.  

**Info:**
 - Suite Version: https://suite.corp.sldev.cz/suite-web/develop/web/settings/debug/
 - Browser: Chrome Version 91.0.4472.114
 - OS: MacOS BigSur 11.4
 - https://suite.corp.sldev.cz/suite-web/develop/web/settings/debug/

**Steps to reproduce:**
1. Connect T1 with an outdated FW
2. Go through new onboarding
3. Start firmware update

<img width="1280" alt="Screen Shot 2021-07-02 at 11 55 51 AM" src="https://user-images.githubusercontent.com/54173889/124258876-317a2880-db2e-11eb-9d53-6eba05869ba0.png">

**Comment by marekrjpolak** [comment]
Should be fixed in https://suite.corp.sldev.cz/suite-web/fix/3981-t1-reboot-instructions/web/.

**Comment by bosomt** [comment]
**QA OK**

<img width="628" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/129891913-87164f39-143f-4aa4-9762-158c54ac85d0.png">

**Info:**
 - Suite version: web 21.9.0 (da468fee0b2e83475860c6d3cd500b302de6b70e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.9.4 regular
