### ISSUE TITLE
LIBUSB_ERROR_ACCESS when starting T1 recovery

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3982]
**Describe the bug**
Happened 2 times of 4 times i wiped and recovered my device today. This error sometimes occur but so far no idea why and how to trigger it every-time. 
Attached one screenshot and log /happened twice during this Suite run/

**Steps to reproduce:**
1. Wipe device model One
2. Start recovery without disconnecting device
3. Repeat till you see error

**Info:**
 - Suite version: desktop 21.6.2 (aaf0b56bec9f666c2151f0651ee1427507eb2dd9)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model One 1.10.2 regular

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/124263085-1a8a0500-db33-11eb-9e69-87d204972d96.png)
[trezor-suite-log-1625219431567.txt](https://github.com/trezor/trezor-suite/files/6754063/trezor-suite-log-1625219431567.txt)

**Comment by tsusanka** [comment]
Using bundled-in Bridge therefore version 2.0.31?

**Comment by bosomt** [comment]
@tsusanka using ` Version: 2.0.31 (rev 5f53132) `

**Comment by mroz22** [comment]
Reassigned to @alex-jerechinsky to decide what to do here until we have a reliable way to simulate this.

**Comment by bosomt** [comment]
issue is still present in latest version of Suite

**Info:**
 - Suite version: web 21.9.2 (cc85c69e3d6556e673c4d30f39953179f690b663)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model 1 1.10.3 regular
 - Bridge Version: 2.0.31 (rev 5f53132)

**Comment by bosomt** [comment]
issue is still present in latest version of Suite

![image](https://user-images.githubusercontent.com/31506317/136954367-3f9e0931-0926-4e2e-88f4-64c1596d8598.png)

**Info:**
 - Suite version: desktop 21.10.1 (30698b091e0eff94a2adddf92b15998092d7a3c9)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model 1 1.10.3 regular

**Comment by wendys-cats** [comment]
Could not reproduce on 21.12.1 APP.

**Info:**
 - Suite version: desktop 21.12.1 (c2f3c43646f88ec791001606428cd78f14d3a482)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.12.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model 1 1.10.4 regular

**Comment by bosomt** [comment]
same result on macOS, tested 10+ times now
looks like it's Linux only problem 

**Info:**
 - Suite version: desktop 21.12.1 (c2f3c43646f88ec791001606428cd78f14d3a482)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.12.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.4 regular

**Comment by bosomt** [comment]
**QA OK**

I was not able to reproduce issue anymore.
Now you are asked to reconnect T1 after you wipe it.
 
**Info:**
 - Suite version: desktop 22.10.1 (6ed234b6b8df5ea61f3de505d35105bf4816522e)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.10.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1536x864
 - Device: model 1 1.11.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32
