### ISSUE TITLE
Replace 3D image with 2D icon

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3983]
Usability test carried out by @stepmes proved the current 3D image (entry point to the product Guide placed at the right bottom corner of the app - see screenshot) is confusing to users. 

Please replace it with 2D image: [**Zeplin**](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/styleguide/components?coid=60b760283ec16c6a2ad345b1) 

<img width="75" alt="Screen Shot 2021-07-02 at 13 40 43" src="https://user-images.githubusercontent.com/29627086/124269390-1b269980-db3b-11eb-8c93-4f6bb2dba331.png">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.7.0 (8b018e2f06a7e36d9a650c2b7327c13da125dcdc)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model 1 1.10.2 regular

**Comment by sorooris** [comment]
**QA OK**

Suite version: web 21.7.1 ca85ae5
Browser: Chromium 91.0.4472.77
OS: NixOS 21.05
Device: model One 1.10.1 3204fd682
