### ISSUE TITLE
New onboarding: Activate coins screen contains a broken string

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#3987]
Description:
The activate coins screen in the new onboarding seems to contain a broken string - the info about how many coins are available and how many are activated. please s. screenshot

Info:
Suite Version: https://suite.corp.sldev.cz/suite-web/develop/web
Browser: Chrome Version 91.0.4472.114
OS: MacOS BigSur 11.4

Steps to reproduce:
1. Connect TT
2. Progress through the new onboarding to the Activate coins screen

Screenshots
<img width="1276" alt="Screen Shot 2021-07-02 at 5 27 59 PM" src="https://user-images.githubusercontent.com/54173889/124297371-49b46c80-db5b-11eb-95f6-ab7704c55532.png">

**Comment by jerechinsky** [comment]
I couldn't replicate. Maybe it was only on develop? Please reopen if it happens again.
