### ISSUE TITLE
New onboarding: Missing picture of Trezor on the last screen

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#3988]
Description:
At the very end of the new onboarding, the picture of Trezor is missing. Please s. screenshot

Info:
Suite Version: https://suite.corp.sldev.cz/suite-web/develop/web/
Browser: Chrome Version 91.0.4472.114
OS: MacOS BigSur 11.4

Steps to reproduce:
- Connect Trezor T
- Go through new onboarding until you reach the last screen with "Edit name" "Change Homescreen"

Screenshot
<img width="1271" alt="Screen Shot 2021-07-02 at 6 30 55 PM" src="https://user-images.githubusercontent.com/54173889/124304462-08748a80-db64-11eb-8e23-f426ba858b5a.png">

Used to look like this
<img width="930" alt="Screen Shot 2021-07-02 at 6 34 35 PM" src="https://user-images.githubusercontent.com/54173889/124304610-3c4fb000-db64-11eb-8731-5fe706111b9f.png">

**Comment by jerechinsky** [comment]
I believe this was fixed by #4017
