### ISSUE TITLE
Add switch to only show accounts with a positive balance (useful when multiple wallets are used)

### ISSUE THREAD

**Issue by xanoni** [trezor/trezor-suite#3989]
**Is your feature request related to a problem? Please describe.**
Trezor Suite allows users to enable/disable coins in the settings screen, however this setting applies to all imported wallets. This can be confusing (bad UX) when the user has multiple Trezor devices or when hidden passphrases are used, and when the wallets contain different sets of coins.

Besides, for non-UTXO based coins such as Ethereum, users often choose to generate new accounts over time to increase privacy. However, this means that old/empty accounts start clogging up the account list, which leads to terrible UX over time.

**Describe the solution you'd like**
1. Add a toggle that allows users to only display accounts with a positive balance.
2. Besides, allow users to manually hide accounts (e.g., Ethereum accounts that only have some airdrop tokens in them that are difficult to sell, but that still make the balance slightly positive).

**Describe alternatives you've considered**
Unfortunately, the only alternative is to use a different wallet. For the old non-UTXO accounts, one could regularly create new wallets and migrate all coins to it, but this is painful and costly (network fees).

**Additional context**
Screenshot ... multiple empty accounts that can no longer be used if privacy is to be preserved, but that keep clogging up the screen (testnet wallet / wallet mockup):

![image](https://user-images.githubusercontent.com/77220130/124340449-69f82180-db83-11eb-8a87-c9f798eb7c55.png)

**Comment by Crypto2** [comment]
I second making it toggle-able. (Could be stored in the same way as address labels?)

**Comment by xanoni** [comment]
> I second this but perhaps just make it toggle-able versus based on balance? (Could be stored in the same way as address labels.)

Yeah that matches my point 2.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
