### ISSUE TITLE
Suite modal says Confirmed before you confirm it via Trezor when replacing transaction

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3990]
**Describe the bug**
Suite modal says Confirmed even when device says Hold to Confirm when replacing transaction.
See screenshots as comparison. In both times device says hold to confirm.

**Steps to reproduce:**
1. Send transaction that you can replace via RBF
2. Replace fee
3. Observe top of modal during transaction confirmation/signing

**Info:**
 - Suite version: desktop 21.6.2 (aaf0b56bec9f666c2151f0651ee1427507eb2dd9)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.1 regular
**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/124453964-34705580-dd88-11eb-9ed3-c70134b0ea5a.png)

![image](https://user-images.githubusercontent.com/31506317/124454232-8913d080-dd88-11eb-8581-58477323814e.png)

**Comment by matejcik** [comment]
will be fixed in firmware, by backing out of (part of) https://github.com/trezor/trezor-firmware/pull/1671

**Comment by bosomt** [comment]
**QA OK**

bump fee AND bump fee with amount decrease works as expected 

**Info:**
 - Suite version: web 21.8.0 (755c2cda15ba92854605d2778b0d035e84d75140)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 version trezor-fw-regular-2.4.1-46e05307
