### ISSUE TITLE
Suite Guide followup

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3992]
Suite Guide improvements not resolved in  #3817

- [x] #3994
- [x] #4407
- [x] #4408
- [x] #4409
- <s>[ ] send also Github issue template when reporting a bug **(Product needed)**</s>
- [x] #4410
- [x] #4411
- [x] open link in a new tab
- [x] do not close on escape when modal is opened

New improvements
- [x] #4412
- [x] #4413
- [x] unit tests
- [x] e2e tests
- [x] #4414
- [ ] more than 2 levels  **(design needed)**
- [x] preload articles 
- [x] #4415
- [x] #4416

**Comment by dimasivan** [comment]
> allow Guide to be open while a modal is open too

![image](https://user-images.githubusercontent.com/42174681/125483742-49af7002-e6c7-4e33-8c7f-bb1d85f1fe77.png)

**Comment by sorooris** [comment]
Question: should the Guide be accessible from the Welcome page?
![image](https://user-images.githubusercontent.com/10185314/127891547-0ca55ba8-34de-428c-b0ec-ed1f25af8510.png)

**Comment by sorooris** [comment]
From https://github.com/trezor/trezor-suite/issues/4027#issuecomment-879704425:
> Another improvement/feature request:
> Open external links in new tab (web Suite) - currently any external links in the Guide are opened in the same tab.

Can't find it in the description above, please add it.

**Comment by wendys-cats** [comment]
Can you please add opening Suite Guide external links in new tab (web browser version) to the folow up? Right now, when you open an external link from Suite Guide, it opens in the same tab as your Suite. Feels like a punishment!

**Comment by tomasklim** [comment]
Will be in the September release:
- [x] open link in a new tab
- [x] do not close on escape when modal is opened

**Comment by tsusanka** [comment]
Separated into own issues. QA: issues being done in November have their own issue so there is nothing to test here AFAIK.
