### ISSUE TITLE
Accounts - scrollbar gap

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3993]
When scrollbar is missing in Accounts, there is an empty space, instead of wider account bar.

@matejzak mentioned in #3817
> It would be nice to fix the gap. Although, I suspect we may need to do a bigger refactor to the scrollbars globally.

![Screenshot 2021-07-05 at 21 06 04](https://user-images.githubusercontent.com/33235762/124510770-d9188480-ddd4-11eb-8bba-e028b57e7a9e.png)
![Screenshot 2021-07-05 at 21 06 00](https://user-images.githubusercontent.com/33235762/124510774-da49b180-ddd4-11eb-84a6-ecbdbee3ca4a.png)

**Comment by matejkriz** [comment]
@matejzak what about to get rid of custom scrollbar styles completely and switch to default/system scrollbars? I believe it's better for the UX...

**Comment by tomasklim** [comment]
@matejkriz @slowbackspace explained this question to me. There was a requirement for the scrollbar to look like on macOS everywhere (Windows, Linux).

**Comment by glacierbits** [comment]
I think that getting rid of the custom scrollbar makes sense (e.g. on MacOS I expect the scrollbar to appear/disappear as in other apps - something the Suite doesn't support). Not sure where the original requirement came from, but we don't have to keep it.

**Comment by matejkriz** [comment]
And I want to challenge that requirement... Even on MacOS it changes with every version and also with theme. But in general, I believe, that it's better to keep the system UI of the user's platform.

**Comment by tomasklim** [comment]
If we want an app without custom scrollbars, it looks like this:

macOS without mouse:
![Screenshot 2021-07-12 at 14 06 55](https://user-images.githubusercontent.com/33235762/125285259-c0e7be80-e31a-11eb-8ce3-fa6b1af12306.png)

macOS with mouse:
![Screenshot 2021-07-13 at 14 48 32](https://user-images.githubusercontent.com/33235762/125456809-df9c3dd3-b7cb-415f-b8b8-1bb34d7489e4.png)

Windows: (scrollbar in guide is from the top to the bottom now)
![Screenshot 2021-07-12 135737](https://user-images.githubusercontent.com/33235762/125285384-e2e14100-e31a-11eb-8a85-ebfca60fce35.png)

Linux:  (scrollbar in guide is from the top to the bottom now)
![image (1)](https://user-images.githubusercontent.com/33235762/125285429-ec6aa900-e31a-11eb-99da-d2a2744afe59.png)

![image](https://user-images.githubusercontent.com/33235762/125285692-3489cb80-e31b-11eb-916b-fddabd5ec982.png)

@sorooris says that on Windows and Linux it looks like every other app. 

Do we want it? it is ready to be merged @matejzak

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: app + web 21.8.0 (7f2b12206bca4149b2c30bf3696bf337a064a60e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular
