### ISSUE TITLE
Send form - "Clear all" button when form is empty

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3995]
**Describe the bug**
Clear all button is available in send section without anything being filled.

**Steps to reproduce:**
1. Send section
2. Add OP Return
3. Hit OP RETURN cross button
4. Clear all button appears but nothing was filled.

**Screenshots:**
![Screenshot 2021-07-07 at 10 50 12](https://user-images.githubusercontent.com/33235762/124729889-1da93a80-df11-11eb-96a7-adac931f2093.png)

**Videos:**
https://user-images.githubusercontent.com/33235762/124729777-08341080-df11-11eb-9395-14bd0eb8a215.mov

**Comment by bosomt** [comment]
I was able to reproduce issue


**Info:**
 - Suite version: desktop 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular

**Comment by wendys-cats** [comment]
Was able to reproduce as well.

Suite version: APP 21.9.1 8b28b4c5df6eebb039ee30a35fab0016dd30679a
OS: Windows 10
Device: model TT 2.4.0 public regular

**Comment by bosomt** [comment]
**QA NOK**

issue is still present

**Info:**
 - Suite version: desktop 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by jvaclavik** [comment]
Is it still valid? I couldn't find it.

https://github.com/trezor/trezor-suite/assets/858321/8b93e7f0-6e8a-4fe5-b009-d8d598e5921b

**Comment by bosomt** [comment]
**QA OK**

i was not able to reproduce it anymore.

**Info:**
 - Suite version: desktop 23.10.1 (6c8d061f7305947b0270a2560e4cc65d1f7ded27)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.10.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
