### ISSUE TITLE
Notion is linked in Suite Guide

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4002]
**Describe the bug**

**Steps to reproduce:**
1. Start latest version of Suite
2. Start Guide and go to `Dashboard/Supported Crypto/Custom ERC20 Token`
3. Click on `Account` in `How to store custom tokens` section

**Info:**
 - Suite version: desktop 21.7.1 (34de15f6b0dcdbf8dc69a34fc65e6abab6a8213d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular

**Screenshots:**
<img width="1056" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/124901159-0ab26b00-dfe2-11eb-957a-176955a91438.png">

**Comment by bosomt** [comment]
I found one more issue.
Dead link to RBF explanation.
Do you want me to go through whole Suite guide and check for dead/bad links ?

<img width="197" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/124924034-4f96cb80-dffb-11eb-9bd4-6900c1ecf876.png">

--


<img width="320" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/124923972-4279dc80-dffb-11eb-9586-07a760549ed5.png">

**Comment by tsusanka** [comment]
I have removed the notion links from Gitbook.

-----

@goodhoko as per the [second comment from @bosomt ](https://github.com/trezor/trezor-suite/issues/4002#issuecomment-876410685) the links are correct in gitbook, does our current Suite Guide implementation support these links or it does not?

**Comment by goodhoko** [comment]
> as per the second comment from @bosomt the links are correct in gitbook, does our current Suite Guide implementation support these links or it does not?

It does not. That would require some additional logic application logic as displaying Guide articles isn't handled by URL and the browser but within the app itself. cc @tomasklim

**Comment by tsusanka** [comment]
We should remove the links then. <s>I'll ask Anthonny.</s> He is on vacation, I'll do it myself.

**Comment by tsusanka** [comment]
Done in https://github.com/trezor/trezor-suite-guide/commit/7defb3d8fd61bd7cc6d7602955f54b95698f5ed2.

**Comment by goodhoko** [comment]
@tsusanka For this to take effect in the upcomming release we need to change the [gitbook ref](https://github.com/trezor/trezor-suite/blob/0868666b806a04ab22f7bb121e8a537d62717d94/packages/suite-data/src/guide/constants.ts#L4) in Suite repo. Shall I do it?

**Comment by tsusanka** [comment]
Ah yes please. Could you please add a short info how to update the guide in `docs/misc/guide.md` or similar? I haven't found this info anywhere.

**Comment by goodhoko** [comment]
> Ah yes please. 

[Here](https://github.com/trezor/trezor-suite/pull/4012) you go.

>  Could you please add a short info how to update the guide in docs/misc/guide.md or similar? I haven't found this info anywhere.

It's right [there](https://github.com/trezor/trezor-suite/blob/develop/docs/misc/guide.md). Maybe it could be put more prominently?

> These are configured to fetch a particular commit of the GitBook mirror by the GB_REVISION constant in packages/suite-data/src/guide/constants.ts. This constant must/can be changed accordingly to propagate changes from GitBook to suite builds.

**Comment by goodhoko** [comment]
... The update 'workflow' is also described in the [Guide manual](https://github.com/trezor/trezor-suite-guide/tree/master#how-to-publish)
> ## How to publish
> 
> The contents of this GitBook are packaged with each release of Suite applicaiton. The version is controlled from within Suite's codebase. To propagate your latest changes to the next relase ask Suite dev team to update the `GB_REVISION` configuration constant in the `suite-data` package.

**Comment by tsusanka** [comment]
Ah I am blind then :). I made it a little bit more explicit in https://github.com/trezor/trezor-suite/pull/4016. Could you review please?

**Comment by tsusanka** [comment]
Fixed by https://github.com/trezor/trezor-suite/pull/4012. Will be on staging tomorrow.

**Comment by sorooris** [comment]
**QA OK**

Haven't found any Notion links in the Guide; #4027 created as a follow-up.

Suite: web 21.7.1 24cc565a
Browser: Chromium 91.0.4472.77
OS: NixOS
Device: model One 1.10.2
