### ISSUE TITLE
Missing space in Settings idem description text

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4007]
**Describe the bug**
It says: `Your standard wallet will still be accessible without a passphrase.Do not forget your passphrase. Unlike`
There is space missing between . and Do

**Steps to reproduce:**
1. Open suite settings and navigate to Device section.
2. Check Passphrase information

**Info:**
 - Suite version: desktop 21.7.1 (ca85ae5c485fd0291952f50bc9d7a06076fddaa4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular

**Screenshots:**
<img width="539" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/125075297-b29d6680-e0be-11eb-8b2b-5ac698dc3633.png">

**Comment by jerechinsky** [comment]
Fixed via copy. Will close when crowdin is synced. 

EDIT: Didn't work.

**Comment by jerechinsky** [comment]
@marekrjpolak please put a space between `TR_DEVICE_SETTINGS_PASSPHRASE_DESC` and `TR_DEVICE_SETTINGS_PASSPHRASE_DESC_MORE`

**Comment by marekrjpolak** [comment]
`TR_DEVICE_SETTINGS_PASSPHRASE_DESC_MORE` will be removed completely, with its text joined after `TR_DEVICE_SETTINGS_PASSPHRASE_DESC` in messages.ts. It is necessary to reflect this change in all existing localizations in Crowdin.

**Comment by tomasklim** [comment]
merged. Do not forget to update English and Spanish text in Crowdin @alex-jerechinsky

**Comment by bosomt** [comment]
**QA OK**

I hope that ; is expected in `This creates a hidden wallet; each hidden wallet can use its own passphrase`

<img width="522" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/129889718-94b07c42-0240-4ad9-8bd7-26fd8b0ae451.png">

**Info:**
 - Suite version: web 21.9.0 (da468fee0b2e83475860c6d3cd500b302de6b70e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 Bitcoin only
