### ISSUE TITLE
Dashboard - Add Token Total Value to Make Dashboard More Accurate

### ISSUE THREAD

**Issue by IAmIntractable** [trezor/trezor-suite#4009]
When viewing the dashboard there are situations where valuations are not being displayed. This makes it difficult to jibe the portfolio total value with the assets displayed. The total value of tokens should be displayed so that it's clear there are tokens with value present.

Suggestions:
1 Show the total Token Value with the associated asset
2 Show each token as an Asset 
3 Create an Asset Classification for a class of tokens such as "ERC20" that could represent the total token value

This will likely mean you will have to resolve all coins/tokens and store that in memory so that you can display an accurate dashboard. But I dont feel Like the dashboard is useful if its not accurate.

**Comment by CoelWu** [comment]
This is indeed an import issue. When I only hold ERC20 tokens, every time I use my hidden wallet on another device, it pop up an warning shows that this is an empty wallet because it does not count ERC20 token value

**Comment by IAmIntractable** [comment]
> This is indeed an import issue. When I only hold ERC20 tokens, every time I use my hidden wallet on another device, it pop up an warning shows that this is an empty wallet because it does not count ERC20 token value

It seems to me that its an easy job to call the code that compiles the list of tokens from the Dashboard and simply total all of the value. I dont need to see every token on the dashboard.

**Comment by ounrequitedo** [comment]
I see this has been removed from the backlog, is it dead or is it being implemented eventually?

**Comment by stepmes** [comment]
Thanks very much for this feedback, we're noting it down and will consider it when working on future improvements.
