### ISSUE TITLE
Missing pictures and gifs in Suite

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#4011]
**Describe the bug**
Suite is missing gifs and pictures. Noticed in onboarding when Suite is installing new firmware for TT device that there is gif missing (the one showing how to reconnect the device in bootloader mode). 

**Info:**
 - Remembered Wallet: no
 - Suite Version: app and web, 21.7.1 ca85ae5c485fd0291952f50bc9d7a06076fddaa4
 - Browser: Chrome 91
 - OS: Windows 10, MacOS Big Sur 11.4
 - Bridge: 2.0.27 (standalone for web), 2.0.31 (bundled for app)
 - Firmware Version: TT 2.3.6

**Steps to reproduce:**
1. install 2.3.6 (or older) FW into device
2. connect device and start onboarding
3. get to FW update and disconect the device
4. see missing gif in modal

**Expected result:**
Gif will be displayed.

**Actual result:**
Gif is missing.

**Screenshots:**
![windows](https://user-images.githubusercontent.com/58593111/125282232-6d27a600-e317-11eb-9a3b-27f99e3f258f.jpg)
![maocs](https://user-images.githubusercontent.com/58593111/125282290-803a7600-e317-11eb-965c-4560e618b390.jpg)

**Note(s):**
If there are any more missing gifs/pictures, I will add them to the issue!

**Comment by sorooris** [comment]
Missing video tT_success_light.webm
![image](https://user-images.githubusercontent.com/10185314/125284144-626e1080-e319-11eb-9363-c95dafa3e327.png)
![image](https://user-images.githubusercontent.com/10185314/125284194-7285f000-e319-11eb-9fbb-bb0758a8205f.png)

Suite: app 21.7.1 ca85ae5c
OS: macOS Big Sur 11.4
Device: any (tested model T 2.3.6 -> 2.4.0 ea3596ad8)

**Comment by marekrjpolak** [comment]
The onboarding video files were all lower-case, but the application requested paths with 'T' as in model T. The issue is probably fixed, but I see similar possible issue e.g. with 'custom' suite theme.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.7.1 (3d90909aa68da250490f474b2d4cab02c0aad272)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular

**Comment by wendys-cats** [comment]
**QA OK**

GIF is back! 

Info:

**Suite** version: APP 21.7.1 3d90909aa68da250490f474b2d4cab02c0aad272
**OS**: Windows10
**Device**:  TT 2.3.6 regular

**Comment by sorooris** [comment]
> GIF is back!

[ALRIGHT](https://youtu.be/6M6samPEMpM?t=113)!
