### ISSUE TITLE
Firmware update/installing new firmware is not showing to which FW version you are updating to

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#4022]
**Describe the bug**
When you are trying to update your FW or when you have a new device and you want to install a FW on your device, Suite is not showing you to which version you are updating to. There is just a blank space.

**Steps to reproduce:**
1. Go to settings>device
2. Try to update your device (even if you have up to date FW version)
3. The modal that opens up doesn't show the version you are updating to

**Info:**
 - Suite version: web 21.7.1 (3d90909aa68da250490f474b2d4cab02c0aad272)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.0 regular

**Expected result:**
Firmware update modal should show to which version you are updating to.

**Actual result:**
Firmware update modal isn't showing to which version you are updating your device.

**Screenshots:**
Firmware reinstall
![image](https://user-images.githubusercontent.com/48477147/125442581-e9eaef75-dff5-4ea0-830a-cb989cf224ae.png)

Firmware update
![image](https://user-images.githubusercontent.com/48477147/125442691-eeecc44c-2ed6-432d-af4b-3f74202c0b26.png)

Onboarding
![image](https://user-images.githubusercontent.com/48477147/125442768-a71594d9-25f8-46ed-9a18-3c8833bbb9cf.png)

**Comment by tsusanka** [comment]
Whis won't get resolved by any chance by simply adding the new firmwares (planed for tomorrow) right? Asking no one in particular, just brainstorming.

**Comment by sorooris** [comment]
It was functional in [this commit](https://github.com/trezor/trezor-suite/commit/ca85ae5c485fd0291952f50bc9d7a06076fddaa4), see this [comment](https://github.com/trezor/trezor-suite/issues/3914#issuecomment-877785274).

**Comment by tsusanka** [comment]
Uf that is very weird! We either broke it by 7adfe196624ad0a274697a8cbd6a6d2231fbc607 or 3d90909aa68da250490f474b2d4cab02c0aad272. Probably the first thing.

**Comment by tsusanka** [comment]
Fixed in #4025, will be on staging tonight.

**Comment by tsusanka** [comment]
On staging.

**Comment by tsusanka** [comment]
On staging.

**Comment by STew790** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.7.1 (1abd1be26f5ae166ec910fe193c4a804d5949a86)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.6 regular
 
 Updating FW
![image](https://user-images.githubusercontent.com/48477147/125588994-c535786d-c198-4077-a95a-5f9bc113b35a.png)

Onboarding (Installing new FW)
![image](https://user-images.githubusercontent.com/48477147/125589174-9cdfe2c8-0f90-41de-9fd2-5658dba035c5.png)
