### ISSUE TITLE
Wrong wording when reinstalling firmware

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#4023]
**Describe the bug**
When you are reinstalling firmware, Suite tells you that new version is available and you can update your firmware even though you have the latest firmware version installed.

**Steps to reproduce:**
1. Open Suite
2. Connect a device with latest available firmware
3. Go to Settings>Device
4. Click on "Up to date" button
5. Firmware update modal opens up with wrong wording (see screenshot)

**Info:**
 - Suite version: web 21.7.1 (3d90909aa68da250490f474b2d4cab02c0aad272)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.0 regular

**Expected result:**
Suite tells you that your firmware is up to date and that you can reinstall your firmware if you want to.

**Actual result:**
Suite tells you that new firmware version is available and that you can update your firmware now.

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/125444846-48a19bcc-a7bd-484e-b5ed-556035245203.png)

**Comment by matejkriz** [comment]
@alex-jerechinsky please update `TR_FIRMWARE_REINSTALL_FW_DESCRIPTION` translation...

**Comment by jerechinsky** [comment]
Sorry. Done now.

**Comment by jerechinsky** [comment]
I'll actually close it when someone syncs crowdin.

**Comment by bosomt** [comment]
@STew790 can we close it ?

current wording:

<img width="646" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/131315045-d9a2c0e9-afb3-422b-8712-b17c2c714896.png">


<img width="635" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/131263054-cdadb671-c019-4776-8593-7d4025e77ed8.png">

**Info:**
 - Suite version: desktop 21.9.0 (f9ecf819ac9cc809aa78295793c065c508f74e72)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 + 2.4.1 regular

**Comment by STew790** [comment]
Yes, I think this is sufficient. I'm closing it.
