### ISSUE TITLE
Suite Guide further improvements 🍰

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#4027]
**Describe the bug**
Found a couple of things when testing #3817 that could be further improved in Suite Guide:

- Redirect to a different part of the Guide - namely seed,
- Consistency of hyperlinks,
- Redirect to a hero page and then to wiki - btc-only firmware,
- How to tackle external links and links to wiki - do we even want to redirect to wiki?
- Order of the topics/articles,

**Screenshots:**
Seed redirect does not work - i'd expect the corresponding article in the Guide to be opened:
![image](https://user-images.githubusercontent.com/10185314/125480800-ab7efa96-5306-479c-bd08-479e7d03d012.png)

Consistency of hyperlinks - external links are usually displayed as hyperlinks (without the whole URL), however there are some exceptions; namely supported coins with the whole https://trezor.io/coins/ shabang:
![image](https://user-images.githubusercontent.com/10185314/125482390-191e59ee-b472-423e-91dc-e969ad907868.png)

Redirect to a hero page and then to wiki - btc-only firmware:
![image](https://user-images.githubusercontent.com/10185314/125482334-f46529ac-8f44-4964-854f-7d687eba5269.png)
![image](https://user-images.githubusercontent.com/10185314/125482354-6d05c063-d868-401b-8a39-ace9977a4d2b.png)
![image](https://user-images.githubusercontent.com/10185314/125482368-7b21c272-6095-4791-b333-dd7f722ea0ef.png)

How to tackle external links and links to wiki - do we even want to redirect to wiki?
![image](https://user-images.githubusercontent.com/10185314/125482576-7bbf0c01-97a6-45b4-9c0a-0eb5f2182f0c.png)

Order of the topics/articles - I'd expect the topics to be in the order they're encountered during onboarding, i.e. Single Backup, Shamir Backup, PIN, Passphrase:
![image](https://user-images.githubusercontent.com/10185314/125483329-90c0b7eb-a960-460e-a182-85eddb5401ed.png)

**Info:**
 - Suite Version: app 21.7.1 3d90909a
 - OS: macOS Big Sur 11.4
 - Bridge: Suite-bundled
 - Firmware Version: any (tested model T 2.4.0)

**Comment by sorooris** [comment]
Another improvement/feature request:
Open external links in new tab (web Suite) - currently any external links in the Guide are opened in the same tab.

**Comment by tomasklim** [comment]
There is a followup issue #3992 for feature requests

**Comment by sorooris** [comment]
Cool, thanks! Closing this one then :)
