### ISSUE TITLE
Add camera selector for Trezor Suite app

### ISSUE THREAD

**Issue by cryptomar1o** [trezor/trezor-suite#4029]
**Describe the request**
With multiple cameras, it is not possible to change which camera is being used by Trezor Suite to scan a QR code. It may be causing difficulties especially when some virtual cameras are installed on the computer.

**Describe the solution**
Add camera selector in the UI of the Trezor Suite application.

**Info:**
 - Suite Version: web 21.7.1 [3d90909](https://github.com/trezor/trezor-suite/commit/3d90909aa68da250490f474b2d4cab02c0aad272)
 - Firmware Version: any (tested model T 2.4.0)

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
