### ISSUE TITLE
Activate automatic formatting of markdown files in docs folder

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4031]
Currently, we have disabled automatic formatting of markdown files in docs folder. 

Let's remove this rule in `.prettierignore` file and reformat all markdown files.

**Comment by bosomt** [comment]
@tomasklim is there anything that can/needs to be tested by QA ?

**Comment by tsusanka** [comment]
@bosomt just a code stuff, moving to Approved
