### ISSUE TITLE
Remote message system config got incorrectly rolled back

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4032]
**Describe the bug**
The newest sequence of message system was `2` which contained information about WebUsbPlugin problem on macOS in Chrome 91. This config was deleted and replaced by old config with sequence `1`.

**Info:**
 - Suite Version: 21.6.2

**Steps to reproduce:**
1. Open Suite instance which has config with sequence 2 in indexDB
2. See the error in the console

or
1. Open Suite
2. Open DevTools>Network
2. Block remote config URL (https://data.trezor.io/config/stable/config.v1.jws)
3. Reset app and refresh
4. Unblock remote config URL
5. Refresh
6. See the error in the console

**Screenshots:**
![image (2)](https://user-images.githubusercontent.com/33235762/125615757-04e8ef4d-31b7-457d-96e4-338d315910ae.png)

**Comment by tomasklim** [comment]
Fix #4019

**Comment by tomasklim** [comment]
Configs with sequence 3 available at
 https://data.trezor.io/config/stable/config.v1.jws
 https://data.trezor.io/config/develop/config.v1.jws

**Comment by sorooris** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/10185314/125844949-b91b84c3-2c51-4a2b-9cda-cbc8da94eea3.png)

Suite: web 21.7.1 24cc565a
Browser: Chromium 91.0.4472.77
OS: NixOS
Device: model One 1.10.2
