### ISSUE TITLE
ETH  transactions are not visible at history

### ISSUE THREAD

**Issue by bunkaq** [trezor/trezor-suite#4036]
Windows version 21.6.1 and 21.7.1 have same issue. I do not see my incoming transactions on ETH anymore. Last incoming transaction I can see is May 2021 and I have weekly ETH transaction comming from ethmine.org. It was showing fine at dashboard and transaction history up to May but nothing is showing at June/July even there are transactions and amount of ETH at wallet is growing.

I am using Trezor One with 1.10.1 and today upgraded to 1.10.2 but same issue.
I do not see same issue with VTC for example where history and dashboard is working fine with transactions.

**Comment by bunkaq** [comment]
I probably understand why from this picture 

![image](https://user-images.githubusercontent.com/83916838/126028868-a4f21abf-a32b-4ea0-98cd-d59d74fda7ef.png)

**Comment by bosomt** [comment]
@bunkaq  can you please give us more information ? 
We are currently not facing any ETH issues related to Suite.
Were your transaction already confirmed during your query ? In recent months pools of unconfirmed transactions holds more than 300k txs and they are not synced .

**Comment by bosomt** [comment]
@bunkaq can you please give us more information or at least Eth address that we can import and check how it behaves in current version of suite ? Or we can close this issue ?

**Comment by jerechinsky** [comment]
Hi @bunkaq, I'm sorry, but your bug report lacks essential information. If you don't use the bug report template, we can't help you nor fix the bug. I will close this issue, but feel free to open a new one and fill the bug report form.

You can use this feature to get basic info like Suite and FW version pre-filled:
https://satoshilabs.notion.site/How-to-open-issue-from-Suite-eb22fda0487349cc8bf92b3964740ab2
