### ISSUE TITLE
Settings > Passphrase: missing space

### ISSUE THREAD

**Issue by rating89us** [trezor/trezor-suite#4037]
![image](https://user-images.githubusercontent.com/45968869/125686844-9cfaca68-fd7c-460e-885b-7d797a4f21b7.png)

**Comment by jerechinsky** [comment]
Fixed now. Thanks @rating89us.

**Comment by jerechinsky** [comment]
Actually not fixed but still a duplicate of #4007 so I'm keeping it closed.
