### ISSUE TITLE
Improve troubleshooting step in onboarding

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#4039]
In the desktop app, it would be more fitting to suggest that a user quits and reopens their app rather than "refreshes". 

If a user is on desktop, please change the troubleshooting subtitle to: "After closing other browser tabs and windows, try quitting and reopening the Suite app."

![image (3)](https://user-images.githubusercontent.com/75733878/125771804-db7c2d6f-6b30-4d16-82a4-2ad839ea63df.png)

**Comment by bosomt** [comment]
**QA NOK**

I don't see any information about app restart in current dev master app.

**Info:**
 - Suite version: desktop 21.8.0 (e1c710e0c6bbd96b0e7970c15e3650c092aa0c83)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular
 - 
<img width="603" alt="Screenshot 2021-07-26 at 19 13 27" src="https://user-images.githubusercontent.com/31506317/127031161-e8b935fb-adf2-49f0-96d2-acb3b6a8075c.png">

**Comment by marekrjpolak** [comment]
It's only when the "device detected in incorrect state", which is displayed e.g. when the device is acquired in another tab/browser:

- open Suite in new tab, go to menu and select any operation which must be confirmed on the device
- while waiting for confirmation, open Suite in other tab/as a desktop application

The subtitles in the two 'tips' should be different in browser and in desktop app. 

![image](https://user-images.githubusercontent.com/26326960/127048339-9226889d-e599-4e55-ae18-be76461b636a.png)

**Comment by bosomt** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/31506317/128016718-9c216d2d-688c-4368-9899-f451bb4a8bac.png)

**Info:**
 - Suite version: desktop 21.8.0 (e9976a3052507d8b888370ceb11eaa61bae5d775)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.4.1 regular
