### ISSUE TITLE
improve @trezor/rollout FW validation

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#4045]
in rollout@1.2.0 validation of FW binary  was added.
i think this validation need some improvements basing on previous implementations.

header validation python-trezor:
https://github.com/trezor/trezor-firmware/blob/master/python/src/trezorlib/firmware.py

header validation old-wallet:
https://github.com/satoshilabs/mytrezor/blob/10d5e61b98df8067854d92669cab489f80c3c80c/app/scripts/utils/validate.js#L18

cc: @mroz22 @marekrjpolak

**Comment by marekrjpolak** [comment]
Was partially resolved in #4085 and will be improved in #3706.
