### ISSUE TITLE
Improve copy when installing intermediary FW

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4047]
**Describe the bug**
Due to https://github.com/trezor/trezor-firmware/issues/1674 there is an extra confirmation that we did not take into account AFAIK. This means that Suite says "Installing firmware" once however user sees two "Installing firmware" screens with a confirmation in the middle. This is confusing and seems like you are installing two firmwares (which you actually are, first Intermediary and then the actual) but we are hiding this fact from the user.

**Info:**
 - Remembered Wallet: no
 - Suite Version: both, 24cc565a3badd85ab48b30348022471dfd85f90e
 - Firmware Version: T1, blank from the factory with BL 1.4.0

**Steps to reproduce:**
1. Buy a Trezor
2. Do an onboarding

**Expected result:**
Suite informs about what is happening.

**Actual result:**
I see Suite informing about firmware installation but I see two installations on the device.

**Note(s):**
Note that we should not come up with some crazy complicated solutions as these firmwares will phase out (we'll also start to manufacture devices with 1.8.0/1.10.0 BLs). It would be nice to alter the copy however a bit not to confuse users. We can even confess that we are installing two firmwares if needed...

**Comment by tsusanka** [comment]
@trezor/qa could you please make a complete video of what is happening on the device and in Suite when onboarding with a completely new device?

@sorooris assigning to you, please reassign as you see fit. Low prio.

**Comment by sorooris** [comment]
aye aye captain, @STew790 will look into this

**Comment by STew790** [comment]
Hello, I hope this will suffice. Let me know if it should be any different, please.

[![IMAGE ALT TEXT](http://img.youtube.com/vi/QuOF7StErCM/0.jpg)](https://youtu.be/QuOF7StErCM "Video Title")



**Info**:
 - Suite version: desktop 21.7.1 (24cc565a3badd85ab48b30348022471dfd85f90e)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model 1 1.10.2 regular

**Comment by tsusanka** [comment]
@matejzak on the video from @STew790:

- At about 0:32 we inform the user about "Installing firmware" 
- At 0:38 we inform "New firmware successfully installed"
- At 1:00 we ask the user for a confirmation on the device again with the prompt "Install new firmware?"
 
I think this needs to be confusing as the user was just informed the firmware has been installed and now confirms another FW update :thinking:.

Note that we can't fix this in FW, see https://github.com/trezor/trezor-firmware/issues/1674, so we need to fix in Suite.

**Comment by tsusanka** [comment]
@STew790 btw I see two imperfections on the video and I think they would deserve their own issues:
1. At 0:21 you hover the FW version and it shows the changelog. It shows v1.6.3 which seems as a bug. Could you confirm and open an issue? (if there isn't one yet)
2. At 0:35 we display the same gif for cases when the button should be pressed. I find that confusing. Could you confirm and open an issue? (if there isn't one yet)

**Comment by STew790** [comment]
@tsusanka Thanks for pointing that out, I actually saw the 1. after I saw the video as well and I want to try it again with a new device again, just to be sure.
Regarding 2., that's true, I didn't even realize it. There should be definitely just a gif/video with the device being connected. I will open an issue as well

**Comment by STew790** [comment]
Forgot to add, both issues here:
https://github.com/trezor/trezor-suite/issues/4075
https://github.com/trezor/trezor-suite/issues/4074

**Comment by tsusanka** [comment]
I am changing priority to LOW, as new Trezor 1 models are now being shipped with 1.10.0 bootloaders. So this concerns only old devices that were still not updated from February 2019 (1.8.0).

Maybe it is not worth fixing at all, up to the Product team I guess.

**Comment by hynek-jina** [comment]
The need for this modification is no longer actual.
