### ISSUE TITLE
Accounts - Old copy when all coins are disabled

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#4051]
**Describe the bug**
Placeholder text is displayed in Account Overview when all coins are disabled.

**Info:**
 - Suite Version: app + web (tested web 21.7.1 24cc565a)
 - Browser: Chromium 91.0.4472.77
 - OS: any (tested NixOS 21.05)
 - Bridge: any
 - Firmware Version: any

**Steps to reproduce:**
1. Disable all coins in Settings -> Crypto,
2. Navigate to Accounts -> Overview,
3. Observe.

**Expected result:**
Actual up-to-date copy is displayed.

**Actual result:**
"It’s so empty here. Can’t even describe the emptiness I’m feelin’ here… You can either add new account (that will enable selected coin) or enable any coin in Settings."

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/126162032-2f7f8539-8855-4b38-9260-595406810cc4.png)

**Comment by STew790** [comment]
**QA NOK**

Issue still present.

**Info:**
 - Suite version: web 21.9.2 (cc85c69e3d6556e673c4d30f39953179f690b663)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.2 regular

**Comment by jerechinsky** [comment]
Thanks! I've updated the copy in Crowdin. Please test it only after freeze (6th of October) as the changes are not reflected yet.

**Comment by STew790** [comment]
**QA OK**
The copy in the Portfolio section is changed, although, @alex-jerechinsky  I am not sure if the "error" copy in the Assets section shouldn't be changed as well, because the "Assets were not loaded properly" might be confusing as well.

**Info:**
 - Suite version: web 21.10.0 (35264277873f8c09078d71f31ac11f07d467950f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.3 regular
 
 **Screenshot**
 
![image](https://user-images.githubusercontent.com/48477147/136039364-11e45b93-3aa5-4df3-a377-a08fd21ddc7b.png)

**Comment by bosomt** [comment]
and of course we need to change it in all language versions 🤷🏿‍♂️ 

`Je tu tak prázdno. Ani nedokážu popsat tu prázdnotu, kterou tu cítím…`

<img width="992" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136447473-49ef2e2e-96f0-42bd-94e8-653aefb4166f.png">

**Info:**
 - Suite version: desktop 21.10.1 (4b0ade9e0732a14970bd484465b1658044cdea30)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by jerechinsky** [comment]
Yes, it's fixed in the new copy. The changes will reflect once the new copy is uploaded to Suite.

**Comment by bosomt** [comment]
so far not updated, in latest version, we will check it after sync and release of Suite

**Info:**
 - Suite version: desktop 21.10.1 (30698b091e0eff94a2adddf92b15998092d7a3c9)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model 1 1.10.3 regular

**Comment by wendys-cats** [comment]
**QA OK** for staging, waiting for app

**Info**
**Suite version:** web 21.10.1 aa3adfa347d0416f970a7fae720d3350f29f8916
**Browser:** Chrome Version 94.0.4606.81 (Official Build) (64-bit)
**OS:** Windows 10
**Device:** T1 1.10.3


![image](https://user-images.githubusercontent.com/58593111/137097298-088a4d73-89f6-43ac-88e4-e26edb324db2.png)

**Comment by jerechinsky** [comment]
It's fixed for me on staging.

<details>
<summary>Screenshots</summary>

![Screenshot 2021-10-13 at 10 32 45](https://user-images.githubusercontent.com/75733878/137097717-173f7bb9-77e0-4efa-bc09-98386c1b4684.png)
![Screenshot 2021-10-13 at 10 35 39](https://user-images.githubusercontent.com/75733878/137097681-a5ad88ba-59fa-4f60-80e4-fb3210ebd63d.png)
</details>


 
 - Suite version: web 21.10.1 (aa3adfa347d0416f970a7fae720d3350f29f8916)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1080
 - Device: model T 2.3.6 regular

**Comment by STew790** [comment]
**QA OK**
Linux app is correct.

**Info:**
 - Suite version: desktop 21.10.1 (aa3adfa347d0416f970a7fae720d3350f29f8916)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.2 regular
 
 
![image](https://user-images.githubusercontent.com/48477147/137099005-90a10239-c640-473c-affd-9be8ab9e9ffa.png)
![image](https://user-images.githubusercontent.com/48477147/137099090-50f755c7-3134-4f34-815b-e5a9c3abe04a.png)

**Comment by bosomt** [comment]
**QA OK** on production

But it looks like it was not changed in Spanish language. I'm not sure who's responsible for that but from now on we have to change it manually in every language ? 🤣 

<img width="475" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/137448669-eeff0f29-2403-40aa-a885-6ebf7cb296db.png">

Esto está muy vacío. No puedo ni describir el vacío que siento aquí…
