### ISSUE TITLE
Suite wallet label import/export

### ISSUE THREAD

**Issue by czee** [trezor/trezor-suite#4055]
It would be nice to have labels imported and exported between the Suite Wallets of 2 different instances of a Trezor model T.

Background:
I updated to 2.4.1 of the Trezor model T and got a USB read error and had to recover the device. I'm not sure why, but I believe something with the USB connection made the device disconnect. Maybe this needs a new Github issue? I've previously upgraded without any problems.

![image](https://user-images.githubusercontent.com/2141379/126323074-06782e2f-26a6-465a-acd9-5ea588710351.png)

**Comment by mroz22** [comment]
Hello, for the reason of RSOD you can check this article https://wiki.trezor.io/RSOD

Once you recover your device (the same device or a new one) from your seed, you should be able to see all of your previous labels. 

So I think this is not a feature request actually.
