### ISSUE TITLE
Buttons on T2 in Welcome screen

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4057]
**Describe the bug**
Text: Please make sure you are not holding any buttons while connecting your device.

**Info:**
 - Suite Version: 21.7.1
 - Device: Trezor T

**Steps to reproduce:**
1. Connect Trezor T in Bootloader
2. Open troubleshouting

**Screenshots:**
![Uploading Screenshot 2021-07-20 at 16.36.43.png…]()

**Comment by marekrjpolak** [comment]
In order to properly fix the issue, FIRMWARE_CONNECT_IN_NORMAL_MODEL_1 and FIRMWARE_CONNECT_IN_NORMAL_MODEL_2 must be updated in all existing translations in Crowdin.
