### ISSUE TITLE
Copy improvement for plural in other languages

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#4059]
The string `TR_PENDING_TX_HEADING` shows as the following in crowdin:

`Pending {count, plural, one {transaction} other {transactions}}
`

It only allows translators to use plural for the `transaction` word but not for `pending`. Please allow translators to also add the plural form of `pending`.

**Comment by bosomt** [comment]
@alex-jerechinsky @szymonlesisz  anything that can/need to b tested on our side or I can move it to approved section ?

**Comment by jerechinsky** [comment]
Not sure how this could be tested. Please move to the approved section.
