### ISSUE TITLE
Add Spanish 🇪🇸

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#4060]
Now that Spanish is nearly finished thanks to @FrankyFFV, let's add it to Suite. 

Please download the Spanish translation from crowdin and add it to the language switcher in Suite. Please add a beta tag so it says `Spanish (BETA)`.

**Comment by bosomt** [comment]
**QA OK**

Muy bien!

**Info:**
 - Suite version: web 21.8.0 (e9976a3052507d8b888370ceb11eaa61bae5d775)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.4.1 regular
