### ISSUE TITLE
Allow translators to pick their language.

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#4061]
Suite already has a great feature that Maroš initially built that allows translators to click any string and be redirected into crowdin to translate it. 

However, changing the language requires the translator to use a command in the console. 

For example `__NEXT_REDUX_STORE__.dispatch({type: "@suite/set-language", locale: "ru"})` for russian. 

Let's add a dropdown menu in the hidden settings of suite so it's easier for the translators to use it. The dropdown menu should contain a list of languages so a translator can easily choose which language they want to translate into. Please put it right below the translator mode toggle. Title it "Translation mode language". 

Could we also please make sure that the language setting persists over reloads of the app? While translator mode remains on across sessions, the selected language gets forgotten each time Suite is closed.

**Comment by jerechinsky** [comment]
@marekrjpolak explained to me that the aforementioned command changes the language of whole Suite, not just the link that redirects to Crowdin. Because of that we have agreed that we will put another language picker in the debug settings, except it will show all languages, even the unfinished ones. This will allow translators to pick their language, see the progress done on the translations and translate the remaining strings that are still in english, which is the fallback language for when a translation is missing. Unlike the normal language picker which will only show finished languages.

**Comment by bosomt** [comment]
**QA OK**

DEBUG:
![image](https://user-images.githubusercontent.com/31506317/128007408-57921ca5-7735-4bd5-b34b-28285f38feb0.png)

**Info:**
 - Suite version: web 21.8.0 (e9976a3052507d8b888370ceb11eaa61bae5d775)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.4.1 regular
