### ISSUE TITLE
Add account: Improvements

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#4067]
- [x] `Activate more coins `font doesn't seem to be correct (weight)
- [x] Plus sign is not vertically alligned with `Activate more coins`  
- [ ] Improve animation from the `activate more coins` button

<img width="227" alt="Screen Shot 2021-07-22 at 15 53 06" src="https://user-images.githubusercontent.com/29627086/126660265-b973f086-f0ef-400c-ad5e-f3399a571b43.png"> 

***  

- [x] The boarder of the coin seems thinner than designed (should be 1.5px) for both states (not/selected) 

<img width="147" alt="Screen Shot 2021-07-22 at 15 57 04" src="https://user-images.githubusercontent.com/29627086/126660960-a4d23129-4058-408a-8da0-c381016e4848.png">

<img width="182" alt="Screen Shot 2021-07-22 at 15 56 44" src="https://user-images.githubusercontent.com/29627086/126660898-e8cc3891-f4f6-4897-b1d7-1569185e677e.png"> 

*** 

- [ ] The label `activate more coins` underline indicate there should be a tooltip

<img width="178" alt="Screen Shot 2021-07-22 at 15 58 45" src="https://user-images.githubusercontent.com/29627086/126661221-1261ec61-13b0-4bbc-a1b8-bbe8d02951a9.png"> 

- [x] Tesnet explanation in tooltip (underline)

<img width="422" alt="Screen Shot 2021-07-22 at 16 20 54" src="https://user-images.githubusercontent.com/29627086/126664695-f3ba83d3-1ec0-40d2-89f2-3c0bf7d7112d.png">

- [ ] Supported tokens tooltip needs to link to the article in Suite Guide

- [x] Too much spacing (to be discussed)

<img width="842" alt="Screen Shot 2021-07-22 at 16 15 45" src="https://user-images.githubusercontent.com/29627086/126663879-2fae66e8-2a73-444e-a1ea-9c972fdd2cce.png"> 

- [x] Hover on "X" to close modal 

- [x] Remove these label below the account type

<img width="684" alt="Screen Shot 2021-07-22 at 16 28 57" src="https://user-images.githubusercontent.com/29627086/126665926-af0b580e-da36-4ee9-997d-41f5e92d04e8.png">

- [x] Remove account type from the coin bubble 

<img width="233" alt="Screen Shot 2021-07-22 at 16 30 24" src="https://user-images.githubusercontent.com/29627086/126666141-5100ba04-40d6-4110-b6a0-4a643adf74fd.png">

- [x] Labels not vertically aligned

<img width="191" alt="Screen Shot 2021-07-22 at 16 31 48" src="https://user-images.githubusercontent.com/29627086/126666517-3bdc3584-134e-4796-9e55-1d441a850cdf.png">
 
 

- [ ] Remove plus sign from button 

<img width="177" alt="Screen Shot 2021-07-22 at 16 33 28" src="https://user-images.githubusercontent.com/29627086/126666625-c424a1b7-7665-4e32-bfab-975220a5c715.png">

- [ ] Get rid of the "TEST COIN" description

<img width="236" alt="Screen Shot 2021-07-22 at 16 34 13" src="https://user-images.githubusercontent.com/29627086/126666683-a08daa8e-af47-48af-95c0-3db1fb39d258.png">
 

- [ ] Labels (select coin, account type) have different font weight

<img width="525" alt="Screen Shot 2021-07-22 at 16 36 51" src="https://user-images.githubusercontent.com/29627086/126667115-6ea03b7b-2dff-4993-8f68-d4a9b4475bb2.png">

- [ ] Disable coin bubble when empty account already created (as oppose to telling the user in 2 steps by disabling the primary button) › Propose use the accounts that can be activated (= those that can have the account added)

**Comment by CruiseMan** [comment]
@matejzak How do I add Binance Smart Chain here ? UX I so non intuitive
<img width="720" alt="Screen Shot 2021-09-03 at 3 50 11 PM" src="https://user-images.githubusercontent.com/15807643/132072250-53462fb2-2070-4feb-ae5f-3453776f5746.png">

**Comment by glacierbits** [comment]
@CruiseMan Binance Chain is not supported by Trezor Suite. Visit https://trezor.io/coins/ for more info.

**Comment by CruiseMan** [comment]
> @CruiseMan Binance Chain is not supported by Trezor Suite. Visit https://trezor.io/coins/ for more info.

What does green check make means in this case, UI confusing sir ?
<img width="1161" alt="Screen Shot 2021-09-04 at 2 09 42 PM" src="https://user-images.githubusercontent.com/15807643/132108121-72350019-c66f-447b-b979-e0420329c95d.png">

**Comment by karpaterna** [comment]
@CruiseMan  supported by device, not trezor suite wallet

**Comment by CruiseMan** [comment]
> @CruiseMan supported by device, not trezor suite wallet

What does it mean and why it's not supported ?

**Comment by karpaterna** [comment]
@CruiseMan ask here please, github issue is not the right place - https://forum.trezor.io/

**Comment by bosomt** [comment]
Looking forward for design change of `activate more coins` and `testnet coins` button design.
One is designed as link and one not. One is drop down menu and one has `x` button

https://user-images.githubusercontent.com/31506317/135964760-b8922545-160f-4476-8e31-ce77ea0276a6.mov

**Comment by sime** [comment]
@dahaca Please create a follow issue for the remaining tasks, then this can be closed.

**Comment by dahaca** [comment]
@sime https://github.com/trezor/trezor-suite/issues/6461

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.10.0 (695db8c7497509ff3ba3c19776e40f3bb9c3cd54)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31
