### ISSUE TITLE
Settings is jumping when modal is opened/closed

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4071]
**Describe the bug**
Navigation bar in Settings changes from "Application |  Device | Coins" to "<- Back" button when modal is opened.

**Info:**
 - Suite Version: 21.7.1

**Steps to reproduce:**
1. Go to settings/device
2. Update firmware

**Expected result:**
Navigation bar remains the same or at least "<- Back" have same height

**Screenshots:**
![Screenshot 2021-07-26 at 9 06 02](https://user-images.githubusercontent.com/33235762/126988313-dbcd2e48-b119-4c27-bc12-1a875721986f.png)
![Screenshot 2021-07-26 at 9 05 56](https://user-images.githubusercontent.com/33235762/126988316-2b7633e9-a0f0-4855-8dd2-a4169d161709.png)

**Comment by STew790** [comment]
**QA OK**

"Back" button is not present anymore when modal is opened. Although, the "floating" menu with "Application" "Device" "Crypto" disappears, not sure if this is intended or not.

![image](https://user-images.githubusercontent.com/48477147/133432280-ee9c12a4-c85c-41e3-acb1-9a78b0883c40.png)


**Info:**
 - Suite version: web 21.9.2 (cc85c69e3d6556e673c4d30f39953179f690b663)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.2 regular

**Comment by jerechinsky** [comment]
I'm observing the same thing as @STew790, which seems like intended behaviour. Reopen the issue if you disagree. 

![Screenshot 2021-09-21 at 23 06 59](https://user-images.githubusercontent.com/75733878/134247904-b923c032-3b60-43d8-bba3-3822f27de3e5.png)
     
**Info:**
 - Suite version: desktop 21.9.2 (6b68428cc0e94f3c636df43f4f1add14b5f6fab3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1080
 - Device: model 1 1.10.3 regular
