### ISSUE TITLE
Usage data description acts incomplete

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4072]
**Info:**
 - Suite Version: 27.1.0

**Steps to reproduce:**
1. Go to Settings / Application

**Expected result:**
The sentence ends with `.`

**Actual result:**
`Trezor Suite does NOT track any balance-related or personal data, all anonymously`

**Note(s):**

**Usage data** title acts vague and description acts incomplete incomplete.

I would suggest to unite it with onboarding 
![Screenshot 2021-07-26 at 14 39 42](https://user-images.githubusercontent.com/33235762/126990186-cac5d2e8-63d8-4bbb-8ddc-befe31b006e2.png)

or 

changing it to something like **Share usage** and add something like `To help us improve Trezor Suite, you can let your application send us anonymous information about how you use it. We do NOT track any personal or balance-related data.` into the description to motivate users.

**Comment by ravinalamada** [comment]
@tomasklim, I added the dot in the analytic description message. If there are other things that I should fix in this issue, please let me know.

**Comment by tomasklim** [comment]
Thank you for your help @ravinalamada! However, this issue will be solved by another issue: https://github.com/trezor/trezor-suite/pull/4086 😢 

Closing.
