### ISSUE TITLE
Installing firmware onto new device shows wrong changelog information on hover

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#4074]
**Describe the bug**
When you are trying to update from older firmwares or installing a new firmware onto new devices (out of the box) the changelog, on hover, states wrong version and wrong changelog info. See screenshots.

**Info:**
 - Remembered Wallet: yes/no
 - Suite Version: web/app 21.7.1
 - Browser: Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
 - OS: Win32
 - Bridge: 2.0.27
 - Firmware Version: model 1

**Steps to reproduce:**
1. Connect a new device or a device with an older (older than 1.6.3) firmware
2. Follow the instructions Suite gives you until you get to firmware install or firmware update and hover over the 1.10.2 version
3. It shows info about 1.6.3 version (as can be seen on screenshot)

**Expected result:**
When installing new firmware or updating to a new firmware the hover info shows the correct firmware version and info.

**Actual result:**
When installing new firmware or updating to a new firmware the hover info shows wrong firmware version and info.

**Screenshots:**

![image](https://user-images.githubusercontent.com/48477147/127012286-79ff3d28-4ba4-457c-8197-93b1a36b3161.png)

![image](https://user-images.githubusercontent.com/48477147/127012336-997b3460-08d5-4ac1-b7f9-c2da11032233.png)

**Comment by sorooris** [comment]
Might be related to #3911 :eyes:

**Comment by bosomt** [comment]
same behaviour for model TT

<img width="572" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/128978719-8f86850a-149e-4e64-b3d8-2d14fbd5f5df.png">


**Info:**
 - Suite version: web 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.0.5 regular

**Comment by matejkriz** [comment]
related to https://github.com/trezor/trezor-suite/issues/4135

TT should be fixed now (21.9.0), changelog was correct on the screenshot from @bosomt, but the offered version was wrong and should have been 2.0.5 -> 2.1.1.

for model 1 the changelog is broken – it doesn't count with intermediary FW. That has to be fixed.

**Comment by bosomt** [comment]
@matejkriz  yes it needs to 

<img width="447" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/131960834-5accdfa2-260d-445f-90a2-08921051be24.png">

**Info:**
 - Suite version: desktop 21.9.1 (c1fd2626a782c05c014d293964e09a4613e3040e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - fresh /never used device model One

**Comment by wendys-cats** [comment]
QA OK for  TT, T1 WIP

**Suite:** WEB 21.10.0 62b9f7dab878b6edd8ff1d8e58ca6ac84f1b9fb4 branch fix/4074
**OS:** Windows 10
**Device:** TT and T1

Tried TT 2.0.5 update OK
         TT 2.1.1 update OK
         TT 2.4.0 update OK
         T1 1.10.1 update OK

**Comment by STew790** [comment]
**QA OK**

Suite shows the correct changelog information when updating from an older firmware. In this case it is uninitialized new device with BL 1.4.0.

**Info**
 - Suite version: web 21.10.1 (4b0ade9e0732a14970bd484465b1658044cdea30)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.4.0 BL

![image](https://user-images.githubusercontent.com/48477147/136393658-7d80c846-d2b1-4cbf-9b8c-f6ffa1f5793b.png)
