### ISSUE TITLE
Tooltip › Guide

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#4076]
The idea: Link from relevant tooltips to the respective article in Suite Guide. 🎉   

**Design:** [Zeplin
](https://zpl.io/bAKvAMx )
**Animation:** [Figma prototype](https://www.figma.com/proto/MmQtIPoIggyJkBm7vMUHpI/Neue-Desktop?page-id=0%3A1&node-id=7093%3A104058&viewport=-4441%2C66818%2C1.1297415494918823&scaling=min-zoom&starting-point-node-id=7093%3A104058&show-proto-sidebar=1)

**Comment by wendys-cats** [comment]
**QA OK**

Tooltips that do not have an article counterpart in Suite Guide do not have a "Learn" link. However, there are instances where there is NO tooltip for the feature, even though a Suite Guide article exists, for example Transaction fees. @matejkriz do you think these tooltips will be added later on? It seems like a pity not to utilise these articles more.

**Suite version:** web 21.8.1 8dfc3fbf9faa870f6c7e6017a63ffeb311cf5b16
**Browser:** Chormium Version 88.0.4324.182 (Official Build) (64-bit)
**OS:** NixOS
**Device:** TT 2.4.2

**Comment by matejkriz** [comment]
> **QA OK**
> 
> Tooltips that do not have an article counterpart in Suite Guide do not have a "Learn" link. However, there are instances where there is NO tooltip for the feature, even though a Suite Guide article exists, for example Transaction fees. @matejkriz do you think these tooltips will be added later on? It seems like a pity not to utilise these articles more.
> 
> **Suite version:** web 21.8.1 [8dfc3fb](https://github.com/trezor/trezor-suite/commit/8dfc3fbf9faa870f6c7e6017a63ffeb311cf5b16)
> **Browser:** Chormium Version 88.0.4324.182 (Official Build) (64-bit)
> **OS:** NixOS
> **Device:** TT 2.4.2

It is probably question on @matejzak, but more links from tooltips will definitely be added gradually as more content in Guide is added...
