### ISSUE TITLE
Transaction id field 'txid' should use camelCase

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#408]
<img width="175" alt="Screenshot 2019-08-15 at 13 39 33" src="https://user-images.githubusercontent.com/6961901/63092514-43667880-bf62-11e9-9439-13828899ec66.png">

**Comment by vladimirvolek** [comment]
blockbook test

![image](https://user-images.githubusercontent.com/3112191/63113436-d5867500-bf92-11e9-896f-8f24b2d3b60b.png)

**Comment by slowbackspace** [comment]
@vladimirvolek  does that mean it is intentional (why though when every other field uses camelCase)? or just that there is the same typo? 😁

**Comment by slowbackspace** [comment]
after discussion we came to conclusion that it is not a bug, it is a feature.
