### ISSUE TITLE
tschuss-next branch issues

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#4080]
Issue for tracking bugs and defects in the /suite-web/feat/tschuss-next/ branch and builds
@trezor/qa please report in the comments using the template provided.

```
**Describe the bug**
A clear and concise description of what the bug is.

**Info:**
 - Remembered Wallet: yes/no
 - Suite Version: app/web, commit
 - Browser: , version
 - OS: system, build
 - Bridge: build version
 - Firmware Version: model , revision 

**Steps to reproduce:**
1. a
2. b
3. c

**Expected result:**
A clear and concise description of what you expected to happen.

**Actual result:**
A clear and concise description of what actually happens.

**Screenshots:**
insert here

**Note(s):**
Add any other context about the problem here.
```

**Comment by sorooris** [comment]
https://github.com/trezor/trezor-suite/issues/3185 still persists in 21.8.0 6d278ade7563485d57cd1e71ab6b2324b4305a56

**Comment by sorooris** [comment]
Closing.

**Comment by sorooris** [comment]
@bosomt found this one https://github.com/trezor/trezor-suite/issues/4096#issue-958894929

**Comment by matejkriz** [comment]
https://github.com/trezor/trezor-suite/issues/4096#issue-958894929 is not related to tschuss-next so it's completely sufficient to track it as separate issue

**Comment by matejkriz** [comment]
Accounts menu is possibly shown after the main content of /accounts page if you load suite on dashboard and switch to accounts for the 1st time?

Reported by @szymonlesisz but I wasn't able to duplicate it. Could you please give it a try, @sorooris?

Suite Version: 21.9.0  (it's related to switch from Next.js to custom build pipelines, so tschuss-next branch issue)

**Steps to reproduce:**
1. reset/disable cache
2. open app on default page (/dashboard)
3. go to Accounts page by clicking Accounts menu button
4. see if left Accounts menu is shown right aways or after the rest of the page
 
note from Szymon: you need to have non-standard resolution (width), more like a square (i got console opened)

![Peek 2021-08-05 14-48](https://user-images.githubusercontent.com/3729633/130582032-2b0c18e9-979f-45b8-bf21-555e01a7e319.gif)

**Comment by sorooris** [comment]
Unfortunately couldn't replicate the late-rendered Accounts section layout with the current 21.9.0 develop build; I tested all options I could think of to no avail, although two things I couldn't figure out on my own or wasn't sure about:
- how do I disable cache in the app? (couldn't find it in the [doc](https://docs.trezor.io/trezor-suite/packages/suite-desktop.html#runtime-flags))
- what OS and version does Szymon use? (he still uses macOS, right?)
- does the described issue depend on speed the Accounts screen is accessed? (maybe a script could replicate it better than a slow meaty human)

I even inspected the above screen recording's size and set it to that :smile: 
![image](https://user-images.githubusercontent.com/10185314/131149045-c238226f-df6e-4ae7-8a90-9a8ca0274021.png)

Unsuccessful attempt no. 69

https://user-images.githubusercontent.com/10185314/131151349-453b2a30-25f8-411d-88ba-1e3dab5782b3.mov



Suite: app 21.9.0 a06614b
OS: macOS Big Sur 11.5.2
Device: model T 2.4.1 with passphrase disabled and empty seed / all seed

**Comment by matejkriz** [comment]
@sorooris thanks for trying. You can't disable cache in the desktop app, the pages are bundled there. You can disable cache only in the web browser. I'm really sorry I didn't mention browser right away.

@szymonlesisz Have you seen it since then again?

**Comment by sorooris** [comment]
@matejkriz No worries! Brief test in the [21.9.0 develop](https://github.com/trezor/trezor-suite/commits/1f5e833a2d214388d3b0c760aa5287e5c83dbd87) web build yielded no results though, Accounts screen loaded correctly; couldn't reproduce :confused:
