### ISSUE TITLE
Install custom firmware allowed for any .bin file

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4085]
**Describe the bug**
1) you can install customer firmware that's intended for different model, can we add some size or header check before we wipe device and end with FW too big error and empty device ?
2) install firmware progress goes from 0% to 100% even it fails on device at 0%, this looks weird /and I think someone complained about that and i'm not sure if there is already issue for this UI issue.

**Steps to reproduce:**
1. Connect Trezor Model One
2. Go to Settings/Device/Install firmware
3. Select model T FW from disk.
4. Install firmware and observe Suite/Device behavior

**Info:**
 - Suite version: desktop 21.8.0 (6d278ade7563485d57cd1e71ab6b2324b4305a56)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.1 regular

**Expected result:**
You are warned or you are not allowed to install file that doesn't contain appropriate firware header 

**Actual result:**
You are allowed to load any file that has.bin extension

**Comment by marekrjpolak** [comment]
Unfortunately, it would be impractical to do full firmware file validation (as in trezorctl), so I've extracted at least the header check as you mentioned.

Should be fixed in https://suite.corp.sldev.cz/suite-web/feat/4085-firmware-validation/web/.

**Comment by bosomt** [comment]
**QA OK**

<img width="335" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/131321808-b00cd4ec-9294-44bc-a3ca-475023959ae4.png">

<img width="425" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/131321845-43b64858-d8ce-483a-bd24-fb44e2b50675.png">

**Info:**
 - Suite version: web 21.9.0 (b5f7239811167a962c440a8ef81345f2115b1c5c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular
