### ISSUE TITLE
Reworking The Passphrase Retry Option

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#4090]
**Describe the bug**
Reopening issue from [here](https://github.com/trezor/trezor-suite/issues/895#issuecomment-587405514).

Creating a new hidden wallet has two steps when it comes to entering the passphrase - first entry, and then the confirmation. 
Suite does not take into account instances when user misspelles their passphrase on the FIRST try of creating a new hidden wallet. Retry option as it is now only lets user re-enter the passphrase confirmation, which runs against the first passphrase entered. Meaning if user misspelled the first passphrase, they have to exit the process manually and start again, which should be considered a bug.

**Info:**
 - Remembered Wallet: No
 - Suite Version: 21.7.1 24cc565a3badd85ab48b30348022471dfd85f90e
 - Browser: Chromium Version 88.0.4324.182 (Official Build) (64-bit)
 - OS: NixOS 21.03
 - Bridge: No
 - Firmware Version: TT 2.4.1. public 

**Steps to reproduce:**
**1.** Click on Create hidden wallet
**2.** Enter a typo in existing passphrase (make sure the generated wallet will be empty)
**3.** Enter the correct passphrase when confirming
**4.** There will be a mismatch notification. Click on the Retry.
**5.** Try to enter the correct passphrase again

**Expected result:**
Upon clicking Retry, the whole process of entering passphrase to create new hidden wallet starts from the start, not just the confirmation step.

**Actual result:**
Retry will only let the user to re-enter the passphrase confirmation, which does not solve issue of user misspelling the first passphrase entry (against which the suite compares the re-entered passphrase).

**Comment by szymonlesisz** [comment]
i guess its only about text/copy

there is a `Try again` button on the bottom of "passphrase confirmation modal" which does exactly what you want (re-discovering all accounts with a new passphrase)

![Screenshot from 2021-08-05 15-10-36](https://user-images.githubusercontent.com/3435913/128355469-716d126d-651c-44a7-b430-08972b65debb.png)

**Comment by wendys-cats** [comment]
@szymonlesisz it is about how Retry (button displayed in Dashboard after passphrase mismatch) works - it does not start the proccess again, but only the confirmation.

**Comment by MiroslavProchazka** [comment]
Resolved by the new Wallet switcher design
