### ISSUE TITLE
Receive address - Requested amount input for QR code

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#4091]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
It would be nice to have the option to generate a QR code with the requested amount, just like with Electrum or any banking app.

**Describe alternatives you've considered**
I don't think there is a workaround for having the amount in the QR code apart from a 3rd party solution... Not sure.

**Additional context**
Electrum 
![image](https://user-images.githubusercontent.com/10185314/127855998-bb870a4b-95ec-4b17-8193-10cf97011a91.png)

**Comment by stepmes** [comment]
Hi, Thanks, this sounds great, I'm adding it to our internal database of feature requests and suggestions.
