### ISSUE TITLE
consolidate animation libraries

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#4095]
so far we have at least:
- react-spring
- framer-motion
- css animations (no library)
- react-awesome-reveal

to save learning API for all of them, potential issues that could came from some and some bytes, would be nice to shorten that list...

**Comment by marekrjpolak** [comment]
By merging #4169, react-awesome-reveal will be eliminated.

**Comment by matejkriz** [comment]
needs decision in team which library to keep react-spring / framer-motion / ?

**Comment by tomasklim** [comment]
Will be solved by #5531
