### ISSUE TITLE
Trade/Exchange - Crypto input text validation

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4096]
**Describe the bug**
Please see video, when you enter text and not value in Exchange fields and you press All or fraction number you will start  `Compare offers` process that will go on forever.

**Steps to reproduce:**
1. Enter `Trade/Exchange tab` enter some text to SendCryptoInput field
2. Press all button
3. Observe

**Info:**
 - Suite version: desktop 21.7.1 (34de15f6b0dcdbf8dc69a34fc65e6abab6a8213d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.4.1 regular

**Screenshots:**

https://youtu.be/oYdFPPyNBc0

![image](https://user-images.githubusercontent.com/31506317/127988665-1c127265-6857-4c79-8ac0-4ff2b4bcc415.png)

[trezor-suite-log-1627979709703.txt](https://github.com/trezor/trezor-suite/files/6922797/trezor-suite-log-1627979709703.txt)

![image](https://user-images.githubusercontent.com/31506317/127986573-7ab4cd93-0cc4-44fb-a337-7d6517ec166b.png)

**Comment by matejkriz** [comment]
related Sentry issue: https://sentry.io/organizations/satoshilabs/issues/2550994235

**Comment by matejkriz** [comment]
I can duplicate it on ETH account, but not on BTC account.

**Comment by matejkriz** [comment]
btw, it's not related to tschuss-next branch, it's in current version too...

**Comment by sorooris** [comment]
QA OK - Tested in https://github.com/trezor/trezor-suite/pull/4140#issuecomment-899514209
