### ISSUE TITLE
Unhandled error during model One firmware update

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4101]
**Describe the bug**

Probably related to https://github.com/trezor/trezor-suite/issues/3718
I was able to reproduce it in web and app version. 
You can reboot to bootloder mode or you can just reconnect your device with button pressed.
When you abort installation via device button you will see `Error: Cannot read property 'code' of null`

**Steps to reproduce:*
1. Proceed firmware update steps
2. Press `Abort` via device button when asked to install firmware
3. Observe error in Suite

**Info:**
 - Suite version: desktop 21.8.0 (e9976a3052507d8b888370ceb11eaa61bae5d775)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model 1 1.10.2 regular

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/128035563-59adc24b-45cb-4592-8004-3e565c4939fd.png)

[trezor-suite-log-1628001472054.txt](https://github.com/trezor/trezor-suite/files/6924941/trezor-suite-log-1628001472054.txt)

**Comment by marekrjpolak** [comment]
I've just reproduced it in current web Suite (21.7.1) so it's even older bug.

**Comment by bosomt** [comment]
I was not able to reproduce it with 2.4.1 or 1.9.4 firmware in Suite 21.8.1, looks like issue with firmware 1.10.x
