### ISSUE TITLE
Multiplication of Standard wallets via retry button in Passphrase mismatch modal.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4108]
**Describe the bug**
You can multiple Standard wallets via retry button in Passphrase mismatch modal.
Please see video, probably reproducible only when Standard wallet is remembered. 

**Steps to reproduce:**
1. Load Standard wallet and remember it
2. Use add hidden wallet dialogue and create passphrase mismatch
3. Press try again after passphrase mismatch dialogue and enter empty passphrase
4. go to wallet/device selector and observe

**Info:**
 - Suite version: desktop 21.8.1 (8dfc3fbf9faa870f6c7e6017a63ffeb311cf5b16)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular

**Screenshots:**

<img width="726" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/128329531-c9ded8a8-eabf-47d4-96d7-fc0dc56fc13b.png">

https://www.youtube.com/watch?v=7FWDZEvsPN8

[trezor-suite-log-1628156222082.txt](https://github.com/trezor/trezor-suite/files/6937603/trezor-suite-log-1628156222082.txt)

**Comment by szymonlesisz** [comment]
should be fixed here: https://suite.corp.sldev.cz/suite-web/fix/4108/web/

**Comment by bosomt** [comment]
EDIT: 
**QA OK**

**Info:**
 - url https://suite.corp.sldev.cz/suite-web/fix/4108/web/settings/debug
 - Suite version: web 21.9.0 (06f935ee65436ab33fa7d21790a807cf717b31fe)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 Bitcoin only

**Comment by bosomt** [comment]
tested multiple times and i was not able to reproduce issue, moving to approved

**Info:**
 - Suite version: desktop 21.9.0 (fc8a7ee0dc3487bc96f3b45cac07b26c2474b5b9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular
