### ISSUE TITLE
ReconnectDevicePrompt__Overlay on top of the firmware update modal obstructs the close button

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#4111]
The ReconnectDevicePrompt__Overlay on top of the firmware update modal obstructs the close button while it's still possible to exit via pressing the Esc key - user should be able to exit the update flow any time, compared to Onboarding.

![image](https://user-images.githubusercontent.com/10185314/128341918-ef1c7d00-aae0-4ef8-b579-5ab1a6eac8b5.png)

Suite: web 21.8.1 8dfc3fbf
Browser: Chromium 92.0.4515.107
OS: NixOS 21.05
Device: model One 1.10.1

_Originally posted by @sorooris in https://github.com/trezor/trezor-suite/issues/3718#issuecomment-893390160_

**Comment by hynek-jina** [comment]
@STew790 Is this still valid? thx

**Comment by STew790** [comment]
**QA NOK**

Unfortunately, this is still valid.

**Info:**
 - Suite version: web 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1440x900
 - Device: model 1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA NOK**

part of dialogue is still missing `X Abort` button

**QA OK**
<img width="554" alt="Screenshot 2022-09-16 at 9 28 46" src="https://user-images.githubusercontent.com/31506317/190585768-54889112-5a04-400e-88d5-c30a20501e08.png">

**QA NOK**
<img width="543" alt="Screenshot 2022-09-16 at 9 28 22" src="https://user-images.githubusercontent.com/31506317/190585797-fc691221-a8af-4e90-aee1-4c981cb8a529.png">


**Info:**
 - Suite version: web 22.10.0 (7d65c11feb97927eea4d206dd7a1b1a47c9de794)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
 - OS: MacIntel
 - Screen: 1848x1155
 - Device: model 1 1.11.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA OK**

Reboot to bootloader cancel button is not planed /you can cancel it via device button/
