### ISSUE TITLE
Ability to copy the URL text from the textbox, informing me that the URL is about to be opened in my default browser.

### ISSUE THREAD

**Issue by geebotron** [trezor/trezor-suite#4114]
**Is your feature request related to a problem? Please describe.**
I would like to be able to copy the URL text in the textbox informing me that an external URL is about to be opened in my default browser.
(Linux app image version - when you click to go to the third party website for the details of a trade)

**Describe the solution you'd like**
Make the text in the box copy-able

**Describe alternatives you've considered**
Manually typing the link text - difficult when it contains a long crypto string.

**Additional context**
I would rather choose the browser the link is opened in, and if the Trezor Suite is running in a sandbox e.g. FireJail, external programs cannot be initiated anyhow.

Thanks

**Comment by geebotron** [comment]
Additional clarification:

- When running Trezor Suite in a sandbox like FireJail, spawning of external processes (opening a browser) is not possible.
- If you connect Trezor Suite via Tor - the links for the news items on the main page are .onion links - and would not open in any browser other than the Tor browser. So it would be futile to attempt to open these URLs if the user's default browser was not the Tor browser.
- It would be much better to make the external URLs copy-able - so the user could paste the links into the browser of their choosing.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.

**Comment by VictorieeMan** [comment]
This would also be good for those who don't want to open any Trezor suite URLs in their default web browser. And or send it forward in an email / text app without having to first open it in their web browser.
