### ISSUE TITLE
Request: In Suite DEX Swap

### ISSUE THREAD

**Issue by HeroHann** [trezor/trezor-suite#4118]
**Is your feature request related to a problem? Please describe.**
At the moment a trade / swap is possible in Suite via the integrated exchange, but this is no DEX and not every small Token is supported.

**Describe the solution you'd like**
Please have a look at Metamasks Mainnet Sawp-Feature. It compares rates and swap in such a simple way even my grandma could do it. No „connect Metamask“ to uniswap or check rates at 1inch anymore.
I feel, Trezor Suite should offer a similar feature to easily swap erc-20.

**Describe alternatives you've considered**
Binding the Trezor to Metamask is an extra step that is imo not good for usage and the looks and feel of the hw.

**Additional context**
Furthermore Suite should offer some sort of dapp connectabiliy like walletconnect.
Related: https://github.com/trezor/trezor-suite/issues/3260 (no mobile app needed for walletconnect functinality)

Looking forward to your response or further questions.
Thanks!

**Comment by stepmes** [comment]
Thank you for your suggestion. We're noting it to our list of feature ideas and will consider it when we next work on the trade options within Suite.

**Comment by HeroHann** [comment]
Is there any overview of such „ideas“? Maybe it would be a good idea to make such ideas somehow votable, so that the costumers can steer the dev work. At the moment there is a lot of disappointment in a lot of issues here on github. @stepmes

**Comment by stepmes** [comment]
Thanks for your interest @HeroHann! The voting system you describe is a good idea and we considered it in the past. The main challenge for us is that we receive far more suggestions than our capacities allow us to implement and so we need to prioritize a lot and base our prioritization on multiple different factors to be sure we're building only the most important features and fixing the most important bugs. We need to make sure that our whole user base is represented in the process, not only users who actively report things (even though their feedback is also very much appreciated), and so we also collect inputs proactively using different methods. All this is then analyzed and discussed within the context of our vision and strategy before decisions are made. At this point, we don't have the research processes in the technical form that would allow sharing it publicly, however, to share at least parts of it would definitely be possible and we might consider it in the future. Hope this sheds some light on how we work with the feedback. If you were interested in more details, let me know.
