### ISSUE TITLE
Suite Guide panel is closed with modal when Esc key is pressed

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4122]
**Describe the bug**
Suite Guide is closed with modal window when Esc key is pressed. 
Please see video, when you close any model via Escape key Suite Guide is /probably/ unintentionally closed too.

**Steps to reproduce:**
1. Open Suite Guide
2. Open Any modal that can be closed via Esc key
3. Press Esc key and observe Suite guide panel

**Info:**
 - Suite version: desktop 21.8.1 (e25dcfce1f3b57cbf3d4bf194b3b5d58499abaf5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 Bitcoin only

**Screenshots:**

https://user-images.githubusercontent.com/31506317/128606443-020c234b-ed6c-441e-b396-81bd1e535832.mov

**Comment by jerechinsky** [comment]
Desired behaviour: When a modal is opened above the suite guide, ESC will only close the modal. Anothe ESC press would then close the suite guide. @tomasklim

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.9.0 (da468fee0b2e83475860c6d3cd500b302de6b70e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular

**Comment by STew790** [comment]
**QA OK**

**Info**:
 - Suite version: web 21.9.0 (da468fee0b2e83475860c6d3cd500b302de6b70e)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
 - OS: Win32
 - Screen: 1440x900
 - Device: model T 2.4.1 regular
