### ISSUE TITLE
English copy + spanish sync from crowdin

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#4124]

**Comment by sorooris** [comment]
@alex-jerechinsky hello, what should we test here?

**Comment by jerechinsky** [comment]
@sorooris no need to test anything, thanks!

**Comment by mroz22** [comment]
you can just be using spanish translation when doing regular testing so that you can spot just such cases when there is too long string and it somehow breaks UI. but this is low priority.
