### ISSUE TITLE
Change wording from wallet to Suite in Trezor Bridge Download modal

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4127]
**Describe the bug**

Please change wording from wallet to Suite in Trezor Bridge Download modal.
And if possible change behaviour of button so you won't end up with two tabs of Trezor Suite /old tab with Welcome screen and new one created from Trezor Bridge Download page.

**Steps to reproduce:**
1. Stop or uninstall Trezor Bridge
2. Start web version of suite in Firefox
3. Observe Trezor Bridge Download modal when asked to install Bridge to ma Trezor work in Firefox

**Info:**
 - Suite version: web 21.8.1 (e25dcfce1f3b57cbf3d4bf194b3b5d58499abaf5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 Bitcoin only

**Screenshots:**

<img width="816" alt="Screenshot 2021-08-09 at 12 03 59" src="https://user-images.githubusercontent.com/31506317/128692828-4d661eec-ea56-477b-a130-0d8bd6bd5330.png">

**Comment by sorooris** [comment]
**QA OK**

Copy was improved and is now "New communication tool to facilitate the connection between your Trezor and your internet browser."
![image](https://user-images.githubusercontent.com/10185314/131661091-27538647-8443-4bc4-9604-1b25d75d8f18.png)

Changelog and download button now open in new tabs.

Suite: web 21.9.1 b5a686a
Browser: Firefox 89.0.2, 91.0.2
OS: NixOS 21.05, Win10 PRO 19042.1165

**Comment by sorooris** [comment]
**QA OK**

Copy was improved and is now "Take me back to Suite".

![image](https://user-images.githubusercontent.com/10185314/131662640-c642a035-f546-4ac7-bfd5-545a58c44e51.png)

Changelog and download button now open in new tabs; navigation back and forth from Welcome screen is in one tab.

Suite: web 21.9.1 b5a686a
Browser: Chromium 92.0.4515.107, Chrome 93.0.4577.63
OS: NixOS 21.05, Win10 PRO 19042.1165
