### ISSUE TITLE
Broken model T persistence mode e2e test

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-suite#4128]
**Describe the bug**
- `t2-dry-run-persistence` e2e test is failing both in CI and locally, complaining about "Device detected in incorrect state" or "Recovery seed check failed" (see the link below with screenshots)

**Info:**
- all relevant info is included in discussion in this PR - https://github.com/trezor/trezor-suite/pull/4079

**Comment by tsusanka** [comment]
@trezor/qa could you please try to make a Shamir recovery and replug the device in the middle of it (that means between shares)? We have some bad signals from our e2e tests.

**Comment by sorooris** [comment]
@tsusanka We'll look into it, however, i'd like to know what priority to give the test - Is it related to the current 21.8.1 release?

**Comment by tsusanka** [comment]
Not at all. No priority -> low priority. We can do it via Asana next time to avoid confusion.

**Comment by grdddj** [comment]
I would mention that it is not connected with Shamir, but with classical recovery (however testing Shamir also will do no harm).

Here is the [test scenario ](https://github.com/trezor/trezor-suite/blob/cb513cfe4c817398f53c238badb7550afb67f42c/packages/integration-tests/projects/suite-web/tests/recovery/t2-dry-run-persistence.test.ts)

**Comment by bosomt** [comment]
Do you want us to test it with some branch or we have to use current dev master ?
edit: of course i'm asking about Firmware version and not Suite version :)

**Comment by tsusanka** [comment]
Let's test with latest released FW and latest released Suite.

**Comment by grdddj** [comment]
Seems really that the issue is on the side of `Suite` tests. I will be trying some tips from [this comment](https://github.com/trezor/trezor-suite/pull/4079#issuecomment-895435242)

**Comment by bosomt** [comment]
i was not able to replicate any error

tested 2.4.1 public and current master
tested all seed and shamir seed, tried to disconnect device during seed entry and between shares.
@grdddj Please keep us updated about your findings, we can proceed with more tests on our side if needed.

**Info:**
 - Suite version: desktop 21.8.1 (e25dcfce1f3b57cbf3d4bf194b3b5d58499abaf5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular

**Comment by grdddj** [comment]
Is it possible that it will be behaving differently based on a browser (Firefox vs Chrome), maybe because of Chrome's webUSB?

Below are the screenshots from the same context in the test, first for Firefox and second for Chrome. Also, in the Firefox case, after manually clicking `Use Trezor here`, the test finished fine. In Chrome's case, clicking `Find Trezor` did not help (showed a troubleshooting guide)

EDIT: this scenario is not connected with stopping and again starting emulator (it works fine previously in the test case), it is testing the restart of the bridge:
```js
cy.wait(501);
cy.reload();
cy.wait(2000);
cy.task('stopBridge')
cy.wait(2000);
cy.task('startBridge');
cy.wait(2000);
```

Firefox:
![image](https://user-images.githubusercontent.com/42543243/128847053-cc77ba62-57f8-49e6-a3ba-34316fc04bd9.png)

Chrome:
![image](https://user-images.githubusercontent.com/42543243/128847000-9f0fb27b-1140-4fba-a36f-e828d51cd4c1.png)

**Comment by tsusanka** [comment]
@bosomt please retest with web version on both Chrome and Firefox. And if it'll work for @bosomt I would simply remove the e2e test altogether..

**Comment by bosomt** [comment]
Maybe it's really related to Chrome. But maybe it's different error ;)
This is what i see when i try to acquire Trezor model T that it's already in recovery mode.

**How to replicate** 

1) Chrome webusb start recovery
2) Close Suite window and THEN try to cancel recovery via x button on device
3) Device will 'soft' freeze
4) Reopen Chrome/Suite and try to acquire device
 

<img width="740" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/129151517-151c6e49-ec92-4d75-9f2e-f44a415fd75f.png">


https://user-images.githubusercontent.com/31506317/129152023-2a1f2151-75ab-43d5-b282-1fe61cc8a58c.mov



**Info:**
 - Suite version: web 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular
 - webUSB, no Bridge present

**Comment by tsusanka** [comment]
Thanks. @bosomt could you please open a new issue for this? It is quite edge-casy, I do not think we need to fix it now, but it should be tracked.

And @grdddj I suggest to remove the persistence test from the e2e test suite for now and close this issue. The main goal of your #4079 is to stabilize the tests..

**Comment by grdddj** [comment]
As per comment above, the problematic test was disallowed/skipped in https://github.com/trezor/trezor-suite/pull/4079. Closing the issue.

Thank you guys for help :)
