### ISSUE TITLE
Intermediary firmware installation loop

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#4129]
**Describe the bug**

When I tested firmware update from firmware older than 1.6.3 with an already initiated device, again, I got into a loop of reinstalling intermediary firmware 1.10.0 and firmware 1.10.2 is never installed (just to correct the comment from @bosomt).

**Info:**
 - Suite Version: 21.8.1 web, commit e25dcfc
 - Browser: Chromium , version91.0.4472.114
 - OS: NixOS
 - Firmware Version: 1.6.0  -> 1.10.2

**Steps to reproduce:**
1. Connect a device with older firmware than 1.6.3 with Suite
2. You will be prompted to install new firmware.
3. Proceed with the installation.
4. After confirming "Install new firmware" prompt on your device, you will be stuck in a loop and Suite will always reinstall only the intermediary firmware 1.10.0

**Expected result:**
Suite will install intermediary firmware silently and after that the newest firmware available will be installed.

**Actual result:**
Suite only installs intermediary firmware and the device gets stuck in a loop of only reinstalling the intermediary firmware.

**Screenshots:**
insert here

**Note(s):**
 firmware is installed, and 1.10.1 fw is installed too but suite installs it over and over again with this dialogue till device glitched and crashed and I ended up with device with bootloader 1.10.0 and no seed or firmware. Attached video of that loop + log from suite.

https://youtu.be/044_JQynLK4
[trezor-suite-log-1624345728858.txt](https://github.com/trezor/trezor-suite/files/6692021/trezor-suite-log-1624345728858.txt)

![image](https://user-images.githubusercontent.com/31506317/122880287-23f8bd80-d33a-11eb-833c-0912c8d527db.png)

```
**Info:**
 - Suite version: desktop 21.6.2 (1ff4cbc91f640b645aa72c59047ffeff01819b1b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
```

_Originally posted by @bosomt in https://github.com/trezor/trezor-suite/issues/3911#issuecomment-865665663_

**Comment by szymonlesisz** [comment]
closing via #4164

**Comment by STew790** [comment]
**QA OK**

I updated from FW 1.5.2 to 1.10.2 without any problem.

**Info**

- Suite version: desktop 21.9.0 (0042e719d7d9fa2dff2ed743b0866e64f4ae0216)
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
- OS: Win32 
- Screen: 1366x768
- Device: model 1 1.10.2 regular
