### ISSUE TITLE
Improve Disconnected status icon "aura" colours

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#4137]
**Is your feature request related to a problem? Please describe.**
Due to an error at exporting designs, the aura colours were never properly specified.
As a result of that, this is how they look like now:
![image](https://user-images.githubusercontent.com/88533514/129034760-ba196af4-090b-4f92-acf0-6f691f2e31e8.png)
![image](https://user-images.githubusercontent.com/88533514/129034774-3f309bf6-114e-47ba-a87a-44d6237f2ab1.png)

**Describe the solution you'd like**
Please change the aura colours to the following ones:
Type/Light Red
background: #FEF3F3;
Type/DM/Light Red
background: #312828;

**Describe alternatives you've considered**
N/A just design thing

**Additional context**
This was the faulty design export (so thanks for the implementation better than that, but we might to give it the final shape now):
![image](https://user-images.githubusercontent.com/88533514/129034973-01ed715f-4752-4ef7-89ad-3d057cf19396.png)
![image](https://user-images.githubusercontent.com/88533514/129034989-6e7d148e-7275-45e4-86b0-8a868865c3b2.png)
![image](https://user-images.githubusercontent.com/88533514/129035020-e16917b3-f1c2-48c1-a9e8-4d43b240e863.png)

**Comment by github-afsaneh** [comment]
#2838 #4053 #2575 #3906

**Comment by bosomt** [comment]
edit: ` ci/gitlab/gitlab.com Pipeline failed on GitLab ` again 

I'm not sure
it looks like this in current dev master.

<img width="52" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/130332748-209311c4-b73d-47d1-ab8a-404d2795848e.png">

<img width="47" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/130332782-ee13fc0b-e94b-4ab9-9517-8f900c74075f.png">


**Info:**
 - Suite version: web 21.9.0 (dd23ecc920f7bf6fab3e63e7e30bdced32989cdd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.3.4 regular

**Comment by STew790** [comment]
I am actually also not sure if this is right or not, but here's what I see:

![image](https://user-images.githubusercontent.com/48477147/130463480-1410215e-4acf-43ed-90d2-f53fe2aaaf76.png)
![image](https://user-images.githubusercontent.com/48477147/130463499-90109423-7a0c-4a03-8e9b-61bf74236679.png)
![image](https://user-images.githubusercontent.com/48477147/130463508-323c69a9-bed9-4f51-a98b-77a4ee58871b.png)
![image](https://user-images.githubusercontent.com/48477147/130463524-793e31a1-dfd7-4005-ab9a-4f7a0464023e.png)


**Info**:
 - Suite version: desktop 21.9.0 (6e3744986e5003e680d73c0a44f94c018d259e7f)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.1 regular

**Comment by tomasklim** [comment]
> I am actually also not sure if this is right or not, but here's what I see:
> 
> ![image](https://user-images.githubusercontent.com/48477147/130463480-1410215e-4acf-43ed-90d2-f53fe2aaaf76.png)
> ![image](https://user-images.githubusercontent.com/48477147/130463499-90109423-7a0c-4a03-8e9b-61bf74236679.png)
> ![image](https://user-images.githubusercontent.com/48477147/130463508-323c69a9-bed9-4f51-a98b-77a4ee58871b.png)
> ![image](https://user-images.githubusercontent.com/48477147/130463524-793e31a1-dfd7-4005-ab9a-4f7a0464023e.png)
> 

I confirm that the colors are correct
