### ISSUE TITLE
Error when trying to acquire Trezor soft frozen in recovery mode

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4139]
**Describe the bug**

This is what i see when i try to acquire Trezor model T that it's already in recovery mode.
AFAIK only way to solve it is to reconnect device or 'defreeze' is by  acquiring device via different wallet.

**How to replicate** 

1) Chrome webusb start recovery
2) Close Suite window and THEN try to cancel recovery via x button on device
3) Device will 'soft' freeze
4) Reopen Chrome/Suite and try to acquire device
 
**Screenshots:**

<img width="740" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/129151517-151c6e49-ec92-4d75-9f2e-f44a415fd75f.png">

https://user-images.githubusercontent.com/31506317/129152023-2a1f2151-75ab-43d5-b282-1fe61cc8a58c.mov

**Info:**
 - Suite version: web 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular
 - webUSB, no Bridge present

_Originally posted by @bosomt in https://github.com/trezor/trezor-suite/issues/4128#issuecomment-897398627_

**Comment by tsusanka** [comment]
Let's retest on 21.10.1.

**Comment by STew790** [comment]
**QA NOK**
Issue still present. After you select on your device, how many recovery seed words you want to enter, you close the Suite and press "X" on the device an it will freeze. Although, the difference now is that the device will unfreeze if you go to Suite page again but the problem now is that if you want to acquire it, the Suite won't load and it will stay in the phase as shown in the screenshot and I had to refresh the page.

**Info:**
 - Suite version: web 21.10.1 (aa3adfa347d0416f970a7fae720d3350f29f8916)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.2 regular

![image](https://user-images.githubusercontent.com/48477147/136964488-1f62c5d4-5b14-4c65-9b11-ef31d863debb.png)

**Comment by jerechinsky** [comment]
@STew790 will try to replicate.

**Comment by STew790** [comment]
I wasn't able to replicate this on 3 different Windows 10 machines. Closing.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.12.0 (f4f9dcf4e2fccf6cf6f1f9d823333c03d81e1eb1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular
