### ISSUE TITLE
Onboarding - failed backup flow improvement

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#4150]
**Describe the bug**
Current failed backup flow instructs the user to navigate to settings where the default  Application subtab is displayed, user has to navigate to the correct Device subtab and scroll all the way down to the unfortunately-named Danger area, where the Wipe memory button is situated. After that checkboxes with information regarding data associated with the pre-existing accounts and funds are displayed which could be seen in the context of a backup failed flow from Onboarding redundant. 

It would be much easier for the user to allow them to wipe device right away in the onboarding and then re-initiate onboarding flow.

**Info:**
 - Suite Version: any (tested 21.8.1 bde9e100)
 - Browser: any (tested Chromium 92.0.4515.107)
 - OS: any (tested NixOS 21.05)
 - Bridge: any (tested 2.0.31 rev unknown)
 - Firmware Version: any (tested 2.4.1)

**Steps to reproduce:**
1. Initiate Onboarding and select the Create new wallet flow,
2. Navigate to the backup step, Begin backup and confirm on device,
3. Disconnect device during backup.

**Expected result:**
Shorter flow to wipe device; Wipe memory button on the backup screen, or redirect straight to the Settings -> Device subtab and focus on the Danger area section, where the Wipe memory button is.

**Actual result:**
Go to settings button is displayed on the backup failed screen, the steps required to wipe device are following:
1. Select the Go to settings button,
2. Select the Device subtab,
3. Scroll down to the Danger area section,
4. Select the Wipe memory button,
5. Confirm checkboxes and confirm on screen,
6. Confirm wipe on device.

**Screenshots:**
Proposed solution:
![image](https://user-images.githubusercontent.com/10185314/129567088-7f4ec015-4171-411a-913a-71f5f1ff76f4.png)

Actual:

Onboarding screen after reconnecting device in an interrupted backup:
![image](https://user-images.githubusercontent.com/10185314/129565574-b14b9719-13d8-4a8f-8c37-6397a9ae9e28.png)

Application settings displayed after selecting the Go to settings button:
![image](https://user-images.githubusercontent.com/10185314/129565601-603ff56f-a0b8-4a02-9d28-b325d06af13d.png)

Selecting the Continue button from the red banner at the top of the screen redirects to the top of the Device subtab, without focus on the Wipe memory button which is at the bottom of the screen, in the "Danger area" section:
![image](https://user-images.githubusercontent.com/10185314/129566238-95c4f302-e017-4899-a415-8ea1fa0a24c1.png)
![image](https://user-images.githubusercontent.com/10185314/129566547-b6ebc8d4-63de-4aa5-8360-e2ca4adf1b78.png)

Checkboxes with information about deleting data on device and funds, probably redundant for a failed backup state
![image](https://user-images.githubusercontent.com/10185314/129566679-00780d59-f295-4375-b65f-bc2370dc9759.png)

**Note(s):**
Incomplete onboarding info by Maros available [here](https://github.com/trezor/trezor-suite/blob/develop/docs/misc/onboarding/onboarding.md#firmware).
Failed backup flow from within Suite should be considered as well since there is a similar long flow.
![image](https://user-images.githubusercontent.com/10185314/129568948-ee8b750b-235f-48c7-b66c-12c20085c7ee.png)

**Comment by sorooris** [comment]
Also important note:
User is allowed to navigate from the Settings screen to Dashboard and Accounts screens and can further generate receive addresses with a failed backup, which would in case of receiving funds and losing the device used afterwards result in coin loss.

It should be differentiated between the _needs backup_ and the _backup failed_ states of the device in Suite; however _needs backup_ can down the line result in a _backup failed_ state in which user should be allowed to send funds to any address - not sure about generating new receiving addresses though.

**Comment by bosomt** [comment]
related issue

**Comment by bosomt** [comment]
related issue 

Backup failed in the new onboarding [bug or feature?]
https://github.com/trezor/trezor-suite/issues/3864

**Comment by tomasklim** [comment]
There is anchor link to the specific button now
