### ISSUE TITLE
Suite desktop download - improve copy of dwnld options

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#4158]
**Is your feature request related to a problem? Please describe.**
We have redundant text in Suite desktop download options. Cognitive load is a bit higher without any proper reason.

**Describe the solution you'd like**
Please get rid of "for " in each option:

![](https://user-images.githubusercontent.com/1835345/129559063-5f92a84e-32d2-47c9-8e3a-6e2015e7ab9f.png)

**Describe alternatives you've considered**
We could keep it as it is, but reading it is slower and less natural than perceiving options as simple visual elements (you don't have to really read macOS, you just know it visually)

**Additional context**
We have touched similar topic in #4149 (screenshot above is from version before 4149 has been handled)

**Comment by Hermez-cz** [comment]
<img width="444" alt="image" src="https://user-images.githubusercontent.com/88533514/129736476-a217b228-f042-49ce-9d26-566417769778.png">

just for the record - align simply as is

**Comment by STew790** [comment]
**QA OK**

It looks like this:
![image](https://user-images.githubusercontent.com/48477147/131518875-8fb3178a-8f9c-4c7e-bae8-fc9ebe6a79f4.png)

**Info**:
 - Suite version: web 21.9.0 (1f5e833a2d214388d3b0c760aa5287e5c83dbd87)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
