### ISSUE TITLE
Sign transaction error : Not an original output

### ISSUE THREAD

**Issue by username1618** [trezor/trezor-suite#4159]
I can't bump fee. When i try to do it i reciev "Sign transaction error: Not an original output". 
 Trezor One.   Suite version: 21.8.1.  Windows 10.

**Comment by bosomt** [comment]
@username1618 can you please give us more information if possible  so we can check your issue ?

- firmware version of your device
- coin that you are trying to bump /eth,btc,../ ?

**Comment by bosomt** [comment]
**QA OK**

I was able to bump multiple TXs with BTC and ETC coins
@username1618 closing this issue, 
it was possible that you were trying to bump transaction with unconfirmed inputs or transaction that was already included in blockchain 


**Info:**
 - Suite version: desktop 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular
