### ISSUE TITLE
Details about firmware update should lead to blog post if present

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4161]
In the new onboarding we have `View all` which leads to [this wiki page](https://wiki.trezor.io/Firmware_changelog).

![image](https://user-images.githubusercontent.com/1835345/129861797-b0a7aa82-9a72-4d46-9546-94430ca1a6b6.png)

I see two issues:
1) It seems some padding is missing between the button and the title or the button should be on a different place altogether.
2) We should link to a blog post if present (`notes` in releases.json) and if it is not then to changelog (`https://github.com/trezor/trezor-firmware/blob/master/core/CHANGELOG.md`).

**Info:**
 - Suite version: web 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.2 regular

**Comment by wendys-cats** [comment]
**QA OK - will close once merged into develop**

tested update to 2.1.1 (no blog post), 2.4.2 (blog post present), 1.10.3 (blog post present)

**OS:** Windows 10
**Device:** TT (update from 2.0.5 and 2.3.6) and T1 (update form 1.10.1)
**Suite:** WEB 21.10.0 694100cd86a6e3a7f5863c45b43ff4995ba16578 branch fix/4161

**Comment by matejkriz** [comment]
> @matejzak said:
design needed : Ideally we would have 2 buttons there — (1) give me more details (link to blogpost as Susi suggests) and (2) show all changes throughout the history of the FW universe (link to all changelogs on wiki) :slightly_smiling_face:

see conversation: https://satoshilabs.slack.com/archives/C01SXSHGK44/p1630653496010000

**Comment by tsusanka** [comment]
We are happy with this for now like this :).

**Comment by bosomt** [comment]
**QA OK**

<img width="1139" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/141974629-eaa58429-1479-4aa7-a695-05f9c3429f0a.png">

**Info:**
 - Suite version: web 21.12.0 (0ebc97c99e03ed4d2f9a98ab272875430674d3ec)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular
