### ISSUE TITLE
 Inaccurate Ethereum Account Overview value compared to real status

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4167]
**Describe the bug**
Inaccurate Ethereum Account Overview value compared to real status.
Please see screenshots or import account with address 0x73d0385F4d8E00C5e6504C6030F47BF6212736A8
It's first Standard account of all seed. 
According to account Overview it has -0.2315xxx ETH value

**Steps to reproduce:**
1. Connect device with all seed and select Standard wallet
2. Select first Account
3. Compare real 0 value and negative value and graph in Account overview

**Info:**
 - Suite version: web 21.9.0 (dd23ecc920f7bf6fab3e63e7e30bdced32989cdd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular

**Screenshots:**

<img width="786" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/130352666-e7ab881c-2945-4e8c-a580-be2826e339f5.png">

**Comment by bosomt** [comment]
i just found one more account on our testing passphrase

<img width="814" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/133964794-26aee3b4-281e-4507-a568-faaabfc90b07.png">

0x68A896f9969c52DDb3f05E543D16AEe21893e16a

**Info:**
 - Suite version: desktop 21.10.0 (0244ceff3e6200b020c02586729aa4586067289c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.0 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by bosomt** [comment]
**QA NOK**

issue is still present

<img width="800" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/140473384-885045b0-10e6-4a15-9bd4-be0cec0c3ade.png">

<img width="810" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/140473427-6cff1f74-e5c0-4901-93d9-6f0c1b776c15.png">

**Info:**
 - Suite version: desktop 21.11.0 (4a56ae794159091a4f2c4de847d237a47657dc1c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.11.0 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Comment by tomasklim** [comment]
The problem is caused by `Ethereum internal transactions`, which are not yet supported by Blockbook #3658. 

The transaction which is causing problems on all seed is this one https://eth1.trezor.io/tx/0x9dc9b9c884aad768328f28e8194f1f86121f6c2a1742fa817c33bcc2f3b7aa3c
https://etherscan.io/tx/0x9dc9b9c884aad768328f28e8194f1f86121f6c2a1742fa817c33bcc2f3b7aa3c
