### ISSUE TITLE
Install custom firmware - mislabeled redirect to trezor.io

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4168]
**Describe the bug**
See screenshot. Suite says: `Download on Trezor.io`
But link goes to `https://github.com/trezor/webwallet-data/tree/master/firmware`
Maybe we can consider to change it to `Download on github.com` or `Download on github.com/Trezor`

**Steps to reproduce:**
1. Visit Settings/Device/DANGER AREA in suite and click on `Install custom firmware`
2. Open `Download on Trezor.io` link
3. Observe real url that was opened 

**Info:**
 - Suite version: desktop 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular

**Screenshots:**

![obrazek](https://user-images.githubusercontent.com/31506317/130421648-b8ec7e98-b7d5-4000-83a1-bc727d7bc6b2.png)

**Comment by jerechinsky** [comment]
I can change it via copy. What do you think? @Hermez-cz @matejzak

**Comment by jerechinsky** [comment]
I will leave it in the product column for now. I'm capable of fixing it myself but I need confirmation since changing it to `Download on github.com` could confuse some people who don't know what github is or something... 
Please suggest what to do.

**Comment by Hermez-cz** [comment]
Hi @alex-jerechinsky thanks for your suggestion. I agree, that a change to correct copy will help.
My guess would be, that there won't be many users trying to `Install custom firmware` while not knowing what GitHub is. Furthermore, the link will really lead them to GitHub anyways, so they will have to learn what GitHub is to some extent. Mentioning GitHub openly will also help users that don't understand what it is and/or whether they trust it or not decide if they want to click such link.
Would like to have approval from @matejzak , but I'd go with Download on github.com as suggested by @bosomt

**Comment by glacierbits** [comment]
Agreed! Thanks bois.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.12.0 (f4f9dcf4e2fccf6cf6f1f9d823333c03d81e1eb1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
