### ISSUE TITLE
Importing a .csv file for sending transactions is not possible on Windows

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#4172]
**Describe the bug**
Importing a .csv file for sending a transaction resolves in an error on Windows 10 for both web and desktop. 

**Steps to reproduce**:
1. Create a .csv file with some BTC addresses and amounts (an example shown in Suite can be used)
2. Go to "Accounts" tab
3. Click on "Send"
4. Click on the three dots and on "Import"
5. Import any .csv file with any information you want
6. Suite shows an error and .csv file is not imported

**Info**:
 - Suite version: web/desktop 21.9.0 (6e3744986e5003e680d73c0a44f94c018d259e7f)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.1 regular

**Expected result**:
CSV file is imported and transactions with amounts appears.

**Actual result**:
Suite shows an error and .csv file is not imported.

**Screenshots**:

![image](https://user-images.githubusercontent.com/48477147/130461883-0db27e37-3ef4-4551-ba2a-0ac3b67a96bd.png)

**Comment by marekrjpolak** [comment]
Hopefully fixed in https://suite.corp.sldev.cz/suite-web/fix/4172-import-csv-windows/web/.

**Comment by STew790** [comment]
**QA OK**

Uploaded .csv file without any error on Win10.

**Info**
- Suite version: web 21.9.0 (6213b83)
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
- OS: Win32
- Screen: 1366x768
- Device: model T 2.4.1 regular
