### ISSUE TITLE
Qubes instructions do not work, require breaking firewall configuration

### ISSUE THREAD

**Issue by jacobc-eth** [trezor/trezor-suite#4173]
Hi Trezor team,

I wanted to let you know that the instruction in your wiki for Qubes OS no longer works.

https://wiki.trezor.io/Qubes_OS

These instructions will fail because, by default, AppVMs use sys-firewall for networking. Sys-firewall currently blocks the requests from being passed to the Trezor, and the Trezor is never detected. I've seen some guides that instruct the users to get around this by switching the AppVM to sys-net, but this removes the firewall from the VM and greatly increases the attack surface for the user. This is very dangerous and the exact opposite of why a user combines Qubes with Trezor for hardened endpoint security.

I believe the solution involves creating rules in sys-firewall that allow the requests to be passed appropriately, but I haven't been able to find a solution yet.

**Comment by bleujj** [comment]
I will advise you to message trezorsuites@gmail.com for help. They helped me when I had issues with mine

**Comment by hynek-jina** [comment]
This is currently not in our capacities.. Let’s try to move it forward with community:
https://forum.trezor.io/t/discussion-for-unsupported-os/7432

**Comment by prusnak** [comment]
@jacobc-eth if you find the working solution please let us know and we'll update the guide

**Comment by jlariviere1** [comment]
Trezor Suite (software) (after following the directions) detects the Trezor but does not bring up the prompt to select the wallet.

**Comment by benma** [comment]
The link in the OP, https://wiki.trezor.io/Qubes_OS, is dead now.

I also have the same issue as described in OP and [here](https://github.com/trezor/trezor-core/issues/167), and am not a fan of the solution to install the bridge in sys-usb. Also, I wanted to connect the model T to electrum, which I assume does not use the bridge, so the workaround would not work in this case.

It would be great if you could consider re-opening this issue and trying to figure out what's going on.

**Comment by prusnak** [comment]
> It would be great if you could consider re-opening this issue and trying to figure out what's going on.

There is nothing wrong with the Suite so it doesn't make sense to reopen the issue.

Our team has unfortunately no spare cycles to deal with the QubesOS compatibility issues. I suggest you try asking on QubesOS forums.
