### ISSUE TITLE
Numpad entry is ambigous

### ISSUE THREAD

**Issue by Giszmo** [trezor/trezor-suite#4174]
**Describe the bug**
When first confronted with a 2x3 grid, the user doesn't know which buttons to click on the 3x3 numpad

**Steps to reproduce:**
1. restore wallet on Trezor One, using the advanced method
2. use the (3x3) numpad instead of the mouse for quicker input
3. write until you get less than 7 options for the current word

**Expected result:**
The Trezor Suite shows a 3x3 square with missing center column to make clear that the user is supposed to use 1, 4, 7, 3, 6, 9, with 2, 5 and 8 being inactive.

**Actual result:**
The Trezor Suite shows a 2x3 square to click on but gives no hint on what to use on the 3x3 numpad

**Note(s):**
As this issue only occurs when concluding a word and it's not clear that the backspace button also lets you correct your last word, this can induce some anxiety in an anyways stressful situation.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
