### ISSUE TITLE
Warn user about caps lock enabled when entering passphrase

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4177]
**Is your feature request related to a problem? Please describe.**

I think that it's common/best practise to warn user about caps lock enabled when entering password.
Maybe we can consider to add this warning when you enter passphrase in Suite ?

**Screenshots:**

![obrazek](https://user-images.githubusercontent.com/31506317/130609949-a37f95a8-4a47-404c-8d4f-eb1e83256188.png)

**Comment by stepmes** [comment]
Thanks, I'm noting it down to the list of feature requests/suggestions!
