### ISSUE TITLE
udev autoinstall - better copy for cancellation toast notification

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#4183]
**Describe the bug**
An unclear error message in the toast notification is displayed after cancelling automatic udev rules installation.

**Info:**
 - Remembered Wallet: any
 - Suite Version: app 21.9.0 a7fc3731db3e9f58e066a5af970832519b6699f4
 - OS: Linux Mint 19.3 Cinnamon
 - Bridge: any
 - Firmware Version: any

**Steps to reproduce:**
Precondition: udev rules not installed on the machine
1. Launch Suite on Linux,
2. Connect device,
3. Cancel automatic installation of udev rules.

**Expected result:**
A more user-friendly error message is displayed.

**Actual result:**
_Error: pkexec exit with code 126_ is displayed in the toast notification.

**Screenshots:**
![udev autoinstall error message toast notification](https://user-images.githubusercontent.com/10185314/130975131-60dbbd4e-c875-4123-bb2d-0ccb5b03e3a2.png)

**Comment by szymonlesisz** [comment]
i guess we can "translate" known exit codes, like 126, but imho i think this format is quite helpful for debugging and i would leave it as is.

**Comment by prusnak** [comment]
From the documentation: https://www.freedesktop.org/software/polkit/docs/latest/pkexec.1.html#pkexec-return-value

> Upon successful completion, the return value is the return value of PROGRAM. If the calling process is not authorized or an authorization could not be obtained through authentication or an error occured, pkexec exits with a return value of 127. If the authorization could not be obtained because the user dismissed the authentication dialog, pkexec exits with a return value of 126.


I think it would be really nice touch to show a different text for 126 - I sent a PR in https://github.com/trezor/trezor-suite/pull/4190
