### ISSUE TITLE
XRP explorer opens up as wss address

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#4185]
**Describe the bug**
Opening XRP transaction details in XRP explorer in Suite opens up wss://s1.ripple.com/tx/ rather than in https://xrpscan.com/.

**Steps to reproduce:**
1. Open Trezor Suite
2. Go to your XRP account
3. Open transaction details
4. Open transaction details in XRP explorer

**Info:**
 - Suite version: web 21.9.0 (3307bcb0915ffb05b0d40b960e5d4fa7b2516e86)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.2 regular

**Expected result:**
Open standard XRP explorer and show the transaction

**Actual result:**
Suite opens XRP transaction via wss://s1.ripple.com/tx/

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/130977758-cc4e0b98-97fe-4355-b819-6a754ffd1d99.png)

**Comment by dimasivan** [comment]
Probably because of #4105 I can take a look
