### ISSUE TITLE
Data Analytics

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#4189]
After consultation with @tomasklim, we want some changes in suite logs:

- [ ] rename event `wallet/created` to something more intuitive, e.g. `select-wallet-type`, and `add-wallet` from modal switch-device rename to `add-hidden-wallet`
- [ ] delete event `desktop-init`: event has no added value, its only unique atributte `DesktopOsVersion` is not used anywhere.

**Comment by tomasklim** [comment]
Renamed:
`wallet/created` => `select-wallet-type`

Deleted:
`desktop-init`

Added:
`switch-device/add-hidden-wallet`

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.10.1 (30698b091e0eff94a2adddf92b15998092d7a3c9)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728

log:

```
DEBUG(csp): Header applied to https://data.trezor.io/suite/log/desktop/stable.log?c_v=1.13&c_type=select-wallet-type&c_commit=30698b091e0eff94a2adddf92b15998092d7a3c9&

DEBUG(csp): Header applied to https://data.trezor.io/suite/log/desktop/stable.log?c_v=1.13&c_type=switch-device%2Fadd-hidden-wallet&c_commit=30698b091e0eff94a2adddf92b15998092d7a3c9```
