### ISSUE TITLE
Write more test for actions

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#419]

**Comment by mroz22** [comment]
what is criteria for this task? :] lets do 100% coverage for all actions? :] this is uncleary to me at which moment this issue should be considered done

this is current situation: (note some tests are in PRs)
![image](https://user-images.githubusercontent.com/30367552/63802013-f2fffb00-c911-11e9-9dd4-f78ffb214074.png)

**Comment by ZdenekSL** [comment]
I think 100% coverage is good enough :)
