### ISSUE TITLE
permission to save labels on google drive at every Suite launch

### ISSUE THREAD

**Issue by LukAss741** [trezor/trezor-suite#4193]
Rencetly a save labels message box started appearing after every launch of Suite.
I must click google drive then browser window opens where I chose an account then give permission to Suite to access my google drive and then close the browser window. See attached screenshot.
This is an annoying process to go through after every launch. Can you improve it so that I don't have to do all this work?
![1](https://user-images.githubusercontent.com/8490744/131153994-048429f2-d9d8-4552-b79d-123bab8f58d8.png)
![2](https://user-images.githubusercontent.com/8490744/131153993-da4fbab5-568c-4b66-9314-cd74a407e178.png)
![3](https://user-images.githubusercontent.com/8490744/131153991-7b46d2d0-29cb-4e16-b8e8-63b467785664.png)
![4](https://user-images.githubusercontent.com/8490744/131153986-28356c90-eb9e-4afc-a04c-b034195a92e8.png)

**Comment by bosomt** [comment]
I was not able to reproduce issue, and I never experienced this kind of behaviour.


**Info:**
 - Suite version: desktop 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular

**Comment by ztmr** [comment]
I had this in the past, but not regularly. Now it is getting worse: clicking the GDrive button starts the spinner wheel which will never finish. Upgrading from 21.7.1 to 21.8.1 did not help. Nothing relevant is printed to the stdout/stderr, not sure how to debug this. Is there any way to activate Electron DevTools? Web wallet does not have this issue. Is this related or worth a new ticket?

**Comment by bosomt** [comment]
@LukAss741 can you please confirm that behaviour changed with latest versions of Suite ?
So far we were not able to reproduce issue during our release testing cycle.

**Comment by LukAss741** [comment]
I confirm. After update to the latest version I diddn't have to go through the process of giving access to google drive as before. It loaded labels straight away.
Thank you.

**Comment by LukAss741** [comment]
Since about a month ago it started requiring permissions to access my google drive after every launch again.

Is there any way I can transfer my labels from google drive to local disk?
