### ISSUE TITLE
Can't get into Suite when connecting T1 with PIN enabled

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#4194]
**Describe the bug**
Connecting  Trezor One with PIN enabled results in an error in Suite which won't let me into the Suite.

**Info:**
- Suite version: desktop 21.9.0 (9eeb277b0c316344148ece9bc5f552d16ed600d8)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model 1 1.10.3 (9276b170)

**Steps to reproduce:**
1. Start Suite
2. Connect your Trezor One with PIN enabled
3. Suite will show an error as shown on the screenshot (log included as well)

**Expected result:**
Suite will show a numpad to enter a PIN

**Actual result:**
Suite shows an error resulting not being able to get into Suite

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/131158564-ed7a4b37-9df6-49a3-8723-b7f7925acd45.png)

[log.txt](https://github.com/trezor/trezor-suite/files/7068329/log.txt)

**Comment by bosomt** [comment]
same here, i was able to reproduce issue, 
disabled PIN via trezorctl to get to Suite 

**Info:**
 - Suite version: web 21.9.0 (f9ecf819ac9cc809aa78295793c065c508f74e72)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular

<img width="810" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/131225481-cbfa4857-f3be-426f-a459-3a6601b8b9d1.png">

**Comment by tsusanka** [comment]
cc @matejcik

**Comment by szymonlesisz** [comment]
fixed by https://github.com/trezor/trezor-suite/pull/4198

**Comment by STew790** [comment]
**QA OK**

I could enter the PIN and get into the Suite just fine.

**Info**:
 - Suite version: desktop 21.9.0 (1f5e833a2d214388d3b0c760aa5287e5c83dbd87)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model 1 1.10.3 regular
