### ISSUE TITLE
Maintain connection with trezor-user-env in e2e tests?

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4195]
@mroz22 in https://github.com/trezor/trezor-suite/pull/4084#issuecomment-903308013 we have discussed with @grdddj that we always disconnect and connect to `tenv` for every single command that goes from Cypress. Do you think this is a good idea? Is it a common practice? I think we should connect before every test and then disconnect in some `tearDown` function. I am just wondering if this can't cause some of the flakiness.

Btw shouldn't we also introduce some kind of `restart` function in `tenv` that would bring it to its default state? I mean if we call `startBridge` in one test is there a guarantee that it will be turned off for the following test?

**Comment by mroz22** [comment]
> Do you think this is a good idea?

Definitely not. It is a legacy stuff. I already have some WIP branch that tries to deal with it #3991

> Btw shouldn't we also introduce some kind of restart function in tenv that would bring it to its default state? I mean if we call startBridge in one test is there a guarantee that it will be turned off for the following test?

So far on the Suite's side we have global beforeEach hook that turns bridge off before every test. Each test is then responsible to do its own setup. So far I can live with that I'd say.
