### ISSUE TITLE
Feature Request: PIN and Passphrase focus GUI

### ISSUE THREAD

**Issue by petrkr** [trezor/trezor-suite#4199]
Would be handy if PIN and Passphrase inputs will somehow notice user they are NOT focused (like red border or something)

For example if you want entry PIN but you have opened other windows/pages/tabs like "facebook" and you will accidentally write your PIN (even it's masked by matrix) or passphrase  to that tab. I know this is mostly user's mistake, but when you write pin more times (different wallets, reconnect trezor offten), then it is easy to make post as your passphase

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.

**Comment by petrkr** [comment]
Is it done? Since you closed this issue?
