### ISSUE TITLE
Ask macOS users which processor they have before offering the proper build (Apple Silicon/Intel)

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4206]
**Describe the bug**

At https://staging-suite.trezor.io/ landed new build for macOS M1, 
but default download for macOS M1 is is still Intel version of build.

offered: https://staging-suite.trezor.io/web/static/desktop/Trezor-Suite-21.9.1-mac.dmg
correct: https://staging-suite.trezor.io/web/static/desktop/Trezor-Suite-21.9.1-mac-arm64.dmg

**Steps to reproduce:**
1. use macbook with M1 silicon apple processor
2. go to https://staging-suite.trezor.io/
3. check binary that's offered for download

**Info:**
 - Suite version: desktop 21.9.1 (b5a686adb5a92d59304cfdb1aa032723d49886fb)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular

**Expected result:**
MacOS silicon apple processor binary is offered for download

**Actual result:**
MacOS intel apple processor binary is offered for download

**Screenshots:**

<img width="949" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/131538478-22b4b71f-638f-47a8-b6b7-5d0e493361a9.png">

**Comment by jerechinsky** [comment]
I don't think it is possible to find out which processor the user has. Every macOS software I download makes me select which processor I have with a popup. Perhaps this issue is more of a feature request for this kind of popup. 

Here's how it looks when I try to download chrome:
![Screenshot 2021-09-02 at 10 32 54](https://user-images.githubusercontent.com/75733878/131810739-06b7111d-fc91-479c-bccf-7870f7de6262.png)

**Comment by jerechinsky** [comment]
@matejzak I believe a popup like to one I pasted above could be beneficial. Currently, there's no visual cue or indication as to why the user would have to go to the drop-down and select Apple Silicon, when the download button already shows an Apple icon, leading the user to believe he's good to go (when in fact he's not if he has M1).
![Screenshot 2021-09-07 at 11 57 32](https://user-images.githubusercontent.com/75733878/132325610-6ff4f0eb-8801-4a8b-9020-e713b1f7f857.png)

Only if the user is curious and clicks the Apple logo will they discover that they can download an Apple Silicon build.

![Screenshot 2021-09-07 at 11 57 44](https://user-images.githubusercontent.com/75733878/132325733-8d0685aa-2e35-4adf-a4d0-4718518d0132.png)

**Comment by jerechinsky** [comment]
_Originally posted by @matejkriz  in https://github.com/trezor/trezor-suite/issues/4424#issuecomment-951850978_

> ### Selection of macOS platform needs better UI
> On landing page [suite.trezor.io](https://suite.trezor.io/) (and [suite.trezor.io/start](https://suite.trezor.io/start)) there is no feedback on selection of mac platform. The only option to see what mac platform is selected is to check the link and looking for x64 or arm64 in the filename... <img alt="image" width="244" src="https://user-images.githubusercontent.com/3729633/138718210-564a1958-0f2d-4df5-b1a4-3ec819bdc994.png">
> 
> Check how e.g. Chrome solve it here [#4420 (comment)](https://github.com/trezor/trezor-suite/pull/4420#issuecomment-950659164)
> 
> It's not technically possible to detect Apple Silicon on web reliably and it's because there are so few Apple Silicon users that it would be too strong information for fingerprinting.

**Comment by bosomt** [comment]
**QA OK**
works as expected in Firefox and in Chrome.
