### ISSUE TITLE
Same prices for individual transactions

### ISSUE THREAD

**Issue by DominikRocek** [trezor/trezor-suite#4209]
**Describe the bug**
Omlouvám se za češtinu, neumím moc anglicky, snad to nebude problém...

U každé transakce v Trezor Suite se dříve zobrazovala cena BTC v čase, kdy transakce proběhla, a aktuální cena BTC (viz screenshot, zelené šipky).

Od jisté verze aplikace (bohužel si nepamatuji od které) se obě ceny zobrazují stejně - a to v čase, kdy proběhla transakce.

**Info:**
 - Remembered Wallet: yes
 - Suite Version: app, 21.8.1
 - Browser: ---
 - OS: macOS Big Sur 11.5.2
 - Bridge: ---
 - Firmware Version: Model T, 2.4.1

**Steps to reproduce:**
1. přijmout transakci

**Expected result:**
Ceny by měly být odlišné, jako v dřívějších verzích aplikace.

**Actual result:**
Ceny jsou stejné.

**Screenshots:**

<img width="810" alt="pic" src="https://user-images.githubusercontent.com/35472032/131623183-7a5c5383-6604-454a-94e9-db3462591b83.png">

**Note(s):**
...

**Comment by wendys-cats** [comment]
@DominikRocek ďakujeme za napísanie issue! Táto funkcionalita sa z aplikácie nevytratila, iba presunula do detailu transakcie.

Historická cena coinu vo FIAT prepočte je uvedená v detaile transakcie, tj. keď si rozkliknete konkrétnu transakciu a kliknete na Show FIAT. Objavia sa dva stĺpce, kde jeden ukazuje prepočet hodnôt na FIAT v čase, kedy bola transakcia vykonaná, a druhý stĺpec ukazuje prepočet na hodnoty v prítomnosti. 


**Príklad:**
[transakcia ](https://btc1.trezor.io/tx/afa9c4924908e1d79780fcc158d5befdbb62e39f18f60ac7871b24a7464593cc) z dňa 22.5.2020

**Hodnota BTC v deň transakcie $9,080.33 vs hodnota v prítomnosti $45,084.97**
![photo_2021-09-12_23-29-45](https://user-images.githubusercontent.com/58593111/133003626-a487fdbf-4dad-4cff-845f-f149b7f30504.jpg)

**Transakcia v sekcii Histórie transakcií**
![photo_2021-09-12_23-40-17](https://user-images.githubusercontent.com/58593111/133003647-7f05472f-6bfd-4a6e-8b3c-e1b7d54fe54a.jpg)

**Detail transakcie**
![photo_2021-09-12_23-30-58](https://user-images.githubusercontent.com/58593111/133003665-d97facec-4be8-4902-9b02-44b18ed01ff4.jpg)

**Detail transakcie po kliknutí na Show FIAT**
![image](https://user-images.githubusercontent.com/58593111/133003660-6e913198-3ceb-4519-9382-bc960390f302.png)

**[Video](https://drive.google.com/file/d/16d5V6nAstWETBDPYX6Ki2Ryg3Ij4Ue70/view)**

**Comment by DominikRocek** [comment]
Dobrý den,
děkuji Vám za odpověď a ukázku. Nějak jsem nepostřehl, že je tam funkcionalita schovaná po rozkliknutí. :-)

Mějte se hezky a přeji krásný den.

S pozdravem,
Dominik Roček

**Comment by wendys-cats** [comment]
Resolved, closing issue
