### ISSUE TITLE
Possibility to export / import labels

### ISSUE THREAD

**Issue by DominikRocek** [trezor/trezor-suite#4210]
**Is your feature request related to a problem? Please describe.**
For example, if I reinstall the operating system, I will lose labels. 

**Describe the solution you'd like**
Possibility to export / import labels.

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by stepmes** [comment]
Thanks @DominikRocek very much for this input, we're noting it down and will consider it when working on future improvements.
