### ISSUE TITLE
Add possibility to enter Discreet mode before you load your accounts

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4214]
**Is your feature request related to a problem? Please describe.**
Add possibility to enter Discreet mode before you load your accounts.
It's not really discreet to enter Suite, start to load your accounts and only after that you can enter `Discreet mode`

**Describe the solution you'd like**
`Discreet mode` button added to passphrase modal 

**Additional context**

<img width="623" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/131658512-8785e04f-b97d-490c-a291-fce16337386f.png">

**Comment by glacierbits** [comment]
Thanks for the suggestion @bosomt, I appreciate the proactivity. However, I don't think we should do this because it makes the decision process on this crucial modal even more complex, especially for the novice user. We really want the user to focus on a one thing here, and one thing only.
