### ISSUE TITLE
Trezor Bridge download modal - inconsistencies between browsers and OS combinations

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#4215]
**Describe the bug**
Trezor Bridge download modal is missing elements in certain OS and browser combinations.

**Info:**
 - Suite Version: web 21.9.1 b5a686a
 - Browser: Firefox, Chrome/Chromium
 - OS: NixOS 21.05, macOS Big Sur 11.5.2, Windows 10 19042.1165
 - Bridge: not running
 - Firmware Version: not needed

**Steps to reproduce:**
1. Select an OS and Browser combination,
2. Disable standalone Bridge and quit any running Suite app instance,
3. Launch web Suite and navigate to the Trezor Bridge download modal.

**Expected result:**
Back navigation button, PGP signature link and changelog link are available for all OS and browser combinations; details described below in the screenshots section.

**Actual result:**
Some elements in the modal are missing for some OS and browser combination; Firefox is consistently missing the back navigation button, PGP signature missing in Linux.
- Back navigation button
- PGP signature
- extra image in NixOS Chromium?

**Screenshots:**

 . | Chrome/Chromium | Firefox
------------ | ------------- | -------------
macOS | ![image](https://user-images.githubusercontent.com/10185314/131667131-88ba4f86-08d8-4f37-8b66-f3b5593989e3.png) | ![image](https://user-images.githubusercontent.com/10185314/131667166-cf583db1-58e0-4746-a80f-beb2844c1036.png)
Win10 | ![image](https://user-images.githubusercontent.com/10185314/131667583-2015f9a1-97c7-4e0f-826b-01c35ed84e22.png) | ![image](https://user-images.githubusercontent.com/10185314/131667630-1c60e2f3-2c12-4688-9a90-2ead5894ac9b.png)
NixOS | ![image](https://user-images.githubusercontent.com/10185314/131667794-c3a8d4ed-fd16-4157-b77d-8400c37f4dc1.png) | ![image](https://user-images.githubusercontent.com/10185314/131667699-fa695a26-df85-429a-ac81-6764c0db19e0.png)

**Comment by jerechinsky** [comment]
@matejzak do you know if the image is supposed to be there in the NixOS modal? I'm guessing the correct variant would be the one we can see on Chrome in macOS and Windows. Could you confirm please?

**Comment by matejkriz** [comment]
could be solved together with https://github.com/trezor/trezor-suite/issues/3972

**Comment by bosomt** [comment]
**QA NOK**

same behavior

**Info:**
 - Suite version: web 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: 
 - Transport: N/A

**Comment by marekrjpolak** [comment]
Currently on NixOS:
![image](https://github.com/trezor/trezor-suite/assets/26326960/93ad04f6-e5c1-4c8a-a3f9-12068cc29758)

**Comment by MiroslavProchazka** [comment]
@Hannsek should we spent time on this?

**Comment by Hannsek** [comment]
I wouldn't:

1. webUSB should be available in chromium browsers
2. We don't want users to download standalone bridge anymore as the old bridge will be deprecated soon™️.
