### ISSUE TITLE
Transaction history export to PDF is never generated

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4218]
**Describe the bug**
It's not possible to export transaction history to PDF.
Export to JSON and CSV works as expected.
Tested in web version and in application.Same behaviour in Mint Linux and macOS
Same behaviour when labelling enabled or disabled, it just idles forever when you select PDF as export format.

**Steps to reproduce:**
1. Load wallet that includes transaction history
2. Export transaction history to PDF file
3. Observe Suite behaviour

**Info:**
 - Suite version: web 21.9.1 (c1fd2626a782c05c014d293964e09a4613e3040e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Screenshots:**

![obrazek](https://user-images.githubusercontent.com/31506317/131794865-d84b1b61-84fb-4a8b-9ee0-b3688abd2a50.png)

**Comment by STew790** [comment]
Same behaviour observed on Windows 10

**Info**
- Suite version: app 21.9.1 (c1fd262)
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
- OS: Windows 10 
- Screen: 1366x768
- Device: model T 2.4.2 regular

**Comment by wendys-cats** [comment]
**QA NOK - Windows 10**

Behaviour still persists.


**Suite version**: app and web 21.9.1 (3aacb04b6dfffbacb1b2e60561354caf913d69b0)
**Browser**: Version 92.0.4515.159 (Official Build) (64-bit)
**OS**: Windows 10
**Device**: model T 2.4.2 regular

**Comment by bosomt** [comment]
**QA NOK**

fonts are missing in pdfmake in current devmaster 21.10.0

<img width="606" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/132218994-0f85411c-ef6e-4070-a4fb-dfa3d7781e56.png">

**Info:**
 - Suite version: web 21.10.0 (97259458f0e219cc8f2dc56649facdbf325db2e3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by matejkriz** [comment]
@wendys-cats the link https://github.com/trezor/trezor-suite/commit/3aacb04b6dfffbacb1b2e60561354caf913d69b0 is pointing before the "fix" commit, so you probably tested the old version.

@bosomt unfortunately pointing to current version with the "fix" included, so the issue still remains :-(

**Comment by bosomt** [comment]
@matejkriz too bat it was only change already deployed to staging few minutes ago :) 
https://github.com/trezor/trezor-suite/compare/v21.9.0...v21.9.1

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.9.1 (7d9ab031275907086a2a20f4f3118c3632ef4904)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular
