### ISSUE TITLE
RBF fails when Sending BTC to myself is bumped

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4223]
**Describe the bug**
See video, when you try to bump transaction that was sent from/to same account and included all inputs it will fail during signing process.

`Sign transaction error: requestPrevTxInfo: Requested unknown TXINPUT: d615324b5ac24ed142563fc3eec9d3c0603db3bfac5f84589df18e849077c79a
Sep 03, 2021•10:35`

tx https://btc2.trezor.io/tx/d615324b5ac24ed142563fc3eec9d3c0603db3bfac5f84589df18e849077c79a

**Steps to reproduce:**
1. Send all BTC to same account with RBF enabled
2. Try to bump/finalize transaction
3. Observe error

**Info:**
 - Suite version: desktop 21.9.1 (c1fd2626a782c05c014d293964e09a4613e3040e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Screenshots:**

https://user-images.githubusercontent.com/31506317/131976142-bafa41e6-9e85-43fe-971c-334b84548517.mov

**Comment by bosomt** [comment]
**QA OK**

i was able to bump I was able to finalize transactions.

**Info:**
 - Suite version: web 21.10.0 (d2eb5c94523fcc90e10f42285bb66de2057fad14)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by wendys-cats** [comment]
**QA OK**

Was able to [bump ](https://btc5.trezor.io/tx/390c15a0928847577758619456af694a6120d4d48e9dafafe00bff1d9eec74fa)and [finalise ](https://btc3.trezor.io/tx/a0b4decff2ed48cca1750d28ea538128f252daa0c1d49fbde3542d004a33ef43)a transaction sent to myself (from and to the same account).

**Info:**
**Suite version:** web 21.10.0 8062c36dbafbaa5cb51a154c795c447b4e2edd3e branch develop
**Browser:** Chrome Version 93.0.4577.82 (Official Build) (64-bit)
**OS:** Windows 10
**Device:** 2.4.2 public regular
