### ISSUE TITLE
Can't aqcuire device after refreshing Suite page when connected via WebUSB

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#4226]
**Describe the bug**
When I try to connect to staging Suite via WebUSB on Windows 10 and I refresh the web Suite page right when I am prompted to choose either a standard wallet or a hidden one, the Suite refreshes to a startup page and the device is in "Incorrect state" and if I try to acquire the device using the "Use Trezor here" button it shows me the error as in the screenshot. After that, I am unable to acquire the device or get into the Suite until I reconnect the device.

**Steps to reproduce:**
1. Kill Trezor Bridge in Task Manager
2. Start Chrome and go to staging Trezor Suite
3. Connect Trezor One
4. Acquire the device and enter Suite
5. When prompted to choose either a standard wallet or hidden wallet, refresh the page
6. After the page refreshes, try to acquire the device by clicking on "Use Trezor here" button
7. Observer the error status message in Suite
8. Try to refresh the Suite again, the Suite will "forever" load until an error message appears (as in screenshot 2)

**Info:**
 - Suite version: web 21.9.1 (b52f0002ea6364ac8d8a9f733709732bef4c2305)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
 - OS: Win32
 - Screen: 1440x900
 - Device: model 1 1.10.3 regular
 - Connection: WebUSB

**Expected result:**
I can aqcuire the device after refreshing the page of Trezor Suite when connected via WebUSB.

**Actual result:**
I am unable to acquire the device when refreshing the page of Trezor Suite when connected via WebUSB in the Select wallet type modal.

**Screenshots**

1
![image](https://user-images.githubusercontent.com/48477147/131995815-7536aee4-2e4d-40f6-ad8c-77c465224875.png)

2
![image](https://user-images.githubusercontent.com/48477147/131995960-8badc541-b829-4e62-a638-567019e5596f.png)

**Comment by bosomt** [comment]
@STew790 please retest, i was not able to replicate it , connected via webUSB , i was never asked to re-aquire and i always saw passphrase modal after reload of Suite /current dev master/ 

**Info:**
 - Suite version: web 21.10.0 (fb77977a704f69423947d850153fe54fedeaf6fe)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.9.4 regular

**Comment by STew790** [comment]
I still managed to replicate this. I recorded video as well.

**Info**

- Suite version: web 21.10.0 (f14989d)
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 - -- Safari/537.36
- OS: Windows 10
- Screen: 1366x768
- Device: model 1 1.10.3 regular

**Video**
https://youtu.be/3q-4i1WgFFY

**Comment by wendys-cats** [comment]
Was able to reproduce it with T1. Cannot be reproduced with TT. 

**Info:**
 - Suite version: web 21.12.2 (8cedeed1d1da121ab6b3dff4cb6365b9030634a2)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model 1 1.10.1 regular

![image](https://user-images.githubusercontent.com/58593111/146095938-19c86c51-725b-412e-a8c7-6a5f4c094298.png)

**Comment by STew790** [comment]
**QA OK**

I am not able to reproduce this. Although, I still get the "Device detected in incorrect state" after refreshing the page but I am able to acquire the device.

**Info:**
 - Suite version: web 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1440x900
 - Device: model 1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
