### ISSUE TITLE
Graph tooltip

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#4227]
Bug: Tooltip folds beneath the header area. 

<img width="443" alt="Screen Shot 2021-09-03 at 15 36 23" src="https://user-images.githubusercontent.com/29627086/132014099-152d6c27-3b89-4064-a0d4-01a2f195e582.png">

**Comment by wendys-cats** [comment]
**QA OK - will close when merged into develop**

**OS:** Windows10
**Suite:** WEB 21.10.0 f8fe218bdcd8ccea71857d334b610242ef69961b branch fix/4227
**Device:** TT 2.4.2


Tooltip does not fold beneath the header area anymore.
![image](https://user-images.githubusercontent.com/58593111/134346604-39798b53-f132-474e-9344-8b4fccdb9cb2.png)

**Comment by matejkriz** [comment]
@matejzak please confirm if it's ok to keep it beneath the sticky header (on scroll) or the tooltip should be even above the sticky header - see video in:
https://github.com/trezor/trezor-suite/pull/4266#discussion_r710801519

**Comment by jerechinsky** [comment]
For now let's keep it beneath the sticky header and merge the PR as is. If the product team objects later, then we'll follow up. @pingpwned

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.10.0 (ec1486f8f6086545526b8ec1c01174906213669a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular
