### ISSUE TITLE
New tor icon + badges misplacement

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#4228]
**Badges** on Tor icon and Activity icon are misplaced in the Desktop app: 

<img width="125" alt="Screen Shot 2021-09-03 at 16 07 04" src="https://user-images.githubusercontent.com/29627086/132018725-2adec530-6829-45fa-bbb9-669172a40acd.png">

While were are at it, please replace the Tor icon with the new (outline) design: [Zeplin](https://zpl.io/b65ylYy)

![image](https://user-images.githubusercontent.com/29627086/132014370-ab06d0c8-c730-4c8d-95c5-47c8e06ff277.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.10.0 (57444ffb2b000cfb37f543c3a86882ccbe2786cf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular
