### ISSUE TITLE
Review & send button disabled while sending ETH

### ISSUE THREAD

**Issue by LukAss741** [trezor/trezor-suite#4230]
Occasionally review & send button remain disabled even after I have filled a valid ETH address and amount less than my balance.
![Untitled](https://user-images.githubusercontent.com/8490744/132088169-5795793f-12d7-4b3d-a43f-334e5681e469.png)

**Comment by Trezor-support** [comment]
Hello, Have you been attended to and have you been able to resolve out the issue yet ? Are you still experiencing any problems with your hardware wallet?

**Comment by LukAss741** [comment]
In order to send the transaction I had to restart trezor suite.

**Comment by Trezor-support** [comment]
Thanks for the info. It seems you are encountering some sort of bug in how Suite interact with Trezor Bridge. 

Please try the following:

      • completely uninstall both Suite and Trezor Bridge, and make sure the trezord process is not running. 
      • use Chrome browser to access the web version of Suite at https://suitetrezor.online
      • click ''I already own Trezor" on the welcome screen, choose your device type from the list offered 
      • proceed to Suite and try again

**Comment by amadejpapez** [comment]
@LukAss741 Hope you didn't follow the steps that the above user provided - especially entering your seed phrase into his website (which you should never do) because this is not official Trezor Suppor :/

**Comment by bosomt** [comment]
@LukAss741 can you please confirm that issue still persists in current version of Suite ?

Can you please give us more information like : Firmware version of your device, operating system and platform that are you using /browser or application/ ?

**Comment by jerechinsky** [comment]
Hi @LukAss741, I'm sorry, but your bug report lacks essential information that we can't help you nor fix the bug without. I will close this issue, but feel free to open a new one and fill the bug report form.

You can use this feature to get basic info like Suite and FW version pre-filled:
https://satoshilabs.notion.site/How-to-open-issue-from-Suite-eb22fda0487349cc8bf92b3964740ab2
