### ISSUE TITLE
Trezor model One bootloader mode not detected during FW update

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4233]
**Describe the bug**
I was able to reproduce this issue on macOS, Linux KUbuntu 21.03 works as expected.
Bootloader mode is not detected even after i disconcerted device and reconnected it bootloader mode. 
@STew790 was not able to reproduce it on Windows 10 computer. 
It looks like macOS M1 problem.

**Steps to reproduce:**
1. Start Suite 21.9.1 and proceed with Firmware update of Trezor model One
2. You are asked to confirm reboot to bootloader via device button
3. Observe that bootloader is not detected after you enter bootloader mode

**Info:**
 - Suite version: desktop 21.9.1 (3aacb04b6dfffbacb1b2e60561354caf913d69b0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular
 - bridge  Version: 2.0.31 (rev 5f53132) 

**Screenshots:**
Insert here.
<img width="584" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/132193185-fa83cda1-357c-4a60-aa36-ac4abd540598.png">
[trezor-suite-log-1630919952595.txt](https://github.com/trezor/trezor-suite/files/7114808/trezor-suite-log-1630919952595.txt)

**Comment by bosomt** [comment]
tested with different computers, works as expected.
@sorooris can you please try to replicate it on your mac ?

**Comment by jerechinsky** [comment]
I was able to complete the FW update of my T1 on my M1 mac. It rebooted automatically into bootloader and then I only had to reconnect it once the update was done.

 - Suite version: desktop 21.9.1 (7d9ab031275907086a2a20f4f3118c3632ef4904)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular

**Comment by bosomt** [comment]
looks like problem with "update" from 1.10.3 to 1.10.3

1.10.2 > 1.10.3 **QA OK**
1.10.2 > 1.10.3 **QA OK**


**Info:**
 - Suite version: desktop 21.9.1 (7d9ab031275907086a2a20f4f3118c3632ef4904)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular

**Comment by bosomt** [comment]
Attached Suite log and screenshot of Trezor Bridge and Trezor Suite waiting forever for 1.10.3 in BL mode.

[trezor-suite-log-1631015194220.txt](https://github.com/trezor/trezor-suite/files/7121269/trezor-suite-log-1631015194220.txt)


<img width="1174" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/132339840-7d15fc73-6c1a-4117-845e-cb9f83ec7c45.png">

**Comment by sorooris** [comment]
@bosomt retested and **QA NOK**

Firmwares with non-disconnecting bootloader mode reboot (1.10.1 and newer) are not detected after rebooting on macOS Intel.

Suite: app 21.9.1 7d9ab03
OS: macOS Intel Big Sur 11.5.2
Device: model One 1.10.1, 1.10.2, 1.10.3 (unsigned rc)
Bridge: Suite-bundled 2.0.31 5f53132

**Comment by STew790** [comment]
Unfortunately, it is not a problem of just 1.10.3 FW reinstalling. I just tried 1.10.2 > 1.10.3 firmware update and it happened to me as well.
As @sorooris mentioned, it happens when I press the "Confirm" button on the device and the device to confirm the reboot into the bootloader mode. 
Also unfortunately, for me it is not 100% reproducible. It doesn't happen every time I try this.

**Info**
- Suite version: desktop 21.9.1 (7d9ab031275907086a2a20f4f3118c3632ef4904)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1366x768
 - Device: model 1 1.10.2 regular

**Comment by jerechinsky** [comment]
I just tried again on my my M1 mac 1.10.1 > 1.10.3 and 1.10.2 > 1.10.3 and it got stuck both times. If I reboot into the bootloader using the button, then I can complete the update, but the user doesn't know that ofc. 

**Info:**
 - Suite version: desktop 21.9.1 (7d9ab031275907086a2a20f4f3118c3632ef4904)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.2 regular

**Comment by bosomt** [comment]
I was able to reproduce issue with 21.8.1 version of Suite. Not always but sometimes.


**Info:**
 - Suite version: desktop 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.2 regular

**Comment by tsusanka** [comment]
Let's find out if this is a regression or not.

> I was able to reproduce issue with 21.8.1 version of Suite. Not always but sometimes.

@bosomt Does this mean 1.10.1 -> 1.10.2?

**Comment by bosomt** [comment]
@tsusanka doesn't look like it's FW version related
i just tested 1.10.1 to 1.10.2 upgrade in 21.8.1 and it was 50/50% success.

**Comment by tomasklim** [comment]
@bosomt could you please test https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/366702367?

**Comment by jerechinsky** [comment]
I tried updating about 5 times both `1.10.1 > 1.10.3` and `1.10.2 > 1.10.3` and I've had only about 50% success rate. 😞

**Info:**
 - Suite version: desktop 21.10.0 (d42e5fec301e0d3bc19252a23285c0f1cef99da4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular

**Comment by jerechinsky** [comment]
Here's the log of when I tried to update `1.10.2 > 1.10.3` and Suite got stuck at the `Reboot your Trezor into bootloader mode` screen. Same version desktop 21.10.0 (d42e5fe).

[trezor-suite-log-1631038141637.txt](https://github.com/trezor/trezor-suite/files/7123544/trezor-suite-log-1631038141637.txt)

**Comment by bosomt** [comment]
**QA NOK**

I just tested https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/366702367

After reboot to BL mode and reconnection suite is not able to detect device correctly: 

Device disconnected:

![obrazek](https://user-images.githubusercontent.com/31506317/132454995-3b11005a-570e-4cf9-8a94-77e5cc789afd.png)


Device connected in normal mode:

<img width="1269" alt="Screenshot 2021-09-08 at 7 56 02" src="https://user-images.githubusercontent.com/31506317/132454713-70ff0ba6-22ae-4512-9bcd-55d3fcae1464.png">

**Info:**
 - Suite version: desktop 21.10.0 (d42e5fec301e0d3bc19252a23285c0f1cef99da4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular

edit:
+ KUbuntu Linux, device not detected in BL mode

![image](https://user-images.githubusercontent.com/31506317/132462812-c75ad7d1-5cdc-4cbf-af17-7f4cabd89573.png)

**Info:**
 - Suite version: desktop 21.10.0 (d42e5fec301e0d3bc19252a23285c0f1cef99da4)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model 1 1.10.3 regular

**Comment by tomasklim** [comment]
@bosomt 
You can test it again and please test that it does not break webusbplugin transport and that it also works on Linux/Windows.

(It should work in onboarding and in settings)

**Comment by jerechinsky** [comment]
I just tested Tom's new fix. https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/367051191 

And it works for me. Tried updating `1.10.2 > 1.10.3` about 5 times and each time the update went through. 👏

**Info:**
 - Suite version: desktop 21.10.0 (2debf49411803c570a43c66ea5eac84e61814710)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular

**Comment by tsusanka** [comment]
I think this is fixed?

**Comment by bosomt** [comment]
**QAOK**

@tsusanka yes it was and AFAIK it was fixed in 21.9.2 public release
