### ISSUE TITLE
update pdfmake lib

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#4236]
follow up issue for https://github.com/trezor/trezor-suite/pull/4232

**Comment by bosomt** [comment]
**QA OK**

tested in app and in web version,
additional testing on different OS platform needed

**Info:**
 - Suite version: web 21.11.0 (60ba7ae6f1eea65dfa8692bff0cb3cf9dbcea977)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by bosomt** [comment]
**QA OK**

app + web version

**Info:**
 - Suite version: web 21.11.0 (60ba7ae6f1eea65dfa8692bff0cb3cf9dbcea977)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0
 - OS: Win32
 - Screen: 1536x864
 - Device: model T 2.4.2 regular

**Comment by STew790** [comment]
**QA OK**
Linux app and web version

**Info:**
 - Suite version: web 21.11.0 (9b398dbee120846b7efe9522b6a66b175daaee2f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.1 regular
