### ISSUE TITLE
device detected in incorrect state

### ISSUE THREAD

**Issue by erickie1** [trezor/trezor-suite#4240]
**Describe the bug**

**Info:**
 - Remembered Wallet: yes/no
 - Suite Version: app/web, commit
 - Browser: , version
 - OS: system, build
 - Bridge: build version
 - Firmware Version: model , revision 

**Steps to reproduce:**
1. a
2. b
3. c

**Expected result:**

**Actual result:**
A clear and concise description of what actually happens.

**Screenshots:**
insert here

**Note(s):**

**Comment by erickie1** [comment]
If I connect my trezor, it says: Trezor Bootloader 1.10.0

Trezor says that I have to put my trezor in bootloader mode. They say that I have to hold both buttons pressed and connect the trezor, but nothing changes.

Remembered Wallet: yes/no   I don't know
Suite Version:   I don't know
OS: system, build   Windows 10
Bridge: build version   I don't understand
Firmware Version: model , revision   I don't understand

**Comment by Miaalexande** [comment]
Hello, Have you been attended to and have you been able to resolve out the issue yet ? Have you tried to update your firmware via Trezor wallet ?

**Comment by wendys-cats** [comment]
@erickie1 can you please send the Suite version that you tried the firmware update on?

**Comment by erickie1** [comment]
@Miaalexande No, it isn't resolved. When I click 'update to version 1.10.2', it starts, but then soon stops installing the firmware. The green bar stops at about 20%.

**Comment by erickie1** [comment]
@wendys-cats I don't know how I can see my version. I don't see it at 'properties'

**Comment by Miaalexande** [comment]
> @Miaalexande No, it isn't resolved. When I click 'update to version 1.10.2', it starts, but then soon stops installing the firmware. The green bar stops at about 20%.

Hello, thanks for the info. It seems you are encountering some sort of bug in how Suite interact with Trezor Bridge. 
Send me an email let me put you through on how to update to a newer version! Miaalexander275@gmail.com

**Comment by Miaalexande** [comment]
@erickie1 send me a direct mail ***@***.***

**Comment by jerechinsky** [comment]
Hi @erickie1, I'm sorry, but your bug report lacks essential information. Without knowing which steps you took before you experienced the bug, we can't help you nor fix the bug. I will close this issue, but feel free to open a new one and fill the bug report form. 

Here's how you can find out Suite Version:
https://satoshilabs.notion.site/How-to-open-issue-from-Suite-eb22fda0487349cc8bf92b3964740ab2 

If you require support, please contact Trezor Support:
https://trezor.io/support/
