### ISSUE TITLE
Account renaming and labelling counterintuitive behaviour

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#4254]
**2023/11 update to a more abstract issue:**
Suite's renaming/labelling inputs behave in an counterintuitive manner in some cases. Please update the behaviour as follows:

- Account renaming
  - From the default state, when user clicks [Rename], leave the original text in the input and make it all selected no matter if it was a placeholder or a previously saved custom name. The selection will make it easy to completely rewrite if desired.
    - If the user clicks anywhere in the selected text, keep the text present, deselect it and move the cursor to this position.
    - If the user hits the left arrow button on their keyboard, keep the text present, deselect it and move the cursor to the beginning of the text (as left as possible)
    - If the user hits the right arrow button on their keyboard, keep the text present, deselect it and move the cursor to the end of the text (as right as possible)
    - If the user clicks outside of the input when only the placeholder is present, don't cancel the action. Behave the same as with a custom name being renamed. We have buttons for saving and canceling the action.
    - Nice to have: If in the edit mode users switch tabs within the account (Overview, Details, Tokens, Staking...), don't cancel the renaming action as the tabs are one level below.
- Labels 
  - When editing a label, please act the same as described above at Account renaming
  - When creating a label ("Add label"):
    - If the address is just an address, keep the behaviour as is, that means start the label empty with just a cursor
    - If instead of the address, there's other user's Account name (because the transaction went from/to that other user's account within the wallet)
      - Nice to have version: please use that as a placeholder text, select it and behave as described above for users to be able to use it as a ground for their label and hint to utilize the information of such a specific transaction
      - Basic version: Start the label empty with just a cursor (but not showing the other account name without being able to select/edit it as it's now please)

**Screenshots:**
![Nov-27-2023 08-18-56](https://github.com/trezor/trezor-suite/assets/88533514/34a09497-4cdd-41a3-a927-5955241baca1)

![Nov-27-2023 08-16-28](https://github.com/trezor/trezor-suite/assets/88533514/4a07de54-47c5-4c34-9bee-92d4aa4c2bea)

![Nov-27-2023 08-13-41](https://github.com/trezor/trezor-suite/assets/88533514/1cf5bc6f-34d2-47c8-a327-d3866d7907b2)

![Nov-27-2023 08-10-31](https://github.com/trezor/trezor-suite/assets/88533514/6707db2a-d6be-4cb4-a162-0200fc013998)

**Comment by wendys-cats** [comment]
@alex-jerechinsky I don't think this is a bug issue, since closable modals in Suite behave the same way - clicking outside the bounds results in closing the modal. 

Maybe adding some effects would be the best option? F.e. some sort of overlay when labeling tag is active, or adding coloured bounds for the labeling tag field?

**Comment by Hermez-cz** [comment]
Hi @wendys-cats - I still see this as a bug from the user perspective, as input field is not a modal, so it really should behave like an input (not modal).

I'd suggest using an easy to find best known practice existing - Google documents renaming. The purpose of it is similar (maybe even the same) and it works pretty seamlessly. It even works differently for default and already renamed state.
We just have the save/cancel buttons Google Docs don't, but I'd retain them, as we have an active button entry into edit state while GDocs have the solution, where the title is like always in edit mode. Thus at google it's natural, that it saves the new title just by clicking outside. We have a higher risk situation, so we are benefitting from users actively saving the new account name (works like a double-check).

@matejzak FYI

> @alex-jerechinsky I don't think this is a bug issue, since closable modals in Suite behave the same way - clicking outside the bounds results in closing the modal.
> 
> Maybe adding some effects would be the best option? F.e. some sort of overlay when labeling tag is active, or adding coloured bounds for the labeling tag field?

**Comment by wendys-cats** [comment]
Hi @Hermez-cz, totally agree. The funcionality itself is rigid and not really user friendly. Attending to it will only benefit the app and its users.

**Comment by hynek-jina** [comment]
Imitate UX from https://docs.new/ title edit

**Comment by dahaca** [comment]
Since it became a part of `suite-e`, I'm closing the issue without QA so that it's not dangling in the milestone board. 

QA idea: if that would smoothen the QA process of Suite Empower for yall, you can access all [closed issues](https://github.com/trezor/trezor-suite/milestone/37?closed=1) to see, in more detail, what has been done. We are going to have a meeting soon, I imagine, after we merge the  suite-e to develop to further discuss the next steps.

cc @bosomt @ondracja @STew790
