### ISSUE TITLE
Design of fw update modal and install custom fw is not unified

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4261]
**Describe the bug**
Design of fw update modal and install custom fw is not unified. Custom fw modal has header but fw update modal has not.
Moreover, there is text `Install custom firmware` in the header but `Install firmware` in the body.

**Info:**
 - Suite Version: 21.8.1

**Expected:**
Same design with correct texts

**Screenshots:**
FW update modal
![Screenshot 2021-09-13 at 12 15 48](https://user-images.githubusercontent.com/33235762/133067566-510e4507-4ed1-4262-8b49-ed167c62b545.png)
![Screenshot 2021-09-13 at 12 16 08](https://user-images.githubusercontent.com/33235762/133067568-8f9bf2cb-9ec7-4127-9bf7-d057c183fa82.png)
![Screenshot 2021-09-13 at 12 15 23](https://user-images.githubusercontent.com/33235762/133067561-d5424340-8982-4f24-b530-e0726fd00afb.png)

FW custom modal:
![Screenshot 2021-09-13 at 12 16 28](https://user-images.githubusercontent.com/33235762/133067599-7856ff97-eb9d-4423-a05b-68308ba36507.png)
![Screenshot 2021-09-13 at 12 17 39](https://user-images.githubusercontent.com/33235762/133067606-3f577201-5899-424a-8cc3-62ed6e1cc53a.png)

**Comment by komret** [comment]
Any opinion which direction to take, @dahaca ? I think the header is necessary to indicate what the user is doing, so I would add it to the firmware update modal and tweak the wording in body if needed.

**Comment by komret** [comment]
Resolved by #6835.

**Comment by hynek-jina** [comment]
@trezor/qa  
I have moved this issue to previous sprint as discussed on standup... Just like: https://github.com/trezor/trezor-suite/issues/6831

**Comment by bosomt** [comment]
is this alignment expected ?
looks strange to me 

<img width="106" alt="image" src="https://user-images.githubusercontent.com/31506317/200810601-279ee2a8-6ba0-4540-a313-3e7957c86e10.png">


**Info:**
 - Suite version: desktop 22.11.1 (73ccf723353e0575a64f58b2f5775d20f072311f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.2 Bitcoin-only (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32



<img width="581" alt="image" src="https://user-images.githubusercontent.com/31506317/200810513-78111825-07d6-4c69-983c-9f95b0d2818f.png">

**Comment by hynek-jina** [comment]
@bosomt It should be centered..

**Comment by bosomt** [comment]
BTC to BTC is only version thats not properly aligned. 
Sending issue

**Comment by STew790** [comment]
**QA OK**

Firmware installation and custom FW installation unified correctly.

**Info:**
 - Suite version: desktop 22.12.0 (2f4c0db8c499ac7541080d4aad5707674a21e45f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.11.3 Universal (revision 1852059e87d2070239cbfadb11b8ca516f80457c)
 - Transport: bridge 2.0.32
