### ISSUE TITLE
Bundling (or not) intermediary firmwares inside desktop app

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#4262]
**Is your feature request related to a problem? Please describe.**
To be able to do onboarding in app offline and test new FW before public release (see related issues) we are bundling newest FWs inside desktop app. We put them here https://github.com/trezor/trezor-suite/tree/develop/packages/connect-common/files/firmware and remove older ones so the size of desktop app is not growing with every new FW release (about 4 MB per version).

But the issue is with older FWs on devices, that can't be updated to latest FW directly. On model one it's solved by special intermediary FW, so this one is also included in connec-common files. For model T, 2.1.1 is needed for oldest versions (2.0.5, 2.0.6 and 2.0.7).

**Describe the solution you'd like**
So far it's possibly ok to bundle those two extra binaries (inter ~ 46 KB, 2.1.1 ~ 1.5 MB) so even users with devices with old FWs are able to onboard in desktop suite offline. The downside of this solution is the extra size of app for all users (most of them don't need those extra binaries).

**Describe alternatives you've considered**
Alternative solution is to keep only latest FWs bundled, so most of the users still get it offline and we could test unreleased FWs, but add fallback for older FWs to download them from data.trezor.io as it used to be before.

**Additional context**
Related to -
Bundle (newest) firmware in Suite: https://github.com/trezor/trezor-suite/issues/3738
Do onboarding completely offline: https://github.com/trezor/trezor-suite/issues/3850

**Comment by tsusanka** [comment]
Discussed with the product team: Let's add both inter and 2.1.1. ~ 1.5 MB is nothing.

**Comment by matejkriz** [comment]
It's the current solution, so it's done ;-)
