### ISSUE TITLE
Ethereum - "Bump fee"  1) Improper balance 2) Pending transaction is not visible at all in trezor-suite

### ISSUE THREAD

**Issue by robertkor** [trezor/trezor-suite#4264]
Hello,

I have sent transaction 0x598e26ef1715b7eee24660bcb03032471241214669c28388c1320140023d6e46  with only 22 Gwei.

After that I wanted to "Bump Fee" but BUG 1 ----> application did not see my actual ETH balance (instead balance from the moment of transaction creation was seen).

as a result the transaction 0x598e26ef1715b7eee24660bcb03032471241214669c28388c1320140023d6e46 keeps blocking my account.

 After 2 days, application even does not see pending transaction on the list. BUG 2 ----> not all pending transactions are visible in the app,

Please help unblock my account.

**Comment by robertkor** [comment]
My OS is Windows 10; Trezor 21.8.1

**Comment by Miaalexande** [comment]
@robertkor You’ll need to reconnect your wallet using the wallet dapps integrator to access the other coins on your wallet

**Comment by wendys-cats** [comment]
@robertkor hello, thank you for taking the time to write down errors you have encountered!

I checked several ETH blockchain exporers and your transaction 0x598e26ef1715b7eee24660bcb03032471241214669c28388c1320140023d6e46 is nowhere to be found, looks like it got rejected by the mempool, which should make the balance available again.

**Comment by bosomt** [comment]
@robertkor can you please confirm that your issue was solved and we can close it ?

**Comment by jerechinsky** [comment]
@robertkor let us know if you still experience this.
