### ISSUE TITLE
Reload app on "Install new firmware" prompt. App never loads.

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4267]
**Describe the bug**
A user wants to abort firmware installation but doesn't notice the prompt on the device so he will try to reload the app. However, the app never loads.

**Info:**
 - Remembered Wallet: yes/no
 - Suite Version: web/desktop, 21.9.2
 - OS: macOS arm+Intel
 - Transport: Bridge 2.0.30, Webusb
 - Firmware Version: T1

**Steps to reproduce:**
1. Settings/Device
2. Update firmware
3. Reboot to bootloader
4. Do not Abort/Continue to “Install new firmware? Never do this without your recovery card!”
5. Refresh app

**Expected result:**
App loads and says to user, that he has a device in BL mode.

**Actual result:**
Webusbplugin - App never loads
Bridge - App loads but first bridge crashes (so desktop app is unusable until restart)

**Screenshots:**
Web webusbplugin:
![Screenshot 2021-09-14 at 9 25 26](https://user-images.githubusercontent.com/33235762/133213829-d323ffd0-33a2-41ce-b1b7-6111770c33fa.png)
Web bridge
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x43ddfa9]

runtime stack:
runtime.throw(0x44f3760, 0x2a)
	/usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:378 +0x47c
```

Desktop bridge:
<img width="571" alt="Screenshot 2021-09-14 at 9 39 35" src="https://user-images.githubusercontent.com/33235762/133216255-194a92b5-ad12-4c41-b20d-c754d56380c7.png">

**Comment by marekrjpolak** [comment]
Reproduced on production as well, with exception that in step 5 I have to refresh twice to encounter the error. After the first attempt, one refresh is enough to produce the error.

__Info__:
- Suite Version: web 21.8.1 (production)
- OS: NixOS
- Transport: Bridge 2.0.31
- Firmware Version: 1.10.3

**Comment by tsusanka** [comment]
Let's retest on 21.10.1.

**Comment by wendys-cats** [comment]
Confirming for Suite APP 21.10.2, both for Windows10 and macOS (intel) Big Sur. 

Once the install firmware prompt is present on device, refreshing Suite leads to forever loading.

**Info:** 
**OS**: Windows10 AND macOS Big Sur 11.6 (intel)
**Device**: TT FW 2.4.2
**Suite**: APP 21.10.2 3cb57ead18474b380841b479a542c0b910b3d936

**Another bug is present** - reported here #4388
Moreover, once the install prompt is present on device, and user cancels it and then opens a new Suite instance, device gets a RSOD (Suite does not need to be reloaded before canceling the install prompt).

**Info:** 
**OS:** Windows10 AND macOS Big Sur 11.6 (intel)
**Device:** TT FW 2.0.5 AND 2.4.0
**Suite:** APP AND WEB 21.10.2 3cb57ead18474b380841b479a542c0b910b3d936

**Steps:**
1. Initiate Update firmware action
2. Reboot to bootloader mode
3. Click "Install firmware" button
4. Close Suite
5. Cancel install firmware on device
6. Device stays in BL
7. Open Suite
8. RSOD
![photo_2021-10-19_09-43-13](https://user-images.githubusercontent.com/58593111/137865517-4ac17f3c-495d-45c4-b48a-cd89d86bdae2.jpg)

**Comment by tomasklim** [comment]
Still available, both bridge and webusb. I do not get `RSOD` error though.

The problem is that the device is not responding so Suite never gets `TRANSPORT_EVENT` event which is a prerequisite for the app to be loaded.

@mroz22 Do you have some solution in mind how to stop communication with "lagged" device? It would be nice to get to Welcome screen in Suite and inform user to replug his device.

**Comment by STew790** [comment]
**QA NOK**

Still present in recent Suite version.

**Info:**
 - Suite version: desktop 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision null)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA OK**

both web and app are reporting device in bootloader mode after reload 

<img width="401" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/b694e62a-31cc-47b8-9be2-04871d9163a5">


**Info:**
 - Suite version: desktop 23.7.0 (8ac7640945b9976da035139932fd2932a809c7be)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.7.0 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.12.1  (revision null)
 - Transport: BridgeTransport 2.0.33
