### ISSUE TITLE
Discovery crashes when opening device selector sometimes

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#4268]
**Describe the bug**
When opening and closing device selector modal in Suite during discovery after connecting a device, the discovery process crashes randomly. See video below.

**Steps to reproduce:**
1. Open suite without having Trezor connected
2. Connect Trezor, enter PIN
3. Optional: try to open device selector modal before Suite asks for passphrase
4. Choose standard wallet (or enter passphrase)
5. Approve labeling in Trezor (if enabled), discovery process begins
6. Open and close device selector modal multiple times
7. The discovery process will fail in such circumstances in random time and result

**Info:**
 - Suite version: desktop 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.1 regular

**Expected result:**
Discovery process should run and succeed no matter what the user clicks (except active cancelation like ejecting the device)

**Actual result:**
Discovery process fails randomly. See video below.

**Screenshots:**
https://user-images.githubusercontent.com/88533514/133215608-2a9402b3-6636-4af3-803a-8124645e971a.mov

**Note(s):**
Edge case, users can figure out easily to be tender during the discovery phase to avoid the bug. So priority low.

**Comment by jerechinsky** [comment]
@bosomt have you experienced something similar before? Could you please try to replicate it sometime?

**Comment by bosomt** [comment]
@alex-jerechinsky yes it's common behaviour of suite since I remember ;) 

It usually ends up in state that you are not able to add another wallet even suite says that device is connected.
I usually just reconnect device.

**Comment by tsusanka** [comment]
Let's retest this on 21.10.1.

**Comment by bosomt** [comment]
**QA NOK**

i was able to reproduce issue on first attempt 

<img width="996" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/137274929-b3080abb-fe87-421e-9c37-f4946d79f718.png">

**Info:**
 - Suite version: desktop 21.10.1 (aa3adfa347d0416f970a7fae720d3350f29f8916)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by Hermez-cz** [comment]
I was able to reproduce it as well. Just instead of any error message, the discovery still runs after several minutes with no result. Showing balance 0.00 and skeleton loaders still present

https://user-images.githubusercontent.com/88533514/137294115-8d25497c-7d30-48fd-a17a-23e51351ff71.mov

10 minutes later:
<img width="808" alt="image" src="https://user-images.githubusercontent.com/88533514/137295406-987e8a49-a3e1-49c4-b8e7-dbba38e156e9.png">

<img width="168" alt="image" src="https://user-images.githubusercontent.com/88533514/137295444-5b0f09d1-8074-4a96-a2f0-9798ca796403.png">
<img width="206" alt="image" src="https://user-images.githubusercontent.com/88533514/137295564-72b968d3-a555-4e96-bdfe-79000ee67dc3.png">

**Comment by tomasklim** [comment]
I cannot replicate this issue. 
Maybe it is not available in `21.11.1` anymore or my computer got recovered and no longer has a problem with everything.

@bosomt could you try please?

**Comment by bosomt** [comment]
no problem to replicate in on 21.11.x staging :0
all you have to do is to click on device/modal multiple times during discovery,
pretty much anything that you do during discovery and depends on device will raise error 

<img width="1286" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/141348155-dff809c3-111c-4411-b3c3-f645682a6607.png">

<img width="421" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/141348222-4eaaa386-5d2f-45fb-87d3-5e8e024b5fa6.png">

**Info:**
 - Suite version: web 21.11.2 (e548c52e39f071f0d8d7d8a833bdbd7e2b6fee36)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular

**Comment by tomasklim** [comment]
@matejkriz could you please try this on your device? No success to replicate the issue

**Comment by Hermez-cz** [comment]
@tomasklim @matejkriz 

I might be onto something..

- I have uninstalled Trezor Bridge recently (when testing onboarding edge cases).
- Today, I have updated to v21.10.2.
- Now I have tried to reproduce the bug (without having standalone Bridge) in the desktop app.
- I haven't been able to reproduce the bug. Everything worked well no matter how much I've tried clicking anything on multiple discovery attempts.
- Thinking about what has changed (except the v21.11.2 update), I've quit desktop Suite, downloaded and installed latest bridge. Launched Suite again. Connected Trezor and tried to reproduce the bug. And voila!:

One time I've ended up stuck in an never ending loader:
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/88533514/142020290-572575b1-c6f6-42c4-94b6-74c8e98b6636.png">

Another time with this error notification repeatedly, but the discovery went well in the end at this attempt after.
(Interestingly, within this attempt, when clicking in and out of the "device selection modal", the message "Passphrase entry; Please type your passphrase on the connected host." has been flashing on the device very very shortly (fraction of a second, but long enough to notice)
<img width="492" alt="Account discovery error assert Type Response of" src="https://user-images.githubusercontent.com/88533514/142020422-c3f9d270-4d51-47dd-9c6e-fd3de59d25dc.png">
OR another notification:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/88533514/142021202-5c3be836-4635-4774-8940-6d10af7e6d6b.png">

And another time, when opening and closing the modal really fast, I've been able to get this:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/88533514/142022950-fce73104-3c85-417a-8222-a2e955bbb35f.png">

Don't know if it might be just a coincidence with the Bridge, but it's for sure worth some more testing.

**Info:**
 - Suite version: desktop 21.11.2 (e548c52e39f071f0d8d7d8a833bdbd7e2b6fee36)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.11.2 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.2 regular

**Comment by matejkriz** [comment]
note to myself: here is some issue with duplicated device locks in state

**Comment by matejkriz** [comment]
note to myself: check this test that reproduces the issue [reproducible example for suite-side discovery issues](https://github.com/trezor/trezor-suite/commit/5c5fb7cd4e8af7c447c835cc403dbd372227a55d)

**Comment by matejkriz** [comment]
It's easily reproducible, but still don't understand the exact reason
![discovery-issue](https://user-images.githubusercontent.com/3729633/160438406-f812f34d-1ce6-47dc-8a88-cb1cc6d4364f.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.7.0 (d81e7e2a7c127bc4e494b69375831cd4b0998bd8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.7.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.1 Universal (revision c3f6e8f19fd647c73b414322e287ba23cf8a0c7c)
 - Transport: NodeUsbTransport
