### ISSUE TITLE
Missing Ethereum tooltip during onboarding

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4270]
**Describe the bug**
See screenshot, when you hover over Ethereum during coin selection during on-boarding you only see string name and not tool-tip.
Tool-tip for XRP /I was on-boarding model One/ is displayed correctly.

**Steps to reproduce:**
1. Onboard new device.
2. During coin selection dialogue hover cursor over Ethereum.
3. Observe tooltip

**Info:**
 - Suite version: web 21.9.2 (cc85c69e3d6556e673c4d30f39953179f690b663)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model 1 1.10.3 regular

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/133256497-b0848a1e-4d8b-40fd-a014-9e3024522bfa.png)

**Comment by jerechinsky** [comment]
The `TR_NETWORK_ETHEREUM_TOOLTIP` string is supposed to say `Supported tokens` according to crowdin. Could you please look into it @marekrjpolak ?

**Comment by marekrjpolak** [comment]
The thing is that the 'unavailable' coin tooltips are translated, while the common coin tooltips are currently handled as simple strings. I'll fix it.

**Comment by wendys-cats** [comment]
**QA OK - will close when merged with develop**

**OS:** Win 10 
**Suite:** 21.10.0 d0abe853eedf3fd49a746deb9c8661e2aa0b43d3
**Device:** TT 2.4.2 public regular

Tooltip has translation!
![image](https://user-images.githubusercontent.com/58593111/134339422-3b9ece6e-d9d4-46cc-9b2d-bdf24c8f2654.png)

**Comment by bosomt** [comment]
**QA OK**

now it says `Supported tokens` 

**Info:**
 - Suite version: web 21.10.0 (523970cf503c66effaf1f556d903447e7b2e2302)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular
