### ISSUE TITLE
Auto Updater changelog content could not be retrieved for a moment

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4280]
**Describe the bug**
When auto-updater modal is displayed it shows `Could not retrieve the changelog` in as changelog and then after a while actual changelog is displayed.

**Info:**
 - Suite Version: app, 21.8.1

**Steps to reproduce:**
1. Launch an older version of app

**Expected result:**
It shows loader until real changelog is fetched.

**Actual result:**
It shows `Could not retrieve the changelog`

**Screenshots:**
https://user-images.githubusercontent.com/33235762/133600755-e12d2270-8480-45b8-8bfe-6f8fe58d0b01.mov

**Comment by tsusanka** [comment]
QA has never experienced this so I am assigning LOW priority.

**Comment by bosomt** [comment]
Maybe we could close this issue ?
Or do you want me to replicate this issue ?

So far no reports `Could not retrieve the changelog` and i havent seen it in last year

**Comment by hynek-jina** [comment]
@bosomt Ok, so let's close the issue...

**Comment by tomasklim** [comment]
This has to be duplicate issue, i remember that i fixed that and closed another issue
