### ISSUE TITLE
Suite offered update to Trezor one for v1.10.13, is this an official release?

### ISSUE THREAD

**Issue by drsgomes** [trezor/trezor-suite#4282]
**Describe the bug**
I'm not sure if that's a bug or would be a security vulnerability issue. Or if that should be reported under trezor-firmware.

I've just opened my trezor suite today and saw an option to update to firmware 1.10.13. I was on 1.10.12. *After I did the update* I noticed something weird when I wanted to check the change logs:

1.10.13 it's not there
https://wiki.trezor.io/Firmware_changelog

Also there is no official tag / release in git.

Under Suite/Settings/Device/Security/Firmware Version, when I hover with the mouse the version I get this link:
https://github.com/trezor/trezor-firmware/commit/9276b1702361f70e094286e2f89e919d8a230d5c
If I try to access that doesn't exist.
see screenshot

I'm unsure what to do? Should I be worried?

**Info:**
 - Remembered Wallet: yes
 - Suite Version: Version 21.9.2 (21.9.2.13354)
 - Browser: , version
 - OS: Mac os big sur 11.5.2 (20G95)
 - Bridge: trezord version 2.0.31 (rev 5f53132)
 - Firmware Version: 1.10.13 

**Screenshots:**
<img width="1253" alt="404" src="https://user-images.githubusercontent.com/34476578/133641977-67f1c49b-9063-4c24-a6a5-ecb35d85408c.png">

<img width="1264" alt="version 1 10 13" src="https://user-images.githubusercontent.com/34476578/133634513-6e381f62-77c5-4631-ba19-b1aac81d657a.png">

**Comment by drsgomes** [comment]
I saw there was a bump in the version here: https://github.com/trezor/trezor-firmware/commit/cec1f39a90b8eff65fa2672f258829464ba28fd0

**Comment by drsgomes** [comment]
https://blog.trezor.io/trezor-suite-and-firmware-updates-september-2021-a490f2ea16c1

```
A new version of Trezor Suite (21.9.2) and updated firmware for the Trezor Model T (2.4.2) and Trezor Model One (1.10.3) hardware wallets are now available. Launch Trezor Suite and follow the on-screen prompts to apply the updates.
```

On that page I saw this link, that is accessible:
https://github.com/trezor/trezor-firmware/blob/legacy/v1.10.3/legacy/firmware/CHANGELOG.md

Now when I try to access https://github.com/trezor/trezor-firmware/commit/9276b1702361f70e094286e2f89e919d8a230d5c I can see the content. Sounds like it was something weird going on with github.

**Comment by drsgomes** [comment]
closing it, now I even see it on https://wiki.trezor.io/Firmware_changelog .

Pheww, for a second I thought I'd lose all my cents hehehe

**Comment by tsusanka** [comment]
Apologies, it (a) takes us a while (b) takes some time to clear caches etc. It should be all good now :).
