### ISSUE TITLE
Inform users about broken autoupdater on 21.9.1

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4287]

**Comment by tsusanka** [comment]
Closed by https://github.com/trezor/trezor-suite/pull/4284.

**Comment by tomasklim** [comment]
Config is alive on develop and should be visible only on develop desktop 21.9.1. Download here: https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/373577159

NOT YET AVAILABLE ON PRODUCTION https://github.com/trezor/trezor-suite/releases/tag/v21.9.1

**Comment by tsusanka** [comment]
The config is alive on develop finally. @trezor/qa can you please test the build from @tomasklim? **Not** the production yet. @tomasklim can provide more details if needed.

**Comment by STew790** [comment]
**QA OK**

MacOS M1
21.9.1 app shows message
21.9.1 web no message
21.10.0 app no message

Windows 10
21.9.1 APP OK shows message
21.9.1 WEB OK no message
21.10.0 APP OK no message

Linux
21.9.1 APP OK shows message
21.9.1 WEB OK no message
21.10.0 APP OK no message

**Comment by tsusanka** [comment]
Great. Let's deploy on production on Monday, just in case.

**Comment by tsusanka** [comment]
Deployed to production.
