### ISSUE TITLE
Eject button in device menu has weird red border

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#430]
<img width="315" alt="Screenshot 2019-08-22 at 12 08 15" src="https://user-images.githubusercontent.com/6961901/63506311-8fbb3680-c4d5-11e9-8c63-774268a10520.png">

we left some debug border in DeviceMenu.
`border: 5px solid red;`

**Comment by vladimirvolek** [comment]
fixed in develop
