### ISSUE TITLE
NPM script refactoring

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#4302]
- [x] fix `yarn run suite:dev:desktop` to build with NODE_ENV=development (production is hardcoded now)
- [x] enable logs to console from [runAfterBuild hook in desktop.webconfig](https://github.com/trezor/trezor-suite/blob/develop/packages/suite-build/configs/desktop.webpack.config.ts#L55)
- [x] nice to have: add script for local lint on staged files only
- [ ] add some consistency for scripts (e.g. there is [suite:build:web](https://github.com/trezor/trezor-suite/blob/develop/package.json#L30-L30) but no `suite:build:desktop`)
- [ ] add some clarity: document useful scripts, try to make them easier to understand, remove useless
- [ ] ged rid off script for copy static data trezor-suite/packages/suite-data/index.ts - Webpack CopyPlugin is used instead and could be used in suite-web-landing too

**Comment by tomasklim** [comment]
- [x] fix `yarn run suite:dev:desktop` to build with NODE_ENV=development (production is hardcoded now)
- [x] enable logs to console from [runAfterBuild hook in desktop.webconfig](https://github.com/trezor/trezor-suite/blob/develop/packages/suite-build/configs/desktop.webpack.config.ts#L55)
- [x] nice to have: add script for local lint on staged files only

Are merged in #4303

**Comment by matejkriz** [comment]
no more relevant
