### ISSUE TITLE
Indicate Dev mode in the UI and command line

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4305]
**Is your feature request related to a problem? Please describe.**
There was a bug that auto-updater was mocked in "production" desktop app. If we indicated `dev` mode in UI, we would find the bug earlier. #4273

**Describe the solution you'd like**
Add `-dev` to version in settings and to feedback panel if the app is built in `development` mode.
Show mode when launching and building app in command line.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.10.1 (4b0ade9e0732a14970bd484465b1658044cdea30)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular
