### ISSUE TITLE
Stuck transaction signing (coin stuck)

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#4306]
**Describe the bug**
People are complaining about stucked transaction signing. See more info here https://satoshilabs.slack.com/archives/CL1D61PQF/p1632439318059100 and support ticket #96208. 

**Note(s):**
- probably Connect issue
- it happens in Suite and old wallet too
- happens on T1
- resolved using Electrum
- it's probably not about complexity of the transaction

**Comment by bosomt** [comment]
**QA OK**

so far it looks like it fixed multiple problems with Suite/Bridge 👏🏿 

**Info:**
 - Suite version: desktop 21.10.1 (30698b091e0eff94a2adddf92b15998092d7a3c9)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model 1 1.10.3 regular
