### ISSUE TITLE
Trading - improve destination address selection in exchange and buy

### ISSUE THREAD

**Issue by martinboehm** [trezor/trezor-suite#4308]
Based on feedback from a user:

> Jsem hrozně nešťastný z toho, jak funguje výběr cílové adresy. 
> - Nenačítají se labels, takže se v tom nedá vyznat. Musím se vždycky jít podívat kolikátý account je ten, který chci použít.
> - Nedovolí mi to tam dát custom adresu (nebo jsem to nenašel).

1) display labels in account selection
2) make it possible to choose any account address (show derivation path of the addresses for easier address choice)

**Comment by tomasklim** [comment]
@bosomt I think part 2 is resolved, right? How about the first part

**Comment by bosomt** [comment]
1. labels are present

<img width="558" alt="image" src="https://github.com/user-attachments/assets/5baa0570-e43b-4297-be39-b669acee50e1">

2. any used and used address can be selected nad used including derivation path

<img width="681" alt="image" src="https://github.com/user-attachments/assets/52b0cd67-98fa-4f79-b739-600d834b3bc0">

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
