### ISSUE TITLE
XRP account minium is set to 20 even it's currently 10

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4316]
**Describe the bug**
See link : https://xrpl.org/reserves.html

`
The current minimum reserve requirement is 10 XRP. (This is the cost of an address that owns no other objects in the ledger.) Each new account must set aside this much XRP. Some of this XRP can be recovered by deleting the account.
`

**Info:**
 - Suite version: desktop 21.9.2 (6b68428cc0e94f3c636df43f4f1add14b5f6fab3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Screenshots:**
<img width="1195" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/135487851-d8b19eeb-0b13-4246-90d6-413306256ba3.png">

**Comment by szymonlesisz** [comment]
@bosomt good catch, should be fixed here:
https://suite.corp.sldev.cz/suite-web/fix/xrp-reserve/web/


![Screenshot from 2021-10-04 12-49-08](https://user-images.githubusercontent.com/3435913/135838919-843d4b08-eb67-4355-9007-75f7ed0de604.png)

![Screenshot from 2021-10-04 12-49-55](https://user-images.githubusercontent.com/3435913/135838928-79a3344e-eb1e-4cf5-adeb-f2711f755066.png)

**Comment by bosomt** [comment]
**QA OK**

tXRP and XRP txs tested 
all we need is to change it in wiki

**Info:**
 - Suite version: web 21.10.0 (9c06f475043a4dc816465a5e4068271b23b6d69c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular
