### ISSUE TITLE
Consider blocking sleep when initiating wallet setup/restore/check

### ISSUE THREAD

**Issue by darwin** [trezor/trezor-suite#4321]
I have a MacBook Air M1 (late 2020) with fresh installation of macOS 12.0 (Monterey beta) with default power settings. This affected me multiple times already when working with Trezor (model T) with the notebook running on battery. Some user workflows like wallet restore, initial wallet backup or backup check could take more time entering seed words on the trezor device. If notebook goes to sleep due to keyboard/mouse inactivity, it breaks the workflow and suite ends up reporting some failure at the end (sometimes it gets confusing).

Please consider preventing sleep in those situations. I believe Electron has [powerSaveBlocker API](https://www.electronjs.org/docs/api/power-save-blocker) to do that.

Alternatively you could at least warn user that power settings could cause trouble properly finishing the workflow in time. 

For time being a workaround is to change power saving settings in system preferences and prevent notebook to go to sleep.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
