### ISSUE TITLE
Labelling button does not fit to Wallets modal in Czech translation 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4336]
**Describe the bug**
See screenshot, after translation to Czech language labelling button does not fit to `Wallets` modal.
English and Spanish version looks as expected. 

**Info:**
 - Suite version: desktop 21.10.1 (ea82dd4a00ad06e3c36a267be1c08ade554dac58)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Screenshots:**
<img width="629" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136081473-e22d0fce-75dc-4ebd-a6cd-4b02230b9526.png">

<img width="370" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136081530-610839b1-f33f-42be-b275-bb4f14675701.png">

<img width="310" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136082324-08d85485-6d13-4c20-8476-91ac35e7c7d5.png">

**Comment by jerechinsky** [comment]
I know you were first @bosomt, but Simona later reported it in #4338, so I guess let's keep the reports contained in that issue.
