### ISSUE TITLE
Suite ask you not to hold any buttons when you connect Trezor model T in bootloader mode

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4337]
**Describe the bug**

Suite asks you to:
`Please make sure you are not holding any buttons while connecting your device.`
even you connect Trezor model T in bootloader mode.

**Steps to reproduce:**
1. Start Suite
2. Connect Trezor model T in bootloader mode
3. Observe instructions

**Info:**
 - Suite version: desktop 21.10.1 (ea82dd4a00ad06e3c36a267be1c08ade554dac58)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Expected result:**
Suite inform you about touch screen

**Actual result:**
Suite inform you about buttons

**Screenshots:**
<img width="562" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136088917-eff49d3b-f25d-4edb-922c-7f364cf88c78.png">

**Comment by tomasklim** [comment]
@alex-jerechinsky 

Please change the translation of `FIRMWARE_CONNECT_IN_NORMAL_MODEL_2`
to `Please make sure you are not holding any buttons while connecting your device.`

After that please ping @mroz22 to update default translation strings.

**Comment by wendys-cats** [comment]
@tomasklim you asked to change the message to the exact same text that was there before :D 
Can you please change it to a TT specific instruction text, TT does nto have any buttons to press/to not press.

**Comment by STew790** [comment]
**QA OK**
![image](https://user-images.githubusercontent.com/48477147/145047726-94c2b9c5-19e6-4180-bb01-2c1278236d2f.png)

**Info:**
 - Suite version: web 21.12.1 (c2f3c43646f88ec791001606428cd78f14d3a482)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular
