### ISSUE TITLE
Suite UI 1.5 - General updates

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#4345]
[Figma link](https://www.figma.com/file/pIibgxmxD0jrAa9UGJd9da/Neue-Desktop-1.5?node-id=7433%3A66228) 

- Each part (Colors, TextStyles, ...) can come in its own PR, they don't have to go together.
- We want to iterate, so do the change and ask UI guys for feedback and also give any feedback to them directly.

### Colors:

- [ ] Type/Green: #279503 > #00854D 
- [ ] BG/Green: #39A814 > #00854D
- [ ] Type/Dark Grey: #404040 > #1F1F1F

### TextStyles:

- [ ] Headline/24/Regular > Headline/24/Medium

### Radiuses:

- [ ] Modal boxes: 6 px > 16 px
- [ ] Content card: 6 px > 12 px
- [ ] Inner elements (inputs, buttons, ...): 6 px > 8 px

**Comment by bosomt** [comment]
**QA OK**

looks much nicer /separate minor issues were/will be sent in separate issues/

**Info:**
 - Suite version: desktop 21.11.0 (4a56ae794159091a4f2c4de847d237a47657dc1c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.11.0 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular
