### ISSUE TITLE
Unknown transaction in DOGE transaction history

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4349]
**Describe the bug**
See screenshots. There is `Unknown transaction` in transaction history. MyTrezor wallet works as expected.
All seed, no passphrase, account #1.

https://doge4.trezor.io/tx/e5891f47995e6f79c4f467d755b0026d2cd1524b6d7774b2b4a1f6a841779684
XPUB: dgub8sbe5Mi8LA4dXB9zPfLZW8armvaRkaqT37y6xfT1QA12ErATDf8iGEG8y7kamAnjLuEk9AMpTMMp6EK9Vjp2HHx91xdDEmWYpmD49fpoUYF

**Steps to reproduce:**
1. Connect Trezor with all seed
2. Load Standard wallet and navigate to Account 1 
3. Observe

**Info:**
 - Suite version: desktop 21.10.1 (4b0ade9e0732a14970bd484465b1658044cdea30)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Screenshots:**

<img width="790" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136511281-d5fc0e98-ed52-4d73-93c6-7c7b51b408cd.png">

<img width="768" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136511310-a94a5557-9766-4bd3-b886-ee07e2041dbc.png">

<img width="837" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136511553-162edd53-d432-40c7-86c8-f03c1c171aee.png">

**Comment by tsusanka** [comment]
@tomasklim would it makes sense to do this along with https://github.com/trezor/trezor-suite/issues/4167 and https://github.com/trezor/trezor-suite/issues/3848?

**Comment by tomasklim** [comment]
@tsusanka Those issues are not related. I checked Ethereum and Doge accounts on our fixed development. Ethereum and Doge issues are still there.

**Comment by szymonlesisz** [comment]
i've found this recently.
it's because address `DKu2a8Wo6zC2dmBBYXwUG3fxWDHbKnNiPj` is a change address on path `m/44'/3'/0'/1/0`

usually we don't show change address in target field because they are meant to be hidden.
but this is exception, somehow someone sent DOGE to "hidden" like on every other address.

@tomasklim could you try this?
https://github.com/trezor/trezor-suite/pull/4481

**Comment by szymonlesisz** [comment]
and @bosomt link 4 you:
https://suite.corp.sldev.cz/suite-web/fix/bl-self-change-targets/web/

**Comment by bosomt** [comment]
@szymonlesisz 
**QA OK**

<img width="799" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/141003312-7fd735ac-bff6-4356-bbca-7617838d1bda.png">

**Info:**
 - Suite version: web 21.12.0 (e934c84430b5cdf74b83b4816b111b8314ace4e1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by bosomt** [comment]
I just found same problem on legacy BTC account.
Unknown in Suite 21.10.2 but OK in dev master 🎉 21.12.0
