### ISSUE TITLE
Remote Secure Messaging: on-top banner over toast

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4350]
<img width="949" alt="Screenshot 2021-09-17 at 11 00 32" src="https://user-images.githubusercontent.com/33235762/133756054-b472febe-f140-4afa-8f31-b08fb0e67c26.png">

**Comment by bosomt** [comment]
**QA OK**

_web_
<img width="381" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/139020099-9ff32326-6105-404a-9a8a-54d316d3dbf0.png">

_app_

<img width="366" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/139020439-6b8d2c94-0a2a-4047-bfd4-a718b56be5bb.png">


**Info:**
 - Suite version: web 21.11.0 (55f600be15addfc47aeffc45443137c7c5fef458)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.4 regular
