### ISSUE TITLE
Banner transition from one to another

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4354]
Currently one a banner (such as a notification from the messaging system) is displayed and then dismissed it is directly replaced by another with no animation. Do we want to tackle this?

**Comment by tsusanka** [comment]
@tomasklim could you make a gif/video please to give the product team an idea of what we are talking about?

**Comment by tomasklim** [comment]
Not sure if we need to spend time on it 😀
https://user-images.githubusercontent.com/33235762/140764637-aee3b568-e56b-4731-8323-691a0fbcd6b6.mov

**Comment by tsusanka** [comment]
@Hermez-cz I think you could decide this one :).

**Comment by hynek-jina** [comment]
I see no significant benefit in that..
