### ISSUE TITLE
Push more for Suite update

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4364]
We currently have only about 30% on the latest version. We should push people more to update.

When user skips the autoupdate they are not prompted again on the next launch. This is maybe even a bug? The user needs to go to Settings and click Check for updates which of course none is doing.

@STew790 could you please confirm that this is true for versions 21.7.1, 21.8.1 and 21.9.2? That once clicked on "Skip" during the update modal it is not displayed again on the next launch?

**Comment by STew790** [comment]
I just tried it only on Linux so far and it is, unfortunately, as you mention. When I skip the autoupdate on every version you listed, I don't get prompted again when I open the Suite again. Only when I clear the cache I get prompted again. I will try it on Win10 again later today as well.

**Comment by amadejpapez** [comment]
Looks like something similar is discussed in issue [#4304](https://github.com/trezor/trezor-suite/issues/4304)

**Comment by tsusanka** [comment]
@Hermez-cz is working on how to approach this from the product side with a deadline set to the end of Oct. So let's have this issue in December planning.

**Comment by tomasklim** [comment]
Note: We can use message system banner to push people in old versions.

**Comment by tsusanka** [comment]
Fixed for now by https://github.com/trezor/trezor-suite/pull/4441. There will be two new follow-up issues that we'll link here then.

**Comment by tsusanka** [comment]
Messaging system moved to #4462.

**Comment by Hermez-cz** [comment]
Related issue created: #4463
