### ISSUE TITLE
Android is detected as Linux

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4380]
**Describe the bug**
Android devices are detected as `Linux`. So `Linux` is being sent to analytics instead of `Android` and also `Android` users see tooltip with `Udev` rules.

_We also detect `ChromeOS` as `Android`_

**Comment by STew790** [comment]
**QA OK**

Android and ChromeOS correctly NOT showing Udev rules tooltip. Is it safe to assume that it will show correctly in the analytics as well?

**Android**
![image](https://user-images.githubusercontent.com/48477147/138116069-b8bf1a6e-d820-4ad2-8e52-75003d12b1b3.png)
**ChromeOS**
![image](https://user-images.githubusercontent.com/48477147/138116109-8a9be80e-c59a-40a6-ad4b-1d1e31bf6145.png)

**Comment by bosomt** [comment]
**QA OK**

**Environment**:
SLdev master
Chrome browser

LInux, macOS and Windows 10 tested

![obrazek](https://user-images.githubusercontent.com/31506317/138118019-62bec1b7-beb1-43a1-8939-c994adc25b38.png)
