### ISSUE TITLE
Error when trying to update firmware while discovery is going on

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#4383]
**Describe the bug**
When I tried to do a FW update from 1.10.1>1.10.3 on T1 (connected through WebUSB) that I got prompted to do, while the discovery was still going on, I got an error and I couldn't proceed with the update. The device got stuck on the "restart to bootloader" screen and Suite suddenly tells me to reconnect the device in bootloader mode. Although, if I reconnect the device in bootloader mode, I can proceed with the update, the screen on the Suite and the screen on the device doesn't "match" with the instructions and it gets confusing. Video of this error is attached.

**Steps to reproduce:**
1. Kill Trezor Bridge.
2. Open Trezor Suite on Chrome
3. Connect your device
4. Quickly navigate to the FW update in Trezor Suite, while the discovery is still going
5. Click on "Install"
6. Aggree that you got your seed
7. The error is shown in the notifications and you get prompted to reconnect device in BL mode

**Info:**
 - Suite version: web 21.10.2 (3cb57ead18474b380841b479a542c0b910b3d936)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
 - OS: Win32
 - Screen: 1440x900
 - Device: model 1 1.10.1 regular

**Expected result:**
No error is present and I can continue with the firmware update.

**Actual result:**
An error pops up and it is unclear what to do since the device and the Suite shows different information

**Video:**

https://user-images.githubusercontent.com/48477147/137503568-ac19bd00-1f9d-4380-a88f-88addac4ed59.mp4

**Comment by wendys-cats** [comment]
Was also able to reproduce the bug.

Install after discovery run finishes [here](https://watch.screencastify.com/v/uqxsE4cG0jtRK3ztuN3s).
Install during discovery [here](https://watch.screencastify.com/v/MjLCyWzUv9sbdSNXVZXW).

Do note that the screenshot below was taken during second scenario (Install during discovery). Error probably comes from conflicting actions Suite and device want to take. Device wants to switch to BL mode automatically (and is asking user for this action), but Suite is waiting for manual switch to BL (by reconnecting device while holding both buttons). Action cannot be cancelled or approved via device. Once user switches to BL manually, install can continue on.
![img_20211015_133108](https://user-images.githubusercontent.com/58593111/137716685-ab4592a8-17ac-41c8-a3fb-236a7f443f0d.jpg)


**Info**
**OS:** Windows 10
**Suite:** web 21.10.2 3cb57ead18474b380841b479a542c0b910b3d936 + **webUSB**
**Browser:** Chrome Version 94.0.4606.81 (Official Build) (64-bit)
**Device:** T1 update 1.10.1->1.10.3

**Comment by STew790** [comment]
**QA OK**
This is fixed by the fact that clicking on the update button in the message system cancels the discovery and also in the settings the update button is disabled while discovery is going on.

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32
