### ISSUE TITLE
Blockchain-link refactoring websocket classes

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#4386]
There are 2 very similar files in @trezor/blockchain-link package 

https://github.com/trezor/trezor-suite/blob/a1c3485131b680c2916b51654f26ebf4addba3cc/packages/blockchain-link/src/workers/blockbook/websocket.ts#L40

todo: add link to the other file after #3627 is merged

I suggest refactoring it using [abstract class](https://www.typescriptlang.org/docs/handbook/2/classes.html#abstract-classes-and-members). There will be a new common class containing common methods (connect, init, onmessage..). Subclasses for blockbook and blockfrost should extend this abstract class.

**Comment by hrudolf** [comment]
This issue was solved in this PR https://github.com/trezor/trezor-suite/pull/8954
