### ISSUE TITLE
Number of accounts per user

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4392]
To make Trezor better, we miss information if users use accounts.

**Step 1**
Remove `account-create` event which does not give relevant data. 
Why? When user has e.g. `bitcoin` coin activated, this event is sent 4x (2x for `normal`, 1x for `segwit`, 1x for `normal`). However, this information tells us nothing, because we do not know if he ever used these accounts or not.

**Step 2**
Add event which will be sent when discovery is complete. Sent number of accounts that have at least 1 transaction.
`
{
  btc_normal: 2,
  btc_segwit: 1,
  eth: 1,
  doge: 8
}
`

**Comment by bosomt** [comment]
Is there anything that can/needs to be tested by QA dept ?

**Comment by tomasklim** [comment]
> Is there anything that can/needs to be tested by QA dept ?

You can check in network tab, that it sends current number of accounts and info for all eligible accounts

**Comment by bosomt** [comment]
**QA OK**

found it in Chrome, no luck in Firefox dev tools ;)
@tomasklim thanks for help !

<img width="183" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/140375142-30d897ef-3055-40a3-ae8d-c4c86eb80c2f.png">

**Info:**
 - Suite version: web 21.11.1 (80f65d680e530c601705cd52f033e424d75d2c9a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
