### ISSUE TITLE
Call In Progress Error Notification Response When Clicking On Reveal Address During Discovery

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#4402]
**Describe the bug**
If user interacts with "Reveal address" button in Sign message tab during discovery, "Verify address error: Device call in progress" error is a response from Suite.

**Info:**
 - Remembered Wallet: no
 - Suite Version: web 21.10.2 3cb57ead18474b380841b479a542c0b910b3d936
 - Browser: Chrome Version 94.0.4606.81 (Official Build) (64-bit)
 - OS: Windows 10
 - Bridge: 2.0.27
 - Firmware Version: TT 2.4.2 regular public

**Steps to reproduce:**
**1.** Connect device
**2.** Go to Account Overview
**3.** Open Sign tab
**4.** Select Address
**5.** Click on Reveal Address while discovery is still running
**6.** Error notification "Verify address error: Device call in progress" is shown.

**Expected result:**
Suite will not respond with this error notification - same as for clicking on Receive address.

**Actual result:**
"Verify address error: Device call in progresss" error notification is shown. 
![image](https://user-images.githubusercontent.com/58593111/138140244-ff54cef9-3ccd-405f-84d8-6c7be0dac29c.png)

**Comment by mroz22** [comment]
Reveal address probably shouldnt be active while discovery is running. Maybe it should be disabled and have a tooltip "wait...", or maybe it shouldnt be there at all.

**Comment by matejkriz** [comment]
we want to add check in discovery `start` method, that discovery hasn't finished in case of remembered device disconnected during discovery

**Comment by MiroslavProchazka** [comment]
Should be fixed on 24.3.4

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.4.1 (f4684c1893fe8b0f45c217837e2cbedaa6928d25)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
