### ISSUE TITLE
Various error notifications for Wipe memory during discovery

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#4403]
**Describe the bug**
Suite responds with various error notifications when Wipe memory button is clicken on while discovery is running. 

**Info:**
 - Remembered Wallet: no
 - Suite Version: app and web 21.10.2 3cb57ead18474b380841b479a542c0b910b3d936
 - Browser: Chrome Version 94.0.4606.81 (Official Build) (64-bit)
 - OS: Windows 10
 - Bridge: 2.0.31 trezord for APP, WEBUSB for web version
 - Firmware Version: TT 2.4.2

**Steps to reproduce:**
**1.** Connect device
**2.** Let discovery run through
**3.** Eject wallet
**4.** Go to Device Settings
**5**. Click on Wipe memory button while discovery is still running

**Expected result:**
Suite will not respond with various error notifications, the button will be disabled the whole time during discovery, like Confirm address (in Trade actions) is during discovery. It is visible in video that Wipe memory button actually IS disabled for some time, but either discovery is still running, or there is something cached that intervenes, and ejecting wallet just once is enough for the bug to occur.

**Actual result:**
Suite responds with error notification when clicking on Wipe device while discovery is running.

**Screenshots:**
Device call in progress error
![image (4)](https://user-images.githubusercontent.com/58593111/138140880-c065a48f-5c45-4035-ac15-fe769fd1c8ab.png)

Error: assertType: Response of unexpected type: Features. Should be Success error 
![image](https://user-images.githubusercontent.com/58593111/138141856-4b327fe4-e5f5-44d9-89ac-929cef45a4f3.png)

Error: assertType: Response of unexpected type: Features. Should be Success error AND Error:Wrong previous session
**Video:** [HERE](https://watch.screencastify.com/v/KVXKJXVJ4X9uMOnydVnC)

**Comment by matejkriz** [comment]
wipe button should be disabled till discovery is finished - verify

**Comment by bosomt** [comment]
**QA OK**

yes wipe button is disabled during discovery
im not able to reproduce issue anymore

**Info:**
 - Suite version: desktop 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
