### ISSUE TITLE
Disabling Passphrase for Ronin

### ISSUE THREAD

**Issue by Tea-Cake** [trezor/trezor-suite#4406]
I am currently using a passphrase for my Ronin wallet transactions, I do about 30 transactions daily and found that the passphrase is troublesome. 

I decided to turn it off, after doing that I can no longer do transactions in Ronin
-nothing happens when I click sell/gift/buy, usually a window pops up and lets me enter the passphrase but now nothing happens both on the web and trezor.

I can only do transactions once I turn on the passphrase again.

I am not sure if this is expected or a bug. I expected turning the passphrase off would mean my assets will be moved to my default wallet but it seems that they are stuck in the hidden wallet.

**Comment by mroz22** [comment]
> I expected turning the passphrase off would mean my assets will be moved to my default wallet

This is not how it works
 
> but it seems that they are stuck in the hidden wallet.

This is how it works. But you can always move your funds from your hidden wallet to your standard wallet.

**Comment by Tea-Cake** [comment]
Ahh I see, makes sense. 
Soo apparently my tokens(Axies, AXS, SLP) are not in the trezor hidden wallet and the main one. They are in my cold wallet, Ronin.

Currently still searching ways on how I could by pass the passphrase.

**Comment by mroz22** [comment]
If still not sure how it all works, please read this article https://wiki.trezor.io/Passphrase

In case you have further questions try to look here https://trezor.io/support/

I am closing this as this does not appear to be issue related to trezor-suite codebase.
