### ISSUE TITLE
Allow Guide to be open while a modal is open too

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4409]
Currently you can't open a Suite Guide when another modal is displayed. This hurts especially in the "Connect your Trezor" modal.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.12.0 (f4f9dcf4e2fccf6cf6f1f9d823333c03d81e1eb1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
