### ISSUE TITLE
Suite Guide: Linking between articles

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4412]
It would be nice to be able to link from one article to another.

**Comment by tsusanka** [comment]
I would use the original markdown hrefs that means `[text](../relative/path)` if possible.

**Comment by wendys-cats** [comment]
**QA OK**
**OS:** Win10
**Suite version:** App and Web 21.11.1 5c7e4065e380923b75fdf8543196d25963de538b
**Device:** TT 2.4.2 public regular

**Checked article links**
Remember and Eject OK
Send OK
OP_Return OK
RBF (Replace by fee) OK
Locktime OK
Passphrase OK
