### ISSUE TITLE
Nice categories images for Suite Guide

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4414]
Currently we use only smiple categories boxes that are black & white. Let's put mages there.

[FIGMA](https://www.figma.com/file/fu1f9wihpfaT37QzvCkl4K/UI-Sync?node-id=1%3A33)

![image](https://user-images.githubusercontent.com/3729633/161992821-42c85682-83bd-4383-bc4f-34ae5ee1714e.png)

Export:
[ikones.zip](https://github.com/trezor/trezor-suite/files/8427518/ikones.zip)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.5.0 (7281ac61483e38d974625c2505bfe5efd519aacb)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: 
 - Transport: N/A
