### ISSUE TITLE
Polish Suite for Android

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4417]
As the React Native is not yet being tackled let's give Android a few days to improve the web experience as much as possible. In another words let's do as many "low hanging fruits" in a few days as possible.

Let's bother Product as much as needed in this issues.

**Comment by yohaaan** [comment]
Adding issue:
If the device is in an inconsistent state user is asked to disable WebUSB and use Bridge instead which is not possible on Android - instructions do not make sense. See screenshot:
![image](https://user-images.githubusercontent.com/37402530/139857786-080bf01b-5dc0-4def-97d1-213027b1f5e2.png)

**Comment by STew790** [comment]
I tested the Suite on Android 11 and this is what I found so far:

**QA OK**

Suite on Android now correctly doesn't show info about Bridge or about disabling WebUSB.

**QA NOK**
Some issues I found. (Will update this if I find anything else)

1) You can't swipe to the right here to see the full button
![image](https://user-images.githubusercontent.com/48477147/143901348-8e30f8b7-7b59-4199-bba2-3299635cdaef.png)
2) Same here, you can actually swipe a little to the right, but not "far enough" to see the whole button.
![image](https://user-images.githubusercontent.com/48477147/143901378-13cb922a-6bd8-4ebc-96c3-4a3c4ad20a35.png)
3) The red arrow pointing down is overlapping with the "$" sign
![image](https://user-images.githubusercontent.com/48477147/143901523-4653264e-2495-404c-ace3-62e23076c90a.png)
4) The address is not shown in full (although, when I tried to copy it, it copied the whole correct address)
![image](https://user-images.githubusercontent.com/48477147/143901557-ab8ed6d5-ceed-44ac-bd66-3e4873099e73.png)
5) Not really sure about this one. It does make sense to me, but it doesn't look too good imo.
![image](https://user-images.githubusercontent.com/48477147/143901816-6a217e6d-0318-4681-bdcf-499ed1575f69.png)

**Info:**
 - Suite version: web 21.12.0 (c7dfffccc8602065aafbd8e16198b8dc385ee0f1)
 - Browser: Mozilla/5.0 (Linux; Android 11; Redmi Note 9 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36
 - OS: Linux armv8l
 - Screen: 393x873
 - Device: model T 2.4.3 regular

**Comment by tomasklim** [comment]
3. and 5., this view is not the default one for small screens. On small screens, the squared one should be the default one, which is fine.

**Comment by STew790** [comment]
6. When you are doing a recovery on T1, there is no clear indication of how to confirm the word you enter. You can't click on enter on the keyboard, or rather it doesn't do anything. You need to click on the word that the drop-down menu shows you.
![image](https://user-images.githubusercontent.com/48477147/144033126-5957da43-5aa1-45e2-bf8f-36e472db2c91.png)

**Comment by STew790** [comment]
7. When you click on any "tooltip", the screen can be swiped to the left or right because the tooltip is bigger then the screen. Also, you can swipe further then the "tooltip" actually ends.
![image](https://user-images.githubusercontent.com/48477147/144054115-211e657d-6b2e-4e70-af1c-77c189770907.png)

**Comment by tomasklim** [comment]
1, 2, 4, 7 should be fixed. Give 10 minutes to pipelines

**Comment by STew790** [comment]
**QA OK**
for 1, 2, 4, 7

**Info:**
 - Suite version: web 21.12.0 (2df245a1890912cd11897479c64014feb1bf4800)
 - Browser: Mozilla/5.0 (Linux; Android 11; Redmi Note 9 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36
 - OS: Linux armv8l
 - Screen: 393x873
 - Device: model T 2.4.3 regular
