### ISSUE TITLE
Transaction history export fails when only pending transactions are present on account

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#4427]
**Describe the bug**
When new account is created and it contains only pending transactions, transaction history export fails.

**Info:**
 - Remembered Wallet: yes/no
 - Suite Version: web 21.10.2 3cb57ead18474b380841b479a542c0b910b3d936
 - Browser: Chrome Version 95.0.4638.54 (Official Build) (64-bit)
 - OS: Windows 10
 - Bridge: 2.0.27
 - Firmware Version: 2.4.3 47e17aab

**Steps to reproduce:**
1. Create new account
2. Create a transaction on new account
3. Try to export transaction history

**Expected result:**
Action comes through and transaction history export is downloaded.

**Actual result:**
Error notification "Error: Export failed."

**Screenshots:**
![image](https://user-images.githubusercontent.com/58593111/138869322-24b1947d-c4c8-48cb-8ae5-dd9f72ba7f9e.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/31506317/180985171-0f881c4d-97b4-4e43-aa24-8b93aa966262.png">
