### ISSUE TITLE
Solve Cardano incompatibilities in Connect

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4437]
We can't release firmware in December until we solve the Cardano incompatibilities in Connect as described in https://github.com/trezor/trezor-firmware/pull/1873. We'll also might need to coordinate with Cardano wallets.

**Comment by jerechinsky** [comment]
@ping mroz22

**Comment by STew790** [comment]
**QA OK**

Just tested this with @bosomt
