### ISSUE TITLE
Send form: validate FW version when user enters taproot address

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#4442]
If a user enters a taproot address while using a FW version that doesn't support it, the copy should suggest that user updates their device. Something like this
<img width="564" alt="Screenshot 2021-11-01 at 20 04 57" src="https://user-images.githubusercontent.com/75733878/139734459-834bae2c-97c6-4e69-abd8-a67636a7d667.png">

**Comment by matejkriz** [comment]
The current state is this, right? 
![image](https://user-images.githubusercontent.com/3729633/143606027-ffbb2d23-1c8b-4d4c-9d08-bb747099df7e.png)

So you mean just updating the copy for RECIPIENT_REQUIRES_UPDATE key, @alex-jerechinsky ?

**Comment by jerechinsky** [comment]
That's correct. Thank you, @matejkriz!

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.12.0 (312a355e355722a2bb67e43133434b4e2abebbfc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.4 regular
