### ISSUE TITLE
Application icon size different compared to rest of system

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4446]
**Describe the bug**
See screenshots from macOS.
Trezor Suite app icon has different size compared to rest of applications.

**Info:**
 - Suite version: desktop 21.11.0 (4a56ae794159091a4f2c4de847d237a47657dc1c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.11.0 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Screenshots:**
<img width="1680" alt="Screenshot 2021-11-02 at 21 40 52" src="https://user-images.githubusercontent.com/31506317/139948769-0cc34189-697f-4fc5-9696-8c1a7b900008.png">

<img width="503" alt="Screenshot 2021-11-02 at 21 39 20" src="https://user-images.githubusercontent.com/31506317/139948812-1adf7810-5d58-411c-a8ab-ac9e7c8d2376.png">

**Comment by bosomt** [comment]
I'm not sure if it's OK or not :)
it got better but command + tab icon still looks too big compared to rest of system.

![obrazek](https://user-images.githubusercontent.com/31506317/140639593-7f3353ad-613c-4d94-a4d2-c0d6e5dafaca.png)

<img width="378" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/140639632-850061f0-f0bd-4292-b766-a86807576e04.png">

**Comment by amadejpapez** [comment]
@bosomt It could be that the icon showing there is the previous one still in cache. You could try clearing icon cache with [this](https://gist.github.com/ismyrnow/e92c6010cda9325b2d8811387a05f224) and see if it works then. :)

**Comment by bosomt** [comment]
@amadejpapez perfect :) /but had to kill Suite app first and then clear the cache :)

**QA OK**


**Info:**
 - Suite version: desktop 21.11.1 (5c7e4065e380923b75fdf8543196d25963de538b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.11.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
