### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#4450]
**Design:** [Figma](https://www.figma.com/file/pIibgxmxD0jrAa9UGJd9da/Neue-Desktop-1.5?node-id=8006%3A82796)
 
**Preview:**
<img width="335" alt="Screenshot 2021-11-03 at 11 55 31" src="https://user-images.githubusercontent.com/75733878/140055636-eae68dbf-72f8-445d-87f4-6cf8b439f200.png">

**Comment by karliatto** [comment]
@alex-jerechinsky Could you help me to find the `.svg` files?

**Comment by STew790** [comment]
**QA NOK**

The icon for the error is still as it was before:

![image](https://user-images.githubusercontent.com/48477147/142896524-fcf8d16d-427c-4dd7-b45c-c060951ee764.png)

**QA OK**

The other icons were changed correctly:
![image](https://user-images.githubusercontent.com/48477147/142897404-b8856522-4b52-40e1-8397-33d50d91144d.png)
![image](https://user-images.githubusercontent.com/48477147/142897530-b316783c-562a-4b55-900b-25731005d61c.png)

**Info:**
 - Suite version: web 21.12.0 (86b5c76e14a05ac723738c8ade198a093eb51c22)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.3 regular

**Comment by glacierbits** [comment]
JFYI it's not aligned correctly (please [see design](https://www.figma.com/file/pIibgxmxD0jrAa9UGJd9da/Neue-Desktop-1.5?node-id=8006%3A82460))

<img width="1164" alt="Screen Shot 2021-12-01 at 10 12 22" src="https://user-images.githubusercontent.com/29627086/144216211-9298c9ea-7a30-40e8-bfd8-34406fdf5093.png">

**Comment by matejkriz** [comment]
all success and error icons should be fixed including the alignment

**Comment by STew790** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.12.1 (48d05025d88905d197da84538fb8d4c6d6b6b9e0)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular
