### ISSUE TITLE
Measure Discovery speed

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4457]
This is very "soft" and based on some non-exact feelings and experience but it seems to me that the wallet discovery upon Suite launch takes a bit longer than it used to (let's say during the Beta state). Blockbook infrastructure however is doing just fine. Could we please measure if there is not some ineffectiveness going on?

**Comment by prusnak** [comment]
I assume lots of changed under the hood with the merge of PR https://github.com/trezor/trezor-suite/pull/4421

But I agree with tsusanka that we could try measure some performance metrics between individual commits.

**Comment by tsusanka** [comment]
Intuitively it seems to me this was even sooner. Like 3 - 6 months ago it just felt faster..

**Comment by szymonlesisz** [comment]
new (and the previous) utxo-lib have nothing to do with discovery process. i will be surprised if that will be it.
utxo-lib only have influence on transaction compose (send form) and sending/veryfing process.

**Comment by hynek-jina** [comment]
I performed an inaccurate manual test for discovery load time:

**T1, FW 1.10.4 (BTC-only)**
- Suite 21.6.2 - 15s
- Suite 21.12.2 - 18s

**TT, FW 2.4.3 (All coins)**
- Suite 21.6.2 - 56s
- Suite 21.12.2 - 72s

**Comment by mroz22** [comment]
We could do an automated tests like this:

- run cypress test for discovery
- write text file with the duration as artifact
- deploy a bot (github action?) that will fetch duration from the last develop and/or release pipeline and posts difference into PR.

**Comment by MiroslavProchazka** [comment]
@trezor/qa please test the discovery speed on 24.5.2 version, so we have some comparison after enabling SOL and Polygon. Thx

**Comment by bosomt** [comment]
Tested with BTC,ETH,SOL,POL enabled /most of time was taken by Bitcoin accounts.
Then retested with SOL and POL enabled.


More info here: https://www.notion.so/satoshilabs/Measure-discovery-speed-9104437f74074b36868a505c0e15a5d2?pvs=4

## Results:
## Results:

### First round: BTC,ETH,SOL,POL

- 24.5.2 - 33 seconds
- 24.6.0 - 32 seconds
- 24.4.3 - 44 seconds

### Second round: SOL,POL

- 24.6.0 - 19 seconds
- 24.4.3 - 46 seconds
- 24.5.2 - Polygon PoS: Websocket timeout
- 24.5.2 - same result [https://matic2.trezor.io/](https://matic2.trezor.io/)
<img width="928" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/c79b6416-12bb-458c-9d28-60897812f6ff">

**Comment by bosomt** [comment]
Looks like discovery time changed based on "speed" of discovered network, i dont see any issue on Trezor Suite

### Monday round: SOL, POL

- 24.5.2 - 20 seconds
- 24.4.3 - 37 seconds

**Comment by bosomt** [comment]
Maybe we can consider closing this old issue ?
Its QA OK on our side and discovery time is ok when servers have no issues
