### ISSUE TITLE
Inform users with old versions to update via messaging system

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4462]
Follow-up of https://github.com/trezor/trezor-suite/issues/4364. Let's please inform all users with older versions (let's say 2 months back?) that they should update.

- [x] @Hermez-cz please decide the details (CTA, versions).
- [x] @b-irving please come up with the copy.
- [x] @tomasklim please implement it after the above is done :).
- [x] @vdovhanych deploy stable config

**Comment by b-irving** [comment]
Update Trezor Suite for enhanced security, all the latest features, and to keep everything running as smoothly as possible.

**Comment by tomasklim** [comment]
We also need Czech and Spanish version of 

> Update Trezor Suite for enhanced security, all the latest features, and to keep everything running as smoothly as possible.

@Hermez-cz With CTA we have 2 options:

- navigate user to https://suite.trezor.io/
- navigate user to settings

**Comment by jerechinsky** [comment]
Spanish (verified by @karliatto)

> Actualice Trezor Suite para obtener una mayor seguridad, las últimas funciones y para que todo funcione lo mejor posible.


Czech (verified by me :)

> Aktualizujte Trezor Suite, abyste získali lepší zabezpečení, všechny nejnovější funkce a aby vše fungovalo co nejplynuleji.

**Comment by Hermez-cz** [comment]
> @Hermez-cz With CTA we have 2 options:
> 
> * navigate user to https://suite.trezor.io/
> * navigate user to settings

**Preferably, we could just open the "Update available" modal right from the CTA.**
- If not possible, then we should navigate users to settings. Can we also scroll to the bottom to the Suite version element in such case? If not, we need to mention the location in the copy like "Go to Settings/Application/Suite version" - this solution has one important edge case to keep in mind: We shouldn't show the notification in cases, when the user cannot access Settings at all, like when they haven't connected Trezor yet.

**Comment by Hermez-cz** [comment]
We need to launch the notification after production release of **v21.11.*** and focus it on users with all previous versions, mainly on:
- 21.10.2
- 21.10.1 (pre-release)
- 21.9.2
- 21.8.1
- 21.7.1
- 21.6.2
- 21.6.1
- 21.5.1

**Comment by Hermez-cz** [comment]
Notifications should be dismissable (closeable).

**Comment by tsusanka** [comment]
@Hermez-cz we usually do nut bump the version if everything works, so what we are releasing today is 21.11.1 AFAIK. So I would omit 21.11.* in general.

**Comment by tomasklim** [comment]
> > @Hermez-cz With CTA we have 2 options:
> > 
> > * navigate user to https://suite.trezor.io/
> > * navigate user to settings
> 
> **Preferably, we could just open the "Update available" modal right from the CTA.**
> 
> * If not possible, then we should navigate users to settings. Can we also scroll to the bottom to the Suite version element in such case? If not, we need to mention the location in the copy like "Go to Settings/Application/Suite version" - this solution has one important edge case to keep in mind: We shouldn't show the notification in cases, when the user cannot access Settings at all, like when they haven't connected Trezor yet.

We cannot open this modal from there. 
We cannot scroll to the bottom.
We cannot distinguish cases when settings is not available.

So what should I do? 😀

Another thing, should the notification be blue, yellow or red? (info, warning, critical)

**Comment by tomasklim** [comment]
@Hermez-cz

**Comment by hynek-jina** [comment]
We will navigate user to the [web](https://suite.trezor.io/) with yellow (warning) notification.
Once we implement [Anchor links](https://github.com/trezor/trezor-suite/issues/3889) we can navigate user directly to download app section in settings.

**Comment by jerechinsky** [comment]
Russian

> Обновите Trezor Suite, чтобы улучшить безопасность, использовать все новейшие функции и обеспечить максимально эффективную работу.

**Comment by tomasklim** [comment]
It is live on `develop`, after release we should put current `develop` branch into `codesign` branch and deploy stable config. @vdovhanych

**Comment by vdovhanych** [comment]
It's now live.

**Comment by tsusanka** [comment]
Awesome. Closing then?
