### ISSUE TITLE
Failing e2e tests when a message from message system config is valid in e2e environment.

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4471]
Snapshots of e2e tests start to fail if we deploy develop message system config which is valid in integration test environment.

Solution:

- disable message system config in Cypress (👮‍♀️ ? #4353)
- ignore the banner
- ?

**Comment by matejkriz** [comment]
- create a separate messages config for cypress and mock it?

**Comment by matejkriz** [comment]
this hotfix turned snapshots off https://github.com/trezor/trezor-suite/pull/5215
 - [ ] enable snapshots again

**Comment by mroz22** [comment]
I think this has been resolved, we are now mocking messaging sstem response so that it does not display anything
