### ISSUE TITLE
Sign and verify output not the same between Trezor Suite and wallet.trezor.io

### ISSUE THREAD

**Issue by lf94** [trezor/trezor-suite#4473]
At Bity we have designed a wallet identification system which relies on signatures and their verification. This system is implemented for Ethereum and Bitcoin and their various signature algorithms (painful, but reality.).

A customer reported to us that signing / verifying with a Trezor is no longer working, which I found very surprising. A quick test with my Trezor demonstrated the broken behavior.

I tested then manually signing through wallet.trezor.io and to my surprise, it worked!

So something has changed in the signature generation algorithm in the new Trezor Suite implementation.

Does Trezor want to correct this issue on their side, unifying the behavior between the two implementations, or would Trezor prefer Bity now handle both implementations?

If you'd like to test this behavior simply go to https://bity.com/exchange , continue as a Guest, do a CHF -> BTC order and either choose Other or Trezor. Other you'll have to manually sign; Trezor will open the Trezor windows (but absolutely fail because of this new behavior).

I'm already looking into Trezor Suite as we speak to see what has changed in case I have to change things on our side.

**Comment by lf94** [comment]
I think the issue is P2SH signing is no longer possible in Trezor Suite. When creating a P2SH address and then going to Sign and Verify, it only displays Bech32 addresses. Is this a bug, because when selecting Legacy addresses and then going to Sign and Verify, it properly displays legacy addresses?...

**Comment by lf94** [comment]
(This issue is also probably extremely particular and probably easy to miss. I only see this stuff quickly because I spent a couple months researching all these cryptographic signature schemes and learned how fragmented the ecosystem is. I would like to avoid further fragmentation if we can, as a community.)

**Comment by lf94** [comment]
This issue should be easily recreated by invoking this https://github.com/BitySA/orianne/blob/master/src/wallets/trezor.ts .

I think the issue is also easily resolvable if we simply request a Bech32 address instead of a P2SH one. I think we originally stuck with P2SH because Trezor did not support signing Bech32 for the longest time.

**Comment by bosomt** [comment]
**QA OK**

tested multiple wallets /standard and passphrase wallet.
Same accounts and same addresses produced same signatures.
See screenshots.
It's probably really problem with Bech32 addresses /they are not supported in old wallet that is deprecated and won't be updated in future 

<img width="397" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/140876300-4f59c8b6-4b25-43ca-88a1-bad90d72b228.png">


<img width="792" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/140876453-a408a1fd-f669-4050-89b8-91c79501e6db.png">

<img width="431" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/140877119-e8cfd57c-f3f9-47b9-a1b6-52c2eaeb7330.png">

<img width="1079" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/140876874-622a9c75-944c-4e11-8c6e-2f30ced2ee43.png">

**Info:**
 - Suite version: desktop 21.11.1 (5c7e4065e380923b75fdf8543196d25963de538b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.11.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
 
 - wallet: public version at https://wallet.trezor.io/

**Comment by lf94** [comment]
How are you able to select and sign with a P2SH address? It's simply not possible for me. The UI will just generate Bech32 addresses when I create a P2SH account...

**Comment by bosomt** [comment]
@lf94 

you have to select in in left list of accounts in Segwit section first

<img width="1365" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/140981000-1d542bff-2ef9-45bf-b82b-9b4547b90eef.png">

**Comment by lf94** [comment]
The issue is still present.

Now I think the issue is moved to the fact that some change in payload size prevents our full message from being signed.

The old payload size for messages was 1024 bytes. What is the new payload size? I'm looking around but from what I can tell there is no limit, and maybe the limit is now imposed elsewhere instead of in the firmware.

Edit: After looking around everywhere I really can't find any limits imposed in the new firmware, or trezor-connect. trezor-suite has its hardcoded 255 but it's probably not related at all.

**Comment by lf94** [comment]
I noticed that when we sign, it shows up as hex on the Trezor display, but signing through Trezor Suite it's plain text? Could this affect anything?

**Comment by lf94** [comment]
@alex-jerechinsky @bosomt

**Comment by hynek-jina** [comment]
@lf94 
I've created a separate issue [#4544 ](https://github.com/trezor/trezor-suite/issues/4544) to unify message properties. Therefore this one will be closed.
