### ISSUE TITLE
Settings menu UX fix

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#4477]
**Describe the bug**
Going to settings requires unnecessary amount of clicks.
The dropdown menu should emerge already on hover, not on click. Click on the settings button should go to Settings/Application right away.

**Steps to reproduce:**
1. Open suite
2. Hover on Settings button ⚙️ > it only becomes highlighted
3. Click on Settings button ⚙️ > dropdown menu opens
4. Click on All/Application/Device/Crypto > you'll get to desired settings section

**Info:**
 - Suite version: desktop 21.10.2 (3cb57ead18474b380841b479a542c0b910b3d936)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.2 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.2 regular

**Expected result:**
- Dropdown menu should appear at hover on the Settings button ⚙️ 
- Clicking the Settings button ⚙️ should go to Settings/Application (the same as clicking on "ALL →" does now in the menu)
- The rest of the menu should keep its current function

**Actual result:**
- Nothing opens on hover
- Dropdown menu opens at click on the Settings button ⚙️ 

**Screenshots:**
![image](https://user-images.githubusercontent.com/88533514/140895870-d0595f40-7671-4ce7-bde9-169f16b9229c.png)
![image](https://user-images.githubusercontent.com/88533514/140895937-6b46ea3d-b3f6-4d63-b09d-17556cdbbdac.png)
![image](https://user-images.githubusercontent.com/88533514/140895966-10f5d48f-a677-42fd-ac0a-da24bc7f58b9.png)

**Comment by jerechinsky** [comment]
Moving this into the product column for product team to prioritize.

**Comment by glacierbits** [comment]
Also this.. 

There are 2 hovers layered on top of each other when the menu is open. 


https://user-images.githubusercontent.com/29627086/148103213-7497a84b-f3b6-4a2c-a1fb-df015b0ae559.mov

**Comment by tomasklim** [comment]
- [x] Moved closed to navbar
- [x] Fixed hover on icon when dropdown is open
- [x] Removed Settings, Tor and Early access dropdowns
- [x] Custom backend icon visible only when at least one custom backend is active  
- [x] Tor and Early access anchors added

Not implemented:
- [ ] Tooltips

**Comment by matejkriz** [comment]
This is already released, only the Tooltips are missing, but they will added separately hopefully in https://github.com/trezor/trezor-suite/issues/4728
