### ISSUE TITLE
update DOGE fee policy

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#4480]
https://github.com/dogecoin/dogecoin/blob/master/doc/fee-recommendation.md

**Comment by bosomt** [comment]
**QA OK**

already tested in asana task **[Suite] Bitcoin-like fees**

**Comment by szymonlesisz** [comment]
already in develop, via connect 8.2.3-beta.4 https://github.com/trezor/trezor-suite/commit/33d776ee08dac952823fd73ebdd1c165e7edc23e

**Comment by bosomt** [comment]
**QA OK **

**Info:**
 - Suite version: web 21.12.0 (f4f9dcf4e2fccf6cf6f1f9d823333c03d81e1eb1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
