### ISSUE TITLE
Duplicate code? 

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#449]
it appears here is some refactoring needed:
- [ ] JSONRequest function is used nowhere (according to my spies)
- [ ] there are still some flow-like type annotations
- [ ] it is nested in wallet structure. being it common logic, I'd see it rather somewhere else, lets say `suite`. And maybe we had discussion with @slowbackspace on folder structure in  #443 that was outlining another way how to do it. so just referencing it.

https://github.com/trezor/trezor-suite/blob/c5b000dfea8c1f4783f51485bd900b29cb3edb0d/packages/suite/src/utils/wallet/networkUtils.ts#L4-L26

**Comment by slowbackspace** [comment]
> it appears here is some refactoring needed:
> 
> * [ ]  JSONRequest function is used nowhere (according to my spies)

nice catch! It isn't used even in the next wallet
> * [ ]  there are still some flow-like type annotations

How can I find these?

**Comment by mroz22** [comment]
> How can I find these?

I mean verbose return types, instead of letting typescript decide. 

https://github.com/trezor/trezor-suite/blob/c5b000dfea8c1f4783f51485bd900b29cb3edb0d/packages/suite/src/utils/wallet/networkUtils.ts#L4

or here you can omit `string`
https://github.com/trezor/trezor-suite/blob/c5b000dfea8c1f4783f51485bd900b29cb3edb0d/packages/suite/src/utils/wallet/networkUtils.ts#L8
