### ISSUE TITLE
Investigate the use of yarn-deduplicate

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#4501]
Yarn v2 deduplicates automatically, but since we are stuck with Yarn v1 for now, we could investigate the use of [yarn-deduplicate](https://www.npmjs.com/package/yarn-deduplicate).

The reason why I started to look into this was the following fragment from `yarn.lock`:

```
electron@*:
  version "12.0.0"
  resolved "https://registry.yarnpkg.com/electron/-/electron-12.0.0.tgz#b3b1d88cc64622e59c637521da5a6b6ab4df4eb5"
  integrity sha512-p6oxZ4LG82hopPGAsIMOjyoL49fr6cexyFNH0kADA9Yf+mJ72DN7bjvBG+6V7r6QKhwYgsSsW8RpxBeVOUbxVQ==
  dependencies:
    "@electron/get" "^1.0.1"
    "@types/node" "^14.6.2"
    extract-zip "^1.0.3"

electron@^15.3.0:
  version "15.3.0"
  resolved "https://registry.yarnpkg.com/electron/-/electron-15.3.0.tgz#f9803c5a05b2dac12efc6d4203492c7e204b4819"
  integrity sha512-YLzaKCFmSniNlz9+NUTNs7ssPyDc+bYOCYZ0b/D6DjVkOeIFz4SR8EYKqlOc8TcqlDNu18BbWqz6zbJPyAAURg==
  dependencies:
    "@electron/get" "^1.13.0"
    "@types/node" "^14.6.2"
    extract-zip "^1.0.3"
```

To me, it seems there is no reason why electron 12.0.0 should be in the `yarn.lock`, when obviously `*` can be resolved to `15.3.0` as well.

I tried running `yarn-deduplicate` and to my surprise it generated quite a lot of optimisations.

I pushed these changes into the [`yarn-deduplicate` branch](https://github.com/trezor/trezor-suite/compare/yarn-deduplicate)

Since these are supposed to be reviewed by someone who actually understands the yarn build system, I am not creating a pull request and rather just creating this issue for someone else to pick this up.

**Comment by prusnak** [comment]
Wondering whether the same could be achieved by `rm yarn.lock && yarn`

**Comment by Nodonisko** [comment]
@prusnak I was curious about it so I tried deleting yarn.lock and here are results:

Base: 3.4Gb
Deleted yarn.lock: 2.1Gb
yarn-deduplicate: 1.7Gb

So `yarn-deduplicate` clearly won, another drawback of deleting `yarn.lock` is that it takes like 5 minutes to install modules after and we should do deduplication with every change in `yarn.lock`
