### ISSUE TITLE
QR code generated in receiving address dialog must be bigger

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#4503]
QR code generated in receiving address dialog must be bigger.

Currently it is quite small (~2cm x ~2cm) and very hard to scan from an (Android) phone = you need to put your phone very close to the screen to fill in the necessary space, but then the camera can't get focus and is unable to read the blurry code.

There is plenty of space. We can even position the QR code above the address:

before:

![Screenshot 2021-11-14 at 11 28 40](https://user-images.githubusercontent.com/42201/141677313-783fccf8-4991-4610-8f76-c4273c952007.png)

after:

![Screenshot 2021-11-14 at 11 28 40-after](https://user-images.githubusercontent.com/42201/141677326-bf628c82-2c0f-42e5-8a12-652fa9678214.png)

**Comment by maciejrrr** [comment]
@prusnak, can I help with this problem?

**Comment by prusnak** [comment]
> @prusnak, can I help with this problem?

Sure, Pull Requests are welcome!

**Comment by maciejrrr** [comment]
Ok cool, assign me to this issue pls.

**Comment by maciejrrr** [comment]
https://github.com/trezor/trezor-suite/pull/4792

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.2.1 (863b788827f389eac348f15d8f673cc1069bea00)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.5 regular
