### ISSUE TITLE
Unify case style for enums

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#4504]
Would be nice to have consistent case style for all enums. And it's easier to change it as long as we only have a few of them...

[Typescript docs](https://www.typescriptlang.org/docs/handbook/enums.html) use PascalCase for both - name of the enum and the key names. We could stick with that, but would be nice to have it confirmed in the team.

(The reason why I didn't change it right away is that it could use some refactoring: enum FEE_LEVELS_TRANSLATION have lowercase keys, but they are tied to values of FeeLevel.label...)

**Comment by Nodonisko** [comment]
Also I would recommend some slight refactoring of enums, some could simple use `const enum` and some could be possible replaced with literal types or discriminated unions. These are small changes but can help have nice final code and better error messages.

Read this really nice article: https://robinpokorny.com/blog/typescript-enums-i-want-to-actually-use/
Some more reading: https://dev.to/azure/the-dangers-of-typescript-enums-55pd

**Comment by matejkriz** [comment]
Let's discuss what we want first...
