### ISSUE TITLE
Onion format links present although this setting is disabled

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#4508]
**Describe the bug**
1. Once user enables Tor and onion format links and then disables onion links, they are still present in Suite - in backends and in transcations. Only blockbook related external links seem to be affected - blog and wiki links keep the standard format once the onion links toggle is disabled.
2. If the user only enabled Tor, but onion format link settings is disabled. Again, only blockbook related external links seem to be affected.

**Steps to reproduce:**
1. Enable Tor and onion link formatting
2. Disable onion link formatting
3. Open either backend external links, or transaction external links

**Info:**
 - Suite version: desktop 21.11.2 (e548c52e39f071f0d8d7d8a833bdbd7e2b6fee36)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.11.2 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.2 regular

**Expected result:**
Onion link formatting is not present in Suite once the setting is disabled

**Actual result:**
Onion format is still present in blockbook related external links.

**Comment by bosomt** [comment]
**QA NOK**

same behavior

**Info:**
 - Suite version: desktop 22.2.1 (863b788827f389eac348f15d8f673cc1069bea00)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.2.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Comment by bosomt** [comment]
@hynek-jina maybe we can consider fixing it in upcoming months /consider its low hanging fruit and its open since 11/2021/

**Comment by hynek-jina** [comment]
@bosomt I agree.. since we are touching related areas..

**Comment by STew790** [comment]
**QA OK**
Links are correctly onionized only when the option is ticked by user.

**Info:**
 - Suite version: desktop 22.12.0 (27d68d107208d22d88ee34e4c7deb4c8d1cb4a6f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
