### ISSUE TITLE
Unable to discover wallet of 2nd device when wiping 1st device

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4510]
**Describe the bug**
More than 1 device is connected. One of them is wiped. Some accounts are not discovered without refreshing app.

**Info:**
 - Remembered Wallet: both
 - Suite Version: both, 21.11.2
 - OS: macOS
 - Firmware Version: 1

**How to reproduce**
1. Connect 2 devices with 2 wallets
2. Wipe 1 device
3. Open select wallet modal
4. Click on "Click to discover wallet"
5. Nothing happens

**Screenshots**

https://user-images.githubusercontent.com/33235762/141756976-a704d2c1-b4ee-40e0-8b3a-564c9a89e7eb.mov

**Comment by tsusanka** [comment]
Doing anything during discovery seems to be problematic. Probably related with https://github.com/trezor/trezor-suite/issues/4402 and https://github.com/trezor/trezor-suite/issues/4268.

**Comment by MiroslavProchazka** [comment]
Since it's quite an edge case and we are not planning to dive further into this topic in upcoming months I'm closing it for now
