### ISSUE TITLE
AOPP support

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4512]
Website: https://aopp.group
Short demo video: https://www.youtube.com/watch?v=heP-ufUke-g

**Comment by prusnak** [comment]
> Apparently there is no special format.

I wonder how they handle signing of segwit and native segwit addresses. The constants we used in [here](https://github.com/trezor/trezor-firmware/blob/40bd66ded4132121c0ffb10fd6be7d47a050b323/core/src/apps/bitcoin/sign_message.py) (`+4` and `+8`) were not adopted by Bitcoin Core, but there are the logical way how to extend the original signing protocol. Did AOPP use the same method?

**Comment by andrewkozlik** [comment]
The AOPP-related changes in firmware have been merged into the master branch and will be released in the next firmware update, which is planned in December.

The rest of the work is in trezor-suite. A PR is already open: https://github.com/trezor/trezor-suite/pull/4468

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.1.1 (75797e8edb726d7ede741a1218ff84a2320a92e0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.1.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.5 regular

**Comment by Safardarzaman** [comment]
[Watsap](https://wa.me/message/RFQURKQ4L77OD1) @prusnak

**Comment by Safardarzaman** [comment]
![IMG-20220130-WA0036](https://user-images.githubusercontent.com/96583617/151724269-6ace841c-a909-42ae-9e0e-0515ceab420d.jpg)
![IMG-20220130-WA0037](https://user-images.githubusercontent.com/96583617/151724273-dcae92ec-448e-44cd-a2b1-960b3a90d3ff.jpg)
![IMG-20220130-WA0038](https://user-images.githubusercontent.com/96583617/151724275-b9d8376e-d044-46b4-a9f6-3d29009e5c7f.jpg)
