### ISSUE TITLE
Better transactions export

### ISSUE THREAD

**Issue by jbruchanov** [trezor/trezor-suite#4522]
Add please some overall wallet export into CSV so data can be easily used for example for https://github.com/BittyTax/BittyTax (new format doesn't work nicely if the coin is not included) or any bulk data processing.

Currently I have to export each wallet & coin manually and the CSV file doesn't have a coin column which needs some tedious updates as 1st step.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
