### ISSUE TITLE
onboarding: advanced backup czech translation

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#4524]
This screen should not have option with shamir backup for T1 devices and outdated TT devices. 

![image](https://user-images.githubusercontent.com/30367552/142218459-a6696f69-10aa-41e2-928e-392cc4591f7f.png)

Seen with with device 1.8.1 device:

```
Features (121 bytes) {
    bootloader_hash: 32 bytes 0xf7fa165be6d780f3e1af00abc07df8b3076bcdad72d70da22a63d8896b6391d8,
    device_id: '0E8ED09EE07E3FD594699EC7',
    initialized: False,
    major_version: 1,
    minor_version: 8,
    model: '1',
    needs_backup: False,
    no_backup: False,
    passphrase_protection: False,
    patch_version: 0,
    pin_protection: False,
    revision: 20 bytes 0x964a622bb512aa85cfcc3e451fc70729cc15bb4f,
    unfinished_backup: False,
    unlocked: False,
    vendor: 'trezor.io',
}

```

**Comment by matejkriz** [comment]
It's just a wrong czech translation of TR_ADVANCED_RECOVERY key... cc @alex-jerechinsky

**Comment by mroz22** [comment]
Ah, sorry. Indeed. This screen is for selection of "input type". whether it be standard where user is inputting words directly, or 'advanced' where "pin-like" matrix is used intead. Totally missed that.

**Comment by mroz22** [comment]
I suggest moving it to December 8. Basically all we need is to update translation in crowdin and sync it.

**Comment by bosomt** [comment]
**QA OK**

<img width="339" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/143602733-dfad4ad5-0ae4-43c7-8ce1-76bd6ce95b9e.png">


**Info:**
 - Suite version: web 21.12.0 (312a355e355722a2bb67e43133434b4e2abebbfc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.4 regular
