### ISSUE TITLE
Different fonts used on Trezor Model T and Trezor Suite

### ISSUE THREAD

**Issue by MarMun** [trezor/trezor-suite#4525]
**Describe the bug**
I just noticed that the font used on Trezor Model T screen and the font used in Trezor Suite don't match.

Specifically, I have a hard time to distinguish "1" (number one) from "l" (lower case "L"? or upper case "i"?) in the Suite.

Looking at the Model T screen, it looks like a lower case "L", while in the Suite, I'm not sure.

**Info:**
 - Remembered Wallet: yes
 - Suite Version: app 21.11.2
 - OS: Ubuntu 20.04.3 LTS 
 - Bridge: see suite version
 - Firmware Version: model T, version 2.4.2

**How to reproduce**
1. Go to 'BTC account'
2. Click on 'receive'
3. Click on 'show full address' (fresh address)
4. Compare addresses shown in suite / on device screen

**Expected behavior**
Use a font in suite that makes it easier (possible) to distinguish "1", lower case "L", upper case "i"

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
