### ISSUE TITLE
Suite cannot re-acquire device after wipe (webUSB only)

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#4527]
**Describe the bug**
Suite is unable to re-acquire device after wipe if it is connected via webUSB (bridge works fine). After wipe, the start page is shown with "Begin setup" button, but the button does not react when clicked on. If user wants to start the onboarding process after wipe, Suite needs to be refreshed - after refresh, Suite has no problem acquiring the device.

**Steps to reproduce:**
1. Connect to Suite via webUSB
2. Wipe device
3. Try to begin the onboarding. 

**Info:**
 - Suite version: web 21.11.2 (e548c52e39f071f0d8d7d8a833bdbd7e2b6fee36)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular, tried also with 2.1.6 regular

**Expected result:**
Suite will re-acquire device after wipe and start the onboarding process correctly.

**Actual result:**
"Begin setup" button does not react, Suite is uable to re-acquire device.

**Screenshots:**
![image (5)](https://user-images.githubusercontent.com/58593111/142401433-71d359ba-48ab-4180-bbc8-e1c302ed79ea.png)
**Note(s):**
There is another webUSB issue #4226

**Comment by mroz22** [comment]
This should be obviously solved on some lower level, connect or trezor-link and I am planning to have a look at it. 

But so far there was a workaround in place that we manually display modal "disconnect you device now" if user does wipe using webusb transport

https://github.com/trezor/trezor-suite/blob/0b4323d719c80641091bfa72302d1ad5b4886651/packages/suite/src/actions/settings/deviceSettingsActions.ts#L79-L85

this modal is still expected in modals component but for some reason it does not render. 

https://github.com/trezor/trezor-suite/blob/0b4323d719c80641091bfa72302d1ad5b4886651/packages/suite/src/components/suite/modals/index.tsx#L212

**Comment by mroz22** [comment]
At the moment there are no modals allowed to be displayed over the landing screen which had changed some time ago. So I somehow reintroduced the old behavior here #4545 but it still needs some more considertions.

**Comment by bosomt** [comment]
Same behavior in latest Chrome and Suite dev master

**Info:**
 - Suite version: web 22.1.0 (11f6429fee5b976d9448e2d5cace789f87d4f8c8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Comment by wendys-cats** [comment]
Issue still present

**Info:**
 - Suite version: web 22.1.1 (e7262e597f6af0487e17ef055a2583425c7a5302)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular

**Comment by wendys-cats** [comment]
QA OK on wipe-device-workaround branch! Tried wipe from FW and BL both, disconnect prompt is present.

 - Suite version: web 22.1.0 (12ad8517ff43e064dc2ce3d38c324a896db7e39d)  wipe-device-workaround branch
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model  TT and T1
