### ISSUE TITLE
CSV export including labels (metadata) for Desktop suite (Win/Linux) ?

### ISSUE THREAD

**Issue by MCM-Mike** [trezor/trezor-suite#4530]
From the current development (https://github.com/trezor/trezor-suite/pull/3867 & https://github.com/trezor/trezor-suite/issues/3185 https://github.com/trezor/trezor-suite/issues/3892  ) and my understanding the CSV export is only working on the "web-suite" (https://suite.trezor.io/) using Dropbox and G-Suite (google). 

But are you going to implement it also on the desktop (Windows, Linux) suite ?

**Comment by mroz22** [comment]
Hello, it is implemented and it works on my machine. If it does not work on yours, please provide more info about what exactly does not work for you.

**Comment by MCM-Mike** [comment]
> Hello, it is implemented and it works on my machine. If it does not work on yours, please provide more info about what exactly does not work for you.

Could you verify, the local download of a CSV including labels is working for you ?
Without the integration into Google-Drive or dropbox.

**Comment by stepmes** [comment]
We're noting this issue down and will re-test it when working on it in the future.
