### ISSUE TITLE
Naming accounts

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#4534]
Taproot PR https://github.com/trezor/trezor-suite/pull/4486 will require some followup. Moved from [notion](https://www.notion.so/satoshilabs/Taproot-product-copy-db17b96784a74ad4bc1cc2d47d9f1bc1).

Naming accounts

Add account dialog and Account details page should be reworked regarding account names.
there are 4 pieces of information we might want to present here:

- "human readable account type"
- bip standard which is implemented
- input script type being used
- address format encoding

account types:

- Taproot | `BIP86` | `P2TR` | `Bech32m`
- Segwit | `BIP84` | `P2WPKH` | `Bech32`⇒ this one is default for the time being
- Compat/Legacy Segwit | `BIP49` | `P2WPKH-nested-in-P2SH` | `Base58`
- Legacy | `BIP44` | `P2PKH` | `Base58`

**Comment by prusnak** [comment]
Before:

<img width="658" alt="Screenshot 2021-11-19 at 20 26 06" src="https://user-images.githubusercontent.com/42201/142680484-13a4b4e4-b699-44ac-84d1-33690817c881.png">

My suggestion:

* SegWit | BIP84, P2WPKH, Bech32
* Taproot | BIP86, P2TR, Bech32m
* Legacy SegWit | BIP49, P2SH-P2WPKH, Base58
* Legacy | BIP44, P2PKH, Base58

**Comment by prusnak** [comment]
I sent a PR to your `feat/taproot` branch which implements the above suggestion and also cleans up the stuff so it is more consistent: https://github.com/trezor/trezor-suite/pull/4535

**Comment by bosomt** [comment]
Maybe you can fix it in Firmware when on it ? See https://github.com/trezor/trezor-firmware/issues/1341

**Comment by prusnak** [comment]
> Maybe you can fix it in Firmware when on it ? See [trezor/trezor-firmware#1341](https://github.com/trezor/trezor-firmware/issues/1341)

Good point! PR in https://github.com/trezor/trezor-firmware/pull/1930

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.12.0 (312a355e355722a2bb67e43133434b4e2abebbfc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.4 regular
