### ISSUE TITLE
Invalid transaction params: Params specify an EIP-1559 

### ISSUE THREAD

**Issue by Cesper1968** [trezor/trezor-suite#4536]
Hello, I'm trying to Withdraw some rewards from Polygon to my wallet and received the message "Invalid transaction params: Params specify an EIP-1559 trans

This is affecting all of Trezor One+Metamask users.
Is there any ETA or guide on how to transact in the meantime? Thank you!

**Comment by prusnak** [comment]
Metamask team are working on a fix - see https://github.com/MetaMask/metamask-extension/issues/12130
