### ISSUE TITLE
Ethereum ERC20 approval transactions do not show fees in transaction history

### ISSUE THREAD

**Issue by martinboehm** [trezor/trezor-suite#4537]
The ERC20 approval transactions necessary for DEX do not show fees in the transaction history:
![image](https://user-images.githubusercontent.com/11609674/142777063-a7ec72a1-e2e9-48c4-9ac7-749f565d78f4.png)
The detail is correct:
![image](https://user-images.githubusercontent.com/11609674/142777077-af4737ab-d8cd-4890-9eee-c6d75dc5e11d.png)
The issue is reported on transaction https://eth2.trezor.io/tx/0xaf642709f422116a36e7777db5232288f78f3e09ae77593ba265a09056724e6b but can be reproduced on all approvals.

Probably related to https://github.com/trezor/trezor-suite/issues/4526

Suite Version: web 21.11.2

**Comment by STew790** [comment]
**QA OK**
via https://github.com/trezor/trezor-suite/pull/4551
