### ISSUE TITLE
Microsoft Edge Chromium is wrongly detected as unsupported on https://suite.trezor.io/web/

### ISSUE THREAD

**Issue by flawedworld** [trezor/trezor-suite#4538]
**Describe the bug**
When I use Microsoft Edge Chromium to navigate to https://suite.trezor.io/web/ I get told I need to install a supported browser.

**Info:**
 - Remembered Wallet: N/A
 - Suite Version: Web hosted on https://suite.trezor.io/web/
 - Browser: Microsoft Edge 96.0.1054.29
 - OS: Windows 11
 - Bridge: N/A
 - Firmware Version: N/A
 - User Agent: ```Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 Edg/96.0.1054.29```

**How to reproduce**
1. Open https://suite.trezor.io/web/ in Microsoft Edge Chromium
2. UI demands that I install Chrome or Firefox

**Expected behavior**
To be able to use Trezor Suite within Microsoft Edge Chromium.

**Comment by prusnak** [comment]
This is intentional. We do not do QA on Microsoft Edge, so it is unsupported.

Please install Chrome to use WebUSB or install the desktop version of the Suite.
