### ISSUE TITLE
Unify signature input message properties

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4544]
- [x] Validate ASCII only message input for signature.
- [x] Unify max message input size to 1024 bytes.
- [x] Allow longer message insertion with warning about the size limit.

Related to: https://github.com/trezor/trezor-suite/issues/4473

**Comment by bosomt** [comment]
3x **QA OK**

please consider greying out Sign and verify button when you are not able to sign or verify transaction. Event button is not active it's always green. /Maybe there is already issue for this i'm not sure/

<img width="777" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/144043531-adc95856-3a25-49d6-a04a-671dd5baa177.png">


<img width="748" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/144043824-6c67c518-ec69-4231-8a3e-f69496cac16a.png">

**Info:**
 - Suite version: web 21.12.0 (f4f9dcf4e2fccf6cf6f1f9d823333c03d81e1eb1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Comment by bosomt** [comment]
OK Disregard my last comment about button. There is already issue to track this issue here https://github.com/trezor/trezor-suite/issues/4100

**Comment by lf94** [comment]
Has this been released?

**Comment by lf94** [comment]
From what I can tell this has fixed the signature failure issue we were having here: https://github.com/trezor/trezor-suite/issues/4473. Thank you very much!
