### ISSUE TITLE
Trezor should not block account creation with "Previous account is empty"

### ISSUE THREAD

**Issue by aspiers** [trezor/trezor-suite#4546]
## Bug description

With Trezor Suite 21.11.2, attempts to create a new account are met with "Previous account is empty" if the Suite thinks the previous account is empty.  This is most likely the intended behaviour, but I contend that it is not correct.  There are many use cases where there is a valid need for allowing consecutive "empty" accounts.  These fall mostly into two categories:

1. The previous account is not empty, but Trezor Suite doesn't realise it.  This has happened before, e.g. #3402, but it could also happen when the account is used on a chain which Trezor Suite does not monitor, or for other reasons which haven't yet been considered.
2. The previous account is empty, but has been reserved to be used for a specific purpose later.  In this case, it is perfectly reasonable for a user to want to reserve one or even multiple accounts for different purposes, in which case they should not be blocked from creating new accounts.

## Info

 - Remembered Wallet: yes
 - Suite Version: 21.11.2 (app)
 - Browser: not relevant to this bug
 - OS: openSUSE Tumbleweed
 - Firmware Version: model T, 2.4.2 

## How to reproduce

1. Open Trezor Suite
2. Click on `Accounts`
3. Click plus icon to create new account
4. Click `Ethereum Incl. ERC-20 tokens`
5. Try to click `+ Add account`

## Expected behavior

It displays a warning that the previous account is empty (ideallywith a link to a page explaining in more detail why this could be an issue), but still allows me to ignore the warning and add a new account.

## Screenshots

![image](https://user-images.githubusercontent.com/100738/143055958-b2f2abec-9e15-40ea-9fa7-477b96623eeb.png)

**Comment by prusnak** [comment]
> 1. The previous account is not empty, but Trezor Suite doesn't realise it.

This is a bug and we should fix it.

> 2. The previous account is empty, but has been reserved to be used for a specific purpose later.

This is a desired feature and we are not going to implement it, because it goes against the "Account discovery" described in BIP44: https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Account_discovery

**Comment by prusnak** [comment]
@aspiers I assume you have not found a new bug (1) and you are just expressing your desire for (2), right?

**Comment by aspiers** [comment]
Firstly thanks a lot for the quick response.

[**@prusnak**](https://github.com/prusnak) commented on [November 23, 2021 6:53 PM](https://github.com/trezor/trezor-suite/issues/4546#issuecomment-977013836 "2021-11-23T18:53:26Z - Replied by Github Reply Comments"):
> [@aspiers](https://github.com/aspiers) I assume you have not found a new bug (1) and you are just expressing your desire for (2), right?

Not really; it's not (just) about bugs: 

[**@prusnak**](https://github.com/prusnak) commented on [November 23, 2021 6:52 PM](https://github.com/trezor/trezor-suite/issues/4546#issuecomment-977012340 "2021-11-23T18:52:13Z - Replied by Github Reply Comments"):
> > 1.  The previous account is not empty, but Trezor Suite doesn't realise it.
> 
> This is a bug and we should fix it.

Not necessarily, e.g. what if the device is used on a chain that Trezor Suite doesn't even know about?  What if it's not even a public chain?

Even if there was some theoretical way for the Suite to know about every single transaction out there, there is still the distinct possibility that it might not behave perfectly in every scenario.  This is not meant as criticism, it's just a fact that all software is imperfect, and it takes time and resources to fix imperfections.  For example the Suite can't correctly handle internal transactions yet (#3658) - this was recognised in April but is not fixed yet.  There's no shame in that - software is hard ;-)  But this is why it's better to adopt a defensive position, and instead design behaviour which tolerates those imperfections gracefully, rather than blocking functionality when it encounters them.

> > 2.  The previous account is empty, but has been reserved to be used for a specific purpose later.
> 
> This is a desired feature and we are not going to implement it, because it goes against the "Account discovery" described in BIP44: [https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Account\_discovery](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Account_discovery)

Yes, I am familiar with this aspect of BIP-44.  I assume you are referring to this:

> This algorithm is successful because software should disallow creation of new accounts if previous one has no transaction history, as described in chapter "Account" above.

However the conclusion that allowing empty accounts goes against that standard can only be reached if you stop reading there and ignore the rest of the spec.  If one continues to read, in fact it's quite the opposite; the ["Address gap limit" section](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#address-gap-limit) directly below this states:

> Address gap limit is currently set to 20. If the software hits 20 unused addresses in a row, it expects there are no used addresses beyond this point and stops searching the address chain.

In other words, it not only possible but *expected* that users will have used addresses *after* unused addresses in the HD sequence - possibly as many as 19 unused addresses in a contiguous sequence in this example.  In fact, [your own wiki acknowledges this](https://wiki.trezor.io/Address#How_an_address_is_derived):

> Users can create as many addresses as they want without any costs. This can be useful for e-commerce websites where a fresh (or unused) address is generated for each customer. On the other hand, the BIP44 standard for Bitcoin hierarchical deterministic wallets proposed to respect the Address gap limit, which is also used in Trezor Wallet, limits the number of fresh addresses created under one account to 20.

On a side note, I recall that Ledger software allows the user to configure the size of the gap, and one of my acquaintances successfully raised the gap to 50 on at least one occasion.  It would be great if Trezor Suite allowed similar flexibility.  This was highlighted and requested recently in your forums: https://forum.trezor.io/t/bug-problems-with-the-addresses-generated-with-the-bitcon-legacy-xpub-and-the-paths-generated-for-some-addresses-balance-problem/3529/5

I believe the choice of a gap of 20 in BIP-44 was relatively arbitrary, and ultimately it should be left to the user to decide where they want the trade-off between performance and flexibility of address management.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.

**Comment by marceljay** [comment]
Is there a mitigation to this issue?
I would propose to use the hidden wallet feature where I just use passwords like "1", "2", "3", but not sure if there are any consequences to this hack.

**Comment by prusnak** [comment]
> Is there a mitigation to this issue?

Sending a transaction to account to make it not empty.

**Comment by aspiers** [comment]
[**@prusnak**](https://github.com/prusnak) commented on [May 19, 2022 5:52 PM](https://github.com/trezor/trezor-suite/issues/4546#issuecomment-1131954866 "2022-05-19T16:52:04Z - Replied by Github Reply Comments"):
> > Is there a mitigation to this issue?
> 
> Sending a transaction to account to make it not empty.

I can confirm that works; however I don't think this issue should have been closed as completed because it's still an ongoing issue.

**Comment by marceljay** [comment]
> > Is there a mitigation to this issue?
> 
> Sending a transaction to account to make it not empty.

This also means, it cost real money to create multiple trezor accounts and potentially clutters the blockchain

**Comment by aspiers** [comment]
I just hit this again, this time with Bitcoin wallet creation:

![image](https://github.com/trezor/trezor-suite/assets/100738/85508a1b-5927-43d7-94ab-923d9f22173f)

It's very obviously a usability issue, would be easy to fix, and violates BIP-44 and contradicts [your own documentation](https://trezor.io/learn/a/addresses-transaction-history) as [previously explained](https://github.com/trezor/trezor-suite/issues/4546#issuecomment-977835680).

So please could you reconsider your decision not to fix this?

Even _before_ fixing this issue, there is another UX issue that the tooltip above the disabled button says "Previous account is empty", which is very cryptic and confusing to anyone not familiar with BIP-44.  **At very least** it should clarify that accounts are ordered sequentially, and that the previous account needs to receive a transaction in order to re-enable the `Add account` button.

**Comment by theronic** [comment]
Need to receive two separate payments into two wallets, so tried to create two new wallet addresses, but can't create two empty accounts because "previous account is empty." No dice – please fix, guys!

**Comment by prusnak** [comment]
> Need to receive two separate payments into two wallets, so tried to create two new wallet addresses, but can't create two empty accounts because "previous account is empty." No dice – please fix, guys!

Send payment to first account. Done. You can create second one. Done.

**Comment by theronic** [comment]
The reason I am creating two addresses in the first place is so that they are not linked in any way to each other, or any other of my addresses. So I don't want to move funds from any other accounts to them, even if the fees are low (or txes are fast), but I need to request payment from two different people at the same time.

Is there a command-line workaround? Why are you forcing customers into a buying position for a different hardware wallet that does not impose this limitation? Surely this is not a technical limitation of btc? :/

**Comment by theronic** [comment]
If you must limit it, limit it to like 5 empty addresses, not 1.

**Comment by prusnak** [comment]
> If you must limit it, limit it to like 5 empty addresses, not 1.

BIP-44 says 1 account not 5 accounts.

**Comment by theronic** [comment]
> Software should prevent a creation of an account if a previous account does not have a transaction history (meaning none of its addresses have been used before).

Customers don't care about BIP-44. Is there a technical limitation in the BTC protocol? Does Ledger have this limitation? This is super annoying for merchants who want to accept btc and want to accept payments into separate addresses from distinct customers in short periods of time.

**Comment by prusnak** [comment]
You obviously do not understand the difference between an account and an address. Please go read BIP-44. If you still have trouble understanding how things work, contact our support.
