### ISSUE TITLE
DEX swaps are shown incorrectly in transaction history

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4552]
**Describe the bug**
Swap transaction of ETH to ERC20 token is displayed incorrectly.

**How to reproduce**
1. Swap ETH for ERC20 on Uniswap, 1inch,...
2. Check transaction history

**Current behavior**
I swapped ETH to UFI. Suite shows:

- `Sent UFI` instead of `Receive UFI` 
- Minus sign before UFI instead of plus sign.
- no ETH spent

**Expected behavior**
- How much ETH I spent
- Correct header and signs

**Screenshots**
![Screenshot 2021-11-24 at 16 47 40](https://user-images.githubusercontent.com/33235762/143272457-9d1ceded-ce64-463f-9597-ee6bbd9d3a36.png)
![Screenshot 2021-11-24 at 16 59 55 (1)](https://user-images.githubusercontent.com/33235762/143273991-ae0a1f4b-5b09-4c41-8d38-2a27ab230a96.png)

**Additional context**
Related to #4526

**Comment by STew790** [comment]
**QA OK**
via https://github.com/trezor/trezor-suite/pull/4551
