### ISSUE TITLE
Transaction daily summary is missing fees

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4557]
**Describe the bug**
The daily summary in tx history is missing fees.
Related to #4537.

**Info:**
 - Suite Version: 21.11.1

**How to reproduce**
1. Check tx history

**Expected behavior**
It should contain fees.

**Screenshots**
![Screenshot 2021-11-25 at 9 57 31](https://user-images.githubusercontent.com/33235762/143410860-553c3348-7581-4786-ab9f-ea28b6f29943.png)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 21.12.0 (f4f9dcf4e2fccf6cf6f1f9d823333c03d81e1eb1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
