### ISSUE TITLE
Transaction incorectly displayed in history

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4571]
**Describe the bug**
During latest firmware testing cycle I sent BTC and TBTC transactions that are displayed incorrectly in Suite transaction history. See screenshots. One transaction has double - and one transaction has change output displayed as another output.

transaction links
https://tbtc2.trezor.io/tx/a98472590145c557813407fe6b9e7bf9c31af34258e17e35e83b7dcaed05104b
https://btc2.trezor.io/tx/8cdfcbabec33e2e76e4217d41190a7e53f6e39d89ef5d63c122535b94093b1ec

xpubs were sent via [Slack](https://satoshilabs.slack.com/archives/CKZHV2G13/p1638180781042900?thread_ts=1637921492.040900&cid=CKZHV2G13)

**Steps to reproduce:**
**Info:**
 - Suite version: web 21.11.2 (e548c52e39f071f0d8d7d8a833bdbd7e2b6fee36)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Screenshots:**
![image (1)](https://user-images.githubusercontent.com/31506317/143855460-0847e2b0-10dd-47bb-80df-039f53065557.png)
![image (2)](https://user-images.githubusercontent.com/31506317/143855469-bb6576a0-bdf6-4a71-a9bf-6c9282d45e42.png)
![image](https://user-images.githubusercontent.com/31506317/143855473-125122ac-f7d6-4d80-b718-125a9fe8559b.png)

**Comment by szymonlesisz** [comment]
1) BTC are spent from different accounts (1J.., 13.. , bc1..) so from the suite point of view two utxos doesn't belong to this account. This is why calculation goes to negative number:
https://btc2.trezor.io/tx/8cdfcbabec33e2e76e4217d41190a7e53f6e39d89ef5d63c122535b94093b1ec

Trezor should warn you about spending from different path (or even fail if you have safety_checks enabled?)

2) TEST input is spent from bech32 account (tb1...) but change is added to segwit-legacy account (2Msi...)
so again, from the suite point of view this is different account:
https://tbtc2.trezor.io/tx/a98472590145c557813407fe6b9e7bf9c31af34258e17e35e83b7dcaed05104b

**Comment by bosomt** [comment]
Looks like problem with Mycellium app. Same with Test and BTC coins.
Transaction is sent as two separate outputs /you have to confirm 2 amounts and destination addresses/
but second change address is derived from destination account and not from origin account.

I already sent email to Mycellium /support@.... and info@... /
