### ISSUE TITLE
Can't use "enter" when doing T1 recovery on Android

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#4579]
**Describe the issue**

When you are doing a recovery on T1, there is no clear indication of how to confirm the word you enter. You can't click on enter on the keyboard, or rather it doesn't do anything. You need to click on the word that the drop-down menu shows you.
![image](https://user-images.githubusercontent.com/48477147/144033126-5957da43-5aa1-45e2-bf8f-36e472db2c91.png)

**How to reproduce**

1. Start a recovery with T1 on Android
2. When you get to writing and selecting a word, write part of the word and confirm it with "enter" on keyboard
3. The word won't get selected or confirmed

**Expected behavior**
The partially written word can be confirmed by "enter" on keyboard.

_Originally posted by @STew790 in https://github.com/trezor/trezor-suite/issues/4417#issuecomment-982516258_

**Comment by MiroslavProchazka** [comment]
Since it's quite an edge case and we are not planning to dive further into this topic in upcoming months I'm closing it for now.
