### ISSUE TITLE
Icon update - layout alignment

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4583]
JFYI it's not aligned correctly (please [see design](https://www.figma.com/file/pIibgxmxD0jrAa9UGJd9da/Neue-Desktop-1.5?node-id=8006%3A82460))

<img width="1164" alt="Screen Shot 2021-12-01 at 10 12 22" src="https://user-images.githubusercontent.com/29627086/144216211-9298c9ea-7a30-40e8-bfd8-34406fdf5093.png">

_Originally posted by @matejzak in https://github.com/trezor/trezor-suite/issues/4450#issuecomment-983492668_

**Comment by matejkriz** [comment]
will be fixed by https://github.com/trezor/trezor-suite/pull/4529/commits/60c264a89b9ea0027a349d2a044f722e5e6fe830

**Comment by jerechinsky** [comment]
Closing this issue as this will get resolved in the December release.
