### ISSUE TITLE
Storing NFTs support

### ISSUE THREAD

**Issue by trymeouteh** [trezor/trezor-suite#4618]
Please add support for storing NFTs into your Trezor wallet.

**Comment by mroz22** [comment]
Hi @trymeouteh, what do you exactly mean by "storing NFTs"? 
To be more specific - what kind of data should be stored and where exactly this data should be stored in your opinion?

**Comment by melroy89** [comment]
Let's fist start with which blockchain are we talking about? Nfts are supported once a blockchain supports smart contracts. So almost any smart contract platform can and does offer nft's.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.
