### ISSUE TITLE
Suite blocked a request to api.coingecko.com

### ISSUE THREAD

**Issue by uj** [trezor/trezor-suite#4624]
After the recent Suite update (21.12.2), it gives this popup error every time Suite is opened:

```
Suite blocked a request to api.coingecko.com.
If you believe this is an error, please contact our support.
```

Windows 10

This has been reported by multiple people: https://www.reddit.com/r/TREZOR/comments/rc4vnv/suite_blocked_a_request_to_coingecko_error/

**Comment by prusnak** [comment]
Thanks for the report!

The Suite Desktop contains a "firewall" which blocks requests to non-approved origins.

The only place where we contact the API is in the invity code here: https://github.com/satoshilabs/invity-api/blob/dd75d3e51e4e91557505b4bd9fde5ac0dcd4f9c2/src/exchangeRateService.ts#L35

The invity code should access the API via our proxy too: https://github.com/trezor/trezor-suite/blob/6c02edb1c53a6b97052e2bde1046255db160052e/packages/suite/src/services/coingecko.ts#L7

Report in the invity-api repo too: https://github.com/satoshilabs/invity-api/issues/78

**Comment by tsusanka** [comment]
That's right but the code is there [already 6 months](https://github.com/satoshilabs/invity-api/blame/dd75d3e51e4e91557505b4bd9fde5ac0dcd4f9c2/src/exchangeRateService.ts#L35). Something had to change? 🤔 

cc @martinboehm

**Comment by marekrjpolak** [comment]
@tsusanka yes, the request-filter itself had changed.

**Comment by martinboehm** [comment]
@prusnak The code you mention is in our API server, it has nothing to do with the Suite. It cannot cause this issue.

**Comment by prusnak** [comment]
> @prusnak The code you mention is in our API server, it has nothing to do with the Suite. It cannot cause this issue.

Ah, sorry. I thought the invity-api code is included in the Suite, but it seems only the types from `@types/invity-api` are included.

**Comment by tsusanka** [comment]
@uj in case you are still seeing this error please follow these [instructions](https://www.reddit.com/r/TREZOR/comments/rc4vnv/comment/hnzwp0p/?utm_source=share&utm_medium=web2x&context=3).

@matejkriz I think we should revert https://github.com/trezor/trezor-suite/pull/4625 as it was just an attempt for hotfix which we did not release. We can close after I believe.

**Comment by matejkriz** [comment]
agree, revert is here https://github.com/trezor/trezor-suite/pull/4639

**Comment by Bowersachs** [comment]
I'm on a Mac and the only way I was able to solve this issue was by completely removing the app and deleting the folder. Users/<user>/Library/Application Support/@trezor/suite-desktop. Just deleting the cashe didn't work for me like I was told.
