### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#463]
Improve notifications:

- [x] l10n is probably missing on some places,
- [ ] how should notifications behave when route changes? 
- [x] probably we should have a way how to decide which notification should be displayed in different context. For example we probably dont want to see transactions related notifications in password manager (but isnt this solved by clearing notifications after route change?

**Comment by slowbackspace** [comment]
just note to self: this should get fixed when Notification component starts supporting intl messages
https://github.com/trezor/trezor-suite/pull/442/files#diff-3bf178d4642c588dd9f239e217e0f5fdR103

edit: done 🎉
