### ISSUE TITLE
https://suite.trezor.io/web/ does not work on Tor Browser (Tails and macOS)

### ISSUE THREAD

**Issue by sunknudsen** [trezor/trezor-suite#4630]
**Describe the bug**

Going to https://suite.trezor.io/web/ on Tor Browser (Tails and macOS) does not work (see screenshots) even if one has installed Trezor Bridge and set `network.proxy.no_proxies_on` to `127.0.0.1:21325`.

**Info:**

 - Remembered Wallet: not applicable
 - Suite Version: latest
 - Browser: Tor Browser 11.0.2
 - OS: Tails 4.25, macOS Big Sur 11.6.1
 - Bridge: 2.0.27 on Tails and 2.0.31 on macOS
 - Firmware Version: not applicable

**How to reproduce**

1. Install [Trezor Bridge](https://suite.trezor.io/web/bridge/)
2. On Tails, run `sudo iptables -I OUTPUT 3 -o lo -s 127.0.0.1/32 -d 127.0.0.1/32 -p tcp --dport 21325 --syn -m owner --uid-owner amnesia -m conntrack --ctstate NEW -j ACCEPT` (not sure if this step is still required)
3. Open Tor Browswer
4. Go to `about:config` and set `network.proxy.no_proxies_on` to `127.0.0.1:21325`
5. Go to https://suite.trezor.io/web/

**Expected behavior**

One should see “Connect your Trezor”.

**Screenshots**

![Screen Shot 2021-12-09 at 3 34 59 PM](https://user-images.githubusercontent.com/2117655/145472152-16aecefd-95dc-484e-8ccf-b26c80e7ae8e.png)

![Screen Shot 2021-12-09 at 3 35 01 PM](https://user-images.githubusercontent.com/2117655/145472158-4c7b6fad-052e-4384-ac67-98ffec796358.png)

![Screen Shot 2021-12-09 at 3 35 03 PM](https://user-images.githubusercontent.com/2117655/145472163-b44653ce-aee9-4e24-8401-08f1fcff6373.png)

![Screen Shot 2021-12-09 at 3 43 09 PM](https://user-images.githubusercontent.com/2117655/145472714-ee8a7ae3-facd-417f-9529-7b331ac94749.png)

**Additional context**

I believe fixing this issue would likely also fix third party hardware wallet integrations on web-based wallets such as https://adalite.io/ which open https://connect.trezor.io/8/popup.html#loading and hang at “Loading…”.

**Comment by prusnak** [comment]
1. Is Javascript enabled for https://suite.trezor.io?

2. Just to confirm, the following address works for you (from https://wiki.trezor.io/Glossary:Tor) `http://suite.trezoriovpjcahpzkrewelclulmszwbqpzmzgub37gbcjlvluxtruqad.onion/` (providing you have also set `network.http.referer.hideOnionSource` to `false`)

**Comment by sunknudsen** [comment]
> Is Javascript enabled for https://suite.trezor.io?

Yes

> Just to confirm, the following address works for you (from https://wiki.trezor.io/Glossary:Tor) http://suite.trezoriovpjcahpzkrewelclulmszwbqpzmzgub37gbcjlvluxtruqad.onion/ (providing you have also set network.http.referer.hideOnionSource to false)

Interesting… it doesn’t.

On Tails:

![Screenshot from 2021-12-10 11-20-38](https://user-images.githubusercontent.com/2117655/145566695-2c551464-7a3b-44af-8bd1-80ebaa5bdb29.png)

On macOS:

![Screen Shot 2021-12-10 at 6 02 10 AM](https://user-images.githubusercontent.com/2117655/145564207-a2c23ead-58f6-4ce3-afb8-773d9ecbfdbe.png)

![Screen Shot 2021-12-10 at 6 04 33 AM](https://user-images.githubusercontent.com/2117655/145564331-cf43bbc9-ab86-4343-b395-366d7c0a085f.png)

Have you tried reproducing issue at your end on Tails and macOS (using “stock” Tor Browser with `about:config` patches and `iptables` patch on Tails)?

**Comment by prusnak** [comment]
@sunknudsen did you set `network.http.referer.hideOnionSource` to `false` before your tests?

**Comment by sunknudsen** [comment]
@prusnak yes, both on Tails and macOS.

**Comment by sunknudsen** [comment]
@prusnak Do you believe we can get the `https` version working as well?

This would significantly increase changes of getting https://connect.trezor.io/8/popup.html#loading to work right?

**Comment by prusnak** [comment]
I think I found the culprit : https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/26463

It seems that IndexedDB does not work in newer builds of Tor Browser :-(

**Comment by prusnak** [comment]
But maybe that IndexedDB warning is just a warning.

I can reproduce now with Tor Browser - will investigate further. Thank you for the report!

**Comment by sunknudsen** [comment]
Thanks for helping out @prusnak!

**Comment by anomaly07** [comment]
I have same problem on Ubuntu 20.04.3 LTS. Already tried several TOR versions (9.0.3, 9.5.4, 11.0.2, 11.5a1) nothing is working. Which version is working?

**Comment by sunknudsen** [comment]
Hey @anomaly07, have you considered using Linux (x86_64) AppImage release on Tails?

I recently published a guide on the topic (see https://sunknudsen.com/privacy-guides/how-to-install-and-use-trezor-suite-on-tails).

**Comment by prusnak** [comment]
It seems to me that everything works correctly, except for some rendering issue in Tor Browser which does not render the UI in the right half of the screen correctly which makes it impossible to enter the wallet.

I can see the elements are there when using Inspector, but they are not visible 🤔 

Still investigating ...

**Comment by bosomt** [comment]
**QA OK**

1) installed Tor browser
2) network.proxy.no_proxies_on to 127.0.0.1:21325
3) network.http.referer.hideOnionSource to false
4) discovery and sent transaction

<img width="1126" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/152367921-c0632f17-332d-4059-8a7a-fab7be7b1a4f.png">

Latest version of Tor and MacOS
Suite production version at suite.trezor.io 22.1.1

**Comment by bosomt** [comment]
@sunknudsen @prusnak 
can we close this issue ?

**Comment by prusnak** [comment]
Yes, let's close it. If the issue still persists, please reopen Sun.
