### ISSUE TITLE
Suite UI 1.5 - General updates vol. II

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4632]
**Design:** [Figma](https://www.figma.com/file/pIibgxmxD0jrAa9UGJd9da/Neue-Desktop-1.5?node-id=7617%3A77348)

- [x] Text input
- [x] Dropdown input
- [x] Dropdown menu
- [x] Segmented control
- [x] Modals
- [x] Navigation
- [x] Icons in settings and titles

- [x] Add Closing `X` on settings page
- [x] Remove 3 dots in settings
- [x] Unify corner radius in Dashboard news

**Notes:** [Notion](https://www.notion.so/satoshilabs/Suite-UI-1-5-II-bb775db7119b477ca549b3cab9b7af6b)

**Comment by matejkriz** [comment]
@hynek-jina most of this is already implemented, right? Is there anything important still missing?
