### ISSUE TITLE
EOSIO chains support

### ISSUE THREAD

**Issue by dafuga** [trezor/trezor-suite#4643]
Hey guys, not sure if this is the best place to ask this, but I was wondering if anyone here could give us some idea of the level of effort that would be required to add support for an EOSIO chain (https://eos.io/) on the trezor suite app?

Also, would some of the core devs be interested in maybe taking on such a task? If so, how much would a project like that cost us?

**Comment by prusnak** [comment]
We are currently not interested in adding coins that are not in the TOP 30 on Coinmarketcap. Should this situation change in the future we might reconsider.
