### ISSUE TITLE
Wallet.trezor.io deprecated banner

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4645]
Add banner to wallet.trezor.io pushing for Suite download.
- [x] implement square banner
- [x] change color from gold to red #D85644
- [x] _(optional)_ Remove blue `New` tag
- [x] Suite Landing Page banner 

**Design:** [Figma](https://www.figma.com/file/MmQtIPoIggyJkBm7vMUHpI/Neue-Desktop?node-id=0%3A1)
**Spec:** [Notion](https://www.notion.so/satoshilabs/Old-wallet-deprecation-Suite-e3ae0891f14d499f84e8fc1299a59ab6)
**Internal communication** [Slack](https://satoshilabs.slack.com/archives/C02HX8P52QJ/p1638980595040900?thread_ts=1638172276.008000&cid=C02HX8P52QJ)

**Comment by bosomt** [comment]
**QA OK**
