### ISSUE TITLE
Long string breaks pin entry modal

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#4646]
**Describe the bug**
If the `TR_THE_PIN_LAYOUT_IS_DISPLAYED` string exceeds 47 characters, it will break the pin entry layout. 

I fixed it in Russian by breaking the line with a `<br>` tag, but Spanish is still broken. 

**Info:**
 - Suite version: web 21.12.2 (8cedeed1d1da121ab6b3dff4cb6365b9030634a2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1080
 - Device: model 1 1.10.3 Bitcoin only

**How to reproduce**
1. Switch language to spanish
2. Connect model 1 with pin enabled
3. Observe

**Expected behavior**
Width of the modal should be restricted according to intended design in figma. Line should break instead of overflowing. 

**Screenshots**
![pin entry broken](https://user-images.githubusercontent.com/75733878/145988590-0e1aba13-4c53-4cd0-8332-e102ff1ac3c0.gif)

![Screenshot 2021-12-14 at 11 59 50](https://user-images.githubusercontent.com/75733878/145988939-0b0576c2-e7d8-4182-b9ca-656bc0f9caa8.png)

**Comment by bosomt** [comment]
**QA OK**

needs to be checked when Translation mode enabled and crowdin account active @alex-jerechinsky plz check if possible.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/31506317/166500749-7acd9d63-3359-47bb-8456-a1ecb7142f15.png">


**Info:**
 - Suite version: web 22.5.0 (2c03ec197653daaef34756a0b7fbc7fd39da1fa7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.9.2 regular (revision cde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea)
 - Transport: bridge 2.0.31
