### ISSUE TITLE
Dependencies (suite): react-redux, redux, redux-thunk, immer, @reduxjs/toolkit

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4651]
Update `react-redux`, `redux`, `redux-thunk`, `immer`, `@reduxjs/toolkit`

Issues:

- update of `redux` breaks `type-check`
- update `react-redux` breaks `type-check` https://redux.js.org/tutorials/typescript-quick-start
- `redux-thunk` has types patch file which probably has to be changed
- bug fix https://github.com/trezor/trezor-suite/pull/4711#issue-1098109503
- `immer` breaks `type-check`
- `@reduxjs/toolkit` breaks `type-check`

**Comment by matejkriz** [comment]
be aware of  react-redux change mentioned here: https://github.com/trezor/trezor-suite/pull/4711#issue-1098109503

**Comment by tomasklim** [comment]
removed from overview #7614
