### ISSUE TITLE
Promote desktop app in web app

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4656]
We inform users about the desktop app only on the landing page and on `Welcome page`. 

![Screenshot 2021-12-14 at 15 45 28](https://user-images.githubusercontent.com/33235762/146020563-4dbe88ed-0e39-440b-9c79-2b6c43549eaf.png)

**Idea:**
What about having it e.g. in settings dropdown or in settings itself.

![Screenshot 2021-12-14 at 15 35 50](https://user-images.githubusercontent.com/33235762/146018546-394a819e-f38a-43c6-b0a2-1137a91e43b8.png)

`Download Trezor Suite app` line could force some users to use desktop app.

**Comment by tomasklim** [comment]
There is no menu anymore. Maybe we can show desktop app features in web app disabled with tooltip to download desktop app?

**Comment by Hannsek** [comment]
How lengthy it would be?

**Comment by sime** [comment]
> we can show desktop app features in web app disabled with tooltip to download desktop app?

This is a nice contextual approach to promoting the desktop app!

Will consider this, as well as a dedicated CTA in suite.

**Comment by sime** [comment]
Closing in favour of #8234
