### ISSUE TITLE
messages.ts bugs & improvements

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#4658]
Please refer to https://github.com/trezor/trezor-suite/blob/develop/docs/misc/localization.md to get familiarised with translations in Trezor Suite.

- [ ] **1.** The `TR_ENTER_PIN` message is currently used both in the heading of the pin entry modal and the _confirm_ button. The English copy `Enter PIN` fits both the heading and the confirm button, but Russian language is not so accommodating. **Can we please create an extra message (i.e. `TR_ENTER_PIN_CONFIRM`) for the confirm button?** 

<details>
  <summary>gif</summary>

![Screenshot](https://user-images.githubusercontent.com/75733878/146034810-96eecea7-7860-4497-a9b0-02109de0d0f4.gif)
</details>

- [ ] **2.** Add support for plural, singular forms in messages `TR_ACTIVE`. It's displayed in the onboarding step where you activate coins. This is how it has been done in `TR_N_TRANSACTIONS`: https://github.com/trezor/trezor-suite/blob/c724a26802def8f620866bcb994b56a9da4e37e3/packages/suite/src/support/messages.ts#L3776-L3778

<details>
  <summary>screenshot</summary>

![Screenshot 2021-12-16 at 12 37 13](https://user-images.githubusercontent.com/75733878/146365886-9f1a79bc-44aa-4396-89c0-24f34d0f8d1d.png)

</details>

**Info:**
 - Suite version: web 21.12.2 (8cedeed1d1da121ab6b3dff4cb6365b9030634a2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1080
 - Device: model 1 1.10.3 Bitcoin only

**Comment by alex-jerechinsky** [comment]
**5.** `LOG_DESCRIPTION` translation is not showing. 
https://staging-suite.trezor.io/web/settings
![Screenshot 2022-01-12 at 13 38 29](https://user-images.githubusercontent.com/75733878/149142000-9dbe1601-c860-4a5c-a3d6-f3b7649301c5.png)

**Comment by hynek-jina** [comment]
@alex-jerechinsky Is this issue still relevant?

**Comment by jerechinsky** [comment]
Yes. 3/5 points were fixed, so I removed them. The 2 that remain still need addressing.

**Comment by AdamSchinzel** [comment]
1. What should be the value for the translation then? Feel free to suggest something better here - https://crowdin.com/translate/trezor-suite/103/en-ru. Would be awesome to have something that fits both places so we don't have to change code.

2. I think not relevant anymore since it's not displayed there. Actually `TR_ACTIVE` is displayed now only in tooltip in custom backend status but it's doesn't have to be there since status is on hover replaced by clean input icon.

**Comment by hynek-jina** [comment]
@AdamSchinzel So can we close the issue?

**Comment by AdamSchinzel** [comment]
Yes 👍
