### ISSUE TITLE
Install Bitcoin-only firmware directly in Suite

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4661]
Currently you have to manually upload a file from GitHub. It feels like a non-recommended option. 

**Terminology**
`Universal` - Regular firmware
`Bitcoin-only` - Bitcoin only firmware

### 1. Onboarding
At first part of onboarding include option to switch on Bitcoin firmware.
![Screenshot 2022-08-02 at 14 25 44](https://user-images.githubusercontent.com/42465546/182387964-cdaa9e33-fb3c-4bd8-ac45-328ec67463f5.png)
After clicking on Bitcoin-only, show confirmation window:
![Screenshot 2022-08-02 at 14 25 51](https://user-images.githubusercontent.com/42465546/182388089-1b4be889-9afe-4719-a786-0a6b6052e386.png)
Upon confirmation, install:
![Screenshot 2022-08-02 at 14 26 02](https://user-images.githubusercontent.com/42465546/182388447-b033b724-acf7-4547-85a1-966320c09365.png)

### 2. Device settings
1. Device settings - add Firmware type section bellow Firmware version section and separate them into a new Firmware category:
![Screenshot 2022-08-02 at 14 27 58](https://user-images.githubusercontent.com/42465546/182388489-467aae74-1614-4971-afa0-8e675b1d7513.png)
2. Show modal after clicking the button
![Screenshot 2022-08-02 at 14 28 25](https://user-images.githubusercontent.com/42465546/182389013-7688afc9-441c-4c9b-95aa-2689b1d61ab0.png)

3. Check if you have a seed (no change)
4. Navigate user to access bootloader (no change)
5. Finally install new firmware
![Screenshot 2022-08-02 at 14 28 53](https://user-images.githubusercontent.com/42465546/182389149-910d3175-4d38-4112-b8f1-9d52ef03ca20.png)

### 3. Crypto settings
Show message offering Universal firmware when Bitcoin-only is installed:
![Screenshot 2022-08-02 at 14 27 38](https://user-images.githubusercontent.com/42465546/182389419-5d21eea8-5d32-457c-9028-34dd776df2d6.png)
Show message offering Bitcoin-only firmware when Universal is installed but only Bitcoin is used:
![Screenshot 2022-08-02 at 14 29 35](https://user-images.githubusercontent.com/42465546/182389570-7dc5128c-296a-44c3-905b-6a05e15ef0e3.png)
    
Few more notes in [specification](https://www.notion.so/satoshilabs/Bitcoin-only-FW-in-Suite-a8a83edcfbc74a6ba70dccedd511f8bf).

**Comment by hynek-jina** [comment]
I’m closing this issue for now until the product is specified.
[Current private specification](https://www.notion.so/satoshilabs/Bitcoin-only-FW-in-Suite-a8a83edcfbc74a6ba70dccedd511f8bf)

**Comment by sime** [comment]
I caution the need for promoting BTC only firmware. Instead, I'd prefer to [make the call](https://basecamp.com/gettingreal/06.4-avoid-preferences#make-the-call) and stick to the 'universal' firmware.

Nonetheless, BTC only firmware users need to be guided back to the universal firmware when stuck. e.g. Attempting to add an altcoin politely informs the user that more coins are available via the universal firmware.

**Comment by komret** [comment]
![chrome-capture-2022-6-19 (1)](https://user-images.githubusercontent.com/42465546/179765152-509c1944-70be-4f0d-82f7-48ea78504a77.gif)
Now that we can expect more people using the Bitcoin-only firmware, should we also enhance some behaviour for crypto selection?
1. The "Enable more coins" in Dashboard leads to Crypto settings where the user can only enable Bitcoin Testnet, which is not very useful - we could either hide the button or redirect to firmware type settings.
2. The tooltip in Crypto settings says "Not supported", which is a bit misleading - we could say something like "Not supported with Bitcoin-only firmware"

**Comment by sime** [comment]
> * The "Enable more coins" in Dashboard leads to Crypto settings where the user can only enable Bitcoin Testnet, which is not very useful - we could either hide the button or redirect to firmware type settings.
> 
> * The tooltip in Crypto settings says "Not supported", which is a bit misleading - we could say something like "Not supported with Bitcoin-only firmware"

The messaging could be a more direct, i.e. 'Switch to universal firmware to access this coin' etc.

Additionally, a banner informing the user that this page is essentially useless on Bitcoin only firmware, and why.

**Comment by hynek-jina** [comment]
@komret 
You are right.. These improvements were planed for future improvements.
However if it is not too complicated I would add message in coin section next to number of active coins

Having `Bitcoin` firmware
- *For more coins install `universal` firmware* 
→ With anchor link to firmware type switch

Having `universal` firmware and only Bitcoin selected
- *If you only require Bitcoin wallet operations, you can install the dedicated `Bitcoin` firmware* 
→ With anchor link to firmware type switch

**Comment by komret** [comment]
**QA:** I updated the issue. Please test the screens I pasted there. The firmware switch should also be tested with a pre-intermediary device (It should work, but I have not tested that.)

**Comment by bosomt** [comment]
Is that expected ?
I would expect to button say `Switch to Bitcoin only` or `Switch to Bitcoin-only`

<img width="788" alt="image" src="https://user-images.githubusercontent.com/31506317/182546319-366bc338-5960-4b1d-b124-1da2ba66dec0.png">

**Info:**
 - Suite version: web 22.8.0 (2e2d8109d9a946eb61f43b39acd48b21885fbd19)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by komret** [comment]
> Is that expected ? I would expect to button say `Switch to Bitcoin only` or `Switch to Bitcoin-only`

@bosomt This is the only exception to the naming - "Bitcoin-only" would make the button longer than other buttons on the page.

**Comment by bosomt** [comment]
**QA OK**

tested: 
1.11.1 universal > 1.11.1 btc only
1.11.1 btc only > 1.11.1 universal
1.11..1 btc only > 1.11.1 universal
Universal 1.10.3 > Bitcoin-only 1.11.1
OFFLINE onboarding to Bitcoin-only 1.11.1

Universal 2.4.3 > Bitcoin-only 2.5.1
Bitcoin-only 2.5.1 > Universal 2.5.1
Universal 2.5.1 > Universal 2.5.1
Universal 2.0.8 > Universal 2.5.1
Universal 2.0.5 > Bitcoin-only 2.1.1 **Installation failed, no BTC FW before 9/2019**
Universal 2.1.1 > Bitcoin-only 2.5.1
OFFLINE onboarding to Bitcoin-only 2.5.1 

i will update comment for more results during Suite/FW testing

**Info:**
 - Suite version: desktop 22.8.1 (503b472935dec8a9c07aac5eef5ba43f86780a38)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA NOK**

I know it's really old FW but we found out last month that people are still using FW thats 4 years old.
So maybe we should hide this feature for old FW ? Maybe for model T1 as well ?

According to https://wiki.trezor.io/Bitcoin_firmware
`When loading the Bitcoin firmware on your [Trezor Model T](https://wiki.trezor.io/Trezor_Model_T), you must have firmware version 2.1.0 or newer installed on your device first.`

`Universal 2.0.5 > Bitcoin-only 2.1.1`
Installation failed
Error: Failed to download firmware binary

<img width="663" alt="Screenshot 2022-08-03 at 13 04 27" src="https://user-images.githubusercontent.com/31506317/182593276-fb42f50f-426a-403c-8c67-94dca09f0c5d.png">

**Comment by komret** [comment]
@sime , could you please confirm whether the grey Github links have a correct target URL?

I can see three issues, but maybe some of it is inteded:
1. Both buttons lead to the same URL (this is new, I could not find a better target)
2. As @STew790 pointed out, it leads to a [commit](https://github.com/trezor/trezor-firmware/commit/85a26d2c9593bcdf858c2d718d79951ca927a0c3), but it might be more helpful to lead to [changelog](https://github.com/trezor/trezor-firmware/blob/85a26d2c9593bcdf858c2d718d79951ca927a0c3/core/CHANGELOG.md).
3. It is the same URL for both T1 and TT - is there only one changelog?

![Screenshot 2022-08-03 at 14 39 55](https://user-images.githubusercontent.com/42465546/182610181-3794c289-7e97-4f0a-a757-22c274ccb542.png)

**Comment by sime** [comment]
GH Firmware links should lead to the commit of CHANGELOG.md as mentioned in a separate issue: https://github.com/trezor/trezor-suite/issues/4665#issuecomment-1197864842 (cc: @bosomt).

v1 CHANGELOG path: `<commit>/legacy/firmware/CHANGELOG.md`
v2 CHANGELOG path: `<commit>/core/CHANGELOG.md`

Remove the firmware link for Universal/Bitcoin as it adds no value. Instead, we should offer context in the future about what the current type of firmware represents/offers.

**Comment by komret** [comment]
Ok, sounds good, I am changing the links and disabling the second button - it will point to Knowledge base or Guide in the near future.

![chrome-capture-2022-7-3](https://user-images.githubusercontent.com/42465546/182638211-23f4760d-dd17-4622-91a2-7b088dd6768d.gif)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.8.2 (58f4c5bf0804e02c05c0b85e020b6e452b419164)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.2 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31
