### ISSUE TITLE
Device firmware changelog linked to Github not to blogpost

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4665]
**Describe the bug**
See this issue https://github.com/trezor/trezor-suite/issues/4161 that was created to change behavior of linking changelog of device firmware/update from Github to Blogpost if available. 
Is it possible that this change was not yet merged/release ?

Last tow FW revisions:

    revision: 20 bytes 0x9276b1702361f70e094286e2f89e919d8a230d5c,
    revision: 20 bytes 0x595b14254c1abb2be3f69e42c7932f1eca8cf1b1,

**Info:**
 - Suite version: desktop 21.12.2 (8cedeed1d1da121ab6b3dff4cb6365b9030634a2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.12.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Expected result:**
2.4.3: https://blog.trezor.io/trezor-suite-and-firmware-updates-december-2021-d1e74c3ea283
2.4.2: https://blog.trezor.io/trezor-suite-and-firmware-updates-september-2021-a490f2ea16c1

**Actual result:**
2.4.3: https://github.com/trezor/trezor-firmware/commit/595b14254c1abb2be3f69e42c7932f1eca8cf1b1
2.4.2: https://github.com/trezor/trezor-firmware/commit/9276b1702361f70e094286e2f89e919d8a230d5c

**Screenshot**
<img width="424" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/146216186-02a53006-b272-43e0-adc2-dddc8cc1d8a9.png">

**Comment by bosomt** [comment]
**QA NOK**


actual status/links

T1 https://github.com/trezor/trezor-firmware/commit/3f12742669bd782cac374a1750d517f4fd88c43b
TT https://github.com/trezor/trezor-firmware/commit/595b14254c1abb2be3f69e42c7932f1eca8cf1b1

expected status/links

T1 https://blog.trezor.io/trezor-suite-and-trezor-model-one-firmware-updates-january-2022-4a77e4a07a5a
TT https://blog.trezor.io/trezor-suite-and-firmware-updates-december-2021-d1e74c3ea283

**Comment by prusnak** [comment]
This is the commit https://github.com/trezor/trezor-suite/commit/7618ef045a9eea8d163bfed94c4b7bf4b5ef8050 that has been merged via https://github.com/trezor/trezor-suite/pull/4201 to fix https://github.com/trezor/trezor-suite/issues/4161

**Comment by bosomt** [comment]
Current Trezor Suite link for 2.5.1 FW: https://github.com/trezor/trezor-firmware/commit/85a26d2c9593bcdf858c2d718d79951ca927a0c3

Do we plan to change it or is this expected and i can close this issue ?

I would expect one of these links and not last commit.
https://blog.trezor.io/trezor-suite-and-firmware-updates-may-2022-b1af60742291
https://github.com/trezor/trezor-firmware/blob/master/core/CHANGELOG.md

**Comment by sime** [comment]
> I would expect one of these links and not last commit.
> https://blog.trezor.io/trezor-suite-and-firmware-updates-may-2022-b1af60742291
> https://github.com/trezor/trezor-firmware/blob/master/core/CHANGELOG.md

I prefer the second link, but based on the commit. i.e replacing `master` with the commit hash.

https://github.com/trezor/trezor-firmware/blob/85a26d2c9593bcdf858c2d718d79951ca927a0c3/core/CHANGELOG.md

**Comment by matejkriz** [comment]
> I prefer the second link, but based on the commit. i.e replacing `master` with the commit hash.
> 
> https://github.com/trezor/trezor-firmware/blob/85a26d2c9593bcdf858c2d718d79951ca927a0c3/core/CHANGELOG.md

@sime 
I think that using the commit instead of `master` is much worse in this case. 

If use has an older FW and we lead him to corresponding commit, user can't see the changelog for newer firmwares and only benefit is that he doesn't have to scroll down to his version (but why would he even do that? Isn't it more interesting to see the changes in newer versions?)

compare:

link for users with FW 1.10.3 by commit:
https://github.com/trezor/trezor-firmware/blob/9276b1702361f70e094286e2f89e919d8a230d5c/legacy/firmware/CHANGELOG.md

universal link for latest changelog in master (my suggestion):
https://github.com/trezor/trezor-firmware/blob/master/legacy/firmware/CHANGELOG.md

**Comment by prusnak** [comment]
> universal link for latest changelog in master (my suggestion):
> 
> https://github.com/trezor/trezor-firmware/blob/master/legacy/firmware/CHANGELOG.md

Can we somehow add an anchor link to the markdown?

If yes then we could link to https://github.com/trezor/trezor-firmware/blob/master/legacy/firmware/CHANGELOG.md#1.10.3 and get best of both worlds.

**Comment by komret** [comment]
@prusnak Yes, but actually no because the full anchor link is more complex (https://github.com/trezor/trezor-firmware/blob/master/legacy/firmware/CHANGELOG.md#1103-16th-september-2021) and we cannot determine the release date in Suite.

**Comment by matejkriz** [comment]
Why would one care about a changelog from an old and already installed version? 

The link to the commit made sense, at least for those who want to read the code. Changelog for the newer version could be useful too. But why changelog for already installed version?

**Comment by sime** [comment]
To follow up the discussion in standup, will stick to commit version of the CHANGELOG.md.

> Why would one care about a changelog from an old and already installed version?

It's contextual, I click on 1.11.1 so I land on Changelog about 1.11.1

**Comment by matejkriz** [comment]
Okay, I've been outvoted by @sime 😃 let's leave it with the commits in the links.

**Comment by STew790** [comment]
**QA OK**
I tried the newest FW for TT and T1 and also a random older FW for both devices and I got the correct changelog.

2.4.3
![image](https://user-images.githubusercontent.com/48477147/183093992-08833918-ff76-474f-996c-4faf3b607d24.png)
2.5.1
![image](https://user-images.githubusercontent.com/48477147/183094540-b38a5501-82c1-4010-b25f-206cfd19e5b0.png)
1.10.1
![image](https://user-images.githubusercontent.com/48477147/183099043-906fbe86-de47-4caa-aa38-0cf4deabe9fb.png)
1.11.1
![image](https://user-images.githubusercontent.com/48477147/183099594-76518eba-480c-4abe-81ac-0760761377f8.png)
