### ISSUE TITLE
Trezor news posts underlined when hover over them

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4668]
**Describe the bug**
When you hover over Blog posts in Dasboard/Trezor  section they are underlined.
I'm not sure if it's design change or bug.

**Steps to reproduce:**
1. Go to Dasboard/Trezor news section
2. Move cursor over blog posts
3. compare with production version of Suite

**Info:**
 - Suite version: web 22.1.0 (c724a26802def8f620866bcb994b56a9da4e37e3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Screenshots:**

dev master vs production 

<img width="348" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/146323005-64098983-0ea2-45ef-a3b4-bdd69a7ab344.png">

<img width="352" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/146323056-37167fea-34d3-4b0b-ad78-d4a72bdcf27d.png">

**Comment by hynek-jina** [comment]
@matejzak is that the intention? thx...

**Comment by glacierbits** [comment]
I believe it's a bug. Haven't seen that happening before. Moving to `Bug` column.

**Comment by bosomt** [comment]
**QA OK**
already fixed and it looks as expected now

**Info:**
 - Suite version: desktop 22.1.0 (95a1a9e112a94666fe6bd787d4b8eed0f54547cf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.1.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Info:**
 - Suite version: web 22.1.0 (6865dca93348d1e5154124fe9ceec8b5c124da71)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.5 regular
