### ISSUE TITLE
ADA - Exporting Public Key Failed

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4669]
**Describe the bug**
Unable to move ADA to other wallets due to "Exporting Public Key Failed".
_Been like this for at least 8 hours._

**Info:**
 - Suite Version: desktop 21.12.2
 - OS: macOs
 - Firmware Version: regular 2.4.3
- Window dimension: 1375x937

_Received from [Notion](https://www.notion.so/satoshilabs/Unable-to-move-ADA-to-other-wallets-due-to-Exporting-Public-Key-Failed-Been-like-this-for-at-least-f31d5e52aa804ee188fb9e43a2c0824e)_

**Comment by hynek-jina** [comment]
Another occurance:

_Hello!  I recently restored a 24 word seed phrase, generated by a Trezor One, with my new Trezor Model T.  I have a passphrase enabled. I am trying to sync the Model T with the Daedalus (full node) wallet so that I can take custody of Cardano.  Daedalus is saying that it cannot export the public key from the Trezor.  Is it possible that using a seed generated on the Trezor One renders the Trezor Model T incompatible with ADA/Cardano assets?  Please advise.  Thank you!_

**Info:**
- Suite Version: desktop 21.12.2
- OS: Windows
- Firmware Version: regular 2.4.3
- Window dimension: 1214x663

**Comment by mroz22** [comment]
Possibly related read https://github.com/trezor/trezor-firmware/blob/949dfe1f5d56c4aa8269b51eb5c7fc188f43176e/core/src/apps/cardano/README.md#seed-derivation-schemes

**Comment by EtherDotBlue** [comment]
Same Trezor issue on Daedalus v4.6.0 #20052

**Comment by prusnak** [comment]
@EtherDotBlue Please report this issue to Daedalus wallet, so they can fix it. They are providing the non-ideal change address which triggers this warning. Link the issue you created in their issue tracker here, please.

**Comment by EtherDotBlue** [comment]
Fixed on Daedalus by rolling back the Trezor firmware to v 2.42.  Instructions:  https://wiki.trezor.io/Firmware_downgrade

**Comment by prusnak** [comment]
For reference: Yoroi issue is already opened here: https://github.com/Emurgo/yoroi-frontend/issues/2575

**Comment by EtherDotBlue** [comment]
@prusnak I think that is a different issue.  This was just about exporting the public key and I solved it by downgrading the firmware to the previous version.

**Comment by prusnak** [comment]
> I solved it by downgrading the firmware to the previous version.

Firmware downgrade is not a solution. It is a workaround.

I reported the issue for Daedalus here: https://github.com/input-output-hk/daedalus/issues/2798

**Comment by prusnak** [comment]
This is a known issue - Daedalus is using the old version of Trezor Connect and they are going to upgrade it - see issue https://github.com/input-output-hk/daedalus/pull/2726
