### ISSUE TITLE
Suite asks you to enable passphrase when you cancel unlock device dialogue

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4670]
**Describe the bug**
Now i'm finally able to reproduce this issue that occurred some time ago 
Suite asks you to enable passphrase when you cancel unlock device dialogue.
Or see screenshot of verify receive address dialogue, there is Enable passphrase notification beofre i unlock or cancle PIN dialogue on device.

**Steps to reproduce:**
1. Lock device
2. Try to perform Sign and verify
3. Cancel unlock dialogue
4. Observe suite behavior

**Info:**
 - Suite version: web 22.1.0 (d24aba06481123518484f0dbb728e7eca02e5c27)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Screenshots:**

https://user-images.githubusercontent.com/31506317/146365614-1a33abee-0e9c-4cc2-a174-9e26900cbfd6.mov

<img width="885" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/146366301-86e030aa-e2bf-4b4e-8677-027ce9a9c420.png">

**Comment by bosomt** [comment]
**QA NOK**

no change in current version

<img width="1052" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/156721733-40d15d44-d71c-429b-8d0f-4e07b859d753.png">

**Info:**
 - Suite version: desktop 22.3.1 (538d147496ee9e5a03c2a8e3754b3532ddedaf6d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Comment by STew790** [comment]
**QA NOK**
Still present in current Suite.

**Info:**
 - Suite version: desktop 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA OK**



**Info:**
 - Suite version: desktop 23.7.0 (8ac7640945b9976da035139932fd2932a809c7be)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.7.0 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
