### ISSUE TITLE
Firmware update flow - Redundant update from the latest to latest firmware offered

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#4671]
**Describe the bug**
Update from the latest to the latest firmware is offered immediately after completing a meaningful update flow (from older to latest). 

**Info:**
 - Remembered Wallet: no
 - Suite Version: 21.12.2 8cedeed1d1da121ab6b3dff4cb6365b9030634a2
 - Browser: Chromium 96.0.4664.110
 - OS: Ubuntu 21.10
 - Bridge: N/A
 - Firmware Version: model T 2.4.2 -> 2.4.3

**Steps to reproduce the behavior:**
Prerequisite - device with firmware older than latest.
1. Initiate update,
2. Complete the update flow,
3. Observe.

**Actual behavior:**
Update modal offering update from the latest 2.4.3 firmware to the same is offered immediately after completing the legit/meaningful update flow.

**Expected behavior**
Either Wallet select modal or previously displayed wallet is displayed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10185314/146393730-a4435c41-4561-4e65-8293-111d44ac32c6.png)

**Additional context**
First visit of web suite in the browser.

**Comment by bosomt** [comment]
**QA NOK**

i was able to reproduce issue when i reinstalled current public firmware

<img width="645" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/149540191-a72c5bef-5a9e-4941-8ab1-80da9f09fe3d.png">

**Info:**
 - Suite version: web 22.1.0 (cd10a81f8e60de899eb77dc58c552ac8668ee0c5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Comment by dahaca** [comment]
@bosomt Was not able to duplicate after many tries
 

- **OS:** Mac M1
- **Browser:**  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
- **Suite version:** web + desktop 22.1.1 and current dev (https://github.com/trezor/trezor-suite/commit/440edca2fd6933553a0630c4688bf63cd18093c6)
- **Device:** Model T `2.4.2 to 2.4.3` and `2.4.3 to 2.5.0`


Also cleaned cookies in web to simulate:

> **Additional context**
> First visit of web suite in the browser.

**Comment by bosomt** [comment]
@dahaca i will try to replicate it in upcoming days 💪🏿

**Comment by bosomt** [comment]
**QA OK**

i was not able to reproduce issue with 10+ tries /app+web, upgrade, reinstall/


**Info:**
 - Suite version: web 22.4.3 (969161f41dcd889fa1fb0cf5e1d3437fddd8c26d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: 2.4.3 + 2.4.2
