### ISSUE TITLE
Option to express the fee in total value

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4673]
Currently you can select transaction fee only in relative terms (sats/vB)
1 sat/vB is currently quite often accepted and it could help to distinguish small fee increment - not directly to 2 sat/vB.

_For example - size of you transaction is ~166 vB and you could set fee to 200 sats._

**Comment by prusnak** [comment]
What is the usecase for this?

**Comment by hynek-jina** [comment]
When you want to get ahead of other transactions but not overpay on fees.

**Comment by prusnak** [comment]
> When you want to get ahead of other transactions but not overpay on fees.

How does that work? Pools pick transactions by sats/vbyte not by absolute value of the fee, block explorers show sats/vbyte stats for mempool, etc.

**Comment by hynek-jina** [comment]
Sure, but you cannot set 1,5 sats/vB in Trezor → which would help you to overcome transactions with 1 sats/vB fees and not overpay to 2 sats/vB. (So the decimal number would solve that as well)

And I thought that expressing the fee in absolute value would be more intuitive that playing around with decimals.

**Comment by prusnak** [comment]
> Sure, but you cannot set 1,5 sats/vB in Trezo

Thanks for confirming my suspicion that the real issue might be, in fact, not being able to enter decimal numbers as fee.

> And I thought that expressing the fee in absolute value would be more intuitive that playing around with decimals.

We'll discuss this within the product meeting.

Thanks!

**Comment by tsusanka** [comment]
Related: https://github.com/trezor/trezor-suite/issues/3252.

**Comment by hynek-jina** [comment]
https://github.com/trezor/trezor-suite/issues/3252 is sufficient solution
