### ISSUE TITLE
App icon missing on Linux in latest Suite versions

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4680]
**Describe the bug**

App icon missing on Linux in latest Suite versions. See attached screenshots.

21.10.2 **QA OK**
21.12.2 + dev master **QA NOK**

**Steps to reproduce:**
1. Start Suite Linux version from October
2. Start latest Linux version of Suite
3. Compare taskbar icons

**Info:**
 - Suite version: desktop 21.12.2 (8cedeed1d1da121ab6b3dff4cb6365b9030634a2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.12.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1536x864
 - Device: model T 2.4.3 regular

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/146897661-bf2d329e-0607-44dc-af0e-5edf2e1a890b.png)

![image](https://user-images.githubusercontent.com/31506317/146898148-8792ac7f-289d-46d9-9900-7e0b709373a8.png)

**Comment by bosomt** [comment]
**QA NOK**

icon is still missing in dev master and on production

**Info:**
 - Suite version: desktop 22.1.0 (b0defd67595dd9e4fb782549539bedc21edda38b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.1.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1536x864
 - Device: model 1 1.10.5 regular

**Comment by mroz22** [comment]
This appeared with this commit for the first time https://github.com/trezor/trezor-suite/commit/fbd87b0c4ae55c06c8782b850bcc5a0802afa335

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.1.0 (4bc9b932487181d8ef32fefa74f231a48cbebbad)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.1.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1536x864
 - Device: model 1 1.10.3 regular
