### ISSUE TITLE
Flatpak: Suite Web cannot find device when once paired, disconected and connected (chromium browser) (webusb)

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#4681]
**Describe the bug**
When using suite with the paired device using webusb in [Chromium browser](https://www.chromium.org/) then disconnect and connect the device back, the suite web app gets stuck in infinite loading.
This bug is only reproducible in [Chromium browser](https://www.chromium.org/) but not in Google chrome.

**Info:**
 - Remembered Wallet: yes/no
 - Suite Version: web, 11f6429fee5b976d9448e2d5cace789f87d4f8c8
 - Browser: Chromium, Version 95.0.4638.69 (Official Build) (64-bit)
 - OS: Pop!_OS 21.04
 - Bridge: only webusb
 - Firmware Version: model T, 2.4.2. 

**How to reproduce**
1. Go to [trezor suite web](https://suite.trezor.io/web/) using Chromium browser
2. Pair the device and go to `Dashboard`
3. disconnect and connect the device into your computer
4. Reload the page
5. There is a spin loader that never ends

**Expected behavior**
The device should be paired again or at least ask the user if she wants to re-pair it

**Additional context**
It is very likely it is a bug in Chromium Browser since this issue is not reproducible in Google Chrome.

**Comment by prusnak** [comment]
> This bug is only reproducible in [Chromium browser](https://www.chromium.org/) but not in Google chrome.

Where did you get the Chromium build from? Is that the official Chromium build or a package from your Linux distribution?

**Comment by bosomt** [comment]
i was not able to reproduce issue
edit: same for dev master 

**Info:**
 - Suite version: web 21.12.2 (8cedeed1d1da121ab6b3dff4cb6365b9030634a2)
 - Suite version: web 22.1.0 (11f6429fee5b976d9448e2d5cace789f87d4f8c8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Comment by karliatto** [comment]
> > This bug is only reproducible in [Chromium browser](https://www.chromium.org/) but not in Google chrome.
> 
> Where did you get the Chromium build from? Is that the official Chromium build or a package from your Linux distribution?

I got the Chromium build from my Linux distribution Pop!_OS in flatpak

**Comment by prusnak** [comment]
My hunch tells me that the Flatpak sandboxing is somehow getting in the way.  :-/

Try reproducing with version of Chromium that does not come from Flatpak and see if this helps. If it does, I am afraid we'll have to close this and report the issue here instead:  https://github.com/flathub/org.chromium.Chromium

**Comment by karliatto** [comment]
> My hunch tells me that the Flatpak sandboxing is somehow getting in the way. :-/
> 
> Try reproducing with version of Chromium that does not come from Flatpak and see if this helps. If it does, I am afraid we'll have to close this and report the issue here instead: https://github.com/flathub/org.chromium.Chromium

I just tried it with latest version of Chromium from snap and webusb does not find any device, it opens the message window to select the device but it says: "No compatible devices found". When at the same time the Flatpak Chromium finds the device successfully.

**Comment by prusnak** [comment]
> Chromium from snap

I don't think that Snap supports access to USB devices (except for media storage) by default.

At this point were are just chasing quirks in Flatpak/Snap sandboxing environments.

**Comment by karliatto** [comment]
Closing this issue since there is no much we can do with Chromium quirks in Flatpak/Snap sandboxing environments.
