### ISSUE TITLE
Remove system popup informing about unknown host from request filter

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4684]
- [ ] Stop following HTTP redirects (needs investigation)
- [x] Start reporting to Sentry all attempts to fetch domains that are not whitelisted
- [x] Remove confusing and ugly system popup warning for blocked domains
- [x] ~~Give the user the option to allow fetch on domain that is not whitelisted (needed for AOPP?)~~

**Comment by matejkriz** [comment]
the last point `Give the user the option to allow fetch on domain that is not whitelisted (needed for AOPP?)` is done in https://github.com/trezor/trezor-suite/issues/4512

**Comment by matejkriz** [comment]
System popup warning for blocked domains has been removed and instead it's reported to Sentry.

**Comment by STew790** [comment]
**QA OK**

No warning appeared in Suite, only error in console and a report to sentry.

![image](https://user-images.githubusercontent.com/48477147/155745189-0d5606a4-782a-4aac-9a5e-47d5447b087c.png)

https://sentry.io/share/issue/4fbbb8adc14f424288445f707479aee3/

**Info:**
 - Suite version: desktop 22.3.0 (3041e4c87aaf67c229ae26be663fba0070500c4c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular
