### ISSUE TITLE
Issues with EOS AND bloks 

### ISSUE THREAD

**Issue by d1gitaldash** [trezor/trezor-suite#4686]
I’m not able to access my EOS on my trezor at bloks…it does nothing when I type in the indexes to use (0,1,2,3,4). Why was eosauthority removed? Unlike bloks, it actually worked…now I have thousands in limbo because of this bug. There are others who are having the exact same issue as me, please advise.

**Comment by hynek-jina** [comment]
@d1gitaldash 
Hi, could you please contact directly [support](https://trezor.io/support/) or via mail help@trezor.io?

**Comment by hynek-jina** [comment]
This might help:
https://docs.bloks.io/login/desktop-wallets/trezor

**Comment by d1gitaldash** [comment]
Thanks but I’ve tried that tutorial and have tried contacting support. nobody seems to know anything about it…it won’t let you see your wallet after typing in the indexes and attempting to connect to the trezor.

**Comment by prusnak** [comment]
@d1gitaldash Please contact Bloks support. Their wallet is closed source, so if there is something wrong in their wallet, it's them who have to fix it.

With regards to EOSAuthority - ask them why they have removed Trezor support.

**Comment by d1gitaldash** [comment]
Will do, thanks
