### ISSUE TITLE
Latest dev version Suite app is draining laptop battery

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4687]
**Describe the bug**
I was able to reproduce issue on macOS and Windows 10.
Even when idle and no device connected app keeps one of CPU cores at 100% and laptop battery is drained really soon.

**Steps to reproduce:**
1. Start Suite 22.1.0
2. Observe CPU and battery status

**Info:**
 - Suite version: desktop 22.1.0 (11f6429fee5b976d9448e2d5cace789f87d4f8c8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.1.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Screenshots:**
<img width="282" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/147335501-3801466a-fe27-4e96-a285-55f86c000607.png">

Temperature :
<img width="133" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/147335695-0ad652f9-7ace-4cdf-94e4-92029bd10a01.png">
CPU:
<img width="133" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/147335966-f2d75446-40dc-48c1-aead-9d974ea1d068.png">

**Comment by prusnak** [comment]
Please run `Activity Monitor` - sort by `% CPU` column - and attach the screenshot here.

**Comment by bosomt** [comment]
Sure.

+ macOS M1
<img width="1141" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/147359244-5f1761fa-3798-442f-8744-f1885a65a4e5.png">

+ included Win 10 screen that i forgot to attach when i created issue.

![obrazek](https://user-images.githubusercontent.com/31506317/147359265-13076d39-2d4a-4a11-9beb-f2c614df015e.png)

**Comment by prusnak** [comment]
> Sure

Thanks. So at least we know it's not the Bridge :-)

**Comment by bosomt** [comment]
i just tried to download older version /before latest libs update/
commit 8479114a2fd145e3d5cc7c03ebfd8075f0aeeba4 and same result CPU goes Up even with this older dev master

**Comment by bosomt** [comment]
same result in Firefox browser

<img width="266" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/147744916-6ae6e291-9c22-4a77-9b6c-d8b0a86b246a.png">

**Info:**
 - Suite version: web 22.1.0 (11f6429fee5b976d9448e2d5cace789f87d4f8c8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.4 regular

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.1.0 (da822cabdaf85f490ada8273d5d75d509ea51175)
 - Suite version: web 22.1.0 (da822cabdaf85f490ada8273d5d75d509ea51175)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.1.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.5 regular
