### ISSUE TITLE
App storage not wiped in Windows application

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4688]
**Describe the bug**
App storage is not wiped in Windows version /i was not able to reproduce it on macOS version/
@STew790 was able to reproduce issue. 
Same results in 22.1.0 and 21.12.2.

**Steps to reproduce:**
1. Change default settings of app
2. Press `Reset app` in `Settings/Application` section
3. Observe app settings after app restart

**Info:**
 - Suite version: desktop 22.1.0 (11f6429fee5b976d9448e2d5cace789f87d4f8c8)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.1.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Win32
 - Screen: 1536x864
 - Device: model 1 1.10.4 regular

**Attachment**
Log from app before and after reboot

[trezor-suite-log-1640688024110.txt](https://github.com/trezor/trezor-suite/files/7784232/trezor-suite-log-1640688024110.txt)
[trezor-suite-log-1640688051456.txt](https://github.com/trezor/trezor-suite/files/7784233/trezor-suite-log-1640688051456.txt)

**Comment by bosomt** [comment]
**QA NOK**

retested in production and dev master on Linux and storage is still not wiped

**Info:**
 - Suite version: desktop 22.1.0 (b0defd67595dd9e4fb782549539bedc21edda38b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.1.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1536x864
 - Device: model 1 1.10.5 regular

**Comment by bosomt** [comment]
**QA NOK**

nothing has changed, settings is not wiped 


**Info:**
 - Suite version: desktop 22.3.2 (563be1e28ad75ddd4e38c2002e6032b0743511d2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1536x864
 - Device: model T 2.4.3 regular

**Comment by bosomt** [comment]
**QA OK**

Suite settings is now wiped as expected.
Im not sure it it was fixed in https://github.com/trezor/trezor-suite/pull/5149 or in previous pr

Info:

    Suite version: desktop 22.3.0 (https://github.com/trezor/trezor-suite/commit/8ecb68b468d6c640e91c3e96b28131773cb98fac)
    OS: Windows 10
    Screen: 1680x1050
    Device: model T 2.4.3 regular

**Comment by hynek-jina** [comment]
@bosomt Can we close the issue then?

**Comment by bosomt** [comment]
yes we can

**Comment by STew790** [comment]
**QA OK**

**Info**:
 - Suite version: desktop 22.4.1 (157aec2030adbb7280d8b90ef0452df2a8400aff)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.4.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device:
