### ISSUE TITLE
Cannot send erc20 when pending receiving txs

### ISSUE THREAD

**Issue by droid192** [trezor/trezor-suite#4695]
latest firmware on latest suite. the cookies were cleared before.

the eth wallet shows receiving pending transactions. if the user meanwhile tries to send a erc20, the ui goes through the signing process & final confirm 'send'. Then popup (with broken 'view details') shows up but nothing is sent, as if the tx was never generated. 

i solved via clearing the tx from the external sending wallet. then i could send from the suite again.

this is horrible experience and software gives alpha impression ..

**Comment by wendys-cats** [comment]
**QA OK**, could not reproduce when tested on [tROP](https://ropsten1.trezor.io/tx/0xd543c99a84f75007716566823c3d02b803f4701e18f22a0cb60e4f6c63384980) nor [ETH](https://eth1.trezor.io/tx/0xa8af8e619c296621507fdea06ff1049effd03ca5df9f7283c5d71a3484ebf409). If you experience this again, please reopen the issue and we will investigate.

**Info**
Suite 22.2.1 (863b788827f389eac348f15d8f673cc1069bea00) - app for tROP, Chrome browser for ETH.
OS Windows 10
Device T1 1.10.5 regular (tROP) and TT 2.4.3 regular (ETH).
