### ISSUE TITLE
Incorrect Czech translation of legacy account names

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4697]
Correct english version:
![Snímek obrazovky 2022-01-04 v 9 42 53](https://user-images.githubusercontent.com/26002916/148032570-dbd64c86-25a3-4952-8505-4b9ffbf928d0.png)

Confusing czech translation:
![Snímek obrazovky 2022-01-04 v 9 43 23](https://user-images.githubusercontent.com/26002916/148032619-66e3e194-70b9-400a-9db7-16e3e78c07d6.png)

**Comment by jerechinsky** [comment]
This has been fixed in Crowdin already and will be reflected in develop when we upload the new translations. Thank you for the issue.

**Comment by jerechinsky** [comment]
fixed on develop

**Comment by bosomt** [comment]
**QA OK**

<img width="297" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/149011586-2c061aa0-9902-4ec7-a10f-f9647294cd44.png">

**Info:**
 - Suite version: web 22.1.0 (4c925c139cc1d5ef77e4815e4c69a3e4730dc6fa)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
