### ISSUE TITLE
DOGE - transaction signing error - Encountered invalid prevhash

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4698]
**Describe the bug**
Customer is experiencing issue when signing transaction.
`transaction signing error - Encountered invalid prevhash`
He was finally able to send his funds via Exodus.
Can you please import his xpub and try to replicate his issue ?
Looks like he has some inputs that are not valid for Suite.
Previous issues with similar problem:
https://github.com/trezor/trezor-firmware/issues/1059 
https://github.com/trezor/trezor-suite/issues/3623

**XPUB**
dgub8t3b1RoB73X7yYovgsQLeMaSDnXsyMntD26n5VUBmNQAsk6m61awvAQ6MqxvEfJ9P8Ga7T42z7Mp83YzDzzwrppki1B99771aG9VM8ZMbRN

**Info:**
 - Suite version: current public version 21.12.2
 - Firmware Version: 1.10.4 and 2.4.3

**Comment by ThanaNL** [comment]
Can anyone please help, how will I be able to send DOGE from my Trezor? :) Hynek has moved my case, but I do not have an answer. Thanks in advance!

**Comment by bosomt** [comment]
@ThanatosHUN don't worry this issue is open, can you please try old wallet located here : https://wallet.trezor.io/ to send your DOGE and give us result ? Thank you !

**Comment by bosomt** [comment]
**QA OK**

i was not able to reproduce issue
we sent multiple transaction and there was no other complaint abut DOGE transactions

Maybe someone from Suite team can try to import customers XPUB and try to generate transaction ? 
/no idea if it's possible or not, it's beyond my skills/

**Comment by ThanaNL** [comment]
Thank you, the issue has been solved. I have no idea how, just was able to
send it from the online platform.

Thank you for your help!
