### ISSUE TITLE
Fee duplicity displayed on OP_RETURN with Taproot account

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4700]
**Steps to reproduce:**
1. Sent a transaction from Taproot account with OP_RETURN

**Info:**
 - Suite version: desktop 21.12.2 (8cedeed1d1da121ab6b3dff4cb6365b9030634a2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.12.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: model T 2.4.3 Bitcoin only

**Expected result:**
Show empty space like on Bech32 accounts:
![Snímek obrazovky 2022-01-04 v 10 35 38](https://user-images.githubusercontent.com/26002916/148039056-857adcc1-b64b-4ce4-b184-12e02e970723.png)

**Actual result:**
Show duplicated amount of fee.

**Screenshots:**
![OP_RETURN](https://user-images.githubusercontent.com/26002916/148038679-77524655-751e-4acf-b3e3-6b76b1f2b925.jpg)

**Comment by hynek-jina** [comment]
Related to: https://github.com/trezor/trezor-suite/issues/3351

**Comment by bosomt** [comment]
**QA OK**

looks fixed to me, just send from and to taproot and it looks as expected

_Taproot tx_

<img width="800" alt="image" src="https://user-images.githubusercontent.com/31506317/181444753-9adee5fb-8f0d-4603-aab8-54b2d9e1fc9a.png">

<img width="813" alt="image" src="https://user-images.githubusercontent.com/31506317/181449629-ec383e78-30f6-437c-b8f8-50f629d3919d.png">

**Info:**
 - Suite version: desktop 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
