### ISSUE TITLE
external keyboard stopped working after launching Tresor Suite

### ISSUE THREAD

**Issue by dcaldr** [trezor/trezor-suite#4702]
**Describe the bug**
USB connected keyboard stopped working after "type your pin phase" in Tresor Suite app and not working until os reboot. Notebook's built-in keyboard works normally.
After pin is typed the keyboard gets disconnected reconnected multiple times in few seconds. 
**I tried :** 
unplugging and pluging back in 
unplugging and plugging keyboard to differnent USB port (even from usb type 2 to type 3) 
keyboard works as expected when other hardware is plugged in, no similar problems before and without using Tresor  

**Info:**
 - Remembered Wallet: yes
 - Suite Version: app 
  - OS: Win10 10.0.19042
  - Tresor one 
  - Notebook: Asus GL503VM (+16GB RAM) 
  - Keyboard: Yenkee Model YKB 3200 

**How to reproduce**
1. Start Tresor Suite app with tresor one plugged in 
2. Type password 
3. Keyboard gets stops working  as mentioned 

**Additional context**
If it is security measure I didn't see notice

**Comment by STew790** [comment]
Hi, would you, please, let us know your app version and also, go to http://127.0.0.1:21325/status/ and tell us your Bridge version?

**Comment by dcaldr** [comment]
Hello, bridge version is 2.0.31 (rev 5f53132) , problem is persisiting even in new version of Trezor app & firmware

**Comment by dcaldr** [comment]
I tried to get Win Event Logs from app startup to keyboard freeze. I don't know if it will be helpful
[fromStartToBad.zip](https://github.com/trezor/trezor-suite/files/7958482/fromStartToBad.zip)

**Comment by bluek97** [comment]
I also have keyboard disconnect issues. I can't reliably reproduce it though. Today it stayed connected throughout passphrase entry, and throughout the transaction (although there were 2-3 USB sounds from my OS). Then as I was about to eject the Trezor, the keyboard disconnected.

Suite version: 22.1.1
Bridge version: 2.0.31 (rev 5f53132)
Windows 10 Home 10.0.19044

Edit: This happens whenever the Suite is open, it doesn't matter if a Trezor is connected or not.

**Comment by bluek97** [comment]
After monitoring the event log, the periodic errors (which don't disconnect the keyboard, but definitely interrupt usage for a second) are from a DCOM error 10016 via PerAppRuntimeBroker. Then after a period of time, the keyboard disconnect coincides with another DCOM error 10016, this time from ImmersiveShell. I can reproduce this behavior by opening Trezor Suite and just waiting.

**Comment by STew790** [comment]
I just tried this with the exact same keyboard as @dcaldr and it stayed connected throughout various attempts and even just "idling" and being connected with Suite open.

Can I ask you, do you have your keyboard connected straight to your machine or through some USB hub?

I will try to monitor this issue for a couple days but so far, I wasn't able to reproduce this.

**Comment by bluek97** [comment]
@STew790 I do have my keyboard connected to a USB hub. When I get a chance, I will try connecting directly and see if it still crashes, but that isn't a good permanent solution for my setup.

**Comment by prusnak** [comment]
> I do have my keyboard connected to a USB hub.

USB hubs are the worst, lots of them do not conform to specifications. If the device works directly, I suggest you get a better USB hub.

**Comment by hynek-jina** [comment]
We can note the problematic USB hubs, but I’m closing this issue for now.
