### ISSUE TITLE
Optimize size of suite-desktop electron package

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#4707]
Currently suite-desktop electron package is increasing in size when more libraries are being added and maybe it is the moment to start considering some improvements in size optimization.

Ways we can optimize size of the desktop app:

- [ ] Including all the dependencies from `node_modules` into the `app.js` file that can be tree shake instead of adding `node_modules` complete without any filter.
- [x] Optimize Videos packaged in the app, that are taking up to 40MB which is considerable amount of the total size (close to 40% if we do not consider the base of electron which is around 120MB)

**Comment by prusnak** [comment]
> * Optimize Videos packaged in the app, that are taking up to 40MB

Good find!

There is no reason why mp4 files should be ~7MB while their webm counterparts are only ~700kB

**Comment by prusnak** [comment]
Now that I am reading `docs/misc/videos.md`, it seems we should only use `webm` everywhere and don't package `mp4` files into the final result?

**Comment by karliatto** [comment]
> Now that I am reading `docs/misc/videos.md`, it seems we should only use `webm` everywhere and don't package `mp4` files into the final result?

I think makes a lot of sense. I will give it a try.

**Comment by prusnak** [comment]
Another offender in app.asar is `node_modules/openpgp` - it has ~20 MB, while it seems we'd need only a fraction of that (ISTM there are lot of duplicated files - `.js`, `.mjs`, `.min.js`, `.min.mjs`, etc).

**Comment by szymonlesisz** [comment]
i've found few other places where we can save some space.

- [ ] build/js/*.js.map - do we need maps in production build?
- [ ] build/static/fonts/* - duplicated woff + woff2 fonts, i'm sure 1 will be perfectly fine
- [ ] build/static/images/icons/favicon - not used
- [ ] build/static/images/icons/* - not sure about whole directory, is it used in desktop build at all?
- [ ] build/static/images/landing - irrelevant big images
- [ ] build/static/images/meta - irrelevant big images
- [ ] build/static/images/suite-web-landing - irrelevant big images
- [ ] build/static/worker.xxxx.map - same as above. do we need maps?

package.json in build app:
3 dependencies which imho are irrelevant for electron/main process to work

"react": "17.0.1"
"react-dom": "17.0.1",
"styled-components": "^5.3.3",

**Comment by tomasklim** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/6416

**Comment by hynek-jina** [comment]
@karliatto @tomasklim 
Do we want something from QA?
And are we ok with closing the issue without solving the first task?

>  Including all the dependencies from node_modules into the app.js file that can be tree shake instead of adding node_modules complete without any filter

**Comment by bosomt** [comment]
Approved.
