### ISSUE TITLE
Wrong behaviour with adding and removing recipients in send form

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4710]
### Bug appears on `Develop` only

**How to reproduce**
1. Go to Send
2. Click on `+ Add recipient`
3. Remove First address
_Both addresses were removed_
4. Add recipient again
_Both addresses were added_

https://user-images.githubusercontent.com/26002916/148776089-c3964e25-1f5d-4698-89f4-2e2509e2c47e.mov

**Expected behavior**
As in live version.
Not being able to remove last remaining address.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.1.0 (638528ddde85b8fd5ec34d753f77b8dcf27a3fff)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
