### ISSUE TITLE
Custom backend UI

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4727]
Current draft solution with coin-chips has few weaknesses.

- Direct coin settings option slides in by hover (not applicable on touch devices, since touching has already different action than hover)

https://user-images.githubusercontent.com/26002916/149172289-5438ef6e-6af1-4449-8d11-2cc6cd541e62.mov

- Animation hides coin icon (Original idea with an increase in width may end-up with bouncing loop)
- Small grey text carrying the info about usage of Custom Backend is already taken by ETH tokens info

![image](https://user-images.githubusercontent.com/26002916/149172259-179aba16-755a-4735-9e79-393c5bf515ff.png)

**Comment by hynek-jina** [comment]
Partly related to: https://github.com/trezor/trezor-suite/issues/4067

**Comment by hynek-jina** [comment]
Mobile solution:

<img width="665" alt="Snímek obrazovky 2022-01-17 v 16 03 34" src="https://user-images.githubusercontent.com/26002916/149793695-ca544a4c-ac53-4c83-a60f-0b1c3fc3ae49.png">

**Comment by hynek-jina** [comment]
- [ ] Add tooltip informing about backend request order - So the user doesn't need to worry about calling the default one before leaving settings

![image](https://user-images.githubusercontent.com/26002916/149794513-d977ceb3-26f1-4b48-af95-274e20de7ee8.png)
.

**Comment by bosomt** [comment]
maybe we can consider to change wording in custom backend modal ?

<img width="705" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/151000829-f4664df4-ee52-4587-8a9c-d98b22353c41.png">

`Try going to Settings › Crypto › Advanced settings` 
- there is no advanced settings any-more
- you are already in custom backend settings

**Comment by bosomt** [comment]
**QA NOK**

i can edit coins/backend when device is disconnected but not when connected in bootloader mode

**Device in bootloader mode**

<img width="803" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/151005765-6f9c8bed-f51d-4715-9d5c-e15d4a54ce42.png">

**Device disconnected**

<img width="821" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/151005885-c784a265-2a0d-41c8-94bf-29cbee4d85d5.png">

**Comment by marekrjpolak** [comment]
> **QA NOK**
> 
> i can edit coins/backend when device is disconnected but not when connected in bootloader mode

Strange, I can edit even when in bootloader mode. According to the tooltip it seems that the device unavailable capabilities are in `update-required` state which causes the issue, but I haven't changed this functionality afaik. Could you please try it again maybe with different device/firmware configuration or something?

**Comment by bosomt** [comment]
@marekrjpolak looks like it's happening only with model T
retested:

**QA OK** with 1.10.0 bootloader device
**QA OK** with 1.8.0 bootloader device
**QA NOK** with 2.4.3/2.0.3 bootloader device
**QA NOK** with 2.3.4/2.0.3 bootloader device


**Info:**
 - Suite version: web 22.1.0 (b0defd67595dd9e4fb782549539bedc21edda38b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0
 - OS: MacIntel
 - Screen: 1680x1050

**Comment by marekrjpolak** [comment]
> @marekrjpolak looks like it's happening only with model T

Agree, now I see it as well. But I reproduced exactly the same behavior on currently released Suite. So maybe we should create a separate issue?

**Comment by bosomt** [comment]
@marekrjpolak i did 👍🏿  https://github.com/trezor/trezor-suite/issues/4810

**Comment by bosomt** [comment]
One more nitpick
When i want to disable or enable all coins from i have to click 10+ time and not just one time before this change.
I'm not sure if anyone except QA department was using this feature but I'm already missing it 😆 :)

**Comment by hynek-jina** [comment]
> One more nitpick When i want to disable or enable all coins from i have to click 10+ time and not just one time before this change. I'm not sure if anyone except QA department was using this feature but I'm already missing it 😆 :)

@marekrjpolak could you please add it to Debug mode?
