### ISSUE TITLE
Access Settings: Trezor disconnected followup

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#4728]
- [x] sticky close button in settings (always visible on scroll) ?

- [x] improve visibility of disabled state for toggles
  - [x] cursor on all the options that are disabled should be cursor: not-allowed (crossed out circle)
  - [x] there should be an explanation tooltip on disabled toggles
![image](https://user-images.githubusercontent.com/3729633/149922461-e90b3c3e-ba55-4685-82d6-5e72a57fd2f8.png)
Figma: https://www.figma.com/file/BUMem1C7j4roQDyJf9yxQT/Exploring-Onboarding?node-id=862%3A1446

  
- [x]  Remembered device -  add banner on top of coins tab (only if the device is remembered and not connected)

- [x] improve banner paddings on small screens

- [ ] ~add Tooltips for navigation actions:  Discrete mode,  Custom backends, Tor, Early Access Program, Notifications, Settings~

**Comment by tomasklim** [comment]
Looks ugly on small screens

- [x] improve banner on small screens

![Screenshot 2022-01-24 at 13 54 19](https://user-images.githubusercontent.com/33235762/150786499-62240da3-2279-4396-9275-030d2ba4b39f.png)

**Comment by hynek-jina** [comment]
Just as a reminder:
- [ ] Implement tooltips for icons in navigation

**Comment by matejkriz** [comment]
Sorry, I haven't found a reasonable solution for tooltips for navigation icons, I just created a separate issue for it: https://github.com/trezor/trezor-suite/issues/5162

**Comment by STew790** [comment]
**QA NOK**

1) On Linux and MacARM when the device is disconnected, labeling can still be enabled, or rather the toggle still works.
2) On all OS, when the device is disconnected but it is remembered, the "Device" settings is still accessible and the tooltip on hover doesn't show. Nonetheless, the settings can't be changed.

**QA OK**
- sticky close button
- visibility state of disabled toggles
- crossed out cursor on disabled toggles
- tooltip on hover on disabled toggle for labeling (only when device is disconnected)
- banner in coins tab when device is remembered and disconnected

**Info:**
 - Suite version: desktop 22.4.1 (157aec2030adbb7280d8b90ef0452df2a8400aff)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.4.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.0 regular

**Comment by matejkriz** [comment]
> **QA NOK**
> 
> 1. On Linux and MacARM when the device is disconnected, labeling can still be enabled, or rather the toggle still works.

I agree that this case could use some bigger UX refactoring [and I mentioned that at least in the commen](https://github.com/trezor/trezor-suite/pull/4784/files#diff-2b548e442fed519540ad79422598077d06ae6c0f4662bc10493041a625158422R30-R33)t. But it is intentionally like that - to make General settings less dependent on the device. The initialization of Labeling in that case start when user select a Wallet.

> 2. On all OS, when the device is disconnected but it is remembered, the "Device" settings is still accessible and the tooltip on hover doesn't show. Nonetheless, the settings can't be changed.
> 

But there is a banner on top saying "Connect device to change Device Settings" and all the buttons are visibly disabled, right? Without tooltips, but at least with the mouse pointer indicator.

**Comment by STew790** [comment]
> I agree that this case could use some bigger UX refactoring [and I mentioned that at least in the commen](https://github.com/trezor/trezor-suite/pull/4784/files#diff-2b548e442fed519540ad79422598077d06ae6c0f4662bc10493041a625158422R30-R33)t. But it is intentionally like that - to make General settings less dependent on the device. The initialization of Labeling in that case start when user select a Wallet.

I see, so this is intended. Didn't see the comment, thank you.

> But there is a banner on top saying "Connect device to change Device Settings" and all the buttons are visibly disabled, right? Without tooltips, but at least with the mouse pointer indicator.

Yes, there is, I just thought that the tooltip on hover would be there as well but the banner is indeed sufficient.

I think the 2 points mentioned are resolved.

**QA OK**

Moving to approved
