### ISSUE TITLE
Tests integration for Electrum server backend with bitcoind regtest

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#4731]
Suite is going to have a new option to have Electrum server backend and we need to test this integration in packages/blockchain-link. In order to be able to test this integration properly we are going to have to run a docker image with electrs and bitcoind in regtest mode. 

- [x] Integrate electrs with a docker image connected to bitcoind from trezor-user-env so we are able to use the WebSocket API to create transactions and mine blocks.
- [x] Write some tests that check that the Electrum server as backend integration works as expected.

**Comment by karliatto** [comment]
This task is been completed in branch https://github.com/trezor/trezor-suite/tree/test/electrum-regtest-bitcoind, it requires [this branch](https://github.com/trezor/trezor-suite/tree/chore/electrum-followup)  to be merged before.

**Comment by bosomt** [comment]
@karliatto anything needed on QA side or i can move it to approved section ?

**Comment by karliatto** [comment]
> @karliatto anything needed on QA side or i can move it to approved section ?
@bosomt nothing can be tested in the app regarding this task
