### ISSUE TITLE
Broken background in Install firmware dialogue

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4736]
**Describe the bug**
See screenshot from web version in Firefox and video from Electron app.

**Steps to reproduce:**
1. Proceed to Install firmware modal in Install custom firmware feature
2. Observe background behavior after reconnect device in bootloader mode

**Info:**
 - Suite version: web 22.1.0 (2d57aebd2e991028b55549d036f64cf20bb1031e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Screenshots:**

<img width="1672" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/149491986-56c49ab3-e4cc-4d32-b546-ae119ab99586.png">

https://user-images.githubusercontent.com/31506317/149491999-bab703d2-ba0a-4008-a7dd-1afd0a0b1c03.mov

**Comment by matejkriz** [comment]
@tomasklim this is what broke it https://github.com/trezor/trezor-suite/commit/9d14cae1ad8dddcfdf579cd3eb7fc2d97867f78e#diff-d063c042c6beafb48007dc106df05e7487b5124d8f8928b7613aba25ccff2884L35

**Comment by tomasklim** [comment]
@bosomt should be fixed in `fix/custom-firmware-layout` branch. Could you please go through all modals and check that everything is okay? 😄

**Comment by bosomt** [comment]
**QA OK**

i will retest it one more time in app as soon it's merged to master or on staging
then i will close this issue

**Info:**
 - Suite version: web 22.1.0 (cd10a81f8e60de899eb77dc58c552ac8668ee0c5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
