### ISSUE TITLE
Guide on mobile and small screens

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4739]
Find and implement a solution for Suite Guide on small screens  (<= 992px).
 

**Spec:**
- the width of the Guide remains fixed ([350px](https://github.com/trezor/trezor-suite/blob/develop/packages/components/src/config/variables.ts/#L13))
- guide is opened from right side (same for all screen sizes)
- screen width above [992 px](https://github.com/trezor/trezor-suite/blob/develop/packages/components/src/config/variables.ts/#L7) remains unchanged.
- screen width [992 px](https://github.com/trezor/trezor-suite/blob/develop/packages/components/src/config/variables.ts/#L7) and below:
  - Guide is displayed OVER modals with overlay. Modal won't move, or better yet, it will be aligned to the left side of the screen so it's easier to see what it contains (nice to have).
  ![image](https://user-images.githubusercontent.com/3729633/152973167-23d8704c-ab6b-41c5-88ad-f4f89445aaf5.png)
- screen width [768 px](https://github.com/trezor/trezor-suite/blob/develop/packages/components/src/config/variables.ts/#L6) and below:
  - Guide is displayed even over navigation bar.
  ![image](https://user-images.githubusercontent.com/3729633/152974842-75e03bfa-46b3-486e-afb4-f5f86952215a.png)
  - Suite Guide should be now accessible from mobile menu (We call it Suite Guide no more Learn & Discover 
  ![image](https://user-images.githubusercontent.com/3729633/152975412-ded25a9e-2480-46cf-9ecc-75c71ef5a684.png)
  - Suite Guite button (lightbulb at the bottom right corner) should be shown
  ![image](https://user-images.githubusercontent.com/3729633/152980368-57f99f0f-0e2c-4b62-b408-8f5ed6bfb375.png)
 
  - Suide Guide button could be hidden if there is an opened modal or (nice to have) displayed as a new button next to close X button:
  ![image](https://user-images.githubusercontent.com/3729633/152977948-dc21dc13-3d03-4381-bf69-95c23b39a6b2.png)
  - Make sure links to guide from tooltips start working as expected  
  ![image](https://user-images.githubusercontent.com/3729633/152979997-a424d9f4-dda8-49a2-94a6-3b5db29ffac4.png)

____
Current state: 
- There is no guide on mobile and small screens (screen width <= 768px)
- Guide breaks layout on some places on small screens (screen between 768px and 992px) 

Why:
- we do not want to have broken layout
- we want to be able to show guide as it is the only place how to find a link to contact support (there are some other places e.g. in onboarding, but I think we should remove it)

**Comment by dahaca** [comment]
> * Suide Guide button could be hidden if there is an opened modal or (nice to have) displayed as a new button next to close X button:

Expanded & moved to #5062

**Comment by STew790** [comment]
**QA NOK**

1. Suite guide not visible after clicking on the yellow light bulb in the select wallet modal
![image](https://user-images.githubusercontent.com/48477147/162766175-8e5a47b8-ed94-43a5-8b82-23fc79f8595c.png)

2. Suite guide light bulb not present in the "Check for updates" modal from settings
![image](https://user-images.githubusercontent.com/48477147/162766272-f9171c52-ad9d-48ca-836f-08f37782771a.png)

**Info:**
 - Suite version: web 22.4.1 (157aec2030adbb7280d8b90ef0452df2a8400aff)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device:

**Comment by dahaca** [comment]
> 1. Suite guide not visible after clicking on the yellow light bulb in the select wallet modal

https://github.com/trezor/trezor-suite/pull/5256

> 2\. Suite guide light bulb not present in the "Check for updates" modal from settings

That's not a `Modal` in code but something else, which is named `Box` :( 

@tomasklim Should I add a guide button there for now? Why not using Modals instead of `Box`?

**Comment by STew790** [comment]
**QA OK**

2 fixes mentioned above will be part of the next release.
