### ISSUE TITLE
Very long labels not handled properly in Suite

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4744]
**Describe the bug**
Label size is not handled properly in Send dialogue.
See screenshot, you can enter very long label

**Steps to reproduce:**
1. Enable labelling
2. edit label in send dialogue
3. observe what happens when you enter very long label

**Info:**
 - Suite version: desktop 22.1.1 (7e2101c6d91c14e6a0faba8b4057f04ba2422578)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.1.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 Bitcoin only

**Screenshots:**
<img width="1393" alt="Screenshot 2022-01-14 at 16 36 40" src="https://user-images.githubusercontent.com/31506317/149542311-94e2d29d-7167-4e91-9eba-22545a46675a.png">

**Comment by hynek-jina** [comment]
Same behaviour like in transaction overview can be used.

**Comment by bosomt** [comment]
**QA NOK**

still same behavior 

**Info:**
 - Suite version: desktop 22.8.2 (58f4c5bf0804e02c05c0b85e020b6e452b419164)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.2 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Bitcoin-only (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA NOK**

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/31506317/186844127-5b35d9b3-3245-4657-a1d3-9c17ac83cdb3.png">


**Info:**
 - Suite version: web 22.9.0 (f385f10a1fcd82339636d9c40f669c365a9e0c90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.1.0 (e24c80afa0c49184f185c16112b545aab9bf0271)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.1.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
