### ISSUE TITLE
Old supported browsers do not work

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4750]
**Describe the bug**
We support Firefox from version 62, but this version and a few following ones do not work. This applies both to the Suite and landing page. Especially landing page should work in most browsers.

**How to reproduce**
Steps to reproduce the behaviour:
1. Download old Firefox. https://ftp.mozilla.org/pub/firefox/releases/62.0/

**Expected behaviour**
The app should work or should warn that the user is using an unsupported browser.

**Screenshots**
<img width="1227" alt="Screenshot 2022-01-14 at 16 44 35" src="https://user-images.githubusercontent.com/33235762/149736214-c8c9504d-2859-4d3a-8c7b-84c027f2a215.png">

Design:
https://www.figma.com/file/fu1f9wihpfaT37QzvCkl4K/UI-Sync?node-id=10%3A1578

**Comment by prusnak** [comment]
Let's increase the support version to 78 which was the previous ESR with support that ended in Nov 2021.

Latest ESR that still has support is 91.

Source: https://endoflife.date/firefox

**Comment by prusnak** [comment]
Maybe we should add the required versions to this screen?


![](https://user-images.githubusercontent.com/1835345/147927946-83f8b8d1-1bc3-4cb3-a145-8659f688193a.png)

**Comment by tsusanka** [comment]
Related: https://github.com/trezor/trezor-suite/pull/4691

**Comment by tomasklim** [comment]
Bumping also Chrome/Chromium required version to ~~83~~ 84, which has almost the same release date as Firefox 78. Our app is not working in older Chromes because of the same error mentioned in the first post.

EDIT: I will bump Chrome to 84 to support https://caniuse.com/flexbox-gap which will help us with styling a lot @marekrjpolak

**Comment by bosomt** [comment]
@tomasklim 
so what's the testing plan ?

Google Chrome 83 - not supported warning 
Google Chrome 84 - supported without warning
Firefox 77 - not supported warning
Firefox 78 - not supported without warning
Landing page - including not supported version works correctly

right ?

**Comment by tomasklim** [comment]
@bosomt 

1. 
Check links on unsupported browser page - `Download` app, `Download` browsers, `Update` browsers

2. 
Your list can be extended by:
Edge/Safari - unsupported browser warning + `go to suite` link in the bottom
Android Samsung browser - unsupported browser + `go to suite` link in the bottom
Android Chrome - should work as before
iOS - not available on iOS + missing `go to suite` link

@STew790 tested that it also works in IE11 and Opera 21
(we do not care about styles, we care that the functionality and texts are there)

3. 
Check also the landing page. I made there some browser compatibility changes.
The `Download` button should work, `Trezor Suite for web` button should work.

IE11 / old Opera should display `Download` buttons and they should work. (We do not expect that our users use it. However, if it works in IE, it works everywhere)
(Probably some styles will be broken, but we care that the functionality and texts are there)

**Comment by STew790** [comment]
**QA OK**

- IE11/ old Opera landing page buttons works as expected and /web page also shows correctly links for supported browsers or app.
- Edge landing page works correctly and /web page as well
- Android Samsung browser /web shows link to download Chrome for Android
- Android Chrome works the same as before
- iOS correctly shows not available on iOS

@bosomt please, test Safari landing page and /web page

**Comment by bosomt** [comment]
**QA OK**

Safari Version 15.4 (17613.1.17.1.6) 

- Landing looks as expected 
- web Suite  Your browser is not supported + download links
