### ISSUE TITLE
ETH fees in Trezor Suite

### ISSUE THREAD

**Issue by soucek87** [trezor/trezor-suite#4751]
**Describe the bug**
A user reached out to us that Suite doesn't calculate fees correctly (sufficiently) which resulted with loss of fees. Exodus, as he said,  calculated it correctly, and tx went through. TXs he refers to: 0xc962134da9cfcae241df63edc3f4e5b585d5cc03ce732f565f6e378e3ae92cba
0x91ee2f868a5224a130659edb1e0de2c0c5ecd3c640c7feb15ff452e0098c882a

**Info:**
Testing environment, Trezor Suite version as per detailed log attached
[trezor-suite-log(5).txt](https://github.com/trezor/trezor-suite/files/7880702/trezor-suite-log.5.txt)

**Comment by hynek-jina** [comment]
This appears to be an edge issue.
