### ISSUE TITLE
Specify supported browser version

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4752]
When user opens https://suite.trezor.io/web/ from unsupported browser - he gets this screen pushing for download of supported browsers. 
We don't support old versions so it might helpful to mention oldest supported one.

Maybe we should add the required versions to this screen?

![](https://user-images.githubusercontent.com/1835345/147927946-83f8b8d1-1bc3-4cb3-a145-8659f688193a.png)

_Originally posted by @prusnak in https://github.com/trezor/trezor-suite/issues/4750#issuecomment-1014279159_

**Comment by prusnak** [comment]
Upon further inspection, it seems that if you are using an older version of supported browser, another dialog is shown, which tells you to update the browser. If that is really the case, we can close this issue.

**Comment by hynek-jina** [comment]
True,
tested on Firefox v 50.0
![Snímek obrazovky 2022-01-17 v 14 53 40](https://user-images.githubusercontent.com/26002916/149781379-87f9210d-914a-4f56-a35c-af37185904d1.png)
