### ISSUE TITLE
Suite guide is not overlapping "Skip" modals in onboarding

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#4755]
**Describe the bug**
Suite guide is not visible, nor is overlapping "Skip" modals in Suite

**Steps to reproduce:**
1. Wipe device
2. Open up Suite guide
3. Start new onboarding and proceed to setting up a PIN for your device
4. Click on "Skip PIN" 
5. Modal with confirming of skipping PIN creation appears and Suite guide is not visible, nor usable

**Info:**
 - Suite version: web 22.1.1 (75797e8edb726d7ede741a1218ff84a2320a92e0)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.5 regular

**Expected result:**
Suite guide should be available everywhere in the Suite.

**Actual result:**
Suite guide is not available for the user while the "Skip PIN" modal is opened

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/149797844-540e20d2-c911-4deb-82c0-dc0d3181a4ef.png)

**Comment by tomasklim** [comment]
We detect open modal window using either `state.router.route?.isForegroundApp` or `state.modal.context !== MODAL.CONTEXT_NONE` variables from Redux. However, in case of `Skip PIN` and `Skip Backup` modals those conditions are not fullfilled as it does not use Redux. Moreover, onboarding itself is a `isForegroundApp`.

I think fixing this bug is not worth it for now and is not straightforward.

**Comment by tomasklim** [comment]
Early access modals also do not work with guide

**Comment by tsusanka** [comment]
So @tomasklim closing? I think modals AND onboarding/EAP is quite edge-casy and we can live without this.

**Comment by STew790** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/48477147/171410830-a5f33698-fa66-4779-8991-d7b6fe897271.png)

**Info:**
 - Suite version: desktop 22.6.1 (8d37e21edabe10ea6b6991f5e3a338e3464925e1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
