### ISSUE TITLE
Setup data analytics for Connect pop-up

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4771]
We would like to know how Connect is being used on third party websites. This feature has two goals:

## 1. Better insights into what software is being used

So we know what OSes, Bridge versions etc are out there. That means gathering:

- Device info (same as in Suite)
    - `model`
    - `language`
    - `firmware`
    - `pin_protection`
    - `passphrase_protection`
    - `backup_type`
    - `mode` (if easily available)
    - `isBitcoinOnly` (if easily available - it will be False most of the time but to have some consistency)
    - `totalDevices` (if easily available)
    - `totalInstances` (if easily available)
    - `vendor`
    - `fw_vendor`
- Bridge and OS info
- Coin info
- URL/project which loads Connect (see the manifest that we have and URL as well)
- Standalone app vs web projekt (e.g. Exodus is a desktop app)
- Separate Connect function calls
    - Among other things this will help with Connect maintenance so we know what parts of code are being used and what aren’t.

## 2. Compare third-parties to Suite

We want to compare usage numbers between Suite and Connect.

We should track Connect sessions (or just device connect actions) - those are comparable to sessions (or device connect actions) in Suite, as long as the user has an active account for a particular coin.

**Comment by tsusanka** [comment]
Let's held a meeting on this to sync (Hynek will schedule it). Let me, however, summarise what is needed here:
<s>
- [ ] @vdovhanych will create a new folder structure in https://github.com/trezor/webwallet-data which will then propagate to data.trezor.io and we can start sending HTTP requests on that location. File structure to be discussed
- [ ] @tptz will prepare this on the "Data side" and help with any "Data engineering" tasks. Not much should be needed as this will mimic the Suite behaviour, but we'll invite him for the meeting to get in sync.
- [ ] @kolomaznikt can help us to ask the right questions, in other words, decide together what we want to track.
- [ ] @mroz22 (or any other member from the Suite team) will then implement it to Connect.
- [ ] @matejzak @Hermez-cz (or someone from the Product team) needs to come up with some nice design/workflow informing about the fact that we collect data.
</s>

Let's first take it from the "product" side of things. @mroz22 will make screenshots of current Connect pop-up workflows, then we'll product-analyse it and after that we can discuss data. @tsusanka will find out what we want to gather in the meantime. Sorry for the fuzz.

**Comment by sime** [comment]
Will be considered for Connect v9.

**Comment by sime** [comment]
Very high level, but missing some error tracking too. Currently, we are blind on Connect.

**Comment by tsusanka** [comment]
It would make sense to add Sentry as well? We just need to remember to have it opt-in.

**Comment by sime** [comment]
Added `fw_vendor` to track signed vs unsigned FWs.

**Comment by bosomt** [comment]
I see that analytics is being reported in connect popup /and not reported when not approved/
But i dont see any FW version, model type or vendor being reported in network tab

![image](https://user-images.githubusercontent.com/31506317/206153404-f7e13a4c-d2b0-4bab-ac3a-f47f05b21990.png)

**Comment by sime** [comment]
> I see that analytics is being reported in connect popup /and not reported when not approved/ But i dont see any FW version, model type or vendor being reported in network tab

@tomasklim Please shout out if this should be tracked in a separate issue.

**Comment by bosomt** [comment]
**QA OK**
