### ISSUE TITLE
@trezor/utils package improvements

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#4786]
With the PR https://github.com/trezor/trezor-suite/pull/4666 we are adding new package `@trezor/utils`. The purpose of this issue is to track potential improvements to that package and discuss whether some utilities make sense to be moved there or not.

## Potential candidates for further improvements

- [ ] trezor-suite/packages/suite/src/utils/suite/parseUri.ts
- [x] trezor-suite/packages/suite/src/utils/wallet/validation.ts
- [x] trezor-suite/packages/suite/src/utils/wallet/promiseUtils.ts
- [x] trezor-suite/packages/suite/src/utils/wallet/ethUtils.ts
- [x] trezor-suite/packages/suite/src/utils/wallet/csvParser.ts
- [x] trezor-suite/packages/rollout/src/utils/version.ts #4870
- [x] trezor-suite/packages/transport/src/utils/semver-compare.ts #4897 
- [x] trezor-suite/packages/utxo-lib/src/crypto.ts
- [x] trezor-suite/packages/utxo-lib/src/bufferutils.ts
- [ ] connect-explorer/src/js/components/Response.tsx
- [ ] packages/transport/src/bridge/http.ts or parts of it to have a generic http utility
- [x] connect/deferred https://github.com/trezor/trezor-suite/pull/9353
- [x] connect/utils

**Comment by szymonlesisz** [comment]
typescript utilities:
- [ ] trezor-suite/packages/suite/src/types/utils
- [ ] trezor-suite/packages/suite-desktop-api/src/methods
- [ ] connect/types/utils

**Comment by mroz22** [comment]
@karliatto could you please go through the list once again? it is now pretty outdated. we could then refactor couple of those remaining and close this issue I guess

**Comment by karliatto** [comment]
I think most of them have been moved to `@trezor/utils` or `@trezor/wallet-utils` or `@trezor/node-utils` with some exception that are just used in some package and probably does not make sense to move it to a more generic utils package at least until it is not required to be use somewhere else.

I moved this last one https://github.com/trezor/trezor-suite/pull/15856 and would I marked to resolve this issue done after that one is merged.
