### ISSUE TITLE
Update copy on landing page (redirected from Wallet)

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4795]
Edit header copy and explanatory box for traffic redirected from https://wallet.trezor.io/ to https://suite.trezor.io/?fromMytrezor=true 

Currently stored on:
https://suite.corp.sldev.cz/suite-web/feat/wallet-deprecation-banner/?fromMytrezor=true (VPN)

```
# Start using Trezor Suite
### A safer, more private experience for desktop & browser.

[Download] 
---
## Looking for Trezor Wallet?
### Trezor Suite is a new interface that makes using your Trezor more private and secure. Learn more 
---
# Trezor Wallet is no longer supported

### Start using Trezor Suite today to enjoy new features, more privacy, and regular updates.

Trezor Suite is a brand new interface for desktop and web that lets you do more with your hardware wallet. The old Trezor Wallet web interface will not be supported from January 31st 2022, so now's the time to get familiar with Trezor Suite. 

For all the new features, download the desktop app. Trezor Suite can be accessed in your web browser by clicking the link at the top-right of this page.

This change won't affect your coins or keys. You will find all the same features (and more!), so you can just install the desktop app and continue from where you left off. 

# What's new in Trezor Suite?

   - Privacy at the flick of a switch with Tor
   - A new, more intuitive interface
   - Quicker transactions with RBF
   - Enough power for exciting upcoming features!

Trezor Suite also has all the features you're used to from the old Trezor Wallet so you can hit the ground running!

# How to get started
    Download and run Trezor Suite for desktop, plug in your hardware wallet and get set up in seconds!
    Alternatively, use the web app to access standard functions (much like in Trezor Wallet). Advanced features are only available using the desktop app.
```

**Comment by jerechinsky** [comment]
I changed all the keys to the requested copy in Crowdin. The following keys do require further attention, though: 

key | old copy | new copy | note
--- | --- | --- | ---
TR_SUITE_WEB_LANDING_ HEADLINE_FROM_MYTREZOR | Trezor Suite makes managing {lineBreak} your crypto safer and easier | Start using Trezor Suite | ✅ I changed it, but previously there was a break in the line. The second line was designed to be green. New copy is too short for two lines so that design element is lost.
TR_SUITE_WEB_LANDING_SUB_HEADLINE | Take control of your Trezor with our desktop & browser app. | Trezor Suite is a new interface that makes using your Trezor more private and secure. Learn more | ❗This key is not unique to landing page of users coming from wallet. It's the same one that's used on the normal page. I think we need a new key @pingpwned. 

Changes will be reflected after #4808 is merged and after crowdin sync from @mroz22.

**Comment by alex-jerechinsky** [comment]
Forgot to tag @hynek-jina to ask for URL of the `Learn more` link in `TR_SUITE_WEB_LANDING_ START_SUB_HEADLINE`. 🙏

**Comment by dimasivan** [comment]
`TR_SUITE_WEB_LANDING_HEADLINE_FROM_MYTREZOR`
 `Start using <em>Trezor Suite</em>`

`TR_SUITE_WEB_LANDING_SUB_HEADLINE_FROM_MYTREZOR`
A safer, more private experience for desktop & browser.

[Download button] 

`TR_SUITE_WEB_LANDING_BANNER_HEADLINE_FROM_MYTREZOR`
 Looking for Trezor Wallet?

`TR_SUITE_WEB_LANDING_BANNER_DESC_FROM_MYTREZOR`
Trezor Suite is a new interface that makes using your Trezor more private and secure. 

`TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_HEADLINE_0`
 Trezor Wallet is no longer supported

`TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_PARAGRAPH_0`
 `<strong>Start using Trezor Suite today to enjoy new features, more privacy, and regular updates.</strong>`

`TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_PARAGRAPH_1`
`Trezor Suite is a brand new interface for desktop and web that lets you do more with your hardware wallet. The old Trezor Wallet web interface <strong>will not be supported from January 31st 2022</strong>, so now's the time to get familiar with Trezor Suite.`

`TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_PARAGRAPH_2`
`For all the new features, download the <strong>desktop app</strong>. Trezor Suite can be accessed in your <strong>web browser</strong> by clicking the link at the top-right of this page.`

`TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_PARAGRAPH_3`
This change won't affect your coins or keys. You will find all the same features (and more!), so you can just install the desktop app and continue from where you left off. 

`TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_HEADLINE_1`
What's new in Trezor Suite?

`TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_PARAGRAPH_4`

`<ul><li>Privacy at the flick of a switch with Tor.</li> <li>A new, more intuitive interface</li> <li>Quicker transactions with RBF</li> <li>Enough power for exciting upcoming features!</li></ul> Trezor Suite also has all the features you're used to from the old Trezor Wallet so you can hit the ground running!`

`TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_HEADLINE_2`
How to get started

`TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_PARAGRAPH_5`
    `<StyledCollapsibleBoxLink>Download and run Trezor Suite for desktop</StyledCollapsibleBoxLink>, plug in your hardware wallet and get set up in seconds!{lineBreak}Alternatively, use the web app to access standard functions (much like in Trezor Wallet). Advanced features are only available using the desktop app.`

**Comment by STew790** [comment]
**QA OK**


![image](https://user-images.githubusercontent.com/48477147/151583591-5e9d964f-a28b-40d0-baba-b6095eb644bd.png)

**Comment by STew790** [comment]
**QA NOK**

Sorry, the copy is really different then what is actually here https://suite.trezor.io/?fromMytrezor=true

Thank you @hynek-jina for pointing it out.

**Comment by jerechinsky** [comment]
I can see that the landing page you linked still has the old copy e.g. `Coming from Trezor Wallet?`.

But on develop copy has been updated even in default messages. 
https://github.com/trezor/trezor-suite/blob/87e552d4f1b1fc932fb853385d722b3f8a678916/packages/suite/src/support/messages.ts#L6367-L6369
https://github.com/trezor/trezor-suite/blob/7f81d831608cf02cb37ea8da02d34fb6bc4f2882/packages/suite-data/files/translations/en.json#L22

Do we know that these changes have actually been deployed to [suite.trezor.io](https://suite.trezor.io)? I'm not too involved so I'm not aware. Can someone chime in?

**Comment by hynek-jina** [comment]
@alex-jerechinsky It was not released yet.

**Comment by jerechinsky** [comment]
Thank you @hynek-jina. And I can see that it's correct on https://staging-suite.trezor.io/?fromMytrezor=true 
so we should be OK.

**Comment by STew790** [comment]
@alex-jerechinsky yes, exactly. It wasn't synced before but now it is on staging.

Now it is **QA OK**
I am sorry for the confusion.
![image](https://user-images.githubusercontent.com/48477147/153019744-e3b0e3b1-2f8b-43e3-98f5-ad8c25ae5d60.png)
