### ISSUE TITLE
Deprecation warning in unit tests

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#481]
![image](https://user-images.githubusercontent.com/3112191/64244238-f8a8a280-cf08-11e9-9f39-0de06017ee4d.png)

**Comment by mroz22** [comment]
its from node.js crypto module that I use to simplify assertions in homescreen.ts tests. I will look at it.

**Comment by mroz22** [comment]
should be fixed in https://github.com/trezor/trezor-suite/commit/2e0a3aa678a76dca69fc26ae963678568ee511bf
