### ISSUE TITLE
Cardano: copy check

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4813]
@b-irving we will need a comprehensive copy check of Cardano in Suite. I am making this issue now, so if you want feel free to play around, however **there will be a demo** next week to present the feature, so ideally let's wait until then so you have an idea what we are talking about :).

Suite desktop build containing Cardano:
- [Linux](https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/2009314700/artifacts/download)
- [macOS](https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/2009314699/artifacts/download)

**Comment by afsoningo** [comment]
#4725 #4829 #4781 #4833 #4829

**Comment by tsusanka** [comment]
@b-irving the demo is here: https://www.loom.com/share/b3176d197d8d46198605093ae4c610a8
(the huge QR code is fixed already don't worry about that)

I am also sending this to Product so they will make a product review but I think it is fine to check the copy right away as I hope there will not be many changes there.

I'll also send the newest binaries shortly.

**Comment by b-irving** [comment]
@tsusanka fantastic, thank you!

**Comment by tsusanka** [comment]
Done and checked by @b-irving, it is all good :).
