### ISSUE TITLE
Issue with pixel density of QR code

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4814]
**Describe the bug**
See screenshots.
Same reults in app and in Firefox browser.

**Steps to reproduce:**
1. Load Suite
2. Show receive or public key QR code
3. Observe

**Info:**
 - Suite version: web 22.1.0 (f5a9176dd5b338f87cdb5c5395358939138b1482)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Screenshots:**
<img width="1345" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/151168777-700ea91f-89cc-4212-a1bd-473435aeec7f.png">

<img width="950" alt="Screenshot 2022-01-26 at 14 08 31" src="https://user-images.githubusercontent.com/31506317/151168646-77f8c076-9a36-4c9c-85d9-b76f03f177f1.png">

**Comment by tomasklim** [comment]
It is a problem on pixelDensity > 1 screens because of this https://github.com/zpao/qrcode.react/blob/main/src/index.js#L278-L285 in QR library.

We should remove 
`style={{ width: '100%', height: 'auto' }}` from QRCode component and reduce size of QRCode according to screen size. On small devices it should be max 250-300px to fit the modal.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.1.0 (fdfa3c5dec90e2c2977512e96f4a114c854fe67a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.1.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular

**Comment by bosomt** [comment]
**QA NOK**

i was able to reproduce issue in current staging version 22.2.1
or maybe it's not same issue but modal does not fit to Suite window
or maybe we can ignore it, QR code fits to window and if QR code does not scale it's size  we can't fix every resolution/scale
ASUS laptop 1920x1080 in default 150% scale it does not fit to display

![obrázok](https://user-images.githubusercontent.com/31506317/152678957-df0508eb-b017-4942-8c1c-c8bf0c0b1159.png)


**Info:**
 - Suite version: desktop 22.2.1 (863b788827f389eac348f15d8f673cc1069bea00)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.2.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Win32
 - Screen: 1280x720
 - Device: model 1 1.10.5 regular

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.2.1 (520802b8052d558de9c5f0ee55f9151ea5122eb4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.2.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
