### ISSUE TITLE
Moderation required on SatoshiLabs in the Microsoft winget package repository

### ISSUE THREAD

**Issue by brianddk** [trezor/trezor-suite#4822]
SatoshiLabs is showing up in the [winget package repo](https://github.com/microsoft/winget-pkgs/tree/master/manifests/s/SatoshiLabs).  It's great to see the packages there, but you might want to take over the PR submission for your ORG.  The packages there seem legit, but technically, anyone could contribute any package there and call it "TrezorSuite".  Your dev team may want to take over these submissions, or request you appear on the PR approval list for your ORG.

* [SathosiLabs Products on Microsoft Repo](https://github.com/microsoft/winget-pkgs/search?q=%28trezor+AND+bridge%29+OR+SatoshiLabs.Trezor&type=issues)
* [Package Contributing Guidelines](https://github.com/microsoft/winget-pkgs#contributing)
* [Open Discussion on Microsoft Moderation Practices](https://github.com/microsoft/winget-pkgs/discussions/15607)

**Comment by tsusanka** [comment]
Hi @brianddk, as there are many package managers out in the wild, it is quite hard to maintain all of them.

As I am looking into the winget repo it seems to me that the Suite apps are taken from GitHub release directly, so that's great and does not have to be changed. Approving the PRs from our side would be nice though.

> request you appear on the PR approval list for your ORG.

If you are familiar with the topic, could you please point to some docs how we can do that?

**Comment by brianddk** [comment]
> If you are familiar with the topic, could you please point to some docs how we can do that?

There are proposals in the works, and I've added to the proposal process.  SL input would be great as well.  It's a fairly heated topic and not yet solidified.

https://github.com/microsoft/winget-pkgs/discussions/15607#discussioncomment-2069357

**Comment by tsusanka** [comment]
Great! I will try look to into that. As there is not much we can do directly here in trezor-suite, I am closing this one. Thanks for the heads-up and I'll try to look into the discussion at some occasion.

**Comment by vedantmgoyal9** [comment]
Hi @tsusanka, you can use https://github.com/marketplace/actions/winget-releaser to officially publish trezor-suite to winget repo. A personal access token will be required to create a PR at microsoft/winget-pkgs repo, and microsoft/winget-pkgs needs to be forked under the org/a bot account like @trezor-ci.
