### ISSUE TITLE
trezor.io homepage missing onion links

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#4823]
while browsing `trezor.io` homepage with tor browser on `trezoriovpjcahpzkrewelclulmszwbqpzmzgub37gbcjlvluxtruqad.onion` i've noticed that there are multiple external links which are not converted to onion addresses, especially link to "Suite" (top right menu), but there are much more.
scroll down and check every link/button

**Comment by tsusanka** [comment]
As we will move to new trezor.io in a few months let's do it then and let's track it there.

cc @Hermez-cz @ElKaDu we need to have the Tor URLs in the new knowledge base or somewhere where it is easily discoverable. Doing Tor recognition and altering the URLs can be done post-MVP I believe.
