### ISSUE TITLE
When disabling TOR, custom backend URLs are not updated so it fails discovery

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#4838]
**Describe the bug**
When disabling TOR, custom backend URLs are not updated so it fails discovery.

**Info:**
 - Remembered Wallet: no
 - Suite Version: desktop-app, develop branch, commit -> 4679a9e84b4bf245fe6880644df4a281f5e6ec06
 - Browser: electron
 - OS: Pop!_OS 21.04
 - Bridge: 2.0.27
 - Firmware Version: Trezor One, 1.10.5

**How to reproduce**
In Desktop app:
1. Enable TOR
2. Disconnect and connect the device to start new discovery with TOR
3. Disable tor
4. Disconnect and connect the device to start new discovery without TOR
5. Discovery fails and if you go to settings > Crypto > Bitcoin settings > You can see custom backend URLs for are `.onion`

**Expected behavior**
When disabling TOR the custom backend URLs should be updated to the default ones or ask the user what they want to do. The current behavior is confusing.

**Comment by marekrjpolak** [comment]
This could be connected to the connect-in-electron problems we're currently solving. Could you please try it on https://github.com/trezor/trezor-suite/tree/chore/connect-electron-followup branch?

**Comment by wendys-cats** [comment]
**QA OK**, could not reproduce.

**Info:**
 - Suite version: desktop 22.2.1 (863b788827f389eac348f15d8f673cc1069bea00)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.2.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular
