### ISSUE TITLE
When a branch with # in the branch name suite e2e tests fail

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#4840]
When creating a branch with `#` in the branch name test fails and it is not very intuitive the reason why. The consequence is wasted developer time trying to figure out what is happening.

Possible solutions:
1. Make some changes that allow the test to work when the branch name contains `#`.
2. Implement a simple check that when it finds `#` in the branch name, tests in CI fail with a meaningful message.

**Comment by matejkriz** [comment]
fixed by https://github.com/trezor/trezor-suite/pull/5163
