### ISSUE TITLE
Docker to test suite e2e fails to start because of node version enforcement

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#4841]
Since we started enforcing node version the docker container for suite e2e testing fails to initialize with the error below:

```bash
[1/5] Validating package.json...
error trezor-suite@1.0.0: The engine "node" is incompatible with this module. Expected version "14.18.1". Got "14.16.1"error trezor-suite@1.0.0: The engine "yarn" is incompatible with this module. Expected version ">=1.22.11<2". Got "1.22.5"
```

**Comment by Nodonisko** [comment]
Hotfix is here #4843 but it should be solved by our own Docker repository where we can manage all our docker images. cc @vdovhanych

**Comment by mroz22** [comment]
I guess we are good?

**Comment by karliatto** [comment]
> I guess we are good?

Yes, this was fixed.
