### ISSUE TITLE
Support Electrum-compatible signatures in SignMessage

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#4855]
Wallets like Sparrow can create signatures compatible both with Trezor/BIP137 and Electrum.

![Screenshot from 2022-02-01 16-20-43](https://user-images.githubusercontent.com/42201/152528129-5eb1835d-01dc-4042-8df2-37aa75231d46.png)

Let's add the same switch to our SignMessage dialog, but change the wording to

`BIP137 (Trezor)` | `Compatibility (Electrum)`

and set the first (BIP137) as default.

BIP137 corresponds to `no_script_type == false`, while Electrum corresponds to `no_script_type == true`.

We do not need to change the VerifyMessage dialog since firmware will be able to check both in the future: https://github.com/trezor/trezor-firmware/issues/2100

**Comment by bosomt** [comment]
**QA OK**

Electrum version valid, trezor version not valid in Electrum 4.1.5

_Trezor vs Electrum message format_

-----BEGIN BITCOIN SIGNED MESSAGE-----
a
-----BEGIN SIGNATURE-----
bc1qfcjv620stvtzjeelg26ncgww8ks49zy8lracjz
H2hfrN0Zn3EkqPTODeVvY+fsm34+3wFT56MT4q7tRtAVZOqeNWmlspQsvhdOOdmfYjbJK3UzKlmm2F6S/iDnAZY=
-----END BITCOIN SIGNED MESSAGE-----

-----BEGIN BITCOIN SIGNED MESSAGE-----
a
-----BEGIN SIGNATURE-----
bc1qfcjv620stvtzjeelg26ncgww8ks49zy8lracjz
J2hfrN0Zn3EkqPTODeVvY+fsm34+3wFT56MT4q7tRtAVZOqeNWmlspQsvhdOOdmfYjbJK3UzKlmm2F6S/iDnAZY=
-----END BITCOIN SIGNED MESSAGE-----

**Info:**
 - Suite version: web 22.3.0 (4e7a0668aa5cc3853c1bb3281c8393b9577d7062)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Comment by bosomt** [comment]
i just noted that we have 2 different `Clear all` buttons.
Is that expected ? 

<img width="800" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/156820891-91b872df-1018-4975-85a8-1186a6f8e6cb.png">

**Comment by dahaca** [comment]
@bosomt The upper `clear all` is present whenever there is text in the form, the bottom one appears when a message has been signed. Personally, I do not find it to be an issue and it might provide more flexibility in some cases. I would not force a user to a certain flow too much.
