### ISSUE TITLE
TrezorConnect window crashes when Trezor Bridge is forcefully stopped

### ISSUE THREAD

**Issue by shinsuny** [trezor/trezor-suite#4857]
When TrezorConnect is the middle of processing any request and Trezor Bridge is forcefully stopped then TrezorConnect window crashes.

There is no response from the called method ( may be because of crash ), although UI event for window close is received.

TrezorConnect v6
TREZOR Bridge Version: 2.0.19 and Version: 2.0.24
Ubuntu 16.04

**Comment by Hannsek** [comment]
@mroz22 Can we close this?

**Comment by Hannsek** [comment]
Closing this as Connect v6 is deprecated.
