### ISSUE TITLE
feature: list which xpubs are being requested in getPublicKeys

### ISSUE THREAD

**Issue by keepkeyjon** [trezor/trezor-suite#4860]
The current dialog in `getPublicKey` doesn't tell you which XPUBs are being requested when an app asks for more than one. It would be more user-friendly if that dialog told them which accounts this is giving full transaction history on.

**Comment by sime** [comment]
This is the case now ![Screenshot 2023-05-12 at 20 09 22](https://github.com/trezor/trezor-suite/assets/216917/66d9e644-b10a-4d62-af1e-70bd191482a1)
