### ISSUE TITLE
WebUSB usage in Connect

### ISSUE THREAD

**Issue by Mrtenz** [trezor/trezor-suite#4865]
Is there any documentation on using WebUSB? I tried simply using the `webusb` option on `TrezorConnect.init`, but that doesn't seem to work. Is there anything else needed to use WebUSB instead of Trezor Bridge?

**Comment by Hannsek** [comment]
WebUSB should now work in both @trezor/connect-web and @trezor/connect-webextension. 

It still does not yet work in @trezor/connect-web when iframe.html cannot be injected into 3rd party application. cc @mroz22

**Comment by mroz22** [comment]
yes
