### ISSUE TITLE
Connect tests: missing fixtures

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#4867]
https://github.com/trezor/trezor-firmware/blob/master/tests/device_tests/test_msg_lisk_getpublickey.py?rgh-link-date=2020-06-26T08%3A23%3A37Z

https://github.com/trezor/trezor-firmware/blob/master/tests/device_tests/test_msg_binance_get_public_key.py?rgh-link-date=2020-06-26T08%3A22%3A35Z

https://github.com/trezor/trezor-firmware/blob/master/tests/device_tests/test_msg_binance_get_address.py?rgh-link-date=2020-06-26T08%3A22%3A07Z

**Comment by tsusanka** [comment]
@mroz22 is this still relevant?

**Comment by hynek-jina** [comment]
Not relevant anymore...
