### ISSUE TITLE
Connect: Implement trezor-address-validator lib

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#4871]
Intention is to have compatible address validation with @trezor/trezor-suite 
Currently few address types are incorrectly validated as `false`

examples which should be valid:
BTC `BC1SW50QA3JX3S`
BTC `bc1pw508d6qejxtdg4y5r3zarvary0c5xw7kw508d6qejxtdg4y5r3zarvary0c5xw7k7grplx`

**Comment by matejkriz** [comment]
this should be resolved as part of this https://github.com/trezor/trezor-suite/issues/4977, right?

**Comment by tsusanka** [comment]
Seems so. Please reopen if that is not the case.

**Comment by matejkriz** [comment]
adding a note to the new issue about the unsupported address types then...
