### ISSUE TITLE
Connect popup misrecognizes Model T as Trezor One

### ISSUE THREAD

**Issue by jafri** [trezor/trezor-suite#4873]
I am trying to log in with a model T on https://bloks.io, and I get this error

![image](https://user-images.githubusercontent.com/13677357/92817797-37770100-f384-11ea-9209-1ea543954975.png)

The relevant call is `TrezorConnect.eosGetPublicKey`

Funnily enough, if I plug in a model one it works

**Comment by tsusanka** [comment]
@bosomt please retest if this still occurs.

**Comment by bosomt** [comment]
**QA OK**

https://trezor.io/coins/#EOS

**T1 latest FW [legacy/v1.10.5]**

Connect: Trezor One not supported

**TT latest fw [core/v2.4.3]**

Connect: Device connected to blocks wallet as expected
