### ISSUE TITLE
Passphrase sometimes insertable only in the browser

### ISSUE THREAD

**Issue by refi93** [trezor/trezor-suite#4874]
Issue: The prompt to insert the passphrase in trezor connect  sometimes omits the option to insert the passphrase on the device as can be seen below:

![device](https://user-images.githubusercontent.com/4980147/94539120-1e57c680-0245-11eb-8620-ef261949a397.png)

A repeated attempt usually results in the option appearing again as can be seen here:

![device2](https://user-images.githubusercontent.com/4980147/94539128-20218a00-0245-11eb-8829-a03122f7c17d.png)

I was able to reproduce it also in incognito mode and both Chrome 85.0.4183.102 and Firefox 81.0 browser on Ubuntu 20.04, trezord version 2.0.27 . I didn't observe any specific pattern, it seems to happen at random, in my case around 1 in 5 attempts results in the missing button. It does not seem to be related to the coin either - I was able to replicate it both in Adalite for Cardano and Myetherwallet. I tried the latest released version of trezor connect (8.1.14) with Adalite locally and MEW seems to be updated to that version already

I tried it with Trezor Model T, fw version 2.3.3

**Comment by tsusanka** [comment]
@STew790 plese retest if this issue still occurs.

**Comment by STew790** [comment]
I tried about 10-15 times on MEW and on MyCrypto as well and it always showed me the button to enter the passphrase on device. 

I tried Chrome (98.0.4758.80 ) as well as FF (96.0.3). 
Device is Trezor Model T (2.4.3)


@refi93 Is this issue still persisting for you?
