### ISSUE TITLE
Connect pop-up window does not show up

### ISSUE THREAD

**Issue by akhekade** [trezor/trezor-suite#4877]
There are a few scenarios when Pop-up window does not show up (without any error messages or warning)
1. When there is not enough Gas to pay tx-fee
2. When the popup windows are blocked (nothing you can do except add a message to enable pop-ups)
3. In some cases on Firefox even when pop-ups are enabled.

**Comment by Hannsek** [comment]
🤔wondering if this is done. I don’t think so…
