### ISSUE TITLE
Connect popup loading indefinitely

### ISSUE THREAD

**Issue by bradwood** [trezor/trezor-suite#4878]
Hi,

https://connect.trezor.io/8/popup.html#loading loading indefinetely -- this is after my trezor connects fine via trezord to wallet.trezor.io...

I'm on Manjaro (arch linux) and Brave, if that helps.

Trying to connect to adalite.io, but no ADA-based wallet seems to work with Trezor right now.

thanks in advance for any help

**Comment by Defnewbe** [comment]
I am also having problems with connect.trezor.io/8/popup.html#. It keeps spinning forever when I try to connect the trezor. It works fine with trezor suite, but won't let me connect to the apps that worked just fine yesterday. Any suggestions? Thanks

**Comment by dantzler** [comment]
I am also having problems with connect.trezor.io/8/popup.html#. It keeps spinning forever when I try to connect the trezor. It works fine with trezor suite.

ETA:    WORKING NOW !
I was using Firefox when I experienced this issue. I switched to Chromium / incognito and got it working. Hope this helps anyone else that may be experiencing this issue.

Thank you.

**Comment by antoniohs** [comment]
Same problem here in Windows 11, with Brave, Chrome and Firefox, no ad blockers and shields disabled.

**Comment by sime** [comment]
@antoniohs Couple of questions:

* Which device do you have
* Which site are you using?
* What action are you performing on that site?
* Which version of Trezor Bridge do you have (find it by visiting: http://127.0.0.1:21325/status/)
* Are you using a passphrase protected wallet? If not, disable passphrase in Trezor Suite settings and try again.

**Comment by antoniohs** [comment]
> @antoniohs Couple of questions:
> 
> * Which device do you have

Trezor T

> * Which site are you using?

Eternl.io

> * What action are you performing on that site?

Adding a wallet by pairing the hardware wallet

> * Which version of Trezor Bridge do you have (find it by visiting: http://127.0.0.1:21325/status/)

Version: 2.0.27

> * Are you using a passphrase protected wallet? If not, disable passphrase in Trezor Suite settings and try again.

No passphrase.

**Comment by sime** [comment]
Thanks for the getting back to me!

> > * Which version of Trezor Bridge do you have (find it by visiting: http://127.0.0.1:21325/status/)
> 
> Version: 2.0.27

That is the version of Trezor Bridge when you install it standalone. If you run Trezor Suite, it has a newer version of Trezor Bridge bundled in. Please try that, you will see version 2.0.31.

> > * Are you using a passphrase protected wallet? If not, disable passphrase in Trezor Suite settings and try again.
> 
> No passphrase.

Please disable passphrase in Trezor Suite, that way we can eliminate that is causing the spinner.

![Screenshot 2022-07-20 at 13 57 08](https://user-images.githubusercontent.com/216917/179976111-01fe10cb-1686-446e-bc8b-c156f59435aa.png)

Are you clicking something in Trezor Connect before the endless spinner starts, or is it spinner on launch?

**Comment by antoniohs** [comment]
Running the trezor suite while I try to connect in Eternl.io has the same result.

Is spinner on launch, and as I said, I do not have a passphrase.

**Comment by sime** [comment]
@antoniohs Can you see if you have Total Cookie Protection on in Firefox for Eternl.io

Related to https://github.com/trezor/trezor-suite/issues/5644

**Comment by antoniohs** [comment]
Just standard, nothing special. Firefox is almost in mint condition, xbrowsersync and bitwarden extensions, nothing else.

**Comment by sime** [comment]
@antoniohs Turning off 'Enhanced Tracking Protection' for Eternl.io makes no difference?

**Comment by antoniohs** [comment]
@sime that did the trick!

Thanks a lot, I appreciate your help!

Had to turn it completely off.

**Comment by melroy89** [comment]
Adalite.io is still not working using Trezor Model T + Firefox actually. uBlock orgin is disabled. Pop-ups are allowed. I'm running Trezor Bridge v2.0.30 (according to http://127.0.0.1:21325/status/). trezord process is running.

The Trezor device is showing using `lsusb` command, I also do have the required udev rules present in my system. https://connect.trezor.io/8/popup.html# is just loading forever together with the https://adalite.io/ site.

Trezor is in UNlocked state. 

I'm using Linux Mint 20 (based on Ubuntu 20.04).

Trying later to access Trezor Suite, the Suite is saying the device is in incorrect state. That problem is resolved by reconnecting the physical device. Adalite + Trezor problem is not fixed.

**Comment by sime** [comment]
@danger89 Does it work if you disable 'Enhanced Tracking Protection' like in https://github.com/trezor/trezor-suite/issues/5644

**Comment by Rickk137** [comment]
I had the same issue with Brave
Disabling ``Block fingerprinting`` and ``Block cookies`` in Settings -> Shields Fixed this issue.

**Comment by prusnak** [comment]
All in all this seems like an issue that is not caused by Connect, so let's close it.

Solutions to this problem:
* disable ad blockers
* try using the Incognito mode
* Firefox: disable `Enhanced Tracking Protection`
* Brave: disable `Block fingerprinting` and `Block cookies` in `Settings -> Shields`

**Comment by melroy89** [comment]
> issue that is not caused by Connect

But can I propose one idea?

Instead of loading indefinitely. Can't you detect some of the issues? Or at least create a timeout...

And give the user a message what they need to change in the browser. Or a link to your documentation. Instead of people searching on github issues.

**Comment by Hannsek** [comment]
https://github.com/trezor/trezor-suite/issues/6129

**Comment by Hannsek** [comment]
https://github.com/trezor/trezor-suite/issues/6129

**Comment by sime** [comment]
We have a hard to track race condition floating around in Trezor Connect happening in Firefox and Connect. Re-opening as its still being tracked.

**Comment by runpure** [comment]
Hello all 

I have the same problem on Chrome

disabled ad blockers
doesnt work on incognito
Chrome disabled enhanced protection
disabled 3rd party cookies

any ideas is much appreciated

**Comment by Hannsek** [comment]
@runpure Are you using Connect v8 or v9. You would know acording to address:  `connect.trezor.io/8/popup.html#`.

**Comment by runpure** [comment]
@Hannsek https://connect.trezor.io/8/popup.html#loading 

Just for context, it was working fine all these while (years) and the issue only happened 4-5 days ago

**Comment by Hannsek** [comment]
Just to be clear, `Allow all cookies` is enabled, right?

**Comment by runpure** [comment]
Yes thats right, allow all cookies, and I tried deny 3rd party cookies, etc

I didnt change any settings and suddenly one day I got the loading screen of death

**Comment by runpure** [comment]
Am on macbook pro

Which device do you have
Model T

Which site are you using?
gmx.io

What action are you performing on that site?
compounding earn (when I close the loading screen of death, gmx.io has an error screen that says "Error: Iframe timeout")

Which version of Trezor Bridge do you have (find it by visiting: http://127.0.0.1:21325/status/)
Version: 2.0.32 (rev 9aa6576)

Are you using a passphrase protected wallet? If not, disable passphrase in Trezor Suite settings and try again.
Yes

**Comment by sime** [comment]
@runpure One troubleshooting strategy is to try a different extension.

In my understanding, [Enkrypt](http://enkrypt.com/) is compatible with MetaMask, and has the latest integration of Trezor Connect (v9). I haven't tested it thoroughly, but I haven't hit any spinners of death (yet).

**Comment by runpure** [comment]
Any other ideas @Hannsek?

**Comment by Hannsek** [comment]
You can try Firefox.

**Comment by runpure** [comment]
Tried on brave and works fine

**Comment by mkalen** [comment]
Reproduced via https://accountviewer.stellar.org/

Firefox Enhanced Tracking Protection (ETP) was the root cause. If ETP is on, Connect popup spins forever. If ETP is off Connect works fine (even works fine if all of Adblock Plus, Startpage Privacy Protection and MetaMask are active - as long as ETP is off). NB; ETP needs to be disabled on the source domain, i.e. accountviewer.stellar.org.

UI_EVENT of type "popup-handshake" does not occur after iframe-call "Core handle message in core" if ETP is on.

Since Firefox ETP is now the suggested default, it would be great if this could be at least detected in Trezor Connect, to hint the user to turn it off. Thanks.

Site: https://accountviewer.stellar.org/
Connect popup: https://connect.trezor.io/8/popup.html#

O/S: Windows 11, Version 22H2 (22621.963)
Browser: Firefox 108.0.2 (64-bit) (same issue on 108.0.1 before upgrade)
Trezor: Model T
Bridge: Version: 2.0.27 (http://127.0.0.1:21325/status/)
USB devices:
	USB\VID_1209&PID_53C1&MI_01\6&22E55329&C&0001	(HID)
	HID\VID_1209&PID_53C1&MI_01\7&848ADD0&0&0000	(FIDO HID)
	USB\VID_1209&PID_53C1\4F3FE6B97B52ED1FFB286761	(USB composite)

Trace using window.__TREZOR_CONNECT_SRC='https://connect.trezor.io/8/'; for both cases:

1. Firefox ETP active, Connect popup spins indefinately / failure:
![Trezor_connect_failure](https://user-images.githubusercontent.com/2629399/210880482-9d2aa030-d17d-4656-bdc3-5f5c18f4b057.png)

2. Firefox ETP off, Connect popup works OK:
![Trezor_connect_OK](https://user-images.githubusercontent.com/2629399/210880539-37844dde-8b4a-435b-8d65-ca6cb4dec01a.png)

**Comment by sime** [comment]
> Since Firefox ETP is now the suggested default, it would be great if this could be at least detected in Trezor Connect, to hint the user to turn it off. Thanks.

We have this in Connect v9 already.

Related issue: https://github.com/trezor/trezor-suite/issues/5644

**Comment by prusnak** [comment]
> Reproduced via https://accountviewer.stellar.org/

Fix in https://github.com/stellar/account-viewer-v2/pull/391 since September

**Comment by sime** [comment]
> > Reproduced via https://accountviewer.stellar.org/
> 
> Fix in [stellar/account-viewer-v2#391](https://github.com/stellar/account-viewer-v2/pull/391) since September

Not merged :(

**Comment by mkalen** [comment]
> > Since Firefox ETP is now the suggested default, it would be great if this could be at least detected in Trezor Connect, to hint the user to turn it off. Thanks.
> 
> We have this in Connect v9 already.
> 
> Related issue: #5644

Great! Thanks for the updates. I will turn upstream and see if Stellar account viewer can get the upgrade to Connect v9 merged.

**Comment by mkalen** [comment]
> > > Reproduced via https://accountviewer.stellar.org/
> > 
> > 
> > Fix in [stellar/account-viewer-v2#391](https://github.com/stellar/account-viewer-v2/pull/391) since September
> 
> Not merged :(

It's fixed now in Stellar Account Viewer (stellar/account-viewer-v2#391, the PR was updated and then merged). Verified at accountviewer.stellar.org that it's now using Trezor Connect v9 on the live site. Connect now gives me a hint how to solve the problem if I have Firefox enhanced tracking protection turned on. Much more user-friendly with v9. Thanks.

**Comment by Hannsek** [comment]
https://github.com/trezor/trezor-suite/issues/8044

**Comment by sime** [comment]
Next version of MetaMask will include Trezor Connect v9. https://github.com/MetaMask/metamask-extension/pull/18302
Next minor release of Trezor Connect will include a work around for Firefox

**Comment by Hannsek** [comment]
I don’t think this is solved for Chrome?

**Comment by Hannsek** [comment]
Connect v8 is now deprecated. All developers should update to v9.

**Comment by qerphrail** [comment]
Guys, this problem appeared again today. Does it have anything to do with the security incident on Trezor X/Twitter account?
The same error that occurred is occurring again: the pop-up window disappears out of nowhere. It is usually opened in a new window, then closed and opened among the other browser tabs, and then compulsorily closed.
Several swap attempts on different DEX's. The same failure occurs in both. I have already restarted Chrome and the PC. It does not solve.
Chrome updated: Version 123.0.6312.58 (Official Build) (64-bit)
Metamask updated: 11.12.2
Please, can you help?

**Comment by sime** [comment]
MetaMask recently merged an update to the popup, but it didn't make the recent release. https://github.com/MetaMask/metamask-extension/pull/23164

**Comment by qerphrail** [comment]
> MetaMask recently merged an update to the popup, but it didn't make the recent release. [MetaMask/metamask-extension#23164](https://github.com/MetaMask/metamask-extension/pull/23164)

Didn't Connect v9 solve this problem?

**Comment by sime** [comment]
Some, but not all of them. :(

**Comment by qerphrail** [comment]
It was going well until yesterday. I thought it might be a browser or Metamask update. Apparently that's not it, right?
Please help me with a solution. I have my funds "blocked" because Trezor does not allow me to approve transactions and I need to transact urgently.

**Comment by sime** [comment]
@jvnovo I can suggest you try different browsers, also to troubleshoot, remove any additional extensions.

Secondly, use [Rabby](https://rabby.io/) in place of MetaMask. Rabby is also on Connect v9.

**Comment by sime** [comment]
@jvnovo Also, have this tab open: https://connect.trezor.io/9/log.html

When the popup isn't behaving, grab the log.

**Comment by Hannsek** [comment]
@jvnovo
1. Does Trezor Suite Web run during the signing on Metamask?
2. Is Trezor Bridge (`trezord`) running on your computer

**Comment by qerphrail** [comment]
> @jvnovo
> 
> 1. Does Trezor Suite Web run during the signing on Metamask?
> 2. Is Trezor Bridge (`trezord`) running on your computer

@Hannsek 
1. No. I use the Trezor Suite App to update when necessary.
2. I don't know. How can I check? Note that I use the same PC I've always used and I haven't changed anything in the way I use the OS. Transactions were flowing well and out of nowhere this problem appeared again.

**Comment by Hannsek** [comment]
Thanks, so does Trezor Suite App run during the signing on Metamask?

Regarding the standalone running bridge you would have a running `trezord` process on your computer.

Also please follow the above instruction about grabbing a log, then we can try to debug it.
