### ISSUE TITLE
Improve copy in Connect popup

### ISSUE THREAD

**Issue by johnbailon** [trezor/trezor-suite#4879]
When initiating a `signMessage` command, the popup displays the following information:

<img width="640" alt="" src="https://user-images.githubusercontent.com/266389/115216628-43574c80-a137-11eb-8bdc-fa87ef885017.png">

```
- Read public keys from Trezor device
- Prepare Trezor device for transaction and data signing
```

Would it be possible to change the second line to only say _**Prepare Trezor device for message signing**_ or something to that effect? It would inform end users the actual scope of the permission they are allowing, which is to say, they are not going to sign any spend transactions.

**Comment by Hannsek** [comment]
This would be tackled with the upcoming connect popup redesign. Closing this for now.
