### ISSUE TITLE
Typing of the redux store allows to use props that doesn't exist

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#488]
line `state.propThatDoesntExist` should throw a ts error (right?!)  just as it throws in case of react components. If it did work it would allow us to catch some errors during type check such as using a param of the router that doesn't exist.

_(don't mind the error on the screenshot as it is related to spellchecker)_
![Screenshot 2019-09-05 at 11 37 18](https://user-images.githubusercontent.com/6961901/64352865-093a4500-cffd-11e9-8437-6e8f7c2673a2.png)

example with component:
![Screenshot 2019-09-05 at 11 36 44](https://user-images.githubusercontent.com/6961901/64352971-34bd2f80-cffd-11e9-9bc6-7138b1add36a.png)

**Comment by mroz22** [comment]
fixed as side effect of #480
