### ISSUE TITLE
Popup auto closes when trying to type in passphrase for hidden wallet.

### ISSUE THREAD

**Issue by patoshii** [trezor/trezor-suite#4883]
I clicked the checkbox where it asks to remember my option, but it seems to now not let me type in any passphrase in the popup when using Trezor with with other applications. I tried uninstalling trezor bridge and also removed all cookies and even tried another browser. It still just auto closes the popup when it loads.

**Comment by tsusanka** [comment]
This is an interesting case: if you remember hidden wallet in connect popup, you still need to be prompted for the passphrase.

**Comment by nopty** [comment]
> This is an interesting case: if you remember hidden wallet in connect popup, you still need to be prompted for the passphrase.

Hey did you manage to fix the popup disappearing issue?

**Comment by Hannsek** [comment]
@nopty Does it still happen to you?

**Comment by nopty** [comment]
> @nopty Does it still happen to you?

Yes, do you have solution

**Comment by nopty** [comment]
@Hannsek yes do you have solution?

**Comment by Hannsek** [comment]
Unfortunately not yet.

Can you please provide more info. Which wallet do you use, what device with which fw do you use, which browser, version of the browser, ...

**Comment by nopty** [comment]
@Hannsek thank you
I use: 
metamask (Version: 1 1 . 4 . 1)
firefox (115.5.0esr (64-bit))
chrome (Version 109.0.5414.120 (Official Build) (64-bit))
MS edge (Version 109.0.1518.140 (Official build) (64-bit))

**Comment by nopty** [comment]
@Hannsek when i tried MS EDGE for first time, trezor worked every time with metamask...then, the next day trezor started the same issue of trezor connect V9  window closing automatically

**Comment by nopty** [comment]
@Hannsek do need to change safety checks to "prompt" or downgrading trezor firmware? some people say it solved their problem....

**Comment by Hannsek** [comment]
> @Hannsek do need to change safety checks to "prompt" or downgrading trezor firmware? some people say it solved their problem….

Do not change safety checks if you don't know what do you do. This won't help.

Also MS Egde is not supported.

**Comment by nopty** [comment]
@Hannsek after all this years with this issue, has anyone narrowed the likely issue? i would like to investigate this

**Comment by Hannsek** [comment]
I believe this should be solved by now.
