### ISSUE TITLE
Cardano maintanance on 2022/Q2

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#4885]
Consider removing some of the cardano backwards compatibility code branches future. Aprox Q1/Q2 2022? 

https://github.com/trezor/connect/blob/0114078d4cd31abd0a23f530607340f67f6c2a19/src/js/core/methods/CardanoGetAddress.js#L186

https://github.com/trezor/connect/blob/0114078d4cd31abd0a23f530607340f67f6c2a19/src/js/core/methods/CardanoSignTransaction.js#L373

todo: add link to relevant code once this is merged https://github.com/trezor/connect/pull/933

**Comment by tsusanka** [comment]
@mroz22 as we are touching Cardano currently we might do this one along?
