### ISSUE TITLE
Connect popup fails in MetaMask?

### ISSUE THREAD

**Issue by bitnoah** [trezor/trezor-suite#4888]
I have a Trezor one. The other day, i was doing a transaction on Metamask but it failed because on the pop-up, trezor failed to connect. I tried connecting using a different USB port; fail. Then  I changed the cable and tried again, fail. I restarted the computer several times after clearing the cache, fail. I updated the firmware and tried to recover, fail as the Trezor cannot connect.

I updated Trezor Bridge and tried for no avail. It keeps asking me to connect the Trezor and stuck there.

Please how may I solve the issue?

**Comment by Hannsek** [comment]
We can probably close this @mroz22, right?
