### ISSUE TITLE
PathPaymentStrictSend in Connect not working (Stellar)

### ISSUE THREAD

**Issue by earrietadev** [trezor/trezor-suite#4890]
## Description
When trying to do a PathPaymentStrictSend operation it fails because we're not parsing the parameters "destMin" and "sendAmount" into integers.

## Steps to reproduce
Generate a PathPaymentStrictSend in the Stellar Laboratory and try to sign it with a Trezor Hardware Wallet.

## Additional info
Browser: Chrome, Brave and Firefox
trezor-connect: 8.2.4-extended
Device: Trezor One (fw 1.10.4)

## How to solve
Updating line https://github.com/trezor/connect/blob/6dfb514f2c4de2b7f93e04965572b22918a0fc1d/src/js/plugins/stellar/plugin.js#L103 and including both 'destMin' and 'sendAmount' fix the issue. It will end up like this:
```
const amounts = ['amount', 'sendMax', 'destAmount', 'startingBalance', 'limit', 'buyAmount', 'destMin', 'sendAmount'];
```

PS: I tried to do the Pull request with the fix but it didn't allowed me to do it

**Comment by tsusanka** [comment]
Should be closed by https://github.com/trezor/trezor-suite/pull/5450.
