### ISSUE TITLE
VPN issue with Trezor Connect

### ISSUE THREAD

**Issue by coinartists** [trezor/trezor-suite#4892]
I am not sure this is an issue specific to the application itself but I didn't know a better place to report it. When I try to sign a transaction, the very first popup that requires me to insert my PIN always fails behind a VPN, as in the popup opens and closes immediately. Popups where I just need to confirm directly in the hw (already loaded my PIN) work fine.

**Comment by tsusanka** [comment]
Closing for no response, let us know if this issue still persists.
