### ISSUE TITLE
Connect legacy tests results

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#4893]
We have just started running more tests against model One and doing so we have found some suspicious observations . I would like to determine if these results are expected or possibly bugs in firmware. 

decred - 1.10.6 
https://github.com/trezor/connect/blob/1e3e4648f7b92df0c1b10bf0fc1d18b4cd4ebf54/tests/__fixtures__/signTransactionDecred.js#L106-L108

decred 1.10.6
https://github.com/trezor/connect/blob/1e3e4648f7b92df0c1b10bf0fc1d18b4cd4ebf54/tests/__fixtures__/signTransactionDecred.js#L152-L154

the same test returns different results with fw < 1.10.6
https://github.com/trezor/connect/blob/1e3e4648f7b92df0c1b10bf0fc1d18b4cd4ebf54/tests/__fixtures__/signTransactionDecred.js#L195-L208

btc external outputs 
https://github.com/trezor/connect/blob/1e3e4648f7b92df0c1b10bf0fc1d18b4cd4ebf54/tests/__fixtures__/signTransactionExternal.js#L20-L23

https://github.com/trezor/connect/blob/1e3e4648f7b92df0c1b10bf0fc1d18b4cd4ebf54/tests/__fixtures__/signTransactionExternal.js#L85-L88

https://github.com/trezor/connect/blob/1e3e4648f7b92df0c1b10bf0fc1d18b4cd4ebf54/tests/__fixtures__/signTransactionExternal.js#L139-L142

https://github.com/trezor/connect/blob/1e3e4648f7b92df0c1b10bf0fc1d18b4cd4ebf54/tests/__fixtures__/signTransactionExternal.js#L188-L191

https://github.com/trezor/connect/blob/1e3e4648f7b92df0c1b10bf0fc1d18b4cd4ebf54/tests/__fixtures__/signTransactionExternal.js#L232-235

**Comment by matejcik** [comment]
> btc external outputs

external outputs were unsupported on T1 until recently (1.11.1) so the failures are expected
