### ISSUE TITLE
Connect API - Could not communicate with the source website

### ISSUE THREAD

**Issue by thaarok** [trezor/trezor-suite#4896]
I am trying to follow the guide how to use the Connect API, but when the test page invokes the TrezorConnect method, the connect.trezor.io produce following error:

> Could not communicate with the source website
> The source website was not able to communicate with Trezor Connect. This can be caused by pop-up or ad blockers. Please ensure all trezor.io domains are allowed.

The output of the `TrezorConnect.ethereumGetAddress` call is `{ error: "Iframe timeout", code: "Init_IframeTimeout" }`

I have tried to add CORS header to my web page:
```
Access-Control-Allow-Origin: *
```
However it does not help.

How I am supposed to allow the trezor.io domains?

Can be the Trezor Connect requirements description added into the documentation?

Thanks!

**Comment by prusnak** [comment]
Relevant part of the error message:

> This can be caused by pop-up or ad blockers.

Disable ad blockers, try different browser, try opening your website in incognito mode (where are extensions are disabled), etc.

**Comment by thaarok** [comment]
I am having the same error when using Firefox or Chromium with no extensions, with enabled pop-ups.
I use Trezor official apps (like https://suite.trezor.io/web/ ) in the same browsers successfully.
I believe there must be some requirement for my app, which I have not found in the doc - how is the source website supposed to communicate with Trezor connect? I dont see any CORS or other error in the web console of my web app or in the TrezorConnect tab...

I believe the key will be this part of the error message:
> Please ensure all trezor.io domains are allowed.

However I have not found how/where should the domains be allowed... (Access-Control-Allow-Origin header doesnt seems to be sufficient...)

My testing app for reference:
http://test.tharok.cz/trezor.php

**Comment by thaarok** [comment]
I have figured it out - it have not work, because I was calling the `TrezorConnect.ethereumGetAddress` method too soon after the page load. It was sufficient to replace:
```
async function test() {
    const result = await TrezorConnect.ethereumGetAddress({ path: "m/44'/60'/0'/0/0" });
}
test();
```
by:
```
window.onload = test;
```
Now it works just fine, thanks and sorry for spam!

Note: No CORS header was necessary at all.
