### ISSUE TITLE
Remove passphrase setting

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#4903]
**User story**
As a newly onboarded Trezor user
I do not want to be presented with a passphrase toggle
So that new concepts are not added to my cognitive load

As an old school Trezor user
I do not want to be presented with a passphrase toggle
So that my cognitive load is reduced

**Background**
Passphrases are a source of friction and a small users actually use a hidden wallet

**Comment by sime** [comment]
I believe it is a language issue. Choosing 'Standard Wallet - No passphrase', followed by navigating to device settings shows passphrase as enabled. In this case I expect it to be disabled.

https://user-images.githubusercontent.com/216917/152957072-8efeba1f-963f-43cf-aacf-f30b77d3dcf3.mp4

**Comment by tsusanka** [comment]
A bit of context: in wallet.trezor.io you had to enable passphrase in settings first to work with it. In Suite we have decided to alter this behaviour and we turn on the passphrase every time during onboarding even if you won't use it. The rational is that we can then onboard you to passphrases easily and work with the whole Hidden wallets concept.

We could enable passphrase on clicking on Add new hidden wallet for the first time but that would trigger a dialog on Trezor (it is not the case when you set it during onboarding). So we decided to simplify this.

What I am wondering though is whether it makes sense to show this setting in Suite at all. Is it a reasonable use-case to turn the passphrase off? We could show it only if passphrase is off (usually users coming from old wallet or other places) so you can turn it on, but not the other way around. For new users in Suite they do not really need this setting and apparently it is kind of confusing. What do you think?

**Comment by tsusanka** [comment]
@stepmes have you encountered this in some user feedback?

**Comment by sime** [comment]
> We could enable passphrase on clicking on Add new hidden wallet for the first time but that would trigger a dialog on Trezor (it is not the case when you set it during onboarding).

Thanks for confirming this, I noticed the difference of enabling passphrase manually (with on device confirmation) and during the onboarding (no confirmation).

> What I am wondering though is whether it makes sense to show this setting in Suite at all. Is it a reasonable use-case to turn the passphrase off? We could show it only if passphrase is off (usually users coming from old wallet or other places) so you can turn it on, but not the other way around. For new users in Suite they do not really need this setting and apparently it is kind of confusing. What do you think?

Yes! This sounds like a smart default or chance to drop an [unnecessary setting](https://signalvnoise.com/archives2/getting_real_the_problem_with_preferences_interface_design_and_the_customer_experience.php)!

Tableau says 30% of users have it disabled, so we need to prepare a migration strategy. I see the options as:
* (as suggested) Leave the setting visible for non passphrase users. UX question: what happens after it is enabled? Disappears immediately or the next time they come back to the suite
* "Force" the user to enable it with a suite update
* "Silently" enable it with firmware update

**Comment by hynek-jina** [comment]
Another user story may be to mask the existence of a hidden wallet to a potential attacker by disabling the ability to enter a passphrase.

**Comment by sime** [comment]
Updated the title and initial description of this issue to match the discussion. i.e. removing the passphrase option

**Comment by hynek-jina** [comment]
Let’s discuss it as a part of bigger [UX of passphrase](https://www.notion.so/satoshilabs/Passphrase-flow-9f11a6abbb6f47e1b2bf1922d5c5419e) topic. I’ll close this issue and let’s reopen it if needed once we know what is the best solution.
