### ISSUE TITLE
Anchor links are not highlighted on repeated clicks

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4915]
**Describe the bug**
Anchor link works just fine but if I repeatedly click on an action (because I am dull or blind) it is not highlighted more, it even disappears. Usually it is solved in a way that the highlighted piece is animated a bit or it at least stays highlighted but I do not think it should just disappear.

**Info:**
 - Remembered Wallet: no
 - Suite Version: EAP v22.2.1 https://github.com/trezor/trezor-suite/commit/520802b8052d558de9c5f0ee55f9151ea5122eb4
 - OS: macOS 12.1

**How to reproduce**
1. Launch Suite and click on the Tor icon repeatedly
2. The anchor is highlighted only once but not repeatedly

**Expected behavior**
The anchor is highlighted more.

**Screenshots**
I am clicking on Tor once and it gets highlighted but on further clicks it is not:

![a](https://user-images.githubusercontent.com/1835345/153236499-d8c58024-04ec-4701-ad69-6627188320ec.gif)

**Comment by bosomt** [comment]
**QA OK **

**Info:**
 - Suite version: web 22.5.0 (bf0e4020dc1344c179501fcb5f57d9c4039c8bf0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.0 regular (revision fd4f8601cf73c5744978f0e8c0aa43d863032a37)
 - Transport: bridge 2.0.31
