### ISSUE TITLE
Broken Firmware Detected - Cannot Install Firmware on new Trezor Model One

### ISSUE THREAD

**Issue by MustardLighthouse** [trezor/trezor-suite#4929]
I have a new Trezor model One with Bootloader 1.10.0. I cannot install any firmware. I have tried this with the Web wallet, different computers, browsers and cables. I have another Trezor One which functions normally.

**Info:**
 - Remembered Wallet: no
 - Suite Version: App 22.1.1.15213
 - OS: Mac OS , version 12.2
 - Bridge: 2.0.27
 - Firmware Version: N/A

Starting Fresh:

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/21340550/153513387-3d1cedd9-7e4f-40ef-884d-c067af416444.png">

Trezor indicated firmware install successful. Rebooting in 3.2.1.... Reboots to a screen which reads: Broken Firmware Detected Unplug your Trezor, reinstall firmware. The suite will not advance from here:

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/21340550/153513754-09750820-c7dc-446f-aa1c-f061f4d9dc69.png">

No computer with recognize the device after this point, unless I am in boot loader mode. 

I am able to enter bootloader mode, factory reset the Trezor and reproduce this issue. I have tried installing old firmwares, custom firmwares. Nothing works at this point.

Thanks!

**Comment by prusnak** [comment]
Please contact our support via https://trezor.io/support/
