### ISSUE TITLE
Disabling passphrase in settings shows a warning that you need to enable it again in order to use your device

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#4933]
**Describe the bug**
If you disable a passphrase in the settings and go to your Accounts, you will see a prompt to enable a passphrase in order to use your device again, which is meaningless if you don't use a passphrase.

**Steps to reproduce:**
1. Start Suite
2. Connect your device
3. Go to Settings and disable passphrase
4. Go to your Accounts and you will see a yellow prompt

**Info:**
 - Suite version: desktop 22.2.1 (520802b8052d558de9c5f0ee55f9151ea5122eb4)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.2.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular

**Expected result:**
There shouldn't be any prompt to enable your passphrase because it shouldn't be needed in order to use the device

**Actual result:**
A prompt to enable your passphrase in order to use your device appears when you disable your passphrase.

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/153629041-4a6c48f2-15ee-4e5d-b88a-c85d83c7371e.png)

**Comment by zaplmi** [comment]
Issue still persists:

info:
Suite version 22.4.3 (web)
FW 2.4.3
NixOS

Steps to reproduce:
connect your device (that has passphrase feature enabled) in Trezor Suite
choose Standard wallet
go to device setting and turn the passphrase feature off
go back to accounts and click on send (any account with balance):

![image](https://user-images.githubusercontent.com/91535734/165795171-4eeadda4-8886-41f4-aa36-0eafbb40a592.png)

I am not able to sign any transaction even from Standard wallet (review and send is grayed out)
After the page is refreshed or passphrase is enabled I am able to sign.

When proceeded to get fresh receiving address (Standard wallet again) following pop-up window appears:

![image](https://user-images.githubusercontent.com/91535734/165795694-ca706e5e-4af6-4ba0-ac1a-b135f8ce0bc6.png)

Again, after refreshing or enabling passphrase I am able to get fresh address without getting the dialog window.

**Comment by tsusanka** [comment]
As I have mentioned in https://github.com/trezor/trezor-suite/issues/4903 I am not sure it makes sense to offer this setting at all. Anyone has a good reason to keep it? I would remove it unless anyone objects.

**Comment by hynek-jina** [comment]
@tsusanka 
I would even say it's counterproductive. It reveals that the user is using a passphrase. So I agree to remove it.

**Comment by matejkriz** [comment]
We should probably keep the option to enable it again for those that disabled it previously.

**Comment by hynek-jina** [comment]
You can add the passphrase anytime.. Is there any benefit of this?

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.9.0 (625ccb6675c533896b97651c60fb95752325b0c3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
