### ISSUE TITLE
Favicon does not always change accordingly to macOS theme

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4934]
**Describe the bug**
Fav icon does not always change accordingly to macOS theme.
See screenshot, it does not occur always but it happens from time to time.
I'm not sure if this occurs only on macOS.

**Steps to reproduce:**
1. Load web version of suite
2. Switch between dark and light theme
3. Observe favicon

**Info:**
 - Suite version: web 22.3.0 (3d468f5975ac59b23a24096b632252ff92567243)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Screenshots:**
<img width="278" alt="Screenshot 2022-02-12 at 7 34 57" src="https://user-images.githubusercontent.com/31506317/153700233-e0ce1dc4-8bca-4ad1-b69b-6794c2931597.png">

<img width="363" alt="Screenshot 2022-02-12 at 7 33 37" src="https://user-images.githubusercontent.com/31506317/153700234-cf20d28e-8513-489c-a65a-d69ede0e5736.png">

<img width="332" alt="Screenshot 2022-02-12 at 7 33 30" src="https://user-images.githubusercontent.com/31506317/153700247-ebd305fc-8c34-4542-b4e3-076edbd72a47.png">

<img width="239" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/153700265-f0eb6c3b-7552-441b-a7cb-752483efce28.png">

**Comment by ondracja** [comment]
I was able to reproduce the issue on multiple browsers (Chromium, Brave, Firefox)

**Info:**

- intel Mac, Big Sur 11.6.2 (20G314) with dark theme set by OS
- Chromium Version 95.0.4608.0 (Developer Build) (x86_64)
- Brave Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) (x86_64)
- FF 97.0 (64-bit)

**Comment by STew790** [comment]
**QA OK**
Favicon changes with the system theme

**Info:**
 - Suite version: web 22.8.0 (88d58010aa8986885ddbb5040feb3dd7e0334bee)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.1 regular 
 - Transport: WebUsbPlugin
