### ISSUE TITLE
CI: Separate deploy to dev and deploy to npm sections

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#4946]
- [x] create new rules for `npm-release` prefix
- [x] npm public release should be available only from prefixed branch
- [x] npm beta release should be available from any branch except `npm-release` (and maybe others?)
- [x] npm publish job should validate package.json version like in [trezor-connect](https://github.com/trezor/connect/blob/develop/.gitlab-ci.yml#L143)
- [x] update docs/releases/npm-release

**Comment by matejkriz** [comment]
- npm public release should be allowed from protected branch (develop?) only, to ensure that the published code is reviewed 
   -  on develop we probably can't check the commit message
   - we could create another protected branch e.g. `npm-release` / `release-npm` but maybe it's an overcomplication?

- we have to add `--dry-run` or `npm pack` to the process, to verify before each publish what files are to be released

**Comment by bosomt** [comment]
anything needed to be tested on QA side ?

**Comment by vdovhanych** [comment]
@bosomt not really. This is just a developer-facing feature.
