### ISSUE TITLE
Support 50 digit PIN codes for T1

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#4947]
## User story
As a T1 user
I want to protect my coins from a physical theft attack
So that my coins are safe if my T1 is stoleln

## Acceptance criteria
Given I set a pin
When I enter a 50 digit pin
And I press 'Enter pin'
And I should see 'Verifying pin'
And I enter the same 50 digit pin
And I press 'Enter pin'
And I should see 'Verifying...'
Then I should see 'PIN changed successfully'

## Background

Since [firmware 1.10.0](https://github.com/trezor/trezor-firmware/blob/master/legacy/firmware/CHANGELOG.md#1100-12th-may-2021) the T1 has supported 50 digit PIN codes. https://github.com/trezor/trezor-firmware/pull/1478

Current implementation limits the T1 PIN code length to 9 digits.

## Screenshots
![Screenshot 2022-02-15 at 19 01 41](https://user-images.githubusercontent.com/216917/154255918-f58fc359-d408-42f4-94f0-76380054f9af.png)
![Screenshot 2022-02-15 at 19 02 14](https://user-images.githubusercontent.com/216917/154255935-faf711d0-b561-4da4-ae9a-a6968cbd8d8a.png)

**Comment by tsusanka** [comment]
Duplicate of https://github.com/trezor/trezor-suite/issues/3737, we should close one of them

**Comment by sime** [comment]
Closing in favour of https://github.com/trezor/trezor-suite/issues/3737
