### ISSUE TITLE
Remove build date from "Update available" modal

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4949]
**Describe the bug**
We display build time instead of the release date under the changelog, which might be confusing to users as we usually release few days after the build. Let's remove the date. 

**Steps to reproduce:**
1. Launch older version of the app
2. See date under changelog in modal with title "Update available"

**Info:**
 - Suite version: desktop 22.2.1 (520802b8052d558de9c5f0ee55f9151ea5122eb4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.2.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900

**Screenshots:**
![image](https://user-images.githubusercontent.com/1835345/154279012-a8f82b01-7ec1-434d-a0f6-040b8ef51b48.png)

**Notes:**

**Comment by hynek-jina** [comment]
There is no clear benefit of this date.. Let's remove it.

**Comment by matejkriz** [comment]
closed by #5232

**Comment by STew790** [comment]
Will be tested together with the autoupdate.

**Comment by STew790** [comment]
**QA OK**
No build date is present in the auto-update modal.

![image](https://user-images.githubusercontent.com/48477147/167093633-2781a3e4-7104-47b6-b65e-b240f4e1d71d.png)
