### ISSUE TITLE
Asking for passphrase for every txn...

### ISSUE THREAD

**Issue by blackboxtrading** [trezor/trezor-suite#4952]
Starting sometime today, trezor + metamask stars to ask for passphrase every time I am sending a txn. It is pretty crazy. Previously it only asks once every time I connect trezor. Was there an update?

**Comment by prusnak** [comment]
Make sure you are on the latest version of Metamask and Trezor firmware.
If the issue still persists, please open the issue in the Metamask repository: https://github.com/MetaMask/metamask-extension
