### ISSUE TITLE
Missing changelog in `Update available` modal when TOR enabled

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4955]
**Describe the bug**
Missing changelog in `Update available` modal when TOR enabled.
Maybe we can consider different delivery of changelog, even when TOR is not enabled it takes some time to show changelog before it's downloaded.

**Steps to reproduce:**
1. Enable TOR in older version
2. restart application
3. observe `Update available` modal

**Info:**
 - Suite version: desktop 21.11.2 (e548c52e39f071f0d8d7d8a833bdbd7e2b6fee36)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.11.2 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Screenshots:**
<img width="752" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/154454800-a8150685-e4f6-4839-abe1-eda80b9416ae.png">

**Comment by tomasklim** [comment]
Both problems should be fixed via solution for https://github.com/trezor/trezor-suite/issues/5012

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.3.0 (8ecb68b468d6c640e91c3e96b28131773cb98fac)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device:
