### ISSUE TITLE
Improve communication of a loading discovery

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4961]
The user should be better informed that not all addresses are loaded yet. Errors occur when using the Suite during discovery. At the same time, the total balance is gradually loaded. An incompletely loaded balance history could scare the user if it is not obvious that discovery is still in progress.

https://user-images.githubusercontent.com/26002916/154655473-26520aa8-1f05-465c-b7f9-4701b26a063e.mp4

- [ ] Add green loading bar
- Add spinning wheel next to:
    - [ ] `Dashboard`/ *portfolio value*
    - [ ] `Dashboard`/ `My assets`
    - [ ] `Accounts` / `My accounts`
    - [ ] `Accounts` / `Receive` / `Show full address` (inside the button)

Related discussion: [Slack](https://satoshilabs.slack.com/archives/C01SXSHGK44/p1644928829171149)

**Comment by STew790** [comment]
**QA OK**

Attached is a video of the current state in dev master. 

- green loading bar present
- spinning wheel in - dashboard/portfolio value present
                               - dashboard/ my assets present
                               - accounts/my accounts present
                               - accounts/receive/show full address present
                               
![image](https://user-images.githubusercontent.com/48477147/155734422-7761d6e5-1a5b-4c38-984a-c6ece09f427f.png)


https://user-images.githubusercontent.com/48477147/155733169-83a6801a-c042-44a8-9380-65a2b93e0052.mp4

**Info:**
 - Suite version: desktop 22.3.0 (8fed4ff9336a4f9c7eef5d7ef29943c66208ad12)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular

**Comment by bosomt** [comment]
Please see video or screenshot. Loading discovery indicator overlaps `Notifications` modal.
Do you want me to send separate issue ? Or reopen this one ? 

**Info:**
 - Suite version: desktop 22.3.1 (6b7e7fa25de1c50814fe3bfcd889cf147c93ef24)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular


<img width="544" alt="Screenshot 2022-03-08 at 21 06 25" src="https://user-images.githubusercontent.com/31506317/157320797-85888b4c-6451-4b9f-afe2-9e65161e9cee.png">


https://user-images.githubusercontent.com/31506317/157322741-2d6a1971-6ecb-429f-aae5-198fdfd380e7.mov

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.3.2 (563be1e28ad75ddd4e38c2002e6032b0743511d2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.4 regular
