### ISSUE TITLE
Message banner in desktop app is hidden below Update modal on welcome screen

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#4964]
**Describe the bug**

If there is a System message available and relevant right after the desktop app start and there is update available, the  banner is hidden below the modal (see screenshot).

The problem is that we want to inform the user, that the update process is broken, but user can't see the message if he don't close the Update modal.

**Info:**

-   Suite Version: desktop app 22.2.3 (but it's not a new issue)

**Expected behavior**
The system message should be visible even if there is an open modal.

**Screenshots**
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/3729633/154675373-78bbe436-bbf8-4dee-b0de-1a3434519fc3.png">

**Comment by STew790** [comment]
**QA OK**

Linux, Windows and MacOS updates tested and all shows the banner correctly.

![image](https://user-images.githubusercontent.com/48477147/156017092-db2d262b-c0fd-40a9-8e84-462fc356e38c.png)
