### ISSUE TITLE
[Macos] Suite Guide sidebar's opening/closing lags when portfolio graph is rendered

### ISSUE THREAD

**Issue by ondracja** [trezor/trezor-suite#4970]
**Describe the bug**
When the user opens the Suite Guide sidebar on the `Dashboard` page after the portfolio graph renders, the process of opening and closing is very laggy.

**Steps to reproduce:**
1. Start the desktop Suite
2. Go to the Dashboard page
3. Wait until the portfolio graph fully renders
4. Open the Suite Guide by clicking on the button in right bottom corner
5. Observe the sluggish process

**Info:**
 - Suite version: desktop 22.2.1 (520802b8052d558de9c5f0ee55f9151ea5122eb4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.2.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel, Big Sur 11.6.2
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Expected result:**
Sidebar opens fluently.

**Actual result:**
Sidebar opens sluggishly

**Notes**
 - issue also reproduced on M1 Macbook with Monterey OS

https://user-images.githubusercontent.com/9817938/154940196-13c4a5fc-7943-4bf8-9337-79c170cf02da.mov

**Comment by bosomt** [comment]
**QA NOK**

still laggy

**Info:**
 - Suite version: desktop 22.8.1 (4ddcf5c6b05fefda0425919434a936e534482a1e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32

**Comment by MiroslavProchazka** [comment]
Working for me just fine
