### ISSUE TITLE
Trading - redirect in Suite Desktop not working as expected

### ISSUE THREAD

**Issue by martinboehm** [trezor/trezor-suite#4979]
In the Invity buy and sell crypto we were using a functionality to redirect user to a specific place in the Suite, calling the Electron function loadURL with url (example from dev environment):
```
 mainWindow.loadURL('http:/localhost:8000/coinmarket-redirect#sell-offers/btc/normal/0/p-qc/CZ/EUR/0.00394041/BTC/71a542f5-a1f8-4f72-851f-ff8743021460');
```
where `mainWindow` is `BrowserWindow`. Unfortunately, while the call caused reload, it ended up in the root of the Suite (Dashboard), not triggering our `coinmarket-redirect` route.

We have since abandoned the functionality in preference to not to reload the Suite for better user experience (the reload is slow and requires to reenter the passphrase and/or pin) but the issue still remains.

**Comment by tomasklim** [comment]
@bosomt please checkif sitll available

**Comment by bosomt** [comment]
**QA OK**

approved by invity
https://satoshilabs.slack.com/archives/C04DD84P4A1/p1729157401012799?thread_ts=1728990186.255179&cid=C04DD84P4A1
