### ISSUE TITLE
suite-desktop/src-electron should have own package

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#4989]
During #4851 I found that every dependency included `package.json` of `suite-desktop` is copied to electron node_modules with all subdependencies. That is problem because we have `src` and `src-electron`, and dependencies that are used in `src` are for ui part and are bundled anyway.

It's hotfixed by **not** defining dependencies in `suite-desktop/package.json` (for example `suite`) even if they are used in code of this package. But this breaks all kinds of monorepo tooling:

1. `suite-desktop` is in blacklist for TS refs generator in root package.json. Because we need to have defined this package in `suite-desktop` tsconfig refs we need to add it manually since it's not defined in `package.json`. This blacklist could be removed after this will be done.
2. Unnecessary dependencies are bundled into electron because they are defined in dependencies in `package.json` but we don't need them because they are also bundled by webpack anyway when building UI.
3. Probably some other issues can occur with this dependencies mess (like phantoms and doppelganger deps). 

**Only logical step here to separate ui and electron to their own packages, that should prevent all possible issues with this.**

- [x] After this will be done we can remove nx implicit deps in suite-desktop
- [x] Remove suite-desktop from `yarn refs` blacklist

**Comment by tomasklim** [comment]
As part of this issue, there will also be optimization of https://www.electron.build/configuration/contents.html and other files inside the app installation package.

- [x] optimize assets in suite-data - pngs, svgs, videos, fonts
- [x] move favicons to images root folder
- [x] `suite-desktop` should not import anything from `suite`

**Comment by Nodonisko** [comment]
Also would be nice to consider creating separate folder as we planned `suite-desktop/` for all suite-desktop related packages. Same way as we have `/suite-common` and `/suite-native`

**Comment by bosomt** [comment]
This Issue will be tested as part of https://github.com/trezor/trezor-suite/pull/6416 testing. 
Correct ? @Nodonisko @tomasklim

**Comment by tomasklim** [comment]
Yes

**Comment by STew790** [comment]
**QA OK**
All results available in Notion task https://www.notion.so/satoshilabs/Packages-split-trezor-suite-desktop-trezor-suite-desktop-ui-app-size-reduction-20-2MB-6-2cc0ce1cbb1841ec97d32d654655e68b
