### ISSUE TITLE
Click on right side of inactive coin "badge" opens custom backend settings

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#4992]
**Describe the bug**
Click on right side of inactive coin "badge" opens custom backend settings instead of activating the coin.

**How to reproduce**

1. Go to Settings/Crypto
2. Click on the right side of the Coin "badge"

**Expected behavior**
Coin should be activated.

**Screenshots**

https://user-images.githubusercontent.com/3729633/155514367-ed6ff1fd-0dc9-418c-8bf0-816196a45a19.mov

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.4.0 (ffc9c08da82b2913e5f61bdb8586065ce6c82f32)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.0 regular
