### ISSUE TITLE
Sentry enhancements - adding context

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#4997]
Add more context/tags to the Sentry issue:
  - [x] transport type (as a tag)
https://github.com/trezor/trezor-suite/pull/5095
  - [x] current route path including app, foregroundapp and fullscreen app (errors from desktop are missing the information about current location, for web there are full URLs)
  - [x] tor status
  - [x] FW and bootloader versions
  - [x] device.mode?, device.type?
  
 
 Stop reporting some useless errors:
 ```
'ERR_INTERNET_DISCONNECTED',
'ERR_NETWORK_IO_SUSPENDED',
'ERR_NETWORK_CHANGED',
'Error: HTTP Error',
'other call in progress',
'Action cancelled by user',
'ResizeObserver loop limit exceeded',
'device disconnected during action',
```

**Comment by tomasklim** [comment]
When `tor` tag is added to sentry, please check again https://github.com/trezor/trezor-suite/issues/5793 that it happens on both `tor` and `clear` web

**Comment by matejkriz** [comment]
There is nothing to test from user perspective, regular sanity tests will cover it.
