### ISSUE TITLE
Custom backend info is still visible after coin is disabled

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#5001]
**Describe the bug**
We show Electrum custom backend as disconnected even when the coin is turned off.

**Steps to reproduce:**
1. Set up Customer Electrum server
2. Disable bitcoin
3. Enable another coin

**Info:**
 - Suite version: desktop 22.3.0 (8fed4ff9336a4f9c7eef5d7ef29943c66208ad12)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: model T 2.4.4 regular

**Expected result:**
No custom backend is shown? Or maybe some other indication that the coin is turned of?
![image](https://user-images.githubusercontent.com/1835345/155693871-13ec498f-c938-465a-88ab-8d06374b1d88.png)

**Screenshots:**
![image](https://user-images.githubusercontent.com/1835345/155693637-539a70eb-834a-443c-823f-7b83d2480504.png)

**Comment by matejkriz** [comment]
please, decide the priority

**Comment by hynek-jina** [comment]
~We have to rethink navigation behaviour first..~
Navigation behaviour issue already described: https://github.com/trezor/trezor-suite/issues/5157

**Comment by bosomt** [comment]
there is easy way to reproduce it
all you have to do is to reset app settings
you will get regtest server disconnected even coin was not enabled before
same result when you wipe complete data from debug section of settings 


**Info:**
 - Suite version: desktop 22.4.0 (b00736043c7d64bbcdcd1db1612a1f253a927fe6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.4.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
 -

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/31506317/160756483-a0e2afa8-4564-4fb7-9df8-1bb9f623f801.png">


<img width="736" alt="image" src="https://user-images.githubusercontent.com/31506317/160756299-6b164721-af72-4109-b2a9-293164c4e1d5.png">

https://user-images.githubusercontent.com/31506317/160756326-92354916-1b56-4478-9a06-11b793517ca5.mov

**Comment by STew790** [comment]
**QA OK**

When I set up custom Electrum BE and then turn off bitcoin the indicator disappears immediately. Also, when resetting the app via settings, there is no regtest server present.

**Info**:

- Suite version: desktop 22.4.1 (https://github.com/trezor/trezor-suite/commit/157aec2030adbb7280d8b90ef0452df2a8400aff)
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.4.1 Chrome/94.0.4606.81 
Electron/15.3.0 Safari/537.36
- OS: Linux x86_64
- Screen: 1920x1080
- Device: model T 2.5.0 regular
