### ISSUE TITLE
Data analytics: Backup succes rate

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#5003]
We want to know how many users started backup creating (anywhere) and finished or not (i.e. the failure rate). 
New event `create-backup` should be created, with attribute `error` with similar function as in `device-update-firmware`.

**Comment by STew790** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/48477147/162758242-af298a4f-488f-46a1-829a-6c97f3ff40b0.png)

**Info:**
 - Suite version: desktop 22.4.1 (157aec2030adbb7280d8b90ef0452df2a8400aff)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.4.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.0 regular
