### ISSUE TITLE
Allow custom Electrum server backend also for Bitcoin testnet

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#5005]
It seems to me that I can't set up Electrum server for Bitcoin testnet. Any reason not to allow that? I think it would be useful for testing.

**Comment by Kixunil** [comment]
Please, regtest as well (didn't test yet)

**Comment by matejkriz** [comment]
@marekrjpolak Is it just a matter of editing the configuration?

**Comment by marekrjpolak** [comment]
> @marekrjpolak Is it just a matter of editing the configuration?

Should be, and it's somehow working with regtest, but I haven't tested it with testnet yet.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.5.0 (91e8119f2e75794c1b3b36997e0aa2fa4397838c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular (revision 595b14254c1abb2be3f69e42c7932f1eca8cf1b1)
 - Transport: bridge 2.0.31

<img width="728" alt="image" src="https://user-images.githubusercontent.com/31506317/166432538-6a383985-78da-434c-9a2f-eebf527bd2ae.png">

https://tbtc1.trezor.io/tx/ff2d6f15e392c7582f9442adaf03064091d68bc08028c359821ee084a8f6cdd8
