### ISSUE TITLE
HTML element in "Looking for Trezor Wallet"

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#5007]
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/1835345/155755766-4c1b195d-ec86-4162-9016-a704faab3761.png">

**Comment by tsusanka** [comment]
@hynek-jina this would be nice to squeeze into the Tueday freeze as it should be pretty quick and we deprecate the Wallet soon.

**Comment by jerechinsky** [comment]
I corrected this in Crowdin. We'll do a Crowdin sync and backport on Monday ahead of the freeze.
https://crowdin.com/translate/trezor-suite/103/en-en#28729

**Comment by STew790** [comment]
**QA OK**

The word "strong" is not there anymore and the whole sentence is correctly bold now.

![image](https://user-images.githubusercontent.com/48477147/155981507-7073c803-5334-4d1d-8e98-b13966df6225.png)

**Comment by tsusanka** [comment]
@alex-jerechinsky could we also change "Quicker transactions with RBF" to "Cheaper transactions with RBF"? They are not faster..

**Comment by jerechinsky** [comment]
> @alex-jerechinsky could we also change "Quicker transactions with RBF" to "Cheaper transactions with RBF"? They are not faster..

Sure. I changed it in Crowdin. I'll make sure it gets cherrypicked before release. There's still some Russian and Czech copy I'm finishing anyway.

https://crowdin.com/translate/trezor-suite/103/en-en#28735
