### ISSUE TITLE
Data analytics: app update

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#5012]
We want to know how many users ignore (or not) new desktop app update.
New event
```markdown
app-update
     -   fromVersion: string
     -   toVersion: string
     -   status: 'finished' | 'cancelled' | 'error'
     -   version: 'stable' | 'beta'
```

**Comment by tomasklim** [comment]
@trezor/qa test this together with app update (contact me for more info)

**Comment by STew790** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/48477147/165315783-94e5c521-cdb0-4570-a020-530ecd41120e.png)

**Info:**
 - Suite version: desktop 22.4.2 (1a1572b58bc0a76020978ab51ad85cbac0766aa1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.4.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular
