### ISSUE TITLE
Cannot use 3rd party backends (not served on trezor.io) with TOR

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#5018]
Default trezor/connect backends, that are not served on trezor.io domain, will fail with an error `Endpoint not set` with TOR enabled. You can test this behaviour with Ripple and Cardano.

I assume the problem is in Connect:
https://github.com/trezor/connect/blob/develop/src/js/backend/BlockchainLink.js#L84-L95

This code will filter out all backends that don't have onion domain defined in:
https://github.com/trezor/connect/blob/b63cd02ba5dc48121756580351321b2e2cacaa84/src/data/config.json#L30

And since there is only trezor.io domain, `this.onionDomains` object is not populated with 3rd party backends.

So if `options.onionDomains` is defined then keys of `this.onionDomains` are used as array of URLs that are passed to BlockchainLink worker (be aware that these are 2 different variables, naming is super confusing), but this object doesn't include non-trezor.io backends at all so `server` var will be set to an empty array.

```js
const server = onionDomains ? Object.keys(this.onionDomains) : blockchainLink.url;
```

**Comment by tsusanka** [comment]
@hynek-jina @matejkriz I believe this is a release blocker. (not necessarily a freeze blocker though)

**Comment by matejkriz** [comment]
fix in connect https://github.com/trezor/connect/pull/1067

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.3.1 (538d147496ee9e5a03c2a8e3754b3532ddedaf6d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
