### ISSUE TITLE
There is a mistake in crowdin's master.json

### ISSUE THREAD

**Issue by fujicoin** [trezor/trezor-suite#5022]
There is no key: TR_RECEIVED_SYMBOL in crowdin's master.json.
The English text of Key: TR_RECEIVING_SYMBOL is different from that of messages.ts.

The relevant part of messages.ts is as follows:
```
    TR_RECEIVED_SYMBOL: {
        id: 'TR_RECEIVING_SYMBOL',
        defaultMessage:
            'Received {multiple, select, true {multiple tokens} false {{symbol}} other {{symbol}}}',
    },
    TR_SENDING_SYMBOL: {
        id: 'TR_SENDING_SYMBOL',
        defaultMessage:
            'Sending {multiple, select, true {multiple tokens} false {{symbol}} other {{symbol}}}',
    },
```

The question is why such mistakes occur.
I can only think that master.json is created manually.
I think master.json must be generated automatically.

**Comment by slowbackspace** [comment]
Hello @fujicoin, @alex-jerechinsky I opened PR that fixes incorrect message ID for `TR_RECEIVED_SYMBOL`. Bug was introduced while refactoring these messages for cardano.
https://github.com/trezor/trezor-suite/pull/5023

**Comment by mroz22** [comment]
`master.json` is autogenerated from `messages.ts`
using 
`yarn workspace @trezor/suite translations:extract`

we also have a nightly job checking whether messages.ts is ok. https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/2146691283#L224

**Comment by fujicoin** [comment]
@alex-jerechinsky @mroz22 

Well, I understand why the error occurred.
The code that generates master.json from message.ts seems to be extracting the value of id key.

However, the Suite program refers to the primary key in message.ts when invoking the translation.
The id key value is not actually used.

Programmers often miss the value of the id key.
The programmer has to enter the primary key in the value of the id key, which is a waste of work.

I propose to abolish the id key.
The code that generates master.json from message.ts should extract the primary key.

**Comment by fujicoin** [comment]
I actually tried running formatjs.
formatjs is issuing a warning correctly.

```
$ yarn workspace @trezor/suite translations:extract
yarn workspace v1.22.17
yarn run v1.22.17
$ formatjs extract src/support/messages.ts --format simple > ../suite-data/files/translations/master.json
warning [FormatJS CLI] Duplicate message id: "TR_RECEIVING_SYMBOL", but the `description` and/or `defaultMessage` are different.
Done in 1.23s.
Done in 1.69s.
```
