### ISSUE TITLE
Create a simple UI for bitcoind regtest to be used for testing 

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#5031]
Right now we have bitcoind regtest that can be used for blockbook and for custom electrum backend.
There are some automatic tests using those but it would be nice to have an easy way to use regtest with difference backends to test different scenarios (send, receive ....)

The idea would be to have few simple options:\
* generate blocks
* create transactions

For achieving this we already have websocket server https://github.com/trezor/trezor-user-env that can be extended.

**Comment by mroz22** [comment]
its done I'd say http://localhost:9002/
