### ISSUE TITLE
Custom backend - address remembering

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5032]
Remember custom backend addresses when switching to Default address

**Comment by tomasklim** [comment]
Example of current behaviour. I have Tor enabled so I would expect that `onion` address will be used, but it is not. 
<img width="852" alt="156207726-6c4445a7-a08b-48e6-ab4b-511dff2bad46" src="https://user-images.githubusercontent.com/33235762/156533669-f5810b2f-5fc3-4841-9edf-97094131c95c.png">

**Comment by STew790** [comment]
**QA OK**

Suite correctly remembers custom backend URL.

**Info:**
 - Suite version: desktop 22.5.0 (04ba1dce216a6f9a958ff411fe79029431fd5038)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.0 regular (revision fd4f8601cf73c5744978f0e8c0aa43d863032a37)
 - Transport: bridge 2.0.31

**Comment by marekrjpolak** [comment]
I'm sorry, @STew790, have you also checked the other concerns from #5287? Especially I want to be sure that nothing breaks and everything is remembered when upgrading from DB version 26 to 27.

**Comment by STew790** [comment]
Yes, thanks for the reminder, I did check it and:
- custom BE persists when updating the db (I tried setting up the custom BE in a Suite a few releases back and it persisted to this newer version)
- Tor and onion address functionality with the custom BE is the same as before (showing correctly modals)
