### ISSUE TITLE
Temporary disappearance of custom backends saved options

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5038]
**Describe the bug**
If I have a custom backend set for a coin and I am navigating between different types of backends in coin backends modal. I cannot see my custom saved addresses unless I reopen the modal.

**Info:**

-   Suite Version: 22.3.1

**How to reproduce**

https://user-images.githubusercontent.com/33235762/156530555-331706b7-db95-492a-b227-ce82fcdf690a.mov

**Comment by hynek-jina** [comment]
Related to: https://github.com/trezor/trezor-suite/issues/5032

**Comment by STew790** [comment]
**QA OK**
This was already resolved via https://github.com/trezor/trezor-suite/issues/5032. Closing.
