### ISSUE TITLE
Message system with the support of anchor links

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5040]
Extend message system config to support anchors.

```
"cta": {
    "action": "internal-link",
    "link": "settings/device", // config/suite/routes.ts
    "anchor": "tor", // constants/suite/anchors.ts
    "label": {
        "en": "Disable tor"
    }
}
```

If the user is already on the page, the message system banner will not redirect #4915

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.5.0 (bf0e4020dc1344c179501fcb5f57d9c4039c8bf0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.0 regular (revision fd4f8601cf73c5744978f0e8c0aa43d863032a37)
 - Transport: bridge 2.0.31
