### ISSUE TITLE
Follow up electron-builder Pull Request for signing dll in windows

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#5042]
We created PR https://github.com/electron-userland/electron-builder/pull/6682 that currently we are patching in our repository https://github.com/trezor/trezor-suite/blob/develop/patches/app-builder-lib%2B22.14.5.patch

It will require some follow up until it gets merge so we will be able to use it in next version instead of as a patch.

**Comment by karliatto** [comment]
The upstream PR was merged https://github.com/electron-userland/electron-builder/pull/6682

So we can just update electron-builder in next released version, and it looks like they do releases quite often.

**Comment by karliatto** [comment]
Electron-builder has created pre-relase version including these changes but we want to wait until there is a final release.

https://github.com/electron-userland/electron-builder/releases

**Comment by ondracja** [comment]
This issue will be tested when we test the auto-update functionality during this code freeze.
