### ISSUE TITLE
Sentry Electron SDK behavior in dev mode

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#5046]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/45338719/156567627-994d7183-42fc-458d-96e6-5f4723c180a9.png">

-   Suite Version: app 22.3.0
-   OS: macOS

**How to reproduce**

1. Run suite in `dev` mode
2. Observe the error

**Expected behavior**
No error

**Additional context**
The error stems from a strange implementation of connection between `@sentry/electron` and `@sentry/electron/renderer`. In `dev` we are disabling Sentry to avoid errors being sent completely but one script:

`@sentry/electron/esm/renderer/ipc.js => getImplementation()`

 is running anyway. That script relies on `@sentry/electron` being `initialized` AND `enabled` (no `enabled: false` in the config). The renderer Sentry does not have to be active. The `enabled` prop in the config has to be true because it controls initialization of internal Sentry integrations, namely the preload scripts, one of which is also responsible for establishing the connection between `@sentry/electron` and `@sentry/electron/renderer`.

**Comment by bosomt** [comment]
@dahaca anytching needed on QA side or i can move it to approved section ?

**Comment by dahaca** [comment]
@bosomt Can move
