### ISSUE TITLE
Autoupdate doesn't start new Suite version after update on Linux

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#5049]
**Describe the bug**
When trying to autoupdate from "mocked" version (0.22.3) to 22.2.3 the app is downloaded and updated but the updated version starts only for a second and then quits again and won't start. Happens only on Linux. On Windows 10, the app will restart for just a second and then quit as well but it will start again fully updated. MacOS update is OK.

**Info:**

-   Suite Version: 0.22.3>22.2.3
-   OS: Linux Ubuntu
-   Bridge: bundled 2.0.31

**How to reproduce**

1. Download the special version of Suite (0.22.3)
2. Install it
3. Open it and immediately an update pops up
4. Update the app
5. After downloading click on update and restart
6. Observe the app doesn't start again

**Expected behavior**
Suite app will start again after "restart and update" is selected.

**Actual behavious**
Suite app won't restart after "restart and update" is selected.

**Comment by matejkriz** [comment]
It was problem with downgrading storage. Please verify, that `desktopApi.appRestart();` itself works on linux as expected.

**Comment by tomasklim** [comment]
Closing as it has nothing to do with auto-update. There is a problem with app relaunch on Linux on app restart. #5055
