### ISSUE TITLE
Generate screenshots of all connect screens

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#5050]
In preparation for a re-design of [trezor/connect](https://github.com/trezor/connect), capture of all pre-existing screens as a base for research of the currently developed use cases.

Latest captures can be found on the [CI develop branch](https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines?page=1&scope=all&ref=develop) > Choose the latest passed job > Jobs tab > "connect-explorer" > download artifact.

#### Base
- [x] getPublicKey
- [ ] requestLogin
- [x] cipherKeyValue
- [x] wipeDevice
- [ ] ~~resetDevice~~ management method, not that important, causing some problems in tests, skipping for now
- [ ] ~~getCoinInfo~~ probably getAccountInfo? Not so important, has the same screen as getPublicKey
- [x] recoverDevice

#### Bitcoin
- [x] getAddress
- [ ] ~~getAddress-multiple~~ no reason, multiple is just like getAddress 
- [x] getAccountInfo
- [x] getAccountInfo-xpub
- [x] composeTransaction
- [x] signTransaction-paytoaddress
- [ ] pushTransaction
- [x] signMessage
- [x] verifyMessage

#### Ethereum
- [x] ethereumGetAddress
- [x] ethereumGetPublicKey
- [x] ethereumSignTransaction
- [x] ethereumSignMessage
- [x] ethereumSignTypedData
- [x] ethereumVerifyMessage

#### Eos
- [x] eosGetPublicKey
- [x] eosSignTransaction

#### NEM
- [x] nemGetAddress
- [x] nemSignTransaction

#### Stellar
- [x] stellarGetAddress
- [ ] ~~stellarSignTransaction~~ blocked. @trezor/connect-plugin-stellar needs to be merged first #5450

#### Cardano
- [x] cardanoGetPublicKey
- [x] cardanoGetAddress
- [x] cardanoGetNativeScriptHash
- [x] cardanoSignTransaction

#### Ripple
- [x] rippleGetAddress
- [x] rippleSignTransaction

#### Tezos
- [x] tezosGetAddress
- [x] tezosGetPublicKey
- [x] tezosSignTransaction

#### Binance
- [x] binanceGetAddress
- [x] binanceGetPublicKey
- [x] binanceSignTransaction

**Comment by sime** [comment]
Some WIP: https://github.com/trezor/trezor-suite/pull/4988

**Comment by mroz22** [comment]
some progress in https://github.com/trezor/trezor-suite/pull/5462

**Comment by sime** [comment]
Woo! 💪

**Comment by STew790** [comment]
After discussion with @mroz22 no further testing from QA needed. Moving to approved.
