### ISSUE TITLE
https://wallet.trezor.io/data/config_signed.bin cannot download now

### ISSUE THREAD

**Issue by aaurix** [trezor/trezor-suite#5054]
We integrated the very early [trezor.js](https://github.com/trezor/trezor.js) library to construct transaction management for our btc multi-signature wallet. 

The trezor is still working fine for the last month. Today, trezor connect reported an error, prompting config parse error.
<img width="943" alt="image" src="https://user-images.githubusercontent.com/7252280/156764305-4b570a1b-d64a-4a9e-a1b6-81e07a8cc4c9.png">

<img width="978" alt="image" src="https://user-images.githubusercontent.com/7252280/156764587-1062eb7e-73a5-4969-8afe-16af4e9877f4.png">

We found that the bin file https://wallet.trezor.io/data/config_signed.bin is no longer available for download, so our multi-signature wallet cannot be used normally.
I know that I need to access the new connect library now, but the time is too fast, and the integration may take a long time and affect the business.
Please provide the cofig_signed.bin file so that our work can be carried out normally.

Best wishes!

**Comment by aaurix** [comment]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/7252280/156771372-e8537d0e-a570-428f-b00f-5dd570b75123.png">

https://data.trezor.io cannot access？
so we cannot get config_signed.bin.  I need to get this file

**Comment by aaurix** [comment]
Stopping this website has caused a lot of trouble to our btc wallet. Please give me this file or tell me where I can download it.
Adapting to the new sdk requires a lot of work

**Comment by matejcik** [comment]
you can find the file here:
https://github.com/trezor/webwallet-data/blob/master/config_signed.bin

**Comment by aaurix** [comment]
thx  sir！

**Comment by aaurix** [comment]
@matejcik this config file is too old for run. can you give me a new verion config_signed.bin.

Our program was written in 2020, the version three years ago is too old

**Comment by aaurix** [comment]
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/7252280/156779722-2a822c83-d172-4d39-bfbd-8b1edea0524d.png">
The config_signed from this link a month ago was ok, just not now https://wallet.trezor.io/data/config_signed.bin

**Comment by sime** [comment]
@0xhelloweb3 I just hashed the file, and the one in GitHub has the same has used to be available on wallet.trezor.io. 

```
$ shasum config_signed*
f46111d54fdbf7b0c10d211f8340f64df4e9a3ad  config_signed(1).bin
f46111d54fdbf7b0c10d211f8340f64df4e9a3ad  config_signed.bin
$ md5 config_signed*
MD5 (config_signed(1).bin) = c48755432ffb2cc5238f1ed51144489e
MD5 (config_signed.bin) = c48755432ffb2cc5238f1ed51144489e
```

**Comment by matejcik** [comment]
~~You shouldn't have been using an ancient version of Trezor Connect if you wrote it in 2020, it's very much out of support and it has been out of support at that time.~~ edit: apparently trezor.js was alive and kicking in 2020?

I am not sure if a newer `config_signed.bin` even exists. The file was necessary for Trezor Bridge version 1, which is not in use since 2018 because it doesn't support Trezor T.

**Comment by aaurix** [comment]
Thanks to the trezor team for your patience, I will try again and migrate to the latest sdk as soon as possible.
