### ISSUE TITLE
Suite doesn't relaunch on "Reset app" on Linux

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#5055]
**Describe the bug**
Suite doesn't relaunch when I try to "Reset app" in settings on Linux Ubuntu. (On NixOS it works correctly)

**Steps to reproduce:**
1. Start Suite
2. Go to settings
3. Click on "Reset app"
4. App will quit but won't relaunch

**Info:**
 - Suite version: 22.2.3 (4dc44f620de7f15cdd66970cf22126695435c969)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.5 regular

**Expected result:**
App will relaunch.

**Actual result:**
App just quits and won't relaunch.

**Comment by tomasklim** [comment]
Probably a working fix. Tested with @STew790  https://github.com/electron-userland/electron-builder/issues/1727#issuecomment-769896927

```
// modified Suite app/restart handler
ipcMain.on('app/restart', () => {
    logger.info('main', 'App restart requested');
    const options: RelaunchOptions = {};
    options.args = process.argv.slice(1).concat(['--relaunch']);
    options.execPath = process.execPath;
    if (process.env.APPIMAGE) {
        options.execPath = process.env.APPIMAGE;
        options.args.unshift('--appimage-extract-and-run');
    }
    app.relaunch(options);
    app.exit(0);
});
```

Would be nice if someone with Linux Ubuntu tries it again @mroz22 
Has to be tested on all OS.

**Comment by STew790** [comment]
**QA OK**

App relaunched correctly when I clicked on "Reset app"

**Info:**
 - Suite version: app 22.4.0 (35d3fb451d1833ddd00a253b275de185ae26b0b8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.4.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.4 regular

**Comment by STew790** [comment]
**QA NOK**
This issue is back, app can't be restarted by "Reset app".

**Info:**
 - Suite version: desktop 22.11.1 (73ccf723353e0575a64f58b2f5775d20f072311f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: bridge 2.0.32

**Comment by matejkriz** [comment]
note from @szymonlesisz , the app can be restarted but it starts disconnected from the console on nixos with `appimage-run`

**Comment by matejkriz** [comment]
Still **NOK** on Ubuntu 22.04.1 LTS

**Comment by matejkriz** [comment]
@trezor/qa could you please retest because we updated the Electron recently?

**Comment by bosomt** [comment]
@matejkriz tested multiple times on KUbuntu with 6e3b9428e732254d8e051b03460d0d0ef5f28650 no luck, app never relaunches after reset is triggered from app settings.

**Comment by matejkriz** [comment]
@bosomt thanks for verification 👍

**Comment by STew790** [comment]
**QA NOK**
Unfortunately, this is still present.

**Info:**
- Suite version: desktop 23.8.0 (24120f18f6a074789fe8e49f3ce1b38e863179bf)
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.8.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
- OS: Linux x86_64
- Screen: 1920x1080
- Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
- Transport: BridgeTransport 2.0.33

**Comment by STew790** [comment]
Not sure if it helps but when I was updating from `0.23.12` version to `23.11.5` (part of the autoupdate test) the Suite actually DID restart itself after the update downloaded the new version and I clicked on "Restart and update", which wasn't happening before because of this issue.
Nonetheless, the "Reset app" button still does not restart the app (but it still does reset it).

**Comment by STew790** [comment]
**QA NOK**
Sadly, this is still not working.

**Info:**
 - Suite version: desktop 24.3.0 (8be1f8046d5228c5fd28b9cd0bcbeceb373d53b9)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by STew790** [comment]
Soo, the app again restarted for me when updating from 24.2.2 > 24.2.3 if that helps to solve this.

**Comment by STew790** [comment]
Seems like this issue might have been fixed by this https://github.com/trezor/trezor-suite/pull/14727
I will wait for the merge and test it again just to be sure.

**Comment by STew790** [comment]
**QA OK**
It is working again :tada: 

**Info:**
 - Suite version: desktop 24.11.1 (9e9dadff47c5243bf4a10f539a898fe48da46506)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: BridgeTransport 2.0.33
