### ISSUE TITLE
Token dropdown indicator changed in recent build

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#5059]
**Describe the bug**
See videos. ⬆️ ⬇️  indicators has changed in `Send` dialogue and in Trade `section`

**Info:**
 - Suite version: desktop 22.3.1 (538d147496ee9e5a03c2a8e3754b3532ddedaf6d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.5 regular

**Screenshots:**

<img width="253" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/157009881-48ac82dc-f575-4069-b33d-0d977b718c24.png">

<img width="259" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/157009911-b8b4919b-1b99-4841-970d-9b390902a298.png">

https://user-images.githubusercontent.com/31506317/157009162-19ec78b6-4cf2-4866-8cff-2787a6bdc41e.mov

https://user-images.githubusercontent.com/31506317/157009186-2b67663a-3376-4aaa-af6e-11422f5be74b.mov

**Comment by matejkriz** [comment]
I suspect this commit https://github.com/trezor/trezor-suite/commit/6237c8013e9c3dc8deb4822d82f4386f4412f817

**Comment by bosomt** [comment]
no change, it still looks strange that ⬆️ marks drop-down selector menu


<img width="499" alt="image" src="https://user-images.githubusercontent.com/31506317/161699373-d885e9ff-23a0-476c-8ceb-3bc615c69ef2.png">

**Comment by bosomt** [comment]
Is there any reason that  ⬆️ ⬇️ have different shades of grey ? @dahaca 

Otherwise **QA OK**

<img width="96" alt="Screenshot 2022-05-04 at 9 39 00" src="https://user-images.githubusercontent.com/31506317/166640026-1d83c0ea-626a-4f52-a493-55646081703b.png">
<img width="134" alt="Screenshot 2022-05-04 at 9 38 07" src="https://user-images.githubusercontent.com/31506317/166640029-700dd3b0-86b7-47e7-b9d4-6548aac9429a.png">

**Info:**
 - Suite version: web 22.5.0 (ad7cc59191eeeab24a3d057da6d418cadf3a0f63)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
