### ISSUE TITLE
Native supported coins on Trezor suite

### ISSUE THREAD

**Issue by pauserratgutierrez** [trezor/trezor-suite#5066]
The suite app doesn't allow to store any coin except for BTC and ETH. That's strange when your website clarelly tells that coin support is absolutelly amazing with more than 1.000 tokens.
![image](https://user-images.githubusercontent.com/73240206/157224065-7a934097-3758-4a90-ac09-577b241bd5fd.png)

In my opinion Trezor is one of the best (if not the best) wallets to store cryptocurrency. Something as simple as not allowing the users to store "suported assets by Trezor" using the Suite app isn't a good thing. A lot of new users are facing this problem, Trezor suite doesn't support that list of coins (it's supported using third party wallets, that isn't said anywhere in the website).

Adding native suport for the list of crypto in the Trezor Suite would be a gamechanger. Why aren't you adding it?

**Comment by pauserratgutierrez** [comment]
Reddit post where users manifest the same complain. https://www.reddit.com/r/TREZOR/comments/lop5sc/how_to_add_altcoins_to_trezor_wallet_for_a_trezor/

**Comment by prusnak** [comment]
> The suite app doesn't allow to store any coin except for BTC and ETH.

This is not correct. There are many coins you can add to the Suite: Litecoin, Dash, Dogecoin, etc. to name a few.
Plus you can use thousands of Ethereum tokens.
Cardano is coming soon.
See this list for more details: https://trezor.io/coins/

**Comment by hynek-jina** [comment]
You can find which wallets are supporting each of the mentioned coin on https://trezor.io/coins/
Most of the tokens in Suite work as an ERC20 via Ethereum.

Generally we are very careful with adding new coins into Trezor Suite. I have noted your idea, but closing this issue for now.

**Comment by pauserratgutierrez** [comment]
I see that now there's a pre release to add native support for Cardano (ADA) in Trezor Suite. That's cool!
I would like to see a lot more coins native supported. (USDT, AXS, SLP, ENJIN COIN, SHIBA and not eth coin support)

**Comment by melroy89** [comment]
Thank you for adding native support for Cardano. I really appreciate it! Just a shout out to the Trezor developers: well done! 🎂🙏
