### ISSUE TITLE
Select value should be object not string

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#507]
```
interface Value {
    value: string,
    label: string
}
```

![image](https://user-images.githubusercontent.com/3112191/64787948-d26eac80-d571-11e9-8b9c-8e0b83485595.png)

**Comment by slowbackspace** [comment]
somehow wrapping a `Select` with styled component (eg. `const LocalCurrencySelect = styled(Select)`) is messing with types for the Select props. Definitely not a good first issue 😄

**Comment by slowbackspace** [comment]
still not fixed
![Screenshot 2019-09-20 at 10 59 46](https://user-images.githubusercontent.com/6961901/65314092-dfa12200-db95-11e9-8962-a8491ec86522.png)

**Comment by vladimirvolek** [comment]
fixed in develop
