### ISSUE TITLE
Replace small secondary cancel button with closing cross

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5075]
Instead of small secondary `Cancel` button use closing X in top right corner of a modal.
This one appears in Checking backup modal, but please check other modals with such an element as well.

![image (4)](https://user-images.githubusercontent.com/26002916/157270374-31ecd527-c0fa-4b0c-b22f-3904425ce2c6.png)

**Comment by hynek-jina** [comment]
Potentially related to: https://github.com/trezor/trezor-suite/issues/5062

**Comment by matejkriz** [comment]
after global [Modal Refactoring](https://github.com/trezor/trezor-suite/pull/5132)
<img width="734" alt="image" src="https://user-images.githubusercontent.com/3729633/162009651-f0775c61-f6b6-4735-9a98-2d51520072d6.png">

**Comment by hynek-jina** [comment]
OK
