### ISSUE TITLE
Custom backend - address hierarchy

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5076]
Define hierarchy of custom backend address selection

**Story**
- For the default backend, we have filled in several of our addresses. On discovery, the Suite first shuffles them randomly and then takes them one by one until it successfully connects. This prevents overflow of one specific connection.
- If the user turns on Tor, we automatically offer `.onion` addresses in the same way

**Expected behaviour** 
- Try to find localhost address
- If not there is none, search for Tor address
- Then if needed fall to clear-net address

- Connect to first available address.
- If connection fails try another one (if listed)

**Comment by hynek-jina** [comment]
> Example of current behaviour. I have Tor enabled so I would expect that `onion` address will be used, but it is not. <img alt="156207726-6c4445a7-a08b-48e6-ab4b-511dff2bad46" width="852" src="https://user-images.githubusercontent.com/33235762/156533669-f5810b2f-5fc3-4841-9edf-97094131c95c.png">

Linked from https://github.com/trezor/trezor-suite/issues/5032#issuecomment-1057834157

**Comment by marekrjpolak** [comment]
Waiting for @mroz22 to give back the stolen commit :cop: as this should be implemented at the place heavily affected by it.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.6.0 (d72ff4c5b9f3cbe2ccb4be47170f88c08e9271d1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision a1d22890ee6a9ffec4edfc6e1b5b6c74d23855a3)
 - Transport: bridge 2.0.31
