### ISSUE TITLE
Pending transaction doesn't appear without app restart while using custom backend

### ISSUE THREAD

**Issue by ondracja** [trezor/trezor-suite#5082]
**Describe the bug**
When the user tries get some btc via regtest with custom electrum backend, the transaction doesn't appear in the suite unless it's been restarted. This is related to [PR#5065](https://github.com/trezor/trezor-suite/pull/5065).

**Steps to reproduce:**
1. Checkout [PR#5065](https://github.com/trezor/trezor-suite/pull/5065)
2. Run custom backend container (via `docker-regtest-electrum.sh` )
3. Follow necessary commands described in [this](https://www.notion.so/satoshilabs/Bitcoin-Regtest-8ccfd88b7d9c47fc9abbd2c935a3a9fb) notion page.
4. When the transaction is signed, observe that that no `pending transaction` is present in Suite
5. Refresh the suite
6. Observe, that the pending transaction appears

**Info:**
 - Suite version: desktop 22.3.1 (6b7e7fa25de1c50814fe3bfcd889cf147c93ef24)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: model T 2.4.3 regular

**Expected result:**
Suite shows a pending transaction

**Actual result:**
Suite doesn't show a pending transaction unless the app is restarted

**Comment by MiroslavProchazka** [comment]
Since it's quite an edge case and we are not planning to dive further into this topic in upcoming months I'm closing for now.
