### ISSUE TITLE
Can the defaultMessage of TR_RECEIVING_SYMBOL and TR_RECEIVED_SYMBOL be the same?

### ISSUE THREAD

**Issue by fujicoin** [trezor/trezor-suite#5088]
https://github.com/trezor/trezor-suite/blob/b6094d33db0cd2f9bba8fea300e14e6f81517e4a/packages/suite/src/support/messages.ts#L6359

Isn't 'Receiving' correct here?

**Comment by mroz22** [comment]
https://github.com/trezor/trezor-suite/blob/b6094d33db0cd2f9bba8fea300e14e6f81517e4a/packages/suite/src/support/messages.ts#L6356-L6365

there are 2 identical source strings. we should remove one of them IMHO

**Comment by slowbackspace** [comment]
@mroz22 I am afraid that TR_RECEIVING_SYMBOL should really start with "Receiving...", if aI remember correctly it is intended for pending transactions. Most likely botched in cardano PR :oops:

**Comment by jerechinsky** [comment]
Thanks for chiming in, @slowbackspace. 
I fixed it in [33269e1](https://github.com/trezor/trezor-suite/commit/33269e1140e87b12702462611f73d391fc149210#diff-988baecac61429698981f7b86b979d1627f33f484918f65402c4b345b5c57cbaR6362-R6363).

`TR_RECEIVING_SYMBOL` is now `Receiving {multiple, select, true {multiple tokens} false {{symbol}} other {{symbol}}}`
