### ISSUE TITLE
Fetching fiat rates for disabled coins and high CPU usage when Suite is open for a long time

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#5089]
**Describe the bug**
Suite is continuously fetching fiat rates even for disabled coins (and even when device is disconnected) after long run (Suite opened one day and the issue observed the next day - PC was put to sleep meanwhile)

At the same time the CPU usage is high.

**Info:**

-   Remembered Wallet: no
-   Suite Version: app, 22.2.3
-   OS: macOS Monterey, 12.2.1
-   Firmware Version: T, 2.4.3

**How to reproduce**

1. Open Suite
1. Connect the device (tested with allall seed)
1. Enable all coins
1. Wait
1. Wait more
1. Maybe put your PC to sleep
1. Observe

**Expected behavior**
Suite should not fetch fiat rates for disabled coins and no more than once every 10 minutes. CPU usage should be stable.

**Screenshots**

https://user-images.githubusercontent.com/3729633/157653967-c4b33c49-ff66-487c-a48c-63c5741229dc.mov

**Comment by matejkriz** [comment]
check this https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/services/fiat/limiter.ts#L28

**Comment by hynek-jina** [comment]
Might be related to coin control: https://satoshilabs.slack.com/archives/C048XFAKL10/p1680011575763659?thread_ts=1679994975.532989&cid=C048XFAKL10

**Comment by hynek-jina** [comment]
@trezor/qa Can you please retest if this still applies? 🙏

**Comment by STew790** [comment]
Both me and @bosomt didn't have any problems with CPU usage for quite some time. Closing this one but if the problem resurface, we will revisit this.
