### ISSUE TITLE
Update Terms and conditions

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5090]
Update
- [x] [TREZOR Suite Terms and Conditions](https://docs.google.com/document/d/1ljCR1GHBoCf122yLIq79_TdtrIO0R7khbj-i71sfzSo/edit) in Onboarding section
Update it here: https://data.trezor.io/legal/wallet-terms.pdf
- [x] [TERMS OF USE Trezor Suite Services by Invity](https://docs.google.com/document/d/1p8jzQpWn_4PZc1DTmc_5MWvW8FpuhX8Ag_TYdyyxLjs/edit#heading=h.ft3qa0h7fg89) in Trade (Invity) section
Update it here: https://data.trezor.io/legal/invity-terms-of-use.pdf

**Comment by vdovhanych** [comment]
updated t&c are now on data.trezor.io
