### ISSUE TITLE
Add Account: allow to add more accounts even though previous has no funds

### ISSUE THREAD

**Issue by tintinweb** [trezor/trezor-suite#5094]
I want to be able to add more ETH accounts, let's say, 10, even though only account 1 and 2 have funds. The reason for this is that I am using a lot of accounts, even without funding, for various purposes and still want to be able to manage them in trezor UI.

Current behavior: Does not allow to add more accounts if the previous account was unused.

Expected behavior: Like metamask, allow to permanently show the first X accounts even though they appear to be unused right now (e.g. because I explicitly use them on other chains)

**Comment by hynek-jina** [comment]
Thank you for your idea input. We are already investigating this option. I'm closing the issue until we have a product specification ready.
