### ISSUE TITLE
Can not label ETH token transactions

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#5096]
**Describe the bug**
Though you are allowed to label transactions while sending ETH you can not label tokens.

**Steps to reproduce:**
1. Send USDT and try to label it

**Info:**
 - Suite version: desktop 22.3.1 (6b7e7fa25de1c50814fe3bfcd889cf147c93ef24)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: mac m1
 - Screen: 1440x900
 - Device: model T 2.4.4 regular

![image](https://user-images.githubusercontent.com/1835345/157867450-59b016f1-9cd4-416a-b337-df413ba573b6.png)

**Comment by bosomt** [comment]
duplicity ? `Labeling - not able to add label to ERC20 transaction #3545` https://github.com/trezor/trezor-suite/issues/3545
