### ISSUE TITLE
Cannot see some rates in Summary

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#510]
![image](https://user-images.githubusercontent.com/3112191/64863595-85540e80-d635-11e9-9a67-8da876e0cb2f.png)

**Comment by slowbackspace** [comment]
could it be that rounded rate for 1 doge is actually 0.00? 🤔 I bet thats the case.

**Comment by slowbackspace** [comment]
<img width="634" alt="Screenshot 2019-09-16 at 21 10 03" src="https://user-images.githubusercontent.com/6961901/64985994-6c15c100-d8c6-11e9-828c-3b6c0b3c39ba.png">

yup, it is correct. I think I already talked about it with someone from QA way back.

**Comment by mroz22** [comment]
not a bug imho, probably needs some ux attention though

**Comment by vladimirvolek** [comment]
Not relevant anymore.
