### ISSUE TITLE
Trezor Connect unable to parse correct NEM Importance Transfer transaction

### ISSUE THREAD

**Issue by cryptoBeliever** [trezor/trezor-suite#5102]
**Describe the bug**
Trezor Connect 8.2.7 is not able to parse correct Importance Transfer transactions. The transaction schema for this tx type is invalid.

**Info:**

- Trezor Connect: 8.2.7
- Firmware: TT (2.4.3), T1 (1.10.5)

**How to reproduce**
Send a request using Trezor Connect:

```
TrezorConnect.nemSignTransaction({
     path: "m/44'/1'/0'/0'/0'",
     transaction: transaction
}).then(function(result) {
    console.log(result);
})
```

where the example Importance Transfer transaction is:

```
{
  "type":2049,
  "version":-1744830463,
  "signer":"462ee976890916e54fa825d26bdd0235f5eb5b6a143c199ab0ae5ee9328e08ce",
  "timeStamp":219493384,
  "deadline":219496984,
  "remoteAccount":"2e559707bb24a2a65379f975ebc4f95b5bf9987dea4bcef790f1431066bb7d70",
  "mode":1,
  "fee":150000
 }
```

There is error: **cannot read property 'mode' of undefined**

Looks like Trezor Connect is expecting other (invalid) transaction format (https://github.com/trezor/connect/blob/develop/tests/__fixtures__/nemSignTransactionOthers.js):

```
transaction: {
   timeStamp: 12349215,
   fee: 9900,
   type: 0x0801,
   deadline: 99,
   message: {},
   importanceTransfer: {
      mode: 1,
      publicKey: 'c5f54ba980fcbb657dbaaa42700539b207873e134d2375efeab5f1ab52f87844',
   },
   version: -1744830464,
}
```
Correct format for Importance Transfer transaction is described here: https://nemproject.github.io/#importanceTransferTransaction
- `mode` is not embedded into `importanceTransfer` object
- there is no property `publicKey` but `remoteAccount` and it's also not embedded into `importanceTransfer` object
- there is redudant `message` field for this tx type

**Expected behavior**
Trezor Connect should correctly parse Importance Transfer Transaction

**Additional context**
The problem did not exists on Trezor Connect v4 (we upgraded from v4 to v8) using same firmware version so it's problem in parsing tx by Trezor Connect.

**Comment by prusnak** [comment]
You need to use our format of transactions.

**Comment by sime** [comment]
@cryptoBeliever I'm getting a slightly different error, does my example make sense?

```
 {
  "id": 1,
  "success": false,
  "payload": {
    "error": "e.importanceTransfer is undefined"
  }
}
```

[nemsigntransaction.html.gz](https://github.com/trezor/trezor-suite/files/8244945/nemsigntransaction.html.gz)

**Comment by prusnak** [comment]
@cryptoBeliever You need to adapt your code to use Trezor format of transactions.

**Comment by cryptoBeliever** [comment]
@sime I'm getting `Cannot read property 'mode' of undefined` on your example. Maybe it's because my Chromium version.
@prusnak all transaction types matches with NEM specification except importance transfer transaction but we can adjust this type of course if needed. Thank you.
