### ISSUE TITLE
Ther is untranslated English message

### ISSUE THREAD

**Issue by fujicoin** [trezor/trezor-suite#5103]
The following English text will be displayed untranslated.
'This device is in recovery mode. Click the button to continue.'

The cause is on the next line:
https://github.com/trezor/trezor-suite/blob/36e436a764b4919e0ed0f5db1dc6b39035a2118a/packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceRecoveryMode.tsx#L43

**Comment by hynek-jina** [comment]
@alex-jerechinsky 
Can you please have a look on that?

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.4.0 (80a5c26ba7844db2c73f0b2208b157b668b4c607)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
