### ISSUE TITLE
Trezor connecting issue

### ISSUE THREAD

**Issue by rntoral** [trezor/trezor-suite#5104]
![trezor T](https://user-images.githubusercontent.com/77877560/158055822-f16738b8-332f-40a2-962c-663390574ab8.JPG)

Been trying to access my NFT's for several days now and Trezor just keep on loading. Please help me

**Comment by rntoral** [comment]
I have tried changing cables, usb ports and use  it into another device and still the same thing. All my assets are there. :(

**Comment by prusnak** [comment]
Seems this is a screenshot for Trezor Connect - please contact support of wallet you are using. (Is it Metamask?)

Also make sure you are not using Brave, but Chrome browser.

**Comment by rntoral** [comment]
It has nothing to do with my metamask. Since I couldn't use my Trezor in 3
wallets I have with them. I have spoken to them already and I was advised
to contact Trezor Contact support.
