### ISSUE TITLE
Trezor Connect `8.2.7-connected` drops Node v12 support

### ISSUE THREAD

**Issue by aloisklink** [trezor/trezor-suite#5107]
Trezor Connect version `8.2.7-connected` drops Node v12 support

**Info:**

-   Browser: Node.js v12.22.3
-   OS: Any 

**How to reproduce**

Try running `require("trezor-connect")` in Node v12 when using `trezor-connect@8.2.7-extended`.

Run the following commands in a new folder:

```console
me@pc:/tmp/trezor-test$ nvm use 12
Now using node v12.22.3 (npm v7.19.1)
me@pc:/tmp/trezor-test$ npm install trezor-connect@8.2.7-extended

added 147 packages, and audited 148 packages in 13s

37 packages are looking for funding
  run `npm fund` for details
me@pc:/tmp/trezor-test$ node
Welcome to Node.js v12.22.3.
Type ".help" for more information.
> require("trezor-connect")
Uncaught Error: Cannot find module 'fs/promises'
Require stack:
- /tmp/trezor-test/node_modules/@trezor/rollout/lib/utils/fetch.js
- /tmp/trezor-test/node_modules/@trezor/rollout/lib/index.js
- /tmp/trezor-test/node_modules/trezor-connect/lib/data/FirmwareInfo.js
- /tmp/trezor-test/node_modules/trezor-connect/lib/data/DataManager.js
- /tmp/trezor-test/node_modules/trezor-connect/lib/core/Core.js
- /tmp/trezor-test/node_modules/trezor-connect/lib/env/node/index.js
- /tmp/trezor-test/node_modules/trezor-connect/lib/index.js
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/trezor-test/node_modules/@trezor/rollout/lib/utils/fetch.js',
    '/tmp/trezor-test/node_modules/@trezor/rollout/lib/index.js',
    '/tmp/trezor-test/node_modules/trezor-connect/lib/data/FirmwareInfo.js',
    '/tmp/trezor-test/node_modules/trezor-connect/lib/data/DataManager.js',
    '/tmp/trezor-test/node_modules/trezor-connect/lib/core/Core.js',
    '/tmp/trezor-test/node_modules/trezor-connect/lib/env/node/index.js',
    '/tmp/trezor-test/node_modules/trezor-connect/lib/index.js',
    '<repl>'
  ]
}
```

**Expected behavior**

Importing `trezor-connect` v8.2.7-extended should work on Node v12 since it worked before.

Dropping Node v12 should be documented in the `CHANGELOG.md` and in the [`package.json`'s `engines` field](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines) that Node v12 is no longer supported:

**Additional context**

The issue seems to be in this line: https://github.com/trezor/trezor-suite/blob/36e436a764b4919e0ed0f5db1dc6b39035a2118a/packages/rollout/src/utils/fetch.ts#L1

`fs/promises` is not supported in Node v12. However, you can still import `promises` from `fs` and that should work in Node v12.

**Comment by bosomt** [comment]
@aloisklink @matejkriz  anything needed on QA side or can we move it to approved section ?

**Comment by sime** [comment]
@bosomt A sanity check would be appreciated.

**Comment by bosomt** [comment]
**QA OK**

Suite app works as expected.

**Info:**
 - Suite version: desktop 22.4.1 (157aec2030adbb7280d8b90ef0452df2a8400aff)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.4.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.0 regular
