### ISSUE TITLE
Cardano - showing token duplicates

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5116]
Hey one quick bug I've found is duplicate tokens showing up in the token interface. Upleading a screenshot here
![Screenshot from 2022-03-14 11-09-53](https://user-images.githubusercontent.com/16806380/158213814-94fa905b-cfa6-478b-bda1-016932692ff4.png)

_Originally posted by @5A4B48 in https://github.com/trezor/trezor-suite/issues/3550#issuecomment-1067010504_

**Comment by osintowl** [comment]
waiting for a few hours and a hard stop and start seems to have cleared this up.

**Comment by hynek-jina** [comment]
We were not able to replicate it anymore.
