### ISSUE TITLE
Fix handling asynchronicity of init process to prevent race conditions

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#5118]
@szymonlesisz have noticed that the init process is no longer synchronous which may (and probably is) causing race conditions on application start.
Main purpose of suiteMiddleware was to control the initialization process correct order until all essential data/prerequisites are initialized:
1. SUITE.INIT (should be first action ever) ->
2. LOAD STORAGE ->
3. LOAD LOCALES ->
4. INIT CONNECT ->
... (for more steps see suiteMiddleware)
5. SUITE.READY -> initialization done, now suite app is ready to do other stuff like render, fetch etc

Currently there are multiple actions that are fired up immediately on first render without respecting that order (see components in suite-web/src/Main.tsx and suite-desktop/src/index.tsx)
Potential race conditions:
1. Autodetect component is accessing the reducer state before LOAD STORAGE action (this one is probably handled by checking state.suite.storageLoaded)
2. Protocol component > saveCoinProtocol action (writing to state) may be called before LOAD STORAGE > STORAGE LOADED
3. Tor component > updateTorStatus action (writing to state) may be called before LOAD STORAGE > STORAGE LOADED
4. DesktopUpdater component actions (fetch, desktopApi, writing to state) are called in parallel to initialization

It probably starts when Tor component was placed above Preloader and then more components followed that pattern

Possibly related to https://github.com/trezor/trezor-suite/issues/3438 (One of the components (updater? tor?) is trying to write to indexeddb in the middle of db migration process)

**Comment by bosomt** [comment]
is there anything that we need/can check or regular testing /including checking error logs/ is good enough ?

**Comment by marekrjpolak** [comment]
> is there anything that we need/can check or regular testing /including checking error logs/ is good enough ?

Phew, everything I guess? No, the only specific thing which came to my mind is that the analytics is correctly initialized and works. Other than that, careful general testing (especially of application starting under various conditions) should be ok.
