### ISSUE TITLE
Data Analytics: custom backends

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#5122]
We would like to track use of custom backends. 

-   `suite-ready` (new attribute):
    -   `customBackends`: ['btc', 'eth', 'ada', ...] (array of coins with custom backend)
-   `settings/coin-backend` (new event):
    -   `symbol`: 'btc', 'eth', 'ada', ...
    -   `type`: 'default' | 'blockbook' | 'electrum' | 'ripple' | 'blockfrost'
    -   `totalRegular`: number
    -   `totalOnion`: number

**Comment by STew790** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/48477147/162755077-6ce643d4-941a-42b3-9d00-3b82ce742932.png)
![image](https://user-images.githubusercontent.com/48477147/162755156-588ccac2-240a-401d-8a70-b619b0fbc3bf.png)

**Info:**
 - Suite version: desktop 22.4.1 (157aec2030adbb7280d8b90ef0452df2a8400aff)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.4.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.0 regular
