### ISSUE TITLE
Data Analytics: language selection

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#5127]
- Which languages are being used.
- Track difference between manual selection or automatic system selection of a language.
- Track how many people manually switched away from automatic system option to English per each language. (i.e. they didn’t like the translation and switched to English against the language of their OS).

New attributes of event `settings/general/change-language`: 
- `previousLanguage`: Available Suite languages e.g. "en"
- `previousAutodetectLanguage`: boolean
- `autodetectLanguage`: boolean
- `platformLanguages`: platform languages separated by comma

New attributes of event `suite-ready`: 
- `autodetectLanguage`: boolean

**Comment by STew790** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/48477147/162753885-e31ee78a-5830-4f5c-8cca-a2c97d07308b.png)

**Info:**
 - Suite version: desktop 22.4.1 (157aec2030adbb7280d8b90ef0452df2a8400aff)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.4.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.0 regular
