### ISSUE TITLE
BAD gpg signature when verifying Linux Appimage 

### ISSUE THREAD

**Issue by dvreed** [trezor/trezor-suite#5133]
**Describe the bug**
I've imported  `satoshilabs-2021-signing-key.asc`, but when verifying the Appimage.asc file I get a BAD signature

**Info:**

-   Suite Version: 22.3.2
-   OS: Linux

**How to reproduce**
1. Import gpg key
```
gpg --import satoshilabs-2021-signing-key.asc 
gpg: key E21B6950A2ECB65C: 1 signature not checked due to a missing key
gpg: key E21B6950A2ECB65C: public key "SatoshiLabs 2021 Signing Key" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: next trustdb check due at 2023-08-21

```
2. Verify signature
```
gpg --verify Trezor-Suite-22.3.2-linux-x86_64.AppImage.asc 
gpg: assuming signed data in 'Trezor-Suite-22.3.2-linux-x86_64.AppImage'
gpg: Signature made Mon 14 Mar 2022 08:18:04 AM PDT
gpg:                using RSA key EB483B26B078A4AA1B6F425EE21B6950A2ECB65C
gpg: BAD signature from "SatoshiLabs 2021 Signing Key" [unknown]
```

**Expected behavior**
GPG should return a GOOD signature ie `Good signature from "SatoshiLabs 2021 Signing Key"`

**Comment by prusnak** [comment]
How did you download `Trezor-Suite-22.3.2-linux-x86_64.AppImage`? You might have a broken download.

They signature validates just fine here.

What is the hash of the downloaded file?

```
❯ sha256sum Trezor-Suite-22.3.2-linux-x86_64.AppImage
6a3739222afa54d0b6a9c5feeeb92754aa4f6cb4879b222ca3726722460d7c5e  Trezor-Suite-22.3.2-linux-x86_64.AppImage
```

**Comment by dvreed** [comment]
Yeah, you are right.  The download was bad for whatever reason.  I re-downloaed from suite.trezor.io and it now passes the GPG verification.  Sorry for the noise
