### ISSUE TITLE
Reproduce some of the TOR issue in suite app

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#5136]
Some people have mentioned that suite app is not very stable when TOR is running.

* User complained that did not  receive ETH tx although it is mined week ago 
* Tor connection crashed in meantime (without Suite realizing that).
* ....

**Comment by tsusanka** [comment]
Unfortunately this seems unreproducible, moving to https://github.com/trezor/trezor-suite/issues/5182, https://github.com/trezor/trezor-suite/issues/5137 and https://github.com/trezor/trezor-suite/issues/5140.
