### ISSUE TITLE
Native Electrum server connection from Umbrel

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5138]
Create a Pull request in the Umbrel repository that would allow direct connection of the Electrum server to the Trezor Suite natively from Umbrel.

https://github.com/getumbrel/umbrel-dashboard/tree/master/src/components/ConnectWallet/Wallets

**Comment by tsusanka** [comment]
I am moving this to HIGH as it would be really nice to make it till the feature is somewhat new.

**Comment by sime** [comment]
@tsusanka I offered a PR upstream. Please leave any comments there. https://github.com/getumbrel/umbrel-dashboard/pull/413

**Comment by tsusanka** [comment]
Haven't built it, but it seems great to me 👍. cc @marekrjpolak if he wants to check it.

**Comment by marekrjpolak** [comment]
I've fixed one unclosed `span` and added the new Trezor Suite page to the wallets list, and it looks good. Should I make a PR to the @sime's forked repo? Or will we do it differently?

![image](https://user-images.githubusercontent.com/26326960/162086157-c4a62097-e5e0-4e16-8a88-2890edde9c25.png)

**Comment by sime** [comment]
@marekrjpolak Glad you built it, as I was struggling a little. I add you as a collaborator to my fork. I suggest you push there so it's ready to go in the one PR.

**Comment by hynek-jina** [comment]
Everything done from our side. Now we are waiting for Umbrel to release a new version.
