### ISSUE TITLE
Improve TOR reliability with @trezor/request-manager

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#5140]
Improvements in TOR with [request-manager](https://github.com/trezor/trezor-suite/tree/feat/tor-request-manager/packages/request-manager) package.

Use  status event from Tor ControlPort to know when circuit is built and available so then connect starts trying connecting to the backends. It makes that the connection is more efficient because it starts trying to connect when circuit is really available.

**Comment by bosomt** [comment]
**QA OK**

Discovery of our old test passphrase with Tor enabled and all coins enabled:

22.5.2: 4min 00 sec
22.6.1:  1min 55 sec

not sure if its really related to issue or just luck with connectivity :)

**Info:**
 - Suite version: desktop 22.6.1 (8d37e21edabe10ea6b6991f5e3a338e3464925e1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by STew790** [comment]
**QA OK**

I tried the same passphrase with same versions:

22.5.2 ~ 5 minutes
22.6.1 ~ 2 minutes 30 seconds

**Info:**
 - Suite version: desktop 22.6.1 (8d37e21edabe10ea6b6991f5e3a338e3464925e1)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
