### ISSUE TITLE
Connect: BTC custom signTransation Error：VerifyTx: Wrong output amount at output 0. Requested: 600000000

### ISSUE THREAD

**Issue by aaurix** [trezor/trezor-suite#5145]
**Describe the bug**
I use btc sign custom Transction, the error is:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/7252280/158940535-2798e5ad-ea6f-439c-94c1-69158a557a93.png">

## sign code
```
const res = await TrezorConnect.signTransaction({
            coin: 'btc',
            inputs: inputs,
            outputs: outputs,
            refTxs: txs,
        })
        .catch(error => {
            console.log(`Error: ${error}`);
        })
        return res
```

## btc inputs:
```json
[{"address_n":[2147483693,2147483648,2147483648,0,0],"script_type":"SPENDMULTISIG","prev_index":1,"prev_hash":"26a0449e1192cf3b63d99de381df3935d6c1dddf150454e969d31a0c07a30144","multisig":{"pubkeys":[{"node":{"depth":0,"child_num":0,"fingerprint":0,"public_key":"03615bee4a2f2e80605be8730dc9630b002ad83b068a902df03b155797357030f7","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"address_n":[]},{"node":{"depth":0,"child_num":0,"fingerprint":0,"public_key":"037f8d0b44a282a89352b238b2d09f996df290aa65e0a95e6c99a445072ce390ce","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"address_n":[]},{"node":{"depth":0,"child_num":0,"fingerprint":0,"public_key":"0281687791324c3d99d9bd39370baf4c138b1e1670a9939a406e3ac22577e39c00","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"address_n":[]},{"node":{"depth":0,"child_num":0,"fingerprint":0,"public_key":"0386b58f51da9b37e59c40262153173bdb59d7e4e45b73994b99eec4d964ee7e88","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"address_n":[]},{"node":{"depth":0,"child_num":0,"fingerprint":0,"public_key":"0299b5c30667f2e80ddccbac8d112e52387fa1056ef2510c0b7a627215eb0a4550","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"address_n":[]},{"node":{"depth":0,"child_num":0,"fingerprint":0,"public_key":"02c179b0e69b342bf295200fa072bd2a4e956a2b74d7319c256946bc349c67d209","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"address_n":[]}],"signatures":["","","","","",""],"m":4}}]
```
## btc outputs

```
[{"amount":100000000,"address":"37DzisAW8DpyY2oqAfT3NfEwpG3SFVUUoR","script_type":"PAYTOADDRESS"},{"amount":182995,"address":"3LrrqZ2LtZxAcroVaYKgM6yDeRszV2sY1r","script_type":"PAYTOADDRESS"}]
```
### btc reftx
```
[{"lock_time":0,"version":1,"hash":"26a0449e1192cf3b63d99de381df3935d6c1dddf150454e969d31a0c07a30144","inputs":[{"prev_index":1,"sequence":4294967295,"prev_hash":"61514ecb55c5e8bb7fface4281ab58cc4b60fca0d1eeab85b36ad3cc2eb656a9","script_sig":"0047304402204dd6f9ccbb24677f67eb2475733940c87d722c11566120093b9527581b28b3a8022070a5d341b1c0d2f8422d026cb4abede3d28e7ca8cc339aacd75ebec5986510c901483045022100a499310fea03c68a7045e982d51dc2173624b3e43cb2adcf535c7823e04e9add0220739c56f7ccf46033807ffeb38fe48fa7db1ba9752be0a568c8c542a135ef398c01483045022100f38f38272c6c56de183f5d1e905a27573ea64ecb30d9c878ce57cab10de9564d0220649b919fe99f8e46bc949a64d16d3da608519dc175e693da5c9b45db4115184701483045022100a608bf17b47777ce96beee0f1cd56166d30db792660f1f50cbaa78019442cb1102206bfb2d1e8b2409e17e431443c6f13e1bf8065d15b92c882bf06c74292badcac2014ccf542102e2b2720a9e54617ba87fca287c3d7f9124154d30fa8dc9cd260b6b254e1d7aea210219fc860933a1362bc5e0a0bbe1b33a47aedf904765f4a85cd166ba1d767927ee2102b921cb319a14c6887b12cee457453f720e88808a735a578d6c57aba0c74e5af32102df92e88c4380778c9c48268460a124a8f4e7da883f80477deaa644ced486efc6210346aa7ade0b567b34182cacf9444deb44ee829e14705dc87175107dd09d5dbf4021034d3e7f87e69c6c71df6052b44f9ed99a3d811613140ebf09f8fdaf904a2e1de856ae"}],"bin_outputs":[{"amount":174000,"script_pubkey":"76a9147cab8a605af0fc643b523ff62325632ba54320a988ac"},{"amount":100201413,"script_pubkey":"a914d246f700f4969106291a75ba85ad863cae68d66787"}],"extra_data":null,"version_group_id":null}]
```

**Comment by aaurix** [comment]
We used to use the trezor.js signature correctly, after upgrading to the latest it doesn't work

**Comment by prusnak** [comment]
Maybe you need to provide amounts for Inputs.

**Comment by aaurix** [comment]
This is our code:
https://github.com/0xhelloweb3/trezor-sign-electron

**Comment by aaurix** [comment]
> You need to provide amounts for Inputs.
Input Raw Tx
```
01000000014401a3070c1ad369e9540415dfddc1d63539df81e39dd9633bcf92119e44a0260100000000ffffffff0200e1f5050000000017a9143cb48559ce25173abcc3af7452ce8c6e2791f90a87d3ca02000000000017a914d246f700f4969106291a75ba85ad863cae68d6678700000000
```
I have no idea about what happened for this error

**Comment by aaurix** [comment]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/7252280/158967741-bc1288a8-828f-4459-a333-0281a5d0311a.png">

**Comment by aaurix** [comment]
<img width="934" alt="image" src="https://user-images.githubusercontent.com/7252280/158968511-8ebeb34e-d2be-4eca-a293-07fcac629df5.png">

**Comment by aaurix** [comment]
We constructed input, output and refTx through the above code. I don't know the reason for this error. Is there something wrong with the constructed input and output?

**Comment by aaurix** [comment]
Do you need more information？

**Comment by sime** [comment]
@0xhelloweb3 I'm trying to get the error with your inputs. Do you get the same error using this template?
[signerror.html.gz](https://github.com/trezor/trezor-suite/files/8303047/signerror.html.gz)

In the future, please try and keep your reports to a single initial message; otherwise it can be hard to keep track of the conversation.

**Comment by aaurix** [comment]
> @0xhelloweb3 I'm trying to get the error with your inputs. Do you get the same error using this template? [signerror.html.gz](https://github.com/trezor/trezor-suite/files/8303047/signerror.html.gz)
> 
> In the future, please try and keep your reports to a single initial message; otherwise it can be hard to keep track of the conversation.
Yes, the trezor can be called up to sign, but an error like VerifyTx:Wrong output is reported

**Comment by aaurix** [comment]
> @0xhelloweb3 I'm trying to get the error with your inputs. Do you get the same error using this template? [signerror.html.gz](https://github.com/trezor/trezor-suite/files/8303047/signerror.html.gz)
> 
> In the future, please try and keep your reports to a single initial message; otherwise it can be hard to keep track of the conversation.

@sime  hello, i just update inputs and outputs，The multi-signature script restricts that only addresses contained in a specific public key can be signed.  
* inputs:
```json
[{"address_n":[2147483693,2147483648,2147483648,0,0],"script_type":"SPENDMULTISIG","prev_index":1,"prev_hash":"26a0449e1192cf3b63d99de381df3935d6c1dddf150454e969d31a0c07a30144","multisig":{"pubkeys":[{"node":{"depth":0,"child_num":0,"fingerprint":0,"public_key":"02e2b2720a9e54617ba87fca287c3d7f9124154d30fa8dc9cd260b6b254e1d7aea","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"address_n":[]},{"node":{"depth":0,"child_num":0,"fingerprint":0,"public_key":"0219fc860933a1362bc5e0a0bbe1b33a47aedf904765f4a85cd166ba1d767927ee","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"address_n":[]},{"node":{"depth":0,"child_num":0,"fingerprint":0,"public_key":"02b921cb319a14c6887b12cee457453f720e88808a735a578d6c57aba0c74e5af3","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"address_n":[]},{"node":{"depth":0,"child_num":0,"fingerprint":0,"public_key":"02df92e88c4380778c9c48268460a124a8f4e7da883f80477deaa644ced486efc6","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"address_n":[]},{"node":{"depth":0,"child_num":0,"fingerprint":0,"public_key":"0346aa7ade0b567b34182cacf9444deb44ee829e14705dc87175107dd09d5dbf40","chain_code":"0000000000000000000000000000000000000000000000000000000000000000"},"address_n":[]},{"node":{"depth":5,"child_num":0,"fingerprint":1724894461,"public_key":"034d3e7f87e69c6c71df6052b44f9ed99a3d811613140ebf09f8fdaf904a2e1de
```
* outputs:
```json
[{"amount":100000000,"address":"37DzisAW8DpyY2oqAfT3NfEwpG3SFVUUoR","script_type":"PAYTOADDRESS"},{"amount":182995,"address":"3LrrqZ2LtZxAcroVaYKgM6yDeRszV2sY1r","script_type":"PAYTOADDRESS"}]
```
* signedTx:
```json
[{"lock_time":0,"version":1,"hash":"26a0449e1192cf3b63d99de381df3935d6c1dddf150454e969d31a0c07a30144","inputs":[{"prev_index":1,"sequence":4294967295,"prev_hash":"61514ecb55c5e8bb7fface4281ab58cc4b60fca0d1eeab85b36ad3cc2eb656a9","script_sig":"0047304402204dd6f9ccbb24677f67eb2475733940c87d722c11566120093b9527581b28b3a8022070a5d341b1c0d2f8422d026cb4abede3d28e7ca8cc339aacd75ebec5986510c901483045022100a499310fea03c68a7045e982d51dc2173624b3e43cb2adcf535c7823e04e9add0220739c56f7ccf46033807ffeb38fe48fa7db1ba9752be0a568c8c542a135ef398c01483045022100f38f38272c6c56de183f5d1e905a27573ea64ecb30d9c878ce57cab10de9564d0220649b919fe99f8e46bc949a64d16d3da608519dc175e693da5c9b45db4115184701483045022100a608bf17b47777ce96beee0f1cd56166d30db792660f1f50cbaa78019442cb1102206bfb2d1e8b2409e17e431443c6f13e1bf8065d15b92c882bf06c74292badcac2014ccf542102e2b2720a9e54617ba87fca287c3d7f9124154d30fa8dc9cd260b6b254e1d7aea210219fc860933a1362bc5e0a0bbe1b33a47aedf904765f4a85cd166ba1d767927ee2102b921cb319a14c6887b12cee457453f720e88808a735a578d6c57aba0c74e5af32102df92e88c4380778c9c48268460a124a8f4e7da883f80477deaa644ced486efc6210346aa7ade0b567b34182cacf9444deb44ee829e14705dc87175107dd09d5dbf4021034d3e7f87e69c6c71df6052b44f9ed99a3d811613140ebf09f8fdaf904a2e1de856ae"}],"bin_outputs":[{"amount":174000,"script_pubkey":"76a9147cab8a605af0fc643b523ff62325632ba54320a988ac"},{"amount":100201413,"script_pubkey":"a914d246f700f4969106291a75ba85ad863cae68d66787"}],"extra_data":null,"version_group_id":null}]
```
Still the same error, I want to know the source of this error:

```
verify tx: The wrong output...
```

**Comment by sime** [comment]
@0xhelloweb3 The 'inputs' you posted are incomplete.

Please update the signerror.html, gzip it and post it back.

I suggest you reconstruct the inputs, outputs and refTxs insolation and share it.

**Comment by 0xhelloweb3** [comment]
[signerror-latest.html.zip](https://github.com/trezor/trezor-suite/files/8308643/signerror-latest.html.zip)
@sime hello, this is latest file

**Comment by aaurix** [comment]
> @0xhelloweb3您发布的“输入”不完整。
> 
> 请更新 signerror.html，将其压缩并回传。
> 
> 我建议你重建输入、输出和 refTxs 日照并分享。
@sime 
[signerror-latest.html.zip](https://github.com/trezor/trezor-suite/files/8308646/signerror-latest.html.zip)
hello, this is latest file.

**Comment by aaurix** [comment]
> @0xhelloweb3 The 'inputs' you posted are incomplete.
> 
> Please update the signerror.html, gzip it and post it back.
> 
> I suggest you reconstruct the inputs, outputs and refTxs insolation and share it.

The previous problem may be that the firmware version is too low, after upgrading the latest firmware version to 1.10.5, we encounter new errors:
**not enough founds**, But we have enough funds in our multi-signature account

![image](https://user-images.githubusercontent.com/7252280/159214250-bcb61f2e-b79d-416e-9bdf-857cf84d7632.png)

**Comment by aaurix** [comment]
> > @0xhelloweb3 The 'inputs' you posted are incomplete.
> > Please update the signerror.html, gzip it and post it back.
> > I suggest you reconstruct the inputs, outputs and refTxs insolation and share it.
> 
> The previous problem may be that the firmware version is too low, after upgrading the latest firmware version to 1.10.5, we encounter new errors: **not enough founds**, But we have enough funds in our multi-signature account
> 
> ![image](https://user-images.githubusercontent.com/7252280/159214250-bcb61f2e-b79d-416e-9bdf-857cf84d7632.png)

@sime Is there a possible reason for this error to help us troubleshoot

**Comment by sime** [comment]
@0xhelloweb3 I'm not familiar with your application. For ease of debugging, I suggest you produce a single JavaScript file which can reproduce this error.

For example, create a new project and add use `yarn add trezor-connect@extended`. Now you can run the Trezor stack without needing a browser. Please show an example how you are generate the inputs, outputs and refTxs. Also showing exactly which TrezorConnect methods you are using.

**Comment by aaurix** [comment]
@sime We have solved the problem
<img width="977" alt="image" src="https://user-images.githubusercontent.com/7252280/159643711-12e72704-a976-48dc-b9f9-7e1c123c1bcb.png">

By adding the amount field to the input，The problem is solved by adding the amount field to the input and ensuring that the amount is of type string, because there is also an amount field in the output, and the sdk has verified it. The root cause of this error is that the incoming amount is of type int, which causes the verification to fail.

Thanks for your patience!

**Comment by sime** [comment]
@0xhelloweb3 I'm glad it worked for you, and thank you for getting back to me.

Yes, `amount` is a [required field](https://github.com/trezor/connect/blob/a3e052bc9f84499c941547bee33e1b9e4ac003ed/src/ts/types/trezor/protobuf.d.ts#L286). :)
