### ISSUE TITLE
Custom backend connection 

### ISSUE THREAD

**Issue by elkimek** [trezor/trezor-suite#5147]
Hi,

I'm testing the new custom backend feature. I have two electrs 0.9.4 running in my local network and the only way I can connect from Suite is over .onion address. IP:PORT won't connect. I'm using the same server with Electrum/Sparrow without any connection issues.

Any ideas or ways to debug this? Thanks.

**Comment by sime** [comment]
@elkimek You tried the `:t` suffix? e.g. `IP:PORT:t`

**Comment by elkimek** [comment]
Yes I did. Without proper string it can't be even confirmed with the green Confirm button.

**Comment by sime** [comment]
@elkimek Are you running your node over SSL? Then you would need `:s` suffix. 

As for clearnet, does connecting to a public Electrum instance work? If that does, then it doesn't sound like a Trezor Suite issue.

**Comment by prusnak** [comment]
> Yes I did.

Please share the connection string you are using. If it is an external IP address you can replace it with 333.333.333.333. If it's a local IP address I think you can share it as verbatim. Thanks!

**Comment by elkimek** [comment]
192.168.1.10:50001:t

**Comment by prusnak** [comment]
> 192.168.1.10:50001:t

I can enter this connection string just fine and confirm via the Confirm button. 🤷

**Comment by elkimek** [comment]
Hm? I can too. The above reply was in a sense that if I haven't the correct string I wouldn't be able to confirm it.

///

I can connect to my electrum server over onion but not over clearnet. It's just clearnet that doesn't work. But it does with other apps Electrum/Sparrow.

**Comment by sime** [comment]
> As for clearnet, does connecting to a public Electrum instance work?

@elkimek What about public clearnet?

**Comment by elkimek** [comment]
I can connect to ```electrum.jochen-hoenicke.de:50099:t```

**Comment by sime** [comment]
@elkimek Is TOR on whilst you attempt to connect to your local clearnet Electrum server?

We have an Electrum server internally that is firewalled off from the public internet and I am unable connect to it when TOR is on.

**Comment by elkimek** [comment]
Yes that seems was the issue :) With Tor disabled, Suite connects to my electrum server immediately. Thanks!

**Comment by prusnak** [comment]
> Yes that seems was the issue :) With Tor disabled, Suite connects to my electrum server immediately. Thanks!

Thanks for confirmation. I am closing this issue and replacing it with https://github.com/trezor/trezor-suite/issues/5153
