### ISSUE TITLE
Custom backend UX ideas

### ISSUE THREAD

**Issue by elkimek** [trezor/trezor-suite#5148]
Hi,

I have some general ideas to improve the custom backend feature.

1) Add test connection button. The UX of adding a server is confusing. User have no way to know if Suite connected to the server without checking the Connection info. See how it works in Sparrow wallet.

https://i.postimg.cc/vTdNgnX8/2022-03-18-10-42-15.png

There is an icon in top menu with green checkmark which implies a connection to the custom server but hovering on it shows Backend is disconnected. This is kinda confusing as well.

2) Following the 1) it would be great to make the server row editable. When the connection doesn't work, user needs to delete it and type it all over again. When debugging the connection issues it can be very annoying.

3) Make the custom backend connections persistent. When user set some custom connections and the switch to Trezor Servers and back to Custom Electrum Servers those previously set connections are gone.

Thanks.

**Comment by hynek-jina** [comment]
Great ideas @elkimek.. thank you for your participation. 
1. `Test connection button` → I've noted it down. And we will consider it in UX improvements.
 -  We plan to improve communication of connection states soon. Currently it is in product specification phase.
2. `Editable server address` → Thanks. Same approach as for 1.
3. Working on that already. See https://github.com/trezor/trezor-suite/issues/5032

I will close this issue now and we can continue discussion on specific issues later on.
