### ISSUE TITLE
Small UI improvements of navigation

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5159]
- [ ] The Settings icon has more space on the right than above it. It should have both equally (12px)
![Group 1](https://user-images.githubusercontent.com/26002916/159281796-0fe9be5e-d586-46c5-a943-f8ebce747ff2.png)
- [ ] The space between the navigation icons is unnecessarily large. There doesn't need to be any space (0px) between hovered states. Currently there is an estimated 5px space _(shown by the red bar)_
![Group 2](https://user-images.githubusercontent.com/26002916/159281989-12bfd350-f008-4700-9326-e5937ff5ae1b.png)
- [ ] Highlight status icons in navigation
![Group 18624](https://user-images.githubusercontent.com/26002916/159282103-7f6dfbb3-63d6-427f-8ef9-6e168eb368b7.png)

**Comment by hynek-jina** [comment]
Related to: https://github.com/trezor/trezor-suite/issues/5157

**Comment by matejkriz** [comment]
Let's close this one, it will be soon redesigned.
