### ISSUE TITLE
Tooltips for navigation actions (menu items)

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#5162]
add Tooltips for navigation actions: 

- [ ] Discrete mode
- [ ] Custom backends
- [ ] Tor
- [ ] Early Access Program
- [ ] Notifications
- [ ] Settings

Maybe it would need some bigger refactoring for Tooltips, because I wasn't able to find a fix for this ugly behavior on click in reasonable time:

https://user-images.githubusercontent.com/3729633/159301093-db009d33-a6a8-4ca0-9f32-1ec14e05aa17.mov

Would be nice to implement it as a singleton (tooltip shown for only one menu item at a time) and to remove the delay for other items once the tooltip for the first item is opened.

**Comment by tomasklim** [comment]
In case we redesign how those icons are positioned (as we have a lot of them), there is a chance that this issue will be irrelevant.

**Comment by STew790** [comment]
**QA OK**
![image](https://user-images.githubusercontent.com/48477147/190606388-d833a5e9-fac4-4154-98d9-bb28c151c8c6.png)
![image](https://user-images.githubusercontent.com/48477147/190606468-2c3e1f89-3ff7-41ab-a90d-6c79960aeac4.png)
![image](https://user-images.githubusercontent.com/48477147/190606519-8ec21eca-42f0-4468-b0a7-e74f24a1a88a.png)
![image](https://user-images.githubusercontent.com/48477147/190606677-231f891d-ba05-4665-a412-c756faf5add5.png)
(It says "Activity" but I think that's ok)
![image](https://user-images.githubusercontent.com/48477147/190606728-71dabb1c-6587-4bcd-81e8-328ad8163ab8.png)
![image](https://user-images.githubusercontent.com/48477147/190606918-9229e5dd-5b41-47cb-8a0f-8d115c462cbb.png)

**Info:**
 - Suite version: desktop 22.10.0 (008aa81777bef6915fc912260b3213ce34ca6c36)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.10.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32
