### ISSUE TITLE
It is not possible to Send, Receive or Trade Cardano on mobile web version

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#5167]
**Describe the bug**
The option to Send, Receive or Trade Cardano is not possible on mobile web version of Suite. The 3 buttons or 3 dots that should be there are out of the screen on vertical view. If I switch to horizontal view, the 3 dots appear.

**Steps to reproduce:**
1. Start Suite in Chrome on Android
2. Connect your device
3. Enable Cardano
4. Go to your Cardano account
5. You can't see the 3 dots on the right

**Info:**
 - Suite version: web 22.3.0 (1fbbf2995ff816a1408670e728f4af874a3e6f83)
 - Browser: Mozilla/5.0 (Linux; Android 11; Redmi Note 9 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.58 Mobile Safari/537.36
 - OS: Linux armv8l
 - Screen: 393x873
 - Device: model T 2.4.3 regular

**Expected result:**
I am able to Send, Receive or Trade Cardano on mobile web version of Suite.

**Actual result:**
I am not able to Send, Receive or Trade Cardano on mobile web version of Suite.

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/159511759-01b113c7-eef3-4994-9e3b-862f171b012b.png)

**Comment by STew790** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/48477147/161981729-08b09b1a-e3ee-4c09-bb16-b087c4997560.png)


**Info:**
 - Suite version: web 22.4.1 (157aec2030adbb7280d8b90ef0452df2a8400aff)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device:

**Comment by STew790** [comment]
**QA NOK**
Unfortunately, this is back again. Weirdly it is only bugged for Cardano, SOL and ETH have three dots there.

![Screenshot_2024-03-19-16-44-32-628-edit_com android chrome](https://github.com/trezor/trezor-suite/assets/48477147/ef3a6a9f-e453-4644-931c-269157bc71ca)

**Info:**
 - Suite version: web 24.2.4 (748176286ae231aae44c83981a62b174b7605e1a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: WebUSB

**Comment by mroz22** [comment]
please go away. still an issue?

**Comment by STew790** [comment]
Well, Cardano is now OK after the empower redesign BUT :sweat_smile: there are some things a little broken now, sadly. But this has a really low prio. When I have an account that has longer "name", the send/receive button is "outside" of my screen but it appears when I scroll a little down.
![image](https://github.com/trezor/trezor-suite/assets/48477147/6d121079-7d38-4661-b24f-ab065a8c870b)
![image](https://github.com/trezor/trezor-suite/assets/48477147/df4168b1-8ccd-4097-a2b1-0ecf9c920bde)
![image](https://github.com/trezor/trezor-suite/assets/48477147/405581c9-7e55-446a-b995-7153cc069d84)

Nonetheless, I will close this because it essentially works and the web suite on mobile is not a priority right now since we have an app.
