### ISSUE TITLE
duplicated .pngs 

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#5174]
We have duplicated png files in the codebase. 

For example, [Coins.png](https://github.com/trezor/trezor-suite/blob/e34d1748b5636fb064a860cd1b3f9fc2d480c87a/packages/suite-data/files/images/suite/3d/coins.png) and [Coins@2x.png](https://github.com/trezor/trezor-suite/blob/4f7997e33e4646edc7275f0b1aec5599d5ec6e61/packages/suite-data/files/images/png/Coins@2x.png) are the same files, just different names. There is also [Coins@3x.png](https://github.com/trezor/trezor-suite/blob/4f7997e33e4646edc7275f0b1aec5599d5ec6e61/packages/suite-data/files/images/png/Coins@3x.png) which is actually a bigger image.

https://github.com/trezor/trezor-suite/blob/8ca2fe302e7730874763bff4ffd2263bf281a719/packages/suite/src/components/suite/images/Image/index.tsx#L18-L20

While this is not a big deal, it seems like a bug to me and it also does not make any sense to have same media files saved under different names.

**Comment by matejkriz** [comment]
Those makes sense at least for mobile app - React Native automatically pickup the size by the device screen density...

**Comment by MiroslavProchazka** [comment]
It seems that we need those for mobile app, closing for now
