### ISSUE TITLE
Wrong Rocket-Pool price

### ISSUE THREAD

**Issue by jiacheo** [trezor/trezor-suite#5176]
**Describe the bug**
Currently (2022-03-23 16:32:48 +08) rocket-pool price is about $31.7326 
In trezor suite's tokens view ,  I have totally 2005 RPLs but got total price $106,516.97 (about $53.12467 per RPL）

**Info:**

-   Remembered Wallet: no
-   Suite Version: Trezor Suite for macOS, 22.3.2.16437
-   Browser:-
-   OS: macOS 12.3
-   Bridge: ?
-   Firmware Version: model T, 2.4.3

**How to reproduce**
get some RPLs in an account

1. Go to 'Account'
2. Select and click a account name
3. click the 'tokens' tab

**Expected behavior**
need a right price for rocket-pool

**Screenshots**
<img width="765" alt="image" src="https://user-images.githubusercontent.com/1650931/159657894-51b7fa9e-ee52-431d-ac6a-c95d084e619b.png">

**Additional context**

**Comment by bosomt** [comment]
Closing. So far there was no other reports of incorrect ERC20 token prices.
Prices are provided by Coingecko wo there no way to fix it on other side if other coins or tokens are displayed correctly.
