### ISSUE TITLE
Connect fixtures are not compatible with firmware master branch

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-suite#5181]
Recently `firmware` tightened security checks of signing BTC transactions and since then Trezor can only sign inputs that belong to its private keys.

This seems to break quite a lot of `Connect` fixtures - `Connect` tests with the latest master `firmware` are for example here - https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/2242830131

As we were modifying our test-cases for BTC transaction signing to account for this, we can offer help with "fixing" the fixtures.

**Comment by sime** [comment]
cc: @mroz22 @szymonlesisz

**Comment by mroz22** [comment]
should be solved now
