### ISSUE TITLE
Unintentional disconnection of the labelling storage

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5187]
**Describe the bug**
When Suite is unaware of the loss of internet connection while the user is uses labelling, the connection to Dropbox or Google is disconnected. Meanwhile, the token is still valid, making the disconnection unnecessary.

**Steps to reproduce:**
1. Turn on labelling 
2. Disconnect from internet without having noticed it by Suite _(So for example stay on wifi or use mobile hotspot)_
3. Change some label

**Info:**
 - Suite version: desktop 22.3.2 (563be1e28ad75ddd4e38c2002e6032b0743511d2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: model 1 1.10.5 Bitcoin only

**Expected result:**
Cloud connection remains valid:
![Snímek obrazovky 2022-03-25 v 9 12 46](https://user-images.githubusercontent.com/26002916/160081086-a4d7a27c-21f1-44f9-9f45-6b86049ed128.png)

**Actual result:**
Labelling connection was cancelled:
![Snímek obrazovky 2022-03-25 v 9 12 17](https://user-images.githubusercontent.com/26002916/160081140-c8eabc98-b8eb-462e-b80f-4b57c8597158.png)

_Originally posted by @tsusanka in https://github.com/trezor/trezor-suite/issues/4849#issuecomment-1078727508_

**Comment by tsusanka** [comment]
I am bumping this to HIGH, because as it is a) low hanging fruit b) people that have 2FA set up in Dropbox and Google Drive have a terrible experience. If it is an easy fix, it would be great to do it.

**Comment by STew790** [comment]
**QA OK**

If I drop the internet connection, the connection to dropbox remains and doesn't disconnect and also correctly connects back when internet is available again. When I tried to rename some label, Suite shows a notification that it is not connected to internet.

![image](https://user-images.githubusercontent.com/48477147/171405901-7cb58b33-29f4-4db4-87f6-727fc2fc27fb.png)

**Info:**
 - Suite version: desktop 22.6.1 (8d37e21edabe10ea6b6991f5e3a338e3464925e1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
