### ISSUE TITLE
[Linux : AppImage] Trezor Suite v22.3.2 developer support for `--bridge-dev` is broken

### ISSUE THREAD

**Issue by brianddk** [trezor/trezor-suite#5190]
**Describe the bug**

When using [--bridge-dev](https://github.com/trezor/trezor-suite/blob/v22.3.2/packages/suite-desktop/src-electron/modules/bridge.ts#L8) with the [Trezor-T emulator v2.4.3+](https://github.com/trezor/trezor-firmware/blob/core/v2.4.3/core/Makefile#L159) account enumeration fails with an "Authorization" error described below

**Info:**

-   Remembered Wallet: yes
-   Suite Version: Linux AppImage v22.3.2
-   Browser: AppImage
-   OS: Ubuntu 21.10 on VirtualBox x64 VM
-   Bridge: 20.0.27
-   Firmware Version: Trezor-T emulator v2.4.3+ / commit: "aff3f51" or commit "core/v2.4.3"

**How to reproduce**

1. Clone `trezor-firmware` to `~/src/trezor-firmware`
2. Download `Trezor-Suite-22.3.2-linux-x86_64.AppImage` to directory `trezor-firmware/download`
3. In `trezor-firmware` checkout tag `aff3f51`
4. In `trezor-firmware/core` build target `build_unix` under `nix-shell`
5. Run the Emulator with the following script to reproduce the failure:

```shell
#!/bin/bash
tag="aff3f51"
src="$HOME/src/trezor-firmware"
appimage="Trezor-Suite-22.3.2-linux-x86_64.AppImage"
download="$src/download"
sudo systemctl stop trezord
cd "$src"
source $HOME/.nix-profile/etc/profile.d/nix.sh
BITCOIN_ONLY=0 PYOPT=0 PRODUCTION=0 nix-shell --run "cd core; poetry run ./emu.py -e -s -p tt -c true"
DEBUG=1 BITCOIN_ONLY=0 PYOPT=1 PRODUCTION=1 nix-shell --run "cd core; poetry run ./emu.py -p tt -c $download/$appimage --bridge-dev"
```

Observe the failure in dashboard and application log (`auth-failed`)

**Expected behavior**
Per the documentation in [core/emulator/index.md](https://github.com/trezor/trezor-firmware/blob/aff3f51/docs/core/emulator/index.md#how-to-run), the `--bridge-dev` switch should work.

**Screenshots**
![emu-auth-error](https://user-images.githubusercontent.com/5009148/160224697-b1f987c2-8146-4adb-a5d8-8e017718e6ea.gif)

**Additional context**
This is obviously of developer impact only.  It is worth noting that running the bridge with `-e` switch (`/usr/bin/trezord -e 21324`) still works allowing Suite to talk to the emulator without the `--dev-bridge` option.  This fails on both commit "aff3f51" or commit "core/v2.4.3"

Trezor-Suite Log: [auth-failed.zip](https://github.com/trezor/trezor-suite/files/8354666/auth-failed.zip)

**Comment by tsusanka** [comment]
(Seems to be working on macOS, tested on 554a4780f0ea58d30b32c7e5b39e3aed65044504)

**Comment by brianddk** [comment]
@tsusanka I'll have to build from `master`.  I used pre-packaged binaries which may be rather stale at this point.  Last commit was `563be1e` which is weeks old at this point.

**Comment by sime** [comment]
@brianddk I just stumbled upon this. Are you still battling this issue?

**Comment by brianddk** [comment]
> Are you still battling this issue?

I'm not running the build regularly.  It was a one-shot build when I hit it.  Glad you reproduced it.

**Comment by sime** [comment]
I meant, I stumbled upon the GH issue, not the reproduction 🙈

**Comment by brianddk** [comment]
Ahh... no, I'm not actively seeing it, but I'm picking up on current revisions.  I vote to close as inactive.  I'll reopen or reference this if the issue returns.
