### ISSUE TITLE
images not showing in Suite Guide

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#5206]
Per [Suite Guide documentation](https://github.com/trezor/trezor-suite-guide#not-all-types-of-rich-content-are-supported), images are supported and should be shown in Suite Guide. However, images are currently not showing.

The following pages currently contain images:
https://github.com/trezor/trezor-suite-guide/blob/master/en/suite-basics/early-access-program.md
https://github.com/trezor/trezor-suite-guide/blob/master/en/suite-basics/message-signing-and-verification/sign-and-verify-in-
https://github.com/trezor/trezor-suite-guide/blob/master/en/suite-basics/message-signing-and-verification/electrum-compatible-signatures.md

**Info:**
 - Suite version: web 22.4.0 (554a4780f0ea58d30b32c7e5b39e3aed65044504)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1440

**How to reproduce**
1. Open Suite Guide 
2. Go to Suite Basics > Early Access Program
3. Observe the lack of images

**Screenshots**
Suite Guide vs Gitbook repo
<img width="1316" alt="Screenshot 2022-03-31 at 18 02 24" src="https://user-images.githubusercontent.com/75733878/161099442-df0a395e-b438-48ea-9796-0fff8f652d91.png">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.5.0 (7281ac61483e38d974625c2505bfe5efd519aacb)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: 
 - Transport: N/A
