### ISSUE TITLE
Enable to change auto-update provider from CLI

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#5214]
The easier part is done - it's possible to change the[ feed URL for auto-updater](https://www.electron.build/auto-update.html#appupdatersetfeedurloptions) by CLI param `--updater-url=URL`.

And there is [a manual job `suite-desktop deploy autoupdate test` on codesign branch](https://github.com/trezor/trezor-suite/blob/3103598f45a9ee40d93e5108c928f778b40f169b/ci/releases.yml#L36) that uploads signed versions of apps on our server and make it available via VPN on https://suite.corp.sldev.cz/suite-desktop/codesign/

What is missing is to adapt [`verifySignature`](https://github.com/trezor/trezor-suite/blob/3103598f45a9ee40d93e5108c928f778b40f169b/packages/suite-desktop/src-electron/libs/update-checker.ts#L14) and [`getReleaseNotes`](https://github.com/trezor/trezor-suite/blob/3103598f45a9ee40d93e5108c928f778b40f169b/packages/suite/src/services/github.ts#L14) methods to work outside Github. 

**The goal is the full auto-update from different provider than GIthub to help us with testing auto-update from release candidate to a next version without interfering with Early Access Program.**

So far we are testing that by releasing the release candidate with lower version number and updating on the current latest production version but the problem is, that it is actually a downgrade so there could be an issue with e.g. DB migration.

**Comment by bosomt** [comment]
**QA OK**

tested on macARM,Win10 and Linux

**Info:**
 - Suite version: desktop 22.6.1 (8d37e21edabe10ea6b6991f5e3a338e3464925e1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular (revision 595b14254c1abb2be3f69e42c7932f1eca8cf1b1)
 - Transport: bridge 2.0.31
