### ISSUE TITLE
Allow decimal tx fees (ie 1.3 sat/vB)

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#5217]
**Describe the bug**
Currently, we enforce integers in the transaction fee dialog but we should also support decimals.

**How to reproduce**

1. Try to send a transaction
2. Set custom fee
3. Try to enter 1.3

**Screenshots**
![image](https://user-images.githubusercontent.com/1835345/161514754-e64b99c4-d85e-46d9-a6a1-48771d85c63e.png)

**Comment by hynek-jina** [comment]
Decimals wait for product specification: https://github.com/trezor/trezor-suite/issues/3252
AFAIK nodes commonly don't accept transactions with fee lower than 1 sat/vB

**Comment by hynek-jina** [comment]
Minimal fee of 1 sat/vB confirmed by @bosomt 
So this issue is only about decimals.

**Comment by hynek-jina** [comment]
I'm closing this issue in favour of original one: https://github.com/trezor/trezor-suite/issues/3252
