### ISSUE TITLE
trezor-connect tests followup

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#5221]
- [ ] create jobs matrix, split into smaller jobs (wait for https://github.com/trezor/connect/pull/1076)
- [ ] use WS and TX cache (see integration-tests/connect/README)
- [ ] update readme
- [ ] plugins tests in CI, see https://github.com/trezor/connect/pull/1050

**Comment by mroz22** [comment]
Since this issue was created, lot of progress has been made.
