### ISSUE TITLE
Recovery autocomplete jumping and clearing entered text

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#5231]
**Describe the bug**
Intermittently, when entering text seed phrase, the autocomplete dropdown will close and clear the already input text.

**Info:**

-   Suite Version: app, 22.3.2
-   OS: OS X 12.2.1
-   Firmware Version: T1

**How to reproduce**

1. Recover seed on T1
2. Choose normal recovery
3. Type "recycle" a number of times

**Expected behavior**
Text doesn't clear :)

**Screenshots**
Will attach in comment, GH is having issues.

**Comment by sime** [comment]
Note these direct reproducible cases, rather they are recordings of the odd behaviour.

**Typed `recycl` and dropdown was closed:**

https://user-images.githubusercontent.com/216917/161785729-7db2d75d-f2d7-47cc-bc47-3578129542b8.mp4

**Typed `rec` and dropdown was closed:**

https://user-images.githubusercontent.com/216917/161787681-9a6b587c-dd70-4109-9071-06d9c20fd841.mp4

**Comment by hynek-jina** [comment]
@sime Is this a bug? Or you just miss some communication from Suite?

**Comment by sime** [comment]
Bug

**Comment by STew790** [comment]
I just tried this on Linux and works fine for me. When I type "rec" or "recycle" or whatever word from the word-list, it doesn't close the drop-down menu for me. Do you press anything after you type the part of the word (or the whole word) or does it just close on its own?

**Info:**
 - Suite version: desktop 22.3.2 (563be1e28ad75ddd4e38c2002e6032b0743511d2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.11.0 regular

**Comment by sime** [comment]
@STew790 Thanks for trying to reconfirm my issue. I wasn't doing anything special, next restore I attempt I will try and reproduce this issue.

**Comment by hynek-jina** [comment]
We were not able to replicate that.. Please specify the steps to reproduce..
