### ISSUE TITLE
Inspect outdated dependencies

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#5239]
check `yarn outdated`, consider what to update/create issue for (there are some already, check [label:dependencies ](https://github.com/trezor/trezor-suite/issues?q=is%3Aissue+is%3Aopen+label%3Adependencies+))

**Comment by hynek-jina** [comment]
Issues already prepared:

- #5564
- #5563
- #5561
- #5535
- #3907
- #4650
- https://github.com/trezor/trezor-suite/issues/4655
- https://github.com/trezor/trezor-suite/issues/4649
- https://github.com/trezor/trezor-suite/issues/5531
- https://github.com/trezor/trezor-suite/issues/5532
- https://github.com/trezor/trezor-suite/issues/4651
- #5537
- https://github.com/trezor/trezor-suite/issues/4654

**Comment by tomasklim** [comment]
Many libraries were updated in this PR. Would be nice to test app thoroughly
