### ISSUE TITLE
Sending arbitrary ethereum transactions with MetaMask silently fails. Should give some sort of message at least

### ISSUE THREAD

**Issue by PaperHandedPuppy** [trezor/trezor-suite#5252]
Probably a dupe of https://github.com/trezor/connect/issues/784 , but that was closed without being properly resolved.

If you try to send an arbitrary Ethereum transaction with MetaMask, which is required to interact with nearly all dApps, it will silently fail. The Trezor Connect window pops up briefly and then closes before you can see anything, and the transaction shows in MetaMask as 'pending' indefinitely (until you quit the browser), but your Trezor never wakes up and asks you to confirm anything.

The solution is to change Trezor's "safety checks" from "strict" to "prompt", but this isn't immediately obvious and I spent hours figuring it out. A simple error message would have been very helpful: "Sorry, your Trezor's safety checks are set to strict, so sending this transaction has been blocked".

**Comment by sime** [comment]
@PaperHandedPuppy Which dApps are classic to fail?

**Comment by sime** [comment]
Next MetaMask release should resolve this. https://github.com/MetaMask/metamask-extension/pull/18302
