### ISSUE TITLE
Extend URI handler for altcoins

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5266]
Extend solution of https://github.com/trezor/trezor-suite/issues/3294
When user scans address with some of the listed prefix → system should open Trezor Suite and fill in the `send to` address

Litecoin `litecoin:`
Ethereum `ethereum:`
Ethereum Classic `ethclassic:`
XRP `ripple:`
Bitcoin Cash `bitcoincash:`
Bitcoin Gold `bitcoingold:`
Dash `dash:`
DigiByte `digibyte:`
Dogecoin `dogecoin:`
Namecoin `namecoin:`
Vertcoin `vertcoin:`
Zcash `zcash:`
Cardano `cardano:`

Related to: https://github.com/trezor/trezor-suite/issues/5241

**Comment by tomasklim** [comment]
Note:
Those URI handlers can be added only to the desktop app because they are `custom`. On the other hand, `bitcoin` is a permitted scheme so it can be available on both web and desktop platforms.

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler

**Comment by tomasklim** [comment]
Bitcoin-like coins' uri handler will now work in desktop app. 
```
    "litecoin",
    "bitcoincash",
    "bitcoingold",
    "dash",
    "digibyte",
    "dogecoin",
    "namecoin",
    "vertcoin",
    "zcash"
```

Other coins are moved to the follow-up issue #5508 as they might have a different implementation.

**Comment by bosomt** [comment]
**QA OK**

<img width="373" alt="Screenshot 2022-06-01 at 8 11 24" src="https://user-images.githubusercontent.com/31506317/171339451-20d54f25-79ff-467c-8dda-9c94ab0929bf.png">

Scan of Coinomi receive address including prefix:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/31506317/171339721-d1dfa8b4-8095-4d03-9935-9cffbd33595e.png">

**Info:**
 - Suite version: desktop 22.6.1 (8d37e21edabe10ea6b6991f5e3a338e3464925e1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular (revision 595b14254c1abb2be3f69e42c7932f1eca8cf1b1)
 - Transport: bridge 2.0.31
