### ISSUE TITLE
Autocorrect missing zero in amount

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5272]
When user type `.1` as an amount, convert it to `0.1`

Related to: https://github.com/trezor/trezor-suite/issues/5271

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.5.0 (0f6b428936d1ab6efe14e9e2fb2cb4d402bfdc67)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.6.0 Universal (revision 3b59d71093a56b7f396bd4aa6b5334a940223b67)
 - Transport: BridgeTransport 2.0.32
