### ISSUE TITLE
Show address anyway displayed when you try to backup wallet during discovery

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#5280]
**Describe the bug**
See video, `Create backup` modal is not consistent when triggered during discovery of accounts and you can see receive address modal.
I was not able to reproduce issue when discovery is over.

**Steps to reproduce:**
1. Connect device that needs backup and start discovery
2. Press `Create backup` and cancel it 
3. Repeat till you see different dialogue modal than usually

**Info:**
 - Suite version: desktop 22.4.1 (157aec2030adbb7280d8b90ef0452df2a8400aff)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.4.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.0 regular

**Screenshots:**
<img width="615" alt="Screenshot 2022-04-21 at 14 14 56" src="https://user-images.githubusercontent.com/31506317/164456677-5bc19a25-7910-413c-b951-ea850fc0eac3.png">

https://user-images.githubusercontent.com/31506317/164456686-5e127edb-e26f-4902-9f30-e3921aaaf2a9.mov

**Comment by komret** [comment]
I could not reproduce it.

**Comment by bosomt** [comment]
I was able to reproduce it.
During discovery you have to press create backup.
It wont happen every time.
I will try to replicate it on latest develop today.

https://github.com/trezor/trezor-suite/assets/31506317/82a72c4c-31b2-463d-a00a-20970fa94bc1

**Info:**
 - Suite version: desktop 23.8.1 (c6b91601f5c333a1de056fbf0b712995a96b5d90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.8.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
**QA NOK**

same results in dev app


**Info:**
 - Suite version: desktop 23.9.0 (db702eaeb7ee0a918db2c1c1d131f3f23624512f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

https://github.com/trezor/trezor-suite/assets/31506317/5b82bc40-71de-4182-a042-214053ff1037

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.9.0 (aa88709a704edb8127e63717e4b197d0bb6809f1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0
 - OS: MacIntel
 - Screen: 2160x1350
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
