### ISSUE TITLE
Add possibility to target 'revision' and bootloader version in messaging system

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#5282]
Add possibility to target specific FW revision (not version) using our messaging system. That means what the FW reports in the Features.revision.

While we are at it, it might also be useful to report the bootloader version.

@hynek-jina we would like to squeeze this into the next release.

**Comment by STew790** [comment]
**QA OK**

Tested with @tomasklim extensively.

**Info:**
 - Suite version: desktop 22.4.2 (1a1572b58bc0a76020978ab51ad85cbac0766aa1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.4.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.0 regular
