### ISSUE TITLE
Electrum server backend: each scripthash is called twice 

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#5285]
According to https://github.com/romanz/electrs/issues/702 the Suite queries each scripthash twice.

Is that intentional or is this a bug?

**Comment by marekrjpolak** [comment]
The response caching should prevent this from happening, but we have to be subscribed to the scripthashes first to make it work. Until now Suite was subscribing only explicitly, later in the discovery process. I'm going to do it implicitly for every scripthash request, which should resolve both this and https://github.com/trezor/trezor-suite/issues/5267.

**Comment by marekrjpolak** [comment]
I have the first results. It seems that enforced subscription resolves this and #5267 and improves the performance (discovery duration) by 40-60 % over clearnet and about 10-15 % when using Tor. But I still have to test it properly.

Btw @Kixunil may I ask how many opened scripthash subscriptions is electrs able to handle at once? In some rather excessive test case I have about 1200 subscriptions. Is it still ok?

**Comment by Kixunil** [comment]
@marekrjpolak according to my knowledge of the code I don't see any reason why thousands of subscriptions should be a problem. The complexity should be linear with a reasonably small constant. However I might be remembering it inaccurately and didn't test it.

**Comment by hynek-jina** [comment]
**What to test**
All these changes are related to the custom Electrum backend only (for BTC, TEST and REGTEST), so it's the only thing which must be tested (discovery, sending, receiving, notifications, ...). The only exception is the throttling mechanism in https://github.com/trezor/trezor-suite/commit/a4f4c06d7b8aa11a23cb5a053e0e658a8590af10 which affects all the backend types (but in theory shouldn't change anything). So please make sure that transactions notification works as expected even on different backend types.

**Comment by bosomt** [comment]
**QA OK**

tested multiple times during release candidates for 22.6 release.
TEST + BTC + Electrum server discovery and transactions /and multiple different coins/ sent.

**Info:**
 - Suite version: desktop 22.6.2 (f45c75705f153ec0dc44cb72fec2e5ec4a031b7c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: 
 - Transport: bridge 2.0.31
