### ISSUE TITLE
@trezor/connect: create @trezor/connect-webextension

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#5307]
Extract webextension logic to a separate package `@trezor/connect-webextension`
- [x] migrate @trezor/connect-examples/webextensions manifests to version 3 (multiple [breaking changes](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/))
- [ ] open/write `trezor-usb-permissions.html` dynamically 
- [x] move `trezor-content-script` to connect-popup
- [ ] communicate directly with the suite-desktop app using [runtime.connectNative](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/connectNative)

**Comment by haarts** [comment]
The Chrome Web Store [no longer accepts](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/) V2 web extensions.

Steps 1, 2 and 3 seem doable for me. Step 4, however, looks significantly more tricky. Is that also your assessment? Are you planning on working on this in the near future?

**Comment by mroz22** [comment]
done
