### ISSUE TITLE
Storybook: Add tests for default Link, full width Button

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#531]
- Link component without any prop (like `isGray`, `isGreen`, `hasNoStyle`) is probably not tested otherwise we would catch a "breaking" change 😬that happened recently. The link used to be green by default, now it is not styled anymore.
<img width="231" alt="Screenshot 2019-09-19 at 09 26 14" src="https://user-images.githubusercontent.com/6961901/65232702-dfd7e980-dad1-11e9-9e3c-f92456751280.png">

- Also we are missing a test for 100% width button, it worked not so long ago. (related issue https://github.com/trezor/trezor-suite/issues/386)
<img width="403" alt="Screenshot 2019-09-19 at 11 39 52" src="https://user-images.githubusercontent.com/6961901/65232892-3ba27280-dad2-11e9-882e-b272c5075177.png">

**Comment by keip** [comment]
> * Link component without any prop (like `isGray`, `isGreen`, `hasNoStyle`) is probably not tested otherwise we would catch a "breaking" change 😬that happened recently. The link used to be green by default, now it is not styled anymore.
> 
> <img alt="Screenshot 2019-09-19 at 09 26 14" width="231" src="https://user-images.githubusercontent.com/6961901/65232702-dfd7e980-dad1-11e9-9e3c-f92456751280.png">
> 

We have test for default link, it's in the paragraphs and by default it is green. I don't see change there.
But yes, we should add tests for all link styles too.

**Comment by slowbackspace** [comment]
> > * Link component without any prop (like `isGray`, `isGreen`, `hasNoStyle`) is probably not tested otherwise we would catch a "breaking" change 😬that happened recently. The link used to be green by default, now it is not styled anymore.
> > 
> > <img alt="Screenshot 2019-09-19 at 09 26 14" width="231" src="https://user-images.githubusercontent.com/6961901/65232702-dfd7e980-dad1-11e9-9e3c-f92456751280.png">
> 
> We have test for default link, it's in the paragraphs and by default it is green. I don't see change there.
> But yes, we should add tests for all link styles too.

Can you post a link where I can find it?
All I can see is that we test `Link` with some prop (`isGray`, `isGreen`), but not the default behaviour without these props, that's why you don't see any changes.

https://github.com/trezor/trezor-suite/blob/ec3c3960d391854b40aabc01775a363edf1ad52f/packages/components-storybook/src/stories/components/text.tsx#L61-L103

**Comment by keip** [comment]
Oh i see now. Okay so i think we have it wrong and we should change it now.
We have now 3 diferent props but i see it as single prop `style` to which you can send `gray` or `nostyle` and the default behaviour should be green.

What do you think?

**Comment by slowbackspace** [comment]
Yup, that will work! I would rather use different name for the prop though. `style` is [already reserved for inline styling](https://reactjs.org/docs/dom-elements.html#style). What about `variant`? It will be consistent with other components.

**Comment by keip** [comment]
> Yup, that will work! I would rather use different name for the prop though. `style` is [already reserved for inline styling](https://reactjs.org/docs/dom-elements.html#style). What about `variant`? It will be consistent with other components.

yes agree `variant` is better, style could be missleading because it can be also css style... 

So it should be like this:
`<Link />` default link is green
`<Link varian="gray" />` styled link is gray
`<Link varian="nostyle" />` unstyled link (no hover, no underline, color inherit)
