### ISSUE TITLE
Remove run-s dependency

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#5318]
We can replace `run-s` with simple `&&`. It's used only in few places anyway so most of our scripts won't work on Win anyway. I believe everyone who wants to develop seriously on Win uses linux subsystem anyway.

**Comment by Zagorrrr** [comment]
0xEF87B134ef94c07A6c7e73e7e37c1b5BDE7483eb

**Comment by mroz22** [comment]
looks like this has already been done
