### ISSUE TITLE
@trezor/connect version

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#5322]
- [ ] consolidate 'version' to be only in one place
- [ ] probably create version file in connect/src/data ? 
- [ ] probably create a function getConnectSrc that will do all the version parsing. Consider new versioning structure for version 9
- [ ] trezor-suite/packages/connect-web/src/webextension/trezor-usb-permissions.js should not import from anyhwere, this is a script that is intended to be copy-pasted. But, it should be possible to pass data from wehre this file is being opened, see trezor-suite/packages/connect-web/src/popup/index.ts (maybe query string, or chrome.tabs.create callback)

**Comment by martykan** [comment]
Stale issue, version is currently consolidated under `connect/src/data/version.ts`
