### ISSUE TITLE
@trezor/connect-popup: hardcoded urls

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#5326]
Urls in @trezor/suite are imported from constants folder. We try never to use url string directly which is a practice helping us avoid some dead urls as collection of urils saved in one place is easier to review and possibly test. 

@trezor/connect-popup still has hardcoded urls. 

Actionpoints: 
- extract hardcoded urls in trezor/connect-popup to a single constants file

Bonus action points:
- this file might be either inside @trezor/connect-popup project or we might consider creating a new package, lets say @trezor/urls that could be shared accross projects and CI tested.

**Comment by marekrjpolak** [comment]
**QA:**

Please check that external links are working in:
- Connect popup
- Landing page
- Browser detection page
- Suite (both web and desktop)

**Comment by STew790** [comment]
**QA OK**

- Connect popup :heavy_check_mark: 
- Landing page :heavy_check_mark: 
- Browser detection page :heavy_check_mark: 
- Suite (both web and desktop) :heavy_check_mark:
