### ISSUE TITLE
You can't upload one device `Homescreen` twice.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#5329]
**Describe the bug**
See uploaded video.
You can't upload one device `Homescreen` twice when you `Choose from gallery` between uploads
I was able to reproduce it in 22.3.2 and in 22.5.1 application.
I was not able to reproduce it on web version of Suite

**Steps to reproduce:**
1. Upload custom homescreen and upload it to device
2. Choose homescreen from gallery and upload it to device
3. Upload custom homescreen again and observe suite

**Info:**
 - Suite version: desktop 22.5.1 (06b93c51d07e8dfbd153c3e1569911884caf97a2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Screenshots:**

https://user-images.githubusercontent.com/31506317/166720248-001b7aa4-d003-47b6-8ca5-9d7f63545e94.mov

**Comment by bosomt** [comment]
**QA NOK**

still present

**Info:**
 - Suite version: desktop 22.8.2 (58f4c5bf0804e02c05c0b85e020b6e452b419164)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.2 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Bitcoin-only (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA NOK**

same behavior with new homescreen in TT


**Info:**
 - Suite version: desktop 23.5.0 (d8503ed15916297502826f65b8995a43e25c97ee)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.5.0 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32

**Comment by komret** [comment]
The bug can be reproduced by attempting to upload the same image twice, it is not necessary to open the gallery in between.

**Comment by bosomt** [comment]
**QA OK**

please move this issue to current sprint/release, 


**Info:**
 - Suite version: desktop 23.5.1 (3a3a0170978edcee49c99c17a428c4efeeba9dfc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.5.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
