### ISSUE TITLE
Cleanup of analytics

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5334]
Removing useless events, renaming and improving existing ones.

[Here](https://www.notion.so/satoshilabs/c63bdab01b704b099cab3bbb3227e1b1?v=406d107d6d584577a47d7580e8b2df89)

**Comment by matejkriz** [comment]
already tested by QA https://github.com/trezor/trezor-suite/pull/5472#issuecomment-1139423308
