### ISSUE TITLE
Send form [part 2]

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#534]
#### Address 
- [x] qr address modal
- [x] btc add more addresses
- [x] btc legacy and segwit address validation

 #### Amount
- [x] set max without rates (bug)
- [ ] erc-20 support

#### Additional form actions
- [ ] ethereum
- [x] xrp
- [x] bitcoin

####  Send
- [x] btc like transaction with modal 
- [ ] eth like transaction with modal 
- [x] xrp like transaction with modal 

#### Fees
- [x] load fees async

#### Reducer
- [x] save state to storage

#### Other
- [ ] responsive
- [ ] reducer and actions tests
- [x] network specific reducer

**Comment by TomasZorvan** [comment]
**Additional ideas**

- [ ] separate multiple recipients better, use line or different backgrounds for odd and even counts.
- [ ] send success notification should have link to blockbook transaction view
- [x] when you set `custom fee` and then set `normal fee` back the `normal fee` is strictly set to `1 sat/B`

**Comment by vladimirvolek** [comment]
Fixed fee in https://github.com/trezor/trezor-suite/pull/695

**Comment by glacierbits** [comment]
Duplicity.
