### ISSUE TITLE
`Install custom firmware' dialogue asks you to install older boot-loader than already installed

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#5341]
**Describe the bug**
See screenshot. I have same results with 22.5.1.
When you try to install custom firmware and device is in boot-loader mode /on firmware installed or you entered boot-loader mode before accessing `Install custom firmware` modal.
It ignores that you already have boot-loader 1.10.0 and asks you to install 1.8.0.

**Steps to reproduce:**
1. Connect device in boot-loader or with deleted firmware
2. proceed with `Install custom firmware` dialogue
3. You are asked to install 1.8.0 boot-loader even you have 1.10.0 boot-loader

**Info:**
 - Suite version: desktop 22.3.2 (563be1e28ad75ddd4e38c2002e6032b0743511d2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1  regular

**Screenshots:**
<img width="636" alt="image" src="https://user-images.githubusercontent.com/31506317/167018491-16d5051a-f326-4cd5-b977-05a3eb24a9ba.png">

```
bootloader_mode: True,
    firmware_present: True,
    major_version: 1,
    minor_version: 10,
    model: '1',
    patch_version: 0,
```

**Comment by hynek-jina** [comment]
Partially related to: https://github.com/trezor/trezor-suite/issues/4661

**Comment by bosomt** [comment]
I'm only able to reproduce it with **unsigned** firmwares like `trezor-fw-regular-1.11.1-85a26d2c.bin`.
Works as expected with `trezor-1.11.1.bin`

**Comment by bosomt** [comment]
**QA OK**



<img width="628" alt="image" src="https://user-images.githubusercontent.com/31506317/184297902-115f3181-bc14-4756-88d8-26696e8b8db7.png">

**Info:**
 - Suite version: desktop 22.9.0 (4d282475dccf0c52a0094e9b024fce5ad7c54e53)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.9.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.32
