### ISSUE TITLE
Enable sign message using change address

### ISSUE THREAD

**Issue by DrHaribo** [trezor/trezor-suite#5342]
It used to be possible to sign messages using a change address. Now the GUI has been updated with a drop-down menu instead of copy-pasting the address in. Change addresses are not available in the menu, so you can't sign messages with them.

**How to reproduce**

1. Go to 'sign & verify'
2. Click on 'address'
3. Impossible to select the address you want to use
4. You have to use Electrum instead

**Expected behavior**
Allow making signatures with all the addresses that are part of the wallet.

**Comment by hynek-jina** [comment]
Hi @DrHaribo,
could you please elaborate a bit what is the use case?
For what do you need such a functionality? Thank you.

**Comment by DrHaribo** [comment]
> For what do you need such a functionality?

This functionality is needed to prove that you control an address. For example during an audit, where the auditor wants to know whether the crypto holdings you claim to have are actually under your control.

**Comment by hynek-jina** [comment]
@DrHaribo 
Thank you,.. Before we implement that.. you can use `trezorctl`
https://wiki.trezor.io/Using_trezorctl_commands_with_Trezor#Sign_message

**Comment by DrHaribo** [comment]
@hynek-jina Thanks!

**Comment by jfburdet** [comment]
> @DrHaribo Thank you,.. Before we implement that.. you can use `trezorctl` https://wiki.trezor.io/Using_trezorctl_commands_with_Trezor#Sign_message

Starting from a change adress (found in your transaction) how do you compute it's derivation path ? I'm asking, because trezorctl sign-message needs you to input derivation path not "raw" adress.

**Comment by MiroslavProchazka** [comment]
The most easiest way would be to add new section to the dropdown menu with "Change address" header. Maybe there would be also need to adjust the view of derivation path - add positions before the /xy - 001/11 eg. 
cc @marekrjpolak correct me on this please.

![image](https://github.com/trezor/trezor-suite/assets/152851523/04f380da-a13e-4716-b8d5-9a9bfee13a4d)

**Comment by MiroslavProchazka** [comment]
cc @Hermez-cz

**Comment by bosomt** [comment]
**QA OK**

signed message using change address from this tx
https://tbtc1.trezor.io/tx/c29352f9c205c0e13a202840a79f78a4cd2b30b3429ad5b66006b290d51dcaf8
`tb1q9ql8yguj85fhh6wgwzrmermalrf0l8cu669t0v`



![Image](https://github.com/trezor/trezor-suite/assets/31506317/36f60ae7-c9be-495d-b7eb-36a20e87be16)



**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33
