### ISSUE TITLE
Suite uses incorrect default logo for T1

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#5347]
**Describe the bug**
See photos of default logo in Trezor Wallet and default logo in Trezor Suite.
Suite is not using default logo loaded in FW but it loads different logo /with old round design/ and device name is never again displayed. 

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: desktop 22.5.1 (06b93c51d07e8dfbd153c3e1569911884caf97a2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Screenshots:**
<img width="428" alt="image" src="https://user-images.githubusercontent.com/31506317/167352598-04131b22-8298-498e-b932-24dc2bfcf6d0.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/31506317/167352652-b73cc23b-97f1-4a1a-b41e-4d140ed679a2.png">

**Comment by bosomt** [comment]
**QA NOK**

same behavior on current version

**Info:**
 - Suite version: desktop 22.8.1 (4ddcf5c6b05fefda0425919434a936e534482a1e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32

**Comment by tomasklim** [comment]
@bosomt please check

**Comment by bosomt** [comment]
**QA OK**

checked it and it looks as expected on device display.

Maybe we can consider changing image `/static/images/homescreens/BW_64x128/original_t1b1.png` too in `Homescreen gallery` section

<img width="200" alt="Screenshot 2024-06-12 at 11 18 07" src="https://github.com/trezor/trezor-suite/assets/31506317/f8d08eb6-55ad-4855-a93f-47686e3b63fa">
