### ISSUE TITLE
Missing pictures in Trezor news section of dashboard

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#5348]
**Describe the bug**
We are missing pictures in Trezor news section of dashboard.
Reproduces on multiple computers/OS, same results in web and app version of Suite.
Issue is not persistent. Sometimes you see pictures sometimes not.
All you see is 403 error in console.

**Steps to reproduce:**
1. Load latest version of Suite on staging 22.5.1
2. Navigate to 'Dashboard'
3. Observe pictures.

**Info:**
 - Suite version: desktop 22.5.1 (06b93c51d07e8dfbd153c3e1569911884caf97a2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Screenshots:**
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/31506317/167358277-208a9022-8f6a-42c7-b036-33335db2e0b4.png">

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/31506317/167358388-16e3c1c6-dac3-4877-b7f0-87d80f6f0ac8.png">

**Comment by bosomt** [comment]
i was able to reproduce it on production server 

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/31506317/167361523-4cd20b8f-1dd4-42dc-a8ab-9c2a52dd40d4.png">

**Info:**
 - Suite version: web 22.4.3 (969161f41dcd889fa1fb0cf5e1d3437fddd8c26d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.1 regular

**Comment by hynek-jina** [comment]
It appears on older versions as well. So it is probraly not a Suite issue..

**Comment by sime** [comment]
Looks like security for cdn.trezor.io is too high? If it is only reverse proxying static assets, it may be worth reducing the security level in CloudFlare. @vdovhanych Is this something you would know?

Below is screenshot from my own CloudFlare account.
![Screenshot 2022-05-09 at 11 04 37](https://user-images.githubusercontent.com/216917/167377768-6a2f1d1a-1c5b-4754-a95b-9e60e1448f59.png)

**Comment by vdovhanych** [comment]
That's not on our end, cnd only rewrites the request to origin, meaning https://medium.comstatic/medium/images/max/1024/1*F%C3%9793-30MpUnmD360A.jpeg is not accessible at all. I would not reduce security as its likely not related to this.

**Comment by vdovhanych** [comment]
on one more look, is it possible medium changed the url for its static files?

**Comment by vdovhanych** [comment]
We will try to fix the URL handling on our CDN for this. I will notify you once I've done it.

UPDATE: So this is the issue of Medium (blog service provider) blocking many IPs from our cloud provider. Meaning our CDN that reforwards the request to blog is blocked, and no pictures are loaded. The trezor news API handles text, and it directly communicates through API with Medium.
cc @hynek-jina @sime

**Comment by STew790** [comment]
**QA OK**

There is now "news" section present now.

**Info:**
 - Suite version: desktop 22.6.0 (681bbc1c50d757d22cf77888090209eef0433915)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
