### ISSUE TITLE
deprecate old connect-explorer

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#5352]
I don't think we are going to commit anything here https://github.com/trezor/connect-explorer 

so please archive this repo.

**Comment by tsusanka** [comment]
And I will point to https://github.com/trezor/trezor-suite/tree/develop/packages/connect-explorer in the Readme correct?

**Comment by mroz22** [comment]
> And I will point to https://github.com/trezor/trezor-suite/tree/develop/packages/connect-explorer in the Readme correct?

yes. makes sense.

**Comment by tsusanka** [comment]
Done. Nothing to QA.
