### ISSUE TITLE
@trezor/connect missing tests fixtures

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#5353]
Add more @trezor/connect tests

### High priority
Before we go on with the release of newly migrated @trezor/connect version 9 (#5212), we should probably fill in gaps of missing tests fixtures. 

- [x] tezosSignTransaction https://github.com/trezor/trezor-suite/pull/5682
- [x] binanceGetAddress https://github.com/trezor/trezor-suite/pull/5682
- [x] binanceGetPublicKey https://github.com/trezor/trezor-suite/pull/5682

### Lower priority
These are either used only by @trezor/suite and tested through its integration tests or even migt not be testable at all (bootloader related tests). We should decide which of them should have tests in @trezor/connect and implement them.

- [ ] backupDevice
- [ ] blockchainDisconnect
- [ ] blockchainEstimateFee
- [ ] blockchainGetAccountBalanceHistory
- [ ] blockchainGetFiatRates
- [ ] blockchainGetTransactions
- [ ] blockchainSetCustomBackend
- [ ] blockchainSubscribe
- [ ] blockchainSubscribeFiatRates
- [ ] blockchainUnsubscribe
- [ ] blockchainUnsubscribeFiatRates
- [ ] changePin
- [ ] cipherKeyValue
- [ ] firmwareUpdate
- [ ] getCoinInfo
- [ ] getDeviceState
- [ ] getSettings
- [ ] pushTransaction
- [ ] rebootToBootloader
- [ ] recoveryDevice
- [ ] requestLogin
- [ ] resetDevice
- [ ] setProxy
- [ ] wipeDevice

**Comment by Hannsek** [comment]
@mroz22 is this still a thing?
