### ISSUE TITLE
suite-native: IconButton component

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#5357]
**Design:** [Figma](https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=48%3A2819)

<img width="659" alt="Screenshot 2022-05-09 at 15 21 10" src="https://user-images.githubusercontent.com/5837757/167419924-de93384c-1ba7-46ba-9e1a-1f6b55ce7629.png">
<img width="197" alt="Screenshot 2022-05-09 at 15 20 56" src="https://user-images.githubusercontent.com/5837757/167419932-b592f38b-ce62-40c3-864d-4242fbbc3488.png">

**Spec:** 
1. Recommended props:
```tsx
type IconButton = {
	icon: string, // (just id of icon, there will be type of all available once Icon component will be introduced)
    colorScheme?: ButtonColorScheme, // same as normal Button
    size?: ButtonSize // same as normal Button,
    isCircle?: boolean,
	onPress: () => void
}
```
2. Don't forget tests

**Comment by juriczech** [comment]
@Nodonisko @bouchja1 Is this IconButton going to be reusable also for things like icon in Input component for clearing texts etc? Currently working on the clear functionality of the input and am on crossroads whether it should be just Pressable with Icon inside or if this icon button would be suitable for that. 

https://tppr.me/i1ztv

**Comment by Nodonisko** [comment]
@juriczech Keep it simple, use Pressable or maybe better TouchableOpacity and normal Icon.
