### ISSUE TITLE
@trezor/connect stellar plugin

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#5358]
trezor-connect is being migrated from [old repository](https://github.com/trezor/connect/) to this place.

Asses the state of stellar 3rd party implementation. Are there some? Is @trezor/connect version 9 good enough for them to work?

We probably should create @trezor/connect-plugin-stellar [see in the old codebase here](https://github.com/trezor/connect/blob/develop/src/js/plugins/stellar/plugin.js) but there are multiple versions of stellar-sdk. It would be great if we were sure that the newly created plugin works with the latest version and has some tests also. 

cc: @overcat

related 
#4876 #4890

**Comment by overcat** [comment]
> Asses the state of stellar 3rd party implementation. Are there some? Is @trezor/connect version 9 good enough for them to work?

The latest trezor-connect version is 8.2.8, I'm not sure what you mean by **@trezor/connect version 9**.

There is a bug in the latest version that prevents `pathPaymentStrictSend` from working properly, I've submitted a PR to fix it, I know of the following services that use trezor-connect, only laboratory is currently affected by this bug
- https://laboratory.stellar.org/
- https://accountviewer.stellar.org/
- https://stellarterm.com/
- https://www.exodus.io/

> We probably should create @trezor/connect-plugin-stellar [see in the old codebase here](https://github.com/trezor/connect/blob/develop/src/js/plugins/stellar/plugin.js) but there are multiple versions of stellar-sdk. It would be great if we were sure that the newly created plugin works with the latest version and has some tests also.

It's great to create a separate package, I added some unit tests in https://github.com/trezor/connect/pull/1091, maybe we should add integration tests too

**Comment by sime** [comment]
> > Asses the state of stellar 3rd party implementation. Are there some? Is @trezor/connect version 9 good enough for them to work?
> 
> The latest trezor-connect version is 8.2.8, I'm not sure what you mean by **@trezor/connect version 9**.

v9 is the integration https://github.com/trezor/connect into the trezor-suite repository, which includes efforts to convert the codebase to TypeScript. You are right that it is not released yet.

**Comment by overcat** [comment]
🎉 #5450 has been merged, I will be integrating the new code in Stellar Laboratory this week to see if it works as expected.

**Comment by mroz22** [comment]
> tada #5450 has been merged, I will be integrating the new code in Stellar Laboratory this week to see if it works as expected.

I will let you know once this is released to npm

**Comment by mroz22** [comment]
@overcat please try 
https://www.npmjs.com/package/@trezor/connect-plugin-stellar
https://www.npmjs.com/package/@trezor/connect
https://www.npmjs.com/package/@trezor/connect-web

we are going to focus on updating docs now, so please let us know if there is something uncleare.

**Comment by overcat** [comment]
Hi @mroz22, I got an error when I tried to upgrade, could you please take a look?

code change: https://github.com/overcat/laboratory/pull/1/files
build log: https://github.com/overcat/laboratory/runs/6932210774?check_suite_focus=true

error info:
```js
Cannot find module '@trezor/transport/lib/types/messages' from 'node_modules/@trezor/connect/lib/constants/index.js'
```

**Comment by hynek-jina** [comment]
Will be tested by 3rd party.. No requirements on QA.

**Comment by mroz22** [comment]
Hi @overcat 
Your problem should be fixed now, try @trezor/connect-web version 9.0.0-beta.2
Just tried to build laboratory locally and it did work on my machine.

**Comment by overcat** [comment]
Hi @mroz22, got another error while running the test, which I think is caused by @trezor/connect.

log: https://github.com/overcat/laboratory/runs/6986247890?check_suite_focus=true

```
yarn test:jest

FAIL src/views/__tests__/EndpointExplorer.test.tsx
  ● Test suite failed to run
    Cannot find module '@trezor/connect-common/lib/storage' from 'node_modules/@trezor/connect/lib/core/AbstractMethod.js'
    Require stack:
      node_modules/@trezor/connect/lib/core/AbstractMethod.js
      node_modules/@trezor/connect/lib/api/applyFlags.js
      node_modules/@trezor/connect/lib/api/index.js
      node_modules/@trezor/connect/lib/core/method.js
      node_modules/@trezor/connect/lib/core/index.js
      node_modules/@trezor/connect/lib/index.js
      node_modules/@trezor/connect-web/lib/iframe/index.js
      node_modules/@trezor/connect-web/lib/index.js
      src/actions/transactionSigner.js
      src/reducers/transactionSigner.js
      src/config/store.ts
      src/helpers/testHelpers.tsx
      src/views/__tests__/EndpointExplorer.test.tsx
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/@trezor/connect/lib/core/AbstractMethod.js:[5](https://github.com/overcat/laboratory/runs/6986247890?check_suite_focus=true#step:5:6):43)
```

**Comment by mroz22** [comment]
ouch, you are right, sorry, I will need to improve my checks to prevent this. Working on that.

**Comment by mroz22** [comment]
Sooo, `9.0.0-beta.4` installs and runs tests but I get some other error running tests . This might be something with stellar plugin maybe? 

```
console.error
      RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
          at new NodeError (internal/errors.js:322:7)
          at boundsError (internal/buffer.js:83:11)
          at Buffer.readInt32BE (internal/buffer.js:481:5)
          at Cursor.read [as readInt32BE] (/home/mroz/repos/laboratory/node_modules/js-xdr/lib/cursor.js:169:38)
          at Object.read (/home/mroz/repos/laboratory/node_modules/js-xdr/lib/int.js:20:15)
          at Function.read (/home/mroz/repos/laboratory/node_modules/js-xdr/lib/enum.js:43:29)
          at Function.read (/home/mroz/repos/laboratory/node_modules/js-xdr/lib/union.js:111:36)
          at Function.fromXDR (/home/mroz/repos/laboratory/node_modules/js-xdr/lib/io-mixin.js:51:23)
          at new fromXDR (/home/mroz/repos/laboratory/node_modules/stellar-base/lib/transaction_builder.js:680:71)
          at /home/mroz/repos/laboratory/src/actions/xdrViewer.js:49:16 {
        code: 'ERR_BUFFER_OUT_OF_BOUNDS'

```

**Comment by overcat** [comment]
> Sooo, `9.0.0-beta.4` installs and runs tests but I get some other error running tests . This might be something with stellar plugin maybe?
> 
> ```
> console.error
>       RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
>           at new NodeError (internal/errors.js:322:7)
>           at boundsError (internal/buffer.js:83:11)
>           at Buffer.readInt32BE (internal/buffer.js:481:5)
>           at Cursor.read [as readInt32BE] (/home/mroz/repos/laboratory/node_modules/js-xdr/lib/cursor.js:169:38)
>           at Object.read (/home/mroz/repos/laboratory/node_modules/js-xdr/lib/int.js:20:15)
>           at Function.read (/home/mroz/repos/laboratory/node_modules/js-xdr/lib/enum.js:43:29)
>           at Function.read (/home/mroz/repos/laboratory/node_modules/js-xdr/lib/union.js:111:36)
>           at Function.fromXDR (/home/mroz/repos/laboratory/node_modules/js-xdr/lib/io-mixin.js:51:23)
>           at new fromXDR (/home/mroz/repos/laboratory/node_modules/stellar-base/lib/transaction_builder.js:680:71)
>           at /home/mroz/repos/laboratory/src/actions/xdrViewer.js:49:16 {
>         code: 'ERR_BUFFER_OUT_OF_BOUNDS'
> ```

I think this error is not caused by upgrading trezor libraries.

**Comment by overcat** [comment]
✅ I ran some tests and all test cases pass.

Version:
```
"@trezor/connect-plugin-stellar": "9.0.0-beta.1",
"@trezor/connect-web": "9.0.0-beta.4",
```

Device: Model T and Model One with the latest firmware

Laboratory url: https://laboratory-mihyld7ic-overcat.vercel.app/#txsigner?network=test

<details>
<summary>test cases</summary>

1. The XDR contains all Trezor supported operations:
`AAAAAgAAAACjaq9KQUVpnO9e09mXAoaUo/bORBjJRHz7oDqjowmeewAAD6ABb2zHAAAQKAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAtUcmV6b3IgVGVzdAAAAAAUAAAAAQAAAACjaq9KQUVpnO9e09mXAoaUo/bORBjJRHz7oDqjowmeewAAAAAAAAAAtGn4J8Joof5VAq9VhwERFiPjv/iBdLOwbVZIjMUu/rgAAAAC39wcNAAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAAGAAAAAVVTRAAAAAAAm466+JY4VR3PnqT3QyBxEGuHqw4ts9abdaU4InL3Wdh//////////wAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAAGAAAAAVVTRAAAAAAAm466+JY4VR3PnqT3QyBxEGuHqw4ts9abdaU4InL3WdgAAAAAAAAAAAAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAABAAAAALRp+CfCaKH+VQKvVYcBERYj47/4gXSzsG1WSIzFLv64AAAAAVVTRAAAAAAAm466+JY4VR3PnqT3QyBxEGuHqw4ts9abdaU4InL3WdgAAAAXSKs+cAAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAACAAAAAAAAAAA7veJgAAAAALRp+CfCaKH+VQKvVYcBERYj47/4gXSzsG1WSIzFLv64AAAAAVVTRAAAAAAAm466+JY4VR3PnqT3QyBxEGuHqw4ts9abdaU4InL3WdgAAAAAd3o+IAAAAAIAAAACQ0FUQ09JTgAAAAAAAAAAANNSjN1wrdfixw+4w0zmKXvxxikg6EKMi9SW1DnNPhNjAAAAAlBBTkRBAAAAAAAAAAAAAADTUozdcK3X4scPuMNM5il78cYpIOhCjIvUltQ5zT4TYwAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAANAAAAAAAAADaJVUHgAAAAALRp+CfCaKH+VQKvVYcBERYj47/4gXSzsG1WSIzFLv64AAAAAVVTRAAAAAAAm466+JY4VR3PnqT3QyBxEGuHqw4ts9abdaU4InL3WdgAACk9yQW7oAAAAAAAAAABAAAAAKNqr0pBRWmc717T2ZcChpSj9s5EGMlEfPugOqOjCZ57AAAABwAAAAC0afgnwmih/lUCr1WHAREWI+O/+IF0s7BtVkiMxS7+uAAAAAFVU0QAAAAAAQAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAAFAAAAAQAAAAC0afgnwmih/lUCr1WHAREWI+O/+IF0s7BtVkiMxS7+uAAAAAEAAAADAAAAAQAAAAQAAAABAAAA/wAAAAEAAAAKAAAAAQAAABQAAAABAAAAHgAAAAEAAAALc3RlbGxhci5vcmcAAAAAAQAAAABYkJIIPjHcUxojJLir8PT8aT9lilWS4KVQAqnjQrGXVQAAAAoAAAABAAAAAKNqr0pBRWmc717T2ZcChpSj9s5EGMlEfPugOqOjCZ57AAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAALRp+CfCaKH+VQKvVYcBERYj47/4gXSzsG1WSIzFLv64AAAACgAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAtoNV9p9SFDn/BDSqdDrxzH3r7QFdMAzlbF9SRSbkfW+AAAACgAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAdoNV9p9SFDn/BDSqdDrxzH3r7QFdMAzlbF9SRSbkfW+AAAACgAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAAMAAAAAAAAAAFVU0QAAAAAAJuOuviWOFUdz56k90MgcRBrh6sOLbPWm3WlOCJy91nYAAAAF5h3vuwAqmW/AADDUAAAAAAAAeJAAAAAAQAAAACjaq9KQUVpnO9e09mXAoaUo/bORBjJRHz7oDqjowmeewAAAAMAAAAAAAAAAVVTRAAAAAAAm466+JY4VR3PnqT3QyBxEGuHqw4ts9abdaU4InL3WdgAATdb/icAoAATduEAAAH0AAAAAAAAAAAAAAABAAAAAKNqr0pBRWmc717T2ZcChpSj9s5EGMlEfPugOqOjCZ57AAAABAAAAAAAAAABVVNEAAAAAACbjrr4ljhVHc+epPdDIHEQa4erDi2z1pt1pTgicvdZ2AAAAAAGGaaAAAEV/wAAw1AAAAABAAAAAKNqr0pBRWmc717T2ZcChpSj9s5EGMlEfPugOqOjCZ57AAAACAAAAAC0afgnwmih/lUCr1WHAREWI+O/+IF0s7BtVkiMxS7+uAAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAAKAAAABWhlbGxvAAAAAAAAAQAAAAV3b3JsZAAAAAAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAAKAAAACmJ5dGVzX2RhdGEAAAAAAAEAAAAUczinjy586kt+0QVo3/Jg11lamlYAAAABAAAAAKNqr0pBRWmc717T2ZcChpSj9s5EGMlEfPugOqOjCZ57AAAACgAAAAplbXB0eV9kYXRhAAAAAAAAAAAAAQAAAACjaq9KQUVpnO9e09mXAoaUo/bORBjJRHz7oDqjowmeewAAAAsBb2zHAAFvVAAAAAAAAAAA`

2. The XDR contains all Trezor supported operations, but the source of the operation is set to None:
`AAAAAgAAAACjaq9KQUVpnO9e09mXAoaUo/bORBjJRHz7oDqjowmeewAAD6ABb2zHAAAQKAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAtUcmV6b3IgVGVzdAAAAAAUAAAAAAAAAAAAAAAAtGn4J8Joof5VAq9VhwERFiPjv/iBdLOwbVZIjMUu/rgAAAAC39wcNAAAAAAAAAAGAAAAAVVTRAAAAAAAm466+JY4VR3PnqT3QyBxEGuHqw4ts9abdaU4InL3Wdh//////////wAAAAAAAAAGAAAAAVVTRAAAAAAAm466+JY4VR3PnqT3QyBxEGuHqw4ts9abdaU4InL3WdgAAAAAAAAAAAAAAAAAAAABAAAAALRp+CfCaKH+VQKvVYcBERYj47/4gXSzsG1WSIzFLv64AAAAAVVTRAAAAAAAm466+JY4VR3PnqT3QyBxEGuHqw4ts9abdaU4InL3WdgAAAAXSKs+cAAAAAAAAAACAAAAAAAAAAA7veJgAAAAALRp+CfCaKH+VQKvVYcBERYj47/4gXSzsG1WSIzFLv64AAAAAVVTRAAAAAAAm466+JY4VR3PnqT3QyBxEGuHqw4ts9abdaU4InL3WdgAAAAAd3o+IAAAAAIAAAACQ0FUQ09JTgAAAAAAAAAAANNSjN1wrdfixw+4w0zmKXvxxikg6EKMi9SW1DnNPhNjAAAAAlBBTkRBAAAAAAAAAAAAAADTUozdcK3X4scPuMNM5il78cYpIOhCjIvUltQ5zT4TYwAAAAAAAAANAAAAAAAAADaJVUHgAAAAALRp+CfCaKH+VQKvVYcBERYj47/4gXSzsG1WSIzFLv64AAAAAVVTRAAAAAAAm466+JY4VR3PnqT3QyBxEGuHqw4ts9abdaU4InL3WdgAACk9yQW7oAAAAAAAAAAAAAAABwAAAAC0afgnwmih/lUCr1WHAREWI+O/+IF0s7BtVkiMxS7+uAAAAAFVU0QAAAAAAQAAAAAAAAAFAAAAAQAAAAC0afgnwmih/lUCr1WHAREWI+O/+IF0s7BtVkiMxS7+uAAAAAEAAAADAAAAAQAAAAQAAAABAAAA/wAAAAEAAAAKAAAAAQAAABQAAAABAAAAHgAAAAEAAAALc3RlbGxhci5vcmcAAAAAAQAAAABYkJIIPjHcUxojJLir8PT8aT9lilWS4KVQAqnjQrGXVQAAAAoAAAAAAAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAALRp+CfCaKH+VQKvVYcBERYj47/4gXSzsG1WSIzFLv64AAAACgAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAtoNV9p9SFDn/BDSqdDrxzH3r7QFdMAzlbF9SRSbkfW+AAAACgAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAdoNV9p9SFDn/BDSqdDrxzH3r7QFdMAzlbF9SRSbkfW+AAAACgAAAAAAAAAMAAAAAAAAAAFVU0QAAAAAAJuOuviWOFUdz56k90MgcRBrh6sOLbPWm3WlOCJy91nYAAAAF5h3vuwAqmW/AADDUAAAAAAAAeJAAAAAAAAAAAMAAAAAAAAAAVVTRAAAAAAAm466+JY4VR3PnqT3QyBxEGuHqw4ts9abdaU4InL3WdgAATdb/icAoAATduEAAAH0AAAAAAAAAAAAAAAAAAAABAAAAAAAAAABVVNEAAAAAACbjrr4ljhVHc+epPdDIHEQa4erDi2z1pt1pTgicvdZ2AAAAAAGGaaAAAEV/wAAw1AAAAAAAAAACAAAAAC0afgnwmih/lUCr1WHAREWI+O/+IF0s7BtVkiMxS7+uAAAAAAAAAAKAAAABWhlbGxvAAAAAAAAAQAAAAV3b3JsZAAAAAAAAAAAAAAKAAAACmJ5dGVzX2RhdGEAAAAAAAEAAAAUczinjy586kt+0QVo3/Jg11lamlYAAAAAAAAACgAAAAplbXB0eV9kYXRhAAAAAAAAAAAAAAAAAAsBb2zHAAFvVAAAAAAAAAAA`

3. The XDR contains specific Timebounds:
`AAAAAgAAAACjaq9KQUVpnO9e09mXAoaUo/bORBjJRHz7oDqjowmeewAAAMgBb2zHAAAQKAAAAAEAAAAAYrUiFwAAAABitSIXAAAAAQAAAAtUcmV6b3IgVGVzdAAAAAABAAAAAQAAAACjaq9KQUVpnO9e09mXAoaUo/bORBjJRHz7oDqjowmeewAAAAsBb2zHAAFvVAAAAAAAAAAA`

4. The XDR contains ID Memo:
`AAAAAgAAAACjaq9KQUVpnO9e09mXAoaUo/bORBjJRHz7oDqjowmeewAAAMgBb2zHAAAQKAAAAAEAAAAAYrUiFwAAAABitSIXAAAAAgAAAAAAEtaHAAAAAQAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAALAW9sxwABb1QAAAAAAAAAAA==`

5. The XDR contains Hash Memo:
`AAAAAgAAAACjaq9KQUVpnO9e09mXAoaUo/bORBjJRHz7oDqjowmeewAAAMgBb2zHAAAQKAAAAAEAAAAAYrUiFwAAAABitSIXAAAAAzOJ6fDxpl8Zc2ys9UTC6CUxPoRH9WkjO7jbOapgfIiJAAAAAQAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAALAW9sxwABb1QAAAAAAAAAAA==`

6. The XDR contains Return Hash Memo:
`AAAAAgAAAACjaq9KQUVpnO9e09mXAoaUo/bORBjJRHz7oDqjowmeewAAAMgBb2zHAAAQKAAAAAEAAAAAYrUiFwAAAABitSIXAAAABDOJ6fDxpl8Zc2ys9UTC6CUxPoRH9WkjO7jbOapgfIiJAAAAAQAAAAEAAAAAo2qvSkFFaZzvXtPZlwKGlKP2zkQYyUR8+6A6o6MJnnsAAAALAW9sxwABb1QAAAAAAAAAAA==`

7. The XDR contains None Memo:
`AAAAAgAAAACjaq9KQUVpnO9e09mXAoaUo/bORBjJRHz7oDqjowmeewAAAMgBb2zHAAAQKAAAAAEAAAAAYrUiFwAAAABitSIXAAAAAAAAAAEAAAABAAAAAKNqr0pBRWmc717T2ZcChpSj9s5EGMlEfPugOqOjCZ57AAAACwFvbMcAAW9UAAAAAAAAAAA=`

8. The source of the operation in this XDR is not equal to the source of the transaction:
`AAAAAgAAAACjaq9KQUVpnO9e09mXAoaUo/bORBjJRHz7oDqjowmeewAAAMgBb2zHAAAQKAAAAAEAAAAAYrUiFwAAAABitSIXAAAAAQAAAAtUcmV6b3IgVGVzdAAAAAABAAAAAQAAAAC0afgnwmih/lUCr1WHAREWI+O/+IF0s7BtVkiMxS7+uAAAAAsBb2zHAAFvVAAAAAAAAAAA`

</details>

**Comment by hynek-jina** [comment]
@mroz22 Can we close the issue?

**Comment by mroz22** [comment]
I think we can close it for now. If there are still problems, @overcat can always reopen. So far thaks for collaboration!
