### ISSUE TITLE
@trezor/connect - unify bip39 words constants

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#5359]
bip39 words are duplicated (suite and connect). should be unified in one package.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.10.0 (22d82a98b0b62a463567c20f3fa21b94e4c0495c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
 - OS: MacIntel
 - Screen: 1848x1155
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32
