### ISSUE TITLE
Address field reports `Required` in Sign dialogue

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#5362]
**Describe the bug**
Address field reports `Required` when i select random one from drop down menu for first time.
When you select address for second time warning disappears.
I was only able to reproduce it on dev master and on on 22.3.2 or 22.5.1 version of Suite.

**Info:**
 - Suite version: web 22.6.0 (54abdebf4991620800bd7fe718fdb99f9efed80f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**How to reproduce**

1. Go to Sign dialogue
2. Select address from drop-down menu
3. Observe `Required` warning

**Screenshots**

<img width="770" alt="image" src="https://user-images.githubusercontent.com/31506317/167415696-af4f4f89-dd7b-4d20-924c-c446f7c93cbd.png">

**Comment by wendys-cats** [comment]
**QA OK on develop branch.** 

Tested against production (bug not present, OK) 22.4.3  and against  staging (bug present, as reported) 22.5.1 (06b93c51d07e8dfbd153c3e1569911884caf97a2). 

**Info:**
 - Suite version: web 22.6.0 (2166f57b6d39157dddf245e3e68778c7de9ddc42)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.5.0 regular (revision fd4f8601cf73c5744978f0e8c0aa43d863032a37)
 - Transport: bridge 2.0.31
