### ISSUE TITLE
Close/Continue buttons size inconsistency

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#5373]
**Describe the bug**
There is Close/Continue buttons size inconsistency in latest EAP version of Suite.
See screenshots, some of them are doubled , some not.

**Steps to reproduce:**
1. Update firmware or onboard device
2. Observe button sizes

**Info:**
 - Suite version: desktop 22.5.1 (33055e92e287a51213bde7a99eff05cb2edccc8e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.5 regular (revision 3f12742669bd782cac374a1750d517f4fd88c43b)
 - Transport: bridge 2.0.31

**Screenshots:**

22.5.1

<img width="633" alt="Screenshot 2022-05-11 at 10 21 56" src="https://user-images.githubusercontent.com/31506317/167803390-2f01482f-6d11-40b4-a2a5-26f59fae533b.png">

<img width="632" alt="Screenshot 2022-05-11 at 10 19 04" src="https://user-images.githubusercontent.com/31506317/167803406-63f84eac-d8a7-4a60-bc23-3081afd79dd9.png">

<img width="451" alt="image" src="https://user-images.githubusercontent.com/31506317/167804681-e2b6e878-f594-4556-b954-4f6290cea5c1.png">

22.3.2
![image](https://user-images.githubusercontent.com/31506317/167804491-bd0971ab-4001-425c-a814-30b5dffa6c4a.png)

**Comment by dahaca** [comment]
I actually already fixed it in my [PR](https://github.com/trezor/trezor-suite/blob/d1d62b52efdb7aabedef0c30472e57c76765bbb4/packages/suite/src/components/firmware/CheckSeed.tsx#L49) but will move that change to a separate one so that it can be merged outright.

**Comment by STew790** [comment]
**QA OK**

Button now correct size.

![image](https://user-images.githubusercontent.com/48477147/169284614-d793f6b8-b2b5-4ef1-b9c9-f864d8292520.png)

**Info:**
 - Suite version: desktop 22.6.0 (681bbc1c50d757d22cf77888090209eef0433915)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
