### ISSUE TITLE
Implement firmware hashing check

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#5377]
In latest FWs (2.5.1 and 1.11.1) we have introduced (https://github.com/trezor/trezor-firmware/pull/2239) a feature capable of hashing the contained firmware. We would like to check the hash against the correct one in Suite. If the check fails let's display the very same warning as [here](https://github.com/trezor/trezor-suite/pull/5291/files#diff-fea5400a179f06014a3400342669fdaec3d3f95d25b74d2e7f5728f8cef54dacR190).

@szymonlesisz will prepare the main business logic and then file a draft PR, we will take it from there.
@andrewkozlik can provide more details if needed.

**Comment by andrewkozlik** [comment]
The `FirmwareUpdate` method in trezor-connect should be extended with an additional step:
If the firmware version is >= 1.11.1 or >= 2.5.1, then after the firmware is uploaded trezor-connect should wait for the device to reboot into firmware mode and then validate the firmware hash. 

**Validation of the firmware hash**
1. Generate a random 32-byte challenge.
2. When the Trezor is in firmware mode send the `GetFirmwareHash` message with the `challenge` field set to the generated challenge. See protobuf definition [here](https://github.com/trezor/trezor-firmware/blob/bdfc453245c33101828122f5695ea0d9a1c9ca71/common/protob/messages-management.proto#L237-L253).
3. Trezor will respond with a `FirmwareHash` message.
4. Compute the expected hash of the firmware `.bin` file as demonstrated in [firmware_hash.py](https://github.com/trezor/trezor-firmware/blob/master/tools/firmware_hash.py). The tool does three things:
    i. In case of official T1 firmware the tool strips the old header (see the `offset` variable).
    ii. The firmware is padded to the right size with `0xFF` bytes, see `SIZE_T1` and `SIZE_T2`.
    iii. The result is hashed using Blake2s: `firmware_hash = blake2s(padded_firmware, key=challenge).digest()`.
5. Verify that the `hash` returned by Trezor is identical to the computed value.

**Error handling**
- If the hash validation fails, then the unofficial firmware warning should be shown to the user same as [here](https://github.com/trezor/trezor-suite/pull/5291/files#diff-fea5400a179f06014a3400342669fdaec3d3f95d25b74d2e7f5728f8cef54dacR190). trezor-connect should also connect to our server to log this incident.
- If the firmware update process is interrupted at any point, then in addition to any standard failure warnings like "firmware update failed" the user should also see "The firmware has not been validated!"

**Comment by szymonlesisz** [comment]
Implemented in `@trezor-connect` and partially in suite, feel free to take it from here

**Comment by matejkriz** [comment]
Implemented warnings:
(typos "deivce" and "connect" already reported)

modal:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/3729633/177785308-29c40270-52e9-4100-be76-df66832b7816.png">

baner after the modal is closed:
<img width="941" alt="image" src="https://user-images.githubusercontent.com/3729633/177785398-476e7195-3e39-440b-bb00-3d157d28ef49.png">

**Comment by tsusanka** [comment]
As for the copy, please let's use the agreed upon sentence `Your Trezor is running unofficial firmware. Please contact help@trezor.io immediately.`

**Comment by bosomt** [comment]
When i try to load `bad` firmware it works as expected.
But when i load it via trezorctl and `bad` firmware is already loaded in device i will get no warning during onboarding or receiving in Suite.

**QA NOK**

**Suite with already loaded firmware**:

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/31506317/177974747-c729b725-6760-4b51-914a-69709ffdb271.png">

**QA OK**
**Suite custom fw update**: ended up with empty device

Custom firmware `trezor-fw-regular-2.5.2-8e873d89`

<img width="624" alt="image" src="https://user-images.githubusercontent.com/31506317/177972779-8a1f34bf-6b73-432c-94ba-74b173bfb8d0.png">
 
Custom firmware `trezor-fw-regular-1.11.2-8e873d89`

<img width="634" alt="image" src="https://user-images.githubusercontent.com/31506317/177973643-2ee0f3d6-c6af-45b8-aa91-e897cd3caae9.png">


**Info:**
 - Suite version: desktop 22.7.1 (442452ee4244b602d3d0b2804f7f829c0216edf9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.2 regular (revision 8e873d89e580fec2bb165770144e8e918daf55d5)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
When i try to load `bad` firmware it works as expected.
But when i load it via trezorctl and `bad` firmware is already loaded in device i will get no warning during on-boarding or receiving in Suite.

**QA NOK**

**Suite with already loaded firmware**:

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/31506317/177974747-c729b725-6760-4b51-914a-69709ffdb271.png">

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/31506317/177980048-39d3a83a-d62c-49f4-b264-71f894839933.png">


**QA OK**
**Suite custom fw update**:

Custom firmware `trezor-fw-regular-2.5.2-8e873d89`

<img width="624" alt="image" src="https://user-images.githubusercontent.com/31506317/177972779-8a1f34bf-6b73-432c-94ba-74b173bfb8d0.png">

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/31506317/177975877-cc3c72e5-7e86-4345-83c1-a9d58bbcc914.png">

 
Custom firmware `trezor-fw-regular-1.11.2-8e873d89`

<img width="634" alt="image" src="https://user-images.githubusercontent.com/31506317/177973643-2ee0f3d6-c6af-45b8-aa91-e897cd3caae9.png">


**Info:**
 - Suite version: desktop 22.7.1 (442452ee4244b602d3d0b2804f7f829c0216edf9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.2 regular (revision 8e873d89e580fec2bb165770144e8e918daf55d5)
 - Transport: bridge 2.0.31

**Comment by mroz22** [comment]
> But when i load it via trezorctl and bad firmware is already loaded in device i will get no warning during on-boarding or receiving in Suite.

This is "expected". This feature was not implemented yet but might be in the future.

**Comment by STew790** [comment]
**QA OK**

After further discussion and testing with @mroz22 approving.
