### ISSUE TITLE
Transaction Signing error: session not found

### ISSUE THREAD

**Issue by Sticatel** [trezor/trezor-suite#5381]
Sign transaction error: session not found when I try to send BTC to my other non-trezor wallet.

Tried with different USB ports as well cables.

-   Suite Version: App 22.4.3 
-   OS: Linux Debian 11 KDE Kernel version: 5.10.0-13-amd64
-   Bridge: version 2.0.27
-   Firmware Version: model T 2.4.3
-   Tor is enabled on the app 

1. Go to your bitcoin account
2. Click on Send
3. Insert Address as well amount
4. Select any fee (I used Economy and Normal)
5. Click on Review & Send
6. Confirm transaction that shows in Trezor
7. Hold to sign transaction
8. While is signing the transaction(The circle loading icon in Trezor) wait a few mins
9. Sign transaction error: session not found appears on Suite while Trezor still shows signing transaction

**Expected behavior**
Send without any errors BTC.

**Screenshots**
![image](https://user-images.githubusercontent.com/66391171/167947039-c6703cd7-c779-4678-9435-d257105f4228.png)

**Comment by hynek-jina** [comment]
@sebas05000 
Thank you for your input. However it seems too general to be reproduced. Please contact our support! Thx
https://trezor.io/support/
