### ISSUE TITLE
Win 10 connection issue

### ISSUE THREAD

**Issue by Liopus** [trezor/trezor-suite#5384]
**Describe the bug**
New Trezor can not connect with Win 10. 

- Bridge installed
- Win Update up to date
- original wire used
- alternative wire used
- reinstalation of Trezor Suite
- reset of PC
- web browser (on chrome) tried
- no firewall or any special SW in PC
=> PC did not recognize the device. Same device worked on MacBook with original wire.

our solution - Wallet has been created on MacBook and after the Windows recognised the Trezor. The same device with same settings and wire.
So, issue is solved, but you should know about it.

Best regards

**Comment by hynek-jina** [comment]
@Liopus 
Thank you for your input. However it seems too general to be reproduced. Please contact our support! Thx
https://trezor.io/support/
