### ISSUE TITLE
Blog article banners not loading properly in Trezor Suite

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-suite#5389]
**Describe the bug**
Blog article banners not loading properly in Trezor Suite. Only happens to few recent ones.

**Info:**

-   Suite Version: app/web, latest
-   Browser: Chromium, Version 99.0.4844.51 (Official Build) (64-bit)
-   OS: NixOS 21.11 (Porcupine); Build ID: 21.11pre-git

**How to reproduce**
1. Log into Suite
2. Go to blog section

**Expected behavior**
Article banners should load properly

**Screenshots**
![image](https://user-images.githubusercontent.com/37402530/168565481-b95994ba-3046-447f-b589-9c3e4cd9a4aa.png)

**Comment by hynek-jina** [comment]
Duplicity of: https://github.com/trezor/trezor-suite/issues/5348

**Comment by yohaaan** [comment]
I always fail to find the other issue 😢
