### ISSUE TITLE
@trezor/connect-analytics

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5397]
Add analytics to connect popup
- [x] Create `@trezor/connect-popup-analytics` 
- [x] Create new data endpoints
    - [x] `https://data.trezor.io/connect/log/develop.log`
    - [x] `https://data.trezor.io/connect/log/stable.log`
- [x] Decide web / desktop endpoints

**Comment by bosomt** [comment]
**QA OK**

tested at suite.corp.sldev.cz/connect/develop
