### ISSUE TITLE
Suite installs intermediary firmware 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#5398]
**Describe the bug**
Suite installs intermediary firmware when you try to reinstall 1.11.1 firmware.
See screenshots.
You will eventually end up with bricked device.
Device recovered by trezorctl firmware-update -f trezor-1.11.1.bin

**Steps to reproduce:**
1. Install latest firmware version via Suite
2. Reinstall latest firmware version via Suite
3. Observe

**Info:**
 - Suite version: desktop 22.5.2 (87bec8157989666bf6cbe294d1af4dda925a3a20)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: 
 - Transport: bridge 2.0.31

**Screenshots:**
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/31506317/168771201-1e6ae907-92a9-4b38-851b-9499b772dec5.png">

<img width="448" alt="image" src="https://user-images.githubusercontent.com/31506317/168771279-ecf9a598-edcc-4b07-9ce7-862465cdc789.png">

<img width="480" alt="image" src="https://user-images.githubusercontent.com/31506317/168771387-6f77c29f-a76c-4721-8e64-7f5531c9b424.png">

**Comment by sime** [comment]
To avoid future foot guns, turn this console warning into a modal, informing the user what action is about to happen.

I don't have all the context (I'm hazy how intermediary FW actually works), so feel free to shoot me down:

![intermediary-fw-modal](https://user-images.githubusercontent.com/216917/168775413-2fe4ee7c-ea90-4703-bbdb-7de6af81b2c3.png)

**Comment by matejkriz** [comment]
I believe the bug is fixed in https://github.com/trezor/trezor-suite/commit/a4ec55219fe123c0bb073d4b8338041eb176add4, right @bosomt?

**Comment by bosomt** [comment]
**QA OK**

@matejkriz right !

**Info:**
 - Suite version: desktop 22.5.2 (a4ec55219fe123c0bb073d4b8338041eb176add4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by matejkriz** [comment]
> To avoid future foot guns, turn this console warning into a modal, informing the user what action is about to happen.
> 
> I don't have all the context (I'm hazy how intermediary FW actually works), so feel free to shoot me down:
> 
> ![intermediary-fw-modal](https://user-images.githubusercontent.com/216917/168775413-2fe4ee7c-ea90-4703-bbdb-7de6af81b2c3.png)

The purpose of intermediary FW is to simplify the process of upgrading FW from older T1 devices, that can't install the latest FW directly. So instead of upgrading to 1.6.3 and then do the same process again to upgrade to the latest, user could always click to install the latest and the gradual upgrade (installing intermediary first and then the latest) happens under the hood.

Intermediary should not be installed if you are not upgrading from FW < 1.6.2, so that was a bug.

**Comment by bosomt** [comment]
already solved
