### ISSUE TITLE
Suite menu items design is broken

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5399]
**Describe the bug**

- Dashboard focus shade does not have a top gap
- Accounts text is not in the middle (maybe dashboard and accounts should be aligned to left)
- Accounts focus shade left gap is bigger than the dashboard left gap
- When you are on the dashboard/in accounts, the menu item font is bigger and cannot be focused/clicked again.

**Info:**

-   Suite Version: 22.5.2/22.6.0

**How to reproduce**
1. Open menu on small screen

**Screenshots**
![Screenshot 2022-05-17 at 10 58 10](https://user-images.githubusercontent.com/33235762/168774044-05ed3be3-a92c-446b-82e3-24f8675b8f36.png)
![Screenshot 2022-05-17 at 11 07 30](https://user-images.githubusercontent.com/33235762/168774760-5f3e64e3-b97a-43b3-9ed8-94020966c3c2.png)
![Screenshot 2022-05-17 at 11 12 00](https://user-images.githubusercontent.com/33235762/168775368-51332d33-587d-4051-9074-60174df88642.png)

**Comment by hynek-jina** [comment]
Not an issue within new design...
