### ISSUE TITLE
Missing bottom gap under "Complete setup" button in final onboarding step

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5400]
**Info:**
-   Suite Version: app, 22.5.2

**How to reproduce**

1. Go to final onboarding step and have small window

**Screenshots**
![Screenshot 2022-05-17 at 11 06 23](https://user-images.githubusercontent.com/33235762/168775893-ec60b6ef-e52e-4ed0-8416-779ef1962e2e.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.6.1 (8d37e21edabe10ea6b6991f5e3a338e3464925e1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
