### ISSUE TITLE
Install custom firmware - Learn more

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5403]
**Describe the bug**
Install custom firmware `Learn more` button is pointing to https://wiki.trezor.io/Firmware_downgrade but it is a welcome page.

**Screenshots**
![Screenshot 2022-05-17 at 11 29 04](https://user-images.githubusercontent.com/33235762/168778865-39407be2-ee78-493f-bc1f-8203e5a23b34.png)

**Comment by jerechinsky** [comment]
Fixed it by adding links to firmware downgrade pages of Model T and Model One

**Comment by bosomt** [comment]
**QA OK**

new link is https://wiki.trezor.io/Firmware_downgrade

**Info:**
 - Suite version: desktop 22.5.2 (a4ec55219fe123c0bb073d4b8338041eb176add4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision a1d22890ee6a9ffec4edfc6e1b5b6c74d23855a3)
 - Transport: bridge 2.0.31
