### ISSUE TITLE
Analytics: 'select-wallet-type' always reports standard wallet type

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5407]
**Describe the bug**
It works in 22.1.1 but it does not work in 22.2.3

```
  case SUITE.AUTH_DEVICE:
      analytics.report({
          type: 'select-wallet-type',
          payload: { type: action.payload.walletNumber ? 'hidden' : 'standard' },
      });
      break;
```

`walletNumber` is always `undefined` so wallet type is always `standard`

**Info:**

-   Suite Version: 22.5.2
-   Firmware: 1.11.1

**How to reproduce**

1. Open DevTools
2. Add hidden wallet
3. Check `select-wallet-type` analytics request
4. See that wallet type is `standard`

**Comment by kolomaznikt** [comment]
It would be great to have automated tests so things like this don't happen, or we catch them quickly.

**Comment by matejkriz** [comment]
already tested by QA https://github.com/trezor/trezor-suite/pull/5472#issuecomment-1139423308
