### ISSUE TITLE
SelectableListItem + ListItem component

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#5419]
**Design:** [Figma](https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=40%3A1185)
![Screenshot 2022-05-17 at 20 17 08](https://user-images.githubusercontent.com/5837757/168883322-71953e4a-cc1a-46ac-8190-caf92bbeb628.png)
![Screenshot 2022-05-17 at 20 16 59](https://user-images.githubusercontent.com/5837757/168883330-5f3079c3-81a6-4924-872e-199a8e7e2276.png)
![Screenshot 2022-05-17 at 20 16 41](https://user-images.githubusercontent.com/5837757/168883335-cca85e08-d10d-4331-a2aa-aa8aadcdecae.png)

**Spec:**
1. Consider creating 3 components:
```tsx
// won't be exported to public
type BaseListItem = {
	icon?: IconType,
	title: string,
	subtitle?: string,
	onPress?: () => void
	rightComponent?: React.ReactNode
}

type ListItem = {
	hasRightArrow: boolean,
} & BaseListItem

type SelectableListItem = RadioButtonProps & Omit<BaseListItem, 'onPress'>;
```

**Prerequisities:**
RadioButton #5416

**Comment by bouchja1** [comment]
@Nodonisko What is a purpose of **rightComponent?: React.ReactNode** in BasicListItem type? Is it just for passing Radio/Checkbox/Whatever for _SelectableListItem_? Does it make sense to use it for _ListItem_ too? Despite it has its own **hasRightArrow** prop to show an arrow?

**Comment by Nodonisko** [comment]
@bouchja1 Yea, it's for passing whatever component you need, but it doesn't make sense for ListItem since only possible component for ListItem is right arrow.
