### ISSUE TITLE
Modal header on mobile screen

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5424]
**Describe the bug**
- Bulb is over text if text is too long.
- margin/padding on mobile is unnecessarily big

**Info:**

-   Suite Version: web, 22.6.0

**How to reproduce**
a. Open a modal with long text. E.g. `Xpub`
b. Check margin/padding via devtools

**Screenshots**
![Screenshot 2022-05-18 at 9 44 51](https://user-images.githubusercontent.com/33235762/168988024-eefd221c-04d0-4262-b3ad-a9967cf0f227.png)
![Screenshot 2022-05-18 at 9 51 37](https://user-images.githubusercontent.com/33235762/168988031-8060e801-e113-42d8-8af7-dceadd86f17d.png)

**Comment by dahaca** [comment]
No longer an issue
<img width="372" alt="image" src="https://user-images.githubusercontent.com/45338719/187095290-ada90c4d-4e6e-4187-9d0a-7ff7f84cb1a9.png">
