### ISSUE TITLE
suite-native: Setup mobile app build for Android with Github actions

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#5429]
- Setup CI build using created fastlane lanes for Android
- use Github CI

Related to https://github.com/trezor/trezor-suite/issues/5521

**Comment by vdovhanych** [comment]
What do you mean by mobile app for macOS?

**Comment by bouchja1** [comment]
> What do you mean by mobile app for macOS?

Title and desc updated to be more clear.
