### ISSUE TITLE
Automate adding to projects

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5431]
**Issues**
- [ ] When there is a new issue with `mobile-app` label add it to project `Suite Mobile`.
  -  Otherwise add that issue to `Suite Desktop` project.
- [ ] Then rename the project `Issues Suite` to `Suite Desktop`
- [x] Remove automated adding to project `Backlog`

**Pull Requests**
- [x] Add all new PR within this repo to https://github.com/orgs/trezor/projects/62
- [x] Remove the previous automation to old project Pull requests: https://github.com/trezor/trezor-suite/projects/8
- [ ]  Automate adding label `mobile-app' by folders touched in PR: https://github.com/marketplace/actions/labeler
- [ ] Move PR from Draft to To be reviewed Column on github.event.action == 'ready_for_review' (when the PR status is changed from draft to ready for review...)

**Comment by matejkriz** [comment]
Adding new PRs to new project already done here https://github.com/trezor/trezor-suite/pull/5459

**Comment by matejkriz** [comment]
Would be really nice to add **automation for moving PR from _Draft_ to _To be reviewed_** Column on `github.event.action == 'ready_for_review'` (when the PR status is changed from draft to ready for review...)

**Comment by matejkriz** [comment]
another nice-to-have idea is to move the PR to _To be reviewed_ column when `READY FOR REVIEW` label is added and also add that label when issue is moved to that column and remove the label when PR is moved from that column 🙂

**Comment by hynek-jina** [comment]
Outdated...
