### ISSUE TITLE
Inconsistent fiat rates

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5437]
**Describe the bug**
Fetched fiat rates are consistent

**Steps to reproduce:**
1. Search for older transaction
2. Record the fiat values
3. Check that tomorrow or on web Suite

**Info:**
 - Suite version: desktop 22.5.2 (a4ec55219fe123c0bb073d4b8338041eb176add4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: model 1 1.11.1 Bitcoin only (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Expected result:**
I would like to see always the same fiat amount for the same transaction

**Actual result:**
Fiat value is not consistent

**Screenshots:**
![Snímek obrazovky 2022-05-18 v 15 47 02](https://user-images.githubusercontent.com/26002916/169071525-c87b29ae-b17b-4bbb-bac1-bc8644571b9d.png)
![Snímek obrazovky 2022-05-18 v 15 44 58](https://user-images.githubusercontent.com/26002916/169071645-f3fcbb8a-8853-420b-9de6-4d953d51335b.png)

These screenshots were taken within minutes of each other

**Comment by bosomt** [comment]
I was not able to reproduce issue :(
I watched for change in fiat rates for 3 days and they were always same.
Both app and web version. Fiat was default USD $.

**Comment by hynek-jina** [comment]
@bosomt 
Could you have a look on older ones? For example from 2019 on `all` seed? Maybe web vs desktop...🤷‍♂️

**Comment by bosomt** [comment]
I just send transaction and fiat values are inconsistent immediately i sent tx.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/31506317/184504741-bb8091d8-40a8-4c7c-b0e1-e9ee2b92b875.png">

**Info:**
 - Suite version: desktop 22.8.2 (58f4c5bf0804e02c05c0b85e020b6e452b419164)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.2 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
So far no luck. 
There were no other reports and so far we were not able to replicate this issue.
From time to time i checked and compared it but with no luck.
If issue reappears we can reopen or create new issue.
