### ISSUE TITLE
Update package READMEs

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#5440]
Update _README_ in each package to make it more useful for developers. Basic package-specific info should go into a _README_, higher level documentation should be gathered in _docs_ package.

### Some considerations:

General:
- [x] Should the READMEs also contain info relevant to dev team only, not to 3rd party devs? E.g. links to _Notion_, directions requiring access to _Keboola_ etc.
- Yes

`analytics`:
> Keep in mind that global `fetch` and `URLSearchParams` methods must be available for this code to work.
- [x] What is an example of an environment when these are not available?
- Node < 18, React Native

`suite-analytics`:
> Package version should be bumped if changes are made to `suite-analytics`.
- [x] Why do we version this package? Can it be used independently from Suite?
- The version is included in logs
> Get access to Keboola
- [x] How can one get access?
- Via access form linked from Notion

`integration-tests`:
> As of now M1 Macs aren't supported.
- [x] Supported now, waiting for https://github.com/trezor/trezor-suite/issues/3616

`request-manager`:
> Library to allow efficient and stable proxy for requests using TOR or other similar systems.
- [x] Should more description be provided?
- Done

`transport`
> yarn workspace @trezor/transport update:submodules to update trezor-common submodule
- [x] This part needs to be updated, this command is no longer available. Not sure if anything else alo changed.
- Done

`utils`
> [![NPM](https://img.shields.io/npm/v/@trezor/utils.svg)](https://www.npmjs.org/package/@trezor/utils)
- [x] Why is this an NPM package? Should we keep bumping the version and publishing it to NPM registry?
- `connect` dependency - `connect` can be used as standalone

`utxo-lib`
> [![NPM](https://img.shields.io/npm/v/@trezor/utxo-lib.svg)](https://www.npmjs.org/package/@trezor/utxo-lib)
- [x] Why is this an NPM package? Do we use it outside of the monorepo or is it just for backwards compatibility?
- `connect` dependency - `connect` can be used as standalone

`connect`
> [Development](https://wiki.trezor.io/Developers_guide:Trezor_Connect_API)
- [x] Is this up-to-date? Should we update the wiki or point somewhere else?
- Waiting for https://github.com/trezor/trezor-suite/issues/5498

`connect-common`
> `releases.json` in `firmware`
- [x] Where does the data come from and where is each field used in Suite?
- Done

> `releases.json` in `bridge`
- [x] Where does the data come from and how is it used in Suite?
- Used for download prompt on web Suite

> `storage`
- [x] What keys are stored?
- information on app permissions given by the user.

`connect-explorer`
> `yarn dev` - runs dev server on port 8088
- [x] Why does this not work with WebUSB (trezord si required)?
- WebUSB is not available for security reasons (disabled by Chrome) because it is a cross-domain request

`connect-iframe`
> Build `@trezor/connect` iframe hosted on `connect.trezor.io/<connect version>/iframe.html`
- [x] When to use self-hosted version, when online version?
- Self-hosted for Suite, otherwise trezor.io

> Build files are copied into `suite-*/build/static` directory.
- [x] How? I cannot see this in webpack config.
- During app build as configured in `suite-build`

> docs-todo: expand on why iframe exists
- [x] What does the iframe do? What parts of `connect` can be accessed directly, what parts need the iframe?
- Being hosted on our domain, it secures communication with Trezor

`connect-plugin-stellar`
- [x] Missing README, what does this do?
- Will be done in #5450

`connect-popup`
> Build `@trezor/connect` popup hosted on `connect.trezor.io/<version>/popup.html`
- [x] What does the popup do?
- Serves as UI for `connect` commands

> `yarn workspace @trezor/connect-popup dev`
- [x] Returns 404.
- Navigate to `/popup.html`.

`connect-web`
> `yarn workspace @trezor/connect-web dev`
- [x] Returns 404.
- There is no default UI.

`suite-storage`
- [x] Where is the logic for `native`? Methods are mostly empty functions/promises.
- Mobile storage is not implemented yet, both desktop and web are in the `web` folder

`suite-web`
> "dev:https": "node ./scripts/httpsServer.js"
- [x] Is this still used? The script ends with an error (requires `next`)
- No, deleted

**Comment by komret** [comment]
@karliatto Do you think you could add more info to https://github.com/trezor/trezor-suite/blob/develop/packages/request-manager/README.md?

E.g. where the package is intended to be used, what is the current state and plans, what problems it solves... To make it a bit more concrete. I am not familiar with this part.

**Comment by komret** [comment]
@mroz22 Could you please update https://github.com/trezor/trezor-suite/tree/develop/packages/transport#from-protobuf-to-typescript-and-flow? It seems outdated with the recent change to submodules.

**Comment by mroz22** [comment]
> Why is this an NPM package? Should we keep bumping the version and publishing it to NPM registry?

It is used by connect. Although we already have connect in monorepo, we probably still need  to publish its dependencies in case someone wants to install connect from npm?
