### ISSUE TITLE
Update messaging system

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#5445]
We would like to:
1. Remove the phishing warning. We will introduce it again in future if needed.
2. Add a warning about revision `e1c605ca90c6107befe11692b4675b7537f3a658` as in https://github.com/trezor/trezor-suite/pull/5291.

**Comment by tomasklim** [comment]
@tsusanka `e1c605ca90c6107befe11692b4675b7537f3a658` this revision is model `1` 

And the previous one (`1e62209d024b7e84a7368be8175735372b8080c9 `) we added was also model `1`.

Do we want to add it?

**Comment by tsusanka** [comment]
`e1c605ca90c6107befe11692b4675b7537f3a658` does not seem to be in GitHub, how can you tell that it is model `1`? Oh or that comes from data analytics?

**Comment by tsusanka** [comment]
Anyway, let's add it. It is probably just some people playing around but it does not hurt. cc @andrewkozlik but he agreed 
with this already on Slack.

**Comment by tomasklim** [comment]
> `e1c605ca90c6107befe11692b4675b7537f3a658` does not seem to be in GitHub, how can you tell that it is model `1`? Oh or that comes from data analytics?

Yes, it is from analytics. To be sure, I will add this revision for both models.

**Comment by STew790** [comment]
**QA OK**

Tested this with @tomasklim yesterday. Moving to approved.
