### ISSUE TITLE
Rename "Signature" to "Raw transaction"

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-suite#5452]
In the Send dialog when I click on details and scroll down I can see the raw transaction, but the heading states "Signature". This is somewhat incorrect. Each transaction contains one or more signatures which are contained in the raw transaction data. I propose renaming it to "Raw transaction".

![image](https://user-images.githubusercontent.com/42678794/169482432-4f38dd41-40e5-44d7-8374-59e43f250c90.png)

**Comment by jerechinsky** [comment]
This "Signature" string is also used in the Sign&Verify modal. So I'm guessing we should split this into two messages in `messages.ts.` One for the send modal and one for sign&verify. 

@hynek-jina, could you please find a dev to do this quick task? 

<img width="779" alt="Screenshot 2022-06-15 at 14 18 51" src="https://user-images.githubusercontent.com/75733878/173825561-6fccfef7-18e3-400c-bff3-6a4a0d740118.png">

**Comment by komret** [comment]
QA: The label in transaction detail should read "Raw transaction", not "Signature".

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.7.0 (07547a8b401fa1e8131820c285eac2d9a6001d59)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.8.3 regular (revision df0963ec48f01f3d07ffca556e21ff0070cab099)
 - Transport: bridge 2.0.31
