### ISSUE TITLE
Prepare E2E test solution for mobile app

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#5464]
Only option here is [Detox](https://github.com/wix/Detox)

- [ ] should be in own package `@suite-native/e2e-tests` (if possible, maybe it will be problem because of Detox)
- [ ] should run on CI

**Comment by mroz22** [comment]
> should be in own package @suite-native/e2e-tests (if possible, maybe it will be problem because of Detox)

this is my long term plan to dissolve tests from `packages/integration-tests` into respective packages. instead of `@trezor/integration-tests` I want to create something like `@trezor/trezor-user-env-link` which will be a reusable client for trezor-user-env with some additional features.

**Comment by Nodonisko** [comment]
@mroz22 Great idea, it makes sense to have reusable tooling for tests.

**Comment by mnuky** [comment]
Needs to be coordinate with QA
