### ISSUE TITLE
Remote Secure Messaging: @message-system/save-valid-messages action overflow

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#5469]
`@message-system/save-valid-messages` action is called too many times, it's triggered by other unrelated actions (in some middleware?)

**Comment by tomasklim** [comment]
It is triggered only by related actions. 

However, I agree that it is triggered too many times because of ` DEVICE.CHANGED` event. It can probably be removed and it will work the same.

**Comment by bosomt** [comment]
can we move it to approved or is there any action needed by QA dept ?

**Comment by hynek-jina** [comment]
No need for validation from QA
