### ISSUE TITLE
firmware update blank modal

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#5470]
**Describe the bug**
Disconnecting device BEFORE request to switch to bootlader mode results with empty view

**How to reproduce**

1. Go to 'settings/device'
2. Click on 'firmware update' (even if your FW is up to date)
3. Go to next step (checkpoint)
4. Disconnect device  instead of clicking on "continue"

**Expected behavior**
modal should be closed?

**Screenshots**
![Screenshot from 2022-05-24 12-16-23](https://user-images.githubusercontent.com/3435913/170008975-d222fb51-06ea-406b-a539-7f3a25893fc4.png)

**Comment by bosomt** [comment]
**QA NOK**

I was able to reproduce issue.

**Info:**
 - Suite version: desktop 22.6.0 (d72ff4c5b9f3cbe2ccb4be47170f88c08e9271d1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: 
 - Transport: bridge 2.0.31
 
<img width="771" alt="Screenshot 2022-05-25 at 17 33 29" src="https://user-images.githubusercontent.com/31506317/170300958-c94e6881-8112-4881-82f6-01a6175d44e4.png">

**Comment by szymonlesisz** [comment]
additional issue :)
why there is no "blurred background" in my screen ~~(darkmode case? idk...)~~
edit: looks like Firefox is missing this regardless of theme, created new issue

**Comment by STew790** [comment]
**QA NOK**

This is still happening in the latest Suite. Although, the difference now is that there is a "X" button for closing the modal and also when I reconnect the device, I can see the modal correctly again. This is definitely an edge case.

![image](https://user-images.githubusercontent.com/48477147/181577131-9ed99afc-ebcd-42ea-8e36-823cbd524a28.png)


**Info:**
 - Suite version: desktop 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.27

**Comment by bosomt** [comment]
**QA NOK**

issue is still present

**Info:**
 - Suite version: desktop 22.11.1 (73ccf723353e0575a64f58b2f5775d20f072311f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: 
 - Transport: bridge 2.0.32

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.4.0 (905e81f59a3aeaad81329ef67aecfe0d2a199b90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
