### ISSUE TITLE
firmware update "ButtonRequest_FirmwareUpdate" is not shown

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#5473]
**Describe the bug**
After switching to bootloader mode but before uploading FW into device, there is a button request which is not reflected in UI.
Device is waiting on update confirmation but there is no "follow instructions on device" modal

**Screenshots**
![Screenshot from 2022-05-24 13-19-36](https://user-images.githubusercontent.com/3435913/170023017-4ba7b8c0-1579-47c6-a5de-1343f41199a7.png)

**Comment by bosomt** [comment]
@szymonlesisz i was not able to replicate it on production version of Suite.
There is banner above model that says `Confirm on Trezor` it's used multiple times in Suite and i think it's confusing.

**Info:**
 - Suite version: desktop 22.5.2 (a4ec55219fe123c0bb073d4b8338041eb176add4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision null)
 - Transport: bridge 2.0.31

<img width="637" alt="image" src="https://user-images.githubusercontent.com/31506317/170040358-753947d9-5bee-46eb-911e-2bbf202e234b.png">

**Comment by szymonlesisz** [comment]
ah! i didnt noticed  element above :) i guess im totally blind :)

closing
