### ISSUE TITLE
Connect: remove multiple messages.json instances remnants

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#5496]
For historical reasons, connect supported multiple messages.json config files that were loaded dynamically based of firmware of currently connected device.

This was just some workaround we finally managed to remove and now connect uses only 1 unified set of messages. Yet some remnants of this still exist in the codebase and I believe we should eliminate them. 

https://github.com/trezor/trezor-suite/blob/803f89220bf408976cc42a1c5487bc70443c1d24/packages/connect/src/data/config.ts#L69

https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/device/DeviceList.ts#L144

https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/data/DataManager.ts#L81

https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/data/DataManager.ts#L64

**Comment by bosomt** [comment]
anything that can/needs to be tested on QA side or regular regression tests are enough ?

**Comment by marekrjpolak** [comment]
> anything that can/needs to be tested on QA side or regular regression tests are enough ?

Regular tests are enough imo.

**Comment by hynek-jina** [comment]
@marekrjpolak  So I'm moving that to approved..
