### ISSUE TITLE
Connect: missing data/icons folder

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#5497]
Looks like we forgot to transfer data/icons folder in connect. 
Not so big deal but should be solved  before we promote connect 9 to "production ready grade"

https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/data/config.ts#L23-L44

**Comment by szymonlesisz** [comment]
or we can completely drop this from config.
for the instance this record is wrong
```
label: 'Trezor Connect Chrome Extension',
            icon: './data/icons/metamask.svg',
```

secondly im not even sure if those extensions id's are valid (may not)

**Comment by hynek-jina** [comment]
No requirements from QA
