### ISSUE TITLE
Move connect documentation from wiki to docs

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#5498]
The existing documentation on `connect` available on [wiki](https://wiki.trezor.io/Developers_guide:Trezor_Connect_API) is outdated. Update it and integrate it to existing documentation in `docs` in this repo.

**Comment by hynek-jina** [comment]
Could you please include these docs labeled `Suite monorepo`?
https://www.notion.so/satoshilabs/db4ad1fae8da4b4da907d33d112bdda6?v=3583289960fa408088aba33f8d5562cc

**Comment by komret** [comment]
- [x] [integrate Trezor into my web application via Connect](https://wiki.corp.sldev.cz/Trezor_Connect_API) overview available in [Suite docs](https://docs.trezor.io/trezor-suite/packages/connect/index.html) and introduction in [package README](https://github.com/trezor/trezor-suite/blob/develop/packages/connect/README.md)
- [ ] [integrate Trezor into my Android application](https://wiki.corp.sldev.cz/Developers_guide:Android) - obsolete, the `trezor-android` package is no longer maintained
- [x] [run Trezor backend as a local instance](https://wiki.corp.sldev.cz/User_manual:Running_a_local_instance_of_Trezor_Wallet_backend_(Blockbook)) - ported to [Knowledge Base](https://trezor.io/support/a/custom-backend-in-trezor-suite)
- [x] [run Trezor Wallet as a local instance](https://wiki.corp.sldev.cz/User_manual:Running_a_local_instance_of_Trezor_Wallet) - obsolete, Trezor Wallet is deprecated
- [x] [use Trezor from command line using trezorctl command](https://wiki.corp.sldev.cz/Using_trezorctl_commands_with_Trezor) - ported to [Knowledge Base](https://trezor.io/support/a/using-trezorctl-commands)
- [x] [verify Trezor firmware](https://wiki.corp.sldev.cz/Developers_guide:Deterministic_firmware_build) - available in [firmware docs](https://docs.trezor.io/trezor-firmware/common/reproducible-build.html)
- [x] [build custom Trezor firmware](https://wiki.corp.sldev.cz/Developers_guide:Custom_firmware) - updated version available in [firmware docs](https://docs.trezor.io/trezor-firmware/core/build/index.html)
- [x] [add new coin/token/network to the official Trezor firmware](https://wiki.corp.sldev.cz/Developers_guide:Contributing) - available in [firmware docs](https://docs.trezor.io/trezor-firmware/misc/contributing.html)
- [ ] [learn about Trezor libraries](https://wiki.corp.sldev.cz/Developers_guide:Trezor_libraries) - available in [firmware docs](https://docs.trezor.io/trezor-firmware/developers/libraries.html), obsolete
- [x] [learn about the Trezor cryptography library which provides all necessary cryptography primitives](https://wiki.corp.sldev.cz/Trezor_Cryptography) - no content except link to [trezor-crypto repo](https://github.com/trezor/trezor-crypto/blob/master/README.md), can be omitted
- [x] [learn about the cryptography standards Trezor uses](https://wiki.corp.sldev.cz/Developers_guide:Cryptography) - this was not ported anywhere, but there is not much original content, mostly excerpts from BIPs
- [ ] [understand the Trezor low level message workflows](https://wiki.corp.sldev.cz/Developers_guide:Message_Workflows) - available in [firmware docs](https://docs.trezor.io/trezor-firmware/common/message-workflows.html), may be obsolete
- [x] [understand the Trezor hardware](https://wiki.corp.sldev.cz/Security:Hardware) - ported to [Knowledge Base](https://trezor.io/learn/a/trezor-hardware-built-in-security)
- [x] [Running Trezor Connect on localhost](https://wiki.corp.sldev.cz/Developers_guide:Running_Trezor_Connect_on_localhost) - updated in the PR
- [x] [Trezor Connect API - Login with Trezor](https://wiki.corp.sldev.cz/Developers_guide:Trezor_Connect_API_-_Login_with_Trezor) - updated in the PR
- [x] [Trezor Connect API - Methods](https://wiki.corp.sldev.cz/Developers_guide:Trezor_Connect_API_Methods) - available in [connect docs](https://docs.trezor.io/trezor-suite/packages/connect/methods.html)

**Comment by komret** [comment]
@Hannsek FYI, I went through the articles, the ones that are not checked do not have an up-to-date successor in docs or Knowledge base, AFAIK. Firmware team might want to update them.

**Comment by bosomt** [comment]
**QA OK**
