### ISSUE TITLE
Camera QR read does not work

### ISSUE THREAD

**Issue by petrkr** [trezor/trezor-suite#5503]
When I scan QR from coinomi, modal disappear, but address is NOT copied to "send"

maybe because it has bitcoin: or litecoin: prefix in QR?

**Comment by bosomt** [comment]
@petrkr you are right, it's due to that prefix.
Duplicity with https://github.com/trezor/trezor-suite/issues/5241

**Comment by petrkr** [comment]
Not planed? So that means we have to retype address from coinomi by hand? Or use different QR reader and strip prefix manually?

That will really help Bitcoin adoption for regular payments...

Actually yesterday I had to retype it in restaurant, because they use coinomi and we have no other way of share address than QR 

(like signal, messager or other).

**Comment by hynek-jina** [comment]
@petrkr 
I'm sorry for the confusion.. Not planned this issue, since it is covered by another issue mentioned above...
