### ISSUE TITLE
Create slide down animation for SlideDownModal component

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#5504]
Modal component is created already but it should have slide down functionality which will close the modal.

Related to https://github.com/trezor/trezor-suite/issues/5421

**Comment by juriczech** [comment]
To discuss: should there also be slide left / back functionality to return to previous section when I'm in a nested section of modal? @Nodonisko @bouchja1

**Comment by Nodonisko** [comment]
That would be nice, but this definitely deserve it's own task.

**Comment by Nodonisko** [comment]
It looks that animation for Modal opening/closing should be already in Figma. If you will have troubles to find it, ask Ondra.
