### ISSUE TITLE
release @trezor/connect v9

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#5505]
Hello, 
I have gathered here some notes on what needs to be done in order to release connect 9. @karliatto has volunteered to oversee this while I am not here. I am sure @szymonlesisz will be ready to answer questions and maybe also he will add or correct something in my list. 

Core tasks:
- [x] the same* content that is here https://suite.corp.sldev.cz/connect/develop/#/ should go to connect.trezor.io/9. It should be ready as @vdovhanych has already added [this job into CI](https://github.com/trezor/trezor-suite/blob/develop/ci/releases.yml#L120)
- [x] all @trezor/* dependencies that are present in `@trezor/connect` package.json file and `@trezor/connect-web` should be released to npm. Please be aware of my little mishap with [accidental npm release here](https://github.com/trezor/trezor-suite/pull/5495#issuecomment-1138542249)
- [x] release @trezor/connect to npm, **dont forget** to add `--tag beta`
- [x] release @trezor/connect-web to npm, **dont forget** to add `--tag beta`
- [x] try to use the newly released packages! A suitable place to do it is for example `@trezor/connect-examples` package. Just try to make those examples work. 

Additional tasks: 
- [x] don't forget about docs. would be great to keep readmes (also in old connect repo) updated about whats going on (there is new connect 9 beta version, connect 8 version is in maintanance mode). 
- [x] optional but important: come up with a solution how not make sure we do not forget to release some of @trezor/connect dependencies. We were discussing it [here](https://github.com/trezor/trezor-suite/pull/5495)
- [x] optional: consider adding text "Warning: connect 9 is still in beta, don't use this in production" somewhere into connect-popup so that even users can see it. 
  - We decided not to do it since it is going to be deployed as beta so there is no way to mistake it
- [x] optional: consider adding some console.warn("Warning: connect 9 is still in beta, don't use this in production") somewhere where it would print into console, typically indexes of `@trezor/connect` and `@trezor/connect-web packages`
  - We decided not to do it since it is going to be deployed as beta so there is no way to mistake it
- [ ] finish [connect-plugin-stellar PR](https://github.com/trezor/trezor-suite/pull/5450) release it and ask stellar developer to test it. He is a very nice a cooperative guy and said he is willing to do the testing here https://github.com/trezor/connect/pull/1091
- [x] do the same with `@trezor/connect-plugin-ethereum` It might need some cleanup before releasing. 
- [x] check out missing icons https://github.com/trezor/trezor-suite/issues/5497
- [ ] replace `"@trezor/connect": "9.0.0-beta.1",` by `"@trezor/connect": "*",` in suite packages when released to npm

cc @sime @tsusanka @marekrjpolak @matejkriz 
___

* actually, one thing needs to be fixed. build of connect-explorer will try to communicate with connect on sldev domain due to this [env variable set in build](https://github.com/trezor/trezor-suite/blob/42bf2996624b2b468ab297826434a65d2c100bbb/ci/build.yml#L297) so it either needs to be changed here, or maybe even somewhere [here where this variable is consumed](https://github.com/trezor/trezor-suite/blob/develop/packages/connect-explorer/src/js/actions/trezorConnectActions.ts#L43)

**Comment by sime** [comment]
@karliatto Ping me when need some sanity check testing.

I'm excited to have connect explorer in public!

**Comment by matejkriz** [comment]
https://connect.trezor.io/9
https://connect.trezor.io/9.0.0-beta.1

https://www.npmjs.com/package/@trezor/connect/v/9.0.0-beta.1
https://www.npmjs.com/package/@trezor/connect-web/v/9.0.0-beta.1
  
are out 🚀 🎉 

cc @sime

**Comment by matejkriz** [comment]
I see "No connected devices" message even though I just exported the public key from the connected device...
<img width="857" alt="image" src="https://user-images.githubusercontent.com/3729633/173542365-5e557cbc-ea56-455f-b322-ec6fdb2f4b77.png">

**Comment by mroz22** [comment]
I believe this can be considered done. Not sure if there is anything for QA

**Comment by vdovhanych** [comment]
Should we close this issue, and if there are other concerns, we will create a new one?
