### ISSUE TITLE
Intercept the requests from the main process with package request-manager to improve Tor

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#5527]
In order to improve the knowledge of the requests that are happening in the electronjs main nodejs process we want to intercept all the network requests that are happening in that process.
- [x]  Create interceptor that gets all the requests from nodejs in `request-manager` package
- [x] Create a module in electron desktop package that creates an instance of the interceptor provided by request-manager and log those requests.

**Comment by STew790** [comment]
Pre-requisities for CoinJoin, no QA needed.
