### ISSUE TITLE
Dependencies(suite): react-spring - fix deprecated method or remove the library

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5531]
**Describe the bug**
Update `react-spring` and fix warning in console which is triggered by a tooltip.

![Screenshot 2022-06-01 at 9 52 14](https://user-images.githubusercontent.com/33235762/171355122-7161d9cc-64cb-4e78-97c5-b909ce7f3871.png)

**Comment by tomasklim** [comment]
We can think about removing this lib in favour of `framer-motion`. We have 2 animation libs in our repo.

If we remove `react-spring`, we save 55kB.

cc @dahaca

**Comment by tomasklim** [comment]
Please update `framer-motion` library to `v6`. E2E test `autodetect` starts failing when updating to `v6`.

![Screenshot 2022-06-07 at 13 00 40](https://user-images.githubusercontent.com/33235762/172372934-5f3772a7-3f4d-41b7-9685-b21f9c66fefe.png)

It is caused by this
```
    cy.stub(win, 'matchMedia')
        .withArgs('(prefers-color-scheme: dark)')
        .returns({
            matches: true,
            addEventListener: () => {},
            removeEventListener: () => {},
        });
```

adding `addListener: () => {},` does not help 😞

**Comment by bosomt** [comment]
anything that can/needs to be tested on QA side or i can move it to approved section ?
