### ISSUE TITLE
Dependencies(suite): react-select

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5532]
**Info**
Update `react-select` lib. We are currently running `3.1.1` version but there is `5.3.2`.

It looks like it does not break anything. However, that are some changes worth looking at.

[CHANGELOG](https://github.com/JedWatson/react-select/blob/master/packages/react-select/CHANGELOG.md)

The most dangerous select we have is probably the one in recovery, which has broken styles a little bit. Please check it with/without a mouse on macOS.
![Screenshot 2022-06-01 at 10 31 57](https://user-images.githubusercontent.com/33235762/171362499-be4df285-7abe-453d-b71c-16d19a4586a0.png)

**Comment by komret** [comment]
QA: The library for dropdown inputs was upgraded, but they should look and behave the same as previously. There are only small UI improvements on the mnemonic word input pictured above (padding, keyboard navigation). Please check that all dropdown inputs behave as expected.
