### ISSUE TITLE
Recover wallet abort button placement

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5533]
**Info**
Device: model 1

I see here a potential problem during recovery. Users can accidentally click on `Abort` button which is directly under the select menu.

https://user-images.githubusercontent.com/33235762/171368670-fce1dbd0-24e1-45e5-b69c-775358309594.mov

**Comment by bosomt** [comment]
Is there plan to move this button ?
It has been reported 6 months ago and i still abort my recovery from time to time ;(((

**Comment by sime** [comment]
Thanks for mentioning it @bosomt.

Expecting that the resolution of the [recovery dropdown](https://github.com/trezor/trezor-suite/issues/6601) issue will have a side effect of lowering the anonyingness of this one.

**Comment by bosomt** [comment]
**QA OK**
