### ISSUE TITLE
Dependencies(suite): semver - remove library

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5535]
**Info**
`versionUtils` got moved from `rollout` to separate `@trezor/utils` package so we can now use them in Suite. 
If we extend them, we can get rid of `semver` library

**Comment by peter-sanderson** [comment]
However it is not easy and maybe we even dont want to remove it after all. We use it heavily in suite-common/message-system/src/messageSystemUtils.ts
