### ISSUE TITLE
Dependencies(suite-desktop): update deprecated electron

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5537]
**Info**
We are using `electron v15`, which got deprecated. Update to `electron v18`. 

**Issues**

- it needs to be updated also in `nix.shell` 
- we need to update `node` to version `16`

**Comment by tomasklim** [comment]
QA: 
Desktop builds and autoupdate have to be exhaustingly tested

**Comment by bosomt** [comment]
**QA OK**

tested multiple time during 22.7.x release cycle.
