### ISSUE TITLE
Cancel receive modal

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5540]
User is not allowed to cancel Receive address modal before he confirms that it corresponds with an address on Trezor.
It's redundant. We can let him cancel this action now.

<img width="1392" alt="Snímek obrazovky 2022-06-02 v 14 03 05" src="https://user-images.githubusercontent.com/26002916/171636424-b13905d1-86cd-4a7b-be3b-952874ccfdbc.png">

**Comment by matejkriz** [comment]
it doesn't make sense to me as a standalone change, receive modal should be thought of as a whole

**Comment by komret** [comment]
[Done](https://github.com/trezor/trezor-suite/pull/8613#issuecomment-1577183560).

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.2.0 (a30bef7c9b4c2a3baa8b4c467038663d9af1b1d1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2T1 2.6.4 bitcoin-only (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
