### ISSUE TITLE
Show Bitcoin value in Satoshis (Trade section)

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5541]
Follow up issue of: https://github.com/trezor/trezor-suite/issues/3004

<img width="1483" alt="Snímek obrazovky 2022-06-02 v 14 18 09" src="https://user-images.githubusercontent.com/26002916/171638140-00576c78-9ec6-4742-b4aa-3243efffc495.png">

Align the display units for Bitcoin on all Invity pages.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.9.1 (32cfc5c61076fd9b38389efb1ec2aee2cc0b94f3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.9.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31
