### ISSUE TITLE
Imitate mirror behavior for QR reader

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5542]
Rotate QR reader so when user move his QR in right direction Suite displays the opposite movement. User gets the feel like with mirror and reading of QR will be more intuitive.

**Comment by Hannsek** [comment]
Can you elaborate more on what do you thing by that?

**Comment by hynek-jina** [comment]
When you scan QR address in send form the camera doesn't work like mirror.. but it's expected and not important..
