### ISSUE TITLE
Uninitialized device in incorrect state after going to settings and back

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#5543]
**Describe the bug**
When you don't have an initialized device and go immediately to device settings and then back to initial screen, it appears as "Device in incorrect state".

**Steps to reproduce:**

1. Connect an uninitialized device
2. Go to "Device settings" immediately.
3. Close the settings 
4. You get a "Device detected in incorrect state" message

**Info:**
 - Suite version: desktop 22.6.1 (8d37e21edabe10ea6b6991f5e3a338e3464925e1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: bridge 2.0.31

**Original comment:**
I wasn't able to replicate the bug in any of described scenarios.
For the scenario with old firmware I have tested 2.3.2 and 2.1.8..

Only where it appear is when you don't have initialized device and go directly to device settings and back. But when you reconnect the device, it's again back in normal state. This seems to be very edge case to me..

https://user-images.githubusercontent.com/26002916/170981973-10ee4442-cf24-4cc1-bfae-dbe49ce97dcd.mov

QA could you please confirm that?

_Originally posted by @hynek-jina in https://github.com/trezor/trezor-suite/issues/3971#issuecomment-1141034277_

**Comment by bosomt** [comment]
Current state:

<img width="461" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/85d32894-0893-414f-b137-a6dba8069a33">


**Info:**
 - Suite version: desktop 23.7.0 (8ac7640945b9976da035139932fd2932a809c7be)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.7.0 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.11.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: BridgeTransport 2.0.33

**Comment by mroz22** [comment]
is it still an issue?

**Comment by bosomt** [comment]
Looks good to me, @STew790 , what do you think ? closing ?

https://github.com/user-attachments/assets/75e5c1dc-7393-4a96-90c7-2737dd52a61a


**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Transport: BridgeTransport 2.0.33
