### ISSUE TITLE
Display virtual bytes for segwit accounts

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5544]
For segwit accounts calculate vsize and display rate in sat/vB

Related to: https://github.com/trezor/trezor-suite/issues/3355

**Comment by martinboehm** [comment]
@hynek-jina Hi, Blockbook now computes and returns `vSize` of the transaction where applicable (not all coins support vSize). It is returned by the tx detail request, see for example https://tbtc2.trezor.io/api/v2/tx/46e25a5cadbb6644b2e1fcc303234b00c554b493f9fba1da994e7682944cd4de and via websocket.

At this moment, the feature is released only to testnet but will be released soon to all applicable coins (BTC, TEST, LTC, BTG, NMC, VTC, DGB).

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.0 (da1945300f7e7497d23eef27030f0c31a6efb43b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision eb182b923f39111d9307a25a86a49d395c6611b0)
 - Transport: bridge 2.0.32
