### ISSUE TITLE
Extend thousands separator to crypto currencies

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5545]
Thousand separators are not set for crypto currencies - only for fiat.
Extend it for cryptocurrencies as well.

Visible with Sats units on Bitcoin accounts (or on Doge coin for example)
Related to: https://github.com/trezor/trezor-suite/issues/3004

**Comment by hynek-jina** [comment]
Format is not by locals but we are using fixed `en-us` format (like 1,234.12)

**Comment by hynek-jina** [comment]
We are using number format based on language settings. So there will be different format for example when is Suite in Czech language (ie `12 345,67`). Trezor device is always english with en-us number formatting (ie `12,345.67`)

In this case, we preferred user-friendliness in the Suite over consistency with Trezor device.

**Comment by matejkriz** [comment]
@hynek-jina 
One more place to consider (maybe as followup issue?) are input fields. They always accept only dot `.` as decimal separator and nothing else, regardless of the language set. We could think at least about better error message for some languages
<img width="171" alt="image" src="https://user-images.githubusercontent.com/3729633/182646110-7444aee2-6a11-4646-a8f4-6e40efc676bf.png">

worst case is in Español:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/3729633/182646392-8bbec9b6-0c2e-4637-a47c-c89d53c14e3c.png">

**Comment by hynek-jina** [comment]
@matejkriz good point.. I just would like to prepare a specification before the issue..

**Comment by hynek-jina** [comment]
@matejkriz good idea. Here is the issue: https://github.com/trezor/trezor-suite/issues/5928

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.9.0 (f385f10a1fcd82339636d9c40f669c365a9e0c90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31
