### ISSUE TITLE
Copy inaccuracy in PIN setting

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5556]
**Describe the bug**
When setting PIN for T1 device user is asked to:

> Confirm on Trezor

Confirmation takes place in the app

> Enter up to 9 digits on your Trezor's keypad

But user is not entering the PIN on the device but on the app screen

![Snímek obrazovky 2022-06-03 v 9 20 02](https://user-images.githubusercontent.com/26002916/172121732-b9c5df37-bd2b-4dcf-b34b-c9682585d2ae.png)

**Comment by b-irving** [comment]
Enter up to 9 digits using the blind matrix by clicking the tiles using your mouse. Match the tiles with the digits displayed on your Trezor device screen.

**Comment by hynek-jina** [comment]
@b-irving 
Thx.. And what about the `Confirm on Trezor`?

And isn't the proposed text quite long? 🤔

And btw. the length is extended to 50 digits...

**Comment by AdamSchinzel** [comment]
> Confirm on Trezor

What would you suggest to put there @hynek-jina?


> Enter up to 9 digits on your Trezor's keypad

This is already solved. There is `Enter up to 50 digits.`

**Comment by hrudolf** [comment]
> @b-irving Thx.. And what about the `Confirm on Trezor`?
> 
> And isn't the proposed text quite long? 🤔
> 
> And btw. the length is extended to 50 digits...

As mentioned by  @AdamSchinzel the instruction has already been solved, namely in: PR https://github.com/trezor/trezor-suite/pull/5547
The "Confirm on Trezor" prompt is also no longer shown in the screen in question.

**Comment by Hannsek** [comment]
So can we close this?

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/trezor/trezor-suite/assets/48477147/ab30039a-3639-4e17-9fed-adf9415c35bd)

**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33
