### ISSUE TITLE
Dependencies(suite): wait for node16 and update @formatjs/cli 

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5561]
**Info**

> error @formatjs/cli@5.0.2: The engine "node" is incompatible with this module. Expected version ">= 16.5.0". Got "14.18.1"

Can be done when finished #5537

**Comment by tomasklim** [comment]
Ready to be updated

**Comment by tomasklim** [comment]
Updated

**Comment by hynek-jina** [comment]
@tomasklim Do we need something from QA?

**Comment by bosomt** [comment]
Approved
