### ISSUE TITLE
[Message] Update firmware to sign Zcash transaction

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5569]
### First message
**Variant**: Warning (yellow)
**Dismissible**: True

**Conditions**

- Activated Zcash
- `AND` Suite app older then `22.6.2`

**Message**

- `en` _Please update your application to be able to sign Zcash transactions [Update Suite]_
- `es` _Por favor, actualiza tu aplicación para poder firmar transacciones de Zcash [Actualizar Suite]_
- `cs` _Aktualizujte prosím aplikaci, aby mohla podepisovat Zcash transakce [Aktualizovat Suite]_
- `ru` _Пожалуйста, обновите свое приложение, чтобы иметь возможность подписывать транзакции Zcash [Обновить Suite]
- `ja` _Zcashの取引に署名できるようにアプリケーションを更新してください [Suiteのアップデート]_

### Second message
**Variant**: Warning (yellow)
**Dismissible**: True

**Conditions**

- Activated Zcash
- `AND` Older firmware then actual one (`<1.11.1`, `<2.5.1`)
- `AND` Suite app version >=  `22.6.2`

**Message**
- `en` _Please update your firmware to be able to sign Zcash transactions [Update Firmware]_
- `es` _Para firmar transacciones de Zcash es necesario actualizar el firmware [Actualizar firmware]_
- `cs` _Aktualizujte prosím svůj firmware, abyste mohli podepisovat Zcash transakce [Aktualizovat Firmware]_
- `ru` _Для подписывания транзакций Zcach необходимо обновить прошивку [Обновить прошивку]
- `ja` _Zcashの取引に署名できるようにファームウェアをアップデートしてください。 [ファームウェアのアップデート]_

**Comment by jerechinsky** [comment]
I suggest
`ru` _Для подписывания транзакций Zcash необходимо обновить прошивку [Обновить прошивку]_

@fujicoin @FrankyFFV, do you guys have suggestions for the `ja` and `es` translations?

**Comment by FrankyFFV** [comment]
@alex-jerechinsky 
RU: Для подписывания транзакций Zcach необходимо обновить прошивку [Обновить прошивку]
ES: Para firmar transacciones de Zcash es necesario actualizar el firmware [Actualizar firmware]

**Comment by fujicoin** [comment]
@alex-jerechinsky 
Japanese (ja) translation is appropriate.

**Comment by matejkriz** [comment]
My suggestion for First message
`cs` Aktualizujte prosím aplikaci, abyste mohli podepisovat Zcash transakce [Aktualizovat Suite]
(Suite doesn't do the signing...)

**Comment by STew790** [comment]
**QA OK**

With older FW:
![image](https://user-images.githubusercontent.com/48477147/173327352-40cee779-5392-40bc-94d9-08b8ed566e4e.png)

With older app:
![image](https://user-images.githubusercontent.com/48477147/173329209-ed58ba86-e9a0-4914-8a7f-1ddfe2e26b33.png)
