### ISSUE TITLE
I don't see all transactions when connected to custom electrum server (umbrel)

### ISSUE THREAD

**Issue by gorrdy** [trezor/trezor-suite#5577]
**Describe the bug**
When I connect to any electrum server (umbrel, cryptoanarchy debian repository), I don't see the very recent transactions in Trezor Suite history. I don't experience this with Trezor backend.

I've found out that the .csv and .pdf export differs when using Trezor backend and my electrum server which I think may be cause by the same problem. The .csv is complete though but the order of transaction is not correct.

Using a Trezor backend the transaction order is from newest to oldest. When I use custom electrum server, the order seems pretty random which I think is the problem (not sure if the electrum server returns a wrong order of transactions or the Trezor suite does not sort it correctly).

**Info:**

-   Remembered Wallet: no
-   Suite Version: app, [v22.5.3](https://github.com/trezor/trezor-suite/releases/tag/v22.5.3)
-   OS: macOS, Monterey 12.4 (21F79)
-   Firmware Version: Trezor T, [version/commit](https://github.com/trezor/trezor-firmware/commit/85a26d2c9593bcdf858c2d718d79951ca927a0c3)

**How to reproduce**

1. Connect umbrel electrum server
2. Go to your Bitcoin account
3. Scroll down to transactions
4. See there are only a few, e.g. from 2021 or 2020 but not the very recent

**Expected behavior**
I would expect the same result when connecting electrum server as the Trezor backend.

**Screenshots**
Trezor backend (transaction dates)
<img width="81" alt="trezor_suite_trezor_backend" src="https://user-images.githubusercontent.com/80678558/172552094-ddfb9bee-092a-435d-89c1-6ead866586da.png">

Custom electrum backend (transaction dates)
<img width="69" alt="trezor_suite_electrum_server" src="https://user-images.githubusercontent.com/80678558/172552104-7adb3afa-be2a-4380-8ec0-fb3d5baf4817.png">

**Comment by Arond-Devv** [comment]
@gorrdy Talk to a Trezor Support on the [Live support page](https://trezor-community.com) so that your issue can be looked into.

**Comment by STew790** [comment]
Most probably related to this issue https://github.com/trezor/trezor-suite/issues/5512
