### ISSUE TITLE
New Bitcoin Gold logo

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#5581]
**Describe the bug**
Suite Bitcoin Gold logo is incorrect

**Info:**
-   Suite Version: 22.5.3.18520

**Expected Behaviour***
https://bitcoingold.org/press-kit/

**Screenshots**
![Screenshot 2022-06-08 at 11 00 00](https://user-images.githubusercontent.com/216917/172576982-d9ae445e-4a2e-4f75-85d1-a0459e54d753.png)

**Comment by dahaca** [comment]
@sime I believe it's too different from everything else :/  Our Icons are a bit stylized anyways.

**Comment by Hannsek** [comment]
Agree, I'd close this.
