### ISSUE TITLE
Data Analytics: Amount showed in Sats

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#5590]
We would like to track the use of this new feature from the very beginning.

Best would be to track the last known state (best should be`Suite ready`) + switch between BTC and Sats as a new event.

**Comment by STew790** [comment]
**QA OK**

The analytics correctly shows the unit and correctly shows the change of the unit as well. 
Only thing is that it doesn't show the unit when it is not selected at first. Nonetheless, this is connected to https://github.com/trezor/trezor-suite/issues/3004#issuecomment-1202365657

**Info:**
 - Suite version: desktop 22.8.0 (4692fffe7467553f430d248c630b74f6aad6ad58)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
