### ISSUE TITLE
Data Analytics: Labeling

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#5591]
We want to track, whether users have the labelling enabled or not. Best would be to track this on app start as the new attribute `Labeling` in event `Suite Ready`.

**Comment by hynek-jina** [comment]
**QA**:
Please doublecheck that the `Labeling` attribute will be sent to analytics...
See the description in PR: https://github.com/trezor/trezor-suite/pull/5611#issue-1270360503

**Comment by STew790** [comment]
**QA OK**

Turn ON labeling:
![image](https://user-images.githubusercontent.com/48477147/175254102-e8e1e2df-24a8-4485-baef-f8ac22452ac3.png)

Labeling provider:
![image](https://user-images.githubusercontent.com/48477147/175254208-658718ef-7a0e-43cc-b27e-746c91c0883c.png)

Labeling turned off:
![image](https://user-images.githubusercontent.com/48477147/175254340-81a520b4-8fd2-4cea-ae96-194b4c00ceb5.png)

**Comment by tomasklim** [comment]
> **QA OK**
> 
> Turn ON labeling: ![image](https://user-images.githubusercontent.com/48477147/175254102-e8e1e2df-24a8-4485-baef-f8ac22452ac3.png)
> 
> Labeling provider: ![image](https://user-images.githubusercontent.com/48477147/175254208-658718ef-7a0e-43cc-b27e-746c91c0883c.png)
> 
> Labeling turned off: ![image](https://user-images.githubusercontent.com/48477147/175254340-81a520b4-8fd2-4cea-ae96-194b4c00ceb5.png)

The last picture is from `suite-ready` right? Check it also when labeling and provider is set.

It should also send `settings/general/labeling` when turning labeling off.
and `settings/general/labeling-provider` empty when disconnecting provider.

**Comment by STew790** [comment]
Yes, exactly.

When labeling and provider is set in `suite-ready`:
![image](https://user-images.githubusercontent.com/48477147/175273304-433334b0-ef86-4f67-896c-559e606b7532.png)

This is when provider is disconnected:
![image](https://user-images.githubusercontent.com/48477147/175272483-014cd6a7-ece2-43b0-a48c-8de168d7723b.png)

And when turning labeling off:
![image](https://user-images.githubusercontent.com/48477147/175273486-9e5ecf8b-cf40-46c6-8820-1b966d32498a.png)
