### ISSUE TITLE
TrezorConnect.cancel() throws random errors

### ISSUE THREAD

**Issue by marcin-mazurek** [trezor/trezor-suite#5597]
**Describe the bug**
After calling `TrezorConnect.cancel()`, from time to time the SDK or the device refuses to perform subsequent actions (for example, getting device features or requesting xpub) and throws various errors.

We noticed that this behavior takes place when the operation is cancelled quickly after it’s requested (under ~5 seconds).

Most often, the error we were getting was `Device_CallInProgress`, however from time to time we could observe other types of errors such as `Error: assertType: Response of unexpected type: CardanoTxItemAck. Should be Features`

**Info:**

-   Remembered Wallet: yes & no - tried both
-   Suite Version: 22.5.2
-   Browser: NodeJS v14
-   OS: macOS 12.1
-   Bridge: 2.0.27
-   Firmware Version: 2.4.4 and 2.5.1

**How to reproduce**

1. Export public key
1. Cancel the operation in 5 seconds
1. Try to export public key again
1. See error

**Expected behavior**
`TrezorConnect.cancel()` cancels the operation and always allows to continue interacting with the device.

**Screenshots**
Some error examples:
![Screenshot 2022-06-01 at 17 41 26](https://user-images.githubusercontent.com/6684554/172998715-142dc20d-89aa-480e-b2f6-11659817eeb6.png)
![Screenshot 2022-06-01 at 22 25 59](https://user-images.githubusercontent.com/6684554/172998750-368bb1a2-7491-4d41-b9f4-77afb48acbfe.png) 

**Additional context**
Observed in Daedalus 4.11.0

Possibly the error is related to this commit: https://github.com/trezor/connect/commit/fc60c3c03d6e689f3de2d518cc51f62e649a20e2

**Comment by sime** [comment]
@marcin-mazurek Is this related to Daedalus wallet recommending Trezor Model T users to downgrade firmware?

**Comment by sime** [comment]
@marcin-mazurek Could you try bridge version 2.0.31. It's 'unrelased' as a standalone app, but bundled within Trezor Suite.

**Comment by szymonlesisz** [comment]
looks like known bug with `trezord` (bridge) 2.0.29 where previous (cancelled) response was still in the buffer (reason for unexpected response type)

to confirm that try to use [2.0.31](https://github.com/trezor/trezor-suite/tree/develop/packages/suite-data/files/bin/bridge/mac-x64) as @sime suggested
