### ISSUE TITLE
Fix transport-native (connect) freeze

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#5604]
How to reproduce:
1. Find some older version of app where connect was used in app, [for example here](https://github.com/trezor/trezor-suite/blob/7d19c1d71f1749b483de2919a1d9fc811dcce919/packages/suite-native/src/screens/Home.tsx)
2. Use that code while real Trezor device is connect and call `TrezorConnect.getDeviceState()` (also used in that previous version)
3. It should cause that app will freeze completely until device is disconnected

Possible problems:
I tracked issue down to `transport-native` package, it looks it's happening at file `packages/transport-native/android/src/main/java/io/trezor/transport/bridges/USBBridge.java` at line `285`, but I don't know for sure.

**Comment by Nodonisko** [comment]
How to reproduce:
1. Find some older version of app where connect was used in app, [for example here](https://github.com/trezor/trezor-suite/blob/7d19c1d71f1749b483de2919a1d9fc811dcce919/packages/suite-native/src/screens/Home.tsx)
2. Use that code while real Trezor device is connect and call `TrezorConnect.getDeviceState()` (also used in that previous version)
3. It should cause that app will freeze completely until device is disconnected

Possible problems:
I tracked issue down to `transport-native` package, it looks it's happening at file `packages/transport-native/android/src/main/java/io/trezor/transport/bridges/USBBridge.java` at line `285`, but I don't know for sure.

**Comment by szymonlesisz** [comment]
im pretty sure it was working at some point, before we created `transport-native` package. could you check commits before that?

**Comment by Nodonisko** [comment]
@szymonlesisz I count with that, but it could be related to new architecture and new native modules implementation in newest RN
