### ISSUE TITLE
CI: connect-popup tests on branch requires connect-explorer build

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#5608]
Manual `connect-popup` job requires `connect-explorer` to be present on given branch.

`connect-explorer` deploy is also set to manual while on branch therefore `connect-popup` tests are always failing with timeout

it would be nice to check if `connect-explorer` is deployed and deploy it if it's not

**Comment by vdovhanych** [comment]
note for myself: 
require `connect-explorer deploy dev manual` job for the `connect-popup manual` job.
use
```yml
needs:
  - connect-explorer deploy dev manual
```

**Comment by vdovhanych** [comment]
@szymonlesisz is it ok that its not displayed at all until the `connect-explorer deploy dev manual` job is run? 

https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/563312824
