### ISSUE TITLE
connect-explorer build/images pollution

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#5609]
`connect-explorer` build produces tons on unnecessary/unused images in `build/images` directory probably because it's using `@trezor/components` package where they are defined

**Comment by martykan** [comment]
Resolved in the new Connect Explorer

**Comment by mroz22** [comment]
great, is it really resolved? I remember giving up trying to fix this since it was caused by some huge index export from @trezor/components
