### ISSUE TITLE
Suite: suite:dev:desktop shows an error

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#561]
<img width="1383" alt="Screenshot 2019-09-24 at 10 23 05" src="https://user-images.githubusercontent.com/6961901/65494621-767f1e80-deb5-11e9-856a-d4f92260e622.png">

**Comment by mroz22** [comment]
Not going to try it now, but it is fixed imho. ReactIntl component does not like not being the only child.
