### ISSUE TITLE
Update connect-examples readmes

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#5619]
I followed the instructions in [connect-examples](https://github.com/trezor/trezor-suite/tree/develop/packages/connect-examples) and discovered some problems:

- [ ] README.md for Node.js is missing.
- [ ] Browser example is missing, the link from the main README is broken.
- [ ] Webextension README instructs to run `yarn prepare`, but the command is missing.

**Comment by mroz22** [comment]
Great, examples were not really finished. One of the problem was that it (in some cases) was impossible to finish it without published connect. now we can do it.
