### ISSUE TITLE
Infinite spinner on Connect for Firefox users with Total Cookie Protection

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#5644]
**Describe the bug**
Using [MyEtherWallet](https://www.myetherwallet.com/wallet/access/hardware?type=overview) on Firefox with Total Cookie Protection results in a continuous loading on connect.trezor.io. 

**Info:**
-   Browser: Firefox 101.0.1
-   OS: OSX 12.2.1
-   Bridge: 2.0.31
-   Firmware Version: TT, 2.5.1

**How to reproduce**
Setup Firefox Total Cookie Protection. Settings > Privacy and Security

 
![Screenshot 2022-06-17 at 16 42 12](https://user-images.githubusercontent.com/216917/174320761-fbfabad3-602f-4f7e-b6b6-5b0c5c64e93b.png)

1. Go to https://www.myetherwallet.com/wallet/access/hardware?type=overview
2. Click Trezor
3. Note the loading spinner

**Screenshots**
Make exemption for particular problem site:
![Screenshot 2022-06-17 at 12 21 15](https://user-images.githubusercontent.com/216917/174322542-50645ba6-fa09-4b6d-9af5-7242244f7cf1.png)

Console error
> Partitioned cookie or storage access was provided to “https://connect.trezor.io/8/iframe.html?version=8.2.8&manifest=IntcImVtYWlsXCI6XCJkZXZAbXlldGhlcndhbGxldC5jb21cIixcImFwcFVybFwiOlwiaHR0cHM6Ly93d3cubXlldGhlcndhbGxldC5jb21cIn0i” because it is loaded in the third-party context and dynamic state partitioning is enabled.

![Screenshot 2022-06-17 at 16 52 55](https://user-images.githubusercontent.com/216917/174322841-17b9cbeb-a62e-4946-a32a-d5c9e438e03f.png)

**Additional context**
The feature is only available to 'easy access' users and is opt in: https://support.mozilla.org/en-US/kb/total-cookie-protection#w_how-do-i-know-if-i-have-early-access

Connect v6 wallet does behave like v8 and thus works in Firefox. Example wallet: https://wallet.xinfin.network/#/access-my-wallet

Suggestion from @mroz22 is to not auto-close the popup in case of error and print it. Though in this case, the popup does not close.

**Comment by wendys-cats** [comment]
related to [this](https://github.com/trezor/connect/issues/784) issue.

**Comment by bosomt** [comment]
**QA OK**

enabled tracking protection for both sites and it works as expected in Firefox

https://adalite.io
https://connect.trezor.io/9/popup.html#
