### ISSUE TITLE
[bug]: Tor does not work

### ISSUE THREAD

**Issue by chrisguida** [trezor/trezor-suite#5645]
**Describe the bug**
When I turn on Tor, no transactions are retrieved. This makes it hard to use Trezor Suite privately. I have Sparrow working on the same laptop with the exact same Tor daemon, so this must be a problem in Trezor Suite.

**Info:**

-   Remembered Wallet: yes
-   Suite Version: Desktop App Version 22.6.2 (22.6.2.18685) (same behavior seen on version 21.12.2)
-   Browser: N/A
-   OS: MacOS 11.6.4 M1 (arm64)
-   Bridge: not sure
-   Firmware Version: 1.10.4

**How to reproduce**

1. Open wallet without Tor.
2. Notice that everything works fine and all transactions are displayed.
3. Turn on Tor:
<img width="821" alt="Screen Shot 2022-06-17 at 11 09 59 AM" src="https://user-images.githubusercontent.com/7445670/174336180-2b653aa6-3f28-4deb-ab7b-9df27bb6e5c4.png">
4. Disconnect and reconnect Trezor

5. Suddenly the backend does not work, but the only message I see is this, which is unsettling:
<img width="347" alt="Screen Shot 2022-06-17 at 11 05 59 AM" src="https://user-images.githubusercontent.com/7445670/174336410-3c204e9f-d407-44aa-9695-488c7ffe67c5.png">
6. Turn Tor back off, and hit "Retry" on the Dashboard.

7. Suddently all transactions show up again.

**Expected behavior**
Tor should be fully supported. This is especially important for using Tor with self-hosted backends such as Embassy, which are difficult/impossible to access via clearnet at this moment.

**Screenshots**
See screenshots above

**Additional context**
This is especially important for using Tor with self-hosted backends such as Embassy, which are difficult/impossible to access via clearnet at this moment.

**Comment by Monero-HackerIndustrial** [comment]
This bug appears to be an issue with the request manager interacting with the tor controller. I see this output on ubuntu terminal. 
```
    at TorController.<anonymous> (/tmp/.mount_TrezortHQQg8/resources/app.asar/node_modules/@trezor/request-manager/lib/controller.js:27:23)
    at Generator.next (<anonymous>)
    at /tmp/.mount_TrezortHQQg8/resources/app.asar/node_modules/@trezor/request-manager/lib/controller.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/.mount_TrezortHQQg8/resources/app.asar/node_modules/@trezor/request-manager/lib/controller.js:4:12)
    at waitUntilResponse (/tmp/.mount_TrezortHQQg8/resources/app.asar/node_modules/@trezor/request-manager/lib/controller.js:25:51)
    at TorController.<anonymous> (/tmp/.mount_TrezortHQQg8/resources/app.asar/node_modules/@trezor/request-manager/lib/controller.js:37:19)
```
Do you know how to force a debug flag to see the output and what specific error it is in a more verbose manner?

**Comment by prusnak** [comment]
Related: There is an ongoing DDoS attack on the Tor network happening since 9th June - the issue has not been resolved yet :-/ https://status.torproject.org/issues/2022-06-09-network-ddos/

**Comment by chrisguida** [comment]
Yes, I'm aware of the DoS attack on Tor, however, that cannot be the problem here since I am able to connect from the exact same laptop to the same exact electrum hidden service from Sparrow with no issues. This is a bug in Trezor Suite.

**Comment by tomasklim** [comment]
@chrisguida 
Hello, could you please check that you still have this issue?

Unfortunately, I am not able to replicate it.

You can run your app with `--log-level=debug` tag. 
Do you see some error messages in terminal regarding `tor` `INFO(tor)`, `ERROR(tor)`,  `DEBUG(tor)`,..?

**Comment by chrisguida** [comment]
Yep, definitely still happening.

I forgot a step, maybe this is it? You need to disconnect the trezor and reconnect it after switching to Tor.

How do I run a mac app with command line arguments? it's just a dmg

**Comment by sime** [comment]
`/Applications/Trezor\ Suite.app/Contents/MacOS/Trezor\ Suite --log-level=debug`

**Comment by chrisguida** [comment]
These logs are a firehose, mostly with this:

<img width="918" alt="Screen Shot 2022-06-24 at 10 12 08 AM" src="https://user-images.githubusercontent.com/7445670/175564864-8435b7dd-0fcd-4cff-8e8e-234d52481e5f.png">

Here's some more interesting-looking parts:
<img width="1136" alt="Screen Shot 2022-06-24 at 10 14 36 AM" src="https://user-images.githubusercontent.com/7445670/175565428-0f942c52-ec7d-49b6-9470-a3617f771ba3.png">

<img width="1440" alt="Screen Shot 2022-06-24 at 10 20 07 AM" src="https://user-images.githubusercontent.com/7445670/175566397-080207dd-de9e-4ea0-b8e2-2b065f8a46e1.png">
<img width="911" alt="Screen Shot 2022-06-24 at 10 20 35 AM" src="https://user-images.githubusercontent.com/7445670/175566407-2ddb7aca-03b7-438a-8258-6e0624127fdd.png">

I'm guessing there are timeouts set too low, Tor has been known not to respond for long periods of time, perhaps 30-60s.

Seems the predominant (first screenshot) error involves attempting to set a timeout to infinity? Perhaps that's the issue?

**Comment by hynek-jina** [comment]
This issue seems to be quite general.. 
It is probably covered by issues with label https://github.com/trezor/trezor-suite/labels/tor
_Can I close this one?_

**Comment by chrisguida** [comment]
I've tested this with the latest version of Trezor Suite, and the issue does appear to be fixed. Thanks so much!! 🎉🙏

**Comment by chrisguida** [comment]
"Not planned"? I'd say "complete".
