### ISSUE TITLE
Firmware binaries other than latest and intermediary are not available in Suite

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#5672]
Only the latest and intermediary Firmware binaries are currently available in Suite (both web and desktop) and there is no fallback on [https://data.trezor.io](https://data.trezor.io).

Not sure if it's causing a bug (if there is any FW version, that doesn't meet the criteria to update to intermediary or latest) - needs to be verified.

Even if it's not a bug, it's not intended behavior and the logic could be fixed (provide a fallback?) or simplified.

Together with fixing this, update the description here: https://github.com/trezor/trezor-suite/blob/107cb8eefebf17704dbf875903355b80c4e30376/docs/releases/adding-new-firmwares.md?plain=1#L7

**Comment by komret** [comment]
🤔 Isn't this the intended behavior?
