### ISSUE TITLE
Sign message dialogue design broken

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#5675]
**Describe the bug**
See screenshots. In recent change Sign dialogue design has changed and address and signature does not fit to fields.
tested on multiple computers. 

**Steps to reproduce:**
1. Navigate to Sign message section
2. Select address and observe design
3. Sign message and observe Signature field

**Info:**
 - Suite version: web 22.7.0 (a92092adee0fc61f4bc2c8a404f40e47323c1450)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.9.4 regular (revision ffa96205fb5e22b43e7b08a3dbc3cdeee0931de3)
 - Transport: bridge 2.0.31

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/175264318-d4ca75b9-b1fa-496d-b8d8-cf9d476a6393.png)

![image](https://user-images.githubusercontent.com/31506317/175264449-fc890ce4-221e-40be-b280-51737bf26232.png)

**Comment by bosomt** [comment]
is it possible that it's related to this change ? https://github.com/trezor/trezor-suite/issues/5532

**Comment by komret** [comment]
> is it possible that it's related to this change ? #5532

Indeed, thanks!

QA: Please check no other Select has incorrect width.

**Comment by bosomt** [comment]
**QA OK**

Recovery drop down select will be tested in https://github.com/trezor/trezor-suite/issues/5532 that needs QA too.

**Info:**
 - Suite version: desktop 22.7.0 (df0ea0625bd3adde3aa18dd16792890a59f97926)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
