### ISSUE TITLE
Stop using `EthereumGetPublicKey` in Connect

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-suite#5683]
It is functionally identical to `GetPublicKey`, so in theory you should be able to just replace `EthereumGetPublicKey` calls with `GetPublicKey` (plus the appropriate return type) with no other changes.

**Comment by matejcik** [comment]
see https://github.com/trezor/trezor-firmware/issues/2350 for discussion -- maybe I was too hasty with the whole thing

**Comment by matejcik** [comment]
...okay, maybe not right now :)

**Comment by bosomt** [comment]
Moving to approved :)
