### ISSUE TITLE
"You were disconnected" on welcome page & in onboarding

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5696]
**Describe the bug**
Users miss info that they are offline when on Welcome Page or in Onboarding

**Info:**

-   Suite Version: desktop, 22.5.2

**How to reproduce**
Steps to reproduce the behaviour:

1. Disconnect
2. Launch the app with a clear device

**Expected behaviour**
Users should see a banner 
![Screenshot 2022-06-27 at 17 01 03](https://user-images.githubusercontent.com/33235762/175972039-6313e920-8ae2-419b-8239-e7b445ba3199.png)

**Comment by MiroslavProchazka** [comment]
Since it's quite an edge case and we are not planning to dive further into this topic in upcoming months I'm closing it for now. Leaving option to possibly re-open it for @Hermez-cz
