### ISSUE TITLE
suite-native: use @trezor/connect for watch-only implementation

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#5708]
We will need connect for fetching transactions and fiat prices etc from blockbook. This PR should be just simply adding connect to mobile app, init it and test if we can fetch transactions etc. 

Storing of transaction to redux, rendering them etc. is NOT part of this issue. There will be follow up task (TODO link it here).
Connecting to Trezor device is NOT part of this issue.

**Implementation ideas/questing:**
1. Will connect work without device, for just xpub?
2. I would imagine we could have package, for these connect-setup stuff.3. 
3. Would be really nice if that package could be shared between suite, I think it could be pretty achievable. From what I have seen in suite code these two files will be most interesting for you:
`packages/suite/src/actions/suite/trezorConnectActions.ts`
`packages/connect-explorer/src/reducers/trezorConnectReducer.ts`

4. I think these two files could be moved to some brand new `@suite-common/connect` package (you may need to add suite-common workspace in yarn). Then you can refactor them to be reusable and to use `redux-toolkit` in new package. There will some challenges but is definitely doable, reducer should be simple, actions file will harder because there are some specific actions related suite which we don't have in mobile yet, so we will probably need two different init actions. You can use react native file suffix to achieve that like `initConnect.native.tsx`.

5. Also please pay attention that you **can't import from suite/ in new package** because that would be cyclic dependency, so maybe you will need to move some things to this package or create thrid package that will be used both with connect package and old suite core package. Another approach could be use something like generator function like `const generateInitAction = ({erroAction) => (dispatch, getState) => { dispatch(errorAction(err)) ...... }` where you will generate init function and can pass these specific functions or whatever to generator first.

6. **What I totally recommend is to do TDD**, before you even beggin refactoring, write tests for that old code and then start refactoring and in the end, you should pass this tests also with refactored code. That should minimalize risk of breaking desktop suite during refactor. Test for `actions` are actually here, so verify if they are enough and for `reducer` you have to write them. **Without doing TDD refactoring will take us to bug hell.**7. 

7. You might need to change `createStore` in suite to `configureStore` from redux-toolkit. 

**People that can help you:**
- @mroz22 - I totally recommend to have call with him before begin. Let him do to some introduction of connect, discuss some possibilties with him etc.
- @matejkriz - Suite related stuff

**Comment by sime** [comment]
When collaborating with @mroz22, loop me in too. I'm also the PM for Trezor Connect.

**Comment by sime** [comment]
Should be able to get pretty fair with the [getAccountInfo](https://connect.trezor.io/9/#/method/getAccountInfo-advanced) method.
```javascript
TrezorConnect.getAccountInfo({
  coin: "btc",
  descriptor: "zpub6rszzdAK6RuafeRwyN8z1cgWcXCuKbLmjjfnrW4fWKtcoXQ8787214pNJjnBG5UATyghuNzjn6Lfp5k5xymrLFJnCy46bMYJPyZsbpFGagT",
  path: "m/84'/0'/0'",
  details: "txs"
});
```

**Comment by bouchja1** [comment]
Ad 1) yes, with some modifications in connect and blockchain-link for RN (https://github.com/trezor/trezor-suite/pull/5741)

Ad 2) I have confirmed with Matěj that it is `packages/suite/src/reducers/suite/deviceReducer.ts` and not `packages/connect-explorer/src/reducers/trezorConnectReducer.ts`

Ad 3) According to the previous point, I believe it is covered in `packages/suite/src/reducers/suite/__tests__/deviceReducer.test.ts`
