### ISSUE TITLE
suite-native: transactions storing, logic

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#5709]
Shared package for both desktop and mobile and directly implement for desktop.

**Implementation ideas:**
1. **Please do TDD and please read description task of #5708 where is lot of info about how to create shared packages**
2. Should be shared package probably could be called `@suite-common/wallet-transactions` and should use `redux-toolkit`
3. These files in suite will be most interesting: `packages/suite/src/reducers/wallet/transactionReducer.ts` and `packages/suite/src/actions/wallet/transactionActions.ts` but maybe there will be more of them.
4. ~~Consider of use https://redux-toolkit.js.org/api/createEntityAdapter for storing transactions which will actually need some refactoring also in desktop suite, but it could be worth it.~~ Lets keep it simple for now...
5. This package should NOT contain any UI related stuff, just logic

People that can help you:
@matejkriz - quick call with before begin should help you or should point you to person who knows most about transactions in suite

**Comment by juriczech** [comment]
https://github.com/trezor/trezor-suite/pull/5981
