### ISSUE TITLE
Standard passphrase is incorrect after app upgrade

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#5735]
**Describe the bug**
Users are reporting problems with remembered wallets.
See Steps to reproduce. 

After upgrade you can't add coins/accounts or receive transaction.
Add account or coin: `Account discovery error Passphrase is incorrect`
Receive address: `Address verification error: Passphrase is incorrect` 

**Steps to reproduce:**
1. Load standard wallet with passphrase disabled
2. Remember wallet
3. Upgrade from app 22.5.3 to 22.6.4
4. Try to receive,add account or coin and observe

**Info:**
 - Suite version: desktop 22.6.4 (5fc4cec20d2b691634e695f7547cb955cff22171)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.4 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Screenshots:**

https://user-images.githubusercontent.com/31506317/176876870-0a2ba815-5a35-40d4-9713-a6afd40106c4.mov

**Comment by mroz22** [comment]
should be fixed now

**Comment by bosomt** [comment]
**QA OK**

fixed in 22.6.5 (62202b) release
