### ISSUE TITLE
Import of transaction from csv format (PASTE)

### ISSUE THREAD

**Issue by abgit** [trezor/trezor-suite#5739]
With old wallet we could send funds to multiple addresses with "import" a csv with just a copy/paste .. a simple textarea.
With trezor suite, import is only possible if we select a local File with csv content.

A textarea to just paste the csv content (like in old wallet) would be great in trezor suite.
Copy/Paste is really nice on some situations.. otherwise we need to create a csv text file, paste csv content on file, save, upload to trezor suite and delete file. With paste into a textarea we just need to paste and go. Much much simple.

Maybe just turn trezor suite import compatible with file and paste in a textarea?

best,

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.1.1 (c4cf80383d5f554ff118ba507b743074e73216d4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.5 regular (revision f4d3a7456afaa850f9651d31ddc9d7e4b68ab7b8)
 - Transport: BridgeTransport 2.0.33
