### ISSUE TITLE
Connect Explorer: Include ERC20 transaction example

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#5744]
**Spec:**
Introduce a ERC20 transaction example into connect explorer.
 
https://connect.trezor.io/9/#/method/ethereumSignTransaction-erc20

**Comment by Adamj1232** [comment]
+1 This would be very helpful!

**Comment by martykan** [comment]
There is an ERC20 example in the new Explorer

https://connect.trezor.io/9/methods/ethereum/ethereumSignTransaction/
