### ISSUE TITLE
Connect v9 integration tracker

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#5757]
Meta issue for tracking PRs integrating Connect v9.

|Project|PR|Status|Mantainer
|-|-|-|-|
| MetaMask | https://github.com/MetaMask/eth-trezor-keyring/pull/132 | Done ✅ |
| [MyEtherWallet](https://www.myetherwallet.com/) | | Done ✅ 
| [MyCrypto](https://mycrypto.com/) | https://github.com/MyCryptoHQ/wallets/pull/34 |  |
| AdaLite | https://github.com/vacuumlabs/adalite/pull/1342 | Done ✅
| [Theta Wallet](https://github.com/thetatoken/theta-wallet-web) | https://github.com/thetatoken/theta-wallet-web/pull/79 | Done ✅
| [Unchained](https://github.com/unchained-capital/unchained-wallets) | https://github.com/unchained-capital/unchained-wallets/pull/74 | Approved! ✅  |
| [FindETH](https://github.com/Mrtenz/FindETH) |  | v7 lol
| [Sovryn](https://github.com/DistributedCollective/sovryn-monorepo/tree/development/packages/wallet) | https://github.com/DistributedCollective/sovryn-monorepo/issues/31 |Done ✅
| Stellar |https://github.com/stellar/account-viewer-v2/pull/391|Done ✅|
| [Ambire Wallet](https://github.com/AmbireTech/wallet) | https://github.com/AmbireTech/wallet/pull/5 | Done ✅ 
| [NuFi](https://wallet.nu.fi/) | | Done ✅ |@gabrielKerekes
|[Cardano hw cli](https://github.com/vacuumlabs/cardano-hw-cli/pull/127/files#diff-826ea20816b036c9f6e1397682f6167db2281fa321ff17c2b0723614da2a990dR10)|| Done ✅ 
|[enkrypt](https://github.com/enkryptcom/enKrypt/tree/main/packages/hw-wallets)|https://github.com/enkryptcom/enKrypt/pull/149|Done ✅|
|[Eternl](https://eternl.io/)|https://github.com/ccwalletio/tracker/issues/133|Done ✅|
|[Typhon](https://typhonwallet.io/#/)|[contact@typhonwallet.io](mailto:contact@typhonwallet.io)|noticed|
|[Nami](https://namiwallet.io/)|https://github.com/berry-pool/nami/issues/744|Done ✅|
|[Flint](https://flint-wallet.com/)|https://github.com/dcSpark/cardano-caniuse/issues/9|Done ✅ |
|[Gerrowallet](https://gerowallet.io/)|helpdesk@gerowallet.io|Done ✅
|curve.fi|https://github.com/curvefi/curve-contract/issues/170|Done ✅
|Rabby|https://github.com/RabbyHub/Rabby/issues/1221|Done ✅ 
|Stellar.org|https://github.com/stellar/account-viewer-v2/issues/393|Done ✅
|Frame|https://github.com/floating/frame/issues/1330|Done ✅
|Chaintek|https://wallet.chaintek.net/|Done ✅| @Scotty0448
|[Paraswap](https://github.com/paraswap/paraswap-dex-lib/issues/399)|https://app.paraswap.io/#/?network=ethereum|sent| 
|[Safe](https://app.safe.global/welcome)|https://github.com/safe-global/safe-wallet-web/issues/2045|Done ✅|

**Comment by mroz22** [comment]
the first non-beta version of @trezor/connect has just been released. lets proceed with updating integrations PRs and do some testing.

**Comment by bosomt** [comment]
adalite.io is already using connect v9 , 
version 9.0.0

<img width="377" alt="image" src="https://user-images.githubusercontent.com/31506317/235633526-f4921ef5-304d-4b46-a69e-f7eb7cbd7497.png">

**Comment by bosomt** [comment]
GeroWallet chrome extension is already using connect v9

**Comment by Hannsek** [comment]
9.0.0 in adalite? How is this possible @mroz22 ?

edit: Adalite behave somehow special with server traffic (or something like this) afaik. You even cannot inject newer Connect into the site.

**Comment by bosomt** [comment]
meta Mask already using connect v9 🎉

**Comment by bosomt** [comment]
curve.fi already integrated connect v9


<img width="1322" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/71f0c81d-0fdb-418b-8596-65b1ff1ed0d4">

**Comment by bosomt** [comment]
Safe | safe-global/safe-wallet-web#2045
-- | --


is already using Connect v9 🎉

**Comment by Hannsek** [comment]
Closing this as majority of apps has updated. We can still edit it and keep adding comments.
