### ISSUE TITLE
Send form - import csv - metadata (labels)

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#5770]
When importing csv to fill send form, it should be able to process label column as well.

### Current import via Trezor Suite
<img width="970" alt="Screenshot 2022-07-12 at 16 18 06" src="https://user-images.githubusercontent.com/216917/186368236-74640fd4-9108-4613-8401-b5b36b8ac466.png">

### Old web wallet import
<img width="622" alt="Screenshot 2022-07-12 at 16 20 07" src="https://user-images.githubusercontent.com/216917/186368334-3e7a1745-448f-496e-afd4-3b8cb7ede4a1.png">

**Comment by bosomt** [comment]
**QA OK**

only one nitpick: when you bump transaction labels are gone ;)

![image](https://user-images.githubusercontent.com/31506317/205087120-e0f041c5-a4d0-4895-a29e-5ca4c059a09d.png)

<img width="531" alt="image" src="https://user-images.githubusercontent.com/31506317/205087294-0b9f1708-0900-4e3b-bd3b-76d9a098bcfc.png">

**Info:**
 - Suite version: web 22.12.0 (68434754c8bdad7ee98eb3c2dd9a2fab3477782d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0
 - OS: MacIntel
 - Screen: 2160x1350
 - Device: model 1 1.10.3 Universal (revision 9276b1702361f70e094286e2f89e919d8a230d5c)
 - Transport: bridge 2.0.32

**Comment by sime** [comment]
@bosomt I imagine this happens for all bumped transaction? Technically, I imagine this is because of new TX ID ?

**Comment by mroz22** [comment]
yep, there is a issue somewhere maybe already.

**Comment by sime** [comment]
@bosomt2 Please create an issue (or link it) when bumped transaction loose their labels.

**Comment by sime** [comment]
@mroz22 Any hesitation with updating the example to include label:

```
address,amount,currency,label
tb1qqmg2mtmugpld08wczesag8mn2s6ae7vg6qw096,0.31337,TEST,Important transaction
tb1qhvslkhdvxwzwrhu3qxsc5jlx868vez0vxrrzl0,0.1,USD,Sending coins to mother
```

**Comment by mroz22** [comment]
@sime no problem with that. should label in the example appear only if labeling is active? probably bes to open another issue for this. And ofc it is lowhanging

**Comment by Hannsek** [comment]
I suppose so. https://github.com/trezor/trezor-suite/issues/7194
