### ISSUE TITLE
Can't delete labels

### ISSUE THREAD

**Issue by rocketeerbkw** [trezor/trezor-suite#5772]
**Describe the bug**
Once an address or transaction has been labelled, it's impossible to remove the label.

**Info:**

-   Remembered Wallet: yes
-   Suite Version: app 22.6.5
-   Browser: n/a
-   OS: MacOS Montery 12.4
-   Bridge: unknown
-   Firmware Version: Model T 2.5.1

**How to reproduce**

1. Enable labelling in Trezor Suite
2. Add a label to an address
3. See there is only "edit label" no "delete label" option
4. Click "edit label"
5. No matter what is entered into the label field, even an empty string, it always remains

**Expected behavior**
A button to delete a label. Or when saving the label with an empty string to delete the label.

**Comment by STew790** [comment]
There is actually a way to delete your labels, but I do agree that it is really inconvenient and something like a "delete" button should be present.

You can actually delete your label by clicking on "Edit" and then writing just one letter and deleting it and then when you confirm this empty string, it actually deletes the label.

Not sure if this should be a bug or a "feature request". cc @hynek-jina

**Comment by hynek-jina** [comment]
Then it make sense as a feature improvement request.

**Comment by rocketeerbkw** [comment]
> when you confirm this empty string, it actually deletes the label

Did you try to reproduce this? It does't work. I updated my steps to be more clear but when I said "No matter what is entered in the label field" in step 5 that included an empty string because I tried that already.

> A button to delete a label. Or when saving the label with an **empty string** to delete the label.

I also already mentioned in the expected behavior that an empty string should delete the label, meaning that it currently doesn't.

I checked the code and saw that it should [delete under some conditions](https://github.com/trezor/trezor-suite/blob/7ea0a9f3a8d9072cbc22d48d49578c55428ae042/packages/suite/src/actions/suite/metadataActions.ts#L528) (like an empty string) but those conditions are never met, so it's a bug IMHO.

**Comment by STew790** [comment]
> Did you try to reproduce this? It does't work. I updated my steps to be more clear but when I said "No matter what is entered in the label field" in step 5 that included an empty string because I tried that already.

Unfortunately, yes, I know that if you just click on "Edit" and confirm an empty string, it doesn't work.

But as I mentioned here:

> You can actually delete your label by clicking on "Edit" and then writing just one letter and deleting it and then when you confirm this empty string, it actually deletes the label.

You need to:

1.  click on the "Edit" 
2. write something 
3. delete it with backspace/delete 
4. then confirm it 

The label is removed for me after that, I just tried it again. I tried to make a video (I hope it makes more sense):

https://user-images.githubusercontent.com/48477147/179023024-765bb28f-1dac-427f-8f00-9a46515b26b3.mp4

**Comment by rocketeerbkw** [comment]
I did follow these instructions you gave in your original reply and it didn't work for me:

>You can actually delete your label by clicking on "Edit" and then writing just one letter and deleting it and then when you confirm this empty string, it actually deletes the label.

But your video solved the mystery. When you say "confirm this empty string" and "4. then confirm it" you're using the `enter` key. When I was confirming it, I was clicking the checkbox button.

So I tested again, and when following your steps with the enter key, it gets deleted. When following your steps with the checkbox button, it reverts back to the previous text.

Steps to reproduce:

1. Have a label called "test"
2. Click on "edit label"
3. write something
4. delete it with backspace/delete
5. then confirm it **with the checkbox button**
6. the label will revert to "test"

**Comment by STew790** [comment]
Ok, I see, my bad. I just instinctively confirmed it with "enter" key but with clicking on the confirm tick, it indeed doesn't work. Thank you!

Adding back the "bug" label. The repro steps are as @rocketeerbkw mentioned. User should be able to "delete" the label via the confirm tick button.

**Comment by rocketeerbkw** [comment]
Tested in 24.10.1 and it seems to be working better. Saving a label with an empty string by clicking or pressing enter deletes the label.

Would still be nice to have a specific "delete" label but I'll close my issue.

**Comment by Lemonexe** [comment]
This applies to the Legacy labelling, which was replaced by the new Suite Sync labelling.
Legacy labelling is maintenance-only, and will be sunset at some point in future.
FYI, Suite Sync already supports deleting labels, check it out 😉
