### ISSUE TITLE
Make MetaMask tests run with Trezor Connect v9

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#5776]
Swapping in Connect v9 for v8 throws an unexpected error in unit tests:

> Error: TrezorConnect has been already initialized
> https://github.com/MetaMask/eth-trezor-keyring/runs/7038556243?check_suite_focus=true#step:10:15

https://github.com/MetaMask/eth-trezor-keyring/pull/132

**Comment by mroz22** [comment]
Should be fixed here https://github.com/MetaMask/eth-trezor-keyring/pull/133
