### ISSUE TITLE
Disable device menu/hidden wallet option when app is not wallet

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#578]
![Screenshot from 2019-09-26 09-33-08](https://user-images.githubusercontent.com/50332311/65667825-ca6a3e80-e040-11e9-8a34-41658491ec23.png)

**Comment by slowbackspace** [comment]
My idea (issue https://github.com/trezor/trezor-suite/issues/126) is that every subapp (TPM, device settings) could pass her own custom menu items to the Suite wrapper (suite handles the rendering of the device menu). So device settings could just send null/undefined/empty array/whatever to let the wrapper know there are not any custom menu items. But idk, maybe it's an overkill.

**Comment by vladimirvolek** [comment]
duplicated of https://github.com/trezor/trezor-suite/issues/126
