### ISSUE TITLE
How to register email and app URL to actually use the SDK?

### ISSUE THREAD

**Issue by JeremyBernier** [trezor/trezor-suite#5789]
According to the [documentation](https://github.com/trezor/connect/blob/develop/docs/index.md#trezor-connect-manifest), one needs to have their email and app URL registered in order to actually use the SDK. Yet there is no mention anywhere of how to actually register.

If anyone could point me to where/how to actually register to use the SDK, that'd be helpful as then I could actually use this SDK

> Starting with Trezor Connect 7, we have implemented a new feature — Trezor Connect Manifest — which requires that you as a Trezor Connect integrator, to share your e-mail and application url with us. This provides us with the ability to reach you in case of any required maintenance. This subscription is mandatory. Trezor Connect raises an error that reads "Manifest not set. Read more at https://github.com/trezor/connect/blob/develop/docs/index.md" if manifest is not provided.

```
TrezorConnect.manifest({
    email: 'developer@xyz.com',
    appUrl: 'http://your.application.com'
})
```

**Comment by sime** [comment]
@JeremyBernier Just include a real E-Mail address and your appUrl, and you will be good to go.

There is no formal registration process :)
