### ISSUE TITLE
Unable to enter IPv6 address for connection to custom Electrum server

### ISSUE THREAD

**Issue by jan386** [trezor/trezor-suite#5798]
**Describe the bug**
As the title states, it is not possible to enter an IPv6 address into Trezor Suite for connection to my own Electrum server. When attempting to input IPv6 address, it is not accepted, remains in red and Invalid URL is shown.

**Info:**

-   Remembered Wallet: no
-   Suite Version: app version 22.6.5
-   Browser: not relevant
-   OS: Windows 10 Pro, 21H2, 19044.1826
-   Bridge: not relevant
-   Firmware Version: not relevant

**How to reproduce**

1. Go to Settings -> Crypto, hover over Bitcoin, click gear icon
2. Choose Custom Electrum server.
3. Input a valid IPv6 address, followd by a colon, port number, colon and service type (e.g. 1234:5678:90ab::cdef:50002:s).
4. Observe that address is shown in red, Invalid URL is displayed and Confirm button is greyed out.
Note: the error is not remedied by placing the IPv6 address in square brackets like so: [1234:5678:90ab::cdef]:50002:s , which is a common way to refer to IPv6:port in web browsers.

**Expected behavior**
Expected behaviour would be for Trezor Suite to parse the IPv6 correctly and attempt to connect to it using the specified port.

**Screenshots**
Screenshots are added.
![ipv6_1](https://user-images.githubusercontent.com/52366922/179367960-a694cc66-3535-49dd-a308-ebf7f5e5c4b6.png)
![ipv6_2](https://user-images.githubusercontent.com/52366922/179367961-db51c787-97b8-4608-bed9-929d8d0d004a.png)

**Additional context**
If more information is needed, let me know. I would be happy to provide it.

**Comment by marekrjpolak** [comment]
Hello @jan386, it's only a matter of URL validation and therefore should be relatively easy to fix. I'll look at it ASAP.

**Comment by bosomt** [comment]
**QA OK**

<img width="323" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/85546e6d-313d-4b99-927b-8887c033f2dd">


**Info:**
 - Suite version: desktop 23.9.0 (625ccb6675c533896b97651c60fb95752325b0c3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 regular (revision b151a3db6b04d2bee0bb68470e57b822443bf83d)
 - Transport: BridgeTransport 2.0.33
