### ISSUE TITLE
Implement "tags" handling

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#58]
Original post by @prusnak:

In short: I have added ["tags" field](https://github.com/trezor/webwallet-data/commit/edc19368e407d68d50cc3ab3fe15735be01d3ba4) to `releases.json`.

The caller could provide the list of tags when calling `getLatestSafeFw`.

* If the provided "tags" list is empty, use the current behaviour with no change
* If the provided "tags" lists is not empty, find if there is a newer firmware that match one of these tags. If there is a match (at least of one of the tags) return the *newest* firmware which can be applied (i.e. not necessarily the matching one).

Let's talk in person about the details.

**Comment by ZdenekSL** [comment]
https://github.com/trezor/trezor-suite/issues/392

**Comment by tsusanka** [comment]
This needs overall product design and rethink. However product currently has other priorities so I am closing here and passing this to the product backlog.
