### ISSUE TITLE
Tor splashscreen on Suite launch

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5805]
[Notion](https://www.notion.so/satoshilabs/Tor-Preflight-loader-Splash-screen-fd922b2d142c4d719f356e941b1bff71)

**Comment by STew790** [comment]
**QA OK**
All the scenarios listed in the PR were tested.

1. Starting suite desktop when Tor was not enable in the settings
   
   * expected => it load the app and nothing from the Tor splash screen should be visible
   - actual => app loads and nothing from the Tor splash screen is visible

2. Starting suite desktop when Tor was enable in the settings
   
   * expected => it displays a window with a progress bar that goes to 100% and then it load the normal suite app
   * actual => a window with progress bar is shown that goes to 100% and then the Suite loads
   
3. Starting suite desktop when Tor was enable in settings and disable Tor before it completes the progress
   
   * expected => it display a progress bar that goes to 100%
   * actual => progress bar that goes to 100% is shown
   
   
   * expected =>if you go to setting you should see Tor disable
   * actual => Tor is disabled in the settings
   
   
   * expected => Tor process should be properly closed
   * actual => Tor process is properly closed
   
4. Starting suite desktop when Tor was enable in settings and make it fail for example disconnecting the internet from your computer
   
   * expected => it should display a red progress bar and allow the user to "Disable Tor" and "Try again"
   * actual => red progress bar is shown and a "Try again" button appears under the progress bar
   
   * expected => when "Try again" is pressed it should start new Tor process and if now you connect your computer to the internet it should complete the progress bar and load the app normally.
   * actual => the progress bar is completed and Tor is switched on if you press the "Try again" button

**Info:**
 - Suite version: desktop 22.9.0 (4d282475dccf0c52a0094e9b024fce5ad7c54e53)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.9.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by Hannsek** [comment]
**Design feedback**

- align progress bar text 
![image](https://user-images.githubusercontent.com/57008159/184328750-a3107a70-b8ba-4323-be28-9545f852bbc1.png)
- put `disable Tor` button under the progress bar rather then next to it

**Comment by bosomt** [comment]
Do we have follow up task to add Tor splash screen to onboarding ?
I'm really missing at least abort button because Tor enabling during onboarding fail almost every-time at first try.
Maybe I should create separate issue for Tor enable fails or is there one ?

**Comment by karliatto** [comment]
If "Tor enabling during onboarding fail almost every-time at first try" it would be great to create an issue to investigate why it happens so often in onboarding.
@bosomt does it happens so often for you if you enable it in settings for example?

**Comment by bosomt** [comment]
@karliatto it happens quite often when enabling for first time, no idea why.
Second time is always successful.

**Comment by STew790** [comment]
**QA OK**
Percentages changed so they are next to the loading bar. 

**Info:**
 - Suite version: desktop 22.9.0 (f52011f3b8dc4c9439b7b787cce8959b70bc25e8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.9.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: bridge 2.0.32
