### ISSUE TITLE
You need to advertise your public key for Desktop App validation

### ISSUE THREAD

**Issue by TomzBench** [trezor/trezor-suite#5809]
You list instructions for validating the Satoshi Labs Trezor-Suite Desktop Application here: https://wiki.trezor.io/Apps:Trezor_Suite#How_to_run

These instructions explain to ignore the warning, explaining that "This warning just means that this key is not certified by a third party authority".

That's true, but because the key is not validated by a "third party authority", the user needs to validate themself. By observing the signature and verifying it matches "Something" they trust.  In this case, the user is trusting Satoshi Labs. But for me to know the app wasn't interfered with by a middle man, i need to verify the signature with one you advertise.

For example, I download the Satoshi Suite app and get fingerprint EB48 3B26 B078 A4AA 1B6F  425E E21B 6950 A2EC B65C.  But I have no idea if that is legit or not unless I see you advertise this somewhere on your public web somewhere.  (I can then confirm this key fingerprint from  multiple computers and sources to know it is a good key)

**Comment by hynek-jina** [comment]
@TomzBench Thanks for the comment.
To verify Trezor Suite, you can download the app directly from https://github.com/trezor/trezor-suite/releases
Then compare with the keys from the web https://suite.trezor.io/

However, we will consider publishing to a third site. 
_I'll close the issue now, but if you have any other thoughts on it, we can reopen it. Thanks_

**Comment by TomzBench** [comment]
You should advertise the finger print of your signing key from multiple locations so that when users verify their software simply.

Here is a guide that documents what I am talking about.

https://www.qubes-os.org/security/verifying-signatures/
