### ISSUE TITLE
Broken download links for trezor bridge

### ISSUE THREAD

**Issue by refi93** [trezor/trezor-suite#5833]
**Describe the bug**
When I visit https://suite.trezor.io/web/bridge/ to download trezor bridge, the links for the installers seem to be broken. If I try e.g. "Windows", it takes me to https://data.trezor.iobridge/2.0.27/trezor-bridge-2.0.27-win32-install.exe so the host URL doesn't seem to be properly concatenated with the rest of the path

**Info:**

-   Remembered Wallet: yes/no
-   Suite Version: app/web, commit
-   Browser: name, version
-   OS: name, version
-   Bridge: version
-   Firmware Version: model, version/commit

**How to reproduce**

1. Go to https://suite.trezor.io/web/bridge/
1. Select "Windows"
1. Click on "Download ..." button
1. I get redirected to https://data.trezor.iobridge/2.0.27/trezor-bridge-2.0.27-win32-install.exe which is not a valid URL

**Expected behavior**
Get redirected to https://data.trezor.io/bridge/2.0.27/trezor-bridge-2.0.27-win32-install.exe

**Screenshots**

**Additional context**

**Comment by sime** [comment]
Thanks @refi93. We are on it: https://github.com/trezor/trezor-suite/pull/5824

(Not released as yet)
