### ISSUE TITLE
Trezor Wiki doesn't say anything about Cardano using the Trezor Suite

### ISSUE THREAD

**Issue by melroy89** [trezor/trezor-suite#5837]
**Describe the bug**

Since I have no other place to share this. I will create this bug report here.

When you visit the [official trezor wiki - Cardano page](https://wiki.trezor.io/Cardano), there is no mention at all about the Cardano support native in the Trezor Suite. Why!?

**How to reproduce**

1. Go to [https://wiki.trezor.io/Cardano](https://wiki.trezor.io/Cardano)
2. See there is no mentioning about the **native support in Trezor Suite**, but only _AdaLite_ is explained!??

**Expected behavior**

I expected that your wiki page was explaining about the Trezor Suite on your Cardano wiki page.

**Screenshots**

![image](https://user-images.githubusercontent.com/628926/180669484-1514ecef-3e06-4926-a876-f8800e2a32d6.png)

**Comment by melroy89** [comment]
I couldn't select documentation as an issue. Maybe create such a GitHub issue template as well?

**Comment by hynek-jina** [comment]
@danger89 no worries.. it's just label..

**Comment by tomasklim** [comment]
It's there now

**Comment by bosomt** [comment]
**QA OK**
