### ISSUE TITLE
After intercepting request evaluation

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#5845]
## Description
After successful interception decide what to do with the request.
Use header requests (still we need to decide which one, that will allow to pass multiple variable data in that header) to evaluate if we need to create new TOR circuit or use default one or not use TOR if it is disable.

## Notes
* the http header that we want to reuse should have an identity identification and maybe later a timeout. So it should be able to have a string that we later on can parse and still be a valid http request.

**Comment by STew790** [comment]
Pre-requisities for CoinJoin, no QA needed.
