### ISSUE TITLE
Analytics event 'suite-ready' is sometimes missing in the data

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5848]
**Describe the bug**

Some of the analytics sessions are missing `suite-ready` and `device-connect` events. It is probably caused by network which is not properly working on the launch of the app.

**Comment by STew790** [comment]
See comment in the PR https://github.com/trezor/trezor-suite/pull/5847#issuecomment-1206380586

**Comment by STew790** [comment]
**QA OK**
Updated my comment and cleared up a misunderstanding.
