### ISSUE TITLE
Analytics: use Suite versioning

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5856]
Right now, we are using custom analytics versioning.

The problem is that if we do not change analytics in a specific Suite version, the analytics version is not bumped. However, analytics data can change or get broken, because there can be a change which can influence analytics. This can result into different behavior of the same version of analytics.

**Comment by hynek-jina** [comment]
@kolomaznikt Please confirm if you agree..

**Comment by kolomaznikt** [comment]
@hynek-jina Agree, we've discussed it with @tomasklim

**Comment by bosomt** [comment]
**QA OK**

<img width="551" alt="image" src="https://user-images.githubusercontent.com/31506317/189321040-2038ac54-5658-4c1d-9e44-f7cc22c0ef85.png">



**Info:**
 - Suite version: web 22.10.0 (93297ce96e2fd2a38c341808a3680f72747ed4bb)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31
