### ISSUE TITLE
Landing page: Offering desktop app only for Windows 10

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5858]
**Describe the bug**
On the landing page, we offer the Desktop app for Windows 10, which also works on Windows 11. 

Probably we should call it just `Windows` and update icon?

**Screenshots**
![Screenshot 2022-07-27 at 12 49 19](https://user-images.githubusercontent.com/33235762/181229518-c6ac091f-09a8-4fe2-9c3b-86f05c4bf4ff.png)

**Comment by tomasklim** [comment]
And, I am not sure how is it nowadays with arm and x86 Windows? @vdovhanych

**Comment by vdovhanych** [comment]
There is an arm window version but it has such a small user base that I would not worry about it for now.

**Comment by sime** [comment]
`Windows` sounds easy, do we support Window 7? Currently it [matches the Windows 11 usage](https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide/).

**Comment by hynek-jina** [comment]
Change name to `Windows` (without version number) and update its icon

**Comment by komret** [comment]
**QA:** The icon has changed and it say "Windows" instead of "Windows 10".

**Comment by bosomt** [comment]
**QA OK**

Suite-web/develop/

<img width="225" alt="image" src="https://user-images.githubusercontent.com/31506317/189079978-db33db43-8e45-4dc4-91f6-c0f5518b4715.png">
