### ISSUE TITLE
Analytics is disabled in fresh app on navigating to Settings

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5861]
**Describe the bug**
In the fresh app, if a user goes to settings before giving us consent to use analytics/sentry. The analytics consent step is skipped and analytics is not working.

**Info:**

- In 22.6.x it is disabled in settings
- In <22.6.x it looks enabled but it is not reporting

**How to reproduce**

1. Reset app
1. Go to settings
1. Connect device
1. You are in the app without giving us consent

**Why**
`@suite/set-flag` - `initialRun` is set to false on navigating to settings 

- [ ] Together with fix please create e2e test

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.9.0 (f385f10a1fcd82339636d9c40f669c365a9e0c90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31
