### ISSUE TITLE
Improve GetFirmwareHash error handling

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-suite#5868]
**Describe the bug**

When `GetFirmwareHash` returns an error such as "Unknown message", the dialog below is displayed, but there is no red banner, nothing saying that the user should contact Trezor support, see https://github.com/trezor/trezor-suite/issues/5377.

![image](https://user-images.githubusercontent.com/42678794/181501066-4b229047-7852-4c43-b670-e4ed2e2a02a9.png)

**Expected behavior**

If the reported firmware version supports `GetFirmwareHash` and the device returns an error response to the `GetFirmwareHash` message, then Suite should behave the same way as if an incorrect hash was returned. If this seems too harsh, then Suite can retry the operation twice, but I think that's not even necessary.

**Comment by hynek-jina** [comment]
QA comment: https://github.com/trezor/trezor-suite/pull/5888#issuecomment-1202381552

**Comment by hynek-jina** [comment]
@STew790 Please retest with `2.4.3` > `2.5.1`

**Comment by STew790** [comment]
**QA OK**

I tried to update `2.4.3>2.5.1` on latest develop and it is showing me correctly the warning and won't let me continue with the onboarding.

![image](https://user-images.githubusercontent.com/48477147/182800270-34c19406-07d6-4755-8c4c-9510ef05e021.png)

**Info:**
 - Suite version: web 22.9.0 (13c3bfd7de81d7b06c3e87433bc4185eab86204b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 Universal (revision b0a7e13c884b2fb4f06a45ba474dbb6f94da3357)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA OK**


tested with all possible scenarios for all models, for example here 
https://www.notion.so/satoshilabs/FW-hash-check-on-T2-and-T3-upon-connection-127dc526060680929931c753653f0946
