### ISSUE TITLE
Display CoinJoin account

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#5873]
> ...Based on https://github.com/trezor/trezor-suite/pull/5871 and https://github.com/trezor/trezor-suite/pull/6016

- [x] Display CJ account always on top all accounts, opened on default (same as Segwit accounts)
- [x] Extend dropdown for Segwit and CoinJoin accounts
- [x] Remove `Trade` tab from CJ account

- [x] Refactor add account button 
    <details>
      <summary>outline a new small component that could be used in AddCoinJoinAccountButton and AddAccountButton</summary>
      
    ```javascript
    interface AddButtonProps {
        disabledMessage?: string | null;
        handleClick: () => void;
    }
    
    export const AddButton = ({ disabledMessage, handleClick }: ButtonProps) => {
        return (
            <Tooltip
                maxWidth={285}
                content={disabledMessage}
            >
                <Button
                    icon="PLUS"
                    variant="primary"
                    isDisabled={!!disabledMessage}
                    onClick={handleClick}
                >
                    <Translation id="TR_ADD_ACCOUNT" />
                </Button>
            </Tooltip>
        );
    };
    ```
    </details>

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.11.0 (da1945300f7e7497d23eef27030f0c31a6efb43b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision eb182b923f39111d9307a25a86a49d395c6611b0)
 - Transport: bridge 2.0.32
