### ISSUE TITLE
REGTEST shouldn't have fiat rates

### ISSUE THREAD

**Issue by marekrjpolak** [trezor/trezor-suite#5875]
**Describe the bug**
REGTEST coins are displayed with fiat rates throughout the Suite (unlike the TEST coins).

**Expected behavior**
REGTEST coins shouldn't be displayed with fiat rates (like the TEST coins).

**Screenshots**
![image](https://user-images.githubusercontent.com/26326960/181716072-6cf9f407-b9e8-415a-8eb2-30bbd8dcddcc.png)

**Comment by szymonlesisz** [comment]
i think its very useful to have it on regtest to be able to test fiat > crypto calculation.
regtest is not available by default and i guess noone will be confused to have it here :)

**Comment by marekrjpolak** [comment]
Ok, but I'll continue to struggle with the false feeling of richness.
