### ISSUE TITLE
Application log croped when copied directly from Suite

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#5877]
**Describe the bug**
There is big discrepancy between copied and exported log at same time from same Suite.
See screenshots, looks like log copied to clipboard is omitted after 3000 lines.
I remember this issue since really old but had no idea that GitHub issue was never created.

**Steps to reproduce:**
1. Navigate to Suite settings
2. Copy and download Application log
3. Compare

**Info:**
 - Suite version: web 22.8.0 (2e9235b143059eb370a904d0047f587e78d40f72)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Screenshots:**
<img width="169" alt="image" src="https://user-images.githubusercontent.com/31506317/181720875-44ebd72b-8e56-437b-8578-d19b4503388f.png">
<img width="179" alt="image" src="https://user-images.githubusercontent.com/31506317/181720916-69e5dbc5-44f4-44c2-b4f6-632ec14d16bc.png">

**Comment by matejkriz** [comment]
clipboard limit is a system thing, there is nothing how could we solve it on our side so we just removed the COPY TO CLIPBOARD button for now

**Comment by STew790** [comment]
**QA OK**

Log correctly doesn't show the option to COPY TO CLIPBOARD.

![image](https://user-images.githubusercontent.com/48477147/182366203-dbb95309-85df-4baa-bf34-2320b4b52455.png)

**Info:**
 - Suite version: web 22.8.0 (fd645811b74416625bdb49a8140d9fbfbe2aa428)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
