### ISSUE TITLE
Discovery error with input from Litecoin MimbleWimble

### ISSUE THREAD

**Issue by cryptomar1o** [trezor/trezor-suite#5882]
**Describe the bug**
When the Litecoin account receive an LTC MWEB (MimbleWimble) input, the account does not load with a discovery error
Discovery error
Accounts were not loaded properly
Litecoin: Invalid address, decoded address is of unknown size

**Info:**
-   Suite Version: desktop 22.7.3 ([8eddb2a](https://github.com/trezor/trezor-suite/commit/8eddb2accd31c78577f276df2e9ecf773d2c3c17))
-   Bridge: bridge 2.0.31
-   Firmware Version: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)

**How to reproduce**
Get a MWEB input to the Litecoin account

**Expected behavior**
Trezor Suite shows the balance and the transaction history

**Screenshots**
<img width="627" alt="Screenshot 2022-07-28 at 10 39 07 PM" src="https://user-images.githubusercontent.com/52966597/181763931-11c3fdc3-e698-4c8a-9146-80d985844ee4.png">

**Comment by sime** [comment]
@cryptomar1o Any issues with blockbook when input the xpub into the search bar? https://ltc1.trezor.io/

**Comment by 465y79h8ugdsnuji** [comment]
No issue with using the xpub on blockbook, it shows an MWEB pegout balance correctly.

It may be worth noting that MWEB pegout transactions show correctly when viewed within a block or via xpub, but if you attempt to search for/access the transaction directly it returns an error.

I replicated the issue, and when the [transaction](https://ltc1.trezor.io/tx/b2d8bda5926ecfc92ea3f06a574611fbb42a1d5355f702895cc460c2fe56121f) is searched directly https://ltc1.trezor.io/ shows:

```
Error
Transaction 'b2d8bda5926ecfc92ea3f06a574611fbb42a1d5355f702895cc460c2fe56121f' not found (MsgTx.BtcDecode: witness tx but flag byte is 08)
```

The same transaction is shown without issue for the block/xpub views. Here's the block view: https://ltc1.trezor.io/block/2306873?page=10

**Comment by sime** [comment]
Blockbook has been updated, and no longer returns an error.

Does the issue persist in suite?

**Comment by cryptomar1o** [comment]
The user confirmed that after the blockbook update, he is now able to see the whole balance including the transaction history.

Issue is resolved.

**Comment by bosomt** [comment]
Moving from `Needs QA` to `Approved` section.
There is no way that this can be tested on our side.
