### ISSUE TITLE
Separate env utils to package

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#5889]
We can create universal package `@trezor/env-utils` from file `packages/suite/src/utils/suite/env.ts`. Most of functions here doesn't depend on anything and that few that depends could be reworked to not depend or we don't need to separate them.

Package should look somehow like this:
**`platformSpecificEnvUtils.ts`** - this file will contain only function like `getScreenWidth`, `getPlatform`... Which are using  "low level" API like `window`, `process` etc.
**`platformSpecificEnvUtils.native.ts`** - version same file that will be used in React Native env, can be added later by mobile team
**`envUtils.ts`** - file use functions from `platformSpecificEnvUtils` to construct higher level functions like `getOsName`, `isLinux` etc. This file should not use any platform specific API like `window` or `process`, all these APIs must be encapsulated in `platformSpecificEnvUtils`

I believe this utils, if done right could be useful also for @mroz22 ?

**Comment by mroz22** [comment]
Yes, sounds good to me. Lets do it.

**Comment by Nodonisko** [comment]
Package was already created by @mroz22 so now it's only about adding RN part.

**Comment by Nodonisko** [comment]
Closing in favor of #6167
