### ISSUE TITLE
Firmware update Trezor 1 Ver 1.6.2 to 1.11.1

### ISSUE THREAD

**Issue by ngodima** [trezor/trezor-suite#5892]
The device shows a fingerprint to confirm.   I do not see a fingerprint on the Web page that has stopped at 92%.
I Really do not need this hassle
What do I do now???????????????????????????????????

![image](https://user-images.githubusercontent.com/94204126/182035921-2f5e7de5-acc9-43b2-ab37-ff4841987b90.png)

**Comment by ngodima** [comment]
Chrome 103.0.5060.114
Windows 10  PC

**Comment by hynek-jina** [comment]
@ngodima 
Thank you, but it is quite difficult to reproduce your issue. Please contact https://trezor.io/support/ for help

**Comment by sime** [comment]
Related to #4224 ?

**Comment by ngodima** [comment]
I think the problem might be that I had pop ups turned off.   I lost the
firmware on the device and then got it reinstalled as a new configuration
then redid the phrases
Thanks
