### ISSUE TITLE
connect-web: importing types into third party apps

### ISSUE THREAD

**Issue by gabrielKerekes** [trezor/trezor-suite#5894]
While integrating Connect v9 into [Cardano HW CLI](https://github.com/vacuumlabs/cardano-hw-cli/pull/127) and NuFi (closed source), we couldn't figure out a way to import and use the Connect types in a nice, simple way.

_Note: I originally wrote [comments in the Cardano Babbage PR](https://github.com/trezor/trezor-suite/pull/5752#issuecomment-1195354023), but as that was already closed, it's probably gone unnoticed._

Previously, before Connect was updated and moved to this repo, we used `import * as TrezorTypes from 'trezor-connect'`to import Cardano types from Connect. Then we were able to do e.g. `TrezorTypes.CardanoSignedTxData` to get the `CardanoSignedTxData` type (or `CardanoSignedTxData`, `CardanoAssetGroup`, ...).

Currently the only way I was able to get to the type was to do `import * as TrezorTxTypes from '@trezor/connect/lib/types/api/cardanoSignTransaction'` and then `TrezoTxTypes.CardanoInput` to get to the underlying types  (which then also means I should probably include `@trezor/connect` as a dependency in addition to `@trezor/connect-web`).

Also to access protobuf messages (mainly enums) e.g. for the `CardanoTxSigningMode` it was possible to do `TrezorTypes.CardanoTxSigningMode.ORDINARY_TRANSACTION`. Now we need to access the enum via the `PROTO` object in `TrezorTypes` (`TrezorTypes` comes from the `import * as TrezorTypes` mentioned above) i.e. `TrezorTypes.PROTO.CardanoTxSigningMode.ORDINARY_TRANSACTION`.

Is there currently another way to import these types? Or could the types perhaps be made more accessible ? 🙏 

We use the types when building the `cardanoSignTransaction` request. Replacing [this line](https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/types/index.ts#L13) with `export * from './api/cardanoSignTransaction';` solves the problem, but I'm not sure it's desirable. Perhaps `export * as Cardano from ...` might be ok? 🤷

**Comment by mroz22** [comment]
Hi, thanks for your feedback. We should do something about it. I think we exported only tezor-connect types that are used somewhere in trezor-suite monorepo and we for unknown reason forgot that there might be other projects implementing those types :man_shrugging:

**Comment by gabrielKerekes** [comment]
@mroz22 Now it is much better, thank you 👍
