### ISSUE TITLE
Format input numbers

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5928]
- [x] ignore all non-numeric symbols except `,` and `.`
- [x] first used `,` or `.` interpret as a decimal separator
- [x] ignore other usage of `,` or `.`
- [x] format number according the language settings. For example:
    - english → `1,234.56` 
    - czech → `1 234,56`
    - spanish → `1.234,56`
- [x] https://github.com/trezor/trezor-suite/issues/5272
- [x] review validation messages

**Comment by dahaca** [comment]
@hynek-jina @sime There is a problem with the `undo` operation in the new `NumberInput` component. It is possible to implement an undo history manually but for now to avoid further complicating code I have disabled `cmd+z` altogether. What are your thoughts on that? :)

**Comment by hynek-jina** [comment]
I've probably never used `undo` in the input field.. Do we have any idea if people use that?

**Comment by Hannsek** [comment]
I do use it all the time. My opinion is that if it is a quick fix for a short period of time, then it is ok. If it is for longterm then NOK. But this is on @sime.

**Comment by sime** [comment]
QA: Please review #7310 as it is somewhat related.

**Comment by sime** [comment]
@dahaca @komret Pasting `.001` results in a validation error
<img width="799" alt="Screenshot 2023-04-05 at 6 59 19" src="https://user-images.githubusercontent.com/216917/229985052-02a47efe-0b20-462b-b622-f5815891e78c.png">

Pasting `.0010` doesn't auto-prepend `0` with validation error
<img width="797" alt="Screenshot 2023-04-05 at 7 02 30" src="https://user-images.githubusercontent.com/216917/229985582-c43bab49-63f7-46e0-8c38-1b36aa8fe969.png">

Typing ",001" returns a validation error

https://user-images.githubusercontent.com/216917/229986403-5510da9a-8cda-4e98-b055-fdc5e1f29f12.mp4

**Comment by bosomt** [comment]
@sime thank you for reporting ;) i just came here to report it :) happened multiple times to **QA** dept



![Image](https://user-images.githubusercontent.com/31506317/230023357-76a4e9f0-0f4e-41b4-9a09-8c5b908999dc.png)

**Comment by dahaca** [comment]
> `.001` results in a validation error

@sime added a commit to the PR https://github.com/trezor/trezor-suite/pull/7995

**Comment by MatthewDavid1984** [comment]
(Testing on Suite version: desktop 23.4.1 (6c6a0e9979bb80b2d6592214684ea3638a532df8), Linux)

Seems to be an issue in Spanish. Entering $123 in the USD field in English or other languages gives the correct corresponding amount of BTC:
![image](https://user-images.githubusercontent.com/121948710/231721662-ff51dbe7-3206-4a48-9652-d07bfeb1ac72.png)

But not in Spanish, it's off by a several decimal places:
![image](https://user-images.githubusercontent.com/121948710/231722348-49e37240-bb15-463c-a90e-5dc39c9fcef6.png)

Same if editing the BTC field:
![image](https://user-images.githubusercontent.com/121948710/231723237-10c0ff7a-68e7-45c3-9bc7-2e506d9e2ca2.png)

Also, the comma and period are not perfectly interchangeable, in this situation I can enter  a period:
![image](https://user-images.githubusercontent.com/121948710/231724375-90413f24-60f7-42a9-b4a8-e59604b0346b.png)
![image](https://user-images.githubusercontent.com/121948710/231724499-044f9761-67c8-4c43-84ff-b5e0f266619b.png)

But a comma input is ignored. I can enter a comma only at the end of the number, after the 3.

Also, entering a period at the beginning of a number already containing a decimal clears the field.
![image](https://user-images.githubusercontent.com/121948710/231725643-a8504ce9-64aa-42f2-9754-f8e5b88d7aa1.png)
![image](https://user-images.githubusercontent.com/121948710/231726090-5128ea0a-feb1-4f08-870d-5fbfb1999956.png)

A comma input is ignored in the same situation.

**Comment by MatthewDavid1984** [comment]
Entering a leading 0 here clears the fiat field and triggers the "maximum decimals" message

![Image](https://user-images.githubusercontent.com/121948710/231764532-5ba92a9f-bedc-477c-bb1c-e0a6e39b7244.png)
![Image](https://user-images.githubusercontent.com/121948710/231764533-57a3e139-a91b-4195-ba97-e47961004f57.png)

Also I can put leading zeroes in the fiat field as long as a decimal is present, then deleting the decimal point deletes the leading zeroes

![Image](https://user-images.githubusercontent.com/121948710/231764531-bc41f303-7a5d-4281-acd7-de9618edf557.png)
![Image](https://user-images.githubusercontent.com/121948710/231764534-94a349f1-f6f8-477d-98f0-b8e0b85a4eeb.png)

I am unsure of the expected behavior in both cases.

**Comment by matejkriz** [comment]
reverted from 23.4, moved to 23.5

**Comment by bosomt** [comment]
**QA OK**

follow up here https://github.com/trezor/trezor-suite/issues/8067#issuecomment-1531610461

**Info:**
 - Suite version: web 23.5.0 (d62a7cbda12f92e9d168a3053eb0ff8c195daacd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
