### ISSUE TITLE
Broken trade section by Satoshi units

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5930]
- [ ] When you are in sats and press “All” then it inserts an amount in sats, however the logic of the form is in BTC, so it converts your sats to billions of dollars
- [ ] When you are in sats and you input any amount in the left field you see an error notification
- [ ] When you are in sats it shows the fee in sats, however the form is still in BTC

![image](https://user-images.githubusercontent.com/26002916/182804504-4d35c273-8ffc-4cd5-a207-7157a658d108.png)

**Comment by matejkriz** [comment]
This should be fixed by https://github.com/trezor/trezor-suite/issues/5541

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.9.1 (32cfc5c61076fd9b38389efb1ec2aee2cc0b94f3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.9.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31
