### ISSUE TITLE
Missing bubbles in balance graph in Accounts section

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#5937]
**Describe the bug**
Missing bubbles in balance graph in Accounts section.
See two screenshots. Dashboard contains bubbles and Account section is missing them.

**Steps to reproduce:**
1. Load accounts with transaction history
2. Navigate to Dashboard
3. Navigate to Accounts 
4. Compare graphs

**Info:**
 - Suite version: desktop 22.8.1 (503b472935dec8a9c07aac5eef5ba43f86780a38)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 Bitcoin-only (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Screenshots:**
_Accounts_
<img width="755" alt="Screenshot 2022-08-04 at 18 15 50" src="https://user-images.githubusercontent.com/31506317/182898275-4a5c931b-7125-4abd-9631-97f48ae477e4.png">
_Dashboard_
<img width="1029" alt="Screenshot 2022-08-04 at 18 15 56" src="https://user-images.githubusercontent.com/31506317/182898297-ede44343-31c8-4d19-a76a-5967571249af.png">

**Comment by STew790** [comment]
**QA OK**
Bubbles are correctly shown again in Accounts section.



**Info:**
 - Suite version: web 22.9.0 (2cbf18207db1f174d7fe9e08cc937039c09c6064)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
