### ISSUE TITLE
Remove specs from docs

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#5961]
I think the [specs](https://docs.trezor.io/trezor-suite/specs/index.html) section should not be a part of the public docs. It is irrelevant to users and third-party developers, it mentions Trezor employees and internal systems, links to Notion. Moreover, it is outdated (looks like the two features are already implemented). Before deleting the section, is there any info worth preserving/updating and moving to Notion?

**Comment by akssshh** [comment]
hey!! Can you assign this to me?

**Comment by komret** [comment]
@gogoiakash2311 Feel free to submit a PR deleting the files and the links from SUMMARY.md. We will merge it once it is decided where (if) to move it.

**Comment by akssshh** [comment]
Should i remove the links of the specs section from SUMMARY.md

**Comment by komret** [comment]
Yes, the whole section.

**Comment by akssshh** [comment]
Okay..soon i'll submit a PR

**Comment by akssshh** [comment]
Hey! I'm new to open source and I have never contributed to any open source project. This is my first time and I'm unable to create a new branch to make new commits. Is the develop branch, the main branch of this project? Please help, I don't want to lose this opportunity of contributing to a project.

**Comment by komret** [comment]
I can't provide a detailed guidance on Git here, sorry. Take your time and learn to use Git before you submit a pull request. All you need to do is to clone the repository, create a new branch based on develop, push it and create a pull request here on Github.

**Comment by akssshh** [comment]
yeah thanks!! I submitted two pull requests. Hope it got merged.

**Comment by gogoiakash2311** [comment]
Did i did anything wrong?

**Comment by akssshh** [comment]
Did I do anything wrong?

**Comment by komret** [comment]
Probably yes, I can't see any pull requests nor branches. Please study Git before posting here.

**Comment by akssshh** [comment]
Heyy! I just submitted a pull request regarding the issue mentioned above.
