### ISSUE TITLE
Suite app is not installed on next launch when this option is chosen in the autoupdate

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#5967]
**Describe the bug**
If I choose the option to install the update on next launch in the autoupdate modal, the Suite will just offer me the autoupdate again on next launch and not immediately install the new update.This was actually changed already in the 21.7.1 version, very probably here https://github.com/trezor/trezor-suite/commit/47bd2f7e8cfaa4455b252cdf68b5f01e7356756e (found by @tomasklim). In the terminal with debug tools flag, it shows:
`2022-08-09T09:23:14.092Z - INFO(auto-updater): Is configured to auto update after app quit? true`.

**Steps to reproduce:**
1. Install an older version of Suite (for example 22.6.5)
2. When I open it, I get offered an update to the newest version (22.7.3)
3. I choose the option to install update on next launch
4. On next launch, I get again an offer for the update (nonetheless I can install the new version as well)

**Info:**
 - Suite version: desktop 22.8.1 (4ddcf5c6b05fefda0425919434a936e534482a1e)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.1.1 Universal (revision 7af1d585)
 - Transport: bridge 2.0.31

**Expected result:**
Suite update is installed immediately on the next launch when this option is chosen.

**Actual result:**
Suite app is not installed on next launch when this option is chosen in the autoupdate

**Comment by tomasklim** [comment]
Another related bug:

If a user is using an unsigned app and it offers an official update. The auto-updater does not fail. It shows the "Restart and Install" button.
When he launches the app again, he is using an old unsigned version.

There is an error in logs but most users do not see it. 
```
2022-08-09T13:09:12.688Z - ERROR(auto-updater): An error happened: Error: Code signature at URL file:///Users/user/Library/Caches/io.trezor.TrezorSuite.ShipIt/update.o9VauiL/Trezor%20Suite.app/ did not pass validation: code failed to satisfy specified code requirement(s)
```

**Comment by STew790** [comment]
**QA OK**
More info in PR https://github.com/trezor/trezor-suite/pull/5969
