### ISSUE TITLE
[connect] Passphrase entry on Trezor Connect confusing for standard wallet users

### ISSUE THREAD

**Issue by typercampbell** [trezor/trezor-suite#5975]
### Description
When users working with third party applications do not have BIP39 passphrases turned off in their device settings, they face the passphrase entry page when connecting their device. 

Users—even advanced users—sometimes unintentionally/mistakenly enter something into this prompt (i.e. their device PIN), which activates an entirely new key. The calls to action on the page do not make it clear that they can continue without a passphrase. For our clients at Unchained, this introduces a range of issues spanning from:

- Key fingerprint mismatching when conducting a best practice key check against a non-passphrase enabled key that is already being used in a multisig wallet (less severe)

to 

- Adding a new key to contribute to a multisig wallet where a passphrase has been **mistakenly** activated (more severe)

### Proposed Solution

The display can mirror the styles used already within the Trezor Suite. This introduces a familiar look, feel, and flow to the user and directs the user to a more common default call to action of Standard wallet. The goal is to not expose the user to a screen that invites them to input text, which can easily lead to the trouble scenarios highlighted above. Showing the Standard wallet and then a drop-down to enter a hidden wallet passphrase would accomplish this (screenshot below)

Additionally, the device displays "Please type your passphrase on the connected host" with **no** information about what to do if you're not using a passphrase. 

![Trezor_Connect](https://user-images.githubusercontent.com/57573735/183983609-4e2fc163-34bc-4464-acba-9bee12a2062e.png)

Improvements outside the scope of Trezor Connect could include the option to disable a toggle for passphrases (hidden wallet) straight from the Standard wallet / Hidden wallet pop-up modal upon initial device setup.

**Comment by sime** [comment]
Hi @typercampbell we are working on this :) https://github.com/trezor/trezor-suite/issues/4880

Closing as duplicate.

**Comment by typercampbell** [comment]
Thank you! Apologies for not catching that, @sime

After working one-on-one with users, I believe that even displaying a text field for passphrase entry as Trezor Suite currently does leads users down an unintended path. A drop-down to then display the passphrase entry field would be a big improvement in this regard. I can comment over on #4880 as well!
