### ISSUE TITLE
Add account modal and "Find my account" button is overlapping on smaller screens and with testnets opened

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#5976]
**Describe the bug**
If I have a smaller screen or I change the Suites window size, the "Add account" modal and the "Find my account" button to add an account is overlapping through the modal as shown in the screenshot. I have to open the testnet coins as well.

**Steps to reproduce:**
1. Open Suite
2. Go to Accounts page
3. Click on the "+" to add an account
4. Click on "Activate more coins" and also click on the drop-down for testnet coins
5. The testnet coins and the "Find my account" button will overlap through the "Add account" modal

**Info:**
 - Suite version: desktop 22.8.1 (4ddcf5c6b05fefda0425919434a936e534482a1e)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.11.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Expected result:**
The coin selection and the "Find my account" button will remain in the "Add account" modal.

**Actual result:**
The tesnet coins and the "Find my account" button are overlapping through the "Add account" modal

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/183947094-e3311c5a-a343-4a13-88f6-768426198370.png)

**Comment by MiroslavProchazka** [comment]
@STew790 still present?

**Comment by STew790** [comment]
No, even if I make it as small as I can on my system, its OK. Closing.
