### ISSUE TITLE
Investigate APK size

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#5989]
Current APK size for Android is about 120 MB, that's a lot for nearly empty app and it's really annoying to even download it for every development version.

Ideas to be explored:

- [ ] Splitting APK per architecture (is it possible to use this with Firebase Distribution?)
- [ ] Use AAB instead of APK
- [ ] Remove unused font files

**Comment by bouchja1** [comment]
Notes:

- Firebase App distributon - AAB supported, but it is necessary to have Firebase app linked with Google Play’s internal app sharing service to process and I think that Google review is a necessary step before this. (https://firebase.google.com/docs/app-distribution/android/distribute-fastlane?apptype=aab). 

- Another ideas in `android/app/build.gradle`
Set `def enableProguardInReleaseBuilds = true` this would enable Progaurd to compress the Java Bytecode. This reduces the app size by a tad bit

- Set `def enableSeparateBuildPerCPUArchitecture = true` . Android devices support two major device artitectures armebi and x86. By default RN builds the native librariers for both these artitectures into the same apk

- buildTypes {
release {
    debuggable false
    minifyEnabled true
    shrinkResources true
    ...
}

- https://aglowiditsolutions.com/blog/how-to-reduce-react-native-app-size/

**Comment by Nodonisko** [comment]
Moving this out of sprint for now. In app stores we will use AAB which should more optimalized thank APK so resulting app size shouldn't be more than ~30 MB.

But there is some space for more improvements for sure.
