### ISSUE TITLE
Passphrase switch active even when device disconnected

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#5990]
**Describe the bug**
See screenshot passphrase switch in Settings/device section is  active even when device disconnected.
At lease looks active, it's not possible to turn off passphrase on disconnected device. 

**Steps to reproduce:**
1. Load device with hidden wallet
2. Remember wallet
3. Disconnect device
4. Navigate to Settings/Device section 
5. Observe Passphrase switch

**Info:**
 - Suite version: desktop 22.8.2 (58f4c5bf0804e02c05c0b85e020b6e452b419164)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.2 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Screenshots:**
<img width="1120" alt="Screenshot 2022-08-14 at 8 17 55" src="https://user-images.githubusercontent.com/31506317/184525131-eefad553-4ceb-4efe-9554-a2353489fe32.png">

**Comment by AdamSchinzel** [comment]
Right now we don't display it at all so it should be "fixed"

**Comment by bosomt** [comment]
**QA OK**

- passphrase switch is fixed
- TS only asks you to enable passphrase when you view account that is generated from passphrase

<img width="620" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/eebdcea1-e462-40d0-8173-ff85a7c58b12">

**Info:**
 - Suite version: desktop 23.9.1 (41a9c13bf28edf71fe629379288a5ad685f259d1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.9.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
