### ISSUE TITLE
Migrate suite blockchain redux stuff to common package

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#5991]

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.9.0 (104a72c66e936370b64ec9f02f3de32fcac6a6a6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: 
 - Transport: bridge 2.0.31
