### ISSUE TITLE
Device restart/reconnect not detected when update includes intermediary firmware

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6004]
**Describe the bug**
Device restart/reconnect not detected when update includes intermediary firmware.
I just tested upgrade to current firmware including intermediary firmware.
I was asked to reconnect device after intermediary FW was installed and new firmware was installed.
**But after final step device asked me to reconnect but Suite asked me to wait.**

**Steps to reproduce:**
1. Connect device with old firmware /used FW 1.5.1, BL 1.5.1/
2. Update to current firmware
3. Observe behavior

**Info:**
 - Suite version: desktop 22.8.2 (58f4c5bf0804e02c05c0b85e020b6e452b419164)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.2 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Screenshots:**

https://youtu.be/WzXMAwYi8rI

[trezor-suite-log-1660556857760.txt](https://github.com/trezor/trezor-suite/files/9336550/trezor-suite-log-1660556857760.txt)

![image](https://user-images.githubusercontent.com/31506317/184618074-65bdfd40-c865-4849-a4fc-b470c7627267.png)

**Comment by STew790** [comment]
**QA OK**
I tried to update:
1.6.3>1.12.1
1.8.0>1.12.1
In both cases I was able to continue without any issue:
![image](https://user-images.githubusercontent.com/48477147/225576635-100e9c51-3981-4fea-9f03-94573bfed860.png)

 **Info:**
 - Suite version: desktop 23.3.2 (2ab6b568e556d4eebd8c0d3bb04fa278bfe18506)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.2 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.12.1 Universal (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.32
