### ISSUE TITLE
Disabling custom blockbook server settings ignored

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6050]
**Describe the bug**
See screenshot and video.
When you disable custom blockbook backend and switch to default one Suite ignores it and keeps using custom one.
Even when you disable and enable again coin and perform discovery. 
Found it during testing of new backend version on staging.

**Steps to reproduce:**
1. Enable custom backend and perform discovery.
2. Disable custom backend.
3. Check backend address that Suite use.

**Info:**
 - Suite version: web 22.8.2 (58f4c5bf0804e02c05c0b85e020b6e452b419164)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Screenshots:**

https://youtu.be/iCMiEEDCZKU

<img width="710" alt="Screenshot 2022-08-19 at 19 22 31" src="https://user-images.githubusercontent.com/31506317/185674548-39cf2d6b-7877-400f-9ea2-34b5dcfa6832.png">

**Comment by hynek-jina** [comment]
@bosomt is it Dash specific?

**Comment by bosomt** [comment]
@hynek-jina no it's not DASH specific, i was able to reproduce it with LTC

<img width="741" alt="image" src="https://user-images.githubusercontent.com/31506317/185849148-c16bc2ef-6c2c-4927-949d-1fa2ee362601.png">

**Comment by bosomt** [comment]
and i was able to reproduce it in 22.9.0 app /i was not sure if its only web issue/

<img width="702" alt="image" src="https://user-images.githubusercontent.com/31506317/185849642-154b3bc0-897c-4410-bb7c-958a599b1ded.png">


**Info:**
 - Suite version: desktop 22.9.0 (2dbc5afb6ab668440d1be54baa738806472156c4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.9.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.0 (d738700d52e85cef51a003c069de4bb22f9e9125)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32
