### ISSUE TITLE
Disable shutdown/sleep while CoinJoining

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#6053]
https://www.notion.so/satoshilabs/d3c3fe72632c42fe93128a4857484b5e?v=b97cf771318d4b1fa19501a3b6df2e0b&p=7a0692d99c4446cb914cb94c8241ed0a&pm=s

**Comment by STew790** [comment]
**QA OK**
My laptop didn't suspend during the CJ process. :tada: 
**Info:**
 - Suite version: desktop 22.12.0 (d4d811a436c25fcf5c80768e6dbb93ad00a5c8b8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
