### ISSUE TITLE
Ethereum new Account with alternate derivation path?

### ISSUE THREAD

**Issue by stn021** [trezor/trezor-suite#6054]
Hello,
when I add a new etherum-account in trezor-suite it is derived from the next address within the same bip-39-account
So, first address is m/44'/60'/0'/0/0 , second address is m/44'/60'/0'/0/1 , third is m/44'/60'/0'/0/2 etc.

My ethereum-accounts are already organized by account.
So, first address is m/44'/60'/0'/0/0 , second is m/44'/60'/1'/0/0 , third is m/44'/60'/2'/0/0

How do I get trezor-suite to add new accounts in the second way instead of the first?

THX, regards, stn

**Info:**

-   Remembered Wallet: yes
-   Suite Version: app
-   Browser: none
-   OS: ubuntu 22.04
-   Bridge: --
-   Firmware Version: newest

**How to reproduce**

1. open trezor-suite
2. select ethereum
3. add new account, check address for its derivation path

**Expected behavior**
Be able to choose, which part of the path is altered when I add a new eth-account

**Comment by hynek-jina** [comment]
Hi @stn021 
You can add another account (if the first one has already received on at least one address), but only up to 10 accounts.
Organisation by accounts is not intended behaviour according the BIP-0032.

If you still need it, please use ie Electrum.
