### ISSUE TITLE
Replace Ropsten testnet with Goerli

### ISSUE THREAD

**Issue by merc1er** [trezor/trezor-suite#6072]
As the Ethereum Ropsten testnet is deprecated ([source](https://ethereum.org/en/developers/docs/networks/#ropsten)), it would be good to replace it (or mark it as deprecated in Suite) and add support for [Goerli](https://ethereum.org/en/developers/docs/networks/#goerli).

> Goerli is expected to be maintained long term as a proof-of-stake testnet.

**Comment by sime** [comment]
We have Goerli, funny thing is now the community says Goerli will be deprecated!

> Goerli (long-term support)
> Note: the Goerli testnet is deprecated and will be replaced by Holesovice in 2023. Please consider migrating your applications to Sepolia.

https://ethereum.org/en/developers/docs/networks/#ethereum-testnets
