### ISSUE TITLE
update https://connect.trezor.io/ frontpage

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#6081]
https://connect.trezor.io/ is pointing to old github repo. 

maybe we could have some static url in monorepo and just upload it there as part of release process?

**Comment by sime** [comment]
Currently, it's deployed from the `gh-pages` branch of the old repo. https://github.com/trezor/connect/blob/gh-pages/index.html

A redirect to the package README is the easiest solution. Not sure how often that page gets hits, if any curious people visit it, I'm not sure the README is enough.

**Comment by tsusanka** [comment]
We can also simply redirect somewhere, so we do not have to worry about deploying.. E.g. to this repo or to docs subfolder etc.

**Comment by mroz22** [comment]
done 🥇
