### ISSUE TITLE
No need of number 0 before decimal point

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#6085]
**Issue**
-e.g. `0.003` cannot be typed as `.003` in `Suite > Send > Amount` as the error message `Maximum 8 decimals allowed` (in BTC) appears

![image](https://user-images.githubusercontent.com/57008159/186336970-84cfb918-b0d8-471e-8b41-2d2546c01c41.png)

- _however, this behaviour is already allowed in `search field `in `transaction history`_

<img width="798" alt="image" src="https://user-images.githubusercontent.com/57008159/186336899-377e3299-9f95-4c6a-a4d9-56a18da84b2a.png">

**Improvements proposal**
- allow user to write small decimal values without 0 before decimal point

**Comment by hynek-jina** [comment]
Duplicity of https://github.com/trezor/trezor-suite/issues/5272
