### ISSUE TITLE
Cannot delete label

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#6099]
**Describe the bug**
When I have labelled the transaction and then I want to delete it, I cannot do that.

**Info:**

-   Remembered Wallet: no
-   Suite Version: app, 22.8.2
-   OS: macOS, version 12.5.1
-   Bridge: version
-   Firmware Version: T1, 1.11.2

**How to reproduce**

1. Go to 'Transaction history'
2. Click on 'Add label'
3. Type something into the text field
4. Confirm the label
5. Click on the label -> 'Edit label' -> delete the label
6. Confirm it

**Expected behavior**
Label should be deleted and address should be visible

**Comment by hynek-jina** [comment]
Duplicity of: https://github.com/trezor/trezor-suite/issues/5772
