### ISSUE TITLE
Distinguish CoinJoin state amounts

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6102]
CoinJoin amounts might appear in 3 states:
- `Not private` - UTXOs with anonymity bellow desired anonymity level
- `Anonymising` - UTXOs in process of anonymisation
- `Private` - Already anonymised UTXOs to desired anonymity level or higher

![Image](https://user-images.githubusercontent.com/26002916/186500034-b25f0a0e-c91d-430f-b3ba-d7fba8901717.png)

- `Anonymize` button leads to https://github.com/trezor/trezor-suite/issues/6101
- `Anonymising` amount is visible only if there are some funds in running CoinJoin

![Image](https://user-images.githubusercontent.com/26002916/186500982-fbad3c7a-86b2-41ee-a0ae-ea9a7d13ff99.jpg)

- `Anonymize` button disappears when are all funds anonymised to desired anonymity level

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.0 (3817fba23064e18ca9416a0ca0d726f50959576b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision fac4e2f157ca7d0c782b8a55175478e476ea7e28)
 - Transport: bridge 2.0.32
