### ISSUE TITLE
All MenuElements in Account AppNavigation visible during discovery

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#6109]
**Describe the bug**
All MenuElements (Overview, Account, Tokens, Stacking) in Account AppNavigation are visible during discovery even those invalid for current network (i.e. Stacking for BTC).

**Info:**

-   Remembered Wallet: both
-   Suite Version: app&web, 58f4c5b
-   Browser: all
-   OS: all
-   Bridge: all
-   Firmware Version: all

**How to reproduce**

1. Go to 'Accounts'
1. Click on '+ button to add account'
1. Add new account for currently disabled network
1. See account menu during discovery

**Expected behavior**
No irrelevant menu items should be visible during discovery (we could hide all or find a way to display only relevant from the very beginning).

**Screenshots**
![image](https://user-images.githubusercontent.com/3729633/186626719-0e998765-3781-40ac-acfc-baead68f1456.png)

**Comment by STew790** [comment]
**QA OK**
Only correct MenuElements are shown when adding a new account

**Info:**
 - Suite version: desktop 22.10.0 (1c1917c1f4fca65b408ea0abc35fc41b29f096b2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.10.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32
