### ISSUE TITLE
Anonymity level control

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6116]
User should be able to change the desired anonymity level for whole CoinJoin account.

![Image](https://user-images.githubusercontent.com/26002916/193046551-8a3e58a7-68c5-4244-81a8-78068de2fec6.png)

We assume discrete logarithmic scale from 1 to 100. However.

There are four anonymity areas:
| Level range | Description | Image |
| --- | --- | --- |
| 1 - 4 | bad | ![Image](https://user-images.githubusercontent.com/26002916/190383338-62829dba-c9fb-4173-9b91-931792b2614d.png) |
| 5 - 9 | medium | ![Image](https://user-images.githubusercontent.com/26002916/190383339-0a80e57b-f6af-46b4-ba64-f71b55ec83ca.png) |
| 10 - 19 | good | ![Image](https://user-images.githubusercontent.com/26002916/190383337-d8046369-3192-4422-9acf-dfaa47bf4b64.png) |
| 20 + | great |  ![Image](https://user-images.githubusercontent.com/26002916/190383340-86b3946f-5d92-45bc-9f3b-25643b80a413.png) |

No confirmation is required to change the desired anonymity level. Changes on slider are simultaneously visible in top right anonymity indicator.

**Comment by hynek-jina** [comment]
@matejkriz Please change the visible anonymity scale from `1-50` to `1-100`..
And remove the explaining tooltip. Thank you..

**Comment by bosomt** [comment]
Is it ok that we allow `1 in 1` mixing ?

It starts with status that all coins are already anonymized. 
With nothing to anonymize. See screenshot.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/31506317/198011548-c7394ef8-218a-496f-a362-e48730bc525b.png">

**Comment by hynek-jina** [comment]
There is nothing to be mixed if user select anonymity level `1 in 1`...
In future version user will probably not be able to change the anonymity level when is the CoinJoin running.

@bosomt Did you change the anonymity level during the active CoinJoin running? Or you were able to run a new one with having everything anonymized? (eventhough to level 1 only)

**Comment by bosomt** [comment]
I was able to start mixing `1 in 1`

This is what i saw when i changed it to `1 in 1` before i pressed `Anonymize` button.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/31506317/198015037-9723d0f6-0027-414e-a214-06a499b88a18.png">

**Comment by hynek-jina** [comment]
Thx.. I will create followup issue from that..

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.0 (d313a2da2cd5ff7c7dbe243a2c6d75d67643efb7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision fac4e2f157ca7d0c782b8a55175478e476ea7e28)
 - Transport: bridge 2.0.32
