### ISSUE TITLE
Signing popup

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6117]
When CoinJoin round reach critical phase modal blocking interaction appears on screen.

<img src="https://user-images.githubusercontent.com/45338719/195304427-577b52e9-d379-48fb-9a68-5c8ca4eb7774.png" width="400"/>

This phase might take up to `200 seconds`. But there are ideas how to lower this time to circa `60 seconds`

<details close>
<summary>If the CoinJoin round fails</summary>
<br/>

![Cancel Plaholder](https://user-images.githubusercontent.com/26002916/188896823-4478d5be-a19d-4173-9714-9e33d7552878.png)

</details>

<details close>
<summary>When user removes the Trezor in `Connection confirmation` or `Output registration` phase (won't be used in the MVP)</summary>
<br/>

<img src="https://user-images.githubusercontent.com/45338719/195878064-7dcd6024-029f-4580-86da-43231eed3ed3.png" width="400"/>

</details>

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.1 (8a8808d3c3fd752bde89507d50650bc4bac56647)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
