### ISSUE TITLE
Global CJ state indicator

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6119]
User can visit another section of Suite and still see the CJ progress.

![Image](https://user-images.githubusercontent.com/26002916/186675677-886081f6-1650-4d4a-9286-c7cf4e1c281a.png)

![Image](https://user-images.githubusercontent.com/26002916/186675698-fc4718bf-850e-4c28-94fd-76921e35e45b.png)
![Image](https://user-images.githubusercontent.com/26002916/186675699-78f8333f-4f92-40ae-8a74-caca9dcae121.png)

**Comment by bosomt** [comment]
**QA OK**

<img width="558" alt="image" src="https://user-images.githubusercontent.com/31506317/196695118-51b7b535-e5a1-4a48-a7fe-efb9b40a7d2d.png">

**Info:**
 - Suite version: desktop 22.11.0 (36300860837188169b1fd07986f1c5a87c701b3b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision eb182b923f39111d9307a25a86a49d395c6611b0)
 - Transport: bridge 2.0.32
