### ISSUE TITLE
Tor identities

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6128]
https://www.notion.so/satoshilabs/Suite-TOR-integration-for-CoinJoin-73b86a20ebe843379f743f20fa7772b3

**Steps**
- [x] https://github.com/trezor/trezor-suite/issues/5527
- [x] https://github.com/trezor/trezor-suite/issues/5845

**PRs**
- https://github.com/trezor/trezor-suite/pull/6017

**Comment by STew790** [comment]
Pre-requisities for CoinJoin, no QA needed.
