### ISSUE TITLE
Add buy CTA to brand new passphrased wallet - empty state

### ISSUE THREAD

**Issue by IvaFingerova** [trezor/trezor-suite#6144]
**Goal** - improve discoverability of Invity features throughout Suite UI
**What** - let's add a CTA "buy" (it is complementary to receive) to the screen
**How** - update the screen consistently as is the new empty account 

<details close>
<summary>Current state:</summary>
<br/>
<pre>

<img width="1545" alt="suite_passphrased_wallet_emptystate" src="https://user-images.githubusercontent.com/8152411/187196480-bb9d6efe-3582-4f1e-9ea7-614161bc72ee.png">

</pre></details>

<details Open>
<summary>Desired state:</summary>
<br/>
<pre>

![Empty account](https://user-images.githubusercontent.com/26002916/187208337-2e130bdf-b252-4bfc-b2b8-861a25123d96.png)

</pre></details>

If the exact design needs to be done - I'll need designer's allocation - lemme know please :)
Díkíčko in advance

**Comment by yanascz** [comment]
@hynek-jina, it seems to be already implemented. What am I missing?
![image](https://user-images.githubusercontent.com/37251117/193843064-b5e5a973-cccb-4749-a223-c639df25d47a.png)

**Comment by hynek-jina** [comment]
OK, so let's close the issue...

**Comment by bosomt** [comment]
**QA OK**

**Comment by IvaFingerova** [comment]
This task isn't done :( 
This is the expected future status (for better clarification created a collage)
![hidden_wallet_future_status](https://user-images.githubusercontent.com/8152411/195308589-aa316238-cac2-4ce0-a7b4-3f835cd0900a.png)

**Comment by IvaFingerova** [comment]
This task isn't done :( 
This is the expected future status (for better clarification created a collage)
![hidden_wallet_future_status](https://user-images.githubusercontent.com/8152411/195306386-e3c722a0-eba0-4cf4-959a-44de28be5fe1.png)

**Comment by sime** [comment]
The below screenshot represents the current state.

![Screenshot 2022-10-12 at 17 03 13](https://user-images.githubusercontent.com/216917/195378688-28ba9e82-5179-40f7-8b24-7454b5e3cfed.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.11.0 (3f49b385ca493de6a84884e414c998c9a424ae71)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.11.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32
