### ISSUE TITLE
Rephrase dust limit validation message

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#6154]
**Describe the bug**
When the user attempts to send an amount equal to dust limit, validation message says they are below dust limit.

**How to reproduce**
Try to send 546 sats from a bitcoin account.

**Expected behavior**
Either the message should change or the transaction should be allowed.

**Screenshots**
![Screenshot 2022-08-30 at 19 04 23](https://user-images.githubusercontent.com/42465546/187497473-3c6b25ab-385b-43b2-b497-46753c32a9f3.png)

**Comment by hynek-jina** [comment]
@b-irving What about simply `Amount must be greater than dust limit (546 sat)`?

**Comment by b-irving** [comment]
@hynek-jina sounds good to me, but just add the definite article i.e. **the** dust limit

**Comment by STew790** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/48477147/189107413-97186fcc-f14b-4e10-a1a7-08e271bde03f.png)

**Info:**
 - Suite version: web 22.9.1 (32cfc5c61076fd9b38389efb1ec2aee2cc0b94f3)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32
