### ISSUE TITLE
update 'Learn more' links

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#6158]
**1.**
When going through Advanced recovery, there's a link that reads `Learn how to enter letters`. It leads to the outdated Wiki manual. Please update the link to https://wiki.trezor.io/Advanced_Recovery_(Trezor_Model_One_only)

<details>
  <summary>screenshot</summary>

![image (10)](https://user-images.githubusercontent.com/75733878/187625570-94ca9ab8-0735-4247-96d1-379fde282c97.png)

</details>

**2.**
In `Settings > device > wallet backup > check backup` the `Learn more` link goes to the outdated article. Please change it to https://wiki.trezor.io/Check_your_seed_(Dry-run_recovery)

<details>
  <summary>screenshot</summary>

![image (11)](https://user-images.githubusercontent.com/75733878/187626112-038b603b-7108-4a63-868a-f93a173e339b.png)

</details>

**Comment by jerechinsky** [comment]
IMO, this is a high-priority issue. @hynek-jina, could you please find someone to do it?

**Comment by mroz22** [comment]
https://github.com/trezor/trezor-suite/blob/develop/packages/urls/src/urls.ts#L47

and 

https://github.com/trezor/trezor-suite/blob/develop/packages/urls/src/urls.ts#L29

**Comment by STew790** [comment]
**QA OK**
Both links are now correct.

**Info:**
 - Suite version: web 22.9.0 (85accd0021e0a6e7e56e8e19aa0a5b27c3c01a83)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.11.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.32
