### ISSUE TITLE
Blockchain explorer should not open on an onion address by default

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#6166]
**Describe the bug**
When Tor is enabled but onion links are not, transaction detail attempts to open blockchain explorer on an onion address.

**How to reproduce**
Open transaction detail in history and click the link to blockchain explorer.

**Expected behavior**
It should lead to a _trezor.io_ address as it does when Tor is off.

**Screenshots**
![Screenshot 2022-08-31 at 18 20 33](https://user-images.githubusercontent.com/42465546/187730636-d8c244fa-859f-4d00-82db-0449b5359efe.png)

**Comment by hynek-jina** [comment]
This behaviour should react on selection in settings:
<img width="785" alt="Snímek obrazovky 2022-09-02 v 7 57 59" src="https://user-images.githubusercontent.com/26002916/188077410-0fc392b6-78bd-4ca7-897d-327c93b6002b.png">

**Comment by bosomt** [comment]
@hynek-jina yes it should, but it's broken at least one year https://github.com/trezor/trezor-suite/issues/4508

**Comment by matejkriz** [comment]
close in favor  of https://github.com/trezor/trezor-suite/issues/4508

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.1.0 (9fe19dcb15c69f22a65368e3e83eb029c1d5863d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
