### ISSUE TITLE
Different sha256sum for Trezor Suite v22.8.2 (suite.trezor.io vs github.com)

### ISSUE THREAD

**Issue by ekzyis** [trezor/trezor-suite#6177]
**Describe the bug**

Hello, I updated Trezor Suite today using the automatic updater inside Trezor Suite.

Out of curiosity, I manually verified the downloaded app image. I therefore downloaded the signature from https://suite.trezor.io/web/static/desktop/Trezor-Suite-22.8.2-linux-x86_64.AppImage.asc

However, the signature does not match the downloaded AppImage:

```
$ gpg --verify Trezor-Suite-22.8.2-linux-x86_64.AppImage.asc
gpg: assuming signed data in 'Trezor-Suite-22.8.2-linux-x86_64.AppImage'
gpg: Signature made Fr 12 Aug 2022 13:23:40 CEST
gpg:                using RSA key EB483B26B078A4AA1B6F425EE21B6950A2ECB65C
gpg: BAD signature from "SatoshiLabs 2021 Signing Key" [unknown]
```

I then noticed that the 22.8.2 release in Github has the correct signature and that suite.trezor.io provides a "different" Trezor Suite v22.8.2 than the release on github.com:

```
$ sha256sum suite.trezor.io/Trezor-Suite-22.8.2-linux-x86_64.AppImage*
16dc1bd21155dc61984a54b70b5b7863ff27f9d8084d8af5789240e76cc2057d  suite.trezor.io/Trezor-Suite-22.8.2-linux-x86_64.AppImage
6496736451bcbf7187bc0be8bf5736ab344aa2d3d336f20af9b9631be90e1ae7  suite.trezor.io/Trezor-Suite-22.8.2-linux-x86_64.AppImage.asc
$ sha256sum github.com/Trezor-Suite-22.8.2-linux-x86_64.AppImage*
42bd015787a293bb12bf5b1caed05fd4571665a898069f1c27eb8b33d7e31a01  github.com/Trezor-Suite-22.8.2-linux-x86_64.AppImage
4f6b6c8291149b4e52ea572dbc5a4ca84e152b6a720391cdf71547fad399c1b7  github.com/Trezor-Suite-22.8.2-linux-x86_64.AppImage.asc
```

Why is that?

**How to reproduce**

1. Download app image from suite.trezor.io: https://suite.trezor.io/web/static/desktop/Trezor-Suite-22.8.2-linux-x86_64.AppImage
1. Download app image from github.com: https://github.com/trezor/trezor-suite/releases/download/v22.8.2/Trezor-Suite-22.8.2-linux-x86_64.AppImage
1. Compare `sha256sum`

**Expected behavior**
`sha256sum` is the same for both downloads since both downloads are about v22.8.2

**Comment by ekzyis** [comment]
I created this ticket because I got quite confused and alerted when I received the first bad signature. I thought there is something wrong with my Trezor Suite and I got hacked or something.

Only after noticing that the automatic update essentially downloads from github.com instead of suite.trezor.io I calmed down.

But now I don't know what the difference between these files are (even though they are about the same version) and can't decide which one to use. So I am asking for some clarification here regarding this

**Comment by vdovhanych** [comment]
Hi there, thank you for raising this question. It's something we're aware of for this release.
 
The release was published too soon on GitHub, and the release needed to be redeployed to GitHub from the ci. 
The builds were signed at different times, creating this mismatch in the hash and signatures. The issue will be resolved by the next release and is something we will be making sure won't happen in the future. Both builds will be redeployed in case we need to remove the release in the future. 
As for the apps and where to download them from, it doesn't matter, as both sources provide identical builds.

**Comment by ekzyis** [comment]
Ah okay, makes sense, thanks for clarifying :+1:
