### ISSUE TITLE
Application log improvements - devices

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#6178]
- Add session id and instance id to the Application log (should be hideable by switch)
  - to find errors in sentry/analytics
- Add info about devices into static info
  - model, firmware, firmware revision, firmware type, bootloader, bootloader hash
- Add app start time

**Comment by STew790** [comment]
**QA OK**
Improved log:
![image](https://user-images.githubusercontent.com/48477147/188885986-9c022800-6891-4942-88b3-bad9a4e09295.png)
![image](https://user-images.githubusercontent.com/48477147/188886137-6c8b772c-b06a-4194-adc9-f938142937b2.png)
switch hides IDs:
![image](https://user-images.githubusercontent.com/48477147/188886605-f33740e2-35f1-46f0-99b8-a5013fa52d84.png)
device in BL mode:
![image](https://user-images.githubusercontent.com/48477147/188886202-bf2ecb90-b5b0-4c71-a91d-53a0bcca8581.png)
normal device:
![image](https://user-images.githubusercontent.com/48477147/188886298-665f4f8a-d21d-4aed-8caf-5dda893feefd.png)
**Info:**
 - Suite version: web 22.9.0 (8c3b6ab7944789b3cfed09db654de8b9fbd59469)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32
