### ISSUE TITLE
Different Hashes for binaries on github vs Trezor suite site

### ISSUE THREAD

**Issue by deandunbar** [trezor/trezor-suite#6181]
**Describe the bug**
There are different files on the Trezor site vs on the github releases tab. Is this expected behavior due to separate build processes? 

They both use the same signing key but have different hashes and different signature files. Why are there different binaries of the same files on github vs on the trezor site for the same version? 

**Info:**

Downloaded file from trezor site: https://suite.trezor.io/web/static/desktop/Trezor-Suite-22.8.2-mac-x64.dmg
sha256sum Trezor-Suite-22.8.2-mac-x64.dmg
a8a34656713cd849881fa1e902bc816320187ad347e764ac50279f1cb4a0d722  Trezor-Suite-22.8.2-mac-x64.dmg

Downloaded file from github: https://github.com/trezor/trezor-suite/releases/download/v22.8.2/Trezor-Suite-22.8.2-mac-x64.dmg
sha256sum Trezor-Suite-22.8.2-mac-x64.dmg
c27e309eb47c8ab1bd16d044f5ecb5014b187e1f1ddac2b9f8742888a58c4450  Trezor-Suite-22.8.2-mac-x64.dmg

The hashes for linux are also different. 

from github: https://github.com/trezor/trezor-suite/releases/download/v22.8.2/Trezor-Suite-22.8.2-linux-x86_64.AppImage
sha256sum Trezor-Suite-22.8.2-linux-x86_64.AppImage
42bd015787a293bb12bf5b1caed05fd4571665a898069f1c27eb8b33d7e31a01  Trezor-Suite-22.8.2-linux-x86_64.AppImage

from trezor suite site: https://suite.trezor.io/web/static/desktop/Trezor-Suite-22.8.2-linux-x86_64.AppImage
sha256sum Trezor-Suite-22.8.2-linux-x86_64.AppImage
16dc1bd21155dc61984a54b70b5b7863ff27f9d8084d8af5789240e76cc2057d  Trezor-Suite-22.8.2-linux-x86_64.AppImage

There is a lot of supply chain attacks and clarity on how binaries are signed could help alleviate some of that risk. 

Thank you!

**Comment by vdovhanych** [comment]
Hi, thank you for raising this question. This is something we are aware of for this release. For more information, please take a look here https://github.com/trezor/trezor-suite/issues/6177
