### ISSUE TITLE
Data Analytics: Non-zero accounts

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#6185]
We want to know which accounts have non-zero balance. Best would be to track this when discovery of all accounts is completed (similar to event `account/status`) as a new event (e.g. `non-zero-accounts/status`).

**Comment by bosomt** [comment]
**QA OK**


`
GET | https://data.trezor.io/suite/log/web/develop.log?c_v=1.23&c_type=accounts/non-zero-balance&c_commit=50395d7cf87e0f379a7ec538f394ed61463f8112&c_instance_id=SweGEwnKa8&c_session_id=RRlTQw3HVz&c_timestamp=1662543553276&btc_normal=2&btc_taproot=1
`

**Info:**
 - Suite version: web 22.9.0 (50395d7cf87e0f379a7ec538f394ed61463f8112)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31
