### ISSUE TITLE
Data Analytics: URI handler

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#6187]
We want to know if/when user used URI handler for given coin. 
In future we might add information about parameters which were prefilled (e.g. amount, address, ...).

**Comment by tomasklim** [comment]
Right now we are tracking analytics only from renderer so I can only track coin and if amount is available. Address is always available (in renderer, does not need to be available in Electron `bitcoin:` is valid method how to start app).

**Comment by bosomt** [comment]
**QA OK**



![Image](https://user-images.githubusercontent.com/31506317/211016678-aec00ba2-73ef-43d4-9d13-d2b143968409.png)

**Info:**
 - Suite version: desktop 23.2.0 (aeb1abfe2b1587e79dde501d1cac6f41f0cd4952)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
