### ISSUE TITLE
Transaction history with multiple CJ rounds

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6211]
**Transaction history** 
![Transaction history](https://user-images.githubusercontent.com/26002916/193045946-6a5f7e00-c2d5-4680-bcaa-e5f5a27e4ebe.png)

**Transaction detail** 
![CJ transaction history](https://user-images.githubusercontent.com/26002916/188883140-74c51f9d-8085-4285-b064-8af3fb4980c4.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.1 (73ccf723353e0575a64f58b2f5775d20f072311f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
