### ISSUE TITLE
Manual settings for CJ bundle

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6216]
Following issue after https://github.com/trezor/trezor-suite/issues/6101

![Custom settings](https://user-images.githubusercontent.com/26002916/188893532-23646704-06bd-4138-93f0-c44cdd1b4524.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.0 (54da46e34ad128b493cc1f43112dd9ebc84434e2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision fac4e2f157ca7d0c782b8a55175478e476ea7e28)
 - Transport: bridge 2.0.32
