### ISSUE TITLE
CoinJoin empty account

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6217]
![CJ empty account](https://user-images.githubusercontent.com/26002916/188894221-86aa9508-2a8e-45f7-803f-de9b800c2dd2.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.0 (d313a2da2cd5ff7c7dbe243a2c6d75d67643efb7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Bitcoin-only (revision fac4e2f157ca7d0c782b8a55175478e476ea7e28)
 - Transport: bridge 2.0.32
