### ISSUE TITLE
CoinJoin progress and it's controls

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6219]
![CJ - progress bar](https://user-images.githubusercontent.com/26002916/188895743-fa4e9db4-7497-4feb-afdb-33da7b1af41b.png)

On hover to three dots show:
![pause or cancel cj](https://user-images.githubusercontent.com/26002916/188895884-deabea3a-e6c9-41ea-a3c7-61f0bc3e3d57.png)

Show blocking modal if user wants to cancel the CoinJoin
![Cancel Plaholder](https://user-images.githubusercontent.com/26002916/188895994-30489cd9-f396-49ed-9f25-52b80cc3ccfc.png)

**Comment by bosomt** [comment]
**QA NOK**

`Cancel CoinJoin` modal aborts CoinJoin progress in background but you need to close it manually.
`No,continue` button works as expected and modal is closed.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/31506317/197178055-b29b5d9a-628c-4266-979e-ba53c842a7d9.png">

**Info:**
 - Suite version: desktop 22.11.0 (da1945300f7e7497d23eef27030f0c31a6efb43b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision eb182b923f39111d9307a25a86a49d395c6611b0)
 - Transport: bridge 2.0.32

**Comment by dahaca** [comment]
@bosomt has been fixed in https://github.com/trezor/trezor-suite/pull/6637

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.0 (d313a2da2cd5ff7c7dbe243a2c6d75d67643efb7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 8668eba9364b0dfb5fa5250a5366421d6ec1dde1)
 - Transport: bridge 2.0.32
