### ISSUE TITLE
Trezor Connect P2WSH 2of3 multisig change address ignores multisig

### ISSUE THREAD

**Issue by CaveRock** [trezor/trezor-suite#6234]
I am having an issue with using trezor-connect to send a p2wsh multisig change output. 
I have setup a repeatable example here:

[example](https://github.com/CaveRock/trezor-connect-p2wsh-multisig)

I have not been able to find any examples on how to use trezor connect to send a change output to a p2wsh 2of3 change address.

In my example above the change is instead being sent to a pay-to-script-hash for the keypath instead of using the multisig.

My apologies in advance if I am using the incorrect place for this post. Additionally apologies in the instance I have made some elementary error.

**Comment by CaveRock** [comment]
Looking to get any assistance with this if possible. Having to confirm the change address on device is very off putting. I have seen the same result when using Unchained Capital multisig p2wsh wallet, but I don't see the issue when using trezor multisig p2wsh with electrum (which I assume uses the python libraries and not connect).

**Comment by mroz22** [comment]
Hi, in your code example you have a comment 

>  //Setting this to PAYTOWITNESS causes trezor to prompt to change it back to PAYTOMULTISIG

By which I understand that you mean @trezor/connect gives you an error (not device itself) that is thrown by this block of code here:

https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/api/bitcoin/outputs.ts#L47

It feels to me that we could probably omit this validation in case script_type is provided or maybe turn it into a fallback - automatically fill in script_type in case it was not provided and we can make a reasonable guess by address_n of the output. :thinking: By removing this validation I was able to sign tx using PAYTOWITNESS script_type which gave me tx like this 

```
01000000000101ef81a1b013054e972f63dd80230b7abedbc816c34a005d62825e0d3adea38aa40000000000ffffffff02830c030000000000220020ab4e9fef404206b0112ce540e01286e6a07a18ca9005fee27908659a2169ae05801a0600000000001600147e504d6363b885a2fe269f9619b64b53560b5bdd0200695221028ea1d4d06cef29e8bf919995ffb9e55cea91eef5b85ca036e1f9ebe1ab6e5f5521035d4060d36c60a512837ffb316c03bd68e7e448c72c66e462fe528813042e340b2103da108bf1722968df8c228bd6e3981388127169884482664c21f859d3b8d7f1a853ae00000000
```

**Comment by CaveRock** [comment]
Hi @mroz22 , 
"By which I understand that you mean @trezor/connect gives you an error (not device itself) that is thrown by this block of code here:"
Yes, that is correct, it is connect that is throwing the error message not the device.

With the tx that you used paytowitness, did you have to confirm the change address on the device? 

I have seen the following new issue covers my problem exactly:

#https://github.com/trezor/trezor-suite/issues/6343

With a resolution to that issue I believe what I am describing will be solved.

Thank for having a look at my issue and spending some time with potential solution. I'm going to wait and see on progress from the other issue I have linked.

Cheers.

**Comment by sime** [comment]
@CaveRock Which device and firmware are you using?

**Comment by CaveRock** [comment]
@sime 

Using Trezor Model One with firmware version: 1.11.2

I have a colleague with the Trezor Model T and latest firmware that experiences the same issue.
** Correction, I need to rescind the mention of the Trezor Model T, I can't confirm the same behaviour. I will need to rerun my initial tests with this device when I can get my hands on it from my colleague, we are remote so this may take a couple days. Apologies.

**Comment by CaveRock** [comment]
@mroz22 
Thanks for the update to your PR. If I may ask a question, does this update remove the need to confirm change address on device?
