### ISSUE TITLE
suite-native: Improve transaction ordering in account detail

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#6239]
Current implementation in account detail only displays date but it should be formatted similar to desktop suite. 

Current date should be marked as "Today" etc.

https://tppr.me/RYN5D

**Comment by Nodonisko** [comment]
This depends on #6235 because it should be done using formatters.

**Comment by juriczech** [comment]
@Nodonisko Actually the ordering doesn't need formatters because it can be sorted without it. You only need the formatters to implement the formatted values but ordering is already implemented.

**Comment by Nodonisko** [comment]
Then this task is only about usage of formatters there I guess?

**Comment by juriczech** [comment]
after consulting with @Nodonisko, this will have to wait until [Intl reformat](https://github.com/trezor/trezor-suite/pull/5647) is merged. Moving from this sprint to Q1 of 2023.
