### ISSUE TITLE
suite-native: Create the new device type: "imported"

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#6240]
Something like:

type ImportedDevice = {
    type: 'imported';
    id: string | null;
    label: string;
    status: 'available';
    mode: 'normal';
    state?: string;
};

According to the discussion with , the device will also have

remember: true,
connected: false,

**Comment by Nodonisko** [comment]
According to @szymonlesisz we can use `features` field instead or `model` field as some string (should be possible because of model R).
