### ISSUE TITLE
suite-native: Use flat list for transaction list

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#6248]
https://reactnative.dev/docs/flatlist

**Comment by juriczech** [comment]
@Nodonisko Can you please add more information as to why use Flat List?

**Comment by Nodonisko** [comment]
@juriczech I meant for TransactionList not for accounts

**Comment by Nodonisko** [comment]
Related to #6242

**Comment by juriczech** [comment]
Selector already implemented in #6268
