### ISSUE TITLE
Transactions with huge amounts have missing amount in transaction list

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#6252]
**Describe the bug**
Transactions with huge amounts have missing amount in transaction list

**Info:**

-   Suite Version: 22.9.x (introduced here)

**Expected behavior**
The amount should be there.

**Screenshots**
![Screenshot 2022-09-12 at 16 45 59](https://user-images.githubusercontent.com/33235762/189685239-8e14f019-e228-4b92-96fb-c00ef1257ceb.png)

**Comment by STew790** [comment]
**QA OK**
Approved with Tomas' help.

**Info:**
 - Suite version: desktop 22.9.1 (a2cec27a5445c65ca476978302a41b73c9c37994)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.9.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.11.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31
