### ISSUE TITLE
"Verify your seal" window is not visible during onboarding

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#6263]
**Describe the bug**
On the intro screen of the Trezor Suite were user should install FW into the device, there is an `Security check` window with three lines of text. On the first line, there is an `My hologram was intact and untampered with.` There is an `hover` function on the word `hologram`. This displays gif with some information about packaging. However, this new window is not visible when it is in `window mode` as it is dependant on the resolution of the screen.

**Info:**

-   Suite Version: 22.82
-   OS: Mac OS
-   resolution

**How to reproduce**

1. Go to Suite with Trezor without FW
2. Click `Begin setup`
3. Hover on `hologram` word

**Expected behavior**
To see the full hover window anytime or at least be able to scroll in the window.

**Screenshots**
![image](https://user-images.githubusercontent.com/57008159/189872580-e326abf4-0879-4ed7-8011-cdc17adc4006.png)

**Comment by STew790** [comment]
**QA NOK**
This is still happening.
![image](https://user-images.githubusercontent.com/48477147/225001399-e5db395f-0eba-4bad-b2c9-dc73fb593559.png)


**Info:**
 - Suite version: desktop 23.3.2 (2ab6b568e556d4eebd8c0d3bb04fa278bfe18506)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.2 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.12.1 Universal (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.32

**Comment by bosomt** [comment]
**QA OK**


![Image](https://github.com/trezor/trezor-suite/assets/31506317/7de09d1a-c472-4b18-85ee-711d1a746c9f)


**Info:**
 - Suite version: desktop 23.8.1 (11285a745786e8cd7c39ada4945f5893d7e8cd23)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.8.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T1B1   (revision null)
 - Transport: BridgeTransport 2.0.33

**Comment by Hannsek** [comment]
@Hermez-cz We should change the picture and wording for upcoming model as well.
