### ISSUE TITLE
Data Analytics: ETH account with tokens

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#6264]
We want to know which Ethereum accounts have tokens. Best would be to track this when discovery of all accounts is completed (similar to event `account/status`) as a new event (e.g. `ETH-accounts/status`).

**Comment by tomasklim** [comment]
<img width="345" alt="Screenshot 2023-01-02 at 16 15 40" src="https://user-images.githubusercontent.com/33235762/210250172-bd77cde5-04ec-4d01-9291-6902a641d43f.png">
