### ISSUE TITLE
Use native-stack instead of stack for navigation

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#6280]
https://reactnavigation.org/docs/native-stack-navigator/

**Comment by PeKne** [comment]
`native-stack` unfortunately doesn't support **swipe from right** screen transition for iOS (more [here](https://reactnavigation.org/docs/native-stack-navigator/#animation)). If we want to keep this animation, `native-stack` navigation can not be used.

**Comment by Nodonisko** [comment]
Closing this for. We can consider using native stack only for Android where performance could be issue (because on iOS it works fine anyway). We can reopen this if needed.
