### ISSUE TITLE
Connection refused. 

### ISSUE THREAD

**Issue by 0xharsha** [trezor/trezor-suite#6281]
Getting connection refused error when trying to connect with trezor (https://connect.trezor.io/8/popup.html). 

![Screenshot 2022-09-14 at 5 02 42 PM](https://user-images.githubusercontent.com/16958403/190143653-d8f0b953-44ad-4d5a-aa6b-156358b60058.png)

![Screenshot 2022-09-14 at 5 02 54 PM](https://user-images.githubusercontent.com/16958403/190144609-ecf6c639-329b-4a6c-ab17-4a2df8b83bf6.png)

**Comment by 0xharsha** [comment]
@hynek-jina we are calling the `getPublicKey` method inside the chrome extension as shown in the screenshot below. 

![Screenshot 2022-09-14 at 5 10 12 PM](https://user-images.githubusercontent.com/16958403/190147685-fc05f0b4-4fd0-40a8-9251-1be53e1cfe37.png)

Please let me know if any further detail required

**Comment by mroz22** [comment]
hi, do you have your code somewhere public?
if not, just please tell us if you are using extension v2 or v3 and if  you are running this code from background script or not

**Comment by 0xharsha** [comment]
We are using extension V3 built with vitejs react and we are not running code in the background script.

**Comment by mroz22** [comment]
ok, v3 is not officialy supported at the moment, but work is in progress. you should either wait (hope it won't be more than a week or two) or figure it out yoursefl

**Comment by 0xharsha** [comment]
sure thank you :)

**Comment by sime** [comment]
Also, it would be advisable to using v9 of connect for any new development.

**Comment by punithbm** [comment]
Hi @sime, we were trying to figure out v3 support for trezor. When do you think official support for v3 Trezor will be rolled out? If it's very soon probably we can wait.

**Comment by sime** [comment]
It's being worked on. But can't offer a timeline. Will ping this thread when it's available.

**Comment by punithbm** [comment]
Sure. Thanks for the response.

**Comment by mroz22** [comment]
I am closing this. Should be tracked in v3 issue https://github.com/trezor/trezor-suite/issues/6458
