### ISSUE TITLE
Save bitcoin tab reloads randomly in the loop

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-suite#6303]
**Describe the bug**
Invity Save Bitcoin tab reloads for no reason in the loop

**Info:**

-   Remembered Wallet: no
-   Suite Version: app v. v22.8.2
-   OS: macOS Monterey 12.5.1 (21G83)
-   Bridge: Suite bundled
-   Firmware Version: 1.11.2 / 2.5.2

**How to reproduce**

1. Go to Bitcoin account
2. Go to trade tab
3. Click on Save Bitcoin
4. Setup the saving
5. click to redirect to Invity
6. Go back to Suite
7. Save bitcoin section keeps realoding in the loop all of the sudden - see atached video

**Expected behavior**
The tab should not reload

**Screencapture**

https://user-images.githubusercontent.com/37402530/190595762-b91fad05-2498-4280-9a69-bd52b1648821.mov

**Comment**
Quitting the app and launching it again solves this (some caching?)

**Comment by IvaFingerova** [comment]
Wasn't able to reproduce. Added Luky and will discuss further

**Comment by yohaaan** [comment]
@IvaFingerova did you try on a setup where you have an active Invity account you're logged into?

**Comment by bosomt** [comment]
**QA NOK**

it was OK till i created Invity account.


https://user-images.githubusercontent.com/31506317/196439869-140a8c35-e3c0-4547-b3c2-e8d139b81c6a.mov



**Info:**
 - Suite version: desktop 22.9.3 (2b9595fdfee9d36935d72af4af536d2fe4742f5e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.9.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by tomasklim** [comment]
DCA removed
