### ISSUE TITLE
Account discovery error: We were unable to discover your accounts.

### ISSUE THREAD

**Issue by NightProwler-dc** [trezor/trezor-suite#6312]
**Describe the bug**
After update to the latest version, account is not discoverable and balance can't show.
**Info:**

-   Remembered Wallet: yes
-   Suite Version: appImage x64 22.8.2
-   OS: Linux
-   Bridge: version
-   Firmware Version: 2.5.2

**How to reproduce**

1. Start trezor suite appImage
2. unlock trezor T and Click on "Standard wallet"
3. After a long time, it shows "Account discovery error", sometimes it can show after a very long time sometimes only Ethereum balance shows while bitcoin balance keeps loading forever with error: _Asset not loaded correctly_ besides the bitcoin price column.

**Expected behavior**
All balance show normally like before.

**Comment by NightProwler-dc** [comment]
The issue seems to be the bitcoin backend server not connectable.
My system uses proxy to connect to the internet. However I did not have issue before with system proxy.
Did recent update change how the app connect to the internet via system proxy? 
That said, the app can check and download software update via proxy without issue.

**Comment by sime** [comment]
@NightProwler-dc All backends have the same issue?

**Comment by NightProwler-dc** [comment]
I only enabled bitcoin and ETH.
At times ETH balance shows while bitcoin couldn't. I went to settings-crypto-bitcoin backends, it said I need to check my internet connection. That said bitcoin price could show up and program self update was also fast. I think my ISP is dodgy and that's why I use a proxy to have a stable connection. I haven't used trezor suite for a few months but I never had this connection problem with the same setup before.
Trying other web wallets or Trezor suit on web all work without issue (through browser proxy)

**Comment by sime** [comment]
@NightProwler-dc How is the experience when you enable Tor?

**Comment by NightProwler-dc** [comment]
My ISP blocks Tor and if I use tor that would be more complicated than what it is now. I am not sure if  I need to run my own tor instance but I did try the button and it never connected as expected.

**Comment by sime** [comment]
@NightProwler-dc

> Did recent update change how the app connect to the internet via system proxy?

Nothing intentional, it would be handy to share which version was working for you previously. Additionally, we have another version coming out shortly, but again no intentional changes.

> That said, the app can check and download software update via proxy without issue.

Backend interactions are done over websockets to our instances reversed proxied by CloudFlare, whereas updates are normal HTTP via GitHub.

Does your proxy do any changes to the headers? CloudFlare doesn't like it when a client doesn't have a user-agent.

**Comment by randomcop** [comment]
I have the exact same problem, but I do not use a proxy to connect to the internet. Enabling tor in Trezor-Suite-22.8.2-linux-x86_64.AppImage does not resolve the problem. Also downloading the previous version 22.8.1 leads to the same result as with 22.8.2. What changed when upgrading to 22.8.2 was that I also upgraded the Trezor firmware.
I am currently using Linux Mint with kernel "Linux 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux"

**Comment by sime** [comment]
We have plenty of Linux users internally at Trezor, so it can't be a widespread issue.

I wonder if you see anything interesting in Console when these errors occur. You can open the console by pressing: Ctrl + Shift + I

**Comment by NightProwler-dc** [comment]
> I have the exact same problem, but I do not use a proxy to connect to the internet. Enabling tor in Trezor-Suite-22.8.2-linux-x86_64.AppImage does not resolve the problem. Also downloading the previous version 22.8.1 leads to the same result as with 22.8.2. What changed when upgrading to 22.8.2 was that I also upgraded the Trezor firmware. I am currently using Linux Mint with kernel "Linux 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux"

This should not have anything to do with firmware as you can try the device with Trezor suite web or other programs that can read hardware wallets, and they should work there.

> We have plenty of Linux users internally at Trezor, so it can't be a widespread issue.
> 
> I wonder if you see anything interesting in Console when these errors occur. You can open the console by pressing: Ctrl + Shift + I

FYI, this is very likely to be a similar issue with Ledger Live APP, which has had the issue with proxy for years. The devs there had been saying they were working on the proxy connection of (websocket) issue for many years and it went nowhere. And that was the reason I pretty much abandoned my ledger device. But I never had the issue with trezor. The last time I used trezor suite app was several months ago (up to date by then) and didn't have any problem.
Here's the [console output](https://gist.github.com/NightProwler-dc/1a92c5c9dc3785c88722f2032f3549c5) when the app trying to load balance

**Comment by sime** [comment]
> > I wonder if you see anything interesting in Console when these errors occur. You can open the console by pressing: Ctrl + Shift + I
> 
> FYI, this is very likely to be a similar issue with Ledger Live APP, which has had the issue with proxy for years. The devs there had been saying they were working on the proxy connection of (websocket) issue for many years and it went nowhere. And that was the reason I pretty much abandoned my ledger device. But I never had the issue with trezor. The last time I used trezor suite app was several months ago (up to date by then) and didn't have any problem. Here's the [console output](https://gist.github.com/NightProwler-dc/1a92c5c9dc3785c88722f2032f3549c5) when the app trying to load balance

Thanks for the log, unfortunately it's not showing any sort of network errors.

Could you consider doing some debugging? By that, I mean installing an older version of Trezor Suite. Previous versions are available here:

https://github.com/trezor/trezor-suite/releases

The versions are in YEAR-MONTH format. For example, if you last used Trezor Suite in May, the version would be 22.5.x.

I'm curious to see if the issue persists if you re-install older versions of Trezor Suite.

**Comment by NightProwler-dc** [comment]
> I have the exact same problem, but I do not use a proxy to connect to the internet. Enabling tor in Trezor-Suite-22.8.2-linux-x86_64.AppImage does not resolve the problem. Also downloading the previous version 22.8.1 leads to the same result as with 22.8.2. What changed when upgrading to 22.8.2 was that I also upgraded the Trezor firmware. I am currently using Linux Mint with kernel "Linux 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux"

This should not have anything to do with firmware as you can try the device with Trezor suite web or other programs that can read hardware wallets, and they should work there.

> We have plenty of Linux users internally at Trezor, so it can't be a widespread issue.
> 
> I wonder if you see anything interesting in Console when these errors occur. You can open the console by pressing: Ctrl + Shift + I

FYI, this is very likely to be a similar issue with Ledger Live APP, which has had the issue with proxy for years. The devs there had been saying they were working on the proxy connection of (websocket) issue for many years and it went nowhere. And that was the reason I pretty much abandoned my ledger device. But I never had the issue with trezor. The last time I used trezor suite app was several months ago (up to date by then) and didn't have any problem.
Here's the [console output](https://gist.github.com/NightProwler-dc/1a92c5c9dc3785c88722f2032f3549c5) when the app trying to load balance

**Comment by sime** [comment]
@NightProwler-dc Not sure if it was intentional, but you re-posted your previous comment.

**Comment by NightProwler-dc** [comment]
> > > I wonder if you see anything interesting in Console when these errors occur. You can open the console by pressing: Ctrl + Shift + I
> > 
> > 
> > FYI, this is very likely to be a similar issue with Ledger Live APP, which has had the issue with proxy for years. The devs there had been saying they were working on the proxy connection of (websocket) issue for many years and it went nowhere. And that was the reason I pretty much abandoned my ledger device. But I never had the issue with trezor. The last time I used trezor suite app was several months ago (up to date by then) and didn't have any problem. Here's the [console output](https://gist.github.com/NightProwler-dc/1a92c5c9dc3785c88722f2032f3549c5) when the app trying to load balance
> 
> Thanks for the log, unfortunately it's not showing any sort of network errors.
> 
> Could you consider doing some debugging? By that, I mean installing an older version of Trezor Suite. Previous versions are available here:
> 
> https://github.com/trezor/trezor-suite/releases
> 
> The versions are in YEAR-MONTH format. For example, if you last used Trezor Suite in May, the version would be 22.5.x.
> 
> I'm curious to see if the issue persists if you re-install older versions of Trezor Suite.

Downloaded 22.3.2, 22.4.2. There was only the first launch that was successful but couldn't detect Trezor device. Then after that launch, all following launches showed a never ending circling animation after I chose "not to update now". Reboot doesn't help. Latest version still launches fine but can't show wallet balance like before. Do older versions conflict with other appimages that have been used on the same machine?

**Comment by NightProwler-dc** [comment]
I have no issue using electrum with trezor. Any tips on how to find and fill an electrum server on the Trezor suite so I can try?

**Comment by sime** [comment]
> Downloaded 22.3.2, 22.4.2. There was only the first launch that was successful but couldn't detect Trezor device. Then after that launch, all following launches showed a never ending circling animation after I chose "not to update now". 

Thanks for trying this! One crazy idea is to try Trezor Suite in a VM on your current machine. 

> Do older versions conflict with other appimages that have been used on the same machine?

No, it shouldn't. 

> I have no issue using electrum with trezor. Any tips on how to find and fill an electrum server on the Trezor suite so I can try?

Yes, we support custom Electrum server backends. In short: Settings > Crypto > hover over Bitcoin > click gear/cog > select custom Electrum server.

More details: https://blog.trezor.io/connecting-your-wallet-to-a-full-node-edf56693b545

**Comment by GVALFER** [comment]
I have the same error.
But:
I do not use any proxy, i am connected normally to the internet.
I just reinstalled my PC, installed the Trezor Suite and I cant connect to my wallet.

The app keep with this msg for a long time:
"Trezor is running a coin discovery check to find your accounts and funds."
And at the end got this:
"This hidden wallet is empty. To make sure you are in the correct hidden wallet, please type the passphrase again."

This is ridiculous :(
I appreciate any help here..

**Comment by roundtripdelay** [comment]
I'm consistently seeing this as well. I have not been able to get my bitcoin account to load for hours (ETH is fine).  Get an error:

Accounts were not loaded properly
Bitcoin: Websocket timeout

I'm not sure if it's my wireshark setup but see a lot of TLS Ignored Unknown Record messages. Maybe an MTU mismatch or an issue on cloudflare? I VPN'ed to different continents but still experience the issue. I upgraded to the latest version but same issue.

**Comment by sime** [comment]
@roundtripdelay @GVALFER Which please detail which Linux distribution you are on, and ideally kernel version (so I don't have to look it up).

Secondly, do you have any success using the web version of Trezor Suite? https://suite.trezor.io/web

**Comment by roundtripdelay** [comment]
@sime it ended up syncing last night and is working fine now... so for me it was intermittent. i'm using OSX version 22.9.3.21688. I never use the web suite but can try next time i see the issue.

**Comment by NightProwler-dc** [comment]
With more tests I can confirm that Trezor suite now has trouble under proxy environment since recent updates.
When turn off system proxy but use VPN on the same machine, it can connect normally.

Now both ledger live and trezor suite stop working under proxy environment. Ledger has the issue since 4 or 5 years ago. Trezor just joined.

I read that this issue happens on other programs like pip too. They can't connect under system proxy environment due to poor coding practice somewhere.

> 
> Secondly, do you have any success using the web version of Trezor Suite? https://suite.trezor.io/web

trezor suite on web works fine, although the browser connects also through the proxy. I hope you don't bring down the suite on web like ledger did.

**Comment by donald22122** [comment]
Hi there . used trezor model T in a week via TOR connection all was perfect . after i sent some $ to a different wallet my trezor suit was lagged and  disconnected. for now i have this issues.
1) https://prnt.sc/gFvxwLim1h7u   (TOR is turned OFF)
2) https://prnt.sc/UgsrDO5JGF3y this is for web version.

no proxy or vpn used - never.

please advice

**Comment by sime** [comment]
> Hi there . used trezor model T in a week via TOR connection all was perfect . after i sent some $ to a different wallet my trezor suit was lagged and disconnected. for now i have this issues.
> 
>     1. https://prnt.sc/gFvxwLim1h7u   (TOR is turned OFF)
> 
>     2. https://prnt.sc/UgsrDO5JGF3y this is for web version.
> 
> 
> no proxy or vpn used - never.
> 
> please advice

Bitcoin backends were down (out of sync) yesterday for about an hour. The Trezor status page indicates this too: notice the orange mark on November 1st. https://status.trezor.io/

<img width="430" alt="Screenshot 2022-11-02 at 14 55 35" src="https://user-images.githubusercontent.com/216917/199507862-1f718317-f010-4d8b-94c9-2a5afa79f98e.png">

**Comment by chenxsan** [comment]
Got a similar issue when using the web version https://suite.trezor.io/web/ with proxy.

<img width="1091" alt="" src="https://user-images.githubusercontent.com/1091472/200817413-35c5518e-9bea-4f04-97c4-25f900d4dd9d.png">

**Comment by wjx** [comment]
Still have the same issue with both Trezor Suite(22.12.1) and web version Trezor Suite. My system is MacOS 12.3.1. 
I even tried remove Trezor Bridge and using WebUSB to connect Trezor to the web version, which doesn't solve the problem.  

Trezor server status seem fine now: https://status.trezor.io/

For some reason my browser and system have to use socks proxy. 

With this issue Trezor is literally unusable now. Is there anything I can do to help debug this issue?

**Comment by sime** [comment]
@wjx That is odd, so Trezor Suite for Web doesn't work with a socks proxy? I imagine no sites would work in that case. 

Which browsers have you tried? Also, I suggest [checking if websockets ](https://websocketstest.com/)work when using a socks proxy.

**Comment by wjx** [comment]
@sime Thanks for your reply,

I tried Chrome 109.0.5414.119 and Firefox 109, both doesn't work, and Websocket works(with https://websocketstest.com/  test) with my socks proxy on both of the browsers.  

From developer tools I see many websocket request are sent to Trezor servers like `wss://btc3.trezor.io/websocket`. On Chrome the connection status turns into 'Finished'(seems failed) and on Firefox the status are more clear: '403
Forbidden'. 
Following are the Request and Response header info for the failed connection from FIrefox Web Developer Tools,

Request Header:  
```
GET /websocket HTTP/1.1
Host: btc1.trezor.io
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://suite.trezor.io
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: n2axkxymTR+M8k8zY6u1NA==
Connection: keep-alive, Upgrade
Sec-Fetch-Dest: websocket
Sec-Fetch-Mode: websocket
Sec-Fetch-Site: same-site
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```

Response Header:
```
HTTP/1.1 403 Forbidden
Date: Mon, 30 Jan 2023 14:32:08 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
Referrer-Policy: same-origin
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=o3Z7ZbJBtR%2FzUv94INZ%2FSp0bEDkIghlspXA79hi0QSt4DZtL53Tz%2FyQZuRs2SOgpsUoxF7tanTo%2BlWOG2a1i070bBhSK2vOAsHjg9vWqRFcdq3JgPe8a2Q21qIr3ytid"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Server: cloudflare
CF-RAY: 791aea4f6fdedff1-NRT
Content-Encoding: br
```

I found that Trezor Suite for Web **works** with Tor Browser over my proxy (that is, my Tor Browser connects to the internet through my socks proxy).  

My socks server connects to the Internet through VPS servers.  I tried two cloud VPS providers, both don't work.

**Comment by sime** [comment]
@wjx Are you messing with your user agent by any chance? The blockbook instances are proxied via CloudFlare and they require a user agent.

Can you use this page? https://btc1.trezor.io/test-websocket.html

**Comment by wjx** [comment]
@sime I didn't change my Browser configs. 
I cannot access https://btc1.trezor.io/test-websocket.html successfully, it reports:
```
Access denied
Error code 1020
You do not have access to btc1.trezor.io.

The site owner may have set restrictions that prevent you from accessing the site.

Error details:
I got an error when visiting btc1.trezor.io/test-websocket.html.

Error code: 1020

Ray ID: 792ac2978836f609

...
``` 
Maybe CloudFlare is blocking VPS IP address? Or is this a Trezor restriction?

**Comment by sime** [comment]
@wjx Then your VPS is likely hosted on AWS. And we have difficultly serving those.

**Comment by wjx** [comment]
@sime  Yes, it's on AWS. Is this for spam/DDoS prevention? 
I wish this restriction could be lifted. At least adding this to Trezor Suite error info could also make people less confused.

**Comment by chenxsan** [comment]
> @sime Yes, it's on AWS. Is this for spam/DDoS prevention? I wish this restriction could be lifted. At least adding this to Trezor Suite error info could also make people less confused.

Second this, would be great to mention somewhere.

**Comment by donald22122** [comment]
![image](https://user-images.githubusercontent.com/117170282/220650719-3ff55167-99e1-4133-9eaa-eddc58077abe.png)

i have 1.24 bitcoin on my account . this 1.24 bitcoin consist of 10-15$  transactions it means that there is around 3000 transactions. today i wanted to send 1000$ to my own new created segwit bitcoin wallet at trezor (via app). the transaction was with this error that you can see on the screen .  after this i have always seen this error  even if try to send 5$. i have tried to disconnect and connect trezor  and nothing happened always same problem . please advice

**Comment by sime** [comment]
> ![image](https://user-images.githubusercontent.com/117170282/220650719-3ff55167-99e1-4133-9eaa-eddc58077abe.png)
> 
> i have 1.24 bitcoin on my account . this 1.24 bitcoin consist of 10-15$ transactions it means that there is around 3000 transactions. today i wanted to send 1000$ to my own new created segwit bitcoin wallet at trezor (via app). the transaction was with this error that you can see on the screen . after this i have always seen this error even if try to send 5$. i have tried to disconnect and connect trezor and nothing happened always same problem . please advice

Please read this blog post, I believe you may have a non-genuine Trezor https://blog.trezor.io/stay-safe-shopping-for-hardware-wallets-543f144e3d24

**Comment by donald22122** [comment]
lol :) waiting for the real dev

**Comment by donald22122** [comment]
this one was bought from original web. what next?

**Comment by donald22122** [comment]
100% same situation on the web suit

**Comment by sime** [comment]
@donald22122 I pointed to the blog post because the message you are experiencing is 1 to 1 with a fake device, in the specific situation when signing a Bitcoin transaction.
>  -26: non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)

The next step is to contact [support](https://trezor.io/support) or reach out on the [Trezor Forum](https://forum.trezor.io/).

**Comment by donald22122** [comment]
when i`m login in  to trezor web i can see btc. so it cant be fake device

**Comment by sime** [comment]
@donald22122 Please contact support. This GitHub thread is not related to your issue.

**Comment by cnzhang2022** [comment]
DeviceCommands Received Address { address: 'mkMXYEoXqbW8smGqUqVQSrTRKjDyxdgwhY', mac: null }
Core handleMessage true { event: 'UI_EVENT', type: 'popup-handshake' }
[Worker "TEST"]: onmessage { id: 0, type: 'm_connect' }
[Worker "TEST"]: Connecting to https://tbtc1.trezor.io

[Worker "TEST"]: Connection failed CustomError: Message not set
    at WebSocket.<anonymous> (D:\electron-main-process\node_modules\@trezor\blockchain-link\lib\workers\blockbook\websocket.js:147:24)
    at Object.onceWrapper (node:events:642:26)
    at WebSocket.emit (node:events:527:28)
    at BlockbookAPI.onTimeout (D:\electron-main-process\node_modules\@trezor\blockchain-link\lib\workers\blockbook\websocket.js:60:16)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7) {
  code: 'blockchain_link/websocket_runtime_error'
}

**Comment by Yachara** [comment]
I have the same issue.
My OS: Ubuntu 22.04
Firmware version: 1.12.1
Suit version: 23.5.2
-----------------------------
The Dashboard just continuously loads and loads and after a while it says "Account discovery error."

Console logs only show:
```
DevTools failed to load source map: Could not parse content for file:///js/vendors.fadd18ee.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///js/components.d62979fa.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///js/react.4870ede3.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///js/main.a4bf20cd.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///js/50626.937bd76c.js.map: Unexpected end of JSON input
```

SOLUTION was to download an earlier version of suit (22.11.1). And that one worked.

**Comment by MiroslavProchazka** [comment]
@Yachara @NightProwler-dc is this still happening for your in Suite 24.1.2 version please?

**Comment by Yachara** [comment]
Hi. I used the Suit version: 24.2.4. and it worked fine.

**Comment by MiroslavProchazka** [comment]
It appears to have been resolved and closed for the time being.

**Comment by Veranik89** [comment]
Добрый день! При подключении к кошельку Trezor One после ввода пин-кода при попытке входа в стандартный кошелек информация о балансе не грузится. Появляется сообщение "Ошибка обнаружения. Счета не удалось правильно загрузить
Bitcoin: All backends are down". Ниже в списке активов напротив каждого актива написано "Актив не удалось правильно загрузить". Подскажите, как можно исправить проблему и получить доступ к балансу? Может ли помочь загрузка более ранней версии? или может быть попробовать восстановить резервную копию? Помогите пожалуйста!
![2024-06-18_00-38-58](https://github.com/trezor/trezor-suite/assets/173072996/c51b9cea-da92-4b65-ba7f-7c0893b9636b)
![2024-06-18_00-38-40](https://github.com/trezor/trezor-suite/assets/173072996/f3813ae6-f069-4173-a827-a6736d8daa94)

**Comment by MiroslavProchazka** [comment]
Hello @Veranik89, 

this seems like a network error. Could you please try following steps? 
1) Try to download the Suite desktop app from https://trezor.io/trezor-suite 
2) Turn off your VPN (You can't use VPN and TOR together, try just one of those) 
3) Connect to VPN to a different region (Europe/USA etc.) 
4) Try to use your mobile data/different wifi 

Please make sure to visit Trezor Suite web or download Trezor Suite desktop app only directly from our websites, there are lot's of phishy websites trying to impersonate us.

**Comment by zoloto-exe** [comment]
![brave_cbyBl4a0S6](https://github.com/user-attachments/assets/dffb9498-7d33-4733-a22e-3beb54b316ae)
@Veranik89 у меня такая же проблема , нашли решение? ничего не помогает , что за херня?
