### ISSUE TITLE
Implement Keyboard Avoiding for inputs

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#6318]
Default KeyboardAvoidingView is not working well acording to RN community. Investigate 3rd party solutions like https://github.com/APSL/react-native-keyboard-aware-scroll-view 

Also try to research other libs (if they are any). 

It should replace ScrollView in Screen component.

**Comment by juriczech** [comment]
@Nodonisko What does it mean `not working well acording to RN community` please?
