### ISSUE TITLE
Send appUrl host to popup.html

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#6326]
### Summary 
Increase the visibility of web extension usage in Connect.

### Problem
Since web extensions do not have an HTTP referrer, we have no visibility to which web extensions Trezor users currently use.

### Propose solution
Send `appUrl` host in popup.html
e.g. For [MetaMask](https://github.com/MetaMask/eth-trezor-keyring/blob/0e2ee81d422c11ed9be7510c471fec5cb2150529/index.js#L22) the popup window will appear as follows.
```
https://connect.trezor.io/9/popup.html?appUrl=metamask.io#
```

**Comment by mroz22** [comment]
do it also for version 8 if possible

**Comment by mroz22** [comment]
After some digging I found that this might not be doable without breaking changes, 

if we want to have arbitrary query string, we would need to update manifest. metamask for example, would be affected 
https://github.com/MetaMask/metamask-extension/blob/develop/app/manifest/v2/_base.json#L45

There would need to be something like (see * at the end)
```
            "matches": ["*://connect.trezor.io/9/popup.html*"],
```

We need to find a workaround and this might not be lowhanging fruit :man_shrugging:

**Comment by sime** [comment]
Ouch, that was unexpected.

Can we ensure this manifest v3?

Happy to sit down and try and work out alternatives. My only other idea is to use document.referrer and report that, as they seem to be consistent. As `nkbihfbeogaeaoehlefnkodbefgpgknn` is MetaMasks identifier.

![Screenshot 2023-01-02 at 17 09 14](https://user-images.githubusercontent.com/216917/210255854-53cdcaf6-69f5-4d25-8f99-126a5dd40a9e.png)

**Comment by STew790** [comment]
Nothing needed from QA.
