### ISSUE TITLE
Trezor Connect and BIP-48 multisig wallets with segwit not working

### ISSUE THREAD

**Issue by jhoenicke** [trezor/trezor-suite#6343]
**Describe the bug**
BIP-48 compatible multisig wallets using segwit not supported by Trezor Connect.

**Info:**

-  Trezor connect version 9; I think it affects all versions

**How to reproduce**
Create a BIP-48 multisig wallet with spendp2shwitness or spendwitness and use a change output.

**Expected behavior**
There are four types of BIP-48 wallets:
- old format (not compatible with BIP-48) `m/48'/coin'/account'` (PAYTOMULTISIG)
- multisig without segwit: `m/48'/coin'/account'/0'`  (PAYTOMULTISIG)
- multisig with p2sh segwit: `m/48'/coin'/account'/1'` (PAYTOP2SHWITNESS)
- multisig with native segwit: `m/48'/coin'/account'/2'` (PAYTOWITNESS)

Note that segwit multisig wallets need to use `PAYTOP2SHWITNESS` or `PAYTOWITNESS`; `PAYTOMULTISIG` is only used for non-segwit wallets.  This was a design decision for segwit to avoid adding PAYTOMULTISIGP2SHWITNESS, etc.  Instead multisig is simply indicated by the presence of the multisig structure.

The checks for  `getOutputScriptType` and `getScriptType` are wrong for segwit multisig wallets:

https://github.com/trezor/connect/blob/develop/src/js/utils/pathUtils.js#L66-L105

Compare this with the correct checks that the Trezor One does:

https://github.com/trezor/trezor-firmware/blob/master/legacy/firmware/crypto.c#L566-L606

Here is an example transaction structure that complains that output type should be PAYTOMULTISIG (which would create a non-segwit address):

```json
{
  "coin": "TEST",
  "inputs": [
    {
      "address_n": [
        2147483696,
        2147483649,
        2147483652,
        2147483649,
        0,
        0
      ],
      "amount": 200000,
      "multisig": {
        "m": 2,
        "pubkeys": [
          {
            "address_n": [
              0,
              0
            ],
            "node": "tpubDFQZ2zbh87ztfQvvB9sbPxUzmp8gghwzNETtmFw9cGD9Z6qPo2Fs3ohp3J6M3e1uJCpsXq9z52JBC4Ey3BsncaXTdiv68cgZ9SFpg1RmHft"
          },
          {
            "address_n": [
              0,
              0
            ],
            "node": "tpubDEs6bv9sDm5DWbcQujozo4AyByVgirWjtDxa7wJ5bPFvbLgBwFfUtyjaFUops3qVu3LtC3CJuXjBMQYEsTTZviDD8B5VZ2y8XVeHgMKWoJS"
          },
          {
            "address_n": [
              0,
              0
            ],
            "node": "tpubDErpDGjyZFY6fAx2vZDz9fch43byUQwBA92om8H9MKnduEEABr7xv7xvxz7QCULpMRKV4bbaYqkqbcJH3tZKYko8cnnJKpebLGcNMW2b1jq"
          }
        ],
        "signatures": [
          "",
          "",
          ""
        ]
      },
      "prev_hash": "1b98f348b2129f5ae6dc976ef24cc8bb1a47e011ee9bbf2d49721e207485d412",
      "prev_index": 0,
      "script_type": "SPENDP2SHWITNESS"
    }
  ],
  "outputs": [
    {
      "address": "2NDzn3wDCJLcyY26gMvHJN1Eh7buX6yGoas",
      "amount": 10000,
      "script_type": "PAYTOADDRESS"
    },
    {
      "address_n": [
        2147483696,
        2147483649,
        2147483652,
        2147483649,
        1,
        0
      ],
      "amount": 188930,
      "multisig": {
        "m": 2,
        "pubkeys": [
          {
            "address_n": [
              1,
              0
            ],
            "node": "tpubDFQZ2zbh87ztfQvvB9sbPxUzmp8gghwzNETtmFw9cGD9Z6qPo2Fs3ohp3J6M3e1uJCpsXq9z52JBC4Ey3BsncaXTdiv68cgZ9SFpg1RmHft"
          },
          {
            "address_n": [
              1,
              0
            ],
            "node": "tpubDEs6bv9sDm5DWbcQujozo4AyByVgirWjtDxa7wJ5bPFvbLgBwFfUtyjaFUops3qVu3LtC3CJuXjBMQYEsTTZviDD8B5VZ2y8XVeHgMKWoJS"
          },
          {
            "address_n": [
              1,
              0
            ],
            "node": "tpubDErpDGjyZFY6fAx2vZDz9fch43byUQwBA92om8H9MKnduEEABr7xv7xvxz7QCULpMRKV4bbaYqkqbcJH3tZKYko8cnnJKpebLGcNMW2b1jq"
          }
        ]
      },
      "script_type": "PAYTOP2SHWITNESS"
    }
  ]
}
```

**Comment by CaveRock** [comment]
@jhoenicke 

I can confirm that this occurs with connect versions 9 and 8 (I haven't tested anything lower than those)
