### ISSUE TITLE
Tab tag "new" for Trade section

### ISSUE THREAD

**Issue by IvaFingerova** [trezor/trezor-suite#6344]
We are adding new features to the Trade section and to make them pop out, tag "new" will help. 

Now it will help us to promote DCA (save bitcoin) to which a big campaign with SwanBitcoin will take place in the upcoming months

Figma: https://www.figma.com/file/pIibgxmxD0jrAa9UGJd9da/Neue-Desktop-1.5?node-id=2480%3A48780

Screenshot:
<img width="330" alt="image" src="https://user-images.githubusercontent.com/8152411/191433756-0e44a6f2-f234-4ad7-854e-e7b9ede013da.png">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.10.0 (25d2c8c65518157e88d16cab32a776fe9cd7177d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
 - OS: MacIntel
 - Screen: 1848x1155
 - Device: model T 2.5.3 Universal (revision 9cec8f057a28afb2f6d432cc90c0a586833b6670)
 - Transport: bridge 2.0.32
