### ISSUE TITLE
Incorrect welcome message after adding custom token to empty ETH account

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6346]
**Describe the bug**
I see incorrect welcome message after adding custom token to my empty ETH account.
See video and screenshots. Message changes from `No tokens` to `No transactions... yet.`

**Steps to reproduce:**
1. Add new ETH account
2. Observe welcome message in Token section
3. Add custom token and observe welcome message again

**Info:**
 - Suite version: web 22.8.2 (58f4c5bf0804e02c05c0b85e020b6e452b419164)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.3 Universal (revision af8a7790fb39bec2bbfdb2746e9fbab81ff9381e)
 - Transport: bridge 2.0.32

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/191447871-2cb5d74a-64c7-4941-abb7-9887bfbeec3a.png)
![image](https://user-images.githubusercontent.com/31506317/191447890-41024217-471c-4b6e-90a4-4402a4cd18f4.png)

https://user-images.githubusercontent.com/31506317/191447522-aef50539-355e-4e18-bc73-b9399ca10576.mov

**Comment by sime** [comment]
The `Add Token` functionality may be removed in the future, as an upcoming Blockbook version will remove the need for add tokens manually.

**Comment by komret** [comment]
I suppose the desired behaviour is not to show the "No transactions" message on this tab, right? Once I add a token, there is no message. Implemented here: #6562

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.11.0 (06a5bf901f7dd05b98d7db650afbef79680efdb7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0
 - OS: MacIntel
 - Screen: 1584x990
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31
