### ISSUE TITLE
Tor suite process not starting in Mac OS when other Tor process is running.

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#6361]
**Describe the bug**
Tor suite process not starting in Mac OS when other Tor process is running.

**Info:**

-   Suite Version: latest develop
-   Browser: desktop app
-   OS: macOS 12.6 | darwin x64

**How to reproduce**

1. Have Tor successfully enabled in Trezor Suite. Exit the app.
1. Turn on the tor service with `brew services start tor`.
1. Start Trezor Suite again and wait for the error to appear…

**Expected behavior**
Tor process should start properly.

**Comment by bosomt** [comment]
22.8.2 + brew tor running


- first attempt : Failed to enable Tor 
- second attempt : Failed to enable Tor
- third attempt :   Failed to enable Tor

is it even possible to run two instances of tor at once ?

**Info:**
 - Suite version: desktop 22.8.2 (58f4c5bf0804e02c05c0b85e020b6e452b419164)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.2 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.3 Universal (revision 9cec8f057a28afb2f6d432cc90c0a586833b6670)
 - Transport: bridge 2.0.32

**Comment by sime** [comment]
I guess it like trying to run two instances of trezord at once.

**Comment by STew790** [comment]
**QA OK**
Tested both on MacIntel as well as MacArm.

**Info:**
 - Suite version: desktop 22.10.0 (233251d3cc640acc0d583da609c7cd402fbba24d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.10.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device:
 - Transport: bridge 2.0.31
