### ISSUE TITLE
Tor enabling screen better resolution image

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#6363]
**Describe the bug**
The image `packages/suite-data/files/images/png/Tor_enabling.png` used in Tor enabling screen could have better resolution, it looks a bit  pixelated.  

**Screenshots**

![image](https://user-images.githubusercontent.com/5362163/191687434-5000bf10-f04c-468c-8418-5e91225f03da.png)

**Comment by karliatto** [comment]
Ok, there is already a PR solving this https://github.com/trezor/trezor-suite/pull/6355
Thanks @tomasklim

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.10.0 (07a9a0d73a0f1482e8d466cc8c5ee6ed410098ed)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
 - OS: MacIntel
 - Screen: 1848x1155
 - Device: model T 2.5.3 Universal (revision 9cec8f057a28afb2f6d432cc90c0a586833b6670)
 - Transport: bridge 2.0.32
