### ISSUE TITLE
Trezor reuses change address

### ISSUE THREAD

**Issue by piriya33** [trezor/trezor-suite#6381]
**Describe the bug**
Upon looking through my past transactions, I discovered that Trezor would occasionally send changes from multiple transactions to the same change address when multiple transactions are made within a block's window, this would deanonymize coinjoined utxos.

**Info:**

-   Remembered Wallet: yes
-   Suite Version: This applies to both wallet and app as older transactions display the same behaviour
-   Browser: multiple
-   OS: multiple
-   Bridge: miltiple
-   Firmware Version: multiple

**How to reproduce**
1. Make multiple transactions, with different inputs and addresses, within a small window of time (before a new block is mined) , if there's change, the changes will be sent to the same change address.
2. When spending from said change address, unused UTXOs are left locked in the address with exposed public key.

**Expected behavior**
1. A new change address should be used every time.
2. When spending from change address with multiple utxos, all utxos should have been used and sent to a new address?

**Screenshots**
![image](https://user-images.githubusercontent.com/20140583/191952423-94024b55-df13-4c49-abdf-7b41a680ff3f.png)
![image](https://user-images.githubusercontent.com/20140583/191952479-e897d84d-8b32-42c5-9be9-ffbd4ff72889.png)
additional screenshots available but these should suffice.

**Additional context**
I believe Trezor wallet check to see if a change address had been used by checking the blockchain so when multiple transactions are made in close succession, the changes are sent to the same change address.
This could potentially de-anonymized utxos that have been through coinjoins by tieing them back together through changes. It would be nice if the wallet also checks the transactions it has made for any address reuse, confirmed or un-confirmed, but this could also present a different problem.

**Comment by sime** [comment]
@piriya33 Has this happened more than once in your experience? Will try and reproduce in the latest version of Trezor Suite.

**Comment by piriya33** [comment]
Yes, the first time I noticed this was when I played around with splitting coinjoined utxo on a friend's wallet for demonstration, and all the changes went to the same address. 
I'll need to ask him for the transaction id later. 

After that incident I checked my past transactions to see if it has ever happened before and turns out that everytime I make multiple transactions within a short window of time (like when paying paychecks when I want to separate the transactions instead of batching them for privacy purpose.), all my changes went to the same address.

**Comment by piriya33** [comment]
Corrections, I checked further and it seems that this did not happen way back in 2019 and earlier, I guess it's a Trezor Suite thing?

**Comment by piriya33** [comment]
![image](https://user-images.githubusercontent.com/20140583/192077200-90796abc-22fd-44bc-addf-913c7b432670.png)
Here's another transaction where I play around with consolidating different sized utxos into identical sized utxos 
(don't ask me why I did that, I was just experimenting) 
I made around 7 such transactions in s short window in Trezor Suite. 
All of the changes went to the same address.

**Comment by sime** [comment]
Thanks for the report @piriya33, nice level of detail. Next will be our QA team to confirm the behaviour (aka bug).

**Comment by bosomt** [comment]
**QA NOK**

I can confirm this behavior.
Sent 3 transactions.
Used 3 separate inputs.
All 3 change addresses are same.

<img width="756" alt="image" src="https://user-images.githubusercontent.com/31506317/192860572-c6c66d3a-ec8c-4f22-a119-7becde07d635.png">


<img width="764" alt="image" src="https://user-images.githubusercontent.com/31506317/192859996-f65f5475-a79b-4787-818d-66cdafb088f5.png">

<img width="764" alt="image" src="https://user-images.githubusercontent.com/31506317/192860043-32345b18-9215-40a8-a06b-fc8a73acfc17.png">

https://tbtc2.trezor.io/tx/3391b8b08a19c1037bce1a9b0cabf31a71bf8bcefbbed79aab252e2a17bb5909
https://tbtc2.trezor.io/tx/5e34d15e0bae80acd5cd3a5ba699ddbdf57134b5e8e5a380ebf329ad4f253924
https://tbtc2.trezor.io/tx/a4b8470fc66ff360d57601e4982502e2b731380f3617cfb9e01e940b5861e53d

**Comment by hynek-jina** [comment]
We need to address this on an Electrum level too...

**Comment by bosomt** [comment]
**QA OK**

<img width="609" alt="image" src="https://user-images.githubusercontent.com/31506317/208055474-8127ba65-27f0-4a41-b813-ef44e613257f.png">

<img width="604" alt="image" src="https://user-images.githubusercontent.com/31506317/208055507-56f668b7-9885-41e8-a114-2445468d2fa0.png">

<img width="614" alt="image" src="https://user-images.githubusercontent.com/31506317/208055532-54ae2324-af24-4a56-8cd0-79fe23b890a8.png">


**Info:**
 - Suite version: desktop 23.1.0 (38b40ef729793e945c3ad2c1f45e29db49460311)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision ff35c77bad82c7acac1df6245940ebe0d6454642)
 - Transport: bridge 2.0.32
