### ISSUE TITLE
Misaligned text in Recovery seed check modal

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6384]
**Describe the bug**
Misaligned text in `Recovery seed check` modal.

**Steps to reproduce:**
1. Navigate to Settings/Device/Wallet backup section
2. Start `Check backup`
3. Interrupt `Check backup` or enter incorrect seed words and observe test in modal. 

**Info:**
 - Suite version: desktop 22.10.0 (07a9a0d73a0f1482e8d466cc8c5ee6ed410098ed)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.10.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.3 Universal (revision 9cec8f057a28afb2f6d432cc90c0a586833b6670)
 - Transport: bridge 2.0.32

**Screenshots:**
<img width="632" alt="image" src="https://user-images.githubusercontent.com/31506317/192138339-0d702880-f96a-42d6-b871-92809988c362.png">

<img width="630" alt="image" src="https://user-images.githubusercontent.com/31506317/192138513-76f74eb6-3931-452e-a497-2251951838dd.png">

**Comment by STew790** [comment]
**QA OK**
![image](https://user-images.githubusercontent.com/48477147/194309551-c5ae42d9-e8aa-43ab-82ac-4fa8ea8db7f8.png)

**Info:**
 - Suite version: desktop 22.11.0 (d738700d52e85cef51a003c069de4bb22f9e9125)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32
