### ISSUE TITLE
Enforce autoupdate by overriding the gradual rollout 

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#6397]
Add an option to enforce update from Settings for eager users because of gradual rollout.

I believe this needs patching the upstream autoupdater library so it might be kind of difficult / annoying.

**Comment by bosomt** [comment]
@hynek-jina looks like low hanging fruit to me , can we get this rolllin so we can check autoupdate after non 100% rellease ?

**Comment by hynek-jina** [comment]
Hi, yes.. this would be helpful and hopefully straight forward... 
Decision about the relative priority is on @sime

**Comment by sime** [comment]
Cautious introducing another setting.

In case of emergency this is solvable by downloading suite directly.

**Comment by STew790** [comment]
@sime Not when we want to try the autoupdate.

**Comment by hynek-jina** [comment]
It could be triggered by `check for updates`.. but it doesn't help with autoupdate.. 
![Screenshot 2023-03-16 at 14 32 41](https://user-images.githubusercontent.com/26002916/225633720-ccb7ef51-a307-46b9-9c76-fdc9fc1360f4.png)

**Comment by sime** [comment]
How often are we checking auto update? Once a release?

Also AFAIK we don't have a staging auto update.

**Comment by matejkriz** [comment]
There is a new issue proposing solution for this: https://github.com/trezor/trezor-suite/issues/11676
