### ISSUE TITLE
"Add wallet" unavailable

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#6405]
**Describe the bug**
Cannot add wallet even though the device is connected

**Info:**

-   Remembered Wallet: no
-   Suite Version: 22.9.3
-   OS: macOS, 12.6
-   Firmware Version: TT, 2.5.2

**How to reproduce**

1. Access wallet
2. Eject wallet while loading -> no wallets are connected
3. see error

**Expected behavior**
To be able to add new wallet

**Screenshots**
<img width="979" alt="image" src="https://user-images.githubusercontent.com/57008159/192566674-919987e8-d083-420c-b8a4-7ca70e20f887.png">

**Additional context**
This is very edge case. In my opinion Suite/Trezor gets stuck in loading process.

**Comment by bosomt** [comment]
It's not really edge case, happens to me every day :)
Its easy to reproduce, all you have to do is to do almost anything during discovery :)
See similar issue here https://github.com/trezor/trezor-suite/issues/4268

**Comment by Niproblema** [comment]
Since upgrading from 22.10 trezor suite is unsable for me. Laggiest pos ever, everytime I reconnect the device the usb service no longer works etc. Very very bad

**Comment by matejkriz** [comment]
I believe this one has been fixed, please reopen if you ever see it again 🙏 
cc @bosomt

**Comment by matejkriz** [comment]
> Since upgrading from 22.10 trezor suite is unsable for me. Laggiest pos ever, everytime I reconnect the device the usb service no longer works etc. Very very bad

I'm sorry for the very late reply, if you are having any problems with the app please contact our support representatives here: https://trezor.io/support

**Comment by bosomt** [comment]
**QA OK**

i was not able to reproduce it for some time
as soon it will be possible to reproduce it i will create new issue
