### ISSUE TITLE
Dependencies: upgrade React and React-DOM

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#6414]
Upgrade manual:
https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

The upgrade will be followed by an upgrade to the mobile app.

**QA:** No visible changes, but pls go through the app to see if anything has broken (as described in the Notion request).

**Comment by bosomt** [comment]
**QA OK**

see https://www.notion.so/satoshilabs/React-upgrade-04c7cbfc41984794a848ccea74f4937b
