### ISSUE TITLE
Block all CoinJoin requests with disconnected Tor

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6418]
- [x] Warn user If he disconnects Tor, that he will not be able to access CoinJoin account - https://github.com/trezor/trezor-suite/pull/6713
- [x] Pause CoinJoin sessions when after creating CoinJoin account Tor is disable.
    - Pause running CoinJoin when Tor is disable (because of user action or for any other reason)
    - When user goes to CoinJoin account a banner explaining that CoinJoin is paused because of Tor being disable
    - The button pause/resume in CoinJoin account should be disable
- [x] Don't fetch the CoinJoin data If user decides to turn off the Tor or the Tor is not available. Behave like when the backend is disconnected. - this part is going to be handled by using only `.onion` addresses to communicate with CoinJoin backend so even if for some reason the CoinJoin account is not disposed properly the communication is not going to work.

**Comment by bosomt** [comment]
**QA OK**

<img width="616" alt="image" src="https://user-images.githubusercontent.com/31506317/207841289-095fee6f-870d-4192-97c0-586e392946e9.png">


**Info:**
 - Suite version: desktop 23.1.0 (c44e5eaa2820b196794b34e9d50785ef5e37f909)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision ff35c77bad82c7acac1df6245940ebe0d6454642)
 - Transport: bridge 2.0.32

**Comment by hynek-jina** [comment]
I think, that one banner would be better. Like don't display `out-of-sync` if the Tor is disabled (so it cannot be connected anyway)
... But ok

**Comment by bosomt** [comment]
I just tested `enable tor` button multiple times.
Always got this error
`Error: Coinjoin not authorized: Device call in progress`
Follow up issue ? @hynek-jina 


https://user-images.githubusercontent.com/31506317/207844157-c1c40435-2257-4cb5-9952-12c56da2a0bc.mov

**Comment by hynek-jina** [comment]
> I just tested `enable tor` button multiple times. Always got this error `Error: Coinjoin not authorized: Device call in progress` Follow up issue ? @hynek-jina
> 
>  Screen.Recording.2022-12-15.at.12.06.56.mov

@karliatto What do you think.. is it small glitch that can be fixed here or it deserves additional issue?

**Comment by karliatto** [comment]
> > I just tested `enable tor` button multiple times. Always got this error `Error: Coinjoin not authorized: Device call in progress` Follow up issue ? @hynek-jina
> > Screen.Recording.2022-12-15.at.12.06.56.mov
> 
> @karliatto What do you think.. is it small glitch that can be fixed here or it deserves additional issue?

@hynek-jina that glitch is not really related to this issue although it appears here, it is probably something with connect. It deserves new issue.

**Comment by bosomt** [comment]
I will reproduce it and create new issue.

**Comment by hynek-jina** [comment]
@bosomt 
I've created this meanwhile:
https://github.com/trezor/trezor-suite/issues/7236
Feel free to edit it.
