### ISSUE TITLE
Link real values into UI

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6421]
Link real values to:
https://github.com/trezor/trezor-suite/issues/6219
- [x] Distinguish of `private`, `anonymizing`, and `not private` amount aggregations

https://github.com/trezor/trezor-suite/issues/6101
- [x] Amount to be anonymized
- [x] Calculated service fee
- [x] Max mining fee for Recommended and Fast options

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.0 (3817fba23064e18ca9416a0ca0d726f50959576b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision fac4e2f157ca7d0c782b8a55175478e476ea7e28)
 - Transport: bridge 2.0.32
