### ISSUE TITLE
Improved CoinJoin controls

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6423]
https://user-images.githubusercontent.com/26002916/193052987-11d67b35-d6b5-4f83-841a-76668aaa3785.mov

| Default state | On hover | On click | On hover [clicked] |
|---|---|---|---|
| ![State=Default](https://user-images.githubusercontent.com/26002916/193053438-ed0c2524-b855-4dcc-a5f0-98c434e07923.png) | ![State=Variant2](https://user-images.githubusercontent.com/26002916/193053487-2cf93631-7dfb-4b19-bf51-a9a2347c66e8.png) | ![State=Pause](https://user-images.githubusercontent.com/26002916/193053540-a099499a-75f5-4603-a072-74ed3dbf385a.png) | ![State=State4](https://user-images.githubusercontent.com/26002916/193053561-181717bd-3f6b-48d4-893c-73e82d3ae4d4.png) |

**Comment by dahaca** [comment]
We agreed that the "Resume" button underneath "coinjoin paused" is redundant

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.11.1 (8a8808d3c3fd752bde89507d50650bc4bac56647)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
