### ISSUE TITLE
Cannot add Regtest account when not connected to the network

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#6424]
**Describe the bug**
The app breaks when attempting to add an account while not connected to the network.

**How to reproduce**
1. Enable Regtest in Settings without connecting to a network.
2. Try to add a Regtest account.

**Expected behavior**
The solution before #6276 was merged was to stop the _Add account_ button in the modal from rendering. Disabling the button and adding a tooltip would be nice.

**Screenshots**
![chrome-capture-2022-8-29](https://user-images.githubusercontent.com/42465546/193065950-22741126-9c67-4db8-9f7f-7c27867c1ecb.gif)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.10.0 (33b374bb68541ff309eae70c469bd387661ee46a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0
 - OS: MacIntel
 - Screen: 1848x1155
 - Device: model 1 1.11.2 Bitcoin-only (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32
