### ISSUE TITLE
Dev Suite crashes when adding Taproot account with older FW version

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6427]
**Describe the bug**

Expected error according https://wiki.trezor.io/Taproot
`If you're running Firmware version 2.4.2 or lower, you will see the message "Firmware does not have capability to work with taproot". In this case, please update the Firmware.`
But Taproot account is enabled and suite crashes.

I was not able to reproduce issue in **22.9.3** version of Suite.

**Steps to reproduce:**
1. Install firmware older than 2.4.3 /i used 2.4.2 by accident/
2. Add Bitcoin Taproot account
3. Observe suite behavior

**Info:**
 - Suite version: web 22.10.0 (7ea8fe63f034019ea72021346ac0c63cc6c087a3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0
 - OS: MacIntel
 - Screen: 1848x1155
 - Device: model T 2.4.2 Universal (revision 9276b1702361f70e094286e2f89e919d8a230d5c)
 - Transport: bridge 2.0.32

**Screenshots:**
_22.10.0_

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/31506317/193127281-059a4291-2e87-4671-88d3-894bd33f2372.png">

https://user-images.githubusercontent.com/31506317/193127514-38364093-30c0-4368-90ba-a5a581ff5ce3.mov

_22.9.3_

<img width="717" alt="image" src="https://user-images.githubusercontent.com/31506317/193128201-e0e0e507-ca69-4424-bfe5-5d16e1d6aa40.png">

**Comment by sime** [comment]
@bosomt2 Would you expect that Taproot account selection is not possible with old FW?

**Comment by bosomt** [comment]
22.9.3 + 2.4.2 FW - warning that your firmware does not support Taproot / see second screenshot marked as 22.9.3/
22.10.0 + 2.4.2 FW - Suite crashes / see first screenshot marked as 22.10.0/

**Comment by bosomt** [comment]
**QA OK**

already fixed today

22.10.0

<img width="537" alt="image" src="https://user-images.githubusercontent.com/31506317/193340854-b72ff46b-0bdc-4144-9224-916aa112521a.png">

**Info:**
 - Suite version: web 22.10.0 (e2a9bba7d92b42868576fd52f4aed1ded61f36db)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0
 - OS: MacIntel
 - Screen: 1848x1155
 - Device: model T 2.4.2 Universal (revision 9276b1702361f70e094286e2f89e919d8a230d5c)
 - Transport: bridge 2.0.32
