### ISSUE TITLE
getPublicKey does not have scriptType as a param

### ISSUE THREAD

**Issue by nhamilton1** [trezor/trezor-suite#6435]
**Describe the bug**
scriptType is not in the list of params for getPublicKey. However, it is listed as an optional paramater in the [docs](https://github.com/trezor/trezor-suite/blob/develop/docs/packages/connect/methods/getPublicKey.md).

**Info:**
Using @trezor/connect-web, version 9.0.2

**Expected behavior**
I should be able to do something like this:
`
       const getPubKey = await TrezorConnect.getPublicKey({
          path: "m/49'/1'/0'",
          scriptType: "SPENDP2SHWITNESS",
        });
`

**Screenshots**
![Screenshot from 2022-09-29 20-15-54](https://user-images.githubusercontent.com/86306035/193167684-ba9f6e1f-7979-4f51-9d68-bee0a0d71c5a.png)

**Comment by mroz22** [comment]
please try now with version 9.0.3.

**Comment by nhamilton1** [comment]
Updating to version 9.0.3, fixes the issue, scriptType is now available as a param. Thank you!
