### ISSUE TITLE
Add Goerli testnet to Trezor Suite

### ISSUE THREAD

**Issue by mkolar242** [trezor/trezor-suite#6441]
At the end of the year Ropsten testnet will be deprecated and we need to replace it.
Goerli testnet needs to be introduced in Trezor Suite.
https://goerli1.trezor.io/
https://goerli2.trezor.io/
Do not remove Ropsten yet.
Goerli testnet token needs to follow the same user flow as Ropsten -> add account in Testnet coins section.

**Comment by mkolar242** [comment]
Do not remove Ropsten yet.
Goerli testnet token needs to follow the same user flow as Ropsten -> add account in Testnet coins section.

**Comment by jakerockland** [comment]
+1; this is impacting test-ability for us on Goerli for our trezor users @ Art Blocks.

**Comment by karliatto** [comment]
Do we have a logo for this test coin? In my PR https://github.com/trezor/trezor-suite/pull/6571 I am using the one suite has for Ropsten. @sime @hynek-jina

**Comment by sime** [comment]
@karliatto Ropsten icon is fine. We will drop Ropsten in the new year.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 22.11.0 (8d158ba55aa5cf6c90bf398f6f045e96cd0468da)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0
 - OS: MacIntel
 - Screen: 1584x990
 - Device: model T 2.5.3 Universal (revision eb182b923f39111d9307a25a86a49d395c6611b0)
 - Transport: bridge 2.0.31

**Comment by 0ff1cec0ffee10** [comment]
Správně by to mělo být: 

> Add **Goerli testnet** and respective **Derivation path** to Trezor Suite

Vypadá to, že Trezor používá defaultně pro "testnet" derivation path m’/44’/1’/0’/0 pro generování adresy. 

Derivation path:
m/purpose'/**coin_type'/account'**/change/address_index

Těch testnetů je více ...  Ropsten, Goerli, Sepolia, a teď nově Holesky.

Ku příkladu:

- Ethereum (ChainID: 1) - m’/44’/60’/0’/0 0x2b93b9d0ada82b29f622c5a702d1540d66057208
- Ethereum Classic (ChainID: 61) - m’/44’/61’/0’/0 0xedf96026dd5dece0c239d5ef810e21c5414a7322
- Ethereum Testnet (Ropsten ChainID: 3) - m’/44’/1’/0’/0 0x0f75354c1a9a3b88f8f5a87b1e83690e68dcce30 ("TGOR" address)
- Ethereum Testnet (Goerli ChainID: 5) - m’/44’/60’/0’/0  0x2b93b9d0ada82b29f622c5a702d1540d66057208
- Ethereum Testnet (Sepolia ChainID: 11155111) - m’/44’/60’/0’/0  0x2b93b9d0ada82b29f622c5a702d1540d66057208
- Ethereum Testnet (Holesky ChainID: 17000) - m’/44’/60’/0’/0  0x2b93b9d0ada82b29f622c5a702d1540d66057208

Interně můžete zvážit zobrazit toto v Trezor GUI.

Pokud bych se pletl, prosím opravte mně.
