### ISSUE TITLE
Ethereum definitions send from host

### ISSUE THREAD

**Issue by marnova** [trezor/trezor-suite#6442]
Firmware will be removing most of the Ethereum definitions for networks and tokens from the code and they will be send as a part of the messages from host to device.

Definitions will be awailable as a binary blobs at `data.trezor.io`. `trezorctl` and `trezorlib` will be prepared to download them and send them to device. Code for TT,`trezorctl` and `trezorlib` is ready to test (but minor changes may still come, code is still WIP) here https://github.com/trezor/trezor-firmware/pull/2410.

Original issue for this change is here https://github.com/trezor/trezor-firmware/issues/15.

**Comment by hynek-jina** [comment]
Consider old Suite versions with new Firmware behaviour... @mroz22

**Comment by bosomt** [comment]
**QA OK**

tested on web version EAP on staging with LPT token /tested before with stable tokens like PAX or USDT/



![Image](https://user-images.githubusercontent.com/31506317/232847880-e0f6b1bb-2e04-4ff4-bd58-f8cb618bd15b.png)





**Info:**
 - Suite version: web 23.4.2 (5c5b3c885c52c38f3c8115fed07c2faf6a77fc7a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0
 - OS: MacIntel
 - Screen: 2160x1350
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
