### ISSUE TITLE
Sentry Tree Shaking 

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#6444]
configure sentry tree shaking to save some bundle size:
https://docs.sentry.io/platforms/javascript/guides/electron/configuration/tree-shaking/

**Comment by bosomt** [comment]
**QA OK**

https://satoshilabs.sentry.io/releases/23.9.0.desktop.930f73d5973daa7dce5493cd08a09cfcb906c635/?environment=desktop&project=5193825


**Info:**
 - Suite version: desktop 23.9.0 (930f73d5973daa7dce5493cd08a09cfcb906c635)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
