### ISSUE TITLE
Manifest v3 support

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#6458]
Chrome Web Store [stopped accepting](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/) *new* Manifest v2 extensions in June 2022. By June 2023 Manifest v2 extension will be unlisted by Chrome Web Store.

Manifest v3 will be only available to Trezor Connect v9.

### Background
Manifest v3 inches towards increasing user Security, Privacy and Performance. Microsoft Edge and Mozilla Firefox are committed to supporting it.

Related #5307

**Comment by mroz22** [comment]
Here https://github.com/trezor/trezor-suite/pull/7699 we documented a workaroundish way how to work with @trezor/connect in mv3 
We would still like to do better and support @trezor/connect inside service worker but we are not there yet. @sime  please decide if this issue is resolved or not
