### ISSUE TITLE
Add account: Improvements Pt.2

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#6461]
**Follow up for https://github.com/trezor/trezor-suite/issues/4067**

- [x] Animate coins container expansion i na way that doesn't move the content inside

- [ ] Disable coin bubble when empty account already created (as oppose to telling the user in 2 steps by disabling the primary button) › move that tooltip to the coin bubble

<img width="244" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/8d6c3813-002d-4755-8637-9deb8a71c006">

**Comment by komret** [comment]
> * [ ]  Get rid of the "TEST COIN" description

Without it, it may not be clear that a network is a testnet, e.g. Ethereum Sepolia in this scenario. Are you sure we should remove it?
![Screenshot 2023-11-29 at 11 29 52](https://github.com/trezor/trezor-suite/assets/42465546/0f05f39d-36b8-48b2-b00e-63876407c18d)

**Comment by dahaca** [comment]
@komret yeah, at firt I thought we can remove the label only in the testnet section but it's better to keep it everywhere for consistency! Removing from the description.

**Comment by komret** [comment]
> * [ ]  Disable coin bubble when empty account already created (as oppose to telling the user in 2 steps by disabling the primary button) › move that tooltip to the coin bubble

This won't work for coins with `accountType` because it depends on the second step whether you can create an account or not. For the sake of consistency, I wouldn't change this for any network.

**Comment by dahaca** [comment]
Тще

**Comment by bosomt** [comment]
**QA OK**

any chance to align tooltip text ? followup issue ?

<img width="455" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/71c91e61-044b-41f4-ab3a-cf65dcffa3ce">

**Info:**
 - Suite version: desktop 24.1.0 (55eecd28bfcc80d1fbee4e912bae69e4dc2d1763)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.1.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by komret** [comment]
@bosomt Do you mean avoiding the linebreak? I wouldn't worry about that as the string will be different for each language.
