### ISSUE TITLE
Responsive CoinJoin UI

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#6473]
At the moment the Coinjoin page UI is not responsive, since the priority is on streamlining the core functionality and having a narrow screen is highly unlikely on desktop. Before release the UI still has to be made responsive to avoid clearly broken screens in production.

**Comment by hynek-jina** [comment]
Czech version could be improved 🙂 

![Image](https://user-images.githubusercontent.com/26002916/227945570-50475a0f-b790-4fd8-81f9-31ee88574e98.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.4.0 (21653072a7c14c04156cfc6992cec5b582b00a99)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
