### ISSUE TITLE
CoinJoin onboarding modals

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6475]
Follow-up of https://github.com/trezor/trezor-suite/issues/6212
<details open>
<summary>1. Account info</summary>
<br/>

![3](https://user-images.githubusercontent.com/26002916/193206143-a59a1202-2073-47a9-be19-c12e08985b1d.png)

</details>

<details open>
<summary>2. Setting desired anonymity level</summary>
<br/>

- Reuse: https://github.com/trezor/trezor-suite/issues/6116
- Warning in Custom settings of anonymity level appears only when user selects anonymity level 5 or lower.

| ![Group 18800](https://user-images.githubusercontent.com/26002916/193841460-9daac7ce-69b5-4f54-948c-d9f627ad0374.png) | ![2](https://user-images.githubusercontent.com/26002916/193206381-76adf12b-c042-41b2-a5fb-83a822c74332.png) |
| --- | --- |
</details>

**Comment by matejkriz** [comment]
reopenning, I will finish the 2. part – anonymity level setup

**Comment by matejkriz** [comment]
@hynek-jina could you please confirm (and update the description) that we decided to remove CoinJoin onboarding modals (except Tor check)? The change is ready in this PR https://github.com/trezor/trezor-suite/pull/6664

**Comment by hynek-jina** [comment]
@matejkriz 
Yes, please remove the modals from onboarding.

**Comment by STew790** [comment]
**QA OK**

No onboarding present when adding CJ account (except for the Tor warning).

**Info:**
 - Suite version: desktop 22.11.1 (8a8808d3c3fd752bde89507d50650bc4bac56647)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
