### ISSUE TITLE
Implement autoupdater

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#649]
Implement auto-updater:
- [ ] Setup Github auto-updater using electron-builder (https://www.electron.build/auto-update)
- [ ] Update "New Update" modal to fetch latest release from Github and display content.
- [ ] Run update (or postpone it) from "New Update" modal.
- [ ] Update landing page to fetch latest desktop update from Github releases.

**Comment by tsusanka** [comment]
## Security considerations

We need the updater to verify signatures. [Auto-update](https://www.electron.build/auto-update) supports that but @keraf found a worrying [article](https://blog.doyensec.com/2020/02/24/electron-updater-update-signature-bypass.html). And from my limited knowledge of JS I can tell the [code](https://github.com/electron-userland/electron-builder/blob/aa3625d5f6b719b6a7634c4c7ba0aad1ffe7d3d6/packages/electron-updater/src/NsisUpdater.ts#L36) indeed doesn't seem very "security-aware".

Even though the issue looks to be addressed to some degree in newer releases (which we're on), the article recommends Electron Forge. But if I am reading the article correctly it does not support Windows signature verification and recommends `minisign` to do that. @keraf is looking into Forge just now.

> Electron Forge represents a potential well-maintained substitute, which is taking advantage of the built-in Squirrel framework and Electron’s autoUpdater module. Since the Squirrel.Windows doesn’t implement signature validation either, for a robust signature validation on Windows consider shipping the app to the Windows Store or incorporate minisign into the update workflow

**Comment by tsusanka** [comment]
We have agreed we will go with Electron-Updater which is part of Electron-Builder and build some additional checks on top of that later on. To be specified.

**Comment by sorooris** [comment]
What is the trigger for update? I couldn't find it in the pull requests.

**Comment by sorooris** [comment]
FYI The update button is stuck in the _Checking..._ state permanently.
![image](https://user-images.githubusercontent.com/10185314/95694471-8ab5cb00-0c32-11eb-97e6-2f028316d239.png)

> Suite: app 20.10.1 a263552
> OS: Windows 10
> Device: model T 2.3.4 50854b921

**Comment by tsusanka** [comment]
> What is the trigger for update? I couldn't find it in the pull requests.

Yes apologies, there is a process we need to go through to be able to test it out. We'll let you know.

**Comment by tsusanka** [comment]
Tested by me, stick and Raf.

**Comment by chaserene** [comment]
as of updating 22.12.1 -> 23.2.1 (GNU/Linux AppImage), the changelog can't be retrieved.

> Could not retrieve the changelog

screenshot:

![](https://user-images.githubusercontent.com/64873595/220212158-74656772-5b97-4697-a8f0-3a8929e80aaa.png)

**Comment by chaserene** [comment]
update: the changelog appeared after keeping the window open for ~15 minutes. I had uninterrupted network access during this time.

**Comment by sime** [comment]
> update: the changelog appeared after keeping the window open for ~15 minutes. I had uninterrupted network access during this time.

Were you on Tor?

**Comment by chaserene** [comment]
@sime if the updater respects the Suite's network settings, then yes, I was.

**Comment by sime** [comment]
Spotted this when Tor is slow or GitHub blocks some exit nodes. Tricky to solve.

**Comment by chaserene** [comment]
got it. I think a different message would already be an improvement, e.g. "Trying to retrieve changelog through Tor, please wait..."
