### ISSUE TITLE
Suite exports tx history with US time format

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6492]
**Describe the bug**
Suite ignores regional format settings and exports transaction history time in US format.
It's not consistent, sometimes it's correct sometimes not.

**Info:**
 - Suite version: desktop 22.10.1 (18bebb2fe1daf8ec131bcb1e7f271f58aad08b29)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.10.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Screenshots:**
<img width="884" alt="image" src="https://user-images.githubusercontent.com/31506317/194237903-3522bda6-18b3-4432-9562-71109c41f857.png">

**Comment by tomasklim** [comment]
I can confirm. It happens also in the console. Only desktop. Web has no issue.

22.9.3
<img width="314" alt="Screenshot 2022-10-10 at 9 14 20" src="https://user-images.githubusercontent.com/33235762/194815390-5a9545fe-4850-4eb6-93c4-16f939a5241c.png">
22.10.0
<img width="297" alt="Screenshot 2022-10-10 at 9 17 50" src="https://user-images.githubusercontent.com/33235762/194815422-0cd0d5ea-c965-4e09-b368-22ce22651ee0.png">

**Comment by tomasklim** [comment]
Caused by https://github.com/trezor/trezor-suite/pull/6359

**Comment by bosomt** [comment]
**QA NOK**

 - web version vs app /app exports as expected/


<img width="673" alt="image" src="https://user-images.githubusercontent.com/31506317/195906218-12467043-0b1b-4df0-954f-38bb29253810.png">

- and there is inconsistency in GMT, one passphrase says GMT+1 and one passphrase GMT+2

<img width="359" alt="image" src="https://user-images.githubusercontent.com/31506317/195906444-b8707e63-e0cf-4bb1-b90a-d40c0a6978be.png">


**Info:**
 - Suite version: desktop 22.10.2 (4fecea60b5c0f2777708c67640375a753bd49234)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.10.2 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 23.1.0 (c657469ccc2bc2cfb66a4e230013c8ef93d50e55)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.11.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32
