### ISSUE TITLE
Sign tx detail (rbf) - visual glitch

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#6494]
1. create rbf transaction
2. observe checkmark, probably some z-index problem
 
![image](https://user-images.githubusercontent.com/30367552/194273461-be30f269-b30d-43ef-9800-41c484efb2a5.png)
![image](https://user-images.githubusercontent.com/30367552/194273561-56080846-1086-4f99-aedc-8707de4770ba.png)

**Comment by bosomt** [comment]
looks like duplicity of https://github.com/trezor/trezor-suite/issues/5580 to me ;)

**Comment by hynek-jina** [comment]
Thanks @bosomt 
Closing in favour of https://github.com/trezor/trezor-suite/issues/5580
