### ISSUE TITLE
Add links to CoinJoin Terms

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6500]
![Group 18695](https://user-images.githubusercontent.com/26002916/194507643-557f77fd-361d-4568-8901-ecc86a6e9acc.png)

- Update copy
- Add tooltip to first bullet
   - _"Most of the time you can safely disconnect Trezor and the CoinJoin will be paused. However, disconnecting during a critical signing phase can disrupt the CoinJoin round for all participants. You won't lose any money, but you may be banned from some upcoming CoinJoin rounds. All of your funds remain spendable."_
- Link to Trezor Suite Terms: TBD
- Link to zkSNACKs Coordinator Terms: https://github.com/zkSNACKs/WalletWasabi/tree/master/WalletWasabi/Legal/Assets

**Comment by komret** [comment]
Is the link to zkSNACKs terms final? There are two files with very similar content.

**Comment by hynek-jina** [comment]
@komret Please use the second (newer) file:
https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/Legal/Assets/LegalDocumentsWw2.txt

**Comment by bosomt** [comment]
@hynek-jina is there a follow up issue First Terms link ends in https://trezor.io/

<img width="485" alt="image" src="https://user-images.githubusercontent.com/31506317/197178713-79fe8945-0854-47ef-9dab-3429bc8cf33c.png">

**Comment by bosomt** [comment]
**QA OK **


**Info:**
 - Suite version: desktop 22.11.0 (da1945300f7e7497d23eef27030f0c31a6efb43b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: 
 - Transport: bridge 2.0.32
