### ISSUE TITLE
Trezor connect init connection settings, open connect trezor popup in new window instead of new tab

### ISSUE THREAD

**Issue by punithbm** [trezor/trezor-suite#6506]
Trezor instance is always opening in the new tab even when passing the popup as true in the connection settings as shown below.
```
TrezorConnect.init({
    manifest: {
      email: 'abc@xyz.com',
      appUrl: 'https://xyz.com',
    },
    popup: true,
  });
```

Is there any way to open the Trezor connection request in the new window instead of the tab

**Comment by mroz22** [comment]
At the moment, no, there is no way to open a new window instead of tab.
