### ISSUE TITLE
Misleading validation message in Send section

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#6514]
Just a nitpick ✨

**Describe the bug:**

Misleading validation message.

**Info:**
-   Suite Version: web

**How to reproduce**
1. Go to send section
2. Paste -1 to the amount input

![image](https://user-images.githubusercontent.com/3112191/194918494-b50e4ca8-baf4-4952-b0f8-6f5287da198e.png)

**Comment by matejkriz** [comment]
resolved by https://github.com/trezor/trezor-suite/issues/5928

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.5.0 (0f6b428936d1ab6efe14e9e2fb2cb4d402bfdc67)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.6.0 Universal (revision 3b59d71093a56b7f396bd4aa6b5334a940223b67)
 - Transport: BridgeTransport 2.0.32
