### ISSUE TITLE
Nice to have fixes

### ISSUE THREAD

**Issue by TomasZorvan** [trezor/trezor-suite#652]
# Show Log
- [x] when you click 'Show Log' it should scroll you to the log.

# Dashboard
- [x] negative number of total tx is displayed in XRP Testnet card.
![xrptestnet-negative-number-of-tx](https://user-images.githubusercontent.com/7147101/66759002-b4ada380-ee9f-11e9-88db-cbaa907b0fbc.png)

# Application settings
- [x] when you set local currency in App settings it should be considered main currency for whole wallet. I changed it to CZK but the send form is still is USD.

# Passphrase
- [x] Entered passphrase is asked to be saved as a password in Chrome

# Transactions
- [x] incorrectly style Info notification about received tx. _(edit: will be resolved after UI/UX overhaul)_
![weird-3-infos](https://user-images.githubusercontent.com/7147101/66759215-20900c00-eea0-11e9-91ce-24ac2622f668.png)
- [x] incorrect date order of txs receive date groups.
![incorrect-txs-date-grouping](https://user-images.githubusercontent.com/7147101/66759188-0c4c0f00-eea0-11e9-8fbe-1f12d5165ccc.png)
- [x] incorrect date of tx: mismatch between blockbook and displayed date in suite
- [x] should hide balances also hide balances of every tx? 

# Receive
- [x] maybe display notification after user adds 20 fresh addresses why he cannot generate new one until he uses one of the newly generated address

# Add Account
- [x] when I add any new account `Legacy accounts` accordion gets opened. It is opened while loading accounts after then it is closed. Maybe it can be closed until user opens it specifically.

# Summary
- [x] When on testnet instead of showing `N/A` for balance and rate just show balance in testnet currency

**Comment by slowbackspace** [comment]
dates in tx history fixed in https://github.com/trezor/trezor-suite/pull/653

**Comment by szymonlesisz** [comment]
dashboard fixed in #663

**Comment by szymonlesisz** [comment]
ad. Passphrase - i don't think we can fix this :( we're struggling with this for years now

**Comment by slowbackspace** [comment]
fixed default fiat currency select in send form https://github.com/trezor/trezor-suite/pull/668

**Comment by mroz22** [comment]
>  should hide balances also hide balances of every tx?

 imho not.

**Comment by mroz22** [comment]
> when you click 'Show Log' it should scroll you to the log.

I would suggest displaying log in a modal

**Comment by keip** [comment]
added Log to modal in #748
