### ISSUE TITLE
sat LTC in notification instead of LTC

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6520]
**Describe the bug**
We are not using smaller units on LTC. However if user switch to Satoshis on Bitcoin account it erroneously starts showing up in notifications of LTC transactions `sat LTC`. It should stick to `LTC`.

<img width="442" alt="image" src="https://user-images.githubusercontent.com/26002916/195051974-23281b1c-e203-4dc1-893e-21db7548403b.png">

**Comment by bosomt** [comment]
I was able to reproduce issue.
Its related to notification only /suite and Trezor shows transaction as expected / and it's happening to BTClike coins.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/31506317/195322449-319366e0-ae8a-4a00-a2cd-012e4a23a3be.png">

**Info:**
 - Suite version: desktop 22.10.1 (6ed234b6b8df5ea61f3de505d35105bf4816522e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.10.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA OK**

`1 DOGE sent from Dogecoin #1`
`0.91911765 NMC sent from Namecoin #1`
`0.12594839 LTC sent from Litecoin #2`
`5061 sat sent from Bitcoin #1`
`111111 sat TEST sent from Bitcoin Testnet #1`

**Info:**
 - Suite version: web 22.11.0 (7b28c2e4e9a951990adefa38283f5e246185c10d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32

**Comment by bosomt** [comment]
I just noted one thing

` 5061 sat sent from Bitcoin #1` does not say sats of what was sent, all other notifications have coin info except BTC :)

@dahaca @hynek-jina issue or expected ? :) 

<img width="425" alt="image" src="https://user-images.githubusercontent.com/31506317/195788133-16c8aadc-d856-44b1-bcae-4e8f3bf26f03.png">

**Comment by hynek-jina** [comment]
@bosomt It should be consistent.. so please open an issue

**Comment by sime** [comment]
Do we have that notation anywhere else in suite? `5061 sat BTC sent from Bitcoin #1` seems odd to my eyes.

**Comment by hynek-jina** [comment]
Here would be the copy rather `Transaction 5,061 sat on Bitcoin #1 successfully confirmed` to be consistent.
But it feels a little weird. 
@b-irving What do you think?

**Comment by b-irving** [comment]
@hynek-jina I'd go with your suggestion for the sake of consistency.

**Comment by hynek-jina** [comment]
Followup issue: https://github.com/trezor/trezor-suite/issues/6565
