### ISSUE TITLE
Custom max mining fee

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6522]
Solve the communication of `max mining fee` selected in custom setup of CoinJoin between Suite and Trezor device.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.0 (54da46e34ad128b493cc1f43112dd9ebc84434e2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision fac4e2f157ca7d0c782b8a55175478e476ea7e28)
 - Transport: bridge 2.0.32
