### ISSUE TITLE
(feat) (Desktop) VPN Kill Switch (Network Interface setting)

### ISSUE THREAD

**Issue by trymeouteh** [trezor/trezor-suite#6527]
I recently discovered that qBittorrent essentially has a [VPN Kill Switch feature](https://www.ghacks.net/2016/03/23/qbittorrent-block-transfers-vpn-disconnect/) built into the client which will kill its connection if it detects your VPN has disconnected. VPN kill switches from VPN clients for the desktop are not fully reliable as they can often fail and you can still connect to the internet with a unencrypted connection with your IP exposed.

I would like to purpose adding this feature in Trezor Suite settings on desktop. This way if your VPN disconnects, Trezor Suite will also lose internet access too. There has been many times my VPN disconnects without me knowing while I was using my wallet.

**Comment by sime** [comment]
Hi @trymeouteh 

Thanks for the feedback. We will track this feature internally for now, but it's interesting and valid suggestion.

Meanwhile, we are improving Tor handling, so with Tor enabled, Trezor Suite won't launch until Tor connects.
