### ISSUE TITLE
Upgrade @testing-library/react

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#6529]
React Testing Library v13 has support for React 18. However, upgrading it breaks some tests as discussed in #6437. There should be no relevant breaking changes in the API, not sure what is causing the problems.

One of the failing tests is `useDiscovery`, see #4711.

Related upgrade issues: #5563, #6025

**Comment by hynek-jina** [comment]
I assume there is no requirement on QA, right?
Moving to `Approved`
