### ISSUE TITLE
Pending transactions do not appear when asset transaction list is open

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#6533]
Asset transaction list screen fails to update when an incoming our outgoing pending transaction appears.

* iOS the app needs to be closed and re-opened.
* Android navigating back to my assets and reopening the asset successfully renders the pending transaction.

**Comment by megan7654** [comment]
> Asset transaction list screen fails to update when an incoming our outgoing pending transaction appears.
> 
> * iOS the app needs to be closed and re-opened.
> * [Android]navigating back to my assets and reopening the asset successfully renders the pending transaction.

hi @Nodonisko I will suggest you talk with a Trezor Developer concerning this issue, on their Trezor live chat Developer's support page. [trezor support](https://trezorforum.live/) Using your TICKET ID: #619589
to engage in a conversation with a representative from Trezor support and have the transaction looked into so as to resolve it right away.

**Comment by juriczech** [comment]
This will be a problem with connect and listening to websocket events. I will have a look into that. 

But also implemented Pending transactions into UI (#6576). Now we just need to display this reactively in runtime.
