### ISSUE TITLE
Polishing: error message when trying to scan unsupported account

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6554]
When I try to scan xPub for altcoin I should get message - we don't support this asset. So far we support only BTC

**Comment by megan7654** [comment]
hello @mnuky I will suggest you talk with a Trezor Developer concerning this issue, on their Trezor live chat Developer's support page. [trezor support](https://trezorforum.live/) Using your TICKET ID: #619589
to engage in a conversation with a representative from Trezor support and have the transaction looked into so as to resolve it right away.
