### ISSUE TITLE
Model R in Suite

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#6567]
What will need to adapt: 

- suite -> settings -> device -> display rotation
- suite -> settings -> device -> background
- connect -> firmware update
- components -> [confirm on device](https://github.com/trezor/trezor-suite/blob/develop/packages/components/src/components/prompts/ConfirmOnDevice/index.tsx#L140)
- all places where we have stuff like `major_version === <number>`

Fill the list, there are likely more

**Comment by Nodonisko** [comment]
Maybe can we also add "imported device" which will be similar process

**Comment by STew790** [comment]
**QA OK**
Tested after discussion with @matejkriz Sanity tests on Suite with both devices and everything was OK.

**Info:**
 - Suite version: desktop 23.2.1 (bcfbc9ffb59b51f6c7ecb58d529769ca0db2f7b1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: BridgeTransport 2.0.32
