### ISSUE TITLE
SegWit accounts identified as DEFAULT ACCOUNTS in accounts panel

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6577]
**Describe the bug**

SegWit accounts identified as `DEFAULT ACCOUNTS` in recent version of Suite

I was able to reproduce it in app and in web version of Suite.

**Steps to reproduce:**
1. Load 22.10.2 version and device with all seed
2. Load 22.9.3 version and device with all seed
3. Compare accounts panel on left

**Info:**
 - Suite version: web 22.10.2 (4fecea60b5c0f2777708c67640375a753bd49234)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0
 - OS: MacIntel
 - Screen: 1584x990
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Expected result:**

**Actual result:**
A clear and concise description of what actually happens.

**Screenshots:**
<img width="266" alt="Screenshot 2022-10-17 at 14 11 22" src="https://user-images.githubusercontent.com/31506317/196174437-c6efee40-71ee-4a30-abe8-223a24fc8b27.png">
<img width="308" alt="Screenshot 2022-10-17 at 14 11 00" src="https://user-images.githubusercontent.com/31506317/196174450-51a78f2e-1d97-4198-8531-edd15584de16.png">

**Comment by sime** [comment]
Flagging this as high priority for the current sprint. Any hint where this might have come from @matejkriz ?

**Comment by hynek-jina** [comment]
We have unified the logic of account display in https://github.com/trezor/trezor-suite/issues/5873
But you are right that we should stick to `SEGWIT` instead of `DEFAULT` accounts...

**Comment by sime** [comment]
> But you are right that we should stick to `SEGWIT` instead of `DEFAULT` accounts...

Can we keep the previous behaviour of no label?

**Comment by matejkriz** [comment]
As @hynek-jina mentioned we unified that because of the new CoinJoin account type that should be above this default group. 

And we call it DEFAULT instead of SEGWIT because not all coins has SEGWIT accounts...

**Comment by hynek-jina** [comment]
I'm closing this issue for now.. 
@sime Let's discuss that if needed..
