### ISSUE TITLE
suite-native: Display portfolio value

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#6582]
Should be the current value of all assets reduced into single value. Already implemented in suite, so have a look if some of the logic could be reused.

![Image](https://user-images.githubusercontent.com/36101761/196332133-7ebdf359-a930-45a9-9567-c13a44fd5b68.png)

**Comment by juriczech** [comment]
@sime @Nodonisko Will this work same as in suite?

**Comment by sime** [comment]
The graphs should be united from mobile to desktop

**Comment by juriczech** [comment]
@sime This is just regarding the number at the top.

**Comment by sime** [comment]
Yes, desktop needs a single portfolio value.

**Comment by Nodonisko** [comment]
We already have this value it's literally last point value in graph. Also I think number should change when swiping finger through graph like it do in Revolut.

**Comment by Nodonisko** [comment]
Also please coordinate with @bouchja1 because this header with with values is directly related to graph and also should be in graph package.

**Comment by juriczech** [comment]
Okay, so this should be part of graph tasks then, so I will close this issue. @Nodonisko @bouchja1
