### ISSUE TITLE
Unify CoinJoin icons

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6586]
In account balance overview change icon of `Private` funds (from closed eye to check mark). And make it green.
![Snímek obrazovky 2022-10-18 v 11 44 32](https://user-images.githubusercontent.com/26002916/196409368-50aed18a-4ffa-4c8e-9dd1-02d23e87ba43.png)

In transaction history change icon of join transaction (from recycle arrows to shuffle)
![Snímek obrazovky 2022-10-18 v 11 44 49](https://user-images.githubusercontent.com/26002916/196409344-cdc0f56b-f039-405e-9017-7ceb64b39c26.png)

**Comment by dahaca** [comment]
Why changing the closed eyed to a checkmark? 🤔

**Comment by hynek-jina** [comment]
To be consistent with https://github.com/trezor/trezor-suite/issues/6215

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.0 (5d1bc34fcbf5ed351a680893b6586cb8bbca8c08)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision fac4e2f157ca7d0c782b8a55175478e476ea7e28)
 - Transport: bridge 2.0.32
