### ISSUE TITLE
Tor friendly usage

### ISSUE THREAD

**Issue by Hercules1122** [trezor/trezor-suite#6588]
Hello guys, 

I am new to the Trezor community and I really like the Trezor Wallet and how the Team offers Tor friendly usage. 

I first wanted to get the Trezor running on Tails OS.
Than figured out that both the Suite App and Webpage doesn't work on Tails anymore.

Than I tried to connect the wallet via Tor Browser on Windows.
Which I thought is going to work when I saw the Trezor Bridge is connected. 
Now reading that the Webpage still says Trezor Bridge is not running. 
So it doesnt work on Tor Browser on Windows any more as well. 

Just checking with the Suite App on Windows Tor connection always breaks to the backend.

I really hope that the Trezor Team focus on fixing those issues. 
That we have at least Trezor on Tor Browser on Windows working and if possible the nicest would be to have Trezor on Tails OS again.

I think those points are really important to ensure a stable and safe Tor connection to the wallet if needed. 
If the Trezor Team is keeping this up, they are kind of outstanding in the whole crypto community to have importance of Tor friendly usage. I guess this is appreciated by many others as well.

Just wanted to leave my opinion on here and hope that the Trezor Team is working on that to keep it up on high standard. 

Thank you very much!

**Comment by hynek-jina** [comment]
@Hercules1122 
Thank you, but your points are already tracked in mentioned issues, right?

**Comment by Hercules1122** [comment]
All right, thanks for noticing! :)
