### ISSUE TITLE
Addresses in Coin Control should use monospace font

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#6590]
We use monospace font for addresses (in transaction history), but in Coin Control a variable-width font is used.

I expect monospace font to be used here as well (and in future versions of the Coin Control dialog such as one being implemented in https://github.com/trezor/trezor-suite/issues/6215)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.11.0 (55f7ea4f0f0c544e300dc1d8a080d558404ae876)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0
 - OS: MacIntel
 - Screen: 1584x990
 - Device: model T 2.5.3 Universal (revision eb182b923f39111d9307a25a86a49d395c6611b0)
 - Transport: bridge 2.0.32
