### ISSUE TITLE
Hiding Ethereum tokens

### ISSUE THREAD

**Issue by mkolar242** [trezor/trezor-suite#6595]
[Design in Figma](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?node-id=7776%3A16586&mode=dev)

**Spec:** 
Please use current component from Empower. 

As a user, I would like to have the ability to hide whether scam airdrop tokens or zero balance tokens.

Implementation for SOL, ETH, MATIC and ADA. 
Leave the Trade button for now, display just the receive and send buttons.
Tokens state (recognized/unrecognized) should be reflected also in the Send select dropdown menu.

Save the info about what is hidden into labeling. All related transactions to hidden tokens should be blurred.

**Settings**
- settings to be available per account
- stored files to be encrypted

**Comment by 420-Bits** [comment]
Please we need this!! ASAP!!

**Comment by quickplaymobile** [comment]
Proposal to also remove the transactions tx for hidden tokens and probably implementing a curated list for automatically blocking them.
https://www.bitdefender.com/blog/hotforsecurity/new-address-poisoning-crypto-scam-on-the-rise-metamask-warns/

**Comment by tomasklim** [comment]
@mkolar242 
- token price is missing in the design
- should it open etherscan or blockbook
- stored files to be encrypted, I think we should discuss this. Not straightforward and maybe we want it for whole Suite @sime 
- how about ERC755 and ERC1155

**Comment by mkolar242** [comment]
@tomasklim 
- we show token amount + token value in fiat -> we have this in design
- open blockbook
- no plan to show ERC721 and ERC1155 in the tokens list
- lets discuss the files encryption next week
- I will update the spec as we also need to remove txs from the tx history

**Comment by tomasklim** [comment]
> we show token amount + token value in fiat

As a user, I would like to know token price if available. This force me to do "complex" math 😀 We show price of BTC, ETH,.. but we will miss token price, which is not even available in blockbook so I will have to go to coingecko/coinmarketcap

> I will update the spec as we also need to remove txs from the tx history

Please discuss this with @sime

**Comment by tomasklim** [comment]
related #3957 #3898

**Comment by tomasklim** [comment]
Any plan with this `Add token` modal?

![Image](https://user-images.githubusercontent.com/33235762/235877954-f3ed1343-c73b-4e02-ae15-ffccfb324e18.png)

**Comment by Hannsek** [comment]
What about it?

**Comment by dbarobin** [comment]
Please, I desperately need this feature. The fake USDT tokens are so annoying.

![SCR-20230509-b2y](https://user-images.githubusercontent.com/3949252/236967811-01e9af4b-16df-48fc-b2bc-540825a7f51f.png)

**Comment by sime** [comment]
> Any plan with this `Add token` modal?
> 
> ![Image](https://user-images.githubusercontent.com/33235762/235877954-f3ed1343-c73b-4e02-ae15-ffccfb324e18.png)

My understanding is we can drop it since blockbook was updated and its original use case is gone.

**Comment by HaydenOtto** [comment]
Do the devs even use their own wallet? Or do they simply not care about this because they are Bitcoin maxis and this issue only effects Ethereum plebs? This is the single greatest problem I have with Trezor walets and it has been ongoing for years now. Can't believe nothing has been done about it and from a developer perspective it shouldn't be hard to implement the ability to hide tokens from the UI.

**Comment by dbarobin** [comment]
> Do the devs even use their own wallet? Or do they simply not care about this because they are Bitcoin maxis and this issue only effects Ethereum plebs? This is the single greatest problem I have with Trezor walets and it has been ongoing for years now. Can't believe nothing has been done about it and from a developer perspective it shouldn't be hard to implement the ability to hide tokens from the UI.

Totally agree. Don't ignore the feelings of users because of your own beliefs. It's not that Trezor doesn't support Ethereum.

**Comment by dbarobin** [comment]
OMG, I can't stand it anymore. I think it would be a good idea to launch the hidden token feature as soon as possible.

![SCR-20230613-mqd](https://github.com/trezor/trezor-suite/assets/3949252/d96020e7-3cbc-47c6-8e21-04aca8308e42)

**Comment by Hannsek** [comment]
We are currently working on it. However, there are plenty of other features. Please be patient. 🙏🏻

**Comment by tomasklim** [comment]
![Screenshot 2023-07-20 at 10 40 06](https://github.com/trezor/trezor-suite/assets/33235762/af9ec679-f876-494d-b790-dfcf6fc073ac)
Long token symbols does not fit screen
![Screenshot 2023-07-20 at 10 40 28](https://github.com/trezor/trezor-suite/assets/33235762/64263ded-f34b-4397-b115-39deca101e4d)

**Comment by Hannsek** [comment]
notes:
- automatically hide transactions (if any) with hidden tokens
- sort tokens according to fiat value

**Comment by HaydenOtto** [comment]
@Hannsek are the above features you mentioned implemented? I can't see anything related to that and I am on the latest firmwares.

**Comment by Hannsek** [comment]
Not yet.

**Comment by dbarobin** [comment]
I can't even filter which is the correct USDT when transferring funds.

![SCR-20231119-m6h](https://github.com/trezor/trezor-suite/assets/3949252/3fcdfe91-511b-4baf-883b-27f0724fd5d9)

**Comment by nzjrs** [comment]
It's absolutely astounding this bug has not yet been given high priority, and fixed.

**Comment by xTnK** [comment]
Bump. Same issue as described above.
It's getting out of hands, I have some wallets with 17 different USDT tokens.

<img width="533" alt="wallet1" src="https://github.com/trezor/trezor-suite/assets/67328034/904cd911-17cc-41da-9c12-80690412fc0c">
<img width="558" alt="wallet2" src="https://github.com/trezor/trezor-suite/assets/67328034/f9a5755a-b88f-4464-a3ad-089411f970d6">

**Comment by tomasklim** [comment]
TODO: do not fetch fiat rates for tokens without definitions <img width="673" alt="Screenshot 2024-01-02 at 5 02 55" src="https://github.com/trezor/trezor-suite/assets/33235762/3c83b87d-f780-4c00-8e82-cbc7e7bc628c">

**Comment by nzjrs** [comment]
What do we all think, this bug going unfixed for years has resulted in how many figures of users being phished? 4, 5, 6 figs of losses you think?

 Lets vote with reaccs. 
 
 * :rocket: = 6 figs
 * :eyes: = 5 figs
 * :+1: = 4 figs

**Comment by marian001** [comment]
+1

**Comment by quickplaymobile** [comment]
![pic 2](https://github.com/trezor/trezor-suite/assets/11901639/d4752742-73bf-4ddc-a9c3-5606792302ed)
![pic 1](https://github.com/trezor/trezor-suite/assets/11901639/e68682dc-b2ab-4355-8554-810e59c08c03)
It becomes increasingly harder to protect ourselves. Please help us protect ourselves, please help us hide them.

**Comment by tomasklim** [comment]
Together with feature what is hidden,... we can store #3883

**Comment by Hannsek** [comment]
Closing in favour of https://github.com/trezor/trezor-suite/issues/12165
