### ISSUE TITLE
Tx detail visual improvement

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#6597]
there is a hover effect on "my inputs..". consider some inner padding. 

![image](https://user-images.githubusercontent.com/30367552/196639872-36c6575b-dd05-45f8-afba-040e64aff805.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.0 (da1945300f7e7497d23eef27030f0c31a6efb43b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision eb182b923f39111d9307a25a86a49d395c6611b0)
 - Transport: bridge 2.0.32
