### ISSUE TITLE
trezor-addres-validator goerli 

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#6599]
https://github.com/trezor/trezor-address-validator

should be updated to supppot tGOR

**Comment by karliatto** [comment]
tGOR addresses are exactly the same as ETH, so I do not think there is nothing needed to modify in https://github.com/trezor/trezor-address-validator

I created this tests using tGOR as well as tROP addresses generated by trezor-suite and they are 100% ethereum valid addresses.

I was discussing it with @martinboehm to confirm it and about getting rid of tGOR and use the symbol ETH even for the testnet, @sime do you know more about it?

**Comment by sime** [comment]
@karliatto Plan is to sync the change with the upcoming FW release in March. Then all testnets across our whole stack will report ETH.

**Comment by mroz22** [comment]
In that case we can close it, thans 🙏
