### ISSUE TITLE
Components - ts error in console

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#66]
Simply by including components into another project, I get this error: 

```
node_modules/trezor-ui-components/lib/components/Textarea/index.d.ts(3,41):
TS7016: Could not find a declaration file for module 'react-textarea-autosize'. '/home/martinvarmuza/repos/trezor-onboarding/node_modules/react-textarea-autosize/dist/react-textarea-autosize.cjs.js' implicitly has an 'any' type.
  Try `npm install @types/react-textarea-autosize` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-textarea-autosize';`

```

**Comment by slowbackspace** [comment]
Have you tried `yarn add --dev @types/react-textarea-autosize`? 😀 
We'll probably soon remove dependency on `react-textarea-autosize` since we are not really using its features anywhere.

created task https://github.com/trezor/trezor-suite/issues/71

**Comment by mroz22** [comment]
Btw shouldnt type declarations be part of dependencies and not dev dependencies? 

https://github.com/trezor/trezor-suite/blob/2e38bad78cbdad5c85d045d0100fd046b0abce5e/packages/components/package.json#L41-L44

**Comment by slowbackspace** [comment]
https://github.com/trezor/trezor-suite/pull/83
