### ISSUE TITLE
Recovery seed process - Trezor one - input field is erasing typed characters

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6601]
If I do the recovery of my Trezor One and go through Standard recovery and start to type the words, sometimes the input field erases what I type. Attached screen recordings.

https://user-images.githubusercontent.com/84183817/196628571-a8955d01-3100-4093-8440-3848b7b99fcc.mov

https://user-images.githubusercontent.com/84183817/196628572-c5d98d52-b7b5-4748-8c14-d7ccf9d0fcac.mov

Suite version: Version 22.10.1 (22.10.1.22288)
Device: MacBook Air

**Comment by bosomt** [comment]
I was able to replicate in last months but but only from time to time, never find out whats causing this issue.

**Comment by sime** [comment]
Fighting this again. Bumping the priority

https://user-images.githubusercontent.com/216917/204571329-d697dfad-2a7a-425f-ac25-b35701b287aa.mp4

**Comment by matejkriz** [comment]
may be related https://sentry.io/share/issue/106652921ac2437d8f6aeca3e78780e1/

**Comment by bosomt** [comment]
**QA NOK**

it still happens from time to time ;(

https://user-images.githubusercontent.com/31506317/222019347-7c730b8b-f6ec-4a70-b6e8-f7d53588e6d7.mov

**Info:**
 - Suite version: desktop 23.3.1 (8f0a5a67bd1cd0cf95724ee1468ee6ad70aead60)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.1 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.12.1 Universal (revision 7430850da5258e5d19ae55bac94a31447a9d4d14)
 - Transport: BridgeTransport 2.0.32

**Comment by sime** [comment]
@bosomt You are testing the frozen app right, not the `feat/recovery-seed-process-upgrade` branch

**Comment by bosomt** [comment]
@sime yes tested on current RC /i was not testing this issue, just recovering device, i had no idea that there is branch that can fix this issue /

**Comment by sime** [comment]
@tomasklim Is this unblocked now?

**Comment by tomasklim** [comment]
@trezor/qa 
Please test:
- `2.0.32+ bridge`, `2.0.27 bridge`, `WebUSB`
- `T1` + `TT`
- advanced and normal recovery in onboarding, check backup in app
- try to click all close/abort buttons in 🔝  and also on device

**Comment by bosomt** [comment]
**QA OK**

https://www.notion.so/satoshilabs/input-field-is-erasing-typed-characters-Issue-6601-c5fc2b0ecd3748679965543989ce082b?pvs=4
