### ISSUE TITLE
Disable CoinJoin for Trezor One

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6609]
CoinJoin account and all related functionality will be available for `Trezor T` only, not for Trezor One.
Prevent all potential conflicts.

Disable add CoinJoin account button with message:
_"CoinJoin is supported only on Trezor Model T"_

note: _We can enable access to CoinJoin account later without CoinJoin functionality, but not for the MVP_

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.11.0 (91cc9ae7ad79fee426a16d2f2553a2017d390572)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision eff8e08a9c43a85de8a6ce5afc09b921e3733e26)
 - Transport: bridge 2.0.32
