### ISSUE TITLE
Prepare option to disable whole CoinJoin for all users

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6610]
Via messaging system we need to transfer some value into Trezor Suite.
Based on this flag we need to turn off specific elements.
- turn-off the option to start CoinJoin
- unregister from running CoinJoin
- display information about turning off the CoinJoin

notes from discussions:
https://www.notion.so/satoshilabs/feature-flags-in-Suite-76741db4b0434b0dbfaf6a631424158b

    - disable CoinJoin button
    - cancel running CoinJoin (wait for end of critical phase if already entered)
    - Communicate reason of the disabled button. _Use already existing element:_
    - ![Snímek obrazovky 2022-12-02 v 9 35 24](https://user-images.githubusercontent.com/26002916/205250875-cf69f6d3-fdd5-48d8-b85c-7607d2a09c0a.png)

**Comment by hynek-jina** [comment]
We should be able to disable participation in CoinJoin based Suite version (commit)

**Comment by hynek-jina** [comment]
I have updated the description...

**Comment by andrewkozlik** [comment]
> We should be able to disable participation in CoinJoin based Suite version (commit)

Similarly, we should also be able to disable participation in CoinJoin based firmware version. In case we release a faulty firmware or in case of some protocol update which does not work with older firmwares.

**Comment by matejkriz** [comment]
> > We should be able to disable participation in CoinJoin based Suite version (commit)
> 
> Similarly, we should also be able to disable participation in CoinJoin based firmware version. In case we release a faulty firmware or in case of some protocol update which does not work with older firmwares.

Yes, we can do that 👌

**Comment by bosomt** [comment]
**QA OK**

tested on version 22.1.0 on Windows and MacARM /running, startling and idling coinjoin/
after deploy of https://github.com/trezor/trezor-suite/pull/7508

**Running **
![image](https://user-images.githubusercontent.com/31506317/215811657-a36c2d79-ed59-479f-80d7-a3ba89568c3f.png)

**Idling**
![image](https://user-images.githubusercontent.com/31506317/215812954-bccd56e7-6be0-461c-81a8-818b9ca832fd.png)
