### ISSUE TITLE
Move CoinJoin to Testnet

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6614]
Migrate CoinJoin functionality from Regtest to Testnet

**Comment by STew790** [comment]
**QA OK**
CJ is available now on Testnet :tada: .

**Info:**
 - Suite version: web 22.11.1 (8a8808d3c3fd752bde89507d50650bc4bac56647)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
