### ISSUE TITLE
Display CoinJoin-related values received from coordinator

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#6625]
Display values from `coinjoin.clients` added in #6563.

**Comment by STew790** [comment]
**QA OK**
Values from coordinator shown correctly.
![image](https://user-images.githubusercontent.com/48477147/201659337-2917e176-2ab6-404e-9245-50b9cd0dd4b8.png)

**Info:**
 - Suite version: desktop 22.12.0 (2f4c0db8c499ac7541080d4aad5707674a21e45f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
