### ISSUE TITLE
Next CoinJoin round counter

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6627]
Improve the precision of countdown counter for the next CoinJoin round to `seconds` .

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.1 (36517f2367056ec69f25858ddd96684364d1dbc5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
