### ISSUE TITLE
Update CJ Trezor Suite terms

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6631]
Followup of https://github.com/trezor/trezor-suite/issues/6500

Please update link to Trezor Suite terms to: https://data.trezor.io/legal/coinjoin-terms.pdf

**Comment by hynek-jina** [comment]
Here is the source for the terms:
https://data.trezor.io/legal/coinjoin-terms.pdf

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.11.1 (8a8808d3c3fd752bde89507d50650bc4bac56647)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
