### ISSUE TITLE
replace links to old wiki.trezor.io by new help center links https://trezor.io/learn

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#6647]
list of links to change in CSV:
[Trezor Suite links 82079077ed634dc6ad43434df24325ab 3 (2).csv](https://github.com/trezor/trezor-suite/files/9852680/Trezor.Suite.links.82079077ed634dc6ad43434df24325ab.3.2.csv)

**Comment by matejkriz** [comment]
there is a separate issue for links inside Suite Guide https://github.com/trezor/trezor-suite-guide/issues/3

**Comment by komret** [comment]
**QA:** All links previously leading to wiki are now pointing to knowledge base. Some of them are dependant on device type, e.g. packaging of [T1](https://trezor.io/learn/a/authenticate-trezor-model-one) and [TT](https://trezor.io/learn/a/authenticate-trezor-model-t). Guide is unaffected by this.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (daaf4fbacbc8d1f613f6b4d94de04451b9d9923d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.8.2 Universal (revision 3c19e3167d69902305a27f10e43abb5fc7a0254d)
 - Transport: bridge 2.0.32
