### ISSUE TITLE
Remove `Anonymizing` category from CoinJoin account

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6653]
![Snímek obrazovky 2022-10-25 v 8 09 57](https://user-images.githubusercontent.com/26002916/197707257-8e38d4b3-3bd5-454d-aed0-d3c57345b079.png)

Consider renaming and change of icon from `Not private` to `Being anonymized` when is the CoinJoin in progress
![Snímek obrazovky 2022-10-25 v 8 11 59](https://user-images.githubusercontent.com/26002916/197707222-217225b9-3af9-411d-aee1-19bee7494f8e.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (8564941f51e20658d0286dc26e14858d8ee0d300)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
