### ISSUE TITLE
 Direct coinjoin account discovery from one button in Accounts page

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6654]
Access coinjoin account on one click from Accounts page. Visible for all Bitcoin users.

Applies on Bitcoin network only (not for Testnet). 

![Normal — Overview](https://user-images.githubusercontent.com/26002916/199762987-c3ac0763-92e3-40dc-8e0d-dc3ff0ce7172.png)

_Coinjoin account will be still discoverable from general `add account` flow. For testnet it will remain as an only option_

**Comment by hynek-jina** [comment]
~~Blocked by: https://github.com/trezor/trezor-suite/issues/6841~~ → not anymore

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
