### ISSUE TITLE
Update app modal is overlapped by Enter passphrase modal.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6655]
**Describe the bug**
See video, sometimes you have to go to settings to finalize app update beacause enter passphrase modal cancels update modal.

**Steps to reproduce:**
1. Start older version of Suite that asks you to update
2. Connect device and wait till it starts and its recognized by Suite
3. Click on Update modal
4. Observe Enter passphrase modal.

**Info:**
 - Suite version: desktop 22.9.3 (2b9595fdfee9d36935d72af4af536d2fe4742f5e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.9.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.11.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Screenshots:**
https://www.youtube.com/watch?v=jV89GNT9dVI

**Comment by matejkriz** [comment]
It's probably just because it can be closed by clicking outside the modal and it's confusing in this context.

**Comment by matejkriz** [comment]
@komret please disable the closing by click outside for those Suite update modals

**Comment by komret** [comment]
I think this is not really a bug but a confusing UX. I assume point 3. should read "click _outside_ the Update modal" - which closes the modal as it is common in Suite. But in this case it is confusing as the user does not know whether the update happens or not and may not know where to check/initiate it. The proposed solution is to make the download modals not closable unless the user specifically clicks a button to close them. This does not apply if the modal was open in settings.

**QA:** I could not fully test the auto-update, maybe you'll have to wait for the auto-update testing version next freeze.

**Comment by MatthewDavid1984** [comment]
**QA OK**

Triggered attempted auto-update to 33.4.1, Suite update modal could not be closed by clicking outside the modal, plugging/unplugging the device had no effect on the modal, passphrase modal stayed behind the Suite update modal. Update modal can still be closed by clicking outside it when the modal is opened in Settings.

**Info:**
 - Suite version: desktop 23.4.1 (6c6a0e9979bb80b2d6592214684ea3638a532df8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.27

**Comment by komret** [comment]
@MatthewDavid1984 Sounds to me like **QA OK**?

**Comment by bosomt** [comment]
testing update to/from 23.5.2 and i see update modal

<img width="523" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/b01c7d74-70db-4d63-ae73-a62aac8d3c75">




but device says `Please type your passphrase on host...`

so i dont see passphrase modal but suite asks device for passphrase anyway :)

**Comment by komret** [comment]
@bosomt , I suppose you can still close this by "Not now" or by updating and then type the passphrase?

I don't think it is related to the changes I made in the PR. Can you please create a new issue?
