### ISSUE TITLE
Disable access to CoinJoin account on web version of Suite

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6661]
Show CoinJoin account in `add account` section, but disable continue button. And navigate user to download desktop app:
_"CoinJoin account is not available on Trezor Suite for web. Please download the Trezor Suite desktop app."_

First evaluate condition in https://github.com/trezor/trezor-suite/issues/6609
_CoinJoin account can remain available on development web version_

**Comment by STew790** [comment]
**QA OK**

Can't add CJ account on web Suite.

![image](https://user-images.githubusercontent.com/48477147/199683174-02785943-f43b-4305-88e4-9ec03175524a.png)


**Info:**
 - Suite version: web 22.11.1 (8a8808d3c3fd752bde89507d50650bc4bac56647)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
