### ISSUE TITLE
Check FW version before accessing CoinJoin account

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6662]
To access CoinJoin account user needs to have FW version `2.5.3` or higher.

Disable access CoinJoin account button with message:
_"Please update your Firmware to enable the CoinJoin feature"_

**Comment by mroz22** [comment]
Maybe we could use capabilities / unavailableCapabilities in connect for this? We should imho avoid matching against firmware version on suite layer

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.11.0 (91cc9ae7ad79fee426a16d2f2553a2017d390572)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.3 Universal (revision 595b14254c1abb2be3f69e42c7932f1eca8cf1b1)
 - Transport: bridge 2.0.32
