### ISSUE TITLE
Add CoinJoin servers to `status.trezor.io` list

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6675]
- [ ] ~~Payment request server~~ - no need to have it in status page
- [x] Wasabi CoinJoin coordinator/backend: 
      Bitcoin https://wasabiwallet.io
      Testnet: https://wasabiwallet.co

**Comment by vdovhanych** [comment]
Its ok to add it there, why do we want to have it there already btw, as those backends are not used in any way for now?

**Comment by hynek-jina** [comment]
Yes, but they will be used in one month.. so we can put this out of our minds :-)
