### ISSUE TITLE
Adjust the tool for uploading custom background to TT with UI2

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#6681]
For FW TT UI2 we need to adjust the tool for uploading custom background to TT.

The tool should firstly check if the user has installed FW with UI2. If yes, then it should verify the correctness of the size of the uploaded image (240x240px), format (JPG) and size (must be less than 16kb). If no, Suite can prompt them to upgrade the FW.

# Acceptance criteria
[Given I have a progressive 240x240px JPEG](https://satoshilabs.slack.com/archives/C02BY51RD8R/p1675154858867669)
When I upload it to suite
Then I should be prompted to change background image on Model T

Given I have a 144x144px JPEG
When I upload it to suite
Then I should see a wrong dimension error

Given I have a 18kb JPEG
When I upload it to suite
Then I should see a wrong file size error

Given I have firmware 2.5.3 or less
When I visit Settings > Device > Homescreen
Then I should see 'Upgrade your firmware to change your homescreen'

**Comment by bosomt** [comment]
So no background change till you install current FW with UI2 ?
 
![Image](https://user-images.githubusercontent.com/31506317/229727902-b25f8904-1ad8-479f-80f9-b48043bf51e3.png)

**Info:**
 - Suite version: desktop 23.4.0 (21653072a7c14c04156cfc6992cec5b582b00a99)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32

**Comment by Hannsek** [comment]
Yes, that is right.

**Comment by STew790** [comment]
**QA OK**
I was able to upload correct image to the new UI2 TT. When I tried different resolution or correct resolution but image size was too big, I was correctly informed.

**Info:**
 - Suite version: desktop 23.4.0 (de59a07c5ee7fcb9947dd4373194548ba186a2a2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 6e0c2578f8932c94413b2d1564725dc687eceaf7)
 - Transport: BridgeTransport 2.0.32

**Comment by Hannsek** [comment]
@tomasklim 
[Here](https://github.com/trezor/trezor-firmware/pull/2979/commits/8213e4fba2e2e563b5d2128b247e059fa10c594c) is a commit that converts progressive jpg into the normal one in trezorlib. Can we make something like this in Suite too?

**Comment by sime** [comment]
Can't introduce Python into suite, partly because of it running on the web.
