### ISSUE TITLE
Remove suite-web-landing completely 🎉 

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#6684]
Suite landing page is now part of trezor.io web, so we could remove it completely from our monorepo 🎉 

New landing pages are https://trezor.io/start (old url, that was redirecting to suite.trezo.io/start) and https://trezor.io/trezor-suite. 

http://suite.trezor.io is now redirected to https://trezor.io/trezor-suite. 

Remove everything that is not used elswhere (including assets, gitlab jobs, dependencies ...).

**Comment by tomasklim** [comment]
![Screenshot 2022-11-21 at 9 36 33](https://user-images.githubusercontent.com/33235762/203003513-4839788c-d549-4672-aacc-2c40936f0acb.png)
will do as a part of this 🔝

**Comment by bosomt** [comment]
**QA OK**
