### ISSUE TITLE
Amount increases whenever send form is reopened

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#6694]
**Describe the bug**
Amount gets multiplied whenever send form is reopened.

**Steps to reproduce:**
1. enter a valid amount into sendform
2. close send form or navigate elsewhere
3. reopen it

**Info:**
 - Suite version: web 22.11.0 (308c6aad3d5e826ccc28dc804325985279625155)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: model T 2.5.3 Universal (revision f56041a759189ade4a4a3287035506c228ac8b11)
 - Transport: bridge 2.0.32

**Expected result:**
Amount should not change.

**Actual result:**
Amount is multiplied by 10 ** 8 -> it might be related to satoshis, @dahaca 

**Screenshots:**
![chrome-capture-2022-9-27](https://user-images.githubusercontent.com/42465546/198296232-e4073c32-5928-43c6-a232-093aa9c48d28.gif)

**Comment by STew790** [comment]
We were actually not able to reproduce this on current web or app dev version. Could you try it again, please?

**Info:**
 - Suite version: web 22.11.0 (4e295f1fb821653c6fcc797ef129acf6f584749b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32

**Comment by komret** [comment]
Thanks @STew790, I now noticed this only happens in `StrictMode` (i.e. only in _development_ environment so you cannot see it). `StrictMode` will be turned off by #6598. However, this indicates a bug in send form, possibly the same issue as @szymon reported in #6596. We need to fix the bug and then turn on `StrictMode` again.

**Comment by komret** [comment]
@STew790 This is not really resolved by #12066. That PR enables `StrictMode` and we didn't observe the bug anymore.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.5.0 (a33ad459d3d919d5b6ac4210c9d876298ee8947a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 2176x1224
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
