### ISSUE TITLE
Change BTC units - settings

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6701]
As a user I would like to be able to change BTC units between BTC and satoshi in order to better see the balance when I have less than BTC. 

There is a new section in Settings under Localisation area called Bitcoin units. In the settings user can switch between Satoshis or BTC units via Bottom sheet radio buttons. 

Acceptance criteria:
- User can change the BTC units in settings
- User can choose between BTC and Sathoshis
- If user chooses BTC, all BTC amounts are displayed in BTC
- If user chooses Satoshi, all BTC amounts are displayed in Sathoshis

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=12869%3A70044&t=9W2PyXu59BEoT0Bc-1

```[tasklist]
### Tasks

**Comment by Nodonisko** [comment]
Some basic version of switching to sats was added during CryptoAmountFormatter refactor, currently placed in Customization. It will need refinements to looks according to Figma. #7762

**Comment by mnuky** [comment]
It works fine for me, let's wait for QA confirmation

**Comment by bosomt** [comment]
**QA OK**

tested yesterday during testing of 23.3.1 (3) 93d3e4b version


+ added sanity test for Test Sats/btc switching
