### ISSUE TITLE
Discreet mode

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6702]
As a user I would like to be able to hide my amounts in the app in order to increase my privacy when I'm e.g. doing printscreen for support or would like to show something in the app to my friend

**Comment by juriczech** [comment]
Should this be persisted between app sessions or when I open the app, it should be set to default visible and only change to discreet after button tap?

**Comment by mnuky** [comment]
let's copy the function from desktop suite for now. Discreet stays even if you switch off and switch on the app
