### ISSUE TITLE
Polishing My asset detail UI

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6704]
Please adjust the My asset detail page according to design in Figma

**Comment by juriczech** [comment]
Can you add more info about this please? I would honestly just go with how it is for now without the search bar as there is really no need for it since there won't be too many accounts if that's what this task is about. Low prio IMHO.

**Comment by mnuky** [comment]
There is no search bar in MVP hand off branch :) This issue is more about polishing the UI than creating new features. Take a look on Desigh hand off designs: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/branch/BlVnxNzUqrZkbhHgezLczh/s2-Mobile?node-id=7162%3A29897

**Comment by juriczech** [comment]
With the link you sent, isn't it duplication of https://github.com/trezor/trezor-suite/issues/6703? I thought this issue is referring to: https://tppr.me/1InU0

**Comment by mnuky** [comment]
There are also designs for Asset detail:
![Screenshot 2022-11-07 at 13 20 32](https://user-images.githubusercontent.com/84183817/200308976-508925e7-c991-481a-a67f-61e1d5cae135.png)

**Comment by juriczech** [comment]
Oh, yeah! Now I see. Completely disregarded the detail word in task description, my bad. Makes sense now.

**Comment by mnuky** [comment]
No worries, I will specify more in the detail future task to avoid this :)
