### ISSUE TITLE
Make the graph interactive

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6706]
All issuer related to display the graph:
1. We need help from other teams to do some changes: connect, suite, blockbook - @bouchja1 is working on the proposal list which we will discuss
2. We are not sure whether current library gives us enough freedom to make the graph interactive - point the finger on it, move and see the changes according my movements - would we use the library we have? Do we need to explore some new?

**Comment by juriczech** [comment]
@Nodonisko You already fixed this and issue should be closed right? This is the PR #6726
