### ISSUE TITLE
CoinJoin ignores that device was disconnected

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6707]
**Describe the bug**
CoinJoin ignores that device was disconnected and is only remembered.
Suite even shows that transactions and being signed and warns you to don't disconnect device that's already disconnected.
See screenshots and video.

**Steps to reproduce:**
1. Connect device and start Coinjoin
2. Remember wallet and disconnect device
3. Observe Suite behavior.

**Info:**
 - Suite version: desktop 22.11.0 (5d1bc34fcbf5ed351a680893b6586cb8bbca8c08)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision fac4e2f157ca7d0c782b8a55175478e476ea7e28)
 - Transport: bridge 2.0.32

**Screenshots:**
https://youtu.be/22wT252wzjU

<img width="1069" alt="Screenshot 2022-10-31 at 10 57 44" src="https://user-images.githubusercontent.com/31506317/198991526-0e501dcd-5f5a-47aa-a60c-5e33aab281f2.png">
<img width="492" alt="Screenshot 2022-10-31 at 10 54 33" src="https://user-images.githubusercontent.com/31506317/198991544-1bfdf749-44ee-4687-b498-da3ca027eff1.png">

**Comment by hynek-jina** [comment]
Should be already fixed.. @@bosomt lease double-check that..

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.1 (8a8808d3c3fd752bde89507d50650bc4bac56647)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
