### ISSUE TITLE
exclude errors related to blockbook backend from coinjoin account

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#6718]
"Backend is disconnected" error is not relevant for CoinJoin account and is not supposed to be displayed there. 

<img width="954" alt="image" src="https://user-images.githubusercontent.com/3729633/200552848-2e31ba50-1855-48f7-aa6b-0db77968cc35.png">

note:
CoinJoin account is using Blockbook too, but in a different way than regular account (not via websocket but REST API). 

Even if you set non-existing custom blockbook server for the coin, CoinJoin account is still able to do the discovery just fine and that is correct.
<img width="961" alt="image" src="https://user-images.githubusercontent.com/3729633/200553393-e9f77419-cf18-49ef-b6e2-ebdb20855bc0.png">

by backendType

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (2f4c0db8c499ac7541080d4aad5707674a21e45f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
