### ISSUE TITLE
Onboarding (scanning the XPUB) - possibility to escape when I import another asset

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6727]
As a user I would like to have option to get out of the scanning (onboarding) process when I already have some XPUBs successfully imported otherwise it is annoying because I have to restart the app to get on the Dashboard or anywhere else. 

Acceptance criteria:
When user already have some XPUBs created and want to create another one, there is a option to close the process and come back where I was

![Image](https://user-images.githubusercontent.com/84183817/199228002-be6d821a-112b-425d-9c31-41f505f04999.png)

**Comment by juriczech** [comment]
So the close option shouldn't be there when importing 1st account, is that right?

**Comment by mnuky** [comment]
IMO I think it is not necessary to put it on the first import as there is nothing else to do for now.
