### ISSUE TITLE
Onboarding (scanning the XPUB) - hint page Where to find the XPUB

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6728]
As a unexperienced user I need to help with where I can find my XPUB in order to be able to scan and add my asset.

Acceptance criteria:

- There is a link on the bottom which is accessible until user scan the XPUB
- If user clicks on it - overlay screen with explanation Where to find the XPUB appears
- If user click on Got it - it is closed
- If user chooses ETH, ETH Classic, XRP, ETH Testnet, ETH Goerli, different content appears because these coins don't have XPUB but only public addresses

Designs in Figma:
https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=5935%3A39909&t=8nioxIJR4SefV3Fx-1

Behaviour of the page is nicely explained on the prototype: https://www.figma.com/proto/Z6AGVUmKQzLNtDozFamW7f/branch/BlVnxNzUqrZkbhHgezLczh/s2-Mobile?node-id=7344%3A30880&scaling=scale-down&page-id=5544%3A35367&starting-point-node-id=5942%3A114223&show-proto-sidebar=1

**Comment by bosomt** [comment]
**QA NOK**

video is not centered on Samsung Android Tablet 
ab6f7f7 - [develop] - feat(suite-native): video-assets and xpub video sheet (#7522)

![image](https://user-images.githubusercontent.com/31506317/218821866-5edcb527-afbc-4def-880e-012c611ddff5.png)

**Comment by PeKne** [comment]
@bosomt FYI I'm really starting to hate Android tablets 😅. Please test again. Fixed in https://github.com/trezor/trezor-suite/pull/7651

**Comment by mnuky** [comment]
@PeKne video works fine, the only UI issue is that the link itself should be "sticky" to the bottom of the screen, not between the input field "Enter xpub" and Submit. See the figma designs:


![Image](https://user-images.githubusercontent.com/84183817/219607389-4d77dbc4-262f-4c43-82a3-8205640bcf28.png)
![Image](https://user-images.githubusercontent.com/84183817/219607424-8a58f5ef-8017-474a-8634-e9e68f175bf5.png)

**Comment by PeKne** [comment]
Ok, my bad. I'm gonna fix that.

**Comment by bosomt** [comment]
**QA OK**

ok for video, waiting for sticky link ;)

4658db7 - [develop]

**Comment by PeKne** [comment]
@bosomt the sticky button is ready for testing.

**Comment by bosomt** [comment]
**QA NOK**

i dont see link at all now ;)

version: 0a00686 - [develop] - chore(mobile): use native stack for navigation (#7702)

![image](https://user-images.githubusercontent.com/31506317/221185732-a4c8c222-8d3f-4412-be46-53d25729b7b4.png)
