### ISSUE TITLE
Onboarding (scanning the XPUB) - scan more XPUBs in the same flow

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6729]
As a user I would like to import more assets within one scanning flow in order save my time. 

Nicely showed in the prototype: https://www.figma.com/proto/Z6AGVUmKQzLNtDozFamW7f/branch/BlVnxNzUqrZkbhHgezLczh/s2-Mobile?node-id=5942%3A114223&scaling=scale-down&page-id=5544%3A35367&starting-point-node-id=5942%3A114223

Acceptance criteria:

- When user imports first XPUB, there is possibility to import another
- User can scan another XPUB
- If user import more than one XPUB there is a carousel where user can check all assets imported
- User can delete the ones he does not like
- When user confirms all imported assets, he is redirected to Homescreen where all assets are imported

**Comment by juriczech** [comment]
@mnuky Just a thought: Even though this is not super complex, it might still require some time spent on this and I would personally put the priority as low and push this to further sprints as it's just improvement IMHO. I would focus on more important stuff that allows for more important functionality and do this later. Just my 2 cents.

**Comment by mnuky** [comment]
Great input @juriczech - thank you. I assumed it will quite ease as there is already a button Import another in the flow and it redirects me back to the scanning. If it's not easy, then let's do it later and lower the priority but remove the button "Import another" from the flow so that we don't confuse users that it is possible - should I create another issue to do that?

**Comment by juriczech** [comment]
@mnuky I am not saying it's rocket science, it probably won't be too hard tbh, it's just not trivial either and we might put our focus elsewhere if you're okay with that from product side :ok_hand:

No need to create issue for the button removal. I did that here as it's pretty trivial and once the team approves this, I will merge it. https://github.com/trezor/trezor-suite/pull/6754

**Comment by Nodonisko** [comment]
Is this still valid? @mnuky

**Comment by mnuky** [comment]
closing, no need to do it anymore
