### ISSUE TITLE
Homescreen Coin component - show share of the coin via icon

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6733]
As a user I would like to see the proportion of my portfolio in order to get better overview of my coins ratio.

**Comment by Nodonisko** [comment]
Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=8269%3A53503&t=Sfk6VTBQkLRbOQA5-1

There is rounded colored border around crypto icon, that is showing filling around by percentage of fiat value in portfolio. Example: I have 750 USD in BTC and 250 USD in ETH => 75% will be filled around BTC and rest 25% around ETH

**Comment by bosomt** [comment]
**QA OK**

tested on version 1ae945c Samsung Android tablet
