### ISSUE TITLE
Settings of my asset

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6738]
As a user I would like to change the name of my imported asset 
As a user I would like to delete my asset from mobile app
As a user I would like to see details of my imported asset - type of coin, account type (if applicable for coin), derivation path
As a user I would like to see XPUB of imported asset, including QR code

Acceptance criteria:
User can change the name of the asset. If name is changed, it is renamed everywhere in the app
If user deletes the asset, it is no longer displayed in the app and user is redirected back to list of assets
User can see information about the asset: type of coin, account type (if applicable for coin), derivation apth
If user clicks on View XPUB / Public address, the "toaster" appears and user sees the QR code, address and possibilty to copy or share the address

**Comment by juriczech** [comment]
Settings of my asset should be visible in asset detail. 

Derivation paths and account type is not ready.
