### ISSUE TITLE
Disable adding multiple CoinJoin accounts

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#6739]
**Describe the bug**
Two coinjoin accounts were created

**How to reproduce**
Not sure. It looks like that under specific circumstances, suite UI does not block me from creating another account. It actually does not react properly (by blocking / waiting me) while creating the first one. 

**Screenshots**
![image](https://user-images.githubusercontent.com/30367552/199248349-e1b8a6d2-624f-41ac-9739-35574e2e389a.png)

**Comment by matejkriz** [comment]
you mean adding one more coinjoin account right after you asked to create the first one but before it's discovered?

**Comment by mroz22** [comment]
> you mean adding one more coinjoin account right after you asked to create the first one but before it's discovered?

could be. not sure. will kindly ask @trezor/qa to check it

**Comment by bosomt** [comment]
I remember that i was able to have multiple CJ accounts.
But I have no idea how to replicate it /I only found out yesterday that there suppose to be only one CJ account :) /
So far adding another during discovery of first one didnt worked for me.
But I will try to replicate it during this testing cycle.

**Comment by bosomt** [comment]
**QA OK**


i was not able to reproduce this issue for days /and i tried to add another account many times/

**Info:**
 - Suite version: desktop 22.11.1 (36517f2367056ec69f25858ddd96684364d1dbc5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: 
 - Transport: bridge 2.0.32
