### ISSUE TITLE
Interactive portfolio graph

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#6741]
Portofolio graph should show real values above graph and these values should change when doing swipe gesture over graph.

**Comment by Nodonisko** [comment]
#6726

**Comment by STew790** [comment]
**QA NOK**
The graph looks good but the values are sometimes shown wrong. I go up on the graph but it shows lower value. Screen recording attached:

https://user-images.githubusercontent.com/48477147/210240997-49ebe47f-6dba-4eb8-b040-ca60ef2c0b84.mp4

**Info:**
Build version: develop-22.12.1 (246) commit 2cf3b69

**Comment by Nodonisko** [comment]
@STew790 That is not a bug, it's caused by algorithm that is making graph nice (not sharp edges etc.). It's not that visible on mobiles, but from video it seems you have really big screen (tablet probably?) so graph points must be stretched quite apart and algorithm need to fill pretty big gaps.

In future we can probably generate more points for wider screens, or adjust alogrithm somehow, but it will require quite a lot of time because it's external library right now.

Is that a big issue @mnuky ?

**Comment by STew790** [comment]
Ok I see, yes it was a tablet with a much bigger screen then usual phones. It probably wouldn't be that visible on smaller screens, I just randomly noticed that so I wanted to be sure you know about this.
Otherwise the graph looks good to me, so I let the decision on @mnuky and we can close this possibly.

**Comment by mnuky** [comment]
if it's only matter of big screens and the effort to fix it is too high, close it pls

**Comment by STew790** [comment]
**QA OK**
The graph looks good, works just fine :tada: .
