### ISSUE TITLE
Add en estimate for Coinjoin session end

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#6746]
Display an estimate for the coinjoin session end in the coinjoin summary section. Use the `getEstimatedTimePerRound()` util for calculation.

**Comment by STew790** [comment]
**QA OK**
Estimate is shown when doing a CJ.
![image](https://user-images.githubusercontent.com/48477147/199732790-91040385-0029-49a5-ab57-b457d40e4d10.png)

**Info:**
 - Suite version: web 22.11.1 (8a8808d3c3fd752bde89507d50650bc4bac56647)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
