### ISSUE TITLE
Artifact above graph in recent mobile app build

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6747]
**Describe the bug**
Artifact above graph in recent mobile app build.
See video and screenshot, from time to time after you change graph view and touch graph line you can see artifact displayed above fiat sign

**Info:**

-   Suite Version: 22.8.0 (185)
[develop] - aec1e32 - feat(mobile): interactive graph (#6726)
-   OS: Android , Samsung

**How to reproduce**

1. Load wallet with transaction history
2. Touch graph line and hold
1. Observe left up corner
1. If nothing happens change graph to different time scale and repeat.

**Screenshots**
<img width="58" alt="image" src="https://user-images.githubusercontent.com/31506317/199291543-6b70f0a4-52c5-43b8-838f-b954033b0313.png">

https://www.youtube.com/watch?v=VKw_lCuKiSU

**Comment by Nodonisko** [comment]
@bosomt can you add more info about device? Android version + screen size? This will probably play important role in this issue

**Comment by bosomt** [comment]
**QA NOK**

artifact moved below fiat values.

<img width="149" alt="image" src="https://user-images.githubusercontent.com/31506317/199442882-00330f27-45f3-43bf-bc6c-7fa4fccd11c8.png">

Video: https://www.youtube.com/watch?v=NEqK1VYNTC4

- Version of Suite:
Release notes for 22.8.0 (186)
[develop] - 790444a - fix: graph overflow + app portrait only (#6749)

 - Device info: `Samsung Galaxy Tab S7 FE`
Resolution: 1600 x 2560 pixels, 16:10 ratio (~243 ppi density)
https://www.gsmarena.com/samsung_galaxy_tab_s7_fe-10922.php

**Comment by Nodonisko** [comment]
Ready to retest.

**Comment by bosomt** [comment]
**QA OK**
