### ISSUE TITLE
Enable access to min UTXO amount value available for CoinJoin

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#6756]
In order to display a UTXO tag in Coin Control (as specified in #6215) informing the user that a UTXO is not available for CoinJoin, the UTXO amount threshold (currently 5.000 sats) needs to be stored in global state. A preferred way is to obtain this value from the coordinator rather than using a hard-coded config value. It will be accessed from `UtxoSelection` component in a similar way as e.g.`coordinatorFeeRate`.

**Comment by komret** [comment]
**QA:** An icon should be displayed in CoinJoin account Coin Control for UTXOs lower than 5000 sat and higher than 134 375 000 000 sat.
![Screenshot 2022-11-02 at 18 01 20](https://user-images.githubusercontent.com/42465546/199555093-5cfbf49b-4d0d-4bc5-8b98-9b073a8f3e04.png)

**Comment by bosomt** [comment]
@komret  

message is correctly displayed in Send dialogue.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/31506317/203322866-279c7131-75d3-4c88-ba77-fbf32bf677c5.png">


But CJ can run with less than 5000 sats.

<img width="618" alt="Screenshot 2022-11-22 at 13 43 35" src="https://user-images.githubusercontent.com/31506317/203323003-1135ca80-eb8a-499a-be2f-0f37af6092dd.png">


<img width="600" alt="Screenshot 2022-11-22 at 13 42 34" src="https://user-images.githubusercontent.com/31506317/203323011-cf254f21-5c70-466b-b1a6-283d40edf531.png">


**Info:**
 - Suite version: desktop 22.12.0 (f26b9c40b939037b6842c26a408f483c36b3121e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by hynek-jina** [comment]
@bosomt Thank you...
I will discuss that with Ondra and create a followup issue once we have clear idea how to do that.. 
_So I moving this issue to approved meanwhile.._
