### ISSUE TITLE
Access a list of UTXOs blacklisted from coinjoin

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#6757]
Similarly to #6756, `UtxoSelection` component in Coin Control needs to figure out whether a UTXO is blacklisted from CoinJoin (due to previous misbehaviour) so that it can display a proper `UtxoTag`. 

When a UTXO is banned from CoinJoin, it should be added into an array of `bannedUtxos` similar to `excludedUtxos` in `useSendForm` where the key is UTXO outpoint and the value is an estimated date when the ban will be lifted. Alternatively, the value can be the date when the UTXO was banned and we can calculate the end date using a duration value from our config.

**Comment by komret** [comment]
There is no way to know this beforehand so that it could be displayed in CoinControl - closing.

**Comment by hynek-jina** [comment]
But we can find out once the user start coinjoin.
@szymonlesisz What information do we get from coordinator? Only time and that the particular UTXO is banned? 
For how long will we keep this information in the memory?

**Comment by szymonlesisz** [comment]
Coordinator doesnt share ban time or a reason, only type `InputBanned`: 3 hours, `InputLongBanned`: 31 days
suite receives it when it tries to register input into the round, those errors could be handled by suite and assigned to particular utxo with current timestamp.
input registration could be repeated after penality period
more in [slack thread](https://satoshilabs.slack.com/archives/C03RY9SEELT/p1675343257467519?thread_ts=1675340047.425319&cid=C03RY9SEELT)
