### ISSUE TITLE
Graph timeframes display of data

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6764]
As a user I would like to see the whole timeframe I choose at the graph no matter when the first transaction was proceed. 

Description:
Current version of the graph displays the data just from the date first transaction was proceed. That means if my first transaction was 15th October ago and I choose 1M I see data line only from 15th October but no data before. It causes that if user switch from 1M to 1Y graph stays the same. 

Acceptance criteria:

- Graph line is displayed for time frame user chooses
- If user chooses the time frame when there are dates without transaction, 0 link is displays until the day first tx has been made

I made simple sketch to explain it, hope it helps. 

![Image](https://user-images.githubusercontent.com/84183817/199496316-2d2e9f41-ef73-4708-906a-8135f39606f0.jpg)
![Image](https://user-images.githubusercontent.com/84183817/199496315-a4f0970b-947f-4c2c-8176-d6149507ab46.jpg)

**Comment by STew790** [comment]
**QA OK**
Graph correctly starts where user selects, not with first transaction.

![image](https://user-images.githubusercontent.com/48477147/207083054-4e100a32-78d2-44aa-aa45-e8a318ad6f9b.png)

**Info:**

Suite version: desktop 22.12.1(145) (https://github.com/trezor/trezor-suite/commit/fab845cd174199f5a8f716e43e9d4b0cc4eacd49)
