### ISSUE TITLE
Interactive graph on Asset detail

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6767]
As a user I would like to interact with the graph on the Asset detail as well in order to see how my crypto has evolving. 

**Acceptance criteria:**
- When user comes to My asset detail he sees default values: current amount of BTC, value in FIAT, todays date, uprises / downrises since yesterday
- When user move on the graph line with finger, values are changing according to date where user points. BTC amount is static and shows only current balance

There will be following issue to make the BTC balance dynamic: https://github.com/trezor/trezor-suite/issues/6768

**Comment by STew790** [comment]
**QA NOK**
Unfortunately, we can click into the graph and move with it only like 1% of the time. It doesn't work almost all the time, doesn't matter if it is on the "dashboard" or in the assets.

**Info:**
 - Suite version: desktop 22.12.1(145) (fab845c)
 - OS: Both Android and iOs

**Comment by STew790** [comment]
**QA OK**
Sorry, completely our fault, we tried it again with a little help and it works.

**Info**:

Suite version: desktop 22.12.1(145) (https://github.com/trezor/trezor-suite/commit/fab845cd174199f5a8f716e43e9d4b0cc4eacd49)
OS: Both Android and iOs
