### ISSUE TITLE
Change balance of BTC according to movements on the graph

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6768]
As a user I would like to see how balance of my BTC has evolving in time according to graph.

**Acceptance criteria:**

- When user moves the finger on the graph line, BTC balance is changing according to movement on the graph line and the date

**Comment by juriczech** [comment]
Already implemented.

**Comment by STew790** [comment]
**QA NOK**
Unfortunately, we can click into the graph and move with it only like 1% of the time. It doesn't work almost all the time, doesn't matter if it is on the "dashboard" or in the assets.

**Info:**
 - Suite version: desktop 22.12.1(145) (fab845c)
 - OS: Both Android and iOs

**Comment by STew790** [comment]
**QA OK**
Sorry, completely our fault, we tried it again with a little help and it works.

**Info:**

Suite version: desktop 22.12.1(145) (https://github.com/trezor/trezor-suite/commit/fab845cd174199f5a8f716e43e9d4b0cc4eacd49)
OS: Both Android and iOs
