### ISSUE TITLE
CoinJoin account loading

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6779]
Implement progress bar with list of tips.
These messages should be randomly selected from list. (TBD)
And switched after `10s` of loading

_note: currently discovery takes circa `90s`._

![Image](https://user-images.githubusercontent.com/26002916/199670321-5ccfcac7-788c-4f42-9945-af9068822f8a.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (a1cce70b103e883528fd6a05659c48f66fb98b1b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
