### ISSUE TITLE
Move anonymity level settings into `Account details`

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6780]
We want to reduce complexity for users. Therefore, we will reduce the visibility of the anonymity level setting by moving it to `account details`.

![Hidden anonymity level](https://user-images.githubusercontent.com/26002916/199671505-f6201522-3188-4778-b91d-179033b051be.png)

Remove anonymity level control from account page:

![Snímek obrazovky 2022-11-16 v 10 42 57](https://user-images.githubusercontent.com/26002916/202145830-18fedc56-5108-433a-9eef-276a4afeb525.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.1.0 (9fe19dcb15c69f22a65368e3e83eb029c1d5863d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
