### ISSUE TITLE
Display derivation path

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#6781]
Display derivation path of the account under the `Account` tab.

Where `Account` tab is not present, create one. (e.g. ETH account)
Change the _Account_ tab to _Details_ tab

Add `Derivation path` field between `Account type` and `Public key (XPUB)` fields.

**Copy:** Derivation path is a parameter according to which the Hierarchical Deterministic (HD) wallet derives individual keys within the tree of keys.

Link under `Learn more`: https://trezor.io/learn/a/what-is-bip32<

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.12.0 (c30d593ca8ffe6d2313f7e5e467740d79bcf2360)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: Trezor T2T1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33
