### ISSUE TITLE
suite-native: Create DebugInfo component

### ISSUE THREAD

**Issue by bouchja1** [trezor/trezor-suite#6783]
- create the component DebugInfo which will be shown in DEV utils section
- will show:
 - current version of the app
 - changelog
 - commit ID
 - ...

**Comment by bouchja1** [comment]
@Nodonisko 

- DebugInfo is "ready"... meaning that all required ENV variables are prepared to be loaded from `process.env` (https://github.com/trezor/trezor-suite/blob/develop/suite-native/config/src/debugUtils.ts) - but it is not working, I don't have any idea right now why it is not present in process.env => it is empty:(

- all these ENVs are being set in fastlane (3 different Fastfiles):
  - suite-native/app/fastlane/Fastfile
  - suite-native/app/ios/fastlane/Fastfile
  - suite-native/app/android/fastlane/Fastfile

![Image](https://user-images.githubusercontent.com/2227592/199980635-6af44e18-32fe-4b57-b498-b00684a225bd.jpg)

**Comment by Nodonisko** [comment]
For some reason values ENV variables are not propagated to `process.env`. Probably something missing in fastlane files, so more investigation needed.
