### ISSUE TITLE
CoinJoin account default visibility 

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6785]
CoinJoin account should be visible by default (once discovered)
![Snímek obrazovky 2022-11-03 v 12 35 19](https://user-images.githubusercontent.com/26002916/199710985-c6adabb9-8883-48ab-a3a2-0d128782c908.png)

**QA note**:
Please test not only adding CoinJoin account but adding all sorts of account types and coins, closing groups, sending funds on account in closed group, switching between wallets.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (8564941f51e20658d0286dc26e14858d8ee0d300)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
