### ISSUE TITLE
Service fee shouldn't have decimals in sats

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6786]
![Snímek obrazovky 2022-11-02 v 10 25 07](https://user-images.githubusercontent.com/26002916/199711898-84a0451d-dcd4-4814-ad9d-c42e33a6f224.png)

Service fee for each UTXO should be rounded down on whole sats.

**Comment by komret** [comment]
I will change the calculation to 0.3% from each UTXO with anonymity level lower than target anonymity, rounding down to whole sats, i.e. count each UTXO separately, not just take a percentage of the whole amount.

Question is, should I remove some UTXOs from the calculation?
- UTXOs with amount lower than `plebsDontPayThreshold` (1M sats)
- previously coinjoined UTXOs (How are these defined? Do they just have higher anonymity than 1 or should I browse transaction history as well?)

**Comment by hynek-jina** [comment]
Thx.. I have specified it in separate issue: https://github.com/trezor/trezor-suite/issues/6821

**Comment by komret** [comment]
**QA:** decimals should never appear after merging #6847.

**Comment by STew790** [comment]
**QA OK**
Service fee is rounded correctly:

![image](https://user-images.githubusercontent.com/48477147/201670540-fbb44f19-1fa9-4019-beef-46d0ed70dfd7.png)

**Info:**
 - Suite version: desktop 22.12.0 (2f4c0db8c499ac7541080d4aad5707674a21e45f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
