### ISSUE TITLE
Set default anonymity level to `10`

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6787]
Currently the default value for desired anonymity level is `80`. Please change it to `10`

**Comment by komret** [comment]
**QA:** newly created CoinJoin accounts have target anonymity 10.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (a1cce70b103e883528fd6a05659c48f66fb98b1b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
