### ISSUE TITLE
Rounding the digits

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6790]
Currently we round the digits behin 0 for too many digits. Please round the digits behind 0 for max 8, as it is in Desktop Suite

**Comment by juriczech** [comment]
Rounding digits will be based on networks config. So it will be:
- Bitcoin 8 decimals
- Ethereum 18 decimals 
- etc as you can see here https://github.com/trezor/trezor-suite/blob/develop/suite-common/wallet-config/src/networksConfig.ts

**Comment by mnuky** [comment]
Great! THX

**Comment by juriczech** [comment]
Resolved in https://github.com/trezor/trezor-suite/pull/6888

**Comment by bosomt** [comment]
**QA OK**
