### ISSUE TITLE
Hovering over anonymity level slider line shows wrong tooltip

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#6800]
**Describe the bug**
If I hover over the "Desired anonymity level" bar, it shows a tooltip that is not showing the number that I would like to select, but some different message (see screenshot).

**Steps to reproduce:**
1. Open Suite
2. Add CoinJoin account
3. Click on the "Desired anonymity level" button
4. Hover over the slider line

**Info:**
 - Suite version: web 22.11.1 (8a8808d3c3fd752bde89507d50650bc4bac56647)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Expected result:**
An exact number is shown.

**Actual result:**
A wrong tooltip is shown

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/199965038-15d066fd-86ff-477e-b2f7-d73d7375297f.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (a1cce70b103e883528fd6a05659c48f66fb98b1b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
