### ISSUE TITLE
Missing UTXOs in Coin control list

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6803]
**Describe the bug**
Running CoinJoin on an account I don't see all my utxos.
As you can see that the balance is higher then the sum of two visible utxos.

<img width="1792" alt="Snímek obrazovky 2022-11-04 v 11 22 28" src="https://user-images.githubusercontent.com/26002916/199978065-f14461ce-5eee-4356-b70c-ab205516f83d.png">

**Comment by hynek-jina** [comment]
It happens when I increase the anonymity level from 1 and I already have some UTXO with anonymity level above 1.


https://user-images.githubusercontent.com/26002916/200500702-5048fff9-c16a-4c1f-86a8-c91b64a89267.mov

**Comment by komret** [comment]
**QA:** I could not check it on the same account where the error was reported because the UTXO set has changed. Please test on several accounts, including some with multiple pages and anonymized UTXOs.

**Comment by bosomt** [comment]
**QA OK**
works as expected.
@hynek-jina can you confirm that it was fixed ? 


**Info:**
 - Suite version: desktop 22.12.0 (e97f817b93cf74d122ad303a2572a8fb1a9bc3f0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by hynek-jina** [comment]
I'm having some issues with Middleware.. so I'm not able to say.. ☹️
