### ISSUE TITLE
Too fat CoinJoin icon

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6804]
| **Fimga - correct version:** | **Currently implemented:** |
| --- | --- |
| <img width="174" alt="Snímek obrazovky 2022-11-04 v 14 06 20" src="https://user-images.githubusercontent.com/26002916/199979596-753a8dd8-b9d2-4054-9168-20e79c52cfc8.png"> | <img width="253" alt="Snímek obrazovky 2022-11-04 v 11 00 02" src="https://user-images.githubusercontent.com/26002916/199979612-c2efa558-b49f-4a19-aabe-114cc481337b.png"> |

**Comment by dahaca** [comment]
Update the Icons instead:



![Image](https://user-images.githubusercontent.com/45338719/201683768-90b1db2f-b05d-4e3b-8210-8be09bbef483.png)

**Comment by hynek-jina** [comment]
@dahaca Sorry for the confusion. We will stick to `shuffle` icons.. Only implemented version doesn't correspond to one in Figma..

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (8621d32d46f792cac28858b790e108cce3b1f1e7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
