### ISSUE TITLE
suite-native: Fix undefined balances for BTC TEST in graph

### ISSUE THREAD

**Issue by bouchja1** [trezor/trezor-suite#6808]
There was the problem _"Cannot convert undefined value to object"_

![Image](https://user-images.githubusercontent.com/2227592/199993551-db71d0ba-9a4e-4592-9377-2761455f6795.png)

...with these assets imported in the mobile app:

- BTC account from our "use dev xpub" button
- BTC test xpub: vpub5ZJFnFjoejaE2GUxf2nhq7Mgv5fzcg3v5CUrKdH7guiZeUhp55s41x6gyjRBU8j4NRVJzAFCVDy491Xgp9yATB42Bp1DEUyBoTnhKvfLXJT
- BTC test xpub 2: vpub5ZJFnFjoejaE6GCRq8aJjqQmZkqVcLZFYHoAoxFJntktMEvaFkreJUz47XMr3vym1Lb681PhHunzgdUetnyHSQTE9PuUmzXXE9ZB7ZPD7M9

The problem with "undefined" value comes from here https://github.com/trezor/trezor-suite/blob/develop/suite-common/wallet-graph/src/graphUtils.ts#L555 so I have already started with fixing it here in this PR:

- https://github.com/trezor/trezor-suite/pull/6807

PR is in progress and the "undefined" problem described above is fixed there.

...now there is another problem for Portfolio graph. It is not an error but something is wrong with the summation of the balance for various different currencies together. See that BTC balance is **$97.39** but graph says "Zero balance in this range".

![Image](https://user-images.githubusercontent.com/2227592/199996305-61979a0c-b8e6-4488-8a5f-e601747c843d.png)

Note: it works correctly in single account view, graph is shown (account detail) so I think the problem above is connected with planned issue https://github.com/trezor/trezor-suite/issues/6686

**Comment by bosomt** [comment]
**QA OK**

tested on latest iPhone version
