### ISSUE TITLE
CoinJoin account discovery often failing

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6811]
**Describe the bug**

See screenshots, same account, same passphrase.
It happens to me everyday. Looks like discovery of funds fails /without any error/ sometimes and account reports no history.

So far i think that it happens when there is already running CJ on Standard wallet and I try to run second CJ in hidden wallet. /but not always/ so Im not able to reproduce it every time. 

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: desktop 22.11.1 (36517f2367056ec69f25858ddd96684364d1dbc5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Screenshots:**
<img width="1297" alt="Screenshot 2022-11-05 at 7 43 58" src="https://user-images.githubusercontent.com/31506317/200106632-cf19a1a0-4598-44db-9bd9-33140ffed32a.png">
<img width="1420" alt="Screenshot 2022-11-05 at 7 39 10" src="https://user-images.githubusercontent.com/31506317/200106634-d16ed59d-3bb9-427e-8b63-3ef561cd4258.png">

**Comment by bosomt** [comment]
[trezor-suite-log-1667627861316.txt](https://github.com/trezor/trezor-suite/files/9943233/trezor-suite-log-1667627861316.txt)
attaching log

**Comment by bosomt** [comment]
Im still able to reproduce issues.
Missing my hundreds transactions and inputs.
Only way to recover is to.
1. remove wallet
2. add wallet again and wait for discovery
3. enable CoinJoin again and wait for discovery

<img width="585" alt="Screenshot 2022-11-29 at 10 18 59" src="https://user-images.githubusercontent.com/31506317/204489629-745452ee-e143-4665-8d4e-857d19bc4a71.png">
<img width="625" alt="Screenshot 2022-11-29 at 10 18 52" src="https://user-images.githubusercontent.com/31506317/204489645-4ebe3bb7-2a94-41a4-87ab-e650131776d6.png">


**Info:**
 - Suite version: desktop 22.12.0 (e97f817b93cf74d122ad303a2572a8fb1a9bc3f0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by hynek-jina** [comment]
@bosomt Could you please try to reproduce this issue? 🙏

**Comment by bosomt** [comment]
@hynek-jina i can't "reproduce" it but it still happens from time to time :(

**Comment by sime** [comment]
@karliatto @marekrjpolak @matejkriz Gents, can we offer more insights to the user the _source_ of these failures?

**Comment by bosomt** [comment]
**QA NOK**

still happening, attaching log

**Info:**
 - Suite version: desktop 23.2.2 (00fe136fa75bc04628abf858e09223170b5cf188)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.2 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32

```
No Funds

Receive some funds and start coinjoining.
```
[Archive.zip](https://github.com/trezor/trezor-suite/files/10820009/Archive.zip)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.4.1 (5044d02a986e634881bbc85393c2936dacdcb6ec)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
