### ISSUE TITLE
Improve arrow control in AnonymityLevelSlider

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#6817]
Keypress of an arrow should change the value by 1. It may be handy to select a high value while moving the slider with a mouse is less precise.
![chrome-capture-2022-10-7](https://user-images.githubusercontent.com/42465546/200299491-c43f5b7d-3a41-49c3-a054-b61643b20f20.gif)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.4.0 (2ee6814afa5f7290889eb4b76c18412fa112b6f1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
