### ISSUE TITLE
Disable anonymization when there is nothing to anonymize

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#6818]
Disable the "Anonymize" button when:
- account has 0 balance
- target anonymity is 1
- all UTXOs are anonymous (not sure about this one @hynek-jina, someone might want to run it again for some reason)

**Comment by hynek-jina** [comment]
> all UTXOs are anonymous
 - ✅, User can increase the desired anonymity level
 
> target anonymity is 1
- this is a subset of previous point, isn't it? _(all UTXOs are anonymized on desired level - which might be 1)_

**Comment by komret** [comment]
Yes, now that we disable coinjoin for anonymous UTXOs it is a subset, otherwise it would be a special case because no coin would ever register.

**Comment by komret** [comment]
**QA:** It should not be possible to initiate coinjoin when there are no non-private funds.

**Comment by bosomt** [comment]
**QA OK**

_Nothing to anonymize_

**Info:**
 - Suite version: desktop 22.12.0 (8564941f51e20658d0286dc26e14858d8ee0d300)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
