### ISSUE TITLE
Specify the calculation of the service fee

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6821]
- [x] Count only UTXOs with lower then desired anonymity level
- [x] Remove UTXOs with amount lower than `plebsDontPayThreshold` (1M sats)
- [x] Remove previously coinjoined UTXOs (direct and indirect)
    - [x] Direct remix is an UTXO that is an output of a coinjoin transaction.
    - [x] ~~Indirect remix is an UTXO that is an output of a transaction such that all inputs of the transaction are direct remixes (this is also known as `Friends don't pay`)~~ Moved to followup: https://github.com/trezor/trezor-suite/issues/6854

**Comment by komret** [comment]
**QA:** Please check that the calculation is correct on an account where you have some UTXOs with anonymity level more than 1. Service fee calculation should not include UTXOS 1) below or equal to 1M sats, 2) originating from a coinjoin transaction.
![Screenshot 2022-11-08 at 16 46 02](https://user-images.githubusercontent.com/42465546/200633587-21daa86e-f085-41d0-b4c5-3f0121139335.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (f26b9c40b939037b6842c26a408f483c36b3121e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
