### ISSUE TITLE
Misplaced close button in Update firmware modal

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6831]
**Describe the bug**
Misplaced close button in Update firmware modal.

**Steps to reproduce:**
1. Navigate to Settings/Device
2. Start firmware update
3. Observe X button placement.

**Info:**
 - Suite version: desktop 22.11.1 (36517f2367056ec69f25858ddd96684364d1dbc5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/200525164-87a9d80e-1d0f-454f-87d7-00af0dbb76ba.png)

**Comment by hynek-jina** [comment]
@trezor/qa  
I have moved this issue to previous sprint as discussed on standup...

**Comment by bosomt** [comment]
**QA OK**

<img width="580" alt="image" src="https://user-images.githubusercontent.com/31506317/200578235-da283a5a-35b3-4826-9faf-c81b394d8d92.png">

**Info:**
 - Suite version: desktop 22.11.1 (73ccf723353e0575a64f58b2f5775d20f072311f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
