### ISSUE TITLE
Add loader for app initialization

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#6832]
In suite desktop there is a loader when the app gets initialized to load all the data and information related to accounts etc. 

Currently there are some minor glitches where even though the app seems to be initialized already, some balances display zero, because fiat rates weren't fetched yet and other stuff as well. 

We should have something similar to how desktop suite behaves to give the user some idea about the state of the app and let him know that some data is still being fetched. 

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/7642
```

**Comment by Nodonisko** [comment]
There won't be central loader there will be loader for just parts specific components etc.

**Comment by juriczech** [comment]
@Nodonisko we can close this issue?

**Comment by Nodonisko** [comment]
We still need to add loaders to formatters in case fiat rates are loading.
