### ISSUE TITLE
Hide do not disconnect dialog after signing

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6833]
After CoinJoin signing completes, the “Do not disconnect” dialog on Trezor seems to remain for a while, even though the Trezor can be safely disconnected or used for other purposes.

After CoinJoin signing completes, send `SetBusy` with `expiry_ms` not set.

![sni__mek_obrazovky_2022-11-08_v__8 22 42](https://user-images.githubusercontent.com/26002916/200527435-a3907542-aecd-44ca-8393-d56fd744e24f.png)

**Comment by bosomt** [comment]
I was able to reduce issue.

**Info:**
 - Suite version: desktop 22.11.1 (36517f2367056ec69f25858ddd96684364d1dbc5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (8564941f51e20658d0286dc26e14858d8ee0d300)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
