### ISSUE TITLE
CoinJoin embedded binary unresponsive  

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6834]
**Describe the bug**
Suite reporting CoinJoin client not enabled when CoinJoin embedded binary unresponsive  
I'm not able to reproduce it but looks like Wasabi binary was not responding properly after i reloaded Suite app.
Attached log, i hope it will be helpful.

`
2022-11-08T07:08:47.912Z - DEBUG(process-WalletWasabi.WabiSabiClientLibrary): Status error: request to http://localhost:57336/Cryptography/analyze-transaction failed, reason: connect ECONNREFUSED 127.0.0.1:57336
`

**Info:**
 - Suite version: desktop 22.11.1 (36517f2367056ec69f25858ddd96684364d1dbc5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/200527583-d33a3aed-9cc7-4f5c-8235-297509c70099.png)

[trezor-suite-log-1667893896777.txt](https://github.com/trezor/trezor-suite/files/9959668/trezor-suite-log-1667893896777.txt)

**Comment by hynek-jina** [comment]
@bosomt Is this still happening?

**Comment by bosomt** [comment]
Nope, never happened or it was never reported since i created issue.
Closing
