### ISSUE TITLE
Show message when there is no transaction on asset detail page

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6836]
As a user I would like to see message when there is no transactions yet on my asset in order not to confused that the page is blank. 

Acceptance criteria:

- If there are no transactions on the asset, display the message
- There is button with Receive which leads to Receive flow

![Image](https://user-images.githubusercontent.com/84183817/200542970-fb1e09b8-7696-4b9c-9821-a1e7d21909fa.png)

**Comment by bosomt** [comment]
**QA OK**
