### ISSUE TITLE
Loading while getting data from XPUB

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6837]
As a user I would like to see nice loading page while the data are read from my XPUB because I trust more what is happening when the load page stays for a while.

Check the prototype, how it should behave: https://www.figma.com/proto/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=5935%3A39982&scaling=scale-down&page-id=5212%3A30121&starting-point-node-id=5935%3A39909&show-proto-sidebar=1

**Acceptance criteria:**

- When user scan the XPUB, loading page appears and stays for 5s even if we load the data earlier
- Design is according to Figma

**Comment by juriczech** [comment]
@mnuky The link seems to be broken. Shows empty page for me. Can you provide more info?

**Comment by mnuky** [comment]
> @mnuky The link seems to be broken. Shows empty page for me. Can you provide more info?

I updated the link, try again pls

**Comment by bosomt** [comment]
**QA OK**

0753a0d - [develop] - feat(suite-native): graph selection dot with line (#7598)
