### ISSUE TITLE
HeaderWithIcons component

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#6839]
Consider creating some universal component for our repeating pattern where we have some center title and icon on the left/right/no icons on sides. Now our solution everytime breaks when we add or remove icons.

Something like this:

```tsx
<HeaderWithIcons leftIcon={<IconButton .... />} rightIcon={<NormalButton ... />}>
   <AnyComponentCouldBeHereLikeTitleOrStepper />
</HeaderWithIcons>
```

**Comment by juriczech** [comment]
I was thinking about it and this style of component will only work if the 2 buttons will be the same size. So I would propose having the header accept these props: 

```
leftIconName?: string,
rightIconName?: string
```

We can work around them being optional by making it either absolute position with height of the header or by placing `Box`, which will either render icon if there is name for it, or remain empty with specific size, to make sure that header title is centered.

**Comment by Nodonisko** [comment]
Making it fixed height is not option because we need it work really universal, that's reason why I want to pass whole components into it, not only icon names.

I pretty sure that dynamic height is achievable. I have some ideas that should work, but need to verify them.

**Comment by Nodonisko** [comment]
Your work around could be fine too, it doesn't have to be even some fixed width but could be something like 15‰
