### ISSUE TITLE
Remove the option to display `xpub` from CoinJoin account

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6840]
![Snímek obrazovky 2022-11-08 v 15 11 42](https://user-images.githubusercontent.com/26002916/200587189-9b4fd82b-8a85-4a8d-89b9-3987f145e401.png)

_The XPUB of the CoinJoin account can be used to completely deanonymize the user in all CoinJoin transactions. Which would hurt not only the user’s own privacy but also that of all other participants. We even apply a special account exploration scheme to avoid leaking information about the account addresses. The user should therefore be discouraged from handling the XPUB and using it in any other applications, unless they are specifically designed to handle CoinJoin account XPUBs._

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.1.0 (9fe19dcb15c69f22a65368e3e83eb029c1d5863d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
