### ISSUE TITLE
Add coinjoin for bitcoin network

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6841]
- To be hidden behind `debug` mode 
- Released with Trezor Suite `23.2`

**Comment by bosomt** [comment]
**QA OK**

<img width="465" alt="image" src="https://user-images.githubusercontent.com/31506317/215996362-3922885a-85f5-4613-af85-e1331e1e5ead.png">

**Info:**
 - Suite version: desktop 23.2.1 (476521cbc912cfb333f77dc9ca68ee6f6412f5e9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
