### ISSUE TITLE
Check Tor status and warn user if there is some problem

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6843]
For users with activated Tor ~~CoinJoin account and being in CJ account~~
- ~~check Tor status page: https://status.torproject.org/~~
- measure latency of requests over Tor

→ If there is some problem, display message:
`Tor network is currently unstable. All your funds are safe, but Trezor Suite functionality might be limited. Please try again later.`

**Comment by sime** [comment]
> check Tor status page: https://status.torproject.org/

Are you suggesting crawling the status page over clearnet to determine if the network is congested? 

I'm concerned this is a privacy leak.

**Comment by hynek-jina** [comment]
You are right.. second option is better (and I think it is more simple as well)

**Comment by karliatto** [comment]
If I understand well the difference between issue https://github.com/trezor/trezor-suite/issues/7004  and this one is that this one is when Tor is already running with CoinJoin and issue #7004 is about Tor establishing connection.
Right @hynek-jina @sime ?

Should I use the same UI elements as described in issue #7004 with different wording ?



![Image](https://user-images.githubusercontent.com/5362163/208389236-44694eee-e677-4d95-82c5-36f2cdc97d49.png)

**Comment by hynek-jina** [comment]
@karliatto Yes,
I think it's almost duplicity. Use the same UI element. Even the wording might be the same I think...

**Comment by sime** [comment]
Same wording.

**Comment by karliatto** [comment]
@hynek-jina in the description of this issue there is mention to CoinJoin "For users with activated CoinJoin account and being in CJ account" but in the issue https://github.com/trezor/trezor-suite/issues/7004 seams that is something generic when Tor is enable. 

Should this work only when CoinJoin or everytime when Tor is enable?

**Comment by hynek-jina** [comment]
True. It should be generic
