### ISSUE TITLE
Account import xpub input field is not reseted

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#6844]
1. Import first account by filling xpub into `Enter xpub` field
2. Finish import
3. Click on Import Assets on homescreen
4. Input `Enter xpub` is prefilled with previously imported xpub (should be empty)

**Comment by Nodonisko** [comment]
Also noticed that coin type switch at the top is not reseted. It seems that screen is not unmounted properly after finishing of import.

**Comment by mnuky** [comment]
It happens also when deleting imported asset before going to dashboard - see the video

Uploading screen-20221103-115430.mp4…

**Comment by Nodonisko** [comment]
I probably already found solution, need to polish it.

**Comment by juriczech** [comment]
@mnuky Can you please verify that this is still relevant?

**Comment by mnuky** [comment]
@juriczech it seems it does not happen any more, close it please
