### ISSUE TITLE
Cropped lowest balance on the right side of the graph

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6845]
If the lowest balance of my crypto is today, the digits are outside of the screen. 

![Image](https://user-images.githubusercontent.com/84183817/200605881-d763614c-1d46-4810-91c6-f56c415b1f54.png)

**Comment by STew790** [comment]
**QA OK**
Correctly cropped on both sides.

![image](https://user-images.githubusercontent.com/48477147/207059625-ccc3968f-6970-4fab-9991-a62e813ba92b.png)

Info:

Suite version: desktop 22.12.1(145) (https://github.com/trezor/trezor-suite/commit/fab845cd174199f5a8f716e43e9d4b0cc4eacd49)
OS: Both Android and iOs
