### ISSUE TITLE
Big int decimals on mobile

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#6850]
Some numbers have much more decimals than should probably related to BigInt.

![image](https://user-images.githubusercontent.com/5837757/200654140-869fb39b-2f28-4a8e-9ca7-11da952e031e.png)

**Comment by juriczech** [comment]
It's a bug. I will take a look at it tomorrow.
https://tppr.me/uH9Ui

**Comment by Nodonisko** [comment]
@juriczech Thanks. It standart dev xpub.

I think it could be due to missing of usage BigInt somewhere, but not sure about that.

**Comment by Nodonisko** [comment]
@juriczech This is already merged right?

Also please don't forget to provide specs (what should be tested) for QA to test later.

**Comment by juriczech** [comment]
Testing task can be seen here.
https://www.notion.so/satoshilabs/Decimals-in-crypto-amounts-are-unchanged-in-desktop-suite-9a13d647bf37497889f4bda4d1da7d95

**Comment by bosomt** [comment]
**QA OK**
