### ISSUE TITLE
Attach list of messages to CoinJoin discovery

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6853]
Followup of: https://github.com/trezor/trezor-suite/issues/6779

**Comment by hynek-jina** [comment]
Here is the list of messages: https://www.notion.so/satoshilabs/Quotes-for-the-CoinJoin-loading-a5d747c2e9bb46efb42e65d3d4c3678f?d=6c77b119afad470eb80d9680a7fcd419

**Comment by dahaca** [comment]
I can see that the 10 placeholder facts have [already been replaced](https://github.com/trezor/trezor-suite/blob/bdabd50393b225938abd25fe86db85a867894187/packages/suite/src/support/messages.ts#L7545) with proper messages. Should I add all the rest or close the issue? @hynek-jina

**Comment by hynek-jina** [comment]
Please add the remaining ones 🙏

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.1.0 (1e8283384ce96628c51d32acfc5246b6407b4bfa)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
