### ISSUE TITLE
Graph counting balance incorrectly while switching between timeframes

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6857]
Steps:
1. Assets BTC (PUB for testing purposes from slack channel) and BTC testnet imported

2. Wait for graph to load with timeframe 1H - all good
3. Switch to 1D - still good
4. Switch to - switch to 1W - balance is increased several times and counted incorrectly
5. Switch to another timeframe - it is not counted properly

Video attached
https://user-images.githubusercontent.com/84183817/200831068-5e5062e4-a663-41a8-8ad2-f384084e7ff3.mp4

XPUBs for BTC testnet
![Image](https://user-images.githubusercontent.com/84183817/200831529-4355f0a1-18f1-48bc-ba2a-159d6e201fa8.png)
![Image](https://user-images.githubusercontent.com/84183817/200831528-2bdfdd3c-0ec1-4314-be90-aae8fc79380c.png)

**Comment by bosomt** [comment]
**QA OK**

Tested in latest Android version and with Bitcoin account.
I was not able to reproduce issue anymore.
