### ISSUE TITLE
Homepage UI bugs

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6858]
The FIAT sign on the top should have different size
The decimals should have different size
Button Receive is missing underneath the button Import asset

Right format:
![Image](https://user-images.githubusercontent.com/84183817/200856782-ececd42b-981c-4c42-9215-5f7297bfae2a.png)

Button Recieve:
![Image](https://user-images.githubusercontent.com/84183817/200857004-cb341dd7-0ed7-4b99-b1f1-afd68e04708d.png)

Current state:
![Image](https://user-images.githubusercontent.com/84183817/200856716-ae8c7c14-8e56-4e77-973f-e0bffa63c4a9.jpg)

**Comment by bosomt** [comment]
**QA OK**
