### ISSUE TITLE
Enhance calculation for max CoinJoin rounds 

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#6863]
There has to be some buffer for failed rounds. We are confirming max number of rounds on Trezor. 

https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/utils/wallet/coinjoinUtils.ts/#L151

Right now we allow confirming only 1 round for target anonymity level below 10. 

For now we allow at least 10 rounds just to be sure. And estimated anonymity gained per round is lower because some rounds could be ruined.

We would need to change that value later with data from testing.

Would be nice to enhance that algorithm later by the UTXOs on the account. So far we check just the lowest anonymity level. We could calculate with anonymity of all UTXOs and so on.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.12.0 (f26b9c40b939037b6842c26a408f483c36b3121e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
