### ISSUE TITLE
Handle account discovery problem with `network reorg`

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6889]
Two blocks are mined at the same time. We display the one we saw first. However, the network may publicize another faster and ours will cease to be valid.

We need to devise and implement logic on how to handle such scenario

**Comment by bosomt** [comment]
@hynek-jina we can probably approve this one, right ?  
afaik there is no way to test it on our side :)

**Comment by hynek-jina** [comment]
Let's leave it for now.
I have opened followup issue for automated test: https://github.com/trezor/trezor-suite/issues/7045
