### ISSUE TITLE
Pause/Resume running CoinJoin when account is out of sync

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6890]
If backend repeatedly doesn't respond:
- [x] Pause running CoinJoin
- [ ] Inform user: `Waiting for account to sync`

**Comment by karliatto** [comment]
If I understand well this issue I think the functionality to "Inform user: Waiting for account to sync" is already implemented by `out-of-sync` messages. @marekrjpolak could you clarify if you see any difference?

So if that is the case this issue would be about Pause running CoinJoin when account goes out-of-sync

**Comment by marekrjpolak** [comment]
I :100: agree @karliatto. The only thing is that currently we're setting `out-of-sync` status after every single failed sync, so it could potentially pause running CJ too aggresively. But if it's the case, it should be imo resolved where the `out-of-sync` status is set rather than where it's consumed.

**Comment by bosomt** [comment]
**QA OK**

<img width="271" alt="image" src="https://user-images.githubusercontent.com/31506317/214044335-6429fe5b-70c7-4850-aabe-48daaff66a3a.png">

**Info:**
 - Suite version: desktop 23.2.0 (47ff6c1b0068967d941c67675a9b6cc012464fb7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision ab65b18b07170c8a9e4f1506620af988d678453b)
 - Transport: bridge 2.0.32
