### ISSUE TITLE
CJ warning when disabling Tor without having CJ accounts

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#6892]
**Describe the bug**
A modal warning a user about lack of safety for Coinjoin accounts without a Tor connection appears when there are no Coinjoin accounts present.

**How to reproduce**

1. Add a CJ account
1. Remember device
1. Forget device
1. Reload the app
2. Go to settings and toggle Tor
3. Observe the error

**Expected behavior**
The modal is not shown

**Screenshots**
![image](https://user-images.githubusercontent.com/45338719/201651235-592e5a1a-a2d3-4a70-9ea8-a9fe7fce4a90.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (f26b9c40b939037b6842c26a408f483c36b3121e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: 
 - Transport: bridge 2.0.32
