### ISSUE TITLE
Prevent address reuse on CoinJoin account

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6894]
In discovery (`coinjoin package`) scan pending transactions and flag all used receive addresses as `used`.
_Gap that might come out of this will be filled in upcoming transaction._

Related to more general bug issue: https://github.com/trezor/trezor-suite/issues/6381

**Comment by matejkriz** [comment]
related to all account types, should be handled in [getPendingAccount](https://github.com/trezor/trezor-suite/blob/develop/suite-common/wallet-utils/src/accountUtils.ts/#L759) util?
