### ISSUE TITLE
Propagate UTXOs registered for coinjoin into reducer

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#6895]
UTXOs registered for an upcoming coinjoin round need to be saved into reducer so that a corresponding icon can be shown in coin control. 

The `UtxoSelection` component is already expecting it:
```ts
const isRegisteredForCoinjoin = coinjoinAccount?.session?.registeredUtxos.includes(
        getUtxoOutpoint(utxo),
    );
```

**Comment by matejkriz** [comment]
No more needed https://github.com/trezor/trezor-suite/issues/7416
