### ISSUE TITLE
Fix coin control for non-CoinJoin account when CoinJoin has been enabled

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#6900]
`isUnavailableForCoinjoin` condition is evaluated even in non-CoinJoin accounts

https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/components/wallet/CoinControl/UtxoSelection.tsx/#L147
<img width="964" alt="image" src="https://user-images.githubusercontent.com/3729633/201709041-d202bb67-48a4-448d-86c7-d67c445e7e5f.png">

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.12.0 (073bf065b9691947244767110b5cd9dc26bc1152)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
