### ISSUE TITLE
Tor activation progress improvement

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#6902]
The `desktopApi` `'tor/bootstrap'` event doesn't reflect the actual progress of the `'tor/toggle'` action, only the progress of [`tor.start()`](https://github.com/trezor/trezor-suite/blob/649fad4b5be4af41c709efc3f8e111a13f260bf2/packages/suite-desktop/src/modules/tor.ts#L90) within it. Because of that listening to the `tor/bootstrap` event in order to track % of progress and [acting upon it ](https://github.com/trezor/trezor-suite/blob/9b3ac2eca79f54813792d0cebb6d6d323d4f6e3e/packages/suite/src/components/suite/modals/TorLoading.tsx#L38)might be unsafe. For example it is possible to go past the Tor activation modal and reach Coinjoin account discovery without Tor having the `Enabled` status in Suite.

**Comment by karliatto** [comment]
I think this issue is not happening anymore, it should be close, right @dahaca ?

**Comment by karliatto** [comment]
This is not issue anymore, it was fixed long time ago.
