### ISSUE TITLE
Not private UTXOs listed in Private section

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6906]
The outputs are in the private section (10+ anonset), but the anonset of the outputs below is 3, 1, 2, 2, respectively
<img width="752" alt="Screenshot 2022-11-14 at 14 01 27" src="https://user-images.githubusercontent.com/26002916/201866738-f5aebdc7-7455-4a0d-a66a-98fe4cdf0b76.png">

_Reported by: @prusnak_

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (e97f817b93cf74d122ad303a2572a8fb1a9bc3f0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
