### ISSUE TITLE
Disable CoinJoin `resume` if something is wrong...

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6908]
User shouldn't be able to resume CoinJoin if there is some problem
- Backend disconnected
- No internet connection
- No Tor connection
- Device disconnected
- ...
---
- [ ] Add explaining tooltip on hover

Visualisation for disabled CoinJoin control
| Disabled | on hover |
| --- | --- |
| ![disabled](https://user-images.githubusercontent.com/26002916/203094505-defa05f2-ff83-4c93-bd90-d13faa1ded74.png) | ![State=State8](https://user-images.githubusercontent.com/26002916/203094965-e5dea2eb-8fea-4da1-a8ca-242065ed339a.png) |

**Comment by bosomt** [comment]
**QA OK**

- i was not able to resume CJ when device is remembered and disconnected
- i was not able to resume CJ when TOR was off
- i was not able to resume CJ when internet was down

**Info:**
 - Suite version: desktop 23.2.0 (8b1289dca7e4279eca789ea2111e5e2a6bf38d7a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
