### ISSUE TITLE
Change stuck `0 seconds` to `Almost there ...`

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6909]
User can get stuck for a while in state of `~0 seconds` 
![Snímek obrazovky 2022-11-14 v 8 48 05](https://user-images.githubusercontent.com/26002916/201876926-a9d8442b-eccb-4f7c-8290-944117623145.png)

_This might appear in more places..._

- [ ] Change `~0 seconds` to `Almost there ...`

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (1953aba292106c1e602305b136aa765d23cb36b2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
