### ISSUE TITLE
Set default name of CoinJoin account

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6910]
- [ ] Set default name of CoinJoin account to `CoinJoin`
- [ ] Set default name of Testnet CoinJoin account to `CoinJoin Testnet`

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (8564941f51e20658d0286dc26e14858d8ee0d300)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
