### ISSUE TITLE
Do not try to open CoinJoin account during Suite startup if the wallet is not remembered

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6911]
_This happened to me today with CJ account. The CoinJoin account is not automatically added after each start of Suite and Suite wants to show you the account that is not there._

![image](https://user-images.githubusercontent.com/48477147/200538808-5fc0e14b-a005-456e-8ed4-b5f7c195cf62.png)

**Info:**
 - Suite version: desktop 22.11.1 (36517f2367056ec69f25858ddd96684364d1dbc5)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

_Originally posted by @STew790 in https://github.com/trezor/trezor-suite/issues/4465#issuecomment-1306970633_

**Comment by hynek-jina** [comment]
@STew790 
Can you please add steps to reproduce the issue?

**Comment by STew790** [comment]
Yes, we will take a look, we got it a couple times but not consistent steps. Will update this issue.

**Comment by bosomt** [comment]
**QA NOK**

i just started my Trezor Suite /with remembered wallet/ to see this :) 

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/31506317/203721977-a5f8df6f-0973-4cce-9708-a9205b78384c.png">

[trezor-suite-log-1669275480515.txt](https://github.com/trezor/trezor-suite/files/10081740/trezor-suite-log-1669275480515.txt)

**Info:**
 - Suite version: desktop 22.12.0 (1953aba292106c1e602305b136aa765d23cb36b2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by dahaca** [comment]
@STew790 @bosomt I am a bit confused by this still. Did this happen in desktop Suite? If so – how were you able to navigate to the Accounts tab and have the Coinjoin account selected?

**Comment by bosomt** [comment]
Probably related https://github.com/trezor/trezor-suite/issues/4465

**Comment by hynek-jina** [comment]
@dahaca What about being in CoinJoin account and the refresh Suite?

**Comment by hynek-jina** [comment]
Looks like duplicity of: https://github.com/trezor/trezor-suite/issues/4465
