### ISSUE TITLE
Disable account buttons during CoinJoin Account discovery

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6912]
Discovery of CoinJoin Account might take a while _(~2 minutes or more)_

User shouldn't be able to interact with the account before it is properly loaded.
- [x] disable `Overview`, `Details` tabs, 
- [x] disable `Send`, `Receive`, and `...`  buttons

![PEA — Loading Header Explo](https://user-images.githubusercontent.com/26002916/202146407-6e72e2ca-db6c-42b8-bf87-79f9540fb88d.png)

**Comment by hynek-jina** [comment]
@komret Please extend the logic to all accounts.

**Comment by komret** [comment]
**QA:** Navigation should be disabled during discovery for all accounts. I also fixed the background hover color on the `...` button (see PR).

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (90d0cef8165b51851cf4d6543836069fd9be56d6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
