### ISSUE TITLE
Wrong Chevron Z-Index at transaction approval

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#6914]
**Describe the bug**
In the transaction approval modal window, if the address is long, there's a chevron to show the entire address.
This chevron stays on top even if Transaction details are shown instead of the default content. See the screen recording video.

**Info:**

-   Suite Version: MacOS app 22.11.1 
-   OS: MacOs Ventura 13.0
-   Firmware Version: Model T, 2.5.3

**How to reproduce**
Steps to reproduce the behavior: Try to send a bitcoin TEST transaction, observe the Transaction approval modal window, click Transaction details button in the lower left corner. See the chevron over the contents.

**Expected behavior**
Chevron should behave as the rest of the content it comes together. Transaction details should be on top of it when open.

Possible solution: There's enough space to show full address without any chevrons (perhaps with some limit for possible überlong addresses). Also, chevron should unwrap the contents just in direction down, not expand both ways upa and down.

**Screenshots**

https://user-images.githubusercontent.com/88533514/201884685-a5a6afa8-66d3-402f-bd3e-30d0ff83359b.mov

**Comment by bosomt** [comment]
related or duplicity https://github.com/trezor/trezor-suite/issues/5580 :)

**Comment by komret** [comment]
> related or duplicity #5580 :)

Indeed.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.1.0 (9fe19dcb15c69f22a65368e3e83eb029c1d5863d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
