### ISSUE TITLE
Pending CoinJoin transactions are missing orange label

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6922]
![Snímek obrazovky 2022-11-15 v 14 45 26](https://user-images.githubusercontent.com/26002916/201935148-f0807c0c-17ab-4fec-953d-98acf7ee0486.png)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.12.0 (e97f817b93cf74d122ad303a2572a8fb1a9bc3f0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
