### ISSUE TITLE
Extend CoinJoin state messages

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6923]
Show more information about the CoinJoin flow to user.

See Notion page: [🚥 CoinJoin states and phases](https://www.notion.so/satoshilabs/CoinJoin-states-and-phases-ab33f8d65cc5483f922e455ef29c24ff)

- In progress bar
- In status below `play`/`resume`
- In CoinJoin modal

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.2.0 (aebe81957c19c1b289f016cca5cb6b2c7808e1bf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
