### ISSUE TITLE
Suite fails to install current firmware after intermediary firmware installation

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6928]
**Describe the bug**

Suite fails to install current firmware after intermediary firmware installation.
Please see video, i was able to reproduce it twice, no idea if its only Windows problem.
Theres no reason to download FW binary when its embedded to Suite app and it never fails with other updates or re installations.

**Steps to reproduce:**
1. Connect device with FW/BL 1.5.2/1.3.2
2. Proceed with firmware update
3. Observe suite behavior

**Info:**
 - Suite version: desktop 22.11.1 (73ccf723353e0575a64f58b2f5775d20f072311f)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model 1 1.11.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32

**Screenshots:**

https://youtu.be/TMsj_x2RZ7Y

[trezor-suite-log-1668596478397.txt](https://github.com/trezor/trezor-suite/files/10021066/trezor-suite-log-1668596478397.txt)

![Screenshot 2022-11-16 120509](https://user-images.githubusercontent.com/31506317/202166128-dccb0f75-cffe-48ef-817c-0b3a93b1e214.jpg)

**Comment by matejkriz** [comment]
logs from analytics (last 30 days, but not from today)
[failed-to-download-firmware-binary.csv](https://github.com/trezor/trezor-suite/files/10022548/failed-to-download-firmware-binary.csv)

**Comment by matejkriz** [comment]
@trezor/qa could you please retest?

**Comment by bosomt** [comment]
DEVKIT: tested 1.6.1/1.4.0 to 1.12.1 including intermediary firmware without any problem / except seed was wiped / 

STANDARD: tested 1.4.2/1.3.1 device froze during FW upload /i will retest on different computer/device /

<img width="526" alt="image" src="https://user-images.githubusercontent.com/31506317/226859389-c211e253-68c7-432f-9e76-34509e328bdd.png">

**Info:**
 - Suite version: desktop 23.4.0 (7e8281dfde9ded5ad99ec0a1cd605c701c4865f9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: 
 - Transport: BridgeTransport 2.0.32

**Comment by bosomt** [comment]
**QA OK**

retested on Windows 10 and 1.4.2/1.3.1  was upgraded to latest including intermediary FW without any problem
