### ISSUE TITLE
Polish Coin Join transaction naming

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6930]
`TR_JOINT_TRANSACTION` -> `TR_COINJOIN_TRANSACTION`
`TR_JOINT_TRANSACTION_TARGET` -> `TR_COINJOIN_TRANSACTION_TARGET`

See draft PR: https://github.com/trezor/trezor-suite/pull/6898

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
