### ISSUE TITLE
Occasionally not possible to navigate out of CoinJoin account.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6933]
**Describe the bug**
Occasionally not possible to navigate out of CoinJoin account, you can click on buttons or accounts and they respond buy you are still in CJ account main view 
See video, happened to me twice but im not able to reproduce it, it just 'happens' from time to time.

**Info:**
 - Suite version: desktop 22.12.0 (8621d32d46f792cac28858b790e108cce3b1f1e7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Screenshots:**
https://youtu.be/xYwk3v5-wmQ

[trezor-suite-log-1668600257397.txt.zip](https://github.com/trezor/trezor-suite/files/10022230/trezor-suite-log-1668600257397.txt.zip)

**Comment by hynek-jina** [comment]
@bosomt Is this still happening?

**Comment by bosomt** [comment]
nope :)
