### ISSUE TITLE
Display and distinguish UTXOs from pending transactions in Coin control

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6935]
![Snímek obrazovky 2022-11-16 v 16 57 42](https://user-images.githubusercontent.com/26002916/202230568-608e73f6-9676-4b46-90a7-08352f321eee.png)

Followup of: https://github.com/trezor/trezor-suite/issues/6215

**Comment by komret** [comment]
We already have a clock icon in transaction history and onboarding, do you mind if I use that one?

![Screenshot 2022-11-16 at 18 27 32](https://user-images.githubusercontent.com/42465546/202256621-d915113b-a994-4387-bab5-8b05208a50ee.png)
![Screenshot 2022-11-16 at 18 29 03](https://user-images.githubusercontent.com/42465546/202256598-4612cfff-5849-4641-9dd4-8666c9bfd851.png)
![Screenshot 2022-11-16 at 18 48 34](https://user-images.githubusercontent.com/42465546/202256551-40444b1e-0c85-45c8-aa9e-1dec25d0858e.png)
![Screenshot 2022-11-16 at 18 48 53](https://user-images.githubusercontent.com/42465546/202256568-712ad405-a9c9-48e9-b508-7d36897d8a6e.png)

Or I can change all of them for the new one.

**Comment by hynek-jina** [comment]
I would prefer the new one since the old one is not consistent with the other icons in coin control section.
However leave the old one in existing cases. Because it's in different size and the new one might not work well there..

**Comment by bosomt** [comment]
**QA Ok**

<img width="351" alt="image" src="https://user-images.githubusercontent.com/31506317/204260270-1c75db17-33c6-4e93-a1f7-481734af0377.png">

**Info:**
 - Suite version: desktop 22.12.0 (e97f817b93cf74d122ad303a2572a8fb1a9bc3f0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
