### ISSUE TITLE
Dashboard graph not loaded in development mode

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#6936]
The graph on the dashboard page does not load due to an error which is logged into console. It only happens in development build, for both web and desktop. The error was introduced in [this commit](https://github.com/trezor/trezor-suite/commit/c9b6238e9147cee25961c713aa2c49d610e6e320).

![Screenshot 2022-11-16 at 17 18 10](https://user-images.githubusercontent.com/42465546/202235012-ce1388a2-2c4e-498d-ae4b-ab24c76812f6.png)

![Screenshot 2022-11-16 at 15 06 04](https://user-images.githubusercontent.com/42465546/202234856-9ae677e0-4b66-48b4-9240-9f01110fe564.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.1.0 (9fe19dcb15c69f22a65368e3e83eb029c1d5863d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
