### ISSUE TITLE
Discreet mode

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#6937]
Discreet mode what will blur exact values - like in desktop.

Requirements:
1. Should use `jotai` (preffered) or context API
2. Usage must be super easy:
```tsx
<DiscreetValue><CryptoAmountFormatter value={something} /></DiscreetValue>
```
It must simple like this, **no hardcoding width/height/position** for every usage etc. Just wrap any component in it and it will blur it when turned on.

3. Skia usage is preferred https://shopify.github.io/react-native-skia/docs/mask-filters#blurmask (not sure if it will work but you can wrap whole Skia canvas in standart view and set it's opacity to something like 0.7. Then you should position it to overlay it any component wrapped in <DiscreetValue>)
4. Can be placed in `@suite-native/atoms`

**Comment by juriczech** [comment]
@Nodonisko I think `jotai` might not be the best choice for this in the end as it seems to struggle a little bit with multiple packages and since this will have to be passed down nearly everywhere, I think it might be better solution to add this to `settingsReducer` in the mobile app.

**Comment by Nodonisko** [comment]
What do you mean by "struggle with multiple packages"?

**Comment by juriczech** [comment]
When I tried it with account graph points, it wasn't updating the value in `useAtom` / `useAtomValue`. I can try it and see and then we can always opt out to use `redux`.

**Comment by Nodonisko** [comment]
That sounds strange it must work without any issues no matter if it's different package or not. Otherwise whole library will useless because you won't be able to use in any 3rd party library.

**Comment by bosomt** [comment]
**QA OK**

tested in Samsung Tablet. 
Version 7e43b20 - [develop] - feat(fastlane): Small improvements for local build (#7193)
