### ISSUE TITLE
Missing anonymity level in transaction detail

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6938]
All my inputs and outputs should have attached calculated anonymity level.
![screenshot_2022-11-16_at_18 20 33](https://user-images.githubusercontent.com/26002916/202381078-1c49582e-e1c4-4d57-8a34-19aa66b8182b.png)

[_link to original post_](https://satoshilabs.slack.com/archives/C048XFAKL10/p1668620508498339?thread_ts=1668618541.854499&cid=C048XFAKL10)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (e97f817b93cf74d122ad303a2572a8fb1a9bc3f0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
