### ISSUE TITLE
Trezor doesn't autolocks after CoinJoin round

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6939]
**Steps to reproduce:**
1. Setup PIN
2. Setup Autolock on 1 minute
3. Start Coin Join
4. Device autolocks before CoinJoin start
5. Once entering `Connection confirmation phase` screen changes to `Do not disconnect ...`
6. Device should lock again after CoinJoin round. But there remains screen with `Do not disconnect...` screen. It works as expected when I cancel the whole CoinJoin.

**Info:**
 - Suite version: desktop 22.12.0 (073bf065b9691947244767110b5cd9dc26bc1152)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Expected result:**
Return to locked screen after every CoinJoin round.

**Actual result:**
Return to locked screen only after whole CoinJoin.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.12.0 (1953aba292106c1e602305b136aa765d23cb36b2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
