### ISSUE TITLE
Ability to cancel actions

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#6941]
When user clicks on `Add (hidden) wallet` in `Wallets` he cannot cancel `Select wallet type` action.
<img width="673" alt="image" src="https://user-images.githubusercontent.com/57008159/202655257-55125c66-a11d-4d82-b3c4-cef54210f590.png">

Same behaviour is under `Enter passphrase on Trezor` and `Enter PIN` popup for T1.

![image](https://user-images.githubusercontent.com/57008159/202655869-e2dccedb-0eba-4d0c-9f24-780fd67e3811.png)
![image](https://user-images.githubusercontent.com/57008159/202655937-b1fedb7b-5457-4146-b2d0-fec00f0591d2.png)

Put a canceling cross on these tabs as in `Wallets`:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/57008159/202657051-0c4b4337-1e19-475b-9d6e-daf8617d0296.png">

**Comment by tomasklim** [comment]
@trezor/qa when merged or in PR branch please test old / new bridge, webusb

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.5.0 (0e2010aa3ca28fd407107948cb608de5c36a02b8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.5.0 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.12.0 Bitcoin-only (revision a97dfd3a4f4a709a08e125946f6e1c96a0cc7ec0)
 - Transport: BridgeTransport 2.0.33
 - Transport: BridgeTransport 2.0.27
 - Transport: webUSB
