### ISSUE TITLE
Remove Ropsten testnet

### ISSUE THREAD

**Issue by mkolar242** [trezor/trezor-suite#6943]
Remove Ropsten testnet from Trezor Suite.

**Comment by STew790** [comment]
**QA OK**
Ropsten is not present in Suite anymore.

**Info:**
 - Suite version: desktop 23.5.0 (e85314461888d4e37f70f22fb675ab0b83068eef)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.5.0 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32

![image](https://user-images.githubusercontent.com/48477147/232499216-78a7a637-06aa-4028-95ff-f57a84f2ce0d.png)
![image](https://user-images.githubusercontent.com/48477147/232499320-4751e1a1-e8dc-4d8f-825c-da7e4794439d.png)
