### ISSUE TITLE
Not able to bump or finalize transaction sent between CJ accounts

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6944]
**Describe the bug**
Not able to bump or finalize transaction sent between CJ accounts

**Steps to reproduce:**
1. Create/load two wallets and add CJ accounts
2. Send transaction between accounts
3. Try to bump or finalize transaction. 

**Info:**
 - Suite version: desktop 22.12.0 (8564941f51e20658d0286dc26e14858d8ee0d300)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Screenshots:**
[trezor-suite-log-1668771090576.txt.zip](https://github.com/trezor/trezor-suite/files/10040987/trezor-suite-log-1668771090576.txt.zip)

![image](https://user-images.githubusercontent.com/31506317/202699388-eef3d9ac-d194-469e-ad00-66c1122a4dbc.png)
![image](https://user-images.githubusercontent.com/31506317/202699556-2e8c4ea8-585f-4866-b24b-6aebb28a15fa.png)

**Comment by hynek-jina** [comment]
Should be resolved by https://github.com/trezor/trezor-suite/pull/7378
But please retest after code review..

**Comment by bosomt** [comment]
**QA OK**

RBF disabled for CJ account transactions

**Info:**
 - Suite version: desktop 23.2.0 (aebe81957c19c1b289f016cca5cb6b2c7808e1bf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
