### ISSUE TITLE
Not able to send Litecoin transaction when input used MimbleWimble 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6947]
**Describe the bug**
Trezor Suite is Not able to send Litecoin transaction when input used MimbleWimble 

**Steps to reproduce:**
1. Send funds to Lietcoin Core
2. Forward them to MimbleWimble address
3. Send them to Suite receiving address
4. Try to send funds to different account or out of Trezor.

**Info:**
 - Suite version: desktop 22.12.0 (8564941f51e20658d0286dc26e14858d8ee0d300)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/202734919-4db06746-ce86-46ba-86b4-e3609e8b6455.png)

**Comment by bosomt** [comment]
**QA NOK**

works as expected but Trezor Suite only see tx after its confirmed, but this can needs to be fixed on blockbook or probably not fixable at all. 

**sent to Suite from Litecoin core**

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/31506317/205684000-0d348581-e0bc-4e20-8eb9-b0bd54492aa5.png">

<img width="627" alt="image" src="https://user-images.githubusercontent.com/31506317/205684052-33d6ac0c-9eca-471c-9f9e-e641f6fedf75.png">

tx disappears after some time

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/31506317/205684523-37dab822-2409-430f-8037-c3fe5b61babe.png">

and its displayed in suite under different tx

https://ltc4.trezor.io/tx/1a74f5b0ce53bb5a7111acbd8ccd2e92cd9ab00d621fa25200c6269b904d88a3

<img width="513" alt="image" src="https://user-images.githubusercontent.com/31506317/205684722-e7559ac8-8b54-4bb7-a46b-de7976344c80.png">

**Sent from Legacy SegWit account to Legacy account**
and after i try to forward it to different account i will get /i have not seen this error before/
`Transaction signing error: -26: bad-txns-premature-spend-of-pegout, tried to spend pegout output at depth 1`
<img width="309" alt="image" src="https://user-images.githubusercontent.com/31506317/205684998-99ecdebe-dbcf-48da-9407-d7fb40776436.png">


https://user-images.githubusercontent.com/31506317/205685330-baabf141-2dc4-4668-8779-3d9538301353.mov

**Info:**
 - Suite version: web 22.12.0 (4142859c4fead7a07a20bc2b652962cc74a09531)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0
 - OS: MacIntel
 - Screen: 2160x1350
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by sime** [comment]
@bosomt To confirm, Trezor Suite (and Blockbook) do not show (both incoming and outgoing) pending transactions that have mweb UTXOs?

**Comment by bosomt** [comment]
@sime afaik YES, i was able to reproduce it multiple times

**Comment by sime** [comment]
@martinboehm We can reproduce TX IDs with mweb UTXOs not appearing in LTC mempool. Shall we lock a Blockbook issue?

**Comment by mroz22** [comment]
> Transaction signing error: -26: bad-txns-premature-spend-of-pegout, tried to spend pegout output at depth 1

Guys I kinda anticipated this. These utxos can be spent only after 6 confirmations according to docs. We should, I believe, address this in our stack but this is a different issue. The goal here was to be able to spend it which now is possible, right?

**Comment by sime** [comment]
> > Transaction signing error: -26: bad-txns-premature-spend-of-pegout, tried to spend pegout output at depth 1
> 
> Guys I kinda anticipated this. These utxos can be spent only after 6 confirmations according to docs. We should, I believe, address this in our stack but this is a different issue. The goal here was to be able to spend it which now is possible, right?

Ah, so depth means block depth.

For [reference](https://github.com/litecoin-project/lips/blob/master/lip-0003.mediawiki#peg-out-transactions):
> Peg-out outputs on the canonical blockchain must be locked for 6 blocks.

**Comment by bosomt** [comment]
I was able to send my utxo today :) 🎉 

https://ltc1.trezor.io/tx/c8e96f14c538916aaf6065f34dcdbbe7e649f9b49ff40689e16adc7090fc2fdc
