### ISSUE TITLE
P2P&DCA Czech translations

### ISSUE THREAD

**Issue by IvaFingerova** [trezor/trezor-suite#6949]
České překlady jsou lehce krkolomné
**P2P - Sekce list nabídek**
* Je nám líto, ale pro Vaše zadání jsme nenašli žádnou nabídku. Zkuste si vybrat z dalších nabídek níže.
* POLOHA -> LOKACE
* ROZSAH ČÁSTEK -> LIMIT KONTRAKTU
* OKNO PLATBY -> PLATEBNÍ OKNO
* NÁZEV -> TITUL
* POTVRZENÍ -> VYŽADOVÁNO POTVRZENÍ<img width="1025" alt="image" src="https://user-images.githubusercontent.com/8152411/202913296-42ce0cb9-06d6-40b7-b749-b92cd41d12b1.png">

**P2P - PRvní krok**
- Začít -> Začátek kontraktu
- Receiving address -> Přijímací adresa
* Transakci je třeba zahájit na stránkách Hodl Hodl - postupujte podle níže uvedených kroků.
* Přihlaste se nebo si vytvořte účet na platformě a postupujte podle jejích pokynů.
* Jakmile vás stránka Hodl Hodl požádá o "uvolňující adresu", vraťte se sem a pokračujte do kroku Přijímací adresa.
<img width="580" alt="image" src="https://user-images.githubusercontent.com/8152411/202913752-649f9e86-239c-4b2a-939e-5777c0cfcd9f.png">

<img width="670" alt="image" src="https://user-images.githubusercontent.com/8152411/202913584-e3191492-3048-453e-93bc-27691e7eeded.png">

**P2P summary blok:**
* OKNO PLATBY -> PLATEBNÍ OKNO
* POTVRZENÍ -> VYŽADOVÁNO POTVRZENÍ 
<img width="415" alt="image" src="https://user-images.githubusercontent.com/8152411/202913617-fb154150-05e6-4c56-b05f-b019df4b6406.png">

**P2P poslední krok**
* Máte skoro hotovo! Zobrazte a zkopírujte si adresu, kterou následně zadejte jako "Uvolňující adresu! na stránce Hodl Hodl a dokončete tam celý proces. 
<img width="574" alt="image" src="https://user-images.githubusercontent.com/8152411/202913717-11fb7076-af0a-44f9-b00d-ed4ee11fbc99.png">

--------------------

**DCA Začátek**
* Nastavení vašeho spořícího plánu
* Bitcoin spořící plán... 
* Pokud Vaše země
* Týdně - Dvoutýdenně - Měsíčně - Čtvrtletně
* Custom -> Vlastní
* Za rok ušetříte -> Za rok si do BTC odložíte
<img width="871" alt="image" src="https://user-images.githubusercontent.com/8152411/202914872-2cbc1f5e-11c2-48f3-a463-926f928766f6.png">

**DCA po návratu z Invity části**
* Nastavení vašeho spořícího plánu
* Denně - Týdně - Měsíčně
* Za rok ušetříte -> Za rok si do BTC odložíte
<img width="847" alt="image" src="https://user-images.githubusercontent.com/8152411/202914927-4216e355-d408-430b-9146-7ea455a9d7fa.png">

DCA běžící plán
* dvakrát týdně -> Dvoutýdenně
* Sledování -> Následující
![image](https://user-images.githubusercontent.com/8152411/202914369-0df2371c-5bd1-4c1f-b2e6-883e91671f16.png)

**Comment by jerechinsky** [comment]
Následující stringy nelze přeložit. Vytvořil jsem issuečko https://github.com/trezor/trezor-suite/issues/7051

**P2P**
> Receiving address -> Přijímací adresa

> Almost there! Reveal and copy your address, paste it into the "Release
address" field back on Hod Hodl, and finalize the transaction

**DCA**

> Týdně - Dvoutýdenně - Měsíčně - Čtvrtletně

> Custom -> Vlastní

---
> Nastavení vašeho spořícího plánu

Podle googlu se více používá termín `spořicí`.
<img width="255" alt="Screenshot 2022-11-28 at 19 59 27" src="https://user-images.githubusercontent.com/75733878/204359771-135814ae-6c54-42f5-b585-238390ac7843.png">
<img width="276" alt="Screenshot 2022-11-28 at 19 59 18" src="https://user-images.githubusercontent.com/75733878/204359885-7aca18a4-88ce-407b-b4e8-24f519671754.png">

Podle této stránky je správně `spořicí` https://proofreading.cz/cestina-pod-lupou/sporici-ucet-nikoli-sporici-ucet/

> Z hlediska pravopisu zdůrazněme, že správný tvar tohoto spojení je spořicí účet, nikoli spořící účet. V tomto případě totiž musíme použít přídavné jméno účelové (spořicí), nikoli dějové (spořící) – účet sám nespoří, on slouží k tomu, aby jeho prostřednictvím klient spořil.

Nechám to na tobě. :) 

---

Ostatní jsem opravil. Udělám synchronizaci crowdinu a zítra to bude v developu.

**Comment by IvaFingerova** [comment]
Uuu, tak beru zpátky spořící! Issue přehazuju na devs @alex-jerechinsky

**Comment by jerechinsky** [comment]
Vše výše uvedené (kromě chybějících nepřekladatelných stringů) je již v developu. Zamergovalo se to v #7053. Proto issue zavírám. Na chybějící stringy je issue #7051.
