### ISSUE TITLE
Repair absurdly high `anonymity level`

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6950]
![screenshot_2022-11-17_at_13 09 49](https://user-images.githubusercontent.com/26002916/202996487-73d40f2f-29bd-474e-87bd-6f68db05e9b8.png)

![Screenshot 2022-11-17 at 13 14 24](https://user-images.githubusercontent.com/26002916/202996480-9d894ed2-4fa6-409e-b719-6527ae3fc47d.png)

[trezor-suite-log-1668686429534.txt](https://github.com/trezor/trezor-suite/files/10054534/trezor-suite-log-1668686429534.txt)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.12.0 (e97f817b93cf74d122ad303a2572a8fb1a9bc3f0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
