### ISSUE TITLE
Error reporting - Sentry?

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#6954]
Before any public release we definitely want to have error reporting.

1. We should use Sentry and reuse as much code is possible with desktop (there is lot configs etc. that should be reused because of privacy etc.)
2. Turning it on/off - Will be possible for users to turn it off? Not sure how this is done is desktop app but I guess for user with disabled analytics it's turned off.

**Comment by Nodonisko** [comment]
@mnuky Please take a look to second point.

**Comment by mnuky** [comment]
@matejkriz How is it handled now at Desktop Suite? When user turns off the tracking, do we still track the errors?

**Comment by mnuky** [comment]
@matejkriz can you please give us feedback on how it is handled in Desktop suite? thx

**Comment by matejkriz** [comment]
@mnuky as described here https://github.com/trezor/trezor-suite/blob/develop/docs/analytics/sentry.md#sentry reporting to Sentry is connected to user decision about analytics. So if user disable analytics, we do not report to Sentry. But it has one exception – if error happens before storage is loaded (during app start) so we don't know the user decision yet, we do report to Sentry, but remove extra metadata like breadcrumbs (https://github.com/trezor/trezor-suite/blob/develop/docs/analytics/sentry.md#user-content-fn-1-ecbe89cfc5d99d1307e278a4566d1f9e)

**Comment by Nodonisko** [comment]
QA:
There is added button in dev menu that will throw error that should be logged into Sentry. This error should be logged only if analytics is turned, also this must be tested only in production because for dev build Sentry is always ON no matter what is analytics settings.

**Comment by juriczech** [comment]
https://github.com/trezor/trezor-suite/pull/8291

**Comment by bosomt** [comment]
**QA OK**

https://satoshilabs.slack.com/archives/C03FL9TCURZ/p1682667316939089
tested on production  version 12 iOS
