### ISSUE TITLE
Force app update

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#6955]
We need way how to force user to update app after we publish new version in case we will fuckup something. This will be quite tricky because we will need server.

1. I think for now we can go with simplest variant of having plain JSON on some server with content something like this `{ androidVersion: "22.10.1", iosVersion: "22.10.1"}` and if version of app will be older than defined version here it will force user to update
2. I think we don't need to encrypt this, since it will be super simple - in future I want to use something like message system from suite which will replace this and will be encrypted/signed.

Figma design: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=19430%3A113180&mode=design&t=qnirSC4twLodE2Wk-1

**Comment by Nodonisko** [comment]
@vdovhanych Is something like this possible?

**Comment by vdovhanych** [comment]
It is possible but I would rather use something else than have a server just for this. Will we need more server based things in the future for the app? Is suppabase/firebase an option for you, its should allow us to have this functionality. But if we go with just the server that holds that one json file its also a possibility and it would work, just the deployment of version force updates wouldn't be so elegant but with some ci job perhaps.

**Comment by sime** [comment]
How critical is this nowadays? I'm assuming app store updates on both iOS and Android automatic.

**Comment by Nodonisko** [comment]
You can easily turn auto-updates off and if you do some critical mistake you need to have way how to force users to update. I my point of view this is very critical.

**Comment by Nodonisko** [comment]
This should be done through message system

**Comment by Nodonisko** [comment]
Done by @vytick
