### ISSUE TITLE
Add support for logs in app

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#6956]
1. In case of problems would be really nice if we can export some logs from app.
2. We should reuse logs system from desktop suite (we should make package of it)
3. Will be accessible using in dev menu and can be exported/copied

**Comment by mnuky** [comment]
ad 1. I would change "really nice" to must have as we plan to integrate some "button" to app like "Report a bug" which would send the app log and message from the user to us
ad 2. 👍
ad 3. What do you mean by dev menu?

**Comment by juriczech** [comment]
QA: Please verify that logs are functioning same way as they were working in previous builds. Test in this branch against develop. 


Some basic checks of logs from changing language, currency, device connection etc should look same.

**Comment by bosomt** [comment]
**QA OK**

i will check "big" log thats generated by app after it gets merged to dev master
 
<img width="554" alt="image" src="https://user-images.githubusercontent.com/31506317/217485248-8bdc23f7-3dac-46a3-8e29-64f68f539dc6.png">

**Info:**
 - Suite version: web 23.3.0 (d7a55aa3b40c0b59761ba6f101ddd0e997e0d94a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: 
 - Transport: BridgeTransport 2.0.32

**Comment by bosomt** [comment]
**QA OK**

checked logs in app and they both work as expected 

**Info:**
 - Suite version: desktop 23.3.0 (2d228b57868b6099facbe1b7e8c5ae55e02d75c8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
