### ISSUE TITLE
Coinjoin: Cancel/resume sumbenu z-index is too high

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#6957]
**Describe the bug**
Menu is visible thru modal background

**Info:**

-   Suite Version: app
-   OS: linux

**How to reproduce**

1. Go to coinjon account, remeber it
1. Start coinjoin session
1. Disconnect device (session should be paused)
1. Connect device
1. Try to resume using submenu and wait for the button request

**Screenshots**
![Screenshot from 2022-11-21 12-34-59](https://user-images.githubusercontent.com/3435913/203043437-0585d67a-9368-4a66-9a7a-49b9d1b1f487.png)

**Comment by bosomt** [comment]
**QA OK**

<img width="495" alt="image" src="https://user-images.githubusercontent.com/31506317/205597723-db30e673-ac1e-41be-b591-f9ac1d8a8ccd.png">

**Info:**
 - Suite version: desktop 22.12.0 (70d4626089a378ac8ee00824e64c4469459792d0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
