### ISSUE TITLE
Data Analytics: Coin Control Usage

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#6959]
We want to track whether Coin control is used during transactions. 

Events to track
* Coin Control opened boolean, default: false
* Coin selection used boolean, default: false. If the coin selection is in untouched then false, or if different UTXOs are selected, then true

Best would be new attributes in `transaction-created` event with boolean value.

**Comment by bosomt** [comment]
**QA OK**

<img width="592" alt="image" src="https://user-images.githubusercontent.com/31506317/211024341-753df344-3bb8-4da1-8bd9-2910e2382650.png">

**Info:**
 - Suite version: desktop 23.2.0 (aeb1abfe2b1587e79dde501d1cac6f41f0cd4952)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
