### ISSUE TITLE
No way to go back after selecting "I have a new device"

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-suite#696]
Trezor T, fw 2.1.7

Steps to reproduce: 
1. Connect a wiped device
2. Select "Create a new wallet"
3. Select "I have a new device" (just to check this option)

Result: 
There is no way to go back
![Screenshot_20191018_114608](https://user-images.githubusercontent.com/31442634/67084399-330a8e00-f19d-11e9-9bcc-da08de355b5a.png)

**Comment by mroz22** [comment]
that should be 'fixed' now
