### ISSUE TITLE
EnableCoins: Use other imported accounts for graph

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#6971]
Currently there are some problems to load graph data for other accounts than Bitcoin and Testnet. 

The problem seems to be with fetching fiat rates after initialization.

Error: 
![Image](https://user-images.githubusercontent.com/36101761/203265764-d9830710-d6ec-4b5e-9608-5e71090fd0de.jpeg)

**Comment by juriczech** [comment]
@Nodonisko Graph tasks you are working on should resolve this, right?

**Comment by Nodonisko** [comment]
Yes it should resolve all problems hopefully.

**Comment by STew790** [comment]
**QA OK**
I tried this with the same coins as are in the screenshot and all are showing graphs and icons as well.

![image](https://user-images.githubusercontent.com/48477147/207085645-c05151e0-da02-42fc-8b23-216e82c3efa9.png)

**Info:**

Suite version: desktop 22.12.1(145) (https://github.com/trezor/trezor-suite/commit/fab845cd174199f5a8f716e43e9d4b0cc4eacd49)
