### ISSUE TITLE
Loading Funds progress bar always restart when navigating in Suite

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6982]
**Describe the bug**
`Loading Funds...`progress bar always restart when navigating in Suite

**Steps to reproduce:**
1. Add CoinJoin account
2. Wait till `Loading Funds...` progress start loading
3. Navigate in Suite and back to loading and observe behavior

**Info:**
 - Suite version: desktop 22.12.0 (daaf4fbacbc8d1f613f6b4d94de04451b9d9923d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Screenshots:**

https://user-images.githubusercontent.com/31506317/203331648-66929541-8d8b-4d4c-955b-febe2d6e8302.mov

**Comment by matejkriz** [comment]
is this gonna solve it? https://github.com/trezor/trezor-suite/issues/6912

**Comment by bosomt** [comment]
@matejkriz you can still leave to another account/wallet/settings and come back to see 0 progress :)

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
