### ISSUE TITLE
Distinguish Bitcoin-only FW changelog

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6987]
User shouldn't see changelog of `regular firmware` when is he updating `bitcoin-only firmware`.
![image (2)](https://user-images.githubusercontent.com/26002916/203516560-512f22ae-9c51-4cd9-9be3-c4b30e2bea81.png)

**Comment by hynek-jina** [comment]
As a reference: https://github.com/trezor/data/commit/090dc88304c01e33d1e541a835235e3eb4864629

**Comment by yohaaan** [comment]
The customer was confused with the Suite changelog as well. They are using a Bitcoin-only FW and yet see altcoin updates in the Suite changelog. More info: https://twitter.com/Bitbello/status/1609955400106876929

**Comment by sime** [comment]
> The customer was confused with the Suite changelog as well. They are using a Bitcoin-only FW and yet see altcoin updates in the Suite changelog. More info: https://twitter.com/Bitbello/status/1609955400106876929

This one is a little trickier but plausible, since we only have **one** Trezor Suite build.

**Comment by bosomt** [comment]
**QA OK**

Will be tested after  BTC only changelog in firmware repo is introduced.
Current dev build works as expected and i see changelog during fw upgrade when hovering over hint.

**Info:**
 - Suite version: web 24.8.0 (a707883081ddf9f3b75ececcb0e8a38732136988)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: WebUsbTransport
