### ISSUE TITLE
Show xpub of account

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#6999]
We should be able to show xpub of account, at least for debugging purposes.

**Comment by mnuky** [comment]
it should be available in account settings - working on it with designers

**Comment by bosomt** [comment]
**QA OK**

tested on multiple accounts /goerli,ltc,btc/
I see xpub text but not QR code, thats expected afaik from PR

![photo_2022-12-06 10 19 52](https://user-images.githubusercontent.com/31506317/205870896-42a31c4d-09a7-4368-bf9a-f0bd6e450e14.jpeg)

**Comment by mnuky** [comment]
@bosomt will be done later in polishing, we agreed with @juriczech
