### ISSUE TITLE
Disable setting of anonymity level when the CoinJoin is running

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7000]
![Coinjoin Running](https://user-images.githubusercontent.com/26002916/203774063-452bb46c-e467-48db-9e91-b01041e13d93.png)

**Comment by matejkriz** [comment]
@hynek-jina Just to make it clear - "CoinJoin is running" in this context means there is an existing CoinJoin session, so even if it is currently paused, right? To be able to change desired anonymity level, user have to Cancel CoinJoin, not just Pause it.

**Comment by hynek-jina** [comment]
@matejkriz Yes, exactly 👍

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.1.0 (c657469ccc2bc2cfb66a4e230013c8ef93d50e55)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision 305b7fe84d802db7f0826d07a222a886f73732f0)
 - Transport: bridge 2.0.32
