### ISSUE TITLE
Improve CoinJoin success modals

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7001]
**Success Screen**
![coinjoin done](https://user-images.githubusercontent.com/26002916/204818648-bb7d39c5-66be-488f-b31c-71662d149d84.png)

---
**Few more rounds needed**
![rounds](https://user-images.githubusercontent.com/26002916/204818685-3bec1fec-05dd-4b97-94eb-f84bef46c176.png)

**Comment by komret** [comment]
We currently don't have a straightforward way to count the "successfully coinjoined" amount nor to check whether all funds sent to coinjoin increased in anonymity. It would require saving some data along the way which is not implemented yet. Also, any calculations are further complicated by any sent or received transaction during the coinjoin. I suggest, for now, adjusting the texts and simplifying the functionality to:
1) show entire private balance (or nothing) in the success modal;
2) check whether all funds in the account are private - if not, show the second modal.

**Comment by hynek-jina** [comment]
After each round check 
- If all funds are already private → Show success modal with all private funds amount in text.
- If all funds are not yet private.
    - Check if you have more rounds available.
    - If yes → Continue with CoinJoin
    - If no → Show CoinJoin ended modal

**Comment by komret** [comment]
**QA:** See the PR for screens please. The success screen can be achieved by a successful coinjoin session or by reducing your target anonymity during the coinjoin (haven't tested myself). It would be nice if you can test this feature with two coinjoins running on the same network (different wallets on the same device)

**Comment by komret** [comment]
> After each round check
> 
> * If all funds are already private → Show success modal with all private funds amount in text.
> * If all funds are not yet private.
>   
>   * Check if you have more rounds available.
>   * If yes → Continue with CoinJoin
>   * If no → Show CoinJoin ended modal

The UTXO check after each round is not implemented. Currently, coinjoin ends only when current round number equals `maxRounds`.

**Comment by hynek-jina** [comment]
OK, we will need to take care of that in later phase.. 
Related: https://github.com/trezor/trezor-suite/issues/7113

**Comment by matejkriz** [comment]
@hynek-jina how to deal with the UTXOs too small for CoinJoin? 🤔 re-running CoinJoin is not going to help with them
![image](https://user-images.githubusercontent.com/3729633/206147101-29e66f17-07d8-4439-9275-d95f93cafcc7.png)

**Comment by hynek-jina** [comment]
It should be covered with this issue: https://github.com/trezor/trezor-suite/issues/7099
We will disable CoinJoin start if user doesn't have any suitable UTXO

**Comment by bosomt** [comment]
**QA OK**



![Image](https://user-images.githubusercontent.com/31506317/210349440-3c3c6b89-2099-4f2d-923e-0343211cda22.png)

**Info:**
 - Suite version: desktop 23.1.0 (ca103db06514e3bd973701a1d79c14eeacfefbb6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
