### ISSUE TITLE
Show feedback when Tor is slow in establishing a connection

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#7004]
## Design
[Figma](https://www.figma.com/file/pIibgxmxD0jrAa9UGJd9da/Neue-Desktop-1.5?node-id=9538%3A83531&t=ZreDr6mVLoBIdItI-4)

<img width="881" alt="Snímek obrazovky 2022-11-20 v 11 23 52" src="https://user-images.githubusercontent.com/216917/203776408-bacb2043-895e-4029-8024-6bd2dfffbbb5.png">

Note the new Tor icon.

## Spec
[Notion](https://www.notion.so/satoshilabs/Tor-connection-delay-a48a1a2795b84e57821a175e1c32a93c)

### Background
Tor is under a consistent DoS attack. Establishing a connection can be awfully slow. Reduce user friction that Trezor Suite/Tor is working as expected.

### User Story
As a Tor user
I want to know when Tor is slow
So that I don’t worry that Tor is broken

### Acceptance Criteria
Given I start Trezor Suite
And Tor is enabled
When Tor takes 5 or more seconds to connect
Then I should see: 'Tor is connecting to the network. Hang in there.'

**Comment by karliatto** [comment]
@sime I see the text in the image says "Tor is slow today, but don't worry, it's connecting" but in the section "Acceptance Criteria" it says  'Tor is connecting to the network. Hang in there.'

What is the right one?

**Comment by sime** [comment]
> 'Tor is connecting to the network. Hang in there.'

Is the correct copy. (Sorry the original screenshot wasn't updated, Figma has the copy correct)

<img width="629" alt="Screenshot 2022-12-22 at 13 18 45" src="https://user-images.githubusercontent.com/216917/209133143-5854da4e-e8d7-4b28-9e3f-5b77f7d6b1f4.png">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.2.0 (8b1289dca7e4279eca789ea2111e5e2a6bf38d7a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
