### ISSUE TITLE
Count grouped transaction as one in transaction history

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7005]
Prerequisite: https://github.com/trezor/trezor-suite/issues/7003

Suite is displaying circa 25 transactions on a page. Since we are grouping more CoinJoin transaction into one it looks confusing when page consists of only few group transactions.

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
