### ISSUE TITLE
Dependencies: ws

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#7006]
`ws` library in `blockchain-link` package has breaking changes in `8.0.0`

**Notes:**
- https://github.com/websockets/ws/releases/tag/8.0.0
- tests are failing
![Screenshot 2022-11-24 at 13 44 34](https://user-images.githubusercontent.com/33235762/203788393-70db957b-2a53-4f22-8658-0fe7ee3a6c51.png)
<img width="682" alt="Screenshot 2022-11-24 at 13 40 38" src="https://user-images.githubusercontent.com/33235762/203788402-9a711fb5-0ad5-4735-a861-a2d67cb15c49.png">
<img width="429" alt="Screenshot 2022-11-24 at 13 40 34" src="https://user-images.githubusercontent.com/33235762/203788407-e9a1ccce-70cc-4aee-b7cc-7122a750ef23.png">

**Comment by matejkriz** [comment]
older ws version triggers ` t.mask is not a function` error, see the discussion here https://satoshilabs.slack.com/archives/C059ZS5T24C/p1702311810887369 and sentry issue https://satoshilabs.sentry.io/issues/4716454172/?project=5193825

Let's bump priority of this.
