### ISSUE TITLE
Trezor suite Tor Backend issue

### ISSUE THREAD

**Issue by ghost** [trezor/trezor-suite#7008]
Hi , I want to use my own electrum server in the suite from my node via Tor .Tor is of course enabled . I use CADR ( https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder/ ) as a full node.  
1) in CADR I generated an onion address for electrs
2) I entered the address in the suite into Bitcoin -- Backend -- custom electrum server in the format : address.onion:50001:t
![Snímek obrazovky z 2022-11-24 15-16-01](https://user-images.githubusercontent.com/117933512/203805811-98309a86-e530-4828-bef1-98258de9f571.png)

Well don't work it :) what could be the problem , please

**Comment by sime** [comment]
@Whiteboxi Can you connect desktop Electrum client to your electrs backend?

Also, can you connect to electrs backend over clearnet?

**Comment by bosomt** [comment]
I just tried to connect to soem random Onion server from this list https://1209k.com/bitcoin-eye/ele.php?chain=btc
 and it worked as expected 


<img width="577" alt="image" src="https://user-images.githubusercontent.com/31506317/210233309-c84fc2e7-fa16-4f23-9c40-ecf152c83af4.png">


**Info:**
 - Suite version: desktop 23.1.0 (c657469ccc2bc2cfb66a4e230013c8ef93d50e55)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.11.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32

**Comment by ghost** [comment]
Hi so I tried some random onion server and it worked. Probably a mistake on my part. Sorry for the late reply. Are you using CADR with Suite ? Does that work?

**Comment by sime** [comment]
No, we only offer AppImage.
