### ISSUE TITLE
Add ilustration to `All funds private`

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7011]
![Group 18744](https://user-images.githubusercontent.com/26002916/203808994-ff069667-932b-45be-898f-b59c5693078a.png)

[Figma](https://www.figma.com/file/PrfGpe3axW0BBgf0UCzFyO/Exploring-CoinJoin?node-id=1%3A31768&t=TvKy2L4VSd3sjVJ6-1)

**Comment by bosomt** [comment]
**QA OK**



![Image](https://user-images.githubusercontent.com/31506317/210349539-b3f3f8a8-8d2d-48a4-8fac-f4c8b2b8b98c.png)


**Info:**
 - Suite version: desktop 23.1.0 (ca103db06514e3bd973701a1d79c14eeacfefbb6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
