### ISSUE TITLE
Add CoinJoin steps guide on empty account

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7012]
![PEA — Empty](https://user-images.githubusercontent.com/26002916/203809521-9676be71-f395-4525-8778-17573c8d6ee4.png)

**Comment by dahaca** [comment]
@hynek-jina Since we are not saving any info regarding coinjoin, if a user clicks Got It and reloads the page, the box will be opened again. Does it still make sense to include the button?

**Comment by hynek-jina** [comment]
@dahaca What if user remembers the wallet?

**Comment by dahaca** [comment]
True! Since if they won't they will be returning to the innitial state it's OK that it's gonna be open again.

**Comment by komret** [comment]
Frankly, I don't think it is worth bothering with collapsing the box and remembering the state because the explanation is only visible as long as the account is empty. But anyway, it is already done :)

**Comment by hynek-jina** [comment]
Hi,
I think that `got it` button should remove that element.


https://user-images.githubusercontent.com/26002916/213663380-1faf6b87-b3d3-47ea-a68f-dad10a1584b3.mov

**Comment by hynek-jina** [comment]
As discussed on standup.. @dahaca 
Please remove the `Got it` button and minimising functionality..
_It is visible only in case of empty account and there is no strong benefit in minimising that element_

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.2.0 (aebe81957c19c1b289f016cca5cb6b2c7808e1bf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by hynek-jina** [comment]
This is not implemented as discussed above.
**Please remove collapsing and `Got it` button**

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.3.0 (3d9487a67690ed0411a2c4081c685308c0b146ef)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
