### ISSUE TITLE
Change anonymity level format from `1 in 10` to plain `10`

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7013]
**Reasoning**
_`1 in 10` format is not intuitive for the user. They expect the first number to be changeable.. It doesn't help to illustrate the meaning of being one of x people._

**Where it appears**
- Anonymity level settings
- Transaction details
- Coin Control

**Comment by komret** [comment]
**QA:** See PR for screenshots.

**Comment by bosomt** [comment]
**QA OK**
