### ISSUE TITLE
Suite does not recognize device in bootloder mode (older firmware versions)

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-suite#702]
Trezor One

Steps to reproduce: 
1. Connect a device with older fw (1.5.2 / 1.6.0) in bootloader mode
Result: Suite keeps saying Connect Trezor to Continue

If I connect the device normally I get "Switch to bootloader screen", but it is impossible to switch to bootloader.

Starting from the fw version 1.6.3 it is okay.

**Comment by mroz22** [comment]
Can you confirm it is still happening? I have just tried with 
```
Features (30 bytes) {
    bootloader_mode: True,
    firmware_present: False,
    major_version: 1,
    minor_version: 5,
    patch_version: 1,
    vendor: 'bitcointrezor.com',
}
```

and it worked.

**Comment by pankrats** [comment]
It is still happening with the desktop version of Suite :O
Firmware 1.5.2
Install button is irresponsive. 
![2019-11-29 13 11 58](https://user-images.githubusercontent.com/31442634/69868531-3fa8f880-12aa-11ea-95dc-42d712969f86.jpg)
