### ISSUE TITLE
Move coinjoin from `debug` mode to live production

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7031]
Starting of 23.3.1
- [x] Both mainnet and testnet should be available outside debug mode  
- [x] Switch to zkSNACKs coordinator

**Comment by bosomt** [comment]
**QA OK**

no idea how to check second ✔️  but suite reports `I agree to the Trezor Suite Terms and zkSNACKs Coordinator Terms` /no info about coordinator in SUite log/

**Info:**
 - Suite version: desktop 23.4.0 (f4dee18ecd17bcce530ae7837c5a34a7b922762a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
