### ISSUE TITLE
Drop dated bech32 promotion 

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#7036]
**Design:**
<img width="1552" alt="image (2)" src="https://user-images.githubusercontent.com/216917/204041654-48172bb1-5556-4674-a97e-765b5f5cd2d3.png">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.12.0 (9eda6a34372ed709612b67c006f2602094d2c4c7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0
 - OS: MacIntel
 - Screen: 1584x990
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
