### ISSUE TITLE
CoinJoin modal blocked by adding passphrase

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7046]
**How to reproduce**

1. Start CoinJoin
1. Once there are only few seconds remaining to start another round start adding new wallet (another passphrase)
1. Instead of signing modal I received empty page.. and the discovery was lost..

![Snímek obrazovky 2022-11-28 v 13 19 17](https://user-images.githubusercontent.com/26002916/204276565-8f1ca705-b772-4f55-96b6-d3c2d525c2de.png)

![Snímek obrazovky 2022-11-28 v 13 20 21](https://user-images.githubusercontent.com/26002916/204276577-226d0d8c-29ed-437b-b9e2-01fe5551998e.png)

[trezor-suite-log-1669634390864.txt](https://github.com/trezor/trezor-suite/files/10103656/trezor-suite-log-1669634390864.txt)

**Comment by hynek-jina** [comment]
@trezor/qa Can you please try to reproduce it? 🙏

**Comment by bosomt** [comment]
Yes. Opened passphrase/add hidden wallet modal and waited for tx signing,
Looks kinda broken but im able to get back via wallet selector /not via coin selector ;(/

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/31506317/212913731-1669590d-61f0-4350-bfb0-c851e78ff7c0.png">


**Info:**
 - Suite version: desktop 23.2.0 (8b1289dca7e4279eca789ea2111e5e2a6bf38d7a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by szymonlesisz** [comment]
i think it was solved by [this PR](https://github.com/trezor/trezor-suite/pull/7656) - merged 22.02
@bosomt could you check it again pls?

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 23.7.0 (d81e7e2a7c127bc4e494b69375831cd4b0998bd8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.7.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.1 Universal (revision c3f6e8f19fd647c73b414322e287ba23cf8a0c7c)
 - Transport: BridgeTransport 2.0.33
