### ISSUE TITLE
Error page Dashboard link

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#7049]
**Describe the bug**
`Go to Dashboard` button navigates to the landing page and not to the dashboard

**Info:**

-   Suite Version: 22.11.1

**How to reproduce**

1. Go to non-existing suite route e.g. https://suite.trezor.io/web/sdfsdfdsf

**Expected behavior**
It should take to dashboard and not landing page

**Screenshots**
![lala](https://user-images.githubusercontent.com/33235762/204330117-b1a232ce-e024-461a-ac55-e4f4e2d67fb3.png)

**Comment by matejkriz** [comment]
beware of ASSET_PREFIX

**Comment by tomasklim** [comment]
@trezor/qa unable to test on sldev, please test on staging. Staging should behave the same way as production

**Comment by bosomt** [comment]
**QA NOK**

actually it takes you to web now :)

<img width="779" alt="Screenshot 2023-08-03 at 8 47 54" src="https://github.com/trezor/trezor-suite/assets/31506317/f7d9d46a-c197-4984-b653-70df7db26388">


<img width="928" alt="Screenshot 2023-08-03 at 8 47 11" src="https://github.com/trezor/trezor-suite/assets/31506317/cce7e59d-8133-4f25-88b4-697bad76c1a1">



**Info:**
 - Suite version: web 23.8.1 (11285a745786e8cd7c39ada4945f5893d7e8cd23)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0
 - OS: MacIntel
 - Screen: 2160x1350

**Comment by AdamSchinzel** [comment]
There must be some problem then with `ASSET_PREFIX` loaded from `env` variables

**Comment by matejkriz** [comment]
> There must be some problem then with `ASSET_PREFIX` loaded from `env` variables

We use ASSET_PREFIX with trailing slash as you can see here: https://github.com/trezor/trezor-suite/blob/develop/ci/build.yml/#L56

this should work: https://github.com/trezor/trezor-suite/pull/9106

**Comment by STew790** [comment]
**QA NOK**
It is not showing me the 404 page at all now and just "defaults" to the main page.

![image](https://github.com/trezor/trezor-suite/assets/48477147/733c7251-621d-4126-81df-e4fb72f89021)


**Info:**
 - Suite version: web 23.8.1 (11285a745786e8cd7c39ada4945f5893d7e8cd23)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor 
 - Transport: BridgeTransport 2.0.33

**Comment by matejkriz** [comment]
@STew790 weird, even in firefox on mac I can see the 404 page... 

anyway, please retest on next build, I just cherry picked the fix of fix

**Comment by bosomt** [comment]
**QA OK**


https://github.com/trezor/trezor-suite/assets/31506317/20e02cef-188b-4357-a075-68a230aa1269



**Info:**
 - Suite version: web 23.8.1 (c6b91601f5c333a1de056fbf0b712995a96b5d90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/116.0
 - OS: MacIntel
 - Screen: 2160x1350
 - Device: 
 - Transport: BridgeTransport 2.0.33
