### ISSUE TITLE
P2P&DCA strings missing from crowdin/messages.ts

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#7051]
**Describe the bug**
In P2P flow, while reviewing an offer, there is an untranslatable string. `Receiving address`

**Steps to reproduce:**
1. Accounts -> Trade -> Buy P2P -> Show offers -> Get this deal -> Confirm
2. Notice `Receiving address`, which is untranslatable.

**Info:**
 - Suite version: web 22.11.1 (73ccf723353e0575a64f58b2f5775d20f072311f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: model T 2.4.3 Universal (revision 595b14254c1abb2be3f69e42c7932f1eca8cf1b1)
 - Transport: WebUsbPlugin

**Screenshots:**
<img width="1463" alt="Screenshot 2022-11-28 at 19 39 35" src="https://user-images.githubusercontent.com/75733878/204357001-85658130-12de-451a-a8af-58fcb82af3eb.png">

**Note(s):**
Please review https://github.com/trezor/trezor-suite/blob/develop/docs/features/localization.md and follow the steps to make sure string is properly translatable.

**Comment by jerechinsky** [comment]
@IvaFingerova please reassign to an invity dev.

**Comment by jerechinsky** [comment]
Another one in P2P flow.

<img width="557" alt="Screenshot 2022-11-28 at 19 56 18" src="https://user-images.githubusercontent.com/75733878/204358246-d3d2d5e5-3732-4a51-91f5-7bba1cf509ff.png">

**Comment by jerechinsky** [comment]
Another one in DCA flow

<img width="787" alt="Screenshot 2022-11-28 at 20 13 10" src="https://user-images.githubusercontent.com/75733878/204361513-8838a465-e610-4ecc-8e90-2a98df558aba.png">

**Comment by jerechinsky** [comment]
Another one in DCA flow after returning from Invity's website.

<img width="847" alt="202914927-4216e355-d408-430b-9146-7ea455a9d7fa" src="https://user-images.githubusercontent.com/75733878/204363097-7f3c03bf-dd14-4228-b9e2-ede0ff9bab2a.png">

**Comment by zuzjes** [comment]
Receiving address already has translation - id :  TR_P2P_RECEIVING_ADDRESS_STEP (not found in cs translations, after adding it it works perfectly fine)

**Comment by zuzjes** [comment]
Done

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.1.0 (ca103db06514e3bd973701a1d79c14eeacfefbb6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision 305b7fe84d802db7f0826d07a222a886f73732f0)
 - Transport: bridge 2.0.32

<img width="534" alt="image" src="https://user-images.githubusercontent.com/31506317/210337551-d17685a1-1b15-4c4a-8446-d776ec89076a.png">
