### ISSUE TITLE
Replace vision-camera with expo-barcode-scanner

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7055]
Expo module is much simpler than vision-camera and we only need scan QR codes. Also vision camera caused quite a lot of issues with build in past, so this should also hopefully make build more stable.

QA:
1. QR scanning
2. **All different combinations of granting/denying camera permission - try to deny, then it should show button go to setting, if you grant it here you should see camera again - try to set it to ask with every usage - try as much magic combinations as possible**

**Comment by bosomt** [comment]
**QA OK**

Tested on Android and on iPhone , latest version
