### ISSUE TITLE
Remove destroyed Tor circuits

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#7062]
When a Tor circuit is used again with user and password the SocksProxy is destroyed (https://github.com/trezor/trezor-suite/blob/develop/packages/request-manager/src/torIdentities.ts#L22), but the Tor circuit is still open and available even if it never going to be used again.
So we should use Tor ControlPort to destroy that circuit.

**Comment by mroz22** [comment]
whats the impact?

**Comment by karliatto** [comment]
> whats the impact?

Tor is clearing the circuits when they are not used, so this seams to over-optimization probably.  Since we have not seen an issue related to this in 2 years I would close it.
