### ISSUE TITLE
Disallow coinjoinning when a device is disconnected 

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#7063]
The foundation for this feature is already [there](https://github.com/trezor/trezor-suite/pull/6796). In addition to when tor is not running, the Anonymize button should be disabled when a device is disconnected. Currently CJ is paused after disconnection but could be re-enabled without a device.
   
     Here is promised visualisation for disabled CoinJoin control
| Disabled | on hover |
| --- | --- |
| ![disabled](https://user-images.githubusercontent.com/26002916/203094505-defa05f2-ff83-4c93-bd90-d13faa1ded74.png) | ![State=State8](https://user-images.githubusercontent.com/26002916/203094965-e5dea2eb-8fea-4da1-a8ca-242065ed339a.png) |

_Originally posted by @hynek-jina in https://github.com/trezor/trezor-suite/issues/6796#issuecomment-1322245402_

**Comment by karliatto** [comment]
This Issue looks like a duplicate of https://github.com/trezor/trezor-suite/issues/6908 that I am working on right now.

**Comment by hynek-jina** [comment]
Duplicity of: https://github.com/trezor/trezor-suite/issues/6908
