### ISSUE TITLE
Creating a bitcoin transaction with OP_RETURN bigger than 80 bytes.

### ISSUE THREAD

**Issue by yanchenko-igor** [trezor/trezor-suite#7064]
According to bitcoin core max size of OP_RETURN can be modified on a per-node basis with $ bicoind -datacarriersize flag. Trezor-suite doesn't allow to use bigger than 80 bytes OP_RETURN, I would really appreciate if you could remove the hard limit and use warning instead if more than 80 bytes is used.

**Comment by sime** [comment]
Hi Igor,

Thanks for the feedback, will take a note of this and track it internally. I can't say we will prioritise such a feature soon.

You are welcome to keep the discussion here.
