### ISSUE TITLE
Transaction detail polishment

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7070]
Please adjust the transaction detail according FIgma:
https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/branch/BlVnxNzUqrZkbhHgezLczh/s2-Mobile?node-id=8563%3A33626&t=7WSawB6M9vR52euv-1

Note: There is estimated time for pending transaction - do not implement it at all now, we don't have the data from blockbook yet. 

Acceptance criteria:
1. When users enters the screen with TX detail he sees following information in main area: 

- Type of transaction (Send / Receive)
- Amount of crypto
- FIAT price
- Date of the transaction
- Address from 
- Status (Pending / Confirmed + date&time of confirmation)
- Address to 
- Fee
User can copy TX ID

2. If user clicks on Parameters - toaster screen appears with following information:
- Transaction ID (user can copy the TX ID)
- Number of confirmations
- Fee rate
- Broadcast: disabled / enabled
- RBF: disabled / enabled
- Add locktime

3. If user clicks on Today's value toaster screen appears with following information about price when TX has been proceed vs today
4. If user clicks on Inputs / Outputs toaster screen appears with information about inputs / outputs
5. If user clicks on Explore in blockchain user is redirected to explorer with TX ID

**Comment by juriczech** [comment]
@mnuky Date will be formatted same way that it is currently until we have intl package ready to use in mobile app

**Comment by juriczech** [comment]
@mnuky No need to test by QA. You can verify polished changes yourself?

**Comment by juriczech** [comment]
Bottom Sheets are not implemented yet. This will be handled separately

**Comment by mnuky** [comment]
looks fine on my phones

**Comment by bosomt** [comment]
Checking ca097db version on Android tablet and
```
Parameters
Current values
Inputs & Outputs
```

modals are empty when i click on them.
Probably those are `bottom sheets` mentioned by @juriczech  :)
Tested on multiple coins.

<img width="491" alt="image" src="https://user-images.githubusercontent.com/31506317/211515467-a0dee28f-a9b7-4d09-b18d-1adc6000a6da.png">

<img width="491" alt="image" src="https://user-images.githubusercontent.com/31506317/211515562-612b9f82-56bf-4203-8015-2f7663398d43.png">

<img width="489" alt="image" src="https://user-images.githubusercontent.com/31506317/211515599-44ce2546-54a1-4780-ae48-2ac8f37e0b5c.png">

**Comment by mnuky** [comment]
@bosomt it is on purpose, content to these panels come in issue: https://github.com/trezor/trezor-suite/issues/7303
