### ISSUE TITLE
List of assets: group assets by coin

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7072]
Ad a user I would like to see my assets grouped by coin so that I can have better clarity of my assets
Figma: 

![Image](https://user-images.githubusercontent.com/84183817/205939240-f34dc6a2-c307-4a6f-8d83-07e81340a6f1.png)

Acceptance criteria:
All assets are grouped by coin and separated in the box

Out of scope: 
Search is not part of this issue, please do not even put the icon there

**Comment by juriczech** [comment]
@mnuky When user clicks on asset in dashboard, it will redirect to account list and no filtering will happen, is that correct?

**Comment by mnuky** [comment]
> @mnuky When user clicks on asset in dashboard, it will redirect to account list and no filtering will happen, is that correct?

great question - we are currently thinking how it should behave when user clicks on the Coin at Dashboard - either goes to Asset list or we will display related assets as "toast" screen immediately.

**Comment by juriczech** [comment]
I will just redirect to assets now and if bottom sheet with assets should be displayed, we'll tackle it as separate issue
