### ISSUE TITLE
Switch onion addresses to clearnet addresses

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#7076]
Due to the ongoing [instability of accessing onion services](https://status.torproject.org/issues/2022-06-09-network-ddos/) over the Tor network, migrate all onion interactions to their clearnet equivalents.

e.g. from: btc1.trezoriovpjcahpzkrewelclulmszwbqpzmzgub37gbcjlvluxtruqad.onion, to: btc1.trezor.io

Caveat: This may be the intention of the attacker.

**Comment by prusnak** [comment]
Also we need to be 100% sure we are not accessing these clearnet addresses via plain connection when in Tor mode. Every connection needs to go through Tor when in Tor mode!

**Comment by prusnak** [comment]
This is a blocker issue for the CoinJoin feature. I suggest prioritising it accordingly.

**Comment by bosomt** [comment]
**QA OK**

<img width="643" alt="image" src="https://user-images.githubusercontent.com/31506317/206191399-a144a9da-57c5-42bc-ab2e-6186f181e6fc.png">


**Info:**
 - Suite version: desktop 22.12.1 (8e04a0545667dc828b96e5aaef8e91479c4edc60)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
