### ISSUE TITLE
Welcome intro while first open the app

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7082]
When user opens the app for the first time I would like to show him welcome page where we explain what the app is for and how it works

Figma designs: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14524%3A54334&t=6sgLGbZic2eL1Qbh-1

Acceptance criteria:
- When user opens the app for the first time, he goes through the welcoming screens
- If the users got out of the app before finishing the welcome flow, we display it again
- Finished welcome flow is when user clicks on "Continue" on the last screen

**Comment by bosomt** [comment]
**QA OK**

tested on latest version of iPhone
