### ISSUE TITLE
Analytics settings/consent screen

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7083]
As a user I would like to decide whether to share data with Trezor. 

Acceptance criteria:

- When user open the app for the first time and went through the welcome screens, we display screen with analytics consent
- If user gives us consent to track him, we switch on the analytics tracking
- If user does not give us consent to track him, we switch off the analytics tracking
- User can change his mind later in the settings, section Privacy&Security and change the ON / OFF of analytics
- if user does not give consent, we don't track him at all (incl. data for Sentry) - the only exception are necessary data to make the app work (e.g. device ID)

Figma for page during welcome flow: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14534%3A55225&t=JTNkRCRzayxqzs3w-1

Figma for settings of the analytics in settings: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=12341%3A93756&t=P2k6RaOvzc2szKQl-1

**Comment by Nodonisko** [comment]
Should this also affect Sentry error reporting?

**Comment by bosomt** [comment]
**QA OK**
