### ISSUE TITLE
App quits when clicking on certain asset or transaction

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7086]
Sometimes the app crashed when clicking on asset or transaction. 

Examples:
LTC (I will provide XPUB separately via slack)
Video:
https://user-images.githubusercontent.com/84183817/205053807-6f8021d7-de9b-464e-9de3-a60a824293bf.mov

BTC Testnet (XPUB in slack)
Video: 
https://user-images.githubusercontent.com/84183817/205054265-7a7209c4-5955-42d7-aa7e-8e6d4f0968ae.mov

ETH Test Goerli (XPUB in Slack)
Video:
https://user-images.githubusercontent.com/84183817/205054690-9d6036bb-b335-4532-8fad-facca696cc9e.MP4

**Comment by Nodonisko** [comment]
QA: it crashed only for some users, I was not able to reproduce it, but users reported that it doesn't crash anymore

**Comment by bosomt** [comment]
**QA OK**

tested in build 22.12.1 (139) 70d4626
