### ISSUE TITLE
FIAT balance on altcoins is incorrect on asset detail

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7090]
Balance of altcoins displayed incorrect balance on asset detail
Example ETH - video attached:
https://user-images.githubusercontent.com/84183817/205077542-e23b5610-4ee8-4766-b604-92bf5c453595.MP4

**Comment by bouchja1** [comment]
I investigated it a little bit and this is related somehow to a graph. The fiat balance represents a selected graph point. But I couldn't reproduce the state from your attached video. My values are either 0 (if a graph is not shown) or sth around 33 USD if a graph is shown.

**Comment by mnuky** [comment]
Might be fixed with new version of the graph, lowering the priority and wait if it will work with the new graph

**Comment by Nodonisko** [comment]
Moving this to QA, since this value originating from graph data and this part was completely refactored.

**Comment by bosomt** [comment]
**QA OK**

tested on Android and multiple coins. FIAT value match Suite app.
