### ISSUE TITLE
Offer option to remember whole Wallet during CoinJoin discovery

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7098]
CoinJoin account discovery is using more different technique than regular accounts. And as a result it takes circa 2 minutes with empty account, but this time will increase with every new bitcoin block mined and every transaction that user has in his history.

So it is recommended to remember account, so user doesn't need to do this on every app launch.

![PEA — Loading](https://user-images.githubusercontent.com/26002916/205248971-9dde9978-acfd-42bc-ad8f-c8f997f8dae9.png)

- Wallet is not remembered on default.
- Option to remember wallet is visible only during the initial discovery (not when the account is loaded and only syncing)

**Comment by komret** [comment]
@hynek-jina @b-irving Can you please check the copy (Note and the text below)? It does not make much sense to me and might be too long.

**Comment by hynek-jina** [comment]
@komret We will review all the coinjoin copy next week.. So feel free to leave it `suboptimal` :-)

**Comment by matejkriz** [comment]
analytics added https://github.com/trezor/trezor-suite/pull/7463

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 23.2.0 (1715c7a70a103c5ce94f9ca7a9e5075b06d99746)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision 461f5667777514e6921ec1a53ca3d023a2a6a092)
 - Transport: bridge 2.0.32
