### ISSUE TITLE
Disable coinjoin start if all UTXOs are too small

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7099]
_Followup of https://github.com/trezor/trezor-suite/issues/6756_

- Disable coinjoin if all non-privat funds are too small 

Smaller then:
-  `mininputvalue + (input size * fee rate) + (output size * feerate)`.
   - `mininputvalue` is 5 000 but we read it dynamicly from the coordinator.
   - taproot input size  `58`
   - taproot output size `43`
   
   
 P.S.: We are not able to find out if all of your funds are banned by the coordinator, there is no way to do it before running coinjoin. And we don't want to disable coinjoin even if all of your funds are not confirmed - it will just take more time then coinjoin actually started, but it should not be a blocker.

**Comment by matejkriz** [comment]
Not sure what message to display to the user in that case. So far I put there quite generic: "Too small amounts to be used in coinjoin."
<img width="703" alt="image" src="https://user-images.githubusercontent.com/3729633/213721156-aaaad438-5137-4ea9-87bc-378a74ea9a0c.png">

We can advise to add more funds or consolidate - but consolidation, especially on coinjoin account, is probably too complex without better explanation. What about some explanation in Suite Guide and link from here? @hynek-jina @b-irving ?

We can use in the message the minimal value for UTXO to be suitable for coinjoin, and it's something like 5202 sats (depending on the fee rate), but again – that would be probably too complex? As you can see on the screenshot - I have 24 999 sats available, but it's split to 5 UTXOs...

I believe the main use case for this warning can be that user sent some very small amount just to test it? Then mentioning the minimal amount would be very useful...

**Comment by hynek-jina** [comment]
Thank you @matejkriz 
I wouldn't complicate that with consolidation. Your message sounds good to me. 

_Maybe we could consider `auto-consolidation` as a followup? 🤔 
Basically when the mining fee is relative low and you have more small amounts utxo we could build the transaction for user... but it's completely different and quite complex topic._

**Comment by bosomt** [comment]
**QA OK**



![Image](https://user-images.githubusercontent.com/31506317/216950114-925df9f1-0844-4cd1-9d15-828ed379e746.png)

**Info:**
 - Suite version: desktop 23.2.1 (bcfbc9ffb59b51f6c7ecb58d529769ca0db2f7b1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
