### ISSUE TITLE
Change logic of progress calculation of CoinJoin progress bar

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7108]
**Current behaviour:**
`signed rounds` / `confirmed rounds`

**Proposed improvement:**
$AL$ = `anonymity level` - 1
$DAL$ = `desired anonymity level` -1

$$progress = {\sum(amount_i* min(AL_i,DAL))\over\sum amount_i * DAL}$$

If $DAL = 0$ then $progress = 1$

**Comment by hynek-jina** [comment]
https://github.com/trezor/trezor-suite/pull/7261#issuecomment-1369549357

**Comment by STew790** [comment]
**QA OK**
After discussion with @hynek-jina this was observed already throughout the recent CJ testing and it is fine. We will definitely still monitor this in the upcoming tests though.

**Info:**

- Suite version: desktop 23.2.0 (https://github.com/trezor/trezor-suite/commit/45c816db15aea3444dea02e0edc777748ef8052c)
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
- OS: Linux x86_64
- Screen: 1920x1080
- Device: model T 2.5.4 Universal (revision ff35c77bad82c7acac1df6245940ebe0d6454642)
- Transport: BridgeTransport 2.0.32
