### ISSUE TITLE
Distinguish requested and expected number of CoinJoin rounds

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7113]
**Curent behavior:**
User confirms number of CoinJoin rounds that is Trezor allowed to sign. It corresponds with a rough estimate how many rounds will be required to reach desired anonymity level. 

**Expected behavior:**
Distinguish `confirmed rounds` and `rounds needed` estimate. (Many rounds might fail)
_ie. user confirms 50 rounds on his Trezor even though Suite estimates only 10 rounds will be needed._

- Minimal estimated time should be 1 hour - never show shorter estimations than average time per round (~1 hour, configurable via message-system, see `roundsDurationInHours`).
_This is a new requirement from discussion of @hynek-jina and @matejkriz_
  - reasoning: even the last round needed (you almost achieved target anonymity and you are in round) can be broken by someone. If we show you the estimation 1 hour and you suddenly see modal that coinjoin was successful, it's fine. 

This is all about number of rounds to be confirmed on Trezor device during coinjoin start and those two places in UI:
![image](https://user-images.githubusercontent.com/3729633/217593135-72089c43-d31e-475a-96f8-db5868b2a78c.png)
![image](https://user-images.githubusercontent.com/3729633/217593214-6a4a8199-c35f-4031-899e-107b9ade8b46.png)

- Rounds needed estimate should be recalculated after every round based on the gained anonymity.

- We don't want to show remaining rounds in status bar because we ask for much more rounds than hopefully needed. We show time estimate till end of coinjoin session instead (same info as in "circle" status).

- We need to be able to dynamically set:
  - `avgAnonGainPerRound`  - average anonymity gained per one round that we know from analytics https://github.com/trezor/trezor-suite/issues/7381
  
  - `roundsFailRateBuffer` - multiplier for number of rounds requested to be allowed by Trezor device. It should be high enough so most of the users are able to achieve desired anonymity, but not excessive high so users are not afraid of too much fees by transactions. It should be basically average count of blame rounds plus little buffer.
  - `roundsDurationInHours` - how long the round takes in average

- The maximum number of rounds that Trezor will allow (with strict safety checks) which is 500 is not forced to not complicate setup for our robots and because we don't allow target anonymity higher than 100 so if avgAnonGainPerRound is at least 1, and roundsFailRateBuffer lower than 5 it should never ask for such high number of round to be confirmed.

**Comment by andrewkozlik** [comment]
- Note that `rounds needed` should be an internal value. Only `confirmed rounds` should be displayed to the user in Suite, so that we don't confuse them with two different values.
- The maximum number of rounds that Trezor will allow (with strict safety checks) is `MAX_ROUNDS=500`.
- We need to multiply the number of rounds needed by the average number of rounds signed per one successful round (`BLAME_ROUND_MULTIPLIER`). I am not sure what this should be 3, 4 or 5? This value may change in time based on network conditions, so it would be good to make it configurable remotely via the messaging system.

Thus we have:
```
confirmed_rounds = min(BLAME_ROUND_MULTIPLIER * rounds_needed, MAX_ROUNDS)
```

**Comment by hynek-jina** [comment]
`rounds needed` is visible in the UI indirectly. We use it for calculation of time needed...

**Comment by STew790** [comment]
**QA OK**
Consulted with hynek. Approving.

**Info:**
 - Suite version: desktop 23.3.1 (76c3579c21da2debfcc2f2124875974f201e84f1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.1 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision e2416bcec2072baf65dda2d3c2359cc7217753bc)
 - Transport: BridgeTransport 2.0.32
