### ISSUE TITLE
Improve CoinJoin time needed estimate

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7114]
**Curent behavior:**
- (skipping off) →  1 hour
- (skipping on) →  2,5hour

**Expected behavior:**
- (skipping off) → `constant` (= 1 hour)
- (skipping on) → `constant` / `skipping frequency` → `1 hour` / `5/4` → 1,25 hours (1 hour and 15 minutes)  

_Related to: https://github.com/trezor/trezor-suite/issues/7113_

**Comment by andrewkozlik** [comment]
I am not sure what is meant by `constant`, but the time required when skipping is off should depend on the number of rounds needed.
- `TIME_PER_ROUND`: The average time it takes to successfully complete a round. This value may change based on network conditions, so it would be good to make it configurable remotely via the messaging system. Actually it would be best if the coordinator communicated this value in the status, but I am not sure whether it does anything like that.
- (skipping off) → `rounds_needed * TIME_PER_ROUND`
- (skipping on) → `rounds_needed * TIME_PER_ROUND / skipping_frequency`

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.1.1 (5d418b5646266ae2d0bb2e40919a3954fe47e462)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
