### ISSUE TITLE
Integration tests on Mac using trezor-user-env are not not working reliably

### ISSUE THREAD

**Issue by martinboehm** [trezor/trezor-suite#7119]
There is a strange issue (maybe multiple issues) that make writing of integration tests problematic. On some Macs it seems to work, however multiple developers are reporting issues. 

Here I document issue I have on my Intel Mac:
When using Bridge version 2.0.32, the Suite cannot connect properly to Trezor, reporting issues like this:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/11609674/205344550-5d70c727-6fe6-4845-892d-7da2154aac41.png">

When manually continuing in the browser and retrying multiple times, the connection to Trezor eventually succeeds but subsequent Trezor communication is unreliable. In the network tab, the failing calls are `http://127.0.0.1:21325/call/<n>` with responses {"error":"device disconnected during action"}.

I observed that when manually switching to Bridge version 2.0.27, the problem disappears.

I tried to initialize in one of the tests to start the Bridge 2.0.27 by `cy.task('startBridge', '2.0.27');`, however the Bridge gets restarted at some moment to the newest version.

**Comment by mroz22** [comment]
Ha, I believe I found whats going on here. Stay tuned...

**Comment by mroz22** [comment]
Maybe this is no longer an issue?

**Comment by mroz22** [comment]
reopen if problem persist, I am now on mac and I am not seeing it.
