### ISSUE TITLE
Account filter hiding all accounts when account is deleted

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7124]
1. Add multiple accounts
2. Go to account detail
3. Pick one and delete it
4. It will take you back to accounts overview but no accounts are visible

Similar issue will happen when you have for example BTC and ETH account. If you will open BTC account detail and then go back you will se only ETH accounts.

**Comment by juriczech** [comment]
I already brought this up with @mnuky and it's known issue. Designers are working on this apparently.

**Comment by Nodonisko** [comment]
I don't think it's related to design, this is just bug that is somehow wrongly resets filter after opening account detail or deleting account. This will happen even if filter will look like differently.

**Comment by mnuky** [comment]
I can't reproduce the bug @Nodonisko. When I delete the asset, it leads me back to My Assets page and I see all remaining assets. Or am I missing something?

**Comment by Nodonisko** [comment]
Did you tried it with different account types like BTC,ETH...?

**Comment by Nodonisko** [comment]
@mnuky Closing this because filter by coin type which was cause of this issues was removed during some refactorings, so it's basically solved.
