### ISSUE TITLE
CoinJoin testing log and warning banner

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7125]
~~⚠️ _Prepare commit for testing purpose only. This shouldn't be merged into develop_ ⚠️~~ EDIT: plan is to test on EAP version, so it has to go to develop.

When accessing CoinJoin account:
- ~~Delete previous log (if exists)~~
- [x] Start collecting new log (into dedicated folder)
- [x] Display non-closable banner in CoinJoin account: "CoinJoin account is currently in testing phase. Don't use your private coins."

**Comment by hynek-jina** [comment]
We will not be deleting existing logs.
But this logs will be stored in Suite folder and deleted with Suite uninstall or general data wipe...

**Comment by matejkriz** [comment]
> We will not be deleting existing logs.
> But this logs will be stored in Suite folder and deleted with Suite uninstall or general data wipe...

Suite folder is not deleted on uninstall by default, at least not on Mac if you don't have some app cleaner utility.

**Comment by matejkriz** [comment]
The logging to file **started when user activate the Debug menu and stop when Debug menu is deactivated** so we can use it not only for CoinJoin but also for other internal debugging purposes. Those log files are not deleted automatically so if somebody use debug mode extensively and never delete Suite data folder it can grow. If that's a problem, I'll come up with an automatic deletion.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.2.0 (aeb1abfe2b1587e79dde501d1cac6f41f0cd4952)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
