### ISSUE TITLE
Dropdown indicator in add account modal pointing in wrong direction

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#7132]
**Describe the bug**
Dropdown indicator in add account modal pointing in wrong direction after you open and close selector.
When you select coin again its pointing in correct direction

**Steps to reproduce:**
1. Navigate to add account modal
2. Open and close dropdown selector
3. Observe dropdown indicator

**Info:**
 - Suite version: desktop 22.12.0 (90d0cef8165b51851cf4d6543836069fd9be56d6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/205858322-0fbf7de3-18a2-4984-b97a-8c0bb9fb9a46.png)

https://user-images.githubusercontent.com/31506317/205858207-a419b4e2-bc41-4337-8542-6300503309b3.mov

**Comment by zvolcsey** [comment]
Hi, can I help to solve this issue?

**Comment by bosomt** [comment]
I was able to reproduce issue in Send dialogue too

how to reproduce:

1. Open dropdown selector
2. Do not select anything, just close it again
3. ˄ is pointing in incorrect direction.

<img width="253" alt="image" src="https://user-images.githubusercontent.com/31506317/206408112-50d371ff-be36-43ff-ad49-2cb722c43b83.png">


**Info:**
 - Suite version: desktop 22.12.1 (8e04a0545667dc828b96e5aaef8e91479c4edc60)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by bosomt** [comment]
**QA NOK**

issue still present


**Info:**
 - Suite version: desktop 23.6.1 (bddd516378beadfcff94523e7c94834ba14f147f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.6.1 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: 
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
fixed in https://github.com/trezor/trezor-suite/issues/7132
