### ISSUE TITLE
Receive flow UI polishing

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7134]
As a user I would like to create receive address via mobile in order to be able to receive crypto from my phone. 

There is already receive flow in the app, there are some UI adjustments needed.

Figma designs: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=10001%3A54065&t=tnvUByaahI2Qdp2u-1

Acceptance criteria:
- User can access receive flow via menu or directly from asset detail
- When user clicks on Receive via menu, he has to choose from assets where he would like to create receive request
- When user clicks on Receive directly in asset detail, he goes directly to receive screen
- On receive screen user sees the asset which will be used for receive request, blurred text with content explaining the risk of creating receive address without connected trezor (This part will change a bit from UI perspective)
- NOTE: Ignore the part with "Request specific amount" - it is out of scope for now
- If user clicks on Show address, QR code and receiving address is displayed
- User can share the address
- User can copy the address

**Comment by bosomt** [comment]
Acceptance criteria checked,
found only one issue and that is `Good to know` text contains link that is not valid and system is not able to open it.

Tested version: 02d9180 - [develop] - Feat\/receive flow polishing (#7454)

![image](https://user-images.githubusercontent.com/31506317/215761393-1bdabf26-183d-459e-94fb-4cc2ce6cf681.png)

**Comment by mnuky** [comment]
@bosomt known task - the article does not exist yet, there is follow up task for that https://github.com/trezor/trezor-suite/issues/7486

**Comment by bosomt** [comment]
then **QA OK** :)
