### ISSUE TITLE
Discreet mode polishing

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7137]
As a user I would like to have the possibility to hide the balance in my app in order to prevent others to see it while I'm using it.

**Acceptance criteria:**
- User can switch on / off the "Hide balance" feature in the Settings, in section Privacy & Security
- When user switch option in the Settings for the first time, he gets notified that he can do it next time via holding the amount on the dashboard
- User can trigger the context menu on the homepage
- In the context menu user can switch on/off visibility of balance
- When user switch on "Hide balance" feature, all balances are blurred

I would suggest to split the issue into 2 deliverables in order to save some effort: 
1. Enable discreet mode in Settings (Prio 1)
2. Enable discreet mode via context menu (Prio 2)

Figma design for Switcher in Settings (PRIO 1): https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14455%3A112977&t=5Yx3LWHGoCszoP1e-1

Figma for whole concept of Discreet mode
Figma design: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/branch/58Gop0xL5XvNnCZjP7esq9/%5Bs2.0%5D-Mobile?node-id=10568%3A56622&t=XLmuhdeR7L0odlNQ-1

```[tasklist]
### Tasks

**Comment by mnuky** [comment]
Related bug: https://github.com/trezor/trezor-suite/issues/7945

**Comment by mnuky** [comment]
OK for me

**Comment by bosomt** [comment]
**QA OK**

 tested on dev version 233 on iPhone 11
