### ISSUE TITLE
About us screen

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7138]
As a user I would like to access about us page in order to find out more information about the app, Terms&Conditions, Privacy policy and possibilty to give feedback

There is a screen in the app with following structure:
Header
Paragraph with text about us 
Button with link to FB - https://www.facebook.com/trezor.io
Button with link to Twitter - https://twitter.com/Trezor
Button with link to Github - https://github.com/orgs/trezor/projects/61/views/7

LInk to Privacy Policy - PDF: https://trezor.io/content/wysiwyg/ToU/privacy-policy.pdf
LInk to Terms&Conditions - PDF - attached - @juriczech can we put this document somewhere temporarily until launch? 

[\[WIP\] Suite Terms of Use - April 2023 (incl. Mobile App).pdf](https://github.com/trezor/trezor-suite/files/10871785/WIP.Suite.Terms.of.Use.-.April.2023.incl.Mobile.App.pdf)

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=12938%3A71922&t=9W2PyXu59BEoT0Bc-1

plus version of the app and last commit hast (mentioned in task: https://github.com/trezor/trezor-suite/issues/7335)

```[tasklist]
### Tasks

**Comment by Nodonisko** [comment]
Follow up #7335 include some version, commit hash etc.
