### ISSUE TITLE
Secure the app with PIN & Biometric

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7139]
As a user I would like have possibility to secure my app with Biometric in order to increase the security of my data in the app. 

Acceptance criteria:
**PRIO 1**
- User can switch on the Biometric in Settings - Privacy & Security
- When the Biometric is switched on, we verify user whenever he opens the app, even when the app runs in the background
- If the Biometric fails twice, we ask for Device pin

**PRIO 2**
- User can allow Biometric during welcome flow

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=14455%3A112977&t=n4mtiRANeb6gjOX0-1

**Comment by bosomt** [comment]
**QA OK**

- tested on Samsung A50 Android devel version `23.5.1 (427)`

/we will add more results from different platforms/device /

**Comment by bosomt** [comment]
**QA NOK**

tested in latest dev version 429 
Android Samsung tablet S7 FE

1. Enabled bio-metrics, restarted app.
2. app asked me for pin /no face unlock is setup on device/
3. cancelled PIN dialogue
4. there is no fall back and app freezes in state like on screenshot forever

maybe we can consider some kind of message or termination of app when there is no correct PIN or face response ?

![Screenshot_20230525_105713_Dev-TrezorSuite](https://github.com/trezor/trezor-suite/assets/31506317/8abce4d2-61c5-416a-ba8a-39170c3b229f)

**Comment by mnuky** [comment]
QA NOK On Nokia 7.2 Device
When I switch on the biometric, it asks me for Phone PIN even if the Biometric is available
Biometric is triggered when the app is closing but not when the app is opening - watch the video

https://github.com/trezor/trezor-suite/assets/84183817/1f7951d3-104d-48d0-8ed0-c71822abbb15

**Comment by bosomt** [comment]
Same here, ended up with bio popup and no app :)



![Image](https://github.com/trezor/trezor-suite/assets/31506317/e59c4a08-c1d7-4235-8832-2f7b7f927c8c)

Samsung Android A50 v 23.5.1 (429)

**Comment by bosomt** [comment]
**QA NOK**

app is asking me for PIN/bio when entering `Privacy & Security` section
this is causing that it asks you twice for PIN/bio when enabling biometrics or when accessing app when last time you visited `Privacy & Security` section

tested on iPhone devel version  286
tested on Android devel version 434

**Comment by juriczech** [comment]
https://github.com/trezor/trezor-suite/pull/8632

**Comment by juriczech** [comment]
@bosomt2 When [this action](https://github.com/trezor/trezor-suite/actions/runs/5196700111) finishes running, biometrics overlay feature (https://github.com/trezor/trezor-suite/pull/8647) should be added to the biometrics flow. If its QA OK, we can then move this issue to approved.

**Comment by bosomt** [comment]
**QA OK**

ios develop version 23.6.1 293
And develop version 23.6.1 442

🎉
