### ISSUE TITLE
Enable import more coins polishing

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7140]
As a PM I would like to polish the first part of importing the XPUB in order to increase the UX. 

**Acceptance criteria**
First step of importing starts with selection of the coin
Coins are ordered by most used once: BTC, ETH, LTC, DOGE, ETH classic, ADA, BTC Cash, XRP, Dash, ZCash, BTC Gold, Vertcoin, Namecoin, Digibyte
Testcoins are always behind the coins in order: BTC Testnet, BTC Regtest, ETH Goerli, ETH Ropsten, Cardano Testnet, XRP Testnet
After user picks the coin he is moved to second step to scan the XPUB
User can change the coin at 2nd step by clicking on the "change" - the page with coins appears again
Number of steps in header is extended to 4 steps

![Image](https://user-images.githubusercontent.com/84183817/205949618-59bc8e6d-c521-402c-9395-8639a33f82a0.png)

**Comment by bosomt** [comment]
**QA OK**

Tetsed on Samsung Android tablet version  7e43b20
