### ISSUE TITLE
Simplify CoinJoin confirmation page

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7163]
- Remove strategy selection (`Recommended`/`Fast`)
- Remove metrics
- Remove redundant tickbox
- Add reassurance about `time expectation`, `disconnection option`, and `bitcoin doesn't leave Trezor` 

![confirmation](https://user-images.githubusercontent.com/26002916/206179780-7dbebfcc-9632-4f3d-adbd-427c920173ec.png)

This has an impact on `custom setup` but that part is not necessary for coinjoin MVP.

**Comment by komret** [comment]
Some nitpicks:
The Trezor image is not consistent with the other two and does not look good with dark theme.
"Coins stay in your Trezor" sounds a little confusing (there are no coins in the device).

![Screenshot 2023-01-20 at 17 50 57](https://user-images.githubusercontent.com/42465546/213759058-e7148505-9eb4-411b-a22c-466bd180071f.png)

**Comment by hynek-jina** [comment]
Thank you @komret 
We will doublecheck the copy with Ben..
And I will ask Ondra about 3D model of Trezor..

**Comment by matejkriz** [comment]
Also the value of service fee seems to be visually too disconnected from the label, I put comment in Figma.

**Comment by matejkriz** [comment]
> We will doublecheck the copy with Ben..

"You can keep your laptop and Trezor locked" is also confusing,  if you lock your laptop and it goes to sleep, coinjoin is paused

**Comment by bosomt** [comment]
**QA OK**

looks like this now:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/31506317/215434345-c437ee21-03ba-4a22-a947-76c04485d25a.png">

**Info:**
 - Suite version: desktop 23.2.0 (1715c7a70a103c5ce94f9ca7a9e5075b06d99746)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision 461f5667777514e6921ec1a53ca3d023a2a6a092)
 - Transport: bridge 2.0.32

**Comment by bosomt** [comment]
**QA OK**

<img width="652" alt="image" src="https://user-images.githubusercontent.com/31506317/215435257-3a8fa1b7-2c0c-4c7a-8d09-8590683c25d1.png">


**Info:**
 - Suite version: desktop 23.2.0 (1715c7a70a103c5ce94f9ca7a9e5075b06d99746)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision 461f5667777514e6921ec1a53ca3d023a2a6a092)
 - Transport: bridge 2.0.32
