### ISSUE TITLE
Communicate potential problems at CEX if using CoinJoin

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7168]
![Snímek obrazovky 2022-12-16 v 10 55 49](https://user-images.githubusercontent.com/26002916/208072745-6e7173aa-8982-4bf2-b600-b3de0ffea822.png)

**Comment by matejkriz** [comment]
Reopened - it has to be visible only in coinjoin account.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 23.2.0 (1715c7a70a103c5ce94f9ca7a9e5075b06d99746)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
