### ISSUE TITLE
Fetch initial configuration file

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#717]
We need to think about future compatibility.
- how to add firmware releases info (releases.json) in to existing build without mandatory app update (there is no need to download whole suite app to provide new firmware)
- how to disable support for future firmware with breaking changes (firmware is no longer compatible with installed version of suite)
- how to disable certain coin/methods support for future firmware with breaking changes

other essential settings added retrospectively to existing build (version)

**Comment by mroz22** [comment]
> how to add firmware releases info (releases.json) in to existing build without mandatory app update (there is no need to download whole suite app to provide new firmware)

maybe connect could have method "forceUpdateConfig" which would asks trezor.io for new data and replace them in connect instance?
