### ISSUE TITLE
Make the requests from Suite to WabiSabi coordinator looks the same as those from Wasabi wallet

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#7182]
- We need to remove HTTP headers that node-fetch automatically add to requests in request filter before request and add them back to response (so node-fetch doesn't fail). Or we can consider some node-fetch alternative that would not add those headers.
- Check all requests to WabiSabi coordinator a complare those from Suite and Wasabi wallet (headers, params, ordering, delays, ...).
  -  How to do it - run Wasabi wallet, regtest, set localhost:8081/backend (our proxy) and log the request. Do the same with Suite. Compare. Align.

**Comment by matejkriz** [comment]
Is it worth doing? Coordinator knows the source of request anyway, right? @szymonlesisz

**Comment by matejkriz** [comment]
@hynek-jina coordinator doesn't need to know the source of the request (suite/wasabi) and must not know. Only affil server knows and **just for inputs**. Nobody should know about the outputs so nobody is able to connect inputs to outputs even if there is only 1 person with Suite in round and all the others using Wasabi.

**Comment by mroz22** [comment]
Note: filters batch size was temporarily changed (halved) in suite and now differs from wabisabi. [f91702d](https://github.com/trezor/trezor-suite/pull/7677/commits/f91702d2130fd6ec4acdffddaf1a3ab03f2abb2b)

We should: 
- either negotiate same batch size
- implement blockfilters on blockbooks and do complete discovery there

**Comment by matejkriz** [comment]
tested by @szymonlesisz and @ondracja, moving to Approved
