### ISSUE TITLE
something seems off - bad english on security check

### ISSUE THREAD

**Issue by jingxi285** [trezor/trezor-suite#7185]
**Describe the bug**
something seems off - quirky English on security check

**Info:**
Version: 22.11.1

**How to reproduce**

1. Wipe trezor
2. disconnect
3. connect again
4. Trezor suite will warn that trezor already initialised "Security check". Then display some bad English "Something seems off. Contact support"

**Expected behavior**
That's not an expression used in English by native speakers. Probably "Worried your device may have been compromised?  Contact support" is clearer

**Screenshots**
Someone added a screenshot to this ticket already.

**Comment by Hannsek** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/57008159/206670034-914019c1-d335-4175-8afb-89a5847e406d.png">

**Comment by jingxi285** [comment]
> <img alt="image" width="448" src="https://user-images.githubusercontent.com/57008159/206670034-914019c1-d335-4175-8afb-89a5847e406d.png">

Worth putting such serious text in **Red** please.

**Comment by sime** [comment]
@jingxi285 Thanks for the issue.

I disagree that 'Something seems off' is not familiar to native English speakers. A brief Google shows the expression used in many places. :)

It is worth re-visiting, as it is likely not so familiar to non-native English speakers.

Would you please edit the description of the issue, to only include the 'how to reproduce' section? The remaining template content should be removed if it is not specified.

**Comment by jingxi285** [comment]
@sime Hi Simon, Thank you for your reply. I updated the description, you're right I hadn't completed it.
May I politely ask are you a native English speaker as your first language? If so, how many times has someone said this expression to you?

It's a kind of archaic expression, and even then there would need to be a question mark; as it's a question. I raised this because someone told me your message meant his Trezor was faulty and was going to throw it away!

**Comment by Hannsek** [comment]
Question mark is a nice catch.

**Comment by jingxi285** [comment]
> Question mark is a nice catch.

Can it be changed? Anything is an improvement on the current text.

**Comment by Hannsek** [comment]
We will revize the whole onboarding. Then we will see if this is something that needs to be changed.

**Comment by Hannsek** [comment]
This is part of the onboarding process which will be revised later on.

**Comment by jingxi285** [comment]
What a waste of my time. 

Trezor can't even fix this defect in how it is. Trezor is wasting users time, every day.

It's a 30 second fix. You really aren't motivated to fix this are you.

**Comment by sime** [comment]
@jingxi285 Pinging you because you mentioned it originally. We are adding an **if** prefix to the sentence.

> If something seems off. Contact support.

**Comment by jingxi285** [comment]
> @jingxi285 Pinging you because you mentioned it originally. We are adding an **if** prefix to the sentence.
> 
> > If something seems off. Contact support.

Thank you, but that is still bad English. Politely I ask, are you a native English speaker? It confuses non-native speakers, Continental European guy asked me, that's why I raised the ticket.

In English the expression would be "If something seems wrong, please contact support". However, that of course misses the context. We don't put fullstops in the middle of sentences like that either in English.

However, what I suggested initially is best.
"Worried your device may have been compromised? Contact support"

Why not speak in your team to all Native English speakers? That's usually USA, Canadians, UK, Ireland, Aus & NZ etc

**Comment by sime** [comment]
> Politely I ask, are you a native English speaker?

I am a native English speaker.

And thanks for your inputs.
