### ISSUE TITLE
Difficult to read grey text on trezor suite and trezor.io

### ISSUE THREAD

**Issue by jingxi285** [trezor/trezor-suite#7191]
**Describe the bug**
Trezor suite uses hard to read grey text on white background. Same issue on multiple different computers, I asked a colleague and they feel the same.
I'm writing this on github, which has chosen appropriate text colors for the background. Could the Trezor suite be updated to be black text on white background?

The trezor.io website suffers the same issues. eg the version number display for the trezor suite is tiny and nearly unreadable in grey text on a white background.

**How to reproduce**
1. use latest trezor suite. Or look at trezor.io download page version number for the Trezor suite.

**Expected behavior**
Appropriate black text on white background that is easy to read.

**Comment by sime** [comment]
@jingxi285 Thanks for the issue, please edit the description and remove the templated content as it makes it hard to read what is the _actual_ issue.

Also screenshots help a lot!

**Comment by bosomt** [comment]
I think we can close this one issue @sime

**Comment by jingxi285** [comment]
Wish I'd not bothered to report the issue. I'm wasting my time here.
