### ISSUE TITLE
Support remote WebAuthn 

### ISSUE THREAD

**Issue by fionera** [trezor/trezor-suite#7192]
As a User I want to use my Trezor as a FIDO Token on devices where I cannot connect the Trezor to. The Trezor Suite should support reading the issued QR Code and solve the challenge.

**Comment by sime** [comment]
Hi @fionera thanks for the issue.

I'm closing this for now, but you are welcome to continue the discussion here.

I have never heard of Remote WebAuthn before. On a brief search, it seems to online exist in the academic world: https://www.scitepress.org/Papers/2021/101927/101927.pdf

Do you have any examples of this in the wild?

(Looks interesting nonetheless)

**Comment by fionera** [comment]
@sime I wasnt really sure what the Name of it was since the Passkey/WebAuthn stuff is very confusing. I mean the feature that allows you to use a QR Code to use a remote device as 2FA Source. I tried to find out how to actually implement it but couldn't find any good resource https://stackoverflow.com/questions/73224907/what-information-does-fido2-url-contain-and-how-can-we-decode-it-in-swift
