### ISSUE TITLE
Edit example in "Import address from CSV"

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#7194]
Update example so that it will include label column. 

Label column would be visible only with labelling turned on.

```
address,amount,currency,label
tb1qqmg2mtmugpld08wczesag8mn2s6ae7vg6qw096,0.31337,TEST,Important transaction
tb1qhvslkhdvxwzwrhu3qxsc5jlx868vez0vxrrzl0,0.1,USD,Sending coins to mother
```

(related issue: https://github.com/trezor/trezor-suite/issues/5770)

**Comment by STew790** [comment]
**QA OK**
`label` column in example is present only when labeling is enabled.

**Info:**
 - Suite version: desktop 23.2.0 (45c816db15aea3444dea02e0edc777748ef8052c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision ff35c77bad82c7acac1df6245940ebe0d6454642)
 - Transport: BridgeTransport 2.0.32
