### ISSUE TITLE
FIAT currency improvements

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7197]
1. Add FIAT shortcut (e.g. Euro - EUR) in front of currency when user picks the FIAT currency. It is visible when I pick it but not in the toaster selection. See printscreens
2. Implement latest version of currency settings from connect

EDIT Jul 7, 2024: Align the labels with the desktop, but do not add BTC/ETH for now as it is not yet on desktop and do not rename the tab.

When user picks:
<img width="350" alt="image" src="https://github.com/user-attachments/assets/f46bf5fc-a226-43f1-b9ce-d932049498b0">

When user go through the selection:
<img width="350" alt="image" src="https://github.com/user-attachments/assets/e4e95ca3-e5f4-4344-9799-fc83535d7277">

**Comment by Hannsek** [comment]
Please align the wording/behaviour with desktop Suite.

From what I see here:

- Add other assets into the currency menu to align it with desktop Suite (gold, silver, xdr, etc.) [_not sure if it isn't already there..._]
- Add `BTC` and `ETH` to currency menu (edit by @sime: out of scope until covered by desktop too)
- rename _currency_ tab to _Unit_ 

See desktop issue on this: https://github.com/trezor/trezor-suite/issues/5939

**Comment by STew790** [comment]
**QA OK**
Currency updated correctly

**Info:**
24.9.1 bf893a5
