### ISSUE TITLE
TREZOR+METAMASK issue Transaction Failure lframe Timeout. 

### ISSUE THREAD

**Issue by gochaita** [trezor/trezor-suite#7204]
I have a trezor connected to a metamask account. never had an issue with it. Now all of a sudden I started getting an error after clicking SEND on metamask when the Trezor page usually opens a popup tab on my browser so I can confirm the transaction on the device.

I get "transaction failed" "lframe timeout" on metmask. this is the popup that opens when i click SEND on trezor. but the page never fully fully opens and then the transaction fails on metamask it just says "loading" on the popup. this is the popup URL:  

https://connect.trezor.io/8/popup.html

I tried on an old computer and was able to to transact fine with no issues for 1 transaction but then the same thing started happening. Is this because of a recent chrome update or something?

what can I do? I think it might be related to the trezor bridge, not sure.

**Comment by Hannsek** [comment]
Try that with incognito mode in Chrome or with Firefox browser.

**Comment by mroz22** [comment]
Most likely some clashing browser extension. Could you, please, send a list of other active browser extensions?

**Comment by gochaita** [comment]
> Most likely some clashing browser extension. Could you, please, send a list of other active browser extensions?

the only extensions i have are 1password, adblock plus, authenticator, metamask, nordVPN

i haven't installed any new extensions in a long time.

**Comment by gochaita** [comment]
i just disabled adblocker. after a couple tries the transactiosn started going through. 

the weird thing is that even the trezor bridge website was blank before I disabled adblocker. the regular trezor shop website was all messed up and the trezor support website was too. now after disabling the adblocker all the website are working fine.

**Comment by Hannsek** [comment]
Thank you for the provided information. I will now close this issue as we are tracking it here: https://github.com/trezor/trezor-suite/issues/7207. Feel free to continue in the thread.
