### ISSUE TITLE
Investigate why Connect failing

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#7207]
What to investigate:

- messages between various extensions
- 
- 

E.g. https://github.com/trezor/trezor-suite/issues/7204

**Comment by sime** [comment]
I don't _think_ it is purely an extension issue, Trezor Connect on web is known to fail.

We have a number of discussions ongoing about this:
* #4878
* https://github.com/trezor/connect/issues/784
* Somewhat related: #5644
