### ISSUE TITLE
Remove FIAT balance for Testnet coins

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7210]
Remove FIAT rate / balance from testnet coin - they don't have any value.

**Comment by PeKne** [comment]
@mnuky Do we have a UI design for cases when are fiat rates hidden?
For example, AssetItem could look like this:
![Screenshot 2023-02-08 at 11 27 46](https://user-images.githubusercontent.com/26143964/217504017-fb3b1862-c0ff-46ca-81d5-751dd5c55253.png)
Or like this:
![Screenshot 2023-02-08 at 11 28 13](https://user-images.githubusercontent.com/26143964/217504120-532e983b-4d65-42f1-9a63-6d812fd210d4.png)

To finish this issue, I need a design version of every component which should reflect the hiding of fiat values. For example, transaction list, account detail, should be graph visible on account detail, etc.

**Comment by bosomt** [comment]
**QA OK**

b52b001 - [develop] 

but maybe we can consider to enable graph based on coins and not on fiat for test accounts ?
accounts looks strange without graph :)
