### ISSUE TITLE
Dependencies(transport): protobufjs, long

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#7213]
`protobufjs` has a breaking change in version 7. Problem described here #7190

**Notes:**
- https://github.com/protobufjs/protobuf.js/releases/tag/protobufjs-v7.0.0
- `protobufjs-cli` has to be added
- test it on both macOS and Linux

**Comment by mroz22** [comment]
Probably a good moment to migrate to protobuf syntax version 3 also. this needs to be synced with trezor-firmware
