### ISSUE TITLE
React render error after CJ session start

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#7221]
**Describe the bug**
React throw render error

**How to reproduce**

1. Go to coinjoin account
1. open console
1. start coinjoin
![Screenshot from 2022-12-14 12-53-48](https://user-images.githubusercontent.com/3435913/207620957-2851793b-0a90-42e1-875d-c8483d55cdda.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.1.0 (c44e5eaa2820b196794b34e9d50785ef5e37f909)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision ff35c77bad82c7acac1df6245940ebe0d6454642)
 - Transport: bridge 2.0.32
