### ISSUE TITLE
Remove coins from importing

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7227]
Remove from app possibility to import these coins as they are agreed to be obsolete and removed from future devices anyhow:
Dash
Bitcoin Gold
Digibyte
Namecoin
Vertcoin

**Comment by bosomt** [comment]
**QA OK**

**Comment by ktechmidas** [comment]
Hi,

Who agreed DASH is obsolete? We released v18,19 and are about to release v20... you can see DASH's current work here: 

https://github.com/dashpay/dash
https://github.com/dashpay/dash/tree/develop
https://github.com/dashpay/platform

Our price may be low, but that reflects most cryptocurrencies in this market, surely the measure of whether a currency is "dead" is whether there's a team behind it doing work?

**Comment by kxcd** [comment]
Please support Dash, the coin is active and far from obsolete.

**Comment by pshenmic** [comment]
Dash +1

It must be accidentally included in this list

**Comment by greatwolf** [comment]
I can second this, how did you come to the conclusion Dash is obsolete?

**Comment by sapph1re** [comment]
Dash is by no means obsolete, please add it back.
