### ISSUE TITLE
Set hierarchy for CoinJoin banners

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7236]
It's ambiguous to show some banners at the same time.. Like `out-of-sync` and `disabled tor`
<img width="616" alt="image" src="https://user-images.githubusercontent.com/31506317/207841289-095fee6f-870d-4192-97c0-586e392946e9.png">

_Originally posted by @bosomt in https://github.com/trezor/trezor-suite/issues/6418#issuecomment-1352888210_

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue.
