### ISSUE TITLE
Switching timeline changes fiat and Bitcoin value

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#7237]
**Describe the bug**
When I choose a different time range, the portfolio value _and_ Bitcoin amount changes.

**How to reproduce**
1. Load xpub
2. Switch between timeframes

**Expected behavior**
1. BTC value to remain the same: 0.0050213 BTC
2. Fiat value to remain the same.

**Screenshots**
|ALL|1Y|1M|
|-|-|-|
|![Screenshot_20221216-111738127](https://user-images.githubusercontent.com/216917/208079554-ef2c0f53-dba4-402b-8eef-fdfb2a445e85.jpg)|![Screenshot_20221216-111728830](https://user-images.githubusercontent.com/216917/208079560-7ca6add4-ffd2-4d27-b195-706b47d3e53b.jpg)|![Screenshot_20221216-111711944](https://user-images.githubusercontent.com/216917/208079561-990f751a-904d-462e-b57b-b124709ee095.jpg)|

|1W|1D|1H|
|-|-|-|
|![Screenshot_20221216-111705211](https://user-images.githubusercontent.com/216917/208079563-23674d89-84c0-4595-aacb-ed825c80d3cd.jpg)|![Screenshot_20221216-111658157](https://user-images.githubusercontent.com/216917/208079566-1c918f7c-08a3-4afc-aea5-ad87bb07de86.jpg)|![Screenshot_20221216-111646994](https://user-images.githubusercontent.com/216917/208079570-60921fc7-249b-43ca-9e39-e008ab77360f.jpg)|

https://user-images.githubusercontent.com/216917/208080338-7edbc0a3-fe4f-4a65-a674-4d2b10dc9d9f.mp4

**Additional context**
Current balance of team xpub is [0.0050213 BTC](https://btc1.trezor.io/xpub/zpub6rjNNddoAVvuYaD6WPdxiqFEToQHgrERjWMg7kM9gGGk6rhPMWNEmL5X745FGqBq8Wp136LfA3A7UjRGEYdJrf8dUfshzNrb5rvaryNfVJf)

**Comment by mnuky** [comment]
Waiting for new version of blockbook

**Comment by Nodonisko** [comment]
Could be tested @bosomt

**Comment by bosomt** [comment]
**QA OK**

Tested on Android Samsung 
**4849bd6 - [develop] **

**Comment by mnuky** [comment]
@Nodonisko the issue with fiat rates fixed but issue poped up - only  the time is visible by default above the graph, the date appears after you click on the graph line. Take a look on printscreens:
![Image](https://user-images.githubusercontent.com/84183817/224268095-31f4a3da-6d20-46aa-a402-7b58a1d62955.PNG)
![Image](https://user-images.githubusercontent.com/84183817/224268094-74153c24-81e6-4b2b-ab8a-b2046b932b95.PNG)

**Comment by Nodonisko** [comment]
@mnuky that's on purpose inspired by Revolut. Date formating is now changing depends on date range and if the selected point is today you see only time. By default is always selected last point so you will see only time.

**Comment by mnuky** [comment]
> @mnuky that's on purpose inspired by Revolut. Date formating is now changing depends on date range and if the selected point is today you see only time. By default is always selected last point so you will see only time.

But Revolut works a little bit differently with displaying the content above the graph. They display the timeframe user is in: e.g. Today, Last week, Last month and then when user taps on the graph, display specific date and time. 
1. Either we do it as it was before: Display last timestamp - date + time
2. Revolut style: display timeframe user is in: Today / Last week / Last month... and when user taps on the graph we add the date and time

Current version is confusing

**Comment by Nodonisko** [comment]
@mnuky PR #7818 will change it to:
1. if range is less than week it will show date + time
2. if it's more it will show only date
