### ISSUE TITLE
Cannot acquire device in Firefox

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#724]
![image](https://user-images.githubusercontent.com/3112191/67647227-c6785780-f931-11e9-9541-b7b1a78d3722.png)

**Comment by vladimirvolek** [comment]
Error notification is not implemented.

![image](https://user-images.githubusercontent.com/3112191/67647285-03dce500-f932-11e9-9827-bd5cf577928e.png)

**Comment by keip** [comment]
> Error notification is not implemented.
> 
> ![image](https://user-images.githubusercontent.com/3112191/67647285-03dce500-f932-11e9-9827-bd5cf577928e.png)

@vladimirvolek  Could you please write some steps to reproduce this bug?

For me it requires the device in both Firefox and chrome.
