### ISSUE TITLE
Balance and rate update forced by user

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7240]
As a user I would like to have option to force the update of the content in the app by swiping up in order to see the latest values. 

Figma prototype incl. animation: https://www.figma.com/proto/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=14455-107614&t=Ld33f5ssNi22tObp-1&scaling=scale-down&page-id=5212%3A30121&starting-point-node-id=14455%3A107614&show-proto-sidebar=1&mode=design

Acceptance criteria:
When user swipe up, animation is displayed
When it is triggered, balances and values are updated

**Comment by Nodonisko** [comment]
Done in #10316
