### ISSUE TITLE
T1 "path not supported" for lightstreams M/44'/60'/0' in v1.11 and get "unknown bootloader" in all older firmwares

### ISSUE THREAD

**Issue by adaptivedev** [trezor/trezor-suite#7243]
MEW shows "path not supported" when trying to send tokens like USDT.

It began after updating firmware on an old T1 (2018 or so).

I tried all allowed older firmware like 1.8, 1.9, 1.10, but then I get

"Unknown bootloader. Contact support"

The path that has the tokens is called "lightstreams" on MEW, and is 

M/44'/60'/0'

Thanks for any help!

**Comment by hynek-jina** [comment]
@adaptivedev Have you contacted support?

**Comment by sime** [comment]
@adaptivedev If you are getting path errors, and you are sure they are right, disable safety checks.

**Comment by adaptivedev** [comment]
Thanks. What happens is the path is entered wrongly by mistake?

**Comment by sime** [comment]
@adaptivedev If you perform actions with safety checks off, you are doing them at your own risk.
