### ISSUE TITLE
Warn about sending funds to a contract address

### ISSUE THREAD

**Issue by mkolar242** [trezor/trezor-suite#7244]
**Design:** 
https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?node-id=4390%3A39787&t=VEeGefz3JzzqMRnu-0

**Spec:** 
As a user I want to be warned when I paste a token contract address to the recipient address field when attempting to send ether or other tokens out of my Ethereum account.

**Acceptance criteria**

- When I paste a token contract address to the “Recipient address” field, warning box will be displayed right under the “Recipients address” field
    - Each pasted string has to be verified against Blockbook which knows all existing contracts, each contract has the following information
![api-blockbook](https://user-images.githubusercontent.com/42438053/208373917-477f8662-2e82-471d-abd9-c98818422440.png)
- Warning box contains the following information:
    - Red triangle warning icon on the left
    - “You are about to send to a contract address which could result in a loss of funds.” text next to the warning icon
    - The warning text is followed by “Lear more” link, which redirect to the knowledge base article
        - Article URL: **https://trezor.io/learn/a/sending-funds-to-a-contract-address**
    - Button “I understand” is located on the right side
        - When I click the button to acknowledge the warning, the whole warning box closes

**Comment by sime** [comment]
Inspiration how MetaMask implemented this (the UI was later changed):
* https://github.com/MetaMask/metamask-extension/pull/6051
* https://github.com/MetaMask/contract-metadata

**Comment by tomasklim** [comment]
Rabby UI:
![Screenshot 2023-07-17 at 13 34 08](https://github.com/trezor/trezor-suite/assets/33235762/598dc288-839e-407e-bd3e-fd093e4bd3fe)
![Screenshot 2023-07-17 at 13 34 16](https://github.com/trezor/trezor-suite/assets/33235762/729d716c-d41b-42c6-a1f5-44091f5e57f4)

we can use `getAccountInfo` blockbook method for this
![Screenshot 2023-07-18 at 10 05 27](https://github.com/trezor/trezor-suite/assets/33235762/660449cb-d7c2-4cc2-8357-5f0dbc7a1794)

Would be nice to connect also with `Never send to this address before` info (Prevents phishing)

**Comment by AdamSchinzel** [comment]
Design link not working

**Comment by enjojoy** [comment]
> Would be nice to connect also with `Never send to this address before` info (Prevents phishing)

@tomasklim  I was thinking that we could create a component (or modify the existing one), so we could stack warnings below the address input. For example when we have multiple warnings, with checksum and contract address etc. 

But then I think it would mean re-making the errors logic in Address component. Also now it's almost impossible to dismiss an address error

**Comment by Hannsek** [comment]
It would be great to stack it. We just need to be sure it is not overwhelming and that it is still clear for the end user.

**Comment by enjojoy** [comment]
> It would be great to stack it. We just need to be sure it is not overwhelming and that it is still clear for the end user.

Created an issue for that to discuss it with PMs and @jvaclavik later, I think it can be a bigger task
https://github.com/trezor/trezor-suite/issues/14253

**Comment by enjojoy** [comment]
@Hermez-cz  FYI this might be good to discuss with designer 

> It would be great to stack it. We just need to be sure it is not overwhelming and that it is still clear for the end user.

**Comment by enjojoy** [comment]
UPD: We decided to enable it for Ethereum Mainnet only

**Comment by bosomt** [comment]
**QA OK**

✅ Eth send waring present
✅ KB link works as expected
✅ i understand button works as expected
✅ warning is present again even i presssed i understand before 
✅ POL send warning not present 

<img width="722" alt="Image" src="https://github.com/user-attachments/assets/b57214a3-ae91-46de-9b5a-e92255cf0302" />

**Info:**
 - Suite version: web 25.1.0 (f81e70edde076bf7a7890b12a303859e6e2ecc06)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport
