### ISSUE TITLE
Generate random change target for each TX to increase privacy

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#7245]
# Summary
Investigate if changes in Bitcoin Core can be applied to Trezor Suite coin selection

# User Story
As a Bitcoin sender
I want to obfuscate my change output
So that I can maintain my privacy

# Acceptance Criteria
Given I am spending Bitcoin
When I inspect coin control
Then I should see a random selection of UTXOs

# Background

Inspired by Bitcoin Core v24 release notes:

> To help prevent fingerprinting transactions created by the Bitcoin Core wallet, change output amounts are now randomized. ([#24494](https://github.com/bitcoin/bitcoin/pull/24494))

And What's New v24 article: [Change Output Randomization To Avoid Fingerprinting](https://bitcoinmagazine.com/technical/bitcoin-core-24-0-released-what-is-new#change-output-randomization-to-avoid-fingerprinting)
> Given that there is no way for a blockchain observer to tell when each scenario happens at a given time, the user should be able to enjoy greater privacy assurances.

**Comment by peter-sanderson** [comment]
Bitcoin Core wallet implements 4 algorithms to select coins:

1. `SelectCoinsBnB` Branch and Bound (called [here](https://github.com/bitcoin/bitcoin/blob/da10e0bab4a3e98868dd663af02c43b1dc8b7f4a/src/wallet/spend.cpp#L708))
2. `KnapsackSolver` (called [here](https://github.com/bitcoin/bitcoin/blob/da10e0bab4a3e98868dd663af02c43b1dc8b7f4a/src/wallet/spend.cpp#L721))
3. `CoinGrinder` (called [here](https://github.com/bitcoin/bitcoin/blob/da10e0bab4a3e98868dd663af02c43b1dc8b7f4a/src/wallet/spend.cpp#L726))
4. `SelectCoinsSRD` - Single Random Draw (called [here](https://github.com/bitcoin/bitcoin/blob/da10e0bab4a3e98868dd663af02c43b1dc8b7f4a/src/wallet/spend.cpp#L734C25-L734C39)) 
    - SRD is similar to our Greedy (accumulative) with the difference that they randomly shuffle inputs and we are sorting by FIFO  

However we only implement:
1. [`bnb`](https://github.com/trezor/trezor-suite/blob/develop/packages/utxo-lib/src/coinselect/inputs/bnb.ts) (Branch and Bound)
2. and [`accumulative`](https://github.com/trezor/trezor-suite/blob/develop/packages/utxo-lib/src/coinselect/inputs/accumulative.ts) Naive alg. that Bitcoin Core does not have (uses SRD for this purpose)

---------------------

The mentioned [Pull Request](https://github.com/bitcoin/bitcoin/pull/24494) enhances the logic in the `Knapsack` algorithm which we don't implement.

**Comment by peter-sanderson** [comment]
We also have this covered by https://www.notion.so/satoshilabs/Send-form-UTXO-selection-algorithm-43f48002bfc747098220bb89007e7cc6
