### ISSUE TITLE
Handle anonymity calculation exceptions

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#7247]
Handle anonymity calculation exceptions and display that information similarly to `out-of-sync` banner.
This error should never happen, but if it does (middleware calculation fail) then probably it will not be fixed by simply reloading.

Anonymity calculation is essential part of Coinjoin account and user should not be able to participate in coinjoin session without it.

**Comment by dahaca** [comment]
FOR QA: The errors being handled are very rare and unlikely to happen so i'm not sure any testing is required at thin point :)

**Comment by STew790** [comment]
OK, thanks @dahaca moving forward then.
