### ISSUE TITLE
Empty menu with unacquired device

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#725]
![image](https://user-images.githubusercontent.com/3112191/67647345-443c6300-f932-11e9-9a4b-32af19f393ed.png)
![image](https://user-images.githubusercontent.com/3112191/67647351-4bfc0780-f932-11e9-9b2a-e3aa25c489f5.png)

**Comment by slowbackspace** [comment]
I wouldn't waste a time with this one, UI/UX will be probably completely different with new design.

**Comment by vladimirvolek** [comment]
It will be handled in the new design.
