### ISSUE TITLE
Real checkboxes during Create Backup onboarding

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#7256]
## Design
![Untitled](https://user-images.githubusercontent.com/216917/209180798-e6ff3a7b-d2a0-4891-b43b-de272cdd7424.png)

## User Story
As a user
I want to confirm I understand what a backup is
So that I know how to recover my funds

## Background
First time Trezor users are conflicted how to progress when prompted to `Begin backup` which is disabled by default.
The feedback is the boxes are already checked.

[Related research](https://www.notion.so/satoshilabs/Trezor-R-Onboarding-4ad0f6908c1347e4b4e7a01bc52ea150#905ab327fa8143afac920b0055f8e323)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.2.0 (aebe81957c19c1b289f016cca5cb6b2c7808e1bf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
