### ISSUE TITLE
Typo in lint-staged command

### ISSUE THREAD

**Issue by sebastianhomeier** [trezor/trezor-suite#7259]
**Describe the bug**
There is a typo in a lint-staged command for stylelint: https://github.com/trezor/trezor-suite/blob/c657469ccc2bc2cfb66a4e230013c8ef93d50e55/package.json#L73

Also, stylelint is currently not listed as a dev dependency.

**Expected behavior**
The command should be `stylelint --fix` and stylelint should be added as a dev dependency. 
If stylelint is not used, its lint-staged command should be removed.

**Comment by AdamSchinzel** [comment]
Fixed by @dahaca in e9643105137e36561daa5136142f324ea1a4af1e
