### ISSUE TITLE
Desired anonymity level and Max mining fee fields in CoinJoin sectiom have no limit of digits that you can enter.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#7260]
**Describe the bug**
`Desired anonymity level` and `Max mining fee` fields have no limit of digits that you can enter.

**Steps to reproduce:**
1. Navigate to CoinJoin section
2. Try to change settings in `Account` and `Custom setup` section by entering really long number
3. Observe behavior of enter field

**Info:**
 - Suite version: desktop 23.1.0 (c657469ccc2bc2cfb66a4e230013c8ef93d50e55)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision 305b7fe84d802db7f0826d07a222a886f73732f0)
 - Transport: bridge 2.0.32

**Screenshots:**
<img width="450" alt="Screenshot 2022-12-27 at 12 20 53" src="https://user-images.githubusercontent.com/31506317/209659404-d9e7cd52-447d-4099-a8ae-d9f6f36940a1.png">
<img width="411" alt="Screenshot 2022-12-27 at 12 20 48" src="https://user-images.githubusercontent.com/31506317/209659409-1bbcc223-5283-4e99-9fcb-7695e8976470.png">

<img width="674" alt="image" src="https://user-images.githubusercontent.com/31506317/209664803-a375fd96-7770-43f4-9c95-d2b7f957fd2e.png">

https://user-images.githubusercontent.com/31506317/209659415-5fa7262c-6656-49f0-a11e-7d852ea58803.mov

**Comment by hynek-jina** [comment]
User shouldn't be able to add anything except numbers: https://github.com/trezor/trezor-suite/issues/7116

**Comment by matejkriz** [comment]
> User shouldn't be able to add anything except numbers: #7116

That is already handled, those Infinity and e+21 values are not from user input but transformed numbers.


I believe, that user should be able to more digits than in max value, but not infinity. The value is validated and changed to max value on blur (or on press Enter). I would suggest to handle just the infinity. 

User can mistype - want to set 100, but type 111. It's better to allow him to type 11100 and then delete those extra 11, than not allowing to type it at all without any explanation/validation message...

**Comment by dahaca** [comment]
I will allow some reasonable max after which the value stops changing, preventing those large weird numbers.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.2.0 (aeb1abfe2b1587e79dde501d1cac6f41f0cd4952)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
