### ISSUE TITLE
Imported send data are calculated for bitcoin but not for sats

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7263]
**Steps to reproduce:**
1. Switch to sats (_click on the amount in the top of your account_ )
2. Import csv with transaction information
3. See that calculated bitcoin value is expressed in BTC not in sats (_using decimals_)

**Info:**
 - Suite version: desktop 22.12.1 (ddaacdb2245d7a909b3d2abfe918cff34d2e1609)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Expected result:**
Calculated the bitcoin value in sats (_integers_)

**Actual result:**
Received amounts in BTC

**Video:**

https://user-images.githubusercontent.com/26002916/209912060-9ca16c6d-5e1a-4f52-8be3-7b4261839fa1.mov

**csv example with random data**
```
"bc1qp66agjq5tmf8cuneq26mj4sg9zmxfzh0cxrmv7,210,EUR,157250"
"bc1qwqdg6squsna38e46795at95yu9atm8azzmyvckulcc7kytlcckxswvvzej,68.90,USD,154838"
```

**Comment by bosomt** [comment]
**QA OK**

- imported `tb1qp4v7ajc36ehssrqxq2thhslp4apxegsp030f9kt,0.31337,TEST` via import dialogue after i switched to sats
- it was imported: `31337000 sat`

**Info:**
 - Suite version: desktop 24.2.0 (81d011d6dc01c0135cb38b989270cec8b9f74a57)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
