### ISSUE TITLE
Display line and graph values by tap on the graph

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7264]
As a user I would like to tap on the graph and immediately see the line and value on the graph. 

Currently user has to click directly on the graph line and wait which is hard to explore. I would like user to just put his finger on the graph and see the line and the value in that moment. 

Acceptance criteria:

- When user tap on the graph, he sees the line where he points and the value in the header of the graph
- When user moves with finger, the line moves according the graph and values are changing

![Image](https://user-images.githubusercontent.com/84183817/209929695-e8149ef6-cb00-4691-83d8-00cbc3197971.png)

**Comment by bosomt** [comment]
**QA OK**

tested on f81df35 - [develop] - fix(suite-native): graph selection line always visible (#7604)
