### ISSUE TITLE
Menu shown / not shown rules

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7268]
As a user I would like to see the menu on all important places thus I can access important stuff directly. 
Menu will be hidden in those cases:

Menu will be displayed:
Dashboard
Asset detail
First step of Receiving - while choosing the asset I would like to receive to
Settings
Asset detail page

Menu will be hidden:
- Receive flow (if you have the acc selected and are only focused on the flow)
- Import asset flow
- Transaction Detail page
- Asset Detail Settings

**Comment by bosomt** [comment]
**QA OK**

tested version 64ff83b
