### ISSUE TITLE
PIN dialog should show Label of the device

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#7269]
Currently, the PIN dialog does not show the label of the device and I have no idea which PIN I should use.

The background of the dialog is blurred out, so I am not able to figure out the device label from there either.

Last but not least, I am not able to figure out the device label from the device either, since the device now shows a PIN dialog too.

![Screenshot 2022-12-30 at 17 04 15](https://user-images.githubusercontent.com/42201/210089852-af8fcfaa-c69a-4472-8482-5fc2695ef26b.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.2.0 (ca097db0a2585fd49fa5f17e0d88daa9e4defd36)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model 1 1.12.0 Bitcoin-only (revision a97dfd3a4f4a709a08e125946f6e1c96a0cc7ec0)
 - Transport: bridge 2.0.32
