### ISSUE TITLE
Feature flags

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7273]
We will need some way how to handle Feature Flags. For example one of the feature flags could be if Trezor devices support is enabled.

We can probably utilize package `@suite-native/config` or create separated package if there will more abstraction around this.

We should think about some smarter solution than just plain `isDeviceConnectionSupported = true` etc.

Inspiration:
1. https://www.flagship.io/feature-flags-react-app/
2. https://tsh.io/blog/feature-flags-best-practices/

In our case we will also need to connect these feature flags with remote `@trezor/message-system` so flags could be enabled/disabled for specific versions remotely.

Related to #7274

**Comment by tomasklim** [comment]
Related to https://github.com/trezor/trezor-suite/pull/7189
