### ISSUE TITLE
Use @trezor/message-system for mobile-app

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7274]
We will need to use message system also for mobile app. We will need it for #7273 and also we will need it for enforcing app updates if needed.
```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/8694
```

**Comment by mnuky** [comment]
Message system is used at Desktop Suite to communicate:
1. Deprecated version of Firmware when user connects Trezor
2. Deprecated version of Suite when user connects Trezor 
3. When something really bad happen and we need to notify ASAP

- Messaging system is working in pipelines It automatically checks the regularly if there are new messages
- When user has Desktop Suite open, we renew the content in 6 hours
- It takes up to 45 minutes to push the message to Suite 

Usage for Mobile app:
1. Deprecated versions of app
2. When something really bad happen and we need to notify ASAP
Other messages will come later with connected Trezor

Design is not ready yet

**Comment by matejkriz** [comment]
> * Messaging system is working in pipelines It automatically checks the regularly if there are new messages
> * When user has Desktop Suite open, we renew the content in 6 hours
> * It takes up to 45 minutes to push the message to Suite
> 

- Message system config is released via Github actions. We have two "tracks"  – `dev` and `prod`. Suite app signed by production key uses `prod` config.
- To release a new config, it has to be merged to develop and then it took about 7 minutes for the action to publish it (no guarantees for the time, it could take longer) https://github.com/trezor/trezor-suite/actions/workflows/release-suite-config.yml 
- Suite checks if there is a new config on server on open and then **every 1 minute**.


This is how to config looks like: https://github.com/trezor/trezor-suite/blob/develop/packages/message-system/src/config/config.v1.json

And here is the whole scheme: https://github.com/trezor/trezor-suite/blob/develop/packages/message-system/src/schema/config.schema.v1.json

**Comment by matejkriz** [comment]
distinguish android/ios

**Comment by matejkriz** [comment]
Not yet testable by QA - there is no new UI in mobile app so far. @mnuky is there a follow-up issue or should this be reopened?

**Comment by mnuky** [comment]
@matejkriz I would keep this as main and I will create child issue for UI, ok?
