### ISSUE TITLE
Share transaction

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7284]
As a user I'd like to be able to share my transaction in order to notify whomever about the transaction. 

Acceptance criteria
User can share the transaction from Transaction detail
When user clicks on share it opens Share settings

**Comment by Nodonisko** [comment]
What should be content of "share"? Some message or just plain txid? Maybe include link to BlockExplorer will be really nice too.

**Comment by mnuky** [comment]
@Nodonisko Share feature will just copy the TX ID and enable to share via standard share feature. BlockExplorer is already in development in issue: https://github.com/trezor/trezor-suite/issues/7070
