### ISSUE TITLE
Access to multiple asset under coin folder on dashboard

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7287]
As a User I would like to choose directly on dashboard from assets under the coin folder which I would like to access in order to get there faster. 

Design:
https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=8222%3A79503&t=vPIepkd4iB7ln7cq-1
![Image](https://user-images.githubusercontent.com/84183817/210374787-33a132bf-c469-4943-8236-880c86092a00.png)

Acceptance criteria:
- When there are more assets under the coin folder and user clicks on it, toaster with selection of the related assets appears
- toaster icnlude information about asset: Icon of the coin, Name of the asset, Current FIAT value, Current balance, Account type (if the asset has account type)
- If user clicks on the asset, he is redirected to selected asset detail

**Comment by bosomt** [comment]
**QA OK**
