### ISSUE TITLE
Enhance My assets page and account settings with Account type

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7289]
As a user I would like to see type of coin account on My asset page in order to have better clarity and overview of my imported assets. 

Notes:
Not all coins have Account type, list of account types is here: https://miro.com/app/board/uXjVPKEIyn4=/?moveToWidget=3458764536804595083&cot=14

Design: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=7833%3A53763&t=vPIepkd4iB7ln7cq-1

**Acceptance criteria:**
- All assets with account type have the account type displayed at My assets page
- all assets with account type have the account type displayed at Asset settings page
- asset type is displayed on receive flow screen

**Comment by PeKne** [comment]
I was about to implement this issue. But then I found, that in the current state of the app, all accounts have property`accountType === 'imported'`.

This is happening during account import flow, particularly on lines: https://github.com/trezor/trezor-suite/blob/618388a3434997bc748c86f2db4301c26a0a43db/suite-native/module-accounts-import/src/accountsThunks.ts#L53-L63.

For this reason, I believe there is currently no account with a type other than `imported`. If there is no account with any special type, I guess that implementing this UI is at this moment useless. 

@Nodonisko

**Comment by Nodonisko** [comment]
Yea, let's skip this one, I think we can't determine account type from just XPUB anyway. @PeKne

**Comment by mnuky** [comment]
> 

@Nodonisko we can determine from XPUB, I've checked with Sime

**Comment by sime** [comment]
@mroz22 might be able to assist.

TrezorConnect.getAccountInfo() return derivation path. We extract the derivation path of individual addresses, is this done locally or on blockbook?

**Comment by PeKne** [comment]
Account type can be determined from derivation path prefix: 
"m/49" is used for P2WPKH nested in P2SH (Legacy SegWit).
"m/84" is used for P2WSH nested in P2SH (SegWit).
"m/86" is used for Taproot addresses.
"m/44" is used for Legacy addresses.

**Comment by Hannsek** [comment]
This is the way we do it in fw. ↑

**Comment by bosomt** [comment]
**QA OK**

 tested on dev version 233 on iPhone 11
