### ISSUE TITLE
Upgrade outdated packages

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#729]
- [x] react-native 0.61 https://github.com/trezor/trezor-suite/issues/769
  - react (should match the required version for react-native)
- [x] electron 7 https://github.com/trezor/trezor-suite/issues/766
- [x] nextjs https://github.com/trezor/trezor-suite/issues/880
- [ ] typescript 3.7 https://github.com/trezor/trezor-suite/issues/768
- [x] all the other 3rd party packages (CI check for outdated packages is green)

**Comment by ZdenekSL** [comment]
Need to specify what we will update.

**Comment by mroz22** [comment]
lets close, we are still waiting for typescript but it has separate issue
