### ISSUE TITLE
Incorrect Android Status Bar color

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7292]
If you have phone in dark mode and dark theme in app, text in status bar is also dark so it's unreadable. If you have light theme in app status bar stays dark.

Same if you have phone light mode, status bar stays light all the time.

![Image](https://user-images.githubusercontent.com/5837757/210385859-3096b144-6b7f-49d4-aa8b-957b57051bad.png)
![Image](https://user-images.githubusercontent.com/5837757/210385860-b5012fc6-aeb9-4709-b77e-b94d5e72de07.png)

**Comment by bosomt** [comment]
**QA OK**

tested on Android 12 
6334b30 - [develop] - fix(mobile): status bar color by theme (#7293)
