### ISSUE TITLE
DCA - Swan Bitcoin - re-authorization flow

### ISSUE THREAD

**Issue by IvaFingerova** [trezor/trezor-suite#7296]
Problem:
tokens created while setting up DCA with Swan unfortunately expired and we need to let users to re-authorise their Trezor

Solution:
we'll add a "banner" to the DCA page to users that need to re-authorize their Trezor device

**Design:** [Figma]
https://github.com/trezor/trezor-suite/pull/7189 ??? Couldn't find it in figma...but it is obviously in the components...
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/8152411/210394286-06966d29-e254-442f-a1bc-41066fd2e08f.png">

**Spec:** [Notion]
https://www.notion.so/satoshilabs/Trade-February-update-67b919577a034c9f9a50e8dd9a59e05c

**Comment by tomasklim** [comment]
No more relavant
