### ISSUE TITLE
Automate Suite freeze process

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#7299]
https://www.notion.so/satoshilabs/Prepare-Update-release-branch-5c7851a9acd04cd0b08212fc180a404d#4d9120ed3a774225ae1f1b10b069d3db

Preparation of release branches, bumping Suite versions, those can be automated or semi-automated in CI.

**Comment by matejkriz** [comment]
mostly done in https://github.com/trezor/trezor-suite/pull/8164, but missing permission to push to protected release branches... https://github.com/trezor/trezor-suite/actions/runs/4864237863/jobs/8673003705

**Comment by komret** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/8446

**Comment by komret** [comment]
Moving to _approved_, nothing to test by QA.
