### ISSUE TITLE
"Maximum N decimals allowed" error message displayed inappropriately

### ISSUE THREAD

**Issue by MatthewDavid1984** [trezor/trezor-suite#7310]
**Describe the bug**
The "Maximum N decimals allowed" error message displays when attempting to enter an invalid amount for sending which is invalid for a different reason. For example, it appears when entering a negative number, a number with no leading zero, or a string containing "e" which is otherwise a number. Tested BTC, LTC, and ETH; BTC and LTC ask for 8 decimals and ETH for 18. 

**Steps to reproduce:**
1. Open Suite
2. Select Accounts
3. Click Send
4. Enter amount without a leading zero, a negative amount, or an amount containing the letter "e" that is otherwise a number.

**Info:**
 - Suite version: desktop 23.1.1 (015c74714a16188f57fdaa5d039e2021724e127c)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Win32
 - Screen: 1366x768
 - Device: model 1 1.11.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.32

**Expected result:**
Ideally the error message should accurately describe the problem with the invalid amount, e.g. the existing "Enter a number (e.g. 1.5)" in the case of an amount including the letter "e"; "Amount cannot be negative" or even the existing "Amount is too low" message in the case of a negative number; and something like "Amount should include a leading zero" when appropriate.

**Actual result:**
The "Maximum N decimals allowed" error message displays when attempting to enter an invalid amount for sending which is invalid for a different reason. For example, it appears when entering a negative number, a number with no leading zero, or a string containing "e" which is otherwise a number.

**Screenshots:**
![8 decimals with no leading zero](https://user-images.githubusercontent.com/121948710/210775713-56d1ada6-5bed-45cf-adcd-453ea2ec8493.jpg)
![8 decimals with negative amount](https://user-images.githubusercontent.com/121948710/210775829-705ab470-8423-4b27-8f01-d8265f0a6693.jpg)
![8 decimals with e](https://user-images.githubusercontent.com/121948710/210776068-9389e8e9-1a57-4e79-b870-67d8e970c11d.jpg)

**Note(s):**

**Comment by sime** [comment]
For the first screenshot, we solve automatically and not throw an error: https://github.com/trezor/trezor-suite/issues/5272

Hint about amount too low is nice, though quite edge casey.

**Comment by sime** [comment]
Thanks for the input, will track it here: https://github.com/trezor/trezor-suite/issues/5928
