### ISSUE TITLE
DeviceImage component high resolution images

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#7311]
@dahaca mentioned that `hiRes` attribute is unused and that the logic in this component could be unified with logic of `Image` [component](https://github.com/trezor/trezor-suite/blob/757dc81ce3a1c7ca5b84106ebcbfdd7b21e91e7c/packages/components/src/components/Image/Image.tsx#L26) 

https://github.com/trezor/trezor-suite/pull/7085#discussion_r1060149298

**Comment by tomasklim** [comment]
@trezor/qa : check that device images/videos/icons are not missing in the ui

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 23.6.0 (318a420dad332eff2c709fed29d403fa7dd2d65b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.6.0 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
