### ISSUE TITLE
Prepare FiatCrytoAmountFormatter

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7325]
Prepare `FiatCryptoAmountFormatter` where you can pass amount in crypto and it will print it's fiat value correctly formatted. You will need to add fiat amounts to formatter context config.

Acceptance criteria:

1. Usage `<FiatCryptoAmountFormatter network="btc" value={cryptoValue} />` will print => `$100`
2. It uses `FiatAmountFormatter` under the hood
3. We already have active fiat currency in config so we don't need pass it extra

**Comment by juriczech** [comment]
Testing:
- test that values for crypto and fiat are not broken is suite desktop

**Comment by bosomt** [comment]
1,205.27846674 DOGE
vs 1205.27846674 DOGE

behavior of thousand separator is not present in mobile app, is that expected ?

tested version: 02d9180 - [develop] 

<img width="136" alt="image" src="https://user-images.githubusercontent.com/31506317/215742942-cfee43fe-86a9-4e61-a14c-a919c8192452.png">

<img width="218" alt="image" src="https://user-images.githubusercontent.com/31506317/215742979-d1dd8fe8-ad95-42eb-818f-9b037ef3ce6c.png">

**Comment by Nodonisko** [comment]
This should be tested in feature branch since it's not merged yet. And since we can build mobile app from feature branches yet. I suggest to wait after todays freeze and merge it and then test it. Or at least test desktop app in feature branch. @bosomt @juriczech please agree together on some solution

**Comment by bosomt** [comment]
**QA NOK**

checked desktop version , see first screens
`dev master `vs branch `feat/fiat-crypto-formatter` , same wallet ;)
looks like whole crypt amount is broken

**Screenshots**
<img width="446" alt="image" src="https://user-images.githubusercontent.com/31506317/215750550-04586290-5a6b-468d-a587-ff54bd83438c.png">

<img width="417" alt="image" src="https://user-images.githubusercontent.com/31506317/215750741-99574acb-91a3-4535-898c-aec7b8ae1d38.png">

<img width="416" alt="image" src="https://user-images.githubusercontent.com/31506317/215751134-e4f02e79-6092-40d4-b83a-923a1d183de3.png">

<img width="277" alt="image" src="https://user-images.githubusercontent.com/31506317/215751299-d7102cbd-75e7-48e0-8ef7-7b5df1829295.png">

<img width="402" alt="image" src="https://user-images.githubusercontent.com/31506317/215751357-149beccd-8df1-4102-b0c6-5d6ddc85100f.png">

**Info:**
 - Suite version: web 23.2.0 (99e9b527bcfaf34c3b53a99cfd843a4a18aaadff)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.2.0 (41a3f6601eedebe176632b8ed99ef3a9c4896ce5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32

**Comment by bosomt** [comment]
**QA OK**

tested on Samsung with 79ad12b - [develop] - feat(suite-common): Formatters (#7401) installed
