### ISSUE TITLE
Wrapper for expo-cliboard

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7331]
We should wrap expo-clipboard to some hook like `useClipboard` which will also show some Toast with text `Copied to clipboard` everytime when called. As quick temporary solution we can use https://github.com/magicismight/react-native-root-toast which is very easy to use and later we will migrate to our notification solution (which will rely on redux to adding notifications, that's reason why should we make it hook right now, to avoid changes to "public api" later).

We will have to create new package named `@suite-native/helpers` - I want to avoid having `utils` package, which will collect all kind of garbage in the end and I hope different name will at least little bit prevent people to do that.

**Comment by bosomt** [comment]
latest version 
a6ae363 - [develop] - feat(suite-native): copy clipboard hook (#7462) 
i see two notifications after i copy receive address

![image](https://user-images.githubusercontent.com/31506317/215421173-87d941a6-9775-43c6-bd86-78b5738e206f.png)

**Comment by PeKne** [comment]
@bosomt The problem was fixed in PR https://github.com/trezor/trezor-suite/pull/7487. Please, test it again.

**Comment by bosomt** [comment]
**QA OK**

tested on Samsung Android 02d9180 - [develop] - Feat\/receive flow polishing (#7454)
