### ISSUE TITLE
Storage encryption

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7332]
Current persistent storage is encrypted with fixed key, which is not secure because everyone can find it in code. Details

1. On first startup generate random crypto-safe hash (using crypto lib) and save it to secured system keychain https://docs.expo.dev/versions/latest/sdk/securestore/
2. Use this hash to encrypt storage in `suite-native/storage/src/storage.ts`
3. Handle edge-cases => what if secure storage fails? etc.

**Comment by bosomt** [comment]
**QA OK**

Android version
7abad7d - [develop] - feat(suite-native): persistent storage encryption (#7447)

storage was wiped 
after restart new settings are remembered 
/no idea how to check if storage is actually encrypted on Android file system/
