### ISSUE TITLE
Show/hide debug menu

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7334]
We need some way how to show/hide debug menu. There is way how they are doing it in Desktop suite, so it would be nice to have it in similar way (something like click 7 times on something to enable) developer debug menu or something).

For debug + developement build we should have menu visible always.

**Comment by juriczech** [comment]
Testing: In about us screen, click 7 times on commit hash and then you should see dev utils screen option in settings which will allow you to copy logs & see commit hash

**Comment by bosomt** [comment]
**QA OK**

tested on iphone and latest production version 6
