### ISSUE TITLE
App info section in About app in Settings

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7335]
It will be super useful to have some information available for every user even without going to debug menu which will be hidden anyway for most of user #7334). Information like version of app, short commin hash etc.

Acceptance criteria:
- if user access app settings there is information about version of the app and last commit hash (shorten one) at the bottom of the page

Figma design: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=12938%3A71922&t=9W2PyXu59BEoT0Bc-1

This needs to be agreed with product/design. @mnuky 

Follow up of #7138

**Comment by mnuky** [comment]
There is already task created with page About where user should find information about app, Terms&Conditions, Privacy policy, give feedback or report a bug. I think it should serve the same purpose https://github.com/trezor/trezor-suite/issues/7138

**Comment by juriczech** [comment]
Closing in favor of #7138
