### ISSUE TITLE
Incorrectly empty CoinJoin account

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7338]
**Describe the bug**
Account on which I already participate in many CoinJoin rounds looks empty... 
I have remembered wallet. Problem disappears when I forget the wallet, restart Suite and run again CoinJoin account discovery.

**Info:**
 - Suite version: desktop 23.2.0 (f9ffa4407c135dafc0b330b2f42be419ac181199)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Expected result:**
See my funds

**Actual result:**
Account pretends to be empty

**Screenshots:**
![Snímek obrazovky 2023-01-06 v 14 44 37](https://user-images.githubusercontent.com/26002916/211025674-a254fc51-fbc9-435e-8fc8-df3da2100147.png)

![Snímek obrazovky 2023-01-06 v 15 13 50](https://user-images.githubusercontent.com/26002916/211029335-0acbfa2f-3efd-41d1-95f7-763723ab8db5.png)

**Comment by bosomt** [comment]
**QA OK**

i was not able to reproduce it anymore, 
@STew790  confirmed too



**Info:**
 - Suite version: desktop 23.4.0 (21653072a7c14c04156cfc6992cec5b582b00a99)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision c21cf87c53f79ad8de9d0549bb714cd08f9b46a0)
 - Transport: BridgeTransport 2.0.32
