### ISSUE TITLE
Can't bump fee when sending BTC from Taproot account

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#7339]
**Describe the bug**
I can't bump fee of a transaction sent from Taproot BTC account in Suite. Trezor freezes when creating the tx and Suite shows error. Both can be seen in screenshots section. Trezor device is fine after reconnecting. This issue is in Suite from 22.7.3 version (as shown in the info part of this issue).

**Steps to reproduce:**
1. Go to your Taproot account
2. Sent few sats to yourself from the Taproot account
3. Try to bump the fee of this transaction
4. An error will appear and Trezor will freeze

**Info:**
 - Suite version: desktop 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 regular (revision ff35c77bad82c7acac1df6245940ebe0d6454642)
 - Transport: bridge 2.0.32

**Expected result:**
I can bump a fee of a Taproot transaction.

**Actual result:**
I can't bump a fee of a Taproot transaction and the Trezor freezes and has to be reconnected. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/211031578-3029a677-736d-4639-acee-74be2c146f34.png)
![image](https://user-images.githubusercontent.com/48477147/211032140-00b685b9-77c4-46a5-9fc1-daf8d81f8db1.png)

**Comment by marekrjpolak** [comment]
I suspect this: https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/api/bitcoin/refTx.ts#L23-L33

My theory is that Taproot txs don't need to send their prevTxs to the device for signing, but they still need their origTx when bumped (as the txid in the error notification is, at least in my case, of the bumped transaction itself). Could it be something like this, @andrewkozlik?

**Comment by andrewkozlik** [comment]
> My theory is that Taproot txs don't need to send their prevTxs to the device for signing, but they still need their origTx when bumped (as the txid in the error notification is, at least in my case, of the bumped transaction itself).

Yes, that is correct.

**Comment by bosomt** [comment]
**QA OK**

i was able to bump Taproot transaction

**Info:**
 - Suite version: desktop 23.2.0 (aebe81957c19c1b289f016cca5cb6b2c7808e1bf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
