### ISSUE TITLE
Cannot sign the transaction for Litecoin

### ISSUE THREAD

**Issue by rastislavcore** [trezor/trezor-suite#7344]
**Describe the bug**

I am trying to send a Litecoin transaction from Trezor Suite from a legacy account to `MR…`. After the `review & send` click it gives me the error: `Transaction signing error: value out of range`

**Info:**

-   Remembered Wallet: yes
-   Suite Version: app, Version 22.12.1 (22.12.1.24264)
-   Browser: Firefox (not relevant)
-   OS: macOS Ventura 13.1
-   Bridge: 2.0.27
-   Firmware Version: Trezor T, 2.5.1

**How to reproduce**

1. Connect Trezor T device
1. Open Trezor Suite app
1. Choose Litecoin
1. Make a new transfer from the legacy wallet
1. Click `Review & Send`
1. Error pop-in `Transaction signing error: value out of range`

**Expected behavior**

Transaction to the wallet you choose and sign the transaction.

**Screenshots**
![Screenshot 2023-01-07 at 13 38 15](https://user-images.githubusercontent.com/537310/211151045-faf3176c-4ea7-4483-b785-b31d33bc8974.png)

**Comment by mroz22** [comment]
Could you please try [22.11.1](https://github.com/trezor/trezor-suite/releases/tag/v22.11.1) ?

There were litecoin releated changes in [22.12.1](https://github.com/trezor/trezor-suite/releases/tag/v22.12.1) so I suspect that might be it. 

Also providing information about exact input you are trying to spend would be helpful. 
I was able to spend some legacy inputs to "M" address [here](https://ltc1.trezor.io/tx/98bb29aa1fc991bc5cb1f4390c302881c44c548fb3f71dfe905cd17496f17dee) so I need to figure out if there is anything specific about your tx

**Comment by mroz22** [comment]
Also please @trezor/qa check it out.

**Comment by bosomt** [comment]
**QA OK**

i was not able to replicate issue in current 22.12.1 version.
Tried all combinations of accounts + used send all and coin control randomly.


**Info:**
 - Suite version: desktop 22.12.1 (ddaacdb2245d7a909b3d2abfe918cff34d2e1609)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

results:
_Legacy to legacy segwit_
https://ltc1.trezor.io/tx/360e2f8aed58a5a3227192fc3382c727d809dbc8fd89d7104546a948526ac13e
_Leagacy segwit to default account_
https://ltc1.trezor.io/tx/30419671ff96eb74f68daba95a1b1bf0620446a2ff951cc30dcf384eaa4122a2
_Default to segwit account_
https://ltc1.trezor.io/tx/8de6bd0fb84a25e44196cdd002bd7092457fab326d01090002e27efc8d1b2d72
_Default to Legacy_
https://ltc1.trezor.io/tx/018809f0b57827fca640ef91ed9ffd9207b7a9892e4dda2f3a60b9525c7728a1
_Legacy segwit to Legacy_
https://ltc1.trezor.io/tx/0026fadab63b19313a70d8e3605f884f666f8e0fd9b3f31b72cf6bd9e80ac595
_Legacy to default_
https://ltc1.trezor.io/tx/6dc6cdee00a095890ce1d5978dae096473845070f3514dce9ac2e353b39c3191
_Legacy to default AND legacy segwit_
https://ltc1.trezor.io/tx/126f2d5324bb9f0db6a0b985d5b7631a9e5323048092fa3a11d6e8941bb785b8

**Comment by bosomt** [comment]
sent 10+ tx /from and to all account types / without any problem

**Comment by STew790** [comment]
Sent 3-5 tx to different account types and also without any problems. Approving.

**Comment by rastislavcore** [comment]
Facing the problem occasionally. I will try to trace more.

**Comment by sime** [comment]
@rastislavcore New version is due to be released tomorrow. If you are desperate, you can enrol into the early access program.
