### ISSUE TITLE
backup modal visual 

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#7361]
This feels broken 

![image](https://user-images.githubusercontent.com/30367552/211531785-71ef0b81-16c5-4820-8223-8c1172758987.png)

**Comment by Hannsek** [comment]
Left align the third checkbox with the two above.

**Comment by bosomt** [comment]
**QA OK**

<img width="545" alt="image" src="https://user-images.githubusercontent.com/31506317/218029594-667463d3-6f5f-446a-888d-d03f7080aa4d.png">

**Info:**
 - Suite version: web 23.3.0 (8855c112658e0e115632d2ec93eb368fc62457cf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model 1 1.8.2 Universal (revision 3c19e3167d69902305a27f10e43abb5fc7a0254d)
 - Transport: BridgeTransport 2.0.32
