### ISSUE TITLE
Use lower case in the name `coinjoin`

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7365]
Replace word `CoinJoin` with `coinjoin` wherever it appears.

Same applies if we use coinjoin as a verb or noun.

**Comment by matejkriz** [comment]
There are some hardcoded values that can't be changed from crowdin:
- account name
- maybe some error messages
- ?

**Comment by Hannsek** [comment]
Account name should be `Coinjoin`, no? Same as e.g. `Bitcoin Taproot`.

**Comment by matejkriz** [comment]
> Account name should be `Coinjoin`, no? Same as e.g. `Bitcoin Taproot`.

I just prepared the PR https://github.com/trezor/trezor-suite/pull/7555, removing account type names from the badge completely (the information about selected account type remains in the select under the badge)

**Comment by Hannsek** [comment]
There is still _Taproot_ with the capital _T_. 
![image](https://user-images.githubusercontent.com/57008159/217005532-c708c27b-9317-413c-8a4e-6234b303f2c0.png)

**Comment by matejkriz** [comment]
> There is still _Taproot_ with the capital _T_.
> ![image](https://user-images.githubusercontent.com/57008159/217005532-c708c27b-9317-413c-8a4e-6234b303f2c0.png)

Yes. I believe this is correct, isn't it?
<img width="541" alt="image" src="https://user-images.githubusercontent.com/3729633/217222908-53973bfc-d8b3-4fe4-affd-20a1b8c4d444.png">

**Comment by b-irving** [comment]
Looks good @matejkriz

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.3.0 (3d9487a67690ed0411a2c4081c685308c0b146ef)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
