### ISSUE TITLE
ETH internal transactions and token transfers

### ISSUE THREAD

**Issue by mkolar242** [trezor/trezor-suite#7368]
<details>
  <summary>Design</summary>

![tx-detail-modal](https://user-images.githubusercontent.com/42438053/211798590-446ecc50-91ef-4f9d-a9df-3faa81aa2315.png)

![tx-detail-mobile](https://user-images.githubusercontent.com/42438053/211798650-e09242fe-17eb-454b-adfd-8e1f091e3251.png)

![inputs-outputs](https://user-images.githubusercontent.com/42438053/211798626-eed54f05-0659-43e5-9f2e-03abca29ddeb.png)

![tx-history](https://user-images.githubusercontent.com/42438053/211798720-5844039f-8993-4c0f-b9a5-339e7e266369.png)

</details>

As a user, I want to see internal transactions, ERC20 token transfers, ERC721 token transfers, and ERC1155 token transfers in the transaction history in Trezor Suite. 

**Acceptance criteria**

As a user, I want to see additional details in the transaction detail modal.

As a user when I click on details of the outgoing or incoming transaction, the modal window will include the following details in the “Inputs, Outputs” tab (Picture - tx-detail-modal):

<details>
  <summary>Amount</summary>
- tab remains as is
</details>

<details>
  <summary>Inputs / Outputs</summary>

- **Inputs, Outputs information to be taken from the Blockbook API:**
    - Inputs - the address from `vin`  → `addresses`
    - Outputs - the address from `vout` → `addresses`
    - **Internal transactions** - displays:
        - Inputs - the address from `internalTransfers` → `from`
        - Outputs
            - the address from `internalTransfers` → `to`
        - Value - the value from `internalTransfers` → `value`
            - ETH value → internal transactions work with ETH exclusively (no tokens involved)
    - **ERC20 tokens transfer** - displays:
        - Valid for `tokenTransfers` → `type: ERC20` only
        - Inputs - the address from `tokenTransfers` → `from`
        - Outputs
            - the address from `tokenTransfers` → `to`
        - Value - the value from `tokenTransfers` → `value`
            - token’s ticker is taken from `tokenTransfers` → `symbol`
    - **ERC721 tokens transfer** - displays:
        - Valid for `tokenTransfers` → `type: ERC721` only
        - Inputs - the address from `tokenTransfers` → `from`
        - Outputs
            - the address from `tokenTransfers` → `to`
        - Value - the value from `tokenTransfers` → `value`
            - upon clicking on the token ID the blockbook detail of the ERC721 token is opened in a new window
            - token’s ticker is taken from `tokenTransfers` → `symbol`
    - **ERC1155 tokens transfer** - displays:
        - Valid for `tokenTransfers` → `type: ERC1155` only
        - Inputs - the address from `tokenTransfers` → `from`
        - Outputs
            - the address from `tokenTransfers` → `to`
        - Value - the value from `tokenTransfers` → `multiTokenValues` → `id`
            - upon clicking on the token ID the blockbook detail of the ERC721 token is opened in a new window
            - token’s ticker is taken from `tokenTransfers` → `symbol`   
    - If there is more then 5 inputs or outputs I want to see “Analyze in Blockbook” banner above the inputs and outputs (Picture - inputs-outputs)
        - When I click anywhere on the banner I want to be redirected to the Blockbook to analyze the whole transaction
        
 </details>

<details>
  <summary>Transaction history</summary>

    As a user I want to see the following in the transaction history (Picture - tx-history)
    
    - When I send or receive ETH only, transaction record remains as is
    - When I send or receive ERC20 token only, transaction record remains as is
    - When I send or receive NFT token only I want to see “Sent NFT” or “Received NFT”
    - When I send or receive any combination of the above I want to see “Sent multiple tokens” or “Received multiple tokens”
 
</details>    

 <details>
  <summary>Mobile</summary>

    As a user I want to see the address displayed in the following format (Picture - tx-detail-modal)
    
    - First characters of the address (number depends on how many we can fit on the display)
    - followed by three dots
    - followed by last six characters of the address

 </details>

<details>
  <summary>Backend details</summary>

1. Goerli testnet
- https://goerli1.trezor.io/address/0x9Fe6529815DffCB7B42E46B73984A85c786c995F
- https://goerli1.trezor.io/api/v2/address/0x9Fe6529815DffCB7B42E46B73984A85c786c995F
- https://goerli1.trezor.io/tx/0x930fc77ec3ba194e700f3f7e716369fe474cbfea73e77d32af4fc9eee831b8fc
2. Ethereum mainnet
- New Blockbook version
   - https://eth3.trezor.io/address/0x62270860B9a5337e46bE8563c512c9137AFa0384
   - https://eth3.trezor.io/api/v2/address/0x62270860B9a5337e46bE8563c512c9137AFa0384
   - https://eth3.trezor.io/tx/0x3a98e4346e3b63723d48f9e837050b75495b0ddd24b4abfe7976a5557fbfb05f
   - https://eth3.trezor.io/api/v2/tx/0x3a98e4346e3b63723d48f9e837050b75495b0ddd24b4abfe7976a5557fbfb05f
- Legacy Blockbook version
   - https://eth1.trezor.io/address/0x62270860B9a5337e46bE8563c512c9137AFa0384
   - https://eth1.trezor.io/api/v2/address/0x62270860B9a5337e46bE8563c512c9137AFa0384
   - https://eth1.trezor.io/tx/0x3a98e4346e3b63723d48f9e837050b75495b0ddd24b4abfe7976a5557fbfb05f
   - https://eth1.trezor.io/api/v2/tx/0x3a98e4346e3b63723d48f9e837050b75495b0ddd24b4abfe7976a5557fbfb05f
 
</details>

**Comment by tomasklim** [comment]
Regarding transaction history:
I would like to use ETH function name if it is available.

It is better for users to see `Swap...` instead of `Sent multiple tokens`.
Better to see `Approve` instead of `Sent ETH`...

![Screenshot 2023-03-07 at 19 31 52](https://user-images.githubusercontent.com/33235762/223517007-4fefeb04-f690-4584-9c56-06d64cb74eb2.png)

I also added internal transaction there.

**Comment by mkolar242** [comment]
Agreed we will use methodID's `name` if available

**Comment by STew790** [comment]
**QA OK**
We see many different ETH transactions and transfers.

![image](https://user-images.githubusercontent.com/48477147/232526836-f0e1075b-817c-49f4-89e2-967847d34ff1.png)
![image](https://user-images.githubusercontent.com/48477147/232526985-14a726c5-01b0-4f12-bae0-6a25ccbee585.png)
![image](https://user-images.githubusercontent.com/48477147/232527108-2b12452b-7453-4a82-a0a8-bc1e376c31cc.png)
![image](https://user-images.githubusercontent.com/48477147/232528100-f5407f8d-9a38-451b-af4f-1878f47ac034.png)

**Info:**
 - Suite version: desktop 23.4.1 (cff9e3ab255d4a7feebe7fb81ff3170146ee3537)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
