### ISSUE TITLE
connect prevent phishing domains

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#7372]
- get some domains blacklist
- deploy it somewhere (data.trezor.io)
- if iframe was loaded by a domain that is blacklisted, connect nukes itself
- blacklist should be easily updated (github job), ideally nighly

cc @tsusanka

**Comment by tsusanka** [comment]
After some discussion in the office we concluded that we do not need to fetch the blacklist remotely and we could just simply use https://github.com/MetaMask/eth-phishing-detect. And we can iterate from there in future.

cc @sime

**Comment by STew790** [comment]
**QA INFO**
Can't really test this one as it is stated in the PR https://github.com/trezor/trezor-suite/pull/7488 .
Moving on.
