### ISSUE TITLE
After enabling coinjoin account a cmd line window appears and doesn't close

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#7374]
**Describe the bug**
After enabling CJ account, a cmd line window appears with WalletWasabi.WabiSabiClientLibrary.exe in title and doesnt close. It is probably something that should be running in the background but it just stays there. This is happening only on Windows. This wasnt happening on the 22.12.1 version.

**Steps to reproduce:**
1. Install Suite 23.1.1 on Windows machine
2. Go to accounts and  try to add coinjoin account
3. After enabling Tor, a cmd line window appears.

**Info:**
 - Suite version: desktop 23.1.1 (5d418b5646266ae2d0bb2e40919a3954fe47e462)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Win32
 - Screen: 1536x864
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.27

**Expected result:**
The wasabi exe library should run in the background.

**Actual result:**
A command line window appears with exe library from wasabi.

**Screenshots:**
![image (1)](https://user-images.githubusercontent.com/48477147/212082384-6d81a367-130d-4cc4-ab0f-cdf3aa64acae.png)

**Comment by hynek-jina** [comment]
Duplicity of: https://github.com/trezor/trezor-suite/issues/7375#issuecomment-1380420930
