### ISSUE TITLE
After enabling CJ account a cmd line window appears and doesn't close

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#7375]
**Describe the bug**
After enabling CJ account, a cmd line window appears with WalletWasabi.WabiSabiClientLibrary.exe in title and doesn't close. It is probably something that should be running in the background but it just stays there. This is happening only on Windows. This wasn't happening on the 22.12.1 version.

**Steps to reproduce:**
1. Install Suite 23.1.1 on Windows machine
2. Go to accounts and  try to add coinjoin account
3. After enabling Tor, a cmd line window appears.

**Info:**
 - Suite version: desktop 23.1.1 (5d418b5646266ae2d0bb2e40919a3954fe47e462)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Win32
 - Screen: 1536x864
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.27

**Expected result:**
The wasabi exe library should run in the background.

**Actual result:**
A command line window appears with exe library from wasabi.

**Screenshots:**
![image (1)](https://user-images.githubusercontent.com/48477147/212082384-6d81a367-130d-4cc4-ab0f-cdf3aa64acae.png)

**Comment by prusnak** [comment]
By default console apps on Windows create their own terminal window. We need to modify the build so it does not do this.

There is a way to just hide the window on start, but this is ugly and confuses users (because it shows a window for few milliseconds).

Guide from the internet:
> Just go to the application's Properties and change the Output type from Console Application to Windows Application.

Since we don't use GUI such as Visual Studio, we need to figure out how to change the setting via a command line.

**Comment by matejkriz** [comment]
Just tested together with @STew790 that it is happening on the unsigned version too (23.2.0)

**Comment by matejkriz** [comment]
@STew790 Please test on Windows those two cases:

- old middleware with the new suite (Suite 23.2.0, middleware from last year)
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/3610155198/artifacts/browse

- new middleware with the old suite (Suite 22.12.1, middleware from the current EAP)
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/3610132419/artifacts/browse

**Comment by STew790** [comment]
So the result is:
 - the old middleware with new Suite (23.2.0) shows the cmd line
 - the new middleware with old Suite (22.12.1) doesn't show the cmd line

**Comment by matejkriz** [comment]
So it looks like Suite issue, not middleware issue 🤔 There were no update of Electron, so maybe the added logging. Will prepare another build to test 🏃‍♂️

**Comment by matejkriz** [comment]
branch https://github.com/trezor/trezor-suite/tree/fix/coinjoin-middleware-bin-on-win

pipeline running https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/751015546

**Comment by STew790** [comment]
Cmd line not showing on this branch :tada:

**Comment by matejkriz** [comment]
@trezor/qa please test the build from this pipeline on Win 🙏 
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/3629601587

**Comment by bosomt** [comment]
**QA OK**

Info:
 - Suite version: desktop 23.2.0 (a18d568085efa8fc32512a674bb01a9c036ef25c)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by STew790** [comment]
**QA OK**
No cmd line present.

**Info:**
 - Suite version: desktop 23.2.0 (1e0a304f3a81ec33ca667e93b0d2a4c4adeab865)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Win32
 - Screen: 1536x864
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
