### ISSUE TITLE
Report reason for failing to sign coinjoin

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-suite#7376]
Suite should report to SatoshiLabs any failures which cause a coinjoin round to break. A round is broken if one or more of the clients fail to provide their transaction signatures to the coinjoin coordinator. Possible reasons that we need to watch out for and report are:
- Internet disconnection during the critical phase.
- Tor failure during the critical phase.
- Forced Suite shutdown during the critical phase.
- Coordinator did not provide `affiliateRequest`.
- Trezor disconnection during the critical phase.
- Trezor error during signing (including the error message), e.g. `Invalid signature in CoinJoin request` or `Invalid external input`.
- Trezor takes too long to sign, i.e. Suite cannot return the transaction signature within the deadline.
- Big latency in Tor. (Not sure if we have a way to detect this on the client side, but let's try.)
- Other?

These events should be reported to us via Sentry. Reporting via the analytics system seems unsuitable, because it allows opting out. We don't want to allow opting out in this case, because diagnosing the round breakage is too important. Nevertheless, we should do maximum for user privacy by reporting these events via Tor (except for actual Tor failures, which will have to go through clearnet).

**Comment by matejkriz** [comment]
> These events should be reported to us via Sentry. Reporting via the analytics system seems unsuitable, because it allows opting out. We don't want to allow opting out in this case, because diagnosing the round breakage is too important. Nevertheless, we should do maximum for user privacy by reporting these events via Tor (except for actual Tor failures, which will have to go through clearnet).

We use exactly the same condition for reporting to Sentry as we have for reporting to analytics so that doesn't make any difference. We can discuss if we should force report for those cases, but then it should be clearly communicated (https://github.com/trezor/trezor-suite/blob/develop/docs/analytics/index.md). 

But Sentry has some queue that is needed to be able to report e.g. internet disconnection, we don't have such queue for analytics yet.

**Comment by STew790** [comment]
**QA OK**
Already looked for the possible reasons in the sentry for this one here https://github.com/trezor/trezor-suite/pull/7733 and the reasons in Sentry were reasonable and reported correctly.

**Info:**
 - Suite version: desktop 23.3.1 (76c3579c21da2debfcc2f2124875974f201e84f1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.1 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision e2416bcec2072baf65dda2d3c2359cc7217753bc)
 - Transport: BridgeTransport 2.0.32
