### ISSUE TITLE
Warn about uneconomical coinjoin

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-suite#7377]
In Wasabi wallet, when the overall account balance is below 0.01 BTC (1 million sats) the application warns the user that "_Coinjoining might be uneconomical. Receive more funds or press play to bypass._"
- Let's replicate this warning in Suite when the user clicks the Anonymize button. Wasabi refers to the threshold value as `PlebStopThreshold`, but maybe we want to call it something like `UneconomicalCoinjoinThreshold`.
- Inform the user during coinjoin account onboarding that "_Coinjoin might be uneconomical if your account balance is below_ `UneconomicalCoinjoinThreshold`."

@hynek-jina please provide the design.

**Comment by andrewkozlik** [comment]
In the design, consider also #7099. It doesn't make sense to display both "Coinjoin is uneconomical" and "Funds are not available for coinjoin". (If funds are not available for coinjoin, then don't show that it's uneconomical.)

**Comment by KhadijaKamran** [comment]
Hey @andrewkozlik! I want to help with this issue.

**Comment by hynek-jina** [comment]
Thanks for your interest @KhadijaKamran 
We need to prepare design first. 

Maybe would be better to start with some issue labeled https://github.com/trezor/trezor-suite/labels/good%20first%20issue
Or do you have some specific knowledge or interest in this one?

**Comment by hynek-jina** [comment]
- not recommended (uneconomical) coinjoin (for funds bellow 1 000 000 sats)
![Wheels](https://user-images.githubusercontent.com/26002916/217817255-ad38676e-4674-4c2a-b65f-ef103682fbfa.png)
- Warning modal
_when user tries to start coinjoin_
![Group 18865](https://user-images.githubusercontent.com/26002916/217817359-b4dbc29e-a353-49e1-989c-97883f9edf7f.png)
- Improved warning message in `Receive` tab
![Snímek obrazovky 2023-02-09 v 13 48 11](https://user-images.githubusercontent.com/26002916/217818096-04d15251-6fab-4ae4-898a-b8041c0d7057.png)

Amounts showed primary in sats/bitcoin and in brackets visible in fiat based on users settings.

For copy see [Notion page](https://www.notion.so/satoshilabs/Warn-about-uneconomical-coinjoin-c0d6c3b99d284e378309312e385a050f)

**Comment by bosomt** [comment]
@hynek-jina Receive sections says `CoinJoin at least 1,000,000 sat TEST for the best results.` We should change it to Coinjoin, right ?



![Image](https://user-images.githubusercontent.com/31506317/228461673-946bdc36-f615-441d-bbf9-1a51d14f2942.png)

**Comment by hynek-jina** [comment]
@bosomt Yes..
I just don't see the string in the crowdin. @dahaca can you help please? Which string is that?

**Comment by bosomt** [comment]
**QA OK**

@hynek-jina do you want issue for that CoinJoin in receive tab ?


![Image](https://user-images.githubusercontent.com/31506317/229723001-0f9daa4f-54fe-4e54-a8b6-99b078f1b280.png)

**Info:**
 - Suite version: desktop 23.4.0 (21653072a7c14c04156cfc6992cec5b582b00a99)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32

**Comment by hynek-jina** [comment]
Not necessary.. thanks

**Comment by skyerjoe** [comment]
Is there any good and not so difficult explanation what could be the consequences if u start the join with an low amount ? 

cause for myself i havent so much money for joing atm in my wallet. 
may its possible to set an link which refers to an good explanation if u want to do so in wasabi wallet
