### ISSUE TITLE
Reallow replace-by-fee for coinjoin accounts

### ISSUE THREAD

**Issue by marekrjpolak** [trezor/trezor-suite#7380]
RBF functionality was disabled for coinjoin accounts, because Connect is by default fetching the original transaction from the usual backends instead of using coinjoin privacy-aware way.

We could resolve it by transforming the original transaction from the Suite redux and sending it to `TrezorConnect.signTransaction` in `refTxs` param.

Note: When we enable RBF for coinjoin accounts, we also need to handle bumping in the same way as sending (=> to pause running coinjoin).

**Comment by hynek-jina** [comment]
For the privacy reasons it is safer to keep RBF disabled on coinjoin accounts
