### ISSUE TITLE
Report anonymity gain per round

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7381]
What is the average anonymity gain per round.

- `accountAnon` is the amount-weighted average anonymity of the account's entire UTXO set $A$:
$$accountAnon = \frac{\sum_{i\in A}amount_i * anon_i}{\sum_{i\in A} amount_i}.$$
- `HindsightCount = 10` is a constant representing the number of the user's most recent coinjoins that Suite looks at when estimating the account's anonymity gain per coinjoin round.
- `HindsightDays = 30` is a constant representing the oldest coinjoin that Suite looks at when estimating the account's anonymity gain per coinjoin round.
- `DefaultAnonGainPerRound` is a constant used by Suite to estimate the anonymity gain per coinjoin round when the account's coinjoin history is insufficient. This constant should be configurable remotely.
 - `avgAnonGainPerRound` is the average `accountAnonGain` for the latest `HindsightCount` coinjoin transactions that the user participated in in the last `HindsightDays` days. If the user participated in fewer than `HindsightCount` coinjoins in the last `HindsightDays` days, then use `DefaultAnonGainPerRound` instead of each missing `accountAnonGain` value. For example if `DefaultAnonGainPerRound` is 2 and the user had 3 transactions in the past 30 days with `accountAnonGain` equal to 3, 1 and 1, then take the average of [3,1,1,2,2,2,2,2,2,2], which is 1.9.
We should not report gain anonymity per one round - always just average per multiple rounds.

### Reporting statistics:

~When to report? To be decided.~
~- every 2 - 5 rounds (randomized)?~
~- every `ReportPeriodHours * (0.5 + Math.random())` `ReportPeriodHours = 2`  ?~

~- `ReportPeriodHours = 1` is a constant representing the frequency with which Suite reports the user's average `accountAnonGain` to SatoshiLabs.~
~- When the user confirms coinjoining on Trezor, Suite should start a timer for `ReportPeriodHours` in the future. When the timer expires Suite should anonymously report to SatoshiLabs the average `accountAnonGain` over all coinjoins that the user took part in since the timer was started. If the user stops coinjoining before the timer expires, then kill the timer and report as if the time was reached. Based on these reports we will then manually adjust `DefaultAnonGainPerRound`.~
~- We can further protect the user's privacy by randomizing the reporting time, e.g. set the timer for `ReportPeriodHours * (0.5 + Math.random())` in the future, which makes it +/- 50% with uniform distribution.~
- To start with, this statistic should be reported just like any other analytics, i.e. only if the user did not opt out from reporting analytics. If in the future we decide to make the reporting of this statistic mandatory for all users, then we need to be open about it and document it in the T&Cs and elsewhere. Furthermore, if we report it for all users, then we should strive to minimize the amount of information being communicated, for example just a 1-bit value saying that the user's `accountAnonGain` is lower or higher than `DefaultAnonGainPerRound`. Based on that alone we can adjust the `DefaultAnonGainPerRound`.

### Update:
- Report the data each time coinjoin is paused or stopped. This way, no data is lost.
- `DefaultAnonGainPerRound` is only used when calculating `maxRounds`, not for reporting. Otherwise it would skew the results.
- To enhance privacy, the reported value is the average of the locally recorded rounds, not results per round.
- Round each `accountAnonGain` to three decimals, more accuracy is unnecessary.
- Unlike other reports, these should not contain `session_id` and `instance_id` so that they cannot be linked to any other reports. Instead of standard values, generate random data. This is better than empty or constant value because it allows to clean data in case they are logged more than once which sometimes happens.

**Comment by matejkriz** [comment]
~watiting for https://github.com/trezor/trezor-suite/issues/7388~

**Comment by komret** [comment]
Here's an example of data that would be sent to analytics with my current implementation when coinjoin is stopped after three rounds: `[0.07371749324409693, -0.718031095381944, -0.8408360047619985]`. The negative numbers represent reduced anonymity. Is this a good format? Should I round the numbers? To how many decimals?

**Comment by komret** [comment]
I updated the issue specification after discussing with @andrewkozlik and @matejkriz. Please check it out to make sure I am on the right track.

**Comment by STew790** [comment]
**QA OK**
Confirmed with our data team, works fine.
**Info:**
 - Suite version: desktop 23.4.1 (cff9e3ab255d4a7feebe7fb81ff3170146ee3537)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
