### ISSUE TITLE
FeeFormatter

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7385]
Create formatter for formatting fee values. We want to replace this: ``${getFeeRate(transaction)} ${getFeeUnits('bitcoin')}``

**Comment by juriczech** [comment]
@Nodonisko do we still need this? Transaction already has fee, rates and symbol so it shouldn't be necessary.

**Comment by Nodonisko** [comment]
@juriczech What do you mean by "transaction already has fee"? In `suite-native/transactions/src/components/TransactionDetail/TransactionDetailParametersSheet.tsx` we still use two functions mentioned above and I think you can't use directly `transaction.fee` because value needs to be processed `getFeeRate(transaction)`.

**Comment by juriczech** [comment]
Closed in favor of #7729

**Comment by mnuky** [comment]
For ETH we will not show fee gas per byte, but same as in Desktop Suite
