### ISSUE TITLE
Estimate the number of coinjoin rounds

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-suite#7388]
Estimate the total number of coinjoin rounds needed to finish anonymizing the user's account.

Below is a proposal for a very rough but fairly simple estimation algorithm for the coinjoin MVP. Let's see how it performs and we can progressively improve it to work with more detailed statistics.

- `targetAnon` is the account's target anonymity score configured by the user.
- `accountAnon` is the amount-weighted average anonymity of the account's entire UTXO set $A$:
$$accountAnon = \frac{\sum_{i\in A}amount_i * anon_i}{\sum_{i\in A} amount_i}.$$
- `accountAnonCapped` is defined similarly, but with the anonymity capped at `targetAnon`:
$$accountAnonCapped = \frac{\sum_{i\in A}amount_i * \min(targetAnon, anon_i)}{\sum_{i\in A} amount_i}.$$
- For each coinjoin transaction `tx` define `tx.accountAnonGain = max(0, accountAnonAfter - accountAnonBefore)`, where `accountAnonBefore` and `accountAnonAfter` is the `accountAnon` immediately before and immediately after the coinjoin transaction.

- `DefaultAnonGainPerRound` is a constant used by Suite to estimate the anonymity gain per coinjoin round when the account's coinjoin history is insufficient. This constant should be configurable remotely.
- `MinAnonGainPerRound = 0.1` is the minimum anonymity gain per coinjoin round that is used to avoid division by zero when computing `roundsNeeded`.

- The expected number of rounds remaining is then computed as:
$$roundsNeeded = \frac{targetAnon - accountAnonCapped}{\max(MinAnonGainPerRound, DefaultAnonGainPerRound)}$$
This should be used as the value of `rounds_needed` in https://github.com/trezor/trezor-suite/issues/7113 and https://github.com/trezor/trezor-suite/issues/7114.

**Comment by andrewkozlik** [comment]
For the coinjoin MVP we can implement a simpler solution which replaces `avgAnonGainPerRound` with `DefaultAnonGainPerRound`, because it turns out that implementing the computation of `avgAnonGainPerRound` can be a bit tricky. If we do go with this simplified solution, then let's not close this issue to make sure that we follow up on the rest of the work post-MVP.

**Comment by matejkriz** [comment]
I just updated the description - moved parts about reporting statistics to folowup issue https://github.com/trezor/trezor-suite/issues/7381

**Comment by hynek-jina** [comment]
Can I close the issue?
