### ISSUE TITLE
Account export file is named "CoinJoin" for BTC and "uknown" for other coins even with labels enabled

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#7389]
**Describe the bug**
When I want to export my account history with labels, the file that is created is now named "CoinJoin" for BTC accounts and "uknown" for other coins and not after the account name with my label as it was before. This is the case for this version and for 22.12.1. On version 22.11.1 it is named correctly.

**Steps to reproduce:**
1. Enable labeling in settings
2. Label your BTC account
3. Try to export it to a file
4. The file named "CoinJoin" and not after your desired label

**Info:**
 - Suite version: desktop 23.1.1 (5d418b5646266ae2d0bb2e40919a3954fe47e462)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Expected result:**
File export name for accounts should be named after the label for the desired account.

**Actual result:**
File export name for account is "CoinJoin" for BTC accounts and "uknown" for other coins.

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/212467906-4f18663f-fd3a-4309-b2a6-bc5d33e70512.png)
![image](https://user-images.githubusercontent.com/48477147/212467916-4e5c86bd-63cd-48b7-bcd2-1c80d5a48ce1.png)
![image](https://user-images.githubusercontent.com/48477147/212468306-f1d3367a-f4b6-4bbc-853a-19bf1f2474c8.png)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 23.2.0 (ca7dd2d4235aad9907e7e948937a2a46e3ee52ed)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
