### ISSUE TITLE
Optimise blockfilters (coinjoin) discovery process

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#7390]
discovery of [vpub5Yme8...Q3CTZM9](https://tbtc1.trezor.io/xpub/vpub5Yme8cvVDuECgS5vuY8rYyVMrnSvDaUwbDeKLNhh3BKZYe3fpKKapVQUFAEVpyBbwaUhZLeZLcwcoRMweSfRtFxB6MenWh3NweXrQ3CTZM9) (~600k blocks, ~540 txs) over Tor now takes approx. 43 minutes
-  filters could be fetched faster, independently on blocks/transactions
- remove the need of fetching txs by two requests (block + every relevant tx in it)
- fetch all mempool txs with one request (from coordinator, not blockbook)
- store fetched filters for later usage (e.g. discovering another account)

**Comment by marekrjpolak** [comment]
> filters could be fetched faster, independently on blocks/transactions

They are now.
> remove the need of fetching txs by two requests (block + every relevant tx in it)

Done.
> fetch all mempool txs with one request (from coordinator, not blockbook)

We're going to synchronize the mempool in a different way.
> store fetched filters for later usage (e.g. discovering another account)

Currently not implemented, but if you have only one remembered cj account (which is the recommended way) there is no benefit from doing it.

Soo, shall we close this issue? @hynek-jina?

**Comment by hynek-jina** [comment]
Yes... No need for QA testing.
