### ISSUE TITLE
Address poisoning attack: Label zero value transactions in TX detail

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7400]
As a user I would like to be warned that I might have received potential scam transaction in order to avoid copying the address and use it elsewhere and lost money.

When potential scam transaction with Zero value appears, we display icon on transaction list with exclamation mark

When user access the transaction, there is a notification informing user about possible fraudulent with text: "Caution! This transaction may be a scam. If you’re unsure, don't engage. Read more here (link: https://trezor.io/support/a/address-poisoning-attacks). 

Figma: https://www.figma.com/file/xiPjYIgQtWDEhpFBwvhLlj/MobileApp-%E2%80%A2-Assorted?type=design&node-id=2088%3A22475&mode=design&t=dPfd5yhLrPa9lJAK-1

Same issue has been developed in Desktop Suite: [Address poisoning attack: Label zero value transactions in TX detail](https://github.com/trezor/trezor-suite/issues/7278)

**Comment by PeKne** [comment]
@mnuky There are multiple design variants in both links. Could you please share a screenshot, which specific design variant is the final solution? Thanks 🙏.

**Comment by bosomt** [comment]
@mnuky 
not sure if we are hiding them or only warning users  , i dont see scammy transaction in tx history.
See comparison 23.11.x and 23.11.x Lite and desktop app

<img width="666" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/6c348ac1-0dde-4326-bd72-7de51676cc5f">
<img width="384" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/e2cf3786-afac-42b1-aa9a-274b722caa13">
