### ISSUE TITLE
Token outputs cannot be given labels.

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#7402]
**Describe the bug**
The `TokenTransfer` component does not include `MetadataLabeling` which leads to token transfers not being able to have labels. Although a label can be added in send form when creating the transaction, it is never displayed. Affects both Ethereum and Cardano.

**Expected behavior**
Be able to add label to token outputs and display it in history.

**Screenshots**
https://user-images.githubusercontent.com/42465546/212911686-b7d56405-8de4-4f1f-8850-9950bf5a419f.mov

**Comment by mroz22** [comment]
https://github.com/trezor/trezor-suite/pull/5155
never finished ...

**Comment by hynek-jina** [comment]
Consider https://github.com/trezor/trezor-suite/issues/7406

**Comment by bosomt** [comment]
Duplicity ? https://github.com/trezor/trezor-suite/issues/3545

**Comment by komret** [comment]
Closing in favour of https://github.com/trezor/trezor-suite/issues/3545.
