### ISSUE TITLE
Transaction detail is rerendering like crazy

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7414]
Turn on rerender indicator in debug menu and go to TransactionDetailScreeen to check and reproduce.

I traced issue down do `blockchain` selector. It's because it is not respecting advice to always select only smallest neccessary part of state but here is selector whole blockchain part of state, which is changed very often. 

Also it seems it is not even necessary, because it is used for generating Explorer url, but you can get this from static object `networks` from network-config.

Then it's passed all way down through many components `TransactionDetailParametersSheet` and it's rerendering everything on the way only because to get one number `blockchain.blockHeight`. This should be solved by selector directly in component where it is used and which will select only that `blockHeight`.

**Comment by bosomt** [comment]
**QA OK**

tested on latest version 64ff83b
