### ISSUE TITLE
Pause coinjoin while being in send dialog

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7416]
We want to prevent ruining of coinjoin rounds due the conflict with sending transactions.

- Pause coinjoin when user enters send dialog
- _User will be informed about that in global state bar_
- Resume the coinjoin once user leave send dialog

**Comment by matejkriz** [comment]
Just a note for product review @hynek-jina  - there is no loading state for the auto-resuming coinjoin session when user leave send dialog. It is possible to add it if that's what it takes.

**Comment by hynek-jina** [comment]
@matejkriz Meaning it just start immediately? I don't have a problem with that..

**Comment by matejkriz** [comment]
> @matejkriz Meaning it just start immediately? I don't have a problem with that..

you'll see when you try it, it's not immediate, there is a small delay

**Comment by hynek-jina** [comment]
So it stays for circa 1 sec paused, right? It is ok.

**Comment by bosomt** [comment]
Its easy to break this via entering Send dialogue multiple times and leaving to main CJ page.
You will get device error and CJ will stay paused till you resume it manually.

@hynek-jina follow up issue ?

<img width="374" alt="image" src="https://user-images.githubusercontent.com/31506317/215438547-a8715514-d341-44a3-9623-d0874c43f866.png">

<img width="703" alt="image" src="https://user-images.githubusercontent.com/31506317/215438483-953584aa-0deb-402c-95c7-3934a22b1845.png">


**Info:**
 - Suite version: desktop 23.2.0 (1715c7a70a103c5ce94f9ca7a9e5075b06d99746)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by STew790** [comment]
**QA OK**
When I don't "mash buttons" and switch to send-form and back casually, it works just fine.

**Info:**
 - Suite version: desktop 23.2.0 (45c816db15aea3444dea02e0edc777748ef8052c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision ff35c77bad82c7acac1df6245940ebe0d6454642)
 - Transport: BridgeTransport 2.0.32
