### ISSUE TITLE
Diagnose high processor usage during coinjoin signing phase

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7419]

**Comment by bosomt** [comment]
[trezor-suite-log-2023-01-27T11-26-15.txt.zip](https://github.com/trezor/trezor-suite/files/10519095/trezor-suite-log-2023-01-27T11-26-15.txt.zip)

running 2 cj instances on two separate accounts and one device
not a single tx was sent and macARM battery was drained 
after restart OK but still no tx

**Info:**
 - Suite version: desktop 23.2.0 (1e0a304f3a81ec33ca667e93b0d2a4c4adeab865)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by dahaca** [comment]
@bosomt for how long was the app opened before that? Perhaps it might be related to https://github.com/trezor/trezor-suite/issues/5089?

**Comment by bosomt** [comment]
@dahaca according to log only one hour, but since then i was not able to reproduce issue, 
lets keep it open for some time and close after there will be no more reports of this issue

**Comment by sime** [comment]
Log: https://satoshilabs.slack.com/archives/C048XFAKL10/p1678979562013309?thread_ts=1678962771.091839&cid=C048XFAKL10

High CPU load, and stuck in an account discovery loop. Interesting points:
* Disabling VPN almost instantly finished discovery. CPU still high
* Disabling analytics **reduced** CPU load (after a few minutes). @marekrjpolak mentioned my log had a **lot** of requests to sentry, which might be causing the high CPU load.

**Comment by hynek-jina** [comment]
Might it be related to coin control? https://satoshilabs.slack.com/archives/C048XFAKL10/p1680011575763659?thread_ts=1679994975.532989&cid=C048XFAKL10

Other testers are reporting problems when activate altcoins...

**Comment by marekrjpolak** [comment]
Tried to reproduce it on NixOS, but no success.

**Comment by bosomt** [comment]
Currently its not possible to use Trezor Suite with latest develop version on macARM during discovery /100+ % CPU + not responding app or when responding then with 30 second lag/ 

Do we have separate issue for this ?

**Info:**
 - Suite version: desktop 23.4.0 (71e608b5a7f3e1393b153b608ac5ef9d91d19198)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 6e0c2578f8932c94413b2d1564725dc687eceaf7)
 - Transport: BridgeTransport 2.0.32

**Comment by marekrjpolak** [comment]
Coinjoin discovery or regular discovery?

**Comment by matejkriz** [comment]
@bosomt with or without Tor?

**Comment by bosomt** [comment]
coinjoin discovery with Tor enabled, so far i was not able to use coinjoin with Tor off even i disabled it in debug settings

**Comment by hynek-jina** [comment]
@marekrjpolak is reviewing discovery.
Closing since it is not related to signing phase anymore

**Comment by nostitos** [comment]
I've been monitoring the resource usage and I don't see CPU going up but I have the UI freeze for about 8 seconds about every minutes.
