### ISSUE TITLE
Repair fetching data from blockbook on mainnet

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7420]
@marekrjpolak identified some problem with fetching data from blockbook when there are more than 1000 transactions in one block. Which happens all the time on bitcoin mainnet.

**Comment by bosomt** [comment]
**QA OK**

discovery of CJ accounts works as expected

**Info:**
 - Suite version: desktop 23.2.0 (1715c7a70a103c5ce94f9ca7a9e5075b06d99746)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
