### ISSUE TITLE
`Skipping round` message with skipping turned off

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7421]
**Steps to reproduce:**
1. Run coinjoin withou skipping (Choose `Fast` option or manually turn it off in advanced settings)
2. Watch the status messages 😄 

**Info:**
 - Suite version: desktop 23.2.0 (47ff6c1b0068967d941c67675a9b6cc012464fb7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Expected result:**
No skipping rounds

**Actual result:**
Sometimes round skipped.. or at least I receive such message

**Screenshots:**
![Snímek obrazovky 2023-01-20 v 10 57 08](https://user-images.githubusercontent.com/26002916/213668597-c24e1a81-d17f-440d-8434-f4b7ecedc597.png)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.2.0 (a7d89a929c5f22d6b80707269bd1d45900862dc1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
