### ISSUE TITLE
Enable import/no-extraneous-dependencies everywhere

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7426]
It seems that eslint rule `import/no-extraneous-dependencies` is disabled for some packages (check `.eslintrc.js`).

**This rule must be enabled everywhere.** It's absolutely critical for Nx to work correctly and also to avoid problem with [phantom dependencies](https://rushjs.io/pages/advanced/phantom_deps/).

**Comment by dahaca** [comment]
What about `devDependencies`?

**Comment by Nodonisko** [comment]
@dahaca I think this rule should work for it too.

**Comment by dahaca** [comment]
@Nodonisko not sure if it makes much sense, what about the test deps? 🤔

**Comment by Nodonisko** [comment]
@dahaca Check how current config of this rule looks like. I think that's good enough for now.

**Comment by dahaca** [comment]
Yeah, I checked, that's why I'm asking wether your are fine with how it is now or you meant that the rule must be literally enabled **everywhere** :D But I got it now.
