### ISSUE TITLE
Coinjoin custom setup

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#7431]
Redesign custom setup page as follows:

![Property 1=Custom](https://user-images.githubusercontent.com/42465546/213759878-0aba2511-f520-4575-b4eb-59b32e49459f.jpg)

- [ ] Reuse or remove old code (`CoinjoinCustomStrategy` component)

**Comment by komret** [comment]
Questions for @hynek-jina:

When I change the custom settings and then close them
1) are the settings remembered so that when I reopen them I see the updated values?
2) if they are remembered when closed, do they apply to the coinjoin?
3) at which point does desired anonymity level affect the global setting? Any time the value changes in the custom settings, or only when a coinjoin is started with an adjusted setting?


My suggestions:
1 - no, custom settings always reset (same behaviour as before although it is somewhat less clear from the UI as there is no "reset" button)
2 - does not apply because custom settings reset
3 - only affect the global setting when coinjoin is started with an adjusted desired anonymity level

**Comment by hynek-jina** [comment]
Good questions, @komret 👍 
Basically I agree with all your suggestions.
1. Click on the `X` resets to default settings. We can use tooltip on that `X` - like ie "Reset to defaul settings".. 
2. Just like you said..
3. Just like you said..

**Comment by komret** [comment]
Closing in favour of #7455
