### ISSUE TITLE
Multiple tor notifications displayed in the same time

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7436]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/26002916/214054906-fc0c352c-8b7c-4768-87db-3041cf329535.png">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.2.0 (64ff83b4de9ea60507c1a8db3d4c64e6d9597004)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision ab65b18b07170c8a9e4f1506620af988d678453b)
 - Transport: bridge 2.0.32
