### ISSUE TITLE
Password for opening Trezor Suite when wallets are remembered.

### ISSUE THREAD

**Issue by cautious-bread** [trezor/trezor-suite#7439]
I feel bad submitting this as I can see there are already two other tickets (#5143 & #3247) that have been closed for the same request, but I don't see any notes/comments on those for how the feature has been implemented.

I like having wallets remembered on my suite so I can check balances or grab an address, but I would love to be able to prevent these being shown in the suite by putting it behind a password or PIN.

Has this actually been implemented?  Is it on the roadmap anywhere?

Thanks again for an amazing product and apologies if this is digging up something already dealt with.

**Comment by hynek-jina** [comment]
Thank you @greenerk ,
but there is no need to open another issue.. it actually makes the tracking more complicated.. This feature is not implemented, but we are considering that. However it's not yet on any roadmap.

I'm closing the issue as duplicity of: https://github.com/trezor/trezor-suite/issues/3166
