### ISSUE TITLE
All-time visible progress circle

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7442]
Since progress bar doesn’t represent progress of current coinjoin bundle but gained annonymity level on a whole coinjoin account, user needs to see progress bar even when the coinjoin is cancelled or not yet started. 

|State|Visual|
|---|---|
| Switch classic start button to circle one | ![Progress box](https://user-images.githubusercontent.com/26002916/214269725-4f4cf339-7c97-43f6-8206-fdb9ff0d7dcc.png) | 
|Make the progress line thinner when the coinjoin is not running| ![Progress box (1)](https://user-images.githubusercontent.com/26002916/214269739-af9c05de-038e-4215-8c4a-704dc1ed06bb.png)
|Make the outline grey when coinjoin is paused| <img width="184" alt="image" src="https://user-images.githubusercontent.com/45338719/222510085-7f755535-8e39-45bf-8c56-0e2519d7ddac.png">
|Make visible the progress circle even for fully anonymised account |![Progress box](https://user-images.githubusercontent.com/26002916/214271249-cd36b0c0-2f78-43df-ad64-52be4938a611.png)|
|Grey out a disabled progress circle|<img width="184" alt="image" src="https://user-images.githubusercontent.com/45338719/222508774-800ccfbb-222f-4ffa-9b47-2ddddf9579ee.png">

For all states see [Figma](https://www.figma.com/file/PrfGpe3axW0BBgf0UCzFyO/Exploring-CoinJoin?node-id=687%3A8842&t=ecsLn2b5xkVv40SA-1) _(but the definitions in the issue are the final ones)_

**Comment by STew790** [comment]
**QA OK**
The new visuals look nice :tada: 

![image](https://user-images.githubusercontent.com/48477147/223090099-520ceb3d-fdd5-4358-93ce-6a0ae228065f.png)
![image](https://user-images.githubusercontent.com/48477147/223104291-9665bc0b-2c6a-4f28-b2bf-3790ee234c87.png)
![image](https://user-images.githubusercontent.com/48477147/223104442-76c91861-b7e5-45c4-963a-4494705bc150.png)
![image](https://user-images.githubusercontent.com/48477147/223090215-d186f432-e985-46c1-9a1a-7b459a95a0a0.png)

**Info:**
 - Suite version: desktop 23.4.0 (98d6248ed2b9f8f264cf79c3504d4a99b08914d8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision e2416bcec2072baf65dda2d3c2359cc7217753bc)
 - Transport: BridgeTransport 2.0.32
