### ISSUE TITLE
Move all coinjoin settings into Account details

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7455]
Move all coinjoin settings into account details. Settings hidden under `Custom` strategy selection:
![Screenshot 2023-02-16 at 12 49 55](https://user-images.githubusercontent.com/26002916/219357408-c0c718b3-3472-44fe-8bd3-ebc9caff7ee4.png)

- Expand options on switch to Custom
![2](https://user-images.githubusercontent.com/26002916/219368566-d7fc3009-9601-44b8-9271-fd5648f4fddb.png)

- Disable changes while coinjoin is running
![3](https://user-images.githubusercontent.com/26002916/219368634-72b847d4-a670-4513-943a-2ed825684433.png)

Design: [Figma](https://www.figma.com/file/PrfGpe3axW0BBgf0UCzFyO/Exploring-CoinJoin?node-id=1043%3A12140&t=G8ejvrDGUO6SXHM7-0)

**Comment by andrewkozlik** [comment]
WasabiWallet logic for economic mining fee (taken from Slack dev channel):

Take the median fee rate of the last `FeeRateMedianTimeFrameHours` (=144) blocks.
If the fee rate of the current coinjoin is higher, do not participate in that round.
If the fee rate is lower, then register inputs.
This means, you will only coinjoin "in the cheaper half of the day"
What the user configures is the time span for that median value calculation, it can be hour, day, week, month, etc

So in our UI the slider could indicate what is the current daily/weekly/monthly median.

**Comment by matejkriz** [comment]
@hynek-jina Skipping round logic or presentation in UI should be reconsidered, what do you think? "Allow Trezor to skip rounds" is confusing. It's always allowed, we are skipping lot of rounds for multiple reasons. This is more like "Skip some rounds randomly". And currently we have no random skipping. 

WasabiWallet logic to be super private is "Only allow a single coin with anonymity score 1 into conjoin registration."

**Comment by hynek-jina** [comment]
I will change the copy..
Default state for this round skipping should be set to `off`

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.4.0 (21653072a7c14c04156cfc6992cec5b582b00a99)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
