### ISSUE TITLE
Skip coinjoin confirmation page when user already has confirmed latest T&C

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7456]
Requires https://github.com/trezor/trezor-suite/issues/7455 to be implemented first.

As a user, I find it annoying to repeatedly confirm terms and conditions. 
Removing the confirmation page will simplify the user flow, while making it easier to communicate [the start button](https://github.com/trezor/trezor-suite/issues/7442).

- I suggest to remove custom settings option from confirmation page. Rather to have all the setting in one place

**Comment by hynek-jina** [comment]
We need to cover logic for potential terms update. For example we could compare last coinjoin transaction with date of latest terms update. But It's a bit difficult to apply this approach on zkSNACKs or other coordinators...

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.8.1 (11285a745786e8cd7c39ada4945f5893d7e8cd23)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.8.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33
