### ISSUE TITLE
"Find logs" button in CJ account throws error because of wrong path on Windows

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#7466]
**Describe the bug**
On Windows, when I click on "Find logs" button in the CJ account, it show an error because it can't find the logs because the path to the logs is wrong. Nonetheless, the logs are created correctly and in the correct folder (path). Works fine on Linux and Mac.

**Steps to reproduce:**
1. Start Suite on Windows
2. Connect a CJ account
3. Go to the account details and click on "Find logs"
4. An error pops up that the Suite can't find the logs

**Info:**
 - Suite version: desktop 23.2.0 (a7d89a929c5f22d6b80707269bd1d45900862dc1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Windows
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision ff35c77bad82c7acac1df6245940ebe0d6454642)
 - Transport: bridge 2.0.32

**Expected result:**
"Find logs" button shows a folder with the logs.

**Actual result:**
"Find logs" button shows an error because the path to the logs is wrong.

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/214882993-07d56b33-d48b-43d2-8c2c-8913c82295ad.png)

**Comment by matejkriz** [comment]
@STew790 what do you see on Win in debug menu in Wipe app data section, please? And what if you click on the path there?
![Untitled 2](https://user-images.githubusercontent.com/3729633/214884676-1ffdd700-16f0-4fd4-8e4a-9adc659fdfc3.jpg)

**Comment by STew790** [comment]
@matejkriz unfortunately, the path is wrong there as well. The path should be for both `C:\Users\$user\AppData\Roaming\@trezor\suite-desktop\`

**Comment by bosomt** [comment]
**QA OK**

log and wipe data buttons are working as expected


![Image](https://user-images.githubusercontent.com/31506317/218410853-6df0d7ad-2fc3-4cd7-aa0f-694446897613.png)



**Info:**
 - Suite version: desktop 23.3.0 (8c1c8ad8e034a92aec5e7647f54ef1c6f95253d5)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision 461f5667777514e6921ec1a53ca3d023a2a6a092)
 - Transport: BridgeTransport 2.0.32
