### ISSUE TITLE
Coinjoin is still running even though the required level of anonymity of all utxos has been reached

### ISSUE THREAD

**Issue by zaplmi** [trezor/trezor-suite#7471]
During the feature testing, I had 5000 non-private sats on my Coinjoin account. 
After two rounds of CJ all my UTXOs has reached desired anonymity level (10) - I had no non-private sats left- however coinjoin still kept running and it kept pairing coins with rounds (and failing) in the endless loop.

Trezor Suite commit hash a7d89a929c5f22d6b80707269bd1d45900862dc1

Expected behavior is that coinjoin stops after desired level of anonymity is reached for all UTXOs of related account.

<img width="801" alt="Screenshot 2023-01-26 at 16 00 30" src="https://user-images.githubusercontent.com/91535734/215042015-de370304-2287-42f0-8a4f-d76419b9521c.png">

<img width="274" alt="Screenshot 2023-01-26 at 15 59 44" src="https://user-images.githubusercontent.com/91535734/215042082-bfc2216f-9dbe-4b5b-af6c-e5cdccda9321.png">

**Comment by komret** [comment]
**QA:**
Coinjoin session should finish with a success modal whenever there are no more non-private UTXOs. This takes some time to test, best way I found is to have one UTXO with no anonymity and set the target to 2. Another scenario to test is spending the non-private UTXOs.

**Comment by bosomt** [comment]
**QA OK**

<img width="672" alt="image" src="https://user-images.githubusercontent.com/31506317/222468653-73219a84-3174-4e2b-9947-9b532d2e3981.png">

**Info:**
 - Suite version: desktop 23.4.0 (f4dee18ecd17bcce530ae7837c5a34a7b922762a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
