### ISSUE TITLE
Monitor affiliate server state

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-suite#7478]
When coinjoin is running, before registering any coins into a round Suite should check the coordinator's status to see if the Trezor affiliate server is online. The state can be determined by verifying that `trezor` is listed amongst the `runningAffiliateServers`:
```json
"affiliateInformation": {"runningAffiliateServers": ["trezor"]}
```

If the affiliate server is not running, then:
1. Suite shouldn't register any inputs into the round.
2. Suite should indicate to the user that coinjoin is not available at the moment. The behavior should be the same as if the coordinator was down.

There is no point in checking the affiliate server state after the inputs have been confirmed. If the affiliate server goes down after that point, then the best that Suite can do is continue and hope that the affiliate server will come back up again before the signing phase.

**Comment by andrewkozlik** [comment]
Testing @trezor/qa 
- Bring the affiliate server down manually.
- Ensure that the coordinator recognizes that the server is down and signals this to clients.
- Ensure that Suite recognizes the signalling from the coordinator and does not register any of the user’s inputs into CoinJoin rounds.
- Ensure that Suite explains to the user that CoinJoins are temporarily disabled.

**Comment by STew790** [comment]
**QA OK**
 - affiliate server brought down
 - Suite recognized that the server is down and warns user about this
 - Suite also cancels the critical phase of the CJ and warns user about this
 - after the affiliate server is back up, the Suite skips the CJ round and continues with another one
