### ISSUE TITLE
Update icons for coinjoin confirmation page

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7479]
All should work with dark and light theme
**Design:** [Figma](https://www.figma.com/file/PrfGpe3axW0BBgf0UCzFyO/Exploring-CoinJoin?node-id=1%3A21321&t=3jVZwD7NQbVqi4mT-0)

It is:
- Puzzle instead of Trezor (_Trezor device was a bit more descriptive, but we gabe a prioryty to design consistency at this case_)
- Improved Lock icon
![Snímek obrazovky 2023-01-27 v 16 35 42](https://user-images.githubusercontent.com/26002916/215125967-3248c971-9b3f-459b-ac7f-89345fcaec3e.png)

Addition to https://github.com/trezor/trezor-suite/issues/7163#event-8372248751

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 23.2.0 (2256288e033ab23893a70f893d002df3b69ee84c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
