### ISSUE TITLE
TransactionDetailHeader is not handling all types of transaction

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7481]
We need to handle all types of transaction. Currently `TransactionDetailHeader` handles only send/receive. For example for self transaction it will show error box:

![Image](https://user-images.githubusercontent.com/5837757/215151959-20f7410c-3d92-4731-ba9c-ffd1efae1a54.png)

Same issue with `TransactionListItemIcon` component.

Acceptance criteria:
- All types of transactions have correct UI state in `suite-native/transactions/src/components/TransactionDetail/TransactionDetailHeader.tsx`
- All transaction types are correctly handled in `suite-native/transactions/src/components/TransactionsList/TransactionListItemIcon.tsx`

**Comment by juriczech** [comment]
@Nodonisko I guess this doesn't need to be tested by QA, right? I'll move it to done and move it back if you think there is need to test it.
