### ISSUE TITLE
Not include develop versions of Connect into analytics

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#7482]
Right now, analytics for Connect include also developer sessions.
![image](https://user-images.githubusercontent.com/57008159/215419070-2fe9d1ab-f96d-4334-8a74-0af285515f7a.png)

Change the analytics to include only public releases of Connect.

_note: Check if the same thing is happening in Suite analytics._

**Comment by sime** [comment]
As mentioned in #5397. Development data endpoint is `https://data.trezor.io/connect/log/develop.log` cc: @mroz22

**Comment by mroz22** [comment]
It looks like now it works like this: 

| domain   | log file |
|-----------|-------|
| localhost | develop.log    |
| sldev | stable.log    |
| trezor.io | stable.log    |

And you probably want to change it to  this: 

| domain   | log file |
|-----------|-------|
| trezor.io | stable.log    |
| whatever else | develop.log    |

right? 

also this comes with another question: should some build on sldev be perceived as "production" and some as "develop" builds?  maybe all should be develop and there should be connect staging envrionment on trezor.io domain?

**Comment by Hannsek** [comment]
Our goal is to have the analytics from our customers, i.e. from the end users, not from the developers/testers.

**Comment by sime** [comment]
> also this comes with another question: should some build on sldev be perceived as "production" and some as "develop" builds? 

sldev is develop from analytics POV

> there should be connect staging envrionment on trezor.io domain?

Make sense.

**Comment by bosomt** [comment]
**QA OK**

Trezor Suite analytics: 

```
GET
	https://data.trezor.io/suite/log/web/develop.log?c_v=24.2.0&c_type=router/location-change&c_commit=2acb84bb22f134bdaef4e2706a6e1041fe277ab1

```


**Info:**
 - Suite version: web 24.2.0 (2acb84bb22f134bdaef4e2706a6e1041fe277ab1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
