### ISSUE TITLE
Busy screen after coinjoin paused

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-suite#7483]
If I pause coinjoin during the registration phase, then:
1. Sometimes the busy screen appears on Trezor anyway and doesn't go away, see log.
2. Sometimes the do-not-disconnect modal appears in Suite anyway, but goes away after about 2 seconds, no log.

[trezor-suite-log-2023-01-30T09-06-38.zip](https://github.com/trezor/trezor-suite/files/10534249/trezor-suite-log-2023-01-30T09-06-38.zip)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.3.0 (8c1c8ad8e034a92aec5e7647f54ef1c6f95253d5)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
