### ISSUE TITLE
Its easy to break this via entering Send dialogue multiple times and leaving to main CJ page.

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7484]
Its easy to break this via entering Send dialogue multiple times and leaving to main CJ page.
You will get device error and CJ will stay paused till you resume it manually.

@hynek-jina follow up issue ?

<img width="374" alt="image" src="https://user-images.githubusercontent.com/31506317/215438547-a8715514-d341-44a3-9623-d0874c43f866.png">

<img width="703" alt="image" src="https://user-images.githubusercontent.com/31506317/215438483-953584aa-0deb-402c-95c7-3934a22b1845.png">

**Info:**
 - Suite version: desktop 23.2.0 (1715c7a70a103c5ce94f9ca7a9e5075b06d99746)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

_Originally posted by @bosomt in https://github.com/trezor/trezor-suite/issues/7416#issuecomment-1408259030_

**Comment by matejkriz** [comment]
Why followup when the original issue didn't pass the QA yet? Why not just reopen the original issue? @hynek-jina @trezor/qa let's discuss the process offline/slack?

**Comment by komret** [comment]
**QA:** The same error was shown when quickly clicking the pause/resume button. This is fixed now as well. I made some subtle changes to the automatic pausing/resuming as well, but let's test them after [#7524](https://github.com/trezor/trezor-suite/issues/7524) is resolved.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.3.0 (8c1c8ad8e034a92aec5e7647f54ef1c6f95253d5)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
