### ISSUE TITLE
Noisy coinjoin notification for remember wallet with no Tor connection 

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#7485]
**Describe the bug**
Noisy notification about `Coinjoin client not enabled`

**Info:**

-   Remembered Wallet: yes
-   Suite Version: Version 23.2.0 (23.2.0.25186)
-   OS: name, OSX

**How to reproduce**
1. Enable coinjoin account
2. Disable Tor
3. Restart suite

**Expected behavior**
Fail silently.

**Screenshots**
![Screenshot 2023-01-30 at 9 57 06](https://user-images.githubusercontent.com/216917/215463605-de748c21-6207-4a38-b5fd-76405ae41813.png)

**Comment by bosomt** [comment]
Did this fix made it to 23.2.2 release ? I dont see this annoying notifications anymore 🎉

**Comment by STew790** [comment]
**QA OK**
I don't see them as well.

**Info:**
 - Suite version: desktop 23.4.0 (f4dee18ecd17bcce530ae7837c5a34a7b922762a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision 557e29769b09dd3abd7b67f9b4fe3d380db9f6c9)
 - Transport: BridgeTransport 2.0.32

**Comment by bosomt** [comment]
**QA NOK**

i see it over and over again in latest release candidate

<img width="314" alt="image" src="https://user-images.githubusercontent.com/31506317/223418093-603f2e17-ec8e-4917-b596-5c0b8fb75458.png">

**Info:**
 - Suite version: desktop 23.3.1 (76c3579c21da2debfcc2f2124875974f201e84f1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.1 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32

**Comment by matejkriz** [comment]
somehow related to this https://github.com/trezor/trezor-suite/issues/7789 (but not the same issue)

**Comment by sime** [comment]
Re-opening as the issue is reoccurring, although not so noisy. Tested on Version 23.4.0 (23.4.0.26957)

<img width="443" alt="Screenshot 2023-04-03 at 20 25 37" src="https://user-images.githubusercontent.com/216917/229595319-30c55f6d-2fff-4bd1-835b-d276b9b5889c.png">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.4.1 (5044d02a986e634881bbc85393c2936dacdcb6ec)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
