### ISSUE TITLE
URL for link in Receive flow

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7486]
We don't know where link should point to.

Link: https://trezor.io/learn/a/verifying-trezor-suite-lite-addresses

![Image](https://user-images.githubusercontent.com/5837757/215469895-03cef66e-9bdc-4cd6-b4c1-5496e9d6361a.png)

**Comment by PeKne** [comment]
@mnuky The link does not work. Are you sure this is the correct link? 

![Image](https://user-images.githubusercontent.com/26143964/233016051-78d2654b-d7d7-41eb-a00c-83e45cbbd4dd.png)

**Comment by mnuky** [comment]
yes, it has not been published yet but confirmed by Grafton that it will work
