### ISSUE TITLE
Refactor Button component

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7493]
Full Button component in Figma https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=4196%3A18608&t=ZXvCPJctgw0jxI8p-1

It seems that Button design is pretty stable now, so it's time to refactor it to follow latest designs:

**Proposed API (props):**

```tsx
type ButtonProps = {
    colorScheme?: "primary" | "secondary" | "tertiary" | "danger",
    size?: "small" | "medium" | "large",
    isDisabled?: boolean,
    children: string,

    // only one of these can be used (use correct type from type-fest for it)
    iconLeft?: IconName,
    iconRight?: IconName,
}
```

Heavily inspired in https://chakra-ui.com/docs/components/button

**Acceptance criteria:**

1. Button component follows proposed API
2. All buttons combination works with correct sizes/colorScheme/isDisabled combinations (add examples to DemoScreen)
3. Button uses `Pressable` instead of `TouchableOpacity` 
4. Button change correctly color `onPress` and that change is animated

**Comment by bosomt** [comment]
**QA OK**


f81df35 - [develop] - fix(suite-native): graph selection line always visible (#7604)
