### ISSUE TITLE
Error messages&Success messages

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7495]
As a user I would like to get right messaging when something is wrong in order to be informed what is happening
As a user I would like to get the right messaging when something happened in order to feel safe and fully informed. 

**Success messages appears in those places and situations:**
- Asset has been removed
- XPUB copied
- Address copied

**Error messages appear in those places and situations:** 
- Network error - we can't read the data from XPUB
- Graph can't be loaded

```[tasklist]
- [ ] https://github.com/trezor/trezor-suite/issues/7773
- [ ] https://github.com/trezor/trezor-suite/issues/7774
- [ ] https://github.com/trezor/trezor-suite/issues/7775
- [ ] https://github.com/trezor/trezor-suite/issues/7776
```

Figma design of success / error messages: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=12244%3A98860&t=cIRdnBGEAEQ6DT1X-1
Figma components: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=9143%3A54133&t=cIRdnBGEAEQ6DT1X-1
animations: https://www.figma.com/proto/Z6AGVUmKQzLNtDozFamW7f/branch/tCSmT0EOdXmhAst051Nxal/s2-Mobile?node-id=9926%3A67312&scaling=min-zoom&page-id=7888%3A55194&starting-point-node-id=9926%3A67312&show-proto-sidebar=1

Asset removed:
![Image](https://user-images.githubusercontent.com/84183817/219389240-98d6581e-4232-4c18-98cb-4a9c690f01b3.png)

XPUB Copied, Address copied
![Image](https://user-images.githubusercontent.com/84183817/219389336-86703785-81e8-471b-b477-31bf9378d28b.png)

Network error:
https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=12728%3A95989&t=KJ9twfK3Gtr8YtS8-1
![Image](https://user-images.githubusercontent.com/84183817/221858619-09e5120f-45c5-45c0-8a3a-ca8e6f55bbce.png)

Graph can't be loaded
https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=12244%3A98860&t=KJ9twfK3Gtr8YtS8-1

![Image](https://user-images.githubusercontent.com/84183817/221858405-8c994519-7350-4b94-b516-bc57c0a67c4d.png)

**Comment by Nodonisko** [comment]
@PeKne Once you start please split this task into at least two smaller as suggested in task list.

**Comment by bosomt** [comment]
**QA NOK**

no notification on iPhone when `Asset has been removed` not sure if behavior has changed or its caused by navigating to My assets after account is removed. 

 tested on dev version 233 on iPhone 11
