### ISSUE TITLE
Warning message before user removes account

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7496]
As a user I would like get warning when I click on Remove asset in order to prevent mistakes.

Acceptance criteria:
- When user clicks on Remove asset, message with question "Are you sure?" is displayed
- When user click on Remove asset, asset is deleted
- When user click on Cancel, he is back on the asset setting screen

Figma design: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=12738%3A101906&t=9W2PyXu59BEoT0Bc-1

```[tasklist]
### Tasks

**Comment by bosomt** [comment]
**QA OK**

+ added test case to Sanity tests :)

tested on dev version 23.5.1 (425) on Android
