### ISSUE TITLE
IconButton refactor

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7497]
Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=4196%3A18608&t=ZXvCPJctgw0jxI8p-1

IconButton needs to be updated according to latest designs.

**Changes:**
1. Updates sizes/colorScheme - same as in Button component
2. Remove `isRounded` prop - it's always rounded unless there is `title` prop
3. Add `title` prop - small text under the button, should be also "clickable". If title will be longer than button size, button will grow to 100% width and doesn't have to be rounded. (Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=4196%3A18608&t=ZXvCPJctgw0jxI8p-1)

**Acceptance criteria:**

1. IconButton component follows proposed changes
2. All buttons combination works with correct sizes/colorScheme/isDisabled combinations (add examples to DemoScreen)
3. Button uses `Pressable` instead of `TouchableOpacity`
4. Button change correctly color onPress and that change is animated

**Comment by bosomt** [comment]
**QA OK**

f81df35 - [develop] - fix(suite-native): graph selection line always visible (#7604)
