### ISSUE TITLE
Give user option to stop after currently running coinjoin round

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7498]
**Design:**
|Default | Coinjoin paused|
|---|---|
| ![modal](https://user-images.githubusercontent.com/26002916/217818794-2fb65a64-e69e-4a23-9e45-2578f16cdc6e.png) | ![modal2](https://user-images.githubusercontent.com/26002916/217818799-e9f97683-de1d-4024-bd0c-cc3e01effe48.png) |

<img width="715" alt="image" src="https://user-images.githubusercontent.com/45338719/224567582-b76b2129-9fe0-48cc-b18c-6efd9a9d257f.png">

**Comment by komret** [comment]
Have you considered using `Switch` instead of the button? The implementation would be much simpler as we could reuse an existing component.

**Comment by bosomt** [comment]
**QA OK**

437a23c40b95ff323dc4dc351db9f1db7009bb08
