### ISSUE TITLE
List of transaction: Order by date is not working

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7500]
Items in transaction list should be ordered by date. The items in the month groups do not match with the group month.
E.g. Transactions from January are marked as December group - check the printscreen

![Image](https://user-images.githubusercontent.com/84183817/215711476-d001a8c0-d923-4081-8b82-85559b90da40.jpg)

**Comment by bosomt** [comment]
**QA OK**

b1b0ebf - [develop] - chore(mobile): enable iPad (#7583)
