### ISSUE TITLE
Bump fee results in TX not found

### ISSUE THREAD

**Issue by ctodea** [trezor/trezor-suite#7505]
**Describe the bug**
A transaction created with a coin control and submitted via pesonal node is not found when trying to replace it by fee.

**Info:**

-   Remembered Wallet: no
-   Suite Version: 22.12.1
-   Browser: None, Trezor suite for Linux.
-   OS: Fedora 36 Workstation Edition, Kernel: 6.0.15-200.fc36.x86_64
-   Bridge: I don't know
-   Firmware Version: Universal 2.5.3 Model T
-   Tor enabled

**How to reproduce**

1. Create a TX with 1 sat/vB fee, coincontrol picking 2 UTXO, RBF ON, broadcast OFF. Transaction sent via own node with `bitcoin-cli sendrawtransaction`. Checked that is valid in several TX explorers, including mempool.space and https://btc1.trezor.io/tx/ TX pending for long because of high congestion.
![RBF-bug](https://user-images.githubusercontent.com/8028199/215763481-62c6b717-6bf2-4075-b5f2-1a2985d9d6a5.png)

2. After hours (15~ But I do not think it is relevant) try to bump fee, pick a higher fee, from the default ones or a custom, did not make a difference to me. For instance 13 sat/vB. Hit Replace transaction.

This results in:
![RBF-bug2](https://user-images.githubusercontent.com/8028199/215763713-80fae0ec-a183-4834-910b-2cbc07286e2b.png)

And this extract in the trezor-suit-log.txt:
```
  {
    "type": "@common/wallet-core/accounts/updateSelectedAccount",
    "datetime": "*********", ##### ommited
    "payload": {
      "payload": {
        "status": "exception",
        "loader": "account-not-exists",
        "network": {
          "symbol": "btc",
          "name": "Bitcoin",
          "networkType": "bitcoin",
          "bip43Path": "******", ###### ommited
          "decimals": 8,
          "explorer": {
            "tx": "https://btc1.trezor.io/tx/",
            "account": "https://btc1.trezor.io/xpub/"
          },
          "features": [
            "rbf",
            "sign-verify",
            "amount-unit"
          ],
          "customBackends": [
            "blockbook",
            "electrum"
          ]
        },
        "discovery": {
          "deviceState": "*****", ###### ommited
          "authConfirm": false,
          "index": 0,
          "status": 4,
          "total": 6,
          "bundleSize": 0,
          "loaded": 6,
          "failed": [],
          "networks": [
            "btc",
            "btc",
            "btc",
            "btc"
          ]
        },
        "params": {
          "symbol": "btc",
          "accountIndex": 0,
          "accountType": "taproot"
        }
      }
    }
  },
```
![RBF-bug4](https://user-images.githubusercontent.com/8028199/215763632-f7ba0803-b832-426e-812f-5135ddbb868a.png)

**Expected behavior**
new TX should be created, and window in trezor suite with Sign button, then having to manually confirm in device, etc.

**Comment by hynek-jina** [comment]
Related to: https://github.com/trezor/trezor-suite/issues/5846

**Comment by sime** [comment]
hi @ctodea thanks for the report.

Will close this for now as we _just_ resolved a taproot fee bumping bug. https://github.com/trezor/trezor-suite/issues/7339

If you are experiencing this error right now, you can try the staging version of the next release (web version): https://staging-suite.trezor.io/web/

Otherwise, the Early Access Program release is planned for mid next week.
