### ISSUE TITLE
Change copy for T2B1

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#7514]
i. e. 
![image](https://user-images.githubusercontent.com/57008159/215986919-d5b18604-bd09-455b-9584-3b9c246bf488.png)

**Comment by matejkriz** [comment]
This particular place on screenshot has been fixed half year ago https://github.com/trezor/trezor-suite/commit/631c7030e4a2a1ebc3a3f79230c1cc8bf9c2f02c for English, but other languages has to be checked in crowdin (keys `TR_RECOVER_SUBHEADING_TOUCH`, `TR_RECOVER_SUBHEADING_BUTTONS`)

But I guess there are still some other places where device name is used. I see something in connect-popup.

**Comment by Hannsek** [comment]
Yeah, we have to check all places in Suite (popup). cc @mroz22
