### ISSUE TITLE
TransactionListItem broken design

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#7519]
There is broken layout for transaction list item on different view ports. Fix according to design using flex and remove margins. 

Design: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=8232%3A51930&t=K0bxw9NMaP2HuR9F-4

![Image](https://user-images.githubusercontent.com/36101761/216055308-4f4d5611-c498-4e81-a957-773f6bffab11.png)

**Comment by bosomt** [comment]
**QA OK**

tested on 93d9403 - [develop]
