### ISSUE TITLE
Prevent to send less than 20 XRP to empty account

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#752]

**Comment by bosomt** [comment]
please see: https://github.com/trezor/trezor-suite/issues/1037#issuecomment-599490838

**Comment by bosomt** [comment]
send max works fine, but you can manually change amount that will ignore 20XRP limit

**Comment by bosomt** [comment]
ah shit, i just noticed that this issue is for less than 20 xrp limit and not for keeping 20 xrp in account
