### ISSUE TITLE
Suite cannot recognize model T2B1 in bootloader mode

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#7521]

**Comment by matejkriz** [comment]
@Hannsek What is meant by this issue, please? I believe Suite properly recognize T2B1 in bootloader when you click "INSTALL FW" on the device. 
<img width="905" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/df4d3352-c1e9-4177-a6c6-e43814823392">

Until you press the "INSTALL FW" even trezorctl can't see the device.

**Comment by Hannsek** [comment]
This already works.
