### ISSUE TITLE
Unify conditions to allow coinjoin session start/restore

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#7524]
The conditions are now set individually for each spot where coinjoin session can be started or restored: main page, confirmation page, status wheel, and middleware. However, the conditions should be more or less the same for each case. Unify them in one place.

**QA:** This is a biggie. Please see the [PR](https://github.com/trezor/trezor-suite/pull/7587) for description of desired logic. Not all cases described there can be tested manually, but please try the following, ideally with multiple coinjoin sessions running, maybe even with multiple devices connected: device disconnected, coinjoin feature not enabled on old firmware version, disconnected from internet, tor disabled, UTXOs too small, send form open. Some cases pause/restore all sessions, others are only related to the selected account, as described.

**Comment by bosomt** [comment]
**QA OK**

- not able to start cj with 2.4.1 firmware
- not able to start cj when disconnected from internet
- not able to start cj when tor disabled
- not able to start cj when Account is possibly out-of-sync
- not able to start cj when there are all funds sent out of account /reports `All funds private` even there no funds 🤔 /
- not able to start cj when there is not enough sats to start cj /tested with 1000 sats/

@STew790 please try to test it out with multiple devices/dessions during upcoming cj test rounds 

**Info:**
 - Suite version: desktop 23.4.0 (f4dee18ecd17bcce530ae7837c5a34a7b922762a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32

**Comment by hynek-jina** [comment]
> /reports All funds private even there no funds 🤔 /

→ this should be resolved by this issue https://github.com/trezor/trezor-suite/issues/7442
But please test it 🙏

**Comment by STew790** [comment]
I had the same results as @bosomt and also the `All funds private` is now correctly represented by this:
![image](https://user-images.githubusercontent.com/48477147/223137515-407309f2-6337-4c33-bc81-e0671856d938.png)
So approving this, although we will definitely still monitor all of this in the upcoming testing CJ rounds.
