### ISSUE TITLE
Fix/optimise communication with Blockbook

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#7526]
Coinjoin is currently unusable on BTC mainnet, because we are almost instantly blocked (rate limited) by Blockbooks (Cloudflare). 

Mempool syncing is the main issue. Discovery may be too.

logs are full of `DEBUG(request-interceptor): request to btc1.trezor.io took 10929ms and responded with status code 503`

Currently Suite is syncing the mempool transactions from from blockbook via REST one by one.

Ideas:
 - _SOCKET_: sync via sockets instead of REST
    - same data load, but avoid rate limit
    - already implemented on blockbook, just disabled – run blockbook with `-enablesubnewtx` param
 - _RATE LIMIT_: turn off rate limit for those request
    - most likely not possible due to possible DDoS attacks 
  - _COORDINATOR_: get from coinjoin coordinator what transactions are relevant for us and ask blockbook for those only
    - fix the issue on blockbook but big increase in requests on coinjoin coordinator
  - _MEMPOOL_: sync the mempool from other sources than blockbook
  - ?

**Comment by matejkriz** [comment]
cc @marekrjpolak @szymonlesisz @mroz22 @hynek-jina 
next steps:

@marekrjpolak 
- temporary turn off mempool syncing on BTC mainnet accounts
  - to see if we still reach rate limit with other requests
  - to potentially make coinjoin on mainnet work (with crippled UX, see the note on next line)
  - note: we will not see transactions in coinjoin account until they are mined
- start implementing mempool syncing on regtest with `-enablesubnewtx` flag

@matejkriz 
- verify with admins potential costs of data transfers (full mempool via socket to every client) and changes in rate limiting

**Comment by marekrjpolak** [comment]
Issue resolved by
> SOCKET: sync via sockets instead of REST

Mempool syncing is turned on again for mainnet, there is no rate limit for websocket.

For next improvement of mempool syncing (fetching of txs already in mempool), changes are needed on Blockbook, which is currently WIP.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.4.0 (2ee6814afa5f7290889eb4b76c18412fa112b6f1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
