### ISSUE TITLE
Device disconnected reported during coinjoin start

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#7527]
**Describe the bug**
Device disconnected reported during coinjoin start even device is connected.
Replicated on multiple computers.

**Steps to reproduce:**
1. Start coinjoin
2. Observe `Start CoinJoin` button behavior after you press it

**Info:**
 - Suite version: desktop 23.2.1 (d76d623f65060a6727f84e34c3e65e515c22b2f1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32

**Screenshots:**
<img width="259" alt="Screenshot 2023-02-02 at 13 37 33" src="https://user-images.githubusercontent.com/31506317/216327324-468d3cd5-1d04-410e-921f-1674ef2b75ac.png">

https://user-images.githubusercontent.com/31506317/216327329-a2b3a3b6-c61d-4167-b41c-97298282105e.mov

**Comment by matejkriz** [comment]
I guess the desired behavior would be loading state on Start coinjoin button.

**Comment by hynek-jina** [comment]
Yes.. or at least removal of that confusing tooltip...

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.3.0 (8c1c8ad8e034a92aec5e7647f54ef1c6f95253d5)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
