### ISSUE TITLE
Create list of data we collect about user

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7540]
Write list of all information we collect about device, user for legal. We need to put it in Privacy policy document.
You don't have to write the analytics events, these will be covered by me and BI

**Comment by Nodonisko** [comment]
I put together list for Sentry https://www.notion.so/satoshilabs/Sentry-data-collected-cbac31f5e7f14981a62fbcfd7327b3f2

**Comment by matejkriz** [comment]
@mnuky Is this still relevant? Should we change the issue from creating a list to revision of the list?

**Comment by mnuky** [comment]
@matejkriz nope, this issue is more than year old and it was resolved
