### ISSUE TITLE
Enable user to rename asset

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7542]
As a user I would like to be able to rename my asset because I can name it while I'm importing it and I can change my mind

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/branch/BlVnxNzUqrZkbhHgezLczh/s2-Mobile?node-id=8313%3A36843&t=XIZhI2OO9YrqtzWu-1

Acceptance criteria:

- User can change the name of the asset in Asset detail settings
- User clicks on the pencil icon 
- When user change the name of the asset, it is changed across the app

```[tasklist]
### Tasks

**Comment by PeKne** [comment]
@mnuky Do we have a UI design for the "rename form"?  I mean the interface that shows after the pencil button is clicked.

**Comment by mnuky** [comment]
it's here: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=10219%3A55968&t=pd9bWqjToE0OoA2D-1

**Comment by PeKne** [comment]
Oh, I missed that. Thanks!

**Comment by bosomt** [comment]
**QA OK**

0a00686 - [develop] - chore(mobile): use native stack for navigation (#7702)
