### ISSUE TITLE
When coinjoin service not available auto pause does not work

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#7549]
**Describe the bug**
When coinjoin service is not available and the message " "The coinjoin service is temporarily unavailable"" is in the progress bar the automatic pause of the coinjoin session is not working.

As well as the banner that says that Tor is disable and a button to enable it is not appearing when Tor is disable with service not available.

**Info:**

-   Remembered Wallet: yes/no
-   Suite Version: latest develop bb36ba517e10d0ae8defbed47009e4f5457ab8e9
-   Browser: desktop

**How to reproduce**

1. Create a coinjoin account
2. The coinjoin coordinator service should be temporarily unavailable
3. Disable Tor
4. In coinjoin account the session is not paused and there is no banner saying Tor is disable.

**Expected behavior**
The session probably should be paused since if the service comes back to work it is not going to work anyway.

**Screenshots**
![image](https://user-images.githubusercontent.com/5362163/216934901-f14128c7-ac51-4409-b1f2-63008af0b6a5.png)

**Comment by matejkriz** [comment]
> As well as the banner that says that Tor is disable and a button to enable it is not appearing when Tor is disable with service not available.

Hey @karliatto , are you sure that you haven't `Allow no Tor` in debug menu enabled? I just tested that and seems to be working as expected to me.

<img width="813" alt="image" src="https://user-images.githubusercontent.com/3729633/217236884-db6b05ee-38e8-415d-8c74-9544aaf3a658.png">
<img width="653" alt="image" src="https://user-images.githubusercontent.com/3729633/217237084-cb56d46d-b535-430f-8f91-fe9430cd145a.png">


> **Expected behavior**
> The session probably should be paused since if the service comes back to work it is not going to work anyway.

"The coinjoin service is temporarily unavailable" means that affil server is temporary not available. That should not happen but could for a short time. There is really no need to pause the coinjoin in that case. If affil server is available in next round, coinjoin can continue without interruption.

**Comment by karliatto** [comment]
You are right @matejkriz, thanks! Closing this issue.
