### ISSUE TITLE
Migrate react-native-graph to monorepo

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7553]
We need to do more and more changes to https://github.com/margelo/react-native-graph and only option is to fork it. Please move this package to `/suite-native`, keep the name `@suite-native/react-native-graph`. This package ideally should standalone zero-dependency to our other code, at least for now.

Follow up #7264

**Comment by bosomt** [comment]
**QA OK**


Graph works as expected in mobile app
b1b0ebf - [develop] - chore(mobile): enable iPad (#7583)
