### ISSUE TITLE
Transport missing - request to http://127.0.0.1:21325/ failed, reason: connect ECONNREFUSED 127.0.0.1:21325

### ISSUE THREAD

**Issue by jaredrethman** [trezor/trezor-suite#7556]
**Describe the bug**
Following steps outlined on [README](https://github.com/trezor/trezor-suite/blob/develop/README.md?plain=1#L48-L53) and using `./packages/connect-examples/electron-main-process` I'm receiving an error - `transport-error`.

**Info:**

-   Remembered Wallet: yes
-   Suite Version: `v22.12.1`
-   Browser: Electron/Chromium
-   OS: MacOS 13.1
-   Bridge: N/A
-   Firmware Version: N/A

**How to reproduce**

1. Clone down repository and carry out instructions outline [here](https://github.com/trezor/trezor-suite/blob/develop/README.md?plain=1#L48-L53)
2. Once all steps have been followed in above, you'll need to add `connect-examples/electron-main-process/*` to `package.json` workspaces property.
3. For a more verbose output update [this line](https://github.com/trezor/trezor-suite/blob/develop/packages/connect-examples/electron-main-process/src/trezor-connect-ipc.js#L22) to `sender.send('trezor-connect', event);`
4. Then `cd packages/connect-examples/` and `yarn && yarn dev`
5. Once Electron has rendered, you should see the screenshot below

**Expected behavior**
* Electron renderers without transport error and trezor connect is able to receive further prompts/instructions.

**Screenshots**
![Screenshot 2023-02-06 at 09 32 12](https://user-images.githubusercontent.com/3676975/217014039-fb41d04e-8acb-4c2d-80e1-366ed386a0d9.png)

**Additional context**
Based on `request to http://127.0.0.1:21325/ failed, reason: connect ECONNREFUSED 127.0.0.1:21325` I feel like this could be related to Trezor Bridge (not sure). If I have Trezor Suite running this error disappears.

**Comment by mroz22** [comment]
Hi, yes, so far, you still need Trezor Bridge process running. Once we finish this https://github.com/trezor/trezor-suite/pull/6509 Trezor Bridge won't be needed anymore.
