### ISSUE TITLE
Using Trezor API in multiple tabs in MV3 chrome extensions does not work correctly

### ISSUE THREAD

**Issue by resetko-corp** [trezor/trezor-suite#7558]
**Describe the bug**
Currently there is no good way to use a single instance of library in MV3 chrome extensions, because there is no way to call `TrezorConnect` functions within background page (bg pages replaced with service worker, which don't have DOM, hence there is no way in inject `iframe`).
This means `TrezorConnect` API calls can be made from `popup.html` or other HTML pages of the extension. There could be more than one extension pages/tabs opened at once. Also we have a content script which creates port, and establish communication with the user code (application code). 

In popup manager there is a piece of code which detects if the connection event is not from the popup opened by current instance of PopupManager and calls `disconnect` on the port. This breaks communication for other instances of the API initialized. 

**Info:**

-   Remembered Wallet: yes
-   Suite Version: web, 9.0.6
-   Browser: Chrome, 109.0.5414.119
-   OS: GNU/Linux, 6.1.8-zen
-   Bridge: 2.0.32.r6.g8f35971-1
-   Firmware Version: Model T, [2.5.3](https://github.com/trezor/trezor-firmware/blob/2f03ace311584988d5aeab58fd1acf24ef54711a/core/CHANGELOG.md#253-16th-november-2022)

**How to reproduce**

1. Create manifest v3 extension with HTML page which is using `TrezorConnect` and injects an iframe
2. Open extension page in a separate tab, do any operation with Trezor (could be also just popup close)
3. Open one more extension page in another tab and try to use `TrezorConnect` calls in it. It will open a popup which will never connect until first tab is closed.

**Expected behavior**
PopupManager expected not to kill ports created by other popups.

**Comment by sime** [comment]
Thanks for the detail description @resetko-zeal, could I ask you to follow the Manifest v3 issue when it gets off the ground as an extra set of eyeballs. https://github.com/trezor/trezor-suite/issues/6458

**Comment by STew790** [comment]
**QA OK**
Tested here in our Notion https://www.notion.so/satoshilabs/QA-tasks-c6cf287ec8d94ae38995dcffbc4795f5?p=dad40086738048cc94f0a77d41186fc9&pm=s
