### ISSUE TITLE
Show warning before revealing the XPUB

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7567]
As a PM I would like to display user warning while he is revealing the XPUB via asset settings in order to increase privacy of our users and let them know the risks. 

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14455%3A107697&t=29tWcb7tYPxPqnty-1

Acceptance criteria:

- When user clicks on View XPUB, first we display warning
- If user clicks on Show Public address (XPUB), QR code and address is displayed
- For ETH, ETH classic, XRP and ERC20 tokens we don't to display this message as they have receiving address and no XPUB and the receiving address is the same as public address

**Comment by mnuky** [comment]
Fine for me

**Comment by bosomt** [comment]
**QA OK**

tested on dev version 233 on iPhone 11
