### ISSUE TITLE
Invalid translation in coinjoin critical phase modal

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#7581]
**Describe the bug**

translation mismatch
https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/support/messages.ts#L7762-L7769

`TR_SESSION_PHASE_32_MESSAGE` should correspond to `AwaitingOthersOutputs` enum
also `id: 'TR_SESSION_PHASE_32_MESSAGE'` field is duplicated

**Screenshots**
![image](https://user-images.githubusercontent.com/3435913/217547580-057499f7-5039-4d0a-9805-a3dec8b6d159.png)

**Comment by andrewkozlik** [comment]
**Not fixed.**

Version: 23.2.2 (internal release from today)
Commit: c985af54f187b7906303e9d587bf053cdb6197fd
Platform: linux x64

![image](https://user-images.githubusercontent.com/42678794/220330477-74cb0058-3e7e-46cf-a971-ee2d7a9bd768.png)

**Comment by STew790** [comment]
**QA OK**
Translation correct now.
![image](https://user-images.githubusercontent.com/48477147/222455249-4eab0e86-9f5e-4109-b3f7-d0ab149d71ff.png)

**Info:**
 - Suite version: desktop 23.4.0 (f4dee18ecd17bcce530ae7837c5a34a7b922762a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision 557e29769b09dd3abd7b67f9b4fe3d380db9f6c9)
 - Transport: BridgeTransport 2.0.32
