### ISSUE TITLE
List of transactions - "+" and "-" is missing in front of value

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7589]
In the list of transactions "-" is missing for Outgoing transactions
In the list of transactions "+" is missing for Incoming transactions

How it should look like
![Image](https://user-images.githubusercontent.com/84183817/217574895-596c0db2-8ab5-43c6-8a62-2cffae466fa5.png)

**Comment by bosomt** [comment]
**QA OK**

already fixed

33c6ca5 - [develop] - Chore\/connect t1 with pin (#9576)

* fix(connect): fix error condition on invalid pin

* feat(suite-native): allow T1 with pin connection
