### ISSUE TITLE
Building in typescript app throws errors with `tsc`

### ISSUE THREAD

**Issue by bucko13** [trezor/trezor-suite#7593]
I'm upgrading a library to build with typescript and I'm able to get everything to work except that when running a build with `tsc` there are failures on two @trezor/ dependencies (total of 8 errors, across 2 files). 

The first looks like:

```
node_modules/@trezor/connect/lib/events/ui-request.d.ts:1:46 - error TS2307: Cannot find module '@trezor/connect-analytics' or its corresponding type declarations.

1 import type { EventTypeDeviceSelected } from '@trezor/connect-analytics';
```

The second is several instances of:

```
node_modules/@trezor/transport/lib/lowlevel/webusb.d.ts:35:32 - error TS2304: Cannot find name 'USBDevice'.

35     _findDevice(path: string): USBDevice;
                                  ~~~~~~~~~
```

I was able to solve the second by manually installing the reference myself with:

```bash
$ npm install --save-dev @types/w3c-web-usb
```
(although this probably shouldn't be necessary and should be included in the `@trezor/transport` dependencies I think).

The first one I'm unable to resolve. The library it's trying to import from isn't published anywhere and it doesn't seem to be bundled with the `@trezor/connect` library. 

My trezor dependencies are:

```json
    "@trezor/connect": "^9.0.6",
    "@trezor/connect-web": "^9.0.6", 
```

The one way i found to fix it was to revert the `@trezor/connect-web` dependency, downgrading back to `9.0.3` and pinning it there as I noticed that the import in questions was added relatively recently.

The project is [unchained-wallets](https://github.com/unchained-capital/unchained-wallets). I'll post a link when I've got a branch up.

**Comment by mroz22** [comment]
You are right there are some missing referenced types in the package and we should probably fix that. But are you sure you don't want to include something like this in your tsconfig.json?
```
 "exclude": [
         "**/node_modules", // <- this?
    ],
``` 

I can confirm that I am seeing the same errors whithout this exclusion.

**Comment by bucko13** [comment]
I added that but was still running into the error presumably because imports are still pulling the impacted files in.

**Comment by mroz22** [comment]
I'd say this could be already fixed on the latest version, would you mind retesting?
