### ISSUE TITLE
TrezorSuite (Linux) Wayland compatibility

### ISSUE THREAD

**Issue by 0xNegnin** [trezor/trezor-suite#7594]
TrezorSuite on Linux does not work using Wayland. 

./TrezorSuite.AppImage gives "Missing X server or $Display. The platform failed to initialize. Exiting."
Even with xorg-xwayland this does not solve the issue.

TrezorSuite should have native wayland support as it's being adopted everywhere, xorg is deprecated.

**Comment by sime** [comment]
Hi @0xNegnin thanks for the report.

Within Trezor we have a mixed environment of some people running Wayland and others Xorg/X11 with no issues. Do you have `xwayland` installed?
