### ISSUE TITLE
ERC20 n.7 - Create carousel for importing multiple accounts

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#7595]
Currently, you can only import 1 asset during onboarding flow. If you want 2, you need to go through the flow twice. 

Enable importing multiple assets per flow. When you import more than 1, you will have them displayed in swipeable carousel. For this, you'll probably want to utilize react-native-gesture-handler API (https://docs.swmansion.com/react-native-gesture-handler/docs/api/gestures/gesture). 

**Acceptance criteria:** 

- [ ] More than one account can be imported during onboarding flow
- [ ] User can delete them during this flow using the bin icon button on asset card
- [ ] User can add labels to these coins directly on the card

**Nice to have:** 

- [ ] Simple animation for swiping gesture would be nice

Design: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=5935%3A39936&t=rEjuEaF74ePtPraS-4
Prototype: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=11081%3A84233&t=L7dO4D5Rri3BYmTi-1

**Comment by mnuky** [comment]
Closing, won't do
