### ISSUE TITLE
Migrate analytics logic to common package

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7596]
There is lot of analytics redux related logic in `package/suite`, move all these to `@suite-common/analytics`.

Output:
1. We are able to log events that are send somewhere. We need to solve how to distinguish between events from desktop and mobile.
2. Take different environment into account (we don't want to mix events from debug/dev/staging/production, how is this done in desktop Suite?)

**Comment by juriczech** [comment]
Tested on desktop by @tomasklim
