### ISSUE TITLE
connect 8 final deprecation

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#7600]
- deprecate npm package
- clearly state security updates policy in readme. cc @Hannsek till when? EOY? 
- put console.warn deprecation warning into iframe

**Comment by Hannsek** [comment]
June is fine, no?

**Comment by diwakergupta** [comment]
Hello, is there a firm deadline for when connect 8 will _stop_ working with Trezor devices?

**Comment by Hannsek** [comment]
Hi, not yet. But definitely this year.

**Comment by nvonpentz** [comment]
Did this already happen? I am trying to debug why the trezor integration is not working in Brave. Brave is still using trezor-connect 8.

**Comment by Hannsek** [comment]
Not yet. It is not brave who uses the connect but rather the application. Please keep in mind that Brave is not supported browser.

**Comment by nvonpentz** [comment]
Thanks. In this case, I think Brave is the one using connect, as it's integrated into the Brave Wallet

**Comment by Hannsek** [comment]
v8 already deprecated.
