### ISSUE TITLE
Dependencies: yup

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#7611]
Update `yup`

Issues:
- breaking changes https://github.com/jquense/yup/blob/master/CHANGELOG.md
<img width="1000" alt="Screenshot_2023-02-10_at_10 26 33" src="https://user-images.githubusercontent.com/33235762/218149762-ff7535bd-c7ba-4441-8454-7524125a9b90.png">

**Comment by peter-sanderson** [comment]
@tomasklim @Nodonisko What is the reason of the yup in our repository. I am quite fan of it, but its barely used in our codebase and we use TypeBox (https://github.com/sinclairzx81/typebox) as well.

Is there any plan to migrate?

**Comment by Nodonisko** [comment]
We use yup for all validations in mobile app, not sure about desktop
