### ISSUE TITLE
Transaction signing error: Cannot read slice out of bounds

### ISSUE THREAD

**Issue by AJPili** [trezor/trezor-suite#7619]
I transferred Litecoin to my Trezor wallet yesterday. Now, I am trying to send it to my Exodus wallet connected to my trezor, but it says "Transaction signing error: Cannot read slice out of bounds". I tried to input smaller amounts but still had the same error. 
I also tried to send it to my binance wallet, but still had the same error. 

I also sent Litecoin to my exodus wallet from binance and send it back to binance and it worked. I am only having problems when sending litecoin from trezor to any wallet I have. 

Trezor suite updated to the latest version. The Firmware of the device Trezor One is updated to the latest version as well. 
Hoping for your help on this. First time encountered this problem. 

![Error](https://user-images.githubusercontent.com/125168871/218290251-3d5f58da-61ae-41b3-9a06-f3f151fc75f3.PNG)

**Comment by Hannsek** [comment]
Hey, can you provide us with more info about the transactions? What kind of output are you trying to sign?

**Comment by AJPili** [comment]
Hello. Yes, I can provide more information.
I sent 1 LTC to my trezor wallet coming from my Binance wallet and it
reflected in the trezor suite. But when I try to send it back to Binance,
Exodus, and Litecoin Core it would not proceed. The error showing is
"Transaction signing error: Cannot read slice out of bounds". I tried so
many different amounts to send starting from 0.001 LTC but still, it won't
proceed.

Trezor Suite and Trezor Firmware are up to date with the latest version. I
also tried it on the web, but still nothing.
[image: image.png]
[image: image.png]
[image: image.png]

**Comment by Hannsek** [comment]
Can you provide us the actual transaction are you trying to sign? Or at least the xpub of the account? That would be very useful.

**Comment by AJPili** [comment]
[image: image.png]

**Comment by Hannsek** [comment]
We cannot see any of the images above. 
![image](https://user-images.githubusercontent.com/57008159/218465001-fb66eb76-6aa9-4249-b1a9-0fa4d1568b0f.png)

**Comment by AJPili** [comment]
This is the actual transaction. This address here is my Exodus wallet which
is paired with the Trezor.
[image: image.png]
[image: image.png]

**Comment by AJPili** [comment]
[image: LTC Transaction.PNG]

**Comment by AJPili** [comment]
Are the images now visible?

**Comment by Hannsek** [comment]
They are not. I think this is because of email reply…

**Comment by AJPili** [comment]
I sent the xpub address of LTC

**Comment by AJPili** [comment]
Here is my Litecoin (XPUB) key:

zpub6qv7A6LSqjiTC639U8pR2QnB9vfEA5xm9Rzzk1D3QWzqBtdwSm15g9cjtgLGyG7nsaSKnE3rCh5a1hPQDF2uKoVgtyiK64bKh8khBvTueNR

**Comment by Hannsek** [comment]
Deleted some comments for clarity.

**Comment by bosomt** [comment]
**QA OK**

tested by sending multiple txs from/to all types of accounts in Trezor Suite

**Info:**
 - Suite version: desktop 23.3.1 (8f0a5a67bd1cd0cf95724ee1468ee6ad70aead60)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.1 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.12.2 Universal (revision e2416bcec2072baf65dda2d3c2359cc7217753bc)
 - Transport: BridgeTransport 2.0.32
