### ISSUE TITLE
Label community translations

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7624]
Add new community translations
  - Italian (GiorgioHerbie, blablableble)
  - Hungarian (Mario Goomba)
    
- Add community label to these languages
  -  Italian
  - Hungarian
  - Japanese
  - Russian
  - Spanish
  - Chinese
  
  _Officially supported languages are currently Czech and English_

Final design: [Figma](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=41%3A230&mode=design&t=dzuknoYIDBLh5Kt5-1)

**Comment by jerechinsky** [comment]
@hynek-jina `blablableble` is actually @mroz22. Some translation credits were overwritten during a file structure migration. Italian translation was entirely done by @GiorgioHerbie

**Comment by hrudolf** [comment]
The _transactions_ label for this issue must be a typo, it should be _translations_ if I'm correct.

**Comment by matejkriz** [comment]
@Hermez-cz This comment should be addressed https://github.com/trezor/trezor-suite/pull/9151 and new community languages added.

**Comment by bosomt** [comment]
**QA OK**

one question is this final text that will be used for Trezor Suite regular users ?

`The Trezor community translated Czech, and we are thankful for their contributions. Ensure language consistency by referring to our official languages for verification.`

I would expect only info about  language and not about translation process, especially when this is first thing that user see when navigating to `Settings`



![Image](https://github.com/trezor/trezor-suite/assets/31506317/c8b4f253-00d6-44ba-af7c-545ad1394d6a)


**Info:**
 - Suite version: web 23.9.0 (c42e684d84addc647ce989be68ed8dd92d368698)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/116.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: 
 - Transport: N/A

**Comment by Hannsek** [comment]
Yes, plus it should be somehow collapsible. @Hermez-cz

**Comment by matejkriz** [comment]
> Yes, plus it should be somehow collapsible. @Hermez-cz

What exactly would you expect to be collapsible?

**Comment by Hannsek** [comment]
The text is imo too long to be there visible all the time.

**Comment by matejkriz** [comment]
> The text is imo too long to be there visible all the time.

Agree! Let's shorten the text then 😉 !

**Comment by sime** [comment]
> > The text is imo too long to be there visible all the time.
> 
> Agree! Let's shorten the text then 😉 !

As [previously mentioned](https://github.com/trezor/trezor-suite/pull/9151#issuecomment-1677118652) by @komret  

Will task @cavigneron (and @Hermez-cz) with this.

**Comment by Hermez-cz** [comment]
**Final & agreed solution:**

- The description text will only be shown when one of the community languages will be selected, that means it will be shown in that very language
- Final copy in English (only as source for translations, it will never be shown as english is an official language): A big thanks to the Trezor community for helping out with this translation. You can always refer to one of the official languages if needed.
- The input and the button will have the same width to stay aligned (✅ solved in #9233 )

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.9.0 (b22b5ca62ce5695546bf57d601e57a002ea18c8e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/116.0
 - OS: MacIntel
 - Screen: 2160x1350
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
