### ISSUE TITLE
Account birthdate discovery optimisation

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7633]
- Check blockbook for `X` first coinjoin receive addresses. Each address request with different tor identity.
- If your find a mined transaction on one of these addresses, use the smallest `block height` as the moment from which the classic coinjoin discovery will take place
- If no transaction is found, the account is loaded immediately
- Disable showing more than `X` receive addresses in the Suite

Initial idea is to set `X`= `1`, but it can be any number between 1 and 20 (actual number of discovered empty addresses on other accounts)

_Issue is related to: https://github.com/trezor/trezor-suite/issues/7390_
> discovery of [vpub5Yme8...Q3CTZM9](https://tbtc1.trezor.io/xpub/vpub5Yme8cvVDuECgS5vuY8rYyVMrnSvDaUwbDeKLNhh3BKZYe3fpKKapVQUFAEVpyBbwaUhZLeZLcwcoRMweSfRtFxB6MenWh3NweXrQ3CTZM9) (~600k blocks, ~540 txs) over Tor now takes approx. 43 minutes

**Comment by karliatto** [comment]
@hynek-jina the core functionality for this is done https://github.com/trezor/trezor-suite/pull/8026

But it assumes that the first address in the account is used, something that is not currently enforce. For instance the user could generate many address and do not use the first one. 
In order for this functionality to be working as expected and after talking with @marekrjpolak it looks like the best way would be to force user to use the first address of the account.

I guess some UI designs or communications should be taken into consideration.

**Comment by STew790** [comment]
**QA OK**
The account discovery of fresh CJ account was basically instantaneous. As mentioned here https://github.com/trezor/trezor-suite/issues/8084 I couldn't discover other address until I sent something to the first one.

**Info:**
 - Suite version: desktop 23.5.1 (3a3a0170978edcee49c99c17a428c4efeeba9dfc)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.5.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
