### ISSUE TITLE
Missing dots at the end of some sentences in "Did you know?" modal

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#7639]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/57008159/219014212-01b08804-6ad4-4a86-be84-0b98f5674448.png">

**Comment by hynek-jina** [comment]
I find only this occurrence and repair it in Crowdin. We don't add dot at the end of one sentence claim.

**Comment by Hannsek** [comment]
Nope, there are more of them. It does not make much sense not to have dots at the and of the sentence. @b-irving

**Comment by Hannsek** [comment]
+ to my knowledge, _Braiins_ is the company and _Braiins Pool_ is the pool, so _Braiins Pool_ is not operated by _Braiins Pool_.
