### ISSUE TITLE
ERC20 n.1 - Show tokens on Import Summary Screen

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7643]
PLEASE review this task if it works as expected:
When user scan ETH Receive Address we display also related ERC20 tokens 
We fetch only ERC20 tokens with FIAT value
We display ERC20 tokens with 0 balance

----

This issue should result into only one thing. Display ERC20 tokens as card on imports summary. Do NOT add them as accounts or anything just display them when importing ETH. No carousel just few card in column.

It may seems simple but this task is pretty important, because we will learn here how to work fetch tokens and we also need decide how we will solve some important things, for example add token icons, fiat rates for tokens etc...

Acceptance criteria:
1. When importing ETH you will see all available tokens as cards on Import Summary Screen.
2. No tokens are added as accounts as something, when you finish import you see only ETH account.

**Comment by bosomt** [comment]
**QA NOK**

1. Eth tokens are not displayed in tx history /only fees/



![Image](https://user-images.githubusercontent.com/31506317/222798287-68aa7bb7-61ab-4f7a-b34c-341fcbaf1f78.png)




![Image](https://user-images.githubusercontent.com/31506317/222798345-2fee94b3-8046-45c2-9262-5c28d2d7a0d7.png)


2.  When you open token tx in tx history app freezes for some time and then displays data that does not match desktop app

3. during import amount does not match desktop app

![Image](https://user-images.githubusercontent.com/31506317/222797772-790cccd5-2ad0-48e2-baeb-39097e156b21.png)

![Image](https://user-images.githubusercontent.com/31506317/222797472-ac143daa-4b71-412e-a0c6-334945e79019.png)



![Image](https://user-images.githubusercontent.com/31506317/222797932-2860dfb7-818d-4501-8f30-3bfd6aeadf43.png)



![Image](https://user-images.githubusercontent.com/31506317/222797729-8185ae79-e80f-4794-a6ef-391e4c0a4332.png)



4. multiple delete buttons are displayed during import, see previous screenshots



no idea how many of this issues is related to this change ;)

**Comment by PeKne** [comment]
PR #7887 fixes the problem **3. during import amount does not match desktop app**. The rest of the found problems are still in progress as planned subtasks from the ERC20 task https://github.com/trezor/trezor-suite/issues/7068.

**Comment by bosomt** [comment]
**QA OK**

tested on iPhone 11 app version dev 244
