### ISSUE TITLE
ERC20 n.3.1 - Token account detail screen

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7645]
User can access the token detail screen from asset overview where are tokens displayed in relation with ETH
Detail of the token contains:
- Name of the token
- Tag "Run on [label of Ethereum]"
- Portfolio balance in token value
- Portfolio balance in FIAT rate
- List of transactions

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=15674%3A73455&t=Y8K01RLwe0rTiroY-1

!!! Detail of the token does not display graph

**Comment by bosomt** [comment]
**QA OK**

tested on iPhone 11 app version dev 243
