### ISSUE TITLE
ERC20 n.4.1 - Display tokens on Dashboard and reflect them in assets values

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7646]
As a user I would like to see the ERC-20 tokens reflected in total balance on dashboard in order not to be confused that some assets are included and some not. 

To Do design: 
Display badge "+ token(s) next to ETH
Put badge to all tokens with coin they are related to

Acceptance criteria:
ERC-20 tokens balances are reflected on dashboard Total balances
ERC-20 tokens balances are reflected in assets on dashboard
[EDIT NEW]: ERC-20 tokens balances are reflected in Wallet switcher
When user has some token and clicks on ETH on dashboard, he gets the bottom sheet with selection of assets.

[Figma](https://www.figma.com/file/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?type=design&node-id=251-409&mode=design&t=oYqjjCX9bZBGJo5t-11)

**Comment by shenkys** [comment]
Research underway, back to "in progress" on 22.3.

**Comment by shenkys** [comment]
https://www.figma.com/file/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?type=design&node-id=251-409&mode=design&t=oYqjjCX9bZBGJo5t-11 

Figma

**Comment by STew790** [comment]
Waiting for merge on this one https://github.com/trezor/trezor-suite/pull/14234

**Comment by STew790** [comment]
**QA NOK**
Unfortunately, I see different value in the dashboard graph, below the graph and in the wallet switcher.

![image](https://github.com/user-attachments/assets/8d86d6b9-29eb-47e1-bcb0-61b7c1cc97a1)
![image](https://github.com/user-attachments/assets/6be26293-6ff5-45ae-afdb-d9d0fc5da4a3)

**Info**

24.9.1 b2926f161eb62381d1557e92175005cecf3dcaba

**Comment by Nodonisko** [comment]
Ready to be retested

**Comment by STew790** [comment]
**QA OK**
LGTM now, all balances are equal.

**Info:**
24.9.2 7a4ddc9
