### ISSUE TITLE
Setting page polishment

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7669]
Please polish the settings page according Figma and give the items right order.
Figma design: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=12341%3A93756&t=N4PQKTAUF7tg2DJL-1

Items in Settings page:
1. Application
- Localisation: Currency, Bitcoin units
- Color scheme
- Privacy&Security: Hide balance, Analytics tracking
- Advanced: User logs

2. Support
- Get help: FAQ, Contact support
- About

**Comment by juriczech** [comment]
Closing because it was implemented in https://github.com/trezor/trezor-suite/pull/7792
