### ISSUE TITLE
make Github changelog URL copyable

### ISSUE THREAD

**Issue by chaserene** [trezor/trezor-suite#7673]
when the Trezor Suite tries to display the changelog of a new version, a button appears that leads to the Github release. this URL can only be clicked, not copied, which means it will eventually open in an OS-default browser.

please make the URL copyable so that those who want to use a different browser or browser profile can easily access release details.

**Comment by sime** [comment]
Hi @chaserene 

Thanks for the report, can't say this will be prioritised soon. But will keep it in mind when this is revisited.

**Comment by chaserene** [comment]
@sime thank you.

just curious, if you want to revisit it later, why close it?
