### ISSUE TITLE
Adjust Suite for receiving ActionCancelled from Trezor in receive flow

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#7698]
With new receive flow on FW, user can cancel address confirmation if the address in Trezor and Suite are different. 

Right now, when Trezor sends `ActionCancelled` to Suite, Suite will freeze.

More info here: https://github.com/trezor/trezor-firmware/pull/2843#issuecomment-1441622398

**Comment by sime** [comment]
@Hannsek Typically we show a toast notification in Suite for such an event. Does that suffice here?

**Comment by Hannsek** [comment]
Yes, show the notification and close the window.

**Comment by matejkriz** [comment]
The new FW flow is not merged nor finalised, right? It seems a bit early to call this a bug in the Suite. But let's keep it here to double check it when it's ready in FW.

**Comment by Hannsek** [comment]
You can currently test this behaviour in master.

**Comment by sime** [comment]
I removed the bug label. Though this flow is unique to Model T right @Hannsek ?

**Comment by Hannsek** [comment]
Yes, for now. It won't be unique for T once we release T2B1.

**Comment by Hannsek** [comment]
I can see that when user cancels address verification on Trezor, it does what it meant to be, but Address verification error is triggered. Can we somehow change the error message? Or not displaying it at all? @marekrjpolak @sime 
![Image](https://user-images.githubusercontent.com/57008159/229718429-9334aa8c-c7a7-48cd-969d-8e419bfbc076.png)

**Comment by matejkriz** [comment]
> I can see that when user cancels address verification on Trezor, it does what it meant to be, but Address verification error is triggered. Can we somehow change the error message? Or not displaying it at all? @marekrjpolak @sime

I think it's global Suite behavior, I would propose to think about it globally and create a separate issue to change it everywhere if needed not as part of this issue.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.4.1 (3693c7aba5ee58758c4c0acedeb812eb6c5fecd5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.1 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision c21cf87c53f79ad8de9d0549bb714cd08f9b46a0)
 - Transport: BridgeTransport 2.0.32
