### ISSUE TITLE
T2B1 Firmware install

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#7701]
There will be separate binaries, so we need to support firmware update for new model in Suite (Connect). Prepare `releases.json` and so on. 

- [x] Discuss with firmware team the requirements.

**Comment by Hannsek** [comment]
[firmware-T2B1-2.6.1-b6bb87406.bin.zip](https://github.com/trezor/trezor-suite/files/11597325/firmware-T2B1-2.6.1-b6bb87406.bin.zip)


[firmware-T2B1-btconly-2.6.1-b6bb87406.bin.zip](https://github.com/trezor/trezor-suite/files/11597324/firmware-T2B1-btconly-2.6.1-b6bb87406.bin.zip)

**Comment by Hannsek** [comment]
Please ping me when you will be doing that. I will provide you with the newest builds.

**Comment by bosomt** [comment]
**QA OK**
