### ISSUE TITLE
CJ account preventing PC from sleep/hybernate

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#7708]
**Describe the bug**
After enabling the CJ account and going through one CJ my PC didn't go to sleep after 10 minutes and it is most probably because of this feature https://github.com/trezor/trezor-suite/issues/6053. This should prevent the PC from going to sleep but only when the CJ is active.

**Steps to reproduce:**
1. Set your PC to go to sleep as soon as it is possible
2. Enable CJ account
3. Start the CJ and wait for it to end
4. After the CJ ends the PC still won't go to sleep even though the CJ is not active

**Info:**
 - Suite version: desktop 23.2.2 (00fe136fa75bc04628abf858e09223170b5cf188)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.2 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: BridgeTransport 2.0.32

**Expected result:**
My PC is able to go to sleep when the CJ is not active.

**Actual result:**
My PC is not able to go to sleep when the CJ is not active.

**Comment by karliatto** [comment]
@STew790 do you mean after successful coinjoin round or after desired anonymity is reached?

**Comment by STew790** [comment]
@karliatto I'm gonna have to check, I actually don't remember now. I will let you know as soon as I know.

**Comment by matejkriz** [comment]
@STew790 is it only Linux issue or mac/win too?

**Comment by STew790** [comment]
I finally got CoinJoin finished on Linux and on Windows too. Unfortunately, it prevents the PC to go to sleep/hybernate in both cases. It stays on CJ successful modal and doesn't go to sleep/hybernate.

Happens on production as well as on latest dev.

**Info:**
 - Suite version: desktop 23.8.0 (d7d60309d441df224f1dd17ea78971ad26593edd)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.8.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
 
**Info:**
 - Suite version: desktop 23.7.2 (900989955cb6a56111d6827091f60ca059bfcf4f)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.7.2 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: Win32
 - Screen: 2560x1440
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.31

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
