### ISSUE TITLE
Implement analytics events

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7710]
https://www.notion.so/satoshilabs/da354c80a23a44a2814748968f701c5a?v=6a0a9e88bd04494db46c139336122d37

**Comment by mnuky** [comment]
@Nodonisko There is already tasks with subtasks: https://github.com/trezor/trezor-suite/issues/7141 - should we include this one as subtask?

**Comment by Nodonisko** [comment]
@mnuky yes
