### ISSUE TITLE
 Metamask + Trezor pop up window automatically closes

### ISSUE THREAD

**Issue by ss18ping** [trezor/trezor-suite#7712]
Team, please open this issue again - https://github.com/trezor/connect/issues/784
because the problem still exist.

**Comment by sime** [comment]
@ss18ping We are tracking this. But it is out of our hands. MetaMask still hasn't released a version w/ Trezor Connect v9. [Even though it was predicted for v10.25.0](https://github.com/trezor/connect/issues/784#issuecomment-1419364217).

**Comment by ss18ping** [comment]
> @ss18ping We are tracking this. But it is out of our hands. MetaMask still hasn't released a version w/ Trezor Connect v9. [Even though it was predicted for v10.25.0](https://github.com/trezor/connect/issues/784#issuecomment-1419364217).

Thank you for the answer! I'll try to talk with metamask team.
