### ISSUE TITLE
TransactionListItem from/to is switched

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7716]
The From address is actually my own address, which doesn’t seem right. When I drill down to the transaction detail, this address is shown as To.

Solution:
1. Remove from transaction list the tag with address. Instead of address put there type of transaction - Sent, Received, Self, Joined
2. On transaction detail show the addresses:
- if there is 1-2 input and 1-2 output - display them
- if there are more addresses on input / output - display always Destination address first
- if there is change address, it is marked as Change address
- if there are more than 2 addresses in input / output, add "Show more" and when user clicks on it, we display bottom sheet with all addresses

Transaction list design: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14639%3A55244&t=F44yeOKhwIn9z4cp-1

Detail of the transaction desing: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14621%3A54840&t=F44yeOKhwIn9z4cp-1

Differences from the design:
On click Show more display bottom sheet with all addresses - do not shorten them, just list all addresses
Do not implement the green arrow

**Comment by juriczech** [comment]
This issue needs more thought as there will be multiple targets and design is not ready for that. @mnuky is already solving this with UX team on how to tackle this.

**Comment by bosomt** [comment]
**QA NOK**

found this transaction with multiple outputs that says from null in tx detial

https://btc1.trezor.io/tx/d6c42e965f9e9a69b9eb1d48d09e787cae8020d86ed952548058c857f7bcfb7e


![image](https://user-images.githubusercontent.com/31506317/232778792-6cf54d76-9a72-4b93-a822-e8611c60110c.png)

 **QA OK**

 tested on dev version 233 on iPhone 11
