### ISSUE TITLE
Update coinjoin first block for discovery 

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7717]
Update blockhash for start of discovery on main net to the latest one before freeze...

**Comment by STew790** [comment]
**QA OK**
Discovery for CJ accounts was faster and feels faster.

**Info:**
 - Suite version: desktop 23.4.0 (f4dee18ecd17bcce530ae7837c5a34a7b922762a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision 557e29769b09dd3abd7b67f9b4fe3d380db9f6c9)
 - Transport: BridgeTransport 2.0.32
