### ISSUE TITLE
Notifications logic

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7721]
We already have notification redux logic in common. Now we need to somehow show notifications added to redux store. 

1. We will need some `NotificationRenderer` component that will be subscribed to redux state and show notifications in UI. This rerender will be placed somewhere in app root.

**Comment by mnuky** [comment]
the notifications work really weird, I did not receive any notification about Pending transaction but many notifications appeared randomly - see printscreen. Plus the design of the notification is broken

![Image](https://user-images.githubusercontent.com/84183817/224930698-0fd17cfd-e385-4a1b-baca-38cded6cd918.PNG)
![Image](https://user-images.githubusercontent.com/84183817/224930697-213524d5-9745-423e-bc14-006f667a4515.PNG)

**Comment by bosomt** [comment]
latest version 195 tested on iPhone 11
Guess it needs some work to do.


![Image](https://user-images.githubusercontent.com/31506317/225990340-8a90b247-4c16-4d65-862b-8686ba1eace7.PNG)

+ video https://photos.app.goo.gl/kcKRZHTWtCto31QF8

**Comment by bosomt** [comment]
Issue is still present in latest dev version of Lite version

f940792 - [develop] - feat(suite-native): internal notifications enabled (#9118)


https://github.com/trezor/trezor-suite/assets/31506317/5ac298de-d60f-4e22-9611-390aae8a28ac

xpub: https://ltc1.trezor.io/xpub/Mtub2tMaQUW5XRTWrqbwZKwJp35TgFx4zNtWCo1Yp3UDxv7CaPe48rPrZ23n8CMY4niYPmAUSXnqcP37NAsu7GXZa7se2Si2pdwsCgVT4oxmw7A

**Comment by bosomt** [comment]
**QA OK**

- iPhone 11
- 8ff3761 - [develop] 

i was not able to reproduce this issue in 10+ tries, same account used, different accounts used, different coins used,
as soon i will be able to reproduce issue i will create new issue

**Comment by juriczech** [comment]
@bosomt That's because the notifications were turned off in #9386 so you won't be able to reproduce. This is an ongoing issue that we should fix when we need notifications in the app. But I think Katka said it's not a high prio ATM

**Comment by karthik-ir** [comment]
Hi, 
Notification on any transaction change is very nice. Good to know that this is WIP. 
I'm currently looking for other 3rd party apps that can do this but no luck without compromising privacy. 
Is this coming as part of next release?

**Comment by matejkriz** [comment]
Closing this now, stale for too many months. Let's create a new issue once we want to reintroduce it.
