### ISSUE TITLE
Extend fee rate logic for non bitcoin coins

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#7729]
Currently fee logic in transaction detail parameters bottom sheet was hardcoded for bitcoin only. This will show Infinity for non bitcoin coins as there might not be `transaction.vsize` property or `transaction.details.size`.

For ethereum and tokens, we will need to display gas used, gas limit and gas price.

Screenshot: https://tppr.me/T5EQu

Steps to reproduce: Open eth based transaction and see parameters modal for fee rate.

Create formatter for formatting fee values. We want to replace this: ${getFeeRate(transaction)} ${getFeeUnits('bitcoin')}

**Comment by Nodonisko** [comment]
This should be solved in FeeFormatter
