### ISSUE TITLE
Set default desired anonymity level to 5

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7730]
We are conservative with anonymity calculation. Middleware will be changed to consider only taproot outputs for anonymity calculation, although Wasabi users will have randomised output scrip types (segwit/taproot)...
- We are aligning this default setting to Wasabi.

**Comment by matejkriz** [comment]
@hynek-jina maybe I'm nitpicking, but with the value on 5 we are currently in the yellow part of the slider. Should we also change the colors on the slider to have the default at the begining of green area?
<img width="492" alt="image" src="https://user-images.githubusercontent.com/3729633/222125634-a956cf9e-540c-4ce0-87f5-8bc6157b1fa6.png">

**Comment by hynek-jina** [comment]
Nice catch!
Yes, enhance it please if that is not complicated 🙏

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.4.0 (f4dee18ecd17bcce530ae7837c5a34a7b922762a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
