### ISSUE TITLE
Fiat value is incorrect

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7736]
**Steps to reproduce:**
1. Send some funds to coinjoin mainnet account
2. See
![Screenshot 2023-03-01 at 8 04 56](https://user-images.githubusercontent.com/26002916/222068173-362d20af-5853-4ea3-8bbf-392679337819.png)

Related fiat rate:
![Screenshot 2023-03-01 at 8 05 24](https://user-images.githubusercontent.com/26002916/222068219-a916a38d-b6fb-482d-a82f-ae535d1fb6ba.png)

**Info:**
 - Suite version: desktop 23.3.1 (8f0a5a67bd1cd0cf95724ee1468ee6ad70aead60)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.1 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.27

**Expected result:**
Correct number of fiat value

**Comment by STew790** [comment]
**QA OK**
FIAT looks correct.
![image](https://user-images.githubusercontent.com/48477147/222452936-358691e9-b173-450a-ab74-fb24f24c2e99.png)

**Info:**
 - Suite version: desktop 23.4.0 (f4dee18ecd17bcce530ae7837c5a34a7b922762a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision 557e29769b09dd3abd7b67f9b4fe3d380db9f6c9)
 - Transport: BridgeTransport 2.0.32
