### ISSUE TITLE
Put a modal on the Connect popup html with copy informing that old Connect version was shut down.

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#7737]
This application was using Trezor Connect v5, which has been discontinued. To continue using Trezor with the application, please contact the application developer directly.

**Comment by bosomt** [comment]
https://www.strip4bit.com/

https://connect.trezor.io/7/popup.html#loading


This application was using Trezor Connect v7, which has been discontinued. To continue using Trezor with the application, please contact the application developer directly.
