### ISSUE TITLE
Suspiciously low `max mining fee` while running coinjoin

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7738]
**Describe the bug**
While testing coinjoin on mainnet I'm confirming default value on Trezor which seem to be hardcoded to `2 sat/vB`.
Or the estimate is quite underrated.
Current mempool conditions are following:
![Screenshot 2023-03-01 at 8 11 02](https://user-images.githubusercontent.com/26002916/222069083-6a36eaa9-5a30-4a31-8f12-9ec8e74a578a.png)

And that is probably the reason why I can't access any coinjoin round
[Recent coinjoin](https://mempool.space/tx/e56addddef51d688964366c0c100207a8e1c7fd675d685691fb634a69ad045e0) had mining feel = `3,07 sat/vB`

**Info:**
 - Suite version: desktop 23.3.1 (8f0a5a67bd1cd0cf95724ee1468ee6ad70aead60)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.1 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.27

**Comment by matejkriz** [comment]
Our[ hardcoded default value is 1 sat/vB](https://github.com/trezor/trezor-suite/blob/develop/packages/coinjoin/src/constants.ts/#L46) so I believe 2 sat/vB come from coordinator as median value, but the problem is that we use median value as max 🤔

**Comment by hynek-jina** [comment]
Ok, so we should either multiply it with some constant or use some higher value, right?

**Comment by matejkriz** [comment]
Multiply or use the value from blockbook that we use in send form, but that makes less sense to me. Ok keep it as it is because it's an economic variant.

**Comment by sime** [comment]
Agreed offline to multiply the max mining fee by 2.5

**Comment by matejkriz** [comment]
Also please delete [`DEFAULT_MAX_MINING_FEE`](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/services/coinjoin/config.ts/#L143) as it is no more used.

**Comment by komret** [comment]
> Also please delete [`DEFAULT_MAX_MINING_FEE`](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/services/coinjoin/config.ts/#L143) as it is no more used.

It is meant to be used in custom setup. But we might use the dynamic value there as well.

**Comment by komret** [comment]
Explanation:
Coordinator provides fee rate medians for 1 month, 1 week and 1 day of previous coinjoin rounds. Previously, we used the **weekly** value as max mining fee, effectively preventing the user to participate in any round with fee higher than the median value (about half of them).
With this change in place, we calculate max fee by multiplying the **weekly** median by a modifier of **2.5**.
We can tweak the calculation further by using other time frame for the median value or changing the modifier.

**Comment by matejkriz** [comment]
followup issue https://github.com/trezor/trezor-suite/issues/7742

**Comment by hynek-jina** [comment]
**QA OK**
