### ISSUE TITLE
Cannot run translations command in CI

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#774]
ttm is undefined

![image](https://user-images.githubusercontent.com/3112191/68387405-8483b880-015e-11ea-99d1-74e0b85cfff6.png)

**Comment by mroz22** [comment]
https://github.com/trezor/trezor-suite/pull/756/commits/030f31189ea9ffec62ab0bd80982a446190d1e99 added a little dirty workaround here
