### ISSUE TITLE
Warn user about low `max mining fee`

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7742]
Coinjoin user confirms `max mining fee` on trezor during coinjoin start.

This amount defines maximum mining fee that is user willing to pay. Generally real mining fee will be lower. 

**This causes problem because:**

Some users might decide to set this `max mining fee` quite low which results in no participation in coinjoin or at least in upcoming period.

*This can happen even without manual user input when the conditions on market change dramatically.*

### Desired outcome:

Warn user that his max mining fee is bit low. Explain what it means.. or maybe navigate him to restart with different conditions?

**Comment by matejkriz** [comment]
Another possible but more complex solution would be to separate the max value confirmed on device from the desired value (always lower or equal to max). Desired value could be in form of period of time (Hours/Days/Weeks) from what to take the median value. The benefit of this solution is that it could reflect the changing conditions on the market but still stay economical by not participating in rounds with higher fees than median.

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
