### ISSUE TITLE
Connect popup methods and attributes to be tracked

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#7755]
Methods and attributes to be tracked.

* `getPublicKey`: `coin`(once per coin)
* `getAddress`: `coin`
* `getAccountInfo`: `coin`, `useCardanoDerivation` (when true)
* `signTranstions`: `coin`
* `pushTransaction`: `coin`
* `composeTransaction: `coin`
* `signMessage`: `coin`
* `verifyMessage`: `coin`
* `ethereumGetPublicKey`
* `ethereumGetAddress`
* `ethereumSignTransaction`: `chainId`, transaction type e.g. `EthereumTransactionEIP1559` or `EthereumSignTransaction`
* `ethereumSignMessage`
* `ethereumSignTypedData`
* `cardanoGetPublicKey`
* `cardanoGetAddress`
* `cardanoGetNativeScriptHash`
* `cardanoSignTransaction`
* `requestLogin`
* `cipherKeyValue`
* ~~`applySettings`~~
* ~~`applyFlags`~~
* ~~`backupDevice`~~
* ~~`changePin`~~
* ~~`firmwareUpdate`~~
* ~~`getFeatures`~~
* ~~`recoveryDevice`~~
* ~~`resetDevice`~~
* ~~`wipeDevice`~~

**Comment by Hannsek** [comment]
Maybe we don't have to add last 9?

**Comment by Hannsek** [comment]
I think this is done, right? @tomasklim @kolomaznikt

**Comment by tomasklim** [comment]
I think so
