### ISSUE TITLE
Ethereum negative balance

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#7766]
It seems that problem is etiher in wrong response of `TrezorConnect.blockchainGetAccountBalanceHistory` (so probably blockbook response) or our function `addBalanceForAccountMovementHistory` is not working well.

JSON with plain response of `TrezorConnect.blockchainGetAccountBalanceHistory` is here https://pastebin.com/P6HBEw2U You can use JSON as fixture in unit test for `addBalanceForAccountMovementHistory` while identifying problem.

Result of our function `addBalanceForAccountMovementHistory` for that JSON:

```json
[
    { "cryptoBalance": "0.06427487", "time": 1493715600 },
    { "cryptoBalance": "0.00281919", "time": 1493719200 },
    { "cryptoBalance": "0", "time": 1493809200 },
    { "cryptoBalance": "0.00124351", "time": 1494936000 },
    { "cryptoBalance": "0", "time": 1495454400 },
    { "cryptoBalance": "0.01534548", "time": 1499781600 },
    { "cryptoBalance": "0", "time": 1502985600 },
    { "cryptoBalance": "0.007", "time": 1527098400 },
    { "cryptoBalance": "0.006744738432", "time": 1527138000 },
    { "cryptoBalance": "0", "time": 1527156000 },
    { "cryptoBalance": "0.002", "time": 1527170400 },
    { "cryptoBalance": "0.001747999", "time": 1527177600 },
    { "cryptoBalance": "0.001639399", "time": 1527206400 },
    { "cryptoBalance": "0", "time": 1527260400 },
    { "cryptoBalance": "0", "time": 1537351200 },
    { "cryptoBalance": "0", "time": 1565298000 },
    { "cryptoBalance": "0", "time": 1569279600 },
    { "cryptoBalance": "0", "time": 1570719600 },
    { "cryptoBalance": "0", "time": 1571418000 },
    { "cryptoBalance": "0", "time": 1577091600 },
    { "cryptoBalance": "0", "time": 1585645200 },
    { "cryptoBalance": "0", "time": 1612551600 },
    { "cryptoBalance": "0", "time": 1619305200 },
    { "cryptoBalance": "0", "time": 1626278400 },
    { "cryptoBalance": "-0.231513790010713751", "time": 1626282000 },
    { "cryptoBalance": "-0.231513790010713751", "time": 1639551600 },
    { "cryptoBalance": "-0.230513790010713751", "time": 1652306400 },
    { "cryptoBalance": "-0.231513790010713751", "time": 1652425200 },
    { "cryptoBalance": "-0.231513790010713751", "time": 1674133200 }
]
```

You can see that at time `1626282000` something went wrong.

In case if you won't find any issue in `addBalanceForAccountMovementHistory` it's probably problem of blockbook. In that case contact @martinboehm 

Public key for that ETH account: `0x73d0385F4d8E00C5e6504C6030F47BF6212736A8`

![Image](https://user-images.githubusercontent.com/5837757/222907177-f6a5d0c5-15c5-4fa9-9af9-28b54043c9ab.png)

**Comment by tomasklim** [comment]
Maybe its related to this https://satoshilabs.slack.com/archives/C02F11Q9UCR/p1677599542546699 but that one is already fixed.
