### ISSUE TITLE
Coinjoin for T1

### ISSUE THREAD

**Issue by andrewkozlik** [trezor/trezor-suite#7777]
Starting with firmware version 1.12.1 Trezor Model One will support coinjoin. We should:
- Enable the coinjoin account for Trezor Model One firmware versions 1.12.1 and newer.
- If the user has an older firmware version than 1.12.1 and wants to use coinjoin, then recommend updating to a newer version. (I assume we already do this for Model T. If not, then disregard.)
- Update any photos of TT with the corresponding photos of T1, namely in the "Do not disconnect" modal.
- Consider that T1 uses the PIN entry modal. Could it interfere with the coinjoin modal?

Note that we don't have a date set for the release of T1 coinjoin in Suite, but we want QA to start testing soon.

**Comment by hynek-jina** [comment]
Please put it behind feature flag

**Comment by hynek-jina** [comment]
Visual to be updated for T1 only in signing modal:
https://www.notion.so/satoshilabs/Prepare-coinjoin-UI-for-T1-and-Safe-3-de4c814bbe95475f931886f8d7b2da0e

**Comment by bosomt** [comment]
running and signing txs
but even i sent 4 transactions i have not seen any modal in Trezor Suite during transaction signing
See video

https://youtu.be/zTB0-GCJwbw


**Info:**
 - Suite version: desktop 23.6.1 (bf8716e07436e942dd86517475e44ba5e6f4b10c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.6.1 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.12.1 Universal (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="635" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/17c20b3d-ac6b-4656-a977-6f5e0e0e96f7">

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 23.7.0 (5d03fad86692c6ff189e861cb548742123ba641b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.7.0 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.12.1 Bitcoin-only (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33


<img width="379" alt="Screenshot 2023-06-09 at 11 21 21" src="https://github.com/trezor/trezor-suite/assets/31506317/99ab9f91-2efa-40aa-acfd-2c7422cf69c5">
