### ISSUE TITLE
Unable to bump fee of ETH send transaction if BTC Satoshi units are enabled

### ISSUE THREAD

**Issue by etam** [trezor/trezor-suite#7779]
**Describe the bug**

Bump fee dialog says "Not enough funds", which is clearly not true, because I have plenty ETH left on this account.

**Info:**

-   Suite Version: 22.8.x to nowdays (23.4.0) (caused by Satoshi unit feature)

**How to reproduce**

1. send transaction with low gas fee
2. enable BTC account -> switch to Satoshi units

**Expected behavior**

Bump the fee, Ethereum is not affected by Bitcoin settings

**Workaround**
Disable Satoshi units on BTC

**Screenshots**
![Screenshot_20230306_123653](https://user-images.githubusercontent.com/220752/223099936-5bdf5884-b5c2-42d4-a22e-42dd46c17fe4.png)

**Comment by etam** [comment]
btw, the transaction in question has been confirmed, so I cannot check it on my end again.

**Comment by bosomt** [comment]
**QA NOK**

i was able to reproduce issue, sent two transactions between  two accounts and none of them is bump-able even there is enough ETH on both accounts.

edit attached logs, maybe it helps: 
[Archive 2.zip](https://github.com/trezor/trezor-suite/files/10902876/Archive.2.zip)


<img width="640" alt="Screenshot 2023-03-06 at 22 14 19" src="https://user-images.githubusercontent.com/31506317/223232707-b0d04f4a-940a-4a1b-baf4-8eed9d056436.png">

<img width="625" alt="Screenshot 2023-03-06 at 22 13 55" src="https://user-images.githubusercontent.com/31506317/223232789-48ccc410-6dac-4949-a260-783b3a794589.png">

<img width="245" alt="Screenshot 2023-03-06 at 22 14 07" src="https://user-images.githubusercontent.com/31506317/223232783-d60014a6-c4a9-4f13-bf19-e1778a5c56fc.png">

tx:
0x493b8d88f8106b15b101896a2af58183e56fff0e768dd6b5269dfbea240d09fa
0x1f3c2bc7c8465e8613b33000395777e72fd2fd1fdae171485e34fbd44f1c7166
**Info:**
 - Suite version: desktop 23.4.0 (f4dee18ecd17bcce530ae7837c5a34a7b922762a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.1 Universal (revision 24bb4016388fca4b998285b95dcd408f4ed0bff6)
 - Transport: BridgeTransport 2.0.32

**Comment by matejkriz** [comment]
maybe duplicate https://github.com/trezor/trezor-suite/issues/7214

**Comment by tomasklim** [comment]
<img width="717" alt="Screenshot 2022-12-20 at 15 34 01" src="https://user-images.githubusercontent.com/33235762/223727784-4403d8fd-f6f9-4e7f-aca1-58ad8235529e.png">
<img width="361" alt="Screenshot 2022-12-20 at 15 34 08" src="https://user-images.githubusercontent.com/33235762/223727791-10ebe727-c542-490a-90af-cd504373460f.png">

![Screenshot 2022-12-20 at 15 34 14](https://user-images.githubusercontent.com/33235762/223727794-5e91a1f6-57dc-40bd-b425-0251e7774734.png)

I encountered this in December

**Comment by hynek-jina** [comment]
This issues seems to be cased by sats unit from bitcoin account.

**Comment by bosomt** [comment]
Yes its cause by sats :)

Sats disabled:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/31506317/224211176-eacbb99b-0bbe-4583-a988-e71432e5012d.png">

Sats enabled:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/31506317/224211234-c1cefc22-81a4-453a-a1fc-aff2111a4e0d.png">

**Comment by ngrigoriev** [comment]
Indeed, this helps (Settings -> Application -> Bitcoin units -> Bitcoin), I was able to replace the transaction that was stuck because of low gas price originally set.

**Comment by bosomt** [comment]
**QA OK**

I was able to bump Erc20 tx 

**Info:**
 - Suite version: web 23.4.0 (3a16b21ce78c7cdc70b946e95092f388dc4af13e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision 305b7fe84d802db7f0826d07a222a886f73732f0)
 - Transport: WebUsbTransport


<img width="567" alt="Screenshot 2023-03-31 at 13 28 55" src="https://user-images.githubusercontent.com/31506317/229108842-8fde639d-8c13-4b5f-a2f3-47a21c31b559.png">

<img width="357" alt="Screenshot 2023-03-31 at 13 29 06" src="https://user-images.githubusercontent.com/31506317/229108838-57056599-a7b9-4a2a-8381-d8093032fe3d.png">

**Comment by bosomt** [comment]
No idea why but now i see two txs ;)

<img width="637" alt="image" src="https://user-images.githubusercontent.com/31506317/229109278-cb84f420-3eae-48cd-b560-62e000d7f66f.png">

https://eth1.trezor.io/tx/0xaacb63865a630e4ba69e0b57c575b80274ce48ca0165afc09113d4b8f33bb9bf
https://eth1.trezor.io/tx/0xded7a705dc23ecc8badd159b0bde071280de331c4a571a460ae25ccca8065d62

**Comment by Hannsek** [comment]
Same amount but different fees. 😳
