### ISSUE TITLE
Coinjoin account reaching target anonymity in the last session round - wrong modal shown

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#7785]
Follow-up to #7680

Coinjoin session ends with either success modal when target anonymity is reached or the "More rounds needed" modal when the last permitted round ends. However, when anonymity is reached in the last possible round, "More rounds needed" modal is shown because the check for `maxRounds` happens before the check for anonymity. One possible solution is to introduce a new phase of coinjoin evaluation which would last until the latest transaction is fetched (if we can be sure those data are up to date). Or we could change the text of the "More round needed" modal.

![Screenshot 2023-03-06 at 19 22 14](https://user-images.githubusercontent.com/42465546/223197602-fb51958d-b353-454d-a2fb-53ce249c3070.png)

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
