### ISSUE TITLE
Manifest v3 support w/ Service worker

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#7803]
Next iteration of #6458

Manifest v3 support is technical done. Though service worker support can be improved: Create a proxy package that will pass calls from popup context to service worker context

Reference: https://github.com/trezor/trezor-suite/issues/6458#issuecomment-1458203347

**Comment by mroz22** [comment]
It will work like this

### Phase 1
1. npm package detects that it can't inject iframe (it is running in service worker)
2. npm package opens popup with some query string `?extended` or so. maybe query string will not be needed, maybe it will be used only for testing to enforce one kind of behavior
3. popup sees that there is no iframe yet, so it creates iframe in its body.
4. npm package already knows that iframe is not going to exist in host, so it looks for iframe in popup
5. communication iframe-popup and host-iframe should now be established.

### Phase 2
- we will open connect API either from suite-desktop or dedicated connect webextension. if one of these is available, connect will prioritize them. 

idea map https://miro.com/app/board/uXjVPF3uHPI=/

**Comment by cleytonb** [comment]
Hi,

Any news on this? I've been waiting to build a new password manager, but without this, it's not possible.

```javascript
// service-worker.js

// throws 'Uncaught (in promise) ReferenceError: window is not defined'
import TrezorConnect from "@trezor/connect-web";

TrezorConnect.init({
    manifest: {
        email: "info@trezor.io",
        appUrl: "trezor-password-manager",
    }
});

// throws 'Uncaught Error: This package is not suitable to work with browser. Use @trezor/connect-web package instead'
import TrezorConnect from "@trezor/connect";

TrezorConnect.init({
    manifest: {
        email: "info@trezor.io",
        appUrl: "trezor-password-manager",
    }
});
```

**Comment by sime** [comment]
@cleytonb You are right about that, but some very early development for MV3 support is being developed https://github.com/trezor/trezor-suite/pull/9525

**Comment by Hannsek** [comment]
@cleytonb new package is out. See [here](https://www.npmjs.com/package/@trezor/connect-webextension).
