### ISSUE TITLE
Received/sent arrows display incorrectly

### ISSUE THREAD

**Issue by MatthewDavid1984** [trezor/trezor-suite#7806]
**Describe the bug**
The recv/sent arrows display on top of the date or "pending transactions" for pending and done txs. 22.11.1 Linux, only the pending tx arrows do this, done txs show as normal. Checked BTC and ETH.

**Steps to reproduce:**
1. Open suite 
2. Navigate to Accounts and select an account with transaction history, and preferably pending transactions
3. Scroll through the tx history and observe the received/sent arrows to the left of each transaction's info

**Info:**
 - Suite version: desktop 23.3.1 (76c3579c21da2debfcc2f2124875974f201e84f1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.1 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.27

**Expected result:**
The arrows should not display over/through the date or "pending transactions" when they align.

**Actual result:**
The recv/sent arrows display on top of the date or "pending transactions" for pending and done txs. 22.11.1 Linux, only the pending tx arrows do this, done txs show as normal. Checked BTC and ETH.

**Screenshots:**
![Screenshot from 2023-03-08 15-21-42](https://user-images.githubusercontent.com/121948710/223943383-9caeaea5-30f1-4162-bea6-e9d9e54a7852.png)
![Screenshot from 2023-03-08 15-21-15](https://user-images.githubusercontent.com/121948710/223943582-f80c810f-e33c-47e5-868b-a8e68b0149e1.png)

**Note(s):**

**Comment by tomasklim** [comment]
Fixed by  #7784
