### ISSUE TITLE
Enable T1 in Suite for coinjoin testing

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7807]
After few more successful tests witch Trezor model T we would like to extend testing on model One as well.

Please prepare some solution so we can use model one, but still being able to release version for model T only.
Probably keep it separately behind debug mode...

Related to: https://github.com/trezor/trezor-suite/issues/7777

**Comment by matejkriz** [comment]
It's not only Suite UI condition 🤔  
<img width="377" alt="image" src="https://user-images.githubusercontent.com/3729633/225391447-609c9bf8-4c95-4731-b9ad-2c8a441ead21.png">

**Comment by hynek-jina** [comment]
@matejkriz Do you use the latest FW?
@andrewkozlik Can you help please? 🙏

**Comment by andrewkozlik** [comment]
This does not look like a firmware-related problem. I assume Suite whitelists or blacklists some set of firmware versions for coinjoin accounts. @szymonlesisz?

**Comment by andrewkozlik** [comment]
Could it be this?
https://github.com/trezor/trezor-suite/blob/1c4c12d8d0b0cc76145c20a0b2475b21fc7bd745/packages/connect/src/data/config.ts#L186

**Comment by matejkriz** [comment]
@andrewkozlik thanks, that config I was aware of, but the problem was unlockPath method. 

@hynek-jina sorry, it wasn't 15 minutes task, but 25 🙉

**Comment by bosomt** [comment]
**QA OK**

debug off - no cj available
debug on - cj available

i was able to add test and btc accounts and i was able to start cj

**Info:**
 - Suite version: desktop 23.4.0 (7e8281dfde9ded5ad99ec0a1cd605c701c4865f9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.12.1 Bitcoin-only (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.32
