### ISSUE TITLE
Unable to bump fee of ETH ERC-20 send transactions

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7808]
**Describe the bug**

Bump fee dialog says "Not enough funds", which is clearly not true, because I have plenty ETH left on this account.

**Info:**

-   Suite Version: 22.7.0 (and probably before) -> nowdays (23.4.0)

**How to reproduce**

1. send ERC-20 transaction with low gas fee
2. bump fee

**Expected behavior**

Transaction fee can be bumped.

![Screenshot 2022-12-20 at 15 34 14](https://user-images.githubusercontent.com/33235762/223727794-5e91a1f6-57dc-40bd-b425-0251e7774734.png)
<img width="361" alt="Screenshot 2022-12-20 at 15 34 08" src="https://user-images.githubusercontent.com/33235762/223727791-10ebe727-c542-490a-90af-cd504373460f.png">

_Originally posted by @tomasklim in https://github.com/trezor/trezor-suite/issues/7779#issuecomment-1460170983_

**Comment by tomasklim** [comment]
maybe duplicate https://github.com/trezor/trezor-suite/issues/7214

**Comment by tomasklim** [comment]
![Screenshot 2023-03-28 at 15 21 26](https://user-images.githubusercontent.com/33235762/228269379-3ec9655d-30be-4dd7-8adb-e919e6265b13.png)
token info not propagated to bump fee form

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.4.0 (f169f0f32c939b2dea222e818a69038ba63ff8be)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.5.4 Universal (revision 305b7fe84d802db7f0826d07a222a886f73732f0)
 - Transport: BridgeTransport 2.0.32
