### ISSUE TITLE
Components 2.0: Buttons

### ISSUE THREAD

**Issue by keip** [trezor/trezor-suite#781]
## Props:
`variant` primary/secondary/danger **Changed**
`icon` string
`isDisabled` boolean
`isLoading` boolean
`align` center/left/right

## New props
`size` small/medium/large
`inlineWidth` boolean

## Removed props
~~isTransparent~~
~~isInverse~~
~~fullWidth~~

> There is no onClick event ...

the onClick event is extended from React.ButtonHTMLAttributes

**Comment by vladimirvolek** [comment]
There is no onClick event ...
