### ISSUE TITLE
Progress bar in CJ shows incorrect progress

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#7811]
**Describe the bug**
Progress bar in CJ shows incorrect progress after gaining some anonymity on some of my coins. When I gain at least some (2) level of anonymity on at least some of my coins, the progress bar should show me some progress since I actually gained something from the Coinjoin that I attended (was part of) and it was successful. Now it only shows progress when I have gained desired anonymity on at least some of my coins.

**Steps to reproduce:**
1. Attend CJ round that is successful
2. Gain some anonymity on some of your coins
3. Observe the progress bar (circle)

**Info:**
 - Suite version: desktop 23.4.0 (dcdb847cd13fc9adf2d6f74ad320f229ad116fb4)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision e2416bcec2072baf65dda2d3c2359cc7217753bc)
 - Transport: BridgeTransport 2.0.32

**Expected result:**
I should be shown that I gained at least some progress when at least some of my coins gained at least some level (2) of anonymity.

**Actual result:**
I am shown a progress only when some of my coins gained my desired level of anonymity.

**Screenshots:**
When I set my desired anonymity to 5 and some of my coins are already on anonymity 2:
![image](https://user-images.githubusercontent.com/48477147/224062124-2d5f5500-cdca-4066-82f1-c0df1f8391df.png)
When I set my desired anonymity to 2 and some of my coins are on anonymity 2:
![image](https://user-images.githubusercontent.com/48477147/224062311-af18d522-89a3-4da2-abe1-bb2c4b78420c.png)

**Comment by sime** [comment]
Is this 'easily' reproducible?

**Comment by STew790** [comment]
If you have some private coins it is. All you have to do is set the anonymity level higher then the already private coins have. I talked to @hynek-jina and he said that user should be able to see the progress when already some of you coins have at least some anonymity level.

**Comment by sime** [comment]
Currently, I am unable to. I have coins at level 1, 2 and 4. And setting the anonymity level from 2-4 shows the same.
![Screenshot 2023-03-16 at 10 23 50](https://user-images.githubusercontent.com/216917/225572633-2199a579-14c0-40aa-b52a-4fac81047a56.png)

**Comment by STew790** [comment]
That is probably correct, right @hynek-jina ? Because that shows that you already have some coins on the level 4 but still have the same amount on 2 and 1 (not sure about this though). Nonetheless, this is about when you select anon level 5 (or above) you should also be able to see the progress.

**Comment by hynek-jina** [comment]
Logic of the progress calculation is here: https://github.com/trezor/trezor-suite/issues/7108
Basically we have two informations
- binary `private`/`not private` coins → tells you what you can already spend
- smooth progress circle taking into account even small privacy improvements..

_I will try to reproduce the bug as well_

**Comment by hynek-jina** [comment]
This bug is quite annoying, because it looks like you get no progress...

**Comment by STew790** [comment]
**QA OK**
Progress showing correctly on the progress wheel.
![image](https://user-images.githubusercontent.com/48477147/235883704-29fc88be-4ab3-44b5-bf99-7edb02fc248c.png)

**Info:**
 - Suite version: desktop 23.5.1 (3a3a0170978edcee49c99c17a428c4efeeba9dfc)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.5.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
