### ISSUE TITLE
Amounts on the graph are cropped from the bottom

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7814]
Balances on the graph are cropped - take a look on the printscreen:

![Image](https://user-images.githubusercontent.com/84183817/224295378-738f27bf-38b7-45e3-84ae-bd73075fb235.PNG)

**Comment by bosomt** [comment]
**QA OK**

iPhone and Android versions are not cropped anymore. 🎉

**Comment by mnuky** [comment]
cropping from the bottom is fixed, but cropping from the side of the graph is broken now :/

![Image](https://user-images.githubusercontent.com/84183817/227019909-e76d2bb3-c264-491d-bef2-eb1489e5590b.PNG)

**Comment by PeKne** [comment]
@mnuky I've checked the implementation and I believe this is another problem. ATM we are not checking the length of the label and if it's too long it overflows. I will create another issue for that: https://github.com/trezor/trezor-suite/issues/7910

**Comment by mnuky** [comment]
ok, it is weird because we've already fixed this issue in the past
