### ISSUE TITLE
ERC20 n.3.2 - Token account detail screen graph

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#7839]
The `AccountDetailGraph` component needs to be adjusted to support ERC20 tokens. The blockbook method `getFiatRatesForTimestamps` accepts ERC20 token contract address as a parameter.

Acceptance criteria:
- on the token detail screen is shown a graph displaying the historical price of a specific token
- the change of token graph timeframe emits even to the analytics server

**Comment by STew790** [comment]
**QA OK**
![image](https://github.com/user-attachments/assets/ac2faaa4-2de8-49d7-8048-181b1f0348df)

**Info:**

Mobile Suite Version: 24.9.1 https://github.com/trezor/trezor-suite/commit/b415aa2c5f4d8c5c767055211d4e22c85865c05c
OS: Android
