### ISSUE TITLE
Make whole coinjoin state clickable

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7852]
**Context**
Suite displays in top bar state of running coinjoin. If user navigates to different account this bar works as a shortcut to running coinjoin page. There might be more of them in the same time but it is quite edge case. 
Proposal here is to only make whole bar clickable (not only small `view` button) and change the backgrounds on hover.

**Design:**
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/26002916/225551993-b93f9bfc-5dcd-4e14-9e57-ac3f99c0e17b.png">

**Figma**
[Exploring coinjoin](https://www.figma.com/file/PrfGpe3axW0BBgf0UCzFyO/Exploring-CoinJoin?node-id=1287%3A19315&t=HOuQYdJJVFjaP9R6-1)

**Comment by bosomt** [comment]
**QA OK**

@hynek-jina do we still need `View` "button" ?



https://github.com/trezor/trezor-suite/assets/31506317/aa8e643c-05a1-47c9-b607-a35bd156a522




**Info:**
 - Suite version: desktop 23.11.0 (40b035b2be45a4792adc9fb8373fdacff7b89bb3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.11.0 Chrome/116.0.5845.188 Electron/26.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Comment by hynek-jina** [comment]
Good question,
Let's leave it there.. confirmed with @Hermez-cz
