### ISSUE TITLE
ERC-20 transactions missing on ETH export file

### ISSUE THREAD

**Issue by rulbricht** [trezor/trezor-suite#7864]
**Describe the bug**
A regression has occurred whereby ERC-20 transactions no longer appear on the export file when exporting ETH transactions.

**Info:**

-   Remembered Wallet: no
-   Suite Version: web 23.3.2
-   Browser: Google Chrome, Version 110.0.5481.177 (Official Build) (arm64)
-   OS: macOS Monterey, 12.2.1 (21D62)
-   Bridge: version
-   Firmware Version: Trezor Model One, firmware v1.11.2

**How to reproduce**

1. Go to 'ETH wallet' (must have executed transactions involving ERC-20 tokens)
1. Click on '...' to the right of the 'Transactions' list
1. Click 'Export as CSV'
1. Observe that CSV includes normal ETH transactions but omits all ERC-20 related transactions

**Expected behavior**
ERC-20 related transactions should be present

**Comment by bosomt** [comment]
**QA NOK**

i can confirm this behavior, missing erc20 transactions in tx history export.

**Info:**
 - Suite version: desktop 23.4.0 (7e8281dfde9ded5ad99ec0a1cd605c701c4865f9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision 2b74d103dbc9e491c2e0b959ca37277218440884)
 - Transport: BridgeTransport 2.0.32

**Comment by sime** [comment]
@rulbricht Thanks for the report. We are taking a look.
Please don't spam unrelated issues, it doesn't help.

**Comment by sime** [comment]
I don't believe this is a regression, which version did you have recently?

**Comment by tomasklim** [comment]
It's caused by missing token's address. There was probably a change in Blockbook which changed `address` to `contract` param

**Comment by sime** [comment]
@tomasklim Is it related to this? https://github.com/trezor/trezor-suite/issues/7866

**Comment by tomasklim** [comment]
I dont think so. It's caused by wrong attribute. In the past, we got token `contract` in `address` attribute from Blockbook, now it is in `contract` attribute.

**Comment by tomasklim** [comment]
Related to #7808

**Comment by bosomt** [comment]
**QA OK**

```
Ethereum_1_20230411T120223.csv
Ethereum_1_20230411T120143.pdf
```

export files contain ERC20 transactions

**Info:**
 - Suite version: desktop 23.4.1 (5044d02a986e634881bbc85393c2936dacdcb6ec)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: BridgeTransport 2.0.32
