### ISSUE TITLE
"Error: Device call in progress" in onboarding

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#7867]
**Describe the bug**
When I go through the onboarding process and I get to choosing either "Standard backup" or "Shamir backup" I should be better navigated to use the Trezor device for confirmation of this. When I try to click one of the options again I get "Error: Device call in progress" because the Trezor wants me to confirm the option I chose earlier. There should be something like "Accepts on device" or something like that.

**Steps to reproduce:**
1. Trezor T without seed.
2. Go through the onboarding till you get to choosing the backup type.
3. Select one of the backup types and try to click on (or the other one) multiple times
4. You will see "Error: Device call in progress"

**Info:**
 - Suite version: desktop 23.4.0 (1c4c12d8d0b0cc76145c20a0b2475b21fc7bd745)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision e2416bcec2072baf65dda2d3c2359cc7217753bc)
 - Transport: BridgeTransport 2.0.32

**Expected result:**
User should be shown to continue on device after selecting the type of backup in the onboarding process.

**Actual result:**
Unclear instructions in onboarding process can lead to selecting the type of backup again in Suite which results in "Error: Device call in progress" error.

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/226328125-780c63ec-8e7c-42e7-a7b1-a51b7c72e3c4.png)

**Comment by mroz22** [comment]
This just needs some UI handling - disabling button based on suite locks

**Comment by komret** [comment]
There are two steps to fix this:
1) Add the Connect method locking the device (in this case, `resetDevice`) to `wrappedMethods` in `connectInitThunk`. This will enable Suite to recognize that no call to Connect should be made while this method is executed.
2) Use the `isLocked` util returned from `useDevice` hook to determin whether the device is locked and while it is, disable the button(s) calling other Connect methods.

We have to do it like this everywhere until Connect implements some queueing mechanism.

Related PR to fix this in other places: https://github.com/trezor/trezor-suite/pull/9858/files The first commit is an example of how to add a method to the list. You can finish that PR as well if you like.

**Comment by STew790** [comment]
**QA OK**
I wasn't able to reproduce this.

**Info:**
 - Suite version: desktop 24.1.0 (ed53f9f5caf12b7fce24bc17b74043e4c1e6d448)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.1.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
