### ISSUE TITLE
ERC20 n.8 - Transaction detail screen ETH + token

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7881]
When user clicks on transaction on transaction detail, he can see detail of the transaction of token
Currently the transaction shows ETH as the value but we should display e.g. Shiba Inu
Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=15675%3A78681&t=Y8K01RLwe0rTiroY-1

**Comment by Nodonisko** [comment]
@mnuky Do we have desing for this?

**Comment by mnuky** [comment]
Not yet, I will take a look on the needed changes compare to current transaction detail tomorrow.

**Comment by bosomt** [comment]
**QA OK**
