### ISSUE TITLE
Cropped text while importing asset

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7891]
Tested on iPhone 12
Steps to replicate the issue:

1. Import any asset
2. Check the loading screen
3. Text is cropped

![Image](https://user-images.githubusercontent.com/84183817/226873681-a9770dc9-36e9-47e4-b2ea-62f52d805818.PNG)
![Image](https://user-images.githubusercontent.com/84183817/226873680-890af77e-c841-437c-aaae-81281ecce2a7.PNG)

**Comment by bosomt** [comment]
**QA OK**

fixed in dev version 250, tested on iPhone 11
