### ISSUE TITLE
'Forged' ERC20 transactions initiated by another address showing in history

### ISSUE THREAD

**Issue by jonsats** [trezor/trezor-suite#7906]
Description:
Attacker(s) are initiating sponsored ERC20 transactions in an attempt to trick users to sending funds to an address the attacker owns. These sponsored transactions are appearing in history to make it look like the user has sent ERC20s to the attacker's address previously.
https://github.com/etherscan/ethvalidate/issues/121

Expected Behavior:
Account history should filter out / grey out / or alert users to a sponsored transaction so they don't think their account has been hacked, and to reduce the chance they send to the wrong address.

**Comment by sime** [comment]
@jonsats Trezor Suite has already this functionality since the February release. 

https://trezor.io/support/a/address-poisoning-attacks
https://github.com/trezor/trezor-suite/issues/7278#issuecomment-1400308319
