### ISSUE TITLE
The fee of transaction is calculated in day header, regardless of ownership of the transaction

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#7907]
**Describe the bug**
Not initiated transactions' fee is counted in day header

**Info:**
-   Suite Version: 22.2.0

**How to reproduce**
1. ETH acc
1. Phishing tx
1. Check day header

**Expected behavior**
I spent 0 ETH, so it should not be counted

**Screenshot**
![Screenshot 2023-03-22 at 18 12 09](https://user-images.githubusercontent.com/33235762/226984678-7dd6db27-6e6d-40fe-9b70-b86bcf7aa143.png)

**Comment by tomasklim** [comment]
Think also about export transactions and redoing `zeroPhishingValue` condition

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.5.1 (3a3a0170978edcee49c99c17a428c4efeeba9dfc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.5.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
