### ISSUE TITLE
Replace Model R with T2B1

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#7908]
All references to Model R to be replaced with T2B1

**Comment by tomasklim** [comment]
So probably all references to Model T should be replaced by `T2...`? and same for 1?

**Comment by Hannsek** [comment]
I do not know, it would be a lot of work, no? 

Besides that, we renamed all legacy builds to T1B1. See [here](https://github.com/trezor/trezor-firmware/pull/2900).

**Comment by sime** [comment]
Agreed with @matejkriz that it is not worth the effort to go back.

**Comment by tomasklim** [comment]
It's not a big effort. Is `features.model` in fw also changing to the new names?

Should we also change it for `connect`? @mroz22 

If model R is reported as `t2b1` I would do some translation on connect side that every `model` is translated to those "professional" names, so that suite does not need to handle model translation for example for images.

**Comment by mroz22** [comment]
Is firmware changing what it reports in `features.model`?

I'd prefer keeping `features.model` as it is since it might be consumed by 3rd party. We could introduce a new field something like `features.model_meow` and use it.

**Comment by Hannsek** [comment]
The internal name T2B1 is not yet implemented to the fw. @matejcik

**Comment by tomasklim** [comment]
This PR does not solve the issue completely.
https://github.com/trezor/trezor-suite/pull/8229

What is done:
- Trezor Model R is now called `T2B1` in comments and codebase. However, it is still called `TR` in case of files  (videos, images) and urls
- Trezor Model 1 and Trezor Model T names are unified as `T1` and `TT` for easier transaction to `T1B1` and `T2T1` in the future
- File names are now unified and prefixed/postfixed to be called `trezor_model` for easier renaming in the future

What is not done and has to be done in future:
- rename `T1` and `TT` to `T1B1` and `T2T1`
- wait for adding `internal_model` attribute to fw
- add `internal_model` fallback to `connect`
  - I find it stupid to add it there now when we do not have it anywhere else
- change device model logic in Suite to use `internal_model`
- rename all images to `internal_model` names
- decide if we want to use internal model names in `connect`
- decide if we need display model logic (current codebase does not need it)

**Comment by sime** [comment]
@Hannsek could you link respective FW/Connect issues so we can track this?
