### ISSUE TITLE
Transaction history wrongly detects change outputs

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#791]
I send a transaction with 1.7 BTC where change output was 0.1 BTC, but in history, I see -1.8 BTC
https://btc1.trezor.io/tx/f3202c913b74924eb29a69274654b7b156d4745f83c41a7273fccf64252d907d

This happens also with incoming transactions with multiple recipients.

**Comment by sorooris** [comment]
Could you please specify the version of Suite this was encountered on and additional details?

**Comment by ZdenekSL** [comment]
@slush0 Can you please provide more technical info? Thank you

**Comment by ZdenekSL** [comment]
See screenshot. The transaction is stated to be -0.05353854 BTC, but in reality, I only send the 0.00141614 BTC

![Screenshot from 2019-11-14 14-37-40](https://user-images.githubusercontent.com/50332311/68861758-700a6780-06ec-11ea-8943-aff9aeae277b.png)

**Comment by ZdenekSL** [comment]
Fixed
