### ISSUE TITLE
Graph axis label horizontal overflow

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#7910]
If the axis label of a graph is too long, it horizontally overflows. A check that controls the length of the label text and adjusts its position accordingly needs to be introduced. 

![Image](https://user-images.githubusercontent.com/26143964/227155050-28177a9b-2e9e-4398-8edb-a91084a57127.png)

**Comment by mnuky** [comment]
@juriczech unfortunately the fix did not work - see printscreen from my updated app (231)


![Image](https://user-images.githubusercontent.com/84183817/232488547-66f0f74d-403f-4c7f-81f2-1b480cb5fe59.PNG)

**Comment by bosomt** [comment]
@mnuky im not able to reproduce it it latest dev version 233 :(
can you please try one more time or move issue to `to do` status or approve if now OK ?

**Comment by juriczech** [comment]
@bosomt @mnuky This PR (https://github.com/trezor/trezor-suite/pull/8128) was merged yesterday. Sorry I forgot to link it in this issue. If the bug is not there, that means it's fixed.
