### ISSUE TITLE
Transaction detail - displayed information for all coins

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7913]
As a user I would like to see information related to transaction of my coin correctly in order not to be confused. 

Description:
Coins have different informations to be displayed in transaction detail. See the description below for each coin. 

1. Bitcoin
2. ETH, ETH Classic, ERC20 tokens
3. Litecoin, Dogecoin, ZCash, Bitcoin cash
4. XRP
5. Cardano

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14956%3A66150&t=Po9fGzQQcOFlLIOd-1

**Comment by bosomt** [comment]
**QA OK**

 tested on dev version 233 on iPhone 11
