### ISSUE TITLE
Indexeddb security origin changed

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#7923]
Security origin for indexeddb in desktop builds has changed from file:// (current production) to file:/// (current develop) ~~so it can lead in **loosing all data stored in DB** on Suite desktop update!~~

**Comment by matejkriz** [comment]
caused by electron update https://github.com/trezor/trezor-suite/commit/4d6fba0280c1230bec18c114d3fae3e93a7c4019 not node update

**Comment by matejkriz** [comment]
https://github.com/electron/electron/issues/37702

**Comment by matejkriz** [comment]
It looks like my assumption about loosing the data because of this change was wrong - data are preserved even though the Security origin has changed from file:// to file://

@bosomt Please double check that on new Release Candidate once is ready (it's not easy to test the transition between current production and develop, because the whole user folder has been renamed for develop - but you could try to migrate the data from production to current develop by renaming the folder from `suite-desktop` to `suite-desktop-dev`)

**Comment by bosomt** [comment]
**QA OK**

23.3.x > 23.4.x migration without any kind of problem **QA OK**
23.4.x > 23.5.x-dev copy via renaming folder **QA OK**


**Info:**
 - Suite version: desktop 23.4.1 (3693c7aba5ee58758c4c0acedeb812eb6c5fecd5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.1 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32

**Comment by bosomt** [comment]
I just found bug /i guess/ @matejkriz 

- renamed app directory to dev
- used dev version
- used production version
- now both dirs exist `suite-desktop-dev` and `suite-desktop`
- but production version reports as dev version in app bar

<img width="806" alt="image" src="https://user-images.githubusercontent.com/31506317/230004067-19a1e01e-82d5-472c-8b8d-4718d9b5c072.png">

**Comment by matejkriz** [comment]
> I just found bug /i guess/ @matejkriz
> 
> * renamed app directory to dev
> * used dev version
> * used production version
> * now both dirs exist `suite-desktop-dev` and `suite-desktop`
> * but production version reports as dev version in app bar
> 

Could you imagine any real use case that can lead to that? Sounds very weird to me.

**Comment by matejkriz** [comment]
Fixed in https://github.com/trezor/trezor-suite/issues/8019

**Comment by bosomt** [comment]
**QA OK**

- tested migration from `23.3.2` to `24.4.1` - language , label, sats, fiat, saved wallet, dark mode - everything was migrated to new database
- tested `23.5.0.dev` to `23.4.1.prod` - renamed `suite-desktop-dev` to `suite-desktop`  and all settings were removed even they both use database version `35`
- no idea whats causing this but separate environment directories works as expected



**Info:**
 - Suite version: desktop 23.4.1 (6c6a0e9979bb80b2d6592214684ea3638a532df8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.27
