### ISSUE TITLE
Enhance the graph with interactions

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7924]
As a user I would like to see the point on the graph when I received or sent the crypto in order to get better understanding of the graph. 

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=14455%3A108463&t=JOLVKyyKfmWgzG6I-1

Acceptance criteria:
Graph with transaction points is only on asset detail page
When there is received transaction, there is green point on the graph
When there is sent transactions, there is red point on the graph
When there are more transactions at once, there is "colour" point
When user moves the finger on the point we display bubble with information about the transaction (Sent / Received and amount)
PRIO 2 - we might try to play with haptic - when user gets to the point on the graph, trigger haptic

**Comment by bosomt** [comment]
**QA OK**

fd58036 - [develop] - chore(suite-native): update fastlane (#8996)
