### ISSUE TITLE
Standard wallet identified as hidden when passphrase disabled

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#7927]
**Describe the bug**
Standard wallet is  identified as hidden when passphrase disabled.
When you remove add wallet without disconnecting device it loads as `Standard wallet`
This happens only when there is PIN protection enabled. 

**Steps to reproduce:**
1. Disable passphrase
2. Enable PIN protection
3. Reconnect device
4. Load wallet and unlock device
5. Observe wallet name

**Info:**
 - Suite version: desktop 23.3.2 (2ab6b568e556d4eebd8c0d3bb04fa278bfe18506)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.2 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.11.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: BridgeTransport 2.0.32

**Screenshots:**

<img width="392" alt="image" src="https://user-images.githubusercontent.com/31506317/227516657-aa522547-c5f0-4d7f-8f7f-014b2a6a79d2.png">

<img width="778" alt="image" src="https://user-images.githubusercontent.com/31506317/227516709-97c01c46-07d3-49f3-be06-4f2771eb8fa4.png">

```
trezorctl get_features                                                                                                   ✔
Features (174 bytes) {
    auto_lock_delay_ms: 600000,
    bootloader_hash: 32 bytes 0xfa12a44fa05fd1d20539358b54f301cee4c3219c9f1bb3a5772ffd609af9e8e2,
    capabilities: [<Capability.Bitcoin: 1>, <Capability.Bitcoin_like: 2>, <Capability.Crypto: 5>, <Capability.Ethereum: 7>, <Capability.NEM: 10>, <Capability.Stellar: 12>, <Capability.U2F: 14>],
    device_id: 'C1C59C136634345A1B4C1719',
    fw_vendor: 'SatoshiLabs',
    initialized: True,
    language: 'en-US',
    major_version: 1,
    minor_version: 11,
    model: '1',
    needs_backup: False,
    no_backup: False,
    passphrase_protection: False,
    patch_version: 1,
    pin_protection: True,
    revision: 20 bytes 0x85a26d2c9593bcdf858c2d718d79951ca927a0c3,
    safety_checks: <SafetyCheckLevel.Strict: 0>,
    unfinished_backup: False,
    unlocked: True,
    vendor: 'trezor.io',
    wipe_code_protection: False,
```

**Comment by matejkriz** [comment]
Here https://github.com/trezor/trezor-suite/issues/4933 is a proposal to remove the option to disabling passphrase from suite settings completely. Can we reconsider that, please? @Hermez-cz

**Comment by bosomt** [comment]
**QA NOK**

standard wallet is still identified as hidden


<img width="582" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/2d715e0b-fbb4-4df7-b798-86057b7f5cdc">

**Info:**
 - Suite version: desktop 23.9.0 (b5c24aa43350998ed132edf093927558d6dde36b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T1B1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 23.9.0 (f63132e332ff78d1f9535c7a12f8cada9c03e757)
 - Suite version: web 23.9.0 (f63132e332ff78d1f9535c7a12f8cada9c03e757)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T1B1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: BridgeTransport 2.0.33
