### ISSUE TITLE
Send form BTC: Error: Cannot read property 'hex' of undefined

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#794]
Linux Mint 19.2 Cinnamon: https://termbin.com/ml1w
Im using the 1.0.0 build of Suite

![Peek 2019-11-14 13-07](https://user-images.githubusercontent.com/50332311/68856110-fe2c2100-06df-11ea-95e6-99a9e3025ddc.gif)

**Comment by vladimirvolek** [comment]
Cannot reproduce in develop. Fixed.
