### ISSUE TITLE
Module not found: Error: Can't resolve 'memcpy' in '.../node_modules/bytebuffer/dist'

### ISSUE THREAD

**Issue by jaredrethman** [trezor/trezor-suite#7944]
**Describe the bug**
Running `trezor/connect` from my project produces a warning in the terminal.

**Info:**

-   Remembered Wallet: yes
-   Suite Version: @trezor/connect v9.0.7
-   Browser: N/A
-   OS: Mac 13.2.1
-   Bridge: v2.0.27
-   Firmware Version: Model 1, v1.12.1

**How to reproduce**

I can provide a reproducible repo if necessary.

**Expected behavior**

* Usage of package yields no warnings.

**Screenshots**

![Screenshot 2023-03-28 at 10 23 14](https://user-images.githubusercontent.com/3676975/228288180-9761cf79-9ad8-4d27-9ac3-9e09c04ea73e.png)

**Additional context**
I received an additional warning regarding [encoding](https://github.com/andris9/encoding#readme) dependency missing. Was able to install which resolved the warning, however I'm unable to install https://github.com/dcodeIO/node-memcpy as it throws a fatal error, which I don't understand.
![Screenshot 2023-03-28 at 10 40 25](https://user-images.githubusercontent.com/3676975/228292177-e9451477-4496-4459-ba75-7bfabe8a57ee.png)

**Comment by sime** [comment]
@jaredrethman Are you sure that node-memcpy is coming from @trezor/connect? 

I too fail to install node-memcpy, but installing @trezor/connect by itself doesn't cause an issue.
