### ISSUE TITLE
Accounts list broken in descreet mode

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#7945]
**Describe the bug**
Mobile version is missing accounts list and receive addresses when you enable discreet mode.
When you disable discreet mode you can see again receive addresses and list of imported accounts.

**Info:**

-   Suite Version: mobile version 23.3.1 Lite
-   OS: iPhone

**How to reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/31506317/228456181-a0123ba3-c604-4783-8084-36d5809f863d.png)
![image](https://user-images.githubusercontent.com/31506317/228456206-3a7fbc64-697a-41b6-aa3f-84f5a21fe766.png)
![image](https://user-images.githubusercontent.com/31506317/228456238-e0ceda66-fa2e-4129-9c6b-7273bce2c764.png)

**Comment by mnuky** [comment]
it's working on my devices

**Comment by bosomt** [comment]
I was not able to reproduce issue anymore 🎉
