### ISSUE TITLE
Handle situation with all non-private uxtos in pending state

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7946]
**Situation**
All non-private utxos are pending... It is expected that pairing will be failing. 

<img width="1287" alt="Screenshot 2023-03-29 at 6 57 35" src="https://user-images.githubusercontent.com/26002916/228499379-30b1a2f1-c67a-4079-aa97-aae00e9f5a5e.png">

**Proposal**
Change the state to something like: "Waiting for transaction confirmation" and keep regular time estimate in the progress circle.

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
