### ISSUE TITLE
Show xpub UI bug

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#7950]
**Describe the bug**
See screenshot, there is grey line above XPUB QR code 

**Info:**

-   Remembered Wallet: yes/no
-   Suite Version: mobile 23.3.1
-   OS: Android

**How to reproduce**

1. Go to imported account detial
2. Click on `Show public key (XPUB)`
3. Observe modal

**Screenshots**
![image](https://user-images.githubusercontent.com/31506317/228551211-8f3b008f-a336-4faa-b524-325976132a89.png)

**Comment by PeKne** [comment]
Already fixed by PR https://github.com/trezor/trezor-suite/pull/8049. Closing.

**Comment by bosomt** [comment]
**QA OK**
