### ISSUE TITLE
Receive section does not allow you to select coin or account

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#7951]
**Describe the bug**
`Receive` section does not allow you to select coin or account.
It only shows you last selected coin and when you press `<`
 button you are navigated to `My Coins` section.

**Info:**
-   Suite Version: mobile 23.3.1
-   OS: Android

**How to reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Screenshots**
<img width="359" alt="image" src="https://user-images.githubusercontent.com/31506317/228554133-8ed33e4e-2a4f-4ae7-b294-5cd5b953a6aa.png">

**Comment by PeKne** [comment]
@bosomt Could you please specify what you mean by `Receive section does not allow you to select coin or account.`? From which screen did you navigate to receive screen?

I was not able to reproduce this issue.

**Comment by bosomt** [comment]
already fixed, now you can see coins/accounts when you navigate to `Receive` section
