### ISSUE TITLE
Investigate possible git tagging for mobile app releases 

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#7953]
Looks like any tag on github interfere with current Suite Desktop autoupdate setup - Suite takes latest tag as latest release. 

Tested on fork, Suite Desktop app checking the tag `@trezor/suite-native@23.6.1` https://github.com/matejkriz/trezor-suite/releases/tag/%40trezor%2Fsuite-native%4023.6.1 🤔 

We need to find a solution to allow tags for mobile app releases but do not interfere with desktop updates.

**Comment by matejkriz** [comment]
So the possible solution is quite easy – never ever check `Set as the latest release` nor `Set as a pre-release` checkboxes for the mobile app release. Suite Desktop always check only those latest or pre-release versions. 
![image](https://user-images.githubusercontent.com/3729633/229154068-b79f4385-0cd5-4812-beb4-4a2f7c380918.png)
cc @juriczech @vdovhanych @Nodonisko

**Comment by vdovhanych** [comment]
is it possible to create a release without checking one of those options?

**Comment by matejkriz** [comment]
> is it possible to create a release without checking one of those options?

Yes, there is always just one latest release. Tested on fork. And every release that was latest is now in that state.

**Comment by Nodonisko** [comment]
Ok, thanks for info. cc @juriczech
