### ISSUE TITLE
Coin amount changes after it was imported 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#7956]
**Describe the bug**
Coin amount changes from time to time with my test account.
Account showed 0,1 then 0,005 and back.

https://tbtc1.trezor.io/xpub/vpub5YiQAEKHWwmdG1qMm1y5FryfPmMCm4ANtZTNthSpLRC1ATZ9CpQddrTKXDrw9xbxvPPhjKJyUfWc8xQJQLx5KyoComWt1Ho18mb6P86ed2u

**Info:**

-   Suite Version: mobile 23.3.1
-   OS: Android

**Screenshots**

<img width="392" alt="image" src="https://user-images.githubusercontent.com/31506317/228602460-85c2df0f-f3d3-4d8d-b3df-24381e6465f1.png">

<img width="339" alt="image" src="https://user-images.githubusercontent.com/31506317/228602399-7c8b26b6-d92f-481c-a8c2-881fc856bd93.png">

<img width="336" alt="image" src="https://user-images.githubusercontent.com/31506317/228602339-30913267-5198-4dae-88d0-125c8651b970.png">

<img width="332" alt="image" src="https://user-images.githubusercontent.com/31506317/228602284-59892415-bc30-4047-937a-b63bbe4d80ea.png">

**Comment by bosomt** [comment]
i was able to replicate issue on iPhone version.
0 tbtc vs 0.125.. tbtc

<img width="374" alt="image" src="https://user-images.githubusercontent.com/31506317/228603760-de41dd8d-3ac4-4ad9-8837-03e9bb0fa7e7.png">

<img width="370" alt="image" src="https://user-images.githubusercontent.com/31506317/228603865-00a70026-eea6-463d-92a8-0e117d4b4e1f.png">

**Comment by PeKne** [comment]
This problem was affecting only the testnet accounts. Fixed in  #8043.

**Comment by bosomt** [comment]
**QA OK**

 tested on dev version 233 on iPhone 11
