### ISSUE TITLE
App sometimes hangs on splash screen

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#7957]
Sometimes app hangs on splash screen. Both iOS and Android.

I found that issue is caused by this error https://satoshilabs.sentry.io/issues/3913536417/?project=4504214699245568&referrer=project-issue-stream related to MMKV storage

Following should be considered and handled too: 
1. Could be realted to https://github.com/expo/expo/issues/21173
2. Could be related to our init thunk (maybe something is pending forever and thunk is never done?)

**Comment by Nodonisko** [comment]
Related to #8131 

We should now at least display error message instead of splahscreen idefinitely

**Comment by juriczech** [comment]
Seems to be fixed by https://github.com/trezor/trezor-suite/issues/8131
