### ISSUE TITLE
Clicking on the cross does nothing

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#7959]
New firmware on model T introduces this message in receive flow: `ButtonRequest.Warning`

After receiving this message by Suite there is currently this popup. When I click on the cross in the upper right corner, error message `Address verification error: Popup closed` is triggered and Suite freezes.

**Expected behaviour**: Suite should exit the receive flow and send message to Trezor to exit the receive flow as well.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/57008159/228649737-61a689ff-2ab1-40f6-b928-5c5bb8972b87.png">
<img width="380" alt="image" src="https://user-images.githubusercontent.com/57008159/228649806-390f9dd7-50ce-4e3a-bb82-c4f5f0750bdf.png">

**Comment by Hannsek** [comment]
Solved for now on fw side. Will reopen when needed.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.5.0 (0f6b428936d1ab6efe14e9e2fb2cb4d402bfdc67)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.6.0 Universal (revision 3b59d71093a56b7f396bd4aa6b5334a940223b67)
 - Transport: BridgeTransport 2.0.32
