### ISSUE TITLE
Use reboot to bootloader feature for TT and T2B1

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#7961]
**Spec:** 
Use this feature https://github.com/trezor/trezor-firmware/pull/2841 in Suite.

Change the current TT flow for TT and T2B1 from the current, where users have to manually reconnect the device in bootloader mode:

![Image](https://github.com/trezor/trezor-suite/assets/88533514/9b815c9d-b03c-4280-a93e-061033c14bdf)

![Image](https://github.com/trezor/trezor-suite/assets/88533514/d26b07da-3132-459a-bdd2-91d61b6e4bf7)

To automatic bootloader entry without disconnecting as it is already on T1 (only use the proper device illustration):

![Image](https://github.com/trezor/trezor-suite/assets/88533514/85c831d1-5bbe-4761-8743-07e128a086a0)

![Image](https://github.com/trezor/trezor-suite/assets/88533514/65224d1b-244f-451d-9ebb-676615e226d6)

**Comment by Hannsek** [comment]
\+ Connect as well.

**Comment by sime** [comment]
@Hannsek @matejkriz FYI I created a milestone `Core FW 2.6.1` and placed this tasked in it, where we (I) can keep track of next FW update-specific tasks.

**Comment by sime** [comment]
In theory, we can develop this anytime, if someone migrates from 2.6.0 universal to 2.6.0 btc only. Good catch @bosomt

**Comment by bosomt** [comment]
Do we really have to wait for next firmware update 2.6.1 to get this feature ?
I consider it low hanging fruit :) /but thats just my opinion ;) /

**Comment by Hannsek** [comment]
We don't have to wait. Next fw update is the latest date. It's just about priority and that is on @sime @Hermez-cz.

**Comment by matejkriz** [comment]
I believe the flow for T2T1 and T2B1 can be improved here, because it's different from T1B1:

On T1B1 the device in bootloader is connected to Suite and ready for FW installation right away, but on T2 user have to do one more click on the device INSTALL FIRMWARE (T2T1) / INSTALL FW (T2B1).

So it looks like this on T2:
<img width="600" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/e7017656-4643-447f-9045-aca3cb2ead9f">
<img width="300" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/c4c94021-ae12-45fe-a345-f5ddcf5d45eb">

And after you click on RESTART:
<img width="600" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/4e8cb90f-ffc0-481a-ada9-5cb20d5e47a6">
(see no Confirm on Trezor, because there is no device visible for the Suite at that moment)

<img width="300" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/fe717014-1423-4805-81d2-79c5cf7fe1b6">


That state after RESTART can be improved somehow - at least change the copy to something like "Confirm INSTALL FIRMWARE/FW" on your Trezor screen. But keep in mind, that the state is Indistinguishable from the state when the device is really disconnected.

cc @Hermez-cz 

P.S.: "reboot to bootloader" feature doesn't make it worse than it is with "reconnect in bootloader"...

**Comment by Hannsek** [comment]
We will slightly edit the "new fw install" flow. So let's sync on it @Hermez-cz.

**Comment by bosomt** [comment]
Im not sure if asking to reconnect device with swiping touchscreen is expected outcome when you cancel reboot to bootloader on device.
But feature works as expected. 

+ retest with older fw **QA OK**
 - Device: Trezor T2T1 2.4.0 Universal (revision ea3596ad8)


https://github.com/trezor/trezor-suite/assets/31506317/699b1792-e2ba-46d5-9068-1e506518563e

**Info:**
 - Suite version: desktop 23.8.0 (549c8f7df73e06cd2542440ec88078a2786170cb)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.8.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33

**Comment by Hannsek** [comment]
The expected outcome is that the "jump to bootloader"/"install fw" flow would be canceled.

Maybe we can get rid of the cancel button in FW. 🤔

But it is not a blocker for this PR for me.

**Comment by sime** [comment]
Agreed not a blocker, as the 'information' is still correct, though the expectation may be something else.

But worthy of a separate issue.
