### ISSUE TITLE
Icon highlight doesn't correspond with text highlight in bottom menu

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#7965]
**Describe the bug**
When I try to import an XPUB and click into the text field where I can paste my XPUB and instead of pasting it I click on "X" to close the importing, it gets me correctly to the "Home" page but in the menu at the bottom only the text "Home" is highlighted in green and the icon of "Coins" stays highlighted in green. It might be more clear from the screenshot provided.

**Info:**

-   Suite Version: 23.3.1 (4) ba45616
-   OS: iOS 16.3

**How to reproduce**

1. Click on "Portfolio"
2. Click on "+" sign to add account
3. Select any coin
4. Click into the text field for entering account manually
5. Click on the "X" to close the importing of account
6. It takes me back to "Home" but in the menu at the bottom only the text "Home" is highlighted in green and the icon of "Coins" stays highlighted in green

**Expected behavior**
Correct part of menu and icon is highlighted.

**Screenshots**
![image](https://user-images.githubusercontent.com/48477147/228860603-480d9103-a677-4d8b-9bee-059bd91a3d08.png)

**Comment by juriczech** [comment]
@STew790 Can you please verify that this bug is still in the app? Tried to reproduce but wasn't succesful.

**Comment by STew790** [comment]
**QA OK**
I can't reproduce this on latest production app 23.4.1 (718daf8) on Android.

**Comment by STew790** [comment]
**QA NOK**
Unfortunately, this showed up again.
When I tried to do the "Import already imported XPUB" test, I end up with this bug again.

1. start the app
    1. navigate to already imported btc account 
    2. display xpub and copy it
2. navigate back to account section and select import
3. type the XPUB key in the `enter XPUB manually` input and confirm
    1. user is transferred to the `Coin already synced` page
4. Press `Continue to app`

** Info: **
Suite Lite version 23.9.1 (20) iOS

**Comment by matejkriz** [comment]
@STew790 Could you please double check?

**Comment by STew790** [comment]
**QA OK**
I can no longer reproduce this.

**Info:**
24.9.1 https://github.com/trezor/trezor-suite/commit/9ff8920814b8616034ab7375d1b6dbf9b5ec65ab
