### ISSUE TITLE
Example text in Import tx overflows

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#7966]
Taproot account -> Send -> Import

The example text overflows. (It will be related to all addresses that are as long as Taproot addresses)

<img width="703" alt="image" src="https://user-images.githubusercontent.com/57008159/229109221-a2b788ac-8362-4136-a03e-85c30df68687.png">

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.2.0 (b69076a80bab8eca3eb8a0caa0d3d2cb44e24981)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2T1 2.6.4 bitcoin-only (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
