### ISSUE TITLE
Amount not displayed in Send dialogue

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#7967]
**Describe the bug**
See screen and video.
I was able to reproduce this issue in Google Chrome and Mozilla Firefox.
Tested with ETH and BTC , same results.
Same results with coin control on/off.

Noticed when you leave Send dialogue and come back amount is rendered as expected.

**Steps to reproduce:**
1. Navigate to Send dialogue
2. Select send all or input fiat amount
3. Check Amount in coin field

**Info:**
 - Suite version: web 23.4.0 (f169f0f32c939b2dea222e818a69038ba63ff8be)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.5.4 Universal (revision 305b7fe84d802db7f0826d07a222a886f73732f0)
 - Transport: BridgeTransport 2.0.32

**Expected result:**

**Actual result:**
A clear and concise description of what actually happens.

**Screenshots:**
<img width="636" alt="Screenshot 2023-03-31 at 15 20 05" src="https://user-images.githubusercontent.com/31506317/229131350-581a2fab-948d-418f-afc8-ae771af4f852.png">

<img width="628" alt="image" src="https://user-images.githubusercontent.com/31506317/229132258-e354fc47-188d-4d0b-a67e-f811465287ac.png">

https://user-images.githubusercontent.com/31506317/229131361-74216b39-ff42-4a97-a800-86bf53f30f70.mov

**Comment by bosomt** [comment]
Works as expected in older dev app.

 - Suite version: desktop 23.4.0 (2ee6814afa5f7290889eb4b76c18412fa112b6f1)

**Comment by matejkriz** [comment]
blame this PR https://github.com/trezor/trezor-suite/pull/7850, @dahaca could you please have a look on that?

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.4.0 (21653072a7c14c04156cfc6992cec5b582b00a99)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: BridgeTransport 2.0.32
