### ISSUE TITLE
Occassionally broken ProgressWeel in coinjoin account

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#7968]
Broken `ProgressWheel` (see video). Not sure how to reproduce it, it happened to me twice already.

**Info:**
 - Suite version: desktop 23.4.0 (2836861d877dd46c06fcc966190cf1bf5d5defed)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteLocal/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: model T 2.5.4 Universal (revision 04964dc2e8647abe600164b024dbe2dc64d89b79)
 - Transport: BridgeTransport 2.0.32

**Screenshots:**
https://user-images.githubusercontent.com/42465546/229196482-fd5c4c2a-cb8b-4746-b1b9-a49b38852b8b.mov
![Screenshot 2023-03-31 at 19 35 00](https://user-images.githubusercontent.com/42465546/229197907-30c35279-030d-4c01-a4ee-03ce206663b5.png)

**Comment by hynek-jina** [comment]
@STew790 saw that as well

**Comment by STew790** [comment]
Yes, this happened to me as well. Unfortunately, I'm also not really sure how to reproduce this one. I was in a Coinjoin round and alt-tabbing back and forth and somehow saw this once. It got "fixed" on its own when the progress wheel changed.
![image](https://user-images.githubusercontent.com/48477147/229458212-cf19cd19-f14f-4fda-80ae-ef54c20b3f29.png)

**Info:**
 - Suite version: desktop 23.4.0 (71e608b5a7f3e1393b153b608ac5ef9d91d19198)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 6e0c2578f8932c94413b2d1564725dc687eceaf7)
 - Transport: BridgeTransport 2.0.32

**Comment by hynek-jina** [comment]
Spotted again in production version 😢

**Comment by hynek-jina** [comment]
The fix wasn't released yet... so the bug is expected in production..

**Comment by STew790** [comment]
**QA OK**
I was not able to reproduce this.

**Info:**
 - Suite version: desktop 23.5.1 (3a3a0170978edcee49c99c17a428c4efeeba9dfc)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.5.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
