### ISSUE TITLE
Logs not created even when debug is enabled

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#7972]
**Describe the bug**

Recently we disabled extensive logging in suite but default, but im not able to find logs even when debug mode is enabled.
When you start Trezor Suite via `./Trezor\ Suite --log-level=debug --log-write`  you can see log in cli but file is not created

**Steps to reproduce:**
1. Start Suite
2. Enable debug mode if not enabled already
3. Open local storage directory and look for logs 

**Info:**
 - Suite version: desktop 23.4.0 (71e608b5a7f3e1393b153b608ac5ef9d91d19198)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 6e0c2578f8932c94413b2d1564725dc687eceaf7)
 - Transport: BridgeTransport 2.0.32

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/229469214-7a857b38-6a7b-48ee-9a3a-2f75e687a13b.png)

**Comment by matejkriz** [comment]
blaming this commit https://github.com/trezor/trezor-suite/commit/69f95a43cb4baa9f94e5fe9beb8a8c8ae5a2dfc2 respectively https://github.com/trezor/trezor-suite/commit/9fbead564b0cb63522802e6e30bb6db81c52614c
cc @karliatto

**Comment by bosomt** [comment]
**QA OK**

<img width="400" alt="image" src="https://user-images.githubusercontent.com/31506317/229991570-3d31d5e7-4518-40d0-b203-a6318a5c9b85.png">

<img width="505" alt="image" src="https://user-images.githubusercontent.com/31506317/229991727-3441c719-737e-4373-b6b4-0aa72696b6c2.png">


**Info:**
 - Suite version: desktop 23.5.0 (fb7f33afedb2b485bd366a37242c22840e2eb516)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.5.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: 
 - Transport: BridgeTransport 2.0.32
 - 
**Info:**
 - Suite version: desktop 23.4.1 (3693c7aba5ee58758c4c0acedeb812eb6c5fecd5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.1 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32
