### ISSUE TITLE
Remember pending and prepending transactions

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7973]
With remembered account Suite should remember pending and prepending transactions.

**Context**
_Currently on coinjoin accounts we do mempool sync only for new transactions, so there is a risk that user woun't see the transaction. This may cause an unintentionalan attempt to double-spend → cancellation of already coordinated coinjoin rounds.
This affects all accounts types._

**QA**
- Please make sure that there are no duplicities - specially when transaction changes status  (prepending → pending → mined)

**Comment by STew790** [comment]
**QA OK**
After I remembered wallet and after a successful coinjoin I quit Suite and open again and I correctly see the pending transaction.

**Info:**
 - Suite version: desktop 23.4.1 (cff9e3ab255d4a7feebe7fb81ff3170146ee3537)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
