### ISSUE TITLE
Send dialogue fiat field not auto filled

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#7984]
**Describe the bug**
Fiat field is never filled when you enter amount manually.
When you select send max it works as expected.
When you edit amount it works. 
But when you just enter amount and wait it never gets filled.

**Steps to reproduce:**
1. Navigate to `Send` dialogue
2. Fill in `Address` and `Amount` fields
3. Observe fiat field 

**Info:**
 - Suite version: desktop 23.4.0 (21653072a7c14c04156cfc6992cec5b582b00a99)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32

**Screenshots:**
<img width="650" alt="image" src="https://user-images.githubusercontent.com/31506317/229735404-c40a02de-eedf-4e7a-b23d-7ed82b91e67a.png">

<img width="672" alt="image" src="https://user-images.githubusercontent.com/31506317/229736299-50e5d68c-eb11-4ef7-930f-22969bd639c1.png">

**Comment by STew790** [comment]
~~**QA OK**~~
~~Send max button works correctly now.~~

~~**Info:**~~
 - ~~Suite version: desktop 23.5.0 (25db17dd25a294b299e7210911e446127500a2d3)~~
 - ~~Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.5.0 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36~~
 - ~~OS: Linux x86_64~~
 - ~~Screen: 1920x1080~~
 - ~~Device: model T 2.6.0 Universal (revision 3b59d71093a56b7f396bd4aa6b5334a940223b67)~~
 - ~~Transport: BridgeTransport 2.0.32~~
 
 Sorry, jumped the gun here. This isn't ready yet. My bad.

**Comment by STew790** [comment]
**QA OK**
Ok, now it is correct. After filling some amount and pressing "Send all" the amount is correctly filled out.

**Info:**
 - Suite version: desktop 23.4.1 (6c6a0e9979bb80b2d6592214684ea3638a532df8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 3b59d71093a56b7f396bd4aa6b5334a940223b67)
 - Transport: BridgeTransport 2.0.32
