### ISSUE TITLE
Misleading tooltip 'Amounts are too small for coinjoin.' 

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7996]
**Describe the bug**
Having all coins private hover on circle progress displays tooltip `Amounts are too small for coinjoin`.
When I increase the desired anonymity level it takes a while to calculate the state... and after that tooltip disapears.

**Info:**
 - Suite version: desktop 23.4.1 (3693c7aba5ee58758c4c0acedeb812eb6c5fecd5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.1 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: model 1 1.12.1 Bitcoin-only (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.27

**Video**

https://user-images.githubusercontent.com/26002916/229998394-e0b45caf-36eb-4d3b-b6c5-ccf17b6cdc39.mov

**Comment by komret** [comment]
**QA:** The tooltip should not be visible when all funds are private. Secondly, there should be no delay between updating coinjoin setup and the values propagating to the Overview tab or send form. E.g. after changing anonymity, Coin Control categories should be adjusted accordingly and the `ProgressWheel` (play/pause button) should be in correct state.

**Comment by STew790** [comment]
**QA OK**
Tooltip is not visible when all funds are private. Also, I don't see any delay when setting up different desired anonymity level and switching to the "Overview" of the account or to the coin control. Progress wheel seems to be working fine as well, showing the right current anonymity level.

**Info:**
 - Suite version: desktop 23.5.0 (a6fe27dc5c98075732dba81999c7af7068b03643)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.5.0 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
