### ISSUE TITLE
Change & Add icons

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7997]
Change icon according to Figma on these screens:
1. Fetching data while importing XPUB: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14455%3A105826&t=DanJhjDpokLX7ICG-1
2. Asset detail with empty asset: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14455%3A108634&t=DanJhjDpokLX7ICG-1
3. Pending transaction in transaction list: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14455%3A107273&t=TgghX1OReNBBWFQn-1

Add icons according to Figma on these screens:
1. Coin synced: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14455%3A105710&t=DanJhjDpokLX7ICG-1
2. Coin already synced: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14455%3A105806&t=DanJhjDpokLX7ICG-1
3. Error screen: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14455%3A107585&t=DanJhjDpokLX7ICG-1
4. Receive screen before revealing address: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14455%3A111380&t=DanJhjDpokLX7ICG-1
5. Add icon for Coinjoin transactions: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14455%3A107273&t=DanJhjDpokLX7ICG-1

**Comment by bosomt** [comment]
**QA OK**
