### ISSUE TITLE
Add storage support (web/electron)

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#8]
*  @trezor/suite (indexedDB)
     * [x] initial support 
     * [x] settings
     * [x] sendForm cache
     * [x] accounts
     * [x] devices
     * [x] transactions

**Comment by slowbackspace** [comment]
progress on react-native implementation is tracked in https://github.com/trezor/trezor-suite/issues/765 as part of [the react-native epic](https://github.com/trezor/trezor-suite/issues/740)
