### ISSUE TITLE
Too long symbol name and address in transaction detail

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#8002]
**Describe the bug**
- symbol name is too long and makes transaction detail ugly

**Info:**

-   Suite Version: 23.4.0

**How to reproduce**
1. Find transaction with long token name (cardano acc ALL SEED)

**Expected behavior**
- shorten it, same as NFT
![Screenshot 2023-04-05 at 11 03 42](https://user-images.githubusercontent.com/33235762/230034502-d3b8428e-91e2-4b4a-bfc9-b8e65bef5378.png)

**Screenshots**

![Screenshot 2023-04-05 at 11 01 16](https://user-images.githubusercontent.com/33235762/230033883-160209c6-30d4-4815-be86-4b1bfd178915.png)
![Screenshot 2023-04-05 at 11 01 36](https://user-images.githubusercontent.com/33235762/230033977-ee3fb43c-3ae3-4654-be82-e0ae240d370f.png)

**Comment by tomasklim** [comment]
Resolved here #12319

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.5.0 (a8b9ad1cb927fe970d12e3f74b47c45b423ca9ea)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
