### ISSUE TITLE
NFTs section

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#8004]
![Screenshot 2024-06-11 at 17 15 36](https://github.com/trezor/trezor-suite/assets/33235762/bb9fdde3-f355-476c-81d9-6150ae61073c)

**Describe the bug**
- ERC721, ERC1155 are filtered out so they do not arrive to Suite UI (not sure where)

**Expected behavior**
I will see NFTs in Suite. I want to be able to filter by ERC721 and ERC1155. Rabby does not distinguish
![Screenshot 2024-05-02 at 12 24 06](https://github.com/trezor/trezor-suite/assets/33235762/54436058-f05d-4898-89c7-7cf9cf2530ab)

**What we get from BlockBook:**

**ERC1155**
```
{
  "type": "ERC1155",
  "name": "Airdrop at linkredeem.io",
  "contract": "0x43721eF8de94FD33E23eE267546d67CeFdB1968C",
  "transfers": 1,
  "symbol": "NFT",
  "decimals": 18,
  "multiTokenValues": [
    {
      "id": "1",
      "value": "1"
    }
  ]
}
```
Link to BlockBook: `https://matic1.trezor.io/nft/0x43721eF8de94FD33E23eE267546d67CeFdB1968C/1`

What is interesting for us?
`type` (ERC-1155)
`name` (Collection)
`symbol`
`contract address`
`ID` (id of NFT, number)
`amount` (how many of specific NFT with specific ID I have)
`number of transfers`

**ERC721:**
```
{
  "type": "ERC721",
  "name": "AstronomiaMeta",
  "contract": "0x23A864B6bB94518B0FA41d17f8f52ea38A826457",
  "transfers": 1,
  "symbol": "AstronomiaMeta",
  "decimals": 18,
  "ids": [
    "95729"
  ]
}
```
Link to BlockBook: `https://eth1.trezor.io/nft/0x8506540784ec25A19aB750741A4AB1b6D8790e2c/1`

What is interesting for us?
`type` (ERC-720)
`name` (Collection)
`symbol`
`contract address`
`ID` (id of NFT, number, there is always just 1 unique)
`number of transfers`

Icon for recognised NFTs can be fetched from coingecko. It is not circle but square
![Screenshot 2024-05-02 at 12 22 27](https://github.com/trezor/trezor-suite/assets/33235762/21c3c90d-1895-4500-b5cf-5e66f895f444)

User can have more NFTs from same collection. Do we want to put collections together or just have it as a new token?
`type` (ERC-720)
`name` (Collection)
`symbol`
`contract address`
`number of transfers`
+ icon

is for collection.

`ID` (id of NFT, number)
`amount` (how many of specific NFT with specific ID I have)

for item

**Comment by tomasklim** [comment]
#8036 interesting links included

**Comment by tomasklim** [comment]
@AdamSchinzel let's add it in experimental features for first versions

**Comment by enjojoy** [comment]
NFT -> NFT and HIDDEN -> Two tables for 2 types of tokens

No picture, no receive, no send, copy contract address, show transaction history, link to blockbook where pictures are sown.

**Comment by tomasklim** [comment]
@trezor/qa please wait with testing, @enjojoy will prepare manual for you and everything needed

**Comment by bosomt** [comment]
Manual here : https://github.com/trezor/trezor-suite/pull/15467#issuecomment-2557011809

**Comment by bosomt** [comment]
**QA OK**

https://github.com/trezor/trezor-suite/pull/15467#issuecomment-2575148298
