### ISSUE TITLE
Internal transaction - type 1 + 2 - contract creation/destruction are ignored

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#8006]
**Describe the bug**
- internal transaction - contract creation and destruction is filtered out in `blockchain-link` and should not be

**Info:**

-   Suite Version: 23.4.0

**How to reproduce**
1. Have account with this transaction
1. Check that you do not see it in transactions

**Expected behavior**
- you will see it 

**Screenshots**
![Screenshot 2023-04-05 at 11 13 14](https://user-images.githubusercontent.com/33235762/230036895-d7df016c-cbcf-42ea-97f6-63c0026e56ba.png)

**Comment by sime** [comment]
@tomasklim Do you think this is low hanging?

**Comment by tomasklim** [comment]
I think it is not trivial

**Comment by tomasklim** [comment]
closing together with #8017
