### ISSUE TITLE
Codesign version shows "Trezor Suite Dev" in titlebar

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8019]
<img width="632" alt="image" src="https://user-images.githubusercontent.com/3729633/230115863-dcecb14f-3e7d-40e5-9484-a9e3a9dfbf41.png">

**Comment by matejkriz** [comment]
Still not fixed, @suite-common is not processed by esbuild in /packages/suite-desktop/scripts/build.ts but only by `build:lib` script so `IS_CODESIGN_BUILD` environment variable had been evaluated with build:libs. I'll fix it.

**Comment by STew790** [comment]
**QA OK**
No "Dev" present in titlebar.
**Info:**
 - Suite version: desktop 23.4.1 (6c6a0e9979bb80b2d6592214684ea3638a532df8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 3b59d71093a56b7f396bd4aa6b5334a940223b67)
 - Transport: BridgeTransport 2.0.32
