### ISSUE TITLE
Missing transactions at coinjoin account history

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8020]
**Describe the bug**
Missing transactions at coinjoin account history after messing up with laving from account during discovery

**Info:**

-   Remembered Wallet: yes/no
-   Suite Version: app/web, commit
-   Browser: name, version
-   OS: name, version
-   Bridge: version
-   Firmware Version: model, version/commit

**How to reproduce**

1. Add coinjoin account
1. Switch to default account
1. Switch back to coinjoin account 
1. Switch to default account
1. Switch back to coinjoin account 
1. Wait for the discovery loading
1. Everything seems ok, but you might be missing some transactions

**Comment by STew790** [comment]
**QA OK**
I was not able to reproduce this on the latest RC.
**Info:**
 - Suite version: desktop 23.4.1 (6c6a0e9979bb80b2d6592214684ea3638a532df8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
