### ISSUE TITLE
Save device bug and Camera still??

### ISSUE THREAD

**Issue by akissz** [trezor/trezor-suite#8027]
There seems to be a bug in the current version or maybe previous. Not sure how the save device was supposed to function but for about 12 months I was able to start the Trezor Suite without Trezor plugged in and it would still display the previously viewed screen, maybe that was wrong. Now recently it asks me to plug in the Trezor each time and its very very slow syncing data. I tried force resetting the application deleting the application data on the computer and restarting the application and this does not help, it does not save the device it seems. So it seems older Suite versions were running better.

And you still have the forward facing camera a default thing? Why is camera even a option on the Trezor Suite, seems like a major security flaw, and also completely useless to use anyway. You should change the camera button to be select image file on computer or scan qr on screen with screen selector box only.

**Comment by sime** [comment]
@akissz Click on your wallet in the top left and toggle the remember option

As for camera access, it's needed for QR code scanning.
