### ISSUE TITLE
Standard wallet labeled as Hidden wallet when empty passphrase is entered on device 

### ISSUE THREAD

**Issue by zaplmi** [trezor/trezor-suite#8029]
**Describe the bug**
When entering blank passphrase **on device** the empty string is being used in the wallet derivation process and Standard (not passphrase protected) wallet is correctly discovered, however it is wrongly labeled as **Hidden wallet n.1**

**Info:**

-   Remembered Wallet: no
-   Suite Version: 23.3.2
-   OS: MacOS
-   Bridge: 2.0.27 (bundled with Suite)
-   Firmware Version: model T, FW 2.5.3

**How to reproduce**

1. Open Trezor Suite ( 23.3.2), 
2. Connect and unlock Trezor device 
3. Click on 'Enter Passphrase on Trezor'
4. Leave passphrase blank and confirm
5. See error (wallet wrongly labeled as Hidden wallet n.1 even though Standar wallet is accessed)

**Expected behavior**
After leaving the passphrase blank an proceeding, not passphrase protected wallet is accessed. This wallet should be labeled as _Standard wallet._

**Screenshots**

<img width="523" alt="image" src="https://user-images.githubusercontent.com/91535734/230480396-3bb49141-203c-4f0c-8d04-75350fb3e784.png">

**Additional context**
After proceeding to +Add wallet - and choosing Standard from the modal:
I am getting:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/91535734/230481062-cfdb3e09-dfeb-438a-9d33-0011699916eb.png">

When continue to discover wallet, it is labeled correctly. 
However If blank passphrase is entered on device again, I get passphrase duplicated and Standard wallet is wrongly labeled again.

**Comment by sime** [comment]
@zaplmi I think this is related: https://github.com/trezor/trezor-suite/issues/7927

**Comment by bosomt** [comment]
afaik its expected i already created issue for it in past
https://github.com/trezor/trezor-suite/issues/3620#issuecomment-817941128

**Comment by sime** [comment]
Closing as suite intentionally doesn't know what was entered on device.

**Comment by Hannsek** [comment]
It can be "fixed", when you have your wallet remembered…
