### ISSUE TITLE
Tx with ERC-1155 shows only first NFT available, without # of units

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#8036]
**Describe the bug**

Right now, we show only first ERC-1155 within a transaction without units.
https://github.com/trezor/trezor-suite/blob/develop/suite-common/wallet-utils/src/transactionUtils.ts#L413
https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/components/suite/FormattedNftAmount.tsx#L48

**Info:**

-   Suite Version: 23.4.0

**How to reproduce**
https://ethereum.org/en/developers/docs/standards/tokens/erc-1155/

Example tx:
https://etherscan.io/tx/0xa3074c72e058a29f077f5c478e86dd600623c562939e5ce0a3a3cb65b7a4a706
https://eth1.trezor.io/api/v2/tx/0xa3074c72e058a29f077f5c478e86dd600623c562939e5ce0a3a3cb65b7a4a706

Example address with NFTs:
https://eth1.trezor.io/address/0x958B69371e5750Ca8e6436f122322d68b395f781
https://etherscan.io/token/0x05baf9f1961e1ed1dac222a1f97c479441b31b34?a=81#inventory

**Expected behavior**
- shows all NFTs of tx
- shows value of NFT

<img width="1426" alt="Screenshot 2023-04-07 at 21 51 54" src="https://user-images.githubusercontent.com/33235762/230668977-cb45c1dc-38b1-404b-9956-6410d331c8ed.png">

**Comment by sime** [comment]
@tomasklim Seems like a blockbook problem first?

**Comment by tomasklim** [comment]
I think the data we are getting are correct

**Comment by enjojoy** [comment]
The data are correct and we get all the multitoken values, it just has to be displayed on the frontend 

<img width="453" alt="image" src="https://github.com/user-attachments/assets/38c97c3c-b061-4004-8156-fa56ae972aaa">

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/2bea1949-c9ba-476b-9c6e-3434c1664978)

<img width="708" alt="image" src="https://github.com/user-attachments/assets/8e185701-7ef9-454c-8eae-eb92727a215a">


**Info:**
 - Suite version: web 24.12.0 (8e06da97c80bc2660920a2daee3db3a02af625e7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: WebUsbTransport
