### ISSUE TITLE
UI Polishing of Receive address with QR code

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8040]
As a user I would like to see nicer Receive address page because it:
1. increases my trust to Trezor brand, 
2. Bigger QR code helps me to scan it
3. splitting the number after 4 digits helps me to read the address
4. Lighten up the screen helps with scanning the QR code in the dark

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=14455%3A111759&t=1q4oz8ByTCkTIELZ-1

**Acceptance criteria:**

- Make the QR code bigger
- Receive address is split after 4 characters (it increases the readability) and aligned on the center
- When user clicks on Copy, page is not closed, but we display "Copied" notification
- When user reveal the address - screen mobile app screen brightens up no matter what is the current setting of the screen

**Comment by bosomt** [comment]
**QA NOK**


See difference between displayed and actual address.

Tested on Android develop version 429

Missing last two characters :)

<img width="361" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/e85de853-48f2-4a90-8e76-073aab22f621">

<img width="344" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/76fccfbb-2682-4928-8e88-0dccbbff1849">

**Comment by bosomt** [comment]
**QA OK**

tested on Android dev version 23.5.1 (433)
