### ISSUE TITLE
Chaintek Wallet won't let you send funds with Trezor

### ISSUE THREAD

**Issue by TomTom1991** [trezor/trezor-suite#8044]
**Describe the bug**
After logging in with Trezor to the Chaintek Wallet https://wallet.chaintek.net/ it is not possible to send any RVN coin to any other wallet. When trying to enter the transaction, Trezor gets stuck in the Signing Transaction screen (see screenshot below)

**Info:**

-   Remembered Wallet: yes
-   Suite Version: web
-   Browser: Google Chrome, most recent
-   OS: Win 10
-   Bridge: most recent
-   Firmware Version: most recent

**How to reproduce**

1. Go to Chaintek Wallet
2. Connect to RVN wallet with Trezor, it will prompt for your passcode displayed on your Trezor
3. Click on RVN wallet
4. Click on Send RVN
5. Choose valid address & amount of RVN, click on send
6. Trezor will get stuck in Signing Transaction screen

**Expected behavior**
The expected behavior is that Trezor prompts me to input my pin and it sign the transaction.

**Screenshots**

Trezor &  Chaintek wallet get's stuck in the following screen
![Problem1](https://user-images.githubusercontent.com/15375498/231025519-40b4933b-cc56-465f-b8a9-13f5919fb1b9.PNG)

**Additional context**
I tried different browsers (Chrome, Edge, Firefox), allowed pop ups, disables app blocker, disabled firewall, tried disabling Trezors safety checks and nothing works.

**Comment by Hannsek** [comment]
Chaintek wallet still uses Connect v8. I’ll prompt them to update to v9.

**Comment by Hannsek** [comment]
If you need to send the coins, you can download _electrum-ravencoin_ together with Trezor Bridge. All your funds should appear in the app.
