### ISSUE TITLE
Import screen is displayed when currency is changed

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8056]
Steps to reproduce the bug:
1. You have at least one XPUB imported
2. Go to settings and switch the currency
3. You are redirected to import asset screen without no reason - look at the video

https://user-images.githubusercontent.com/84183817/231257246-150f4955-5537-43e6-b8be-3d8819f0df53.MP4

**Comment by bosomt** [comment]
**QA OK**

tested on dev version 233 on iPhone 11
