### ISSUE TITLE
Mark change address in transaction detail

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8058]
As a user I would like to see change address marked otherwise I'm confused what is the second address in my outputs

Acceptance criteria:
If we are able to recognize the change address, change address is marked

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14639%3A55770&t=5rIwPtgfFL5UmKYW-1

**Comment by bosomt** [comment]
**QA OK**

fd58036 - [develop] - chore(suite-native): update fastlane (#8996)
