### ISSUE TITLE
Coinjoin max rounds cap of 500

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8062]
The max number of rounds we ask Trezor for should be 500 with safety checks enabled on the device. 

We need to have a solution for our robots that currently asks for more rounds (with safety checks disabled).

https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/utils/wallet/coinjoinUtils.ts/#L188

Without this cap it can happen if you gain really low anonymity from your previous rounds, that you get this error:
![Screenshot 2023-04-12 at 10 26 28](https://user-images.githubusercontent.com/3729633/231412219-e2b00974-1735-49b9-a26d-ef64179c8fe6.png)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 23.6.0 (318a420dad332eff2c709fed29d403fa7dd2d65b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.6.0 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
