### ISSUE TITLE
Pending CJ transaction detail modal closing unexpectedly after opening it in CJ transaction history

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#8069]
**Describe the bug**
When I open a pending transaction details modal in CJ history of a CJ transaction that just happened, it closes itself after a few seconds on its own for some reason.

**Steps to reproduce:**
1. Participate in a CJ round
2. After CJ round successfully ends, open the pending CJ transaction in the tx history
3. The transaction detail modal closes on itself after a few seconds

**Info:**
 - Suite version: desktop 23.4.1 (5044d02a986e634881bbc85393c2936dacdcb6ec)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 3b59d71093a56b7f396bd4aa6b5334a940223b67)
 - Transport: BridgeTransport 2.0.32

**Expected result:**
Transaction detail modal stays open.

**Actual result:**
The transaction detail modal closes on itself after a few seconds

**Comment by sime** [comment]
@STew790 Is this 100% reproducible?

**Comment by sime** [comment]
@STew790 Double checking the reproducibility of this?

**Comment by STew790** [comment]
Ah my bad, I remember I even checked this but I forgot to respond, sorry.
**QA OK**
I wasn't able to reproduce this in 23.5.0 build.
