### ISSUE TITLE
ERC20 tokens - token transactions on ETH detail screen

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8071]
When ETH has some ERC20 tokens included, we differentiate them in transaction list.
User can switch to see only ETH transaction
User can switch to see ERC20 tokens included

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=15608%3A66814&t=Y8K01RLwe0rTiroY-1

**Comment by PeKne** [comment]
related PR #8169

**Comment by mnuky** [comment]
@PeKne - as discussed on SU - list of ETH transaction should display only transaction contains ETH, rest is in Token tab + remove from the blue message sentense: Your token balance is reflected in My portfolio balance.

**Comment by bosomt** [comment]
**QA OK**
