### ISSUE TITLE
My assets and Receive pages are not visible in discrete mode

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#8080]
**Describe the bug**
When I launch the app, turn on discrete mode and then go to My assets or/and Receive page, I cannot see the content of the pages.

Then when I go to Home, turn off discrete mode and go back to My assets/Receive page, I can see everything there. After this, when I turn on the discrete mode again and go back again to My assets/Receive, I can see the page’s contents.

**Expected behavior**
Be able to see contents of My assets/Receive pages after I launch the app and immediately turn on discrete mode.
![3B6113EB-F5C7-4E7C-BD28-EE776E5D9F91](https://user-images.githubusercontent.com/57008159/231695833-88c9af5c-95ea-475e-aa63-221b6978d6d7.png)
![BCA59D6B-FCD7-467F-B6BB-382C9F1EE3FF](https://user-images.githubusercontent.com/57008159/231695845-28ec3dcb-b77b-4b27-8517-b47a17b4ba13.png)

iPhone 13 Pro Max,
iOS 16.3.1
develop-23.3.1 (192), commit 55eb05e

**Comment by juriczech** [comment]
@Hannsek Can you please update to latest version and verify that the issue still persist? Should've been fixed already.

**Comment by Hannsek** [comment]
I cannot update to newer version.
![77E29929-57D4-4E75-8BD4-BE59C8D91A19](https://user-images.githubusercontent.com/57008159/231697594-637462f3-14b1-4722-813f-e163a9561a69.jpeg)

**Comment by juriczech** [comment]
My latest version is build number 227. 
![IMG_154AD8B10FE0-1](https://user-images.githubusercontent.com/36101761/231698730-f5dde5b3-8fe4-4511-b20d-04be1baa2345.jpeg)

**Comment by Hannsek** [comment]
It seems to be fixed in 227 build.

**Comment by bosomt** [comment]
**QA OK**

tested on dev version 233 on iPhone 11
