### ISSUE TITLE
Disable display of 2nd coinjoin address unless there is some transaction related to the first one

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8084]
We have introduced much faster discovery of coinjoin account here: https://github.com/trezor/trezor-suite/issues/7633
This approach relies on assumption that user uses his first address first. Otherwise it could cause missing transactions in history.

**Proposal**
Disable display of second receive address unless there is some transaction related to first transaction already

**Design:** 
Disable button Show full address once you have first address revealed (and not having any transaction associated) and put explanation on tooltip.

Tooltip copy:
```
To create additional addresses for a coinjoin account, you must ensure that you have already 
received bitcoin at the initial address.
```

_[Notion mini page](https://www.notion.so/satoshilabs/Disable-display-of-2nd-coinjoin-address-unless-there-is-some-transaction-related-to-the-first-one-602ddaf0165045e98544e1f63ea55d52)_

**Comment by STew790** [comment]
**QA OK**
I can't add another new address on a fresh Coinjoin account.

**Info:**
 - Suite version: desktop 23.5.1 (3a3a0170978edcee49c99c17a428c4efeeba9dfc)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.5.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
 
![image](https://user-images.githubusercontent.com/48477147/235872228-a4567b11-304b-43ce-8649-5634f488d057.png)
