### ISSUE TITLE
Custom fee auto changes when you navigate from custom settings 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#8090]
**Describe the bug**
Custom fee auto changes when you navigate from custom settings to different fee and back.
I was able to reproduce it on ETH and on BTC network

**Steps to reproduce:**
1. Navigate to send dialgue
2. Set custom fee
3. Switch to normal fee
4. Switch back to custom fee and observe

**Info:**
 - Suite version: desktop 23.4.1 (6c6a0e9979bb80b2d6592214684ea3638a532df8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.27

**Screenshots:**

https://user-images.githubusercontent.com/31506317/231782154-0b5898e4-4ad6-4d44-be8f-633c9c9deee2.mov

https://user-images.githubusercontent.com/31506317/231783153-bb3de5fc-fc32-4548-8006-c1454f14c2f7.mov

**Comment by tomasklim** [comment]
I would say this is expected behavior
