### ISSUE TITLE
Nicer date formatting in tx detail

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#8092]
**Describe the bug**
Nicer date formatting in transaction detail.
See screenshot, date doesn't look nice.

**Info:**
 - Suite version: desktop 23.4.1 (6c6a0e9979bb80b2d6592214684ea3638a532df8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.27

**Screenshots:**
<img width="595" alt="image" src="https://user-images.githubusercontent.com/31506317/231803463-2ab29c33-cdb7-48cd-98ce-74f93a07c6da.png">

**Comment by tomasklim** [comment]
There is a bug for CZ language in JS https://stackoverflow.com/questions/64506088/cs-cz-locale-and-javascript-new-date-constructor-doesnt-allow-for-shorthand-dat

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 23.5.0 (9fab12ae5eb6cf1af8d70d5ee66fe103daac92fc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
