### ISSUE TITLE
Erc20 tokens interpreted as Ethereum in confirm modal of send dialogue.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#8099]
**Describe the bug**
Erc20 tokens interpreted as Ethereum in confirm modal of send dialogue.
You are sending token but Suite reports amount and value in Ethereum

**Steps to reproduce:**
1. Navigate to Send section
2. Try to send ERC20 token
3. Observe confirm modal during tx signing

**Info:**
 - Suite version: desktop 23.4.1 (cff9e3ab255d4a7feebe7fb81ff3170146ee3537)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.27

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/232012142-0dbaa04f-96cd-49a7-b04b-a8704992ba2f.png)

**Comment by tomasklim** [comment]
also missing contract as a first step

**Comment by tomasklim** [comment]
@trezor/qa https://github.com/trezor/trezor-suite/pull/8102#issuecomment-1508318059

**Comment by bosomt** [comment]
**QA OK**

@tomasklim confirmation steps are not aligned  properly during tx signing , does https://github.com/trezor/trezor-suite/issues/7948 needs to be merged to current rc ?

There are 4 steps in modal but only 3 steps on device / you dont need to confirm contract address / 

<img width="521" alt="image" src="https://user-images.githubusercontent.com/31506317/232572720-6a266f4e-c2a4-4ef1-9f8b-0fce048aabeb.png">

**Info:**
 - Suite version: desktop 23.4.2 (e264fca3c3404309870a1f60b29a474fce48519d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.2 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Comment by Hannsek** [comment]
I can see in our tests that you "confirm" contract as well: 
![image](https://user-images.githubusercontent.com/57008159/232678055-0cec0786-09ce-426c-8710-60cb39613a64.png)

**Comment by bosomt** [comment]
This only happens for unknown contracts, with known tokens Contract confirm page is skipped and tx signing starts with `SENDING TO` screen, @Hannsek @tomasklim should i create issue ?

**Comment by Hannsek** [comment]
I have created one for FW: https://github.com/trezor/trezor-firmware/issues/2968

For Suite, we will discuss with @sime.

**Comment by bosomt** [comment]
@Hannsek @sime approving issue , feel free to ping me if you want me to create follow up issue :)
