### ISSUE TITLE
Missing BTC only firmware in latest release candidate

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#8101]
**Describe the bug**
Missing BTC only firmware in latest release candidate.
no idea why app is looking for `trezor-2.6.0x-bitcoinonly.bin`  when file is called `trezor-2.6.0-bitcoinonly.bin` and its embeded in app

**Steps to reproduce:**
1. Try to switch firmware type in app/device settings
2. Observe error

**Info:**
 - Suite version: desktop 23.4.1 (cff9e3ab255d4a7feebe7fb81ff3170146ee3537)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0  (revision null)
 - Transport: BridgeTransport 2.0.27

**Screenshots:**
<img width="511" alt="Screenshot 2023-04-14 at 12 32 53" src="https://user-images.githubusercontent.com/31506317/232021591-c1a665c9-dd7c-410c-ae10-32491ffeb0d0.png">

**Comment by tomasklim** [comment]
there is `x` in the path

**Comment by bosomt** [comment]
**QA OK**

2.6.0
tested on universal > btc only
Btc only > universal
universal > universal


 - Suite version: web 23.5.0 (f91dd2b891f9e46a7ad57ff60301c8e4e1b70258)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0
 - OS: MacIntel

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 23.4.2 (e264fca3c3404309870a1f60b29a474fce48519d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.2 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Bitcoin-only (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
