### ISSUE TITLE
Overlapping modals while installing custom firmware

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#8108]
Downgrading FW from 2.6.0 to 2.5.3. It works, but the UI looks broken. There should not be overlapping modals nor a modal without content.

![Screenshot 2023-04-14 at 15 03 14](https://user-images.githubusercontent.com/42465546/232052360-f7f155a5-8890-4b05-9d29-db3a0abfa717.png)

![Screenshot 2023-04-14 at 15 03 43](https://user-images.githubusercontent.com/42465546/232052240-703bd81a-f48c-42b4-a40f-63bcac27cb24.png)

**Comment by STew790** [comment]
**QA NOK**
Unfortunately, this is still present.
![image](https://github.com/trezor/trezor-suite/assets/48477147/f1e1f087-6b2e-4e00-833a-11ffecc6a4c7)

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32

**Comment by komret** [comment]
> **QA NOK** Unfortunately, this is still present.

This screen looks as expected, closing. (Modals are overlapping, but in correct order.)

**Comment by STew790** [comment]
Sorry, you are right, I mistook the modal for a different one. It is OK as you pointed out.
