### ISSUE TITLE
Fetching ERC20 tokens from Blockbook instead of cdn.trezor.io

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8109]
New blockbooks has fiat rates for tokens, we should use them.

Check how it is already solved in native app https://github.com/trezor/trezor-suite/pull/7960

Would be nice to do it separately from https://github.com/trezor/trezor-suite/issues/8110 if possible.

**Comment by AdamSchinzel** [comment]
My research on this is is that on blockbook we have rates for everything except Cardano, XRP and ERC-20 tokens that are not on Coingecko (blockbook is implementing it).

That would mean that we can get rid of `blockbook.ts` `@suite-common/fiat-services` (it has outdated ticker support and everything there is implemented in `@trezor/connect`).

**Comment by AdamSchinzel** [comment]
Or maybe better, we can move fiat fetching logic to `@suite-common/fiat-services` and then use it `@suite-common/wallet-core`

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.1.1 (c4cf80383d5f554ff118ba507b743074e73216d4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: BridgeTransport 2.0.33
