### ISSUE TITLE
Refactor fiat rates fetching logic

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8110]
Integrate changes done in https://github.com/trezor/trezor-suite/pull/7960 into @suite-common/fiat-services and make it again shared logic between desktop and native. 

Discuss with @Nodonisko what issues he has been facing when he initially tried to do it shared right away.

If it's possible to do it gradually, please split it in more issues/PRs.

Maybe it can fix https://github.com/trezor/trezor-suite/issues/5089
It should definitelly decrease and optimize the number of requests on fiat rates.

**Comment by Nodonisko** [comment]
Package `@suite-native/fiat-rates` basically could be copy pasted to common, then you need to replace all access to state `state.wallet.fiat.coins` with selectors `selectCoinsLegacy`. That should be it.

Also there will be some refactoring needed in `@suite-common/wallet-types/src/fiat.ts` - most of types here should be deprecated in favor of types from new package.

**Comment by matejkriz** [comment]
partially related discussion on slack https://satoshilabs.slack.com/archives/CKZHV2G13/p1690892218934719

**Comment by bosomt** [comment]
**QA OK**

<img width="512" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/73517d53-d7a1-40f1-bbd1-bd2daefe8a2b">

**Info:**
 - Suite version: desktop 24.1.1 (c4cf80383d5f554ff118ba507b743074e73216d4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 regular (revision 1f693d3561c375661563970e066f678590abc19c)
 - Transport: BridgeTransport 2.0.33
