### ISSUE TITLE
Some BTC/ADA exports missing fee information

### ISSUE THREAD

**Issue by MatthewDavid1984** [trezor/trezor-suite#8111]
**Describe the bug**
BTC and ADA exports in CSV/PDF format are missing fee information for some transactions. All RECV txs and some SELF txs are affected 

**Steps to reproduce:**
1. Open suite
2. Export BTC or ADA transactions in PDF or CSV form
3. Observe the file's fee column

**Info:**
 - Suite version: desktop 23.4.1 (cff9e3ab255d4a7feebe7fb81ff3170146ee3537)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.27

**Expected result:**
Fee information should be present for all transactions that have an associated fee

**Files:**

[lol_account_20230414T175850.pdf](https://github.com/trezor/trezor-suite/files/11233614/lol_account_20230414T175850.pdf)
[Cardano_1_20230414T180425.pdf](https://github.com/trezor/trezor-suite/files/11233643/Cardano_1_20230414T180425.pdf)

**Comment by bosomt** [comment]
I think its expected, since last public version you dont see fees of received transactions in transaction list too.
