### ISSUE TITLE
FIAT rate on Detail of the transaction is missing

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8116]
Go to any asset detail
Click on transaction
FIAT rate under the coin amount is missing

![Image](https://user-images.githubusercontent.com/84183817/232157071-e3ccd845-12e9-4b41-9e93-5409ac215138.PNG)

**Comment by mnuky** [comment]
@Nodonisko it seems to be ok e.g. for ETH and LTC but BTC still does not display the FIAT value

![Image](https://user-images.githubusercontent.com/84183817/233146284-10bf2b91-c68e-41d0-851b-bb18cd6cc767.PNG)
![Image](https://user-images.githubusercontent.com/84183817/233146287-ab50234c-04e0-45e5-bb8c-ce03afeccb4f.PNG)
![Image](https://user-images.githubusercontent.com/84183817/233146288-d0367fdc-6f04-4ea9-aa1b-e2e768bd4b95.PNG)

**Comment by mnuky** [comment]
@Nodonisko it seems to be fine now on my devices

**Comment by bosomt** [comment]
**QA OK**

tested on iPhone 11 app version dev 243
