### ISSUE TITLE
Address poisoning attack: Label unverified token transactions in TX detail

### ISSUE THREAD

**Issue by mkolar242** [trezor/trezor-suite#8119]
BACKGROUND
---
Related to https://github.com/trezor/trezor-suite/issues/7278

Scammers employ a similar logic to that of zero-value transactions by utilizing unverified tokens that hold no fiat value but still carry a positive number of units in the transaction.

Example of the token: https://etherscan.io/token/0x8744dab2fa43055130a85c70d6b0676a82ae4704
Transaction example: https://etherscan.io/tx/0xfd7788d4ac55a9b1024d39a5d124f9e2012fc2dca197daa10c12e178d50b26ec

PROPOSED CHANGES
---
- Check the token contract address against Ethereum definitions
- If the contract address is not in Ethereum definitions label tx in the tx history
- Design remains as it is

**Comment by sime** [comment]
Could be done in combination with https://github.com/trezor/trezor-suite/issues/8007

**Comment by Hannsek** [comment]
Restrict copying the address from tx labeled as posioned.

**Comment by zaplmi** [comment]
An effective and hopfeully simple way to prevent this could be to add a warning reminding users that copying an address from your transaction history is always unsafe. They'd see it every time they copy from their history, with an option to hide it. The same goes for BTC; address re-use isn't any good to anyone. It damages privacy and makes UTXO management confusing.

[etherscan.io] has something like that for dodgy tokens. We could extend this to every copy and paste of addresses in Suite. This way, we don't even have to have a whitelist/blacklist, which would be imperfect anyway.

proposal: 

<img width="813" alt="image" src="https://github.com/trezor/trezor-suite/assets/91535734/ddeaa551-84cf-415a-8339-012260db2e71">

example from Etherscan: 

<img width="346" alt="image" src="https://github.com/trezor/trezor-suite/assets/91535734/73230b95-fb3d-42a7-a391-1b3fd54866c4">

**Comment by Hannsek** [comment]
Probably prevent copying of addresses from all transactions…

**Comment by Hannsek** [comment]
recap:
- check the token contract address against ethereum definitions
- if the contract address is not in ethereum definitions label tx in the tx history
- restrict copying the address from the tx history and also from tx detail
- ~~if one tx will contain not-scammy and scammy tokens, do not label the transaction as scammy, but follow the previous point for the scammy address –> restrict copying this address~~

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.2.0 (d0e9a1cb6b1748fbeed916520cb15304ee56a3ea)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
