### ISSUE TITLE
App allows to scan xpubs of different cryptocurrencies

### ISSUE THREAD

**Issue by zaplmi** [trezor/trezor-suite#8126]
**Describe the bug**
App allows to scan xpubs or receiving addresses of different cryptocurrencies and during the syncing process the app either freezes on _Checking transactions_  or wrongly label the account, depending on the format of the xpub. 

**Info:**

-   Suite Version: mobile 23.3.1
-   OS: iOS

**How to reproduce**

1. Go to My assets 
2. Click on +
3. Choose Bitcoin
4. Scan xpub or receiving address of different cryptocurrency 

**Expected behavior**
Displaying error message saying that the scanned QR code is not Bitcoin xpub (invalid xpub) as it is done when entered manually. 

**Screenshots**

Importing Dogecoin xpub (freezes):
![IMG_0020](https://user-images.githubusercontent.com/91535734/232473042-6cd311fa-1a7a-413f-ad84-58fcafca512d.png)

Importing Litecoin xpub (wrongly labeled):
![IMG_0021](https://user-images.githubusercontent.com/91535734/232474810-4e9ac278-1009-48ed-b1cb-78cbebc12653.png)

**Comment by Nodonisko** [comment]
This can't be always prevented but we added as many validation as possible. Right @mnuky ?
