### ISSUE TITLE
Support internal-link in coinjoin context in message system

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8129]
internal-link is supported in general message-system banner:
https://github.com/trezor/trezor-
suite/blob/develop/packages/suite/src/components/suite/Banners/MessageSystemBanner.tsx/#L43

but not in coinjoin context banner:
https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/components/wallet/AccountAnnouncement/CoinjoinContextMessage.tsx/#L21
so Suite tries to open internal link as relative external link...

![image](https://user-images.githubusercontent.com/3729633/232499011-e071f51b-2447-4b1c-82a3-f82228f11efa.png)

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
