### ISSUE TITLE
Proper error if something is wrong with storage

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#8131]
We still getting lot of errors in Sentry about storage problems. This could be caused because we were messing with encryption keys and people are updating to newest version, but we need to be ready if this somehow happen in production. If that will happen it cause app to hang on splash screen forever without any message and app reinstall is only option. We should display some kind of message and maybe button to reset storage at least.

**Comment by bosomt** [comment]
**QA OK**



![Image](https://user-images.githubusercontent.com/31506317/234010713-61d8e414-8c3e-46b4-b628-b27dcae9dcc7.png)
