### ISSUE TITLE
Update Guideline videos

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8139]
Change the Guidelines videos for ETH family, BTC family and XRP. We've removed "Desktop" from the first title as the Trezor Suite works in web browser as well.

**Comment by davycoth** [comment]
https://user-images.githubusercontent.com/131247310/233018884-7e942f6d-20e9-4d6a-9047-052e4c653edf.mp4


https://user-images.githubusercontent.com/131247310/233018942-4760462b-6e0e-4585-8ac7-bf70216553d4.mp4
