### ISSUE TITLE
Remove 1H from the graph

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8143]
Remove option to display timeframe 1H from the graph
Add 6M option to graph

FYI FOR QA - this changes Sanity test - Basic dashboard check

**Comment by mnuky** [comment]
ok for me,  tested on iPhone 12

**Comment by bosomt** [comment]
**QA OK**

tested on iPhone 11 app version dev 243

updated test template to  1D / 1W / 1M / 6M / 1Y / ALL)
