### ISSUE TITLE
Add warning if network is not in a good condition

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8145]
If network connection is not working well, there is a bigger chance that you break coinjoin round. 

There are ways how to check how bad you connection is (e.g. checking how often requests on https://wasabiwallet.co/wabisabi/status fail)

Would be nice to warn user in that case, that could be better to try it later.

**Comment by andrewkozlik** [comment]
A warning is insufficient if the user is not present or not paying attention to Suite. Suite should assess the severity of the poor network connection, and it should warn if the risk of breaking rounds is low or pause coinjoin if the risk of breaking rounds is high.

The problem might only be with individual circuits, not Tor as a whole. In that case it would be good to monitor the latency of each circuit, close it if it's too high and open a new one for the identity.

Another simple option that we discussed with @marekrjpolak is to abandon input registration if Suite detects that one of the input registration requests had a large round-trip-time.

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
