### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by taherfattahi** [trezor/trezor-suite#8149]
Can you tell me when you'll decide to support iOS devices?

**Comment by Hannsek** [comment]
This is not the right place where these questions belong. Feel free to ask on reddit/forum.

**Comment by taherfattahi** [comment]
Excuse me, but it was very important to me, I'd appreciate your help.
thank you

**Comment by taherfattahi** [comment]
I found a solution for communicating with Trezor hardware in iOS devices:
use MIDI protocol
I've tested this protocol in trezor-firmware
