### ISSUE TITLE
npm install fails installing @trezor/connect@9.0.7

### ISSUE THREAD

**Issue by mholtzman** [trezor/trezor-suite#8156]
**Describe the bug**
Attempting to install trezor-connect via the command:
`npm install @trezor/connect@9.0.7`

fails with error:

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:9.0.7

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/matt/.npm/_logs/2023-04-19T18_40_05_762Z-debug-0.log
```

Existing builds that were previously working are now failing as well.

**Info:**

Node version: 18.9.0
NPM version: 8.19.1

**How to reproduce**

1. Create a brand new project via `npm init`
2. Attempt to install trezor connect: `npm install @trezor/connect@9.0.7`

**Expected behavior**
module(s) should be installed

**Comment by mroz22** [comment]
Thanks for reporting. We are on it
