### ISSUE TITLE
Make more space on the top on dashboard above the amount

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8159]
Insert space above the section My portfolio balance, it is too close to the top of the screen and does not look good. 

![Image](https://user-images.githubusercontent.com/84183817/233297105-bab03f77-34cf-4132-a343-6f7d8ef31465.PNG)

Figma refference: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=14455%3A106119&t=4jxVmq6hB5wz2bEY-1

**Comment by bosomt** [comment]
**QA OK**

fixed in dev version 250, tested on iPhone 11
