### ISSUE TITLE
Display message when receiving ERC20 token

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8161]
As a user I would like to be informed that ERC20 token receiving address is ETH address in order to stay calm otherwise I'm confused why ETH receiving address is there.

Acceptance criteria:
When user would like to get receive address for ERC20 token, there is message informing user that this is ETH receiving address

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?node-id=15635%3A69467&t=v1gZqVsOfIUjcp71-1

**Comment by bosomt** [comment]
**QA OK**

tested in dev version 24.4.1 (263)

**Comment by mnuky** [comment]
@bosomt @PeKne I don't see it at all on both platforms - build 23.4. (263)

Uploading RPReplay_Final1683017470.mov…

**Comment by bosomt** [comment]
iPhone dev v 263

![image](https://user-images.githubusercontent.com/31506317/235623061-53f6b595-77a0-447d-a0c9-2a9fd520606d.png)

**Comment by PeKne** [comment]
Strange... On Android develop-23.4.1 (406) it also works.
