### ISSUE TITLE
Amount on asset detail should not be shortened

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8168]
![Image](https://user-images.githubusercontent.com/84183817/233444193-b8408a50-7d3c-49d8-85f4-b1c2e1606a51.png)

Amount on asset detail should not be shortened, e.g. ETH is cropped after 8 decimals, but ETH should display 18decimals

It should follow this: https://github.com/trezor/trezor-suite/blob/develop/suite-common/wallet-config/src/networksConfig.ts

**Comment by bosomt** [comment]
**QA NOK**

tested on iPhone latest dev version 251
during import and in my assets and in account detail Eth amount is always shortened 

![image](https://user-images.githubusercontent.com/31506317/234223471-52f4cf07-6adc-4f17-bcb2-be9f48d15554.png)

![image](https://user-images.githubusercontent.com/31506317/234223554-361aaf3f-b277-47c4-a050-26ef938eaeb9.png)

**Comment by PeKne** [comment]
Good catch @bosomt. The ETH decimals length was now fixed with the follow-up PR https://github.com/trezor/trezor-suite/pull/8231. Please test again.

**Comment by bosomt** [comment]
**QA OK**

tesed in latest dev version 253 on iPhone 11
