### ISSUE TITLE
Coin Control hang in CoinJoin account of Suite GUI

### ISSUE THREAD

**Issue by brianddk** [trezor/trezor-suite#8171]
**Describe the bug**
While a Coinjoin was running on testnet, I opened the `send -> coin control` window and it seems to have hung.  I could click on most controls, but none of them seemed to do anything.  Eventually I clicked on the `scan` button in the `send-to` field and that seemed to clear the hang allowing me to back out.

**Info:**

-   Remembered Wallet: yes
-   Suite Version: Windows App v23.4.2
-   Browser: N/A
-   OS: Windows 10 22H2
-   Bridge: 2.0.27
-   Firmware Version: Model-T v2.6.0

**How to reproduce**

Single occurrence, I cannot reproduce.

1. [Add Coinjoin](https://trezor.io/learn/a/coinjoin-in-trezor-suite) SLIP-25 account on Testnet
1. Start the coinjoin and let it run for 1 hour
1. While it's running, click `Send` from your SLIP-25 account
1. In the Send Dialog click `Coin Control`
1. Notice that the top right `X` to close the Send Dialog is no longer responsive

**Expected behavior**
That the Send dialog would be dismissible

**Additional context**
This was on Testnet for what it's worth

**Comment by bosomt** [comment]
**QA OK**

im not able to reproduce issues,
currently coinjoin is paused after you enter send dialogue

**Info:**
 - Suite version: desktop 23.8.0 (d548fb3fc370de8b20458b0fd9903d91289c5e59)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.8.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
