### ISSUE TITLE
Coinjoin Account and labeling disappears if TOR is disabled

### ISSUE THREAD

**Issue by brianddk** [trezor/trezor-suite#8172]
**Describe the bug**
Disabling the TOR option in Suite GUI will remove the Coinjoin (SLIP-25) account

**Info:**

-   Remembered Wallet: yes
-   Suite Version: Windows App v23.4.2
-   Browser: N/A
-   OS: Windows 10 22H2
-   Bridge: 2.0.27
-   Firmware Version: Model-T v2.6.0

**How to reproduce**

1. [Add Coinjoin](https://trezor.io/learn/a/coinjoin-in-trezor-suite) SLIP-25 account on Testnet
1. Enable "Remember Account" both in device and Coinjoin page
1. Label account "tBTC slip-25"
1. Start the coinjoin and let it finish
1. Close Trezor Suite
1. Unplug Trezor
1. Launch Trezor and disable TOR in settings
1. Plug in Trezor and connect
1. Notice the Coinjoin (SLIP-25) account is missing
1. Enable Tor and add back the SLIP-25 account
1. Notice the account returns, but the label does not

**Expected behavior**
The account should stay visible without TOR, just not accessible.  Labeling should persist if the account is re-added.  Many networks (work / school) don't allow TOR.  It's useful to be able to toggle TOR on/off even if that makes your SLIP-25 account read-only

**Additional context**
This is on Testnet, for what its worth.

**Comment by sime** [comment]
Hi @brianddk 

Thanks for the issue, since only a single CJ account is permitted per wallet, we won't prioritise this anytime soon. But you are right that this is a bug. Either the labelling should outright work, or be disabled for CJ accounts.

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue.
