### ISSUE TITLE
T Suite should support sat standard (full 8 decimals)

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#8173]
![image](https://user-images.githubusercontent.com/48504624/233521901-ed48cd16-7d15-45c7-8588-89257a5db46a.png)

Preferably on all amounts but at least small amounts should always show 8 decimals even when they're 0s.

Beside making it easier to count it's also a good reminder that amount like 0.00123 are an unusually round number (123,000) Good for change privacy.

**Comment by sime** [comment]
@nostitos thanks for the issue. You can switch to a sats denomination by either clicking on the Bitcoin account balance or via Settings > Application > Bitcoin units > Satoshis

I understand it's not exactly what you are asking, but it's how we currently solve it.

But the next time we work around the Bitcoin denomination, I will keep your keep in mind.
