### ISSUE TITLE
Coinjoin Private coins revert when restarting Coinjoin

### ISSUE THREAD

**Issue by brianddk** [trezor/trezor-suite#8174]
**Describe the bug**
If a conjoin only partially completes, when it is restarted the private UTXOs revert back and loose their existing anonymity score.

**Info:**

-   Remembered Wallet: yes
-   Suite Version: Windows App v23.4.2
-   Browser: N/A
-   OS: Windows 10 22H2
-   Bridge: 2.0.27
-   Firmware Version: Model-T v2.6.0

**How to reproduce**

1. [Add Coinjoin](https://trezor.io/learn/a/coinjoin-in-trezor-suite) SLIP-25 account on Testnet
1. Enable "Remember Account" both in device and Coinjoin page
1. Start the coinjoin and let it finish or stop it before all coins are private
1. Note your private UTXOs (viewable under `send->coin control`) and Private sat balance
1. Restart a new Coinjoin to anonymize some of the UTXOs that are not yet private
1. Notice when the Coinjoin starts that your private coins now become non-private

**Expected behavior**
The private coins should remain private.  If the private UTXOs are needed mix with the non-private one's a warning should be given to the user.

**Additional context**
I attempted three conjoins on April 19th and April 20th.  I used the SLIP-14 seed with `coinjoin` passphrase.  If anyone want's to view the transaction set that managed to de-anonymize some of the coins, all the activities on these UTXOs is visible by loading the seed/passphrase on TESTNET

```
seed: all all all all all all all all all all all all
passphrase: coinjoin
```

**Comment by hynek-jina** [comment]
Thank you @brianddk 
This is no surprise on testnet since there is are few people. Since our privacy calculation algorithm is quite strict, you are actually loosing privacy is such a bad rounds.
