### ISSUE TITLE
You have mixed numbers in the transaction details

### ISSUE THREAD

**Issue by kalich5** [trezor/trezor-suite#8184]
There is a bug in coinjoin showing amount details. The amount of the fee and the amount credited to the account are swapped.

![image](https://user-images.githubusercontent.com/8988898/233765636-048912a8-85b2-45fa-9273-e3a656283688.png)

**Comment by Hannsek** [comment]
It is not a bug. The fee is the overall fee for the whole transaction. 

The amount is the part of the whole fee that you pay.

**Comment by hynek-jina** [comment]
Thank you @kalich5 
You are right that current version is a bit confusing.
Planned improvement is described here: https://github.com/trezor/trezor-suite/issues/7109

**Comment by kalich5** [comment]
Great, now this is really confusing.
