### ISSUE TITLE
TT Recovery workflow has no ability to previous word like T1

### ISSUE THREAD

**Issue by brianddk** [trezor/trezor-suite#8186]
**Describe the bug**
When doing an Advanced Recovery on T1 and TT, I've noticed that T1 allows the user to backspace over characters, but T1 will allow you to continually back up until you get to the previous word.

**Info:**

-   Remembered Wallet: yes
-   Suite Version: Windows App v23.4.2
-   Browser: N/A
-   OS: Windows 10 22H2
-   Bridge: 2.0.27
-   Firmware Version: Model-T v2.6.0 / Model 1 v1.12.1

**How to reproduce**

1. Attempt a dry-run advanced recovery on T1
2. Get to word 9, then on the Suite GUI use the "backspace" control
3. You will notice you can eventually backup to the previous word (word 8)
4. Attempt a dry-run advanced recovery on TT and use the on-device "backspace" control
5. Notice that you can't backup to previous word, only to the first char of the current

**Expected behavior**
It would be nice to have the "previous word" feature on TT like it is on T1

**Additional context**
I find that entering 12 word seeds I will often jump to the wrong word on my list.  It's a pain to have to start all over again.  Would be nice if the user could jump back to previous words if they find out they are entering word 11 and the prompt is asking for word 10.

**Comment by sime** [comment]
Just to clarify, there is no advanced recovery on TT. There is only a single type of recovery.

**Comment by Hannsek** [comment]
This is nice to have feature. However, I don't see this as implemented in near future. Therefore I am closing this now. We can reopen this once it will be prioritized.
