### ISSUE TITLE
Coinjoin status is : Pairing failed, retrying

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#8191]
I keep getting this, Not sure what that mean.
Does that mean "pairing" with the HWW?

**Comment by hynek-jina** [comment]
Hi @nostitos,
this is not a problem.. We just need to improve copy.. 
Pairing means that Suite is trying register some of your inputs for coinjoin... It might fail from various reasons. It's not related directly to HWW conneciton..

**Comment by nostitos** [comment]
Are there logs to see what went wrong?  It lasted for 12+ hours and stopped after I restarted Suite

**Comment by sime** [comment]
@nostitos Yes, there are logs available.

1. Enable Debug mode: Click on `Settings` five times. Then a debug menu will appear
2. In coinjoin details tab, you will see a logs button
![Screenshot 2023-04-24 at 18 24 15](https://user-images.githubusercontent.com/216917/234058894-b4a4c5f2-7bcb-4feb-83e3-71848919857e.png)

**Comment by nostitos** [comment]
> @nostitos Yes, there are logs available.
> 
> 1. Enable Debug mode: Click on `Settings` five times. Then a debug menu will appear
> 2. In coinjoin details tab, you will see a logs button
>    ![Screenshot 2023-04-24 at 18 24 15](https://user-images.githubusercontent.com/216917/234058894-b4a4c5f2-7bcb-4feb-83e3-71848919857e.png)

There is no Debug option in Settings.
