### ISSUE TITLE
GPU goes to 50% when the CJ-HWW shows up

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#8194]
![image](https://user-images.githubusercontent.com/48504624/233870230-290f6644-778b-4af4-a029-02b1e59d981d.png)

This is a dedicated GPU, almost nothing is moving on the app except the small spinning disk.

**Comment by nostitos** [comment]
![image](https://user-images.githubusercontent.com/48504624/233870289-480461e5-a5de-41ca-9b05-75d295730b23.png)

**Comment by hynek-jina** [comment]
Similar to: https://github.com/trezor/trezor-suite/issues/7419

**Comment by tomasklim** [comment]
Probably related to https://github.com/trezor/trezor-suite/issues/5948

**Comment by nostitos** [comment]
50% GPU and 70mb of GPU ram to render this? :  
![image](https://github.com/trezor/trezor-suite/assets/48504624/3a97327b-5bb3-4319-a103-9d0467e29af1)

![image](https://github.com/trezor/trezor-suite/assets/48504624/9b7efde3-886b-4854-b387-4dcb18afb3bc)

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
