### ISSUE TITLE
ERC20 tokens - strange FIAT rate

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8198]
Some tokens should not have FIAT rates but we display them with huge amount of FIAT rates - see attached. 
Most likely caused by wrong data fetching - when we don't have fiat, we put ETH price. When Token does not have FIAT value, we should not list the token at all.

Example NFTGiftX.com token:

![Image](https://user-images.githubusercontent.com/84183817/233965356-32eacad9-0143-4e46-8239-8178d322ad60.PNG)

**Comment by bosomt** [comment]
**QA OK**
