### ISSUE TITLE
Ropsten network name with signing a Goerli TX

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#8213]
**Describe the bug**
Connect shows Ropsten network name when signing a TX on the Goerli network

**Info:**
Connect v9

**How to reproduce**
Sign a TX on Goerli

**Expected behavior**
Show Goerli network name

**Screenshots**

![Screenshot 2023-04-21 at 13 58 33](https://user-images.githubusercontent.com/216917/234046881-55f6b43a-2a80-4d6c-a0e4-593a50a0ae0a.png)

**Comment by mroz22** [comment]
This probably requires either:
A] providing chainId param to each eth releated connect method from outside (now it is only in ethereumSignTransaction)
B] keeping only one eth network where `"slip44": 1` in coins.json 
I wonder which way

**Comment by Hannsek** [comment]
@bosomt Is this still a thing?

**Comment by mroz22** [comment]
I already solved this but broke another (more important) thing so I had to unsolve this. Final solution shoudl be done in #9289

**Comment by bosomt** [comment]
I see Görli now in metamask


<img width="521" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/122865c8-2e47-47ac-9873-6a46f5c7193e">

**Comment by mroz22** [comment]
well. you always see the first ethereum-testnet network from `coins-eth.json` file. next time you will see sepolia there unless we improve it. 

so what is the expect behaviour? When I am signing tx (I know chain_id) I should show network name? And what if I am only requesting addres? In that case I don't have chain_id. In that case I should show goerli? Doesn't make much sense to me. I would just show "Get ethereum testnet address".

To use it I suggest that we should change ethereum definition for testned in fw repo. Right definition download by slip44 now  decodes as 
<img width="428" alt="image" src="https://github.com/trezor/trezor-suite/assets/30367552/34c1fbd2-d40a-4be5-8558-d3fbec5bfa1c">

**Comment by Hannsek** [comment]
> so what is the expect behaviour? When I am signing tx (I know chain_id) I should show network name?

yes

> And what if I am only requesting addres? In that case I don't have chain_id. In that case I should show goerli?

just show _ethereum testnet_

> To use it I suggest that we should change ethereum definition for testned in fw repo.

How it should be changed?

**Comment by mroz22** [comment]
> How it should be changed? 

I don't know. It probably can't be done to satisfy showing chain name when signing and "export testnet address" when exporting address at the same time

**Comment by Hannsek** [comment]
However, I believe this is just internal/developer thing. So I would probably close it. @sime are you ok with closing this?
