### ISSUE TITLE
Cannot add label to ETH tokens transfers and internal transactions

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#8222]
**Describe the bug**
Cannot add label to ETH tokens transfers and internal transactions

**Info:**

-   Remembered Wallet: no
-   Suite Version: app, 23.5.0
-   OS: macOS, 13.2.1

**How to reproduce**

1. Try to add label to token transfer or to internal transaction
2. You can't

**Expected behavior**
To be able to add label.

https://user-images.githubusercontent.com/57008159/234195896-0036b182-73c8-4dc5-9d63-9814419202e6.mov

**Comment by tomasklim** [comment]
Duplicate of https://github.com/trezor/trezor-suite/issues/3545

It applies to all ERC (ERC-20, ERC-721, ERC1155) and internal transfers.

**Comment by Hannsek** [comment]
Closing this in favour of https://github.com/trezor/trezor-suite/issues/3545.

We should probably bump the priority of this. @sime
