### ISSUE TITLE
@trezor/connect-web styled iframe

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#8227]
make user interaction available directly inside iframe. this would enable webusb and simplify npm package (less backwards compatibility issues)

issue create per @Hannsek request
@szymonlesisz might know about duplicate issues

**Comment by Hannsek** [comment]
@mroz22 Is this still valid?

**Comment by mroz22** [comment]
depends on product. but I think we are considering an alternative approach of popup-in-suite now

**Comment by mroz22** [comment]
imho we are going another direction
