### ISSUE TITLE
Promote mobile app and desktop suite CTA

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#8234]
## Design

* [Dashboard](https://www.figma.com/file/YoGkN5kl5FUdxZ2EOkpZTL/Exploring-Navigation?node-id=1440%3A8088&t=7NsJHbUZ1Joee0KW-1)
* [Settings](https://www.figma.com/file/YoGkN5kl5FUdxZ2EOkpZTL/Exploring-Navigation?node-id=1201-4670&t=ewPgTXI14dQoIXFO-4)

## Spec

Historical product specs
* https://www.notion.so/satoshilabs/Trezor-Suite-Lite-CTA-2588f3c57db947f9816e3e26744f47db
* https://www.notion.so/satoshilabs/Download-desktop-suite-CTAs-for-web-users-0609d608426e4a9e8e1e7fac44630469

As a web suite user
I want to download Trezor suite
So that I am secure

Given I am on the dashboard
When I scroll to the bottom
Then I should see a 'Download desktop app' button
And a Google Play store button
And an App Store store button

As a desktop suite user
I want to download Trezor Suite Lite
So that I can monitor my balance without a computer

Given I am on the dashboard
When I scroll to the bottom
Then I should see a Google Play store button
And an App Store store button

## Preflight checklist
- [x] Product/Design
- [x] [App store links](https://www.notion.so/satoshilabs/Mobile-app-general-info-6d4c382f42f74d8bb9bea1124c28ffff)
- [x] Copy
- [x] Tech Feedback

**Comment by bosomt** [comment]
**QA OK**

tested in web and in app version, including QR codes and links to app stores

**Info:**
 - Suite version: desktop 23.5.2 (c7bd95bbdf78e4944d45037f4cbff70fa66ea4a6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.5.2 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
