### ISSUE TITLE
HWW gets out of CJ mode while Coinjoning

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#8241]
Suite keep asking to verify on HWW when a CJ is about to happen, The wallet doesn't get into CJ mode, Just get into ready to sign mode.

I'll add to this report once I understand more what start this behavior.

**Comment by nostitos** [comment]
Looks like whatever has put it out of CJ mode isn't putting it back into it while it's running, unless CJ is Paused and Restarted

**Comment by sime** [comment]
It's not clear what you are describing. Could you drop an annotated screenshot?

**Comment by sime** [comment]
Please come back with more comments when you have them. Closing this issue for now.
