### ISSUE TITLE
Refactor navigators

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#8242]
Currently we have some weird logic in navigation in the mobile app. Since we use nested navigators, it's weird that we have `AccountDetail` in HomeStack, `TransactionDetail` and `AccountSettings` in RootStack.

- Refactor navigators so that account stack has account detail and account list
- TransactionDetail should also be in account list as an account namespace
- Account settings should be in account stack as well

There will be some problems with navigation handlers that should be addressed.

**Comment by juriczech** [comment]
Would be nice to do it together with [Icon highlight doesn't correspond with text highlight in bottom menu#7965](https://github.com/trezor/trezor-suite/issues/7965)

**Comment by STew790** [comment]
This should fix an issue when going to "Assets" and the picking one account (for example ETH) but the menu shows "Home".
Screenshot:
![image](https://user-images.githubusercontent.com/48477147/234599927-b53e17dc-6652-480c-8a5c-72e9c1422868.png)

**Comment by juriczech** [comment]
As agreed with @mnuky and UX:
- account detail will not have a tab bar and will be part of RootStack
- Receive option will be displayed as a modal unless it's accessed directly from tab bar
- Tab change will reset tabs state

**Comment by bosomt** [comment]
**QA OK**

tested on latest dev version 267 on iPhone
