### ISSUE TITLE
App doesn't remember mobile camera permissions on Android

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#8247]
**Describe the bug**
When I set my mobile camera permission for the app to "Ask every time" for the camera permission it doesn't ask and wants me to grant it the permission in the Android settings for the app. (video included)

**Info:**

-   Suite Version:  23.4.1 (718daf8) 
-   OS: Android 12

**How to reproduce**

1. Open the app
2. Click on "Sync my coins"
3. Click on any coin
4. Click on "Scan public key (XPUB)"
5. An Android modal for Camera permission should show up
6. Select "Ask every time"
7. Scan any coin or go back
8. Try to scan any XPUB again
9. A window with "Camera access denied" shows and the app doesn't ask for the permission

**Expected behavior**
App should ask for camera permission when this setting is ON.

**Video:**

https://user-images.githubusercontent.com/48477147/234537528-e8883eb6-9a81-4810-80e5-ea9d57b44667.mp4

**Comment by mnuky** [comment]
won't fix
