### ISSUE TITLE
Import a unsupported XPUB freezes

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#8248]
**Describe the bug**
When you import a unsupported XPUB Suite Lite freezes and you have to kill app.
Loading goes forever and you can even cancel it via `X` button.

**Info:**

-   Suite Version: build: 23.4.1 (9) 718daf8 mobile
-   OS: iOS

**How to reproduce**

1. Go to import asset BTC
1. Scan Eth QR code
1. Observe app behavior 

**Screenshots**
![image](https://user-images.githubusercontent.com/31506317/234562973-87a93792-37cf-487d-b0f6-dbacc2efb490.png)

**Comment by juriczech** [comment]
https://github.com/trezor/trezor-suite/pull/8261

**Comment by bosomt** [comment]
**QA OK**

tested in `Version 23.4.1 (10) 564056a` version
