### ISSUE TITLE
Can't enable labeling on remembered hidden wallet

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#8250]
**Describe the bug**
Can't enable labeling on remembered hidden wallet.

**Info:**

-   Remembered Wallet: yes
-   Suite Version: 23.5.0-dev
-   OS: macOS
-   Firmware Version: TT 2.6.0

**How to reproduce**

1. Enter a hidden wallet
2. Remember it
3. Reconnect the device
4. Try to enable labeling in the Sessions
5. Observe a loader being displayed on device and nothing happening afterwards.

**Expected behavior**
Suite should ask to provide a passphrase and then prompt to enable labeling on device.

**Comment by Hannsek** [comment]
Actually, the labeling is enabled. You can even click on the `add label` button. Then, the Suite sends message to Trezor for passphrase input. On Trezor I can see `Please type your passphrase on the connected host` for ~ 1/4 second and then I can see two loaders on Trezor. That is all -> I cannot add label.

**Comment by dahaca** [comment]
@Hannsek it's even less desirable.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 23.6.0 (318a420dad332eff2c709fed29d403fa7dd2d65b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.6.0 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
