### ISSUE TITLE
connect popup - useUi: false bug

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#8252]
1. modify connect explorer, so that it before submitting actual method sends TrezorConnect.getSettings().
2. TrezorConnect.getSettings(). will go through, actuall method will hang.

**Comment by Hannsek** [comment]
@mroz22 Is this still valid? cc @martykan

**Comment by mroz22** [comment]
Dunno, I didn't touch it since creating this issue so probably yes
