### ISSUE TITLE
Change the name of production app

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8253]
Final name of the mobile app should be Trezor Suite Lite - it should be reflected everywhere including the app name and presence in the store

**Comment by bosomt** [comment]
tested on iOS production version 11 - app was renamed

tested on And production version 11 - app was renamed in app store but dektop name is still TrezorSuite / tried to uninstall and install back, didnt help/



![Image](https://user-images.githubusercontent.com/31506317/236440789-727b2af1-fdd5-417b-b211-5f8f4a6d19ee.png)



![Image](https://user-images.githubusercontent.com/31506317/236440862-ba4de6d2-c38c-43a6-bb67-b90303e8ca42.png)

**Comment by bosomt** [comment]
**OK** Andorid after received update v 14
**NOK**  iOS and latets version 11



![Image](https://user-images.githubusercontent.com/31506317/236459179-46aa7b3c-244e-46cf-8889-e7cb827a6491.png)

**Comment by bosomt** [comment]
now ok on both platforms after iOS published version 12
