### ISSUE TITLE
Dot placement on graph sometimes doesn't correspond with finger placement on Android

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#8259]
**Describe the bug**
The dot placement on the graph sometimes doesn't correspond with the finger placement when "scrolling" through the graph. If you hold your finger on one point and doesn't move it, it sometimes shows the dot on the last placement you clicked other then where your finger actually is at the moment. It might be more relevant/comprehensible from the video attached.

**Info:**

-   Suite Version: app/web, commit
-   OS: name, version

**How to reproduce**

1. Go to any place where there's a graph in app
2. Click on the graph with your finger and hold your finger on one point
3. The dot on the graph either appears at the very beginning of the graph or where you last placed your finger and "left" the dot there

**Expected behavior**
The dot on the graph should be where I place my finger.

**Video:**

https://user-images.githubusercontent.com/48477147/234603227-dbbc730c-1973-47b1-8a5a-f6b43f7511fe.mp4

**Comment by bosomt** [comment]
**QA OK**

24.01.1 (673)
96d12a4 - [develop] - fix(suite): fix label drop for RBG transactions
Android 13 - Nothing phone 1
