### ISSUE TITLE
Replace `createRef` with `useRef` in function components

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#8265]
The `createRef` API is meant for class components and causes bugs in functional components as it resets its value between rerenders, unlike `useRef`. Example of such bug is https://github.com/trezor/trezor-suite/issues/5329

Detailed explanation: https://blog.bitsrc.io/react-useref-and-react-createref-the-difference-afedb9877d0f

Solution: replace `createRef` with `useRef` in all function components and make sure it does not break anything.

**Comment by komret** [comment]
@tomasklim Anything specific QA can check here? Have you tested the related components?

**Comment by tomasklim** [comment]
Yes I tested it. I don't think so

**Comment by komret** [comment]
Ok, moving this to Approved as it is just refactoring, @trezor/qa
