### ISSUE TITLE
Connect device modal

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#828]
**Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa1afc2149329a03c3fbdc)

**Comment by mroz22** [comment]
Screen not available anymore.

**Comment by glacierbits** [comment]
Web USB button (prd_ui).

**Comment by petrsulc** [comment]
Design updated:
https://zpl.io/adwln9e
