### ISSUE TITLE
Expand coin control bellow (not above) send options

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8286]
Coin control section should be expanded bellow send options (not above as in current implementation)
![Screenshot 2023-04-27 at 14 42 28](https://user-images.githubusercontent.com/26002916/234881050-f1ce766f-1db7-4ed0-a868-3aad3d0fda7f.png)

As a user I want to add another recipient, but it is unscreened bellow coin control. So I have to keep scrolling up and down when adding more recipients.

Something like this,.. but nicer:
![Screenshot 2023-04-27 at 14 54 07](https://user-images.githubusercontent.com/26002916/234883964-6a4a11a8-5d1c-4caa-8b50-0354741445e8.png)

**Comment by komret** [comment]
Done during Empower redesign:

https://github.com/user-attachments/assets/6be3404b-8540-4643-8018-aadf470ec040

**Comment by bosomt** [comment]
**QA OK**

Info:

    Suite version: web 24.8.0 (https://github.com/trezor/trezor-suite/commit/fe65e0963b951f8b8bf820916ca877d953964058)
    Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
    OS: MacIntel
    Screen: 1512x982
    Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
    Transport: BridgeTransport 2.0.33
