### ISSUE TITLE
Receive - icons switch, receive address displayed without warning when switching between accounts

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8287]
Steps to reproduce:
Have BTC and ETH assets in the app

1. Go to Receive and generate receive address, click Show address
2. Go to Home
3. Go my assets and click on ETH and Receive
4. Receive screen is displayed with revealed address - warning message is not displayed

Expected behaviour:
When user clicks on Receive the coin, address should be always hidden and the warning message is displayed before revealing
When user leaves the Receive screen without closing it by himself, we should reset it on our own - it means everytime user clicks on Receive on the menu, we should display screen with accounts where user would like to receive to

Icon switch:
1. Go to ETH and click Receive - reveal the address
2. Go to My assets and click on BTC and Receive
3. Receive screen is displayed directly with revealed address and the icon is ETH instead of BTC

Videos:
https://user-images.githubusercontent.com/84183817/234895003-24623735-8923-4c2d-9f72-d0e1c1e46a7f.MOV
https://user-images.githubusercontent.com/84183817/234895002-a3f4b6c4-ed20-4ff6-8442-207761ee093c.MP4

**Comment by bosomt** [comment]
**QA OK**

tested on iPhone with latest dev version
