### ISSUE TITLE
Connection to Custom Electrum Server backend within Trezor Suite does not work

### ISSUE THREAD

**Issue by tripletuple** [trezor/trezor-suite#8300]
I have been using Trezor Suite since launch and this particular feature has never worked for me.  I have tried getting Trezor Suite to connect to my own "Customer Electrum server" backend but it does not work.  

I have electrum server (electrs) running on a MyNode instance as well as electrum personal sever (eps v.0.2.4) running on a different instance and all of my various wallets - electrum, sparrow, blue wallet, etc can all connect to either my MyNode instance or my EPS instance with Bitcoin Core just fine which means that Electrs and EPS are both functioning and accepting connections.  

Trezor Suite cannot connect and has never been able to connect to either of these environments.  I use a secure connection to connect to both so the syntax I use within Trezor Suite is the following - X.X.X.X:50002:s.  Does not connect.  I get the standard message - "Not connected to the backend. Try reconnecting the device. Also, check your internet connection or the URL of your custom backend."

**Info:**

-   Remembered Wallet: either
-   Suite Version: All since launch
-   Browser: N/A using desktop app on MacOS (all versions)
-   OS: MacOS - currently running 13.3.1
-   Bridge: N/A
-   Firmware Version: N/A

**Comment by jandrli** [comment]
I have the same problem. I tested it today with a new Trezor. Current app: 
rpm 23.4.2 
bridge 2.0.27

On mynode server side Electrum:
v0.9.9

Tested port 50001 and 50002 under tcp and ssl. They do not match. However, the port is open (nmap):

PORT STATE SERVICE
50001/tcp open unknown

PORT STATE SERVICE
50002/tcp open iiimsf

**Comment by sime** [comment]
I managed to connect to an electrs backend that is inaccessible to the public internet. Likewise, to a random one from this list (both clearnet and Tor): https://1209k.com/bitcoin-eye/ele.php

Are you by any chance using Tor? Reminds me of this issue: https://github.com/trezor/trezor-suite/issues/5153

**Comment by tripletuple** [comment]
Not using Tor.  My electrum personal server backend is not connected to the internet. everything in my setup is accessible and connected directly via my LAN.  MyNode uses Electrs and that doesnt work.

**Comment by jandrli** [comment]
In my case, you're right. I turned off TOR support and it took my server address. With TOR enabled, even with the server address set to TOR, it didn't work initially. But maybe it took time. I tried turning on tor and set the onion address to port 50001:t and currently even that works.

**Comment by sime** [comment]
@tripletuple What happens if you try an Electrum server from this list: https://1209k.com/bitcoin-eye/ele.php

**Comment by tripletuple** [comment]
> 

electrum.blockstream.info:50002:s - doesnt work.  as well as others from the list of open electrum servers on that site.

**Comment by tripletuple** [comment]
> I managed to connect to an electrs backend that is inaccessible to the public internet. Likewise, to a random one from this list (both clearnet and Tor): https://1209k.com/bitcoin-eye/ele.php
> 
> Are you by any chance using Tor? Reminds me of this issue: #5153

not using tor and would prefer to not use tor. i want to use EPS or Electrs with my own node which itself uses Tor.  I want to connect to either of those services from my internal network.

**Comment by sime** [comment]
@tripletuple I feel like your operating system might be blocking some type of network requestions from Trezor Suite. Especially since you mention sparrow wallet connects to your node.
