### ISSUE TITLE
Can't edit CJ details after pausing.

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#8305]
I clicked Pause, waited at least 10min, I still have this

![image](https://user-images.githubusercontent.com/48504624/235328697-cc409788-29cd-4b7d-9b7d-a0bf559ed2be.png)

Update : It wasn't obvious at all that clicking the ... would show a cancel button.

**Comment by hynek-jina** [comment]
Thank you @nostitos 
Yes, it isn't obvious... we are considering merging the meaning of `pause` and `cancel`... So that you could be change the settings, but it would stop your current coinjoin.

We track it here:
https://github.com/trezor/trezor-suite/issues/7871
