### ISSUE TITLE
InputBanned for no apparent reason

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#8307]
My PC is always on and internet extremely stable. I can't think of any reason why my input would be banned.

That explain why of the many many input none of them get registered into a CJ for days.

I can't see anything in the logs that would explain why my inputs would have gotten banned.

I think we need comprehensive logs of the process in the main UI that would show the outcome of a mix attempt and when inputs are banned.

**Comment by hynek-jina** [comment]
It is hard to replicate this issue.
There are many reason for which you could ruin the round. For example your connection might be strong but the tor is probably not under your control.
These banned inputs should be accepted again in few days..

**Comment by nostitos** [comment]
We're talking about 8 pages times 25 UTXO per page worth of banned coins.

Looks like something is off about Suite and not just Tor stability.

I see my Trezor signing CJ transactoin then nothing, not even some fail message. It keeps looping like this over all steps, It's frustrating to get so little result and no feedback.

**Comment by hynek-jina** [comment]
I assume that you have received one utxo and they were splited during the coinjoin, right? How many utxos do you have now? (8*25 → 200 sounds like too many.. so can you please confirm?)

**Comment by nostitos** [comment]
pretty much, last page has just 1 so 176 UTXO

A whole lot of my sufficiently mixed coin (target 5) are 2-20$ Disgustingly small compared to how much was sent to be mixed.

**Comment by hynek-jina** [comment]
I'm sorry for that.. this is very annoying.. it seems to me like this issue:
https://github.com/zkSNACKs/WalletWasabi/issues/10462

You privacy is probably very good already.. however wabisabi client library thinks otherwise...
We are investigating that.. but so far without significant improvement.. 😞

**Comment by nostitos** [comment]
![image](https://user-images.githubusercontent.com/48504624/235492823-abe0a82f-6b4c-45b1-9234-0630ed4543f5.png)

Half of my coins are almost dusts.

I don't think privacy assumption can be made about my larger coins, I can see the last CJ I participated in being mostly breaking small UTXO smaller.

One problem is that my private coins have 10 to 16 anon score. While my target is 5.

I think these small coins and these already private coins were selected because the bigger ones got banned.

**Comment by nopara73** [comment]
Something seems very off. The number of coins are governed by the coin selection and amount decomposition algorithms. We have not encountered this before, which is strange. Do I recall correctly that you guys are using the Wasabi code directly for that? Is it possible that you made some modifications?

**Comment by nopara73** [comment]
> One problem is that my private coins have 10 to 16 anon score. While my target is 5.

That's normal. If there's 10 to 16 equal outputs to your coin, then you'll gain that anonscore.

**Comment by nopara73** [comment]
> I think these small coins and these already private coins were selected because the bigger ones got banned.

I think this is causing the UTXO inflation! Assume coins get banned very often, but not always. In that case there'll always be fewer coins selected than outputs created.

**Comment by nopara73** [comment]
Thus, the following actions can be taken:

1. Solution: Make sure coins don't get banned, there must be a lot of Tor reliability issues you have right now. Remember why I was so worried about an independent Tor implementation back then? You'll now need to make your Tor implementation battle tested.
2. Fallback: Regulate the coinjoining pace by assessing the quantities of short banned and non-banned coins and performing coinjoins only when their numbers look good (this might, in some extreme situations, hinder coinjoining altogether? But it is preferable to UTXO inflation, I suppose?)

**Comment by onvej-sl** [comment]
>Something seems very off. The number of coins are governed by the coin selection and amount decomposition algorithms. We have not encountered this before, which is strange. Do I recall correctly that you guys are using the Wasabi code directly for that? Is it possible that you made some modifications?

As far as I can remember, this is the only modification that could be related:  https://github.com/zkSNACKs/WalletWasabi/pull/10096.

**Comment by nopara73** [comment]
@turbolay commented on slack that that PR can lead to coin inflation, which would be good news for you, because rolling that back would be much easier than stabilizing Tor implementation. I am not convinced that is the culprit, but certainly worth an investigation!

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
