### ISSUE TITLE
Cannot start coinjoin due incorrect `Amounts are too small`

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8308]
**Describe the bug**
I wasn't able to start coinjoin. Tooltip has shown `Amounts are too small`, but it is not the case. It has disappeared after circa 1 minute of waiting.

**Steps to reproduce:**
1. Open Suite and go directly to remembered device
2. Disabled start button has a wrong tooltip
3. It stays there for a while even if connect the Trezor

**Info:**
 - Suite version: desktop 23.4.2 (5c5b3c885c52c38f3c8115fed07c2faf6a77fc7a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.2 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.6.0 Bitcoin-only (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

<img width="827" alt="Snímek obrazovky 2023-04-30 v 5 16 45" src="https://user-images.githubusercontent.com/26002916/235335381-cea1ac1c-945f-4f75-a6e4-fb4ea95fab89.png">

**Comment by matejkriz** [comment]
I believe this one is fixed already, please reopen if you ever see it again.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.8.1 (11285a745786e8cd7c39ada4945f5893d7e8cd23)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.8.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33
