### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#8314]
This graph is over 1 hours, 
8.33% = 100% of a single core on this 12 core machine.
40-50 seconds of 100% usage spaced by 10-20 seocnds of no usage.

Wallet isn't doing anything, Only looking at the Portfolio/ Dashboard.

I've closed the process and restarted it and will try to figure out after how long that CPU usage ramp up.

![image](https://user-images.githubusercontent.com/48504624/235469721-4ffa815a-037b-4648-9188-7523a0ca96c0.png)

**Comment by nostitos** [comment]
I see the same CPU usage pattern at start but lasting way shorter.

![image](https://user-images.githubusercontent.com/48504624/235474991-52d69789-6020-4e2e-9fb5-8805a8147dda.png)

**Comment by nostitos** [comment]
I changed the charting delay from 1sec to 5sec

![image](https://user-images.githubusercontent.com/48504624/235521169-c4371fd1-8163-4c26-a317-1311683c3ed6.png)

CPU usage got worst after starting to mix, 

I think there is a good chance that my UTXO get banned because Suite become unresponsive during these 1min CPU spikes.

**Comment by sime** [comment]
Fighting something similar at the moment. Do you get better performance (less CPU spikes) when disabling other coins?

**Comment by nostitos** [comment]
Yes I've reset all data and only loaded the one wallet with CJ
It still hang every minutes (when doin getinfo) but not for as long.

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
