### ISSUE TITLE
Empty state

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#832]
Design: https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa1b3f97449919cc6f7111

**Comment by ZdenekSL** [comment]
Added new screen

**Comment by slowbackspace** [comment]
design done in https://github.com/trezor/trezor-suite/pull/990, https://github.com/trezor/trezor-suite/pull/1006

one thing that needs to be finished is proper condition that defines 'empty wallet', currently it is set when the balance of all assets is 0. Is it correct? Maybe it should be for 'fresh/never-used' device?

**Comment by wendys-cats** [comment]
**Note:** For non-empty state scenario, there will be a graph implemented instead of the "Your wallet is ready" picture.
graph here: https://github.com/trezor/trezor-suite/issues/833
