### ISSUE TITLE
Put "learn more" button to labelling tab

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#8323]
Put 
<img width="94" alt="image" src="https://user-images.githubusercontent.com/57008159/235699036-74e7ec5c-9492-48b9-84c7-dfc3c62697fa.png">
under _Saving labels locally_

<img width="795" alt="image" src="https://user-images.githubusercontent.com/57008159/235698990-55d4717b-cf41-4aea-a280-3134ca37fb5c.png">

The `learn more` button will lead to kb article, where this is displayed: 
![image](https://user-images.githubusercontent.com/57008159/235699556-5be2a1e5-c061-469b-8b2a-a55a0560453a.png)

URL under `learn more` button: https://trezor.io/learn/a/labels-in-trezor-suite-app#storing-labels-locally

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.6.0 (318a420dad332eff2c709fed29d403fa7dd2d65b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.6.0 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
