### ISSUE TITLE
Extend coinjoin time estimate by market conditions

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8325]
UTXOs from pending transactions are not accepted into other coinjoin rounds. Coinjoin cannot be finished until the pending  transaction is mined. This doesn't apply to very last transaction.

**Naive Proposal**
- For pending transactions check its mining fee
- Compare mining fee with mempool conditions 
- Add this time to overal coinjoin estimate
- You can have a look on last broadcasted coinjoin if it is users first coinjoin transaction

But part of the issue is to came up with better solution 🙂

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
