### ISSUE TITLE
CJ tx disappear from UI

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#8328]
I participated in these two CJ this morning.

https://mempool.space/tx/3d7774decbc139ecf13cf06fd7d98887079642c65fc7e94b0cf4699e0e554116
https://mempool.space/tx/22e3ed32bbb3562b7683d110df6c3866f71ff273e26d2a096491ec6eeca0f613

They were visible about an hour ago, I didn't close Suite and now they're gone.

I follow the same wallet with Sparrow so I learned there are also the last 5 other CJ done May 1st that are not visible.

**Comment by sime** [comment]
@nostitos Is the wallet remembered?

If so, it should be solved with this: https://github.com/trezor/trezor-suite/pull/7977

**Comment by nostitos** [comment]
No it was not on remember, I did now.
Still the wallet stayed open and on screen.

**Comment by sime** [comment]
@nostitos We shipped a change that is related. Are you still seeing this?

**Comment by sime** [comment]
Closing, please shout out if you find anything else. Closing for now.

**Comment by matejkriz** [comment]
Also this can help https://github.com/trezor/trezor-suite/pull/8614 (will be available from version 23.6)
