### ISSUE TITLE
Dashboard graph

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#833]
**[Zeplin](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5e79c9bc8b52437106eac048)**

**Comment by slowbackspace** [comment]
Issue is still missing link to zeplin but I think this one is good. @matejzak could you confirm? https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5def869efffd4216938e514e

**Comment by glacierbits** [comment]
Yes, that works (as far as the graph itself). New layout updated ^

**Comment by glacierbits** [comment]
Y axis (zero)

<img width="977" alt="Screen Shot 2020-04-14 at 12 41 10" src="https://user-images.githubusercontent.com/29627086/79216354-4e550e00-7e4d-11ea-905f-e9049668a2da.png">

**Comment by bosomt** [comment]
i think that all graph looks terrible  :(

![image](https://user-images.githubusercontent.com/31506317/79461499-89df0c00-7ff6-11ea-8ef4-715581828c80.png)

**Comment by slowbackspace** [comment]
@bosomt can I reproduce this terrible look? :) (is it on all all seed?)

**Comment by sorooris** [comment]
@slowbackspace it's on all seed but behind an in-use passphrase - @bosomt or I can provide whatever screenshots or gifs needed

also:
1) please specify what timespan should be displayed under the "all" option - i would expect a span from the first date a transaction happened to the current date
![image](https://user-images.githubusercontent.com/10185314/79474173-5dcb8700-8006-11ea-9eb6-a02c748edf09.png)

2) there's a small visual bug when displaying all transactions - the last transaction overlaps with the right side Y axis
![image](https://user-images.githubusercontent.com/10185314/79477745-ddf3eb80-800a-11ea-9bb0-0b87456b41a7.png)

3) wouldn't it be better to allow a custom date select? (for example similar to soundcloud's stats page in the screenshot below)
![image](https://user-images.githubusercontent.com/10185314/79474026-34aaf680-8006-11ea-98f7-bda736131bfd.png)

**Comment by slowbackspace** [comment]
@sorooris 
ad 1) that should be the case.
ad 2) I know, there was no time left (happens only with "all" range)
ad 3) yes sir, this is like the 5th time I hear about it. @matejzak let's make it happen!
