### ISSUE TITLE
Investigate&fix bundle size rise from 23.4 to 23.5

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8340]
reported here https://satoshilabs.slack.com/archives/CLNTU7877/p1683100079777029?thread_ts=1683090650.121149&cid=CLNTU7877

The thing is that react-native is bundled

as unpacked:
![image](https://user-images.githubusercontent.com/3729633/235871756-2c429832-5c0e-496d-9051-797e731dca2c.png)

but also in app.asar in node modules
<img width="534" alt="image" src="https://user-images.githubusercontent.com/3729633/235876159-da83ad5a-e39b-4e4a-a254-8aa027199e8a.png">

**Comment by matejkriz** [comment]
blaming https://github.com/trezor/trezor-suite/commit/ea9bfc97874530407373eebae4cf8d928d4f74e1 cc @mroz22

**Comment by bosomt** [comment]
**QA OK**

Latest daily build went down to regular size
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/857848418
