### ISSUE TITLE
Change guide video for BTC family and ETH family

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8350]
Uploading BTC public address walkthrough.mp4…

**Comment by mnuky** [comment]
BTC family video:
https://user-images.githubusercontent.com/84183817/236240123-06fa5488-e658-47ad-bac2-aff5361bcca6.mp4

ETH family video:
https://user-images.githubusercontent.com/84183817/236240178-34d789c0-59cb-482c-9d91-a09a7ddb1c00.mp4

**Comment by Hannsek** [comment]
The video is still wrong. It still says `Account` instead of `Accounts`.

**Comment by Hannsek** [comment]
Also, if the video will change, we should change the name of the ETH account from `Ethereum tokens` to something else. It can be misleading/confusing for some users.

**Comment by bosomt** [comment]
**QA OK**

tested on dev version Android build 416
