### ISSUE TITLE
Add Sepolia testnet to Trezor Suite

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#8360]
At the end of the year Goerli testnet will be deprecated and we need to replace it.
Sepolia testnet needs to be introduced in Trezor Suite.
https://sepolia1.trezor.io/

Do not remove Goerli yet.

Source: https://ethereum.org/en/developers/docs/networks/#ethereum-testnets
> Note: the Goerli testnet is deprecated and will be replaced by Holesovice in 2023. Please consider migrating your applications to Sepolia.

**Comment by AdamSchinzel** [comment]
Also keep eye on [Holešovice Testnet](https://devpost.com/software/holesovice-testnet) that was developed on ETHPrague 2022 and is planned to launch later this year as said be Tim [here](https://twitter.com/TimBeiko/status/1628823216574844928?lang=en)

**Comment by tomasklim** [comment]
Mostly a reverse action to the modifications made in #8075

**Comment by bosomt** [comment]
**QA OK**

send, receive, explorer link OK
https://sepolia1.trezor.io/tx/0x60b15cd70f18eed51263a31f5f48dbb05151ad23c9a4dc468b4080cb9fbc8c21

**Info:**
 - Suite version: desktop 23.9.0 (b1c5e1a274403a0e94696888c39c83743b69ae8a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33
