### ISSUE TITLE
Assets + portfolio value

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#837]
**[Zeplin](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5def869efffd4216938e514e)**

**Comment by bosomt** [comment]
ETC column needs to be fixed ;(

![image](https://user-images.githubusercontent.com/31506317/74412231-3eb14d00-4e3d-11ea-8523-e51907e1e60a.png)

**Comment by bosomt** [comment]
but otherwise it looks nice, how about you @sorooris
