### ISSUE TITLE
Build coinjoin candidate transaction

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8370]
`Pending transaction` - The one you receive from mempool, but is not mined yet
`Pre-pending transaction` - The one that Suite knows already but is not received yet by mempool. Looks very same for the user as pending transaction.
`Candidate transaction` (earlier called `pre-pre-pending transaction`) - The one Trezor already signed but it isn't signed yet by all other coinjoin participants. Therefore this transaction might disappear (become invalid).. 
However it is important to know about it - to prevent user from spending old utxo or register it into another round.

Design:
<img width="1000" alt="image" src="https://github.com/trezor/trezor-suite/assets/26002916/de1f0312-44fb-4352-b502-db91e7f76053">

**Comment by STew790** [comment]
**QA OK**
I was able to attend a CJ and got the "candidate transation" as well.
![image](https://github.com/trezor/trezor-suite/assets/48477147/b07f48da-4200-4975-abb5-bf5926b3e313)


**Info:**
 - Suite version: desktop 23.7.0 (5d03fad86692c6ff189e861cb548742123ba641b)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.7.0 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
