### ISSUE TITLE
Add Account modal

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#838]
Add BTC:
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6eebdc4fff1fd6d89214

External wallets:
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa1bc473681316bb51587a

**Comment by vladimirvolek** [comment]
Missing states: 

![image](https://user-images.githubusercontent.com/3112191/72991231-e795fa80-3df1-11ea-8543-c43f5f1c8325.png)

![image](https://user-images.githubusercontent.com/3112191/72991256-f41a5300-3df1-11ea-8770-a5c466018e54.png)

![image](https://user-images.githubusercontent.com/3112191/72991290-06948c80-3df2-11ea-8fa0-671c72743d84.png)

**Comment by wendys-cats** [comment]
UI issue:
Missing hyperlink "Learn more" in the Add account modal for BTC. 

Expected
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6eebdc4fff1fd6d89214

Actual
![Screenshot_20200217_113422](https://user-images.githubusercontent.com/58593111/74646875-eea6f300-517a-11ea-85f5-65d8f86071c5.png)

**Comment by glacierbits** [comment]
The  _**Learn more**_ component hasn't been ready at the time. @slowbackspace pls add it to the account type selection. Thanks!

**Comment by wendys-cats** [comment]
Issue:
**Incomplete design**

**Expected**
Visuals for buttons will be consistent. 

**Actual**
Text will get underlined on hover in buttons that have external wallet links. 

Please get rid of the underline, thank you! 

![underlined text in button on hover](https://user-images.githubusercontent.com/58593111/76772873-e2c24700-67a1-11ea-8eb7-1f1f81d5b287.png)
