### ISSUE TITLE
Error: Coinjoin client not enabled: status is missing error when enabling coinjoin/tor

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#8380]
**Describe the bug**
I'm receiving `Error: Coinjoin client not enabled: status is missing` when enabling coinoin.
`Enabling Tor`  modal idling forever even tor is already connected.
I was able to reproduce it with remembered and not remembered wallet.

**Steps to reproduce:**
1. Load wallet
2. Add coinjoin account
3. Observe Suite desktop app behavior. 

**Info:**
 - Suite version: desktop 23.5.1 (3a3a0170978edcee49c99c17a428c4efeeba9dfc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.5.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/236430901-9edf3f2a-5029-4b7e-9923-0f46968bddef.png)

https://user-images.githubusercontent.com/31506317/236449315-ea9058b5-6fe8-47e4-918e-f2391ef75844.mov

**Comment by marekrjpolak** [comment]
Closely related to this: https://github.com/trezor/trezor-suite/issues/6902

The `Enabling Tor` modal is never explicitly closed when successful, but rather overriden by `Confirm on your device` modal. But when CJ fails to connect to coordinator over Tor, account creation process is not started (= no Confirm modal) but `status is missing` is shown instead.

We must make sure that when Tor loader ends successfully and Coinjoin account creation process starts, Tor is really running already.

But we can at least close the Tor modal as soon as the loader ends so we're not blocking user interaction even if account creation fails.

**Comment by bosomt** [comment]
**QA NOK**

<img width="304" alt="Screenshot 2023-05-16 at 11 58 56" src="https://github.com/trezor/trezor-suite/assets/31506317/74a099b6-4fe9-4425-8964-ffc6d291c6ed">



[trezor-suite-log-2023-05-16T09-59-49.txt.zip](https://github.com/trezor/trezor-suite/files/11486489/trezor-suite-log-2023-05-16T09-59-49.txt.zip)


**Info:**
 - Suite version: desktop 23.5.1 (f0d64a3661bf54493cda1528cbbb5caaf68168b7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.5.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Comment by marekrjpolak** [comment]
Is it same as before @bosomt? Were you trying to activate Tor while adding CJ account?

At least Tor progress modal hanging forever should be definitely fixed, was this ok?

With `status is missing` thing we at least tried to wait 1000 ms before assuming Tor is running, which should improve (but not necessarily fix) it, proper fix (which is too big to cherry-pick imo) will be related to #6902.

**Comment by bosomt** [comment]
@marekrjpolak its different "issue" and so far i was not able to reproduce it.

**Comment by bosomt** [comment]
managed to recreate

1. start cj discovery
2. remember wallet
3. quit app before it finishes discovery
4. start app

<img width="373" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/44c4ab24-b692-4027-aa84-af608b9ca167">

**Comment by bosomt** [comment]
**QA OK**

im not able to reproduce this error anymore


**Info:**
 - Suite version: desktop 23.6.0 (034ecfa94a98ca9ef2435e2c2961a8448ba93b71)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.6.0 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
