### ISSUE TITLE
Account details

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#839]
Account details in Menu: **[Zeplin](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6ef65c53651b0ae7f5ed)**

Xpub modal: **[Zeplin](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6ef99e5f0c1b94404980)**

**Comment by szymonlesisz** [comment]
resolved https://github.com/trezor/trezor-suite/pull/1234

**Comment by wendys-cats** [comment]
**Issue: Unfinished design**

**Expected**
Consistent buttons

**Actual**
Buttons Show public key and Copy public key are grey (give off the impression that these options are disabled/not available). 

Please unite the visual aspect (make buttons green again). Thank you!

![issue 832](https://user-images.githubusercontent.com/58593111/76846701-38016580-6841-11ea-8f46-b7f3b6189566.png)

**Comment by szymonlesisz** [comment]
should be fixed, in both "Show xpub" and "Show address" modals
