### ISSUE TITLE
Do not register into round if too many utxos are banned

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8394]
If a user has banned more than 40% of total non-private utxos or sum of banned utxos amounts is greater than 40% then they should not register to the next round for a certain period of time (1 hour).

It could work as a prevention of unknown bugs like https://github.com/trezor/trezor-suite/issues/8307

**Comment by matejkriz** [comment]
fixed by https://github.com/trezor/trezor-suite/pull/8484 ?

**Comment by bosomt** [comment]
AFAIK there is no way to test it on our side right ?

**Comment by matejkriz** [comment]
You can test it, at least on testnet where it's more OK to ruin the round to have banned UTXO, but I believe it's ok to test it during normal coinjoin testing...
