### ISSUE TITLE
Dev dependancy issue with bytebuffer while implementing NextJS v13.4 App/ Directory

### ISSUE THREAD

**Issue by Seranged** [trezor/trezor-suite#8396]
**Describe the bug**
Recently have been upgrading to NextJS's new App/ directory router with v13.4
While utilizing the Pages directory, this was not an issue. 

NextJS v13.4 (Page directory) (No Issue)
NextJS v13.1 (Page directory) (No Issue)
NextJS v13.4 (App directory) (Issue)
NextJS v13.1 (App directory) (Issue)

**Info:**

-   Suite Version: web
-   Browser: Chrome/Version 112.0.5615.137 (Official Build) (arm64)
-   OS: macOS Monterey, V12.5.1

**Reproduction**

I have recreated the issue in this bootstrap repo branch:
https://github.com/Seranged/EVM-FE-Bootstrap/tree/trezor-nextjs-issue-reproduction

1. yarn install
2. yarn dev
3. terminal says:

 warn ./node_modules/bytebuffer/dist/bytebuffer-node.js
Module not found: Can't resolve 'memcpy' in '/GitHub/EVM-bootstrap/node_modules/bytebuffer/dist'

Import trace for requested module:
./node_modules/bytebuffer/dist/bytebuffer-node.js
./node_modules/@trezor/transport/lib/lowlevel/receive.js
./node_modules/@trezor/transport/lib/bridge/v2.js
./node_modules/@trezor/transport/lib/index.js
./node_modules/@trezor/connect/lib/data/config.js
./node_modules/@trezor/connect-web/lib/index.js
./src/app/layout.tsx

**Expected behavior**
There shouldn't be a dev dependency issue, I think it's to do with how the Trezor dev dependencies are working in combination with the new NextJS App directory, as the exact same repo but utilizing the Page/ directory works perfectly fine.

**Screenshots**
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/80223622/236628800-a6f34de8-e46c-46f1-8282-ddb3fd7dbe6d.png">

**Comment by sime** [comment]
Looks related to https://github.com/trezor/trezor-suite/issues/7944

**Comment by Seranged** [comment]
@sime 

Tried replicating your suggestion in #7944 

1. Checked that memcpy or bytesbuffer is not in package.json
2. Ran `rm -rf node_modules`
3. Ran `yarn install`
4. Ran `yarn dev`
5. Issue still persists (screenshot)

This issue is also associated with   `"@trezor/connect-web": "^9.0.8"` and not `@trezor/connect`

<img width="1000" alt="image" src="https://github.com/trezor/trezor-suite/assets/80223622/e9146d87-8ad6-4e8a-97fd-4562b5ec37c0">

**Comment by Seranged** [comment]
Furthermore, similarly to #7944,

`Additional context
I received an additional warning regarding [encoding](https://github.com/andris9/encoding#readme) dependency missing. Was able to install which resolved the warning`

Which works fine when installed as its own dependency inside this front-end repository
