### ISSUE TITLE
Wallet is not aware of it's own CJ

### ISSUE THREAD

**Issue by Transisto** [trezor/trezor-suite#8398]
The wallet participates into valid coinjoin but the wallet isn't made aware of it.

It's trying to re-register these same unconfirmed into next CJ

**Comment by hynek-jina** [comment]
Thank you @Transisto for your issue.
It should be solved by this https://github.com/trezor/trezor-suite/issues/8344

**Comment by Transisto** [comment]
This is different because the wallet already had the transaction, it signed
it.

**Comment by hynek-jina** [comment]
The above mentioned solve both problems.. but we will consider the work on your proposal too.

**Comment by hynek-jina** [comment]
Should be solved.
@trezor/qa please double-check

**Comment by bosomt** [comment]
**QA OK**

Already checked and deployed see https://github.com/trezor/trezor-suite/issues/8344
