### ISSUE TITLE
COINJOIN TRANSACTION LOST, CAN FIND MY FUNDS OR TX ID & hash 

### ISSUE THREAD

**Issue by chakam9** [trezor/trezor-suite#8403]
Hi, im really concern about this i need some help

I use the coinjoin service, i canceled because it tooks 40hours, then i send my btc to another wallet, i got the tx id and everything seems fine, but it nevers confirmed my btc didnt arrive, 48 hours later i go and check and the tx is dropped from the mempool, and i didnt get my btc back on my coinjoin wallet,

*** this is my coinjoin adress
*** this is the wallet where i was sending the btc to

this is the tx id when i send my funds to my other wallet ***

This is my coinjoin tx id transaction ( privatizing ) ***

3 days unconfirmed and dropped also

This is the second coinjoin transaction that shows ***

Its still on pending

_ERror coinjoin not available_

**Comment by hynek-jina** [comment]
Hi @chakam9,
thank you for your report.

Bitcoin fees have currently risen to unusually high levels. As a result, many transactions have been waiting in the mempool for several days. As a result of the large number of transactions, some of them are temporarily invisible, causing further problems.

Therefore, we have decided to temporarily suspend coinjoin. I understand this is inconvenient and I apologize for this. I assure you that you will not lose your funds. It will just take a few days for everything to return to the correct state and for your funds to be displayed correctly.

- Please don’t share anywhere your addresses, it harms your privacy.
- It is recommended to keep your funds on the coinjoin account. If you simply withdraw them to another account you can again harm your privacy.


I'm closing this issue and we will track the progress here: https://github.com/trezor/trezor-suite/issues/8344

**Comment by chakam9** [comment]
Hi Jena as you see on my post y already move the funds my money it’s on the nowhere and no that you turn off coin join I can’t even watch my tx ids !! I don’t have the money on my conjoin account that’s the problem!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hynek-jina** [comment]
Please use https://trezor.io/support 
My colleagues will help you to find your funds.

**Comment by chakam9** [comment]
It’s not this the support?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hynek-jina** [comment]
No, GitHub is for tracking the issues regarding the development and everything is visible. That can harm your privacy during the potential debugging.
