### ISSUE TITLE
Crypto price visible on asset detail

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8408]
As a user I would like to see the price of crypto on asset detail page in order to be able to make decision whether to buy / sell / receive / send.

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=14455%3A108463&t=JOLVKyyKfmWgzG6I-1

Acceptance criteria:
When user goes on asset detail, he can see the price of related coin

**Comment by bosomt** [comment]
**QA OK**

tested on Android dev version 23.5.1 (433)
