### ISSUE TITLE
Receive [EPIC]

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#841]
- [x] Previous addresses closed #1101
- [x] Previous address open #1100 
- [x] Check address #1099

**Comment by ZdenekSL** [comment]
@matejzak We think there should be an option to copy the old used address.

**Comment by glacierbits** [comment]
Modal is waiting for review.

**Comment by glacierbits** [comment]
Merged via #1154

**Comment by bosomt** [comment]
I'm still missing X button to close dialogue :(

![image](https://user-images.githubusercontent.com/31506317/74415523-d31eae00-4e43-11ea-9fe9-15dcec4f508d.png)
