### ISSUE TITLE
Trezor Connect (API) - can create Legacy Segwit Testnet (2-) addresses?

### ISSUE THREAD

**Issue by 7-of-9** [trezor/trezor-suite#8424]
Hi all,

I'm porting an existing wallet to use Trezor HW signing; it uses Legacy Segwit addreses (3-addr's for mainnet, 2-addr's for testnet).

I can see that Trezor Connect `getAddress()` returns 3-addr's if I pass `scriptType: SPENDP2SHWITNESS`... is there any way I can get equivalent testnet 2-addr's out of the Trezor? 

Thank you,
D.

**Comment by sime** [comment]
This might help: https://connect.trezor.io/9/#/method/getAddress

```
TrezorConnect.getAddress({
  "path": "m/49'/1'/0'/0/0",
  "coin": "test",
  "showOnTrezor": true
});
```
