### ISSUE TITLE
Hide token balance whilst in discreet mode

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#8429]
Original source: https://forum.trezor.io/t/trezor-suite-discreet-mode-issue/12396

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/trezor/trezor-suite/assets/31506317/db6d610d-1a1d-4a45-ae6b-7b41730e105a)



**Info:**
 - Suite version: web 23.7.0 (92eae50f69f2f11232db8be28d14c15a9a8110c5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/114.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.6.1 Universal (revision c3f6e8f19fd647c73b414322e287ba23cf8a0c7c)
 - Transport: BridgeTransport 2.0.33
