### ISSUE TITLE
[Wallet] Sign & Verify

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#843]
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f363b71b411bf68115e

**Comment by ZdenekSL** [comment]
How we would communicate success or failure?

**Comment by glacierbits** [comment]
All possible notifications (incl. successes and failures) need to be analyzed and designed first.
WIP: https://www.notion.so/satoshilabs/1d622e7079c14f64a03fa17f50bce14f?v=7e094ac0e0524a8983133a3f07b850b2

**Comment by tsusanka** [comment]
@matejzak maybe this is a duplicate of #2854?

**Comment by mroz22** [comment]
it is
