### ISSUE TITLE
Address poisoning attack: Label unverified token transactions in TX detail

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8434]
Related to preventions done by Desktop Suite: https://github.com/trezor/trezor-suite/issues/8119

BACKGROUND
Related to https://github.com/trezor/trezor-suite/issues/7278

Scammers employ a similar logic to that of zero-value transactions by utilizing unverified tokens that hold no fiat value but still carry a positive number of units in the transaction.

Example of the token: https://etherscan.io/token/0x8744dab2fa43055130a85c70d6b0676a82ae4704
Transaction example: https://etherscan.io/tx/0xfd7788d4ac55a9b1024d39a5d124f9e2012fc2dca197daa10c12e178d50b26ec

PROPOSED CHANGES
Check the token contract address against Ethereum definitions
If the contract address is not in Ethereum definitions label tx in the tx history
Design remains as it is

**Comment by sime** [comment]
@matejkriz Do we have the logic on mobile for this detection?

**Comment by vytick** [comment]
@sime We utilise `isZeroValuePhishing` from suite-common for txn labeling. Afaik nothing else

**Comment by matejkriz** [comment]
This is about integrating tokens definitions redux from this https://github.com/trezor/trezor-suite/pull/10034 to suite-native  and replacing isZeroValuPhishing by more general isPhishingTransaction.
