### ISSUE TITLE
Missing sent transaction notifications

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#8459]
**Describe the bug**
Missing sent transaction notifications in `All activity/Notification` section in latest staging version compared with latest production

**Steps to reproduce:**
1. Load wallet with funds in latest 23.5.1 version
2. Send transaction outside loaded accounts
3. Try to find info about sent transaction in `All activity/Notification` section

**Info:**
 - Suite version: web 23.5.1 (f0d64a3661bf54493cda1528cbbb5caaf68168b7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/113.0
 - OS: MacIntel
 - Screen: 2160x1350
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

**23.5.1**

<img width="373" alt="Screenshot 2023-05-14 at 11 55 08" src="https://github.com/trezor/trezor-suite/assets/31506317/7be0774e-3767-4209-824c-a0b6e94c6859">

https://github.com/trezor/trezor-suite/assets/31506317/15d0d2e8-c15d-4829-99d6-31cf4a4940aa

**23.4.1**

<img width="326" alt="Screenshot 2023-05-14 at 11 53 36" src="https://github.com/trezor/trezor-suite/assets/31506317/4d861914-4369-40d1-a754-56a1860db0ff">

https://github.com/trezor/trezor-suite/assets/31506317/b5316c3f-033b-4934-9e52-8035ccc16b63

**Comment by bosomt** [comment]
probably related 
1tx 3 notifications

https://cexplorer.io/tx/b124dca077386c42db8be4f393501677f7e5f23e3c085b6879703c797b6c812f

<img width="575" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/f9f24664-c489-43a3-b101-34b80bdd571f">


<img width="839" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/3e01bea2-8acf-4416-b9e9-1f36229343c2">

**Comment by tomasklim** [comment]
TK OK:
Just tested RC and my branch and it looks good. No problem at all.

<img width="507" alt="Screenshot 2023-05-16 at 13 02 14" src="https://github.com/trezor/trezor-suite/assets/33235762/ec737577-48a0-4367-8eb2-253125d02209">

**Comment by tomasklim** [comment]
<img width="801" alt="Screenshot 2023-05-16 at 13 25 06" src="https://github.com/trezor/trezor-suite/assets/33235762/aa91c4bc-eea2-46ff-89ef-4cdbbfe1a254">
<img width="772" alt="Screenshot 2023-05-16 at 13 25 41" src="https://github.com/trezor/trezor-suite/assets/33235762/f0c05362-4570-40a6-996d-b0c72fddb074">

same outputs to same address, no problem

**Comment by bosomt** [comment]
multiple notifications are not appearing anymore after app reset, 🎉 
as soon i replicate issue i will document and create separate one

**Comment by komret** [comment]
Now when I get the notification after the fix in https://github.com/trezor/trezor-suite/pull/8487, the notification is marked as read from the start, that is probably not expected?

Sending to my other account - receive notification is unread, send notification is read, although I get both of them at the same time.
![Screenshot 2023-05-16 at 14 04 31](https://github.com/trezor/trezor-suite/assets/42465546/59b39e7d-a16b-4b41-afd6-71fb0cf3b029)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 23.5.2 (c7bd95bbdf78e4944d45037f4cbff70fa66ea4a6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.5.2 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
