### ISSUE TITLE
Device Settings

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#846]
Device Settings: https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa2101006745990e37c943

Change PIN in separate issue #1230

**Comment by ZdenekSL** [comment]
@matejzak We need modal design for each option in the settings.

**Comment by ZdenekSL** [comment]
@matejzak I think we missed the "Change PIN" feature. In the current wallet, we have this under Basic settings. We have 2 states when the pin is not enabled, you can enable it and it will call the Trezor, you will confirm it and you set the pin on the device. Once you have the PIN, you can change it in Basic settings and disable it in advanced settings.

**Comment by bosomt** [comment]
we are still missing change PIN feature and 
upload image button is not working and
dropbox button is not working

**Comment by wendys-cats** [comment]
@bosomt all these things are in separate issues - Change PIN feature #1230 in this release, Custom Homescreen and Dropbox button both in the next release.

**Comment by mroz22** [comment]
- dropbox does not belong to device settings
- upload image imho works for model T, for model one button is hidden.
- change pin feature does not have design, so now it works turn off -> turn on agaion = change

**Comment by sorooris** [comment]
Please specify the PIN mismatch design, then it'll be properly tested.

**Comment by wendys-cats** [comment]
**Issue**
Suite allows user to change device settings for a disconnected device

**Steps to reproduce**
1. Connect one device and apply Remember wallet
2. Connet second device (preferably a different model than the first one)
3. Disconnect the first device
4. Go into wallet of the first device
5. Click on the Settings, then choose Device Settings in the sub-menu

**Expected**
Suite will not let the user change (or attempt to change) settings on a device that is disconnected. 

**Actual** 
This scenario (in Steps to reproduce) will result in mismatch of what suite is showing the user. If user tries to change anything (PIN, Device Label, Homescreen, Display rotation,...), suite will make the changes on any device that is currently plugged in and connected, even if it is a different model. Some of the results is a "byte overflow" error given when changing homescreen on a disconnected TT device if the connected device is T1 (expected).
