### ISSUE TITLE
[Suite] Dashboard Settings

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#847]
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f839e5f0c1b944050be

**Comment by ZdenekSL** [comment]
@matejzak Is there really need to have different primary crypto and fiat per app? We think this should be global for the whole Suite.

**Comment by glacierbits** [comment]
@ZdenekSL Right you are. We were aware of this particular issue, failed to update the proposal, our apologies. Updated now: Primary fiat in General settings + no such option in Dashboard. Primary crypto in the discovery process.

**Comment by mroz22** [comment]
Is this still valid? Havent seen dashboard settings designs for a while?

**Comment by ZdenekSL** [comment]
@matejzak Are there any dashboard specific settings?

**Comment by glacierbits** [comment]
@ZdenekSL No sir. The only remaining settings after the recent iterations are: 
General, Device, Coins (i.e. we don't have Wallet settings either - for now at least)

**Comment by ZdenekSL** [comment]
Closed as deprecated
