### ISSUE TITLE
Independent coinjoin account discovery

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8473]
In the current version we use blockfilters obtained from the coordinator. In case the coordinator is not working, users would not get their coinjoin account balance easily.

**Comment by STew790** [comment]
**QA OK**
Discovery of the CJ account was OK. I was able to get into a round and complete a CJ. Pending transaction of CJ was shown as well correctly, even when a round failed.

**Info:**
 - Suite version: desktop 23.9.1 (4310819f047d4341d2a86c422d65de447e99dd17)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.9.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
