### ISSUE TITLE
Update analytics symbol to contract

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#8476]
In https://github.com/trezor/trezor-suite/pull/8426 we ERC20 tokens filtering from `ethereumSymbol` to `contract`. Agreed with analytics team that this change should be reflected to analytics as well.

Replace `tokenSymbol` with `contract` in analytics payloads to reflect Notion analytics spec.

**Comment by PeKne** [comment]
Implementation: 

Leave the symbol as it is and add the contract:
```
{
  assetSymbol: 'eth',
  tokenSymbol: 'usdt',
  tokenContract: '0xdac17f958d2ee523a2206206994597c13d831ec7'
}
```
   in case there would be more tokens included in the event, the tokes data would be two ordered arrays:
```
{
  assetSymbol: 'eth',
  tokenSymbols: ['usdt', 'shib', ...],
  tokenContracts: '['0xdac17f958d2ee523a2206206994597c13d831ec7', ''0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce, ...]
}
```
(in this case, the first contract is equal to usdt, the following one to shib )

**Comment by vytick** [comment]
Will we use this for Solana as well? If so I suggest to use different naming, because there are no contracts but mints.
 
Possible change:
 
`tokenContract` -> `tokenAddress`

**Comment by PeKne** [comment]
I would leave it to `tokenContract` for now for consistency. When will be Solana introduced in native code, we will have to rework/rename this in many parts of the code anyway. So I will not take care of this now. This should be designed thoroughly later when we will implement another chains with token support.

**Comment by vytick** [comment]
It is contract address for ethereum. So it will be consistent anyway and also work with mint address for solana. 

There wont be a reason to rework it and it would make sense then as it would make now.

**Comment by vytick** [comment]
Also I think that using singular would only add more work on the other side, where consument would have to make two queries (or variants) insted of one. There still can be `tokenSymbols: ['usdt'],`. I dont see the benefit of singular option, but maybe there is one.

What do you think?
