### ISSUE TITLE
Portfolio graph does not work with imported testnet asset

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#8481]
Current behaviour:
If there is any testnet account imported, then the portfolio graph shows a zero balance and error message.

Expected behaviour:
The testnet does not affects the portfolio graph at all and it shows balance of other imported assets.

## Screenshot of the bug
![Image](https://user-images.githubusercontent.com/26143964/238347099-3006ad28-7322-460c-b062-3fc3d5209257.png)

**Comment by bosomt** [comment]
Account detail looks as expected.
Overall `Home` graph is not rendered properly / not disabled when only testnet coins enabled/

Tested in 23.5.1 (425) on Android os

![Screenshot_20230524_112040_Dev-TrezorSuite](https://github.com/trezor/trezor-suite/assets/31506317/f34838e9-b330-437c-9d3a-ef8a26b3e091)


![Screenshot_20230524_112023_Dev-TrezorSuite](https://github.com/trezor/trezor-suite/assets/31506317/544ae335-6dca-4b26-9e22-336517aff597)

**Comment by PeKne** [comment]
@mnuky How should the graph look if there is no other asset imported than a testnet?

**Comment by PeKne** [comment]
@bosomt The issue was fixed with https://github.com/trezor/trezor-suite/pull/8587. If only testnet accounts are imported, the graph shows an error message now.

Please test again.

**Comment by bosomt** [comment]
**QA NOK**


no idea what happened buy latest dev version 430 is now showing graphl loading and fiat value of test account ;)

![image](https://github.com/trezor/trezor-suite/assets/31506317/3e052e7d-f3fd-48c5-bcf8-882b4f48bdb6)

**Comment by bosomt** [comment]
**QA OK**

tested on Android dev version 23.5.1 (433)
