### ISSUE TITLE
Internal ETH transactions are visible in list of transactions

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8482]
As a user I would like to see also internal transactions within the app otherwise I'm super stressed not to see them and worried that I've lost some funds. 

Implementation - it should be pretty easy to do so - for implementation detail get in touch with @tomasklim

**Acceptance criteria:**
Internal ETH transactions are visible in the app

**Comment by PeKne** [comment]
## Implementation proposal:
We could reuse the idea from the desktop Suite and display internal and (potentially also) ERC20 transactions in the transaction `Inputs & Outputs` detail sheet. 

### Current UI for desktop suite:


![Image](https://github.com/trezor/trezor-suite/assets/26143964/d2c8b68c-dd7e-4e7d-8ee3-570e96760c8c)

### Current UI for mobile app:


![Image](https://github.com/trezor/trezor-suite/assets/26143964/b2eed176-6e5f-4983-8b26-60bd9cffd1c5)

### Acceptance criteria
- In the Inputs & Outputs transaction detail are Internal transactions and ERC20 token transactions visible


@mnuky please let me know what you think

**Comment by bosomt** [comment]
**QA OK**

i see this tx including internal trancaction detials

68888d6 - [develop] - feat(suite-native): internal transaction detail (#8927)

Internal and token transfers added to the transaction detail `Inputs & Outputs` sheet.

https://eth1.trezor.io/tx/0x9dc9b9c884aad768328f28e8194f1f86121f6c2a1742fa817c33bcc2f3b7aa3c



![Image](https://github.com/trezor/trezor-suite/assets/31506317/2b7c3a4e-19d9-4f35-b753-e64ee7804743)
