### ISSUE TITLE
Change the app icon for iOS

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8488]
![Image](https://github.com/trezor/trezor-suite/assets/84183817/397eb507-4691-4a19-a8d0-452e61a24f6d)

We use wrong "green" colour for app icon on iOS - the right one: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=17265%3A76029&t=cRnafaeasMhJe0R8-1

DEV: 
![Image](https://github.com/trezor/trezor-suite/assets/84183817/8efd8f50-4971-47d2-91ed-3bb4564f31a6)

Stage:
![Image](https://github.com/trezor/trezor-suite/assets/84183817/20976778-5ab1-4824-88a9-814735ab0d86)

Local: 
![Image](https://github.com/trezor/trezor-suite/assets/84183817/d7321ede-4c4a-45cc-8dad-7e758b44722a)

plus fix the issue with the right format of the icon: https://github.com/trezor/trezor-suite/issues/8474

**Comment by juriczech** [comment]
@mnuky The icon is in incorrect format. It shouldn't have round edges. Can you please update the icon?

**Comment by juriczech** [comment]
It would be best to update other icons (staging, develop) as well to have that all correct. Plus it would be easier to test as we can verify that it functions on develop.
