### ISSUE TITLE
Firmware hash check every time the device is plugged in

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8489]
Currently we have in debug menu hidden possibility to check FW authenticity but it requires downloading the binary, that is why it's not enabled by default.

https://satoshilabs.slack.com/archives/C03D2GGJ8G0/p1684221988914369 
An idea of how to do the firmware hash check every time the device is plugged in, without having to keep a downloaded version of the firmware:

- Every day our backend will generate a random challenge and compute the firmware hash for each firmware version released after May 2022 (older ones don't support the feature).
- The challenge and the list of firmware versions and hashes will be placed in something similar to current secure messaging system.
- Suite will use the challenge from there to execute a firmware hash every time the device is plugged in and it will compare the result with the reference result.

Both the challenge and the responses can be truncated to small values. For example as little as 4 bytes for the random challenge and the first 2 bytes for the hash result seems acceptable. (We can double these numbers just to be on the safe side.)

**Comment by andrewkozlik** [comment]
Firmware versions that are strictly older than 1.11.1 and 2.5.1 don't support the firmware hashing feature. In case of firmware versions that are older than these, Suite should strongly encourage the user to update to the latest firmware version. If they choose not to, then Suite should either restrict functionality by going into compromised device mode or it should at least warn the user that they are continuing at their own risk.

**Comment by bosomt** [comment]
**QA OK**

https://www.notion.so/satoshilabs/FW-hash-check-on-T1-upon-connection-11fdc526060680abb931f19c28076e2d#11fdc526060681bb9909c1f62d08c2ab
