### ISSUE TITLE
[Suite] Coin settings

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#849]
Coins Settings: https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f86f01928120a0b1bbb
Testnet Coins:
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f891898121f8d1c8126
Advanced Coin Settings:
#913

**Comment by mroz22** [comment]
done. except search which has separate issue now https://github.com/trezor/trezor-suite/issues/1057
