### ISSUE TITLE
hidden XPUB overflows on the Show XPUB screen

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#8494]
## Description
On small devices, the XPUB overflows and part of it is visible even if it should not. 

<image width="250" src="https://user-images.githubusercontent.com/26143964/238682034-1e0d7b05-8a5e-4ee4-aa7b-591c195ba23b.png"/>

## Proposed solution:
Do not render XPUB before the user clicks on the `Show public key` button.

**Comment by bosomt** [comment]
**QA OK**

tested on Android Samsung A50 v 23.5.1 (429)
