### ISSUE TITLE
Full network fees for a CJ are shown as if they were debited from our balance.

### ISSUE THREAD

**Issue by Transisto** [trezor/trezor-suite#8495]
![image](https://github.com/trezor/trezor-suite/assets/388716/87be31c3-0875-4ae8-b27b-57525b15351e)

**Comment by hynek-jina** [comment]
I have to confirm this bug:

## Version 23.4.2 - Correct
<img width="1404" alt="Snímek obrazovky 2023-05-17 v 5 22 11" src="https://github.com/trezor/trezor-suite/assets/26002916/5a7cb008-ce25-4bc2-bc26-75771a2cd439">

## Version 23.5.1 - False
<img width="1404" alt="Snímek obrazovky 2023-05-17 v 5 26 55" src="https://github.com/trezor/trezor-suite/assets/26002916/bc7a5f06-fa15-493f-b380-06540cab02b0">

**Comment by hynek-jina** [comment]
**QA OK**
