### ISSUE TITLE
Unconfirmed transactions show wrong date/blockHeight when exported

### ISSUE THREAD

**Issue by MatthewDavid1984** [trezor/trezor-suite#8496]
**Describe the bug**
Unconfirmed transactions show a Timestamp of "", a Date of 1/1/1970, and/or a blockHeight of -1 in exports.

[account_test_20230517T095559.pdf](https://github.com/trezor/trezor-suite/files/11494658/account_test_20230517T095559.pdf)

[account_test_20230517T095746.csv](https://github.com/trezor/trezor-suite/files/11494677/account_test_20230517T095746.csv)

![blockHeight -1](https://github.com/trezor/trezor-suite/assets/121948710/00bdd1ef-e417-4cad-9454-58c2aa947940)
0230517T095746.csv)

**Info:**
 - Suite version: desktop 23.5.2 (c7bd95bbdf78e4944d45037f4cbff70fa66ea4a6)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.5.2 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Win32
 - Screen: 1366x768
 - Device: model 1 1.12.1 Universal (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
Transactions should show valid values in the Timestamp, Date, and blockHeight fields when exported.

**Comment by sime** [comment]
The definition of valid timestamp, date and blockheight is empty string in this case. As the arrival datetime of a TX in the mempool is not universal.

**Comment by sime** [comment]
Solution: Do not include unconfirmed transactions in exports

**Comment by bosomt** [comment]
**QA OK**

pending transactions are gone



**Info:**
 - Suite version: desktop 23.7.0 (d81e7e2a7c127bc4e494b69375831cd4b0998bd8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.7.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.1 Universal (revision c3f6e8f19fd647c73b414322e287ba23cf8a0c7c)
 - Transport: NodeUsbTransport
