### ISSUE TITLE
Drop outdated pending transactions

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8499]
Pending transactions might remain visible in transaction history even if they are invalidated.
As an example see: https://www.blockchain.com/explorer/transactions/btc/bcc19b06329d79b7261d0ee9067d519d213a60666b7f7cbe56d3f7995967c014
- it is not visible in other mempools

**Comment by jooray** [comment]
...and then coinjoin tries to submit them for a round and fails, even though the transactions never confirm.

Either a button to rescan for all transactions would be great, or make sure that the pending transactions are still valid.

**Comment by bosomt** [comment]
Already tested and confirmed by Szymon
