### ISSUE TITLE
[Wallet] Passphrase modal

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#850]
Passphrase first screen:https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6fd7b175671f3f031ded

Passphrase second screen:https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6fd648727c1fb11cf9d8

**Comment by ZdenekSL** [comment]
I think we need some fail state design

**Comment by slowbackspace** [comment]
flowchart (remember device->passphrase->...) https://miro.com/app/board/o9J_kwng2E0=/?moveToWidget=3074457347030604004

**Comment by ZdenekSL** [comment]
@matejzak we agreed with the development team that this logic doesn't make sense. There should be one modal for entering passphrase. Let's brainstorm together.

**Comment by glacierbits** [comment]
Duplicity.
