### ISSUE TITLE
(Continued/Reopened) #8396 'Module not found: Can't resolve 'memcpy'/ 'encoding' in @trezor/connect-web'

### ISSUE THREAD

**Issue by Seranged** [trezor/trezor-suite#8506]
Hi, @mroz22 (and whoever else may be concerned). This is a reopening of an issue from [#8396](https://github.com/trezor/trezor-suite/issues/8396), @mroz22's PR to attempt to fix the issue is [here](https://github.com/trezor/trezor-suite/pull/8421)

I just updated the dependencies to "@trezor/connect-web": "^9.0.10", which I think has the bugfix @mroz22 implemented last week, and am still having the issue described above.

Recreated in this branch: https://github.com/Seranged/EVM-FE-Bootstrap/tree/trezor-nextjs-issue-reproduction

Ran rm -rf node_modules
Ran yarn install
Ran yarn dev
Error in the terminal is provided below
Module not found: Can't resolve 'memcpy' in '/EVM-bootstrap/node_modules/bytebuffer/dist'

Import trace for requested module:
./node_modules/bytebuffer/dist/bytebuffer-node.js
./node_modules/@trezor/transport/lib/lowlevel/receive.js
./node_modules/@trezor/transport/lib/bridge/v2.js
./node_modules/@trezor/transport/lib/index.js
./node_modules/@trezor/connect/lib/device/DeviceList.js
./node_modules/@trezor/connect/lib/core/index.js
./node_modules/@trezor/connect/lib/index.js
./node_modules/@trezor/connect-web/lib/iframe/index.js
./node_modules/@trezor/connect-web/lib/index.js
./src/app/layout.tsx

./node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/EVM-bootstrap/node_modules/node-fetch/lib'

Import trace for requested module:
./node_modules/node-fetch/lib/index.js
./node_modules/cross-fetch/dist/node-ponyfill.js
./node_modules/@trezor/connect/lib/device/DeviceList.js
./node_modules/@trezor/connect/lib/core/index.js
./node_modules/@trezor/connect/lib/index.js
./node_modules/@trezor/connect-web/lib/iframe/index.js
./node_modules/@trezor/connect-web/lib/index.js
./src/app/layout.tsx
(node:43143) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use node --trace-deprecation ... to show where the warning was created)

**Comment by mroz22** [comment]
@Seranged plesase check it now, 9.0.11 version has been just released

**Comment by Seranged** [comment]
Hi @mroz22, ok, so, it seems as if the issue regarding: 

`Module not found: Can't resolve 'memcpy'`  is fixed! - No error.

But 

`Module not found: Can't resolve 'encoding'`

Is still having the issue (screenshot below). 

I can manually install `encoding` and it removes the error entirely, which will solve all of my issues locally. But still, perhaps you guys would want to remove this dependency error on your side as well. 

Thanks for the help.

---

1. Ran rm -rf node_modules
2. Ran yarn install
3. Ran yarn dev

Screenshot provided:

<img width="767" alt="image" src="https://github.com/trezor/trezor-suite/assets/80223622/f357aa83-48a5-4ae8-a7e1-33ab598a824b">

**Comment by Seranged** [comment]
It seems as though the `encoding`  and `memcpy` issues have been resolved with Trezor in this release! Ty @mroz22 !

A few other dependencies (walletConnect and WAGMI) (screenshot attached) are also having this issue with `encoding`, so I will open issues with those guys.

Thank you for the help!

<img width="805" alt="image" src="https://github.com/trezor/trezor-suite/assets/80223622/ea4470b3-fcc5-44fd-bbb8-7c7550b8eab6">
