### ISSUE TITLE
Missing history/funds in CoinJoin account after reloading Bitcoin as used coin (v23.5.1 pre-release)

### ISSUE THREAD

**Issue by kravens** [trezor/trezor-suite#8525]
**Describe the bug**
I have received BTC in an address from the Coinjoin account on a Trezor Model T, joined a few coinjoins with it and reached 100% privacy level.
After that I accidentally deselected Bitcoin as used coin in Trezor Suite, and had to resync the Bitcoin account balances in the wallet. So I re-enabled the Coinjoin account and to my surprise found the history to be incomplete and the privacy tab showing an error.

**Info:**

-   Remembered Wallet: yes
-   Suite Version: v23.5.1 pre-release
-   Browser: -
-   OS: W11
-   Backend: Tried both Trezor servers over Tor and Electrum Rust Server on personal node
-   Firmware Version: Model T, 2.6.0 bitcoin-only

**How to reproduce**

1. Go to Accounts
2. Add Coinjoin account type
3. Use Coinjoin account to receive and Coinjoin until 100% privacy (I used default coinjoin settings here)
4. Go to Settings -> Crypto
5. Uncheck Bitcoin as active coin
6. Re-check Bitcoin as active coin again
7. Go to Accounts
8. Re-add Coinjoin account type
9. See Error and missing history/balance in account

**Expected behavior**
I expect to see the full balance and correct history of each used address in the account.
Instead I got to see only ~3/4 of my bitcoin balance and missing Coinjoined UTXO, together with an error in the Privacy tab.

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/9646902/c7a1795e-7940-4860-b5d6-68a30a8e039b)
incorrect value of total received on my address:
![image](https://github.com/trezor/trezor-suite/assets/9646902/d527bc8e-770a-46fb-86e9-691387199452)
should have been > 1000000 sats

**Additional context**
Using a different software I checked the history and balances of the xpub on derivation path m/10025'/0'/0'/1'
Here I did see my complete balance and correct history show up, matching the earlier balance on Trezor Suite before my error triggered this bug.

**Comment by Hannsek** [comment]
@trezor/qa Can you reproduce this?

**Comment by hynek-jina** [comment]
I wasn't able to reproduce the issue. 

@kravens Could you please have a look if you have received funds first at your first address? 🙏

**Comment by kravens** [comment]
I believe the first confirmed funds arrived in address 3, as address 1 and 2 were self-transfers with a very low fee that dropped out of the Trezor Server mempool. Also funds to address 3 were sent by a miningpool and included in block 789042 with 0 sat fee.

**Comment by hynek-jina** [comment]
Ok,
that it is the issue 😞 We have implemented this: https://github.com/trezor/trezor-suite/issues/7633
Meaning that you have to use your first address first.. It labels the moment for further account synchronisation.

So please do the following steps:
- Download older [Trezor Suite 23.4.2](https://github.com/trezor/trezor-suite/releases/tag/v23.4.2)
- Re-run coinjoin account discovery
- Identify your first address (look into `Receive` tab)
- Check transaction history when was mined the one pointing to your first receive address
- Resend UTXOs mined before this moment to fresh address

**Comment by kravens** [comment]
Reverting back to 23.4.2 and rerunning coinjoin account discovery solved the missing funds issue indeed 💯 
Hope there is a good fix for this soon in a next version.

**Comment by kravens** [comment]
![image](https://github.com/trezor/trezor-suite/assets/9646902/2a1cc7df-9d66-4e9f-8bad-94bdee2661ad)
After sending the coins out in v23.4.2 and updating to the latest release, the account balance is again bugged.
