### ISSUE TITLE
Amounts in accounts tab in discrete mode behaves incorectly when scrolling

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#8529]
**Describe the bug**
Amounts in accounts tab in discrete mode behaves incorectly when scrolling

**Info:**

-   Suite Version: 23.5.1
-   OS: macOS Ventura 13.3.1 (a)
-   Firmware Version: 2.6.0

**How to reproduce**

1. turn on discrete mode
2. scroll down the account tab (the accounts will go up)
3. See that the blurred numbers are "behind" the `DEFAULT ACCOUNT` text.

**Expected behavior**
Blurred numbers should "hide" at same point as the names of the accounts.

**Screenshots**

https://github.com/trezor/trezor-suite/assets/57008159/214d61a3-cfb6-4dc8-b783-6d8d89c84024

**Side note**
The priority of this is probably lower than the lowest one.

**Comment by komret** [comment]
Resolved during Empower redesign:

https://github.com/user-attachments/assets/85ed252c-e1da-41e4-8566-f8cb0229a2da

**Comment by bosomt** [comment]
**QA OK**

im not able to reproduce it anymore

**Info:**
 - Suite version: desktop 24.7.2 (3282fe8f6f491e024c0cc9cae99f3085c229c96c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33
