### ISSUE TITLE
Suite crashing after click on Show log

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8530]
![image_720](https://github.com/trezor/trezor-suite/assets/26002916/5957f804-2952-49f2-8d44-4ca7864d5911)

**Comment by kravens** [comment]
For me this only happened once, not sure how to reproduce it myself.

**Comment by bosomt** [comment]
I was not able to reproduce it it in 
23.5.2 browser Google Chrome device connected via webUSB
23.6.1 app connected device via bridge

**Comment by hynek-jina** [comment]
Let's close it for now since we are not able to reproduce the issue
