### ISSUE TITLE
Import LTC XPUB is not working

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8533]
Steps to reproduce:
Try to import LTC XPUB
App shows error

![Image](https://user-images.githubusercontent.com/84183817/239907271-bad1adc2-c1ae-4f06-8d0b-9071567bb6c6.PNG)

**Comment by juriczech** [comment]
Cannot reproduce this issue on develop build. Might be fixed already. Feel free to open the issue if the bug is there and if it is, we will need more info on how to reproduce.

**Comment by bosomt** [comment]
Can be related ? 
But i will get no error, account is imported but not present after import ;) 
https://github.com/trezor/trezor-suite/issues/8557

**Comment by juriczech** [comment]
@bosomt2 the other issue is reproducible on develop, I will have a look at what's happening
