### ISSUE TITLE
Accessibility font scaling brokes app layout

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8534]
The problem of broken formatting is caused by **Font scaling accessibility feature**. To enable usage of our app to users with such settings on we need to adjust our styling implementation.
### Implementation proposal
  - [x] Adjust font scaling of our Text and its prop `textVariant` to look appropriate relative to other rendered components
  - [x] Make sure that all the screens are scrollable and the upsized content does not overflow any of the screens
  - [x] Make all the Views that contain multiple inner Views to enable `flexWrap` to prevent overflow
  - [x] Upscale all our atom components  as `Toggle`, `Radio` `TextInput` etc. to also reflect the scaling
  - [ ] Adjust the implementation of Icon components to reflect the scaling (follow up issue [#8716](https://github.com/trezor/trezor-suite/issues/8716))

**Comment by PeKne** [comment]
Follow up issue [#8716](https://github.com/trezor/trezor-suite/issues/8716) created.

**Comment by bosomt** [comment]
**QA OK**


tested with high contrast and big fonts on both platforms

iOS version 304
And version 455

**Comment by bosomt** [comment]
Only "problem" i found that on both platforms app crashes when you change accessibility settings and apps is running.
Not sure if its worth follow up issue.
