### ISSUE TITLE
Send tab

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#854]
- [ ] Send Bitcoin
- [ ] Send Etherum
- [ ] Send Ripple
- [ ] Import csv
- [ ] RBF
- [ ] Advanced Forms
- [ ] Sign Modal
- [ ] op return
- [ ] More recepients in bitcoin

**Comment by glacierbits** [comment]
Duplicating _Epic_ level issue #1027 . Please continue there.
