### ISSUE TITLE
Check the presence of previous transacitons

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8541]
Make sure that Suite is having previous transactions to all users inputs used in users transactions.
If not:
- try to fetch missing pieces
- report error into sentry
- disable coinjoin
- don't calculate privacy for these "incomplete" transactions...

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
