### ISSUE TITLE
UTXO that are non-private all have a score of 1

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#8547]
When looking at coin selection I have 15 UTXO that are in the non-private section.

Problem is there's no way these would ALL be at score 1 while the average of Private coin is ~13 while aiming for 5.

There is something wrong with these UTXO that they NEVER get chosen for registration.

**Comment by hynek-jina** [comment]
Thank you @nostitos 
This issue should be solved by https://github.com/trezor/trezor-suite/issues/8394 (in progress)
