### ISSUE TITLE
Not able to import some LTC account types to Lite app

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#8557]
**Describe the bug**
Some account types of Litecoin are not imported.
Overall import looks as expected but they are not listed in `My assets` section
Tested on all seed standard accounts.
First two accounts are not imported and third one is imported

**Info:**

-   Suite Version: lite app Tested in 23.5.1 (425) on Android os
-   OS:Android

**How to reproduce**

1. Try to import provided XPUBs
2. Observe imported accounts after you finish import

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/31506317/60ea5247-1182-4f43-8137-9cad268e2a77)
![image](https://github.com/trezor/trezor-suite/assets/31506317/610b9ad3-3a57-43d1-9e92-2f7a1bfb93c0)
![image](https://github.com/trezor/trezor-suite/assets/31506317/d1a373d8-3374-4266-a812-c314104f73a6)

**Comment by bosomt** [comment]
Ltub2Y8PyEMWQVgiX4L4gVzU8PakBTQ2WBxFdS6tJARQeasUUfXmBut2jGShnQyD3jgyBf7mmvs5jPNgmgXad5J6M8a8FiZK78dbT21fYtTAC9a

zpub6qhzAgn63nQAJZiY829GUUb1eXFDqpLbeShTdAbTEKyZa8n2VbkLwbRhq9xqPyj5Yet5TBdbCZDgiw53NQ2qwib4mygybFq66i7ZcXUcwgU

**Comment by juriczech** [comment]
Should be partially resolved by https://github.com/trezor/trezor-suite/issues/8564

**Comment by bosomt** [comment]
**QA OK**


tested on dev version Android 23.6.1 (438)
