### ISSUE TITLE
Custom Electrum Server for Litecoin

### ISSUE THREAD

**Issue by goodc0re** [trezor/trezor-suite#8569]
While Trezor Suite offers three options for custom Bitcoin backends (Trezor, Custom Blockbook and Custom Electrum server), there are only two options for Litecoin backends, Trezor servers or Custom Blockbook server. 

Is there any reason for the Custom Electrum server option missing for Litecoin? It would be nice to be able to specify a custom Electrum or Fulcrum server for Litecoin.

**Comment by mroz22** [comment]
Hello @goodc0re I am afraid it is not on our roadmap at the moment. But maybe if you are willing to contribute... 😉

**Comment by sime** [comment]
Thanks for the issue @goodc0re we won't be on this issue anytime soon, so will close it for now.
