### ISSUE TITLE
Larger amounts cropped on graph

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#8571]
**Describe the bug**

Higher amounts get cropped on the right side of the screen. 

**Info:**
-   Suite Version: 23.5.1 (13) commit 6902cc4
-   OS: iPhone 13, iOS 16.4.1 (20E252)

**How to reproduce**

1. Launch app 
1. Get dough
1. Set to CZK
1. Observe

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/1835345/f2144698-7924-4622-92c5-f7868f2fb819)

**Comment by Hannsek** [comment]
Even on the left side.

**Comment by bosomt** [comment]
**QA OK**

d2efe78 - [develop] - fix(suite-native): event tooltip zero sum values (#8950)
