### ISSUE TITLE
UI polishing - shadows

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8573]
We should have a shadow behind the white boxes - see the comparisons of actual app and designs: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/branch/9ekR1zKZAnvteokURutvZ4/%5Bs2.0%5D-Mobile?type=design&node-id=18386%3A101695&t=gHvIG4FScRVHGpI6-1

Acceptance criteria:
- there is a right and bottom shadow behind the box components
- there is a right and bottom shadow behind the selected graph timeframe button components

**Comment by bosomt** [comment]
**QA OK**

bf64bce - [develop] - fix(suite-native): bottom sheet grabber (#9234)
