### ISSUE TITLE
UI polishing - overlays

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8576]
When there is any bottom sheet open, there should be nice background overlay:
![Image](https://user-images.githubusercontent.com/84183817/240845501-2b6d464e-0a2e-403e-baed-2dd033477872.png)

**Comment by mnuky** [comment]
@PeKne QA NOK - there is some strange pink background on all overlays - check the video and prinstcreen - iPhone 12

![Image](https://github.com/trezor/trezor-suite/assets/84183817/d7e6fa18-8ad1-4c89-baf6-97caaace906a)

![Image](https://github.com/trezor/trezor-suite/assets/84183817/2e3b1d59-5a21-45cd-9ad6-3c90705e0e42)

https://github.com/trezor/trezor-suite/assets/84183817/e3886a70-26a3-433f-9d03-3894bbc42b39

**Comment by bosomt** [comment]
**QA OK**

3abc6cf - [develop] - chore(suite-native): downgrade skia to v.0.1.202 (#9408)

**Comment by mnuky** [comment]
QA OK, iPhone 12 (app version 23.11.1. (373)
@bosomt can you please also test?

**Comment by bosomt** [comment]
**QA OK**

- iOS 23.11.1 (371) iPhone 11
- And 23.11.1 (568) Nothing phone 1 Android 13

only one nitpick
When you move modals you can see part of windows is not actually blurred.
Maybe we can consider to disable whole modal movement ?

https://github.com/trezor/trezor-suite/assets/31506317/dd42f360-7c97-4221-8800-fc505068dcac

**Comment by PeKne** [comment]
That is a bug, For some reason the blurred overlay does not cover whole screen on some Android devices. I am preparing and issues that will address this one and other overlay related bugs. Ignore it for now please :).
