### ISSUE TITLE
UI polishing - formatted account balance typography

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8585]
We have a wrong format for displaying the portfolio balance, the right format is as:
1. currency sign is smaller and has lighter grey color than amount
2. decimals are smaller and have lighter grey color

 **This design should be used in the following screens:**
- account import summary
- dashboard (home screen)
- account detail screen

![Image](https://user-images.githubusercontent.com/84183817/241147741-d8b73239-37d0-4cd4-b7b8-3a97273eb697.png)

**Comment by bosomt** [comment]
**QA OK**

3309f30 - [develop] - Feat\/blurred screen overlay (#9380)
