### ISSUE TITLE
UI broken in coinjoin privacy section and possibly on other places too

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8588]
**Describe the bug**
Layout of coinjoin Privacy section is broken (extra 8px margin on top of CoinjoinStatusWheel card) and possibly other places where Card component is used?

**Info:**

current `develop` - not released

**Screenshots**
<img width="644" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/9efd704a-157f-4759-91f1-1dddbc000fe0">
<img width="865" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/772faaea-aa92-459a-b165-6a05a0be7efd">

**Additional context**
this change broke it:
https://github.com/trezor/trezor-suite/blame/develop/packages/components/src/components/others/Card.tsx#L11

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 23.6.1 (bf8716e07436e942dd86517475e44ba5e6f4b10c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.6.1 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Bitcoin-only (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
