### ISSUE TITLE
Ledger Live derivation path in Suite

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#8591]
**Problem**
Ledger users with a legacy Ethereum derivation path cannot access funds in Trezor Suite.

as an MVP without optimalization, discover accounts/addresess with this derivation path: `m/44'/coin_type'/0'/account`

Fws supporting this feature: **1.12.1**, **2.6.0**

**Comment by MiroslavProchazka** [comment]
Please add also Ledger live derivation path

Ledger (legacy): m/44'/60'/0'/{account_index} (eg. m/44'/60'/0'/0, m/44'/60'/0'/1, m/44'/60'/0'/2, etc)
ledger (live): m/44'/60'/{account_index}'/0/0 (eg. m/44'/60'/0'/0/0, m/44'/60'/1'/0/0, m/44'/60'/2'/0/0, etc)
trezor: m/44'/60'/0'/0/{account_index} (eg. m/44'/60'/0'/0/0, m/44'/60'/0'/0/1, m/44'/60'/0'/0/2, etc) 

First derivation path of Ledger live and Trezor is same. We have to omit it in Trezor Suite!

**Comment by bosomt** [comment]
**QA OK**

https://satoshilabs.slack.com/archives/C06AZUTQMD1/p1723035192098009

**Comment by bosomt** [comment]
**QA NOK**

im not able to add Cardano and Cardano test account with `Account discovery error` other coins works as expected


![Image](https://github.com/user-attachments/assets/cb2ec01e-4e62-4cc2-a9bf-c36a8abeda39)


**Info:**
 - Suite version: web 24.9.0 (e86c3fea59d9d0d9acfeaccd0ab4c65f700fff59)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.32

**Comment by tomasklim** [comment]
**TK OK**

1. This is ETH issue. Cardano is not relevant
2. 
   - 12/24 words seed works as expected (trezor icarus available for 24 words, not available for 12 words - not broken there)
   - SLIP39 seed works as expected (no trezor icarus - no broken algorithm, no ledger - no support of this seed)
