### ISSUE TITLE
Cardano in graph/app

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#8592]
Cardano should have support for `blockchainGetAccountBalanceHistory` which is our only blocker for ADA in graph. According to Martin V. it should only receive little bit different params.

Plus in order to be able to test it, enable Cardano import on Import page

**Comment by Hannsek** [comment]
The difference should be between the parameters `grouBy` and `to`, right @mroz22?

**Comment by bosomt** [comment]
**QA OK**


tested on Android version develop 23.6.1 (446)
