### ISSUE TITLE
Restrict sending non-ASCII characters to Trezor as a name/label

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#8604]
<img width="770" alt="Screenshot 2023-05-31 at 8 18 25" src="https://github.com/trezor/trezor-suite/assets/57008159/8a20eb01-b75b-4afb-b9a7-5cd48815f440">

When changing name of the device, user can input there any characters (including emojis). However, Trezor [supports](https://github.com/trezor/trezor-firmware/blob/master/core/embed/lib/fonts/font_roboto_bold_20.c) only 7-bit ASCII (code points 32-126) characters.

Suite shouldn't allow sending unsupported characters to Trezor. 

If user would click on "edit name", there should be a warning saying there are unsupported characters in the input field.

_Unsupported characters in device name. Please use [standard ASCII characters](https://trezor.io/learn/a/trezor-suite-settings#ASCII-chars) only._

**Comment by mroz22** [comment]
Iam sure it was handled some time ago using this util  https://github.com/trezor/trezor-suite/blob/develop/packages/utils/src/isAscii.ts#L1

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.9.0 (b1c5e1a274403a0e94696888c39c83743b69ae8a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33
