### ISSUE TITLE
PIN modal has broken layout with longer device names

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8606]
**Describe the bug**
If you have longer device name, PIN entry modal is broken

**Info:**
-  Trezor 1 

**How to reproduce**

1. Give your Model 1 trezor longer name
1. Set PIN for the device
1. Connect the device
1. See error

**Expected behavior**
Longer device label should not break the layout. How to resolve? To be defined. I would expect ellipsis...

**Screenshots**
![Device_name-PIN_distorted](https://github.com/trezor/trezor-suite/assets/3729633/2c202493-6236-4def-bd1c-c0b6729e2816)

**Comment by tomasklim** [comment]
We can remove name from modal heading and just put it into description text

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.9.0 (930f73d5973daa7dce5493cd08a09cfcb906c635)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
