### ISSUE TITLE
[Suite-web] Potential security issue with Cypress

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#861]
Exporting store is not a good idea. Declaration of `window.Cypress = true` in console lets anyone to modify reducers or even call actions!

https://github.com/trezor/trezor-suite/blob/develop/packages/suite-web/support/CypressExportStore.tsx#L17

**Comment by vladimirvolek** [comment]
https://github.com/reduxjs/redux/issues/776
