### ISSUE TITLE
Suite takes about 30min of 100% CPU usage at every start

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#8615]
![image](https://github.com/trezor/trezor-suite/assets/48504624/8d86e670-20b4-4999-bc41-1571bb378dbc)

There is two wallet, One with 40 regular transaction and one with 200 CJ.

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
