### ISSUE TITLE
Wallet creation stuck on "Get the latest firmware" with new device

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#862]
Suite version: Pipeline 99357995, commit ba7c684a
FW after Suite install: 2.1.1
Operating System: NixOS 19.09.1279.5f506b95f9f
KDE Plasma Version: 5.16.5
KDE Frameworks Version: 5.61.0
Qt Version: 5.12.3
Kernel Version: 4.19.84
OS Type: 64-bit
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 15,5 GiB of RAM

When I try to create a new wallet with a fresh device (the device had hologram before the creating of the wallet), the onboarding installs firmware and then it's stuck on "Get the latest firmware". When I click on Back, I'm presented with a screen with "According to your decision in a previous step, this was supposed to be a fresh device. But we were able to detect already installed firmware on it., which cycles the whole process. **THIS DOESNT HAPPEN WHEN I WIPE THE DEVICE** with trezorcrl wipe-device -b, then I get the correct screen with Continue (last screen). Its also seems that when I use the fresh device, Suite installs only 2.1.1, but then when I wipe the device, the firmware installed is 2.1.8. There are some fresh Trezors T on QA, if you need more, Erik can provide some.
I'm using $ rm -rf /home/**user**/.config/@trezor/suite-desktop/IndexedDB to clear indexedDB

Maybe check the bootloader version of the devices on QA, please.

Picks bellow 
![20191129_163544](https://user-images.githubusercontent.com/50332311/69879350-86591b80-12c7-11ea-9ee1-dbae01c111b1.jpg)

![Screenshot_20191129_163525](https://user-images.githubusercontent.com/50332311/69879368-953fce00-12c7-11ea-8af7-ae2ee867ef28.png)

![Screenshot_20191129_164212](https://user-images.githubusercontent.com/50332311/69879375-9cff7280-12c7-11ea-987a-f0d8d0a2706e.png)

After trezorctl wipe-device -b
![Screenshot_20191129_164925](https://user-images.githubusercontent.com/50332311/69880005-295e6500-12c9-11ea-8a7c-1946cadb26f9.png)

**Comment by mroz22** [comment]
> Suite installs only 2.1.1, but then when I wipe the device, the firmware installed is 2.1.8. 

This is in lieu with https://github.com/trezor/trezor-suite/tree/develop/packages/rollout

**Comment by mroz22** [comment]
Not really blocked by https://github.com/trezor/trezor-firmware/issues/4 
but it might be reasonable to wait.
