### ISSUE TITLE
Support for vivaldi browser

### ISSUE THREAD

**Issue by daniel5gh** [trezor/trezor-suite#863]
Not entirely sure if this monorepo is the right place to report this issue.

When I go to https://wallet.trezor.io/#/ or the beta wallet site, I see a message my browser is not supported, since my browser, Vivaldi, is chromium based and supports all required features, I expect the wallet site to load.

Spoofing the user agent works around the problem and I have used the wallet site successfully.

My Vivaldi user agent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.137 Safari/537.36 Vivaldi/2.7.1628.33`
Spoofed one I used: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/78.0.3904.108 Chrome/78.0.3904.108 Safari/537.36`

Issue #418 is probably related.

https://vivaldi.com/

Thanks

**Comment by slowbackspace** [comment]
Hi @daniel5gh,
we are planning to allow all chromium-based browsers in our upcoming app (which we are developing in this repository). However, your issue is with our current Trezor Wallet, @TomasZorvan will look into it and keep you updated!
