### ISSUE TITLE
Account XPUB Disconnected to Connected Trezor fix

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#8637]
Follow up to #3454 (showing XPUB with Trezor not connected)

In the step from the following screenshot, if user connects Trezor, it is not recognized and the modal stays exactly as it is.

![Image](https://github.com/trezor/trezor-suite/assets/88533514/6a361ef4-a0e3-4900-a84a-2c84b833248f)

Desired solution: Device connection should be recognized and the XPUB verification flow should continue based on that.

**Comment by komret** [comment]
I suppose this screen is no longer needed, right? It appears before XPUB is shown when device is not connected.

![Screenshot 2023-08-23 at 13 57 18](https://github.com/trezor/trezor-suite/assets/42465546/ecd5c2ea-9263-4741-be98-4acc0aab8b53)

I also expect the same flow for receive address.

@Hermez-cz

**Comment by Hermez-cz** [comment]
Note: We have agreed in person with @komret to keep the "Device XYZ is not connected" modal, but to remove the `Try again` button, as the device will be recognized automatically upon connecting.

**Comment by komret** [comment]
**QA:** The "Try again" button is gone. When you connect the device while the warning modal or the address/XPUB modal is open, Suite should react to it, hide all warnings and the value should be displayed on Trezor for verification.

Some cases to try:
- Both receive and XPUB flow
- Connect device while the first/second modal is open
- Different coins
- With/without PIN
- With/without passphrase (also passphrase wallet with passphrase disabled in settings)
- With/Without backup

![Screenshot 2023-08-25 at 16 15 10](https://github.com/trezor/trezor-suite/assets/42465546/e8da04d6-b4f4-4bb4-9852-65b5eb6f6eeb)

![Screenshot 2023-08-25 at 16 16 22](https://github.com/trezor/trezor-suite/assets/42465546/6911e1d5-3360-4b5d-9112-293a13b75e7f)

**Comment by tomasklim** [comment]
> **QA:** The "Try again" button is gone. When you connect the device while the warning modal or the address/XPUB modal is open, Suite should react to it, hide all warnings and the value should be displayed on Trezor for verification.
> 
> Some cases to try:
> 
> * Both receive and XPUB flow
> * Connect device while the first/second modal is open
> * Different coins
> * With/without PIN
> * With/without passphrase (also passphrase wallet with passphrase disabled in settings)
> * With/Without backup
> 
> ![Screenshot 2023-08-25 at 16 15 10](https://user-images.githubusercontent.com/42465546/263294623-e8da04d6-b4f4-4bb4-9852-65b5eb6f6eeb.png)
> 
> ![Screenshot 2023-08-25 at 16 16 22](https://user-images.githubusercontent.com/42465546/263294538-6911e1d5-3360-4b5d-9112-293a13b75e7f.png)


@komret @Hermez-cz  would be nice to unify translation strings, one of them has `"` around device name, the others do not. 
```
  "TR_DEVICE_LABEL_IS_NOT_BACKED_UP": "Device {deviceLabel} is not backed up",
  "TR_DEVICE_LABEL_IS_NOT_CONNECTED": "Device {deviceLabel} is not connected",
  "TR_DEVICE_LABEL_IS_UNAVAILABLE": "Device \"{deviceLabel}\" is unavailable",
  ```

**Comment by komret** [comment]
I edited it in Crowdin to always use quotes (or bold folt) when `deviceLabel` is used.

**Comment by bosomt** [comment]
**QA OK**

✔️  Both receive and XPUB flow
✔️ Connect device while the first/second modal is open
✔️  Different coins /Ethereum and Cardano/
✔️  With/without PIN
✔️  With/without passphrase (also passphrase wallet with passphrase disabled in settings) /including force on device passphrase /
✔️  With/Without backup /suite asks you to create device backup, i think its expected/


**Info:**
 - Suite version: web 23.9.0 (3e34fcac398c3b6e2c577b4725dfc52f969bed5d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: Trezor T2T1 2.6.1 regular (revision a8a97276a8d57c75f97a904bfec0119be6452cf9)
 - Transport: BridgeTransport 2.0.33
