### ISSUE TITLE
Add buy CTA to dashboard Assets overview

### ISSUE THREAD

**Issue by IvaFingerova** [trezor/trezor-suite#8638]
In the dashboard part called “My Assets“ we’ll be adding our CTA “Buy” to buy for each coin

Buy button is visible in normal state on each row right after the current price column. 

* Exception for no buy button Testnets 
* On mouseover buy button will get to hover state. 
*On click user will be redirected to topmost account of chosen coin’s trade section → buy tab aka buy form ready
* 2 different views - list and grid

use current localisations for buy feature
**Design:** [Figma]
https://www.figma.com/file/SbNtdMSSi1XHgEFMZVMTex/Invity_in_Suite?type=design&node-id=1427-28324

**Spec:** [Notion]
https://www.notion.so/satoshilabs/P1-Dashboard-portfolio-151a225001b74e1b8a40d19135460833?pvs=4

**Comment by IvaFingerova** [comment]
Here are screenshots of the implementation:

![Screenshot 2023-06-29 at 13 45 47](https://github.com/trezor/trezor-suite/assets/8152411/a2b2b836-e251-45eb-9a80-04850df3e894)
![Screenshot 2023-06-29 at 13 46 33](https://github.com/trezor/trezor-suite/assets/8152411/befe78b8-7da3-46d7-b760-6ad54706c7ba)

**Comment by Hannsek** [comment]
I don't think that this is the direction in which we want to go. I can see this as very annoying for many users. cc @Hermez-cz
Plus is nowhere near nice.
Trading section in Suite is only for part of our users. The rest doesn't want to be bothered by so much CTA buttons which they will never use.

**Comment by IvaFingerova** [comment]
Released last week - closing as done

**Comment by Hannsek** [comment]
As I pointed this out BEFORE release, we should really have discussed this. @sime @Hermez-cz please step in and say if we really want this…
