### ISSUE TITLE
Bug: Send tab content disappears

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#864]
Chrome and desktop Suite. FW 2.1.8

When I click a second time on Send tab in coin, the content is replaced with empty page :tophat: :rabbit: 

![Peek 2019-11-30 10-07](https://user-images.githubusercontent.com/50332311/69898426-cbc62900-1359-11ea-8e3c-b776d68e681e.gif)

**Comment by pankrats** [comment]
Beautiful bug.
Also happens with Trezor One fw 1.8.3
