### ISSUE TITLE
Graph error on first loading the app

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8654]
Steps to reproduce the app:
Close the app (it is not running in the background)
Open the app
Graph displays error with loading the data
Click to Try again - graph displays
Imported accounts: BTC and LTC

![Image](https://github.com/trezor/trezor-suite/assets/84183817/e763a646-a308-4d39-a07e-f2bf484653f1)

**Comment by juriczech** [comment]
Reported issue to connect team and they are working on a fix. cc @mroz22

**Comment by bosomt** [comment]
**QA OK**


tested on Android verzion 610546d
