### ISSUE TITLE
Cannot Start Trezor App

### ISSUE THREAD

**Issue by jbegley323** [trezor/trezor-suite#8665]
**Describe the bug**
I just tried to install and start the Trezor App for the first time and keep getting the following:  Error: http-receiver: Start error code: EACCES

**Info:**

-   Remembered Wallet: yes/no
-   Suite Version: app/web, commit
-   Browser: name, version
-   OS: name, version
-   Bridge: version
-   Firmware Version: model, version/commit

**How to reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sime** [comment]
@jbegley323 Thanks for the issue, please contact our support representatives here: https://trezor.io/support
