### ISSUE TITLE
Unable to bump ETH fee when sending more than a half of balance

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#8671]
**Describe the bug**

- we subtract amount of pending tx from available balance which is not correct 
  - you have 1 ETH, you send 0.6 ETH with low fee
  - your balance should be 1 ETH until the tx is confirmed
  - we count only with 0.4 ETH, that's why I cannot bump fee
  - (I am also not able to send tx with more than 0.4 ETH. However, I believe I should be able to send more in case of same `nonce`)

https://satoshilabs.slack.com/archives/CKYFBT2C9/p1685718567047089
https://www.reddit.com/r/TREZOR/comments/1457kke/eth_fees_too_low_bump_fee_option_not_working/

**Info:**

-   Suite Version: 23.6.0

**How to reproduce**
1. Send more than half of your ETH balance to different address than yours 
1. Try to bump fee

**Expected behavior**
I am able to bump tx or send tx with amount of my full balance

**Screenshots**
![Screenshot 2023-06-12 at 13 13 06](https://github.com/trezor/trezor-suite/assets/33235762/9484183c-646b-4483-b79d-10b2fd6e7398)
![Screenshot 2023-06-12 at 13 12 17](https://github.com/trezor/trezor-suite/assets/33235762/bd16a80e-2ea9-4c15-a346-2de852361687)
![Screenshot 2023-06-12 at 13 12 05](https://github.com/trezor/trezor-suite/assets/33235762/c1b8bc1e-8ae8-4efd-a0d6-242f40a32eb5)
![Screenshot 2023-06-12 at 13 11 52](https://github.com/trezor/trezor-suite/assets/33235762/14e5f0b7-975b-40b0-8eef-4463c140904f)
![Screenshot 2023-06-12 at 12 41 53](https://github.com/trezor/trezor-suite/assets/33235762/f7a0a9d6-561c-4bd1-894a-1933b7c42881)

Note:
If you change `availableBalance` to `balance` in `composeTransaction` in `sendFormEthereumActions` it fixes the problem but "breaks" send max feature in send form.

**Comment by attila-lendvai** [comment]
i'm bitten by this now.

trezor suite in general doesn't handle pending transactions too well. at various places it says "received" instead of "receiving", and the total amount is also displayed as if the transaction has been confirmed while it's clearly a 3-state process with the middle state sometimes lasting for days. let alone the case where multiple competing transactions are waiting to be confirmed...

**Comment by STew790** [comment]
**QA OK**
I was able to bump fee when sending more then half of my balance.

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
