### ISSUE TITLE
ETH bump fee does not offer current gas price

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#8672]
**Describe the bug**

Let's say I send ETH tx to someone with gas price `10`. However, the current gas price in the network is `100`. Tx obviously stays pending, but I need to send it now. I use `Bump Fee` feature. I do not check network fee and just use the suggested fee by Trezor Suite. However, the suggested fee is `11`, so it stays pending again 🙃

**Info:**

-   Suite Version: since the dawn of time

**How to reproduce**

1. Send tx with small gas price
2. Try to bump fee

**Expected behavior**
It offers current gas price of network.

**Screenshots**
![Screenshot 2023-06-12 at 13 54 01](https://github.com/trezor/trezor-suite/assets/33235762/74cfd893-0416-40c4-9503-8902ebef402d)
Send form current gas price suggestion
![Screenshot 2023-06-12 at 13 54 15](https://github.com/trezor/trezor-suite/assets/33235762/fca04374-e7bc-4523-b864-eefc772eca78)

**Additional context**
`useRbfForm` file. Introduced here https://github.com/trezor/trezor-suite/pull/3429
`current.plus(1);`
<img width="570" alt="Screenshot 2023-06-12 at 13 52 56" src="https://github.com/trezor/trezor-suite/assets/33235762/d9f7b973-fe61-495e-af36-9e10b0a7c0ec">

**Comment by bosomt** [comment]
**QA OK**

+ Found this bug during testing https://github.com/trezor/trezor-suite/issues/8919

**Info:**
 - Suite version: desktop 23.8.0 (9018aa1e38c9e37e963d67753a1ae8ff5dc1ab05)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.8.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.1 Universal (revision c3f6e8f19fd647c73b414322e287ba23cf8a0c7c)
 - Transport: BridgeTransport 2.0.33
