### ISSUE TITLE
Changing discreet mode via click on balance

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#8680]
As a user, I would like to enable discreet mode by tapping on portfolio balance in order to hide the balances faster.

Acceptance criteria:
When the user switches on the discreet mode in Settings for the first time, we show the bottom sheet with information that he can do it directly from the dashboard by tapping on the balance amount
If a user taps on the portfolio balance amount for the first time, we will display the bottom sheet with information that this action triggers discreet mode
When a user taps on the portfolio balance, the amounts are hidden

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/branch/58Gop0xL5XvNnCZjP7esq9/%5Bs2.0%5D-Mobile?type=design&node-id=18104%3A115299&t=WREkjCZb2ImnqtEf-1

**Comment by matejkriz** [comment]
In Suite Desktop we switch the unit by clicking on the balance (sats/bitcoin)

**Comment by Hannsek** [comment]
So the UX of this will be different from Suite desktop?

**Comment by juriczech** [comment]
Yes, we discussed this is a super low visibility feature and makes more sense on the mobile to use discreet mode on tap rather than changing to sats. That setting is still available in the settings though. Might be revisited in future.

**Comment by bosomt** [comment]
**QA OK**

Android 14 Nothing phone 1 
24.4.0 cd82750
