### ISSUE TITLE
Receive screen brightness is not getting back to previous settings

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8688]
Steps to reproduce:
Set the brightness of the device low
Go to the app and generate receive address
Screen brightness up
Shut out the app
Brightness is still up

Expected behaviour: Brightness comes back to initial settings.

Video:
https://github.com/trezor/trezor-suite/assets/84183817/702d8a44-25aa-4137-a303-2c5add1777f5

**Comment by mnuky** [comment]
QA NOK - iPhone 12, app version 23.11.1 (373) - brightness is not going back to low when the app is turned off. 
Steps to reproduce:
Set the brightness of the device to low
Open the app and show address > Brightness of the screen is automatically increased
Shut down the app > Brightness is still increased - it should be set to low as it was before

**Comment by bosomt** [comment]
I was able to reproduce issue on iPhone 11

**Comment by mnuky** [comment]
Closing as we have got rid of the brightness increase when showing the receive address

**Comment by bosomt** [comment]
**QA OK**
