### ISSUE TITLE
App freezes with Biometric when open top menu iPhone

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8689]
Steps to reproduce:

1. Open the app
2. Enable Biometric
3. Open top menu settings
4. Come back to the app
5. App freezes

Video:

**Comment by bosomt** [comment]
Still happening with latest builds.
Work in progress, waiting for fix deployment.

**Comment by bosomt** [comment]
**QA OK**

fixed in latest dev build 
9be286d - [develop] - fix(suite-native): biometrics overlay on first launch (#8757)
