### ISSUE TITLE
Components v2 bugs

### ISSUE THREAD

**Issue by keip** [trezor/trezor-suite#869]
- [x] Button: default to inlineWidth, add fullWidth prop
- [x] Button: fix paddings and center
- [x] Button: fix isDisabled/disabled
- [x] Link: add nostyle prop
- [x] Fonts: use only one font type (add line to number zero in TTHoves)
- [x] Input left button 
![image](https://user-images.githubusercontent.com/3112191/70614133-41f44680-1c0a-11ea-8f29-eaebe22ff5c7.png)
**solved with align, when you set align right the button and state icon will be left**
- [x] Missing monospace font 
- [x] button text is not centered
![image](https://user-images.githubusercontent.com/3112191/70632926-f81e5700-1c2f-11ea-8356-3d24b302062b.png)
- [x] button icon is not centered 
![image](https://user-images.githubusercontent.com/3112191/70632780-c86f4f00-1c2f-11ea-935e-e8945c8ef609.png)
- [x] input button is not centered
![image](https://user-images.githubusercontent.com/3112191/70630642-2b5ee700-1c2c-11ea-869e-3a1c9c4572c8.png)
- [x] switch does not support isDisabled
- [x] wrong docks in storybook (checkbox / switch)
![image](https://user-images.githubusercontent.com/30367552/70851289-847c8400-1e93-11ea-93bb-4fd69abf5e17.png)

**Comment by slowbackspace** [comment]
- [x] Button: tertiary button should have transparent background

**Comment by keip** [comment]
- [ ] Button: add alignIcon prop

**Comment by slowbackspace** [comment]
- [ ] Missing some icons https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa1b3f97449919cc6f7111

**Comment by slowbackspace** [comment]
- [ ] Missing component's props exports (eg. ButtonProps, IconProps,...)

**Comment by slowbackspace** [comment]
- [x] Missing value `500` in `FONT_WEIGHTS` const

**Comment by mroz22** [comment]
- [ ] Button isDisabled property does not have disabling effect (works only visually)

**Comment by keip** [comment]
- [x] fix all font-family to "TT Hoves"

**Comment by keip** [comment]
- [ ] #1013
- [ ] #1013 
- [ ] #1010 
- [ ] #1007 
- [ ] #957 
- [ ] #1011 
- [ ] #1017 
- [ ] #1026

**Comment by keip** [comment]
- [ ] fix Tooltip snapshots

**Comment by keip** [comment]
closing after creating new issue #1043
