### ISSUE TITLE
Migrate notarization from altool to notarytool

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8692]
Deadline: November 1, 2023 (Apple notary service will no longer accept uploads from altool from that date)

Migration guide from Apple:
https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool?changes=_3_3

We use `@electron/notarize` that have option tool, so it should be simple.

https://github.com/electron/notarize#method-notarizeopts-promisevoid

**Comment by matejkriz** [comment]
low hanging for implementation, but requires special attention when testing and test signed version too.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.8.1 (11285a745786e8cd7c39ada4945f5893d7e8cd23)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.8.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T1B1 1.12.1 Universal (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33
