### ISSUE TITLE
Pending transactions should show date

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#8719]
![image (1)](https://github.com/trezor/trezor-suite/assets/42465546/b7647b56-11e9-431f-927b-01423b0e5331)

The above transaction made me confused as it looks like it has been sent this morning. In fact, it has been pending for two weeks, but one cannot tell without opening the detail.

This could be resolved by grouping the the pending transactions same as the rest of history, with date on top.

Suggested look:
![Screenshot 2024-05-07 at 18 24 15](https://github.com/trezor/trezor-suite/assets/42465546/da8069c1-599f-4afd-8d26-327bee833466)

**Comment by dahaca** [comment]
I was already working on [this](https://github.com/trezor/trezor-suite/issues/8628), so we can just group Pending TXs by date just like we group normal ones if they are not from *today*

**Comment by szymonlesisz** [comment]
there is definetelly something wrong with date/time in pending txs. check out those screenshots

![Screenshot from 2023-06-22 11-57-15](https://github.com/trezor/trezor-suite/assets/3435913/49d97308-cae6-4d0b-8b3b-c3cff209f609)

![Screenshot from 2023-06-22 12-02-01](https://github.com/trezor/trezor-suite/assets/3435913/3844d9bb-e6b3-4aa3-a1dc-34078d5c9162)

**Comment by komret** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/12975

**QA:** To be tested on both mobile and desktop. Please test all types of coins, not just bitcoin-like.

**Comment by bosomt** [comment]
**QA OK**

I can see transaction date in pending transaction. Date differed, probably mobile app uses different bloxk explorer



![Image](https://github.com/user-attachments/assets/ce5d11b1-17a0-48b4-a2f5-b9df6c161956)



![Image](https://github.com/user-attachments/assets/b8af522a-cbdd-449f-ad89-3bd0e51d53dc)



![Image](https://github.com/user-attachments/assets/8cd1d2b6-33ed-4aee-991c-e5130096c1dc)



![Image](https://github.com/user-attachments/assets/458a54a0-9ac5-40dc-8e93-498bd1bd0502)

**Info:**
 - Suite version: web 24.8.0 (90b029d7f70e030bc2a7cfd2b178df9b45fbd5d1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.32
