### ISSUE TITLE
Fee rate in transaction detail not updated after transaction bump

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#8724]
**Describe the bug**
Fee rate not updated after transaction bump in transaction detail.
Fee changes but not fee rates, easy to compare with blockbook that it does not match

**Steps to reproduce:**
1. Send transaction and check transaction detail
2. Bump or finalize transaction and check transaction detail
3. Fee rate never changes even after multiple bumps :)

**Info:**
 - Suite version: desktop 23.6.1 (bddd516378beadfcff94523e7c94834ba14f147f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.6.1 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.1 Universal (revision 089ff768229f543c89927ff34c4d45d830a2442f)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="599" alt="Screenshot 2023-06-19 at 12 33 42" src="https://github.com/trezor/trezor-suite/assets/31506317/01bb592f-020c-4a27-87af-8bb5876bd06e">

<img width="624" alt="Screenshot 2023-06-19 at 12 32 18" src="https://github.com/trezor/trezor-suite/assets/31506317/4dca25ef-9b06-45f6-8240-d3f5c8ea2092">

<img width="620" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/1141b3c2-f0a4-41b5-a590-a8bd4e17c3f8">

**Comment by tomasklim** [comment]
Same for ETH.
Looks like txs are not updated in redux, not sure if fetched again.
Interesting that fee component knows it, but the top bubble does not
<img width="313" alt="Screenshot 2023-07-21 at 9 38 00" src="https://github.com/trezor/trezor-suite/assets/33235762/fd81da3b-77e5-4734-9128-f66ab00d6ddc">

Weird that ETH rbf uses bitcoin names for fees. FeePerByte is actually gas price in gwei
![Screenshot 2023-07-21 at 10 26 09](https://github.com/trezor/trezor-suite/assets/33235762/c30779a4-4c87-4da7-80cc-169111dcc047)

**Comment by bosomt** [comment]
**QA OK**



**Info:**
 - Suite version: web 23.9.0 (c01dad446692eef861d166fe4d5ff252830dc891)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: Trezor T2T1 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33
