### ISSUE TITLE
Cardano balances don't match with Desktop Suite

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8727]
Cardano balances seem a bit off:
Rounding up/down for USD values appears different between TSL vs. Desktop Suite (even with my small testing amounts split between two ADA accounts, the USD value is out by 2 cents)
When in the Home screen view in TSL, the combined value in ADA matches what is shown in Desktop Suite, but if I click on Cardano in TSL to reveal the Select account dialog, the values are different

Desktop balances:
![Image](https://user-images.githubusercontent.com/84183817/246827521-d883f23d-8a39-4166-ba8c-c6b8f12ec8df.png)

TSL balances:
![Image](https://user-images.githubusercontent.com/84183817/246827552-0e19cd89-aaae-440b-b7fb-09aca3650094.png)
![Image](https://user-images.githubusercontent.com/84183817/246827550-f99ba99c-90c7-422f-aa0e-99bcfc9ba6c1.png)

So there are in fact three very similar but still different USD values depending on where I view the accounts
And the ADA values are slightly different between Desktop and the Home screen in TSL (a few decimal points maybe), but there is a much greater difference when you go to Select Account (cca. 2 ADA)

**Comment by bosomt** [comment]
Same accounts, latest mobile dev version and latest desktop eap version


<img width="341" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/6fbe6e8f-79db-4844-a2ed-a8fbfd41deab">

<img width="128" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/5c7ad5e3-e49b-4727-8c7d-c45fa000eb58">


is it possible that mobile app includes rewards ?


105.80646 + 0.568749 = 106,375209
94.922545 + 0.264461 = 95,187006

<img width="233" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/d8058281-8887-465b-b6db-ec67fd623ae7">

<img width="393" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/fd9bd3bc-dcbe-4910-85cc-33ebea721807">

**Comment by bosomt** [comment]
Checked it one more time during different issue testing, Firts standard account of all seed.
Difference is definitely rewards for staking ;) 

<img width="544" alt="Screenshot 2023-06-20 at 10 00 08" src="https://github.com/trezor/trezor-suite/assets/31506317/48db952d-759f-4262-84bb-7f21d4a05e65">
<img width="320" alt="Screenshot 2023-06-20 at 9 57 52" src="https://github.com/trezor/trezor-suite/assets/31506317/315a7df4-0271-4291-b139-0993c73ba089">
<img width="343" alt="Screenshot 2023-06-20 at 9 57 43" src="https://github.com/trezor/trezor-suite/assets/31506317/07857a67-126b-44fa-9017-1dee1aebbd7f">

**Comment by Nodonisko** [comment]
We are using standart `account.balance` field (that we are using for all coins) which is basically returned from connect. It seems that @bosomt correctly discovered that this field includes rewards. We can switch to `account.availableBalance` which seems to have correct balance without rewards, but question is: Should we use `account.availableBalance` everywhere instead of just `balance`?

@mroz22 Can you help?

**Comment by bosomt** [comment]
**QA OK**

9be286d - [develop] - fix(suite-native): biometrics overlay on first launch (#8757)
looks fixed.

| App  | Amount | Fiat |
| ------------- | ------------- | ------------- |
| Desktop app  | 94.922545 ADA | $26.38  |
| Lite app | 94.922545 ADA |  $25.60  |

No idea about difference in fiat rates 🤷🏿
