### ISSUE TITLE
Double notification on Android in Lite app

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#8738]
**Describe the bug**
When you copy receive address you see app notification and system notification, i think we wanted only render one notification.
On iPhone you only see app notification and no system notification. 

**Info:**
- 23.6.1 (451)
- 970ec06 - [develop] - fix(suite-native): biometrics permissions (#8734)
- Samsung A13 with Android 13

**How to reproduce**

1. Go to receive address section
2. Press `Copy`
3. Observe multiple notifications 

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/31506317/a4e61c60-bfb8-4e18-9a82-4bae5ddac0a5)

**Comment by Nodonisko** [comment]
Should be solved.

**Comment by bosomt** [comment]
**QA OK**

6fbef4c - [develop] - fix(mobile): fix animation related crashes (#10461)
Nothing phone 1 , Android 13
