### ISSUE TITLE
connect popup - implement most common error screens

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#8739]
connect-popup now does not close automatically if there is error response from connect (https://github.com/trezor/trezor-suite/pull/8447). so far this feature is enabled only in debug mode

Implement most common error screens with valuable information for users. 

Incomplete list:
- [x] passphrase mismatch -  we are using the current one adding tests - https://github.com/trezor/trezor-suite/pull/8851
- [x] transport missing (not sure here, consider whether it could become part of general error logic) - We are using the current one
- [x] forbidden key path (can be easily tested in metamask using goerli testnet) - We are using the current one
- [x] Success screen

## Other situations
- [x] 3rd party clossing  https://github.com/trezor/trezor-suite/pull/8851
   1. open 3rd party
   1. open popup
   1.  close 3rd pary
   1.  3dd party stays open without any error. in production though, popup party is closed automatically. I would expect    popup to show error most likely. but yes. this is actually edge case. this is not RESPONSE_EVENT but something else
- [x] Popup should close when user cancels the flow in popup UI for instance click on "Cancel" when asking for permissions. - https://github.com/trezor/trezor-suite/pull/8858

## Add tests
- [x] extending passphrase mismatch test  https://github.com/trezor/trezor-suite/issues/8739
  -  user opens popup, enters passphrase A, finishes call
    user reloads 3rd party, meaning inframe is reloaded too but device was not disconnected
    user opens popup, it should ask passphrase, user enters passphrase B
 

- [x] extending close popup test with situation below:  https://github.com/trezor/trezor-suite/pull/8853
    * From connect explorer try to get an address
    * When user display the options to "Export" or "Cancel" right now if user clicks on cancel it gets `success: false`  from `RESPONSE_EVENT` so popup displays error screen. 
    * I am not sure what it should do in this situation :thinking: 

related issue https://github.com/trezor/trezor-suite/issues/8082

cc @Hannsek might get some ideas here.
cc @karliatto

**Comment by sime** [comment]
Are these errors caught up sentry/analytics?

**Comment by mroz22** [comment]
For now we go on with generic error screens. Assigning to to product

**Comment by martykan** [comment]
We can close this right?

**Comment by evgenysl** [comment]
**QA OK**

I see generic error and popup is not closing automatically.

![Screenshot](https://github.com/user-attachments/assets/090010e2-c1ed-42ee-9874-60c848a6d775)
