### ISSUE TITLE
RBF form does not respect fee decimals

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#8740]
I change fee per vByte (decimals), but the total fee stays the same.

Decimals should work the same way as in the send form.

https://github.com/trezor/trezor-suite/assets/42465546/ceaca68f-a771-4d6a-b026-38f296624505

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.8.0 (4c4f5995cffd4663d84af18d39c00481de34c687)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33
