### ISSUE TITLE
RBF INCORRECT-FEE-RATE error message

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#8741]
When I set a fee rate that is not higher than the original fee rate, a toast message with an ugly error pops up.

There should be a message next to the field instead, in a more readable format. This behaviour is already implemented for "Not enough funds" error.

https://github.com/trezor/trezor-suite/assets/42465546/518bc472-3e25-4a59-8906-a7ac0df0aedf

**Comment by Hannsek** [comment]
Please put the error into [this](https://www.notion.so/satoshilabs/6b5ba89df787440c8b881140f1462256?v=f7ec7c38ff7947b6b1b6e02f452f2fea) table.

**Comment by komret** [comment]
This bug is only in my branch, sorry, closing this.

Actual error message looks like this. I added it to the table.

![Screenshot 2023-06-20 at 14 32 26](https://github.com/trezor/trezor-suite/assets/42465546/e82ca446-31e9-486d-808a-d464edf2283a)

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/trezor/trezor-suite/assets/31506317/7a76cf9c-d618-423f-9658-18c26a220071)


**Info:**
 - Suite version: web 23.7.0 (92eae50f69f2f11232db8be28d14c15a9a8110c5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/114.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.6.1 Universal (revision c3f6e8f19fd647c73b414322e287ba23cf8a0c7c)
 - Transport: BridgeTransport 2.0.33
