### ISSUE TITLE
RBF DecreasedOutputs warning disappearing

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#8742]
When I set the fee in RBF so high that I do not have enough funds to cover it, there should appear a warning (`Decreased Outputs`) component.

However, sometimes it disappears instantly.

https://github.com/trezor/trezor-suite/assets/42465546/0cd03c3c-7bd0-4bab-94a5-506f7d176cdd

Also, in case it does not disappear, it shows incorrect original amount if using sat units:

![Screenshot 2023-06-20 at 14 00 39](https://github.com/trezor/trezor-suite/assets/42465546/4de2a2ff-b1e0-4918-acde-155f8b59967d)

**Comment by szymonlesisz** [comment]
i was not able to simulate disappearing component but i've fixed invalid amount displayed in sats.

i believe disappearing issue was by fixed by [this commit](https://github.com/trezor/trezor-suite/commit/69124a47669e3eb3192e81529de0771dcee486b4)

**Comment by komret** [comment]
I can't reproduce it either, closing.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.8.0 (4c4f5995cffd4663d84af18d39c00481de34c687)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33
