### ISSUE TITLE
connect-analytics: report RESPONSE_EVENT error 

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#8744]
in reaction to https://github.com/trezor/trezor-suite/issues/8739#issuecomment-1598298032

whenever connect emits response which has `success: false`, it would probably make sense to report it into analytics system. reporting `response.payload.code` would probably be enough. There is also `response.payload.error` but it might contain sensitive data.

**Comment by bosomt** [comment]
**QA OK**

i see 

<img width="490" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/1bae7612-aa6c-4c2a-b428-562be270bc98">

at https://suite.corp.sldev.cz/connect/release/connect-v9/popup.html
