### ISSUE TITLE
Disable scanning XPUBs receiving address

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8746]
As a user I would like to know that I tried to scan BTC receive address because I do this mistake instead of scanning XPUB.

For design use this message: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=18856%3A108643&t=rDya5yyKZj5nZhWt-1

Content of the message:
Title: This is your BTC receive address
Paragraph: To check the balance of your BTC coin, scan your BTC public key (XPUB).
Link: Where to find my Public key (XPUB) 
Button: Got it

Acceptance criteria:
- When user scan BTC receive address, we display notification
- If user clicks on Got it, user is redirected back to screen with importing the coin
- if user clicks on Where to find my Public key (XPUB), video with guidance appears

**Comment by Hannsek** [comment]
jFYI some OG users may have also single address (without xpub) they want to import to app. Or they don't want to upload xpub but only some addresses. Do not know if we support this right now, or if it is a thing for us. 🤔

**Comment by mnuky** [comment]
it is not intended feature and we aim to tailor it most for newcomers, so I don't see the need to have this as a feature for now

**Comment by bosomt** [comment]
**QA OK**


040ee13 - [develop] - feat(suite-native): alert upon importing address (#8893)

**Comment by mnuky** [comment]
QA NOK with Cardano - it shows error instead of message that this is receiving address, check the video
https://github.com/trezor/trezor-suite/assets/84183817/23ea4556-13a2-4033-9609-832a671e9f8c

**Comment by mnuky** [comment]
@juriczech can you please change the copy a bit?
This is your receive address
To sync your coin, scan your public key (XPUB)
Button: Got it
Button: Where is my public key (XPUB)?

**Comment by mnuky** [comment]
@juriczech QA OK now
