### ISSUE TITLE
Coinjoin discovery progress goes backwards sometimes

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#8756]
**Describe the bug**
Coinjoin discovery progress goes backwards sometimes.
See attached video. + attached log

**Info:**
 - Suite version: desktop 23.6.1 (bddd516378beadfcff94523e7c94834ba14f147f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.6.1 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.1 Universal (revision c3f6e8f19fd647c73b414322e287ba23cf8a0c7c)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

[trezor-suite-log-2023-06-20T11-23-11.txt.zip](https://github.com/trezor/trezor-suite/files/11817005/trezor-suite-log-2023-06-20T11-23-11.txt.zip)

https://github.com/trezor/trezor-suite/assets/31506317/5410bc83-fcdb-4491-a734-cbf6c0a52070

**Comment by marekrjpolak** [comment]
How to break it:
- start Suite
- add CJ account
- open device selection modal immediately
- close it (or wait until it closes on its own)
- if there's 2 or more consecutive `scanAccount`'s in app log, it's successfully broken.

Fix ETA tomorrow.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.7.0 (d81e7e2a7c127bc4e494b69375831cd4b0998bd8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.7.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.1 Universal (revision c3f6e8f19fd647c73b414322e287ba23cf8a0c7c)
 - Transport: BridgeTransport 2.0.33
