### ISSUE TITLE
Advanced dry-run on Model 1 modal is skewed

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#8760]
**Describe the bug**
Advanced dry-run on Model 1 modal skewed to almost full width

**Info:**

-   Suite Version: 23.05 and 23.06

**How to reproduce**

1. Model 1
2. Device > Check backup
3. Start > 12 words > Advanced

**Expected behavior**
"Normal" width modal

**Screenshots**
![Screenshot 2023-06-21 at 16 22 15](https://github.com/trezor/trezor-suite/assets/216917/05bfa5ae-b0bd-444d-ac64-849f51559519)

**Additional context**
Broken in 23.05 and 23.06.

Works in 23.04

**Comment by bosomt** [comment]
**QA OK**

<img width="582" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/5faec603-97c9-4422-a1ab-be53dfe30d43">


**Info:**
 - Suite version: web 23.8.0 (d548fb3fc370de8b20458b0fd9903d91289c5e59)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: 
 - Transport: BridgeTransport 2.0.33
