### ISSUE TITLE
Enable fast discovery with trusted Custom backend via Electrum

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8774]
Coinjoin account discovery can take minutes to be perfectly private.

Advanced users with custom and mainly **trusted** backend via Electrum Server could have direct (fast) discovery for better user experience without compromising on privacy.

**Design**
TBD - Enable to express that custom node is trusted and explain what it means

![Screenshot 2023-06-22 at 14 57 30](https://github.com/trezor/trezor-suite/assets/26002916/e873b224-2d0a-41ca-a4a0-a7b95fca2995)

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
