### ISSUE TITLE
WebView for displaying URLs

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#8782]
Have a small UX proposal and that is to add WebView that would work as a wrapper around URL so user can stay in the mobile app and visit external links.

Instead of using `Linking.openURL(href)` user will be pushed to a new screen that will handle the href. Technically really easy to implement with library like `react-native-webview`

**Comment by Nodonisko** [comment]
We should let user use browser of their preference also it means no work for us.
