### ISSUE TITLE
Graph on home screen not loading if test coins are synced

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#8784]
**Describe the bug**
When I synced my testnet coins from Goerli the chart on home screen stopped working (see the screenshot).

**Info:**

-   Suite Version: mobile app

**How to reproduce**

1. Click on the button Sync my coins
2. Click on Ethereum Goerli (but probably you can select any testnet)
3. Enter some address with testnet tokens
4. Click on Confirm
5. Click on Continue to app

**Expected behavior**
The graph should show some data even after testnet coins are added.

**Screenshots**
![IMG_1204](https://github.com/trezor/trezor-suite/assets/66002635/c6c3e014-c2b7-449e-bd64-46d5f5641478)

**Comment by mnuky** [comment]
@bosomt  - I can't reproduce, it's seems to be working on dev version. Can you retest?

**Comment by bosomt** [comment]
**QA OK**

53bf934 - [develop] - chore(suite): remove remaining createSelector usage to unify

current behavior for testnets:

![image](https://github.com/trezor/trezor-suite/assets/31506317/1835be1a-bbb4-432b-bf3d-4622515be7b6)

![image](https://github.com/trezor/trezor-suite/assets/31506317/e16f6695-b90d-4b28-981e-e621c097ddab)

**Comment by AdamSchinzel** [comment]
> @bosomt  - I can't reproduce, it's seems to be working on dev version. Can you retest?

Now it is fixed
