### ISSUE TITLE
Add swap tab to Ethereum trade options

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#8788]
Have a (not so small) product feature proposal and that is to add swap tab for users with ERC-20 in their wallet so they can swap them.

The UI/UX for it can be highly inspired by what e.g. Uniswap already has.

For the technical solution it would be great to compare offers from different swap smart contracts that are popular ([Uniswap](https://app.uniswap.org/#/swap), [SushiSwap](https://www.sushi.com/swap), [Curve](https://curve.fi/#/ethereum/swap), ...) and by default go with the best offer. That could be archived with API like [this](https://0x.org/docs/category/swap-api).

**Comment by sime** [comment]
@AdamSchinzel Swapping of tokens is already possible under the exchange tab. I think this is what you meant?


<img width="840" alt="Screenshot 2023-06-28 at 11 31 01" src="https://github.com/trezor/trezor-suite/assets/216917/3d908bd2-4068-4d23-ba9b-15e581f7caa2">

**Comment by AdamSchinzel** [comment]
> @AdamSchinzel Swapping of tokens is already possible under the exchange tab. I think this is what you meant?
> 
> <img alt="Screenshot 2023-06-28 at 11 31 01" width="840" src="https://user-images.githubusercontent.com/216917/249420113-3d908bd2-4068-4d23-ba9b-15e581f7caa2.png">

Yes, sorry. Couldn't find it.
