### ISSUE TITLE
CJ "Loading Fund" takes a very long time after being at 100%

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#8791]
It stayed like this for more than 10 min
![image](https://github.com/trezor/trezor-suite/assets/48504624/48b3cad3-f8c5-49bf-80db-e4ef35a8da2f)

CPU at near 100% but choppy during that time (last green block)

![image](https://github.com/trezor/trezor-suite/assets/48504624/b1e495b5-9f5e-4612-8cf1-81b468bd2e20)

I then switched account and the progress is back to zero
![image](https://github.com/trezor/trezor-suite/assets/48504624/3ea214fb-c23f-435c-b785-d5fc0aa946e3)

It never got to load, closed the wallet and trying again .... will report back

**Comment by nostitos** [comment]
Took 2 hours to sync,  I closed it and open again, 

It then took 50min this time, it was fully synced a few seconds before, zero progress after 20min.

![image](https://github.com/trezor/trezor-suite/assets/48504624/2d62ab84-4d10-49a7-83ea-2684bf0e4508)

![image](https://github.com/trezor/trezor-suite/assets/48504624/d8c6569d-b87a-46af-98c2-030508e42aed)

**Comment by nostitos** [comment]
Suite randomly start "Loading fund" while it's already synced, It also spend more than 20 minutes doing it, 
The internet connection is rock solid and CPU is at almost 100%, DOING WHAT?

![image](https://github.com/trezor/trezor-suite/assets/48504624/a90e64c4-08a2-49a7-a95b-be54cf5647dc)

**Comment by nostitos** [comment]
35min, to do an arbitrary mid-session resync.

![image](https://github.com/trezor/trezor-suite/assets/48504624/ccfc6e71-63f9-4f1d-8b43-9890c5769f75)

**Comment by nostitos** [comment]
100% progress and no end in sight.

![image](https://github.com/trezor/trezor-suite/assets/48504624/0f9ee0fb-4305-4bd5-9a81-829804bb6ed4)

**Comment by nostitos** [comment]
It got through it after ~1h and resumed CJing
![image](https://github.com/trezor/trezor-suite/assets/48504624/f48b1338-8e1b-4728-9160-9b16b9cefd9c)

**Comment by bosomt** [comment]
@nostitos can you please check it one more time ?
there was significant improvement in loading of coinjoin accounts in new versions

**Comment by MiroslavProchazka** [comment]
I'm closing this issue due to the prolonged period of inactivity and the absence of any response.
