### ISSUE TITLE
Very slow list of transaction screens where there is lot of Transactions

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#8798]
Current SectionList renders all available transaction at once which is very slow (it shouldn't but I have no idea why). Best solution will be migrate it to FlashList.

**Comment by bosomt** [comment]
**QA OK**


tested on Android Samsung A13 phone
cd5d50f - [develop] - chore(mobile): improve perf of transaction list (#8836)
loaded BTC and ETH accounts with hundreds of transactions.
