### ISSUE TITLE
Migrate account labels to new metadata structure

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#8804]
Write storage migrations for https://github.com/trezor/trezor-suite/pull/8646#pullrequestreview-1498434557

We need to migrate accountLabel to new place. Use redux-persists migration API.

**Comment by bosomt** [comment]
**QA OK**


tested one more time as migration from 481 to 491

- tested on iPhone 11
- d3102fd - [develop] - chore(suite-native): account label migrations (#8947)
- 001e5ef - [develop] - feat(suite-native): filterable accounts list (#9098)
