### ISSUE TITLE
Graph is not working properly when currency is changed

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8809]
Steps to reproduce:
1. Open the app, wait for graph to be loaded
2. Go to settings and change the currency
3. Come back to dashboard - graph and total balance is not loaded, it shows 0
4. Change the graph timeframe to 1W - graph is loaded, change the graph to 1D - graph and total balance displays 0

Video:

**Comment by bosomt** [comment]
**QA OK**

fd58036 - [develop] - chore(suite-native): update fastlane (#8996)

**Comment by miroslavdejl-dot** [comment]
I’m experiencing a similar issue in Trezor Suite mobile.
The BTC market price chart (current price + historical view, e.g. 1Y) appeared briefly after launching the app, but then disappeared after synchronization and never came back.
This is not the portfolio graph, but the general Bitcoin price chart.
I didn’t change any settings manually.
Platform: mobile app
Fiat currency: CZK
It looks like the chart is not reliably reloaded after app state changes.
