### ISSUE TITLE
Big number handling improvement. 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#8813]
**Describe the bug**
Mobile app needs to improve long/big numbers formatting/handling. 
Please see screenshots when using Etehreum and Argentinian pesos.

**Info:**

- 23.6.1 (19) hash e700d39

**Screenshots**

![image](https://github.com/trezor/trezor-suite/assets/31506317/b259f8d7-2af7-40bb-85ed-57b924c4f6ce)

![image](https://github.com/trezor/trezor-suite/assets/31506317/e226771b-c232-44a6-8d1d-6e08d211fa5a)

**Comment by PeKne** [comment]
@mnuky How should we solve this from the design point of view? Should we make the text shorter (remove some decimal digits) or make the text font smaller?

**Comment by PeKne** [comment]
Acceptance criteria:
- too long ETH values are shortened on the top Home screen assets
- too long values deeper in the app (TransactionListScreen, AssetListScreentransaction detail, input&outputs sheet etc.) will have decreased font size to fit in the layout.

**Comment by bosomt** [comment]
Shortening is definitively  better than current state ;)

<img width="353" alt="Screenshot 2023-07-20 at 12 49 50" src="https://github.com/trezor/trezor-suite/assets/31506317/ee8ab397-8a1b-4509-91c9-e03ba11357af">

**Comment by bosomt** [comment]
**QA OK**

i think that long eth values are too small but maybe i need new glasses ;)
<img width="351" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/93400e1d-e077-4693-8f5e-0ef0ff26aff7">

fd58036 - [develop] - chore(suite-native): update fastlane (#8996)

**Comment by PeKne** [comment]
@bosomt you are right, this solution is not ideal. But it is still better than rounding to fixed decimals even in cases like (0,000000001 ETH  rounded to ==> 0,00000000 ==> represented as 0 ETH). We believe that would scare many people so we decided to keep the "font size adjusting" solution as long as the design team does not come up with a better solution.
