### ISSUE TITLE
Wrong redirection at https://connect.trezor.io/

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#8831]
**Describe the bug**
When going to https://connect.trezor.io/ it tell you
```Please visit https://github.com/trezor/connect for more details...```
It does not seam right since that repository is archived.

**How to reproduce**

1. Go to https://connect.trezor.io/ 
1. See error ```Please visit https://github.com/trezor/connect for more details...```

**Expected behavior**
I would expect it not to redirect me to an archived repository. But I can think of some nice options like:
* Redirecting to https://connect.trezor.io/9 it does not need to display the test before, just redirecting automatically.
* Some simple landing page for connect that offers a link to https://connect.trezor.io/9

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/5362163/b92d1d42-9abb-42db-a22f-e7f42867248e)

**Comment by mroz22** [comment]
lets just redirect this to `https://connect.trezor.io/9` 
may I please @vdovhanych ? 🙏

**Comment by vdovhanych** [comment]
@mroz22 You mean [connect.trezor.io/](https://connect.trezor.io/) to [connect.trezor.io/9/](https://connect.trezor.io/9/#/) ?

**Comment by mroz22** [comment]
exactly

**Comment by vdovhanych** [comment]
well as it is hosted on AWS trough its CloudFront the only option to redirect it on the server side is to use AWS Lambda with some code that would redirect the viewer to a new domain. Could we modify the HTML index for connect.trezor.io so it redirects based of it? or not?

**Comment by mroz22** [comment]
client side redirect? I don't mind

**Comment by vdovhanych** [comment]
yes something like this in the head of the HTML file.

```
<meta http-equiv="refresh" content="0; url=https://connect.trezor.io/9/#/" />
```

**Comment by vdovhanych** [comment]
Done, it is now doing client-side redirect to `connect.trezor.io/9/`
