### ISSUE TITLE
Bump supported browser versions

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8832]
**Chrome 92** (2 years old)
**Firefox 102** (long term support)

**Comment by matejkriz** [comment]
By the way, this solves the problem that we use String.prototype.at().

**Comment by matejkriz** [comment]
discussion https://satoshilabs.slack.com/archives/CKZHV2G13/p1688023919844709

**Comment by bosomt** [comment]
**QA OK**

Chrome 84: Your browser is outdated
Firefox 78: Your browser is outdated

Chrome Version 92.0.4515.0 (Developer Build) (x86_64 translated) works
Firefox 102.0 works
