### ISSUE TITLE
Add eye icon for show/hide PIN instead of backspace icon in the PIN input (Model 1)

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#8835]
In my opinion it makes more sense to have eye icon for show/hide PIN instead of the backspace icon in the right part of the input used for typing in your PIN on Trezor Model 1.

You can't show hide PIN at all now but you can press backspace on your keyboard.

<img width="371" alt="Screenshot 2023-06-29 at 3 41 47 PM" src="https://github.com/trezor/trezor-suite/assets/66002635/822c8653-9673-4890-82ce-ed8486e29e5b">

**Comment by Hannsek** [comment]
But that is the thing why there is the matrix. To not show the actual pin on computer screen.
