### ISSUE TITLE
Reintroduce RNUsbPlugin outside Trezor Connect

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8849]
There was a file [RNUsbPlugin.ts](https://github.com/trezor/trezor-suite/blob/5b71a77ba8410778454e719ab96865210c6f4949/packages/connect/src/workers/RNUsbPlugin.ts) inside Trezor Connect, that is removed and should be reintroduced outside Connect and injected during initialization.

**Comment by Nodonisko** [comment]
Done
