### ISSUE TITLE
Non-private utxo in private section

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8870]
**Describe the bug**
I have a defaul privacy level (5) and as image shows one of the utxos with privacy level 1 is located in the private section.

<img width="852" alt="Screenshot 2023-07-07 at 7 55 08" src="https://github.com/trezor/trezor-suite/assets/26002916/cf8946f1-e51c-49c2-b76c-1d59a90ef455">

**Info:**
 - Suite version: desktop 23.7.0 (8438ae61daf6c3ff3853112940cbfb6fcebcbdab)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.7.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.6.0 Bitcoin-only (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Comment by matejkriz** [comment]
@hynek-jina does it stay there or did you only see it temporarily?

**Comment by hynek-jina** [comment]
I don't know... I will try to retest it

**Comment by bosomt** [comment]
**QA OK**

i was not able to reproduce issue

**Info:**
 - Suite version: desktop 23.8.1 (c6b91601f5c333a1de056fbf0b712995a96b5d90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.8.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 Universal (revision b151a3db6b04d2bee0bb68470e57b822443bf83d)
 - Transport: BridgeTransport 2.0.33
