### ISSUE TITLE
Pop-up advising to upgrade bridge when none is running

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#8880]
**Describe the bug**
Connect pop-up advises to upgrade Bridge when non is running

**Info:**

-   Browser: Chrome 114.0.5735.198, Firefox 114.0.1 
-   OS: OSX 13.4 (22F66)
-   Bridge: NONE

**How to reproduce**
1. https://connect.trezor.io/9/#/method/getPublicKey
2. Click 'Get public key'

**Expected behavior**
No update bridge option

**Screenshots**
![Screenshot 2023-07-10 at 12 10 40](https://github.com/trezor/trezor-suite/assets/216917/3c2b6cbc-49b5-4f67-baa6-6818334f87b5)

**Comment by Hannsek** [comment]
It seems like this is not happening anymore.

**Comment by bosomt** [comment]
**QA OK**

tested at https://connect.trezor.io/9/#/method/getPublicKey with no bridge running

**Comment by Hannsek** [comment]
It may happen in some corner case situation when WebUSB is not available. But it shouldn't happen for the majority of users. @mroz22
