### ISSUE TITLE
Graph timeframes improvements

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8891]
As a user, I would like to keep the selected timeframe when I change it, go to some other screen and then come back to the graph. Currently, the graph Timeframe always comes back to the default timeframe
As a user, I would like to see the default timeframe for the graph as 1M as it makes more sense from DCA / viewing the changes POV. 

Acceptance criteria:
- When the user set a timeframe in the graph and goes to another screen and comes back to the graph, the selected timeframes stays the same
- Default graph timeframe is 1M
- every instance of a graph (portfolio and any account detail graph) remember its custom settings

**Comment by Hannsek** [comment]
Can it stay on the selected timeframe even when I quit the app and then go back?

**Comment by PeKne** [comment]
> Can it stay on the selected timeframe even when I quit the app and then go back? @Hannsek 

This is also possible indeed. What do you think @mnuky ?

**Comment by mnuky** [comment]
if it's not a big effort, let's do it! :)

**Comment by bosomt** [comment]
**QA OK**

b501fa1 - [develop] - feat(suite-native): persistent graph timeframe storage (#8948)
