### ISSUE TITLE
All time high value changing when switching between different timeframes

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#8896]
**Describe the bug**
All time high changing when switching between different timeframes even though the all time high is in the 1 day time frame

**Info:**

-   Suite Version: mobile, e700d39
-   OS: iOS 16.5.1

**How to reproduce**
Switch between different timeframes and see that the all time high value is changing.

**Expected behavior**
All time high should stay the same

**Comment by Hannsek** [comment]
I suppose that if user choose larger time frame, the graph would drop some data. The data "provided to" graph will be less granular

**Comment by Nodonisko** [comment]
There is nothing we can do about this, because of different granularity of data per timeframe.
