### ISSUE TITLE
"My portfolio balance" is changing when changing different timeframes

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#8897]
**Describe the bug**

"My portfolio balance" is changing when changing different timeframes

**Info:**

Suite Version: mobile, https://github.com/trezor/trezor-suite/commit/e700d390a517b615eaf2ea9660bcdf5d9cb21b2b
OS: iOS 16.5.1

**How to reproduce**
Switch between different timeframes and see that the all time high value is changing.

1Y and 6m has the same value, 1W and 1M has the same (but different from others) value.
1D and ALL are different as well.

**Expected behavior**
Portfolio balance should stay the same

**Additional context**
The same behaviour is for CZK and USD (I didn't try other currencies.)

**Comment by mroz22** [comment]
isn't this just https://en.wikipedia.org/wiki/Coastline_paradox ?

**Comment by Hannsek** [comment]
Could be…🤷🏻

**Comment by sime** [comment]
@Hannsek Duplicate https://github.com/trezor/trezor-suite/issues/7237 ?

**Comment by Hannsek** [comment]
It looks similarly. 🤔🤔

**Comment by Hannsek** [comment]
Probably duplicate.
