### ISSUE TITLE
Switching between currencies won't change the text under the currency tab

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#8898]
Info:

Suite Version: mobile, e700d39
OS: iOS 16.5.1

**How to reproduce**

1. Go to Localization
2. Click on Currency
3. change currency to some other
4. See that the currency in currency tab is still the same

**Expected behavior**
Changed text under the currency tab

**Comment by Hannsek** [comment]
Plus when I get to the dashboard after changing the currency, the graph won’t show up. I have to quit the app, kill it and reopen in order to make it work.

**Comment by mnuky** [comment]
https://github.com/trezor/trezor-suite/issues/8898#issuecomment-1632655452

This one is already reported here: https://github.com/trezor/trezor-suite/issues/8809

**Comment by Nodonisko** [comment]
Should be done.

**Comment by bosomt** [comment]
**QA OK**

24.01.1 (673)
96d12a4 - [develop] - fix(suite): fix label drop for RBG transactions
Android 13 - Nothing phone 1
