### ISSUE TITLE
Currency "name" not rendered properly

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#8899]
**Describe the bug**
If I switch between different currencies, longer text won't render properly

**Info:**

Suite Version: mobile, https://github.com/trezor/trezor-suite/commit/e700d390a517b615eaf2ea9660bcdf5d9cb21b2b
OS: iOS 16.5.1

**How to reproduce**

1. Somehow click between different currencies + go back to settings between changing the currencies. 😅

**Expected behavior**
Properly rendered text of chosen currency

**Screenshots**
![IMG_8573](https://github.com/trezor/trezor-suite/assets/57008159/fe679ef0-a3dc-4901-aedf-3cea8c167eae)

**Comment by PeKne** [comment]
Seems like it was already fixed. Could you please retest? @bosomt

**Comment by bosomt** [comment]
**QA OK**

already fixed
just checked on Android and iOS devices
