### ISSUE TITLE
Trading - Select/Modal z-index clash in Exchange Offers

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#8907]
![Screenshot 2023-07-12 at 9 58 50](https://github.com/trezor/trezor-suite/assets/42465546/7899e251-3660-4f7f-9b82-652169545e80)

How to reproduce:
You need to have some amount of mainnet coins in your account or change source code so that youu are able to get to the screen. Go to Trade > Exchange > Compare offers > Get deal > Create a new account. Reported [here](https://satoshilabs.slack.com/archives/C031LD98L9K/p1688568630994659?thread_ts=1688480384.320529&cid=C031LD98L9K).

**Comment by komret** [comment]
[The linked](https://github.com/trezor/trezor-suite/pull/8901) offers one solution, but a better way seems to be refactoring `ReceiveOptions` to use `Dropdown` instead of `Select`.

**Comment by komret** [comment]
Closing in favour of #8917.

**Comment by bosomt** [comment]
@komret current dev master app :(


<img width="908" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/6e543063-141d-4251-8d91-aa9c6e223d89">


https://github.com/trezor/trezor-suite/assets/31506317/30ae4c36-3f0c-40c2-bc4d-682cebcf4f1c


**Info:**
 - Suite version: desktop 23.8.0 (2d8e93cc503867fec6508379a831ef283381241f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.8.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
**QA NOK**

still happening 

![image](https://github.com/trezor/trezor-suite/assets/31506317/19d6700d-f58b-4cb6-b5cd-3c484bd3bcfe)


**Info:**
 - Suite version: desktop 24.6.0 (e9a042518338e1b23fbf1542d4f08ea64dd930cd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by tomasklim** [comment]
@bosomt could you please recheck?

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
