### ISSUE TITLE
Select does not open when there is not enough space for menu

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#8909]
All Selects are broken like this. Reduce the window size or open devtools:

https://github.com/trezor/trezor-suite/assets/42465546/3ce08f0c-a642-47e3-9f40-43a674112ff3

How it works when you remove `menuPortalTarget` and `closeMenuOnScroll` from `Select`:

https://github.com/trezor/trezor-suite/assets/42465546/5fcbe975-82fa-4d45-9990-6d4008c65fdf

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.8.0 (4c4f5995cffd4663d84af18d39c00481de34c687)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33
