### ISSUE TITLE
ETH in transaction details show negative amount even though it's an incoming transaction

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#8913]
**Describe the bug**
The "Amount" in the transaction detail of an incoming ETH transaction shows "-" before the amount even though the transaction is incoming and it shows "+" correctly in the transaction history.

**Steps to reproduce:**
1. Go to ETH account with transaction history
2. Click on any incoming transaction and observe, that it shows "+" in the transaction history
3. The "Amount" in the transaction detail shows "-" instead of "+"

**Info:**
 - Suite version: desktop 23.7.1 (4a4127f0beab65e4dfadb2a68385761abee44396)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.7.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
"Amount" in the transaction detail of an incoming ETH transaction shows correctly "+".

**Actual result:**
"Amount" in the transaction detail of an incoming ETH transaction shows "-".

**Screenshots:**
Trasnaction history:
![image](https://github.com/trezor/trezor-suite/assets/48477147/ec5f271c-97a4-4c45-ad4d-7644eee3ec62)
Transaciton detail:
![image](https://github.com/trezor/trezor-suite/assets/48477147/15fb247e-2152-44a4-91eb-51abec63c871)

**Comment by tomasklim** [comment]
Applies to every network.

![Screenshot 2023-07-17 at 14 46 04](https://github.com/trezor/trezor-suite/assets/33235762/18744132-893b-439d-a8ff-4166537152f9)
![Screenshot 2023-07-17 at 14 46 10](https://github.com/trezor/trezor-suite/assets/33235762/2aab223c-1326-4eb3-979a-ff5139e3bb21)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.8.0 (d548fb3fc370de8b20458b0fd9903d91289c5e59)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.8.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
