### ISSUE TITLE
Decimals allowed in Ethereum gas price field 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#8919]
**Describe the bug**
Trezor Suite allows you to use decimals in gas price field in Send dialogue , this leads to crash of app.

**Steps to reproduce:**
1. Navigate to Ethereum send dialogue.
2. Use custom `Gas price` with decimals
3. press `Review & Send`

**Info:**
 - Suite version: desktop 23.8.0 (9018aa1e38c9e37e963d67753a1ae8ff5dc1ab05)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.8.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.1 Universal (revision c3f6e8f19fd647c73b414322e287ba23cf8a0c7c)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/ea71f462-fa4d-4e62-8e3a-e3a015b31ff6

<img width="546" alt="Screenshot 2023-07-16 at 9 12 36" src="https://github.com/trezor/trezor-suite/assets/31506317/4c97d958-5dbd-4d58-aa40-f924da8b87a5">
<img width="1163" alt="Screenshot 2023-07-16 at 9 12 04" src="https://github.com/trezor/trezor-suite/assets/31506317/563394f6-fb60-4105-8ac2-9ae443136c23">

**Comment by matejkriz** [comment]
great that you discovered where it's happening 🎉 , we have ~ 80 users/ 30day in Sentry with this error: https://satoshilabs.sentry.io/issues/?project=5193825&query=is%3Aunresolved+number-to-bn&referrer=issue-list&statsPeriod=30d

**Comment by tomasklim** [comment]
~No. The bug is in validation.~ Gas price can be decimal (9 places)
https://eth1.trezor.io/tx/0x6f9cecaf69cc27473396f20a5a378992e9576c076d9ab1721b048cc0e32dfcd0

**Comment by tomasklim** [comment]
I can't replicate it

**Comment by tomasklim** [comment]
`T1B1` ok
`T2T1` <2.6.0 ok
`T2T1` >=2.6.0 nok 

Introduced because of new flow in https://github.com/trezor/trezor-suite/pull/7989

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.8.0 (f629847444f2f16651fd500e60f9ba7c11ac6b45)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33
