### ISSUE TITLE
Split sathoshis digits by thousands

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8922]
Satoshis miss the digits formatting as we have with others digits. 

Expected look: Satoshis are split by thousands as other digits within the app

![Image](https://github.com/trezor/trezor-suite/assets/84183817/ccd6ff57-43ca-46d1-8aa9-f1694af273ea)

**Comment by PeKne** [comment]
Suite desktop UI: 

![Image](https://github.com/trezor/trezor-suite/assets/26143964/32be6131-3b3e-4d65-a3d9-2bb847cb8d13)

**Comment by mnuky** [comment]
QA OK - iPhone 12, app version 23.11.1 (373)
@bosomt can you please test it, too?

**Comment by bosomt** [comment]
**QA OK**

dev version 23.11.1 (568) Noting phone 1 Android 13 
dev version 23.11.1 (371) iPhone 11 /latest iOS/
