### ISSUE TITLE
Check that we use `fromWei`, `toWei` from `web3-utils` correctly

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#8931]
To prevent issues such as https://github.com/trezor/trezor-suite/pull/8930 and incorrect amounts

https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html#fromwei
https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html#towei

Would be nice to check that we use those methods correctly in our codebase. It is used in 9 files, so it would not be that hard to check and make some report / fixes.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.6.5 regular (revision a784c4046e79ae138f9a7a9c5e97d2f6771140eb)
 - Transport: BridgeTransport 2.0.33
