### ISSUE TITLE
Add devices param to the supportedFirmware config in Connect

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#8952]
Currently there is no way to tie a Connect method to a specific device or firmware based on device. Extend the config to enable that functionality.

**Comment by szymonlesisz** [comment]
not sure i understand, there is a way how to define mininum fw version for coin, method and capability


examples:
```
{
    coin: ['eth', 'tgor'],
    min: ['1.8.0', '2.1.0'],
    comment: ['There were protobuf backwards incompatible changes.'],
},
{
    methods: ['cardanoGetAddress', 'cardanoGetPublicKey'],
    min: ['0', '2.3.2'],
    comment: ['Shelley fork support since firmware 2.3.2'],
},
{
    capabilities: ['eip1559'],
    min: ['1.10.4', '2.4.2'],
    comment: ['new eth transaction pricing mechanism (EIP1559) since 1.10.4/2.4.2'],
},
```

**Comment by mroz22** [comment]
we are going to need to discriminate by `version` times `model`. Seems like situation is coming where a method will be supported by firmware `2.x.y` but only on specific model (because of hardware diffrences)

But maybe we could somehow leverage features.capabilities for this 🤔

**Comment by matejkriz** [comment]
When this is done, we can add current device model capabilities validation in device authenticity check as mentioned here: https://github.com/trezor/trezor-suite/pull/9315
