### ISSUE TITLE
[Message] Enable coinjoin for T1

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8958]
- [x] Enable coinjoin accounts for T1 from `23.8`
- [x] Request at least `23.8` Suite version for coinjoin feature
- [ ] ~Remove beta part of banner, ~make it dismissible and~ less alarming~ Not yet
- [x] Update privacy gain estimates - https://satoshilabs.slack.com/archives/C04QY40TJL9/p1692182491500419
  - [x] `averageAnonymityGainPerRound: 0.2`
  - [x] `roundsDurationInHours: 1.5`
- [x] get back estimated time per round from 3 to 1 (reverting https://github.com/trezor/trezor-suite/pull/8345) 

This improvement should be released with 23.8. (on 16th of August)

## Notes for QA

- **Turn off** debug menu for testing T1, otherwise it has no effect...
- verify currentSequence === 41

**Comment by matejkriz** [comment]
> * make it dismissible and less alarming

dismissing of context banners is not yet implemented

**Comment by hynek-jina** [comment]
Can we show it in top bar then but only to users with coinjoin account?

**Comment by matejkriz** [comment]
> Can we show it in top bar then but only to users with coinjoin account?

unfortunatelly not, we don't have `coinjoin` account as possible condition, only tor and coins enabled, versions of app, operating system,  device, ...

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.8.1 (c6b91601f5c333a1de056fbf0b712995a96b5d90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.8.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 Universal (revision b151a3db6b04d2bee0bb68470e57b822443bf83d)
 - Transport: BridgeTransport 2.0.33
