### ISSUE TITLE
Handle frequent `403 Forbidden` from Blockbook on CJ accounts

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#8960]
Mostly on CJ accounts, we're getting frequent 403's from Blockbook, because Cloudflare blocks some of Tor exit nodes. Possible solutions:
:heavy_check_mark: start to use ([again](https://github.com/trezor/trezor-suite/issues/7076)) Tor hidden services (.onion addresses)
:construction: run our own Tor exit node and whitelist it on Cloudflare (if possible)
:no_entry: experiment with empty `User-Agent` (Wasabi does that, but Blockbook doesn't support it currently)
:heavy_check_mark: restart Tor circuit on 403 even when opening websockets (now we're doing it only for GET/POST requests)

**Comment by marekrjpolak** [comment]
Are we going to keep the issue opened until dedicated Tor exit node idea is resolved one way or another, or can we close it? @matejkriz

**Comment by matejkriz** [comment]
> Are we going to keep the issue opened until dedicated Tor exit node idea is resolved one way or another, or can we close it? @matejkriz

When this issue is scoped on CJ accounts, I believe we can close it now.
