### ISSUE TITLE
Unable to bump fee to an amount lower than current base gas price 

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#8972]
**Describe the bug**
Unable to bump gas price to an amount lower than current network gas price 

**Info:**

-   Suite Version: 23.8.0

**How to reproduce**

1. Create tx with small gas price `1`
2. Bump fee in custom, try to put there `2`. The minimum is currect network fee

**Expected behavior**
It will allow me to insert what ever I want higher than `1`, probably `2` or even better `1.00000001`

**Screenshots**

![Screenshot 2023-07-21 at 11 27 29](https://github.com/trezor/trezor-suite/assets/33235762/d177d4f4-67a7-4369-8593-4fe2aa3adc27)

**Comment by tomasklim** [comment]
@AdamSchinzel probably caused by https://github.com/trezor/trezor-suite/pull/8787

**Comment by bosomt** [comment]
**QA OK**

- sent 5 gas
- suggested bump was 17
- i was allowed to bump free from 6 to 10000

**Info:**
 - Suite version: desktop 23.8.0 (549c8f7df73e06cd2542440ec88078a2786170cb)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.8.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33
