### ISSUE TITLE
Custom backends for coinjoin

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#8976]
**Design:** TBD

**Spec:** [Notion (WIP)](https://www.notion.so/satoshilabs/CoinJoin-custom-backend-ca2474131d1a40ebb71aeabd9d3a0691?pvs=4)

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
