### ISSUE TITLE
Czech translation of one "Did you know" tip when CJ is loading is slightly cropped

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#8981]
**Describe the bug**
Czech translation of one "Did you know" tip when CJ account is loading is slightly cropped. It is the one about BTC halving. More in screenshot.

**Steps to reproduce:**
Try to add CJ account in Czech and be lucky to get the "Did you know" tip about BTC halving.

**Info:**
 - Suite version: desktop 23.7.2 (900989955cb6a56111d6827091f60ca059bfcf4f)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.7.2 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: Win32
 - Screen: 2560x1440
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.31

**Expected result:**
"Did you know" tip is not cropped.

**Actual result:**
"Did you know" tip is slighlty cropped.

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/48477147/4bc3370b-09e4-413d-b86c-4eef8ea69dd1)

**Comment by Hannsek** [comment]
Quick fix would be just changing the text.

**Comment by hynek-jina** [comment]
@Hannsek Good point..
I've changed it in crowdin to:
```
Halving je mechanismus, při kterém se odměna za těžbu bitcoinu každé čtyři roky snižuje na polovinu. Na začátku byste za vytěžení jednoho bloku získali 50 BTC, zatímco v roce 2022 už jenom 6,25 BTC.
```

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.8.0 (549c8f7df73e06cd2542440ec88078a2786170cb)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.8.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33
