### ISSUE TITLE
Cannot access coinjoin account

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#8984]
**Describe the bug**
Cannot access cj account.
The "loading funds…" loader is present only for couple of seconds, then "account discovery error" occurs. 
**Info:**

-   Remembered Wallet: no
-   Suite Version: app, 23.7.2
-   OS: macOS, 13.3.1 (a) (22E772610a)
-   Firmware Version: T, 2.6.0
**How to reproduce**
Try to access cj account

**Expected behavior**
access cj account

**Screenshots**
<img width="788" alt="image" src="https://github.com/trezor/trezor-suite/assets/57008159/1aae8996-874b-4672-aa05-4c437fcd2647">
<img width="421" alt="image" src="https://github.com/trezor/trezor-suite/assets/57008159/618c6924-155e-402d-b8b1-992ae4f9ff31">

**Comment by ondracja** [comment]
@Hannsek This is a currently know issue - tor nodes are being banned. A fast solution should be to turn tor on/off to connect to a different node. A better solution is being (hopefully) developed.

**Comment by Hannsek** [comment]
Can we add this on/off tor to “retry” button? So it will reconnect to another tor node automatically.
