### ISSUE TITLE
Token transaction list contains extra subtitles

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#8985]
In the section list of token transactions are some redundant month subtitles: 

![Image](https://github.com/trezor/trezor-suite/assets/26143964/04502cbb-82cf-4c29-9cb5-ab505ebccde2)

**Comment by bosomt** [comment]
**QA OK**

d2efe78 - [develop] - fix(suite-native): event tooltip zero sum values (#8950)
