### ISSUE TITLE
Zero amount transactions that contains internal transfer are hidden

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#8986]
So far we have been filtering out zero amount transactions from the transaction list. Now when we introduce internal transfers, we need to display that zero-amount transaction which includes internal transfers. Without this adjustment are most of the internal transfers hidden from the user.

## Acceptance criteria:
If an Ethereum based transaction contains an internal transfer, it is displayed in the transaction list.

**Comment by bosomt** [comment]
**QA OK**

checked on account with this tx
https://eth1.trezor.io/tx/0x9dc9b9c884aad768328f28e8194f1f86121f6c2a1742fa817c33bcc2f3b7aa3c

fd58036 - [develop] - chore(suite-native): update fastlane (#8996)
