### ISSUE TITLE
Update to RN 0.72 + Expo SDK 49

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#8991]

**Comment by juriczech** [comment]
@trezor/qa This issue will need testing on Android + iOS after merge to develop of #9071. Just click through all screens to make sure nothing broke. This is just general `react-native` upgrade but potentially it could break app somewhere so just to be on the safe side.

**Comment by Nodonisko** [comment]
We will do to 0.73 directly once it's out
