### ISSUE TITLE
Disable coinjoin for unfortunate bridge versions

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#9013]
There are only few people using Bridge 2.0.30 and legacy versions. Disable coinjoin for these users to prevent ruining of coinjoin rounds.

For related discussion see [Slack](https://satoshilabs.slack.com/archives/C04QY40TJL9/p1678808090047169?thread_ts=1678802362.728489&cid=C04QY40TJL9)

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
