### ISSUE TITLE
TypeError: Cannot destructure property 'BridgeV2' of 'transport_1.default' as it is undefined on Trezor connect 9.0.7

### ISSUE THREAD

**Issue by mholtzman** [trezor/trezor-suite#9047]
**Describe the bug**

Getting error:

`TypeError: Cannot destructure property 'BridgeV2' of 'transport_1.default' as it is undefined.`
 
when simply trying to import Trezor Connect:

 `import TrezorConnect, { DEVICE_EVENT, DEVICE, UI_EVENT, UI } from '@trezor/connect'`

This seems to have changed recently (within the last couple of days) as this is breaking in one of our automated tests.

**Info:**

@trezor/connect v9.0.7

**How to reproduce**
This happens consistently when trying to import the module.

**Comment by KayBeSee** [comment]
I'm experiencing the same issue.

**Comment by mroz22** [comment]
Update to 9.0.11 should solve this. I am still trying to figure out what exactly causes this issue for you on 9.0.7 version

**Comment by mroz22** [comment]
BridgeV2 doesnt exist anymore in the codebase.
