### ISSUE TITLE
Trying to import BTC address freezes the app sometimes

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#9055]
**Describe the bug**
When I try to import a Bitcoin address the app freezes in about 50% of the time. 

**Info:**

-   Suite Version: mobile 23.8.1 18
-   OS: iOS

**How to reproduce**

1. Navigate to `My Assets` and press `+` to import account
2. Select `Bitcoin`
3. Select `Scan QR`
4. Try yo import `Bitcoin` address via QR code
5. The app freezes and needs to be shut down

**Expected behavior**
I can import a BTC address without any issue

**Video**

https://github.com/trezor/trezor-suite/assets/48477147/2db0e5fb-de1f-41e8-8c34-69800c6e19f9

**Comment by juriczech** [comment]
https://github.com/trezor/trezor-suite/pull/9064

**Comment by bosomt** [comment]
**QA OK**

2d8e93c - [develop] - fix(mobile): freeze on attempt to import address as account (#9064)
