### ISSUE TITLE
Show public key / not backed up modal when creating a coinjoin account

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#9059]
**Describe the bug**
When creating a coinjoin account on a device without a backup, after confirmation of the "Do you want to access your coinjoin account?" prompt on the device, the _Show public key / not backed up_ modal modal window is shown by mistake. See screenshots below.

**Info:**

-   Remembered Wallet: no
-   Suite Version: macOS arm app version 23.7.2
-   OS: macOS Ventura 13.2.1
-   Bridge: version 20.0.33
-   Firmware Version: Model T: 2.6.0 Universal; Model One: 1.12.1 BTC-Only
 
**How to reproduce**

1. Go to Accounts
2. Click on "+" to add another account
3. Choose Bitcoin or Bitcoin Testnet
4. Account type select menu appears, choose coinjoin from it and confirm
5. Confirm on device
6. See the modal (that is not expected in this place and time)

**Expected behavior**
Coinoin account should be created without this warning modal. Or the warning about no backup should be tailored to the situation of adding a coinjoin account.

**Screenshots**
![Image](https://github.com/trezor/trezor-suite/assets/88533514/009d4421-a831-40db-9d82-3ebf5ea1520e)

**Additional context**

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.9.1 (41a9c13bf28edf71fe629379288a5ad685f259d1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.9.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
