### ISSUE TITLE
Coin Control not triggering validation correctly

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#9062]
This can be observed on develop with all seed:

https://github.com/trezor/trezor-suite/assets/42465546/c0482bcb-c421-48e2-96dc-ebd5f3ca3dbb

Transaction is not recomposed and the form stays in invalid state.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.9.0 (930f73d5973daa7dce5493cd08a09cfcb906c635)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
