### ISSUE TITLE
ETH data input validation bugs

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#9063]
An account with ETH or TGOR is required to test.

https://github.com/trezor/trezor-suite/assets/42465546/18a27dcf-95e0-4282-8743-507fcd3cbad9

You can see three bugs in the video:
1. The first character input should not reset the amount field.
2. There should not be a console error as 0 amount is valid when there is data (I believe we have this error in Sentry).
3. After inputting the last character towards the end of the video, there should be no validation message below amount as the value is actually valid.

**Comment by tomasklim** [comment]
2)) will be fixed here #8959





4)) wrong padding on textarea input bottom text error

**Comment by komret** [comment]
Ad 3) To fix, `trigger` `amount` validation in an effect. Currently, validation runs before the data value has changed, resulting to the incorrect validation message.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.9.0 (27f88acdf82fb86f4b78db9386ca48a6df26fe4b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
