### ISSUE TITLE
Wrong gain percentage value

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#9068]
**Describe the bug**
Gain percentage value is wrong
**Info:**

-   Suite Version: 23.6.1 (16), e700d39
-   OS: iOS

**How to reproduce**
1. transaction
2. compare values

**Expected behavior**
Correnct percentage gain

**Screenshots**
![IMG_645A7DCED891-1](https://github.com/trezor/trezor-suite/assets/57008159/bba9ab08-d0b7-431c-8062-28bbe740c808)
![IMG_3EB2E7872235-1](https://github.com/trezor/trezor-suite/assets/57008159/a3efd454-45ee-4141-befa-b7dc1c9208ae)

**Comment by Hannsek** [comment]
Plus there should be a space between the number and the percentage sign. 
![image](https://github.com/trezor/trezor-suite/assets/57008159/24c10323-1633-4028-8049-a5546bc35a71)

**Comment by bosomt** [comment]
**QA OK**

develop-TrezorSuite 23.10.1 (368) iPhone 11
