### ISSUE TITLE
Empty accounts list placeholder

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#9092]
In case the account list is empty (now possible due to added filtration #6988), we display a simple and ugly info message:

Here is the design for empty page: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=20473%3A224798&mode=design&t=amNTPxivpbZ8njp8-1

![Image](https://github.com/trezor/trezor-suite/assets/26143964/afd294ca-8add-4a49-9687-5ea6fe67cf0e)

Let's create something more representative.

**Comment by bosomt** [comment]
**QA OK**

very nice improvement !

b22b5ca - [develop] - feat(suite-native): account list placeholder component (#9269)
