### ISSUE TITLE
Add tracking event on buy buttons on Dashboard

### ISSUE THREAD

**Issue by IvaFingerova** [trezor/trezor-suite#9100]
To be able to evaluate properly the outcome of this improvement, we need to add a tracking event to the buy buttons.

**Comment by kolomaznikt** [comment]
The best solution would be to have a standalone event (e.g. `accounts/dashboard/buy`) similar to [accounts/empty-account/buy](https://www.notion.so/satoshilabs/accounts-empty-account-buy-ad35d94c38ca4241b40690c192942ff4?pvs=4) with special attribute `symbol` to be able to distinguish coins.

**Comment by LukasRada** [comment]
I have just tested the implementation and the payload in query string looks like this:
```
c_v: 23.9.0
c_type: accounts/dashboard/buy
c_commit: c9e4b81956d0797703712643619b649ca8b8bb4b
c_instance_id: lTuYOQIUZA
c_session_id: GM1USWYvJG
c_timestamp: 1692265527657
c_message_id: pulPs8q5ZW
symbol: btc
```
The whole request URL is:
`https://data.trezor.io/suite/log/web/develop.log?c_v=23.9.0&c_type=accounts%2Fdashboard%2Fbuy&c_commit=c9e4b81956d0797703712643619b649ca8b8bb4b&c_instance_id=lTuYOQIUZA&c_session_id=GM1USWYvJG&c_timestamp=1692265527657&c_message_id=pulPs8q5ZW&symbol=btc`

Is this OK? @kolomaznikt

**Comment by bosomt** [comment]
**QA OK**

```
Request URL: https://data.trezor.io/suite/log/desktop/develop.log?c_v=23.9.0&c_type=accounts%2Fdashboard%2Fbuy&c_commit=b5c24aa43350998ed132edf093927558d6dde36b&c_instance_id=vOgWKaRrxX&c_session_id=FKACdIQhr4&c_timestamp=1692693064613&c_message_id=w7v5VyKX4K&symbol=btc
```

**Info:**
 - Suite version: desktop 23.9.0 (b5c24aa43350998ed132edf093927558d6dde36b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 regular (revision b151a3db6b04d2bee0bb68470e57b822443bf83d)
 - Transport: BridgeTransport 2.0.33
