### ISSUE TITLE
Default Test XRP backend reports unknown transactions in Trezor Suite.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9102]
**Describe the bug**

Default Test XRP backend reports unknown transactions in Trezor Suite.
Sometimes it reports that transaction does not exist sometimes it exist.

https://blockexplorer.one/xrp/testnet/address/rNaqKtKrMSwpwZSzRckPf7S96DkimjkF4H
https://test.bithomp.com/explorer/rNaqKtKrMSwpwZSzRckPf7S96DkimjkF4H

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: web 23.9.0 (c01dad446692eef861d166fe4d5ff252830dc891)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: Trezor T2T1 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="697" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/3be1bcb4-b058-4b5e-904b-0f53c49ba837">

<img width="1019" alt="Screenshot 2023-08-02 at 15 41 07" src="https://github.com/trezor/trezor-suite/assets/31506317/52f47365-4913-4c25-8076-40bf6077282b">

<img width="1034" alt="Screenshot 2023-08-02 at 15 40 42" src="https://github.com/trezor/trezor-suite/assets/31506317/f2981fe0-fec5-4946-972d-a9c111c1825b">

**Comment by szymonlesisz** [comment]
`TransactionType` received from backend changed type from `Payment` to `TrustSet`

needs investigation https://xrpl.org/transaction-types.html

**Comment by szymonlesisz** [comment]
also kind of related to https://github.com/trezor/trezor-suite/issues/4942

**Comment by Hannsek** [comment]
@bosomt Do you see _unknown transactions_ also on mainnet or only on testnet?

**Comment by Hannsek** [comment]
@szymonlesisz How those two parameters are connected?

[Payment](https://xrpl.org/payment.html)
Send funds from one account to another.
[TrustSet](https://xrpl.org/trustset.html)
Add or modify a trust line.

**Comment by bosomt** [comment]
@Hannsek no i dont, we only send and receive standard transactions
i checked multiple older passphrases and account that we use/d and i have not seen a single unknown transaction

**Comment by Hannsek** [comment]
Ok, so it is some kind of non-standard transaction, right?

**Comment by bosomt** [comment]
**QA OK**

im not able to replicate this issue anymore

**Info:**
 - Suite version: desktop 24.3.2 (f67de55c38fb87853e66fafc2143fe3b17ac6e54)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.2 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
