### ISSUE TITLE
Icon in select is not working properly

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#9125]
**Describe the bug**
When you open select and close it by clicking inside it, the dropdown is closed but the icon indicating the state of the dropdown is still pointing to the top (indication open state).

**How to reproduce**

1. Go to your Ethereum account
1. Click on Send
1. See select for tokens/currencies

**Expected behavior**
The icon points down after closing by clicking inside it.

**Screenshots**

https://github.com/trezor/trezor-suite/assets/66002635/985228a0-38e0-4fcc-960f-817a3527ff2e

**Comment by sime** [comment]
This is where we can use the fancy term "chevron".

**Comment by bosomt** [comment]
**QA OK**

Duplicity with https://github.com/trezor/trezor-suite/issues/7132 :)
But finally fixed !

**Info:**
 - Suite version: desktop 23.9.0 (b1c5e1a274403a0e94696888c39c83743b69ae8a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 Universal (revision 4a6420c5dd038c06a6641331995c7b22cf4c699c)
 - Transport: BridgeTransport 2.0.33
