### ISSUE TITLE
Enable activate multiple coins when adding account

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#9133]
**Describe the bug**
Right now we enable user to activate multiple coins during onboarding and in settings but not from Accounts page when he clicks add (he can there activate just one).

**How to reproduce**

1. Go to accounts
1. Click on the plus icon next to My accounts

**Expected behavior**
Enable user to activate more coins also from adding account.

**Comment by matejkriz** [comment]
This is not a bug, more like product feedback. I've heard this suggestion from more than one person.

**Comment by komret** [comment]
Closing, unless @Hermez-cz wants us to implement it.
