### ISSUE TITLE
Two primary buttons on screen

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#9136]
**Describe the bug**
There are two buttons with primary design (green) on the user data consent screen. Not sure if this was implemented from Figma but it's generally not recommended to have two primary buttons on screen.

**How to reproduce**

1. Go to onboarding
1. Keep clicking until you are on user data consent screen

**Expected behavior**
Keep the bottom one as primary (green) and change the top one to secondary (gray).

**Screenshots**

![Screenshot 2023-08-08 at 7 43 31 PM](https://github.com/trezor/trezor-suite/assets/66002635/9cf5add3-d24c-4465-8375-6c6e10c6fdd2)

**Comment by AdamSchinzel** [comment]
Maybe not needed if this is planned #8892

**Comment by mnuky** [comment]
@AdamSchinzel we already count with improvements in #8892, I'm closing this issue
