### ISSUE TITLE
Coinjoin client not enabled: status is missing

### ISSUE THREAD

**Issue by Barlog951** [trezor/trezor-suite#9137]
**Describe the bug**
When connecting a wallet and then trying to add a CoinJoin wallet, this attempt failed and the error displayed is **Error: coinjoin client not enabled: status is missing**

I have some funds on this wallet so I hope the CoinJoin wallets are not lost

**Info:**

-   Remembered Wallet: it happens on both cases 
-   Suite Version: 23.7.2
-   Browser: name, version
-   OS: MacOS 13.4.1 and Windows 11
-   Firmware Version: 2.6.0

**Screenshots**
<img width="459" alt="Snímka obrazovky 2023-08-09 o 0 14 58" src="https://github.com/trezor/trezor-suite/assets/9975572/c50d848a-6452-4e77-abc2-cce9796fc14e">

**Additional context**
Tested on MacOS also on Windows 11
the same error was displayed when I had the Trezor remembered, the CoinJoin wallet was in status out of synch and every few minutes an error was displayed, but when I ejected the Trezor, the CoinJoin wallet could not even be added anymore

**Comment by jjstrat3** [comment]
I'm have this same issue on Windows 11.  I've tried the following with no success:

* Using with or without a VPN
* Disabling Tor than re-enabling when attempting to add the wallet
* Down-grading to a previous version of Trezor Suite
* Completely uninstalling and deleting the "@trezor" folder in AppData/Roaming before installing fresh

I've reached out to their email support, so we'll see, but I also have a fair bit of btc sitting in a coin join wallet that I can't re-add.

**Comment by Hannsek** [comment]
Same [issue](https://github.com/trezor/trezor-suite/issues/8380)?

**Comment by andrewkozlik** [comment]
Firstly, I am sure that all funds are safe.

Probably not the same issue @Hannsek, just the same symptoms. It's possible that the coordinator was down for a while. Trezor Suite currently relies on the coordinator to perform account discovery (fetching blockfilters) so if the coordinator is not responding, then Suite is unable to load it. Further investigation is needed though.

**Comment by Barlog951** [comment]
@andrewkozlik my heart just stop when this error started appearing, and I see on my founds just 0 ...

I just installed the new beta version **23.8.1** and the problem stopped
I was able to add CoinJoin wallet and synch end up successfully as well

On version **23.7.2** problem still remains

**Comment by jjstrat3** [comment]
> @andrewkozlik my heart just stop when this error started appearing, and I see on my founds just 0 ...
> 
> I just installed the new beta version **23.8.1** and the problem stopped I was able to add CoinJoin wallet and synch end up successfully as well
> 
> On version **23.7.2** problem still remains

Can confirm, using the 23.8.1 pre-release version fixes the issue for me, allowing me to re-add my CoinJoin wallet and use it.

I've also been able to consistently get the issue on 23.7.2 for the past several days, so don't see how it could be an issue with the coordinator at this point.

**Comment by andrewkozlik** [comment]
It turns out that Wasabi recently changed some configuration on their coordinator, which caused status requests from Suite to be rejected. Coincidentally the beta version didn't have this problem, which is why we were unable to reproduce it at first. Wasabi reverted the changes temporarily until most of our users have a chance to upgrade to the new Suite version, which will be fully released next week. So it should be working now for both the released version and the beta.

**Comment by bosomt** [comment]
**QA OK**

 - Suite version: desktop 23.8.1 (c6b91601f5c333a1de056fbf0b712995a96b5d90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.8.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 Universal (revision b151a3db6b04d2bee0bb68470e57b822443bf83d)
 - Transport: BridgeTransport 2.0.33
