### ISSUE TITLE
bug: account search by account label

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#9140]
metadata structure refactoring (probably) broke account search by account label 

![image](https://github.com/trezor/trezor-suite/assets/30367552/3c58bbca-10e4-4c5c-ab4f-81cf50293152)

**Comment by mroz22** [comment]
should be fixed now

**Comment by bosomt** [comment]
**QA OK**

<img width="241" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/e298b27d-bc76-4df4-b16c-00f21fa57de8">

**Info:**
 - Suite version: desktop 23.9.0 (625ccb6675c533896b97651c60fb95752325b0c3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.9.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 regular (revision b151a3db6b04d2bee0bb68470e57b822443bf83d)
 - Transport: BridgeTransport 2.0.33
