### ISSUE TITLE
ETH account with no fiat rate tokens glitches

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#9144]
**Describe the bug**
When importing an ETH account that include tokens but none of the has fiat rates, the UI is glitched. See the screenshots attached. 

example receive address: `0x24254Df1Fa059DF4755d4073198c5A16F196A197`

Fix this so an imported ETH account looks the same as any other account.

**Info:**

-   Mobile Suite Version: 23.8.1
-   OS: Both

**Screenshots**

![Image](https://github.com/trezor/trezor-suite/assets/26143964/a7d4e311-dee5-4ef7-aa76-8da7551e5da2)
![Image](https://github.com/trezor/trezor-suite/assets/26143964/515bad50-3431-4b92-97d9-1bf7d5349ccf)

**Comment by bosomt** [comment]
**QA OK**
- iPhone 11
- 8ff3761 - [develop]
