### ISSUE TITLE
Address labeling is not working for every address or account

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#9149]
**Describe the bug**
Label option is not visible on hover for every address or account. More especially in token transfer transaction type.

**How to reproduce**

1. Go to accounts (all seed)
1. Click on ETH#1

**Expected behavior**
I can label everything.

**Screenshots**

https://github.com/trezor/trezor-suite/assets/66002635/93d90cdc-9c5f-4b43-8bc3-53fb2e03c671

**Comment by Hannsek** [comment]
Duplicate of [this](https://github.com/trezor/trezor-suite/issues/3545), right?

**Comment by AdamSchinzel** [comment]
Yup
