### ISSUE TITLE
 Fiat rates are not loading in latest dev version

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9158]
**Describe the bug**
Fiat rates are not loading in latest dev version app.
Issue is not consistent, some accounts are laoding some not but `all`  value works on all accounts and day does not load on most of accounts.
`Try again` button does not fix this problem.

**Info:**

-  8ff3761 - [develop] 
- iPhone 11

**Screenshots**

![image](https://github.com/trezor/trezor-suite/assets/31506317/54c3387b-78e6-4de6-ac3c-9ffd5216f7f3)

**Comment by matejkriz** [comment]
related or not? https://github.com/trezor/trezor-suite/issues/9163

**Comment by PeKne** [comment]
> related or not? #9163

I don't think so. The solution was suite-native related fix in graph data processing.

PR https://github.com/trezor/trezor-suite/pull/9161

**Comment by bosomt** [comment]
**QA OK**

f1d7d1f - [develop] - fix(suite): RBF form DecreasedOutputs view RadioButton margin
