### ISSUE TITLE
FIAT Value of ETH tokens is not showing

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#9163]
**Describe the bug**
FIAT Value is not showing for ETH tokens for some users from 23.7.2 version.

**Steps to reproduce:**
1. Enable ETH
2. Go to ETH accounts and swithc to Tokens
3. Tokens are shown but they are not showing their FIAT value

**Info:**
 - Suite version: desktop 23.8.1 (c6b91601f5c333a1de056fbf0b712995a96b5d90)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.8.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
I should be able to see FIAT value of my ETH tokens.

**Actual result:**
I don't see FIAT value of my ETH tokens

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/48477147/08e221bc-5289-4986-8276-81335980e2f0)
![image](https://github.com/trezor/trezor-suite/assets/48477147/8e783b29-8434-476e-8fac-ccb95871d85d)

**Additional info:**
https://satoshilabs.slack.com/archives/CKZHV2G13/p1690892218934719

**Comment by g1tt** [comment]
Hi. I am running version 23.11.3 on Windows 10 22H2 and the problem still exists! Not fixed!

**Comment by Hannsek** [comment]
Should be fixed together with https://github.com/trezor/trezor-suite/issues?q=is%3Aissue+is%3Aopen+hiding.

**Comment by juanmjr** [comment]
Same problem here. No individual values for tokens and didn't show a sum value at ethereum selection asset.

Version: 23.11.5
Trezor suite - mac version

**Comment by bosomt** [comment]
**QA OK**

<img width="591" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/f6a3748c-b8e3-41e4-8d86-bc46ff7ed2c5">


**Info:**
 - Suite version: desktop 24.1.1 (c4cf80383d5f554ff118ba507b743074e73216d4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by moxim** [comment]
I'd be hesitant. So far only the value of the first token is displayed, any following are not. Does [c4cf803](https://github.com/trezor/trezor-suite/commit/c4cf80383d5f554ff118ba507b743074e73216d4) consider more than just the first token?

**Comment by bosomt** [comment]
Found the account with more than 1 tokens that have value ;)

<img width="630" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/f7b046e6-59d0-4977-9c53-294160b1e5f7">
