### ISSUE TITLE
My axie marketplace got hacked even it is connected to trezor

### ISSUE THREAD

**Issue by jhonreezy** [trezor/trezor-suite#9164]
Why did i got hacked even I have trezor for my account? my ronin accounts got swept

**Comment by sime** [comment]
@jhonreezy This is not a support forum. Please reach out to Trezor Support https://trezor.io/support

Be mindful of which contracts you approve. Approving malicious contracts can sweep accounts. You can see which contracts you have approved here: https://revoke.cash/
