### ISSUE TITLE
Accounts tab - order of network filter is different than accounts order

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#9165]
**Describe the bug**
The order of networks in the sidebar network filter is now based on the order in which the networks were enabled.

**Info:**

-   Suite Version: 24.8.1

**How to reproduce**

1. Disable all networks in `Settings` in `Coins` section
2. Enable `Litecoin`, `Polygon`, `Dogecoin`, `Bitcoin`
3. Check sidebar order of networks in filter vs order of accounts 
4. `Litecoin`, `Polygon`, `Dogecoin`, `Bitcoin` vs `Bitcoin`, `Polygon`, `Litecoin`, `Dogecoin`

**Expected behavior**
Networks filter should have same order as networks in Settings / accounts tab

**Screenshots**
![Screenshot 2024-10-21 at 11 59 35](https://github.com/user-attachments/assets/89d11bf7-9627-4a0b-ae7b-3a0a7799e240)
![Screenshot 2024-10-21 at 12 00 07](https://github.com/user-attachments/assets/1bf1dc34-f137-459a-8dc5-c5d5735f1ad4)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.12.0 (c4e3d8a47e8ee6e26d264f29f3470336ab0da5c2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport
