### ISSUE TITLE
Disable the Node.js integration in all renderers that display remote content

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#917]
https://github.com/electron/electron/blob/master/docs/tutorial/security.md#2-do-not-enable-nodejs-integration-for-remote-content

**Comment by keraf** [comment]
Both places where `BrowserWindow` (`/packages/suite-desktop/src-electron/electron.ts` and `/packages/suite-desktop/src-electron/oauth.ts`) is initialized, the `nodeIntegration` parameter is explicitly set to `false` already. Closing issue.
