### ISSUE TITLE
[EPIC] Welcome flow with connected Trezor

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9182]
As a user I would like to get some intro about the mobile app capabilities in order to set up right my expectations.

**Highlevel acceptance criteria:**
When user opens the app for the first time, he is guided through welcome flow
If the user opens the app for second and more time, we don't display it again

Figma: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=2313%3A294&mode=design&t=MpeLRWtYVToFTXnX-1

Acceptance criteria per platform:
**Android (with connected Trezor)**
- When user install the app, first we display Welcome to the app intro flow
- First user sees Welcome to Trezor Suite App screen, with link to eShop (in case app is downloaded without having trezor device)
- When user clicks on "Get started", he is redirected to second screen with information that he can connect the Trezor Device. User can go back about one screen. User can continue to next screen by clicking on "Next"
- The third screen explains that user can generate and verify receive addresses. User can go back about one screen. User can continue to next screen by clicking on Next
- The fourth screen explains that user can track his favourite coins with portfolio tracker. User can go back about one screen. User can continue to next screen by clicking on Continue
- Fifth screen is Consent to analytic tracking. If user keeps the switcher enabled, we can track anonymously the activity, if user disables the tracking, we don't track any activity. 
- When user clicks confirm, he is landed on "empty app" screen and the he is offered enable Biometric. 
- If user clicks on "I'll do it later in Settings" - no biometric is triggered and message is closed
- If user clicks on Enable, we trigger Biometric feature and let user to secure the app with Biometric right away. 

iOS
- When user install the app, first we display Welcome to the app intro flow
- First user sees Welcome to Trezor Suite App screen, with link to eShop (in case app is downloaded without having trezor device)
- When user clicks on "Get started", he is redirected to second screen with information that he track balances by syncing the coins. User can go back about one screen. User can continue to next screen by clicking on "Next"
- The third screen explains that user can generate receive addresses. User can go back about one screen. User can continue to next screen by clicking on Next
- Fourth screen is Consent to analytic tracking. If user keeps the switcher enabled, we can track anonymously the activity, if user disables the tracking, we don't track any activity. 
- When user clicks confirm, he is landed on "empty app" screen and the he is offered enable Biometric. 
- If user clicks on "I'll do it later in Settings" - no biometric is triggered and message is closed
- If user clicks on Enable, we trigger Biometric feature and let user to secure the app with Biometric right away. 

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/9632
- [ ] https://github.com/trezor/trezor-suite/issues/9633
```

**Comment by mnuky** [comment]
@bosomt this epic can be already tested on Android and iOS

**Comment by bosomt** [comment]
### iOS - latest develop version- 23.11.1 (373) 7b68bab - Tested on latest iOS and iPhone 11
  - on-boarding follows steps as described above 

### Android - latest develop version - 23.11.1 (576) c30d593 - Tested on Nothing phone 1 and Android 13 
  - on-boarding follows steps as described above
