### ISSUE TITLE
[BUG] Negative account balance in Trezor Suite is shown

### ISSUE THREAD

**Issue by kravens** [trezor/trezor-suite#9195]
**Describe the bug**
The same bug as #8525 is there again for me. After recreating my CoinJoin Account in v23.8.1 of Trezor Suite (desktop version).

**Info:**

-   Remembered Wallet: yes
-   Suite Version: v23.8.1 (latest Early Access release)
-   Browser: -
-   OS: Windows 11
-   Bridge: ?
-   Firmware Version: model T, 2.6.0

**How to reproduce**

1. Receive bitcoin on an address that has index 2 or higher before receiving on address with index 1.
2. Spend bitcoin from the wallet
3. Recreate account in Trezor Suite
4. See faulty (in my case negative) balance in Trezor Suite.

**Expected behavior**
The wallet should properly scan the transaction history of all addresses (within a reasonable gap-limit) and display the correct balance of the wallet/account. In my case it should have shown 0 BTC as correct balance.

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/9646902/2699ac59-49f0-452c-a683-d2065425d018)

**Additional context**
After a Rescan account (in Details tab of CoinJoin account) the correct balance of 0 sat is shown again, perhaps this could be triggered automatically if the balance shown is impossible (Bitcoin has no negative balances).

**Comment by marekrjpolak** [comment]
Hi @kravens,

> After a Rescan account (in Details tab of CoinJoin account) the correct balance of 0 sat is shown again

That's exactly what I wanted to suggest, so it's good to hear it worked.

> perhaps this could be triggered automatically if the balance shown is impossible (Bitcoin has no negative balances).

Agreed, I'll think about it. The thing is that this only works when the missing tx is `receive` (well, first tx on any account **has** to be `receive`, so this is probably fine) and the utxo was spent after. I mean, we can automatically detect inconsistent tx history, but we cannot detect consistent but incomplete one. Still, it would definitely be an improvement.

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
