### ISSUE TITLE
UI polishing - Text inputs

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#9207]
The current production version of text input fields contains some inconsistencies compared to the UI design.

Acceptance criteria:
- text input reflects [UI design](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=1-1960&mode=dev)
- specifically:
  - [x] input does not contain a border if it is in an unfocused state
  - [x] unfocused input has a correct shade of grey
  - [x] confirm button on xpub import screen is not displayed until the input is filled
  - [x] input on xpub import screen is always visible while focused
  - [x] input extends to multiple lines if needed
  - [ ] input may optionally contain [paste button on the right side](https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=18855-120562&mode=dev) (blocked by https://github.com/trezor/trezor-suite/issues/9084)
  - [x] on clicking the rename button in account detail, the label input keyboard is opened and input focused so the user can start typing immediately.

**Comment by bosomt** [comment]
**QA OK**

b22b5ca - [develop] - feat(suite-native): account list placeholder component (#9269)
