### ISSUE TITLE
Anything after 23.3.2 fails with KERNEL32.DLL error

### ISSUE THREAD

**Issue by IndustrialOne** [trezor/trezor-suite#9211]
Installs successfully but as soon as I try to run it, I get a KERNEL32.DLL error, I lost the exact message but something to do with entry point failure. I have MS visual C++ redistributable 2015-2022 installed. I narrowed the problem down to version 23.4. That and anything after it fails with same error.

I use Windows 7, if my only problem is that Trezor Suite no longer supports my obsolete OS, I'll take it.

**Comment by tomasklim** [comment]
Electron does not support Windows 7 from version `23` and we use version `24` https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

You are probably also not enable to run newest Google Chrome browser

To run Trezor Suite, you can use web version
