### ISSUE TITLE
Add Hungarian and Italian as community languages

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#9214]
**Spec:** Please add Hungarian and Italian as community languages (from Crowdin) and move Czech to community languages as well (= for now, only English will be an official language, but that will change soon)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 23.9.0 (864b94e8e02aed435bed7254b3e2f66b3901a449)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/116.0
 - OS: MacIntel
 - Screen: 2160x1350
 - Device: 
 - Transport: BridgeTransport 2.0.33
