### ISSUE TITLE
0.1 Lite staking

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9219]
### User Story
As an Ethereum user
I want to stake my Ethereum
So that I can earn rewards

### Acceptance Criteria
Given I am on the staking tab
When I enter 1 ETH
And I press Continue
Then I should see 'Confirm on Trezor' dialog
And I see '1 ETH' on my Trezor

Given I am on the staking tab
Then I should see 'Staking: 1 ETH'
And I should see 'Staked: 0 ETH'
And I should see 'Rewards: 0 ETH'

Given I am on the staking tab
And I wait 30 days
Then I should see 'Staking: 0 ETH'
And I should see 'Staked: 1 ETH'
And I should see 'Rewards: 0 ETH'

Given I am on the staking tab
And I wait 7 days
Then I should see 'Staking: 0 ETH'
And I should see 'Staked: 1 ETH'
And I should see 'Rewards: 0.0001 ETH'

```[tasklist]
### Tasks
- [ ] https://github.com/trezor/trezor-suite/issues/9220
- [ ] https://github.com/trezor/trezor-suite/issues/9222
```

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
