### ISSUE TITLE
Deprecation warning during Suite launch from command line

### ISSUE THREAD

**Issue by filipponeri** [trezor/trezor-suite#9224]
**Describe the bug**
when launching Trezor Suite on Ubuntu 22.04 from the command line I receive the following Deprecation Warning. How do I deal with it? Thanks!

>./Trezor-Suite-23.8.1-linux-x86_64.AppImage
(node:1016272) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `trezor-suite --trace-deprecation ...` to show where the warning was created)

**Info:**

-   Remembered Wallet: yes
-   Suite Version: APP 23.8.1-linux-x86_64
-   Browser: command line
-   OS: Ubuntu 22.04
-   Bridge: trezor-bridge_2.0.27 
-   Firmware Version: 2.6.0 
-

**How to reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by RabbitHole26** [comment]
Hello @matejkriz, 

I am experiencing this issue as well. Does this affect the security of the suite software in any significant capacities? I suppose it doesn't since the .AppImage file is still hosted on your website but I rather check before hooking up the device.

Thank you.

**Comment by doolio** [comment]
Also see this on Debian 11.

**Comment by matejkriz** [comment]
Thank you for your reports! This warning is nothing new and we do not use that deprecated API directly in our codebase, but one of our old dependency use it. We do not know about any abuse of this old API. 

Here is some explanation of the context of the warning: https://nodesource.com/blog/understanding-the-buffer-deprecation-in-node-js-10/

@mroz22 The warning during app start comes from usage of bytebuffer dependency, can we replace it with something better maintained? https://github.com/trezor/trezor-suite/blob/develop/packages/protobuf/src/encode.ts/#L74

**Comment by matejkriz** [comment]
BTW it's not linux related, it can be seen on any platform running Suite from command line

**Comment by mroz22** [comment]
in general, `bytebuffer` should be replacable. We should do it.

**Comment by mroz22** [comment]
`yarn why bytebuffer` does not give any results anymore. Of course there could be more deprecated usages of something somewhere but for now, I am closing it as completed
