### ISSUE TITLE
Remember Wallet as a default option

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#9226]
As a user I would like to access my accounts even without my trezor is connected in order to see the amount and transactions that are happening.

**Comment by Hermez-cz** [comment]
Exploration WIP: https://www.notion.so/satoshilabs/Remember-mode-dfd8a9d41c4a495ca36c4c1ca4b0282d?pvs=4

**Comment by komret** [comment]
Making this default is not planned, closing.
