### ISSUE TITLE
Warn user when he wants to forget coinjoin account

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#9227]
User might be surprised that coinjoin balance will not appear automatically without remembered accounts.
To prevent heart attack - warn user that removal of coinjoin account hides it from overal balance for upcoming app loads.

Better to implement https://github.com/trezor/trezor-suite/issues/9226 first.

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
