### ISSUE TITLE
Overlay when app is in the background

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9235]
As a user I would like to see some nice overlay when the app is in the background and I'm swiping between the apps because it increases my privacy (app content is not visible).
Current version of the app displays only white screen. Please add there logo, now it looks weird and buggy. 
Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=19697%3A120233&mode=design&t=E9EKkYqCDC7YY97S-1

**Comment by bosomt** [comment]
**QA OK**

3309f30 - [develop] - Feat\/blurred screen overlay (#9380)
* fix(suite-native): biometrics overlay on Android
Fixes #9338
* feat(suite-native): screen-overlay package
* feat(suite-native): biometrics blurred overlay
Resolves #9235
* feat(suite-native): sheets blurred background overlay
Resolves #8576

no overlays in latest builds

![telegram-cloud-photo-size-4-6050741766623181939-y](https://github.com/trezor/trezor-suite/assets/31506317/fdbff362-7392-4983-b716-113c385c0056)

**Comment by PeKne** [comment]
@bosomt do you have biometrics set on? The overlay is shown only if the biometrics are enabled.

**Comment by bosomt** [comment]
Looks like this when i enable bio-metrics.
Why pink ? :) And i still see my portfolio /ttill i enable discreet mode  :)

<img width="429" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/4a50b545-276c-4fb2-93c5-655bcdf0f016">

**Comment by PeKne** [comment]
Wtf, the overlay filter is somehow bugged. On the simulator it shows a nice blurred view, for some strange reason it is just some color (pink) filter on a physical device. Let me investigate.

**Comment by PeKne** [comment]
@bosomt There was a problem in the underlying library that we used, that make it look wrong on the physical. Library was updated and should be already working as expected after merging https://github.com/trezor/trezor-suite/pull/9395. Please test again.

**Comment by bosomt** [comment]
**QA OK**

tested on iPhone 11 and Samsung Android tablet /both with biometrics enabled/
3abc6cf - [develop] - chore(suite-native): downgrade skia to v.0.1.202 (#9408)

**Comment by bosomt** [comment]
Overlay is available only when bio-metrics is enabled.
Is that expected @mnuky  ?

iPhone 11
develop-TrezorSuite 23.10.1 (370) 

![telegram-cloud-photo-size-4-5929058187711987142-y](https://github.com/trezor/trezor-suite/assets/31506317/f05660e6-7c5d-4739-8c17-1956476d2b1d)
![telegram-cloud-photo-size-4-5929058187711987143-y](https://github.com/trezor/trezor-suite/assets/31506317/ad09c39d-5f04-47b6-ae3e-173d98f60d05)

**Comment by bosomt** [comment]
**QA NOK**

no overlay on android 13 on Nothing phone 1 even biometrics enabled 



![Image](https://github.com/trezor/trezor-suite/assets/31506317/e44ef2b4-91f2-4e40-b548-82b5de3bacbd)

**Comment by mnuky** [comment]
@bosomt - nope, it is not expected, the overlay should be there no matter of Biometrics settings

**Comment by bosomt** [comment]
**QA NOK**

overlay not available when biometrics is disabled
Android 13 , Nothing phone 1 
23.11.1 (568) hash 48bce28

**Comment by juriczech** [comment]
Relates to https://github.com/trezor/trezor-suite/issues/9955
