### ISSUE TITLE
Grabber is out of remove account modal

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9244]
**Describe the bug**
Grabber is out of remove account modal

**Info:**

-   Mobile Suite Version: bf64bce - [develop] - fix(suite-native): bottom sheet grabber (#9234)
-   OS: name, version iPhone 11 latest macOS

**How to reproduce**

1. Try to remove imported account.
2. observe warning modal.

**Screenshots**
![telegram-cloud-photo-size-4-5996701955528965595-y](https://github.com/trezor/trezor-suite/assets/31506317/32f03791-0d6f-47e0-b93d-8fe6003386d4)

**Comment by mnuky** [comment]
won't fix in the near future
