### ISSUE TITLE
Lite unstaking: Pending/Unstaking balances

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9246]
### User Story

As a staker
I want to unstake my Ethereum
So that I can buy NTFs

### Acceptance criteria

Given I am on the staking tab
Then I should see 'Unstaking: 1 ETH'
And I should see 'Staking: 0 ETH'
And I should see 'Staked: 0 ETH'
And I should see 'Rewards: 0 ETH'

Given I am on the staking tab
And I wait 7 days
Then I should see 'Ready to claim: 1 ETH'
And I should see 'Staking: 0 ETH'
And I should see 'Staked: 0 ETH'
And I should see 'Rewards: 0 ETH'

### Screens

![image](https://github.com/trezor/trezor-suite/assets/216917/dad7c375-0cb8-4b72-9540-37cecbfc32e7)
![image](https://github.com/trezor/trezor-suite/assets/216917/918fe14c-1812-4451-a6e7-98247a97f262)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
