### ISSUE TITLE
Lite unstaking: Unstake variable amount

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9247]
### User Story

As a staker
I want to unstake my Ethereum
So that I can buy NTFs

### Acceptance criteria

Given I am on the staking tab
And I see 'Staked: 1 ETH'
When I enter '1 ETH' into 'Unstake' input field
And I click 'Unstake' button
Then I should see 'Confirm on Trezor' dialog
And I see '1 ETH' on my Trezor

### Screens

![image](https://github.com/trezor/trezor-suite/assets/216917/de68f16f-bf95-41e5-9e35-7c82f75c872c)
![image](https://github.com/trezor/trezor-suite/assets/216917/c2e0eaab-0398-432b-954b-2b58b43ef0f2)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
