### ISSUE TITLE
Lite claiming: Claim balance

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9249]
0.3 Lite claiming

### User Story

As an Ethereum unstaker
I wanto claim my unstaked Ethereum
So that I can buy that new NFT

### Acceptance Criteria

Given I on the staking tab
And I see 'Ready to claim 1 ETH'
When I click on 'Claim'
Then I should see 'Claim form'

Given I see the 'Claim form'
And I see '1 ETH'
When I click on 'Claim'
Then I should see 'Confirm on Trezor' dialog
And I see 'Claim' on my Trezor

Given I on the staking tab
Then I should see '1 ETH' in balance

### Screens

![image](https://github.com/trezor/trezor-suite/assets/216917/122fdc0d-e674-47f5-b4eb-9fc3a6c3e840)
![image](https://github.com/trezor/trezor-suite/assets/216917/24fe91ac-0cb8-4e89-91bb-7304fe07fadb)

**Comment by bosomt** [comment]
**QA OK**

claimed, claim modal looked as expected



![Image](https://github.com/trezor/trezor-suite/assets/31506317/7bcae38a-c75a-4867-b558-7967c003da19)

**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
