### ISSUE TITLE
0.3 Lite claiming: Claim balance

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9250]
### User Story

As an Ethereum unstaker
I wanto claim my unstaked Ethereum
So that I can buy that new NFT

### Acceptance Criteria

Given I on the staking tab
And I see 'Ready to claim 1 ETH'
When I click on 'Claim'
Then I should see 'Claim form'

Given I see the 'Claim form'
And I see '1 ETH'
When I click on 'Claim'
Then I should see 'Confirm on Trezor' dialog
And I see 'Claim' on my Trezor

```[tasklist]
### Tasks
- [ ] #9249
```

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
