### ISSUE TITLE
Warn user before closing Suite

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#9251]
Mainly during running coinjoin.

Related screen from Wasabi wallet:
![Screenshot 2023-08-24 at 14 20 44](https://github.com/trezor/trezor-suite/assets/26002916/7abce2ba-1865-4d73-9ee9-1c755a91bfc2)

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
