### ISSUE TITLE
Staking: Empty state + Modal

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9253]
### User Story

As an Ethereum user
I want to stake Ethereum
So that I can earn a return on my hodlings

### Acceptance Criteria

Given I am on the staking tab
Then I should see 'Staking Ethereum' heading
And I should see 'What is staking?'
And I should see a button 'Start staking'
When I click on 'Start staking'
Then I should see 'Staking in a nutshell'

Given I see 'Staking in a nutshell'
When I click on 'Got it'
Then I should see 'Stake Ethereum'

Given I see 'Staking in a nutshell'
When I click on 'X'
Then I should see 'What is staking?'

### [Screens](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6218-19002&mode=design&t=2gxlGVuOcreATUC3-4)

![image](https://github.com/trezor/trezor-suite/assets/216917/7a750777-b0d1-4be9-8c68-83296e34cb6f)
![image](https://github.com/trezor/trezor-suite/assets/216917/ffa3c2be-e30b-40d2-84ee-bec181aa14e7)

**Comment by sime** [comment]
Update the description to include behaviour when 'X' is clicked. cc: @shotgunofdeath

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
