### ISSUE TITLE
Staking: Stake Min/Max + ETH to Fiat pairing

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9255]
### User Story

As an Ethereum user
I want to stake Ethereum
So that I can earn a return on my hodlings

### Acceptance Criteria

Given I see 'Stake Ethereum'
And I see my available balance
When I type in '500' into the USD field
Then I should see 0.3 in the ETH field

Given I have a balance of 1 ETH
When I type in '1' into the ETH field
Then I should see the warning 'not possible to stake all your funds'
And the 'Continue' button is disabled

Given I have a balance of 1 ETH
When I click '100%'
Then I should see '0.97' minus current ETH fee into the ETH field
And I should see a message, 'We’ve left 0.03 ETH out so you will be able to pay for withdrawal fees"

Given I have a balance of 1 ETH
When I input more than '0.97' minus current ETH fee into the ETH field
Then I should see a message, 'We recommend you to leave 0.03 ETH so you will be able to pay for withdrawal fees"

Given I have a balance of 1 ETH
When I enter '0.09' in the ETH field
Then I should see a message: 'Minimum stake is 0.1 ETH'
And the 'Continue' button is disabled

### [Screens](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6218-23908&mode=design&t=2gxlGVuOcreATUC3-4)

![image](https://github.com/trezor/trezor-suite/assets/216917/77c27f99-bcfb-4de8-9580-326ba5bcc07a)

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
