### ISSUE TITLE
Staking: Maximum fee + Custom

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9257]
### User Story

As an Ethereum user
I want to stake Ethereum
So that I can earn a return on my hodlings

### Acceptance Critieria

Given I am on the 'Stake Ethereum' modal
When I hover over 'Maximum fee'
Then I should see a tooltip
And it should read 'Maximum fee is the paid to the network to ensure your transaction gets processed.'

Given I see 'Maximum fee'
And 'Recommended' is selected
Then ETH value should reflect the current [gas](https://etherscan.io/gastracker) [price](https://ethgasalerts.xyz/) for the contract execution

Given I see 'Custom'
When I click it
Then I should see the input field 'Gas limit'
And I should see the input field 'Gas price'

Given the maximum fee is '0.000021'
And the gas limit is '21000'
And the gas price is '1'
When I enter '30' into 'Gas price'
Then the maximum fee should be '0.00063'

Given I enter a Custom gas price
When I go over funds
Then I should see 'Insufficient funds'

### [Screens](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6218-23908&mode=design&t=2gxlGVuOcreATUC3-4)
![image](https://github.com/trezor/trezor-suite/assets/216917/133b5d42-4cf7-4336-82fb-735da84f7f04)

**Comment by bosomt** [comment]
There is no custom fee.
Is that expected ?



![Image](https://github.com/trezor/trezor-suite/assets/31506317/6e14544d-7079-479e-b3b1-7d1abc982d4e)



![Image](https://github.com/trezor/trezor-suite/assets/31506317/3ad0b607-4918-4b73-8406-cd7aa2bfd4e7)


**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by sime** [comment]
Re-opening as custom fee use case not implemented.

**Comment by tomasklim** [comment]
Closing in favor of #11564
