### ISSUE TITLE
Staking: Returns projection

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9258]
### User Story

As an Ethereum user
I want to stake Ethereum
So that I can earn a return on my hodlings

### Acceptance Criteria

Background: Yearly rate is dynamic

Given I am on the 'Stake Ethereum' modal
And the Yearly rate is 5%
When I enter '1' into the ETH column
Then I should see an estimated year gain of '0.05 ETH = $82.27*'

### [Screens](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6218-23908&mode=design&t=2gxlGVuOcreATUC3-4)
![image](https://github.com/trezor/trezor-suite/assets/216917/e6175e7d-bce8-415b-be9f-6acc12c0be6c)

**Comment by tomasklim** [comment]
@sime Please update

Kraken UI solution


https://github.com/user-attachments/assets/67726170-ae29-4344-a49a-35dd8862c8f8

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
