### ISSUE TITLE
Staking: Staking pool waiting period

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9259]
### User Story

As an Ethereum user
I want to stake Ethereum
So that I can earn a return on my hodlings

### Acceptance Criteria

Background: 'Add to staking pool' value is dynamic

Given I am on the 'Stake Ethereum' modal
Then I should see '35 days' next to 'Add to staking pool'

### [Screens](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6218-23908&mode=design&t=2gxlGVuOcreATUC3-4)
![image](https://github.com/trezor/trezor-suite/assets/216917/51ab66d9-41b4-40b5-9220-4b876f64decc)

**Comment by tomasklim** [comment]
@sime Please update

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33
