### ISSUE TITLE
Staking: Confirm dialog + Sign TX

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9267]
### User Story

As an Ethereum user
I want to stake Ethereum
So that I can earn a return on my hodlings

### Acceptance Criteria

Background: 'Add to staking pool' value is dynamic

Given I have 1 ETH to stake on 'Stake Ethereum' form
And I have sufficient balance
When I click 'Continue'
Then I should see 'Confirm'

Given I see 'Confirm'
Then I should see '35 days'
And I should see 'Confirm to stake' is disabled

Given I see 'Confirm'
When I click on 'I acknowledge the above about staking'
Then I should see 'Confirm to stake' is enabled

Given 'Confirm to stake' is enabled
When I click on 'Confirm to stake'
Then I should see 'Confirm on Trezor'

Given I see 'Confirm on Trezor'
Then I should see 'Amount to stake'
And I should see '1 ETH'

Given I am in tx review modal
When I click on 'X' (Cancel)
Then It should take me back to staking form modal

### [Screens](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6218-24052&mode=design&t=biDstCGFMVCBHo23-4)
![image](https://github.com/trezor/trezor-suite/assets/216917/e223cd8f-55e3-4555-a6b3-0e02579dd952)
![image](https://github.com/trezor/trezor-suite/assets/216917/db8129fe-f15c-46bc-873e-3bcefa1cba56)

**Comment by bosomt** [comment]
**QA OK**

So far steps on device does not match sign modal
- older firmware - expected 
- new firmware - needs new signatures
- will retested here https://github.com/trezor/trezor-suite/issues/10593#issuecomment-1975086118

**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by sime** [comment]
Re-opened as delay is hard-coded to 35 days.

**Comment by sime** [comment]
Re-check as domains as Trezor domains have been whitelisted.

**Comment by bosomt** [comment]
1. [Learn more](https://suite.corp.sldev.cz/suite-web/develop/web/accounts/staking#) button is still not configured...

2. still 35 days

<img width="492" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/f0db4e17-3308-44d9-ba5e-c86ebaba8858">


**Info:**
 - Suite version: web 24.4.0 (2d338465bccb7e05003e29047c7baebe4b8c73c9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.4.0 (3a5dee13187d9decb0592c009a9c9e1d5704a7bc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
