### ISSUE TITLE
Staking: Pending

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9268]
### User Story

As an Ethereum user
I want to stake Ethereum
So that I can earn a return on my hodlings

### Acceptance Criteria

Given I have confirmed staking on Trezor
Then I should see 'Pending'
And I should see 'Your ETH is getting ready 1 ETH'
And I should see 'Staked 0.0 ETH'
And I should see 'Rewards 0.0 ETH'
And I should see APY
And I should see Reward payout frequency

### [Screens](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6218-20178&mode=design&t=biDstCGFMVCBHo23-4)

![image](https://github.com/trezor/trezor-suite/assets/216917/d375f90f-60c1-4ad1-8991-f11684939192)

**Comment by bosomt** [comment]
**QA NOK**

i see `Transaction confirmed` immediately even its not confirmed

![Image](https://github.com/trezor/trezor-suite/assets/31506317/0d5da0f7-544a-4296-ae99-c6cffa80aa08)

**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.4.0 (fdd09c1115e32052c305e4f58624ab99c43d0149)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
