### ISSUE TITLE
Staking: In progress staking 

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9272]
### User Story

As an Ethereum user
I want to stake Ethereum
So that I can earn a return on my hodlings

### Acceptance Criteria

Given I have staked 1 ETH
When my staking transaction is confirmed
Then I should then I should not see 'Pending'
And I should see 'Add to staking pool 35 days'

Given my staking transaction is confirmed
When I wait 7 days
Then I should see 'Add to staking pool 28 days'
And I should see 'Your ETH is waiting to add to staking pool 1 ETH'

### Screens
![image](https://github.com/trezor/trezor-suite/assets/216917/ef3d7269-b02f-4b41-98d5-530a02d69723)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.6.5 regular (revision a784c4046e79ae138f9a7a9c5e97d2f6771140eb)
 - Transport: BridgeTransport 2.0.33

**Comment by sime** [comment]
Re-opening, as time estimation is missing. 


![310522577-498b03dc-ffaf-4a6e-bbac-696d4c0ec5ae](https://github.com/trezor/trezor-suite/assets/216917/e52ffd58-28a2-419e-b074-708e29059c49)

**Comment by tomasklim** [comment]
I can see it, can you recheck?
![Screenshot 2024-03-13 at 14 22 00](https://github.com/trezor/trezor-suite/assets/33235762/ef251314-ad45-4d7e-a07b-7b44f78c1be8)

**Comment by bosomt** [comment]
I can see it now on 24.3.1 

<img width="409" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/56ded4d2-9d76-459f-876b-637101f9cc8b">
