### ISSUE TITLE
Staking: Staked

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9274]
### User Story

As an Ethereum user
I want to stake Ethereum
So that I can earn a return on my hodlings

### Acceptance Criteria

Background: Reward estimation calculation
APY = 5% (dynamic)
Rounding down = 75% (under promise, overdeliver)
(0.05 * 75%) / 100 = 0.0375
(Total ETH staked * 0.0375) / 52 (weeks of a year)
Example: (0.1 ETH * 0.0375) / 52 = 0,000721153846154 ETH

Given I have staked 0.1 ETH
When 35 days have passed
Then I should see 'Staked 0.1 ETH'
And I should '0.1 ETH' next to the piggy bank icon

Given I have staked 1 ETH
And the APY is 5%
Then I should see the estimated reward as '0,00007 ETH'
And it should be 5 decimal places

### [Screens](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6218-20733&mode=design&t=biDstCGFMVCBHo23-4)

![image](https://github.com/trezor/trezor-suite/assets/216917/10268691-49f4-406c-ac2c-03815939288f)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
