### ISSUE TITLE
Bottom of Get help section incorrectly set 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9275]
**Describe the bug**
Observe `Get help` section scroll issue on video.
 
**Info:**

-   Mobile Suite Version:3659e0f - [develop] - feat(suite-native): message system ui (#9105)
-   OS: iPhone, latest macOS

**How to reproduce**

1. Go to `Settings`
1. Click on `Get help`
1. Scroll down and observe

**Screenshots**

https://github.com/trezor/trezor-suite/assets/31506317/6a7c7fae-5ac3-41dc-b985-e79f9b52fd0e

**Comment by STew790** [comment]
**QA OK**
Fixed in develop.

24.5.0 https://github.com/trezor/trezor-suite/commit/45e45055a48875b82f8b6c044a81b597ccdad63f
