### ISSUE TITLE
Unstaking: Variable amount

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9278]
### User Story

As a staker
I want to unstake my Ethereum
So that I can buy NTFs

### Acceptance Criteria

Given I have 1 ETH pending stake
Then the button 'Unstake to claim' button should be disabled

Given I have 1 ETH staked
When I click on 'Unstake to claim'
Then I should see 'Unstake' modal

Given I see the 'Unstake' modal
When I click on 'Other amount'
Then I should see ETH input field

Given I see an ETH input field
When I type in 1.1 ETH
Then I should see an error 'Insufficient funds' 

Given I see an ETH input field
When I type in 0.5 ETH
And I press 'Unstake'
Then I should see 'Confirm on Trezor'

Given I see 'Confirm on Trezor'
Then I should see 'Amount to unstake 0.5 ETH'

### [Screens](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6218-23911&mode=design&t=biDstCGFMVCBHo23-4)

![image](https://github.com/trezor/trezor-suite/assets/216917/3aa03206-4218-4779-8864-1a2e6a0ee3e8)
![image](https://github.com/trezor/trezor-suite/assets/216917/63bad73c-8975-4a5e-a87d-5e49685f6e08)
![image](https://github.com/trezor/trezor-suite/assets/216917/53fe96ef-8775-462b-8891-3267a5bd6205)

**Comment by tomasklim** [comment]
TODO: custom fee and other amount slider

**Comment by tomasklim** [comment]
Closing in favor of #11564 and #11566
