### ISSUE TITLE
Unstaking: In progress unstaking

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9280]
### User Story

As a staker
I want to unstake my Ethereum
So that I can buy NTFs

### Acceptance Criteria

Given I have 1 ETH staked
When I unstake 0.5 ETH
Then I should see 'Unstaking 0.5 ETH (ETA 7 days)'

Given I unstaked 0.5 ETH
When I wait 3 days
Then I should see 'Unstaking 0.5 ETH (ETA 4 days)'

### [Screens](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6218-21930&mode=design&t=biDstCGFMVCBHo23-4)

![image](https://github.com/trezor/trezor-suite/assets/216917/d8639b29-5635-4356-9d83-16eaaa6332ac)

**Comment by bosomt** [comment]
**QA OK**

but no info about days i have to wait /unstaked 3 days ago/



![Image](https://github.com/trezor/trezor-suite/assets/31506317/b5a0173b-de94-4bc8-a835-81567e9afc12)

**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
