### ISSUE TITLE
Claiming: Claiming unstaked ETH

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9282]
### User Story

As an Ethereum unstaker
I wanto claim my unstaked Ethereum
So that I can buy that new NFT

### Acceptance Criteria

Given I unstake 1 ETH
When I have wait 7 days
Then I should see 'Unstaked and ready to claim 1 ETH'

Given I see 'Unstaked and ready to claim 1 ETH'
When I click 'Claim'
Then I should see 'Claim' modal

Given I see 'Claim' modal
And I see '1 ETH'
When I click on 'Claim'
Then I should see 'Confirm on Trezor'

### [Screens](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6218-23913&mode=design&t=biDstCGFMVCBHo23-4)

![image](https://github.com/trezor/trezor-suite/assets/216917/fdc9a81a-521e-4ea8-98dd-b5bf0639d720)
![image](https://github.com/trezor/trezor-suite/assets/216917/9bc12c08-3883-413f-9466-ae429f15c82a)

**Comment by tomasklim** [comment]
TODO: custom fee

**Comment by tomasklim** [comment]
Closing in favor of #11564
