### ISSUE TITLE
3. Claiming

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9283]
### User Story

As an Ethereum unstaker
I wanto claim my unstaked Ethereum
So that I can buy that new NFT

```[tasklist]
### Tasks
- [ ] #9282
- [ ] https://github.com/trezor/trezor-suite/issues/9284
- [ ] https://github.com/trezor/trezor-suite/issues/11587
```

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.4.0 (fdd09c1115e32052c305e4f58624ab99c43d0149)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
