### ISSUE TITLE
Claiming: In-progress and successful claiming

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9284]
### User Story

As an Ethereum unstaker
I want to claim my unstaked Ethereum
So that I can buy that new NFT

### Acceptance Criteria

Given I have 1 ETH unstaked
When I claim it
Then I should see 'Claim pending'

Given I have 'Claim pending'
When the transaction confirms
Then I should see 'ETH successfully claimed'
And I should see my ETH balance update

### [Screens](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6488-27919&mode=design&t=biDstCGFMVCBHo23-4)

![image](https://github.com/trezor/trezor-suite/assets/216917/1e7a2f6f-040f-4187-a52d-1f6fd50adbd7)

![image](https://github.com/trezor/trezor-suite/assets/216917/e88bce3f-442e-4ca7-9fb5-07fc983ab5a5)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33
