### ISSUE TITLE
Staking set dressing: Dashboard CTA

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9285]
### User Story
As an Ethereum user
I want to know about Ethereum Staking
So that I can earn rewards on my assets

### Acceptance Criteria

Background: Minimum stake 0.1 ETH, fee/gas reserve 0.03 ETH

Given as an Ethereum user
When I have at least 0.103 ETH
Then I should see 'Stake Ethereum'

Given I see 'Stake Ethereum'
When I click 'Start staking'
Then I should land on the staking tab

### [Screens](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6218-18354&mode=design&t=biDstCGFMVCBHo23-4)

![image](https://github.com/trezor/trezor-suite/assets/216917/e987ff84-c543-497e-89b6-9bbfc9bb7996)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.6.5 regular (revision a784c4046e79ae138f9a7a9c5e97d2f6771140eb)
 - Transport: BridgeTransport 2.0.33
