### ISSUE TITLE
Staking set dressing: Staking banner in ETH account

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#9287]
### User Story
As an Ethereum user
I want to know about Ethereum Staking
So that I can earn rewards on my assets

### Acceptance Criteria

Given I am on my Ethereum account
When I have 1.03 ETH
Then I should see 'Stake. Earn rewards. Repeat'

Given I see 'Stake. Earn rewards. Repeat'
When I click 'Learn More'
Then I should see 'Stake Ethereum'

### [Screens](https://www.figma.com/file/hZ22ckyTRlCYRLTNUbTdWO/Exploring-Accounts?type=design&node-id=6218-18475&mode=design&t=biDstCGFMVCBHo23-4)

![image](https://github.com/trezor/trezor-suite/assets/216917/4b0fa3ac-f80b-480c-a7d0-54b8fbfa3646)

**Comment by bosomt** [comment]
**QA OK**

<img width="1075" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/28432d28-4c0d-4a07-861b-e8a58130b5f7">

**Info:**
 - Suite version: desktop 24.3.0 (9f8c6dbe0ca13bc1c91c52e33fc30384cf09550e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.3.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
