### ISSUE TITLE
Investigate Source maps for Sentry

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#9334]
In Sentry we often miss source maps so stack traces are cryptic. Let's investigate possible improvements.

**Comment by AdamSchinzel** [comment]
Here are possible options for uploading source maps, I think the best one is Webpack - https://docs.sentry.io/platforms/node/sourcemaps/uploading/?original_referrer=https%3A%2F%2Fwww.google.com%2F

**Comment by davidmurdoch** [comment]
In https://www.npmjs.com/package/@trezor/protobuf, at least, you ship JavaScript that _references_ source maps (via `//# sourceMappingURL=<some-file.js.map>` comments), but don't actually ship any sourcemaps. I think this is actually breaking some tooling, like SWC: https://github.com/swc-project/swc/issues/8789

p.s., this is for MetaMask

**Comment by marekrjpolak** [comment]
Hopefully resolved, at least for now.
