### ISSUE TITLE
Biometrics overlay won't work on Android

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#9338]
Biometrics overlay is not shown on Android.

### Steps to reproduce
1. use Android phone
2. turn on biometrics
3. leave the app
4. when you scroll between opened apps, the Trezor Suite Lite app doesn't hide the screen content with an overlay as it should.

**Comment by bosomt** [comment]
**QA OK**

tested on Nothing phone 1 
23.10.1 (554) version
a20ef43 - [develop] - chore: update eslint
