### ISSUE TITLE
Replace themed .webm device animations with transparent

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#9339]
In `DeviceAnimation/index.tsx` file, we have this condition for now 
```
    // T2B1 animations are transparent
    const theme = device?.features?.internal_model === DeviceModelInternal.T2B1 ? '' : `_${THEME}`;
```

If we generate new animations for T2T1 and T1B1 with transparent background, we can reduce size of the app and maybe make it nicer.

![Screenshot 2023-09-04 at 12 56 44](https://github.com/trezor/trezor-suite/assets/33235762/8f654efc-5a7c-4ed8-948e-f182cd1e7089)

## What we need:
@Hermez-cz 
### Trezor Model One: 
- bootloader 1 button
- bootloader 2 buttons
- reconnect
- onboarding success

(Right now we use WHITE Trezor Model One)

### Trezor Model T:
- bootloader swipe
- onboarding success

**Comment by MiroslavProchazka** [comment]
We are working on this together with a new design for the upcoming device. All images/animations in Suite will be reworked, so they will have transparent backgrounds and a unified look (camera angle, lighting settings etc.)

I'm closing this for now as a fix is in progress.
