### ISSUE TITLE
trezor connect web no longer fires device event

### ISSUE THREAD

**Issue by yushih** [trezor/trezor-suite#9344]
**Describe the bug**
Trezor connect no longer fires device events (https://docs.trezor.io/trezor-suite/packages/connect/events.html). A few months ago it did. I didn't bump `@trezor/connect-web` version during the time. Could something in https://connect.trezor.io/9/popup.html have changed?

I used to get the "acquired" device event and got vendor, model and device ID from the event data. Now there is no more API for doing this.

**Info:**

-   Remembered Wallet: no sure what this is
-   Suite Version: "@trezor/connect-web": "^9.0.7"
-   Browser: newest chrome
-   OS: ubuntu & mac os
-   Bridge: 2.0.27
-   Firmware Version: Trezor model t 2.6.0 

**How to reproduce**
index.html
```
<!doctype html>
<html>
  <head>
    <script src="https://connect.trezor.io/9/trezor-connect.js"></script>
    <script src="index.js"></script>
  </head>
  <body>
    <button id="start">start</button>
  </body>
</html>
```
index.js
```
var TrezorConnect = window.TrezorConnect;

function onClick () {
  console.log('click');
  TrezorConnect.init({
    lazyLoad: true,  
    manifest: {
      email:  
      appUrl: 
    },
  });

  TrezorConnect.on('DEVICE_EVENT', event => {
    console.log('device event:', event);
  });

  TrezorConnect.on('UI_EVENT', event => {
    console.log('ui event:', event);
  });

  TrezorConnect.cardanoGetPublicKey({
    path: "m/44'/1815'/0'",
  }).then(resp => {
    console.log('response:', resp);
  });
}

window.onload = function () {
  console.log('onload');
  document.getElementById('start').addEventListener('click', onClick);
}

```

**Expected behavior**
The call to `cardanoGetPublicKey` returns successfully.
The ui events fire as expected.
Expect the device event callback to be invoked. But it is not.

**Screenshots**
na

**Additional context**
na

**Comment by mroz22** [comment]
did you allow permanent permissions to read from device on permission screen in connect popup?

**Comment by yushih** [comment]
@mroz22 yes I did. But it made no difference.

**Comment by yushih** [comment]
@mroz22 thanks!

**Comment by bosomt** [comment]
**QA OK**

fixed on dev version that will be soon released

<img width="495" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/cdcb4a63-93e3-420a-971c-a2188d50a647">

<img width="832" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/18e48c9c-4106-43ce-9826-c393376282a1">
