### ISSUE TITLE
Error message not properly translated when adding same custom backend

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9358]
**Describe the bug**
Ugly error when adding custom backend with same address.
TR_CUSTOM_BACKEND_BACKEND_ALREADY_ADDED

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: web 23.8.1 (c6b91601f5c333a1de056fbf0b712995a96b5d90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: Trezor T2T1 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32

<img width="523" alt="Screenshot 2023-09-05 at 16 32 31" src="https://github.com/trezor/trezor-suite/assets/31506317/23bbefbf-9b21-47f4-a51f-29e7379b5fb1">

**Comment by komret** [comment]
Fixed by #9192

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 23.12.0 (7d86196d2c570fbcdee4c1164507800cc1566b3e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: 
 - Transport: N/A
