### ISSUE TITLE
Trade box in account

### ISSUE THREAD

**Issue by marek-andrsk** [trezor/trezor-suite#9359]
### Design
Design WIP - TBA

### Spec 

**Issue**
Users are unsure of the meaning of the Trade button and unaware of the Trading options in Suite.

**Solution**
![image](https://github.com/trezor/trezor-suite/assets/12121074/efc1be40-ffdf-41c6-bb25-691355147e2d)
![image](https://github.com/trezor/trezor-suite/assets/12121074/a57ab3b1-e4bd-489f-9e64-e6cf49f0d2d5)

In addition to the Trade button in header we will show a Trade box in each account with relevant coin, showing 7d change in value.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.11.0 (9745dbb7a78674007258f39cfa144dfdcd8aeb59)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0
 - OS: MacIntel
 - Screen: 3200x1800
 - Device: Trezor T2T1 2.6.3 regular (revision 104124eb1346c9c2cb3d5e58bf9e1cf26f12b10d)
 - Transport: BridgeTransport 2.0.32
