### ISSUE TITLE
Trezor Connect forever "loading" when Trezor is not backed up

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-suite#9363]
**Describe the bug**
When the Trezor is not backed up, the Connect pop-up launched from Metamask extension will throw an error in console and spin "loading..." forever.

Error:
```
Uncaught TypeError: Cannot set properties of undefined (setting 'onclick')
    at popup.f8da22c4687e87bca375.js:1:922849
    at BroadcastChannel.pw (popup.f8da22c4687e87bca375.js:1:923013)
```

The problem goes away once the seed backup is complete. (my guess is something to do with the orange "make a backup in 3 minutes" dialog in top left?)

**Info:**

-   Remembered Wallet: no
-   Connect version: today
-   Browser: Google Chrome / Chromium 116.0.5845.140
-   OS: Linux
-   Bridge: 2.0.30something
-   Firmware Version: Trezor One 1.12.1

**How to reproduce**

1. Set up a Trezor, **do not back up seed**. 
2. open Metamask
3. navigate to Add hardware wallet, choose Trezor
4. Connect pop-up will appear
5. Allow this extension to export public keys -> yes
6. "Loading" spinner now loads forever

**Expected behavior**
Pop-up should ask to export public key 1, then close and return to Metamask

**Screenshots**
![Screenshot from 2023-09-06 09-46-57](https://github.com/trezor/trezor-suite/assets/596073/f6f9c4e1-ce42-4efa-bb7d-cb79962c5774)

**Comment by mroz22** [comment]
thanks for report. this is already fixed in develop and I think we can do hotfix release for this today as well 0357ab8819f4133b557df6b8d36a4e9373d7c295

**Comment by STew790** [comment]
**QA OK**
In latest develop this is already fixed. Popup warns the user about the device not being backed up.
![image](https://github.com/trezor/trezor-suite/assets/48477147/c1549419-bb73-4b0f-bfb9-1a3703d94c99)
Even after proceeding, there's still warning throughout the whole process:
![image](https://github.com/trezor/trezor-suite/assets/48477147/6bc199f7-5c95-4018-9f55-64bd3a513a4a)
