### ISSUE TITLE
Add support ZIP-317 for ZCash

### ISSUE THREAD

**Issue by gades** [trezor/trezor-suite#9375]
After activation ZIP-317 (April 28, 2023) in zcash network  is require different way for fees - pay 5000 zat per logical actions instead of fee per byte https://github.com/zcash/zips/blob/main/zip-0317.rst#fee-calculation

Could you please implement ZIP-317 for zcash ?

**Comment by mroz22** [comment]
could you please clarify what happens / is happening unless this is implemented? txs being rejected by network?

also cc @trezor/qa

**Comment by gades** [comment]
>could you please clarify what happens / is happening unless this is implemented? txs being rejected by network?

Right now mempool in zcash is overloaded and many txs have unpaid actions due new rules in ZIP-317 because each logical action is require 5000 zat per action and minimum actions is two. ZIP 317 cares about fee per logical action.

Here is reply from zcash devs: "ZIP 317 requires that a transaction's fee be proportional to the number of "actions" (spends or outputs, whichever is larger). If a transaction has more actions than its fee would be proportional to, it means that some of those actions are "unpaid". If a transaction doesn't pay the ZIP 317 fee, then we generally don't want it to get mined, because doing so has negative effects on the entire network. 
What is currently happening on the network is that the mempool is full of transactions that pay no fee, and have just under the default unpaid action limit of 50. This means only a single one of those transactions can get into each block, so if the mempool has e.g. 5000 such transactions, it takes 5000 blocks to mine them all (because all 5000 are vastly underpaying fee). It also means that if one of those transactions happens to be selected for a block, then other smaller transactions that are underpaying can't be selected for that same block. We do weight the selection process towards smaller transactions, but if there are thousands of the large ones, it's still quite likely they get selected."  https://github.com/zcash/zcash/issues/6748#issuecomment-1674156994

@trezor/qa

**Comment by bosomt** [comment]
- @mroz22 no idea how to get ZIP-317 to our testing account
- i see that ZEC is mining almost empty blocks even when there are thousands of unconfirmed transactions ;)
- of course i will love to test it, @gades is there something like Zcash electrum that i can use to generate this transaction and send it to our t1Tr193SjNzhwV6fzmaHWU5DYXmyevWy5Ay address ?

**Comment by mroz22** [comment]
@gades  so do I get it right that now in zcash I don't calculate fee based on tx size in bytes. From now on, this is to be completely ignored. Instead I simply do something like

```
 Math.max(inputs.length, outputs.length) * 5000 
```
and this is the fee? 


EDIT: oh,  I read this zip 317 talks about default fee. so final fee is basic fee set by tx size plus this default fee right?

**Comment by Hannsek** [comment]
@bosomt So transactions go to the mempool and stays there and are not getting mined?

**Comment by gades** [comment]
@mroz22 I think the better ask @str4d about correct implementation ZIP-317, he’s developer of zcash core 

> i see that ZEC is mining almost empty blocks even when there are thousands of unconfirmed transactions ;)

it’s related to that rules in ZIP and only couple transaction can join to the block by using unpaid actions and it’s strange policy

**Comment by mroz22** [comment]
I am already reading this here https://github.com/zcash/zips/blob/main/zip-0317.rst#specification
Are you guys maybe willing to contribute or at least review? 

ok, and here we have some inspiration:
- https://github.dev/BitGo/BitGoJS/blob/c6ac3efd478be313ecfc73d74dc59f6b6ced1005/modules/unspents/src/zcash.ts

**Comment by Hannsek** [comment]
So, @STew790 sent [this tx](https://zec4.trezor.io/tx/b27f876c4de6abba9419ef4822c00ca5d78f4a9b8c122668719e887e8d9553e8) with really small fee (226 zats) and it gets confirmed in a reasonable time.

**Comment by bosomt** [comment]
**QA OK**

tx sent and confirmed
used fee  `0.00015 ZEC (30.00 sat/Byte)`
it was auto changed even i tried to use custom 1 sat/B fee


https://zec3.trezor.io/tx/59b0f270dedb79cddfaef0572a83b03a775f398b0d799bbd17a91f72adb69e23 **QA OK**

**Info:**
 - Suite version: web 23.10.0 (3d3a82ae53a4d40fc4301b05ec8257e65f1fbc73)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0
 - OS: MacIntel
 - Screen: 2160x1350
 - Device: Trezor T2T1 2.6.1 regular (revision a8a97276a8d57c75f97a904bfec0119be6452cf9)
 - Transport: BridgeTransport 2.0.33

**Comment by gades** [comment]
I'm using https://github.com/trezor/trezor-suite/releases/tag/v23.10.1 and this feature steel isn't available

**Comment by Hannsek** [comment]
The zcash fee policy should be changed in the new release. Is it missing?

**Comment by gades** [comment]
> The zcash fee policy should be changed in the new release. Is it missing?

yes, I don't see this changes in latest release

**Comment by bosomt** [comment]
I tried to send tx with current production version that was released yesterday.
Fee rate was (9.32 sat/Byte) and it got immediately confirmed.

https://zec1.trezor.io/tx/114aa9463f98bb2d965c979ea9b58c265d22423f8f4f852eea2b7b86ed04ea29


**Info:**
 - Suite version: desktop 23.10.1 (6c8d061f7305947b0270a2560e4cc65d1f7ded27)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.10.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Comment by gades** [comment]
> I tried to send tx with current production version that was released yesterday. Fee rate was (9.32 sat/Byte) and it got immediately confirmed.

your fee is 0.0000192 ZEC (9.32 sat/Byte) and it's wrong 

Some time it's require to wait more 1 hour because I forget to set the correct fees manually, but the patch still doesn’t work

**Comment by Hannsek** [comment]
cc @marekrjpolak

**Comment by gades** [comment]
@Hannsek I can confirm that this feature was appear in [23.11.5](https://github.com/trezor/trezor-suite/releases/tag/v23.11.5) but I notice one small issue when set specific fee peer byte 

1 - 29 sat/b  I see 0.0001 
<img width="804" alt="Screenshot 2023-11-25 at 12 59 42" src="https://github.com/trezor/trezor-suite/assets/4200730/0e64e2bf-ed23-4502-8741-b7bc4928ef48">

but in case increase it 

31 sat/b  0.0001054 ZEC

<img width="800" alt="Screenshot 2023-11-25 at 13 01 12" src="https://github.com/trezor/trezor-suite/assets/4200730/9f1c6df0-c515-4c50-bd74-d326f7929e25">

Is this intended or does it make sense for each range of 30 to be a multiplier?
example:
1 - 29 sat/b  - 0.0001 
30 - 59 sat/b  - 0.0002 
60 - 89 sat/b  - 0.0003 


@str4d Could you please provide more details about fees after implementation ZIP-317? Is reason to increase fees for force mining tx?

**Comment by Hannsek** [comment]
I don't follow. What is the issue here?

**Comment by gades** [comment]
> I don't follow. What is the issue here?

Please create new transaction and set custom fess above 31 sat/b and you will see  0.0001054 ZEC instead of 0.0001. I don't know if there is any point in a custom fee at all. Unless make a multiplier that will increase the cost for a logical action.

I don't know why zcash developers aren't actively involved. 

p.s. the solution works and I'm happy, but maybe some cosmetic changes need to be made. 

Thanks for ZIP 317 implementation in the Trezor wallet

**Comment by Hannsek** [comment]
But if I set the fee ti 31 sat/b the amoun, 0.0001054, is the correct one. 0.0001 is not.

**Comment by gades** [comment]
only in the document ZIP-317 requires payment for a logical action and there is no such thing as a cost per kilobyte, so it is not clear how it turned out another 0.0000054 if in fact the number of logical actions has not changed. 

if I specify values 1 - 29 sat/b then it calculate as expected
