### ISSUE TITLE
Update on quit button quits and updates app unexpectedly 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9376]
**Describe the bug**
Replicated on Windows 10 and macARM OS.
`Update on quit` button actually quits and updated app and does not wait for correct quit on user side.

**Steps to reproduce:**
1. Install latest RC
2. Update to codesign version
3. Observe `Update on quit` button behavior

**Info:**
 - Suite version: desktop 23.9.1 (41a9c13bf28edf71fe629379288a5ad685f259d1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.9.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: 
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/714f7232-0a1d-419c-9cc0-482592d77f1d

**Comment by AdamSchinzel** [comment]
Caused by 8d92fa8d3a0be619c80d4182eacc825764997e45 (we lost a prop there to install it based on how user wants it)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.10.1 (0b3ccfe0b8e9bc2af00609d640bc1be31ab8edaa)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.10.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33
