### ISSUE TITLE
sha512sum of linux app images

### ISSUE THREAD

**Issue by algorithmical** [trezor/trezor-suite#9390]
Hi, the sha512sum of the linux app image doesn't match what's in the release pages.
I tested by running `sha512sum Trezor-Suite-23.8.1-linux-x86_64.AppImage` and `sha512sum Trezor-Suite-23.8.1-linux-arm64.AppImage`
I am probably using the sha512 verification wrong, please advise how I am supposed to check thank you.

**Comment by algorithmical** [comment]
```
openssl dgst -binary -sha512 ~/Desktop/Trezor-Suite-23.8.1-linux-x86_64.AppImage | openssl base64
```

is the answer. Having this in your readme would be nice.

**Comment by bosomt** [comment]
@algorithmical sorry for late reply, we were kinda busy last few weeks.
ALready checked it and asked colleagues to add it to our knowledge base at https://trezor.io/learn


```
tbosansk@tbosansk-Latitude-3410:~/Downloads$ cat latest-linux.yml
version: 23.10.1
files:
  - url: Trezor-Suite-23.10.1-linux-x86_64.AppImage
    sha512: BqdfhYLG4z+9B7KbJGWGPml7U2fl/RQ1nZK0vdeA/cKhG0SjH0K8er9bemg60RPBXj0AeuK80v/6vMbDtyEnRQ==
    size: 148940363
    blockMapSize: 157279
path: Trezor-Suite-23.10.1-linux-x86_64.AppImage
sha512: BqdfhYLG4z+9B7KbJGWGPml7U2fl/RQ1nZK0vdeA/cKhG0SjH0K8er9bemg60RPBXj0AeuK80v/6vMbDtyEnRQ==
releaseDate: '2023-10-09T13:03:07.384Z'


tbosansk@tbosansk-Latitude-3410:~/Downloads$ openssl dgst -binary -sha512 Trezor-Suite-23.10.1-linux-x86_64.AppImage | openssl base64
BqdfhYLG4z+9B7KbJGWGPml7U2fl/RQ1nZK0vdeA/cKhG0SjH0K8er9bemg60RPB
Xj0AeuK80v/6vMbDtyEnRQ==
```
