### ISSUE TITLE
T2B1 unable to set homescreen

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#9404]
**Describe the bug**
- it is not possible to set T2B1 homescreen
- getting Invalid homescreen error

**How to reproduce**

1. Choose homescreen from settings

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.10.0 (7e7e183598efd9ee3413d74f0689322811bbc1e9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.10.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2B1 2.6.1 regular (revision 364c1ce123ead6e4dffab8cd3abb208e19158bce)
 - Transport: BridgeTransport 2.0.33
