### ISSUE TITLE
Importing bitcoin XPUB fails

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#9413]
Importing Bitcoin XPUB fails. 

QA: Import bitcoin account works as expected.

**Comment by PeKne** [comment]
Fixed by https://github.com/trezor/trezor-suite/pull/9414 ?

**Comment by bosomt** [comment]
**QA OK**

33c6ca5 - [develop] - Chore\/connect t1 with pin (#9576)

* fix(connect): fix error condition on invalid pin

* feat(suite-native): allow T1 with pin connection
