### ISSUE TITLE
Custom fee field autoclosing when bumping transaction fee

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9416]
**Describe the bug**

Custom fee field isautoclosing when bumping transaction fee.
See video, you dont even need to click on custom fee field and TS auto switch to normal fee .

**Steps to reproduce:**
1. Send tx
2. Try to bump tx with custom fee
3. Observe behavior of modal

**Info:**
 - Suite version: desktop 23.9.1 (4310819f047d4341d2a86c422d65de447e99dd17)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.9.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/285ffc03-7618-47b1-a3d1-a62fd1f836e8

**Comment by matejkriz** [comment]
@bosomt is it reproducible on other networks like testnet or BTC?

**Comment by bosomt** [comment]
i was only able to replicate when **bumping** ETH, Bitcon and GOERLI transaction /so i expect it happening on all coins.
Im not able to reproduce it when sending transaction.

And i replicated it on dev master

**Info:**
 - Suite version: web 23.10.0 (a866d2c1b2ed97763f96e3e639e4b591385fcbef)

**Comment by komret** [comment]
It closes because the whole form resets every time `formValues` change. `formValues` are an object so the reference changes on every render. A render is periodically caused by - I suppose - update of `feeInfo`. I think the solution is to remove[ this `useEffect`](https://github.com/trezor/trezor-suite/blob/a3b21ed8584285bd85eb6f721639f5d069567509/packages/suite/src/hooks/wallet/useRbfForm.ts#L204), but I don't understand why it was added in the first place 😕 It was also probably broken for some time.

**Comment by matejkriz** [comment]
@bosomt could you please try to reproduce it on 23.8.1? 🙏

**Comment by matejkriz** [comment]
> @bosomt could you please try to reproduce it on 23.8.1? 🙏

nevermind, I see the answer in the original slack thread - works as expected on 23.8.1

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.9.2 (7a6edf6d2508907cdb95a915864eb7ad77d9684c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.9.2 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
