### ISSUE TITLE
error with Bump fee - the suite works with a different value than what I enter

### ISSUE THREAD

**Issue by kulisekf** [trezor/trezor-suite#9424]
**Describe the bug**
I have submitted the transaction. Subsequently, I wanted to perform a replacement by fee, as I did not set the fee quite ideally, but when the fee is increased after the first step, the Trezor Suite works with a different value than what I enter

**Info:**

-   Suite Version: app
-   OS: Win 10
-   Trezor Suite Version: 23.8.1

**How to reproduce**
First I sent the transaction with 12 sat/B
![image](https://github.com/trezor/trezor-suite/assets/120821113/15b791af-98d8-461c-a1b2-c84c1ee58de2)

Next click on Bump fee and set the fee to 14 sat/B - then click on replace transaction
![image](https://github.com/trezor/trezor-suite/assets/120821113/d091078c-34fa-4fd8-bb24-1840339209c0)

Subsequently, a window with information about the new transaction will appear - note that the wrong Fee rate value is displayed in the left part - I set 14 sat/B, here it shows 8.62 sat/B. Image already shows the status after signing a new transaction on the wallet - it is possible to replace the transaction
![image](https://github.com/trezor/trezor-suite/assets/120821113/301ec8d1-82a7-4846-a517-785185499f62)

After confirming the replacement of the transaction, I get the following warning in the suite and the transaction does not submit. The value displayed for Fee rate in the previous image seems to correspond to the value Trezor Suite was working with, which is not the value I entered in the first step
![image](https://github.com/trezor/trezor-suite/assets/120821113/e24e1b4d-3aef-47e9-b138-13a1b90cbb27)

I repeated the procedure with other replacement fee values. When I set the fee to 15 sat/B, the information window (picture number 3) showed me Fee rate 9.62 sat/B, 17 sat/B shows me 11.62 sat/B.

It helped me to enter a value of 19 sat/B, where the suite continued to work with a value of 13.62 sat/B. The transaction was successfully signed and sent. If I look at mempool.space now, the fee shown here is 13.62 sat/B

**Comment by kulisekf** [comment]
Today i realized why i might have this error. The original transaction I made spent one whole UTXO (using coin control I chose UTXO and set the transaction volume with Send Max). Thanks to this, this transaction had only 1 output - there was no change output in it. When I tried to replace by fee to keep the amount of funds sent to the destination address the same, additional UTXO had to be added to cover the new fees. There was one more UTXO at the address I was sending from, which was automatically added to the transaction. Adding another UTXO increased the transaction size from 203B to ‎384B (I have this data from mempool.space). However, I think that the total fee volume was calculated before adding the new UTXO and finding the new total transaction size, due to which, after adding another UTXO, the fee was recalculated to sat/B format and was therefore lower than what I entered.

**Comment by bosomt** [comment]
I noticed this happening. Even i selected 2 sats fee Suite uses 1,55.
But i think its related to multiple incoming and outgoing UNCONFIRMED transactions.
But fee is same in both screenshots only fee rate is different

<img width="517" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/045bbfa3-ffc8-4394-9f0e-9ae0b67fa3d3">

<img width="589" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/372a1e8f-5d6e-45be-b9fc-ea513c8a8f8a">

**Comment by szymonlesisz** [comment]
@bosomt i'm wondering if this issue is still present in suite version >= 23.9?

there were some changes and fixes in 23.9 regarding rbf, fee calculation and dust limit

**Comment by bosomt** [comment]
Tried to bump multiple txs on dev master.
Only one of attempts fee rate does not match in modals /fee is same but different rate is rendered/

It was this tx and it contains unconfirmed input 
https://btc2.trezor.io/tx/29fdddcd2c2d27e53d7b3c04aecb4d7e3528980144e753b912996026ffc85c2a

<img width="584" alt="Screenshot 2023-10-16 at 16 26 00" src="https://github.com/trezor/trezor-suite/assets/31506317/f00f3013-fa97-4d7c-9a8a-a3246344821d">
<img width="634" alt="Screenshot 2023-10-16 at 16 25 51" src="https://github.com/trezor/trezor-suite/assets/31506317/f37bfc01-a9f4-4d99-b801-3f32f4355cd9">


**Info:**
 - Suite version: desktop 23.11.0 (40b035b2be45a4792adc9fb8373fdacff7b89bb3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.11.0 Chrome/116.0.5845.188 Electron/26.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Comment by kulisekf** [comment]
I tried again today with Suite 23.10.1, the problem reappeared. Procedure for replication:
1. when creating a transaction, select the Coin control option, then select only one UTXO, and then select the Send max option in the Amount field - all funds from exactly one UTXO will be sent
2. perform a bump fee - if I try to bump the fee, another UTXO will need to be added, which will increase the total transaction size and the error will show
I assume that the original size of the transaction (one input and one output) is used when calculating the fee, instead of the new size (two inputs and two outputs), due to which there are discrepancies between the entered Fee and Fee rate. Looking at the attached utransaction from @bosomt , it also has one input and one output. If you try to bump fee for this transaction, I assume that there will also be an increase in the number of inputs and outputs

**Comment by bosomt** [comment]
**QA OK**

tested in @szymonlesisz branch, i was not able to reproduce 
- multiple bumps of BTC transactions
- multiple finalize BTC transactions 
- multiple REGTEST transactions

i will retest during release cycle testing one more time

**Info:**
 - Suite version: web 23.12.0 (694dfebd22f0574d0660c96f04557893005a75b7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0
 - OS: MacIntel
 - Screen: 3200x1800
 - Device: 
 - Transport: BridgeTransport 2.0.33
