### ISSUE TITLE
Remove unused messages

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9440]
Please remove these unused messages for translation.

unused messages: 
there are unused messages!
[
  'TR_CONNECT_YOUR_TREZOR_TO_CHECK',
  'TR_SHOW_ON_TREZOR',
  'TR_UNVERIFIED_ADDRESS_COMMA_CONNECT',
  'TR_UNVERIFIED_ADDRESS_COMMA_SHOW'
]

**Comment by bosomt** [comment]
+1 more message 


  'TR_CONNECT_YOUR_TREZOR_TO_CHECK',
  'TR_SHOW_ON_TREZOR',
  'TR_UNVERIFIED_ADDRESS_COMMA_CONNECT',
  'TR_UNVERIFIED_ADDRESS_COMMA_SHOW',
  **'TR_SENT_SUCCESSFULLY'**

**Comment by AdamSchinzel** [comment]
> +1 more message
> 
> 'TR_CONNECT_YOUR_TREZOR_TO_CHECK', 'TR_SHOW_ON_TREZOR', 'TR_UNVERIFIED_ADDRESS_COMMA_CONNECT', 'TR_UNVERIFIED_ADDRESS_COMMA_SHOW', **'TR_SENT_SUCCESSFULLY'**

The last one is actually used in `@trezor/suite` in review transaction.
