### ISSUE TITLE
Upload custom homescreen image

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#945]
Native system dialog (as is).

**Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f801b73d7a6f1b08335)

**Comment by glacierbits** [comment]
Duplicate

**Comment by jimbojw** [comment]
Duplicate of what? Where's the open bug for this feature? The old browser-based wallet used to support custom home screens, but I don't see this option in the trezor-suite app.

**Comment by mroz22** [comment]
The feature is indeed not implemented yet. But there may be already an open issue for that.

**Comment by jimbojw** [comment]
> But there may be already an open issue for that.

Can you provide a link? I want to see that there is indeed an open issue.

**Comment by prusnak** [comment]
> Can you provide a link? I want to see that there is indeed an open issue.

Duplicate of https://github.com/trezor/trezor-suite/issues/1157
