### ISSUE TITLE
Discovery 4. - pause & resume

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#9466]
While the discovery is running, the `connect` module blocks access to the device. That might be a problem because in such a case user can not interact with the device in any way (verifying the receive address, sending, changing the device label, etc.). For this reason, we need to implement a feature that pauses the discovery process to allow the user to perform the desired action (e.g. verifying the receive address) and automatically resume the discovery when the action is done.

**Comment by Nodonisko** [comment]
Will this be necessary if you implement n.5 #9467 ? I think that basically solves the issue right?

**Comment by PeKne** [comment]
Yes, you are right. This issue describes the approach implemented in suite-desktop . If we decide to optimize discovery as proposed in issue #9467, this issue does not need to be implemented at all.

**Comment by bosomt** [comment]
**QA OK**

started recovery, 
displayed receive address
came back to my assets
discovery resumed

24.01.1 (673)
96d12a4 - [develop] - fix(suite): fix label drop for RBG transactions
Android 13 - Nothing phone 1
