### ISSUE TITLE
Discovery 5. - fetch the xpubs/addresses first

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#9467]
The current process of discovery involves continuously alternating between reading an xpub from the device and running a discovery above the derivation path. However, this is not ideal for the mobile app use case because it requires the device to be connected for a long period of time (while many things could go wrong in the meantime: lost connectivity, device disconnected, etc.).

A better approach would be to initially fetch all the xpubs, which can be done within seconds, and then complete the discovery process without the need for the connected device.

### Implementation proposal: 

- Create a new discovery thunk that first download the xpub keys. When the xpubs are downloaded, the device is no longer needed and the discovery can be completed independently.
  -  Use the [TrezorConnect.getPublicKey](https://connect.trezor.io/9/#/method/getPublicKey-multiple) method to retrieve the xpubs. 
  - After that the thunk should iteratively call [TrezorConnect.getAccountInfo](https://connect.trezor.io/9/#/method/getAccountInfo-xpub), which retrieves xpub accounts and their balances without requiring a device connection.

**Comment by Nodonisko** [comment]
Good idea, but we need to take in account user might not want to remember device.
