### ISSUE TITLE
Overlap of text in enter xpub via text field

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9472]
**Describe the bug**
See screenshot.
When you enter xpub manually placeholder text is not deleted and both text overlaps.

**Info:**

-   Mobile Suite Version: ccabcec - [develop] - chore(suite-common): device middleware (#9445)
-   OS: iOS + Android

**How to reproduce**

**Screenshots**
<img width="643" alt="Screenshot 2023-09-18 at 15 55 50" src="https://github.com/trezor/trezor-suite/assets/31506317/52b1cfd6-e2e5-4464-b8c0-867e259fc4e0">

**Comment by bosomt** [comment]
**QA NOK**

when you enter xpub manually it does not overlap anymore
but when you scan it and you go back due to already imported it overlaps

how to replicate:
- import asset
- import again
- navigate back
- observe overlap

24.2.0 (709) c12a2a8 - [develop] - wip commit to get the develop build

![telegram-cloud-photo-size-4-5879572193002767052-y](https://github.com/trezor/trezor-suite/assets/31506317/e525c04f-9b67-403e-a000-fa2294ca451e)


https://github.com/trezor/trezor-suite/assets/31506317/bd4719b2-e45c-4e8a-a052-d331eeb83464

**Comment by PeKne** [comment]
Good catch 😎

**Comment by bosomt** [comment]
**QA OK**

Android 14 - Nothing Phone 1
24.3.1 (24) dev version 6e9d8d6
