### ISSUE TITLE
Provide Android APK via GitHub releases

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#9475]
It would be great if users were able to download Suite Mobile APKs via GitHub Releases. 

That would enable installation using e.g [Obtanium](https://github.com/ImranR98/Obtainium) but of course direct install as well.

**Comment by mnuky** [comment]
Hi @prusnak - we already have an issue with some exploration / proposed solutions here: https://github.com/trezor/trezor-suite/issues/5728. I will archive this issue, ok?

**Comment by prusnak** [comment]
Closing as duplicate of https://github.com/trezor/trezor-suite/issues/5728
