### ISSUE TITLE
Hide portfolio total fiat value when discovery fails

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#9483]
**Describe the bug**
I think that we should hide portfolio total fiat value when discovery process fails. We don't show even balances of individual active coins and users can get confused maybe a bit...

**How to reproduce**

1. Simulate discovery error (e. g. open app offline)

**Expected behavior**
Portfolio total fiat value is hidden or in loading state.

**Screenshots**
![4BABF731-538B-41D4-8755-FBD218CD13F0](https://github.com/trezor/trezor-suite/assets/66002635/81b516a1-04f7-46d8-ab29-75310f38a001)

**Comment by Hermez-cz** [comment]
Expected behavior: Loading state.

**Comment by bosomt** [comment]
**QA OK**

<img width="1146" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/8cd60e9e-403b-48da-a5aa-00496687a84c">

**Info:**
 - Suite version: web 24.1.0 (e24c80afa0c49184f185c16112b545aab9bf0271)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
