### ISSUE TITLE
Different homescreen images for T2B1

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#9494]
Prepare logic so that we can create special homescreen images for T2B1

**Comment by STew790** [comment]
**QA OK**
Pre-selected few homescreens works and custom homescreen works as well.

**Info:**
 - Suite version: desktop 23.10.0 (e6d29e01e6fc70862133fcb1ebf968132afa7379)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.10.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.6.2 regular (revision fbd5c466f0f8b062be517b2afbe5979542f19484)
 - Transport: BridgeTransport 2.0.33
