### ISSUE TITLE
Standard wallet identified as hidden

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9502]
**Describe the bug**
Standard wallet identified as hidden when PIN protection enabled.
After i reload TS and device is already unlocked it wont happen again till i reconnect device.

**Steps to reproduce:**
1. Connect device with passphrase and PIN enabled
2. Add standard wallet
3. Observe behavior 

**Info:**
 - Suite version: desktop 23.9.2 (7a6edf6d2508907cdb95a915864eb7ad77d9684c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.9.2 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T1B1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="185" alt="Screenshot 2023-09-20 at 9 29 42" src="https://github.com/trezor/trezor-suite/assets/31506317/23b77c63-1cb7-4e57-bc3c-f78561de5986">

https://github.com/trezor/trezor-suite/assets/31506317/a8accd7b-803e-4eeb-9526-813a4ce42f2a

**Comment by matejkriz** [comment]
I can reproduce it on allall, no need for empty wallet.

Can't reproduce it on 23.8.1

**Comment by bosomt** [comment]
I can confirm that its happening with all seed /not empty standard wallet / too.

https://github.com/trezor/trezor-suite/assets/31506317/f40e509f-6935-4584-8865-56a63aa05fa9

**Comment by matejkriz** [comment]
It was caused by the fix for devices with passhprase protection disabled that was applied for devices with passhprase protection enabled too. So would be nice to retest all possible cases/models again:

- standard/hidden wallets
- remembered/not remembered
- passhprase_protection true/false
- T1B1/T2T1/T2B1
- ?/?
@trezor/qa

**Comment by bosomt** [comment]
**QA OK**


**T2T1**

- passphrase enabled and PIN disabled **OK**
- passphrase enabled and PIN enabled **OK**
- passphrase disabled and PIN enabled **OK**
- passphrase disabled and PIN disabled **OK**


**T1B1**

- passphrase enabled and PIN enabled **OK**
- passphrase disabled and PIN enabled **OK**
- passphrase disabled and PIN disabled **OK**
- passphrase enabled and PIN disabled **OK**

8x loaded Standard wallet

remembered wallet works as expected
hidden wallets loaded as hidden wallet

**Info:**
 - Suite version: desktop 23.9.3 (f903de22010dc963973d99e84514b4b243e92109)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.9.3 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T1B1 1.10.0 regular (revision f4424ece1ccb7fc0d6cad00ff840fac287a34f07)
 - Transport: BridgeTransport 2.0.33

**Comment by STew790** [comment]
**QA OK**

T2B1

- passphrase enabled and PIN disabled OK
- passphrase enabled and PIN enabled OK
- passphrase disabled and PIN enabled OK
- passphrase disabled and PIN disabled OK


hidden wallet loads as hidden

**Info:**
 - Suite version: web 23.9.2 (45c00c9a31eac498a408f7aa5475b4f1e0e7d067)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2B1 2.6.1 regular (revision ee3442506259c8c1e9684d836064e63e3b23cd11)
 - Transport: WebUsbTransport
