### ISSUE TITLE
Aborting backup check not working properly

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#9510]
Aborting the action during the recovery check on TT closes the modal but the device does not react to it. Then, the device can get into incorrect state when interrupting the backup for the second time.

**Expected behavior**
Trezor screen should return to default state after aborting the action.

**Screenshots**

https://github.com/trezor/trezor-suite/assets/42465546/053167b0-5a12-49f0-95cf-1d91e24fbef5

**Comment by mroz22** [comment]
is this still issue?

**Comment by komret** [comment]
> is this still issue?

Yes. Firmware does not react to the cancel request. Closing in favour of https://github.com/trezor/trezor-firmware/issues/3503
