### ISSUE TITLE
Fetch eth tokens rates

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#952]
Currently we are only fetching rates for coins.

**Comment by bosomt** [comment]
looks fine, price is right

**Comment by bosomt** [comment]
but there are no ERC20 prices/funds in dashboard,
is this proper behavior ?
@szymonlesisz @slowbackspace

**Comment by slowbackspace** [comment]
> but there are no ERC20 prices/funds in dashboard,
> is this proper behavior ?
> @szymonlesisz @slowbackspace

yup, the impementation should match the designs. There was an idea to add list of tokens when user clicks on ETH row in the table, but afaik there is no task for this right now. :]

feel free to open another issue if you want to see it implemented before the release (I want it too!) :)

**Comment by bosomt** [comment]
@slowbackspace on it !
