### ISSUE TITLE
No backup banner formatting

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#9520]
**Describe the bug**
Backup banner in suite is broken

**Info:**

-   Remembered Wallet: yes/no
-   Suite Version: 23.9.3 (it is in EAP, not in prod)

**How to reproduce**

1. Have non-backed up device

**Screenshots**

![Screenshot 2023-09-21 at 15 02 56](https://github.com/trezor/trezor-suite/assets/33235762/78f44159-828c-470f-b525-95025603c955)
![Screenshot 2023-09-21 at 15 02 50](https://github.com/trezor/trezor-suite/assets/33235762/11b3a80d-9209-4d1e-9755-4a3d03c2c9d1)

**Comment by bosomt** [comment]
**QA OK**

<img width="497" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/74a19493-bd88-4003-ba22-0080a9eb9970">

**Info:**
 - Suite version: web 23.10.0 (109db0a3f6fc6fc5cdb24098ee50480692c92dbf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
 - OS: MacIntel
 - Screen: 2160x1350
 - Device: Trezor T2B1 2.6.1 regular (revision 364c1ce123ead6e4dffab8cd3abb208e19158bce)
 - Transport: BridgeTransport 2.0.33
