### ISSUE TITLE
Fw installation - Device ready image

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#9523]
**Describe the bug**
- when you want to update fw, there is an image to switch to bootloader
- when you switch to bootloader, device is now ready but the image "switch to bootloader" is still there

**Info:**

-   Suite Version: 23.10.0

**How to reproduce**

1. Update fw

**Expected behavior**
I would expect different image or not image

**Screenshots**

![Screenshot 2023-09-21 at 15 22 28](https://github.com/trezor/trezor-suite/assets/33235762/8c60438b-f0a3-41fe-b763-770db41a5fec)

**Comment by Hermez-cz** [comment]
Solution: Remove image please.

**Comment by bosomt** [comment]
**QA OK**

<img width="490" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/0ec543a0-883e-48f1-bfaa-e560764b0e09">

**Info:**
 - Suite version: desktop 23.12.1 (babafe5fbac98a751c69b696c816e9183a67e180)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.12.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
