### ISSUE TITLE
Send empty protobug message instead of sending picture when setting up default homescreen

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#9528]
When user change the home screen to default on TT in Suite, Suite sends .jpg image which takes space in TT storage (as Trezor see it as a custom homescreen).
This is unnecessary as Trezor has default wallpaper saved internally already.

It is enough to send empty protobuff message to Trezor in order to set homescreen to default.

Please do it for all models.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.11.0 (328ab76b499da4a79633883b721d8ace3556285e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
 - OS: MacIntel
 - Screen: 2160x1350
 - Device: Trezor T2T1 2.6.3 regular (revision f7aec0aeb1654268cddbf9f9c359c4edb0349f9b)
 - Transport: BridgeTransport 2.0.33
