### ISSUE TITLE
Address label not showing in dropdown

### ISSUE THREAD

**Issue by FreeWall** [trezor/trezor-suite#9532]
**Describe the bug**
When user sets a label for any bitcoin or bitcoin-like receiving address, the label is then not showing in the exchange flow.

**How to reproduce**
- Open any BTC account
- Go to Receive
- Set a label for any of the used addresses
- Open Ethereum account
- Select Trade and Exchange, compare offers and choose deal
- Open Receive address dropdown

**Expected behavior**
Instead of the address, user will see their label, in Exchange flow, Buy and DCA.

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/12121074/053324b7-89df-472b-9cd5-7e272ae98f7a)
![image](https://github.com/trezor/trezor-suite/assets/12121074/dd6a50e0-6dd8-4e03-9456-8848b1748b8f)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.10.0 (4115374edf1ed878ba4584ccc08cf45c6b9ff50e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
 - OS: MacIntel
 - Screen: 2160x1350
 - Device: Trezor T2B1 2.6.2 regular (revision 6e5967af25de87bebd331d697e6ef940e64286ef)
 - Transport: BridgeTransport 2.0.33
