### ISSUE TITLE
Disable receive address double click select and copy

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#9536]
**Describe the bug**
User is still able to copy receive address even he doesn't confirmed it on his device yet. It's easy as double click select and copy.

**How to reproduce**

1. Go to Accounts
1. Click on receive

**Expected behavior**
User is really able to copy the address after he confirmed it on his device.

**Screenshots**
![E4C1D5E9-0E40-40C9-8298-7285E5234310](https://github.com/trezor/trezor-suite/assets/66002635/153eb89b-eb8a-4b96-8ce5-abfd683207c8)

**Additional context**
I saw that GitHub did similar thing. When deleting project you are prompted to type the repo name. Before I was able to just copy what GitHub wanted me to type but now I am not able to copy it and I therefore forced to type it myself. I guess it's for the better.

**Comment by Hannsek** [comment]
More like feature now as this allow address copying and checking in some sendform (e.g. imessage).
