### ISSUE TITLE
Uneconomical coinjoin warning you everytime you press start

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9561]
**Describe the bug**
Uneconomical coinjoin warning modal is rendered everytime you press start button.
Maybe we can warn users only once /maybe one warning per app start ? / and not everytime you stop/start coinjoin.

**Info:**
 - Suite version: desktop 23.10.0 (7e7e183598efd9ee3413d74f0689322811bbc1e9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.10.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: 
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

![image](https://github.com/trezor/trezor-suite/assets/31506317/a7a8d9df-560f-47ce-9010-dcfc2594c7e8)

**Comment by hynek-jina** [comment]
This warning make sense for users and should be displayed everytime (just like it is implemented now).
Can we increase testing amount to cover this requirement? We should even test primary scenario - with amounts above 1M sats.
