### ISSUE TITLE
ETH send modal does not correspond with FW

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#9567]
### Problem statement
(look below for solution)

<img width="747" alt="image" src="https://github.com/trezor/trezor-suite/assets/57008159/2dc1c432-dce6-418f-8601-701a3f3c8afd">

In FW (2.6.2) there are currently only 2 screens: 
![image](https://github.com/trezor/trezor-suite/assets/57008159/1f75a539-e660-4394-907c-a6d1e2d3053c)

In Suite, there are 5 points.

I'd expect only 2 bullets:
- Receipient
- Amount | Maximum fee

In tokens there is additional Contract address screen:
![image](https://github.com/trezor/trezor-suite/assets/57008159/c999f2e6-4d6c-4ec2-a32b-59bea8d310e5)

+ when I press the back arrow in fw, bullets keeps checking one by one. I'd expect the bullet to uncheck when I go back in fw. (not sure if this is possible; are we differentiating between "confirm" and "back" message in fw? @mmilata)

### Solution

Please update the Ethereum and Ethereum tokens send flow for T2B1 (all FWs) and T2T1 (only with FW 2.6.3 and later) as follows and align with the FW team to synchronize the FW<->Suite actions.

Reduce the steps in Ethereum send flow modal window from current 5 steps to only 3:

1. Recipient address match? ([Figma design](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=205%3A777&mode=design&t=01EikyoHUBtnEPV9-1))
2. Amount & Maximum fee matching? ([Figma design](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=205%3A1022&mode=design&t=01EikyoHUBtnEPV9-1))
3. All confirmed, send ([Figma design](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=205%3A1145&mode=design&t=01EikyoHUBtnEPV9-1))

Important: The example in the Suite design in Figma above is including the Spaced address checking and in the design corresponding to T2T1. Please make sure to have the black frame contents in the format and design matching the device type, its firmware version and Spaced/Continuous address view setup in settings as described in [T2B1 Segmented Address Checking#31](https://github.com/trezor/trezor-suite-private/issues/31)

For Ethereum tokens, there's one extra step in the Send modal (and FW ofc) before all the other steps. Otherwise it should behave same as the Ethereum send flow described above.

- [Figma design Ethereum token send modal first step](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=209%3A1387&mode=design&t=01EikyoHUBtnEPV9-1)
- [Figma design Ethereum token send modal last step](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=207%3A1274&mode=design&t=01EikyoHUBtnEPV9-1)

Please note that all data in the design might be sort of gibberish, use real data, labels etc. as we did until now).

Nice to have: if the user would return a step in FW, the modal should ideally return as well to help users checking the contents in the best focus.

**Comment by matejkriz** [comment]
@Hannsek ~~isn't it already in 2.6.0?~~
nope

**Comment by matejkriz** [comment]
QA: please see Notes for QA  in PR description https://github.com/trezor/trezor-suite/pull/9716

**Comment by bosomt** [comment]
**QA NOK**

sent issues for different coins but ETH modal does not correspond with model S3 too.
Device asks you to confirm amount but modal is still focused on address even it was already confirmed

 

![telegram-cloud-photo-size-4-5958666962106170901-y](https://github.com/trezor/trezor-suite/assets/31506317/227d6934-bd3f-42a0-9792-9697a8bf6aa7)

**Info:**
 - Suite version: desktop 23.11.3 (71b8305bd14f3cc01d7796157e329f83bf242a6a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.11.3 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2B1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33

**Comment by Hannsek** [comment]
This should now "work" with TT only as there was a bug on TS3. Should be fixed by [this](https://github.com/trezor/trezor-firmware/pull/3393) and it should be in the next fw release. Please try it with current main fw.

**Comment by bosomt** [comment]
**QA OK**

retested ETH flow again and it works as expected

https://www.notion.so/satoshilabs/eth-send-flow-7e8280cb08e548b79d72ad70b7ea5d9d

**Info:**
 - Suite version: desktop 23.11.3 (71b8305bd14f3cc01d7796157e329f83bf242a6a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.11.3 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33
