### ISSUE TITLE
Address poisoning attack vol. 2

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#9580]
Follow up on [this](https://github.com/trezor/trezor-suite/issues/7278).

Scammers came up with new type of this scam. They send transactions with tokens of the same name as users but with no fiat value. User sees it in Suite and copy it into send modal -> get scammed.

From my pov there are several ways how to mitigate this:

- the easiest one (and the worst) is to restrict copying of addresses in eth transaction history and eth transaction details.
- as those tokens have no fiat value (exchange rate not available from Coingecko, Blockbook gets the exchange rates by contract addresses) we can just don't display them
- we can possibly white label known contract addresses (eth definitions) and if Suite will encounter some token with unknown contract address, it can at first:
     - ask user by some modal if he recognizes this transaction. If he says yes, it would be in the tx history and if he say no, it won't be there
     - label it with the warning as we label current poisoned addresses. User would be able to click on the transaction and tell if it is legit or not. If yes, the warning will vanish.

@tomasklim please check these approaches if they are all feasable. Then we decide which would be the best.

**Comment by sime** [comment]
_Might_ be considered a duplicate, dropping here as a reference. https://github.com/trezor/trezor-suite/issues/8119

The approach is to use ethereum definitions as a whitelist of 'safe' contracts. But fresh legit tokens can be flagged as false positive until ETH definitions are updated.

Personally, I see the prioritising tokens with fiat values as a more scalable solution, but unfortunately, not a silver bullet.

**Comment by Hannsek** [comment]
Probably a duplicate, but let's keep them both.

What do you mean by _prioritising_?

**Comment by sime** [comment]
Only that tokens with fiat value are 'safer' than those without a fiat value.

**Comment by Hannsek** [comment]
Closing in favour of the other issue.
