### ISSUE TITLE
You can generate 21 and not 20 fresh receive addresses

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9634]
**Describe the bug**
It is expected that you can generate 20 fresh new receive addresses see https://github.com/trezor/trezor-suite/issues/8310 bu actually you can generate 21 of them. See screenshot.

Managed to reproduce it on production and on develop version of Trezor Suite

**Steps to reproduce:**
1. Add fresh receive addresses till possible
2. Count them

**Info:**
 - Suite version: web 23.9.3 (f903de22010dc963973d99e84514b4b243e92109)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="455" alt="Screenshot 2023-10-11 at 12 13 15" src="https://github.com/trezor/trezor-suite/assets/31506317/cc5e50f9-9a60-4f42-ba67-d49341cf2a59">

**Comment by bosomt** [comment]
looks like its possible to replicate on fresh account.
On already used account you can generate only 20 new addresses 

<img width="506" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/de472c8f-b61a-472c-aa12-e35f230acdd4">

**Comment by peter-sanderson** [comment]
The problem is in the blockbook. It returns 21 change adrresses instead of 20.

![image](https://github.com/trezor/trezor-suite/assets/152899911/af02f2cd-2294-46f0-b78d-a8838c4c7da9)
