### ISSUE TITLE
Add new FWs 2.6.3 to Suite for T2T1 & T2B1

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#9656]
Add new FWs once they ready and signed.

Suite related changes:

- [x] https://github.com/trezor/trezor-suite/issues/9567
- [x] https://github.com/trezor/trezor-suite-private/issues/31
- [x] T2B1 only https://github.com/trezor/trezor-suite/issues/9679

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.11.1 (99636a4d69124507ca182aa0d4699c46fb4334ca)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.11.1 Chrome/116.0.5845.228 Electron/26.4.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.32
