### ISSUE TITLE
T2B1 link to Knowledge Base from settings

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#9657]
If there's a T2B1 device connected to Trezor Suite, there are 2 Authenticity Check related items shown in the Device Settings. Please provide more context to the users by adding a link to the related Knowledge base article:

- Check device: Please add a link (`Learn more` button) to the Knowledge Base article
- Disable device check: Please change the link from the current Blog post to the KB article

KB Article link: https://trezor.io/learn/a/trezor-safe-3-authentication-check

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.11.0 (328ab76b499da4a79633883b721d8ace3556285e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
 - OS: MacIntel
 - Screen: 2160x1350
 - Device: Trezor T2B1 2.6.2 regular (revision 6e5967af25de87bebd331d697e6ef940e64286ef)
 - Transport: BridgeTransport 2.0.33
