### ISSUE TITLE
Don’t allow to run two coinjoins at the same time

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#9661]
ℹ️ Trezor needs circa 45s to sign whole coinjoin transaction.

Coordinator doesn’t provide enough time to sign more transactions with one trezor. Therefore it is safer to disable more coinjoin rounds at the same time.

Allow only one device, one passphrase, and one network [bitcoin, testnet, regtest] per coinjoin session.

When user wants to start another coinjoin, open modal with warning.

**Proposal**, _feel free to edit @Hermez-cz_
Message: `Only one coinjoin is allowed at the same time`
Secondary button: `Keep the previous`
Primary button: `Run new one`

**Comment by MiroslavProchazka** [comment]
Coinjoin feature was discontinued as of June 1st, 2024. I’m closing this issue
