### ISSUE TITLE
Update links on firmware repo master -> main

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#9664]
https://satoshilabs.slack.com/archives/CKN5C51CJ/p1697205032351059?thread_ts=1696501753.849209&cid=CKN5C51CJ

trezor-firmware repository switched the main branch, we have some links in Suite/Connect to it, let's update them.

There is an automatic redirect on github side so there should be no rush.

**Comment by komret** [comment]
**QA:** changes mostly in readmes and comments. FW changelog links is the only part of runtime code that was changed.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.11.0 (1abb3790e0c6c87d94924d4c7d765c6392deed4a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
 - OS: MacIntel
 - Screen: 3840x2160
 - Device: Trezor T2T1 2.6.3 regular (revision b95b2182fa67f7823f25e724d6702e531312e918)
 - Device: Trezor T2B1
 - Transport: BridgeTransport 2.0.33
