### ISSUE TITLE
Drop non-error toast messages form Authenticity Check in the Onboarding

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#9669]
The non-error toast messages are not needed, as the flow itself and the copy within guides the users. Please leave only the error toast messages that can provide more context to the users if anything goes wrong.

**Comment by komret** [comment]
**QA:** After discussion with @Hermez-cz, I removed the success toasts for PIN and backup steps as well. Explanation in the [PR](https://github.com/trezor/trezor-suite/pull/9673). Toasts should still work in the settings as previously.

**Comment by bosomt** [comment]
Maybe we can consider removing toast messages from name and homescreen to keep consistency ?

<img width="1160" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/3586b5aa-6947-46dc-a36f-747481d4e899">

**Info:**
 - Suite version: web 23.11.0 (68b722eb30a16a758450dd3c37d88e5b6aa2b00e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: Trezor T2T1 2.6.3 regular (revision c937f21447966b31e930ae8d20d1093d20e9fa66)
 - Transport: BridgeTransport 2.0.32

**Comment by komret** [comment]
@bosomt We decided to keep those because they are the only confirmation the settings changed. Unlike the other cases, which are confirmed by success screens.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.11.0 (68b722eb30a16a758450dd3c37d88e5b6aa2b00e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: Trezor T2T1 2.6.3 regular (revision c937f21447966b31e930ae8d20d1093d20e9fa66)
 - Transport: BridgeTransport 2.0.32
