### ISSUE TITLE
Tailored security/authenticity fail result copy

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#9674]
Currently there is only one common copy for two kinds of check:

1. Device security check, where users check if their device is the one depicted in Suite and if the device was bought from the official Trezor Shop or a trusted reseller etc. (users' choice)
2. Device authenticity check, where suite checks the device's authenticity without users actively evaluating anything.

Negative result screen has the same copy for both cases and it looks like this now:

![Image](https://github.com/trezor/trezor-suite/assets/88533514/11137e37-4d8c-4480-8c19-6bcbbd730da7)

Please divide the negative result screens:

1. Device security check negative result screen - please separate this one and change the copy to the one in [this design](https://www.figma.com/file/BUMem1C7j4roQDyJf9yxQT/Exploring-Onboarding?type=design&node-id=2773%3A1905&mode=design&t=P65T8eBkBF8R6e90-1). Please make all translation keys separate even if some of the strings remain unchanged, so we can easily change them independently afterwards.
2. Device authenticity check negative result screen - please keep this one as it is now

**Comment by komret** [comment]
> Please make all translation keys separate even if some of the strings remain unchanged, so we can easily change them independently afterwards.

@Hermez-cz This approach can cause some issues because Crowdin has no power over the related icons, number of items in the list or translation variables (e.g. a word **bold**) and we may end up with duplicate translations if not all items change. Please let's try to avoid this approach in the future and have at least some temporary copy before coding it.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.11.0 (68b722eb30a16a758450dd3c37d88e5b6aa2b00e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: Trezor T2T1 2.6.3 regular (revision c937f21447966b31e930ae8d20d1093d20e9fa66)
 - Transport: BridgeTransport 2.0.32
