### ISSUE TITLE
FW type switch warning modal improvement

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#9679]
### Problem statement
On Trezor Safe 3, the FW switch between Universal and BTC Only firmware will wipe the device, because that's safer.
We need to update the flow in Suite to respect this, as currently the switch can be done without wiping the device. It will remain the old way for T1 and TT to avoid device wiping for the FW update that will introduce this feature.
Technically, the vendor header will be different for different FW types.

### Solution
We need to separate the Universal<->BTC Only FW switch flow from the "normal" FW reinstallation flow that is and will be used for FW updates or reinstallation of the same. Wiping the device is a serious step, so we need to help users to understand that it's going to happen, what it means and what they need to do.

**Current FW re-installation flow:**

1. [User goes to Settings > Device > Firmware > Type, clicks the [Switch to Bitcoin-only] button (or Universal in the opposite direction)](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=209%3A1521&mode=design&t=01EikyoHUBtnEPV9-1)
2. [Firmware installation modal window is shown](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=209%3A1522&mode=design&t=01EikyoHUBtnEPV9-1)
3. User clicks the [Install firmware] button
4. [Do you have your recovery seed (wallet backup)? step is shown in the modal](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=209%3A1525&mode=design&t=01EikyoHUBtnEPV9-1)
5. User clicks the "Yes, I do" checkbox, [Continue] button becomes active
6. User clicks the [Continue button]
7. FW reinstallation goes on without wiping the device

**Proposed FW re-installation flow:**

1. User goes to Settings > Device > Firmware > Type, clicks the [Switch to Bitcoin-only] button (or Universal in the opposite direction)]
2. Firmware installation modal window is shown ([Figma design](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=210%3A6306&mode=design&t=01EikyoHUBtnEPV9-1)) PLACEHOLDER COPY ⚠️
3. User clicks the [Re-Install] button
4. Do you really have your recovery seed (wallet backup)? step is shown in the modal ([Figma design](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=210%3A6310&mode=design&t=01EikyoHUBtnEPV9-1)) PLACEHOLDER COPY ⚠️
5. User clicks the "Yes I do have my backup seed ready and readable." checkbox, [Re-install and Wipe] button becomes active
6. User clicks the [Re-install and Wipe] button
7. FW reinstallation goes on *with* wiping the device

**Comment by bosomt** [comment]
**QA OK**

model T and model One Universal<->BTC Only FW changed multiple times/ways and no wipe or warning


**Info:**
 - Suite version: desktop 23.11.1 (99636a4d69124507ca182aa0d4699c46fb4334ca)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.11.1 Chrome/116.0.5845.228 Electron/26.4.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.3 bitcoin-only (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.32

**Comment by STew790** [comment]
**QA OK**
Two warnings before the installation and also a warning right before confirming on device when changing BTC only<-> Universal FW.
![image](https://github.com/trezor/trezor-suite/assets/48477147/c0a503fe-770c-4072-b02a-4ce9b05b8330)
![image](https://github.com/trezor/trezor-suite/assets/48477147/485aa93a-6dec-4fec-b002-606bb795dd41)

**Info:**
 - Suite version: desktop 23.11.2 (8a61e6c12d84e2ead068702c02a49bb20d5ffaa7)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.11.2 Chrome/116.0.5845.228 Electron/26.4.2 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.32
