### ISSUE TITLE
Connect trezor - Fine tune images and icons

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#9682]
Finalize images for Connect device module in mobile app. 

1. [x] Welcome flow - screen with Connected Device - please put there animation (#10192)
2. [x] Connect Trezor screen - please put there animation (#10192)
3. [x] Empty app (divider) - please replace icon for illustration
4. [x] Bottom sheet Receive flow no.1 - insert the picture 
5. [x] Bottom sheet Receive flow no.2 - insert the picture 
6. [x] "Connect Trezor" element
- cable: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=5237%3A21396&mode=design&t=IV8zWxZMLHOWkfw8-1
- Confirm on Trezor: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=4603%3A36189&mode=design&t=IV8zWxZMLHOWkfw8-1

illustrations are available in Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=21584%3A7624&mode=design&t=QeLkAUX9AmU0sqxP-1 (there are also illustrations and animation showed in design)
animation attached in lottie

[connect_device.json.zip](https://github.com/trezor/trezor-suite/files/13522881/connect_device.json.zip)

**Comment by mnuky** [comment]
Updated picture for Bottom sheet Receive flow no.2 here: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=5324%3A22323&mode=design&t=LS1uGmUj9VxVGC6E-1
