### ISSUE TITLE
P2P Trade not showing any offers

### ISSUE THREAD

**Issue by marek-andrsk** [trezor/trezor-suite#9683]
P2P offers are not showing, user stays on the same page.

**Info:**
-   Suite Version: app+web, 23.10.1

**How to reproduce**

- Select BTC coin and click on Trade button
- Click on Buy P2P tab
- Enter any amount and click on Show offers

**Expected behavior**
P2P offers from hodlhodl are shown in comparator.

**Screenshots**
![image-20231017-135402](https://github.com/trezor/trezor-suite/assets/6542812/9ab23d0a-24c2-4209-8a90-a9555294ad61)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.11.0 (68b722eb30a16a758450dd3c37d88e5b6aa2b00e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: Trezor T2T1 2.6.3 regular (revision 297b2bade72c55033fc3c93c1da818c42b7f453d)
 - Transport: BridgeTransport 2.0.32
