### ISSUE TITLE
Handling of multiple parallel backend initialization attempts.

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#9701]
**Describe the bug**
When there are multiple parallel calls accessing a connect backend that is not initialized yet, the initialization happens for every call rather than once. As a result, the `blockchain-connect` message is dispatched for every call. Since this message is handled inside of  [blockchainMiddleware](https://github.com/trezor/trezor-suite/blob/618388a3434997bc748c86f2db4301c26a0a43db/suite-common/wallet-core/src/blockchain/blockchainMiddleware.ts) it leads to many unnecessary updates that result in lower app performance. 

**How to reproduce**

1.	call any blockchain method (e.g. `TrezorConnect.blockchainGetAccountBalanceHistory`) multiple times in parallel for a blockchain backend type that is not initialized yet. For inspiration see this [graphDataFetching]( https://github.com/trezor/trezor-suite/blob/84ac2b5ae3aad6dfccf8a7ad9b425440ff9d6fbb/suite-common/graph/src/graphDataFetching.ts#L159) example. 
3.	Inside of the `TrezorConnect.blockchainGetAccountBalanceHistory` it checks if the backend is already initialized. If not, it tries to initialize it. Since the method is called multiple times in parallel, it will attempt to connect to the backend multiple times in a row. Since the connection does not yet exist, initialization will actually occur every time.
4.	After each initialization, a message “blockchain-connect” is dispatched from the [Blockchain.init()](https://github.com/trezor/trezor-suite/blob/27d68d107208d22d88ee34e4c7deb4c8d1cb4a6f/packages/connect/src/backend/BackendManager.ts#L39) method.
5.	Each of these messages is intercepted in[ suite-common/blockchainMiddleware](https://github.com/trezor/trezor-suite/blob/618388a3434997bc748c86f2db4301c26a0a43db/suite-common/wallet-core/src/blockchain/blockchainMiddleware.ts#L22), and as a reaction, syncAccountsWithBlockchainThunk is triggered, which calls `TrezorConnect.getAccountInfo` for each account separately.

Ideally, it should execute the `TrezorConnect.getAccountInfo` only once per account. Now it is executed for every connection attempt. This leads to huge performance overhead.

**Expected behavior**
If you try to initialize a backend, there should be some check controlling if the connection is not being created at the moment. If yes, wait for it rather than creating it again.

**Comment by mroz22** [comment]
@marekrjpolak is about to do some preliminary investigation to asses how much effort would be needed

**Comment by marekrjpolak** [comment]
Hi @PeKne,

it should be relatively easy and uncontroversial to await the already-running init from all the concurrently called methods if we decide to do so.

Correct me if I'm wrong, but from this non-native [init action](https://github.com/trezor/trezor-suite/blob/5352aee04d475462ab45ed9464d94a9ddad2c967/packages/suite/src/actions/suite/initAction.ts#L53) it seems that backends for all the activated coins are initialized exactly once before the execution continues, right? I've found out that you have [almost identical code in native](https://github.com/trezor/trezor-suite/blob/5352aee04d475462ab45ed9464d94a9ddad2c967/suite-native/app/src/initActions.ts#L29) as well, except the `initBlockchainThunk` is not awaited. Would it help to await it? And if not, shouldn't the backends be initialized eagerly as in web/desktop, rather than lazily by the connect methods?

**Comment by PeKne** [comment]
@marekrjpolak I just tested it and it works like a charm! 👏 Thanks for pointing me out, it would take me ages to find this little difference.

Since this resolves our performance problems, I think that this issue is very low prio now. Maybe even ready to close? Up to you.

**Comment by Nodonisko** [comment]
@marekrjpolak Sadly we can't really on awaiting this during app init. If for example user have app in background for longer period of time all living connection are terminated and if resumes app from background, connections needs to be estabilished again which will basically by-pass this check at init time.

**Comment by Hannsek** [comment]
So, what is the status of this? Will we work on this later or can we close it?

**Comment by marekrjpolak** [comment]
> So, what is the status of this? Will we work on this later or can we close it?

@Hannsek it was fixed by @Nodonisko in a different way: https://github.com/trezor/trezor-suite/pull/9766

**Comment by Hannsek** [comment]
Closing this then. We can reopen it in the future.
