### ISSUE TITLE
Data analytics: Tradebox button

### ISSUE THREAD

**Issue by kolomaznikt** [trezor/trezor-suite#9711]
We want to track the new buttons clicks. Ideal would be a separate new event `accounts/tradebox/button`  with specific parameter `symbol` for coin (currency) and `type` for buy/sell/exchange differentiation.

**Comment by bosomt** [comment]
**QA OK**

```
GET | https://data.trezor.io/suite/log/web/develop.log?c_v=23.11.0&c_type=accounts/tradebox/button&c_commit=9745dbb7a78674007258f39cfa144dfdcd8aeb59&c_instance_id=Z04wNMyHlf&c_session_id=Z7qeBw8mBM&c_timestamp=1698763630371&c_message_id=kXxNerHCt2&symbol=btc&type=sell
```
**Info:**
 - Suite version: web 23.11.0 (9745dbb7a78674007258f39cfa144dfdcd8aeb59)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0
 - OS: MacIntel
 - Screen: 2859x1608
 - Device: Trezor T2T1 2.6.3 regular (revision 104124eb1346c9c2cb3d5e58bf9e1cf26f12b10d)
 - Transport: BridgeTransport 2.0.32
