### ISSUE TITLE
Change Cardano testnet explorer 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9721]
**Describe the bug**
Change Cardano testnet explorer from testnet.cexplorer.io to preview.cexplorer.io.
Current one reports that its deprecated and reports coins unconfirmed even after 30 minutes.

**Info:**
 - Suite version: web 23.11.0 (8a8ef774f6ef1a2858ee7e94fa076d07e8d24d06)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: Trezor T2T1 2.6.3 regular (revision 4ea48c1fe67c91de5395ee7721ce23fc6cfcbe75)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="596" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/1f45b6e5-207a-4a3b-83d4-be8f3c691898">

**Comment by slowbackspace** [comment]
It should be fixed now ☺️

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 23.10.1 (6c8d061f7305947b0270a2560e4cc65d1f7ded27)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: Trezor T2T1 2.6.3 regular (revision 4ea48c1fe67c91de5395ee7721ce23fc6cfcbe75)
 - Transport: BridgeTransport 2.0.33
