### ISSUE TITLE
Inform user he connects device with unsupported FW version

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9730]
If user connects device with FW version we don't support, he is informed that he must first update the Trezor in Trezor Suite and then connect the device again

Acceptance criteria:
When user connects device with unsuppported version of FW, he can't use the app with connected Trezor and is informed, he must update the FW in Desktop Suite first. 

Figma: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=4064%3A24657&mode=design&t=CKCzBe1aAcFjAFdS-1

**Comment by bosomt** [comment]
**QA OK**

tested with model T and 2.1.1 firmware

Nothing phone 1 - Android 13
23.11.1 (601) 
9e363ff - [develop] - feat(suite-native): bootloader error alert (#10127)
