### ISSUE TITLE
Inform user he connects device which is not set up

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9731]
When user connects Trezor Device which has not been set up yet, he is informed that he must first set up the device in Trezor Suite and then come to the mobile app

Acceptance criteria:
When user connects device which is not set up, he can't use the app and is informed, he must initialise the device first in Desktop Suite and then come back

Figma: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=4068%3A24715&mode=design&t=CKCzBe1aAcFjAFdS-1

**Comment by bosomt** [comment]
**QA OK**

tested on Android 13 - Nothing phone 1
 23.11.1 (591)
f3c6929 - [develop] - Fix\/discovery fixes (#10061)

**Comment by bosomt** [comment]
@mnuky do we have detection of device connected in bootloader mode in progress ?
Noticed that Lite app informs you that no FW is installed and device needs to be initialized even device is already set up  BUT connected in bootloader mode ?

**Comment by mnuky** [comment]
@bosomt good catch, we don't have any message for device in bootloader mode, I will create an issue to handle it

**Comment by bosomt** [comment]
**QA OK**

tested with device with no seed and with device in BL mode 

Nothing phone 1 - Android 13
23.11.1 (601) 
9e363ff - [develop] - feat(suite-native): bootloader error alert (#10127)
