### ISSUE TITLE
Include destination tag in UI in coinmarket

### ISSUE THREAD

**Issue by FreeWall** [trezor/trezor-suite#9740]
**Describe the bug**
What I suggest is to include a destination tag for XRP sell in Trezor Suite in overview of transaction. See attached image. What needs to be communicated correctly to user is how to call the field? For XRP it is destination tag. For XLM it is called memo.

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/12121074/9945c7bf-fed0-4581-9779-469008baaff5)

**Comment by Rcargon81** [comment]
Sending XRP to another wallet requiring a Destination Tag will still go through with an error, even after correcting the issue with the correct destination tag.  Cannot duplicate the problem, there are no logs to confirm this issue.
