### ISSUE TITLE
Disconnect device status

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9747]
As a user I would like to be redirected to the correct state, when I disconnect the device in order know what happens. 

There are two ways how to disconnect the Trezor device from app:
1. From nav bar via button Eject
2. Manual disconnection the Trezor Device (unplug the device)

Acceptance criteria:
When user disconnects the Device via Eject button or manually and has no portfolio tracker, he is redirected to "Empty dashboard" screen. 
If user has portfolio tracker with imported coins, he is redirected to Portfolio tracker Dashboard

**Comment by juriczech** [comment]
When disconnect feature is implemented it should be used in `Device manager` and in module connect device (alert)

**Comment by PeKne** [comment]
Closed by #10063

**Comment by bosomt** [comment]
**QA OK**

Nothing phone 1 - Android 13
23.11.1 (601) 
9e363ff - [develop] - feat(suite-native): bootloader error alert (#10127)
