### ISSUE TITLE
Ugly coin icons

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#9756]
**Describe the bug**
Coin icons are rendered imperfectly.
It happens on my desktop app, in Brave, and @bosomt has reproduced it on Chrome as well. 
Firefox works as expected.
![screenshot_2023-10-26_at_08 00 46_480](https://github.com/trezor/trezor-suite/assets/26002916/27622fca-3fc7-48c8-aebf-751ee554dd7c)

**Steps to reproduce:**
1. Open Suite
2. Watch

**Info:**
 - Suite version: desktop 23.10.1 (6c8d061f7305947b0270a2560e4cc65d1f7ded27)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.10.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
![image_360](https://github.com/trezor/trezor-suite/assets/26002916/31fc8573-1fcb-4ac0-ad70-832caf8cac38)

**Actual result:**
![image_360-1](https://github.com/trezor/trezor-suite/assets/26002916/6be22df4-14c9-40c3-a787-32f9a0e28d26)

**Comment by matejkriz** [comment]
It's not related to react-svg, because I can see the issue even if I just render the plane svg in a browser. 

It's an issue with the ANGLE backend of the WebGL renderer. If you set the backend on Metal in Chrome via chrome://flags/#use-angle, icon is rendered just fine. If you switch it on OpenGL or default on macOS 14 Sonoma, the icon is rendered ugly.

So far I don't know what we can do about it. Will investigate.

**Comment by bosomt** [comment]
**QA OK**

<img width="93" alt="Screenshot 2023-11-03 at 12 15 25" src="https://github.com/trezor/trezor-suite/assets/31506317/f7c93151-0d22-4480-9762-696691b00d99">

**Info:**
 - Suite version: web 23.11.1 (091c08da42e804460aa8f54b1155f6888b470391)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.32
