### ISSUE TITLE
Device management

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#9759]
We're now switching from operating with single device to multiple device system. This requires all logic to be "lifted" level up if needs be. 

Also Portfolio tracker logic should now be conditioned by hidden device (if its selected or not).

- [x] Allow switching between portfolios / devices
- [x] Account list - remove add button for non imported devices
- [x] Empty states - these are derived from accounts, but these accounts should be only taken from the selected device
- [x] Disable removing of account imported by device discovery

**Comment by bosomt** [comment]
**QA OK**

50fe764 - [develop] - chore(suite-native): update skia + reanimated (#10202)
