### ISSUE TITLE
Analytics for connected Trezor

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9763]
- [x] device connect
- [x] empty dashboard
- [x] coin discovery
- [x] switcher
- [x] receive
- [x] onboarding complete
- [x] eject
- [x] update notion

**Comment by kolomaznikt** [comment]
Hi, after discussion with Katka, we came up with a few new analytics events and one updated event. If there is any confusion, I will be happy to explain here or on Slack.

new event `device_connect` triggered when device is connected, with parameters:
- firmwareVersion : string
- pinProtection : boolean
- deviceModel : string
- isBitcoinOnly : boolean
- deviceLanguage : string
- firmwareState : string (”supported firmware | unsuported firmware | not installed firmware | other”)

new event `empty_dashboard/action` triggered when user clicks on connect device or asset sync on an empty dashboard, with parameter:

- action : string (”connect device | asset sync”)

new event `coin_discovery` triggered when discovery is done, with parameters:

- load_duration : number
- [one parameter per each specific coin] : number of accounts discovered (eg. btc : 2)

new event `switcher` triggered when user clicks on something in switcher, with parameter:

- action : string  (”device” | “portfolio” | “sync” - only option for ios)

new event `receiveAddress/confirm_on_trezor` triggered by click in receive address flow, no special parameter

event `onboarding_completed` update with a new parameter:

- biometricsEnabled : boolean

**Comment by juriczech** [comment]
Discovery finished by https://github.com/trezor/trezor-suite/issues/10143
