### ISSUE TITLE
Device Receive - UI for each device model

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#9778]
## Address chunking acceptance criteria
There will different view of the address per device:
TS3 - address is displayed in chunks and has its own font (Pixel Operator Mono 8, Regular)
TT - address is displayed in chunks and has its own font (Roboto Mono, Medium)
T1 - address is displayed as string (no chunks) and has its own font (Pixel Operator 8, Bold)

Figma: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=2303%3A9941&mode=design&t=KK5AYCikGNAanrLR-1

**Comment by bosomt** [comment]
**QA NOK**

address not chunked with model T fw 2.6.3
feel free to approve if its expected

Nothing phone 1 - Android 13
23.11.1 (601) 
9e363ff - [develop] - feat(suite-native): bootloader error alert (#10127)

**Comment by PeKne** [comment]
If it is not chunked on the mobile screen, it is not expected and it is a bug. On the other hand if it is not chunked on the device screen it is expected. We are waiting for the connect fixup to make it possible to chunk address on the device screen.
