### ISSUE TITLE
Missing frame of Anonymous data collection modal

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9783]
**Describe the bug**
Missing frame of `Anonymous data collection` modal.
Same results in Google Chrome and Mozilla Firefox.
Same results on staging and on production.

**Screenshots**
Staging
![image](https://github.com/trezor/trezor-suite/assets/31506317/3bb3f86a-6d77-4399-8ebf-0097abc8485a)

Production
![image](https://github.com/trezor/trezor-suite/assets/31506317/4d2d30a0-fb13-4cc8-86be-0cbaed383548)

**Comment by mroz22** [comment]
maybe @dahaca has idea what has changed in components package? we did not touch it imho. it feels like some hardcoded z-indices are gone?

**Comment by Hannsek** [comment]
Note: We will have to implement some UI tests for popup in the future.

**Comment by mroz22** [comment]
we have exactly 0 UI tests for suite at the moment :P

**Comment by bosomt** [comment]
**QA OK**
