### ISSUE TITLE
Device name banner too thick in connect explorer

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9785]
**Describe the bug**

Device name banner is too thick and overlaps part of connect interface

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/31506317/70e8e1d1-71a2-4be9-ba8c-12d05a7e1a0d)
![image](https://github.com/trezor/trezor-suite/assets/31506317/5fa9da57-056a-44f3-ba97-deb628bd14f5)

**Comment by Hannsek** [comment]
You mean thick right?

**Comment by bosomt** [comment]
right ;) fixed :)

**Comment by bosomt** [comment]
**QA OK**
