### ISSUE TITLE
Polishing empty state dashboard of portfolio tracker

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9794]
Adjust the empty state of portfolio tracker dashboard to final design: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=3804%3A12800&mode=design&t=YnHRkTshNoYXfIaG-1

**Comment by juriczech** [comment]
Closing as completed
