### ISSUE TITLE
Add French as an official language

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#9795]
Please take French language from CrowdIn and make it an official language. Please keep in mind the Messaging system as well when adding a language.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 33.11.1 (a70b4d364b1233d4ed620473c04755f34a798acd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/33.11.1 Chrome/116.0.5845.228 Electron/26.4.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.32
