### ISSUE TITLE
Add Send section

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#98]
- [x] Session storage

Send form for 
BTC & btc like coins

- [x] Address
- [x] Scan address QR code
- [x] Amount 
- [x] Set Max
- [x] Converter to fiat (USD, EUR  etc.)
- [x] Fee (Normal, Economy, High....)
- [x] Clear
- [x] Send
- [x] Add recipient
- [ ] add opt return
- [ ] lock time
- [x] Remove all recipients
- [ ] import from csv
- [ ] RBF (replace by fee) - NTH
- [ ] Select UTXO - NTH
- [x] Fiat 
- [x] Connect composing transactions from connect

ETH
- [x] Address
- [x] Scan address QR code
- [ ] Amount 
- [ ] Set Max
- [x] Converter to fiat (USD, EUR  etc.)
- [ ] Fee (Normal, Economy, High....)
- [x] Clear
- [ ] Send
ETH advanced
- [ ] Gas limit
- [ ] Gas price
- [ ] Data
- [ ] Connect composing transactions from connect
- [ ] RBF - NTH

Ripple
- [x] Address
- [x] Scan adress QR code
- [x] Amount 
- [x] Set Max
- [x] Converter to fiat (USD, EUR  etc.)
- [x] Fee
- [x] Clear
- [x] Send
Ripple advanced
- [x] Fee
- [x] Destination tag

**Comment by glacierbits** [comment]
Duplicity.
