### ISSUE TITLE
Change the setup (onboarding) time estimate to 20 mins (instead of 5)

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#9802]
On the T2B1 packaging there's an information that the onboarding will take about 20 minutes. We should change it to the same number of 20 minutes in the security check screen button (where we have 5 now).
https://github.com/trezor/trezor-suite-private/pull/42#discussion_r1343674630

**Comment by Hannsek** [comment]
Cannot we change that in Crowdin?

**Comment by STew790** [comment]
**QA OK**
<img width="655" alt="image" src="https://github.com/trezor/trezor-suite/assets/48477147/08bcf642-ba98-4290-a690-3943d3cc1801">

**Info:**
 - Suite version: desktop 23.12.1 (9ec6ac5438d7a952abcbbdc049bf729a47d4e039)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.12.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33
