### ISSUE TITLE
Enable stylelint in components

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#9810]
In https://github.com/trezor/trezor-suite/pull/9803 `stylelint` was disabled for the `components` package because of the abundance of changes on `suite-e` in there. It has to be turned back on.

**Comment by tomasklim** [comment]
This has to be added to `scripts` in `package.json` in components
```
        "lint:styles": "npx stylelint './src/**/*{.ts,.tsx}' --cache --config ../../.stylelintrc",
```

and in root `package.json` you have to add `components` to `lint-staged`

**Comment by tomasklim** [comment]
https://storybook.js.org/docs/react/migration-guide for storybook
