### ISSUE TITLE
Not able to compare receiver address when bumping Ethereum transaction.

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9845]
**Describe the bug**
Not able to compare receiver address when bumping Ethereum transaction.
Address is not actually rendered at same time when you have to compare it on device.
Work as expected on model Safe 3.

**Steps to reproduce:**
1. Send Ethereum tar
2. Bump transaction
3. Observe behavior bump modal and device

**Info:**
 - Suite version: desktop 33.11.1 (a70b4d364b1233d4ed620473c04755f34a798acd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/33.11.1 Chrome/116.0.5845.228 Electron/26.4.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.32

**Screenshots:**
![telegram-cloud-photo-size-4-5920023247263483182-y](https://github.com/trezor/trezor-suite/assets/31506317/30b60a08-34b0-4569-a65f-2738c272406d)
![telegram-cloud-photo-size-4-5920023247263483181-y](https://github.com/trezor/trezor-suite/assets/31506317/7bb0b992-e9ac-4c5e-8a50-026b2abf9525)

![telegram-cloud-photo-size-4-5920023247263483207-y](https://github.com/trezor/trezor-suite/assets/31506317/6611533a-55d2-4611-8b09-19b318cdcdb2)

**Comment by tomasklim** [comment]
@bosomt is it still available?

**Comment by bosomt** [comment]
**QA OK**

i was not able to replicate it 


**Info:**
 - Suite version: desktop 24.11.3 (71f9b21d21c9b033e34fc8c6d33ffd8223ffda73)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.3 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
