### ISSUE TITLE
Discrepancy when bumping and finalizing bitcoin transaction

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9846]
**Describe the bug**
There is discrepancy when bumping and finalizing bitcoin transaction.
There are 3 steps in modal but last thing you confirm on device is fee rate and modal still shows step 2 of 3.
And there is no hold to confirm or press both buttons to confirm on device at end of confirmation.
Same reults for model Safe 3 and model T

**Steps to reproduce:**
1. Send bitcoin transaction
2. Bump transaction
3. Compare Trezor Suite modal and device dialogues

**Info:**
 - Suite version: desktop 33.11.1 (a70b4d364b1233d4ed620473c04755f34a798acd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/33.11.1 Chrome/116.0.5845.228 Electron/26.4.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2B1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Device: Trezor T2T1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.32

**Screenshots:**
![telegram-cloud-photo-size-4-5920023247263483221-y](https://github.com/trezor/trezor-suite/assets/31506317/d2bd75a4-6ee1-4e6a-a579-840d974acce8)

https://github.com/trezor/trezor-suite/assets/31506317/ab04f07a-43e8-49c4-83a6-6aaedb21c95f

**Comment by AdamSchinzel** [comment]
Have a fix but firstly we need to check if it's really a bug on Suite (displaying it) or bug on FW (not displaying it). Imho it makes sense to have it there but I asked @Hermez-cz what is his view on this.

**Comment by bosomt** [comment]
**QA OK**

TT OK
S3 follow up issue https://github.com/trezor/trezor-firmware/issues/3452

**Info:**
 - Suite version: desktop 23.12.2 (66925d36a98887aac3ab7143bc442ed3bc70a061)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.12.2 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
