### ISSUE TITLE
Dependencies: proxy-memoize

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#9857]
- update `proxy-memoize`
- `2.0.4` was breaking mobile app

**Issues:**
- https://github.com/trezor/trezor-suite/pull/8912
- https://github.com/trezor/trezor-suite/pull/8700#issuecomment-1633670581

**Comment by matejkriz** [comment]
We get back to Reselect, so proxy-memoize is no longer included in our dependencies https://github.com/trezor/trezor-suite/pull/15333
