### ISSUE TITLE
Finalize transaction only bumps a fee of a transaction

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#9874]
**Describe the bug**
When I want to Finalize a transaction, it only increases the fee of the transaction and I can still bump the fee higher. It does not turn the RBF off.

**Steps to reproduce:**
1. Send a transaction with enabled RBF
2. Try to finalize this transaction
3. See that the fee of the transaction is higher but the RBF is not turned off

**Info:**
 - Suite version: desktop 23.11.1 (9a466944f069ad7aba27ac5aeef84dce12aa7e64)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.11.1 Chrome/116.0.5845.228 Electron/26.4.2 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
Finalizing a transaction turns off the RBF and actually finalizes the transaction.

**Actual result:**
Finalize transaction only bumps a fee of a transaction

**Comment by bosomt** [comment]
i was not able to replicate on production, tx was finalized

https://btc5.trezor.io/tx/8087a7f4b8b7a2a3a154e043485b04f5ae0f3fc0441d68cdee47ccdc05940fef

**Info:**
 - Suite version: web 23.10.1 (6c8d061f7305947b0270a2560e4cc65d1f7ded27)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0
 - OS: MacIntel
 - Screen: 3840x2160
 - Device: Trezor T2B1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33

**Comment by STew790** [comment]
**QA OK**
I was able to finalize a transaction and it turned off the RBF.
https://btc1.trezor.io/tx/fc214c26c763dfb92c468f55b6f220de8e2853acd88f36ddb5deda7f264a9e07

**Info:**
 - Suite version: desktop 23.11.2 (8a61e6c12d84e2ead068702c02a49bb20d5ffaa7)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.11.2 Chrome/116.0.5845.228 Electron/26.4.2 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33
