### ISSUE TITLE
Cardano Send Max: Not enough funds

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#9888]
**Describe the bug**
On Cardano testnet when trying to Send funds, if in the Send form I click the [Send max] toggle, instead of sending a feasible maximum, the input stays empty, is highlighted in red and a "Not enough funds" validation message is shown.

**Info:**

-   Remembered Wallet: no
-   Suite Version: app 23.11.1, also web 23.11.2
-   Browser: Arc 1.15.1 (43023)
-   OS: MacOS 14.1 (23B74)
-   Bridge: 2.0.33
-   Firmware Version: T2B1, 2.6.3

**How to reproduce**

1. Go to Cardano testnet account (even better mainnet, just I don't have any ADA there)
2. Click on [SEND]
3. Enter a valid address
4. Click the [Send max] toggle
5. Observe the error

**Expected behavior**
After clicking the Send max toggle, I'd expect the rest of the fields being filled in accordingly. That means that total will be whatever is on my current Cardano account and it will be divided correctly into fee and amount sent in the Send form.
**Screenshots**

![Image](https://github.com/trezor/trezor-suite/assets/88533514/a5222a8a-9a71-4694-8563-e7c405da31ba)

**Comment by STew790** [comment]
**QA OK**
Works fine for me on testnet and mainnet.

![image](https://github.com/trezor/trezor-suite/assets/48477147/f118c77b-a8f8-4c18-817b-6b7594766bcb)
![image](https://github.com/trezor/trezor-suite/assets/48477147/c964015d-288b-47b8-8923-c35c9d96ec49)

**Info:**
 - Suite version: desktop 23.11.2 (8a61e6c12d84e2ead068702c02a49bb20d5ffaa7)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.11.2 Chrome/116.0.5845.228 Electron/26.4.2 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33

**Comment by STew790** [comment]
**QA NOK**
`setMax` feature is actually not working for some accounts. Discussion here https://satoshilabs.slack.com/archives/C0292ULQHGD/p1699890907150469
cc @slowbackspace

**Comment by bosomt** [comment]
**QA OK**

tested on our all ADA and TADA with funds

**Info:**
 - Suite version: web 23.12.0 (fd1a094335763c8f10a37d871f46a66365707b79)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33
