### ISSUE TITLE
Account detail buttons dis-/appear wildly at window resizing

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#9891]
**Describe the bug**
On the account detail, if you're shrinking your app window, the [Send][Receive][Trade] buttons should disappear when they don't fit the screen anymore and appear back when they fit back again.
1. The disappearing is a bit fuzzy, they dis-/appear wildly at resizing.
2. If I'll shrink the window entirely for them to disappear, open Recive, Send or other window, expand the window to maximum width and close the Receive or other window, the buttons remain hidden under the [...] menu.

**Info:**

-   Remembered Wallet: no influence
-   Suite Version: app 23.11.1
-   OS: MacOS 14.1
-   Bridge: no influence
-   Firmware Version: T2B1 2.6.3

**How to reproduce**

1. Go to any account
2. Resize your app window fiercely back and forth
3. Observe the buttons dis-/appearing
4. Shrink the window to a narrow width where the buttons are steady hidden
5. Click the [...] menu and select Receive
6. While on the Receive window, widen your app window to the maximum width
7. Close the Receive window
8. Observe the buttons missing

(the same happens also in the opposite direction)

**Expected behavior**
Buttons should be present when they fit without overlaps, buttons should be hidden in the [...]menu when they don't fit without overlaps; no other situations or their combinations should occur no matter how you much the user resizes the app window.

**Screenshots**
https://drive.google.com/file/d/19scNIjqKUpJYS80uCUNgqNFSYIGBZsx7/view

**Comment by peter-sanderson** [comment]
Info from @dahaca  we had the implementation for this but it was removed for some reason
- https://github.com/trezor/trezor-suite/blob/cecd1d6a218aae3e2d50317ffb32963e69a63cf8/packages/suite/src/components/suite/OverflowItems.tsx
- https://github.com/trezor/trezor-suite/commit/25b405118502f848ad93d4e3c0353e08eface248

:point_up: should be investigated.

**Comment by komret** [comment]
Appears to be resolved by the Empower redesign.

**Comment by bosomt** [comment]
**QA OK**
