### ISSUE TITLE
@trezor/connect-web connection does not work within iframe for chrome extensions

### ISSUE THREAD

**Issue by resetko-corp** [trezor/trezor-suite#9894]
**Describe the bug**
Not able to connect and pull ethereum addresses from the device when in iframe

**Info:**

-   Remembered Wallet: yes/no (not sure)
-   Suite Version: `"@trezor/connect-web": "9.1.5"`
-   Browser: `Google Chrome Version 119.0.6045.105 (Official Build) (64-bit)`
-   OS: Linux
-   Bridge: Version: 2.0.30
-   Firmware Version: model T, [2.6.0]

**How to reproduce**

1. Pull the [repository](https://github.com/resetko-zeal/trezor-test-extension), do `yarn` then `yarn build`, then install unpacked extension from `dist` folder
2. Click on extension action button, on the page there are two buttons, each attempting to pull ethereum addresses from the device. The button out of iframe `connect and fetch! [A]` would work, but the button within iframe won't `connect and fetch! [B]`, popup appears for a moment, and then disappears
3. As well extension will inject iframe on all pages (it's a bit aggressive, but for testing purposes :)), and in this iframe the connection is also don't work (`connect and fetch! [C]` button) with same outcome, popup appears for a moment with "establishing connection with host", and then disappears

**Expected behavior**
Connection through bridge should work regardless of iframe usage (at least according to https://github.com/trezor/trezor-suite/issues/9644, where it's mentioned as webusb issue)

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/112621289/e1be4b1c-edaa-40c2-86d0-c6eba45e12c1)
![image](https://github.com/trezor/trezor-suite/assets/112621289/39e4587c-dbf3-4465-b18d-ce813b2f5338)

**Comment by mroz22** [comment]
hi, 
I tried your repro and I confirm it behaves the way you describe. But this is the expected way.
<img width="1338" alt="image" src="https://github.com/trezor/trezor-suite/assets/30367552/c24478ae-94cc-45a6-b56f-0c6d189e1ba3">

We are maybe mixing up term `iframe`. `@trezor/connect-web` at the moment, needs to be able to inject iframe. @trezor/connect core logic lives in this iframe. It communicates with popup.html on trezor.io domain. 

This approach works only in some environments. Where it does work:
- web pages
- webextensions frontend or background script (manifest v2)
- webextensions frontend (manifest v3)

There are some limitations on which transports can be used
- Bridge works everywhere
- Webusb only works now in webextensions 

We are working now on:
- being able to use connect directly from service worker in manifest v3 #9525
- we will introduce also possibility to use connect without its internal iframe for web pages later on which will enable webusb everywhere as well.

I am not sure whay you need to work with more iframes introduced on your side? This is something we never tested. So altough it could work in theory, it probably needs some more work to enable that.

**Comment by resetko-corp** [comment]
@mroz22 have you tested the `C` scenario? 

It's the most important scenario for us, the extension injects the iframe companion to do some web3 stuff.

And the main problem is that it was actually working fine on 9.0.6 and suddenly stopped working.

**Comment by mroz22** [comment]
ok, I will check. could you please try running it on older chrome? I don't think we made changes so I suspect some chrome security tightening.

**Comment by Hannsek** [comment]
@resetko-zeal do you have any updates regarding this?

**Comment by resetko-corp** [comment]
Hey, don't really have the older chrome at hand, but will try to do that. Also see that it partially works with brave :thinking:  Why partially is because on latest brave version it does work for one person and does not work for another :exploding_head: 

When you communicate with bridge, you still create Iframe (in that case it's like iframe within iframe, right?) and then do just regular https requests to it, to localhost, am I correct?

I'm bit suspicious of chrome tightening security on making https requests from iframes within iframes, but who knows :D

**Comment by resetko-corp** [comment]
Tested on `Version 112.0.5615.121 (Official Build) (64-bit)` - it works all 3 (A/B/C) scenarios, I have the couple of other versions to test

UPD: on version `Version 115.0.5790.110 (Official Build) (64-bit)` I have "waiting for host to load" infinite spinner in B and C scenario

**Comment by resetko-corp** [comment]
So on the versions I have in my cache:
`Version 113.0.5672.126 (Official Build) (64-bit)` - works :heavy_check_mark: 
`Version 114.0.5735.106 (Official Build) (64-bit)` - works :heavy_check_mark: 
`Version 114.0.5735.198 (Official Build) (64-bit)` - works :heavy_check_mark: 
`Version 115.0.5790.110 (Official Build) (64-bit)` - does not work in B and C :stop_sign: 

So it's somewhere between 114 and 115

It looks to me it's not more like some USB/Bridge communication is broken, but communication between iframe SDK inject and popup is broken somehow. I'm not fully familiar with the code and architecture of the SDK, but maybe you can help to find exact place in code which does not work as expected :thinking:

**Comment by resetko-corp** [comment]
hey @mroz22 @Hannsek, maybe you have some hints/directions to dig into, because v9 popup with 9.1.5 (latest now) version does not work, and mentioned in #9644 potential problems with cookies (https://github.com/trezor/trezor-suite/issues/4878 and https://github.com/trezor/trezor-suite/issues/6129) seems like not the case, at least in brave disabling cookie blocking is not fixing the issue and in chrome allowing 3rd party cookies for all sites is also not fixing it.

**Comment by mroz22** [comment]
I am pretty sure that chrome changed behaviour of Broadcast channel ([maybe this?](https://developer.chrome.com/docs/privacy-sandbox/storage-partitioning/)), which is the mechanism used under the hood to communicate betwee @trezor/connet-web package (by it injected iframe) and popup. Looking into it now.

And yes, there have been some developments now. We merged @trezor/connect-webextension into develop. This makes it possible to run our SDK in serviceworker. Not in production yet but you may experiment with it locally if you want. It does not relly on this Broadcast channel anymore and there is no iframe on our side. 

In the future, we are going to implement some better features negotiation based on env. tldr - we find that we can't communicate for some reason using iframe model, so we skip it and load SKD into popup. This is how the newly added package works actually, it has yet to be implemented for the old one.

**Comment by mroz22** [comment]
btw beta package for webextension/serviceworker is now out https://www.npmjs.com/package/@trezor/connect-webextension

**Comment by resetko-corp** [comment]
> btw beta package for webextension/serviceworker is now out https://www.npmjs.com/package/@trezor/connect-webextension

Hey, just a question on usage, should we use it in service worker _instead_ of the frame? Or it should just work magically, same was as trezor's content script work?

I can't see it registers anywhere when I just try to import it, but from other hand I can't just call `importScripts` at root of the service worker. 

Maybe some minimal example would be helpful :pray:

**Comment by resetko-corp** [comment]
cc @graadient

**Comment by Hannsek** [comment]
Yes, it should be implemented within a service worker.
[Here is a minimal example](https://github.com/trezor/trezor-suite/tree/develop/packages/connect-examples/webextension-mv3-sw) of mv3 web extension with connect-webextension in a  service worker.

**Comment by mroz22** [comment]
@resetko-zeal I'd like to cooperate here. My problem is that I don't tooling around webextensions. With the new package,  you should be able to import it inside serviceworker context and it should just give you API to work with trezor from there. I will happily do changes to this package based on your requests.

**Comment by resetko-corp** [comment]
> @resetko-zeal I'd like to cooperate here. My problem is that I don't tooling around webextensions. With the new package, you should be able to import it inside serviceworker context and it should just give you API to work with trezor from there. I will happily do changes to this package based on your requests.

I think it should be fairly easy to adopt this :thinking: even with current state of the package, let me try :pray: I plan just to proxy TrezorConnect calls through extensions runtime messages

**Comment by mroz22** [comment]
please try. also @karliatto  should have almost ready some proxying solution that will be bundled together with the lib, but it is not merged yet.

**Comment by resetko-corp** [comment]
@karliatto Hey, sorry for a bit long time to reply :) just tried the mentioned package, but unfortunately it does not work for me.

So what I did - I've pulled the latest version of `trezor-suite` repo, and followed build instructions for `connect-webextension`.
So I got `trezor-connect-webextension.js` file, and to keep it supersimple I just put it into my extension as static file.

Then, I do 

```typescript
declare const TrezorConnect: any;
declare const importScripts: any;

importScripts("../trezor-connect-webextension.js");

const fetchAddresses = async (count: number) => {
  try {
    await TrezorConnect.init({
      lazyLoad: false, // this param will prevent iframe injection until TrezorConnect.method will be called
      connectSrc: "https://connect.trezor.io/9/",
      debug: true,
      hostLabel: "Zeal wallet",
      webusb: false,
      manifest: {
        email: "hi@zeal.app",
        appUrl: "https://www.zeal.app/",
      },
    });
  } catch (e) {
    console.log("trezor init error", e);
  }

  const result = await TrezorConnect.ethereumGetAddress({
    bundle: new Array(count).fill(1).map((_, index) => ({
      path: `m/44'/60'/0'/0/${index}`,
      showOnTrezor: false,
    })),
  }).then((response: any) => {
    if (response.success) {
      return response.payload.map((item: any) => ({
        address: item.address,
        path: item.serializedPath,
      }));
    } else {
      throw new Error(
        `TrezorError ${response.payload.error}${response.payload.code}`
      );
    }
  });

  return result;
};

chrome.action.onClicked.addListener(() => {
  chrome.tabs.create({
    url: chrome.runtime.getURL("./index.html"),
  });
});

chrome.runtime.onMessage.addListener((message, _, sendResponse) => {
  if (message !== "trezor-test") {
    return;
  }

  console.log("Received message in service worker: ", message);

  fetchAddresses(2)
    .then((result) => {
      sendResponse(result);
    })
    .catch((error) => {
      console.log("failed to fetch addresses", error);
      sendResponse(error.message);
    });

  return true;
});
```

in my service worked, and then send this message from various locations, but the only result I have - `handshake failed` error.

![image](https://github.com/trezor/trezor-suite/assets/112621289/8a23e4fb-78fe-44c8-9935-21e8e224b0e2)


Also seems like I need to add 

```

  "permissions": ["tabs", "scripting"],

```

to manifest, which is a bit concerning TBH, but it's minor for now, just want to make it work :thinking: 

This is my test extension I'm using, just created separate [branch and PR](https://github.com/resetko-zeal/trezor-test-extension/pull/1/files) for this exercise

**Comment by mroz22** [comment]
'scripting' permission is needed to be able to establish communication between service worker and connect.trezor.io/9/popup.html. 
maybe there is a better way how to do it, or maybe there is a way how to limit this scripting permissions only for trezor.io domain?

**Comment by resetko-corp** [comment]
By the way, @karliatto @mroz22, are there any discord / telegram where we can work on this a bit closer? :)

**Comment by Hannsek** [comment]
We can create a new slack channel. Would it be ok for you?

**Comment by resetko-corp** [comment]
> We can create a new slack channel. Would it be ok for you?

sounds great :+1:

**Comment by Hannsek** [comment]
Please give us your email. You can send it to jan.setina@satoshilabs.com.

**Comment by karliatto** [comment]
I think this issue was solved by the release of https://www.npmjs.com/package/@trezor/connect-webextension

Feel free to re-open or open new issue if you feel otherwise.
