### ISSUE TITLE
Add receive section

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#99]
BTC (like)

- [x] Used addresses
- [x] Fresh addresses
- [x] + Show new addresses (20 max)

ETH & Ripple

- [x] Connect with the connect
- [ ] Add accounts
- [x] Show QR code

**Comment by slowbackspace** [comment]
Design for btc receive tab from the old wallet
<img width="693" alt="Screenshot 2019-08-26 at 16 56 10" src="https://user-images.githubusercontent.com/6961901/63700232-ba352880-c822-11e9-913a-6053518f840e.png">
<img width="882" alt="Screenshot 2019-08-26 at 16 56 24" src="https://user-images.githubusercontent.com/6961901/63700233-bacdbf00-c822-11e9-89d6-8a0bda89d2ff.png">
<img width="670" alt="Screenshot 2019-08-26 at 16 57 07" src="https://user-images.githubusercontent.com/6961901/63700234-bacdbf00-c822-11e9-838e-386e6059a853.png">
<img width="652" alt="Screenshot 2019-08-26 at 16 55 50" src="https://user-images.githubusercontent.com/6961901/63700236-bacdbf00-c822-11e9-835b-96c5f70c08d2.png">
<img width="686" alt="Screenshot 2019-08-26 at 16 56 01" src="https://user-images.githubusercontent.com/6961901/63700242-bb665580-c822-11e9-8417-7928552cc207.png">
