### ISSUE TITLE
Github issue template, support.trezor.io Invalid SSL certificate

### ISSUE THREAD

**Issue by GittyGitGitGitty** [trezor/trezor-suite#9901]
```
General support and product feedback
Please do not use this Github repository for technical support. Contact Trezor support directly or visit our community forum at forum.trezor.io.
```

When creating this issue, clicking for technical support links to support.trezor.io but the site won't connect because of Invalid SSL certificate.

![support trezor io](https://github.com/trezor/trezor-suite/assets/105609718/553e5cf2-78f3-4180-9777-38cb931aefc4)

**Comment by matejkriz** [comment]
@GittyGitGitGitty thanks for noticing, link fixed 👍
