### ISSUE TITLE
Improve the process for reproducing a (signed) suite-desktop AppImage

### ISSUE THREAD

**Issue by GittyGitGitGitty** [trezor/trezor-suite#9902]
Related to https://github.com/trezor/trezor-suite/issues/2687#issuecomment-1804913614

I've followed the build steps for suite-desktop (`yarn && yarn build:libs && yarn workspace @trezor/suite-desktop build:linux`) but this produces a dev build despite wanting a production build. Obviously, I can't sign a production build but I want an identical build to what Trezor's website releases - minus the signing (as do we all).

Is running a dev build as safe as production, in terms of potential debug symbols or debug related codepaths that aren't run in production? Will this dev build pull in a dev/debug version of firmware upon firmware update?

**Comment by matejkriz** [comment]
Hey @GittyGitGitGitty, 
`yarn workspace @trezor/suite-desktop build:linux` really gives you dev build, that is not exactly the same as production. The differences are minor - most visible is different app name but most important are:
- analytics reporting to different endpoint (but you can disable analytics completely)
- [secure message system ](https://github.com/trezor/trezor-suite/blob/develop/docs/features/message-system.md) is fetching config from different endpoint and can contain dev messages meant for testing and not production (basically it can show you weird banner on top of the app or disable coinjoin feature remotely)

But there is an easy way how to build the version same as production locally, you just have to set IS_CODESIGN_BUILD environment variable:

`IS_CODESIGN_BUILD="true" yarn workspace @trezor/suite-desktop build:linux`

That should produce build closest to production, just not signed.
