### ISSUE TITLE
Update MMKV & other libs for prod release

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#9903]
- [ ] Update MMKV
- [ ] Update react-native-skia
- [ ] reanimated

These changes are to be done over last release branch so we can release them alone without any changes from develop

**Comment by bosomt** [comment]
**QA OK**

tested on 23.11.1 release candidate
https://www.notion.so/satoshilabs/Smoke-test-mobile-app-23-11-x-c57c5c0899bd4af6848c8ebbf68e0e72?pvs=4
