### ISSUE TITLE
Register custom (trezorsuite:) protocol for opening suite app

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#991]
little experiment work was started in #694 
basically now we need a plan what to do with it.
ideas:
- handle suite custom protocol URI (eg: trezorsuite:action) for triggering the action from the web? for the start one action could be 'open' 
- <s>handle bitcoin URI format (bitcoin:address?amount=blabla) could open send tab
https://bitcoin.org/en/payment-processing-guide#bitcoin-uri</s> Moved to #3294

![Screen Recording 2019-10-17 at 15 31 15](https://user-images.githubusercontent.com/6961901/67018412-7e6c6000-f0fb-11e9-8586-739390b6de0c.gif)

**Comment by slush0** [comment]
Handling "bitcoin:" URIs is in requirements for Suite already and it is quite common interaction with wallets from the websites.

Regards the "suite:" handler, I think it is a good idea as already discussed with @szymonlesisz maybe year ago, because it can open Suite even if it has not been running on the background.

**Comment by slush0** [comment]
Probably suite:open should (?) be the only necessary action to be handled as the rest can go thru Connect API directly.

**Comment by tsusanka** [comment]
I have created a new issue for `bitcoin:` (#3294) and let's track here only our custom protocol `trezorsuite:` because the priorities are different.

In this issue we need to specify what kind of actions we want to support so I am assigning this to @matejzak because it needs a product spec.

**Comment by glacierbits** [comment]
All product-related questions tracked in #3294

**Comment by tomasklim** [comment]
Opened. 

- [x] Implement a featureless `trezorsuite:` uri handler which will only open the Trezor Suite app.

**Comment by tsusanka** [comment]
With the PR merged lets close again?

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.11.0 (5d1bc34fcbf5ed351a680893b6586cb8bbca8c08)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision fac4e2f157ca7d0c782b8a55175478e476ea7e28)
 - Transport: bridge 2.0.32
