### ISSUE TITLE
Trezor Suite asks you to enable passphrase when entering incorrect passphrase

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9919]
**Describe the bug**
Trezor Suite ask you to enable passphrase protection when entering incorrect passphrase

**Steps to reproduce:**
1. Add wallet
2. Enter different empty passphrase twice
3. Observe TS behavior 

**Info:**
 - Suite version: desktop 23.11.2 (8a61e6c12d84e2ead068702c02a49bb20d5ffaa7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.11.2 Chrome/116.0.5845.228 Electron/26.4.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2B1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="959" alt="Screenshot 2023-11-13 at 11 31 46" src="https://github.com/trezor/trezor-suite/assets/31506317/df22ac6e-0cf5-41a8-906c-65d13a927bde">
<img width="1097" alt="Screenshot 2023-11-13 at 11 31 37" src="https://github.com/trezor/trezor-suite/assets/31506317/72b8e495-46ba-4ebb-b566-51ff0bdabd84">

https://github.com/trezor/trezor-suite/assets/31506317/f6972e0f-4163-411f-8cbb-41cd44d9c1fc

**Comment by tomasklim** [comment]
old flow

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.11.0 (17bac171ecd870c4d76bb64c6ec5f8d69b333d4c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport
