### ISSUE TITLE
T2B1 promo in Suite

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#9936]
**Design:** [Figma](https://www.figma.com/file/pIibgxmxD0jrAa9UGJd9da/Neue-Desktop-1.5?type=design&node-id=11741%3A72491&mode=design&t=AskFmFwmFWRXcO5Z-1) 

**Spec:** 
After we haven't had any promo in Suite for a long time period, we can and should afford having one for the great event of launching a new hardware product after many years. Please implement it according to the design linked above.

A couple details:
- Placement: Dashboard
  - From the two design options, please use the lower placement under the graph, it matches the design better
- The banner should never be show if the users would connect a T2B1 (ideally even never after they would connect it once, as such it wouldn't be relevant for such users anymore)
- Please respect the breakpoints as designed and scale in between them, so it doesn't jump much when resizing the window. Always match the width of the rest of the elements (graph, transactions list, ...)
- Only the buttons should be clickable and they should also have our commonly used effects on hover to show the interactivity.
- The close (x) button should close the banner and ideally never show it again in that Suite instance (and after closing, there shouldn't remain an empty gap, the interface should close the gap to the state like if the banner never has been in the place)
- The Shop now button should link to: https://trezor.io/
- Please add an analytics event on both buttons
- "Get the next-generation of security today" will be in english only, untranslatable

**Comment by STew790** [comment]
**QA OK**

- banner present on dashboard
- banner is never shown again when TS3 is connected
- banner looks OK when resizing the window, always respects the width of the graph (other elements)
- only the buttons are clickable and they "dimm" on hover
- close button works correctly
- shop now button leads to t.io 
- text in banner is always in english

**Info:**
 - Suite version: desktop 23.12.1 (9ec6ac5438d7a952abcbbdc049bf729a47d4e039)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.12.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33
