### ISSUE TITLE
Enable RBF for exchange transactions in coinmarket

### ISSUE THREAD

**Issue by FreeWall** [trezor/trezor-suite#9938]
**Describe the bug**
Users are unable to bump fees for Exchange transaction made with BTC.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.12.1 (9ec6ac5438d7a952abcbbdc049bf729a47d4e039)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.12.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 1f693d3561c375661563970e066f678590abc19c)
 - Transport: BridgeTransport 2.0.33
