### ISSUE TITLE
version 23.11.2 on github is not available on the the official trezor webiste

### ISSUE THREAD

**Issue by paboman** [trezor/trezor-suite#9943]
version 23.11.2 on github is not available on the the official trezor webiste
on trezor website the last available version is 23.10.1

why is so ?

Trezor suite wants to update to 23.11.2 and kaspersky is telling that there is NO valid certificate for :
www.iuk33gxyzkx.com
and
www.7wpe74cljqeosxh7lfcc4e.com

**Comment by Hannsek** [comment]
I can see it is available: 
<img width="693" alt="image" src="https://github.com/trezor/trezor-suite/assets/57008159/0d67dbb6-65ad-4b14-9b2b-98d212578c11">

**Comment by bosomt** [comment]
Checked and latest release is linked and available on this url
https://github.com/trezor/trezor-suite/releases/download/v23.11.3/Trezor-Suite-23.11.3-mac-arm64.dmg
