### ISSUE TITLE
Version 23.11.2: crashes when starting on Linux (AppImage, Debian 12)

### ISSUE THREAD

**Issue by eribertomota** [trezor/trezor-suite#9945]
**Describe the bug**
Some minutes ago, Trezor Suite asked me for an update. After this, I got crashes when trying to start it (with or without the wallet connected via USB). Now, I am not able to start the software. I am a Debian Developer.

The app says: Render process terminated unexpectedly (reason: crashed). Please, see the screenshot attached.

The terminal says:
```

$ ./Trezor-Suite-23.11.2-linux-x86_64.AppImage 
(node:55027) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `trezor-suite --trace-deprecation ...` to show where the warning was created)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
2023-11-14T16:26:09.366Z - ERROR(content): Render process gone (reason: crashed)

$ ./Trezor-Suite-23.11.2-linux-x86_64.AppImage --trace-deprecation ...
(node:56298) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:202:11)
    at new Buffer (node:buffer:286:3)
    at /tmp/.mount_TrezorCSBrsM/resources/app.asar/dist/app.js:4:68813
    at /tmp/.mount_TrezorCSBrsM/resources/app.asar/dist/app.js:8:4162
    at /tmp/.mount_TrezorCSBrsM/resources/app.asar/dist/app.js:1:263
    at /tmp/.mount_TrezorCSBrsM/resources/app.asar/dist/app.js:8:6251
    at /tmp/.mount_TrezorCSBrsM/resources/app.asar/dist/app.js:1:263
    at /tmp/.mount_TrezorCSBrsM/resources/app.asar/dist/app.js:8:21647
    at /tmp/.mount_TrezorCSBrsM/resources/app.asar/dist/app.js:1:263
    at /tmp/.mount_TrezorCSBrsM/resources/app.asar/dist/app.js:8:28657
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
2023-11-14T16:31:03.951Z - ERROR(content): Render process gone (reason: crashed)
```

**Info:**

-   Remembered Wallet: is not possible to know
-   Suite Version: Trezor-Suite-23.11.2-linux-x86_64.AppImage
-   OS: Debian 12 Bookworm
-   Bridge: 2.0.27

**How to reproduce**
Simply start Trezor Suite on Debian.

Thanks!

![crash](https://github.com/trezor/trezor-suite/assets/6435502/eac2c3df-723f-412b-9c76-b5ffc97d5e8e)

**Comment by prusnak** [comment]
Can you try different Electron app on your system?

It seems your graphics drivers are not friendly to Electron:

```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

**Comment by eribertomota** [comment]
Hi @prusnak,

Electron is not available for Debian yet. Please, see here[1].

[1] https://bugs.debian.org/842420

**Comment by prusnak** [comment]
> Electron is not available for Debian yet. Please, see here[1].

There are thousands Electron apps distributed as AppImage out there. You can try for example this one: https://etcher.balena.io/#download-etcher or this one https://obsidian.md/download ...

**Comment by eribertomota** [comment]
> > Electron is not available for Debian yet. Please, see here[1].
> 
> There are thousands Electron apps distributed as AppImage out there. You can try for example this one: https://etcher.balena.io/#download-etcher or this one https://obsidian.md/download ...

Thanks. The both apps opening and working. The last version of Tresor was working fine too.

**Comment by eribertomota** [comment]
Do you need any specific test?

**Comment by eribertomota** [comment]
I remember now that I use losslesscut and it is an app using electron. I made a test now. It produces the same error message about libva error, but works fine (it produces videos).

**Comment by redmac68** [comment]
'+ 1

**Comment by eribertomota** [comment]
> '+ 1

Debian? Ubuntu? Version?

**Comment by redmac68** [comment]
LMDE6 (Debian 12)

**Comment by cebas** [comment]
Same here, but not graphics driver related:

```
$ ./Trezor-Suite-23.11.2-linux-x86_64.AppImage --trace-deprecation

(process:1008269): GLib-CRITICAL **: 02:00:11.871: g_file_test: assertion 'filename != NULL' failed
(node:1008300) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:202:11)
    at new Buffer (node:buffer:286:3)
    at /tmp/.mount_TrezorRs6Odl/resources/app.asar/dist/app.js:4:68813
    at /tmp/.mount_TrezorRs6Odl/resources/app.asar/dist/app.js:8:4162
    at /tmp/.mount_TrezorRs6Odl/resources/app.asar/dist/app.js:1:263
    at /tmp/.mount_TrezorRs6Odl/resources/app.asar/dist/app.js:8:6251
    at /tmp/.mount_TrezorRs6Odl/resources/app.asar/dist/app.js:1:263
    at /tmp/.mount_TrezorRs6Odl/resources/app.asar/dist/app.js:8:21647
    at /tmp/.mount_TrezorRs6Odl/resources/app.asar/dist/app.js:1:263
    at /tmp/.mount_TrezorRs6Odl/resources/app.asar/dist/app.js:8:28657
request-manager: connect ECONNREFUSED 127.0.0.1:33011
2023-11-15T05:00:21.051Z - ERROR(content): Render process gone (reason: crashed)

```

I had the previous version installed and allowed for the autoupdate. When the new version started, crash. 
I also downloaded the latest (23.11.2) from trezor site, which is identical, and the result was the same.
I also tried cleaning the caches at /home/me/.config/@trezor/suite-desktop/{Cache,Code Cache,DawnCache,GPUCache}, getting the same result.
I also have several electron and appimage apps running fine. Which includes previous suite version, of course.

Kubuntu 23.04
AMD CPU and AMD GPU

**Comment by ndeet** [comment]
+1 on an Ubuntu 22.10; previous versions worked without problem

**Comment by Hannsek** [comment]
Thanks for reporting. Looking into it. 👀

**Comment by bidonmegale** [comment]
same issue here on ubuntu 22.04

`./Trezor-Suite-23.11.2-linux-x86_64.AppImage 
(node:516427) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `trezor-suite --trace-deprecation ...` to show where the warning was created)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
`

`./Trezor-Suite-23.11.2-linux-x86_64.AppImage --trace-deprecation
(node:517473) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:202:11)
    at new Buffer (node:buffer:286:3)
    at /tmp/.mount_Trezore8kqQj/resources/app.asar/dist/app.js:4:68813
    at /tmp/.mount_Trezore8kqQj/resources/app.asar/dist/app.js:8:4162
    at /tmp/.mount_Trezore8kqQj/resources/app.asar/dist/app.js:1:263
    at /tmp/.mount_Trezore8kqQj/resources/app.asar/dist/app.js:8:6251
    at /tmp/.mount_Trezore8kqQj/resources/app.asar/dist/app.js:1:263
    at /tmp/.mount_Trezore8kqQj/resources/app.asar/dist/app.js:8:21647
    at /tmp/.mount_Trezore8kqQj/resources/app.asar/dist/app.js:1:263
    at /tmp/.mount_Trezore8kqQj/resources/app.asar/dist/app.js:8:28657
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`

**Comment by matejkriz** [comment]
It is an electron issue (I believe this one https://github.com/electron/electron/issues/40391), we will fix it by updating electron version. Working on releasing it. Sorry for the inconvenience, you can use [23.10.1](https://github.com/trezor/trezor-suite/releases/tag/v23.10.1) for now BUT BEWARE ⚠️  if you downgrade Suite from 23.11 to 23.10, local storage will be wiped so you will loose remembered wallets and Suite settings.

**Comment by prusnak** [comment]
We were able to replicate the problem internally and we are currently testing the potential fix.

**Comment by eribertomota** [comment]
> We were able to replicate the problem internally and we are currently testing the potential fix.

A good news. Thanks!

**Comment by chknlittle** [comment]
+1 having the same issue

> We were able to replicate the problem internally and we are currently testing the potential fix.

thanks for looking into it

**Comment by eribertomota** [comment]
23.11.3 working like a charm. Thanks!
