### ISSUE TITLE
Light bulb icon position in modal is broken in some cases

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#9947]
**Describe the bug**
In some cases we display light bulb icon in modals but the position is sometimes quite strange.

**How to reproduce**

1. Try to update firmware
2. Try different screen sizes when the modal for updating firmware is visible

**Expected behavior**
Icon placement is okey.

**Screenshots
![Fix device ready image](https://github.com/trezor/trezor-suite/assets/66002635/ec961502-c4cc-4717-af78-4ca354e8eb91)
![Fix device ready](https://github.com/trezor/trezor-suite/assets/66002635/1b692639-bc01-452d-ba93-c1002805390f)

**Additional context**
I was not going that deep in the cases so don't know exactly where it's broken (just provided an example). This need further investigation.

**Comment by dahaca** [comment]
It is misaligned in modals without a Header, so the ones which are not closable or with a `AbortButton`

**Comment by bosomt** [comment]
duplicity ? https://github.com/trezor/trezor-suite/issues/9571

**Comment by AdamSchinzel** [comment]
Thanks for pointing out
