### ISSUE TITLE
trezor suite connecting to a strange website without certificate 

### ISSUE THREAD

**Issue by paboman** [trezor/trezor-suite#9949]
I got this warning from Kaspersky Endpoint Protection Cloud which is warning me that:

tor.exe
executed from:
C:\Users\pabom\AppData\Local\Programs\Trezor Suite\resources\bin\tor
is reaching a website:
(www dot iuk33gxyzkx dot com)
without a valid certificate chain.

![Capture](https://github.com/trezor/trezor-suite/assets/17086550/9b2cd079-ade0-4005-b131-99e2a7d2e2d6)

**Comment by matejkriz** [comment]
Thank you for the report! We'll investigate. You're on Suite version 23.11.2, right?

**Comment by paboman** [comment]
> Thank you for the report! We'll investigate. You're on Suite version 23.11.2, right?

When Kaspersky noticed this behaviour I was on Trezor Suite 23.10.1

**Comment by matejkriz** [comment]
It's nothing suspicious, it's expected behaviour of Tor process and false positive from Kaspersky 👌  Anyone can run a tor relay and set the reverse record for the IP address to whatever name.
