### ISSUE TITLE
Implementation of SOL trade options in Suite

### ISSUE THREAD

**Issue by marek-andrsk** [trezor/trezor-suite#9953]
Implementation of SOL (only the native coin) trade. The tokens will require further refactor, so this will be implemented later (as part of the Polygon update).

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.1.0 (c74ef86d43ec51a9eb438d186edb46482275b4b8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 1f693d3561c375661563970e066f678590abc19c)
 - Transport: BridgeTransport 2.0.33
