### ISSUE TITLE
Add deprecation banner to Connect v8 popup

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#9969]
![image](https://github.com/trezor/trezor-suite/assets/57008159/217ea367-d3b0-485f-8c78-e9248a99db54)

details about size/colour/.. can be found [here](https://www.figma.com/file/63TRdbKaLqfnMylNIXRQyn/Connect?type=design&node-id=40-211&mode=design&t=rCGFPXM0fzZg75Jz-4).

**Comment by bosomt** [comment]
**QA OK**

tested at

https://trezor.github.io/connect-explorer/#/method/getPublicKey
