### ISSUE TITLE
webUSB connection not available in Android phone

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#9973]
**Describe the bug**
webUSB connection not available in Android.
Checked on multiple phones and multiple versions of Google Chrome
Desktop works as expected 

Desktop:

**Info:**
 - Suite version: web 23.11.2 (8a61e6c12d84e2ead068702c02a49bb20d5ffaa7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.3 regular (revision 297b2bade72c55033fc3c93c1da818c42b7f453d)
 - Transport: WebUsbTransport

**Comment by Hannsek** [comment]
Is this regression?

**Comment by sime** [comment]
Yes, web suite works in 23.10.1.

Console of production:
```
Uncaught ReferenceError: SharedWorker is not defined
    at iframe.460453007388324ce2b1.js:59:378033
    at iframe.460453007388324ce2b1.js:59:382494
    at iframe.460453007388324ce2b1.js:59:382498
```

**Comment by Hannsek** [comment]
@mroz22 can you take a look please?

**Comment by sime** [comment]
SharedWorker is not supported by Chrome for Android.

**Comment by mroz22** [comment]
in PR #9975

**Comment by bosomt** [comment]
**QA OK**

23.11.4 deployed on production and tested on multiple Android phones
