### ISSUE TITLE
Update Configure AWS credentials

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#9983]
[This is the last place](https://github.com/trezor/trezor-suite/pull/9961#discussion_r1394190936) which probably uses `node16` in `configure-aws-credentials@v1-node16`, check if it is ok or update it if there is newer version. In their repo, they have `aws-actions/configure-aws-credentials@v4` as an example

https://github.com/aws-actions/configure-aws-credentials

**Comment by vdovhanych** [comment]
Just simply update the action to the `aws-actions/configure-aws-credentials@v4` version. There shouldn't be any issues with it, I have it already on multiple repositories.
