### ISSUE TITLE
Device mutually exclusive access

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#9986]
There are some connect methods that need exclusive access to the device. If there is such method called, during its execution it is not possible access device with any other method. Since on mobile we do not use device locks on the same basis as desktop implementation do, we need to implement and mutually exclusive queue, that ensures that there are never two concurrent attempts to read or write the device memory.

Acceptance criteria:
- create a new package `suite-native/device-mutex` with a mutex queue implementation
- export only two functions for device access request (one of the prioritized, other unprioritized access)

**Comment by bosomt** [comment]
**QA OK**

- version 23.12.2 (656) 19c6638 - [develop] - Chore\/receive image btc cash (#10414)
- Android 13 - Nothing phone 1
