### ISSUE TITLE
There should not be grey circles around the icon "close"

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9997]
Close icon should not have circled background - look at the designs comparison:
![Screenshot 2023-11-17 at 11 16 10](https://github.com/trezor/trezor-suite/assets/84183817/b39545c7-45a6-4768-affc-674d32f986e9)

**Comment by bosomt** [comment]
**QA OK**

tested on Android 13 - Nothing phone 1
 23.11.1 (591)
f3c6929 - [develop] - Fix\/discovery fixes (#10061)
