### ISSUE TITLE
Icons are missing in opened switcher

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9998]
Opened switcher misses the related icon, look at the design comparison:

![Screenshot 2023-11-17 at 11 22 22](https://github.com/trezor/trezor-suite/assets/84183817/aafd5966-f96b-408b-97f1-23a0cc2b2596)

**Comment by bosomt** [comment]
**QA OK**

tested on Android 13 - Nothing phone 1
 23.11.1 (591)
f3c6929 - [develop] - Fix\/discovery fixes (#10061)
