### ISSUE TITLE
When the device is connected, icon should have "green" mark around it

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9999]
![Screenshot 2023-11-17 at 11 22 22](https://github.com/trezor/trezor-suite/assets/84183817/208f219d-1b1c-4a80-a6a8-54b941984a5b)

**Comment by bosomt** [comment]
**QA OK**

tested on Android 13 - Nothing phone 1
 23.11.1 (591)
f3c6929 - [develop] - Fix\/discovery fixes (#10061)
